project:
  type: website
  resources:
  - CNAME
  - .nojekyll
  render: 
    - index.qmd
    - liste.qmd
    - chapters.qmd
    - apparatus.qmd
    - byzantine_priority.qmd
    - byzantine_priority_es.qmd
    - collations/*.qmd
    - apparatus/*.qmd
    

website:
  title: "Greek New Testament Collations"
  favicon: logo.png
  back-to-top-navigation: true
  page-footer: "Version {{< var version >}}, data up-to-date as of {{< var listeupdated >}}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - liste.qmd
      - chapters.qmd
      - apparatus.qmd
      - byzantine_priority.qmd

bibliography: bibliography.bib

format:
  pdf:
    #documentclass: article
    #classoption: [landscape]
    sansfont: "Garamond Libre"
    mainfont: "Garamond Libre"
    papersize: a4
    mainfontoptions:
        - Numbers=Lowercase
    fontsize: 14pt
    include-in-header: preamble.tex
  #html:
  #  theme: [litera, styles/customs.scss]
  #  css: styles/styles.css
  #  toc: true
  #  fontsize: 21px
  #  header-includes: |
  #    <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,600;1,400;1,600&display=swap" type="text/css"/>


filters:
   - latex-environment
commands:
  apparatus-byzatine-primary-line: ByzPrimaryLine
  century-apparatus: CenturyApparatus
  apparatus-uncertain: ApparatusUncertain

#mainfont: "EB Garamond"
editor: visual

