---
format: html
editor: 
  markdown: 
    wrap: 72
---

# Third John

## Chapter 1

### Verse 1:1

[ο^**1**^ πρεσβυτερος γαιω^**2**^ τω^**3**^ αγαπητω^**4**^ ον εγω αγαπω
εν^**5**^ αληθεια^**6**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 6

**Number of witnesses that were taken into account in the collation: 6**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (3):
[[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
[[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
:::

1.  **ο\]** (5/6) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

2.  **πρεσβυτερος γαιω\]** (6/6) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

3.  **τω\]** (5/6) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   τωι:
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

4.  **αγαπητω\]** (5/6) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   αγαπητωι:
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

5.  **ον εγω αγαπω εν\]** (6/6) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

6.  **αληθεια\]** (5/6) *unan.* +
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   αληθια:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

### Verse 1:2

[αγαπητε^**1**^ περι παντων^**2**^ ευχομαι^**3**^ σε^**4**^
ευοδουσθαι^**5**^ και υγιαινειν καθως ευοδουται σου η
ψυχη^**6**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

**Number of witnesses that were taken into account in the collation: 7**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (5):
[[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
[[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
[[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
[[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
:::

1.  **αγαπητε\]** (6/7) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}γαπητε:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

2.  **περι παντων\]** (7/7) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

3.  **ευχομαι\]** (5/7) *unan.* +

    -   ευ[\[?\]]{.apparatus-uncertain}ομαι:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    -   ευχομε:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

4.  **σε\]** (7/7) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

5.  **ευοδουσθαι\]** (6/7) *unan.* +
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   ευοδουσθε:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

6.  **και υγιαινειν καθως ευοδουται σου η ψυχη\]** (7/7) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

### Verse 1:3

[εχαρην^**1**^ γαρ^**2**^ •^**3**^ λιαν^**4**^ ερχομενων^**5**^ αδελφων
και^**6**^ μαρτυρουντων^**7**^ σου^**8**^ τη^**9**^ αληθεια
καθως^**10**^ •^**11**^ συ^**12**^ εν αληθεια^**13**^ •^**14**^
περιπατεις^**15**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (1):
[[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 8**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **εχαρην\]** (7/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   εχαριν:
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}

2.  **γαρ\]** (7/8)
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

3.  **•\]** (6/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   λειαν:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

4.  **λιαν\]** (7/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

5.  **ερχομενων\]** (7/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}ρχομενων:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

6.  **αδελφων και\]** (8/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

7.  **μαρτυρουντων\]** (6/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   μαρτυρουν:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

8.  **σου\]** (8/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

9.  **τη\]** (7/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   τηι:
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

10. **αληθεια καθως\]** (8/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

11. **•\]** (7/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   και:
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

12. **συ\]** (6/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

13. **εν αληθεια\]** (8/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

14. **•\]** (7/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   περι:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

15. **περιπατεις\]** (7/8)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   πατεις:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

### Verse 1:4

[μειζοτεραν^**1**^ τουτων^**2**^ •^**3**^ ουκ^**4**^ •^**5**^ εχω^**6**^
χαραν^**7**^ ινα ακουω τα εμα τεκνα εν^**8**^ •^**9**^ αληθεια
περιπατουντα^**10**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (2):
[[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
[[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 9**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (3):
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
[[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
[[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **μειζοτεραν\]** (7/9) *unan.* +
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   μειζονα:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    -   μιζοτεραν:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

2.  **τουτων\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

3.  **•\]** (8/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   ταυτης:
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

4.  **ουκ\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

5.  **•\]** (7/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   εχων:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

6.  **εχω\]** (8/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

7.  **χαραν\]** (7/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   χαριν:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

8.  **ινα ακουω τα εμα τεκνα εν\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

9.  **•\]** (6/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   τη:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

10. **αληθεια περιπατουντα\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

### Verse 1:5

[αγαπητε πιστον ποιεις ο^**1**^ εαν^**2**^ εργαση^**3**^ εις^**4**^
τους^**5**^ αδελφους και^**6**^ εις^**7**^ τους^**8**^ •^**9**^
ξενους^**10**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (1):
[[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 8**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (2):
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
[[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **αγαπητε πιστον ποιεις ο\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

2.  **εαν\]** (6/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   αν:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

3.  **εργαση\]** (5/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   εργαζη:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

4.  **εις\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

5.  **τους\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

6.  **αδελφους και\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

7.  **εις\]** (4/8) *unan.* +
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

8.  **τους\]** (4/8) *unan.* +
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

9.  **•\]** (3/8) *unan.* +
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   τουτο:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

10. **ξενους\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

### Verse 1:6

[οι^**1**^ εμαρτυρησαν σου^**2**^ τη^**3**^ •^**4**^ •^**5**^
αγαπη^**6**^ ενωπιον εκκλησιας^**7**^ •^**8**^ ους^**9**^ καλως ποιησεις
προπεμψας αξιως του θεου^**10**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (1):
[[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 8**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (4):
[[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
[[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
[[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
:::

::: {.callout-warning collapse="true" icon="false"}
## *Nomina sacra* or abbreviations

Please note that one or more of the manuscripts contains *nomina sacra*
which have been spelled out by our automated algorithm. This process is
very accurate, but occasional mistakes can happen, especially with
obscure or uncommon *nomina sacra*. In case of doubt about the actual
reading of a *nomen sacrum*, please consult the original transcripts or
facsimiles.
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **οι\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   ο:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

2.  **εμαρτυρησαν σου\]** (8/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

3.  **τη\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   τηι:
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

4.  **•\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   αληθεια:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

5.  **•\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   και:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

6.  **αγαπη\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   αγαπηι:
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

7.  **ενωπιον εκκλησιας\]** (8/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

8.  **•\]** (6/8) *unan.* +
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   ου:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

9.  **ους\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

10. **καλως ποιησεις προπεμψας αξιως του θεου\]** (8/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

### Verse 1:7

[υπερ^**1**^ •^**2**^ γαρ του ονοματος^**3**^ •^**4**^ εξηλθον^**5**^
μηδεν λαμβανοντες^**6**^ •^**7**^ απο των^**8**^
εθνων^**9**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (1):
[[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 8**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (2):
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
[[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **υπερ\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

2.  **•\]** (7/8) *unan.* +
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   γαρ:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

3.  **γαρ του ονοματος\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

4.  **•\]** (6/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   αυτου:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

5.  **εξηλθον\]** (6/8) *unan.* +
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   εξηλθαν:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

6.  **μηδεν λαμβανοντες\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

7.  **•\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   λαβοντες:
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

8.  **απο των\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

9.  **εθνων\]** (3/8) *unan.* +
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   εθνικων:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

### Verse 1:8

[ημεις ουν^**1**^ οφειλομεν^**2**^ απολαμβανειν^**3**^ •^**4**^ τους
τοιουτους ινα συνεργοι^**5**^ •^**6**^ γινωμεθα^**7**^ τη^**8**^
αληθεια^**9**^ •^**10**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (3):
[[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
[[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
[[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation:
10**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (1):
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **ημεις ουν\]** (10/10) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

2.  **οφειλομεν\]** (7/10) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   οφιλομεν:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

3.  **απολαμβανειν\]** (4/10) *unan.* +
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

4.  **•\]** (3/10) *unan.* +
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   υπολαμβανειν:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    -   υπολαμβανιν:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

5.  **τους τοιουτους ινα συνεργοι\]** (10/10) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

6.  **•\]** (7/10) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   γεινωμεθα:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

7.  **γινωμεθα\]** (8/10) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

8.  **τη\]** (7/10) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   τηι:
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    -   της:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

9.  **αληθεια\]** (4/10) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   αληθειαι:
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    -   αληθειας:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    -   εκκλησια:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

10. **•\]** (9/10) *unan.* +
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   αληθια:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

### Verse 1:9

[εγραψα^**1**^ •^**2**^ •^**3**^ τη^**4**^ εκκλησια^**5**^ αλλ ο
φιλοπρωτευων αυτων^**6**^ •^**7**^ •^**8**^ διοτρεφης^**9**^ •^**10**^
•^**11**^ ουκ επιδεχεται ημας^**12**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (2):
[[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
[[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 9**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (1):
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **εγραψα\]** (8/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

2.  **•\]** (5/9) *unan.* +
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   αν:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    -   εγραψας:
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

3.  **•\]** (4/9) *unan.* +
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   τι:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

4.  **τη\]** (7/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

    -   τηι:
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

5.  **εκκλησια\]** (7/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

    -   εκκλησιαι:
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

6.  **αλλ ο φιλοπρωτευων αυτων\]** (9/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

7.  **•\]** (8/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   ο:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

8.  **•\]** (8/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   ̔:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

9.  **διοτρεφης\]** (8/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   τρε:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

10. **•\]** (8/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   ́:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

11. **•\]** (8/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   φης:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

12. **ουκ επιδεχεται ημας\]** (9/9) *unan.* +
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

### Verse 1:10

[δια τουτο^**1**^ εαν^**2**^ ελθω υπομνησω^**3**^ αυτου^**4**^ τα εργα
α^**5**^ •^**6**^ •^**7**^ ποιει^**8**^ •^**9**^ •^**10**^ λογοις
πονηροις^**11**^ φλυαρων^**12**^ ημας και μη^**13**^ αρκουμενος^**14**^
•^**15**^ επι τουτοις ουτε αυτος^**16**^ επιδεχεται^**17**^ τους
αδελφους και τους βουλομενους^**18**^ •^**19**^ κωλυει και^**20**^
εκ^**21**^ της εκκλησιας
εκβαλλει^**22**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (1):
[[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 8**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (2):
[[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
[[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **δια τουτο\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

2.  **εαν\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   αν:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

3.  **ελθω υπομνησω\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

4.  **αυτου\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   αυτους:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

5.  **τα εργα α\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

6.  **•\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   ̓̀:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

7.  **•\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   ν:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

8.  **ποιει\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   ει:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

9.  **•\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   ̓́:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

10. **•\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   η:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

11. **λογοις πονηροις\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

12. **φλυαρων\]** (7/8) *unan.* +
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   φλοιαρων:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

13. **ημας και μη\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

14. **αρκουμενος\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   αρκου:
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}

15. **•\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   μενος:
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}

16. **επι τουτοις ουτε αυτος\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

17. **επιδεχεται\]** (5/8) *unan.* +
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   επιδεχετε:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    -   υποδεχεται:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

18. **τους αδελφους και τους βουλομενους\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

19. **•\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   επιδεχομενους:
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

20. **κωλυει και\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

21. **εκ\]** (6/8) *unan.* +
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

22. **της εκκλησιας εκβαλλει\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

### Verse 1:11

[αγαπητε^**1**^ μη^**2**^ •^**3**^ μιμου^**4**^ το κακον αλλα το αγαθον
ο αγαθοποιων εκ του θεου εστιν ο^**5**^ •^**6**^ κακοποιων ουχ^**7**^
•^**8**^ εωρακεν^**9**^ τον
θεον^**10**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 7

Manuscripts *included twice* due to having corrected hands (1):
[[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 8**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (3):
[[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
[[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
[[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
:::

::: {.callout-warning collapse="true" icon="false"}
## *Nomina sacra* or abbreviations

Please note that one or more of the manuscripts contains *nomina sacra*
which have been spelled out by our automated algorithm. This process is
very accurate, but occasional mistakes can happen, especially with
obscure or uncommon *nomina sacra*. In case of doubt about the actual
reading of a *nomen sacrum*, please consult the original transcripts or
facsimiles.
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **αγαπητε\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   αγαπ[\[?\]]{.apparatus-uncertain}τε:
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}

2.  **μη\]** (8/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

3.  **•\]** (6/8) *unan.* +
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   μειμου:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

4.  **μιμου\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

5.  **το κακον αλλα το αγαθον ο αγαθοποιων εκ του θεου εστιν ο\]** (8/8)
    *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

6.  **•\]** (7/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   δε:
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}

7.  **κακοποιων ουχ\]** (8/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

8.  **•\]** (6/8) *unan.* +
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   εορακεν:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

9.  **εωρακεν\]** (3/8) *unan.* +

    -   εωρακε:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

10. **τον θεον\]** (8/8) *unan.* +
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

### Verse 1:12

[δημητριω^**1**^ μεμαρτυρηται^**2**^ υπο^**3**^ παντων^**4**^ και^**5**^
υπ^**6**^ αυτης^**7**^ της^**8**^ •^**9**^ αληθειας^**10**^ και^**11**^
ημεις^**12**^ δε^**13**^ μαρτυρουμεν^**14**^ και^**15**^ οιδατε^**16**^
•^**17**^ οτι^**18**^ η^**19**^ μαρτυρια^**20**^ ημων^**21**^
αληθης^**22**^ εστιν^**23**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 9

Manuscripts *ignored* due to being too fragmentary (2):
[[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
[[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

Manuscripts *included twice* due to having corrected hands (2):
[[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
[[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 9**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (2):
[[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
[[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **δημητριω\]** (9/9) *unan.* +
    [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

2.  **μεμαρτυρηται\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

3.  **υπο\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

4.  **παντων\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}ν:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

5.  **και\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

6.  **υπ\]** (8/9) *unan.* +
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   υπο:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

7.  **αυτης\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

8.  **της\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}μ[\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   [\[?\]]{.apparatus-uncertain}ς:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}

9.  **•\]** (7/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

10. **αληθειας\]** (6/9) *unan.* +
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   {.:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   αληθιας:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

11. **και\]** (8/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   unclear:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

12. **ημεις\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   }:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

13. **δε\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

14. **μαρτυρουμεν\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   {.:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

15. **και\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   unclear:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

16. **οιδατε\]** (4/9) *unan.* +
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   }:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

17. **•\]** (4/9) *unan.* +
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}ς:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
    -   οιδας:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

18. **οτι\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

19. **η\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

20. **μαρτυρια\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

21. **ημων\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

22. **αληθης\]** (9/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

23. **εστιν\]** (8/9) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[*20002^\*^(V)?*](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

    -   εστι:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[10074(VII)](https://www.gntcollations.com/collations/10074.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

### Verse 1:13

[πολλα^**1**^ ειχον^**2**^ γραφειν^**3**^ •^**4**^ •^**5**^ αλλ^**6**^
ου^**7**^ θελω^**8**^ δια^**9**^ μελανος^**10**^ και^**11**^
καλαμου^**12**^ •^**13**^ σοι^**14**^
γραψαι^**15**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 8

Manuscripts *ignored* due to being too fragmentary (1):
[[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

Manuscripts *included twice* due to having corrected hands (1):
[[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 8**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-tip collapse="true" icon="false"}
## Unanimous group

Manuscripts that attest a verse identical with Byz^RP^, or 'unanimous'
group (1):
[[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **πολλα\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}λλα:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

2.  **ειχον\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   ειχο[\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

3.  **γραφειν\]** (3/8) *unan.* +
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

4.  **•\]** (2/8) *unan.* +
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   γραψαι:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

5.  **•\]** (2/8) *unan.* +
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   σοι:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

6.  **αλλ\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   αλλα:
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

7.  **ου\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   ουκ:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

8.  **θελω\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   εβουληθην:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}

9.  **δια\]** (9/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

10. **μελανος\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   μ[\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

11. **και\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

12. **καλαμου\]** (7/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}λαμου:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   καλαμω:
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}

13. **•\]** (5/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   γραφειν:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

14. **σοι\]** (8/8) *unan.* +
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

15. **γραψαι\]** (3/8) *unan.* +
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[*30424^\*^(XI)?*](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

    -   γραφειν:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    -   *either missing or lacuna*:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

### Verse 1:14

[ελπιζω^**1**^ δε^**2**^ ευθεως^**3**^ •^**4**^ ιδειν^**5**^ σε^**6**^
και^**7**^ στομα^**8**^ •^**9**^ προς^**10**^ στομα^**11**^ •^**12**^
λαλησομεν^**13**^ ειρηνη^**14**^ σοι^**15**^ ασπαζονται^**16**^
σε^**17**^ οι^**18**^ φιλοι^**19**^ ασπαζου^**20**^ τους^**21**^
φιλους^**22**^ κατ^**23**^
ονομα^**24**^]{.apparatus-byzatine-primary-line}

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 8

Manuscripts *ignored* due to being too fragmentary (1):
[[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

Manuscripts *included twice* due to having corrected hands (2):
[[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
[[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 9**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

::: {.callout-important collapse="true" icon="false"}
## Potentially inaccurate

One or more of the witnesses included in the collation are corrected.
Due to the limitations of the TEI-XML format, it is not possible to
automatically reconstruct the corrected hand perfectly. For this reason,
the apparatus may display inaccuracies. For example, let the text of a
manuscript be πολλα ειχον γραφειν [γραψαι]{.corr} (γραψαι is the
correction). In this case the uncorrected hand is clearly πολλα ειχον
γραφειν. The *corrected* hand, however, can be reconstructed by the
computer as either πολλα ειχον γραφειν γραψαι or πολλα ειχον γραψαι. The
decision as to the appropriate reconstruction must be made by a human
expert. This algorithmic collation includes both the corrected words and
the corrections in the corrected hands (thus, πολλα ειχον γραφειν γραψαι
instead of πολλα ειχον γραψαι in the example), but this may lead to
imperfect witness counts if the algorithmic reconstruction is wrong. Due
to this we advise the reader to consult the individual collations by
clicking on the manuscript's number or refer to the original transcripts
or facsimiles.

The corrected hands in the apparatus have been marked with a ? symbol in
order to highlight this uncertainty.
:::

1.  **ελπιζω\]** (9/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}ιζω:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

2.  **δε\]** (10/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

3.  **ευθεως\]** (9/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   ευθε[\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

4.  **•\]** (6/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   σε:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

5.  **ιδειν\]** (9/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

6.  **σε\]** (6/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

7.  **και\]** (9/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}ι:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

8.  **στομα\]** (10/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

9.  **•\]** (8/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

    -   προ:
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

10. **προς\]** (9/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

11. **στομα\]** (9/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

12. **•\]** (7/9)
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}σωμεν:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   λαλησαμεν:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

13. **λαλησομεν\]** (8/9)
    [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

    -   *either missing or lacuna*:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

14. **ειρηνη\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

15. **σοι\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

16. **ασπαζονται\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

17. **σε\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

18. **οι\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

19. **φιλοι\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

20. **ασπαζου\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

21. **τους\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

22. **φιλους\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

23. **κατ\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

24. **ονομα\]** (0/9)

    -   *either missing or lacuna*:
        [[*20001^\*^(IV)?*](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[*20003^\*^(IV)?*](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}

### Verse 1:15

**This verse is not present in Byz^RP^**

::: {.callout-note collapse="true" icon="false"}
## Witness counts

Number of manuscripts that contain this verse: 8

Manuscripts *ignored* due to being too fragmentary (1):
[[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

**Number of witnesses that were taken into account in the collation: 7**

(The total number of witnesses is calculated as the total manuscripts
minus the fragmentary manuscripts plus the corrected hands.)
:::

1.  **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   ειρηνη:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

2.  **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   σοι:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

3.  **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}παζονται:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   ασπαζονται:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

4.  **•\]** (0/7)

    -   σε:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

5.  **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   οι:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

6.  **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   αδελφοι:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    -   φιλοι:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

7.  **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}σπαζου:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   ασπαζου:
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    -   ασπασαι:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}

8.  **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}ς:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   τους:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

9.  **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   αδελφους:
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    -   φιλους:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}

10. **•\]** (6/7)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   [\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   σου:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

11. **•\]** (1/7)
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}

    -   κατ:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}
    -   κατα:
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}

12. **•\]** (0/7)

    -   [\[?\]]{.apparatus-uncertain}νο[\[?\]]{.apparatus-uncertain}:
        [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    -   ονομα:
        [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
        [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
        [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
        [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
        [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
        [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

13. **•\]** (7/7)
    [[20001(IV)](https://www.gntcollations.com/collations/20001.html)]{.apparatus-manuscript-link}
    [[20002(V)](https://www.gntcollations.com/collations/20002.html)]{.apparatus-manuscript-link}
    [[20003(IV)](https://www.gntcollations.com/collations/20003.html)]{.apparatus-manuscript-link}
    [[20044(X)](https://www.gntcollations.com/collations/20044.html)]{.apparatus-manuscript-link}
    [[20251(VI)](https://www.gntcollations.com/collations/20251.html)]{.apparatus-manuscript-link}
    [[30424(XI)](https://www.gntcollations.com/collations/30424.html)]{.apparatus-manuscript-link}
    [[30630(XIII)](https://www.gntcollations.com/collations/30630.html)]{.apparatus-manuscript-link}

    -   αμην:
        [[20020(IX)](https://www.gntcollations.com/collations/20020.html)]{.apparatus-manuscript-link}
