---
title: "Collation of Byz^RP^ vs 20022 (22)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 22 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20022).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 22                                   	| λογος                              	|
| 22 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 22 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 22               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 22                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 22 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 22                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 5

[και]{.greek-omitted} [απηλθεν]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δεκαπολει]{.greek-omitted} οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς [επ]{.greek-omitted} [προς]{.greek-added} αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων [αυτον]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} πιπτει [προς]{.greek-omitted} [παρα]{.greek-added} τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μο[υ]{.greek-supplied} εσχατω[ς]{.unclear} [εχει]{.greek-supplied} ινα ελθ[ων]{.greek-supplied} [επιθης]{.greek-omitted} [[ε]{.greek-supplied}πειθης]{.greek-added} [αυτη]{.greek-supplied} τας χειρας οπως σωθη και [ζ]{.unclear}ησεται[5:23]{.aside}

και απηλθεν μετ [αυ]{.greek-added} [αυτου]{.greek-omitted} [του]{.greek-added} και ηκολουθει αυτω οχλος πολυς και συ[ν]{.unclear}εθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δω[δ]{.greek-supplied}[ε]{.unclear}κα[5:25]{.aside}

[και]{.greek-omitted} [πολλα]{.greek-omitted} [ποπλλα]{.greek-added} [πα]{.greek-supplied}[θ]{.unclear}ουσα υπο [πολλ]{.greek-supplied}ων ιατρων [και]{.greek-supplied} [δα]{.greek-supplied}[π]{.unclear}ανησα[σα]{.greek-supplied} [τα]{.greek-supplied} [π]{.greek-supplied}αρ αυτη[ς]{.unclear} [π]{.unclear}αντα και [μ]{.unclear}η[δε]{.greek-supplied}ν ωφελ[η]{.unclear}θει[σ]{.unclear}α αλλα μαλλ[ο]{.unclear}ν εις το [χειρον]{.greek-omitted} [χιρο[ν]{.unclear}]{.greek-added} ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα [εν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [εις]{.greek-added} [τον]{.greek-added} [οχλον]{.greek-added} οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

ελεγεν γαρ [ε[ν]{.unclear}]{.greek-added} [εαυτη]{.greek-added} οτι καν των ιματιων αυτου [αψωμαι]{.greek-omitted} [σωθησομαι]{.greek-omitted} [αψωμε]{.greek-added} [σωθη]{.greek-added} [σομε]{.greek-added}[5:28]{.aside}

και [ευθεως]{.greek-omitted} [ευ[θ]{.unclear}ες]{.greek-added} εξηρ[α]{.unclear}νθη [η]{.unclear} π[ηγη]{.unclear} [τ]{.unclear}ου αιματος αυτης και εγνω τω σωματι οτι [ιαται]{.greek-omitted} [ιατε]{.greek-added} απο της μαστιγος [αυτης]{.greek-added}[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και [ελεγον]{.greek-omitted} [λεγ[ου]{.unclear}σιν]{.greek-added} αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβ[η]{.unclear}θεισα και τρεμουσα [ειδυια]{.greek-omitted} [ο]{.greek-omitted} [γεγονεν]{.greek-omitted} [ηδυεια]{.greek-added} [το]{.greek-added} [γεγονος]{.greek-added} επ αυτη ηλθεν και προσεπεσεν αυτω και ειπεν αυτω πασαν την [α]{.greek-added} [αληθειαν]{.greek-omitted} [ληθειαν]{.greek-added}[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου σεσωκεν σε [υπαγε]{.greek-omitted} [πορευου]{.greek-added} εις ειρηνην και [ισθι]{.greek-omitted} [εισθει]{.greek-added} υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου απεθανεν τι [ετι]{.greek-omitted} σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} [ακουσας]{.greek-added} ευθεως [ακουσας]{.greek-omitted} τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω συνακολουθησαι ει μη πετρον και ιακωβον και ιωαννην τον αδελφον ιακ[ω]{.unclear}βου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και [θεωρει]{.greek-omitted} [θεωρι]{.greek-added} θορυβον [και]{.greek-added} κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβισθαι]{.greek-added} και [κλαιετε]{.greek-omitted} [κλαιεται]{.greek-added} το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον [ανακειμενον]{.greek-omitted} [ανακιμενον]{.greek-added}[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εσ]{.greek-added} [εστιν]{.greek-omitted} [τιν]{.greek-added} [μεθηρμηνευομενον]{.greek-added} [μεθερμηνευομενον]{.corr} το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και [περιεπατει]{.greek-omitted} [περιεπατι]{.greek-added} ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστιλατο]{.greek-added} αυτοις πολλα ινα μηδεις γνω τουτο και ειπεν δοθηναι αυτη [φαγειν]{.greek-omitted} [φαγιν]{.greek-added}[5:43]{.aside}

### Chapter 6

και εξηλθεν [εκειθεν]{.greek-omitted} [εκιθεν]{.greek-added} και ηλθεν εις την πατριδα αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} [εξεπλησσοντο]{.greek-omitted} [εξεπλησ]{.greek-added} [σοντο]{.greek-added} λεγοντες ποθεν τουτω ταυτα και τις η σοφια η δοθεισα αυτω και [αι]{.greek-added} δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο τεκτων ο [υιος]{.greek-abbr} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

ελεγεν δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ εστιν προφητης ατιμος ει μη εν τη [πατριδι]{.greek-omitted} [πατριδει]{.greek-added} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσεν]{.greek-added} [αυτου]{.greek-added} και εν τη [οικια]{.greek-omitted} [οικεια]{.greek-added} αυτου[6:4]{.aside}

και ουκ [ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} εκει ουδεμιαν [δυναμιν]{.greek-omitted} [δυναμειν]{.greek-added} ποιησαι ει μη ολιγοις αρρωστοις [επιθεις]{.greek-omitted} [επειθεις]{.greek-added} τας χειρας εθεραπευσεν[6:5]{.aside}

και εθαυμαζεν δια την απιστιαν αυτων και περιηγεν τας κωμας κυ[κλ]{.unclear}ω διδασκων[6:6]{.aside}

και [προσκαλειται]{.greek-omitted} [προσκαλιται]{.greek-added} τους δωδεκ[α]{.unclear} και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των ακαθαρτων[6:7]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγιλεν]{.greek-added} αυτοις ινα μηδεν [αιρωσιν]{.greek-omitted} [ερωσιν]{.greek-added} εις οδον ει μη ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους [σανδαλια]{.greek-omitted} [σανδαλεια]{.greek-added} και μη [ενδυσησθε]{.greek-omitted} [ενδεδυσθαι]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε [εκειθεν]{.greek-omitted} [εκιθεν]{.greek-added}[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι [εκειθεν]{.greek-omitted} [εκιθεν]{.greek-added} εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις [μ]{.unclear}αρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η γομορροις εν ημερα κρισεως η τη πολ[ε]{.unclear}ι εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησουσιν]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και [ηλειφον]{.greek-omitted} [ηλιφον]{.greek-added} ελαιω πολλους αρρωστους και [εθεραπευον]{.greek-omitted} [εθεραπευοντο]{.greek-added}[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυ[ν]{.unclear}[α]{.greek-supplied}μεις [ενεργουσειν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω απεκεφαλισα ιωαννην ουτος εστιν αυτος ηγερθη [εκ]{.greek-omitted} [απο]{.greek-added} [των]{.greek-added} νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης [αποστειλας]{.greek-omitted} [αποστιλας]{.greek-added} εκρατησεν τον ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο ιωαννης τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας [ενειχεν]{.greek-omitted} [ενιχεν]{.greek-added} αυτω και ηθελεν αυτον [αποκτειναι]{.greek-omitted} [αποκτιναι]{.greek-added} και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβιτο]{.greek-added} τον ιωαννην [ειδως]{.greek-omitted} [ιδως]{.greek-added} αυτο[ν]{.unclear} ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου [δειπνον]{.greek-omitted} [διπνον]{.greek-added} εποιει τοις μεγιστασιν αυτου και τοις [χιλιαρχοις]{.greek-omitted} [χιλειαρχοις]{.greek-added} και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις [συνανακειμενοις]{.greek-omitted} [συνανακιμενοις]{.greek-added} [ει]{.greek-added} [ειπεν]{.greek-omitted} [πεν]{.greek-added} ο βασιλευς τω κορασιω [αιτησον]{.greek-omitted} [αιτησε]{.greek-added} με ο εα[ν]{.unclear} [θελης]{.greek-omitted} [θελεις]{.greek-added} και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν [με]{.greek-omitted} αιτηση[ς]{.unclear} δωσω σοι εως [ημισους]{.greek-omitted} [ημισυ]{.greek-added} της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι [αιτησομαι]{.greek-omitted} [αιτησωμε]{.greek-added} η δε ειπεν την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα [δος]{.greek-added} μοι [δως]{.greek-omitted} εξαυτης επι [πινακι]{.greek-omitted} [πινακει]{.greek-added} την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους [συνανακειμενους]{.greek-omitted} [συνανακιμενους]{.greek-added} ουκ ηθελησεν [αθετησαι]{.greek-added} αυτην [αθετησαι]{.greek-omitted}[6:26]{.aside}

και ευθεως [αποστειλας]{.greek-omitted} [αποστιλας]{.greek-added} ο βασιλευς σπ[ε]{.unclear}κουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι [πινακι]{.greek-omitted} [πινακει]{.greek-added} και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν [μνημειω]{.greek-omitted} [μνημιω]{.greek-added}[6:29]{.aside}

και [συναγονται]{.greek-omitted} [συναγον]{.greek-added} [ται]{.greek-added} οι αποστολοι προς τον [ιησουν]{.greek-abbr} και [απηγγειλαν]{.greek-omitted} [απηγγιλαν]{.greek-added} αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε [υμεις]{.greek-omitted} [υμις]{.greek-added} αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυσασθαι]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και απηλθον εις ερημον τοπον [εν]{.greek-added} τω πλοιω κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ιδεν]{.greek-added} [οχλον]{.greek-added} πολυν [οχλον]{.greek-omitted} και [εσπλαγχνισθη]{.greek-omitted} [εσπλανχνισθη]{.greek-added} επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης [προσελθοντες]{.greek-omitted} [προσηλθον]{.greek-added} αυτω οι μαθηται αυτου [λεγουσιν]{.greek-omitted} [λεγοντες]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας [αγορασωσιν]{.greek-omitted} [αγορασωσειν]{.greek-added} εαυτοις αρτους τι γαρ [φαγωσιν]{.greek-omitted} [φαγουσιν]{.greek-added} ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις [υμεις]{.greek-omitted} [υμις]{.greek-added} φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν [διακοσιων]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} αρτους και [δωμεν]{.greek-omitted} [δωσωμεν]{.greek-added} αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και [ιδετε]{.greek-omitted} [ειδετε]{.greek-added} και γνοντες λεγουσιν [αυτω]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και [ανεπεσον]{.greek-omitted} [ανεπεσαν]{.greek-added} πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον ουρανον ευλογησεν και κατεκλασεν τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας εμερισεν πασιν[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους [πεντακισχιλιοι]{.greek-omitted} [πεντακισχειλιοι]{.greek-added} ανδρες[6:44]{.aside}

και ευθεως ηναγκασεν τους μαθητας αυτου εμβηναι εις το πλοιον και [προαγειν]{.greek-omitted} [προαγιν]{.greek-added} [αυτον]{.greek-added} εις το περαν προς βηθσαιδαν εως αυτος απολυση τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσε[υ]{.unclear}ξασθαι[6:46]{.aside}

[και]{.greek-omitted} οψιας [δε]{.greek-added} γενομενης ην το πλοιον εν μεσω της θαλα[σ]{.unclear}σης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω [ελαυνειν]{.greek-omitted} [ελαυνιν]{.greek-added} ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον [ειδον]{.greek-omitted} [ιδον]{.greek-added} και εταραχθησαν και ευθεως ελαλησεν μετ αυτων [ο]{.greek-added} [ι[ς]{.unclear}]{.greek-added} και λεγει αυτοις θαρσειτε εγω ειμι μη [φοβεισθε]{.greek-omitted} [φοβισθε]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις τ[ο]{.unclear} πλοιον και εκοπασεν ο ανεμος και λιαν [εκπερισσου]{.greek-omitted} εν εαυτοις [ε[κ]{.unclear}]{.greek-added} [περισσου]{.greek-added} εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ αυτων η καρδια πεπ[ω]{.unclear}ρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρεθ]{.greek-added} και [προσωρμισθησαν]{.greek-omitted} [προσορμισθησαν]{.greek-added} [εκει]{.greek-added}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις [κραββατοις]{.greek-omitted} [κραβαττοις]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει εστιν[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} και οσοι αν ηπτοντο αυτου [εσωζοντο]{.greek-omitted} [διεσωζοντο]{.greek-added}[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων [οι]{.greek-added} ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις χερσιν τουτ εστιν ανιπτοις εσθιοντας [τους]{.greek-added} αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη [νιψωνται]{.greek-omitted} [νιψονται]{.greek-added} τας [χειρας]{.greek-added} χειρας ουκ εσθιουσιν κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη [βαπτισωνται]{.greek-omitted} [βαπτισονται]{.greek-added} ουκ εσθιουσιν και αλλα πολλα εστιν α παρελαβον κρατειν [βαπτισμους]{.greek-omitted} [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [χαλκιων]{.greek-omitted} [και]{.greek-omitted} [κλινων]{.greek-omitted}[7:4]{.aside}

[ελεγεν]{.greek-omitted} [δε]{.greek-omitted} [οτι]{.greek-omitted} [το]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος ασελγεια οφθαλμος πονηρος [βλασφημια]{.greek-omitted} [βλασφημεια]{.greek-added} [υπερηφανια]{.greek-omitted} [υπερηφανεια]{.greek-added} αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν [εκπορευεται]{.greek-omitted} [εκπορευονται]{.greek-added} και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης ειχεν το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα προσεπεσεν προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτη]{.greek-omitted} [αυαυτη]{.greek-added} αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα [κυναρια]{.greek-omitted} [κυναρεια]{.greek-added} υποκατω της τραπεζης [εσθιει]{.greek-omitted} [εσθειει]{.greek-added} απο των [ψιχιων]{.greek-omitted} [ψιχειων]{.greek-added} των παιδιων[7:28]{.aside}

και ειπεν αυτη [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης ευρεν το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος ηλθεν προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων [δεκαπολεως]{.greek-omitted} [δεκαπο]{.greek-added} [λεως]{.greek-added}[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω [την]{.greek-omitted} [τας]{.greek-added} [χειρα]{.greek-omitted} [χειρας]{.greek-added}[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ [ιδιαν]{.greek-omitted} [ιδειαν]{.greek-added} εβαλεν τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον ουρανον εστεναξεν και λεγει αυτω εφφαθα ο εστιν διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και [δι]{.greek-added} [διεστειλατο]{.greek-omitted} [εστιλατο]{.greek-added} αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις διεστελλετο [αυτοι]{.greek-added} μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και [υπερπερισσως]{.greek-omitted} [υπερπερισως]{.greek-added} εξεπλησσοντο λεγοντες καλως παντα πεποιηκεν και τους κωφους ποιει ακουειν και τους αλαλους [λαλειν]{.greek-omitted} [λαλιν]{.greek-added}[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παλιν]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου οντος και μη εχοντων τι φαγωσιν προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας [αυτου]{.greek-omitted} λεγει αυτοις[8:1]{.aside}

[σπλαγχνιζομαι]{.greek-omitted} [σπλαγχνιζομε]{.greek-added} επι τον οχλον οτι ηδη ημεραι [τρεις]{.greek-omitted} [τρις]{.greek-added} προσμενουσιν μοι και [ουκ]{.greek-omitted} [ου]{.greek-added} [κ]{.greek-added} [εχουσιν]{.greek-omitted} [εχωσιν]{.greek-added} τι φαγωσιν[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις οικον αυτων [εκλυθησονται]{.greek-omitted} [εγλυθησονται]{.greek-added} εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκασιν]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτο[υ]{.unclear}ς δυνησεται τις ωδε [χορτασαι]{.greek-omitted} [χωρτασαι]{.greek-added} αρτων επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους εχετε αρτους οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγιλεν]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας εκλασεν και εδιδου τοις μαθηταις αυτου ινα [πα]{.greek-added} [παραθωσιν]{.greek-omitted} [ραθωσειν]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον [ιχθυδια]{.greek-omitted} [ιχθυδεια]{.greek-added} ολιγα και [αυτα]{.greek-added} ευλογησας ειπεν παραθειναι [αυτοις]{.greek-added} [και]{.greek-omitted} [αυτα]{.greek-omitted}[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως [τετρακισχιλιοι]{.greek-omitted} [τετρακισχειλιοι]{.greek-added} και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα [μερη]{.greek-omitted} [ορη]{.greek-added} δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο [συζητειν]{.greek-omitted} [συνζητειν]{.greek-added} αυτω ζητουντες παρ αυτου [σημειον]{.greek-omitted} [σημιον]{.greek-added} απο του ουρανου [πειραζοντες]{.greek-omitted} [πιραζοντες]{.greek-added} αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη [σημειον]{.greek-omitted} [σημιον]{.greek-added} [επιζητει]{.greek-omitted} [επιζητι]{.greek-added} αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη [σημειον]{.greek-omitted} [σημιον]{.greek-added}[8:12]{.aside}

και [αφεις]{.greek-omitted} [καταλιπων]{.greek-added} αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των [φαρισαιων]{.greek-omitted} [φαρισεων]{.greek-added} και της ζυμης ηρωδου[8:15]{.aside}

και [διελογιζοντο]{.greek-omitted} [ελογιζοντο]{.greek-added} προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε [συνιετε]{.greek-omitted} [συνειετε]{.greek-added} [ετι]{.greek-omitted} πεπωρωμενην εχετε την καρδιαν υμ[ων]{.unclear} [υμων]{.greek-added}[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε [ουπω]{.greek-added} [νοειτε]{.greek-added} [και]{.greek-omitted} [ου]{.greek-omitted} [μνημονευετε]{.greek-omitted}[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους [πεντακισχιλιους]{.greek-omitted} [πεντακισχιλειους]{.greek-added} ποσους κοφινους πληρεις κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε [και]{.greek-added} τους επτα εις τους [τετρακισχιλιους]{.greek-omitted} [τετρακισχιλειους]{.greek-added} ποσων [σπυ]{.greek-added} [σπυριδων]{.greek-omitted} [ριδων]{.greek-added} πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν [αυτοις]{.greek-omitted} πως [ου]{.greek-omitted} [ουπω]{.greek-added} [συνιετε]{.greek-omitted} [συνειετε]{.greek-added}[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω [επηρωτα]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν επεθηκεν τας χειρας [αυτου]{.greek-added} επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και ενεβλεψεν τηλαυγως απαντας[8:25]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστιλεν]{.greek-added} αυτον εις [τον]{.greek-omitted} οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας [καισαρειας]{.greek-omitted} [καισαριας]{.greek-added} της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην [και]{.greek-omitted} αλλοι [δε]{.greek-added} ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις [υμεις]{.greek-omitted} [υμις]{.greek-added} δε τινα με λεγετε ειναι [και]{.greek-added} αποκριθεις [δε]{.greek-omitted} ο πετρος λεγε[ι]{.greek-supplied} αυτω συ ει ο [χριστος]{.greek-omitted} [[χ]{.unclear}ς]{.greek-added}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι λεγωσιν περι αυτου[8:30]{.aside}

και ηρξατο [διδασκειν]{.greek-omitted} [διδασκιν]{.greek-added} αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και [των]{.greek-omitted} αρχιερεων και [των]{.greek-omitted} γραμματεων και αποκτανθηναι και μετα [τρεις]{.greek-omitted} [τρις]{.greek-added} ημερας αναστηναι[8:31]{.aside}

και παρρησια [ελαλει]{.greek-added} τον λογον [ελαλει]{.greek-omitted} [και]{.greek-omitted} [προσλαβομενος]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [ηρξατο]{.greek-omitted} [επιτιμαν]{.greek-omitted} [αυτω]{.greek-omitted}[8:32]{.aside}

### Chapter 9

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-added} αμην λεγω υμιν οτι εισιν τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν ιδωσιν την βασιλειαν του [θεου]{.greek-abbr} [εληλυθυιαν]{.greek-omitted} [εληλυθυειαν]{.greek-added} εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα [λιαν]{.greek-omitted} [λειαν]{.greek-added} ως χιων οια γναφευς επι της γης ου [δυ]{.greek-added} [δυναται]{.greek-omitted} [ναται]{.greek-added} λευκαναι [ουτως]{.greek-added}[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυσει]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [ραββι]{.greek-omitted} [ραββει]{.greek-added} καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας [τρεις]{.greek-omitted} [τρις]{.greek-added} [σοι]{.greek-omitted} [συ]{.greek-added} μιαν και [μωση]{.greek-omitted} [μωυσει]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

[και]{.greek-omitted} εγενετο [δε]{.greek-added} νεφελη επισκιαζουσα αυτοις και ηλθεν φωνη εκ της νεφελης ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα [περιβλεψαμενοι]{.greek-omitted} [περιβλεψα]{.greek-added} [μενοι]{.greek-added} ουκετι ουδενα ειδον [αλλα]{.greek-omitted} [ει]{.greek-added} [μη]{.greek-added} τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

[και]{.greek-added} καταβαινοντων [δε]{.greek-omitted} αυτων απο του ορους [διεστειλατο]{.greek-omitted} [διεστιλατο]{.greek-added} αυτοις ινα [μηδενι]{.greek-omitted} [μηδενει]{.greek-added} [διηγησωνται]{.greek-omitted} [διηγησοντε]{.greek-added} α [ειδον]{.greek-omitted} [ιδον]{.greek-added} ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους [συζητουντες]{.greek-omitted} [συνζητουντες]{.greek-added} τι εστιν το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων [πρωτον]{.greek-omitted} [πρωτος]{.greek-added} αποκαθιστα παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και [εξουδενωθη]{.greek-omitted} [εξουθενηθη]{.greek-added}[9:12]{.aside}

αλλα λεγω υμιν οτι [και]{.greek-omitted} ηλιας [ηδη]{.greek-added} εληλυθεν και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον πολυν περι αυτους και γραμματεις [συζητουντας]{.greek-omitted} [συνζητουντας]{.greek-added} αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και επηρωτησεν τους γραμματεις τι [συζητειτε]{.greek-omitted} [συνζητιτε]{.greek-added} προς αυτους[9:16]{.aside}

και [απο]{.greek-added} [αποκριθεις]{.greek-omitted} [κριθεις]{.greek-added} εις εκ του οχλου ειπεν διδασκ[α]{.unclear}λε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} [αλαλον]{.greek-omitted} [αλλον]{.greek-added}[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και [τριζει]{.greek-omitted} [τριζι]{.greek-added} τους οδοντας αυτου και [ξηραινεται]{.greek-omitted} [ξηρενεται]{.greek-added} και ειπον τοις μαθηταις σου ινα αυτο εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [λεγει]{.greek-added} αυτω [λεγει]{.greek-omitted} ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και επηρωτησεν τον [πατερα]{.greek-abbr} αυτου [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ποσος χρονος εστιν [ως]{.greek-omitted} [αφ]{.greek-added} [ου]{.greek-added} τουτο [γεγονεν]{.greek-omitted} [γεγονει]{.greek-added} αυτω ο δε ειπεν [εκ]{.greek-added} [παιδιοθεν]{.greek-omitted} [παιδοθεν]{.greek-added}[9:21]{.aside}

και [πολλακις]{.greek-omitted} [πολλακεις]{.greek-added} αυτον και εις [το]{.greek-omitted} πυρ εβαλεν και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει [δυνασαι]{.greek-omitted} [δυνη]{.greek-added} [πιστευσαι]{.corr} παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα [δακρυων]{.greek-omitted} [δακρυ]{.greek-added} [ων]{.greek-added} ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει οχλος επετιμησεν τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα [σπαραξαν]{.greek-omitted} [σπαραξας]{.greek-added} αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος [ηγειρεν]{.greek-omitted} [ηγιρεν]{.greek-added} αυτον και ανεστη[9:27]{.aside}

και [εισελθοντα]{.greek-omitted} [ελθοντα]{.greek-added} αυτον εις οικον οι μαθηται αυτου επηρωτων α[υ]{.unclear}τον κατ ιδιαν οτι ημεις ουκ ηδυνηθημεν [εκ]{.unclear}βαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν [ουδενι]{.greek-omitted} [ο[υ]{.unclear}δενει]{.greek-added} δυναται ε[ξ]{.unclear}ελθειν ει μ[η]{.unclear} [ε]{.unclear}ν προσε[υ]{.unclear}χη και [νηστεια]{.greek-omitted} [νηστια]{.greek-added}[9:29]{.aside}

και εκειθεν εξελθοντες [π]{.unclear}αρ[ε]{.unclear}πορ[ευ]{.unclear}οντο δια της γ[α]{.unclear}λιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε [η]{.greek-added} [ηγνοουν]{.greek-omitted} [γνοουν]{.greek-added} το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια [γενομενος]{.greek-omitted} [γεναμενος]{.greek-added} επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε [εσιωπων]{.greek-omitted} [εσιωπουν]{.greek-added} προς αλληλους γαρ διελεχθησαν εν τη οδω τις [μειζων]{.greek-omitted} [μιζων]{.greek-added}[9:34]{.aside}

και καθισας εφωνησεν τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι εσται παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και [εναγκαλισαμενος]{.greek-omitted} [ε[ν]{.unclear}]{.greek-added} [νος]{.greek-added} αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται [[α]{.unclear}]{.greek-added} ουκ εμε [δεχεται]{.greek-omitted} [δεχητε]{.greek-added} αλλα τον [αποστειλαντα]{.greek-omitted} [αποστιλαντα]{.greek-added} με[9:37]{.aside}

απεκριθη δε αυτω ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ειδαμεν]{.greek-added} τινα [εν]{.greek-added} τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και [εκωλυσαμεν]{.greek-omitted} [εκλυσαμεν]{.greek-added} αυτον οτι ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω [ο]{.greek-added} [ονοματι]{.greek-omitted} [νοματι]{.greek-added} μου και δυνησεται ταχυ [κακολογησαι]{.greek-omitted} [κακολογησε]{.greek-added} με[9:39]{.aside}

ος γαρ ουκ εστιν καθ υμων υπερ υμων εστιν[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν ονοματι [μου]{.greek-omitted} οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} σκανδαλιση ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει [περικειται]{.greek-omitted} [περικιτε]{.greek-added} λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου [απο]{.greek-added} [αποκοψον]{.greek-omitted} [κοψον]{.greek-added} αυτην καλον σοι εστιν κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεε[ν]{.unclear}ναν εις το πυρ το [ασβεστον]{.greek-omitted} [αζβεστον]{.greek-added}[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου [σβεννυται]{.greek-omitted} [σβεννυτε]{.greek-added}[9:44]{.aside}

και εαν ο πους σου [σκανδαλιζη]{.greek-omitted} [σκανδαλειζη]{.greek-added} σε αποκοψον αυτον καλον εστιν σοι εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις [την]{.greek-omitted} γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι εστιν μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο [αρτυσετε]{.greek-omitted} [αρτυσεται]{.greek-added} εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

[κακειθεν]{.greek-omitted} [κακιθεν]{.greek-added} αναστας [ερχεται]{.greek-omitted} [ηλθεν]{.greek-added} εις τα ορια της ιουδαιας δια του περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως [ειωθει]{.greek-omitted} [ιωθει]{.greek-added} παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι [πειραζοντες]{.greek-omitted} [πιραζοντες]{.greek-added} αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν [ενετειλατο]{.greek-omitted} [ενετιλατο]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} επ[ε]{.unclear}τρεψεν βιβλιον αποστασιου γραψαι και απολυσαι [αυτην]{.greek-added}[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων [εγραψεν]{.greek-omitted} [επετρεψεν]{.greek-added} υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

[και]{.greek-added} [ειπεν]{.greek-added} ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταλιψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-omitted} και την [μητερα]{.greek-abbr} και προσκολληθησεται [προς]{.greek-omitted} [την]{.greek-omitted} [τη]{.greek-added} [γυναικα]{.greek-omitted} [γυναικει]{.greek-added} αυτου[10:7]{.aside}

και [εσονται]{.greek-omitted} [εσοντε]{.greek-added} οι δυο εις σαρκα μιαν ωστε ουκετι εισιν δυο αλλα μια σαρξ[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [τουτου]{.greek-added} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [επερωτησαν]{.greek-added} αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και [γαμηθη]{.greek-omitted} [γαμηση]{.greek-added} αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε [ο]{.unclear} [ιησους]{.greek-abbr} ηγανακτησεν και ειπεν αυτοις αφετε τα παιδια ερχε[σ]{.unclear}θαι προς με μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την [βασιλειαν]{.greek-omitted} [βασιλει]{.greek-added} [αν]{.greek-added} του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα [τιθεις]{.greek-omitted} [τιθ[ι]{.unclear}ς]{.greek-added} τας χειρας επ αυτα [ευλογει]{.greek-omitted} [κατηυλογ[ι]{.unclear}]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης μη [απο]{.greek-added} [αποστερησης]{.corr} [τιμα]{.corr} τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου [τι]{.greek-added} [ετι]{.greek-added} [υστερω]{.greek-added}[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγ[α]{.unclear}πησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελις]{.greek-added} [τελιος]{.greek-added} [ειναι]{.greek-added} εν σοι υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν ουρανω και δευρο ακολουθει μοι αρας τον σταυρον[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα [πολλα]{.greek-omitted} [πολ]{.greek-added} [λα]{.greek-added}[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις [τεκνα]{.greek-omitted} [τεκνια]{.greek-added} πως δυσκολον εστιν τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον εστιν καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος [εισελθειν]{.greek-omitted} [εισελθιν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} [εισελθειν]{.greek-omitted} [εισελ]{.greek-added} [θειν]{.greek-added}[10:25]{.aside}

οι δε [περισσως]{.greek-omitted} [περισως]{.greek-added} [εξεπλησσοντο]{.greek-omitted} [εξεπλησοντο]{.greek-added} λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα ανθρωποις [τουτο]{.greek-added} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα εστιν παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθει[ς]{.unclear} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν [ουδεις]{.greek-omitted} [ουδις]{.greek-added} εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} [ενε]{.greek-added} [κεν]{.greek-added} του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας [και]{.greek-added} [πατερας]{.greek-added} και μητερας και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε [εσονται]{.greek-omitted} [εσοντε]{.greek-added} πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσειν]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσειν]{.greek-added} και κατακρινουσιν αυτον θανατω και [παραδωσουσιν]{.greek-omitted} [παραδωσουσειν]{.greek-added} αυτον τοις εθνεσιν[10:33]{.aside}

και εμπαιξουσιν αυτω και μαστιγωσουσιν [αυτον]{.greek-omitted} και [εμπτουσουσιν]{.greek-added} [εμπτυσουσιν]{.corr} αυτω και [αποκτενουσιν]{.greek-omitted} [αποκτενουσειν]{.greek-added} αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και [προσπορευονται]{.greek-omitted} [προσπορευοντε]{.greek-added} αυτω ιακωβος και [ιω]{.greek-added} [ιωαννης]{.greek-omitted} [αννης]{.greek-added} [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν [σε]{.greek-added} αιτησωμεν ποιησης ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι [αιτεισθε]{.greek-omitted} [αιτισθε]{.greek-added} δυνασθε πιειν το ποτηριον ο εγω πινω [και]{.greek-omitted} [η]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζομε]{.greek-added} βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο [αγανακτειν]{.greek-omitted} [αγανακτιν]{.greek-added} περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι [αυτων]{.greek-omitted} κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος [εαν]{.greek-omitted} [θελη]{.greek-omitted} [γενεσθαι]{.greek-omitted} [μεγας]{.greek-omitted} [εν]{.greek-omitted} [υμιν]{.greek-omitted} [εσται]{.greek-omitted} [υμων]{.greek-omitted} [διακονος]{.greek-omitted}[10:43]{.aside}

### Chapter 11

[και]{.greek-omitted} [ηγαγον]{.greek-omitted} [τον]{.greek-omitted} [πωλον]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [και]{.greek-omitted} [επεβαλον]{.greek-omitted} αυτω τα ιματια αυτων και εκαθισεν επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added} αλλοι δε [στοιβαδας]{.greek-omitted} [στυβαδας]{.greek-added} εκοπτον εκ των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added}[11:12]{.aside}

και ιδων συκην [απο]{.greek-added} μακροθεν εχουσαν φυλλα ηλθεν ει αρα [τι]{.greek-added} ευρησει [τι]{.greek-omitted} εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα [μονον]{.greek-added} ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται [παλιν]{.greek-added} εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο [εκβαλλειν]{.greek-omitted} [εκβαλλιν]{.greek-added} τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων [εξεχεεν]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και εδιδασκεν λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται πασιν τοις εθνεσιν [υμεις]{.greek-omitted} [υμις]{.greek-added} δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι γραμματεις και οι αρχιερεις και εζητουν πως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσειν]{.greek-added} εφοβουντο γαρ αυτον οτι πας [γαρ]{.greek-added} ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και [πρωι]{.greek-omitted} [πρωει]{.greek-added} παραπορευομενοι [ειδον]{.greek-omitted} [ιδον]{.greek-added} την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηρανθη]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην [γαρ]{.greek-omitted} λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα πιστευση οτι [α]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-added} [λαλει]{.greek-added} [γινεται]{.greek-omitted} [γεινεται]{.greek-added} εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα [αν]{.greek-omitted} [εαν]{.greek-added} προσευχομενοι [αιτησθε]{.greek-omitted} [αιτισθε]{.greek-added} πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκηται]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις ουρανοις αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε [υμεις]{.greek-omitted} [υμις]{.greek-added} ουκ [α]{.greek-added} [αφιετε]{.greek-omitted} [φιετε]{.greek-added} ουδε ο [πατηρ]{.greek-abbr} υμων ο εν [ουρανω]{.greek-added} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω υμιν εν ποια [ε]{.greek-added} [εξουσια]{.greek-omitted} [ξουσια]{.greek-added} ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ ουρανου ην η εξ [ανθρωπων]{.greek-abbr} [αποκριθητε]{.greek-omitted} [αποκριθηται]{.greek-added} μοι[11:30]{.aside}

[και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} ελογιζοντο προς εαυτους λεγοντες εαν ειπωμεν εξ ουρανου ερει δια τι ουν ουκ [επιστευσατε]{.greek-omitted} [επιστευσαται]{.greek-added} αυτω[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-abbr} [εφοβουντο]{.greek-omitted} [φοβουμεθα]{.greek-added} τον [λαον]{.greek-omitted} [οχλον]{.greek-added} [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ ειχον τον ιωαννην [ως]{.greek-added} [οτι]{.greek-omitted} [οντως]{.greek-omitted} [προφητης]{.greek-omitted} [προφητην]{.greek-added} [ην]{.greek-omitted}[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} τω [ιησου]{.greek-abbr} [λεγουσιν]{.greek-added} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο [λεγειν]{.greek-added} αυτοις εν παραβολαις [λεγειν]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} [εφυτευσεν]{.greek-added} αμπελωνα [εφυτευσεν]{.greek-omitted} [ανθρωπος]{.greek-omitted} και περιεθηκεν [αυτω]{.greek-added} φραγμον και ωρυξεν υποληνιον και ωκοδομησεν πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστιλεν]{.greek-added} προς τους γεωργους [δουλον]{.greek-added} τω καιρω [δουλον]{.greek-omitted} ινα παρα των γεω[ρ]{.greek-supplied}γων λαβη απο [του]{.greek-omitted} [καρπου]{.greek-omitted} [[τ]{.unclear}[ων]{.greek-supplied}]{.greek-added} [καρπων]{.greek-added} του α[μ]{.unclear}πελωνος[12:2]{.aside}

οι δε λαβοντες αυτον [εδειραν]{.greek-omitted} [εδιραν]{.greek-added} και [απεστειλαν]{.greek-omitted} [απεστιλαν]{.greek-added} κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστιλεν]{.greek-added} προς αυτους αλλον δουλον [κακεινον]{.greek-omitted} [κακινον]{.greek-added} λιθοβολησαντες εκεφαλαιωσαν και [απεστειλαν]{.greek-omitted} [απεστιλαν]{.greek-added} ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστιλεν]{.greek-added} [κακεινον]{.greek-omitted} [κακινον]{.greek-added} [απεκτειναν]{.greek-omitted} [απεκτιναν]{.greek-added} και πολλους αλλους τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα [υιον]{.greek-abbr} εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστιλεν]{.greek-added} και αυτον προς αυτους εσχατον λεγων [οτι]{.greek-omitted} [εντραπησονται]{.greek-omitted} [εντραπησοντε]{.greek-added} τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [ιδοντες]{.greek-added} [αυτον]{.greek-added} ειπον προς εαυτους [οτι]{.greek-omitted} ουτος εστιν ο κληρονομος δευτε [αποκτεινωμεν]{.greek-omitted} [αποκτινωμεν]{.greek-added} αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον [απεκτειναν]{.greek-omitted} [απεκτιναν]{.greek-added} και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους [εκεινους]{.greek-added} και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλη[ν]{.unclear} γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και [αφεντες]{.greek-omitted} [αφεν]{.greek-added} [τες]{.greek-added} αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελουσιν]{.greek-added} προς αυτον τινας των [φαρισαιων]{.greek-omitted} [φαρισεων]{.greek-added} και των ηρωδιανων ινα αυτον αγρευσωσιν λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου [μελει]{.greek-omitted} [μελι]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [ειπε]{.greek-added} [ουν]{.greek-added} [ημιν]{.greek-added} εξεστιν κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε [ειδως]{.greek-omitted} [ιδως]{.greek-added} αυτων την υποκρισιν ειπεν [αυ]{.greek-added} [αυτοις]{.greek-omitted} [τοις]{.greek-added} τι με [πειραζετε]{.greek-omitted} [πιραζετε]{.greek-added} [υπ[ο]{.unclear}κριται]{.greek-added} [φερετε]{.greek-omitted} [φερετοι]{.greek-added} μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος [εστιν]{.greek-added} η [εικων]{.greek-omitted} [ικων]{.greek-added} αυτη και η επιγραφη οι δε ειπ[ο]{.unclear}ν αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν α[υ]{.greek-supplied}τοις αποδοτε τα καισαρος [καισαρι]{.greek-omitted} [κεσαρει]{.greek-added} και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν ημιν οτι εαν τινος αδελφος [αποθανη]{.greek-omitted} [και]{.greek-omitted} [καταλιπη]{.greek-omitted} [γυναικα]{.greek-omitted} [και]{.greek-omitted} [τεκνα]{.greek-omitted} [μη]{.greek-omitted} [αφη]{.greek-omitted} [ινα]{.greek-omitted} [λαβη]{.greek-omitted} [ο]{.greek-omitted} [αδελφος]{.greek-omitted} [αυτου]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εξαναστηση]{.greek-omitted} [σπερμα]{.greek-omitted} [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [αυτου]{.greek-omitted}[12:19]{.aside}

### Chapter 14

[αμην]{.greek-omitted} λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινο[ν]{.unclear} [εν]{.greek-supplied} [τ]{.greek-supplied}[η]{.unclear} βασιλεια [τ]{.unclear}[ου]{.greek-supplied} [θεου]{.greek-abbr}[14:25]{.aside}

και υ[μνη]{.greek-supplied}[σ]{.unclear}αντες εξηλθον εις [τ]{.unclear}[ο]{.greek-supplied} ορος των ελ[αι]{.greek-supplied}ων[14:26]{.aside}

και λεγε[ι]{.greek-supplied} [αυ]{.greek-supplied}τοις ο [ιησους]{.greek-abbr} οτι [π]{.unclear}[αν]{.greek-supplied}τες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλ[ι]{.unclear}[σ]{.greek-supplied}θησεσθαι]{.greek-added} εν εμοι εν τη νυκτι ταυτη [οτι]{.greek-omitted} [γεγραπται]{.greek-omitted} [γεγραπτε]{.greek-added} [γαρ]{.greek-added} παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις [τη]{.greek-supplied}ν γαλιλαιαν[14:28]{.aside}

[ο]{.greek-supplied} [δ]{.greek-supplied}ε πετρος εφ[η]{.greek-supplied} [α]{.greek-supplied}υτω και ει παντες [σκανδαλισθησονται]{.greek-omitted} [σκανδαλισθησοντε]{.greek-added} αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν η δις αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε [πετρος]{.greek-added} εκπερισ[σο]{.greek-supplied}[υ]{.unclear} ελεγεν μ[α]{.unclear}[λλ]{.greek-supplied}ον εαν [δεη]{.greek-added} μ[ε]{.greek-supplied} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} [[σ]{.unclear}υ[ν]{.unclear}αποθανι[ν]{.unclear}]{.greek-added} σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομε]{.greek-added} ωσαυτως δε και παν[τ]{.unclear}ες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεσσημανει]{.greek-added} και λεγ[ει]{.unclear} τοις μα[θ]{.unclear}[ηταις]{.greek-supplied} αυτου καθ[ισα]{.greek-supplied}τε ωδε ε[ως]{.greek-supplied} [[α]{.greek-supplied}[π]{.unclear}ελ[θ]{.unclear}ων]{.greek-added} προσευ[ξ]{.greek-supplied}ωμαι[14:32]{.aside}

και πα[ρ]{.greek-supplied}αλαμβανει τον [π]{.unclear}ετρον και ι[α]{.greek-supplied}κωβον και ιωαννην μεθ εαυτου και ηρξατο [εκθαμβεισθαι]{.greek-omitted} [εκθαμβεισθε]{.greek-added} και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου [εω]{.greek-supplied}[ς]{.unclear} θανατου [μ]{.unclear}[ειν]{.greek-supplied}[α]{.unclear}τε [ω]{.unclear}δε κα[ι]{.unclear} [γρ]{.unclear}ηγορειτε[14:34]{.aside}

και [προσελθων]{.greek-omitted} [πρ[ο]{.unclear}[―]{.gap}ελθων]{.greek-added} μικ[ρον]{.greek-supplied} επεσεν επι [της]{.greek-supplied} γης και προ[σ]{.greek-supplied}ηυχετο ινα [ε]{.unclear}[ι]{.greek-supplied} δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε [τουτο]{.greek-added} το ποτηριον απ εμου [τουτο]{.greek-omitted} [πλην]{.greek-added} αλ[λ]{.unclear} ου τι εγω θε[λ]{.greek-supplied}[ω]{.unclear} αλλα τι συ[14:36]{.aside}

[και]{.greek-supplied} ερχεται και [ευρισ]{.greek-supplied}κει αυτους καθευδοντας και λεγει τω πετρω σ[ιμ]{.unclear}ων [κα]{.greek-added} [καθευδεις]{.greek-omitted} [θευδις]{.greek-added} ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις [πειρασμον]{.greek-omitted} [πιρασμον]{.greek-added} το μεν [πνευμα]{.greek-abbr} προθυμον η δε [σ]{.unclear}[αρξ]{.greek-supplied} ασθενης[14:38]{.aside}

και παλιν [α]{.unclear}[πελ]{.greek-supplied}θων π[ρ]{.unclear}[οσηυ]{.greek-supplied}ξατο τον αυ[τ]{.unclear}[ον]{.greek-supplied} λογον ειπων[14:39]{.aside}

και υ[πο]{.unclear}στρεψας ευρεν αυτους [καθευδοντας]{.greek-added} παλιν [καθευδοντας]{.greek-omitted} ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καταβαρυνομενομενοι]{.greek-added} και ουκ [ηδεισαν]{.greek-omitted} [ηδισαν]{.greek-added} τι αυτ[ω]{.greek-supplied} [απ]{.greek-supplied}οκριθω[σ]{.unclear}[ιν]{.greek-supplied}[14:40]{.aside}

και ερχεται το [τ]{.unclear}ριτον και λε[γ]{.greek-supplied}ει αυτοις [καθευδετε]{.greek-omitted} [κα[θ]{.greek-supplied}ευδεται]{.greek-added} [το]{.greek-added} [λ]{.greek-supplied}οιπον και [αναπαυεσθε]{.greek-omitted} [α[ν]{.unclear}απαυεσθαι]{.greek-added} απεχει ηλθεν η ωρα ιδου [παραδιδοται]{.greek-omitted} [παραδιδοτε]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} [χειρας]{.greek-omitted} [χιρας]{.greek-added} των αμαρτωλων[14:41]{.aside}

[εγειρεσθε]{.greek-omitted} [εγιρεσθε]{.greek-added} αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γραμματεων και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον [αυτοις]{.greek-omitted} λεγων ον [αν]{.greek-omitted} [εαν]{.greek-added} φιλησω αυτος εστιν [κρατησατε]{.greek-omitted} [κρατησαται]{.greek-added} αυτον και απαγαγετε [αυτον]{.greek-added} ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [λε]{.unclear}γει αυτ[ω]{.unclear} ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον [αυτω]{.greek-added} [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν επαισεν τον δουλον του αρχιερεως και [αφειλεν]{.greek-omitted} [αφιλεν]{.greek-added} αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων [συλλαβειν]{.greek-omitted} [συλλαβιν]{.greek-added} με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι [των]{.greek-added} [προφητων]{.greek-added}[14:49]{.aside}

[και]{.greek-omitted} [τοτε]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} αφεντες αυτον [παντες]{.greek-omitted} εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και [συνερχονται]{.greek-omitted} [συνερχοντε]{.greek-added} [αυτω]{.greek-omitted} [αυτων]{.greek-added} παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος [και]{.greek-added} [θερμενομενος]{.greek-added} μετα των υπηρετων [και]{.greek-omitted} [θερμαινομενος]{.greek-omitted} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το [συν]{.greek-added} [συνεδριον]{.greek-omitted} [εδριον]{.greek-added} εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και [τινες]{.greek-omitted} [τιναις]{.greek-added} ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι [ημεις]{.greek-omitted} [ημις]{.greek-added} ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον [χειροποιητον]{.greek-omitted} [χιροποιητον]{.greek-added} και [αλλον]{.greek-added} [αχιροποιητον]{.greek-added} δια τριων ημερων [αλλον]{.greek-omitted} [αχειροποιητον]{.greek-omitted} οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω [ειμι]{.greek-omitted} [ειμει]{.greek-added} και [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του ουρανου[14:62]{.aside}

ο δε αρχιερευς [διαρρηξας]{.greek-omitted} [διαρηξας]{.greek-added} τους χιτωνας αυτου λεγει τι ετι [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχομεν μαρτυρων[14:63]{.aside}

[ηκουσατε]{.greek-omitted} [ηκουσαται]{.greek-added} [παντες]{.greek-added} της βλασφημιας [αυτου]{.greek-added} τι υμιν [φαινεται]{.greek-omitted} [δοκει]{.greek-added} οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και [περικαλυπτειν]{.greek-omitted} [περικαλυπτιν]{.greek-added} το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [πεσας]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [ελαβον]{.greek-added}[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον [θερμαινομενον]{.greek-omitted} [θερμενομενον]{.greek-added} εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε επισταμαι [συ]{.greek-added} τι [συ]{.greek-omitted} [λεγεις]{.greek-omitted} [λεγις]{.greek-added} και εξηλθεν εξω εις το προαυλιον και αλεκτωρ εφωνησεν[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνησατο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου [ομοιαζει]{.greek-omitted} [δηλοι]{.greek-added}[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} [τουτον]{.greek-omitted} ον [λεγετε]{.greek-omitted} [λεγωται]{.greek-added}[14:71]{.aside}

και εκ δευτερου αλεκτωρ εφωνησεν και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα [φωνησαι]{.greek-omitted} [φωνησε]{.greek-added} δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι το πρωι [συμβουλιον]{.greek-omitted} [συμβουλειον]{.greek-added} ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} [απηνεγκαν]{.greek-omitted} [απηγαγον]{.greek-added} και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε [[ιησους]{.greek-abbr}]{.greek-added} αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν [ιδε]{.greek-omitted} [ειδε]{.greek-added} ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσειν]{.greek-added}[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των [συστασιαστων]{.greek-omitted} [στασιαστων]{.greek-added} δεδεμενος οιτινες εν τη στασει φονο[ν]{.unclear} πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο [αιτεισθαι]{.greek-omitted} [αιτισθαι]{.greek-added} καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

εγινωσκεν γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδωκεισαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεσισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν [θελετε]{.greek-omitted} [θελεται]{.greek-added} ποιησω ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν σταυρωσον αυτον[15:13]{.aside}

ο δε πιλατος [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις τι γαρ κακον εποιησεν οι δε περισσοτερως εκραξαν σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και παρεδωκεν τον [ιησουν]{.greek-abbr} φραγελλωσας ινα σταυρωθη[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο εστιν πραιτωριον και [συγκαλουσιν]{.greek-omitted} [συνκαλουσιν]{.greek-added} ολην την [σπειραν]{.greek-omitted} [σπιραν]{.greek-added}[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και [περιτιθεασιν]{.greek-omitted} [περιτιθεασειν]{.greek-added} αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον [και]{.greek-added} [λεγειν]{.greek-added} χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα [ιδια]{.greek-omitted} [ιδεια]{.greek-added} και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-omitted} [σταυρωσουσιν]{.greek-added} αυτον[15:20]{.aside}

και αγγαρευουσιν [παραγοντα]{.greek-omitted} τινα σιμωνα [κυρηναιον]{.greek-omitted} [κυρηνεον]{.greek-added} ερχομενον [απ]{.greek-omitted} [απο]{.greek-added} αγ[ρ]{.unclear}ου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον στ[α]{.unclear}υρον αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} [γολγοθα]{.greek-omitted} [γολγοθαν]{.greek-added} τοπον ο εστιν [μεθερμηνευομενον]{.greek-omitted} [μεθερμηνευομενος]{.greek-added} κρανιου τοπος[15:22]{.aside}

και εδιδουν [αυ]{.greek-added} [αυτω]{.greek-omitted} [πιειν]{.greek-omitted} [εσμυρνισμενον]{.greek-omitted} [οινον]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ουκ]{.greek-omitted} [ελαβεν]{.greek-omitted}[15:23]{.aside}

[γενομενης]{.greek-omitted} [δε]{.greek-omitted} [ωρας]{.greek-omitted} [εκτης]{.greek-omitted} [σκοτος]{.greek-omitted} [εγενετο]{.greek-omitted} [εφ]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [εως]{.greek-omitted} [ωρας]{.greek-omitted} ενατης[15:33]{.aside}

και τη ωρα τη ενατη [εβοησεν]{.greek-omitted} [[α]{.unclear}νεβοησεν]{.greek-added} ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λαμα]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβαχθανει]{.greek-added} ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις [τε]{.greek-omitted} καλαμω εποτιζεν αυτον λεγων [αφετε]{.greek-omitted} [αφεται]{.greek-added} ιδωμεν ει ερχεται ηλιας καθελειν αυ[τ]{.unclear}ον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσε[ν]{.unclear}[15:37]{.aside}

και [ιδου]{.greek-added} το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην και μαρια η μαγδαληνη και μαρια η [του]{.greek-omitted} ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν [αυτω]{.greek-omitted} και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης [επει]{.greek-omitted} [ην]{.greek-omitted} [παρασκευη]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [προσαββατον]{.greek-omitted}[15:42]{.aside}

