---
title: "Collation of Byz^RP^ vs 20020 (20)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 20 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20020).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 20                                   	| λογος                              	|
| 20 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 20 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 20               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 20                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 20 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 20                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 8

[ω]{.greek-omitted} [προσειχον]{.greek-omitted} [απο]{.greek-omitted} [μικρου]{.greek-omitted} [εως]{.greek-omitted} [μεγαλου]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [δυνα]{.greek-supplied}μις του [θεου]{.greek-abbr} η μεγαλη[[8:10 *(lacunose)*]{.lacunose}]{.aside}

προσειχον δε αυτω δια [το]{.greek-omitted} [τω]{.greek-added} ικανω χρονω ταις μαγειαις εξεστακεναι αυτους[8:11]{.aside}

οτε δε επιστευσαν τω φιλιππω ευαγγελιζομενω τα περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος επιστευσεν και βαπτισθεις ην προσκαρτερων τω φιλιππω θεωρων τε δυναμεις και σημεια γινομενα εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} απεστειλαν προς αυτους τον πετρον και ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως [λαβωσιν]{.greek-omitted} [λαβωσι]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

ουπω γαρ ην επ ουδενι αυτων επιπεπτωκος μονον δε βεβαπτισμενοι υπηρχον εις το ονομα του [χριστου]{.greek-abbr} [ιησου]{.greek-abbr}[8:16]{.aside}

τοτε επετιθουν τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

θεασαμενος δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω εαν επιθω τας χειρας λαμβανη [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε ειπεν προς αυτον το αργυριον σου συν σοι ειη εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} ενομισας δια χρηματων κτασθαι[8:20]{.aside}

ουκ εστιν σοι μερις ουδε κληρος εν τω λογω τουτω η γαρ καρδια σου ουκ εστιν ευθεια [ενωπιον]{.greek-omitted} [ενω]{.greek-added} [πιον]{.greek-added} του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} ει αρα αφεθησεται σοι η επινοια της καρδιας σου[8:22]{.aside}

εις γαρ χολην πικριας και συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

αποκριθεις δε ο σιμων ειπεν δεηθητε υμεις υπερ εμου προς τον [κυριον]{.greek-abbr} οπως μηδεν επελθη επ εμε [ων]{.greek-omitted} [ως]{.greek-added} ειρηκατε[8:24]{.aside}

οι μεν ουν [διαμαρτυραμενοι]{.greek-omitted} [διαμαρτυρομενοι]{.greek-added} και λαλησαντες τον λογον του [κυριου]{.greek-abbr} υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} πολλας τε κωμας των σαμαρειτων ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} προς φιλιππον λεγων αναστηθι και πορευου κατα [μσιμβριαν]{.greek-added} [μεσημβριαν]{.greek-omitted} [[μεσιμβριαν]{.corr}]{.greek-added} επι την οδον την καταβαινουσαν απο [ιερουσαλημ]{.greek-abbr} εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ αιθιοψ ευνουχος δυναστης κανδακης της βασιλισσης [αιθιοπων]{.greek-omitted} [αιθιωπων]{.greek-added} ος ην επι πασης της γαζης αυτης ος [εληλυθει]{.greek-omitted} [εληλυθη]{.greek-added} προσκυνησων [εις]{.greek-omitted} [εν]{.greek-added} [ιερουσαλημ]{.greek-abbr}[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου και [ανεγινωσκεν]{.greek-omitted} [ανεγινωσκε]{.greek-added} τον προφητην ησαιαν[8:28]{.aside}

ειπεν δε το [πνευμα]{.greek-abbr} τω φιλιππω προσελθε και κολληθητι [[κολλιθητι]{.corr}]{.greek-added} τω αρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος τον προφητην ησαιαν και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε ειπεν πως γαρ αν δυναιμην εαν μη τις οδηγηση με παρεκαλεσεν τε τον φιλιππον αναβαντα καθισαι συν αυτω[8:31]{.aside}

η δε περιοχη της γραφης ην ανεγινωσκεν ην [αυτη]{.greek-omitted} [αυ]{.greek-added} [τη]{.greek-added} ως προβατον επι [σ]{.greek-supplied}φαγην ηχθη και ως αμνος εναντιον του [κειροντος]{.greek-omitted} [κει[ρ]{.unclear}αντος]{.greek-added} αυτον αφωνος [ουτως]{.greek-omitted} [ουτος]{.greek-added} ουκ ανοιγει το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω ειπεν δεομαι σου περι τινος ο προφητης λεγει τουτο περι εαυτου η περι ετερου τινος[8:34]{.aside}

ανοιξας δε ο φιλιππος το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο αυτω τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο κατα την οδον ηλθον επι τι υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} στηναι το αρμα και κατεβησαν αμφοτεροι εις το υδωρ ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν εκ του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} [ηρπασεν]{.greek-omitted} [ηρπασε]{.greek-added} τον φιλιππον και ουκ ειδεν αυτον ουκετι ο ευνουχος επορευετο γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις καισαρειαν[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

[ητησατο]{.greek-omitted} [ητισατο]{.greek-added} παρ αυτου επιστολας εις δαμασκον προς τας συναγωγας οπως εαν τινας ευρη της οδου οντας ανδρας τε και γυναικας δεδεμενους [αγαγη]{.greek-omitted} [αγαγει]{.greek-added} εις ιερουσαλημ[9:2]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} πορευεσθαι εγενετο αυτον εγγιζειν τη δαμασκω και [εξαιφνης]{.greek-omitted} [εξαιφνις]{.greek-added} περιηστραψεν αυτον φως [απο]{.greek-omitted} [εκ]{.greek-added} του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην ηκουσεν φωνην λεγουσαν αυτω σαουλ σαουλ τι με διωκεις[9:4]{.aside}

ειπεν δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[9:5]{.aside}

αλλα αναστηθι και εισελθε εις την πολιν και λαληθησεται σοι τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι συνοδευοντες αυτω ειστηκεισαν [ενεοι]{.greek-omitted} [εννεοι]{.greek-added} ακουοντες μεν της φωνης μηδενα δε θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων τε των οφθαλμων αυτου ουδενα εβλεπεν [χειραγωγουντες]{.greek-omitted} [χειραγογουντες]{.greek-added} δε αυτον εισηγαγον εις [δαμασκον]{.greek-omitted} [δαμασκων]{.greek-added}[9:8]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και ειπεν προς αυτον ο [κυριος]{.greek-abbr} εν οραματι ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και ειδεν εν οραματι ανδρα ονοματι ανανιαν εισελθοντα και επιθεντα αυτω χειρα οπως [αναβλεψη]{.greek-omitted} [αναβλεψει]{.greek-added}[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα εποιησεν τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και ωδε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

ειπεν δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω [αυτω]{.greek-omitted} [αυτον]{.greek-added} οσα δει αυτον υπερ του ονοματος μου παθειν[9:16]{.aside}

απηλθεν δε ανανιας και εισηλθεν εις την οικιαν και επιθεις επ αυτον τας χειρας ειπεν σαουλ αδελφε ο [κυριος]{.greek-abbr} απεσταλκεν με ο [οφθεις]{.greek-omitted} [ωφθεις]{.greek-added} σοι εν τη οδω η ηρχου οπως αναβλεψης και πλησθης [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

και ευθεως απεπεσον απο των οφθαλμων αυτου ωσει λεπιδες ανεβλεψεν τε [παραχρημα]{.greek-added} και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε ο σαυλος μετα των [οντων]{.greek-added} εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις εκηρυσσεν τον [χριστον]{.greek-abbr} οτι ουτος εστιν ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγον ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους [αγαγη]{.greek-omitted} [αγαγει]{.greek-added} επι τους αρχιερεις[9:21]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και [συνεχυνεν]{.greek-omitted} [συνεχυνε]{.greek-added} τους ιουδαιους τους κατοικουντας εν δαμασκω συμβιβαζων οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω η επιβουλη αυτων παρετηρουν τε τας πυλας ημερας [τε]{.greek-omitted} και νυκτος οπως αυτον ανελωσιν[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος καθηκαν δια του τειχους χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι εστιν μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον ηγαγεν προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω [επαρρησιασατ[ω]{.unclear}]{.greek-added} [επαρρησιασατο]{.corr} εν τω ονοματι του [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος εις [ιερουσαλημ]{.greek-abbr} και παρρησιαζομενος εν τω ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

[ελαλει]{.greek-omitted} [ελαλη]{.greek-added} τε και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

[επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} δε οι αδελφοι κατηγαγον [αυτον]{.greek-omitted} εις καισαρειαν και εξαπεστειλαν αυτον εις ταρσον[9:30]{.aside}

αι μεν ουν [αικκλησιαι]{.greek-added} [εκκλησιαι]{.corr} καθ ολης της ιουδαιας και γαλιλαιας και σαμαρειας ειχον ειρηνην οικοδομουμεναι και πορευομεναι τω φοβω του [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} επληθυνοντο[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας λυδδαν[9:32]{.aside}

ευρεν δε εκει [ανθρωπον]{.greek-abbr} τινα αινεαν ονοματι εξ ετων οκτω κατακειμενον επι [κραββατω]{.greek-omitted} [κραβαττω]{.greek-added} ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον [σεαυτω]{.greek-omitted} [σεαυτον]{.greek-added} και ευθεως ανεστη[9:34]{.aside}

και ειδον αυτον παντες οι κατοικουντες λυδδαν και τον ασσαρωνα οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} η διερμηνευομενη λεγεται δορκας αυτη ην πληρης αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν εν υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν προς αυτον παρακαλουντες μη οκνησαι διελθειν εως αυτων[9:38]{.aside}

αναστας δε πετρος συνηλθεν αυτοις ον παραγενομενον ανηγαγον εις το υπερωον και παρεστησαν αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μετ αυτων ουσα η δορκας[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος θεις τα γονατα προσηυξατο και επιστρεψας προς το σωμα ειπεν [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} αναστηθι η δε ηνοιξεν τους οφθαλμους αυτης και ιδουσα τον πετρον ανεκαθισεν[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην φωνησας δε τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωστον δε εγενετο καθ ολης [της]{.greek-omitted} [τη]{.greek-added} [ιοππης]{.greek-omitted} [ιοππη]{.greek-added} και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι αυτον [εν]{.greek-omitted} [ιοππη]{.greek-omitted} παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις [ην]{.greek-omitted} εν καισαρεια ονοματι κορνηλιος [εκατονταρχης]{.greek-omitted} εκ σπειρης της καλουμενης ιταλικης[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

ειδεν εν οραματι φανερως ωσει ωραν [ενατην]{.greek-omitted} [εννατην]{.greek-added} της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω [κορνηλιε]{.greek-omitted}[10:3]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ατενισας]{.greek-omitted} [αυτω]{.greek-omitted} και εμφοβος γενομενος ειπεν τι εστιν [κυριε]{.greek-abbr} ειπεν δε αυτω αι προσευχαι σου και αι ελεημοσυναι σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν οικια παρα θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος [ο]{.greek-omitted} λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και [στρα]{.greek-added} [στρατιωτην]{.greek-omitted} [τιωτην]{.greek-added} ευσεβη των προσκαρτερουντων αυτω[10:7]{.aside}

και εξηγησαμενος αυτοις απαντα απεστειλεν αυτους εις την ιοππην[10:8]{.aside}

τη δε επαυριον [οδοιπορουντων]{.greek-omitted} [οδυπορουντων]{.greek-added} [εκεινων]{.greek-omitted} [αυτων]{.greek-added} και τη πολει εγγιζοντων ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν εκτην[10:9]{.aside}

εγενετο δε [προσπεινος]{.greek-omitted} [προσπινος]{.greek-added} και ηθελεν γευσασθαι παρασκευαζοντων δε εκεινων επεπεσεν επ αυτον εκστασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεωγμενον και καταβαινον επ αυτον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις δεδεμενον και καθιεμενον επι της γης[10:11]{.aside}

εν ω [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} παντα τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστας πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος ειπεν μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον η ακαθαρτον[10:14]{.aside}

και φωνη παλιν εκ δευτερου προς αυτον α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθερησεν]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν ανεληφθη το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο πετρος τι αν ειη το οραμα ο ειδεν και ιδου οι ανδρες οι απεσταλμενοι απο του κορνηλιου διερωτησαντες την οικιαν σιμωνος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει σιμων ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες ζητουσιν σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους[10:20]{.aside}

καταβας δε [ο]{.greek-added} πετρος προς τους ανδρας ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος ουν αυτους [εξενισεν]{.greek-omitted} [εξενησεν]{.greek-added} τη δε επαυριον ο πετρος εξηλθεν συν αυτοις και τινες των αδελφων των απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος αυτον ηγειρεν λεγων αναστηθι καγω αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και [συνομιλων]{.greek-omitted} [συνομηλων]{.greek-added} αυτω εισηλθεν και ευρισκει συνεληλυθοτας πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως [αθεμιτον]{.greek-omitted} [αθεμητον]{.greek-added} εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και [αναντιρρητως]{.greek-omitted} [αναντηρειτως]{.greek-added} ηλθον μεταπεμφθεις πυνθανομαι ουν τινι λογω [μετεπεμψασθε]{.greek-omitted} [μετεπεμψασθαι]{.greek-added} με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και [την]{.greek-omitted} [ενατην]{.greek-omitted} [ωραν]{.greek-omitted} [προσευχομενος]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [οικω]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και φησιν κορνηλιε εισηκουσθη σου η προσευχη και αι [ελεημοσυναι]{.greek-omitted} [λεημοσυναι]{.greek-added} σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και μετακαλεσαι σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος βυρσεως παρα θαλασσαν ος παραγενομενος λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιη[σα]{.unclear}ς παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα ειπεν επ αληθειας καταλαμβανομαι οτι ουκ εστιν προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι εθνει ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην δεκτος αυτω εστιν[10:35]{.aside}

τον λογον ον απεστειλεν τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος εστιν παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το βαπτισμα ο εκηρυξεν ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο ναζαρετ ως εχρισεν αυτον ο [θεος]{.greek-abbr} [εν]{.greek-added} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-abbr} ον και ανειλον κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} ηγειρεν τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες συνεφαγομεν και συνεπιομεν αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι αυτος εστιν ο ωρισμενος υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

[τουτω]{.greek-omitted} [τουτον]{.greek-added} παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε [α]{.greek-added} [απεκριθη]{.greek-omitted} [πεκριθη]{.greek-added} ο πετρος[10:46]{.aside}

μητι το υδωρ κωλυσαι δυναται τις του μη βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

προσεταξεν τε αυτους βαπτισθηναι εν τω ονοματι του [κυριου]{.greek-abbr} τοτε ηρωτησαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας [εισηλθες]{.greek-omitted} [εισηλθεν]{.greek-added} και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε ο πετρος εξετιθετο αυτοις [καθεξης]{.corr} λεγων[11:4]{.aside}

εγω ημην εν πολει ιοππη προσευχομενος και ειδον εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και ειδον τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του ουρανου[11:6]{.aside}

ηκουσα δε φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθερισεν]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν ανεσπασθη απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η ημην απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

ειπεν δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν διακρινομενον ηλθον δε συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

απηγγειλεν τε ημιν πως ειδεν τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις σωθηση συ και πας ο οικος σου[11:14]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} αρξασθαι με λαλειν επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω δε τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες [αρα]{.greek-omitted} [αραγε]{.greek-added} [γε]{.greek-omitted} και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες απο της θλιψεως της γενομενης επι στεφανω διηλθον εως φοινικης και κυπρου και [αντιοχειας]{.greek-omitted} [αντιοχιας]{.greek-added} μηδενι λαλουντες τον λογον ει μη μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων ανδρες [κυ]{.greek-added} [κυπριοι]{.greek-omitted} [πριοι]{.greek-added} και [κυρηναιοι]{.greek-omitted} [κυρινναιοι]{.greek-added} οιτινες [εισελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της εν ιεροσολυμοις περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει παντας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και πληρης [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

εξηλθεν δε εις ταρσον ο βαρναβας αναζητησαι σαυλον[11:25]{.aside}

και ευρων [αυτον]{.greek-added} ηγαγεν αυτον εις αντιοχειαν εγενετο δε αυτους ενιαυτον ολον συναχθηναι τη εκκλησια και διδαξαι οχλον ικανον [χρηματισαι]{.greek-omitted} [χρηματησαι]{.greek-added} τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος εσημανεν δια του [πνευματος]{.greek-abbr} λιμον μεγαν μελλειν εσεσθαι εφ ολην την οικουμενην οστις και εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως [ευπορειτο]{.greek-omitted} [ηυπορειτο]{.greek-added} τις ωρισαν εκαστος αυτων εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

[ο]{.greek-omitted} [οι]{.greek-added} και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της εκκλησιας[12:1]{.aside}

ανειλεν δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

και ιδων οτι αρεστον εστιν τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε [αι]{.greek-omitted} ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους τεσσαρσιν τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω [λαω]{.greek-omitted} [λαων]{.greek-added}[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης [γ[ε]{.unclear}νομενη]{.greek-added} [γινομενη]{.corr} υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} αυτον προαγειν ο ηρωδης τη [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} εκεινη [[ην]{.unclear}]{.greek-added} ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και εξεπεσον αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

ειπεν τε [προς]{.greek-added} [αυτον]{.greek-added} ο αγγελος [προς]{.greek-omitted} [αυτον]{.greek-omitted} περιζωσαι και υποδησαι τα [σανδαλια]{.greek-omitted} [σανδαλεια]{.greek-added} σου εποιησεν δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι[12:8]{.aside}

και εξελθων [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και ουκ [ηδει]{.greek-omitted} [ειδει]{.greek-added} οτι αληθες [εστιν]{.greek-omitted} [εστι]{.greek-added} το [γινομενον]{.greek-omitted} [γενομενον]{.greek-added} δια του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν [την]{.greek-omitted} [φερουσαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} ητις [αυτοματη]{.greek-omitted} [αυτοματι]{.greek-added} ηνοιχθη αυτοις και εξελθοντες [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος γενομενος εν εαυτω ειπεν νυν οιδα αληθως οτι εξαπεστειλεν [κυριος]{.greek-abbr} τον αγγελον αυτου και [εξειλετο]{.greek-omitted} [εξειλατο]{.greek-added} με εκ χειρος ηρωδου και πασης της προσδοκιας του λαου των ιουδαιων[12:11]{.aside}

συνιδων τε ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} ιωαννου του επικαλουμενου μαρκου ου ησαν ικανοι [συνηθροισμενοι]{.greek-omitted} [συνηθρυσμενοι]{.greek-added} και προσευχομενοι[12:12]{.aside}

κρουσαντος δε [του]{.greek-omitted} [αυτου]{.greek-added} [πετρου]{.greek-omitted} την θυραν του πυλωνος προσηλθεν παιδισκη υπακουσαι ονοματι ροδη[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ ηνοιξεν τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον [μαινη]{.greek-omitted} [μαινει]{.greek-added} [ει]{.greek-added} [η]{.corr} δε διισχυριζετο ουτως εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος επεμενεν κρουων ανοιξαντες δε ειδον αυτον και εξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξηγαγεν εκ της φυλακης ειπεν δε απαγγειλατε ιακωβω και τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις την καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης θυμομαχων τυριοις και σιδωνιοις ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι αυτων την χωραν απο της βασιλικης[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα βασιλικην και καθισας επι του βηματος εδημηγορει προς αυτους[12:21]{.aside}

ο δε δημος επεφωνει φωνη [θεου]{.greek-abbr} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε επαταξεν αυτον αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ εδωκεν δοξαν τω [θεω]{.greek-abbr} και γενομενος [σκωλικοβροτος]{.greek-added} [σκωληκοβρωτος]{.greek-omitted} [[σκωλικοβρωτος]{.corr}]{.greek-added} εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} ηυξανεν και επληθυνετο[12:24]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} πληρωσαντες την διακονιαν συμπαραλαβοντες και ιωαννην τον επικληθεντα μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε τινες εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος ο κυρηναιος μαναην τε ηρωδου του τετραρχου συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων ειπεν το [πνευμα]{.greek-abbr} το αγιον [αφορισατε]{.greek-omitted} [αφορησατε]{.greek-added} δη μοι τον βαρναβαν και τον σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες τας χειρας αυτοις απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεντες υπο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις την σελευκειαν εκειθεν δε απεπλευσαν εις την κυπρον[13:4]{.aside}

και γενομενοι εν [σαλαμινι]{.greek-omitted} [σαλαμινη]{.greek-added} κατηγγελλον τον λογον του [θεου]{.greek-abbr} εν ταις συναγωγαις των ιουδαιων ειχον δε και ιωαννην υπηρετην[13:5]{.aside}

διελθοντες δε την νησον αχρι παφου ευρον τινα μαγον ψευδοπροφητην ιουδαιον ω ονομα [βαριησους]{.greek-omitted} [βαριησουν]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω παυλω ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επεζητησεν ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο [μαγος]{.greek-omitted} [μεγας]{.greek-added} ουτως γαρ μεθερμηνευεται το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου [και]{.greek-omitted} ατενισας εις αυτον[13:9]{.aside}

ειπεν ω πληρης παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου παυση διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον αχρι καιρου παραχρημα δε [επεπεσεν]{.greek-omitted} [επεσεν]{.greek-added} επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε αποχωρησας απ αυτων υπεστρεψεν εις ιεροσολυμα[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει εστιν λογος εν υμιν παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη [πα]{.greek-added} [παροικια]{.greek-omitted} [ροικια]{.greek-added} εν γη αιγυπτω και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον ετροποφορησεν αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη επτα εν γη χανααν κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

και μετα ταυτα ως [ετεσιν]{.greek-omitted} [ετεσι]{.greek-added} τετρακοσιοις και [πεντηκοντα]{.greek-omitted} [πεντικοντα]{.greek-added} εδωκεν κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ υιον κις ανδρα εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμην]{.greek-added} ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και ειπεν μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν ηγαγεν τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-abbr}[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας τω [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου ο ιωαννης τον δρομον ελεγεν τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος της [σωτηριας]{.greek-abbr} ταυτης απεσταλη[13:26]{.aside}

οι γαρ κατοικουντες εν [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον [αγνοησαντες]{.greek-omitted} [αγνωησαντες]{.greek-added} και τας φωνας των προφητων τας κατα παν σαββατον αναγινωσκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις μνημειον[13:29]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας [πληους]{.greek-added} [πλειους]{.corr} τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες εισιν μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} [επαγγελιαν]{.greek-omitted} [επαγγελειαν]{.greek-added} γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκεν]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω τω δευτερω γεγραπται υιος μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον εκ νεκρων μηκετι μελλοντα υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και ειδεν διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ ειδεν διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν ανδρες αδελφοι οτι δια τουτου υμιν αφεσις αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται και θαυμασατε και αφανισθητε οτι εργον εγω εργαζομαι εν ταις ημεραις υμων ο ου μη πιστευσητε εαν τις [εκδιηγηται]{.greek-omitted} [εκδιηγειται]{.greek-added} υμιν[13:41]{.aside}

[εξιοντων]{.greek-omitted} [εξιωντων]{.greek-added} δε [αυτων]{.greek-added} εκ της συναγωγης των ιουδαιων παρεκαλουν τα εθνη εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

[λυθεισης]{.greek-omitted} [λυθησεις]{.greek-added} δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και [τω]{.greek-omitted} βαρναβα οιτινες προσλαλουντες επειθον αυτους επιμενειν τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

[τω]{.greek-omitted} [το]{.greek-added} τε ερχομενω σαββατω σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-abbr}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλου λεγομενοις [βλασ]{.greek-added} [αντιλεγοντες]{.greek-omitted} [και]{.greek-omitted} [βλασφημουντες]{.greek-omitted} [φημουντες]{.greek-added}[13:45]{.aside}

παρρησιασαμενοι δε ο παυλος και ο βαρναβας ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} επειδη δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ εντεταλται ημιν ο [κυριος]{.greek-abbr} [τεθεικα]{.greek-omitted} [τεθηκα]{.greek-added} σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον τον λογον του [κυριου]{.greek-abbr} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-abbr} δι ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας και τας ευσχημονας και τους πρωτους της πολεως και επηγειραν διωγμον επι τον παυλον και [τον]{.greek-omitted} βαρναβαν και εξεβαλον αυτους απο των οριων αυτων[13:50]{.aside}

οι δε εκτιναξαμενοι τον κονιορτον των ποδων αυτων επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι δε μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι [ιουδαιων]{.greek-omitted} [ελληνων]{.greek-added} τε και [ελληνων]{.greek-omitted} [ιουδαιων]{.greek-added} πολυ πληθος[14:1]{.aside}

οι δε απειθουντες ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου [και]{.greek-added} διδοντι σημεια και τερατα γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και λιθοβολησαι αυτους[14:5]{.aside}

[συνιδοντες]{.greek-omitted} [συνειδοντες]{.greek-added} κατεφυγον εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει ησαν ευαγγελιζομενοι[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων ος ουδεποτε περιπεπατηκει[14:8]{.aside}

ουτος ηκουσεν του παυλου λαλουντος ος ατενισας αυτω και ιδων οτι πιστιν εχει του σωθηναι[14:9]{.aside}

ειπεν μεγαλη τη φωνη αναστηθι επι τους ποδας σου [ορθως]{.greek-omitted} [ορθος]{.greek-added} και ηλλετο και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν ο παυλος επηραν την φωνην αυτων [λυκαονιστι]{.greek-omitted} [λυκαονιστη]{.greek-added} λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν [δια]{.greek-omitted} [διαν]{.greek-added} τον δε παυλον ερμην επειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο δε ιερευς του διος του οντος προ της πολεως αυτων ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις ηθελεν θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων εισεπηδησαν εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε και ημεις ομοιοπαθεις εσμεν υμιν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο τουτων των ματαιων επιστρεφειν επι τον [θεον]{.greek-abbr} τον ζωντα ος [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τον ουρανον και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις παρωχημεναις γενεαις [ειασεν]{.greek-omitted} [ιασαι]{.greek-added} παντα τα εθνη πορευεσθαι [ταις]{.greek-omitted} [τοις]{.greek-added} οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρον εαυτον [αφηκεν]{.greek-omitted} [ηφηκεν]{.greek-added} αγαθοποιων ουρανοθεν υμιν υετους διδους και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας ημων[14:17]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν [αυτο[υ]{.unclear}ς]{.greek-added} [αυτοις]{.corr}[14:18]{.aside}

επηλθον δε απο αντιοχειας και ικονιου ιουδαιοι και πεισαντες τους οχλους και λιθασαντες τον παυλον [εσυρον]{.greek-omitted} [εσυραν]{.greek-added} εξω της πολεως νομισαντες αυτον τεθναναι[14:19]{.aside}

κυκλωσαντων δε [αυτον]{.greek-omitted} [αυτων]{.greek-added} των μαθητων αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν συν τω βαρναβα εις δερβην[14:20]{.aside}

ευαγγελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν και ικονιον και αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει ημας εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε [αυτο[υ]{.unclear}ς]{.greek-added} [αυτοις]{.corr} πρεσβυτερους κατ εκκλησιαν προσευξαμενοι μετα νηστειων παρεθεντο [αυτους]{.greek-omitted} [αυτοις]{.greek-added} τω [κυριω]{.greek-abbr} εις ον πεπιστευκεισαν[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον εις παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον κατεβησαν εις [ατταλειαν]{.greek-omitted} [αταλειαν]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν παραδεδομενοι τη χαριτι του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν ανηγγειλαν οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} θυραν πιστεως[14:27]{.aside}

διετριβον δε εκει χρονον ουκ ολιγον συν τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη περιτεμνησθε τω εθει [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης [ουν]{.greek-omitted} [δε]{.greek-added} στασεως και ζητησεως ουκ ολιγης τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την φοινικην και σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις αδελφοις[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-abbr} απεδεχθησαν υπο της εκκλησιας και των αποστολων και των πρεσβυτερων ανηγγειλαν τε οσα ο [θεος]{.greek-abbr} εποιησεν μετ αυτων [και]{.greek-added} [οτι]{.greek-added} [ηνοιξεν]{.greek-added} [τοις]{.greek-added} [εθνεσιν]{.greek-added} [θυραν]{.greek-added} [πιστεως]{.greek-added}[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων [πεπιστευκοτες]{.greek-omitted} [πεπιστευκοτων]{.greek-added} λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added}[15:5]{.aside}

συνηχθησαν δε οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε συζητησεως γενομενης αναστας πετρος ειπεν προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων ο [θεος]{.greek-abbr} εν ημιν εξελεξατο δια του στοματος μου ακουσαι τα εθνη τον λογον του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και [ουδεν]{.greek-omitted} [ουθεν]{.greek-added} διεκρινεν μεταξυ ημων τε και αυτων τη πιστει καθαρισας τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} [επιθειναι]{.greek-omitted} [επιθηναι]{.greek-added} ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

[εσιγησεν]{.greek-omitted} [εσιγησε]{.greek-added} δε παν το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δι αυτων[15:12]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον επι τω ονοματι αυτου[15:14]{.aside}

και [τουτω]{.greek-omitted} [τουτο]{.greek-added} συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted}[15:17]{.aside}

γνωστα απ αιωνος εστιν τω [θεω]{.greek-abbr} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

αλλα επιστειλαι αυτοις του απεχεσθαι απο των αλισγηματων των ειδωλων και της [πορ]{.greek-added} [πορνειας]{.greek-omitted} [νειας]{.greek-added} και του πνικτου και του αιματος[15:20]{.aside}

[μωυσης]{.greek-omitted} [μωσης]{.greek-added} γαρ εκ γενεων αρχαιων κατα πολιν τους κηρυσσοντας αυτον εχει εν ταις συναγωγαις κατα παν σαββατον αναγινωσκομενος[15:21]{.aside}

τοτε [εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν παυλω και βαρναβα ιουδαν τον [επικαλουμενον]{.greek-omitted} [καλουμενον]{.greek-added} βαρσαββαν και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων [εξελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} εταραξαν υμας λογοις [ανασκευαζοντες]{.greek-omitted} [ανασκευγαζοντες]{.greek-added} τας ψυχας υμων λεγοντες περιτεμνεσθαι και τηρειν [τον]{.greek-omitted} [το]{.greek-added} νομον οις ου διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον [εκλεξαμενους]{.greek-omitted} [εκλεξαμενοις]{.greek-added} ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα και παυλω[15:25]{.aside}

[ανθρωποις]{.greek-abbr} [παραδεδωκοσιν]{.greek-omitted} [παραδεδωκοσι]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

[εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} γαρ τω αγιω [πνευματι]{.greek-abbr} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην των επαναγκες τουτων[15:28]{.aside}

απεχεσθαι ειδωλοθυτων και αιματος και πνικτου και πορνειας εξ ων διατηρουντες εαυτους ευ [πραξετε]{.greek-omitted} [πραξατε]{.greek-added} ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες ηλθον εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

[αναγνοντες]{.greek-omitted} [αναγνωντες]{.greek-added} δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης απο των αδελφων προς τους αποστολους[15:33]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας ειπεν παυλος προς βαρναβαν επιστρεψαντες δη επισκεψωμεθα τους αδελφους ημων κατα πασαν πολιν εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως εχουσιν[15:36]{.aside}

βαρναβας δε εβουλευσατο [συμπαραλαβειν]{.greek-omitted} [συνπαραλαβειν]{.greek-added} τον ιωαννην τον καλουμενον μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη συμπαραλαβειν τουτον[15:38]{.aside}

εγενετο ουν [παροξυσμος]{.greek-omitted} [παρωξυσμος]{.greek-added} ωστε αποχωρισθηναι [αυτους]{.greek-omitted} [αυτοις]{.greek-added} απ αλληλων τον τε βαρναβαν παραλαβοντα τον μαρκον [εκπλευσαι]{.greek-omitted} [εκπλευ]{.greek-added} [σαι]{.greek-added} εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν εξηλθεν παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και κιλικιαν επιστηριζων τας εκκλησιας[15:41]{.aside}

### Chapter 16

κατηντησεν δε εις δερβην και λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος υιος γυναικος τινος ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και [λαβων]{.greek-omitted} [περιετεμεν]{.greek-omitted} [αυτον]{.greek-omitted} [δια]{.greek-omitted} [τους]{.greek-omitted} ιουδαιους τους οντας εν τοις τοποις εκεινοις [ηδεισαν]{.greek-omitted} [ειδησαν]{.greek-added} γαρ απαντες τον [πατερα]{.greek-abbr} αυτου οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις παρεδιδουν αυτοις φυλασσειν τα δογματα τα κεκριμενα υπο των αποστολων και των πρεσβυτερων των εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και επερισσευον τω αριθμω καθ ημεραν[16:5]{.aside}

διελθοντες δε την φρυγιαν και την γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες κατα την [μυσιαν]{.greek-omitted} [μυειαν]{.greek-added} επειραζον κατα την βιθυνιαν πορευεσθαι και ουκ ειασεν αυτους το [πνευμα]{.greek-abbr}[16:7]{.aside}

παρελθοντες δε την [μυσιαν]{.greek-omitted} [μυειαν]{.greek-added} κατεβησαν εις τρωαδα[16:8]{.aside}

και οραμα δια της νυκτος ωφθη τω παυλω ανηρ τις ην μακεδων εστως παρακαλων αυτον και λεγων διαβας εις μακεδονιαν βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα ειδεν ευθεως εζητησαμεν εξελθειν εις [την]{.greek-omitted} μακεδονιαν συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι αυτους[16:10]{.aside}

αναχθεντες ουν απο της τρωαδος ευθυδρομησαμεν εις σαμοθρακην τη τε επιουση εις νεαπολιν[16:11]{.aside}

εκειθεν [τε]{.greek-omitted} [δε]{.greek-added} εις φιλιππους ητις εστιν πρωτη της μεριδος της μακεδονιας πολις [κολωνεια]{.greek-omitted} [κολωνια]{.greek-added} ημεν δε εν αυτη τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των σαββατων εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο προσευχη [[προσευχην]{.corr}]{.greek-added} ειναι και [καθισαντες]{.greek-omitted} [καθησαντες]{.greek-added} ελαλουμεν ταις συνελθουσαις γυναιξιν[16:13]{.aside}

και τις γυνη ονοματι λυδια [πορφυροπωλις]{.greek-omitted} [πορφυροπολεις]{.greek-added} πολεως [θυατειρων]{.greek-omitted} [θυατηρων]{.greek-added} σεβομενη τον [θεον]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουσεν]{.greek-added} ης ο [κυριος]{.greek-abbr} διηνοιξεν την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης [παρεκαλεσεν]{.greek-omitted} [παρεκαλεσε]{.greek-added} λεγουσα ει κεκρικατε με πιστην τω [κυριω]{.greek-abbr} ειναι εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην [παιδισκην]{.greek-omitted} [παιδισκειν]{.greek-added} τινα εχουσαν [πνευμα]{.greek-abbr} πυθωνος απαντησαι ημιν ητις εργασιαν πολλην [παρειχεν]{.greek-omitted} [παρειχε]{.greek-added} τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και [ημιν]{.greek-omitted} [τω]{.greek-added} [σιλα]{.greek-added} [εκραζεν]{.greek-omitted} [εκραζε]{.greek-added} λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον [σωτηριας]{.greek-abbr}[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} ειπεν παραγγελλω σοι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της εργασιας αυτων επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και καταγγελλουσιν [εθη]{.greek-omitted} [ηθη]{.greek-added} α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις ουσιν[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι [περιρρηξαντες]{.greek-omitted} [περιρηξαντες]{.greek-added} αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην ειληφως εβαλεν αυτους εις την εσωτεραν φυλακην και τους ποδας αυτων ησφαλισατο εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [επηκροωντο]{.greek-omitted} [επικροωντο]{.greek-added} δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του [δεσμωτηριου]{.greek-omitted} [δεσμοτηριου]{.greek-added} ανεωχθησαν τε παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} εαυτον αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

[εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} δε φωνη μεγαλη ο παυλος λεγων μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα εισεπηδησεν και εντρομος γενομενος [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και ο οικος σου[16:31]{.aside}

και ελαλησαν αυτω τον λογον του [κυριου]{.greek-abbr} και πασιν τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα της νυκτος ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου παντες παραχρημα[16:33]{.aside}

αναγαγων τε αυτους εις τον οικον αυτου [παρεθηκεν]{.greek-omitted} [παρεθηκε]{.greek-added} τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασατο]{.greek-added} πανοικι πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενομενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

[απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι [απεσταλκασιν]{.greek-omitted} [απεσταλκα]{.greek-added} [σιν]{.greek-added} οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας εκβαλλουσιν ου γαρ [αλλα]{.greek-omitted} [αλλ]{.greek-added} ελθοντες αυτοι [ημας]{.greek-added} εξαγαγετωσαν[16:37]{.aside}

ανηγγειλαν δε τοις στρατηγοις οι ραβδουχοι τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι εισιν[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και [εξαγαγοντες]{.greek-omitted} [εξαγαγωντες]{.greek-added} ηρωτων εξελθειν της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες τους αδελφους παρεκαλεσαν αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και απολλωνιαν ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το ειωθος τω παυλω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν ο [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων επεισθησαν και προσεκληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων πολυ πληθος γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

προσλαβομενοι δε οι ιουδαιοι οι [απειθουντες]{.greek-omitted} [απειθουν]{.greek-added} [τες]{.greek-added} των αγοραιων τινας ανδρας πονηρους και οχλοποιησαντες εθορυβουν την πολιν επισταντες τε τη οικια ιασονος εζητουν αυτους [αγαγειν]{.greek-omitted} [αναγαγειν]{.greek-added} εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τον ιασονα και τινας αδελφους επι τους πολιταρχας βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι και ενθαδε παρεισιν[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος πρασσουσιν βασιλεα λεγοντες ετερον ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον οχλον και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του ιασονος και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια της νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις βεροιαν οιτινες παραγενομενοι εις την συναγωγην απηεσαν των ιουδαιων[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας το καθ ημεραν ανακρινοντες τας γραφας ει εχοι ταυτα ουτως[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της θεσσαλονικης ιουδαιοι οτι και εν τη βεροια κατηγγελη υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι ως επι την θαλασσαν υπεμενον δε ο τε σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε καθιστωντες τον παυλον ηγαγον αυτον εως αθηνων και λαβοντες εντολην προς τον σιλαν και τιμοθεον ινα ως ταχιστα [ελθωσιν]{.greek-omitted} [ελθωσι]{.greek-added} προς αυτον [εξηεσαν]{.greek-omitted} [εξιεσαν]{.greek-added}[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου παρωξυνετο το [πνευμα]{.greek-abbr} αυτου εν αυτω θεωρουντι κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις σεβομενοις και εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε και των επικουρειων και των [στοικων]{.greek-omitted} [στωικων]{.greek-added} φιλοσοφων [συνεβαλλον]{.greek-omitted} [συνεβαλον]{.greek-added} αυτω και τινες ελεγον τι αν θελοι ο σπερμολογος ουτος λεγειν οι δε ξενων δαιμονιων δοκει καταγγελευς ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο[17:18]{.aside}

επιλαβομενοι τε αυτου επι τον [αρειον]{.greek-omitted} [αγριον]{.greek-added} παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι τι αν θελοι ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον ευκαιρουν η λεγειν τι και ακουειν καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως δεισιδαιμονεστερους υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και αναθεωρων τα σεβασματα υμων ευρον και βωμον εν ω επεγεγραπτο αγνωστω [θεω]{.greek-abbr} ον ουν αγνοουντες [ευσεβειτε]{.greek-omitted} [σεβητε]{.greek-added} τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [κυριος]{.greek-abbr} υπαρχων ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} θεραπευεται προσδεομενος τινος αυτος διδους πασιν ζωην και πνοην κατα παντα[17:25]{.aside}

εποιησεν τε εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ει αρα γε ψηλαφησειαν αυτον και ευροιεν και γε ου μακραν απο ενος εκαστου [ημων]{.greek-omitted} [υμων]{.greek-added} υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ υμας ποιητων ειρηκασιν του γαρ και γενος εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν χρυσω η αργυρω η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-abbr} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} [πασιν]{.greek-omitted} [πασι]{.greek-added} πανταχου μετανοειν[17:30]{.aside}

διοτι εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω [ωρισεν]{.greek-omitted} [ωρισε]{.greek-added} πιστιν παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον ακουσομεθα σου παλιν περι τουτου[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα ιουδαιον ονοματι ακυλαν ποντικον τω γενει προσφατως εληλυθοτα απο της [ιταλιας]{.greek-omitted} [ιταλειας]{.greek-added} και πρισκιλλαν γυναικα αυτου δια το τεταχεναι κλαυδιον χωριζεσθαι παντας τους ιουδαιους [εκ]{.greek-omitted} [απο]{.greek-added} της ρωμης προσηλθεν αυτοις[18:2]{.aside}

και δια το ομοτεχνον ειναι [εμενεν]{.greek-omitted} [εμεινεν]{.greek-added} παρ αυτοις και ειργαζετο ησαν γαρ σκηνοποιοι [την]{.greek-omitted} [τη]{.greek-added} [τεχνην]{.greek-omitted} [τεχνη]{.greek-added}[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον επειθεν τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο [της]{.greek-omitted} μακεδονιας ο τε σιλας και ο τιμοθεος συνειχετο τω [πνευματι]{.greek-abbr} ο παυλος διαμαρτυρομενος τοις ιουδαιοις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων εκτιναξαμενος τα ιματια ειπεν προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη [πορευσομαι]{.greek-omitted} [πορευομαι]{.greek-added}[18:6]{.aside}

και μεταβας εκειθεν ηλθεν εις οικιαν τινος ονοματι ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια ην συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος [επιστευσεν]{.greek-omitted} [επιστευσε]{.greek-added} τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} επιστευον και εβαπτιζοντο[18:8]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} δι οραματος εν νυκτι τω παυλω μη φοβου αλλα λαλει και μη σιωπησης[18:9]{.aside}

διοτι εγω ειμι μετα σου και ουδεις επιθησεται σοι του κακωσαι σε διοτι λαος [μοι]{.greek-added} εστιν [μοι]{.greek-omitted} πολυς εν τη πολει ταυτη[18:10]{.aside}

εκαθισεν τε ενιαυτον και μηνας εξ διδασκων εν αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της αχαιας κατεπεστησαν ομοθυμαδον οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον ουτος [αναπειθει]{.greek-omitted} [αναπειθη]{.greek-added} τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν ουν [ην]{.greek-omitted} αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν ηνεσχομην υμων[18:14]{.aside}

ει δε ζητημα [εστιν]{.greek-omitted} [εστι]{.greek-added} περι λογου και ονοματων και νομου του καθ υμας οψεσθε αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι δε παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω γαλλιωνι εμελλεν[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος την κεφαλην εν κεγχρεαις ειχεν γαρ ευχην[18:18]{.aside}

κατηντησεν δε εις εφεσον [και]{.greek-omitted} [εκεινους]{.greek-omitted} [κακεινους]{.greek-added} [κατελιπεν]{.greek-omitted} [κατελειπεν]{.greek-added} αυτου αυτος δε εισελθων εις την συναγωγην διελεχθη τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε [αυτων]{.greek-omitted} [αυτον]{.greek-added} επι πλειονα χρονον μειναι παρ αυτοις ουκ επενευσεν[18:20]{.aside}

αλλ απεταξατο αυτοις ειπων δει με παντως την εορτην την ερχομενην ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

και κατελθων εις καισαρειαν αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα εξηλθεν διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε αυτου ακυλας και πρισκιλλα προσελαβοντο αυτον και ακριβεστερον αυτω εξεθεντο την του [θεου]{.greek-abbr} οδον[18:26]{.aside}

βουλομενου δε αυτου διελθειν εις την αχαιαν προτρεψαμενοι οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος συνεβαλετο πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπιστευκοσι]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω τον [απολλω]{.greek-omitted} [απολλων]{.greek-added} ειναι εν κορινθω παυλον διελθοντα τα ανωτερικα μερη ελθειν εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

ειπεν προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε ειπον προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

ειπεν τε προς αυτους εις τι ουν εβαπτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

ειπεν δε παυλος ιωαννης μεν [εβαπτισεν]{.greek-omitted} [εβαπτισε]{.greek-added} βαπτισμα μετανοιας τω λαω λεγων εις τον ερχομενον μετ αυτον ινα [πιστευσωσιν]{.greek-omitted} [πιστευσωσι]{.greek-added} τουτ εστιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε [γλω]{.greek-added} [γλωσσαις]{.greek-omitted} [σσαις]{.greek-added} και προεφητευον[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει δεκαδυο[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους αποστας απ αυτων [αφωρισεν]{.greek-omitted} [αφωρισε]{.greek-added} τους μαθητας καθ ημεραν διαλεγομενος εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι [δυο]{.greek-added} ετη [δυο]{.greek-omitted} ωστε παντας τους κατοικουντας την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας εποιει ο [θεος]{.greek-abbr} δια των χειρων παυλου[19:11]{.aside}

ωστε και επι τους ασθενουντας επιφερεσθαι απο του χρωτος αυτου [επιφερεσθαι]{.greek-added} σουδαρια η σιμικινθια και απαλλασσεσθαι απ αυτων τας νοσους τα τε πνευματα τα πονηρα εξερχεσθαι απ αυτων[19:12]{.aside}

επεχειρησαν δε τινες απο των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους εχοντας τα πνευματα τα πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} λεγοντες ορκιζομεν υμας τον [ιησουν]{.greek-abbr} ον ο παυλος κηρυσσει[19:13]{.aside}

ησαν δε τινες υιοι σκευα [ιουδαιου]{.greek-omitted} [ιουδαιοι]{.greek-added} αρχιερεως επτα οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε το πνευμα το πονηρον ειπεν τον [ιησουν]{.greek-abbr} [γι]{.greek-added} [γινωσκω]{.greek-omitted} [νωσκω]{.greek-added} και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και εφαλλομενος επ αυτους ο [ανθρωπος]{.greek-abbr} εν ω ην το πνευμα το πονηρον και κατακυριευσαν αυτων ισχυσεν κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν εκ του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον πασιν ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} τοις [κατοικουσιν]{.greek-omitted} [κατοικουσι]{.greek-added} την εφεσον και [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι τε των πεπιστευκοτων ηρχοντο εξομολογουμενοι και αναγγελλοντες τας πραξεις αυτων[19:18]{.aside}

ικανοι δε των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και συνεψηφισαν τας τιμας αυτων και ευρον αργυριου μυριαδας πεντε[19:19]{.aside}

ουτως κατα κρατος ο λογος του [κυριου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και ισχυεν[19:20]{.aside}

ως δε επληρωθη ταυτα εθετο ο παυλος εν τω [πνευματι]{.greek-abbr} διελθων την μακεδονιαν και αχαιαν πορευεσθαι εις [ιερουσαλημ]{.greek-abbr} ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις την μακεδονιαν δυο των διακονουντων αυτω τιμοθεον και εραστον αυτος [επεσχεν]{.greek-omitted} [επεσχε]{.greek-added} χρονον εις την ασιαν[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος περι της οδου[19:23]{.aside}

δημητριος γαρ τις ονοματι αργυροκοπος ποιων ναους αργυρους αρτεμιδος παρειχετο τοις τεχνιταις εργασιαν ουκ ολιγην[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας ειπεν ανδρες επιστασθε οτι εκ ταυτης της εργασιας η ευπορια ημων εστιν[19:25]{.aside}

και θεωρειτε και ακουετε οτι ου μονον εφεσου αλλα [και]{.greek-added} σχεδον πασης της ασιας ο παυλος ουτος πεισας μετεστησεν ικανον οχλον λεγων οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} θεοι οι δια χειρων [γινομενοι]{.greek-omitted} [γενομενοι]{.greek-added}[19:26]{.aside}

ου μονον δε τουτο κινδυνευει ημιν το μερος εις απελεγμον ελθειν αλλα και το της μεγαλης θεας [αρτεμιδος]{.greek-added} ιερον [αρτεμιδος]{.greek-omitted} εις [ουθεν]{.greek-omitted} [ουδεν]{.greek-added} λογισθηναι μελλειν δε και καθαιρεισθαι την [μεγαλειοτητα]{.greek-omitted} [μεγαλειωτητα]{.greek-added} αυτης ην ολη η ασια και η οικουμενη σεβεται[19:27]{.aside}

ακουσαντες δε και γενομενοι [πληρεις]{.greek-omitted} [πληρης]{.greek-added} θυμου εκραζον λεγοντες μεγαλη η αρτεμις εφεσιων[19:28]{.aside}

και επλησθη η πολις ολη της συγχυσεως ωρμησαν τε ομοθυμαδον εις το θεατρον συναρπασαντες γαιον και αρισταρχον μακεδονας συνεκδημους παυλου[19:29]{.aside}

του δε παυλου βουλομενου εισελθειν εις τον δημον ουκ [ειων]{.greek-omitted} [ειον]{.greek-added} αυτον οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες αυτω φιλοι πεμψαντες προς αυτον παρεκαλουν μη δουναι εαυτον εις το θεατρον[19:31]{.aside}

αλλοι μεν ουν αλλο τι εκραζον ην γαρ η εκκλησια συγκεχυμενη και οι πλειους ουκ [ηδεισαν]{.greek-omitted} [ειδησαν]{.greek-added} τινος ενεκεν [συνεληλυθεισαν]{.greek-omitted} [συνεληλυθησαν]{.greek-added}[19:32]{.aside}

εκ δε του οχλου προεβιβασαν αλεξανδρον [προβαλοντων]{.greek-omitted} [προβαλλοντων]{.greek-added} [αυτων]{.greek-added} [αυτον]{.corr} των ιουδαιων ο δε αλεξανδρος κατασεισας την χειρα ηθελεν απολογεισθαι τω δημω[19:33]{.aside}

επιγνοντες δε οτι ιουδαιος εστιν φωνη εγενετο μια εκ παντων ως επι ωρας δυο κραζοντων μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλας δε ο γραμματευς τον οχλον φησιν ανδρες εφεσιοι τις γαρ εστιν [ανθρωπος]{.greek-abbr} ος ου γινωσκει την εφεσιων πολιν [νεωκορον]{.greek-omitted} [νεοκορον]{.greek-added} ουσαν της μεγαλης θεας αρτεμιδος και του διοπετους[19:35]{.aside}

[αναντιρρητων]{.greek-omitted} [αναντηρητων]{.greek-added} ουν οντων τουτων δεον εστιν υμας κατεσταλμενους υπαρχειν και μηδεν προπετες πρασσειν[19:36]{.aside}

ηγαγετε γαρ τους ανδρας τουτους ουτε ιεροσυλους ουτε βλασφημουντας την θεον υμων[19:37]{.aside}

ει μεν ουν δημητριος και οι συν αυτω τεχνιται [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν εγκαλειτωσαν αλληλοις[19:38]{.aside}

ει δε τι περι ετερων επιζητειτε εν τη εννομω εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι της σημερον μηδενος αιτιου υπαρχοντος περι [ου]{.greek-omitted} [ουν]{.greek-added} ου δυνησομεθα δουναι λογον της συστροφης ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσεν]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον θορυβον προσκαλεσαμενος ο παυλος τους μαθητας και ασπασαμενος [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} πορευθηναι εις [την]{.greek-omitted} μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας τε μηνας τρεις γενομενης [δε]{.greek-added} αυτω επιβουλης υπο των ιουδαιων μελλοντι αναγεσθαι εις την συριαν εγενετο γνωμη του υποστρεφειν δια μακεδονιας[20:3]{.aside}

[συνειπετο]{.greek-omitted} [συνειπετω]{.greek-added} δε αυτω αχρι της ασιας σωπατρος [βεροιαιος]{.greek-omitted} [βηροιαιος]{.greek-added} [θεσσαλονικεων]{.greek-omitted} [θεσσαλονικαιων]{.greek-added} δε αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος ασιανοι δε τυχικος και τροφιμος[20:4]{.aside}

ουτοι προσελθοντες εμενον ημας εν τρωαδι[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και ηλθομεν προς αυτους εις την τρωαδα αχρι ημερων πεντε ου διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων των μαθητων κλασαι αρτον ο παυλος διελεγετο αυτοις μελλων εξιεναι τη επαυριον παρετεινεν τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε [λα]{.greek-added} [λαμπαδες]{.greek-omitted} [μπαδες]{.greek-added} ικαναι εν τω υπερωω ου ημεν συνηγμενοι[20:8]{.aside}

καθημενος δε τις νεανιας ονοματι ευτυχος επι της θυριδος καταφερομενος υπνω βαθει διαλεγομενου του παυλου επι πλειον κατενεχθεις απο του υπνου επεσεν απο του τριστεγου κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και συμπεριλαβων ειπεν μη θορυβεισθε η γαρ ψυχη αυτου εν [αυτω]{.greek-omitted} [εαυτω]{.greek-added} εστιν[20:10]{.aside}

αναβας δε και κλασας αρτον και γευσαμενος εφ ικανον τε ομιλησας [αχρι]{.greek-omitted} [αχρις]{.greek-added} αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον δε τον παιδα ζωντα και παρεκληθησαν ου μετριως[20:12]{.aside}

ημεις δε [προσελθοντες]{.greek-omitted} [προελθοντες]{.greek-added} επι το πλοιον ανηχθημεν εις την [ασσον]{.greek-omitted} [θασον]{.greek-added} εκειθεν μελλοντες αναλαμβανειν τον παυλον ουτως γαρ ην διατεταγμενος μελλων αυτος πεζευειν[20:13]{.aside}

ως δε συνεβαλεν ημιν εις την ασσον αναλαβοντες αυτον [ανηλθομεν]{.greek-added} [ηλθομεν]{.corr} εις [μιτυληνην]{.greek-omitted} [μυτυλινην]{.greek-added}[20:14]{.aside}

κακειθεν αποπλευσαντες τη επιουση κατηντησαμεν [αντικρυ]{.greek-omitted} [αντικρυς]{.greek-added} χιου τη δε ετερα παρεβαλομεν εις σαμον και μειναντες εν [τρωγυλλιω]{.greek-omitted} [τρογυλιω]{.greek-added} τη εχομενη ηλθομεν εις μιλητον[20:15]{.aside}

[εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} γαρ ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια [εσπευδεν]{.greek-omitted} [εσπευδε]{.greek-added} γαρ ει δυνατον ην αυτω την ημεραν της [πεντηκοστης]{.greek-omitted} [πεν]{.greek-added} [τικοστης]{.greek-added} γενεσθαι εις ιεροσολυμα[20:16]{.aside}

απο δε της μιλητου πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον ειπεν αυτοις υμεις επιστασθε απο πρωτης ημερας αφ ης επεβην εις την ασιαν πως μεθ υμων τον παντα χρονον εγενομην[20:18]{.aside}

δουλευων τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και πολλων δακρυων και πειρασμων των συμβαντων μοι εν ταις επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων του μη αναγγειλαι υμιν και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

διαμαρτυρομενος ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} την εις τον [θεον]{.greek-abbr} μετανοιαν και πιστιν την εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr}[20:21]{.aside}

και νυν ιδου εγω δεδεμενος τω [πνευματι]{.greek-abbr} πορευομαι εις [ιερουσαλημ]{.greek-abbr} τα εν αυτη συναντησοντα μοι μη ειδως[20:22]{.aside}

πλην οτι το [πνευμα]{.greek-abbr} το αγιον κατα πολιν διαμαρτυρεται [λεγον]{.greek-omitted} [λεγων]{.greek-added} οτι δεσμα με και θλιψεις μενουσιν[20:23]{.aside}

αλλ ουδενος λογον ποιουμαι ουδε εχω την ψυχην [μου]{.greek-omitted} τιμιαν εμαυτω ως τελειωσαι τον δρομον μου μετα χαρας και την διακονιαν ην ελαβον παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι οψεσθε το προσωπον μου υμεις [παντες]{.greek-omitted} [παν]{.greek-added} [τες]{.greek-added} εν οις διηλθον κηρυσσων την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

[διοτι]{.greek-omitted} [διο]{.greek-added} μαρτυρομαι υμιν εν τη σημερον ημερα οτι καθαρος εγω απο του αιματος παντων[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι υμιν πασαν την βουλην του [θεου]{.greek-abbr}[20:27]{.aside}

προσεχετε ουν εαυτοις και παντι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επισκοπους ποιμαινειν την εκκλησιαν του [κυριου]{.greek-abbr} και [θεου]{.greek-abbr} ην περιεποιησατο δια του ιδιου αιματος[20:28]{.aside}

εγω γαρ οιδα τουτο οτι εισελευσονται μετα την [αφιξιν]{.greek-omitted} [αφηξιν]{.greek-added} μου [λυκοι]{.greek-omitted} [λοικοι]{.greek-added} βαρεις εις υμας μη φειδομενοι του ποιμνιου[20:29]{.aside}

και εξ υμων αυτων αναστησονται ανδρες λαλουντες διεστραμμενα του αποσπαν τους μαθητας οπισω αυτων[20:30]{.aside}

διο γρηγορειτε μνημονευοντες οτι τριετιαν νυκτα και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον[20:31]{.aside}

και τα νυν παρατιθεμαι υμας αδελφοι τω [θεω]{.greek-abbr} και τω λογω της χαριτος αυτου τω δυναμενω εποικοδομησαι και δουναι υμιν κληρονομιαν εν τοις ηγιασμενοις πασιν[20:32]{.aside}

αργυριου η χρυσιου η ιματισμου ουδενος επεθυμησα[20:33]{.aside}

αυτοι γινωσκετε οτι ταις χρειαις μου και τοις [ουσιν]{.greek-omitted} [ουση]{.greek-added} μετ εμου υπηρετησαν αι χειρες αυται[20:34]{.aside}

παντα υπεδειξα υμιν οτι ουτως [κο]{.greek-added} [κοπιωντας]{.greek-omitted} [πιωντας]{.greek-added} δει αντιλαμβανεσθαι των ασθενουντων μνημονευειν τε [των]{.greek-omitted} [τον]{.greek-added} [λογων]{.greek-omitted} [λογον]{.greek-added} του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} οτι αυτος ειπεν μακαριον εστιν μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα γονατα αυτου [συν]{.greek-omitted} [πασιν]{.greek-omitted} [συμπασιν]{.greek-added} αυτοις προσηυξατο[20:36]{.aside}

ικανος δε εγενετο κλαυθμος παντων και επιπεσοντες επι τον τραχηλον του παυλου κατεφιλουν αυτον[20:37]{.aside}

[οδυνωμενοι]{.greek-omitted} [οδυνομενοι]{.greek-added} μαλιστα επι τω λογω ω ειρηκει οτι ουκετι [μελλουσιν]{.greek-omitted} [μελλουσι]{.greek-added} το προσωπον αυτου θεωρειν προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας [αποσπασθεντας]{.greek-omitted} [αποσπασθεντες]{.greek-added} απ αυτων ευθυδρομησαντες ηλθομεν εις την κων τη δε εξης εις την ροδον κακειθεν εις παταρα[21:1]{.aside}

και ευροντες πλοιον [διαπερων]{.greek-omitted} [διαπερον]{.greek-added} εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

αναφανεντες δε την κυπρον και [καταλιποντες]{.greek-omitted} [καταλειποντες]{.greek-added} αυτην ευωνυμον [επλει]{.greek-added} [επλεομεν]{.corr} εις συριαν και κατηχθημεν εις τυρον [εκεισε]{.greek-omitted} [εκεισαι]{.greek-added} γαρ ην το πλοιον αποφορτιζομενον τον γομον[21:3]{.aside}

και ανευροντες μαθητας επεμειναμεν [αυτου]{.greek-omitted} [αυτοις]{.greek-added} ημερας επτα οιτινες τω παυλω ελεγον δια του [πνευματος]{.greek-abbr} μη αναβαινειν εις [ιερουσαλημ]{.greek-abbr}[21:4]{.aside}

οτε δε εγενετο ημας εξαρτισαι τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και τεκνοις εως εξω της πολεως και θεντες τα γονατα επι τον αιγιαλον [προσηυξαμεθα]{.greek-omitted} [προσευξαμεθα]{.greek-added}[21:5]{.aside}

και ασπασαμενοι αλληλους επεβημεν εις το πλοιον εκεινοι δε υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν διανυσαντες απο τυρου κατηντησαμεν εις [πτολεμαιδα]{.greek-omitted} [πτωλεμαιδα]{.greek-added} και ασπασαμενοι τους αδελφους εμειναμεν ημεραν μιαν παρ αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες οι περι τον παυλον ηλθον εις καισαρειαν και εισελθοντες εις τον οικον φιλιππου του ευαγγελιστου οντος εκ των επτα εμειναμεν παρ αυτω[21:8]{.aside}

τουτω δε ησαν θυγατερες παρθενοι τεσσαρες προφητευουσαι[21:9]{.aside}

επιμενοντων δε ημων ημερας πλειους κατηλθεν τις [προφητης]{.greek-added} απο της ιουδαιας [προφητης]{.greek-omitted} ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρας την ζωνην του παυλου δησας τε αυτου τους ποδας και τας χειρας ειπεν ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τον ανδρα ου εστιν η ζωνη αυτη ουτως δησουσιν εν [ιερουσαλημ]{.greek-abbr} οι ιουδαιοι και παραδωσουσιν εις χειρας εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκαλουμεν ημεις τε και οι εντοπιοι του μη αναβαινειν αυτον εις [ιερουσαλημ]{.greek-abbr}[21:12]{.aside}

απεκριθη τε ο παυλος τι ποιειτε κλαιοντες και συνθρυπτοντες μου την καρδιαν εγω γαρ ου μονον δεθηναι αλλα και αποθανειν εις [ιερουσαλημ]{.greek-abbr} [ετοιμως]{.greek-omitted} [ετυμως]{.greek-added} εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου ησυχασαμεν ειποντες το θελημα του [κυριου]{.greek-abbr} γενεσθω[21:14]{.aside}

μετα δε τας ημερας ταυτας επισκευασαμενοι [αν[α]{.unclear}βαινομεν]{.greek-added} [ανεβαινομεν]{.corr} εις [ιερουσαλημ]{.greek-abbr}[21:15]{.aside}

συνηλθον δε και των μαθητων απο καισαρειας συν ημιν αγοντες παρ ω ξενισθωμεν μνασωνι τινι κυπριω αρχαιω μαθητη[21:16]{.aside}

γενομενων δε ημων εις ιεροσολυμα ασμενως εδεξαντο ημας οι αδελφοι[21:17]{.aside}

τη δε επιουση εισηει ο παυλος συν ημιν προς ιακωβον παντες τε παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος [αυτους]{.greek-omitted} [αυτοις]{.greek-added} εξηγειτο καθ εν εκαστον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις εθνεσιν [[εθνεσι]{.corr}]{.greek-added} δια της διακονιας αυτου[21:19]{.aside}

οι δε [ακουσαντες]{.greek-omitted} [ακουοντες]{.greek-added} εδοξαζον τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} [ειποντες]{.greek-omitted} [ειπον]{.greek-added} [τε]{.greek-added} αυτω θεωρεις αδελφε ποσαι μυριαδες εισιν ιουδαιων των πεπιστευκοτων και παντες ζηλωται του νομου υπαρχουσιν[21:20]{.aside}

κατηχηθησαν δε περι σου οτι αποστασιαν διδασκεις απο [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} τους κατα τα εθνη παντας ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} περιπατειν[21:21]{.aside}

τι ουν εστιν [παντως]{.greek-omitted} [παντος]{.greek-added} δει πληθος συνελθειν ακουσονται γαρ οτι εληλυθας[21:22]{.aside}

τουτο ουν ποιησον ο σοι λεγομεν εισιν ημιν ανδρες τεσσαρες ευχην εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων αγνισθητι συν αυτοις και δαπανησον επ αυτοις ινα [ξυρησωνται]{.greek-omitted} [ξυρισων]{.greek-added} την κεφαλην και [γνωσιν]{.greek-omitted} [γνωσι]{.greek-added} παντες οτι ων κατηχηνται περι σου ουδεν εστιν αλλα στοιχεις και αυτος τον νομον φυλασσων[21:24]{.aside}

περι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες μηδεν τοιουτον τηρειν αυτους ει μη φυλασσεσθαι αυτους το τε ειδωλοθυτον και το αιμα και πνικτον και πορνειαν[21:25]{.aside}

τοτε ο παυλος παραλαβων τους ανδρας τη εχομενη ημερα συν αυτοις αγνισθεις [εισηει]{.greek-omitted} [εισειη]{.greek-added} εις το ιερον διαγγελλων την εκπληρωσιν των ημερων του αγνισμου εως ου προσηνεχθη υπερ ενος εκαστου αυτων η προσφορα[21:26]{.aside}

ως δε [εμελλον]{.greek-omitted} [ημελλον]{.greek-added} αι επτα ημεραι συντελεισθαι οι απο της ασιας ιουδαιοι θεασαμενοι αυτον εν τω ιερω συνεχεον παντα τον οχλον και επεβαλον τας χειρας επ αυτον[21:27]{.aside}

κραζοντες ανδρες ισραηλιται βοηθειτε ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου τουτου παντας πανταχου διδασκων ετι τε και ελληνας εισηγαγεν εις το ιερον και [κεκοινωκεν]{.greek-omitted} [κεκοινωκε]{.greek-added} τον αγιον τοπον τουτον[21:28]{.aside}

ησαν γαρ [εωρακοτες]{.greek-omitted} [εορακοτες]{.greek-added} τροφιμον τον εφεσιον εν τη πολει συν αυτω ον [ενομιζον]{.greek-omitted} [ενομι]{.greek-added} [ζον]{.greek-added} οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

[εκινηθη]{.greek-omitted} [εκεινηθη]{.greek-added} τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του παυλου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

ζητουντων δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της σπειρης οτι ολη συγκεχυται [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και εκατονταρχους κατεδραμεν επ αυτους οι δε ιδοντες τον χιλιαρχον και τους στρατιωτας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

εγγισας δε ο χιλιαρχος επελαβετο [αυτου]{.greek-omitted} [αυτον]{.greek-added} και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δεθηναι [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} και επυνθανετο τις αν ειη και τι εστιν πεποιηκως[21:33]{.aside}

αλλοι δε [αλλο]{.greek-omitted} [αλλ]{.greek-added} [τι]{.greek-omitted} [οτι]{.greek-added} εβοων εν τω οχλω μη δυναμενος δε γνωναι το ασφαλες δια τον θορυβον εκελευσεν αγεσθαι αυτον εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον υπο των στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

[ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} γαρ το πληθος του λαου κραζον αιρε αυτον[21:36]{.aside}

μελλων τε εισαγεσθαι εις την παρεμβολην ο παυλος λεγει τω χιλιαρχω ει εξεστιν μοι ειπειν προς σε ο δε εφη [ελληνιστι]{.greek-omitted} [ελληνιστη]{.greek-added} γινωσκεις[21:37]{.aside}

ουκ αρα συ ει ο αιγυπτιος ο προ τουτων των ημερων αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

ειπεν δε ο παυλος εγω [ανθρωπος]{.greek-abbr} μεν ειμι ιουδαιος ταρσευς της κιλικιας ουκ [ασημου]{.greek-omitted} [ασιμου]{.greek-added} πολεως πολιτης δεομαι [δε]{.greek-omitted} σου επιτρεψον μοι λαλησαι προς τον λαον[21:39]{.aside}

επιτρεψαντος δε αυτου ο παυλος εστως επι των αναβαθμων [κατεσεισεν]{.greek-omitted} [κατεσεισε]{.greek-added} τη χειρι τω λαω πολλης δε σιγης γενομενης [προσεφωνει]{.greek-omitted} [προσεφωνησε]{.greek-added} τη εβραιδι διαλεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς [υμας]{.greek-omitted} [ημας]{.greek-added} νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη εβραιδι διαλεκτω [προσεφωνει]{.greek-omitted} [προσεφωνησεν]{.greek-added} αυτοις μαλλον παρεσχον ησυχιαν και φησιν[22:2]{.aside}

εγω μεν ειμι ανηρ ιουδαιος γεγεννημενος εν ταρσω της κιλικιας ανατεθραμμενος δε εν τη πολει ταυτη παρα τους ποδας γαμαλιηλ πεπαιδευμενος κατα ακριβειαν του πατρωου νομου ζηλωτης υπαρχων του [θεου]{.greek-abbr} καθως παντες υμεις εστε σημερον[22:3]{.aside}

ος ταυτην την οδον εδιωξα αχρι θανατου δεσμευων και παραδιδους εις φυλακας ανδρας τε και γυναικας[22:4]{.aside}

ως και ο αρχιερευς μαρτυρει μοι και παν το πρεσβυτεριον παρ ων και επιστολας δεξαμενος προς τους αδελφους εις [δαμασκον]{.greek-omitted} [δαμασκων]{.greek-added} επορευομην αξων και τους εκεισε οντας δεδεμενους εις [ιερουσαλημ]{.greek-abbr} ινα [τιμωρηθωσιν]{.greek-omitted} [τιμωριθωσιν]{.greek-added}[22:5]{.aside}

εγενετο δε μοι πορευομενω και εγγιζοντι τη δαμασκω περι μεσημβριαν εξαιφνης εκ του [ουρανου]{.greek-abbr} περιαστραψαι φως ικανον περι εμε[22:6]{.aside}

[επεσα]{.greek-omitted} [επεσον]{.greek-added} τε εις το εδαφος και ηκουσα φωνης λεγουσης μοι σαουλ σαουλ τι με διωκεις[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} ειπεν τε προς με εγω ειμι [ιησους]{.greek-abbr} ο ναζωραιος ον συ διωκεις[22:8]{.aside}

οι δε συν εμοι οντες το μεν φως εθεασαντο και εμφοβοι εγενοντο την δε φωνην ουκ ηκουσαν του λαλουντος μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν προς με αναστας πορευου εις [δαμασκον]{.greek-omitted} [δαμασκων]{.greek-added} κακει σοι λαληθησεται περι παντων ων τετακται σοι ποιησαι[22:10]{.aside}

ως δε ουκ ενεβλεπον απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι ηλθον εις [δαμασκον]{.greek-omitted} [δαμασκων]{.greek-added}[22:11]{.aside}

ανανιας δε τις ανηρ [ευσεβης]{.greek-omitted} [ευλαβης]{.greek-added} κατα τον νομον μαρτυρουμενος υπο παντων των κατοικουντων [εν]{.greek-added} [δαμασκω]{.greek-added} ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας ειπεν μοι σαουλ αδελφε αναβλεψον καγω αυτη τη ωρα ανεβλεψα εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [προεχειρισατο]{.greek-omitted} [προεχειρησατο]{.greek-added} σε γνωναι το θελημα αυτου και ιδειν τον δικαιον και ακουσαι φωνην εκ του στοματος αυτου[22:14]{.aside}

οτι εση μαρτυς αυτω προς παντας ανθρωπους ων [εωρακας]{.greek-omitted} [εορακας]{.greek-added} και ηκουσας[22:15]{.aside}

και νυν τι μελλεις αναστας βαπτισαι και απολουσαι τας αμαρτιας σου επικαλεσαμενος το ονομα του [κυριου]{.greek-abbr}[22:16]{.aside}

εγενετο δε μοι υποστρεψαντι εις [ιερουσαλημ]{.greek-abbr} και προσευχομενου μου εν τω ιερω γενεσθαι [με]{.greek-omitted} [μοι]{.greek-added} εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον και εξελθε εν ταχει εξ [ιερουσαλημ]{.greek-abbr} διοτι ου παραδεξονται σου την μαρτυριαν περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω ημην φυλακιζων και δερων κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε εξεχειτο το αιμα στεφανου του [μαρτυρος]{.greek-omitted} [πρωτομαρτυρος]{.greek-added} σου και αυτος ημην εφεστως και συνευδοκων τη αναιρεσει αυτου φυλασσων τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και ειπεν προς με πορευου οτι εγω εις εθνη μακραν εξαποστελω σε[22:21]{.aside}

ηκουον δε αυτου αχρι τουτου του λογου και επηραν την φωνην αυτων λεγοντες αιρε απο της γης τον τοιουτον ου γαρ καθηκεν αυτον ζην[22:22]{.aside}

[κραζοντων]{.greek-omitted} [κραυγαζοντων]{.greek-added} δε αυτων και [ριπτουντων]{.greek-omitted} [ριπτοντων]{.greek-added} τα ιματια και κονιορτον βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν αυτον ο χιλιαρχος αγεσθαι εις την παρεμβολην ειπων μαστιξιν ανεταζεσθαι αυτον ινα επιγνω δι ην αιτιαν ουτως επεφωνουν αυτω[22:24]{.aside}

ως δε [προετεινεν]{.greek-omitted} [προετειναν]{.greek-added} αυτον τοις ιμασιν ειπεν προς τον εστωτα εκατονταρχον ο παυλος ει [ανθρωπον]{.greek-abbr} ρωμαιον και ακατακριτον εξεστιν υμιν μαστιζειν[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τω χιλιαρχω λεγων ορα τι μελλεις ποιειν ο γαρ [ανθρωπος]{.greek-abbr} ουτος ρωμαιος εστιν[22:26]{.aside}

προσελθων δε ο χιλιαρχος ειπεν [αυτω]{.greek-omitted} [τω]{.greek-added} [παυλω]{.greek-added} λεγε μοι ει συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκριθη [τε]{.greek-omitted} ο χιλιαρχος εγω πολλου κεφαλαιου την [πολιτειαν]{.greek-omitted} [πολιτιαν]{.greek-added} ταυτην εκτησαμην ο δε παυλος εφη εγω δε και γεγεννημαι[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες αυτον ανεταζειν και ο χιλιαρχος δε εφοβηθη επιγνους οτι ρωμαιος εστιν και οτι ην αυτον δεδεκως[22:29]{.aside}

τη δε επαυριον βουλομενος γνωναι το ασφαλες το τι κατηγορειται παρα των ιουδαιων ελυσεν αυτον απο των δεσμων και εκελευσεν ελθειν τους αρχιερεις και ολον το συνεδριον [των]{.greek-added} [αυτων]{.corr} και καταγαγων τον παυλον εστησεν εις αυτους[22:30]{.aside}

### Chapter 23

ατενισας δε ο παυλος τω συνεδριω ειπεν ανδρες [αδελφοι]{.greek-omitted} [αδελ]{.greek-added} [φοι]{.greek-added} εγω παση συνειδησει αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι ταυτης της ημερας[23:1]{.aside}

ο δε αρχιερευς ανανιας [επεταξεν]{.greek-omitted} [επεταξε]{.greek-added} τοις παρεστωσιν αυτω τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον ειπεν τυπτειν σε μελλει ο [θεος]{.greek-abbr} τοιχε κεκονιαμενε και συ καθη κρινων με κατα τον νομον και παρανομων κελευεις με τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες ειπον τον αρχιερεα του [θεου]{.greek-abbr} [λοιδορεις]{.greek-omitted} [λυδορεις]{.greek-added}[23:4]{.aside}

εφη τε ο παυλος ουκ [ηδειν]{.greek-omitted} [ειδειν]{.greek-added} αδελφοι οτι εστιν αρχιερευς γεγραπται γαρ αρχοντα του λαου σου ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος εστιν σαδδουκαιων το δε ετερον [των]{.greek-added} φαρισαιων εκραξεν εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμι υιος φαρισαιου περι ελπιδος και αναστασεως νεκρων εγω κρινομαι[23:6]{.aside}

τουτο δε αυτου λαλησαντος εγενετο στασις των φαρισαιων και [των]{.greek-added} [σαδδουκαιων]{.greek-added} [και]{.greek-added} εσχισθη το πληθος[23:7]{.aside}

σαδδουκαιοι μεν γαρ λεγουσιν μη ειναι αναστασιν μηδε αγγελον μητε [πνευμα]{.greek-abbr} φαρισαιοι δε [ομολογουσιν]{.greek-omitted} [ομολογουσι]{.greek-added} τα αμφοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και ανασταντες [οι]{.greek-omitted} γραμματεις του μερους των φαρισαιων διεμαχοντο λεγοντες ουδεν κακον ευρισκομεν εν τω [ανθρωπω]{.greek-abbr} τουτω ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω η αγγελος μη [θεομαχωμεν]{.greek-omitted} [θεομα]{.greek-added} [χωμεν]{.greek-added}[23:9]{.aside}

πολλης δε γενομενης στασεως ευλαβηθεις ο χιλιαρχος μη διασπασθη ο παυλος υπ αυτων [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} το στρατευμα καταβηναι και αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση νυκτι επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν θαρσει παυλε ως γαρ διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} ουτως σε δει και εις ρωμην μαρτυρησαι[23:11]{.aside}

γενομενης δε ημερας ποιησαντες [συστροφην]{.greek-added} τινες των ιουδαιων [συστροφην]{.greek-omitted} ανεθεματισαν εαυτους λεγοντες μητε φαγειν μητε πιειν εως ου [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} τον παυλον[23:12]{.aside}

ησαν δε πλειους τεσσαρακοντα οι ταυτην την συνωμοσιαν [πεποιηκοτες]{.greek-omitted} [ποιησαντες]{.greek-added}[23:13]{.aside}

οιτινες προσελθοντες τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις ειπον αναθεματι ανεθεματισαμεν εαυτους [μηδενος]{.greek-omitted} [μηθενος]{.greek-added} γευσασθαι εως ου αποκτεινωμεν τον παυλον[23:14]{.aside}

νυν ουν υμεις εμφανισατε τω χιλιαρχω συν τω συνεδριω οπως αυριον [καταγαγη]{.greek-added} αυτον [καταγαγη]{.greek-omitted} προς υμας ως μελλοντας διαγινωσκειν ακριβεστερον τα περι αυτου ημεις δε προ του εγγισαι αυτον ετοιμοι εσμεν του ανελειν αυτον[23:15]{.aside}

ακουσας δε ο υιος της αδελφης παυλου το ενεδρον παραγενομενος και εισελθων εις την παρεμβολην [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τω παυλω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων εφη τον νεανιαν τουτον απαγαγε προς τον χιλιαρχον εχει γαρ τι απαγγειλαι αυτω[23:17]{.aside}

ο μεν ουν παραλαβων αυτον ηγαγεν προς τον χιλιαρχον και φησιν ο δεσμιος παυλος προσκαλεσαμενος με [ηρωτησεν]{.greek-omitted} [ηρωτησε]{.greek-added} τουτον τον νεανιαν αγαγειν προς σε εχοντα τι λαλησαι σοι[23:18]{.aside}

επιλαβομενος δε της χειρος αυτου ο χιλιαρχος και αναχωρησας κατ ιδιαν [επυνθανετο]{.greek-omitted} [εποινθανετο]{.greek-added} τι εστιν ο εχεις απαγγειλαι μοι[23:19]{.aside}

ειπεν δε οτι οι ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον [καταγαγης]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} εις το συνεδριον [καταγαγης]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} ως μελλοντα τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ ουν μη [πεισθης]{.greek-omitted} [πισθης]{.greek-added} αυτοις [ενεδρευουσιν]{.greek-omitted} [ενεδρευουσι]{.greek-added} γαρ αυτον εξ αυτων ανδρες πλειους τεσσαρακοντα οιτινες ανεθεματισαν εαυτους μητε φαγειν μητε πιειν εως ου ανελωσιν αυτον και νυν ετοιμοι εισιν προσδεχομενοι την απο σου επαγγελιαν[23:21]{.aside}

ο μεν ουν χιλιαρχος [απελυσεν]{.greek-omitted} [απελυσε]{.greek-added} τον νεανιαν παραγγειλας μηδενι εκλαλησαι οτι ταυτα [ενεφανισας]{.greek-omitted} [ενεφανησας]{.greek-added} προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους οπως πορευθωσιν εως καισαρειας και ιππεις εβδομηκοντα και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

κτηνη τε παραστησαι ινα [επιβιβασαντες]{.greek-omitted} [επιβηβασαντες]{.greek-added} τον παυλον [διασωσωσιν]{.greek-omitted} [διασωσωσι]{.greek-added} προς φηλικα τον ηγεμονα[23:24]{.aside}

γραψας επιστολην περιεχουσαν τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω ηγεμονι φηλικι χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο των ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι εξειλομην αυτον μαθων οτι ρωμαιος εστιν[23:27]{.aside}

βουλομενος δε γνωναι την αιτιαν δι ην ενεκαλουν αυτω κατηγαγον αυτον εις το συνεδριον αυτων[23:28]{.aside}

ον [ευρον]{.greek-omitted} [ηυρον]{.greek-added} εγκαλουμενον περι ζητηματων του νομου αυτων μηδεν αξιον θανατου η δεσμων εγκλημα εχοντα[23:29]{.aside}

μηνυθεισης δε μοι επιβουλης εις τον ανδρα μελλειν εσεσθαι υπο των ιουδαιων εξαυτης [ουν]{.greek-added} επεμψα προς σε παραγγειλας και τοις κατηγοροις λεγειν τα προς αυτον [αυτους]{.greek-added} επι σου ερρωσο[23:30]{.aside}

οι μεν ουν στρατιωται κατα το διατεταγμενον αυτοις [εποιουν]{.greek-added} αναλαβοντες τον παυλον ηγαγον δια της νυκτος εις την αντιπατριδα[23:31]{.aside}

τη δε [επαυριον]{.greek-omitted} [επαυρι]{.greek-added} [ον]{.greek-added} εασαντες τους ιππεις πορευεσθαι συν αυτω υπεστρεψαν εις την παρεμβολην[23:32]{.aside}

οιτινες εισελθοντες εις την καισαρειαν και αναδοντες [τω]{.greek-added} [ηγεμονι]{.greek-added} την επιστολην [τω]{.greek-omitted} [ηγεμονι]{.greek-omitted} παρεστησαν και τον παυλον αυτω[23:33]{.aside}

αναγνους δε ο ηγεμων και [επερωτησας]{.greek-omitted} [ερωτησας]{.greek-added} εκ ποιας επαρχιας εστιν και πυθομενος οτι απο [της]{.greek-added} κιλικιας[23:34]{.aside}

διακουσομαι σου εφη οταν και οι κατηγοροι σου [παραγενωνται]{.greek-omitted} [παραγενονται]{.greek-added} εκελευσεν τε αυτον εν τω πραιτωριω ηρωδου φυλασσεσθαι[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη ο αρχιερευς ανανιας μετα των πρεσβυτερων και ρητορος τερτυλλου τινος οιτινες [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} τω [ηγεμονι]{.greek-omitted} [ηγεμωνι]{.greek-added} κατα του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο κατηγορειν ο τερτυλλος λεγων πολλης ειρηνης τυγχανοντες δια σου και κατορθωματων [γινομενων]{.greek-omitted} [γενομενων]{.greek-added} τω εθνει τουτω δια της σης προνοιας[24:2]{.aside}

παντη τε και πανταχου αποδεχομεθα κρατιστε φηλιξ μετα πασης ευχαριστιας[24:3]{.aside}

ινα δε μη επι πλειον σε [εγκοπτω]{.greek-omitted} [εκκοπτω]{.greek-added} παρακαλω ακουσαι [σε]{.greek-omitted} ημων συντομως τη ση επιεικεια[24:4]{.aside}

ευροντες γαρ τον ανδρα τουτον λοιμον και κινουντα στασιν πασιν τοις ιουδαιοις τοις κατα την οικουμενην [πρωτοστατην]{.greek-omitted} [προτοστατην]{.greek-added} τε της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον [επειρασεν]{.greek-omitted} [επειρασε]{.greek-added} βεβηλωσαι ον και εκρατησαμεν[24:6]{.aside}

παρ ου δυνηση αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

συνεπεθεντο δε και [οι]{.corr} ιουδαιοι φασκοντες ταυτα ουτως εχειν[24:9]{.aside}

απεκριθη δε ο παυλος νευσαντος [αυ]{.greek-added} [αυτω]{.corr} του [ηγεμονος]{.greek-omitted} [ηγεμωνος]{.greek-added} λεγειν εκ πολλων ετων οντα σε κριτην τω εθνει τουτω επισταμενος [ευθυμοτερον]{.greek-omitted} [ευθυμωτερον]{.greek-added} τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου γνωναι οτι ου πλειους [εισιν]{.greek-omitted} [εισι]{.greek-added} μοι ημεραι δεκαδυο αφ ης [ανεβην]{.greek-omitted} [ανεβη]{.greek-added} προσκυνησων εν [ιερουσαλημ]{.greek-abbr}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η επισυστασιν ποιουντα οχλου ουτε εν ταις συναγωγαις ουτε κατα την πολιν[24:12]{.aside}

ουτε παραστησαι [με]{.greek-omitted} δυνανται περι ων νυν κατηγορουσιν [μου]{.greek-omitted} [μοι]{.greek-added}[24:13]{.aside}

ομολογω δε τουτο σοι οτι κατα την οδον ην λεγουσιν αιρεσιν ουτως λατρευω τω πατρωω [θεω]{.greek-abbr} πιστευων πασιν τοις κατα τον νομον και τοις προφηταις γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι προσδεχονται αναστασιν μελλειν εσεσθαι νεκρων δικαιων τε και αδικων[24:15]{.aside}

εν τουτω [δε]{.greek-omitted} [και]{.greek-added} αυτος ασκω απροσκοπον συνειδησιν εχων προς [τε]{.greek-added} τον [θεον]{.greek-abbr} και τους [ανθρωπους]{.greek-abbr} δια παντος[24:16]{.aside}

δι ετων δε πλειονων παρεγενομην ελεημοσυνας ποιησων εις το εθνος μου και προσφορας[24:17]{.aside}

εν οις ευρον με ηγνισμενον εν τω ιερω ου μετα οχλου ουδε μετα θορυβου [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιοι]{.greek-added} ους δει επι σου παρειναι και κατηγορειν [ει]{.greek-omitted} [ετι]{.greek-added} [τι]{.greek-omitted} εχοιεν προς με[24:19]{.aside}

η αυτοι ουτοι ειπατωσαν τι ευρον εν εμοι αδικημα σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας ταυτης φωνης ης εκραξα εστως εν αυτοις οτι περι αναστασεως νεκρων εγω κρινομαι σημερον υφ υμων[24:21]{.aside}

ακουσας δε ταυτα ο φηλιξ ανεβαλετ[ο]{.greek-supplied} αυτους ακριβεστερον ειδως τα περι της οδου ειπων οταν λυσιας ο χιλιαρχος καταβη διαγνωσομαι τα καθ υμας[24:22]{.aside}

διαταξαμενος [τε]{.greek-omitted} [δε]{.greek-added} τω εκατονταρχη τηρεισθαι τον παυλον εχειν τε ανεσιν και μηδενα κωλυειν των ιδιω[ν]{.unclear} αυτου υπηρετειν η προσερχεσθαι αυτω[24:23]{.aside}

μετα δε ημερας τινας παραγενομενος ο φηλιξ συν [δρουσιλλη]{.greek-omitted} [δρυσιλλη]{.greek-added} τη γυναικι ουση ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου περι της εις [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του [μελλοντος]{.greek-omitted} [μελλον]{.greek-added} [τος]{.greek-added} εσεσθαι εμφοβος γενομενος ο φηλιξ απεκριθη το νυν [εχον]{.greek-omitted} [εχων]{.greek-added} πορευου καιρον δε μεταλαβων μετακαλεσομαι σε[24:25]{.aside}

αμα και ελπιζων οτι χρηματα δοθησεται αυτω υπο του παυλου οπως λυση αυτον [δ]{.unclear}ιο και πυκνοτερον αυτον μεταπεμπομενος [ωμιλει]{.greek-omitted} [ομιλει]{.greek-added} αυτω[24:26]{.aside}

[διετιας]{.greek-omitted} [διαιτιας]{.greek-added} δε πληρωθεισης [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} διαδοχον ο φηλιξ πορκιον φηστον [θελων]{.greek-omitted} [θελον]{.greek-added} τε [χαριτας]{.greek-omitted} [χαριν]{.greek-added} καταθεσθαι τοις ιουδαιοις ο φηλιξ [κατελιπεν]{.greek-omitted} [κατελειπεν]{.greek-added} τον παυλον δεδεμενον[24:27]{.aside}

### Chapter 25

φηστος ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη εις ιεροσολυμα απο καισαρειας[25:1]{.aside}

[ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} δε αυτω [ο]{.greek-omitted} [οι]{.greek-added} [αρχιερευς]{.greek-omitted} [αρχιερεις]{.greek-added} και οι πρωτοι των ιουδαιων κατα του παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται αυτον εις [ιερουσαλημ]{.greek-abbr} ενεδραν ποιουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν ουν φηστος απεκριθη τηρεισθαι τον παυλον εν καισαρεια εαυτον δε μελλειν εν ταχει εκπορευεσθαι[25:4]{.aside}

[οι]{.greek-omitted} [ει]{.greek-added} ουν δυνατοι εν υμιν φησιν συγκαταβαντες ει τι εστιν εν τω ανδρι τουτω [κατηγορειτωσαν]{.greek-omitted} [κατηγορητωσαν]{.greek-added} αυτου[25:5]{.aside}

διατριψας δε εν αυ[τ]{.unclear}οις ημερας πλειους η δεκα καταβας εις καισαρειαν τη επαυριον καθισας επι του βηματος εκελευσεν [αχθηναι]{.greek-added} τον παυλον [αχθηναι]{.greek-omitted}[25:6]{.aside}

παραγενομενου δε αυτου περιεστησαν [αυτον]{.greek-added} οι απο ιεροσολυμων καταβεβηκοτες ιουδαιοι πολλα και βαρεα αιτιωματα φεροντες [κατα]{.greek-omitted} [κατ]{.greek-added} [του]{.greek-omitted} [αυτου]{.greek-added} [παυλου]{.greek-omitted} α ουκ ισχυον αποδειξαι[25:7]{.aside}

[του]{.greek-added} [παυλου]{.greek-added} απολογουμενου αυτου οτι ουτε εις τον νομον των ιουδαιων ουτε εις το ιερον ουτε εις καισαρα τι ημαρτον[25:8]{.aside}

ο φηστος δε τοις ιουδαιοις θελων χαριν καταθεσθαι αποκριθεις τω παυλω ειπεν θελεις εις ιεροσολυμα αναβας εκει περι τουτων κρινεσθαι επ εμου[25:9]{.aside}

ειπεν δε ο παυλος επι του βηματος καισαρος εστως ειμι ου με δει κρινεσθαι ιουδαιους ουδεν ηδικησα ως και συ καλλιον επιγινωσκεις[25:10]{.aside}

ει μεν γαρ αδικω και αξιον θανατου πεπραχα τι ου παραιτουμαι το αποθανειν ει δε ουδεν εστιν ων ουτοι κατηγορουσιν [μου]{.greek-omitted} [μοι]{.greek-added} ουδεις με δυναται [αυτοις]{.greek-omitted} [τουτοις]{.greek-added} χαρισασθαι καισαρα επικαλουμαι[25:11]{.aside}

τοτε ο φηστος συλλαλησας μετα του [συμβουλιου]{.greek-omitted} [συμβουλου]{.greek-added} απεκριθη καισαρα επικεκλησαι επι καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τινων αγριππας ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν ασπασαμενοι τον φηστον[25:13]{.aside}

ως δε πλειους ημερας [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added} εκει ο φηστος τω βασιλει ανεθετο τα κατα τον παυλον λεγων ανηρ τις εστιν καταλελειμμενος υπο φηλικος δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις ιεροσολυμα ενεφανισαν οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} εις απωλειαν πριν η ο κατηγορουμενος κατα προσωπον εχοι τους κατηγορους τοπον τε απολογιας λαβοι περι του εγκληματος[25:16]{.aside}

συνελθοντων ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη εξης καθισας επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν [επεφερον]{.greek-omitted} [εφερον]{.greek-added} ων υπενοουν εγω[25:18]{.aside}

ζητηματα δε τινα περι της ιδιας δεισιδαιμονιας ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τεθνηκοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω [εις]{.greek-added} την περι [τουτου]{.greek-omitted} [τουτων]{.greek-added} ζητησιν ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-abbr} κακει [κρινεσθαι]{.greek-omitted} [κριθηναι]{.greek-added} περι τουτων[25:20]{.aside}

του δε παυλου επικαλεσαμενου τηρηθηναι αυτον εις την του σεβαστου [διαγνωσιν]{.greek-omitted} [διαγνω]{.greek-added} [σιν]{.greek-added} εκελευσα τηρεισθαι αυτον εως ου πεμψω αυτον προς καισαρα[25:21]{.aside}

αγριππας δε προς τον φηστον εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της βερνικης μετα πολλης φαντασιας και εισελθοντων εις το ακροατηριον συν τε τοις χιλιαρχοις και [ανδρασιν]{.greek-omitted} [ανδρασι]{.greek-added} τοις κατ εξοχην [ουσιν]{.greek-omitted} [ουσι]{.greek-added} της πολεως και κελευσαντος του φηστου ηχθη ο παυλος[25:23]{.aside}

και φησιν ο φηστος αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες θεωρειτε τουτον περι ου παν το πληθος των ιουδαιων ενετυχον μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν ζην αυτον μηκετι[25:24]{.aside}

εγω δε καταλαβομενος μηδεν αξιον θανατου αυτον πεπραχεναι και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα πεμπειν αυτον[25:25]{.aside}

περι ου ασφαλες τι γραψαι τω κυριω ουκ εχω διο προηγαγον αυτον εφ υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως γενομενης σχω τι γραψαι[25:26]{.aside}

αλογον γαρ μοι δοκει [πεμποντα]{.greek-omitted} [πεμποντι]{.greek-added} δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη [επιτρεπεται]{.greek-omitted} [επιτετρεπται]{.greek-added} σοι υπερ σεαυτου λεγειν τοτε ο παυλος απελογειτο εκτεινας την χειρα[26:1]{.aside}

περι παντων ων εγκαλουμαι υπο ιουδαιων βασιλευ αγριππα ηγημαι εμαυτον μακαριον επι σου μελλων απολογεισθαι σημερον[26:2]{.aside}

μαλιστα γνωστην οντα σε παντων των κατα ιουδαιους ηθων τε και ζητηματων διο δεομαι σου μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ νεοτητος την απ αρχης γενομενην εν τω εθνει μου εν ιεροσολυμοις [ισασιν]{.greek-omitted} [ισασι]{.greek-added} παντες οι ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν [θελωσιν]{.greek-omitted} [θελωσι]{.greek-added} μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας θρησκειας εζησα φαρισαιος[26:5]{.aside}

και νυν επ ελπιδι της προς τους [πατερας]{.greek-abbr} επαγγελιας γενομενης υπο [του]{.greek-omitted} [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν εκτενεια νυκτα και ημεραν λατρευον ελπιζει καταντησαι περι ης ελπιδος εγκαλουμαι βασιλευ αγριππα υπο ιουδαιων[26:7]{.aside}

τι απιστον κρινεται παρ υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησα εν ιεροσολυμοις και πολλους των [αγιων]{.greek-omitted} [αγι]{.greek-added} [ων]{.greek-added} εγω [εν]{.greek-added} φυλακαις κατεκλεισα την παρα των αρχιερεων εξουσιαν λαβων αναιρουμενων τε αυτων κατηνεγκα ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν περισσως τε εμμαινομενος αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις και πορευομενος εις την δαμασκον μετ εξουσιας και επιτροπης της παρα των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον ειδον βασιλευ ουρανοθεν υπερ την λαμπροτητα του ηλιου περιλαμψαν [με]{.greek-omitted} [μοι]{.greek-added} φως και τους συν εμο[ι]{.unclear} πορευομενους[26:13]{.aside}

παντων δε καταπεσοντων ημων εις την γην ηκουσα φωνην λαλουσαν προς με και λεγουσαν τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε ειπον τις ει [κυριε]{.greek-abbr} ο δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [ιησους]{.greek-abbr} [ο]{.unclear}[ν]{.greek-supplied} [σ]{.unclear}υ διωκ[ε]{.unclear}ις[26:15]{.aside}

αλλα αναστηθι και στηθι επι τους ποδας σου εις τουτο γαρ ωφθην σοι προχειρισασθαι σε υπηρετην και μαρτυρα ων τε ειδες ων τε [οφθησομαι]{.greek-omitted} [ωφθησομαι]{.greek-added} σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου και των εθνων εις ους εγω σε αποστελλω[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του [υποστρεψαι]{.greek-omitted} [επιστρεψαι]{.greek-added} απο σκοτους εις φως και [απο]{.greek-added} της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην [απειθης]{.greek-omitted} [απειθεις]{.greek-added} τη ουρανιω οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω [πρ]{.unclear}ωτον και ιεροσολυμοις εις πασαν [τε]{.greek-omitted} την χωραν της ιουδαιας και τοις εθνεσιν απαγγελλων μετανοειν και επιστρεφειν επι τον [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων [οι]{.greek-omitted} ιουδαιοι με συλλαβομενοι εν τω ιερω επειρωντο διαχειρισασθαι[26:21]{.aside}

επικουριας ουν τυχων της παρα του [θεου]{.greek-abbr} αχρι της ημερας ταυτης [εστηκα]{.greek-omitted} [εστικα]{.greek-added} μαρτυρομενος μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και μωυσης[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως μελλει καταγγελλειν τω λαω και τοις εθνεσιν[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο φηστος μεγαλη τη φωνη εφη μαινη παυλε τα πολλα σε γραμματα εις μανιαν περιτρεπει[26:24]{.aside}

ο δε ου μαινομαι φησιν κρατιστε φηστε αλλα αληθειας και σωφροσυνης ρηματα αποφθεγγομαι[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον και παρρησιαζομενος λαλω λανθανειν γαρ αυτον τι τουτων ου πειθομαι ουδεν ου γαρ εν γωνια πεπραγμενον τουτο[26:26]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

ο δε αγριππας προς τον παυλον εφη εν ολιγω με πειθεις χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος ειπεν [ευξαιμην]{.greek-omitted} [ευξαμην]{.greek-added} αν τω [θεω]{.greek-abbr} και εν ολιγω και εν πολλω ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος καγω ειμι παρεκτος των δεσμων τουτων[26:29]{.aside}

και ταυτα ειποντος αυτου ανεστη ο βασιλευς και ο ηγεμων η τε βερνικη και οι συγκαθημενοι αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν θανατου αξιον η δεσμων πρασσει ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω φηστω εφη απολελυσθ[α]{.greek-supplied}ι εδυνατο ο ανθρωπος ουτος ει μη [επεκεκλητο]{.greek-omitted} [επεκεκλειτο]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την ιταλιαν παρεδιδουν τον τε παυλον και τινας [δεσμωτας]{.greek-added} ετερους [δεσμωτας]{.greek-omitted} εκατονταρχη ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω [αδραμυττηνω]{.greek-omitted} [αδραμυττινω]{.greek-added} μελλοντες πλειν τους κατα την ασιαν τοπους [ανηχθημεν]{.greek-omitted} [ανηχθη]{.greek-added} [μεν]{.greek-added} οντος συν ημιν αρισταρχου μακεδονος θεσσαλονικεως[27:2]{.aside}

τη [τε]{.greek-omitted} [δε]{.greek-added} ετερα κατηχθημεν εις σιδωνα φιλανθρωπως τε ο ιουλιος τω παυλω χρησαμενος [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες [υ]{.greek-supplied}πεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες κατηλθομεν εις μυρα της λυκιας[27:5]{.aside}

κακει ευρων ο εκατονταρχος πλοιον αλεξανδρινον πλεον εις την ιταλιαν ενεβιβασεν ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις βραδυπλοουντες και μολις γενομενοι κατα την κνιδον μη προσεωντος ημας του ανεμου υπεπλευσαμεν την κρητην κατα σαλμωνην[27:7]{.aside}

μολις τε παραλεγομενοι αυτην ηλθομεν εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις λασαια[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος ηδη επισφαλους του πλοος δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των ψυχων [ημων]{.greek-omitted} [υμων]{.greek-added} [με]{.greek-added} [μελλειν]{.greek-omitted} [λλειν]{.greek-added} εσεσθαι τον πλουν[27:10]{.aside}

ο δε εκατονταρχης τω κυβερνητη και τω ναυκληρω επειθετο μαλλον η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι πλειους εθεντο βουλην αναχθηναι [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της κρητης [βλεποντα]{.greek-omitted} [βλεπον]{.greek-added} κατα λιβα και κατα χωρον[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες ασσον παρελεγοντο την κρητην[27:13]{.aside}

μετ ου πολυ δε [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} κατ αυτης ανεμος τυφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι υποδραμοντες καλουμενον κλαυδην μολις ισχυσαμεν περικρατεις γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες βοηθειαις εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη εις την συρτην [εκπεσωσιν]{.greek-omitted} [εκπεσωσι]{.greek-added} χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως δε χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη αυτοχειρες την σκευην του πλοιου ερριψαμεν[27:19]{.aside}

μητε δε ηλιου μητε αστρων [επιφαινοντων]{.greek-omitted} [επιφαινον]{.greek-added} [των]{.greek-added} επι πλειονας ημερας χειμωνος τε ουκ ολιγου επικειμενου λοιπον περιηρειτο πασα [η]{.greek-added} ελπις του σωζεσθαι ημας[27:20]{.aside}

πολλης δε [ασιτιας]{.greek-omitted} [ασιτειας]{.greek-added} υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης κερδησαι τε την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης ουδεμια εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι αγγελος του [θεου]{.greek-abbr} ου ειμι ω και λατρευω[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

[διο]{.greek-omitted} [δι]{.greek-added} ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα μεσον της νυκτος υπενοουν οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και βολισαντες ευρον οργυιας εικοσι βραχυ δε διαστησαντες και παλιν βολισαντες ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι τε [μη]{.greek-added} [μηπως]{.greek-omitted} [πως]{.greek-added} εις τραχεις τοπους [ε]{.greek-added} [εκπεσωμεν]{.greek-omitted} [κπεσωμεν]{.greek-added} εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ πρωρας μελλοντων αγκυρας εκτεινειν[27:30]{.aside}

ειπεν ο παυλος τω εκατονταρχη και τοις στρατιωταις εαν μη ουτοι μεινωσιν εν τω πλοιω υμεις σωθηναι ου δυνασθε[27:31]{.aside}

τοτε οι στρατιωται απεκοψαν τα σχοινια της σκαφης και [ειασαν]{.greek-omitted} [ιασαν]{.greek-added} αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου ημελλεν ημερα γινεσθαι παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην σημερον ημεραν προσδοκωντες ασιτοι διατελειτε μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας προσλαβειν τροφης τουτο γαρ προς της [υμετερας]{.greek-omitted} [ημετερας]{.greek-added} [σωτηριας]{.greek-abbr} υπαρχει ουδενος γαρ υμων [θριξ]{.greek-omitted} [θρηξ]{.greek-added} εκ της κεφαλης πεσειται[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον [ευχαριστησεν]{.greek-omitted} [ευχαριστησε]{.greek-added} τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

ημεν δε εν τω πλοιω αι πασαι ψυχαι διακοσιαι εβδομηκοντα εξ[27:37]{.aside}

κορεσθεντες δε της τροφης εκουφιζον το πλοιον [εκβαλλομενοι]{.greek-omitted} [εκβαλομενοι]{.greek-added} τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον εβουλευσαντο ει δυνατον εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των πηδαλιων και επαραντες τον αρτεμονα τη πνεουση κατειχον εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον επωκειλαν την ναυν και η μεν πρωρα ερεισασα εμεινεν ασαλευτος [η]{.greek-omitted} [ει]{.greek-added} δε πρυμνα [ελυετο]{.greek-omitted} [διελυετο]{.greek-added} υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} μη τις εκκολυμβησας [διαφυγη]{.greek-omitted} [διαφυγει]{.greek-added}[27:42]{.aside}

ο δε εκατονταρχος βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του βουληματος εκελευσεν τε τους δυναμενους κολυμβαν απορριψαντας πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους μεν επι σανισιν ους δε επι τινων των απο του πλοιου και ουτως εγενετο παντας διασωθηναι επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες [οι]{.greek-added} [περι]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} [πλοος]{.greek-added} τοτε επεγνωσαν οτι μελιτη η νησος καλειται[28:1]{.aside}

οι δε βαρβαροι παρειχον ου την τυχουσαν φιλανθρωπιαν ημιν αναψαντες γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον [εφεστωτα]{.greek-omitted} [υφεστωτα]{.greek-added} και δια το ψυχος[28:2]{.aside}

συστρεψαντος δε του παυλου φρυγανων πληθος και επιθεντος επι την πυραν εχιδνα [εκ]{.greek-omitted} [απο]{.greek-added} της θερμης διεξελθουσα [καθηψεν]{.greek-omitted} [καθηψε]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε ειδον οι βαρβαροι [κρεμαμενον]{.greek-omitted} [κρεμμαμενον]{.greek-added} το θηριον εκ της χειρος αυτου ελεγον προς αλληλους παντως φονευς εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν [αποτιναξας]{.greek-omitted} [αποτειναξαμενος]{.greek-added} το θηριον εις το πυρ επαθεν ουδεν κακον[28:5]{.aside}

οι δε [προσεδοκων]{.greek-omitted} [προσεδοκουν]{.greek-added} αυτον μελλειν πιμπρασθαι η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων [προσδοκωντων]{.greek-omitted} [προσδοκοντων]{.greek-added} και θεωρουντων μηδεν ατοπον εις αυτον [γ[ε]{.unclear}νομενον]{.greek-added} [γινομενον]{.corr} μεταβαλλομενοι ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6]{.aside}

εν δε τοις περι τον τοπον εκεινον [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} χωρια τω πρωτω της νησου ονοματι ποπλιω ος αναδεξαμενος ημας τρεις ημερας φιλοφρονως εξενισεν[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του ποπλιου πυρετοις και [δυσεντερια]{.greek-omitted} [δυσεντεριω]{.greek-added} συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις τας χειρας αυτω ιασατο αυτον[28:8]{.aside}

τουτου ουν [γενομενου]{.greek-omitted} [γινομενου]{.greek-added} και οι λοιποι οι εχοντες ασθενειας εν τη νησω προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρειαν[28:10]{.aside}

μετα δε τρεις [[η]{.unclear}[μερ]{.greek-supplied}ας]{.greek-added} [μηνας]{.corr} [ηχθημεν]{.greek-omitted} [ανηχθημεν]{.greek-added} εν πλοιω παρακεχειμακοτι εν τη νησω αλεξανδρινω παρασημω διοσκουροις[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες κατηντησαμεν εις [ρηγιον]{.greek-omitted} [ρηγειον]{.greek-added} και μετα μιαν ημεραν επιγενομενου νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις επιμειναι ημερας επτα και ουτως εις την ρωμην [ηλθομεν]{.greek-omitted} [εισηλθομεν]{.greek-added}[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντ[ε]{.greek-supplied}ς τα περι ημων εξηλθον εις απαντησιν ημιν [αχρι]{.greek-omitted} [αχρις]{.greek-added} αππιου φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} θαρσος[28:15]{.aside}

οτε δε ηλθομεν εις [την]{.greek-added} ρωμην ο εκατονταρχος [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τους δεσμιους τω [στρατοπεδαρχη]{.greek-omitted} [στρατοπαιδαρχω]{.greek-added} τω δε παυλω [επετραπη]{.greek-omitted} [επετραπει]{.greek-added} μενειν καθ εαυτον συν τω φυλασσοντι [αυτον]{.greek-omitted} [αυτω]{.greek-added} [στρατιωτη]{.greek-omitted} [στρατιωτι]{.greek-added}[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι τον παυλον τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} προς αυτους ανδρες αδελφοι εγω ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} τοις πατρωοις δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με [εβουλοντο]{.greek-omitted} [ηβουλοντο]{.greek-added} απολυσαι δια το μηδεμιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου εχων τι κατηγορησαι[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι ενεκεν γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε γραμματα περι σου εδεξαμεθα απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν η ελαλησεν τι περι σου πονηρον[28:21]{.aside}

[ακουσαι]{.greek-added} [αξιουμεν]{.greek-omitted} [δε]{.greek-omitted} παρα σου [ακουσαι]{.greek-omitted} α φρονεις περι μεν [γαρ]{.greek-omitted} της αιρεσεως ταυτης γνωστον εστιν ημιν οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι δε αυτω ημεραν ηκον προς αυτον εις την ξενιαν πλειονες οις εξετιθετο διαμαρτυρομενος [αυτοις]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους τα περι του [ιησου]{.greek-abbr} απο τε του νομου μωυσεως και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} ημων[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και ειπον ακοη ακουσετε και ου μη [συνητε]{.greek-omitted} [συνειτε]{.greek-added} και βλεποντες βλεψετε και ου μη ιδητε[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις ωσιν βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν ακουσωσιν και τη καρδια συνωσιν και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και ιασομαι αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και ταυτα αυτου ειποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις συζητησιν[28:29]{.aside}

[εμεινεν]{.greek-omitted} [εμεινε]{.greek-added} δε ο παυλος διετιαν ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους προς αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα πασης παρρησιας [ακωλυτως]{.greek-omitted} [ακολυτως]{.greek-added}[28:31]{.aside}

## First John

### Chapter 1

ο ην απ αρχης ο ακηκοαμεν ο εωρακαμεν τοις οφθαλμοις ημων ο εθεασαμεθα και αι χειρες ημων εψηλαφησαν περι του λογου της ζωης[1:1]{.aside}

και η ζωη εφανερωθη και εωρακαμεν και μαρτυρουμεν και απαγγελλομεν υμιν την ζωην την αιωνιον ητις ην προς τον [πατερα]{.greek-abbr} και εφανερωθη ημιν[1:2]{.aside}

ο εωρακαμεν και ακηκοαμεν απαγγελλομεν υμιν ινα και υμεις κοινωνιαν εχητε μεθ ημων και η κοινωνια δε η ημετερα μετα του [πατρος]{.greek-abbr} και μετα του [υιου]{.greek-abbr} αυτου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:3]{.aside}

και ταυτα γραφομεν υμιν ινα η χαρα ημων η πεπληρωμενη[1:4]{.aside}

και εστιν αυτη η αγγελια ην ακηκοαμεν απ αυτου και αναγγελλομεν υμιν οτι ο [θεος]{.greek-abbr} φως εστιν και σκοτια εν αυτω ουκ εστιν ουδεμια[1:5]{.aside}

εαν ειπωμεν οτι κοινωνιαν εχομεν μετ αυτου και εν τω σκοτει περιπατωμεν ψευδομεθα και ου ποιουμεν την αληθειαν[1:6]{.aside}

εαν δε εν τω φωτι περιπατωμεν ως αυτος [εστιν]{.greek-omitted} εν τω φωτι κοινωνιαν εχομεν μετ αλληλων και το αιμα [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του [υιου]{.greek-abbr} αυτου καθαριζει ημας απο πασης αμαρτιας[1:7]{.aside}

εαν ειπωμεν οτι αμαρτιαν ουκ εχομεν εαυτους πλανωμεν και η αληθεια ουκ εστιν εν ημιν[1:8]{.aside}

εαν ομολογωμεν τας αμαρτιας ημων πιστος εστιν και δικαιος ινα αφη ημιν τας αμαρτιας και καθαριση ημας απο πασης αδικιας[1:9]{.aside}

εαν ειπωμεν οτι ουχ ημαρτηκαμεν ψευστην ποιουμεν αυτον και ο λογος αυτου ουκ εστιν εν ημιν[1:10]{.aside}

### Chapter 2

τεκνια μου ταυτα γραφω υμιν ινα μη αμαρτητε και εαν τις αμαρτη παρακλητον εχομεν προς τον [πατερα]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} δικαιον[2:1]{.aside}

και αυτος ιλασμος εστιν περι των αμαρτιων ημων ου περι των ημετερων δε μονον αλλα και περι ολου του κοσμου[2:2]{.aside}

και εν τουτω γινωσκομεν οτι εγνωκαμεν αυτον εαν τας εντολας αυτου τηρωμεν[2:3]{.aside}

ο λεγων εγνωκα αυτον και τας εντολας αυτου μη τηρων ψευστης εστιν και εν τουτω η αληθεια ουκ εστιν[2:4]{.aside}

ος δ αν τηρη αυτου τον λογον αληθως εν τουτω η αγαπη του [θεου]{.greek-abbr} τετελειωται εν τουτω γινωσκομεν οτι εν αυτω εσμεν[2:5]{.aside}

ο λεγων εν αυτω μενειν οφειλει καθως εκεινος περιεπατησεν [και]{.greek-omitted} [αυτος]{.greek-omitted} [ουτως]{.greek-omitted} [περιπατειν]{.greek-omitted}[2:6]{.aside}

αδελφοι ουκ εντολην καινην γραφω υμιν αλλ εντολην παλαιαν ην ειχετε απ αρχης η εντολη η παλαια εστιν ο λογος ον ηκουσατε απ αρχης[2:7]{.aside}

παλιν εντολην καινην γραφω υμιν ο εστιν αληθες εν αυτω και εν υμιν οτι η σκοτια παραγεται και το φως το αληθινον ηδη φαινει[2:8]{.aside}

ο λεγων εν τω φωτι ειναι και τον αδελφον αυτου μισων εν τη σκοτια εστιν εως αρτι[2:9]{.aside}

ο αγαπων τον αδελφον αυτου εν τω φωτι [μενει]{.greek-omitted} [μένει]{.greek-added} και σκανδαλον εν αυτω ουκ εστιν[2:10]{.aside}

ο δε μισων τον αδελφον αυτου εν τη σκοτια εστιν και εν τη σκοτια περιπατει και ουκ οιδεν που υπαγει οτι η σκοτια ετυφλωσεν τους οφθαλμους αυτου[2:11]{.aside}

γραφω υμιν τεκνια οτι αφεωνται [υμιν]{.greek-omitted} [υμων]{.greek-added} αι αμαρτιαι δια το ονομα αυτου[2:12]{.aside}

γραφω υμιν [πατερες]{.greek-abbr} οτι εγνωκατε τον απ αρχης γραφω υμιν νεανισκοι οτι νενικηκατε τον πονηρον [γραφω]{.greek-omitted} [υμιν]{.greek-omitted} [παιδια]{.greek-omitted} [οτι]{.greek-omitted} [εγνωκατε]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted}[2:13]{.aside}

[εγραψα]{.greek-added} [υμιν]{.greek-added} [παιδια]{.greek-added} [οτι]{.greek-added} [εγνωκατε]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} εγραψα υμιν [πατερες]{.greek-abbr} οτι εγνωκατε τον απ αρχης εγραψα υμιν νεανισκοι οτι ισχυροι εστε και ο λογος του [θεου]{.greek-abbr} εν υμιν [μενει]{.greek-omitted} [μένει]{.greek-added} και νενικηκατε τον πονηρον[2:14]{.aside}

μη αγαπατε τον κοσμον μηδε τα εν τω κοσμω εαν τις αγαπα τον κοσμον ουκ εστιν η αγαπη του [πατρος]{.greek-abbr} εν αυτω[2:15]{.aside}

οτι παν το εν τω κοσμω η επιθυμια της σαρκος και η επιθυμια των οφθαλμων και η [αλαζονεια]{.greek-omitted} [αλαζονια]{.greek-added} του βιου ουκ εστιν εκ του [πατρος]{.greek-abbr} αλλ εκ του κοσμου εστιν[2:16]{.aside}

και ο κοσμος παραγεται και η επιθυμια αυτου ο δε ποιων το θελημα του [θεου]{.greek-abbr} [μενει]{.greek-omitted} [μένει]{.greek-added} εις τον αιωνα[2:17]{.aside}

παιδια εσχατη ωρα εστιν και καθως ηκουσατε [οτι]{.greek-omitted} ο αντιχριστος ερχεται και νυν αντιχριστοι πολλοι γεγονασιν οθεν γινωσκομεν οτι εσχατη ωρα εστιν[2:18]{.aside}

εξ ημων εξηλθον αλλ ουκ ησαν εξ ημων ει γαρ ησαν εξ ημων μεμενηκεισαν αν μεθ ημων αλλ ινα φανερωθωσιν οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} παντες εξ ημων[2:19]{.aside}

και υμεις χρισμα εχετε απο του αγιου και οιδατε παντα[2:20]{.aside}

ουκ εγραψα υμιν οτι ουκ οιδατε την αληθειαν αλλ οτι οιδατε αυτην και οτι παν ψευδος εκ της αληθειας ουκ εστιν[2:21]{.aside}

τις εστιν ο ψευστης ει μη ο αρνουμενος οτι [ιησους]{.greek-abbr} ουκ εστιν ο [χριστος]{.greek-abbr} ουτος εστιν ο αντιχριστος ο αρνουμενος τον [πατερα]{.greek-abbr} και τον [υιον]{.greek-abbr}[2:22]{.aside}

πας ο αρνουμενος τον [υιον]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} εχει[2:23]{.aside}

υμεις ουν ο ηκουσατε απ αρχης εν υμιν μενετω εαν εν υμιν μεινη ο απ αρχης ηκουσατε και υμεις εν τω [υιω]{.greek-abbr} και εν τω [πατρι]{.greek-abbr} μενειτε[2:24]{.aside}

και αυτη εστιν η επαγγελια ην αυτος επηγγειλατο ημιν την ζωην την αιωνιον[2:25]{.aside}

ταυτα εγραψα υμιν περι των πλανωντων υμας[2:26]{.aside}

και υμεις το χρισμα ο ελαβετε απ αυτου εν υμιν [μενει]{.greek-omitted} [μένει]{.greek-added} και ου χρειαν εχετε ινα [τις]{.greek-omitted} [τίς]{.greek-added} [διδασκη]{.greek-omitted} [διδασκει]{.greek-added} υμας αλλ ως το αυτο χρισμα διδασκει υμας περι παντων και αληθες εστιν και ουκ εστιν ψευδος και καθως εδιδαξεν υμας μενειτε εν αυτω[2:27]{.aside}

και νυν τεκνια μενετε εν αυτω ινα οταν φανερωθη εχωμεν παρρησιαν και μη αισχυνθωμεν απ αυτου εν τη παρουσια αυτου[2:28]{.aside}

εαν [ειδητε]{.greek-omitted} [ἴδητε]{.greek-added} οτι δικαιος [εστιν]{.greek-omitted} [εστι]{.greek-added} γινωσκετε οτι πας ο ποιων την δικαιοσυνην εξ αυτου γεγεννηται[2:29]{.aside}

### Chapter 3

ιδετε ποταπην αγαπην [δεδωκεν]{.greek-omitted} [εδωκεν]{.greek-added} ημιν ο [πατηρ]{.greek-abbr} ινα τεκνα [θεου]{.greek-abbr} κληθωμεν δια τουτο ο κοσμος ου γινωσκει υμας οτι ουκ εγνω αυτον[3:1]{.aside}

αγαπητοι νυν τεκνα [θεου]{.greek-abbr} εσμεν και ουπω εφανερωθη τι εσομεθα οιδαμεν δε οτι εαν φανερωθη ομοιοι αυτω εσομεθα οτι οψομεθα αυτον καθως εστιν[3:2]{.aside}

και πας ο εχων την ελπιδα ταυτην επ αυτω αγνιζει εαυτον καθως εκεινος αγνος εστιν[3:3]{.aside}

πας ο ποιων την αμαρτιαν και την ανομιαν ποιει και η αμαρτια εστιν η ανομια[3:4]{.aside}

και οιδατε οτι εκεινος εφανερωθη ινα τας αμαρτιας ημων αρη και αμαρτια εν αυτω ουκ εστιν[3:5]{.aside}

πας ο εν αυτω μενων ουχ αμαρτανει πας ο αμαρτανων ουχ εωρακεν αυτον ουδε εγνωκεν αυτον[3:6]{.aside}

τεκνια μηδεις πλανατω υμας ο ποιων την δικαιοσυνην δικαιος εστιν καθως εκεινος δικαιος εστιν[3:7]{.aside}

ο ποιων την αμαρτιαν εκ του διαβολου εστιν οτι απ αρχης ο διαβολος αμαρτανει εις τουτο εφανερωθη ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ινα λυση τα εργα του διαβολου[3:8]{.aside}

πας ο γεγεννημενος εκ του [θεου]{.greek-abbr} αμαρτιαν ου ποιει οτι σπερμα αυτου εν αυτω [μενει]{.greek-omitted} [μένει]{.greek-added} και ου δυναται αμαρτανειν οτι εκ του [θεου]{.greek-abbr} γεγεννηται[3:9]{.aside}

εν [τουτω]{.greek-omitted} [τουτο]{.greek-added} φανερα εστιν τα τεκνα του [θεου]{.greek-abbr} και τα τεκνα του διαβολου πας ο μη ποιων δικαιοσυνην ουκ εστιν εκ του [θεου]{.greek-abbr} και ο μη αγαπων τον αδελφον αυτου[3:10]{.aside}

οτι αυτη εστιν η αγγελια ην ηκουσατε απ αρχης ινα αγαπωμεν αλληλους[3:11]{.aside}

ου καθως καιν εκ του πονηρου ην και [εσφαξεν]{.greek-omitted} [εσφαξε]{.greek-added} τον αδελφον αυτου και χαριν τινος εσφαξεν αυτον οτι τα εργα αυτου πονηρα ην τα δε του αδελφου αυτου δικαια[3:12]{.aside}

μη θαυμαζετε αδελφοι μου ει μισει υμας ο κοσμος[3:13]{.aside}

ημεις οιδαμεν οτι μεταβεβηκαμεν εκ του θανατου εις την ζωην οτι αγαπωμεν τους αδελφους ο μη αγαπων τον αδελφον [μενει]{.greek-omitted} [μένει]{.greek-added} εν τω θανατω[3:14]{.aside}

πας ο μισων τον αδελφον αυτου ανθρωποκτονος εστιν και οιδατε οτι πας ανθρωποκτονος ουκ εχει ζωην αιωνιον εν εαυτω μενουσαν[3:15]{.aside}

εν τουτω εγνωκαμεν την αγαπην οτι εκεινος υπερ ημων την ψυχην αυτου εθηκεν και ημεις οφειλομεν υπερ των αδελφων τας ψυχας τιθεναι[3:16]{.aside}

ος δ αν [εχη]{.greek-omitted} [εχει]{.greek-added} τον βιον του κοσμου και [θεωρη]{.greek-omitted} [θεωρει]{.greek-added} τον αδελφον αυτου χρειαν εχοντα και [κλειση]{.greek-omitted} [κλησει]{.greek-added} τα σπλαγχνα αυτου απ αυτου πως η αγαπη του [θεου]{.greek-abbr} [μενει]{.greek-omitted} [μενεῖ]{.greek-added} εν αυτω[3:17]{.aside}

τεκνια μου μη αγαπωμεν λογω μηδε τη [γλωσση]{.greek-omitted} [γλωσσει]{.greek-added} αλλ εν εργω και αληθεια[3:18]{.aside}

και εν τουτω γινωσκομεν οτι εκ της αληθειας εσμεν και εμπροσθεν αυτου πεισομεν τας καρδιας ημων[3:19]{.aside}

οτι εαν [καταγινωσκη]{.greek-omitted} [καταγινωσκει]{.greek-added} ημων η καρδια οτι μειζων εστιν ο [θεος]{.greek-abbr} της καρδιας ημων και γινωσκει παντα[3:20]{.aside}

αγαπητοι εαν η καρδια ημων μη [καταγινωσκη]{.greek-omitted} [καταγινωσκει]{.greek-added} ημων παρρησιαν εχομεν προς τον [θεον]{.greek-abbr}[3:21]{.aside}

και ο εαν αιτωμεν λαμβανομεν παρ αυτου οτι τας εντολας αυτου τηρουμεν και τα αρεστα ενωπιον αυτου ποιουμεν[3:22]{.aside}

και αυτη εστιν η εντολη αυτου ινα πιστευσωμεν τω ονοματι του [υιου]{.greek-abbr} αυτου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} και αγαπωμεν αλληλους καθως εδωκεν εντολην[3:23]{.aside}

και ο τηρων τας εντολας αυτου εν αυτω [μενει]{.greek-omitted} [μένει]{.greek-added} και αυτος εν αυτω και εν τουτω γινωσκομεν οτι [μενει]{.greek-omitted} [μένει]{.greek-added} εν ημιν εκ του [πνευματος]{.greek-abbr} ου ημιν εδωκεν[3:24]{.aside}

### Chapter 4

αγαπητοι μη παντι πνευματι πιστευετε αλλα δοκιμαζετε τα πνευματα ει εκ του [θεου]{.greek-abbr} εστιν οτι πολλοι ψευδοπροφηται [εξε]{.greek-added} [εξεληλυθασιν]{.greek-omitted} [ληλυθασιν]{.greek-added} εις τον κοσμον[4:1]{.aside}

εν τουτω [γινωσκεται]{.greek-omitted} [γινωσκετε]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} παν [πνευμα]{.greek-abbr} ο ομολογει [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εν σαρκι εληλυθοτα εκ του [θεου]{.greek-abbr} εστιν[4:2]{.aside}

και παν [πνευμα]{.greek-abbr} ο μη ομολογει [τον]{.greek-added} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εν σαρκι εληλυθοτα [εκ]{.greek-omitted} του [θεου]{.greek-abbr} ουκ εστιν και τουτο εστιν το του αντιχριστου ο ακηκοατε οτι ερχεται και νυν εν τω κοσμω εστιν ηδη[4:3]{.aside}

υμεις εκ του [θεου]{.greek-abbr} εστε τεκνια και νενικηκατε αυτους οτι μειζων εστιν ο εν υμιν η ο εν τω κοσμω[4:4]{.aside}

αυτοι εκ του κοσμου εισιν δια τουτο εκ του κοσμου λαλουσιν και ο κοσμος αυτων ακουει[4:5]{.aside}

ημεις εκ του [θεου]{.greek-abbr} εσμεν ο γινωσκων τον [θεον]{.greek-abbr} [ακουει]{.greek-omitted} [ημων]{.greek-omitted} [ος]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ουκ]{.greek-omitted} ακουει ημων εκ τουτου γινωσκομεν το [πνευμα]{.greek-abbr} της αληθειας και το [πνευμα]{.greek-abbr} της πλανης[4:6]{.aside}

αγαπητοι αγαπωμεν αλληλους οτι η αγαπη εκ του [θεου]{.greek-abbr} εστιν και πας ο αγαπων εκ του [θεου]{.greek-abbr} γεγεννηται και γινωσκει τον [θεον]{.greek-abbr}[4:7]{.aside}

ο μη αγαπων ουκ εγνω τον [θεον]{.greek-abbr} οτι ο [θεος]{.greek-abbr} αγαπη εστιν[4:8]{.aside}

εν τουτω εφανερωθη η αγαπη του [θεου]{.greek-abbr} εν ημιν οτι τον [υιον]{.greek-abbr} αυτου τον μονογενη απεσταλκεν ο [θεος]{.greek-abbr} εις τον κοσμον ινα ζησωμεν δι αυτου[4:9]{.aside}

εν τουτω εστιν η αγαπη ουχ οτι ημεις ηγαπησαμεν τον [θεον]{.greek-abbr} αλλ οτι αυτος ηγαπησεν ημας και απεστειλεν [[απεστειλε]{.corr}]{.greek-added} τον [υιον]{.greek-abbr} αυτου ιλασμον περι των αμαρτιων ημων[4:10]{.aside}

αγαπητοι ει ουτως ο [θεος]{.greek-abbr} ηγαπησεν ημας και ημεις οφειλομεν αλληλους αγαπαν[4:11]{.aside}

[θεον]{.greek-abbr} ουδεις [πωποτε]{.greek-omitted} [πωπωτε]{.greek-added} τεθεαται εαν αγαπωμεν αλληλους ο [θεος]{.greek-abbr} εν ημιν [μενει]{.greek-omitted} [μένει]{.greek-added} και η αγαπη αυτου τετελειωμενη εστιν εν ημιν[4:12]{.aside}

εν τουτω γινωσκομεν οτι εν αυτω μενομεν και αυτος εν ημιν οτι εκ του [πνευματος]{.greek-abbr} αυτου δεδωκεν ημιν[4:13]{.aside}

και ημεις τεθεαμεθα και μαρτυρουμεν οτι ο [πατηρ]{.greek-abbr} [απεσταλκεν]{.greek-omitted} [απεσταλκε]{.greek-added} τον [υιον]{.greek-abbr} [σωτηρα]{.greek-abbr} του κοσμου[4:14]{.aside}

ος αν ομολογηση οτι [ιησους]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο [θεος]{.greek-abbr} εν αυτω [μενει]{.greek-omitted} [μένει]{.greek-added} και αυτος εν τω [θεω]{.greek-abbr}[4:15]{.aside}

και ημεις εγνωκαμεν και πεπιστευκαμεν την αγαπην ην εχει ο [θεος]{.greek-abbr} εν ημιν ο [θεος]{.greek-abbr} αγαπη εστιν και ο μενων εν τη αγαπη εν τω [θεω]{.greek-abbr} [μενει]{.greek-omitted} [μένει]{.greek-added} και ο [θεος]{.greek-abbr} εν αυτω [μενει]{.greek-omitted} [μένει]{.greek-added}[4:16]{.aside}

εν τουτω τετελειωται η αγαπη μεθ ημων ινα παρρησιαν εχωμεν εν τη ημερα της κρισεως οτι καθως εκεινος εστιν και ημεις εσμεν εν τω κοσμω τουτω[4:17]{.aside}

φοβος ουκ εστιν εν τη αγαπη αλλ η τελεια αγαπη εξω βαλλει τον φοβον οτι ο φοβος κολασιν εχει ο δε φοβουμενος ου τετελειωται εν τη αγαπη[4:18]{.aside}

ημεις αγαπωμεν αυτον οτι αυτος πρωτος ηγαπησεν ημας[4:19]{.aside}

εαν τις ειπη οτι [αγαπω]{.greek-omitted} [αγα]{.greek-added} [πω]{.greek-added} τον [θεον]{.greek-abbr} και τον αδελφον αυτου μιση ψευστης εστιν ο γαρ μη αγαπων τον αδελφον αυτου ον [εωρακεν]{.greek-omitted} [εωρακε]{.greek-added} τον [θεον]{.greek-abbr} ον ουχ [εωρακεν]{.greek-omitted} [εωρακε]{.greek-added} πως δυναται αγαπαν[4:20]{.aside}

και ταυτην την εντολην εχομεν απ αυτου ινα ο αγαπων τον [θεον]{.greek-abbr} αγαπα και τον αδελφον αυτου[4:21]{.aside}

### Chapter 5

πας ο πιστευων οτι [ιησους]{.greek-abbr} εστιν ο [χριστος]{.greek-abbr} εκ του [θεου]{.greek-abbr} γεγεννηται και πας ο αγαπων τον γεννησαντα αγαπα και τον γεγεννημενον εξ αυτου[5:1]{.aside}

εν τουτω γινωσκομεν οτι αγαπωμεν τα τεκνα του [θεου]{.greek-abbr} οταν τον [θεον]{.greek-abbr} αγαπωμεν και τας εντολας αυτου τηρωμεν[5:2]{.aside}

αυτη γαρ εστιν η αγαπη του [θεου]{.greek-abbr} ινα τας εντολας αυτου τηρωμεν και αι εντολαι αυτου βαρειαι ουκ εισιν[5:3]{.aside}

οτι παν το γεγεννημενον εκ του [θεου]{.greek-abbr} νικα τον κοσμον και αυτη εστιν η νικη η νικησασα τον κοσμον η πιστις [ημων]{.greek-omitted} [υμων]{.greek-added}[5:4]{.aside}

τις εστιν ο νικων τον κοσμον ει μη ο πιστευων οτι [ιησους]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[5:5]{.aside}

ουτος εστιν ο ελθων δι υδατος και αιματος [ιησους]{.greek-abbr} [χριστος]{.greek-abbr} ουκ εν τω υδατι μονον αλλ εν τω υδατι και [εν]{.greek-added} τω αιματι και το [πνευμα]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} το μαρτυρουν οτι το [πνευμα]{.greek-abbr} εστιν η αληθεια[5:6]{.aside}

οτι τρεις εισιν οι μαρτυρουντες[5:7]{.aside}

το [πνευμα]{.greek-abbr} και το υδωρ και το αιμα και οι τρεις εις το εν εισιν[5:8]{.aside}

ει την μαρτυριαν των [ανθρωπων]{.greek-abbr} [λαμβανομεν]{.greek-omitted} [λαμβα]{.greek-added} [νομεν]{.greek-added} η μαρτυρια του [θεου]{.greek-abbr} μειζων εστιν οτι αυτη εστιν η μαρτυρια του [θεου]{.greek-abbr} ην [μεμαρτυρηκεν]{.greek-omitted} [μεμαρτυρικεν]{.greek-added} περι του [υιου]{.greek-abbr} αυτου[5:9]{.aside}

ο πιστευων εις τον [υιον]{.greek-abbr} του [θεου]{.greek-abbr} εχει την μαρτυριαν εν αυτω ο μη πιστευων τω [θεω]{.greek-abbr} ψευστην πεποιηκεν αυτον οτι ου πεπιστευκεν εις την μαρτυριαν ην μεμαρτυρηκεν ο [θεος]{.greek-abbr} περι του [υιου]{.greek-abbr} αυτου[5:10]{.aside}

και αυτη εστιν η μαρτυρια οτι ζωην αιωνιον εδωκεν ημιν ο [θεος]{.greek-abbr} και αυτη η ζωη εν τω [υιω]{.greek-abbr} αυτου εστιν[5:11]{.aside}

ο εχων τον [υιον]{.greek-abbr} εχει την ζωην ο μη εχων τον [υιον]{.greek-abbr} του [θεου]{.greek-abbr} την ζωην ουκ εχει[5:12]{.aside}

ταυτα εγραψα υμιν τοις πιστευουσιν εις το ονομα του [υιου]{.greek-abbr} του [θεου]{.greek-abbr} ινα [ειδητε]{.greek-omitted} [ειδῆτε]{.greek-added} οτι ζωην αιωνιον [εχετε]{.greek-omitted} [εχητε]{.greek-added} και ινα πιστευητε εις το ονομα του [υιου]{.greek-abbr} του [θεου]{.greek-abbr}[5:13]{.aside}

και αυτη εστιν η παρρησια ην εχομεν προς αυτον οτι εαν τι αιτωμεθα κατα το θελημα αυτου ακουει ημων[5:14]{.aside}

και εαν οιδαμεν οτι ακουει ημων ο εαν αιτωμεθα οιδαμεν οτι εχομεν τα αιτηματα α ητηκαμεν παρ αυτου[5:15]{.aside}

εαν τις [ιδη]{.greek-omitted} [ἴδη]{.greek-added} τον αδελφον αυτου αμαρτανοντα αμαρτιαν μη προς θανατον αιτησει και δωσει αυτω ζωην τοις [αμαρτανουσιν]{.greek-omitted} [αμαρτανουσι]{.greek-added} μη προς θανατον εστιν αμαρτια προς θανατον ου περι εκεινης λεγω ινα ερωτηση[5:16]{.aside}

πασα αδικια αμαρτια εστιν και εστιν αμαρτια ου προς θανατον[5:17]{.aside}

οιδαμεν οτι πας ο γεγεννημενος εκ του [θεου]{.greek-abbr} ουχ αμαρτανει αλλ ο γεννηθεις εκ του [θεου]{.greek-abbr} τηρει εαυτον και ο πονηρος ουχ απτεται αυτου[5:18]{.aside}

οιδαμεν οτι εκ του [θεου]{.greek-abbr} εσμεν και ο κοσμος ολος εν τω πονηρω κειται[5:19]{.aside}

οιδαμεν [δε]{.greek-omitted} οτι ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} [ηκει]{.greek-omitted} [ηκη]{.greek-added} και δεδωκεν ημιν διανοιαν ινα [γινωσκωμεν]{.greek-omitted} [γινωσκομεν]{.greek-added} τον αληθινον και εσμεν εν τω αληθινω εν τω [υιω]{.greek-abbr} αυτου [ιησου]{.greek-abbr} [χριστω]{.greek-abbr} ουτος εστιν ο αληθινος [θεος]{.greek-abbr} και [η]{.greek-added} ζωη [η]{.greek-added} αιωνιος[5:20]{.aside}

τεκνια φυλαξατε εαυτα απο των ειδωλων αμην[5:21]{.aside}

## Second John

### Chapter 1

ο πρεσβυτερος εκλεκτη κυρια και τοις τεκνοις αυτης ους εγω αγαπω εν αληθεια και ουκ εγω [δε]{.greek-added} μονος αλλα και παντες οι εγνωκοτες την αληθειαν[1:1]{.aside}

δια την αληθειαν την μενουσαν εν ημιν και μεθ ημων εσται εις τον αιωνα[1:2]{.aside}

[εσται]{.greek-omitted} [εστε]{.greek-added} μεθ ημων χαρις ελεος ειρηνη παρα [θεου]{.greek-abbr} [πατρος]{.greek-abbr} και παρα [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του [υιου]{.greek-abbr} του [πατρος]{.greek-abbr} εν αληθεια και αγαπη[1:3]{.aside}

[εχαρην]{.greek-omitted} [εχαριν]{.greek-added} λιαν οτι ευρηκα εκ των τεκνων σου περιπατουντας εν αληθεια καθως εντολην ελαβομεν παρα του [πατρος]{.greek-abbr}[1:4]{.aside}

και νυν ερωτω σε κυρια ουχ ως εντολην γραφων σοι καινην [αλλα]{.greek-omitted} [αλλ]{.greek-added} ην ειχομεν απ αρχης ινα αγαπωμεν αλληλους[1:5]{.aside}

και αυτη εστιν η αγαπη ινα περιπατωμεν κατα τας εντολας αυτου αυτη εστιν η εντολη καθως ηκουσατε απ αρχης ινα εν αυτη [περιπατητε]{.greek-omitted} [περιπατειτε]{.greek-added}[1:6]{.aside}

οτι πολλοι πλανοι εισηλθον εις τον κοσμον οι μη ομολογουντες [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} ερχομενον εν σαρκι ουτος εστιν ο πλανος και ο αντιχριστος[1:7]{.aside}

βλεπετε [εαυτους]{.greek-omitted} [αυτους]{.greek-added} ινα μη απολεσωμεν α ειργασαμεθα αλλα μισθον [πληρη]{.greek-omitted} [πληρης]{.greek-added} απολαβωμεν[1:8]{.aside}

πας ο παραβαινων και μη μενων εν τη διδαχη του [χριστου]{.greek-abbr} [θεον]{.greek-abbr} ουκ εχει ο μενων εν τη διδαχη του [χριστου]{.greek-abbr} ουτος και τον [πατερα]{.greek-abbr} και τον [υιον]{.greek-abbr} εχει[1:9]{.aside}

ει τις ερχεται προς υμας και ταυτην την διδαχην ου φερει [μη]{.greek-omitted} [μι]{.greek-added} λαμβανετε αυτον εις οικιαν και χαιρειν αυτω μη λεγετε[1:10]{.aside}

ο γαρ λεγων αυτω χαιρειν κοινωνει τοις εργοις αυτου τοις πονηροις[1:11]{.aside}

πολλα εχων υμιν γραφειν ουκ εβουληθην δια χαρτου και μελανος [αλλα]{.greek-omitted} [αλλ]{.greek-added} ελπιζω ελθειν προς υμας και στομα προς στομα λαλησαι ινα η χαρα ημων η πεπληρωμενη[1:12]{.aside}

ασπαζεται σε τα τεκνα της αδελφης σου της εκλεκτης αμην[1:13]{.aside}

## Third John

ο πρεσβυτερος γαιω τω αγαπητω ον εγω αγαπω εν αληθεια[1:1]{.aside}

αγαπητε περι παντων ευχομαι σε ευοδουσθαι και υγιαινειν καθως ευοδουται σου η ψυχη[1:2]{.aside}

[εχαρην]{.greek-omitted} [εχαριν]{.greek-added} γαρ λιαν ερχομενων αδελφων και μαρτυρουντων σου τη αληθεια καθως συ εν αληθεια περιπατεις[1:3]{.aside}

μειζοτεραν τουτων ουκ εχω χαραν ινα ακουω τα εμα τεκνα εν αληθεια περιπατουντα[1:4]{.aside}

αγαπητε πιστον ποιεις ο εαν εργαση εις τους αδελφους και εις τους ξενους[1:5]{.aside}

οι εμαρτυρησαν σου τη αγαπη ενωπιον εκκλησιας ους καλως ποιησεις προπεμψας αξιως του [θεου]{.greek-abbr}[1:6]{.aside}

υπερ γαρ του ονοματος εξηλθον μηδεν λαμβανοντες απο των εθνων[1:7]{.aside}

ημεις ουν οφειλομεν απολαμβανειν τους τοιουτους ινα συνεργοι γινωμεθα τη αληθεια[1:8]{.aside}

εγραψα τη εκκλησια αλλ ο φιλοπρωτευων αυτων διοτρεφης ουκ επιδεχεται ημας[1:9]{.aside}

δια τουτο εαν ελθω υπομνησω αυτου τα εργα α ποιει λογοις πονηροις φλυαρων ημας και μη [αρκουμενος]{.greek-omitted} [αρκου]{.greek-added} [μενος]{.greek-added} επι τουτοις ουτε αυτος επιδεχεται τους αδελφους και τους βουλομενους κωλυει και εκ της εκκλησιας εκβαλλει[1:10]{.aside}

αγαπ[η]{.unclear}τε μη μιμου το κακον αλλα το αγαθον ο αγαθοποιων εκ του [θεου]{.greek-abbr} εστιν ο [δε]{.greek-added} κακοποιων ουχ [εωρακεν]{.greek-omitted} [εωρακε]{.greek-added} τον [θεον]{.greek-abbr}[1:11]{.aside}

δημητριω μεμαρτυρηται υπο παντων και υπ αυτης της αληθειας και ημεις δε μαρτυρουμεν και οιδατε οτι η μαρτυρια ημων αληθης εστιν[1:12]{.aside}

πολλα ειχον γραφειν αλλ ου θελω δια μελανος και [καλαμου]{.greek-omitted} [καλαμω]{.greek-added} σοι γραψαι[1:13]{.aside}

ελπιζω δε ευθεως ιδειν σε και στομα προς στομα λαλησομεν [ειρηνη]{.greek-omitted} [σοι]{.greek-omitted} [ασπαζονται]{.greek-omitted} [σε]{.greek-omitted} [οι]{.greek-omitted} [φιλοι]{.greek-omitted} [ασπαζου]{.greek-omitted} [τους]{.greek-omitted} [φιλους]{.greek-omitted} [κατ]{.greek-omitted} [ονομα]{.greek-omitted}[1:14]{.aside}

[ειρηνη]{.greek-added} [σοι]{.greek-added} [ασπαζονται]{.greek-added} [σε]{.greek-added} [οι]{.greek-added} [φιλοι]{.greek-added} [ασπαζου]{.greek-added} [τους]{.greek-added} [φιλους]{.greek-added} [κατ]{.greek-added} [ονομα]{.greek-added} [αμην]{.greek-added}[1:15]{.aside}

## Jude

ιουδας [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} δουλος αδελφος δε ιακωβου τοις εν [θεω]{.greek-abbr} [πατρι]{.greek-abbr} ηγιασμενοις και [ιησου]{.greek-abbr} [χριστω]{.greek-abbr} τετηρημενοις κλητοις[1:1]{.aside}

ελεος υμιν και ειρηνη και αγαπη πληθυνθειη[1:2]{.aside}

αγαπητοι πασαν σπουδην ποιουμενος γραφειν υμιν περι της κοινης [σωτηριας]{.greek-abbr} αναγκην εσχον γραψαι υμιν παρακαλων επαγωνιζεσθαι τη απαξ παραδοθειση τοις αγιοις πιστει[1:3]{.aside}

παρεισεδυσαν γαρ τινες [ανθρωποι]{.greek-abbr} οι παλαι προγεγραμμενοι εις τουτο το κριμα ασεβεις την του [θεου]{.greek-abbr} ημων χαριν μετατιθεντες εις ασελγειαν και τον μονον δεσποτην [θεον]{.greek-abbr} και [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} αρνουμενοι[1:4]{.aside}

υπομνησαι δε υμας βουλομαι ειδοτας υμας απαξ τουτο οτι ο [κυριος]{.greek-abbr} λαον εκ γης αιγυπτου σωσας το δευτερον τους μη πιστευσαντας απωλεσεν[1:5]{.aside}

αγγελους τε τους μη τηρησαντας την εαυτων αρχην αλλα [απολιποντας]{.greek-omitted} [απολειπόντας]{.greek-added} το ιδιον οικητηριον εις κρισιν μεγαλης ημερας δεσμοις αιδιοις υπο ζοφον τετηρηκεν[1:6]{.aside}

ως σοδομα και γομορρα και αι περι αυτας πολεις τον ομοιον τουτοις τροπον εκπορνευσασαι και απελθουσαι οπισω σαρκος ετερας προκεινται [δειγμα]{.greek-omitted} [δηγμα]{.greek-added} πυρος αιωνιου δικην υπεχουσαι[1:7]{.aside}

ομοιως μεντοι και ουτοι ενυπνιαζομενοι σαρκα μεν μιαινουσιν κυριοτητα δε αθετουσιν δοξας δε βλασφημουσιν[1:8]{.aside}

ο δε μιχαηλ ο αρχαγγελος οτε τω διαβολω διακρινομενος διελεγετο περι του μωυσεως σωματος ουκ [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} κρισιν επενεγκειν βλασφημιας αλλ ειπεν [επιτιμησαι]{.greek-omitted} [επιτημησαι]{.greek-added} σοι [κυριος]{.greek-abbr}[1:9]{.aside}

ουτοι δε οσα μεν ουκ [οιδασιν]{.greek-omitted} [οιδασι]{.greek-added} βλασφημουσιν οσα δε φυσικως ως τα αλογα ζωα επιστανται εν τουτοις φθειρονται[1:10]{.aside}

ουαι αυτοις οτι τη οδω του καιν επορευθησαν και τη πλανη του βαλααμ μισθου εξεχυθησαν και τη αντιλογια του κορε απωλοντο[1:11]{.aside}

ουτοι εισιν [οι]{.greek-added} εν ταις αγαπαις υμων σπιλαδες [συνευωχουμενοι]{.greek-omitted} [συνευωχου]{.greek-added} [μενοι]{.greek-added} αφοβως εαυτους ποιμαινοντες νεφελαι ανυδροι υπο ανεμων παραφερομεναι δενδρα [φθινοπωρινα]{.greek-omitted} [φθινωπορινα]{.greek-added} ακαρπα δις αποθανοντα εκριζωθεντα[1:12]{.aside}

κυματα αγρια θαλασσης επαφριζοντα τας εαυτων αισχυνας αστερες [πλανηται]{.greek-omitted} [πλανιται]{.greek-added} οις ο ζοφος του σκοτους εις αιωνα τετηρηται[1:13]{.aside}

[προεφητευσεν]{.greek-omitted} [προεφητευσε]{.greek-added} δε και τουτοις εβδομος απο αδαμ ενωχ λεγων ιδου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} [κυριος]{.greek-abbr} εν αγιαις μυριασιν αυτου[1:14]{.aside}

ποιησαι κρισιν κατα παντων και ελεγξαι παντας τους ασεβεις αυτων περι παντων των εργων ασεβειας αυτων ων ησεβησαν και περι παντων των σκληρων ων ελαλησαν κατ αυτου αμαρτωλοι ασεβει[ς]{.unclear}[1:15]{.aside}

ουτοι [εισιν]{.greek-omitted} [εισι]{.greek-added} γογγυσται [μεμψιμοιροι]{.greek-omitted} [μεμψιμυροι]{.greek-added} κατα τας επιθυμιας [αυτων]{.greek-omitted} [εαυτων]{.greek-added} πορευομενοι και το στομα αυτων λαλει υπερογκα θαυμαζοντες προσωπα [ωφελειας]{.greek-omitted} [ωφελιας]{.greek-added} χαριν[1:16]{.aside}

υμεις δε αγαπητοι μνησθητε των ρηματων των προειρημενων υπο των αποστολων του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:17]{.aside}

οτι ελεγον υμιν [οτι]{.corr} εν εσχατω χρονω εσονται [εμπαικται]{.greek-omitted} [εμπαιγκται]{.greek-added} κατα τας εαυτων επιθυμιας πορευομενοι των ασεβειων[1:18]{.aside}

ουτοι εισιν οι αποδιοριζοντες ψυχικοι [πνευμα]{.greek-abbr} μη εχοντες[1:19]{.aside}

υμεις δε αγαπητοι τη αγιωτατη υμων πιστει εποικοδομουντες εαυτους εν [πνευματι]{.greek-abbr} αγιω [προσευχομενοι]{.greek-omitted} [προσευχο]{.greek-added} [μενοι]{.greek-added}[1:20]{.aside}

εαυτους εν αγαπη [θεου]{.greek-abbr} τηρησατε προσδεχομενοι το ελεος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εις ζωην αιωνιον[1:21]{.aside}

και ους μεν ελεειτε διακρινομενοι[1:22]{.aside}

ους δε εν φοβω σωζετε εκ πυρος αρπαζοντες μισουντες και τον απο της σαρκος εσπιλωμενον χιτωνα[1:23]{.aside}

τω δε δυναμενω φυλαξαι [αυτους]{.greek-omitted} [υμας]{.greek-added} απταιστους και στησαι κατενωπιον της δοξης αυτου αμωμους εν αγαλλιασει[1:24]{.aside}

μονω σοφω [θεω]{.greek-abbr} [σωτηρι]{.greek-abbr} [ημων]{.greek-added} [δια]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} ημων δοξα και μεγαλωσυνη κρατος και εξουσια [προ]{.greek-added} [παντος]{.greek-added} [του]{.greek-added} [αιωνος]{.greek-added} και νυν και εις παντας τους αιωνας [των]{.greek-added} [αιωνων]{.greek-added} αμην[1:25]{.aside}

