---
title: "Collation of Byz^RP^ vs 20025 (25)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 25 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20025).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 25                                   	| λογος                              	|
| 25 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 25 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 25               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 25                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 25 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 25                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 2

[ετεροι]{.greek-omitted} [δε]{.greek-omitted} [χλευαζοντες]{.greek-omitted} [ελεγον]{.greek-omitted} [οτι]{.greek-omitted} [γλευκους]{.greek-omitted} [μεμεστωμενοι]{.greek-omitted} [εισιν]{.greek-omitted}[[2:13 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 6

[εν]{.greek-omitted} [δε]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [ταυταις]{.greek-omitted} [πληθυνοντων]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [εγενετο]{.greek-omitted} [γογγυσμος]{.greek-omitted} [των]{.greek-omitted} [ελληνιστων]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [εβραιους]{.greek-omitted} [οτι]{.greek-omitted} [παρεθεωρουντο]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [διακονια]{.greek-omitted} [τη]{.greek-omitted} [καθημερινη]{.greek-omitted} [αι]{.greek-omitted} [χηραι]{.greek-omitted} [αυτων]{.greek-omitted}[6:1]{.aside}

### Chapter 12

[και]{.greek-omitted} [ιδων]{.greek-omitted} [οτι]{.greek-omitted} [αρεστον]{.greek-omitted} [εστιν]{.greek-omitted} [τοις]{.greek-omitted} [ιουδαιοις]{.greek-omitted} [προσεθετο]{.greek-omitted} [συλλαβειν]{.greek-omitted} [και]{.greek-omitted} [πετρον]{.greek-omitted} [ησαν]{.greek-omitted} [δε]{.greek-omitted} [αι]{.greek-omitted} [ημεραι]{.greek-omitted} [των]{.greek-omitted} [αζυμων]{.greek-omitted}[12:3]{.aside}

### Chapter 16

[αναχθεντες]{.greek-omitted} [ουν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [τρωαδος]{.greek-omitted} [ευθυδρομησαμεν]{.greek-omitted} [εις]{.greek-omitted} [σαμοθρακην]{.greek-omitted} [τη]{.greek-omitted} [τε]{.greek-omitted} [επιουση]{.greek-omitted} [εις]{.greek-omitted} [νεαπολιν]{.greek-omitted}[16:11]{.aside}

### Chapter 17

[τινες]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [επικουρειων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [στοικων]{.greek-omitted} [φιλοσοφων]{.greek-omitted} [συνεβαλλον]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [τινες]{.greek-omitted} [ελεγον]{.greek-omitted} [τι]{.greek-omitted} [αν]{.greek-omitted} [θελοι]{.greek-omitted} [ο]{.greek-omitted} [σπερμολογος]{.greek-omitted} [ουτος]{.greek-omitted} [λεγειν]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [ξενων]{.greek-omitted} [δαιμονιων]{.greek-omitted} [δοκει]{.greek-omitted} [καταγγελευς]{.greek-omitted} [ειναι]{.greek-omitted} [οτι]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [αναστασιν]{.greek-omitted} [ευηγγελιζετο]{.greek-omitted}[17:18]{.aside}

[ξενιζοντα]{.greek-omitted} [γαρ]{.greek-omitted} [τινα]{.greek-omitted} [εισφερεις]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [ακοας]{.greek-omitted} [ημων]{.greek-omitted} [βουλομεθα]{.greek-omitted} [ουν]{.greek-omitted} [γνωναι]{.greek-omitted} [τι]{.greek-omitted} [αν]{.greek-omitted} [θελοι]{.greek-omitted} [ταυτα]{.greek-omitted} [ειναι]{.greek-omitted}[17:20]{.aside}

[ουδε]{.greek-omitted} [υπο]{.greek-omitted} [χειρων]{.greek-omitted} [ανθρωπων]{.greek-omitted} [θεραπευεται]{.greek-omitted} [προσδεομενος]{.greek-omitted} [τινος]{.greek-omitted} [αυτος]{.greek-omitted} [διδους]{.greek-omitted} [πασιν]{.greek-omitted} [ζωην]{.greek-omitted} [και]{.greek-omitted} [πνοην]{.greek-omitted} [κατα]{.greek-omitted} [παντα]{.greek-omitted}[17:25]{.aside}

### Chapter 20

[αναβας]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [κλασας]{.greek-omitted} [αρτον]{.greek-omitted} [και]{.greek-omitted} [γευσαμενος]{.greek-omitted} [εφ]{.greek-omitted} [ικανον]{.greek-omitted} [τε]{.greek-omitted} [ομιλησας]{.greek-omitted} [αχρι]{.greek-omitted} [αυγης]{.greek-omitted} [ουτως]{.greek-omitted} [εξηλθεν]{.greek-omitted}[20:11]{.aside}

### Chapter 26

[ημερας]{.greek-omitted} [μεσης]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [ειδον]{.greek-omitted} [βασιλευ]{.greek-omitted} [ουρανοθεν]{.greek-omitted} [υπερ]{.greek-omitted} [την]{.greek-omitted} [λαμπροτητα]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [περιλαμψαν]{.greek-omitted} [με]{.greek-omitted} [φως]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [συν]{.greek-omitted} [εμοι]{.greek-omitted} [πορευομενους]{.greek-omitted}[26:13]{.aside}

### Chapter 28

[αξιουμεν]{.greek-omitted} [δε]{.greek-omitted} [παρα]{.greek-omitted} [σου]{.greek-omitted} [ακουσαι]{.greek-omitted} [α]{.greek-omitted} [φρονεις]{.greek-omitted} [περι]{.greek-omitted} [μεν]{.greek-omitted} [γαρ]{.greek-omitted} [της]{.greek-omitted} [αιρεσεως]{.greek-omitted} [ταυτης]{.greek-omitted} [γνωστον]{.greek-omitted} [εστιν]{.greek-omitted} [ημιν]{.greek-omitted} [οτι]{.greek-omitted} [πανταχου]{.greek-omitted} [αντιλεγεται]{.greek-omitted}[28:22]{.aside}

[ταξαμενοι]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} [ημεραν]{.greek-omitted} [ηκον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ξενιαν]{.greek-omitted} [πλειονες]{.greek-omitted} [οις]{.greek-omitted} [εξετιθετο]{.greek-omitted} [διαμαρτυρομενος]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [πειθων]{.greek-omitted} [τε]{.greek-omitted} [αυτους]{.greek-omitted} [τα]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [απο]{.greek-omitted} [τε]{.greek-omitted} [του]{.greek-omitted} [νομου]{.greek-omitted} [μωυσεως]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted} [απο]{.greek-omitted} [πρωι]{.greek-omitted} [εως]{.greek-omitted} [εσπερας]{.greek-omitted}[28:23]{.aside}

## First John

### Chapter 0

[0:0]{.aside}

### Chapter 2

[και]{.greek-omitted} [ο]{.greek-omitted} [κοσμος]{.greek-omitted} [παραγεται]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [επιθυμια]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ποιων]{.greek-omitted} [το]{.greek-omitted} [θελημα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μενει]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [αιωνα]{.greek-omitted}[2:17]{.aside}

[παιδια]{.greek-omitted} [εσχατη]{.greek-omitted} [ωρα]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [καθως]{.greek-omitted} [ηκουσατε]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [αντιχριστος]{.greek-omitted} [ερχεται]{.greek-omitted} [και]{.greek-omitted} [νυν]{.greek-omitted} [αντιχριστοι]{.greek-omitted} [πολλοι]{.greek-omitted} [γεγονασιν]{.greek-omitted} [οθεν]{.greek-omitted} [γινωσκομεν]{.greek-omitted} [οτι]{.greek-omitted} [εσχατη]{.greek-omitted} [ωρα]{.greek-omitted} [εστιν]{.greek-omitted}[2:18]{.aside}

## Second John

[2:0]{.aside}

[2:0 | instance no. 2]{.aside}

## Third John

### Chapter 0

[0:0]{.aside}

[0:0 | instance no. 2]{.aside}

## Revelation

### Chapter 1

[και]{.greek-omitted} [εποιησεν]{.greek-omitted} [ημας]{.greek-omitted} [βασιλειαν]{.greek-omitted} [ιερεις]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [και]{.greek-omitted} [πατρι]{.greek-omitted} [αυτου]{.greek-omitted} [αυτω]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τος]{.greek-added} [κρατος]{.greek-omitted} εις τους αιωνας [των]{.greek-omitted} [αιωνων]{.greek-omitted} αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το αλφα και το ω λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [ο]{.greek-added} [κοινωνος]{.greek-omitted} [συγκοινωνος]{.greek-added} εν τη θλιψει και [εν]{.greek-added} [τη]{.greek-added} βασιλεια και υπομονη εν [χριστω]{.greek-omitted} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-omitted}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα [φωνην]{.greek-omitted} οπισω μου [φωνην]{.greek-added} μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης [εγω]{.greek-added} [αλφα]{.greek-added} [και]{.greek-added} [το]{.greek-added} [ω]{.greek-added} [πρωτος]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [εσχατος]{.greek-added} [και]{.greek-added} ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα [εκκλησιαις]{.greek-omitted} [εκκλησι]{.greek-added} [εις]{.greek-omitted} [εφεσον]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [σμυρναν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [περγαμον]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [θυατειρα]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [σαρδεις]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [φιλαδελφειαν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [λαοδικειαν]{.greek-omitted}[1:11]{.aside}

[λις]{.greek-added} [λεγουσης]{.greek-omitted} [ο]{.greek-omitted} [βλεπεις]{.greek-omitted} [γραψον]{.greek-omitted} [εις]{.greek-omitted} [βιβλιον]{.greek-omitted} [και]{.greek-omitted} [πεμψον]{.greek-omitted} [ταις]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαις]{.greek-omitted} εις εφεσον και εις σμυρναν και εις περγαμον και [εις]{.greek-omitted} [εν]{.greek-added} [θυατειρα]{.greek-omitted} [θυατειρoις]{.greek-added} και εις σαρδεις και εις [φιλαδελφειαν]{.greek-omitted} [φιλαδελφιαν]{.greek-added} και εις λαοδικειαν[1:11 | instance no. 2]{.aside}

και [εκει]{.greek-omitted} επεστρεψα βλεπειν την φωνην ητις [ελαλει]{.greek-omitted} [ελαλησεν]{.greek-added} μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των [επτα]{.greek-omitted} λυχνιων ομοιον υιω ανθρωπου ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις μαστοις ζωνην [χρυσην]{.greek-omitted} [χρυσαν]{.greek-added}[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι [ως]{.greek-omitted} [ωσει]{.greek-added} εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκωλιβανω]{.greek-added} ως εν [αμινω]{.greek-added} [καμινω]{.corr} πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια [χειρι]{.greek-added} αυτου [χειρι]{.greek-omitted} αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη [και]{.greek-omitted} [η]{.greek-omitted} [οψις]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [φαινει]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δυναμει]{.greek-omitted} [αυτου]{.greek-omitted}[1:16]{.aside}

[και]{.greek-omitted} [εχων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δεξια]{.greek-omitted} [αυτου]{.greek-omitted} [χειρι]{.greek-omitted} [αστερας]{.greek-omitted} [επτα]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτου]{.greek-omitted} [ρομφαια]{.greek-omitted} [διστομος]{.greek-omitted} [οξεια]{.greek-omitted} [εκπορευομενη]{.greek-omitted} και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16 | instance no. 2]{.aside}

και οτε ειδον αυτον επεσα προς τους ποδας αυτου ως νεκρος και εθηκεν την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων [αμην]{.greek-omitted} και εχω τας κλεις του θανατου και του αδου[1:18]{.aside}

γραψον ουν α ειδες και α εισιν και α μελλει [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων [ων]{.greek-omitted} [ους]{.greek-added} ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν και αι λυχνιαι αι επτα [ας]{.greek-added} [ειδες]{.greek-added} επτα εκκλησιαι εισιν[1:20]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη [δεξια]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [περιπατων]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιων]{.greek-omitted} [των]{.greek-omitted} [χρυσων]{.greek-omitted}[2:1]{.aside}

[τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [εφεσω]{.greek-omitted} [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [κρατων]{.greek-omitted} [τους]{.greek-omitted} [επτα]{.greek-omitted} [αστερας]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1 | instance no. 2]{.aside}

οιδα τα εργα σου και τον κοπον [σου]{.greek-omitted} και την υπομονην σου και οτι ου δυνη [βαστασαι]{.greek-omitted} [βασταξαι]{.greek-added} κακους και επειρασας τους λεγοντας εαυτους αποστολους [ειναι]{.greek-omitted} και ουκ εισιν και ευρες αυτους ψευδεις[2:2]{.aside}

[και]{.greek-added} [εβαστασας]{.greek-added} [με]{.greek-added} και υπομονην εχεις [και]{.greek-omitted} [εβαστασας]{.greek-omitted} δια το ονομα μου και ουκ εκοπιασας[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν [πεπτωκας]{.greek-omitted} [εκπεπτωκας]{.greek-added} και μετανοησον και τα πρωτα εργα ποιησον ει δε μη [ερχομαι]{.greek-omitted} [ερχομε]{.greek-added} σοι [ταχυ]{.greek-omitted} και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι [μσεις]{.greek-added} [μισεις]{.corr} τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω [νικωντι]{.greek-omitted} [νικων]{.greek-added} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [φαγειν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [παραδεισω]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted}[2:7]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} τι [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [τω]{.greek-omitted} [νικωντι]{.greek-omitted} δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν [μεσω]{.greek-added} τω [παραδεισω]{.greek-omitted} [παραδισω]{.greek-added} του [θεου]{.greek-abbr} [μου]{.greek-omitted}[2:7 | instance no. 2]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου [τα]{.greek-omitted} [εργα]{.greek-omitted} [και]{.greek-omitted} την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν [εκ]{.greek-omitted} των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βαλλειν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και [εξετε]{.greek-omitted} [εχητε]{.greek-added} θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [την]{.greek-omitted} [ρομφαιαν]{.greek-omitted} [την]{.greek-omitted} [διστομον]{.greek-omitted} [την]{.greek-omitted} [οξειαν]{.greek-omitted}[2:12]{.aside}

[και]{.greek-omitted} [τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [περγαμω]{.greek-omitted} εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την [οξειαν]{.greek-omitted} [οξιαν]{.greek-added}[2:12 | instance no. 2]{.aside}

οιδα [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις [ημεραις]{.greek-omitted} [ημερες]{.greek-added} εν αις αντιπας ο μαρτυς μου ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδασκεν]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [βαλααμ]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως [ομισω]{.greek-added}[2:15]{.aside}

μετανοησον [ουν]{.greek-omitted} ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [τω]{.greek-omitted} [νικωντι]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [του]{.greek-omitted} [μαννα]{.greek-omitted} [του]{.greek-omitted} [κεκρυμμενου]{.greek-omitted} [και]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [ψηφον]{.greek-omitted} [λευκην]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [ψηφον]{.greek-omitted} [ονομα]{.greek-omitted} [καινον]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [ο]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [λαμβανων]{.greek-omitted}[2:17]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω [φαγειν]{.greek-added} [απο]{.greek-added} του [μαννα]{.greek-omitted} [ξυλου]{.greek-added} του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17 | instance no. 2]{.aside}

και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατηροις]{.greek-added} εκκλησιας γραψον ταδε λεγει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκωλιβανω]{.greek-added}[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου οτι αφεις την γυναικα [σου]{.greek-omitted} ιεζαβελ [η]{.greek-omitted} [λεγει]{.greek-omitted} [την]{.greek-added} [λεγουσαν]{.greek-added} εαυτην [προφητιν]{.greek-omitted} [προφητην]{.greek-added} και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και [εδωκα]{.greek-omitted} [εδω]{.greek-added} [αυτη]{.greek-omitted} [χρονον]{.greek-omitted} [ινα]{.greek-omitted} [μετανοηση]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [θελει]{.greek-omitted} [μετανοησαι]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted}[2:21]{.aside}

[και]{.greek-omitted} [κα]{.greek-added} [εδωκα]{.greek-omitted} αυτη χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21 | instance no. 2]{.aside}

ιδου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν [θυατειροις]{.greek-omitted} [θυατηροις]{.greek-added} οσοι ουκ εχουσιν την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθη]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω [σι]{.greek-added} [σιδηρα]{.greek-omitted} [ως]{.greek-omitted} [τα]{.greek-omitted} [σκευη]{.greek-omitted} [τα]{.greek-omitted} [κεραμικα]{.greek-omitted} [συντριβησεται]{.greek-omitted} [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[και]{.greek-omitted} [ποιμανει]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [ραβδω]{.greek-omitted} [σιδηρα]{.greek-omitted} [δηρα]{.greek-added} ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27 | instance no. 2]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα πνευματα του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και στηρισον τα λοιπα α [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [εμελλον]{.greek-added} [αποθανειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη [γρηγορησης]{.greek-omitted} [γρειγορησης]{.greek-added} ηξω [επι]{.greek-omitted} [σε]{.greek-omitted} ως κλεπτης και ου μη γνως ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ [εχεις]{.greek-added} ολιγα [εχεις]{.greek-omitted} ονοματα εν σαρδεσιν α ουκ [εμολυναν]{.greek-omitted} [εμωλυναν]{.greek-added} τα ιματια αυτων [και]{.greek-omitted} [περιπατησουσιν]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [εν]{.greek-omitted} [λευκοις]{.greek-omitted} [οτι]{.greek-omitted} [αξιοι]{.greek-omitted} [εισιν]{.greek-omitted}[3:4]{.aside}

[αλλ]{.greek-omitted} [ολιγα]{.greek-omitted} [εχεις]{.greek-omitted} [ονοματα]{.greek-omitted} [εν]{.greek-omitted} [σαρδεσιν]{.greek-omitted} [α]{.greek-omitted} [ουκ]{.greek-omitted} [εμολυναν]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτων]{.greek-omitted} και περιπατησουσιν μετ [εμ]{.greek-added} [εμου]{.corr} εν λευκοις οτι αξιοι εισιν[3:4 | instance no. 2]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει [και]{.greek-added} [κλειων]{.greek-added} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} και ουδεις [ανοιξει]{.greek-omitted} [ανοιγει]{.greek-added}[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν [ανεωγμενην]{.greek-omitted} [ηνεωγμενην]{.greek-added} ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και [ετηρησα]{.greek-added} [ετηρησας]{.corr} μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξουσιν]{.greek-added} και [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσιν]{.greek-added} ενωπιον των ποδων σου και γνωσιν οτι [εγω]{.greek-added} ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της [υπομονη]{.greek-added} [υπομονης]{.corr} μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η [καταβαινει]{.greek-omitted} [καταβενουσα]{.greek-added} εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα [μ]{.greek-added} [μου]{.corr} [το]{.greek-omitted} [καινον]{.greek-omitted}[3:12]{.aside}

[ο]{.greek-omitted} [νικων]{.greek-omitted} [ποιησω]{.greek-omitted} [αυτον]{.greek-omitted} [στυλον]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ναω]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [εξω]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [εξελθη]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [γραψω]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted} [της]{.greek-omitted} [καινης]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [η]{.greek-omitted} [καταβαινει]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} το καινον[3:12 | instance no. 2]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος [οφελον]{.greek-omitted} [ωφελον]{.greek-added} ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και [ου]{.greek-omitted} [ζεστος]{.greek-omitted} ουτε ψυχρος [ουτε]{.greek-added} [ζεστος]{.greek-added} μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και πεπλουτηκα και [ουδενος]{.greek-omitted} [ουδεν]{.greek-added} [ος]{.greek-added} χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και [ο]{.greek-omitted} ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι [χρυσιον]{.greek-omitted} παρ εμου [χρυσιον]{.greek-added} πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η [αισχυνη]{.greek-omitted} [ασχημοσυνη]{.greek-added} της γυμνοτητος σου και [κολ]{.greek-added} [κολλυριον]{.greek-omitted} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [τους]{.greek-omitted} [οφθαλμους]{.greek-omitted} [σου]{.greek-omitted} [ινα]{.greek-omitted} [βλεπης]{.greek-omitted}[3:18]{.aside}

[συμβουλευω]{.greek-omitted} [σοι]{.greek-omitted} [αγορασαι]{.greek-omitted} [χρυσιον]{.greek-omitted} [παρ]{.greek-omitted} [εμου]{.greek-omitted} [πεπυρωμενον]{.greek-omitted} [εκ]{.greek-omitted} [πυρος]{.greek-omitted} [ινα]{.greek-omitted} [πλουτησης]{.greek-omitted} [και]{.greek-omitted} [ιματια]{.greek-omitted} [λευκα]{.greek-omitted} [ινα]{.greek-omitted} [περιβαλη]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [φανερωθη]{.greek-omitted} [η]{.greek-omitted} [αισχυνη]{.greek-omitted} [της]{.greek-omitted} [γυμνοτητος]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [κολλυριον]{.greek-omitted} [λουριον]{.greek-added} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [εγχρισον]{.greek-added} τους οφθαλμους σου ινα βλεπης[3:18 | instance no. 2]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω ζηλωσον ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν [και]{.greek-omitted} εισελευσομαι προς αυτον και [δειπνησω]{.greek-omitted} [διπνησω]{.greek-added} μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα [ανεωγμενη]{.greek-omitted} [ηνεωγμενη]{.greek-added} εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου [λεγων]{.greek-omitted} [λεγουσα]{.greek-added} αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} [και]{.greek-omitted} [ιδου]{.greek-omitted} [θρονος]{.greek-omitted} [εκειτο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [θρονον]{.greek-omitted} [καθημενος]{.greek-omitted}[4:2]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [εγενομην]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι [τον]{.greek-omitted} [του]{.greek-added} [θρονον]{.greek-omitted} [θρονου]{.greek-added} καθημενος[4:2 | instance no. 2]{.aside}

[και]{.greek-added} [ο]{.greek-added} [καθημενος]{.greek-added} ομοιος ορασει λιθω ιασπιδι και [σαρδιω]{.greek-omitted} [σαρδινω]{.greek-added} και [ιρις]{.greek-omitted} [ϊρις]{.greek-added} κυκλοθεν του θρονου [ομοιως]{.greek-omitted} [ομοιος]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδινω]{.greek-added}[4:3]{.aside}

και κυκλοθεν του θρονου θρονοι εικοσι τεσσαρες και επι τους θρονους [τους]{.greek-omitted} εικοσι τεσσαρας πρεσβυτερους καθημενους περιβεβλημενους [εν]{.greek-omitted} ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου [α]{.greek-added} [αυτου]{.greek-omitted} [αι]{.greek-omitted} εισιν [τα]{.greek-added} επτα πνευματα του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων [εμπροσθεν]{.greek-omitted} [εμπροσ]{.greek-added} [και]{.greek-omitted} [οπισθεν]{.greek-omitted}[4:6]{.aside}

[και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [ως]{.greek-omitted} [θαλασσα]{.greek-omitted} [υαλινη]{.greek-omitted} [ομοια]{.greek-omitted} [κρυσταλλω]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [θεν]{.greek-added} [μεσω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [κυκλω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [τεσσαρα]{.greek-omitted} [ζωα]{.greek-omitted} [γεμοντα]{.greek-omitted} [οφθαλμων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} και οπισθεν[4:6 | instance no. 2]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον εχον [το]{.greek-added} προσωπον [ως]{.greek-added} [ανθρωπου]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} και το τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} [εχον]{.greek-omitted} [εχοντα]{.greek-added} ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσουσι]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλου]{.greek-added} [τους]{.greek-omitted} [στεφανους]{.greek-omitted} [αυτων]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [λεγοντες]{.greek-omitted}[4:10]{.aside}

[σι]{.greek-added} [πεσουνται]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [προσκυνησουσιν]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [και]{.greek-omitted} [βαλουσιν]{.greek-omitted} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10 | instance no. 2]{.aside}

αξιος ει [[κυριε]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [κυριος]{.greek-omitted} και ο [θεος]{.greek-abbr} ημων [ο]{.greek-omitted} [αγιος]{.greek-omitted} λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας [τα]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισιν]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα [εν]{.greek-omitted} φωνη μεγαλη τις αξιος [εστιν]{.greek-omitted} ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εν τω [ουρανω]{.greek-abbr} [ανω]{.greek-omitted} [ουτε]{.greek-omitted} [ουδε]{.greek-added} επι της γης [ουτε]{.greek-omitted} [ουδε]{.greek-added} υποκατω της γης ανοιξαι το βιβλιον [ουτε]{.greek-omitted} [ουδε]{.greek-added} βλεπειν αυτο[5:3]{.aside}

και [εγω]{.greek-omitted} εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων [λε]{.greek-added} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [μη]{.greek-omitted} [κλαιε]{.greek-omitted} [ιδου]{.greek-omitted} [ενικησεν]{.greek-omitted} [ο]{.greek-omitted} [λεων]{.greek-omitted} [ο]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [φυλης]{.greek-omitted} [ιουδα]{.greek-omitted} [η]{.greek-omitted} [ριζα]{.greek-omitted} [δαυιδ]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [σφραγιδας]{.greek-omitted} [αυτου]{.greek-omitted}[5:5]{.aside}

[και]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [λεγει]{.greek-omitted} [γει]{.greek-added} [μοι]{.greek-omitted} μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και τας επτα σφραγιδας αυτου[5:5 | instance no. 2]{.aside}

και ειδον εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως εσφαγμενον εχον κερατα επτα και οφθαλμους επτα [α]{.greek-omitted} [εισιν]{.greek-omitted} [τα]{.greek-omitted} [επτα]{.greek-omitted} πνευματα του [θεου]{.greek-abbr} [αποστελλομενα]{.greek-omitted} [[απoστελλομε]{.greek-supplied}να]{.greek-added} εις πασαν την γην[[5:6 *(lacunose)*]{.lacunose}]{.aside}

και ηλθεν και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε ελαβεν το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι [επεσον]{.greek-omitted} [[επεσαν]{.greek-supplied}]{.greek-added} [ενωπιον]{.greek-supplied} του αρνιου [εχοντες]{.greek-supplied} [εκαστος]{.greek-supplied} κιθαραν και φιαλας χρυσας γεμουσας θυμιαματων αι εισιν [αι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας [σφραγιδας]{.greek-omitted} [σφραγι]{.greek-added} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [εσφαγης]{.greek-omitted} [και]{.greek-omitted} [ηγορασας]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [ημας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αιματι]{.greek-omitted} [σου]{.greek-omitted} [εκ]{.greek-omitted} [πασης]{.greek-omitted} [φυλης]{.greek-omitted} [και]{.greek-omitted} [γλωσσης]{.greek-omitted} [και]{.greek-omitted} [λαου]{.greek-omitted} [και]{.greek-omitted} [εθνους]{.greek-omitted}[[5:9 *(lacunose)*]{.lacunose}]{.aside}

[δας]{.greek-added} [και]{.greek-omitted} [αδουσιν]{.greek-omitted} [ωδην]{.greek-omitted} [καινην]{.greek-omitted} [λεγοντες]{.greek-omitted} [αξιος]{.greek-omitted} [ει]{.greek-omitted} [λαβειν]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [και]{.greek-omitted} [ανοιξαι]{.greek-omitted} [τας]{.greek-omitted} [σφραγιδας]{.greek-omitted} αυτου οτι εσφαγης και ηγορασας [τω]{.unclear} [[θεω]{.greek-abbr}]{.unclear} [ημας]{.unclear} [εν]{.unclear} [τω]{.unclear} [αι]{.unclear}ματι σου [εκ]{.greek-omitted} [πασης]{.greek-omitted} [φυλης]{.greek-omitted} και γλωσσης [και]{.greek-omitted} [λαου]{.greek-omitted} [και]{.greek-omitted} [εθνους]{.greek-omitted}[[5:9 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

και [εποι[―]{.gap}]{.greek-added} [εποιησας]{.greek-omitted} [αυτους]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [ημων]{.greek-omitted} [μων]{.greek-added} [βασιλεις]{.greek-omitted} [και]{.greek-omitted} [ιερεις]{.greek-omitted} [και]{.greek-omitted} βασιλευσουσιν επι της γης[[5:10 *(lacunose)*]{.lacunose}]{.aside}

και ειδον και ηκουσα [ως]{.greek-omitted} φωνην αγγελων πολλων κυκλω [τ]{.greek-added} [του]{.corr} θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξ[ιον]{.greek-supplied} [εσ]{.greek-supplied}τιν το αρνιον το εσφαγμενον λαβειν την δυναμιν και [τον]{.greek-omitted} πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν τω [ουρανω]{.greek-abbr} και επι της γης και υποκατω της γης και επι της θαλασσης [α]{.greek-added} εστιν και τα εν αυτοις [παντας]{.greek-omitted} [παντα]{.greek-added} ηκουσα λεγοντας τω [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [κα]{.greek-added} [τω]{.greek-omitted} [αρνιω]{.greek-omitted} [η]{.greek-omitted} [ευλογια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [τιμη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [κρατος]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [αμην]{.greek-omitted}[5:13]{.aside}

### Chapter 6

[και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [αλλος]{.greek-omitted} [ιππος]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [λαβειν]{.greek-omitted} [την]{.greek-omitted} [ειρηνην]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ινα]{.greek-omitted} [αλληλους]{.greek-omitted} [σφαξωσιν]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [μαχαιρα]{.greek-omitted} [χαιρα]{.greek-added} μεγαλη[6:4]{.aside}

και οτε ηνοιξεν την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [ειδον]{.greek-added} και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα [ως]{.greek-added} φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες [κριθης]{.greek-omitted} [κριθων]{.greek-added} δηναριου και το ελαιον και τον οινον μη [αδικησης]{.greek-omitted} [αδικησις]{.greek-added}[6:6]{.aside}

και οτε ηνοιξεν την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος [χλωρος]{.greek-omitted} [χλορος]{.greek-added} και ο καθημενος επανω [αυτου]{.greek-omitted} ονομα αυτω ο θανατος και ο [αδη]{.greek-added} [αδης]{.corr} ηκολουθει [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} και εδοθη [αυτω]{.greek-omitted} [αυτοις]{.greek-added} εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε ηνοιξεν την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των [[ανθρωπων]{.greek-abbr}]{.greek-added} [των]{.greek-added} εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} ην ειχον[6:9]{.aside}

και [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων [εκ]{.greek-omitted} [απο]{.greek-added} των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} ετι χρονον [μικρον]{.greek-added} εως πληρωσωσιν και οι συνδουλοι αυτων και οι αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκτεινεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

και ειδον [και]{.greek-added} οτε ηνοιξεν την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος [εγενετο]{.greek-added} μελας [εγενετο]{.greek-omitted} ως σακκος τριχινος και η σεληνη [ολη]{.greek-omitted} εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ου]{.greek-added} [ουρανου]{.greek-omitted} [επεσον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [ως]{.greek-omitted} [συκη]{.greek-omitted} [βαλουσα]{.greek-omitted} [τους]{.greek-omitted} [ολυνθους]{.greek-omitted} [αυτης]{.greek-omitted} [υπο]{.greek-omitted} [ανεμου]{.greek-omitted} [μεγαλου]{.greek-omitted} [σειομενη]{.greek-omitted}[6:13]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [αστερες]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [ρανου]{.greek-added} [επεσον]{.greek-omitted} [επεσαν]{.greek-added} εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλει]{.greek-added} τους ολυνθους [αυτη]{.greek-added} [αυτης]{.corr} υπο [μεγαλου]{.greek-added} ανεμου [μεγαλου]{.greek-omitted} σειομενη[6:13 | instance no. 2]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ειλισσομενον]{.greek-added} και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και [πας]{.greek-added} ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις [πεσετε]{.greek-omitted} [πεσατε]{.greek-added} εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

και μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} ειδον τεσσαρας αγγελους εστωτας επι τας [τεσσαρας]{.greek-omitted} [τεσσαρες]{.greek-added} γωνιας της γης κρατουντας τους τεσσαρας ανεμους [της]{.greek-omitted} [γης]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [πνεη]{.greek-omitted} [ανεμος]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [μητε]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [μητε]{.greek-omitted} [επι]{.greek-omitted} [τι]{.greek-omitted} [δενδρον]{.greek-omitted}[7:1]{.aside}

[και]{.greek-omitted} [μετα]{.greek-omitted} [τουτο]{.greek-omitted} [ειδον]{.greek-omitted} [τεσσαρας]{.greek-omitted} [αγγελους]{.greek-omitted} [εστωτας]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [τεσσαρας]{.greek-omitted} [γωνιας]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [κρατουντας]{.greek-omitted} [τους]{.greek-omitted} [τεσσαρας]{.greek-omitted} [ανεμους]{.greek-omitted} της γης ινα μη πνεη ανεμος επι της γης μητε επι της θαλασσης μητε επι [τι]{.greek-omitted} [παν]{.greek-added} δενδρον[7:1 | instance no. 2]{.aside}

και ειδον αλλον αγγελον [αναβενοντ]{.greek-added} [αναβαινοντα]{.greek-omitted} [[αναβενοντα]{.corr}]{.greek-added} απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραζεν]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

[λεγων]{.greek-omitted} [λεγον]{.greek-added} μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα αχρι [ου]{.greek-omitted} σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον [και]{.greek-omitted} τεσσαρακοντα τεσσαρες χιλιαδες [εσφραγισμενων]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης [ρουβιμ]{.greek-omitted} [δωδεκα]{.greek-omitted} [ρουβην]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης γαδ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [νεφθαλειμ]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [μανασση]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted}[7:6]{.aside}

[εκ]{.greek-omitted} [φυλης]{.greek-omitted} [ασηρ]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} εκ φυλης νεφθαλειμ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης μανασση [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:6 | instance no. 2]{.aside}

εκ φυλης συμεων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης λευι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [ισαχαρ]{.greek-omitted} [ισσαχαρ]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμειν]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφ[ρα]{.greek-supplied}[γισμ[ενοι]{.greek-supplied}]{.greek-supplied}]{.greek-added}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι [αυτον]{.greek-added} ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εκ παντος εθνους και φυλων και λαων και γλωσσων [εστωτας]{.greek-omitted} [εστοτες]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου [περιβεβλημενους]{.greek-omitted} [περιβεβλημενοι]{.greek-added} στολας λευκας και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η σωτηρια τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω θρονω και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι [ειστηκεισαν]{.greek-omitted} [ιστηκεισαν]{.greek-added} κυκλω του θρονου και των πρεσβυτερων και των [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [και]{.greek-omitted} [επεσον]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [επι]{.greek-omitted} [τα]{.greek-omitted} [προσωπα]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[7:11]{.aside}

[και]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [ειστηκεισαν]{.greek-omitted} [κυκλω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} τεσσαρων ζωων και [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του θρονου επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11 | instance no. 2]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η [δυναμις]{.greek-omitted} [δυναμεις]{.greek-added} και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες εισιν και ποθεν ηλθον[7:13]{.aside}

και [ειπον]{.greek-omitted} [ειρηκα]{.greek-added} αυτω κυριε μου συ οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της [μεγαλη]{.greek-added} [μεγαλης]{.corr} και επλυναν τας στολας αυτων και ελευκαναν [αυτας]{.greek-added} εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι τω θρονω σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε [διψησουσιν]{.greek-omitted} [διψησωσιν]{.greek-added} [ετι]{.greek-omitted} [ουδ]{.greek-omitted} [ουδε]{.greek-added} [ου]{.greek-omitted} μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγησει]{.greek-added} αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε ηνοιξεν την σφραγιδα την εβδομην εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως ημιωριον[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} εστηκασιν και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος ηλθεν και εσταθη επι [του]{.greek-omitted} [το]{.greek-added} [θυσιαστηριου]{.greek-omitted} [θυσιαστηριον]{.greek-added} εχων λιβανωτον χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα δωση ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των [θυμι]{.greek-added} [θυμιαματων]{.greek-omitted} [ταις]{.greek-omitted} [προσευχαις]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [εκ]{.greek-omitted} [χειρος]{.greek-omitted} [του]{.greek-omitted} [αγγελου]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[8:4]{.aside}

[και]{.greek-omitted} [ανεβη]{.greek-omitted} [ο]{.greek-omitted} [καπνος]{.greek-omitted} [των]{.greek-omitted} [θυμιαματων]{.greek-omitted} [αματων]{.greek-added} ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4 | instance no. 2]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και [εγεμισεν]{.greek-omitted} [εγεμησεν]{.greek-added} αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο [φωναι]{.greek-added} [και]{.greek-added} βρονται [και]{.greek-omitted} [φωναι]{.greek-omitted} και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος εσαλπισεν και εγενετο χαλαζα και πυρ [μεμιγμενα]{.greek-omitted} [μεμιγμενον]{.greek-added} εν αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος [χλωρος]{.greek-omitted} [χλορος]{.greek-added} κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος εσαλπισεν και ως ορος μεγα [πυρι]{.greek-added} [καιομενον]{.greek-omitted} [κεομενον]{.greek-added} εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και απεθανεν το τριτον [των]{.greek-omitted} [κτισματων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [τα]{.greek-omitted} [εχοντα]{.greek-omitted} [ψυχας]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [πλοιων]{.greek-omitted} [διεφθαρη]{.greek-omitted}[8:9]{.aside}

[και]{.greek-omitted} [απεθανεν]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} των κτισματων [των]{.greek-added} εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων [διεφθαρη]{.greek-omitted} [διεφθαρησαν]{.greek-added}[8:9 | instance no. 2]{.aside}

και ο τριτος αγγελος εσαλπισεν και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο [αψινθος]{.greek-omitted} [αψινθο]{.greek-added} [[αψινθο]{.corr}]{.greek-added} και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος εσαλπισεν και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [μη]{.greek-added} [φενη]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος [αγγε]{.greek-added} [αετου]{.greek-omitted} [πετομενου]{.greek-omitted} [εν]{.greek-omitted} [μεσουρανηματι]{.greek-omitted} [λεγοντος]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [ουαι]{.greek-omitted} [ουαι]{.greek-omitted} [ουαι]{.greek-omitted} [τοις]{.greek-omitted} [κατοικουσιν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [λοιπων]{.greek-omitted} [φωνων]{.greek-omitted} [της]{.greek-omitted} [σαλπιγγος]{.greek-omitted} [των]{.greek-omitted} [τριων]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [μελλοντων]{.greek-omitted} [σαλπιζειν]{.greek-omitted}[8:13]{.aside}

[λου]{.greek-added} [και]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} [ηκουσα]{.greek-omitted} [ενος]{.greek-omitted} [αετου]{.greek-omitted} πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13 | instance no. 2]{.aside}

### Chapter 9

και ο πεμπτος αγγελος εσαλπισεν και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα [εις]{.greek-omitted} [επι]{.greek-added} την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και ηνοιξεν το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος ως καπνος καμινου [καιομενης]{.greek-omitted} [μεγαλης]{.greek-added} και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη αδικησωσιν τον χορτον της γης ουδε παν χλωρον [ουδε]{.greek-omitted} [παν]{.greek-omitted} [δενδρον]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [οιτινες]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[9:4]{.aside}

[και]{.greek-omitted} [ερρεθη]{.greek-omitted} [αυταις]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [αδικησωσιν]{.greek-omitted} [τον]{.greek-omitted} [χορτον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ουδε]{.greek-omitted} [παν]{.greek-omitted} [χλωρον]{.greek-omitted} ουδε παν δενδρον ει μη [του]{.greek-added} [τους]{.corr} [ανθρωπους]{.greek-abbr} οιτινες ουκ εχουσιν την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων [αυτων]{.greek-omitted}[9:4 | instance no. 2]{.aside}

και εδοθη [αυταις]{.greek-omitted} [αυτοις]{.greek-added} ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθησονται]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [πεση]{.greek-added} ανθρωπον[9:5]{.aside}

και εν ταις [ημεραις]{.greek-omitted} [ημερες]{.greek-added} εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [ευρωσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευγει]{.greek-added} [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι [χρυσοι]{.greek-omitted} [ομοιοι]{.greek-added} [χρυσω]{.greek-added} και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον [θω]{.greek-added} [θωρακας]{.greek-omitted} [ως]{.greek-omitted} [θωρακας]{.greek-omitted} [σιδηρους]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [των]{.greek-omitted} [πτερυγων]{.greek-omitted} [αυτων]{.greek-omitted} [ως]{.greek-omitted} [φωνη]{.greek-omitted} [αρματων]{.greek-omitted} [ιππων]{.greek-omitted} [πολλων]{.greek-omitted} [τρεχοντων]{.greek-omitted} [εις]{.greek-omitted} [πολεμον]{.greek-omitted}[9:9]{.aside}

[και]{.greek-omitted} [ειχον]{.greek-omitted} [θωρακας]{.greek-omitted} [ρακας]{.greek-added} ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9 | instance no. 2]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα και εν ταις ουραις αυτων [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[και]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσιν]{.greek-added} [[επ]{.corr}]{.greek-added} [[αυτον]{.corr}]{.greek-added} βασιλεα [τον]{.greek-added} [επ]{.greek-omitted} [αυτων]{.greek-omitted} αγγελον της αβυσσου ονομα αυτω εβραιστι [αββαδων]{.greek-omitted} [αβαδδων]{.greek-added} [και]{.greek-added} εν [δε]{.greek-omitted} τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

λεγουσαν [τ]{.greek-added} [τω]{.corr} εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω [ευφρατη]{.greek-omitted} [πο]{.greek-added}[9:14]{.aside}

[λεγουσαν]{.greek-omitted} [τω]{.greek-omitted} [εκτω]{.greek-omitted} [αγγελω]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [την]{.greek-omitted} [σαλπιγγα]{.greek-omitted} [λυσον]{.greek-omitted} [τους]{.greek-omitted} [τεσσαρας]{.greek-omitted} [αγγελους]{.greek-omitted} [τους]{.greek-omitted} [δεδεμενους]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [ποταμω]{.greek-omitted} [ταμω]{.greek-added} [τω]{.greek-omitted} [μεγαλω]{.greek-omitted} ευφρατη[9:14 | instance no. 2]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και [εις]{.greek-omitted} [την]{.greek-omitted} ημεραν και μηνα και ενιαυτον ινα αποκτεινωσιν το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [ιππου]{.greek-omitted} [ιππικου]{.greek-added} [δεισ]{.greek-added} μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και [ουτω]{.greek-added} [ουτως]{.corr} ειδον τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του πυρος και του καπνου και [εκ]{.greek-added} του θειου του εκπορευομενου εκ των [στο]{.greek-added} [στοματων]{.greek-omitted} [αυτων]{.greek-omitted}[9:18]{.aside}

[απο]{.greek-omitted} [των]{.greek-omitted} [τριων]{.greek-omitted} [πληγων]{.greek-omitted} [τουτων]{.greek-omitted} [απεκτανθησαν]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [καπνου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [θειου]{.greek-omitted} [του]{.greek-omitted} [εκπορευομενου]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [στοματων]{.greek-omitted} [ματων]{.greek-added} αυτων[9:18 | instance no. 2]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων εστιν και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσαις]{.greek-added} κεφαλας και εν αυταις αδικουσιν[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις [ου]{.greek-omitted} [ουτε]{.greek-added} μετενοησαν εκ των εργων των χειρων αυτων ινα μη προσκυνησωσιν τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακιων]{.greek-added} αυτων ουτε εκ της [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} [περιβεβλημενον]{.greek-omitted} [νεφελην]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [ιρις]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ποδες]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [στυλοι]{.greek-omitted} [πυρος]{.greek-omitted}[10:1]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [ος]{.greek-omitted} [εκτισεν]{.greek-omitted} τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν και ετελεσθη το [μυστριον]{.greek-added} [μυστηριον]{.corr} του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους [εαυτου]{.greek-added} δουλους [αυτου]{.greek-omitted} τους [προφητα]{.greek-added} [προφητας]{.corr}[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν [λαλουσα]{.greek-omitted} [λαλουσαν]{.greek-added} μετ εμου και [λεγουσα]{.greek-omitted} [λεγουσαν]{.greek-added} υπαγε λαβε το [βιβλιδαριον]{.greek-omitted} [βιβλαριδιον]{.greek-added} το [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω [δουναι]{.greek-omitted} [δος]{.greek-added} μοι το [βιβλιδαριον]{.greek-omitted} [βιβλαριδιον]{.greek-added} και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βιβλαριδιον]{.greek-added} εκ της χειρος του αγγελου και κατεφαγον αυτο και ην [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [μου]{.greek-omitted} [ως]{.greek-omitted} [μελι]{.greek-omitted} [γλυκυ]{.greek-omitted} [και]{.greek-omitted} [οτε]{.greek-omitted} [εφαγον]{.greek-omitted} [αυτο]{.greek-omitted} [επικρανθη]{.greek-omitted} [η]{.greek-omitted} [κοιλια]{.greek-omitted} [μου]{.greek-omitted}[10:10]{.aside}

### Chapter 21

[εχουσα]{.greek-omitted} [τειχος]{.greek-omitted} [μεγα]{.greek-omitted} [και]{.greek-omitted} [υψηλον]{.greek-omitted} [εχουσα]{.greek-omitted} [πυλωνας]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [πυλωσιν]{.greek-omitted} [αγγελους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [ονοματα]{.greek-omitted} [επιγεγραμμενα]{.greek-omitted} [α]{.greek-omitted} [εστιν]{.greek-omitted} [ονοματα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [φυλων]{.greek-omitted} [των]{.greek-omitted} [υιων]{.greek-omitted} [ιων]{.greek-added} [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο [ανατολων]{.greek-omitted} [ανατολης]{.greek-added} πυλωνες τρεις και απο βορρα πυλωνες τρεις και απο νοτου πυλωνες τρεις και απο δυσμων πυλωνες τρεις[21:13]{.aside}

και το τειχος της πολεως [εχον]{.greek-omitted} [εχων]{.greek-added} θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου ειχεν μετρον καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15]{.aside}

και η πολις [τετραγωνος]{.greek-omitted} [τετραγονος]{.greek-added} κειται και το μηκος αυτης οσον το πλατος και εμετρησεν την πολιν [εν]{.greek-added} τω καλαμω επι σταδιους δωδεκα χιλιαδων [δωδεκα]{.greek-omitted} το μηκος και το πλατος και το υψος αυτης ισα εστιν[21:16]{.aside}

και εμετρησεν το τειχος αυτης εκατον τεσσαρακοντα τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και [ην]{.greek-omitted} η ενδομησις του τειχους αυτης [ιασπις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [χρυσιον]{.greek-omitted} [καθαρον]{.greek-omitted} [ομοιον]{.greek-omitted} [υελω]{.greek-omitted} [καθαρω]{.greek-omitted}[21:18]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [ου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχει]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [λιου]{.greek-added} ουδε της σεληνης ινα [φαινωσιν]{.greek-omitted} [φενωσιν]{.greek-added} αυτη η γαρ δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και περιπατησουσιν τα εθνη δια του φωτος αυτης και οι βασιλεις της γης φερουσιν [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν [και]{.greek-omitted} [τιμην]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [εθνων]{.greek-omitted} εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και οισουσιν την δοξαν και την τιμην των εθνων εις αυτην[21:26]{.aside}

και ου μη εισελθη εις αυτην παν κοινον και ποιουν βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και εδειξεν μοι ποταμον [καθαρον]{.greek-omitted} υδατος ζωης λαμπρον ως κρυσταλλον εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου [εντευθεν]{.greek-omitted} [και]{.greek-omitted} [εκειθεν]{.greek-omitted} [ξυλον]{.greek-omitted} [ζωης]{.greek-omitted} [ποιουν]{.greek-omitted} [καρπους]{.greek-omitted} [δωδεκα]{.greek-omitted} [κατα]{.greek-omitted} [μηνα]{.greek-omitted} [εκαστον]{.greek-omitted} [αποδιδους]{.greek-omitted} [τον]{.greek-omitted} [καρπον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [εις]{.greek-omitted} [θεραπειαν]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted}[[22:2 *(lacunose)*]{.lacunose}]{.aside}

[εν]{.greek-omitted} [μεσω]{.greek-omitted} [της]{.greek-omitted} [πλατειας]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [ποταμου]{.greek-omitted} εντευθεν [και]{.greek-omitted} [εκειθεν]{.greek-omitted} [ξυλον]{.greek-omitted} [λον]{.greek-added} [ζ[―]{.gap}]{.greek-added} [ζωης]{.greek-omitted} [ποιουν]{.greek-omitted} [καρπους]{.greek-omitted} [δωδεκα]{.greek-omitted} [δεκα]{.greek-added} κατα [μηνα]{.greek-omitted} [μην[―]{.gap}]{.greek-added} [εκαστον]{.greek-omitted} [αποδιδους]{.greek-omitted} [αποδιδ[―]{.gap}]{.greek-added} [τον]{.greek-omitted} [καρπον]{.greek-omitted} [αυτου]{.greek-omitted} και τα φυλλα του ξυλου εις [θεραπειαν]{.greek-omitted} [θεραπιαν]{.greek-added} των εθνων[[22:2 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

και παν καταθεμα ουκ εσται ετι και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι δουλοι αυτου λατρευσουσιν αυτω[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των μετωπων αυτων[22:4]{.aside}

και νυξ ουκ εσται [εκει]{.greek-omitted} [ετι]{.greek-added} και χρειαν ουκ εχουσιν λυχνου και [φωτος]{.greek-omitted} [φως]{.greek-added} ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [φωτιει]{.greek-omitted} [φωτισει]{.greek-added} αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και [λεγει]{.greek-omitted} [ειπεν]{.greek-added} μοι ουτοι οι λογοι πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των πνευματων των προφητων απεστειλεν τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν [ταχει]{.greek-omitted}[22:6]{.aside}

