---
title: "Collation of Byz^RP^ vs 20024 (24)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 24 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20024).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 24                                   	| λογος                              	|
| 24 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 24 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 24               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 24                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 24 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 24                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

[ιωσιας]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} [τον]{.greek-omitted} [ιεχονιαν]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [αδελφους]{.greek-omitted} αυ[το]{.greek-supplied}υ [επι]{.greek-supplied} της μετοικεσιας βαβυλωνος[1:11]{.aside}

μετα δε την μετοικεσιαν βαβυλωνος ιεχονιας εγεννησεν τον σαλαθιηλ σαλαθιηλ δε εγεννησεν τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε εγεννησεν τον αβιουδ αβιουδ δε εγεννησεν τον ελιακειμ ελιακειμ δε εγεννησεν τον αζωρ[1:13]{.aside}

αζωρ δε εγεννησεν τον σαδωκ σ[αδωκ]{.greek-supplied} [δε]{.greek-supplied} [ε]{.greek-supplied}γεννησεν τον αχειμ αχειμ δε εγεννησεν τον ελιουδ[1:14]{.aside}

ελιουδ δε εγεννησεν τον ελεαζαρ ελεαζαρ δε εγεννησεν τον ματθαν ματθαν δε εγεννησεν τον ιακωβ[1:15]{.aside}

ιακωβ δε εγεννησεν τον ιωσηφ τον ανδρα μαριας εξ ης εγενν[η]{.greek-supplied}θη [ιησους]{.greek-abbr} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

πασαι ουν αι γ[ε]{.greek-supplied}νεαι απο [αβρααμ]{.greek-omitted} [αβρα]{.greek-added} [εως]{.greek-omitted} [δαυιδ]{.greek-omitted} [γενεαι]{.greek-omitted} [δεκατεσσαρες]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [δαυιδ]{.greek-omitted} [εως]{.greek-omitted} [της]{.greek-omitted} [μετοικεσιας]{.greek-omitted} [βαβυλωνος]{.greek-omitted} [γενεαι]{.greek-omitted} [δεκατεσσαρες]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μετοικεσιας]{.greek-omitted} [βαβυλωνος]{.greek-omitted} [εως]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [γενεαι]{.greek-omitted} [δεκατεσσαρες]{.greek-omitted}[1:17]{.aside}

[[αμ]{.greek-supplied}]{.greek-added} [πασαι]{.greek-omitted} [ουν]{.greek-omitted} [αι]{.greek-omitted} [γενεαι]{.greek-omitted} [απο]{.greek-omitted} [αβρααμ]{.greek-omitted} [εως]{.greek-supplied} [δαυιδ]{.greek-omitted} [[δαδ]{.greek-supplied}]{.greek-added} γενεαι δεκατεσσαρες και απο [δαυιδ]{.greek-abbr} εως της μετοικεσιας βαβυλωνος γενεαι δεκατεσσαρες και απο της μετοικεσιας βαβυλωνος εως του [χριστου]{.greek-abbr} γενεαι δεκατεσσαρες[1:17 | instance no. 2]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η [γεννησις]{.greek-omitted} [γενεσις]{.greek-added} ουτως ην [μνηστευθεισης]{.greek-omitted} [μνηστευθισης]{.greek-added} γαρ της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν η συνελθειν αυτους ευρεθη εν γαστρι [ε]{.greek-supplied}χ[ουσα]{.greek-supplied} [εκ]{.greek-supplied} [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην [παραδειγματισαι]{.greek-omitted} [παραδιγματισαι]{.greek-added} εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ εφανη αυτω λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη φοβηθης παραλαβειν μαριαμ την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

τεξεται δε [υιον]{.greek-abbr} [και]{.greek-omitted} [καλεσεις]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [ιησουν]{.greek-omitted} [αυτος]{.greek-omitted} [γαρ]{.greek-omitted} [σωσει]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [αυτου]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [αμαρτιων]{.greek-omitted} [αυτων]{.greek-omitted}[1:21]{.aside}

### Chapter 3

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον ιωαννην του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε ιωαννης διεκωλυεν αυτον λεγων εγω [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν προς αυτον αφες αρτι ουτως γαρ πρεπον εστιν ημιν πληρωσαι πασαν δικαιοσυνην τοτε αφιησ[ιν]{.greek-supplied} αυτον[3:15]{.aside}

και βαπτισθεις ο [ιησους]{.greek-abbr} ανεβη ευθυς απο του υδατο[ς]{.greek-supplied} και ιδου [ανεωχθησαν]{.greek-omitted} [ηνεωχθησαν]{.greek-added} αυτω οι ουρανοι και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} καταβαινον ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των ουρανων λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[3:17]{.aside}

### Chapter 4

τοτε ο [ιησους]{.greek-abbr} ανηχθη εις την ερημον υπο του [πνευματος]{.greek-omitted} [πειρασθηναι]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [διαβολου]{.greek-omitted}[4:1]{.aside}

[τοτε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ανηχθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ερημον]{.greek-omitted} [υπο]{.greek-omitted} [τ]{.greek-supplied}ου [πνευματος]{.greek-abbr} πειρασθηναι υπο του διαβολου[4:1 | instance no. 2]{.aside}

και νηστευσας ημερας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} και νυκτας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} υστερον [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added}[4:2]{.aside}

και προσελθων αυτω ο πειραζων ειπεν ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι γενωνται[4:3]{.aside}

ο δε αποκριθεις ειπεν γεγραπται ουκ επ αρτω μονω ζησεται [ο]{.greek-added} [ανθρωπος]{.greek-abbr} αλλ επι παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει [υιος]{.greek-abbr} ει του θεου βαλε σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων αρουσιν σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} παλιν γεγραπται ουκ εκπειρασεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν παραλαμβανει αυτον ο διαβολος εις ορος υψηλον [λιαν]{.greek-omitted} [λειαν]{.greek-added} και [δεικνυσιν]{.greek-omitted} [δικνυσιν]{.greek-added} αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε [οπισω]{.greek-omitted} [μου]{.greek-omitted} σατανα γεγραπται γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου [προσκυνησεις]{.greek-omitted} [προσκυνησης]{.greek-added} και αυτω μονω λατρευσεις[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} οτι ιωαννης παρεδοθη ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την [ναζαρετ]{.greek-omitted} [ναζαραθ]{.greek-added} ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν [εν]{.greek-omitted} [οριοις]{.greek-omitted} [ζαβουλων]{.greek-omitted} [και]{.greek-omitted} [νεφθαλειμ]{.greek-omitted}[4:13]{.aside}

[και]{.greek-omitted} [καταλιπων]{.greek-omitted} [την]{.greek-omitted} [ναζαρετ]{.greek-omitted} [ελθων]{.greek-omitted} [κατωκησεν]{.greek-omitted} [εις]{.greek-omitted} [καπερναουμ]{.greek-omitted} [την]{.greek-omitted} [παραθαλασσιαν]{.greek-omitted} εν οριοις ζαβουλων και νεφθαλειμ[4:13 | instance no. 2]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη νεφθαλειμ οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} φως μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε ηγγικεν γαρ η βασιλεια των ουρανων[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} δυο αδελφους σιμωνα τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω [υμας]{.greek-omitted} [αλιεις]{.greek-omitted} [ανθρωπων]{.greek-omitted}[4:19]{.aside}

### Chapter 10

[πορευομενοι]{.greek-omitted} [δε]{.greek-omitted} [κηρυσσετε]{.greek-omitted} [λεγοντες]{.greek-omitted} οτι ηγγικεν η βασιλεια των ουρανων[10:7]{.aside}

ασθενουντας [θεραπευετε]{.greek-omitted} [θεραπευεται]{.greek-added} λεπρους [καθαριζετε]{.greek-omitted} [καθαριζεται]{.greek-added} δαιμονια [εκβαλλετε]{.greek-omitted} [εκβαλλεται]{.greek-added} [νεκρους]{.greek-added} [εγειρεται]{.greek-added} δωρεαν ελαβετε δωρεαν δοτε[10:8]{.aside}

μη κτησησθε χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε ραβδους αξιος γαρ ο εργατης της τροφης αυτου εστιν[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις εν αυτη αξιος εστιν κακει μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν [ασπασασθε]{.greek-omitted} [ασπασασθαι]{.greek-added} αυτην[10:12]{.aside}

και εαν μεν η η οικια αξια ελθετω η ειρηνη υμων επ αυτην εαν δε μη η αξια η ειρηνη υμων προς υμας [επιστραφητω]{.greek-omitted} [επι]{.greek-added}[10:13]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [μεν]{.greek-omitted} [η]{.greek-omitted} [η]{.greek-omitted} [οικια]{.greek-omitted} [αξια]{.greek-omitted} [ελθετω]{.greek-omitted} [η]{.greek-omitted} [ειρηνη]{.greek-omitted} [υμων]{.greek-omitted} [επ]{.greek-omitted} [αυτην]{.greek-omitted} [εαν]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [η]{.greek-omitted} [αξια]{.greek-omitted} [η]{.greek-omitted} [ειρηνη]{.greek-omitted} [υμων]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [επιστραφητω]{.greek-omitted} [στραφητω]{.greek-added}[10:13 | instance no. 2]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της οικιας η της πολεως εκεινης εκτιναξατε τον κονιορτον των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν ανεκτοτερον εσται γη σοδομων και [γομορρων]{.greek-omitted} [γομορρας]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ουν φρονιμοι ως οι οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} παραδωσουσιν γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις [αχθησεσθε]{.greek-omitted} [αχθησεσθαι]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε [παρα]{.greek-added} [παραδιδωσιν]{.greek-omitted} [υμας]{.greek-omitted} [μη]{.greek-omitted} [μεριμνησητε]{.greek-omitted} [πως]{.greek-omitted} [η]{.greek-omitted} [τι]{.greek-omitted} [λαλησητε]{.greek-omitted} [δοθησεται]{.greek-omitted} [γαρ]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [τι]{.greek-omitted} [λαλησετε]{.greek-omitted}[10:19]{.aside}

και ος εαν ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε ιωαννης ακουσας εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-abbr} πεμψας [δυο]{.greek-omitted} [δια]{.greek-added} των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι αναβλεπουσιν και χωλοι περιπατουσιν λεπροι καθαριζονται και κωφοι ακουουσιν [νεκροι]{.greek-omitted} [εγειρονται]{.greek-omitted} [και]{.greek-omitted} [πτωχοι]{.greek-omitted} [ευαγγελιζονται]{.greek-omitted}[11:5]{.aside}

[τυφλοι]{.greek-omitted} [αναβλεπουσιν]{.greek-omitted} και [χωλοι]{.greek-omitted} [περιπατουσιν]{.greek-omitted} [λεπροι]{.greek-omitted} [καθαριζονται]{.greek-omitted} [και]{.greek-omitted} [κωφοι]{.greek-omitted} [ακουουσιν]{.greek-omitted} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5 | instance no. 2]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωαννου τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις [ιματιοις]{.greek-omitted} [ειματιοις]{.greek-added} ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ εστιν περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου [ος]{.greek-omitted} [και]{.greek-added} κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ουκ]{.greek-omitted} [εγηγερται]{.greek-omitted} [εν]{.greek-omitted} [γεννητοις]{.greek-omitted} [γυναικων]{.greek-omitted} [μειζων]{.greek-omitted} [ιωαννου]{.greek-omitted} [του]{.greek-omitted} [βαπτιστου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [μικροτερος]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [μειζων]{.greek-omitted} [αυτου]{.greek-omitted} [εστιν]{.greek-omitted}[11:11]{.aside}

### Chapter 13

[ωσπερ]{.greek-omitted} [ουν]{.greek-omitted} [συλλεγεται]{.greek-omitted} [τα]{.greek-omitted} [ζιζανια]{.greek-omitted} [και]{.greek-omitted} [πυρι]{.greek-omitted} [καιεται]{.greek-omitted} [ουτως]{.greek-omitted} [εσται]{.greek-omitted} εν τη συντελεια του αιωνος τουτου[13:40]{.aside}

αποστελει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια εστιν η βασιλεια των ουρανων θησαυρω κεκρυμμενω εν τω αγρω ον ευρων [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας αυτου υπαγει και παντα οσα εχει πωλει και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των ουρανων [ανθρωπω]{.greek-omitted} [εμπορω]{.greek-omitted} [ζητουντι]{.greek-omitted} [καλους]{.greek-omitted} [μαργαριτας]{.greek-omitted}[13:45]{.aside}

[παλιν]{.greek-omitted} [ομοια]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45 | instance no. 2]{.aside}

ος ευρων ενα πολυτιμον μαργαριτην απελθων πεπρακεν παντα οσα ειχεν και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των ουρανων σαγηνη [βληθειση]{.greek-omitted} [βληθηση]{.greek-added} εις την θαλασσαν και εκ παντος γενους συναγαγουση[13:47]{.aside}

ην οτε επληρωθη αναβιβασαντες [αυτην]{.greek-added} επι τον αιγιαλον και καθισαντες συνελεξαν τα καλα εις [αγγεια]{.greek-omitted} [αγγια]{.greek-added} τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται εν τη συντελεια του αιωνος εξελευσονται οι αγγελοι και αφοριουσιν τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:50]{.aside}

### Chapter 14

[οψιας]{.greek-omitted} [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [προσηλθον]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [λεγοντες]{.greek-omitted} [ερημος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [τοπος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted} [ηδη]{.greek-omitted} [παρηλθεν]{.greek-omitted} [απολυσον]{.greek-omitted} [τους]{.greek-omitted} [οχλους]{.greek-omitted} [ινα]{.greek-omitted} [απελθοντες]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [κωμας]{.greek-omitted} αγορασωσιν εαυτοις βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε ειπεν [αυτοις]{.greek-added} φερετε μοι αυτους ωδε[14:18]{.aside}

και κελευσας τους οχλους ανακλιθηναι επι τους χορτους λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον ουρανον [ευλογησεν]{.greek-omitted} [ηυλογησεν]{.greek-added} και κλασας εδωκεν τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες ωσει πεντακισχιλιοι χωρις [γυναικων]{.greek-omitted} [και]{.greek-omitted} [παιδιων]{.greek-omitted}[14:21]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [εσθιοντες]{.greek-omitted} [ησαν]{.greek-omitted} [ανδρες]{.greek-omitted} [ωσει]{.greek-omitted} [πεντακισχιλιοι]{.greek-omitted} [χωρις]{.greek-omitted} γυναικων και παιδιων[14:21 | instance no. 2]{.aside}

και ευθεως ηναγκασεν [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας [αυτου]{.greek-added} εμβηναι εις το πλοιον και προαγειν αυτον εις το περαν εως ου απολυση τους οχλους[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος κατ ιδιαν προσευξασθαι οψιας δε γενομενης μονος ην εκει[14:23]{.aside}

το δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος απηλθεν [προς]{.greek-omitted} [πρ]{.greek-added} αυτους [ο]{.greek-omitted} [ιησους]{.greek-omitted} περιπατων επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασσαν]{.greek-added}[14:25]{.aside}

και [ιδοντες]{.greek-omitted} [ειδοντες]{.greek-added} αυτον οι μαθηται επι την θαλασσαν περιπατουντα εταραχθησαν λεγοντες οτι φαντασμα εστιν και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε [ελα]{.greek-added} [ελαλησεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγων]{.greek-omitted} [θαρσειτε]{.greek-omitted} [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [μη]{.greek-omitted} [φοβεισθε]{.greek-omitted}[14:27]{.aside}

[ευθεως]{.greek-omitted} [δε]{.greek-omitted} [ελαλησεν]{.greek-omitted} [λησεν]{.greek-added} αυτοις ο [ιησους]{.greek-abbr} λεγων θαρσειτε εγω ειμι μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[14:27 | instance no. 2]{.aside}

αποκριθεις δε αυτω ο πετρος ειπεν [κυριε]{.greek-abbr} ει συ ει κελευσον με προς σε ελθειν επι τα υδατα[14:28]{.aside}

ο δε ειπεν ελθε και καταβας απο του πλοιου ο πετρος περιεπατησεν επι τα υδατα ελθειν προς τον [ιησουν]{.greek-abbr}[14:29]{.aside}

βλεπων δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι εκραξεν λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα επελαβετο αυτου και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω ελθοντες προσεκυνησαν αυτω λεγοντες αληθως [θεου]{.greek-abbr} [υιος]{.greek-abbr} ει[14:33]{.aside}

και διαπερασαντες ηλθον εις την γην [γεννησαρετ]{.greek-omitted} [γεννησαρεθ]{.greek-added}[14:34]{.aside}

και επιγνοντες αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον αψωνται του κρασπεδου του [ιματιου]{.greek-omitted} [ειματιου]{.greek-added} αυτου και οσοι ηψαντο διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτε προσερχονται τω [ιησου]{.greek-abbr} οι απο ιεροσολυμων γραμματεις και φαρισαιοι λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου παραβαινουσιν την παραδοσιν των πρεσβυτερων ου γαρ νιπτονται τας χειρας αυτων οταν αρτον εσθιωσιν[15:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και υμεις [παραβαινετε]{.greek-omitted} [παραβενεται]{.greek-added} την [εν]{.greek-added} [εντολην]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [παραδοσιν]{.greek-omitted} [υμων]{.greek-omitted}[15:3]{.aside}

[και]{.greek-omitted} μεταβας εκειθεν ο [ιησους]{.greek-abbr} ηλθεν παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος εκαθητο εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ εαυτων χωλους τυφλους κωφους κυλλους και ετερους πολλους και ερριψαν αυτους παρα τους ποδας του [ιησου]{.greek-abbr} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους λαλουντας κυλλους [υγιεις]{.greek-omitted} [υγιης]{.greek-added} [και]{.greek-added} χωλους περιπατουντας και τυφλους βλεποντας και εδοξασαν τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου ειπεν σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις προσμενουσιν μοι και ουκ εχουσιν τι φαγωσιν και απολυσαι αυτους [νηστεις]{.greek-omitted} [ου]{.greek-omitted} [θελω]{.greek-omitted} [μηποτε]{.greek-omitted} [εκλυθωσιν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted}[15:32]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [σπλαγχνιζομαι]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [οτι]{.greek-omitted} [ηδη]{.greek-omitted} [ημεραι]{.greek-omitted} [τρεις]{.greek-omitted} [προσμενουσιν]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted} [και]{.greek-omitted} [απολυσαι]{.greek-omitted} [αυτους]{.greek-omitted} νηστεις ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32 | instance no. 2]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια αρτοι τοσουτοι ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και εκελευσεν τοις οχλοις αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας εκλασεν και εδωκεν τοις μαθηταις αυτου οι δε μαθηται τω οχλω[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας [πληρεις]{.greek-omitted} [πληρης]{.greek-added}[15:37]{.aside}

οι δε εσθιοντες ησαν τετρακισχιλιοι ανδρες χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας [τους]{.greek-omitted} [οχλους]{.greek-omitted} [ενεβη]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [και]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορια]{.greek-omitted} [μαγδαλα]{.greek-omitted}[15:39]{.aside}

## The Gospel of John

### Chapter 1

[τη]{.greek-omitted} [επαυριον]{.greek-omitted} [βλεπει]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} ερχομενον προς αυτον και λεγει ιδε ο αμνος του [θεου]{.greek-abbr} ο αιρων την αμαρτιαν του κοσμου[[1:29 *(lacunose)*]{.lacunose}]{.aside}

ουτος εστιν περι ου εγω ειπον οπισω μου ερχεται ανηρ ος εμπροσθεν μου γεγονεν οτι πρωτος μου ην[1:30]{.aside}

καγω ουκ ηδειν αυτον αλλ ινα φανερωθη τω [ισραηλ]{.greek-abbr} δια τουτο ηλθον εγω εν [τω]{.greek-omitted} υδατι βαπτιζων[1:31]{.aside}

και εμαρτυρησεν ιωαννης λεγων οτι τεθεαμαι το [πνευμα]{.greek-abbr} καταβαινον ωσει περιστεραν εξ ουρανου και εμεινεν επ αυτον[1:32]{.aside}

καγω ουκ ηδειν αυτον αλλ ο πεμψας με βαπτιζειν εν υδατι εκεινος μοι ειπεν εφ ον αν ιδης το [πνευμα]{.greek-abbr} καταβαινον και μενον επ αυτον ουτος εστιν ο βαπτιζων εν [πνευματι]{.greek-abbr} αγιω[1:33]{.aside}

καγω [εωρακα]{.greek-omitted} [εορακα]{.greek-added} και μεμαρτυρηκα οτι ουτος [εστιν]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[1:34]{.aside}

τη επαυριον παλιν [ειστηκει]{.greek-omitted} [ιστηκει]{.greek-added} ο ιωαννης και εκ των μαθητων αυτου δυο[1:35]{.aside}

και εμβλεψας τω [ιησου]{.greek-abbr} περιπατουντι λεγει [ιδε]{.greek-omitted} [ειδε]{.greek-added} ο αμνος του [θεου]{.greek-abbr}[1:36]{.aside}

και ηκουσαν αυτου οι δυο μαθηται λαλουντος και ηκολουθησαν τω [ιησου]{.greek-abbr}[1:37]{.aside}

στραφεις δε ο [ιησους]{.greek-abbr} και θεασαμενος αυτους ακολουθουντας λεγει αυτοις τι ζητειτε οι δε ειπον αυτω [ραββι]{.greek-omitted} [ραββει]{.greek-added} ο [λεγεται]{.greek-omitted} [λεγετε]{.greek-added} ερμηνευομενον διδασκαλε που μενεις[1:38]{.aside}

λεγει αυτοις [ερχεσθε]{.greek-omitted} [ερχεσθαι]{.greek-added} και [ιδετε]{.greek-omitted} [ειδετε]{.greek-added} ηλθον και ειδον που μενει και παρ αυτω [εμειναν]{.greek-omitted} [εμεινον]{.greek-added} την ημεραν εκεινην ωρα ην ως δεκατη[1:39]{.aside}

ην ανδρεας ο αδελφος σιμωνος πετρου εις εκ των δυο των ακουσαντων παρα ιωαννου και ακολουθησαντων αυτω[1:40]{.aside}

### Chapter 2

και εγγυς ην το πασχα των ιουδαιων και ανεβη εις ιεροσολυμα ο [ιησους]{.greek-abbr}[2:13]{.aside}

και ευρεν εν τω ιερω τους πωλουντας βοας και προβατα και περιστερας και τους κερματιστας καθημενους[2:14]{.aside}

και ποιησας φραγελλιον εκ σχοινιων παντας εξεβαλεν εκ του ιερου τα τε προβατα και τους βοας και των κολλυβιστων εξεχεεν το κερμα και τας τραπεζας ανεστρεψεν[2:15]{.aside}

και τοις τας περιστερας πωλουσιν ειπεν αρατε ταυτα εντευθεν μη ποιειτε τον οικον του [πατρος]{.greek-abbr} μου οικον εμποριου[2:16]{.aside}

εμνησθησαν δε οι μαθηται αυτου οτι γεγραμμενον εστιν ο ζηλος του οικου σου καταφαγεται με[2:17]{.aside}

απεκριθησαν ουν οι ιουδαιοι και ειπον αυτω τι σημειον [δεικνυεις]{.greek-omitted} [ημιν]{.greek-omitted} [οτι]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιεις]{.greek-omitted}[2:18]{.aside}

απεκριθη [ιησους]{.greek-abbr} και ειπεν αυτοις λυσατε τον ναον τουτον και εν τρισιν ημεραις εγερω αυτον[2:19]{.aside}

ειπον ουν οι ιουδαιοι [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} και εξ ετεσιν ωκοδομηθη ο ναος ουτος και συ εν τρισιν ημεραις εγερεις αυτον[2:20]{.aside}

εκεινος δε ελεγεν περι του ναου του σωματος αυτου[2:21]{.aside}

οτε ουν ηγερθη εκ νεκρων εμνησθησαν οι μαθηται αυτου οτι τουτο ελεγεν και επιστευσαν τη γραφη και τω λογω ω ειπεν ο [ιησους]{.greek-abbr}[2:22]{.aside}

ως δε ην εν τοις ιεροσολυμοις εν τω πασχα εν τη εορτη πολλοι επιστευσαν εις το ονομα αυτου θεωρουντες αυτου τα σημεια α εποιει[2:23]{.aside}

αυτος δε ο [ιησους]{.greek-abbr} ουκ επιστευεν εαυτον αυτοις δια το αυτον [γινωσκειν]{.greek-omitted} [γινωσκιν]{.greek-added} παντας[2:24]{.aside}

και [οτι]{.greek-omitted} [ου]{.greek-omitted} [χρειαν]{.greek-omitted} [ειχεν]{.greek-omitted} [ινα]{.greek-omitted} [τις]{.greek-omitted} [μαρτυρηση]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [αυτος]{.greek-omitted} [γαρ]{.greek-omitted} [εγινωσκεν]{.greek-omitted} [τι]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted}[[2:25 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 21

[μετα]{.greek-omitted} [ταυτα]{.greek-omitted} [εφανερωσεν]{.greek-omitted} [εαυτον]{.greek-omitted} [παλιν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [της]{.greek-omitted} [τιβεριαδος]{.greek-omitted} εφανερωσεν δε ουτως[[21:1 *(lacunose)*]{.lacunose}]{.aside}

ησαν ομου σιμων πετρος και θωμας ο λεγομενος διδυμος και ναθαναηλ ο απο κανα της γαλιλαιας και οι του ζεβεδαιου και αλλοι εκ των μαθητων αυτου δυο[21:2]{.aside}

λεγει αυτοις σιμων πετρος υπαγω αλιευειν λεγουσιν αυτω ερχομεθα και ημεις συν σοι [και]{.greek-added} [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} και ενεβησαν εις το πλοιον ευθυς και εν εκεινη τη νυκτι επιασαν ουδεν[21:3]{.aside}

πρωιας δε ηδη γενομενης εστη [ο]{.greek-omitted} [ιησους]{.greek-abbr} εις τον αιγιαλον ου μεντοι ηδεισαν οι μαθηται οτι [ιησους]{.greek-abbr} εστιν[21:4]{.aside}

λεγει ουν αυτοις ο [ιησους]{.greek-abbr} παιδια μη τι προσφαγιον εχετε απεκριθησαν αυτω ου[21:5]{.aside}

ο δε ειπεν αυτοις βαλετε εις τα δεξια μερη του πλοιου το δικτυον και [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} εβαλον ουν [και]{.greek-omitted} [ουκετι]{.greek-omitted} [αυτο]{.greek-omitted} [ελκυσαι]{.greek-omitted} [ισχυσαν]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [πληθους]{.greek-omitted} [των]{.greek-omitted} [ιχθυων]{.greek-omitted}[21:6]{.aside}

λεγει ουν ο μαθητης εκεινος ον ηγαπα ο [ιησους]{.greek-abbr} τω πετρω ο [κυριος]{.greek-abbr} εστιν σιμων ουν πετρος ακουσας οτι ο [κυριος]{.greek-abbr} εστιν τον επενδυτην διεζωσατο ην γαρ γυμνος και εβαλεν εαυτον εις την θαλασσαν[21:7]{.aside}

οι δε αλλοι μαθηται τω [πλοιαριω]{.greek-omitted} [πλοιω]{.greek-added} ηλθον ου γαρ ησαν μακραν απο της γης αλλ ως απο πηχων διακοσιων συροντες το δικτυον των ιχθυων[21:8]{.aside}

ως ουν απεβησαν εις την γην [βλεπουσιν]{.greek-omitted} [ειδαν]{.greek-added} ανθρακιαν κειμενην και οψαριον επικειμενον και αρτον[21:9]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ενεγκατε απο των οψαριων ων επιασατε νυν[21:10]{.aside}

ανεβη σιμων πετρος και ειλκυσεν το δικτυον [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [εις]{.greek-added} [την]{.greek-added} [γην]{.greek-added} μεστον [ιχθυων]{.greek-omitted} [μεγαλων]{.greek-omitted} [εκατον]{.greek-omitted} [πεντηκοντα]{.greek-omitted} [τριων]{.greek-omitted} [και]{.greek-omitted} [τοσουτων]{.greek-omitted} [οντων]{.greek-omitted} [ουκ]{.greek-omitted} [εσχισθη]{.greek-omitted} [το]{.greek-omitted} [δικτυον]{.greek-omitted}[[21:11 *(lacunose)*]{.lacunose}]{.aside}

