---
title: "Collation of Byz^RP^ vs 20050 (50)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 50 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20050).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 50                                   	| λογος                              	|
| 50 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 50 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 50               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 50                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 50 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 50                                                     	| [―]{.gap}                        	|
:::

## The Gospel of John

### Chapter 1

[εν]{.greek-omitted} [Εν]{.greek-added} [αρχη]{.greek-added} [ην]{.greek-added} [ο]{.greek-added} [λογος]{.greek-added} [Εν]{.greek-added} [αρχη]{.greek-added} [ην]{.greek-added} [ο]{.greek-added} [λογος]{.greek-added} [Εν]{.greek-added} [αρχη]{.greek-added} [ην]{.greek-added} [ο]{.greek-added} [λογος]{.greek-added} [Εν]{.greek-added} [αρχη]{.greek-added} [ην]{.greek-added} [ο]{.greek-added} [λογος]{.greek-added} [Εν]{.greek-added} αρχη ην ο λογος και ο λογος ην προς τον [θεον]{.greek-abbr} [και]{.greek-omitted} [θεος]{.greek-omitted} [ην]{.greek-omitted} [ο]{.greek-omitted} [λογος]{.greek-omitted}[[1:1 *(lacunose)*]{.lacunose}]{.aside}

[παντα]{.greek-omitted} [δι]{.greek-omitted} [αυτου]{.greek-omitted} [εγενετο]{.greek-omitted} και χωρις αυτου εγενετο ουδε εν ο γεγονεν[[1:3 *(lacunose)*]{.lacunose}]{.aside}

[εν]{.greek-omitted} [Εν]{.greek-added} αυτω ζωη ην [και]{.greek-omitted} [η]{.greek-omitted} [Εν]{.greek-added} [αυτω]{.greek-added} ζωη ην [το]{.greek-omitted} [φως]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted}[[1:4 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 2

[εμνησθησαν]{.greek-omitted} [Εμνησθησαν]{.greek-added} δε οι μαθηται αυτου οτι γεγραμμενον εστιν [οτι]{.greek-added} ο ζηλος του οικου σου καταφαγεται με[2:17]{.aside}

[απεκριθησαν]{.greek-omitted} [Απεκριθησαν]{.greek-added} ουν οι ιουδαιοι και ειπον αυτω τι σημειον δεικνυεις ημιν οτι ταυτα ποιεις[2:18]{.aside}

[απεκριθη]{.greek-omitted} [Απεκριθη]{.greek-added} [ιησους]{.greek-abbr} και ειπεν αυτοις λυσατε τον ναον τουτον και εν τρισιν ημεραις εγερω αυτον[2:19]{.aside}

[ειπον]{.greek-omitted} [Ειπον]{.greek-added} ουν οι ιουδαιοι τεσσαρακοντα και εξ ετεσιν [ωκοδομηθη]{.greek-omitted} [οικοδομηθη]{.greek-added} ο ναος ουτος και συ εν τρισιν ημεραις εγερεις αυτον[2:20]{.aside}

[εκεινος]{.greek-omitted} [Εκεινος]{.greek-added} δε ελεγεν περι του ναου του σωματος αυτου[2:21]{.aside}

[οτε]{.greek-omitted} [Οτε]{.greek-added} ουν ηγερθη εκ νεκρων εμνησθησαν οι μαθηται αυτου οτι τουτο ελεγεν και επιστευσαν τη γραφη και τω λογω [ω]{.greek-omitted} [ον]{.greek-added} ειπεν ο [ιησους]{.greek-abbr}[2:22]{.aside}

[ως]{.greek-omitted} [Ως]{.greek-added} δε ην εν τοις ιεροσολυμοις εν τω πασχα εν τη εορτη πολλοι επιστευσαν εις το ονομα αυτου θεωρουντες αυτου τα σημεια α εποιει[2:23]{.aside}

[αυτος]{.greek-omitted} [Αυτος]{.greek-added} δε [ο]{.greek-omitted} [ιησους]{.greek-abbr} ουκ [επιστευεν]{.greek-omitted} [επιστευσεν]{.greek-added} εαυτον αυτοις δια το αυτον γινωσκειν παντας[2:24]{.aside}

και οτι ου χρειαν ειχεν ινα τις μαρτυρηση περι του [ανθρωπου]{.greek-abbr} αυτος γαρ [εγινωσκεν]{.greek-omitted} [εγινωσκε¯]{.greek-added} τι ην εν τω [ανθρωπω]{.greek-abbr}[2:25]{.aside}

### Chapter 3

[ην]{.greek-omitted} [Ην]{.greek-added} δε [ανθρωπος]{.greek-abbr} εκ των φαρισαιων νικοδημος ονομα αυτω [αρχων]{.greek-omitted} [αρχω¯]{.greek-added} των ιουδαιων[3:1]{.aside}

ουτος ηλθεν προς αυτον νυκτος και ειπεν αυτω ραββι οιδαμεν οτι απο [θεου]{.greek-abbr} εληλυθας διδασκαλος ουδεις γαρ [δυναται]{.greek-added} ταυτα τα σημεια [δυναται]{.greek-omitted} ποιειν α συ ποιεις εαν μη η ο [θεος]{.greek-abbr} μετ αυτου[3:2]{.aside}

[απεκριθη]{.greek-omitted} [Απεκριθη]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-abbr} και ειπεν αυτω αμην αμην λεγω σοι εαν μη τις γεννηθη ανωθεν ου δυναται ιδειν την βασιλειαν του [θεου]{.greek-abbr} [Απεκριθη]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [και]{.greek-added} [ειπεν]{.greek-added} [αυτω]{.greek-added} [αμην]{.greek-added} [αμην]{.greek-added} [λεγω]{.greek-added} [σοι]{.greek-added} [εαν]{.greek-added} [μη]{.greek-added} [τις]{.greek-added} [γεννηθη]{.greek-added} [ανωθεν]{.greek-added} [ου]{.greek-added} [δυναται]{.greek-added} [ιδειν]{.greek-added} [τη¯]{.greek-added} [βασιλειαν]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added}[3:3]{.aside}

[λεγει]{.greek-omitted} [Λεγει]{.greek-added} προς αυτον [ο]{.greek-omitted} νικοδημος πως δυναται [ανθρωπος]{.greek-abbr} γεννηθηναι [γερων]{.greek-omitted} [γερω¯]{.greek-added} ων μη δυναται εις την κοιλιαν της [μητρος]{.greek-abbr} αυτου δευτερον εισελθειν και γεννηθηναι[3:4]{.aside}

[απεκριθη]{.greek-omitted} [Απεκριθη]{.greek-added} [ιησους]{.greek-abbr} [και]{.greek-added} [ειπεν]{.greek-added} αμην αμην λεγω σοι εαν μη τις γεννηθη εξ υδατος και [πνευματος]{.greek-abbr} ου δυναται εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} [Απεκριθη]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [και]{.greek-added} [ειπεν]{.greek-added} [αμην]{.greek-added} [αμην]{.greek-added} [λεγω]{.greek-added} [σοι]{.greek-added} [εαν]{.greek-added} [μη]{.greek-added} [τις]{.greek-added} [γεννηθη]{.greek-added} [εξ]{.greek-added} [υδατος]{.greek-added} [και]{.greek-added} [[πνευματος]{.greek-abbr}]{.greek-added} [ου]{.greek-added} [δυναται]{.greek-added} [εισελθειν]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [Απεκριθη]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [και]{.greek-added} [ειπεν]{.greek-added} [αμην]{.greek-added} [αμην]{.greek-added} [λεγω]{.greek-added} [σοι]{.greek-added} [εαν]{.greek-added} [μη]{.greek-added} [τις]{.greek-added} [γεννηθη]{.greek-added} [εξ]{.greek-added} [υδατος]{.greek-added} [και]{.greek-added} [[πνευματος]{.greek-abbr}]{.greek-added} [ου]{.greek-added} [δυναται]{.greek-added} [εισελθειν]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added}[3:5]{.aside}

[το]{.greek-omitted} [Το]{.greek-added} γεγεννημενον εκ της σαρκος σαρξ εστιν [και]{.greek-omitted} [Και]{.greek-added} το γεγεννημενον εκ του [πνευματος]{.greek-abbr} [πνευμα]{.greek-abbr} εστιν[3:6]{.aside}

[μη]{.greek-omitted} [Μη]{.greek-added} θαυμασης οτι ειπον σοι δει υμας γεννηθηναι [ανωθεν]{.greek-omitted} [ανωθε¯]{.greek-added}[3:7]{.aside}

[το]{.greek-omitted} [Το]{.greek-added} [πνευμα]{.greek-abbr} οπου θελει πνει και την φωνην α[υ]{.greek-supplied}του ακουεις αλλ ουκ οιδας ποθεν ερχεται και που υπαγει ου[τ]{.greek-supplied}ως εστιν πας ο γεγεννημενος εκ του [πνευματος]{.greek-abbr}[3:8]{.aside}

[ει]{.greek-omitted} [Ει]{.greek-added} τα επιγεια ειπον [υμιν]{.greek-omitted} [υμι¯]{.greek-added} και ου πιστευετε πως εαν ειπω υμιν τα επουρανια [πιστευσετε]{.greek-omitted} [πιστευετε]{.greek-added}[3:12]{.aside}

[και]{.greek-omitted} [Και]{.greek-added} ουδεις αναβεβηκεν εις τον [ουρανον]{.greek-abbr} ει μη ο εκ του [ουρανου]{.greek-abbr} καταβας ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ο ων εν τω [ουρανω]{.greek-abbr}[3:13]{.aside}

πας γαρ ο [τα]{.greek-added} φαυλα πρασσων μισει το φως και ουκ ερχεται προς το φως ινα μη ελεγχθη τα εργα αυτου[3:20]{.aside}

ο δε ποιων την αληθειαν ερχεται προς το φως ινα φανερωθη αυτου τα εργα οτι εν [θεω]{.greek-abbr} εστιν ειργασμενα[3:21]{.aside}

μετα ταυτα ηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις την ιουδαιαν γην και εκει διετριβεν μετ αυτων και εβαπτιζεν[3:22]{.aside}

### Chapter 4

ερχεται γυνη εκ της σαμ[α]{.unclear}ρειας αντλησ[αι]{.unclear} υδωρ λεγει αυτη [ο]{.unclear} [ιησους]{.greek-abbr} δος μοι π[ιε]{.unclear}ιν[4:7]{.aside}

ο[ι]{.unclear} [γ]{.greek-supplied}αρ μαθ[η]{.unclear}[τα]{.greek-supplied}[ι]{.unclear} [α]{.unclear}υτου [απεληλυθεισαν]{.greek-omitted} [απηλθ[ο]{.unclear}¯]{.greek-added} εις την π[ολ]{.greek-supplied}[ι]{.unclear}ν [ι]{.greek-supplied}να τροφας [αγορασωσιν]{.greek-omitted} [α[γ]{.unclear}[ορα]{.greek-supplied}[σωσ]{.unclear}ι¯]{.greek-added}[4:8]{.aside}

λεγει ουν αυτω [η]{.unclear} [γ]{.unclear}υνη η [σαμαρειτις]{.greek-omitted} [σαμαριτις]{.greek-added} πως συ ιουδαιος [ων]{.greek-omitted} [ω¯]{.greek-added} παρ εμου πιειν αιτεις [γυναικος]{.greek-added} [σαμαριτιδος]{.greek-added} ουσης [γυναικος]{.greek-omitted} [σαμαρειτιδος]{.greek-omitted} ου γαρ συγχρωνται ιουδαιοι [σαμαρειταις]{.greek-omitted} [σαμαριταις]{.greek-added}[4:9]{.aside}

[απεκριθη]{.greek-omitted} [Απεκριθη]{.greek-added} [ιησους]{.greek-abbr} και ειπεν αυτη ει [ηδεις]{.greek-omitted} [ειδης]{.greek-added} την δωρεαν του [θεου]{.greek-abbr} και τις εστιν ο λεγων σοι δος μοι πιειν συ αν ητησας [αυτον]{.greek-omitted} και εδωκεν αν σοι υδωρ [ζων]{.greek-omitted} [ζον]{.greek-added}[4:10]{.aside}

[λεγει]{.greek-omitted} [Λεγει]{.greek-added} αυτω η γυνη [κυριε]{.greek-abbr} ουτε αντλημα εχεις και το φρεαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} βαθυ ποθεν ουν εχεις το υδωρ το [ζων]{.greek-omitted} [ζον]{.greek-added}[4:11]{.aside}

[μη]{.greek-omitted} [Μη]{.greek-added} συ μειζων ει του [πατρος]{.greek-abbr} ημων ιακωβ ος εδωκεν ημιν το φρεαρ και αυτος εξ αυτου επιεν και οι υιοι αυτου και τα θρεμματα αυτου [Μη]{.greek-added} [συ]{.greek-added} [μειζων]{.greek-added} [ει]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιακωβ]{.greek-added} [ος]{.greek-added} [εδωκεν]{.greek-added} [ημιν]{.greek-added} [το]{.greek-added} [φρεαρ]{.greek-added} [και]{.greek-added} [αυτος]{.greek-added} [εξ]{.greek-added} [αυτου]{.greek-added} [επιεν]{.greek-added} [και]{.greek-added} [οι]{.greek-added} [υιοι]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [τα]{.greek-added} [θρεμματα]{.greek-added} [αυτου]{.greek-added}[4:12]{.aside}

[απεκριθη]{.greek-omitted} [Απεκριθη]{.greek-added} [ιησους]{.greek-abbr} [κα]{.unclear}ι ειπεν αυτη πας ο πινων εκ του υδατος τουτου διψησει παλιν[4:13]{.aside}

[ος]{.greek-omitted} [Ος]{.greek-added} δ αν πιη εκ του υδατος ου εγω δωσω αυτω ου μη [διψηση]{.greek-omitted} [διψησει]{.greek-added} εις τον αιωνα αλλα το υδωρ ο δωσω αυτω γενησεται εν αυτω πηγη υδατος αλλομενου εις ζωην αιωνιον[4:14]{.aside}

### Chapter 20

[απηλθον]{.greek-omitted} [Απηλθον]{.greek-added} ουν παλιν προς εαυτους οι μαθηται[20:10]{.aside}

[μαρια]{.greek-omitted} [μαριαμ]{.greek-added} δε [ειστηκει]{.greek-omitted} [ιστηκει]{.greek-added} προς το μνημειον [εξω]{.greek-added} κλαιουσα [εξω]{.greek-omitted} ως ουν εκλαιεν παρεκυψεν εις το μνημειον[20:11]{.aside}

και θεωρει δυο αγγελους εν λευκοις καθεζομενους ενα προς τη κεφαλη και ενα προς τοις [ποσιν]{.greek-omitted} [ποσι¯]{.greek-added} οπου εκειτο το σωμα του [ιησου]{.greek-abbr}[20:12]{.aside}

και λεγουσιν αυτη εκεινοι γυναι τι κλαιεις [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [οτι]{.greek-omitted} [ηραν]{.greek-omitted} [τον]{.greek-omitted} [κυριον]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [οιδα]{.greek-omitted} [που]{.greek-omitted} [εθηκαν]{.greek-omitted} [αυτον]{.greek-omitted}[[20:13 *(lacunose)*]{.lacunose}]{.aside}

[λεγει]{.greek-omitted} [Λεγει]{.greek-added} αυτη ο [ιησους]{.greek-abbr} γυναι τι κλαιεις τινα ζητεις εκεινη δοκουσα οτι ο κηπουρος εστιν λεγει αυτω [κυριε]{.greek-abbr} ει συ εβαστασας αυτον ειπε μοι που εθηκας αυτον καγω αυτον αρω [Λεγει]{.greek-added} [αυτη]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [γυναι]{.greek-added} [τι]{.greek-added} [κλαιεις]{.greek-added} [τινα]{.greek-added} [ζητεις]{.greek-added} [εκεινη]{.greek-added} [δοκουσα]{.greek-added} [οτι]{.greek-added} [ο]{.greek-added} [κηπουρος]{.greek-added} [εστιν]{.greek-added} [λεγει]{.greek-added} [αυτω]{.greek-added} [[κυριε]{.greek-abbr}]{.greek-added} [ει]{.greek-added} [συ]{.greek-added} [εβαστασας]{.greek-added} [αυτον]{.greek-added} [ειπε]{.greek-added} [μοι]{.greek-added} [που]{.greek-added} [εθηκας]{.greek-added} [αυτον]{.greek-added} [καγω]{.greek-added} [αυτον]{.greek-added} [αρω]{.greek-added}[20:15]{.aside}

[λεγει]{.greek-omitted} [Λεγει]{.greek-added} αυτη [ο]{.greek-omitted} [ιησους]{.greek-abbr} [μαρια]{.greek-omitted} [μαριαμ]{.greek-added} στραφεισα εκεινη λεγει αυτω [εβραιστι]{.greek-added} [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ο λεγεται διδασκαλε[20:16]{.aside}

[λεγει]{.greek-omitted} [Λεγει]{.greek-added} αυτη ο [ιησους]{.greek-abbr} μη μου απτου ουπω γαρ αναβεβηκα προς τον [πατερα]{.greek-abbr} μου πορευου [δε]{.greek-omitted} [ουν]{.greek-added} προς τους αδελφους μου και ειπε αυτοις αναβαινω προς τον [πατερα]{.greek-abbr} μου και [πατερα]{.greek-abbr} υμων και [θεον]{.greek-abbr} μου και [θεον]{.greek-abbr} υμων [Λεγει]{.greek-added} [αυτη]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [μη]{.greek-added} [μου]{.greek-added} [απτου]{.greek-added} [ουπω]{.greek-added} [γαρ]{.greek-added} [αναβεβηκα]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [μου]{.greek-added} [πορευου]{.greek-added} [ουν]{.greek-added} [προς]{.greek-added} [τους]{.greek-added} [αδελφους]{.greek-added} [μου]{.greek-added} [και]{.greek-added} [ειπε]{.greek-added} [αυτοις]{.greek-added} [αναβαινω]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [μου]{.greek-added} [και]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [υμων]{.greek-added} [και]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added} [μου]{.greek-added} [και]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added} [υμων]{.greek-added} [Λεγει]{.greek-added} [αυτη]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [μη]{.greek-added} [μου]{.greek-added} [απτου]{.greek-added} [ουπω]{.greek-added} [γαρ]{.greek-added} [αναβεβηκα]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [μου]{.greek-added} [πορευου]{.greek-added} [ουν]{.greek-added} [προς]{.greek-added} [τους]{.greek-added} [αδελφους]{.greek-added} [μου]{.greek-added} [και]{.greek-added} [ειπε]{.greek-added} [αυτοις]{.greek-added} [αναβαινω]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [μου]{.greek-added} [και]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [υμων]{.greek-added} [και]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added} [μου]{.greek-added} [και]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added} [υμων]{.greek-added}[20:17]{.aside}

