---
title: "Collation of Byz^RP^ vs 20057 (57)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 57 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20057).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 57                                   	| λογος                              	|
| 57 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 57 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 57               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 57                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 57 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 57                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 3

[ο]{.greek-omitted} [δε]{.greek-omitted} [επειχεν]{.greek-omitted} [αυτοι]{.greek-supplied}ς [πρ]{.unclear}οσδοκω[ν]{.greek-supplied} [τι]{.greek-supplied} [παρ]{.greek-supplied} αυτων [λαβ]{.unclear}ειν[[3:5 *(lacunose)*]{.lacunose}]{.aside}

[ειπεν]{.greek-supplied} [δε]{.unclear} [π]{.greek-supplied}[ετ]{.unclear}ρος αρ[γυ]{.greek-supplied}[ρ]{.unclear}[ι]{.greek-supplied}ον κα[ι]{.unclear} χρυσι[ον]{.unclear} [ο]{.unclear}υ[χ]{.greek-supplied} [υπαρχει]{.greek-omitted} [[υ]{.unclear}παρχι]{.greek-added} μοι [ο]{.unclear} [δ]{.unclear}ε [ε]{.unclear}[χω]{.unclear} [τ]{.unclear}ουτο σο[ι]{.unclear} [διδω]{.unclear}[μ]{.greek-supplied}[ι]{.unclear} [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} [του]{.greek-omitted} [ναζωραιου]{.greek-omitted} [εγειραι]{.greek-omitted} [και]{.greek-omitted} [περιπατει]{.greek-omitted}[3:6]{.aside}

[επεγινωσκον]{.greek-omitted} [τε]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουτος]{.greek-omitted} [ην]{.greek-omitted} [ο]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [ελεημοσυνην]{.greek-omitted} [καθημενος]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [ωραια]{.greek-omitted} [πυλη]{.greek-omitted} [του]{.greek-omitted} [ι]{.unclear}ερου κ[α]{.unclear}ι επλησθησαν θα[μ]{.unclear}βους και εκστασεως επι τω συ[μ]{.unclear}β[εβ]{.unclear}ηκοτι αυτω[3:10]{.aside}

κρατ[ουν]{.unclear}τος δε [του]{.greek-omitted} [αυτου]{.greek-added} [ιαθεντος]{.greek-omitted} [χωλου]{.greek-omitted} τον πετρον και [τον]{.greek-added} ιωα[ννην]{.unclear} συνεδραμεν [προς]{.greek-omitted} [αυτους]{.greek-omitted} π[α]{.unclear}ς ο [λα]{.unclear}ος [[π]{.unclear}ρος]{.greek-added} [αυτ[ο]{.unclear}υ[ς]{.unclear}]{.greek-added} [ε]{.unclear}πι [τη]{.unclear} [σ]{.unclear}[το]{.greek-supplied}[α]{.unclear} τη [καλ]{.unclear}ου[μ]{.unclear}ε[ν]{.greek-supplied}[η]{.unclear} σο[λ]{.unclear}ομων[τ]{.unclear}ος [ε]{.greek-supplied}[κ]{.unclear}θ[αμβ]{.unclear}οι[3:11]{.aside}

ιδ[ω]{.unclear}ν δε [[ο]{.greek-supplied}]{.greek-added} [πετρος]{.unclear} [α]{.unclear}π[ε]{.unclear}κρι[νατο]{.greek-supplied} [π]{.greek-supplied}[ρ]{.unclear}ος τον λ[α]{.unclear}[ον]{.greek-supplied} [ανδρε]{.greek-supplied}ς ισραηλ[ι]{.greek-supplied}[ται]{.greek-supplied} [τι]{.greek-omitted} [θαυμαζετε]{.greek-omitted} [επι]{.greek-omitted} [τουτω]{.greek-omitted} [η]{.greek-omitted} [ημιν]{.greek-omitted} [τι]{.greek-omitted} [ατενιζετε]{.greek-omitted} [ως]{.greek-omitted} [ιδια]{.greek-omitted} [δυναμει]{.greek-omitted} [η]{.greek-omitted} [ευσεβεια]{.greek-omitted} [πεποιηκοσιν]{.greek-omitted} [του]{.greek-omitted} [περιπατειν]{.greek-omitted} [αυτον]{.greek-omitted}[3:12]{.aside}

