---
title: "Collation of Byz^RP^ vs 20055 (55)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 55 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20055).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 55                                   	| λογος                              	|
| 55 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 55 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 55               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 55                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 55 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 55                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [υιου]{.greek-omitted} του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται [εν]{.greek-omitted} [τοις]{.greek-omitted} [προφηταις]{.greek-omitted} [ιδου]{.greek-omitted} [εγω]{.greek-omitted} [αποστελλω]{.greek-omitted} [τον]{.greek-omitted} [αγγελον]{.greek-omitted} [μου]{.greek-omitted} [προ]{.greek-omitted} [προσωπου]{.greek-omitted} [σου]{.greek-omitted} [ος]{.greek-omitted} [κατασκευασει]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [σου]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [σου]{.greek-omitted}[[1:2 *(lacunose)*]{.lacunose}]{.aside}

[φωνη]{.greek-omitted} [βοωντος]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [ετοιμασατε]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [κυριου]{.greek-omitted} ευθειας [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added} τας τριβους αυτου[[1:3 *(lacunose)*]{.lacunose}]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας [εις]{.greek-omitted} [αφεσιν]{.greek-omitted} [αμαρτιων]{.greek-omitted}[[1:4 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εξεπορευετο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πασα]{.greek-omitted} [η]{.greek-omitted} [ιουδαια]{.greek-omitted} [χωρα]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ιεροσολυμιται]{.greek-omitted} [και]{.greek-omitted} [εβαπτιζοντο]{.greek-omitted} [παντες]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιορδανη]{.greek-omitted} [ποταμω]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} εξομολογουμενοι τας αμαρτιας αυτων[[1:5 *(lacunose)*]{.lacunose}]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και εκηρυσσεν λεγων ερχεται ο ισχυροτερος [μος]{.greek-added} μου οπισω μου ου ουκ ειμι ικανος [κυψας]{.greek-omitted} [λυσαι]{.greek-omitted} [τον]{.greek-omitted} [ιμαντα]{.greek-omitted} [των]{.greek-omitted} [υποδηματων]{.greek-omitted} [αυτου]{.greek-omitted}[[1:7 *(lacunose)*]{.lacunose}]{.aside}

[εγω]{.greek-omitted} [μεν]{.greek-omitted} [εβαπτισα]{.greek-omitted} [υμας]{.greek-omitted} [εν]{.greek-omitted} [υδατι]{.greek-omitted} αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[[1:8 *(lacunose)*]{.lacunose}]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη [υπο]{.greek-omitted} [ιωαννου]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ιορδανην]{.greek-omitted}[[1:9 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [φωνη]{.greek-omitted} [εγενετο]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[[1:11 *(lacunose)*]{.lacunose}]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [εκει]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [ημερας]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [πειραζομενος]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [θηριων]{.greek-omitted} και οι αγγελοι διηκονουν αυτω[[1:13 *(lacunose)*]{.lacunose}]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν [ο]{.greek-omitted} [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων [οτι]{.greek-omitted} [πεπληρωται]{.greek-omitted} [ο]{.greek-omitted} [καιρος]{.greek-omitted} [και]{.greek-omitted} [ηγγικεν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μετανοειτε]{.greek-omitted} [και]{.greek-omitted} [πιστευετε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ευαγγελιω]{.greek-omitted}[[1:15 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [εκαλεσεν]{.greek-omitted} [αυτους]{.greek-omitted} και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[[1:20 *(lacunose)*]{.lacunose}]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν [εισελθων]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [συναγωγην]{.greek-omitted} [εδιδασκεν]{.greek-omitted}[[1:21 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [διδασκων]{.greek-omitted} [αυτους]{.greek-omitted} [ως]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχων]{.greek-omitted} και ουχ ως οι γραμματεις[[1:22 *(lacunose)*]{.lacunose}]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν πνευματι ακαθαρτω και ανεκραξεν[1:23]{.aside}

λεγων εα τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαρινε]{.greek-added} ηλθες [απολεσαι]{.greek-omitted} [απωλεσαι]{.greek-added} ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το πνευμα το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν [εξ]{.greek-omitted} [αυτου]{.greek-omitted}[1:26]{.aside}

και εθαμβηθησαν παντες ωστε [συζητειν]{.greek-omitted} [ζητειν]{.greek-added} προς εαυτους [λεγοντας]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [τουτο]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [διδαχη]{.greek-omitted} [η]{.greek-omitted} [καινη]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [κατ]{.greek-omitted} [εξουσιαν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [πνευμασιν]{.greek-omitted} [τοις]{.greek-omitted} [ακαθαρτοις]{.greek-omitted} [επιτασσει]{.greek-omitted} [και]{.greek-omitted} [υπακουουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[[1:27 *(lacunose)*]{.lacunose}]{.aside}

εξηλθεν δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [ηγειρεν]{.greek-omitted} [αυτην]{.greek-omitted} κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[[1:31 *(lacunose)*]{.lacunose}]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και εθεραπευσεν πολλους κακως εχοντας ποικιλαις νοσοις [και]{.greek-omitted} [δαιμονια]{.greek-omitted} [πολλα]{.greek-omitted} [εξεβαλεν]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηφιεν]{.greek-omitted} [λαλειν]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [οτι]{.greek-omitted} [ηδεισαν]{.greek-omitted} [αυτον]{.greek-omitted}[1:34]{.aside}

[και]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [πολλους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [ποικιλαις]{.greek-omitted} [νοσοις]{.greek-omitted} και δαιμονια πολλα εξεβαλεν και ουκ ηφιεν λαλειν τα δαιμονια οτι ηδεισαν αυτον[1:34 | instance no. 2]{.aside}

και πρωι εννυχον [λιαν]{.greek-omitted} αναστας εξηλθεν [και]{.greek-omitted} [απηλθεν]{.greek-omitted} [εις]{.greek-omitted} [ερημον]{.greek-omitted} [τοπον]{.greek-omitted} [κακει]{.greek-omitted} [προσηυχετο]{.greek-omitted}[[1:35 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [αγωμεν]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [εχομενας]{.greek-omitted} [κωμοπολεις]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [εκει]{.greek-omitted} [κηρυξω]{.greek-omitted} εις τουτο γαρ εξεληλυθα[[1:38 *(lacunose)*]{.lacunose}]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον [και]{.greek-omitted} [γονυπετων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγων]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [εαν]{.greek-omitted} [θελης]{.greek-omitted} [δυνασαι]{.greek-omitted} [με]{.greek-omitted} [καθαρισαι]{.greek-omitted}[[1:40 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ειποντος]{.greek-omitted} [αυτου]{.greek-omitted} ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[[1:42 *(lacunose)*]{.lacunose}]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν ειπης αλλ υπαγε σεαυτον [δειξον]{.greek-omitted} [τω]{.greek-omitted} [ιερει]{.greek-omitted} [και]{.greek-omitted} [προσενεγκε]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [καθαρισμου]{.greek-omitted} [σου]{.greek-omitted} [α]{.greek-omitted} [προσεταξεν]{.greek-omitted} [μωσης]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted}[[1:44 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ορα]{.greek-omitted} [μηδενι]{.greek-omitted} [μηδεν]{.greek-omitted} [ειπης]{.greek-omitted} [αλλ]{.greek-omitted} [υπαγε]{.greek-omitted} [σεαυτον]{.greek-omitted} δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου [α]{.greek-omitted} [προσεταξεν]{.greek-omitted} [μωσης]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted}[[1:44 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εξελθων]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [πολλα]{.greek-omitted} [και]{.greek-omitted} [διαφημιζειν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ωστε]{.greek-omitted} [μηκετι]{.greek-omitted} [αυτον]{.greek-omitted} [δυνασθαι]{.greek-omitted} [φανερως]{.greek-omitted} [εις]{.greek-omitted} [πολιν]{.greek-omitted} [εισελθειν]{.greek-omitted} [αλλ]{.greek-omitted} [εξω]{.greek-omitted} [εν]{.greek-omitted} [ερημοις]{.greek-omitted} [τοποις]{.greek-omitted} [ην]{.greek-omitted} και ηρχοντο προς αυτον πανταχοθεν[[1:45 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 2

και εισηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} παλιν εις καπερναουμ [δι]{.greek-omitted} [ημερων]{.greek-omitted} [και]{.greek-omitted} [ηκουσθη]{.greek-omitted} [οτι]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [εστιν]{.greek-omitted}[[2:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [μη]{.greek-omitted} [δυναμενοι]{.greek-omitted} [προσεγγισαι]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [απεστεγασαν]{.greek-omitted} [την]{.greek-omitted} [στεγην]{.greek-omitted} [οπου]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [εξορυξαντες]{.greek-omitted} [χαλωσιν]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} εφ ω ο παραλυτικος κατεκειτο[[2:4 *(lacunose)*]{.lacunose}]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον αφεωνται σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι [και]{.greek-omitted} [διαλογιζομενοι]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [καρδιαις]{.greek-omitted} [αυτων]{.greek-omitted}[[2:6 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [επιγνους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [ουτως]{.greek-omitted} [αυτοι]{.greek-omitted} [διαλογιζονται]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[[2:8 *(lacunose)*]{.lacunose}]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω αφεωνται σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ιδητε]{.greek-added} οτι εξουσιαν [εχει]{.greek-omitted} [εχη]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι επι της γης αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

[σοι]{.greek-omitted} [συ]{.greek-added} λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν εναντιον παντων [ωστε]{.greek-omitted} [εξιστασθαι]{.greek-omitted} [παντας]{.greek-omitted} [και]{.greek-omitted} [δοξαζειν]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [λεγοντας]{.greek-omitted} [οτι]{.greek-omitted} [ουδεποτε]{.greek-omitted} [ουτως]{.greek-omitted} [ειδομεν]{.greek-omitted}[2:12]{.aside}

[και]{.greek-omitted} [ηγερθη]{.greek-omitted} [ευθεως]{.greek-omitted} [και]{.greek-omitted} [αρας]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εναντιον]{.greek-omitted} [παντων]{.greek-omitted} ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added}[2:12 | instance no. 2]{.aside}

και εξηλθεν παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον [επι]{.greek-omitted} [εις]{.greek-added} το τελωνιον [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [αναστας]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted}[[2:14 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κατακεισθαι]{.greek-omitted} [αυτον]{.greek-omitted} εν τη οικια αυτου [και]{.greek-omitted} [πολλοι]{.greek-omitted} [τελωναι]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλοι]{.greek-omitted} [συνανεκειντο]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted}[[2:15 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κατακεισθαι]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [αυτου]{.greek-omitted} και πολλοι τελωναι και αμαρτωλοι [συνανεκειντο]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted}[[2:15 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [εσθιοντα]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} [ελεγον]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[[2:16 *(lacunose)*]{.lacunose}]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν [εχουσιν]{.greek-omitted} [εχου]{.greek-added} οι ισχυοντες [ιατρου]{.greek-omitted} [αλλ]{.greek-omitted} [οι]{.greek-omitted} [κακως]{.greek-omitted} [εχοντες]{.greek-omitted} [ουκ]{.greek-omitted} [ηλθον]{.greek-omitted} [καλεσαι]{.greek-omitted} [δικαιους]{.greek-omitted} [αλλα]{.greek-omitted} [αμαρτωλους]{.greek-omitted} [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[[2:17 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ησαν]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευοντες]{.greek-omitted} [και]{.greek-omitted} [ερχονται]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευουσιν]{.greek-omitted} οι δε σοι μαθηται ου νηστευουσιν[[2:18 *(lacunose)*]{.lacunose}]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται [οι]{.greek-omitted} υιοι του νυμφωνος [εν]{.greek-omitted} [ω]{.greek-omitted} [ο]{.greek-omitted} [νυμφιος]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted} [εστιν]{.greek-omitted} [νηστευειν]{.greek-omitted} [οσον]{.greek-omitted} [χρονον]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [εχουσιν]{.greek-omitted} [τον]{.greek-omitted} [νυμφιον]{.greek-omitted} [ου]{.greek-omitted} [δυνανται]{.greek-omitted} [νηστευειν]{.greek-omitted}[[2:19 *(lacunose)*]{.lacunose}]{.aside}

[ελευσονται]{.greek-omitted} [δε]{.greek-omitted} [ημεραι]{.greek-omitted} [οταν]{.greek-omitted} [απαρθη]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted} [ο]{.greek-omitted} [νυμφιος]{.greek-omitted} [και]{.greek-omitted} [τοτε]{.greek-omitted} [νηστευσουσιν]{.greek-omitted} εν εκειναις ταις ημεραις[[2:20 *(lacunose)*]{.lacunose}]{.aside}

και ουδεις επιβλημα [ρακους]{.greek-omitted} [ρακκους]{.greek-added} αγναφου [επιρραπτει]{.greek-omitted} [επι]{.greek-omitted} [ιματιω]{.greek-omitted} [παλαιω]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [αιρει]{.greek-omitted} [το]{.greek-omitted} [πληρωμα]{.greek-omitted} [αυτου]{.greek-omitted} [το]{.greek-omitted} [καινον]{.greek-omitted} [του]{.greek-omitted} [παλαιου]{.greek-omitted} [και]{.greek-omitted} [χειρον]{.greek-omitted} [σχισμα]{.greek-omitted} [γινεται]{.greek-omitted}[[2:21 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ουδεις]{.greek-omitted} [βαλλει]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [παλαιους]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [ρησσει]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [ο]{.greek-omitted} [νεος]{.greek-omitted} [τους]{.greek-omitted} [ασκους]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [εκχειται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [απολουνται]{.greek-omitted} [αλλα]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} εις ασκους καινους βλητεον[[2:22 *(lacunose)*]{.lacunose}]{.aside}

και εγενετο παραπορευεσθαι [αυτον]{.greek-omitted} εν τοις σαββασιν [δια]{.greek-omitted} [των]{.greek-omitted} [σποριμων]{.greek-omitted} [και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [οδον]{.greek-omitted} [ποιειν]{.greek-omitted} [τιλλοντες]{.greek-omitted} [τους]{.greek-omitted} [σταχυας]{.greek-omitted}[[2:23 *(lacunose)*]{.lacunose}]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην εχων την χειρα[3:1]{.aside}

[και]{.greek-omitted} [εξελθοντες]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ευθεως]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [ηρωδιανων]{.greek-omitted} [συμβουλιον]{.greek-omitted} [εποιουν]{.greek-omitted} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} οπως [αν]{.greek-added} αυτον απολεσωσιν[[3:6 *(lacunose)*]{.lacunose}]{.aside}

και ο [ιησους]{.greek-abbr} ανεχωρησεν μετα των μαθητων αυτου [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν [αυτω]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted}[[3:7 *(lacunose)*]{.lacunose}]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν [αυτος]{.greek-omitted} [και]{.greek-omitted} [απηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[[3:13 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ιουδαν]{.greek-omitted} [ισκαριωτην]{.greek-omitted} ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[[3:19 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος [ωστε]{.greek-omitted} [μη]{.greek-omitted} [δυνασθαι]{.greek-omitted} [αυτους]{.greek-omitted} [μητε]{.greek-omitted} [αρτον]{.greek-omitted} [φαγειν]{.greek-omitted}[[3:20 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οι]{.greek-omitted} [παρ]{.greek-omitted} [αυτου]{.greek-omitted} [εξηλθον]{.greek-omitted} [κρατησαι]{.greek-omitted} [αυτον]{.greek-omitted} ελεγον γαρ οτι εξεστη[[3:21 *(lacunose)*]{.lacunose}]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον [οτι]{.greek-omitted} [βεελζεβουλ]{.greek-omitted} [εχει]{.greek-omitted} [και]{.greek-omitted} [οτι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αρχοντι]{.greek-omitted} [των]{.greek-omitted} [δαιμονιων]{.greek-omitted} εκβαλλει τα δαιμονια[[3:22 *(lacunose)*]{.lacunose}]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [πως]{.greek-omitted} [δυναται]{.greek-omitted} [σατανας]{.greek-omitted} [σαταναν]{.greek-omitted} [εκβαλλειν]{.greek-omitted}[[3:23 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [ανεστη]{.greek-omitted} [εφ]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [μεμερισται]{.greek-omitted} ου δυναται σταθηναι αλλα τελος εχει[[3:26 *(lacunose)*]{.lacunose}]{.aside}

ουδεις δυναται τα σκευη του ισχυρου [εισελθων]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπασαι]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [πρωτον]{.greek-omitted} [τον]{.greek-omitted} [ισχυρον]{.greek-omitted} [δηση]{.greek-omitted} [και]{.greek-omitted} τοτε την οικιαν αυτου διαρπαση[[3:27 *(lacunose)*]{.lacunose}]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα [τοις]{.greek-omitted} [υιοις]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [και]{.greek-omitted} [βλασφημιαι]{.greek-omitted} [οσας]{.greek-omitted} [αν]{.greek-omitted} [βλασφημησωσιν]{.greek-omitted}[[3:28 *(lacunose)*]{.lacunose}]{.aside}

οτι ελεγον πνευμα ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι και η [μητηρ]{.greek-abbr} αυτου [και]{.greek-omitted} [εξω]{.greek-omitted} [εστωτες]{.greek-omitted} [απεστειλαν]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [φωνουντες]{.greek-omitted} [αυτον]{.greek-omitted}[[3:31 *(lacunose)*]{.lacunose}]{.aside}

[ος]{.greek-omitted} [γαρ]{.greek-omitted} [αν]{.greek-omitted} [ποιηση]{.greek-omitted} [το]{.greek-omitted} [θελημα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ουτος]{.greek-omitted} [αυτος]{.greek-added} αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} εστιν[[3:35 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [συνηχθη]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [ωστε]{.greek-omitted} [αυτον]{.greek-omitted} [εμβαντα]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [καθησθαι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ην]{.greek-omitted}[[4:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [πολλα]{.greek-omitted} και ελεγεν αυτοις εν τη διδαχη αυτου[[4:2 *(lacunose)*]{.lacunose}]{.aside}

ακουετε [ιδου]{.greek-omitted} [εξηλθεν]{.greek-omitted} [ο]{.greek-omitted} [σπειρων]{.greek-omitted} [του]{.greek-omitted} [σπειραι]{.greek-omitted}[4:3]{.aside}

[ακουετε]{.greek-omitted} ιδου εξηλθεν ο σπειρων του σπειραι[4:3 | instance no. 2]{.aside}

και εγενετο [εν]{.greek-omitted} [τω]{.greek-omitted} [σπειρειν]{.greek-omitted} [ο]{.greek-omitted} [μεν]{.greek-omitted} [επεσεν]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [και]{.greek-omitted} [ηλθεν]{.greek-omitted} [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [και]{.greek-omitted} [κατεφαγεν]{.greek-omitted} [αυτο]{.greek-omitted}[[4:4 *(lacunose)*]{.lacunose}]{.aside}

και ελεγεν ο εχων ωτα ακουειν [ακουειν]{.greek-added} ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα [την]{.greek-omitted} [παραβολην]{.greek-omitted}[[4:10 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [την]{.greek-omitted} [καλην]{.greek-omitted} [σπαρεντες]{.greek-omitted} [οιτινες]{.greek-omitted} [ακουουσιν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [παραδεχονται]{.greek-omitted} [και]{.greek-omitted} [καρποφορουσιν]{.greek-omitted} [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[[4:20 *(lacunose)*]{.lacunose}]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} τι κρυπτον ο εαν μη φανερωθη [ουδε]{.greek-omitted} [εγενετο]{.greek-omitted} [αποκρυφον]{.greek-omitted} [αλλ]{.greek-omitted} [ινα]{.greek-omitted} [εις]{.greek-omitted} [φανερον]{.greek-omitted} [ελθη]{.greek-omitted}[[4:22 *(lacunose)*]{.lacunose}]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε [εν]{.greek-omitted} [ω]{.greek-omitted} [μετρω]{.greek-omitted} [μετρειτε]{.greek-omitted} [μετρηθησεται]{.greek-omitted} [υμιν]{.greek-omitted} [και]{.greek-omitted} [προστεθησεται]{.greek-omitted} [υμιν]{.greek-omitted} [τοις]{.greek-omitted} [ακουουσιν]{.greek-omitted}[[4:24 *(lacunose)*]{.lacunose}]{.aside}

[ος]{.greek-omitted} [γαρ]{.greek-omitted} [αν]{.greek-omitted} [εχη]{.greek-omitted} [δοθησεται]{.greek-omitted} [αυτω]{.greek-omitted} και ος ουκ εχει και ο εχει αρθησεται απ αυτου[[4:25 *(lacunose)*]{.lacunose}]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [τον]{.greek-omitted} [σπορον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[[4:26 *(lacunose)*]{.lacunose}]{.aside}

[οταν]{.greek-omitted} [δε]{.greek-omitted} [παραδω]{.greek-omitted} [ο]{.greek-omitted} [καρπος]{.greek-omitted} [ευθεως]{.greek-omitted} [αποστελλει]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} οτι παρεστηκεν ο θερισμος[[4:29 *(lacunose)*]{.lacunose}]{.aside}

και ελεγεν τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} [η]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} [παραβολη]{.greek-omitted} [παραβαλωμεν]{.greek-omitted} [αυτην]{.greek-omitted}[[4:30 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [σπαρη]{.greek-omitted} [αναβαινει]{.greek-omitted} [και]{.greek-omitted} [γινεται]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} [λαχανων]{.greek-omitted} [μειζων]{.greek-omitted} [και]{.greek-omitted} [ποιει]{.greek-omitted} [κλαδους]{.greek-omitted} [μεγαλους]{.greek-omitted} [ωστε]{.greek-omitted} [δυνασθαι]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [σκιαν]{.greek-omitted} [αυτου]{.greek-omitted} τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[[4:32 *(lacunose)*]{.lacunose}]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει [αυτοις]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [καθως]{.greek-omitted} [εδυναντο]{.greek-omitted} [ακουειν]{.greek-omitted}[[4:33 *(lacunose)*]{.lacunose}]{.aside}

[χωρις]{.greek-omitted} [δε]{.greek-omitted} [παραβολης]{.greek-omitted} [ουκ]{.greek-omitted} [ελαλει]{.greek-omitted} [αυτοις]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [δε]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} επελυεν παντα[[4:34 *(lacunose)*]{.lacunose}]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης [διελθωμεν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted}[[4:35 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης [εις]{.greek-omitted} [την]{.greek-omitted} [χωραν]{.greek-omitted} [των]{.greek-omitted} [γαδαρηνων]{.greek-omitted}[5:1]{.aside}

[και]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} εις την χωραν των γαδαρηνων[5:1 | instance no. 2]{.aside}

και εξελθοντι αυτω εκ του [πλοιου]{.greek-omitted} [ευθεως]{.greek-omitted} [απηντησεν]{.greek-omitted} [αυτω]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [μνημειων]{.greek-omitted} [ανθρωπος]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [ακαθαρτω]{.greek-omitted}[5:2]{.aside}

[και]{.greek-omitted} [εξελθοντι]{.greek-omitted} [αυτω]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν πνευματι ακαθαρτω[5:2 | instance no. 2]{.aside}

ος την κατοικησιν [ειχεν]{.greek-omitted} [εσχεν]{.greek-added} εν τοις μνημασιν και ουτε αλυσεσιν ουδεις εδυνατο αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις αυτον ισχυεν δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις ορεσιν και εν τοις μνημασιν ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν εδραμεν και προσεκυνησεν αυτω[5:6]{.aside}

[και]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [πολλα]{.greek-omitted} ινα μη αυτους αποστειλη εξω της χωρας[[5:10 *(lacunose)*]{.lacunose}]{.aside}

ην δε εκει προς τω ορει αγελη χοιρων μεγαλη βοσκομενη[5:11]{.aside}

[και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [παρακαλειν]{.greek-omitted} [αυτον]{.greek-omitted} [απελθειν]{.greek-omitted} απο των οριων αυτων[[5:17 *(lacunose)*]{.lacunose}]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους [και]{.greek-omitted} [αναγγειλον]{.greek-omitted} [αυτοις]{.greek-omitted} [οσα]{.greek-omitted} [σοι]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [πεποιηκεν]{.greek-omitted} [και]{.greek-omitted} [ηλεησεν]{.greek-omitted} [σε]{.greek-omitted}[[5:19 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [διαπερασαντος]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} [παλιν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} [συνηχθη]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} παρα την θαλασσαν[[5:21 *(lacunose)*]{.lacunose}]{.aside}

και ιδου ερχεται εις των [αρχισυναγωγων]{.greek-omitted} [αρχισυναγαγων]{.greek-added} [ονοματι]{.greek-omitted} [ονομα]{.greek-added} ιαειρος [και]{.greek-omitted} [ιδων]{.greek-omitted} [αυτον]{.greek-omitted} [πιπτει]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted}[[5:22 *(lacunose)*]{.lacunose}]{.aside}

και [απηλθεν]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ηκολουθει]{.greek-omitted} [αυτω]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [και]{.greek-omitted} [συνεθλιβον]{.greek-omitted} [εθλιβον]{.greek-added} αυτον[[5:24 *(lacunose)*]{.lacunose}]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [επιγνους]{.greek-omitted} [εν]{.greek-omitted} [εαυτω]{.greek-omitted} [την]{.greek-omitted} [εξ]{.greek-omitted} [αυτου]{.greek-omitted} [δυναμιν]{.greek-omitted} [εξελθουσαν]{.greek-omitted} επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[[5:30 *(lacunose)*]{.lacunose}]{.aside}

και ελεγον αυτω οι [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [βλεπεις]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [συνθλιβοντα]{.greek-omitted} [σε]{.greek-omitted} [και]{.greek-omitted} [λεγεις]{.greek-omitted} [τις]{.greek-omitted} [μου]{.greek-omitted} [ηψατο]{.greek-omitted}[[5:31 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [διεστειλατο]{.greek-omitted} [αυτοις]{.greek-omitted} [πολλα]{.greek-omitted} ινα μηδεις γνω τουτο και ειπεν δοθηναι αυτη φαγειν[[5:43 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την πατριδα αυτου [και]{.greek-omitted} [ακολουθουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted}[[6:1 *(lacunose)*]{.lacunose}]{.aside}

και εθαυμαζεν δια την απιστιαν αυτων [και]{.greek-omitted} [περιηγεν]{.greek-omitted} [τας]{.greek-omitted} [κωμας]{.greek-omitted} [κυκλω]{.greek-omitted} [διδασκων]{.greek-omitted}[6:6]{.aside}

[και]{.greek-omitted} [εθαυμαζεν]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [απιστιαν]{.greek-omitted} [αυτων]{.greek-omitted} και περιηγεν τας κωμας κυκλω διδασκων[6:6 | instance no. 2]{.aside}

[και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [μη]{.greek-omitted} [δεξωνται]{.greek-omitted} [υμας]{.greek-omitted} [μηδε]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [υμων]{.greek-omitted} [εκπορευομενοι]{.greek-omitted} [εκειθεν]{.greek-omitted} [εκτιναξατε]{.greek-omitted} [τον]{.greek-omitted} [χουν]{.greek-omitted} [τον]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [η]{.greek-omitted} [γομορροις]{.greek-omitted} εν ημερα κρισεως η τη πολει εκεινη[[6:11 *(lacunose)*]{.lacunose}]{.aside}

και εξελθοντες εκηρυσσον ινα μετανοησωσιν[6:12]{.aside}

[και]{.greek-omitted} [δαιμονια]{.greek-omitted} [πολλα]{.greek-omitted} [εξεβαλλον]{.greek-omitted} [και]{.greek-omitted} [ηλειφον]{.greek-omitted} [ελαιω]{.greek-omitted} πολλους αρρωστους και εθεραπευον[[6:13 *(lacunose)*]{.lacunose}]{.aside}

και ηκουσεν ο βασιλευς ηρωδης φανερον γαρ εγενετο [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [οτι]{.greek-omitted} [ιωαννης]{.greek-omitted} [ο]{.greek-omitted} [βαπτιζων]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} [ηγερθη]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ενεργουσιν]{.greek-omitted} [αι]{.greek-omitted} [δυναμεις]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted}[[6:14 *(lacunose)*]{.lacunose}]{.aside}

[αλλοι]{.greek-omitted} [ελεγον]{.greek-omitted} [οτι]{.greek-omitted} [ηλιας]{.greek-omitted} [εστιν]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [ελεγον]{.greek-omitted} οτι προφητης εστιν ως εις των προφητων[[6:15 *(lacunose)*]{.lacunose}]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω απεκεφαλισα [ιωαννην]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [αυτος]{.greek-omitted} [ηγερθη]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted}[[6:16 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} [και]{.greek-omitted} [ηνεγκεν]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [πινακι]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτην]{.greek-omitted} [τω]{.greek-omitted} [κορασιω]{.greek-omitted} και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[[6:28 *(lacunose)*]{.lacunose}]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν [αυτω]{.greek-omitted} [παντα]{.greek-omitted} [και]{.greek-omitted} [οσα]{.greek-omitted} [εποιησαν]{.greek-omitted} [και]{.greek-omitted} [οσα]{.greek-omitted} [εδιδαξαν]{.greek-omitted}[[6:30 *(lacunose)*]{.lacunose}]{.aside}

και [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδων]{.greek-added} αυτους υπαγοντας και επεγνωσαν αυτον [πολλοι]{.greek-omitted} [και]{.greek-omitted} [πεζη]{.greek-omitted} [απο]{.greek-omitted} [πασων]{.greek-omitted} [των]{.greek-omitted} [πολεων]{.greek-omitted} [συνεδραμον]{.greek-omitted} [εκει]{.greek-omitted} [και]{.greek-omitted} [προηλθον]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [συνηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[[6:33 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ποσους]{.greek-omitted} [αρτους]{.greek-omitted} [εχετε]{.greek-omitted} [υπαγετε]{.greek-omitted} [και]{.greek-omitted} [ιδετε]{.greek-omitted} [και]{.greek-omitted} [γνοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} πεντε και δυο ιχθυας[[6:38 *(lacunose)*]{.lacunose}]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακληθηναι]{.greek-added} παντας [συμποσια]{.greek-omitted} [συμποσια]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [χλωρω]{.greek-omitted} [χορτω]{.greek-omitted}[[6:39 *(lacunose)*]{.lacunose}]{.aside}

και ησαν οι φαγοντες τους αρτους [πεντακισχιλιοι]{.greek-omitted} [[͵ε]{.greek-abbr}]{.greek-added} ανδρες[6:44]{.aside}

και ευθεως ηναγκασεν τους μαθητας αυτου [εμβηναι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [και]{.greek-omitted} [προαγειν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} [προς]{.greek-omitted} [βηθσαιδαν]{.greek-omitted} [εως]{.greek-omitted} [αυτος]{.greek-omitted} [απολυση]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted}[[6:45 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ειδεν]{.greek-omitted} [αυτους]{.greek-omitted} [βασανιζομενους]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ελαυνειν]{.greek-omitted} ην γαρ ο ανεμος εναντιος αυτοις [και]{.greek-omitted} [περι]{.greek-omitted} [τεταρτην]{.greek-omitted} [φυλακην]{.greek-omitted} [της]{.greek-omitted} [νυκτος]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [περιπατων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[[6:48 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ειδεν]{.greek-omitted} [αυτους]{.greek-omitted} [βασανιζομενους]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ελαυνειν]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [εναντιος]{.greek-omitted} [αυτοις]{.greek-omitted} και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[[6:48 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εξελθοντων]{.greek-omitted} [αυτων]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [πλοιου]{.greek-omitted} ευθεως επιγνοντες αυτον[[6:54 *(lacunose)*]{.lacunose}]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην [ηρξαντο]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [κραββατοις]{.greek-omitted} [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [περιφερειν]{.greek-omitted} [οπου]{.greek-omitted} [ηκουον]{.greek-omitted} [οτι]{.greek-omitted} [εκει]{.greek-omitted} [εστιν]{.greek-omitted}[[6:55 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [οπου]{.greek-omitted} [αν]{.greek-omitted} [εισεπορευετο]{.greek-omitted} [εις]{.greek-omitted} [κωμας]{.greek-omitted} [η]{.greek-omitted} [πολεις]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [αγοραις]{.greek-omitted} [ετιθουν]{.greek-omitted} [τους]{.greek-omitted} [ασθενουντας]{.greek-omitted} [και]{.greek-omitted} [παρεκαλουν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [καν]{.greek-omitted} [του]{.greek-omitted} [κρασπεδου]{.greek-omitted} [του]{.greek-omitted} [ιματιου]{.greek-omitted} [αυτου]{.greek-omitted} [αψωνται]{.greek-omitted} και οσοι αν ηπτοντο αυτου εσωζοντο[[6:56 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [ελθοντες]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted}[[7:1 *(lacunose)*]{.lacunose}]{.aside}

[ματην]{.greek-omitted} [δε]{.greek-omitted} [σεβονται]{.greek-omitted} [με]{.greek-omitted} διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[[7:7 *(lacunose)*]{.lacunose}]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} [κρατειτε]{.greek-omitted} [την]{.greek-omitted} [παραδοσιν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [βαπτισμους]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [παρομοια]{.greek-omitted} [τοιαυτα]{.greek-omitted} [πολλα]{.greek-omitted} [ποιειτε]{.greek-omitted}[[7:8 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} καλως [αθετειτε]{.greek-omitted} [αθετειται]{.greek-added} την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων [τηρησητε]{.greek-omitted} [τηρησηται]{.greek-added}[[7:9 *(lacunose)*]{.lacunose}]{.aside}

μωσης γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου [και]{.greek-omitted} [ο]{.greek-omitted} [κακολογων]{.greek-omitted} [πατερα]{.greek-omitted} [η]{.greek-omitted} [μητερα]{.greek-omitted} [θανατω]{.greek-omitted} [τελευτατω]{.greek-omitted}[[7:10 *(lacunose)*]{.lacunose}]{.aside}

[ακυρουντες]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τη]{.greek-omitted} [παραδοσει]{.greek-omitted} [υμων]{.greek-omitted} [η]{.greek-omitted} [παρεδωκατε]{.greek-omitted} και παρομοια τοιαυτα πολλα [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added}[[7:13 *(lacunose)*]{.lacunose}]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν [αυτοις]{.greek-omitted} [ακουετε]{.greek-omitted} [μου]{.greek-omitted} [παντες]{.greek-omitted} [και]{.greek-omitted} [συνιετε]{.greek-omitted}[[7:14 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [οχλου]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} περι της παραβολης[[7:17 *(lacunose)*]{.lacunose}]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε [ου]{.greek-omitted} [νοειτε]{.greek-omitted} [οτι]{.greek-omitted} [παν]{.greek-omitted} [το]{.greek-omitted} [εξωθεν]{.greek-omitted} [εισπορευομενον]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted}[[7:18 *(lacunose)*]{.lacunose}]{.aside}

[παντα]{.greek-omitted} [ταυτα]{.greek-omitted} [τα]{.greek-omitted} [πονηρα]{.greek-omitted} [εσωθεν]{.greek-omitted} [εκπορευεται]{.greek-omitted} και κοινοι τον [ανθρωπον]{.greek-abbr}[[7:23 *(lacunose)*]{.lacunose}]{.aside}

και εκειθεν αναστας απηλθεν [εις]{.greek-omitted} [τα]{.greek-omitted} [μεθορια]{.greek-omitted} [τυρου]{.greek-omitted} [και]{.greek-omitted} [σιδωνος]{.greek-omitted} [και]{.greek-omitted} [εισελθων]{.greek-omitted} [εις]{.greek-omitted} [οικιαν]{.greek-omitted} [ουδενα]{.greek-omitted} [ηθελεν]{.greek-omitted} [γνωναι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθη]{.greek-omitted} [λαθειν]{.greek-omitted}[[7:24 *(lacunose)*]{.lacunose}]{.aside}

[ακουσασα]{.greek-omitted} [γαρ]{.greek-omitted} [γυνη]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted} [ης]{.greek-omitted} [ειχεν]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [αυτης]{.greek-omitted} [πνευμα]{.greek-omitted} [ακαθαρτον]{.greek-omitted} ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[[7:25 *(lacunose)*]{.lacunose}]{.aside}

ην δε [η]{.greek-omitted} γυνη [ελλην]{.greek-added} [ελληνις]{.corr} [εκβαλλει]{.greek-added} [συραφοινικισσα]{.greek-omitted} [τω]{.greek-omitted} [γενει]{.greek-omitted} [και]{.greek-omitted} [ηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [το]{.greek-omitted} [δαιμονιον]{.greek-omitted} [εκβαλη]{.greek-omitted} εκ της θυγατρος αυτης[[7:26 *(lacunose)*]{.lacunose}]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι [τα]{.greek-omitted} [τεκνα]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [λαβειν]{.greek-omitted} [τον]{.greek-omitted} [αρτον]{.greek-omitted} [των]{.greek-omitted} [τεκνων]{.greek-omitted} [και]{.greek-omitted} [βαλειν]{.greek-omitted} [τοις]{.greek-omitted} [κυναριοις]{.greek-omitted}[[7:27 *(lacunose)*]{.lacunose}]{.aside}

η δε απεκριθη και λεγει αυτω [ναι]{.greek-omitted} [κυριε]{.greek-omitted} [και]{.greek-omitted} [γαρ]{.greek-omitted} [τα]{.greek-omitted} [κυναρια]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [τραπεζης]{.greek-omitted} [εσθιει]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [ψιχιων]{.greek-omitted} [των]{.greek-omitted} [παιδιων]{.greek-omitted}[[7:28 *(lacunose)*]{.lacunose}]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [απεκριθη]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια [υποκατω]{.greek-omitted} [της]{.greek-omitted} [τραπεζης]{.greek-omitted} [εσθιει]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [ψιχιων]{.greek-omitted} [των]{.greek-omitted} [παιδιων]{.greek-omitted}[[7:28 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον [εκ]{.greek-omitted} [της]{.greek-omitted} [θυγατρος]{.greek-omitted} [σου]{.greek-omitted}[[7:29 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [απελθουσα]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [αυτης]{.greek-omitted} [ευρεν]{.greek-omitted} [το]{.greek-omitted} [δαιμονιον]{.greek-omitted} [εξεληλυθος]{.greek-omitted} και την θυγατερα βεβλημενην επι της κλινης[[7:30 *(lacunose)*]{.lacunose}]{.aside}

και παλιν εξελθων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [ανα]{.greek-omitted} [μεσον]{.greek-omitted} [των]{.greek-omitted} [οριων]{.greek-omitted} [δεκαπολεως]{.greek-omitted}[[7:31 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [υπερπερισσως]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [καλως]{.greek-omitted} [παντα]{.greek-omitted} [πεποιηκεν]{.greek-omitted} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[[7:37 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις παμπολλου οχλου [οντος]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [εχοντων]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted}[[8:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [απεκριθησαν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [ποθεν]{.greek-omitted} [τουτους]{.greek-omitted} [δυνησεται]{.greek-omitted} [τις]{.greek-omitted} ωδε χορτασαι αρτων επ ερημιας[[8:4 *(lacunose)*]{.lacunose}]{.aside}

και επηρωτα αυτους ποσους [αρτους]{.greek-added} εχετε [αρτους]{.greek-omitted} οι δε ειπον επτα[8:5]{.aside}

και παρηγγειλεν τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας εκλασεν [και]{.greek-omitted} [εδιδου]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [παραθωσιν]{.greek-omitted} [και]{.greek-omitted} [παρεθηκαν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted}[[8:6 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ειχον]{.greek-omitted} [ιχθυδια]{.greek-omitted} [ολιγα]{.greek-omitted} [και]{.greek-omitted} [ευλογησας]{.greek-omitted} [ειπεν]{.greek-omitted} παραθειναι και αυτα[[8:7 *(lacunose)*]{.lacunose}]{.aside}

εφαγον [δε]{.greek-omitted} και εχορτασθησαν [και]{.greek-omitted} [ηραν]{.greek-omitted} [περισσευματα]{.greek-omitted} [κλασματων]{.greek-omitted} [επτα]{.greek-omitted} [σπυριδας]{.greek-omitted}[[8:8 *(lacunose)*]{.lacunose}]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [φαγοντες]{.greek-omitted} [ως]{.greek-omitted} [τετρακισχιλιοι]{.greek-omitted} και απελυσεν αυτους[[8:9 *(lacunose)*]{.lacunose}]{.aside}

και ευθεως εμβας εις το πλοιον [μετα]{.greek-omitted} [ματα]{.greek-added} των μαθητων αυτου ηλθεν εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι [και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [συζητειν]{.greek-omitted} [αυτω]{.greek-omitted} [ζητουντες]{.greek-omitted} [παρ]{.greek-omitted} [αυτου]{.greek-omitted} [σημειον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} πειραζοντες αυτον[[8:11 *(lacunose)*]{.lacunose}]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} [αυτου]{.greek-omitted} [λεγει]{.greek-omitted} [τι]{.greek-omitted} [η]{.greek-omitted} [γενεα]{.greek-omitted} [αυτη]{.greek-omitted} [σημειον]{.greek-omitted} [επιζητει]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} ει δοθησεται τη γενεα ταυτη σημειον[[8:12 *(lacunose)*]{.lacunose}]{.aside}

και αφεις αυτους εμβας [παλιν]{.greek-omitted} εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον [ουκ]{.greek-omitted} [ειχον]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted}[[8:14 *(lacunose)*]{.lacunose}]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε [ουδε]{.greek-omitted} [συνιετε]{.greek-omitted} [ετι]{.greek-omitted} [πεπωρωμενην]{.greek-omitted} [εχετε]{.greek-omitted} [την]{.greek-omitted} [καρδιαν]{.greek-omitted} [υμων]{.greek-omitted}[[8:17 *(lacunose)*]{.lacunose}]{.aside}

και ελεγεν αυτοις πως ου συνιετε[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον [και]{.greek-omitted} [παρακαλουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [αυτου]{.greek-omitted} [αψηται]{.greek-omitted}[[8:22 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [απεστειλεν]{.greek-omitted} [αυτον]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [αυτου]{.greek-omitted} [λεγων]{.greek-omitted} [μηδε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [κωμην]{.greek-omitted} [εισελθης]{.greek-omitted} μηδε ειπης τινι εν τη κωμη[[8:26 *(lacunose)*]{.lacunose}]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου [εις]{.greek-omitted} [τας]{.greek-omitted} [κωμας]{.greek-omitted} [καισαρειας]{.greek-omitted} [της]{.greek-omitted} [φιλιππου]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [επηρωτα]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγων]{.greek-omitted} [αυτοις]{.greek-omitted} τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[[8:27 *(lacunose)*]{.lacunose}]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην [και]{.greek-omitted} [αλλοι]{.greek-omitted} [ηλιαν]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [ενα]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted}[[8:28 *(lacunose)*]{.lacunose}]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [απεκριθησαν]{.greek-omitted} [ιωαννην]{.greek-omitted} [τον]{.greek-omitted} [βαπτιστην]{.greek-omitted} και [αλλοι]{.greek-omitted} [ηλιαν]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [ενα]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted}[[8:28 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [επετιμησεν]{.greek-omitted} [αυτοις]{.greek-omitted} ινα μηδενι λεγωσιν περι αυτου[[8:30 *(lacunose)*]{.lacunose}]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [πολλα]{.greek-omitted} [παθειν]{.greek-omitted} [και]{.greek-omitted} [αποδοκιμασθηναι]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [αρχιερεων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [και]{.greek-omitted} [αποκτανθηναι]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [τρεις]{.greek-omitted} [ημερας]{.greek-omitted} [αναστηναι]{.greek-omitted}[[8:31 *(lacunose)*]{.lacunose}]{.aside}

και παρρησια τον λογον ελαλει [και]{.greek-omitted} [προσλαβομενος]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [ηρξατο]{.greek-omitted} [επιτιμαν]{.greek-omitted} [αυτω]{.greek-omitted}[[8:32 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [παρρησια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ελαλει]{.greek-omitted} και προσλαβομενος αυτον ο πετρος [ηρξατο]{.greek-omitted} [επιτιμαν]{.greek-omitted} [αυτω]{.greek-omitted}[[8:32 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [επιστραφεις]{.greek-omitted} [και]{.greek-omitted} [ιδων]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} επετιμησεν τω πετρω λεγων υπαγε οπισω μου σατανα [οτι]{.greek-omitted} [ου]{.greek-omitted} [φρονεις]{.greek-omitted} [τα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted}[[8:33 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[[8:34 *(lacunose)*]{.lacunose}]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι [απολεσει]{.greek-omitted} [αυτην]{.greek-omitted} [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [απολεση]{.greek-omitted} [την]{.greek-omitted} [εαυτου]{.greek-omitted} [ψυχην]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted} ουτος σωσει αυτην[[8:35 *(lacunose)*]{.lacunose}]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} [εαν]{.greek-omitted} [κερδηση]{.greek-omitted} [τον]{.greek-omitted} [κοσμον]{.greek-omitted} [ολον]{.greek-omitted} [και]{.greek-omitted} [ζημιωθη]{.greek-omitted} [την]{.greek-omitted} [ψυχην]{.greek-omitted} [αυτου]{.greek-omitted}[[8:36 *(lacunose)*]{.lacunose}]{.aside}

[η]{.greek-omitted} [τι]{.greek-omitted} [δωσει]{.greek-omitted} [ανθρωπος]{.greek-omitted} ανταλλαγμα της ψυχης αυτου[[8:37 *(lacunose)*]{.lacunose}]{.aside}

ος γαρ εαν επαισχυνθη με [και]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [λογους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [γενεα]{.greek-omitted} [ταυτη]{.greek-omitted} [τη]{.greek-omitted} [μοιχαλιδι]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλω]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [επαισχυνθησεται]{.greek-omitted} [αυτον]{.greek-omitted} [οταν]{.greek-omitted} [ελθη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δοξη]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [αυτου]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted}[[8:38 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 9

και ελεγεν αυτοις [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [εισιν]{.greek-omitted} [τινες]{.greek-omitted} [των]{.greek-omitted} [ωδε]{.greek-omitted} [εστηκοτων]{.greek-omitted} [οιτινες]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [γευσωνται]{.greek-omitted} [θανατου]{.greek-omitted} [εως]{.greek-omitted} [αν]{.greek-omitted} [ιδωσιν]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εληλυθυιαν]{.greek-omitted} [εν]{.greek-omitted} [δυναμει]{.greek-omitted}[[9:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων [οιτινες]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [γευσωνται]{.greek-omitted} [θανατου]{.greek-omitted} [εως]{.greek-omitted} [αν]{.greek-omitted} [ιδωσιν]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} εληλυθυιαν εν δυναμει[[9:1 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και ιωαννην [και]{.greek-omitted} [αναφερει]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [ορος]{.greek-omitted} [υψηλον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [μονους]{.greek-omitted} [και]{.greek-omitted} [μετεμορφωθη]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [αυτων]{.greek-omitted}[9:2]{.aside}

[και]{.greek-omitted} [μεθ]{.greek-omitted} [ημερας]{.greek-omitted} [εξ]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τον]{.greek-omitted} [πετρον]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [ιακωβον]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2 | instance no. 2]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [νεφελη]{.greek-omitted} [επισκιαζουσα]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [ηλθεν]{.greek-omitted} [φωνη]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [νεφελης]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [μου]{.greek-omitted} [ο]{.greek-omitted} [αγαπητος]{.greek-omitted} αυτου ακουετε[[9:7 *(lacunose)*]{.lacunose}]{.aside}

και [εξαπεινα]{.greek-added} [εξαπινα]{.corr} περιβλεψαμενοι ουκετι ουδενα [ειδον]{.greek-omitted} [αλλα]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [μονον]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted}[[9:8 *(lacunose)*]{.lacunose}]{.aside}

[καταβαινοντων]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ορους]{.greek-omitted} [διεστειλατο]{.greek-omitted} [αυτοις]{.greek-omitted} [ινα]{.greek-omitted} [μηδενι]{.greek-omitted} [διηγησωνται]{.greek-omitted} [α]{.greek-omitted} [ειδον]{.greek-omitted} ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[[9:9 *(lacunose)*]{.lacunose}]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις [οτι]{.greek-omitted} [ηλιαν]{.greek-omitted} [δει]{.greek-omitted} [ελθειν]{.greek-omitted} [πρωτον]{.greek-omitted}[[9:11 *(lacunose)*]{.lacunose}]{.aside}

[αλλα]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [ηλιας]{.greek-omitted} [εληλυθεν]{.greek-omitted} [και]{.greek-omitted} [εποιησαν]{.greek-omitted} [αυτω]{.greek-omitted} οσα ηθελησαν καθως γεγραπται επ αυτον[[9:13 *(lacunose)*]{.lacunose}]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον πολυν περι [αυτους]{.greek-omitted} [και]{.greek-omitted} [γραμματεις]{.greek-omitted} [συζητουντας]{.greek-omitted} [αυτοις]{.greek-omitted}[[9:14 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [ιδων]{.greek-omitted} [αυτον]{.greek-omitted} [εξεθαμβηθη]{.greek-omitted} και προστρεχοντες ησπαζοντο αυτον[[9:15 *(lacunose)*]{.lacunose}]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησαν]{.greek-added} τους γραμματεις τι [συζητειτε]{.greek-omitted} [[σ]{.unclear}υνζητειτε]{.greek-added} [προς]{.greek-omitted} [αυτους]{.greek-omitted}[[9:16 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [κρατησας]{.greek-omitted} [αυτον]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} ηγειρεν αυτον και ανεστη[[9:27 *(lacunose)*]{.lacunose}]{.aside}

και [εισελθοντα]{.greek-omitted} [ελθοντα]{.greek-added} αυτον εις οικον οι μαθηται αυτου επηρωτων [αυτον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [οτι]{.greek-omitted} [ημεις]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθημεν]{.greek-omitted} [εκβαλειν]{.greek-omitted} [αυτο]{.greek-omitted}[[9:28 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τουτο]{.greek-omitted} [το]{.greek-omitted} [γενος]{.greek-omitted} [εν]{.greek-omitted} [ουδενι]{.greek-omitted} [δυναται]{.greek-omitted} [εξελθειν]{.greek-omitted} ει μη εν προσευχη και νηστεια[[9:29 *(lacunose)*]{.lacunose}]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της [μελ]{.greek-added} [γαλιλαιας]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηθελεν]{.greek-omitted} [ινα]{.greek-omitted} [τις]{.greek-omitted} [γνω]{.greek-omitted}[[9:30 *(lacunose)*]{.lacunose}]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ηγνοουν]{.greek-omitted} [το]{.greek-omitted} [ρημα]{.greek-omitted} και [εφοβουντο]{.greek-omitted} [εφοβουν]{.greek-added} αυτον επερωτησαι[[9:32 *(lacunose)*]{.lacunose}]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος [επηρωτα]{.greek-omitted} [αυτους]{.greek-omitted} [τι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [διελογιζεσθε]{.greek-omitted}[[9:33 *(lacunose)*]{.lacunose}]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [εσιωπων]{.greek-omitted} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [γαρ]{.greek-omitted} [διελεχθησαν]{.greek-omitted} εν τη οδω τις μειζων[[9:34 *(lacunose)*]{.lacunose}]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις [ει]{.greek-omitted} [τις]{.greek-omitted} [θελει]{.greek-omitted} [πρωτος]{.greek-omitted} [ειναι]{.greek-omitted} [εσται]{.greek-omitted} [παντων]{.greek-omitted} [εσχατος]{.greek-omitted} [και]{.greek-omitted} [παντων]{.greek-omitted} [διακονος]{.greek-omitted}[[9:35 *(lacunose)*]{.lacunose}]{.aside}

[ος]{.greek-omitted} [εαν]{.greek-omitted} [εν]{.greek-omitted} [των]{.greek-omitted} [τοιουτων]{.greek-omitted} [παιδιων]{.greek-omitted} [δεξηται]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [εμε]{.greek-omitted} [δεχεται]{.greek-omitted} [και]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [εμε]{.greek-omitted} [δεξηται]{.greek-omitted} [ουκ]{.greek-omitted} [εμε]{.greek-omitted} [δεχεται]{.greek-omitted} αλλα τον αποστειλαντα με[[9:37 *(lacunose)*]{.lacunose}]{.aside}

απεκριθη δε αυτω [ο]{.greek-added} ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [τινα]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [σου]{.greek-omitted} [εκβαλλοντα]{.greek-omitted} [δαιμονια]{.greek-omitted} [ος]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[[9:38 *(lacunose)*]{.lacunose}]{.aside}

ος γαρ ουκ εστιν καθ υμων υπερ [ημων]{.greek-added} [υμων]{.corr} εστιν[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν ονοματι [μου]{.greek-omitted} [οτι]{.greek-omitted} [χριστου]{.greek-omitted} [εστε]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} ου μη απολεση τον μισθον αυτου[[9:41 *(lacunose)*]{.lacunose}]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων [εις]{.greek-omitted} [εμε]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [αυτω]{.greek-omitted} [μαλλον]{.greek-omitted} [ει]{.greek-omitted} [περικειται]{.greek-omitted} [λιθος]{.greek-omitted} [μυλικος]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [τραχηλον]{.greek-omitted} [αυτου]{.greek-omitted} και βεβληται εις την θαλασσαν[[9:42 *(lacunose)*]{.lacunose}]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην [καλον]{.greek-omitted} [σοι]{.greek-omitted} [εστιν]{.greek-omitted} [κυλλον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ζωην]{.greek-omitted} [εισελθειν]{.greek-omitted} [η]{.greek-omitted} [τας]{.greek-omitted} [δυο]{.greek-omitted} [χειρας]{.greek-omitted} [εχοντα]{.greek-omitted} [απελθειν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γεενναν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [το]{.greek-omitted} [ασβεστον]{.greek-omitted}[[9:43 *(lacunose)*]{.lacunose}]{.aside}

[πας]{.greek-omitted} [γαρ]{.greek-omitted} [πυρι]{.greek-omitted} [αλισθησεται]{.greek-omitted} και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται [εν]{.greek-omitted} [τινι]{.greek-omitted} [αυτο]{.greek-omitted} [αρτυσετε]{.greek-omitted} [εχετε]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} [αλας]{.greek-omitted} και ειρηνευετε εν αλληλοις[[9:50 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας [δια]{.greek-omitted} [του]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} [και]{.greek-omitted} [συμπορευονται]{.greek-omitted} [παλιν]{.greek-omitted} [οχλοι]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} ειωθει παλιν εδιδασκεν αυτους[[10:1 *(lacunose)*]{.lacunose}]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι [επηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted} [ει]{.greek-omitted} [εξεστιν]{.greek-omitted} [ανδρι]{.greek-omitted} [γυναικα]{.greek-omitted} [απολυσαι]{.greek-omitted} πειραζοντες αυτον[[10:2 *(lacunose)*]{.lacunose}]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted}[[10:3 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [ους]{.greek-added} ουν ο [θεος]{.greek-abbr} [συνεζευξεν]{.greek-omitted} [εζευξεν]{.greek-added} [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted}[[10:10 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [γυνη]{.greek-omitted} [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον ανδρα αυτης και [γαμηθη]{.greek-omitted} [γαμησει]{.greek-added} αλλω μοιχαται[[10:12 *(lacunose)*]{.lacunose}]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων [οι]{.greek-omitted} [δε]{.greek-omitted} [μαθηται]{.greek-omitted} [επετιμων]{.greek-omitted} [τοις]{.greek-omitted} [προσφερουσιν]{.greek-omitted}[[10:13 *(lacunose)*]{.lacunose}]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ηγανακτησεν]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αφετε]{.greek-omitted} [τα]{.greek-omitted} [παιδια]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted} [μη]{.greek-omitted} [κωλυετε]{.greek-omitted} [αυτα]{.greek-omitted} των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[[10:14 *(lacunose)*]{.lacunose}]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} [ως]{.greek-omitted} [παιδιον]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [εισελθη]{.greek-omitted} [εις]{.greek-omitted} [αυτην]{.greek-omitted}[[10:15 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εναγκαλισαμενος]{.greek-omitted} [αυτα]{.greek-omitted} τιθεις τας χειρας επ αυτα ευλογει αυτα[[10:16 *(lacunose)*]{.lacunose}]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις [και]{.greek-omitted} [γονυπετησας]{.greek-omitted} [αυτον]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [διδασκαλε]{.greek-omitted} [αγαθε]{.greek-omitted} [τι]{.greek-omitted} [ποιησω]{.greek-omitted} [ινα]{.greek-omitted} [ζωην]{.greek-omitted} [αιωνιον]{.greek-omitted} [κληρονομησω]{.greek-omitted}[[10:17 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[[10:20 *(lacunose)*]{.lacunose}]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω [ηγαπησεν]{.greek-omitted} [ηγαπα]{.greek-added} αυτον και ειπεν αυτω εν σοι υστερει υπαγε οσα εχεις [πωλησον]{.greek-omitted} [και]{.greek-omitted} [δος]{.greek-omitted} [πτωχοις]{.greek-omitted} [και]{.greek-omitted} [εξεις]{.greek-omitted} [θησαυρον]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [δευρο]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [αρας]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted}[[10:21 *(lacunose)*]{.lacunose}]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου [πως]{.greek-omitted} [δυσκολως]{.greek-omitted} [οι]{.greek-omitted} [τα]{.greek-omitted} [χρηματα]{.greek-omitted} [εχοντες]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισελευσονται]{.greek-omitted}[[10:23 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγει]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν [του]{.greek-omitted} [θεου]{.greek-omitted} [εισελευσονται]{.greek-omitted}[[10:23 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [περισσως]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} και τις δυναται σωθηναι[[10:26 *(lacunose)*]{.lacunose}]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} [αδυνατον]{.greek-omitted} [αλλ]{.greek-omitted} [ου]{.greek-omitted} [παρα]{.greek-omitted} [θεω]{.greek-omitted} [παντα]{.greek-omitted} [γαρ]{.greek-omitted} δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[[10:27 *(lacunose)*]{.lacunose}]{.aside}

ηρξατο ο πετρος λεγειν αυτω ιδου [ημεις]{.greek-omitted} [αφηκαμεν]{.greek-omitted} [παντα]{.greek-omitted} [και]{.greek-omitted} [ηκολουθησαμεν]{.greek-omitted} [σοι]{.greek-omitted}[[10:28 *(lacunose)*]{.lacunose}]{.aside}

[εαν]{.greek-omitted} [μη]{.greek-omitted} [λαβη]{.greek-omitted} [εκατονταπλασιονα]{.greek-omitted} [νυν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [καιρω]{.greek-omitted} [τουτω]{.greek-omitted} [οικιας]{.greek-omitted} [και]{.greek-omitted} [αδελφους]{.greek-omitted} [και]{.greek-omitted} [αδελφας]{.greek-omitted} [και]{.greek-omitted} [μητερας]{.greek-omitted} [και]{.greek-omitted} [τεκνα]{.greek-omitted} [και]{.greek-omitted} [αγρους]{.greek-omitted} [μετα]{.greek-omitted} [διωγμων]{.greek-omitted} και εν τω αιωνι τω ερχομενω ζωην αιωνιον[[10:30 *(lacunose)*]{.lacunose}]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [προαγων]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εθαμβουντο]{.greek-omitted} [και]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} [παραλαβων]{.greek-omitted} [παλιν]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγειν]{.greek-omitted} [τα]{.greek-omitted} [μελλοντα]{.greek-omitted} [αυτω]{.greek-omitted} [συμβαινειν]{.greek-omitted}[[10:32 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εμπαιξουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αυτον]{.greek-omitted} και τη τριτη ημερα αναστησεται[[10:34 *(lacunose)*]{.lacunose}]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι [ζεβεδαιου]{.greek-omitted} [λεγοντες]{.greek-omitted} [διδασκαλε]{.greek-omitted} [θελομεν]{.greek-omitted} [ινα]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [αιτησωμεν]{.greek-omitted} [ποιησης]{.greek-omitted} [ημιν]{.greek-omitted}[[10:35 *(lacunose)*]{.lacunose}]{.aside}

[το]{.greek-omitted} [δε]{.greek-omitted} [καθισαι]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ευωνυμων]{.greek-omitted} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[[10:40 *(lacunose)*]{.lacunose}]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [ιωαννου]{.greek-omitted}[[10:41 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ουκ]{.greek-omitted} [ηλθεν]{.greek-omitted} [διακονηθηναι]{.greek-omitted} [αλλα]{.greek-omitted} [διακονησαι]{.greek-omitted} και δουναι την ψυχην αυτου λυτρον αντι πολλων[[10:45 *(lacunose)*]{.lacunose}]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο [ιεριχω]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [οχλου]{.greek-omitted} [ικανου]{.greek-omitted} [υιος]{.greek-omitted} [τιμαιου]{.greek-omitted} [βαρτιμαιος]{.greek-omitted} [ο]{.greek-omitted} [τυφλος]{.greek-omitted} [εκαθητο]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [προσαιτων]{.greek-omitted}[[10:46 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} τι θελεις ποιησω σοι ο δε τυφλος ειπεν αυτω [ραββουνι]{.greek-omitted} [ινα]{.greek-omitted} [αναβλεψω]{.greek-omitted}[[10:51 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [υπαγε]{.greek-omitted} [η]{.greek-omitted} [πιστις]{.greek-omitted} [σου]{.greek-omitted} [σεσωκεν]{.greek-omitted} [σε]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [ανεβλεψεν]{.greek-omitted} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[[10:52 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} [εις]{.greek-omitted} [βηθσφαγη]{.greek-omitted} [και]{.greek-omitted} [βηθανιαν]{.greek-omitted} [προς]{.greek-omitted} [το]{.greek-omitted} [ορος]{.greek-omitted} [των]{.greek-omitted} [ελαιων]{.greek-omitted} [αποστελλει]{.greek-omitted} [δυο]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted}[[11:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [τις]{.greek-omitted} [υμιν]{.greek-omitted} [ειπη]{.greek-omitted} [τι]{.greek-omitted} [ποιειτε]{.greek-omitted} [τουτο]{.greek-omitted} [ειπατε]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [αυτου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχει]{.greek-omitted} και ευθεως αυτον αποστελλει ωδε[[11:3 *(lacunose)*]{.lacunose}]{.aside}

απηλθον δε και [ευρον]{.greek-omitted} [ευρεν]{.greek-added} πωλον δεδεμενον προς την θυραν [εξω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [αμφοδου]{.greek-omitted} [και]{.greek-omitted} [λυουσιν]{.greek-omitted} [αυτον]{.greek-omitted}[[11:4 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ηγαγον]{.greek-omitted} [τον]{.greek-omitted} [πωλον]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} και επεβαλον αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτα]{.greek-added}[[11:7 *(lacunose)*]{.lacunose}]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [εκοπτον]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [δενδρων]{.greek-omitted} [και]{.greek-omitted} [εστρωννυον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted}[[11:8 *(lacunose)*]{.lacunose}]{.aside}

[ευλογημενη]{.greek-omitted} [η]{.greek-omitted} [ερχομενη]{.greek-omitted} [βασιλεια]{.greek-omitted} [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [ημων]{.greek-omitted} [δαυιδ]{.greek-omitted} ωσαννα εν τοις υψιστοις[[11:10 *(lacunose)*]{.lacunose}]{.aside}

και εισηλθεν εις ιεροσολυμα [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [παντα]{.greek-omitted} [οψιας]{.greek-omitted} [ηδη]{.greek-omitted} [ουσης]{.greek-omitted} [της]{.greek-omitted} [ωρας]{.greek-omitted} [εξηλθεν]{.greek-omitted} εις βηθανιαν μετα των [δωδεκα]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[[11:11 *(lacunose)*]{.lacunose}]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted}[[11:12 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} [μηκετι]{.greek-omitted} [εκ]{.greek-omitted} [σου]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [αιωνα]{.greek-omitted} [μηδεις]{.greek-omitted} [καρπον]{.greek-omitted} [φαγοι]{.greek-omitted} και ηκουον οι μαθηται αυτου[[11:14 *(lacunose)*]{.lacunose}]{.aside}

και ερχονται εις ιεροσολυμα [και]{.greek-omitted} [εισελθων]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκβαλλειν]{.greek-omitted} [τους]{.greek-omitted} [πωλουντας]{.greek-omitted} [και]{.greek-omitted} [αγοραζοντας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [τραπεζας]{.greek-omitted} [των]{.greek-omitted} [κολλυβιστων]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [καθεδρας]{.greek-omitted} [των]{.greek-omitted} [πωλουντων]{.greek-omitted} [τας]{.greek-omitted} [περιστερας]{.greek-omitted} [κατεστρεψεν]{.greek-omitted}[[11:15 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [λεγων]{.greek-omitted} [αυτοις]{.greek-omitted} [ου]{.greek-omitted} [γεγραπται]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [οικος]{.greek-omitted} [μου]{.greek-omitted} [οικος]{.greek-omitted} [προσευχης]{.greek-omitted} [κληθησεται]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted} υμεις δε εποιησατε αυτον [σπηλαον]{.greek-added} [σπηλαιον]{.corr} ληστων[[11:17 *(lacunose)*]{.lacunose}]{.aside}

και ηκουσαν οι γραμματεις [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [εζητουν]{.greek-omitted} [πως]{.greek-omitted} [αυτον]{.greek-omitted} [απολεσωσιν]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} εξεπλησσετο επι τη διδαχη αυτου[[11:18 *(lacunose)*]{.lacunose}]{.aside}

και οτε [οψε]{.greek-omitted} [οψαι]{.greek-added} [εγενετο]{.greek-omitted} [εγινετο]{.greek-added} εξεπορευετο εξω της πολεως[11:19]{.aside}

[αμην]{.greek-omitted} [γαρ]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [ος]{.greek-omitted} [αν]{.greek-omitted} [ειπη]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} [τουτω]{.greek-omitted} [αρθητι]{.greek-omitted} [και]{.greek-omitted} [βληθητι]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [διακριθη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [καρδια]{.greek-omitted} [αυτου]{.greek-omitted} [αλλα]{.greek-omitted} [πιστευση]{.greek-omitted} [οτι]{.greek-omitted} [α]{.greek-omitted} [λεγει]{.greek-omitted} [γινεται]{.greek-omitted} εσται αυτω ο εαν ειπη[[11:23 *(lacunose)*]{.lacunose}]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [πιστευετε]{.greek-omitted} [οτι]{.greek-omitted} [λαμβανετε]{.greek-omitted} [και]{.greek-omitted} [εσται]{.greek-omitted} [υμιν]{.greek-omitted}[[11:24 *(lacunose)*]{.lacunose}]{.aside}

[αφησει]{.greek-added} [και]{.greek-omitted} [οταν]{.greek-omitted} [στηκητε]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [αφιετε]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} [εχετε]{.greek-omitted} [κατα]{.greek-omitted} [τινος]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} τα παραπτωματα υμων[[11:25 *(lacunose)*]{.lacunose}]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω [περιπατουντος]{.greek-omitted} [αυτου]{.greek-omitted} [ερχονται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted}[[11:27 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [επερωτησω]{.greek-omitted} [υμας]{.greek-omitted} [και]{.greek-omitted} [εγω]{.greek-omitted} [ενα]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [αποκριθητε]{.greek-omitted} [μοι]{.greek-omitted} και ερω υμιν εν ποια εξουσια ταυτα ποιω[[11:29 *(lacunose)*]{.lacunose}]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε [μοι]{.greek-omitted}[[11:30 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [αποκριθεντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [ουκ]{.greek-omitted} [οιδαμεν]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[[11:33 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 12

και ηρξατο αυτοις [εν]{.greek-omitted} [εμ]{.greek-added} παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-omitted} [και]{.greek-omitted} [περιεθηκεν]{.greek-omitted} [φραγμον]{.greek-omitted} [και]{.greek-omitted} [ωρυξεν]{.greek-omitted} [υποληνιον]{.greek-omitted} [και]{.greek-omitted} [ωκοδομησεν]{.greek-omitted} [πυργον]{.greek-omitted} [και]{.greek-omitted} [εξεδοτο]{.greek-omitted} [αυτον]{.greek-omitted} [γεωργοις]{.greek-omitted} [και]{.greek-omitted} [απεδημησεν]{.greek-omitted}[[12:1 *(lacunose)*]{.lacunose}]{.aside}

ουδε την γραφην ταυτην ανεγνωτε [λιθον]{.greek-omitted} [ον]{.greek-omitted} [απεδοκιμασαν]{.greek-omitted} [οι]{.greek-omitted} [οικοδομουντες]{.greek-omitted} [ουτος]{.greek-omitted} [εγενηθη]{.greek-omitted} [εις]{.greek-omitted} [κεφαλην]{.greek-omitted} [γωνιας]{.greek-omitted}[[12:10 *(lacunose)*]{.lacunose}]{.aside}

[ουδε]{.greek-omitted} [την]{.greek-omitted} [γραφην]{.greek-omitted} [ταυτην]{.greek-omitted} [ανεγνωτε]{.greek-omitted} λιθον ον απεδοκιμασαν οι οικοδομουντες [ουτος]{.greek-omitted} [εγενηθη]{.greek-omitted} [εις]{.greek-omitted} [κεφαλην]{.greek-omitted} [γωνιας]{.greek-omitted}[[12:10 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εζητουν]{.greek-omitted} [αυτον]{.greek-omitted} [κρατησαι]{.greek-omitted} [και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [εγνωσαν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [ειπεν]{.greek-omitted} και αφεντες αυτον απηλθον[[12:12 *(lacunose)*]{.lacunose}]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων [και]{.greek-omitted} [των]{.greek-omitted} [ηρωδιανων]{.greek-omitted} [ινα]{.greek-omitted} [αυτον]{.greek-omitted} [αγρευσωσιν]{.greek-omitted} [λογω]{.greek-omitted}[[12:13 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αποδοτε]{.greek-omitted} [τα]{.greek-omitted} [καισαρος]{.greek-omitted} [καισαρι]{.greek-omitted} και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[[12:17 *(lacunose)*]{.lacunose}]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν [αναστασιν]{.greek-omitted} [μη]{.greek-omitted} [ειναι]{.greek-omitted} [και]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγοντες]{.greek-omitted}[[12:18 *(lacunose)*]{.lacunose}]{.aside}

[ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [νεκρων]{.greek-omitted} [αλλα]{.greek-omitted} [θεος]{.greek-omitted} [ζωντων]{.greek-omitted} υμεις ουν πολυ [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added}[[12:27 *(lacunose)*]{.lacunose}]{.aside}

και προσελθων εις των γραμματεων ακουσας [αυτων]{.greek-omitted} [συζητουντων]{.greek-omitted} [ειδως]{.greek-omitted} [οτι]{.greek-omitted} [καλως]{.greek-omitted} [αυτοις]{.greek-omitted} [απεκριθη]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [αυτου]{.greek-added} [ποια]{.greek-omitted} [εστιν]{.greek-omitted} [πρωτη]{.greek-omitted} [παντων]{.greek-omitted} [εντολη]{.greek-omitted}[[12:28 *(lacunose)*]{.lacunose}]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω ιερω [πως]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [υιος]{.greek-omitted} [εστιν]{.greek-omitted} [δαυιδ]{.greek-omitted}[12:35]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ελεγεν]{.greek-omitted} [διδασκων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35 | instance no. 3]{.aside}

[αυτος]{.greek-omitted} [ουν]{.greek-omitted} [δαυιδ]{.greek-omitted} [λεγει]{.greek-omitted} [αυτον]{.greek-omitted} [κυριον]{.greek-omitted} [και]{.greek-omitted} [ποθεν]{.greek-omitted} [υιος]{.greek-omitted} [αυτου]{.greek-omitted} [εστιν]{.greek-omitted} και ο πολυς οχλος ηκουεν αυτου ηδεως[[12:37 *(lacunose)*]{.lacunose}]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των [γραμματεων]{.greek-omitted} [των]{.greek-omitted} [θελοντων]{.greek-omitted} [εν]{.greek-omitted} [στολαις]{.greek-omitted} [περιπατειν]{.greek-omitted} [και]{.greek-omitted} [ασπασμους]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [αγοραις]{.greek-omitted}[[12:38 *(lacunose)*]{.lacunose}]{.aside}

[οι]{.greek-omitted} [κατεσθιοντες]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [των]{.greek-omitted} [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} ουτοι ληψονται περισσοτερον κριμα[[12:40 *(lacunose)*]{.lacunose}]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του [γαζοφυλακιου]{.greek-omitted} [γαζοφυλακειου]{.greek-added} εθεωρει [πως]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [βαλλει]{.greek-omitted} [χαλκον]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [γαζοφυλακιον]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [πλουσιοι]{.greek-omitted} [εβαλλον]{.greek-omitted} [πολλα]{.greek-omitted}[[12:41 *(lacunose)*]{.lacunose}]{.aside}

[παντες]{.greek-omitted} [γαρ]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [περισσευοντος]{.greek-omitted} [αυτοις]{.greek-omitted} [εβαλον]{.greek-omitted} [αυτη]{.greek-omitted} [δε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [υστερησεως]{.greek-omitted} [αυτης]{.greek-omitted} [παντα]{.greek-omitted} [οσα]{.greek-omitted} [ειχεν]{.greek-omitted} εβαλεν ολον τον βιον αυτης[[12:44 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ιδε]{.greek-omitted} [ποταποι]{.greek-omitted} [λιθοι]{.greek-omitted} [και]{.greek-omitted} [ποταπαι]{.greek-omitted} [οικοδομαι]{.greek-omitted}[[13:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [βλεπεις]{.greek-omitted} [ταυτας]{.greek-omitted} [τας]{.greek-omitted} [μεγαλας]{.greek-omitted} [οικοδομας]{.greek-omitted} ου μη αφεθη λιθος επι λιθω ος [ου]{.greek-omitted} μη καταλυθη[[13:2 *(lacunose)*]{.lacunose}]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι [του]{.greek-omitted} [ιερου]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [πετρος]{.greek-omitted} [και]{.greek-omitted} [ιακωβος]{.greek-omitted} [και]{.greek-omitted} [ιωαννης]{.greek-omitted} [και]{.greek-omitted} [ανδρεας]{.greek-omitted}[[13:3 *(lacunose)*]{.lacunose}]{.aside}

[ειπε]{.greek-omitted} [ημιν]{.greek-omitted} [ποτε]{.greek-omitted} [ταυτα]{.greek-omitted} [εσται]{.greek-omitted} [και]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [σημειον]{.greek-omitted} οταν μελλη παντα ταυτα συντελεισθαι[[13:4 *(lacunose)*]{.lacunose}]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν [βλεπετε]{.greek-omitted} [μη]{.greek-omitted} [τις]{.greek-omitted} [υμας]{.greek-omitted} [πλανηση]{.greek-omitted}[[13:5 *(lacunose)*]{.lacunose}]{.aside}

[εγερθησεται]{.greek-omitted} [γαρ]{.greek-omitted} [εθνος]{.greek-omitted} [επι]{.greek-omitted} [εθνος]{.greek-omitted} [και]{.greek-omitted} [βασιλεια]{.greek-omitted} [επι]{.greek-omitted} [βασιλειαν]{.greek-omitted} [και]{.greek-omitted} [εσονται]{.greek-omitted} [σεισμοι]{.greek-omitted} [κατα]{.greek-omitted} [τοπους]{.greek-omitted} και εσονται λιμοι και ταραχαι αρχαι ωδινων ταυτα[[13:8 *(lacunose)*]{.lacunose}]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας [εις]{.greek-omitted} [συνεδρια]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [συναγωγας]{.greek-omitted} [δαρησεσθε]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [ηγεμονων]{.greek-omitted} [και]{.greek-omitted} [βασιλεων]{.greek-omitted} [σταθησεσθε]{.greek-omitted} ενεκεν εμου εις μαρτυριον αυτοις[[13:9 *(lacunose)*]{.lacunose}]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε αγαγωσιν υμας παραδιδοντες [μη]{.greek-omitted} [προμεριμνατε]{.greek-omitted} τι [προμεριμναται]{.greek-added} [λαλησητε]{.greek-omitted} [μηδε]{.greek-omitted} [μελετατε]{.greek-omitted} [αλλ]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [δοθη]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [τουτο]{.greek-omitted} [λαλειτε]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [εστε]{.greek-omitted} [υμεις]{.greek-omitted} [οι]{.greek-omitted} [λαλουντες]{.greek-omitted} [αλλα]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αγιον]{.greek-omitted}[[13:11 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εσεσθε]{.greek-omitted} [μισουμενοι]{.greek-omitted} [υπο]{.greek-omitted} [παντων]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} ο δε υπομεινας εις τελος ουτος σωθησεται[[13:13 *(lacunose)*]{.lacunose}]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως το ρηθεν [υπο]{.greek-omitted} [δανιηλ]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [εστως]{.greek-omitted} [οπου]{.greek-omitted} [ου]{.greek-omitted} [δει]{.greek-omitted} [ο]{.greek-omitted} [αναγινωσκων]{.greek-omitted} [νοειτω]{.greek-omitted} [τοτε]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ιουδαια]{.greek-omitted} [φευγετωσαν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορη]{.greek-omitted}[[13:14 *(lacunose)*]{.lacunose}]{.aside}

[αρα]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [αγρον]{.greek-omitted} [ων]{.greek-omitted} [μη]{.greek-omitted} [επιστρεψατω]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [οπισω]{.greek-omitted} [αραι]{.corr} το ιματιον αυτου[[13:16 *(lacunose)*]{.lacunose}]{.aside}

ουαι δε ταις εν γαστρι εχουσαις [και]{.greek-omitted} [ταις]{.greek-omitted} [θηλαζουσαις]{.greek-omitted} [εν]{.greek-omitted} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted}[[13:17 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [κυριος]{.greek-omitted} [εκολοβωσεν]{.greek-omitted} [τας]{.greek-omitted} [ημερας]{.greek-omitted} [ουκ]{.greek-omitted} [αν]{.greek-omitted} [εσωθη]{.greek-omitted} [πασα]{.greek-omitted} [σαρξ]{.greek-omitted} [αλλα]{.greek-omitted} [δια]{.greek-omitted} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted} ους εξελεξατο εκολοβωσεν τας ημερας[[13:20 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη πιστευετε[13:21]{.aside}

[υμεις]{.greek-omitted} [δε]{.greek-omitted} [βλεπετε]{.greek-omitted} ιδου προειρηκα υμιν παντα[[13:23 *(lacunose)*]{.lacunose}]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [σκοτισθησεται]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [ου]{.greek-omitted} [δωσει]{.greek-omitted} [το]{.greek-omitted} [φεγγος]{.greek-omitted} [αυτης]{.greek-omitted}[[13:24 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [τοτε]{.greek-omitted} [αποστελει]{.greek-omitted} [τους]{.greek-omitted} [αγγελους]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [επισυναξει]{.greek-omitted} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted} [αυτου]{.greek-omitted} εκ των [τεσσαρων]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[[13:27 *(lacunose)*]{.lacunose}]{.aside}

απο δε της συκης μαθετε την παραβολην [οταν]{.greek-omitted} [αυτης]{.greek-omitted} [ηδη]{.greek-omitted} [ο]{.greek-omitted} [κλαδος]{.greek-omitted} [απαλος]{.greek-omitted} [γενηται]{.greek-omitted} [και]{.greek-omitted} [εκφυη]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [γινωσκετε]{.greek-omitted} [οτι]{.greek-omitted} [εγγυς]{.greek-omitted} [το]{.greek-omitted} [θερος]{.greek-omitted} [εστιν]{.greek-omitted}[[13:28 *(lacunose)*]{.lacunose}]{.aside}

[ουτως]{.greek-omitted} [και]{.greek-omitted} [υμεις]{.greek-omitted} [οταν]{.greek-omitted} [ταυτα]{.greek-omitted} [ιδητε]{.greek-omitted} [γινομενα]{.greek-omitted} γινωσκετε οτι εγγυς εστιν επι θυραις[[13:29 *(lacunose)*]{.lacunose}]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [ου]{.greek-omitted} [παντα]{.greek-omitted} [ταυτα]{.greek-omitted} [γενηται]{.greek-omitted}[[13:30 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [ουρανος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [παρελευσεται]{.greek-omitted} οι δε λογοι μου ου μη παρελθωσιν[[13:31 *(lacunose)*]{.lacunose}]{.aside}

περι δε της ημερας εκεινης η ωρας ουδεις οιδεν ουδε οι αγγελοι [οι]{.greek-omitted} εν ουρανω [ουδε]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted}[13:32]{.aside}

[περι]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} [η]{.greek-omitted} [ωρας]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ουδε]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32 | instance no. 2]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους [τοις]{.greek-omitted} [δουλοις]{.greek-omitted} [αυτου]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [και]{.greek-omitted} [εκαστω]{.greek-omitted} [το]{.greek-omitted} [εργον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [θυρωρω]{.greek-omitted} [ενετειλατο]{.greek-omitted} [ινα]{.greek-omitted} [γρηγορη]{.greek-omitted}[[13:34 *(lacunose)*]{.lacunose}]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [πως]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [δολω]{.greek-omitted} [κρατησαντες]{.greek-omitted} [αποκτεινωσιν]{.greek-omitted}[[14:1 *(lacunose)*]{.lacunose}]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οπου]{.greek-omitted} [εαν]{.greek-omitted} [κηρυχθη]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [τουτο]{.greek-omitted} [εις]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [κοσμον]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [εποιησεν]{.greek-omitted} [αυτη]{.greek-omitted} λαληθησεται εις μνημοσυνον αυτης[[14:9 *(lacunose)*]{.lacunose}]{.aside}

και ο ιουδας ο ισκαριωτης εις των [[ιβ]{.greek-abbr}]{.greek-added} [δωδεκα]{.greek-omitted} [απηλθεν]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [αρχιερεις]{.greek-omitted} [ινα]{.greek-omitted} [παραδω]{.greek-omitted} [αυτον]{.greek-omitted} [αυτοις]{.greek-omitted}[[14:10 *(lacunose)*]{.lacunose}]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ακουσαντες]{.greek-omitted} [εχαρησαν]{.greek-omitted} [και]{.greek-omitted} [επηγγειλαντο]{.greek-omitted} [αυτω]{.greek-omitted} [αργυριον]{.greek-omitted} [δουναι]{.greek-omitted} και εζητει πως [ευσαιρως]{.greek-added} [ευκαιρως]{.corr} αυτον παραδω[[14:11 *(lacunose)*]{.lacunose}]{.aside}

και τη πρωτη ημερα των αζυμων [οτε]{.greek-omitted} [το]{.greek-omitted} [πασχα]{.greek-omitted} [εθυον]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [που]{.greek-omitted} [θελεις]{.greek-omitted} [απελθοντες]{.greek-omitted} [ετοιμασωμεν]{.greek-omitted} [ινα]{.greek-omitted} [φαγης]{.greek-omitted} [το]{.greek-omitted} [πασχα]{.greek-omitted}[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις [υπαγετε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [απαντησει]{.greek-omitted} [υμιν]{.greek-omitted} [ανθρωπος]{.greek-omitted} [κεραμιον]{.greek-omitted} [υδατος]{.greek-omitted} [βασταζων]{.greek-omitted} [ακολουθησατε]{.greek-omitted} [αυτω]{.greek-omitted}[[14:13 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εξηλθον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [ευρον]{.greek-omitted} [καθως]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} και ητοιμασαν το πασχα[[14:16 *(lacunose)*]{.lacunose}]{.aside}

και οψιας γενομενης ερχεται μετα των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[14:17]{.aside}

και ανακειμενων [αυτων]{.greek-omitted} [και]{.greek-omitted} [εσθιοντων]{.greek-omitted} [ειπεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [εις]{.greek-omitted} [εξ]{.greek-omitted} [υμων]{.greek-omitted} [παραδωσει]{.greek-omitted} [με]{.greek-omitted} [ο]{.greek-omitted} [εσθιων]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted}[[14:18 *(lacunose)*]{.lacunose}]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ηρξαντο]{.greek-omitted} [λυπεισθαι]{.greek-omitted} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} [εις]{.greek-omitted} [καθ]{.greek-omitted} [εις]{.greek-omitted} μητι εγω και αλλος μητι εγω[[14:19 *(lacunose)*]{.lacunose}]{.aside}

ο δε αποκριθεις ειπεν αυτοις [εις]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [ο]{.greek-omitted} [εμβαπτομενος]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [τρυβλιον]{.greek-omitted}[[14:20 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [μεν]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [υπαγει]{.greek-omitted} [καθως]{.greek-omitted} [γεγραπται]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted} [ουαι]{.greek-omitted} [δε]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [εκεινω]{.greek-omitted} [δι]{.greek-omitted} [ου]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδιδοται]{.greek-omitted} [καλον]{.greek-omitted} [ην]{.greek-omitted} [αυτω]{.greek-omitted} [ει]{.greek-omitted} ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[[14:21 *(lacunose)*]{.lacunose}]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [λαβετε]{.greek-omitted} [φαγετε]{.greek-omitted} [τουτο]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [μου]{.greek-omitted}[[14:22 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τουτο]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [αιμα]{.greek-omitted} [μου]{.greek-omitted} [το]{.greek-omitted} [της]{.greek-omitted} [καινης]{.greek-omitted} [διαθηκης]{.greek-omitted} το περι πολλων εκχυνομενον[[14:24 *(lacunose)*]{.lacunose}]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω [εκ]{.greek-omitted} [του]{.greek-omitted} [γενηματος]{.greek-omitted} [της]{.greek-omitted} [αμπελου]{.greek-omitted} [εως]{.greek-omitted} [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} οταν αυτο [πιννω]{.greek-added} [πινω]{.corr} [καινον]{.greek-omitted} [καινω]{.greek-added} εν τη βασιλεια [του]{.greek-omitted} [θεου]{.greek-omitted}[[14:25 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [υμνησαντες]{.greek-omitted} εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεσθαι]{.greek-added} [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω [τον]{.greek-omitted} [ποιμενα]{.greek-omitted} [και]{.greek-omitted} [διασκορπισθησεται]{.greek-omitted} [τα]{.greek-omitted} [προβατα]{.greek-omitted}[[14:27 *(lacunose)*]{.lacunose}]{.aside}

[αλλα]{.greek-omitted} [μετα]{.greek-omitted} [το]{.greek-omitted} [εγερθηναι]{.greek-omitted} [με]{.greek-omitted} προαξω υμας εις την γαλιλαιαν[[14:28 *(lacunose)*]{.lacunose}]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι [συ]{.greek-omitted} σημερον [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} [πριν]{.greek-omitted} [η]{.greek-omitted} [δις]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} [τρις]{.greek-omitted} [απαρνηση]{.greek-omitted} [με]{.greek-omitted}[[14:30 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εκπερισσου]{.greek-omitted} [ελεγεν]{.greek-omitted} [μαλλον]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} [σοι]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [σε]{.greek-omitted} [απαρνησωμαι]{.greek-omitted} ωσαυτως δε και παντες ελεγον[[14:31 *(lacunose)*]{.lacunose}]{.aside}

και ερχονται εις [χωριον]{.greek-omitted} [χωρειον]{.greek-added} ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [ωδε]{.greek-omitted} [εως]{.greek-omitted} [προσευξωμαι]{.greek-omitted}[[14:32 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αββα]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [παντα]{.greek-omitted} [δυνατα]{.greek-omitted} [σοι]{.greek-omitted} [παρενεγκε]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted} [τουτο]{.greek-omitted} αλλ ου τι εγω θελω αλλα τι [συ]{.greek-omitted} [σοι]{.greek-added}[[14:36 *(lacunose)*]{.lacunose}]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας [και]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [σιμων]{.greek-omitted} [καθευδεις]{.greek-omitted} [ουκ]{.greek-omitted} [ισχυσας]{.greek-omitted} [μιαν]{.greek-omitted} [ωραν]{.greek-omitted} [γρηγορησαι]{.greek-omitted}[[14:37 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [υποστρεψας]{.greek-omitted} [ευρεν]{.greek-omitted} [αυτους]{.greek-omitted} [παλιν]{.greek-omitted} [καθευδοντας]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [οφθαλμοι]{.greek-omitted} [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} και ουκ ηδεισαν τι αυτω αποκριθωσιν[[14:40 *(lacunose)*]{.lacunose}]{.aside}

και ερχεται το τριτον και λεγει αυτοις [καθευδετε]{.greek-omitted} [λοιπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [απεχει]{.greek-omitted} [ηλθεν]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted} [ιδου]{.greek-omitted} [παραδιδοται]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [των]{.greek-omitted} [αμαρτωλων]{.greek-omitted}[[14:41 *(lacunose)*]{.lacunose}]{.aside}

εγειρεσθε [αγωμεν]{.greek-omitted} [αγομεν]{.greek-added} [εντευθεν]{.greek-added} ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των δωδεκα και [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} μετα [ταυτα]{.greek-added} [μαχαιρων]{.greek-omitted} [και]{.greek-omitted} [ξυλων]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} [αρχιερεων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted}[[14:43 *(lacunose)*]{.lacunose}]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [επεβαλον]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [αυτων]{.greek-omitted} και εκρατησαν αυτον[[14:46 *(lacunose)*]{.lacunose}]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [τον]{.greek-omitted} [δουλον]{.greek-omitted} [του]{.greek-omitted} [αρχιερεως]{.greek-omitted} [και]{.greek-omitted} [αφειλεν]{.greek-omitted} [αυτου]{.greek-omitted} [το]{.greek-omitted} [ωτιον]{.greek-omitted}[[14:47 *(lacunose)*]{.lacunose}]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων [και]{.greek-omitted} [ξυλων]{.greek-omitted} [συλλαβειν]{.greek-omitted} [με]{.greek-omitted}[[14:48 *(lacunose)*]{.lacunose}]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα [επι]{.greek-omitted} [γυμνου]{.greek-omitted} [και]{.greek-omitted} [κρατουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[[14:51 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [καταλιπων]{.greek-omitted} [την]{.greek-omitted} [σινδονα]{.greek-omitted} γυμνος εφυγεν απ αυτων[[14:52 *(lacunose)*]{.lacunose}]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted}[[14:53 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εσιωπα]{.greek-omitted} [και]{.greek-omitted} [ουδεν]{.greek-omitted} [απεκρινατο]{.greek-omitted} [παλιν]{.greek-omitted} [ο]{.greek-omitted} [αρχιερευς]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[[14:61 *(lacunose)*]{.lacunose}]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων [καθημενον]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [και]{.greek-omitted} [ερχομενον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [νεφελων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[[14:62 *(lacunose)*]{.lacunose}]{.aside}

[ηκουσατε]{.greek-omitted} [της]{.greek-omitted} [βλασφημιας]{.greek-omitted} [τι]{.greek-omitted} [υμιν]{.greek-omitted} [φαινεται]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [παντες]{.greek-omitted} [κατεκριναν]{.greek-omitted} [αυτον]{.greek-omitted} ειναι ενοχον θανατου[[14:64 *(lacunose)*]{.lacunose}]{.aside}

και ηρξαντο τινες [εμπτυειν]{.greek-omitted} [διαπτυειν]{.greek-added} αυτω και περικαλυπτειν το προσωπον [αυτου]{.greek-omitted} [και]{.greek-omitted} [κολαφιζειν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} [προφητευσον]{.greek-omitted} και οι υπηρεται ραπισμασιν [ελαβον]{.greek-added} [αυτον]{.greek-omitted} [εβαλλον]{.greek-omitted}[[14:65 *(lacunose)*]{.lacunose}]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων [του]{.greek-omitted} [αρχιερεως]{.greek-omitted}[[14:66 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [δευτερου]{.greek-omitted} [αλεκτωρ]{.greek-omitted} [εφωνησεν]{.greek-omitted} [και]{.greek-omitted} [ανεμνησθη]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [το]{.greek-omitted} [ρημα]{.greek-omitted} [ο]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [πριν]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} [δις]{.greek-omitted} [απαρνηση]{.greek-omitted} [απαρνησει]{.greek-added} με τρις και επιβαλων εκλαιεν[[14:72 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων [και]{.greek-omitted} [γραμματεων]{.greek-omitted} [και]{.greek-omitted} [ολον]{.greek-omitted} [το]{.greek-omitted} [συνεδριον]{.greek-omitted} [δησαντες]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [απηνεγκαν]{.greek-omitted} [και]{.greek-omitted} [παρεδωκαν]{.greek-omitted} [τω]{.greek-omitted} [πιλατω]{.greek-omitted}[[15:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [αναβοησας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [ηρξατο]{.greek-omitted} [αιτεισθαι]{.greek-omitted} καθως αει εποιει αυτοις[[15:8 *(lacunose)*]{.lacunose}]{.aside}

ο δε [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [βουλομενος]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [το]{.greek-omitted} [ικανον]{.greek-omitted} [ποιησαι]{.greek-omitted} [απελυσεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τον]{.greek-omitted} [βαραββαν]{.greek-omitted} και παρεδωκεν τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγελωσας]{.greek-added} ινα [σταυρωθη]{.greek-abbr}[[15:15 *(lacunose)*]{.lacunose}]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον [και]{.greek-omitted} [συγκαλουσιν]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [σπειραν]{.greek-omitted}[[15:16 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [αγγαρευουσιν]{.greek-omitted} [παραγοντα]{.greek-omitted} [τινα]{.greek-omitted} [σιμωνα]{.greek-omitted} [κυρηναιον]{.greek-omitted} [ερχομενον]{.greek-omitted} [απ]{.greek-omitted} [αγρου]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αλεξανδρου]{.greek-omitted} [και]{.greek-omitted} [ρουφου]{.greek-omitted} ινα αρη τον [σταυρον]{.greek-abbr} αυτου[[15:21 *(lacunose)*]{.lacunose}]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον [κρανιου]{.greek-omitted} [τοπος]{.greek-omitted}[[15:22 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [σταυρουσιν]{.greek-omitted} [δυο]{.greek-omitted} [ληστας]{.greek-omitted} [ενα]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} και ενα εξ ευωνυμων αυτου[[15:27 *(lacunose)*]{.lacunose}]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουα]{.greek-omitted} [ο]{.greek-omitted} [καταλυων]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τρισιν]{.greek-omitted} [ημεραις]{.greek-omitted} [οικοδομων]{.greek-omitted}[[15:29 *(lacunose)*]{.lacunose}]{.aside}

[δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γεμισας]{.greek-omitted} [σπογγον]{.greek-omitted} [οξους]{.greek-omitted} [περιθεις]{.greek-omitted} [τε]{.greek-omitted} [καλαμω]{.greek-omitted} [εποτιζεν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [ιδωμεν]{.greek-omitted} ει ερχεται ηλιας καθελειν αυτον[[15:36 *(lacunose)*]{.lacunose}]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [καταπετασμα]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [εσχισθη]{.greek-omitted} [εις]{.greek-omitted} [δυο]{.greek-omitted} απο ανωθεν εως κατω[[15:38 *(lacunose)*]{.lacunose}]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι [εν]{.greek-omitted} [αις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [του]{.greek-omitted} [ιακωβου]{.greek-omitted} [του]{.greek-omitted} [μικρου]{.greek-omitted} [και]{.greek-omitted} [ιωση]{.greek-omitted} [μητηρ]{.greek-omitted} [και]{.greek-omitted} [σαλωμη]{.greek-omitted}[[15:40 *(lacunose)*]{.lacunose}]{.aside}

[αι]{.greek-omitted} [και]{.greek-omitted} [οτε]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [γαλιλαια]{.greek-omitted} [ηκολουθουν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [διηκονουν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αλλαι]{.greek-omitted} [πολλαι]{.greek-omitted} αι συναναβασαι αυτω εις ιεροσολυμα[[15:41 *(lacunose)*]{.lacunose}]{.aside}

και [ηδη]{.greek-omitted} [δη]{.greek-added} οψιας γενομενης επει ην παρασκευη ο εστιν [προσαββατον]{.greek-omitted}[[15:42 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 16

[και]{.greek-omitted} [διαγενομενου]{.greek-omitted} [του]{.greek-omitted} [σαββατου]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [σαλωμη]{.greek-omitted} [ηγορασαν]{.greek-omitted} [αρωματα]{.greek-omitted} ινα ελθουσαι αλειψωσιν αυτον[[16:1 *(lacunose)*]{.lacunose}]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον [ανατειλαντος]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted}[[16:2 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εισελθουσαι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [μνημειον]{.greek-omitted} [ειδον]{.greek-omitted} [νεανισκον]{.greek-omitted} [καθημενον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [δεξιοις]{.greek-omitted} περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[[16:5 *(lacunose)*]{.lacunose}]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [ναζαρινον]{.greek-added} τον εσταυρωμενον [ηγερθη]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [ωδε]{.greek-omitted} [ιδε]{.greek-omitted} [ο]{.greek-omitted} [τοπος]{.greek-omitted} [οπου]{.greek-omitted} [εθηκαν]{.greek-omitted} [αυτον]{.greek-omitted}[[16:6 *(lacunose)*]{.lacunose}]{.aside}

[αλλ]{.greek-omitted} [υπαγετε]{.greek-omitted} [ειπατε]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [οτι]{.greek-omitted} [προαγει]{.greek-omitted} [υμας]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted} εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} καθως ειπεν υμιν[[16:7 *(lacunose)*]{.lacunose}]{.aside}

και εξελθουσαι εφυγον απο του μνημειου ειχεν δε αυτας τρομος και εκστασις [και]{.greek-omitted} [ουδενι]{.greek-omitted} [ουδεν]{.greek-omitted} [ειπον]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted}[[16:8 *(lacunose)*]{.lacunose}]{.aside}

[εκεινοι]{.greek-omitted} [δε]{.greek-omitted} [εξελθοντες]{.greek-omitted} [εκηρυξαν]{.greek-omitted} [πανταχου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [συνεργουντος]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [βεβαιουντος]{.greek-omitted} δια των επακολουθουντων σημειων [α]{.unclear}μην[[16:20 *(lacunose)*]{.lacunose}]{.aside}

