---
title: "Collation of Byz^RP^ vs 20067 (67)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 67 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20067).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 67                                   	| λογος                              	|
| 67 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 67 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 67               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 67                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 67 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 67                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 9

[και]{.greek-omitted} [ελθων]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον πολυν περι αυτους κα[ι]{.unclear} [τους]{.greek-added} γραμματεις [συζητουντας]{.greek-omitted} [συνζητουντα[ς]{.unclear}]{.greek-added} [πρ[ο]{.unclear}ς]{.greek-added} [αυτοις]{.greek-omitted} [αυτους]{.greek-added}[9:14]{.aside}

και ευθεως πα[ς]{.unclear} ο οχλος [ιδων]{.greek-omitted} [ιδο[ν]{.unclear}τες]{.greek-added} αυτον [εξεθαμβηθη]{.greek-omitted} [εξεθαμ[β]{.unclear}ηθησ[α]{.unclear}ν]{.greek-added} και προστρεχοντες ησπαζοντο [αυτον]{.greek-omitted}[9:15]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} οχλ[ου]{.unclear} ειπε[ν]{.unclear} [α[υ]{.unclear}τω]{.greek-added} [δ]{.unclear}ιδ[α]{.unclear}σκαλε η[ν]{.unclear}εγκα τον [υιον]{.greek-abbr} μου προς σε [ε]{.unclear}χοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν α[υ]{.unclear}τον κ[α]{.unclear}τ[α]{.unclear}λα[βη]{.unclear} ρησσε[ι]{.greek-supplied} αυτον και αφριζει και τριζει τους οδοντας αυτου και [ξηραινεται]{.greek-omitted} [ξηρενεται]{.greek-added} και [ει[πα]{.greek-supplied}]{.greek-added} [ειπον]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [σου]{.greek-omitted} [ινα]{.greek-omitted} [αυτο]{.greek-omitted} [εκβαλωσιν]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ισχυσαν]{.greek-omitted}[9:18]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} ω γενεα απιστος εως π[ο]{.unclear}τε προς υμας εσομαι εως ποτε ανεξομαι [υ]{.unclear}μ[ω]{.unclear}ν [φερετε]{.greek-omitted} [φερεται]{.greek-added} αυτ[ον]{.unclear} προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} ε[σ]{.unclear}παραξεν [α]{.unclear}υτον και πε[σων]{.greek-supplied} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [εκυλιετο]{.greek-omitted} [αφριζων]{.greek-omitted}[[9:20 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [ποσος]{.greek-omitted} [χρονος]{.greek-omitted} [εστιν]{.greek-omitted} [ως]{.greek-omitted} τουτο γεγονεν αυτω ο δε ειπεν [εκ]{.greek-added} [παιδιοθεν]{.greek-omitted} [παιδοθε[ν]{.greek-supplied}]{.greek-added}[9:21]{.aside}

και πολλακις [αυτον]{.greek-omitted} [και]{.greek-omitted} εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} και εις υδατα [αυτον]{.greek-added} [εβαλεν]{.greek-added} ινα [αυτον]{.greek-added} απολεση [αυτον]{.greek-omitted} αλλ ει τι [δυνασαι]{.greek-omitted} [δυνη]{.greek-added} [[κυριε]{.greek-abbr}]{.greek-added} [β]{.unclear}οηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

### Chapter 14

[οτι]{.greek-omitted} [ημεις]{.greek-omitted} [ηκουσαμεν]{.greek-omitted} [αυτου]{.greek-omitted} [λεγοντος]{.greek-omitted} [οτι]{.greek-omitted} [εγω]{.greek-omitted} [καταλυσω]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [τουτον]{.greek-omitted} [τον]{.greek-omitted} [χειροποιητον]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [τριων]{.greek-omitted} [ημερων]{.greek-omitted} [αλλον]{.greek-omitted} [αχειροποιητον]{.greek-omitted} [οικο]{.greek-supplied}δομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια [α]{.unclear}υτω[ν]{.unclear}[14:59]{.aside}

και α[ν]{.unclear}αστ[α]{.unclear}ς ο αρχιερε[υς]{.unclear} εις μεσον επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων ουκ [αποκρινη]{.greek-omitted} [αποκριν[ω]{.unclear}]{.greek-added} ουδεν τι ουτ[ο]{.unclear}ι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ου[δ]{.unclear}εν απεκρινατο [παλιν]{.greek-omitted} [παλειν]{.greek-added} [ουν]{.greek-added} ο αρχιερευς [επηρωτα]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτον και λεγε[ι]{.unclear} [αυτω]{.greek-omitted} [συ]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ευλογητου]{.greek-omitted}[[14:61 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.unclear} [δε]{.greek-supplied} [[ιησους]{.greek-abbr}]{.unclear} [ε]{.unclear}[ι]{.greek-supplied}[πεν]{.unclear} [ε]{.greek-supplied}γω ειμι και [ο]{.unclear}ψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [κα[θη]{.greek-supplied}μενον]{.greek-added} εκ δε[ξι]{.greek-supplied}ων [καθημενον]{.greek-omitted} της δυν[α]{.greek-supplied}μεως και ε[ρ]{.unclear}[χο]{.greek-supplied}μενον μετ[α]{.greek-supplied} των νεφελ[ων]{.greek-supplied} του ουρανο[υ]{.greek-supplied}[14:62]{.aside}

ο δε αρχιερε[υς]{.greek-supplied} διαρρηξας τ[ο]{.unclear}[υς]{.greek-supplied} χιτωνας αυ[του]{.greek-supplied} λεγει τι ετι [χ]{.unclear}[ρει]{.greek-supplied}αν εχομεν [μ]{.unclear}[αρ]{.greek-supplied}τυρων[14:63]{.aside}

ηκο[υ]{.greek-supplied}σατε της βλ[α]{.greek-supplied}σφημιας [αυ[του]{.greek-supplied}]{.greek-added} τι υμιν φαιν[εται]{.greek-supplied} οι δε παντες κατεκρινα[ν]{.unclear} [αυτον]{.greek-omitted} [ειναι]{.greek-omitted} [ενοχον]{.greek-omitted} [θανατου]{.greek-omitted}[14:64]{.aside}

[και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [τινες]{.greek-omitted} [εμπτυειν]{.greek-omitted} [αυ]{.greek-supplied}[τ]{.greek-supplied}[ω]{.unclear} και περικα[λ]{.greek-supplied}[υ]{.unclear}πτειν το πρ[ο]{.unclear}[σ]{.greek-supplied}ωπον [α]{.unclear}υτου [κ]{.greek-supplied}[α]{.unclear}ι κολαφι[ζ]{.unclear}ει[ν]{.greek-supplied} [α]{.greek-supplied}[υ]{.unclear}τον και λεγειν [αυτω]{.greek-omitted} [π]{.greek-supplied}ροφητευσον [κ]{.greek-supplied}αι οι υπηρεται [ρ]{.greek-supplied}[α]{.unclear}πισμασιν αυ[τ]{.greek-supplied}ον [εβαλλον]{.greek-omitted} [ελαβον]{.greek-added}[14:65]{.aside}

[και]{.greek-supplied} οντος του [π]{.greek-supplied}[ε]{.unclear}τρου εν τη [αυ]{.greek-supplied}λη [κατω]{.greek-omitted} ερχεται [μ]{.greek-supplied}ια των π[α]{.unclear}ιδι[σ]{.greek-supplied}κων το[υ]{.unclear} [α]{.greek-supplied}ρ[χ]{.unclear}ι[ε]{.greek-supplied}ρεως[14:66]{.aside}

κα[ι]{.greek-supplied} [ι]{.greek-supplied}[δο]{.unclear}υ[σ]{.greek-supplied}α τον πετρον [θ]{.greek-supplied}ερμαινομε[ν]{.greek-supplied}ον εμβλεψα[σ]{.greek-supplied}α αυτ[ω]{.unclear} [λ]{.unclear}εγει [κ]{.greek-supplied}αι συ μετα του [ναζαρηνου]{.greek-omitted} [ιησου]{.greek-omitted} [ησθα]{.greek-omitted}[[14:67 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ηρνησατο]{.greek-omitted} [λεγων]{.greek-omitted} ουκ [οιδα]{.greek-omitted} [ουδε]{.greek-omitted} επισταμαι τι συ [λε]{.unclear}γεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ εφωνησεν[14:68]{.aside}

και η παιδισκη ιδουσα αυτον [παλιν]{.greek-omitted} [παλειν]{.greek-added} ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστωσιν]{.greek-added} οτι ουτος εξ αυτων εστι[ν]{.unclear}[14:69]{.aside}

ο δε [παλιν]{.greek-omitted} [παλειν]{.greek-added} ηρνειτο και μετα μικρον [παλιν]{.greek-omitted} [παλειν]{.greek-added} οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτω[ν]{.unclear} [ει]{.greek-omitted} [και]{.greek-omitted} [γαρ]{.greek-omitted} [γαλιλαιος]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [λαλια]{.greek-omitted} [σου]{.greek-omitted} [ομοιαζει]{.greek-omitted}[14:70]{.aside}

