---
title: "Collation of Byz^RP^ vs 20076 (76)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 76 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20076).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 76                                   	| λογος                              	|
| 76 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 76 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 76               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 76                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 76 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 76                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 2

[κρητες]{.greek-omitted} [και]{.greek-omitted} [αραβες]{.greek-omitted} [ακουομεν]{.greek-omitted} [λαλουντων]{.greek-omitted} [αυτων]{.greek-omitted} [ταις]{.greek-omitted} [ημετεραις]{.greek-omitted} [γλωσσαις]{.greek-omitted} [τα]{.greek-omitted} [μεγαλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και [διηπορουν]{.greek-omitted} [διηπο[ρουν]{.greek-supplied}το]{.greek-added} αλλος [προς]{.unclear} [τον]{.greek-added} αλλο[ν]{.unclear} [λ]{.greek-supplied}[ε]{.unclear}[γ]{.unclear}οντ[ες]{.unclear} [τι]{.unclear} [αν]{.greek-omitted} [θελοι]{.greek-omitted} [θε[λ]{.unclear}[ει]{.greek-supplied}]{.greek-added} [το]{.unclear}υτο ει[ναι]{.greek-supplied}[2:12]{.aside}

[ετ]{.greek-supplied}ερ[οι]{.unclear} [δ]{.unclear}[ε]{.greek-supplied} [χλευαζοντες]{.greek-omitted} [[εχλε]{.greek-supplied}[υαζον]{.unclear}]{.greek-added} [ελεγον]{.greek-omitted} [[λεγοντες]{.greek-supplied}]{.greek-added} [ο]{.unclear}[τι]{.unclear} [γλευκους]{.greek-supplied} [μ]{.unclear}[εμεστωμε]{.greek-supplied}ν[ο]{.unclear}ι ε[ισιν]{.unclear}[2:13]{.aside}

[στ]{.unclear}αθει[ς]{.unclear} [δε]{.greek-supplied} [[ο]{.unclear}]{.greek-added} [π]{.greek-supplied}[ετ]{.unclear}ρο[ς]{.greek-supplied} [συ]{.unclear}ν τ[ο]{.greek-supplied}ις εν[δε]{.greek-supplied}[κα]{.unclear} επηρεν [τ]{.greek-supplied}[ην]{.unclear} φωνην [α]{.greek-supplied}[υ]{.unclear}του και α[πε]{.unclear}[φ]{.greek-supplied}[θ]{.unclear}εγξατο [α]{.unclear}[υ]{.greek-supplied}[τ]{.unclear}οις ανδρε[ς]{.greek-supplied} [ι]{.greek-supplied}ουδα[ι]{.unclear}ο[ι]{.unclear} [κ]{.greek-supplied}[αι]{.unclear} οι κατοικου[ν]{.unclear}[τ]{.unclear}ες [ιερουσαλημ]{.greek-abbr} [απαντες]{.greek-omitted} [[π]{.greek-supplied}[α]{.unclear}ν[τες]{.greek-supplied}]{.greek-added} το[υ]{.unclear}[το]{.greek-supplied} [[γ]{.unclear}ν[ω]{.unclear}[στον]{.greek-supplied}]{.greek-added} [υμιν]{.greek-supplied} [γνωστον]{.greek-omitted} [εστ]{.unclear}[ω]{.greek-supplied} [και]{.greek-supplied} [ενω]{.greek-supplied}τ[ι]{.unclear}[σασθε]{.greek-supplied} [τα]{.greek-supplied} [ρ]{.unclear}[ηματα]{.greek-supplied} [μο]{.greek-supplied}[υ]{.unclear}[2:14]{.aside}

[ο]{.unclear}[υ]{.greek-supplied} [γαρ]{.greek-supplied} [ως]{.greek-supplied} [υ]{.greek-supplied}[μ]{.unclear}[εις]{.greek-supplied} [υπολαμ]{.greek-supplied}[βαν]{.unclear}[ετε]{.greek-supplied} [ουτοι]{.greek-supplied} μ[εθ]{.unclear}[υουσι]{.greek-supplied}[ν]{.unclear} εστ[ι]{.unclear}[ν]{.greek-supplied} [γαρ]{.greek-supplied} ωρ[α]{.unclear} τ[ρι]{.unclear}[τη]{.greek-supplied} [της]{.greek-supplied} [η]{.greek-supplied}[μερα]{.unclear}[ς]{.greek-supplied}[2:15]{.aside}

[αλλα]{.greek-supplied} [τ]{.greek-supplied}[ου]{.unclear}[το]{.greek-supplied} [ε]{.greek-supplied}[στι]{.unclear}ν [το]{.unclear} [ε]{.unclear}[ιρημενον]{.greek-supplied} [δια]{.unclear} [του]{.unclear} [προ]{.greek-supplied}φη[τ]{.unclear}ου [ιωηλ]{.greek-supplied}[2:16]{.aside}

κ[αι]{.unclear} [εστα]{.unclear}[ι]{.greek-supplied} [[με]{.greek-supplied}τα]{.greek-added} [ταυτ[α]{.unclear}]{.greek-added} [εν]{.greek-omitted} [ταις]{.greek-omitted} [εσχαταις]{.greek-omitted} [ημεραις]{.greek-omitted} [λ]{.unclear}[εγει]{.greek-supplied} ο [θεος]{.greek-abbr} [ε]{.greek-supplied}[κχεω]{.unclear} [απ]{.unclear}[ο]{.greek-supplied} [τ]{.greek-supplied}ου [πνευματος]{.greek-abbr} μο[υ]{.unclear} [επι]{.greek-supplied} [πα]{.greek-supplied}[σα]{.greek-supplied}ν σ[αρ]{.unclear}[κα]{.greek-supplied} [και]{.greek-omitted} [προφητευσουσιν]{.greek-omitted} [οι]{.greek-omitted} [υιοι]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [θυγατερες]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted} [υμων]{.greek-omitted} [ορασεις]{.greek-omitted} [οψονται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [υμων]{.greek-omitted} [ενυπνια]{.greek-omitted} [ενυπνιασθησονται]{.greek-omitted}[2:17]{.aside}

[και]{.greek-omitted} [εσται]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [εσχαταις]{.greek-omitted} [ημεραις]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκχεω]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [πνευματος]{.greek-omitted} [μου]{.greek-omitted} [επι]{.greek-omitted} [πασαν]{.greek-omitted} [σαρκα]{.greek-omitted} κ[αι]{.unclear} προφη[τ]{.unclear}ευ[σ]{.greek-supplied}[ο]{.unclear}υσ[ι]{.unclear}[ν]{.greek-supplied} [οι]{.unclear} [υ]{.unclear}[ιο]{.greek-supplied}[ι]{.unclear} υ[μ]{.greek-supplied}[ω]{.unclear}ν και [αι]{.greek-supplied} [θυγα]{.greek-supplied}[τ]{.unclear}[ε]{.greek-supplied}[ρες]{.unclear} [υμων]{.greek-supplied} [κ]{.greek-supplied}[α]{.unclear}ι οι [νεανισκοι]{.greek-supplied} [υ]{.unclear}[μων]{.greek-supplied} [ορασει]{.greek-supplied}[ς]{.unclear} [οψονται]{.greek-supplied} και [οι]{.greek-supplied} [πρεσβ]{.greek-supplied}[υ]{.unclear}τε[ροι]{.greek-supplied} [υμ]{.greek-supplied}[ω]{.unclear}ν [ενυπνια]{.greek-omitted} [εν[υπνιοις]{.greek-supplied}]{.greek-added} [ε]{.unclear}νυπνι[ασθησον]{.greek-supplied}ται[2:17 | instance no. 2]{.aside}

[κ]{.unclear}α[ι]{.unclear} [γε]{.greek-supplied} [επι]{.greek-supplied} [τους]{.unclear} [δο]{.unclear}[υλους]{.greek-supplied} [μου]{.greek-supplied} [και]{.greek-supplied} [επι]{.greek-supplied} [τ]{.greek-supplied}[ας]{.unclear} [δου]{.unclear}[λ]{.unclear}[ας]{.greek-supplied} [μ]{.greek-supplied}[ο]{.unclear}υ εν ταις [η]{.unclear}[με]{.greek-supplied}ραις εκει[ν]{.unclear}αι[ς]{.unclear} εκχεω [απ]{.unclear}ο του [πνευματος]{.greek-abbr} [μου]{.greek-supplied} [κα]{.unclear}ι προφ[η]{.unclear}τευ[σουσιν]{.greek-supplied}[2:18]{.aside}

[και]{.unclear} [δωσ]{.greek-supplied}[ω]{.unclear} τ[ε]{.unclear}ρ[α]{.unclear}[τα]{.greek-supplied} [εν]{.greek-supplied} [τ]{.greek-supplied}ω [ου]{.unclear}ρανω ανω και σημεια ε[π]{.greek-supplied}[ι]{.unclear} της γης κα[τ]{.unclear}ω αιμα και [π]{.greek-supplied}υρ και ατμιδα καπνο[υ]{.unclear}[2:19]{.aside}

ο ηλι[ος]{.unclear} [μετ]{.greek-supplied}[α]{.unclear}[σ]{.unclear}τρ[α]{.unclear}[φησε]{.greek-supplied}ται ει[ς]{.unclear} [σκο]{.greek-supplied}[τος]{.unclear} [και]{.greek-supplied} [η]{.greek-supplied} [σε]{.unclear}[λ]{.unclear}[ηνη]{.greek-supplied} [εις]{.greek-supplied} [αι]{.unclear}μα [π]{.unclear}[ριν]{.greek-supplied} [η]{.greek-supplied} [ε]{.unclear}λθειν [την]{.greek-omitted} [η]{.unclear}[μερ]{.greek-supplied}[α]{.unclear}ν [κυριου]{.greek-abbr} [τη]{.unclear}ν μεγαλην κα[ι]{.unclear} επιφα[νη]{.unclear}[2:20]{.aside}

[κ]{.unclear}αι [ε]{.unclear}σται πας [ος]{.unclear} [α]{.unclear}ν επικαλε[σ]{.unclear}ηται το [ο]{.unclear}[νο]{.greek-supplied}[μ]{.unclear}α [κυριου]{.greek-abbr} σωθη[σε]{.greek-supplied}ται[2:21]{.aside}

αν[δ]{.unclear}[ρ]{.greek-supplied}[ες]{.unclear} [ισραηλιται]{.greek-omitted} [ισραηλ[ε]{.unclear}[ιται]{.greek-supplied}]{.greek-added} ακου[σατε]{.unclear} τους [λο]{.greek-added} [λογους]{.greek-omitted} [τουτους]{.greek-omitted} [ιησουν]{.greek-omitted} [τον]{.greek-omitted} [ναζωραιον]{.greek-omitted} [ανδρα]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [αποδεδειγμενον]{.greek-omitted} [εις]{.greek-omitted} [υμας]{.greek-omitted} [δυναμεσιν]{.greek-omitted} [και]{.greek-omitted} [τερασιν]{.greek-omitted} [και]{.greek-omitted} [σημειοις]{.greek-omitted} [οις]{.greek-omitted} [εποιησεν]{.greek-omitted} [δι]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [υμων]{.greek-omitted} [καθως]{.greek-omitted} [και]{.greek-omitted} [αυτοι]{.greek-omitted} [οιδατε]{.greek-omitted}[2:22]{.aside}

