---
title: "Collation of Byz^RP^ vs 20073 (73)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 73 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20073).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 73                                   	| λογος                              	|
| 73 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 73 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 73               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 73                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 73 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 73                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 14

[και]{.greek-omitted} [κελευσας]{.greek-omitted} [τους]{.greek-omitted} [οχλους]{.greek-omitted} [ανακλιθηναι]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [χορτους]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} και τους δυο ιχθυας αναβλεψας εις τον ουρανον [ε]{.unclear}υλογησεν και κλασας εδωκ[ε]{.unclear}ν τοις μαθηταις τους [α]{.unclear}ρ[του]{.unclear}ς οι δε μαθη[τ]{.unclear}αι τοις οχλοις[14:19]{.aside}

και εφαγον παντ[ε]{.unclear}ς και εχορτασθησαν και ηραν το περισ[σε]{.unclear}υον των κλασματων δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε εσθι[ο]{.unclear}ντες ησαν ανδρες ωσει πεντακισ[χι]{.unclear}λιοι χωρις γυναι[κ]{.unclear}ων [και]{.greek-supplied} [παιδιων]{.greek-supplied}[14:21]{.aside}

[και]{.greek-supplied} [ευθεως]{.greek-supplied} [ηναγκασεν]{.greek-supplied} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τους]{.greek-supplied} [μαθητας]{.greek-supplied} [εμβηναι]{.greek-supplied} εις το πλοιον και προαγειν αυτον εις το περαν εως ου α[π]{.unclear}ολυση τους οχλους[14:22]{.aside}

[κ]{.greek-supplied}αι απολυσας τους οχλο[υς]{.unclear} ανεβη εις [τ]{.unclear}ο ορο[ς]{.unclear} [κατ]{.unclear} ιδιαν προσε[υξασθ]{.unclear}αι [ο]{.greek-supplied}ψιας [δε]{.unclear} [γ]{.unclear}ενομενης μον[ος]{.unclear} [η]{.unclear}ν εκει[14:23]{.aside}

[τ]{.greek-supplied}ο δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εν[αν]{.unclear}τιος ο αν[εμ]{.unclear}ος[14:24]{.aside}

τεταρτη δ[ε]{.unclear} φ[υλακη]{.unclear} [τ]{.unclear}ης νυκτος [απηλθεν]{.greek-omitted} [ηλθ[εν]{.unclear}]{.greek-added} προς αυ[το]{.unclear}υς [ο]{.greek-omitted} [ιησους]{.greek-omitted} πε[ριπα]{.unclear}των επ[ι]{.greek-supplied} [της]{.greek-omitted} [[τ]{.greek-supplied}ην]{.greek-added} [θαλασσης]{.greek-omitted} [θαλ[ασ]{.unclear}σαν]{.greek-added}[14:25]{.aside}

κ[αι]{.unclear} [ι]{.unclear}δοντ[ε]{.unclear}ς αυτον [περιπατουντα]{.greek-added} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} επι [την]{.greek-omitted} [τη[ς]{.unclear}]{.greek-added} [θαλασσαν]{.greek-omitted} [θαλασσ[η]{.unclear}ς]{.greek-added} [περιπατουντα]{.greek-omitted} εταραχθη[σα]{.unclear}ν [λ]{.unclear}ε[γ]{.unclear}οντες οτι φαντασμα εστιν και απο του φοβου [ε]{.unclear}κραξαν[14:26]{.aside}

[ευθεως]{.greek-omitted} [[ε]{.unclear}υθ[υς]{.unclear}]{.greek-added} [δ]{.unclear}ε ελαλησεν [αυτοις]{.greek-omitted} [ο]{.greek-supplied} [[ιησους]{.greek-abbr}]{.greek-supplied} [[αυτοις]{.greek-supplied}]{.greek-added} [λε]{.greek-supplied}γων θαρσειτε [ε]{.unclear}γω ειμι μη [φοβεισθε]{.greek-omitted} [φοβισθ[ε]{.unclear}]{.greek-added}[14:27]{.aside}

[[ελθει]{.greek-supplied}ν]{.greek-added} [αποκριθεις]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [ειπεν]{.greek-omitted} [κυριε]{.greek-omitted} [ει]{.greek-omitted} [συ]{.greek-omitted} [ει]{.greek-omitted} [κελευσον]{.greek-omitted} [με]{.greek-omitted} προς σε [ελθειν]{.greek-omitted} [επι]{.greek-supplied} [τα]{.greek-supplied} [υ]{.greek-supplied}δατα[14:28]{.aside}

ο δε [ειπεν]{.greek-supplied} ελθε [και]{.greek-supplied} [καταβα]{.greek-supplied}ς απο του [πλοιου]{.greek-supplied} [ο]{.greek-supplied} πετρος [περιεπατησεν]{.greek-omitted} [[περιεπα]{.greek-supplied}τησε]{.greek-added} [ν]{.greek-added} ε[πι]{.greek-supplied} [τα]{.greek-supplied} [υδα]{.greek-supplied}τα [ελθειν]{.greek-omitted} [ελθιν]{.greek-added} [προς]{.greek-supplied} [τον]{.greek-supplied} [ιησουν]{.greek-abbr}[14:29]{.aside}

βλεπων [δε]{.greek-supplied} [τον]{.greek-supplied} [αν]{.greek-supplied}εμον [ισχυρον]{.greek-omitted} ε[φοβηθη]{.greek-supplied} [και]{.greek-omitted} αρξαμε[νος]{.greek-supplied} [καταποντιζεσθαι]{.greek-omitted} [[κατα]{.greek-supplied}ποντιζε[σθε]{.greek-supplied}]{.greek-added} [εκρα]{.greek-supplied}ξεν λεγων [[κυριε]{.greek-abbr}]{.greek-supplied} [σωσο]{.greek-supplied}ν με[14:30]{.aside}

ευθε[ως]{.greek-supplied} [δε]{.greek-supplied} [ο]{.greek-supplied} [ιησους]{.greek-abbr} [εκτεινας]{.greek-supplied} [την]{.greek-omitted} [χειρα]{.greek-omitted} [επελαβετο]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ολιγοπιστε]{.greek-omitted} [εις]{.greek-omitted} [τι]{.greek-omitted} [εδιστασας]{.greek-omitted}[14:31]{.aside}

[ευθεως]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εκτεινας]{.greek-omitted} [τη]{.unclear}[ν]{.greek-supplied} [χ]{.unclear}ειρα επελα[βε]{.greek-supplied}το αυτου και λε[γε]{.unclear}[ι]{.greek-supplied} αυτω ολιγοπιστε ε[ι]{.unclear}ς τι εδιστασας[14:31 | instance no. 2]{.aside}

κ[α]{.unclear}[ι]{.greek-supplied} [εμβαντων]{.greek-omitted} [[α]{.greek-supplied}ναβαντων]{.greek-added} α[υ]{.greek-supplied}των εις το πλοιο[ν]{.greek-supplied} εκοπασε[ν]{.unclear} ο αν[ε]{.unclear}μος[14:32]{.aside}

οι δε εν τ[ω]{.unclear} πλοιω [ελθοντες]{.greek-omitted} προσεκ[υ]{.unclear}[νη]{.greek-supplied}σαν αυτω λεγον[τ]{.unclear}[ες]{.greek-supplied} αλη[θω]{.unclear}ς [θεου]{.greek-abbr} [υιος]{.greek-abbr} ει[14:33]{.aside}

και διαπερασαντ[ε]{.unclear}[ς]{.greek-supplied} [ηλθον]{.greek-omitted} [ηλθαν]{.greek-added} [εις]{.greek-omitted} [επι]{.greek-added} την [γη]{.unclear}[ν]{.greek-supplied} [εις]{.greek-added} γεννησ[α]{.unclear}[ρετ]{.greek-supplied}[14:34]{.aside}

και επιγ[νοντες]{.greek-supplied} [αυ]{.greek-supplied}τον οι αν[δρες]{.greek-supplied} [του]{.greek-supplied} τοπου [εκεινου]{.greek-omitted} [απεστειλαν]{.greek-omitted} [εις]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [περιχωρον]{.greek-omitted} [εκεινην]{.greek-omitted} [και]{.greek-omitted} [προσηνεγκαν]{.greek-omitted} [αυτω]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted}[[14:35 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 15

[δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μα]{.greek-supplied}θηται σου [παραβαινουσιν]{.greek-omitted} [παραβαινουσι]{.greek-added} την παραδοσιν των πρεσβυτερων ου γαρ νιπτονται τας [χειρας]{.greek-omitted} [χιρας]{.greek-added} [αυτων]{.greek-omitted} οταν αρτον εσθιωσιν[[15:2 *(lacunose)*]{.lacunose}]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και υμεις παρ[αβα]{.unclear}ιν[ε]{.unclear}τε την εν[το]{.unclear}λην του [θεου]{.greek-abbr} δια [τ]{.unclear}ην παραδοσιν υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} [ειπεν]{.greek-added} [ενετειλατο]{.greek-omitted} [λεγων]{.greek-omitted} τιμα τον [πα]{.greek-supplied}[τ]{.unclear}ερα και την μη[τερα]{.greek-supplied} και ο κακολογ[ων]{.greek-supplied} πατερα η μητερ[α]{.greek-supplied} [θα]{.greek-supplied}νατω τελευ[τατω]{.greek-supplied}[15:4]{.aside}

[υμεις]{.greek-supplied} [δε]{.greek-supplied} [λεγετε]{.greek-supplied} [ος]{.greek-supplied} [αν]{.greek-supplied} [ειπη]{.greek-supplied} [τω]{.greek-supplied} [πα]{.greek-supplied}τρι [η]{.greek-omitted} [τη]{.greek-omitted} [μητρι]{.greek-omitted} δωρον ο εαν εξ εμου ωφεληθης [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[ου]{.greek-added} [μη]{.greek-added} [τιμησει]{.greek-added} [το[ν]{.unclear}]{.greek-added} [πατερα]{.greek-added} [αυτου]{.greek-added} [η]{.greek-added} [την]{.greek-added} [μητερα]{.greek-added} και ηκυρωσατε [την]{.greek-omitted} [εντολην]{.greek-omitted} [τον]{.greek-added} [νομον]{.greek-added} του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:6]{.aside}

υποκριται καλως [προεφητευσεν]{.greek-omitted} [επροφητευσεν]{.greek-added} περι υμω[ν]{.unclear} ησαιας λεγων[15:7]{.aside}

[εγγιζει]{.greek-omitted} [μοι]{.greek-omitted} ο λαος ουτος [τω]{.greek-omitted} [στοματι]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} τοις [χειλεσιν]{.greek-omitted} [χιλεσιν]{.greek-added} με τιμα [η]{.greek-omitted} [δε]{.greek-omitted} [καρδια]{.greek-omitted} [αυτων]{.greek-omitted} [πορρω]{.greek-omitted} [απεχει]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted}[15:8]{.aside}

