---
title: "Collation of Byz^RP^ vs 20072 (72)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 72 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20072).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 72                                   	| λογος                              	|
| 72 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 72 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 72               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 72                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 72 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 72                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 2

[εσθαι]{.greek-added} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [παραπορευεσθαι]{.greek-omitted} α[υτο]{.unclear}[ν]{.greek-supplied} εν [τοις]{.greek-supplied} [σαβ]{.greek-supplied}βασ[ιν]{.unclear} δ[ι]{.unclear}α [τ]{.unclear}ω[ν]{.unclear} σπο[ρι]{.unclear}[μ]{.greek-supplied}ων και [ηρξαντο]{.greek-omitted} [ο]{.unclear}ι μαθ[η]{.unclear}ται αυ[τ]{.unclear}ου [ηρξαντο]{.greek-added} [[π]{.unclear}οι[ειν]{.unclear}]{.greek-added} οδο[ν]{.unclear} [ποιειν]{.greek-omitted} [τι]{.unclear}λλο[ν]{.unclear}τες [τους]{.unclear} σ[τα]{.greek-supplied}[χυ]{.unclear}α[ς]{.unclear}[2:23]{.aside}

[κ]{.unclear}αι οι [φαρ]{.greek-supplied}[ι]{.unclear}σαιοι [ε]{.unclear}λ[ε]{.unclear}[γο]{.greek-supplied}[ν]{.unclear} [αυ]{.unclear}[τω]{.greek-supplied} ιδ[ε]{.unclear} τι ποιο[υ]{.unclear}σι[ν]{.unclear} [εν]{.greek-supplied} [τοις]{.greek-supplied} σαβ[β]{.unclear}[ασιν]{.greek-supplied} [ο]{.greek-supplied} ουκ ε[ξε]{.unclear}στι[ν]{.greek-supplied}[2:24]{.aside}

κα[ι]{.unclear} [λ[ε]{.unclear}[γει]{.greek-supplied}]{.greek-added} [αυτος]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυ]{.greek-supplied}[τ]{.unclear}[οι]{.greek-supplied}[ς]{.unclear} ο[υ]{.greek-supplied}[δ]{.unclear}ε[πο]{.unclear}[τε]{.unclear} [ανεγνω]{.greek-supplied}[τε]{.unclear} [τι]{.unclear} [εποιη]{.greek-supplied}σ[εν]{.unclear} [δαυιδ]{.greek-supplied} [ο]{.greek-supplied}[τε]{.unclear} [χρειαν]{.greek-supplied} [ε]{.unclear}[σχεν]{.greek-supplied} [και]{.greek-supplied} [επεινασεν]{.greek-omitted} [[ε]{.unclear}π[ιν]{.unclear}[ασεν]{.greek-supplied}]{.greek-added} [αυτος]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[[2:25 *(lacunose)*]{.lacunose}]{.aside}

[πως]{.greek-omitted} [ει]{.unclear}σ[η]{.unclear}[λθεν]{.greek-supplied} [εις]{.greek-supplied} τ[ον]{.greek-supplied} [οικον]{.greek-supplied} [του]{.greek-supplied} [θεου]{.greek-omitted} [επι]{.greek-omitted} [αβιαθαρ]{.greek-omitted} [αρχιερε]{.greek-supplied}[ω]{.unclear}[ς]{.greek-supplied} [και]{.greek-supplied} [τους]{.greek-supplied} [αρτους]{.unclear} [της]{.unclear} [π]{.unclear}ροθ[εσε]{.unclear}ως [ε]{.unclear}φ[αγεν]{.greek-supplied} [ους]{.greek-supplied} ουκ [εξεστιν]{.greek-omitted} [εστι[ν]{.unclear}]{.greek-added} φα[γε]{.unclear}ι[ν]{.unclear} ει μ[η]{.unclear} [τοις]{.greek-omitted} [[τους]{.greek-supplied}]{.greek-added} [ιερευσιν]{.greek-omitted} [ι[ε]{.unclear}ρε[ις]{.greek-supplied}]{.greek-added} [κ]{.greek-supplied}αι [εδ]{.unclear}ω[κεν]{.greek-supplied} κ[α]{.unclear}ι [τοις]{.greek-supplied} [σ]{.greek-supplied}υ[ν]{.greek-supplied} [α]{.greek-supplied}υτ[ω]{.unclear} ου[σιν]{.unclear}[[2:26 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-supplied} ελε[γεν]{.greek-supplied} [αυ]{.greek-supplied}το[ις]{.unclear} [το]{.greek-supplied} [[σαβ]{.greek-supplied}]{.greek-added} [σαββατον]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted} [εγενετο]{.greek-omitted} [ουχ]{.greek-omitted} [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [σαββατον]{.greek-omitted}[2:27]{.aside}

### Chapter 3

[και]{.greek-omitted} [εισηλθεν]{.greek-omitted} [π]{.unclear}αλιν [εις]{.unclear} τη[ν]{.unclear} [σ]{.unclear}υν[αγωγην]{.unclear} [κ]{.greek-supplied}αι η[ν]{.unclear} εκει [α]{.unclear}νθρω[π]{.unclear}ο[ς]{.unclear} εξ[η]{.unclear}ρα[μμ]{.unclear}[ε]{.greek-supplied}[νην]{.unclear} [εχ]{.unclear}ω[ν]{.unclear} [τη]{.greek-supplied}[ν]{.unclear} [χει]{.unclear}ρ[α]{.unclear}[3:1]{.aside}

[κα]{.unclear}ι [π]{.unclear}αρ[ε]{.greek-supplied}τηρου[ν]{.unclear} [αυτον]{.greek-omitted} [ει]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [θεραπευσει]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [κα]{.greek-supplied}τηγ[ορησω]{.unclear}σ[ι]{.unclear}ν αυτου[[3:2 *(lacunose)*]{.lacunose}]{.aside}

και λε[γ]{.greek-supplied}[ε]{.unclear}ι τω α[ν]{.unclear}θρ[ωπω]{.unclear} τω [εξηραμμενην]{.greek-omitted} [εχοντι]{.greek-omitted} τη[ν]{.unclear} [χ]{.unclear}ει[ρ]{.unclear}α [ε[χ]{.unclear}ο[ντι]{.unclear}]{.greek-added} [ε[ξ]{.greek-supplied}ηρα[μμενην]{.greek-supplied}]{.greek-added} [εγειραι]{.greek-omitted} [εγει[ρ]{.unclear}ε]{.greek-added} εις το με[σον]{.unclear}[3:3]{.aside}

κα[ι]{.unclear} λε[γει]{.unclear} [αυτοις]{.greek-supplied} [[τ]{.greek-supplied}ι]{.greek-added} [ε]{.unclear}[ξε]{.greek-supplied}[στι]{.unclear}[ν]{.greek-supplied} [τοις]{.greek-supplied} [σαββασιν]{.greek-supplied} [αγαθοποιησαι]{.greek-omitted} [[αγα]{.greek-supplied}θ[ον]{.unclear}]{.greek-added} [πο[ιησ]{.unclear}αι]{.greek-added} [η]{.greek-supplied} [κα]{.greek-supplied}κ[οπ]{.greek-supplied}οιη[σαι]{.greek-supplied} [ψ]{.greek-supplied}υ[χη]{.unclear}ν [σωσαι]{.greek-supplied} [η]{.unclear} απ[ο]{.unclear}[κτειναι]{.greek-supplied} [οι]{.greek-omitted} [δε]{.greek-omitted} [εσιωπων]{.greek-omitted}[3:4]{.aside}

