---
title: "Collation of Byz^RP^ vs 20083 (83)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 83 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20083).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 83                                   	| λογος                              	|
| 83 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 83 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 83               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 83                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 83 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 83                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 13

[και]{.greek-added} παραδωσει [δε]{.greek-omitted} αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε [ιδητε]{.greek-omitted} [ειδη[τ]{.unclear}ε]{.greek-added} το βδελυγμα της ερη[μωσεως]{.greek-supplied} [το]{.greek-omitted} [ρηθεν]{.greek-omitted} [υπο]{.greek-omitted} [δανιηλ]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [εστως]{.greek-omitted} [οπου]{.greek-omitted} [ου]{.greek-omitted} [δει]{.greek-omitted} [ο]{.greek-omitted} [αναγινωσκων]{.greek-omitted} [νοειτω]{.greek-omitted} [τοτε]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ιουδαια]{.greek-omitted} [φευγετωσαν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορη]{.greek-omitted}[[13:14 *(lacunose)*]{.lacunose}]{.aside}

και ο εις τον αγρον [ων]{.greek-omitted} μη επιστρεψατω [εις]{.greek-omitted} [τα]{.greek-omitted} οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται [η]{.greek-omitted} [φυγη]{.greek-omitted} [υμων]{.greek-omitted} χειμωνος[13:18]{.aside}

εσονται γαρ [αι]{.unclear} [ημε]{.unclear}ραι εκειναι [θλιψις]{.greek-omitted} [θλιψ[εις]{.unclear}]{.greek-added} οια ου γεγον[ε]{.unclear}ν τοιαυτη α[π]{.unclear} [αρχης]{.greek-supplied} κ[τ]{.unclear}ισε[ως]{.greek-supplied} [ης]{.greek-omitted} [[ην]{.greek-supplied}]{.greek-added} [εκτισεν]{.greek-supplied} [ο]{.greek-supplied} [θεος]{.greek-supplied} [εως]{.greek-omitted} [του]{.greek-omitted} [νυν]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [γενηται]{.greek-omitted}[13:19]{.aside}

[τοτε]{.greek-omitted} [εαν]{.greek-omitted} [τις]{.greek-omitted} [υμιν]{.greek-omitted} ειπη [ιδου]{.greek-omitted} [ιδε]{.greek-added} ωδε ο [χριστος]{.greek-abbr} [ιδε]{.greek-added} [η]{.greek-omitted} [ιδου]{.greek-omitted} εκει μη πιστευετε[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και δωσουσιν σημεια και τερατα προς το αποπλαναν ει δυνατον [και]{.greek-omitted} τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε [ιδου]{.greek-omitted} προει[ρη]{.unclear}κα υμιν παντα[13:23]{.aside}

[αλ]{.unclear}[λ]{.greek-supplied} [ε]{.greek-supplied}ν ε[κε]{.unclear}ιναις ταις [ημεραις]{.greek-supplied} [μετα]{.greek-supplied} [τη]{.greek-supplied}ν [θλιψιν]{.greek-omitted} [εκεινην]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [σκοτισθησεται]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [ου]{.greek-omitted} [δωσει]{.greek-omitted} [το]{.greek-omitted} [φεγγος]{.greek-omitted} [αυτης]{.greek-omitted}[[13:24 *(lacunose)*]{.lacunose}]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως πολλης και δοξης[13:26]{.aside}

και τοτε αποστελει τους αγγελους [αυτου]{.greek-omitted} και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως ακρου ουρανου[13:27]{.aside}

απο δε της συκης μ[α]{.unclear}θετε την παραβολην [οταν]{.greek-omitted} [αυτης]{.greek-omitted} [ηδη]{.greek-omitted} [ο]{.greek-omitted} [κλαδος]{.greek-omitted} [απαλος]{.greek-omitted} [γενηται]{.greek-omitted} [και]{.greek-omitted} [εκφυη]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [γινωσκετε]{.greek-omitted} [οτι]{.greek-omitted} [εγγυς]{.greek-omitted} [το]{.greek-omitted} [θερος]{.greek-omitted} [εστιν]{.greek-omitted}[13:28]{.aside}

### Chapter 14

[ο]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} [εφη]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [παντες]{.greek-omitted} σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον [εν]{.greek-omitted} [ταυτη]{.greek-added} τη νυκτι [ταυτη]{.greek-omitted} πριν η δις αλ[ε]{.unclear}κτορα φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} [με]{.greek-added} απαρνηση [με]{.greek-omitted}[14:30]{.aside}

ο δε [εκπερισσου]{.greek-omitted} [εκπερισσως]{.greek-added} [ελαλει]{.greek-added} [ελεγεν]{.greek-omitted} [μαλλον]{.greek-omitted} εαν [δεη]{.greek-added} με [συν]{.greek-added} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} σοι [αποθανειν]{.greek-added} ου μη σε απαρνη[σ]{.unclear}ωμαι ωσαυτως δε και παντες [ελεγον]{.greek-supplied}[14:31]{.aside}

[και]{.greek-supplied} [ερ]{.greek-supplied}[χονται]{.greek-supplied} [ε]{.greek-supplied}ις χω[ριον]{.greek-supplied} [ου]{.greek-supplied} [το]{.greek-supplied} [ο]{.greek-supplied}[νο]{.unclear}μα [γεθσημανη]{.greek-omitted} [[γεθσ]{.greek-supplied}ημ[α]{.unclear}νι]{.greek-added} και λε[γει]{.greek-supplied} το[ι]{.unclear}ς μα[θη]{.unclear}ται[ς]{.unclear} [α]{.greek-supplied}υτου [καθισ]{.unclear}ατε ω[δ]{.unclear}ε [ε]{.unclear}ως προσευ[ξ]{.unclear}ωμαι[14:32]{.aside}

[κα]{.greek-supplied}[ι]{.unclear} παραλαμ[β]{.unclear}ανει [το]{.greek-supplied}ν πετρο[ν]{.unclear} και ι[α]{.unclear}κωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημον[ει]{.unclear}ν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως [θανα]{.unclear}του [μεινατε]{.greek-omitted} [μινατε]{.greek-added} ωδε και γρηγορειτε [μετ]{.greek-added} [εμου]{.greek-added}[14:34]{.aside}

και [προσελθων]{.greek-omitted} [προελθων]{.greek-added} μι[κ]{.unclear}ρον [επεσεν]{.greek-omitted} [επιπτεν]{.greek-added} επι [τ]{.unclear}[ης]{.greek-supplied} [γης]{.greek-supplied} και προσηυχε[τ]{.unclear}[ο]{.greek-supplied} ινα [ει]{.unclear} δυ[νατ]{.unclear}[ον]{.greek-supplied} [εστιν]{.greek-supplied} παρελ[θη]{.greek-supplied} [απ]{.greek-supplied} [αυτου]{.greek-supplied} η ωρα[14:35]{.aside}

[κ]{.unclear}[αι]{.greek-supplied} [ελεγεν]{.greek-supplied} αββα ο [πατηρ]{.greek-abbr} [παντα]{.greek-supplied} δυνατα [σ]{.unclear}[οι]{.greek-supplied} [παρε]{.greek-supplied}[νε]{.unclear}γ[κε]{.unclear} τ[ο]{.unclear} [ποτηριον]{.greek-supplied} [το[υ]{.unclear}το]{.greek-added} απ [ε]{.unclear}[μου]{.greek-supplied} [τουτο]{.greek-omitted} [αλλ]{.greek-supplied} [ου]{.greek-supplied} τι εγω θ[ελ]{.unclear}[ω]{.greek-supplied} [αλλα]{.greek-supplied} τι συ[14:36]{.aside}

και ερχετα[ι]{.greek-supplied} [και]{.greek-supplied} [ευρι]{.greek-supplied}σκ[ε]{.unclear}ι αυτου[ς]{.greek-supplied} [καθευδοντας]{.greek-supplied} [και]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [σιμων]{.greek-omitted} [καθευδεις]{.greek-omitted} [ουκ]{.greek-omitted} [ισχυσας]{.greek-omitted} [μιαν]{.greek-omitted} [ωραν]{.greek-omitted} [γρηγορησαι]{.greek-omitted}[14:37]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [και]{.greek-omitted} [ευρισκει]{.greek-omitted} [αυτους]{.greek-omitted} [καθευδοντας]{.greek-omitted} και λεγει τω π[ετ]{.unclear}ρω σιμων καθευδεις ουκ ισχυσ[ας]{.unclear} μιαν ωραν γρηγορησαι[14:37 | instance no. 2]{.aside}

γρηγορειτε και προσευχεσθε ινα μη ε[ισε]{.unclear}λθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} π[ρ]{.unclear}οθυμον η δε σαρξ [ασθ]{.unclear}ενης[14:38]{.aside}

και παλιν απ[ε]{.unclear}λθων προ[ση]{.unclear}υξατο τον [αυτ]{.greek-supplied}[ον]{.unclear} [λ]{.unclear}ογον ειπων[14:39]{.aside}

[και]{.greek-supplied} [υποστρεψας]{.greek-omitted} [[π]{.unclear}α[λ]{.unclear}ιν]{.greek-added} [ελθων]{.greek-added} [ευρεν]{.greek-supplied} [α]{.greek-supplied}[υ]{.unclear}του[ς]{.unclear} [παλιν]{.greek-omitted} [κα]{.unclear}[θευδοντας]{.greek-supplied} [ησαν]{.greek-supplied} [γαρ]{.unclear} [[αυτων]{.greek-supplied}]{.greek-added} [οι]{.unclear} οφθαλ[μοι]{.greek-supplied} [[κα]{.greek-supplied}[τ]{.unclear}α[β]{.unclear}αρ[υ]{.unclear}[νομενοι]{.greek-supplied}]{.greek-added} [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδεισαν]{.greek-omitted} [τι]{.greek-omitted} [αυτω]{.greek-omitted} [αποκριθωσιν]{.greek-omitted}[[14:40 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-supplied} [ερχεται]{.greek-supplied} [το]{.greek-supplied} [τρι]{.greek-supplied}[τον]{.greek-supplied} [και]{.greek-supplied} [λεγει]{.greek-supplied} αυτ[οις]{.unclear} [καθευδετε]{.greek-supplied} [[το]{.unclear}]{.greek-added} λ[οιπον]{.unclear} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[[14:41 *(lacunose)*]{.lacunose}]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} ετι αυτου λαλο[υν]{.unclear}τος παραγινεται ιουδας εις [ων]{.greek-omitted} των δωδεκα και μετ αυτο[υ]{.unclear} οχλος [πολυς]{.greek-omitted} μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γρ[α]{.unclear}[μματεων]{.greek-supplied} και [των]{.greek-omitted} π[ρεσβυτερων]{.greek-supplied}[14:43]{.aside}

δ[ε]{.unclear}δ[ωκε]{.unclear}[ι]{.greek-supplied} [δε]{.greek-supplied} [ο]{.greek-supplied} [παρα]{.greek-supplied}διδους α[υ]{.unclear}τον [σ]{.unclear}[υσση]{.greek-supplied}μο[ν]{.unclear} [αυ]{.unclear}τοις λεγ[ων]{.greek-supplied} ον [α]{.unclear}ν φι[λη]{.unclear}σω αυτος [εσ]{.unclear}τιν κρ[ατη]{.unclear}σατε [α]{.unclear}υτον κ[α]{.unclear}ι [απαγαγετε]{.greek-omitted} [απ[αγε]{.unclear}τε]{.greek-added} [ασ]{.unclear}φα[λ]{.unclear}[ως]{.greek-supplied}[14:44]{.aside}

και ελ[θων]{.unclear} [[ευθυς]{.unclear}]{.greek-added} [ευθεως]{.greek-omitted} [προσελθων]{.greek-omitted} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} [ραββι]{.greek-omitted} [και]{.greek-omitted} [κατεφιλησεν]{.greek-omitted} [αυτον]{.greek-omitted}[14:45]{.aside}

### Chapter 15

[και]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [σταυρουσιν]{.greek-omitted} [δυο]{.greek-omitted} [ληστας]{.greek-omitted} ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρ[ω]{.unclear}θ[η]{.unclear} η γραφη [η]{.greek-supplied} [λεγουσα]{.greek-supplied} και με[τ]{.unclear}[α]{.greek-supplied} [ανομων]{.greek-supplied} ελογισ[θ]{.unclear}[η]{.greek-supplied}[15:28]{.aside}

και οι π[α]{.unclear}[ραπορευο]{.greek-supplied}μενοι ε[βλασφη]{.greek-supplied}μουν αυτον κ[ινουν]{.greek-supplied}τες τας κεφαλας [αυ]{.greek-supplied}των και λεγοντε[ς]{.greek-supplied} ουα ο καταλυων τον ναον και [οικοδομων]{.greek-added} εν τρισιν ημεραις [οικοδομων]{.greek-omitted}[15:29]{.aside}

σωσον σεαυτον [και]{.greek-omitted} [καταβα]{.greek-omitted} [καταβας]{.greek-added} απο του σταυρου[15:30]{.aside}

ομοιως και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} π[ρο]{.unclear}ς αλληλους μετα των γραμματ[ε]{.unclear}ων ελεγον αλλους εσωσεν εα[υτ]{.unclear}ον ου δυν[α]{.unclear}ται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς [του]{.greek-omitted} [ισραηλ]{.greek-abbr} καταβ[α]{.unclear}τω νυν απο του στ[αυ]{.greek-supplied}[ρου]{.greek-supplied} [ι]{.unclear}να [ιδωμεν]{.greek-omitted} [ειδωμεν]{.greek-added} [και]{.greek-supplied} πιστευσωμε[ν]{.unclear} [αυτω]{.greek-omitted} [και]{.greek-supplied} οι συνεσταυρω[με]{.greek-supplied}νοι [συν]{.greek-added} αυτω [ω]{.greek-supplied}νειδιζον αυτον[15:32]{.aside}

[[και]{.greek-supplied}]{.greek-added} [γ]{.greek-supplied}[ε]{.unclear}νομενης [δε]{.greek-omitted} ωρ[ας]{.unclear} [εκτ]{.greek-supplied}ης σκοτ[ο]{.unclear}ς εγε[ν]{.unclear}[ετο]{.greek-supplied} [ε]{.unclear}φ ολην τ[ην]{.unclear} [γην]{.greek-supplied} εως ωρ[ας]{.unclear} [ενατης]{.greek-omitted} [[ε]{.unclear}[ν]{.unclear}νατ[ης]{.unclear}]{.greek-added}[15:33]{.aside}

κα[ι]{.greek-supplied} [τ]{.unclear}η [ενατη]{.greek-added} ω[ρα]{.greek-supplied} [τη]{.greek-omitted} [ενατη]{.greek-omitted} εβοη[σε]{.unclear}ν ο [ιησους]{.greek-abbr} φω[νη]{.greek-supplied} μεγαλη [λεγων]{.greek-omitted} ελωι ε[λωι]{.greek-supplied} [λιμα]{.greek-omitted} [λε[μα]{.greek-supplied}]{.greek-added} [σ]{.greek-supplied}αβαχ[θ]{.unclear}[ανι]{.greek-supplied} ο εσ[τ]{.unclear}[ιν]{.greek-supplied} μ[εθ]{.unclear}ερμηνευ[ο]{.unclear}μεν[ον]{.greek-supplied} [ο]{.greek-supplied} [[θεος]{.greek-abbr}]{.greek-supplied} [μου]{.greek-supplied} ο [θεος]{.greek-abbr} μ[ου]{.unclear} [εις]{.greek-supplied} [τι]{.greek-supplied} [[εγκα]{.greek-supplied}[τελ]{.greek-supplied}[ιπ]{.unclear}[ες]{.greek-supplied}]{.greek-added} [με]{.greek-supplied} [εγκατελιπες]{.greek-omitted}[15:34]{.aside}

κ[αι]{.greek-supplied} [τινες]{.greek-supplied} [των]{.greek-supplied} [παρεσ]{.greek-supplied}[τηκοτων]{.greek-supplied} [ακου]{.greek-supplied}[σαντε]{.greek-supplied}[ς]{.unclear} [ελ]{.unclear}[εγον]{.greek-supplied} [ιδου]{.greek-omitted} [[ιδε]{.greek-supplied}]{.greek-added} [ηλι]{.greek-supplied}αν φ[ω]{.unclear}[νει]{.greek-supplied}[15:35]{.aside}

[δ]{.unclear}ραμων δε [εις]{.greek-omitted} [τις]{.greek-added} και [γ]{.unclear}εμισας σπογγον [ο]{.greek-supplied}[ξ]{.unclear}ους περιθεις [τε]{.greek-omitted} καλα[μ]{.greek-supplied}ω εποτιζ[ε]{.unclear}ν [α]{.unclear}υτον [λ]{.greek-supplied}[ε]{.unclear}γων αφετε ιδω[μ]{.unclear}εν ει ερχεται [η]{.unclear}[λι]{.greek-supplied}[α]{.unclear}ς καθελειν αυ[τ]{.unclear}[ον]{.greek-supplied}[15:36]{.aside}

[ο]{.unclear} δε [ιησους]{.greek-abbr} αφεις φω[νην]{.greek-supplied} [μ]{.unclear}εγαλην εξεπ[ν]{.unclear}[ευσεν]{.greek-supplied}[15:37]{.aside}

και το καταπ[ε]{.unclear}[τα]{.greek-supplied}[σ]{.greek-supplied}[μ]{.unclear}α το[υ]{.unclear} [ναου]{.greek-supplied} [εσχισθη]{.greek-supplied} [ε]{.greek-supplied}ι[ς]{.unclear} [δ]{.unclear}[υο]{.greek-supplied} [απο]{.greek-omitted} [[απ]{.greek-supplied}]{.greek-added} [ανωθεν]{.greek-supplied} [ε]{.greek-supplied}ως κατω[15:38]{.aside}

[ιδ]{.greek-supplied}[ω]{.unclear}ν δε ο κεντ[υ]{.greek-supplied}ριω[ν]{.greek-supplied} [ο]{.greek-supplied} [π]{.unclear}αρεστη[κ]{.unclear}ως εξ ε[ν]{.greek-supplied}[αντιας]{.unclear} [α]{.unclear}υτ[ου]{.greek-supplied} οτι [ουτως]{.greek-supplied} [[εκραξεν]{.greek-supplied}]{.greek-added} [κραξας]{.greek-omitted} [εξεπνευσεν]{.greek-omitted} ειπεν αληθως [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} [ουτος]{.greek-supplied} [υιος]{.greek-abbr} [[θεου]{.greek-abbr}]{.greek-added} ην [θεου]{.greek-omitted}[15:39]{.aside}

[ησαν]{.greek-supplied} [δε]{.greek-supplied} [και]{.greek-supplied} [γ]{.greek-supplied}υναι[κες]{.greek-supplied} [απο]{.greek-supplied} [μακ]{.greek-supplied}ροθεν [θεωρουσαι]{.greek-supplied} εν αις [ην]{.greek-omitted} [και]{.greek-supplied} [μαρι]{.greek-supplied}α η μα[γδαληνη]{.greek-supplied} και μα[ρια]{.greek-supplied} [η]{.greek-supplied} [του]{.greek-omitted} [ιακ]{.greek-supplied}ωβου του μικρου και [ιωση]{.greek-omitted} [ιωσητος]{.greek-added} [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι [και]{.greek-omitted} οτε ην εν τη γαλι[λαια]{.unclear} ηκολουθουν αυ[τω]{.greek-supplied} [και]{.greek-supplied} διηκον[ουν]{.greek-supplied} [αυτ]{.greek-supplied}[ω]{.unclear} και [αλλαι]{.greek-supplied} [πολ]{.greek-supplied}λαι αι [συναναβασ]{.greek-supplied}αι αυτω [εις]{.greek-supplied} [ιεροσο]{.greek-supplied}[λ]{.unclear}υμα[15:41]{.aside}

[και]{.greek-supplied} [ηδη]{.unclear} [ο]{.unclear}ψιας γενο[μ]{.unclear}ενης [επει]{.greek-omitted} [επι]{.greek-added} ην παρασκευη ο εστι[ν]{.unclear} προσαββατον[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ [ο]{.greek-omitted} απο αριμαθαιας ευσχημων βουλευτης ος και [α]{.unclear}υτ[ος]{.unclear} ην προσ[δε]{.unclear}χομενος την βασιλειαν του [θεου]{.greek-abbr} [τολμησας]{.greek-omitted} [τολμησαν]{.greek-added} εισηλ[θεν]{.greek-supplied} προς πιλα[τον]{.greek-supplied} [και]{.greek-supplied} ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθ[αυ]{.greek-supplied}μασεν ε[ι]{.greek-supplied} [ηδη]{.greek-omitted} [τεθνηκεν]{.greek-omitted} [και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [κεντυριωνα]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ει]{.greek-omitted} [παλαι]{.greek-omitted} [απεθανεν]{.greek-omitted}[[15:44 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [γνους]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} κε[ν]{.unclear}τ[υ]{.unclear}ρ[ιωνος]{.greek-supplied} [εδω]{.greek-supplied}ρ[η]{.unclear}σατο τ[ο]{.unclear} [σωμ]{.unclear}[α]{.greek-supplied} [τ]{.greek-supplied}[ω]{.unclear} [ι]{.unclear}ω[σηφ]{.greek-supplied}[15:45]{.aside}

και [α]{.unclear}γ[ο]{.unclear}ρ[α]{.unclear}σ[ας]{.unclear} [σινδονα]{.greek-supplied} [και]{.greek-omitted} [καθ]{.greek-supplied}[ελ]{.unclear}ων [αυτον]{.greek-supplied} [ενειλ]{.greek-supplied}ησ[εν]{.unclear} τη σινδονι και [κατεθηκεν]{.greek-omitted} [εθηκεν]{.greek-added} αυτο[ν]{.unclear} εν [μνημειω]{.greek-omitted} [μν[η]{.unclear}μιω]{.greek-added} ο ην [λε]{.unclear}[λα]{.greek-supplied}τομημενον εκ πετρας και προ[σε]{.unclear}κυλισεν λιθον επ[ι]{.unclear} την θυραν του [μνημειου]{.greek-omitted} [μνημιου]{.greek-added}[15:46]{.aside}

η δε μαρ[ια]{.unclear} η μ[α]{.unclear}γδαληνη κα[ι]{.unclear} μαρια [ιωση]{.greek-omitted} [η]{.greek-added} [ιωσητος]{.greek-added} εθεωρου[ν]{.unclear} που [τιθεται]{.greek-omitted} [τ[ε]{.unclear}[θει]{.greek-supplied}ται]{.greek-added}[15:47]{.aside}

### Chapter 16

[και]{.unclear} διαγε[νο]{.greek-supplied}μεν[ου]{.greek-supplied} [τ]{.greek-supplied}[ο]{.unclear}υ σαβ[β]{.unclear}[ατου]{.greek-supplied} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [σαλωμη]{.greek-omitted} [ηγορασαν]{.greek-omitted} [αρωματα]{.greek-omitted} [ινα]{.greek-omitted} [ελθουσαι]{.greek-omitted} [αλειψωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[[16:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [λιαν]{.greek-omitted} [πρωι]{.greek-omitted} [της]{.greek-omitted} [μιας]{.greek-omitted} [[μια]{.unclear}]{.greek-added} [[των]{.greek-supplied}]{.greek-added} [σαββατων]{.greek-supplied} ερχον[ται]{.greek-supplied} [επι]{.greek-supplied} [το]{.greek-supplied} [μνη]{.unclear}[μειον]{.greek-supplied} [ανατειλαν]{.greek-supplied}τος του [ηλιου]{.greek-supplied}[16:2]{.aside}

[και]{.greek-supplied} ελεγον [προς]{.greek-supplied} [εαυτας]{.greek-supplied} τις απο[κυλισει]{.greek-supplied} [ημιν]{.greek-supplied} τ[ο]{.unclear}ν λι[θ]{.unclear}[ον]{.greek-supplied} [εκ]{.greek-supplied} [της]{.greek-supplied} θυρας τ[ου]{.greek-supplied} [μνημειου]{.greek-supplied}[16:3]{.aside}

και αν[α]{.unclear}[βλεψασαι]{.greek-supplied} [θε]{.greek-supplied}ωρουσ[ι]{.unclear}[ν]{.greek-supplied} [οτι]{.greek-supplied} [αποκε]{.greek-supplied}[κ]{.unclear}[υλισται]{.greek-supplied} [ο]{.greek-supplied} [λιθος]{.greek-supplied} [η]{.unclear}ν [γ]{.unclear}[αρ]{.greek-supplied} [μεγας]{.greek-supplied} [σφο]{.greek-supplied}δρα[16:4]{.aside}

κ[αι]{.greek-supplied} [εισελθουσαι]{.greek-supplied} [εις]{.unclear} το [μνημειον]{.greek-supplied} ειδον [ν]{.unclear}[εανισκον]{.greek-supplied} καθη[μ]{.unclear}[ενον]{.greek-supplied} [εν]{.greek-supplied} [τοις]{.greek-supplied} δεξιοι[ς]{.unclear} [περιβεβλη]{.greek-supplied}μεν[ον]{.unclear} [στολην]{.greek-supplied} [λευκην]{.greek-supplied} κα[ι]{.unclear} ε[ξ]{.unclear}[εθαμβηθησαν]{.greek-supplied}[16:5]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυταις]{.greek-omitted} [μη]{.greek-omitted} [εκθαμβεισθε]{.greek-omitted} [ιησουν]{.greek-omitted} [ζητειτε]{.greek-omitted} [τον]{.greek-omitted} [ναζαρηνον]{.greek-omitted} [τον]{.greek-omitted} [εσταυρωμενον]{.greek-omitted} [ηγερθη]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [ωδε]{.greek-omitted} [ιδε]{.greek-supplied} [ο]{.greek-supplied} [τοπος]{.greek-supplied} [ο]{.greek-supplied}που [εθηκαν]{.greek-supplied} [αυ]{.greek-supplied}τον[16:6]{.aside}

[αλλ]{.greek-omitted} [[αλλα]{.greek-supplied}]{.greek-added} [υπαγε]{.greek-supplied}τε ειπα[τε]{.greek-supplied} [τοις]{.greek-supplied} [μαθ]{.greek-supplied}ηταις αυ[του]{.greek-supplied} [και]{.greek-supplied} [τ]{.greek-supplied}ω πετρω [οτι]{.greek-supplied} [προαγ]{.greek-supplied}ει υμας [εις]{.greek-supplied} [την]{.greek-supplied} [γα]{.greek-supplied}λιλαιαν [εκει]{.greek-supplied} [αυτο]{.greek-supplied}ν οψεσθε [καθως]{.greek-supplied} [ει]{.greek-supplied}πεν υμιν[16:7]{.aside}

[και]{.greek-supplied} [εξελθο]{.greek-supplied}υσαι εφυ[γον]{.greek-supplied} [απο]{.greek-supplied} [τ]{.greek-supplied}ου μνη[μειου]{.greek-supplied} [ειχε]{.greek-supplied}ν [δε]{.greek-omitted} [γαρ]{.greek-added} αυ[τας]{.greek-supplied} [τρομο]{.greek-supplied}ς και εκ[στασις]{.greek-supplied} [και]{.greek-supplied} ουδεν[ι]{.greek-supplied} [ουδεν]{.greek-supplied} [ει]{.greek-supplied}πον εφο[βουντο]{.greek-supplied} [γ]{.greek-supplied}αρ[[16:8 *(lacunose)*]{.lacunose}]{.aside}

[ταυτα]{.greek-added} και [εξελθουσαι]{.greek-omitted} [εφυγον]{.greek-omitted} [αυτος]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} απο [ανατολης]{.greek-added} [αχρι]{.greek-added} [δυσεως]{.greek-added} [εξαπεστειλεν]{.greek-added} [δι]{.greek-added} [αυτων]{.greek-added} [του]{.greek-omitted} [το]{.greek-added} [μνημειου]{.greek-omitted} [ειχεν]{.greek-omitted} [ιερον]{.greek-added} [και]{.greek-added} [αφθαρτον]{.greek-added} [κηρυγμα]{.greek-added} [της]{.greek-added} [αιωνιου]{.greek-added} [σωτηριας]{.greek-added} [αμην]{.greek-added} [εστιν]{.greek-added} δε [αυτας]{.greek-omitted} [τρομος]{.greek-omitted} και [ταυτα]{.greek-added} [φερομενα]{.greek-added} [μετα]{.greek-added} [το]{.greek-added} [εκστασις]{.greek-omitted} [και]{.greek-omitted} [ουδενι]{.greek-omitted} [ουδεν]{.greek-omitted} [ειπον]{.greek-omitted} [εφοβουντο]{.greek-omitted} [εφοβουτο]{.greek-added} γαρ[[16:8 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη [αφ]{.greek-omitted} [παρ]{.greek-added} ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθ[εισα]{.greek-supplied} απηγγειλεν [τοις]{.greek-supplied} με[τ]{.greek-supplied} [αυτου]{.greek-omitted} [γενομενοις]{.greek-omitted} [πενθουσιν]{.greek-omitted} [και]{.greek-omitted} [κλαιουσιν]{.greek-omitted}[[16:10 *(lacunose)*]{.lacunose}]{.aside}

