---
title: "Collation of Byz^RP^ vs 20096 (96)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 96 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20096).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 96                                   	| λογος                              	|
| 96 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 96 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 96               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 96                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 96 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 96                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 2

[γενομενης]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [φωνης]{.greek-omitted} [ταυτης]{.greek-omitted} [συνηλθεν]{.greek-omitted} [το]{.greek-omitted} [πληθος]{.greek-omitted} [κ]{.greek-supplied}[α]{.unclear}ι συνεχυθη οτι η[κουο]{.greek-supplied}ν εις εκ[α]{.unclear}στο[ς]{.unclear} τη [ι]{.unclear}δι[α]{.unclear} [διαλε]{.greek-supplied}κτω λα[λ]{.unclear}ο[υντων]{.unclear} [αυ]{.unclear}[τω]{.greek-supplied}ν[2:6]{.aside}

εξιστα[ν]{.unclear}το δε [παντ]{.greek-supplied}[ες]{.unclear} [κ]{.unclear}αι εθα[υμα]{.unclear}[ζο]{.greek-supplied}ν λε[γοντ]{.greek-supplied}ες [π]{.unclear}ρος αλληλους [ουκ]{.greek-omitted} [[ουχ]{.greek-supplied}]{.greek-added} [ι]{.greek-supplied}δ[ου]{.unclear} [παντες]{.greek-omitted} [απαντες]{.greek-added} ου[τοι]{.unclear} [εισιν]{.greek-supplied} οι [λ]{.unclear}αλο[υν]{.unclear}τ[ες]{.unclear} [γαλιλαιοι]{.greek-omitted} [[γαλει]{.unclear}[λαιοι]{.greek-supplied}]{.greek-added}[2:7]{.aside}

[και]{.unclear} πως [ημεις]{.unclear} α[κ]{.unclear}ο[υ]{.unclear}[ομε]{.greek-supplied}ν εκαστος τη [ιδια]{.unclear} [δια]{.unclear}[λεκτ]{.greek-supplied}ω ημω[ν]{.unclear} εν η [ε]{.unclear}γεν[νηθ]{.greek-supplied}[η]{.unclear}μεν[2:8]{.aside}

[παρ]{.unclear}θοι και [μ]{.unclear}η[δοι]{.greek-supplied} [κ]{.unclear}αι ελαμι[ται]{.unclear} [και]{.unclear} οι κα[τοικ]{.greek-supplied}ουντες την μεσο[ποτα]{.greek-supplied}μιαν ιουδαιαν τε και [καπ]{.greek-supplied}[π]{.unclear}αδοκιαν ποντον [και]{.greek-supplied} [τ]{.greek-supplied}η[ν]{.unclear} ασιαν[2:9]{.aside}

φρυγιαν τ[ε]{.unclear} [και]{.greek-supplied} [π]{.greek-supplied}α[μ]{.unclear}φυλιαν αιγυπτον [και]{.greek-supplied} [τ]{.greek-supplied}[α]{.unclear} μερη [τ]{.unclear}ης λιβυης τη[ς]{.unclear} [κατα]{.greek-supplied} [κυρ]{.unclear}ηνην και οι επι[δημ]{.greek-supplied}ουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[[ιουδ]{.greek-supplied}αιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυ[τοι]{.greek-supplied}]{.greek-added} [κ]{.greek-supplied}[ρ]{.unclear}ητες και αραβες ακου[ομεν]{.greek-supplied} [λαλουντ]{.greek-supplied}[ω]{.unclear}ν [αυ]{.unclear}των [ταις]{.greek-omitted} [ημετεραις]{.greek-omitted} [γλωσσαις]{.greek-omitted} [τα]{.greek-omitted} [μεγαλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[2:11]{.aside}

εξισταντο δε παν[τες]{.greek-supplied} [και]{.greek-supplied} διηπορουν αλλος [προς]{.greek-supplied} αλλον λεγοντες τ[ι]{.greek-supplied} [αν]{.greek-omitted} [θελοι]{.greek-omitted} [[θελει]{.greek-supplied}]{.greek-added} τουτο ειναι[2:12]{.aside}

ετε[ροι]{.greek-supplied} [δε]{.greek-supplied} χλευαζοντες [[διαχλευαζοντες]{.corr}]{.greek-added} ελεγ[ον]{.greek-supplied} [οτι]{.greek-supplied} γλευκους μεμεστ[ωμε]{.greek-supplied}νοι εισιν[2:13]{.aside}

στα[θεις]{.greek-supplied} δε [ο]{.greek-added} πετ[ρ]{.unclear}ος συν το[ις]{.greek-supplied} [εν]{.greek-supplied}δεκα επηρεν την [φ]{.unclear}[ωνην]{.greek-supplied} αυτου και απεφθε[γ]{.unclear}[ξατο]{.greek-supplied} αυτοις ανδρες ιου[δαιοι]{.greek-supplied} και οι κατοικουντ[ες]{.greek-supplied} [ιερουσαλημ]{.greek-abbr} [παντες]{.greek-added} [απαντες]{.corr} τουτο υμι[ν]{.unclear} [γνω]{.greek-supplied}στον εστω και [ενωτισασθε]{.greek-omitted} [ενω[τισασ]{.greek-supplied}θαι]{.greek-added} τα ρηματα μου[2:14]{.aside}

ο[υ]{.greek-supplied} [γαρ]{.greek-supplied} ως [υμεις]{.greek-omitted} [υμις]{.greek-added} υπολαμβα[ν]{.unclear}[ετε]{.greek-supplied} ουτοι μεθυουσιν ε[στιν]{.greek-supplied} γαρ ωρα τριτη της η[μ]{.unclear}[ερας]{.greek-supplied}[2:15]{.aside}

αλλα τουτο εστιν το ε[ιρημε]{.greek-supplied}νον δια του προφη[τ]{.unclear}[ου]{.greek-supplied} ιωηλ[2:16]{.aside}

και εσται ε[ν]{.greek-supplied} [ταις]{.greek-supplied} εσχαταις ημεραις λ[εγει]{.greek-supplied} ο [θεος]{.greek-abbr} [εκχεω]{.greek-omitted} [εκχαιω]{.greek-added} απο τ[ου]{.greek-supplied} [[πνευματος]{.greek-abbr}]{.greek-supplied} μο[υ]{.unclear} ε[πι]{.unclear} [πασ]{.unclear}[αν]{.greek-supplied} [σαρκα]{.greek-supplied} [και]{.greek-omitted} [προφητευσουσιν]{.greek-omitted} [οι]{.greek-omitted} [υιοι]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [θυγατερες]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted} [υμων]{.greek-omitted} [ορασεις]{.greek-omitted} [οψονται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [υμων]{.greek-omitted} [ενυπνια]{.greek-omitted} [ενυπνιασθησονται]{.greek-omitted}[2:17]{.aside}

### Chapter 26

[εις]{.greek-omitted} [ην]{.greek-omitted} [το]{.greek-omitted} [δωδεκαφυλον]{.greek-omitted} [ημων]{.greek-omitted} [εν]{.greek-omitted} [εκτενεια]{.greek-omitted} [νυκτα]{.greek-omitted} [και]{.greek-omitted} [ημεραν]{.greek-omitted} [λατρευον]{.greek-omitted} [ελπιζει]{.greek-omitted} [καταντησαι]{.greek-omitted} [περι]{.greek-omitted} [ης]{.greek-omitted} [ελπιδος]{.greek-omitted} [εγκαλουμαι]{.greek-omitted} [βασιλευ]{.greek-omitted} [αγριππα]{.greek-omitted} [υπο]{.unclear} [ιο]{.unclear}υδαι[ω]{.unclear}[ν]{.greek-supplied} [[βα]{.greek-supplied}σιλευ]{.greek-added}[26:7]{.aside}

τι απιστον κ[ρι]{.greek-supplied}[ν]{.greek-supplied}[ε]{.unclear}ται παρ υμιν ει ο [θεος]{.greek-abbr} ν[ε]{.greek-supplied}[κ]{.greek-supplied}[ρ]{.unclear}ους εγειρει[26:8]{.aside}

εγω μ[ε]{.unclear}[ν]{.greek-supplied} [ο]{.greek-supplied}υν εδοξα εμαυτω προ[ς]{.greek-supplied} [τ]{.greek-supplied}[ο]{.unclear} ονομα [ιησου]{.greek-abbr} του ναζωρ[αι]{.greek-supplied}[ο]{.greek-supplied}υ δειν πολλα εναντια [π]{.unclear}[ρα]{.greek-supplied}[ξα]{.greek-supplied}ι[26:9]{.aside}

ο και εποιησα εν ιερο[σο]{.greek-supplied}[λυ]{.greek-supplied}μοις και πολλους [[τ]{.unclear}[ε]{.greek-supplied}]{.greek-added} [τω]{.greek-supplied}ν αγιων εγω [εν]{.greek-added} φυλα[καις]{.greek-supplied} [κατεκλεισα]{.greek-omitted} [[κα]{.greek-supplied}τεκλισα]{.greek-added} την παρα των [αρ]{.greek-supplied}[χι]{.greek-supplied}ερεων εξουσιαν λαβ[ω]{.unclear}[ν]{.greek-supplied} [αν]{.greek-supplied}αιρουμενων τε αυτ[ω]{.unclear}[ν]{.greek-supplied} [κα]{.greek-supplied}τηνεγκα ψηφον[26:10]{.aside}

[και]{.greek-supplied} κατα πασας τας συναγ[ω]{.greek-supplied}[γα]{.greek-supplied}ς πολλακις [τιμωρων]{.greek-omitted} [τειμωρω[ν]{.greek-supplied}]{.greek-added} [αυ]{.greek-supplied}τους ηναγκαζον βλασ[φη]{.greek-supplied}[με]{.greek-supplied}ιν περισσως τε εμμ[αι]{.greek-supplied}[νο]{.greek-supplied}μενος [αυτοις]{.greek-omitted} [αυτους]{.greek-added} εδιω[κον]{.greek-supplied} [ε]{.greek-supplied}[ω]{.greek-supplied}[ς]{.unclear} και εις τας εξω πολει[ς]{.unclear}[26:11]{.aside}

[εν]{.greek-supplied} οις [και]{.greek-omitted} πορευομενος ει[ς]{.unclear} [τη]{.greek-supplied}[ν]{.unclear} δαμασκον μετ εξου[σια]{.greek-supplied}ς και επιτροπ[η]{.unclear}ς [της]{.greek-omitted} [παρα]{.greek-omitted} τω[ν]{.greek-supplied} [αρχιερεων]{.greek-omitted}[26:12]{.aside}

[ημερας]{.greek-omitted} [μεσης]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [ειδον]{.greek-omitted} [βασιλευ]{.greek-omitted} [ουρανοθεν]{.greek-omitted} [υπερ]{.greek-omitted} [τ]{.greek-supplied}[η]{.unclear}ν λαμ[προ]{.unclear}[τητα]{.greek-supplied} [του]{.greek-supplied} [ηλι]{.greek-supplied}[ο]{.greek-supplied}υ περιλαμψαν με φ[ω]{.unclear}[ς]{.greek-supplied} [κ]{.greek-supplied}αι τους συν εμοι πο[ρ]{.unclear}[ευ]{.greek-supplied}[ο]{.greek-supplied}μενους[26:13]{.aside}

παντων [δε]{.greek-omitted} [[τ]{.unclear}[ε]{.greek-supplied}]{.greek-added} [κ]{.greek-supplied}[α]{.unclear}ταπεσοντων ημω[ν]{.unclear} [εις]{.greek-supplied} [τ]{.greek-supplied}ην γην ηκουσα φω[ν]{.unclear}[ην]{.greek-supplied} [λαλουσαν]{.greek-omitted} [[λ]{.unclear}εγουσαν]{.greek-added} προς με [και]{.greek-omitted} [λεγουσαν]{.greek-omitted} τη [εβρα]{.greek-supplied}[ι]{.greek-supplied}δι διαλεκτω σαουλ σα[ουλ]{.greek-supplied} [τ]{.greek-supplied}ι με διωκεις σκληρον [σοι]{.greek-supplied} [π]{.unclear}ρος κεντρα λακτ[ι]{.unclear}ζει[ν]{.unclear}[26:14]{.aside}

[εγ]{.greek-supplied}ω [δε]{.corr} ειπον τις ει [κυριε]{.greek-abbr} [ο]{.unclear} δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [[ιησους]{.greek-abbr}]{.greek-supplied} [ο]{.unclear}ν συ διωκεις[26:15]{.aside}

αλλα α[ν]{.unclear}[α]{.greek-supplied}[σ]{.greek-supplied}τηθι και στηθι επι το[υς]{.greek-supplied} [π]{.unclear}οδας σου εις τουτο γ[α]{.unclear}[ρ]{.greek-supplied} [ω]{.greek-supplied}φθην σοι προχειρισασ[θαι]{.greek-supplied} [σ]{.greek-supplied}ε υπηρετην και μαρτυ[ρα]{.greek-supplied} ων τε ειδες ων τε οφ[θ]{.unclear}[η]{.greek-supplied}[σ]{.greek-supplied}ομαι σοι[26:16]{.aside}

εξαιρουμεν[ος]{.greek-supplied} [σ]{.unclear}ε εκ του λαου και [εκ]{.greek-added} τ[ω]{.unclear}[ν]{.greek-supplied} εθνων εις ους εγω [απ[ο]{.greek-supplied}στελω]{.greek-added} σε [αποστελλω]{.greek-omitted}[26:17]{.aside}

ανοιξα[ι]{.unclear} οφθ[αλ]{.greek-supplied}[μ]{.unclear}ο[υ]{.unclear}ς [αυτων]{.greek-omitted} [[τυ]{.unclear}φλων]{.greek-added} του [υποστρεψαι]{.greek-omitted} [ε[π]{.unclear}[ιστρεψαι]{.greek-supplied}]{.greek-added} [απο]{.greek-omitted} [σκοτους]{.greek-omitted} [εις]{.greek-omitted} [φως]{.greek-omitted} [και]{.greek-omitted} [της]{.greek-omitted} [εξουσιας]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [του]{.greek-omitted} [λαβειν]{.greek-omitted} [αυτους]{.greek-omitted} [αφεσιν]{.greek-omitted} [αμαρτιων]{.greek-omitted} [και]{.greek-omitted} [κληρον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ηγιασμενοις]{.greek-omitted} [πιστει]{.greek-omitted} [τη]{.greek-omitted} [εις]{.greek-omitted} [εμε]{.greek-omitted}[26:18]{.aside}

