---
title: "Collation of Byz^RP^ vs 20093 (93)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 93 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20093).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 93                                   	| λογος                              	|
| 93 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 93 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 93               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 93                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 93 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 93                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 24

[ακουσας]{.greek-omitted} [δε]{.greek-omitted} [ταυτα]{.greek-omitted} [ο]{.unclear} [φη]{.unclear}λιξ ανε[β]{.unclear}αλ[ε]{.unclear}το αυτους α[κ]{.unclear}ριβεστερον ειδως τα περι της οδου [ε]{.unclear}ιπ[ω]{.unclear}ν οτ[α]{.unclear}ν λυσιας ο χιλιαρχος [κ]{.unclear}αταβη διαγνωσομαι τα καθ υμας[24:22]{.aside}

διατα[ξ]{.unclear}αμ[ε]{.greek-supplied}[ν]{.unclear}ος τε τω εκατον[τ]{.unclear}αρ[χ]{.unclear}[η]{.greek-supplied} τηρεισθαι τον παυλον εχειν τε ανεσιν και μηδεν[α]{.unclear} κωλυει[ν]{.unclear} τω[ν]{.unclear} [ι]{.unclear}διω[ν]{.unclear} αυτου [υπηρετειν]{.greek-omitted} [υπερετειν]{.greek-added} η [π]{.unclear}ροσερχ[ε]{.unclear}σθα[ι]{.unclear} [α]{.unclear}υ[τ]{.unclear}ω[24:23]{.aside}

μετα δε [η]{.unclear}μ[ε]{.greek-supplied}ρας τινας πα[ρ]{.unclear}αγενομεν[ος]{.unclear} [ο]{.unclear} φηλιξ συ[ν]{.unclear} δρουσιλλ[η]{.greek-supplied} [τ]{.greek-supplied}[η]{.unclear} γ[υ]{.greek-supplied}ναικι ο[υ]{.unclear}[ση]{.greek-supplied} ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου περ[ι]{.unclear} [τη]{.unclear}ς εις [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added} πιστεως[24:24]{.aside}

διαλεγομε[νου]{.unclear} δε αυτο[υ]{.unclear} [πε]{.greek-supplied}ρι δικα[ιοσυνης]{.greek-supplied} και εγκρατ[ει]{.greek-supplied}ας και του [κ]{.unclear}[ρι]{.greek-supplied}ματος του [μ]{.unclear}ελλοντος εσεσθαι εμφοβος γενομενος ο φηλιξ απεκριθη το νυν εχον πο[ρ]{.unclear}ευου καιρον δε [μεταλαβων]{.greek-omitted} [λαβων]{.greek-added} μετακαλεσομαι σε[24:25]{.aside}

αμα και [ελπι]{.greek-added} [ελπιζων]{.greek-omitted} [οτι]{.greek-omitted} [χρηματα]{.greek-omitted} [δοθησεται]{.greek-omitted} [αυτω]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [παυλου]{.greek-omitted} [οπως]{.greek-omitted} [λυση]{.greek-omitted} [αυτον]{.greek-omitted} [διο]{.greek-omitted} [και]{.greek-omitted} [πυκνοτερον]{.greek-omitted} [αυτον]{.greek-omitted} [μεταπεμπομενος]{.greek-omitted} [ωμιλει]{.greek-omitted} [αυτω]{.greek-omitted}[24:26]{.aside}

[[ζων]{.greek-supplied}]{.greek-added} [αμα]{.greek-omitted} [και]{.greek-omitted} [ελπιζων]{.greek-omitted} [οτι]{.greek-supplied} [χρημα]{.unclear}[τα]{.greek-supplied} [δο]{.greek-supplied}[θ]{.unclear}ησε[ται]{.greek-supplied} [αυ]{.greek-supplied}τ[ω]{.unclear} [υ]{.unclear}πο [το]{.greek-supplied}υ [π]{.greek-supplied}αυλου οπ[ως]{.greek-supplied} [λυ]{.greek-supplied}[ση]{.unclear} αυ[τ]{.unclear}ο[ν]{.unclear} [διο]{.greek-supplied} [και]{.greek-supplied} [π]{.greek-supplied}υ[κνοτερ]{.unclear}ο[ν]{.unclear} [αυ]{.greek-supplied}τον [μετ]{.unclear}α[πεμπ]{.greek-supplied}ομεν[ος]{.greek-supplied} [ωμιλει]{.greek-supplied} αυτ[ω]{.greek-supplied}[24:26 | instance no. 2]{.aside}

[διετι]{.greek-supplied}ας [δε]{.unclear} [πληρωθει]{.greek-supplied}ση[ς]{.greek-supplied} [ελαβ]{.greek-supplied}ε[ν]{.unclear} δι[αδο]{.unclear}[χ]{.greek-supplied}ον ο φηλ[ι]{.unclear}ξ [πορκιον]{.unclear} φη[στον]{.greek-supplied} θελ[ω]{.unclear}[ν]{.greek-supplied} [τε]{.greek-omitted} [χαριτας]{.greek-omitted} [καταθεσθαι]{.greek-omitted} [τοις]{.greek-omitted} [ιουδαιοις]{.greek-omitted} [ο]{.greek-omitted} [φηλιξ]{.greek-omitted} [κατελιπεν]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [δεδεμενον]{.greek-omitted}[24:27]{.aside}

