---
title: "Collation of Byz^RP^ vs 20104 (104)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 104 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20104).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 104                                   	| λογος                              	|
| 104 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 104 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 104               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 104                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 104 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 104                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

[και]{.greek-omitted} [εθαμβηθησαν]{.greek-omitted} [παντες]{.greek-omitted} [ωστε]{.greek-omitted} [συζητειν]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [λεγοντας]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [τουτο]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [διδαχη]{.greek-omitted} [η]{.greek-omitted} [καινη]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} κατ ε[ξ]{.unclear}ου[σιαν]{.greek-supplied} κα[ι]{.unclear} [τοις]{.unclear} [π]{.unclear}[νευ]{.greek-supplied}μασι[ν]{.unclear} [τοις]{.greek-supplied} [α]{.greek-supplied}κ[αθαρτοις]{.greek-supplied} ε[π]{.unclear}[ιτασσει]{.greek-supplied} κα[ι]{.greek-supplied} [υπακουου]{.greek-supplied}σιν α[υτω]{.unclear}[1:27]{.aside}

[[και]{.greek-supplied}]{.greek-added} [ε]{.greek-supplied}ξη[λθεν]{.greek-supplied} [δε]{.greek-omitted} [η]{.greek-supplied} [ακοη]{.greek-supplied} [αυτου]{.greek-supplied} [ευθυς]{.greek-supplied} [[πα]{.unclear}[νταχου]{.greek-supplied}]{.greek-added} [εις]{.greek-supplied} [ο]{.greek-supplied}[λην]{.greek-supplied} [την]{.greek-supplied} [περι]{.greek-supplied}[χ]{.unclear}[ωρον]{.greek-supplied} [της]{.greek-supplied} [γαλιλαιας]{.greek-omitted} [[γα]{.greek-supplied}λαιας]{.greek-added}[1:28]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} ε[ξε]{.unclear}λθοντε[ς]{.unclear} ηλθ[ον]{.greek-supplied} ει[ς]{.greek-supplied} [την]{.greek-supplied} [ο]{.unclear}ι[κ]{.unclear}ι[α]{.unclear}ν [σιμω]{.greek-supplied}[ν]{.unclear}ο[ς]{.unclear} κ[αι]{.greek-supplied} [ανδρε]{.greek-supplied}ου [μετα]{.greek-supplied} [ιακω]{.greek-supplied}β[ου]{.greek-supplied} [και]{.greek-supplied} [ιωαν]{.greek-supplied}[ν]{.unclear}[ου]{.greek-supplied} [και]{.greek-added} [ευ[θεως]{.greek-supplied}]{.greek-added} [ε[ξε]{.unclear}λθοντε[ς]{.unclear}]{.greek-added} [ηλθ[ον]{.greek-supplied}]{.greek-added} [ει[ς]{.greek-supplied}]{.greek-added} [[την]{.greek-supplied}]{.greek-added} [[ο]{.unclear}ι[κ]{.unclear}ι[α]{.unclear}ν]{.greek-added} [[σιμω]{.greek-supplied}[ν]{.unclear}ο[ς]{.unclear}]{.greek-added} [κ[αι]{.greek-supplied}]{.greek-added} [[ανδρε]{.greek-supplied}ου]{.greek-added} [[μετα]{.greek-supplied}]{.greek-added} [[ιακω]{.greek-supplied}β[ου]{.greek-supplied}]{.greek-added} [[και]{.greek-supplied}]{.greek-added} [[ιωαν]{.greek-supplied}[ν]{.unclear}[ου]{.greek-supplied}]{.greek-added}[1:29]{.aside}

[[η]{.greek-supplied}]{.greek-added} [[δε]{.greek-supplied}]{.greek-added} [[πενθερα]{.greek-supplied}]{.greek-added} [[σι]{.greek-supplied}μ[ωνος]{.greek-supplied}]{.greek-added} [[κατεκει]{.greek-supplied}]{.greek-added} [τ[εκ]{.unclear}[ε]{.greek-supplied}ιτ[ο]{.unclear}]{.greek-added} [πυ]{.greek-added} [[ρ]{.unclear}εσ[σ]{.unclear}ο[υ]{.unclear}σα]{.greek-added} [[και]{.greek-supplied}]{.greek-added} [η]{.greek-supplied} [δε]{.greek-supplied} [πενθερα]{.greek-supplied} [σι]{.greek-supplied}μ[ωνος]{.greek-supplied} [κα]{.greek-supplied}τ[εκ]{.unclear}[ε]{.greek-supplied}ιτ[ο]{.unclear} πυ[ρ]{.unclear}εσ[σ]{.unclear}ο[υ]{.unclear}σα και ε[υθ]{.unclear}εως λεγου[σ]{.greek-supplied}ιν αυτω πε[ρι]{.greek-supplied} [αυτης]{.greek-supplied}[1:30]{.aside}

[κ]{.unclear}αι π[ρ]{.unclear}οσ[ελθων]{.greek-supplied} ηγ[ε]{.unclear}ι[ρεν]{.greek-supplied} [αυ]{.greek-supplied}την [κρατη]{.greek-supplied}σας [της]{.greek-supplied} [χει]{.greek-supplied}ρος [α]{.unclear}υ[της]{.greek-supplied} [και]{.greek-supplied} αφηκ[εν]{.unclear} α[υτ]{.unclear}ην [ο]{.unclear} [πυ]{.unclear}ρετος ευθεως [κ]{.unclear}αι δι[ηκ]{.unclear}ονε[ι]{.unclear} αυτοι[ς]{.unclear}[1:31]{.aside}

οψιας [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [οτε]{.greek-omitted} [εδυ]{.greek-omitted} [ο]{.greek-omitted} [η]{.greek-supplied}λιος εφερον προς [α]{.unclear}υτον παντ[α]{.unclear}ς τους [κακ]{.unclear}ως εχον[τα]{.unclear}ς και τους δ[α]{.unclear}ιμονι[ζο]{.unclear}μενους[1:32]{.aside}

[κ]{.unclear}α[ι]{.unclear} η πολις [ο]{.unclear}λη επισ[υ]{.unclear}νηγμενη ην προς την [θ]{.unclear}υ[ρ]{.unclear}αν[1:33]{.aside}

και εθεραπευσεν πολλους κακως εχον[τ]{.unclear}ας ποικ[ι]{.unclear}λαις [ν]{.unclear}οσοις και [δαιμονια]{.greek-omitted} [[μ]{.greek-supplied}[ον]{.unclear}ια]{.greek-added} πολλα εξεβαλεν [κ]{.unclear}αι ουκ ηφιεν [λ]{.greek-supplied}[α]{.unclear}λειν τα δαιμονια οτι ηδεισα[ν]{.unclear} αυτον [και]{.greek-added} [εθεραπευσεν]{.greek-added} [πολλους]{.greek-added} [κακως]{.greek-added} [εχον[τ]{.unclear}ας]{.greek-added} [ποικ[ι]{.unclear}λαις]{.greek-added} [[ν]{.unclear}οσοις]{.greek-added} [και]{.greek-added} [[μ]{.greek-supplied}[ον]{.unclear}ια]{.greek-added} [πολλα]{.greek-added} [εξεβαλεν]{.greek-added} [[κ]{.unclear}αι]{.greek-added} [ουκ]{.greek-added} [ηφιεν]{.greek-added} [[λ]{.greek-supplied}[α]{.unclear}λειν]{.greek-added} [τα]{.greek-added} [δαιμονια]{.greek-added} [οτι]{.greek-added} [ηδεισα[ν]{.unclear}]{.greek-added} [αυτον]{.greek-added}[1:34]{.aside}

[κ]{.unclear}αι πρωι εννυχον λια[ν]{.unclear} ανασ[τας]{.greek-supplied} [εξηλθεν]{.greek-omitted} [κ]{.unclear}αι [απηλθεν]{.greek-omitted} [πρωι]{.greek-added} [εννυχον]{.greek-added} [λια[ν]{.unclear}]{.greek-added} [ανασ[τας]{.greek-supplied}]{.greek-added} [εις]{.unclear} [ερημον]{.unclear} τοπον κακ[ε]{.unclear}ι [προσηχετο]{.greek-added} [προσηυχετο]{.corr}[[1:35 *(lacunose)*]{.lacunose}]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιο[ξ]{.unclear}αν]{.greek-added} αυτον ο σιμ[ων]{.unclear} και οι μετ αυτου[1:36]{.aside}

και ευροντες αυ[τ]{.unclear}ο[ν]{.greek-supplied} λεγουσιν α[υ]{.unclear}[τ]{.unclear}ω οτ[ι]{.unclear} πα[ν]{.unclear}[τ]{.unclear}ες σε ζητουσιν[1:37]{.aside}

[κ]{.unclear}αι [λε]{.greek-added} [λεγει]{.greek-omitted} [γ[ε]{.greek-supplied}ι]{.greek-added} αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ ε[ξ]{.unclear}εληλυθα[1:38]{.aside}

και ην [κηρυσσων]{.greek-omitted} [κη[―]{.gap}ρυσων]{.greek-added} [εν]{.greek-omitted} [[κηρυσων]{.corr}]{.greek-added} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [σ[υ]{.unclear}ναγωγ[α]{.unclear}ς]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα [δαιμονια]{.greek-omitted} [εκβαλλων]{.greek-omitted} [[β]{.unclear}αλλω[ν]{.unclear}]{.greek-added}[1:39]{.aside}

[κ]{.unclear}α[ι]{.unclear} ερχεται προς [α]{.unclear}υτον λεπρος παρακαλων [αυτον]{.greek-omitted} [και]{.greek-omitted} [γονυπετων]{.greek-omitted} [αυ]{.unclear}τον και λεγων αυτω οτι εαν θελης δ[υ]{.unclear}νασαι [μ]{.unclear}ε [καθαρισαι]{.greek-omitted} [καθαθαρισαι]{.greek-added}[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχ[ν]{.unclear}ισθεις εκτεινας τη[ν]{.unclear} [χειρα]{.greek-omitted} [ηψατο]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [θελω]{.greek-omitted} [καθαρισθητι]{.greek-omitted}[[1:41 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 13

[παραδωσει]{.greek-omitted} [δε]{.greek-omitted} [αδελφος]{.greek-omitted} [αδελφον]{.greek-omitted} [εις]{.greek-omitted} [θανατον]{.greek-omitted} [και]{.greek-omitted} [πατηρ]{.greek-omitted} [τεκνον]{.greek-omitted} [και]{.greek-omitted} [επαναστη]{.greek-supplied}[σ]{.unclear}ονται τε[κ]{.greek-supplied}ν[α]{.greek-supplied} επι γο[νεις]{.unclear} και [θανατωσου]{.greek-supplied}σιν αυ[τ]{.unclear}[ους]{.greek-supplied} [[σ]{.unclear}ονται]{.greek-added} [τε[κ]{.greek-supplied}ν[α]{.greek-supplied}]{.greek-added} [επι]{.greek-added} [γο[νεις]{.unclear}]{.greek-added} [και]{.greek-added} [[θανατωσου]{.greek-supplied}σιν]{.greek-added} [αυ[τ]{.unclear}[ους]{.greek-supplied}]{.greek-added}[[13:12 *(lacunose)*]{.lacunose}]{.aside}

και εσεσ[θ]{.unclear}[ε]{.greek-supplied} [μι]{.greek-supplied}σουμεν[οι]{.unclear} [υ]{.greek-supplied}πο π[αντων]{.greek-supplied} δια το ονο[μα]{.greek-supplied} μο[υ]{.unclear} ο δε [υ]{.greek-supplied}πομεινας ε[ις]{.unclear} τε[λ]{.unclear}ος ο[υ]{.unclear}τος σωθησεται [και]{.greek-added} [εσεσ[θ]{.unclear}[ε]{.greek-supplied}]{.greek-added} [[μι]{.greek-supplied}σουμεν[οι]{.unclear}]{.greek-added} [[υ]{.greek-supplied}πο]{.greek-added} [π[αντων]{.greek-supplied}]{.greek-added} [δια]{.greek-added} [το]{.greek-added} [ονο[μα]{.greek-supplied}]{.greek-added} [μο[υ]{.unclear}]{.greek-added} [ο]{.greek-added} [δε]{.greek-added} [[υ]{.greek-supplied}πομεινας]{.greek-added} [ε[ις]{.unclear}]{.greek-added} [τε[λ]{.unclear}ος]{.greek-added} [ο[υ]{.unclear}τος]{.greek-added} [σωθησεται]{.greek-added}[13:13]{.aside}

οτα[ν]{.greek-supplied} δε ιδητε το [βδ]{.unclear}ε[λυγμα]{.greek-supplied} [της]{.greek-supplied} [ερη]{.greek-supplied}[μωσεως]{.greek-supplied} [το]{.greek-supplied} ρηθε[ν]{.unclear} [υπ]{.unclear}ο δα[ν]{.unclear}[ιηλ]{.greek-supplied} τ[ο]{.unclear}υ προ[φ]{.unclear}ητ[ου]{.unclear} [εστως]{.greek-omitted} [εστος]{.greek-added} οπου ο[υ]{.unclear} δει [ο]{.greek-supplied} [αναγι]{.greek-supplied}[νωσ]{.unclear}κων νοειτ[ω]{.unclear} το[τ]{.unclear}ε οι εν τ[η]{.unclear} ιου[δα]{.greek-supplied}ια φε[υ]{.greek-supplied}γετ[ωσαν]{.unclear} εις τα ορ[η]{.unclear} [ο]{.greek-added} [[δ]{.unclear}ε]{.greek-added} [ε[π]{.unclear}ι]{.greek-added} [το[υ]{.unclear}]{.greek-added} [[δωμα]{.greek-supplied}]{.greek-added} [[επιστρε]{.greek-supplied}[ψατω]{.greek-supplied}]{.greek-added} [[ει]{.greek-supplied}ς]{.greek-added} [τ[α]{.unclear}]{.greek-added} [οπ[ισω]{.greek-supplied}]{.greek-added} [[αραι]{.greek-supplied}]{.greek-added} [το]{.greek-added} [ι[ματιον]{.greek-supplied}]{.greek-added} [[α]{.unclear}υτ[ου]{.greek-supplied}]{.greek-added} [οτα[ν]{.greek-supplied}]{.greek-added} [δε]{.greek-added} [ιδητε]{.greek-added} [το]{.greek-added} [[βδ]{.unclear}ε[λυγμα]{.greek-supplied}]{.greek-added} [ρηθε[ν]{.unclear}]{.greek-added} [[υπ]{.unclear}ο]{.greek-added} [δα[ν]{.unclear}[ιηλ]{.greek-supplied}]{.greek-added} [τ[ο]{.unclear}υ]{.greek-added} [προ[φ]{.unclear}ητ[ου]{.unclear}]{.greek-added} [εστος]{.greek-added} [οπου]{.greek-added} [ο[υ]{.unclear}]{.greek-added} [δει]{.greek-added} [[ο]{.greek-supplied}]{.greek-added} [[αναγι]{.greek-supplied}[νωσ]{.unclear}κων]{.greek-added} [νοειτ[ω]{.unclear}]{.greek-added} [το[τ]{.unclear}ε]{.greek-added} [οι]{.greek-added} [εν]{.greek-added} [τ[η]{.unclear}]{.greek-added} [ιου[δα]{.greek-supplied}ια]{.greek-added} [φε[υ]{.greek-supplied}γετ[ωσαν]{.unclear}]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ορ[η]{.unclear}]{.greek-added}[[13:14 *(lacunose)*]{.lacunose}]{.aside}

ο [δ]{.unclear}ε ε[π]{.unclear}ι το[υ]{.unclear} [δωματος]{.greek-supplied} [μη]{.greek-omitted} [καταβατω]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [μηδε]{.greek-omitted} [εισελθετω]{.greek-omitted} [αραι]{.greek-omitted} [τι]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [οικιας]{.greek-omitted} [αυτου]{.greek-omitted}[[13:15 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [αγρον]{.greek-omitted} [ων]{.greek-omitted} [μη]{.greek-omitted} [επιστρε]{.greek-supplied}[ψατω]{.greek-supplied} [ει]{.greek-supplied}ς τ[α]{.unclear} οπ[ισω]{.greek-supplied} [αραι]{.greek-supplied} το ι[ματιον]{.greek-supplied} [α]{.unclear}υτ[ου]{.greek-supplied}[[13:16 *(lacunose)*]{.lacunose}]{.aside}

ου[αι]{.unclear} [δ]{.unclear}ε ταις [ου[αι]{.unclear}]{.greek-added} [[δ]{.unclear}ε]{.greek-added} [ταις]{.greek-added} [εν]{.greek-omitted} [γαστρι]{.greek-omitted} [εχουσαις]{.greek-omitted} [και]{.greek-omitted} ταις θηλαζο[υ]{.greek-supplied}σαις ε[ν]{.unclear} εκε[ιναις]{.greek-supplied} τ[α]{.unclear}ις η[μ]{.unclear}εραις[[13:17 *(lacunose)*]{.lacunose}]{.aside}

πρ[οσ]{.greek-supplied}[ε]{.unclear}υχεσθε [δ]{.unclear}ε ινα μη γενηται η φ[υγ]{.greek-supplied}η υμων [χει]{.greek-supplied}μωνος[13:18]{.aside}

[ε]{.greek-supplied}[σ]{.unclear}οντ[αι]{.greek-supplied} [γ]{.greek-supplied}αρ αι ημε[ρ]{.unclear}αι εκ[ειναι]{.greek-supplied} [θλι]{.greek-supplied}ψις [οια]{.greek-supplied} [ου]{.greek-supplied} [γε]{.greek-supplied}[γονεν]{.greek-supplied} [τοιαυ]{.greek-supplied}[τη]{.greek-supplied} α[π]{.greek-supplied} [αρχ]{.unclear}ης [κ]{.greek-supplied}τισ[ε]{.unclear}ω[ς]{.unclear} η[ς]{.unclear} [εκ]{.greek-supplied}τ[ισ]{.greek-supplied}ε[ν]{.unclear} ο [θεος]{.greek-abbr} [εως]{.greek-supplied} [τ]{.greek-supplied}ου [νυ]{.unclear}ν [και]{.greek-supplied} ο[υ]{.unclear} [μη]{.unclear} γενη[ται]{.greek-supplied}[13:19]{.aside}

[κ]{.unclear}αι ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [ε[κ]{.greek-supplied}ολο[β]{.unclear}ωσε]{.greek-added} τ[α]{.greek-supplied}ς ημε[ρ]{.greek-supplied}[α]{.unclear}ς [ουκ]{.greek-supplied} [αν]{.greek-supplied} [ε]{.greek-supplied}σωθη πα[σα]{.unclear} [σαρξ]{.greek-omitted} [αλλα]{.greek-omitted} [δια]{.greek-omitted} [τους]{.greek-omitted} [εκλεκ]{.greek-supplied}τους ους [εξ]{.greek-supplied}ελεξατο [εκολοβωσεν]{.greek-omitted} [[εκ]{.greek-supplied}ολοβωσε]{.greek-added} [τα]{.greek-supplied}ς ημερ[α]{.unclear}ς[13:20]{.aside}

[[και]{.greek-supplied}]{.greek-added} τοτ[ε]{.unclear} [εα]{.unclear}ν [τις]{.greek-supplied} [υμι]{.greek-supplied}ν ειπη [ιδου]{.greek-omitted} [[ιδ]{.greek-supplied}[ε]{.greek-supplied}]{.greek-added} [ωδ]{.greek-supplied}ε ο [[χριστος]{.greek-abbr}]{.unclear} [η]{.greek-omitted} [ιδου]{.greek-omitted} [―]{.gap} εκει [μη]{.greek-supplied}[[13:21 *(lacunose)*]{.lacunose}]{.aside}

[ε]{.unclear}γερθη[σο]{.greek-supplied}[νται]{.greek-supplied} [γ]{.unclear}αρ [[ψ]{.unclear}ευ[δο]{.greek-supplied}]{.greek-added} [ψευδοχριστοι]{.greek-omitted} [και]{.greek-omitted} [ψ]{.unclear}ευ[δοπροφη]{.greek-supplied}ται [και]{.greek-supplied} [δωσου]{.greek-supplied}σ[ιν]{.unclear} σ[ημ]{.unclear}εια κα[ι]{.unclear} τερα[τα]{.unclear} [π]{.unclear}ρος [το]{.greek-supplied} αποπ[λ]{.unclear}α[να]{.unclear}ν ε[ι]{.unclear} δυ[νατον]{.greek-supplied} [κ]{.unclear}αι τους ε[κλ]{.unclear}ε[κτ]{.unclear}ο[υ]{.unclear}ς[13:22]{.aside}

[υμ]{.greek-supplied}ει[ς]{.unclear} [δε]{.greek-supplied} [βλε]{.greek-supplied}πε[τε]{.greek-supplied} [ιδου]{.greek-omitted} [προειρηκα]{.greek-supplied} [υμιν]{.greek-omitted} [παντα]{.greek-omitted}[[13:23 *(lacunose)*]{.lacunose}]{.aside}

α[λ]{.unclear}[λ]{.greek-supplied} [εν]{.greek-supplied} ε[κ]{.unclear}ε[ιναι]{.unclear}ς ταις [ημε]{.unclear}ραις [μετα]{.greek-supplied} [την]{.greek-supplied} [θλι]{.greek-supplied}[ψι]{.unclear}[ν]{.greek-supplied} [εκεινην]{.unclear} ο ηλιος σκοτισ[θ]{.greek-supplied}[η]{.unclear}σεται και η σελ[η]{.unclear}νη ο[υ]{.unclear} δωσ[ε]{.unclear}ι [τ]{.unclear}ο [φ]{.unclear}εγγος αυτης[13:24]{.aside}

και οι [α]{.greek-supplied}στ[ε]{.unclear}ρ[ες]{.unclear} [του]{.unclear} [ουρανου]{.greek-omitted} [ουνου]{.greek-added} [εσονται]{.greek-supplied} εκπι[πτ]{.unclear}ον[τ]{.unclear}ες και [α]{.unclear}[ι]{.greek-supplied} [δυναμ]{.greek-supplied}εις αι [ε]{.unclear}[ν]{.greek-supplied} [τοις]{.greek-supplied} [ουρανοις]{.greek-abbr} σαλ[ε]{.unclear}[υθησονται]{.greek-supplied}[13:25]{.aside}

και τοτε οψον[τ]{.unclear}αι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [ερ]{.unclear}χομενον εν νεφελαις μετα δυ[ν]{.unclear}α[μ]{.unclear}εως [και]{.greek-added} [δοξης]{.greek-added} πολλης και [τοτε]{.greek-added} [οψον[τ]{.unclear}αι]{.greek-added} [τον]{.greek-added} [[υιον]{.greek-abbr}]{.greek-added} [του]{.greek-added} [[ανθρωπου]{.greek-abbr}]{.greek-added} [[ερ]{.unclear}χομενον]{.greek-added} [εν]{.greek-added} [νεφελαις]{.greek-added} [μετα]{.greek-added} [δυ[ν]{.unclear}α[μ]{.unclear}εως]{.greek-added} [και]{.greek-added} δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυν[α]{.unclear}[ξει]{.greek-supplied} τους εκλεκτ[ο]{.unclear}[υς]{.greek-supplied} αυτου εκ τω[ν]{.unclear} [τεσσαρων]{.greek-omitted} [ανεμων]{.greek-omitted} [απ]{.greek-omitted} [και]{.greek-added} [τοτε]{.greek-added} [αποστελει]{.greek-added} [τους]{.greek-added} [αγγελους]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [επισυν[α]{.unclear}[ξει]{.greek-supplied}]{.greek-added} [τους]{.greek-added} [εκλεκτ[ο]{.unclear}[υς]{.greek-supplied}]{.greek-added} [αυτου]{.greek-added} [εκ]{.greek-added} [τω[ν]{.unclear}]{.greek-added} [α]{.greek-supplied}κρου γης εως ακρου [ουρανου]{.greek-abbr}[[13:27 *(lacunose)*]{.lacunose}]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυ[τ]{.unclear}ης ηδη ο [κ]{.unclear}λα[δ]{.greek-supplied}ος απαλος [γ]{.unclear}ενηται και εκφυη τα φυλ[λ]{.greek-supplied}α [γινωσκετε]{.greek-omitted} [[γ]{.unclear}ινωσκ[ε]{.unclear}]{.greek-added} [[τ]{.unclear}ε]{.greek-added} οτι εγγ[υς]{.greek-supplied} [τ]{.greek-supplied}ο [θ]{.greek-supplied}ερος εσ[τιν]{.unclear}[13:28]{.aside}

ο[υ]{.unclear}[τως]{.greek-supplied} [κ]{.unclear}αι [υ]{.unclear}μει[ς]{.unclear} [ο]{.greek-supplied}[τ]{.unclear}αν τ[αυτα]{.unclear} [ιδη]{.greek-supplied}τε [γινομενα]{.greek-omitted} [γενομ[ε]{.unclear}να]{.greek-added} γινωσκ[ε]{.greek-supplied}τ[ε]{.unclear} οτι εγγ[υ]{.unclear}[ς]{.greek-supplied} εσ[τ]{.unclear}ι[ν]{.unclear} επι θυραι[ς]{.unclear}[13:29]{.aside}

[α]{.unclear}μην λεγω υ[μ]{.unclear}ιν οτι ου μη παρελθη [η]{.greek-omitted} [γενεα]{.greek-omitted} [αυτη]{.greek-omitted} [μεχρι]{.greek-omitted} [[με]{.unclear}χρις]{.greek-added} ο[υ]{.unclear} [πα]{.unclear}[ν]{.greek-supplied}τα ταυτα γενηται[[13:30 *(lacunose)*]{.lacunose}]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρ[α]{.unclear}λευσεται]{.greek-added} οι δε λ[ο]{.unclear}γοι μου ου μ[η]{.unclear} παρελθωσιν[13:31]{.aside}

[[ου]{.greek-supplied}δε]{.greek-added} [[οι]{.unclear}]{.greek-added} [[αγγ]{.unclear}ε[λ]{.unclear}οι]{.greek-added} [ο[ι]{.unclear}]{.greek-added} [[εν]{.unclear}]{.greek-added} [[ουρανω]{.greek-abbr}]{.greek-added} [[ου]{.greek-supplied}[δ]{.unclear}ε]{.greek-added} [ο]{.greek-added} [[υιος]{.greek-abbr}]{.greek-added} [[ει]{.greek-supplied}]{.greek-added} [[μη]{.greek-supplied}]{.greek-added} [ο]{.greek-added} [[πατηρ]{.greek-abbr}]{.greek-added} περι δε της ημερας εκεινη[ς]{.unclear} η ωρας [ε[κ]{.unclear}εινη[ς]{.unclear}]{.greek-added} ουδει[ς]{.greek-supplied} οιδε[ν]{.greek-supplied} [ου]{.greek-supplied}δε [οι]{.unclear} [αγγ]{.unclear}ε[λ]{.unclear}οι ο[ι]{.unclear} [εν]{.unclear} [ουρανω]{.greek-abbr} [ου]{.greek-supplied}[δ]{.unclear}ε ο [υιος]{.greek-abbr} [ει]{.greek-supplied} [μη]{.greek-supplied} ο [πατηρ]{.greek-abbr}[13:32]{.aside}

[βλε]{.greek-supplied}[π]{.unclear}ετε [αγρ]{.greek-supplied}υ[π]{.unclear}[νειτε]{.greek-supplied} [και]{.greek-supplied} [προσ]{.greek-supplied}ε[υχεσθ]{.unclear}ε ο[υ]{.greek-supplied}[κ]{.unclear} οιδ[ατε]{.greek-supplied} [γαρ]{.greek-supplied} ποτε [ο]{.unclear} [κα]{.unclear}ι[ρος]{.unclear} εστι[ν]{.unclear} [[βλε]{.greek-supplied}[π]{.unclear}ετε]{.greek-added} [[αγρ]{.greek-supplied}υ[π]{.unclear}[νειτε]{.greek-supplied}]{.greek-added} [[και]{.greek-supplied}]{.greek-added} [[προσ]{.greek-supplied}ε[υχεσθ]{.unclear}ε]{.greek-added} [ο[υ]{.greek-supplied}[κ]{.unclear}]{.greek-added} [οιδ[ατε]{.greek-supplied}]{.greek-added} [[γαρ]{.greek-supplied}]{.greek-added} [ποτε]{.greek-added} [[ο]{.unclear}]{.greek-added} [[κα]{.unclear}ι[ρος]{.unclear}]{.greek-added} [εστι[ν]{.unclear}]{.greek-added}[13:33]{.aside}

[ως]{.greek-supplied} [ανθρωπος]{.greek-omitted} [[[α]{.greek-supplied}]{.greek-abbr}]{.greek-added} α[ποδη]{.unclear}[μος]{.greek-supplied} [α]{.unclear}φεις τη[ν]{.unclear} [οι]{.greek-supplied}κιαν αυτου και [δους]{.greek-omitted} [τοις]{.greek-omitted} [δουλοις]{.greek-omitted} [[ως]{.greek-supplied}]{.greek-added} [[[α]{.greek-supplied}]{.greek-abbr}]{.greek-added} [α[ποδη]{.unclear}[μος]{.greek-supplied}]{.greek-added} [[α]{.unclear}φεις]{.greek-added} [τη[ν]{.unclear}]{.greek-added} [[οι]{.greek-supplied}κιαν]{.greek-added} αυτου [την]{.greek-omitted} [και]{.greek-added} εξουσι[α]{.unclear}ν [κ]{.unclear}αι εκα[στ]{.unclear}ω τ[ο]{.unclear} εργον [αυ]{.unclear}τ[ου]{.unclear} [και]{.unclear} τω θυ[ρ]{.unclear}ω[ρω]{.unclear} ενετειλ[ατο]{.unclear} ιν[α]{.unclear} [γ]{.unclear}[ρ]{.greek-supplied}η[γ]{.unclear}[ορη]{.greek-supplied}[[13:34 *(lacunose)*]{.lacunose}]{.aside}

[γ]{.greek-supplied}[ρ]{.unclear}η[γο]{.greek-supplied}[ρ]{.unclear}ειτ[ε]{.unclear} [ουν]{.greek-supplied} [ουκ]{.greek-supplied} [οιδατε]{.greek-supplied} [γαρ]{.greek-supplied} ποτε [ο]{.greek-supplied} [κυριος]{.greek-abbr} [τ]{.unclear}[ης]{.greek-supplied} οικι[ας]{.unclear} ε[ρχε]{.greek-supplied}ται [οψε]{.greek-omitted} [η]{.greek-omitted} [μεσονυκτιου]{.greek-omitted} [η]{.greek-omitted} [αλεκτοροφωνιας]{.greek-omitted} [η]{.greek-omitted} [πρωι]{.greek-omitted}[[13:35 *(lacunose)*]{.lacunose}]{.aside}

### Chapter 14

[[ην]{.greek-supplied}]{.greek-added} [[δε]{.greek-supplied}]{.greek-added} [[το]{.greek-supplied}]{.greek-added} [[πασ]{.greek-supplied}χα]{.greek-added} [[και]{.greek-supplied}]{.greek-added} [[τα]{.greek-supplied}]{.greek-added} [[αζυ]{.greek-supplied}]{.greek-added} [[μ]{.unclear}[α]{.greek-supplied}]{.greek-added} [[μετα]{.greek-supplied}]{.greek-added} [[δυο]{.greek-supplied}]{.greek-added} [ημερα[ς]{.unclear}]{.greek-added} [κ[α]{.unclear}ι]{.greek-added} [ην]{.greek-supplied} [δε]{.greek-supplied} [το]{.greek-supplied} [πασ]{.greek-supplied}χα [και]{.greek-supplied} [τα]{.greek-supplied} [αζυ]{.greek-supplied}[μ]{.unclear}[α]{.greek-supplied} [μετα]{.greek-supplied} [δυο]{.greek-supplied} ημερα[ς]{.unclear} κ[α]{.unclear}ι [εζητουν]{.greek-supplied} [ο]{.unclear}ι [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} γ[ρ]{.unclear}αμματεις [πως]{.unclear} α[υτ]{.unclear}ον εν [δολω]{.unclear} [κρ]{.unclear}α[τ]{.unclear}η[σα]{.unclear}[ντες]{.greek-supplied} [[και]{.greek-supplied}]{.greek-added} [απ]{.unclear}ο[κ]{.unclear}[τεινωσιν]{.greek-supplied}[[14:1 *(lacunose)*]{.lacunose}]{.aside}

ελε[γ]{.unclear}[ον]{.greek-supplied} [δε]{.greek-omitted} [[γαρ]{.greek-supplied}]{.greek-added} [μη]{.greek-supplied} εν τη εορ[τη]{.greek-supplied} μ[ηποτε]{.greek-supplied} [θορυβος]{.greek-omitted} [εσται]{.greek-supplied} [του]{.greek-omitted} [λαου]{.greek-omitted}[[14:2 *(lacunose)*]{.lacunose}]{.aside}

και οντ[ος]{.greek-supplied} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

