---
title: "Collation of Byz^RP^ vs 20120 (120)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 120 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20120).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 120                                   	| λογος                              	|
| 120 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 120 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 120               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 120                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 120 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 120                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 16

[και]{.greek-omitted} [προαγαγων]{.greek-omitted} [αυτους]{.greek-omitted} [εξω]{.greek-omitted} [εφη]{.greek-omitted} [κυριοι]{.greek-omitted} [τι]{.greek-omitted} [με]{.greek-omitted} δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και ο οικος σου[16:31]{.aside}

και ελαλησαν [αυ]{.unclear}τω τον λογον του [κυριου]{.greek-abbr} [κ]{.unclear}αι πασιν τοι[ς]{.unclear} εν τη οικια [αυ]{.unclear}του[16:32]{.aside}

και παραλαβων αυ[τ]{.greek-supplied}[ο]{.unclear}υς εν εκεινη τη ωρα [τ]{.unclear}η[ς]{.unclear} νυκτος ελουσεν απο [τ]{.unclear}ων πληγων και εβαπ[τισθη]{.greek-supplied} [αυτος]{.greek-supplied} [και]{.unclear} [οι]{.unclear} [αυτου]{.unclear} [παντες]{.greek-omitted} [παραχρημα]{.greek-omitted}[16:33]{.aside}

[και]{.greek-omitted} [παραλαβων]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [της]{.greek-omitted} [νυκτος]{.greek-omitted} [ελουσεν]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [πληγων]{.greek-omitted} [και]{.greek-omitted} [εβαπτισθη]{.greek-omitted} [αυτος]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αυτου]{.greek-omitted} [π]{.unclear}αντες παραχρημα[16:33 | instance no. 2]{.aside}

ανα[γ]{.greek-supplied}[αγ]{.unclear}ων τε αυτους εις τον [ο]{.greek-supplied}[ι]{.unclear}κον αυτου παρεθηκεν [τ]{.unclear}ραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασα[τ]{.unclear}ο]{.greek-added} πανοικι πεπιστευκως [τ]{.unclear}ω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γε[ν]{.greek-supplied}ομενης απεστειλαν οι [σ]{.greek-supplied}τρατηγοι τους ρα[β]{.unclear}δου[χ]{.greek-supplied}ους λεγοντες απολυσον [τ]{.unclear}ους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

απηγ[γ]{.greek-supplied}ειλεν δε ο δεσμοφυλαξ [τους]{.greek-omitted} [λογους]{.greek-omitted} [τουτους]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [οτι]{.greek-omitted} [απεσταλκασιν]{.greek-omitted} [οι]{.greek-omitted} [στρατηγοι]{.greek-omitted} [ινα]{.greek-omitted} [απολυθητε]{.greek-omitted} [νυν]{.greek-omitted} [ουν]{.greek-omitted} [εξελθοντες]{.greek-omitted} [πορευεσθε]{.greek-omitted} [εν]{.greek-omitted} [ειρηνη]{.greek-omitted}[16:36]{.aside}

[απηγγειλεν]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [δεσμοφυλαξ]{.greek-omitted} τους λογους τουτους προς τον παυλ[ο]{.unclear}ν οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες [πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} εν ειρ[η]{.unclear}νη[16:36 | instance no. 2]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας ε[βα]{.greek-supplied}λον εις φυλακην και νυ[ν]{.greek-supplied} λαθρα ημας εκβαλλουσι[ν]{.unclear} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [αλλα]{.greek-omitted} [ελθοντες]{.greek-omitted} [αυτοι]{.greek-omitted} [εξαγαγετωσαν]{.greek-omitted}[16:37]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [παυλος]{.greek-omitted} [εφη]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [δειραντες]{.greek-omitted} [ημας]{.greek-omitted} [δημοσια]{.greek-omitted} [ακατακριτους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [ρωμαιους]{.greek-omitted} [υπαρχοντας]{.greek-omitted} [εβαλον]{.greek-omitted} [εις]{.greek-omitted} [φυλακην]{.greek-omitted} [και]{.greek-omitted} [νυν]{.greek-omitted} [λαθρα]{.greek-omitted} [ημας]{.greek-omitted} [εκβαλλουσιν]{.greek-omitted} ου γαρ αλλα ελθοντες αυ[τ]{.unclear}[οι]{.greek-supplied} [ημας]{.greek-added} εξαγαγετωσαν[16:37 | instance no. 2]{.aside}

[ανηγγειλαν]{.greek-omitted} [αν[ηγ]{.greek-supplied}γιλαν]{.greek-added} δε τοις [σ]{.unclear}τρατηγο[ις]{.greek-supplied} οι ραβδ[ο]{.unclear}υχοι τα ρηματα τ[αυ]{.greek-supplied}τα κα[ι]{.unclear} εφοβηθησαν ακο[υ]{.greek-supplied}[σ]{.unclear}αντες οτι ρωμαιοι εισι[ν]{.unclear}[16:38]{.aside}

και ελθοντε[ς]{.unclear} παρεκαλεσα[ν]{.greek-supplied} αυτους και ε[ξ]{.unclear}αγαγοντες [η]{.greek-supplied}ρωτων εξελθειν της π[ο]{.greek-supplied}λεως[16:39]{.aside}

εξελθοντες δε εκ τ[ης]{.greek-supplied} φυλακης [εισηλθον]{.greek-omitted} [εισηλθεν]{.greek-added} προς τ[ην]{.greek-supplied} [λυδιαν]{.greek-omitted} [και]{.greek-omitted} [ιδοντες]{.greek-omitted} [τους]{.greek-omitted} [αδελφους]{.greek-omitted} [παρεκαλεσαν]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [εξηλθον]{.greek-omitted}[16:40]{.aside}

[εξελθοντες]{.greek-omitted} [δε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [φυλακης]{.greek-omitted} [εισηλθον]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [λυδιαν]{.greek-supplied} [και]{.greek-supplied} [ιδο]{.greek-supplied}[ν]{.unclear}[τες]{.greek-supplied} [το]{.greek-supplied}[υ]{.unclear}[ς]{.greek-supplied} [α]{.greek-supplied}[δε]{.greek-supplied}λφους παρεκαλεσαν αυτους [κ]{.greek-supplied}αι εξηλθον[16:40 | instance no. 2]{.aside}

### Chapter 17

διοδευσαν[τ]{.greek-supplied}[ε]{.unclear}ς δε την αμφ[ι]{.unclear}πολιν και [α]{.greek-supplied}πολλων[ι]{.unclear}αν ηλθον ε[ι]{.unclear}ς [θεσσαλονικην]{.greek-omitted} [θε[σ]{.greek-supplied}[α]{.unclear}λονικην]{.greek-added} οπου ην [η]{.greek-omitted} συνα[γ]{.greek-supplied}ωγη των ιουδαιων[17:1]{.aside}

κα[τα]{.greek-supplied} δε [το]{.unclear} ειωθος τω παυλω [ει]{.greek-supplied}[σ]{.unclear}ηλθεν πρ[ο]{.unclear}ς αυτους και ε[πι]{.greek-supplied} σαββατα τρια [διελεξατο]{.greek-omitted} [διελεχθη]{.greek-added} [αυ]{.greek-supplied}τοις απο των γραφων[17:2]{.aside}

[δ]{.greek-supplied}ιανοιγων και παρατιθε[μ]{.greek-supplied}[ε]{.unclear}νος οτι τον [χριστον]{.greek-abbr} εδει [πα]{.greek-added} [παθειν]{.greek-omitted} [και]{.greek-omitted} [αναστηναι]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} [και]{.greek-omitted} [οτι]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [ιησους]{.greek-omitted} [ον]{.greek-omitted} [εγω]{.greek-omitted} [καταγγελλω]{.greek-omitted} [υμιν]{.greek-omitted}[17:3]{.aside}

[διανοιγων]{.greek-omitted} [και]{.greek-omitted} [παρατιθεμενος]{.greek-omitted} [οτι]{.greek-omitted} [τον]{.greek-omitted} [χριστον]{.greek-omitted} [εδει]{.greek-omitted} [παθειν]{.greek-omitted} [[θειν]{.greek-supplied}]{.greek-added} [και]{.greek-supplied} [ανασ]{.greek-supplied}[την]{.unclear}αι εκ νε[κ]{.greek-supplied}[ρ]{.unclear}ων και οτι ουτος εστιν [ο]{.greek-supplied} [[χριστος]{.greek-abbr}]{.greek-supplied} [ιησους]{.greek-abbr} ον εγω καταγγελλω [υ]{.greek-supplied}μιν[17:3 | instance no. 2]{.aside}

και τινες εξ αυτων [επεισθησαν]{.greek-omitted} [[ε]{.greek-supplied}πιστευσαν]{.greek-added} και προσεκλη[ρ]{.greek-supplied}ωθησαν τω παυλω και [τ]{.greek-supplied}ω [σ]{.unclear}ιλα των τε σεβομε[ν]{.greek-supplied}ων ελληνων [πληθος]{.greek-added} πο[λ]{.greek-supplied}[υ]{.unclear} [πληθος]{.greek-omitted} γυναικων τε των πρωτων [ουκ]{.greek-omitted} [ολιγαι]{.greek-omitted}[17:4]{.aside}

[και]{.greek-omitted} [τινες]{.greek-omitted} [εξ]{.greek-omitted} [αυτων]{.greek-omitted} [επεισθησαν]{.greek-omitted} [και]{.greek-omitted} [προσεκληρωθησαν]{.greek-omitted} [τω]{.greek-omitted} [παυλω]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [σιλα]{.greek-omitted} [των]{.greek-omitted} [τε]{.greek-omitted} [σεβομενων]{.greek-omitted} [ελληνων]{.greek-omitted} [πολυ]{.greek-omitted} [πληθος]{.greek-omitted} [γυναικων]{.greek-omitted} [τε]{.greek-omitted} [των]{.greek-omitted} [πρωτων]{.greek-omitted} [ο]{.unclear}υ[κ]{.unclear} [ολιγαι]{.greek-supplied}[17:4 | instance no. 2]{.aside}

[προσλαβομενοι]{.greek-omitted} [[ζηλωσαντες]{.greek-supplied}]{.greek-added} [δε]{.greek-supplied} οι ιουδαιοι οι απειθουν[τ]{.unclear}[ες]{.greek-supplied} [και]{.greek-added} [προσλαβομενοι]{.greek-added} των [αγοραιων]{.greek-omitted} [[α]{.greek-supplied}γωραιων]{.greek-added} [ανδρα[ς]{.unclear}]{.greek-added} τινα[ς]{.unclear} [ανδρας]{.greek-omitted} [πο]{.greek-supplied}νηρους και οχλοποιη[σ]{.unclear}αν[τες]{.greek-supplied} εθορυβουν την πολιν [[και]{.greek-supplied}]{.greek-added} επισταντες [τε]{.greek-omitted} τη οικια [ια]{.unclear}[σονος]{.greek-supplied} εζητουν αυτους [αγαγειν]{.greek-omitted} [πρ[ο]{.unclear}α[γ]{.greek-supplied}αγειν]{.greek-added} εις τον [δ]{.unclear}ημον[17:5]{.aside}

[μ]{.unclear}[η]{.greek-supplied} [ευ]{.greek-supplied}ροντες δε αυτους εσυ[ρον]{.greek-supplied} [τ]{.unclear}ον ιασονα και τινας [αδελ]{.greek-supplied}φους επι τους πολιταρ[χας]{.greek-supplied} [βοων]{.greek-supplied}[τες]{.unclear} [οτι]{.unclear} [οι]{.unclear} [τ]{.unclear}[ην]{.greek-supplied} [[οικου]{.greek-supplied}]{.greek-added} [οικουμενην]{.greek-omitted} [αναστατωσαντες]{.greek-omitted} [ουτοι]{.greek-omitted} [και]{.greek-omitted} [ενθαδε]{.greek-omitted} [παρεισιν]{.greek-omitted}[17:6]{.aside}

[μενην]{.greek-added} [μη]{.greek-omitted} [ευροντες]{.greek-omitted} [δε]{.greek-omitted} [αυτους]{.greek-omitted} [εσυρον]{.greek-omitted} [τον]{.greek-omitted} [ιασονα]{.greek-omitted} [και]{.greek-omitted} [τινας]{.greek-omitted} [αδελφους]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [πολιταρχας]{.greek-omitted} [βοωντες]{.greek-omitted} [οτι]{.greek-omitted} [οι]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} α[ν]{.unclear}α[στα]{.unclear}[τωσαν]{.greek-supplied}τες ουτοι και ενθαδε π[αρ]{.greek-supplied}εισιν[17:6 | instance no. 2]{.aside}

ους υποδεδεκτα[ι]{.unclear} [ια]{.greek-supplied}σων και ουτοι παντε[ς]{.unclear} [α]{.greek-supplied}πεναντι των δογ[μ]{.unclear}[ατων]{.greek-supplied} καισαρος πρασσουσιν [βα]{.unclear}[σι]{.greek-supplied}λεα λεγοντες ετερον [ει]{.unclear}[ναι]{.greek-supplied} [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον ο[χ]{.unclear}[λον]{.greek-supplied} κ[αι]{.unclear} τους πολιταρχας [[ακ]{.unclear}ο[υ]{.greek-supplied}]{.greek-added} [ακουοντας]{.greek-omitted} [ταυτα]{.greek-omitted}[17:8]{.aside}

[οντ[α]{.unclear}ς]{.greek-added} [εταραξαν]{.greek-omitted} [δε]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πολιταρχας]{.greek-omitted} [ακουοντας]{.greek-omitted} ταυτα[17:8 | instance no. 2]{.aside}

κα[ι]{.unclear} [λ]{.unclear}αβοντες το ικανον παρα του ιασονος και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε α[δε]{.greek-supplied}[λ]{.unclear}φο[ι]{.unclear} ευθεως δια [της]{.greek-omitted} νυκτος [ε]{.greek-supplied}ξεπεμψαν τον τε παυλον κα[ι]{.unclear} τον σιλαν εις βεροιαν οι[τ]{.unclear}ινες παραγεν[ο]{.unclear}μενοι εις την συναγωγην [απηεσαν]{.greek-omitted} των ι[ο]{.greek-supplied}[υ]{.unclear}δαιων [απιεσαν]{.greek-added}[17:10]{.aside}

ουτοι [δε]{.greek-supplied} [ησ]{.greek-supplied}[α]{.unclear}[ν]{.greek-supplied} [ευγενεστεροι]{.greek-supplied} [των]{.greek-supplied} [εν]{.greek-omitted} [θεσσαλονικη]{.greek-omitted} [οιτινες]{.greek-omitted} [εδεξαντο]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [μετα]{.greek-omitted} [πασης]{.greek-omitted} [προθυμιας]{.greek-omitted} [το]{.greek-omitted} [καθ]{.greek-omitted} [ημεραν]{.greek-omitted} [ανακρινοντες]{.greek-omitted} [τας]{.greek-omitted} [γραφας]{.greek-omitted} [ει]{.greek-omitted} [εχοι]{.greek-omitted} [ταυτα]{.greek-omitted} [ουτως]{.greek-omitted}[17:11]{.aside}

[ουτοι]{.greek-omitted} [δε]{.greek-omitted} [ησαν]{.greek-omitted} [ευγενεστεροι]{.greek-omitted} [των]{.greek-omitted} εν θεσσαλονικη οιτινες [ε]{.greek-supplied}[δε]{.unclear}ξαντο τ[ο]{.unclear}ν λογον μετα πασης προθυμιας [το]{.greek-omitted} καθ ημεραν ανακ[ρ]{.unclear}ινοντες τας γραφας ει [εχοι]{.greek-omitted} ταυτα ουτως [[ε]{.unclear}χ[ε]{.unclear}ι]{.greek-added}[17:11 | instance no. 2]{.aside}

πολλοι μεν ουν εξ αυτων επι[σ]{.unclear}τευσαν και των [ε]{.greek-supplied}[λ]{.unclear}ληνιδων γυναικων των ευσχημονων κα[ι]{.unclear} ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε [ε]{.unclear}γνωσαν οι απο της [θεσσ[α]{.unclear}]{.greek-added} [θεσσαλονικης]{.greek-omitted} [ιουδαιοι]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [βεροια]{.greek-omitted} [κατηγγελη]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [παυλου]{.greek-omitted} [ο]{.greek-omitted} [λογος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ηλθον]{.greek-omitted} [κακει]{.greek-omitted} [σαλευοντες]{.greek-omitted} [τους]{.greek-omitted} [οχλους]{.greek-omitted}[17:13]{.aside}

[λονικης]{.greek-added} [ως]{.greek-omitted} [δε]{.greek-omitted} [εγνωσαν]{.greek-omitted} [οι]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [θεσσαλονικης]{.greek-omitted} ιουδαιοι οτι και εν τη [β]{.unclear}εροια κατηγγελη υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες το[υ]{.unclear}ς [ο]{.greek-supplied}χλου[ς]{.unclear}[17:13 | instance no. 2]{.aside}

ευθεως [δ]{.unclear}ε τοτε τ[ον]{.unclear} παυλ[ο]{.unclear}ν εξαπεστειλαν οι αδ[ελ]{.greek-supplied}φοι [πορευεσθαι]{.greek-omitted} [πορευεσθε]{.greek-added} ως επι την θ[α]{.greek-supplied}λασσαν [υπεμενον]{.greek-omitted} [υπεμειν[α]{.unclear}ν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} ο τ[ε]{.unclear} [σ]{.unclear}ιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε καθιστωντες τον πα[υ]{.greek-supplied}λον ηγαγον [αυτον]{.greek-omitted} εως [αθη]{.greek-added} [αθηνων]{.greek-omitted} [και]{.greek-omitted} [λαβοντες]{.greek-omitted} [εντολην]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [σιλαν]{.greek-omitted} [και]{.greek-omitted} [τιμοθεον]{.greek-omitted} [ινα]{.greek-omitted} [ως]{.greek-omitted} [ταχιστα]{.greek-omitted} [ελθωσιν]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [εξηεσαν]{.greek-omitted}[17:15]{.aside}

[νων]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [καθιστωντες]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [ηγαγον]{.greek-omitted} [αυτον]{.greek-omitted} [εως]{.greek-omitted} [αθηνων]{.greek-omitted} και λαβοντες εντολη[ν]{.unclear} προς τον σιλαν και τιμοθε[ον]{.greek-supplied} ινα ως ταχιστα [ελθωσιν]{.greek-omitted} [ελθοσιν]{.greek-added} πρ[ος]{.greek-supplied} αυτον εξηεσαν[17:15 | instance no. 2]{.aside}

[ε]{.unclear}ν [δ]{.unclear}ε τα[ις]{.unclear} αθηναις εκδεχομενο[υ]{.unclear} α[υ]{.unclear}τους του παυλο[υ]{.unclear} παρωξυνετο το [πνευμα]{.greek-abbr} αυτου εν [αυτω]{.greek-omitted} [εαυτω]{.greek-added} θεωρουντι κατειδωλον ου[σ]{.unclear}αν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις [σεβ[ο]{.unclear}]{.greek-added} [σεβομενοις]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [αγορα]{.greek-omitted} [κατα]{.greek-omitted} [πασαν]{.greek-omitted} [ημεραν]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [παρατυγχανοντας]{.greek-omitted}[17:17]{.aside}

[τινες]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [επικουρειων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [στοικων]{.greek-omitted} [φιλοσοφων]{.greek-omitted} [συνεβαλλον]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [τινες]{.greek-omitted} [ελεγον]{.greek-omitted} [τι]{.greek-omitted} [αν]{.greek-omitted} [θελοι]{.greek-omitted} [ο]{.greek-omitted} [σπερμολογος]{.greek-omitted} [ουτος]{.greek-omitted} [λεγειν]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [ξενων]{.greek-omitted} [δαιμονιων]{.greek-omitted} [δοκει]{.greek-omitted} [καταγγελευς]{.greek-omitted} [ειναι]{.greek-omitted} [οτι]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-abbr} [και]{.greek-supplied} [την]{.greek-supplied} [αναστασιν]{.greek-supplied} [ευ]{.greek-supplied}ηγ[γελιζετο]{.greek-supplied}[17:18]{.aside}

[επιλαβομε]{.greek-supplied}νοι τ[ε]{.greek-supplied} [αυτου]{.greek-supplied} [επι]{.greek-supplied} [τον]{.greek-supplied} [αρειον]{.greek-supplied} πα[γ]{.unclear}[ον]{.greek-supplied} [ηγαγον]{.greek-supplied} [λεγοντες]{.greek-supplied} δυ[ν]{.unclear}[αμεθα]{.greek-supplied} [γνωναι]{.greek-supplied} [τις]{.greek-supplied} [η]{.greek-supplied} και[νη]{.greek-supplied} [αυτη]{.greek-supplied} [η]{.greek-supplied} [υπο]{.greek-supplied} [σου]{.greek-supplied} [λα]{.greek-supplied}λου[μενη]{.greek-supplied} [διδαχη]{.greek-supplied}[17:19]{.aside}

[ξενιζον]{.greek-supplied}τα γ[αρ]{.greek-supplied} [τινα]{.greek-supplied} [εισφερεις]{.greek-supplied} [εις]{.greek-supplied} [τας]{.greek-supplied} ακ[ο]{.unclear}[ας]{.greek-supplied} [ημων]{.greek-supplied} [βουλομεθα]{.greek-supplied} ουν [γ]{.unclear}[νωναι]{.greek-supplied} [[τινα]{.greek-supplied}]{.greek-added} [τι]{.greek-omitted} [αν]{.greek-omitted} [θελοι]{.greek-omitted} [[θελει]{.greek-supplied}]{.greek-added} [ταυ]{.greek-supplied}τα ε[ι]{.unclear}[ναι]{.greek-supplied}[17:20]{.aside}

[αθηναιοι]{.greek-supplied} [δε]{.greek-supplied} [παν]{.greek-supplied}τες κ[αι]{.greek-supplied} [οι]{.greek-supplied} [επιδημουντες]{.greek-supplied} [ξενοι]{.greek-omitted} [εις]{.greek-omitted} [ουδεν]{.greek-omitted} [ετερον]{.greek-omitted} [ευκαιρουν]{.greek-omitted} [η]{.greek-omitted} [λεγειν]{.greek-omitted} [τι]{.greek-omitted} [και]{.greek-omitted} [ακουειν]{.greek-omitted} [καινοτερον]{.greek-omitted}[17:21]{.aside}

[διερχομενος]{.greek-omitted} [γαρ]{.greek-omitted} [και]{.greek-omitted} [αναθεωρων]{.greek-omitted} [τα]{.greek-omitted} [σεβασματα]{.greek-omitted} [υμων]{.greek-omitted} [ευρον]{.greek-omitted} [και]{.greek-omitted} [βωμον]{.greek-supplied} [εν]{.greek-supplied} [ω]{.greek-supplied} [επεγεγ]{.greek-supplied}ρα[π]{.unclear}[το]{.greek-supplied} [αγνωστω]{.greek-supplied} [[θεω]{.greek-abbr}]{.greek-supplied} [ον]{.greek-omitted} [[ο]{.greek-supplied}]{.greek-added} ουν [αγνοουντες]{.greek-supplied} [ευσεβε]{.greek-supplied}[ιτ]{.unclear}ε [τουτον]{.greek-omitted} [[τουτο]{.greek-supplied}]{.greek-added} [εγω]{.greek-supplied} [καταγγ]{.greek-supplied}[ε]{.unclear}λλω [υμιν]{.greek-supplied}[17:23]{.aside}

[ο]{.greek-supplied} [[θεος]{.greek-abbr}]{.greek-supplied} [ο]{.greek-supplied} [ποιησας]{.greek-supplied} τον [κοσμον]{.greek-supplied} [και]{.greek-supplied} [παντα]{.greek-supplied} [τ]{.unclear}α εν [αυτω]{.greek-supplied} [ουτος]{.greek-supplied} [[ουρανου]{.greek-abbr}]{.greek-supplied} [κ]{.unclear}αι [γης]{.greek-supplied} [[υπαρχων]{.greek-supplied}]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-supplied} [υπαρχων]{.greek-omitted} [ουκ]{.greek-supplied} [ε]{.unclear}ν [χειροποιητοις]{.greek-supplied} [ναοις]{.greek-supplied} κα[τ]{.unclear}[οικει]{.greek-supplied}[17:24]{.aside}

[ουδε]{.greek-supplied} [υπο]{.greek-supplied} [χειρ]{.greek-supplied}[ω]{.unclear}ν [ανθρωπων]{.greek-omitted} [[ανθρωπινων]{.greek-supplied}]{.greek-added} [θεραπευεται]{.greek-omitted} [[θεραπευ]{.greek-supplied}ετε]{.greek-added} [προσδεομενος]{.greek-supplied} [τινος]{.greek-supplied} [αυ]{.greek-supplied}τος [διδους]{.greek-omitted} [πασιν]{.greek-omitted} [ζωην]{.greek-omitted} [και]{.greek-omitted} [πνοην]{.greek-omitted} [κατα]{.greek-omitted} [παντα]{.greek-omitted}[17:25]{.aside}

[ζητειν]{.greek-omitted} [τον]{.greek-omitted} [κυριον]{.greek-omitted} [ει]{.greek-omitted} [αρα]{.greek-omitted} [γε]{.greek-omitted} [ψηλαφ]{.greek-supplied}[ησειαν]{.greek-supplied} [αυτον]{.greek-supplied} [και]{.greek-supplied} [ε]{.unclear}υροιεν [και]{.unclear} [γε]{.unclear} [ο]{.unclear}υ [μα]{.greek-supplied}[κρ]{.unclear}αν [α]{.unclear}πο ενο[ς]{.unclear} εκαστ[ο]{.unclear}υ [η]{.greek-supplied}[μω]{.unclear}ν [υπαρχοντα]{.greek-omitted} [υπαρχοντο[ς]{.unclear}]{.greek-added}[17:27]{.aside}

εν αυτω [γ]{.unclear}αρ ζωμεν και κινουμ[ε]{.greek-supplied}θα και εσμεν ως και τιν[ες]{.greek-supplied} των καθ υμας ποιητ[ων]{.unclear} ειρηκασιν του γαρ κα[ι]{.greek-supplied} γενος εσμεν[17:28]{.aside}

γεν[ο]{.unclear}ς ου[ν]{.unclear} υπαρχοντες του [θεου]{.greek-abbr} ουκ ο[φ]{.greek-supplied}ειλομεν νομιζειν χρυσω η [α]{.greek-supplied}ργυρω η λιθω χαραγματ[ι]{.greek-supplied} τεχνης και ενθυμησε[ω]{.unclear}ς [ανθρωπου]{.greek-abbr} το θειον [ειναι]{.greek-omitted} [ομοιον]{.greek-omitted}[17:29]{.aside}

[διοτι]{.greek-omitted} [εστησεν]{.greek-omitted} [ημεραν]{.greek-omitted} [εν]{.greek-omitted} [η]{.greek-omitted} [μελλει]{.greek-omitted} [κρινειν]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} [εν]{.greek-omitted} [δικαιοσυνη]{.greek-omitted} [εν]{.greek-omitted} [ανδρι]{.greek-omitted} [ω]{.greek-omitted} [ωρισεν]{.greek-omitted} πιστιν παρασ[χ]{.unclear}[ων]{.greek-supplied} [πασιν]{.greek-supplied} αν[ασ]{.unclear}τη[σας]{.unclear} [α]{.unclear}[υτ]{.greek-supplied}ον εκ νεκρων[17:31]{.aside}

[α]{.unclear}[κουσα]{.greek-supplied}ντες δε ανα[σ]{.unclear}τα[σ]{.unclear}ιν [ν]{.unclear}εκ[ρ]{.unclear}ων ο[ι]{.unclear} μεν εχλ[ε]{.unclear}υαζον οι [δ]{.unclear}[ε]{.greek-supplied} ειπον ακουσομεθα σ[ο]{.unclear}υ [π]{.greek-supplied}αλιν περ[ι]{.unclear} τουτου[17:32]{.aside}

και [ο]{.greek-supplied}[υ]{.unclear}τως ο παυλος εξηλθεν εκ [μ]{.greek-supplied}εσου αυτων[17:33]{.aside}

τινες δ[ε]{.unclear} [α]{.greek-supplied}νδρες [κολληθεντες]{.greek-omitted} [κολλιθεντες]{.greek-added} α[υ]{.unclear}τω επιστευσαν εν οις κ[α]{.greek-supplied}ι διονυσιος ο αρεοπαγιτ[η]{.unclear}ς και γυνη ονοματι [δ]{.unclear}[α]{.greek-supplied}μαρις και [ετεροι]{.greek-omitted} [συν]{.greek-omitted} [αυτοις]{.greek-omitted}[17:34]{.aside}

### Chapter 18

[κρισπος]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [αρχισυναγωγος]{.greek-omitted} [επιστευσεν]{.greek-omitted} [τω]{.greek-omitted} [κυριω]{.greek-omitted} [συν]{.greek-omitted} [ολω]{.greek-omitted} [τω]{.greek-omitted} [οικω]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [των]{.greek-omitted} [κορινθιων]{.greek-omitted} [ακουοντες]{.greek-omitted} [επιστευον]{.greek-omitted} [[στε]{.greek-supplied}[υ]{.unclear}ον]{.greek-added} και εβαπτιζοντο[18:8]{.aside}

[ειπ]{.greek-supplied}[εν]{.unclear} [δε]{.unclear} [ο]{.unclear} [κυριος]{.greek-omitted} [[κς]{.unclear}]{.greek-added} δι [ορ]{.unclear}αματος εν [νυκ]{.greek-supplied}τ[ι]{.unclear} [τω]{.unclear} [παυλ]{.unclear}[ω]{.greek-supplied} [μη]{.greek-supplied} φ[ο]{.unclear}[βο]{.greek-supplied}[υ]{.unclear} [α]{.unclear}λλα λ[α]{.unclear}λ[ει]{.greek-supplied} [και]{.greek-supplied} [μη]{.greek-supplied} [σι]{.greek-supplied}ω[πησης]{.greek-supplied}[18:9]{.aside}

[διοτι]{.greek-supplied} [εγω]{.greek-supplied} [ει]{.greek-supplied}[μι]{.unclear} με[τ]{.greek-supplied}α [σου]{.greek-supplied} [και]{.greek-supplied} [ουδεις]{.greek-supplied} [επιθησε]{.greek-supplied}[ται]{.greek-supplied} [σοι]{.greek-omitted} [του]{.greek-omitted} [κακωσαι]{.greek-omitted} [σε]{.greek-omitted} [διοτι]{.greek-omitted} [λαος]{.greek-omitted} [εστιν]{.greek-omitted} [μοι]{.greek-omitted} [πολυς]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [ταυτη]{.greek-omitted}[[18:10 *(lacunose)*]{.lacunose}]{.aside}

[εκαθισεν]{.greek-omitted} [τε]{.greek-omitted} [ενιαυτον]{.greek-omitted} [και]{.greek-omitted} [μηνας]{.greek-omitted} [εξ]{.greek-omitted} [διδασκων]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted} [τ]{.greek-supplied}[ο]{.unclear}ν λογον του [θεου]{.greek-abbr}[18:11]{.aside}

[[γα]{.unclear}λλι]{.greek-added} [γαλλιωνος]{.greek-omitted} [δε]{.greek-omitted} [ανθυπατευοντος]{.greek-omitted} [της]{.greek-omitted} [αχαιας]{.greek-omitted} [κατεπεστησαν]{.greek-omitted} [ομοθυμαδον]{.greek-omitted} [οι]{.greek-omitted} [ιουδαιοι]{.greek-omitted} [τω]{.greek-omitted} [παυλω]{.greek-omitted} [και]{.greek-omitted} [ηγαγον]{.greek-omitted} [αυτον]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [βημα]{.greek-omitted}[18:12]{.aside}

[γαλλιωνος]{.greek-omitted} [[ωνο]{.greek-supplied}[ς]{.unclear}]{.greek-added} [δε]{.unclear} ανθυπατευοντος [τη]{.greek-supplied}ς αχαιας κατεπεστησαν [ομ]{.greek-supplied}οθυμαδον οι ιουδαιοι [τ]{.greek-supplied}ω παυλω και ηγαγον [αυ]{.greek-supplied}τον επι το βημα[18:12 | instance no. 2]{.aside}

λεγον[τ]{.greek-supplied}ες οτι παρα τον νομον [ου]{.greek-supplied}τος [αναπειθει]{.greek-omitted} [αναπειθη]{.greek-added} τους [ανθρωπους]{.greek-abbr} [σε]{.greek-supplied}βεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλον[το]{.greek-supplied}[ς]{.unclear} δε του παυλου ανοιγειν [το]{.greek-omitted} [στομα]{.greek-omitted} [ειπεν]{.greek-omitted} [ο]{.greek-omitted} [γαλλιων]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [ιουδαιους]{.greek-omitted} [ει]{.greek-omitted} [μεν]{.greek-omitted} [ουν]{.greek-omitted} [ην]{.greek-omitted} [αδικημα]{.greek-omitted} [τι]{.greek-omitted} [η]{.greek-omitted} [ραδιουργημα]{.greek-omitted} [πονηρον]{.greek-omitted} [ω]{.greek-omitted} [ιουδαιοι]{.greek-omitted} [κατα]{.greek-omitted} [λογον]{.greek-omitted} [αν]{.greek-omitted} [ηνεσχομην]{.greek-omitted} [υμων]{.greek-omitted}[18:14]{.aside}

[μελλοντος]{.greek-omitted} [δε]{.greek-omitted} [του]{.greek-omitted} [παυλου]{.greek-omitted} [ανοιγειν]{.greek-omitted} [το]{.greek-omitted} [στομα]{.greek-omitted} [ειπεν]{.greek-omitted} [ο]{.greek-omitted} [γαλλιων]{.greek-omitted} προς τους ιουδαιους ει [μεν]{.greek-supplied} [ουν]{.greek-omitted} ην αδικημα τι η ρα[δι]{.greek-supplied}ουργημα πονηρον [ω]{.unclear} [ι]{.greek-supplied}ουδαιοι κατα λογον α[ν]{.greek-supplied} [ηνεσχομην]{.greek-omitted} [[α]{.greek-supplied}νεσχομην]{.greek-added} υμων[18:14 | instance no. 2]{.aside}

ει [δε]{.greek-supplied} ζητημα εστιν περι [λο]{.greek-supplied}γου και ονοματων [και]{.greek-supplied} νομου του καθ υμας [ο]{.greek-supplied}ψεσθ[ε]{.unclear} αυτοι κριτης [γ]{.unclear}[αρ]{.greek-supplied} εγω τουτων ου βουλ[ο]{.greek-supplied}μαι ε[ι]{.unclear}ναι[18:15]{.aside}

και απηλασ[εν]{.greek-supplied} αυτους απο του βημα[τος]{.greek-supplied}[18:16]{.aside}

επιλαβομενοι δε παν[τες]{.greek-supplied} οι ελληνε[ς]{.unclear} [σ]{.unclear}ωσθενη[ν]{.greek-supplied} τον αρχ[ισυν]{.greek-supplied}αγωγο[ν]{.greek-supplied} ετ[υ]{.unclear}πτο[ν]{.unclear} [εμπ]{.unclear}ρ[οσ]{.unclear}θε[ν]{.greek-supplied} το[υ]{.unclear} [β]{.unclear}ημα[τος]{.unclear} [κ]{.unclear}αι ουδ[εν]{.greek-supplied} [τ]{.unclear}ου[των]{.unclear} [τω]{.unclear} [γ]{.unclear}αλ[λ]{.unclear}ι[ω]{.unclear}νι εμελλ[ε]{.unclear}ν[18:17]{.aside}

ο δε παυ[λος]{.greek-supplied} [ετι]{.greek-omitted} προσμ[ε]{.unclear}ινα[ς]{.unclear} ημερας [ι]{.unclear}κ[α]{.unclear}νας τοις αδελ[φ]{.unclear}οι[ς]{.unclear} [αποτ[α]{.greek-supplied}]{.greek-added} [αποταξαμενος]{.greek-omitted} [εξεπλει]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [συριαν]{.greek-omitted} [και]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [πρισκιλλα]{.greek-omitted} [και]{.greek-omitted} [ακυλας]{.greek-omitted} [κειραμενος]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [εν]{.greek-omitted} [κεγχρεαις]{.greek-omitted} [ειχεν]{.greek-omitted} [γαρ]{.greek-omitted} [ευχην]{.greek-omitted}[18:18]{.aside}

[[ξαμενος]{.greek-supplied}]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [παυλος]{.greek-omitted} [ετι]{.greek-omitted} [προσμεινας]{.greek-omitted} [ημερας]{.greek-omitted} [ικανας]{.greek-omitted} [τοις]{.greek-omitted} [αδελφοις]{.greek-omitted} [αποταξαμενος]{.greek-omitted} [ε]{.unclear}ξεπλ[ε]{.unclear}ι ει[ς]{.unclear} [την]{.unclear} [συ]{.greek-supplied}ριαν και συν αυτω πρισ[κι]{.greek-supplied}λλα και ακυλας [κειραμενος]{.greek-omitted} [κηρα[μ]{.greek-supplied}ενος]{.greek-added} την κεφαλην εν [κε]{.greek-supplied}γχρεαις ειχεν γαρ ευ[χ]{.greek-supplied}[η]{.unclear}ν[18:18 | instance no. 2]{.aside}

κατηντησεν δε [εις]{.greek-supplied} [ε]{.unclear}φεσον [και]{.greek-omitted} [εκεινους]{.greek-omitted} [κακεινους]{.greek-added} [κατελιπεν]{.greek-omitted} [[κ]{.greek-supplied}[α]{.unclear}τελειπεν]{.greek-added} αυτου αυ[τος]{.greek-supplied} δε [εισελθων]{.greek-omitted} [εισελθον]{.greek-added} εις την [συ]{.greek-supplied}ναγωγην διελεχθη [τ]{.greek-supplied}οις ιουδαιοις[18:19]{.aside}

ερωτων[τ]{.greek-supplied}ων δε αυτων επι πλει[ονα]{.greek-supplied} [χ]{.unclear}ρονον μειναι [παρ]{.greek-omitted} [αυτοις]{.greek-omitted} ουκ [επενευσεν]{.greek-omitted} [ε]{.greek-added}[18:20]{.aside}

[ερωτωντων]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [επι]{.greek-omitted} [πλειονα]{.greek-omitted} [χρονον]{.greek-omitted} [μειναι]{.greek-omitted} [παρ]{.greek-omitted} [αυτοις]{.greek-omitted} [ουκ]{.greek-omitted} [επενευσεν]{.greek-omitted} [[πε]{.greek-supplied}νευσεν]{.greek-added}[18:20 | instance no. 2]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} απεταξα[το]{.greek-supplied} αυτοις ειπων δει με [παντως]{.greek-omitted} [[π]{.greek-supplied}[α]{.unclear}ντος]{.greek-added} την εορτην [τ]{.greek-supplied}[η]{.unclear}ν ερχομενην ποιησαι [εις]{.greek-supplied} [ι]{.unclear}εροσολυμα παλιν δε [αν]{.greek-supplied}ακαμψω προς υμας [το]{.greek-supplied}υ [θεου]{.greek-abbr} θελοντος [και]{.greek-added} [αν]{.greek-supplied}ηχθη απο της εφεσου[18:21]{.aside}

[και]{.greek-supplied} κατελθων εις [καισαρειαν]{.greek-omitted} [καισαριαν]{.greek-added} [αναβας]{.greek-omitted} [και]{.greek-omitted} [ασπασαμενος]{.greek-omitted} [την]{.greek-omitted} [εκκλησιαν]{.greek-omitted} [κατεβη]{.greek-omitted} [εις]{.greek-omitted} [αντιοχειαν]{.greek-omitted}[18:22]{.aside}

[και]{.greek-omitted} [κατελθων]{.greek-omitted} [εις]{.greek-omitted} [καισαρειαν]{.greek-omitted} ανα[β]{.unclear}ας και ασπ[α]{.unclear}[σαμενος]{.greek-supplied} [την]{.greek-supplied} εκκλησιαν κατεβη εις α[ν]{.greek-supplied}τιοχειαν[18:22 | instance no. 2]{.aside}

και ποιησας χ[ρο]{.greek-supplied}νον τινα εξηλθεν [διερ]{.unclear}[χο]{.greek-supplied}μενος καθεξης την γ[α]{.unclear}λ[α]{.greek-supplied}τικην χωραν και φρυ[γιαν]{.greek-supplied} επιστηριζων παντα[ς]{.greek-supplied} [τους]{.greek-supplied} μαθητας[18:23]{.aside}

ιουδαιος [δε]{.greek-supplied} [τις]{.greek-supplied} απολλως ονοματι αλε[ξαν]{.greek-supplied}δρευς [τω]{.greek-omitted} [το]{.greek-added} γεν[ε]{.unclear}ι ανηρ [λ]{.unclear}[ογιος]{.greek-supplied} κατηντησεν εις ε[φε]{.unclear}[σον]{.greek-supplied} δυνατος ων εν ταις [γ]{.unclear}[ρα]{.greek-supplied}φαις[18:24]{.aside}

ουτος ην [κατηχημενος]{.greek-omitted} [κατη[χ]{.unclear}[ημε]{.greek-supplied}]{.greek-added} [την]{.greek-omitted} [οδον]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [και]{.greek-omitted} [ζεων]{.greek-omitted} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [ελαλει]{.greek-omitted} [και]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [ακριβως]{.greek-omitted} [τα]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [επισταμενος]{.greek-omitted} [μονον]{.greek-omitted} [το]{.greek-omitted} [βαπτισμα]{.greek-omitted} [ιωαννου]{.greek-omitted}[18:25]{.aside}

[νος]{.greek-added} [ουτος]{.greek-omitted} [ην]{.greek-omitted} [κατηχημενος]{.greek-omitted} την οδον του [κυριου]{.greek-abbr} [και]{.greek-supplied} ζεων τω [πνευματι]{.greek-abbr} ελαλε[ι]{.unclear} [κ]{.unclear}[αι]{.greek-supplied} [ε]{.greek-supplied}διδα[σ]{.unclear}κεν ακριβως τ[α]{.greek-supplied} [πε]{.greek-supplied}ρι του [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} επισταμεν[ο]{.unclear}[ς]{.greek-supplied} [μο]{.greek-supplied}νον το βαπτισμα ιωα[ν]{.greek-supplied}νου[18:25 | instance no. 2]{.aside}

ουτος τε ηρξατο [π]{.unclear}[αρ]{.greek-supplied}ρησιαζεσθαι εν τη συ[ν]{.unclear}[α]{.greek-supplied}γωγη ακουσαντες δε [αυ]{.greek-supplied}του ακυλας και πρισκιλλα [προσελαβοντο]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ακριβεστερον]{.greek-omitted} [αυτω]{.greek-omitted} [εξεθεντο]{.greek-omitted} [την]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [οδον]{.greek-omitted}[18:26]{.aside}

