---
title: "Collation of Byz^RP^ vs 20130 (130)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 130 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20130).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 130                                   	| λογος                              	|
| 130 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 130 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 130               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 130                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 130 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 130                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

[[ρος]{.greek-supplied}]{.greek-added} [και]{.greek-omitted} [προσελθων]{.greek-omitted} [ηγειρεν]{.greek-omitted} [αυτην]{.greek-omitted} [κρατησας]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} αυτ[ης]{.unclear} και αφη[κεν]{.greek-supplied} [αυτ]{.greek-supplied}[ην]{.unclear} [ο]{.unclear} πυρετο[ς]{.unclear} [ευ]{.unclear}θεως [και]{.greek-supplied} [διηκονει]{.greek-omitted} [[δ]{.unclear}ι[η]{.unclear}κονι]{.greek-added} αυτο[ις]{.unclear}[1:31]{.aside}

[οψ]{.greek-supplied}[ι]{.unclear}ας δε γεν[ο]{.unclear}μενης [οτ]{.unclear}[ε]{.greek-supplied} [εδ]{.greek-supplied}υ ο [η]{.unclear}λιος εφε[ρο]{.unclear}[ν]{.greek-supplied} προς [αυ]{.greek-supplied}τον πα[ντα]{.unclear}ς τ[ους]{.unclear} [κακως]{.unclear} [εχοντα]{.greek-supplied}ς κ[αι]{.unclear} [το]{.unclear}[υς]{.greek-supplied} δαιμονι[ζ]{.unclear}ο[μ]{.unclear}ε[ν]{.unclear}[ους]{.greek-supplied}[1:32]{.aside}

κ[αι]{.greek-supplied} [[ην]{.greek-supplied}]{.greek-added} [[ολη]{.greek-supplied}]{.greek-added} [η]{.greek-supplied} [πολις]{.greek-supplied} [ολη]{.greek-omitted} [επισυνηγμενη]{.greek-omitted} [ην]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted}[[1:33 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-supplied} [εθεραπ]{.greek-supplied}ευ[σ]{.greek-supplied}[εν]{.unclear} [πολ]{.unclear}[λους]{.greek-supplied} [κα]{.greek-supplied}[κ]{.unclear}ως εχ[οντας]{.unclear} ποικιλ[αις]{.unclear} [νο]{.greek-supplied}[σοι]{.greek-supplied}[ς]{.unclear} [και]{.unclear} δαιμονια πολλα [εξ]{.greek-supplied}ε[β]{.unclear}αλεν και ουκ ηφ[ιεν]{.greek-supplied} [λαλειν]{.greek-omitted} [[λ]{.greek-supplied}αλιν]{.greek-added} τα δαιμ[ο]{.unclear}ν[ια]{.unclear} οτι [ηδεισαν]{.greek-omitted} [η[δ]{.unclear}ι[σα]{.greek-supplied}[ν]{.unclear}]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added}[1:34]{.aside}

και π[ρ]{.greek-supplied}ω[ι]{.greek-supplied} [εννυχον]{.greek-omitted} [ε[ννυχα]{.greek-supplied}]{.greek-added} [λιαν]{.greek-supplied} [α]{.greek-supplied}[ναστα]{.unclear}ς εξηλ[θεν]{.greek-supplied} [και]{.greek-supplied} [απηλ]{.greek-supplied}θεν εις ερημον τοπον κακει [προ]{.unclear}[σηυχετο]{.greek-supplied}[1:35]{.aside}

[και]{.greek-supplied} [κατεδιωξαν]{.greek-omitted} [[κατ]{.greek-supplied}[ε]{.unclear}διο[ξα]{.unclear}ν]{.greek-added} αυτον ο σι[μ]{.unclear}ων και οι μετ α[υ]{.unclear}το[υ]{.unclear}[1:36]{.aside}

[και]{.greek-supplied} [ευ]{.greek-supplied}[ρ]{.unclear}ον[τ]{.unclear}ες αυτον λεγ[ο]{.unclear}υσι[ν]{.unclear} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [παντες]{.greek-omitted} [σε]{.greek-omitted} [ζητουσιν]{.greek-omitted}[1:37]{.aside}

[και]{.greek-omitted} [ευροντες]{.greek-omitted} [αυτον]{.greek-omitted} [λεγουσιν]{.greek-omitted} αυτω οτι π[αν]{.unclear}[τες]{.greek-supplied} [[ζητουσιν]{.greek-supplied}]{.greek-added} [σε]{.greek-supplied} [ζητουσιν]{.greek-omitted}[1:37 | instance no. 2]{.aside}

και λεγει α[υ]{.unclear}τοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} αγωμ[εν]{.unclear} εις τας εχομενας κω[μ]{.unclear}[οπολεις]{.greek-supplied} [ινα]{.greek-omitted} [και]{.greek-omitted} [εκει]{.greek-omitted} [κηρυξω]{.greek-omitted} [εις]{.greek-omitted} [τουτο]{.greek-omitted} [γαρ]{.greek-omitted} [εξεληλυθα]{.greek-omitted}[[1:38 *(lacunose)*]{.lacunose}]{.aside}

[και]{.unclear} [ερχετ]{.unclear}[αι]{.greek-supplied} προς [αυ]{.unclear}τ[ον]{.unclear} [λε]{.unclear}[προς]{.greek-supplied} παρα[καλ]{.unclear}[ω]{.greek-supplied}ν αυτον και [γ]{.unclear}ον[υ]{.unclear}πετ[ων]{.unclear} αυτον [και]{.unclear} [λεγων]{.unclear} [αυ]{.unclear}[τω]{.greek-supplied} οτι εα[ν]{.unclear} [θ]{.unclear}ελης δυνασαι με [καθαρισαι]{.unclear}[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [σπλαγχνισ]{.greek-supplied}[θεις]{.unclear} [εκτεινας]{.greek-supplied} [την]{.greek-supplied} [χειρα]{.greek-supplied} [ηψατο]{.greek-omitted} [αυ]{.greek-supplied}[του]{.greek-supplied} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [θελω]{.greek-omitted} [καθαρισθητι]{.greek-omitted}[[1:41 *(lacunose)*]{.lacunose}]{.aside}

και ειπον[τ]{.unclear}[ος]{.greek-supplied} [αυτου]{.greek-supplied} [ευθε]{.greek-supplied}ω[ς]{.unclear} [απηλθεν]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [λεπρα]{.greek-omitted} και [εκαθ]{.unclear}[αρισθ]{.greek-supplied}[η]{.unclear}[[1:42 *(lacunose)*]{.lacunose}]{.aside}

και [εμ]{.unclear}βριμ[ησαμεν]{.unclear}ος αυτω ευ[θε]{.unclear}ως ε[ξ]{.unclear}ε[β]{.unclear}αλ[ε]{.unclear}ν αυτον[1:43]{.aside}

και [λε]{.unclear}[γει]{.greek-supplied} [αυτω]{.greek-omitted} [ορα]{.greek-omitted} [μηδενι]{.greek-omitted} [μηδεν]{.greek-omitted} [ειπης]{.greek-omitted} [αλλ]{.greek-omitted} [υπαγε]{.greek-omitted} [σεαυτον]{.greek-omitted} [δειξον]{.greek-omitted} [τω]{.greek-omitted} [ιερει]{.greek-omitted} [και]{.greek-omitted} [προσενεγκε]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [καθαρισμου]{.greek-omitted} [σου]{.greek-omitted} [α]{.greek-omitted} [προσεταξεν]{.greek-omitted} [μωσης]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted}[1:44]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης [αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγε σεαυτον [δειξον]{.greek-omitted} [διξ[ον]{.unclear}]{.greek-added} τω [ιερει]{.greek-omitted} [ιερι]{.greek-added} και προσενεγκε περι του καθαρισμου σου α προσεταξε[ν]{.unclear} [μωσης]{.greek-omitted} [[μωυ]{.greek-supplied}σης]{.greek-added} [εις]{.greek-supplied} [μαρτυριον]{.greek-supplied} [αυτοις]{.greek-supplied}[1:44 | instance no. 2]{.aside}

[ο]{.greek-supplied} δε [εξελθων]{.greek-supplied} [ηρξα]{.greek-supplied}το [κηρυσσειν]{.greek-omitted} [[κηρ]{.greek-supplied}[υ]{.unclear}σσ[ιν]{.greek-supplied}]{.greek-added} [πολλ]{.greek-supplied}[α]{.unclear} κα[ι]{.unclear} [διαφημιζειν]{.greek-omitted} [διαφημιζιν]{.greek-added} τον λο[γ]{.unclear}[ον]{.greek-supplied} ωσ[τε]{.unclear} μηκετ[ι]{.greek-supplied} αυτ[ον]{.unclear} δυ[ν]{.unclear}ασ[θ]{.unclear}αι φανερως εις [πολιν]{.greek-omitted} [πο[λ]{.greek-supplied}υν]{.greek-added} εισελθειν [αλλ]{.greek-omitted} [αλλα]{.greek-added} εξω [εν]{.greek-omitted} [επ]{.greek-added} ερημοις τ[ο]{.unclear}ποις [ην]{.greek-omitted} [εν]{.greek-added} και [ηρχοντο]{.greek-omitted} [ερχοντο]{.greek-added} προς αυτον [πανταχοθεν]{.greek-omitted} [[παντοθε]{.greek-supplied}ν]{.greek-added}[1:45]{.aside}

### Chapter 2

και ε[ι]{.greek-supplied}σηλθεν [παλιν]{.greek-supplied} [εις]{.greek-supplied} [καπερναουμ]{.greek-omitted} [καφ[αρνα]{.greek-supplied}[ο]{.unclear}υμ]{.greek-added} δι η[μ]{.unclear}ερων και [η]{.unclear}κουσθη οτι εις οικον εστιν[2:1]{.aside}

και ευθεως συ[ν]{.unclear}ηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και [ελαλει]{.greek-omitted} [αυτοις]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted}[2:2]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [συνηχθησαν]{.greek-omitted} [πολλοι]{.greek-omitted} [ωστε]{.greek-omitted} [μηκετι]{.greek-omitted} [χωρειν]{.greek-omitted} [μηδε]{.greek-omitted} [τα]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted} [και]{.greek-omitted} ελαλει αυτοις τον λογον [περι]{.greek-added} [του]{.greek-added} [πα[ρα]{.unclear}λυτικου]{.greek-added}[2:2 | instance no. 2]{.aside}

και ερχονται προς αυτον [παραλυτικ]{.greek-supplied}ον φ[ε]{.unclear}ρ[οντε]{.unclear}ς αι[ρομεν]{.greek-supplied}ο[ν]{.greek-supplied} [υπο]{.greek-supplied} [τε]{.greek-supplied}[σσαρ]{.unclear}ων[2:3]{.aside}

[και]{.greek-supplied} [μη]{.greek-supplied} [δυναμενοι]{.greek-supplied} [προσ]{.greek-supplied}εγγι[σαι]{.greek-supplied} [αυτω]{.greek-supplied} [δια]{.greek-supplied} [τον]{.greek-supplied} [οχ]{.greek-supplied}λ[ο]{.greek-supplied}ν απε[στεγασαν]{.greek-supplied} [την]{.greek-supplied} [στεγην]{.greek-supplied} [ο]{.greek-supplied}που [ην]{.greek-supplied} [και]{.greek-supplied} [εξορυξα]{.greek-supplied}[ν]{.unclear}τες [χαλωσιν]{.greek-supplied} [τον]{.greek-supplied} [κραββατον]{.greek-omitted} [[κραβα]{.greek-supplied}[τ]{.unclear}τον]{.greek-added} [εφ]{.greek-omitted} [ω]{.greek-omitted} [ο]{.greek-omitted} παρ[αλ]{.unclear}υτικος [κατεκειτο]{.greek-omitted} [κατεκιτο]{.greek-added}[[2:4 *(lacunose)*]{.lacunose}]{.aside}

[ιδων]{.greek-omitted} [ειδων]{.greek-added} δε ο [ιησους]{.greek-abbr} την πιστιν αυτ[ω]{.unclear}ν λεγει τω παραλυτ[ικω]{.greek-supplied} τεκνον [αφεωνται]{.greek-omitted} [αφιενται]{.greek-added} [σοι]{.greek-omitted} [[σ]{.unclear}ου]{.greek-added} [αι]{.unclear} [α]{.unclear}μαρτιαι [σου]{.greek-omitted}[2:5]{.aside}

ησ[α]{.greek-supplied}[ν]{.unclear} δε τινες τ[ων]{.greek-supplied} [γραμματεων]{.greek-supplied} [εκει]{.greek-supplied} [καθημε]{.greek-supplied}[νοι]{.greek-supplied} και [διαλο]{.unclear}[γιζ]{.greek-supplied}[ομε]{.unclear}νοι ε[ν]{.unclear} ταις καρδιαις αυτων[2:6]{.aside}

[τι]{.greek-supplied} ουτος ουτως [λαλει]{.greek-omitted} [λαλι]{.greek-added} [βλασφημιας]{.greek-omitted} [βλασ[φη]{.greek-supplied}μας]{.greek-added} τις δυναται αφιενα[ι]{.greek-supplied} αμα[ρ]{.unclear}τιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνο[υ]{.unclear}ς ο [ιησους]{.greek-abbr} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [ουτως]{.greek-omitted} [αυτοι]{.greek-omitted} [διαλογιζονται]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [ταυτα]{.greek-omitted} [διαλογιζεσθε]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [καρδιαις]{.greek-omitted} [υμων]{.greek-omitted}[[2:8 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [επιγνους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [ουτως]{.greek-omitted} [αυτοι]{.greek-omitted} [διαλογιζονται]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-supplied} ειπεν αυτοις τι [ταυτα]{.greek-supplied} [διαλογιζεσθε]{.greek-omitted} [[δια]{.greek-supplied}[λ]{.unclear}ογιζεσθαι]{.greek-added} εν ταις [καρδιαις]{.greek-supplied} [υ]{.unclear}μων[[2:8 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

τι εστιν ευ[κοπωτερ]{.greek-supplied}[ο]{.unclear}ν ειπειν τω [παραλυτι]{.greek-supplied}κω αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} [αι]{.greek-supplied} [αμαρτια]{.greek-supplied}ι η ειπειν εγειραι [και]{.greek-supplied} [αρον]{.greek-supplied} [σ]{.greek-supplied}ου τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} [και]{.greek-supplied} [περιπατει]{.greek-supplied}[2:9]{.aside}

ινα δε ειδητε [οτι]{.greek-supplied} [εξουσι]{.greek-supplied}αν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} [επι]{.greek-supplied} [τ]{.unclear}ης γης [αφιεναι]{.greek-added} [αμαρτιας]{.greek-supplied} [λ]{.unclear}εγει τω παραλυτι[κω]{.greek-supplied}[2:10]{.aside}

[σοι]{.greek-supplied} [λε]{.greek-supplied}[γ]{.unclear}ω εγειραι και [αρον]{.greek-supplied} [τον]{.greek-supplied} [κραββατον]{.greek-omitted} [[κ]{.unclear}ραβαττον]{.greek-added} σου και [υπαγε]{.greek-supplied} [εις]{.greek-supplied} [τ]{.unclear}ον οικον σου[2:11]{.aside}

[και]{.greek-supplied} [ηγερθ]{.greek-supplied}η ευθεως και [αρας]{.greek-supplied} [τον]{.greek-supplied} [κραββατον]{.greek-omitted} [[κ]{.unclear}ραβαττον]{.greek-added} εξηλ[θεν]{.greek-supplied} [εναν]{.greek-supplied}τιον παντων ωσ[τε]{.greek-supplied} [εξιστασ]{.greek-supplied}θαι παντας και [δοξαζειν]{.greek-supplied} τον [θεον]{.greek-abbr} λεγοντας [οτι]{.greek-supplied} [ουδεπ]{.greek-supplied}οτε ουτως ειδομεν[2:12]{.aside}

[και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [παλιν]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} ηρχ[ε]{.unclear}το π[ρ]{.unclear}ος α[υ]{.unclear}τον [και]{.greek-supplied} εδιδασκεν αυτου[ς]{.greek-supplied} [περι]{.greek-added} [λευι]{.greek-added} [του]{.greek-added} [τε[―]{.gap}]{.greek-added}[2:13]{.aside}

και παραγων [ει]{.unclear}δε[ν]{.unclear} [λευι]{.greek-omitted} [[λευιν]{.greek-supplied}]{.greek-added} τον του αλφαιου κ[αθ]{.unclear}[ημε]{.greek-supplied}νον [επι]{.greek-omitted} [επε]{.greek-added} το τελ[ω]{.unclear}ν[ιον]{.greek-supplied} [και]{.greek-supplied} λεγει αυτω α[κ]{.unclear}ο[λο]{.unclear}υ[θει]{.greek-supplied} [μοι]{.greek-supplied} και αναστας ηκο[λ]{.unclear}[ουθη]{.greek-supplied}σεν αυτω[2:14]{.aside}

και εγενετο [εν]{.unclear} τ[ω]{.greek-supplied} [κατακεισθαι]{.greek-omitted} [[κατα]{.greek-supplied}κλιθηναι]{.greek-added} αυτ[ον]{.unclear} [ε]{.greek-supplied}[ν]{.unclear} [τη]{.greek-supplied} [οι]{.greek-supplied}κια αυτου και π[ολ]{.unclear}[λοι]{.greek-supplied} [τε]{.greek-supplied}λωναι και αμαρτ[ωλοι]{.greek-supplied} [συν]{.greek-supplied}ανεκειντο τω [ιησου]{.greek-abbr} [και]{.greek-supplied} [τοις]{.greek-supplied} μαθηταις αυτο[υ]{.unclear} η[σαν]{.greek-supplied} [γαρ]{.unclear} πολλοι και [ηκολουθησαν]{.greek-omitted} [[η]{.unclear}κ[ολου]{.greek-supplied}θουν]{.greek-added} αυτω[2:15]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} γραμ[μ]{.unclear}[ατεις]{.greek-supplied} [των]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [φαρισα[ι]{.unclear}ων]{.greek-added} [ιδ]{.unclear}[οντες]{.greek-supplied} αυτο[ν]{.unclear} εσθι[ο]{.unclear}ν[τα]{.greek-supplied} [μ]{.unclear}[ετα]{.greek-supplied} των [τελωνων]{.greek-omitted} [τε[λω]{.unclear}ν[ω]{.unclear}[νων]{.greek-supplied}]{.greek-added} [κ]{.greek-supplied}[α]{.unclear}ι α[μ]{.unclear}[αρτωλων]{.greek-supplied} [ελεγον]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [τι]{.greek-omitted} [οτι]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} [εσθιει]{.greek-omitted} [και]{.greek-omitted} [πινει]{.greek-omitted}[2:16]{.aside}

