---
title: "Collation of Byz^RP^ vs 20140 (140)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 140 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20140).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 140                                   	| λογος                              	|
| 140 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 140 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 140               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 140                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 140 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 140                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 5

αναστας [δε]{.greek-omitted} τις εν τω συνεδριω φαρισαιος [ον]{.unclear}οματι γαμαλιηλ [ν]{.unclear}ομοδιδασκαλος τιμιος παντι τω λαω εκελευσεν εξω βραχυ [τι]{.greek-omitted} τους αποστολους ποιησαι[5:34]{.aside}

ειπεν τε προς αυτους ανδρες ισραηλιται [προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} [αυτοις]{.greek-added} [εαυτοις]{.corr} επι τοις [ανθρωποις]{.greek-abbr} τουτοις τι μελλετε πρασσειν[5:35]{.aside}

προ γαρ τουτων των ημερων [ανεστη]{.greek-omitted} [ανεστι]{.greek-added} θευδας λεγων ειναι τινα εαυτον ω [προσε]{.greek-added} [προσεκληθη]{.greek-omitted} [αριθμος]{.greek-omitted} [ανδρων]{.greek-omitted} [ωσει]{.greek-omitted} [τετρακοσιων]{.greek-omitted} [ος]{.greek-omitted} [ανηρεθη]{.greek-omitted} [και]{.greek-omitted} [παντες]{.greek-omitted} [οσοι]{.greek-omitted} [επειθοντο]{.greek-omitted} [αυτω]{.greek-omitted} [διελυθησαν]{.greek-omitted} [και]{.greek-omitted} [εγενοντο]{.greek-omitted} [εις]{.greek-omitted} [ουδεν]{.greek-omitted}[5:36]{.aside}

[κλιθησαν]{.greek-added} [ανδρων]{.greek-added} [προ]{.greek-omitted} [γαρ]{.greek-omitted} [τουτων]{.greek-omitted} [των]{.greek-omitted} [ημερων]{.greek-omitted} [ανεστη]{.greek-omitted} [θευδας]{.greek-omitted} [λεγων]{.greek-omitted} [ειναι]{.greek-omitted} [τινα]{.greek-omitted} [εαυτον]{.greek-omitted} [ω]{.greek-omitted} [προσεκληθη]{.greek-omitted} αριθμος [ως]{.greek-added} [ανδρων]{.greek-omitted} [ωσει]{.greek-omitted} [τετρακοσιων]{.greek-omitted} [τερακοσιων]{.greek-added} ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις [ουδεν]{.greek-omitted} [ουθεν]{.greek-added}[5:36 | instance no. 2]{.aside}

μετα τουτον ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της απογραφης και απεστησεν λαον ικανον οπισω αυτου κακεινος απωλετο και παντες οσοι [επειθοντο]{.greek-omitted} [επιθοντο]{.greek-added} αυτω διεσκορπισθησαν[5:37]{.aside}

και τα νυν λεγω υμιν αποστητε απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε αυτους [ο]{.unclear}τι εαν [η]{.unclear} εξ [ανθρωπων]{.greek-abbr} [η]{.greek-omitted} [βουλη]{.greek-omitted} [η]{.greek-omitted} [το]{.greek-omitted} [εργον]{.greek-omitted} [τουτο]{.greek-omitted} [καταλυθησεται]{.greek-omitted}[5:38]{.aside}

