---
title: "Collation of Byz^RP^ vs 20166 (166)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 166 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20166).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 166                                   	| λογος                              	|
| 166 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 166 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 166               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 166                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 166 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 166                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 28

[εμεινεν]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [παυλος]{.greek-omitted} [δι]{.greek-supplied}[ετι]{.unclear}[αν]{.greek-supplied} [ολην]{.greek-supplied} [εν]{.greek-supplied} [ι]{.greek-supplied}[διω]{.unclear} [μισθωμα]{.greek-supplied}τι κ[αι]{.unclear} [απεδεχε]{.greek-supplied}το πα[ν]{.unclear}[τας]{.greek-supplied} [τους]{.greek-supplied} εισπορ[ευ]{.unclear}[ομε]{.greek-supplied}νους προ[ς]{.greek-supplied} [αυτον]{.greek-supplied}[28:30]{.aside}

κηρυσ[σων]{.greek-supplied} [την]{.greek-supplied} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [διδασκων]{.greek-omitted} [τα]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} [μετα]{.greek-omitted} [πασης]{.greek-omitted} [παρρησιας]{.greek-omitted} [ακωλυτως]{.greek-omitted}[28:31]{.aside}

