---
title: "Collation of Byz^RP^ vs 20162 (162)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 162 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20162).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 162                                   	| λογος                              	|
| 162 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 162 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 162               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 162                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 162 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 162                                                     	| [―]{.gap}                        	|
:::

## The Gospel of John

### Chapter 2

[ταυτην]{.greek-omitted} [εποιησεν]{.greek-omitted} [την]{.greek-omitted} [αρχην]{.greek-omitted} [των]{.greek-omitted} [σημειων]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εν]{.greek-omitted} [κανα]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [και]{.greek-omitted} [εφανερωσεν]{.greek-omitted} [την]{.greek-omitted} [δοξαν]{.greek-omitted} αυτου και επιστευσαν εις αυτον οι μαθηται αυτου[2:11]{.aside}

μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} κατεβη εις [καπερναουμ]{.greek-omitted} [καφαρναουμ]{.greek-added} αυτος και η μητηρ αυτου και οι αδελφοι [αυτου]{.greek-omitted} και οι μαθηται αυτου και εκει εμειναν ου πολλας ημερας[2:12]{.aside}

και εγγυς ην το πα[σχ]{.greek-supplied}α των ιουδαιων και [ανε]{.greek-supplied}βη [ει]{.unclear}ς ιεροσολυμα ο [ιησους]{.greek-abbr}[2:13]{.aside}

[και]{.greek-supplied} [ευ]{.greek-supplied}ρεν εν τω ιερω τους πω[λου]{.greek-supplied}ντας βοας και προβατα [και]{.greek-supplied} περιστερας κα[ι]{.greek-supplied} [το]{.greek-supplied}[υ]{.unclear}ς κερμ[ατ]{.greek-supplied}ιστας καθημενους[2:14]{.aside}

[και]{.greek-supplied} ποιησας [ως]{.greek-added} φραγελλιον [εκ]{.greek-supplied} [σχοι]{.greek-supplied}νιων παντας [εξεβαλεν]{.greek-omitted} [εξεβαλετο]{.greek-added} [ε]{.greek-supplied}κ του ιερου τα τε προβατα [κ]{.unclear}[α]{.greek-supplied}ι τους βοας και των κολλυβιστων εξεχεεν [το]{.greek-omitted} [τα]{.greek-added} [κερμα]{.greek-omitted} [κερματα]{.greek-added} και τας τραπεζ[α]{.greek-supplied}ς ανεστρεψεν[2:15]{.aside}

και τοις τα[ς]{.greek-supplied} περιστερας πωλουσιν ειπεν αρατε ταυτα εντευθεν μη ποιειτε τον οικον του [πατρος]{.greek-abbr} μου οικον εμποριου[2:16]{.aside}

εμνησθησαν [δε]{.greek-omitted} οι μαθηται αυτου οτι γεγραμμενον εστιν ο [ζη]{.unclear}λος του οικου σου [καταφαγεται]{.greek-omitted} [κατεφαγετα[ι]{.unclear}]{.greek-added} [με]{.unclear}[2:17]{.aside}

απεκριθησαν ουν οι ιουδα[ι]{.unclear}οι και [ειπον]{.greek-omitted} [ειπαν]{.greek-added} αυτω τι σημ[ειον]{.greek-supplied} [δει]{.greek-supplied}κνυεις ημιν οτι ταυτ[α]{.greek-supplied} [ποιεις]{.greek-supplied}[2:18]{.aside}

απεκριθη [ιησους]{.greek-abbr} και ειπεν α[υ]{.unclear}[τοις]{.greek-supplied} λυσατ[ε]{.unclear} τον ναον τουτον [και]{.greek-supplied} [εν]{.greek-supplied} [τ]{.greek-supplied}ρισιν [η]{.unclear}μεραις εγερω [αυτον]{.greek-supplied}[2:19]{.aside}

[ειπον]{.greek-omitted} [[ειπ]{.greek-supplied}[α]{.unclear}ν]{.greek-added} ουν οι ιουδαιοι [τεσσαρακοντα]{.greek-omitted} [μ]{.greek-added} και εξ ετε[σι]{.greek-supplied}ν ωκοδομηθη ο ναος ουτος και συ εν τρισιν ημεραις [ε]{.greek-supplied}γερεις αυτον[2:20]{.aside}

εκεινος δε ελεγεν περι του ναου του σω[μ]{.unclear}ατος αυτου[2:21]{.aside}

οτε ουν ηγερθη ε[κ]{.unclear} [νεκ]{.greek-added} [νεκρων]{.greek-omitted} [εμνησθησαν]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [τουτο]{.greek-omitted} [ελεγεν]{.greek-omitted} [και]{.greek-omitted} [επιστευσαν]{.greek-omitted} [τη]{.greek-omitted} [γραφη]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [λογω]{.greek-omitted} [ω]{.greek-omitted} [ειπεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted}[2:22]{.aside}

