---
title: "Collation of Byz^RP^ vs 20184 (184)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 184 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20184).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 184                                   	| λογος                              	|
| 184 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 184 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 184               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 184                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 184 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 184                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 15

[δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γεμισας]{.greek-omitted} [σπογ]{.greek-supplied}[γον]{.unclear} [ο]{.unclear}ξο[υ]{.unclear}ς περιθεις [τε]{.greek-omitted} [κα]{.greek-supplied}[λαμ]{.unclear}ω εποτ[ιζεν]{.greek-supplied} [αυτον]{.greek-supplied} [λε]{.unclear}γω[ν]{.unclear} [αφετε]{.greek-omitted} [[αφε]{.greek-supplied}ς]{.greek-added} ιδωμεν ει ερχε[τ]{.unclear}αι ηλιας κα[θε]{.unclear}λε[ιν]{.unclear} [α]{.unclear}υτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

[ησαν]{.greek-supplied} [δε]{.greek-supplied} [κα]{.greek-supplied}ι γυναικες απο [μ]{.unclear}[α]{.greek-supplied}κροθεν θε[ω]{.unclear}ρουσαι εν αις [ην]{.greek-omitted} και [μαρια]{.greek-omitted} [μαρ[ιαμ]{.unclear}]{.greek-added} [η]{.greek-omitted} [μα]{.unclear}γδαλ[ην]{.unclear}[η]{.greek-supplied} κ[αι]{.greek-supplied} μαρια η [του]{.greek-omitted} ι[α]{.unclear}κ[ω]{.unclear}βου του μ[ικρου]{.greek-supplied} και [ιωση]{.greek-omitted} [ιωσητος]{.greek-added} [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι [και]{.greek-omitted} ο[τ]{.unclear}ε [ην]{.unclear} [ε]{.unclear}[ν]{.greek-supplied} [τη]{.greek-supplied} [γαλιλαια]{.greek-supplied} [ηκολουθουν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [διηκονουν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αλλαι]{.greek-omitted} [πολλαι]{.greek-omitted} [αι]{.greek-omitted} [συναναβασαι]{.greek-omitted} [αυτω]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted}[15:41]{.aside}

