---
title: "Collation of Byz^RP^ vs 20188 (188)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 188 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20188).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 188                                   	| λογος                              	|
| 188 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 188 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 188               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 188                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 188 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 188                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 11

[και]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [παντα]{.greek-omitted} [οψιας]{.greek-omitted} [ηδη]{.greek-omitted} [ουσης]{.greek-omitted} [της]{.greek-omitted} [ωρας]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εις]{.greek-omitted} [βηθανιαν]{.greek-supplied} [με]{.greek-supplied}τα τ[ω]{.unclear}ν [δωδε]{.greek-supplied}κα[[11:11 *(lacunose)*]{.lacunose}]{.aside}

[τ[η]{.unclear}]{.greek-added} [κ]{.greek-supplied}α[ι]{.unclear} [τη]{.greek-omitted} [ε]{.unclear}[π]{.greek-supplied}[αυ]{.greek-supplied}ριον εξελθον[τω]{.greek-supplied}[ν]{.unclear} αυτω[ν]{.unclear} απ[ο]{.unclear} [βηθανιας]{.greek-omitted} [[βιθ]{.unclear}αν[ια]{.greek-supplied}ς]{.greek-added} [επεινασεν]{.greek-omitted} [επηνασε[ν]{.unclear}]{.greek-added}[11:12]{.aside}

και ιδων συκ[ην]{.unclear} [απο]{.greek-added} μα[κ]{.unclear}[ρ]{.greek-supplied}οθεν [εχουσαν]{.greek-omitted} [φυλλα]{.greek-omitted} ηλθεν [ως]{.greek-added} [ευρησων]{.greek-added} [ει]{.greek-omitted} [αρα]{.greek-omitted} [ευρησει]{.greek-omitted} τι εν αυτη [και]{.greek-omitted} ελθων [δε]{.greek-added} [επ]{.greek-omitted} [αυτην]{.greek-omitted} ουδεν ευρε[ν]{.unclear} [εν]{.greek-added} [αυτη]{.greek-added} [ει]{.greek-omitted} [μη]{.greek-omitted} [φυλλα]{.greek-omitted} ου γαρ ην [καιρος]{.greek-omitted} [καρπ[ο]{.unclear}ς]{.greek-added} συκων[11:13]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} ο [δε]{.greek-added} [ιησους]{.greek-abbr} ει[π]{.unclear}εν αυτη μηκετι [εκ]{.greek-omitted} [μηδεις]{.greek-added} [απο]{.greek-added} σου [καρπον]{.greek-added} [φαγοι]{.greek-added} εις τον αι[ω]{.unclear}να [μηδεις]{.greek-omitted} [καρπον]{.greek-omitted} [φαγοι]{.greek-omitted} και ηκουον οι μα[θ]{.unclear}ηται αυτου[11:14]{.aside}

και [ερχοντ]{.greek-supplied}αι [ει]{.unclear}[ς]{.greek-supplied} [ιεροσολυμα]{.greek-supplied} και [εισ]{.greek-supplied}[ε]{.unclear}λθω[ν]{.unclear} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ει]{.greek-supplied}ς το ι[ε]{.unclear}[ρ]{.greek-supplied}[ο]{.unclear}ν ηρξα[τ]{.unclear}[ο]{.greek-supplied} [εκβ]{.greek-supplied}αλ[λ]{.greek-supplied}ειν τους πωλουν[τ]{.greek-supplied}ας κ[αι]{.greek-supplied} [αγοραζ]{.unclear}οντ[ας]{.greek-supplied} [εν]{.greek-supplied} [τ]{.unclear}ω ιερω [και]{.unclear} [τ]{.unclear}ας [τ]{.greek-supplied}ραπεζας των κολλυβιστων και τας καθεδρας των πωλουντων τας περιστ[ε]{.unclear}[ρας]{.greek-supplied} [κατεστρεψεν]{.greek-omitted} [ανεστρε[ψεν]{.greek-supplied}]{.greek-added}[11:15]{.aside}

[κ]{.greek-supplied}[α]{.unclear}ι ουκ ηφιε[ν]{.unclear} [[διε]{.greek-supplied}[νεγ]{.unclear}κειν]{.greek-added} [ινα]{.greek-omitted} [τινα]{.greek-added} [τις]{.greek-omitted} [διενεγκη]{.greek-omitted} σκευος δια του ιερου[11:16]{.aside}

και [ελεγεν]{.greek-added} [εδιδασκεν]{.greek-omitted} [λεγων]{.greek-omitted} αυτοις [ου]{.greek-omitted} γεγραπται [οτι]{.greek-omitted} ο οικος μου οικος προσευ[χης]{.unclear} κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν [υμεις]{.greek-omitted} [δε]{.greek-omitted} [εποιησατε]{.greek-omitted} [αυτον]{.greek-omitted} [σπηλαιον]{.greek-omitted} [ληστων]{.greek-omitted}[11:17]{.aside}

