---
title: "Collation of Byz^RP^ vs 20211 (211)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 211 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20211).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 211                                   	| λογος                              	|
| 211 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 211 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 211               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 211                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 211 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 211                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [υιου]{.greek-abbr} του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω [αποστελλω]{.greek-omitted} [αποστελω]{.greek-added} τον αγγελον μου προ προσωπου σου [ος]{.greek-omitted} [ως]{.greek-added} κατασκευασει την οδον σου [εμπροσθεν]{.greek-omitted} [σου]{.greek-omitted}[1:2]{.aside}

φωνη βοωντος εν τη ερημω [ετοιμασατε]{.greek-omitted} [ετοιμασαται]{.greek-added} την οδον [κυριου]{.greek-abbr} ευθειας [ποιειτε]{.greek-omitted} [ποιηται]{.greek-added} τας τριβους αυτου[1:3]{.aside}

εγενετο ιωανν[ης]{.greek-supplied} βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα [μετανοιας]{.greek-omitted} [μαιτανο[ι]{.unclear}[ας]{.greek-supplied}]{.greek-added} εις αφεσιν αμα[ρ]{.unclear}τιων[1:4]{.aside}

και εξεπο[ρ]{.unclear}ευετο προς [αυτον]{.greek-omitted} [πασα]{.greek-omitted} [η]{.greek-omitted} [ιουδαια]{.greek-omitted} [χωρα]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ιεροσολυμιται]{.greek-omitted} [και]{.greek-omitted} [εβαπτιζοντο]{.greek-omitted} [παντες]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιορδανη]{.greek-omitted} [ποταμω]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} [εξομολογουμενοι]{.greek-omitted} [τας]{.greek-omitted} [αμαρτιας]{.greek-omitted} [αυτων]{.greek-omitted}[1:5]{.aside}

[και]{.greek-omitted} [εξεπορευετο]{.greek-omitted} [προς]{.greek-omitted} αυτον πασα [η]{.greek-omitted} ιουδαια χωρα και οι [ιεροσολυμιται]{.greek-omitted} [ιεροσολυμειται]{.greek-added} και [εβαπτηζονο]{.greek-added} [εβαπτιζοντο]{.greek-omitted} [[εβαπτηζοντο]{.corr}]{.greek-added} παντες εν [τω]{.greek-omitted} [το]{.greek-added} [ιορδανη]{.greek-omitted} [ιορδανι]{.greek-added} ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5 | instance no. 2]{.aside}

ην δε [ο]{.greek-omitted} ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην [δερματινην]{.greek-omitted} [δερματηνην]{.greek-added} περι την οσφυν αυτου και [εσθιων]{.greek-omitted} [εσθιον]{.greek-added} ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσεν]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας [λυσαι]{.greek-omitted} [λυσ[ε]{.unclear}]{.greek-added} τον ιμαντα τ[ων]{.unclear} υποδηματων αυτου[1:7]{.aside}

εγω μεν [εβαπτισα]{.greek-omitted} [εβαπτησα]{.greek-added} υμας εν [υδατι]{.greek-omitted} [υδατη]{.greek-added} αυτ[ος]{.greek-supplied} δε [βαπτισει]{.greek-omitted} υμας [βαπτησει]{.greek-added} εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[1:8]{.aside}

[κα]{.greek-added} [και]{.corr} [εγενετο]{.greek-omitted} [ηγενετο]{.greek-added} εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της [γαλιλαιας]{.greek-omitted} [[γ]{.unclear}αληλαιας]{.greek-added} και [εβαπτισθη]{.greek-omitted} [εβαπτησθι]{.greek-added} υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και [ευθεως]{.greek-omitted} [εθεως]{.greek-added} [αναβαινων]{.greek-omitted} [αναβενον]{.greek-added} απο του υδατος [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [σχιζομενους]{.greek-omitted} [σχηζομενους]{.greek-added} τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν [κατα]{.greek-added} [καταβαινον]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted}[1:10]{.aside}

[βαινουσαν]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [αναβαινων]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [υδατος]{.greek-omitted} [ειδεν]{.greek-omitted} [σχιζομενους]{.greek-omitted} [τους]{.greek-omitted} [ουρανους]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ωσει]{.greek-omitted} [περιστεραν]{.greek-omitted} [καταβαινον]{.greek-omitted} επ α[υ]{.greek-supplied}τον[1:10 | instance no. 2]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [η[υ]{.unclear}δοκησα]{.greek-added}[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκε[ι]{.unclear} εν τη ερημω ημερας [τεσσαρακοντα]{.greek-omitted} [τεσαρακοντα]{.greek-added} [και]{.greek-added} [τεσαρακοντα]{.greek-added} [νυκτ[ας]{.unclear}]{.greek-added} πειραζομενος υπο του σατανα και ην μετα των θηρ[ι]{.unclear}ων και ο[ι]{.unclear} αγγελοι δ[ιη]{.unclear}κονουν αυτω[1:13]{.aside}

[μ]{.greek-supplied}[ε]{.unclear}τα δε το [παραδοθηναι]{.greek-omitted} [παρ[α]{.unclear}δ[ο]{.unclear}θειναι]{.greek-added} [τον]{.greek-omitted} ιωαννην ηλθεν [ο]{.greek-omitted} [ιησους]{.greek-abbr} εις την [γαλιλαιαν]{.greek-omitted} [γαληλαιαν]{.greek-added} [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

[και]{.greek-omitted} λεγων [ο]{.unclear}τι πεπληρω[τ]{.unclear}αι ο [καιρος]{.greek-omitted} [κερος]{.greek-added} και [ηγγικεν]{.greek-omitted} [ειγγηκεν]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} [μετανοειτε]{.greek-omitted} [μετανοηται]{.greek-added} και [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} εν τ[ω]{.unclear} ευαγγελιω[1:15]{.aside}

[περιπατων]{.greek-omitted} [περιπατον]{.greek-added} δε παρα την θαλασ[σ]{.unclear}αν της [γαλιλαιας]{.greek-omitted} [γαληλαιας]{.greek-added} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου του σιμω[νος]{.unclear} [βαλλοντας]{.greek-omitted} [αμφηβα[λλ]{.unclear}οντας]{.greek-added} αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα [δικτυα]{.greek-omitted} [δικτοια]{.greek-added} αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν [ολιγον]{.greek-omitted} [οληγον]{.greek-added} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των [μισθωτων]{.greek-omitted} [μησθοτων]{.greek-added} απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και αν[ε]{.unclear}κραξεν[1:23]{.aside}

λεγων [εα]{.greek-omitted} [τι]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [σοι]{.greek-omitted} [ιησου]{.greek-omitted} [ναζαρηνε]{.greek-omitted} [ηλθες]{.greek-omitted} [απολεσαι]{.greek-omitted} [ημας]{.greek-omitted} [οιδα]{.greek-omitted} [σε]{.greek-omitted} [τις]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[1:24]{.aside}

[λεγων]{.greek-omitted} εα τι ημιν και σοι [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαριναι]{.greek-added} ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24 | instance no. 2]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων [φιμωθητι]{.greek-omitted} [φημθητη]{.greek-added} [[φημοθητη]{.corr}]{.greek-added} και [εξελθε]{.greek-omitted} [εξελθαι]{.greek-added} [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε [συζητειν]{.greek-omitted} [συνζητην]{.greek-added} προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι εστιν τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις πνευμασιν τοις ακαθαρτοις [επιτασσει]{.greek-omitted} [επιτασι]{.greek-added} και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν δε η ακοη αυτου ευθυς εις ολην την περιχωρον της [γαλιλαιας]{.greek-omitted} [γαληλαιας]{.greek-added}[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και [προσελθων]{.greek-omitted} [ηγειρεν]{.greek-omitted} [αυτην]{.greek-omitted} [κρατησας]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [αφηκεν]{.greek-omitted} [αυτην]{.greek-omitted} [ο]{.greek-omitted} [πυρετος]{.greek-omitted} [ευθεως]{.greek-omitted} [και]{.greek-omitted} [διηκονει]{.greek-omitted} [αυτοις]{.greek-omitted}[1:31]{.aside}

[και]{.greek-omitted} προσελθων [ηγειρεν]{.greek-omitted} [ειγιρεν]{.greek-added} αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και [διηκονει]{.greek-omitted} [διηκονι]{.greek-added} αυτοις[1:31 | instance no. 2]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η [πολις]{.greek-omitted} [πολης]{.greek-added} ολη [επισυνηγμενη]{.greek-omitted} [επισυνιγμενη]{.greek-added} ην προς την θυραν[1:33]{.aside}

και εθεραπευσεν πολλους κακως εχοντας [ποικιλαις]{.greek-omitted} [ποικηλαις]{.greek-added} [νοσοις]{.greek-omitted} [νοσσοις]{.greek-added} και δαιμονια πολλα εξεβαλεν και ουκ ηφιεν λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ηδισαν]{.greek-added} αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι εννυχον [λιαν]{.greek-omitted} αναστας εξηλθεν και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον [κακει]{.greek-omitted} [κακη]{.greek-added} προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιοξαν]{.greek-added} αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες [αυτον]{.greek-omitted} λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας [κωμοπολεις]{.greek-omitted} [κομοπολεις]{.greek-added} ινα και εκει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων [εις]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [εκβαλλων]{.greek-omitted}[1:39]{.aside}

[ει]{.greek-added} [και]{.greek-omitted} [ην]{.greek-omitted} [κηρυσσων]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [συναγωγαις]{.greek-omitted} [αυτων]{.greek-omitted} [εις]{.corr} ολην την [γαλιλαιαν]{.greek-omitted} [γαληλαιαν]{.greek-added} και τα δαιμονια εκβαλλων[1:39 | instance no. 2]{.aside}

[και]{.greek-omitted} [κα]{.greek-added} ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων αυτω οτι εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} με [καθαρισαι]{.greek-omitted} [καθαρησαι]{.greek-added}[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [σπλαγχνισθεις]{.greek-omitted} [σπλαχνησθεις]{.greek-added} εκτεινας την χειρα ηψατο αυτου και λεγει αυτω [θελω]{.greek-omitted} [καθαρισθητι]{.greek-omitted} [καθαρησθητη]{.greek-added}[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν [η]{.greek-added} [λεπρα]{.greek-added} απ αυτου [η]{.greek-omitted} [λεπρα]{.greek-omitted} και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} περι του καθαρισμου σου α προσεταξεν μωσης εις μαρτυρι[ον]{.unclear} αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και [διαφημιζειν]{.greek-omitted} [διαφημηζειν]{.greek-added} τον λογον ωστε μηκετι αυτον δυνασθαι [φανερως]{.greek-omitted} [φανερος]{.greek-added} εις [πολιν]{.greek-omitted} [πολην]{.greek-added} εισελθειν [αλλ]{.greek-omitted} [αλλα]{.greek-added} εξω εν ερημοις τοποις ην και ηρχοντο προς [αυτον]{.greek-omitted} [πανταχοθεν]{.greek-omitted}[1:45]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εξελθων]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [πολλα]{.greek-omitted} [και]{.greek-omitted} [διαφημιζειν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ωστε]{.greek-omitted} [μηκετι]{.greek-omitted} αυτον [δυνασθαι]{.greek-omitted} [φανερως]{.greek-omitted} [εις]{.greek-omitted} [πολιν]{.greek-omitted} [εισελθειν]{.greek-omitted} [αλλ]{.greek-omitted} [εξω]{.greek-omitted} [εν]{.greek-omitted} [ερημοις]{.greek-omitted} [τοποις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ηρχοντο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πανταχοθεν]{.greek-omitted} [παντοθ[εν]{.unclear}]{.greek-added}[1:45 | instance no. 2]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισελθων]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [παλιν]{.greek-omitted} [παλην]{.greek-added} εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον εστιν[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φ[ε]{.unclear}ροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι [προσεγγισαι]{.greek-omitted} [προσεγγεισε]{.greek-added} αυτω δια τον οχλον [απεστεγασαν]{.greek-omitted} [αποστεγασαν]{.greek-added} την στεγην οπου ην και εξορυξαντες χαλωσιν τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εφ ω ο [παραλυτικος]{.greek-omitted} [παραλυτηκος]{.greek-added} κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} αυτων λεγει τω [παραλυτικω]{.greek-omitted} [παραλυτηκω]{.greek-added} τεκνον αφεωνται σοι αι [αμαρτιαι]{.greek-omitted} [αμαρτιαις]{.greek-added} σου[2:5]{.aside}

ησαν δε [τινες]{.greek-omitted} [τιναις]{.greek-added} των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτο[ς]{.unclear} [ουτως]{.greek-omitted} λαλει βλασφημιας τις δυναται αφιεναι [α]{.greek-added} [αμαρτιας]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εις]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted}[2:7]{.aside}

[τι]{.greek-omitted} [ουτος]{.greek-omitted} [ουτως]{.greek-omitted} [λαλει]{.greek-omitted} [βλασφημιας]{.greek-omitted} [τις]{.greek-omitted} [δυναται]{.greek-omitted} [αφιεναι]{.greek-omitted} [αμαρτιας]{.greek-omitted} [μαρτιας]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[2:7 | instance no. 2]{.aside}

και ευθεως επιγνους [το]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τω]{.greek-omitted} [πνευματι]{.greek-abbr} αυτου οτι [ουτως]{.greek-omitted} [ουτος]{.greek-added} αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} [ειπειν]{.greek-omitted} [ειπιν]{.greek-added} τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεωντε]{.greek-added} σου αι αμαρτιαι [η]{.greek-omitted} [ειπειν]{.greek-omitted} [ει]{.greek-added} [ηπειν]{.greek-added} εγειραι και αρον [σου]{.greek-omitted} τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} και [περιπατει]{.greek-omitted} [περιπατη]{.greek-added}[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ηδητε]{.greek-added} οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι επι της γης αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

[σοι]{.greek-omitted} [συ]{.greek-added} λεγω εγειραι και αρον τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} σου και [υπαγε]{.greek-omitted} [υπαγαι]{.greek-added} εις τον οικον σου[2:11]{.aside}

και [ηγερθη]{.greek-omitted} [ηγερθει]{.greek-added} ευθεως και αρας τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε [ουτως]{.greek-omitted} [ουτος]{.greek-added} [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added}[2:12]{.aside}

και εξηλθεν [παλιν]{.greek-omitted} [παλην]{.greek-added} παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και [παραγων]{.greek-omitted} [ειδεν]{.greek-omitted} [λευι]{.greek-omitted} [τον]{.greek-omitted} [του]{.greek-omitted} [αλφαιου]{.greek-omitted} [καθημενον]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [τελωνιον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [αναστας]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted}[2:14]{.aside}

[και]{.greek-omitted} παραγων [ειδεν]{.greek-omitted} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [δε]{.greek-added} [λευι]{.greek-omitted} [λευειν]{.greek-added} τον του αλφαιου [καθη]{.greek-added} καθημενον επι το [τελωνιον]{.greek-omitted} [τελωνειων]{.greek-added} και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[2:14 | instance no. 2]{.aside}

και εγενετο εν τω κατακεισθαι [αυτον]{.greek-omitted} εν [τη]{.greek-omitted} [τι]{.greek-added} οικια αυτου και πολλοι τελωναι και αμαρτωλοι [συνανεκειντο]{.greek-omitted} [συνανεκηντο]{.greek-added} [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γρ[α]{.unclear}μματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου [χρειαν]{.greek-omitted} [χρια[ν]{.unclear}]{.greek-added} εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ [ηλθον]{.greek-omitted} [ηλθω[ν]{.unclear}]{.greek-added} καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και [ησαν]{.greek-omitted} [εισαν]{.greek-added} οι μαθηται ιωαννου και οι [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [φαρισαιοι]{.greek-added} νηστευοντες και ερχονται και [λε]{.greek-added} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευουσιν]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [σοι]{.greek-omitted} [μαθηται]{.greek-omitted} [ου]{.greek-omitted} [νηστευουσιν]{.greek-omitted}[2:18]{.aside}

[και]{.greek-omitted} [ησαν]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευοντες]{.greek-omitted} [και]{.greek-omitted} [ερχονται]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [γουσιν]{.greek-added} αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου νηστευουσιν[2:18 | instance no. 2]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο ν[υ]{.greek-supplied}μφιος μετ αυτων εστιν νηστευειν οσον χρονον μεθ εαυτων εχουσιν τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευουσιν]{.greek-added} εν [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [εκεινη]{.greek-added} [τι]{.greek-added} [ημεραις]{.greek-omitted} [ημερα]{.greek-added}[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω [ει]{.greek-omitted} [η]{.greek-added} δε μη [αιρει]{.greek-omitted} [ερει]{.greek-added} το πληρωμα [απ]{.greek-added} αυτου το καινον του παλαιου και [χειρον]{.greek-omitted} [χηρον]{.greek-added} [σχισμα]{.greek-omitted} [σχησμα]{.greek-added} γινεται[2:21]{.aside}

και ουδεις [βαλλει]{.greek-omitted} [βαλει]{.greek-added} οινον [νεον]{.greek-omitted} [ναιον]{.greek-added} εις ασκους παλαιους ει δε μη [ρησσει]{.greek-omitted} [ρησει]{.greek-added} [ο]{.greek-omitted} [οινος]{.greek-omitted} ο νεος [οινος]{.greek-added} τους ασκους και ο οινος εκχειται και [οι]{.unclear} ασκοι απολουνται αλλα οινον νεον εις ασκους καινους βλητεον[2:22]{.aside}

και [εγενετο]{.greek-omitted} [παραπορευεσθαι]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [δια]{.greek-omitted} [των]{.greek-omitted} [σποριμων]{.greek-omitted} [και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [οδον]{.greek-omitted} [ποιειν]{.greek-omitted} [τιλλοντες]{.greek-omitted} [τους]{.greek-omitted} [σταχυας]{.greek-omitted}[2:23]{.aside}

[και]{.greek-omitted} εγενετο παραπορευεσθαι αυτον [εν]{.greek-omitted} τοις σαββασιν δια [των]{.greek-omitted} [τον]{.greek-added} σποριμων και ηρξαντο οι μαθηται αυτου οδον [ποιειν]{.greek-omitted} [ποιην]{.greek-added} τιλλοντες τους [σταχυας]{.greek-omitted} [ταχυας]{.greek-added}[2:23 | instance no. 2]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ εξεστιν[2:24]{.aside}

και [αυτος]{.greek-omitted} ελεγεν αυτοις ουδεποτε ανεγνωτε τι εποιησεν [δαυιδ]{.greek-abbr} οτε [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εσχεν και επεινασεν [αυτος]{.greek-omitted} [αυτως]{.greek-added} και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ [του]{.greek-added} αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ εξεστιν φαγειν ει [μη]{.greek-omitted} [μι]{.greek-added} τοις ιερευσιν και εδωκεν και τοις συν αυτω ουσιν[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν [παλιν]{.greek-omitted} [παλην]{.greek-added} εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην [εχων]{.greek-omitted} [εχον]{.greek-added} την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις σαββασιν [θεραπευσει]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [κατηγορησωσιν]{.greek-omitted} [αυτου]{.greek-omitted}[3:2]{.aside}

[και]{.greek-omitted} [παρετηρουν]{.greek-omitted} [αυτον]{.greek-omitted} [ει]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [θεραπευσει]{.greek-omitted} [θεραπευει]{.greek-added} αυτον ινα [κατηγορησωσιν]{.greek-omitted} [κατηγορισωσιν]{.greek-added} αυτου[3:2 | instance no. 2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω εξηραμμενην εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις εξεστιν τοις σαββασιν [αγαθοποιησαι]{.greek-omitted} [αγαθων]{.greek-added} [ποιησαι]{.greek-added} η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα [σου]{.greek-omitted} και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθι]{.greek-added} [η]{.greek-omitted} [ει]{.greek-added} χειρ αυτου [υγιης]{.greek-omitted} [υγιεις]{.greek-added} ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι [ευθεως]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [ηρωδιανων]{.greek-omitted} συμβουλιον [εποιουν]{.greek-omitted} [εποιησαν]{.greek-added} κατ αυτου οπως αυτον απολεσωσιν[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [γνους]{.greek-added} [ανεχωρησεν]{.greek-omitted} [ανεχωρισεν]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και [πολυ]{.greek-omitted} [πολλοι]{.greek-added} πληθος απο της [γαλιλαιας]{.greek-omitted} [γαληλαιας]{.greek-added} ηκολουθησαν αυτω και απο της [ιουδαιας]{.greek-omitted} [ιουδαι]{.greek-added}[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου [και]{.greek-omitted} [οι]{.greek-omitted} [περι]{.greek-omitted} [τυρον]{.greek-omitted} [και]{.greek-omitted} [σιδωνα]{.greek-omitted} [πληθος]{.greek-omitted} [πολυ]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οσα]{.greek-omitted} [εποιει]{.greek-omitted} [ηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[3:8]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} [και]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} και οι περι τυρον και [σιδωνα]{.greek-omitted} [σιδονα]{.greek-added} πληθος [πολυ]{.greek-omitted} [πολλοι]{.greek-added} ακουσαντες οσα εποιει ηλθον προς αυτον[3:8 | instance no. 2]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερι]{.greek-added} αυτω δια τον οχλον ινα μη [θλιβωσιν]{.greek-omitted} [θλιβοσιν]{.greek-added} αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} οσοι ειχον [μαστιγας]{.greek-omitted} [μαστιγιας]{.greek-added}[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} [τα]{.greek-omitted} ακαθαρτα οταν αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτ[οις]{.greek-supplied} ινα μη [αυτον]{.greek-added} φ[α]{.greek-supplied}νερον [αυτον]{.greek-omitted} ποιησωσ[ιν]{.greek-supplied}[3:12]{.aside}

και [αναβαινει]{.greek-omitted} [αναβενει]{.greek-added} εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και επ[ο]{.unclear}[ι]{.greek-supplied}ησεν δωδεκα ινα ωσιν μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτου[ς]{.unclear} κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τ[ας]{.greek-supplied} [νοσους]{.greek-omitted} [νοσσους]{.greek-added} και εκβαλλειν τα δαιμονια[3:15]{.aside}

και επεθηκεν τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον [τον]{.greek-omitted} [του]{.greek-omitted} [ζεβεδαιου]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [τον]{.greek-omitted} [αδελφον]{.greek-omitted} [του]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [επεθηκεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ονοματα]{.greek-omitted} [βοανεργες]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [υιοι]{.greek-omitted} [βροντης]{.greek-omitted}[3:17]{.aside}

[και]{.greek-omitted} [ιακωβον]{.greek-omitted} τον του ζεβεδα[ι]{.greek-supplied}ου και ιωαννην τον αδελφον [αυτου]{.greek-added} του ιακωβου και επεθηκεν αυτοις ονοματα [βοανεργες]{.greek-omitted} [βοανηργες]{.greek-added} ο εστιν υιοι βροντης[3:17 | instance no. 2]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον [κανανιτην]{.greek-omitted} [κανανητη[ν]{.unclear}]{.greek-added}[3:18]{.aside}

και ιουδαν ισκαριωτην [ος]{.greek-omitted} [ως]{.greek-added} και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερ[χ]{.unclear}ονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται [παλιν]{.greek-omitted} [παλην]{.greek-added} [ο]{.greek-added} οχλος ωστε μη δυνασθαι αυτους μητε αρτον [φαγειν]{.greek-omitted} [φαγην]{.greek-added}[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι [εξεστη]{.greek-omitted} [εξεστι]{.greek-added}[3:21]{.aside}

και οι γραμματεις οι απο [ιεροσολυμων]{.greek-omitted} [ιεροσωλυμων]{.greek-added} καταβαντες [ε]{.unclear}λεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δα[ι]{.unclear}μονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγε[ν]{.unclear} αυτοις πως δυναται σαταν[α]{.unclear}[ς]{.greek-supplied} σαταναν [εκβαλλειν]{.greek-omitted} [εκβα]{.greek-added}[3:23]{.aside}

[λλειν]{.greek-added} [και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [πως]{.greek-omitted} [δυναται]{.greek-omitted} [σατανας]{.greek-omitted} [σαταναν]{.greek-omitted} [εκβαλλειν]{.greek-omitted}[3:23 | instance no. 2]{.aside}

και εαν βασιλεια εφ εαυτη[ν]{.unclear} [μ]{.unclear}ερισθ[η]{.unclear} ου [δ]{.unclear}υναται [σταθηναι]{.greek-omitted} [σταθειναι]{.greek-added} η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην [μερισθη]{.greek-omitted} [μερησθη]{.greek-added} ου δυναται σταθηναι [η]{.unclear} οικια εκεινη[3:25]{.aside}

και [ει]{.greek-omitted} [η]{.greek-added} ο σατανας ανεστη εφ εαυτον και [μεμερισται]{.greek-omitted} [μεμερισθαι]{.greek-added} ου δυναται [σταθηναι]{.greek-omitted} [σταθειναι]{.greek-added} αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου [εισελθων]{.greek-omitted} [εισελθον]{.greek-added} εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτ[ο]{.unclear}υ [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λ[ε]{.unclear}γω υμιν οτι παντ[α]{.unclear} [α]{.unclear}φεθ[ησεται]{.unclear} τ[α]{.unclear} αμαρτηματα το[ις]{.unclear} υιοις των [ανθρωπων]{.greek-abbr} και βλασ[φη]{.unclear}μι[αι]{.unclear} [οσας]{.greek-omitted} [οσα]{.greek-added} αν [βλασφημησωσιν]{.greek-omitted} [βλασφημισωσιν]{.greek-added}[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [β[λ]{.unclear}ασφημησει]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες [α]{.greek-added} [απεστειλαν]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [φωνουντες]{.greek-omitted} [αυτον]{.greek-omitted}[3:31]{.aside}

[ερχονται]{.greek-omitted} [ουν]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [μητηρ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εξω]{.greek-omitted} [εστωτες]{.greek-omitted} [απεστειλαν]{.greek-omitted} [πεστειλαν]{.greek-added} προς αυτον [φωνουντες]{.greek-omitted} [αυτον]{.greek-omitted}[3:31 | instance no. 2]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} [σου]{.greek-omitted} και οι [αδελφοι]{.greek-omitted} [αδελφοις]{.greek-added} [σου]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} σου εξω ζητουσιν σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω [τους]{.greek-omitted} [τοις]{.greek-added} περι αυτον [καθημενους]{.greek-omitted} [καθημενοις]{.greek-added} λεγει [ιδε]{.greek-omitted} [ηδε]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη [μου]{.greek-omitted} και [μητηρ]{.greek-abbr} εστιν[3:35]{.aside}

### Chapter 4

και [παλιν]{.greek-omitted} [παλην]{.greek-added} ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος [πολυς]{.greek-omitted} [πολοις]{.greek-added} ωστε αυτον εμβαντα εις [το]{.greek-omitted} πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} εν τη διδαχη αυτου[4:2]{.aside}

[ακουετε]{.greek-omitted} [ακουεται]{.greek-added} ιδου εξηλθεν ο σπειρω[ν]{.unclear} [του]{.greek-omitted} σπειραι[4:3]{.aside}

και εγενετο εν [τω]{.greek-omitted} [το]{.greek-added} [σπειρειν]{.greek-omitted} [σπειριν]{.greek-added} ο μεν επεσεν παρα την οδον και ηλθεν τα [πετεινα]{.greek-omitted} [πετινα]{.greek-added} και κατεφαγεν [αυτο]{.greek-omitted}[4:4]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σπειρειν]{.greek-omitted} [ο]{.greek-omitted} [μεν]{.greek-omitted} [επεσεν]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [και]{.greek-omitted} [ηλθεν]{.greek-omitted} [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [και]{.greek-omitted} [κατεφαγεν]{.greek-omitted} [αυτο]{.greek-omitted} [αυτω]{.greek-added}[4:4 | instance no. 2]{.aside}

[και]{.greek-added} αλλο [δε]{.greek-omitted} επεσεν επι το πετρωδες [οπου]{.greek-omitted} [ουπου]{.greek-added} ουκ [ειχεν]{.greek-omitted} [εχει]{.greek-added} γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος [εκαυματισθη]{.greek-omitted} [εκαυματησθη]{.greek-added} και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} και καρπον ουκ εδωκεν[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον [αναβαινοντα]{.greek-omitted} [αναβενοντα]{.greek-added} και αυξανοντα και εφερεν εν τριακοντα και εν εξηκοντα και εν εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα [ταυτην]{.greek-added} την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν [δεδοται]{.greek-omitted} [δεδωται]{.greek-added} [γνωναι]{.greek-omitted} το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα γινεται[4:11]{.aside}

ινα βλεποντες βλεπωσιν και [μη]{.greek-omitted} [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [μηποτε]{.greek-omitted} [επιστρεψωσιν]{.greek-omitted} [και]{.greek-omitted} [αφεθη]{.greek-omitted} [αυτοις]{.greek-omitted} [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted}[4:12]{.aside}

[ινα]{.greek-omitted} [βλεποντες]{.greek-omitted} [βλεπωσιν]{.greek-omitted} [και]{.greek-omitted} μη ιδωσιν και ακουοντες ακουωσιν και μη συνιωσιν μηποτε επιστρεψωσιν και αφεθη αυτοις τα [αμαρτηματα]{.greek-omitted} [αμαρτιματα]{.greek-added}[4:12 | instance no. 2]{.aside}

και λεγει αυτοις ουκ [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} την παραβολην [τ]{.unclear}αυτην και πως [πα]{.unclear}σας τα[ς]{.unclear} παρ[αβολα]{.unclear}ς γ[νω]{.unclear}σ[εσθε]{.unclear}[4:13]{.aside}

ο [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} τον λογον [σ]{.unclear}πειρει[4:14]{.aside}

ουτοι δε [ε]{.unclear}ισ[ι]{.unclear}ν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και [αιρει]{.greek-omitted} [ερει]{.greek-added} τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα [πετρωδη]{.greek-omitted} [πετρωδις]{.greek-added} σπειρομενοι οι οταν ακουσωσιν τον λογον ευθεως μετα χαρ[ας]{.unclear} λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [ε]{.unclear}χουσιν ριζαν εν εαυτοις αλλα προσκ[αι]{.unclear}ροι εισιν [ειτα]{.greek-omitted} [ητα]{.greek-added} γενομενης θλιψεω[ς]{.unclear} η [διωγμου]{.greek-omitted} [διογμου]{.greek-added} δια τον λογον ευθεως [σκανδαλιζονται]{.greek-omitted} [σκανδαληζονται]{.greek-added}[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και [αι]{.greek-omitted} [ε]{.greek-added} μεριμναι του [αιωνος]{.greek-omitted} [τουτου]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [απατη]{.greek-omitted} [του]{.greek-omitted} [πλουτου]{.greek-omitted} [και]{.greek-omitted} αι [περι]{.greek-omitted} [τα]{.greek-omitted} [λοιπα]{.greek-omitted} [επιθυμιαι]{.greek-omitted} [εισπορευομεναι]{.greek-omitted} [συμπνιγουσιν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [ακαρπος]{.greek-omitted} [γινεται]{.greek-omitted}[4:19]{.aside}

[και]{.greek-omitted} [αι]{.greek-omitted} [μεριμναι]{.greek-omitted} [του]{.greek-omitted} [αιωνος]{.greek-omitted} [ωνος]{.greek-added} τουτου και η απατη του πλουτου και [αι]{.greek-omitted} [ε]{.greek-added} περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συνπνιγουσιν]{.greek-added} τον λογον και ακαρπος γινεται[4:19 | instance no. 2]{.aside}

και ουτοι εισιν οι επι την γην την καλην [σ]{.unclear}παρ[ε]{.unclear}ντες οιτιν[ε]{.unclear}ς ακουουσιν τ[ον]{.unclear} λογον και παραδεχονται και καρποφορουσιν εν τ[ρ]{.unclear}[ι]{.greek-supplied}ακοντα και εν εξηκοντα και εν εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ εστιν [τι]{.greek-omitted} κρυπτον ο εαν [μ]{.unclear}η [φανερωθη]{.greek-omitted} [φανεροθη]{.greek-added} ουδε εγενετο αποκρυφον [α]{.unclear}λλ ινα ει[ς]{.unclear} φανερον [ε]{.unclear}λθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} τι [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} εν ω μετρω [μετρειτε]{.greek-omitted} [μετριται]{.greek-added} [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} υμιν και προστεθ[η]{.unclear}σεται υμιν τοις ακου[ουσιν]{.unclear}[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [εχη]{.greek-omitted} [εχει]{.greek-added} [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} αυτω και ος ουκ εχει και ο [ε]{.greek-added} [εχει]{.greek-omitted} [αρθησεται]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted}[4:25]{.aside}

[ος]{.greek-omitted} [γαρ]{.greek-omitted} [αν]{.greek-omitted} [εχη]{.greek-omitted} [δοθησεται]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ος]{.greek-omitted} [ουκ]{.greek-omitted} [εχει]{.greek-omitted} [χει]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [εχει]{.greek-omitted} αρθησεται απ αυτου[4:25 | instance no. 2]{.aside}

και ελεγεν [ουτως]{.greek-omitted} [ουτος]{.greek-added} εστιν η βασιλεια του [θεου]{.greek-abbr} [ως]{.greek-omitted} [ος]{.greek-added} εαν [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [βαλει]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και [καθευδη]{.greek-omitted} [καθευδει]{.greek-added} και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος βλαστανη και [μηκυνηται]{.greek-omitted} [μηκυνιται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον [ειτα]{.greek-omitted} [ητα]{.greek-added} σταχυν [ειτα]{.greek-omitted} [πληρη]{.greek-omitted} [ητα]{.greek-added} [πληρις]{.greek-added} σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως [αποστελλει]{.greek-omitted} [αποστελει]{.greek-added} το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσω]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως κοκκον σιναπεως [ος]{.greek-omitted} [ο]{.greek-added} οταν [σπαρη]{.greek-omitted} [σπειρει]{.greek-added} επι της γης [μικροτερος]{.greek-omitted} [μηκροτερος]{.greek-added} [εστιν]{.greek-added} παντων των σπερματων [εστιν]{.greek-omitted} των επι της γης[4:31]{.aside}

και οταν σπαρη [αναβαινει]{.greek-omitted} [αναβενει]{.greek-added} και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [κατασκηνουν]{.greek-omitted}[4:32]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [σπαρη]{.greek-omitted} [αναβαινει]{.greek-omitted} [και]{.greek-omitted} [γινεται]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} [λαχανων]{.greek-omitted} [μειζων]{.greek-omitted} [και]{.greek-omitted} [ποιει]{.greek-omitted} [κλαδους]{.greek-omitted} [μεγαλους]{.greek-omitted} [ωστε]{.greek-omitted} [δυνασθαι]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [σκιαν]{.greek-omitted} [αυτου]{.greek-omitted} τα πετεινα του [ουρανου]{.greek-abbr} [κατασκηνουν]{.greek-omitted} [κατασκινουν]{.greek-added}[4:32 | instance no. 2]{.aside}

και τοιαυταις παραβολαις πολλαις [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον [καθως]{.greek-omitted} [καθος]{.greek-added} [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις κατ ιδιαν δε τοις μαθηταις αυτου επελυεν παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται λαιλαψ ανεμου μεγαλη τα δε [κυματα]{.greek-omitted} [κοιματα]{.greek-added} [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε [αυτο]{.greek-omitted} [αυτω]{.greek-added} [ηδη]{.greek-omitted} [ηδι]{.greek-added} γεμιζεσθαι[4:37]{.aside}

και ην [αυτος]{.greek-omitted} [αυτως]{.greek-added} επι τη πρυμνη επι το προσκεφαλαιον [καθευδων]{.greek-omitted} [καθευδον]{.greek-added} και διεγειρουσιν αυτον και λεγουσιν αυτω [διδασκαλε]{.greek-omitted} [διδασκαλαι]{.greek-added} ου μελει σοι οτι [απολλυμεθα]{.greek-omitted} [απολλοιμεθα]{.greek-added}[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} τω ανεμω και ειπεν τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [πεφημωσο]{.greek-added} και εκοπασεν ο [ανεμος]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [γαληνη]{.greek-omitted} [μεγαλη]{.greek-omitted}[4:39]{.aside}

[και]{.greek-omitted} [διεγερθεις]{.greek-omitted} [επετιμησεν]{.greek-omitted} [τω]{.greek-omitted} [ανεμω]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [σιωπα]{.greek-omitted} [πεφιμωσο]{.greek-omitted} [και]{.greek-omitted} [εκοπασεν]{.greek-omitted} [ο]{.greek-omitted} ανεμος και εγενετο γαληνη μεγαλη[4:39 | instance no. 2]{.aside}

και ειπεν αυτοις τι [δειλοι]{.greek-omitted} [διλοι]{.greek-added} εστε [ουτως]{.greek-omitted} [ουτος]{.greek-added} πως ουκ εχετε [πιστιν]{.greek-omitted} [πιστην]{.greek-added}[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γεργεσινων]{.greek-added}[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως απηντησεν αυτω εκ των [μνημειων]{.greek-omitted} [μνημηων]{.greek-added} [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την [κατοικησιν]{.greek-omitted} [κατυκησιν]{.greek-added} ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις εδυνατο αυτον δησαι[5:3]{.aside}

δια το αυτον [πολλακις]{.greek-omitted} [πολλακης]{.greek-added} πεδαις και αλυσεσιν δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [ισχυσεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} [δαμασαι]{.greek-omitted} [δαμασε]{.greek-added}[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημασιν]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και [κατακοπτων]{.greek-omitted} [εαυτον]{.greek-omitted} [λιθοις]{.greek-omitted}[5:5]{.aside}

[και]{.greek-omitted} [δια]{.greek-omitted} [παντος]{.greek-omitted} [νυκτος]{.greek-omitted} [και]{.greek-omitted} [ημερας]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ορεσιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [μνημασιν]{.greek-omitted} [ην]{.greek-omitted} [κραζων]{.greek-omitted} [και]{.greek-omitted} [κατακοπτων]{.greek-omitted} [κατακοπτον]{.greek-added} εαυτον λιθοις[5:5 | instance no. 2]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} εδραμεν και προσεκυνησεν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} [υιε]{.greek-abbr} του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με [βασανισης]{.greek-omitted} [βασανησις]{.greek-added}[5:7]{.aside}

ελεγεν γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και [επιροτα]{.greek-added} [επηρωτα]{.greek-omitted} [[επιρωτα]{.corr}]{.greek-added} αυτον τι [ονομα]{.greek-added} σοι [ονομα]{.greek-omitted} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλη]{.greek-added} αυτον πολλα ινα μη [αποστελλει]{.greek-added} αυτους [αποστειλη]{.greek-omitted} εξω της χωρας[5:10]{.aside}

ην δε εκει [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων μεγαλη [βοσκομενη]{.greek-omitted} [προς]{.greek-added} [τ[ο]{.unclear}]{.greek-added} [ορει]{.greek-added}[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} τα ακαθαρτα εισηλθον εις τους χοιρους και [ωρμησεν]{.greek-omitted} [ορμησεν]{.greek-added} η αγελη κατα του [κρημνου]{.greek-omitted} [κριμνου]{.greek-added} εις την θαλασσαν [ησαν]{.greek-omitted} [εισαν]{.greek-added} δε ως [δισχιλιοι]{.greek-omitted} [δισχηλιοι]{.greek-added} και [επνι]{.greek-added} [επνιγοντο]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted}[5:13]{.aside}

[γοντο]{.greek-added} [και]{.greek-omitted} [επετρεψεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εξελθοντα]{.greek-omitted} [τα]{.greek-omitted} [πνευματα]{.greek-omitted} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [εισηλθον]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [και]{.greek-omitted} [ωρμησεν]{.greek-omitted} [η]{.greek-omitted} [αγελη]{.greek-omitted} [κατα]{.greek-omitted} [του]{.greek-omitted} [κρημνου]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [ησαν]{.greek-omitted} [δε]{.greek-omitted} [ως]{.greek-omitted} [δισχιλιοι]{.greek-omitted} [και]{.greek-omitted} [επνιγοντο]{.greek-omitted} εν τη θαλασση[5:13 | instance no. 2]{.aside}

[και]{.greek-added} οι [δε]{.greek-omitted} βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απιγγηλαν]{.greek-added} εις την [πολιν]{.greek-omitted} [πολην]{.greek-added} και εις τους αγρους και [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} [ιδειν]{.greek-omitted} [ειδιν]{.greek-added} τι εστιν το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και θεωρουσιν τον δαιμονιζομενον καθημενον και [ιματισμενον]{.greek-omitted} [ιματησμενον]{.greek-added} και [σωφρονουντα]{.greek-omitted} [σοφρονουντα]{.greek-added} [τον]{.greek-omitted} [εσχηκοτα]{.greek-omitted} [εσχικοτα]{.greek-added} τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν [απο]{.greek-omitted} των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβενοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} μετ αυτου [ει]{.greek-added}[5:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς [του]{.greek-added} [τους]{.corr} σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} πεποιηκεν και ηλεησεν σε[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη δεκαπολει [οσα]{.greek-omitted} [εποιησεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [παντες]{.greek-omitted} [εθαυμαζον]{.greek-omitted}[5:20]{.aside}

[και]{.greek-omitted} [απηλθεν]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δεκαπολει]{.greek-omitted} οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20 | instance no. 2]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω [παλιν]{.greek-omitted} [παλην]{.greek-added} εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων [ονοματι]{.greek-omitted} [ονοματη]{.greek-added} ιαειρος και ιδων αυτον πιπτει [προς]{.corr} [εις]{.greek-added} τους ποδας αυτου[5:22]{.aside}

και [παρεκαλει]{.greek-omitted} [παρακαλει]{.greek-added} αυτον πολλα λεγων οτι το θυγατριον μου [εσχατως]{.greek-omitted} [εσχατος]{.greek-added} εχει [ινα]{.greek-omitted} [ιν]{.greek-added} ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} [αυτη]{.greek-omitted} [αυτω]{.greek-added} τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και απηλθεν μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν [ρυσι]{.greek-added} [ρυσει]{.corr} αιματος [ετη]{.greek-omitted} [ετι]{.greek-added} δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν [ωφεληθεισα]{.greek-omitted} [ωφελεθεισα]{.greek-added} αλλα μαλλον εις το [χειρον]{.greek-omitted} [χηρον]{.greek-added} ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν [το]{.greek-added} [τω]{.corr} οχλω [οπισθεν]{.greek-omitted} [οπησθεν]{.greek-added} ηψατο του ιματιου αυτου[5:27]{.aside}

[ελε]{.greek-added} [ελεγεν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [καν]{.greek-omitted} [των]{.greek-omitted} [ιματιων]{.greek-omitted} [αυτου]{.greek-omitted} [αψωμαι]{.greek-omitted} [σωθησομαι]{.greek-omitted}[5:28]{.aside}

[ελεγεν]{.greek-omitted} [γεν]{.greek-added} γαρ οτι καν [των]{.greek-omitted} [τω]{.greek-added} [ιματιων]{.greek-omitted} [ιματιω]{.greek-added} αυτου αψωμαι σωθησομαι[5:28 | instance no. 2]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της [μαστιγος]{.greek-omitted} [μαστιγγος]{.greek-added}[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνου[ς]{.unclear} εν [εαυτω]{.greek-omitted} [εαυτον]{.greek-added} την εξ αυτο[υ]{.unclear} [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} εξελθουσαν επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη [φοβηθεισα]{.greek-omitted} [φοβηθησα]{.greek-added} και τρεμουσα ειδυια ο γεγονεν επ αυτη ηλθεν και προσεπεσεν αυτω και ειπεν αυτω πασαν την [α]{.unclear}ληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου σεσωκεν σε υπαγε εις ειρηνην και [ισθι]{.greek-omitted} [εισθη]{.greek-added} υγιης απο της [μαστιγος]{.greek-omitted} [μαστιγγος]{.greek-added} σου[5:34]{.aside}

ετι αυτου λαλου[ν]{.unclear}τος ερχονται απο του [αρχησυ]{.greek-added} [αρχισυναγωγου]{.greek-omitted} [λεγοντες]{.greek-omitted} [οτι]{.greek-omitted} [η]{.greek-omitted} [θυγατηρ]{.greek-omitted} [σου]{.greek-omitted} [απεθανεν]{.greek-omitted} [τι]{.greek-omitted} [ετι]{.greek-omitted} [σκυλλεις]{.greek-omitted} [τον]{.greek-omitted} [διδασκαλον]{.greek-omitted}[5:35]{.aside}

[ναγωγου]{.greek-added} [ετι]{.greek-omitted} [αυτου]{.greek-omitted} [λαλουντος]{.greek-omitted} [ερχονται]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [αρχισυναγωγου]{.greek-omitted} λεγοντες οτι η θυγατηρ σου απεθανεν τι ετι [σκυλλεις]{.greek-omitted} [σκυλεις]{.greek-added} τον διδασκαλον[5:35 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} [ευθεως]{.greek-omitted} ακουσας τον λογον λαλουμενον λεγει τω [αρχισυναγωγω]{.greek-omitted} [αρχησυναγωγω]{.greek-added} μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω [συνακολουθησαι]{.greek-omitted} [ακολουθησαι]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} πετρον και ιακωβον και ιωαννην τον αδελφον [ιακωβου]{.greek-omitted} [αυτου]{.greek-added}[5:37]{.aside}

και ερχεται εις τον οικον του [αρχισυναγωγου]{.greek-omitted} [αρχησυναγωγου]{.greek-added} και θεωρει θορυβον κλαιοντας και [αλαλαζοντας]{.greek-omitted} [αλαζοντας]{.greek-added} πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και [κλαιετε]{.greek-omitted} [κλαιεται]{.greek-added} το παιδιον ουκ απεθανεν αλλα [καθευδει]{.greek-omitted} [καθευδη]{.greek-added}[5:39]{.aside}

και κατεγ[ε]{.unclear}λ[ων]{.unclear} αυτου ο δε εκβαλων παντας [παραλαμβανει]{.greek-omitted} [παραλαμβανη]{.greek-added} τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευ[ε]{.unclear}ται οπου ην το παιδιον αν[α]{.unclear}κε[ι]{.unclear}μενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου [και]{.greek-added} λεγει αυτη [ταλιθα]{.greek-omitted} [ταληθα]{.greek-added} [κουμι]{.greek-omitted} [κουμη]{.greek-added} ο εστιν [μεθερ]{.greek-added} [μεθερμηνευομενον]{.greek-omitted} [το]{.greek-omitted} [κορασιον]{.greek-omitted} [σοι]{.greek-omitted} [λεγω]{.greek-omitted} [εγειραι]{.greek-omitted}[5:41]{.aside}

[και]{.greek-omitted} [κρατησας]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [του]{.greek-omitted} [παιδιου]{.greek-omitted} [λεγει]{.greek-omitted} [αυτη]{.greek-omitted} [ταλιθα]{.greek-omitted} [κουμι]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [μεθερμηνευομενον]{.greek-omitted} [μηνευομενον]{.greek-added} το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41 | instance no. 2]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει [μεγαλη]{.greek-omitted} [μεγαλει]{.greek-added}[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και ειπεν δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την πατριδα αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτα και τις η σοφια η [δοθεισα]{.greek-omitted} [δοθησα]{.greek-added} αυτω και [δυναμεις]{.greek-omitted} [δυναμης]{.greek-added} τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο [του]{.greek-added} τεκτων ο [υιος]{.greek-abbr} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ [εισιν]{.greek-omitted} [ησιν]{.greek-added} αι [αδελφαι]{.greek-omitted} [αιδελφαι]{.greek-added} αυτου ωδε προς ημας και [εσκανδαλιζοντο]{.greek-omitted} [εσκανδαληζοντο]{.greek-added} εν αυτω[6:3]{.aside}

[[και]{.unclear}]{.greek-added} ελεγεν δε αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [προφητης]{.greek-omitted} [ατιμος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πατριδι]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [συγγενεσιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [αυτου]{.greek-omitted}[6:4]{.aside}

[ελεγεν]{.greek-omitted} [δε]{.greek-omitted} [αυτοις]{.greek-omitted} ο [ιησους]{.greek-abbr} οτι ουκ εστιν προφητης ατιμος ει [μη]{.greek-omitted} [μι]{.greek-added} εν [τη]{.greek-omitted} [τι]{.greek-added} πατριδι αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [σοιγγενευσιν]{.greek-added} και εν [τη]{.greek-omitted} [τι]{.greek-added} οικια αυτου[6:4 | instance no. 2]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} ποιησαι ει [μη]{.greek-omitted} [μι]{.greek-added} ολιγοις αρρωστοις επιθεις τας χειρας εθεραπευσεν[6:5]{.aside}

και εθαυμαζεν δια την απιστιαν αυτων και περιηγεν τας κωμας κυκλω διδασκων[6:6]{.aside}

και [προσκαλειται]{.greek-omitted} [προσκαληται]{.greek-added} τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παριγγηλεν]{.greek-added} αυτοις ινα μηδεν [αιρωσιν]{.greek-omitted} [αιρουσιν]{.greek-added} εις οδον ει [μη]{.greek-omitted} [μι]{.greek-added} ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσισθαι]{.greek-added} δυο [χιτωνας]{.greek-omitted} [χητωνας]{.greek-added}[6:9]{.aside}

και ελεγεν αυτοις οπου εαν [εισελθητε]{.greek-omitted} [εισελθηται]{.greek-added} εις οικιαν εκει μενετε εως αν [εξελθητε]{.greek-omitted} [εξελθηται]{.greek-added} εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε [ακου]{.greek-added} [ακουσωσιν]{.greek-omitted} [υμων]{.greek-omitted} [εκπορευομενοι]{.greek-omitted} [εκειθεν]{.greek-omitted} [εκτιναξατε]{.greek-omitted} [τον]{.greek-omitted} [χουν]{.greek-omitted} [τον]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [η]{.greek-omitted} [γομορροις]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [εκεινη]{.greek-omitted}[6:11]{.aside}

[σωσιν]{.greek-added} [και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [μη]{.greek-omitted} [δεξωνται]{.greek-omitted} [υμας]{.greek-omitted} [μηδε]{.greek-omitted} [ακουσωσιν]{.greek-omitted} υμων εκπορευομενοι εκειθεν [εκτιναξατε]{.greek-omitted} [εκτιναξαται]{.greek-added} τον χουν τον [υποκατω]{.greek-omitted} [υποκατο]{.greek-added} των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [εστε]{.greek-added} [σοδομων]{.greek-added} η γομορροις εν ημερα κρισεως η τη [πολει]{.greek-omitted} [πολη]{.greek-added} εκεινη[6:11 | instance no. 2]{.aside}

και εξελθοντες εκηρυσσον ινα μετανοησωσιν[6:12]{.aside}

και δαιμονια πολλα [εξεβαλλον]{.greek-omitted} [εξεβαλον]{.greek-added} και [ηλειφον]{.greek-omitted} [ηλεφον]{.greek-added} ελαιω πολλους αρρωστους κα[ι]{.unclear} εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακωην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο ενεργουσιν αι δυναμεις εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν [α]{.unclear}λλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} ιωαννην ουτος εστιν αυτος ηγερθη εκ νεκρω[ν]{.unclear}[6:16]{.aside}

[αυτος]{.greek-omitted} [αυτως]{.greek-added} γαρ ο ηρωδης αποστειλας εκρατησεν τον ιωαννην και [εδησεν]{.greek-omitted} [εδισεν]{.greek-added} αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο ιωαννης τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν [αποκτειναι]{.greek-added} αυτον [αποκτειναι]{.greek-omitted} και ουκ [ηδυνατο]{.greek-omitted} [ηδυνατω]{.greek-added}[6:19]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητο]{.greek-added} τον ιωαννην [ειδως]{.greek-omitted} [ιδως]{.greek-added} αυτον ανδρα δικαιον και αγιον και [συνετηρει]{.greek-omitted} [συνετειρη]{.greek-added} αυτον και ακουσας αυτου πολλα [εποιει]{.greek-omitted} [εποιη]{.greek-added} και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας [ευκαιρου]{.greek-omitted} [ευκερου]{.greek-added} οτε ηρωδης τοις γενεσιοις αυτου [δειπνον]{.greek-omitted} [διπνον]{.greek-added} εποιει τοις μεγιστασιν αυτου και τοις [χιλιαρχοις]{.greek-omitted} [χηλιαρχοις]{.greek-added} και τοις πρωτοις τ[ης]{.unclear} [γαλιλαιας]{.greek-omitted} [γαληλαιας]{.greek-added}[6:21]{.aside}

και [εισελθουσης]{.greek-omitted} [εισελθουσις]{.greek-added} της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης [και]{.greek-omitted} [αρεσασης]{.greek-omitted} [τω]{.greek-omitted} [ηρωδη]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [συνανακειμενοις]{.greek-omitted} [ειπεν]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [τω]{.greek-omitted} [κορασιω]{.greek-omitted} [αιτησον]{.greek-omitted} [με]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [θελης]{.greek-omitted} [και]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted}[6:22]{.aside}

[και]{.greek-omitted} [εισελθουσης]{.greek-omitted} [της]{.greek-omitted} [θυγατρος]{.greek-omitted} [αυτης]{.greek-omitted} [της]{.greek-omitted} [ηρωδιαδος]{.greek-omitted} [και]{.greek-omitted} [ορχησαμενης]{.greek-omitted} και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω [αιτησον]{.greek-omitted} [αιτισον]{.greek-added} με ο εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} και δωσω σοι[6:22 | instance no. 2]{.aside}

και [ωμοσεν]{.greek-omitted} [ομοσεν]{.greek-added} αυτη οτι ο εαν [με]{.greek-omitted} αιτησης δωσω σοι εως [ημισους]{.greek-omitted} [ειμισου]{.greek-added} της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη μητρι αυτης τι [αιτησομαι]{.greek-omitted} [αιτισωμαι]{.greek-added} [η]{.greek-omitted} [ει]{.greek-added} δε ειπεν την κεφαλην ιωαννου του [βαπτιστου]{.greek-omitted} [βαπτηστου]{.greek-added}[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα [ητησατο]{.greek-omitted} [ητισατω]{.greek-added} λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην ιωαννου του [βαπτιστου]{.greek-omitted} [βαπτηστου]{.greek-added}[6:25]{.aside}

και [περιλυπος]{.greek-omitted} [περιλοιπος]{.greek-added} γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς [σπεκουλατορα]{.greek-omitted} [σπεκουλατωρα]{.greek-added} επεταξεν [ενεχθηναι]{.greek-omitted} [ενεχθειναι]{.greek-added} την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [εινεγκεν]{.greek-added} την κεφαλην αυτου επι [πινακι]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτην]{.greek-omitted} [τω]{.greek-omitted} [κορασιω]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [κορασιον]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτην]{.greek-omitted} [τη]{.greek-omitted} [μητρι]{.greek-omitted} [αυτης]{.greek-omitted}[6:28]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} [και]{.greek-omitted} [ηνεγκεν]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} πινακι και εδωκεν αυτην τω κορασιω και [το]{.greek-omitted} [τω]{.greek-added} [κορασιον]{.greek-omitted} [κορασιω]{.greek-added} εδωκεν αυτην τη μητρι αυτης[6:28 | instance no. 2]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν [το]{.greek-omitted} [τω]{.greek-added} πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και [απηγγειλαν]{.greek-omitted} [απιγγειλαν]{.greek-added} αυτω παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις [δευτε]{.greek-omitted} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [δευται]{.greek-added} [αυτοι]{.greek-added} υμεις [αυτοι]{.greek-omitted} κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} [ολιγον]{.greek-omitted} [οληγον]{.greek-added} ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκερουν]{.greek-added}[6:31]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ιδεν]{.greek-added} πολυν οχλον και [εσπλαγχνισθη]{.greek-omitted} [ευσπλαχνισθη]{.greek-added} [επ]{.greek-omitted} [αυτοις]{.greek-omitted} [οτι]{.greek-omitted} [ησαν]{.greek-omitted} [ως]{.greek-omitted} [προβατα]{.greek-omitted} [μη]{.greek-omitted} [εχοντα]{.greek-omitted} [ποιμενα]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [διδασκειν]{.greek-omitted} [αυτους]{.greek-omitted} [πολλα]{.greek-omitted}[6:34]{.aside}

[και]{.greek-omitted} [εξελθων]{.greek-omitted} [ειδεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [πολυν]{.greek-omitted} [οχλον]{.greek-omitted} [και]{.greek-omitted} [εσπλαγχνισθη]{.greek-omitted} επ αυτοις οτι [ησαν]{.greek-omitted} [εισαν]{.greek-added} ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34 | instance no. 2]{.aside}

και [ηδη]{.greek-omitted} [ηδι]{.greek-added} ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται αυτου λεγουσιν οτι [ερημος]{.greek-omitted} [εριμος]{.greek-added} εστιν ο τοπος και [ηδη]{.greek-omitted} [ηδι]{.greek-added} ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [απελθοντες]{.greek-omitted} [αγορασωμεν]{.greek-omitted} [δηναριων]{.greek-omitted} [διακοσιων]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [δωμεν]{.greek-omitted} [αυτοις]{.greek-omitted} [φαγειν]{.greek-omitted}[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε [και]{.greek-omitted} ιδετε και [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακληναι]{.greek-added} παντας συμποσια συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα [πεντηκοντα]{.greek-omitted} [πεντικοντα]{.greek-added}[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις [τον]{.greek-omitted} [των]{.greek-added} [ουρανον]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [ευλογησεν]{.greek-omitted} [και]{.greek-omitted} [κατεκλασεν]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [παραθωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [εμερισεν]{.greek-omitted} [πασιν]{.greek-omitted}[6:41]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [αναβλεψας]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} ευλογησεν και κατεκλασεν τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας εμερισεν πασιν[6:41 | instance no. 2]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα [κοφινους]{.greek-omitted} [κωφινους]{.greek-added} πληρεις και απο των ιχθυων[6:43]{.aside}

και [ησαν]{.greek-omitted} [εισαν]{.greek-added} οι [φαγοντες]{.greek-omitted} [φαγωντες]{.greek-added} τους αρτους [πεντακισχιλιοι]{.greek-omitted} [πεντακησχηλιοι]{.greek-added} ανδρες[6:44]{.aside}

και ευθεως ηναγκασεν τους μαθητας αυτου [εμβηναι]{.greek-omitted} [εμβιναι]{.greek-added} εις το πλοιον και προαγειν [αυτον]{.greek-added} εις το περαν προς βηθσαιδαν εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος [προσευξασθαι]{.greek-omitted} [προσπροσευξασθαι]{.greek-added}[6:46]{.aside}

και οψιας γενομενης ην το πλοι[ον]{.unclear} [μεσον]{.greek-added} [εν]{.greek-omitted} [μεσω]{.greek-omitted} της θαλασσης και [αυτος]{.greek-omitted} [αυτως]{.greek-added} μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν [τω]{.greek-omitted} [το]{.greek-added} ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην [της]{.greek-omitted} [νυκτος]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [περιπατων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

[και]{.greek-omitted} [ειδεν]{.greek-omitted} [αυτους]{.greek-omitted} [βασανιζομενους]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ελαυνειν]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [εναντιος]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [περι]{.greek-omitted} [τεταρτην]{.greek-omitted} [φυλακην]{.greek-omitted} της νυκτος ερχεται προς αυτους [περιπατων]{.greek-omitted} [περιπατον]{.greek-added} επι της θαλασσης και [ηθελεν]{.greek-omitted} [ειθελεν]{.greek-added} παρελθειν αυτους[6:48 | instance no. 2]{.aside}

οι δε ιδοντες [αυτον]{.greek-omitted} [αυαυτον]{.greek-added} περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον [ειδον]{.greek-omitted} [ιδον]{.greek-added} και [εταραχθησαν]{.greek-omitted} [εταραχθεισαν]{.greek-added} και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις [θαρσειτε]{.greek-omitted} [θαρσειται]{.greek-added} εγω ειμι μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισου]{.greek-added} εν εαυτοις [εξισταντο]{.greek-omitted} [εξησταντο]{.greek-added} και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [πεπωρωμενη]{.greek-omitted} [πεπορωμενη]{.greek-added}[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρεθ]{.greek-added} και [προσωρμισθησαν]{.greek-omitted} [προσορμησθησαν]{.greek-added}[6:53]{.aside}

και [εξελθοντων]{.greek-omitted} [εξελθωντων]{.greek-added} αυτων εκ του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην [ηρξαντο]{.greek-omitted} [ηρξαντω]{.greek-added} επι τοις [κραββατοις]{.greek-omitted} [κραβαττοις]{.greek-added} τους κακως εχοντας [περιφερειν]{.greek-omitted} [περιφε]{.greek-added} [οπου]{.greek-omitted} [ηκουον]{.greek-omitted} [οτι]{.greek-omitted} [εκει]{.greek-omitted} [εστιν]{.greek-omitted}[6:55]{.aside}

[ρειν]{.greek-added} [περιδραμοντες]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [περιχωρον]{.greek-omitted} [εκεινην]{.greek-omitted} [ηρξαντο]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [κραββατοις]{.greek-omitted} [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [περιφερειν]{.greek-omitted} οπου ηκουον οτι εκει εστιν[6:55 | instance no. 2]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις [ει]{.greek-added} [αγρους]{.greek-added} η [αγρους]{.greek-omitted} εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν [αυτον]{.greek-omitted} [αυτων]{.greek-added} ινα καν του κρασπεδου του ιματιου αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και [τινες]{.greek-omitted} [τιναις]{.greek-added} των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελθοντες απο [ιεροσολυμων]{.greek-omitted} [ιεροσωλυμων]{.greek-added}[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις χερσιν τουτ εστιν ανιπτοις [εσθιοντας]{.greek-omitted} [αισθιοντας]{.greek-added} αρτους [εμεμψαντο]{.greek-omitted}[7:2]{.aside}

οι γαρ φαρισαιοι και παντες [οι]{.greek-omitted} [υ]{.greek-added} ιουδαιοι εαν μη [πυγμη]{.greek-omitted} [πτυγμη]{.greek-added} [νιψωνται]{.greek-omitted} [νιψονται]{.greek-added} τας χειρας ουκ εσθιουσιν κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και [απορας]{.greek-added} [απο]{.corr} [αγορας]{.corr} εαν μη [βαπτισωνται]{.greek-omitted} [βαπτησονται]{.greek-added} ουκ εσθιουσιν και αλλα πολλα εστιν α παρελαβον κρατειν [βαπτισμους]{.greek-omitted} [βαπτησμους]{.greek-added} ποτηριων και ξεστων και χαλκιων και [κλινων]{.greek-omitted} [κληνων]{.greek-added}[7:4]{.aside}

[επειτα]{.greek-omitted} [επιτα]{.greek-added} [επε]{.greek-added} [επερωτωσιν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [σου]{.greek-omitted} [ου]{.greek-omitted} [περιπατουσιν]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} [παραδοσιν]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [αλλα]{.greek-omitted} [ανιπτοις]{.greek-omitted} [χερσιν]{.greek-omitted} [εσθιουσιν]{.greek-omitted} [τον]{.greek-omitted} [αρτον]{.greek-omitted}[7:5]{.aside}

[επειτα]{.greek-omitted} [επερωτωσιν]{.greek-omitted} [ρωτωσιν]{.greek-added} αυτον οι [φαρισαιοι]{.greek-omitted} [φαρησαιοι]{.greek-added} και οι γραμματεις δια τι οι [μαθηται]{.greek-omitted} [μαθηταις]{.greek-added} σου [ου]{.greek-omitted} [περιπατουσιν]{.greek-omitted} κατα την παραδοσιν των πρεσβυτερων αλλα ανιπτοις χερσιν εσθιουσιν τον αρτον[7:5 | instance no. 2]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι [καλως]{.greek-omitted} [καλος]{.greek-added} προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χηλεσιν]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε [σεβονται]{.greek-omitted} [σεβοντε]{.greek-added} με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} [κρατειτε]{.greek-omitted} [κρατηται]{.greek-added} την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα [ποιειτε]{.greek-omitted} [ποιηται]{.greek-added}[7:8]{.aside}

και ελεγεν αυτοις καλως [αθετειτε]{.greek-omitted} [αθετηται]{.greek-added} την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων [τηρησητε]{.greek-omitted} [κρατησιται]{.greek-added}[7:9]{.aside}

μωσης γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η [τη]{.greek-omitted} [τι]{.greek-added} [μητρι]{.greek-abbr} κορβαν ο εστιν δωρον ο εαν εξ εμου [ωφεληθης]{.greek-omitted} [ωφεληθεις]{.greek-added}[7:11]{.aside}

και ουκετι [αφιετε]{.greek-omitted} [αφητε]{.greek-added} αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η [τη]{.greek-omitted} [τι]{.greek-added} [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

[ακυρουντες]{.greek-omitted} [ακυρουνταις]{.greek-added} τον λογον του [θεου]{.greek-abbr} [τη]{.greek-omitted} [τι]{.greek-added} παραδοσει υμων [η]{.greek-omitted} [ην]{.greek-added} [παρεδωκατε]{.greek-omitted} [παρεδωκατει]{.greek-added} [κ]{.unclear}αι παρομοια [τοιαυτα]{.greek-omitted} [τυαυτα]{.greek-added} πολλα [ποιειτε]{.greek-omitted} [ποιηται]{.greek-added}[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον [ο]{.greek-omitted} [ου]{.greek-added} δυναται αυτον κοινωσαι [αλλα]{.greek-omitted} [αλλ]{.greek-added} τα εκπορευομενα απ αυτου εκεινα εστιν τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου [επηρωτων]{.greek-omitted} [επιρωτον]{.greek-added} αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις [ουτως]{.greek-omitted} [ουτος]{.greek-added} και υμεις ασυνετοι εστε ου [νοειτε]{.greek-omitted} [νοητε]{.greek-added} οτι παν [το]{.greek-omitted} [τω]{.greek-added} εξωθεν [εκ]{.greek-added} [εισπορευομενον]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted}[7:18]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ουτως]{.greek-omitted} [και]{.greek-omitted} [υμεις]{.greek-omitted} [ασυνετοι]{.greek-omitted} [εστε]{.greek-omitted} [ου]{.greek-omitted} [νοειτε]{.greek-omitted} [οτι]{.greek-omitted} [παν]{.greek-omitted} [το]{.greek-omitted} [εξωθεν]{.greek-omitted} [εισπορευομενον]{.greek-omitted} [πορευομενον]{.greek-added} εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18 | instance no. 2]{.aside}

οτι ουκ [εισπορευε]{.greek-added} [εισπορευεται]{.corr} αυτου εις την καρδιαν [αλλ]{.greek-omitted} [αλ]{.greek-added} εις την [κοιλιαν]{.greek-omitted} [κυλιαν]{.greek-added} και εις τον αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

ελεγεν δε οτι το [εκ]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται [μοιχειαι]{.greek-omitted} [μοιχιαι]{.greek-added} [πορνειαι]{.greek-omitted} [πορνιαι]{.greek-added} φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος [ασελγεια]{.greek-omitted} [ασελγια]{.greek-added} οφθαλμος πονηρος βλασφημια [υπερηφανια]{.greek-omitted} [υπεριφανεια]{.greek-added} αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

[και]{.greek-omitted} [εκειθεν]{.greek-omitted} [κακειθεν]{.greek-added} αναστας απηλθεν εις τα [μεθορια]{.greek-omitted} [ορια]{.greek-added} τυρου και σιδωνος και [εισελθον]{.greek-added} [εισελθων]{.corr} εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ειθελεν]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα [γαρ]{.greek-omitted} γυνη περι αυτου [ης]{.greek-omitted} [εις]{.greek-added} ειχεν το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον [ελθουσα]{.greek-omitted} [προσεπεσεν]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted}[7:25]{.aside}

[ακουσασα]{.greek-omitted} [γαρ]{.greek-omitted} [γυνη]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted} [ης]{.greek-omitted} [ειχεν]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [αυτης]{.greek-omitted} [πνευμα]{.greek-omitted} [ακαθαρτον]{.greek-omitted} ελθουσα προσεπεσεν προς τους ποδας αυτου[7:25 | instance no. 2]{.aside}

ην δε η γυνη [ελληνις]{.greek-omitted} [ελληνης]{.greek-added} [συραφοινικισσα]{.greek-omitted} [συρα]{.greek-added} [φυνισα]{.greek-added} τω [γενει]{.greek-omitted} [γενη]{.greek-added} και ηρωτα αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον [χορτασθηναι]{.greek-omitted} [χορτασθειναι]{.greek-added} τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω [ναι]{.greek-omitted} [κυριε]{.greek-abbr} και γαρ τα κυναρια [υποκατω]{.greek-omitted} [υποκατο]{.greek-added} της [τραπεζης]{.greek-omitted} [τραπεζεις]{.greek-added} [ε]{.unclear}σθιει απο των ψιχιων των [παιδιων]{.greek-omitted} [πιπτοντων]{.greek-added}[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης ευρεν το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της [κλινης]{.greek-omitted} [κληνης]{.greek-added}[7:30]{.aside}

και [παλιν]{.greek-omitted} [παλην]{.greek-added} [εξελθων]{.greek-omitted} [εξελθον]{.greek-added} εκ των [οριον]{.greek-added} [οριων]{.corr} τυρου και σιδωνος ηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} προς την θαλασσαν της [γαλιλαιας]{.greek-omitted} [ανα]{.greek-omitted} [μεσον]{.greek-omitted} [των]{.greek-omitted} [οριων]{.greek-omitted} [δεκαπολεως]{.greek-omitted}[7:31]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-omitted} [εξελθων]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [οριων]{.greek-omitted} [τυρου]{.greek-omitted} [και]{.greek-omitted} [σιδωνος]{.greek-omitted} [ηλθεν]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [γαληλαιας]{.greek-added} ανα μεσον των οριων δεκαπολεως[7:31 | instance no. 2]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσι[ν]{.unclear} αυτον ινα [επιθη]{.greek-omitted} [επιθει]{.greek-added} αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν εβαλεν τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλοσης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} εστεναξεν και λεγει αυτω εφφαθα ο εστιν [διανοιχθητι]{.greek-omitted} [διανυχθητη]{.greek-added}[7:34]{.aside}

και ευθεως [διηνοιχθησαν]{.greek-omitted} [διηνυχθησαν]{.greek-added} αυτου αι ακοαι και ελυθη ο δεσμος της [γλωσσης]{.greek-omitted} [γλοσσης]{.greek-added} αυτου και ελαλει [ορθος]{.greek-added} [ορθως]{.corr}[7:35]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστιλατω]{.greek-added} αυτοις ινα μηδενι ειπωσιν οσον δε [αυτος]{.greek-omitted} αυτοις [αυτως]{.greek-added} [διεστιλετω]{.greek-added} [διεστελλετο]{.greek-omitted} [[διεστιλλετω]{.corr}]{.greek-added} μαλλον [περισσοτερον]{.greek-omitted} [περισοτερον]{.greek-added} εκηρυσσον[7:36]{.aside}

και [υπερπερισσως]{.greek-omitted} [υπερπερισσος]{.greek-added} εξεπλησσοντο λεγοντες [καλως]{.greek-omitted} [καλος]{.greek-added} παντα π[ε]{.unclear}ποιηκεν και τους κωφους ποιει ακουειν και τους αλαλου[ς]{.unclear} λαλειν[7:37]{.aside}

### Chapter 8

εν [εκει]{.greek-added} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [παμπολλου]{.greek-omitted} [οχλου]{.greek-omitted} [οντος]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [εχοντων]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted}[8:1]{.aside}

[ναις]{.greek-added} [εν]{.greek-omitted} [εκειναις]{.greek-omitted} ταις ημεραις [παλην]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου οντος και μη εχοντων τι φαγωσιν προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας [αυτου]{.greek-omitted} λεγει αυτοις[8:1 | instance no. 2]{.aside}

[σπλαγχνιζομαι]{.greek-omitted} [σπλαχνιζομε]{.greek-added} επι τον οχλον οτι [ηδη]{.greek-omitted} [ηδι]{.greek-added} ημεραι [τρις]{.greek-added} [τρεις]{.corr} προσμενουσιν μοι και ουκ [ε]{.greek-supplied}χουσιν τι φαγωσιν[8:2]{.aside}

και εαν απολυσω αυτους [νηστεις]{.greek-omitted} [νηστης]{.greek-added} εις οικον αυτων εκλυθησονται εν [τη]{.greek-omitted} [τι]{.greek-added} οδω τινες γαρ αυτων [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} ηκουσιν[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε [χορτασαι]{.greek-omitted} [χορτασε]{.greek-added} αρτων επ ερημιας[8:4]{.aside}

και [επηρωτα]{.greek-omitted} [επιρωτα]{.greek-added} αυτους [ποσους]{.greek-omitted} [πωσους]{.greek-added} εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παριγγιλεν]{.greek-added} τω οχλω [αναπεσειν]{.greek-omitted} [αναπεσιν]{.greek-added} επι της γης και λαβων τους επτα αρτους ευχαριστησας εκλασεν και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παρατιθωσιν]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και [ελογισας]{.greek-added} [ευλογησας]{.greek-omitted} [[ευλογισας]{.corr}]{.greek-added} ειπεν [παραθειναι]{.greek-omitted} [και]{.greek-omitted} [αυτα]{.greek-omitted}[8:7]{.aside}

[και]{.greek-omitted} [ειχον]{.greek-omitted} [ιχθυδια]{.greek-omitted} [ολιγα]{.greek-omitted} [και]{.greek-omitted} [ευλογησας]{.greek-omitted} [ειπεν]{.greek-omitted} [παραθειναι]{.greek-omitted} [παρατιθεναι]{.greek-added} και αυτα[8:7 | instance no. 2]{.aside}

εφαγον δε και εχορτασθησαν και ηραν [περισσευματα]{.greek-omitted} [περισευματα]{.greek-added} κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακ[ισ]{.unclear}χιλιοι και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου ηλθεν [ειλθεν]{.greek-added} εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο [συζητειν]{.greek-omitted} [συνζητειν]{.greek-added} αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας [τω]{.greek-omitted} [το]{.greek-added} [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημει[ον]{.unclear} επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας [παλιν]{.greek-omitted} [παλην]{.greek-added} εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει [μη]{.greek-omitted} [μι]{.greek-added} ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} απο της ζυμης [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [και]{.greek-omitted} [της]{.greek-omitted} [ζυμης]{.greek-omitted} [ηρωδου]{.greek-omitted}[8:15]{.aside}

[και]{.greek-omitted} [διεστελλετο]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} [ορατε]{.greek-omitted} [βλεπετε]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ζυμης]{.greek-omitted} των φαρισαιων και της ζυμης ηρωδου[8:15 | instance no. 2]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω [νοειτε]{.greek-omitted} [νωηται]{.greek-added} ουδε συνιετε ετι [πεπωρωμενην]{.greek-omitted} [πεπορωμενην]{.greek-added} εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

[οτε]{.greek-omitted} [οτι]{.greek-added} τους πεντε αρτους εκλασα εις τους [πεντακισχιλιους]{.greek-omitted} [πεντακησχιλιους]{.greek-added} ποσους κοφινους [πληρεις]{.greek-omitted} [πληρις]{.greek-added} κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους [τετρακισχιλιους]{.greek-omitted} [τετρακησχιλιους]{.greek-added} ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως [ου]{.greek-omitted} [ουπω]{.greek-added} συνιετε[8:21]{.aside}

και [ερχεται]{.greek-omitted} [ερχοντε]{.greek-added} εις βηθσαιδαν και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου [αψηται]{.greek-omitted}[8:22]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [εις]{.greek-omitted} [βηθσαιδαν]{.greek-omitted} [και]{.greek-omitted} [φερουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [τυφλον]{.greek-omitted} [και]{.greek-omitted} [παρακαλουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [αυτου]{.greek-omitted} [αψηται]{.greek-omitted} [αψιται]{.greek-added}[8:22 | instance no. 2]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω [επηρωτα]{.greek-omitted} [επιρωτα]{.greek-added} αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας ελεγεν βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα [παλιν]{.greek-omitted} [παλην]{.greek-added} επεθηκεν τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψεν]{.greek-added} [τηλαυγως]{.greek-omitted} [τιλαυγος]{.greek-added} απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την [κωμην]{.greek-omitted} [κομην]{.greek-added} [εισελθης]{.greek-omitted} [εισελθει[ς]{.unclear}]{.greek-added} μηδε [ειπης]{.greek-omitted} [ειπεις]{.greek-added} τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω [επηρωτα]{.greek-omitted} [επιρωτα]{.greek-added} τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον [βαπτιστην]{.greek-omitted} [και]{.greek-omitted} [αλλοι]{.greek-omitted} [ηλιαν]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [ενα]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted}[8:28]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [απεκριθησαν]{.greek-omitted} [ιωαννην]{.greek-omitted} [τον]{.greek-omitted} [βαπτιστην]{.greek-omitted} [βαπτηστην]{.greek-added} και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28 | instance no. 2]{.aside}

και [αυτος]{.greek-omitted} [αυτως]{.greek-added} λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγουσιν]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και [αποδοκιμασθηναι]{.greek-omitted} [αποδοκημιθειναι]{.greek-added} απο των πρεσβυτερων και των αρχι[ε]{.unclear}ρεων και των γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και [παρησια]{.greek-added} [παρρησια]{.corr} τον λογον [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} και προσλαβομενος αυτον ο πετρος ηρξατο [επιτιμαν]{.greek-omitted} [επιτημαν]{.greek-added} αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος [τον]{.greek-omitted} [των]{.greek-added} οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [η]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελει οπισω [μου]{.greek-omitted} [ακολουθειν]{.greek-omitted} [απαρνησασθω]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [αρατω]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ακολουθειτω]{.greek-omitted} [μοι]{.greek-omitted}[8:34]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [συν]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [οστις]{.greek-omitted} [θελει]{.greek-omitted} [οπισω]{.greek-omitted} μου ακολουθειν απαρνησασθω εαυτον και [αρατω]{.greek-omitted} [αρατο]{.greek-added} τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητο]{.greek-added} μοι[8:34 | instance no. 2]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [θελη]{.greek-omitted} [θελει]{.greek-added} την ψυχην αυτου [σωσαι]{.greek-omitted} [σωσε]{.greek-added} απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ [ωφελησει]{.greek-omitted} [οφελησει]{.greek-added} [τον]{.greek-added} [ανθρωπον]{.greek-abbr} εαν [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} τον κοσμον ολον και [ζημιωθη]{.greek-omitted} [ζημηωθη]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι [δωσει]{.greek-omitted} [δωσε]{.greek-added} [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ εαν [επαισχυνθη]{.greek-omitted} [επεσχυνθη]{.greek-added} με και τους εμους λογους εν τη γενεα ταυτη τη [πονηρα]{.greek-added} [και]{.greek-added} [μοιχαλιδι]{.greek-omitted} [μυχαλιδι]{.greek-added} και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [επαισχυνθησεται]{.greek-omitted} [επεσχυνθησετε]{.greek-added} αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι εισιν τινες των ωδε [εστηκοτων]{.greek-omitted} [εστικοτων]{.greek-added} [οιτινες]{.greek-omitted} [οιτηνες]{.greek-added} ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν ιδωσιν την βασιλειαν του [θεου]{.greek-abbr} [εληλυθυιαν]{.greek-omitted} [εν]{.greek-omitted} [δυναμει]{.greek-omitted}[9:1]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [εισιν]{.greek-omitted} [τινες]{.greek-omitted} [των]{.greek-omitted} [ωδε]{.greek-omitted} [εστηκοτων]{.greek-omitted} [οιτινες]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [γευσωνται]{.greek-omitted} [θανατου]{.greek-omitted} [εως]{.greek-omitted} [αν]{.greek-omitted} [ιδωσιν]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εληλυθυιαν]{.greek-omitted} [εληλυθυια]{.greek-added} εν [δυναμει]{.greek-omitted} [δυναμη]{.greek-added}[9:1 | instance no. 2]{.aside}

και μεθ ημερας εξ [παραλαμβανει]{.greek-omitted} [παραλαμβανι]{.greek-added} ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και ιωαννην και αναφερει αυτους εις ορος [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο [στιλβοντα]{.greek-omitted} [στηλβοντα]{.greek-added} λευκα λιαν ως χιων οια γναφευς επι της γης ου δυναται λευκαναι[9:3]{.aside}

και [ωφθη]{.greek-omitted} [ωφθι]{.greek-added} αυτοις ηλιας συν μωση και [ησαν]{.greek-omitted} [εισαν]{.greek-added} [σλλαλουντες]{.greek-added} [συλλαλουντες]{.corr} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις [συ]{.greek-added} [σοι]{.greek-omitted} [μιαν]{.greek-omitted} [και]{.greek-omitted} [μωση]{.greek-omitted} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ [ηδει]{.greek-omitted} [ειδι]{.greek-added} τι λαλησει [ησαν]{.greek-omitted} [εισαν]{.greek-added} γαρ εκφοβοι[9:6]{.aside}

και εγενετο [νεφελη]{.greek-omitted} [νεφελει]{.greek-added} επισκιαζουσα αυτοις και ηλθεν φωνη εκ της [νεφελης]{.greek-omitted} [νεφελεις]{.greek-added} ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα [ειδον]{.greek-omitted} [ιδων]{.greek-added} αλλα τον [ιησουν]{.greek-abbr} [μονον]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted}[9:8]{.aside}

[και]{.greek-omitted} [εξαπινα]{.greek-omitted} [περιβλεψαμενοι]{.greek-omitted} [ουκετι]{.greek-omitted} [ουδενα]{.greek-omitted} [ειδον]{.greek-omitted} [αλλα]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} μονον μεθ εαυτων[9:8 | instance no. 2]{.aside}

[καταβαινοντων]{.greek-omitted} [καταβενοντων]{.greek-added} δε αυτων [α]{.unclear}πο του ορους [διεστειλατο]{.greek-omitted} [διεστιλατω]{.greek-added} αυτοις ινα [μηδενι]{.greek-omitted} [μηδενη]{.greek-added} [διηγησωνται]{.greek-omitted} [διηγισονται]{.greek-added} α [ειδον]{.greek-omitted} [ιδων]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον [εκρατησαν]{.greek-omitted} [εκρατεισαν]{.greek-added} [προς]{.greek-omitted} [παρ]{.greek-added} [εαυτους]{.greek-omitted} [εαυτο[ι]{.unclear}ς]{.greek-added} συζητουντες τι εστιν το εκ νεκρων αναστηναι[9:10]{.aside}

και [επηρωτων]{.greek-omitted} [επιρωτον]{.greek-added} αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν [δι]{.greek-added} [δει]{.corr} ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μ[εν]{.greek-supplied} ελθων πρωτον [αποκαθιστα]{.greek-omitted} [αποκαθησταν]{.greek-added} παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και [εξουδενωθη]{.greek-omitted} [εξουδενοθη]{.greek-added}[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας [ε]{.unclear}ληλυθεν και εποιησαν αυτω οσα ηθελησαν [καθως]{.greek-omitted} [καθος]{.greek-added} γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον πολυν περι αυτους και γραμματεις [συζητουντας]{.greek-omitted} [συνζητουντας]{.greek-added} α[υ]{.unclear}τοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον [εθα]{.greek-added} [εξεθαμβηθη]{.greek-omitted} [και]{.greek-omitted} [προστρεχοντες]{.greek-omitted} [ησπαζοντο]{.greek-omitted} [αυτον]{.greek-omitted}[9:15]{.aside}

[μβηθη]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [ιδων]{.greek-omitted} [αυτον]{.greek-omitted} [εξεθαμβηθη]{.greek-omitted} και προστρεχοντες [ησπαζοντο]{.greek-omitted} [εισπαζοντο]{.greek-added} αυτον[9:15 | instance no. 2]{.aside}

και [επηρωτησεν]{.greek-omitted} [επερωτισεν]{.greek-added} τους γραμματεις τι [συζητειτε]{.greek-omitted} [συνζητιται]{.greek-added} προς [αυτους]{.greek-omitted} [εαυτους]{.greek-added}[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε [ηνεγκα]{.greek-omitted} [εινεγκα]{.greek-added} τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου [αν]{.greek-omitted} [εαν]{.greek-added} αυτον καταλαβη [ρησσει]{.greek-omitted} [ρησει]{.greek-added} [αυτον]{.greek-omitted} [εαυτον]{.greek-added} και αφριζει και τριζ[ει]{.unclear} τους οδοντας αυτου και [ξηραινεται]{.greek-omitted} [ξηρενεται]{.greek-added} και ειπον τοις μαθηταις σου ινα [αυτο]{.greek-omitted} [αυτον]{.greek-added} εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [αυτω]{.greek-omitted} [αυτοις]{.greek-added} λεγει ω γενεα απιστος εως ποτε προς υμας [εσομαι]{.greek-omitted} [εσωμαι]{.greek-added} εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και [ιδων]{.greek-omitted} [ιδον]{.greek-added} αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επιρωτησεν]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} αυτω ο δε ειπεν παιδ[ι]{.unclear}οθεν[9:21]{.aside}

και [πολλακις]{.greek-omitted} [πολλακης]{.greek-added} αυτον [και]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [εβαλεν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [υδατα]{.greek-omitted} [ινα]{.greek-omitted} [απολεση]{.greek-omitted} [αυτον]{.greek-omitted} [αλλ]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} [δυνασαι]{.greek-omitted} [βοηθησον]{.greek-omitted} [ημιν]{.greek-omitted} [σπλαγχνισθεις]{.greek-omitted} [εφ]{.greek-omitted} [ημας]{.greek-omitted}[9:22]{.aside}

[και]{.greek-omitted} [πολλακις]{.greek-omitted} [αυτον]{.greek-omitted} και εις [το]{.greek-omitted} πυρ εβαλεν και εις υδατα ινα [απολεση]{.greek-omitted} [απολεσει]{.greek-added} αυτον αλλ ει τι [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} βοηθησον ημιν [σπλαγχνισθεις]{.greek-omitted} [σπλαχνισθεις]{.greek-added} εφ ημας[9:22 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτω [το]{.greek-omitted} ει [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} [πιστευσαι]{.greek-omitted} [πιστευσε]{.greek-added} παντα δυνατα [τω]{.greek-omitted} [το]{.greek-added} [πιστευοντι]{.greek-omitted} [πιστευοντη]{.greek-added}[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [βοηθη]{.greek-added} [κυριε]{.greek-omitted} [βοηθει]{.greek-omitted} μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετημισεν]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-omitted} [το]{.greek-omitted} αλαλον και [κωφον]{.greek-omitted} [κοφον]{.greek-added} εγω σοι επιτασσω εξελθε εξ αυτου και [μηκετι]{.greek-omitted} [μηκετη]{.greek-added} [εισελθης]{.greek-omitted} [εισελθεις]{.greek-added} εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον εξηλθεν και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος [ηγειρεν]{.greek-omitted} [ειγηρεν]{.greek-added} αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις [τον]{.greek-added} οικον οι μαθηται αυτου επηρωτων αυτον κατ [ιδιαν]{.greek-omitted} [ηδιαν]{.greek-added} οτι ημεις ουκ ηδυνηθημεν εκβαλειν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[9:28]{.aside}

και ειπεν αυτοις [οτι]{.greek-added} τουτο το γενος [εν]{.greek-omitted} ουδενι δυναται εξελθειν ει [μη]{.greek-omitted} [μι]{.greek-added} εν προσευχη και [νηστεια]{.greek-omitted} [νιστεια]{.greek-added}[9:29]{.aside}

και [εκειθεν]{.greek-omitted} [εκεθεν]{.greek-added} εξελθοντες παρεπορευοντο δια της [γαλιλαιας]{.greek-omitted} [γαληλαιας]{.greek-added} και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε [ηγνοουν]{.greek-omitted} [ηγνωουν]{.greek-added} το ρημα και εφοβουντο [επερωτισαι]{.greek-added} αυτον [επερωτησαι]{.greek-omitted}[9:32]{.aside}

και ηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν [τη]{.greek-omitted} [τι]{.greek-added} οδω προς εαυτους [διελογιζεσθε]{.greek-omitted} [διελογιζεσθαι]{.greek-added}[9:33]{.aside}

οι δε [εσιωπων]{.greek-omitted} [εσιοπων]{.greek-added} προς αλληλους γαρ [διελεχθησαν]{.greek-omitted} [διελεχθεισαν]{.greek-added} εν [τη]{.greek-omitted} [τι]{.greek-added} οδω τις μειζων[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} [εφωνησεν]{.greek-omitted} [εφωννησεν]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστε]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον [εστησεν]{.greek-omitted} [εστισεν]{.greek-added} [αυτο]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [αυτων]{.greek-omitted} [αυτω]{.greek-added} [και]{.greek-omitted} [εναγκαλισαμενος]{.greek-omitted} [αυτο]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted}[9:36]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [παιδιον]{.greek-omitted} [εστησεν]{.greek-omitted} [αυτο]{.greek-omitted} εν μεσω αυτων και [εναγκαλισαμενος]{.greek-omitted} [εναγκαλησαμενος]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added} ειπεν αυτοις[9:36 | instance no. 2]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι [τω]{.greek-omitted} [το]{.greek-added} [ονοματι]{.greek-omitted} [ονοματη]{.greek-added} μου εμε [δεχεται]{.greek-omitted} [δεχετε]{.greek-added} και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

[απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} [δε]{.greek-omitted} αυτω ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} τινα τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και [εκωλυσαμεν]{.greek-omitted} [εκολυσαμεν]{.greek-added} αυτον οτι ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη [κωλυετε]{.greek-omitted} [κολυεται]{.greek-added} αυτον ουδεις γαρ εστιν ος ποιησει [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} επι [τω]{.greek-omitted} [το]{.greek-added} [ονοματι]{.greek-omitted} [ονοματη]{.greek-added} μου και [δυνησεται]{.greek-omitted} [δυνησετε]{.greek-added} ταχυ [κακολογησαι]{.greek-omitted} [κακωλογησε]{.greek-added} με[9:39]{.aside}

ος γαρ ουκ εστιν καθ [υμων]{.greek-omitted} [ημων]{.greek-added} υπερ [υμων]{.greek-omitted} [ημων]{.greek-added} εστιν[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτησι]{.greek-added} υμας ποτηριον υδατος εν ονοματι [μου]{.greek-omitted} οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεσει]{.greek-added} τον [μισθον]{.greek-omitted} [μησθον]{.greek-added} αυτου[9:41]{.aside}

και ος εαν [σκανδαλιση]{.greek-omitted} [σκανδαλησει]{.greek-added} ενα των [μικρων]{.greek-omitted} [μηκρων]{.greek-added} των πιστευοντων εις εμε καλον [εσ]{.greek-added} [εστιν]{.greek-omitted} [αυτω]{.greek-omitted} [μαλλον]{.greek-omitted} [ει]{.greek-omitted} [περικειται]{.greek-omitted} [λιθος]{.greek-omitted} [μυλικος]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [τραχηλον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [βεβληται]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted}[9:42]{.aside}

[και]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [σκανδαλιση]{.greek-omitted} [ενα]{.greek-omitted} [των]{.greek-omitted} [μικρων]{.greek-omitted} [των]{.greek-omitted} [πιστευοντων]{.greek-omitted} [εις]{.greek-omitted} [εμε]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [τιν]{.greek-added} αυτω μαλλον ει [περικειται]{.greek-omitted} [περικητε]{.greek-added} λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42 | instance no. 2]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαληζει]{.greek-added} [σε]{.greek-omitted} [η]{.greek-omitted} [σαι]{.greek-added} [ει]{.greek-added} χειρ σου αποκοψον αυτην καλον σοι εστιν [κυλλον]{.greek-omitted} [κοιλλον]{.greek-added} εις την ζωην εισελθειν [η]{.greek-omitted} [ει]{.greek-added} τας δυο χειρας εχοντα απελθειν εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκολιξ]{.greek-added} [αυτον]{.greek-added} [αυτων]{.corr} ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον εστιν [σοι]{.greek-omitted} [σε]{.greek-added} εισελθειν [σε]{.greek-added} εις την ζωην χωλον [η]{.greek-omitted} [ει]{.greek-added} τους δυο ποδας εχοντα βληθηναι εις [την]{.greek-omitted} [γεενναν]{.greek-omitted} [εις]{.greek-omitted} το πυρ το [ασβεστον]{.greek-omitted} [ασβητον]{.greek-added}[9:45]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκολιξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτο[ν]{.unclear} καλον σοι εστιν μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα [βληθηναι]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γεενναν]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted}[9:47]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [ο]{.greek-omitted} [οφθαλμος]{.greek-omitted} [σου]{.greek-omitted} [σκανδαλιζη]{.greek-omitted} [σε]{.greek-omitted} [εκβαλε]{.greek-omitted} [αυτον]{.greek-omitted} [καλον]{.greek-omitted} [σοι]{.greek-omitted} [εστιν]{.greek-omitted} [μονοφθαλμον]{.greek-omitted} [εισελθειν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [η]{.greek-omitted} [δυο]{.greek-omitted} [οφθαλμους]{.greek-omitted} [εχοντα]{.greek-omitted} βληθηναι εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} του πυρος[9:47 | instance no. 2]{.aside}

οπου [ο]{.greek-omitted} [σκωληξ]{.greek-omitted} [ω]{.greek-added} [σκολιξ]{.greek-added} [αυτων]{.greek-omitted} [αυτον]{.greek-added} ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια [αλι]{.greek-omitted} αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι [αυτο]{.greek-omitted} [αυτω]{.greek-added} [αρτυσετε]{.greek-omitted} [αρτυσεται]{.greek-added} εχετε εν εαυτοις αλας και [ειρηνευετε]{.greek-omitted} [ειρηνευεται]{.greek-added} εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας [και]{.greek-added} [δια]{.greek-omitted} [του]{.greek-omitted} περαν του ιορδανου και συμπορευονται [παλιν]{.greek-omitted} [παλην]{.greek-added} οχλοι προς αυτον και ως [ειωθει]{.greek-omitted} [ειωθη]{.greek-added} [παλιν]{.greek-omitted} [παλην]{.greek-added} εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι [επηρωτησαν]{.greek-omitted} [επηρωτισαν]{.greek-added} αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν [ενετειλατο]{.greek-omitted} [ενετηλατο]{.greek-added} μωσης[10:3]{.aside}

οι δε ειπον μωσης επετρεψεν βιβλιον αποστασιου γραψαι και [απολυσαι]{.greek-omitted} [απολοισαι]{.greek-added}[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς [την]{.greek-omitted} [σκληροκαρδιαν]{.greek-omitted} [υμων]{.greek-omitted} [εγραψεν]{.greek-omitted} [υμιν]{.greek-omitted} [την]{.greek-omitted} [εντολην]{.greek-omitted} [ταυτην]{.greek-omitted}[10:5]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [προς]{.greek-omitted} την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5 | instance no. 2]{.aside}

απο δε αρχης [κτισεως]{.greek-omitted} [κτησεως]{.greek-added} αρσεν και [θηλυ]{.greek-omitted} [θηλοι]{.greek-added} εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταλιψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι εισιν δυο αλλα μια σαρξ[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν [τη]{.greek-omitted} [τι]{.greek-added} οικια [παλιν]{.greek-omitted} [παλην]{.greek-added} οι μαθηται αυτου περι του αυτου [επηρωτησαν]{.greek-omitted} [επιρωτησαν]{.greek-added} αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου και [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} αλλην μ[οι]{.unclear}χαται επ αυτην[10:11]{.aside}

και εαν γυνη [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα [αψηται]{.greek-omitted} [αψιται]{.greek-added} αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} ηγανακτησεν και ειπεν αυτοις [αφετε]{.greek-omitted} [τα]{.greek-omitted} [παιδια]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted} [μη]{.greek-omitted} [κωλυετε]{.greek-omitted} [αυτα]{.greek-omitted} [των]{.greek-omitted} [γαρ]{.greek-omitted} [τοιουτων]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[10:14]{.aside}

[αφεται]{.greek-added} [ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ηγανακτησεν]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αφετε]{.greek-omitted} τα παιδια ερχεσθαι προς με [και]{.greek-added} μη [κωλυετε]{.greek-omitted} [κολυεται]{.greek-added} αυτα [των]{.greek-omitted} [τον]{.greek-added} γαρ [τοιουτων]{.greek-omitted} [τοιουτον]{.greek-added} εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14 | instance no. 2]{.aside}

αμην λεγω υμιν ος εαν μη [δεξηται]{.greek-omitted} [δεξιται]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη [εισελθη]{.greek-omitted} [εισελθει]{.greek-added} εις αυτην[10:15]{.aside}

και [εναγκαλισαμενος]{.greek-omitted} [εναγκαλησαμενος]{.greek-added} αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ευλογι]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις και γονυπετησας αυτον [επηρωτα]{.greek-omitted} [επιρωτα]{.greek-added} αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας [εντολας]{.greek-omitted} [εντωλας]{.greek-added} οιδας μη [μοιχευσης]{.greek-omitted} [μοιχευσεις]{.greek-added} μη [φονευσης]{.greek-omitted} [φωνευσεις]{.greek-added} μη [κλεψης]{.greek-omitted} [κλεψεις]{.greek-added} μη [ψευδομαρτυρησης]{.greek-omitted} [ψευδομαρτυρησεις]{.greek-added} μη [αποστερησης]{.greek-omitted} [αποστερησεις]{.greek-added} τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-omitted} και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην ε[κ]{.unclear} [νεοτητος]{.greek-omitted} [νεοτιτ[ος]{.unclear}]{.greek-added} μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} [εμβλεψας]{.greek-omitted} [εν[β]{.unclear}λεψας]{.greek-added} [αυ]{.greek-added} [αυτω]{.greek-omitted} [ηγαπησεν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [υστερει]{.greek-omitted} [υπαγε]{.greek-omitted} [οσα]{.greek-omitted} [εχεις]{.greek-omitted} [πωλησον]{.greek-omitted} [και]{.greek-omitted} [δος]{.greek-omitted} [πτωχοις]{.greek-omitted} [και]{.greek-omitted} [εξεις]{.greek-omitted} [θησαυρον]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [δευρο]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [αρας]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted}[10:21]{.aside}

[τω]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [εμβλεψας]{.greek-omitted} [αυτω]{.greek-omitted} ηγαπησεν αυτον και ειπεν αυτω εν σοι υστερει υπαγε [οσα]{.greek-omitted} [ωσα]{.greek-added} εχεις πωλησον και δος [πτωχοις]{.greek-omitted} [πτοχοις]{.greek-added} και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι αρας τον [σταυρον]{.greek-abbr}[10:21 | instance no. 2]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως [δυσκολως]{.greek-omitted} [δυσκολος]{.greek-added} ο[ι]{.unclear} τα [χρηματα]{.greek-omitted} [χριματα]{.greek-added} εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} αποκριθεις λεγει αυτοις τεκνα πως δυσκολον εστιν τους [πεποιθοτας]{.greek-omitted} [πε[π]{.unclear}οιθωτας]{.greek-added} επι [χρημασιν]{.greek-omitted} [χρι[μα]{.unclear}σιν]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

[ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} εστιν καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος εισελθειν [η]{.greek-omitted} [ει]{.greek-added} πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε [περισσως]{.greek-omitted} [περισος]{.greek-added} εξεπλησσοντο λεγοντες προς εαυτους [και]{.greek-omitted} [τις]{.greek-omitted} [δυναται]{.greek-omitted} [σωθηναι]{.greek-omitted}[10:26]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [περισσως]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} και τις δυναται [σωθηναι]{.greek-omitted} [σωθειναι]{.greek-added}[10:26 | instance no. 2]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα εστιν παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω [τουτω]{.greek-omitted} [τουτο]{.greek-added} οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα [διωγμων]{.greek-omitted} [διογμων]{.greek-added} και εν τω αιωνι τω ερχομενω ζωην αιωνιον [κληρονομησει]{.greek-added}[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν [τη]{.greek-omitted} [τι]{.greek-added} οδω [αναβαινοντες]{.greek-omitted} [αναβενοντες]{.greek-added} εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και [εθαμβουντο]{.greek-omitted} [και]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} [παραλαβων]{.greek-omitted} [παλιν]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγειν]{.greek-omitted} [τα]{.greek-omitted} [μελλοντα]{.greek-omitted} [αυτω]{.greek-omitted} [συμβαινειν]{.greek-omitted}[10:32]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [αναβαινοντες]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [προαγων]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} εθαμβουντο και [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} παραλαβων [παλιν]{.greek-omitted} [παλην]{.greek-added} τους δωδεκα [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} αυτοις λεγειν τα μελλοντα αυτω [συμβαινειν]{.greek-omitted} [συμβενειν]{.greek-added}[10:32 | instance no. 2]{.aside}

οτι ιδου [αναβαινομεν]{.greek-omitted} [αναβενομεν]{.greek-added} εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις αρχιερευσιν και γραμματευσιν και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33]{.aside}

και [εμπαιξουσιν]{.greek-omitted} [εμπεξουσην]{.greek-added} αυτω και [μαστιγωσουσιν]{.greek-omitted} [μαστιγγωσουσιν]{.greek-added} αυτον και εμπτυσουσιν αυτω και αποκτενουσιν αυτον και [τη]{.greek-omitted} [τι]{.greek-added} τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης οι [υιοι]{.greek-omitted} [ιοι]{.greek-added} ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν [αιτησωμεν]{.greek-omitted} [σε]{.greek-added} [ετισομεν]{.greek-added} [ποιησης]{.greek-omitted} [ποιησεις]{.greek-added} ημιν[10:35]{.aside}

ο δε ειπεν [αυτοις]{.greek-omitted} τι [θελετε]{.greek-omitted} [θελεται]{.greek-added} [ποιησαι]{.greek-omitted} [ποιησε]{.greek-added} με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ [ευωνυμον]{.greek-added} [ευωνυμων]{.corr} σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη [δοξη]{.greek-omitted} [δοξι]{.greek-added} σου[10:37]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτοις ουκ [οι]{.greek-added} [οιδατε]{.greek-omitted} [τι]{.greek-omitted} [αιτεισθε]{.greek-omitted} [δυνασθε]{.greek-omitted} [πιειν]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [πινω]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [βαπτισμα]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [βαπτιζομαι]{.greek-omitted} [βαπτισθηναι]{.greek-omitted}[10:38]{.aside}

[δαται]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ουκ]{.greek-omitted} [οιδατε]{.greek-omitted} τι [αιτεισθε]{.greek-omitted} [αιτεισθαι]{.greek-added} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} πιειν το ποτηριον ο εγω πινω και το [βαπτισμα]{.greek-omitted} [βαπτησμα]{.greek-added} ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζομε]{.greek-added} [βαπτισθηναι]{.greek-omitted} [βαπτθηναι]{.greek-added}[10:38 | instance no. 2]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το [βαπτισμα]{.greek-omitted} [βαπτησμα]{.greek-added} ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισεσθαι]{.greek-added}[10:39]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησε]{.greek-added} εκ δεξιων μου και εξ [ευωνυμων]{.greek-omitted} [εωνυμων]{.greek-added} ουκ εστιν εμον δουναι αλλ οις [ητοιμασται]{.greek-omitted} [ητυμασθαι]{.greek-added}[10:40]{.aside}

και ακουσαντε[ς]{.unclear} οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος [αυτους]{.greek-omitted} λεγει αυτοις [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} οτι οι δοκουντες αρχειν των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριευσουσιν]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ [ουτως]{.greek-omitted} [ουτος]{.greek-added} δε [εσται]{.greek-omitted} [εστε]{.greek-added} εν υμιν αλλ ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} γενεσθαι μεγας εν υμιν [εσται]{.greek-omitted} [εστε]{.greek-added} υμων διακονος[10:43]{.aside}

και ος εαν [θελει]{.greek-added} [υ]{.greek-added} [θελη]{.greek-omitted} [υμων]{.greek-omitted} [γενεσθαι]{.greek-omitted} [πρωτος]{.greek-omitted} [εσται]{.greek-omitted} [παντων]{.greek-omitted} [δουλος]{.greek-omitted}[10:44]{.aside}

[και]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [θελη]{.greek-omitted} [υμων]{.greek-omitted} [μων]{.greek-added} γενεσθαι πρωτος [εσται]{.greek-omitted} [εστε]{.greek-added} παντων δουλος[10:44 | instance no. 2]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν [διακονηθηναι]{.greek-omitted} [διακονιθιναι]{.greek-added} αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και [ερχονται]{.greek-omitted} [ερχεται]{.greek-added} εις ιεριχω και εκπορευομενου αυτου απο ιε[ρι]{.greek-supplied}χω και των μαθητων αυτου και οχλου ικανου [υιος]{.greek-abbr} τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον [προσαιτων]{.greek-omitted} [προετον]{.greek-added} [[προσετον]{.corr}]{.greek-added}[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο [ναζωραιος]{.greek-omitted} [ναζοραιος]{.greek-added} εστιν ηρξατο κραζειν και λεγειν [ο]{.greek-omitted} [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν [υιε]{.greek-abbr} [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στ[ας]{.unclear} ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και φωνουσιν τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} [φωνει]{.greek-omitted} [σε]{.greek-omitted} [φωνη]{.greek-added} [σαι]{.greek-added}[10:49]{.aside}

ο δε [αποβαλων]{.greek-omitted} [αποβαλον]{.greek-added} το ιματιον αυτου αναστας ηλθεν προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις [ποιησω]{.greek-omitted} [ποιησο]{.greek-added} σοι ο δε [τυ]{.greek-added} [τυφλος]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ραββουνι]{.greek-omitted} [ινα]{.greek-omitted} [αναβλεψω]{.greek-omitted}[10:51]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τι]{.greek-omitted} [θελεις]{.greek-omitted} [ποιησω]{.greek-omitted} [σοι]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [τυφλος]{.greek-omitted} [φλος]{.greek-added} ειπεν αυτω [ραββουνι]{.greek-omitted} [ραββουνει]{.greek-added} ινα αναβλεψω[10:51 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου σεσωκεν σε και ευθεως ανεβλεψεν και [ηκολουθει]{.greek-omitted} [ηκολουθησεν]{.greek-added} τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις ιερουσαλημ εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την [κωμην]{.greek-omitted} [κομην]{.greek-added} την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε [πωλον]{.greek-omitted} [πολον]{.greek-added} δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [καικαθηκεν]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι [ποιειτε]{.greek-omitted} [ποιηται]{.greek-added} τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες [των]{.greek-omitted} [τον]{.greek-added} εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} [ελε]{.greek-added} [ελεγον]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [ποιειτε]{.greek-omitted} [λυοντες]{.greek-omitted} [τον]{.greek-omitted} [πωλον]{.greek-omitted}[11:5]{.aside}

[γον]{.greek-added} [και]{.greek-omitted} [τινες]{.greek-omitted} [των]{.greek-omitted} [εκει]{.greek-omitted} [εστηκοτων]{.greek-omitted} [ελεγον]{.greek-omitted} αυτοις τι [ποιειτε]{.greek-omitted} [ποιηται]{.greek-added} λυοντες τον πωλον[11:5 | instance no. 2]{.aside}

οι δε ειπον αυτοις [καθως]{.greek-omitted} [καθος]{.greek-added} [ενετειλατο]{.greek-omitted} [εντειλατο]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [στυβαδας]{.greek-added} εκοπτον εκ των δενδρων και [εστρωννυον]{.greek-omitted} [εστροννυον]{.greek-added} εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν [ονοματι]{.greek-omitted} [ονοματη]{.greek-added} [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη [η]{.greek-added} βασιλεια [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν [μετα]{.greek-omitted} [με]{.greek-added} των δωδεκα[11:11]{.aside}

και τη επαυριον [εξελ]{.greek-added} [εξελθοντων]{.greek-omitted} [αυτων]{.greek-omitted} [απο]{.greek-omitted} [βηθανιας]{.greek-omitted} [επεινασεν]{.greek-omitted}[11:12]{.aside}

[και]{.greek-omitted} [τη]{.greek-omitted} [επαυριον]{.greek-omitted} [εξελθοντων]{.greek-omitted} [θοντων]{.greek-added} αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added}[11:12 | instance no. 2]{.aside}

και ιδων συκην μακροθεν εχουσαν φυλλα ηλθεν [ει]{.greek-omitted} [η]{.greek-added} αρα ευρησει τι εν αυτη και ελθων ε[π]{.unclear} αυτην ουδεν ευρεν ει [μη]{.greek-omitted} [μι]{.greek-added} φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη [μηκετι]{.greek-omitted} [μηκετη]{.greek-added} εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

κα[ι]{.unclear} ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο [εκβαλλειν]{.greek-omitted} [εκβαλειν]{.greek-added} τους [πωλουντας]{.greek-omitted} [πολουντας]{.greek-added} και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβηστων]{.greek-added} και τας [καθεδρας]{.greek-omitted} [τραπεζας]{.greek-added} των [πωλουντων]{.greek-omitted} [πολλουντων]{.greek-added} τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ ηφιεν ινα τις [διενεγκη]{.greek-omitted} [διενεγκει]{.greek-added} σκευος δια του ιερου[11:16]{.aside}

και εδιδασκεν λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος [προσευχης]{.greek-omitted} [προσευχει[ς]{.unclear}]{.greek-added} κληθησεται πασιν τοις [εθνεσιν]{.greek-omitted} [υμεις]{.greek-omitted} [δε]{.greek-omitted} [εποιησατε]{.greek-omitted} [αυτον]{.greek-omitted} [σπηλαιον]{.greek-omitted} [ληστων]{.greek-omitted}[11:17]{.aside}

[και]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [λεγων]{.greek-omitted} [αυτοις]{.greek-omitted} [ου]{.greek-omitted} [γεγραπται]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [οικος]{.greek-omitted} [μου]{.greek-omitted} [οικος]{.greek-omitted} [προσευχης]{.greek-omitted} [κληθησεται]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} εθνεσιν υμεις δε [εποιησατε]{.greek-omitted} αυτον [εποιησαται]{.greek-added} σπηλαιον ληστων[11:17 | instance no. 2]{.aside}

και ηκουσαν οι γραμματεις και οι αρχιερεις και εζητουν πως αυτον απολεσωσιν [εφοβουντο]{.greek-omitted} [εφοβουντω]{.greek-added} γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη [διδαχη]{.greek-omitted} [δηδαχη]{.greek-added} αυτου[11:18]{.aside}

και οτε οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενο[ι]{.unclear} [ειδον]{.greek-omitted} [ιδον]{.greek-added} την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και [αναμνησθεις]{.greek-omitted} [αναμνησθης]{.greek-added} ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω εξηρανται[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε [πιστιν]{.greek-omitted} [πιστην]{.greek-added} [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος [αν]{.greek-omitted} [εαν]{.greek-added} ειπη τω [ορει]{.greek-omitted} [ορι]{.greek-added} τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν [τη]{.greek-omitted} [τι]{.greek-added} καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσι]{.greek-added} οτι α λεγει γινεται [εσται]{.greek-omitted} [εστε]{.greek-added} αυτω ο εαν [ειπη]{.greek-omitted} [ειπει]{.greek-added}[11:23]{.aside}

[και]{.greek-added} δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτεισθαι]{.greek-added} [πισ]{.greek-added} [αιτησθε]{.greek-omitted} [πιστευετε]{.greek-omitted} [οτι]{.greek-omitted} [λαμβανετε]{.greek-omitted} [και]{.greek-omitted} [εσται]{.greek-omitted} [υμιν]{.greek-omitted}[11:24]{.aside}

[δια]{.greek-omitted} [τουτο]{.greek-omitted} [λεγω]{.greek-omitted} [τευεται]{.greek-added} [οτι]{.greek-added} [λαμβανεται]{.greek-added} [και]{.greek-added} [εστε]{.greek-added} υμιν [παντα]{.greek-omitted} [οσα]{.greek-omitted} [αν]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [αιτησθε]{.greek-omitted} [πιστευετε]{.greek-omitted} [οτι]{.greek-omitted} [λαμβανετε]{.greek-omitted} [και]{.greek-omitted} [εσται]{.greek-omitted} [υμιν]{.greek-omitted}[11:24 | instance no. 2]{.aside}

και οταν [στηκητε]{.greek-omitted} [στικετε]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα [παραπτωματα]{.greek-omitted} [παραπτοματα]{.greek-added} υμων[11:25]{.aside}

ει δε υμεις ουκ [αφιετε]{.greek-omitted} [αφηετε]{.greek-added} ουδε ο [πατηρ]{.greek-abbr} υμων ο εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται [παλιν]{.greek-omitted} [παλην]{.greek-added} εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι [γραμματεις]{.greek-omitted} [γραματεις]{.greek-added} και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας και εγω ενα λογον και αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και ελογιζοντο προς [εαυτους]{.greek-omitted} [λεγοντες]{.greek-omitted} [εαν]{.greek-omitted} [ειπωμεν]{.greek-omitted} [εξ]{.greek-omitted} [ουρανου]{.greek-omitted} [ερει]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [ουν]{.greek-omitted} [ουκ]{.greek-omitted} [επιστευσατε]{.greek-omitted} [αυτω]{.greek-omitted}[11:31]{.aside}

[και]{.greek-omitted} [ελογιζοντο]{.greek-omitted} [προς]{.greek-omitted} εαυτους λεγοντες εαν [ειπωμεν]{.greek-omitted} [ειπομεν]{.greek-added} εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31 | instance no. 2]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} [ειπωμεν]{.greek-omitted} [ειπον]{.greek-added} εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον απαντες γαρ ειχον τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες λεγουσιν τω [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και περιεθηκεν [φραγμον]{.greek-omitted} [φραγμων]{.greek-added} και ωρυξεν [υποληνιον]{.greek-omitted} [υπολινιον]{.greek-added} και ωκοδομησεν πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδιμησεν]{.greek-added}[12:1]{.aside}

και απεστειλεν προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων [λαβη]{.greek-omitted} [λαβει]{.greek-added} απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν [κενον]{.greek-omitted} [καινον]{.greek-added}[12:3]{.aside}

και [παλιν]{.greek-omitted} [παλην]{.greek-added} απεστειλεν προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} [εκεφα]{.greek-added} [εκεφαλαιωσαν]{.greek-omitted} [και]{.greek-omitted} [απεστειλαν]{.greek-omitted} [ητιμωμενον]{.greek-omitted}[12:4]{.aside}

[λαιωσαν]{.greek-added} [και]{.greek-omitted} [παλιν]{.greek-omitted} [απεστειλεν]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [αλλον]{.greek-omitted} [δουλον]{.greek-omitted} [κακεινον]{.greek-omitted} [λιθοβολησαντες]{.greek-omitted} [εκεφαλαιωσαν]{.greek-omitted} και απεστειλαν ητιμωμενον[12:4 | instance no. 2]{.aside}

και [παλιν]{.greek-omitted} [παλην]{.greek-added} [απεστειλεν]{.greek-added} αλλον [απεστειλεν]{.greek-omitted} κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα [υιον]{.greek-abbr} [εχον]{.greek-added} [εχων]{.corr} [αγαπητον]{.greek-omitted} [αγαπιτον]{.greek-added} αυτου απεστειλεν και αυτον προς αυτους εσχατον λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος [δευτε]{.greek-omitted} [δευται]{.greek-added} αποκτεινωμεν αυτον και ημων [εσται]{.greek-omitted} [εστε]{.greek-added} η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδοκημασαν]{.greek-added} οι οικοδομουντες ουτος [εγενηθη]{.greek-omitted} [εγεννηθην]{.greek-added} εις κεφαλην [γωνιας]{.greek-omitted} [γονιας]{.greek-added}[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν [θαυ]{.greek-added} [θαυμαστη]{.greek-omitted} [εν]{.greek-omitted} [οφθαλμοις]{.greek-omitted} [ημων]{.greek-omitted}[12:11]{.aside}

[μαστι]{.greek-added} [παρα]{.greek-omitted} [κυριου]{.greek-omitted} [εγενετο]{.greek-omitted} [αυτη]{.greek-omitted} [και]{.greek-omitted} [εστιν]{.greek-omitted} [θαυμαστη]{.greek-omitted} εν οφθαλμοις ημων[12:11 | instance no. 2]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και αποστελλουσιν προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα [αυτον]{.greek-omitted} [αυτων]{.greek-added} αγρευσωσιν λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και ου [μελει]{.greek-omitted} [μελη]{.greek-added} σοι περι ουδενος ου γαρ [βλεπεις]{.greek-omitted} [βλεπ[η]{.unclear}ς]{.greek-added} εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδ[α]{.unclear}σκεις [εξεστιν]{.greek-omitted} [εξεστην]{.greek-added} κηνσον [καισαρι]{.greek-omitted} [καισαρει]{.greek-added} δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε [ειδως]{.greek-omitted} [ιδως]{.greek-added} [αυτων]{.greek-omitted} [αυτον]{.greek-added} την υποκρισιν ειπεν αυτοις τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} φερετε μοι [δηναριον]{.greek-omitted} [διναριον]{.greek-added} ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ει]{.greek-added} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αποδοτε]{.greek-omitted} [τα]{.greek-omitted} [καισαρος]{.greek-omitted} [καισαρι]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [και]{.greek-omitted} [εθαυμασαν]{.greek-omitted} [επ]{.greek-omitted} [αυτω]{.greek-omitted}[12:17]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [πεν]{.greek-added} αυτοις [αποδοτε]{.greek-omitted} [αποδωται]{.greek-added} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17 | instance no. 2]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και [επηρωτησαν]{.greek-omitted} [επιρωτησαν]{.greek-added} αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι [εαν]{.greek-omitted} [αν]{.greek-added} τινος αδελφος [αποθανη]{.greek-omitted} [αποθανει]{.greek-added} και [καταλιπη]{.greek-omitted} [καταλιπει]{.greek-added} γυναικα και τεκνα μη αφη ινα [λαβη]{.greek-omitted} [λαβει]{.greek-added} ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι [ησαν]{.greek-omitted} [εισαν]{.greek-added} και ο πρωτος ελαβεν γυναικα και αποθνησκων ουκ αφηκεν σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν και ουδε αυτος αφηκεν σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και [οι]{.greek-added} [επτα]{.greek-added} ελαβον αυτην [οι]{.greek-omitted} [επτα]{.greek-omitted} και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} παντων [απεθανεν]{.greek-omitted} και η γυνη [απεθανεν]{.greek-added}[12:22]{.aside}

εν τη αναστασει οταν αναστωσιν [τι]{.greek-added} [τινος]{.greek-omitted} [αυτων]{.greek-omitted} [εσται]{.greek-omitted} [γυνη]{.greek-omitted} [οι]{.greek-omitted} [γαρ]{.greek-omitted} [επτα]{.greek-omitted} [εσχον]{.greek-omitted} [αυτην]{.greek-omitted} [γυναικα]{.greek-omitted}[12:23]{.aside}

[εν]{.greek-omitted} [τη]{.greek-omitted} [αναστασει]{.greek-omitted} [οταν]{.greek-omitted} [αναστωσιν]{.greek-omitted} [τινος]{.greek-omitted} [νος]{.greek-added} αυτων εσται [η]{.greek-added} γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added} μη [ειδοτες]{.greek-omitted} [ειδοταις]{.greek-added} τας γραφας μηδε την [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [γαμησκονται]{.greek-added} [αλλ]{.greek-omitted} [αλλα]{.greek-added} εισιν ως αγγελοι οι εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε [τι]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} βιβλω μωσεως επι του βατου [ως]{.greek-omitted} [ος]{.greek-added} ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-abbr} ζωντων υμεις ουν [πολυ]{.greek-omitted} [πολλοι]{.greek-added} [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added}[12:27]{.aside}

και προσελθων εις των γραμματεων ακουσας αυτων [συζητουντων]{.greek-omitted} [συνζητουντων]{.greek-added} [ειδως]{.greek-omitted} [ιδως]{.greek-added} οτι [καλως]{.greek-omitted} [καλος]{.greek-added} αυτοις απεκριθη επηρωτησεν αυτον ποια εστιν πρωτη παντων εντολη[12:28]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [απεκριθη]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [πρωτη]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} [εντολων]{.greek-omitted} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} [σου]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [διανοιας]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} [σου]{.greek-omitted} [αυτη]{.greek-omitted} [πρωτη]{.greek-omitted} [εντολη]{.greek-omitted}[12:30]{.aside}

[και]{.greek-omitted} [αγαπησεις]{.greek-omitted} [κυριον]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της [διανοιας]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} ισχυος σου αυτη πρωτη εντολη[12:30 | instance no. 2]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} [μειζων]{.greek-omitted} [μηζων]{.greek-added} [τουτων]{.greek-omitted} [τουτον]{.greek-added} αλλη εντολη ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς [καλως]{.greek-omitted} [διδασκαλε]{.greek-omitted} επ αληθειας ειπας οτι εις εστιν και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον εστιν παντων των [ολοκαυτωματων]{.greek-omitted} [ολοκαυτοματων]{.greek-added} και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων [αυτον]{.greek-omitted} [αυτων]{.greek-added} οτι νουνεχως [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} [ε]{.unclear}ιπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω [ιε]{.greek-added} [ιερω]{.greek-omitted} [πως]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [υιος]{.greek-omitted} [εστιν]{.greek-omitted} [δαυιδ]{.greek-omitted}[12:35]{.aside}

[ρω]{.greek-added} [και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ελεγεν]{.greek-omitted} [διδασκων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [[δαυιδ]{.greek-abbr}]{.greek-added} εστιν [δαυιδ]{.greek-omitted}[12:35 | instance no. 2]{.aside}

[αυτως]{.greek-added} [αυτος]{.corr} γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} [λεγει]{.greek-omitted} [καλει]{.greek-added} αυτον [κυριον]{.greek-abbr} και [ποθεν]{.greek-omitted} [πωθεν]{.greek-added} [υιος]{.greek-abbr} αυτου εστιν και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν [τη]{.greek-omitted} [τι]{.greek-added} διδαχη αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις [συναγωγαις]{.greek-omitted} [συναγογαις]{.greek-added} και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις [δειπνοις]{.greek-omitted} [διπνοις]{.greek-added}[12:39]{.aside}

οι [κατεσθιοντες]{.greek-omitted} [κατεσθειοντες]{.greek-added} τας οικιας των χηρων και [προφασει]{.greek-omitted} [προφαση]{.greek-added} μακρα προσευχομενοι ουτοι [ληψονται]{.greek-omitted} [λιψονται]{.greek-added} [περισσοτερον]{.greek-omitted} [περησωτερον]{.greek-added} κριμ[α]{.unclear}[12:40]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} ο [ιησους]{.greek-abbr} κατ[ε]{.unclear}ναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον ει[ς]{.unclear} το [γαζο]{.greek-added} [γαζοφυλακιον]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [πλουσιοι]{.greek-omitted} [εβαλλον]{.greek-omitted} [πολλα]{.greek-omitted}[12:41]{.aside}

[και]{.greek-omitted} [καθισας]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [κατεναντι]{.greek-omitted} [του]{.greek-omitted} [γαζοφυλακιου]{.greek-omitted} [εθεωρει]{.greek-omitted} [πως]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [βαλλει]{.greek-omitted} [χαλκον]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [γαζοφυλακιον]{.greek-omitted} [φυλακιον]{.greek-added} και πολλοι πλουσιοι εβαλλον πολλα[12:41 | instance no. 2]{.aside}

και ελθουσα μια χηρα [πτωχη]{.greek-omitted} [πτοχη]{.greek-added} [εβαλεν]{.greek-omitted} [εβαλλεν]{.greek-added} λεπτα δυο ο εστιν κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η [πτωχη]{.greek-omitted} [πτοχη]{.greek-added} πλειον παντων βεβληκεν των βαλλοντων εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισευοντος]{.greek-added} αυτοις [εβαλον]{.greek-omitted} [εβαλλον]{.greek-added} αυτη δε εκ της υστερησεως αυτης παντα [οσα]{.greek-omitted} [ωσα]{.greek-added} ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλ[ας]{.unclear} οικοδομας ου μη [αφεθη]{.greek-omitted} [αφεθει]{.greek-added} λιθος επι λιθω ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων [κατεναντι]{.greek-omitted} [του]{.greek-omitted} [ιερου]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [πετρος]{.greek-omitted} [και]{.greek-omitted} [ιακωβος]{.greek-omitted} [και]{.greek-omitted} [ιωαννης]{.greek-omitted} [και]{.greek-omitted} [ανδρεας]{.greek-omitted}[13:3]{.aside}

[και]{.greek-omitted} [καθημενου]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ορος]{.greek-omitted} [των]{.greek-omitted} [ελαιων]{.greek-omitted} κατεναντι του ιερου [επηρωτων]{.greek-omitted} [επιρωτων]{.greek-added} αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3 | instance no. 2]{.aside}

ειπε ημιν ποτε ταυτα [εσται]{.greek-omitted} [εστε]{.greek-added} και τι το [σημειον]{.greek-omitted} [σιμειον]{.greek-added} οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας [πλανηση]{.greek-omitted} [πλανησει]{.greek-added}[13:5]{.aside}

[πολλοι]{.greek-omitted} [πολοι]{.greek-added} γαρ [ελευσονται]{.greek-omitted} [ελευσοντε]{.greek-added} επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου λεγοντες οτι εγω ειμι και [πολλους]{.greek-omitted} [πολους]{.greek-added} πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη [θροεισθε]{.greek-omitted} [θρωεισθαι]{.greek-added} δει γαρ γενεσθαι αλλ [ουπω]{.greek-omitted} [ουπο]{.greek-added} το τελος[13:7]{.aside}

[εγερθησεται]{.greek-omitted} [εγερθεισετε]{.greek-added} γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται [σεισμοι]{.greek-omitted} [σισμοι]{.greek-added} κατα τοπους και [εσονται]{.greek-omitted} [εσοντε]{.greek-added} λιμοι και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους παραδωσουσιν γαρ υμας εις συνεδρια και εις συναγωγας [δαρησεσθε]{.greek-omitted} [δαρησεσθαι]{.greek-added} και επι [ηγεμονων]{.greek-omitted} [ηγεμωνω[ν]{.greek-supplied}]{.greek-added} και βασιλεων [στα]{.greek-added} [σταθησεσθε]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted}[13:9]{.aside}

[βλεπετε]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [εαυτους]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [γαρ]{.greek-omitted} [υμας]{.greek-omitted} [εις]{.greek-omitted} [συνεδρια]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [συναγωγας]{.greek-omitted} [δαρησεσθε]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [ηγεμονων]{.greek-omitted} [και]{.greek-omitted} [βασιλεων]{.greek-omitted} [σταθησεσθε]{.greek-omitted} [θησεσθε]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις[13:9 | instance no. 2]{.aside}

και εις παντα τα εθνη δει πρωτον [κηρυχθηναι]{.greek-omitted} [κηρυχθειναι]{.greek-added} το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας [παραδιδοντες]{.greek-omitted} μη [προμεριμνατε]{.greek-omitted} [προμεριμναται]{.greek-added} τι [λαλησητε]{.greek-omitted} [λαλησιτε]{.greek-added} μηδε μελετατε [αλ]{.greek-added} [αλλ]{.corr} ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο [λαλειτε]{.greek-omitted} [λαληται]{.greek-added} ου γαρ [οιμεις]{.greek-added} εστε [υμεις]{.greek-omitted} οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} [τεκνον]{.greek-omitted} [τεκνων]{.greek-added} και [επαναστησονται]{.greek-omitted} [επαναστησοντε]{.greek-added} τεκνα επι γονεις και [θανατωσουσιν]{.greek-omitted} [θανατοσουσιν]{.greek-added} αυτους[13:12]{.aside}

και εσεσθε [μισουμενοι]{.greek-omitted} [μησουμενοι]{.greek-added} υπο παντων δια το ονομα μου ο δε [υπομεινας]{.greek-omitted} [υπομηνας]{.greek-added} εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε [ιδητε]{.greek-omitted} [ιδιτε]{.greek-added} το βδελυγμα της ερημωσεως το [ρηθεν]{.greek-omitted} [ριθεν]{.greek-added} [υπο]{.greek-omitted} [δια]{.greek-added} δανιηλ του προφητου [εστως]{.greek-omitted} [εστος]{.greek-added} οπου ου δει ο [αναγινωσκων]{.greek-omitted} [αναγινοσκον]{.greek-added} νοειτω τοτε [οι]{.greek-omitted} εν τη ιουδαια [φευγετωσαν]{.greek-omitted} [φευγετοσαν]{.greek-added} εις τα [ορη]{.greek-omitted} [ορι]{.greek-added}[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την [οικιαν]{.greek-omitted} [μηδε]{.greek-omitted} [εισελθετω]{.greek-omitted} [αραι]{.greek-omitted} [τι]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [οικιας]{.greek-omitted} [αυτου]{.greek-omitted}[13:15]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [δωματος]{.greek-omitted} [μη]{.greek-omitted} [καταβατω]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15 | instance no. 2]{.aside}

και ο εις τον αγρον [ων]{.greek-omitted} [ον]{.greek-added} μη επιστρεψατω εις τα οπισω αραι [το]{.greek-omitted} [τω]{.greek-added} ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχαισθαι]{.greek-added} δε ινα μη γενηται η [φυγη]{.greek-omitted} [φυγι]{.greek-added} υμων [χειμωνος]{.greek-omitted} [χημωνος]{.greek-added}[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου γεγονεν τοιαυτη απ [αρχης]{.greek-omitted} [αρχεις]{.greek-added} [κτισεως]{.greek-omitted} [κτησεως]{.greek-added} ης [εκτισεν]{.greek-omitted} [εκτησεν]{.greek-added} ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και [ει]{.greek-omitted} [μη]{.greek-omitted} [η]{.greek-added} [μι]{.greek-added} [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβοσεν]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους [εξελεξατο]{.greek-omitted} [εξελεξατω]{.greek-added} εκολοβωσεν τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη πιστευετε[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και δωσουσιν [σημεια]{.greek-omitted} [σιμεια]{.greek-added} και τερατα προς το αποπλαναν ει δυνατον και [τους]{.greek-omitted} [του]{.greek-added} εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου [προειρηκα]{.greek-omitted} [προειρικα]{.greek-added} υμιν [παντα]{.greek-omitted} [απαντα]{.greek-added}[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα [την]{.greek-omitted} [θλιψιν]{.greek-omitted} [εκεινην]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [σκοτισθησεται]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [ου]{.greek-omitted} [δωσει]{.greek-omitted} [το]{.greek-omitted} [φεγγος]{.greek-omitted} [αυτης]{.greek-omitted}[13:24]{.aside}

[αλλ]{.greek-omitted} [εν]{.greek-omitted} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [μετα]{.greek-omitted} την θλιψιν [εκινην]{.greek-added} [εκεινην]{.corr} ο ηλιος [σκοτισθησεται]{.greek-omitted} [σκοτησθησεται]{.greek-added} και η σεληνη ου δωσει το φεγγος αυτης[13:24 | instance no. 2]{.aside}

και οι [αστερες]{.greek-omitted} [αστεραις]{.greek-added} του [ουρανου]{.greek-abbr} εσονται [εκπιπτοντες]{.greek-omitted} [εκπιπτονταις]{.greek-added} και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα [δυναμεω]{.greek-added} [δυναμεως]{.corr} πολλης και δοξης[13:26]{.aside}

και τοτε [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης [μαθετε]{.greek-omitted} [μαθεται]{.greek-added} την παραβολην οταν αυτης [ηδη]{.greek-omitted} ο κλαδος [ηδη]{.greek-added} απαλος γενηται και [εκφυη]{.greek-omitted} τα φυλλα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι [εγγυς]{.greek-omitted} [εγγοις]{.greek-added} το θερος εστιν[13:28]{.aside}

[ουτως]{.greek-omitted} [ουτος]{.greek-added} και υμεις οταν ταυτα [ιδητε]{.greek-omitted} [ιδηται]{.greek-added} [γινομενα]{.greek-omitted} [γινωμενα]{.greek-added} [γινωσκετε]{.greek-omitted} [γινοσκετε]{.greek-added} οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν [οτι]{.greek-omitted} ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η [γ]{.unclear}η [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι οι εν [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει [μη]{.greek-omitted} [μι]{.greek-added} ο [πατηρ]{.greek-abbr}[13:32]{.aside}

[βλεπετε]{.greek-omitted} [[β]{.unclear}λεπεται]{.greek-added} [αγρυπνειτε]{.greek-omitted} [αγρυπνιται]{.greek-added} και [προσευχεσθε]{.greek-omitted} [προσευχαισθαι]{.greek-added} ουκ [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} γαρ ποτε ο καιρος εστιν[13:33]{.aside}

[ος]{.greek-added} [ως]{.corr} [ανθρωπος]{.greek-abbr} [α]{.unclear}ποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω [θυρωρω]{.greek-omitted} [θυρορω]{.greek-added} [ενετειλατο]{.greek-omitted} [ενετειλατω]{.greek-added} ινα [γρηγορη]{.greek-omitted} [γριγορει]{.greek-added}[13:34]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγοριται]{.greek-added} ουν ουκ [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} [οψε]{.greek-omitted} [οψαι]{.greek-added} η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων [εξαιφνης]{.greek-omitted} [ευρη]{.greek-omitted} [εξεφνις]{.greek-added} [ευρει]{.greek-added} υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω πασιν λεγω [γρηγορειτε]{.greek-omitted} [γριγοριται]{.greek-added}[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και [εζητουν]{.greek-omitted} [εζειτουν]{.greek-added} οι [αρχιερεις]{.greek-omitted} [αρχηερεις]{.greek-added} και οι γραμματεις πως αυτον εν δολω [κρατησαντες]{.greek-omitted} [κρατισαντες]{.greek-added} αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν [τη]{.greek-omitted} [τι]{.greek-added} εορτη μηποτε θορυβος [εσται]{.greek-omitted} [εστε]{.greek-added} του λαου[14:2]{.aside}

και οντος αυτου εν [βηθανια]{.greek-omitted} [βιθανια]{.greek-added} εν [τη]{.greek-omitted} [τι]{.greek-added} οικια [σιμωνος]{.greek-omitted} [σιμονος]{.greek-added} του λεπρου [κατακειμενου]{.greek-omitted} [κατακειμε]{.greek-added} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

[νου]{.greek-added} [και]{.greek-omitted} [οντος]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} αυτου ηλθεν γυνη εχουσα αλαβαστρον μυρου ναρδου [πιστικης]{.greek-omitted} [πιστηκης]{.greek-added} πολυτελους και [συντριψασα]{.greek-omitted} [συντριψας]{.greek-added} το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3 | instance no. 2]{.aside}

ησαν δε [τινες]{.greek-omitted} [τιναις]{.greek-added} [αγανακτουντες]{.greek-omitted} [αγανακτουνταις]{.greek-added} προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

[ηδυνατο]{.greek-omitted} [ηδυνατω]{.greek-added} γαρ [τουτο]{.greek-omitted} [τουτω]{.greek-added} [το]{.greek-added} [μυρον]{.greek-added} [πραθηναι]{.greek-omitted} [πραθειναι]{.greek-added} επανω τριακοσιων [δηναριων]{.greek-omitted} [διναριων]{.greek-added} και δοθηναι τοις [πτωχοις]{.greek-omitted} [πτοχοις]{.greek-added} και [ενεβριμοντο]{.greek-added} [ενεβριμωντο]{.corr} αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον [ειργασατο]{.greek-omitted} [ηργασατω]{.greek-added} εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν [θελητε]{.greek-omitted} [θελετε]{.greek-added} [δυνασθε]{.greek-omitted} αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο [εσχεν]{.greek-omitted} [ειχεν]{.greek-added} αυτη εποιησεν προελαβεν μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου [εαν]{.greek-omitted} [αν]{.greek-added} [κηρυχθη]{.greek-omitted} [κηρυχθει]{.greek-added} το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθ[η]{.unclear}σεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο [ισκα]{.greek-added} [ισκαριωτης]{.greek-omitted} [εις]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [απηλθεν]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [αρχιερεις]{.greek-omitted} [ινα]{.greek-omitted} [παραδω]{.greek-omitted} [αυτον]{.greek-omitted} [αυτοις]{.greek-omitted}[14:10]{.aside}

[και]{.greek-omitted} [ριωτης]{.greek-added} ο [ιουδας]{.greek-omitted} [ο]{.greek-omitted} [ισκαριωτης]{.greek-omitted} εις των δωδεκα απηλθεν προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10 | instance no. 2]{.aside}

οι δε ακουσαντες [εχαρησαν]{.greek-omitted} [εχαρισαν]{.greek-added} και [επηγγειλαντο]{.greek-omitted} [επιγγειλαντο]{.greek-added} αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως [ευκαιρως]{.greek-omitted} [ευκερως]{.greek-added} αυτον παραδω[14:11]{.aside}

και [τη]{.greek-omitted} [τι]{.greek-added} πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα [φαγης]{.greek-omitted} [φαγεις]{.greek-added} το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την [πολιν]{.greek-omitted} [πολην]{.greek-added} και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που εστιν το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος [υμιν]{.greek-omitted} [ημιν]{.greek-added} δειξει [ανωγεον]{.greek-omitted} [ανογεον]{.greek-added} μεγα εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την [πολιν]{.greek-omitted} [πολην]{.greek-added} και ευρον [καθως]{.greek-omitted} [καθος]{.greek-added} ειπεν αυτοις και [ητοιμασαν]{.greek-omitted} [ητυμασαν]{.greek-added} το πασχα[14:16]{.aside}

και οψιας γενομενης [ερ]{.greek-added} [ερχεται]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted}[14:17]{.aside}

[και]{.greek-omitted} [οψιας]{.greek-omitted} [γενομενης]{.greek-omitted} [ερχεται]{.greek-omitted} [χεται]{.greek-added} μετα των δωδεκα[14:17 | instance no. 2]{.aside}

και [ανακειμενων]{.greek-omitted} [ανακειμενον]{.greek-added} αυτων και εσθιοντων [αυτων]{.greek-added} ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο [εσθιων]{.greek-omitted} [εσθιον]{.greek-added} μετ εμου[14:18]{.aside}

οι δε ηρξαντο [λυπεισθαι]{.greek-omitted} [λυπεισθε]{.greek-added} και λεγειν αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο [εμβαπτομενος]{.greek-omitted} [ενβαπτομενος]{.greek-added} μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει [καθως]{.greek-omitted} [καθος]{.greek-added} γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} [εκεινω]{.greek-omitted} [εκεινο]{.greek-added} δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} καλον ην αυτω [ει]{.greek-omitted} [η]{.greek-added} ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων [λαβον]{.greek-added} [λαβων]{.corr} ο [ιησους]{.greek-abbr} αρτον ευλογησας εκλασεν και εδωκεν αυτοις και ειπεν λαβετε [φαγετε]{.greek-omitted} τουτο εστιν το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον [ευχαριστησας]{.greek-omitted} [ευχαρηστησας]{.greek-added} εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο εστιν το αιμα μου το της [καινης]{.greek-omitted} διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη [πιω]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [γενηματος]{.greek-omitted} [της]{.greek-omitted} [αμπελου]{.greek-omitted} [εως]{.greek-omitted} [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} [οταν]{.greek-omitted} [αυτο]{.greek-omitted} [πινω]{.greek-omitted} [καινον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[14:25]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [ουκετι]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} πιω εκ του γενηματος της αμπελου εως της ημερας εκειν[ης]{.unclear} οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} πι[νω]{.unclear} [κ]{.unclear}αινον εν [τη]{.greek-omitted} [τι]{.greek-added} βα[σ]{.unclear}ιλεια του [θεου]{.greek-abbr}[14:25 | instance no. 2]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλησθισεσθαι]{.greek-added} [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπησθησεται]{.greek-added} τα προβατα [της]{.greek-added} [ποιμνης]{.greek-added}[14:27]{.aside}

αλλα μετα το [εγερθηναι]{.greek-omitted} [εγερθεινε]{.greek-added} με προαξω υμας εις την [γαλιλαιαν]{.greek-omitted} [γαληλαιαν]{.greek-added}[14:28]{.aside}

ο δε πετρος εφη αυτω [ει]{.greek-added} και [ει]{.greek-omitted} παντες [κανδαλησθησονται]{.greek-added} [σκανδαλισθησονται]{.greek-omitted} [[σκανδαλησθησονται]{.corr}]{.greek-added} αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι [συ]{.greek-omitted} [σοι]{.greek-added} σημερον εν [τη]{.greek-omitted} [τι]{.greek-added} [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} ταυτη πριν [η]{.greek-omitted} [ι]{.greek-added} [δις]{.greek-omitted} [δεις]{.greek-added} αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε [εκπερισσου]{.greek-omitted} [εκπερισου]{.greek-added} ελεγε[ν]{.unclear} μαλλον εαν με δεη συναποθανειν σοι ου μη σε απαρνησωμαι [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added} δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις [χοριον]{.greek-added} [χωριον]{.corr} ου το ονομα [γεθσημανη]{.greek-omitted} [γεσσημανη]{.greek-added} και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομε]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και [ιωαν]{.greek-added} [ιωαννην]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτου]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκθαμβεισθαι]{.greek-omitted} [και]{.greek-omitted} [αδημονειν]{.greek-omitted}[14:33]{.aside}

[νην]{.greek-added} [μεθ]{.greek-added} [αυτου]{.greek-added} και [παραλαμβανει]{.greek-omitted} [τον]{.greek-omitted} [πετρον]{.greek-omitted} [και]{.greek-omitted} [ιακωβον]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτου]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} εκθαμβεισθαι και [αδημονειν]{.greek-omitted} [αδιμονειν]{.greek-added}[14:33 | instance no. 2]{.aside}

και λεγει αυτοις [περιλυπος]{.greek-omitted} [περιλοιπος]{.greek-added} εστιν η ψυχη μου εως θανατου μεινατε ωδε και [γρηγορειτε]{.greek-omitted} [γριγοριται]{.greek-added}[14:34]{.aside}

και προσελθων [μικρον]{.greek-omitted} [μηκρον]{.greek-added} επεσεν επι της γης και [προσηυχετο]{.greek-omitted} [προσηυχετω]{.greek-added} ινα ει δυνατον εστιν [παρελθη]{.greek-omitted} [παρελθει]{.greek-added} απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι [παρενεγκε]{.greek-omitted} [παρενεγκαι]{.greek-added} το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ ου τι εγω θελω αλλα τι [συ]{.greek-omitted} [σοι]{.greek-added}[14:36]{.aside}

και ερχεται και [ευρισκει]{.greek-omitted} [ευρησκει]{.greek-added} αυτους καθευδοντας και λεγει τω πετρω σιμων [καθευδεις]{.greek-omitted} [καθευδης]{.greek-added} ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και [παλιν]{.greek-omitted} [παλην]{.greek-added} απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους [παλιν]{.greek-omitted} [παλην]{.greek-added} [αυτους]{.greek-added} καθευδοντας [ησαν]{.greek-omitted} [εισαν]{.greek-added} γαρ [αυτων]{.greek-added} οι οφθαλμοι [καταβαρυνομενοι]{.greek-added} [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} και ουκ [ηδεισαν]{.greek-omitted} [ειδησαν]{.greek-added} τι αυτω αποκριθωσιν[14:40]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} το τριτον και λεγει αυτοις [καθευδετε]{.greek-omitted} [καθευδε]{.greek-added} [λοιπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [απεχει]{.greek-omitted} [ηλθεν]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted} [ιδου]{.greek-omitted} [παραδιδοται]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [των]{.greek-omitted} [αμαρτωλων]{.greek-omitted}[14:41]{.aside}

[τε]{.greek-added} [και]{.greek-omitted} [ερχεται]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [καθευδετε]{.greek-omitted} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των αμαρτωλων[14:41 | instance no. 2]{.aside}

[εγειρεσθε]{.greek-omitted} [εγειρεσθαι]{.greek-added} αγωμεν ιδου ο παραδιδους με [ηγγικεν]{.greek-omitted} [ηγγηκεν]{.greek-added}[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται [ο]{.greek-added} ιουδας εις ων των δωδεκα και μετ αυτου οχλος [πολυς]{.greek-omitted} [πολοις]{.greek-added} μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γραμματεων και των πρεσβυτερων[14:43]{.aside}

[δεδωκει]{.greek-omitted} [δεδοκει]{.greek-added} δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος εστιν [κρατησατε]{.greek-omitted} [κρατεισαται]{.greek-added} αυτον και απαγαγετε [ασφαλος]{.greek-added} [ασφαλως]{.corr}[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας [αυτων]{.greek-omitted} [αυτω]{.greek-added} και [εκρατησαν]{.greek-omitted} [εκρατισαν]{.greek-added} αυτον[14:46]{.aside}

εις δε τις των [παρεστηκοτων]{.greek-omitted} [παρεστικοτων]{.greek-added} σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επεσεν]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι λ[η]{.unclear}στην [εξηλθετε]{.greek-omitted} [εξηλθαται]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ [ημεραν]{.greek-omitted} [ημην]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [διδασκων]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εκρατησατε]{.greek-omitted} [με]{.greek-omitted} [ημε]{.greek-added} [αλλ]{.greek-omitted} [ινα]{.greek-omitted} [πληρωθωσιν]{.greek-omitted} [αι]{.greek-omitted} [γραφαι]{.greek-omitted}[14:49]{.aside}

[ραν]{.greek-added} [καθ]{.greek-omitted} [ημεραν]{.greek-omitted} ημην προς υμας εν τω ιερω διδασκων και [ου]{.greek-added} [ουκ]{.corr} [εκρατησατε]{.greek-omitted} [κρατισατε]{.greek-added} με αλλ ινα πληρωθωσιν αι γραφαι[14:49 | instance no. 2]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω [περιβεβλημενος]{.greek-omitted} [περιβεβλιμενος]{.greek-added} σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και [απηγαγον]{.greek-omitted} [απιγαγον]{.greek-added} τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην [συγκαθημενος]{.greek-omitted} [συνκαθημενος]{.greek-added} μετα των [υπηρετων]{.greek-omitted} [υπιρετων]{.greek-added} και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το [θανατωσαι]{.greek-omitted} [θανατοσαι]{.greek-added} αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ [εψευδομαρτυρουν]{.greek-omitted} [εψευδομαρτυρισαν]{.greek-added} κατ αυτου και [ισαι]{.greek-omitted} [εισαι]{.greek-added} αι μαρτυριαι ουκ [ησαν]{.greek-omitted} [εισαν]{.greek-added}[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου [λεγοντες]{.greek-omitted} [λεγον]{.greek-added}[14:57]{.aside}

[και]{.greek-omitted} [τινες]{.greek-omitted} [τες]{.greek-added} [ανασταντες]{.greek-omitted} [εψευδομαρτυρουν]{.greek-omitted} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} [λεγοντες]{.greek-omitted}[14:57 | instance no. 2]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε [ουτως]{.greek-omitted} [ουτος]{.greek-added} ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επιρωτισεν]{.greek-added} τον [ιησουν]{.greek-abbr} [λεγον]{.greek-added} [λεγων]{.corr} ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν [τι]{.greek-omitted} [τη]{.greek-added} ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε [ειωπα]{.greek-added} [εσιωπα]{.corr} και ουδεν απεκρινατο παλιν ο αρχιερευς [επηρωτα]{.greek-omitted} [επιρωτησεν]{.greek-added} αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [καθημενον]{.greek-added} εκ [δεξιων]{.greek-omitted} [δεξιον]{.greek-added} [καθημενον]{.greek-omitted} της δυναμεως και [ερχομενον]{.greek-omitted} [ερχωμενον]{.greek-added} μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς [διαρρηξας]{.greek-omitted} [διαρριξας]{.greek-added} τους [χιτωνας]{.greek-omitted} [χειτωνας]{.greek-added} αυτου λεγει τι ετι [χρειαν]{.greek-omitted} [χριαν]{.greek-added} [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν [φαινεται]{.greek-omitted} [φενετε]{.greek-added} οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες [εμπτυειν]{.greek-omitted} [ενπτυειν]{.greek-added} αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} [προφητευσον]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [υπηρεται]{.greek-omitted} [ραπισμασιν]{.greek-omitted} [αυτον]{.greek-omitted} [εβαλλον]{.greek-omitted}[14:65]{.aside}

[και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [τινες]{.greek-omitted} [εμπτυειν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [περικαλυπτειν]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [κολαφιζειν]{.greek-omitted} αυτον και λεγειν αυτω προφητευσον και οι υπηρεται ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added}[14:65 | instance no. 2]{.aside}

και οντος του πετρου εν [τη]{.greek-omitted} [τι]{.greek-added} αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον [θερμαινομενον]{.greek-omitted} [θερμενομενον]{.greek-added} [εμβλεψασα]{.greek-omitted} [εμβλεψας]{.greek-added} αυτω λεγει και [συ]{.greek-omitted} [σοι]{.greek-added} μετα του [ναζαρηνου]{.greek-omitted} [ναζαρινου]{.greek-added} [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} [επισταμαι]{.greek-omitted} [επισταμε]{.greek-added} τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ εφωνησεν[14:68]{.aside}

και η [παιδισκη]{.greek-omitted} [παιδισκει]{.greek-added} ιδουσα αυτον παλιν [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστικωσιν]{.greek-added} οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνητω]{.greek-added} και μετα [μικρον]{.greek-omitted} [μηκρον]{.greek-added} παλιν οι [παρεστωτες]{.greek-omitted} [παρεστοταις]{.greek-added} ελεγον τω πετρω αληθως εξ αυτων ει και γαρ [γαλιλαιος]{.greek-omitted} [γαληλαιος]{.greek-added} ει και η [λαλια]{.greek-omitted} [λαληα]{.greek-added} σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ εφωνησεν και [ανεμνησθη]{.greek-omitted} [εμνησθη]{.greek-added} ο πετρος το ρημα [ο]{.greek-omitted} [ω]{.greek-added} ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι [δις]{.greek-omitted} [απαρνηση]{.greek-omitted} [με]{.greek-omitted} [τρις]{.greek-omitted} [και]{.greek-omitted} [επιβαλων]{.greek-omitted} [εκλαιεν]{.greek-omitted}[14:72]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [δευτερου]{.greek-omitted} [αλεκτωρ]{.greek-omitted} [εφωνησεν]{.greek-omitted} [και]{.greek-omitted} [ανεμνησθη]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [το]{.greek-omitted} [ρημα]{.greek-omitted} [ο]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [πριν]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72 | instance no. 2]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} [απηνεγκαν]{.greek-omitted} [απι[νεγ]{.unclear}καν]{.greek-added} και παρεδωκαν τω πιλατω[15:1]{.aside}

και [επηρωτησεν]{.greek-omitted} [επιρωτισεν]{.greek-added} αυτον ο [πιλατος]{.greek-omitted} [πειλατος]{.greek-added} συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και [κατηγορουν]{.greek-omitted} [κατηγωρουν]{.greek-added} αυτου [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} πολλα[15:3]{.aside}

ο δε [πιλατος]{.greek-omitted} [πειλατος]{.greek-added} παλιν [επηρωτησεν]{.greek-omitted} [επιρωτισεν]{.greek-added} αυτον λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} ωστε θαυμαζειν τον [πιλατον]{.greek-omitted} [πειλατον]{.greek-added}[15:5]{.aside}

κατα δε εορτην απελυεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει [φονον]{.greek-omitted} [φωνον]{.greek-added} [πεποιηκεισαν]{.greek-omitted} [πεποιηκασιν]{.greek-added}[15:7]{.aside}

και [αναβοησας]{.greek-omitted} [αναβοεισας]{.greek-added} ο οχλος [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε [πιλατος]{.greek-omitted} [πειλατος]{.greek-added} [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} αυτοις λεγων [θελετε]{.greek-omitted} [θελεται]{.greek-added} απολυσω υμιν τον βασιλεα [των]{.greek-omitted} [ιουδαιων]{.greek-omitted}[15:9]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [απεκριθη]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} [θελετε]{.greek-omitted} [απολυσω]{.greek-omitted} [υμιν]{.greek-omitted} [τον]{.greek-omitted} [βασιλεα]{.greek-omitted} των ιουδαιων[15:9 | instance no. 2]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινοσκεν]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παραδεδωκασιν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεσισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} αυτοις[15:11]{.aside}

ο δε [πιλατος]{.greek-omitted} [πειλατος]{.greek-added} αποκριθεις παλιν ειπεν αυτοις τι ουν [θελετε]{.greek-omitted} [θελετα]{.greek-added} [[θελεται]{.corr}]{.greek-added} ποιησω ον λεγετε [τον]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν σταυρωσον αυτον[15:13]{.aside}

ο δε [πιλατος]{.greek-omitted} [πειλατος]{.greek-added} ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισοτερος]{.greek-added} εκραξαν σταυρωσον αυτον[15:14]{.aside}

ο δε [πιλατος]{.greek-omitted} [πειλατος]{.greek-added} βουλομενος τω οχλω το ικανον ποιησαι [απελυσεν]{.greek-omitted} [απελοισεν]{.greek-added} αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκαν]{.greek-added} τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγελωσας]{.greek-added} ινα σταυρωθη[15:15]{.aside}

οι δε στρατιωται [απηγαγον]{.greek-omitted} [απιγαγον]{.greek-added} αυτον εσω της αυλης ο εστιν πραιτωριον και [συγκαλουσιν]{.greek-omitted} [συνκαλουσιν]{.greek-added} ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον [στεφανον]{.greek-omitted} [στεφανονον]{.greek-added}[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον [αυ]{.greek-added} [αυτου]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [καλαμω]{.greek-omitted} [και]{.greek-omitted} [ενεπτυον]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [τιθεντες]{.greek-omitted} [τα]{.greek-omitted} [γονατα]{.greek-omitted} [προσεκυνουν]{.greek-omitted} [αυτω]{.greek-omitted}[15:19]{.aside}

[και]{.greek-omitted} [ετυπτον]{.greek-omitted} [αυτου]{.greek-omitted} [του]{.greek-added} την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα [γονατα]{.greek-omitted} [γωνατα]{.greek-added} προσεκυνουν αυτω[15:19 | instance no. 2]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα σταυρωσωσιν αυτον[15:20]{.aside}

και αγγαρευουσιν [παραγοντα]{.greek-omitted} [παραγοντι]{.greek-added} τινα σιμωνα [κυρηναιον]{.greek-omitted} [κυριναιον]{.greek-added} ερχομενον [απ]{.greek-omitted} [απο]{.greek-added} αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα [αρη]{.greek-omitted} [αρει]{.greek-added} τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [γολγοθα]{.greek-omitted} [γολγοθαν]{.greek-added} τοπον ο εστιν μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν [εσμυρνισμενον]{.greek-omitted} [εσμυρισμενον]{.greek-added} οινον ο δε ουκ ελαβεν[15:23]{.aside}

και σταυρωσαντες αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα [τριτη]{.greek-omitted} [εκτι]{.greek-added} και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου [επιγεγραμμενη]{.greek-omitted} [επιγεγραμενον]{.greek-added} ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω σταυρουσιν δυο ληστας ενα εκ δεξιων και ενα εξ [ευωνυμων]{.greek-omitted} [ευωνυμον]{.greek-added} αυτου[15:27]{.aside}

και [επληρωθη]{.greek-omitted} [επληρω]{.greek-added} [η]{.greek-omitted} [γραφη]{.greek-omitted} [η]{.greek-omitted} [λεγουσα]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [ανομων]{.greek-omitted} [ελογισθη]{.greek-omitted}[15:28]{.aside}

[θη]{.greek-added} [και]{.greek-omitted} [επληρωθη]{.greek-omitted} η γραφη η λεγουσα και μετα ανομων [ελογισθη]{.greek-omitted} [ελογησθη]{.greek-added}[15:28 | instance no. 2]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες [οα]{.greek-added} [ουα]{.corr} ο [καταλυων]{.greek-omitted} [καταλυον]{.greek-added} τον ναον και [εν]{.greek-omitted} τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [καταβιθη]{.greek-added} απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} προς αλληλους μετα των γραμματεων [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} [καταβατω]{.greek-omitted} [καταβατο]{.greek-added} νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι συνεσταυρωμενοι αυτω [ωνειδιζον]{.greek-omitted} [ονιδειζον]{.greek-added} αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και [τη]{.greek-omitted} [τι]{.greek-added} ωρα [τη]{.greek-omitted} [τι]{.greek-added} ενατη εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λημα]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβακθανι]{.greek-added} ο εστιν [μεθερμηνευομενον]{.greek-omitted} [μεθερμινευομενον]{.greek-added} ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με [εγκατελιπες]{.greek-omitted} [εγκατελειπες]{.greek-added}[15:34]{.aside}

και τινες των [παρεστηκοτων]{.greek-omitted} [παρεστικοτων]{.greek-added} ακουσαντες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και [γεμισας]{.greek-omitted} [γεμησας]{.greek-added} σπογγον οξους [περιθεις]{.greek-omitted} [τε]{.greek-omitted} [καλαμω]{.greek-omitted} [εποτιζεν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [ιδωμεν]{.greek-omitted} [ει]{.greek-omitted} [ερχεται]{.greek-omitted} [ηλιας]{.greek-omitted} [καθελειν]{.greek-omitted} [αυτον]{.greek-omitted}[15:36]{.aside}

[δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γεμισας]{.greek-omitted} [σπογγον]{.greek-omitted} [οξους]{.greek-omitted} περιθεις τε καλαμω εποτιζεν αυτον λεγων [αφετε]{.greek-omitted} [αφες]{.greek-added} ιδωμεν ει [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} ηλιας καθελειν αυτον[15:36 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη [εις]{.greek-omitted} [δυο]{.greek-omitted} απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο [κεντυριον]{.greek-added} [κεντυριων]{.corr} ο [παρεστηκως]{.greek-omitted} [παρεστικος]{.greek-added} εξ εναντιας αυτου οτι [ουτως]{.greek-omitted} [ουτος]{.greek-added} κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} θεωρουσαι εν αις ην και μαρια η μαγδαληνη και μαρια η [του]{.greek-omitted} [το]{.greek-added} ιακωβου του [μικρου]{.greek-omitted} [μηκρου]{.greek-added} και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

[αι]{.greek-omitted} και οτε ην εν τη [γαλιλαια]{.greek-omitted} [γαληλαια]{.greek-added} ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι [συναναβασαι]{.greek-omitted} [συναναβασε]{.greek-added} αυτω εις ιεροσολυμα[15:41]{.aside}

και [η]{.unclear}δη οψιας γενομενης επει ην παρασκευη ο εστιν [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο [αριμαθαιας]{.greek-omitted} [αριμαθιας]{.greek-added} ευσχημων βουλευτης ος και αυτος [ην]{.greek-omitted} [προσδεχομενος]{.greek-omitted} [προσδεχωμενος]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} τολμησας εισηλθεν προς [πιλατον]{.greek-omitted} [πειλατον]{.greek-added} και [ητησατο]{.greek-omitted} [ητησα]{.greek-added} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted}[15:43]{.aside}

[ηλθεν]{.greek-omitted} [ιωσηφ]{.greek-omitted} [ο]{.greek-omitted} [απο]{.greek-omitted} [αριμαθαιας]{.greek-omitted} [ευσχημων]{.greek-omitted} [βουλευτης]{.greek-omitted} [ος]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ην]{.greek-omitted} [προσδεχομενος]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [το]{.greek-added} [θεου]{.greek-omitted} [τολμησας]{.greek-omitted} [εισηλθεν]{.greek-omitted} [προς]{.greek-omitted} [πιλατον]{.greek-omitted} [και]{.greek-omitted} [ητησατο]{.greek-omitted} το σωμα του [ιησου]{.greek-abbr}[15:43 | instance no. 2]{.aside}

ο δε [πιλατος]{.greek-omitted} [πειλατος]{.greek-added} εθαυμασεν ει [ηδη]{.greek-omitted} [ηδι]{.greek-added} [τεθνηκεν]{.greek-omitted} [τεθνικεν]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα [επηρωτησεν]{.greek-omitted} [επειρωτισεν]{.greek-added} αυτον ει παλαι [απεθανεν]{.greek-omitted} [απαιθανεν]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος [εδωρησατο]{.greek-omitted} [εδωρισατο]{.greek-added} το σωμα τω ιωσηφ[15:45]{.aside}

[και]{.greek-omitted} [ο]{.greek-added} [δε]{.greek-added} [ιωσηφ]{.greek-added} [αγορασας]{.greek-omitted} [αγωρασας]{.greek-added} σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενιλησεν]{.greek-added} τη σινδονι και [κατεθηκεν]{.greek-omitted} [κατεθεικεν]{.greek-added} αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλησεν]{.greek-added} λιθον επι την θυραν του [μνημειου]{.greek-omitted} [μνμειου]{.greek-added}[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-added} [του]{.greek-added} ιακωβου και σαλωμη [ηγορασαν]{.greek-omitted} [ηγωρασαν]{.greek-added} αρωματα ινα ελθουσαι αλειψωσιν [αυτον]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το [μνημειον]{.greek-omitted} [μνημειων]{.greek-added} [ετι]{.greek-added} ανατειλαντος του [ηλιου]{.greek-omitted} [ηληου]{.greek-added}[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον [εκ]{.greek-omitted} [απο]{.greek-added} της θυρα[ς]{.unclear} του μνημειου[16:3]{.aside}

και [αναβλεψασαι]{.greek-omitted} [αναβλεψασε]{.greek-added} θεωρουσιν οτι [αποκεκυλισται]{.greek-omitted} [αποκεκυλησται]{.greek-added} ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον [ειδον]{.greek-omitted} [ιδων]{.greek-added} νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και [εξεθαμβηθησαν]{.greek-omitted} [εξεθαμβειθησαν]{.greek-added}[16:5]{.aside}

ο δε λεγει [αυταις]{.greek-omitted} [αυτοις]{.greek-added} μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβεισθαι]{.greek-added} [ιησουν]{.greek-abbr} [ζητειτε]{.greek-omitted} [ζητειται]{.greek-added} τον [ναζαρηνον]{.greek-omitted} [ναζορινον]{.greek-added} τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθ[η]{.unclear}καν αυτον[16:6]{.aside}

αλλ υπαγετε [ειπατε]{.greek-omitted} [ειπαται]{.greek-added} τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την [γαλιλαιαν]{.greek-omitted} [γαληλαιαν]{.greek-added} εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου ειχεν δε αυτας τρομος και εκστασις και ουδενι ουδεν [ειπον]{.greek-omitted} [ειπων]{.greek-added} εφοβουντο γαρ[16:8]{.aside}

αναστας δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι [πρωτη]{.greek-omitted} [πρωτης]{.greek-added} σαββατου εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης [εκβεβληκει]{.greek-omitted} [εκβεβλικει]{.greek-added} επτα δαιμονια[16:9]{.aside}

[εκεινη]{.greek-omitted} [εκηνει]{.greek-added} πορευθεισα [απηγγειλεν]{.greek-omitted} [απιγειλεν]{.greek-added} τοις μετ αυτου γενομενοις πενθουσιν και κλαιουσιν[16:10]{.aside}

κακεινοι ακουσαντες οτι [ζη]{.greek-omitted} [ζει]{.greek-added} και [εθεαθη]{.greek-omitted} [εθεα]{.greek-added} [υπ]{.greek-omitted} [αυτης]{.greek-omitted} [ηπιστησαν]{.greek-omitted}[16:11]{.aside}

[θη]{.greek-added} [κακεινοι]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οτι]{.greek-omitted} [ζη]{.greek-omitted} [και]{.greek-omitted} [εθεαθη]{.greek-omitted} υπ αυτης ηπιστησαν[16:11 | instance no. 2]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν [εφανερωθη]{.greek-omitted} [εφανη]{.greek-added} εν ετερα μορφη [πορευομενοις]{.greek-omitted} [πορεομενοις]{.greek-added} εις αγρον[16:12]{.aside}

κακεινοι απελθοντες [[απελτωντες]{.corr}]{.greek-added} [απηγγειλαν]{.greek-omitted} [απιγγειλαν]{.greek-added} τοις [λοιποις]{.greek-omitted} [λυποις]{.greek-added} ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ονιδεισεν]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον [εγηγερμενον]{.greek-omitted} [εγειγερμενον]{.greek-added} [εκ]{.greek-added} [νεκρον]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα [κηρυξατε]{.greek-omitted} [κηρυξαται]{.greek-added} το ευαγγελιον [παση]{.greek-omitted} [πασι]{.greek-added} τη [κτισει]{.greek-omitted} [κτηση]{.greek-added}[16:15]{.aside}

ο πιστευσας και [βαπτισθεις]{.greek-omitted} [βαπτησθεις]{.greek-added} [σωθησεται]{.greek-omitted} [σωθησετε]{.greek-added} ο δε [απιστησας]{.greek-omitted} [απιστεισας]{.greek-added} κατακριθησεται[16:16]{.aside}

σημεια δε τοις πιστευσασιν ταυτα παρακολουθησει εν [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου [δαιμονια]{.greek-omitted} [δαιμονι]{.greek-added} [εκβαλουσιν]{.greek-omitted} [εκβαλλουσιν]{.greek-added} [γλωσσαις]{.greek-omitted} [γλοσαις]{.greek-added} λαλησουσιν καιναις[16:17]{.aside}

οφεις αρουσιν καν [θανασιμον]{.greek-omitted} [θανασιμων]{.greek-added} τι πιωσιν ου μη αυτους βλαψη [επι]{.greek-omitted} [επ]{.greek-added} αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθεισουσιν]{.greek-added} και [καλως]{.greek-omitted} [καλος]{.greek-added} εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} [[ιησους]{.greek-abbr}]{.greek-added} μετα [το]{.greek-omitted} [λαλησαι]{.greek-omitted} [αυτοις]{.greek-omitted} [ανεληφθη]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [και]{.greek-omitted} [εκαθισεν]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[16:19]{.aside}

[ο]{.greek-omitted} [μεν]{.greek-omitted} [ουν]{.greek-omitted} [κυριος]{.greek-omitted} [μετα]{.greek-omitted} το [λαλησαι]{.greek-omitted} [λαλεισαι]{.greek-added} αυτοις [ανεληφθη]{.greek-omitted} [[α]{.unclear}νε[λημ]{.unclear}φθει]{.greek-added} εις [τον]{.greek-omitted} [τω[ν]{.unclear}]{.greek-added} [ουρανον]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ [δεξιων]{.greek-omitted} [δεξειων]{.greek-added} του [θεου]{.greek-abbr}[16:19 | instance no. 2]{.aside}

εκεινοι δε εξελθοντες εκηρυ[ξ]{.unclear}αν πανταχου του [του]{.greek-added} [κυριου]{.greek-abbr} συνεργουντος και τον λογον [βεουντος]{.greek-added} [βεβαιουντος]{.corr} δια των επακολουθουντων [σημειων]{.greek-omitted} [σιμειων]{.greek-added} αμην[16:20]{.aside}

