---
title: "Collation of Byz^RP^ vs 20236 (236)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 236 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20236).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 236                                   	| λογος                              	|
| 236 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 236 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 236               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 236                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 236 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 236                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 3

[[α]{.unclear}υτους]{.greek-added} [ιδων]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} [απεκρινατο]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [ανδρ]{.greek-supplied}[ες]{.unclear} [ισραηλιται]{.greek-omitted} [[ι]{.greek-supplied}σρα[η]{.unclear}λειτ[αι]{.greek-supplied}]{.greek-added} [τι]{.greek-supplied} [θαυ]{.unclear}μα[ζε]{.unclear}τ[ε]{.greek-supplied} [επι]{.greek-supplied} τ[ου]{.unclear}τω η [ημ]{.unclear}[ιν]{.greek-supplied} [τι]{.greek-supplied} [α]{.greek-supplied}[τε]{.unclear}νιζετε ως [ιδια]{.unclear} [δυ]{.greek-supplied}ναμει η ευ[σε]{.unclear}[βεια]{.greek-supplied} [τουτο]{.greek-added} πεπ[ο]{.unclear}[ιηκο]{.greek-supplied}[σιν]{.greek-supplied} [του]{.greek-omitted} [περιπατειν]{.greek-omitted} [αυτον]{.greek-omitted}[3:12]{.aside}

ο [θεος]{.greek-abbr} αβραα[μ]{.unclear} [και]{.unclear} [ισα]{.greek-supplied}[α]{.unclear}κ και ιακω[β]{.unclear} [ο]{.unclear} [[θεος]{.greek-abbr}]{.greek-supplied} [τ]{.greek-supplied}[ων]{.unclear} πατ[ερ]{.unclear}ω[ν]{.greek-supplied} [ημ]{.greek-supplied}[ω]{.unclear}ν εδοξ[ασεν]{.unclear} [τον]{.greek-supplied} παιδα αυ[το]{.unclear}υ [ιησουν]{.greek-omitted} [ον]{.greek-omitted} [υμεις]{.greek-omitted} [μεν]{.greek-omitted} [παρεδωκατε]{.greek-omitted} [και]{.greek-omitted} [ηρνησασθε]{.greek-omitted} [αυτον]{.greek-omitted} [κατα]{.greek-omitted} [προσωπον]{.greek-omitted} [πιλατου]{.greek-omitted} [κριναντος]{.greek-omitted} [εκεινου]{.greek-omitted} [απολυειν]{.greek-omitted}[3:13]{.aside}

[τον]{.greek-omitted} [δε]{.greek-omitted} [αρχηγο]{.greek-supplied}ν τ[η]{.unclear}ς [ζωης]{.greek-supplied} [α]{.greek-supplied}πεκτεινα[τε]{.greek-supplied} [ον]{.greek-supplied} [ο]{.greek-supplied} [θεος]{.greek-abbr} ηγειρεν [[αυτο]{.greek-supplied}ν]{.greek-added} εκ νεκρων [ου]{.greek-supplied} [η]{.greek-supplied}μεις μαρτυ[ρες]{.greek-supplied} εσμεν[3:15]{.aside}

και [επι]{.greek-omitted} [τη]{.greek-supplied} [π]{.unclear}ιστει τ[ου]{.unclear} ο[νο]{.greek-supplied}ματος α[υ]{.unclear}του [τ]{.greek-supplied}[ο]{.unclear}υτον ον [θ]{.unclear}εω[ρ]{.greek-supplied}[ε]{.unclear}ιτε και ο[ι]{.unclear}δατε [ε]{.greek-supplied}στερεωσεν το [ο]{.unclear}νομα αυτου και η πιστις η δι [αυ]{.unclear}του εδωκεν [αυτω]{.greek-omitted} [την]{.greek-omitted} [ολοκληριαν]{.greek-omitted} [ταυτην]{.greek-omitted} [απεναντι]{.greek-omitted} [παντων]{.greek-omitted} [υμων]{.greek-omitted}[3:16]{.aside}

