---
title: "Collation of Byz^RP^ vs 20232 (232)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 232 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20232).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 232                                   	| λογος                              	|
| 232 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 232 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 232               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 232                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 232 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 232                                                     	| [―]{.gap}                        	|
:::

## Second John

### Chapter 1

[ο]{.greek-omitted} [πρεσβυτερος]{.greek-omitted} [εκλεκτη]{.greek-omitted} κυρια και τοι[ς]{.unclear} τεκνοις αυτης ους εγω αγαπω εν αληθεια και ουκ εγω μονος αλλα [και]{.greek-omitted} παντες οι εγνωκοτες την αληθειαν[1:1]{.aside}

δια την αληθειαν την μενουσαν εν [ημιν]{.greek-omitted} [ημειν]{.greek-added} και μεθ ημων εσται εις τον αιωνα[1:2]{.aside}

εσται μεθ ημων χαρις [ελεος]{.greek-omitted} [ελαιος]{.greek-added} ειρηνη παρα [θεου]{.greek-abbr} [πατρος]{.greek-abbr} και παρα [κυριου]{.greek-omitted} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του [υιου]{.greek-abbr} του [πατρος]{.greek-abbr} εν αληθ[εια]{.unclear} [και]{.greek-omitted} [α]{.unclear}γαπη[1:3]{.aside}

εχαρην [λιαν]{.greek-omitted} [λειαν]{.greek-added} [οτ]{.unclear}ι [ευρηκα]{.greek-omitted} [[ε]{.unclear}υ[ρο]{.unclear}ν]{.greek-added} εκ των τεκνων [σ]{.unclear}ου π[ερι]{.unclear}πατουντας εν αληθ[εια]{.unclear} [κα]{.unclear}θως εντολην ελαβο[μεν]{.greek-supplied} [π]{.greek-supplied}[αρα]{.unclear} του [πατρος]{.greek-abbr}[1:4]{.aside}

[κ]{.unclear}αι νυν [ερωτω]{.greek-supplied} [σε]{.greek-supplied} [κυρια]{.greek-supplied} [ουχ]{.greek-supplied} [ως]{.greek-supplied} [ε]{.unclear}ν[τολην]{.greek-supplied} [γραφων]{.greek-omitted} [σοι]{.greek-omitted} [καινην]{.greek-omitted} [αλλα]{.greek-omitted} [ην]{.greek-omitted} [ειχομεν]{.greek-omitted} [απ]{.greek-omitted} [αρχης]{.greek-omitted} [ινα]{.greek-omitted} [αγαπωμεν]{.greek-omitted} [αλληλους]{.greek-omitted}[1:5]{.aside}

[και]{.greek-omitted} [αυτη]{.greek-omitted} [εστιν]{.greek-omitted} η αγαπη ινα πε[ρ]{.unclear}ιπατωμεν κατα τας εντολ[α]{.unclear}ς αυτου αυτη [εστιν]{.greek-omitted} η εντολη [εστιν]{.greek-added} [ινα]{.greek-added} καθως ηκουσατε απ αρχης ινα εν αυτη [περιπατητε]{.greek-omitted} [περιπατητα[ι]{.unclear}]{.greek-added}[1:6]{.aside}

[ο]{.unclear}τι πολλοι πλανοι [εισηλθον]{.greek-omitted} [εξηλθον]{.greek-added} εις [τ]{.unclear}ον κοσμον οι μη ομολογουν[τες]{.unclear} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} ερχομενον εν σαρκι ου[τος]{.unclear} [ε]{.unclear}στιν ο πλανος και ο [αντιχριστος]{.greek-omitted} [αντιχρ[ει]{.unclear}στος]{.greek-added}[1:7]{.aside}

[βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} [εαυτους]{.greek-omitted} [αυτου[ς]{.unclear}]{.greek-added} [ινα]{.unclear} μη [απολεσωμεν]{.greek-omitted} [απολεσητα[ι]{.unclear}]{.greek-added} α [ειργασαμεθα]{.greek-omitted} [ειρ[γασασθα]{.unclear}ι]{.greek-added} αλλα [μ]{.unclear}ισθον πληρη [απολαβωμεν]{.greek-omitted} [απ[ολαβη]{.greek-supplied}ται]{.greek-added}[1:8]{.aside}

[π]{.unclear}ας ο [παραβαινων]{.greek-omitted} [προαγω[ν]{.unclear}]{.greek-added} [κα]{.unclear}ι [μη]{.unclear} [μενων]{.greek-omitted} [[μα]{.unclear}[ι]{.greek-supplied}νων]{.greek-added} ε[ν]{.unclear} τη διδαχη τ[ου]{.unclear} [χριστου]{.greek-abbr} [θεον]{.greek-omitted} [[θν]{.unclear}]{.greek-added} ουκ εχ[ει]{.unclear} [ο]{.unclear} [μεν]{.unclear}ων [εν]{.unclear} τη [δι]{.unclear}[δαχη]{.greek-supplied} [του]{.greek-omitted} [χριστου]{.greek-omitted} [ουτος]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [εχει]{.greek-omitted}[1:9]{.aside}

