---
title: "Collation of Byz^RP^ vs 20233 (233)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 233 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20233).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 233                                   	| λογος                              	|
| 233 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 233 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 233               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 233                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 233 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 233                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 2

[οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [εν]{.greek-omitted} [βηθλεεμ]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} ουτως γαρ γεγραπται δια του προφητου[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ου[δ]{.unclear}αμως ελαχιστη ει εν τοις ηγεμοσιν ιουδα εκ σου γαρ ε[ξ]{.unclear}ελευσεται ηγουμενος [οστις]{.greek-omitted} [οστης]{.greek-added} ποιμανει τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους ηκριβωσεν παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτ[ους]{.unclear} εις βηθλεεμ [ει]{.unclear}πεν [[αυτοις]{.unclear}]{.greek-added} [πο]{.unclear}ρευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω [αυ]{.unclear}τω[2:8]{.aside}

οι δε [ακου]{.greek-supplied}σαντες του βασ[ι]{.unclear}λεως επορευθησαν και ιδου [ο]{.greek-omitted} αστηρ ον [ειδον]{.greek-omitted} [ιδων]{.greek-added} εν [τη]{.greek-supplied} [ανατολη]{.greek-supplied} [προ]{.greek-supplied}ηγεν [αυ]{.unclear}τους εως ελ[θ]{.unclear}ων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον α[στε]{.unclear}ρα εχαρησαν χαραν μεγαλην σφοδρα[2:10]{.aside}

και [ελθοντες]{.greek-omitted} [ελθωντες]{.greek-added} εις την οικιαν [ειδον]{.greek-omitted} [ιδο[ν]{.unclear}]{.greek-added} [το]{.unclear} παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσ[εκυ]{.unclear}[νησαν]{.unclear} [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ανοιξ[αντες]{.greek-supplied} τους θησαυρους αυτων προσηνεγκαν αυτω [δω]{.greek-added} [δωρα]{.greek-omitted} [χρυσον]{.greek-omitted} [και]{.greek-omitted} [λιβανον]{.greek-omitted} [και]{.greek-omitted} [σμυρναν]{.greek-omitted}[2:11]{.aside}

[ρα]{.greek-added} [και]{.greek-omitted} [ελθοντες]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [ειδον]{.greek-omitted} [το]{.greek-omitted} [παιδιον]{.greek-omitted} [μετα]{.greek-omitted} [μαριας]{.greek-omitted} [της]{.greek-omitted} [μητρος]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [πεσοντες]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ανοιξαντες]{.greek-omitted} [τους]{.greek-omitted} [θησαυρους]{.greek-omitted} [αυτων]{.greek-omitted} [προσηνεγκαν]{.greek-omitted} [αυτω]{.greek-omitted} [δωρα]{.greek-omitted} χρυσον και λιβανον και σμυρναν[2:11 | instance no. 2]{.aside}

και [χρηματισθεντες]{.greek-omitted} [χριματισθεντες]{.greek-added} κατ οναρ μη ανακαμψαι προς ηρωδην δι [αλλης]{.greek-omitted} [αλης]{.greek-added} οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδο[υ]{.unclear} αγγελος [κυριου]{.greek-abbr} [φαινεται]{.greek-omitted} [κατ]{.greek-supplied} [ο]{.greek-supplied}ναρ [φαι[νεται]{.greek-supplied}]{.greek-added} [τω]{.greek-supplied} ιωσηφ λεγων εγερθεις παραλαβε το πα[ι]{.unclear}διον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπ[ω]{.unclear} σοι μελλει γαρ ηρωδης ζητειν το παιδιον [του]{.unclear} [απολεσαι]{.greek-omitted} [απολεσε]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added}[2:13]{.aside}

[ο]{.greek-supplied} [δε]{.greek-supplied} [εγερθ]{.greek-supplied}εις παρελαβεν [το]{.unclear} [παιδιον]{.unclear} κ[αι]{.unclear} την [μητερα]{.greek-abbr} [αυτου]{.unclear} νυκτος και [ανεχω]{.unclear}ρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο [του]{.greek-omitted} [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκα[λεσ]{.unclear}α τον [υιον]{.greek-abbr} μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι [ενεπαιχθη]{.greek-omitted} [ενεπεχθη]{.greek-added} υπο των μαγων εθυμωθη λιαν και αποστειλας ανειλεν παντας τους παιδας τους εν βηθ[λεε]{.unclear}μ και εν πασιν τοις οριοις αυτης απο διετους και κατωτερω κατα [των]{.greek-added} [τον]{.corr} χρονον ον ηκριβωσεν παρα των μαγων[2:16]{.aside}

τοτε [επλη]{.greek-added} [επληρωθη]{.greek-omitted} [το]{.greek-omitted} [ρηθεν]{.greek-omitted} [υπο]{.greek-omitted} [ιερεμιου]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [λεγοντος]{.greek-omitted}[2:17]{.aside}

[ρω[θ]{.unclear}η]{.greek-added} [τοτε]{.greek-omitted} [επληρωθη]{.greek-omitted} το ρηθεν υπο ιερεμιου του προφητου λεγοντος[2:17 | instance no. 2]{.aside}

φωνη εν [ραμα]{.greek-omitted} [ρεμα]{.greek-added} ηκουσθη θρηνος και κλαυθμος και οδυρμος [πολυς]{.greek-omitted} [πολλοις]{.greek-added} [ραχηλ]{.greek-omitted} [ραχιηλ]{.greek-added} κλαιουσα τα τεκνα αυτης και ουκ ηθελεν παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

τελευτησαντος δε του ηρωδο[υ]{.unclear} ιδου αγγελος [κυριου]{.greek-abbr} [κατ]{.unclear} [ο]{.unclear}ναρ φαινεται τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων εγερ[θ]{.unclear}εις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} τεθνηκασ[ι]{.unclear}ν γαρ οι ζητουντες την [ψ]{.unclear}υχην του παι[δ]{.unclear}ιου[2:20]{.aside}

ο δε εγερθεις παρελαβεν το [παι]{.unclear}διον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει επι της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαια[ς]{.unclear}[2:22]{.aside}

και ελθων κατωκησεν εις [πολιν]{.greek-omitted} [πολην]{.greek-added} [λεγομε]{.greek-supplied}νην ναζαρετ [[ναζαρεθ]{.corr}]{.greek-added} οπως πληρωθη το ρηθεν δια των προφητων οτι [ναζωραιος]{.greek-omitted} [ναζοραιος]{.greek-added} κληθησεται[2:23]{.aside}

### Chapter 3

εν δε ταις η[μεραις]{.unclear} εκειναις [παραγι]{.unclear}νεται [[ο]{.greek-supplied}]{.greek-added} [ιωαννης]{.greek-supplied} [ο]{.greek-omitted} [βαπτιστης]{.greek-omitted} [κηρυσσων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted}[3:1]{.aside}

[εν]{.greek-omitted} [δε]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [εκειναις]{.greek-omitted} [παραγινεται]{.greek-omitted} [ιωαννης]{.greek-omitted} ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1 | instance no. 2]{.aside}

και λεγων [μετανοειτε]{.greek-omitted} [μετανοιται]{.greek-added} [ηγγικεν]{.greek-omitted} [ηγγηκεν]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

ουτος γαρ εστιν ο [ρηθεις]{.greek-omitted} [ριθεις]{.greek-added} υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας [ποιειτε]{.greek-omitted} [ποι[η]{.unclear}ται]{.greek-added} τας τριβους αυτου[3:3]{.aside}

αυτος δε ο ιωαννης ειχεν το ενδυμα αυτου α[π]{.unclear}ο τριχων καμηλου και ζωνην [δερματινην]{.greek-omitted} [δερματηνην]{.greek-added} περι την οσφυν αυτου η δε τροφη [ην]{.greek-added} αυτου [ην]{.greek-omitted} ακριδες και [μελι]{.greek-omitted} [μελη]{.greek-added} [αγριον]{.greek-omitted} [αγριων]{.greek-added}[3:4]{.aside}

τοτε εξεπορευετο προς αυτον ιεροσ[ο]{.unclear}λυμα και πασα [η]{.greek-omitted} ιουδαια και πασα η [περιχωρος]{.greek-omitted} [περιχορος]{.greek-added} του ιορδανου[3:5]{.aside}

και εβαπτ[ι]{.unclear}ζοντο εν τω ιορδανη [ποταμω]{.greek-added} υπ αυτου εξομολ[ο]{.unclear}γουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και [σαδδουκαιων]{.greek-omitted} [σαδουκαιων]{.greek-added} ερχομενους επι το βαπτισμα αυτου ειπεν αυτοις γε[ν]{.greek-supplied}[ν]{.unclear}ηματα εχιδνων τ[ις]{.unclear} [υμιν]{.greek-added} υπεδειξεν [υμιν]{.greek-omitted} φυγειν απο της μελλουσης [οργης]{.greek-omitted} [ορ]{.greek-added}[3:7]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [πολλους]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [και]{.greek-omitted} [σαδδουκαιων]{.greek-omitted} [ερχομενους]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [βαπτισμα]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [γεννηματα]{.greek-omitted} [εχιδνων]{.greek-omitted} [τις]{.greek-omitted} [υπεδειξεν]{.greek-omitted} [υμιν]{.greek-omitted} [φυγειν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} [οργης]{.greek-omitted} [γης]{.greek-added}[3:7 | instance no. 2]{.aside}

[ποιησατε]{.greek-omitted} [ποιησαται]{.greek-added} ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη [δοξητε]{.greek-omitted} [δοξηται]{.greek-added} [λεγειν]{.greek-omitted} [λεγων]{.greek-added} εν [εαυτοις]{.greek-omitted} [αιαυτοις]{.greek-added} [πατερα]{.greek-abbr} [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των [λιθων]{.greek-omitted} [λιθον]{.greek-added} [τουτων]{.greek-omitted} [τουτον]{.greek-added} εγειραι τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε [και]{.greek-omitted} η [αξινη]{.greek-omitted} [α[ξ]{.unclear}ηνη]{.greek-added} προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ [βαλλεται]{.greek-omitted} [βαλετε]{.greek-added}[3:10]{.aside}

εγω μεν βαπτιζω υμας εν [υδατι]{.greek-omitted} [υδατη]{.greek-added} εις μετανοιαν ο δε [οπισω]{.greek-omitted} [οπησω]{.greek-added} μου ερχομενος [ισχυροτερος]{.greek-omitted} [ισχυρωτερος]{.greek-added} μου εστιν ου ουκ ειμι ικανος τα υποδηματα [βαστασαι]{.greek-omitted} [βαστασε]{.greek-added} αυτος [υμας]{.greek-omitted} [ημας]{.greek-added} [βαπτισει]{.greek-omitted} [βαπτησει]{.greek-added} εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[3:11]{.aside}

ου το [πτυον]{.greek-omitted} [πτοιον]{.greek-added} εν [τη]{.greek-omitted} [τι]{.greek-added} χειρι αυτου και [διακαθαριει]{.greek-omitted} [καθαριει]{.greek-added} την αλωνα αυτου και συναξει τον [μεν]{.greek-added} σιτον αυτου εις την αποθηκην το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε [παραγινεται]{.greek-omitted} [παραγηνεται]{.greek-added} ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον ιωαννην του [βαπτισθηναι]{.greek-omitted} [βαπτησθηναι]{.greek-added} υπ αυτου[3:13]{.aside}

ο δε ιωαννης [διεκωλυεν]{.greek-omitted} [διεκωλυ]{.greek-added} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [εγω]{.greek-omitted} [χρειαν]{.greek-omitted} [εχω]{.greek-omitted} [υπο]{.greek-omitted} [σου]{.greek-omitted} [βαπτισθηναι]{.greek-omitted} [και]{.greek-omitted} [συ]{.greek-omitted} [ερχη]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted}[3:14]{.aside}

[εν]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιωαννης]{.greek-omitted} [διεκωλυεν]{.greek-omitted} αυτον λεγων εγω χρειαν εχω υπο σου [βαπτισθηναι]{.greek-omitted} [βαπτησθηναι]{.greek-added} και συ ερχη προς με[3:14 | instance no. 2]{.aside}

[αποκριθεις]{.greek-omitted} [αποκριθης]{.greek-added} δε ο [ιησους]{.greek-abbr} ειπεν προς αυτον αφες [αρτι]{.greek-omitted} [αρτη]{.greek-added} ουτως γαρ πρεπον [εστιν]{.greek-omitted} [εστην]{.greek-added} ημιν πληρωσαι [[πληρωσε]{.corr}]{.greek-added} πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και [βαπτισθεις]{.greek-omitted} [βαπτησθεις]{.greek-added} [δε]{.greek-added} ο [ιησους]{.greek-abbr} ανεβη [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} απο του υδατος και ιδου [ανεωχθησαν]{.greek-omitted} [ανεωγθησαν]{.greek-added} αυτω οι [ουρανοι]{.greek-abbr} και ειδεν το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} καταβαινο[ν]{.unclear} ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[3:17]{.aside}

### Chapter 4

τοτε [ανηχθη]{.greek-added} ο [ιησους]{.greek-abbr} [ανηχθη]{.greek-omitted} εις την ερημον υπο του [πνευματος]{.greek-abbr} πειρασθηναι υπο του διαβολου[4:1]{.aside}

και [νηστευσας]{.greek-omitted} [νιστευσας]{.greek-added} ημερας τεσσαρακοντα και νυκτας τεσσαρακοντα υστερον [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added}[4:2]{.aside}

και προσελθων αυτω ο πειραζων ειπεν ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι γενωνται[4:3]{.aside}

ο δε αποκριθεις ειπεν [γεγραπται]{.greek-omitted} [γεγραπτε]{.greek-added} ουκ επ αρτω μονω ζησεται [ανθρωπος]{.greek-abbr} αλλ [ε]{.greek-added} [επι]{.greek-omitted} [παντι]{.greek-omitted} [ρηματι]{.greek-omitted} [εκπορευομενω]{.greek-omitted} [δια]{.greek-omitted} [στοματος]{.greek-omitted} [θεου]{.greek-omitted}[4:4]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [γεγραπται]{.greek-omitted} [ουκ]{.greek-omitted} [επ]{.greek-omitted} [αρτω]{.greek-omitted} [μονω]{.greek-omitted} [ζησεται]{.greek-omitted} [ανθρωπος]{.greek-omitted} [αλλ]{.greek-omitted} [επι]{.greek-omitted} [πι]{.greek-added} [παντι]{.greek-omitted} [παντη]{.greek-added} ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4 | instance no. 2]{.aside}

τοτε παραλα[μβ]{.unclear}ανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} βαλε [σεαυτον]{.greek-omitted} [σαιαυτον]{.greek-added} κατω [γεγραπται]{.greek-omitted} [γεγραπτε]{.greek-added} γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων αρουσιν σε μηποτε προσκοψης προς [λιθον]{.unclear} τον ποδα σου[4:6]{.aside}

[ε]{.unclear}φη αυτω [ο]{.unclear} [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} [παλην]{.greek-added} γεγραπται ουκ [εκπειρασεις]{.greek-omitted} [εκπειρασης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σ[ου]{.unclear}[4:7]{.aside}

[π]{.unclear}αλιν παραλαμβανει αυτον ο διαβολος εις ορο[ς]{.unclear} [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} λιαν και δεικνυσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα [σοι]{.greek-added} παντα [σοι]{.greek-omitted} δωσω εαν πεσων [προσκυνησης]{.greek-omitted} [προσκυνησεις]{.greek-added} μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε [οπισω]{.greek-omitted} [μου]{.greek-omitted} σατανα γεγραπται γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω [μονω]{.greek-omitted} [μονο]{.greek-added} λατρευσεις[4:10]{.aside}

τοτε [αφιησιν]{.greek-omitted} [αφειησιν]{.greek-added} αυτον ο διαβολος και ιδου αγγελοι προσηλθον κα[ι]{.unclear} δ[ιη]{.unclear}κο[νουν]{.greek-supplied} [αυτω]{.greek-supplied}[4:11]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} [οτι]{.greek-omitted} [οτη]{.greek-added} ιωαννης [παρεδοθη]{.greek-omitted} [παρεδωθη]{.greek-added} ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} την [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ελθων κατωκησεν εις [καπερναουμ]{.greek-omitted} [καφαρναουμ]{.greek-added} την παραθαλασσιαν εν οριοις [ζαβουλων]{.greek-omitted} [ζαβουλ[ο]{.unclear}ν]{.greek-added} και [νεφθαλειμ]{.greek-omitted} [νεφθαλιμ]{.greek-added}[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη [νεφθαλειμ]{.greek-omitted} [νεφθαλιμ]{.greek-added} οδο[ν]{.unclear} θαλασσης περαν του ιορδανου [γαλιλαια]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted}[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} φως [μεγα]{.greek-supplied} [και]{.greek-supplied} [τοις]{.greek-supplied} καθημενοις εν χωρα και σκια θανατου φω[ς]{.unclear} ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν [μετανοειτε]{.greek-omitted} [μετανοειται]{.greek-added} [ηγγικεν]{.greek-omitted} [ηγγηκε[ν]{.greek-supplied}]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} δυο αδελφους [σιμωνα]{.greek-omitted} [σημωνα]{.greek-added} τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας [αμφιβληστρον]{.greek-omitted} [α[μ]{.unclear}φηβληστρον]{.greek-added} εις την θαλασσαν [ησαν]{.greek-omitted} [εισαν]{.greek-added} γαρ αλιεις[4:18]{.aside}

και λεγει α[υ]{.unclear}τοις δευτε οπ[ι]{.unclear}σω μου και ποιησω υμας αλιεις [ανθρωπων]{.greek-abbr}[4:19]{.aside}

### Chapter 5

[λεγω]{.greek-omitted} [γαρ]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [περισσευση]{.greek-omitted} [η]{.greek-omitted} [δικαιοσυνη]{.greek-omitted} [υμων]{.greek-omitted} [πλειον]{.greek-omitted} [των]{.greek-omitted} [ταιων]{.greek-added} [γραμματεων]{.greek-omitted} και φαρισαιων ου μη [εισελθητε]{.greek-omitted} [εισελθηται]{.greek-added} εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

[ηκουσατε]{.greek-omitted} [ηκουσαται]{.greek-added} [οτι]{.greek-omitted} [οτη]{.greek-added} [ερρεθη]{.greek-omitted} [ερεθη]{.greek-added} τοις αρχαιοις ου [φονευσεις]{.greek-omitted} [φωνευσης]{.greek-added} ος δ αν [φονευση]{.greek-omitted} [φωνευσει]{.greek-added} ενοχος εσται τη [κρισει]{.greek-omitted} [κριση]{.greek-added}[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο [οργιζομενος]{.greek-omitted} [ορ[γ]{.unclear}ιζωμενος]{.greek-added} τω αδελφω αυτου εικη ενοχος εσται τη [κρισει]{.greek-omitted} [κριση]{.greek-added} ος δ αν ειπη τω αδελφω αυτου [ρακα]{.greek-omitted} [ρακκα]{.greek-added} ενοχος εσται [τω]{.greek-omitted} [το]{.greek-added} συνεδριω ος δ αν [ειπη]{.greek-omitted} [ειπι]{.greek-added} [τω]{.greek-added} [αδελφω]{.greek-added} [αυτου]{.greek-added} μωρε ενοχος εσται εις την [γεενναν]{.greek-omitted} [γεενα]{.greek-added} του πυρος[5:22]{.aside}

εαν ουν προσφερη[ς]{.unclear} το δωρον σου ε[πι]{.unclear} το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} μνησθης οτι [ο]{.greek-omitted} αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον [διαλλαγηθι]{.greek-omitted} [διαλαγηθη]{.greek-added} τω αδελφω σου και τοτε [ελθων]{.greek-omitted} προσφερε το δωρον σου[5:24]{.aside}

[ισθι]{.greek-omitted} [ισθη]{.greek-added} [ευνοων]{.greek-omitted} [ευνωον]{.greek-added} [τω]{.greek-omitted} [το]{.greek-added} αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου μηποτε σε παραδω ο αντιδικος [τω]{.greek-omitted} [το]{.greek-added} κριτη και ο κριτης σε παραδω τω υπ[ηρε]{.unclear}τη και εις φυλακην βληθ[η]{.unclear}ση[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως [αν]{.greek-omitted} [οτου]{.greek-added} αποδως τον εσχατον κοδραντην[5:26]{.aside}

[ηκουσατε]{.greek-omitted} [ηκουσαται]{.greek-added} οτι ερρεθη [τοις]{.greek-added} [αρχαιοις]{.greek-added} ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα προς το [επιθυμησαι]{.greek-omitted} [επιθυμησε]{.greek-added} αυτην [ηδη]{.greek-omitted} [ιδει]{.greek-added} εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιος [σκανδαλιζει]{.greek-omitted} [σκανδαληζει]{.greek-added} σε εξελε [α]{.unclear}υτον και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολειται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις [γεενναν]{.greek-omitted} [γεεναν]{.greek-added}[5:29]{.aside}

και ει η δεξια σου χειρ [σκανδαλιζει]{.greek-omitted} [σκανδαληζη]{.greek-added} σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολειται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις [γεενναν]{.greek-omitted} [γεεναν]{.greek-added}[5:30]{.aside}

ερρεθη δε οτι ος [αν]{.greek-omitted} [εαν]{.greek-added} [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου δοτω [αυτη]{.greek-omitted} [αυτιν]{.greek-added} αποστασιον[5:31]{.aside}

εγω δε λεγω υμιν οτι [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} [πας]{.greek-added} [ο]{.greek-added} [απολυων]{.greek-added} την γυναικα αυτου παρεκτος λογου [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} ποιει αυτην μοιχα[σ]{.unclear}θαι και ος [εαν]{.greek-omitted} [αν]{.greek-added} [απο]{.greek-added} [απολελυμενην]{.greek-omitted} [γαμηση]{.greek-omitted} [μοιχαται]{.greek-omitted}[5:32]{.aside}

### Chapter 6

[[ο]{.unclear}φελε[τ]{.unclear}αις]{.greek-added} [και]{.greek-omitted} [αφες]{.greek-omitted} [ημιν]{.greek-omitted} [τα]{.greek-omitted} [οφειληματα]{.greek-omitted} ημων [ως]{.greek-omitted} [και]{.greek-omitted} [ημεις]{.greek-omitted} [αφιεμεν]{.greek-omitted} [τοις]{.greek-omitted} [οφειλεταις]{.greek-omitted} [ημων]{.greek-omitted}[6:12]{.aside}

και μη εισενεγκης ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βα[σιλεια]{.unclear} [και]{.unclear} [η]{.unclear} [δυνα]{.unclear}μις και η [δυναμις]{.greek-added} [και]{.greek-added} [η]{.greek-added} δοξα [εις]{.unclear} τους αιωνας αμην[6:13]{.aside}

εαν γαρ [αφητε]{.greek-omitted} [αφηται]{.greek-added} τοις [ανθρωποις]{.greek-abbr} τα [π]{.unclear}αραπτω[μ]{.unclear}ατα αυτων [αφησει]{.greek-omitted} [αφηεισει]{.greek-added} και υμιν ο [πατηρ]{.greek-abbr} υμων ο ουρανιος[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων [αφησει]{.greek-omitted} [αφιησει]{.greek-added} τα παραπτωματα υμων[6:15]{.aside}

[ο]{.unclear}ταν [δ]{.unclear}ε [νηστευητε]{.greek-omitted} [νισ[τευ]{.unclear}ετε]{.greek-added} μη [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ωσπερ οι υποκριται σκυθρωποι αφανιζουσιν γαρ τα προσωπ[α]{.unclear} αυτων οπως φανωσιν τοις [ανθρωποις]{.greek-abbr} [νηστευοντες]{.greek-omitted} [νιστευοντες]{.greek-added} αμην λεγω υμιν [οτι]{.greek-omitted} [απε]{.unclear}χουσιν τον μισθον αυτων[6:16]{.aside}

συ δε [νηστευων]{.greek-omitted} [νιστευον]{.greek-added} [αλειψαι]{.greek-omitted} [αλειψε]{.greek-added} σου την κεφαλην και το προσωπον σου [ν]{.unclear}ι[ψ]{.unclear}αι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} [νηστευων]{.greek-omitted} [νιστευων]{.greek-added} αλλα [τω]{.greek-omitted} [το]{.greek-added} [πατρι]{.greek-abbr} σου τω [εν]{.unclear} τω κρυπτω [και]{.unclear} ο [πατηρ]{.greek-abbr} σου ο βλ[επω]{.unclear}ν εν τω κρ[υπτω]{.unclear} αποδ[ωσει]{.greek-supplied} [σοι]{.greek-supplied} [[εν]{.greek-supplied}]{.greek-added}[6:18]{.aside}

[οπως]{.greek-omitted} [μη]{.greek-omitted} [φανης]{.greek-omitted} [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted} [νηστευων]{.greek-omitted} [αλλα]{.greek-omitted} τω [φ[α]{.unclear}νερω]{.greek-added} [πατρι]{.greek-omitted} [σου]{.greek-omitted} [τω]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κρυπτω]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [σου]{.greek-omitted} [ο]{.greek-omitted} [βλεπων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κρυπτω]{.greek-omitted} [αποδωσει]{.greek-omitted} [σοι]{.greek-omitted}[6:18 | instance no. 2]{.aside}

μη [θησαυριζετε]{.greek-omitted} [θησαυριζεται]{.greek-added} υμι[ν]{.unclear} [θ]{.unclear}ησαυρους επι της γης οπου σης και [βρωσις]{.greek-omitted} [βρωσης]{.greek-added} αφανιζει και οπου [κλεπται]{.greek-omitted} [κλεπτε]{.greek-added} [δ]{.unclear}ι[ορ]{.unclear}υ[σσ]{.unclear}ουσιν και κλεπτουσιν[6:19]{.aside}

[θησαυριζετε]{.greek-omitted} [θησαυριζεται]{.greek-added} δε υμιν θησαυρους εν [ουρανω]{.greek-abbr} οπου ουτε σης ουτε [βρωσις]{.greek-omitted} [βρωσης]{.greek-added} αφανιζει και οπου κλεπται ου διορυσσουσιν ουδε κλεπτουσιν[6:20]{.aside}

οπου γαρ [εστιν]{.greek-omitted} [εστ[η]{.unclear}ν]{.greek-added} ο θησαυρος υμων εκει εσται και η καρδια υμων[6:21]{.aside}

ο λυχνος του σω[μα]{.unclear}τος εστιν ο οφθαλμος εαν ουν [η]{.greek-added} ο οφθαλμος σου απλου[ς]{.unclear} [η]{.greek-omitted} ολον το σωμα [σου]{.unclear} [φωτεινον]{.greek-omitted} [φωτηνον]{.greek-added} [εσται]{.greek-omitted} [εστην]{.greek-added}[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου [σκοτεινον]{.greek-omitted} [σκοτηνον]{.greek-added} εσται ει ουν το φω[ς]{.unclear} το εν σοι σκοτος εστιν το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται δυσιν κυριοις δουλευειν η γαρ τον ενα [μισησει]{.greek-omitted} [μησεισι]{.greek-added} και τον ετερον αγαπησει η ενος ανθεξεται και του ετερου καταφρονησει ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} [θεω]{.greek-abbr} δουλευειν και μαμωνα[6:24]{.aside}

δια τουτο λεγω υμιν μη [μεριμνατε]{.greek-omitted} [μεριμνησιτε]{.greek-added} τη ψυχη υμων [τι]{.greek-omitted} [τη]{.greek-added} [φαγητε]{.greek-omitted} [φαγηται]{.greek-added} και [τι]{.greek-omitted} [πιητε]{.greek-omitted} [μηδε]{.greek-omitted} [τω]{.greek-omitted} [σωματι]{.greek-omitted} [υμων]{.greek-omitted} [τι]{.greek-omitted} [ενδυσησθε]{.greek-omitted} [ουχι]{.greek-omitted} [η]{.greek-omitted} [ψυχη]{.greek-omitted} [πλειον]{.greek-omitted} [εστιν]{.greek-omitted} [της]{.greek-omitted} [τη]{.greek-added} [πι]{.greek-added} [τροφης]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ενδυματος]{.greek-omitted}[6:25]{.aside}

[[ηται]{.unclear}]{.greek-added} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [μη]{.greek-omitted} [μεριμνατε]{.greek-omitted} [τη]{.greek-omitted} [ψυχη]{.greek-omitted} [υμων]{.greek-omitted} [τι]{.greek-omitted} [φαγητε]{.greek-omitted} [και]{.greek-omitted} [τι]{.greek-omitted} [πιητε]{.greek-omitted} μηδε [τω]{.greek-omitted} [το]{.greek-added} σωματι υμων [τι]{.greek-omitted} [τη]{.greek-added} [ενδυσησθε]{.greek-omitted} [ενδυσησθαι]{.greek-added} ουχι η ψυχη πλειον εστιν της τροφης και το σωμα του ενδυματος[6:25 | instance no. 2]{.aside}

[εμβλεψατε]{.greek-omitted} [εμβλεψαται]{.greek-added} εις τα πετεινα του ουρανου οτι ου σπ[ει]{.unclear}ρουσιν ουδε θερ[ι]{.unclear}ζουσιν ουδε συναγουσιν εις αποθηκας και ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} [τρεφει]{.greek-omitted} [τρεφη]{.greek-added} αυτα ουχ υμεις μαλλον [διαφερετε]{.greek-omitted} [διαφερεται]{.greek-added} α[υτων]{.unclear}[6:26]{.aside}

τις δε ε[ξ]{.unclear} υμων [μεριμνων]{.greek-omitted} [μεριμν[ο]{.unclear}ν]{.greek-added} [δυναται]{.greek-omitted} [δυνατε]{.greek-added} προσθ[ει]{.unclear}ναι επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι [μεριμνατε]{.greek-omitted} [μεριμναται]{.greek-added} [καταμαθετε]{.greek-omitted} [κα[τα]{.unclear}μα[θεται]{.unclear}]{.greek-added} τα κρινα το[υ]{.unclear} αγρου πως αυξανει ου κοπια ουδε [νηθει]{.greek-omitted} [νηθη]{.greek-added}[6:28]{.aside}

λεγω δε υμιν οτι ουδε [σολομων]{.greek-omitted} [σολωμων]{.greek-added} ε[ν]{.unclear} [παση]{.greek-omitted} [πασει]{.greek-added} τη δοξη [αυ]{.unclear}του περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις [κλιβανον]{.greek-omitted} [κληβανον]{.greek-added} [βαλλομενον]{.greek-omitted} [βαλομενον]{.greek-added} ο [θεος]{.greek-abbr} ουτως αμφι[ε]{.unclear}ννυσιν ου πολλω μαλλον υμας [ολιγοπιστοι]{.greek-omitted} [ολιγωπιστοι]{.greek-added}[6:30]{.aside}

μη ουν [μεριμνησητε]{.greek-omitted} [μεριμνησειται]{.greek-added} λεγοντες τι φαγωμεν η τι πιωμεν η τι περιβαλωμεθα[6:31]{.aside}

[παντα]{.greek-omitted} [γαρ]{.greek-omitted} [ταυτα]{.greek-omitted} [τα]{.greek-omitted} [ταυ]{.greek-added} [εθνη]{.greek-omitted} [επιζητει]{.greek-omitted} [οιδεν]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [ουρανιος]{.greek-omitted} [οτι]{.greek-omitted} [χρηζετε]{.greek-omitted} [τουτων]{.greek-omitted} [απαντων]{.greek-omitted}[6:32]{.aside}

[τα]{.greek-added} [γαρ]{.greek-added} παντα [γαρ]{.greek-omitted} [ταυτα]{.greek-omitted} τα εθνη [επιζητει]{.greek-omitted} [επιζητη]{.greek-added} οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} οτι [χρηζετε]{.greek-omitted} [χριζεται]{.greek-added} τουτων απαντων[6:32 | instance no. 2]{.aside}

[ζητειτε]{.greek-omitted} [ζητηται]{.greek-added} δε πρωτον την βασιλειαν του [θεου]{.greek-abbr} και τ[ην]{.unclear} [δικαιοσυ]{.unclear}νην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν μεριμνησητε εις την αυριον η γαρ αυριον [μεριμνησει]{.greek-omitted} [μερημνησει]{.greek-added} τα εαυτης αρκετον τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

μη [κρινετε]{.greek-omitted} [κρινεται]{.greek-added} ινα μη κριθητε[7:1]{.aside}

[εν]{.unclear} [ω]{.unclear} γαρ κριμα[τι]{.greek-supplied} [κρινετε]{.greek-omitted} [κρινεται]{.greek-added} [κριθησεσθε]{.greek-omitted} [κριθ[ησεσ]{.unclear}θαι]{.greek-added} και εν ω μετρω [μετρειτε]{.greek-omitted} [μετρειτ[αι]{.unclear}]{.greek-added} [μετρηθησεται]{.greek-omitted} [[α]{.unclear}ντι[μ]{.unclear}ετρ[η]{.unclear}θησετε]{.greek-added} υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος το εν τω οφθαλμω του αδελφου σου την δε [δοκον]{.greek-added} [την]{.greek-added} εν τω [σω]{.greek-omitted} οφθαλμω [δοκον]{.greek-omitted} [σου]{.greek-added} ου κ[α]{.unclear}τανοεις[7:3]{.aside}

[η]{.unclear} [πως]{.unclear} [[λεγεις]{.unclear}]{.greek-added} [ερεις]{.greek-omitted} [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [σου]{.greek-omitted} [αφες]{.greek-omitted} εκβαλω το καρφος [απο]{.greek-omitted} [εκ]{.greek-added} του οφθαλμου σου και ιδου [η]{.greek-omitted} [ι]{.greek-added} δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

### Chapter 8

εισελθοντι δε αυτω εις [καπερναουμ]{.greek-omitted} [καφαρναουμ]{.greek-added} προσηλθεν αυτ[ω]{.unclear} εκατονταρχος [πα]{.unclear}ρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου βεβληται εν τη [οικια]{.greek-omitted} [οικεια]{.greek-added} [παραλυτικος]{.greek-omitted} [παραλυτηκος]{.greek-added} [δεινως]{.greek-omitted} [[δ]{.unclear}ινως]{.greek-added} βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκρι[θεις]{.unclear} [ο]{.unclear} [ε]{.unclear}κατον[τα]{.unclear}ρχος εφη [κυριε]{.greek-abbr} ουκ [ειμι]{.greek-omitted} [ει[μ]{.unclear}η]{.greek-added} ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν εχων υπ [εμαυτον]{.greek-omitted} [εμαυτων]{.greek-added} στρατιωτας και λεγω τουτω πορευθητι και [πορευεται]{.greek-omitted} [[π]{.unclear}ορε[υ]{.unclear}ετε]{.greek-added} και [αλλω]{.greek-omitted} [αλλο]{.greek-added} ερχου και ερχεται και τω δουλω μου ποιησον [τουτο]{.greek-omitted} [τουτω]{.greek-added} και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} εθαυμασεν και ειπεν τοις ακολουθουσιν [αυτω]{.greek-added} αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην [πιστιν]{.greek-omitted} [πιστην]{.greek-added} [ευρον]{.greek-omitted} [ηυρον]{.greek-added}[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων ηξουσιν και [ανακλιθησονται]{.greek-omitted} [ανακληθησονται]{.greek-added} μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε [υ]{.greek-added} [υιοι]{.greek-omitted} [της]{.greek-omitted} [βασιλειας]{.greek-omitted} [εκβληθησονται]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [σκοτος]{.greek-omitted} [το]{.greek-omitted} [εξωτερον]{.greek-omitted} [εκει]{.greek-omitted} [εσται]{.greek-omitted} [ο]{.greek-omitted} [κλαυθμος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [βρυγμος]{.greek-omitted} [των]{.greek-omitted} [οδοντων]{.greek-omitted}[8:12]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [υιοι]{.greek-omitted} [ιοι]{.greek-added} της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12 | instance no. 2]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} [τω]{.greek-omitted} [το]{.greek-added} εκατονταρχη υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο πα[ις]{.unclear} [α]{.unclear}υτου εν τη ωρα εκεινη[8:13]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και εξεβαλεν τα [πνευματα]{.greek-abbr} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το [ρηθεν]{.greek-omitted} [ριθεν]{.greek-added} δια ησαιου του προφητ[ου]{.unclear} λε[γον]{.unclear}τος [αυ]{.unclear}τος τας ασθενειας ημων ελαβεν και τας νοσους εβαστασεν[8:17]{.aside}

[ιδων]{.greek-omitted} [ιδον]{.greek-added} δε ο [ιησους]{.greek-abbr} πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και π[ρο]{.unclear}σελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν α[π]{.unclear}ερχη[8:19]{.aside}

και λεγει [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αι]{.greek-omitted} [αλωπεκες]{.greek-omitted} [φωλεους]{.greek-omitted} [εχουσιν]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [κατασκηνωσεις]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ουκ]{.greek-omitted} [εχει]{.greek-omitted} [που]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [κλινη]{.greek-omitted}[8:20]{.aside}

[βη]{.greek-added} [και]{.greek-omitted} [ιδου]{.greek-omitted} [πασα]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εις]{.greek-omitted} [συναντησιν]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [και]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [παρεκαλεσαν]{.greek-omitted} [οπως]{.greek-omitted} [μεταβη]{.greek-omitted} απο των ορι[ω]{.unclear}ν αυτων[8:34]{.aside}

### Chapter 9

[κ]{.unclear}αι εμβας εις το πλοιον διε[π]{.unclear}ε[ρ]{.unclear}ασεν και ηλθεν εις την ιδιαν [πολιν]{.greek-omitted} [πολην]{.greek-added}[9:1]{.aside}

κ[αι]{.unclear} [ιδου]{.greek-supplied} προσεφερ[ον]{.unclear} [αυ]{.unclear}τω [παραλυτικον]{.greek-omitted} [παραλυτηκον]{.greek-added} επι κλινης [β]{.unclear}εβλημε[ν]{.unclear}ον και ιδων ο [ιησους]{.greek-abbr} την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} αυτ[ω]{.unclear}ν ειπεν τω [παραλυτικω]{.greek-omitted} [παραλυτ[η]{.unclear}κω]{.greek-added} θαρσει τεκνον [αφεωνται]{.greek-omitted} [αφαιονται]{.greek-added} σο[ι]{.greek-supplied} [α]{.unclear}ι αμαρτιαι σου[9:2]{.aside}

και ιδου [τινες]{.greek-omitted} [τιναις]{.greek-added} των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ειπον [εν]{.unclear} [εαυτοις]{.unclear} [ουτος]{.greek-omitted} [ου[τ]{.unclear}ως]{.greek-added} βλασφημει[9:3]{.aside}

και ιδων ο [ιησους]{.greek-abbr} τας εν[θ]{.unclear}υμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατ[ι]{.unclear}]{.greek-added} [τι]{.greek-omitted} [υ]{.unclear}[μεις]{.unclear} [ενθυμεισθε]{.greek-omitted} [[ε]{.unclear}νθυμεισ[θα]{.unclear}ι]{.greek-added} πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} ειπειν αφεωνται σου αι αμαρτιαι [σου]{.greek-added} η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[9:5]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ιδειτε]{.greek-added} οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την [κλινην]{.greek-omitted} [κληνην]{.greek-added} και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον α[υ]{.unclear}του[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυ[την]{.greek-supplied} τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκ[εινω]{.unclear}]{.greek-added} παραγων ο [ιησους]{.greek-abbr} [εκει]{.unclear}θεν [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [ανθρωπον]{.greek-abbr} [καθημενον]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [τελωνιον]{.greek-omitted} [ματθαιον]{.greek-omitted} [λεγομενον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [αναστας]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted}[9:9]{.aside}

[και]{.greek-omitted} [παραγων]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εκειθεν]{.greek-omitted} [ειδεν]{.greek-omitted} [ανθρωπον]{.greek-omitted} [καθ]{.unclear}ημενον επι [το]{.greek-supplied} [τ]{.unclear}ε[λω]{.unclear}νιον [ματθαιον]{.greek-omitted} [μαθθαιον]{.greek-added} λεγομενον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[9:9 | instance no. 2]{.aside}

και εγενετο α[υ]{.unclear}τ[ου]{.greek-supplied} ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων εσθιει ο διδασκαλ[ος]{.unclear} υμων[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν ε[χο]{.unclear}υσιν οι ισχυοντ[ες]{.unclear} ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες [δε]{.unclear} μαθετε τι εστιν ελεον θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται ιωαννου λεγοντες δια τι ημει[ς]{.unclear} και οι φαρισαιοι [νηστευομεν]{.greek-omitted} [νιστευομεν]{.greek-added} πολλα οι δε μαθηται σου ου [νηστευουσιν]{.greek-omitted} [νιστευουσιν]{.greek-added}[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος πενθειν εφ ο[σ]{.unclear}ον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απ[α]{.unclear}ρ[θη]{.unclear} απ αυτων ο νυμφιος και τ[οτε]{.unclear} [νηστευσουσιν]{.greek-omitted} [νιστευσωσιν]{.greek-added}[9:15]{.aside}

### Chapter 10

[ο]{.greek-omitted} [ευρων]{.greek-omitted} [την]{.greek-omitted} [ψυχην]{.greek-omitted} [αυτου]{.greek-omitted} [απολεσει]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [απολεσας]{.greek-omitted} [λεσας]{.greek-added} την ψυχην [αυ]{.unclear}του ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο [δεχομενος]{.greek-supplied} προφητην εις ονομα προφητου [μισθον]{.greek-omitted} [μησθον]{.greek-added} προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου [μισθον]{.greek-omitted} [μησθον]{.greek-added} δικαιου ληψεται[10:41]{.aside}

και ος εαν [ποτιση]{.greek-omitted} [ποτησει]{.greek-added} ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθη[τ]{.unclear}ου αμην λεγω υμιν ου μη απολεση τον [μισθον]{.greek-omitted} [μησθον]{.greek-added} αυτου[10:42]{.aside}

### Chapter 11

και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} [οτε]{.greek-omitted} [ο[τι]{.unclear}]{.greek-added} ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα [μαθηταις]{.greek-omitted} [μαθητες]{.greek-added} αυτου μετεβη εκειθεν του [κηρυσσει[ν]{.unclear}]{.greek-added} [και]{.greek-added} διδασκειν [και]{.greek-omitted} [κηρυσσειν]{.greek-omitted} εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε ιωαννης ακουσας εν τω [δεσμωτηριω]{.greek-omitted} [δεσμοτηριω]{.greek-added} τα εργα του [χριστου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} πεμψας [δυο]{.greek-omitted} [δια]{.greek-added} των μαθητων αυτου[11:2]{.aside}

ειπεν [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες [απαγγειλατε]{.greek-omitted} [απαγγειλαται]{.greek-added} ιωαννη α [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} και [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added}[11:4]{.aside}

τυφλοι αναβλεπουσιν και χωλοι περιπατου[σι]{.unclear}ν [λεπροι]{.greek-omitted} [καθαριζονται]{.greek-omitted} [και]{.greek-omitted} [κωφοι]{.greek-omitted} [ακουουσιν]{.greek-omitted} [νεκροι]{.greek-omitted} [εγειρονται]{.greek-omitted} [και]{.greek-omitted} [πτωχοι]{.greek-omitted} [ευαγγελιζονται]{.greek-omitted}[11:5]{.aside}

[τυφλοι]{.greek-omitted} [αναβλεπουσιν]{.greek-omitted} [και]{.greek-omitted} [χωλοι]{.greek-omitted} [περιπατουσιν]{.greek-omitted} λεπροι καθαριζονται και κωφοι ακουουσιν [και]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5 | instance no. 2]{.aside}

και μακαριος εστιν ος [εαν]{.greek-omitted} μη [σκανδαλισθη]{.greek-omitted} [σκανδαλιστη]{.greek-added} εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωαννου [τι]{.greek-omitted} [εξηλθετε]{.greek-omitted} [τη]{.greek-added} [εξηλθαται]{.greek-added} εις την ερημ[ον]{.greek-supplied} [θε]{.greek-supplied}ασασθαι [καλαμο]{.unclear}ν υπ[ο]{.unclear} ανεμου [σ]{.unclear}αλ[ευ]{.unclear}ομενον[11:7]{.aside}

αλλα [τι]{.greek-omitted} [εξηλθετε]{.greek-omitted} [τη]{.greek-added} [εξηλθαται]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοι[ς]{.unclear} ημφιεσμεν[ον]{.unclear} ιδου οι τα μαλ[α]{.unclear}κα φορουντ[ες]{.unclear} εν τοις οικοις τ[ω]{.unclear}ν [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

[αλλα]{.unclear} [τι]{.greek-omitted} [εξηλθετε]{.greek-omitted} [τ[η]{.unclear}]{.greek-added} [[εξηλθα]{.unclear}ται]{.greek-added} ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ εστιν περι ου [γεγραπται]{.greek-omitted} [γεγραπτε]{.greek-added} ιδου εγ[ω]{.unclear} αποστε[λ]{.unclear}λω τον αγγελον μου προ προσωπου [σ]{.greek-supplied}ου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων [μειζων]{.greek-omitted} [μηζων]{.greek-added} ιωαννου του [βαπτιστου]{.greek-omitted} [βαπτηστου]{.greek-added} ο δε [μικροτερος]{.greek-omitted} [μηκροτερος]{.greek-added} [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [βασιλεια]{.greek-omitted} [βασιλειαν]{.greek-added} των [ουρανων]{.greek-abbr} [μειζων]{.greek-omitted} [μηζων]{.greek-added} αυτου [εστιν]{.greek-omitted} [εστην]{.greek-added}[11:11]{.aside}

απο δε των ημ[ε]{.unclear}ρων ιωαν[νου]{.unclear} [του]{.unclear} [βαπτιστου]{.greek-omitted} [βαπτηστου]{.greek-added} εως [αρτι]{.greek-omitted} [αρτει]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [[βι]{.greek-supplied}]{.greek-added} [βιαζεται]{.greek-omitted} [και]{.greek-omitted} [βιασται]{.greek-omitted} [αρπαζουσιν]{.greek-omitted} [αυτην]{.greek-omitted}[11:12]{.aside}

[τησμενοι]{.greek-added} [δευτε]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [κοπιωντες]{.greek-omitted} [και]{.greek-omitted} [πεφορτισμενοι]{.greek-omitted} καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος [ειμι]{.greek-omitted} [ειμ[η]{.unclear}]{.greek-added} και ταπεινος τη καρδια και [ευρησετε]{.greek-omitted} [ευρισεται]{.greek-added} αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου [χρηστος]{.greek-omitted} [[χριστος]{.greek-abbr}]{.greek-added} και το φ[ορ]{.unclear}τιον μου ελαφρον [εστιν]{.greek-omitted} [εστ[η]{.unclear}ν]{.greek-added}[11:30]{.aside}

### Chapter 12

[εν]{.greek-omitted} [εκεινω]{.greek-omitted} τω καιρω [εκει[νω]{.unclear}]{.greek-added} επορευθη ο [ιησους]{.greek-abbr} τοις σαββασιν [δι]{.unclear}α των [σποριμων]{.greek-omitted} [σπορημων]{.greek-added} οι δε μαθηται αυτου [επεινασαν]{.greek-omitted} [επινασαν]{.greek-added} και [ηρξαντο]{.greek-omitted} [ηρξαντω]{.greek-added} [τιλλειν]{.greek-omitted} [[τιλ]{.unclear}[λιν]{.unclear}]{.greek-added} σταχυας και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντε[ς]{.unclear} ειπον αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστ[η]{.unclear}ν]{.greek-added} ποιειν εν σαββατω[12:2]{.aside}

ο δε ειπεν αυτοις ουκ ανεγνωτε [τι]{.greek-omitted} [τη]{.greek-added} εποιησεν [δαυιδ]{.greek-abbr} οτε επεινασεν [αυτος]{.greek-omitted} και οι μετ αυτου[12:3]{.aside}

[π]{.unclear}ως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως εφαγεν ους ουκ [εξον]{.greek-omitted} [εξων]{.greek-added} ην αυτω φαγειν ουδ[ε]{.unclear} [το]{.unclear}ις μετ αυ[το]{.greek-supplied}υ ει μη τοις ιερ[ε]{.unclear}υσιν μονοις[12:4]{.aside}

η ουκ ανεγνωτε [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [οτι]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [οι]{.greek-omitted} [ιερεις]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [το]{.greek-omitted} [σαββατον]{.greek-omitted} [βεβηλουσιν]{.greek-omitted} [και]{.greek-omitted} [αναιτιοι]{.greek-omitted} [εισιν]{.greek-omitted}[12:5]{.aside}

[η]{.greek-omitted} [ουκ]{.greek-omitted} [ανεγνωτε]{.greek-omitted} εν τω νομω οτι τοις σαββασιν οι ιερεις εν τω ιερω το σαββατον βεβηλουσιν και [αναιτιοι]{.greek-omitted} [ανετιοι]{.greek-added} εισιν[12:5 | instance no. 2]{.aside}

λεγω δε υμιν οτι του ιερου [μειζον]{.greek-omitted} [μηζων]{.greek-added} [εστιν]{.greek-omitted} [εστην]{.greek-added} ωδε[12:6]{.aside}

ει δε [εγνωκειτε]{.greek-omitted} [εγνωκειται]{.greek-added} [τι]{.greek-omitted} [τη]{.greek-added} εστιν [ελεον]{.greek-omitted} [ελεος]{.greek-added} θελω και ου θυσιαν ουκ αν [κατεδικασατε]{.greek-omitted} [κατεδικασαται]{.greek-added} τους [αναιτιους]{.greek-omitted} [[α]{.unclear}νετιους]{.greek-added}[12:7]{.aside}

[κυριος]{.greek-abbr} γαρ [εστιν]{.greek-omitted} [εστην]{.greek-added} του σαββατου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} ην [[εκει]{.unclear}]{.greek-added} [εχον]{.greek-added} την χειρα [εχων]{.greek-omitted} ξηραν και επηρωτησαν αυτον λεγοντες ει [εξεστιν]{.greek-omitted} [εξεστην]{.greek-added} τοις σαββασιν θεραπευειν ινα [κατηγορησωσιν]{.greek-omitted} [κατηγωρησωσιν]{.greek-added} αυτου[12:10]{.aside}

ο δε ειπεν αυτοις [τις]{.greek-omitted} [της]{.greek-added} εσται εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν [εμπεση]{.greek-omitted} [πεση]{.greek-added} τουτο [τ]{.unclear}οις σαββασιν εις βοθυνον [ουχι]{.greek-omitted} [ουχη]{.greek-added} κρατησει αυτο και εγερει[12:11]{.aside}

ποσω ουν διαφερει [ανθρωπος]{.greek-abbr} π[ρο]{.unclear}βατου ωστε [εξεστιν]{.greek-omitted} [εξεστ[η]{.unclear}ν]{.greek-added} τοις [σαβ]{.unclear}βασιν καλως ποιειν[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου [και]{.unclear} [εξετεινεν]{.greek-omitted} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[12:13]{.aside}

[[εξε]{.unclear}τεινεν]{.greek-added} [τοτε]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [εκτεινον]{.greek-omitted} την χειρα [σου]{.greek-omitted} και [εξετεινεν]{.greek-omitted} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} υγιης ως η αλλη[12:13 | instance no. 2]{.aside}

οι δε φαρισαιοι συμβουλιον ελαβον κατ αυτου εξελθοντες οπως αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρη[σε]{.unclear}ν εκειθεν και ηκολουθησαν αυτω [πολλοι]{.greek-added} οχλοι [πολλοι]{.greek-omitted} και εθεραπευσεν αυτους παντας[12:15]{.aside}

και [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} αυτοις [ι]{.unclear}να μη φανερον αυτον ποιησωσιν[12:16]{.aside}

οπως πληρωθη το ρηθεν δια η[σ]{.unclear}αιου [το]{.unclear}υ προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον [ηρετισα]{.greek-omitted} [ηρετησα]{.greek-added} ο [αγαπητος]{.greek-omitted} [αγαπιτος]{.greek-added} μου εις ον [ευδοκησεν]{.greek-omitted} [ηυδοκη[σε]{.unclear}ν]{.greek-added} η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις ε[θνε]{.unclear}σιν απαγγελει[12:18]{.aside}

ουκ [ερισει]{.greek-omitted} [ερησει]{.greek-added} ουδε κραυγασε[ι]{.unclear} ουδε ακουσει [τις]{.greek-omitted} [της]{.greek-added} εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετρ[ιμμε]{.unclear}νον ου κατεαξει και λινον τυφομενον ου σβεσει εως αν εκβαλη εις νικος την κρ[ι]{.unclear}σιν[12:20]{.aside}

και [επι]{.greek-added} [τω]{.unclear} ον[ο]{.unclear}ματι αυτ[ου]{.unclear} εθνη ελπιουσιν[12:21]{.aside}

τοτε προσ[ηνεχθη]{.unclear} [αυτω]{.greek-omitted} [δαιμονιζομενος]{.greek-omitted} [τυφλος]{.greek-omitted} [και]{.greek-omitted} [κωφος]{.greek-omitted} [και]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [αυτον]{.greek-omitted} [ωστε]{.greek-omitted} [τον]{.greek-omitted} [τυφλον]{.greek-omitted} [και]{.greek-omitted} [κωφον]{.greek-omitted} [και]{.greek-omitted} [λαλειν]{.greek-omitted} [και]{.greek-omitted} [βλεπειν]{.greek-omitted}[12:22]{.aside}

[τοτε]{.greek-omitted} [προσηνεχθη]{.greek-omitted} αυτω δαιμονιζομενος τυφλος και κωφος και εθεραπευσεν αυτον ωστε τον [κωφον]{.greek-added} [και]{.greek-added} τυφλον [και]{.greek-omitted} [κωφον]{.greek-omitted} και λαλειν και βλεπειν[12:22 | instance no. 2]{.aside}

και εξισταντο πα[ντε]{.unclear}ς οι οχλοι κ[α]{.unclear}ι ελεγον μητι ουτο[ς]{.unclear} εσ[τιν]{.unclear} [ο]{.unclear} [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαν[τ]{.unclear}ες ειπον ουτος ουκ εκβαλ[λει]{.unclear} τα δαιμονι[α]{.unclear} ει μη εν [τω]{.greek-omitted} [το]{.greek-added} β[ε]{.unclear}[ελ]{.unclear}ζεβουλ αρ[χοντι]{.unclear} των δαι[μονι]{.unclear}ων[12:24]{.aside}

[ειδως]{.unclear} [δ]{.unclear}ε ο [ιησους]{.greek-abbr} τας [ενθ]{.unclear}υ[μ]{.unclear}ησεις αυτων ειπεν αυτοις πασα βασιλεια [μερισθεισα]{.greek-omitted} [μερισθησα]{.greek-added} καθ εαυτης ερημουται και πασα πολις η οικια [μερισθεισα]{.greek-omitted} [μερισθη[σ]{.unclear}α]{.greek-added} καθ εαυτης ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν [εκβαλλει]{.greek-omitted} [εκβαλει]{.greek-added} εφ εαυ[τ]{.unclear}ον εμερ[ισθη]{.unclear} [πως]{.unclear} [ουν]{.unclear} [σ]{.unclear}ταθη[σε]{.unclear}[ται]{.unclear} η βασιλεια αυτου[12:26]{.aside}

και ει εγω [εν]{.unclear} [β]{.unclear}εελζεβουλ εκβαλλω τα δαιμ[ο]{.unclear}νια οι [υιοι]{.greek-omitted} [ιοι]{.greek-added} υμων εν [τινι]{.greek-omitted} [τινει]{.greek-added} εκβαλλου[σιν]{.unclear} δια τουτο αυτοι υμω[ν]{.unclear} [εσο]{.unclear}νται κρ[ιται]{.unclear}[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} εγω εκ[βα]{.unclear}[λλω]{.greek-supplied} [τα]{.greek-supplied} [δαιμονια]{.greek-omitted} [αρα]{.greek-omitted} [εφθασεν]{.greek-omitted} [εφ]{.greek-omitted} [υμας]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[12:28]{.aside}

### Chapter 13

[μεν]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [εφη]{.greek-omitted} [αυτοις]{.greek-omitted} [εχθρος]{.greek-omitted} [ανθρωπος]{.greek-omitted} [τουτο]{.greek-omitted} [εποιησεν]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [δουλοι]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [θελεις]{.greek-omitted} [ουν]{.greek-omitted} [απελθοντες]{.greek-omitted} [συλλεξομεν]{.greek-omitted} αυτα[13:28]{.aside}

ο δε εφη ου μηποτε συλλεγοντες τα ζιζανια [εκριζωσητε]{.greek-omitted} [εκριζοσειται]{.greek-added} αμα αυτοις τον σιτον[13:29]{.aside}

[αφετε]{.greek-omitted} [αφεται]{.greek-added} συναυξανεσθαι αμφοτερα μεχρι του θερισμου και εν [τω]{.greek-added} καιρω του θερισμου ερω τοις θερισταις [συλλεξατε]{.greek-omitted} [συλλεξαται]{.greek-added} πρωτον τα ζιζανια και δησατε αυτα εις δεσμας προς [τ]{.unclear}ο [κατακαυσαι]{.greek-omitted} [κατακαυσε]{.greek-added} αυτα τον δε σιτον συναγαγε[τ]{.unclear}ε εις την αποθηκην μου[13:30]{.aside}

αλλην παραβολην παρεθηκεν αυτοις [λ]{.unclear}εγων ομοια [εστιν]{.greek-omitted} [εστην]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} κοκκ[ω]{.unclear} [σιναπεως]{.greek-omitted} [σηναπεως]{.greek-added} ον [λαβων]{.greek-omitted} [λαβον]{.greek-added} [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο μικροτερον μεν [εστιν]{.greek-omitted} [εστην]{.greek-added} παντων των σπερματων οταν δε αυξηθη μειζον των λαχανων εστιν και γινεται δενδρον ωστε ελθειν τα πετεινα του [ουρανου]{.greek-abbr} και κατασκηνουν εν τοις κλαδοις αυτου[13:32]{.aside}

αλλην παραβολην ελαλησεν αυτοις ομοια εστ[ι]{.unclear}ν η βασιλεια των [ουρανων]{.greek-abbr} ζυ[μη]{.greek-supplied} ην λαβου[σα]{.unclear} [γυνη]{.greek-supplied} [εκρυψεν]{.greek-omitted} [εις]{.greek-omitted} [αλευρου]{.greek-omitted} [σατα]{.greek-omitted} [τρια]{.greek-omitted} [εως]{.greek-omitted} [ου]{.greek-omitted} [εζυμωθη]{.greek-omitted} [ολον]{.greek-omitted}[13:33]{.aside}

[αλλην]{.greek-omitted} [παραβολην]{.greek-omitted} [ελαλησεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ομοια]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [ζυμη]{.greek-omitted} [ην]{.greek-omitted} [λαβουσα]{.greek-omitted} [γυνη]{.greek-omitted} εκρυψεν εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33 | instance no. 2]{.aside}

ταυτα παντα ελαλησεν ο [ιησους]{.greek-abbr} εν παραβολαις τοις οχλοις και χωρις παραβολης ουκ [ελαλει]{.greek-omitted} [ελα[λ]{.unclear}η]{.greek-added} αυ[τ]{.unclear}οις[13:34]{.aside}

οπως πληρω[θ]{.unclear}η το ρηθεν δια του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου ερευξομαι κεκρυμμενα απο καταβολης κοσμου[13:35]{.aside}

τοτε αφεις τους οχλους ηλθεν [εις]{.unclear} την οικιαν ο [ιησους]{.greek-abbr} και προσηλθον αυτω οι μαθηται αυτου λεγοντες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ει[π]{.unclear}εν αυτοις ο [σπειρων]{.greek-omitted} [σπειρο[ν]{.unclear}]{.greek-added} [τ]{.unclear}ο καλον σπερμα εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν [οι]{.greek-omitted} [[υ]{.unclear}]{.greek-added} [υ]{.unclear}ιοι της βασιλειας τα δε ζιζανια εισιν οι [υιοι]{.greek-omitted} [ιοι]{.greek-added} του πονηρου[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστ[ιν]{.unclear} οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν [συλλεγεται]{.greek-omitted} τα ζιζανια [συλλεγεται]{.greek-added} και πυρι [κεετε]{.greek-added} [καιεται]{.greek-omitted} [ουτως]{.greek-omitted} [εσται]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [συντελεια]{.greek-omitted} [του]{.greek-omitted} [ου]{.greek-added} [αιωνος]{.greek-omitted} [τουτου]{.greek-omitted}[13:40]{.aside}

[ωσπερ]{.greek-omitted} [ουν]{.greek-omitted} [συλλεγεται]{.greek-omitted} [τα]{.greek-omitted} [ζιζανια]{.greek-omitted} [και]{.greek-omitted} [πυρι]{.greek-omitted} [καιεται]{.greek-omitted} [ουτως]{.greek-omitted} [τως]{.greek-added} εσται εν τη συντελεια [του]{.unclear} αιωνος τουτου[13:40 | instance no. 2]{.aside}

αποστελει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} τ[ου]{.unclear}ς αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι [εκλαμψουσιν]{.greek-omitted} [εκλαμπουσιν]{.greek-added} [ως]{.greek-omitted} [ος]{.greek-added} ο [ηλιος]{.greek-omitted} [ηληος]{.greek-added} εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια [εστιν]{.greek-omitted} [εστην]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [θ]{.unclear}ησαυρω [κεκρυμμενω]{.greek-omitted} [καικρυμμενω]{.greek-added} εν [τω]{.greek-omitted} αγρω ον [ευρων]{.greek-omitted} [ευρον]{.greek-added} [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας αυτου υπαγει και παντα οσα εχει πωλει και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια [εστιν]{.greek-omitted} [εστη[ν]{.unclear}]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

[ος]{.greek-omitted} [ευρων]{.greek-omitted} [ευρον]{.greek-added} [δε]{.greek-added} ενα [βαρυτιμον]{.greek-added} [πολυτιμον]{.greek-omitted} [μαργαριτην]{.greek-omitted} απελθων πεπρακεν παντα οσα ειχεν και ηγορασεν αυτον[13:46]{.aside}

παλ[ι]{.unclear}ν ομοια εστ[ι]{.unclear}ν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη βληθειση εις την [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [παντος]{.greek-omitted} [γενους]{.greek-omitted} [συναγαγουση]{.greek-omitted}[13:47]{.aside}

[παλιν]{.greek-omitted} [ομοια]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [σαγηνη]{.greek-omitted} [βληθειση]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} θαλασσαν και εκ παντος γενους [συναγαγουση]{.greek-omitted} [συναγαγουσιν]{.greek-added}[13:47 | instance no. 2]{.aside}

ην οτε επληρωθη [αναβιβασαντες]{.greek-omitted} [αναβηβασαντες]{.greek-added} επι τον αιγιαλον και [καθισαντες]{.greek-omitted} [καθησαντες]{.greek-added} συνελεξαν τα καλα εις αγγει[α]{.unclear} τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται εν τη συντελεια του αιωνος εξελευσονται οι αγγελοι και αφοριουσιν τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις [την]{.greek-omitted} [τιν]{.greek-added} καμινον του πυρος εκει εσται ο κλαυ[θ]{.unclear}μος και ο βρυγμο[ς]{.unclear} τ[ω]{.unclear}ν οδοντων[13:50]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα [λε]{.unclear}γουσιν αυτ[ω]{.unclear} ναι [κυριε]{.greek-abbr}[13:51]{.aside}

ο δε ειπεν αυτοις δια τουτο πας γραμματευς μαθητευθεις [εις]{.greek-omitted} την βασιλειαν των [ουρανων]{.greek-abbr} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη [οστις]{.greek-omitted} [οστης]{.greek-added} [εκβαλλει]{.greek-omitted} [εκβαλει]{.greek-added} εκ του θησαυρου αυτου [καινα]{.greek-omitted} [κενα]{.greek-added} και παλαια[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας [τα]{.unclear}υτας μετηρεν εκειθεν[13:53]{.aside}

και ελθων εις την πατριδα αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων [ωστε]{.greek-omitted} [εκπληττεσθαι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [ποθεν]{.greek-omitted} [τουτω]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [αυτη]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [δυναμεις]{.greek-omitted}[13:54]{.aside}

### Chapter 15

[ο]{.greek-omitted} [γαρ]{.greek-omitted} [θεος]{.greek-omitted} [ενετειλατο]{.greek-omitted} [λεγων]{.greek-omitted} [τιμα]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} και την [μητερα]{.greek-abbr} και [ο]{.unclear} [κακολογων]{.greek-omitted} [κακολογον]{.greek-added} [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[15:4]{.aside}

υμεις δε [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} [ο]{.unclear}ς [αν]{.greek-omitted} [εαν]{.greek-added} [ειπη]{.greek-omitted} [ειπει]{.greek-added} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} δωρον ο [εαν]{.greek-omitted} εξ εμου [οφελεθεις]{.greek-added} [ωφεληθης]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

και [ου]{.greek-added} [μη]{.greek-added} [τημησει]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [η]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [ηκυρωσατε]{.greek-omitted} [ηκυρωσαται]{.greek-added} την εντολην του [θεου]{.greek-abbr} δια την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων[15:6]{.aside}

υποκριται καλως προεφητευσεν περι υμων ησαιας λεγων[15:7]{.aside}

[εγγιζει]{.greek-omitted} [μοι]{.greek-omitted} ο λαος ουτος [τω]{.greek-omitted} [στοματι]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} τοις χ[ει]{.unclear}λεσιν με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[15:8]{.aside}

ματην δε σεβονται με διδασκοντες [διδασκαλιας]{.greek-omitted} [διδασκαλειας]{.greek-added} ενταλματα [ανθρωπων]{.greek-abbr}[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις ακουετε και συνιετε[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} αλλα το εκπορευομενον εκ του στοματος τουτο κοινοι τον [ανθρωπον]{.greek-abbr}[15:11]{.aside}

τοτε προσελθοντες οι μαθηται αυτου ειπον αυτω οιδας οτι ο[ι]{.unclear} φαρισαιοι ακουσαντες τον λογον εσκανδαλισθησαν[15:12]{.aside}

ο δε αποκριθεις ειπεν πασα φυτεια ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο ουρανιος [εκριζωθησεται]{.greek-supplied}[15:13]{.aside}

[αφετε]{.greek-omitted} [αφε]{.greek-added} αυτους [οδηγοι]{.greek-omitted} [εισιν]{.greek-omitted} τυφλοι [ησιν]{.greek-added} [οδειγοι]{.greek-added} τυφλων τυφλος δε τυφλον εαν οδηγη αμφοτεροι [πεσουνται]{.greek-added} εις [βυθονον]{.greek-added} [βοθυνον]{.greek-omitted} [πεσουνται]{.greek-omitted}[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν ακμην και υμεις ασυνετοι εστε[15:16]{.aside}

[ουπω]{.greek-omitted} [ουπο]{.greek-added} νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα [εκβαλλεται]{.greek-omitted} [εκβαλεται]{.greek-added}[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ της καρδιας εξερχεται [και]{.greek-added} [κακεινα]{.greek-omitted} [[ε]{.greek-supplied}κεινα]{.greek-added} κοινοι [τον]{.greek-supplied} [ανθρωπον]{.greek-abbr}[15:18]{.aside}

εκ γαρ της καρδιας εξερχο[ν]{.greek-supplied}ται διαλογισμοι πονηροι [πορνειαι]{.greek-added} [μοιχειαι]{.greek-added} φονοι [μοιχειαι]{.greek-omitted} [πορνειαι]{.greek-omitted} κλοπαι ψευδομαρτυριαι [βλασφημιαι]{.greek-omitted} [βλασφημειαι]{.greek-added}[15:19]{.aside}

ταυτα [εστιν]{.greek-omitted} [εστην]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr} το δε ανιπτοις χερσιν φαγειν ου κοινοι τον [ανθρωπον]{.greek-abbr}[15:20]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα [μερη]{.greek-omitted} [μερι]{.greek-added} τυρου και [σιδωνος]{.greek-omitted} [σηδωνος]{.greek-added}[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα [εκραυγασεν]{.greek-omitted} [εκραυασεν]{.greek-added} αυτω λεγουσα ελεησον με [κυριε]{.greek-abbr} [υιε]{.greek-abbr} [δαυιδ]{.greek-abbr} η θυγατηρ [μου]{.greek-omitted} [κακως]{.greek-omitted} [δαιμονιζεται]{.greek-omitted}[15:22]{.aside}

[και]{.greek-omitted} [ιδου]{.greek-omitted} [γυνη]{.greek-omitted} [χαναναια]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [οριων]{.greek-omitted} [εκεινων]{.greek-omitted} [εξελθουσα]{.greek-omitted} [εκραυγασεν]{.greek-omitted} [αυτω]{.greek-omitted} [λεγουσα]{.greek-omitted} [ελεησον]{.greek-omitted} [με]{.greek-omitted} [κυριε]{.greek-omitted} [υιε]{.greek-omitted} [δαυιδ]{.greek-omitted} [η]{.greek-omitted} [θυγατηρ]{.greek-omitted} μου [κακως]{.greek-omitted} [κακος]{.greek-added} δαιμονιζεται[15:22 | instance no. 2]{.aside}

ο δε ουκ απεκριθη αυτη λογον και προσελθοντες οι μαθηται αυτου [ηρωτων]{.greek-omitted} [ηρωτον]{.greek-added} αυτον λεγοντες απολυσον αυτην οτι κραζει [οπισθεν]{.greek-omitted} [οπιθεν]{.greek-added} ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην ει [μη]{.greek-omitted} [μι]{.greek-added} εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

η δε ελθουσα [προσεκυνησεν]{.greek-omitted} [προσεκυνει]{.greek-added} αυτω λεγουσα [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [βοηθησον]{.greek-added} μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ [εστιν]{.greek-omitted} [εστην]{.greek-added} καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

[η]{.greek-omitted} [ο]{.greek-added} δε ειπεν ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια [εσθιει]{.greek-omitted} [εσθειη]{.greek-added} απο των ψιχιων των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη ω γυναι μεγαλη σου η [πιστις]{.greek-omitted} [πιστης]{.greek-added} γενηθητω σοι ως [θελεις]{.greek-omitted} [θελης]{.greek-added} και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} ηλθεν παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος [εκαθητο]{.greek-omitted} [εκαθητω]{.greek-added} εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντ[ες]{.greek-supplied} [με]{.unclear}θ εαυτων [χωλους]{.greek-omitted} [τυφλους]{.greek-omitted} [κωφους]{.greek-supplied} [κυλλους]{.greek-omitted} [και]{.greek-omitted} [ετερους]{.greek-omitted} [πολλους]{.greek-omitted} [και]{.greek-omitted} [ερριψαν]{.greek-omitted} [αυτους]{.greek-omitted} [παρα]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [και]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [αυτους]{.greek-omitted}[15:30]{.aside}

[και]{.greek-omitted} [προσηλθον]{.greek-omitted} [αυτω]{.greek-omitted} [οχλοι]{.greek-omitted} [πολλοι]{.greek-omitted} [εχοντες]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} χωλους τυφλους [κωφους]{.greek-omitted} κυλλους και ετερους πολλους και ερρ[ι]{.greek-supplied}ψαν αυτους παρα τους ποδας [του]{.greek-omitted} [αυτου]{.greek-added} [ιησου]{.greek-omitted} και εθεραπευσεν αυτους[15:30 | instance no. 2]{.aside}

[ωστε]{.greek-omitted} [ωσται]{.greek-added} τους οχλους θαυμασαι βλεποντας κωφους λαλουντας κυλλους [υγιεις]{.greek-omitted} [υγηεις]{.greek-added} χωλους περιπατουντας και τυφλους βλεποντας και [εδοξασαν]{.greek-omitted} [εδοξαζον]{.greek-added} τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου ειπεν [σπλαγχνιζομαι]{.greek-omitted} [σπλαγχνηζομαι]{.greek-added} επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις προσμενουσιν μοι και ουκ εχουσιν [τι]{.greek-omitted} [τη]{.greek-added} φαγωσιν και απολυσαι αυτους [νηστεις]{.greek-omitted} [νιστεις]{.greek-added} ου θελω μηποτε [εκλυθ[ο]{.unclear}σιν]{.greek-added} [εκλυθωσιν]{.corr} εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν [ερημια]{.greek-omitted} [εριμηα]{.greek-added} [τοσουτοι]{.greek-added} αρτοι [τοσουτοι]{.greek-omitted} ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους [εχετε]{.greek-omitted} [εχεται]{.greek-added} οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και εκελευσεν τοις οχλοις [αναπεσειν]{.greek-omitted} [αναπαισειν]{.greek-added} επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας [εκλα]{.greek-added} [εκλασεν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [μαθηται]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted}[15:36]{.aside}

### Chapter 18

[δια]{.greek-omitted} [τουτο]{.greek-omitted} [ωμοιωθη]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος ηθελησεν συναραι λ[ο]{.unclear}γον μετα των δουλων αυτου[18:23]{.aside}

αρξαμενου δε αυτου [συναιρειν]{.greek-omitted} [συνερειν]{.greek-added} προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν αυτον ο κυριος αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα ειχεν και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος προσεκυνει αυτω λεγων κυριε μακρ[ο]{.unclear}θυμησον επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο κυριος του δουλου εκεινου απελυσεν αυτον και το δανειον αφηκεν αυτω[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον [δηναρια]{.greek-omitted} [διναρια]{.greek-added} και κρατησας αυτον [επνιγεν]{.greek-omitted} [επνηγεν]{.greek-added} λεγων αποδος [μοι]{.greek-omitted} ει τι [οφειλεις]{.greek-omitted} [οφηλης]{.greek-added}[18:28]{.aside}

πεσων ουν ο συνδουλος αυτου εις τους ποδας αυτου παρεκαλει αυτον λεγων μακροθυμησον επ [ε]{.greek-added} [εμοι]{.greek-omitted} [και]{.greek-omitted} [αποδωσω]{.greek-omitted} [σοι]{.greek-omitted}[18:29]{.aside}

[πεσων]{.greek-omitted} [ουν]{.greek-omitted} [ο]{.greek-omitted} [συνδουλος]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [μακροθυμησον]{.greek-omitted} [επ]{.greek-omitted} [εμοι]{.greek-omitted} [μοι]{.greek-added} και [παντα]{.greek-added} [σοι]{.greek-added} αποδωσω σοι[18:29 | instance no. 2]{.aside}

ο δε ουκ [ηθελεν]{.greek-omitted} [ειθελεν]{.greek-added} αλλα απελθων εβαλεν αυτον εις φυλακην εως ου αποδω το οφειλομενον[18:30]{.aside}

ιδοντες δε οι συνδουλοι αυτου τα γενομενα ελυπηθησαν σφοδρα και [ελθοντες]{.greek-omitted} [απελθοντες]{.greek-added} διεσαφησαν τω [κυριω]{.greek-abbr} [εαυτων]{.greek-omitted} [αυτων]{.greek-added} παντα τα γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο κυριος αυτου λεγει αυτω δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι [επει]{.greek-omitted} [επι]{.greek-added} παρεκαλεσας με[18:32]{.aside}

ουκ εδει και σε [ελε]{.unclear}ησαι τον συνδουλον σου ως και εγω σε ηλεησα[18:33]{.aside}

και [οργισθεις]{.greek-omitted} [οργησθης]{.greek-added} ο κυριος αυτου παρεδωκεν αυτον τοις βασανισταις [εως]{.unclear} ου αποδω παν το οφειλομενον [αυτω]{.greek-omitted} [αυτο]{.greek-added}[18:34]{.aside}

ουτως και ο [πατηρ]{.greek-abbr} μου ο [επουρανιος]{.greek-omitted} [ουρανιος]{.greek-added} ποιησει υμιν εαν μη αφητε εκαστος τ[ω]{.unclear} αδελφω αυτου απο των καρδιων υμων τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας [και]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορια]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted}[19:1]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [οτε]{.greek-omitted} [ετελεσεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τους]{.greek-omitted} [λογους]{.greek-omitted} [τουτους]{.greek-omitted} [μετηρεν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1 | instance no. 2]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και προσηλθον αυτω [οι]{.greek-omitted} φαρισαιοι πειραζοντες αυτον και λεγοντες αυτω ει [εξεστιν]{.greek-omitted} [εξεστην]{.greek-added} [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} οτι ο ποιησας απ αρχης αρσεν και [θηλυ]{.greek-omitted} [θηλοι]{.greek-added} εποιησεν αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταλειψη]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-added} και την [μητερα]{.greek-abbr} και [προσκολληθησεται]{.greek-omitted} [κολληθησεται]{.greek-added} τη γυναικι αυτου και εσοντ[α]{.unclear}ι οι δυ[ο]{.greek-supplied} εις σαρκα μιαν[19:5]{.aside}

ωστε ουκετι εισιν δ[υο]{.unclear} αλλα [σαρξ]{.greek-omitted} [σαρκα]{.greek-added} μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ενετειλατο δουναι βιβλιον αποστασιου και [απολυσαι]{.greek-omitted} [απολυειν]{.greek-added} αυτην[19:7]{.aside}

λεγει αυτοις οτι [μωσης]{.greek-omitted} [μωυσης]{.greek-added} προς την [σκληροκαρδιαν]{.greek-omitted} [σκληρωκαρδιαν]{.greek-added} υμων επετρεψεν υμιν απολυσαι τας γυναικας [υμων]{.greek-omitted} [απ]{.greek-omitted} [αρχης]{.greek-omitted} [δε]{.greek-omitted} [ου]{.greek-omitted} [γεγονεν]{.greek-omitted} [ουτως]{.greek-omitted}[19:8]{.aside}

[λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [οτι]{.greek-omitted} [μωσης]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [σκληροκαρδιαν]{.greek-omitted} [υμων]{.greek-omitted} [επετρεψεν]{.greek-omitted} [υμιν]{.greek-omitted} [απολυσαι]{.greek-omitted} [τας]{.greek-omitted} [γυναικας]{.greek-omitted} υμων απ [αρχης]{.greek-omitted} [αρχην]{.greek-added} δε ου [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} ουτως[19:8 | instance no. 2]{.aside}

λεγω δε υμιν οτι ος αν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου [μη]{.greek-omitted} [επι]{.greek-omitted} [παρεκτος]{.greek-added} [λογου]{.greek-added} [πορνεια]{.greek-omitted} [πορνειας]{.greek-added} [ποιει]{.greek-added} [αυτην]{.greek-added} [μοιχευθηναι]{.greek-added} και [γαμηση]{.greek-omitted} [αλλην]{.greek-omitted} [απολελυμενην]{.greek-added} [γαμον]{.greek-added} μοιχαται [και]{.greek-omitted} [ο]{.greek-omitted} [απολελυμενην]{.greek-omitted} [γαμησας]{.greek-omitted} [μοιχαται]{.greek-omitted}[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτ[ω]{.unclear}ς [εστιν]{.greek-omitted} [εστην]{.greek-added} η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφερ[ει]{.unclear} γαμησαι[19:10]{.aside}

ο δ[ε]{.unclear} ειπε[ν]{.unclear} [αυτ]{.unclear}ο[ι]{.unclear}ς ου παντες χωρουσιν τον λογον τουτον αλλ οις δεδοται[19:11]{.aside}

εισιν γαρ ευνουχο[ι]{.unclear} [οιτινες]{.greek-omitted} [οιτιτινες]{.greek-added} εκ κοιλιας [μητρος]{.greek-abbr} [εγεννηθη]{.greek-supplied}σαν ου[τως]{.unclear} [και]{.unclear} εισιν ευνουχ[οι]{.unclear} οιτινες [ευνουχισθησαν]{.greek-omitted} υπο [τω]{.unclear}ν [ανθρωπων]{.greek-abbr} [ευνουχ[ισ]{.unclear}θησαν]{.greek-added} και εισιν ευνουχοι οιτινες [ευνουχισαν]{.greek-omitted} [ευνουχησαν]{.greek-added} εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε [προσηνεχθη]{.greek-omitted} [προσηνεχθησαν]{.greek-added} αυτω παιδια ινα τας χειρας επιθη αυτοις και προσευξηται οι δε μαθηται [επετιμησαν]{.greek-omitted} [επετημησαν]{.greek-added} αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αφετε]{.greek-omitted} [αφεται]{.greek-added} τα παιδια και μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} [αυτα]{.unclear} ελθειν [προς]{.greek-omitted} [με]{.greek-omitted} [των]{.greek-omitted} [γαρ]{.greek-omitted} [τοιουτων]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted}[19:14]{.aside}

### Chapter 21

[ειπατε]{.greek-omitted} [τη]{.greek-omitted} [θυγατρι]{.greek-omitted} [σιων]{.greek-omitted} [ιδου]{.greek-omitted} ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον και [πωλον]{.greek-omitted} [π[ο]{.unclear}λον]{.greek-added} [υιον]{.greek-omitted} [υιων]{.greek-added} υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και π[ο]{.unclear}ιησαντες [κ]{.unclear}αθ[ω]{.unclear}ς προ[σε]{.unclear}ταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και τον [πωλον]{.greek-omitted} [πολον]{.greek-added} και επεθηκαν [επανω]{.greek-omitted} [επ]{.greek-added} [αυτων]{.greek-omitted} [αυτον]{.greek-added} τα ιματ[ια]{.unclear} αυτων και [επεκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επα[νω]{.unclear} αυτων[21:7]{.aside}

ο δε πλειστος οχλος εστρωσαν [εαυτων]{.greek-omitted} τα ιματια [αυτων]{.greek-added} [ε]{.unclear}ν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και [εστρωννυον]{.greek-omitted} [εστρωσαν]{.greek-added} εν τη οδω[21:8]{.aside}

οι δε οχλοι οι [προαγοντες]{.greek-omitted} [πρωαγοντες]{.greek-added} και οι [α]{.unclear}κολουθουντες εκραζον λεγοντες ωσαννα τω [υιω]{.greek-abbr} [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

[και]{.greek-omitted} εισελ[θ]{.unclear}ον[το]{.unclear}ς [αυτου]{.unclear} [εις]{.unclear} [ιερο]{.unclear}σολυμα εσει[σ]{.unclear}θη πασα η πολις λεγουσα τις [εσ]{.unclear}τιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο [ναζαρετ]{.greek-omitted} [ναζαρ[ε]{.unclear}[θ]{.greek-supplied}]{.greek-added} [τ]{.unclear}[ης]{.greek-supplied} γαλιλαιας[21:11]{.aside}

και εισ[η]{.unclear}λθεν ο [ιησους]{.greek-abbr} εις το [ιερον]{.greek-supplied} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [εξεβαλεν]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [πωλουντας]{.greek-omitted} [και]{.greek-omitted} [αγοραζοντας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [τραπεζας]{.greek-omitted} [των]{.greek-omitted} [κολλυβιστων]{.greek-omitted} [κατεστρεψεν]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [καθεδρας]{.greek-omitted} [των]{.greek-omitted} [πωλουντων]{.greek-omitted} [τας]{.greek-omitted} [περιστερας]{.greek-omitted}[21:12]{.aside}

[και]{.greek-omitted} [εισηλθεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} του [θεου]{.greek-abbr} και εξεβαλεν παντας τους [πωλουντας]{.greek-omitted} [πολουντας]{.greek-added} και αγοραζοντας εν τ[ω]{.greek-supplied} ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} κατεστρεψεν και τας καθεδρας των [πωλουντων]{.greek-omitted} [π[ο]{.unclear}λουντων]{.greek-added} τας περιστερας[21:12 | instance no. 2]{.aside}

και λεγει αυτοις γεγραπ[τ]{.unclear}αι ο οικος μου οικος προσευχ[ης]{.unclear} [κληθ]{.unclear}ησεται [υ]{.unclear}μεις δε αυ[τον]{.greek-supplied} [εποιησατε]{.greek-supplied} [σπηλαιον]{.greek-supplied} [ληστων]{.greek-supplied}[21:13]{.aside}

[και]{.greek-supplied} [προσηλθον]{.greek-supplied} [αυτω]{.greek-supplied} [χωλοι]{.greek-supplied} [και]{.greek-supplied} [τυφλοι]{.greek-supplied} [εν]{.greek-supplied} [τω]{.greek-supplied} [ιερω]{.greek-supplied} [και]{.greek-supplied} [εθεραπευ]{.greek-supplied}σεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις [και]{.greek-supplied} [οι]{.greek-omitted} γραμματεις τα θαυμασια α εποιησεν και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω [υιω]{.greek-abbr} [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις ναι ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} οτι εκ στοματος νηπιων και θηλαζοντ[ων]{.greek-supplied} [κατηρτισω]{.greek-omitted} [[κατη]{.greek-supplied}ρτ[ησω]{.unclear}]{.greek-added} αινον[21:16]{.aside}

και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} [αυτους]{.greek-supplied} [εξηλ]{.greek-supplied}θεν εξω της πολεως εις [βηθανιαν]{.greek-omitted} [β[ι]{.unclear}θανιαν]{.greek-added} και [ηυλισθη]{.greek-supplied} εκει[21:17]{.aside}

[πρωιας]{.greek-omitted} [[προ]{.unclear}ιας]{.greek-added} δε επ[α]{.unclear}να[γων]{.greek-supplied} [εις]{.greek-supplied} [τ]{.unclear}ην πολιν επει[να]{.unclear}σεν[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και [ουδε]{.greek-supplied}ν ευρεν ε[ν]{.greek-supplied} αυτη ει [μ]{.unclear}η φυ[λ]{.greek-supplied}[λα]{.greek-supplied} μονον και [λεγει]{.greek-supplied} αυτη μηκετ[ι]{.greek-supplied} εκ σου καρπος γενη[τ]{.unclear}α[ι]{.unclear} εις [τ]{.greek-supplied}ον αιωνα [και]{.greek-supplied} εξηραν[θη]{.unclear} παραχρημα η συκη[21:19]{.aside}

[κ]{.unclear}αι [ι]{.greek-supplied}δοντες οι μαθη[τ]{.unclear}αι εθαυ[μ]{.unclear}ασαν λεγον[τες]{.greek-supplied} πως παρα[χρημ]{.unclear}[α]{.greek-supplied} [εξ]{.greek-supplied}[ηραν]{.unclear}[θ]{.greek-supplied}η η [συκη]{.unclear}[21:20]{.aside}

α[ποκ]{.unclear}ρ[ι]{.unclear}θει[ς]{.unclear} [δε]{.unclear} ο [ιησους]{.greek-abbr} [ει]{.unclear}π[ε]{.unclear}ν αυ[τ[οις]{.greek-supplied}]{.unclear} αμην λεγω υμιν εαν [εχητε]{.greek-omitted} [εχητα[ι]{.greek-supplied}]{.greek-added} [πι]{.greek-supplied}στ[ιν]{.greek-supplied} [και]{.greek-supplied} [μη]{.unclear} [διακριθητε]{.greek-omitted} [[δ]{.unclear}ιακριθηται]{.greek-added} ου μο[νο]{.unclear}ν [το]{.greek-supplied} [της]{.greek-supplied} [συ]{.greek-supplied}κ[η]{.unclear}ς [ποιησετε]{.greek-omitted} [[ποιησατ]{.unclear}αι]{.greek-added} αλλα κα[ν]{.unclear} [τω]{.greek-omitted} [[το]{.unclear}]{.greek-added} ορει τουτω [ειπητε]{.greek-omitted} [ειπ[η]{.greek-supplied}ται]{.greek-added} αρ[θητι]{.unclear} [κ]{.unclear}αι βληθη[τ]{.unclear}ι [εις]{.unclear} την [θ]{.unclear}αλασσαν γε[νη]{.greek-supplied}σε[ται]{.greek-supplied}[21:21]{.aside}

[κ]{.unclear}αι παντα οσα [εαν]{.greek-omitted} [αν]{.greek-added} [αιτησητε]{.greek-omitted} [[αι]{.unclear}τ[η]{.unclear}σ[η]{.greek-supplied}[τ]{.unclear}αι]{.greek-added} [εν]{.unclear} τη προσευχη πι[στ]{.unclear}ευ[ο]{.unclear}ντες [ληψεσθε]{.greek-omitted} [ληψεσθ[αι]{.greek-supplied}]{.greek-added}[21:22]{.aside}

κ[αι]{.unclear} [ε]{.unclear}[λθ]{.greek-supplied}[ον]{.unclear}τι αυ[τω]{.unclear} εις το ιερον προσηλθον αυτ[ω]{.greek-supplied} δι[δ]{.greek-supplied}ασκοντι οι αρχιερεις και οι πρεσβυ[τε]{.greek-supplied}ροι [το]{.unclear}[υ]{.greek-supplied} [λ]{.greek-supplied}[αο]{.unclear}[υ]{.greek-supplied} [λε]{.greek-supplied}[γοντες]{.greek-supplied} [εν]{.greek-supplied} [ποια]{.greek-omitted} [[ποι]{.greek-supplied}]{.greek-added} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιεις]{.greek-omitted} [και]{.greek-omitted} [τις]{.greek-omitted} [σοι]{.greek-omitted} [εδωκεν]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [ταυτην]{.greek-omitted}[21:23]{.aside}

[α]{.greek-added} [και]{.greek-omitted} [ελθοντι]{.greek-omitted} [αυτω]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [προσηλθον]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκοντι]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [του]{.greek-omitted} [λαου]{.greek-omitted} [λεγοντες]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} εξουσια ταυτα ποι[ει]{.unclear}ς και [τις]{.greek-omitted} [της]{.greek-added} σοι εδωκεν την εξουσιαν ταυτην[21:23 | instance no. 2]{.aside}

αποκριθεις δε [ο]{.unclear} [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω υμας κα[γ]{.greek-supplied}ω [λογ]{.unclear}ον ενα ον εαν [ειπητε]{.greek-omitted} [ειπηται]{.greek-added} μοι καγω υμιν ερω εν π[ο]{.unclear}ια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [ιωανου]{.greek-added} ποθεν ην εξ [ουρανου]{.greek-abbr} [[η]{.unclear}ν]{.greek-added} [η]{.unclear} εξ [ανθρωπων]{.greek-abbr} [οι]{.greek-supplied} [δε]{.greek-supplied} [δ]{.greek-supplied}ιελογιζον[το]{.greek-supplied} παρ εαυτοις [λεγοντες]{.greek-supplied} εαν [ε]{.greek-supplied}ιπ[ω]{.unclear}μεν ε[ξ]{.unclear} [ουρανου]{.greek-abbr} ερει ημιν [δια]{.greek-supplied} [τι]{.greek-supplied} [ουν]{.greek-supplied} ουκ [επιστευσατε]{.greek-omitted} [ε[πιστευσ]{.greek-supplied}αται]{.greek-added} αυ[τω]{.greek-supplied}[21:25]{.aside}

[εα]{.greek-supplied}ν δε [ειπωμεν]{.greek-omitted} [ειπ[ο]{.unclear}μεν]{.greek-added} εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες [γ]{.unclear}αρ εχουσιν τ[ον]{.greek-supplied} ι[ω]{.unclear}αννην ως προφητην[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} [ειπον]{.greek-omitted} [ειπαν]{.greek-added} ου[κ]{.greek-supplied} [οιδαμεν]{.greek-supplied} εφ[η]{.unclear} α[υτοις]{.greek-supplied} [κα]{.unclear}ι αυτο[ς]{.unclear} ουδε εγω [υμιν]{.greek-added} λεγω [υμιν]{.greek-omitted} εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι [δε]{.greek-omitted} υμιν δοκει [ανθρωπος]{.greek-abbr} ειχεν τεκνα δυο και πρ[οσε]{.unclear}λθων τ[ω]{.greek-supplied} πρ[ω]{.unclear}τ[ω]{.greek-supplied} ειπεν τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι [μου]{.greek-omitted}[21:28]{.aside}

ο δε αποκριθεις ει[π]{.unclear}εν [[υπαγω]{.greek-supplied}]{.greek-added} [[[κυριε]{.greek-abbr}]{.greek-supplied}]{.greek-added} [[και]{.greek-supplied}]{.greek-added} [ου]{.greek-omitted} [[ουκ]{.greek-supplied}]{.greek-added} [θελω]{.greek-omitted} [υστερον]{.greek-omitted} [δε]{.greek-omitted} [μεταμεληθεις]{.greek-omitted} [α]{.greek-supplied}πηλθεν[21:29]{.aside}

[και]{.unclear} [προ[σ]{.greek-supplied}]{.greek-added} [προσελθων]{.greek-omitted} [τω]{.greek-omitted} [δευτερω]{.greek-omitted} [ειπεν]{.greek-omitted} [ωσαυτως]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [εγω]{.greek-omitted} [κυριε]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [απηλθεν]{.greek-omitted}[21:30]{.aside}

[ελθων]{.greek-added} [και]{.greek-omitted} [προσελθων]{.greek-omitted} τω [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν ωσαυτως ο δε αποκριθεις ειπεν [εγω]{.greek-omitted} [κυριε]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ου]{.greek-added} [θελω]{.greek-added} [υστερον]{.greek-added} [δε]{.greek-added} [μεταμεληθεις]{.greek-added} απηλθεν[21:30 | instance no. 2]{.aside}

τις εκ των δυο εποιησεν το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο [πρωτος]{.greek-omitted} [εσχατος]{.greek-added} λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

ηλθεν γαρ προς υμας ιωαννης εν οδω δικαιοσυνης και ουκ [επιστευσατε]{.greek-omitted} [επιστευσαται]{.greek-added} αυτω οι δε τελωναι και [αι]{.greek-omitted} πορναι επιστευσαν αυτω υμεις δε ιδοντες [ου]{.greek-omitted} [ουδε]{.greek-added} [μετεμεληθητε]{.greek-omitted} [μετεμεληθηται]{.greek-added} υστερον του πιστευσαι αυτω[21:32]{.aside}

[αλλην]{.greek-omitted} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [την]{.greek-added} παραβολην [ακουσατε]{.greek-omitted} [ταυτην]{.greek-added} [ανθρωπος]{.greek-abbr} [τις]{.greek-omitted} [της]{.greek-added} ην οικοδεσποτης [οστις]{.greek-omitted} [οστης]{.greek-added} εφυτευσεν αμπελωνα και φραγμον αυτω περιεθηκεν και ωρυξεν εν αυτω [ληνον]{.greek-omitted} [λινον]{.greek-added} κ[αι]{.greek-supplied} [ωκοδ]{.greek-supplied}ομησεν πυργον και [εξεδοτο]{.greek-omitted} [εξεδετω]{.greek-added} αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε [[ηγ]{.greek-supplied}]{.greek-added} [ηγγισεν]{.greek-omitted} [ο]{.greek-omitted} [καιρος]{.greek-omitted} [των]{.greek-omitted} [καρπων]{.greek-omitted} [απεστειλεν]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [αυτου]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [γεωργους]{.greek-omitted} [λαβειν]{.greek-omitted} [τους]{.greek-omitted} [καρπους]{.greek-omitted} [αυτου]{.greek-omitted}[21:34]{.aside}

[γησεν]{.greek-added} [οτε]{.greek-omitted} [δε]{.greek-omitted} [ηγγισεν]{.greek-omitted} ο καιρος των καρπων απεστειλεν τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34 | instance no. 2]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

[παλιν]{.greek-omitted} [παλην]{.greek-added} απεστειλεν [αλλους]{.greek-omitted} [αλους]{.greek-added} δουλους [πλειονας]{.greek-omitted} [πλειωνας]{.greek-added} των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε απεστειλεν προς αυτους τον [υιον]{.greek-abbr} αυτου [λεγ]{.unclear}ω[ν]{.unclear} εντραπησονται τον [υιον]{.greek-abbr} μου[21:37]{.aside}

οι δε [γεω]{.unclear}ργοι ιδοντες τον [υιον]{.greek-abbr} ειπον εν εαυτοις ουτος [εστιν]{.greek-omitted} [εστην]{.greek-added} ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον [ε]{.unclear}ξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος [τι]{.greek-omitted} [τη]{.greek-added} ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα [εκδ[o]{.greek-supplied}]{.greek-added} [εκδωσεται]{.greek-omitted} [αλλοις]{.greek-omitted} [γεωργοις]{.greek-omitted} [οιτινες]{.greek-omitted} [αποδωσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [τους]{.greek-omitted} [καρπους]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [καιροις]{.greek-omitted} [αυτων]{.greek-omitted}[21:41]{.aside}

[σαιτε]{.greek-added} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [κακους]{.greek-omitted} [κακως]{.greek-omitted} [απολεσει]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [αμπελωνα]{.greek-omitted} [εκδωσεται]{.greek-omitted} αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις καιροις αυτων[21:41 | instance no. 2]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} εν ταις γραφαις λιθον ον απεδοκιμασαν οι οικοδομουντες [ουτος]{.greek-omitted} [ουτως]{.greek-added} [εγενηθη]{.greek-omitted} [εγεννηθη]{.greek-added} εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμασ[τ]{.unclear}η εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται [εθνει]{.greek-omitted} [ε[θ]{.unclear}ν[η]{.greek-supplied}]{.greek-added} ποιουντι τους καρπους [αυτης]{.greek-omitted} [[ε]{.unclear}αυτης]{.greek-added}[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον [συνθλασθησεται]{.greek-omitted} [συντριβησεται]{.greek-added} εφ ον δ αν [πεση]{.greek-omitted} [πεσει]{.greek-added} [λικμησει]{.greek-omitted} [ληκμησει]{.greek-added} αυτον[21:44]{.aside}

και ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

κ[αι]{.unclear} [ζητουντες]{.greek-omitted} [[ε]{.unclear}ζητουν]{.greek-added} αυτον κρατησαι εφοβηθησαν τους οχλους [επειδη]{.greek-omitted} [οτι]{.greek-added} ως προφητην αυτον [ειχον]{.greek-omitted} [ηχον]{.greek-added}[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} παλιν ειπεν αυτοις εν παρα[βο]{.unclear}λαις λε[γ]{.unclear}ων[22:1]{.aside}

[την]{.greek-added} [και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [παλιν]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [λεγων]{.greek-omitted}[22:1 | instance no. 2]{.aside}

[ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} ανθρωπω βασιλει [οστις]{.greek-omitted} [ωστης]{.greek-added} εποιησεν γαμους τω [υιω]{.greek-abbr} αυτου[22:2]{.aside}

και απεστειλεν τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους [και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων [ειπατε]{.greek-omitted} [ειπαται]{.greek-added} τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα [σιτιστα]{.greek-omitted} [σιτευτα]{.greek-added} τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον [ο]{.greek-omitted} [μεν]{.greek-omitted} εις τον ιδιον αγρον [ο]{.greek-omitted} [ο[ς]{.unclear}]{.greek-added} δε εις [την]{.greek-omitted} [τιν]{.greek-added} [εμποριαν]{.greek-omitted} [εμπορειαν]{.greek-added} αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου [υβρισαν]{.greek-omitted} [υβρησαν]{.greek-added} και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος [ωργισθη]{.greek-omitted} [οργισθη]{.greek-added} και πεμψας τα [στρατευματα]{.greek-omitted} [στρευματα]{.greek-added} αυτου [απωλεσεν]{.greek-omitted} [απολεσεν]{.greek-added} τους φονεις εκεινους και την πολιν αυτων ενεπρησεν[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος [εστιν]{.greek-omitted} [εστην]{.greek-added} οι δε κεκλημενοι ουκ [ησαν]{.greek-omitted} [ησιν]{.greek-added} αξιοι[22:8]{.aside}

[πο]{.greek-added} [πορευεσθε]{.greek-omitted} [ουν]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [διεξοδους]{.greek-omitted} [των]{.greek-omitted} [οδων]{.greek-omitted} [και]{.greek-omitted} [οσους]{.greek-omitted} [αν]{.greek-omitted} [ευρητε]{.greek-omitted} [καλεσατε]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [γαμους]{.greek-omitted}[22:9]{.aside}

[πορευεσθε]{.greek-omitted} [ρευεσθαι]{.greek-added} ουν [επι]{.greek-omitted} [εις]{.greek-added} τας διεξοδ[ο]{.unclear}υς των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} [ευρητε]{.greek-omitted} [ευρειτε]{.greek-added} καλεσατε εις τους γαμους[22:9 | instance no. 2]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον παντας οσους ευρον πονηρους τε και αγαθους κα[ι]{.unclear} [επ]{.unclear}λησθη ο γαμος [των]{.greek-added} ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυ[με]{.unclear}νον ενδυμα [γαμου]{.unclear}[22:11]{.aside}

και λεγει [α]{.unclear}υ[τω]{.unclear} [εταιρε]{.greek-omitted} [ετερε]{.greek-added} [π]{.unclear}ως εισηλθες ω[δ]{.unclear}ε μη εχων ενδυμα γαμου ο δε [εφιμωθη]{.greek-omitted} [εφ[η]{.unclear}μωθη]{.greek-added}[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου [χειρας]{.greek-added} [και]{.greek-added} ποδας [και]{.greek-omitted} [χειρας]{.greek-omitted} αρατε αυτον και εκβα[λ]{.greek-supplied}ετε εις το σκοτος το [εξωτερον]{.greek-omitted} [εξ[ο]{.greek-supplied}[τε]{.unclear}ρον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ εισιν κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον ελαβον [κατ]{.greek-added} [[αυ]{.unclear}του]{.greek-added} οπως αυτον [παγιδευσωσιν]{.greek-omitted} [παγειδευσωσιν]{.greek-added} [εν]{.greek-supplied} [λογω]{.greek-supplied}[22:15]{.aside}

[και]{.greek-supplied} [αποστελλουσιν]{.greek-supplied} [[αυ]{.greek-supplied}]{.greek-added} [αυτω]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτων]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [ηρωδιανων]{.greek-omitted} [λεγοντες]{.greek-omitted} [διδασκαλε]{.greek-omitted} [οιδαμεν]{.greek-omitted} [οτι]{.greek-omitted} [αληθης]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εν]{.greek-omitted} [αληθεια]{.greek-omitted} [διδασκεις]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [περι]{.greek-omitted} [ουδενος]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [βλεπεις]{.greek-omitted} [εις]{.greek-omitted} [προσωπον]{.greek-omitted} [ανθρωπων]{.greek-omitted}[22:16]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [αποστελλουσιν]{.greek-omitted} [αυτω]{.greek-omitted} τους μα[θ]{.unclear}ητας αυτων μετα των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπον]{.greek-abbr}]{.greek-added}[22:16 | instance no. 2]{.aside}

ειπε ουν [ημ]{.unclear}[ιν]{.greek-supplied} [τι]{.greek-omitted} [τη]{.greek-added} σοι δοκει εξε[σ]{.unclear}τιν δου[ν]{.unclear}αι κηνσον καισαρι [η]{.unclear} ου[22:17]{.aside}

γνου[ς]{.unclear} δε ο [ιησους]{.greek-abbr} την πο[ν]{.unclear}ηριαν αυτων ειπεν [τι]{.greek-omitted} [τη]{.greek-added} με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} υποκρι[ται]{.unclear}[22:18]{.aside}

[επιδειξατε]{.greek-omitted} [[ε]{.unclear}π[ι]{.unclear}δειξαται]{.greek-added} [μοι]{.unclear} το νομισμα του κηνσου οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις [τινος]{.greek-omitted} [[τ]{.unclear}ηνος]{.greek-added} η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις απο[δοτ]{.unclear}ε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντε[ς]{.unclear} [ε]{.unclear}θα[υ]{.unclear}μασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω [σαδδουκαιοι]{.greek-omitted} [[σ]{.unclear}αδδουκαοι]{.greek-added} [οι]{.greek-omitted} λεγοντες μη ειναι αναστασιν και επηρω[τ]{.unclear}ησαν [αυτον]{.greek-omitted}[22:23]{.aside}

[εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ημερα]{.greek-omitted} [προσηλθον]{.greek-omitted} [αυτω]{.greek-omitted} [σαδδουκαιοι]{.greek-omitted} [οι]{.greek-omitted} [λεγοντες]{.greek-omitted} [μη]{.greek-omitted} [ειναι]{.greek-omitted} [αναστασιν]{.greek-omitted} [και]{.greek-omitted} [επηρωτησαν]{.greek-omitted} αυτον[22:23 | instance no. 2]{.aside}

λεγοντες διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ειπεν εαν τις αποθανη μη [εχων]{.greek-omitted} [εχον]{.greek-added} τεκνα επιγαμβρευσει ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος [γαμησας]{.greek-omitted} [γημας]{.greek-added} ετελευτησεν και μη [εχων]{.greek-omitted} [εχον]{.greek-added} σπερμα αφηκεν την γυναικα [αυτου]{.greek-omitted} τω αδελφω αυ[τ]{.unclear}ου[22:25]{.aside}

ομοιως [δε]{.greek-added} και ο δευτερος και [ο]{.unclear} τ[ρ]{.unclear}ιτος εως των ε[π]{.unclear}τα[22:26]{.aside}

υστερον [δε]{.greek-supplied} [παντων]{.greek-supplied} [απε]{.greek-supplied}θανεν και η γ[υ]{.unclear}νη[22:27]{.aside}

εν τη [αναστασει]{.greek-added} ουν [αναστασει]{.greek-omitted} τινος των επτα εστ[αι]{.greek-supplied} [η]{.greek-added} γυνη παντες γαρ εσχον αυτην [γυναικα]{.greek-added}[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added} μη [ειδοτες]{.greek-omitted} [ιδωτες]{.greek-added} τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ [τη]{.unclear} αναστασει ουτε γαμουσι[ν]{.unclear} ουτε [εκγαμιζονται]{.greek-omitted} [γαμισκονται]{.greek-added} αλ[λ]{.unclear} ως αγγε[λ]{.unclear}οι [του]{.greek-omitted} [θεου]{.greek-omitted} εν [ουρανω]{.greek-abbr} εισιν[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανε[γ]{.unclear}νωτε το ρηθεν [υμιν]{.greek-omitted} υπο του [θεου]{.greek-abbr} [λεγοντος]{.greek-omitted}[22:31]{.aside}

[περι]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [αναστασεως]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [ουκ]{.greek-omitted} [ανεγνωτε]{.greek-omitted} [το]{.greek-omitted} [ρηθεν]{.greek-omitted} [υμιν]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} λεγοντος[22:31 | instance no. 2]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες ο[ι]{.unclear} οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημω[σ]{.unclear}εν]{.greek-added} τους σαδδουκ[α]{.unclear}ιους συνη[χθ]{.unclear}ησαν επι [τ]{.unclear}ο αυ[τ]{.unclear}[ο]{.greek-supplied}[22:34]{.aside}

και [επη]{.greek-supplied}ρωτησε[ν]{.unclear} [εις]{.greek-supplied} εξ αυτων [νομικος]{.greek-omitted} [πειραζων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγων]{.greek-omitted}[22:35]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} [επηρωτησεν]{.greek-omitted} [εις]{.greek-omitted} [εξ]{.greek-omitted} [αυτων]{.greek-omitted} [ν]{.unclear}ομικος [τις]{.greek-added} [προσηλθεν]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [πειρα]{.unclear}ζων αυτον και λεγων[22:35 | instance no. 2]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη καρδια σου και εν ολη ψυχη σου [και]{.greek-supplied} [ε]{.greek-supplied}ν ολη τη διανοια σου[22:37]{.aside}

αυτη [εστιν]{.greek-supplied} [[η]{.greek-supplied}]{.greek-added} [πρωτη]{.greek-omitted} [[π]{.unclear}ρωτι]{.greek-added} και μεγαλη εντολ[η]{.unclear}[22:38]{.aside}

δευτερα δε ομοια αυτη [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων [επηρωτησεν]{.greek-omitted} [επειρωτησεν]{.greek-added} αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι [υμιν]{.greek-omitted} [δοκει]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [τινος]{.greek-omitted} [υιος]{.greek-omitted} [εστιν]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [του]{.greek-omitted} [δαυιδ]{.greek-omitted}[22:42]{.aside}

### Chapter 23

[οστις]{.greek-omitted} [δε]{.greek-omitted} [υψωσει]{.greek-omitted} [εαυτον]{.greek-omitted} [ταπεινωθησεται]{.greek-omitted} και [οστις]{.greek-omitted} [οστης]{.greek-added} ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειεται]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθαι]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιεται]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χειρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχο[με]{.unclear}νοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθαι]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [περιαγετε]{.greek-omitted} [περιαγεται]{.greek-added} την θαλασσαν και την ξηραν [ποιησαι]{.greek-omitted} [ποιησε]{.greek-added} ενα προσηλυτον και οταν [γενηται]{.greek-omitted} [γενητε]{.greek-added} ποιειτε αυτον υιον [γεεννης]{.greek-omitted} [γεενης]{.greek-added} [διπλοτερον]{.greek-omitted} [διπλωτερον]{.greek-added} υμων[23:15]{.aside}

ουαι υμιν [οδηγοι]{.greek-omitted} [οδιγοι]{.greek-added} τυφλοι οι λεγοντες ος αν [ομοση]{.greek-omitted} [ομωσει]{.greek-added} εν τω ναω ουδεν [εστιν]{.greek-omitted} [εστην]{.greek-added} ος δ αν ομοση εν τω χρυσω του ναου [οφειλει]{.greek-omitted}[23:16]{.aside}

[ουαι]{.greek-omitted} [υμιν]{.greek-omitted} [οδηγοι]{.greek-omitted} [τυφλοι]{.greek-omitted} [οι]{.greek-omitted} [λεγοντες]{.greek-omitted} [ος]{.greek-omitted} [αν]{.greek-omitted} [ομοση]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ναω]{.greek-omitted} [ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [ομοση]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [χρυσω]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [οφειλει]{.greek-omitted} [οφιλει]{.greek-added}[23:16 | instance no. 2]{.aside}

μωροι και τυφλοι [τις]{.greek-omitted} [της]{.greek-added} γαρ μειζων [εστιν]{.greek-omitted} [εστην]{.greek-added} ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος εαν [ο]{.unclear}μοση εν τω θυσιαστηριω ουδεν [εστιν]{.greek-omitted} [εστην]{.greek-added} ος δ αν [ομοση]{.greek-omitted} [ωμωσης]{.greek-added} εν τω δωρω τω επανω αυτου [οφειλει]{.greek-omitted} [οφιλει]{.greek-added}[23:18]{.aside}

μωροι και τυφλοι [τι]{.greek-omitted} [της]{.greek-added} γαρ [εστην]{.greek-added} [μειζον]{.greek-omitted} [μειζων]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} δωρον [η]{.greek-omitted} [το]{.greek-omitted} [θυσιαστηριον]{.greek-omitted} [το]{.greek-omitted} [αγιαζον]{.greek-omitted} [το]{.greek-omitted} [δωρον]{.greek-omitted}[23:19]{.aside}

ο ουν [ομοσας]{.greek-omitted} [ωμωσας]{.greek-added} εν τω θυσιαστηριω [ομνυει]{.greek-omitted} [ωμνοιει]{.greek-added} εν αυτω και εν πασιν τοις επανω αυτου[23:20]{.aside}

και [ο]{.greek-omitted} [ομοσας]{.greek-omitted} [ω]{.greek-added} [ωμωσας]{.greek-added} εν τω ναω [ομνυει]{.greek-omitted} [ομνοιει]{.greek-added} εν αυτω και εν τω [κατοικησαντι]{.greek-omitted} [κατοικισαντι]{.greek-added} αυτον[23:21]{.aside}

και ο [ομοσας]{.greek-omitted} [ωμωσας]{.greek-added} εν τω [ουρανω]{.greek-abbr} [ομνυει]{.greek-omitted} [ωμνυει]{.greek-added} εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το κυμινον και αφηκατε τα [βαρυτερα]{.greek-omitted} [βαρεα]{.greek-added} του νομου την κρισιν και [τον]{.greek-omitted} [το]{.greek-added} [ελεον]{.greek-omitted} [ελεος]{.greek-added} και την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} ταυτα [[δ]{.unclear}ε]{.greek-added} εδει ποιησαι [κακεινα]{.greek-omitted} [μη]{.greek-omitted} [αφιεναι]{.greek-omitted}[23:23]{.aside}

### Chapter 25

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [ο]{.greek-omitted} [τα]{.greek-omitted} [πεντε]{.greek-omitted} [ταλαντα]{.greek-omitted} [λαβων]{.greek-omitted} [προσηνεγκεν]{.greek-omitted} [αλλα]{.greek-omitted} [πεντε]{.greek-omitted} [ταλαντα]{.greek-omitted} [λεγων]{.greek-omitted} [κυριε]{.greek-omitted} [πεντε]{.greek-omitted} [ταλαντα]{.greek-omitted} [μοι]{.greek-omitted} [παρεδωκας]{.greek-omitted} [ρεδωκας]{.greek-added} ιδε [αλλα]{.greek-omitted} πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη δε αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [ην]{.greek-added} πιστος επι πολλω[ν]{.unclear} σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα [λαβων]{.corr} ειπεν [κυριε]{.greek-abbr} δυο ταλαντα [μ]{.unclear}οι [π]{.unclear}αρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [εις]{.greek-added} πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον [ειληφως]{.greek-omitted} [ηλιφως]{.greek-added} ειπεν [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ [εσπειρας]{.greek-omitted} [εσπηρας]{.greek-added} και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και [φοβηθεις]{.greek-omitted} [φοβιθεις]{.greek-added} απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε [ηδεις]{.greek-omitted} [ιδεις]{.greek-added} οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν [ου]{.greek-omitted} [διεσκορπισα]{.greek-omitted}[25:26]{.aside}

[αποκριθεις]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [πονηρε]{.greek-omitted} [δουλε]{.greek-omitted} [και]{.greek-omitted} [οκνηρε]{.greek-omitted} [ηδεις]{.greek-omitted} [οτι]{.greek-omitted} [θεριζω]{.greek-omitted} [οπου]{.greek-omitted} [ουκ]{.greek-omitted} [εσπειρα]{.greek-omitted} [και]{.greek-omitted} [συναγω]{.greek-omitted} [οθεν]{.greek-omitted} ου διεσκορπισα[25:26 | instance no. 2]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις [τραπεζιταις]{.greek-omitted} [τραπεζηταις]{.greek-added} και ελθων εγω [εκομισαμην]{.greek-omitted} [εκομησαμην]{.greek-added} αν [το]{.greek-omitted} [τω]{.greek-added} εμον συν τοκω[25:27]{.aside}

[αρατε]{.greek-omitted} [αραται]{.greek-added} ουν απ αυτου το ταλαντον και [δοτε]{.greek-omitted} [τω]{.greek-omitted} [δ[ο]{.unclear}ται]{.greek-added} [το]{.greek-added} εχοντι τα δεκα ταλαντα[25:28]{.aside}

[τω]{.greek-omitted} [το]{.greek-added} γαρ εχοντι παντι δοθησεται [και]{.greek-omitted} [περισσευθησεται]{.greek-omitted} απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον [εκβαλετε]{.greek-omitted} [εκβαλεται]{.greek-added} εις το σκοτος το [εξωτερον]{.greek-omitted} [εξοτερον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} οταν δε ελθη ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι [αγιοι]{.greek-omitted} αγγελοι μετ αυτου τοτε [καθισει]{.greek-omitted} [καθησει]{.greek-added} επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και [αφοριει]{.greek-omitted} [αφορεισι]{.greek-added} αυτους απ αλληλων ωσπερ ο ποιμην [αφοριζει]{.greek-omitted} [αφορειζει]{.greek-added} τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added}[25:33]{.aside}

τοτε ερει [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [τοις]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [αυτου]{.greek-omitted} [δευτε]{.greek-omitted} [οι]{.greek-omitted} [ευλογημενοι]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted} [κληρονομησατε]{.greek-omitted} [την]{.greek-omitted} [ητοιμασμενην]{.greek-omitted} [υμιν]{.greek-omitted} [βασιλειαν]{.greek-omitted} [απο]{.greek-omitted} [καταβολης]{.greek-omitted} [κοσμου]{.greek-omitted}[25:34]{.aside}

### Chapter 26

[τοτε]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [παντες]{.greek-omitted} [υμεις]{.greek-omitted} [σκανδαλισθησεσθε]{.greek-omitted} [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} [γεγραπται]{.greek-omitted} [γαρ]{.greek-omitted} [παταξω]{.greek-omitted} [τον]{.greek-omitted} [ποιμενα]{.greek-omitted} [και]{.greek-omitted} [διασκορπισθησεται]{.greek-omitted} τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει [και]{.greek-added} παντες [σκανδαλισθησονται]{.greek-omitted} [σκανδαλησθησεσθα[ι]{.unclear}]{.greek-added} εν σοι εγω [δε]{.greek-omitted} ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη [νυκτι]{.greek-omitted} [νυκτ[η]{.unclear}]{.greek-added} πριν αλεκτορα [φ]{.unclear}ωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} [απαρνηση]{.greek-omitted} [απαρνησι]{.greek-added} με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε απαρνησωμ[αι]{.greek-supplied} [ο]{.greek-supplied}μοιως δε και παν[τ]{.greek-supplied}[ες]{.unclear} [οι]{.unclear} [μαθηται]{.unclear} [ε]{.greek-supplied}ιπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον [λεγομενον]{.greek-omitted} [λεγωμενον]{.greek-added} [γεθσημανη]{.greek-omitted} [γεθσεμανι]{.greek-added} και λεγει τοις μαθηταις [καθισατε]{.greek-omitted} [καθησατ[ε]{.unclear}]{.greek-added} αυτου εως [ου]{.greek-omitted} [αν]{.greek-added} απελθων προσευξωμαι εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους [δυο]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added} υιους ζεβεδαιου ηρξατο λυπεισθαι κα[ι]{.greek-supplied} [αδημονειν]{.greek-omitted} [[α]{.unclear}δημονην]{.greek-added}[26:37]{.aside}

τοτε λεγει αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} περιλυπος [εστιν]{.greek-omitted} [εστην]{.greek-added} η ψυχη μου εως θανατου μεινατε [ω]{.unclear}δε και [γρηγορειτε]{.greek-omitted} [γρηγωρειτε]{.greek-added} μετ εμου[26:38]{.aside}

και [προσελθων]{.greek-omitted} [προελθ[ων]{.unclear}]{.greek-added} μικρον [επεσεν]{.unclear} επι προσωπον [αυτου]{.unclear} [προσευχομενος]{.greek-omitted} [και]{.greek-omitted} [λεγων]{.greek-omitted} [πατερ]{.greek-omitted} [μου]{.greek-omitted} [ει]{.greek-omitted} [δυνατον]{.greek-omitted} [εστιν]{.greek-omitted} [παρελθετω]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [τουτο]{.greek-omitted} [πλην]{.greek-omitted} [ουχ]{.greek-omitted} [ως]{.greek-omitted} [εγω]{.greek-omitted} [θελω]{.greek-omitted} [αλλ]{.greek-omitted} [ως]{.greek-omitted} [συ]{.greek-omitted}[26:39]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [μικρον]{.greek-omitted} [επεσεν]{.greek-omitted} [επι]{.greek-omitted} [προσωπον]{.greek-omitted} [αυτου]{.greek-omitted} προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [εστην]{.greek-added} παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως [συ]{.greek-omitted} [σοι]{.greek-added}[26:39 | instance no. 2]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ [ισχυσατε]{.greek-omitted} [ισχυσαται]{.greek-added} μιαν ωραν γρηγορησα[ι]{.unclear} μετ εμου[26:40]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορητε]{.greek-added} και προσευχεσθε ινα μη εισελθ[η]{.unclear}τε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον [η]{.unclear} δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται [τουτο]{.greek-omitted} το ποτηριον [τουτο]{.greek-added} παρελθειν απ εμου εαν μη [αυτο]{.greek-omitted} [αυτω]{.greek-added} πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων [ευρισκει]{.greek-omitted} [ηυρεν]{.greek-added} αυτους [παλιν]{.greek-omitted} [παλην]{.greek-added} καθευδοντας ησαν γαρ [αυτων]{.greek-omitted} οι οφθαλμοι [αυτων]{.greek-added} βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων [παλιν]{.greek-omitted} προσηυξατο [παλην]{.greek-added} εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας [αυτου]{.greek-omitted} και λεγει αυτοις [καθευδετε]{.greek-omitted} [το]{.greek-omitted} [λοιπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [ιδου]{.greek-omitted} [ηγγικεν]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδιδοται]{.greek-omitted} [εις]{.greek-omitted} [χειρας]{.greek-omitted} [αμαρτωλων]{.greek-omitted}[26:45]{.aside}

[α]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [κρατησαντες]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [απηγαγον]{.greek-omitted} [προς]{.greek-omitted} [καιαφαν]{.greek-omitted} [τον]{.greek-omitted} [αρχιερεα]{.greek-omitted} οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω απο μακροθεν εως της αυλης του αρχιερεως και [ε]{.unclear}ισελθων εσω [εκαθητο]{.greek-omitted} [εκαθητω]{.greek-added} μετα των υπηρετων ιδειν [τ]{.unclear}ο τελος[26:58]{.aside}

οι δε αρχιερεις και [οι]{.greek-supplied} [πρε]{.greek-supplied}[σβ]{.unclear}υτεροι και [το]{.greek-supplied} [σ]{.unclear}υνεδριον ολον εζητουν [ψευ]{.unclear}δομαρτυριαν κατα το[υ]{.unclear} [ιησου]{.greek-abbr} οπως θανατωσωσιν [αυτον]{.unclear}[26:59]{.aside}

και ουχ [ευρον]{.greek-omitted} [ηυρον]{.greek-added} [και]{.greek-omitted} πολλων [[πρ]{.unclear}οσελθοντων]{.greek-added} [ψευ]{.unclear}δομαρτυρων [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντων]{.greek-omitted} [προσελθοντες]{.greek-added} [ουχ]{.greek-omitted} [ευρον]{.greek-omitted} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} [ειπον]{.greek-omitted} [ειπων]{.greek-added} ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερ[ω]{.unclear}ν οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν α[υ]{.unclear}[τ]{.greek-supplied}[ω]{.unclear} ουδεν α[ποκ]{.unclear}ρινη τι ου[τοι]{.unclear} [σο]{.unclear}υ καταμα[ρ]{.unclear}τυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και [απο]{.unclear}κριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κα[τα]{.unclear} [του]{.unclear} [θεου]{.greek-abbr} [του]{.unclear} ζωντος ινα ημιν ειπης [ει]{.unclear} [συ]{.unclear} [ει]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[26:63]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [εσιωπα]{.greek-omitted} [και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [αρχιερευς]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [εξορκιζω]{.greek-omitted} [σε]{.greek-omitted} [κατα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [ζωντος]{.greek-omitted} [ινα]{.greek-omitted} [ημιν]{.greek-omitted} [ειπης]{.greek-omitted} [ει]{.greek-omitted} [συ]{.greek-omitted} ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} [του]{.greek-added} [ζωντος]{.greek-added}[26:63 | instance no. 2]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερριξεν]{.greek-added} τα ιματια αυτου λεγων [οτι]{.greek-omitted} εβλασφημησεν τι ετι [χ]{.unclear}ρειαν εχομεν μαρτυρων ιδε νυν [ηκουσατε]{.greek-omitted} [ηκουσαται]{.greek-added} την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου [εστιν]{.greek-omitted} [εστην]{.greek-added}[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και εκολαφισαν αυτον οι δε [ερραπισαν]{.greek-omitted} [εραπησαν]{.greek-added}[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μ[ι]{.unclear}α παιδισκη λεγουσα και συ [ησθα]{.greek-omitted} [εισθα]{.greek-added} μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο [ε]{.unclear}μπροσθεν αυτων παντων λεγων ουκ οιδα τι λεγεις [ουδε]{.greek-added} [επισταμαι]{.greek-added}[26:70]{.aside}

εξελθοντα δε αυτον εις τον [πυλωνα]{.greek-omitted} [πυλω]{.greek-added} [ειδεν]{.greek-omitted} [αυτον]{.greek-omitted} [αλλη]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [εκει]{.greek-omitted} [και]{.greek-omitted} [ουτος]{.greek-omitted} [ην]{.greek-omitted} [μετα]{.greek-omitted} [ιησου]{.greek-omitted} [του]{.greek-omitted} [ναζωραιου]{.greek-omitted}[26:71]{.aside}

### Chapter 27

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φραγελλωσας παρεδωκεν [αυτοις]{.greek-added} ινα σταυρωθη[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το [πραιτωριον]{.greek-omitted} [πραιτοριον]{.greek-added} συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν [αυτω]{.greek-omitted} [αυτο]{.greek-added} χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων [επεθηκαν]{.greek-omitted} [εθηκαν]{.greek-added} επι την κεφαλην αυτου και καλα[μον]{.unclear} [επι]{.greek-omitted} [[εν]{.unclear}]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [δεξιαν]{.greek-omitted} [δεξια]{.greek-added} αυτου και γονυπετησαντες ε[μ]{.unclear}προσθεν [αυ]{.unclear}[τ]{.unclear}ου [ενεπαιζον]{.greek-omitted} [ενεπεζον]{.greek-added} [αυτω]{.greek-omitted} [[α]{.unclear}υτων]{.greek-added} λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και [εμπτυσαντες]{.greek-omitted} [ενπτυσαντες]{.greek-added} εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} [αυτω]{.greek-omitted} [αυτο]{.greek-added} εξεδυσαν αυτ[ο]{.unclear}ν την χλαμυδα και ενεδυσαν [αυτον]{.greek-omitted} [αυτων]{.greek-added} τα ιματια αυτου και απηγαγον αυτον εις το σταυρωσαι[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} [κυρ[η]{.unclear}]{.greek-added} [κυρηναιον]{.greek-omitted} [ονοματι]{.greek-omitted} [σιμωνα]{.greek-omitted} [τουτον]{.greek-omitted} [ηγγαρευσαν]{.greek-omitted} [ινα]{.greek-omitted} [αρη]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted} [αυτου]{.greek-omitted}[27:32]{.aside}

[ναιον]{.greek-added} [εξερχομενοι]{.greek-omitted} [δε]{.greek-omitted} [ευρον]{.greek-omitted} [ανθρωπον]{.greek-omitted} [κυρηναιον]{.greek-omitted} ονοματι σι[μω]{.unclear}να τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32 | instance no. 2]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα ο [εστιν]{.greek-omitted} [εστην]{.greek-added} [λεγομενος]{.greek-omitted} [λεγομενον]{.greek-added} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμ[ιγ]{.unclear}μενον και γευσαμενος ουκ ηθελεν πιειν[27:34]{.aside}

σταυρωσαντες δε αυτον διεμερισαντο τα ιματια αυτου [βαλλοντες]{.greek-omitted} [βαλοντες]{.greek-added} κληρον [ινα]{.greek-added} [πληρωθη]{.greek-added} [το]{.greek-added} [ρηθεν]{.greek-added} [δια]{.greek-added} [του]{.greek-added} [προφητου]{.greek-added} [διεμερισαντο]{.greek-added} [τα]{.greek-added} [ιματια]{.greek-added} [μου]{.greek-added} [εαυτοις]{.greek-added} [και]{.greek-added} [επι]{.greek-added} [τον]{.greek-added} [ιματισμον]{.greek-added} [μου]{.greek-added} [εβαλον]{.greek-added} [κληρον]{.greek-added}[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστ[ι]{.unclear}ν [ιησους]{.greek-abbr} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε σταυρουνται συν αυτω δυο λησται εις εκ δ[ε]{.unclear}ξιων και εις εξ [ευωνυμων]{.greek-omitted} [ευ[ο]{.unclear}νυμων]{.greek-added}[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο [καταλυων]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [και]{.greek-omitted} [κα]{.greek-added} [εν]{.greek-omitted} [τρισιν]{.greek-omitted} [ημεραις]{.greek-omitted} [οικοδομων]{.greek-omitted} [σωσον]{.greek-omitted} [σεαυτον]{.greek-omitted} [ει]{.greek-omitted} [υιος]{.greek-omitted} [ει]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [καταβηθι]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [σταυρου]{.greek-omitted}[27:40]{.aside}

## The Gospel of Mark

### Chapter 1

[οψιας]{.greek-omitted} [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [οτε]{.greek-omitted} [εδυ]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [εφερον]{.greek-omitted} προς αυτον παντας [τους]{.unclear} [κακως]{.unclear} εχον[τ]{.unclear}ας και τους δ[αι]{.greek-supplied}μονιζομεν[ο]{.unclear}υς[1:32]{.aside}

και η πο[λι]{.unclear}ς [ο]{.greek-supplied}λη επι[σ]{.unclear}υνη[γ]{.unclear}μενη η[ν]{.unclear} προς την θυραν[1:33]{.aside}

και ε[θ]{.unclear}εραπευσεν πολλ[ο]{.unclear}[υ]{.greek-supplied}ς [κ]{.unclear}ακ[ω]{.unclear}ς εχον[τ]{.unclear}ας π[ο]{.unclear}ικ[ιλα]{.unclear}ις νοσοις κα[ι]{.greek-supplied} [δα]{.greek-supplied}ιμονια πολ[λα]{.greek-supplied} εξεβ[α]{.unclear}[λ]{.greek-supplied}εν [και]{.unclear} [ο]{.greek-supplied}υκ [ηφιεν]{.greek-omitted} [[ηφ]{.greek-supplied}[η]{.unclear}εν]{.greek-added} λαλειν τα δαιμο[ν]{.unclear}ια οτι ηδεισαν [τον]{.greek-added} [[χριστον]{.greek-abbr}]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι [εννυχον]{.greek-omitted} [ε[νν]{.greek-supplied}[υ]{.unclear}χ[α]{.unclear}]{.greek-added} [λιαν]{.greek-omitted} [[λ]{.greek-supplied}ια]{.greek-added} ανα[σ]{.unclear}τα[ς]{.unclear} εξηλθεν και απηλθε[ν]{.greek-supplied} [ε]{.greek-supplied}ις ερ[η]{.unclear}μον τοπον [κ]{.unclear}α[κε]{.unclear}ι προσηυχε[το]{.greek-supplied}[1:35]{.aside}

κα[ι]{.unclear} κα[τ]{.unclear}[ε]{.greek-supplied}διωξαν αυτον ο [τε]{.greek-added} σιμων και οι μετ αυτου[1:36]{.aside}

και [ευροντες]{.greek-omitted} [ευρ[ο]{.unclear}ντ[ε]{.unclear}ς[ς]{.greek-supplied}]{.greek-added} [α]{.greek-supplied}υτον [λ]{.unclear}ε[γο]{.greek-supplied}[υ]{.unclear}σιν αυτω οτι παντ[ες]{.unclear} [σ]{.unclear}ε ζητο[υ]{.unclear}σ[ι]{.unclear}ν[1:37]{.aside}

και λεγ[ει]{.greek-supplied} [αυ]{.greek-supplied}[τ]{.unclear}[ο]{.greek-supplied}ι[ς]{.unclear} αγωμ[ε]{.unclear}ν εις τας εχομενας κ[ωμ]{.unclear}οπολει[ς]{.unclear} ινα [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} [κ]{.unclear}ηρυ[ξ]{.unclear}ω εις [τ]{.unclear}ο[υ]{.unclear}[το]{.greek-supplied} γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [[τ]{.unclear}ας]{.greek-added} [συναγωγαις]{.greek-omitted} [σ[υ]{.unclear}ναγω[γ]{.unclear}ας]{.greek-added} [αυ]{.greek-supplied}[των]{.unclear} [και]{.greek-added} εις [ολ]{.unclear}ην την [γ]{.unclear}αλιλαια[ν]{.unclear} και τα [δα]{.unclear}ιμονια ε[κβ]{.unclear}αλλων[1:39]{.aside}

κ[α]{.unclear}ι [ε]{.unclear}ρχεται [π]{.unclear}ρ[ος]{.unclear} [αυτ]{.unclear}ον [λ]{.unclear}επρ[ος]{.unclear} [παρακαλων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [γονυπετων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγων]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [εαν]{.greek-omitted} [θελης]{.greek-omitted} [δυνασαι]{.greek-omitted} [με]{.greek-omitted} [καθαρισαι]{.greek-omitted}[1:40]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [λεπρος]{.greek-omitted} παρακαλων αυτον και [γονυπετων]{.greek-omitted} [γωνυπετων]{.greek-added} αυτον και λε[γ]{.unclear}[ω]{.greek-supplied}[ν]{.unclear} αυτω [[αυτ[ο]{.unclear}]{.corr}]{.greek-added} οτι εαν [θελης]{.greek-omitted} [[θ]{.greek-supplied}ελε[ι]{.unclear}ς]{.greek-added} [[κυριε]{.greek-abbr}]{.greek-added} δυνασαι με κα[θ]{.unclear}αρισαι[1:40 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισ[θ]{.unclear}ε[ι]{.unclear}[ς]{.greek-supplied} εκτεινας την χειρα ηψατο αυτου και λεγει αυτω [θ]{.unclear}[ε]{.greek-supplied}λ[ω]{.unclear} [κ]{.unclear}αθαρισ[θ]{.unclear}ητι[1:41]{.aside}

και ει[πο]{.unclear}ντος αυτου ευθ[ε]{.greek-supplied}[ω]{.unclear}ς απηλ[θ]{.unclear}εν [[η]{.unclear}]{.greek-added} [[λε]{.unclear}πρα]{.greek-added} α[π]{.greek-supplied} α[υτ]{.unclear}ου [η]{.greek-omitted} [λεπρα]{.greek-omitted} και [εκαθαρισθη]{.greek-omitted} [ε[καθ]{.unclear}ερισ[θ]{.unclear}η]{.greek-added}[1:42]{.aside}

και [εμ]{.greek-supplied}[β]{.unclear}ρι[μ]{.unclear}ησαμε[ν]{.unclear}ος αυτ[ω]{.unclear} ευ[θε]{.greek-supplied}[ω]{.unclear}ς ε[ξε]{.unclear}βαλεν [αυ]{.unclear}τον[1:43]{.aside}

[κ]{.unclear}αι λεγει αυτω ορα μηδενι μηδε[ν]{.greek-supplied} ειπης αλλ υπα[γ]{.unclear}ε σεαυτον δειξον τω ιερει [και]{.unclear} προ[σ]{.unclear}ενεγκ[ε]{.unclear} περι τ[ο]{.greek-supplied}υ καθαρισμου σ[ο]{.unclear}υ α προσεταξεν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [ει]{.greek-supplied}ς [μ]{.greek-supplied}[α]{.unclear}ρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρ[υ]{.unclear}σσ[ει]{.unclear}[ν]{.greek-supplied} πολλα και διαφ[η]{.unclear}μιζει[ν]{.unclear} [τ]{.unclear}ον λ[ο]{.unclear}γον [ω]{.unclear}στε [μ]{.unclear}ηκετι [αυ]{.unclear}τ[ον]{.unclear} [δ]{.unclear}υνασθ[α]{.greek-supplied}ι φανερ[ω]{.unclear}ς εις π[ολ]{.unclear}[ιν]{.greek-supplied} [ε]{.greek-supplied}[ισελθ]{.unclear}ειν αλλ ε[ξ]{.unclear}[ω]{.greek-supplied} [εν]{.greek-omitted} [[επ]{.greek-supplied}]{.greek-added} [ε]{.unclear}ρη[μοις]{.greek-supplied} τοποις η[ν]{.unclear} [κα]{.unclear}ι ηρχο[ντο]{.unclear} [πρ]{.unclear}[ος]{.greek-supplied} [α]{.greek-supplied}[υ]{.unclear}τ[ο]{.unclear}ν [πανταχοθεν]{.greek-omitted} [π[αντοθ]{.greek-supplied}εν]{.greek-added}[1:45]{.aside}

### Chapter 2

και [ε]{.unclear}ισηλθ[εν]{.greek-supplied} [π]{.greek-supplied}α[λ]{.unclear}ιν εις [κ]{.unclear}απερ[ναο]{.unclear}υμ [δι]{.greek-omitted} [ημερων]{.greek-omitted} [και]{.greek-omitted} [ηκουσθη]{.greek-omitted} [οτι]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [εστιν]{.greek-omitted}[2:1]{.aside}

### Chapter 8

[ο]{.greek-omitted} [δε]{.greek-omitted} [επιστραφεις]{.greek-omitted} [και]{.greek-omitted} [ιδων]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [επετιμησεν]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [λεγων]{.greek-omitted} [υπαγε]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [σατανα]{.greek-omitted} οτι ου φρονεις τα [το]{.unclear}υ [θεου]{.greek-abbr} αλλα [τ]{.unclear}α [τ]{.greek-supplied}[ω]{.unclear}ν [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκα[λ]{.unclear}εσαμενος τ[ο]{.unclear}ν οχλον συ[ν]{.unclear} τ[οις]{.unclear} μα[θ]{.unclear}ηται[ς]{.unclear} αυτου ειπεν αυ[τ]{.unclear}οις [ει]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελε[ι]{.unclear} [ο]{.unclear}πισω [μου]{.unclear} ακ[ο]{.unclear}λουθειν απαρνησασθω εα[υ]{.unclear}τον κ[αι]{.unclear} [αρατω]{.greek-omitted} [αρατο]{.greek-added} τον σταυρον [αυτου]{.unclear} και ακολουθε[ι]{.unclear}τ[ω]{.unclear} [μοι]{.unclear}[8:34]{.aside}

[[ω]{.unclear}ς]{.greek-added} [ος]{.corr} γαρ αν [θελη]{.greek-omitted} [θελει]{.greek-added} [την]{.unclear} ψυχην [αυ]{.greek-supplied}του σω[σ]{.greek-supplied}αι [απ]{.greek-supplied}ολε[σ]{.greek-supplied}[ε]{.unclear}ι αυ[την]{.greek-supplied} ος [δ]{.unclear} αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την [εαυτου]{.greek-omitted} ψυχην [αυτου]{.greek-added} ενεκεν εμου και [τ]{.greek-supplied}ου ε[υαγγ]{.unclear}ελιου [ουτος]{.greek-omitted} σωσ[ει]{.unclear} αυτην[8:35]{.aside}

τι [γα]{.unclear}ρ ωφελησει [τ[ο]{.unclear}ν]{.greek-added} [ανθρωπον]{.greek-abbr} εα[ν]{.greek-supplied} [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} τον κοσ[μ]{.unclear}ον [ο]{.unclear}λον και [ζημιωθη]{.greek-omitted} [ζημι[ω]{.greek-supplied}θτη]{.greek-added} [την]{.greek-omitted} ψυχη[ν]{.unclear} αυ[τ]{.greek-supplied}[ο]{.unclear}υ[8:36]{.aside}

η τι δ[ωσ]{.unclear}ει αν[θ]{.unclear}ρωπος ανταλλ[α]{.unclear}γ[μα]{.unclear} της ψυχης αυτου[8:37]{.aside}

ος γαρ [ε]{.unclear}α[ν]{.unclear} [ε]{.unclear}πα[ι]{.unclear}σ[χυν]{.unclear}[θ]{.greek-supplied}η [μ]{.unclear}ε και [τ]{.unclear}[ου]{.greek-supplied}ς ε[μους]{.unclear} λ[ο]{.unclear}γους εν [τη]{.greek-supplied} [γενεα]{.greek-omitted} [ταυτη]{.greek-omitted} [τη]{.greek-omitted} [μοιχαλιδι]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλω]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [επαισχυνθησεται]{.greek-omitted} [αυτον]{.greek-omitted} [οταν]{.greek-omitted} [ελθη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δοξη]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [αυτου]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted}[8:38]{.aside}

[ος]{.greek-omitted} [γαρ]{.greek-omitted} [εαν]{.greek-omitted} [επαισχυνθη]{.greek-omitted} [με]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [λογους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} γενεα τα[υ]{.greek-supplied}τη τη [μοιχαλιδι]{.greek-omitted} [μοιχαλιδη]{.greek-added} και [τη]{.greek-added} αμαρτωλω και ο [υιος]{.greek-abbr} τ[ου]{.unclear} [ανθρωπου]{.greek-abbr} επαισχ[υ]{.unclear}ν[θ]{.unclear}η[σεται]{.unclear} αυ[τ]{.greek-supplied}ον ο[τ]{.unclear}αν ελθη [εν]{.unclear} [τ]{.unclear}η δο[ξ]{.unclear}η του [πατρος]{.greek-abbr} αυτ[ου]{.unclear} [μ]{.unclear}[ε]{.greek-supplied}τ[α]{.unclear} των αγγελων τ[ων]{.unclear} αγιων[8:38 | instance no. 2]{.aside}

### Chapter 9

και ελεγεν [αυτοις]{.greek-omitted} [αυτο[ι]{.greek-supplied}ις]{.greek-added} α[μην]{.unclear} λεγ[ω]{.unclear} υμιν [ο]{.unclear}τι εισιν τινες τ[ω]{.greek-supplied}[ν]{.unclear} ω[δ]{.greek-supplied}ε [εστ]{.greek-supplied}ηκοτω[ν]{.unclear} οιτινες ου μη [γευσωνται]{.greek-omitted} [γευ[σο]{.unclear}ν[τ]{.unclear}αι]{.greek-added} θα[ν]{.unclear}ατου εως αν ιδ[ωσι]{.greek-supplied}ν την βασιλει[α]{.unclear}ν του [θεου]{.greek-abbr} εληλυθυιαν ε[ν]{.unclear} δυνα[μει]{.unclear}[9:1]{.aside}

και με[θ]{.unclear} η[μ]{.unclear}ερας εξ παρ[αλαμ]{.unclear}[β]{.unclear}α[νει]{.unclear} ο [ιησους]{.greek-abbr} τον [π]{.unclear}ετρον και τον [[ι]{.unclear}[ω]{.unclear}ανν[η]{.unclear}ν]{.greek-added} [κ[αι]{.unclear}]{.greek-added} ιακ[ω]{.unclear}βον [και]{.greek-omitted} [ιωαννην]{.greek-omitted} και [α]{.unclear}[να]{.greek-supplied}φερει αυτου[ς]{.unclear} εις ορο[ς]{.unclear} [υ]{.unclear}ψηλον κατ ι[δι]{.greek-supplied}αν μονους και μετεμορφω[θη]{.unclear} [εμ]{.unclear}πρ[ο]{.unclear}σ[θε]{.greek-supplied}ν αυτων[9:2]{.aside}

και τα ιματια αυτου εγ[ε]{.unclear}νοντο [στιλβον]{.unclear}τα λευκα [λι]{.unclear}α[ν]{.unclear} [ως]{.unclear} χ[ιων]{.greek-supplied} [οι]{.unclear}α [γ]{.unclear}[να]{.greek-supplied}φευς επι της [γης]{.unclear} ου [δυναται]{.greek-omitted} [λευκαναι]{.greek-omitted}[9:3]{.aside}

### Chapter 10

[οι]{.greek-omitted} [δε]{.greek-omitted} [μαθηται]{.greek-omitted} [εθαμβουντο]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [λογοις]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [παλιν]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [τεκνα]{.greek-omitted} [πως]{.greek-omitted} δυσκολο[ν]{.unclear} [εσ]{.unclear}τιν τους πεποι[θοτ]{.greek-supplied}ας ε[πι]{.unclear} χρημασιν [εις]{.greek-supplied} την βασιλειαν τ[ου]{.unclear} [θεου]{.greek-abbr} εισελ[θ]{.unclear}ειν[10:24]{.aside}

[ευκοπω[τ]{.unclear}ιν]{.greek-added} [ευκοπωτερον]{.corr} [εσ[τ]{.unclear}ιν]{.corr} καμ[η]{.greek-supplied}[λο]{.unclear}ν δια της τρυμαλιας της ραφιδος εισ[ελ]{.unclear}[θ]{.unclear}[ε]{.greek-supplied}ιν η πλο[υ]{.unclear}[σιο]{.unclear}ν εις [τ]{.unclear}ην [βα]{.unclear}[σιλει]{.greek-supplied}α[ν]{.unclear} του [θεου]{.greek-abbr} εισελ[θ]{.unclear}ειν[10:25]{.aside}

[ο]{.unclear}ι δ[ε]{.unclear} περι[σσ]{.unclear}ως ε[ξ]{.unclear}επλησσ[ο]{.unclear}ντ[ο]{.unclear} λεγοντ[ε]{.unclear}ς προ[ς]{.greek-supplied} [ε]{.greek-supplied}αυτου[ς]{.greek-supplied} και τ[ις]{.greek-supplied} [δ]{.greek-supplied}[υν]{.unclear}[α]{.greek-supplied}ται [σωθ]{.greek-supplied}ηναι[10:26]{.aside}

εμ[βλ]{.unclear}εψας [δε]{.greek-omitted} αυ[τ]{.greek-supplied}οις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλ[λ]{.unclear} ου παρα [[τω]{.greek-supplied}]{.greek-added} [θεω]{.greek-abbr} παντα γαρ δυνατα εστιν παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο ο πετρ[ος]{.unclear} λεγειν αυ[τω]{.unclear} ιδου ημεις αφηκαμεν παντα και [ηκολουθησαμεν]{.greek-omitted} [ηκολουθηκα[μεν]{.unclear}]{.greek-added} [σοι]{.unclear}[10:28]{.aside}

αποκριθ[ε]{.unclear}ι[ς]{.unclear} [ο]{.unclear} [ιησους]{.greek-abbr} ε[ι]{.unclear}πεν αμην λεγ[ω]{.unclear} υμιν ουδ[ε]{.unclear}ις εστιν ο[ς]{.unclear} [α]{.unclear}φηκεν οικ[ι]{.unclear}αν η αδελφ[ο]{.unclear}υ[ς]{.unclear} η αδε[λ]{.unclear}φας η [[μητερα]{.greek-abbr}]{.greek-added} [[η]{.unclear}]{.greek-added} [πατερα]{.greek-abbr} [η]{.greek-omitted} [μητερα]{.greek-omitted} [η]{.unclear} γυναι[κ]{.unclear}α η [τε]{.unclear}[κνα]{.unclear} η αγρ[ους]{.greek-supplied} ενεκεν [εμου]{.greek-supplied} [και]{.greek-omitted} [ενεκεν]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted}[10:29]{.aside}

[αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ουδεις]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} [αφηκεν]{.greek-omitted} [οικιαν]{.greek-omitted} [η]{.greek-omitted} [αδελφους]{.greek-omitted} [η]{.greek-omitted} [αδελφας]{.greek-omitted} [η]{.greek-omitted} [πατερα]{.greek-omitted} [η]{.greek-omitted} [μητερα]{.greek-omitted} [η]{.greek-omitted} [γυναικα]{.greek-omitted} [η]{.greek-omitted} [τεκνα]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} και ενεκ[ε]{.unclear}ν του ευαγγελιου[10:29 | instance no. 2]{.aside}

εαν μη λα[β]{.unclear}η εκατονταπλασιονα ν[υ]{.unclear}ν εν τ[ω]{.unclear} καιρω [τ]{.unclear}ουτω ο[ι]{.unclear}κ[ι]{.unclear}ας και αδελφους και αδελφας και μ[η]{.unclear}τερας και τεκνα και αγρ[ου]{.unclear}ς μετα διωγμων και εν τ[ω]{.unclear} αιωνι τ[ω]{.unclear} [ε]{.greek-supplied}ρχ[ομ]{.unclear}ενω [ζωη]{.unclear}ν αι[ω]{.unclear}νιο[ν]{.unclear}[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατ[ο]{.greek-supplied}ι πρω[το]{.unclear}ι[10:31]{.aside}

ησαν δε [ε]{.greek-supplied}ν τη οδω αν[α]{.unclear}[βαινον]{.greek-supplied}[τες]{.unclear} ει[ς]{.unclear} [ι]{.unclear}ερ[οσο]{.unclear}λυμα [κ]{.unclear}αι ην πρ[ο]{.unclear}α[γω]{.greek-supplied}ν αυτους ο [ιησους]{.greek-abbr} και ε[θ]{.unclear}αμβο[υ]{.unclear}ντ[ο]{.unclear} [κ]{.unclear}αι [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} παραλαβων παλ[ι]{.unclear}ν του[ς]{.unclear} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ηρ[ξ]{.greek-supplied}α[το]{.unclear} αυτοις λε[γ]{.greek-supplied}ειν τα μελ[λο]{.unclear}ν[τ]{.unclear}α αυτ[ω]{.unclear} [σ]{.unclear}υ[μβ]{.unclear}αινειν[10:32]{.aside}

οτι ιδου ανα[β]{.unclear}αινο[μ]{.unclear}εν εις ιερ[ο]{.unclear}σ[ο]{.greek-supplied}λυμα και [ο]{.unclear} [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησ[ε]{.unclear}[τ]{.unclear}α[ι]{.greek-supplied} τοι[ς]{.greek-supplied} [α]{.unclear}ρ[χ]{.unclear}ιερευ[σ]{.unclear}ιν και [[τ]{.unclear}[οι]{.greek-supplied}[ς]{.unclear}]{.greek-added} [γ]{.unclear}ρ[α]{.unclear}μ[μα]{.greek-supplied}[τε]{.unclear}υσιν [κ]{.unclear}α[ι]{.unclear} [κ]{.unclear}[ατ]{.greek-supplied}ακρινου[σι]{.greek-supplied}[ν]{.unclear} α[υ]{.unclear}τον [θα]{.greek-added} [θανατω]{.greek-omitted} [και]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted}[10:33]{.aside}

[[να]{.greek-supplied}τω]{.greek-added} [οτι]{.greek-omitted} [ιδου]{.greek-omitted} [αναβαινομεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} και [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδοθησεται]{.greek-omitted} [τοις]{.greek-omitted} [αρχιερευσιν]{.greek-omitted} [και]{.greek-omitted} [γραμματευσιν]{.greek-omitted} [και]{.greek-omitted} [κατακρινουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [θανατω]{.greek-omitted} [και]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [παρ[α]{.unclear}[δ]{.greek-supplied}οσουσιν]{.greek-added} αυτο[ν]{.unclear} τ[ο]{.unclear}[ις]{.greek-supplied} εθνεσιν[10:33 | instance no. 2]{.aside}

και [εμπαιξουσιν]{.greek-omitted} [εμπαι[ξ]{.unclear}ωσιν]{.greek-added} αυτω και μ[α]{.greek-supplied}σ[τ]{.unclear}ιγωσουσιν αυτον και [εμπτυσουσιν]{.greek-omitted} [εμπτυσωσιν]{.greek-added} αυτω και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προ[σ]{.unclear}πορ[ε]{.unclear}υονται αυ[τω]{.greek-supplied} ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λε[γο]{.unclear}ντε[ς]{.unclear} διδ[α]{.unclear}σκαλε θελομεν ινα ο εαν [σ[ε]{.unclear}]{.greek-added} [α]{.unclear}ιτησωμ[ε]{.unclear}ν ποιηση[ς]{.unclear} η[μ]{.unclear}ιν[10:35]{.aside}

ο δε ειπεν αυτοις τι [θ]{.unclear}ελετε [ποιησαι]{.greek-omitted} μ[ε]{.greek-supplied} [[ποιησω]{.greek-supplied}]{.greek-added} [υ]{.greek-supplied}μιν[10:36]{.aside}

οι δε [ειπον]{.greek-supplied} αυτω δος ημιν ινα εις εκ δ[ε]{.greek-supplied}[ξ]{.unclear}ι[ω]{.greek-supplied}ν [σ]{.unclear}ου [και]{.greek-supplied} εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [καθει[σ]{.unclear}ωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτ[εισ]{.unclear}θε δυνασ[θ]{.unclear}ε πιειν το ποτηριον ο εγω π[ι]{.unclear}ν[ω]{.unclear} και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ε[ι]{.unclear}πον αυ[τ]{.unclear}ω δυναμεθα ο δε [[ιησους]{.greek-abbr}]{.unclear} ειπεν [αυ]{.unclear}το[ι]{.unclear}[ς]{.greek-supplied} το μεν ποτη[ρ]{.unclear}[ι]{.greek-supplied}[ο]{.unclear}ν ο εγω πινω [πιεσ]{.greek-supplied}θε και το [βαπτισμα]{.greek-omitted} [[βαπτι]{.greek-supplied}]{.greek-added} [ο]{.greek-omitted} [εγω]{.greek-omitted} [βαπτιζομαι]{.greek-omitted} [βαπτισθησεσθε]{.greek-omitted}[10:39]{.aside}

[σμα]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [δυναμεθα]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [το]{.greek-omitted} [μεν]{.greek-omitted} [ποτηριον]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [πινω]{.greek-omitted} [πιεσθε]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [βαπτισμα]{.greek-omitted} ο εγω βαπτιζομαι βαπτισθησεσθε[10:39 | instance no. 2]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμ[ο]{.unclear}ν δουναι αλλ οις ητ[οιμ]{.unclear}ασται[10:40]{.aside}

και ακουσαντ[ες]{.unclear} οι δεκ[α]{.unclear} ηρξαντο αγαν[ακτει]{.greek-supplied}ν περι ιακωβου και ιωαννου[10:41]{.aside}

[ο]{.greek-supplied} δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτου[ς]{.unclear} λεγε[ι]{.greek-supplied} [α]{.greek-supplied}υτοις οιδατε [ο]{.unclear}τι οι δοκουντες [α]{.unclear}ρχειν των εθνων κατακυριευουσιν [αυτων]{.greek-omitted} [αυτον]{.greek-added} και οι μεγαλοι αυτω[ν]{.unclear} κατε[ξ]{.unclear}ο[υ]{.unclear}σια[ζου]{.unclear}σιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη [γενεσθαι]{.greek-omitted} [γενεσθε]{.greek-added} μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν [υ[μ]{.unclear}ων]{.greek-added} θελη [υμων]{.greek-omitted} γενεσθαι πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και [ε]{.unclear}ρχονται εις ιερι[χ]{.unclear}ω και εκπορευομενο[υ]{.unclear} α[υ]{.unclear}του απο ι[ε]{.unclear}ρι[χ]{.unclear}ω [και]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [οχλου]{.greek-omitted} [ικανου]{.greek-omitted} [υιος]{.greek-omitted} [τιμαιου]{.greek-omitted} [βαρτιμαιος]{.greek-omitted} [ο]{.greek-omitted} [τυφλος]{.greek-omitted} [εκαθητο]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [προσαιτων]{.greek-omitted}[10:46]{.aside}

### Chapter 11

[και]{.greek-omitted} [ηκουσαν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [εζητουν]{.greek-omitted} [πως]{.greek-omitted} [αυτον]{.greek-omitted} [απολεσωσιν]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-supplied} [π]{.unclear}ας [ο]{.unclear} [ο]{.unclear}χλ[ος]{.unclear} [ε]{.unclear}[ξ]{.greek-supplied}[ε]{.unclear}πλησ[σετο]{.greek-supplied} ε[πι]{.unclear} τη διδαχη αυτου[11:18]{.aside}

και οτ[ε]{.unclear} οψε εγενετο [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} εξ[ω]{.unclear} τη[ς]{.unclear} [πολεως]{.greek-omitted} [π[ω]{.unclear}λε[ω]{.unclear}ς]{.greek-added}[11:19]{.aside}

και πρωι [π]{.unclear}αραπ[ο]{.greek-supplied}[ρ]{.unclear}ευομενοι [ειδον]{.greek-omitted} [ιδον]{.greek-added} την σ[υ]{.unclear}κην εξηραμ[μ]{.unclear}[ε]{.greek-supplied}νην εκ ριζων[11:20]{.aside}

και αναμνησ[θεις]{.greek-supplied} ο πετρ[ο]{.unclear}ς λεγει [αυτ]{.greek-supplied}ω [ραββι]{.greek-omitted} [ραββει]{.greek-added} [ιδε]{.greek-omitted} [ιδου]{.greek-added} η συ[κ]{.greek-supplied}[η]{.unclear} ην κατ[η]{.unclear}ρα[σω]{.greek-supplied} [ε]{.unclear}ξηραν[ται]{.unclear}[11:21]{.aside}

και α[π]{.unclear}οκρ[ιθ]{.unclear}εις [ο]{.unclear} [[ιησους]{.greek-abbr}]{.unclear} λε[γ]{.unclear}[ει]{.greek-supplied} [αυτ]{.unclear}οις [[ει]{.unclear}]{.greek-added} [ε]{.unclear}χ[ετ]{.greek-supplied}ε [πιστιν]{.greek-omitted} [[π]{.greek-supplied}ισ[τ]{.greek-supplied}[η]{.unclear}ν]{.greek-added} [θεου]{.greek-abbr}[11:22]{.aside}

α[μ]{.unclear}ην γαρ [λεγω]{.greek-supplied} [υ]{.unclear}μιν [οτι]{.unclear} ο[ς]{.unclear} αν ειπη [τω]{.greek-supplied} [ο]{.greek-supplied}ρει του[τω]{.greek-supplied} αρθητι και βλη[θ]{.unclear}ητι εις την [θ]{.unclear}α[λασ]{.unclear}σαν και [μ]{.unclear}η διακρ[ιθ]{.unclear}η εν τη καρδ[ια]{.greek-supplied} [αυτου]{.greek-supplied} [αλ]{.unclear}[λα]{.unclear} [π]{.unclear}ισ[τε]{.greek-supplied}[υσ]{.unclear}η οτι [α]{.unclear} [λεγει]{.unclear} γινεται [εστ]{.greek-supplied}α[ι]{.unclear} [αυ]{.unclear}τ[ω]{.unclear} ο εαν ειπη[11:23]{.aside}

δια τουτ[ο]{.unclear} [λε]{.greek-supplied}[γω]{.unclear} [υ]{.unclear}μιν πα[ν]{.unclear}[τα]{.unclear} [ο]{.unclear}σα [αν]{.greek-omitted} [[εαν]{.unclear}]{.greek-added} [π]{.unclear}ροσ[ευ]{.unclear}[χομε]{.greek-supplied}νοι [αιτησθε]{.greek-omitted} [α[ιτισ]{.unclear}[θε]{.greek-supplied}]{.greek-added} [πι]{.unclear}στευετε οτι [λαμ]{.greek-supplied}[β]{.unclear}αν[ε]{.unclear}τε [και]{.unclear} εσται υμιν[11:24]{.aside}

και οτα[ν]{.unclear} [στηκητε]{.greek-omitted} [[σ]{.greek-supplied}τηκ[ε]{.unclear}[τε]{.greek-supplied}]{.greek-added} [π]{.unclear}ροσευχομ[ε]{.unclear}[ν]{.greek-supplied}[ο]{.unclear}ι αφ[ιετε]{.unclear} [ει]{.unclear} τ[ι]{.greek-supplied} [ε]{.greek-supplied}χετε κα[τα]{.unclear} [τι]{.greek-supplied}[νος]{.unclear} ινα [και]{.greek-omitted} [ο]{.unclear} [πατηρ]{.greek-omitted} [[πηρ]{.unclear}]{.greek-added} [υ]{.unclear}[μω]{.greek-supplied}ν ο εν [τοις]{.greek-supplied} ουρανοις [αφη]{.greek-supplied} [[υ]{.greek-supplied}]{.greek-added} [υμιν]{.greek-omitted} [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [υμων]{.greek-omitted}[11:25]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [στηκητε]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [αφιετε]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} [εχετε]{.greek-omitted} [κατα]{.greek-omitted} [τινος]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} [μιν]{.greek-added} τα παραπτωματα υμ[ω]{.unclear}ν[11:25 | instance no. 2]{.aside}

ει δε υμει[ς]{.unclear} [ο]{.unclear}υ[κ]{.unclear} αφιε[τ]{.unclear}ε ουδε ο [πατηρ]{.greek-abbr} [υ]{.unclear}μ[ω]{.unclear}ν ο ε[ν]{.unclear} τοις ουρανοις [αφησει]{.greek-omitted} [αφηση]{.greek-added} τα [παραπτωματα]{.greek-omitted} [[πα]{.unclear}ρ[α]{.unclear}πτωμα]{.greek-added} [τα]{.greek-added} υμων[11:26]{.aside}

και ερχονται [πα]{.unclear}[λ]{.greek-supplied}ιν εις ιεροσολυμα και εν τ[ω]{.unclear} ιερ[ω]{.unclear} περ[ι]{.unclear}π[α]{.unclear}τ[ουν]{.unclear}τ[ο]{.greek-supplied}ς [α]{.unclear}υτου ερχον[τ]{.unclear}αι προς αυτον οι αρχ[ι]{.unclear}ερεις [κ]{.unclear}αι οι γραμματεις [και]{.unclear} ο[ι]{.greek-supplied} [πρεσ]{.greek-supplied}βυτεροι[11:27]{.aside}

κα[ι]{.greek-supplied} [λε]{.greek-supplied}[γο]{.greek-supplied}υ[σ]{.unclear}ιν αυ[τ]{.unclear}[ω]{.greek-supplied} εν ποια εξο[υ]{.unclear}σι[α]{.unclear} τ[α]{.unclear}υτα πο[ι]{.unclear}εις κα[ι]{.unclear} τις σοι [την]{.unclear} ε[ξο]{.unclear}υσιαν ταυ[τ]{.unclear}ην εδωκε[ν]{.unclear} ινα ταυτα π[οι]{.unclear}[η]{.unclear}ς[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκρι[θ]{.unclear}εις ειπεν αυτοις επερωτη[σ]{.unclear}ω υ[μ]{.unclear}ας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} ενα [λο]{.unclear}γον [κ]{.unclear}αι αποκρι[θ]{.unclear}ητε μοι και ερ[ω]{.unclear} υμιν εν ποια εξου[σι]{.unclear}α ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου [ε]{.greek-supplied}ξ [ουρανου]{.greek-abbr} ην η ε[ξ]{.unclear} [ανθρωπων]{.greek-abbr} [αποκριθητε]{.greek-omitted} [αποκριθηται]{.greek-added} μοι[11:30]{.aside}

και ελ[ο]{.unclear}γιζοντο προς εαυτου[ς]{.unclear} λεγοντ[ε]{.unclear}ς [εα]{.greek-supplied}ν ειπωμεν ε[ξ]{.unclear} [ου]{.unclear}ραν[ου]{.greek-supplied} ερει δια τι [ουν]{.greek-omitted} ουκ ε[πι]{.unclear}στευ[σ]{.unclear}[ατε]{.greek-supplied} αυτ[ω]{.unclear}[11:31]{.aside}

[αλλ]{.unclear} [[ε]{.unclear}ι]{.greek-added} [ειπωμεν]{.greek-omitted} [εξ]{.greek-omitted} [ανθρωπων]{.greek-omitted} [εφοβουντο]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [απαντες]{.greek-omitted} [γαρ]{.greek-omitted} [ειχον]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [οτι]{.greek-omitted} [οντως]{.greek-omitted} [προφητης]{.greek-omitted} [ην]{.greek-omitted}[11:32]{.aside}

[αλλ]{.greek-omitted} [ειπωμεν]{.greek-omitted} [[πω]{.unclear}μεν]{.greek-added} εξ [αν]{.unclear}θρωπ[ω]{.unclear}ν εφοβο[υ]{.unclear}ντ[ο]{.unclear} τον [λαον]{.greek-omitted} [οχλον]{.greek-added} απαντες γαρ ειχ[ον]{.unclear} τον [ι]{.unclear}ωαννην οτι οντως [π]{.unclear}ροφητης ην[11:32 | instance no. 2]{.aside}

και αποκριθεντες λεγ[ο]{.greek-supplied}υσιν τω [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκρι[θε]{.unclear}ις]{.greek-added} [ο]{.unclear} [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγ[ε]{.unclear}ι αυτοις ο[υ]{.unclear}δε εγ[ω]{.unclear} λεγ[ω]{.unclear} υμιν [ε]{.greek-supplied}ν ποια [ε]{.unclear}[ξ]{.unclear}ουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοι[ς]{.unclear} εν παραβολαις λε[γ]{.unclear}[ει]{.greek-supplied}ν [α]{.greek-supplied}[μ]{.unclear}πελω[ν]{.unclear}[α]{.greek-supplied} [ε]{.unclear}φυτευσεν [ανθρωπος]{.greek-abbr} και περιε[θ]{.unclear}ηκεν φραγ[μο]{.unclear}ν και ωρυξεν [υ]{.unclear}ποληνιον και [ω]{.unclear}κοδομησεν πυργ[ο]{.unclear}ν και [εξεδοτο]{.greek-omitted} [εξεδετο]{.greek-added} αυτ[ο]{.greek-supplied}ν γεωργοις και απεδημησεν[12:1]{.aside}

[κ]{.unclear}αι απεστειλεν προς τους γεωργους τ[ω]{.unclear} καιρω δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

[οι]{.greek-omitted} [ο]{.greek-added} δε λαβοντες αυτον εδειραν και απ[εσ]{.unclear}τειλαν κενον[12:3]{.aside}

και [απε[στειλεν]{.unclear}]{.greek-added} παλιν [απεστειλεν]{.greek-omitted} προ[ς]{.unclear} αυτου[ς]{.unclear} αλ[λον]{.unclear} δ[ου]{.unclear}λον κακε[ιν]{.unclear}ον [λιθ]{.greek-supplied}οβο[λη]{.unclear}[σαν]{.greek-supplied}τες εκεφαλα[ιωσαν]{.unclear} [κ]{.unclear}αι απεστειλαν [ητιμωμενον]{.greek-omitted} [ητ[ι]{.greek-supplied}]{.greek-added}[12:4]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-omitted} [απεστειλεν]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [αλλον]{.greek-omitted} [δουλον]{.greek-omitted} [κακεινον]{.greek-omitted} [λιθοβολησαντες]{.greek-omitted} [εκεφαλαιωσαν]{.greek-omitted} [και]{.greek-omitted} [απεστειλαν]{.greek-omitted} [ητιμωμενον]{.greek-omitted} [μ[ωμ]{.unclear}ενον]{.greek-added}[12:4 | instance no. 2]{.aside}

και παλιν [απε[σ]{.unclear}τειλαν]{.greek-added} αλλον [απεστειλεν]{.greek-omitted} κακεινον [α]{.unclear}πεκτειναν και πολλους [αλλους]{.corr} τους [μ]{.greek-supplied}εν δερον[τε]{.unclear}ς τους δε [αποκτενοντες]{.greek-omitted} [αποκτεννοντες]{.greek-added}[12:5]{.aside}

ετι [ουν]{.greek-omitted} [τον]{.greek-added} ε[ν]{.unclear}α [υιον]{.greek-abbr} εχων αγαπητον αυτου απεστειλεν και αυτον προς αυτου[ς]{.unclear} εσχατον λεγων [οτι]{.unclear} εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [θεασα[μεν]{.unclear}οι]{.greek-added} [αυτον]{.greek-added} [ερχομενον]{.greek-added} ειπον προς εα[υ]{.unclear}τ[ο]{.unclear}υς οτι ουτος [εσ]{.unclear}τιν ο κληρονο[μ]{.unclear}ος δευτ[ε]{.unclear} αποκτειν[ω]{.unclear}[με]{.greek-supplied}ν αυτον και ημ[ω]{.unclear}ν [εσται]{.greek-omitted} [εστε]{.greek-added} η κληρονο[μ]{.unclear}ια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον [αυτον]{.greek-added} εξω του α[μπ]{.unclear}ελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} το[υ]{.unclear} αμπελωνος [ελευσεται]{.greek-omitted} [[ε]{.unclear}λευσετε]{.greek-added} και [απολεσει]{.greek-omitted} [α[πο]{.greek-supplied}λεση]{.greek-added} τους γεω[ρ]{.greek-supplied}γου[ς]{.unclear} και δωσει [τ]{.unclear}ον αμπελων[α]{.unclear} αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε [λ]{.unclear}[ι]{.greek-supplied}[θ]{.unclear}ον [ο]{.unclear}ν απεδοκ[ι]{.unclear}μα[σ]{.unclear}αν οι οικοδο[μ]{.unclear}ουντες ου[τος]{.unclear} εγ[ε]{.unclear}νη[θ]{.unclear}η εις [κε]{.greek-added} [κεφαλην]{.greek-omitted} [γωνιας]{.greek-omitted}[12:10]{.aside}

[ο[ς]{.unclear}]{.greek-added} [και]{.greek-omitted} [το]{.greek-omitted} [αγαπαν]{.greek-omitted} [αυτον]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [συνεσεως]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} και το αγαπαν τον πλησιον ως εαυτον [πλειον]{.greek-omitted} [πλειονα]{.greek-added} [εστιν]{.greek-omitted} παντων των ολοκαυτωμ[α]{.greek-supplied}τω[ν]{.unclear} [εστιν]{.greek-added} και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουν[ε]{.unclear}χως απεκριθη ειπεν αυτω ου μακραν ει απο της [βασ]{.unclear}ιλειας του [θεου]{.greek-abbr} και ουδεις ο[υκ]{.unclear}ετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω ιερω πως [λ]{.unclear}εγουσιν οι γραμματεις [ο]{.unclear}τι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} εσ[τ]{.unclear}ιν [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος [γαρ]{.greek-omitted} [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δε[ξ]{.unclear}ιων μου εως αν θ[ω]{.unclear} τους εχθρου[ς]{.unclear} σου [υποποδιον]{.greek-omitted} [υποκατω]{.greek-added} [των]{.greek-supplied} ποδων σου[12:36]{.aside}

αυτ[ος]{.unclear} ου[ν]{.unclear} [[δαυιδ]{.greek-abbr}]{.greek-supplied} λεγει αυ[τ]{.unclear}ον [κυριον]{.greek-abbr} [κ]{.greek-supplied}[α]{.unclear}ι ποθεν [υιος]{.greek-abbr} αυτ[ου]{.unclear} εστιν και ο π[ολυς]{.greek-supplied} οχλος [ηκουεν]{.greek-omitted} [ηκουσεν]{.greek-added} α[υ]{.unclear}του ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη [α]{.unclear}υτου βλεπετε απο των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} των θελοντων εν στολαις περιπατειν και ασπασμους εν τ[αις]{.unclear} [αγοραις]{.greek-supplied}[12:38]{.aside}

[και]{.greek-supplied} [πρωτοκαθεδριας]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [συναγωγαις]{.greek-omitted} [και]{.greek-omitted} [πρωτοκλισιας]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [δειπνοις]{.greek-omitted}[12:39]{.aside}

[και]{.greek-omitted} [πρωτοκα]{.greek-supplied}θεδρια[ς]{.unclear} [ε]{.greek-supplied}ν ταις συν[αγωγ]{.unclear}αις [κ]{.unclear}αι πρωτοκλι[σ]{.unclear}ιας εν τοις δε[ι]{.unclear}πνοι[ς]{.unclear}[12:39 | instance no. 2]{.aside}

οι [κατεσθιοντες]{.greek-omitted} [[κ]{.unclear}αται[σ]{.unclear}θιοντες]{.greek-added} τας οικιας τ[ων]{.unclear} χηρων κ[αι]{.unclear} [προφασει]{.greek-omitted} [π[ρο]{.greek-supplied}[φ]{.unclear}ασι]{.greek-added} μακρα [προσε]{.greek-supplied}υχομενοι [ουτοι]{.greek-supplied} [ληψονται]{.greek-omitted} [[λημψον]{.greek-supplied}ται]{.greek-added} [π]{.unclear}ερι[σσο]{.greek-supplied}τερον κρι[μα]{.unclear}[12:40]{.aside}

και [καθισας]{.greek-omitted} [εστως]{.greek-added} [ο]{.unclear} [ιησους]{.greek-abbr} [κατεναντι]{.greek-omitted} [α[π]{.unclear}εναντι]{.greek-added} του γαζοφυλακιου εθεωρει πως ο οχλος βα[λ]{.unclear}λει χαλκον εις το γαζοφυλακιον και πολλοι πλουσι[οι]{.greek-supplied} εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια [χηρα]{.greek-omitted} [πτωχη]{.greek-omitted} [εβαλεν]{.greek-omitted} [ε[β]{.unclear}αλλ[ε]{.unclear}εν]{.greek-added} λεπτα δυο ο [εσ]{.unclear}τιν [κο]{.unclear}δραντης[[12:42 *(lacunose)*]{.lacunose}]{.aside}

και προσκα[λεσαμε]{.unclear}νος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτ[ω]{.unclear}χη πλειον παντων βεβληκ[εν]{.unclear} των βαλλ[ον]{.unclear}των εις το γαζοφυλακ[ι]{.unclear}ον[12:43]{.aside}

παντες γα[ρ]{.unclear} εκ του περισ[σ]{.unclear}ε[υ]{.unclear}οντος αυτοις εβαλον αυτη [δε]{.unclear} εκ της υστερη[σ]{.unclear}εως αυτης παντα οσα ει[χ]{.unclear}ε[ν]{.unclear} εβαλεν ολ[ον]{.unclear} τον [β]{.unclear}ιον α[υ]{.unclear}της[12:44]{.aside}

### Chapter 13

[παραδωσει]{.greek-omitted} [δε]{.greek-omitted} [αδελφος]{.greek-omitted} [αδελφον]{.greek-omitted} [εις]{.greek-omitted} [θανατον]{.greek-omitted} [και]{.greek-omitted} [πατηρ]{.greek-omitted} [τεκνον]{.greek-omitted} και επαναστησ[ον]{.unclear}ται τεκν[α]{.unclear} ε[πι]{.greek-supplied} [γο]{.greek-supplied}[ν]{.unclear}εις κα[ι]{.greek-supplied} θανατωσου[σιν]{.unclear} α[υ]{.unclear}[τους]{.greek-supplied}[13:12]{.aside}

[και]{.greek-supplied} [εσεσθε]{.unclear} [μισο]{.unclear}υ[μενοι]{.greek-supplied} [υπο]{.greek-supplied} παντ[ων]{.unclear} δια το ονομα μου [ο]{.unclear} δε υπομεινας εις τελος ου[τος]{.greek-supplied} [σωθ]{.unclear}ησεται[13:13]{.aside}

οτα[ν]{.unclear} δε [ιδητε]{.greek-omitted} [[ιδη]{.unclear}ται]{.greek-added} το βδ[ε]{.unclear}λ[υγμ]{.unclear}α της ερημ[ωσε]{.unclear}[ω]{.unclear}ς το ρηθεν υπο δανιηλ το[υ]{.unclear} πρ[ο]{.unclear}φητου [εστως]{.greek-omitted} [εστος]{.greek-added} [οπ]{.unclear}ου ου δει ο αναγιν[ω]{.unclear}σκ[ων]{.unclear} νοειτ[ω]{.unclear} τοτε ο[ι]{.unclear} εν [τη]{.unclear} [ιο]{.greek-supplied}[υ]{.unclear}δαια φε[υγε]{.unclear}τ[ω]{.unclear}σαν εις τ[α]{.unclear} [ο]{.unclear}ρη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελ[θε]{.unclear}τω αραι τι [ε]{.greek-supplied}κ της [ο]{.unclear}ικια[ς]{.unclear} αυτ[ου]{.unclear}[13:15]{.aside}

[κ]{.unclear}αι ο εις τον αγρον ων μη [επιστρεψατω]{.greek-omitted} [επιστρεψατο]{.greek-added} εις τα οπισω αραι το ιμ[α]{.unclear}τιον α[υ]{.unclear}του[13:16]{.aside}

ο[υ]{.unclear}αι δε ταις εν γαστρι εχουσα[ις]{.unclear} και ταις [θ]{.unclear}ηλαζο[υ]{.unclear}σαις εν εκειναις τα[ι]{.unclear}ς ημεραις[13:17]{.aside}

προσευχεσθε δε ι[να]{.unclear} [μ]{.unclear}η [γενηται]{.greek-omitted} [γενη[τ]{.unclear}ε]{.greek-added} η φ[υ]{.unclear}γη [υ]{.unclear}μων χειμ[ω]{.unclear}νος[13:18]{.aside}

ε[σ]{.greek-supplied}ονται γαρ αι η[μ]{.unclear}εραι εκειναι θ[λ]{.unclear}ιψις οια ου γεγονεν τοια[υ]{.unclear}τη α[π]{.unclear} αρ[χης]{.unclear} κ[τ]{.unclear}ισε[ω]{.unclear}ς η[ς]{.unclear} [[εκτι]{.unclear}]{.greek-added} [εκτισεν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εως]{.greek-omitted} [του]{.greek-omitted} [νυν]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [γενηται]{.greek-omitted}[13:19]{.aside}

[σεν]{.greek-added} [εσονται]{.greek-omitted} [γαρ]{.greek-omitted} [αι]{.greek-omitted} [ημεραι]{.greek-omitted} [εκειναι]{.greek-omitted} [θλιψις]{.greek-omitted} [οια]{.greek-omitted} [ου]{.greek-omitted} [γεγονεν]{.greek-omitted} [τοιαυτη]{.greek-omitted} [απ]{.greek-omitted} [αρχης]{.greek-omitted} [κτισεως]{.greek-omitted} [ης]{.greek-omitted} [εκτισεν]{.greek-omitted} ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19 | instance no. 2]{.aside}

και ει μη [κυριος]{.greek-abbr} εκολοβωσεν τας ημερας [εκεινας]{.greek-added} ουκ αν [ε]{.unclear}σωθη πασα σαρξ αλλα δια τ[ο]{.unclear}υς εκλεκτους ους εξελεξατο εκολοβωσεν τας ημ[ε]{.unclear}ρας[13:20]{.aside}

[και]{.greek-added} τοτε [εαν]{.greek-omitted} [αν]{.greek-added} τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη πιστευετε[13:21]{.aside}

εγ[ε]{.unclear}ρθησονται γαρ ψευδοχριστοι [κ]{.unclear}αι ψευδοπροφηται και δωσ[ου]{.unclear}σιν σημει[α]{.unclear} [και]{.greek-supplied} [τε]{.greek-supplied}ρ[α]{.unclear}τ[α]{.unclear} [π]{.unclear}ρ[ος]{.unclear} τ[ο]{.greek-supplied} [αποπλα]{.greek-supplied}ναν [ει]{.greek-supplied} δυνατον [κ]{.unclear}αι [τους]{.greek-supplied} [ε]{.unclear}κλ[εκτους]{.greek-supplied}[13:22]{.aside}

[υ]{.greek-supplied}μεις δε βλεπετε [ι]{.greek-supplied}δου πρ[ο]{.unclear}ειρηκα υμιν παντ[α]{.unclear}[13:23]{.aside}

[α]{.unclear}λλ εν εκ[ειν]{.unclear}αις ταις η[με]{.greek-supplied}ραις [μ]{.unclear}ετα την θλιψιν εκεινην ο ηλιος σκοτι[σθ]{.unclear}ησεται κ[α]{.unclear}ι η σεληνη [ου]{.greek-supplied} δωσει το [φεγγος]{.greek-omitted} [ψ[ε]{.unclear}γγος]{.greek-added} αυτης[13:24]{.aside}

[κ]{.unclear}αι οι αστερες του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυ[ν]{.greek-supplied}αμεις αι εν τοις [ουρανοις]{.greek-abbr} σ[α]{.unclear}λευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [ερ]{.greek-added} [ερχομενον]{.greek-omitted} [εν]{.greek-omitted} [νεφελαις]{.greek-omitted} [μετα]{.greek-omitted} [δυναμεως]{.greek-omitted} [πολλης]{.greek-omitted} [και]{.greek-omitted} [δοξης]{.greek-omitted}[13:26]{.aside}

[και]{.greek-omitted} [τοτε]{.greek-omitted} [οψονται]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ερχομενον]{.greek-omitted} [[χ]{.unclear}ομενον]{.greek-added} εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} κα[ι]{.unclear} δοξης [πολλης]{.greek-added}[13:26 | instance no. 2]{.aside}

και τοτε αποστελει τους αγγελους αυτου και [επισυναξει]{.greek-omitted} [επισυναζει]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρ[ω]{.unclear}ν ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης [ηδη]{.greek-omitted} ο κλαδος [ηδη]{.greek-added} απαλος γενηται και εκφυη τα φυλλα γ[ι]{.unclear}ν[ω]{.unclear}σκ[ε]{.unclear}τ[ε]{.unclear} οτι ε[γ]{.unclear}[γυς]{.greek-supplied} το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν τα[υ]{.unclear}τα ιδητε γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

[ο]{.unclear} ουρανος και η γη [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης η ωρας [εκεινης]{.greek-added} ουδεις οιδεν ουδ[ε]{.unclear} οι αγγελοι οι [ε]{.unclear}ν [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετ[ε]{.greek-supplied} αγρυπν[ε]{.unclear}ιτ[ε]{.unclear} [και]{.unclear} [προσευχεσθε]{.greek-omitted} [ουκ]{.greek-omitted} [οιδατε]{.greek-omitted} [γαρ]{.greek-omitted} [ποτε]{.greek-omitted} [ο]{.greek-omitted} [καιρος]{.greek-omitted} [εστιν]{.greek-omitted}[13:33]{.aside}

[βλεπετε]{.greek-omitted} [αγρυπνειτε]{.greek-omitted} [και]{.greek-omitted} προσευχεσθ[ε]{.unclear} ουκ οιδατε γαρ ποτε ο καιρο[ς]{.unclear} [εσ]{.unclear}τιν[13:33 | instance no. 2]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν [ου]{.unclear}κ οιδατε [γ]{.unclear}αρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψ[ε]{.unclear} η [μεσονυκτιου]{.greek-omitted} [μεσωνυκτιω]{.greek-added} η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης [ευρη]{.greek-omitted} [ευρησει]{.greek-added} υμας καθευδοντας[13:36]{.aside}

[α]{.greek-omitted} [ο]{.greek-added} δ[ε]{.unclear} υμιν λεγω πασιν λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και ε[ζ]{.unclear}ητουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω [κρατησαντες]{.greek-omitted} [κρατεισαντες]{.greek-added} αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν τη οικια σιμων[ος]{.unclear} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

[και]{.greek-omitted} [υμνησαντες]{.greek-omitted} [εξηλθον]{.greek-omitted} εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε εν εμοι εν τη νυκτι [ταυτη]{.greek-omitted} [ταυτ[ι]{.unclear}]{.greek-added} οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το εγ[ε]{.unclear}ρθηναι με [προαξω]{.greek-omitted} [προαγ[ξ]{.unclear}ω]{.greek-added} υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρ[ο]{.unclear}ς [ε]{.unclear}φη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον ε[ν]{.unclear} τη νυκτι ταυτη πριν η δι[ς]{.unclear} αλεκτορα φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με[14:30]{.aside}

ο δε εκπερισσου ελεγεν μαλλον εαν με δεη [συναποθανειν]{.greek-omitted} [συν]{.greek-added} σοι [αποθανειν]{.greek-added} ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεδσημανι]{.greek-added} και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθεισατε]{.greek-added} ωδε [εως]{.greek-omitted} [προσευξωμαι]{.greek-omitted}[14:32]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [χωριον]{.greek-omitted} [ου]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [γεθσημανη]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [καθισατε]{.greek-omitted} [ωδε]{.greek-omitted} [ε]{.greek-supplied}ως [προσευξωμαι]{.greek-omitted} [προσευ[ξ]{.unclear}ομαι]{.greek-added}[14:32 | instance no. 2]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγ[ο]{.greek-supplied}ρειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει [δ]{.greek-supplied}υνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκ[ε]{.unclear}ι αυτους καθευδον[τα]{.unclear}ς και λεγει τω πετρω σ[ι]{.unclear}μων καθευδει[ς]{.unclear} ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε κ[αι]{.unclear} προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προ[θ]{.unclear}υμον η δ[ε]{.unclear} [σ]{.unclear}αρ[ξ]{.unclear} [ασθενης]{.greek-omitted} [ασθενε[ι]{.unclear}ς]{.greek-added}[14:38]{.aside}

και παλιν απελθων προσ[ηυξ]{.unclear}ατο τον αυτον [λ]{.unclear}ογον ειπ[ω]{.unclear}ν[14:39]{.aside}

και [υ]{.unclear}ποστρεψας ε[υ]{.unclear}ρεν [αυ]{.unclear}το[υ]{.unclear}ς παλιν καθευδοντας ησαν γαρ οι οφ[θαλμοι]{.greek-supplied} [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-supplied}[κ]{.greek-supplied} [ηδεισαν]{.greek-omitted} [[ε]{.unclear}ιδεισαν]{.greek-added} τι αυτω αποκριθω[σιν]{.unclear}[[14:40 *(lacunose)*]{.lacunose}]{.aside}

και [ε]{.unclear}ρ[χ]{.unclear}εται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον [κ]{.unclear}[αι]{.greek-supplied} αναπαυεσθε απε[χ]{.unclear}ει [[το]{.unclear}]{.greek-added} [τελος]{.greek-added} η[λ]{.unclear}θεν η ωρα ιδου παραδιδ[ο]{.unclear}ται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ει[ς]{.unclear} [τας]{.greek-omitted} χειρας τ[ων]{.unclear} αμαρτ[ωλων]{.unclear}[14:41]{.aside}

εγειρεσθε α[γω]{.unclear}μεν [ι]{.unclear}δο[υ]{.greek-supplied} [ο]{.greek-supplied} [π]{.greek-supplied}αραδιδο[υ]{.unclear}ς με η[γ]{.unclear}γικεν[14:42]{.aside}

και ευθε[ω]{.unclear}ς [ετ]{.unclear}ι αυ[τ]{.unclear}ου λαλου[ν]{.unclear}τος παραγι[νε]{.unclear}ται ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις ων τω[ν]{.unclear} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και μ[ετ]{.unclear} αυτου ο[χλος]{.unclear} [πολυς]{.greek-omitted} μετα [μα]{.unclear}χαιρ[ω]{.unclear}ν και ξυλ[ω]{.unclear}ν παρα τ[ω]{.unclear}ν αρχιερεων κ[αι]{.greek-supplied} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και [των]{.unclear} πρεσβυτερ[ω]{.greek-supplied}ν[14:43]{.aside}

δεδωκ[ει]{.unclear} [δ]{.unclear}ε ο παραδιδους αυτον [συσ]{.greek-added} [συσσημον]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} [ον]{.greek-omitted} [αν]{.greek-omitted} [φιλησω]{.greek-omitted} [αυτος]{.greek-omitted} [εστιν]{.greek-omitted} [κρατησατε]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [απαγαγετε]{.greek-omitted} [ασφαλως]{.greek-omitted}[14:44]{.aside}

[δεδωκει]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [παραδιδους]{.greek-omitted} [αυτον]{.greek-omitted} [συσσημον]{.greek-omitted} [σημον]{.greek-added} αυτοις λεγων [ον]{.greek-omitted} [ο]{.greek-added} αν φιλησω αυτος εστιν κρατ[η]{.unclear}σατε αυτον και απαγαγετε ασφαλως[14:44 | instance no. 2]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} [ραββει]{.greek-added} [ραββι]{.greek-omitted} [ραβ[β]{.unclear}ει]{.greek-added} και κατεφιλησεν α[υ]{.unclear}τον[14:45]{.aside}

οι δε επεβαλον [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας αυ[τω]{.unclear}ν και ε[κ]{.greek-supplied}ρ[α]{.unclear}τησαν [αυ]{.unclear}τον[14:46]{.aside}

εις δε τι[ς]{.unclear} [τ]{.unclear}[ων]{.greek-supplied} [πα]{.unclear}ρεσ[τ]{.unclear}ηκοτων σπασαμενο[ς]{.unclear} την μαχαιραν [επαι]{.greek-supplied}σεν τον δου[λ]{.unclear}ον του αρχιερ[ε]{.unclear}ως και αφειλεν αυτου το [ω]{.unclear}τιο[ν]{.unclear}[14:47]{.aside}

και [α]{.unclear}ποκριθει[ς]{.unclear} [ο]{.greek-supplied} [[ιησους]{.greek-abbr}]{.greek-supplied} [ει]{.greek-supplied}πεν αυτοις [ως]{.unclear} επι ληστην [εξηλθετε]{.greek-omitted} [[ε]{.unclear}ξηλθατε]{.greek-added} μετα μαχαιρ[ων]{.unclear} και ξυλων συ[λ]{.unclear}λαβειν με[14:48]{.aside}

καθ ημεραν ημην [π]{.greek-supplied}ρος [υμας]{.unclear} [δ[ι]{.unclear}δασκων]{.greek-added} ε[ν]{.unclear} [τω]{.unclear} ι[ε]{.unclear}[ρω]{.unclear} [διδασκων]{.greek-omitted} και ουκ ε[κ]{.unclear}ρατησατε με [α]{.unclear}λ[λ]{.greek-supplied} [ι]{.greek-supplied}να π[λ]{.unclear}ηρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον [οι]{.greek-added} [μαθηται]{.greek-added} παντες [εφυγον]{.greek-omitted} [[ε]{.unclear}φγον]{.greek-added}[14:50]{.aside}

και ει[ς]{.unclear} τι[ς]{.unclear} νεαν[ι]{.unclear}σκος ηκολου[θ]{.unclear}ησεν αυτω περιβεβλημενος σινδονα [επι]{.greek-omitted} [γυμνου]{.greek-omitted} [και]{.greek-omitted} [κρατουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[14:51]{.aside}

### Chapter 15

[μων]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [παραπορευομενοι]{.greek-omitted} [εβλασφημουν]{.greek-omitted} [αυτον]{.greek-omitted} [κινουντες]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουα]{.greek-omitted} [ο]{.greek-omitted} [καταλυων]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τρισιν]{.greek-omitted} [ημεραις]{.greek-omitted} [οικοδομων]{.greek-omitted}[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [κ[ατ]{.unclear}αβη[θι]{.unclear}]{.greek-added} απο του σταυρου[15:30]{.aside}

[ομοιως]{.unclear} [δε]{.greek-added} και οι [α]{.unclear}ρχιερει[ς]{.unclear} εμπαιζον[τ]{.unclear}ες προς αλ[λ]{.unclear}ηλους μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} [ε]{.unclear}λεγον αλλο[υ]{.unclear}ς εσωσεν εαυτ[ον]{.greek-supplied} ου [δ]{.unclear}υναται σ[ω]{.unclear}σαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο [β]{.unclear}ασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο το[υ]{.unclear} σταυρου [ιν]{.unclear}α ιδ[ω]{.unclear}μεν και πισ[τ]{.unclear}ευσωμεν αυτω και οι συ[ν]{.unclear}εσταυρω[με]{.unclear}νοι α[υτ]{.unclear}ω [ωνειδιζον]{.greek-omitted} [ονειδιζον]{.greek-added} αυτον[15:32]{.aside}

[και]{.greek-added} [γ]{.unclear}ενομενης [δε]{.greek-omitted} ωρας εκτης σκοτ[ο]{.unclear}ς εγενετο εφ ολην την γην εως ωρας ενατ[ης]{.unclear}[15:33]{.aside}

και τη ωρα τη ενατη εβοη[σεν]{.unclear} [ο]{.unclear} [[ιησους]{.greek-abbr}]{.unclear} φ[ω]{.unclear}νη μεγαλη λεγων ε[λ]{.unclear}ωι ελωι [λιμα]{.greek-omitted} [λειμα]{.greek-added} σα[β]{.unclear}αχθανι [ο]{.unclear} [εσ]{.unclear}τιν μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} [ο]{.unclear} [[θεος]{.greek-abbr}]{.unclear} μου ει[ς]{.unclear} [τ]{.unclear}ι με εγκατελ[ι]{.unclear}πες[15:34]{.aside}

και [τι]{.greek-supplied}ν[ες]{.greek-supplied} των παρ[εσ]{.unclear}τηκοτ[ω]{.unclear}ν ακουσαντες [ελεγον]{.unclear} ιδου ηλι[αν]{.unclear} [φω]{.unclear}νει[15:35]{.aside}

δρα[μω]{.greek-supplied}ν δε εις και γεμ[ι]{.unclear}σας [σπογγον]{.greek-omitted} [οξους]{.greek-omitted} [περιθεις]{.greek-omitted} [τε]{.greek-omitted} [καλαμω]{.greek-omitted} [εποτιζεν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [ιδωμεν]{.greek-omitted} [ει]{.greek-omitted} [ερχεται]{.greek-omitted} [ηλιας]{.greek-omitted} [καθελειν]{.greek-omitted} [αυτον]{.greek-omitted}[15:36]{.aside}

[δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γεμισας]{.greek-omitted} σπογγον οξους περιθεις τε καλαμω [εποτιζεν]{.greek-omitted} [εποτειζεν]{.greek-added} αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας κ[αθελ]{.unclear}ειν αυτον[15:36 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην [μ]{.unclear}εγαλην εξεπνευσεν[15:37]{.aside}

και τ[ο]{.unclear} [καταπετασμα]{.greek-omitted} [κ[α]{.unclear}ταπαιτασμα]{.greek-added} του ναου εσχισθη εις δυο [απο]{.greek-omitted} [απ]{.greek-added} ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο [κεντυριων]{.greek-omitted} [κεντυριον]{.greek-added} ο παρεστηκως εξ εναντιας αυτου οτι [ουτως]{.greek-omitted} [ου[τω]{.unclear}]{.greek-added} κραξας εξεπνευσεν ει[π]{.unclear}ε[ν]{.unclear} αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [[θεου]{.greek-abbr}]{.greek-supplied}[15:39]{.aside}

ησαν δε και [γυ]{.unclear}[ν]{.unclear}αικες απο μακρ[ο]{.unclear}θ[ε]{.unclear}ν [θ]{.greek-supplied}[εω]{.unclear}ρου[σ]{.unclear}α[ι]{.unclear} [εν]{.unclear} αις [ην]{.unclear} [και]{.unclear} μαρια η μα[γ]{.unclear}δαληνη και [μ]{.unclear}αρια η τ[ου]{.unclear} ιακωβου [το]{.unclear}υ [μικ]{.unclear}ρου κα[ι]{.unclear} ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε [ην]{.unclear} [εν]{.unclear} [τη]{.unclear} [γα]{.greek-supplied}[λιλα]{.unclear}ια ηκολουθουν αυτω και διηκονου[ν]{.unclear} [α]{.unclear}υτω κ[α]{.unclear}ι αλ[λ]{.unclear}αι πο[λλαι]{.unclear} αι [σ]{.unclear}υ[ναναβα]{.unclear}σαι αυ[τω]{.unclear} ε[ι]{.unclear}ς ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενο[μ]{.unclear}[ενης]{.greek-supplied} [επει]{.greek-omitted} [[ε]{.greek-supplied}π[ι]{.unclear}]{.greek-added} ην [παρασκευη]{.greek-omitted} [π[αρασκ]{.unclear}ευ]{.greek-added} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [προσαββατον]{.greek-omitted}[15:42]{.aside}

[η]{.greek-added} [και]{.greek-omitted} [ηδη]{.greek-omitted} [οψιας]{.greek-omitted} [γενομενης]{.greek-omitted} [επει]{.greek-omitted} [ην]{.greek-omitted} [παρασκευη]{.greek-omitted} ο εστιν προσαββατον[15:42 | instance no. 2]{.aside}

[ηλθεν]{.greek-omitted} [ελθ[ω]{.unclear}ν]{.greek-added} ιωσηφ ο απο αριμαθαιας ευσχ[η]{.unclear}μων βουλευτης ος και αυτος ην προσδεχομεν[ος]{.unclear} την βασιλει[αν]{.unclear} του [θεου]{.greek-abbr} τολμησας εισηλθεν προς πιλα[τ]{.unclear}ον και ητησατ[ο]{.unclear} το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

[ο]{.unclear} δε πιλα[τος]{.unclear} [ε]{.unclear}θαυμασεν ει ηδη τ[εθνηκε]{.unclear}ν [και]{.unclear} προσκαλεσα[μ]{.greek-supplied}ενος [τον]{.greek-supplied} κεντυρι[ωνα]{.greek-supplied} επ[η]{.unclear}ρ[ω]{.unclear}[τησεν]{.greek-supplied} αυτο[ν]{.unclear} ε[ι]{.unclear} παλ[αι]{.unclear} [α]{.unclear}[πεθανε]{.greek-supplied}ν[15:44]{.aside}

και γνους απο του κεντυριωνος ε[δω]{.unclear}ρ[η]{.unclear}σατο το σ[ω]{.unclear}[μα]{.greek-supplied} τ[ω]{.unclear} [ιω]{.unclear}σηφ[15:45]{.aside}

και α[γο]{.unclear}ρασας σινδονα και καθελων [α]{.unclear}υτον ενειλησεν τη σ[ι]{.unclear}νδονι [κ]{.unclear}αι κατ[ε]{.unclear}θηκε[ν]{.unclear} [α]{.unclear}υτ[ο]{.unclear}ν εν μνημει[ω]{.unclear} [ο]{.unclear} ην λελατομη[με]{.unclear}νον εκ π[ετ]{.unclear}ρας και [προσεκυλισεν]{.greek-omitted} [πρ[ο]{.unclear}σεκ[υ]{.unclear}λη[σ]{.unclear}εν]{.greek-added} λιθο[ν]{.unclear} ε[π]{.unclear}ι την θυραν τ[ο]{.unclear}υ μνημειου[15:46]{.aside}

η [δε]{.unclear} [μ]{.unclear}αρια η μαγ[δ]{.unclear}αλην[η]{.unclear} και μαρια [η]{.greek-added} ι[ωση]{.unclear} εθεωρου[ν]{.unclear} που [τιθεται]{.greek-omitted} [τεθ[η]{.unclear}τα[ι]{.unclear}]{.greek-added}[15:47]{.aside}

### Chapter 16

και [διαγενομενου]{.greek-omitted} [διαγεν[ο]{.unclear}με]{.greek-added} [του]{.greek-omitted} [σαββατου]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [σαλωμη]{.greek-omitted} [ηγορασαν]{.greek-omitted} [αρωματα]{.greek-omitted} [ινα]{.greek-omitted} [ελθουσαι]{.greek-omitted} [αλειψωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[16:1]{.aside}

[νου]{.greek-added} [και]{.greek-omitted} [διαγενομενου]{.greek-omitted} του σαββατου μαρια η [μα]{.unclear}γδαλη[νη]{.greek-supplied} κα[ι]{.unclear} μαρι[α]{.greek-supplied} [[η]{.greek-supplied}]{.greek-added} [[του]{.greek-supplied}]{.greek-added} [ι]{.unclear}ακ[ω]{.unclear}[βου]{.greek-supplied} [και]{.greek-supplied} [σαλωμη]{.greek-supplied} [ηγο]{.greek-supplied}ρ[ασαν]{.unclear} [αρ]{.unclear}ωμα[τα]{.unclear} [ινα]{.greek-supplied} [ελθ]{.greek-supplied}[ο]{.unclear}υσαι αλ[ει]{.greek-supplied}[ψω]{.unclear}σιν αυτον[16:1 | instance no. 2]{.aside}

και λιαν πρωι [της]{.greek-omitted} [τη]{.greek-added} [μιας]{.greek-omitted} [μ[ια]{.unclear}]{.greek-added} [των]{.greek-added} [σαββα]{.greek-supplied}[τ]{.unclear}ων ερ[χο]{.unclear}ν[τ]{.unclear}α[ι]{.unclear} επι το μνημειον α[ν]{.unclear}[ατειλαντος]{.greek-supplied} [του]{.greek-omitted} [ηλιου]{.greek-omitted}[16:2]{.aside}

