---
title: "Collation of Byz^RP^ vs 20250 (250)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 250 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20250).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 250                                   	| λογος                              	|
| 250 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 250 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 250               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 250                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 250 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 250                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 2

[και]{.greek-omitted} [χρηματισθεντες]{.greek-omitted} [κατ]{.greek-omitted} [οναρ]{.greek-omitted} [μη]{.greek-omitted} [ανακαμψαι]{.greek-omitted} [προς]{.greek-omitted} [ηρωδην]{.greek-omitted} [δι]{.greek-omitted} [αλλης]{.greek-omitted} [οδου]{.greek-omitted} ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδου αγγελος [κυριου]{.greek-abbr} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε [το]{.greek-omitted} [τον]{.greek-added} [παιδιον]{.greek-omitted} [παιδα]{.greek-added} και την [μητερα]{.greek-abbr} αυτου και [φευγε]{.greek-omitted} [φυγε]{.greek-added} εις αιγυπτον και [ισθι]{.greek-omitted} [ισθει]{.greek-added} εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε [εγερθεις]{.greek-omitted} [διεγερθεις]{.greek-added} παρελαβεν το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο [του]{.greek-omitted} [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον υιον μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι [ενεπαιχθη]{.greek-omitted} [ενεπεχθη]{.greek-added} υπο των μαγων εθυμωθη λιαν και αποστειλας ανειλεν παντας τους παιδας τους [οντας]{.greek-added} εν βηθλεεμ και εν πασιν τοις οριοις αυτης απο διετους και κατωτερω κατα τον χρονον ον ηκριβωσεν παρα των μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν [υπο]{.greek-omitted} [δια]{.greek-added} [ιερεμιου]{.greek-omitted} [ιερημιου]{.greek-added} του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη [θρηνος]{.greek-omitted} [και]{.greek-omitted} κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ ηθελεν παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} [φαινεται]{.greek-added} κατ [ο]{.greek-supplied}[ναρ]{.greek-supplied} [φαινεται]{.greek-omitted} [τω]{.greek-supplied} [ιωσηφ]{.greek-supplied} εν αιγυπτω[2:19]{.aside}

λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} τεθνηκασιν γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις παρελαβεν το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην ισραηλ[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει επι της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν εις πολιν λεγομενην [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} οπως πληρωθη το ρηθεν δια των προφητων οτι ναζωραιος κληθησε[ται]{.greek-supplied}[2:23]{.aside}

### Chapter 3

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς [τον]{.greek-omitted} ιωαννην του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε ιωαννης διεκωλυεν αυτον λεγων εγω [χρειαν]{.greek-omitted} [χρεαν]{.greek-added} εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν [προς]{.greek-omitted} [αυτον]{.greek-omitted} αφες αρτι [ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ πρεπον εστιν ημιν πληρωσαι πασαν δικαιοσυνην τοτε [αφιησιν]{.greek-omitted} [αφιησι]{.greek-added} αυτον[3:15]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον αυτω οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους λεγων[5:2]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθη[σονται]{.unclear}[5:4]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [η]{.greek-omitted} [δεξια]{.greek-omitted} [σου]{.greek-omitted} [χειρ]{.greek-omitted} [σκανδαλιζει]{.greek-omitted} [δαλιζει]{.greek-added} σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη δε [οτι]{.greek-omitted} ος αν απολυση την γυναικα αυτου δοτω αυτη αποστασιον[5:31]{.aside}

εγω δε λεγω υμιν [οτι]{.greek-omitted} [οστις]{.greek-added} [ος]{.greek-omitted} αν απολυση την γυναικα αυτου παρεκτος λογου [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} ποιει αυτην [μοιχασθαι]{.greek-omitted} [μοιχευθηναι]{.greek-added} και ος εαν απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε [τω]{.greek-omitted} [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη ομοσαι ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος εστιν του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον εστιν των ποδων αυτου μητε εις ιεροσολυμα οτι πολις εστιν του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου ομοσης οτι ου δυνασαι μιαν τριχα [ποιησαι]{.greek-added} λευκην η μελαιναν [ποιησαι]{.greek-omitted}[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου εστιν[5:37]{.aside}

### Chapter 6

[προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} την [ελεημοσυνην]{.greek-omitted} [δικαιοσυνην]{.greek-added} υμων μη ποιειν εμπροσθεν των ανθρωπων προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} παρα [τω]{.greek-omitted} [πατρι]{.greek-omitted} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} υμων [τω]{.greek-omitted} [του]{.greek-added} εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν ποιης ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν απεχουσιν τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι [ποιει]{.greek-omitted} [ποιη]{.greek-added} η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω [αυτος]{.greek-omitted} αποδωσει σοι εν τω φανερω[6:4]{.aside}

οταν δε [νηστευητε]{.greek-omitted} [νηστευηται]{.greek-added} μη [γινεσθε]{.greek-omitted} [γεινεσθαι]{.greek-added} ωσπερ οι υποκριται σκυθρωποι αφανιζουσιν γαρ τα προσωπα αυτων οπως φανωσιν τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην λεγω υμιν [οτι]{.greek-omitted} απεχουσιν τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων [αλειψαι]{.greek-omitted} [αλιψαι]{.greek-added} σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω πατρι σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι[6:18]{.aside}

### Chapter 7

παντα ουν οσα [αν]{.greek-omitted} [εαν]{.greek-added} [θελητε]{.greek-omitted} [θελεται]{.greek-added} ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} ουτως και υμεις [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added} αυτοις ουτος γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

[προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} [δε]{.greek-omitted} απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε εισιν λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων [επιγνωσεσθε]{.greek-omitted} [επιγνωσεσθαι]{.greek-added} αυτους μητι συλλεγουσιν απο ακανθων [σταφυλην]{.greek-omitted} [σταφυλας]{.greek-added} η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον [σαπρον]{.greek-omitted} [σαρπον]{.greek-added} καρπους καλους [ποιειν]{.greek-omitted} [ποειν]{.greek-added}[7:18]{.aside}

παν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων [επιγνωσεσθε]{.greek-omitted} [επιγνωσεσθαι]{.greek-added} αυτους[7:20]{.aside}

### Chapter 8

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} εθαυμασεν και ειπεν τοις ακολουθουσιν αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων ηξουσιν και ανακλιθησονται μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας [εκβληθησονται]{.greek-omitted} [εξελευσονται]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} υπαγε [και]{.greek-omitted} ως επιστευσας [γενηθητω]{.greek-supplied} [σοι]{.greek-supplied} και ιαθη ο παις [απο]{.greek-added} [της]{.greek-added} [ωρας]{.greek-added} [εκεινης]{.greek-added} [και]{.greek-added} [υποστρεψας]{.greek-added} [εκατονταρχα]{.greek-added} [αρχης]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} αυτου εν [αυτη]{.greek-added} τη ωρα [εκεινη]{.greek-omitted} [ευρεν]{.greek-added} [τον]{.greek-added} [παιδα]{.greek-added} [υγιενοντα]{.greek-added}[8:13]{.aside}

[οψιας]{.greek-omitted} [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [προσηνεγκαν]{.greek-omitted} [αυτω]{.greek-omitted} [δαιμονιζομενους]{.greek-omitted} [πολλους]{.greek-omitted} [και]{.greek-omitted} [εξεβαλεν]{.greek-omitted} [τα]{.greek-omitted} [πνευματα]{.greek-omitted} [λογω]{.greek-omitted} και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας [ασθενειας]{.greek-omitted} [ασθενιας]{.greek-added} ημων ελαβεν και τας νοσους εβαστασεν[8:17]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι [αλωπεκες]{.greek-omitted} [αλωπηκες]{.greek-added} φωλεους εχουσιν και τα πετεινα του ουρανου κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην κλινη[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

### Chapter 9

και παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

ελθοντι δε εις την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} προσηλθον αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των [οφθαλμων]{.greek-omitted} [ομματτων]{.greek-added} αυτων λεγων κατα την πιστιν υμων γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις [γινωσκετω]{.greek-omitted} [γεινωσκετω]{.greek-added}[9:30]{.aside}

οι δε εξελθοντες διεφημισαν αυτον εν ολη τη γη εκεινη[9:31]{.aside}

ιδων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν εσκυλμενοι και [ερριμμενοι]{.greek-omitted} [ρεριμμενοι]{.greek-added} ωσει προβατα μη εχοντα ποιμενα[9:36]{.aside}

### Chapter 10

τουτους τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} απεστειλεν ο [ιησους]{.greek-abbr} [παραγγειλας]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} [εις]{.greek-omitted} [οδον]{.greek-omitted} [εθνων]{.greek-omitted} [μη]{.greek-omitted} [απελθητε]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [πολιν]{.greek-omitted} [σαμαρειτων]{.greek-omitted} [μη]{.greek-omitted} [εισελθητε]{.greek-omitted}[10:5]{.aside}

### Chapter 12

λεγω δε υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} αποδωσουσιν περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων σου δικαιωθηση και εκ των λογων σου καταδικασθηση[12:37]{.aside}

τοτε απεκριθησαν τινες των γραμματεων και φαρισαιων λεγοντες διδασκαλε θελομεν απο σου [σημειον]{.greek-omitted} [σημιον]{.greek-added} ιδειν[12:38]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητουν αναπαυσιν και ουχ ευρισκει[12:43]{.aside}

τοτε λεγει επιστρεψω εις τον οικον μου οθεν εξηλθον και [ελθον]{.greek-omitted} [ελθων]{.greek-added} ευρισκει σχολαζοντα [[και]{.greek-supplied}]{.greek-added} σεσαρωμενον και κεκοσμημενον[12:44]{.aside}

τοτε πορευεται και παραλαμβανει μεθ εαυτου επτα ε[τε]{.greek-supplied}ρα [πνευματα]{.greek-abbr} πονηροτερα εαυτου και ε[ισ]{.greek-supplied}ελθοντα κατοικ[ει]{.greek-supplied} εκει και [γινεται]{.greek-omitted} [γεινετα[ι]{.greek-supplied}]{.greek-added} τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου χειρονα των πρωτων ουτως εσται και τη γενεα ταυτη τη πονηρα[12:45]{.aside}

### Chapter 13

τοτε αφεις τους οχλους ηλθεν εις την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} ο [ιησους]{.greek-abbr} και προσηλθον αυτω οι μαθηται αυτου λεγοντες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις ο [σπειρων]{.greek-omitted} [σπιρων]{.greek-added} το καλον σπερμα εστιν ο υιος του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του πονη[ρο]{.greek-supplied}υ[13:38]{.aside}

[ο]{.greek-supplied} δε εχθρος ο [σπειρας]{.greek-omitted} [σπιρας]{.greek-added} αυτα εστιν ο διαβολος ο δε θερισμος [συντελεια]{.greek-omitted} [συντελια]{.greek-added} του αιωνος εστιν οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν [συλλεγεται]{.greek-omitted} [συλλεται]{.greek-added} τα ζιζανια και πυρι [καιεται]{.greek-omitted} [κεεται]{.greek-added} ουτως εσται εν τη συντελεια του αιωνος τουτου[13:40]{.aside}

[αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και [βαλουσιν]{.greek-omitted} [βαλλουσιν]{.greek-added} αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο [βρυγμος]{.greek-supplied} [των]{.greek-supplied} [οδον]{.greek-supplied}των[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν τω αγρω ον ευρων [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας [αυτου]{.greek-omitted} υπαγει και παντα οσα εχει πωλει και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

ος ευρων ενα πολυτιμον μαργαριτην απελθων πεπρακεν παντα οσα ειχεν και ηγορασεν αυτον[13:46]{.aside}

### Chapter 26

[σαι]{.greek-added} [και]{.greek-omitted} [εμνησθη]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [του]{.greek-omitted} [ρηματος]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [ειρηκοτος]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [πριν]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} τρις απαρνηση με και εξελθων εξω εκλαυσεν πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν αυτον ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [εστη]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [του]{.greek-omitted} [ηγεμονος]{.greek-omitted} [και]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [ηγεμων]{.greek-omitted} [λεγων]{.greek-omitted} [συ]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted} ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου καταμαρτυρουσιν[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων [ενα]{.greek-added} απολυειν [ενα]{.greek-omitted} τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν[27:16]{.aside}

[ηδει]{.greek-omitted} [ηδι]{.greek-added} γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} [απολεσωσιν]{.greek-omitted} [απωλεσωσιν]{.greek-added}[27:20]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} [λεγουσιν]{.greek-supplied} [αυτω]{.greek-supplied} [παν]{.greek-supplied}τες σταυρωθητω[27:22]{.aside}

[οι]{.greek-added} [δε]{.greek-added} [περισσως]{.greek-added} [εκραζον]{.greek-added} [λεγοντες]{.greek-added} [σταυρωθητω]{.greek-added} ο δε ηγεμων εφη τι γαρ κακον εποιησεν [οι]{.greek-omitted} [δε]{.greek-omitted} [περισσως]{.greek-omitted} [εκραζον]{.greek-omitted} [λεγοντες]{.greek-omitted} [σταυρωθητω]{.greek-omitted}[27:23]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν [τον]{.greek-supplied} [δε]{.greek-supplied} [[ιησουν]{.greek-abbr}]{.greek-supplied} [φραγελλω]{.greek-supplied}σας παρεδωκεν ινα σταυρωθη[27:26]{.aside}

[ριον]{.greek-added} [συνηγαγον]{.greek-added} [επ]{.greek-added} [αυτον]{.greek-added} [ολην]{.greek-added} [την]{.greek-added} [σπιραν]{.greek-added} τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το [πραιτωριον]{.greek-omitted} [πραιτοριον]{.greek-added} συνηγαγον επ αυτον ολην την [σπειραν]{.greek-omitted} [σπιραν]{.greek-added}[27:27]{.aside}

και εκδυσαντε[ς]{.greek-supplied} [αυτον]{.greek-supplied} [περι]{.greek-supplied}εθηκαν αυτω χλαμυδα κοκκινην [και]{.greek-added} [εκδυσαντες]{.greek-added} [αυτον]{.greek-added} [περιεθηκαν]{.greek-added} [αυτω]{.greek-added} [χλαμυδα]{.greek-added} [κοκκινην]{.greek-added}[27:28]{.aside}

και πλεξαντες στεφανον [[εξ]{.greek-supplied}]{.greek-added} [[ακανθων]{.greek-supplied}]{.greek-added} [επεθηκαν]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [κεφ]{.greek-added} [αυτω]{.greek-added} [και]{.greek-added} [καλαμον]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [δεξιαν]{.greek-added} [αυτου]{.greek-added} [[και]{.greek-supplied}]{.greek-added} [[γονυπε]{.greek-supplied}τησαντες]{.greek-added} [εμπροσθεν]{.greek-added} [αυτου]{.greek-added} [ενεπεζον]{.greek-added} [αυτω]{.greek-added} [λεγοντες]{.greek-added} [χαιρε]{.greek-added} [β[ασιλευ]{.greek-supplied}]{.greek-added} [[των]{.greek-supplied}]{.greek-added} [ιουδαιων]{.greek-added} [και]{.greek-added} [πλεξαντες]{.greek-added} [στεφαν]{.greek-added} εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και [γονυπετησαντες]{.greek-omitted} [γονυπετησαντε]{.greek-added} εμπροσθεν αυτου [ενεπαιζον]{.greek-omitted} [ενεπεζον]{.greek-added} αυτω λεγοντες χαιρε [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [βασιλευ]{.greek-added} των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ε[τυπτον]{.greek-supplied} εις την κεφαλην αυτου [και]{.greek-added} [εμπτυ]{.greek-added}[27:30]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-omitted} [σταυρωθηναι]{.greek-added}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρη[ναιον]{.greek-supplied} ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον σταυρον αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα ο εστιν [λεγομενος]{.greek-omitted} [λεγομενον]{.greek-added} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ [ηθελεν]{.greek-omitted} [ηθελησεν]{.greek-added} πιειν[27:34]{.aside}

σταυρωσαντες [δε]{.greek-omitted} [ουν]{.greek-added} αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον [ινα]{.greek-added} [πληρωθη]{.greek-added} [το]{.greek-added} [ρηθεν]{.greek-added} [δια]{.greek-added} [του]{.greek-added} [προφητου]{.greek-added} [λεγοντος]{.greek-added} [διεμερισαντο]{.greek-added} [τα]{.greek-added} [ιματια]{.greek-added} [μου]{.greek-added} [εαυτοις]{.greek-added} [[τισμον]{.greek-supplied}]{.greek-added} [[μου]{.greek-supplied}]{.greek-added} [[εβαλον]{.greek-supplied}]{.greek-added} [κληρον]{.greek-added}[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-abbr} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε σταυρουνται συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον [κινουντες]{.greek-omitted} [κεινουντες]{.greek-added} τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} [καταβηθι]{.greek-omitted} [καταβηθει]{.greek-added} απο του σταυρου[27:40]{.aside}

## The Gospel of Mark

### Chapter 14

και [ευθυς]{.greek-added} εκ δευτερου [εφωνησεν]{.greek-added} αλεκτωρ [εφωνησεν]{.greek-omitted} και ανεμνησθη ο πετρος το ρημα [ο]{.greek-omitted} [ως]{.greek-added} ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις απαρνηση με [τρις]{.greek-omitted} [τρεις]{.greek-added} και επιβαλων [εκλαιεν]{.greek-omitted} [εκλεεν]{.greek-added}[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.corr} πρω[ι]{.greek-supplied} συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον [και]{.greek-added} δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν [προς]{.greek-added} [την]{.greek-added} [αυλην]{.greek-added} και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων [ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [συ]{.greek-omitted} [λεγεις]{.greek-omitted}[15:2]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν [απεκριθη]{.greek-omitted} [απεκρινατο]{.greek-added} ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των [συστασιαστων]{.greek-omitted} [συνστασιαστων]{.greek-added} δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

εγινωσκεν γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδωκεισαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεσισαν]{.greek-added} τον οχλον ινα μαλλον τον [βαραββαν]{.greek-omitted} [απολυση]{.greek-omitted} [αυτοις]{.greek-omitted}[15:11]{.aside}

ο δε πιλατος [παλιν]{.greek-added} αποκριθεις [παλιν]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} τι ουν [θελετε]{.greek-omitted} [θελεται]{.greek-added} ποιησω ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν σταυρωσον αυτον[15:13]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [ελεγεν]{.greek-omitted} αυτοις τι γαρ κακον εποιησεν οι δε περισσοτερως [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και παρεδωκεν τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγελωσας]{.greek-added} [ινα]{.unclear} σταυρωθη[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω [της]{.greek-omitted} [εις]{.greek-added} [την]{.greek-added} [αυλης]{.greek-omitted} [αυλην]{.greek-added} ο εστιν πραιτωριον και [συγκαλουσιν]{.greek-omitted} [συνκαλουσιν]{.greek-added} ολην την [σπειραν]{.greek-omitted} [σπιραν]{.greek-added}[15:16]{.aside}

και ενδυουσιν αυτον [χλαμυδα]{.greek-added} [κοκκινην]{.greek-added} [και]{.greek-added} πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [βασιλευ]{.greek-added} των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον [την]{.greek-added} [χλαμυδα]{.greek-added} [και]{.greek-added} την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-omitted} [σταυρωσουσιν]{.greek-added} αυτον[15:20]{.aside}

και αγγαρευουσιν [τινα]{.greek-added} παραγοντα [τινα]{.greek-omitted} σιμωνα κυρηναιον ερχομενον απ αγρου τον πατερα αλεξανδρου και ρουφου ινα αρη τον σταυρον αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} γολγοθα τοπον ο εστιν μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν [εσμυρνισμενον]{.greek-omitted} [εσμυρνομενον]{.greek-added} [οινον]{.greek-omitted} ο δε ουκ ελαβεν[15:23]{.aside}

και σταυρωσαντες αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω σταυρουσιν δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

