---
title: "Collation of Byz^RP^ vs 20304 (304)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 304 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20304).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 304                                   	| λογος                              	|
| 304 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 304 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 304               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 304                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 304 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 304                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 6

[και]{.greek-omitted} [ηρεσεν]{.greek-omitted} [ο]{.greek-omitted} [λογος]{.greek-omitted} [ενωπιον]{.greek-omitted} [παντος]{.greek-omitted} [του]{.greek-omitted} [πληθους]{.greek-omitted} [και]{.greek-omitted} [εξελεξαντο]{.greek-omitted} [στεφανον]{.greek-omitted} [ανδρα]{.greek-omitted} [πληρης]{.greek-omitted} [πιστεως]{.greek-omitted} [και]{.greek-omitted} [πνευματος]{.greek-omitted} [αγιου]{.greek-omitted} [και]{.greek-omitted} [φιλιππον]{.greek-omitted} [και]{.greek-omitted} [προχορον]{.greek-omitted} και [ν]{.unclear}[ικα]{.greek-supplied}[νορα]{.greek-supplied} [κ]{.greek-supplied}αι τιμωνα και [παρμε]{.greek-supplied}[ναν]{.unclear} και [ν]{.unclear}ικολα[ον]{.greek-supplied} [προσ]{.greek-supplied}ηλυ[τ]{.unclear}ον αντιο[χεα]{.greek-supplied}[6:5]{.aside}

[ο]{.greek-supplied}[υ]{.unclear}ς ε[σ]{.unclear}τησαν ενω[πιον]{.greek-supplied} [τ]{.greek-supplied}[ω]{.unclear}ν αποστολων [και]{.greek-supplied} [πρ]{.greek-supplied}[ο]{.unclear}σευξαμενοι ε[πεθη]{.greek-supplied}[κ]{.unclear}αν αυτοι[ς]{.unclear} τας [χειρας]{.greek-supplied}[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} [ηυ]{.greek-supplied}[ξ]{.unclear}ανεν κ[αι]{.greek-supplied} [ε]{.unclear}πλη[θυνετο]{.greek-supplied} [ο]{.greek-supplied} αρ[ι]{.unclear}θ[μο]{.unclear}ς τ[ων]{.greek-supplied} [μαθη]{.greek-supplied}των ε[ν]{.unclear} [ιερουσαλημ]{.greek-abbr} σφο[δρα]{.greek-supplied} [π]{.greek-supplied}ολυς τε [ο]{.unclear}χλος [των]{.greek-supplied} [ι]{.greek-supplied}[ε]{.unclear}ρεων υπηκου[ον]{.greek-supplied} [τη]{.greek-supplied} [πιστει]{.greek-omitted} [πιστη]{.greek-added}[6:7]{.aside}

[στεφα]{.greek-supplied}νο[ς]{.unclear} [δε]{.unclear} [πλη]{.unclear}ρη[ς]{.unclear} [πιστεως]{.greek-omitted} [[χα]{.unclear}[ριτος]{.greek-supplied}]{.greek-added} [κ]{.unclear}α[ι]{.unclear} δυν[α]{.unclear}με[ω]{.unclear}[ς]{.greek-supplied} [ε]{.greek-supplied}[ποιει]{.greek-supplied} [τ]{.greek-supplied}ερατα και ση[μεια]{.greek-supplied} μεγαλα εν [τ]{.unclear}ω λαω [[δια]{.greek-supplied}]{.greek-added} [[τ]{.greek-supplied}[ο]{.unclear}υ]{.greek-added} [ονοματος]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added}[6:8]{.aside}

ανεστησαν [δε]{.greek-supplied} [τι]{.greek-supplied}νες των εκ τ[η]{.unclear}[ς]{.greek-supplied} [συνα]{.greek-supplied}[γ]{.unclear}ωγ[ης]{.unclear} [της]{.greek-omitted} [τω[ν]{.unclear}]{.greek-added} [λεγομενης]{.greek-omitted} [λε[γ]{.unclear}ο[μεν]{.greek-supplied}[ω]{.unclear}ν]{.greek-added} λιβερ[τ]{.unclear}[ι]{.greek-supplied}νων [και]{.greek-supplied} [κ]{.greek-supplied}υρη[ν]{.greek-supplied}α[ι]{.greek-supplied}ων και α[λεξα]{.greek-supplied}νδρε[ων]{.unclear} και των [απο]{.greek-supplied} [κ]{.greek-supplied}ιλικι[α]{.unclear}ς και ασιας [συζ]{.greek-supplied}[η]{.unclear}τουντες τω στε[φαν]{.greek-supplied}[ω]{.unclear}[6:9]{.aside}

και ουκ [ισχυον]{.greek-omitted} [ισχυσαν]{.greek-added} [αντ]{.greek-supplied}ιστηναι τ[η]{.greek-supplied} [σο]{.unclear}φια [και]{.greek-supplied} [τ]{.greek-supplied}ω [πνευματι]{.greek-abbr} ω [ελ]{.unclear}[αλει]{.greek-supplied}[[6:10 *(lacunose)*]{.lacunose}]{.aside}

[συνεκινησαν]{.greek-omitted} [τε]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πρεσβυ]{.greek-supplied}τερου[ς]{.unclear} κα[ι]{.unclear} [του]{.unclear}[ς]{.greek-supplied} [γραμ]{.greek-supplied}ματ[ει]{.unclear}ς και [ε]{.unclear}πι[σταν]{.unclear}τες συνηρπασαν αυτον και ηγαγον εις το συν[εδριον]{.unclear}[[6:12 *(lacunose)*]{.lacunose}]{.aside}

[ε]{.unclear}στ[η]{.unclear}σα[ν]{.unclear} τε μ[αρτυ]{.unclear}ρας ψευ[δ]{.unclear}εις λεγ[ο]{.unclear}ντ[ας]{.unclear} [[ο]{.unclear}τ[ι]{.unclear}]{.greek-added} [ο]{.greek-supplied} [ανθρωπος]{.greek-abbr} [ουτος]{.greek-omitted} ου [παυεται]{.greek-omitted} [[παυ]{.greek-supplied}[ετε]{.unclear}]{.greek-added} [ρηματα]{.greek-omitted} [βλασφημα]{.greek-omitted} [λαλων]{.greek-omitted} κα[τα]{.unclear} του τοπου του α[γ]{.unclear}[ιο]{.greek-supplied}υ [τ[ου]{.unclear}[το]{.unclear}υ]{.greek-added} [κ]{.unclear}αι του [ν]{.unclear}ομου [[λα]{.unclear}λων]{.greek-added} [ρηματα]{.greek-added} [βλασφημα]{.greek-added}[6:13]{.aside}

ακηκοαμεν γαρ αυτ[ου]{.unclear} λεγοντο[ς]{.greek-supplied} [οτι]{.unclear} [ιησους]{.greek-abbr} ο να[ζ]{.unclear}ωρ[α]{.unclear}ιος ουτος κα[τα]{.unclear}λυσε[ι]{.greek-supplied} [το]{.greek-supplied}ν τοπο[ν]{.unclear} τ[ου]{.unclear}τον και αλλαξει [τ]{.greek-supplied}[α]{.unclear} [εθ]{.unclear}η [α]{.unclear} [πα]{.unclear}ρεδω[κ]{.unclear}[εν]{.greek-supplied} η[μι]{.unclear}ν [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[6:14]{.aside}

και ατενισαντες εις αυτο[ν]{.unclear} [απ]{.unclear}αντες οι καθεζομενοι εν τω συνεδριω [ειδον]{.greek-omitted} [ιδον]{.greek-added} το προσωπον αυτου ωσ[ε]{.unclear}ι προσωπ[ον]{.greek-supplied} αγγελου[6:15]{.aside}

### Chapter 7

ει[πεν]{.unclear} δε ο αρχιερευς ει αρα ταυτα [ο]{.unclear}υτως [ει]{.greek-added} [αρα]{.greek-added} [ταυτα]{.greek-added} [ουτως]{.greek-added} εχει[7:1]{.aside}

ο δ[ε]{.unclear} εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσα[τε]{.greek-supplied} [ο]{.unclear} [θεος]{.greek-abbr} τ[ης]{.unclear} δοξης [ωφθη]{.greek-omitted} [τω]{.greek-omitted} [πατρι]{.greek-omitted} [ημων]{.greek-omitted} [αβρααμ]{.greek-omitted} [οντι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [μεσοποταμια]{.greek-omitted} [πριν]{.greek-omitted} [η]{.greek-omitted} [κατοικησαι]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [χαρραν]{.greek-omitted}[[7:2 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [εξελθε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [συγ]{.greek-supplied}[γενειας]{.greek-supplied} [σου]{.greek-supplied} [και]{.greek-supplied} [δευρο]{.unclear} [εις]{.greek-supplied} [[την]{.greek-supplied}]{.greek-added} [γ]{.greek-supplied}ην [ην]{.unclear} [α]{.unclear}ν σοι [δει]{.unclear}ξω[[7:3 *(lacunose)*]{.lacunose}]{.aside}

τοτε εξελθων ε[κ]{.unclear} γη[ς]{.unclear} χ[αλ]{.unclear}δαιων κατωκησεν [ε]{.greek-supplied}[ν]{.unclear} χαρραν κακειθεν μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μ[ε]{.unclear}τωκεισεν]{.greek-added} αυτ[ο]{.unclear}ν εις την γην ταυτην εις ην υμεις νυν κατοι[κει]{.unclear}τ[ε]{.unclear}[7:4]{.aside}

κ[α]{.greek-supplied}ι [ο]{.unclear}υκ εδωκεν αυτω κ[λ]{.unclear}ηρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι [αυτω]{.greek-omitted} [αυ[τ]{.unclear}ην]{.greek-added} εις κατ[ασ]{.unclear}χεσιν [αυτην]{.greek-omitted} [αυτω]{.greek-added} και τω σπερματι αυτου μετ αυτον ουκ [οντος]{.greek-omitted} [οντως]{.greek-added} αυτω τεκνου[7:5]{.aside}

ελαλησεν δε [ουτως]{.greek-omitted} [αυτω]{.greek-added} ο [θεος]{.greek-abbr} οτι εσται το σπερμα αυτου παροικον εν γη αλλοτρια και δουλωσουσιν αυτο και κακωσουσιν ετη τετρακοσια[7:6]{.aside}

και το εθνος ω εαν δουλευσωσιν κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και λατρευσουσιν [μοι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [τοπω]{.greek-omitted} [τουτω]{.greek-omitted}[[7:7 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτω]{.greek-omitted} [διαθηκην]{.greek-omitted} [περιτομης]{.greek-omitted} [και]{.greek-omitted} [ουτως]{.greek-omitted} [εγεννησεν]{.greek-omitted} [τον]{.greek-omitted} [ισαακ]{.greek-omitted} [και]{.greek-omitted} [περιετεμεν]{.greek-omitted} [αυτον]{.greek-omitted} [τη]{.unclear} [ημ]{.unclear}ερ[α]{.unclear} [τη]{.unclear} [ογδοη]{.greek-supplied} και [ο]{.greek-omitted} ισαακ τ[ο]{.unclear}ν [ιακωβ]{.greek-supplied} και [ο]{.greek-omitted} ιακωβ τ[ους]{.greek-supplied} [δω]{.greek-supplied}δεκα πα[τ]{.unclear}ρι[α]{.unclear}[ρχας]{.greek-supplied}[[7:8 *(lacunose)*]{.lacunose}]{.aside}

και οι πατριαρ[χαι]{.greek-supplied} [ζη]{.greek-supplied}λωσ[α]{.unclear}ντες το[ν]{.greek-supplied} [ιωσηφ]{.greek-supplied} απεδοντο ε[ι]{.unclear}[ς]{.greek-supplied} [αιγυπτον]{.greek-supplied} και ην ο [θεος]{.greek-abbr} μ[ε]{.unclear}[τ]{.greek-supplied} [αυτου]{.greek-supplied}[7:9]{.aside}

και [εξειλετο]{.greek-omitted} [εξιλατο]{.greek-added} [αυτον]{.greek-supplied} εκ π[α]{.unclear}[σ]{.greek-supplied}ων τω[ν]{.greek-supplied} [θλιψε]{.greek-supplied}ω[ν]{.unclear} αυτου [κα]{.unclear}[ι]{.greek-supplied} [εδωκεν]{.greek-supplied} αυτ[ω]{.unclear} χαριν [κ]{.unclear}[αι]{.greek-supplied} [σοφιαν]{.greek-supplied} [εναν]{.greek-added} [εναντιον]{.greek-omitted} [[εναντι]{.corr}]{.greek-added} φαραω [βασιλεως]{.greek-supplied} αιγυπτου κα[ι]{.greek-supplied} [κατεσ]{.greek-supplied}τησεν αυτον [ηγου]{.greek-supplied}μενον επ αιγ[υπτον]{.greek-supplied} και ολον το[ν]{.unclear} [οικον]{.greek-supplied} αυτου[7:10]{.aside}

ηλ[θε]{.unclear}[ν]{.greek-supplied} [δε]{.greek-supplied} [λι]{.greek-supplied}μος εφ ολην [την]{.greek-supplied} [γην]{.greek-supplied} αιγυπτου και [χανα]{.greek-supplied}αν και θλιψ[ις]{.unclear} [μεγα]{.greek-supplied}λη και ουχ ευρ[ισκον]{.greek-supplied} χορτασματα [ο]{.unclear}[ι]{.greek-supplied} [πατερες]{.greek-abbr} [ημων]{.greek-omitted} [οιμων]{.greek-added}[7:11]{.aside}

ακου[σ]{.unclear}[ας]{.greek-supplied} [δε]{.greek-supplied} [ι]{.greek-supplied}ακωβ οντα [σιτα]{.greek-omitted} [σ[ε]{.unclear}[ιτια]{.greek-supplied}]{.greek-added} [ε]{.greek-supplied}ν αιγυπτω ε[ξ]{.unclear}[απεσ]{.greek-supplied}τειλεν τους [πατερας]{.greek-abbr} [ημων]{.greek-supplied} πρωτον[7:12]{.aside}

και ε[ν]{.unclear} [τω]{.greek-supplied} δευτερω ανεγ[νωρισ]{.greek-supplied}θη ιωσηφ τοι[ς]{.unclear} [αδελ]{.greek-supplied}φοις αυτου κα[ι]{.greek-supplied} [φανερον]{.greek-omitted} [εγενετο]{.greek-omitted} [τω]{.greek-omitted} [φαραω]{.greek-omitted} [το]{.greek-omitted} [γενος]{.greek-omitted} [του]{.greek-omitted} [ιωσηφ]{.greek-omitted}[7:13]{.aside}

