---
title: "Collation of Byz^RP^ vs 20301 (301)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 301 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=20301).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 301                                   	| λογος                              	|
| 301 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 301 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 301               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 301                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 301 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 301                                                     	| [―]{.gap}                        	|
:::

## The Gospel of John

### Chapter 17

[ταυτα]{.greek-omitted} [ελαλησεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [επηρεν]{.greek-omitted} [τους]{.greek-omitted} [μους]{.greek-added} [οφθαλμους]{.greek-omitted} αυτου εις τον [ουρανον]{.greek-abbr} [και]{.greek-omitted} ειπεν [πατερ]{.greek-abbr} εληλυ[θεν]{.greek-supplied} η ωρα δοξασο[ν]{.greek-supplied} σου τον [υιον]{.greek-abbr} ινα [και]{.greek-omitted} ο [υιος]{.greek-abbr} [σου]{.greek-omitted} δο[ξα]{.unclear}ση σε[17:1]{.aside}

καθως εδωκας αυτω εξουσιαν πασης σαρκος ινα παν ο δεδωκας αυτω δωσει αυτοις [ζω]{.greek-supplied}ην αιωνιον[17:2]{.aside}

[α]{.greek-supplied}υτη δε εστιν [η]{.greek-supplied} αιωνιος ζω[η]{.greek-supplied} ινα [γινωσκωσιν]{.greek-omitted} [γιν[ωσ]{.unclear}[κ]{.unclear}ουσιν]{.greek-added} σε τον μονον [αληθινον]{.greek-omitted} [αληθεινον]{.greek-added} [θεον]{.greek-abbr} και ον απεστειλας [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr}[17:3]{.aside}

εγω σε εδοξασα επι της γης το [ερ]{.greek-supplied}γον [ετελειωσα]{.greek-omitted} [τελειωσας]{.greek-added} ο [δεδω]{.greek-added} [δεδωκας]{.greek-omitted} [μοι]{.greek-omitted} [ινα]{.greek-omitted} [ποιησω]{.greek-omitted}[17:4]{.aside}

