---
title: "Collation of Byz^RP^ vs 30026 (26)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 26 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30026).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 26                                   	| λογος                              	|
| 26 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 26 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 26               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 26                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 26 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 26                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν [τη]{.greek-omitted} [τηι]{.greek-added} [ερημω]{.greek-omitted} [ερημωι]{.greek-added} ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης [βαπτιζων]{.greek-omitted} [βατιζων]{.greek-added} εν [τη]{.greek-omitted} [τηι]{.greek-added} [ερημω]{.greek-omitted} [ερημωι]{.greek-added} και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται και εβαπτιζοντο παντες εν [τω]{.greek-omitted} [τωι]{.greek-added} [ιορδανη]{.greek-omitted} [ιορδανηι]{.greek-added} [ποταμω]{.greek-omitted} [ποταμωι]{.greek-added} υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας [εν]{.greek-omitted} υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} [αγιω]{.greek-omitted} [αγιωι]{.greek-added}[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} [ωσει]{.greek-omitted} [ως]{.greek-added} περιστεραν καταβαινον [ε]{.greek-added} [επ]{.greek-omitted} [αυτον]{.greek-omitted}[1:10]{.aside}

[π]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [αναβαινων]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [υδατος]{.greek-omitted} [ειδεν]{.greek-omitted} [σχιζομενους]{.greek-omitted} [τους]{.greek-omitted} [ουρανους]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ωσει]{.greek-omitted} [περιστεραν]{.greek-omitted} [καταβαινον]{.greek-omitted} [επ]{.greek-omitted} αυτον[1:10 | instance no. 2]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν [ω]{.greek-omitted} [ωι]{.greek-added} ευδοκησα[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν [τη]{.greek-omitted} [τηι]{.greek-added} [ερημω]{.greek-omitted} [ερημωι]{.greek-added} ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[1:13]{.aside}

μετα δε το παραδοθηναι [τον]{.greek-omitted} ιωαννην ηλθεν [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν [τω]{.greek-omitted} [τωι]{.greek-added} [ευαγγελιω]{.greek-omitted} [ευαγγελιωι]{.greek-added}[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και ανδρεαν [τον]{.greek-omitted} [αδελφον]{.greek-omitted} αυτου του σιμωνος [τον]{.greek-added} [αδελφον]{.greek-added} βαλλοντας αμφιβληστρον εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν [τω]{.greek-omitted} [τωι]{.greek-added} [πλοιω]{.greek-omitted} [πλοιωι]{.greek-added} καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν [τω]{.greek-omitted} [τωι]{.greek-added} [πλοιω]{.greek-omitted} [πλοιωι]{.greek-added} μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο επι [τη]{.greek-omitted} [τηι]{.greek-added} [διδαχη]{.greek-omitted} [διδαχηι]{.greek-added} αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν [τη]{.greek-omitted} [τηι]{.greek-added} [συναγωγη]{.greek-omitted} [συναγωγηι]{.greek-added} αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} [ακαθαρτω]{.greek-omitted} [ακαθαρτωι]{.greek-added} και [ανεκραξεν]{.greek-omitted} [εκραξε]{.greek-added}[1:23]{.aside}

λεγων [εα]{.greek-omitted} [τι]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [σοι]{.greek-omitted} [ιησου]{.greek-omitted} [ναζαρηνε]{.greek-omitted} [ηλθες]{.greek-omitted} [απολεσαι]{.greek-omitted} [ημας]{.greek-omitted} [οιδα]{.greek-omitted} [σε]{.greek-omitted} [τις]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[1:24]{.aside}

[λεγων]{.greek-omitted} εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24 | instance no. 2]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους λεγοντας τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [[πνασι]{.greek-abbr}]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου [ευθυς]{.greek-omitted} εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη [ην]{.greek-omitted} προς [την]{.greek-omitted} [τηι]{.greek-added} [θυραν]{.greek-omitted} [θυραι]{.greek-added}[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις νοσο[ι]{.unclear}ς και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον[1:34]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και [λε]{.greek-added} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [αγωμεν]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [εχομενας]{.greek-omitted} [κωμοπολεις]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [εκει]{.greek-omitted} [κηρυξω]{.greek-omitted} [εις]{.greek-omitted} [τουτο]{.greek-omitted} [γαρ]{.greek-omitted} [εξεληλυθα]{.greek-omitted}[1:38]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [γει]{.greek-added} αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38 | instance no. 2]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οτι εαν [θελης]{.greek-omitted} [θεληις]{.greek-added} δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ορα μηδενι [μηδεν]{.greek-omitted} ειπης [αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγε σεαυτον δειξον [τω]{.greek-omitted} [τωι]{.greek-added} ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις καπερναουμ δι ημερ[ω]{.unclear}ν και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την [θυραν]{.greek-omitted} [θυρα]{.greek-added} και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ [ω]{.greek-omitted} [ωι]{.greek-added} ο [παραλυτικος]{.greek-omitted} [κατεκειτο]{.greek-omitted}[2:4]{.aside}

[και]{.greek-omitted} [μη]{.greek-omitted} [δυναμενοι]{.greek-omitted} [προσεγγισαι]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [απεστεγασαν]{.greek-omitted} [την]{.greek-omitted} [στεγην]{.greek-omitted} [οπου]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [εξορυξαντες]{.greek-omitted} [χαλωσιν]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [εφ]{.greek-omitted} [ω]{.greek-omitted} [ο]{.greek-omitted} παραλυτικος κατεκειτο[2:4 | instance no. 2]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει [τω]{.greek-omitted} [τωι]{.greek-added} [παραλυτικω]{.greek-omitted} [παραλυτικωι]{.greek-added} τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [πνευματι]{.greek-abbr} αυτου [οτι]{.greek-omitted} [ουτως]{.greek-omitted} [αυτοι]{.greek-omitted} [διαλογιζονται]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν [τω]{.greek-omitted} [τωι]{.greek-added} [παραλυτικω]{.greek-omitted} [παραλυτικωι]{.greek-added} [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} αμαρτιας λεγει [τω]{.greek-omitted} [τωι]{.greek-added} [παραλυτικω]{.greek-omitted} [παραλυτικωι]{.greek-added}[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως ειδομεν[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ειδε]{.greek-added} λευι τον του [αλφαιου]{.greek-omitted} [αλφεου]{.greek-added} καθημενον επι το τελωνιον και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ακολουθει μοι και αναστας ηκολουθησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[2:14]{.aside}

και εγενετο εν [τω]{.greek-omitted} [τωι]{.greek-added} κατακεισθαι αυτον εν [τη]{.greek-omitted} [τηι]{.greek-added} [οικια]{.greek-omitted} [οικιαι]{.greek-added} αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο [τω]{.greek-omitted} [τωι]{.greek-added} [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[2:15]{.aside}

και οι γραμματεις και οι [φα]{.greek-added} [φαρισαιοι]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [εσθιοντα]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} [ελεγον]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [τι]{.greek-omitted} [οτι]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} [εσθιει]{.greek-omitted} [και]{.greek-omitted} [πινει]{.greek-omitted}[2:16]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ρισαιοι]{.greek-added} ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} εσθιει και πινει[2:16 | instance no. 2]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν [ω]{.greek-omitted} [ωι]{.greek-added} ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι [ιματιω]{.greek-omitted} [ιματιωι]{.greek-added} [παλαιω]{.greek-omitted} [παλαιωι]{.greek-added} ει δε μη αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι [απολουνται]{.greek-omitted} [απολλυνται]{.greek-added} αλλα οινον νεον εις ασκους καινους βλητεον[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει [εν]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει [αυτον]{.greek-omitted} ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει [τω]{.greek-omitted} [τωι]{.greek-added} [ανθρωπω]{.greek-omitted} [[ανωι]{.greek-abbr}]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} εξηραμμενην εχοντι την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι [τη]{.greek-omitted} [τηι]{.greek-added} [πωρωσει]{.greek-omitted} [πωρρωσει]{.greek-added} της καρδιας αυτων λεγει [τω]{.greek-omitted} [τωι]{.greek-added} [ανθρωπω]{.greek-omitted} [[ανωι]{.greek-abbr}]{.greek-added} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και αποκατεσταθη η χειρ αυτου υγιης ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον [εποιουν]{.greek-omitted} [εποιησαν]{.greek-added} κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [ηκολουθησεν]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και απο της ιουδαιας[3:7]{.aside}

και [απο]{.corr} ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και σιδωνα [πληθος]{.greek-omitted} [πολυ]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οσα]{.greek-omitted} [εποιει]{.greek-omitted} [ηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[3:8]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} [και]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [περι]{.greek-omitted} [τυρον]{.greek-omitted} [και]{.greek-omitted} [σιδωνα]{.greek-omitted} πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8 | instance no. 2]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον προσκαρτερη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [απτωνται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα οταν αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστειλη]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [του]{.greek-omitted} [αυτου]{.greek-added} [ιακωβου]{.greek-omitted} και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον [τον]{.greek-omitted} του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν [ο]{.greek-added} οχλος ωστε μη δυνασθαι αυτους [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και [ο]{.greek-added} [οτι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αρχοντι]{.greek-omitted} [των]{.greek-omitted} [δαιμονιων]{.greek-omitted} [εκβαλλει]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted}[3:22]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [οι]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [καταβαντες]{.greek-omitted} [ελεγον]{.greek-omitted} [οτι]{.greek-omitted} [τι]{.greek-added} [βεελζεβουλ]{.greek-omitted} [εχει]{.greek-omitted} [και]{.greek-omitted} [οτι]{.greek-omitted} εν [τω]{.greek-omitted} [τωι]{.greek-added} αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22 | instance no. 2]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται [σταθηναι]{.greek-omitted} [στηναι]{.greek-added} η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου [εισελθων]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπασαι]{.greek-omitted} [αρπασαι]{.greek-added} εαν μη πρωτον τον ισχυρον [δηση]{.greek-omitted} [δησηι]{.greek-added} και τοτε την οικιαν αυτου διαρπαση[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημησηι]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες [αυτον]{.greek-omitted} [αυτωι]{.greek-added}[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} ειπον δε [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν [ποιηση]{.greek-omitted} [ποιησηι]{.greek-added} το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} εστιν[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και [συνη]{.greek-added} [συνηχθη]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [ωστε]{.greek-omitted} [αυτον]{.greek-omitted} [εμβαντα]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [καθησθαι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ην]{.greek-omitted}[4:1]{.aside}

[χθη]{.greek-added} [και]{.greek-omitted} [παλιν]{.greek-omitted} [ηρξατο]{.greek-omitted} [διδασκειν]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [συνηχθη]{.greek-omitted} προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1 | instance no. 2]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν [τη]{.greek-omitted} [τηι]{.greek-added} [διδαχη]{.greek-omitted} [διδαχηι]{.greek-added} αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν [τω]{.greek-omitted} [τωι]{.greek-added} σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα [πετεινα]{.greek-omitted} [πετηνα]{.greek-added} και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ εδωκεν[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και [αφεθη]{.greek-omitted} [αφεθησεται]{.greek-added} αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον [ο]{.greek-omitted} εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε [τι]{.greek-omitted} ακουετε εν [ω]{.greek-omitted} [ωι]{.greek-added} [μετρω]{.greek-omitted} [μετρωι]{.greek-added} μετρειτε μετρηθησεται υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ αν εχη δοθησεται [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η [βασι]{.greek-added} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ως]{.greek-omitted} [εαν]{.greek-omitted} [ανθρωπος]{.greek-omitted} [βαλη]{.greek-omitted} [τον]{.greek-omitted} [σπορον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[4:26]{.aside}

[λεια]{.greek-added} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [ουτως]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26 | instance no. 2]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρετε]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν [τω]{.greek-omitted} [τωι]{.greek-added} σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσω]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν [ποια]{.greek-omitted} [ποιαι]{.greek-added} [παραβολη]{.greek-omitted} [παραβοληι]{.greek-added} παραβαλωμεν αυτην[4:30]{.aside}

ως [κοκκον]{.greek-omitted} [κοκκωι]{.greek-added} σιναπεως ος οταν [σπαρη]{.greek-omitted} [σπαρηι]{.greek-added} επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [σπαρηι]{.greek-added} αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα [πετεινα]{.greek-omitted} [πετηνα]{.greek-added} του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν [εκεινη]{.greek-omitted} [εκεινηι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} [ημερα]{.greek-omitted} [ημεραι]{.greek-added} οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν [τω]{.greek-omitted} [τωι]{.greek-added} [πλοιω]{.greek-omitted} [πλοιωι]{.greek-added} και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται λαιλαψ ανεμου μεγαλη τα δε κυματα επεβαλλεν εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι [τη]{.greek-omitted} [τηι]{.greek-added} [πρυμνη]{.greek-omitted} [πρυμνηι]{.greek-added} επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [ανεμω]{.greek-omitted} [ανεμωι]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασ]{.greek-added} [σιωπα]{.greek-omitted} [πεφιμωσο]{.greek-omitted} [και]{.greek-omitted} [εκοπασεν]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [γαληνη]{.greek-omitted} [μεγαλη]{.greek-omitted}[4:39]{.aside}

[σηι]{.greek-added} [και]{.greek-omitted} [διεγερθεις]{.greek-omitted} [επετιμησεν]{.greek-omitted} [τω]{.greek-omitted} [ανεμω]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39 | instance no. 2]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν [αυτω]{.greek-omitted} [αυτου]{.greek-added}[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γαδδαρηνων]{.greek-added}[5:1]{.aside}

και εξελθοντι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εκ του πλοιου ευθεως απηντησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} [ακαθαρτω]{.greek-omitted} [ακαθαρτωι]{.greek-added}[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [ισχυσεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημασι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[5:6]{.aside}

και κραξας [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} ειπεν τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με [βασανισης]{.greek-omitted} [βασανισηις]{.greek-added}[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι ονομα και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτωι]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη [αυτους]{.greek-omitted} αποστειλη [αυτον]{.greek-added} εξω της χωρας[5:10]{.aside}

ην δε [εκει]{.greek-omitted} [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων μεγαλη βοσκομενη [προς]{.greek-added} [τωι]{.greek-added} [ορει]{.greek-added}[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον [παντες]{.greek-omitted} οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα [εις]{.greek-omitted} [αυτους]{.greek-omitted} [εισελθωμεν]{.greek-omitted}[5:12]{.aside}

[και]{.greek-omitted} [παρεκαλεσαν]{.greek-omitted} [αυτον]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [δαιμονες]{.greek-omitted} [λεγοντες]{.greek-omitted} [πεμψον]{.greek-omitted} [ημας]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [ινα]{.greek-omitted} εις αυτους εισελθωμεν[5:12 | instance no. 2]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε [ως]{.greek-omitted} [ωσει]{.greek-added} δισχιλιοι και επνιγοντο εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added}[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο [τω]{.greek-omitted} [τωι]{.greek-added} [δαιμονιζομενω]{.greek-omitted} [δαιμονιζομενωι]{.greek-added} και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} μετ αυτου [ηι]{.greek-added}[5:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ αφηκεν αυτον αλλα λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν [τη]{.greek-omitted} [τηι]{.greek-added} δεκαπολει οσα εποιησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν [τω]{.greek-omitted} [τωι]{.greek-added} [πλοιω]{.greek-omitted} [πλοιωι]{.greek-added} παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [αυτη]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [οπως]{.greek-omitted} [σωθη]{.greek-omitted} [και]{.greek-omitted} [ζησεται]{.greek-omitted}[5:23]{.aside}

[και]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [πολλα]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [μου]{.greek-omitted} [εσχατως]{.greek-omitted} [εχει]{.greek-omitted} [ινα]{.greek-omitted} [ελθων]{.greek-omitted} επιθης [αυτη]{.greek-omitted} [αυτηι]{.greek-added} τας χειρας οπως σωθη και ζησεται[5:23 | instance no. 2]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και ηκολουθει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν [τω]{.greek-omitted} [τωι]{.greek-added} [οχλω]{.greek-omitted} [οχλωι]{.greek-added} οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [εν]{.greek-added} [εαυτηι]{.greek-added} οτι καν [των]{.greek-omitted} [ιματιων]{.greek-omitted} [του]{.greek-added} [ιματιου]{.greek-added} αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω [τω]{.greek-omitted} [τωι]{.greek-added} σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν [εαυτω]{.greek-omitted} [εαυτωι]{.greek-added} την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν [τω]{.greek-omitted} [τωι]{.greek-added} [οχλω]{.greek-omitted} [οχλωι]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ [αυτη]{.greek-omitted} [αυτηι]{.greek-added} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλεις]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει [τω]{.greek-omitted} [τωι]{.greek-added} [αρχισυναγωγω]{.greek-omitted} [αρχισυναγωγωι]{.greek-added} μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [συνακολουθησαι]{.greek-omitted} [ακολουθησαι]{.greek-added} ει μη πετρον [και]{.greek-omitted} [ιακωβον]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [τον]{.greek-omitted} [αδελφον]{.greek-omitted} [ιακωβου]{.greek-omitted}[5:37]{.aside}

[και]{.greek-omitted} [ουκ]{.greek-omitted} [αφηκεν]{.greek-omitted} [ουδενα]{.greek-omitted} [αυτω]{.greek-omitted} [συνακολουθησαι]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [πετρον]{.greek-omitted} και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37 | instance no. 2]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι θορυβεισθε και κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει [αυτη]{.greek-omitted} [αυτηι]{.greek-added} ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ [ως]{.greek-added} ετων δωδεκα και εξεστησαν εκστασει [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added}[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις [γνω]{.greek-omitted} [γνωι]{.greek-added} τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι [αυτη]{.greek-omitted} [αυτηι]{.greek-added} φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την πατριδα αυτου και ακολουθουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν [τη]{.greek-omitted} [τηι]{.greek-added} [συναγωγη]{.greek-omitted} [συναγωγηι]{.greek-added} διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτωι]{.greek-added} ταυτα και τις η σοφια η δοθεισα [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ινα]{.greek-added} και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο τεκτων ο [υιος]{.greek-abbr} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν [τη]{.greek-omitted} [τηι]{.greek-added} [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσι]{.greek-added} και εν [τη]{.greek-omitted} [τηι]{.greek-added} [οι]{.greek-added} [οικια]{.greek-omitted} [αυτου]{.greek-omitted}[6:4]{.aside}

[κιαι]{.greek-added} [ελεγεν]{.greek-omitted} [δε]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [προφητης]{.greek-omitted} [ατιμος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πατριδι]{.greek-omitted} αυτου [και]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [συγγενεσιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [αυτου]{.greek-omitted}[6:4 | instance no. 2]{.aside}

και ουκ [ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν [αιρωσιν]{.greek-omitted} [αρωσιν]{.greek-added} εις οδον ει μη ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσασθαι]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η γομορροις εν [ημερα]{.greek-omitted} [ημεραι]{.greek-added} κρισεως η [τη]{.greek-omitted} [τηι]{.greek-added} πολει [εκεινη]{.greek-omitted} [εκεινηι]{.greek-added}[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον [ελαιω]{.greek-omitted} [ελαιωι]{.greek-added} πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων [ηγερθη]{.greek-omitted} [ανεστη]{.greek-added} και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν [οτι]{.greek-omitted} [ον]{.greek-omitted} [εγω]{.greek-omitted} [απεκεφαλισα]{.greek-omitted} [ιωαννην]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [αυτος]{.greek-omitted} [ηγερθη]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted}[6:16]{.aside}

[ακουσας]{.greek-omitted} [δε]{.greek-omitted} [ηρωδης]{.greek-omitted} [ειπεν]{.greek-omitted} οτι ον εγω απεκεφαλισα ιωαννην ουτος εστιν [αυτος]{.corr} [ηγερθη]{.corr} [εκ]{.corr} [νεκρων]{.corr}[6:16 | instance no. 2]{.aside}

αυτος γαρ ο ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον ιωαννην και εδησεν αυτον εν [φυλακη]{.greek-omitted} [φυλακηι]{.greek-added} δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο ιωαννης [τω]{.greek-omitted} [τωι]{.greek-added} [ηρωδη]{.greek-omitted} [ηρωδηι]{.greek-added} οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και [ακουσας]{.greek-omitted} [ακουων]{.greek-added} αυτου πολλα εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις [χιλιαρχοις]{.greek-omitted} [χιλιαρχαις]{.greek-added} και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης [τω]{.greek-omitted} [τωι]{.greek-added} [ηρωδη]{.greek-omitted} [ηρωδηι]{.greek-added} και τοις συνανακειμενοις ειπεν ο βασιλευς [τω]{.greek-omitted} [τωι]{.greek-added} [κορασιω]{.greek-omitted} [κορασιωι]{.greek-added} αιτησον με [και]{.greek-added} [δωσω]{.greek-added} [σοι]{.greek-added} ο εαν θελης [και]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted}[6:22]{.aside}

και ωμοσεν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} οτι ο εαν [αιτησηι]{.greek-added} με [αιτησης]{.greek-omitted} δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε ειπεν την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα [ητησατο]{.greek-omitted} [ηιτησατο]{.greek-added} λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν [αυτην]{.greek-omitted} [αθετησαι]{.greek-omitted}[6:26]{.aside}

[και]{.greek-omitted} [περιλυπος]{.greek-omitted} [γενομενος]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [δια]{.greek-omitted} [τους]{.greek-omitted} [ορκους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [συνανακειμενους]{.greek-omitted} [ουκ]{.greek-omitted} [ηθελησεν]{.greek-omitted} αυτην αθετησαι[6:26 | instance no. 2]{.aside}

και ευθεως [αποστειλας]{.greek-omitted} ο βασιλευς [αποστειλας]{.greek-added} σπεκουλατορα [απεκεφαλισεν]{.greek-added} [επεταξεν]{.greek-omitted} [ενεχθηναι]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [αυτου]{.greek-omitted} [αυτον]{.greek-added} [εν]{.greek-added} [τηι]{.greek-added} [φυλακηι]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν αυτην [τω]{.greek-omitted} [τωι]{.greek-added} [κορασιω]{.greek-omitted} [κορασιωι]{.greek-added} και το κορασιον εδωκεν αυτην [τη]{.greek-omitted} [τηι]{.greek-added} [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και [ηραν]{.greek-omitted} [ηιραν]{.greek-added} το πτωμα αυτου και εθηκαν αυτο εν [μνημειω]{.greek-omitted} [μνημειωι]{.greek-added}[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και αναπαυεσθε ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και [απηλθον]{.greek-omitted} [απηλθαν]{.greek-added} εις ερημον τοπον [τω]{.greek-omitted} [τωι]{.greek-added} [πλοιω]{.greek-omitted} [πλοιωι]{.greek-added} κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ειδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο [αυτους]{.greek-added} διδασκειν [αυτους]{.greek-omitted} πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες [αυτω]{.greek-omitted} οι μαθηται αυτου λεγουσιν [αυτωι]{.greek-added} οτι ερημος εστιν ο τοπος και [η]{.greek-added} [ωρα]{.greek-added} ηδη [ωρα]{.greek-omitted} πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις [φαγειν]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [απελθοντες]{.greek-omitted} [αγορασωμεν]{.greek-omitted} [δηναριων]{.greek-omitted} [διακοσιων]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [δωμεν]{.greek-omitted} [αυτοις]{.greek-omitted} [φαγειν]{.greek-omitted}[6:37]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [δοτε]{.greek-omitted} [αυτοις]{.greek-omitted} [υμεις]{.greek-omitted} φαγειν και λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} απελθοντες αγορασωμεν δηναριων διακοσιων αρτους και δωμεν αυτοις φαγειν[6:37 | instance no. 2]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και γνοντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι [τω]{.greek-omitted} [τωι]{.greek-added} [χλωρω]{.greek-omitted} [χλωρωι]{.greek-added} [χορτω]{.greek-omitted} [χορτωι]{.greek-added}[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παρατιθωσιν]{.greek-added} αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς βηθσαιδαν εως αυτος απολυση τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον [μεσον]{.greek-added} [εν]{.greek-omitted} [μεσω]{.greek-omitted} της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν [τω]{.greek-omitted} [τωι]{.greek-added} ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν [φαντασμα]{.greek-omitted} [ειναι]{.greek-omitted} [και]{.greek-omitted} [ανεκραξαν]{.greek-omitted}[6:49]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [περιπατουντα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [εδοξαν]{.greek-omitted} φαντασμα ειναι και ανεκραξαν[6:49 | instance no. 2]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ αυτων η καρδια [πεπωρωμενη]{.greek-omitted} [πεπωρρωμενη]{.greek-added}[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γεννισαρετ]{.greek-added} και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων [εκ]{.greek-omitted} [απο]{.greek-added} του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη [πυγμη]{.greek-omitted} [πυγμηι]{.greek-added} νιψωνται τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και [απο]{.greek-omitted} [απ]{.greek-added} αγορας εαν μη βαπτισωνται ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [χαλκιων]{.greek-omitted} [και]{.greek-omitted} [κλινων]{.greek-omitted}[7:4]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [αγορας]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [βαπτισωνται]{.greek-omitted} [ουκ]{.greek-omitted} [εσθιουσιν]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [πολλα]{.greek-omitted} [εστιν]{.greek-omitted} [α]{.greek-omitted} [παρελαβον]{.greek-omitted} [κρατειν]{.greek-omitted} [βαπτισμους]{.greek-omitted} ποτηριων και ξεστων και [χαλκιων]{.greek-omitted} [χαλκειων]{.greek-added} και κλινων[7:4 | instance no. 2]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την παραδοσιν των πρεσβυτερων αλλα ανιπτοις χερσιν εσθιουσιν [τον]{.greek-omitted} αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} [θανατω]{.greek-omitted} [θανατωι]{.greek-added} τελευτατω[7:10]{.aside}

υμεις δε λεγετε [[ο]{.unclear}]{.greek-added} [εαν]{.corr} ειπη [ανθρωπος]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [πατρι]{.greek-abbr} η [τη]{.greek-omitted} [τηι]{.greek-added} [μητρι]{.greek-abbr} [αυτου]{.greek-added} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι [τω]{.greek-omitted} [τωι]{.greek-added} [πατρι]{.greek-abbr} αυτου η [τη]{.greek-omitted} [τηι]{.greek-added} [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} [τη]{.greek-omitted} [τηι]{.greek-added} παραδοσει υμων [η]{.greek-omitted} [ηι]{.greek-added} παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα [κοινουντα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[7:15]{.aside}

[ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [εξωθεν]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εισπορευομενον]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [εκπορευομενα]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [εκεινα]{.greek-omitted} [εστιν]{.greek-omitted} [τα]{.greek-omitted} κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15 | instance no. 2]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα [εκπορευεται]{.greek-omitted} [πορευεται]{.greek-added} καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι [δολος]{.greek-omitted} [δολοι]{.greek-added} [ασελγεια]{.greek-omitted} [ασελγειαι]{.greek-added} οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις [οικιαν]{.greek-omitted} [οικον]{.greek-added} ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια [εσθιει]{.greek-added} υποκατω της τραπεζης [εσθιει]{.greek-omitted} απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} την χειρα[7:32]{.aside}

και [απολαβομενος]{.greek-omitted} [επιλαβομενος]{.greek-added} αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις παμπολλου οχλου οντος και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους [νηστεις]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [αυτων]{.greek-omitted} [εκλυθησονται]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [τινες]{.greek-omitted} [γαρ]{.greek-omitted} [αυτων]{.greek-omitted} [μακροθεν]{.greek-omitted} [ηκουσιν]{.greek-omitted}[8:3]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [απολυσω]{.greek-omitted} [αυτους]{.greek-omitted} νηστεις εις οικον αυτων εκλυθησονται εν [τη]{.greek-omitted} [τηι]{.greek-added} [οδω]{.greek-omitted} [οδωι]{.greek-added} τινες γαρ αυτων [απο]{.greek-added} μακροθεν ηκουσιν[8:3 | instance no. 2]{.aside}

και απεκριθησαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε χορτασαι αρτων επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [οχλω]{.greek-omitted} [οχλωι]{.greek-added} αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν [τω]{.greek-omitted} [τωι]{.greek-added} [οχλω]{.greek-omitted} [οχλωι]{.greek-added}[8:6]{.aside}

και ειχον [και]{.greek-added} ιχθυδια ολιγα και [ταυτα]{.greek-added} ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παραθειναι και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν [παντες]{.greek-added} και [ηραν]{.greek-omitted} [ηιραν]{.greek-added} περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες [ως]{.greek-omitted} [ωσει]{.greek-added} τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη [δαλμανουθα]{.greek-omitted} [μαλδανουθα]{.greek-added}[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας [τω]{.greek-omitted} [τωι]{.greek-added} [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται [τη]{.greek-omitted} [τηι]{.greek-added} [γενεα]{.greek-omitted} [γενεαι]{.greek-added} [ταυτη]{.greek-omitted} [ταυτηι]{.greek-added} σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν [τω]{.greek-omitted} [τωι]{.greek-added} [πλοιω]{.greek-omitted} [πλοιωι]{.greek-added}[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε ετι [πεπωρωμενην]{.greek-omitted} [πεπωρρωμενην]{.greek-added} εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους πληρεις κλασματων [ηρατε]{.greek-omitted} [ηιρατε]{.greek-added} λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων [ηρατε]{.greek-omitted} [ηιρατε]{.greek-added} οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις [ουπω]{.greek-added} [πως]{.greek-omitted} [ου]{.greek-omitted} συνιετε[8:21]{.aside}

και ερχεται εις βηθσαιδαν και φερουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας [αυτω]{.greek-omitted} [αυτωι]{.greek-added} επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και αποκατεσταθη και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις [τον]{.greek-omitted} οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν [τη]{.greek-omitted} [τηι]{.greek-added} [κωμη]{.greek-omitted} [κωμηι]{.greek-added}[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν [τη]{.greek-omitted} [τηι]{.greek-added} [οδω]{.greek-omitted} [οδωι]{.greek-added} επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην και αλλοι [ηλιαν]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [ενα]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted}[8:28]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [απεκριθησαν]{.greek-omitted} [ιωαννην]{.greek-omitted} [τον]{.greek-omitted} [βαπτιστην]{.greek-omitted} [και]{.greek-omitted} [αλλοι]{.greek-omitted} ηλιαν αλλοι δε ενα των προφητων[8:28 | instance no. 2]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και [των]{.greek-omitted} αρχιερεων και [των]{.greek-omitted} γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και [παρρησια]{.greek-omitted} [παρρησιαι]{.greek-added} τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[8:32]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [πετρω]{.greek-omitted} [πετρωι]{.greek-added} λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [ος]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελει οπισω μου [ακολουθειν]{.greek-omitted} [ελθειν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[8:34]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσηι]{.greek-added} την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου ουτος σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} εαν κερδηση τον κοσμον ολον και [ζημιωθη]{.greek-omitted} [ζημιωθηι]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν [τη]{.greek-omitted} [τηι]{.greek-added} [γενεα]{.greek-omitted} [γενεαι]{.greek-added} [ταυτη]{.greek-omitted} [ταυτηι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} μοιχαλιδι και [αμαρτωλω]{.greek-omitted} [αμαρτωλωι]{.greek-added} και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν [ελθη]{.greek-omitted} [ελθηι]{.greek-added} εν [τη]{.greek-omitted} [τηι]{.greek-added} [δοξη]{.greek-omitted} [δοξηι]{.greek-added} του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [εισιν]{.greek-omitted} [τινες]{.greek-omitted} [των]{.greek-omitted} [ωδε]{.greek-omitted} [εστηκοτων]{.greek-omitted} [οιτινες]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [γευσωνται]{.greek-omitted} [θανατου]{.greek-omitted} [εως]{.greek-omitted} [αν]{.greek-omitted} [ιδωσιν]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εληλυθυιαν]{.greek-omitted} [εν]{.greek-omitted} [δυναμει]{.greek-omitted}[9:1]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1 | instance no. 2]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν [ως]{.greek-omitted} [ωσει]{.greek-added} χιων οια [γναφευς]{.greek-omitted} [κναφευς]{.greek-added} επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωσει]{.greek-added} και ησαν συλλαλουντες [τω]{.greek-omitted} [τωι]{.greek-added} [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει [τω]{.greek-omitted} [τωι]{.greek-added} [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυσηι]{.greek-added} μιαν και [ηλια]{.greek-omitted} [ηλιαι]{.greek-added} μιαν[9:5]{.aside}

ου γαρ [ηδει]{.greek-omitted} [ηιδει]{.greek-added} τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα αυτοις και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι διηγησωνται α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων [αναστη]{.greek-omitted} [αναστηι]{.greek-added}[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον [αποκα]{.greek-added} [αποκαθιστα]{.greek-omitted} [παντα]{.greek-omitted} [και]{.greek-omitted} [πως]{.greek-omitted} [γεγραπται]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ινα]{.greek-omitted} [πολλα]{.greek-omitted} [παθη]{.greek-omitted} [και]{.greek-omitted} [εξουδενωθη]{.greek-omitted}[9:12]{.aside}

[θιστα]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ηλιας]{.greek-omitted} [μεν]{.greek-omitted} [ελθων]{.greek-omitted} [πρωτον]{.greek-omitted} [αποκαθιστα]{.greek-omitted} παντα [καθως]{.greek-added} [και]{.greek-omitted} [πως]{.greek-omitted} γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και [εξουδενωθη]{.greek-omitted} [εξουδενωθηι]{.greek-added}[9:12 | instance no. 2]{.aside}

αλλα λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν [εν]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ειδον]{.greek-added} οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου [αν]{.greek-omitted} [εαν]{.greek-added} αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [αυτω]{.greek-omitted} [αυτοις]{.greek-added} λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδ[ω]{.unclear}ν [[ιδον]{.corr}]{.greek-added} αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα ινα [απολεση]{.greek-omitted} [απολεσηι]{.greek-added} αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} το ει δυνασαι πιστευσαι [παντα]{.greek-omitted} [παν]{.greek-added} [δυνατα]{.greek-omitted} [τω]{.greek-omitted} [πιστευοντι]{.greek-omitted}[9:23]{.aside}

[τα]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [το]{.greek-omitted} [ει]{.greek-omitted} [δυνασαι]{.greek-omitted} [πιστευσαι]{.greek-omitted} [παντα]{.greek-omitted} δυνατα [τω]{.greek-omitted} [τωι]{.greek-added} πιστευοντι[9:23 | instance no. 2]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} βοηθει μου [τη]{.greek-omitted} [τηι]{.greek-added} [απιστια]{.greek-omitted} [απιστιαι]{.greek-added}[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [πνευματι]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [ακαθαρτω]{.greek-omitted} [ακαθαρτωι]{.greek-added} λεγων [αυτω]{.greek-omitted} [αυτωι]{.greek-added} το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον εξηλθεν και [εγενετο]{.greek-omitted} [εγινετο]{.greek-added} ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν [δια]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει μη εν [προσευχη]{.greek-omitted} [προσευχηι]{.greek-added} και [νηστεια]{.greek-omitted} [νηστειαι]{.greek-added}[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις [τη]{.greek-omitted} [τηι]{.greek-added} [τριτη]{.greek-omitted} [τριτηι]{.greek-added} [ημερα]{.greek-omitted} [ημεραι]{.greek-added} αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις καπερναουμ και εν [τη]{.greek-omitted} [τηι]{.greek-added} [οικια]{.greek-omitted} [οικιαι]{.greek-added} γενομενος επηρωτα αυτους τι εν [τη]{.greek-omitted} [τηι]{.greek-added} [οδω]{.greek-omitted} [οδωι]{.greek-added} προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ [διελεχθησαν]{.greek-omitted} [διειλεχθησαν]{.greek-added} εν [τη]{.greek-omitted} [τηι]{.greek-added} [οδω]{.greek-omitted} [οδωι]{.greek-added} τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους [δω]{.greek-added} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [θελει]{.greek-omitted} [πρωτος]{.greek-omitted} [ειναι]{.greek-omitted} [εσται]{.greek-omitted} [παντων]{.greek-omitted} [εσχατος]{.greek-omitted} [και]{.greek-omitted} [παντων]{.greek-omitted} [διακονος]{.greek-omitted}[9:35]{.aside}

[και]{.greek-omitted} [καθισας]{.greek-omitted} [εφωνησεν]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [δεκα]{.greek-added} και λεγει αυτοις ει τις θελει πρωτος ειναι εσται παντων εσχατος και παντων διακονος[9:35 | instance no. 2]{.aside}

και λαβων παιδιον εστησεν αυτο εν [μεσω]{.greek-omitted} [μεσωι]{.greek-added} αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των [[παιδι]{.unclear}ων]{.greek-added} [[τουτ]{.unclear}ων]{.greek-added} [τοιουτων]{.corr} [παιδιων]{.corr} δεξηται επι [τω]{.greek-omitted} [τωι]{.greek-added} ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ιωαννης λεγων διδασκαλε ειδομεν τινα [τω]{.greek-omitted} [τωι]{.greek-added} ονοματι σου [εκβαλλοντα]{.greek-omitted} [εκβαλοντα]{.greek-added} δαιμονια ος ουκ ακολουθει ημιν [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι [τω]{.greek-omitted} [τωι]{.greek-added} ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστι]{.greek-added} [καθ]{.greek-added} [ημων]{.greek-added} [υπερ]{.greek-added} [ημων]{.greek-added} εστιν [καθ]{.greek-omitted} [υμων]{.greek-omitted} [υπερ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted}[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτισηι]{.greek-added} υμας ποτηριον υδατος [ον]{.greek-added} [εν]{.corr} ονοματι [μου]{.greek-omitted} οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος εαν [σκανδαλιση]{.greek-omitted} [σκανδαλισηι]{.greek-added} ενα των μικρων των πιστευοντων εις εμε καλον εστιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} μαλλον ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιζηι]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} [κυλλον]{.greek-omitted} [κυλον]{.greek-added} εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου [σκανδαλιζη]{.greek-omitted} [σκανδαλιζηι]{.greek-added} σε αποκοψον αυτον καλον [γαρ]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν [σε]{.greek-added} εις την ζωην χωλον η τους δυο [πο]{.greek-added} [ποδας]{.greek-omitted} [εχοντα]{.greek-omitted} [βληθηναι]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γεενναν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [το]{.greek-omitted} [ασβεστον]{.greek-omitted}[9:45]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [ο]{.greek-omitted} [πους]{.greek-omitted} [σου]{.greek-omitted} [σκανδαλιζη]{.greek-omitted} [σε]{.greek-omitted} [αποκοψον]{.greek-omitted} [αυτον]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [σοι]{.greek-omitted} [εισελθειν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ζωην]{.greek-omitted} [χωλον]{.greek-omitted} [η]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ποδας]{.greek-omitted} [δας]{.greek-added} εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45 | instance no. 2]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου [σκανδαλιζη]{.greek-omitted} [σκανδαλιζηι]{.greek-added} σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας δια του περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν [τη]{.greek-omitted} [τηι]{.greek-added} [οικια]{.greek-omitted} [οικιαι]{.greek-added} [παλιν]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted}[10:10]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} παλιν οι μαθηται αυτου περι του αυτου επηρωτησαν αυτον[10:10 | instance no. 2]{.aside}

και λεγει αυτοις ος εαν [απολυση]{.greek-omitted} [απολυσηι]{.greek-added} την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη [αλλω]{.greek-omitted} [αλλωι]{.greek-added} μοιχαται[10:12]{.aside}

και προσεφερον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ευλογησεν]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} [πλουσιος]{.greek-added} προσδραμων [εις]{.greek-omitted} και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη [μοιχευσης]{.greek-omitted} [μοιχευσηις]{.greek-added} μη [φονευσης]{.greek-omitted} [φονευσηις]{.greek-added} μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} ταυτα παντα εφυλαξαμην εκ νεοτητος μου [τι]{.greek-added} [ετι]{.greek-added} [υστερω]{.greek-added}[10:20]{.aside}

ο δε [ιησους]{.greek-omitted} εμβλεψας [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ηγαπησεν αυτον και ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν [σοι]{.greek-omitted} [σε]{.greek-added} υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και δευρο ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι [τω]{.greek-omitted} [τωι]{.greek-added} [λογω]{.greek-omitted} [λογωι]{.greek-added} [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος [ην]{.greek-omitted} [γαρ]{.greek-omitted} [εχων]{.greek-omitted} [κτηματα]{.greek-omitted} [πολλα]{.greek-omitted}[10:22]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [στυγνασας]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [λογω]{.greek-omitted} [απηλθεν]{.greek-omitted} [λυπουμενος]{.greek-omitted} ην γαρ εχων κτηματα πολλα[10:22 | instance no. 2]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες [εισελευσονται]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} [εισελευσονται]{.greek-omitted}[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις [τεκνα]{.greek-omitted} πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [θεω]{.greek-omitted} [τωι]{.greek-added} [[θωι]{.greek-abbr}]{.greek-added} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν [τω]{.greek-omitted} [τωι]{.greek-added} [καιρω]{.greek-omitted} [καιρωι]{.greek-added} [τουτω]{.greek-omitted} [τουτωι]{.greek-added} οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν [τω]{.greek-omitted} [τωι]{.greek-added} αιωνι [τω]{.greek-omitted} [τωι]{.greek-added} [ερχομενω]{.greek-omitted} [ερχομενωι]{.greek-added} ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν [τη]{.greek-omitted} [τηι]{.greek-added} [οδω]{.greek-omitted} [οδωι]{.greek-added} αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα [αυτω]{.greek-omitted} [συμβαινειν]{.greek-omitted}[10:32]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [αναβαινοντες]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [προαγων]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εθαμβουντο]{.greek-omitted} [και]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} [παραλαβων]{.greek-omitted} [παλιν]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγειν]{.greek-omitted} [τα]{.greek-omitted} [μελλοντα]{.greek-omitted} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} συμβαινειν[10:32 | instance no. 2]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον [θανατω]{.greek-omitted} [θανατωι]{.greek-added} και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και εμπαιξουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και μαστιγωσουσιν αυτον και εμπτυσουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και αποκτενουσιν αυτον και [τη]{.greek-omitted} [τηι]{.greek-added} [τριτη]{.greek-omitted} [τριτηι]{.greek-added} [ημερα]{.greek-omitted} [ημεραι]{.greek-added} αναστησεται[10:34]{.aside}

και προσπορευονται [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν [ινα]{.greek-omitted} ο εαν αιτησωμεν ποιησης ημιν[10:35]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτοις]{.greek-omitted} τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν [τη]{.greek-omitted} [τηι]{.greek-added} [δοξη]{.greek-omitted} [δοξηι]{.greek-added} σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε [ειπον]{.greek-omitted} [λεγουσιν]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι [δεκα]{.greek-omitted} [δωδεκα]{.greek-added} ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη υμων γενεσθαι πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [ο]{.greek-added} [υιος]{.greek-abbr} τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων [αυτω]{.greek-omitted} [αυτον]{.greek-added} πολλοι ινα [σιωπηση]{.greek-omitted} [σιωπησηι]{.greek-added} ο δε πολλω μαλλον εκραζεν [υιε]{.greek-abbr} [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες [αυτω]{.greek-omitted} [αυτωι]{.greek-added} θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} ο [ιησους]{.greek-abbr} [λεγει]{.greek-added} [αυτωι]{.greek-added} τι [σοι]{.greek-added} θελεις ποιησω [σοι]{.greek-omitted} ο δε τυφλος ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει [τω]{.greek-omitted} [τωι]{.greek-added} [ιησου]{.greek-abbr} εν [τη]{.greek-omitted} [τηι]{.greek-added} [οδω]{.greek-omitted} [οδωι]{.greek-added}[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις ιερουσαλημ εις [βηθσφαγη]{.greek-omitted} [βιθσφαγη]{.greek-added} και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον [ουπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκε]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν [ειπη]{.greek-omitted} [τι]{.greek-omitted} [ποιειτε]{.greek-omitted} [τουτο]{.greek-omitted} [ειπατε]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [αυτου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχει]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [αυτον]{.greek-omitted} [αποστελλει]{.greek-omitted} [ωδε]{.greek-omitted}[11:3]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [τις]{.greek-omitted} [υμιν]{.greek-omitted} [ειπη]{.greek-omitted} [ειπηι]{.greek-added} τι ποιειτε [τουτο]{.greek-omitted} [τουτωι]{.greek-added} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3 | instance no. 2]{.aside}

απηλθον δε και ευρον [τον]{.greek-added} πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον [επ]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [εν]{.greek-added} [τηι]{.greek-added} [οδωι]{.greek-added} [και]{.greek-added} αλλοι [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ των δενδρων και εστρωννυον [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [εν]{.greek-added} [τηι]{.greek-added} [οδωι]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

[και]{.greek-added} ευλογημενη η ερχομενη βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} [εν]{.greek-added} [ονοματι]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και [τη]{.greek-omitted} [τηι]{.greek-added} επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην [μιαν]{.greek-added} μακροθεν εχουσαν φυλλα ηλθεν ει αρα ευρησει τι εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} μηκετι εκ σου εις τον αιωνα μηδεις καρπον [φαγοι]{.greek-omitted} [φαγη]{.greek-added} και ηκουον οι [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted}[11:14]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} [μηκετι]{.greek-omitted} [εκ]{.greek-omitted} [σου]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [αιωνα]{.greek-omitted} [μηδεις]{.greek-omitted} [καρπον]{.greek-omitted} [φαγοι]{.greek-omitted} [και]{.greek-omitted} [ηκουον]{.greek-omitted} [οι]{.greek-omitted} μαθηται αυτου[11:14 | instance no. 2]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν [τω]{.greek-omitted} [τωι]{.greek-added} [ιερω]{.greek-omitted} [ιερωι]{.greek-added} και τας τραπεζας των κολλυβιστων και τας [καθεδρας]{.greek-omitted} [τραπεζας]{.greek-added} των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε [αυτον]{.greek-added} εποιησατε [αυτον]{.greek-omitted} σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ [αυτον]{.greek-omitted} οτι πας ο οχλος [εξεπλησσετο]{.greek-omitted} [εξεπλησσοντο]{.greek-added} επι [τη]{.greek-omitted} [τηι]{.greek-added} [διδαχη]{.greek-omitted} [διδαχηι]{.greek-added} αυτου[11:18]{.aside}

και [οτε]{.greek-omitted} [οταν]{.greek-added} οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη [τω]{.greek-omitted} [τωι]{.greek-added} ορει [τουτω]{.greek-omitted} [τουτωι]{.greek-added} αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν [τη]{.greek-omitted} [τηι]{.greek-added} [καρδια]{.greek-omitted} [καρδιαι]{.greek-added} αυτου αλλα πιστευση οτι α λεγει γινεται εσται [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο εαν [ειπη]{.greek-omitted} [ειπηι]{.greek-added}[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα [αν]{.greek-omitted} [εαν]{.greek-added} προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθε]{.greek-added} πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} αφησει τα [παραπτωματα]{.greek-omitted} [υμων]{.greek-omitted}[11:26]{.aside}

[ει]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [ουκ]{.greek-omitted} [αφιετε]{.greek-omitted} [ουδε]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [αφησει]{.greek-omitted} [τα]{.greek-omitted} παραπτωματα υμων[11:26 | instance no. 2]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν [τω]{.greek-omitted} [τωι]{.greek-added} [ιερω]{.greek-omitted} [ιερωι]{.greek-added} περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added} και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added}[11:27]{.aside}

και λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εν [ποια]{.greek-omitted} [ποιαι]{.greek-added} [εξουσια]{.greek-omitted} [εξουσιαι]{.greek-added} ταυτα ποιεις και τις σοι [εδωκε]{.greek-added} την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} ινα ταυτα ποιης[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτοις επερωτησω [καγω]{.greek-added} υμας [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω υμιν εν [ποια]{.greek-omitted} [ποιαι]{.greek-added} [εξουσια]{.greek-omitted} [εξουσιαι]{.greek-added} ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον απαντες γαρ ειχον τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν [ποια]{.greek-omitted} [ποιαι]{.greek-added} [εξουσια]{.greek-omitted} [εξουσιαι]{.greek-added} ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωικοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους [τω]{.greek-omitted} [τωι]{.greek-added} [καιρω]{.greek-omitted} [καιρωι]{.greek-added} δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον λιθοβολησαντες εκεφαλαιωσαν και απεστειλαν [ητιμωμενον]{.greek-omitted} [η]{.greek-added}[12:4]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-omitted} [απεστειλεν]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [αλλον]{.greek-omitted} [δουλον]{.greek-omitted} [κακεινον]{.greek-omitted} [λιθοβολησαντες]{.greek-omitted} [εκεφαλαιωσαν]{.greek-omitted} [και]{.greek-omitted} [απεστειλαν]{.greek-omitted} [ητιμωμενον]{.greek-omitted} [τιμωμενον]{.greek-added}[12:4 | instance no. 2]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} [και]{.greek-added} [κακεινον]{.greek-omitted} [εκεινον]{.greek-added} απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε [αποκτενοντες]{.greek-omitted} [αποκτεννοντες]{.greek-added}[12:5]{.aside}

ετι ουν ενα [υιον]{.greek-abbr} εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον [εσχατον]{.greek-added} προς αυτους [εσχατον]{.greek-omitted} λεγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις [ημων]{.greek-omitted} [υμων]{.greek-added}[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} [λογω]{.greek-omitted} [λογωι]{.greek-added}[12:13]{.aside}

οι δε ελθοντες λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} διδασκαλε οιδαμεν οτι αληθης ει και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [κηνσον]{.greek-omitted} καισαρι δουναι [κηνσον]{.greek-added} η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις τι με πειραζετε φερετε μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων [αυτη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [επιγραφη]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [καισαρος]{.greek-omitted}[12:16]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ηνεγκαν]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [τινος]{.greek-omitted} [η]{.greek-omitted} [εικων]{.greek-omitted} αυτη και η επιγραφη οι δε ειπον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} καισαρος[12:16 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} και εθαυμασαν επ [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα [τω]{.greek-omitted} [τωι]{.greek-added} [αδελφω]{.greek-omitted} [αδελφωι]{.greek-added} αυτου[12:19]{.aside}

επτα αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν [τη]{.greek-omitted} [τηι]{.greek-added} [ουν]{.greek-added} αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [ου]{.greek-omitted} δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν [τη]{.greek-omitted} [τηι]{.greek-added} [βιβλω]{.greek-omitted} [βιβλωι]{.greek-added} [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} επι [του]{.greek-omitted} [της]{.greek-added} βατου ως ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων εις των [γραμ]{.greek-added} [γραμματεων]{.greek-omitted} [ακουσας]{.greek-omitted} [αυτων]{.greek-omitted} [συζητουντων]{.greek-omitted} [ειδως]{.greek-omitted} [οτι]{.greek-omitted} [καλως]{.greek-omitted} [αυτοις]{.greek-omitted} [απεκριθη]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ποια]{.greek-omitted} [εστιν]{.greek-omitted} [πρωτη]{.greek-omitted} [παντων]{.greek-omitted} [εντολη]{.greek-omitted}[12:28]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [εις]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [ματεων]{.greek-added} ακουσας αυτων συζητουντων ειδως οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη παντων εντολη[12:28 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οτι πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολη]{.greek-added} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη [παντων]{.greek-added} εντολη[12:30]{.aside}

[και]{.greek-omitted} δευτερα [δε]{.greek-added} ομοια [αυτη]{.greek-omitted} [αὐτήι]{.greek-added} αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} διδασκων εν [τω]{.greek-omitted} [τωι]{.greek-added} [ιερω]{.greek-omitted} [ιερωι]{.greek-added} πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} [αγιω]{.greek-omitted} [αγιωι]{.greek-added} λεγει ο [κυριος]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [κυριω]{.greek-omitted} [[κωι]{.greek-abbr}]{.greek-added} μου καθου εκ δεξιων μου εως αν [θω]{.greek-omitted} [θωι]{.greek-added} τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου εστιν και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν [τη]{.greek-omitted} [τηι]{.greek-added} [διδαχη]{.greek-omitted} [διδαχηι]{.greek-added} αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει [μακρα]{.greek-omitted} [μακραι]{.greek-added} προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του [γαζοφυλακιου]{.greek-omitted} [γαζοφυλακιωι]{.greek-added} εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των βαλ[λ]{.unclear}οντων [[βαλοντων]{.corr}]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη [καταλυθη]{.greek-omitted} [καταλυθηι]{.greek-added}[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε [η]{.greek-added} [ημιν]{.greek-omitted} [ποτε]{.greek-omitted} [ταυτα]{.greek-omitted} [εσται]{.greek-omitted} [και]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [σημειον]{.greek-omitted} [οταν]{.greek-omitted} [μελλη]{.greek-omitted} [παντα]{.greek-omitted} [ταυτα]{.greek-omitted} [συντελεισθαι]{.greek-omitted}[13:4]{.aside}

[ειπε]{.greek-omitted} [ημιν]{.greek-omitted} [μιν]{.greek-added} ποτε ταυτα εσται και τι το σημειον οταν [μελλη]{.greek-omitted} [μελη]{.greek-added} [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας [πλανηση]{.greek-omitted} [πλανησηι]{.greek-added}[13:5]{.aside}

πολλοι γαρ ελευσονται επι [τω]{.greek-omitted} [τωι]{.greek-added} ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται [λ[ει]{.unclear}μοι]{.greek-added} [λιμοι]{.corr} και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων [δε]{.greek-added} και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη προμεριμνατε τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} μηδε μελετατε αλλ ο εαν δοθη υμιν εν [εκεινη]{.greek-omitted} [εκεινηι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} [ωρα]{.greek-omitted} [ωραι]{.greek-added} τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο αναγινωσκων [νοειτω]{.greek-omitted} [τοτε]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ιουδαια]{.greek-omitted} [φευγετωσαν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορη]{.greek-omitted}[13:14]{.aside}

[οταν]{.greek-omitted} [δε]{.greek-omitted} [ιδητε]{.greek-omitted} [το]{.greek-omitted} [βδελυγμα]{.greek-omitted} [της]{.greek-omitted} [ερημωσεως]{.greek-omitted} [το]{.greek-omitted} [ρηθεν]{.greek-omitted} [υπο]{.greek-omitted} [δανιηλ]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [εστως]{.greek-omitted} [οπου]{.greek-omitted} [ου]{.greek-omitted} [δει]{.greek-omitted} [ο]{.greek-omitted} [αναγινωσκων]{.greek-omitted} νοειτω τοτε οι εν [τη]{.greek-omitted} [τηι]{.greek-added} [ιουδαια]{.greek-omitted} [ιουδαιαι]{.greek-added} φευγετωσαν εις τα ορη[13:14 | instance no. 2]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω [τι]{.greek-added} αραι [τι]{.greek-omitted} εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω [εις]{.greek-omitted} [τα]{.greek-omitted} οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} [η]{.greek-omitted} [και]{.greek-added} ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν [παντα]{.greek-omitted} [απαντα]{.greek-added}[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες [εσονται]{.greek-added} [εκ]{.greek-added} του [ουρανου]{.greek-abbr} [εσονται]{.greek-omitted} [εκπιπτοντες]{.greek-omitted} [πιπτοντες]{.greek-added} και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και [επισυναξει]{.greek-omitted} [επισυνα]{.greek-added} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted} [αυτου]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ανεμων]{.greek-omitted} [απ]{.greek-omitted} [ακρου]{.greek-omitted} [γης]{.greek-omitted} [εως]{.greek-omitted} [ακρου]{.greek-omitted} [ουρανου]{.greek-omitted}[13:27]{.aside}

[ξει]{.greek-added} [και]{.greek-omitted} [τοτε]{.greek-omitted} [αποστελει]{.greek-omitted} [τους]{.greek-omitted} [αγγελους]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [επισυναξει]{.greek-omitted} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου [της]{.greek-added} γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27 | instance no. 2]{.aside}

απο δε της συκης μαθετε την παραβολην οταν [αυτης]{.greek-omitted} [ηδη]{.greek-omitted} [ιδητε]{.greek-added} [οτι]{.greek-added} ο κλαδος [αυτης]{.greek-added} [γενηται]{.greek-added} απαλος [γενηται]{.greek-omitted} και εκφυη τα φυλλα [τοτε]{.greek-added} γινωσκετε οτι εγγυς το θερος [εστιν]{.greek-omitted}[13:28]{.aside}

ουτως και υμεις οταν [ιδητε]{.greek-added} ταυτα [ιδητε]{.greek-omitted} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν [οτι]{.greek-omitted} ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [των]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} ουδε ο υιος ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και [εκαστω]{.greek-omitted} [εκαστωι]{.greek-added} το εργον αυτου και [τω]{.greek-omitted} [τωι]{.greek-added} [θυρωρω]{.greek-omitted} [θυρωρωι]{.greek-added} ενετειλατο ινα [γρηγορη]{.greek-omitted} [γρηγορηι]{.greek-added}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν [δολω]{.greek-omitted} [δολωι]{.greek-added} κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν [τη]{.greek-omitted} [τηι]{.greek-added} [εορτη]{.greek-omitted} [εορτηι]{.greek-added} μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν [βηθανια]{.greek-omitted} [βηθανιαι]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

[και]{.greek-omitted} [οντος]{.greek-omitted} [αυτου]{.greek-omitted} εν [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [οικιαι]{.greek-added} σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3 | instance no. 2]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο [το]{.greek-added} [μυρον]{.greek-added} πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο [αυτη]{.greek-omitted} [αυτηι]{.greek-added}[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι [αυτη]{.greek-omitted} [αυτηι]{.greek-added} κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου [εαν]{.greek-omitted} [αν]{.greek-added} [κηρυχθη]{.greek-omitted} [κηρυχθηι]{.greek-added} το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και [τη]{.greek-omitted} [τηι]{.greek-added} [πρωτη]{.greek-omitted} [πρωτηι]{.greek-added} [ημερα]{.greek-omitted} [ημεραι]{.greek-added} των αζυμων οτε το πασχα εθυον λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οι μαθηται αυτου που θελεις απελθοντες [ετοιμασωμεν]{.greek-omitted} [ετοιμασομεν]{.greek-added} ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-omitted} [κεραμιον]{.greek-omitted} [υδατος]{.greek-omitted} [βασταζων]{.greek-omitted} [ακολουθησατε]{.greek-omitted} [αυτω]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [αποστελλει]{.greek-omitted} [δυο]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [απαντησει]{.greek-omitted} [υμιν]{.greek-omitted} [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[14:13 | instance no. 2]{.aside}

και οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθη ειπατε [τω]{.greek-omitted} [τωι]{.greek-added} [οικοδεσποτη]{.greek-omitted} [οικοδεσποτηι]{.greek-added} οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει [ανωγεον]{.greek-omitted} [αναγαιον]{.greek-added} μεγα εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν [αυτω]{.greek-omitted} εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε [τω]{.greek-omitted} [τωι]{.greek-added} [ανθρωπω]{.greek-omitted} [[ανωι]{.greek-abbr}]{.greek-added} [εκεινω]{.greek-omitted} [εκεινωι]{.greek-added} δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον [και]{.greek-added} ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν λαβετε [φαγετε]{.greek-omitted} τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο [πινω]{.greek-omitted} [πιω]{.greek-added} καινον [εν]{.greek-omitted} [τη]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[14:25]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [ουκετι]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [πιω]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [γενηματος]{.greek-omitted} [της]{.greek-omitted} [αμπελου]{.greek-omitted} [εως]{.greek-omitted} [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} [οταν]{.greek-omitted} [αυτο]{.greek-omitted} [πινω]{.greek-omitted} [καινον]{.greek-omitted} εν [τη]{.greek-omitted} [τηι]{.greek-added} [βασιλεια]{.greek-omitted} [βασιλειαι]{.greek-added} του [θεου]{.greek-abbr}[14:25 | instance no. 2]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε εν εμοι εν [τη]{.greek-omitted} [τηι]{.greek-added} νυκτι [ταυτη]{.greek-omitted} [ταυτηι]{.greek-added} οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα [της]{.greek-added} [ποιμνης]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν [τη]{.greek-omitted} [τηι]{.greek-added} νυκτι [ταυτη]{.greek-omitted} [ταυτηι]{.greek-added} πριν η δις αλεκτορα φωνησαι τρις [απαρνηση]{.greek-omitted} [απαρνησηι]{.greek-added} με[14:30]{.aside}

ο δε εκπερισσου [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν με [δεη]{.greek-omitted} [δεηι]{.greek-added} συναποθανειν σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσιμανι]{.greek-added} και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [αν]{.greek-added} [απελθων]{.greek-added} προσευξωμαι[14:32]{.aside}

και παραλαμβανει τον πετρον και [τον]{.greek-added} ιακωβον και [τον]{.greek-added} ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και [προσελθων]{.greek-omitted} [προελθων]{.greek-added} μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε [απ]{.greek-added} [εμου]{.greek-added} το ποτηριον [απ]{.greek-omitted} [εμου]{.greek-omitted} τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει [τω]{.greek-omitted} [τωι]{.greek-added} [πετρω]{.greek-omitted} [πετρωι]{.greek-added} σιμων καθευδεις ουκ ισχυσας [μιαν]{.greek-omitted} [ωραν]{.greek-omitted} [γρηγορησαι]{.greek-omitted}[14:37]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [και]{.greek-omitted} [ευρισκει]{.greek-omitted} [αυτους]{.greek-omitted} [καθευδοντας]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [σιμων]{.greek-omitted} [καθευδεις]{.greek-omitted} [ουκ]{.greek-omitted} [ισχυσας]{.greek-omitted} μιαν ωραν γρηγορησαι[14:37 | instance no. 2]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καταβαρυνομενοι]{.greek-added} και ουκ ηδεισαν τι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [αποκριθωσιν]{.greek-omitted} [αποκριθωσι]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων [παρα]{.greek-omitted} [απο]{.greek-added} των αρχιερεων και των γραμματεων και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων [αυτω]{.greek-omitted} [αυτωι]{.greek-added} λεγει [αυτω]{.greek-omitted} ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας αυτων [επ]{.greek-added} [αυτον]{.greek-added} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην [προς]{.greek-omitted} [υμας]{.greek-omitted} [μεθ]{.greek-added} [υμων]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ιερω]{.greek-omitted} [ιερωι]{.greek-added} διδασκων και ουκ [εκρατησατε]{.greek-omitted} [εκρατησα]{.greek-added} [με]{.greek-omitted} [αλλ]{.greek-omitted} [ινα]{.greek-omitted} [πληρωθωσιν]{.greek-omitted} [αι]{.greek-omitted} [γραφαι]{.greek-omitted}[14:49]{.aside}

[τε]{.greek-added} [καθ]{.greek-omitted} [ημεραν]{.greek-omitted} [ημην]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [διδασκων]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εκρατησατε]{.greek-omitted} με αλλ ινα πληρωθωσιν αι γραφαι[14:49 | instance no. 2]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και συνερχονται [αυτω]{.greek-omitted} [αυτωι]{.greek-added} παντες οι αρχιερεις και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added} και οι [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added}[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και [ουδε]{.greek-omitted} [ουδ]{.greek-added} ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινηι]{.greek-added} ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των [νεφε]{.greek-added} [νεφελων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[14:62]{.aside}

[λων]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [και]{.greek-omitted} [οψεσθε]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [καθημενον]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [και]{.greek-omitted} [ερχομενον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [νεφελων]{.greek-omitted} του [ουρανου]{.greek-abbr}[14:62 | instance no. 2]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} προφητευσον και οι υπηρεται ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν [τη]{.greek-omitted} [τηι]{.greek-added} [αυλη]{.greek-omitted} [αυληι]{.greek-added} κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα [αυτω]{.greek-omitted} [αυτωι]{.greek-added} λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο [αυτον]{.greek-added} λεγων ουκ οιδα ουδε επισταμαι τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστωσιν]{.greek-added} οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες ελεγον [τω]{.greek-omitted} [τωι]{.greek-added} [πετρω]{.greek-omitted} [πετρωι]{.greek-added} αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και ανεμνησθη ο πετρος το ρημα [ο]{.greek-omitted} [ως]{.greek-added} ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις [απαρνηση]{.greek-omitted} [απαρνησηι]{.greek-added} με τρις και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και [ο]{.greek-added} [ολον]{.greek-omitted} [το]{.greek-omitted} [συνεδριον]{.greek-omitted} [δησαντες]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [απηνεγκαν]{.greek-omitted} [και]{.greek-omitted} [παρεδωκαν]{.greek-omitted} [τω]{.greek-omitted} [πιλατω]{.greek-omitted}[15:1]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [πρωι]{.greek-omitted} [συμβουλιον]{.greek-omitted} [ποιησαντες]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [γραμματεων]{.greek-omitted} [και]{.greek-omitted} [ολον]{.greek-omitted} [λον]{.greek-added} το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν [τω]{.greek-omitted} [τωι]{.greek-added} [πιλατω]{.greek-omitted} [πιλατωι]{.greek-added}[15:1 | instance no. 2]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος [επηρωτα]{.greek-added} [παλιν]{.greek-omitted} [επηρωτησεν]{.greek-omitted} αυτον λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινηι]{.greek-added} ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ [ητουντο]{.greek-omitted} [ηιτουντο]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν [τη]{.greek-omitted} [τηι]{.greek-added} στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων [τινα]{.greek-added} θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος [παλιν]{.greek-added} αποκριθεις [παλιν]{.greek-omitted} ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [λεγοντες]{.greek-added} σταυρωσον αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσως]{.greek-added} [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος [τω]{.greek-omitted} [τωι]{.greek-added} [οχλω]{.greek-omitted} [οχλωι]{.greek-added} το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} φραγελλωσας ινα σταυρωθη[15:15]{.aside}

οι δε στρατιωται [απηγαγον]{.greek-omitted} [αυτον]{.greek-omitted} [εσω]{.greek-omitted} [της]{.greek-omitted} [αυλης]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [πραιτωριον]{.greek-omitted} [και]{.greek-omitted} [συγκαλουσιν]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [σπειραν]{.greek-omitted}[15:16]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [στρατιωται]{.greek-omitted} απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16 | instance no. 2]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην [καλαμω]{.greek-omitted} [καλαμωι]{.greek-added} και ενεπτυον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και τιθεντες τα γονατα προσεκυνουν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[15:19]{.aside}

και οτε ενεπαιξαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα σταυρωσωσιν αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και σταυρωσαντες αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε [τριτη]{.greek-added} ωρα [τριτη]{.greek-omitted} και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [σταυρουσιν]{.greek-omitted} [σταυρουσι]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν [ημε]{.greek-added} [ημεραις]{.greek-omitted} [οικοδομων]{.greek-omitted}[15:29]{.aside}

[ραις]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [παραπορευομενοι]{.greek-omitted} [εβλασφημουν]{.greek-omitted} [αυτον]{.greek-omitted} [κινουντες]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουα]{.greek-omitted} [ο]{.greek-omitted} [καταλυων]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τρισιν]{.greek-omitted} [ημεραις]{.greek-omitted} οικοδομων[15:29 | instance no. 2]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και οι συνεσταυρωμενοι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ωνειδιζον αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και [τη]{.greek-omitted} [τηι]{.greek-added} ωρα [τη]{.greek-omitted} [τηι]{.greek-added} [ενατη]{.greek-omitted} [εννατηι]{.greek-added} εβοησεν ο [ιησους]{.greek-abbr} [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} λεγων ελωι ελωι λιμα σαβαχθανι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον [οτι]{.greek-added} ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε [καλαμω]{.greek-omitted} [καλαμωι]{.greek-added} εποτιζεν αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν [τη]{.greek-omitted} [τηι]{.greek-added} [γαλιλαια]{.greek-omitted} [γαλιλαιαι]{.greek-added} ηκολουθουν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και [διηκο]{.greek-added} [διηκονουν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αλλαι]{.greek-omitted} [πολλαι]{.greek-omitted} [αι]{.greek-omitted} [συναναβασαι]{.greek-omitted} [αυτω]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted}[15:41]{.aside}

[νουν]{.greek-added} [αι]{.greek-omitted} [και]{.greek-omitted} [οτε]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [γαλιλαια]{.greek-omitted} [ηκολουθουν]{.greek-omitted} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [και]{.greek-omitted} [διηκονουν]{.greek-omitted} [αυτω]{.greek-omitted} και αλλαι πολλαι αι συναναβασαι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εις ιεροσολυμα[15:41 | instance no. 2]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα [τω]{.greek-omitted} [τωι]{.greek-added} ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισε]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} σινδονι και κατεθηκεν αυτον εν [μνημειω]{.greek-omitted} [μνημειωι]{.greek-added} ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε [λεγει]{.greek-omitted} [αυταις]{.greek-omitted} [μη]{.greek-omitted} [εκθαμβεισθε]{.greek-omitted} [ιησουν]{.greek-omitted} [ζητειτε]{.greek-omitted} [τον]{.greek-omitted} [ναζαρηνον]{.greek-omitted} [τον]{.greek-omitted} [εσταυρωμενον]{.greek-omitted} [ηγερθη]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [ωδε]{.greek-omitted} [ιδε]{.greek-omitted} [ο]{.greek-omitted} [τοπος]{.greek-omitted} [οπου]{.greek-omitted} [εθηκαν]{.greek-omitted} [αυτον]{.greek-omitted}[16:6]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον εσταυρωμενον ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6 | instance no. 2]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και [τω]{.greek-omitted} [τωι]{.greek-added} [πετρω]{.greek-omitted} [πετρωι]{.greek-added} οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη πρωτον [μαρια]{.greek-omitted} [μαριαι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} [μαγδαληνη]{.greek-omitted} [μαγδαληνηι]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν [ετερα]{.greek-omitted} [ετεραι]{.greek-added} [μορφη]{.greek-omitted} [μορφηι]{.greek-added} πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον [παση]{.greek-omitted} [πασηι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν [τω]{.greek-omitted} [τωι]{.greek-added} [ονο]{.greek-added} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [δαιμονια]{.greek-omitted} [εκβαλουσιν]{.greek-omitted} [γλωσσαις]{.greek-omitted} [λαλησουσιν]{.greek-omitted} [καιναις]{.greek-omitted}[16:17]{.aside}

[ματι]{.greek-added} [σημεια]{.greek-omitted} [δε]{.greek-omitted} [τοις]{.greek-omitted} [πιστευσασιν]{.greek-omitted} [ταυτα]{.greek-omitted} [παρακολουθησει]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17 | instance no. 2]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους [βλαψη]{.greek-omitted} [βλαψει]{.greek-added} επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

