---
title: "Collation of Byz^RP^ vs 30028 (28)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 28 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30028).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 28                                   	| λογος                              	|
| 28 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 28 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 28               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 28                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 28 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 28                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.corr} [υιου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου [εγω]{.corr} αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [[τ[ου]{.unclear}]{.corr}]{.greek-added} [κυριου]{.greek-abbr} ευθειας [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added} τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης [βαπτιζων]{.greek-omitted} εν τη ερημω [βαπτιζων]{.greek-added} και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται [παντες]{.greek-added} και εβαπτιζοντο [εις]{.greek-added} [τον]{.greek-added} [παντες]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιορδανη]{.greek-omitted} [ιορδανην]{.greek-added} [ποταμω]{.greek-omitted} υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

[ο]{.greek-added} [δε]{.greek-added} [ιωαννης]{.greek-added} ην [δε]{.greek-omitted} [ο]{.greek-omitted} [ιωαννης]{.greek-omitted} ενδεδυμενος τριχας [καμιλου]{.greek-added} [καμηλου]{.corr} και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και [μελι]{.greek-omitted} [μελει]{.greek-added} αγριον[1:6]{.aside}

και εκηρυσσεν λεγων [οτι]{.greek-added} [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος [κυψας]{.corr} λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος [δε]{.greek-omitted} [υμας]{.greek-added} βαπτισει [υμας]{.greek-omitted} εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη [εν]{.greek-added} [τω]{.greek-added} [ιορδανη]{.greek-added} υπο ιωαννου [εις]{.greek-omitted} [τον]{.greek-omitted} [ιορδανην]{.greek-omitted}[1:9]{.aside}

και ευθεως αναβαινων [απο]{.greek-omitted} [εκ]{.greek-added} του υδατος [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν [καταβαινον]{.greek-omitted} [καταβαινων]{.greek-added} επ αυτον[1:10]{.aside}

και φωνη [εγενετο]{.greek-omitted} εκ των [ουρανων]{.greek-abbr} [η[κ]{.unclear}ουσθη]{.greek-added} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν [ω]{.greek-omitted} [σοι]{.greek-added} [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλ[ει]{.unclear} εις την ερημον[1:12]{.aside}

και ην εκει [εν]{.corr} [τη]{.corr} [ερημω]{.corr} [επι]{.greek-added} ημερας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} [πειραζομενος]{.greek-omitted} [πιραζομενος]{.greek-added} υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον [της]{.corr} [βασιλειας]{.corr} του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και [ηγγικεν]{.greek-omitted} [ηγγεικεν]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} [μετανοειτε]{.greek-omitted} [μετανοειται]{.greek-added} και [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} εν τω ευαγγελιω[1:15]{.aside}

[περιπατων]{.greek-omitted} [παραγων]{.greek-added} δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [τον]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου [του]{.greek-omitted} [σιμωνος]{.greek-omitted} [βαλλοντας]{.greek-omitted} [αμφιβαλλοντας]{.greek-added} [αμφιβληστρον]{.greek-omitted} [εν]{.greek-omitted} [τα]{.greek-added} [δικτυ]{.greek-added} [[δικτυα]{.corr}]{.greek-added} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσαν]{.greek-added} ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα [αυτων]{.corr} [ηκο]{.greek-added} [ηκολουθησαν]{.greek-omitted} [λουθησαν]{.greek-added} αυτω[1:18]{.aside}

και προβας [εκειθεν]{.greek-omitted} [ολιγον]{.greek-omitted} [ολιγων]{.greek-added} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω [καταρτιζοντας]{.greek-omitted} [κατασκευαζοντας]{.greek-added} τα δικτυα[1:19]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} τοις σαββασιν [εισελθων]{.greek-omitted} [εδιδασκεν]{.greek-added} εις την συναγωγην [εδιδασκεν]{.greek-omitted}[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και ανεκραξεν[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαρηναι]{.greek-added} ηλθες απολεσαι ημας [οιδα]{.greek-omitted} [οι]{.greek-added} [δα]{.greek-added} σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και [εξελθε]{.greek-omitted} [εξελθαι]{.greek-added} εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και [κραξαν]{.greek-omitted} [κραζαν]{.greek-added} φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους λεγοντας τι εστιν τουτο τις [η]{.corr} διδαχη [η]{.corr} καινη αυτη [οτι]{.corr} κατ εξουσιαν και τοις [πνευμασιν]{.greek-abbr} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν δε η ακοη αυτου [ευθυς]{.greek-omitted} εις ολην την περιχωρον [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [του]{.greek-added} [ιορδανου]{.greek-added}[1:28]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο πυρεσσουσα και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος [ευθεως]{.greek-omitted} και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε [εδυ]{.greek-omitted} [εδυσεν]{.greek-added} ο ηλιος εφερον [παντες]{.greek-added} προς αυτον [παντας]{.greek-omitted} τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη [επισυνηγμενη]{.greek-omitted} [συνηγμενη]{.greek-added} ην προς [την]{.greek-omitted} [τας]{.greek-added} [θυραν]{.greek-omitted} [θυρας]{.greek-added}[1:33]{.aside}

και εθεραπευσεν πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα εξεβαλεν και ουκ ηφιεν λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ιδεσαν]{.greek-added} αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι [εννυχον]{.greek-omitted} [εννυχα]{.greek-added} λιαν αναστας εξηλθεν [και]{.corr} [απηλθεν]{.corr} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο [τε]{.greek-added} σιμων και οι μετ αυτου[1:36]{.aside}

και [ευροντες]{.greek-omitted} [ευρωντες]{.greek-added} αυτον λεγουσιν αυτω οτι παντες [ζητουσιν]{.greek-added} σε [ζητουσιν]{.greek-omitted}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων [αυτω]{.greek-omitted} [αυτον]{.greek-added} οτι εαν θελης [[κυριε]{.greek-abbr}]{.greek-added} [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [σπλαγχνισθεις]{.greek-omitted} [σπλαγχνησθεις]{.greek-added} [εκτεινας]{.greek-omitted} [εκτινας]{.greek-added} την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτω ορα [μηνι]{.greek-added} [μηδενι]{.corr} μηδεν ειπης αλλ υπαγε σεαυτον [δειξον]{.greek-omitted} [διξον]{.greek-added} τω ιερει και προσενεγκε περι του καθαρισμου σου α προσεταξεν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι [φανερως]{.greek-omitted} εις πολιν [φανερως]{.greek-added} εισελθειν αλλ εξω [εν]{.greek-omitted} [επι]{.greek-added} [ερημοις]{.greek-omitted} [εριμοις]{.greek-added} τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισελθων]{.greek-added} παλιν εις καπερναουμ δι ημερων [και]{.greek-omitted} ηκουσθη οτι εις οικον εστιν[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε [μηκετι]{.greek-omitted} [μηκετη]{.greek-added} χωρειν [μηδε]{.greek-omitted} τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και [ιδου]{.greek-added} [ανδρες]{.greek-added} ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι [προσεγγισαι]{.greek-omitted} [προσεγγεισαι]{.greek-added} αυτω δια τον οχλον απεστεγασαν την στεγην [αυτου]{.greek-added} οπου ην και [εξορυξαντες]{.greek-omitted} [εξωρυξαντες]{.greek-added} χαλωσιν τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

[και]{.greek-added} ιδων [δε]{.greek-omitted} ο [ιησους]{.greek-abbr} την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφιενται]{.greek-added} [σοι]{.greek-omitted} [σου]{.greek-added} αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και [ευθεως]{.greek-omitted} [επιγνους]{.greek-omitted} ο [ιησους]{.greek-abbr} [επιγνους]{.greek-added} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως [αυτοι]{.greek-omitted} διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφιενται]{.greek-added} σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρου]{.greek-added} και αρον [τον]{.greek-added} [κραβαττον]{.greek-added} σου [τον]{.greek-omitted} [κραββατον]{.greek-omitted} και [περιπατει]{.greek-omitted} [περιπατι]{.greek-added}[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι επι της γης αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω εγειραι [και]{.greek-omitted} αρον τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως [ο]{.greek-added} [παραλυτικως]{.greek-added} και αρας τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εξηλθεν [εναντιον]{.greek-omitted} [ενωπιον]{.greek-added} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added}[2:12]{.aside}

και εξηλθεν παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

[και]{.greek-omitted} παραγων [δε]{.greek-added} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [λευι]{.greek-omitted} [λευη]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθι]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου [και]{.greek-omitted} πολλοι τελωναι και αμαρτωλοι [συνανεκειντο]{.greek-omitted} [συνανεκιντο]{.greek-added} τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις [των]{.greek-added} [φαρησαιων]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} ιδοντες αυτον εσθιοντα μετα των τελωνων [και]{.corr} [αμαρτωλων]{.corr} [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει [αυτοις]{.greek-omitted} ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι των [φαρισαιων]{.greek-omitted} [φαρησαιων]{.greek-added} νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε [σοι]{.greek-omitted} μαθηται [σου]{.greek-added} ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων εστιν νηστευειν οσον χρονον [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} εχουσιν τον νυμφιον [μετ]{.greek-added} [αυτων]{.greek-added} ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν [απαρθη]{.greek-omitted} [αρθη]{.greek-added} απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [εκεινη]{.greek-added} [τη]{.greek-added} [ημεραις]{.greek-omitted} [ημερα]{.greek-added}[2:20]{.aside}

[και]{.greek-omitted} ουδεις [δε]{.greek-added} επιβλημα ρακους [αγναφου]{.greek-omitted} [ακναφου]{.greek-added} [επιρραπτει]{.greek-omitted} [επιραπτη]{.greek-added} επι ιματιω παλαιω ει δε μη [γε]{.greek-added} αιρει το πληρωμα [αυτου]{.greek-omitted} το καινον [απο]{.greek-added} του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος [ο]{.greek-omitted} [νεος]{.greek-omitted} τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον εις ασκους καινους [βλητεον]{.greek-omitted} [βληταιον]{.greek-added}[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις σαββασιν δια των σποριμων και [ηρξαντο]{.greek-omitted} οι μαθηται αυτου [ηρξαντο]{.greek-added} οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν [οι]{.greek-added} [μαθηται]{.greek-added} [σου]{.greek-added} [ο]{.greek-added} [ουκ]{.greek-added} [εξεστιν]{.greek-added} εν τοις σαββασιν [ο]{.greek-omitted} [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted}[2:24]{.aside}

και αυτος [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} [εν]{.greek-added} [ταις]{.greek-added} [γραφαις]{.greek-added} τι εποιησεν [δαυιδ]{.greek-abbr} οτε [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εσχεν και [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added} αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ [του]{.greek-added} αρχιερεως και τους αρτους της προθεσεως εφαγεν [ους]{.greek-omitted} [οις]{.greek-added} ουκ εξεστιν φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [αρχιερευσιν]{.greek-added} και εδωκεν και τοις συν αυτω ουσιν[2:26]{.aside}

και ελεγεν αυτοις [οτι]{.greek-added} το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην εχων την [χειρα]{.greek-omitted} [χηρα]{.greek-added}[3:1]{.aside}

και παρετηρουν αυτον ει τοις σαββασιν θεραπευσει αυτον ινα [κατηγορησωσιν]{.greek-omitted} [κατηγορησουσιν]{.greek-added} αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [την]{.greek-added} [χηρα]{.greek-added} [[χειρα]{.corr}]{.greek-added} [εχοντι]{.greek-added} εξηραμμενην [εχοντι]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις εξεστιν [εν]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι [μαλλον]{.greek-added} η [αποκτειναι]{.greek-omitted} [απολεσαι]{.greek-added} οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη πωρωσει της [κα]{.unclear}ρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου υγιης ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον [εποιουν]{.greek-omitted} [εδιδουν]{.greek-added} κατ αυτου οπως αυτον απολεσωσιν[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} μετα των μαθητων αυτου [προς]{.greek-omitted} [ανεχωρησεν]{.greek-added} [παρα]{.greek-added} την θαλασσαν και [πολυ]{.greek-omitted} [πολοι]{.greek-added} πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted} και [απο]{.greek-omitted} [της]{.greek-omitted} ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι [τυρον]{.greek-omitted} [τοιρον]{.greek-added} και σιδωνα πληθος πολυ ακουσαντες [οσα]{.greek-omitted} [α]{.greek-added} εποιει [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη θλιβωσιν αυτον [οι]{.greek-added} [οχλοι]{.greek-added}[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου αψωνται [και]{.greek-added} οσοι [ειχον]{.greek-omitted} [ηχον]{.greek-added} μαστιγας[3:10]{.aside}

και [τα]{.greek-omitted} [πνευματα]{.greek-abbr} [τα]{.greek-omitted} ακαθαρτα [οταν]{.greek-omitted} [οτε]{.greek-added} [αν]{.greek-added} [εθεωρουν]{.greek-added} αυτον [εθεωρει]{.greek-omitted} [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζων]{.greek-added} [λεγοντα]{.greek-omitted} [λεγοντες]{.greek-added} οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις το ορος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και εποιησεν [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} [ους]{.greek-added} [και]{.greek-added} [αποστολους]{.greek-added} [ονομασεν]{.greek-added} [[ωνομασεν]{.corr}]{.greek-added} ινα ωσιν [μετ]{.greek-omitted} [περι]{.greek-added} [αυτου]{.greek-omitted} [αυτον]{.greek-added} και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και [εξουσιαν]{.greek-added} εχειν [εξουσιαν]{.greek-omitted} θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και επεθηκεν τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του [ζε]{.greek-added} [ζεβεδαιου]{.greek-omitted} [βεδαιου]{.greek-added} και ιωαννην τον αδελφον [του]{.greek-omitted} [αυτου]{.greek-added} [ιακωβου]{.greek-omitted} και επεθηκεν αυτοις [ονοματα]{.greek-omitted} [ονομα]{.greek-added} βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη δυνασθαι αυτους [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις [οι]{.greek-omitted} απο ιεροσολυμων καταβαντες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται [σταθηναι]{.greek-omitted} η οικια εκεινη [σταθηναι]{.greek-added}[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

[αλλ]{.greek-added} ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου διαρπαση[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted} τοις υιοις των [ανθρωπων]{.greek-abbr} [τα]{.greek-added} [αμαρτηματα]{.greek-added} και [αι]{.greek-added} βλασφημιαι οσας αν [βλασφημησωσιν]{.greek-omitted} [βλασφημισωσιν]{.greek-added}[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημιση]{.greek-added} εις το [αγιον]{.greek-added} [πνευμα]{.greek-abbr} [το]{.greek-omitted} [αγιον]{.greek-omitted} ουκ εχει αφεσιν [εις]{.greek-omitted} [τον]{.greek-omitted} [αιωνα]{.greek-omitted} αλλ ενοχος εστιν αιωνιου [κρισεως]{.greek-omitted} [αμαρτηματος]{.greek-added}[3:29]{.aside}

οτι ελεγον [οτι]{.greek-added} [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

[και]{.greek-added} ερχονται [ουν]{.greek-omitted} οι αδελφοι και η [μητηρ]{.greek-abbr} αυτου και εξω [εστωτες]{.greek-omitted} [στηκοντες]{.greek-added} απεστειλαν προς αυτον [φωνουντες]{.greek-omitted} [καλουντες]{.greek-added} αυτον[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [ειπον]{.greek-omitted} [οχλος]{.greek-added} [ειπωντων]{.greek-added} δε [αυτω]{.greek-omitted} [αυτων]{.greek-added} ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω ζητουσιν σε[3:32]{.aside}

[και]{.greek-omitted} απεκριθη αυτοις [λεγων]{.greek-omitted} [και]{.greek-added} [λεγει]{.greek-added} τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος [τους]{.greek-added} κυκλω [τους]{.greek-omitted} περι αυτον καθημενους [λεγει]{.greek-omitted} [ιδε]{.greek-omitted} [ειπεν]{.greek-added} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη [μου]{.greek-omitted} και [μητηρ]{.greek-abbr} εστιν[3:35]{.aside}

### Chapter 4

[και]{.greek-omitted} παλιν [δε]{.greek-added} ηρξατο διδασκειν παρα την θαλασσαν και [συνηχθη]{.greek-omitted} [συναγεται]{.greek-added} προς αυτον οχλος [πολυς]{.greek-omitted} [πολλυς]{.greek-added} ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις [πολλα]{.greek-omitted} [λεγων]{.greek-added} και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

[ακουετε]{.greek-omitted} [ακουεται]{.greek-added} ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν τω [σπειρειν]{.greek-omitted} [σπιρειν]{.greek-added} [ο]{.greek-omitted} [α]{.greek-added} μεν επεσεν [παρα]{.greek-omitted} [επι]{.greek-added} την οδον και ηλθεν τα πετεινα και κατεφαγεν [αυτο]{.greek-omitted} [αυτα]{.greek-added}[4:4]{.aside}

[αλλο]{.greek-omitted} [αλλα]{.greek-added} δε επεσεν επι το πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξεβλαστησεν]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε [ανατειλαντος]{.greek-omitted} [ανατιλαντος]{.greek-added} εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και [αλλο]{.greek-omitted} [αλλα]{.greek-added} επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν [αυτο]{.greek-omitted} [αυτα]{.greek-added} και καρπον ουκ εδωκεν[4:7]{.aside}

και [αλλο]{.greek-omitted} [αλλα]{.greek-added} επεσεν [εις]{.greek-omitted} [επι]{.greek-added} την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [εἰς]{.greek-added} τριακοντα και [εν]{.greek-omitted} [εἰς]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [εἰς]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} [ηρωτησαν]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον οι [περι]{.greek-omitted} [μαθηται]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added} [συν]{.greek-omitted} [τοις]{.greek-omitted} [τις]{.greek-added} [η]{.greek-added} [δωδεκα]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [παραβολη]{.greek-added} [αυτη]{.greek-added}[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι [τα]{.greek-added} το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα [γινεται]{.greek-omitted} [λεγεται]{.greek-added}[4:11]{.aside}

ινα βλεποντες [μη]{.greek-added} βλεπωσιν και [μη]{.greek-omitted} [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} ακουοντες [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} μη συνιωσιν μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστραψωσιν]{.greek-added} και αφεθη αυτοις [τα]{.corr} [αμαρτηματα]{.corr}[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την [παραβολην]{.greek-omitted} [παρα]{.greek-added} [βολην]{.greek-added} ταυτην και πως πασας τας παραβολας [γνωσεσθε]{.greek-omitted} [γνωσεσθαι]{.greek-added}[4:13]{.aside}

ο [σπειρων]{.greek-omitted} [σπιρων]{.greek-added} τον λογον [σπειρει]{.greek-omitted} [σπιρει]{.greek-added}[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου [σπειρεται]{.greek-omitted} [σπιρεται]{.greek-added} ο λογος και οταν ακουσωσιν [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} ερχεται ο σατανας και [αιρει]{.greek-omitted} [ερει]{.greek-added} τον λογον τον εσπαρμενον [εις]{.greek-added} [αυτους]{.greek-added} [εν]{.greek-omitted} [ταις]{.greek-omitted} [καρδιαις]{.greek-omitted} [αυτων]{.greek-omitted}[4:15]{.aside}

και ουτοι εισιν [ομοιως]{.greek-omitted} οι επι τα πετρωδη [σπειρομενοι]{.greek-omitted} [σπιρομενοι]{.greek-added} οι οταν ακουσωσιν τον λογον [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} μετα χαρας λαμβανουσιν [αυτον]{.greek-omitted}[4:16]{.aside}

και ουκ εχουσιν ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης [θλιψεως]{.greek-omitted} [θληψεως]{.greek-added} η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και [ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} οι εις τας ακανθας [σπειρομενοι]{.greek-omitted} [σπιρομενοι]{.greek-added} [ουτοι]{.greek-added} [εισιν]{.greek-added} οι τον λογον [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added}[4:18]{.aside}

και αι μεριμναι του αιωνος [τουτου]{.greek-omitted} και η απατη του πλουτου [και]{.greek-omitted} [αι]{.greek-omitted} [περι]{.greek-omitted} [τα]{.greek-omitted} [λοιπα]{.greek-omitted} [επιθυμιαι]{.greek-omitted} [εισπορευομεναι]{.greek-omitted} [εισπορευομενα]{.greek-added} συμπνιγουσιν τον λογον και ακαρπος γινεται[4:19]{.aside}

και [ουτοι]{.greek-omitted} εισιν οι επι την [καλην]{.greek-added} γην [την]{.greek-omitted} [καλην]{.greek-omitted} σπαρεντες οιτινες ακουουσιν τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις [ιδετε]{.greek-added} μητι [ο]{.greek-omitted} λυχνος ερχεται ινα υπο τον μοδιον τεθη η [ινα]{.greek-added} υπο την κλινην ουχ ινα επι την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21]{.aside}

ου γαρ εστιν [τι]{.greek-omitted} κρυπτον [ει]{.greek-added} [ο]{.greek-omitted} [εαν]{.greek-omitted} μη [ινα]{.greek-added} φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} τι [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} εν ω μετρω [μετρειτε]{.greek-omitted} [μετριται]{.greek-added} [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} υμιν [και]{.greek-omitted} προστεθησεται [γαρ]{.greek-added} υμιν τοις ακουουσιν[4:24]{.aside}

ος [εχει]{.greek-added} γαρ [αν]{.greek-omitted} [εχη]{.greek-omitted} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν [ουτως]{.greek-omitted} [ουτος]{.greek-added} εστιν η βασιλεια του [θεου]{.greek-abbr} [ωσπερ]{.greek-added} [ως]{.greek-omitted} [εαν]{.greek-omitted} [ανθρωπος]{.greek-abbr} [βαλλει]{.greek-added} [βαλη]{.greek-omitted} [τον]{.greek-omitted} σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [νυκτα]{.greek-omitted} [εγηρεται]{.greek-added} [νυκτος]{.greek-added} και [ημεραν]{.greek-omitted} [ημερας]{.greek-added} και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και μηκυνηται ως ουκ οιδεν [αυτος]{.greek-omitted}[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα [πληρη]{.greek-omitted} [πληρης]{.greek-added} σιτον εν τω [σταχυι]{.greek-omitted} [σταχυει]{.greek-added}[4:28]{.aside}

οταν δε [παραδω]{.greek-omitted} [παραδοι]{.greek-added} ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν [τινι]{.greek-omitted} [πως]{.greek-added} [ομοιωσωμεν]{.greek-omitted} [ομοιωσω]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν [ποια]{.greek-omitted} [τινι]{.greek-added} [αυτην]{.greek-added} παραβολη [θωμεν]{.greek-added} [παραβαλωμεν]{.greek-omitted} [αυτην]{.greek-omitted}[4:30]{.aside}

ως κοκκον σιναπεως ος οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} επι [της]{.greek-omitted} [γης]{.greek-omitted} [την]{.greek-added} [γην]{.greek-added} [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων των σπερματων εστιν των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} αναβαινει και γινεται [μιζων]{.greek-added} παντων των λαχανων [μειζων]{.greek-omitted} και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [πετινα]{.greek-added} του [ουρανου]{.greek-abbr} [κατασκηνουν]{.greek-omitted} [κατασκινουν]{.greek-added}[4:32]{.aside}

και τοιαυταις παραβολαις [πολλαις]{.greek-omitted} ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [ελυεν]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και [αφεντες]{.greek-omitted} [αφιουσιν]{.greek-added} τον οχλον [και]{.greek-added} παραλαμβανουσιν αυτον ως ην εν τω πλοιω και [τα]{.greek-added} αλλα [τα]{.greek-added} [οντα]{.greek-added} [δε]{.greek-omitted} [πλοιαρια]{.greek-omitted} [ην]{.greek-omitted} μετ αυτου [πλοια]{.greek-added}[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λελαψ]{.greek-added} [μεγαλη]{.greek-added} [του]{.greek-added} ανεμου [μεγαλη]{.greek-omitted} [και]{.greek-added} τα [δε]{.greek-omitted} κυματα επεβαλλεν εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος [επι]{.greek-omitted} [εν]{.greek-added} τη πρυμνη επι [το]{.greek-omitted} προσκεφαλαιον καθευδων και [διεγειρουσιν]{.greek-omitted} [διεγειραντες]{.greek-added} αυτον [και]{.greek-omitted} λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελη]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

και [διεγερθεις]{.greek-omitted} [εγερθεις]{.greek-added} επετιμησεν τω ανεμω και [ειπεν]{.greek-omitted} τη θαλασση [ειπεν]{.greek-added} σιωπα [πεφιμωσο]{.greek-omitted} [πεφημωσον]{.greek-added} και εκοπασεν ο ανεμος και εγενετο [γαληνη]{.greek-omitted} [γαλινη]{.greek-added} μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι [δειλοι]{.greek-omitted} [εστε]{.greek-omitted} ουτως [πως]{.greek-omitted} [ουκ]{.greek-omitted} [εχετε]{.greek-omitted} [δηλοι]{.greek-added} [ουπω]{.greek-added} [εχεται]{.greek-added} [πιστιν]{.greek-omitted} [πιστην]{.greek-added}[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους [τι]{.greek-added} [τις]{.corr} αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα [υπακουουσιν]{.greek-omitted} αυτω [υπακουει]{.greek-added}[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γεργεσηνων]{.greek-added}[5:1]{.aside}

και [εξελθοντι]{.greek-omitted} [εξελθοντος]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} εκ του πλοιου ευθεως [απηντησεν]{.greek-omitted} [υπηντησεν]{.greek-added} αυτω εκ των [μνημειων]{.greek-omitted} [μνημιων]{.greek-added} [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

[ος]{.greek-omitted} [οστις]{.greek-added} την κατοικησιν ειχεν εν τοις μνημασιν και ουτε [αλυσεσιν]{.greek-omitted} [αλυσαισιν]{.greek-added} [ουκετι]{.greek-added} ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον [δησαι]{.greek-omitted} [δαμασαι]{.greek-added}[5:3]{.aside}

[δι]{.greek-added} [α[υ]{.unclear}]{.greek-added} [δια]{.corr} [το]{.corr} [αυτον]{.corr} [πολλακις]{.greek-omitted} [πολλας]{.greek-added} [πεδαις]{.greek-omitted} [παιδας]{.greek-added} και [αλυσεσιν]{.greek-omitted} [αλυσεις]{.greek-added} [δεδεσθαι]{.greek-omitted} [αις]{.greek-added} [εδησαν]{.greek-added} [αυτον]{.greek-added} [διεσπακεναι]{.greek-added} και [συντετριφ[―]{.gap}ναι]{.greek-added} [[συντετριφεναι]{.corr}]{.greek-added} [διεσπασθαι]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} [τας]{.greek-omitted} [αλυσεις]{.greek-omitted} και [τας]{.greek-omitted} [πεδας]{.greek-omitted} [συντετριφθαι]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [ουδις]{.greek-added} [ισχυσεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημιοις]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

[και]{.greek-added} ιδων [δε]{.greek-omitted} τον [ιησουν]{.greek-abbr} απο μακροθεν εδραμεν και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη ειπεν τι εμοι και σοι [ιησου]{.greek-abbr} [υιε]{.greek-abbr} του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

ελεγεν γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι [ονομα]{.greek-added} σοι [ονομα]{.greek-omitted} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον πολλα ινα μη αυτους [αποστειλη]{.greek-omitted} [αποστιλη]{.greek-added} εξω της χωρας[5:10]{.aside}

ην δε εκει [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων μεγαλη [προς]{.greek-added} [τω]{.greek-added} [ορι]{.greek-added} βοσκομενη[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρακαλεσαντες]{.greek-added} αυτον [ειπον]{.greek-added} [παντες]{.greek-omitted} [οι]{.greek-omitted} [δαιμονες]{.greek-omitted} [λεγοντες]{.greek-omitted} πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} και εξελθοντα τα πνευματα [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του [κρημνου]{.greek-omitted} [κριμνου]{.greek-added} εις την θαλασσαν ησαν [δε]{.greek-omitted} [γαρ]{.greek-added} ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

[και]{.greek-added} οι [δε]{.greek-omitted} βοσκοντες [τους]{.greek-omitted} [αυτους]{.greek-added} [χοιρους]{.greek-omitted} εφυγον και ανηγγειλαν εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι εστιν το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και θεωρουσιν τον δαιμονιζομενον καθημενον [και]{.greek-omitted} ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι [ιδοντες]{.greek-omitted} [ιδοτες]{.greek-added} πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο [δαιμονισθεις]{.greek-omitted} [δαιμονισθης]{.greek-added} ινα [η]{.greek-omitted} μετ αυτου [η]{.greek-added}[5:18]{.aside}

[και]{.greek-added} ο [δε]{.greek-omitted} [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και [αναγγειλον]{.greek-omitted} [διαγγειλον]{.greek-added} αυτοις οσα σοι ο [κυριος]{.greek-abbr} πεποιηκεν και ηλεησεν σε[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη [δεκαπολει]{.greek-omitted} [δεκαπολι]{.greek-added} οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες [εθαυμαζον]{.greek-omitted} [εθαυμαζων]{.greek-added}[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} παλιν εις το περαν συνηχθη οχλος [πολυς]{.greek-omitted} [πολλυς]{.greek-added} [επ]{.greek-omitted} [προς]{.greek-added} αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των [αρχισυναγωγων]{.greek-omitted} [αρχησυναγωγων]{.greek-added} ονοματι [ιαειρος]{.greek-omitted} [ιαιαρος]{.greek-added} και ιδων αυτον [πιπτει]{.greek-omitted} [πιπτι]{.greek-added} προς τους ποδας αυτου[5:22]{.aside}

και [παρεκαλει]{.greek-omitted} [παρακαλει]{.greek-added} αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων επιθης [αυτη]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [χειρα]{.greek-added} [οπως]{.greek-omitted} [επ]{.greek-added} [αυτην]{.greek-added} [ινα]{.greek-added} σωθη και ζησεται[5:23]{.aside}

και απηλθεν μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν [ρυσει]{.greek-omitted} [ρυσι]{.greek-added} αιματος [δωδεκα]{.greek-added} ετη [δωδεκα]{.greek-omitted}[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα [παντα]{.greek-added} τα [παρ]{.greek-omitted} [αυτης]{.greek-omitted} [εαυτης]{.greek-added} [παντα]{.greek-omitted} και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα [εν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [εις]{.greek-added} [τον]{.greek-added} [οχλον]{.greek-added} οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

ελεγεν γαρ [οτι]{.greek-omitted} καν των ιματιων αυτου αψωμαι [σωθησομαι]{.greek-omitted} [σωθησωμαι]{.greek-added}[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι [ιαται]{.greek-omitted} [ιαθη]{.greek-added} απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και [ελεγον]{.greek-omitted} [ελεγωσαν]{.greek-added} αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο [ποιησασαν]{.greek-omitted} [πεποιηκυιαν]{.greek-added}[5:32]{.aside}

η δε γυνη [φοβηθεισα]{.greek-omitted} [φοβηθησα]{.greek-added} και τρεμουσα [ειδυια]{.greek-omitted} [διο]{.greek-added} [πεποιηκη]{.greek-added} [λαθρα]{.greek-added} [ιδουσα]{.greek-added} ο γεγονεν επ αυτη ηλθεν και προσεπεσεν αυτω και ειπεν αυτω πασαν την [αληθειαν]{.greek-omitted} [αιτιαν]{.greek-added}[5:33]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτη [θυγατερ]{.greek-omitted} [θυγατηρ]{.greek-added} η [πιστις]{.greek-omitted} [πιστης]{.greek-added} σου σεσωκεν σε υπαγε εις ειρηνην και [ισθι]{.greek-omitted} [ισθη]{.greek-added} υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου απεθανεν τι ετι [σκυλλεις]{.greek-omitted} [σκυλεις]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-omitted} [ευθεως]{.greek-omitted} ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω [μη]{.greek-omitted} [μι]{.greek-added} φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω [συνακολουθησαι]{.greek-omitted} [παρακολουθησαι]{.greek-added} ει [μι]{.greek-added} [μη]{.corr} πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} κλαιοντας και [αλα]{.greek-added} [αλαλαζοντας]{.greek-omitted} [λαζοντας]{.greek-added} πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και [τι]{.greek-added} [κλαιετε]{.greek-omitted} [κλαιεται]{.greek-added} [ουκ]{.greek-added} [απεθανεν]{.greek-added} το παιδιον [ουκ]{.greek-omitted} [απεθανεν]{.greek-omitted} αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} [του]{.greek-omitted} [της]{.greek-added} [παιδιου]{.greek-omitted} [παιδος]{.greek-added} και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον [ανακειμενον]{.greek-omitted} [κατακειμενον]{.greek-added}[5:40]{.aside}

και κρατησας της χειρος του παιδιου [λεγει]{.greek-omitted} [λεγε]{.greek-added} αυτη ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο εστιν μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστιλατο]{.greek-added} αυτοις πολλα ινα [μηδεις]{.greek-omitted} [μητις]{.greek-added} γνω τουτο και ειπεν δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την πατριδα αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και [οι]{.greek-added} πολλοι [ακουσαντες]{.greek-added} [ακουοντες]{.corr} εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η σοφια η [δοθεισα]{.greek-omitted} [δοθησα]{.greek-added} αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο τεκτων ο [υιος]{.greek-abbr} [μαριας]{.greek-omitted} [μαριαμ]{.greek-added} αδελφος δε ιακωβου και ιωση και ιουδ[α]{.unclear} και σιμωνος [[και]{.corr}]{.greek-added} και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

ελεγεν δε [αυτοις]{.greek-omitted} ο [ιησους]{.greek-abbr} οτι ουκ εστιν προφητης ατιμος ει μη εν τη [πατριδι]{.greek-omitted} [πατριδει]{.greek-added} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσιν]{.greek-added} [αυτου]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας εθεραπευσεν[6:5]{.aside}

και εθαυμαζεν δια την απιστιαν αυτων και περιηγεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν [των]{.greek-omitted} [πνευματων]{.greek-abbr} [των]{.greek-omitted} ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν [αιρωσιν]{.greek-omitted} [ερωσιν]{.greek-added} εις [την]{.greek-added} οδον ει μη ραβδον [και]{.greek-added} μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσησθαι]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν [εισελθητε]{.greek-omitted} [εισελθηται]{.greek-added} εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και [οσοι]{.greek-omitted} [ος]{.greek-added} αν [τοπος]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξητε]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις [αμην]{.corr} [λεγω]{.corr} [υμιν]{.corr} [ανεκτοτερον]{.corr} [εσται]{.corr} [[γη]{.corr}]{.greek-added} [σοδομοις]{.corr} [η]{.corr} [γομορροις]{.greek-omitted} [[γομοροις]{.corr}]{.greek-added} [εν]{.corr} [ημερα]{.corr} [κρισεως]{.corr} [η]{.corr} [τη]{.corr} [πολει]{.greek-omitted} [[πολι]{.corr}]{.greek-added} [εκεινη]{.corr}[6:11]{.aside}

και εξελθοντες [εκηρυσσον]{.greek-omitted} [εκηρυσσων]{.greek-added} ινα μετανοησωσιν[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και [ηλειφον]{.greek-omitted} [ηλιφον]{.greek-added} ελαιω πολλους αρρωστους και εθεραπευον [αυτους]{.greek-added}[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο [βαπτιζων]{.greek-omitted} [βαπτιστης]{.greek-added} εκ νεκρων ηγερθη και δια τουτο ενεργουσιν αι δυναμεις εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε [ελεγον]{.greek-omitted} οτι προφητης [εστιν]{.greek-omitted} [η]{.greek-added} ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν [οτι]{.greek-omitted} ον εγω απεκεφαλισα ιωαννην ουτος [εστιν]{.greek-omitted} [αυτος]{.greek-omitted} [ηγερθη]{.greek-omitted} εκ νεκρων [ηγερθη]{.greek-added}[6:16]{.aside}

αυτος γαρ ο ηρωδης [αποστειλας]{.greek-omitted} [αποστιλας]{.greek-added} [εκρατησεν]{.greek-omitted} [εκρατη]{.greek-added} [εν]{.greek-added} τον ιωαννην και ε[δησ]{.unclear}εν αυτον [εν]{.greek-omitted} [και]{.greek-added} [εβαλεν]{.greek-added} [εις]{.greek-added} [φυλακη]{.greek-omitted} [φυλακην]{.greek-added} δια [ηρω]{.greek-added} [ηρωδιαδα]{.greek-omitted} [διαδα]{.greek-added} την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ [ο]{.greek-omitted} ιωαννης τω ηρωδη [οτι]{.greek-omitted} ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας [ενειχεν]{.greek-omitted} [ενιχεν]{.greek-added} αυτω και ηθελεν αυτον [αποκτειναι]{.greek-omitted} [αποκτιναι]{.greek-added} και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητο]{.greek-added} τον ιωαννην [ειδως]{.greek-omitted} [ιδος]{.greek-added} αυτον ανδρα δικαιον και αγιον και συνετηρει [αυτον]{.greek-omitted} [αυτου]{.greek-added} και ακουσας αυτου πολλα [α]{.greek-added} εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου [δειπνον]{.greek-omitted} [διπνον]{.greek-added} [εποιει]{.greek-omitted} [εποιεισεν]{.greek-added} τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

[και]{.greek-omitted} εισελθουσης [δε]{.greek-added} της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω [αιτησον]{.greek-omitted} [αιτισον]{.greek-added} με ο εαν θελης και δωσω σοι[6:22]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [αυτη]{.greek-omitted} [ωμωσας]{.greek-added} [πολλα]{.greek-added} [ο]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ο εαν με αιτησης δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι [αιτησομαι]{.greek-omitted} [αιτισωμαι]{.greek-added} η δε ειπεν [αυτη]{.greek-added} την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} μετα σπουδης προς τον βασιλεα [ειπεν]{.greek-added} [ητησατο]{.greek-omitted} [λεγουσα]{.greek-omitted} θελω ινα μοι δως εξαυτης [επι]{.greek-omitted} [πινακι]{.greek-omitted} την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως [αποστειλας]{.greek-omitted} [αποστιλας]{.greek-added} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [και]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι [πινακι]{.greek-omitted} [πινακει]{.greek-added} και [εδωκεν]{.greek-omitted} [εδω]{.greek-added} [κεν]{.greek-added} αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον [κηδευσαι]{.greek-added} [και]{.greek-omitted} [ηραν]{.greek-omitted} το πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν [μνημειω]{.greek-omitted} [μνημιω]{.greek-added}[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και [απηγγειλαν]{.greek-omitted} [ανηγγειλαν]{.greek-added} αυτω [παντα]{.greek-omitted} [απαντα]{.greek-added} [α]{.greek-added} [και]{.greek-omitted} [οσα]{.greek-omitted} εποιησαν και οσα [εδιδαξαν]{.greek-omitted} [εδιδασκον]{.greek-added}[6:30]{.aside}

και ειπεν αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} δευτε υμεις [αυτοι]{.greek-omitted} κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} ολιγον ησαν γαρ οι [ερχομενοι]{.greek-omitted} [υπαγοντες]{.greek-added} και οι [υπαγοντες]{.greek-omitted} [ερχομενοι]{.greek-added} πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκερουν]{.greek-added}[6:31]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} συνηλθον [αυτω]{.greek-added} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [πολυν]{.greek-omitted} [πολλυν]{.greek-added} οχλον και [εσπλαγχνισθη]{.greek-omitted} [εσπλαγχνησθη]{.greek-added} επ αυτοις οτι ησαν [εσκυλμενοι]{.greek-added} [και]{.greek-added} [εριμμενοι]{.greek-added} ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται [αυτου]{.greek-omitted} λεγουσιν οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον [ουν]{.greek-added} αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις [αρτους]{.greek-omitted} τι [γαρ]{.greek-omitted} φαγωσιν [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted}[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν δηναριων διακοσιων αρτους και [δωμεν]{.greek-omitted} [δωσωμεν]{.greek-added} αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους [εχετε]{.greek-omitted} [εχεται]{.greek-added} [υμεις]{.greek-added} [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} και ιδετε και [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακλιθηναι]{.greek-added} παντας συμποσια συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και [ανεπεσον]{.greek-omitted} [ανεπεσαν]{.greek-added} πρασιαι πρασιαι ανα εκατον και ανα [πεντηκοντα]{.greek-omitted} [πεντικοντα]{.greek-added}[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ηυλογησεν]{.greek-added} και κατεκλασεν τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας εμερισεν πασιν[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [κλασματων]{.greek-omitted} [κλασματα]{.greek-added} δωδεκα κοφινους [πληρεις]{.greek-omitted} [πληρις]{.greek-added} και απο των ιχθυων[6:43]{.aside}

και ησαν οι [φαγοντες]{.greek-omitted} [φαγωντες]{.greek-added} [ωσει]{.greek-added} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [πεντακισχιλιοι]{.greek-omitted} [πεντακισχειλιοι]{.greek-added} ανδρες[6:44]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} ηναγκασεν τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν [αυτον]{.greek-added} εις το περαν [προς]{.greek-omitted} [εις]{.greek-added} [βηθσαιδαν]{.greek-omitted} [βιθσαιδα]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην [παλαι]{.greek-added} το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις [σφοδρα]{.greek-added} και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης [φαντασμα]{.greek-added} εδοξαν [φαντασμα]{.greek-omitted} [ειναι]{.greek-omitted} [ινα]{.greek-added} και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον [ειδον]{.greek-omitted} [ιδον]{.greek-added} και εταραχθησαν και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και [λιαν]{.greek-omitted} [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο [και]{.greek-omitted} [εθαυμαζον]{.greek-omitted}[6:51]{.aside}

ου γαρ [συνηκαν]{.greek-omitted} [συνη]{.greek-added} [καν]{.greek-added} επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [εις]{.greek-added} γεννησαρετ [και]{.greek-omitted} [προσωρμισθησαν]{.greek-omitted}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον [οι]{.greek-added} [ανδρες]{.greek-added} [του]{.greek-added} [τοπου]{.greek-added}[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι [τοις]{.greek-omitted} [κραββατοις]{.greek-omitted} [κραβατοις]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι [εστιν]{.greek-added} εκει [εστιν]{.greek-omitted}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν [ηπτοντο]{.greek-omitted} [ηψαντο]{.greek-added} αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων [αυτου]{.greek-omitted} [αυτον]{.greek-added} κοιναις χερσιν τουτ εστιν ανιπτοις εσθιοντας [χε[ιρ]{.unclear}]{.greek-added} αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας χειρας ουκ εσθιουσιν κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη βαπτισωνται ουκ εσθιουσιν και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων [και]{.corr} [κλινων]{.corr}[7:4]{.aside}

[επειτα]{.greek-omitted} [επιτα]{.greek-added} [επερωτωσιν]{.greek-omitted} [ερωτωσιν]{.greek-added} αυτον οι φαρισαιοι και οι γραμματεις [λεγοντες]{.greek-added} δια τι οι μαθηται σου ου περιπατουσιν κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων αλλα [ανιπτοις]{.greek-omitted} [κοιναις]{.greek-added} [ταις]{.greek-added} χερσιν εσθιουσιν τον [τον]{.greek-added} αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν [ησαιας]{.greek-omitted} περι υμων [ησαιας]{.greek-added} των υποκριτων ως γεγραπται ουτος ο λαος τοις χειλεσιν με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

[βαπτισμους]{.greek-added} [ζεστων]{.greek-added} [και]{.greek-added} [ποτηριων]{.greek-added} [και]{.greek-added} [αλλα]{.greek-added} [παρομοια]{.greek-added} [τοιαυτα]{.greek-added} [ποιειτε]{.greek-added} αφεντες [γαρ]{.greek-omitted} την εντολην του [θεου]{.greek-abbr} κρατειτε την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} [βαπτισμους]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [παρομοια]{.greek-omitted} [τοιαυτα]{.greek-omitted} [πολλα]{.greek-omitted} [ποιειτε]{.greek-omitted}[7:8]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων [τηρησητε]{.greek-omitted} [στησητε]{.greek-added}[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} εαν [ειπη]{.greek-omitted} [ειπει]{.greek-added} [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο εστιν δωρον ο [εαν]{.greek-omitted} [αν]{.greek-added} εξ εμου [ωφεληθης]{.greek-omitted} [ωφελεθης]{.greek-added}[7:11]{.aside}

[και]{.greek-omitted} ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} [αυτου]{.greek-omitted} η τη [μητρι]{.greek-abbr} [αυτου]{.greek-omitted}[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωσει]{.greek-added} υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και [συνιετε]{.greek-omitted} [συνιεται]{.greek-added}[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} [εισπορευομενον]{.greek-omitted} [εισπορευωμενον]{.greek-added} εις αυτον ο δυναται αυτον [κ[α]{.unclear}νωσαι]{.greek-added} [κοινωσαι]{.corr} αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εισιν]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και [λεγει]{.greek-omitted} [ελεγεν]{.greek-added} αυτοις [ουτως]{.greek-omitted} και υμεις ασυνετοι [εστε]{.greek-omitted} [εσται]{.greek-added} ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον [αφεδρωνα]{.greek-omitted} [αφαιδρονα]{.greek-added} εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

ελεγεν δε οτι το εκ του [ανθρωπου]{.greek-abbr} [εκπορευομενον]{.greek-omitted} [εκπορευ]{.greek-added} [ομενον]{.greek-added} [εκεινο]{.greek-omitted} [εκεινω]{.greek-added} κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν [γαρ]{.greek-omitted} εκ της καρδιας [οι]{.greek-added} [διαλογισμοι]{.greek-added} των [ανθρωπων]{.greek-abbr} οι [διαλογισμοι]{.greek-omitted} [οι]{.greek-omitted} κακοι εκπορευονται [μοιχειαι]{.greek-omitted} [μοιχιαι]{.greek-added} [πορνειαι]{.greek-omitted} [πορνιαι]{.greek-added} [φονοι]{.greek-omitted} [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} [πλεονεξιαι]{.greek-omitted} [πλεονεξια]{.greek-added} [πονηριαι]{.greek-omitted} [πονηρια]{.greek-added} δολος [ασελγεια]{.greek-omitted} [ασελγια]{.greek-added} οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

[ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} τα πονηρα εσωθεν [εκπορευεται]{.greek-omitted} [εκπορευονται]{.greek-added} και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας [απηλθεν]{.greek-omitted} [ηλθεν]{.greek-added} εις τα [μεθορια]{.greek-omitted} [ορια]{.greek-added} τυρου [και]{.greek-omitted} [σιδωνος]{.greek-omitted} και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου [ης]{.greek-omitted} [η]{.greek-added} ειχεν [το]{.greek-omitted} θυγατριον [αυτης]{.greek-omitted} [εν]{.greek-added} [πνευμα]{.greek-omitted} [[πνευματι]{.greek-abbr}]{.greek-added} [ακαθαρτον]{.greek-omitted} [ακαθαρτω]{.greek-added} ελθουσα προσεπεσεν [αυτω]{.greek-added} [προς]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted}[7:25]{.aside}

[η]{.greek-added} [δε]{.greek-added} [γυνη]{.greek-added} ην [δε]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [ελληνις]{.greek-omitted} [ελληνεις]{.greek-added} [συραφοινικισσα]{.greek-omitted} [συροφοινηκησσα]{.greek-added} τω [γενει]{.greek-omitted} [γενη]{.greek-added} και ηρωτα αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλει]{.greek-added} [εκ]{.greek-omitted} της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτη]{.greek-omitted} αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και [βαλειν]{.greek-omitted} τοις κυναριοις [βαλειν]{.greek-added}[7:27]{.aside}

η δε [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} [λεγουσα]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} ναι [κυριε]{.greek-abbr} και [γαρ]{.greek-omitted} τα κυναρια υποκατω της τραπεζης [εσθιει]{.greek-omitted} [εσθιουσιν]{.greek-added} απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον [αυτης]{.greek-omitted} ευρεν το δαιμονιον [εξεληλυθος]{.greek-omitted} [εξεληλυθως]{.greek-added} και την θυγατερα βεβλημενην επι της [κλινης]{.greek-omitted} [κληνης]{.greek-added}[7:30]{.aside}

και παλιν εξελθων [εκ]{.greek-omitted} [απο]{.greek-added} των οριων τυρου και σιδωνος ηλθεν [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν της γαλιλαιας ανα [μεσον]{.greek-omitted} [μεσων]{.greek-added} των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν εβαλεν τους δακτυλους αυτου [πτυσας]{.greek-added} εις τα ωτα αυτου και [πτυσας]{.greek-omitted} ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} εστεναξεν και λεγει αυτω εφφαθα ο εστιν [διανοιχθητι]{.greek-omitted} [διανυχθητι]{.greek-added}[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ορθως[7:35]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστιλατο]{.greek-added} αυτοις ινα μηδενι [ειπωσιν]{.greek-omitted} [μηδεν]{.greek-added} [λεγωσιν]{.greek-added} οσον δε [αυτος]{.greek-omitted} αυτοις [διεστελλετο]{.greek-omitted} [διεστιλατο]{.greek-added} μαλλον [δε]{.greek-added} περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα πεποιηκεν [και]{.greek-omitted} τους κωφους ποιει [λαλειν]{.greek-added} [και]{.greek-added} ακουειν [και]{.greek-omitted} [τους]{.greek-omitted} [αλαλους]{.greek-omitted} [λαλειν]{.greek-omitted}[7:37]{.aside}

### Chapter 8

εν εκειναις [δε]{.greek-added} ταις ημεραις [παλιν]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου οντος και μη εχοντων τι φαγωσιν προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας [αυτου]{.greek-omitted} λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις προσμενουσιν μοι και ουκ εχουσιν τι φαγωσιν[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις [τον]{.greek-added} οικον αυτων εκλυθησονται εν τη οδω [και]{.greek-added} τινες [γαρ]{.greek-omitted} αυτων [απο]{.greek-added} μακροθεν [ηκουσιν]{.greek-omitted} [ηκασιν]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν [ωδε]{.greek-added} [τουτους]{.greek-omitted} [τοσουτους]{.greek-added} [δυνησεται]{.greek-omitted} [δυναται]{.greek-added} τις [ωδε]{.greek-omitted} χορτασαι αρτων επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους [αρτους]{.greek-added} εχετε [αρτους]{.greek-omitted} οι δε ειπον επτα[8:5]{.aside}

και παρηγγειλεν τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας εκλασεν και εδιδου τοις μαθηταις αυτου ινα παραθωσιν και παρεθηκαν τω οχλω[8:6]{.aside}

και [[η]{.unclear}χον]{.greek-added} [ειχον]{.corr} ιχθυδια ολιγα και [αυτα]{.greek-added} ευλογησας ειπεν [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} [και]{.greek-omitted} [αυτα]{.greek-omitted}[8:7]{.aside}

[και]{.greek-added} εφαγον [δε]{.greek-omitted} και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως [τετρακισχιλιοι]{.greek-omitted} [τετρακισχειλιοι]{.greek-added} και απελυσεν αυτους[8:9]{.aside}

και [ευθεως]{.greek-omitted} εμβας [ευθυς]{.greek-added} εις [το]{.greek-omitted} πλοιον μετα των μαθητων αυτου ηλθεν εις [τα]{.greek-omitted} [μερη]{.greek-omitted} [δαλμανουθα]{.greek-omitted} [το]{.greek-added} [ορος]{.greek-added} [μαγεδα]{.greek-added}[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο [συζητειν]{.greek-omitted} [συνζητειν]{.greek-added} αυτω ζητουντες [τι]{.greek-added} παρ αυτου [σημειον]{.greek-omitted} [σημιον]{.greek-added} απο του [ουρανου]{.greek-abbr} [πειραζοντες]{.greek-omitted} [πιραζοντες]{.greek-added} αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη [ζητει]{.greek-added} [σημειον]{.greek-omitted} [σημιον]{.greek-added} [επιζητει]{.greek-omitted} αμην λεγω υμιν ει δοθησεται τη γενεα [ταυτη]{.greek-omitted} [εκεινη]{.greek-added} [σημειον]{.greek-omitted} [σημιον]{.greek-added}[8:12]{.aside}

και αφεις αυτους [παλιν]{.greek-added} εμβας [παλιν]{.greek-omitted} εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [μαθηται]{.greek-added} λαβειν αρτους [και]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} ενα [μονον]{.greek-added} [εχοντες]{.greek-added} αρτον [ουκ]{.greek-omitted} [ειχον]{.greek-omitted} μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και [διεστελλετο]{.greek-omitted} [διεστιλατο]{.greek-added} αυτοις λεγων ορατε [και]{.greek-added} [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} απο της ζυμης των [φαρισαιων]{.greek-omitted} [φαρησαιων]{.greek-added} και [απο]{.greek-added} της [ζυμης]{.greek-omitted} [ζυμις]{.greek-added} [ηρωδου]{.greek-omitted} [των]{.greek-added} [ηρωδιανων]{.greek-added}[8:15]{.aside}

και διελογιζοντο προς αλληλους [λεγοντες]{.greek-omitted} οτι αρτους ουκ [εχομεν]{.greek-omitted} [εχουσιν]{.greek-added}[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} [εν]{.greek-added} [ταις]{.greek-added} [καρδιαις]{.greek-added} [υμων]{.greek-added} [ολιγοπιστοι]{.greek-added} οτι αρτους ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} ουπω νοειτε ουδε συνιετε [ετι]{.greek-omitted} [πεπωρωμενην]{.greek-omitted} [πεπωρρωμενην]{.greek-added} [εχετε]{.greek-omitted} [εχοντες]{.greek-added} την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} και ωτα εχοντες ουκ [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} [και]{.greek-omitted} [ου]{.greek-omitted} [μνημονευετε]{.greek-omitted}[8:18]{.aside}

[οτε]{.greek-omitted} τους πεντε αρτους [ους]{.greek-added} εκλασα εις τους [πενκισχειλιους]{.greek-added} [πεντακισχιλιους]{.greek-omitted} [[πεντακισχειλιους]{.corr}]{.greek-added} ποσους κοφινους πληρεις κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις πως ου [συνιετε]{.greek-omitted} [συνιεται]{.greek-added}[8:21]{.aside}

και [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} εις [βηθσαιδαν]{.greek-omitted} [βιθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος [αυτου]{.greek-added} της χειρος [του]{.greek-omitted} [τυφλου]{.greek-omitted} εξηγαγεν αυτον εξω της [κωμης]{.greek-omitted} [κωμις]{.greek-added} και πτυσας εις τα ομματα αυτου [και]{.greek-added} επιθεις τας χειρας αυτω επηρωτα αυτον ει τι [βλεπη]{.greek-added} [βλεπει]{.corr}[8:23]{.aside}

και αναβλεψας ελεγεν βλεπω τους [ανθρωπους]{.greek-abbr} [οτι]{.greek-omitted} ως δενδρα [ορω]{.greek-omitted} περιπατουντας[8:24]{.aside}

ειτα παλιν επεθηκεν τας χειρας επι τους οφθαλμους αυτου και [διεβλεψεν]{.greek-added} [εποιησεν]{.greek-omitted} [αυτον]{.greek-omitted} [αναβλεψαι]{.greek-omitted} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ενεβλεπεν]{.greek-added} [τηλαυγως]{.greek-omitted} [τιλαυγως]{.greek-added} [απαντας]{.greek-omitted} [απαντα]{.greek-added}[8:25]{.aside}

και απεστειλεν αυτον εις [τον]{.greek-omitted} οικον αυτου λεγων [μηδε]{.greek-omitted} [υπαγε]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [εαν]{.greek-added} εις την κωμην εισελθης [μηδενι]{.greek-added} [μηδεν]{.greek-added} [ειπης]{.greek-added} μηδε [ειπης]{.greek-omitted} [τινι]{.greek-omitted} εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας [καισαρειας]{.greek-omitted} [καισαριας]{.greek-added} της φιλιππου και εν τη [ωδω]{.greek-added} [οδω]{.greek-omitted} [επηρωτα]{.greek-omitted} τους μαθητας αυτου [επηρωτα]{.greek-added} λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [αυτω]{.greek-added} [λεγοντες]{.greek-added} ιωαννην τον [βαπτιστην]{.greek-omitted} [βαπτιζοντα]{.greek-added} και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

[και]{.greek-omitted} [αυτος]{.greek-omitted} λεγει αυτοις υμεις δε τινα με [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} ειναι αποκριθεις δε ο πετρος [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι λεγωσιν περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και [των]{.greek-omitted} αρχιερεων και των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και [μετα]{.greek-omitted} [τρεις]{.greek-omitted} [τη]{.greek-added} [τριτη]{.greek-added} [ημερας]{.greek-omitted} [ημερα]{.greek-added} αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου επετιμησεν τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [ει]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} [θελει]{.greek-omitted} [θελη]{.greek-added} οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} θελη την [εαυτου]{.greek-added} ψυχην [αυτου]{.greek-omitted} σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την εαυτου ψυχην ενεκεν [εμου]{.greek-omitted} [και]{.greek-omitted} του ευαγγελιου [ευρησει]{.greek-added} [ουτος]{.greek-omitted} [σωσει]{.greek-omitted} αυτην[8:35]{.aside}

τι γαρ ωφελησει [τον]{.greek-added} [ανθρωπον]{.greek-abbr} εαν [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

[η]{.greek-omitted} τι [γαρ]{.greek-added} δωσει [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} [επαι]{.greek-added} [επαισχυνθη]{.greek-omitted} [σχυνθη]{.greek-added} με και τους εμους λογους εν τη γενεα ταυτη τη [μοιχαλιδι]{.greek-omitted} [μοιχαλιδη]{.greek-added} και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι εισιν τινες των ωδε [εστηκοτων]{.greek-omitted} [εστικοτων]{.greek-added} οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν ιδωσιν την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ [παραλαμβανει]{.greek-omitted} [παραλαμβαννει]{.greek-added} ο [ιησους]{.greek-abbr} τον πετρον και τον [ιωαννην]{.greek-added} [και]{.greek-added} [τον]{.greek-added} ιακωβον [και]{.greek-omitted} [ιωαννην]{.greek-omitted} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και [εν]{.greek-added} [τω]{.greek-added} [προσευχεσθαι]{.greek-added} [αυτον]{.greek-added} μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα [λιαν]{.greek-omitted} [λειαν]{.greek-added} [ως]{.greek-omitted} [ωσει]{.greek-added} [χιων]{.greek-omitted} [χειων]{.greek-added} οια [γναφευς]{.greek-omitted} [κναφευς]{.greek-added} επι της γης ου δυναται [ουτως]{.greek-added} λευκαναι[9:3]{.aside}

και [ιδου]{.greek-added} ωφθη [αυτοις]{.greek-omitted} [αυτω]{.greek-added} ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν [συλλαλουντες]{.greek-omitted} [συνλαλουντες]{.greek-added} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος [λεγει]{.greek-omitted} [ελεγεν]{.greek-added} τω [ιησου]{.greek-abbr} [ραββι]{.greek-omitted} [ραββει]{.greek-added} καλον εστιν ημας ωδε ειναι [και]{.greek-omitted} [ει]{.greek-added} [θελεις]{.greek-added} ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυση]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ [ηδει]{.greek-omitted} [ηδη]{.greek-added} τι [λαλησει]{.greek-omitted} [αποκριθη]{.greek-added} ησαν γαρ εκφοβοι[9:6]{.aside}

και [ιδου]{.greek-added} εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [φωνη]{.greek-added} ηλθεν [φωνη]{.greek-omitted} εκ της νεφελης [λεγουσα]{.greek-added} ουτος εστιν ο [υιος]{.greek-abbr} μου ο [αγαπητος]{.greek-omitted} [αγαπιτος]{.greek-added} [ακουσατε]{.greek-added} αυτου [ακουετε]{.greek-omitted}[9:7]{.aside}

και [εξαπινα]{.greek-omitted} [ευθεως]{.greek-added} περιβλεψαμενοι ουκετι ουδενα [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλα τον [ιησουν]{.greek-abbr} μονον μεθ [εαυτων]{.greek-omitted} [εαυτον]{.greek-added}[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους [διεστειλατο]{.greek-omitted} [διεστιλατο]{.greek-added} αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} α [ειδον]{.greek-omitted} [ιδον]{.greek-added} [εξηγησονται]{.greek-added} ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν [προς]{.greek-omitted} [παρ]{.greek-added} [εαυτους]{.greek-omitted} [εαυτοις]{.greek-added} [συζητουντες]{.greek-omitted} [συνζητουντες]{.greek-added} τι εστιν το εκ νεκρων αναστηναι[9:10]{.aside}

και [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας [μεν]{.greek-omitted} ελθων πρωτον [αποκαθιστα]{.greek-omitted} [αποκατασταινει]{.greek-added} παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} [του]{.greek-omitted} [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι [και]{.greek-omitted} ηλιας [εληλυθεν]{.greek-omitted} [ηλθεν]{.greek-added} και εποιησαν [εν]{.greek-added} αυτω οσα ηθελησαν καθως γεγραπται [επ]{.greek-omitted} [περι]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added}[9:13]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον [πολυν]{.greek-omitted} περι αυτους και [τους]{.greek-added} γραμματεις [συζητουντας]{.greek-omitted} [συνζητουντας]{.greek-added} [προς]{.greek-added} [αυτοις]{.greek-omitted} [αυτους]{.greek-added}[9:14]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} πας ο οχλος [ιδων]{.greek-omitted} [ιδοντες]{.greek-added} αυτον [εξεθαμβηθη]{.greek-omitted} [εξεθαμβηθησαν]{.greek-added} και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και επηρωτησεν [τους]{.greek-omitted} [αυτους]{.greek-added} [γραμματεις]{.greek-omitted} τι [συζητειτε]{.greek-omitted} [συνζητειτε]{.greek-added} προς αυτους[9:16]{.aside}

και [αποκριθεις]{.greek-omitted} [απεκριθεις]{.greek-added} [εις]{.greek-omitted} εκ του οχλου [εις]{.greek-added} ειπεν [αυτω]{.greek-added} διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον [καταλαβη]{.greek-omitted} [καταλαβει]{.greek-added} ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και [ξηραινεται]{.greek-omitted} [ξηρενεται]{.greek-added} και [ειπον]{.greek-omitted} [ειπα]{.greek-added} τοις μαθηταις σου ινα [αυτο]{.greek-omitted} εκβαλωσιν [αυτω]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} αποκριθεις αυτω [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} λεγει ω γενεα απιστος εως ποτε προς υμας [εσομαι]{.greek-omitted} [εσωμαι]{.greek-added} εως ποτε [ανεξομαι]{.greek-omitted} [ανεξωμαι]{.greek-added} υμων [φερετε]{.greek-omitted} [φερεται]{.greek-added} αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν [αυτον]{.greek-omitted} [το]{.greek-added} [παιδιον]{.greek-added} και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και επηρωτησεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τον [πατερα]{.greek-abbr} αυτου [λεγων]{.greek-added} ποσος χρονος εστιν [ως]{.greek-omitted} [[αφ]{.unclear}]{.greek-added} [ο[υ]{.unclear}]{.greek-added} [[ος]{.corr}]{.greek-added} τουτο γεγονεν αυτω ο δε ειπεν [παιδιοθεν]{.greek-omitted} [παιδιωθεν]{.greek-added}[9:21]{.aside}

και [πολλακις]{.greek-omitted} [πολλακεις]{.greek-added} αυτον και εις [το]{.greek-omitted} πυρ εβαλεν και εις υδατα ινα [απολεση]{.greek-omitted} [απολεσει]{.greek-added} αυτον αλλ [ει]{.greek-omitted} [η]{.greek-added} τι δυνασαι βοηθησον ημιν [σπλαγχνισθεις]{.greek-omitted} [σπλαγχνησθεις]{.greek-added} εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [το]{.greek-omitted} ει [δυνασαι]{.greek-omitted} [δυνη]{.greek-added} πιστευσαι παντα [γαρ]{.greek-added} δυνατα τω πιστευοντι[9:23]{.aside}

[και]{.greek-omitted} ευθεως [δε]{.greek-added} κραξας ο [πατηρ]{.greek-abbr} του παιδιου [μετα]{.greek-omitted} [δακρυων]{.greek-omitted} ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος επετιμησεν τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας [αυτον]{.greek-omitted} της χειρος [αυτου]{.greek-added} ηγειρεν αυτον και ανεστη[9:27]{.aside}

και [εισελθοντα]{.greek-omitted} [εισελθοντος]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added} εις οικον [προσηλθον]{.greek-added} [αυτω]{.greek-added} οι μαθηται αυτου [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} κατ ιδιαν [και]{.greek-added} [ηρωτησαν]{.greek-added} [αυτον]{.greek-added} [λεγοντες]{.greek-added} οτι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν [ουδενι]{.greek-omitted} [ου]{.greek-added} [δενει]{.greek-added} δυναται εξελθειν ει μη εν προσευχη και [νηστεια]{.greek-omitted} [νηστια]{.greek-added}[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδοθησεται]{.greek-added} εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα [αναστησεται]{.greek-omitted} [εγειρεται]{.greek-added}[9:31]{.aside}

οι δε [ηγνοουν]{.greek-omitted} [ηγνωουν]{.greek-added} το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη [οδω]{.greek-omitted} [ωδω]{.greek-added} [διελεχθητε]{.greek-added} προς εαυτους [διελογιζεσθε]{.greek-omitted}[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις [μειζων]{.greek-omitted} [μιζων]{.greek-added}[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} εφωνησεν τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν [αυτο]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [εμμεσω]{.greek-added} αυτων και εναγκαλισαμενος [αυτο]{.greek-omitted} [αυτω]{.greek-added} ειπεν αυτοις[9:36]{.aside}

ος [εαν]{.greek-omitted} [αν]{.greek-added} εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος [εαν]{.greek-omitted} [αν]{.greek-added} εμε δεξηται ουκ εμε δεχεται [μονον]{.greek-added} αλλα [και]{.greek-added} τον [αποστειλαντα]{.greek-omitted} [πεμψαντα]{.greek-added} με[9:37]{.aside}

[απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} δε αυτω ιωαννης [λεγων]{.greek-omitted} [και]{.greek-added} [λεγει]{.greek-added} διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} τινα τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και εκωλυσαμεν αυτον [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται [ταχυ]{.greek-omitted} [κακολογησαι]{.greek-omitted} με [κακολογεισαι]{.greek-added}[9:39]{.aside}

ος γαρ ουκ εστιν καθ [υμων]{.greek-omitted} [ημων]{.greek-added} υπερ [υμων]{.greek-omitted} [ημων]{.greek-added} εστιν[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτισει]{.greek-added} υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι μου οτι [χριστου]{.greek-abbr} [εστε]{.greek-omitted} [εσται]{.greek-added} αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεσει]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} [σκανδαλιση]{.greek-omitted} [σκανδαλησει]{.greek-added} ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον εστιν [μαλλον]{.greek-added} αυτω [μαλλον]{.greek-omitted} ει περικειται [μυλικος]{.greek-added} λιθος [μυλικος]{.greek-omitted} περι [τον]{.greek-omitted} [των]{.greek-added} [τραχηλον]{.greek-omitted} [τραχειλον]{.greek-added} αυτου και [βεβληται]{.greek-omitted} [βεβλητο]{.greek-added} εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιζει]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον [σοι]{.greek-omitted} εστιν [σε]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις [την]{.greek-omitted} [γεενναν]{.greek-omitted} [εις]{.greek-omitted} το πυρ το ασβεστον[9:43]{.aside}

και εαν ο πους σου [σκανδαλιζη]{.greek-omitted} [σκανδαλιζει]{.greek-added} σε αποκοψον αυτον καλον εστιν [σοι]{.greek-omitted} εισελθειν [σε]{.greek-added} εις την ζωην [χωλον]{.greek-omitted} [χολον]{.greek-added} η τους [δυο]{.corr} ποδας εχοντα [βληθηναι]{.greek-omitted} [απελθειν]{.greek-added} εις [την]{.greek-omitted} [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} [εις]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [το]{.greek-omitted} [ασβεστον]{.greek-omitted}[9:45]{.aside}

και εαν ο οφθαλμος σου [σκανδαλιζη]{.greek-omitted} [σκανδαλιζει]{.greek-added} σε εκβαλε αυτον καλον [σοι]{.greek-omitted} εστιν [μονο]{.greek-added} [μονοφθαλμον]{.greek-omitted} [φθαλμον]{.greek-added} εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις [την]{.greek-omitted} [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} [του]{.greek-omitted} [πυρος]{.greek-omitted}[9:47]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκωλιξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι [αλισθησεται]{.greek-omitted} [αυλισθησεται]{.greek-added} [και]{.corr} [πασα]{.corr} [θυσια]{.corr} [αλι]{.corr} [αλισθησεται]{.corr}[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι [αυτο]{.greek-omitted} [αυτω]{.greek-added} [αρτυσετε]{.greek-omitted} [εχετε]{.greek-omitted} [αρτυσηται]{.greek-added} [εχεται]{.greek-added} [ουν]{.greek-added} [υμεις]{.greek-added} εν εαυτοις [αλας]{.greek-omitted} [αλα]{.greek-added} και [ειρηνευετε]{.greek-omitted} [ειρηνευεται]{.greek-added} εν αλληλοις[9:50]{.aside}

### Chapter 10

[και]{.greek-added} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} αναστας ερχεται εις τα ορια της ιουδαιας [δια]{.greek-omitted} [του]{.greek-omitted} περαν του ιορδανου και [συμπορευονται]{.greek-omitted} [συμπορευεται]{.greek-added} παλιν [οχλοι]{.greek-omitted} [οχλος]{.greek-added} προς αυτον και ως [ειωθει]{.greek-omitted} [ιωθει]{.greek-added} παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [φαρισαιοι]{.greek-omitted} [φαρησαιοι]{.greek-added} επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι [πειραζοντες]{.greek-omitted} [πιραζοντες]{.greek-added} αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν [ενετειλατο]{.greek-omitted} [ετιλατο]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} επετρεψεν [βιβλιον]{.greek-omitted} [βιβληον]{.greek-added} αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς [την]{.greek-omitted} [τη]{.greek-added} σκληροκαρδιαν υμων εγραψεν [υμιν]{.greek-omitted} την εντολην ταυτην[10:5]{.aside}

απο δε αρχης [κτισεως]{.greek-omitted} [κτησεως]{.greek-added} αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

[και]{.greek-added} [ειπεν]{.greek-added} ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταλιψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε [ουκετι]{.greek-omitted} [ουκ]{.greek-added} εισιν δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη [οικια]{.greek-omitted} [οικιαν]{.greek-added} παλιν οι μαθηται [αυτου]{.greek-omitted} περι του αυτου επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις [ος]{.greek-omitted} εαν [ανηρ]{.greek-added} [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου και [γαμηση]{.greek-omitted} [γαμισει]{.greek-added} αλλην μοιχαται [επ]{.greek-omitted} [αυτην]{.greek-omitted}[10:11]{.aside}

και [γυνη]{.greek-added} εαν [εξελθη]{.greek-added} [απο]{.greek-added} [του]{.greek-added} [ανδρος]{.greek-added} [γυνη]{.greek-omitted} [απολυση]{.greek-omitted} [τον]{.greek-omitted} [ανδρα]{.greek-omitted} [αυτης]{.greek-omitted} και [γαμηθη]{.greek-omitted} [αλλω]{.greek-omitted} [γαμησει]{.greek-added} [αλλον]{.greek-added} μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις [προσφερουσιν]{.greek-omitted} [προσερουσιν]{.greek-added}[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} ηγανακτησεν και [επιτιμησας]{.greek-added} ειπεν αυτοις [αφετε]{.greek-omitted} [αφεται]{.greek-added} τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος [εαν]{.greek-omitted} [αν]{.greek-added} μη [δεξηται]{.greek-omitted} [δεξητε]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη [εισεθη]{.greek-added} [εισελθη]{.corr} εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα [τιθεις]{.greek-omitted} [τιθων]{.greek-added} τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηυλογει]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} [πλουσιος]{.greek-added} προσδραμων [εις]{.greek-omitted} και [γονυπετησας]{.greek-omitted} [γονυπετων]{.greek-added} αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην [αιωνιον]{.greek-omitted} κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα [εφυλαξαμην]{.greek-omitted} [εφυλαξα]{.greek-added} εκ [νεοτητος]{.greek-omitted} [νεωτητος]{.greek-added} μου [τι]{.greek-added} [ετι]{.greek-added} [υστερ[ω]{.unclear}]{.greek-added}[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας [αυτω]{.greek-omitted} ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελης]{.greek-added} [τελιος]{.greek-added} [ειναι]{.greek-added} εν [σοι]{.greek-omitted} [σε]{.greek-added} υστερει υπαγε οσα εχεις πωλησον και δος [τοις]{.greek-added} πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} αρας τον [σταυρον]{.greek-abbr} [ακολουθη]{.greek-added} [μοι]{.greek-added}[10:21]{.aside}

ο δε στυγνασας επι [τουτω]{.greek-added} τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον εστιν τους [πεποιθοτας]{.greek-omitted} [πεποιθωτας]{.greek-added} επι [τοις]{.greek-added} χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον εστιν [καμηλον]{.greek-omitted} [καμιλον]{.greek-added} δια [της]{.greek-omitted} τρυμαλιας της [ραφιδος]{.greek-omitted} [ραφηδος]{.greek-added} εισελθειν η [πλουσιον]{.greek-omitted} εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν [πλουσιον]{.greek-added}[10:25]{.aside}

οι δε [περισσως]{.greek-omitted} [πρισσως]{.greek-added} εξεπλησσοντο λεγοντες προς εαυτους και τις [δυναται]{.greek-omitted} [δυνησεται]{.greek-added} σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [μεν]{.greek-added} [ανθρωποις]{.greek-abbr} [τουτο]{.greek-added} αδυνατον [εστιν]{.greek-added} αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο [δε]{.greek-added} [λεγειν]{.greek-added} [αυτω]{.greek-added} ο πετρος [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

[εαν]{.greek-omitted} [ος]{.greek-added} [ου]{.greek-added} μη λαβη [εκατονταπλασιονα]{.greek-omitted} νυν [εκατονταπλασιωνα]{.greek-added} εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [μητερας]{.greek-abbr} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις αρχιερευσιν και [τοις]{.greek-added} γραμματευσιν και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33]{.aside}

και [εμπαιξουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [εμ]{.greek-added} [πεξουσιν]{.greek-added} [αυτον]{.greek-added} και μαστιγωσουσιν αυτον [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν [σε]{.greek-added} [αιτησωμεν]{.greek-omitted} [αιτισωμεν]{.greek-added} ποιησης ημιν[10:35]{.aside}

ο δε ειπεν [αυτοις]{.greek-omitted} τι [θελετε]{.greek-omitted} [θελεται]{.greek-added} ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} ειπεν αυτοις ουκ οιδατε τι [αιτεισθε]{.greek-omitted} [αιτεισθαι]{.greek-added} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} πιειν το ποτηριον ο εγω πινω [και]{.greek-omitted} [η]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω [πιεσθε]{.greek-omitted} [πιεσθαι]{.greek-added} και το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζωμαι]{.greek-added} [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added}[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι [αυτων]{.greek-omitted} κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη [γενεσθαι]{.greek-omitted} [μεγας]{.greek-omitted} εν υμιν [μεγας]{.greek-added} [γενεσθαι]{.greek-added} εσται υμων διακονος[10:43]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} θελη [εν]{.greek-added} [υμων]{.greek-omitted} [υμιν]{.greek-added} [γενεσθαι]{.greek-omitted} [ειναι]{.greek-added} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [ιδου]{.greek-added} [ο]{.greek-added} [υιος]{.greek-abbr} τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο [ναζωραιος]{.greek-omitted} [ναζωρινος]{.greek-added} εστιν ηρξατο κραζειν [[κυριε]{.greek-abbr}]{.greek-added} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-omitted} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν [υιε]{.greek-omitted} [[κυριε]{.greek-abbr}]{.greek-added} [[υιος]{.greek-abbr}]{.greek-added} [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και φωνουσιν [τον]{.greek-omitted} [αυτον]{.greek-added} [τυφλον]{.greek-omitted} [λεγοντες]{.greek-added} λεγοντες αυτω [θαρσει]{.greek-omitted} [εγειραι]{.greek-omitted} [θαρρων]{.greek-added} [εγειρου]{.greek-added} φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας ηλθεν προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος ειπεν [αυτω]{.greek-omitted} [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η [πιστις]{.greek-omitted} [πιστης]{.greek-added} σου σεσωκεν σε και ευθεως ανεβλεψεν και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε [εγγιζουσιν]{.greek-omitted} [εγγειζουσιν]{.greek-added} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολ[λ]{.unclear}υμα]{.greek-added} [[ιεροσολυμα]{.corr}]{.greek-added} εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

[λεγων]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} εις την κωμην την κατεναντι υμων και ευθεως [εισπορευομενοι]{.greek-omitted} [πορευομενοι]{.greek-added} εις αυτην [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκεν]{.greek-added} [και]{.greek-added} λυσαντες αυτον [αγαγετε]{.greek-omitted} [αγαγεται]{.greek-added}[11:2]{.aside}

και εαν τις υμιν ειπη τι [ποιειτε]{.greek-omitted} [τουτο]{.greek-omitted} [λυεται]{.greek-added} [τον]{.greek-added} [πωλον]{.greek-added} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον [δε]{.greek-omitted} [ουν]{.greek-added} και ευρον [τον]{.greek-added} πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

[και]{.greek-omitted} τινες [δε]{.greek-added} των εκει εστηκοτων [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως [ενετειλατο]{.greek-omitted} [ειπεν]{.greek-added} [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και [ηγαγον]{.greek-omitted} [αγουσιν]{.greek-added} τον πωλον προς τον [ιησουν]{.greek-abbr} και [επεβαλον]{.greek-omitted} [επιβαλλουσιν]{.greek-added} αυτω [τα]{.greek-omitted} ιματια [αυτων]{.greek-omitted} και [εκαθισεν]{.greek-omitted} [καθιζει]{.greek-added} επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων [εστρωσαν]{.greek-omitted} [εις]{.greek-omitted} [εστρωννυον]{.greek-added} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added} αλλοι δε [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ [των]{.greek-omitted} δενδρων και εστρωννυον εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες [εκραζον]{.greek-omitted} [εκραζων]{.greek-added} λεγοντες ωσαννα [τω]{.greek-added} [υψιστω]{.greek-added} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} [ωσαννα]{.greek-omitted} [ειρηνη]{.greek-added} εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} [και]{.greek-omitted} εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της [ωρας]{.greek-omitted} [ημερας]{.greek-added} εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο [βηθανιαν]{.greek-added} [βηθανιας]{.corr} [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added}[11:12]{.aside}

και ιδων συκην [απο]{.greek-added} [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} εχουσαν φυλλα ηλθεν ει αρα [τι]{.greek-added} ευρησει [τι]{.greek-omitted} εν αυτη και ελθων επ αυτην ουδεν [ευρεν]{.greek-omitted} [ηυρεν]{.greek-added} ει μη φυλλα [μονα]{.greek-added} ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι [εκ]{.greek-omitted} [σου]{.greek-omitted} εις τον αιωνα [εκ]{.greek-added} [σου]{.greek-added} μηδεις καρπον [φαγοι]{.greek-omitted} [φαγη]{.greek-added} και [ηκουον]{.greek-omitted} [ηκουσαν]{.greek-added} οι μαθηται αυτου[11:14]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} και εισελθων [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [αγοραζοντας]{.greek-omitted} [αγωραζοντας]{.greek-added} εν τω ιερω και τας τραπεζας των κολλυβιστων [εξεχεεν]{.greek-added} και τας καθεδρας των [πωλουντων]{.greek-omitted} [πολουντων]{.greek-added} τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και εδιδασκεν λεγων [αυτοις]{.greek-omitted} [ου]{.greek-omitted} γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted} υμεις δε εποιησατε αυτον [σπηλαιον]{.greek-omitted} [σπηλλαιον]{.greek-added} ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον [απολεσωσιν]{.greek-omitted} [απωλεσωσιν]{.greek-added} εφοβουντο γαρ αυτον [οτι]{.greek-omitted} πας [γαρ]{.greek-added} ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και [οτε]{.greek-omitted} [οψε]{.greek-omitted} [οταν]{.greek-added} [οψαι]{.greek-added} εγενετο [εξεπορευετο]{.greek-omitted} εξω της πολεως [εξεπορευοντο]{.greek-added}[11:19]{.aside}

και [παραπορευομενοι]{.greek-added} πρωι [παραπορευομενοι]{.greek-omitted} [ειδον]{.greek-omitted} [ιδον]{.greek-added} την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω [ραββι]{.greek-omitted} [ραββει]{.greek-added} ιδε η συκη ην κατηρασω εξηρανται[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις [ει]{.greek-added} εχετε [πιστιν]{.greek-omitted} [πιστην]{.greek-added} [θεου]{.greek-omitted}[11:22]{.aside}

αμην [γαρ]{.greek-omitted} λεγω υμιν οτι ος αν ειπη τω [ορει]{.greek-omitted} [ορι]{.greek-added} τουτω [αρθητι]{.greek-omitted} [αρθηναι]{.greek-added} και [βληθητι]{.greek-omitted} [βληθηναι]{.greek-added} εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι α λεγει γινεται εσται αυτω [ο]{.greek-omitted} [εαν]{.greek-omitted} [ειπη]{.greek-omitted}[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτισησθαι]{.greek-added} [[αιτισθαι]{.corr}]{.greek-added} [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} οτι [λαμβανετε]{.greek-omitted} [λαμβανεται]{.greek-added} και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκεται]{.greek-added} προσευχομενοι [αφιετε]{.greek-omitted} [αφιεται]{.greek-added} ει τι [εχετε]{.greek-omitted} [εχεται]{.greek-added} κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ [αφιετε]{.greek-omitted} [αφιεται]{.greek-added} ουδε ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν [ινα]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιης]{.greek-omitted}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις [επερωτησω]{.greek-omitted} [επερωτισω]{.greek-added} υμας [και]{.greek-omitted} [εγω]{.greek-omitted} [καγω]{.greek-added} [λογον]{.greek-added} ενα [λογον]{.greek-omitted} [και]{.greek-omitted} [αποκριθητε]{.greek-omitted} [αποκριθηται]{.greek-added} μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} [αποκριθητε]{.greek-omitted} [αποκριθηται]{.greek-added} μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες [τι]{.greek-added} [ειπωμεν]{.greek-added} εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι [ουν]{.greek-omitted} ουκ επιστευσατε [εις]{.greek-added} αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} [εφοβουντο]{.greek-omitted} [φοβουμεθα]{.greek-added} τον λαον [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ [ειχον]{.greek-omitted} [ειχοσαν]{.greek-added} τον ιωαννην οτι [οντως]{.greek-omitted} προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} τω [ιησου]{.greek-abbr} [λεγουσιν]{.greek-added} ουκ οιδαμεν και [ο]{.greek-omitted} [ιησους]{.greek-omitted} αποκριθεις λεγει αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις [λεγειν]{.greek-omitted} [λαλειν]{.greek-added} αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και περιεθηκεν [αυτω]{.greek-added} φραγμον και ωρυξεν υποληνιον και ωκοδομησεν πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστιλεν]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων [λαβη]{.greek-omitted} [λαβει]{.greek-added} απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδ[ει]{.unclear}ραν και απεστειλαν [κενον]{.greek-omitted} [καινον]{.greek-added}[12:3]{.aside}

[και]{.greek-omitted} παλιν απεστειλεν προς αυτους αλλον δουλον [κακεινον]{.greek-omitted} [λιθοβολησαντες]{.greek-omitted} [εκεφαλαιωσαν]{.greek-omitted} και [εκεινον]{.greek-added} [κεφαλαιωσαντες]{.greek-added} [απεστειλαν]{.greek-omitted} [απεστιλαν]{.greek-added} [ητιμωμενον]{.greek-omitted} [ητιμασμενον]{.greek-added}[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστιλεν]{.greek-added} κακεινον [απεκτειναν]{.greek-omitted} [απεκτιναν]{.greek-added} και πολλους αλλους τους μεν δεροντες τους δε [αποκτενοντες]{.greek-omitted} [αποκτεννοντες]{.greek-added}[12:5]{.aside}

[υστερον]{.greek-added} [δε]{.greek-added} ετι [ουν]{.greek-omitted} ενα [υιον]{.greek-abbr} εχων [τον]{.greek-added} αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστιλεν]{.greek-added} [και]{.greek-omitted} [αυτον]{.greek-omitted} προς αυτους εσχατον λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [ειπον]{.greek-omitted} [θεασαμενοι]{.greek-added} [αυτον]{.greek-added} [ερχομενον]{.greek-added} προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [οτι]{.greek-omitted} [ειπαν]{.greek-added} ουτος εστιν ο κληρονομος δευτε [αποκτεινωμεν]{.greek-omitted} [αποκτινωμεν]{.greek-added} αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον [απεκτειναν]{.greek-omitted} [απεκτιναν]{.greek-added} και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο κυριος του αμπελωνος [ελευσεται]{.greek-omitted} [ελευσετε]{.greek-added} και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδοκημασαν]{.greek-added} οι οικοδομουντες ουτος εγενηθη εις κεφαλην [γωνιας]{.greek-omitted} [γονιας]{.greek-added}[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και αποστελλουσιν προς αυτον τινας των [φαρισαιων]{.greek-omitted} [φαρησαιων]{.greek-added} και των ηρωδιανων ινα αυτον αγρευσωσιν λογω[12:13]{.aside}

οι δε ελθοντες [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [ηρξαντο]{.greek-added} [ερωταν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [δολω]{.greek-added} [λεγοντες]{.greek-added} διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [ειπον]{.greek-added} [ουν]{.greek-added} [ημιν]{.greek-added} [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον [καισαρι]{.greek-omitted} δουναι [και]{.greek-added} [σαρι]{.greek-added} η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε [[ιησους]{.greek-abbr}]{.greek-added} [ιδων]{.greek-added} [ειδως]{.greek-omitted} [[ιδως]{.corr}]{.greek-added} αυτων την υποκρισιν ειπεν αυτοις τι με [πειραζετε]{.greek-omitted} [πιραζεται]{.greek-added} [υποκριται]{.greek-added} [φερετε]{.greek-omitted} [φερεται]{.greek-added} μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} [αυτω]{.greek-omitted} καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις [αποδοτε]{.greek-omitted} τα καισαρος [αποδοτε]{.greek-added} καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[12:17]{.aside}

και ερχονται [σαδδουκαιοι]{.greek-omitted} προς αυτον [σαδδουκαιοι]{.greek-added} οιτινες λεγουσιν [αναστασιν]{.greek-omitted} [αναστασης]{.greek-added} [μη]{.greek-omitted} [ειναι]{.greek-omitted} [ουκ]{.greek-added} [εστιν]{.greek-added} και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και [καταλιπη]{.greek-omitted} [εχει]{.greek-added} γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι ησαν [παρ]{.greek-added} [ημιν]{.greek-added} και ο πρωτος ελαβεν γυναικα και [αποθνησκων]{.greek-omitted} [απεθανεν]{.greek-added} [και]{.greek-added} ουκ αφηκεν σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν και ουδε [αυτος]{.greek-omitted} [ουτος]{.greek-added} αφηκεν σπερμα και ο τριτος [ωσαυτως]{.greek-omitted}[12:21]{.aside}

[ωσαυτως]{.greek-added} [και]{.greek-omitted} [ελαβον]{.greek-omitted} [αυτην]{.greek-omitted} οι επτα και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} [δε]{.greek-added} παντων [απεθανεν]{.greek-omitted} και η γυνη [απεθανεν]{.greek-added}[12:22]{.aside}

εν τη αναστασει [ουν]{.greek-added} οταν αναστωσιν τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

[και]{.greek-omitted} αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added} μη [ειδοτες]{.greek-omitted} [ιδωτες]{.greek-added} τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ [αναστωσιν]{.greek-added} εκ νεκρων [αναστωσιν]{.greek-omitted} ουτε γαμουσιν ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [[ουρανος]{.greek-abbr}]{.greek-added} [[ουρανοις]{.greek-abbr}]{.corr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} [λεγων]{.greek-omitted} εγω [ειμι]{.greek-added} ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added}[12:27]{.aside}

και προσελθων εις των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} [ακουσας]{.greek-omitted} [ακουων]{.greek-added} αυτων [συζητουντων]{.greek-omitted} [συνζητουντων]{.greek-added} [ειδως]{.greek-omitted} [ιδων]{.greek-added} οτι καλως [απεκριθει]{.greek-added} αυτοις [απεκριθη]{.greek-omitted} επηρωτησεν αυτον ποια εστιν πρωτη [παντων]{.greek-omitted} εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} [απεκριθη]{.greek-omitted} [ειπεν]{.greek-added} αυτω [οτι]{.greek-omitted} [πρωτη]{.greek-omitted} παντων [πρωτον]{.greek-added} [των]{.greek-omitted} [εντολων]{.greek-omitted} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη [εντολη]{.greek-omitted}[12:30]{.aside}

και δευτερα ομοια αυτη [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} τον πλησιον σου ως [εαυτον]{.greek-added} [σεαυτον]{.corr} μειζων τουτων αλλη εντολη ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις εστιν [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον εστιν παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} [ιδων]{.greek-omitted} [ιδως]{.greek-added} [αυτον]{.greek-omitted} οτι [νουνεχως]{.greek-omitted} [συναιτως]{.greek-added} απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον [τι]{.greek-added} [επερωτησαι]{.greek-omitted} [επερωταν]{.greek-added}[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} εστιν [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος [γαρ]{.greek-omitted} [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου [υποποδιον]{.greek-omitted} [υποκατω]{.greek-added} των ποδων σου[12:36]{.aside}

αυτος [ουν]{.greek-omitted} [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και [ποθεν]{.greek-omitted} [πως]{.greek-added} [υιος]{.greek-abbr} αυτου εστιν και [ο]{.greek-omitted} πολυς οχλος ηκουεν [ιδεως]{.greek-added} αυτου [ηδεως]{.greek-omitted}[12:37]{.aside}

και ελεγεν [αυτοις]{.greek-omitted} εν τη διδαχη αυτου [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} απο των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και [πρωτοκαθεδριας]{.greek-omitted} [πρωτοκαθεδριαις]{.greek-added} εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις [δειπνοις]{.greek-omitted} [διπνοις]{.greek-added}[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και [ορφανων]{.greek-added} [και]{.greek-added} προφασει μακρα προσευχομενοι [ουτοι]{.greek-omitted} [οιτινες]{.greek-added} ληψονται περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [εστως]{.greek-added} ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει [τον]{.greek-added} χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη εβαλεν λεπτα δυο ο εστιν [κοδραντης]{.greek-omitted} [κοδραντις]{.greek-added}[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι [αυτη]{.greek-added} η χηρα [αυτη]{.greek-omitted} η πτωχη πλειον παντων βεβληκεν [των]{.greek-omitted} [βαλλοντων]{.greek-omitted} εις το γαζοφυλ[α]{.greek-supplied}κιον[12:43]{.aside}

παντες γαρ εκ του περισσευ[ον]{.greek-supplied}τος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις [εκ]{.greek-added} των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας [αμην]{.greek-added} [λεγω]{.greek-added} [σοι]{.greek-added} ου μη αφεθη [ωδε]{.greek-added} λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου [επηρωτων]{.greek-omitted} [επηρωτα]{.greek-added} αυτον κατ ιδιαν πετρος και [ιωαννης]{.greek-added} [και]{.greek-added} ιακωβος και [ιωαννης]{.greek-omitted} [και]{.greek-omitted} ανδρεας[13:3]{.aside}

[ειπε]{.greek-omitted} [ειπον]{.greek-added} ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [συντελεισθαι]{.greek-omitted} [συντελισθαι]{.greek-added}[13:4]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} αποκριθεις αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ηρξατο λεγειν [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} μη τις υμας [πλανηση]{.greek-omitted} [πλανησει]{.greek-added}[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} και πολλους πλανησουσιν[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουσηται]{.greek-added} πολεμους και ακοας πολεμων μη [θροεισθε]{.greek-omitted} [θρωεισθαι]{.greek-added} [δει]{.greek-omitted} [δι]{.greek-added} γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος [επι]{.greek-omitted} [επ]{.greek-added} εθνος και βασιλεια επι βασιλειαν και εσονται [σεισμοι]{.greek-omitted} [σισμοι]{.greek-added} κατα τοπους [και]{.greek-omitted} εσονται λιμοι και ταραχαι [αρχαι]{.greek-omitted} [ταυτα]{.greek-added} [δε]{.greek-added} [παντα]{.greek-added} [αρχη]{.greek-added} ωδινων [ταυτα]{.greek-omitted}[13:8]{.aside}

[και]{.greek-added} [βλεπετε]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [εαυτους]{.greek-omitted} παραδωσουσιν [γαρ]{.greek-omitted} υμας εις συνεδρια και εις συναγωγας [δαρησεσθε]{.greek-omitted} [δαρησεσθαι]{.greek-added} και επι ηγεμονων και βασιλεων [σταθησεσθε]{.greek-omitted} [σταθησεσθαι]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη [πρωτον]{.greek-added} δει [πρωτον]{.greek-omitted} κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη προμεριμνατε [μηδε]{.greek-added} [μελετατε]{.greek-added} τι λαλησητε [μηδε]{.greek-omitted} [μελετατε]{.greek-omitted} αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα [τουτο]{.greek-omitted} [εκεινο]{.greek-added} λαλειτε ου γαρ [εστε]{.greek-omitted} [εσται]{.greek-added} υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως το ρηθεν [υπο]{.greek-omitted} [δια]{.greek-added} δανιηλ του προφητου [εστως]{.greek-omitted} [στηκον]{.greek-added} οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη [μη]{.greek-added} καταβατω εις την οικιαν μηδε [εισελθετω]{.greek-omitted} [εισελθατω]{.greek-added} αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον [ων]{.greek-omitted} μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις [εν]{.greek-omitted} [γαστρι]{.greek-omitted} [εγγαστρι]{.greek-added} εχουσαις και ταις [θηλαζουσαις]{.greek-omitted} [θηλαζομεναις]{.greek-added} εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται [ταυτα]{.greek-added} [η]{.greek-omitted} [φυγη]{.greek-omitted} [υμων]{.greek-omitted} [χειμωνος]{.greek-omitted} [χιμονος]{.greek-added}[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι [θλιψις]{.greek-omitted} [θλιψης]{.greek-added} οια ου γεγονεν τοιαυτη απ αρχης [ην]{.greek-added} [κτισεως]{.greek-omitted} [ης]{.greek-omitted} [εκτισεν]{.greek-omitted} [εκτησεν]{.greek-added} ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-omitted} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} εκολοβωσεν τας ημερας ουκ αν εσωθη πασα σαρξ [αλλα]{.greek-omitted} δια [δε]{.greek-added} τους εκλεκτους ους εξελεξατο εκολοβωσεν τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η [ιδου]{.greek-omitted} [ιδε]{.greek-added} εκει μη [πιστευετε]{.greek-omitted} [πιστευσηται]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [ποιησουσιν]{.greek-added} [σημεια]{.greek-omitted} [σημια]{.greek-added} και τερατα πρ[ος]{.greek-supplied} [τ]{.unclear}ο [αποπλαναν]{.greek-omitted} [πλανησαι]{.greek-added} ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε [ιδου]{.greek-omitted} προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την [θλιψιν]{.greek-omitted} [θλιψην]{.greek-added} εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες [εκ]{.greek-added} του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν [νεφελαις]{.greek-omitted} [νεφελη]{.greek-added} μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου και [επισυναξει]{.greek-omitted} [επισυνστρεψουσιν]{.greek-added} τους εκλεκτους [αυτου]{.greek-omitted} εκ των τεσσαρων ανεμων [απ]{.greek-omitted} [απο]{.greek-added} ακρου [της]{.greek-added} γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης ηδη ο κλαδος [γενηται]{.greek-added} απαλος [γενηται]{.greek-omitted} και εκφυη τα φυλλα [εν]{.greek-added} [αυτη]{.greek-added} [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν ταυτα ιδητε γινομενα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη [εως]{.greek-added} [αν]{.greek-added} [η]{.greek-omitted} [γενεα]{.greek-omitted} [αυτη]{.greek-omitted} [μεχρι]{.greek-omitted} [ου]{.greek-omitted} παντα [γενηται]{.greek-added} ταυτα [γενηται]{.greek-omitted}[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [των]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε [αγρυπνειτε]{.greek-omitted} [δε]{.greek-added} και [αγρυπνητε]{.greek-added} [και]{.greek-added} [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

[ως]{.greek-omitted} [ωσπερ]{.greek-added} [γαρ]{.greek-added} [ανθρωπος]{.greek-abbr} [αποδημος]{.greek-omitted} [αποδημων]{.greek-added} [αφεις]{.greek-omitted} [αφης]{.greek-added} την [οικιαν]{.greek-omitted} [οικηαν]{.greek-added} αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω [θυρωρω]{.greek-omitted} [θυρορω]{.greek-added} ενετειλατο ινα [γρηγορη]{.greek-omitted} [γρηγορει]{.greek-added}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο κυριος της οικιας ερχεται [οψε]{.greek-omitted} [οψαι]{.greek-added} η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω πασιν λεγω [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added}[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον [εν]{.greek-omitted} δολω [κρατησαντες]{.greek-omitted} [κρατησωσιν]{.greek-added} [και]{.greek-added} [αποκτεινωσιν]{.greek-omitted} [αποκτηνωσιν]{.greek-added}[14:1]{.aside}

[ελεγον]{.greek-omitted} [ελεγων]{.greek-added} δε μη εν τη εορτη μηποτε θορυβος [εσται]{.greek-omitted} [γενηται]{.greek-added} του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν τη οικια σιμωνος του λεπρου κατακειμενου αυτου ηλθεν γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης [πολυτελους]{.greek-omitted} [πολυτιμου]{.greek-added} και συντριψασα [το]{.greek-omitted} [τον]{.greek-added} αλαβαστρον κατεχεεν αυτου [κατα]{.greek-omitted} της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους [και]{.greek-omitted} λεγοντες εις τι η [απωλεια]{.greek-omitted} [απωλια]{.greek-added} αυτη του μυρου [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added}[14:4]{.aside}

ηδυνατο γαρ [το]{.greek-added} [μυρον]{.greek-added} τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αφετε]{.greek-omitted} [αφεται]{.greek-added} αυτην τι αυτη κοπους [παρεχετε]{.greek-omitted} [παρεχεται]{.greek-added} καλον [γαρ]{.greek-added} εργον [ειργασατο]{.greek-omitted} [ηργασατο]{.greek-added} εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους [εχετε]{.greek-omitted} [εχεται]{.greek-added} μεθ εαυτων και οταν [θελητε]{.greek-omitted} [θελεται]{.greek-added} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} αυτους ευ [ποιησαι]{.greek-omitted} [ποιεισαι]{.greek-added} εμε δε ου παντοτε [εχετε]{.greek-omitted} [εχεται]{.greek-added}[14:7]{.aside}

ο [ηχεν]{.greek-added} [εσχεν]{.greek-omitted} [αυτη]{.greek-omitted} εποιησεν προελαβεν μυρισαι μου το σωμα εις τον ενταφιασμον [μου]{.greek-added}[14:8]{.aside}

αμην [γαρ]{.greek-added} λεγω υμιν οπου [εαν]{.greek-omitted} [αν]{.greek-added} κηρυχθη το ευαγγελιον [τουτο]{.greek-omitted} εις ολον τον κοσμον και ο εποιησεν [αυ]{.unclear}τη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας [ο]{.greek-omitted} ισκαριωτης εις των δωδεκα απηλθεν προς τους αρχιερεις ινα [παραδω]{.greek-omitted} [παραδοι]{.greek-added} αυτον [αυτοις]{.greek-omitted}[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο αυτω αργυριον δουναι και [εζητει]{.greek-omitted} [εζητη]{.greek-added} πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και [εισελθοντων]{.greek-added} [υμων]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [πολιν]{.greek-added} [απαντησει]{.greek-omitted} [υπαντισει]{.greek-added} υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζ[ω]{.unclear}ν ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που εστιν το καταλυμα [μου]{.greek-added} οπου το πασχα μετα των μαθητων μου [φαγω]{.greek-omitted} [φαγωμαι]{.greek-added}[14:14]{.aside}

και αυτος υμιν [δειξει]{.greek-omitted} [διξει]{.greek-added} [ανωγεον]{.greek-omitted} [αναγαιον]{.greek-added} μεγα εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον [ετοιμασαι]{.greek-added} [αυτω]{.greek-added} οι μαθηται [αυτου]{.greek-omitted} και ηλθον εις την πολιν και [ευρον]{.greek-omitted} [ηυρον]{.greek-added} καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και [εσθιοντων]{.greek-omitted} [αισθιοντων]{.greek-added} ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο [λυπεισθαι]{.greek-omitted} [λυπεισθε]{.greek-added} και λεγειν αυτω εις καθ εις μητι εγω [ειμι]{.greek-added} και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω [ει]{.greek-omitted} [η]{.greek-added} ουκ [εγεννηθη]{.greek-omitted} [εγενηθη]{.greek-added} ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας εκλασεν και εδωκεν αυτοις και ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[14:22]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον ευχαριστησας εδωκεν αυτοις και επιον [παντες]{.greek-added} εξ αυτου [παντες]{.greek-omitted}[14:23]{.aside}

και ειπεν αυτοις τουτο εστιν το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεσθαι]{.greek-added} εν εμοι [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη [νυκτη]{.greek-added} [νυκτι]{.corr} ταυτη πριν η δις αλεκτορα φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με[14:30]{.aside}

ο δε [πετρος]{.greek-added} εκπερισσου ελεγεν μαλλον εαν με δεη συναποθανειν σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσιμανη]{.greek-added} και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε εως [αν]{.greek-added} [απελθων]{.greek-added} προσευξωμαι [εκει]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε [μετ]{.greek-added} [εμου]{.greek-added}[14:34]{.aside}

και προσελθων μικρον επεσεν επι [της]{.greek-omitted} [γης]{.greek-omitted} [προσωπον]{.greek-added} [αυτου]{.greek-added} και προσηυχετο ινα ει δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι [παρενεγκε]{.greek-omitted} [παρενενκε]{.greek-added} το ποτηριον απ εμου τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ ηδεισαν τι αυτω αποκριθωσιν[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις ων των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και των γραμματεων και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο [παραδιδους]{.greek-omitted} [παραδηδους]{.greek-added} αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και [απαγαγετε]{.greek-omitted} [απαγετε]{.greek-added} ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας [αυτων]{.greek-omitted} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των [παρεστηκοτων]{.greek-omitted} [παρεστικοτων]{.greek-added} σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επεσε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ [ευρισκον]{.greek-omitted} [ευρον]{.greek-added}[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις [μεσον]{.greek-omitted} [μεσων]{.greek-added} επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων [ουκ]{.greek-omitted} [ουδεν]{.greek-added} αποκρινη [ουδεν]{.greek-omitted} τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [ευλογητου]{.greek-omitted} [ευλογημενου]{.greek-added}[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον [μετα]{.greek-omitted} [επι]{.greek-added} των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν [φαινεται]{.greek-omitted} [δοκει]{.greek-added} οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον και οι υπηρεται ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον [θερμαινομενον]{.greek-omitted} [θερμενομενον]{.greek-added} εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} επισταμαι τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ εφωνησεν[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ εφωνησεν και ανεμνησθη ο πετρος [το]{.greek-omitted} [του]{.greek-added} [ρημα]{.greek-omitted} [ρηματος]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} ο ειπεν αυτω [ο]{.greek-omitted} [ιησους]{.greek-omitted} οτι πριν αλεκτορα φωνησαι δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν [αυτου]{.greek-omitted} [αυτον]{.greek-added} οι αρχιερεις πολλα[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν [ιδ[υο]{.unclear}]{.greek-added} [οσα]{.greek-added} [ιδε]{.corr} [ποσα]{.corr} σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} ωστε θαυμαζειν τον [πιλατων]{.greek-added} [πιλατον]{.corr}[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον [πεποιηκεισαν]{.greek-omitted} [πεποιηκαν]{.greek-added}[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

εγινωσκεν γαρ οτι δια φθονον παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεσισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν σταυρωσον [σταυρωσον]{.greek-added} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε περισσοτερως εκραξαν σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και παρεδωκεν τον [ιησουν]{.greek-abbr} φραγελλωσας ινα σταυρωθη[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [πραιτωριον]{.greek-omitted} [πραιτοριον]{.greek-added} και συγκαλουσιν [ολην]{.greek-omitted} [ολιν]{.greek-added} την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο [ασπαζεσθαι]{.greek-omitted} [ασπαζεσθε]{.greek-added} αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωθη]{.greek-added} [σταυρωσωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[15:20]{.aside}

και αγγαρευουσιν παραγοντα τινα σιμωνα [κυρηναιον]{.greek-omitted} [κυριναιον]{.greek-added} ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο εστιν μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ ελαβεν[15:23]{.aside}

και σταυρωσαντες αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-abbr} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και [εν]{.greek-omitted} τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [ενπαιζοντες]{.greek-added} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και [πιστευσω]{.greek-added} [πιστευσωμεν]{.corr} [αυ[τω]{.greek-supplied}]{.corr} και οι συνεσταυρωμενοι αυτω [ωνειδιζον]{.greek-omitted} [ονειδιζον]{.greek-added} [αυτον]{.greek-omitted} [αυτω]{.greek-added}[15:32]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και τη ωρα τη ενατη εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λειμα]{.greek-added} σαβαχθανι ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των [παρεστηκοτων]{.greek-omitted} [παρεστικοτων]{.greek-added} ακουσαντες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και [γεμισας]{.greek-omitted} [γεμησας]{.greek-added} σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} [λοιποι]{.greek-added} [ελεγον]{.greek-added} [αφες]{.greek-added} ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο [κεντυριων]{.greek-omitted} [κεντυριον]{.greek-added} ο [παρεστηκως]{.greek-omitted} [παρεστικως]{.greek-added} εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} θεωρουσαι εν αις ην [μαρια]{.greek-added} [η]{.greek-added} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου του μικρου και [ιωση]{.greek-omitted} [ιοση]{.greek-added} [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω [διακονουσαι]{.greek-added} [και]{.greek-omitted} [διηκονουν]{.greek-omitted} αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και [ηδη]{.greek-omitted} [ιδη]{.greek-added} οψιας γενομενης επει ην παρασκευη ο εστιν [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

ηλθεν ιωσηφ [ο]{.greek-omitted} απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας εισηλθεν προς πιλατον και [ητησατο]{.greek-omitted} [ητισατο]{.greek-added} [το]{.greek-added} το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απαθανεν]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω [ιωσηφ]{.greek-omitted} [ισηφ]{.greek-added}[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισεν]{.greek-added} [αυτον]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν [μνημειω]{.greek-omitted} [μνημιω]{.greek-added} ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλησε]{.greek-added} λιθον επι την θυραν του [μνημειου]{.greek-omitted} [μνημιου]{.greek-added}[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις [αποκυλισει]{.greek-omitted} [αποκυλησει]{.greek-added} ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις [περιβεβλημενον]{.greek-omitted} [περιβεβλημμενον]{.greek-added} στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβεισθαι]{.greek-added} [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον εσταυρωμενον ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου ειχεν δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι πρωτη [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα απηγγειλεν τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ονειδησεν]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον [εγηγερμενον]{.greek-omitted} [εγειγερμενον]{.greek-added} [εκ]{.greek-added} [νεκρων]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη [κτισει]{.greek-omitted} [κτησει]{.greek-added}[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε [απιστησας]{.greek-omitted} [απιστισας]{.greek-added} κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια εκβαλουσιν γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις αρουσιν καν θανασιμον τι πιωσιν ου μη αυτους [βλαψη]{.greek-omitted} [βλαψει]{.greek-added} επι αρρωστους χειρας επιθησουσιν και καλως [εξουσιν]{.greek-omitted} [εξουσι]{.greek-added}[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ανεληφθη εις τον [ουρανον]{.greek-abbr} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

