---
title: "Collation of Byz^RP^ vs 30091 (91)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 91 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30091).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 91                                   	| λογος                              	|
| 91 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 91 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 91               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 91                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 91 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 91                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου [τω]{.greek-omitted} [τωι]{.greek-added} [δουλω]{.greek-omitted} [δουλωι]{.greek-added} αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [οσα]{.greek-omitted} [ειδεν]{.greek-omitted} [ιωαννου]{.greek-added} [μυησις]{.greek-added} [η]{.greek-added} [κεκρυμμενη]{.greek-added}[1:2]{.aside}

[ος]{.greek-omitted} [εμαρτυρησεν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} οσα ειδεν[1:2 | instance no. 2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-omitted} [του]{.greek-added} ο ων και ο ην και ο ερχομενος και απο των επτα πνευματων α ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [ο]{.greek-omitted} [πιστος]{.greek-omitted} [ο]{.greek-omitted} [πρωτοτοκος]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αρχων]{.greek-omitted} [των]{.greek-omitted} [βασιλεων]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [τω]{.greek-omitted} [αγαπωντι]{.greek-omitted} [ημας]{.greek-omitted} [και]{.greek-omitted} [λουσαντι]{.greek-omitted} [ημας]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [αμαρτιων]{.greek-omitted} [ημων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αιματι]{.greek-omitted} [αυτου]{.greek-omitted}[1:5]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} ο μαρτυς ο πιστος ο πρωτοτοκος των νεκρων και ο αρχων των βασιλεων της γης τω αγαπωντι ημας και λουσαντι ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5 | instance no. 2]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου [αυτω]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [κρατος]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [αμην]{.greek-omitted}[1:6]{.aside}

[και]{.greek-omitted} [εποιησεν]{.greek-omitted} [ημας]{.greek-omitted} [βασιλειαν]{.greek-omitted} [ιερεις]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [και]{.greek-omitted} [πατρι]{.greek-omitted} [αυτου]{.greek-omitted} αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6 | instance no. 2]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [[ἄλφα]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και κοινωνος εν τη θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και [δια]{.greek-omitted} την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-omitted} [πνι]{.greek-added} εν τη κυριακη ημερα και ηκουσα φωνην οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις σμυρναν και εις περγαμον και εις θυατειρα και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

[και]{.greek-omitted} εκει επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας [λβ]{.greek-added}[1:12]{.aside}

και εν μεσω των επτα λυχνιων ομοιον [υιω]{.greek-omitted} [υιον]{.greek-added} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω [ως]{.corr} [εν]{.corr} [καμινω]{.corr} [[πε]{.corr}]{.greek-added} [πεπυρωμενοι]{.greek-omitted} [[πυρωμενοι]{.corr}]{.greek-added} [και]{.corr} [η]{.corr} [φωνη]{.corr} [αυτου]{.corr} [ως]{.corr} [φωνη]{.corr} [υδατων]{.corr} [πολλων]{.corr} [λγ]{.greek-added}[1:15]{.aside}

και εχων εν τη δεξια [χειρι]{.greek-added} αυτου [χειρι]{.greek-omitted} αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον [επεσα]{.greek-omitted} [επεσον]{.greek-added} προς τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} την δεξιαν αυτου επ εμε λεγων [μη]{.greek-omitted} [φοβου]{.greek-omitted} [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [εσχατος]{.greek-omitted}[1:17]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ειδον]{.greek-omitted} [αυτον]{.greek-omitted} [επεσα]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [νεκρος]{.greek-omitted} [και]{.greek-omitted} [εθηκεν]{.greek-omitted} [την]{.greek-omitted} [δεξιαν]{.greek-omitted} [αυτου]{.greek-omitted} [επ]{.greek-omitted} [εμε]{.greek-omitted} [λεγων]{.greek-omitted} μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17 | instance no. 2]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας [κλεις]{.greek-omitted} [κλειδας]{.greek-added} του θανατου και του [αδου]{.greek-omitted} [αιδου]{.greek-added}[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας [οι]{.greek-omitted} [επτα]{.greek-omitted} [αστερες]{.greek-omitted} [αγγελοι]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιων]{.greek-omitted} [εισιν]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [λυχνιαι]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαι]{.greek-omitted} [εισιν]{.greek-omitted}[1:20]{.aside}

[το]{.greek-omitted} [μυστηριον]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αστερων]{.greek-omitted} [ων]{.greek-omitted} [ειδες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιας]{.greek-omitted} [τας]{.greek-omitted} [χρυσας]{.greek-omitted} οι επτα αστερες αγγελοι των επτα εκκλησιων [εισιν]{.greek-omitted} [εισι]{.greek-added} και αι λυχνιαι αι επτα επτα εκκλησιαι [εισιν]{.greek-omitted} [εισι]{.greek-added}[1:20 | instance no. 2]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις [και]{.greek-omitted} [εβαστασας]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εκοπιασας]{.greek-omitted}[2:3]{.aside}

[και]{.greek-omitted} [υπομονην]{.greek-omitted} [εχεις]{.greek-omitted} και εβαστασας δια το ονομα μου και ουκ [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3 | instance no. 2]{.aside}

αλλα εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη [μετανοησης]{.greek-omitted} [μετανοησηις]{.greek-added}[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν τω παραδεισω [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted}[2:7]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [τω]{.greek-omitted} [νικωντι]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [φαγειν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [παραδεισω]{.greek-omitted} του θεου μου[2:7 | instance no. 2]{.aside}

και τω αγγελω της εν [σμυρνη]{.greek-omitted} [σμουρνηι]{.greek-added} εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος [ος]{.greek-omitted} εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν εκ των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις παθειν ιδου δη μελλει [βαλειν]{.greek-omitted} [βαλεῖν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν [ημερων]{.greek-omitted} [ημερας]{.greek-added} δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις [ο]{.greek-omitted} [νικων]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [αδικηθη]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [του]{.greek-omitted} [δευτερου]{.greek-omitted}[2:11]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted} ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11 | instance no. 2]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις [εν]{.greek-omitted} αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς μου ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} και φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω [[απο]{.corr}]{.greek-added} του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου [ομοιοι]{.greek-omitted} [ομοιον]{.greek-added} χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα [πλειονα]{.greek-omitted} [χειρονα]{.greek-added} των πρωτων[2:19]{.aside}

αλλ εχω κατα σου οτι αφεις την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει [και]{.greek-omitted} [πλανα]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [δουλους]{.greek-omitted} [πορνευσαι]{.greek-omitted} [και]{.greek-omitted} [φαγειν]{.greek-omitted} [ειδωλοθυτα]{.greek-omitted}[2:20]{.aside}

[αλλ]{.greek-omitted} [εχω]{.greek-omitted} [κατα]{.greek-omitted} [σου]{.greek-omitted} [οτι]{.greek-omitted} [αφεις]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [σου]{.greek-omitted} [ιεζαβελ]{.greek-omitted} [η]{.greek-omitted} [λεγει]{.greek-omitted} [εαυτην]{.greek-omitted} [προφητιν]{.greek-omitted} [και]{.greek-omitted} [διδασκει]{.greek-omitted} και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20 | instance no. 2]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις [τοις]{.greek-omitted} [εν]{.greek-omitted} [θυατειροις]{.greek-omitted} [οσοι]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [την]{.greek-omitted} [διδαχην]{.greek-omitted} [ταυτην]{.greek-omitted} [οιτινες]{.greek-omitted} [ουκ]{.greek-omitted} [εγνωσαν]{.greek-omitted} [τα]{.greek-omitted} [βαθεα]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [ως]{.greek-omitted} [λεγουσιν]{.greek-omitted} [ου]{.greek-omitted} [βαλλω]{.greek-omitted} [εφ]{.greek-omitted} [υμας]{.greek-omitted} [αλλο]{.greek-omitted} [βαρος]{.greek-omitted}[2:24]{.aside}

[υμιν]{.greek-omitted} [δε]{.greek-omitted} [λεγω]{.greek-omitted} [τοις]{.greek-omitted} [λοιποις]{.greek-omitted} τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24 | instance no. 2]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [ανοιξω]{.greek-added} [αν]{.greek-omitted} [ηξω]{.greek-omitted}[2:25]{.aside}

και ο νικων και ο τηρων [αχρι]{.greek-omitted} [τελους]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [μου]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσιαν]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted}[2:26]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [νικων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [τηρων]{.greek-omitted} αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26 | instance no. 2]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα [κεραμικα]{.greek-omitted} [κεραμεικα]{.greek-added} συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα πνευματα του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [και]{.greek-added} ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και στηρισον τα λοιπα α εμελλες αποβαλλειν ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας [και]{.greek-omitted} [ηκουσας]{.greek-omitted} [και]{.greek-omitted} [τηρει]{.greek-omitted} και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη γνως ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} [αυτου]{.greek-omitted}[3:5]{.aside}

[ο]{.greek-omitted} [νικων]{.greek-omitted} [ουτος]{.greek-omitted} [περιβαλειται]{.greek-omitted} [εν]{.greek-omitted} [ιματιοις]{.greek-omitted} [λευκοις]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [εξαλειψω]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [βιβλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [και]{.greek-omitted} [ομολογησω]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5 | instance no. 2]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει αυτην [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [ανοιξει]{.greek-omitted}[3:7]{.aside}

[και]{.greek-omitted} [τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [φιλαδελφεια]{.greek-omitted} [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [ο]{.greek-omitted} [αληθινος]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [την]{.greek-omitted} [κλειν]{.greek-omitted} [του]{.greek-omitted} [δαυιδ]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [κλεισει]{.greek-omitted} [αυτην]{.greek-omitted} ει μη ο ανοιγων και ουδεις ανοιξει[3:7 | instance no. 2]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας [τον]{.greek-omitted} [λογον]{.greek-omitted} [της]{.greek-omitted} [υπομονης]{.greek-omitted} [μου]{.greek-omitted} [καγω]{.greek-omitted} [σε]{.greek-omitted} [τηρησω]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [ωρας]{.greek-omitted} [του]{.greek-omitted} [πειρασμου]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [οικουμενης]{.greek-omitted} [ολης]{.greek-omitted} [πειρασαι]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[3:10]{.aside}

[οτι]{.greek-omitted} [ετηρησας]{.greek-omitted} τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10 | instance no. 2]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα [μου]{.greek-omitted} το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν λαοδικεια εκκλησιας γραψον [λγ]{.greek-added} [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [αμην]{.greek-omitted} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [ο]{.greek-omitted} [πιστος]{.greek-omitted} [και]{.greek-omitted} [αληθινος]{.greek-omitted} [η]{.greek-omitted} [αρχη]{.greek-omitted} [της]{.greek-omitted} [κτισεως]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[3:14]{.aside}

[και]{.greek-omitted} [τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [λαοδικεια]{.greek-omitted} [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14 | instance no. 2]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος οφελον ψυχρος ης η ζεστος [λδ]{.greek-added}[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις [οτι]{.greek-added} πλουσιος ειμι και πεπλουτηκα και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και [ο]{.greek-omitted} ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι χρυσιον παρ εμου πεπυρωμενον εκ πυρος ινα [πλουτησης]{.greek-omitted} [πλουτησηις]{.greek-added} και ιματια λευκα ινα [περιβαλη]{.greek-omitted} [περιβαλλη]{.greek-added} και μη φανερωθη η αισχυνη της γυμνοτητος σου και [κολλυριον]{.greek-omitted} [κολλουριον]{.greek-added} ινα [εγχριση]{.greek-omitted} [εγχρισηι]{.greek-added} τους οφθαλμους σου ινα [βλεπης]{.greek-omitted} [βλεπηις]{.greek-added}[3:18]{.aside}

[εγω]{.greek-omitted} [και]{.greek-added} οσους εαν φιλω ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλευε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν και εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων [δωσω]{.greek-omitted} [δωσωι]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} καθισαι μετ εμου εν [τω]{.greek-omitted} [τωι]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

[και]{.greek-omitted} ευθεως εγενομην εν πνευματι και ιδου θρονος εκειτο εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και επι τον θρονον καθημενος[4:2]{.aside}

ομοιος ορασει [λιθω]{.greek-omitted} [λιθωι]{.greek-added} ιασπιδι και [σαρδιω]{.greek-omitted} [σαρδιωι]{.greek-added} [και]{.greek-omitted} [ιρις]{.greek-omitted} [κυκλοθεν]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [ομοιως]{.greek-omitted} [ορασις]{.greek-omitted} [σμαραγδινων]{.greek-omitted}[4:3]{.aside}

[κ]{.greek-added} [ομοιος]{.greek-omitted} [ορασει]{.greek-omitted} [λιθω]{.greek-omitted} [ιασπιδι]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-added} [σαρδιω]{.greek-omitted} [και]{.greek-omitted} [ιρις]{.greek-omitted} [ἶρις]{.greek-added} κυκλοθεν του θρονου ομοιως ορασις [σμαραγδινων]{.greek-omitted} [σμαραγδινω]{.greek-added}[4:3 | instance no. 2]{.aside}

[και]{.greek-omitted} κυκλοθεν του θρονου θρονοι εικοσι τεσσαρες και επι τους θρονους τους εικοσι τεσσαρας πρεσβυτερους καθημενους [περιβεβλημενους]{.greek-omitted} [περιβεβλημενοις]{.greek-added} εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα πνευματα του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου [ως]{.greek-omitted} [θαλασσα]{.greek-omitted} [υαλινη]{.greek-omitted} [ομοια]{.greek-omitted} [κρυσταλλω]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [κυκλω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [τεσσαρα]{.greek-omitted} [ζωα]{.greek-omitted} [γεμοντα]{.greek-omitted} [οφθαλμων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [και]{.greek-omitted} [οπισθεν]{.greek-omitted}[4:6]{.aside}

[και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} ως θαλασσα υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6 | instance no. 2]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον [μοσχω]{.greek-omitted} [μοσχωι]{.greek-added} και το τριτον ζωον εχον [το]{.greek-added} προσωπον [ανθρωπου]{.greek-abbr} και το τεταρτον [ζωον]{.greek-omitted} ομοιον αετω [πετομενω]{.greek-omitted} [πετομενωι]{.greek-added}[4:7]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα εν καθ εν εχον ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσι]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επι του θρονου [τω]{.greek-omitted} [τωι]{.greek-added} ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} ζωντι εις τους αιωνας των αιωνων [και]{.greek-omitted} [βαλουσιν]{.greek-omitted} [τους]{.greek-omitted} [στεφανους]{.greek-omitted} [αυτων]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [λεγοντες]{.greek-omitted}[4:10]{.aside}

[πεσουνται]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} και [προσκυνησουσιν]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [και]{.greek-omitted} [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10 | instance no. 2]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας παντα και δια το θελημα σου ησαν και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο εν τω [ουρανω]{.greek-abbr} ανω ουτε επι της γης ουτε υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} ο ανοιγων το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως εσφαγμενον εχον κερατα επτα και οφθαλμους επτα α [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα πνευματα [του[θεου]{.greek-abbr}]{.greek-added} [του]{.greek-omitted} [θεου]{.greek-omitted} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι [επεσον]{.greek-omitted} [επεσoν]{.greek-added} ενωπιον του αρνιου εχοντες εκαστος κιθαραν και φιαλας χρυσας γεμουσας θυμιαματων αι [εισιν]{.greek-omitted} [εισι]{.greek-added} [αι]{.greek-added} [προσευχαι]{.greek-omitted} [προσευχων]{.greek-added} των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} ημας εν [τω]{.greek-omitted} [τωι]{.greek-added} αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} ημων βασιλεις και ιερεις [και]{.greek-omitted} [βασιλευσουσιν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[5:10]{.aside}

[και]{.greek-omitted} [εποιησας]{.greek-omitted} [αυτους]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [ημων]{.greek-omitted} [βασιλεις]{.greek-omitted} [και]{.greek-omitted} [ιερεις]{.greek-omitted} και βασιλευσουσιν επι της γης[5:10 | instance no. 2]{.aside}

και ειδον και ηκουσα ως φωνην αγγελων πολλων [κυκλω]{.greek-omitted} [κυκλωι]{.greek-added} του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και τον πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και επι της γης και υποκατω της γης και επι της θαλασσης [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις παντας ηκουσα λεγοντας [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τωι]{.greek-added} [θρονωι]{.greek-added} και [τω]{.greek-omitted} [τωι]{.greek-added} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added} η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13]{.aside}

και τα τεσσαρα ζωα λεγοντα το αμην και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνὴ]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ιδε]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} στεφανος και εξηλθεν νικων και ινα [νικηση]{.greek-omitted} [νικησει]{.greek-added}[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την δευτεραν σφραγιδα ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος [πυρος]{.greek-omitted} [πυρρος]{.greek-added} και [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επ αυτον εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} λαβειν την ειρηνην εκ της γης ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και ιδε και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες κριθης δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ιδε]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο [αδης]{.greek-omitted} [αιδης]{.greek-added} ηκολουθει [αυτω]{.greek-omitted} [αυτων]{.greek-added} και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν [λιμω]{.greek-omitted} [λιμωι]{.greek-added} και εν [θανατω]{.greek-omitted} [θανατωι]{.greek-added} και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα [ειδον]{.greek-omitted} [υποκατω]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [τας]{.greek-omitted} [ψυχας]{.greek-omitted} [των]{.greek-omitted} [εσφαγμενων]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [ην]{.greek-omitted} [ειχον]{.greek-omitted}[6:9]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [πεμπτην]{.greek-omitted} [σφραγιδα]{.greek-omitted} ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν του αρνιου ην ειχον[6:9 | instance no. 2]{.aside}

και εκραξαν [φωνη]{.greek-omitted} [φωνην]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαλην]{.greek-added} λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις [εκαστω]{.greek-omitted} στολη λευκη και ερρεθη αυτοις ινα αναπαυσωνται ετι χρονον εως [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος μελας εγενετο [ως]{.greek-omitted} [σακκος]{.greek-omitted} [τριχινος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [ολη]{.greek-omitted} [εγενετο]{.greek-omitted} [ως]{.greek-omitted} [αιμα]{.greek-omitted}[6:12]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [την]{.greek-omitted} [εκτην]{.greek-omitted} [και]{.greek-omitted} [σεισμος]{.greek-omitted} [μεγας]{.greek-omitted} [εγενετο]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [μελας]{.greek-omitted} [εγενετο]{.greek-omitted} ως σακκος τριχινος και η σεληνη ολη εγενετο [ως]{.greek-omitted} [εις]{.greek-added} αιμα[6:12 | instance no. 2]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη βαλουσα τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ελισσομενος]{.greek-added} και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται [σταθηναι]{.greek-omitted} [σωθηναι]{.greek-added}[6:17]{.aside}

### Chapter 7

και μετα τουτο ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους τεσσαρας ανεμους της γης ινα μη πνεη ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον [λδ]{.greek-added}[7:1]{.aside}

και ειδον [αγγελον]{.greek-added} αλλον [αγγελον]{.greek-omitted} αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [σφραγισωμεν]{.greek-omitted} [σφραγισομεν]{.greek-added} τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον [[μ]{.greek-abbr}]{.greek-added} [και]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} τεσσαρες χιλιαδες εσφραγισμενων εκ πασης φυλης υιων [ισραηλ]{.greek-abbr} [λε]{.greek-added}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες εσφραγισμεναι εκ φυλης [ρουβιμ]{.greek-omitted} [ρουβειμ]{.greek-added} δωδεκα χιλιαδες εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ δωδεκα χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι δωδεκα χιλιαδες εκ φυλης ισαχαρ δωδεκα χιλιαδες[7:7]{.aside}

εκ φυλης [ζαβουλων]{.greek-omitted} [ιωσηφ]{.greek-added} δωδεκα χιλιαδες εκ φυλης [ιωσηφ]{.greek-omitted} [ζαβουλων]{.greek-added} δωδεκα χιλιαδες εκ φυλης βενιαμιν δωδεκα χιλιαδες εσφραγισμεναι[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις εδυνατο εκ παντος εθνους και φυλων και λαων [και]{.greek-omitted} γλωσσων [εστωτας]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [περιβεβλημενους]{.greek-omitted} [στολας]{.greek-omitted} [λευκας]{.greek-omitted} [και]{.greek-omitted} [φοινικας]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [χερσιν]{.greek-omitted} [αυτων]{.greek-omitted}[7:9]{.aside}

[μετα]{.greek-omitted} [ταυτα]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [ον]{.greek-omitted} [αριθμησαι]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [εκ]{.greek-omitted} [παντος]{.greek-omitted} [εθνους]{.greek-omitted} [και]{.greek-omitted} [φυλων]{.greek-omitted} [και]{.greek-omitted} [λαων]{.greek-omitted} [και]{.greek-omitted} [γλωσσων]{.greek-omitted} [εστωτας]{.greek-omitted} [εστωτες]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου περιβεβλημενους στολας λευκας και φοινικας εν ταις χερσιν αυτων[7:9 | instance no. 2]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η σωτηρια [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} ημων τω καθημενω επι [τω]{.greek-omitted} [τωι]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} και [τω]{.greek-omitted} [τωι]{.greek-added} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added}[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου [αυτου]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} κυριε μου συ οιδας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν εν [τω]{.greek-omitted} [τωι]{.greek-added} αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ημερας και νυκτος εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} αυτου και ο καθημενος επι [τω]{.greek-omitted} [τωι]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν ετι ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και οδηγει αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην εγενετο σιγη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι του θυσιαστηριου εχων λιβανωτον χρυσουν και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δωσηι]{.greek-added} ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν [το]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted}[8:3]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [αγγελος]{.greek-omitted} [ηλθεν]{.greek-omitted} [και]{.greek-omitted} [εσταθη]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [εχων]{.greek-omitted} [λιβανωτον]{.greek-omitted} [χρυσουν]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [θυμιαματα]{.greek-omitted} [πολλα]{.greek-omitted} [ινα]{.greek-omitted} [δωση]{.greek-omitted} [ταις]{.greek-omitted} [προσευχαις]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [παντων]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [θυσιαστηριον]{.greek-omitted} [το]{.greek-omitted} [χρυσουν]{.greek-omitted} το ενωπιον του θρονου[8:3 | instance no. 2]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο βρονται και φωναι και αστραπαι [και]{.greek-omitted} [σεισμος]{.greek-omitted}[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας [χορτος]{.greek-omitted} χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} [και]{.greek-omitted} [ως]{.greek-omitted} [ορος]{.greek-omitted} [μεγα]{.greek-omitted} [καιομενον]{.greek-omitted} [εβληθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [αιμα]{.greek-omitted}[8:8]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} και ως ορος [μεγα]{.greek-omitted} [μετα]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8 | instance no. 2]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον των κτισματων εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις [αψινθον]{.greek-omitted} [αψινθιον]{.greek-added} και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

[και]{.greek-omitted} [αι]{.greek-added} ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον [του]{.greek-omitted} [ηλιου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} της σεληνης [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [αστερων]{.greek-omitted} [ινα]{.greek-omitted} [σκοτισθη]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτης]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [νυξ]{.greek-omitted} [ομοιως]{.greek-omitted}[8:12]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [επληγη]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [σεληνης]{.greek-omitted} και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και το τριτον αυτης μη φανη η ημερα και η νυξ ομοιως[8:12 | instance no. 2]{.aside}

και ειδον και ηκουσα ενος αετου πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} η κλεις του φρεατος της αβυσσου[9:1]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} και ανεβη καπνος εκ του φρεατος ως καπνος καμινου καιομενης και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον [ει]{.greek-omitted} [μη]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [οιτινες]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[9:4]{.aside}

[και]{.greek-omitted} [ερρεθη]{.greek-omitted} [αυταις]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [αδικησωσιν]{.greek-omitted} [τον]{.greek-omitted} [χορτον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ουδε]{.greek-omitted} [παν]{.greek-omitted} [χλωρον]{.greek-omitted} [ουδε]{.greek-omitted} [παν]{.greek-omitted} [δενδρον]{.greek-omitted} ει μη τους ανθρωπους οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4 | instance no. 2]{.aside}

και εδοθη αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν παιση [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη ευρησουσιν αυτον και επιθυμησουσιν αποθανειν και φευξεται απ αυτων ο θανατος[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι χρυσοι και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα και εν ταις ουραις αυτων εξουσιαν εχουσιν [του]{.greek-omitted} αδικησαι τους ανθρωπους μηνας πεντε[9:10]{.aside}

εχουσαι βασιλεα επ αυτων αγγελον της αβυσσου ονομα αυτω εβραιστι αββαδων εν δε τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου ερχεται ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγοντος]{.greek-added} τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και [εις]{.greek-omitted} [την]{.greek-omitted} ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του ιππου μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι οφεων εχουσαι κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα [και]{.greek-omitted} [τα]{.greek-omitted} [χαλκα]{.greek-omitted} και τα λιθινα και τα ξυλινα α ουτε βλεπειν δυναται ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και εχων εν τη χειρι αυτου βιβλιον ανεωγμενον [και]{.greek-omitted} [εθηκεν]{.greek-omitted} [τον]{.greek-omitted} [ποδα]{.greek-omitted} [αυτου]{.greek-omitted} [τον]{.greek-omitted} [δεξιον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [τον]{.greek-omitted} [δε]{.greek-omitted} [ευωνυμον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[10:2]{.aside}

και [εχων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτου]{.greek-omitted} [βιβλιον]{.greek-omitted} [ανεωγμενον]{.greek-omitted} [και]{.greek-omitted} [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2 | instance no. 2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν [αι]{.greek-omitted} επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν [σφραγισον]{.greek-omitted} [α]{.greek-omitted} [ελαλησαν]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [βρονται]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [αυτα]{.greek-omitted} [γραψης]{.greek-omitted}[10:4]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ελαλησαν]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [βρονται]{.greek-omitted} [εμελλον]{.greek-omitted} [γραφειν]{.greek-omitted} [και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσαν]{.greek-omitted} σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα [γραψης]{.greek-omitted} [γραψηις]{.greek-added}[10:4 | instance no. 2]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμοσε]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [εστι]{.greek-added} εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν και ετελεσθη το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα μετ εμου και λεγουσα υπαγε [και]{.greek-added} λαβε το βιβλιδαριον το ανεωγμενον εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω δουναι μοι το βιβλιδαριον και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και [κατεφαγον]{.greek-omitted} [κατέφαγον]{.greek-added} αυτο και ην εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι μου ως μελι γλυκυ και οτε [εφαγον]{.greek-omitted} [αυτο]{.greek-omitted} [επικρανθη]{.greek-omitted} [η]{.greek-omitted} [κοιλια]{.greek-omitted} [μου]{.greek-omitted}[10:10]{.aside}

[και]{.greek-omitted} [ελαβον]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [του]{.greek-omitted} [αγγελου]{.greek-omitted} [και]{.greek-omitted} [κατεφαγον]{.greek-omitted} [αυτο]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [μου]{.greek-omitted} [ως]{.greek-omitted} [μελι]{.greek-omitted} [γλυκυ]{.greek-omitted} [και]{.greek-omitted} [οτε]{.greek-omitted} εφαγον αυτο επικρανθη η κοιλια μου[10:10 | instance no. 2]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος [ραβδω]{.greek-omitted} [ραβδωι]{.greek-added} λεγων εγειραι και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε εξω και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} [και]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [αγιαν]{.greek-omitted} [πατησουσιν]{.greek-omitted} [μηνας]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [και]{.greek-omitted} [δυο]{.greek-omitted}[11:2]{.aside}

[και]{.greek-omitted} [την]{.greek-omitted} [αυλην]{.greek-omitted} [την]{.greek-omitted} [εξωθεν]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [εκβαλε]{.greek-omitted} [εξω]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [αυτην]{.greek-omitted} [μετρησης]{.greek-omitted} [οτι]{.greek-omitted} [εδοθη]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα και δυο[11:2 | instance no. 2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα [περιβεβλημενοι]{.greek-omitted} [περιβεβλημενους]{.greek-added} σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-abbr} της γης [εστωσαι]{.greek-omitted} [εστωτες]{.greek-added}[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους αδικησαι [ουτως]{.greek-omitted} [ουτω]{.greek-added} δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον [ουρανον]{.greek-abbr} εξουσιαν κλεισαι ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα [κ]{.greek-added} [και]{.greek-omitted} [αι]{.greek-added} παταξαι την γην οσακις εαν θελησωσιν εν παση πληγη[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το αναβαινον εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και το πτωμα αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματι]{.greek-abbr}κως σοδομα και αιγυπτος [οπου]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [αυτων]{.greek-omitted} [εσταυρωθη]{.greek-omitted}[11:8]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [πτωμα]{.greek-omitted} [αυτων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [πλατειας]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [ητις]{.greek-omitted} [καλειται]{.greek-omitted} [πνευματικως]{.greek-omitted} [σοδομα]{.greek-omitted} [και]{.greek-omitted} [αιγυπτος]{.greek-omitted} οπου και ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8 | instance no. 2]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφησουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και ευφρανθησονται και δωρα δωσουσιν αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν εις αυτους και εστησαν επι τους ποδας αυτων και φοβος μεγας επεσεν επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν [τη]{.greek-omitted} [τηι]{.greek-added} [νεφελη]{.greek-omitted} [νεφεληι]{.greek-added} και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

[και]{.greek-omitted} εν εκεινη [τη]{.greek-omitted} [τηι]{.greek-added} ημερα εγενετο σεισμος μεγας και το δεκατον της πολεως επεσεν [και]{.greek-omitted} [απεκτανθησαν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σεισμω]{.greek-omitted} [ονοματα]{.greek-omitted} [ανθρωπων]{.greek-omitted} [χιλιαδες]{.greek-omitted} [επτα]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [εμφοβοι]{.greek-omitted} [εγενοντο]{.greek-omitted} [και]{.greek-omitted} [εδωκαν]{.greek-omitted} [δοξαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[11:13]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ημερα]{.greek-omitted} [εγενετο]{.greek-omitted} [σεισμος]{.greek-omitted} [μεγας]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [δεκατον]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [επεσεν]{.greek-omitted} και απεκτανθησαν εν [τω]{.greek-omitted} [τωι]{.greek-added} [σεισμω]{.greek-omitted} [σεισμωι]{.greek-added} ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} του [ουρανου]{.greek-abbr}[11:13 | instance no. 2]{.aside}

η ουαι η δευτερα απηλθεν η ουαι η τριτη ιδου ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι εγενετο η βασιλεια του κοσμου [και]{.greek-added} του κυριου ημων [[ιησου]{.greek-abbr}]{.greek-added} [και]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-abbr} [αυτου]{.greek-omitted} και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι οι ενωπιον του θρονου του [θεου]{.greek-abbr} [καθημενοι]{.greek-omitted} [οι]{.greek-added} [καθηνται]{.greek-added} επι τους θρονους αυτων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους [διαφθειροντας]{.greek-omitted} [διαφθειραντας]{.greek-added} την γην[11:18]{.aside}

και [ηνοιγη]{.greek-omitted} [ηνοιχθη]{.greek-added} ο ναος του [θεου]{.greek-abbr} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [ουρανωι]{.greek-added} και ωφθη η κιβωτος της διαθηκης του [κυριου]{.greek-abbr} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} αυτου και εγενοντο αστραπαι και φωναι και βρονται και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [αυτης]{.greek-omitted} [στεφανος]{.greek-omitted} [αστερων]{.greek-omitted} [δωδεκα]{.greek-omitted}[12:1]{.aside}

[και]{.greek-omitted} [σημειον]{.greek-omitted} [μεγα]{.greek-omitted} [ωφθη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [γυνη]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [τον]{.greek-omitted} [ηλιον]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [αυτης]{.greek-omitted} και επι της κεφαλης αυτης [στεφανος]{.greek-omitted} [στεφανοι]{.greek-added} αστερων δωδεκα[12:1 | instance no. 2]{.aside}

και εν γαστρι εχουσα εκραζεν ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και ιδου δρακων [πυρος]{.greek-omitted} [πυρρος]{.greek-added} μεγας εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἕστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει εκτρεφωσιν αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη [αυτω]{.greek-omitted} [αυτων]{.greek-added} ετι εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

δια τουτο ευφραινεσθε ουρανοι και οι εν αυτοις σκηνουντες ουαι τη γη και [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν [τη]{.greek-omitted} [τηι]{.greek-added} γυναικι δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον αυτης οπως τρεφηται εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον [ποιηση]{.greek-omitted} [ποιησηι]{.greek-added}[12:15]{.aside}

και εβοηθησεν η γη [τη]{.greek-omitted} [τηι]{.greek-added} γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι [τη]{.greek-omitted} [τηι]{.greek-added} γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθη]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον εχον κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον ην ομοιον παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου ωσει εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} δρακοντι [τω]{.greek-omitted} [τωι]{.greek-added} δεδωκοτι την εξουσιαν [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} και προσεκυνησαν τω θηριω λεγοντες τις ομοιος [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} [και]{.greek-omitted} τις δυνατος πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και βλασφημιαν και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξουσια πολεμ[ο]{.unclear}ν ποιησαι μηνας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} δυο[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου τους εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} σκηνουντας[13:6]{.aside}

και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ποιησαι πολεμον μετα των αγιων και νικησαι αυτους και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξουσια επι πασαν φυλην και λαον και γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες επι της γης ων ου γεγραπται το ονομα εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} της ζωης [του]{.greek-omitted} [αρνιου]{.greek-omitted} [του]{.greek-omitted} [εσφαγμενου]{.greek-omitted} [απο]{.greek-omitted} [καταβολης]{.greek-omitted} [κοσμου]{.greek-omitted}[13:8]{.aside}

[και]{.greek-omitted} [προσκυνησουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [κατοικουντες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ων]{.greek-omitted} [ου]{.greek-omitted} [γεγραπται]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8 | instance no. 2]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις εχει αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} δει αυτον [εν]{.greek-omitted} [μαχαιρα]{.greek-omitted} [αποκτανθηναι]{.greek-omitted} [ἀποκτανθῆναι]{.greek-added} ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και [ειχεν]{.greek-omitted} [ειχε]{.greek-added} κερατα [δυο]{.greek-omitted} ομοια [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added} και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και εποιει την γην και τους εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} το θηριον το πρωτον [ου]{.greek-omitted} [εθεραπευθη]{.greek-omitted} [η]{.greek-omitted} [πληγη]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [αυτου]{.greek-omitted}[13:12]{.aside}

[και]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [του]{.greek-omitted} [πρωτου]{.greek-omitted} [θηριου]{.greek-omitted} [πασαν]{.greek-omitted} [ποιει]{.greek-omitted} [ενωπιον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εποιει]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [κατοικουντας]{.greek-omitted} [ινα]{.greek-omitted} [προσκυνησωσιν]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [το]{.greek-omitted} [πρωτον]{.greek-omitted} ου εθεραπευθη η πληγη του θανατου αυτου[13:12 | instance no. 2]{.aside}

και ποιει σημεια μεγαλα [ινα]{.greek-added} και πυρ ινα εκ του [ουρανου]{.greek-abbr} καταβαινη επι την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα τους εμους τους κατοικουντας επι της γης δια τα σημεια α εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} [ο]{.greek-omitted} [ὃ]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} [την]{.greek-omitted} πληγην και εζησεν απο της μαχαιρας[13:14]{.aside}

και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} πνευμα δουναι [τη]{.greek-omitted} [τηι]{.greek-added} εικονι του θηριου ινα και [λαληση]{.greek-omitted} [λαλησηι]{.greek-added} η εικων του θηριου και [ποιηση]{.greek-omitted} [ποιησηι]{.greek-added} οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} εικονι του θηριου αποκτανθωσιν[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσ[ο]{.unclear}υσιν]{.greek-added} αυτοις χαραγματα [επι]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [αυτων]{.greek-omitted} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [η]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [μετωπον]{.greek-omitted} [αυτων]{.greek-omitted}[13:16]{.aside}

[και]{.greek-omitted} [ποιει]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πλουσιους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πτωχους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [ελευθερους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [ινα]{.greek-omitted} [δωσωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [χαραγματα]{.greek-omitted} επι [της]{.greek-omitted} χειρος αυτων της δεξιας η επι το μετωπον αυτων[13:16 | instance no. 2]{.aside}

και ινα μη τις δυναται αγορασαι η πωλησαι ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} εστιν [και]{.greek-omitted} ο αριθμος αυτου [[χξϛ]{.greek-abbr}]{.greek-added} [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και ειδον και ιδου το αρνιον εστηκος επι το ορος σιων και μετ αυτου αριθμος [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλης και η φωνη ην ηκουσα ως κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις εδυνατο μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι εισιν οι ακολουθουντες τω αρνιω οπου αν υπαγη ουτοι υπο [ιησου]{.greek-abbr} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} και τω αρνιω[14:4]{.aside}

και ουχ ευρεθη εν τω στοματι αυτων ψευδος αμωμοι γαρ εισιν [ουτοι]{.greek-added} [εισιν]{.greek-added} [οι]{.greek-added} [ακολουθουντες]{.greek-added} [τωι]{.greek-added} [αρνιωι]{.greek-added}[14:5]{.aside}

και ειδον αγγελον πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον ευαγγελισαι τους καθημενους [λϛ]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [παν]{.greek-omitted} [εθνος]{.greek-omitted} [και]{.greek-omitted} [φυλην]{.greek-omitted} [και]{.greek-omitted} [γλωσσαν]{.greek-omitted} [και]{.greek-omitted} [λαον]{.greek-omitted}[14:6]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αγγελον]{.greek-omitted} [πετομενον]{.greek-omitted} [εν]{.greek-omitted} [μεσουρανηματι]{.greek-omitted} [εχοντα]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [αιωνιον]{.greek-omitted} [ευαγγελισαι]{.greek-omitted} [τους]{.greek-omitted} [καθημενους]{.greek-omitted} επι της γης και επι παν εθνος και φυλην και γλωσσαν και λαον[14:6 | instance no. 2]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-abbr} και δοτε [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε αυτον τον ποιησαντα τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος δευτερος αγγελος [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη εκ του οινου του θυμου της πορνειας [αυτης]{.greek-omitted} [ταυτης]{.greek-added} [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8]{.aside}

[και]{.greek-omitted} αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει χαραγμα επι του μετωπου αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος [λζ]{.greek-added} [πιεται]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [κεκερασμενου]{.greek-omitted} [ακρατου]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ποτηριω]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [βασανισθησεται]{.greek-omitted} [εν]{.greek-omitted} [πυρι]{.greek-omitted} [και]{.greek-omitted} [θειω]{.greek-omitted} [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [αγγελων]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted}[14:10]{.aside}

[και]{.greek-omitted} [αυτος]{.greek-omitted} πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν [τω]{.greek-omitted} [τωι]{.greek-added} [ποτηριω]{.greek-omitted} [ποτηριωι]{.greek-added} της οργης αυτου και βασανισθησεται εν πυρι και [θειω]{.greek-omitted} [θειωι]{.greek-added} ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10 | instance no. 2]{.aside}

και ο καπνος του βασανισμου αυτων εις [αιωνας]{.greek-omitted} [αιωνα]{.greek-added} αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε [η]{.greek-omitted} υπομονη των αγιων εστιν οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης γραψον [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [νεκροι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [κυριω]{.greek-omitted} [αποθνησκοντες]{.greek-omitted} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} [ναι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ινα]{.greek-omitted} [αναπαυσωνται]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κοπων]{.greek-omitted} [αυτων]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted} [ακολουθει]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσης]{.greek-omitted} [γραψον]{.greek-omitted} μακαριοι οι νεκροι οι εν [κυριω]{.greek-omitted} [[κωι]{.greek-abbr}]{.greek-added} αποθνησκοντες [ἀπάρτι]{.greek-added} [απ]{.greek-omitted} [αρτι]{.greek-omitted} λεγει ναι το πνευμα ινα [αναπαυσωνται]{.greek-omitted} [αναπαησωνται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυτων [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μετ αυτων[14:13 | instance no. 2]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην καθημενον ομοιον υιω [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου κραζων εν [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι [οτι]{.greek-omitted} [εξηρανθη]{.greek-omitted} [ο]{.greek-omitted} [θερισμος]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[14:15]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [αγγελος]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [κραζων]{.greek-omitted} [εν]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [νεφελης]{.greek-omitted} [πεμψον]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [θερισον]{.greek-omitted} [οτι]{.greek-omitted} [ηλθεν]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted} [θερισαι]{.greek-omitted} οτι εξηρανθη ο θερισμος της γης[14:15 | instance no. 2]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου του εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} [κραυγη]{.greek-omitted} [κραυγηι]{.greek-added} μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι [ηκμασαν]{.greek-omitted} [ηκμασεν]{.greek-added} [αι]{.greek-omitted} [η]{.greek-added} [σταφυλαι]{.greek-omitted} [σταφυλαη]{.greek-added} [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[14:18]{.aside}

και [εβαλεν]{.greek-omitted} [εξεβαλεν]{.greek-added} ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις την ληνον του θυμου του [θεου]{.greek-abbr} τον μεγαν[14:19]{.aside}

και επατηθη η ληνος εξωθεν της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο σταδιων [[αχ]{.greek-abbr}]{.greek-added} [χιλιων]{.greek-omitted} [εξακοσιων]{.greek-omitted}[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [ουρανωι]{.greek-added} [μεγα]{.greek-omitted} [και]{.greek-omitted} [θαυμαστον]{.greek-omitted} [αγγελους]{.greek-omitted} [επτα]{.greek-omitted} [εχοντας]{.greek-omitted} [πληγας]{.greek-omitted} [επτα]{.greek-omitted} [τας]{.greek-omitted} [εσχατας]{.greek-omitted} [οτι]{.greek-omitted} [εν]{.greek-omitted} [αυταις]{.greek-omitted} [ετελεσθη]{.greek-omitted} [ο]{.greek-omitted} [θυμος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[15:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αλλο]{.greek-omitted} [σημειον]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [μεγα]{.greek-omitted} [και]{.greek-omitted} [θαυμαστον]{.greek-omitted} αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1 | instance no. 2]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ [της]{.greek-added} [εικονος]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} του θηριου [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [εικονος]{.greek-omitted} αυτου και εκ του αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην μωυσεως [του]{.greek-omitted} δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη φοβηθη σε [κυριε]{.greek-abbr} και [δοξαση]{.greek-omitted} [δοξασει]{.greek-added} το ονομα σου οτι μονος αγιος οτι [παντες]{.greek-added} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [οι]{.greek-omitted} [ησαν]{.greek-omitted} [ενδεδυμενοι]{.greek-omitted} [λινον]{.greek-omitted} [καθαρον]{.greek-omitted} [λαμπρον]{.greek-omitted} [και]{.greek-omitted} [περιεζωσμενοι]{.greek-omitted} [περι]{.greek-omitted} [τα]{.greek-omitted} [στηθη]{.greek-omitted} [ζωνας]{.greek-omitted} [χρυσας]{.greek-omitted}[15:6]{.aside}

[και]{.greek-omitted} [εξηλθον]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} [αγγελοι]{.greek-omitted} [οι]{.greek-omitted} [εχοντες]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [πληγας]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} οι ησαν ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6 | instance no. 2]{.aside}

και εν εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος [εκ]{.greek-added} [του]{.greek-added} καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις εδυνατο εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα [μεγαλης]{.greek-added} φωνης [μεγαλης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας επτα φιαλας του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη [ζωσα]{.greek-omitted} [ζωης]{.greek-added} απεθανεν εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added}[16:3]{.aside}

και ο τριτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και [ο]{.greek-omitted} [ος]{.greek-added} ην [ο]{.greek-omitted} οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν αξιοι εισιν[16:6]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος [αγγελος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και εδοθη αυτω καυματισαι εν πυρι τους [ανθρωπους]{.greek-abbr}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και [εμασωντο]{.greek-omitted} [εμασσωντο]{.greek-added} τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος εξεχεεν [αυτου]{.greek-added} την φιαλην [αυτου]{.greek-omitted} επι τον ποταμον [τον]{.greek-omitted} [μεγαν]{.greek-omitted} [ευφρατην]{.greek-omitted} [και]{.greek-omitted} [εξηρανθη]{.greek-omitted} [το]{.greek-omitted} [υδωρ]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [ετοιμασθη]{.greek-omitted} [η]{.greek-omitted} [οδος]{.greek-omitted} [των]{.greek-omitted} [βασιλεων]{.greek-omitted} [των]{.greek-omitted} [απο]{.greek-omitted} [ανατολης]{.greek-omitted} [ηλιου]{.greek-omitted}[16:12]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [ποταμον]{.greek-omitted} τον μεγαν ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12 | instance no. 2]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα ακαθαρτα τρια ως βατραχοι[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ πνευματα δαιμονιων ποιουντα σημεια α εκπορευεται επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης [μακαριος]{.greek-omitted} [ο]{.greek-omitted} [γρηγορων]{.greek-omitted} [και]{.greek-omitted} [τηρων]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [γυμνος]{.greek-omitted} [περιπατη]{.greek-omitted} [και]{.greek-omitted} [βλεπωσιν]{.greek-omitted} [την]{.greek-omitted} [ασχημοσυνην]{.greek-omitted} [αυτου]{.greek-omitted}[16:15]{.aside}

[ιδου]{.greek-omitted} [ερχομαι]{.greek-omitted} [ως]{.greek-omitted} [κλεπτης]{.greek-omitted} μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος [περιπατη]{.greek-omitted} [περιπατηι]{.greek-added} και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15 | instance no. 2]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [μαγεδῶν]{.greek-added}[16:16]{.aside}

και ο εβδομος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη απο του ναου του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και φωναι και σεισμος μεγας οιος ουκ εγενετο αφ ου οι [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους ανθρωπους και εβλασφημησαν οι ανθρωποι τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη αυτης σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας [και]{.greek-omitted} [ελαλησεν]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [λεγων]{.greek-omitted} [δευρο]{.greek-omitted} [δειξω]{.greek-omitted} [σοι]{.greek-omitted} [το]{.greek-omitted} [κριμα]{.greek-omitted} [της]{.greek-omitted} [πορνης]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [της]{.greek-omitted} [καθημενης]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [υδατων]{.greek-omitted} [των]{.greek-omitted} [πολλων]{.greek-omitted}[17:1]{.aside}

και [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [εχοντων]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [φιαλας]{.greek-omitted} [και]{.greek-omitted} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο [δειξω]{.greek-omitted} [δειξωσι]{.greek-added} [σοι]{.greek-omitted} το κριμα της πορνης της μεγαλης της καθημενης επι των υδατων των πολλων[17:1 | instance no. 2]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον κοκκινον γεμον [ονοματα]{.greek-omitted} [ονοματων]{.greek-added} βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἦν]{.greek-added} περιβεβλημενη [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον κεχρυσωμενη [χρυσιω]{.greek-omitted} [χρυσιωι]{.greek-added} και [λιθω]{.greek-omitted} [λιθωι]{.greek-added} [τιμιω]{.greek-omitted} [τιμιωι]{.greek-added} και μαργαριταις εχουσα ποτηριον χρυσουν εν τη χειρι αυτης γεμον βδελυγματων [και]{.greek-omitted} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted}[17:4]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [ην]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [πορφυρουν]{.greek-omitted} [και]{.greek-omitted} [κοκκινον]{.greek-omitted} [κεχρυσωμενη]{.greek-omitted} [χρυσιω]{.greek-omitted} [και]{.greek-omitted} [λιθω]{.greek-omitted} [τιμιω]{.greek-omitted} [και]{.greek-omitted} [μαργαριταις]{.greek-omitted} [εχουσα]{.greek-omitted} [ποτηριον]{.greek-omitted} [χρυσουν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτης]{.greek-omitted} [γεμον]{.greek-omitted} [βδελυγματων]{.greek-omitted} και τα ακαθαρτα της πορνειας [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[17:4 | instance no. 2]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν [εκ]{.greek-omitted} του αιματος των αγιων εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος δια τι εθαυμασας εγω ερω σοι το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ εστιν και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες επι της γης ων ου γεγραπται τα ονοματα επι το βιβλιον της ζωης απο καταβολης κοσμου βλεποντων οτι ην το θηριον και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν [αι]{.greek-omitted} [επτα]{.greek-omitted} [κεφαλαι]{.greek-omitted} [επτα]{.greek-omitted} [ορη]{.greek-omitted} [εισιν]{.greek-omitted} [οπου]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [καθηται]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted}[17:9]{.aside}

[ωδε]{.greek-omitted} [ο]{.greek-omitted} [νους]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [σοφιαν]{.greek-omitted} αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [εισιν]{.greek-added} [επτα]{.greek-added}[17:9 | instance no. 2]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε επεσον ο εις εστιν ο αλλος ουπω [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και οταν ελθη ολιγον δει αυτον μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και αυτος ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} και εκ των επτα [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν λαμβανουσιν μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την δυναμιν και [την]{.greek-omitted} εξουσιαν αυτων τω θηριω διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει αυτους οτι κυριος κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ [αυτου]{.greek-omitted} [αυτοι]{.greek-added} κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες [και]{.greek-added} [η]{.greek-added} [γυνη]{.greek-added} ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην ποιησουσιν αυτην και γυμνην ποιησουσιν αυτην και τας σαρκας αυτης φαγονται και αυτην κατακαυσουσιν εν πυρι[17:16]{.aside}

ο γαρ θεος εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι γνωμην μιαν και δουναι την βασιλειαν αυτων τω θηριω αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[μετα]{.corr} [ταυτα]{.corr} [ειδον]{.corr} [[αγγελον]{.corr}]{.greek-added} [αλλον]{.corr} [αγγελον]{.greek-omitted} [καταβαινοντα]{.corr} [εκ]{.corr} [του]{.corr} [[ουρανου]{.greek-abbr}]{.corr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν ισχυρα φωνη λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων [λζ]{.greek-added} [και]{.greek-omitted} [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [πνευματος]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [ορνεου]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} [μεμισημενου]{.greek-omitted}[18:2]{.aside}

[και]{.greek-omitted} [εκραξεν]{.greek-omitted} [ισχυρα]{.greek-omitted} [φωνη]{.greek-omitted} [λεγων]{.greek-omitted} [επεσεν]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [κατοικητηριον]{.greek-omitted} [δαιμονων]{.greek-omitted} και φυλακη παντος [πνευματος]{.greek-abbr} ακαθαρτου και [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [ορνεου]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} μεμισημενου[18:2 | instance no. 2]{.aside}

οτι εκ του οινου του θυμου της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκασι]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του ουρανου και εμνημονευσεν ο θεος τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν [υμιν]{.greek-added} και διπλωσατε αυτη διπλα κατα τα εργα αυτης εν [τω]{.greek-omitted} [τωι]{.greek-added} [ποτηριω]{.greek-omitted} [ποτηριωι]{.greek-added} [ω]{.greek-omitted} [ωι]{.greek-added} [εκερασεν]{.greek-omitted} [εκερασε]{.greek-added} κερασατε αυτη διπλουν [λη]{.greek-added}[18:6]{.aside}

οσα εδοξασεν [αυτην]{.greek-omitted} [εαυτην]{.greek-added} και εστρηνιασεν τοσουτον δοτε αυτη βασανισμον και πενθος οτι εν τη καρδια αυτης λεγει οτι καθημαι βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος [και]{.greek-omitted} πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [κρινων]{.greek-added} [θεος]{.greek-omitted} [ο]{.greek-omitted} [κρινας]{.greek-omitted} αυτην[18:8]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και κοψονται επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του βασανισμου αυτης λεγοντες ουαι ουαι [η]{.greek-omitted} πολις η μεγαλη βαβυλων η πολις η ισχυρα οτι μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και πενθησουσιν επ αυτη οτι τον γομον αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και μαργαριτου και βυσσινου και πορφυρου και σηρικου και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κιναμωμου]{.greek-added} και θυμιαματα και μυρον και λιβανον και [ελαιον]{.greek-added} [και]{.greek-added} οινον [και]{.greek-omitted} [ελαιον]{.greek-omitted} και σεμιδαλιν και σιτον και προβατα και κτηνη και ιππων και ραιδων και σωματων και ψυχας ανθρωπων[18:13]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα απωλετο απο σου και ουκετι [αυτα]{.greek-omitted} ου μη ευρης [αυτα]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15]{.aside}

και λεγοντες ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και πορφυρουν [και]{.greek-omitted} κοκκινον και κεχρυσωμενη [χρυσιω]{.greek-omitted} [χρυσιωι]{.greek-added} και [λιθω]{.greek-omitted} [λιθωι]{.greek-added} [τιμιω]{.greek-omitted} [τιμιωι]{.greek-added} [και]{.greek-omitted} [μαργαριταις]{.greek-omitted}[18:16]{.aside}

[και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουαι]{.greek-omitted} [ουαι]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [η]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [βυσσινον]{.greek-omitted} [και]{.greek-omitted} [πορφυρουν]{.greek-omitted} [και]{.greek-omitted} [κοκκινον]{.greek-omitted} [και]{.greek-omitted} [κεχρυσωμενη]{.greek-omitted} [χρυσιω]{.greek-omitted} [και]{.greek-omitted} [λιθω]{.greek-omitted} [τιμιω]{.greek-omitted} και μαργαριταις[18:16 | instance no. 2]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος και πας κυβερνητης και πας [ο]{.greek-omitted} επι [τοπον]{.greek-omitted} [των]{.greek-added} [πλοιων]{.greek-added} πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και εκραζον βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη πολει [τη]{.greek-omitted} [τηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added}[18:18]{.aside}

και εβαλον χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες και λεγοντες ουαι ουαι η πολις η [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} εν η επλουτησαν παντες οι εχοντες [τα]{.greek-omitted} πλοια εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} εκ της τιμιοτητος αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ [αυτη]{.greek-omitted} [αυτηι]{.greek-added} [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης πασης τεχνης ου μη ευρεθη εν σοι ετι και φωνη μυλου ου μη [ακουσθη]{.greek-omitted} [φανη]{.greek-added} εν σοι ετι[18:22]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [φανῇ]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη ακουσθη εν σοι ετι οτι οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν [τη]{.greek-omitted} [τηι]{.greek-added} φαρμακεια σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα ηκουσα ως φωνην μεγαλην οχλου πολλου εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλόυια]{.greek-added} η [σωτηρια]{.greek-abbr} και η δυναμις και η δοξα του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [διεφθειρε]{.greek-added} [την]{.greek-added} [γην]{.greek-added} [την]{.greek-added} [μεγαλην]{.greek-added} [ητις]{.greek-added} [διεφθειρε]{.greek-added} την γην εν [τη]{.greek-omitted} [τηι]{.greek-added} πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ χειρος αυτης[19:2]{.aside}

και δευτερον ειρηκεν αλληλουια και ο καπνος αυτης αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι πρεσβυτεροι οι εικοσι τεσσαρες και τα τεσσαρα ζωα και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τωι]{.greek-added} [θρονωι]{.greek-added} λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη [απο]{.greek-omitted} [εκ]{.greek-added} του θρονου [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} λεγουσα αινειτε τον [θεον]{.greek-abbr} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα ως φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων λεγοντες αλληλουια οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και αγαλλιωμεθα και δωμεν την δοξαν [αυτω]{.greek-omitted} [αυτου]{.greek-added} οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη [αυτη]{.greek-omitted} [αυτηι]{.greek-added} ινα περιβαληται βυσσινον λαμπρον και καθαρον το γαρ βυσσινον τα δικαιωματα των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις το δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι αληθινοι του [θεου]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[19:9]{.aside}

και [επεσα]{.greek-omitted} [επεσον]{.greek-added} εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι ορα μη συνδουλος σου ειμι [και]{.greek-omitted} [των]{.greek-omitted} [αδελφων]{.greek-omitted} [σου]{.greek-omitted} [των]{.greek-omitted} [εχοντων]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [προσκυνησον]{.greek-omitted} [η]{.greek-omitted} [γαρ]{.greek-omitted} [μαρτυρια]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [της]{.greek-omitted} [προφητειας]{.greek-omitted}[19:10]{.aside}

[και]{.greek-omitted} [επεσα]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [αυτου]{.greek-omitted} [προσκυνησαι]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [ορα]{.greek-omitted} [μη]{.greek-omitted} [συνδουλος]{.greek-omitted} [σου]{.greek-omitted} [ειμι]{.greek-omitted} και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} προσκυνησον η γαρ μαρτυρια του [ιησου]{.greek-omitted} [υιου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} το [πνευμα]{.greek-abbr} της προφητειας[19:10 | instance no. 2]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον [καλουμενος]{.greek-omitted} πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων [ονοματα]{.greek-omitted} [γεγραμμενα]{.greek-omitted} [και]{.greek-omitted} ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον βεβαμμενον [εν]{.greek-added} αιματι και καλειται το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα τα εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ηκολουθει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} επι ιπποις λευκοις ενδεδυμενοι βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν [ραβδω]{.greek-omitted} [ραβδωι]{.greek-added} σιδηρα και αυτος πατει την ληνον του οινου του θυμου της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον αγγελον εστωτα εν [τω]{.greek-omitted} [τωι]{.greek-added} [ηλιω]{.greek-omitted} [ηλιωι]{.greek-added} και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι [δευτε]{.greek-omitted} [συναχθητε]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [δειπνον]{.greek-omitted} [το]{.greek-omitted} [μεγα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[19:17]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αγγελον]{.greek-omitted} [εστωτα]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ηλιω]{.greek-omitted} [και]{.greek-omitted} [εκραξεν]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [λεγων]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [ορνεοις]{.greek-omitted} [τοις]{.greek-omitted} [πετομενοις]{.greek-omitted} [εν]{.greek-omitted} [μεσουρανηματι]{.greek-omitted} δευτε συναχθητε εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον [το]{.greek-omitted} [τον]{.greek-added} [μεγα]{.greek-omitted} [μεγαν]{.greek-added} του [θεου]{.greek-abbr}[19:17 | instance no. 2]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων [των]{.greek-added} ελευθερων τε και δουλων και μικρων [τε]{.greek-omitted} και μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι [τον]{.greek-added} πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον και ο μετ αυτου ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας [τη]{.greek-omitted} [τηι]{.greek-added} εικονι αυτου ζωντες εβληθησαν οι δυο εις την λιμνην του πυρος [την]{.greek-omitted} [της]{.greek-added} καιομενην εν [θειω]{.greek-omitted} [θειωι]{.greek-added}[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την κλειν της αβυσσου και αλυσιν [μεγαλην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [αυτου]{.greek-omitted}[20:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αγγελον]{.greek-omitted} [καταβαινοντα]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [εχοντα]{.greek-omitted} [την]{.greek-omitted} [κλειν]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [αλυσιν]{.greek-omitted} μεγαλην επι την χειρα αυτου[20:1 | instance no. 2]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και ο σατανας ο πλανων την οικουμενην ολην και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλεισε]{.greek-added} και εσφραγισεν επανω αυτου ινα μη πλανα ετι τα εθνη αχρι τελεσθη τα χιλια ετη και μετα ταυτα δει [λυθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και ειδον θρονους και εκαθισαν [επ]{.greek-omitted} [επανω]{.greek-added} αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν το θηριον ουδε την εικονα αυτου και ουκ ελαβον το χαραγμα επι το μετωπον και επι την χειρα αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} τα χιλια ετη[20:4]{.aside}

και οι λοιποι των νεκρων ουκ εζησαν αχρι τελεσθη τα χιλια ετη αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν τη αναστασει [τη]{.greek-omitted} [τηι]{.greek-added} [πρωτη]{.greek-omitted} [πρωτηι]{.greek-added} επι τουτων ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} [μετ]{.greek-omitted} [μετα]{.greek-added} [αυτου]{.greek-omitted} [ταυτα]{.greek-added} χιλια ετη[20:6]{.aside}

και [μετα]{.greek-added} [οταν]{.greek-omitted} [τελεσθη]{.greek-omitted} τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης [τον]{.greek-omitted} [γωγ]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [μαγωγ]{.greek-omitted} [συναγαγειν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [πολεμον]{.greek-omitted} [ων]{.greek-omitted} [ο]{.greek-omitted} [αριθμος]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αμμος]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted}[20:8]{.aside}

[και]{.greek-omitted} [εξελευσεται]{.greek-omitted} [πλανησαι]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [τεσσαρσιν]{.greek-omitted} [γωνιαις]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} τον γωγ και τον μαγωγ συναγαγειν αυτους εις τον πολεμον ων ο αριθμος [ωσει]{.greek-added} [ως]{.greek-omitted} [η]{.greek-omitted} αμμος της θαλασσης[20:8 | instance no. 2]{.aside}

και ανεβησαν επι το πλατος της γης και εκυκλωσαν την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και θειου οπου και το θηριον και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10]{.aside}

και ειδον θρονον μεγαν λευκον και τον καθημενον επ αυτον ου απο [του]{.greek-added} προσωπου εφυγεν η γη και ο [ουρανος]{.greek-abbr} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον τους νεκρους [εστωτας]{.greek-added} [τους]{.greek-added} [μικρους]{.greek-added} [και]{.greek-added} τους μεγαλους [και]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} [εστωτας]{.greek-omitted} ενωπιον του θρονου και βιβλια [ηνεωχθησαν]{.greek-omitted} [ηνοιχθησαν]{.greek-added} και αλλο βιβλιον ηνεωχθη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} και ο θανατος και ο αδης [εδωκαν]{.greek-omitted} [εδωκε]{.greek-added} τους νεκρους τους εν αυτοις και εκριθησαν εκαστος κατα τα εργα αυτων[20:13]{.aside}

και ο θανατος και ο [αδης]{.greek-omitted} [αιδης]{.greek-added} εβληθησαν εις την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ει τις ουχ ευρεθη εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη απηλθον [και]{.greek-omitted} [η]{.greek-omitted} [θαλασσα]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [ετι]{.greek-omitted}[21:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [ουρανον]{.greek-omitted} [καινον]{.greek-omitted} [και]{.greek-omitted} [γην]{.greek-omitted} [καινην]{.greek-omitted} [ο]{.greek-omitted} [γαρ]{.greek-omitted} [πρωτος]{.greek-omitted} [ουρανος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πρωτη]{.greek-omitted} [γη]{.greek-omitted} [απηλθον]{.greek-omitted} και η θαλασσα ουκ εστιν ετι[21:1 | instance no. 2]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} ητοιμασμενην ως νυμφην κεκοσμημενην [τω]{.greek-omitted} [τωι]{.greek-added} ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} [εσται]{.greek-omitted} μετ αυτων [εσται]{.greek-added}[21:3]{.aside}

και [εξαλειψει]{.greek-omitted} [εκλεψει]{.greek-added} παν δακρυον απο των οφθαλμων αυτων και ο θανατος ουκ εσται ετι ουτε πενθος ουτε κραυγη ουτε πονος ουκ εσται ετι οτι τα πρωτα [απηλθον]{.greek-omitted} [απηλθε]{.greek-added}[21:4]{.aside}

και ειπεν ο καθημενος επι τω θρονω ιδου [ιδου]{.greek-added} παντα καινα ποιω και λεγει [μοι]{.greek-omitted} γραψον [οτι]{.greek-omitted} [ουτοι]{.greek-omitted} [οι]{.greek-omitted} [λογοι]{.greek-omitted} [αληθινοι]{.greek-omitted} [και]{.greek-omitted} [πιστοι]{.greek-omitted} [εισιν]{.greek-omitted}[21:5]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [ο]{.greek-omitted} [καθημενος]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [θρονω]{.greek-omitted} [ιδου]{.greek-omitted} [παντα]{.greek-omitted} [καινα]{.greek-omitted} [ποιω]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [γραψον]{.greek-omitted} οτι ουτοι οι λογοι [πιστοι]{.greek-added} [και]{.greek-added} αληθινοι [και]{.greek-omitted} [πιστοι]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added}[21:5 | instance no. 2]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι γεγονα [εγω]{.greek-added} το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} [η]{.greek-omitted} αρχη και [το]{.greek-omitted} τελος εγω [τω]{.greek-omitted} [τωι]{.greek-added} διψωντι δωσω [αυτωι]{.greek-added} εκ της πηγης του υδατος της ζωης δωρεαν[21:6]{.aside}

ο νικων [κληρονομησει]{.greek-omitted} [δωσω]{.greek-added} [αυτωι]{.greek-added} ταυτα και εσομαι αυτω [θεος]{.greek-abbr} και αυτος εσται μοι υιος[21:7]{.aside}

τοις δε δειλοις και απιστοις και αμαρτωλοις και εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} και πορνοις και φαρμακοις και ειδωλολατραις και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν τη λιμνη τη καιομενη πυρι και θειω ο [εστιν]{.greek-omitted} [εστι]{.greek-added} ο θανατος ο δευτερος[21:8]{.aside}

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας γεμουσας [των]{.greek-omitted} επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την γυναικα την νυμφην του αρνιου[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εν [πνευματι]{.greek-abbr} επ ορος μεγα και υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} [μοι]{.greek-omitted} [με]{.greek-added} την πολιν [την]{.greek-omitted} [μεγαλην]{.greek-omitted} την αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του [θεου]{.greek-abbr}[21:10]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης ομοιος [λιθω]{.greek-omitted} [λιθωι]{.greek-added} [τιμιωτατω]{.greek-omitted} [τιμιωτατωι]{.greek-added} ως [λιθω]{.greek-omitted} [λιθωι]{.greek-added} ιασπιδι [κρυσταλλιζοντι]{.greek-omitted} [κρυσταλιζοντι]{.greek-added}[21:11]{.aside}

εχουσα τειχος μεγα και υψηλον εχουσα πυλωνας [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και επι τοις πυλωσιν αγγελους δωδεκα και ονοματα επιγεγραμμενα [λη]{.greek-added} [α]{.greek-omitted} [εστιν]{.greek-omitted} [ονοματα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [φυλων]{.greek-omitted} [των]{.greek-omitted} [υιων]{.greek-omitted} [ισραηλ]{.greek-omitted}[21:12]{.aside}

[εχουσα]{.greek-omitted} [τειχος]{.greek-omitted} [μεγα]{.greek-omitted} [και]{.greek-omitted} [υψηλον]{.greek-omitted} [εχουσα]{.greek-omitted} [πυλωνας]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [πυλωσιν]{.greek-omitted} [αγγελους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [ονοματα]{.greek-omitted} [επιγεγραμμενα]{.greek-omitted} α εστιν [τα]{.greek-added} ονοματα των δωδεκα φυλων [των]{.greek-omitted} υιων [ισραηλ]{.greek-abbr}[21:12 | instance no. 2]{.aside}

απο ανατολων πυλωνες τρεις και απο βορρα πυλωνες τρεις και απο νοτου πυλωνες τρεις και απο δυσμων πυλωνες τρεις[21:13]{.aside}

και το τειχος της πολεως εχον θεμελιους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} μετρον καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν [τω]{.greek-omitted} [τωι]{.greek-added} [καλαμω]{.greek-omitted} [καλαμωι]{.greek-added} επι σταδιους [δωδεκα]{.greek-omitted} [δεκαδυο]{.greek-added} χιλιαδων δωδεκα το μηκος και το πλατος και το υψος αυτης ισα [εστιν]{.greek-omitted} [εστι]{.greek-added}[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} το τειχος αυτης [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρων]{.greek-omitted} πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον ομοιον [υελω]{.greek-omitted} [υαλωι]{.greek-added} [καθαρω]{.greek-omitted} [καθαρωι]{.greek-added}[21:18]{.aside}

οι θεμελιοι του τειχους της πολεως παντι [λιθω]{.greek-omitted} [λιθωι]{.greek-added} [τιμιω]{.greek-omitted} [τιμιωι]{.greek-added} κεκοσμημενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος [σαρδονυξ]{.greek-omitted} [σαρδωνυξ]{.greek-added} ο εκτος σαρδιον ο εβδομος χρυσολιθος ο ογδοος βηρυλλος ο ενατος τοπαζιον ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος ο δωδεκατος αμεθυσος[21:20]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται [ανα]{.greek-omitted} [εις]{.greek-omitted} [εκαστος]{.greek-omitted} [των]{.greek-omitted} [πυλωνων]{.greek-omitted} [ην]{.greek-omitted} [εξ]{.greek-omitted} [ενος]{.greek-omitted} [μαργαριτου]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πλατεια]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [χρυσιον]{.greek-omitted} [καθαρον]{.greek-omitted} [ως]{.greek-omitted} [υελος]{.greek-omitted} [διαυγης]{.greek-omitted}[21:21]{.aside}

[ινα]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [δωδεκα]{.greek-omitted} [πυλωνες]{.greek-omitted} [δωδεκα]{.greek-omitted} [μαργαριται]{.greek-omitted} [ανα]{.greek-omitted} εις εκαστος των πυλωνων ην εξ ενος μαργαριτου και η πλατεια της πολεως χρυσιον καθαρον ως [υελος]{.greek-omitted} [υαλος]{.greek-added} διαυγης[21:21 | instance no. 2]{.aside}

και ναον ουκ ειδον εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} ο γαρ [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν αυτη [γαρ]{.greek-added} η [γαρ]{.greek-omitted} δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης φερουσιν αυτω δοξαν και τιμην των εθνων εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην [και]{.greek-added} [εισελθωσιν]{.greek-added}[21:26]{.aside}

και ου μη εισελθη εις αυτην παν κοινον και ποιουν βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον καθαρον υδατος ζωης λαμπρον ως κρυσταλλον εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της [πλατειας]{.greek-omitted} [πολεως]{.greek-added} αυτης και του ποταμου εντευθεν και εκειθεν ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα [αποδιδους]{.greek-added} εκαστον [αποδιδους]{.greek-omitted} τον καρπον αυτου και τα φυλλα του ξυλου εις θεραπειαν των εθνων[22:2]{.aside}

και παν καταθεμα ουκ εσται [ετι]{.greek-omitted} [εκει]{.greek-added} και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} εσται και οι δουλοι αυτου λατρευσουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των μετωπων αυτων[22:4]{.aside}

και νυξ ουκ εσται εκει και χρειαν ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} λυχνου και [φωτος]{.greek-omitted} [φως]{.greek-added} ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [φωτιει]{.greek-omitted} [φωτιζει]{.greek-added} αυτους [και]{.greek-omitted} [βασιλευσουσιν]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[22:5]{.aside}

[και]{.greek-omitted} [νυξ]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [εκει]{.greek-omitted} [και]{.greek-omitted} [χρειαν]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [λυχνου]{.greek-omitted} [και]{.greek-omitted} [φωτος]{.greek-omitted} [ηλιου]{.greek-omitted} [οτι]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [φωτιει]{.greek-omitted} [αυτους]{.greek-omitted} και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5 | instance no. 2]{.aside}

και [λεγει]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι οι λογοι πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο θεος των [πνευματων]{.greek-abbr} των προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

[και]{.greek-omitted} ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

[καγω]{.greek-omitted} [ιωαννης]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} ο [βλεπων]{.greek-added} [και]{.greek-added} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} ταυτα και οτε ηκουσα και εβλεψα επεσον προσκυνησαι εμπροσθεν των ποδων του αγγελου του [δεικνυοντος]{.greek-omitted} [δεικνυντος]{.greek-added} μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι [εγω]{.greek-added} και των αδελφων σου των προφητων [και]{.greek-omitted} των τηρουντων τους λογους του βιβλιου τουτου [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} προσκυνησον[22:9]{.aside}

και λεγει μοι μη [σφραγισης]{.greek-omitted} [σφραγισηις]{.greek-added} τους λογους της προφητειας του βιβλιου τουτου ο καιρος [γαρ]{.greek-omitted} εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος ρυπαρευθητω ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον [αυτου]{.greek-added} εσται [αυτου]{.greek-omitted}[22:12]{.aside}

εγω το αλφα και το ω [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} ο πρωτος και ο εσχατος [η]{.greek-omitted} [αρχη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τελος]{.greek-omitted}[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι [φονεις]{.greek-omitted} [φωνεις]{.greek-added} και [οι]{.greek-omitted} ειδωλολατραι και πας [ο]{.greek-added} [ποιων]{.greek-added} [και]{.greek-added} φιλων [και]{.greek-omitted} [ποιων]{.greek-omitted} ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα [επι]{.greek-omitted} ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} ο αστηρ ο [πρωινος]{.greek-added} [ο]{.greek-added} λαμπρος [ο]{.greek-omitted} [πρωινος]{.greek-omitted}[22:16]{.aside}

και το πνευμα και η νυμφη λεγουσιν ερχου και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

[μαρτυρω]{.greek-omitted} [μαρτυρομαι]{.greek-added} εγω παντι τω ακουοντι τους λογους της προφητειας του βιβλιου τουτου εαν τις επιθη επ αυτα [επιθησαι]{.greek-omitted} [επιθησει]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-omitted} επ αυτον [[θεος]{.greek-abbr}]{.greek-added} τας [επτα]{.greek-added} πληγας τας γεγραμμενας εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} [τουτω]{.greek-omitted} [τουτωι]{.greek-added}[22:18]{.aside}

και εαν τις αφελη απο των λογων του βιβλιου [της]{.greek-omitted} [προφητειας]{.greek-omitted} [ταυτης]{.greek-omitted} [αφελοι]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [το]{.greek-omitted} [μερος]{.greek-omitted} [αυτου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [της]{.greek-omitted} [αγιας]{.greek-omitted} [των]{.greek-omitted} [γεγραμμενων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [τουτω]{.greek-omitted}[22:19]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [τις]{.greek-omitted} [αφελη]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [λογων]{.greek-omitted} [του]{.greek-omitted} [βιβλιου]{.greek-omitted} της προφητειας ταυτης [αφελοι]{.greek-omitted} [αφελει]{.greek-added} ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} [τουτω]{.greek-omitted} [τουτωι]{.greek-added}[22:19 | instance no. 2]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην [ναι]{.greek-omitted} ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added}[22:20]{.aside}

η χαρις του [κυριου]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-abbr} μετα παντων των αγιων αμην[22:21]{.aside}

