---
title: "Collation of Byz^RP^ vs 30104 (104)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 104 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30104).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 104                                   	| λογος                              	|
| 104 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 104 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 104               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 104                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 104 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 104                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

τον μεν πρωτον λογον εποιησαμην περι παντων ω θεοφιλε ων ηρξατο ο [ιησους]{.greek-abbr} ποιειν τε και διδασκειν[1:1]{.aside}

αχρι [ην]{.greek-added} [ης]{.corr} ημερας εντειλαμενος τοις αποστολοις δια [πνευματος]{.greek-abbr} αγιου ους εξελεξατο ανελ[η]{.unclear}φθη[1:2]{.aside}

οις και παρεστησεν εαυτον ζωντα μετα το παθειν αυτον εν πολλοις [τεκ]{.greek-added} [τεκμηριοις]{.greek-omitted} [μηριοις]{.greek-added} δι ημερων τεσσαρακοντα οπτανομενος αυτοις και λεγων τα περι της βασιλειας του [θεου]{.greek-abbr}[1:3]{.aside}

και συναλιζομενος παρηγγειλεν αυτοις απο ιεροσολυμων μη χωριζεσθαι αλλα περιμενειν την επαγγελιαν του [πατρος]{.greek-abbr} ην ηκουσατε μου[1:4]{.aside}

οτι ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω ου μετα πολλας ταυτας ημερας[1:5]{.aside}

οι μεν ουν συνελθοντες επηρωτων αυτον λεγοντες [κυριε]{.greek-abbr} ει εν τω χρονω τουτω [αποκαθιστανεις]{.greek-omitted} [αποκαθιστανης]{.greek-added} την βασιλειαν τω [ισραηλ]{.greek-abbr}[1:6]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε προς αυτους ουχ υμων εστιν [[εστι]{.corr}]{.greek-added} γνωναι χρονους η καιρους ους ο [πατηρ]{.greek-abbr} εθετο εν τη ιδια εξουσια[1:7]{.aside}

αλλα ληψεσθε δυναμιν επελθοντος του αγιου [πνευματος]{.greek-abbr} εφ υμας και εσεσθε μοι μαρτυρες εν τε [ιερουσαλημ]{.greek-abbr} και εν παση τη ιουδαια και σαμαρεια και εως εσχατου της γης[1:8]{.aside}

και ταυτα ειπων βλεποντων αυτων επηρθη και νεφελη υπελαβεν αυτον απο των οφθαλμων αυτων[1:9]{.aside}

και ως ατενιζοντες ησαν εις τον [ουρανον]{.greek-abbr} πορευομενου αυτου και ιδου ανδρες δυο [παρειστηκεισαν]{.greek-omitted} [παριστηκησαν]{.greek-added} αυτοις εν εσθητι λευκη[1:10]{.aside}

οι και ειπον ανδρες γαλιλαιοι τι εστηκατε [εμβλεποντες]{.greek-omitted} [βλεποντες]{.greek-added} εις τον [ουρανον]{.greek-abbr} ουτος ο [ιησους]{.greek-abbr} ο αναληφθεις αφ υμων εις τον [ουρανον]{.greek-abbr} ουτως ελευσεται [παλιν]{.greek-added} ον τροπον εθεασασθε αυτον πορευομενον εις τον [ουρανον]{.greek-abbr}[1:11]{.aside}

τοτε υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} απο ορους του καλουμενου ελαιωνος ο εστιν εγγυς [ιερουσαλημ]{.greek-abbr} σαββατου εχον οδον[1:12]{.aside}

και οτε εισηλθον ανεβησαν εις το υπερωον ου ησαν καταμενοντες ο τε πετρος και [ιωαννης]{.greek-added} [και]{.greek-added} ιακωβος και [ιωαννης]{.greek-omitted} [ανδρεας]{.greek-added} και [ανδρεας]{.greek-omitted} φιλιππος και θωμας βαρθολομαιος και ματθαιος ιακωβος αλφαιου και σιμων ο ζηλωτης και ιουδας ιακωβου[1:13]{.aside}

ουτοι παντες ησαν προσκαρτερουντες ομοθυμαδον τη προσευχη και τη δεησει συν γυναιξιν [[γυναιξι]{.corr}]{.greek-added} και μαρια τη [μητρι]{.greek-abbr} του [ιησου]{.greek-abbr} και [συν]{.greek-omitted} τοις αδελφοις αυτου[1:14]{.aside}

και εν ταις ημεραις ταυταις αναστας πετρος εν μεσω των [μαθητων]{.greek-omitted} [αδελφων]{.greek-added} ειπεν ην τε οχλος ονοματων επι το αυτο [ως]{.greek-omitted} [ωσει]{.greek-added} εκατον εικοσι[1:15]{.aside}

ανδρες αδελφοι εδει πληρωθηναι την γραφην [ταυτην]{.greek-omitted} ην προειπεν [[προειπε]{.corr}]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον δια στοματος [δαυιδ]{.greek-abbr} περι ιουδα του γενομενου οδηγου τοις [συλλαβουσιν]{.greek-omitted} [συλλαβουσι]{.greek-added} τον [ιησουν]{.greek-abbr}[1:16]{.aside}

οτι κατηριθμημενος ην [συν]{.greek-omitted} [εν]{.greek-added} ημιν και ελαχεν [[ελαχε]{.corr}]{.greek-added} τον κληρον της διακονιας ταυτης[1:17]{.aside}

ουτος μεν ουν εκτησατο χωριον εκ μισθου της αδικιας και πρηνης γενομενος ελακησεν [[ελακησε]{.corr}]{.greek-added} μεσος και εξεχυθη παντα τα σπλαγχνα αυτου[1:18]{.aside}

και γνωστον εγενετο πασιν [[πασι]{.corr}]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} ωστε [κληθηναι]{.greek-omitted} [κλιθηναι]{.greek-added} το χωριον εκεινο τη ιδια διαλεκτω αυτων ακελδαμα τουτ εστιν [[εστι]{.corr}]{.greek-added} χωριον αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω ψαλμων γενηθητω [η]{.unclear} επαυλις αυτου ερημος και μη εστω ο κατοι[κ]{.unclear}ων εν αυτη και την επισκοπην αυτου [λαβοι]{.greek-omitted} [λαβετω]{.greek-added} ετερος[1:20]{.aside}

δει ουν των συνελθοντων ημιν ανδρων εν παντι χρονω εν ω εισηλθεν [[εισηλθε]{.corr}]{.greek-added} και εξηλθεν εφ ημας ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βαπτισματος ιωαννου [εως]{.greek-omitted} [αχρι]{.greek-added} της ημερας ης ανεληφθη αφ ημων μαρτυρα της αναστασεως αυτου γενεσθαι συν ημιν ενα τουτων[1:22]{.aside}

και εστησαν δυο ιωσηφ τον καλουμενον [βαρσαβαν]{.greek-omitted} [βαρσαββαν]{.greek-added} ος επεκληθη ιουστος και ματθιαν[1:23]{.aside}

και προσευξαμενοι ειπον συ [κυριε]{.greek-abbr} καρδιογνωστα παντων αναδειξον ον εξελεξω εκ τουτων των δυο ενα[1:24]{.aside}

λαβειν τον κληρον της διακονιας ταυτης και αποστολης [εξ]{.greek-omitted} [αφ]{.greek-added} ης παρεβη ιουδας πορευθηναι εις τον τοπον τον ιδιον[1:25]{.aside}

και εδωκαν κληρους [αυτων]{.greek-omitted} [αυτοις]{.greek-added} και επεσεν ο κληρος επι ματθιαν και συγκατεψηφισθη μετα των ενδεκα αποστολων[1:26]{.aside}

### Chapter 2

και εν τω συμπληρουσθαι την ημεραν της πεντηκοστης ησαν απαντες ομοθυμαδον επι το αυτο[2:1]{.aside}

και εγενετο αφνω εκ του [ουρανου]{.greek-abbr} ηχος ωσπερ φερομενης [πνοης]{.greek-omitted} [πνωης]{.greek-added} βιαιας και επληρωσεν ολον τον οικον ου ησαν καθημενοι[2:2]{.aside}

και ωφθησαν αυτοις διαμεριζομεναι γλωσσαι ωσει πυρος εκαθισεν [[εκαθισε]{.corr}]{.greek-added} τε εφ ενα ε[κα]{.greek-supplied}στον αυτων[2:3]{.aside}

και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετεραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου [αποφθεγγεσθαι]{.greek-added} αυτοις [αποφθεγγεσθαι]{.greek-omitted}[2:4]{.aside}

ησαν δε εν [ιερουσαλημ]{.greek-abbr} κατοικουντες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο τον [ουρανον]{.greek-abbr}[2:5]{.aside}

γενομενης δε της φωνης ταυτης συνηλθεν [[συνηλθε]{.corr}]{.greek-added} το πληθος και συνεχυθη οτι ηκουον εις εκαστος τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

εξισταντο δε παντες και εθαυμαζον λεγοντες προς αλληλους ουκ ιδου παντες ουτοι εισιν οι λαλουντες γαλιλαιοι[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η [εγεννηθημεν]{.greek-omitted} [εγενηθημεν]{.greek-added}[2:8]{.aside}

παρθοι και μηδοι και ελαμιται και οι κατοικουντες την μεσοποταμιαν ιουδαιαν τε και καππαδοκιαν ποντον και την ασιαν[2:9]{.aside}

φρυγιαν τε και παμφυλιαν αιγυπτον και τα μερη της λιβυης της κατα [κυρηνην]{.greek-omitted} [κυρινην]{.greek-added} και οι επιδημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[ιουδαιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυτοι]{.greek-added} κρητες και αραβες ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα μεγαλεια του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και διηπορουν αλλος προς αλλον λεγοντες τι αν θελοι τουτο ειναι[2:12]{.aside}

ετεροι δε χλευαζοντες ελεγον οτι γλευκους μεμεστωμενοι εισιν [[εισι]{.corr}]{.greek-added}[2:13]{.aside}

σταθεις δε πετρος συν τοις ενδεκα επηρεν [[επηρε]{.corr}]{.greek-added} την φωνην αυτου και απεφθεγξατο αυτοις ανδρες ιουδαιοι και οι κατοικουντες [ιερουσαλημ]{.greek-abbr} απαντες τουτο υμιν γνωστον εστω και ενωτισασθε τα ρηματα μου[2:14]{.aside}

ου γαρ ως υμεις υπολαμβανετε ουτοι μεθυουσιν εστιν [[εστι]{.corr}]{.greek-added} γαρ ωρα τριτη της ημερας[2:15]{.aside}

αλλα τουτο εστιν [[εστι]{.corr}]{.greek-added} το ειρημενον δια του προφητου ιωηλ[2:16]{.aside}

και εσται εν ταις εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υιοι υμων και αι θυγατερες υμων και οι νεανισκοι υμων ορασεις οψονται και οι πρεσβυτεροι υμων [ενυπνια]{.greek-omitted} [ενυπνιοις]{.greek-added} ενυπνιασθησονται[2:17]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις εκχεω απο του [πνευματος]{.greek-abbr} μου και προφητευσουσιν [[προφητευσουσι]{.corr}]{.greek-added}[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω και σημεια επι της γης κατω αιμα και πυρ και ατμιδα καπνου[2:19]{.aside}

ο ηλιος μεταστραφησεται εις σκοτος και η σεληνη εις αιμα πριν η ελθειν την ημεραν [κυριου]{.greek-abbr} την μεγαλην και επιφανη[2:20]{.aside}

και εσται πας ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθησεται[2:21]{.aside}

ανδρες ισραηλιται ακουσατε τους λογους τουτους [ιησουν]{.greek-abbr} τον ναζωραιον ανδρα [αποδεδειγμενον]{.greek-added} απο του [θεου]{.greek-abbr} [αποδεδειγμενον]{.greek-omitted} εις υμας [δυναμεσιν]{.greek-omitted} [δυνα]{.greek-added} [μεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και σημειοις οις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δι αυτου ο [θεος]{.greek-abbr} εν μεσω υμων καθως [και]{.greek-omitted} αυτοι οιδατε[2:22]{.aside}

τουτον τη [ωρισμενη]{.greek-omitted} [ορισμενη]{.greek-added} βουλη και προγνωσει [του]{.greek-omitted} [θεου]{.greek-omitted} [εκδοτον]{.greek-omitted} [λαβοντες]{.greek-omitted} δια χειρων ανομων προσπηξαντες [ανειλετε]{.greek-omitted} [ανηλατε]{.greek-added}[2:23]{.aside}

ον ο [θεος]{.greek-abbr} ανεστησεν [[ανεστησε]{.corr}]{.greek-added} λυσας τας ωδινας του θανατου καθοτι ουκ ην δυνατον κρατεισθαι αυτον υπ αυτου[2:24]{.aside}

[δαυιδ]{.greek-abbr} γαρ λεγει εις αυτον [προωρωμην]{.greek-omitted} [προορωμην]{.greek-added} τον [κυριον]{.greek-abbr} ενωπιον μου δια παντος οτι εκ δεξιων μου εστιν ινα μη σαλευθω[2:25]{.aside}

δια τουτο [ευφρανθη]{.greek-omitted} [ηυφρανθη]{.greek-added} η καρδια μου και ηγαλλιασατο η γλωσσα μου ετι δε και η σαρξ μου κατασκηνωσει επ ελπιδι[2:26]{.aside}

οτι ουκ εγκαταλειψεις την ψυχην μου εις αδου ουδε δωσεις τον οσιον σου ιδειν διαφθοραν[2:27]{.aside}

εγνωρισας μοι οδους ζωης πληρωσεις με ευφροσυνης μετα του προσωπου σου[2:28]{.aside}

ανδρες αδελφοι εξον ειπειν μετα παρρησιας προς υμας περι του [πατριαρχου]{.greek-abbr} [δαυιδ]{.greek-abbr} οτι και ετελευτησεν [[ετελευτησε]{.corr}]{.greek-added} και εταφη και το μνημα αυτου εστιν εν ημιν αχρι της ημερας ταυτης[2:29]{.aside}

προφητης ουν υπαρχων και ειδως οτι ορκω ωμοσεν αυτω ο [θεος]{.greek-abbr} εκ καρπου της οσφυος αυτου το κατα σαρκα [αναστησειν]{.greek-omitted} [αναστησεις]{.greek-added} τον [χριστον]{.greek-abbr} [και]{.greek-added} καθισαι επι του θρονου αυτου[2:30]{.aside}

[προιδων]{.greek-omitted} [προειδως]{.greek-added} ελαλησεν [[ελαλησε]{.corr}]{.greek-added} περι της αναστασεως του [χριστου]{.greek-abbr} οτι [ου]{.greek-omitted} [ουκ]{.greek-added} [κατελειφθη]{.greek-omitted} [εγκατελειφθη]{.greek-added} η ψυχη αυτου εις αδου ουδε η σαρξ αυτου ειδεν [[ειδε]{.corr}]{.greek-added} διαφθοραν[2:31]{.aside}

τουτον τον [ιησουν]{.greek-abbr} ανεστησεν ο [θεος]{.greek-abbr} ου παντες ημεις εσμεν μαρτυρες[2:32]{.aside}

τη δεξια ουν του [θεου]{.greek-abbr} υψωθεις την τε επαγγελιαν του αγιου [πνευματος]{.greek-abbr} λαβων παρα του [πατρος]{.greek-abbr} εξεχεεν [[εξεχεε]{.corr}]{.greek-added} τουτο ο νυν υμεις βλεπετε και ακουετε[2:33]{.aside}

ου γαρ [δαυιδ]{.greek-abbr} ανεβη εις τους [ουρανους]{.greek-abbr} λεγει δε αυτος ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου[2:34]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[2:35]{.aside}

ασφαλως ουν γινωσκετω πας οικος [ισραηλ]{.greek-abbr} οτι και [κυριον]{.greek-abbr} και [χριστον]{.greek-abbr} αυτον ο [θεος]{.greek-abbr} εποιησεν [[εποιησε]{.corr}]{.greek-added} τουτον τον [ιησουν]{.greek-abbr} ον υμεις [εσταυρωσατε]{.greek-abbr}[2:36]{.aside}

ακουσαντες δε κατενυγησαν τη καρδια ειπον τε προς τον πετρον και τους λοιπους αποστολους τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} ανδρες αδελφοι[2:37]{.aside}

πετρος δε εφη προς αυτους μετανοησατε και βαπτισθητω εκαστος υμων επι τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εις αφεσιν αμαρτιων και ληψεσθε την δωρεαν του αγιου [πνευματος]{.greek-abbr}[2:38]{.aside}

υμιν γαρ εστιν η επαγγελια και τοις τεκνοις υμων και πασιν [[πασι]{.corr}]{.greek-added} τοις εις μακραν οσους αν προσκαλεσηται [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων[2:39]{.aside}

ετεροις τε λογοις πλειοσιν [[πλειοσι]{.corr}]{.greek-added} [διεμαρτυρετο]{.greek-omitted} [διεμαρτυρατο]{.greek-added} και παρεκαλει [αυτους]{.greek-added} λεγων σωθητε απο της γενεας της σκολιας ταυτης[2:40]{.aside}

οι μεν ουν ασμενως αποδεξαμενοι τον λογον αυτου εβαπτισθησαν και προσετεθησαν τη ημερα εκεινη ψυχαι ωσει τρισχιλιαι[2:41]{.aside}

ησαν δε προσκαρτερουντες τη διδαχη των αποστολων και τη κοινωνια και τη κλασει του αρτου και ταις προσευχαις[2:42]{.aside}

εγενετο δε παση ψυχη φοβος πολλα τε τερατα και σημεια [εγινετο]{.greek-added} δια των [χειρων]{.greek-added} [των]{.greek-added} αποστολων [εγινετο]{.greek-omitted} [εν]{.greek-added} [[ιερουσαλημ]{.greek-abbr}]{.greek-added}[2:43]{.aside}

παντες δε οι [πιστευοντες]{.greek-omitted} [πιστευσαντες]{.greek-added} ησαν επι το αυτο και ειχον απαντα κοινα[2:44]{.aside}

και τα κτηματα και τας υπαρξεις επιπρασκον και διεμεριζον αυτα [πασιν]{.greek-omitted} [πασι]{.greek-added} καθοτι αν τις χρειαν ειχεν [[ειχε]{.corr}]{.greek-added}[2:45]{.aside}

καθ ημεραν [τε]{.greek-omitted} [δε]{.greek-added} προσκαρτερουντες ομοθυμαδον εν τω ιερω κλωντες τε κατ οικον αρτον μετελαμβανον τροφης εν αγαλλιασει και αφελοτητι καρδιας[2:46]{.aside}

αινουντες τον [θεον]{.greek-abbr} και εχοντες χαριν προς ολον τον λαον ο δε [κυριος]{.greek-abbr} [προσετιθει]{.greek-omitted} [προσετιθη]{.greek-added} τους σωζομενους καθ ημεραν [εν]{.greek-added} τη εκκλησια[2:47]{.aside}

### Chapter 3

επι το αυτο δε πετρος και ιωαννης ανεβαινον εις το ιερον επι την ωραν της προσευχης την ενατην[3:1]{.aside}

και τις ανηρ χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων εβασταζετο ον ετιθουν καθ ημεραν προς την θυραν του ιερου την λεγομενην ωραιαν του αιτειν ελεημοσυνην παρα των εισπορευομενων [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [εν]{.greek-added} [τω]{.greek-added} [ιερω]{.greek-added}[3:2]{.aside}

ος ιδων πετρον και ιωαννην μελλοντας εισιεναι εις το ιερον ηρωτα ελεημοσυνην [λαβειν]{.greek-added}[3:3]{.aside}

ατενισας δε πετρος εις αυτον συν τω ιωαννη ειπεν [[ειπε]{.corr}]{.greek-added} βλεψον εις ημας[3:4]{.aside}

ο δε επειχεν αυτοις προσδοκων τι [λαβειν]{.greek-added} παρ αυτων [λαβειν]{.greek-omitted}[3:5]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε πετρος αργυριον και χρυσιον ουχ υπαρχει μοι ο δε εχω τουτο σοι [διδωμι]{.greek-omitted} [διδομι]{.greek-added} εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και [περιεπατει]{.greek-added} [περιπατει]{.corr}[3:6]{.aside}

και πιασας αυτον της δεξιας χειρος ηγειρεν [[ηγειρε]{.corr}]{.greek-added} παραχρημα δε εστερεωθησαν αυτου αι βασεις και τα σφυρα[3:7]{.aside}

και εξαλλομενος εστη και περιεπατει και εισηλθεν [[εισηλθε]{.corr}]{.greek-added} συν αυτοις εις το ιερον [πε]{.greek-added} [περιπατων]{.greek-omitted} [ριπατων]{.greek-added} και αλλομενος και αινων τον [θεον]{.greek-abbr}[3:8]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτον πας ο λαος περιπατουντα και αινουντα τον [θεον]{.greek-abbr}[3:9]{.aside}

επεγινωσκον τε αυτον οτι ουτος ην ο προς την ελεημοσυνην καθημενος επι τη ωραια πυλη του ιερου και επλησθησαν θαμβους και εκστασεως επι τω συμβεβηκοτι αυτω[3:10]{.aside}

κρατουντος δε του ιαθεντος χωλου [[χολου]{.corr}]{.greek-added} τον πετρον και ιωαννην συνεδραμεν [[συνεδραμε]{.corr}]{.greek-added} προς αυτους πας ο λαος [επι]{.greek-omitted} [εν]{.greek-added} τη στοα τη καλουμενη σολομωντος εκθαμβοι[3:11]{.aside}

ιδων δε πετρος απεκρινατο προς τον λαον ανδρες ισραηλιται τι θαυμαζετε επι τ[ου]{.greek-supplied}τω η ημιν τι ατενιζετε ως ιδια δυναμει η ευσεβεια πεποιηκοσιν [[πεποιηκοσι]{.corr}]{.greek-added} του περιπατειν αυτον[3:12]{.aside}

ο [θεος]{.greek-abbr} αβρααμ και [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} ισαακ και [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} ιακωβ ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων εδοξασεν [[εδοξασε]{.corr}]{.greek-added} τον παιδα αυτου [ιησουν]{.greek-abbr} ον υμεις μεν παρεδωκατε και ηρνησασθε αυτον κατα προσωπον πιλατου κριναντος εκεινου απολυειν[3:13]{.aside}

υμεις δε τον αγιον και δικαιον ηρνησασθε και ητησασθε ανδρα φονεα χαρισθηναι υμιν[3:14]{.aside}

τον δε αρχηγον της [ζωης]{.greek-omitted} [ζω]{.greek-added} [ης]{.greek-added} απεκτεινατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων ου ημεις μαρτυρες εσμεν[3:15]{.aside}

και επι τη πιστει του ονοματος αυτου τουτον ον θεωρειτε και οιδατε εστερεωσεν [[εστερεωσε]{.corr}]{.greek-added} το ονομα αυτου και η πιστις η δι αυτου εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[3:16]{.aside}

και νυν αδελφοι [οιδα]{.greek-omitted} [οιδατε]{.greek-added} οτι κατα αγνοιαν επραξατε ωσπερ και οι αρχοντες υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α προκατ[η]{.unclear}γγειλεν [[προκατ[η]{.unclear}γγειλε]{.corr}]{.greek-added} δια στοματος παντων των προφητων [αυτου]{.greek-omitted} παθειν τον [χριστον]{.greek-abbr} [αυτου]{.greek-added} επληρωσεν ουτως [[ουτω]{.corr}]{.greek-added}[3:18]{.aside}

μετανοησατε ουν και επιστρεψατε εις το [εξαλειφθηναι]{.greek-omitted} [εξαληφθηναι]{.greek-added} υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσιν]{.greek-added} [[ελθωσι]{.corr}]{.greek-added} [καιροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και αποστειλη τον προκεχειρισμενον υμιν [[ιησουν]{.greek-abbr}]{.greek-added} [χριστον]{.greek-abbr} [ιησουν]{.greek-omitted}[3:20]{.aside}

ον δει [ουρανον]{.greek-omitted} [[ουρανους]{.greek-abbr}]{.greek-added} μεν [δεξασθαι]{.greek-omitted} [δεξασθε]{.greek-added} αχρι χρονων αποκαταστασεως παντων ων ελαλησεν ο [θεος]{.greek-abbr} δ[ι]{.unclear}α στοματος παντων των αγιων αυτου προφητων απ αιωνος[3:21]{.aside}

[μωσης]{.greek-omitted} []{.greek-added} μωυσης [γαρ]{.greek-omitted} μεν προς τους [πατερας]{.greek-abbr} ειπεν οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [ημων]{.greek-omitted} [[θεος]{.greek-abbr}]{.greek-added} υμων εκ των αδελφων υμων [ω]{.unclear}ς [εμε]{.greek-supplied} αυτου ακουσεσθε κατα παντα οσα [λαληση]{.greek-omitted} [[αν]{.unclear}]{.greek-added} [λαλ]{.unclear}ησει προς[3:22]{.aside}

εσται δε πασα ψυχη ητις εαν μη ακουση του προφητου εκεινου εξολοθρευθησεται εκ του λαου[3:23]{.aside}

και παντες δε οι προφηται απο σαμουηλ και των καθεξης οσοι ελαλησαν και [κατηγγειλαν]{.greek-omitted} [προκατηγγειλαν]{.greek-added} τας ημερας ταυτας[3:24]{.aside}

υμεις εστε υιοι των προφητων και της διαθηκης ης διεθετο ο [θεος]{.greek-abbr} προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} λεγων προς αβρααμ και εν τω σπερματι σου ενευλογηθησονται πασαι αι πατριαι της γης[3:25]{.aside}

υμιν [ουν]{.greek-added} πρωτον [αναστησας]{.greek-added} ο [θεος]{.greek-abbr} [αναστησας]{.greek-omitted} τον παιδα αυτου [ιησουν]{.greek-abbr} απεστειλεν αυτον ευλογουντα υμας εν τω αποστρεφειν [εκαστον]{.greek-omitted} [εκαστος]{.greek-added} απο των πονηριων υμων[3:26]{.aside}

### Chapter 4

λαλουντων δε αυτων προς τον λαον επεστησαν αυτοις οι ιερεις και ο στρατηγος του ιερου και οι σαδδουκαιοι[4:1]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον λαον και καταγγελλειν εν τω [ιησου]{.greek-abbr} την αναστασιν [των]{.greek-omitted} [την]{.greek-added} [εκ]{.greek-added} νεκρων[4:2]{.aside}

και επεβαλον αυτοις τας χειρας και εθεντο [αυτους]{.greek-added} εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι δε των ακουσαντων τον λογον επιστευσαν και εγενηθη ο αριθμος των ανδρων ωσει χιλιαδες πεντε[4:4]{.aside}

εγενετο δε επι την αυριον συναχθηναι αυτων τους αρχοντας και [τους]{.greek-added} πρεσβυτερους και γραμματεις εις [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και ανναν τον αρχιερεα και καιαφαν και ιωαννην και αλεξανδρον και οσοι ησαν εκ γενους αρχιερατικου[4:6]{.aside}

και στησαντες αυτους εν μεσω επυνθανοντο εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος πλησθεις [πνευματος]{.greek-abbr} αγιου ειπεν [[ειπε]{.corr}]{.greek-added} προς αυτους αρχοντες του λαου και πρεσβυτεροι του [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα επι ευεργεσια [ανθρωπου]{.greek-abbr} ασθενους εν τινι ουτος σεσωσται[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω [ισραηλ]{.greek-abbr} οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις [εσταυρωσατε]{.greek-abbr} ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν τουτω ουτος παρεστηκεν ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ υμων των οικοδομουντων ο γενομενος εις κεφαλην γωνιας[4:11]{.aside}

και ουκ εστιν εν αλλω ουδενι [η]{.greek-omitted} [σωτηρια]{.greek-abbr} ουτε γαρ ονομα [ετερον]{.greek-added} εστιν [ετερον]{.greek-omitted} [υπο]{.greek-added} [τον]{.greek-added} [[ουρανον]{.greek-abbr}]{.greek-added} το δεδομενον εν [ανθρωποις]{.greek-abbr} εν ω δει σωθηναι ημας[4:12]{.aside}

θεωρουντες δε την του πετρου παρρησιαν και ιωαννου και καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι εισιν [[εισι]{.corr}]{.greek-added} και ιδιωται εθαυμαζον επεγινωσκον τε αυτους οτι συν τω [ιησου]{.greek-abbr} ησαν[4:13]{.aside}

τον [δε]{.greek-omitted} [τε]{.greek-added} [ανθρωπον]{.greek-abbr} βλεποντες συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου απελθειν συνεβαλλον προς αλληλους[4:15]{.aside}

λεγοντες τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} τοις [ανθρωποις]{.greek-abbr} τουτοις οτι μεν γαρ γνωστον σημειον γεγονεν [[γεγονε]{.corr}]{.greek-added} δι αυτων πασιν [[πασι]{.corr}]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} φανερον και ου δυναμεθα αρνησασθαι[4:16]{.aside}

αλλ ινα μη επι πλειον διανεμηθη εις τον λαον απειλη απειλησομεθα αυτοις μηκετι λαλειν επι τω ονοματι τουτω μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και καλεσαντες αυτους παρηγγειλαν αυτοις το καθολου μη φθεγγεσθαι μηδε διδασκειν επι τω ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

[τοτε]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} πετρος και ιωαννης αποκριθεντες προς αυτους ειπον ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ ημεις α [ειδομεν]{.greek-omitted} [ιδαμεν]{.greek-added} και ηκουσαμεν μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως κολασονται αυτους δια τον λαον οτι παντες εδοξαζον τον [θεον]{.greek-abbr} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε ηλθον προς τους ιδιους και [απηγγειλαν]{.greek-omitted} [ανηγγειλαν]{.greek-added} οσα προς αυτους οι αρχιερεις και οι πρεσβυτεροι ειπον[4:23]{.aside}

οι δε ακουσαντες ομοθυμαδον ηραν φωνην προς τον [θεον]{.greek-abbr} και ειπον δεσποτα συ ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[4:24]{.aside}

ο δια στοματος [δαυιδ]{.greek-abbr} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

παρεστησαν οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας επι τον αγιον παιδα σου [ιησουν]{.greek-abbr} ον εχρισας ηρωδης [τε]{.unclear} και ποντιος πιλατος συν εθνεσιν [[εθνεσι]{.corr}]{.greek-added} και λα[οι]{.greek-supplied}ς [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η βουλη σου προωρισεν [[προωρισε]{.corr}]{.greek-added} γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} επιδε επι τας απειλας αυτων και δος τοις δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την [χειρα]{.greek-omitted} [χει]{.greek-added} [ρα]{.greek-added} σου εκτεινειν σε εις ιασιν και σημεια και τερατα γινεσθαι δια του ονοματος του αγιου παιδος σου [ιησου]{.greek-abbr}[4:30]{.aside}

και δεηθεντων αυτων εσαλευθη ο τοπος εν ω ησαν συνηγμενοι και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και [ελαλουν]{.greek-omitted} [ελαλησαν]{.greek-added} τον λογον του [θεου]{.greek-abbr} μετα παρρησιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και ουδε εις τι των υπαρχοντων αυτων ελεγεν ιδιον ειναι αλλ ην αυτοις απαντα κοινα[4:32]{.aside}

και μεγαλη δυναμει απεδιδουν το μαρτυριον οι αποστολοι της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} χαρις τε μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις υπηρχεν εν αυτοις οσοι γαρ [κτητωρες]{.greek-added} [κτητορες]{.corr} χωριων η οικιων [υπηρχον]{.greek-omitted} [υπηρχων]{.greek-added} πωλουντες εφερον τας τιμας των πιπρασκομενων[4:34]{.aside}

και ετιθουν παρα τους ποδας των αποστολων διεδιδοτο δε εκαστω καθοτι αν τις χρειαν ειχεν[4:35]{.aside}

[ιωσης]{.greek-omitted} [ιωσηφ]{.greek-added} δε ο επικληθεις βαρναβας απο των αποστολων ο εστιν [[εστι]{.corr}]{.greek-added} μεθερμηνευομενον [υιος]{.greek-abbr} παρακλησεως λευιτης κυπριος τω γενει[4:36]{.aside}

υπαρχοντος αυτω αγρου πωλησας ηνεγκεν [[ηνεγκε]{.corr}]{.greek-added} το χρημα και εθηκεν [[εθηκε]{.corr}]{.greek-added} παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις ανανιας ονοματι συν σαπφειρη τη γυναικι αυτου [επωλησεν]{.greek-omitted} [επωλυσεν]{.greek-added} [[επωλυσε]{.corr}]{.greek-added} κτημα[5:1]{.aside}

και ενοσφισατο απο της τιμης συνειδυιας και της γυναικος αυτου [και]{.greek-omitted} ενεγκας μερος τι παρα τους ποδας των αποστολων εθηκεν[5:2]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε πετρος [προς]{.greek-added} [αυτω]{.greek-added} ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι [σε]{.greek-omitted} απο της τιμης του χωριου[5:3]{.aside}

ουχι μενον σοι εμενεν [[εμενε]{.corr}]{.greek-added} και πραθεν εν τη ση εξουσια υπηρχεν [[υπηρχε]{.corr}]{.greek-added} τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε ο ανανιας τους λογους τουτους πεσων εξεψυξεν [[εξεψυξε]{.corr}]{.greek-added} και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι νεωτεροι συνεστειλαν αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων διαστημα και η γυνη αυτου μη ειδυια το γεγονος εισηλθεν[5:7]{.aside}

απεκριθη δε αυτη ο πετρος ειπε μοι ει τοσουτου το χωριον απεδοσθε η δε ειπεν [[ειπε]{.corr}]{.greek-added} ναι τοσουτου[5:8]{.aside}

ο δε πετρος ειπεν [[ειπε]{.corr}]{.greek-added} προς αυτην τι οτι [συνε]{.greek-added} [συνεφωνηθη]{.greek-omitted} [φωνηθη]{.greek-added} υμιν πειρασαι το [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ιδου οι ποδες των θαψαντων τον ανδρα σου επι τη θυρα και εξοισουσιν [[εξοισουσι]{.corr}]{.greek-added} σε[5:9]{.aside}

επεσεν [[επεσε]{.corr}]{.greek-added} δε παραχρημα παρα τους ποδας αυτου και [εξ]{.greek-supplied}εψυξεν εισελθοντες δε οι νεανισκοι ευ[ρον]{.greek-supplied} αυτην νεκραν και εξενεγκαντες εθα[ψ]{.greek-supplied}αν προς τον ανδρα αυτης[5:10]{.aside}

και εγενετο φοβος μεγας [εφ]{.greek-omitted} [ολην]{.greek-omitted} [επι]{.greek-added} [πασαν]{.greek-added} την εκκλησιαν και επι παντας τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων εγινετο σημεια και τερατα εν τω λαω πολλα και ησαν ομοθυμαδον απαντες εν τη στοα [σολομωντος]{.greek-omitted} [σολομωνος]{.greek-added}[5:12]{.aside}

των δε λοιπων ουδεις ετολμα κολλασθαι αυτοις αλλ εμεγαλυνεν αυτους ο λαος[5:13]{.aside}

 μαλλον δε προσετιθεντο πιστευοντες τω [κυριω]{.greek-abbr} πληθη ανδρων [τε]{.greek-supplied} [και]{.greek-supplied}[5:14]{.aside}

ωστε κατα τας πλατειας εκφερειν τους ασθενεις και τιθεναι επ[ι]{.unclear} κλινων και [κραββατων]{.greek-omitted} [κραβαττων]{.greek-added} ινα [ερχομενου]{.greek-omitted} [διερχομενου]{.greek-added} πετρου καν η σκια [επισκιαση]{.greek-omitted} [επισκιασει]{.greek-added} τινι αυτων[5:15]{.aside}

συνηρχετο δε και το πληθος των περιξ πολεων εις [ιερουσαλημ]{.greek-abbr} φεροντες ασθενεις και οχλουμενους υπο [πνευματων]{.greek-abbr} ακαθαρτων οιτινες εθεραπευοντο απαντες[5:16]{.aside}

αναστας δε ο αρχιερευς και παντες οι συν αυτω η ουσα αιρεσις των σαδδουκαιων επλησθησαν ζηλου[5:17]{.aside}

και επεβαλον τας χειρας αυτων επι τους αποστολους και εθεντο αυτους εν τηρησει δημοσια[5:18]{.aside}

αγγελος δε [κυριου]{.greek-abbr} δια [της]{.greek-omitted} νυκτος [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τας θυρας της φυλακης εξαγαγων τε αυτους ειπεν [[ειπε]{.corr}]{.greek-added}[5:19]{.aside}

πορευεσθε και σταθεντες λαλειτε εν τω ιερω τω λαω παντα τα ρηματα της ζωης ταυτης[5:20]{.aside}

ακουσαντες δε εισηλθον υπο τον ορθρον εις το ιερον και εδιδασκον παραγενομενος δε ο αρχιερευς και οι συν αυτω συνεκαλεσαν το συνεδριον και π[ασαν]{.unclear} την γερουσιαν των υιων [ισραηλ]{.greek-abbr} και απεστειλαν εις το δεσμωτηριον αχθηναι αυτους[5:21]{.aside}

[οι]{.greek-supplied} δε υπηρεται παραγενομενοι ουχ ευρον αυτους εν τη φυλακη αναστρεψαντες δε απηγγειλαν[5:22]{.aside}

λεγοντες οτι το μεν δεσμω[τη]{.greek-supplied}ριον [ευρομεν]{.greek-omitted} [ευρωμεν]{.greek-added} [κεκλεισμενων]{.greek-added} [κεκλεισμενον]{.corr} εν παση [α]{.greek-supplied}σφαλεια και τους φυλακας εστωτας π[ρο]{.greek-supplied} των θυρων ανοιξαντες δε εσω ουδενα ευρομεν[5:23]{.aside}

ως δε ηκουσαν τους λογους τουτους ο τε ιερευς και ο στρατηγος του ιερου και οι [σαδδου]{.greek-added} [καιοι]{.greek-added} [και]{.greek-added} [οι]{.greek-added} αρχιερεις διηπορουν περι αυτων τι αν γενοιτο τουτο[5:24]{.aside}

παραγενομενος δε τις απηγγειλεν αυτοις οτι ιδου οι ανδρες ους εθεσθε εν τη φυλακη εισιν εν τω ιερω εστωτες και διδασκοντες τον λαον[5:25]{.aside}

τοτε απελθων ο στρατηγος συν τοις υπηρεταις ηγαγεν αυτους ου μετα βιας εφοβουντο γαρ τον λαον ινα μη λιθασθωσιν[5:26]{.aside}

αγαγοντες δε αυτους εστησαν εν τω συνεδριω και επηρωτησεν αυτους ο αρχιερευς[5:27]{.aside}

λεγων ου παραγγελια παρηγγειλαμεν υμιν μη διδασκειν επι τω ονοματι τουτω και ιδου πεπληρωκατε την [ιερουσαλημ]{.greek-abbr} της διδαχης υμων και βουλεσθε επαγαγειν εφ ημας το αιμα του [ανθρωπου]{.greek-abbr} τουτου[5:28]{.aside}

αποκριθεις δε πετρος και οι αποστολοι ειπον πειθαρχειν δει [θεω]{.greek-abbr} μαλλον η [ανθρωποις]{.greek-abbr}[5:29]{.aside}

ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων ηγειρεν [ιησουν]{.greek-abbr} ον υμεις διεχειρισασθε κρεμασαντες επι ξυλου[5:30]{.aside}

τουτον ο [θεος]{.greek-abbr} αρχηγον και [σωτηρα]{.greek-abbr} υψωσεν [[υψωσε]{.corr}]{.greek-added} τη δεξια αυτου δουναι μετανοιαν τω [ισραηλ]{.greek-abbr} και αφεσιν αμαρτιων[5:31]{.aside}

και ημεις εσμεν [αυτου]{.greek-omitted} μαρτυρες των ρηματων τουτων και το [πνευμα]{.greek-abbr} δε το αγιον ο εδωκεν ο [θεος]{.greek-abbr} τοις πειθαρχουσιν αυτω[5:32]{.aside}

οι δε [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} διεπριοντο και [εβουλευοντο]{.greek-omitted} [εβουλοντο]{.greek-added} ανελειν αυτους[5:33]{.aside}

αναστας δε τις εν τω συνεδριω φαρισαιος ονοματι γαμαλιηλ νομοδιδασκαλος τιμιος παντι τω λαω εκελευσεν εξω [βραχυ]{.greek-omitted} [τι]{.greek-omitted} τους αποστολους [βραχυ]{.greek-added} ποιησαι[5:34]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} τε προς αυτους ανδρες ισραηλιται προσεχετε εαυτοις επι τοις [ανθρωποις]{.greek-abbr} τουτοις τι μελλετε πρασσειν[5:35]{.aside}

προ γαρ τουτων των ημερων ανεστη θευδας λεγων ειναι τινα εαυτον ω [προσεκληθη]{.greek-omitted} [προσεκολληθη]{.greek-added} αριθμος ανδρων ωσει τετρακοσιων ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις ουδεν[5:36]{.aside}

μετα τουτον ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της απογραφης και [απεστησεν]{.greek-omitted} [απεστησε]{.greek-added} λαον ικανον οπισω αυτου κακεινος απωλετο και παντες οσοι επειθοντο αυτω διεσκορπισθησαν[5:37]{.aside}

και τα νυν λεγω υμιν αποστητε απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε αυτους οτι εαν η εξ [ανθρωπων]{.greek-abbr} η βουλη [αυτη]{.greek-added} η το εργον τουτο καταλυθησεται[5:38]{.aside}

ει δε εκ [θεου]{.greek-abbr} εστιν ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} καταλυσαι αυτο μηποτε και θεομαχοι ευρεθητε [επεισθησαν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added}[5:39]{.aside}

[επεισθησαν]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} και προσκαλεσαμενοι τους αποστολους δειραντες παρηγγειλαν μη λαλειν επι τω ονοματι [του]{.greek-omitted} [ιησου]{.greek-abbr} και απελυσαν αυτους[5:40]{.aside}

οι μεν ουν επορευοντο χαιροντες απο προσωπου του συνεδριου οτι υπερ του ονοματος [του]{.greek-omitted} [αυτου]{.greek-added} [ιησου]{.greek-omitted} κατηξιωθησαν ατιμασθηναι[5:41]{.aside}

πασαν τε ημεραν εν τω ιερω και κατ οικον ουκ επαυοντο διδασκοντες και ευαγγελιζομενοι [ιησουν]{.greek-omitted} τον [χριστον]{.greek-abbr}[5:42]{.aside}

### Chapter 6

εν δε ταις ημεραις ταυταις πληθυνοντων των μαθητων εγενετο γογγυσμος των ελληνιστων προς τους εβραιους οτι παρεθεωρουντο εν τη διακονια τη καθημερινη αι χηραι αυτων[6:1]{.aside}

προσκαλεσαμενοι δε οι δωδεκα το πληθος των μαθητων ειπον ουκ αρεστον εστιν ημας καταλειψαντας τον λογον του [θεου]{.greek-abbr} διακονειν τραπεζαις[6:2]{.aside}

επισκεψασθε ουν αδελφοι ανδρας εξ υμων μαρτυρουμενους επτα πληρεις [πνευματος]{.greek-abbr} αγιου και σοφιας ους καταστησωμεν επι της χρειας ταυτης[6:3]{.aside}

ημεις δε τη προσευχη και τη διακονια του λογου [προσκαρτερησομεν]{.greek-omitted} [προσκαρτερησωμεν]{.greek-added}[6:4]{.aside}

και ηρεσεν ο λογος ενωπιον παντος του πληθους και εξελεξαντο στεφανον ανδρα πληρης πιστεως και [πνευματος]{.greek-abbr} αγιου και φιλιππον και προχορον και [νικανορα]{.greek-omitted} [νικανωρα]{.greek-added} και τιμωνα και παρμεναν και νικολαον προσηλυτον αντιοχεα[6:5]{.aside}

ους εστησαν ενωπιον των αποστολων και προσευξαμενοι επεθηκαν αυτοις τας χειρας[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} ηυξανεν [[ηυξανε]{.corr}]{.greek-added} και επληθυνετο ο αριθμος των μαθητων εν ιερουσαλημ σφοδρα πολυς τε οχλος των ιερεων υπηκουον τη πιστει[6:7]{.aside}

στεφανος δε πληρης [πιστεως]{.greek-omitted} [χαριτος]{.greek-added} και δυναμεως εποιει τερατα και σημεια μεγαλα εν τω λαω [δια]{.greek-added} [του]{.greek-added} [ονοματος]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added}[6:8]{.aside}

ανεστησαν δε τινες των εκ της συναγωγης της λεγομενης λιβερτινων και [κυρηναιων]{.greek-omitted} [κυριναιων]{.greek-added} και αλεξανδρεων και των απο κιλικιας και ασιας συζητουντες τω στεφανω[6:9]{.aside}

και ουκ ισχυον αντιστηναι τη σοφια και τω [πνευματι]{.greek-abbr} ω ελαλει[6:10]{.aside}

τοτε υπεβαλον ανδρας λεγοντας οτι ακηκοαμεν αυτου λαλουντος ρηματα βλασφημα εις [μωσην]{.greek-omitted} [μωϋσην]{.greek-added} και τον [θεον]{.greek-abbr}[6:11]{.aside}

συνεκινησαν τε τον λαον και τους πρεσβυτερους και τους γραμματεις και επισταντες συνηρπασαν αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας ψευδεις λεγοντας ο [ανθρωπος]{.greek-abbr} ουτος ου παυεται ρηματα βλασφημα λαλων κατα του τοπου του αγιου [τουτου]{.greek-added} και του νομου[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος καταλυσει τον τοπον τουτον και αλλαξει τα εθη α [παρεδωκεν]{.greek-omitted} [περεδωκεν]{.greek-added} ημιν [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[6:14]{.aside}

και ατενισαντες εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω [ειδον]{.greek-omitted} [ιδον]{.greek-added} το προσωπον αυτου ωσει προσωπον αγγελου[6:15]{.aside}

### Chapter 7

ειπεν [[ειπε]{.corr}]{.greek-added} δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} ημων αβρααμ [οντι]{.greek-omitted} [οτι]{.greek-added} εν τη μεσοποταμια πριν η κατοικησαι αυτον εν [χαρραν]{.greek-omitted} [χαραν]{.greek-added}[7:2]{.aside}

και ειπεν [[ειπε]{.corr}]{.greek-added} προς αυτον εξελθε εκ της γης σου και εκ της συγγενειας σου και δευρο εις γην ην αν σοι δειξω[7:3]{.aside}

τοτε εξελθων εκ γης χαλδαιων κατωκησεν [εν]{.greek-omitted} [εις]{.greek-added} χαρραν κακειθεν μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μετωκησεν]{.greek-added} αυτον εις την γην ταυτην εις ην [και]{.greek-added} υμεις νυν κατοικειτε[7:4]{.aside}

και ουκ εδωκεν αυτω κληρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι αυτω εις κατασχεσιν αυτην και τω σπερματι αυτου μετ αυτον ουκ οντος αυτω τεκνου[7:5]{.aside}

ελαλησεν [[ελαλησε]{.corr}]{.greek-added} δε [ουτως]{.greek-omitted} [αυτω]{.greek-added} ο [θεος]{.greek-abbr} οτι εσται το σπερμα αυτου παροικον εν γη αλλοτρια και δουλωσουσιν αυτο και κακωσουσιν ετη τετρακοσια[7:6]{.aside}

και το εθνος [ω]{.greek-omitted} [ο]{.greek-added} εαν δουλευσωσιν [[δουλευσωσι]{.corr}]{.greek-added} κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και [λατρευσουσιν]{.greek-omitted} [λατρευσωσιν]{.greek-added} [[λατρευσωσι]{.corr}]{.greek-added} μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και ουτως εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον ισαακ και περιετεμεν αυτον τη [ογδοη]{.greek-added} ημερα [τη]{.greek-omitted} [ογδοη]{.greek-omitted} και ο ισαακ τον ιακωβ και ο ιακωβ τους δωδεκα πατριαρχας[7:8]{.aside}

και οι πατριαρχαι ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και εξειλετο αυτον εκ πασων των θλιψεων αυτου και εδωκεν αυτω χαριν και σοφιαν εναντιον φαραω βασιλεως αιγυπτου και κατεστησεν αυτον ηγουμενον επ αιγυπτον και [εφ]{.greek-added} ολον τον οικον αυτου[7:10]{.aside}

ηλθεν [[ηλθε]{.corr}]{.greek-added} δε λιμος εφ ολην την γην αιγυπτου και χανααν και θλιψις μεγαλη και ουχ ευρισκον χορτασματα οι [πατερες]{.greek-abbr} ημων[7:11]{.aside}

ακουσας δε ιακωβ οντα σιτα εν αιγυπτω εξαπεστειλεν [[εξαπεστειλε]{.corr}]{.greek-added} τους [πατερας]{.greek-abbr} ημων πρωτον[7:12]{.aside}

και εν τω δευτερω [ανεγνωρισθη]{.greek-omitted} [ανεγνωσθη]{.greek-added} ιωσηφ τοις αδελφοις αυτου και φανερον εγενετο τ[ω]{.unclear} φ[αρα]{.greek-supplied}ω το γενος του ιωσηφ[7:13]{.aside}

αποστειλας δε [ο]{.greek-added} ιωσηφ μετεκαλεσατο τον [πατερα]{.greek-abbr} αυτου ιακωβ και πασαν την συγγενειαν [αυτου]{.greek-added} εν ψυχαις εβδομηκοντα πεντε[7:14]{.aside}

κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν αυτος και οι [πατερες]{.greek-abbr} ημων[7:15]{.aside}

και μετετεθησαν εις συχεμ και ετεθησαν εν τω μνηματι [ο]{.greek-omitted} [ω]{.greek-added} ωνησατο αβρααμ τιμης αργυριου παρα των υιων εμμορ του συχεμ[7:16]{.aside}

καθως δε ηγγιζεν ο χρονος της επαγγελιας ης ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος [επ]{.greek-added} [αιγυπτον]{.greek-added} ος ουκ ηδει τον ιωσηφ[7:18]{.aside}

ουτος κατασ[ο]{.unclear}φισαμενος το γενος ημων εκακωσεν [[εκακωσε]{.corr}]{.greek-added} τους [πατερας]{.greek-abbr} ημων του ποιειν εκθετα τα βρεφη [αυτων]{.greek-omitted} [ημων]{.greek-added} εις το μη ζωογονεισθαι[7:19]{.aside}

εν ω καιρω εγεννηθη [μωσης]{.greek-omitted} [μωϋσης]{.greek-added} και ην αστειος τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr} [αυτου]{.greek-added}[7:20]{.aside}

εκτεθεντα δε αυτον [ανειλετο]{.greek-omitted} [ανειλατο]{.greek-added} [αυτον]{.greek-added} η θυγατηρ φαραω και ανεθρεψατο αυτον [εαυτη]{.greek-omitted} [εαυτης]{.greek-added} εις [υιον]{.greek-abbr}[7:21]{.aside}

και επαιδευθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σοφια αιγυπτιων ην δε δυνατος εν λογοις και [εν]{.greek-added} εργοις [αυτου]{.greek-added}[7:22]{.aside}

ως δε επληρουτο αυτω [τεσσαρακονταετης]{.greek-omitted} [τεσσερακονταετης]{.greek-added} χρονος ανεβη επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον η[μ]{.unclear}υνατο και εποιησεν εκδικησιν τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

ενομιζεν [[ενομιζε]{.corr}]{.greek-added} δε συνιεναι τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις [σωτηριαν]{.greek-abbr} οι δε ου συνηκαν[7:25]{.aside}

τη τε επιουση ημερα ωφθη αυτοις μαχομενοις και συνηλασεν αυτους εις ειρηνην ειπων ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} αδικειτε αλληλους[7:26]{.aside}

ο δε αδικων τον πλησιον απωσατο αυτον ειπων τις σε κατεστησεν αρχοντα και δικαστην εφ [ημας]{.greek-omitted} [ημων]{.greek-added}[7:27]{.aside}

μη ανελειν με συ [θελεις]{.greek-omitted} [θελης]{.greek-added} ον τροπον ανειλες χθες τον αιγυπτιον[7:28]{.aside}

εφυγεν [[εφυγε]{.corr}]{.greek-added} δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} ωφθη αυτω εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-abbr} εν φλογι πυρος βατου[7:30]{.aside}

ο δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ιδων εθαυμαζεν [[εθαυμαζε]{.corr}]{.greek-added} το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} προς αυτον[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} σου ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ εντρομος δε [γενομενος]{.greek-omitted} [γεναμενος]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουκ ετολμα κατανοησαι[7:32]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε αυτω ο [κυριος]{.greek-abbr} λυσον το υποδημα των ποδων σου ο γαρ τοπος εν ω εστηκας γη αγια εστιν[7:33]{.aside}

ιδων [ειδον]{.greek-omitted} [ιδον]{.greek-added} την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και κατεβην [του]{.greek-added} εξελεσθαι αυτους και νυν δευρο αποστελω σε εις αιγυπτον[7:34]{.aside}

τουτον τον [μωσην]{.greek-omitted} [μωυσην]{.greek-added} ον ηρνησαντο ειποντες τις σε κατεστησεν αρχοντα και δικαστην τουτον ο [θεος]{.greek-abbr} αρχοντα και λυτρωτην απεστειλεν εν χειρι αγγελου του οφθεντος αυτω εν τη βατω[7:35]{.aside}

ουτος εξηγαγεν αυτους ποιησας τερατα και σημεια εν γη αιγυπτω και εν ερυθρα θαλασση και εν τη ερημω ετη [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added}[7:36]{.aside}

ουτος εστιν ο [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο [λογον]{.greek-omitted} [λογια]{.greek-added} ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθελησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων [αλλ]{.greek-omitted} [αλλα]{.greek-added} απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

ειποντες τω ααρων ποιησον ημιν θεους οι προπορευσονται ημων ο γαρ [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις εκειναις και ανηγαγον θυσιαν τω ειδωλω και [ευφραινοντο]{.greek-omitted} [ηυφραινοντο]{.greek-added} εν τοις εργοις των χειρων αυτων[7:41]{.aside}

εστρεψεν [[εστρεψε]{.corr}]{.greek-added} δε ο [θεος]{.greek-abbr} και παρεδωκεν αυτους λατρευειν τη στρατια του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη σφαγια και θυσιας προσηνεγκατε μοι ετη [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} εν τη ερημω οικος [ισραηλ]{.greek-abbr}[7:42]{.aside}

και ανελαβετε την σκηνην του [μολοχ]{.greek-omitted} [μοχολ]{.greek-added} και το αστρον του [θεου]{.greek-abbr} υμων [ρεμφαν]{.greek-omitted} [ρεφα]{.greek-added} τους τυπους ους εποιησατε προσκυνειν αυτοις και μετοικιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου [ην]{.greek-omitted} [εν]{.greek-added} τοις πατρασιν ημων εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωυση]{.greek-added} ποιησαι αυτην κατα τον τυπον ον [εωρακει]{.greek-omitted} [εωρακεν]{.greek-added}[7:44]{.aside}

ην και εισηγαγον διαδεξαμενοι οι [πατερες]{.greek-abbr} ημων μετα ιησου εν τη κατασχεσει των εθνων ων εξωσεν ο [θεος]{.greek-abbr} απο προσωπου των [πατερων]{.greek-abbr} ημων εως των ημερων [δαυιδ]{.greek-abbr}[7:45]{.aside}

ος ευρεν [[ευρε]{.corr}]{.greek-added} χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν αυτω οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις ναοις κατοικει καθως ο προφητης λεγει[7:48]{.aside}

ο [ουρανος]{.greek-abbr} μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον [οικοδομησετε]{.greek-omitted} [οικοδομησεται]{.greek-added} μοι λεγει [κυριος]{.greek-abbr} η τις τοπος της καταπαυσεως μου[7:49]{.aside}

ουχι η χειρ μου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} ταυτα παντα[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια και τοις ωσιν υμεις αει τω [πνευματι]{.greek-abbr} τω αγιω αντιπιπτετε ως οι [πατερες]{.greek-abbr} υμων και υμεις[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι [πατερες]{.greek-abbr} υμων και απεκτειναν τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις προδοται και φονεις [γεγενησθε]{.greek-omitted} [εγενεσθε]{.greek-added}[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

ακουοντες δε ταυτα διεπριοντο ταις καρδιαις αυτων και [ε]{.greek-added} [εβρυχον]{.greek-omitted} [βρυχον]{.greek-added} τους οδοντας επ αυτον[7:54]{.aside}

υπαρχων δε πληρης [πνευματος]{.greek-abbr} αγιου ατενισας εις τον [ουρανον]{.greek-abbr} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [[ιδε]{.corr}]{.greek-added} δοξαν [θεου]{.greek-abbr} και [ιησουν]{.greek-abbr} εστωτα εκ δεξιων του [θεου]{.greek-abbr}[7:55]{.aside}

και ειπεν ιδου θεωρω τους [ουρανους]{.greek-abbr} ανεωγμενους και τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη συνεσχον τα ωτα αυτων και ωρμησαν ομοθυμαδον επ αυτον[7:57]{.aside}

και εκβαλοντες [αυτον]{.greek-added} εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τα ιματια [αυτων]{.greek-added} παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} δεξαι το πνευμα μου[7:59]{.aside}

θεις δε τα γονατα εκραξεν [[εκραξε]{.corr}]{.greek-added} φωνη μεγαλη [κυριε]{.greek-abbr} μη στησης αυτοις την αμαρτιαν ταυτην και τουτο ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

σαυλος δε ην συνευδοκων τη αναιρεσει αυτου εγενετο δε εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις παντες δε διεσπαρησαν κατα τας χωρας της ιουδαιας και σαμαρειας πλην των αποστολων[8:1]{.aside}

[συνεκομισαν]{.greek-omitted} [συνεκομησαν]{.greek-added} δε τον στεφανον ανδρες ευλαβεις και [εποιησαντο]{.greek-omitted} [εποιησαν]{.greek-added} [το]{.greek-added} κοπετον μεγαν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[8:2]{.aside}

σαυλος δε ελυμαινετο την εκκλησιαν κατα τους οικους εισπορευομενος συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπαρεντες διηλθον ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος δε κατελθων εις πολιν της σαμαρειας εκηρυσσεν αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον τε οι οχλοι τοις λεγομενοις υπο του φιλιππου ομοθυμαδον εν τω ακουειν αυτους και βλεπειν τα σημεια α εποιει[8:6]{.aside}

πολλων γαρ [των]{.greek-omitted} [τον]{.greek-added} εχοντων πνευματα ακαθαρτα βοωντα φωνη μεγαλη [εξηρχετο]{.greek-omitted} [εξηρχοντο]{.greek-added} πολλοι δε παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

και εγενετο χαρα μεγαλη εν τη πολει εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι σιμων προυπηρχεν εν τη πολει μαγευων και εξιστων το εθνος της σαμαρειας λεγων ειναι τινα εαυτον μεγαν[8:9]{.aside}

ω προσειχον [παντες]{.greek-added} απο μικρου εως μεγαλου λεγοντες ουτος εστιν η δυναμις του [θεου]{.greek-abbr} η μεγαλη[8:10]{.aside}

προσειχον δε αυτω δια [το]{.greek-omitted} [τω]{.greek-added} ικανω χρονω ταις [μαγειαις]{.greek-omitted} [μαγιαις]{.greek-added} εξεστακεναι αυτους[8:11]{.aside}

οτε δε επιστευσαν τω φιλιππω ευαγγελιζομενω τα περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος επιστευσεν [[επιστευσε]{.corr}]{.greek-added} και βαπτισθεις ην προσκαρτερων τω φιλιππω θεωρων τε δυναμεις [μεγαλας]{.greek-added} και σημεια γινομενα εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} απεστειλαν προς αυτους τον πετρον και ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως λαβωσιν [[λαβωσι]{.corr}]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

ουπω γαρ ην επ ουδενι αυτων επιπεπτωκος μονον δε βεβαπτισμενοι υπηρχον εις το ονομα του [χριστου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr}[8:16]{.aside}

τοτε επετιθουν τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

θεασαμενος δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω [εαν]{.greek-omitted} [αν]{.greek-added} [και]{.greek-added} επιθω τας χειρας [λαμβανη]{.greek-omitted} [λαμβανει]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε ειπεν [[ειπε]{.corr}]{.greek-added} προς αυτον το αργυριον σου συν σοι ειη εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} ενομισας δια χρηματων κτασθαι[8:20]{.aside}

ου[κ]{.unclear} [ε]{.unclear}στιν [[[ε]{.unclear}στι]{.corr}]{.greek-added} σοι μ[ε]{.unclear}ρις ουδε κληρος εν τω λογ[ω]{.unclear} τουτω [η]{.unclear} γαρ καρδια σου ουκ εστιν [ευ]{.unclear}θεια εν[ω]{.unclear}πιον του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} ει αρα [α]{.greek-supplied}φεθησεται σοι η επινοια τη[ς]{.unclear} καρδιας σου[8:22]{.aside}

εις γαρ χολην πικριας κα[ι]{.unclear} [συν]{.greek-supplied}[δ]{.unclear}[εσμ]{.greek-supplied}ον αδικιας ορω σε οντα[8:23]{.aside}

αποκριθει[ς]{.greek-supplied} [δε]{.greek-supplied} [ο]{.greek-supplied} [σι]{.greek-supplied}[μ]{.unclear}ων ειπεν δεηθητε υμεις υπερ εμου προς [τον]{.greek-omitted} [κυριον]{.greek-abbr} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι μ[εν]{.unclear} ουν διαμαρτυραμενοι και λαλησαντες τον λογον του [κυριου]{.greek-abbr} υπεστρεψ[αν]{.unclear} εις [ιερουσαλημ]{.greek-abbr} πολλας τε κωμ[ας]{.unclear} των σαμαρειτων ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} ελαλησεν [[ελαλησε]{.corr}]{.greek-added} προς φιλιππον λεγων αναστηθι και πορευου [κατα]{.greek-supplied} μεσημβριαν επι την οδον την καταβαινουσαν απο [ιερουσαλημ]{.greek-abbr} εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ αιθιοψ ευνουχος δυναστης κανδακης της βασιλισσης αιθιοπων ος ην επι πασης της γα[ζη]{.greek-supplied}ς [αυτης]{.greek-supplied} [ο]{.greek-supplied}ς [εληλυθει]{.greek-omitted} [εληλυ[―]{.gap}θη]{.greek-added} [[εληλυθη]{.corr}]{.greek-added} προσκυνησ[ων]{.greek-supplied} [εις]{.greek-omitted} [[ει]{.greek-supplied}]{.greek-added} [ιερουσαλημ]{.greek-supplied}[8:27]{.aside}

ην τε υποστρεφων και καθ[ημενος]{.greek-supplied} [επι]{.greek-supplied} του αρματος αυτου και ανεγιν[ωσκεν]{.greek-supplied} [τον]{.greek-supplied} [προ]{.greek-supplied}φητην ησαιαν[8:28]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε [το]{.greek-supplied} [πνευμα]{.greek-supplied} [τω]{.greek-supplied} [φι]{.greek-supplied}λιππω προσελθε και κολληθητι [τ]{.unclear}ω [α]{.unclear}ρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππ[ος]{.greek-supplied} [ηκ]{.greek-supplied}ουσεν αυτου αναγινωσκοντος τον προ[φ]{.unclear}[η]{.greek-supplied}την ησαιαν και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

[ο]{.unclear} δε ειπεν [[ειπε]{.corr}]{.greek-added} πως γαρ αν δυναιμην εαν μη τις [οδηγηση]{.greek-omitted} [οδηγησει]{.greek-added} με παρεκαλεσεν [[παρεκαλεσε]{.corr}]{.greek-added} τε τον φιλιππον αναβαντα καθισαι συν αυτω[8:31]{.aside}

η δε περιοχη της γραφης ην ανεγινωσκεν ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του [κειροντος]{.greek-omitted} [κηραντος]{.greek-added} αυτον αφωνος ουτως ουκ ανοιγει το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι [αιρεται]{.greek-omitted} [αιρετε]{.greek-added} απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω ειπεν [[ειπε]{.corr}]{.greek-added} δεομαι σου περι τινος [ο]{.greek-supplied} [προ]{.greek-supplied}φητης λεγει τουτο περι εαυτου η περι ετερου τινος[8:34]{.aside}

ανοιξας δε [ο]{.greek-omitted} [φιλιππος]{.greek-omitted} το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο αυτω τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο [κατα]{.greek-supplied} [τ]{.unclear}ην οδον ηλθον επι τι υδωρ και φησιν ο ευ[νουχος]{.greek-supplied} ιδου υδωρ τι κωλυει με βαπτισθην[αι]{.unclear}[8:36]{.aside}

[και]{.unclear} εκελευσεν [[εκελευσε]{.corr}]{.greek-added} στηναι το αρ[μ]{.unclear}α [και]{.unclear} κατ[ε]{.unclear}[βησαν]{.greek-supplied} [α]{.greek-supplied}[μ]{.unclear}φοτεροι εις το υδωρ ο τε [φιλιππος]{.greek-omitted} [φιλιπ]{.greek-added} [πος]{.greek-added} και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν εκ του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ηρπασεν [[ηρπασε]{.corr}]{.greek-added} τον φιλιππον και ουκ [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτον ουκετι ο ευνουχος επορευετο γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις καισαρειαν[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις δαμασκον προς τας συναγωγας οπως εαν τινας ευρη της οδου [ταυτης]{.greek-added} οντας ανδρας τε και γυναικας δεδεμενους αγαγη εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} πορευεσθαι εγενετο αυτον εγγιζειν τη δαμασκω και εξαιφνης περιηστραψεν αυτον φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην ηκουσεν [[ηκουσε]{.corr}]{.greek-added} φωνην λεγουσαν αυτω σαουλ σαουλ τι με διωκεις[9:4]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} [ο]{.greek-added} [ναζωραιος]{.greek-added} ον συ διωκεις[9:5]{.aside}

αλλα αναστηθι [και]{.greek-omitted} εισελθε εις την πολιν και λαληθησεται σοι τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι συνοδευοντες αυτω [ειστηκεισαν]{.greek-omitted} [ιστηκησαν]{.greek-added} ενεοι ακουοντες μεν της φωνης μηδενα [δε]{.greek-omitted} θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων τε των οφθαλμων αυτου ουδενα εβλεπεν [[εβλεπε]{.corr}]{.greek-added} χειραγωγουντες δε αυτον εισηγαγον εις δαμασκον[9:8]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και ειπεν [[ειπε]{.corr}]{.greek-added} προς αυτον [εν]{.greek-added} [οραματι]{.greek-added} ο [κυριος]{.greek-abbr} [εν]{.greek-omitted} [οραματι]{.greek-omitted} ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} εν οραματι ανδρα ονοματι ανανιαν εισελθοντα και επιθεντα αυτω χειρα οπως αναβλεψη[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα εποιησεν [[εποιησε]{.corr}]{.greek-added} τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και ωδε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων [τε]{.greek-added} και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει αυτον υπερ του ονοματος μου παθειν[9:16]{.aside}

απηλθεν [[απηλθε]{.corr}]{.greek-added} δε ανανιας και εισηλθεν εις την οικιαν και επιθεις επ αυτον τας χειρας ειπεν [[ειπε]{.corr}]{.greek-added} σαουλ αδελφε ο [κυριος]{.greek-abbr} απεσταλκεν [[απεσταλκε]{.corr}]{.greek-added} με [[ιησους]{.greek-abbr}]{.greek-added} ο οφθεις σοι εν τη οδω η ηρχου οπως αναβλεψης και πλησθης [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

και ευθεως [απεπεσον]{.greek-omitted} [απεπεσαν]{.greek-added} απο των οφθαλμων αυτου ωσει λεπιδες ανεβλεψεν [τε]{.greek-omitted} [[ανεβλεψε]{.corr}]{.greek-added} [δε]{.greek-added} [παραχρημα]{.greek-added} και αναστας εβαπτισθη[9:18]{.aside}

και λαβων [τροφην]{.greek-omitted} [τροφης]{.greek-added} ενισχυσεν [εγενετο]{.greek-omitted} [εγε]{.greek-added} [νετο]{.greek-added} δε ο σαυλος μετα των εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις εκηρυσσεν [[εκηρυσσε]{.corr}]{.greek-added} τον [χριστον]{.greek-abbr} οτι ουτος εστιν ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγον ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους [αγαγη]{.greek-omitted} [αγαγει]{.greek-added} επι τους αρχιερεις[9:21]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και [συνεχυνεν]{.greek-omitted} [συνεχυνε]{.greek-added} τους ιουδαιους τους κατοικουντας εν δαμασκω συμβιβαζων οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω [η]{.corr} [επιβουλη]{.corr} αυτων [παρετηρουν]{.greek-omitted} [παρετηρουντο]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} [και]{.greek-added} τας πυλας ημερας [τε]{.greek-omitted} και νυκτος οπως αυτον ανελωσιν [[ανελωσι]{.corr}]{.greek-added}[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος καθηκαν δια του τειχους χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι εστιν [[εστι]{.corr}]{.greek-added} μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον ηγαγεν [[ηγαγε]{.corr}]{.greek-added} προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [[ιδε]{.corr}]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν τω ονοματι [του]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος [και]{.greek-added} [εκπορευομενος]{.greek-added} εις [ιερουσαλημ]{.greek-abbr} και παρρησιαζομενος εν τω ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

ελαλει [τε]{.greek-omitted} [δε]{.greek-added} και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

επιγνοντες δε οι αδελφοι κατηγαγον αυτον εις καισαρειαν και εξαπεστειλαν αυτον εις ταρσον[9:30]{.aside}

αι μεν ουν εκκλησιαι καθ ολης της ιουδαιας και γαλιλαιας και σαμαρειας ειχον ειρηνην οικοδομουμεναι και πορευομεναι τω φοβω του [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} επληθυνοντο[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας λυδδαν[9:32]{.aside}

ευρεν [[ευρε]{.corr}]{.greek-added} δε εκει [ανθρωπον]{.greek-abbr} τινα αινεαν ονοματι εξ ετων οκτω κατακειμενον επι [κραββατω]{.greek-omitted} [κραβαττω]{.greek-added} ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον σεαυτω και ευθεως ανεστη[9:34]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον παντες οι κατοικουντες λυδδαν και τον ασσαρωνα οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} η διερμηνευομενη λεγεται δορκας αυτη ην πληρης αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν [αυτην]{.greek-added} εν υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν προς αυτον παρακαλουντες μη οκνησαι διελθειν εως αυτων[9:38]{.aside}

αναστας δε πετρος συνηλθεν αυτοις ον παραγενομενον ανηγαγον εις το υπερωον και παρεστησαν αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μετ αυτων ουσα η δορκας[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος [και]{.greek-added} θεις τα γονατα προσηυξατο και επιστρεψας προς το σωμα ειπεν [[ειπε]{.corr}]{.greek-added} [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} αναστηθι η δε [ηνοιξεν]{.greek-omitted} [ηνυξεν]{.greek-added} [[ηνυξε]{.corr}]{.greek-added} τους οφθαλμους αυτης και ιδουσα τον πετρον ανεκαθισεν [[ανεκαθισε]{.corr}]{.greek-added}[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην φωνησας δε τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωστον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι αυτον εν ιοππη παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις [ην]{.greek-omitted} εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ σπειρης της καλουμενης ιταλικης[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

[ειδεν]{.greek-omitted} [ιδεν]{.greek-added} εν οραματι φανερως ωσει [περι]{.greek-added} ωραν ενατην της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και [ειποντα]{.greek-omitted} [ειπεν]{.greek-added} αυτω κορνηλιε[10:3]{.aside}

ο δε ατενισας αυτω και εμφοβος γενομενος ειπεν [[ειπε]{.corr}]{.greek-added} τι εστιν [[εστι]{.corr}]{.greek-added} [κυριε]{.greek-abbr} ειπεν [[ειπε]{.corr}]{.greek-added} δε αυτω αι προσευχαι σου και αι ελεημοσυναι σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν [η]{.greek-added} οικια παρα θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην ευσεβη των προσκαρτερουντων αυτω[10:7]{.aside}

και εξηγησαμενος αυτοις απαντα απεστειλεν αυτους εις [την]{.greek-omitted} ιοππην[10:8]{.aside}

τη δε επαυριον [οδοιπορουντων]{.greek-omitted} [οδυπορουντων]{.greek-added} [εκεινων]{.greek-omitted} [αυτων]{.greek-added} και τη πολει εγγιζοντων ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν εκτην[10:9]{.aside}

εγενετο δε προσ[―]{.gap}πεινος [[προσπεινος]{.corr}]{.greek-added} και ηθελεν [[ηθελε]{.corr}]{.greek-added} [γευ]{.greek-added} [γευσασθαι]{.greek-omitted} [σασθαι]{.greek-added} παρασκευαζοντων δε [εκεινων]{.greek-omitted} [αυτων]{.greek-added} επεπεσεν επ [α]{.unclear}υτον εκστασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεω[γ]{.unclear}μενον και καταβαινον επ αυτον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις δεδεμενον και [καθιεμενον]{.greek-omitted} [καθηεμενον]{.greek-added} επι της γης[10:11]{.aside}

εν ω υπηρχεν [[υπηρχε]{.corr}]{.greek-added} παντα τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον [αναστας]{.greek-omitted} [αναστα]{.greek-added} πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος ειπεν [[ειπε]{.corr}]{.greek-added} μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον η ακαθαρτον[10:14]{.aside}

και φωνη παλιν εκ δευτερου προς αυτον α ο [θεος]{.greek-abbr} εκαθαρισεν [[εκαθαρισε]{.corr}]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι [τρεις]{.greek-added} [τρις]{.corr} και παλιν ανεληφθη το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο πετρος τι αν ειη το οραμα ο [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [[ιδε]{.corr}]{.greek-added} και ιδου οι ανδρες οι απεσταλμενοι [απο]{.greek-omitted} [παρα]{.greek-added} του κορνηλιου διερωτησαντες την οικιαν σιμωνος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει σιμων ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες [τρεις]{.greek-added} ζητουσιν [[ζητουσι]{.corr}]{.greek-added} σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους [προς]{.greek-added} [σε]{.greek-added}[10:20]{.aside}

καταβας δε [ο]{.greek-added} πετρος προς τους ανδρας ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος [τε]{.greek-omitted} υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος ουν αυτους εξενισεν [[εξενισε]{.corr}]{.greek-added} τη δε επαυριον ο πετρος εξηλθεν συν αυτοις και τινες των αδελφων [των]{.greek-omitted} απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις [την]{.greek-omitted} καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος [ηγειρεν]{.greek-added} αυτον [ηγειρεν]{.greek-omitted} λεγων αναστηθι καγω αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω εισηλθεν [[εισηλθε]{.corr}]{.greek-added} και ευρισκει συνεληλυθοτας πολλους[10:27]{.aside}

[εφησεν]{.greek-added} [εφη]{.greek-omitted} [[εφησε]{.corr}]{.greek-added} [τε]{.greek-omitted} προς αυτους υμεις επιστασθε ως [αθεμιτον]{.greek-omitted} [αθεμητον]{.greek-added} εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν [[εδειξε]{.corr}]{.greek-added} μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και [αναντιρρητως]{.greek-omitted} [αναντηρρητως]{.greek-added} ηλθον μεταπεμφθεις πυνθανομαι ουν τινι λογω [μετεπεμψασθε]{.greek-omitted} [μετεπεμψασθαι]{.greek-added} με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και την ενατην ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και φησιν [[φησι]{.corr}]{.greek-added} κορνηλιε εισηκουσθη σου η προσευχη και αι ελεημοσυναι σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και [μετακαλεσαι]{.greek-omitted} [μετακαλεσε]{.greek-added} σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος βυρσεως παρα θαλασσαν ος παραγενομενος λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα ειπεν επ αληθειας καταλαμβανομαι οτι ουκ εστιν [[εστι]{.corr}]{.greek-added} προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι εθνει ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην δεκτος αυτω εστιν [[εστι]{.corr}]{.greek-added}[10:35]{.aside}

τον λογον ον απεστειλεν [[απεστειλε]{.corr}]{.greek-added} τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος εστιν [[εστι]{.corr}]{.greek-added} παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το βαπτισμα ο εκηρυξεν ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ως εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-abbr} ον και ανειλον κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} ηγειρεν [[ηγειρε]{.corr}]{.greek-added} τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα [μαρτυσιν]{.greek-omitted} [μαρτυ]{.greek-added} [μαρτυ]{.greek-added} [σιν]{.greek-added} [[σι]{.corr}]{.greek-added} τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες συνεφαγομεν και συνεπιομεν αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι αυτος εστιν ο [ωρισμενος]{.greek-omitted} [ορισμενος]{.greek-added} υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα επεπεσεν [[επεπεσε]{.corr}]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη [ο]{.greek-omitted} πετρος[10:46]{.aside}

μητι το υδωρ κωλυσαι δυναται τις του μη βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

προσεταξεν [[προσεταξε]{.corr}]{.greek-added} τε αυτους βαπτισθηναι εν τω ονοματι του [κυριου]{.greek-abbr} τοτε ηρωτησαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

[και]{.greek-omitted} οτε [δε]{.greek-added} ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε ο πετρος εξετιθετο αυτοις καθεξης λεγων[11:4]{.aside}

εγω ημην εν πολει ιοππη προσευχομενος και [ειδον]{.greek-omitted} [ιδον]{.greek-added} εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν αχρι εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και [ειδον]{.greek-omitted} [ιδου]{.greek-added} τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε [και]{.greek-added} φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαιρισεν]{.greek-added} [[εκαθαιρισε]{.corr}]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι τρις και παλιν ανεσπασθη απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η ημην απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν διακρινομενον ηλθον [δε]{.greek-omitted} συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

απηγγειλεν [[απηγγειλε]{.corr}]{.greek-added} τε ημιν πως [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [[ιδε]{.corr}]{.greek-added} τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις σωθηση συ και πας ο οικος σου[11:14]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} αρξασθαι με λαλειν επεπεσεν [[επεπεσε]{.corr}]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [του]{.greek-added} [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω [δε]{.greek-omitted} τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και [εδοξαζον]{.greek-omitted} [εδοξασαν]{.greek-added} τον [θεον]{.greek-abbr} λεγοντες αρα γε και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες απο της θλιψεως της γενομενης επι στεφανω διηλθον εως φ[οι]{.unclear}νικης και κυπρου και αντιοχειας μηδενι λαλουντες τον λογον ει μη μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων [ανδδρες]{.greek-added} [ανδρες]{.corr} κυπριοι και [κυρηναιοι]{.greek-omitted} [κυριναιοι]{.greek-added} οιτινες [εισελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων [εις]{.greek-added} [το]{.greek-added} [ιασθαι]{.greek-added} [αυτους]{.greek-added} πολυς τε αριθμος [ο]{.greek-added} πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της εν ιεροσολυμοις περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει παντας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και πληρης [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

εξηλθεν [[εξηλθε]{.corr}]{.greek-added} δε εις ταρσον ο βαρναβας αναζητησαι σαυλον[11:25]{.aside}

και ευρων [αυτον]{.greek-added} ηγαγεν αυτον εις αντιοχειαν εγενετο δε αυτους ενιαυτον ολον συναχθηναι [εν]{.greek-added} τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος εσημανεν [[εσημανε]{.corr}]{.greek-added} δια του [πνευματος]{.greek-abbr} λιμον μεγαν μελλειν εσεσθαι εφ ολην την οικουμενην οστις και εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως ευπορειτο τις ωρισαν εκαστος αυτων εις δι[α]{.unclear}κονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

ο και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ [ε]{.greek-added} [εκεινον]{.greek-omitted} [κεινον]{.greek-added} δε [των]{.greek-added} [καιρων]{.greek-added} [τον]{.corr} [καιρον]{.corr} επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της εκκλησιας[12:1]{.aside}

ανειλεν [[ανειλε]{.corr}]{.greek-added} δε ιακωβον τον αδελφον ιωαννου μαχ[α]{.unclear}ιρα[12:2]{.aside}

και ιδων οτι αρεστον εστιν [[εστι]{.corr}]{.greek-added} τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε αι ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε εμελλεν αυτον προαγειν ο ηρωδης τη νυκτι εκεινη ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος αλυσεσιν [[αλυσεσι]{.corr}]{.greek-added} δυσιν φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω [οικηματι]{.greek-omitted} [οικιματι]{.greek-added} παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και [εξεπεσον]{.greek-omitted} [εξεπεσαν]{.greek-added} αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} τε ο αγγελος προς αυτον [περιζωσαι]{.greek-omitted} [ζωσαι]{.greek-added} και υποδησαι τα σανδαλια σου εποιησεν [[εποιησε]{.corr}]{.greek-added} δε ουτως [[ουτω]{.corr}]{.greek-added} και λεγει αυτω περιβαλου το ιματιον σου και ακολουθει μοι[12:8]{.aside}

και εξελθων ηκολουθει αυτω και ουκ ηδει οτι αληθες εστιν [[εστι]{.corr}]{.greek-added} το γινομενον [δια]{.greek-omitted} [υπο]{.greek-added} του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν εις την πολιν ητις αυτοματη ηνοιχθη αυτοις και εξελθοντες [προσηλθον]{.greek-added} [προηλθον]{.corr} ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος γενομενος εν εαυτω ειπεν [[ειπε]{.corr}]{.greek-added} νυν οιδα αληθως οτι εξαπεστειλεν [[εξαπεστειλε]{.corr}]{.greek-added} [κυριος]{.greek-abbr} τον αγγελον αυτου και [εξειλετο]{.greek-omitted} [εξειλατο]{.greek-added} με εκ χειρος ηρωδου και πασης της προσδοκιας του λαου των ιουδαιων[12:11]{.aside}

[συνιδων]{.greek-omitted} [συνειδων]{.greek-added} τε ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} ιωαννου του επικαλουμενου μαρκου ου ησαν ικανοι [συνηθροισμενοι]{.greek-omitted} [συνηθρυσμενοι]{.greek-added} και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του πετρου την θυραν του πυλωνος προσηλθεν [[προσηλθε]{.corr}]{.greek-added} παιδισκη υπακουσαι ονοματι [ρωδη]{.greek-added} [ροδη]{.corr}[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ ηνοιξεν [[ηνοιξε]{.corr}]{.greek-added} τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον μαινη η δε διισχυριζετο ουτως εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος επεμενεν [[επεμενε]{.corr}]{.greek-added} κρουων ανοιξαντες δε [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον και εξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξηγαγεν εκ της φυλακης ειπεν [[ειπε]{.corr}]{.greek-added} δε απαγγειλατε ιακωβω και τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις [την]{.greek-omitted} καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης θυμομαχων τυριοις και [σιδωνιοις]{.greek-omitted} [σιδονιοις]{.greek-added} ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι αυτων την χωραν απο της [βασιλικης]{.greek-omitted} [βασιλεικης]{.greek-added}[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα [βασιλικην]{.greek-omitted} [βασιλεικην]{.greek-added} και [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εδημηγορει προς αυτους[12:21]{.aside}

ο δε δημος επεφωνει φωνη [θεου]{.greek-abbr} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε επαταξεν αυτον αγγελος [κυριου]{.greek-abbr} ανθ ων ου[κ]{.unclear} εδωκεν [[εδωκε]{.corr}]{.greek-added} δοξαν τω [θεω]{.greek-abbr} και γενομενος [σκωληκοβρωτος]{.greek-omitted} [σκωληκοβροτος]{.greek-added} εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} ηυξανεν [[ηυξανε]{.corr}]{.greek-added} και επληθυνετο[12:24]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} [εις]{.greek-added} [αντιοχειαν]{.greek-added} πληρωσαντες την διακονιαν συμπαραλαβοντες και ιωαννην τον επικληθεντα μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε τινες εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος ο [κυρηναιος]{.greek-omitted} [κυριναιος]{.greek-added} μαναην τε ηρωδου του τετραρχου συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων ειπεν [[ειπε]{.corr}]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον [προς]{.greek-added} [αυτους]{.greek-added} [αφορισατε]{.greek-omitted} [αφορησατε]{.greek-added} [δη]{.greek-omitted} [δε]{.greek-added} μοι τον βαρναβαν και τον σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες τας χειρας αυτοις απελυσαν[13:3]{.aside}

ουτοι μεν [ουν]{.greek-omitted} εκπεμφθεντες υπο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις [την]{.greek-omitted} σελευκειαν εκειθεν δε απεπλευσαν εις την κυπρον[13:4]{.aside}

και γενομενοι εν σαλαμινι κατηγγελλον τον λογον του [θεου]{.greek-abbr} εν ταις συναγωγαις των ιουδαιων ειχον [δε]{.greek-omitted} [τε]{.greek-added} και ιωαννην υπηρετην[13:5]{.aside}

διελθοντες δε την [νυ]{.greek-added} [νησον]{.greek-omitted} [σον]{.greek-added} αχρι παφου ευρον τινα μαγον ψευδοπροφητην ιουδαιον ω ονομα [βαριησους]{.greek-omitted} [βαριησουν]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω [παυλω]{.greek-omitted} ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επεζητησεν ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε [αυτοις]{.greek-omitted} [αυτω]{.greek-added} ελυμας ο μαγος ουτως [[ουτω]{.corr}]{.greek-added} γαρ μεθερμηνευεται το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου [και]{.greek-omitted} ατενισας εις αυτον[13:9]{.aside}

ειπεν ω [πληρης]{.greek-omitted} [πληρεις]{.greek-added} παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου [παυση]{.greek-omitted} [παυη]{.greek-added} διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον αχρι καιρου παραχρημα δε [επεπεσεν]{.greek-omitted} [επεσεν]{.greek-added} επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε αποχωρησας απ αυτων υπεστρεψεν εις ιεροσολυμα[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν [προς]{.greek-added} [αυτους]{.greek-added} οι αρχισυναγωγοι [προς]{.greek-omitted} [αυτους]{.greek-omitted} λεγοντες ανδρες αδελφοι ει εστιν [λογος]{.greek-omitted} εν υμιν [λογος]{.greek-added} παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη αιγυπτω και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως [τεσσαρακονταετη]{.greek-omitted} [τεσσερακονταετη]{.greek-added} χρονον ετροποφορησεν αυτους εν τη ερημω[13:18]{.aside}

και [κα]{.greek-supplied}θελων εθνη [επτα]{.greek-omitted} εν γη χανααν κατεκλ[ηρο]{.greek-supplied}νομησεν αυτοις την γην αυτων[13:19]{.aside}

και [μετα]{.greek-supplied} ταυτα ως ετεσιν [[ετεσι]{.corr}]{.greek-added} τετρακοσιοις κα[ι]{.greek-supplied} [π]{.greek-supplied}[ε]{.unclear}ντηκοντα εδωκεν κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ υιον κις ανδρα εκ φυλης βενιαμιν ετη [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added}[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και ειπεν [[ειπε]{.corr}]{.greek-added} μαρτυρησας [ευρον]{.greek-omitted} [ευρεν]{.greek-added} [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν [ηγαγεν]{.greek-omitted} [ηγειρεν]{.greek-added} [[ηγειρε]{.corr}]{.greek-added} τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-omitted} [[σωτηρα]{.greek-abbr}]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας [παντι]{.greek-added} τω [λαω]{.greek-added} [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου ο ιωαννης τον δρομον [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν [υ]{.unclear}μιν φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος τ[ης]{.unclear} [σωτηριας]{.greek-abbr} ταυτης απεσταλη[13:26]{.aside}

οι γαρ κατοικουν[τες]{.greek-supplied} [εν]{.greek-supplied} [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον [αγνο]{.greek-supplied}ησαντες και τας φωνας των προ[φητων]{.greek-supplied} τας κατα παν σαββατον αναγιν[ωσκο]{.greek-supplied}μενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις μνημειον[13:29]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [νυν]{.greek-added} εισιν [[εισι]{.corr}]{.greek-added} μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκεν]{.greek-added} [[εκπεπληρωκε]{.corr}]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω τω δευτερω γεγραπται [υιος]{.greek-abbr} μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον εκ νεκρων μηκετι μελλοντα υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [[ιδε]{.corr}]{.greek-added} διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν ανδρες αδελφοι οτι δια τουτου [υμιν]{.greek-omitted} αφεσις αμαρτιων [υμιν]{.greek-added} καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωυσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη [επελθη]{.greek-omitted} [επελθοι]{.greek-added} εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται [και]{.greek-added} [επιβλεψατε]{.greek-added} και θαυμασατε και αφανισθητε οτι εργον [εργαζομαι]{.greek-added} εγω [εργαζομαι]{.greek-omitted} εν ταις ημεραις υμων ο ου μη πιστευσητε εαν τις εκδιηγηται υμιν[13:41]{.aside}

εξιοντων δε [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [ιουδαιων]{.greek-omitted} παρεκαλουν [τα]{.greek-omitted} [εθνη]{.greek-omitted} εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

λυθεισης δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και τω βαρναβα οιτινες προσλαλουντες επειθον αυτους επιμενειν τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω τε ερχομενω σαββατω σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-abbr}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλου λεγομενοις αντιλεγοντες και βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι δε ο παυλος και [ο]{.greek-omitted} [βαρ]{.greek-added} [βαρναβας]{.greek-omitted} [ναβας]{.greek-added} ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} επειδη δε απωθεισθε αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

ουτως [[ουτω]{.corr}]{.greek-added} γαρ εντεταλται ημιν ο [κυριος]{.greek-abbr} [ιδου]{.greek-added} τεθεικα σε εις φως εθνων [του]{.greek-omitted} ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον τον λογον του [κυριου]{.greek-abbr} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-abbr} δι ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας και τας ευσχημονας και τους πρωτους της πολεως και επηγειραν [διωγμον]{.greek-omitted} [διογμον]{.greek-added} επι τον παυλον και τον βαρναβαν και εξεβαλον αυτους απο των οριων αυτων[13:50]{.aside}

οι δε [εκτιναξαμενοι]{.greek-omitted} [εκτει[ν]{.unclear}αξαμενοι]{.greek-added} τον κονιορτον των ποδων αυτων επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι δε μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων τε και ελληνων πολυ πληθος[14:1]{.aside}

οι δε απειθουντες ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου [και]{.greek-added} [διδοντι]{.greek-omitted} [διδουντι]{.greek-added} σημεια και τερατα γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και λιθοβολησαι αυτους[14:5]{.aside}

[συνιδοντες]{.greek-omitted} [συνειδοντες]{.greek-added} κατεφυγον εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει ησαν ευαγγελιζομενοι[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν [[ποσι]{.corr}]{.greek-added} [εκαθητο]{.greek-omitted} [εκαθιτο]{.greek-added} χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων ος ουδεποτε [περιπεπατηκει]{.greek-omitted} [περιεπατησεν]{.greek-added}[14:8]{.aside}

ουτος ηκουσεν [[ηκουσε]{.corr}]{.greek-added} του παυλου λαλουντος ος ατενισας αυτω και ιδων οτι πιστιν εχει του σωθηναι[14:9]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} μεγαλη τη φωνη αναστηθι επι τους ποδας σου ορθως και ηλλετο και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν ο παυλος επηραν [αυτων]{.greek-added} την φωνην [αυτων]{.greek-omitted} λυκαονιστι λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν δια τον δε παυλον ερμην επειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο δε ιερευς του διος του οντος προ της πολεως αυτων ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις ηθελεν [[ηθελε]{.corr}]{.greek-added} θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων [εισεπηδησαν]{.greek-omitted} [εισεπιδησαν]{.greek-added} εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε και ημεις ομοιοπαθεις εσμεν υμιν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο τουτων των ματαιων επιστρεφειν επι [τον]{.greek-omitted} [θεον]{.greek-abbr} [τον]{.greek-omitted} ζωντα ος εποιησεν [[εποιησε]{.corr}]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις [παρωχημεναις]{.greek-omitted} [παροχημεναις]{.greek-added} γενεαις ειασεν [[ειασε]{.corr}]{.greek-added} παντα τα εθνη πορευεσθαι [εν]{.greek-added} ταις οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρον εαυτον αφηκεν αγαθοποιων [ουρανοθεν]{.greek-abbr} υμιν υετους διδους και καιρους καρποφορους [εμπιπλων]{.greek-omitted} [εμπιμπλων]{.greek-added} [τροφης]{.greek-omitted} [χαρας]{.greek-added} και ευφροσυνης τας καρδιας ημων[14:17]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν αυτοις [αλλα]{.greek-added} [πορευεσθαι]{.greek-added} [εκαστος]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ιδια]{.greek-added}[14:18]{.aside}

επηλθον δε απο αντιοχειας και ικονιου ιουδαιοι [και]{.greek-added} [διαλεγομενων]{.greek-added} [αυτων]{.greek-added} [παρρησια]{.greek-added} [επεισαν]{.greek-added} [τους]{.greek-added} [οχλους]{.greek-added} [αποστειναι]{.greek-added} [απ]{.greek-added} [αυτων]{.greek-added} [λεγοντες]{.greek-added} [οτι]{.greek-added} [ουδεν]{.greek-added} [αληθειαν]{.greek-added} [λεγουσιν]{.greek-added} [αλλα]{.greek-added} [παντα]{.greek-added} [ψευδονται]{.greek-added} και πεισαντες τους οχλους και λιθασαντες τον παυλον εσυρον εξω της πολεως νομισαντες αυτον τεθναναι[14:19]{.aside}

κυκλωσαντων δε [αυτων]{.greek-added} [αυτον]{.corr} των μαθητων αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν συν τω βαρναβα εις δερβην[14:20]{.aside}

ευ[αγ]{.unclear}γελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν και ικονιον και αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων [και]{.greek-added} παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει ημας εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις πρεσβυτερους κατ εκκλησιαν προσευξαμενοι μετα [νηστειων]{.greek-omitted} [νηστειας]{.greek-added} παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον πεπιστευκεισαν[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον εις παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον κατεβησαν εις [ατταλειαν]{.greek-omitted} [αταλειαν]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν παραδεδομενοι τη χαριτι του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν ανηγγειλαν οσα [εποιησεν]{.greek-omitted} ο [θεος]{.greek-abbr} [εποιησεν]{.greek-added} [[εποιησε]{.corr}]{.greek-added} μετ αυτων και οτι ηνοιξεν [[ηνοιξε]{.corr}]{.greek-added} τοις εθνεσιν [[εθνεσι]{.corr}]{.greek-added} θυραν [της]{.greek-added} πιστεως[14:27]{.aside}

διετριβον δε εκει χρονον ουκ ολιγον συν τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη περιτεμνησθε τω εθει μωυσεως ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης ουν στασεως και ζητησεως ουκ ολιγης τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την φοινικην και [την]{.greek-added} σαμαρειαν [εκδιηγουμενοι]{.greek-omitted} [διηγουμενοι]{.greek-added} την επιστροφην των εθνων και εποιουν χαραν μεγαλην πασιν [[πασι]{.corr}]{.greek-added} τοις αδελφοις[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-abbr} απεδεχθησαν υπο της εκκλησιας και των αποστολων και των πρεσβυτερων ανηγγειλαν τε οσα ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} μετ αυτων [και]{.greek-added} [οτι]{.greek-added} [ηνοιξεν]{.greek-added} [[ηνοιξε]{.corr}]{.greek-added} [τοις]{.greek-added} [εθνεσιν]{.greek-added} [[εθνεσι]{.corr}]{.greek-added} [θυραν]{.greek-added} [πιστεως]{.greek-added}[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων [πεπιστευκοτες]{.greek-omitted} [πεπιστευκοτων]{.greek-added} λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον μωυσεως[15:5]{.aside}

συνηχθησαν δε οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε συζητησεως γενομενης αναστας πετρος ειπεν [[ειπε]{.corr}]{.greek-added} προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων ο [θεος]{.greek-abbr} εν ημιν εξελεξατο δια του στοματος μου ακουσαι τα εθνη τον λογον του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και [ουδεν]{.greek-omitted} [ουθεν]{.greek-added} διεκρινεν [[διεκρινε]{.corr}]{.greek-added} μεταξυ ημων τε και αυτων τη πιστει καθαρισας τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} [επιθειναι]{.greek-omitted} [επιθηναι]{.greek-added} ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

εσιγησεν [[εσιγησε]{.corr}]{.greek-added} δε παν το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δι αυτων[15:12]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον [επι]{.greek-omitted} τω ονοματι αυτου[15:14]{.aside}

και τουτω συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων ταυτα παντα[15:17]{.aside}

γνωστα [απ]{.greek-omitted} [απο]{.greek-added} [του]{.greek-added} αιωνος εστιν [[εστι]{.corr}]{.greek-added} τω [θεω]{.greek-abbr} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} επιστειλαι αυτοις του απεχεσθαι απο των αλισγηματων των ειδωλων και της [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} και του πνικτου και του αιματος[15:20]{.aside}

μωυσης γαρ εκ γενεων αρχαιων κατα πολιν τους [κηρυσσοντας]{.greek-omitted} [κηρυσ]{.greek-added} [σοντας]{.greek-added} [αυτων]{.greek-added} [αυτον]{.corr} εχει εν ταις συναγωγαις κατα παν σαββατον αναγινωσκομενος[15:21]{.aside}

τοτε εδοξεν [[εδοξε]{.corr}]{.greek-added} τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν παυλω και βαρναβα ιουδαν τον επικαλουμενον βαρσαββαν και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων εξελθοντες εταραξαν υμας λογοις ανασκευαζοντες τας ψυχας υμων λεγοντες περιτεμνεσθαι και τηρειν τον νομον οις ου διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον εκλεξαμενους ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα και παυλω[15:25]{.aside}

[ανθρωποις]{.greek-abbr} [παραδεδωκοσιν]{.greek-omitted} [παραδεδοκωσι]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

εδοξεν [γαρ]{.greek-omitted} [[εδοξε]{.corr}]{.greek-added} τω αγιω [πνευματι]{.greek-abbr} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην [τουτων]{.greek-added} των επαναγκες [τουτων]{.greek-omitted}[15:28]{.aside}

[απεχεσθαι]{.greek-omitted} [απεχεσθε]{.greek-added} ειδωλοθυτων και αιματος και πνικτου και [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} εξ ων διατηρουντες εαυτους ευ πραξετε ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες ηλθον εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

αναγνοντες δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης απο των αδελφων προς τους αποστολους[15:33]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας ειπεν [[ειπε]{.corr}]{.greek-added} παυλος προς βαρναβαν επιστρεψαντες [δη]{.greek-omitted} [δε]{.greek-added} επισκεψωμεθα τους αδελφους ημων κατα πασαν πολιν εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως εχουσιν [[εχουσι]{.corr}]{.greek-added}[15:36]{.aside}

βαρναβας δε [εβουλευσατο]{.greek-omitted} [εβουλετο]{.greek-added} συμπαραλαβειν [τον]{.greek-omitted} [και]{.greek-added} ιωαννην τον [καλουμενον]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη [συμπαραλαβειν]{.greek-omitted} [συμπαραλαμβανειν]{.greek-added} τουτον[15:38]{.aside}

εγενετο ουν παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων τον τε βαρναβαν παραλαβοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν εξηλθεν [[εξηλθε]{.corr}]{.greek-added} παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και κιλικιαν επιστηριζων τας εκκλησιας[15:41]{.aside}

### Chapter 16

κατηντησεν [[κατηντησε]{.corr}]{.greek-added} δε εις δερβην και λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος [υιος]{.greek-abbr} γυναικος [τινος]{.greek-omitted} [χηρας]{.greek-added} ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τοποις εκεινοις ηδεισαν γαρ απαντες τον [πατερα]{.greek-abbr} αυτου οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις παρεδιδουν αυτοις φυλασσειν τα δογματα τα [κεκριμενα]{.greek-omitted} [κεκρυμμενα]{.greek-added} υπο των αποστολων και των πρεσβυτερων των εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και επερισσευον τω αριθμω καθ ημεραν[16:5]{.aside}

διελθοντες δε την φρυγιαν και την γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες κατα την μυσιαν επειραζον κατα την βιθυνιαν πορευεσθαι και ουκ ειασεν αυτους το [πνευμα]{.greek-abbr}[16:7]{.aside}

παρελθοντες δε την μυσιαν κατεβησαν εις [τρωαδα]{.greek-omitted} [τροαδα]{.greek-added}[16:8]{.aside}

και οραμα δια της νυκτος ωφθη τω παυλω ανηρ τις ην μακεδων εστως παρακαλων αυτον και λεγων διαβας εις μακεδονιαν βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ευθεως εζητησαμεν εξελθειν εις [την]{.greek-omitted} μακεδονιαν συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι αυτους[16:10]{.aside}

αναχθεντες ουν απο της [τρωαδος]{.greek-omitted} [τροαδος]{.greek-added} ευθυδρομησαμεν εις σαμοθρακην τη τε επιουση εις νεαπολιν[16:11]{.aside}

[εκειθεν]{.greek-omitted} [κακειθεν]{.greek-added} [τε]{.greek-omitted} εις φιλιππους ητις εστιν [[εστι]{.corr}]{.greek-added} πρωτη της μεριδος της μακεδονιας πολις [κολωνεια]{.greek-omitted} [κολωνια]{.greek-added} ημεν δε εν αυτη τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των σαββατων εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο προσευχη ειναι και [καθισαντες]{.greek-omitted} [καθησαντες]{.greek-added} ελαλουμεν ταις συνελθουσαις γυναιξιν [[γυναιξι]{.corr}]{.greek-added}[16:13]{.aside}

και τις γυνη ονοματι λυδια [πορφυροπωλις]{.greek-omitted} [πορφυροπολις]{.greek-added} πολεως θυατειρων σεβομενη τον [θεον]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουσεν]{.greek-added} ης ο [κυριος]{.greek-abbr} [διηνοιξεν]{.greek-omitted} [διηνοιξε]{.greek-added} την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης παρεκαλεσεν [[παρεκαλεσε]{.corr}]{.greek-added} λεγουσα ει κεκρικατε με πιστην τω [κυριω]{.greek-abbr} ειναι εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην παιδισκην τινα εχουσαν [πνευμα]{.greek-abbr} πυθωνος απαντησαι ημιν ητις εργασιαν πολλην παρειχεν [[παρειχε]{.corr}]{.greek-added} τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και ημιν εκραζεν [[εκραζε]{.corr}]{.greek-added} [λεγουσα]{.greek-omitted} [λεγουσαν]{.greek-added} ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν [ημιν]{.greek-omitted} [υμιν]{.greek-added} οδον [σωτηριας]{.greek-abbr}[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας [διαπονηθεις]{.greek-omitted} [διαπο]{.greek-added} [νηθεις]{.greek-added} δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} ειπεν [[ειπε]{.corr}]{.greek-added} παραγγελλω σοι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της εργασιας αυτων επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και καταγγελλουσιν εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις ουσιν [[ουσι]{.corr}]{.greek-added}[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι [περιρρηξαντες]{.greek-omitted} [περιρηξαντες]{.greek-added} αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην ειληφως εβαλεν αυτους εις την εσωτεραν φυλακην και τους ποδας αυτων ησφαλισατο εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [επηκροωντο]{.greek-omitted} [επικρο]{.greek-added} [ωντο]{.greek-added} δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του [δεσμωτηριου]{.greek-omitted} [δεσμοτηριου]{.greek-added} ανεωχθησαν [τε]{.greek-omitted} [δε]{.greek-added} παραχρημα αι θυραι πασαι [του]{.greek-added} [δεσμοτηριου]{.greek-added} και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν εμελλεν εαυτον αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

εφωνησεν [[εφωνησε]{.corr}]{.greek-added} δε φωνη μεγαλη ο παυλος λεγων μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα [εισεπηδησεν]{.greek-omitted} [εισεπιδησεν]{.greek-added} [[εισεπιδησε]{.corr}]{.greek-added} και εντρομος γενομενος προσεπεσεν [[προσεπεσε]{.corr}]{.greek-added} τω παυλω και τω σιλα[16:29]{.aside}

και [προαγαγων]{.greek-omitted} [προσαγαγων]{.greek-added} αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και ο οικος σου[16:31]{.aside}

και ελαλησαν αυτω τον λογον του [κυριου]{.greek-abbr} και πασιν [[πασι]{.corr}]{.greek-added} τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα της νυκτος ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου παντες παραχρημα[16:33]{.aside}

αναγαγων τε αυτους εις τον οικον αυτου [παρεθηκεν]{.greek-omitted} [παρεθηκαν]{.greek-added} τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασατο]{.greek-added} πανοικι πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενομενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

απηγγειλεν [[απηγγειλε]{.corr}]{.greek-added} δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας εκβαλλουσιν ου γαρ αλλα ελθοντες αυτοι εξαγαγετωσαν[16:37]{.aside}

ανηγγειλαν [δε]{.greek-omitted} [τε]{.greek-added} τοις στρατηγοις οι ραβδουχοι τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι εισιν [[εισι]{.corr}]{.greek-added}[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και εξαγαγοντες [ηρωτων]{.greek-omitted} [ηρωτουν]{.greek-added} εξελθειν της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες τους αδελφους [παρεκαλεσαν]{.greek-omitted} [παρεκα]{.greek-added} [λεσαν]{.greek-added} αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και απολλωνιαν ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το ειωθος τω παυλω εισηλθεν [[εισηλθε]{.corr}]{.greek-added} προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν ο [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων επεισθησαν και προσεκληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων [πολυ]{.greek-omitted} πληθος γυναικων τε [και]{.greek-added} των πρωτων ουκ ολιγαι[17:4]{.aside}

[προσλαβομενοι]{.greek-omitted} [ζηλωσαντες]{.greek-added} δε οι ιουδαιοι [οι]{.greek-omitted} [απειθουντες]{.greek-omitted} [και]{.greek-added} [προσλαβομενοι]{.greek-added} των αγοραιων τινας ανδρας πονηρους και οχλοποιησαντες εθορυβουν την πολιν επισταντες τε τη οικια [ιασονος]{.greek-omitted} [ιασσονος]{.greek-added} εζητουν αυτους αγαγειν εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τον [ιασονα]{.greek-omitted} [ιασσονα]{.greek-added} και τινας αδελφους επι τους [πολιταρχας]{.greek-omitted} [πολυταρχας]{.greek-added} βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι [και]{.greek-omitted} ενθαδε παρεισιν[17:6]{.aside}

ους υποδεδεκται [ιασων]{.greek-omitted} [ιασσων]{.greek-added} και ουτοι παντες απεναντι των δογματων καισαρος πρασσουσιν [[πρασσουσι]{.corr}]{.greek-added} βασιλεα λεγοντες ετερον ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον οχλον και τους [πολιταρχας]{.greek-omitted} [πολυταρχας]{.greek-added} ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του [ιασονος]{.greek-omitted} [ιασσονος]{.greek-added} και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια [της]{.greek-omitted} νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις βεροιαν οιτινες παραγενομενοι εις την συναγωγην [απηεσαν]{.greek-omitted} των ιουδαιων [απηεσαν]{.greek-added}[17:10]{.aside}

[ουτοι]{.greek-omitted} [αυτοι]{.greek-added} δε ησαν ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας [το]{.greek-omitted} καθ ημεραν ανακρινοντες τας γραφας ει εχοι ταυτα ουτως [[ουτω]{.corr}]{.greek-added}[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και [των]{.greek-added} ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της θεσσαλονικης ιουδαιοι οτι και εν τη βεροια [κατηγγελη]{.greek-omitted} [κατηγγελλει]{.greek-added} υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες [και]{.greek-added} [ταρασσοντες]{.greek-added} τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι [ως]{.greek-omitted} [εως]{.greek-added} επι την θαλασσαν [υπεμενον]{.greek-omitted} [δε]{.greek-omitted} [επεμειναν]{.greek-added} [τε]{.greek-added} ο τε σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε [καθιστωντες]{.greek-omitted} [καθιστανοντες]{.greek-added} τον παυλον ηγαγον [αυτον]{.greek-omitted} εως αθηνων και λαβοντες εντολην προς τον σιλαν και τιμοθεον ινα ως ταχιστα ελθωσιν [[ελθωσι]{.corr}]{.greek-added} προς αυτον εξηεσαν[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου παρωξυνετο το [πνευμα]{.greek-abbr} αυτου εν αυτω [θεωρουντι]{.greek-omitted} [θεωρουντος]{.greek-added} κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις σεβομενοις [και]{.greek-omitted} εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε και [τ]{.unclear}ων [επικουρειων]{.greek-omitted} [επικουριων]{.greek-added} και [των]{.greek-omitted} στοικων φιλοσοφων συνεβαλλον αυτω και τινες ελεγον τι αν θελοι [λεγειν]{.greek-added} ο σπερμολογος ουτος [λεγειν]{.greek-omitted} οι δε ξενων δαιμονιων δοκει καταγγελευς ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο [αυτοις]{.greek-added}[17:18]{.aside}

επιλαβομενοι τε [αυτου]{.greek-omitted} [αυτον]{.greek-added} επι τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι [τινα]{.greek-added} [τι]{.greek-omitted} [αν]{.greek-omitted} [θελοι]{.greek-omitted} [θελει]{.greek-added} ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον ευκαιρουν η λεγειν τι [και]{.greek-omitted} [η]{.greek-added} ακουειν [τι]{.greek-added} καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως δεισιδαιμονεστερους υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και αναθεωρων τα σεβασματα υμων ευρον και βωμον εν ω [επεγεγραπτο]{.greek-omitted} [επιγεγραπτο]{.greek-added} αγνωστω [θεω]{.greek-abbr} ον ουν αγνοουντες ευσεβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [κυριος]{.greek-abbr} υπαρχων ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-omitted} [ανθρωπινων]{.greek-added} θεραπευεται [ως]{.greek-added} προσδεομενος τινος αυτος [διδους]{.greek-omitted} [δους]{.greek-added} πασιν [[πασι]{.corr}]{.greek-added} ζωην και πνοην κατα παντα[17:25]{.aside}

εποιησεν [[εποιησε]{.corr}]{.greek-added} τε εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ει αρα γε [ψηλαφησειαν]{.greek-omitted} [ψηλαφησειεν]{.greek-added} αυτον και ευροιεν και γε ου μακραν απο ενος εκαστου ημων υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ [υμας]{.greek-omitted} [υμων]{.greek-added} ποιητων ειρηκασιν [[ειρηκασι]{.corr}]{.greek-added} του γαρ και γενος εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν [χρυσω]{.greek-omitted} [χρυσιω]{.greek-added} η [αργυρω]{.greek-omitted} [αργυριω]{.greek-added} η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-abbr} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} πασιν [[πασι]{.corr}]{.greek-added} πανταχου μετανοειν[17:30]{.aside}

διοτι εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω ωρισεν [[ωρισε]{.corr}]{.greek-added} πιστιν παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον ακουσομεθα σου παλιν περι τουτου[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονομα[τ]{.unclear}ι δαμαρις και ετεροι [πολλοι]{.greek-added} συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα ιουδαιον ονοματι ακυλαν ποντικον τω γενει προσφατως εληλυθοτα απο της ιταλιας και πρισκιλλαν γυναικα αυτου δια το τεταχεναι κλαυδιον χωριζεσθαι παντας τους ιουδαιους εκ της ρωμης προσηλθεν αυτοις[18:2]{.aside}

και δια το ομοτεχνον ειναι [εμενεν]{.greek-omitted} [εμεινεν]{.greek-added} [[εμεινε]{.corr}]{.greek-added} παρ αυτοις και ειργαζετο ησαν γαρ σκηνοποιοι την τεχνην[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον επειθεν [[επειθε]{.corr}]{.greek-added} τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και ο τιμοθεος συνειχετο τω [πνευματι]{.greek-abbr} ο παυλος [διαμαρτυρομενος]{.greek-omitted} [διαμαρτυρουμενος]{.greek-added} τοις ιουδαιοις [ειναι]{.greek-added} τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων [εκτιναξαμενος]{.greek-omitted} [εκτειναξαμενος]{.greek-added} [αυτου]{.greek-added} τα ιματια ειπεν [[ειπε]{.corr}]{.greek-added} προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας εκειθεν [ηλθεν]{.greek-omitted} [εισηλθεν]{.greek-added} εις οικιαν τινος ονοματι ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια ην συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος επιστευσεν [[επιστευσε]{.corr}]{.greek-added} τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} επιστευον και εβαπτιζοντο[18:8]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε ο [κυριος]{.greek-abbr} δι οραματος εν νυκτι τω παυλω μη φοβου αλλα λαλει και μη σιωπησης[18:9]{.aside}

διοτι εγω [ειμι]{.greek-omitted} μετα σου και ουδεις επιθησεται σοι του κακωσαι σε διοτι λαος εστιν [[εστι]{.corr}]{.greek-added} μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

εκαθισεν [[εκαθισε]{.corr}]{.greek-added} τε ενια[υτ]{.unclear}ον και μηνας εξ διδασκων εν αυ[το]{.unclear}ις τον λογον του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της αχαιας κατεπεστησαν [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον ουτος αναπειθει τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν ουν [ην]{.greek-omitted} αδικημα τι η ραδιουργημα πονηρον [ω]{.greek-omitted} [ιουδαιοι]{.greek-omitted} κατα λογον αν [ηνεσχομην]{.greek-omitted} [ηνεσχαμην]{.greek-added} υμων[18:14]{.aside}

ει δε [ζητημα]{.greek-omitted} [ζητηματα]{.greek-added} εστιν [[εστι]{.corr}]{.greek-added} περι λογου και ονοματων και νομου του καθ υμας οψεσθε αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι δε παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω γαλλιωνι [εμελλεν]{.greek-omitted} [εμελεν]{.greek-added}[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος [αυτοις]{.greek-added} εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος την κεφαλην εν [κεγχρεαις]{.greek-omitted} [κε[ι]{.unclear}γχρεαις]{.greek-added} [ειχεν]{.greek-omitted} [ειχ[ε]{.unclear}]{.greek-added} γαρ ευχην[18:18]{.aside}

κατηντησεν [[κατηντησε]{.corr}]{.greek-added} δε εις εφεσον και εκεινους κατελιπεν [αυτου]{.greek-omitted} [εκει]{.greek-added} αυτος δε εισελθων εις την συναγωγην διελεχθη τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε αυτων επι πλειονα χρονον [μειναι]{.greek-omitted} [παραμειναι]{.greek-added} [παρ]{.greek-omitted} αυτοις ουκ επενευσεν[18:20]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} απεταξατο αυτοις ειπων δει με παντως την εορτην την ερχομενην ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

και κατελθων εις [την]{.greek-added} καισαρειαν αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα εξηλθεν [[εξηλθε]{.corr}]{.greek-added} διερχομενος καθεξης την γαλατικην χωραν και [την]{.greek-added} φρυγιαν επιστηριζων [παντας]{.greek-omitted} τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-abbr} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε αυτου ακυλας και πρισκιλλα προσελαβοντο αυτον και ακριβεστερον αυτω εξεθεντο την του [θεου]{.greek-abbr} οδον[18:26]{.aside}

βουλομενου δε αυτου διελθειν εις την αχαιαν προτρεψαμενοι οι αδελφοι εγρ[α]{.unclear}ψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος συνεβαλετο πολυ τοις πεπιστευκοσιν [[πεπιστευκοσι]{.corr}]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν [τω]{.unclear} τον απολλω ειναι εν κορινθω παυλον διελθ[ο]{.unclear}ντα τα [ανωτερικα]{.greek-omitted} [ανατολικα]{.greek-added} μερη ελθειν εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε ειπον προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} τε προς αυτους εις τι ουν εβαπτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

ειπεν [δε]{.greek-omitted} [[ειπε]{.corr}]{.greek-added} [τε]{.greek-added} παυλος ιωαννης μεν εβαπτισεν [[εβαπτισε]{.corr}]{.greek-added} βαπτισμα μετανοιας [παντι]{.greek-added} τω λαω λεγων εις τον ερχομενον μετ αυτον ινα πιστευσωσιν [[πιστευσωσι]{.corr}]{.greek-added} τουτ εστιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας ηλθεν [[ηλθε]{.corr}]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν [τε]{.greek-omitted} [δε]{.greek-added} γλωσσαις και [προεφητευον]{.greek-omitted} [επροφητευον]{.greek-added}[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει δεκαδυο[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους [α]{.unclear}ποστας απ αυτων [αφωρισεν]{.greek-omitted} [αφορισεν]{.greek-added} [[αφορισε]{.corr}]{.greek-added} τους μαθητ[ας]{.unclear} [το]{.greek-added} καθ ημεραν διαλεγομενος εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι ετη δυο ωστε παντας τους κατοικουντας την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας εποιει ο [θεος]{.greek-abbr} δια των χειρων παυλου[19:11]{.aside}

ωστε και επι τους ασθενουντας [επιφερεσθαι]{.greek-omitted} [αποφερεσθαι]{.greek-added} απο του χρωτος αυτου σουδαρια η σιμικινθια και απαλλασσεσθαι απ αυτων τας νοσους τα τε [πνευματα]{.greek-abbr} τα πονηρα εξερχεσθαι απ αυτων[19:12]{.aside}

επεχειρησαν δε τινες [και]{.greek-added} απο των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους εχοντας τα πνευματα τα πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} λεγοντες [ορκιζομεν]{.greek-omitted} [ορκιζωμεν]{.greek-added} υμας τον [ιησουν]{.greek-abbr} ον ο παυλος [κηρυσσει]{.greek-omitted} [κηρυττει]{.greek-added}[19:13]{.aside}

ησαν δε τινες υιοι σκευα ιουδαιου αρχιερεως επτα οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε το [πνευμα]{.greek-abbr} το πονηρον ειπεν [[ειπε]{.corr}]{.greek-added} τον [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και εφαλλομενος επ αυτους ο [ανθρωπος]{.greek-abbr} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον και [κατακυριευσαν]{.greek-omitted} [κατακυριευσας]{.greek-added} [αυτων]{.greek-omitted} [αμφοτερων]{.greek-added} ισχυσεν [[ισχυσε]{.corr}]{.greek-added} κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν εκ του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον πασιν ιουδαιοις τε και ελλησιν [[ελλησι]{.corr}]{.greek-added} τοις κατοικουσιν [[κατοικουσι]{.corr}]{.greek-added} την εφεσον και επεπεσεν [[επεπεσε]{.corr}]{.greek-added} φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι τε των πεπιστευκοτων ηρχοντο εξομολογουμενοι και αναγγελλοντες τας πραξεις αυτων[19:18]{.aside}

ικανοι δε των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και [συνεψηφισαν]{.greek-omitted} [συνεψηφησαν]{.greek-added} τας τιμας αυτων και ευρον αργυριου μυριαδας πεντε[19:19]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} κατα κρατος ο λογος του [κυριου]{.greek-abbr} ηυξανεν [[ηυξανε]{.corr}]{.greek-added} και ισχυεν[19:20]{.aside}

ως δε επληρωθη ταυτα εθετο [ο]{.greek-omitted} παυλος εν τω [πνευματι]{.greek-abbr} διελθων την μακεδονιαν και αχαιαν πορευεσθαι εις [ιερουσαλημ]{.greek-abbr} ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις την μακεδονιαν δυο των διακονουντων αυτω τιμοθεον και εραστον αυτος επεσχεν [[επεσχε]{.corr}]{.greek-added} χρονον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [ασιαν]{.greek-omitted} [ασια]{.greek-added}[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος περι της οδου[19:23]{.aside}

δημητριος γαρ [τις]{.greek-omitted} [τω]{.greek-added} ονοματι αργυροκοπος ποιων ναους αργυρους αρτεμιδος παρειχετο τοις τεχνιταις εργασιαν ουκ ολιγην[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας ειπεν ανδρες επιστασθε οτι εκ ταυτης της εργασιας η ευπορια ημων εστιν [[εστι]{.corr}]{.greek-added}[19:25]{.aside}

και θεωρειτε και ακουετε οτι ου μονον εφεσου αλλα σχεδον πασης της ασιας ο παυλος [ουτος]{.greek-omitted} [ουτως]{.greek-added} πεισας μετεστησεν ικανον οχλον λεγων οτι ουκ εισιν [[εισι]{.corr}]{.greek-added} θεοι οι δια χειρων γινομενοι[19:26]{.aside}

ου μονον δε τουτο κινδυνευει ημιν το μερος εις απελεγμον ελθειν αλλα και το της μεγαλης θεας ιερον αρτεμιδος εις ουθεν λογισθηναι [μελλειν]{.greek-omitted} [μελλει]{.greek-added} δε και καθαιρεισθαι την [μεγαλειοτητα]{.greek-omitted} [μεγαλιοτητα]{.greek-added} αυτης ην ολη η ασια και η οικουμενη σεβεται[19:27]{.aside}

ακουσαντες δε και γενομενοι πληρεις θυμου εκραζον λεγοντες μεγαλη η αρτεμις εφεσιων[19:28]{.aside}

και επλησθη η πολις ολη της συγχυσεως ωρμησαν τε ομοθυμαδον εις το θεατρον συναρπασαντες γαιον και αρισταρχον μακεδονας συνεκδ[η]{.greek-supplied}μους παυλου[19:29]{.aside}

του δε παυλου βουλομενου εισελθειν εις τον δημον ουκ ειων αυτον οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες αυτω φιλοι πεμψαντες προς αυτον παρεκαλουν μη δουναι εαυτον εις το θεατρον[19:31]{.aside}

αλλοι μεν ουν αλλο τι εκραζον ην γαρ η εκκλησια συγκεχυμενη και οι πλειους ουκ ηδεισαν τινος ενεκεν [συνεληλυθεισαν]{.greek-omitted} [συνεληλυθησαν]{.greek-added}[19:32]{.aside}

εκ δε του οχλου προεβιβασαν αλεξανδρον [προβαλοντων]{.greek-omitted} [προβαλλοντων]{.greek-added} αυτον των ιουδαιων ο δε αλεξανδρος κατασεισας [την]{.greek-omitted} [τη]{.greek-added} [χειρα]{.greek-omitted} [χειρι]{.greek-added} ηθελεν [απολογεισθαι]{.greek-omitted} [απολογησασθαι]{.greek-added} τω δημω[19:33]{.aside}

επιγνοντες δε οτι ιουδαιος εστιν [[εστι]{.corr}]{.greek-added} φωνη εγενετο μια εκ παντων ως επι ωρας δυο κραζοντων μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλας δε ο γραμματευς τον οχλον φησιν ανδρες εφεσιοι τις γαρ εστιν [ανθρωπος]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} ος ου γινωσκει την εφεσιων πολιν νεωκορον ουσαν της μεγαλης θεας αρτεμιδος και του διοπετους[19:35]{.aside}

αναντιρρητων ουν οντων τουτων δεον εστιν υμας κατεσταλμενους υπαρχειν και μηδεν προπετες πρασσειν[19:36]{.aside}

ηγαγετε γαρ τους ανδρας τουτους ουτε ιεροσυλους ουτε βλασφημουντας την θεον υμων[19:37]{.aside}

ει μεν ουν δημητριος και οι συν αυτω [τεχνιται]{.greek-omitted} [τεχνηται]{.greek-added} εχουσιν [[εχουσι]{.corr}]{.greek-added} προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν εγκαλειτωσαν αλληλοις[19:38]{.aside}

ει δε τι περι ετερων επιζητειτε εν τη εννομω εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι της σημερον μηδενος αιτιου υπαρχοντος περι ου ου δυνησομεθα δουναι λογον [περι]{.greek-added} της συστροφης ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσεν]{.greek-added} [[απελυσε]{.corr}]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον θορυβον προσκαλεσαμενος ο παυλος τους μαθητας και [παρακαλεσας]{.greek-added} ασπασαμενος [τε]{.greek-added} εξηλθεν [[εξηλθε]{.corr}]{.greek-added} πορευθηναι εις [την]{.greek-omitted} μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας τε μηνας τρεις γενομενης αυτω επιβουλης υπο των ιουδαιων μελλοντι αναγεσθαι εις την συριαν εγενετο [γνωμη]{.greek-omitted} [γνωμης]{.greek-added} του υποστρεφειν δια μακεδονιας[20:3]{.aside}

συνειπετο [δε]{.greek-omitted} [δ]{.greek-added} αυτω [αχρι]{.greek-omitted} [μεχρι]{.greek-added} της ασιας [σωπατρος]{.greek-omitted} [σωσιπατρος]{.greek-added} [πυρρου]{.greek-added} βεροιαιος [θεσσαλονικεων]{.greek-omitted} [θεσσαλονικαιων]{.greek-added} δε αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος ασιανοι δε τυχικος και [τροφιμος]{.greek-omitted} [τροφημος]{.greek-added}[20:4]{.aside}

[ουτοι]{.greek-omitted} [αυτοι]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-omitted} [προελθοντες]{.greek-added} εμενον ημας εν τρωαδι[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και ηλθομεν προς αυτους εις την τρωαδα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ημερων πεντε ου διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων [ημων]{.greek-added} [των]{.greek-omitted} [μαθητων]{.greek-omitted} κλασαι αρτον ο παυλος διελεγετο αυτοις μελλων εξιεναι τη επαυριον παρετεινεν [[παρετεινε]{.corr}]{.greek-added} τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε λαμπαδες ικαναι εν τω υπερωω ου ημεν συνηγμενοι[20:8]{.aside}

καθημενος δε τις νεανιας ονοματι ευτυχος επι της θυριδος καταφερομενος υπνω βαθει διαλεγομενου του παυλου επι πλειον κατενεχθεις [απο]{.greek-omitted} [υπο]{.greek-added} του υπνου επεσεν απο του τριστεγου κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και [συμπεριλαβων]{.greek-omitted} [συμπαραλαβων]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη θορυβεισθε η γαρ ψυχη αυτου εν αυτω εστιν[20:10]{.aside}

αναβας δε και κλασας αρτον και γευσαμενος εφ ικανον τε ομιλησας [αχρι]{.greek-omitted} [αχρις]{.greek-added} αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον δε τον παιδα ζωντα και παρεκληθησαν ου μετριως[20:12]{.aside}

ημεις δε προσελθοντες επι το πλοιον ανηχθημεν [εις]{.greek-omitted} [επι]{.greek-added} την [ασσον]{.greek-omitted} [θασον]{.greek-added} εκειθεν μελλοντες αναλαμβανειν τον παυλον ουτως γαρ ην διατεταγμενος μελλων αυτος πεζευειν[20:13]{.aside}

ως δε συνεβαλεν ημιν εις την [ασσον]{.greek-omitted} [θασον]{.greek-added} αναλαβοντες αυτον ηλθομεν εις [μιτυληνην]{.greek-omitted} [μιτυλινην]{.greek-added}[20:14]{.aside}

κακειθεν αποπλευσαντες τη επιουση [κατηντησαμεν]{.greek-omitted} [κατηντισαμεν]{.greek-added} [αντικρυ]{.greek-omitted} [αντικρυς]{.greek-added} χι[ου]{.unclear} τη δε ετερα παρεβαλομεν εις σαμον και μειναντες εν [τρωγυλλιω]{.greek-omitted} [στρογυλιω]{.greek-added} τη εχομενη ηλθομεν εις μιλητον[20:15]{.aside}

εκρινεν [γαρ]{.greek-omitted} ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια εσπευδεν [[εσπευδε]{.corr}]{.greek-added} γαρ ει δυνατον ην αυτω την ημεραν της πεντηκοστης γενεσθαι εις ιεροσολυμα[20:16]{.aside}

απο δε της μιλητου πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον ειπεν αυτοις υμεις επιστασθε απο πρωτης ημερας αφ ης επεβην εις την ασιαν πως μεθ υμων τον [παντα]{.greek-omitted} [απαντα]{.greek-added} χρονον εγενομην[20:18]{.aside}

δουλευων τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και πολλων δακρυων και πειρασμων των συμβαντων μοι εν ταις επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων [υμιν]{.greek-added} του μη αναγγειλαι [υμιν]{.greek-omitted} και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

διαμαρτυρομενος ιουδαιοις τε και ελλησιν [[ελλησι]{.corr}]{.greek-added} την εις τον [θεον]{.greek-abbr} μετανοιαν και πιστιν την εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr} [[χριστον]{.greek-abbr}]{.greek-added}[20:21]{.aside}

και νυν ιδου εγω δεδεμενος τω [πνευματι]{.greek-abbr} πορευομαι εις [ιερουσαλημ]{.greek-abbr} τα εν αυτη [συναντησοντα]{.greek-omitted} [συναντησαντα]{.greek-added} μοι μη ειδως[20:22]{.aside}

πλην οτι το [πνευμα]{.greek-abbr} το αγιον κατα πολιν διαμαρτυρεται [μοι]{.greek-added} [λεγον]{.greek-omitted} [λεγων]{.greek-added} οτι δεσμα [με]{.greek-omitted} και θλιψεις [με]{.greek-added} μενουσιν[20:23]{.aside}

αλλ ουδενος λογον ποιουμαι ουδε εχω την ψυχην μου τιμιαν εμαυτω ως τελειωσαι τον δρομον μου μετα χαρας και την διακονιαν ην ελαβον παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι οψεσθε το προσωπον μου υμεις παντες εν οις διηλθον κηρυσσων την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

[διοτι]{.greek-omitted} [διο]{.greek-added} μαρτυρομαι υμιν εν τη σημερον ημερα οτι καθαρος εγω απο του αιματος παντων [υμων]{.greek-added}[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι υμιν πασαν την βουλην του [θεου]{.greek-abbr}[20:27]{.aside}

προσεχετε [ουν]{.greek-omitted} εαυτοις και παντι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επισκοπους [ποιμαινειν]{.greek-omitted} [ποιμενειν]{.greek-added} την εκκλησιαν του [κυριου]{.greek-omitted} [και]{.greek-omitted} [θεου]{.greek-abbr} ην περιεποιησατο δια του ιδιου αιματος[20:28]{.aside}

εγω γαρ οιδα τουτο οτι εισελευσονται μετα την αφιξιν μου λυκοι βαρεις εις υμας μη φειδομενοι του ποιμνιου[20:29]{.aside}

και εξ υμων αυτων αναστησονται ανδρες λαλουντες διεστραμμενα του αποσπαν τους μαθητας οπισω αυτων[20:30]{.aside}

διο γρηγορειτε μνημονευοντες οτι τριετιαν νυκτα και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον [υμων]{.greek-added}[20:31]{.aside}

και τα νυν παρατιθεμαι υμας αδελφοι τω [θεω]{.greek-abbr} και τω λογω της χαριτος αυτου τω δυναμενω εποικοδομησαι και δουναι [υμιν]{.greek-omitted} κληρονομιαν εν τοις ηγιασμενοις πασιν[20:32]{.aside}

αργυριου η χρυσιου η ιματισμου ουδενος επεθυμησα[20:33]{.aside}

αυτοι γινωσκετε οτι ταις χρειαις μου και τοις ουσιν [[ουσι]{.corr}]{.greek-added} μετ εμου υπηρετησαν αι χειρες αυται[20:34]{.aside}

παντα υπεδειξα υμιν οτι ουτως [[ουτω]{.corr}]{.greek-added} κοπιωντας δει αντιλαμβανεσθαι των ασθενουντων μνημονευειν τε των λογων του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} οτι αυτος ειπεν [[ειπε]{.corr}]{.greek-added} μακαριον εστιν [[εστι]{.corr}]{.greek-added} μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα γονατα αυτου συν πασιν αυτοις προσηυξατο[20:36]{.aside}

ικανος δε εγενετο κλαυθμος παντων και επιπεσοντες επι τον τραχηλον του παυλου κατεφιλουν αυτον[20:37]{.aside}

[οδυνωμενοι]{.greek-omitted} [οδυνομενοι]{.greek-added} μαλιστα επι τω λογω ω ειρηκει οτι ουκετι μελλουσιν [[μελλουσι]{.corr}]{.greek-added} το προσωπον αυτου θεωρειν προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας αποσπασθεντας απ αυτων ευθυδρομησαντες ηλθομεν εις την κων τη δε εξης εις την ροδον κακειθεν εις παταρα[21:1]{.aside}

και ευροντες πλοιον [διαπερων]{.greek-omitted} [διαπερουν]{.greek-added} εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

αναφανεντες δε [εις]{.greek-added} την κυπρον και [καταλιποντες]{.greek-omitted} [καταλειποντες]{.greek-added} αυτην ευωνυμον επλεομεν εις συριαν και κατηχθημεν εις τυρον εκεισε γαρ ην το πλοιον αποφορτιζομενον τον γομον[21:3]{.aside}

και ανευροντες μαθητας επεμειναμεν αυτου ημερας επτα οιτινες τω παυλω ελεγον δια του [πνευματος]{.greek-abbr} μη αναβαινειν εις ιερουσαλημ[21:4]{.aside}

οτε δε εγενετο ημας εξαρτισαι τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν γυναιξιν [[γυναιξι]{.corr}]{.greek-added} και τεκνοις εως εξω της πολεως και θεντες τα γονατα επι τον αιγιαλον [προσηυξαμεθα]{.greek-omitted} [προσευξαμενοι]{.greek-added}[21:5]{.aside}

και ασπασαμενοι αλληλους επεβημεν εις το πλοιον εκεινοι δε υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν [διανυσαντες]{.greek-omitted} [διανοισαντες]{.greek-added} απο τυρου κατηντησαμεν εις πτολεμαιδα και ασπασαμενοι τους αδελφους εμειναμεν ημεραν μιαν παρ αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες [εισηλθομεν]{.greek-added} [οι]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [ηλθον]{.greek-omitted} εις καισαρειαν και εισελθοντες εις τον οικον φιλιππου του ευαγγελιστου οντος εκ των επτα εμειναμεν παρ αυτω[21:8]{.aside}

τουτω δε ησαν θυγατερες παρθενοι τεσσαρες προφητευουσαι[21:9]{.aside}

επιμενοντων δε ημων ημερας πλειους κατηλθεν [[κατηλθε]{.corr}]{.greek-added} τις απο της ιουδαιας προφητης ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρας την ζωνην του παυλου δησας [τε]{.greek-omitted} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} τους ποδας και τας χειρας ειπεν [[ειπε]{.corr}]{.greek-added} ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τον ανδρα ου εστιν η ζωνη αυτη ουτως [[ουτω]{.corr}]{.greek-added} δησουσιν εν [ιερουσαλημ]{.greek-abbr} οι ιουδαιοι και παραδωσουσιν εις χειρας εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκ[αλ]{.unclear}ουμεν ημεις τε και οι εντοπιοι του μη αναβαινειν αυτον εις [ιερουσαλημ]{.greek-abbr}[21:12]{.aside}

απεκριθη τε ο παυλος [και]{.greek-added} [ειπεν]{.greek-added} [[ειπε]{.corr}]{.greek-added} τι ποιειτε κλαιοντες και συνθρυπτοντες μου την καρδιαν εγω γαρ ου μονον δεθηναι αλλα και αποθανειν εις [ιερουσαλημ]{.greek-abbr} ετοιμως εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου [ησυχασαμεν]{.greek-omitted} [ησυχα]{.greek-added} [σαμεν]{.greek-added} ειποντες το θελημα του [κυριου]{.greek-abbr} γενεσθω[21:14]{.aside}

μετα δε τας ημερας ταυτας επισκευασαμενοι ανεβαινομεν εις [ιερουσαλημ]{.greek-abbr}[21:15]{.aside}

συνηλθον δε και των μαθητων απο καισαρειας συν ημιν αγοντες παρ ω ξενισθωμεν μνασωνι τινι κυπριω αρχαιω μαθητη[21:16]{.aside}

γενομενων δε ημων εις ιεροσολυμα ασμενως [εδεξαντο]{.greek-omitted} [απεδεξαντο]{.greek-added} ημας οι αδελφοι[21:17]{.aside}

τη δε επιουση εισηει ο παυλος συν ημιν προς ιακωβον παντες τε παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος αυτους εξηγειτο καθ εν εκαστον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις εθνεσιν [[εθνεσι]{.corr}]{.greek-added} δια της διακονιας αυτου[21:19]{.aside}

οι δε ακουσαντες εδοξαζον τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ειποντες αυτω θεωρεις αδελφε ποσαι μυριαδες εισιν ιουδαιω[ν]{.unclear} των πεπιστευκοτων και παντες ζηλωται του νομου υπαρχουσιν [[υπαρχουσι]{.corr}]{.greek-added}[21:20]{.aside}

[κατηχηθησαν]{.greek-omitted} [κατηχησαν]{.greek-added} δε περι σου οτι αποστασιαν διδασκεις απο μωυσεως τους κατα τα εθνη παντας ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις [εθεσιν]{.greek-omitted} [εθνεσιν]{.greek-added} [περιπατειν]{.greek-omitted} [[εθνεσι]{.corr}]{.greek-added} [τοις]{.greek-added} [πατρωοις]{.greek-added} [ακολουθειν]{.greek-added}[21:21]{.aside}

τι ουν εστιν [[εστι]{.corr}]{.greek-added} παντως δει πληθος συνελθειν ακουσονται γαρ οτι εληλυθας[21:22]{.aside}

τουτο ουν ποιησον ο σοι λεγομεν εισιν [[εισι]{.corr}]{.greek-added} [συν]{.greek-added} ημιν ανδρες τεσσαρες ευχην εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων αγνισθητι συν αυτοις και δαπανησον επ αυτοις ινα [ξυρησωνται]{.greek-omitted} [ξυρησονται]{.greek-added} την κεφαλην και [γνωσιν]{.greek-omitted} [γνωσονται]{.greek-added} παντες οτι ων κατηχηνται περι σου [ουδεν]{.greek-omitted} [ουθεν]{.greek-added} εστιν αλλα στοιχεις και αυτος [φυλασσων]{.greek-added} τον νομον [φυλασσων]{.greek-omitted}[21:24]{.aside}

περι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες μηδεν τοιουτον τηρειν αυτους ει μη φυλασσεσθαι αυτους το τε ειδωλοθυτον και το αιμα και πνικτον και πορνειαν[21:25]{.aside}

τοτε ο παυλος παραλαβων τους ανδρας τη εχομενη ημερα συν αυτοις αγνισθεις [εισηει]{.greek-omitted} [εισειη]{.greek-added} εις το ιερον διαγγελλων την εκπληρωσιν των ημερων του αγνισμου εως ου προσηνεχθη υπερ ενος εκαστου αυτων η προσφορα[21:26]{.aside}

ως δε εμελλον αι επτα ημεραι [συντελεισθαι]{.greek-omitted} [συντελεσθεισαι]{.greek-added} οι απο της ασιας ιουδαιοι θεασαμενοι αυτον εν τω ιερω [συνεχεον]{.greek-omitted} [συνεχεαν]{.greek-added} παντα τον οχλον και επεβαλον [επ]{.greek-added} [αυτον]{.greek-added} τας χειρας [επ]{.greek-omitted} [αυτον]{.greek-omitted}[21:27]{.aside}

κραζοντες ανδρες ισραηλιται βοηθειτε ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου τουτου παντας πανταχου διδασκων ετι [τε]{.greek-omitted} [δε]{.greek-added} και ελληνας εισηγαγεν εις το ιερον και κεκοινωκεν [[κεκοινωκε]{.corr}]{.greek-added} τον αγιον τοπον τουτον[21:28]{.aside}

ησαν γαρ [εωρακοτες]{.greek-omitted} [προεωρακοτες]{.greek-added} [τροφιμον]{.greek-omitted} [τροφημον]{.greek-added} τον εφεσιον εν τη πολει συν αυτω ον ενομιζον οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

εκινηθη τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του παυλου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

ζητουντων δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της σπειρης οτι ολη συγκεχυται [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και εκατονταρχους κατεδραμεν επ αυτους οι δε ιδοντες τον χιλιαρχον και τους στρατιωτας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

εγγισας [δε]{.greek-omitted} [ουν]{.greek-added} ο χιλιαρχος επελαβετο αυτου και εκελευσεν [[εκελευσε]{.corr}]{.greek-added} δεθηναι αλυσεσιν δυσιν [[δυσι]{.corr}]{.greek-added} και επυνθανετο τις αν ειη και τι εστιν [[εστι]{.corr}]{.greek-added} πεποιηκως[21:33]{.aside}

αλλοι δ[ε]{.unclear} [α]{.unclear}λλο τι [εβοων]{.greek-omitted} [επεβοων]{.greek-added} εν τω οχλω μη δυναμενος δε γνωναι το ασφαλες δια τον θορυβον εκελευσεν [αυτον]{.greek-added} [ο]{.greek-added} [χιλιαρχος]{.greek-added} αγεσθαι [αυτον]{.greek-omitted} εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον υπο των στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

ηκολουθει γαρ το πληθος του λαου κραζον αιρε αυτον[21:36]{.aside}

μελλων τε εισαγεσθαι εις την παρεμβολην ο παυλος λεγει τω χιλιαρχω ει εξεστιν [[εξεστι]{.corr}]{.greek-added} μοι ειπειν προς σε ο δε εφη ελληνιστι γινωσκεις[21:37]{.aside}

ουκ αρα συ ει ο αιγυπτιος ο προ τουτων των ημερων αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε ο παυλος εγω [ανθρωπος]{.greek-abbr} μεν ειμι ιουδαιος ταρσευς της κιλικιας ουκ [ασημου]{.greek-omitted} [ασιμου]{.greek-added} πολεως πολιτης δεομαι δε σου επιτρεψον μοι λαλησαι προς τον λαον[21:39]{.aside}

επιτρεψαντος δε [αυτων]{.greek-added} [αυτου]{.corr} ο παυλος εστως επι των αναβαθμων [κατεσεισεν]{.greek-omitted} [κατεσεισε]{.greek-added} τη χειρι τω λαω πολλης δε σιγης γενομενης [προσεφωνησεν]{.greek-added} [προσεφωνει]{.greek-omitted} [[προσεφωνησε]{.corr}]{.greek-added} τη εβραιδι διαλεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς υμας νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη εβραιδι διαλεκτω προσεφωνει αυτοις μαλλον παρεσχον ησυχιαν και φησιν[22:2]{.aside}

εγω μεν ειμι ανηρ ιουδαιος γεγεννημενος εν ταρσω της κιλικιας ανατεθραμμενος δε εν τη πολει ταυτη παρα τους ποδας γαμαλιηλ πεπαιδευμενος κατα ακριβειαν του πατρωου νομου ζηλωτης υπαρχων του [θεου]{.greek-abbr} καθως παντες υμεις εστε σημερον[22:3]{.aside}

ος ταυτην την οδον εδιωξα [αχρι]{.greek-omitted} [μεχρι]{.greek-added} θανατου δεσμευων και παραδιδους εις φυλακας ανδρας τε και γυναικας[22:4]{.aside}

ως και ο αρχιερευς μαρτυρει μοι και παν το πρεσβυτεριον παρ ων και επιστολας δεξαμενος προς τους αδελφους εις δαμασκον επορευομην αξων και τους εκεισε οντας δεδεμενους εις [ιερουσαλημ]{.greek-abbr} ινα τιμωρηθωσιν[22:5]{.aside}

εγενετο δε μοι πορευομενω και εγγιζοντι τη δαμασκω περι μεσημβριαν εξαιφνης εκ του [ουρανου]{.greek-abbr} περιαστραψαι φως ικανον περι εμε[22:6]{.aside}

επεσα τε εις το εδαφος και ηκουσα φωνης λεγουσης μοι [σαουλ]{.greek-omitted} [σαυλε]{.greek-added} [σαουλ]{.greek-omitted} [σαυλε]{.greek-added} τι με διωκεις[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} ειπεν [[ειπε]{.corr}]{.greek-added} τε προς με εγω ειμι [ιησους]{.greek-abbr} ο ναζωραιος ον συ διωκεις[22:8]{.aside}

οι δε συν εμοι οντες το μεν φως εθεασαντο και εμφοβοι εγενοντο την δε φωνην ουκ ηκουσαν του λαλουντος μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς με αναστας πορευου εις δαμασκον κακει σοι λαληθησεται [τι]{.greek-added} [σε]{.greek-added} [δει]{.greek-added} [περι]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [τετακται]{.greek-omitted} [σοι]{.greek-omitted} ποιησαι[22:10]{.aside}

ως δε ουκ ενεβλεπον απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι ηλθον εις δαμασκον[22:11]{.aside}

ανανιας δε τις ανηρ [ευσεβης]{.greek-omitted} [ευλαβης]{.greek-added} κατα τον νομον μαρτυρουμενος υπο παντων των κατοικουντων [εν]{.greek-added} [δαμασκω]{.greek-added} ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας ειπεν [[ειπε]{.corr}]{.greek-added} μοι σαουλ αδελφ[ε]{.unclear} αναβλεψον καγω αυτη τη ωρα [ανεβλεψα]{.greek-omitted} [ενεβλεψα]{.greek-added} εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων προεχειρισατο σε γνωναι το θελημα αυτου και ιδειν τον δικαιον και ακουσαι φωνην εκ του στοματος αυτου[22:14]{.aside}

οτι εση μαρτυς αυτω προς παντας [ανθρωπους]{.greek-abbr} ων εωρακας και ηκουσας[22:15]{.aside}

και νυν τι μελλεις αναστας βαπτισαι και απολουσαι τας αμαρτι[α]{.unclear}ς σου επικαλεσαμενος το ονομα [του]{.greek-omitted} [κυριου]{.greek-abbr}[22:16]{.aside}

εγενετο δε [μοι]{.greek-omitted} [με]{.greek-added} [υποστρεψαντι]{.greek-omitted} [υποστρεψαντα]{.greek-added} εις [ιερουσαλημ]{.greek-abbr} [και]{.greek-omitted} [προσευχομενου]{.greek-omitted} [προσευχομενον]{.greek-added} [μου]{.greek-omitted} [τε]{.greek-added} εν τω ιερω γενεσθαι [με]{.greek-omitted} εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον και εξελθε εν [τα]{.greek-added} [ταχει]{.greek-omitted} [χει]{.greek-added} εξ [ιερουσαλημ]{.greek-abbr} διοτι ου παραδεξονται σου την μαρτυριαν περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω ημην φυλακιζων και [δερων]{.greek-omitted} [δαιρων]{.greek-added} κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε [εξεχειτο]{.greek-omitted} [εξεχυτο]{.greek-added} το αιμα στεφανου του μαρτυρος σου και αυτος ημην εφεστως και συνευδοκων τη αναιρεσει αυτου [και]{.greek-added} [φυλασσων]{.greek-omitted} [φυλαττων]{.greek-added} τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και ειπεν [η]{.greek-added} [φωνη]{.greek-added} προς με πορευου οτι εγω εις [εθνη]{.greek-omitted} [εθνος]{.greek-added} μακραν εξαποστελω σε[22:21]{.aside}

ηκουον δε αυτου αχρι [τουτου]{.greek-omitted} του λογου [τουτου]{.greek-added} και επηραν [αυτων]{.greek-added} την φωνην [αυτων]{.greek-omitted} λεγοντες αιρε απο της γης τον τοιουτον ου γαρ καθηκεν αυτον ζην[22:22]{.aside}

[κραζοντων]{.greek-omitted} [κραυγαζοντων]{.greek-added} δε αυτων και [ριπτουντων]{.greek-omitted} [ριπτοντων]{.greek-added} τα ιματια και κονιορτον βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν αυτον ο χιλιαρχος αγεσθαι εις την παρεμβολην ειπων [μαστιξιν]{.greek-omitted} [μαστιγξιν]{.greek-added} ανεταζεσθαι αυτον [ινα]{.greek-omitted} [ιν]{.greek-added} επιγνω δι ην αιτιαν ουτως επεφωνουν αυτω[22:24]{.aside}

ως δε [προετεινεν]{.greek-omitted} [προετειναν]{.greek-added} αυτον τοις ιμασιν ειπεν [[ειπε]{.corr}]{.greek-added} προς τον [εστωτα]{.greek-omitted} [εφεστωτα]{.greek-added} εκατονταρχον ο παυλος ει [ανθρωπον]{.greek-abbr} ρωμαιον και ακατακριτον εξεστιν υμιν μαστιζειν[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων απηγγειλεν [[απηγγειλε]{.corr}]{.greek-added} τω χιλιαρχω λεγων ορα τι μελλεις ποιειν ο γαρ [ανθρωπος]{.greek-abbr} ουτος ρωμαιος εστιν [[εστι]{.corr}]{.greek-added}[22:26]{.aside}

προσελθων δε ο χιλιαρχος ειπεν αυτω λεγε μοι [ει]{.greek-omitted} συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκριθη τε ο χιλιαρχος εγω πολλου κεφαλαιου την πολιτειαν ταυτην [εκτησαμην]{.greek-omitted} [εκτισαμην]{.greek-added} ο δε παυλος εφη εγω δε και γεγεννημαι[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες αυτον ανεταζειν και ο χιλιαρχος δε εφοβηθη επιγνους οτι ρωμαιος εστιν [[εστι]{.corr}]{.greek-added} και οτι ην αυτον δεδεκως[22:29]{.aside}

τη δε επαυριον βουλομενος γνωναι το ασφαλες το τι κατηγορειται [παρα]{.greek-omitted} [υπο]{.greek-added} των ιουδαιων ελυσεν αυτον απο των δεσμων και εκελευσεν ελθειν τους αρχιερεις και ολον το συνεδριον αυτων και καταγαγων τον παυλον εστησεν εις αυτους[22:30]{.aside}

### Chapter 23

ατενισας δε ο παυλος τω σ[υν]{.unclear}εδριω ειπεν ανδρες αδελφοι εγω παση συνειδησει αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι ταυτης της ημερας[23:1]{.aside}

ο δε αρχιερευς ανανιας επεταξεν [[επεταξε]{.corr}]{.greek-added} τοις παρεστωσιν αυτω τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον ειπεν [[ειπε]{.corr}]{.greek-added} τυπτειν σε μελλει ο [θεος]{.greek-abbr} τοιχε κεκονιαμενε και συ καθη κρινων με κατα τον νομον και παρανομων κελευεις με τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες ειπον τον αρχιερεα του [θεου]{.greek-abbr} λοιδορεις[23:4]{.aside}

εφη τε ο παυλος ουκ ηδειν αδελφοι οτι εστιν αρχιερευς γεγραπται γαρ [οτι]{.greek-added} αρχοντα του λαου σου ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος εστιν [[εστι]{.corr}]{.greek-added} σαδδουκαιων το δε ετερον φαρισαιων εκραξεν εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμι [υιος]{.greek-abbr} φαρισαιου περι ελπιδος και αναστασεως νεκρων εγω κρινομαι[23:6]{.aside}

τουτο δε αυτου λαλησαντος εγενετο στασις των φαρισαιων και [των]{.greek-added} [σαδδουκαιων]{.greek-added} [και]{.greek-added} εσχισθη το πληθος[23:7]{.aside}

σαδδουκαιοι μεν γαρ λεγουσιν [[λεγουσι]{.corr}]{.greek-added} μη ειναι αναστασιν μηδε αγγελον μητε [πνευμα]{.greek-abbr} φαρισαιοι δε ομολογουσιν [[ομολογουσι]{.corr}]{.greek-added} τα αμφοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και α[ν]{.unclear}ασταντες [τινες]{.greek-added} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [του]{.greek-omitted} [μερους]{.greek-omitted} των φαρισαιων διεμαχοντο λεγοντες ουδεν κακον [ευρισκομεν]{.greek-omitted} [ευρισκωμεν]{.greek-added} εν τω [ανθρωπω]{.greek-abbr} τουτω ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω η αγγελος μη θεομαχωμεν[23:9]{.aside}

πολλης δε γενομενης στασεως ευλαβηθεις ο χιλιαρχος μη διασπασθη ο παυλος υπ αυτων εκελευσεν [[εκελευσε]{.corr}]{.greek-added} το στρατευμα καταβηναι και αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση νυκτι επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν [[ειπε]{.corr}]{.greek-added} θαρσει παυλε ως γαρ διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} ουτως [σε]{.greek-omitted} [[ουτω]{.corr}]{.greek-added} δει και εις ρωμην μαρτυρησαι[23:11]{.aside}

γενομενης δε ημερας ποιησαντες τινες των ιουδαιων συστροφην ανεθεματισαν εαυτους λεγοντες μητε φαγειν μητε πιειν εως ου αποκτεινωσιν [[αποκτεινωσι]{.corr}]{.greek-added} τον παυλον[23:12]{.aside}

ησαν δε πλειους [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} οι ταυτην την συνωμοσιαν πεποιηκοτες[23:13]{.aside}

οιτινες προσελθοντες τοις αρχιερευσιν [[αρχιερευσι]{.corr}]{.greek-added} και τοις πρεσβυτεροις ειπον αναθεματι ανεθεματισαμεν εαυτους μηδενος γευσασθαι εως [ου]{.greek-omitted} [αν]{.greek-added} αποκτεινωμεν τον παυλον[23:14]{.aside}

νυν ουν υμεις εμφανισατε τω χιλιαρχω συν τω συνεδριω οπως αυριον αυτον καταγαγη προς υμας ως μελλοντας [ακριβεστερον]{.greek-added} διαγινωσκειν [ακριβεστερον]{.greek-omitted} τα περι αυτου ημεις δε προ του εγγισαι αυτον ετοιμοι εσμεν του ανελειν αυτον[23:15]{.aside}

ακουσας δε ο [υιος]{.greek-abbr} της αδελφης παυλου το ενεδρον παραγενομενος και εισελθων εις την παρεμβολην απηγγειλεν [[απηγγειλε]{.corr}]{.greek-added} τω παυλω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων [εφη]{.greek-omitted} [ειπεν]{.greek-added} [[ειπε]{.corr}]{.greek-added} τον νεανιαν τουτον απαγαγε προς τον χιλιαρχον [εχει]{.greek-omitted} [γαρ]{.greek-omitted} [τι]{.greek-omitted} [απαγγειλαι]{.greek-omitted} [αυτω]{.greek-omitted}[23:17]{.aside}

[ο]{.greek-omitted} [μεν]{.greek-omitted} [ουν]{.greek-omitted} [παραλαβων]{.greek-omitted} [αυτον]{.greek-omitted} [ηγαγεν]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [χιλιαρχον]{.greek-omitted} και φησιν ο δεσμιος παυλος προσκαλεσαμενος με ηρωτησεν [τουτον]{.greek-omitted} [[ηρωτησε]{.corr}]{.greek-added} τον νεανιαν [τουτον]{.greek-added} αγαγειν προς σε εχοντα τι λαλησαι σοι[23:18]{.aside}

επιλαβομενος δε της χειρος αυτου ο χιλιαρχος και αναχωρησας κατ ιδιαν επυνθανετο τι εστιν ο εχεις απαγγειλαι μοι[23:19]{.aside}

ειπεν [[ειπε]{.corr}]{.greek-added} δε οτι οι ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον εις το συνεδριον καταγαγης τον παυλον ως μελλοντα τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ ουν μη πεισθης αυτοις ενεδρ[ευ]{.unclear}ουσιν [[ενεδρ[ευ]{.unclear}ουσι]{.corr}]{.greek-added} γαρ αυτον εξ αυτων ανδρες πλειους [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} οιτινες ανεθεματισαν εαυτους μητε φαγειν μητε πιειν εως [ου]{.greek-omitted} [αν]{.greek-added} ανελωσιν αυτον και νυν ετοιμοι εισιν [[εισι]{.corr}]{.greek-added} προσδεχομενοι την απο σου επαγγελιαν[23:21]{.aside}

ο μεν ουν χιλιαρχος απελυσεν [[απελυσε]{.corr}]{.greek-added} τον νεανιαν παραγγειλας μηδενι εκλαλησαι οτι ταυτα ενεφανισας προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους οπως πορευθωσιν εως καισαρειας και ιππεις εβδομηκοντα και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

κτηνη τε παραστησαι [ινα]{.greek-omitted} [οπως]{.greek-added} επιβιβασαντες τον παυλον διασωσωσιν [[διασωσωσι]{.corr}]{.greek-added} προς [φηλικα]{.greek-omitted} [φιλικα]{.greek-added} τον ηγεμονα[23:24]{.aside}

γραψας επιστολην περιεχουσαν τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω ηγεμονι [φηλικι]{.greek-omitted} [φιλικι]{.greek-added} χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο [των]{.greek-omitted} ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι εξειλομην αυτον μαθων οτι ρωμαιος εστιν [[εστι]{.corr}]{.greek-added}[23:27]{.aside}

βουλομενος δε γνωναι την αιτιαν δι ην ενεκαλουν αυτω κατηγαγον αυτον εις το συνεδριον αυτων[23:28]{.aside}

ον ευρον εγκαλουμενον περι ζητηματων του νομου αυτων μηδεν [δε]{.greek-added} αξιον θανατου η δεσμων [εχοντα]{.greek-added} εγκλημα [εχοντα]{.greek-omitted}[23:29]{.aside}

μηνυθεισης δε μοι επιβουλης εις τον ανδρα μελλειν εσεσθαι υπο των ιουδαιων εξαυτης επεμψα προς σε παραγγειλας και τοις κατηγοροις λεγειν τα προς αυτον επι σου ερρωσο[23:30]{.aside}

οι μεν ουν στρατιωται κατα το διατεταγμενον αυτοις αναλαβοντες τον παυλον ηγαγον δια [της]{.greek-omitted} νυκτος εις την αντιπατριδα[23:31]{.aside}

τη δε επαυριον εασαντες τους ιππεις πορευεσθαι συν αυτω υπεστρεψαν εις την παρεμβολην[23:32]{.aside}

οιτινες εισελθοντες εις την καισαρειαν και αναδοντες την επιστολην τω ηγεμονι παρεστησαν και τον παυλον αυτω[23:33]{.aside}

αναγνους δε ο ηγεμων και επερωτησας εκ ποιας επαρχιας εστιν [[εστι]{.corr}]{.greek-added} και πυθομενος οτι απο κιλικιας[23:34]{.aside}

διακουσομαι σου εφη οταν [και]{.greek-omitted} οι κατηγοροι σου παραγενωνται εκελευσεν [[εκελευσε]{.corr}]{.greek-added} τε αυτον εν τω πραιτωριω ηρωδου φυλασσεσθαι[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη ο αρχιερευς ανανιας μετα [των]{.greek-omitted} πρεσβυτερων και ρητορος τερτυλλου τινος οιτινες [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} τω ηγεμονι κατα του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο κατηγορειν ο τερτυλλος λεγων πολλης ειρηνης τυγχανοντες δια σου και [κατορθωματων]{.greek-omitted} [κατωρθωματων]{.greek-added} γινομενων τω εθνει τουτω δια της σης προνοιας[24:2]{.aside}

[παντη]{.greek-omitted} [παντι]{.greek-added} τε και πανταχου αποδεχομεθα κρατιστε [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} μετα πασης [ευχαριστιας]{.greek-omitted} [ευχαριστειας]{.greek-added}[24:3]{.aside}

ινα δε μη επι πλειον σε εγκοπτω παρακαλω ακουσαι σε [ημων]{.greek-omitted} συντομως τη ση επιεικεια[24:4]{.aside}

ευροντες γαρ τον ανδρα τουτον λοιμον και κινουντα στασιν πασιν [[πασι]{.corr}]{.greek-added} τοις ιουδαιοις τοις κατα την οικουμενην πρωτοστατην τε [οντα]{.greek-added} της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον επειρασεν [[επειρασε]{.corr}]{.greek-added} βεβηλωσαι ον και εκρατησαμεν [και]{.greek-added} [κατα]{.greek-added} [τον]{.greek-added} [ημετερον]{.greek-added} [νομον]{.greek-added} [ηθελησαμεν]{.greek-added} [κριναι]{.greek-added}[24:6]{.aside}

[παρελθων]{.greek-added} [δε]{.greek-added} [λυσιας]{.greek-added} [ο]{.greek-added} [χιλιαρχος]{.greek-added} [μετα]{.greek-added} [πολλης]{.greek-added} [βιας]{.greek-added} [εκ]{.greek-added} [των]{.greek-added} [χειρων]{.greek-added} [ημων]{.greek-added} [απηγαγεν]{.greek-added} [[απηγαγε]{.corr}]{.greek-added}[24:7]{.aside}

[κελευσας]{.greek-added} [τους]{.greek-added} [κατηγορους]{.greek-added} [αυτου]{.greek-added} [ερχεσθαι]{.greek-added} [επι]{.greek-added} [σου]{.greek-added} παρ ου δυνηση [και]{.greek-added} αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

συνεπεθεντο δε και οι ιουδαιοι φασκοντες ταυτα ουτως [εχειν]{.greek-omitted} [εχει]{.greek-added}[24:9]{.aside}

απεκριθη [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος νευσαντος αυτω του ηγεμονος λεγειν εκ πολλων ετων οντα σε κριτην [δικαιον]{.greek-added} τω εθνει τουτω επισταμενος [ευθυμοτερον]{.greek-omitted} [ευθυμως]{.greek-added} τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου γνωναι οτι ου πλειους εισιν [[εισι]{.corr}]{.greek-added} μοι ημεραι δεκαδυο αφ ης ανεβην προσκυνησων [εν]{.greek-omitted} [εις]{.greek-added} [ιερουσαλημ]{.greek-abbr}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η επισυστασιν ποιουντα οχλου ουτε εν ταις συναγωγαις ουτε κατα την [πο]{.greek-added} [πολιν]{.greek-omitted} [λιν]{.greek-added}[24:12]{.aside}

ουτε παραστησαι [με]{.greek-omitted} δυνανται [σοι]{.greek-added} περι ων νυν κατηγορουσιν [[κατηγορουσι]{.corr}]{.greek-added} μου[24:13]{.aside}

ομολογω δε [σοι]{.greek-added} τουτο [σοι]{.greek-omitted} οτι κατα την οδον ην λεγουσιν [[λεγουσι]{.corr}]{.greek-added} αιρεσιν ουτως [[ουτω]{.corr}]{.greek-added} λατρευω τω πατρωω [θεω]{.greek-abbr} πιστευων πασιν [[πασι]{.corr}]{.greek-added} τοις κατα τον νομον και τοις [εν]{.greek-added} [τοις]{.greek-added} προφηταις γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι προσδεχονται [αναστασιν]{.greek-omitted} [μελλειν]{.greek-omitted} [εσεσθαι]{.greek-omitted} [νεκρων]{.greek-omitted} [δικαιων]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [αδικων]{.greek-omitted}[24:15]{.aside}

εν τουτω [δε]{.greek-omitted} [και]{.greek-added} αυτος ασκω απροσκοπον συνειδησιν [εχων]{.greek-omitted} [εχειν]{.greek-added} προς τον [θεον]{.greek-abbr} και τους [ανθρωπους]{.greek-abbr} δια παντος[24:16]{.aside}

δι ετων δε πλειονων [παρεγενομην]{.greek-omitted} ελεημοσυνας ποιησων εις το εθνος μου [παρεγενομην]{.greek-added} και προσφορας[24:17]{.aside}

εν [οις]{.greek-omitted} [αις]{.greek-added} ευρον με ηγνισμενον εν τω ιερω ου μετα οχλου ουδε μετα θορυβου [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [δε]{.greek-added} [των]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιοι]{.greek-added} ους [δει]{.greek-omitted} [εδει]{.greek-added} επι σου παρειναι και κατηγορειν ει τι εχοιεν προς με[24:19]{.aside}

η αυτοι ουτοι ειπα[τ]{.greek-supplied}[ωσ]{.unclear}αν τι ευρον εν εμοι [αδικημα]{.greek-omitted} [αδικιμα]{.greek-added} σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας ταυτης φωνης ης [εκραξα]{.greek-omitted} [εκεκραξα]{.greek-added} [εστως]{.greek-omitted} εν αυτοις [εστως]{.greek-added} οτι περι αναστασεως νεκρων εγω κρινομαι σημερον [υφ]{.greek-omitted} [εφ]{.greek-added} υμων[24:21]{.aside}

ακουσας δε ταυτα ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} ανεβαλετο αυτους ακριβεστερον ειδως τα περι της οδου ειπων οταν λυσιας ο χιλιαρχος καταβη διαγνωσομαι τα καθ υμας[24:22]{.aside}

διαταξαμενος τε τω εκατονταρχη τηρεισθαι τον παυλον εχειν τε ανεσιν και μηδενα κωλυειν των ιδιων αυτου υπηρετειν η προσερχεσθαι αυτω[24:23]{.aside}

μετα δε ημερας τινας παραγενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} συν δρουσιλλη τη [ιδια]{.greek-added} [αυτου]{.greek-added} γυναικι ουση ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου περι της εις [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του μελλοντος εσεσθαι εμφοβος γενομενος ο [φηλιξ]{.greek-omitted} [φιληξ]{.greek-added} απεκριθη το νυν [εχον]{.greek-omitted} [εχων]{.greek-added} πορευου καιρον δε μεταλαβων [μετακαλεσομαι]{.greek-omitted} [μεταπεμψομαι]{.greek-added} σε[24:25]{.aside}

αμα και ελπιζων οτι χρηματα δοθησεται αυτω υπο του παυλου [οπως]{.greek-omitted} [λυση]{.greek-omitted} [αυτον]{.greek-omitted} διο και πυκνοτερον αυτον μεταπεμπομενος ωμιλει αυτω[24:26]{.aside}

διετιας δε πληρωθεισης ελαβεν [[ελαβε]{.corr}]{.greek-added} διαδοχον ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} πορκιον φηστον θελων [τε]{.greek-omitted} [δε]{.greek-added} [χαριτας]{.greek-omitted} [χαριτα]{.greek-added} καταθεσθαι τοις ιουδαιοις ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [κατελιπεν]{.greek-omitted} [κατελειπεν]{.greek-added} τον παυλον [δεδεμενον]{.greek-omitted} [δεσμιον]{.greek-added}[24:27]{.aside}

### Chapter 25

φηστος ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη εις ιεροσολυμα απο καισαρειας[25:1]{.aside}

[ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} δε αυτω [ο]{.greek-omitted} [οι]{.greek-added} [αρχιερευς]{.greek-omitted} [αρχιερεις]{.greek-added} και οι πρωτοι των ιουδαιων κατα [του]{.greek-omitted} παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται αυτον εις [ιερουσαλημ]{.greek-abbr} ενεδραν ποιουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν ουν φηστος απεκριθη τηρεισθαι τον παυλον εν καισαρεια εαυτον δε μελλειν εν ταχει εκπορευεσθαι[25:4]{.aside}

οι ουν δυνατοι εν υμιν φησιν [[φησι]{.corr}]{.greek-added} συγκαταβαντες ει τι εστιν εν τω ανδρι [τουτω]{.greek-omitted} [ατοπον]{.greek-added} [κατηγορειτωσαν]{.greek-omitted} [κατηγορησατωσαν]{.greek-added} αυτου[25:5]{.aside}

διατριψας δε εν αυτοις ημερας πλειους [οκτω]{.greek-added} η δεκα καταβας εις καισαρειαν [και]{.greek-added} τη επαυριον [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εκελευσεν [[εκελευσε]{.corr}]{.greek-added} τον παυλον αχθηναι[25:6]{.aside}

παραγενομενου δε αυτου περιεστησαν [αυτον]{.greek-added} οι απο ιεροσολυμων καταβεβηκοτες ιουδαιοι πολλα και βαρεα αιτιωματα φεροντες κατα του παυλου α ουκ ισχυον αποδειξαι[25:7]{.aside}

απολογουμενου αυτου οτι ουτε εις τον νομον των ιουδαιων ουτε εις το ιερον ουτε εις καισαρα τι ημαρτον[25:8]{.aside}

ο φηστος δε [θελων]{.greek-added} τοις ιουδαιοις [θελων]{.greek-omitted} χαριν καταθεσθαι αποκριθεις τω παυλω ειπεν θελεις εις ιεροσολυμα αναβας εκει περι τουτων κρινεσθαι επ εμου[25:9]{.aside}

[ει]{.greek-added} [ει]{.greek-added} [ειπεν]{.greek-omitted} [πεν]{.greek-added} [[πε]{.corr}]{.greek-added} δε ο παυλος επι του βηματος καισαρος εστως ειμι ου με δει κρινεσθαι ιουδαιους ουδεν ηδικησα ως και συ καλλιον επιγινωσκεις[25:10]{.aside}

[ει]{.greek-supplied} [μ]{.greek-supplied}εν γαρ αδικω και αξιον θανατου πεπραχα τι ου παραιτουμαι [το]{.greek-omitted} [του]{.greek-added} αποθανειν ει δε ουδεν εστιν ων ουτοι κατηγορουσιν [μου]{.greek-omitted} [[κατηγορουσι]{.corr}]{.greek-added} [μοι]{.greek-added} ουδεις με δυναται αυτοις χαρισασθαι καισαρα επικαλουμαι[25:11]{.aside}

τοτε ο φηστος συλλαλησας μετα του συμβουλιου απεκριθη καισαρα επικεκλησαι επι καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τινων αγριππας ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν [ασπασαμενοι]{.greek-omitted} [ασπασομενοι]{.greek-added} τον φηστον[25:13]{.aside}

ως δε πλειους ημερας [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added} εκει ο φηστος τω βασιλει ανεθετο [τα]{.greek-omitted} [το]{.greek-added} κατα τον παυλον λεγων ανηρ τις εστιν [[εστι]{.corr}]{.greek-added} καταλελειμμενος υπο [φηλικος]{.greek-omitted} [φιλικος]{.greek-added} δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις ιεροσολυμα [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου [δικην]{.greek-omitted} [καταδικην]{.greek-added}[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} [εις]{.greek-omitted} [απωλειαν]{.greek-omitted} πριν η ο κατηγορουμενος κατα προσωπον εχοι τους κατηγορους τοπον τε απολογιας λαβοι περι του εγκληματος[25:16]{.aside}

συνελθοντων ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη [δε]{.greek-added} εξης [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν επεφερον ων υπενοουν εγω [πονηρων]{.greek-added}[25:18]{.aside}

ζητηματα δε τινα περι της [ιδιας]{.greek-omitted} [εαυτων]{.greek-added} [δεισιδαιμονιας]{.greek-omitted} [δισιδαιμονιας]{.greek-added} ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τε[θνη]{.unclear}κοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω [εις]{.greek-added} την περι [τουτου]{.greek-omitted} [τουτων]{.greek-added} ζητησιν ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} κακει κρινεσθαι περι τουτων[25:20]{.aside}

του δε παυλου [επικαλεσαμενου]{.greek-omitted} [επικαλουμενου]{.greek-added} τηρηθηναι αυτον εις την του σεβα[σ]{.unclear}τ[ου]{.unclear} διαγνωσιν εκελευσα τηρεισθαι α[υτον]{.unclear} εως ου [πεμψω]{.greek-omitted} [αναπεμψω]{.greek-added} αυτον [προς]{.greek-omitted} [εις]{.greek-added} καισαρ[α]{.unclear}[25:21]{.aside}

αγριππας δε προς τον φηστον εφη εβ[ου]{.unclear}λομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της βερνικης μετα πολλης φαντασιας και [εισελθοντων]{.greek-omitted} [εισελθων]{.greek-added} εις το ακροατηριον συν τε τοις [χιλι]{.greek-added} [χιλιαρχοις]{.greek-omitted} [αρχοις]{.greek-added} και ανδρασιν [[ανδρασι]{.corr}]{.greek-added} τοις κατ εξοχην [ουσιν]{.greek-omitted} της πολεως [ουσιν]{.greek-added} [[ουσι]{.corr}]{.greek-added} και κελευσαντος του φηστου ηχθη ο παυλος[25:23]{.aside}

και φησιν ο φηστος αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες θεωρειτε τουτον περι ου [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος των ιουδαιων [ενετυχον]{.greek-omitted} [ενετυχε]{.greek-added} μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν [αυτον]{.greek-added} ζην [αυτον]{.greek-omitted} μηκετι[25:24]{.aside}

εγω δε καταλαβομενος μηδεν αξιον θανατου αυτον πεπραχεναι και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα πεμπειν [αυτον]{.greek-omitted}[25:25]{.aside}

περι ου ασφαλες τι γραψαι τω [κυριω]{.greek-abbr} [μου]{.greek-added} ουκ εχω διο [και]{.greek-added} προηγαγον αυτον εφ υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως [επι]{.greek-added} [σου]{.greek-added} [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} σχω τι γραψαι[25:26]{.aside}

αλογον γαρ μοι δοκει πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη επιτρεπεται σοι [υπερ]{.greek-omitted} [περι]{.greek-added} σεαυτου λεγειν τοτε ο παυλος [απελογειτο]{.greek-omitted} εκτεινας την χειρα [απελογειτο]{.greek-added}[26:1]{.aside}

περι παντων ων εγκαλουμαι υπο ιουδαιων βασιλευ αγριππα ηγημαι εμαυτον μακαριον επι σου μελλων απολογεισθαι [σημερον]{.greek-omitted}[26:2]{.aside}

μαλιστα γνωστην οντα σε [παντων]{.greek-omitted} των κατα ιουδαιους [ηθων]{.greek-omitted} [εθων]{.greek-added} τε και ζητηματων διο δεομαι [σου]{.greek-omitted} μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ νεοτητος την απ αρχης γενομενην εν τω εθνει μου εν [τε]{.greek-added} ιεροσολυμοις ισασιν [[ισασι]{.corr}]{.greek-added} παντες οι ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν [θελωσιν]{.greek-omitted} [θελωσι]{.greek-added} μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας θρησκειας εζησα φαρισαιος[26:5]{.aside}

και νυν [δε]{.greek-added} επ ελπιδι της [προς]{.greek-omitted} [εις]{.greek-added} τους [πατερας]{.greek-abbr} [ημων]{.greek-added} επαγγελιας [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} υπο του [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν [εκτενεια]{.greek-omitted} [εκτενια]{.greek-added} [νυκτα]{.greek-omitted} [νυκταν]{.greek-added} και ημεραν [λατρευον]{.greek-omitted} [λατρευων]{.greek-added} ελπιζει καταντησαι περι ης ελπιδος εγκαλουμαι [υπο]{.greek-added} [ιουδαιων]{.greek-added} βασιλευ αγριππα [υπο]{.greek-omitted} [ιουδαιων]{.greek-omitted}[26:7]{.aside}

τι απιστον κρινεται παρ υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν [ουν]{.greek-omitted} εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησ[α]{.unclear} εν ιεροσολυμοις και πολλους των αγιων εγω [εν]{.greek-added} φυλακαις κατεκλεισα την παρα των αρχιερεων εξουσιαν λαβων [αναι]{.greek-added} [αναιρουμενων]{.greek-omitted} [ρουμενων]{.greek-added} τε αυτων κατηνεγκα ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν [περισσως]{.greek-omitted} [περισσοτερως]{.greek-added} τε εμμαινομενος αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις και πορευομενος εις [την]{.greek-omitted} δαμασκον μετ εξουσιας και επιτροπης της παρα των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον [ειδον]{.greek-omitted} [ιδον]{.greek-added} βασιλευ [αγριππα]{.greek-added} [ουρανοθεν]{.greek-abbr} υπερ την λαμπροτητα του ηλιου περιλαμψαν με φως και τους [συ]{.unclear}ν εμοι πορευομενους[26:13]{.aside}

παντων [δε]{.greek-omitted} [τε]{.greek-added} καταπεσοντων ημων εις την γην ηκουσα φωνην [λαλουσαν]{.greek-omitted} [λεγουσαν]{.greek-added} προς με [και]{.greek-omitted} [λεγουσαν]{.greek-omitted} τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σο[ι]{.unclear} προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε [ειπον]{.greek-omitted} [ειπα]{.greek-added} τις ει [κυριε]{.greek-abbr} ο δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [ιησους]{.greek-abbr} [ο]{.greek-added} [ναζωραιος]{.greek-added} ον συ διωκεις[26:15]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} αναστηθι και στηθι επι τους ποδας σου εις τουτο γαρ ωφθην σοι προχειρισασθαι σε υπηρετην και μαρτυρα ων τε [ειδες]{.greek-omitted} [ιδες]{.greek-added} [δυναμεων]{.greek-added} ων τε οφθησομαι σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου και [εκ]{.greek-added} των εθνων εις ους εγω [αποστελω]{.greek-added} σε [αποστελλω]{.greek-omitted}[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του [υποστρεψαι]{.greek-omitted} [επιστρεψαι]{.greek-added} απο σκοτους εις φως και [απο]{.greek-added} της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην απειθης τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον [τε]{.greek-added} και ιεροσολυμοις εις πασαν τε την χωραν της ιουδαιας και τοις εθνεσιν [απαγγελλων]{.greek-omitted} [απηγγελλον]{.greek-added} μετανοειν και επιστρεφειν επι τον [ζωντα]{.greek-added} [θεον]{.greek-abbr} αξια της μετανοιας εργα [πρασσοντας]{.greek-omitted} [πραττοντας]{.greek-added}[26:20]{.aside}

ενεκα τουτων [με]{.greek-added} οι ιουδαιοι [με]{.greek-omitted} συλλαβομενοι [οντα]{.greek-added} εν τω ιερω επειρωντο διαχειρισασθαι[26:21]{.aside}

επικουριας ουν τυχων της [παρα]{.greek-omitted} [απο]{.greek-added} του [θεου]{.greek-abbr} αχρι της ημερας τα[υ]{.unclear}της εστηκα [μαρτυρομενος]{.greek-omitted} [μαρτυρουμενος]{.greek-added} μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και μωυσης[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως [μελλει]{.greek-omitted} [μελλειν]{.greek-added} καταγγελλειν τω λαω και τοις εθνεσιν [[εθνεσι]{.corr}]{.greek-added}[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο φηστος μεγαλη τη φωνη [εφη]{.greek-omitted} [μαινη]{.greek-omitted} [φησιν]{.greek-added} [[φησι]{.corr}]{.greek-added} [μαινει]{.greek-added} παυλε τα πολλα σε γραμματα εις μανιαν περιτρεπει[26:24]{.aside}

ο δε [παυλος]{.greek-added} ου [μαι]{.greek-added} [μαινομαι]{.greek-omitted} [νομαι]{.greek-added} φησιν [[φησι]{.corr}]{.greek-added} κρατιστε [φηστε]{.greek-omitted} [φηστα]{.greek-added} αλλα αληθειας και σωφροσυνης ρηματα αποφθεγγομαι[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον [και]{.greek-omitted} παρρησιαζομενος λαλω λανθανειν γαρ αυτον τι τουτων ου πειθομαι [ουθεν]{.greek-added} [ουδεν]{.greek-omitted} [ουδε]{.greek-added} [ου]{.greek-omitted} γαρ εν γωνια [εστιν]{.greek-added} [[εστι]{.corr}]{.greek-added} πεπραγμενον τουτο[26:26]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

ο δε αγριππας προς τον παυλον εφη εν ολιγω με [πειθεις]{.greek-omitted} [πειθης]{.greek-added} χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος ειπεν [ευξαιμην]{.greek-omitted} [ευξαμην]{.greek-added} αν τω [θεω]{.greek-abbr} και εν [ολιγω]{.greek-omitted} [πολλω]{.greek-added} και εν [πολλω]{.greek-omitted} [ολιγω]{.greek-added} ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος καγω ειμι παρεκτος των δεσμων τουτων[26:29]{.aside}

[και]{.greek-omitted} ταυτα ειποντος αυτου ανεστη ο βασιλευς και ο ηγεμων η τε βερνικη και οι [συγκαθημενοι]{.greek-omitted} [συνκαθημενοι]{.greek-added} αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν θανατου [αξιον]{.greek-omitted} η δεσμων [αξιον]{.greek-added} [τι]{.greek-added} πρασσει ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω φηστω εφη απολελυσθαι [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} ο [ανθρωπος]{.greek-abbr} ουτος ει μη [επεκεκλητο]{.greek-omitted} [επικεκλητο]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την ιταλιαν παρεδιδουν τον τε παυλον και τινας ετερους δεσμ[ω]{.unclear}τας εκατονταρχη ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω αδραμυττηνω [μελλοντες]{.greek-omitted} [μελλοντα]{.greek-added} πλειν [εις]{.greek-added} τους κατα την ασιαν τοπους ανηχθημεν οντος συν ημιν αρισταρχου μακεδονος θεσσαλονικεως[27:2]{.aside}

τη [τε]{.greek-omitted} [δε]{.greek-added} ετερα κατηχθημεν εις σιδωνα [φιλανθρωπως]{.greek-omitted} [φιλανθρωπος]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} ο ιουλιος τω παυλω χρησαμενος επετρεψεν [[επετρεψε]{.corr}]{.greek-added} προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το [ειναι]{.greek-added} τους ανεμους [ειναι]{.greek-omitted} εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες [κατηλθομεν]{.greek-omitted} [ηλθομεν]{.greek-added} εις μυρα της λυκιας[27:5]{.aside}

[κακει]{.greek-omitted} [κακεισε]{.greek-added} ευρων ο εκατονταρχος πλοιον αλεξανδρινον πλεον εις την ιταλιαν [ενεβιβασεν]{.greek-omitted} [ανεβιβασεν]{.greek-added} ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις [βραδυπλοουντες]{.greek-omitted} [βραδυπλουντες]{.greek-added} και μολις γενομενοι κατα την κνιδον μη προσεωντος ημας του ανεμου υπεπλευσαμεν την [κρητην]{.greek-omitted} [κριτην]{.greek-added} κατα [σαλμωνην]{.greek-omitted} [σαλμονην]{.greek-added}[27:7]{.aside}

μολις τε παραλεγομενοι αυτην ηλθομεν εις τοπον τινα καλουμενον καλους λιμεν[α]{.unclear}ς ω εγγυς ην πολις λασαια[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος ηδη επισφαλους του πλοος δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των ψυχων ημων μελλειν εσεσθαι τον πλουν[27:10]{.aside}

ο δε εκατονταρχης τω [κυβερνητη]{.greek-omitted} [κυβερνιτη]{.greek-added} και τω ναυκληρω [μαλλον]{.greek-added} επειθετο [μαλλον]{.greek-omitted} η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι πλειους εθεντο βουλην αναχθηναι [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της [κρητης]{.greek-omitted} [κριτης]{.greek-added} βλεποντα κατα λιβα και κατα [χωρον]{.greek-omitted} [χωραν]{.greek-added}[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες [ασσον]{.greek-omitted} [ασον]{.greek-added} παρελεγοντο την κρητην[27:13]{.aside}

μετ ου πολυ δε εβαλεν [[εβαλε]{.corr}]{.greek-added} κατ αυτης ανεμος τυφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι υποδραμοντες καλουμενον [κλαυδην]{.greek-omitted} [κλαυδαν]{.greek-added} μολις ισχυσαμεν περικρατεις γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες βοηθειαις εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη [πως]{.greek-added} εις την συρτην [εκπεσωσιν]{.greek-omitted} [́εκπεσωσιν]{.greek-added} [[εκπεσωσι]{.corr}]{.greek-added} χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως [δε]{.greek-omitted} [τε]{.greek-added} χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη [ημερα]{.greek-added} αυτοχειρες την σκευην του πλοιου ερριψαμεν[27:19]{.aside}

μητε δε ηλιου μητε αστρων επιφαινοντων επι πλειονας ημερας χειμωνος τε ουκ ολιγου επικειμενου λοιπον περιηρειτο [ελπις]{.greek-added} πασα [ελπις]{.greek-omitted} του σωζεσθαι ημας[27:20]{.aside}

πολλης δε ασιτιας υπαρχουσης τοτε [σταθεις]{.greek-omitted} ο παυλος [σταθεις]{.greek-added} εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης κερδησαι τε την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης ουδεμια εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι αγγελος του [θεου]{.greek-abbr} ου ειμι ω και λατρευω[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα μεσον της νυκτος υπενοουν οι ναυται [προσαγειν]{.greek-omitted} [προαγειν]{.greek-added} τινα αυτοις χωραν[27:27]{.aside}

και [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας εικοσι βραχ[υ]{.unclear} δε διαστησαντες και παλιν [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι τε [μηπως]{.greek-omitted} [εις]{.greek-omitted} [μη]{.greek-added} [που]{.greek-added} [κατα]{.greek-added} [τραχεις]{.greek-omitted} [βραχεις]{.greek-added} τοπους εκπεσωμεν εκ πρυμνης ριψαντες αγκυρας [τεσσαρας]{.greek-omitted} [τεσσαρες]{.greek-added} [ηυχοντο]{.greek-omitted} [ευχοντο]{.greek-added} ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ πρωρας μελλοντων [εκτεινειν]{.greek-added} αγκυρας [εκτεινειν]{.greek-omitted}[27:30]{.aside}

ειπεν ο παυλος τω εκατονταρχη και τοις στρατιωταις εαν μη ουτοι μεινωσιν εν τω πλοιω υμεις σωθηναι ου δυνασθε[27:31]{.aside}

τοτε [αποκοψαντες]{.greek-added} οι στρατιωται [απεκοψαν]{.greek-omitted} τα σχοινια της σκαφης [και]{.greek-omitted} ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου ημελλεν ημερα γινεσθαι παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην [ημεραν]{.greek-added} σημερον [ημεραν]{.greek-omitted} προσδοκωντες ασιτοι [διατελειτε]{.greek-omitted} [διετελειτε]{.greek-added} μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας [προσλαβειν]{.greek-omitted} [μεταλαβειν]{.greek-added} [τροφης]{.greek-omitted} [τροφεις]{.greek-added} τουτο γαρ προς της υμετερας [σωτηριας]{.greek-omitted} [[σριας]{.greek-abbr}]{.greek-added} υπαρχει ουδενος γαρ υμων θριξ [εκ]{.greek-omitted} [απο]{.greek-added} της κεφαλης πεσειται[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον ευχαριστησεν [[ευχαριστησε]{.corr}]{.greek-added} τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

ημεν δε [αι]{.greek-added} [πασαι]{.greek-added} [ψυχαι]{.greek-added} εν τω πλοιω [αι]{.greek-omitted} [πασαι]{.greek-omitted} [ψυχαι]{.greek-omitted} διακοσιαι εβδομηκοντα εξ[27:37]{.aside}

κορεσθεντες δε [της]{.greek-omitted} τροφης εκουφιζον το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ [επεγινωσκον]{.greek-omitted} [εγινωσκον]{.greek-added} κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον [εβουλευσαντο]{.greek-omitted} [εβουλευοντο]{.greek-added} ει [δυνατον]{.greek-omitted} [δυναιντο]{.greek-added} εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των πηδαλιων και επαραντες τον [αρτεμονα]{.greek-omitted} [αρ]{.greek-added} [τεμωνα]{.greek-added} τη πνεουση [κατειχον]{.greek-omitted} [κατειχοντο]{.greek-added} εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον [επωκειλαν]{.greek-omitted} [επεκηλαν]{.greek-added} την ναυν και η μεν πρωρα ερεισασα εμεινεν ασαλευτος η δε πρυμνα ελυετο [υπο]{.greek-omitted} [απο]{.greek-added} της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας αποκτεινωσιν [[αποκτεινωσι]{.corr}]{.greek-added} μη τις εκκολυμβησας διαφυγη[27:42]{.aside}

ο δε [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του βουληματος εκελευσεν [[εκελευσε]{.corr}]{.greek-added} τε τους δυναμ[ε]{.unclear}νους κολυμβαν [απορριψαντας]{.greek-omitted} [αποριψαντας]{.greek-added} πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους μεν επι σανισιν ους δε επι τινων των [απο]{.greek-omitted} του πλοιου και ουτως εγενετο παντας διασωθηναι επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες τοτε επεγνωσαν οτι μελιτη η νησος καλει[τ]{.unclear}αι[28:1]{.aside}

οι [δε]{.greek-omitted} [τε]{.greek-added} βαρβαροι παρειχον ου την τυχουσαν [φιλανθρωπιαν]{.greek-abbr} ημιν αναψαντες γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον εφεστωτα και δια το ψυχος[28:2]{.aside}

συστρεψαντος δε του παυλου φρυγανων [τι]{.greek-added} πληθος και [επιθεντος]{.greek-omitted} [επιτιθεντος]{.greek-added} επι την πυραν εχιδνα [εκ]{.greek-omitted} [απο]{.greek-added} της θερμης [διεξελθουσα]{.greek-omitted} [εξελθουσα]{.greek-added} [καθηψεν]{.greek-omitted} [καθηψε]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε [ειδον]{.greek-omitted} [ιδον]{.greek-added} οι βαρβαροι κρεμαμενον το θηριον εκ της χειρος αυτου ελεγον προς αλληλους παντως φονευς εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν [αποτιναξας]{.greek-omitted} [αποτιναξαμενος]{.greek-added} το θηριον εις το πυρ επαθεν ουδεν κακον[28:5]{.aside}

οι δε [προσεδοκων]{.greek-omitted} [προσεδοκουν]{.greek-added} αυτον μελλειν πιμπρασθαι η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων [προσδοκωντων]{.greek-omitted} [προσδοκουντων]{.greek-added} και θεωρουντων μηδεν ατοπον εις αυτον γινομενον μεταβαλλομενοι ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6]{.aside}

εν δε τοις περι τον τοπον εκεινον υπηρχεν [[υπηρχε]{.corr}]{.greek-added} χωρια τω πρωτω της νησου ονοματι [ποπλιω]{.greek-omitted} [πουπλιω]{.greek-added} ος αναδεξαμενος ημας [ημερας]{.greek-added} τρεις [ημερας]{.greek-omitted} φιλοφρονως [εξενισεν]{.greek-omitted} [εξενησεν]{.greek-added}[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του [ποπλιου]{.greek-omitted} [πουπλιου]{.greek-added} πυρετοις και [δυσεντερια]{.greek-omitted} [δυσεντεριω]{.greek-added} συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις τας χειρας [αυτω]{.greek-omitted} [αυτου]{.greek-added} ιασατο αυτον[28:8]{.aside}

τουτου [ουν]{.greek-omitted} [δε]{.greek-added} γενομενου και οι λοιποι οι [εχοντες]{.greek-omitted} [ασθενειας]{.greek-omitted} εν τη νησω [εχοντες]{.greek-added} [ασθενειας]{.greek-added} προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρει[αν]{.greek-supplied}[28:10]{.aside}

μετα δε τρεις μηνας [ηχθημεν]{.greek-omitted} [ανηχθημεν]{.greek-added} εν πλοιω παρακεχειμακοτι εν τη νησω αλεξανδρινω [παρασημω]{.greek-omitted} [παρασιμω]{.greek-added} [διοσκουροις]{.greek-omitted} [διοσκοροις]{.greek-added}[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες [κατηντησαμεν]{.greek-omitted} [κατηντησωμεν]{.greek-added} εις ρηγιον και μετα μιαν ημεραν [επιγενομενου]{.greek-omitted} [επιγινομενου]{.greek-added} νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις επιμειναι ημερας επτα και ουτως [ηλθομεν]{.greek-added} εις [την]{.greek-omitted} ρωμην [ηλθομεν]{.greek-omitted}[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περι ημων [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} εις απαντησιν [ημιν]{.greek-omitted} [ημων]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} [αππιου]{.greek-omitted} [απφιου]{.greek-added} φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} ελαβεν θαρσος[28:15]{.aside}

οτε δε ηλθομεν εις ρωμην ο εκατονταρχος παρεδωκεν [[παρεδωκε]{.corr}]{.greek-added} τους δεσμιους τω στρατοπεδαρχη τω δε παυλω [επετραπη]{.greek-omitted} [επετραπει]{.greek-added} μενειν καθ εαυτον συν τω φυλασσοντι αυτον στρατιωτη[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων ελεγεν [[ελεγε]{.corr}]{.greek-added} προς αυτους ανδρες αδελφοι εγω ουδεν εναντιον ποιησας τω λαω η τοις εθεσιν [[εθεσι]{.corr}]{.greek-added} τοις πατρωοις δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με εβουλοντ[ο]{.unclear} [με]{.greek-added} απολυσαι δια το μηδεμιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου εχων τι [κατηγορησαι]{.greek-omitted} [κατηγορειν]{.greek-added}[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι ενεκεν [γαρ]{.greek-omitted} της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπ[ο]{.unclear}ν ημεις [ουτε]{.greek-omitted} [ουδε]{.greek-added} γραμματα [εδεξαμεθα]{.greek-added} περι σου [εδεξαμεθα]{.greek-omitted} απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν η ελαλησεν [[ελαλησε]{.corr}]{.greek-added} τι περι σου πονηρον[28:21]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι [μεν]{.greek-omitted} γαρ της αιρεσεως ταυτης γνωστον [ημιν]{.greek-added} εστιν [ημιν]{.greek-omitted} οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι [δε]{.greek-omitted} [τε]{.greek-added} αυτω ημεραν [ηλθον]{.greek-added} [ηκον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} εις την ξενιαν [προς]{.greek-added} [αυτον]{.greek-added} πλειονες οις εξετιθετο [διαμαρτυρομενος]{.greek-omitted} [διαμαρτυρωμενος]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους τα περι [της]{.greek-added} [βασιλειας]{.greek-added} του [ιησου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} απο τε του νομου μωυσεως και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφων[οι]{.unclear} δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον ελαλησεν [[ελαλησε]{.corr}]{.greek-added} δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added}[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και ειπον ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη [ιδητε]{.greek-omitted} [ειδητε]{.greek-added}[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε ιδωσιν [[ιδωσι]{.corr}]{.greek-added} τοις οφθαλμοις και τοις ωσιν ακουσωσιν [[ακουσωσι]{.corr}]{.greek-added} και τη καρδια [συν]{.unclear}[ωσιν]{.greek-supplied} και επιστρεψωσιν [[επιστρεψωσι]{.corr}]{.greek-added} και ιασομαι αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη [τουτο]{.greek-added} το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και τ[α]{.unclear}υτα αυτου ειποντος απηλθον οι ιουδαιοι [πολλην]{.greek-omitted} [[πο]{.greek-supplied}λην]{.greek-added} εχοντες εν [εαυτοις]{.greek-omitted} [αυτοις]{.greek-added} [συζητησιν]{.greek-omitted} [ζητησιν]{.greek-added}[28:29]{.aside}

εμεινεν [[εμεινε]{.corr}]{.greek-added} δε ο παυλος διετιαν ολην εν ιδιω μισθωμα[τ]{.unclear}ι και απεδεχετο παντας τους εισπορευομενο[υ]{.unclear}ς προς αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} [κ]{.unclear}αι διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα πασης παρρησιας ακωλυτως[28:31]{.aside}

