---
title: "Collation of Byz^RP^ vs 30131 (131)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 131 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30131).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 131                                   	| λογος                              	|
| 131 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 131 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 131               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 131                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 131 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 131                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

[ως]{.greek-omitted} [καθως]{.greek-added} γεγραπται εν [τοις]{.greek-omitted} [ησαια]{.greek-added} [τω]{.greek-added} [προφηταις]{.greek-omitted} [προφητη]{.greek-added} ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται και [εβαπτιζοντο]{.greek-omitted} [ευαπτιζοντο]{.greek-added} παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε [[ιω]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [ιωαννης]{.greek-omitted} ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερο[ς]{.unclear} μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν [εβαπτισα]{.greek-omitted} [ευαπτισα]{.greek-added} υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ιησους]{.greek-abbr} απ[ο]{.unclear} [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} της γαλιλαιας και [εβαπτισθη]{.greek-omitted} [ευαπτισ[θη]{.unclear}]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [ιορδανη]{.greek-added} υπο ιωαννου [εις]{.greek-omitted} [τον]{.greek-omitted} [ιορδανην]{.greek-omitted}[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [και]{.greek-added} ειδεν σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπ[η]{.unclear}τος εν [ω]{.greek-omitted} [σοι]{.greek-added} ευδοκησα[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει [επι]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν [[διεκονουν]{.corr}]{.greek-added} αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων [οτι]{.greek-omitted} πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν σιμωνα και ανδρεαν τον αδελφον αυτου [του]{.corr} σιμωνος [αμφιβληστρα]{.greek-added} βαλλοντας [αμφιβληστρον]{.greek-omitted} εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως [α]{.greek-added} [αφεντες]{.greek-omitted} [τα]{.greek-omitted} [δικτυα]{.greek-omitted} [αυτων]{.greek-omitted} [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted}[1:18]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [αφεντες]{.greek-omitted} [φεντες]{.greek-added} τα δικτυα [αυτων]{.greek-omitted} ηκολουθησαν αυτω[1:18 | instance no. 2]{.aside}

και προβας [εκειθεν]{.greek-omitted} ολιγον ειδεν ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων [απηλθον]{.greek-omitted} [απηλθων]{.greek-added} οπισω αυτου[1:20]{.aside}

και [εισπορευονται]{.greek-omitted} [εισπορευετε]{.greek-added} εις καπερναουμ και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και [ευθυς]{.greek-added} ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και [εθαμβηθησαν]{.greek-omitted} [εξεθαμβηθησαν]{.greek-added} παντες ωστε συζητειν προς εαυτους λεγοντας τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο [τις]{.greek-omitted} [η]{.greek-omitted} διδαχη [η]{.greek-omitted} καινη αυτη [οτι]{.greek-omitted} κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [[πνασι]{.greek-abbr}]{.greek-added} τοις ακαθαρτοις [επιτασσει]{.greek-omitted} [επιτασει]{.greek-added} και υπακουουσιν αυτω[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου [ευθυς]{.greek-omitted} εις ολην την περιχωρον [της]{.greek-omitted} γαλιλαιας[1:28]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} εκ της συναγωγης [εξελθοντες]{.greek-omitted} [εξελθων]{.greek-added} [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις την οικιαν σιμωνος και ανδρεου μετα [[ιω]{.greek-abbr}]{.greek-added} [και]{.greek-added} ιακωβου [και]{.greek-omitted} [ιωαννου]{.greek-omitted}[1:29]{.aside}

η δε πενθερα [του]{.greek-added} σιμωνος κατεκειτο [πυρεσσουσα]{.greek-omitted} [πυρεσουσα]{.greek-added} και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος [ευθεως]{.greek-omitted} και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως [εχωντας]{.greek-added} [εχοντας]{.corr} και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλλε]{.greek-added} και ουκ ηφιεν λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ιδεισαν]{.greek-added} αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι [εννυχον]{.greek-omitted} [εννυχα]{.greek-added} λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις ερημον τοπον [κα]{.greek-added} [κακει]{.greek-omitted} [προσηυχετο]{.greek-omitted}[1:35]{.aside}

[και]{.greek-omitted} [κατεδιωξαν]{.greek-omitted} [διωξαν]{.greek-added} αυτον ο [τε]{.greek-added} σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες [αυτω]{.greek-added} [αυτον]{.corr} λεγουσιν αυτω [οτι]{.greek-omitted} [οτε]{.greek-added} παντες σε ζητουσιν[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας [εχομενας]{.greek-omitted} [εχωμενας]{.greek-added} κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων αυτω οτι εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [[ιησους]{.greek-abbr}]{.greek-added} [σπλαγχνισθεις]{.greek-omitted} [σπλαγχνισθ[η]{.unclear}ς]{.greek-added} εκτεινας την χειρα ηψατο αυτου και λεγει [αυτω]{.greek-omitted} θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν ειπης [αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξαι]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν [οχλοι]{.greek-added} πολλοι ωστε μηκετι χωρειν [τα]{.greek-added} μηδε [τα]{.greek-omitted} προς την θυραν και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον [φεροντες]{.greek-added} παραλυτικον [φεροντες]{.greek-omitted} αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον [κραββατον]{.greek-omitted} [κραβατον]{.greek-added} εφ [ω]{.greek-omitted} [ο]{.greek-added} ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφαιωνται]{.greek-added} [σοι]{.greek-omitted} [σου]{.greek-added} αι αμαρτιαι [σου]{.greek-omitted}[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως λαλει [βασφημιας]{.greek-added} [βλασφημιας]{.corr} τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} [τω]{.greek-omitted} [το]{.greek-added} [πνευματι]{.greek-abbr} αυτου οτι ουτως [αυτοι]{.greek-omitted} διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} [ειπειν]{.greek-omitted} [τω]{.greek-omitted} [παραλυτικω]{.greek-omitted} [αφεωνται]{.greek-omitted} [σου]{.greek-omitted} [αι]{.greek-omitted} [αμαρτιαι]{.greek-omitted} [η]{.greek-omitted} [ειπειν]{.greek-omitted} [εγειραι]{.greek-omitted} [και]{.greek-omitted} [αρον]{.greek-omitted} [σου]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [και]{.greek-omitted} [περιπατει]{.greek-omitted}[2:9]{.aside}

[τι]{.greek-omitted} [εστιν]{.greek-omitted} [ευκοπωτερον]{.greek-omitted} ειπειν τω παραλυτικω αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν εγειραι [και]{.greek-omitted} αρον [τον]{.greek-added} [κραβατον]{.greek-added} [[κραβαττον]{.corr}]{.greek-added} σου [τον]{.greek-omitted} [κραββατον]{.greek-omitted} και περιπατει[2:9 | instance no. 2]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ιδητε]{.greek-added} οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} αφιεναι επι της γης αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

[σοι]{.greek-omitted} [συ]{.greek-added} [λεγει]{.greek-added} [λεγω]{.corr} εγειραι και [αρον]{.greek-omitted} [αρων]{.greek-added} τον [κραββατον]{.greek-omitted} [κραβατον]{.greek-added} σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον [κραββατον]{.greek-omitted} [κραβατον]{.greek-added} εξηλθεν [εναντιον]{.greek-omitted} [εναντιων]{.greek-added} παντων ωστε εξιστασθαι παντας και [δοξαζειν]{.greek-omitted} [δοξαζει]{.greek-added} τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added}[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθη]{.greek-added} [ακολουθει]{.corr} μοι και αναστας [ηκολουθησεν]{.greek-omitted} [ηκολουθει]{.greek-added} αυτω[2:14]{.aside}

και εγενετο εν [τω]{.greek-omitted} [το]{.greek-added} κατακεισθαι αυτον εν τη οικια αυτου [και]{.greek-omitted} πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει [αυτοις]{.greek-omitted} ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ [ηλθον]{.greek-omitted} [ηλθων]{.greek-added} καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} νηστευουσιν οι δε σοι μαθηται ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων εστιν νηστευειν οσον χρονον [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον [μετ]{.greek-added} [αυτων]{.greek-added} ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

[και]{.greek-omitted} ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω ει δε μη αιρει το πληρωμα [απ]{.greek-added} αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη [ρησσει]{.greek-omitted} [ρησει]{.greek-added} ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλ]{.greek-added} [αλλα]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [καινους]{.greek-omitted} [βλητεον]{.greek-omitted}[2:22]{.aside}

[λ]{.greek-added} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [βαλλει]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [παλαιους]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [ρησσει]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [ο]{.greek-omitted} [νεος]{.greek-omitted} [τους]{.greek-omitted} [ασκους]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [εκχειται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [απολουνται]{.greek-omitted} [αλλα]{.greek-omitted} οινον νεον εις ασκους καινους βλητεον[2:22 | instance no. 2]{.aside}

και εγενετο παραπορευεσθαι αυτον [εν]{.greek-omitted} τοις σαββασιν δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ελεγον αυτω ιδε τι ποιουσιν [εν]{.greek-omitted} [οι]{.greek-added} [μαθηταις]{.greek-added} [σου]{.greek-added} τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} τι [εποιησεν]{.greek-omitted} [εποιησαι]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχ[ε]{.unclear}]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} ε[πι]{.unclear} [α]{.unclear}βιαθαρ [του]{.greek-added} αρχιερε[ως]{.unclear} και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και εδωκεν και τοις [συν]{.greek-omitted} [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} ουσιν[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} [εγενετο]{.greek-omitted} [εκτισθη]{.greek-added} ουχ ο ανθρωπος δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και [παρετηρουν]{.greek-omitted} [παρετηρουντο]{.greek-added} αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τω [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις [τι]{.greek-added} [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η [αποκτειναι]{.greek-omitted} [απολεσαι]{.greek-added} οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και αποκατεσταθη η χειρ αυτου [υγιης]{.greek-omitted} ως η αλλη[3:5]{.aside}

και [εξελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ευθεως μετα των ηρ[ω]{.unclear}διανων συμβουλιον εποιουν κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρισε]{.greek-added} μετα των μαθητων αυτου [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν και [πολυ]{.greek-omitted} [πολλ[υ]{.unclear}]{.greek-added} πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [ηκολουθησεν]{.greek-added} αυτω [και]{.greek-added} [απο]{.greek-added} [ιεροσολυμων]{.greek-added} και απο της ιουδαιας[3:7]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} και περαν του ιορδανου και οι περι τυρον και [σιδωνα]{.greek-omitted} [σιδονα]{.greek-added} πληθος πολυ [ακουσαντες]{.greek-omitted} [ακουοντες]{.greek-added} οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω [δια]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [θλιβωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[3:9]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [πλοιαριον]{.greek-omitted} [προσκαρτερη]{.greek-omitted} [αυτω]{.greek-omitted} δια τον οχλον ινα μη θλιβωσιν αυτον[3:9 | instance no. 2]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα οταν αυτον εθεωρει προσεπιπτεν αυτω και [εκραζεν]{.greek-omitted} [εκραζε]{.greek-added} λεγοντα οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη [αυτον]{.greek-added} φανερον [αυτον]{.greek-omitted} ποιησωσιν[3:12]{.aside}

και [αναβαινει]{.greek-omitted} [ανευη]{.greek-added} εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [του]{.greek-omitted} ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι [βροντοις]{.greek-added} [βροντης]{.corr}[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

και [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} [και]{.greek-added} [συνερχεται]{.greek-omitted} [συνερχονται]{.greek-added} παλιν οχλος [πολυς]{.greek-added} ωστε μη δυνασθαι αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και [προσκαλεσαμενος]{.greek-omitted} [προσκαλεσαμενους]{.greek-added} αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

[αλλ]{.greek-added} ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted} τοις υιοις [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [και]{.greek-omitted} [βλασφημιαι]{.greek-omitted} [οσας]{.greek-omitted} [αν]{.greek-omitted} [βλασφημησωσιν]{.greek-omitted}[3:28]{.aside}

[των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [παντα]{.greek-omitted} [αφεθησεται]{.greek-omitted} τα αμαρτηματα [τοις]{.greek-omitted} [υιοις]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} και βλασφημιαι οσας αν [βλασφημησωσιν]{.greek-omitted} [βλασφημισωσιν]{.greek-added}[3:28 | instance no. 2]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημισει]{.greek-added} εις το [πνευμα]{.greek-abbr} [τ]{.unclear}ο αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος [εστιν]{.greek-omitted} [εστι]{.greek-added} αιωνιου κρισεως[3:29]{.aside}

[οτι]{.greek-omitted} [οτε]{.greek-added} ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

[ερχονται]{.greek-omitted} [ουν]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} και [εξερχεται]{.greek-added} η [μητηρ]{.greek-abbr} αυτου και [οι]{.greek-added} [αδελφοι]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} εξω [εστωτες]{.greek-omitted} [εστηκοτες]{.greek-added} απεστειλαν προς αυτον [φωνουντες]{.greek-omitted} [καλουντες]{.greek-added} αυτον[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

[και]{.greek-omitted} απεκριθη αυτοις [λεγων]{.greek-omitted} [και]{.greek-added} [λεγει]{.greek-added} τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω [τους]{.greek-omitted} περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη [μου]{.greek-omitted} και [μητηρ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και [συνηχθη]{.greek-omitted} [συνερχονται]{.greek-added} προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις [το]{.greek-omitted} πλοιον καθησθαι εν τη θαλασση και πας ο οχλος [προς]{.greek-omitted} [παρα]{.greek-added} την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις [πολλα]{.greek-omitted} [πολλω]{.greek-added} και [ε]{.unclear}λεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν [τω]{.greek-omitted} [το]{.greek-added} σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι [το]{.greek-omitted} [τα]{.greek-added} [πετρωδες]{.greek-omitted} [πετρωδη]{.greek-added} οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εβλαστησε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν [αι]{.greek-omitted} [οι]{.greek-added} ακανθαι και συνεπνιξαν αυτο και καρπον ουκ εδωκεν[4:7]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} [εξηκοντα]{.greek-omitted} [εξικοντα]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν [δεδωται]{.greek-added} [δεδοται]{.corr} γνωναι [το]{.greek-omitted} [τα]{.greek-added} [μυστηριον]{.greek-omitted} [μυστηρια]{.greek-added} της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και [μη]{.greek-omitted} [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [μηποτε]{.greek-omitted} [επιστρεψωσιν]{.greek-omitted} [και]{.greek-omitted} [αφεθη]{.greek-omitted} [αυτοις]{.greek-omitted} [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted}[4:12]{.aside}

[ινα]{.greek-omitted} [βλεποντες]{.greek-omitted} [βλεπωσιν]{.greek-omitted} [μη]{.greek-added} [ιδωσι]{.greek-added} [και]{.greek-added} [ακουοντες]{.greek-added} [ακουωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12 | instance no. 2]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν [ομοιως]{.greek-omitted} οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας [δεχονται]{.greek-added} [λαμβανουσιν]{.greek-omitted} [αυτον]{.greek-omitted}[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου [και]{.greek-omitted} [αι]{.greek-omitted} [περι]{.greek-omitted} [τα]{.greek-omitted} [λοιπα]{.greek-omitted} [επιθυμιαι]{.greek-omitted} [εισπορευομεναι]{.greek-omitted} [εισπορευομενα]{.greek-added} [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις μητι [ερχεται]{.greek-added} ο λυχνος [ερχεται]{.greek-omitted} ινα υπο τον μοδιον τεθη η [ινα]{.greek-added} υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον [ει]{.greek-added} [ο]{.greek-omitted} [εαν]{.greek-omitted} μη [ινα]{.greek-added} φανερωθη ουδε εγενετο αποκρυφον [αλλ]{.greek-omitted} [ει]{.greek-added} [μη]{.greek-added} ινα εις φανερον ελθη[4:22]{.aside}

[ει]{.greek-omitted} [η]{.greek-added} τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε μετρηθησεται υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ αν [εχη]{.greek-omitted} [εχει]{.greek-added} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτ[ω]{.unclear}ς εστιν η βασιλεια του [θεου]{.greek-abbr} ως [εαν]{.greek-omitted} [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [οταν]{.greek-added} [βαλει]{.greek-added} [[βαλλει]{.corr}]{.greek-added} τον σπορον επι [της]{.greek-omitted} [γης]{.greek-omitted} [την]{.greek-added} [γην]{.greek-added}[4:26]{.aside}

και [καθευδη]{.greek-omitted} [καθευδει]{.greek-added} και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και μηκυνηται ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν [ειτα]{.greek-omitted} [πληρη]{.greek-omitted} [σιτον]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σταχυι]{.greek-omitted}[4:28]{.aside}

[αυτοματη]{.greek-omitted} [γαρ]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [καρποφορει]{.greek-omitted} [πρωτον]{.greek-omitted} [χορτον]{.greek-omitted} [ειτα]{.greek-omitted} [σταχυν]{.greek-omitted} ειτα πληρη σιτον εν τω σταχυι[4:28 | instance no. 2]{.aside}

οταν δε παραδω ο καρπος [ευθεως]{.greek-omitted} [τοτε]{.greek-added} [αποστελει]{.greek-added} [αποστελλει]{.corr} το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν [ποια]{.greek-omitted} [παραβολη]{.greek-omitted} [τινι]{.greek-added} [ομοιωματι]{.greek-added} [παραβαλωμεν]{.greek-omitted} [παραβαλλωμεν]{.greek-added} αυτην[4:30]{.aside}

ως κοκκον σιναπεως ος οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} επι της γης [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται [μειζων]{.greek-added} παντων των λαχανων [μειζων]{.greek-omitted} και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} [κατασκηνουν]{.greek-omitted} [κατασκινουν]{.greek-added}[4:32]{.aside}

και τοιαυταις παραβολαις [πολλαις]{.greek-omitted} ελαλει αυτοις τον λογον καθως εδυναντο ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε [τοις]{.greek-omitted} [οις]{.greek-added} μαθηταις αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και [τα]{.greek-added} αλλα [τα]{.greek-added} [οντα]{.greek-added} [δε]{.greek-omitted} [πλοιαρια]{.greek-omitted} [ην]{.greek-omitted} μετ αυτου [πλοια]{.greek-added}[4:36]{.aside}

και γινεται λαιλαψ [μεγαλη]{.greek-added} ανεμου [μεγαλη]{.greek-omitted} [και]{.greek-added} τα [δε]{.greek-omitted} κυματα επεβαλλεν εις το πλοιον ωστε αυτο ηδη [γεμιζεσθαι]{.greek-omitted} [βυθιζεσθαι]{.greek-added}[4:37]{.aside}

και ην αυτος [επι]{.greek-omitted} [εν]{.greek-added} τη πρυμνη επι [το]{.greek-omitted} [προσκεφαλαιον]{.greek-omitted} [προσκεφαλαιου]{.greek-added} καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} τη θαλασση [και]{.greek-added} [ειπεν]{.greek-added} σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι [ουτως]{.greek-added} δειλοι [εσται]{.greek-added} [εστε]{.corr} [ουπω]{.greek-added} [ουτως]{.greek-omitted} [πως]{.greek-omitted} [ουκ]{.greek-omitted} εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και [ο]{.greek-omitted} [οι]{.greek-added} [ανεμος]{.greek-omitted} [ανεμοι]{.greek-added} και η θαλασσα [υπακουουσιν]{.greek-omitted} αυτω [υπακουει]{.greek-added}[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γεργεσηνων]{.greek-added}[5:1]{.aside}

και [εξελθοντι]{.greek-omitted} [εξελθοντος]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} εκ του πλοιου ευθεως [απηντησεν]{.greek-omitted} [υπηνησεν]{.greek-added} αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις [ετι]{.greek-added} εδυνατο αυτον δησαι[5:3]{.aside}

δια το αυτον [πολλακις]{.greek-omitted} [πολλας]{.greek-added} [πεδαις]{.greek-omitted} [πεδας]{.greek-added} και [αλυσεσιν]{.greek-omitted} [αλυσεις]{.greek-added} [δεδεσθαι]{.greek-omitted} [αις]{.greek-added} [εδησαν]{.greek-added} [αυτον]{.greek-added} [διεσπακεναι]{.greek-added} και [διεσπασθαι]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} [τας]{.greek-omitted} [αλυσεις]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [πεδας]{.greek-omitted} [συντετριφθαι]{.greek-omitted} [συντετριφεναι]{.greek-added} και ουδεις [ισχυσεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και [ημερας]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ορεσιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [μνημασιν]{.greek-omitted} [ην]{.greek-omitted} [κραζων]{.greek-omitted} [και]{.greek-omitted} [κατακοπτων]{.greek-omitted} [εαυτον]{.greek-omitted} [λιθοις]{.greek-omitted}[5:5]{.aside}

[και]{.greek-omitted} [δια]{.greek-omitted} [παντος]{.greek-omitted} [νυκτος]{.greek-omitted} [και]{.greek-omitted} ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημειοις]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5 | instance no. 2]{.aside}

[και]{.greek-added} ιδων [δε]{.greek-omitted} τον [ιησουν]{.greek-abbr} απο μακροθεν εδραμεν και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με [βασανισης]{.greek-omitted} [βασανισεις]{.greek-added}[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι [ονομα]{.greek-added} σοι [ονομα]{.greek-omitted} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον πολλα ινα μη [αυτους]{.greek-omitted} [αποστειλη]{.greek-omitted} εξω της χωρας [αυτους]{.greek-added} [αποστειλλη]{.greek-added}[5:10]{.aside}

ην δε εκει [αγελη]{.greek-added} [χοιρων]{.greek-added} προς τω ορει [αγελη]{.greek-omitted} [χοιρων]{.greek-omitted} [μεγαλη]{.greek-omitted} βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον [παντες]{.greek-omitted} [οι]{.greek-omitted} [δαιμονες]{.greek-omitted} λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} και εξελθοντα τα [πνευματα]{.greek-abbr} τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

[και]{.greek-added} οι [δε]{.greek-omitted} βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον [και]{.greek-omitted} ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως [εγενετο]{.greek-omitted} [τω]{.greek-omitted} [δαιμονιζομενω]{.greek-omitted} [εσωθη]{.greek-added} [ο]{.greek-added} [δαιμονισθεις]{.greek-added} και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} μετ αυτου [η]{.greek-added}[5:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και [αναγγειλον]{.greek-omitted} [διαγγειλον]{.greek-added} αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [εποιησε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησαι]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες [εθαυμαζων]{.greek-added} [εθαυμαζον]{.corr}[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} παλιν εις το περαν συνηχθη οχλος πολυς [επ]{.greek-omitted} [μετ]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει [αυτου]{.greek-added} προς τους ποδας [αυτου]{.greek-omitted}[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως [ε]{.greek-added} [εχει]{.greek-omitted} [ινα]{.greek-omitted} [ελθων]{.greek-omitted} [επιθης]{.greek-omitted} [αυτη]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [οπως]{.greek-omitted} [σωθη]{.greek-omitted} [και]{.greek-omitted} [ζησεται]{.greek-omitted}[5:23]{.aside}

[και]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [πολλα]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [μου]{.greek-omitted} [εσχατως]{.greek-omitted} [εχει]{.greek-omitted} [χει]{.greek-added} ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} [αυτη]{.greek-omitted} τας χειρας [αυτη]{.greek-added} οπως σωθη και ζησεται[5:23 | instance no. 2]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος [δωδεκα]{.greek-added} ετη [δωδεκα]{.greek-omitted}[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα [παρ]{.greek-omitted} [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι καν των ιματιων αυτου αψωμαι [σωθησομαι]{.greek-omitted} [σωθησωμαι]{.greek-added}[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η [πιστις]{.greek-omitted} [πιστι]{.greek-added} σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλεις]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} [ακουσας]{.greek-added} ευθεως [ακουσας]{.greek-omitted} τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω συνακολουθησαι ει μη πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον κλαιοντας και [αλαλαζοντας]{.greek-omitted} [αλλαλαζοντας]{.greek-added} πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και [κλαιετε]{.greek-omitted} [κλαιεται]{.greek-added} το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω εγειραι[5:41]{.aside}

και ευθεως [ανε]{.greek-added} [ανεστη]{.greek-omitted} [το]{.greek-omitted} [κορασιον]{.greek-omitted} [και]{.greek-omitted} [περιεπατει]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [ετων]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [εξεστησαν]{.greek-omitted} [εκστασει]{.greek-omitted} [μεγαλη]{.greek-omitted}[5:42]{.aside}

[στη]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [ανεστη]{.greek-omitted} το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν [εκστασει]{.greek-omitted} [εκσταση]{.greek-added} μεγαλη[5:42 | instance no. 2]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και ειπεν δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν [και]{.greek-omitted} [ηλθεν]{.greek-omitted} εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η σοφια η δοθεισα αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο [τεκτων]{.greek-omitted} [τεκτον]{.greek-added} ο [υιος]{.greek-abbr} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [πατριδι]{.greek-omitted} [πατριδη]{.greek-added} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας εθεραπευσεν[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και [προσκαλειται]{.greek-omitted} [προσκαληται]{.greek-added} τους δωδεκα και ηρξατο αυτους [αποστελλειν]{.greek-omitted} [αποστελειν]{.greek-added} δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη [ραβδον]{.greek-omitted} [ραυδον]{.greek-added} μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μ[η]{.unclear} ενδυσησθε δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει [μενετε]{.greek-omitted} [μενεται]{.greek-added} εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι αν [[ος]{.corr}]{.greek-added} [[εαν]{.corr}]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι [εκειθεν]{.greek-omitted} [εκει]{.greek-added} [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η [γομορροις]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} τη πολει εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [ελεγον]{.greek-omitted} [οτι]{.greek-omitted} [ηλιας]{.greek-omitted} [εστιν]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} ιωαννην ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο ιωαννης τω ηρωδη [οτι]{.greek-omitted} ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν [την]{.greek-omitted} γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν [αυτου]{.greek-omitted} και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [αιτησης]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted} εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε ειπεν την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης [προς]{.greek-omitted} [εις]{.greek-added} τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε [και]{.greek-added} υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} [ολιγον]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [ολι]{.greek-added} [ερχομενοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [υπαγοντες]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ουδε]{.greek-omitted} [φαγειν]{.greek-omitted} [ευκαιρουν]{.greek-omitted}[6:31]{.aside}

[γον]{.greek-added} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [δευτε]{.greek-omitted} [υμεις]{.greek-omitted} [αυτοι]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [εις]{.greek-omitted} [ερημον]{.greek-omitted} [τοπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [ολιγον]{.greek-omitted} ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31 | instance no. 2]{.aside}

και [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} εις ερημον τοπον [εν]{.greek-added} τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} πολλοι και [πεζη]{.greek-omitted} [πεζοι]{.greek-added} απο πασων των πολεων [συνεδραμον]{.greek-omitted} [συνεδραμων]{.greek-added} εκει και [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων ειδεν ο [ιησους]{.greek-abbr} πολυν οχλον και εσπλαγχνισθη επ [αυτοις]{.greek-omitted} [αυτους]{.greek-added} οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται αυτου λεγουσιν οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας [αγορασωσιν]{.greek-omitted} [αγωρασωσιν]{.greek-added} εαυτοις αρτους τι γαρ [φαγωσιν]{.greek-omitted} [φαγουσιν]{.greek-added} ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε [αυτοις]{.greek-omitted} [αυτους]{.greek-added} υμεις φαγειν και λεγουσιν αυτω απελθοντες [αγωρασωμεν]{.greek-added} [αγορασωμεν]{.corr} δηναριων διακοσιων αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και γνοντες λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακλιθηναι]{.greek-added} παντας συμποσια συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βησθαιδαν]{.greek-added} εως αυτος απολυση τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος [ην]{.greek-added} επι [της]{.greek-omitted} [γης]{.greek-omitted} [την]{.greek-added} [γην]{.greek-added}[6:47]{.aside}

και ειδεν αυτους [βασα]{.greek-added} [βασανιζομενους]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ελαυνειν]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [εναντιος]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [περι]{.greek-omitted} [τεταρτην]{.greek-omitted} [φυλακην]{.greek-omitted} [της]{.greek-omitted} [νυκτος]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [περιπατων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

[και]{.greek-omitted} [ειδεν]{.greek-omitted} [αυτους]{.greek-omitted} [βασανιζομενους]{.greek-omitted} [νιζομενους]{.greek-added} εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην [φυλακην]{.greek-omitted} [φυλακιν]{.greek-added} της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48 | instance no. 2]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και [ανεκραξαν]{.greek-omitted} [εκραξαν]{.greek-added}[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [περισου]{.greek-added} [εκπερισσου]{.greek-omitted} [[περισσου]{.corr}]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι [τοις]{.greek-omitted} [τους]{.greek-added} [αρτοις]{.greek-omitted} [αρτους]{.greek-added} ην γαρ αυτων η καρδια [πεπωρωμενη]{.greek-omitted} [πεπορωμενη]{.greek-added}[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην γεννησαρετ και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις χερσιν τουτ εστιν ανιπτοις εσθιοντας [αρτους]{.greek-omitted} [αρτον]{.greek-added} εμεμψαντο[7:2]{.aside}

οι γαρ [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την [παραδ[ω]{.unclear}σιν]{.greek-added} [παραδοσιν]{.corr} των πρεσβυτερων[7:3]{.aside}

και απο [αγωρας]{.greek-added} [αγορας]{.corr} εαν μη βαπτισωνται ουκ εσθιουσιν και αλλα πολλα [εστιν]{.greek-omitted} [εισιν]{.greek-added} α [παρελαβων]{.greek-added} [παρελαβον]{.corr} κρατειν [βαπτισμους]{.greek-added} [ποτηριων]{.greek-added} βαπτισμους ποτηριων και ξεστων και [χαλκιων]{.greek-omitted} [χαλκειων]{.greek-added} και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και [οι]{.greek-omitted} γραμματεις δια τι οι [μαθηται]{.greek-omitted} [μαθηταις]{.greek-added} σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την [παραδ[ω]{.unclear}σι[ν]{.unclear}]{.greek-added} [παραδοσι[ν]{.unclear}]{.corr} των πρεσβυτερων αλλα ανιπτοις χερσιν εσθιουσιν τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις [οτι]{.greek-omitted} [καλως]{.greek-omitted} [προεφητευσεν]{.greek-omitted} [ησαιας]{.greek-omitted} [περι]{.greek-omitted} [υμων]{.greek-omitted} [των]{.greek-omitted} [υποκριτων]{.greek-omitted} [ως]{.greek-omitted} [γεγραπται]{.greek-omitted} [ουτος]{.greek-omitted} [ο]{.greek-omitted} [λαος]{.greek-omitted} [τοις]{.greek-omitted} [χειλεσιν]{.greek-omitted} [με]{.greek-omitted} [τιμα]{.greek-omitted} [η]{.greek-omitted} [δε]{.greek-omitted} [καρδια]{.greek-omitted} [αυτων]{.greek-omitted} [πορρω]{.greek-omitted} [απεχει]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted}[7:6]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6 | instance no. 2]{.aside}

ματην δε [σεβονται]{.greek-omitted} [σευονται]{.greek-added} με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια [πολλα]{.greek-added} τοιαυτα [πολλα]{.greek-omitted} [ποιηται]{.greek-added} [ποιειτε]{.greek-omitted} [[ποιειται]{.corr}]{.greek-added}[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω [τελευτατω]{.greek-omitted} [τετλευτατω]{.greek-added}[7:10]{.aside}

υμεις δε λεγετε εαν [ειπη]{.greek-omitted} [ειπει]{.greek-added} [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η [παρεδωκατε]{.greek-omitted} [παρεδοκατε]{.greek-added} και παρομοια [πολλα]{.greek-added} τοιαυτα [πολλα]{.greek-omitted} [ποιητε]{.greek-added} [ποιειτε]{.corr}[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε [εισηλθεν]{.greek-omitted} [εισηλθον]{.greek-added} εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως [και]{.greek-omitted} υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα [εκπορευεται]{.greek-omitted} [εκπορευετε]{.greek-added} καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος ασελγεια οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

[ακουσασα]{.greek-omitted} [ακουσας]{.greek-added} γαρ γυνη [πε]{.greek-added} [περι]{.greek-omitted} [αυτου]{.greek-omitted} [ης]{.greek-omitted} [ειχεν]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [αυτης]{.greek-omitted} [πνευμα]{.greek-omitted} [ακαθαρτον]{.greek-omitted} [ελθουσα]{.greek-omitted} [προσεπεσεν]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted}[7:25]{.aside}

[ρι]{.greek-added} [ακουσασα]{.greek-omitted} [γαρ]{.greek-omitted} [γυνη]{.greek-omitted} [περι]{.greek-omitted} αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25 | instance no. 2]{.aside}

ην δε η γυνη ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισα]{.greek-added} [τω]{.greek-omitted} [το]{.greek-added} γενει και ηρωτα αυτον ινα το δαιμονιον [εκβαλλει]{.greek-added} [εκβαλη]{.greek-omitted} [εκ]{.greek-omitted} της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και [βαλειν]{.greek-omitted} [βαλλειν]{.greek-added} τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον [εκ]{.greek-omitted} [απο]{.greek-added} της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και [παρακαλουσιν]{.greek-omitted} [παρακαλ[―]{.gap}σιν]{.greek-added} αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και [απολαβομενος]{.greek-omitted} [επιλαβομενος]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added} απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως δι[η]{.unclear}νοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε αυτος [αυτοις]{.greek-omitted} διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και [υπερπερισσως]{.greek-omitted} [υπερπερισσος]{.greek-added} εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παμπολλου]{.greek-omitted} [πανπολλου]{.greek-added} οχλου οντος και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος ο [ιησους]{.greek-abbr} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον [οτι]{.greek-omitted} [ηδη]{.greek-omitted} [ημεραι]{.greek-omitted} [τρεις]{.greek-omitted} [προσμενουσιν]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted}[8:2]{.aside}

[σπλαγχνιζομαι]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2 | instance no. 2]{.aside}

και εαν απολυσω αυτους νηστεις εις οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκουσι]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε [επ]{.greek-added} [ερημιας]{.greek-added} χορτασαι αρτων [επ]{.greek-omitted} [ερημιας]{.greek-omitted}[8:4]{.aside}

και επηρωτα αυτους ποσους [αρτους]{.greek-added} εχετε [αρτους]{.greek-omitted} οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθηναι]{.greek-added} [παραθειναι]{.corr} και αυτα[8:7]{.aside}

[εφαγων]{.greek-added} [εφαγον]{.corr} δε και εχορτασθησαν και ηραν [περισσευματα]{.greek-omitted} [περισευματα]{.greek-added} κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και ευθεως εμβας εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη [δαλμανουθα]{.greek-omitted} [δαλμανοσθα]{.greek-added}[8:10]{.aside}

και εξηλθον οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και [διεστελλετο]{.greek-omitted} [διεστειλατο]{.greek-added} αυτοις [λεγων]{.greek-omitted} [λεγον]{.greek-added} ορατε βλεπετε απο της ζυμης των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς [αληλους]{.greek-added} [αλληλους]{.corr} λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους [πληρεις]{.greek-omitted} κλασματων [πλη]{.greek-added} [ηρατε]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δωδεκα]{.greek-omitted}[8:19]{.aside}

[ρης]{.greek-added} [οτε]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [εκλασα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [πεντακισχιλιους]{.greek-omitted} [ποσους]{.greek-omitted} [κοφινους]{.greek-omitted} [πληρεις]{.greek-omitted} [κλασματων]{.greek-omitted} ηρατε λεγουσιν αυτω δωδεκα[8:19 | instance no. 2]{.aside}

οτε δε [τους]{.greek-omitted} [επτα]{.greek-omitted} εις τους τετρακισχιλιους [τους]{.greek-added} [επτα]{.greek-added} ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως ου [[ουπω]{.corr}]{.greek-added} συνιετε[8:21]{.aside}

και ερχεται εις βηθσαιδαν και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα [αψηται]{.greek-added} αυτου [αψηται]{.greek-omitted}[8:22]{.aside}

και επιλαβομενος της χειρος [αυτου]{.greek-added} του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-omitted} [[ουρανους]{.greek-abbr}]{.greek-added} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και αποκατεσταθη και [ενεβλεψεν]{.greek-omitted} [ανεβλεψαι]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι [αποκριθ[ι]{.unclear}ς]{.greek-added} [αποκριθεις]{.corr} δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και των αρχιερεων και των γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

[και]{.greek-omitted} [παρρησια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ελαλει]{.greek-omitted} και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[8:34]{.aside}

ος γαρ αν [θελη]{.greek-omitted} [θελει]{.greek-added} την ψυχην αυτου σωσαι [απολεσει]{.greek-omitted} [αυτην]{.greek-omitted} [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [απολεση]{.greek-omitted} [απολε]{.greek-added} [την]{.greek-omitted} [εαυτου]{.greek-omitted} [ψυχην]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted} [ουτος]{.greek-omitted} [σωσει]{.greek-omitted} [αυτην]{.greek-omitted}[8:35]{.aside}

[σει]{.greek-added} [ος]{.greek-omitted} [γαρ]{.greek-omitted} [αν]{.greek-omitted} [θελη]{.greek-omitted} [την]{.greek-omitted} [ψυχην]{.greek-omitted} [αυτου]{.greek-omitted} [σωσαι]{.greek-omitted} [απολεσει]{.greek-omitted} αυτην ος δ αν απολεση την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου ουτος σωσει αυτην[8:35 | instance no. 2]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} εαν κερδηση τον κοσμον ολον και [ζημιωθη]{.greek-omitted} [ζημειωθη]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} [επεσχυθη]{.greek-added} [επαισχυνθη]{.corr} με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη [του]{.greek-omitted} [πατρος]{.greek-omitted} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν [οτι]{.greek-omitted} [εισιν]{.greek-omitted} [ει[σι]{.unclear}]{.greek-added} τινες των ωδε εστηκο[τ]{.unclear}[ω]{.greek-supplied}ν οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θαν[ατο]{.unclear}υ εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βα[σι]{.unclear}λειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και [ιωαννην]{.greek-omitted} [τον]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν ως χιων οια γναφευς επι της γης ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν μωση και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και μωση μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα αυτοις και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} [διηγησονται]{.greek-added} α ειδον ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [εληλυ]{.greek-added} [και]{.greek-omitted} [εποιησαν]{.greek-omitted} [αυτω]{.greek-omitted} [οσα]{.greek-omitted} [ηθελησαν]{.greek-omitted} [καθως]{.greek-omitted} [γεγραπται]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted}[9:13]{.aside}

[θεν]{.greek-added} [αλλα]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [ηλιας]{.greek-omitted} [εληλυθεν]{.greek-omitted} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13 | instance no. 2]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις συζητουντας [αυτοις]{.greek-omitted} [αυτους]{.greek-added}[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και [ξηραινεται]{.greek-omitted} [ξηρενεται]{.greek-added} και ειπον τοις μαθηταις σου ινα [αυτο]{.greek-omitted} [αυτω]{.greek-added} [εκβαλωσιν]{.greek-omitted} [εκβαλλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτε προς υμας [εσομαι]{.greek-omitted} [εσωμαι]{.greek-added} εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης [εκυλιετο]{.greek-omitted} [εκυληετο]{.greek-added} αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις το πυρ [εβαλεν]{.greek-omitted} [εβαλλε]{.greek-added} και εις υδατα ινα [απολεση]{.greek-omitted} [απολεσει]{.greek-added} αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [το]{.greek-omitted} ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [βοηθ[η]{.unclear}]{.greek-added} μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [συντρεχει]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το πνευμα το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι [εισελθης]{.greek-omitted} [εισελθεις]{.greek-added} εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν οτι [δια]{.greek-added} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις [τουτο]{.greek-omitted} [το]{.greek-omitted} [του]{.greek-added} [γενος]{.greek-omitted} [εν]{.greek-omitted} [ουδενι]{.greek-omitted} [δυναται]{.greek-omitted} [εξελθειν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εν]{.greek-omitted} [προσευχη]{.greek-omitted} [και]{.greek-omitted} [νηστεια]{.greek-omitted}[9:29]{.aside}

[το]{.greek-added} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τουτο]{.greek-omitted} το γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29 | instance no. 2]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα [αναστησεται]{.greek-omitted} [αναστησετε]{.greek-added}[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους [διελογιζεσθαι]{.greek-added} [διελογιζεσθε]{.corr}[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου εμε [δεχεται]{.greek-omitted} [δεχετε]{.greek-added} και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε αυτω ιωαννης λεγων διδασκαλε ειδομεν τινα [τω]{.greek-omitted} [επι]{.greek-added} [το]{.greek-added} ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καθ υμων υπερ υμων [εστιν]{.greek-omitted} [εστι]{.greek-added}[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτηση]{.greek-added} υμας ποτηριον υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων εις εμε [καλον]{.greek-omitted} [καλλον]{.greek-added} εστιν αυτω μαλλον ει [περικειτε]{.greek-added} [περικειται]{.corr} λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι εστιν [[εστι]{.corr}]{.greek-added} [κυλον]{.greek-added} [κυλλον]{.corr} εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} σοι εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας δια του περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} [επηρωτησαν]{.greek-omitted} [επερωτησαν]{.greek-added} αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο μωσης[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [επετρεψεν]{.greek-omitted} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται [προς]{.greek-omitted} [την]{.greek-omitted} [τη]{.greek-added} [γυναικα]{.greek-omitted} [γυναικι]{.greek-added} [αυτου]{.greek-omitted}[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου και [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη [απολυσει]{.greek-added} [απολυση]{.corr} τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ηγανακτησεν]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αφετε]{.greek-omitted} [τα]{.greek-omitted} [παιδια]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted} [μη]{.greek-omitted} [κωλυετε]{.greek-omitted} [αυτα]{.greek-omitted} [των]{.greek-omitted} [γαρ]{.greek-omitted} [τοιουτων]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[10:14]{.aside}

[ιδων]{.greek-omitted} δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14 | instance no. 2]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα ευλογει αυτα[10:16]{.aside}

και εκπορευομενου αυτου [[[ιησου]{.greek-abbr}]{.corr}]{.greek-added} εις οδον προσδραμων εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη [μοιχευσης]{.greek-omitted} [μοιχευσεις]{.greek-added} μη [φονευσης]{.greek-omitted} [φονευσεις]{.greek-added} μη [κλεψης]{.greek-omitted} [κλεψεις]{.greek-added} μη [ψευδομαρτυρησης]{.greek-omitted} [ψευδομαρτυρησεις]{.greek-added} μη [αποστερησης]{.greek-omitted} [αποστερησεις]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω εν σοι υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε [στυγνασας]{.greek-omitted} [στυγνωσας]{.greek-added} επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους [πεποιθωτας]{.greek-added} [πεποιθοτας]{.corr} επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [γαρ]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν [οι]{.greek-added} [οικιαν]{.greek-omitted} [η]{.greek-omitted} [αδελφους]{.greek-omitted} [η]{.greek-omitted} [αδελφας]{.greek-omitted} [η]{.greek-omitted} [πατερα]{.greek-omitted} [η]{.greek-omitted} [μητερα]{.greek-omitted} [η]{.greek-omitted} [γυναικα]{.greek-omitted} [η]{.greek-omitted} [τεκνα]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [ενεκεν]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted}[10:29]{.aside}

[αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ουδεις]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} [αφηκεν]{.greek-omitted} [οικιαν]{.greek-omitted} [κιαν]{.greek-added} η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29 | instance no. 2]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [μητερας]{.greek-abbr} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33]{.aside}

και εμπαιξουσιν αυτω και μαστιγωσουσιν αυτον και εμπτυσουσιν αυτω και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οι υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν αιτησωμεν [ποιησης]{.greek-omitted} [ποιησεις]{.greek-added} ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε [ειπον]{.greek-omitted} [ειπων]{.greek-added} αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι [αιτεισθε]{.greek-omitted} [αιτησθαι]{.greek-added} δυνασθε [πιειν]{.greek-omitted} [πιην]{.greek-added} το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον [αυτω]{.corr} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις [ητοιμασθαι]{.greek-added} [ητοιμασται]{.corr}[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι [αυ]{.greek-added} [αυτων]{.greek-omitted} [κατεξουσιαζουσιν]{.greek-omitted} [αυτων]{.greek-omitted}[10:42]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [οιδατε]{.greek-omitted} [οτι]{.greek-omitted} [οι]{.greek-omitted} [δοκουντες]{.greek-omitted} [αρχειν]{.greek-omitted} των [εθνων]{.greek-omitted} [κατακυριευουσιν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μεγαλοι]{.greek-omitted} [αυτων]{.greek-omitted} κατεξουσιαζουσιν αυτων[10:42 | instance no. 2]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη υμων γενεσθαι πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον [αντι]{.corr} πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-omitted} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και φωνουσιν τον τυφλον λεγοντες αυτω θαρσει εγειραι φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος ειπεν αυτω ραββουνι ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις [ου]{.greek-added} [σου]{.corr} [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} εις βηθσφαγη και βηθανιαν προς το ορος των ελαιων [αποστελλει]{.greek-omitted} [αποστελει]{.greek-added} δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} κεκαθικεν λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι ποιειτε τουτο ειπατε οτι ο [κυρος]{.greek-added} [κυριος]{.corr} αυτου χρειαν εχει και ευθεως [αυτον]{.greek-omitted} [αυτους]{.greek-added} αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων ελεγον αυτοις τι [ποιειτε]{.greek-omitted} [ποιει]{.greek-added} [λυοντες]{.greek-omitted} [τον]{.greek-omitted} [πωλον]{.greek-omitted}[11:5]{.aside}

[τε]{.greek-added} [και]{.greek-omitted} [τινες]{.greek-omitted} [των]{.greek-omitted} [εκει]{.greek-omitted} [εστηκοτων]{.greek-omitted} [ελεγον]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [ποιειτε]{.greek-omitted} λυοντες τον πωλον[11:5 | instance no. 2]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και εκαθισεν επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε στοιβαδας εκοπτον εκ των δενδρων και εστρωννυον εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος [παντα]{.greek-omitted} [παντας]{.greek-added} οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην μακροθεν εχουσαν [φυλα]{.greek-added} [φυλλα]{.corr} ηλθεν ει αρα ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου [γαρ]{.greek-omitted} [γαν]{.greek-added} ην καιρος συκων[11:13]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον [φαγει]{.greek-added} [φαγοι]{.corr} και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας καθεδρας των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι γραμματεις [και]{.greek-added} [οι]{.greek-added} [φαρισσαιοι]{.greek-added} και οι αρχιερεις και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted}[11:18]{.aside}

[και]{.greek-omitted} [ηκουσαν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [εζητουν]{.greek-omitted} [πως]{.greek-omitted} [αυτον]{.greek-omitted} [απολεσωσιν]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [εξεπλησσετο]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} διδαχη αυτου[11:18 | instance no. 2]{.aside}

και οτε οψε [εγενετο]{.greek-omitted} [εγινετο]{.greek-added} εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραντε]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν [οτι]{.greek-added} παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθαι]{.greek-added} πιστευετε οτι [λαμβανετε]{.greek-omitted} [λαμβανεται]{.greek-added} και εσται υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ [αφιετε]{.greek-omitted} [αφηεται]{.greek-added} ουδε ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} [δεδωκεν]{.greek-added} ινα ταυτα ποιης[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας και εγω ενα λογον και αποκριθητε μοι και ερω υμιν εν ποια [ε]{.unclear}ξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και ελογιζοντο προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον απαντες γαρ ειχον τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις [λε]{.greek-added} [λεγειν]{.greek-omitted} [αμπελωνα]{.greek-omitted} [εφυτευσεν]{.greek-omitted} [ανθρωπος]{.greek-omitted} [και]{.greek-omitted} [περιεθηκεν]{.greek-omitted} [φραγμον]{.greek-omitted} [και]{.greek-omitted} [ωρυξεν]{.greek-omitted} [υποληνιον]{.greek-omitted} [και]{.greek-omitted} [ωκοδομησεν]{.greek-omitted} [πυργον]{.greek-omitted} [και]{.greek-omitted} [εξεδοτο]{.greek-omitted} [αυτον]{.greek-omitted} [γεωργοις]{.greek-omitted} [και]{.greek-omitted} [απεδημησεν]{.greek-omitted}[12:1]{.aside}

[και]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [λεγειν]{.greek-omitted} [γειν]{.greek-added} αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[12:1 | instance no. 2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα [υιον]{.greek-abbr} εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον προς αυτους εσχατον λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε [αποκτεινωμεν]{.greek-omitted} [αποκτεινομεν]{.greek-added} αυτον και ημων εσται η [κληρονομια]{.greek-omitted} [κληρωνομια]{.greek-added}[12:7]{.aside}

και [λαβοντες]{.greek-omitted} [εκβαλοντες]{.greek-added} αυτον [απεκτειναν]{.greek-omitted} [και]{.greek-omitted} [εξεβαλον]{.greek-omitted} εξω του αμπελωνος [απεκτειναν]{.greek-added}[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην [ταυτην]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον ανθρωπων αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} φερετε μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η [εικων]{.greek-omitted} [εικον]{.greek-added} αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα εσχατη παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [ου]{.greek-omitted} δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε [γαμουσιν]{.greek-omitted} [γαμωσιν]{.greek-added} ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω μωσεως επι [του]{.greek-omitted} [της]{.greek-added} βατου [ως]{.greek-omitted} [πως]{.greek-added} ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω [ειμι]{.greek-added} ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και [ο]{.greek-omitted} [θεος]{.greek-omitted} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων [εις]{.greek-omitted} [τις]{.greek-added} των γραμματεων ακουσας αυτων συζητουντων ειδως οτι καλως [απεκριθη]{.greek-added} αυτοις [απεκριθη]{.greek-omitted} επηρωτησεν αυτον ποια εστιν [εντολη]{.greek-added} πρωτη [παν]{.greek-added} [παντων]{.greek-omitted} [εντολη]{.greek-omitted}[12:28]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [εις]{.greek-omitted} των [γραμματεων]{.greek-omitted} [ακουσας]{.greek-omitted} [αυτων]{.greek-omitted} [συζητουντων]{.greek-omitted} [ειδως]{.greek-omitted} [οτι]{.greek-omitted} [καλως]{.greek-omitted} [αυτοις]{.greek-omitted} [απεκριθη]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ποια]{.greek-omitted} [εστιν]{.greek-omitted} [πρωτη]{.greek-omitted} [παντων]{.greek-omitted} [εντολη]{.greek-omitted}[12:28 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω οτι πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολη]{.greek-added} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη [παντων]{.greek-added} εντολη[12:30]{.aside}

και δευτερα ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων αλλη εντολη ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι [εις]{.greek-omitted} [ει]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της [ισχυος]{.greek-omitted} [ισχυως]{.greek-added} και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [[δαυιδ]{.greek-abbr}]{.greek-added} εστιν [δαυιδ]{.greek-omitted}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} [ειπεν]{.greek-omitted} εν [πνευματι]{.greek-abbr} αγιω λεγει [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των γραμματεων [και]{.greek-added} των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και [πρωτοκαθεδριας]{.greek-omitted} [πρωτοκαθεδριαις]{.greek-added} εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθι[σ]{.greek-supplied}ας ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το [γαζοφυλακιον]{.greek-omitted} [γαζοφυλακειον]{.greek-added} και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισσευον]{.greek-added} [αυτοις]{.greek-omitted} [εβαλον]{.greek-omitted} [αυτη]{.greek-omitted} [δε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [υστερησεως]{.greek-omitted} [αυτης]{.greek-omitted} [παντα]{.greek-omitted} [οσα]{.greek-omitted} [ειχεν]{.greek-omitted} [εβαλεν]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [βιον]{.greek-omitted} [αυτης]{.greek-omitted}[12:44]{.aside}

[τος]{.greek-added} [παντες]{.greek-omitted} [γαρ]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [περισσευοντος]{.greek-omitted} αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44 | instance no. 2]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [παντα]{.greek-omitted} ταυτα συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους [πλανησουσιν]{.greek-omitted} [πλανησωσιν]{.greek-added}[13:6]{.aside}

οταν [δε]{.corr} ακουσητε πολεμους και ακοας πολεμων [ορατε]{.greek-added} μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων και βασιλεων [σταθησεσθε]{.greek-omitted} [αχθησεσθε]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη [πρω]{.greek-added} [δει]{.greek-omitted} [πρωτον]{.greek-omitted} [κηρυχθηναι]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted}[13:10]{.aside}

[τον]{.greek-added} [δε]{.greek-added} [και]{.greek-omitted} [εις]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} δει [πρωτον]{.greek-omitted} κηρυχθηναι το ευαγγελιον[13:10 | instance no. 2]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [μεριμνατε]{.greek-added} τι λαλησητε μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτ[ε]{.unclear} ου γαρ [εστε]{.greek-omitted} υμεις [εσται]{.greek-added} οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το [βδελυμα]{.greek-added} [βδελυγμα]{.corr} της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο [αναγινωσκων]{.greek-omitted} [αναγινωσκον]{.greek-added} νοειτω τοτε οι εν τη ιουδαια φευγετωσαν [εις]{.greek-omitted} [επι]{.greek-added} τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} [ταυτη]{.greek-added} [τοιαυτη]{.corr} απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} [η]{.greek-omitted} ιδου εκει μη πιστευετε[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και του[ς]{.unclear} εκλεκτους[13:22]{.aside}

υμεις δε [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} [πεσουντε]{.greek-added} [εσονται]{.greek-omitted} [εκπιπτοντες]{.greek-omitted} και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-omitted} [ερχομενον]{.greek-omitted} [εν]{.greek-omitted} [νεφελαις]{.greek-omitted} μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης [μαθετε]{.greek-omitted} [μαθεται]{.greek-added} την παραβολην οταν αυτης ηδη ο κλαδος απαλος γενηται και [εκφυη]{.greek-omitted} [εκφυει]{.greek-added} τα φυλλα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν ταυτα [ιδητε]{.greek-omitted} [ηδητε]{.greek-added} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι [δε]{.greek-omitted} της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [οι]{.greek-omitted} εν [τω]{.greek-added} [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

[βλεπετε]{.greek-omitted} αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως ανθρωπος αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα [γρηγορη]{.greek-omitted} [γρηγορει]{.greek-added}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο κυριος της οικιας ερχεται οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} [λεγω]{.greek-omitted} γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν τη οικια σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα [το]{.greek-omitted} [τον]{.greek-added} αλαβαστρον κατεχεεν [αυ]{.greek-added} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

[και]{.greek-omitted} [οντος]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} του [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} κατα της κεφαλης[14:3 | instance no. 2]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους [παρεχεται]{.greek-added} [παρεχετε]{.corr} καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο [εσχεν]{.greek-omitted} [ειχεν]{.greek-added} αυτη [εποιησεν]{.greek-omitted} [εποισεν]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον [κοσμον]{.greek-omitted} [κοσμων]{.greek-added} και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και ο ιουδας ο ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλαντο]{.greek-omitted} [επιγγειλαντο]{.greek-added} αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως [αυτον]{.greek-added} ευκαιρως [αυτον]{.greek-omitted} παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα φαγης το πασχα[14:12]{.aside}

και [αποστελλει]{.greek-omitted} [αποστελει]{.greek-added} δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει [αναγαιον]{.greek-added} [ανωγεον]{.greek-omitted} [μεγα]{.greek-omitted} εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και [ανα]{.greek-added} [ανακειμενων]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εσθιοντων]{.greek-omitted} [ειπεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [εις]{.greek-omitted} [εξ]{.greek-omitted} [υμων]{.greek-omitted} [παραδωσει]{.greek-omitted} [με]{.greek-omitted} [ο]{.greek-omitted} [εσθιων]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted}[14:18]{.aside}

[και]{.greek-omitted} [ανακειμενων]{.greek-omitted} [κειμενων]{.greek-added} αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18 | instance no. 2]{.aside}

οι δε ηρξαντο λυπεισθαι και [λεγειν]{.greek-omitted} [λεγει]{.greek-added} αυτω εις καθ εις μητι εγω [και]{.greek-omitted} [αλλος]{.greek-omitted} [μητι]{.greek-omitted} [εγω]{.greek-omitted}[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου [εις]{.greek-omitted} [το]{.greek-omitted} [εν]{.greek-added} [τω]{.greek-added} [τρυβλιον]{.greek-omitted} [τρυβλιω]{.greek-added}[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} [οτι]{.greek-omitted} παντες σκανδαλισθησεσθε [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} ταυτη [πριν]{.greek-omitted} [πρις]{.greek-added} η δις αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε εκπερισσου [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν [δεη]{.greek-added} με [δεη]{.greek-omitted} συναποθανειν σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added} δε και παντες ελεγον[14:31]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσημανει]{.greek-added} και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου [μει]{.greek-added} [μεινατε]{.greek-omitted} [ωδε]{.greek-omitted} [και]{.greek-omitted} [γρηγορειτε]{.greek-omitted}[14:34]{.aside}

[νατε]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [περιλυπος]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [ψυχη]{.greek-omitted} [μου]{.greek-omitted} [εως]{.greek-omitted} [θανατου]{.greek-omitted} [μεινατε]{.greek-omitted} ωδε και γρηγορειτε[14:34 | instance no. 2]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν [γρηγορεισαι]{.greek-added} [γρηγορησαι]{.corr}[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ ηδεισαν τι αυτω αποκριθωσιν[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα [και]{.greek-added} ιδου [παραδιδοται]{.greek-omitted} [παραδιδοτε]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις ων των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γραμματεων και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν [φιλησω]{.greek-omitted} [φιλισω]{.greek-added} αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω ραββι ραββι και [κατεφιλησεν]{.greek-omitted} [κατεφιλισεν]{.greek-added} αυτον[14:45]{.aside}

οι δε [επεβαλον]{.greek-omitted} [επεβαλλον]{.greek-added} επ αυτον τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω [περιβεβλημενος]{.greek-omitted} [σινδονα]{.greek-omitted} [επι]{.greek-omitted} [γυμνου]{.greek-omitted} [και]{.greek-omitted} [κρατουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[14:51]{.aside}

[και]{.greek-omitted} [εις]{.greek-omitted} [τις]{.greek-omitted} [νεανισκος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted} περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51 | instance no. 2]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και [απηγαγον]{.greek-omitted} [απηγαγων]{.greek-added} τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην [συγκαθημενος]{.greek-omitted} [συνκαθημενος]{.greek-added} μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} [λεγων]{.greek-omitted} [λεγον]{.greek-added} ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [καθημενον]{.greek-added} εκ δεξιων [καθημενον]{.greek-omitted} της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν φαινεται οι δε παντες κατεκριναν αυτον [ενοχον]{.greek-added} ειναι [ενοχον]{.greek-omitted} θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον και [ο]{.greek-supplied}ι υπηρεται ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων [του]{.greek-omitted} [αρχιερεως]{.greek-omitted}[14:66]{.aside}

[και]{.greek-omitted} [οντος]{.greek-omitted} [του]{.greek-omitted} [πετρου]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [αυλη]{.greek-omitted} [κατω]{.greek-omitted} [ερχεται]{.greek-omitted} [μια]{.greek-omitted} [των]{.greek-omitted} [παιδισκων]{.greek-omitted} του αρχιερεως[14:66 | instance no. 2]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε [επισταμαι]{.greek-omitted} [επισταμε]{.greek-added} τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον [παλιν]{.greek-omitted} ηρξατο λεγειν [παλιν]{.greek-added} τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες [ελεγων]{.greek-added} [ελεγον]{.corr} τω πετρω αληθως εξ αυτων ει και [γαρ]{.greek-omitted} [γαλιλαιος]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και [ανεμνησθη]{.greek-omitted} [ανεμνησθει]{.greek-added} ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι δις απαρνηση με τρις και επιβαλων [εκλαιεν]{.greek-omitted} [εκλαιε]{.greek-added}[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος [επηρωτα]{.greek-added} [παλιν]{.greek-omitted} [επηρωτησεν]{.greek-omitted} αυτον λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον παραδεδωκεισαν αυτον οι [αρχιερεις]{.greek-omitted} [αρ]{.greek-added}[15:10]{.aside}

[εγινωσκεν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [δια]{.greek-omitted} [φθονον]{.greek-omitted} [παραδεδωκεισαν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [χιερεις]{.greek-added}[15:10 | instance no. 2]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεπεισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} οι δε περισσοτερως εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται [απηγαγων]{.greek-added} [απηγαγον]{.corr} αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [[σταυρωθη]{.greek-abbr}]{.greek-added} [σταυρωσωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω [πιειν]{.greek-omitted} [πιην]{.greek-added} εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[[σ]{.greek-supplied}τρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι [παραπορευομενοι]{.greek-omitted} [εβλασφημουν]{.greek-omitted} [αυτον]{.greek-omitted} [κινουντες]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουα]{.greek-omitted} [ο]{.greek-omitted} [καταλυων]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τρισιν]{.greek-omitted} [ημεραις]{.greek-omitted} [οικοδομων]{.greek-omitted}[15:29]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο κατα[λ]{.greek-supplied}υων τον ναον και εν τρισιν ημεραις οικοδομων[15:29 | instance no. 2]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} [σωσαι]{.greek-omitted} [σωσε]{.greek-added}[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν αυτω και οι [συνεσταυρωμενοι]{.greek-abbr} αυτω [ωνειδιζον]{.greek-omitted} [ονειδιζον]{.greek-added} αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και τη ωρα τη ενατη [εβοησεν]{.greek-omitted} [ευοησεν]{.greek-added} ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων [ελωι]{.greek-omitted} [ελωι]{.greek-omitted} [ηλι]{.greek-added} [ηλι]{.greek-added} λιμα [σαβαχθανι]{.greek-omitted} [σαβαχθανη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των [π]{.greek-supplied}αρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως [κ]{.greek-supplied}ατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια η του ιακωβου του μικρου και [η]{.greek-added} ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι [και]{.greek-omitted} οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη [ο]{.greek-supplied}ψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο αριμαθαιας [ευσχημων]{.greek-omitted} [βουλευτης]{.greek-omitted} [ος]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ην]{.greek-omitted} [προσδεχομενος]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τολμησας]{.greek-omitted} [εισηλθεν]{.greek-omitted} [προς]{.greek-omitted} [πιλατον]{.greek-omitted} [και]{.greek-omitted} [ητησατο]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted}[15:43]{.aside}

[ηλθεν]{.greek-omitted} [ιωσηφ]{.greek-omitted} [ο]{.greek-omitted} [απο]{.greek-omitted} [αριμαθαιας]{.greek-omitted} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43 | instance no. 2]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλησε]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια [η]{.greek-added} ιωση εθεωρουν που [τιθεται]{.greek-omitted} [τεθηται]{.greek-added}[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι [αποκεκυλισται]{.greek-omitted} [αποκεκυλισθαι]{.greek-added} ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβεισθαι]{.greek-added} [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και [εκστασις]{.greek-omitted} [εκστασης]{.greek-added} και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι πρωτη [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} εφανη [πρωτον]{.greek-omitted} [μαρια]{.greek-omitted} [τη]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [αφ]{.greek-omitted} [ης]{.greek-omitted} [εκβεβληκει]{.greek-omitted} [επτα]{.greek-omitted} [δαιμονια]{.greek-omitted}[16:9]{.aside}

[αναστας]{.greek-omitted} [δε]{.greek-omitted} [πρωι]{.greek-omitted} [πρωτη]{.greek-omitted} [σαββατου]{.greek-omitted} [εφανη]{.greek-omitted} πρωτον μαρια τη μαγδαληνη αφ ης [εκβεβληκει]{.greek-omitted} [εκβεβληκη]{.greek-added} επτα δαιμονια[16:9 | instance no. 2]{.aside}

εκεινη [πορευθεισα]{.greek-omitted} [απελθουσα]{.greek-added} [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και κλαιουσιν[16:10]{.aside}

[κακεινοι]{.greek-omitted} [εκεινοι]{.greek-added} [δε]{.greek-added} ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ονειδησε]{.greek-added} την απιστιαν αυτων και [σκληροκαρδιαν]{.greek-omitted} [σκηροκαρδιαν]{.greek-added} οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις [π]{.unclear}ορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους [βλαψη]{.greek-omitted} [βλαψει]{.greek-added} επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον [βεβαιουντος]{.greek-omitted} [βεβαιομυτος]{.greek-added} δια των επακολουθουντων σημειων αμην[16:20]{.aside}

