---
title: "Collation of Byz^RP^ vs 30163 (163)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 163 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30163).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 163                                   	| λογος                              	|
| 163 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 163 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 163               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 163                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 163 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 163                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

βιβλος γενεσεως [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου [δαυιδ]{.greek-abbr} υιου αβρααμ[1:1]{.aside}

αβρααμ [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ ισαακ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιουδαν και τους αδελφους αυτου[1:2]{.aside}

ιουδας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον φαρες και τον ζαρα εκ της θαμαρ φαρες δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εσρωμ εσρωμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αραμ[1:3]{.aside}

αραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [το]{.greek-added} [αμιναδαβ]{.greek-omitted} [αμιναδαβ]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} [τον]{.greek-omitted} ναασσων ναασσων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [σαλμων]{.greek-omitted}[1:4]{.aside}

[των]{.greek-added} [σαλμων]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} [τον]{.greek-omitted} βοοζ εκ της ραχαβ βοοζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ωβηδ εκ της ρουθ ωβηδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεσσαι[1:5]{.aside}

ιεσσαι δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [δαυιδ]{.greek-abbr} τον βασιλεα [δαυιδ]{.greek-abbr} δε ο βασιλευς [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [σολομωνα]{.greek-omitted} [σολομωντα]{.greek-added} εκ της του ουριου[1:6]{.aside}

σολομων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ασα[1:7]{.aside}

ασα δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ιωσαφατ]{.greek-omitted} [ιωσαφ]{.greek-added} [ιωσαφατ]{.greek-omitted} [ιωσαφ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον οζιαν[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωαθαμ ιωαθαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [αχαζ]{.greek-omitted} [αχας]{.greek-added} [αχαζ]{.greek-omitted} [αχας]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εζεκιαν[1:9]{.aside}

εζεκιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον μανασση μανασσης δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμων αμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-added} [ιωακειμ]{.greek-added} [ιωακειμ]{.greek-added} [δε]{.greek-added} [εγεννησε]{.greek-added} τον ιεχονιαν και τους αδελφους αυτου επι της [μετοικεσιας]{.greek-omitted} [μετοικησιας]{.greek-added} βαβυλωνος[1:11]{.aside}

μετα δε την [μετοικεσιαν]{.greek-omitted} [μετοικησιαν]{.greek-added} βαβυλωνος ιεχονιας [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [σαλαθιηλ]{.greek-omitted} [σαλαθιηλ]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβιουδ αβιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ελιακειμ]{.greek-omitted} [ελιακιμ]{.greek-added} [ελιακειμ]{.greek-omitted} [ελιακιμ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [αχειμ]{.greek-omitted} [αχιμ]{.greek-added} [αχειμ]{.greek-omitted} [αχιμ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελεαζαρ ελεαζαρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

πασαι ουν αι γενεαι απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεαι δεκατεσσαρες και απο [δαυιδ]{.greek-abbr} εως της [μετοικεσιας]{.greek-omitted} [μετοικησιας]{.greek-added} βαβυλωνος γενεαι δεκατεσσαρες και απο της [μετοικεσιας]{.greek-omitted} [μετοικησιας]{.greek-added} βαβυλωνος εως του [χριστου]{.greek-abbr} γενεαι δεκατεσσαρες[1:17]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην [μνηστευθεισης]{.greek-omitted} [μνηστευθησης]{.greek-added} γαρ της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν η συνελθειν αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην [παραδειγματισαι]{.greek-omitted} [παραδειγματησαι]{.greek-added} εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} [εφανη]{.greek-added} κατ οναρ [εφανη]{.greek-omitted} [αυτω]{.greek-omitted} [τω]{.greek-added} [ιωσηφ]{.greek-added} λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη [φοβηθης]{.greek-omitted} [φοβιθεις]{.greek-added} παραλαβειν μαριαμ την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

τεξεται δε [υιον]{.greek-abbr} και καλεσεις το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο [του]{.greek-omitted} [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι [εξει]{.greek-omitted} [εξη]{.greek-added} και τεξεται [υιον]{.greek-abbr} και [καλεσουσιν]{.greek-omitted} [καλεση]{.greek-added} το ονομα αυτου εμμανουηλ ο εστιν μεθερμηνευομενον μεθ [η]{.greek-added} [ημων]{.greek-omitted} [μων]{.greek-added} ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε ο ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και παρελαβεν την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου ετεκεν [το]{.unclear}ν [υιον]{.greek-abbr} αυτης τον πρωτοτοκον και εκαλεσεν το ονομα αυτου ιησουν[1:25]{.aside}

### Chapter 2

του δε [ιησου]{.greek-abbr} γεννηθεντος εν βηθλεεμ της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων ειδομεν γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι αυτω[2:2]{.aside}

ακουσας δε ηρωδης ο βασιλευς εταραχθη και πασα ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας το[υς]{.greek-supplied} [α]{.unclear}ρχιερεις και γραμματεις του λαου επυνθανετο παρ αυτων που ο [χριστος]{.greek-abbr} γενναται[2:4]{.aside}

οι δε ειπον αυτω εν βηθλεεμ της ιουδαιας ουτως [γαρ]{.greek-omitted} γεγραπται δια του προφητου[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ουδαμως ελαχιστη ει εν τοις ηγεμοσιν ιουδα εκ σου γαρ εξελευσεται ηγουμενος οστις ποιμανει τον λαον μου τον ισραηλ[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ ειπεν [αυτοις]{.greek-added} πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε [απαγγειλατε]{.greek-omitted} [αναγγειλατε]{.greek-added} μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ ον [ειδον]{.greek-omitted} [ιδον]{.greek-added} εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα [εχαρησαν]{.greek-omitted} [εχαρισαν]{.greek-added} χαραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες εις την οικιαν [ειδον]{.greek-omitted} [ιδον]{.greek-added} το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσεκυνησαν αυτω και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων [δε]{.greek-omitted} [αυτων]{.greek-omitted} [των]{.greek-added} [μαγων]{.greek-added} ιδου αγγελος [κυριου]{.greek-abbr} [φαινεται]{.greek-omitted} κατ οναρ [φαινεται]{.greek-added} τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο [του]{.greek-omitted} [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον [υιον]{.greek-abbr} μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη λιαν και αποστειλας ανειλεν παντας τους παιδας τους εν βηθλεεμ και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις οριοις αυτης απο διετους και [κατωτερω]{.greek-omitted} [κατωτερων]{.greek-added} κατα τον χρονον ον [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρα των μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν υπο ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη [θρηνος]{.greek-omitted} [θρινος]{.greek-added} και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ειθελεν]{.greek-added} παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ φαινεται τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} [τεθνηκασιν]{.greek-omitted} [τεθνηκασι]{.greek-added} γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις παρελαβεν το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει επι της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν εις πολιν λεγομενην ναζαρετ οπως πληρωθη το ρηθεν δια των προφητων οτι ναζωραιος κληθησεται[2:23]{.aside}

### Chapter 3

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [εν]{.greek-omitted} [δε]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [εκειναις]{.greek-omitted} παραγινεται ιωαννης ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

και λεγων μετανοειτε ηγγικεν γαρ η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

[ουτος]{.greek-omitted} [ουτως]{.greek-added} γαρ εστιν ο ρηθεις υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε ο ιωαννης ειχεν το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον ιεροσολυμα και πασα η ιουδαια και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο εν τω ιορδανη [ποταμω]{.greek-added} υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισμα αυτου ειπεν αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν εαυτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των [λιθων]{.greek-omitted} [λιθον]{.greek-added} τουτων εγειραι τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[3:10]{.aside}

εγω μεν βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον [μεν]{.greek-added} σιτον [αυτου]{.greek-omitted} εις την αποθηκην [αυτου]{.greek-added} το δε [αχυρον]{.greek-omitted} [αχειρον]{.greek-added} κατακαυσει πυρι ασβεστω[3:12]{.aside}

[τοτε]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον ιωαννην του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε ιωαννης [διεκωλυεν]{.greek-omitted} [διεκολυεν]{.greek-added} αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν προς αυτον αφες αρτι ουτως [γαρ]{.greek-omitted} [πρεπον]{.greek-omitted} [πρεπων]{.greek-added} εστιν ημιν πληρωσαι πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

[και]{.greek-omitted} βαπτισθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ανεβη [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} απο του υδατος και ιδου ανεωχθησαν αυτω οι [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} [καταβαινον]{.greek-omitted} [καταβαινων]{.greek-added} ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[3:17]{.aside}

### Chapter 4

τοτε [ανηχθη]{.greek-added} ο [ιησους]{.greek-abbr} [ανηχθη]{.greek-omitted} εις την ερημον υπο του [πνευματος]{.greek-abbr} πειρασθηναι υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας τεσσαρακοντα και νυκτας τεσσαρακοντα υστερον επεινασεν[4:2]{.aside}

και προσελθων αυτω ο πειραζων ειπεν ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι [γενωνται]{.greek-omitted} [γενονται]{.greek-added}[4:3]{.aside}

ο δε αποκριθεις ειπεν γεγραπται ουκ επ αρτω μονω ζησεται [ανθρωπος]{.greek-abbr} αλλ επι παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και [ιστησιν]{.greek-omitted} [ειστησιν]{.greek-added} αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} βαλε σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων αρουσιν σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} παλιν γεγραπται ουκ εκπειρασεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν παραλαμβανει αυτον ο διαβολος εις ορος υψηλον λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι [δωσω]{.greek-omitted} [δοσω]{.greek-added} εαν πεσων [προσκυνησης]{.greek-omitted} [προσκυνησεις]{.greek-added} μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω μονω λατρευσεις[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ακουσας [δε]{.greek-omitted} ο [ιησους]{.greek-abbr} οτι ιωαννης [παρεδοθη]{.greek-omitted} [παρεδωθη]{.greek-added} ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} την [ναζαρετ]{.greek-omitted} [αζαρετ]{.greek-added} ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και νεφθαλειμ[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη νεφθαλειμ [οδον]{.greek-omitted} [οδος]{.greek-added} θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει ειδεν φως μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων [δε]{.greek-omitted} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} δυο αδελφους σιμωνα τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπι[σ]{.unclear}ω μου και ποιησω υμας αλιεις [ανθρωπων]{.greek-abbr}[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων [καταρτιζοντας]{.greek-omitted} [τα]{.greek-omitted} [δικτυα]{.greek-omitted} [αυτων]{.greek-omitted} και εκαλεσεν αυτους[4:21]{.aside}

οι δε ευθεως αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν ολην την γαλιλαιαν ο [ιησους]{.greek-abbr} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και [απηλθεν]{.greek-omitted} [εξηλθεν]{.greek-added} η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και βασανοις συνεχομενους [και]{.greek-omitted} δαιμονιζομενους και σεληνιαζομενους και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} ηκολουθησαν [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} οχλοι [πολλοι]{.greek-omitted} απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και [καθισαντος]{.greek-omitted} [καθησαντος]{.greek-added} αυτου προσηλθον αυτω οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους λεγων[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθησονται[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομησουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι [πεινωντες]{.greek-omitted} [πινωντες]{.greek-added} και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

μακαριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι εστε οταν ονειδισωσιν υμας και [διωξωσιν]{.greek-omitted} [διωξωσι]{.greek-added} και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

[χαιρετε]{.greek-omitted} [χαιρεται]{.greek-added} και [αγαλλιασθε]{.greek-omitted} [αγαλλιασθαι]{.greek-added} οτι ο μισθος υμων πολυς εν τοις [ουρανοις]{.greek-abbr} ουτως γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το αλας της γης εαν δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και [τιθεασιν]{.greek-omitted} [τηθεασιν]{.greek-added} αυτον υπο τον μοδιον αλλ επι την λυχνιαν και [διαλαμπη]{.greek-added} [λαμπει]{.greek-omitted} [[διαλαμπει]{.corr}]{.greek-added} πασιν τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων εμπροσθεν των [ανθρωπων]{.greek-abbr} οπως ιδωσιν υμων τα καλα εργα και [δοξασωσιν]{.greek-omitted} [δοξασωσι]{.greek-added} τον [πατερα]{.greek-abbr} υμων τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη [νομισητε]{.greek-omitted} [νομησητε]{.greek-added} οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η μια [κεραια]{.greek-omitted} [κερεα]{.greek-added} ου μη παρελθη απο του νομου [και]{.greek-added} [των]{.greek-added} [προφητων]{.greek-added} εως αν παντα γενηται[5:18]{.aside}

ος [εαν]{.greek-omitted} [αν]{.greek-added} ουν λυση μιαν των [εντολων]{.greek-omitted} [εντωλων]{.greek-added} τουτων των ελαχιστων και διδαξη ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} και διδαξη ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση [υμων]{.greek-added} η δικαιοσυνη [υμων]{.greek-omitted} [πλειον]{.greek-omitted} [πλεον]{.greek-added} των γραμματεων και φαρισαιων ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν φονευση ενοχος εσται τη κρισει[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν ειπη τω αδελφω αυτου ρακα ενοχος εσται τω συνεδριω ος δ αν ειπη [τω]{.greek-added} [αδελφω]{.greek-added} [αυτου]{.greek-added} μωρε ενοχος εσται εις την γεενναν του πυρος[5:22]{.aside}

εαν ουν [προσφερης]{.greek-omitted} [προσφερεις]{.greek-added} το δωρον σου επι το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου [ει]{.greek-omitted} [η]{.greek-added} εν τη οδω μετ αυτου μηποτε σε παραδω ο [αντιδικος]{.greek-omitted} [αντιδικως]{.greek-added} τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην βληθηση[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως [αν]{.greek-omitted} [οτου]{.greek-added} αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη [τοις]{.greek-added} [αρχαιοις]{.greek-added} ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα προς το επιθυμησαι αυτην ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιος σκανδαλιζει σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολειται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ σκανδαλιζει σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολειται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη δε [ο[ς]{.unclear}]{.greek-added} [οτι]{.corr} [ος]{.corr} [αν]{.greek-omitted} [εαν]{.greek-added} απολυση την γυναικα αυτου [δοτω]{.greek-omitted} [αυτη]{.greek-omitted} [αποστασιον]{.greek-omitted}[5:31]{.aside}

[εγω]{.greek-omitted} [δε]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [αυτου]{.greek-omitted} παρεκτος λογου πορνειας ποιει αυτην μοιχασθαι και ος [εαν]{.greek-omitted} απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατ[ε]{.unclear} [[ηκουσαται]{.corr}]{.greek-added} οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε τω [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη [ομοσαι]{.greek-omitted} [ομωσαι]{.greek-added} ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος εστιν του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον εστιν των ποδων αυτου μητε εις ιεροσολυμα οτι πολις εστιν του μεγαλου βασιλεως[5:35]{.aside}

[μητε]{.greek-omitted} [μηποτε]{.greek-added} εν τη κεφαλη σου ομοσης οτι ου δυνασαι μιαν τριχα λευκην η μελαιναν ποιησαι[5:36]{.aside}

εστω δε ο λογος [υμων]{.greek-omitted} [ημων]{.greek-added} ναι ναι ου ου το δε [περισσον]{.greek-omitted} [περισσων]{.greek-added} τουτων εκ του πονηρου εστιν[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω αλλ οστις σε ραπισει επι την δεξιαν [σιαγονα]{.greek-omitted} [σιαγοναν]{.greek-added} [σου]{.greek-added} στρεψον αυτω και την αλλην[5:39]{.aside}

και τω θελοντι σοι κριθηναι και τον [χιτωνα]{.greek-omitted} [χιτονα]{.greek-added} σου λαβειν αφες αυτω και το ιματιον[5:40]{.aside}

και οστις σε αγγαρευσει μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} τω αιτουντι σε διδου και τον θελοντα απο σου δανεισασθαι μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και [μισησεις]{.greek-omitted} [μησησεις]{.greek-added} τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων ευλογειτε τους καταρωμενους υμας καλως ποιειτε τοις μισουσιν υμας και προσευχεσθε υπερ των [επηρεαζοντων]{.greek-omitted} [επερεαζοντων]{.greek-added} υμας και διωκοντων [υμας]{.greek-omitted}[5:44]{.aside}

οπως γενησθε υιοι του [πατρος]{.greek-abbr} υμων του εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} [οτι]{.greek-omitted} [οστις]{.greek-added} τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ αγαπησητε τους αγαπωντας υμας τινα μισθον εχετε ουχι και οι τελωναι το [αυτο]{.greek-omitted} [αυτω]{.greek-added} ποιουσιν[5:46]{.aside}

και εαν ασπασησθε τους φιλους υμων μονον τι περισσον [ποιειτε]{.greek-omitted} [ποιει]{.greek-added} ουχι και οι [τελωναι]{.greek-omitted} [ουτως]{.greek-omitted} [εθνικοι]{.greek-added} [το]{.greek-added} [αυτο]{.greek-added} ποιουσιν[5:47]{.aside}

εσεσθε ουν υμεις τελειοι ωσπερ ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} τελειος εστιν[5:48]{.aside}

### Chapter 6

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} προσεχετε την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων [[ημων]{.corr}]{.greek-added} τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν [ποιης]{.greek-omitted} [ποιεις]{.greek-added} ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αυτος αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται [οτι]{.greek-omitted} φιλουσιν εν ταις συναγωγαις και εν ταις γωνιαις των πλατειων εστωτες προσευχεσθαι οπως [αν]{.greek-omitted} [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το ταμιειον σου και κλεισας την θυραν σου προσευξαι τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη βαττολογησητε ωσπερ οι εθνικοι [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν ομοιωθητε αυτοις οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ων χρειαν εχετε προ του υμας αιτησαι αυτον[6:8]{.aside}

ουτως ουν προσευχεσθε υμεις [πατερ]{.greek-abbr} ημων ο εν τοις ουρανοις αγιασθητω το ονομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων ως και ημεις [αφιεμεν]{.greek-omitted} [αφιομεν]{.greek-added} τοις οφειλεταις ημων[6:12]{.aside}

και μη [εισενεγκης]{.greek-omitted} [εισενεγκεις]{.greek-added} ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα εις τους αιωνας αμην[6:13]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} εαν [γαρ]{.greek-omitted} αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων [αφησει]{.greek-omitted} [αφιησι]{.greek-added} και υμιν ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} [τα]{.greek-added} [παραπτωματα]{.greek-added} [υμων]{.greek-added}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων [αφησει]{.greek-omitted} [αφιησι]{.greek-added} τα παραπτωματα υμων[6:15]{.aside}

οταν δε [νηστευητε]{.greek-omitted} [νιστευητε]{.greek-added} μη γινεσθε ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων αλειψαι σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι [εν]{.greek-added} [τω]{.greek-added} [φανερω]{.greek-added}[6:18]{.aside}

μη θησαυριζετε υμιν θησαυρους επι της γης οπου σης και βρωσις [αφανιζει]{.greek-omitted} [αφανιζη]{.greek-added} και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορισουσι]{.greek-added} και κλεπτουσιν[6:19]{.aside}

[θησαυριζετε]{.greek-omitted} [θησαυριζεται]{.greek-added} δε υμιν θησαυρους εν ουρανω οπου ουτε σης ουτε βρωσις αφανιζει και οπου κλεπται ου διορυσσουσιν ουδε [κλεπτουσιν]{.greek-omitted} [κλεπτουσι]{.greek-added}[6:20]{.aside}

οπου γαρ εστιν ο θησαυρος υμων εκει εσται και η καρδια υμων[6:21]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους η ολον το σωμα σου [φωτεινον]{.greek-omitted} [φωτινον]{.greek-added} εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος εστιν το σκοτος ποσον[6:23]{.aside}

ουδεις [δυναται]{.greek-omitted} [δυνατε]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα [μισησει]{.greek-omitted} [μισισει]{.greek-added} και τον ετερον [αγαπησει]{.greek-omitted} η ενος ανθεξεται και του ετερου καταφρονησει ου δυνασθε [θεω]{.greek-abbr} δουλευειν και [μαμωνα]{.greek-omitted} [μαμονα]{.greek-added}[6:24]{.aside}

δια τουτο λεγω υμιν μη [μεριμνατε]{.greek-omitted} [μεριμνησητε]{.greek-added} τη ψυχη υμων τι φαγητε και τι πιητε μηδε τω σωματι υμων τι ενδυσησθε ουχι η ψυχη πλειον εστιν της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα πετεινα του [ουρανου]{.greek-abbr} οτι ου σπειρουσιν ουδε θεριζουσιν ουδε συναγουσιν εις αποθηκας και ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} τρεφει αυτα ουχ υμεις μαλλον διαφερετε αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται [προσθειναι]{.greek-omitted} [προσθηναι]{.greek-added} επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου [κοπια]{.greek-omitted} [κοπιπια]{.greek-added} ουδε νηθει[6:28]{.aside}

λεγω δε υμιν οτι ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλομενον ο [θεος]{.greek-abbr} ουτως [αμφιεννυσιν]{.greek-omitted} [αμφυεννυσιν]{.greek-added} ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν μεριμνησητε λεγοντες τι φαγωμεν η τι πιωμεν η τι [περιβαλωμεθα]{.greek-omitted} [περιβαλλομεθα]{.greek-added}[6:31]{.aside}

παντα γαρ ταυτα τα εθνη επιζητει οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} οτι [χρηζετε]{.greek-omitted} [χρηζεται]{.greek-added} τουτων απαντων[6:32]{.aside}

ζητειτε δε [πρωτον]{.greek-omitted} [πρωτων]{.greek-added} την βασιλειαν του θεου και [την]{.greek-omitted} [δικαιοσυνην]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν μεριμνησητε εις την αυριον η γαρ αυριον μεριμνησει τα εαυτης αρκετον τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} μη κρινετε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε κριθησεσθε και εν ω μετρω μετρειτε [μετρηθησεται]{.greek-omitted} [αντιμετριθησεται]{.greek-added} υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος [το]{.greek-omitted} [τω]{.greek-added} εν τω οφθαλμω του αδελφου σου την δε [δωκον]{.greek-added} [την]{.greek-added} εν τω [σω]{.greek-omitted} οφθαλμω [δοκον]{.greek-omitted} [σου]{.greek-added} ου κατανοεις [τω]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [οφθαλμω]{.greek-added} [του]{.greek-added} [αδελφου]{.greek-added} [σου]{.greek-added} [την]{.greek-added} [δε]{.greek-added} [δοκον]{.greek-added} [την]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [οφθαλμω]{.greek-added} [σου]{.greek-added} [ου]{.greek-added} [κατανοεις]{.greek-added}[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος [απο]{.greek-omitted} [η]{.greek-added} [πως]{.greek-added} [ερεις]{.greek-added} [το]{.greek-added} [αδελφω]{.greek-added} [σου]{.greek-added} [αφες]{.greek-added} [εκβαλω]{.greek-added} [το]{.greek-added} [καρφος]{.greek-added} [εκ]{.greek-added} του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη δωτε το αγιον τοις κυσιν μηδε βαλητε τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε καταπατησωσιν αυτους [εν]{.greek-omitted} τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

αιτειτε και [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} υμιν ζητειτε και ευρησετε κρουετε και ανοιγησεται υμιν[7:7]{.aside}

πας γαρ ο αιτων [λαμβανει]{.greek-omitted} [λαμβανειν]{.greek-added} και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις εστιν εξ υμων [ανθρωπος]{.greek-abbr} [ον]{.greek-omitted} [ο]{.greek-added} εαν [αιτηση]{.greek-omitted} [αιτησει]{.greek-added} ο [υιος]{.greek-abbr} αυτου αρτον μη λιθον [επιδωση]{.greek-added} [επιδωσει]{.corr} αυτω[7:9]{.aside}

[και]{.corr} [εαν]{.corr} [ιχθυν]{.corr} [αιτηση]{.greek-omitted} [[αιτησει]{.corr}]{.greek-added} [μη]{.corr} [οφιν]{.corr} [επιδωσει]{.greek-omitted} [[επιδωση]{.corr}]{.greek-added} [αυτω]{.corr}[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο εν τοις ουρανοις [δωσει]{.greek-omitted} [δωση]{.greek-added} αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

παντα ουν οσα αν θελητε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} ουτως και υμεις ποιειτε αυτοις ουτος γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

[εισελθετε]{.greek-omitted} [εισελθατε]{.greek-added} δια της στενης πυλης οτι πλατεια η πυλη και [ευρυχωρος]{.greek-omitted} [ευρυχορος]{.greek-added} η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

[τι]{.greek-omitted} [τη]{.greek-added} στενη [η]{.greek-omitted} [πυλη]{.greek-omitted} και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

προσεχετε δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων [επιγνωσεσθε]{.greek-omitted} [επιγνωσεσθαι]{.greek-added} αυτους [μητι]{.greek-omitted} [μη]{.greek-added} [τις]{.greek-added} συλλεγουσιν απο [ακανθων]{.greek-omitted} [ακαν]{.greek-added} [θων]{.greek-added} [σταφυλην]{.greek-omitted} [σταφυλας]{.greek-added} η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν [ουδε]{.greek-omitted} [δενδρον]{.greek-omitted} [σαπρον]{.greek-omitted} [καρπους]{.greek-omitted} [καλους]{.greek-omitted} [ποιειν]{.greek-omitted}[7:18]{.aside}

παν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων [επιγνωσεσθε]{.greek-omitted} [επιγνωσεσθαι]{.greek-added} αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι ερουσιν μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου τω σω ονοματι προεφητευσαμεν και τω σω ονοματι δαιμονια εξεβαλομεν και τω σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε ομολογησω αυτοις οτι ουδεποτε εγνων υμας αποχωρειτε απ εμου [παντες]{.greek-added} οι εργαζομενοι την ανομιαν[7:23]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} πας ουν οστις ακουει μου τους λογους τουτους και ποιει αυτους [ομοιωθησεται]{.greek-added} [ομοιωσω]{.greek-omitted} [αυτον]{.greek-omitted} ανδρι φρονιμω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδωμησεν]{.greek-added} την οικιαν αυτου επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και [προσεπεσον]{.greek-omitted} [προσερρηξαν]{.greek-added} τη οικια εκεινη και ουκ επεσεν [τεθεμελιωτο]{.greek-omitted} [τεθεμελιωτω]{.greek-added} γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω οστις ωκοδομησεν την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και [προσεκοψαν]{.greek-omitted} [προσεκρουσαν]{.greek-added} τη οικια εκεινη και επεσεν και ην η πτωσις αυτης μεγαλη [σφοδρα]{.greek-added}[7:27]{.aside}

και εγενετο οτε [συνετελεσεν]{.greek-omitted} [εσυνετελεσεν]{.greek-added} ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και [ο[―]{.gap}]{.greek-added} [χ]{.greek-added} [ουχ]{.corr} ως οι γραμματεις [αυτων]{.greek-added} [και]{.greek-added} [οι]{.greek-added} [φαρισαιοι]{.greek-added}[7:29]{.aside}

### Chapter 8

καταβαντι δε [αυτω]{.greek-omitted} [αυτου]{.greek-added} απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου λεπρος [ελθων]{.greek-omitted} [προσελθων]{.greek-added} [προσεκυνει]{.greek-omitted} [προσεκυνη]{.greek-added} αυτω λεγων [κυριε]{.greek-abbr} εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} δυνασαι με καθαρισαι[8:2]{.aside}

και [εκτεινας]{.greek-omitted} [εκτηνας]{.greek-added} την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω καθαρισθητι και ευθεως εκαθαρισθη αυτου η [λεπρα]{.greek-omitted} [λεμπρα]{.greek-added}[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι ειπης [αλλα]{.greek-omitted} [αλλ]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε το δωρον ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης [[μωυσης]{.corr}]{.greek-added} εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} εις καπερναουμ προσηλθεν αυτω εκατονταρχος [παρακαλων]{.greek-omitted} [αυτον]{.greek-omitted}[8:5]{.aside}

[και]{.greek-omitted} λεγων [κυριε]{.greek-abbr} ο παις μου βεβληται εν τη οικια παραλυτικος [δεινως]{.greek-omitted} [δεινος]{.greek-added} βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω [τουτω]{.greek-omitted} [τουτο]{.greek-added} πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} εθαυμασεν και ειπεν τοις ακολουθουσιν [αυτω]{.greek-added} αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην [πιστιν]{.greek-omitted} [πιστην]{.greek-added} ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων ηξουσιν και [ανακλιθησονται]{.greek-omitted} [ανακληθησονται]{.greek-added} μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το [εξωτερον]{.greek-omitted} [εξοτερον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω εκατονταρχη υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη [και]{.greek-added} [υποστρεψας]{.greek-added} [ο]{.greek-added} [εκατονταρχης]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [αυτου]{.greek-added} [εν]{.greek-added} [αυτη]{.greek-added} [τη]{.greek-added} [ωρα]{.greek-added} [ευρεν]{.greek-added} [τον]{.greek-added} [παιδα]{.greek-added} [υγιαινοντα]{.greek-added}[8:13]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και [διηκονει]{.greek-omitted} [διεικονει]{.greek-added} αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και εξεβαλεν τα [πνευματα]{.greek-abbr} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια [ησαιου]{.greek-omitted} [ισαιου]{.greek-added} του προφητου λεγοντος αυτος τας ασθενειας ημων ελαβεν και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [πολλους]{.greek-omitted} [πολυς]{.greek-added} [οχλους]{.greek-omitted} [οχλος]{.greek-added} περι [αυτον]{.greek-omitted} [αυτων]{.greek-added} εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν απερχη[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι [αλωπεκες]{.greek-omitted} [αλωπηκες]{.greek-added} [φωλεους]{.greek-omitted} [φωλαιους]{.greek-added} εχουσιν και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κλινει]{.greek-added}[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [ακολουθη]{.greek-added} [ακολουθει]{.corr} μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

[και]{.greek-omitted} εμβαντι [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} εις [το]{.greek-omitted} πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων [ην]{.greek-added} [γαρ]{.greek-added} [ο]{.greek-added} [ανεμος]{.greek-added} [εναντιος]{.greek-added} [αυτοις]{.greek-added} αυτος δε εκαθευδεν[8:24]{.aside}

και προσελθοντες οι μαθηται [αυτου]{.greek-added} ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι τοτε εγερθεις [επετημισεν]{.greek-added} [επετιμησεν]{.greek-omitted} [[επετημησεν]{.corr}]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο [γαληνη]{.greek-omitted} [γαλινη]{.greek-added} μεγαλη[8:26]{.aside}

οι δε [αν]{.greek-added} [ανθρωποι]{.greek-omitted} [θρωποι]{.greek-added} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} ελθοντι [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [αυτω]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} εις την χωραν των [γεργεσηνων]{.greek-omitted} [γεγερσινων]{.greek-added} υπηντησαν αυτω δυο δαιμονιζομενοι εκ των [μνημειων]{.greek-omitted} [μνημειον]{.greek-added} εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} [υιε]{.greek-abbr} του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων πολλων βοσκομενη[8:30]{.aside}

οι [δε]{.greek-omitted} δαιμονες παρεκαλουν αυτον λεγοντες ει [εκβαλλεις]{.greek-omitted} [εκβαλεις]{.greek-added} ημας επιτρεψον ημιν απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου [ωρμησεν]{.greek-omitted} [ορμησεν]{.greek-added} πασα η αγελη [των]{.greek-omitted} [χοιρων]{.greek-omitted} κατα του [κρημνου]{.greek-omitted} [κριμνου]{.greek-added} εις [την]{.greek-omitted} [στην]{.greek-added} θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν [απηγγειλαν]{.greek-omitted} [απειγγειλαν]{.greek-added} παντα και τα των [δαιμονιζομενων]{.greek-omitted} [δαιμονων]{.greek-added}[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις [συναντησιν]{.greek-omitted} [συναντισιν]{.greek-added} τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις [το]{.greek-omitted} πλοιον διεπερασεν και ηλθεν εις την ιδιαν πολιν [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [εμβας]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [πλοιον]{.greek-added} [και]{.greek-added} [επερασεν]{.greek-added} [και]{.greek-added} [ηλθεν]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [ιδιαν]{.greek-added} [πολιν]{.greek-added}[9:1]{.aside}

και ιδου [προσεφερον]{.greek-omitted} [προσεφεραν]{.greek-added} αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} αυτων ειπεν τω παραλυ[τ]{.unclear}ικω θαρσει τεκνον [αφεωνται]{.greek-omitted} [αφαιονται]{.greek-added} σοι αι αμαρτιαι σου[9:2]{.aside}

και ιδου τινε[ς]{.unclear} των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ειπον εν εαυτοις [ουτος]{.greek-omitted} [ουτως]{.greek-added} βλασφημει[9:3]{.aside}

και [ιδων]{.greek-omitted} [ειδως]{.greek-added} ο [ιησους]{.greek-abbr} τας [ενθυμησεις]{.greek-omitted} [ενθυμισεις]{.greek-added} αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις ενθυμεισθε [πονηρα]{.greek-omitted} [πονιρα]{.greek-added} εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν [ευκο]{.greek-added} [ευκοπωτερον]{.greek-omitted} [πωτερον]{.greek-added} ειπειν [αφεωνται]{.greek-omitted} [αφαιονται]{.greek-added} σου αι αμαρτιαι [σου]{.greek-added} η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[9:5]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} παραγων ο [ιησους]{.greek-abbr} εκειθεν [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [ανθρωπον]{.greek-abbr} καθημενον επι [το]{.greek-omitted} [τω]{.greek-added} τελωνιον [ματθαιον]{.greek-omitted} [μαθθαιον]{.greek-added} λεγομενον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες [συνανεκειντο]{.greek-omitted} [συνανεκειντω]{.greek-added} τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων εσθιει ο διδασκαλος υμων[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν ελεον θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται ιωαννου λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε μαθηται σου ου νηστευουσιν[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος [πενθειν]{.greek-omitted} [νηστευειν]{.greek-added} εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευσωσιν]{.greek-added}[9:15]{.aside}

ουδεις δε επιβαλλει επιβλημα [ρακους]{.greek-omitted} [ρακκους]{.greek-added} [αγναφου]{.greek-omitted} [ακναφου]{.greek-added} επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και [χειρον]{.greek-omitted} [χει]{.greek-added} [ρων]{.greek-added} σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος εκχειται και οι ασκοι [απολουνται]{.greek-omitted} [απολλυνται]{.greek-added} αλλα βαλλουσιν οινον νεον εις ασκους καινους και [αμφοτεροι]{.greek-omitted} [αμφοτερα]{.greek-added} συντηρουνται[9:17]{.aside}

ταυτα αυτου λαλουντος αυτοις [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ιδου αρχων [εις]{.greek-omitted} [ελθων]{.greek-omitted} [τις]{.greek-added} [προσελθων]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν αλλα ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

ελεγεν γαρ εν εαυτη εαν μονον [αψωμαι]{.greek-omitted} [αψομαι]{.greek-added} [του]{.greek-added} [κρασπεδου]{.greek-added} του ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην ειπεν θαρσει θυγατερ η [πιστις]{.greek-omitted} [πιστι]{.greek-added} σου σεσωκεν σε και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυ[β]{.unclear}ουμενον[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ απεθανεν το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισελθων εκρατησεν της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} παραγοντι [εκειθεν]{.greek-omitted} τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

[ελθοντι]{.greek-omitted} [ελθοντος]{.greek-added} δε [αυτου]{.greek-added} εις την οικιαν προσηλθον αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} πιστευετε οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων αυτων λεγων κατα την πιστιν υμων γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν [αυτων]{.greek-omitted} [αυτον]{.greek-added} οι οφθαλμοι [και]{.unclear} [ενε]{.unclear}βριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες [διεφημισαν]{.greek-omitted} [διεφημησαν]{.greek-added} αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες ουδεποτε εφανη ουτως εν τω ισραηλ[9:33]{.aside}

οι δε φαρισαιοι ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας [πολεις]{.greek-omitted} [πολις]{.greek-added} πασας και τας [κωμας]{.greek-omitted} [κομας]{.greek-added} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω [και]{.greek-added} [πολλοι]{.greek-added} [ηκολουθησαν]{.greek-added} [αυτω]{.greek-added}[9:35]{.aside}

ιδων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν εσκυλμενοι [ως]{.greek-added} [και]{.greek-omitted} [ερριμμενοι]{.greek-omitted} [ωσει]{.greek-omitted} προβατα μη εχοντα ποιμ[ε]{.unclear}ν[α]{.unclear}[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως εκβαλη εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} προσκαλεσαμενος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους δωδεκα μαθητας αυτου εδωκεν αυτοις εξουσιαν [κατα]{.greek-added} πνευματων ακαθαρτων ωστε εκβαλλειν αυτα και θεραπευειν πασαν νοσον και πασαν μαλακιαν [υπερβα]{.greek-added} [εμπροσθεν]{.greek-added}[10:1]{.aside}

των δε δωδεκα αποστολων τα ονοματα εστιν ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου ιακωβος ο του [ζεβεδαιου]{.greek-omitted} [ζεβεδεου]{.greek-added} και ιωαννης ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και λεββαιος ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο [κανανιτης]{.greek-omitted} [καναναιος]{.greek-added} και ιουδας [ο]{.greek-added} ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους [δωδεκα]{.greek-omitted} [δοδεκα]{.greek-added} απεστειλεν ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν [σαμαρειτων]{.greek-omitted} [σαμαριτων]{.greek-added} μη εισελθητε[10:5]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} δε μαλλον προς τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρυσσετε λεγοντες οτι ηγγικεν η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας θεραπευετε λεπρους καθαριζετε δαιμονια εκβαλλετε [νεκρους]{.greek-added} [εγειρετε]{.greek-added} δωρεαν ελαβετε δωρεαν [δοτε]{.greek-omitted} [δωτε]{.greek-added}[10:8]{.aside}

μη κτησησθε χρυσον [μηδε]{.greek-omitted} [μητε]{.greek-added} αργυρον [μηδε]{.greek-omitted} [μητε]{.greek-added} χαλκον [εις]{.greek-omitted} [επι]{.greek-added} τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε [ραβδους]{.greek-omitted} [ραβδον]{.greek-added} αξιος γαρ ο εργατης της τροφης αυτου εστιν[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις εν αυτη αξιος εστιν κακει μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν ασπασασθε αυτην[10:12]{.aside}

και εαν μεν η η οικια αξια [ελθετω]{.greek-omitted} [ελθατω]{.greek-added} η ειρηνη υμων [επ]{.corr} [αυτην]{.corr} [εαν]{.corr} [δε]{.corr} [μη]{.corr} [η]{.greek-omitted} [αξια]{.corr} [η]{.corr} [ειρηνη]{.corr} [υμων]{.corr} προς υμας επιστραφητω[10:13]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της οικιας η της πολεως εκεινης [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον κονιορτον των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν ανεκτοτερον εσται γη σοδομων και [γομορρων]{.greek-omitted} [γομορρας]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων γινεσθε ουν [φρονιμοι]{.greek-omitted} [φρονημοι]{.greek-added} [ωσει]{.greek-added} [ως]{.greek-omitted} [οι]{.greek-omitted} οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας [δε]{.greek-omitted} και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε [παραδιδωσιν]{.greek-omitted} [παραδωσουσιν]{.greek-added} [υμας]{.greek-omitted} [ημας]{.greek-added} μη μεριμνησητε πως η τι λαλησητε [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} γαρ υμιν εν εκεινη τη ωρα τι [λαλησετε]{.greek-omitted} [λαλησητε]{.greek-added}[10:19]{.aside}

ου γαρ υμεις εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

[παραδωσει]{.greek-omitted} [παραδωσοι]{.greek-added} δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος [ουτος]{.greek-omitted} [ουτως]{.greek-added} σωθησεται[10:22]{.aside}

οταν δε διωκωσιν υμας εν τη πολει ταυτη φευγετε εις την αλλην [καν]{.greek-added} [εκ]{.greek-added} [ταυτης]{.greek-added} [διωκωσιν]{.greek-added} [φευγετε]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [ετεραν]{.greek-added} αμην γαρ λεγω υμιν ου μη τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ εστιν μαθητης υπερ [τον]{.greek-omitted} [των]{.greek-added} διδασκαλον ουδε δουλος υπερ τον [κυριον]{.greek-abbr} αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα γενηται [ως]{.greek-omitted} [ος]{.greek-added} ο διδασκαλος αυτου και ο δουλος ως ο [κυριος]{.greek-abbr} αυτου ει τον οικοδεσποτην βεελζεβουλ [εκαλεσαν]{.greek-omitted} [επεκαλεσαντο]{.greek-added} ποσω μαλλον τους [οικειακους]{.greek-omitted} [οικιακους]{.greek-added} αυτου[10:25]{.aside}

μη ουν φοβηθητε αυτους [ουδε]{.greek-added} [ουδεν]{.corr} γαρ εστιν κεκαλυμμενον ο ουκ [αποκαλυφθησεται]{.greek-omitted} [απολυφθησεται]{.greek-added} και κρυπτον ο ου γνωσθησεται[10:26]{.aside}

ο λεγω υμιν εν τη σκοτια ειπατε εν τω φωτι και ο εις το ους [ακουετε]{.greek-omitted} [ηκουσατε]{.greek-added} κηρυξατε επι των [δωματων]{.greek-omitted} [δοματων]{.greek-added}[10:27]{.aside}

και μη φοβεισθε απο των αποκτενοντων το σωμα την δε ψυχην μη δυναμενων αποκτειναι φοβηθητε δε μαλλον τον δυναμενον [και]{.greek-omitted} την ψυχην και το σωμα απολεσαι εν γεεννη[10:28]{.aside}

ουχι δυο στρουθια ασσαριου πωλειται και εν εξ αυτων ου πεσειται επι την γην ανευ του [πατρος]{.greek-abbr} υμων[10:29]{.aside}

υμων δε και αι τριχες της κεφαλης πασαι ηριθμημεναι [εισιν]{.greek-omitted} [εισι]{.greek-added}[10:30]{.aside}

μη ουν φοβηθητε πολλων στρουθιων διαφερετε υμεις[10:31]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} πας ουν οστις ομολογησει εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:32]{.aside}

οστις δ αν αρνησηται με εμπροσθεν των [ανθρωπων]{.greek-abbr} αρνησομαι αυτον καγω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:33]{.aside}

μη [νομισητε]{.greek-omitted} [νομησητε]{.greek-added} οτι ηλθον [ειρηνην]{.greek-added} βαλειν [ειρηνην]{.greek-omitted} επι την γην ουκ ηλθον βαλειν [ηρηνη]{.greek-added} [ειρηνην]{.greek-omitted} [[ειρηνη]{.corr}]{.greek-added} αλλα [μαχην]{.greek-added} [και]{.greek-added} μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι ανθρωπον κατα του [πατρος]{.greek-abbr} αυτου και [θυγατερα]{.greek-omitted} [θυγατεραν]{.greek-added} κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και εχθροι του [ανθρωπου]{.greek-abbr} οι [οικειακοι]{.greek-omitted} [οικιακοι]{.greek-added} αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ εστιν μου αξιος και ο φιλων [υιον]{.greek-abbr} η [θυγατεραν]{.greek-added} [υπερ]{.greek-added} [εμε]{.greek-added} [ουκ]{.greek-added} [εστιν]{.greek-added} [μου]{.greek-added} [αξιος]{.greek-added} [ο]{.greek-added} [φιλων]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [η]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [υπερ]{.greek-added} [εμε]{.greek-added} [ουκ]{.greek-added} [εστιν]{.greek-added} [μου]{.greek-added} [αξιος]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [φιλων]{.greek-added} [η]{.greek-added} [[υιον]{.greek-abbr}]{.greek-added} [η]{.greek-added} θυγατερα υπερ εμε ουκ εστιν μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ εστιν μου αξιος [και]{.greek-added} [ος]{.greek-added} [ου]{.greek-added} [λαμβανει]{.greek-added} [τον]{.greek-added} [[σταυρον]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [ακολουθει]{.greek-added} [οπισω]{.greek-added} [μου]{.greek-added} [ουκ]{.greek-added} [εστιν]{.greek-added} [μου]{.greek-added} [αξιος]{.greek-added}[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος πρ[ο]{.unclear}φητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψεται[10:41]{.aside}

και ος εαν [ποτιση]{.greek-omitted} [ποτηση]{.greek-added} ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεσει]{.greek-added} τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις [δωδεκα]{.greek-omitted} [δ[ο]{.unclear}δεκα]{.greek-added} μαθηταις αυτου μετεβη εκειθεν του [κηρυσσειν]{.greek-added} [και]{.greek-added} διδασκειν [και]{.greek-omitted} [κηρυσσειν]{.greek-omitted} εν ταις πολεσιν αυτων[11:1]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ακουσας]{.greek-added} ο [δε]{.greek-omitted} ιωαννης [ακουσας]{.greek-omitted} εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον [προσδοκωμεν]{.greek-omitted} [προσδωκωμεν]{.greek-added}[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι αναβλεπουσιν και [χωλοι]{.greek-omitted} [χολοι]{.greek-added} περιπατουσιν [λεπροι]{.greek-omitted} [καθαριζονται]{.greek-omitted} και [κωφοι]{.greek-omitted} [ακουουσιν]{.greek-omitted} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και [μ]{.unclear}ακαριος εστιν ος εαν μη [σ]{.unclear}κανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωανν[ο]{.unclear}υ τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} εις την ερημον θεασασθαι [καλαμον]{.greek-omitted} [κα[λ]{.unclear}α]{.greek-added} [μον]{.greek-added} υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

[ουτος]{.greek-omitted} [ουτως]{.greek-added} γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ [εγηγερται]{.greek-omitted} [εγειγερται]{.greek-added} εν γεννητοις γυναικων μειζων ιωαννου του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων [ιωαννου]{.greek-omitted} [ιαννου]{.greek-added} του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως ιωαννου προεφητευσαν[11:13]{.aside}

και ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια εστιν παιδιοις εν [αγοραις]{.greek-omitted} [αγορα]{.greek-added} καθημενοις και [προσφωνουσιν]{.greek-omitted} [προσφωνουσι]{.greek-added} τοις [εταιροις]{.greek-omitted} [ετεροις]{.greek-added} αυτων[11:16]{.aside}

και λεγουσιν ηυλησαμεν υμιν και ουκ ωρχησασθε εθρηνησαμεν υμιν και ουκ εκοψασθε[11:17]{.aside}

ηλθεν γαρ ιωαννης μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης [φιλος]{.greek-added} τελωνων [φιλος]{.greek-omitted} και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης [παντων]{.greek-added}[11:19]{.aside}

τοτε ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ονειδιζειν τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χοραζειν]{.greek-added} ουαι σοι [βηθσαιδα]{.greek-omitted} [βιθσαιδα]{.greek-added} οτι [ει]{.greek-omitted} εν τυρω και [σιδωνι]{.greek-omitted} [σιδονι]{.greek-added} εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι αν εν σακκω και σποδω [καθημεναι]{.greek-added} μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και [σιδωνι]{.greek-omitted} [σιδονι]{.greek-added} ανεκτοτερον εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ [η]{.greek-omitted} [μη]{.greek-added} εως [του]{.greek-omitted} [ουρανου]{.greek-abbr} [υψωθεισα]{.greek-omitted} [υψωθηση]{.greek-added} εως αδου [καταβιβασθηση]{.greek-omitted} [καταβηση]{.greek-added} οτι ει εν σοδομοις εγενοντο αι δυναμεις αι γενομεναι εν σοι εμειναν αν μεχρι της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι γη σοδομων ανεκτοτερον εσται εν ημερα κρισεως η σοι[11:24]{.aside}

εν εκεινω τω καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο [σοφων]{.greek-omitted} [σωφων]{.greek-added} και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι παρεδοθη υπο του [πατρος]{.greek-abbr} μου και ουδεις επιγινωσκει τον [υιον]{.greek-abbr} ει [μη]{.greek-omitted} [μι]{.greek-added} ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο [υιος]{.greek-abbr} και ω [εαν]{.greek-omitted} [αν]{.greek-added} βουληται ο [υιος]{.greek-abbr} αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι [κοπιωντες]{.greek-omitted} [κοποιωντες]{.greek-added} και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} αναπαυσιν ταις ψυχαις [υμων]{.greek-omitted} [ημων]{.greek-added}[11:29]{.aside}

ο γαρ ζυγος μου χρηστος και το φορτιον μου ελαφρον εστιν[11:30]{.aside}

### Chapter 12

εν εκεινω τω καιρω επορευθη ο [ιησους]{.greek-abbr} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων οι δε μαθηται αυτου επεινασαν και [ηρξατο]{.greek-added} [ηρξαντο]{.corr} τιλλειν σταχυας και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντες ειπον αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ποιειν εν σαββατω[12:2]{.aside}

ο δε ειπεν αυτοις ουκ ανεγνωτε τι εποιησεν [δαυιδ]{.greek-abbr} οτε επεινασεν [αυτος]{.greek-omitted} και οι μετ αυτου[12:3]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} [επι]{.greek-added} [αβιαθαρ]{.greek-added} [αρχιερε[ως]{.unclear}]{.greek-added} και τους αρτους της προθεσεως εφαγεν ους ουκ εξον ην αυτω φαγειν ουδε τοις μετ αυτου ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} μονοις[12:4]{.aside}

η ουκ ανεγνωτε εν τω νομω οτι τοις σαββασιν οι ιερεις εν τω ιερω το σαββατον βεβηλουσιν και αναιτιοι εισιν[12:5]{.aside}

λεγω δε υμιν οτι του ιερου μειζον εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε τι εστιν ελεον θελω και ου θυσιαν ουκ αν κατεδικασατε τους αναιτιους[12:7]{.aside}

[κυριος]{.greek-abbr} γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} του σαββατου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} ην [εκει]{.greek-added} [εχων]{.greek-added} την χειρα [εχων]{.greek-omitted} ξηραν και επηρωτησαν αυτον λεγοντες ει εξεστιν τοις σαββασιν θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις εσται εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει αυτο και [εγερει]{.greek-omitted} [εγειρει]{.greek-added}[12:11]{.aside}

ποσω ουν διαφερει [ανθρωπος]{.greek-abbr} προβατου ωστε [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} καλως ποιειν[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και εξετεινεν [την]{.greek-added} [χειρα]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

οι δε φαρισαιοι συμβουλιον ελαβον κατ αυτου εξελθοντες οπως αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηκολουθησαν]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [οχλοι]{.greek-added} [πολλοι]{.greek-added} [και]{.greek-added} [εθεραπευσεν]{.greek-added} [αυτους]{.greek-added} [παντας]{.greek-added}[12:15]{.aside}

και [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} αυτοις ινα μη φανερον αυτον ποιησωσιν[12:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον [ηρετισα]{.greek-omitted} [ηρετησα]{.greek-added} ο αγαπητος μου εις ον [ευδοκησεν]{.greek-omitted} [ηυδοκησεν]{.greek-added} η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει ουδε ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον [τυφομενον]{.greek-omitted} ου σβεσει εως αν εκβαλη εις νικος την κρισιν[12:20]{.aside}

και [επι]{.greek-added} τω ονοματι αυτου [εθνη]{.greek-omitted} ελπιουσιν[12:21]{.aside}

τοτε προσηνεχθη αυτω δαιμονιζομενος τυφλος και [κωφος]{.greek-omitted} [κοφος]{.greek-added} και εθεραπευσεν αυτον ωστε τον τυφλον και [κωφον]{.greek-omitted} [[κ]{.unclear}οφον]{.greek-added} [και]{.greek-omitted} λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο παντες οι οχλοι και ελεγον μητι ουτος εστιν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες ειπον [ουτος]{.greek-omitted} [ουτως]{.greek-added} ουκ εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

ειδως δε ο [ιησους]{.greek-abbr} τας [ενθυμησεις]{.greek-omitted} [ενθυμισεις]{.greek-added} αυτων ειπεν αυτοις πασα βασιλεια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτοις]{.greek-added} ερημουται και πασα πολις η οικια μερισθεισα καθ εαυτης ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν εκβαλλει εφ εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

και ει εγω εν βεελζεβουλ εκβαλλω τα δαιμονια οι υιοι υμων [εν]{.greek-omitted} [τινι]{.greek-omitted} [εκβαλλουσιν]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [αυτοι]{.greek-omitted} [υμων]{.greek-omitted} εσονται κριται[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} εγω εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

η πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου [διαρπασαι]{.greek-omitted} [αρπασαι]{.greek-added} εαν μη πρωτον δηση τον ισχυρον και τοτε την οικιαν αυτου [διαρπασει]{.greek-omitted} [διαρπαση]{.greek-added}[12:29]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} ο μη ων μετ εμου κατ εμου εστιν και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

δια τουτο λεγω υμιν πασα αμαρτια και βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} η δε του [πνευματος]{.greek-abbr} βλασφημια ουκ αφεθησεται τοις [ανθρωποις]{.greek-abbr}[12:31]{.aside}

και ος εαν ειπη λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω ος δ αν ειπη κατα του [πνευματος]{.greek-abbr} του αγιου ουκ [αφε]{.greek-added} [αφεθησεται]{.greek-omitted} [θησεται]{.greek-added} αυτω ουτε εν [τουτω]{.greek-added} τω [νυν]{.greek-omitted} αιωνι ουτε εν τω μελλοντι[12:32]{.aside}

η ποιησατε το δενδρον καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον γινωσκεται[12:33]{.aside}

γεννηματα εχιδνων πως [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} αγαθα [λαλειν]{.greek-omitted} [ποιειν]{.greek-added} πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου [της]{.greek-added} [καρδιας]{.greek-added} εκβαλλει [τα]{.greek-added} αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου [εκβαλλει]{.greek-omitted} [της]{.greek-added} [καρδιας]{.greek-added} [αυτου]{.greek-added} [προσφερει]{.greek-added} [τα]{.greek-added} πονηρα[12:35]{.aside}

λεγω δε υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσουσι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των [λογων]{.greek-omitted} [λογον]{.greek-added} σου δικαιωθηση και εκ των [λογων]{.greek-omitted} [λογον]{.greek-added} σου καταδικασθηση[12:37]{.aside}

τοτε απεκριθησαν [αυτω]{.greek-added} τινες των γραμματεων και φαρισαιων λεγοντες διδασκαλε [θελομεν]{.greek-omitted} [θελωμεν]{.greek-added} απο σου σημειον [ιδειν]{.greek-omitted} [ειδειν]{.greek-added}[12:38]{.aside}

ο δε αποκριθεις ειπεν αυτοις γενεα πονηρα και [μοιχαλλης]{.greek-added} [μοιχαλις]{.greek-omitted} [[μοιχαλλις]{.corr}]{.greek-added} σημειον επιζητει και σημειον ου [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} αυτη ει [μη]{.greek-omitted} [μι]{.greek-added} το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ γαρ ην ιωνας εν τη κοιλ[ι]{.greek-supplied}α του κητους τρεις ημερας και τρεις νυκτας ουτως εσται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τη καρδια της γης τρεις ημερας και τρεις νυκτας[12:40]{.aside}

ανδρες [νινευιται]{.greek-omitted} [νηνευη]{.greek-added} αναστησονται εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

[βασιλισσα]{.greek-omitted} [βασιλεισσα]{.greek-added} [νοτου]{.greek-omitted} [νωτου]{.greek-added} εγερθησεται εν τη κρισει μετα της γενεας ταυτης και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν [σολωμοντος]{.greek-added} [σολομωνος]{.greek-omitted} [[σολωμωντος]{.corr}]{.greek-added} και ιδου πλειον [σολομωνος]{.greek-omitted} [σολομωντος]{.greek-added} ωδε[12:42]{.aside}

οταν δε το ακαθαρτον πνευμα εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητουν αναπαυσιν και ουχ ευρισκει[12:43]{.aside}

τοτε λεγει επιστρεψω εις τον οικον μου οθεν [εξηλθον]{.greek-omitted} [εξηλθων]{.greek-added} και [εαν]{.greek-added} [ελθον]{.greek-omitted} [ελθων]{.greek-added} [ευρισκει]{.greek-omitted} [ευρει]{.greek-added} σχολαζοντα σεσαρωμενον και [κεκοσμημενον]{.greek-omitted} [κεκοσμιμενον]{.greek-added}[12:44]{.aside}

τοτε πορευεται και [παραλαμβανει]{.greek-omitted} [παραλαμβαννει]{.greek-added} μεθ εαυτου [ετερα]{.greek-added} επτα [ετερα]{.greek-omitted} [πνευματα]{.greek-omitted} πονηροτερα εαυτου και εισελθοντα κατοικει εκει και γινεται τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου [χειρονα]{.greek-omitted} [χειρωνα]{.greek-added} των [πρωτων]{.greek-omitted} [πρωτον]{.greek-added} ουτως εσται και τη γενεα ταυτη τη πονηρα[12:45]{.aside}

[ετη]{.greek-added} [ετι]{.corr} δε αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και οι αδελφοι αυτου [ειστηκεισαν]{.greek-omitted} [ιστηκησαν]{.greek-added} εξω ζητουντες αυτω λαλησαι[12:46]{.aside}

ειπεν δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εξω [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} ζητουντες σοι λαλησαι[12:47]{.aside}

ο δε αποκριθεις ειπεν τω ειποντι αυτω τις εστιν η [μητηρ]{.greek-abbr} μου [και]{.greek-omitted} [η]{.greek-added} τινες εισιν οι αδελφοι μου[12:48]{.aside}

οστις γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr} αυτος μου αδελφος και αδελφη και [μητηρ]{.greek-abbr} εστιν[12:50]{.aside}

### Chapter 13

εν δε τη ημερα εκεινη εξελθων ο [ιησους]{.greek-abbr} απο της οικιας [εκαθητο]{.greek-omitted} [εκαθιτο]{.greek-added} παρα την θαλασσαν[13:1]{.aside}

και συνηχθησαν προς αυτον οχλοι πολλοι ωστε αυτον εις [το]{.greek-omitted} πλοιον εμβαντα [καθησθαι]{.greek-omitted} [καθισαι]{.greek-added} και πας ο οχλος επι τον αιγιαλον ειστηκει[13:2]{.aside}

και ελαλησεν αυτοις [πολλα]{.greek-omitted} εν παραβολαις [πολλα]{.greek-added} λεγων ιδου εξηλθεν ο σπειρων του [σπειρειν]{.greek-omitted} [σπειραι]{.greek-added} [τον]{.greek-added} [σπορον]{.greek-added}[13:3]{.aside}

και εν τω [σπειρειν]{.greek-omitted} [σπειρην]{.greek-added} αυτον α μεν επεσεν παρα την οδον και ηλθεν τα πετεινα [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν αυτα[13:4]{.aside}

αλλα δε επεσεν επι τα πετρωδη οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[13:5]{.aside}

[ηλιου]{.greek-omitted} [ηλι]{.greek-added} [ου]{.greek-added} δε ανατειλαντος εκαυματισθη και δια το μη εχειν [ριζαν]{.greek-omitted} [βαθος]{.greek-added} [ριζης]{.greek-added} εξηρανθη[13:6]{.aside}

αλλα δε επεσεν επι τας ακανθας και ανεβησαν αι ακανθαι και απεπνιξαν αυτα[13:7]{.aside}

αλλα δε επεσεν επι την γην την καλην και εδιδου καρπον ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:8]{.aside}

ο εχων ωτα ακουειν ακουετω[13:9]{.aside}

και προσελθοντες οι μαθηται ειπον αυτω δια τι εν παραβολαις λαλεις αυτοις[13:10]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι υμιν [δεδοται]{.greek-omitted} [δεδοτε]{.greek-added} γνωναι τα μυστηρια της βασιλειας των [ουρανων]{.greek-abbr} εκεινοις δε ου δεδοται[13:11]{.aside}

οστις γαρ εχει δοθησεται [αυτω]{.greek-omitted} [και]{.greek-omitted} [περισσευθησεται]{.greek-omitted} οστις δε ουκ εχει και ο εχει αρθησεται απ αυτου[13:12]{.aside}

δια τουτο εν παραβολαις αυτοις λαλω οτι βλεποντες ου βλεπουσιν και ακουοντες ουκ ακουουσιν ουδε συνιουσιν[13:13]{.aside}

και αναπληρουται αυτοις η προφητεια ησαιου η λεγουσα ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες βλεψετε και ου μη ιδητε[13:14]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις ωσιν βαρεως ηκουσαν και τους οφθαλμους αυτων [εκαμμυσαν]{.greek-omitted} [εκαμυσαν]{.greek-added} μηποτε ιδωσιν τοις οφθαλμοις και τοις ωσιν ακουσωσιν και τη καρδια [συνωσιν]{.greek-omitted} [συνιωσιν]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και [ιασομαι]{.greek-omitted} [ιασωμαι]{.greek-added} αυτους[13:15]{.aside}

υμων δε μακαριοι οι οφθαλμοι οτι βλεπουσιν και τα ωτα υμων οτι [ακουει]{.greek-omitted} [ακουειν]{.greek-added}[13:16]{.aside}

αμην [γαρ]{.greek-omitted} λεγω υμιν [τοις]{.greek-added} [ακουουσιν]{.greek-added} οτι πολλοι προφηται και δικαιοι επεθυμησαν ιδειν α βλεπετε και ουκ [ειδον]{.greek-omitted} [ιδον]{.greek-added} και [ακουσαι]{.greek-omitted} [ακουσε]{.greek-added} α ακουετε και ουκ ηκουσαν[13:17]{.aside}

υμεις ουν ακουσατε την παραβολην του [σπειροντος]{.greek-omitted} [σπειραντος]{.greek-added}[13:18]{.aside}

παντος ακουοντος τον λογον της βασιλειας και μη [συνιεντος]{.greek-omitted} [συνιοντος]{.greek-added} [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} ο πονηρος και αρπαζει το εσπαρμενον εν τη καρδια αυτου ουτος εστιν ο παρα την οδον σπαρεις[13:19]{.aside}

ο δε επι τα πετρωδη σπαρεις ουτος εστιν ο τον λογον ακουων και ευθυς μετα χαρας λαμβανων αυτον[13:20]{.aside}

ουκ εχει δε ριζαν εν εαυτω αλλα [προσκαιρος]{.greek-omitted} [προσκερος]{.greek-added} εστιν γενομενης δε [θλιψεως]{.greek-omitted} [θληψεως]{.greek-added} η διωγμου δια τον λογον [ευθυς]{.greek-omitted} [ευθυ]{.greek-added} σκανδαλιζεται[13:21]{.aside}

ο δε εις τας ακανθας σπαρεις ουτος εστιν ο τον λογον ακουων και η μεριμνα του αιωνος τουτου και η απατη του πλουτου συμπνιγει τον λογον και ακαρπος γινεται[13:22]{.aside}

ο δε επι την [καλην]{.greek-added} γην [την]{.greek-omitted} [καλην]{.greek-omitted} σπαρεις ουτος εστιν ο τον λογον ακουων και συνιων ος δη καρποφορει και ποιει ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:23]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} σπειροντι καλον σπερμα εν τω αγρω αυτου[13:24]{.aside}

εν δε τω καθευδειν τους [ανθρωπους]{.greek-abbr} ηλθεν αυτου ο εχθρος και εσπειρεν ζιζανια ανα μεσον του σιτου και απηλθεν[13:25]{.aside}

οτε δε εβλαστησεν ο χορτος και καρπον εποιησεν τοτε εφανη και τα ζιζανια[13:26]{.aside}

προσελθοντες δε οι δουλοι του οικοδεσποτου ειπον αυτω [κυριε]{.greek-abbr} ουχι καλον σπερμα εσπειρας εν τω σω αγρω ποθεν ουν εχει [ζιζανια]{.greek-omitted} [ζηζανια]{.greek-added}[13:27]{.aside}

ο δε εφη αυτοις εχθρος [ανθρωπος]{.greek-abbr} τουτο εποιησεν οι δε δουλοι ειπον αυτω θελεις ουν απελθοντες [συλλεξομεν]{.greek-omitted} [συλλεξωμεν]{.greek-added} αυτα[13:28]{.aside}

ο δε εφη ου [μηποτε]{.greek-omitted} [μη]{.greek-added} συλλεγοντες τα ζιζανια εκριζωσητε αμα αυτοις τον σιτον[13:29]{.aside}

αφετε [ουν]{.greek-added} [συναυξανεσθαι]{.greek-omitted} [αυξανεσθαι]{.greek-added} αμφοτερα μεχρι του θερισμου και εν [τω]{.greek-added} καιρω του θερισμου ερω τοις θερισταις συλλεξατε πρωτον τα ζιζανια και δησατε αυτα εις δεσμας προς το κατακαυσαι αυτα τον δε σιτον [συναγαγετε]{.greek-omitted} [συναγαγε]{.greek-added} [τε]{.greek-added} εις την αποθηκην μου[13:30]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ομοια εστιν η βασιλεια των ουρανων [κοκκω]{.greek-omitted} [κοκκο]{.greek-added} [σιναπεως]{.greek-omitted} [συναπεος]{.greek-added} ον λαβων [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο [μικροτερον]{.greek-omitted} [μικρο]{.greek-added} μεν εστιν παντων των σπερματων οταν δε αυξηθη [μειζον]{.greek-omitted} [μειζων]{.greek-added} των λαχανων εστιν και γινεται δενδρον ωστε ελθειν τα πετεινα του [ουρανου]{.greek-abbr} και κατασκηνουν εν τοις κλαδοις αυτου[13:32]{.aside}

αλλην παραβολην ελαλησεν αυτοις ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} ζυμη ην λαβουσα γυνη εκρυψεν εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33]{.aside}

ταυτα παντα ελαλησεν ο [ιησους]{.greek-abbr} εν παραβολαις τοις οχλοις και χωρις παραβολης ουκ [ελαλει]{.greek-omitted} [ελαλησεν]{.greek-added} αυτοις[13:34]{.aside}

οπως πληρωθη το ρηθεν δια του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου ερευξομαι [κεκρυμενα]{.greek-added} [κεκρυμμενα]{.corr} απο καταβολης κοσμου[13:35]{.aside}

τοτε αφεις τους οχλους ηλθεν εις την οικιαν ο [ιησους]{.greek-abbr} και προσηλθον αυτω οι μαθηται αυτου λεγοντες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε [αποκριθεις]{.greek-omitted} ειπεν αυτοις ο σπειρων το καλον σπερμα εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του πονηρου[13:38]{.aside}

ο δε εχθρος ο [σπειρας]{.greek-omitted} [σπειρον]{.greek-added} αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστιν οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν [συλλεγεται]{.greek-omitted} τα ζιζανια [συλλεγεται]{.greek-added} και πυρι καιεται ουτως εσται εν τη συντελεια του αιωνος τουτου[13:40]{.aside}

αποστελει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι [εκλαμψουσιν]{.greek-omitted} [εκλαψουσιν]{.greek-added} ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν [ομοια]{.greek-added} [εστιν]{.greek-added} [η]{.greek-added} [βασιλεια]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added} ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν [τω]{.greek-omitted} αγρω ον ευρων [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας αυτου υπαγει και παντα οσα εχει πωλει και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

[ος]{.greek-omitted} ευρων [δε]{.greek-added} ενα πολυτιμον μαργαριτην απελθων πεπρακεν παντα οσα ειχεν και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη [βληθειση]{.greek-omitted} [βληθηση]{.greek-added} εις την θαλασσαν και εκ παντος γενους συναγαγουση[13:47]{.aside}

ην οτε επληρωθη [αναβιβασαντες]{.greek-omitted} [αναβηβασαντες]{.greek-added} επι τον αιγιαλον και [καθισαντες]{.greek-omitted} [καθησαντες]{.greek-added} συνελεξαν τα καλα εις [αγγεια]{.greek-omitted} [αγγια]{.greek-added} τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται εν τη συντελεια του αιωνος εξελευσονται [οι]{.greek-omitted} αγγελοι και [αφοριουσιν]{.greek-omitted} [αφοριουσι]{.greek-added} τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο [κλαυθμος]{.greek-omitted} [κλαθμος]{.greek-added} και ο βρυγμος των οδοντων[13:50]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[13:51]{.aside}

ο δε ειπεν αυτοις δια τουτο πας γραμματευς μαθητευθεις [εις]{.greek-omitted} [την]{.greek-omitted} [τη]{.greek-added} [βασιλειαν]{.greek-omitted} [βασιλεια]{.greek-added} των [ουρανων]{.greek-abbr} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη [οστις]{.greek-omitted} [οστης]{.greek-added} εκβαλλει εκ του θησαυρου αυτου καινα και παλαια[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας μετηρεν εκειθεν[13:53]{.aside}

και ελθων εις την πατριδα αυτου εδιδασκεν [αυ]{.greek-added} [αυτους]{.greek-omitted} [τους]{.greek-added} εν τη συναγωγη αυτων ωστε εκπληττεσθαι αυτους και λεγειν ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} η σοφια αυτη και αι δυναμεις[13:54]{.aside}

ουχ ουτος εστιν ο του τεκτονος [υιος]{.greek-abbr} ουχι η [μητηρ]{.greek-abbr} αυτου λεγεται μαριαμ και οι αδελφοι αυτου ιακωβος και ιωσης και σιμων και ιουδας[13:55]{.aside}

[και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [αυτου]{.greek-omitted} [ουχι]{.greek-omitted} [πασαι]{.greek-omitted} [προς]{.greek-omitted} [ημας]{.greek-omitted} [εισιν]{.greek-omitted} ποθεν ουν τουτω ταυτα παντα[13:56]{.aside}

και εσκανδαλιζοντο εν αυτω ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ εστιν προφητης ατιμος ει μη εν τη πατριδι αυτου και εν τη οικια αυτου[13:57]{.aside}

και ουκ [εποιησεν]{.greek-omitted} [επιησεν]{.greek-added} εκει δυναμεις πολλας δια την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο τετραρχης την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και ειπεν τοις παισιν αυτου [ουτως]{.greek-added} [ουτος]{.corr} εστιν ιωαννης ο βαπτιστης αυτος ηγερθη απο των νεκρων και δια τουτο αι δυναμεις ενεργουσιν εν αυτω[14:2]{.aside}

ο γαρ ηρωδης κρατησας τον ιωαννην εδησεν [αυτων]{.greek-added} [αυτον]{.corr} και εθετο εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου[14:3]{.aside}

ελεγεν γαρ αυτω ο ιωαννης ουκ εξεστιν σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων δε αγομενων του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και ηρεσεν τω ηρωδη[14:6]{.aside}

οθεν μεθ ορκου [ωμολογησεν]{.greek-omitted} [αυτη]{.greek-omitted} [ομωσεν]{.greek-added} [αυτου]{.greek-added} δουναι ο εαν [αιτησηται]{.greek-omitted} [αιτησειται]{.greek-added}[14:7]{.aside}

η δε [προβιβασθεισα]{.greek-omitted} [προβηβασθησα]{.greek-added} υπο της [μητρος]{.greek-abbr} αυτης δος μοι φησιν ωδε επι πινακι την κεφαλην ιωαννου του βαπτιστου[14:8]{.aside}

και ελυπηθη ο βασιλευς δια δε τους ορκους και τους συνανακειμενους εκελευσεν δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλισε]{.greek-added} τον ιωαννην εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι πινακ[ι]{.unclear} και εδοθη τω κορασιω και ηνεγκεν τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το σωμα και εθαψαν αυτο και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

[και]{.greek-omitted} ακουσας [δε]{.greek-added} ο [ιησους]{.greek-abbr} ανεχωρησεν εκειθεν εν πλοιω εις ερημον τοπον κατ ιδιαν και ακουσαντες οι οχλοι ηκολουθησαν αυτω [πεζη]{.greek-omitted} [πεζι]{.greek-added} απο των πολεων[14:13]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} εξελθων ο [ιησους]{.greek-abbr} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις και εθεραπευσεν τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται αυτου λεγοντες ερημος εστιν ο τοπος και η ωρα ηδη παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας κωμας [αγορασωσιν]{.greek-omitted} [αγωρασωσιν]{.greek-added} εαυτοις βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου χρειαν εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} ωδε ει [μ]{.unclear}η πεντε αρτους και δυο [ιχθυας]{.greek-omitted} [οιχθυας]{.greek-added}[14:17]{.aside}

ο δε ειπεν φερετε μοι αυτους ωδε[14:18]{.aside}

και [κελευσας]{.greek-omitted} [εκελευσεν]{.greek-added} τους οχλους [ανακλιθηναι]{.greek-omitted} [ανακληθηναι]{.greek-added} επι τους χορτους [και]{.greek-added} λαβων τους πεντε αρτους και τους δυο [ιχθυας]{.greek-omitted} [οιχθυας]{.greek-added} αναβλεψας εις τον [ουρανον]{.greek-abbr} ευλογησεν και κλασας [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν [το]{.greek-omitted} [των]{.greek-added} περισσευον των κλασματων δωδεκα [κοφινους]{.greek-omitted} [κωφινους]{.greek-added} [πληρεις]{.greek-omitted} [πληρις]{.greek-added}[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες [ωσει]{.greek-omitted} [ωση]{.greek-added} πεντακισχιλιοι χωρις γυναικων και παιδιων[14:21]{.aside}

και ευθεως ηναγκασεν ο [ιησους]{.greek-abbr} τους μαθητας εμβηναι εις το πλοιον και προαγειν αυτον εις το περαν εως ου απολυση τους οχλους [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηναγκασεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [τους]{.greek-added} [μαθητας]{.greek-added} [αυτου]{.greek-added} [εμβηναι]{.greek-added} [εις]{.greek-added} [το]{.greek-added} [πλοιον]{.greek-added} [και]{.greek-added} [προαγειν]{.greek-added} [αυτον]{.greek-added} [εις]{.greek-added} [το]{.greek-added} [περαν]{.greek-added} [εως]{.greek-added} [ου]{.greek-added} [απολυση]{.greek-added} [τους]{.greek-added} [οχλους]{.greek-added}[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος κατ ιδιαν [προσ]{.greek-added} [προσευξασθαι]{.greek-omitted} [ευξασθαι]{.greek-added} οψιας δε γενομενη[ς]{.unclear} μονος ην εκει[14:23]{.aside}

το δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος [απηλθεν]{.greek-omitted} [ηλθεν]{.greek-added} προς αυτους ο [ιησους]{.greek-abbr} περιπατων επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασσαν]{.greek-added}[14:25]{.aside}

και ιδοντες αυτον οι μαθηται επι την θαλασσαν περιπατουντα εταραχθησαν λεγοντες οτι φαντασμα εστιν και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} λεγων θαρσειτε εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε αυτω ο πετρος ειπεν [κυριε]{.greek-abbr} ει συ ει κελευσον [με]{.greek-omitted} [μοι]{.greek-added} [ελθειν]{.greek-added} προς σε [ελθειν]{.greek-omitted} επι τα υδατα[14:28]{.aside}

ο δε ειπεν ελθε και καταβας [απο]{.greek-omitted} [εκ]{.greek-added} του πλοιου ο πετρος περιεπατησεν επι τα υδατα ελθειν προς [το]{.unclear}ν [ιησουν]{.greek-abbr}[14:29]{.aside}

[βλεπων]{.greek-omitted} [βλεπον]{.greek-added} δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι εκραξεν λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα επελαβετο αυτου και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω ελθοντες προσεκυνησαν αυτω λεγοντες αληθως [θεου]{.greek-abbr} [υιος]{.greek-abbr} ει[14:33]{.aside}

και διαπερασαντες ηλθον [εις]{.greek-omitted} [επι]{.greek-added} την γην [εις]{.greek-added} [γεννησαρετ]{.greek-omitted} [γεννησαρεθ]{.greek-added}[14:34]{.aside}

και επιγνοντες αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον [αψωνται]{.greek-omitted} [αψονται]{.greek-added} του κρασπεδου του ιματιου αυτου και οσοι [ηψαντο]{.greek-omitted} [ηψαν]{.greek-added} [αυτον]{.greek-added} διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτε προσερχονται τω [ιησου]{.greek-abbr} οι απο ιεροσολυμων γραμματεις και φαρισαιοι λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου παραβαινουσιν την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων ου γαρ νιπτονται τας χειρας αυτων οταν [αρτον]{.greek-omitted} [αρτων]{.greek-added} εσθιωσιν[15:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και υμεις παραβαινετε την εντολην του [θεου]{.greek-abbr} δια την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} ενετειλατο λεγων τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[15:4]{.aside}

υμεις δε λεγετε ος [αν]{.greek-omitted} [εαν]{.greek-added} ειπη τω [πατρι]{.greek-abbr} [η]{.greek-omitted} [και]{.greek-added} τη [μητρι]{.greek-abbr} δωρον ο [εαν]{.greek-omitted} [αν]{.greek-added} εξ εμου [ωφεληθης]{.greek-omitted} [οφεληθης]{.greek-added} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[και]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [τημησει]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [η]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} και ηκυρωσατε την εντολην του [θεου]{.greek-abbr} δια την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων[15:6]{.aside}

υποκριται καλως προεφητευσεν περι υμων ησαιας λεγων[15:7]{.aside}

εγγιζει μοι ο λαος ουτος τω στοματι αυτων και τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[15:8]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις ακουετε και συνιετε[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} [αλλα]{.greek-omitted} [το]{.greek-omitted} [εκπορευομενον]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [τουτο]{.greek-omitted} [κοινοι]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[15:11]{.aside}

τοτε προσελθοντες οι μαθηται αυτου ειπον αυτω οιδας οτι οι φαρισαιοι ακουσαντες τον λογον εσκανδαλισθησαν[15:12]{.aside}

ο δε αποκριθεις ειπεν πασα φυτεια ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο [ουρανιος]{.greek-abbr} εκριζωθησεται[15:13]{.aside}

αφετε αυτους [τυφλοι]{.greek-added} [εισιν]{.greek-added} οδηγοι [εισιν]{.greek-omitted} [τυφλοι]{.greek-omitted} τυφλων τυφλος δε [τυφλων]{.greek-added} [τυφλον]{.corr} εαν οδηγη αμφοτεροι [πεσουνται]{.greek-added} εις βοθυνον [πεσουνται]{.greek-omitted}[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν ακμην και υμεις ασυνετοι εστε[15:16]{.aside}

ουπω νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ της καρδιας εξερχεται κακεινα κοινοι τον [ανθρωπον]{.greek-abbr}[15:18]{.aside}

εκ γαρ της καρδιας εξερχονται διαλογισμοι πονηροι [πορνειαι]{.greek-added} [μοιχειαι]{.greek-added} φονοι [μοιχειαι]{.greek-omitted} [πορνειαι]{.greek-omitted} κλοπαι ψευδομαρτυριαι βλασφημιαι[15:19]{.aside}

ταυτα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr} το δε ανιπτοις χερσιν φαγειν ου κοινοι τον [ανθρωπον]{.greek-abbr}[15:20]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρη]{.greek-added} [σεν]{.greek-added} εις τα μερη τυρου και [σιδωνος]{.greek-omitted} [σιδονος]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [εισηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [μερη]{.greek-added} [τυρου]{.greek-added} [και]{.greek-added} [σιδονος]{.greek-added}[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα εκραυγασεν αυτω λεγουσα ελεησον με [κυριε]{.greek-abbr} υιε [δαυιδ]{.greek-abbr} η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε ουκ απεκριθη αυτη λογον και προσελθοντες οι μαθηται αυτου [ηρωτων]{.greek-omitted} [ηρωτον]{.greek-added} αυτον λεγοντες απολυσον αυτην οτι κραζει οπισθεν ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην ει μη εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

η δε ελθουσα [προσεκυνησεν]{.greek-omitted} [προσεκυνη]{.greek-added} αυτω λεγουσα [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [βοηθησον]{.greek-added} μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ εστιν καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε ειπεν ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των ψιχιων των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη ω γυναι μεγαλη σου η [πιστις]{.greek-omitted} [πιστης]{.greek-added} γενηθητω σοι ως [θελεις]{.greek-omitted} [θελης]{.greek-added} και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} ηλθεν παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος [εκαθητο]{.greek-omitted} [εκαθετο]{.greek-added} εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ εαυτων [κωφους]{.greek-added} [κυλλους]{.greek-added} χωλους τυφλους [κωφους]{.greek-omitted} [κυλλους]{.greek-omitted} και ετερους πολλους και ερριψαν αυτους παρα τους ποδας [του]{.greek-omitted} [αυτου]{.greek-added} [ιησου]{.greek-omitted} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους λαλουντας κυλλους υγιεις χωλους περιπατουντας και τυφλους βλεποντας και [εδοξασαν]{.greek-omitted} [εδοξαζον]{.greek-added} τον [θεον]{.greek-abbr} ισραηλ[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος [τους]{.greek-added} [μαθητας]{.greek-added} [ειπεν]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [προσκαλεσαμενος]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους μαθητας αυτου ειπεν σπλαγχνιζομαι επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις προσμενουσιν μοι και ουκ εχουσιν τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} και απολυσαι αυτους νηστεις ου θελω μηποτε [εκλυθωσιν]{.greek-omitted} [εκβλυθωσιν]{.greek-added} εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια [τοσουτοι]{.greek-added} αρτοι [τοσουτοι]{.greek-omitted} ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και εκελευσεν τοις οχλοις αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας εκλασεν και εδωκεν τοις μαθηταις αυτου οι δε μαθηται [τω]{.greek-omitted} [οχλω]{.greek-omitted} [τοις]{.greek-added} [οχλοις]{.greek-added}[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας [πληρεις]{.greek-omitted} [πληρης]{.greek-added}[15:37]{.aside}

οι δε εσθιοντες ησαν [ωσει]{.greek-added} τετρακισχιλιοι [ανδρες]{.greek-omitted} χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους [ενεβη]{.greek-omitted} [ανεβη]{.greek-added} εις το πλοιον και ηλθεν εις τα ορια [μαγδαλα]{.greek-omitted} [μαγδαλαν]{.greek-added}[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε ευδια πυρραζει γαρ ο [ουρανος]{.greek-abbr}[16:2]{.aside}

και πρωι σημερον χειμων πυρραζει γαρ στυγναζων ο [ουρανος]{.greek-abbr} [υποκριται]{.greek-omitted} το μεν προσωπον του [ουρανου]{.greek-abbr} [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} διακρινειν τα δε σημεια των καιρων ου [δυνασθε]{.greek-omitted} [δοκειμαζετε]{.greek-added}[16:3]{.aside}

γενεα πονηρα και [μοιχαλις]{.greek-omitted} [μιχαλλις]{.greek-added} σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου [και]{.greek-omitted} καταλιπων αυτους απηλθεν[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν επελαθοντο αρτους λαβειν[16:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ορατε και προσεχετε απο της ζυμης των φαρισαιων και σαδδουκαιων[16:6]{.aside}

οι δε [διελογιζοντο]{.greek-omitted} [διαλογιζοντο]{.greek-added} εν εαυτοις λεγοντες οτι αρτους ουκ ελαβομεν[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-omitted} τι διαλογιζεσθε εν εαυτοις ολιγοπιστοι οτι αρτους ουκ ελαβετε[16:8]{.aside}

ουπω νοειτε ουδε μνημονευετε τους πεντε αρτους των πεντακισχιλιων και ποσους κοφινους ελαβετε[16:9]{.aside}

ουδε τους επτα αρτους των τετρακισχιλιων και ποσας σπυριδας ελαβετε[16:10]{.aside}

πως ου νοειτε οτι [ου]{.greek-omitted} περι [αρτου]{.greek-omitted} [αρτον]{.greek-added} ειπον υμιν [προσεχειν]{.greek-omitted} [προσεχετε]{.greek-added} [δε]{.greek-added} απο της ζυμης των φαρισαιων και σαδδουκαιων[16:11]{.aside}

τοτε συνηκαν οτι ουκ ειπεν προσεχειν απο της ζυμης του αρτου [αλλα]{.greek-omitted} [αλλ]{.greek-added} απο της διδαχης των φαρισαιων και σαδδουκαιων[16:12]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ελθων [δε]{.greek-omitted} ο [ιησους]{.greek-abbr} εις τα [μερη]{.greek-omitted} [μερει]{.greek-added} [καισαρειας]{.greek-omitted} [καισαριας]{.greek-added} της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον [οι]{.greek-omitted} [η]{.greek-added} μεν ιωαννην τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λεγει αυτοις υμεις δε τινα με λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος ειπεν συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτω μακαριος ει σιμων βαριωνα οτι σαρξ και αιμα ουκ απεκαλυψεν σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις [ουρανοις]{.greek-abbr}[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι αδου ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν τοις [ουρανοις]{.greek-abbr} και ο εαν [λυσης]{.greek-omitted} [λυσις]{.greek-added} επι της γης εσται λελυμενον εν τοις [ουρανοις]{.greek-abbr}[16:19]{.aside}

τοτε διεστειλατο τοις μαθηταις αυτου ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} δεικνυειν τοις μαθηταις αυτου οτι δει αυτον απελθειν εις ιεροσολυμα και πολλα παθειν απο των πρεσβυτερων και αρχιερεων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και τη τριτη ημερα εγερθηναι[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος ηρξατο [επιτιμαν]{.greek-omitted} [επιτημαν]{.greek-added} αυτω λεγων ιλεως σοι [κυριε]{.greek-abbr} ου μη εσται σοι τουτο[16:22]{.aside}

ο δε στραφεις ειπεν τω πετρω υπαγε οπισω μου σατανα σκανδαλον μου ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα [τα]{.greek-omitted} των [ανθρωπων]{.greek-abbr}[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} ειπεν τοις μαθηταις αυτου ει τις θελει οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[16:24]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την ψυχην αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι γαρ [ωφελειται]{.greek-omitted} [οφεληθησεται]{.greek-added} [ανθρωπος]{.greek-abbr} εαν τον κοσμον ολον [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} την δε ψυχην αυτου ζημιωθη η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχεσθαι εν τη δοξη [του]{.greek-omitted} [πατρος]{.greek-omitted} [αυτου]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} αυτου και τοτε αποδωσει εκαστω κατα την πραξιν αυτου[16:27]{.aside}

αμην [δε]{.greek-added} λεγω υμιν [οτι]{.greek-added} εισιν τινες [των]{.greek-added} ωδε [εστωτες]{.greek-omitted} [εστωτων]{.greek-added} οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν ιδωσιν τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} [μεθ]{.greek-omitted} [ημερας]{.greek-omitted} [εξ]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [παραλαμβαννει]{.greek-added} ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και ιωαννην τον αδελφον αυτου και αναφερει αυτους εις ορος [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και ελαμψεν το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου εγενοντο λευκα ως το φως[17:2]{.aside}

και [ιδου]{.greek-omitted} ωφθησαν αυτοις [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

αποκριθεις δε ο πετρος ειπεν τω [ιησου]{.greek-abbr} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι ει θελεις ποιησωμεν ωδε τρεις σκηνας σοι μιαν και [μωση]{.greek-omitted} [μωυση]{.greek-added} μιαν [και]{.greek-omitted} [μιαν]{.greek-omitted} [ηλια]{.greek-omitted}[17:4]{.aside}

ετι [δε]{.greek-added} αυτου λαλουντος ιδου νεφελη φωτεινη επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added} αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται επεσον επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν εγερθητε και μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα [ειδον]{.greek-omitted} [ιδων]{.greek-added} ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινοντων αυτων εκ του ορους ενετειλατο αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι ειπητε το οραμα [τουτο]{.greek-added} εως ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[17:9]{.aside}

και επηρωτησαν αυτον οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν δει ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις ηλιας μεν ερχεται πρωτον και [αποκαταστησει]{.greek-omitted} [αποκαθηστησι]{.greek-added} παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας [ηδη]{.greek-omitted} [ηδι]{.greek-added} ηλθεν και ουκ επεγνωσαν αυτον [αλλα]{.greek-omitted} [αλλ]{.greek-added} εποιησαν εν αυτω οσα ηθελησαν ουτως και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι ιωαννου του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} [τις]{.greek-added} προσηλθεν [αυτω]{.greek-omitted} [ανθρωπος]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} γονυπετων αυτον[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον [υιον]{.greek-abbr} οτι [σεληνιαζεται]{.greek-omitted} [σελινιαζεται]{.greek-added} και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και προσηνεγκα αυτον τοις μαθηταις σου και ουκ [ηδυνηθησαν]{.greek-omitted} [ηδυνιθησαν]{.greek-added} αυτον θεραπευσαι[17:16]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε εσομαι μεθ υμων εως ποτε [ανεξομαι]{.greek-omitted} [ανεξωμαι]{.greek-added} υμων φερετε [μοι]{.greek-omitted} αυτον ωδε[17:17]{.aside}

και [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε προσελθοντες οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην γαρ λεγω [υμιν]{.greek-omitted} [υμην]{.greek-added} εαν εχητε πιστιν ως κοκκον [σιναπεως]{.greek-omitted} [σιναπεος]{.greek-added} ερειτε τω ορει [τουτω]{.greek-omitted} [τουτο]{.greek-added} [μεταβηθι]{.greek-omitted} [μεταβηθη]{.greek-added} εντευθεν εκει και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ εκπορευεται ει μη εν προσευχη και νηστεια[17:21]{.aside}

αναστρεφομενων δε αυτων εν τη γαλιλαια ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα [εγερθησεται]{.greek-omitted} [αναστησεται]{.greek-added} [και]{.corr} [ελυπηθησαν]{.corr} [σφοδρα]{.corr}[17:23]{.aside}

[ελθοντων]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ελθωντι]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} εις καπερναουμ προσηλθον οι τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added} [λαμβανοντες]{.greek-omitted} [λαμβαννοντες]{.greek-added} τω πετρω και ειπον ο διδασκαλος υμων ου τελει τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added}[17:24]{.aside}

λεγει ναι και οτε εισηλθεν εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο [τινων]{.greek-omitted} [τινος]{.greek-added} [λαμβανουσιν]{.greek-omitted} [λαμβαννουσι]{.greek-added} τελη η κηνσον απο των [υιων]{.greek-omitted} [[υιον]{.greek-abbr}]{.greek-added} αυτων η απο των αλλοτριων[17:25]{.aside}

λεγει αυτω ο πετρος απο των αλλοτριων εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις την θαλασσαν βαλε αγκιστρον και τον [αναβαινοντα]{.greek-omitted} [αναβαντα]{.greek-added} πρωτον ιχθυν αρον και ανοιξας το στομα αυτου ευρησεις στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ωρα προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες τις αρα μειζων εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη [στραφητε]{.greek-omitted} [επιστραφητε]{.greek-added} και γενησθε ως τα παιδια ου μη [εισελθητε]{.greek-omitted} [εισελθηται]{.greek-added} εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο ουτος εστιν ο μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος εαν δεξηται παιδιον τοιουτον εν επι τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν σκανδαλιση ενα [των]{.greek-omitted} [το]{.greek-added} [μικρον]{.greek-added} [τουτον]{.greek-added} [μικρων]{.corr} [τουτων]{.corr} [των]{.corr} πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος εις τον τραχηλον [αυ]{.greek-added} [αυτου]{.greek-omitted} [του]{.greek-added} και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου [το]{.greek-omitted} [τω]{.greek-added} σκανδαλον ερχεται[18:7]{.aside}

[ει]{.greek-omitted} [η]{.greek-added} δε η χειρ σου η ο πους σου σκανδαλιζει σε εκκοψον [αυτα]{.greek-omitted} [αυτον]{.greek-added} και βαλε απο σου καλον σοι [εστιν]{.greek-omitted} [εστην]{.greek-added} [εισελθειν]{.greek-omitted} εις την ζωην χωλον η κυλλον η δυο χειρας η δυο ποδας εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και ει ο οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εις την ζωην εισελθειν η δυο οφθαλμους εχοντα [βληθηναι]{.greek-omitted} [βλυθηναι]{.greek-added} εις την γεενναν του πυρος[18:9]{.aside}

[ορατε]{.greek-added} [μη]{.greek-added} [καταφρονησητε]{.greek-added} [ενος]{.greek-added} [των]{.greek-added} [μικρων]{.greek-added} [τουτων]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} ορατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} [το]{.corr} [προσωπον]{.corr} του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[18:10]{.aside}

ηλθεν γαρ ο υιος του [ανθρωπου]{.greek-abbr} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει εαν γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα [ενενηκοντα]{.greek-omitted} [ενενικοντα]{.greek-added} [εννεα]{.greek-omitted} [ενεα]{.greek-added} επι τα ορη πορευθεις ζητει το [πλανωμενον]{.greek-omitted} [πλανομενον]{.greek-added}[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η επι τοις ενενηκοντα [εννεα]{.greek-omitted} [ενεα]{.greek-added} τοις μη πεπλανημενοις[18:13]{.aside}

ουτως ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} θελημα εμπροσθεν του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [μου]{.greek-added} του εν [ουρανοις]{.greek-abbr} ινα αποληται εις των μικρων τουτων[18:14]{.aside}

εαν δε αμαρτηση εις σε ο αδελφος σου υπαγε και ελεγξον αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη ακουση παραλαβε μετα σου ετι ενα η δυο ινα επι στοματος δυο μαρτυρων η τριων [σταθη]{.greek-omitted} [σταθησεται]{.greek-added} παν ρημα[18:16]{.aside}

εαν δε παρακουση αυτων ειπε τη εκκλησια εαν δε και της εκκλησιας παρακουση εστω σοι ωσπερ ο εθνικος και ο τελωνης[18:17]{.aside}

αμην λεγω υμιν οσα εαν δησητε επι της γης εσται δεδεμενα εν τω [ουρανω]{.greek-abbr} και οσα εαν λυσητε επι της γης εσται λελυμενα εν τω [ουρανω]{.greek-abbr}[18:18]{.aside}

παλιν αμην λεγω υμιν οτι εαν δυο υμων συμφωνησωσιν επι της γης περι παντος πραγματος ου εαν αιτησωνται γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:19]{.aside}

ου γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο η τρεις συνηγμενοι εις το εμον ονομα εκει ειμι εν μεσω αυτων[18:20]{.aside}

τοτε προσελθων αυτω ο πετρος ειπεν [κυριε]{.greek-abbr} ποσακις αμαρτησει εις εμε ο αδελφος μου και αφησω αυτω εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} ου λεγω σοι εως επτακις αλλ εως εβδομηκοντακις επτα[18:22]{.aside}

δια τουτο [ωμοιωθη]{.greek-added} [η]{.greek-added} [βασιλεια]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added} ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος [ηθελησεν]{.greek-omitted} [ηθελησε]{.greek-added} συναραι λογον μετα των δουλων αυτου[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν αυτον ο [κυριος]{.greek-abbr} αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα ειχεν και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} μακροθυμησον επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο [κυριος]{.greek-abbr} του δουλου εκεινου απελυσεν αυτον και το δανειον αφηκεν αυτω[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον δηναρια και κρατησας αυτον επνιγεν λεγων αποδος μοι ει τι οφειλεις[18:28]{.aside}

πεσων ουν ο συνδουλος αυτου εις τους ποδας αυτου παρεκαλει αυτον λεγων [μακροθυμησον]{.greek-omitted} [μακροθυμισον]{.greek-added} επ εμοι και [παντα]{.greek-added} αποδωσω σοι[18:29]{.aside}

ο δε ουκ ηθελεν αλλα απελθων εβαλεν αυτον εις φυλακην εως ου αποδω το οφειλομενον[18:30]{.aside}

ιδοντες δε οι συνδουλοι αυτου τα γενομενα ελυπηθησαν σφοδρα και ελθοντες διεσαφησαν τω [κυριω]{.greek-abbr} εαυτων παντα τα γενομενα[18:31]{.aside}

τοτε [προσκαλεσαμενος]{.greek-omitted} [προσκαλεσανος]{.greek-added} αυτον ο [κυριος]{.greek-abbr} αυτου λεγει αυτω δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι επει παρεκαλεσας με[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως και εγω σε ηλεησα[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} αυτου παρεδωκεν αυτον τοις βασανισταις εως ου αποδω παν το οφειλομενον αυτω[18:34]{.aside}

ουτως και ο [πατηρ]{.greek-abbr} μου ο [επουρανιος]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} ποιησει υμιν εαν μη [αφητε]{.greek-omitted} [αφηιτε]{.greek-added} εκαστος τω αδελφω αυτου απο των καρδιων υμων τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους [εκει]{.greek-omitted}[19:2]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} προσηλθον αυτω οι φαρισαιοι πειραζοντες αυτον και λεγοντες αυτω ει εξεστιν [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ ανεγνωτε οτι ο ποιησας απ αρχης αρσεν και θηλυ εποιησεν αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταληψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-added} και την [μητερα]{.greek-abbr} και προσκολληθησεται τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν μωσης ενετειλατο δουναι βιβλιον αποστασιου και απολυσαι αυτην[19:7]{.aside}

λεγει αυτοις οτι μωσης προς την σκληροκαρδιαν υμων επετρεψεν υμιν απολυσαι τας γυναικας υμων απ αρχης δε ου γεγονεν ουτως[19:8]{.aside}

λεγω δε υμιν οτι ος αν απολυση την γυναικα αυτου μη επι πορνεια και γαμηση αλλην μοιχαται και ο απολελυμενην [γαμησας]{.greek-omitted} [γαμων]{.greek-added} μοιχαται[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτως εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφερει γαμησαι[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες [χωρουσιν]{.greek-omitted} [χωρουσι]{.greek-added} τον λογον τουτον αλλ οις δεδοται[19:11]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ ευνουχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} εγεννηθησαν ουτως και εισιν ευνουχοι οιτινες ευνουχισθησαν υπο των [ανθρωπων]{.greek-abbr} και εισιν ευνουχοι οιτινες ευνουχισαν εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε [προσηνεχθη]{.greek-omitted} [προσηνεχθησαν]{.greek-added} αυτω παιδια ινα τας χειρας επιθη αυτοις και προσευξηται οι δε μαθηται επετιμησαν αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε τα παιδια και μη κωλυετε αυτα ελθειν προς με των γαρ [τοιουτων]{.greek-omitted} [τιουτων]{.greek-added} [εστιν]{.greek-omitted} η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και επιθεις αυτοις τας χειρας επορευθη εκειθεν[19:15]{.aside}

και ιδου εις προσελθων ειπεν αυτω [διδασκαλε]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [νεανισκος]{.greek-added} [τις]{.greek-added} [προσηλθε]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [γονυπετων]{.greek-added} [αυτον]{.greek-added} [και]{.greek-added} [λεγων]{.greek-added} διδασκαλε αγαθε τι αγαθον ποιησω ινα εχω ζωην αιωνιον[19:16]{.aside}

ο δε ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr} ει δε θελεις εισελθειν εις την ζωην [τηρησον]{.greek-omitted} [τιρησον]{.greek-added} τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} ειπεν το ου φονευσεις ου μοιχευσεις ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} [σου]{.greek-added} και αγαπησεις τον πλησιον σου ως σεαυτον[19:19]{.aside}

λεγει αυτω ο νεανισκος παντα ταυτα εφυλαξαμην εκ νεοτητος μου τι ετι υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελεις τελειος ειναι υπαγε πωλησον σου τα υπαρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως πλουσιος εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν δε λεγω υμιν ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια τρυπηματος ραφιδος [διελθειν]{.greek-omitted} [εισελθειν]{.greek-added} η [πλουσιον]{.greek-omitted} [πλουσιος]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[19:24]{.aside}

ακουσαντες δε οι μαθηται αυτου εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

[εμβλεψας]{.greek-omitted} [εμβλεμψας]{.greek-added} δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα δε [θεω]{.greek-abbr} παντα δυνατα[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν [τοτε]{.greek-added} [αποκριθεις]{.greek-added} [ο]{.greek-added} [πετρος]{.greek-added} [ειπεν]{.greek-added} [αυτω]{.greek-added} [ιδου]{.greek-added} [ημεις]{.greek-added} [αφηκαμεν]{.greek-added} [παντα]{.greek-added}[19:27]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν [καθιση]{.greek-omitted} [καθησει]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου καθισεσθε και υμεις επι δωδεκα θρονους κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας [ος]{.greek-omitted} [οστις]{.greek-added} αφηκεν οικιας η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν του ονοματος μου [εκατονταπλασιονα]{.greek-omitted} [εκατονταπλασιωνα]{.greek-added} ληψεται και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε ε[σ]{.unclear}ονται πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι [εν]{.greek-added} [τη]{.greek-added} [βασιλεια]{.greek-added} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added}[19:30]{.aside}

### Chapter 20

[ομοια]{.greek-omitted} [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

[και]{.greek-omitted} συμφωνησας [δε]{.greek-added} μετα των εργατων εκ [δηναριου]{.greek-omitted} [δυναριου]{.greek-added} την ημεραν [απεστειλεν]{.greek-omitted} [απεστηλεν]{.greek-added} αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι τριτην ωραν ειδεν αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

[και]{.greek-omitted} [εκεινοις]{.greek-omitted} [κακεινοις]{.greek-added} ειπεν υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν εξελθων περι εκτην και ενατην ωραν εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο λεγει αυτοις υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον ληψεσθε[20:7]{.aside}

οψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και [αποδος]{.greek-omitted} [αποδως]{.greek-added} αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι πλειονα ληψονται και ελαβον και αυτοι ανα δηναριον[20:10]{.aside}

λαβοντες δε εγογγυζον κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι ουτοι οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις [βαστασασιν]{.greek-omitted} [βαστασασι]{.greek-added} το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων εταιρε ουκ αδικω σε ουχι [δηναριου]{.greek-omitted} [δυναριου]{.greek-added} συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω εσχατω δουναι ως και σοι[20:14]{.aside}

η ουκ εξεστιν μοι ποιησαι ο θελω εν τοις εμοις [ει]{.greek-omitted} [η]{.greek-added} ο οφθαλμος σου πονηρος [εστιν]{.greek-omitted} [εστι]{.greek-added} οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι και οι πρωτοι εσχατοι πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

και αναβαινων ο [ιησους]{.greek-abbr} εις ιεροσολυμα [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} τους δωδεκα μαθητας κατ ιδιαν εν τη οδω και ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω[20:18]{.aside}

και [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} [αυτον]{.greek-omitted} τοις εθνεσιν εις το εμπαιξαι και μαστιγωσαι και [σταυρωσαι]{.greek-abbr} και τη τριτη ημερα αναστησεται[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι θελεις λεγει αυτω ειπε ινα καθισωσιν ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις [εξ]{.greek-omitted} [ε]{.greek-added} [ξ]{.greek-added} ευωνυμων σου εν [τη]{.greek-omitted} [τηι]{.greek-added} βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω μελλω πινειν η το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε το δε καθισαι εκ δεξιων μου και εξ ευωνυμων μου ουκ εστιν [εμον]{.greek-omitted} [εμων]{.greek-added} [τουτο]{.greek-added} δουναι αλλ οις [η]{.unclear}τοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως [δε]{.greek-omitted} εσται εν υμιν αλλ ος εαν θελη εν υμιν μεγας γενεσθαι εσται υμων διακονος[20:26]{.aside}

και ος εαν θελη εν υμιν ειναι πρωτος [εστω]{.greek-omitted} [εσται]{.greek-added} υμων δουλος[20:27]{.aside}

ωσπερ ο υιος του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και εκπορευομενων αυτων απο ιεριχω ηκολουθησεν αυτω οχλος πολυς [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [πορευομενου]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [απο]{.greek-added} [ιεριχω]{.greek-added} [ηκολουθησεν]{.greek-added} [αυτω]{.greek-added} [οχλος]{.greek-added} [πολυς]{.greek-added}[20:29]{.aside}

και ιδου δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

ο δε οχλο[ς]{.unclear} επ[ε]{.greek-supplied}τ[ι]{.greek-supplied}μησεν αυτοις ινα σι[ωπ]{.unclear}ησωσιν [οι]{.greek-supplied} δε [μ]{.unclear}ειζον [εκραζον]{.greek-omitted} [εκραξαν]{.greek-added} λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:31]{.aside}

και [στας]{.greek-omitted} [σταθεις]{.greek-added} ο [ιησους]{.greek-abbr} [ε]{.unclear}φωνησε[ν]{.unclear} αυτους κ[αι]{.unclear} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} [αυτοις]{.greek-added} τι θελετε ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτ[ω]{.unclear} [κυριε]{.greek-abbr} [ι]{.greek-supplied}να [ανοιχθωσιν]{.greek-omitted} [ανοιγωσιν]{.greek-added} [η]{.unclear}μων οι οφθαλμοι[20:33]{.aside}

σπ[λα]{.unclear}γχνισθει[ς]{.unclear} [δε]{.unclear} ο [ιησους]{.greek-abbr} ηψ[ατο]{.unclear} των οφθαλμων αυτων και ευθεως ανεβλεψαν αυτων οι [ο]{.greek-added} [οφθαλμοι]{.greek-omitted} [φθαλμοι]{.greek-added} και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε ηγγισαν εις ιεροσολυμα και ηλθον εις [βηθσφαγη]{.greek-omitted} [βησφαγη]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [οτε]{.greek-added} [ηγγισεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [ιεροσολυμα]{.greek-added} [και]{.greek-added} [ηλθον]{.greek-added} [εις]{.greek-added} [βησφαγη]{.greek-added} προς το ορος [των]{.greek-added} των ελαιων τοτε ο [ιησους]{.greek-abbr} απεστειλεν δυο μαθητας[21:1]{.aside}

λεγων αυτοις [πορευθητε]{.greek-omitted} [πορευεσθε]{.greek-added} εις την κωμην την απεναντι υμων και ευθεως ευρησετε ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο [κυριος]{.greek-abbr} αυτων χρειαν εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον και πωλον [υιον]{.greek-abbr} υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες καθως προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και τον πωλον και επεθηκαν επανω αυτων τα ιματια αυτων και [επεκαθισεν]{.greek-omitted} [επεκαθησεν]{.greek-added} επανω αυτων[21:7]{.aside}

ο δε πλειστος οχλος εστρωσαν [εαυτων]{.greek-omitted} [αυτων]{.greek-added} τα ιματια εν τη οδω αλλοι δε εκοπτον κλαδους απο των [δενδρων]{.greek-omitted} [δεδρων]{.greek-added} και εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

[υποστρεψαντος]{.greek-added} [δε]{.greek-added} [αυτου]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [πολιν]{.greek-added} και εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον του [θεου]{.greek-abbr} και εξεβαλεν παντας τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων κατεστρεψεν και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο οικος μου οικος προσευχης κληθησεται υμεις δε [εποιησατε]{.greek-added} αυτον [εποιησατε]{.greek-omitted} σπηλαιον [ληστων]{.greek-omitted}[21:13]{.aside}

και προσηλθον αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων [κατηρτησω]{.greek-added} [κατηρτισω]{.corr} αινον[21:16]{.aside}

και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη εκει[21:17]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} πρωιας [δε]{.greek-omitted} επαναγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις την πολιν επεινασεν[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει μη φυλλα μονον και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη [παραχρημα]{.greek-omitted} [παραχρη]{.greek-added} η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν εχητε πιστιν και μη διακριθητε ου μονον το της συκης ποιησετε αλλα καν τω ορει τουτω ειπητε αρθητι και [βλητι]{.greek-added} [βληθητι]{.corr} εις την θαλασσαν [[κ]{.unclear}αι]{.greek-added} γενησεται[21:21]{.aside}

και παντα οσα [εαν]{.greek-omitted} [αν]{.greek-added} αιτησητε εν τη προσευχη πιστευοντες ληψεσθε[21:22]{.aside}

και ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις σοι [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω υμας καγω λογον ενα ον εαν ειπητε μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα ιωαννου ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο παρ εαυτοις λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει ημιν δια τι ουν ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον ιωαννην ως προφητην[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} ειπον ουκ οιδαμεν εφη αυτοις και αυτος ουδε εγω [υμιν]{.greek-added} λεγω [υμιν]{.greek-omitted} εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} ειχεν τεκνα δυο και προσελθων τω πρωτω ειπεν τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε μεταμεληθεις απηλθεν[21:29]{.aside}

και προσελθων τω [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν ωσαυτως ο δε αποκριθεις ειπεν εγω [κυριε]{.greek-abbr} και ουκ απηλθεν[21:30]{.aside}

τις εκ των δυο [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

[ηλθε]{.greek-added} [ηλθεν]{.corr} γαρ προς υμας ιωαννης εν οδω δικαιοσυν[η]{.unclear}ς και ουκ επιστευσατε αυτω οι δε τελωναι και [αι]{.corr} πορναι επιστευσαν αυτω υμεις δε ιδοντες ου μετεμεληθητε υστερον του πιστευσαι αυτω[21:32]{.aside}

αλλην παραβολην ακουσατε [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added} [ανθρωπος]{.greek-abbr} τις ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω [περι]{.greek-added} [περιεθηκεν]{.greek-omitted} [εθηκεν]{.greek-added} και ωρυξεν εν αυτω ληνον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και [εξεδο[―]{.gap}]{.greek-added} [εξεδοτο]{.corr} αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε ηγγισεν ο καιρος των καρπων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν [δε]{.greek-added} απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους τον υιον αυτου [λεγον]{.greek-added} [λεγων]{.corr} εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα εκδωσεται αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις καιροις αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} [ουδεποτε]{.greek-omitted} [ουδεπωτε]{.greek-added} ανεγνωτε εν ταις γραφαις λιθον ον [απεδωκιμασαν]{.greek-added} [απεδοκιμασαν]{.corr} οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται εθνει ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση [λικμησει]{.greek-omitted} [ληκμησει]{.greek-added} αυτον[21:44]{.aside}

και ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους επειδη ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} παλιν ειπεν αυτοις εν παραβολαις [λεγων]{.greek-omitted} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added}[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω αυτου[22:2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα σιτιστα τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την [εμποριαν]{.greek-omitted} [εμπορειαν]{.greek-added} αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος ωργισθη και πεμψας τα στρατευματα αυτου απωλεσεν τους φονεις εκεινους και την πολιν αυτων ενεπρησεν[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον παντας οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου ποδας και χειρας αρατε αυτον και [εκβαλετε]{.greek-omitted} [εμβαλετε]{.greek-added} εις το σκοτος το [εξο]{.greek-added} [εξωτερον]{.greek-omitted} [τερον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} συμβουλιον [ελαβον]{.greek-omitted} [εποιησαν]{.greek-added} [οι]{.greek-added} [φαρισαιοι]{.greek-added} οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι κηνσον καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων ειπεν τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του κηνσου οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις αποδοτε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι οι λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης ειπεν εαν τις αποθανη μη εχων τεκνα [επιγαμβρευσει]{.greek-omitted} [επιγαμβευσει]{.greek-added} ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος γαμησας ετελευτησεν και μη εχων σπερμα αφηκεν την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο [τρητος]{.greek-added} [τριτος]{.corr} εως των επτα[22:26]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις πλανασθε μη ειδοτες τας γραφας μηδε την [δυναμιν]{.greek-omitted} [δυνα]{.greek-added} [μιν]{.greek-added} του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε [εκγαμιζονται]{.greek-omitted} [ενγαμιζονται]{.greek-added} αλλ ως αγγελοι του [θεου]{.greek-abbr} εν ουρανω [εισιν]{.greek-omitted} [εισι]{.greek-added}[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημωσε]{.greek-added} τους σαδδουκαιους συνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [νομικος]{.greek-added} [τις]{.greek-added} [προσηλθε]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη καρδια σου και εν ολη ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη εστιν [η]{.greek-added} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως σεαυτον[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος [ο]{.unclear} νομος και οι προφηται κρεμανται[22:40]{.aside}

συ[ν]{.unclear}ηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος [υιος]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} καλει αυτον [κυριον]{.greek-abbr} πως υιος αυτου εστιν[22:45]{.aside}

και ουδεις εδυνατο αυτω αποκριθηναι λογον ουδε ετολμησεν τις απ ε[κ]{.unclear}ειν[η]{.unclear}ς της ημερας επερ[ωτη]{.unclear}σαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησε]{.greek-added} [[τοις]{.greek-supplied}]{.greek-added} [οχλοις]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ελαλησεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τοις οχλοις και τοις μα[θη]{.unclear}ταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} οι [γραμματεις]{.greek-omitted} [γραματεις]{.greek-added} και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και ποιειτε κατα δε τα εργα αυτων μη ποιειτε [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου ποιουσιν[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} [γαρ]{.greek-omitted} [δε]{.greek-added} φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι τοις ανθρωποις [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} δε τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} την [πρωτοκλισιαν]{.greek-omitted} [πρωτοκλησιαν]{.greek-added} εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και [καλεισθαι]{.greek-omitted} [λεγεσθαι]{.greek-added} υπο των [ανθρωπων]{.greek-abbr} [ραββι]{.greek-omitted} [ραββει]{.greek-added} [ραββι]{.greek-omitted} [ραββει]{.greek-added}[23:7]{.aside}

υμεις δε μη κληθητε [ραββι]{.greek-omitted} [ραββει]{.greek-added} εις γαρ εστιν υμων ο καθηγητης ο [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε υμων επι της γης εις γαρ εστιν ο [πρ]{.greek-added} [[πατηρ]{.greek-abbr}]{.corr} υμων ο εν τοις [ουρανοις]{.greek-abbr}[23:9]{.aside}

μηδε κληθητε καθηγηται εις γαρ [υμων]{.greek-omitted} εστιν ο καθηγητης ο [χριστος]{.greek-abbr} [υμων]{.greek-added}[23:10]{.aside}

ο δε μειζων υμων [εσται]{.greek-omitted} [υμων]{.greek-omitted} διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και [και]{.greek-added} οστις ταπεινωσει [εαυτων]{.greek-added} [εαυτον]{.corr} υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [ερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χιρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι περιαγετε την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν γενηται ποιειτε αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν ομοση εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} ουδεν ε[σ]{.unclear}τιν ος δ αν ομοση εν τω χρυσω του ναου [οφειλει]{.greek-omitted} [οφιλει]{.greek-added}[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος εαν ομοση εν τω θυσιαστηριω ουδεν εστιν ος δ αν ομοση εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλο[ι]{.unclear} τι γαρ μειζον το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω [ομνυει]{.greek-omitted} [ομνυειν]{.greek-added} εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο ομοσας εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} ομνυει εν αυτω και εν τω κατοικησαντι α[υ]{.unclear}[τ]{.greek-supplied}ον[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το κυμινον και αφηκατε τα βαρυτερα του νομου την κρισιν και τον ελεον και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι καθαριζετε το εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και [αδικιας]{.greek-omitted} [ακρα]{.greek-added} [σιας]{.greek-added}[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι παρομοιαζετε ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις εξωθεν μεν φαινεσθε τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι εστε υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι οικοδομειτε τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει [ημεν]{.greek-omitted} [ημεθα]{.greek-added} εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν [ημεν]{.greek-omitted} [ημεθα]{.greek-added} κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε [τω]{.greek-added} [των]{.corr} φονευσαντων τους προφητας[23:31]{.aside}

και υμεις πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και [σταυρωσετε]{.greek-abbr} και εξ αυτων μαστιγωσετε εν ταις συναγωγαις υμων και διωξετε απο πολεως εις πολιν[23:34]{.aside}

οπως ελθη εφ υμας παν αιμα δικαιον εκχυνομενον επι της γης απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει παντα ταυτα επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η αποκτενουσα τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον τροπον επισυναγει ορνις τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη με ιδητε απ αρτι εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτου επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου βλεπετε [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου [μη]{.greek-added} καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων [τωι]{.greek-added} [καιρωι]{.greek-added} [εκεινωι]{.greek-added} προσηλθον [αυτω]{.greek-omitted} οι μαθηται [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους πλανησουσιν[24:5]{.aside}

μελλησετε δε ακουειν πολεμους και ακοας πολεμων ορατε μη θροεισθε δει γαρ παντα γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εστι]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και λοιμοι και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη ωδινων[24:8]{.aside}

τοτε παραδωσουσιν υμας εις [θλιψιν]{.greek-omitted} [θληψιν]{.greek-added} και αποκτενουσιν υμας και εσεσθε μισουμενοι υπο παντων των εθνων δια το [ονομα]{.greek-omitted} [ονομαμα]{.greek-added} μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους [παραδωσουσιν]{.greek-omitted} [παραδωσωσιν]{.greek-added} και [μισησουσιν]{.greek-omitted} [μησησουσιν]{.greek-added} αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} πολλους[24:11]{.aside}

και δια το [πλη]{.greek-added} [πληθυνθηναι]{.greek-omitted} [θυνθηναι]{.greek-added} την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται τουτο το ευαγγελιον της βασιλειας εν ολη τη οικουμενη εις μαρτυριον [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν ιδητε το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου [εστως]{.greek-omitted} [εστος]{.greek-added} εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν [τη]{.greek-omitted} [τηι]{.greek-added} [ιουδαια]{.greek-omitted} [ιουδαιαι]{.greek-added} φευγετωσαν επι τα ορη[24:16]{.aside}

ο επι του δ[ω]{.unclear}ματος μη [καταβαινετω]{.greek-omitted} [κακαταβαινετω]{.greek-added} αραι τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος μηδε σαββατω[24:20]{.aside}

εσται γαρ τοτε θλιψις μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν [ουδ]{.greek-omitted} [ουδε]{.greek-added} [ου]{.greek-omitted} μη γενηται[24:21]{.aside}

και ει μη εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια μεγαλα και τερατα ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω [εστιν]{.greek-omitted} [εστι]{.greek-added} μη εξελθητε ιδου εν τοις ταμειοις μη πιστευσητε[24:26]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και [φαινεται]{.greek-omitted} [φενεται]{.greek-added} εως δυσμων ουτως εσται [και]{.greek-omitted} η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ εαν η το πτωμα εκει συναχθησονται οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος [σκοτισθησεται]{.greek-omitted} [κοτισσθησεται]{.greek-added} και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε κοψονται πασαι αι φυλαι της γης και οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και αποστελει τους αγγελους αυτου μετα σαλπιγγος [και]{.greek-added} φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξουσι]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-abbr} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος αυτης γενηται απαλος και τα φυλλα εκφυη γινωσκετε οτι εγγυς [το]{.greek-omitted} [θερος]{.greek-omitted}[24:32]{.aside}

[ουτως]{.greek-omitted} [και]{.greek-omitted} [υμεις]{.greek-omitted} [οταν]{.greek-omitted} [ιδητε]{.greek-omitted} [ταυτα]{.greek-omitted} [παντα]{.greek-omitted} [γινωσκετε]{.greek-omitted} [οτι]{.greek-omitted} [εγγυς]{.greek-omitted} εστιν επι θυραις[24:33]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} αμην λεγω υμιν ου μη παρελθη η γενεα αυτη εως αν παντα [ταυτα]{.greek-omitted} γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσονται οι δε λογοι μου ου μη παρελθωσιν[24:35]{.aside}

περι δε της ημερας εκεινης και ωρας ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} [ουδε]{.greek-added} [ο]{.greek-added} [υιος]{.greek-added} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις προ του κατακλυσμου τρωγοντες και πινοντες γαμουντες και [εκγαμιζοντες]{.greek-omitted} [εγγαμιζοντες]{.greek-added} αχρι ης ημερας εισηλθεν νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο [επι]{.greek-added} [κλινης]{.greek-added} [εις]{.greek-added} [αληθουσαι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [μυλωνι]{.greek-omitted} [μια]{.greek-omitted} παραλαμβανεται και [μια]{.greek-omitted} [ο]{.greek-added} [εις]{.greek-added} αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει ηδει ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν ειασεν διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και [φρονιμος]{.greek-omitted} [φρονημος]{.greek-added} ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της [θεραπειας]{.greek-omitted} [οικετιας]{.greek-added} αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [αυτου]{.greek-added} [εσθιειν]{.greek-omitted} [εσθιει]{.greek-added} δε και [πινειν]{.greek-omitted} [πινη]{.greek-added} μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων [θησει]{.greek-omitted} [θυσει]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται [η]{.greek-added} [βασιλεια]{.greek-added} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [δεκα]{.greek-added} [παρθενοις]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθ[ε]{.unclear}νοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου [και]{.greek-added} [της]{.greek-added} [νυμφης]{.greek-added}[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και [αι]{.corr} πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων [ελαιον]{.greek-omitted} [ελεον]{.greek-added}[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και [εκαθευδων]{.greek-added} [εκαθευδον]{.corr}[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε ημιν εκ του ελαιου υμων οτι [αι]{.greek-omitted} [ε]{.greek-added} λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε ουκ αρκεση ημιν και υμιν πορευεσθε δε μαλλον προς τους πωλουντας και [αγορασατε]{.greek-omitted} [αγωρασατε]{.greek-added} εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν εν η ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα [τοσαυτα]{.greek-added} [πεντε]{.greek-omitted} [ταλαντα]{.greek-omitted}[25:16]{.aside}

ωσαυτως και ο τα δυο [εκερδησεν]{.greek-omitted} [εκερδησε]{.greek-added} και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και [απεκρυψεν]{.greek-omitted} [απεκρυψε]{.greek-added} το αργυριον του [κυριου]{.greek-abbr} αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και συναιρει [λογον]{.greek-added} μετ αυτων [λογον]{.greek-omitted}[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη [δε]{.greek-omitted} αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης [πιστως]{.greek-added} [πιστος]{.corr} επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων ειπεν [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως ειπεν [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε ηδεις οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο [δωκει]{.greek-added} εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον [εκβαλετε]{.greek-omitted} [εμβαλετε]{.greek-added} εις το σκοτος το [εξωτερον]{.greek-omitted} [εξοτερον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} οταν [δε]{.greek-omitted} ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε [καθηση]{.greek-added} [καθισει]{.greek-omitted} [[καθιση]{.corr}]{.greek-added} επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των [ε]{.greek-added} [εριφων]{.greek-omitted} [ριφων]{.greek-added}[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με ξενος ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και επεσκεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} πεινωντα και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} ξενον και συνηγαγομεν η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των [ελαχιστων]{.greek-added} αδελφων μου [των]{.greek-omitted} [ελαχιστων]{.greek-omitted} εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου [συνηγαγετε]{.greek-omitted} [σνυηγαγετε]{.greek-added} [με]{.greek-omitted} [γυμνος]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [περιεβαλετε]{.greek-omitted} με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους ειπεν τοις μαθηταις αυτου[26:1]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το σταυρωθηναι[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω [κρατησωσιν]{.greek-omitted} [κρατησωσι]{.greek-added} και [αποκτεινωσιν]{.greek-omitted} [αποκτινωσιν]{.greek-added}[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

[ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} γαρ τουτο [το]{.greek-omitted} [μυρον]{.greek-omitted} πραθηναι πολλου και δοθηναι [τοις]{.greek-added} πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους παρεχετε τη γυναικι εργον γαρ καλον ειργασατο εις εμε[26:10]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το ενταφιασαι με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο [λεγομενος]{.greek-omitted} [λεγωμενος]{.greek-added} ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

ειπεν τι θελετε μοι δουναι καγω υμιν παραδωσω αυτον [και]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που θελεις [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα [μαθητων]{.greek-added}[26:20]{.aside}

και εσθιοντων αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρα [ηρξαντο]{.greek-omitted} [ηρξατο]{.greek-added} λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω [τρυβλιω]{.greek-omitted} [τριβλιω]{.greek-added} την χειρα ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον ειπεν μητι εγω ειμι [ραββι]{.greek-omitted} [ραββει]{.greek-added} λεγει αυτω συ ειπας[26:25]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας εκλασεν και εδιδου τοις μαθηταις και ειπεν λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του γεννηματος της αμπελου εως της ημερας εκεινης οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις [κανδαλισθησεσθε]{.greek-added} [σκανδαλισθησεσθε]{.corr} εν εμοι εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα [προβατη]{.greek-added} [προβατα]{.corr} της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει [και]{.greek-added} παντες σκανδαλισθησονται εν σοι εγω [δε]{.greek-omitted} ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε απαρνησωμαι ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον γεθσημανη και λεγει τοις μαθηταις καθισατε αυτου εως ου απελθων προσευξωμαι εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους [ζεβεδαιου]{.greek-omitted} [ζεβαιδαιου]{.greek-added} ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον εστιν [παρελθετω]{.greek-omitted} [παρελθατω]{.greek-added} απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων πατερ μου ει ου δυναται τουτο [το]{.greek-omitted} [ποτηριον]{.greek-omitted} παρελθειν απ εμου εαν μη [αυτο]{.greek-omitted} [αυ]{.greek-added} [το]{.greek-added} πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων [ευρισκει]{.greek-omitted} [ευρεν]{.greek-added} αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων [προσηυξατο]{.greek-added} παλιν [προσηυξατο]{.greek-omitted} εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας [αυτου]{.greek-omitted} και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα ηλθεν και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον αν [[εαν]{.corr}]{.greek-added} [φιλησω]{.greek-omitted} [φιλεισω]{.greek-added} αυτος εστιν κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} ειπεν χαιρε [ραββι]{.greek-omitted} [ραββει]{.greek-added} και [κατεφιλησεν]{.greek-omitted} [κατεφιλεισεν]{.greek-added} αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ [ω]{.greek-omitted} [ο]{.greek-added} παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και [εκρατησαν]{.greek-omitted} [εκρατεισαν]{.greek-added} αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} εκτεινας την [χειρα]{.greek-omitted} [χειραν]{.greek-added} [απεσπασεν]{.greek-omitted} [απεσπασε]{.greek-added} την μαχαιραν αυτου και παταξας [των]{.greek-added} [τον]{.corr} δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον σου την μαχαιραν εις τον τοπον αυτης παντες γαρ οι λαβοντες [μαχαιραν]{.greek-omitted} [μαχαιρα]{.greek-added} εν μαχαιρα [αποθανουνται]{.greek-omitted} [απολουνται]{.greek-added}[26:52]{.aside}

η [δοκεις]{.greek-omitted} [δοκει]{.greek-added} [σοι]{.greek-added} οτι ου δυναμαι [αρτι]{.greek-omitted} παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνα[ς]{.unclear} [αγγελων]{.greek-omitted} [[λεγεωνωνων]{.corr}]{.greek-added} [αγγελους]{.greek-added}[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς [υμας]{.greek-omitted} [ημας]{.greek-added} εκαθεζομην [διδασκων]{.greek-omitted} εν τω ιερω [διδασκω[ν]{.unclear}]{.greek-added} και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και το συνεδριον ολον εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως [αυτον]{.greek-added} θανατωσωσιν [αυτον]{.greek-omitted}[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [τινες]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr} [του]{.greek-added} [ζωντος]{.greek-added}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματια αυτου λεγων οτι εβλασφημησεν τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου [εστιν]{.greek-omitted} [εστι]{.greek-added}[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και [εκολαφισαν]{.greek-omitted} [εκολαφησαν]{.greek-added} αυτον οι δε [ερραπισαν]{.greek-omitted} [εραπισαν]{.greek-added}[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μια [παιδισκ[α]{.unclear}]{.greek-added} [παιδισκη]{.corr} λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν [αυτων]{.greek-omitted} παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

[εξελθοντα]{.greek-omitted} [εξελθωντα]{.greek-added} δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει αυτοις εκει και [ουτος]{.greek-omitted} [ουτως]{.greek-added} ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο [μεθ]{.greek-omitted} [μετα]{.greek-added} ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα [μικρον]{.greek-omitted} [μικρων]{.greek-added} δε προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ εφωνησεν[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος του [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω εκλαυσεν πικρως[26:75]{.aside}

### Chapter 27

[πρωιας]{.greek-omitted} [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν αυτον ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

[τοτε]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ιδων ιουδας ο παραδιδους [αυτων]{.greek-added} [αυτον]{.corr} οτι κατεκριθη μεταμεληθεις [απεστρεψεν]{.greek-omitted} [απεστρεψε]{.greek-added} τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε ειπον τι προς ημας συ [οψει]{.greek-omitted} [οψη]{.greek-added}[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω ανεχωρησεν και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον κορβαναν επει τιμη αιματος εστιν[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα συνεταξεν μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και των πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν [ενα]{.greek-omitted} τω οχλω [ενα]{.greek-added} δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν [οστις]{.greek-added} [δια]{.greek-added} [φονον]{.greek-added} [ην]{.greek-added} [βεβλημενος]{.greek-added} [εις]{.greek-added} [φυλακην]{.greek-added}[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ [επαθων]{.greek-added} [επαθον]{.corr} σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} [αυτω]{.greek-omitted} παντες σταυρωθητω[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες σταυρωθητω[27:23]{.aside}

ιδων δε ο [πιλατος]{.greek-omitted} [πιλατως]{.greek-added} οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος ειπεν το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φραγελλωσας παρεδωκεν ινα σταυρωθη[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και [πλεξαντες]{.greek-omitted} [πλεξαντε]{.greek-added} στεφανον εξ ακανθων [επεθηκαν]{.greek-omitted} [εθηκαν]{.greek-added} επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και γονυπετησαντες εμπροσθεν αυτου [ενεπαιζον]{.greek-omitted} [ενεμπαιζον]{.greek-added} αυτω λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν [αυτον]{.greek-omitted} [αυτου]{.greek-added} την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} [κυρηναιον]{.greek-omitted} [κυριναιον]{.greek-added} ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} ελθοντες [οι]{.greek-added} [στρατιωται]{.greek-added} εις τοπον λεγομενον γολγοθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [λεγομενος]{.greek-omitted} [λεγομενον]{.greek-added} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ ηθελεν πιειν[27:34]{.aside}

[σταυρωσαντες]{.greek-omitted} [σταυροσαντες]{.greek-added} δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-abbr} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε σταυρουνται συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} καταβηθι απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως δε και οι αρχιερεις εμπαιζοντες μετα των γραμματεων και [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} φαρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} και [πιστευωμεν]{.greek-added} [πιστευσομεν]{.greek-omitted} [[πιστευομεν]{.corr}]{.greek-added} επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω νυν αυτον ει θελει αυτον ειπεν γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι συσταυρωθεντες αυτω [ωνειδιζον]{.greek-omitted} [ωνιδιζον]{.greek-added} αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας ενατης[27:45]{.aside}

περι δε την [ενατην]{.greek-omitted} [ενατη]{.greek-added} ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι [λιμα]{.greek-omitted} [λειμα]{.greek-added} σαβαχθανι τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου [θεε]{.corr} [μου]{.corr} [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με [εγκατελιπες]{.greek-omitted} [εγκατελειπες]{.greek-added}[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες ελεγον οτι ηλιαν φωνει ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες [ι]{.greek-added} [ιδωμεν]{.greek-omitted} [δωμεν]{.greek-added} ει ερχεται ηλιας [σωσων]{.greek-omitted} [σωσαι]{.greek-added} αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη αφηκεν το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη [εσεισθη]{.greek-omitted} [εσεισσθη]{.greek-added} και [αι]{.greek-omitted} [ε]{.greek-added} πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια ανεωχθησαν και πολλα σωματα των κεκοιμημενων αγιων [ηγερθη]{.greek-omitted} [ηγερθησαν]{.greek-added}[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου [τηρουνται]{.greek-added} [τηρουντες]{.corr} τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} υιος ην ουτος[27:54]{.aside}

ησαν δε εκει γυναικες πολλαι [απο]{.greek-omitted} μακροθεν θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η μαγδαληνη και μαρια η του ιακωβου και [ιωση]{.greek-omitted} [μητηρ]{.greek-omitted} [και]{.greek-omitted} η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο [αριμαθαιας]{.greek-omitted} [αριμαθιας]{.greek-added} τουνομα ιωσηφ ος και αυτος εμαθητευσεν τω [ιησου]{.greek-abbr}[27:57]{.aside}

[ουτος]{.greek-omitted} [ουτως]{.greek-added} προσελθων τω πιλατω [ητησατο]{.greek-omitted} [ητισατο]{.greek-added} το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ ενετυλιξεν αυτο σινδονι καθαρα[27:59]{.aside}

και εθηκεν [αυτω]{.greek-added} [αυτο]{.corr} εν τω καινω αυτου μνημειω ο ελατομησεν εν τη πετρα και [προσκυλησας]{.greek-added} [προσκυλισας]{.corr} λιθον μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η μαγδαληνη και η αλλη μαρια καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την [παρα]{.greek-added} [παρασκευην]{.greek-omitted} [σκευην]{.greek-added} συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς πιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου [νυκτος]{.greek-omitted} κλεψωσιν αυτον και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} τω λαω ηγερθη απο των νεκρων και εσται η εσχατη [πλανη]{.greek-omitted} χειρων της πρωτης[27:64]{.aside}

εφη [δε]{.greek-omitted} αυτοις ο πιλατος εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε [δε]{.greek-omitted} σαββατων τη [επιφωσκουση]{.greek-omitted} [επιφουσκουση]{.greek-added} εις μιαν σαββατων ηλθεν μαρια η μαγδαληνη και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} [και]{.greek-added} προσελθων [απεκυλισεν]{.greek-omitted} [απεκυλισε]{.greek-added} τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο [ω]{.greek-supplied}σει νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος ειπεν ταις γυναιξιν μη φοβεισθε υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} [τον]{.greek-omitted} [εσταυρωμενον]{.greek-omitted} ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως ειπεν δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ [πορευθησαι]{.greek-added} [πορευθεισαι]{.corr} ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

ως δε επορευοντο απαγγειλαι τοις μαθηταις αυτου και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} απηντησεν αυταις λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

λεγοντες ειπατε οτι [ημων]{.greek-added} [κοιμωμενων]{.greek-added} [ελθοντες]{.greek-added} οι μαθηται αυτου νυκτος [ελθοντες]{.greek-omitted} εκλεψαν αυτον [ημων]{.greek-omitted} [κοιμωμενων]{.greek-omitted}[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις πεισομεν αυτον και υμας αμεριμνους ποιησομεν[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και [διεφημισθη]{.greek-omitted} [διεφημησθη]{.greek-added} ο λογος ουτος παρα ιουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα [μαται]{.greek-added} [μαθηται]{.corr} επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες [ουν]{.greek-added} μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

