---
title: "Collation of Byz^RP^ vs 30176 (176)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 176 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30176).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 176                                   	| λογος                              	|
| 176 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 176 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 176               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 176                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 176 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 176                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [υιου]{.greek-abbr} του [θεου]{.greek-abbr}[1:1]{.aside}

[ως]{.greek-omitted} [καθως]{.greek-added} γεγραπται εν [τοις]{.greek-omitted} [προφηταις]{.greek-omitted} [ησαια]{.greek-added} [τω]{.greek-added} [πρωφητη]{.greek-added} ιδου εγω αποστελλω τον αγγελον μου προ προσωπου [μου]{.greek-added} [σου]{.corr} ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντ[ος]{.unclear} εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας [ποιητε]{.greek-added} [ποιειτε]{.corr} τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} προς αυτον πασα η ιουδαια χωρα και [οι]{.greek-omitted} [ιερσολυμιται]{.greek-added} [ιεροσολυμιται]{.corr} και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και εκηρυσσεν λεγων [οτι]{.greek-added} ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε [υμας]{.greek-added} βαπτισει [υμας]{.greek-omitted} εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ιησους]{.greek-abbr} απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} της γαλιλαιας και εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος ειδεν σχιζομενους τους [ουρανους]{.greek-abbr} και [το]{.greek-omitted} [πνευμα]{.greek-abbr} [[θεου]{.greek-abbr}]{.greek-added} ωσει περιστεραν καταβαινον [και]{.greek-added} [μενον]{.greek-added} επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ [τω]{.greek-added} [των]{.corr} [ουρανων]{.greek-abbr} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} [εκβαλλει]{.greek-added} αυτον [εκβαλλει]{.greek-omitted} εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειρα[ζ]{.unclear}ομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι [τον]{.greek-omitted} ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

[και]{.greek-omitted} λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν σιμωνα και ανδρεαν τον αδελφον αυτου [του]{.greek-omitted} [σιμωνος]{.greek-omitted} βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} [δευτε]{.greek-omitted} [δευται]{.greek-added} οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr} [γενεσθαι]{.greek-added}[1:17]{.aside}

και [ευθεως]{.greek-omitted} [ευθεος]{.greek-added} αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον του ζεβεδαιου [[ζεβεδεου]{.corr}]{.greek-added} και ιωαννην τον αδελφον αυτου και αυτους εν [τω]{.greek-omitted} [το]{.greek-added} πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν [τω]{.greek-omitted} [το]{.greek-added} πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι [γραμματεις]{.greek-omitted} [γραμματοις]{.greek-added}[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και ανεκραξεν[1:23]{.aside}

λεγων εα τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} ο [ιησους]{.greek-abbr} λεγων [φιμωθητι]{.greek-omitted} [φημωθητι]{.greek-added} και [εξελθε]{.greek-omitted} [εξηλθεν]{.greek-added} [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το [[πνευμα]{.greek-abbr}]{.greek-added} [πνευμα]{.corr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο [η]{.greek-added} τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν δε η ακοη αυτου ευθυς εις ολην την [περιχωρον]{.greek-omitted} [περιχορον]{.greek-added} της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν [σιμονος]{.greek-added} [σιμωνος]{.corr} και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο [πυρρεσσουσα]{.greek-added} [πυρεσσουσα]{.corr} και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και [προσελθων]{.greek-omitted} [προ[σ]{.unclear}ελθον]{.greek-added} [[προ[σ]{.unclear}]{.corr}]{.greek-added} [[ελθων]{.corr}]{.greek-added} ηγειρεν αυτην [κρατησας]{.greek-omitted} [κρατισας]{.greek-added} της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και [διηκονει]{.greek-omitted} [διηκονη]{.greek-added} αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δαιμονιζομενους]{.greek-omitted}[1:32]{.aside}

[οψιας]{.greek-omitted} [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [οτε]{.greek-omitted} [εδυ]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [εφερον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [παντας]{.greek-omitted} τους [κακος]{.greek-added} [κακως]{.corr} εχοντας και τους [δαιμονιζομενους]{.greek-omitted} [δεμονιζομενους]{.greek-added}[1:32 | instance no. 2]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και εθεραπευσεν πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα εξεβαλεν και ουκ ηφιεν λαλειν τα δαιμονια οτι ηδεισαν [τον]{.greek-added} [[χριστον]{.greek-abbr}]{.greek-added} αυτον [ειναι]{.greek-added}[1:34]{.aside}

και πρ[ω]{.unclear}ι εννυχον λιαν αναστας εξηλθεν και απηλθεν εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιοξαν]{.greek-added} αυτον ο [τε]{.greek-added} σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37]{.aside}

[και]{.unclear} λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων [και]{.greek-added} εις ολην την [γαλαιαν]{.greek-added} [γαλιλαιαν]{.corr} και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων [αυτον]{.greek-omitted} [αυτω]{.greek-added} και λεγων [αυτο[ν]{.unclear}]{.greek-added} [αυτω]{.corr} οτι εαν θελης [[κυριε]{.greek-abbr}]{.greek-added} δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [σπλαγχνισθεις]{.greek-omitted} [σπλαχνισθεις]{.greek-added} εκτεινας την χ[ει]{.unclear}ρα ηψατο αυτου και λεγει αυτω [θελω]{.greek-omitted} [θελο]{.greek-added} καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν [η]{.greek-added} [λεπρα]{.greek-added} απ αυτου [η]{.greek-omitted} [λεπρα]{.greek-omitted} και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτ[ο]{.unclear}ν[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α προσεταξεν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον παντ[α]{.unclear}χοθεν[1:45]{.aside}

### Chapter 2

και εισηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} παλιν εις καπερναο[υ]{.unclear}μ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φερ[ο]{.unclear}ντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι [προσεγγισαι]{.greek-omitted} [προσεγισαι]{.greek-added} αυτω δια τον οχλον απε[σ]{.unclear}τεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [εφ]{.greek-omitted} [ω]{.greek-omitted} [ο]{.greek-omitted} [παραλυτικος]{.greek-omitted} [κατεκειτο]{.greek-omitted}[2:4]{.aside}

[χαλωσι]{.greek-added} [και]{.greek-omitted} [μη]{.greek-omitted} [δυναμενοι]{.greek-omitted} [προσεγγισαι]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} τον [οχλον]{.greek-omitted} [απεστεγασαν]{.greek-omitted} [την]{.greek-omitted} [στεγην]{.greek-omitted} [οπου]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [εξορυξαντες]{.greek-omitted} [χαλωσιν]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [κραβανττον]{.greek-added} εφ ω ο παραλυτικος κατεκειτο[2:4 | instance no. 2]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον αφεωνται σοι [αι]{.corr} αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομενοι εν [ταις]{.greek-omitted} [τες]{.greek-added} καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτος]{.greek-added} [ουτως]{.corr} [λαλει]{.greek-omitted} [λαλη]{.greek-added} βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} [τω]{.greek-omitted} [το]{.greek-added} [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα διαλογιζεσθε εν [ταις]{.greek-omitted} [τες]{.greek-added} καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν [τω]{.greek-omitted} [το]{.greek-added} παραλυτικω αφεωνται σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} [και]{.greek-omitted} αρον [[ς]{.unclear}]{.greek-added} [[τον]{.corr}]{.greek-added} [κραβαντον]{.greek-added} [[κραββαντον]{.corr}]{.greek-added} σου [τον]{.greek-omitted} [κραββατον]{.greek-omitted} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιεναι]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

[σοι]{.greek-omitted} [συ]{.greek-added} λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} [και]{.greek-omitted} αρον [τ]{.greek-supplied}ον [κραβανγον]{.greek-added} [κραββατον]{.greek-omitted} [[κραβαττον]{.corr}]{.greek-added} σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως κ[α]{.unclear}[ι]{.greek-supplied} αρας [τον]{.greek-omitted} [των]{.greek-added} [κραβανγον]{.greek-added} [κραββατον]{.greek-omitted} [[κραβαττον]{.corr}]{.greek-added} [αυτου]{.greek-added} εξηλθεν [εναντιον]{.greek-omitted} [εναντι[ω]{.unclear}ν]{.greek-added} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε [ουτος]{.greek-added} [ουτως]{.corr} ειδομεν[2:12]{.aside}

και εξηλθεν παλιν παρα την θαλασσα[ν]{.unclear} και πας ο οχλος [η]{.unclear}ρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων ειδεν [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του [αλφαιου]{.greek-omitted} [αλφεου]{.greek-added} καθημενον επι το τελωνιον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-omitted} [[ιησους]{.greek-abbr}]{.greek-added} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν α[υ]{.unclear}τω[2:15]{.aside}

και οι γραμματεις [και]{.unclear} οι φαρισαιοι ιδοντες [αυτον]{.greek-omitted} [αυτων]{.greek-added} εσθιοντα μετα των τελωνων και αμαρτωλων [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} τοις μαθηταις αυτου τι οτι μετα των τελωνων και [αμαρτωλων]{.greek-omitted} [αμαρτολων]{.greek-added} εσθιει και πινει [ο]{.greek-added} [διδασκαλος]{.greek-added} [υμων]{.greek-added}[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι [κακος]{.greek-added} [κακως]{.corr} εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις [μετανοιαν]{.greek-omitted} [μετανιαν]{.greek-added}[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι [μαθηται]{.greek-omitted} ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη [[δυ]{.unclear}ναται]{.greek-added} [[δυ]{.unclear}νανται]{.corr} οι [υ]{.unclear}ιοι του [νυμφωνος]{.greek-omitted} [νυμφ[ω]{.unclear}]{.greek-added} [εν]{.greek-omitted} [ω]{.greek-omitted} [ο]{.greek-omitted} [νυμφιος]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted} [εστιν]{.greek-omitted} [νηστευειν]{.greek-omitted} [οσον]{.greek-omitted} [χρονον]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [εχουσιν]{.greek-omitted} [τον]{.greek-omitted} [νυμφιον]{.greek-omitted} [ου]{.greek-omitted} [δυνανται]{.greek-omitted} [νηστευειν]{.greek-omitted}[2:19]{.aside}

[νος]{.greek-added} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [μη]{.greek-omitted} [δυνανται]{.greek-omitted} [οι]{.greek-omitted} [υιοι]{.greek-omitted} [του]{.greek-omitted} [νυμφωνος]{.greek-omitted} εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} [νηστευει]{.greek-added} [νηστευειν]{.corr} οσον χρονον [μεθ]{.greek-omitted} [μετ]{.greek-added} [εαυτων]{.greek-omitted} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19 | instance no. 2]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευσωσιν]{.greek-added} εν εκειναις ταις ημεραις[2:20]{.aside}

[και]{.greek-omitted} ουδεις [επιβλημα]{.greek-omitted} [επιβλημμα]{.greek-added} [ρακους]{.greek-omitted} [ρακκους]{.greek-added} αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω ει δε μη [αιρει]{.greek-omitted} [αιρη]{.greek-added} το πληρωμα [απ]{.greek-added} αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις [[οι]{.unclear}[―]{.gap}]{.greek-added} [[ασ]{.unclear}κους]{.corr} παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι [ασ]{.unclear}κοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον ε[ι]{.unclear}ς ασκους καινους βλητεον[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις [σαβασι]{.greek-added} [σαββασιν]{.greek-omitted} [[σαββασι]{.corr}]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτο[υ]{.unclear} [οδον]{.greek-omitted} [ποιειν]{.greek-omitted} [οδοποιειν]{.greek-added} [τιλλοντες]{.greek-omitted} [τιλλοτες]{.greek-added} τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο [ου]{.unclear}κ εξεστιν[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι εποιησ[ε]{.unclear}ν [δαυιδ]{.greek-abbr} οτε χρειαν εσχεν και επεινασεν αυτος και [οι]{.unclear} μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τ[ο]{.unclear}ν οικον του [θεου]{.greek-abbr} επι αβιαθαρ [του]{.greek-added} αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και εδωκεν και τοις συν αυτω ουσιν[2:26]{.aside}

και ελεγεν αυτοις το σαββατον [δ]{.unclear}[ια]{.greek-supplied} [το]{.unclear}[ν]{.greek-supplied} [ανθρωπον]{.greek-omitted} [δια]{.greek-added} [τον]{.greek-added} [[ανον]{.greek-abbr}]{.greek-added} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην [εχ[―]{.gap}ν]{.greek-added} [εχων]{.corr} την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυ[του]{.unclear}[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-omitted} [[ανω]{.greek-abbr}]{.greek-added} τω [ε]{.unclear}ξηραμμενην εχοντι την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις τ[ο]{.unclear} μεσον[3:3]{.aside}

και λεγει αυτοις εξεσ[τ]{.unclear}ιν [εν]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειν[αι]{.unclear} οι δε [εσι]{.unclear}ωπων[3:4]{.aside}

και πε[ρ]{.unclear}[ι]{.greek-supplied}[βλ]{.unclear}ε[ψ]{.unclear}αμενος αυτους [με]{.unclear}τ ο[ρ]{.unclear}γης συλλυπουμεν[ος]{.unclear} επ[ι]{.unclear} τη [πορωσει]{.greek-added} [πωρωσει]{.corr} της κα[ρδι]{.unclear}ας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα [σου]{.greek-omitted} και εξ[ε]{.unclear}τεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατε[σ]{.unclear}τ[α]{.unclear}θη]{.greek-added} η χειρ αυτου υγιης [ως]{.unclear} [η]{.unclear} αλλη[3:5]{.aside}

και [εξε]{.unclear}λθοντες οι φαρισαι[ο]{.unclear}[ι]{.greek-supplied} ευθ[ε]{.unclear}ως μετα των ηρω[δ]{.greek-supplied}ιανω[ν]{.unclear} [συμβουλιον]{.greek-omitted} [εποιουν]{.greek-omitted} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} [οπως]{.greek-omitted} [αυτον]{.greek-omitted} [απολεσωσιν]{.greek-omitted}[3:6]{.aside}

[και]{.greek-omitted} [εξελθοντες]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ευθεως]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [ηρωδιανων]{.greek-omitted} συμβουλιον εποιουν κατ αυτου οπως αυτον απολεσωσιν[3:6 | instance no. 2]{.aside}

και ο [ιησους]{.greek-abbr} ανεχωρησεν μετα των [μαθητων]{.greek-omitted} αυτου [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [ηκολουθησεν]{.greek-added} αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και [σιδονα]{.greek-added} [σιδωνα]{.corr} πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθ[ε]{.unclear}ραπευσεν ωστε επιπιπτειν αυτω ινα [αυτου]{.greek-omitted} [ατου]{.greek-added} αψωνται οσοι ειχον [μαστιγας]{.greek-omitted} [μαστηγας]{.greek-added}[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [αθαρτα]{.greek-added} οταν αυτον εθεωρει προσεπιπτεν αυτω και εκραζεν λεγοντα οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και εποιησεν δωδεκα ινα ωσιν μετ αυτ[ου]{.unclear} και ινα αποστελλη αυτ[ο]{.unclear}[υ]{.greek-supplied}ς κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και επεθηκεν τω σιμωνι [ονομα]{.greek-omitted} πετρο[ν]{.unclear}[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [του]{.greek-omitted} ιακωβου και επεθηκεν αυτοις ονοματα [βοανεργες]{.greek-omitted} [βοανηργες]{.greek-added} ο εστιν [υιοι]{.greek-omitted} [υιος]{.greek-added} βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον [τον]{.greek-added} [τελωνην]{.greek-added} και θωμαν και ιακωβον τον [του]{.greek-omitted} [αλφαιου]{.greek-omitted} [αλφεου]{.greek-added} και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν [ο]{.greek-added} οχλος ωστε μη δυνασθαι αυτους [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες [οι]{.corr} παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και [προσκαλεσαμενος]{.greek-omitted} [προοσκαλεσαμενος]{.greek-added} αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας [σαταναν]{.greek-omitted} [εκβαλλειν]{.greek-omitted}[3:23]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [πως]{.greek-omitted} [δυναται]{.greek-omitted} [σατανας]{.greek-omitted} σαταναν εκβαλλειν[3:23 | instance no. 2]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου [εισελθων]{.greek-omitted} [εισελθον]{.greek-added} εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και [τ[ω]{.unclear}τε]{.greek-added} [τοτε]{.corr} την οικιαν αυτου διαρπαση[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα [αμαρτηματα]{.greek-omitted} [αμαρτιματα]{.greek-added} τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} [ειπον]{.greek-omitted} [ειπαν]{.greek-added} δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω ζητουσιν σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει ιδε η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} εστιν[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκ[ε]{.unclear}ν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν επεσεν παρα την οδο[ν]{.unclear} και ηλθεν τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε [ανατειλαντος]{.greek-omitted} [εκαυματισθη]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [μη]{.greek-omitted} [εχειν]{.greek-omitted} [ριζαν]{.greek-omitted} [εξηρανθη]{.greek-omitted}[4:6]{.aside}

[ηλιου]{.greek-omitted} [δε]{.greek-omitted} ανατειλαντος [εκαυματισθη]{.greek-omitted} [εκαματισθη]{.greek-added} και δια το μη εχειν ριζαν εξηρανθη[4:6 | instance no. 2]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ εδωκεν[4:7]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο [εχων]{.greek-omitted} [εχον]{.greek-added} [ωτα]{.greek-omitted} [οτα]{.greek-added} [ακου[ετω]{.unclear}]{.greek-added} [ακουειν]{.corr} ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον [[αυτων]{.corr}]{.greek-added} συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν [αυτο[―]{.gap}ς]{.greek-added} [αυτοις]{.corr} υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} [παντα]{.greek-omitted} [γινεται]{.greek-omitted}[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και μη συνιωσιν [μηποτε]{.greek-omitted} [μηπωτε]{.greek-added} επιστρεψωσιν και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

[ο]{.greek-omitted} [[ω]{.unclear}]{.greek-added} σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν [ταις]{.greek-omitted} [τες]{.greek-added} καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως [οι]{.greek-omitted} επι τα πετρωδη σπειρομενοι οι οταν ακουσωσιν τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ εχουσιν ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι [τον]{.greek-omitted} [των]{.greek-added} λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και [καρπο[ν]{.unclear}]{.greek-added} [φ[ε]{.unclear}ρουσιν]{.greek-added} [καρποφορουσιν]{.corr} [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} αυτοις μητι ο λυχνος [ερχε]{.greek-added} [ερχεται]{.greek-omitted} [ινα]{.greek-omitted} [υπο]{.greek-omitted} [τον]{.greek-omitted} [μοδιον]{.greek-omitted} [τεθη]{.greek-omitted} [η]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [κλινην]{.greek-omitted} [ουχ]{.greek-omitted} [ινα]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [λυχνιαν]{.greek-omitted} [επιτεθη]{.greek-omitted}[4:21]{.aside}

[ται]{.greek-added} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [μητι]{.greek-omitted} [ο]{.greek-omitted} [λυχνος]{.greek-omitted} [ερχεται]{.greek-omitted} ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα [επι]{.greek-omitted} [υπο]{.greek-added} την λυχνιαν [επιτεθη]{.greek-omitted} [υποτεθη]{.greek-added}[4:21 | instance no. 2]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} [κρυπτον]{.greek-omitted} [κρυπτ[ω]{.unclear}ν]{.greek-added} ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} υμιν και [προστεθησεται]{.greek-omitted} [πρ[ω]{.unclear}στεθησεται]{.greek-added} υμιν τοις ακουουσιν[4:24]{.aside}

[ος]{.greek-omitted} [ως]{.greek-added} γαρ αν εχη δοθησ[ε]{.unclear}ται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν [ουτος]{.greek-added} [ουτως]{.corr} εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [βαλει]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και μηκυνηται [[μηκυνεται]{.corr}]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη [σ]{.greek-supplied}ιτον εν τω σταχυι[4:28]{.aside}

ο[τ]{.greek-supplied}αν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν ποια [παραβολ[η]{.greek-supplied}]{.corr} [παραβαλωμεν]{.greek-omitted} [παρβαλωμεν]{.greek-added} αυτην[4:30]{.aside}

ως κοκκον σιναπεως ος οταν σπαρη επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκην[ου]{.unclear}ν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθω[ς]{.unclear} [εδυναντο]{.greek-omitted} [εδυνατο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μα[θ]{.unclear}ηται[ς]{.unclear} αυτου επελυεν παντα[4:34]{.aside}

και λεγει αυτοις ε[ν]{.unclear} ε[κε]{.unclear}ινη τη ημερα οψιας γενομενης διελθωμε[ν]{.unclear} εις το περαν[4:35]{.aside}

και αφεντ[ε]{.unclear}[ς]{.greek-supplied} τον οχλον παραλ[α]{.unclear}μβ[α]{.unclear}νουσιν αυτον ως η[ν]{.unclear} [εν]{.unclear} [τ]{.unclear}[ω]{.greek-supplied} πλοιω και αλλα [δε]{.unclear} [πλοι]{.greek-supplied}αρια ην μετ αυτ[ο]{.unclear}[υ]{.greek-supplied}[4:36]{.aside}

και γ[ι]{.greek-supplied}νεται λαιλα[ψ]{.unclear} α[ν]{.unclear}εμ[ου]{.unclear} μεγαλη τα δε κυματ[α]{.unclear} [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε αυτο ηδη [γε]{.unclear}μιζ[εσ]{.unclear}θαι[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι το [προ[σ]{.unclear}]{.greek-added} [προσκεφαλαιον]{.greek-omitted} [καθευδων]{.greek-omitted} [και]{.greek-omitted} [διεγειρουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [οτι]{.greek-omitted} [απολλυμεθα]{.greek-omitted}[4:38]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [αυτος]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [πρυμνη]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [προσκεφαλαιον]{.greek-omitted} [κεφαλαιον]{.greek-added} καθευδων και διεγειρουσιν [αυτω]{.greek-added} [αυτον]{.corr} και λεγουσιν αυτω διδασκαλε ου μελει σοι οτι απολλυμεθα[4:38 | instance no. 2]{.aside}

και διεγερθεις επετιμησεν τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [πεφημωσω]{.greek-added} και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε [ουτως]{.greek-omitted} [ουτος]{.greek-added} πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και [ο]{.greek-omitted} [οι]{.greek-added} [ανεμος]{.greek-omitted} [ανεμοι]{.greek-added} και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις [εδυνατο]{.greek-omitted} [εδυνατ[ω]{.unclear}]{.greek-added} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δεδεσθαι]{.greek-omitted} [δεδαισθαι]{.greek-added} και [διεσπασθαι]{.greek-omitted} [διασπασθαι]{.greek-added} υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [εδυνατ[ο]{.unclear}]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημασι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ωρεσιν]{.greek-added} [[ορεσιν]{.corr}]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} απο μακροθεν εδραμεν και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

ελεγεν γαρ αυτω εξελθε το πνευμα το ακαθαρτον [εκ]{.greek-omitted} [απο]{.greek-added} του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι [ονομα]{.greek-added} σοι [ονομα]{.greek-omitted} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη [αποστειλει]{.greek-added} αυτους [αποστειλη]{.greek-omitted} εξω της χωρας[5:10]{.aside}

ην δε εκει [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων μεγαλη βοσκομενη [προς]{.greek-added} [το]{.greek-added} [ορει]{.greek-added}[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον [παντες]{.greek-omitted} οι δαιμονες [παντες]{.greek-added} λεγοντες πεμψον ημας εις τους χοιρους ινα ει[ς]{.unclear} [αυ]{.unclear}τους εισελθωμεν[5:12]{.aside}

[κ]{.unclear}αι επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} [τα]{.greek-omitted} ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του [κρημνου]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [ησαν]{.greek-omitted} [δε]{.greek-omitted} [ως]{.greek-omitted} [δισχιλιοι]{.greek-omitted} [και]{.greek-omitted} [επνιγοντο]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted}[5:13]{.aside}

[και]{.greek-omitted} [επετρεψεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εξελθοντα]{.greek-omitted} [τα]{.greek-omitted} [πνευματα]{.greek-omitted} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [εισηλθον]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [και]{.greek-omitted} [ωρμησεν]{.greek-omitted} [η]{.greek-omitted} [αγελη]{.greek-omitted} [κατα]{.greek-omitted} [του]{.greek-omitted} κρημνου εις την θαλασσαν [ησαν]{.greek-omitted} [εισαν]{.greek-added} δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13 | instance no. 2]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και εξηλθον ιδειν [τι]{.greek-omitted} [εστιν]{.greek-omitted} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και [σωφρονουντα]{.greek-omitted} [σοφρονουντα]{.greek-added} τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

διηγησαντο δε αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον [απελθειν]{.greek-omitted} [ινα]{.greek-added} [μεταβει]{.greek-added} απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} μετ αυτου [η]{.greek-added}[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκ[η]{.unclear}]{.greek-added} και ηλεησεν σε[5:19]{.aside}

και απ[ηλ]{.unclear}θεν και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} [κ]{.unclear}αι παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις [τ]{.unclear}[ο]{.greek-supplied} περαν συνηχθη οχλο[ς]{.unclear} πολυς επ αυτον κα[ι]{.unclear} ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται [ει]{.unclear}ς των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και πα[ρ]{.unclear}εκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα [ελθον]{.greek-added} [ελθων]{.corr} επιθης αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και απηλθεν μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν [ωφεληθεισα]{.greek-omitted} [οφεληθεισα]{.greek-added} αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

ελεγεν γαρ οτι καν των ιματιων αυτου αψ[ω]{.unclear}μαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη [η]{.unclear} [π]{.greek-supplied}[η]{.unclear}γη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστ[ι]{.unclear}γος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} [επιγνους]{.greek-omitted} [εν]{.greek-omitted} [εαυτω]{.greek-omitted} [την]{.greek-omitted} [εξ]{.greek-omitted} [αυτου]{.greek-omitted} [δυναμιν]{.greek-omitted} [εξελθουσαν]{.greek-omitted} [επιστραφεις]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [ελεγεν]{.greek-omitted} [τις]{.greek-omitted} [μου]{.greek-omitted} [ηψατο]{.greek-omitted} [των]{.greek-omitted} [ιματιων]{.greek-omitted}[5:30]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30 | instance no. 2]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα [διο]{.greek-added} [πεποιηκεν]{.greek-added} [λαθρα]{.greek-added} ειδυια ο γεγονεν επ αυτη ηλθεν και π[ρ]{.unclear}οσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου σεσωκεν σε υπαγε εις ειρηνην [και]{.greek-supplied} [ισθι]{.greek-omitted} [ισθη]{.greek-added} υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου απεθανεν τι [ε]{.unclear}τ[ι]{.unclear} σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεω[ς]{.unclear} α[κ]{.unclear}ουσας τον λογον [λα]{.unclear}λουμ[ε]{.unclear}νον λεγει τ[ω]{.unclear} [αρχισυναγωγω]{.greek-omitted} [[αρ]{.unclear}χ[ι]{.greek-supplied}συναγω]{.greek-added} μη φοβ[ου]{.unclear} μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα [α]{.unclear}υ[τω]{.unclear} [συν]{.greek-supplied}ακολουθησ[αι]{.unclear} ει μη [πετρ]{.greek-supplied}ον και ιακω[βο]{.unclear}ν και [ι]{.greek-supplied}ωαννην τον α[δ]{.unclear}ελ[φο]{.unclear}[ν]{.greek-supplied} [ιακωβου]{.greek-omitted} [αυτου]{.greek-added}[5:37]{.aside}

και ερχεται εις το[ν]{.unclear} οικον του αρχισυν[α]{.unclear}γωγου και θεω[ρει]{.unclear} θορυβον κλαι[οντα]{.unclear}ς και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτ[ο]{.unclear}ις τι [θορυβεισθε]{.greek-omitted} [θο[ρυ]{.unclear}β[ει]{.unclear}σθαι]{.greek-added} και κλαιε[τε]{.unclear} το παιδιο[ν]{.unclear} ουκ α[π]{.unclear}[ε]{.greek-supplied}θανεν αλλα καθε[υ]{.unclear}δει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} [του]{.unclear} [παι]{.unclear}διου και την [μητερα]{.greek-abbr} [και]{.greek-omitted} τους μετ αυτου και εισ[π]{.unclear}ορευεται οπου ην το παιδιον ανακει[μ]{.unclear}ενον[5:40]{.aside}

και κρατησ[ας]{.greek-supplied} της χειρος του [π]{.unclear}[αι]{.greek-supplied}[δ]{.unclear}ιου λεγει αυτη [ταλιθα]{.greek-omitted} [[τ]{.greek-supplied}αληθα]{.greek-added} κουμι ο [εστιν]{.greek-omitted} [[εστ]{.unclear}ι]{.greek-added} μεθερμηνε[υ]{.unclear}ομενον το [κο]{.unclear}ρασιον σ[οι]{.greek-supplied} λεγ[ω]{.unclear} [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως αν[εστη]{.unclear} τ[ο]{.unclear} [κ]{.unclear}[ο]{.greek-supplied}[ρα]{.unclear}σιο[ν]{.unclear} και [π]{.unclear}ερι[επατει]{.unclear} ην γαρ ετω[ν]{.unclear} [δ]{.unclear}ω[δ]{.unclear}εκα και εξεστησ[αν]{.unclear} εκστασει μεγαλη[5:42]{.aside}

και [δι]{.unclear}εστειλατο αυτοις πολλα ινα μηδεις γνω τ[ο]{.unclear}υτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και [ε]{.unclear}ξηλθεν [εκειθεν]{.greek-omitted} [και]{.greek-omitted} [ηλθεν]{.greek-omitted} εις την πατριδα αυτου [και]{.greek-omitted} [ακολουθουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted}[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν [τη]{.greek-omitted} [συναγωγη]{.greek-omitted} [διδασκειν]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [ακουοντες]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [ποθεν]{.greek-omitted} [τουτω]{.greek-omitted} [ταυτα]{.greek-omitted} [και]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [η]{.greek-omitted} [δοθεισα]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [δυναμεις]{.greek-omitted} [τοιαυται]{.greek-omitted} [δια]{.greek-omitted} [των]{.greek-omitted} [χειρων]{.greek-omitted} [αυτου]{.greek-omitted} [γινονται]{.greek-omitted}[6:2]{.aside}

[και]{.greek-omitted} [γενομενου]{.greek-omitted} [σαββατου]{.greek-omitted} [ηρξατο]{.greek-omitted} [εν]{.greek-omitted} τη συναγωγη διδασκει[ν]{.unclear} και πολλοι ακουοντες [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [ελεγων]{.greek-added} [εν]{.greek-added} [ε[αυτ]{.unclear}οις]{.greek-added} ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτ[α]{.unclear} και τις η σοφια η δοθεισα αυτω και δυναμεις τ[ο]{.unclear}[ι]{.greek-supplied}αυται δια τω[ν]{.unclear} χειρων αυτου γινονται[6:2 | instance no. 2]{.aside}

ουχ ουτος εστιν ο [του]{.greek-added} [τεκτων]{.greek-omitted} [τ[ε]{.unclear}κτωνος]{.greek-added} ο [υιος]{.greek-abbr} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμω[ν]{.unclear}ος και ουκ εισιν αι αδελφα[ι]{.unclear} αυτο[υ]{.unclear} ωδε προς ημας και εσκανδαλ[ι]{.unclear}ζοντο εν αυτω[6:3]{.aside}

ελ[ε]{.unclear}γεν δε αυτοις ο [ιησους]{.greek-abbr} οτι ο[υ]{.unclear}κ εστιν προφητης ατιμος ει μη εν τη πατριδι αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγενευσιν]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει [μη]{.greek-omitted} [μι]{.greek-added} ολιγοις αρρωστοις επιθεις τας χειρας εθεραπευσεν[6:5]{.aside}

και εθαυμαζεν δια τη[ν]{.unclear} απιστιαν αυτων [κ]{.unclear}αι περιηγεν τας κωμα[ς]{.unclear} κυκλω διδασκων[6:6]{.aside}

και προσκαλει[τ]{.unclear}αι [το]{.unclear}υς δωδεκα και ηρξατο αυ[τ]{.unclear}ους αποστελλειν [δ]{.unclear}υο δυο και [ε]{.unclear}διδου αυ[τ]{.unclear}[οις]{.greek-supplied} εξουσιαν των π[ν]{.unclear}ε[υμ]{.unclear}ατ[ω]{.unclear}ν [των]{.unclear} ακαθ[α]{.unclear}ρ[τ]{.unclear}ων[6:7]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρ[η]{.unclear}γγελεν]{.greek-added} αυτοις ινα μηδεν αιρωσιν εις [την]{.greek-added} οδον [ει]{.unclear} μη ραβδον [μονον]{.greek-omitted} μη πηραν μη αρτον [μη]{.greek-omitted} [μηδε]{.greek-added} εις την [ζωνην]{.greek-omitted} [ζονην]{.greek-added} χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενου[ς]{.unclear} σανδαλια κα[ι]{.unclear} μη ενδυσησθε [δυ]{.greek-added} [δυο]{.corr} χι[τ]{.unclear}ω[ν]{.unclear}ας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν [εισελθητε]{.greek-omitted} [ελθητε]{.greek-added} εις οικιαν εκει μενετε εως αν εξελθητε [εκειθεν]{.greek-omitted} [εκηθεν]{.greek-added}[6:10]{.aside}

και [οσοι]{.greek-omitted} [ος]{.greek-added} [αν]{.greek-omitted} [εαν]{.greek-added} μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον χουν [τον]{.greek-omitted} [των]{.greek-added} υποκατω των π[ο]{.unclear}δ[ω]{.unclear}ν υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η γομορροις εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον [[εκηρυσσων]{.corr}]{.greek-added} ινα μετανοησωσιν[6:12]{.aside}

και δαιμονια πολλα [εξεβαλλον]{.greek-omitted} [εξεβαλον]{.greek-added} και ηλειφον ελαιω πολλους αρρω[στο]{.unclear}υς και εθεραπευον[6:13]{.aside}

και ηκουσεν [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ε[λ]{.unclear}εγεν οτι ιωαννης ο β[απτι]{.unclear}ζων εκ νεκρων ηγερθη και δ[ι]{.unclear}α τουτο ενεργ[ο]{.unclear}υσιν α[ι]{.unclear} δυναμε[ι]{.unclear}ς εν αυτω[6:14]{.aside}

[α]{.unclear}λλοι ελε[γ]{.unclear}ον οτι ηλιας εστι[ν]{.unclear} αλλοι δε ελεγο[ν]{.unclear} οτι προφη[τ]{.unclear}ης εστιν [ω]{.unclear}ς εις των π[ρο]{.unclear}φητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} [ιωαννην]{.greek-omitted} [ιωανην]{.greek-added} ουτος εστιν αυτος [γαρ]{.greek-added} ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο ιωαννης τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητο]{.greek-added} τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις [μεγιστασιν]{.greek-omitted} [μεγιστανσιν]{.greek-added} αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης [της]{.greek-omitted} ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις [συνανακειμενοις]{.greek-omitted} [υνανακειμενοις]{.greek-added} ειπεν ο βασιλευς τω κορασιω [αιτησον]{.greek-omitted} [αιτισον]{.greek-added} με ο εαν θελης και δωσω σοι[6:22]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [αιτησης]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted} εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε ειπεν την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης [προς]{.greek-omitted} [εις]{.greek-added} τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την [κεφαλην]{.greek-omitted} [καιφαλην]{.greek-added} αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και [ακου]{.greek-added} [ακουσαντες]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθον]{.greek-omitted} [και]{.greek-omitted} [ηραν]{.greek-omitted} [το]{.greek-omitted} [πτωμα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εθηκαν]{.greek-omitted} [αυτο]{.greek-omitted} [εν]{.greek-omitted} [μνημειω]{.greek-omitted}[6:29]{.aside}

[και]{.greek-omitted} [ακουσαντες]{.greek-omitted} [σαντες]{.greek-added} οι μαθηται αυτου ηλθον και ηραν το [πτωμα]{.greek-omitted} [σωμα]{.greek-added} αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29 | instance no. 2]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε [αυτοι]{.greek-added} υμεις [αυτοι]{.greek-omitted} κατ ιδιαν εις ερημον τοπον και αναπαυεσθε ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} εις ερημον τοπον τω [πλοιω]{.greek-omitted} [πλοιον]{.greek-added} κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [προηγουν]{.greek-added} αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ο [ιησους]{.greek-abbr} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσ[ελ]{.unclear}θοντες [αυτω]{.greek-omitted} οι μαθηται αυτου λεγουσιν οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας [αγορασωσιν]{.greek-omitted} [αγωρασωσιν]{.greek-added} εαυτοις αρτους [τ]{.unclear}ι γαρ φαγωσιν [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted}[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις [ο]{.greek-added} φαγειν και λεγουσιν [[αυ]{.unclear}αυτω]{.greek-added} [αυτω]{.corr} απελθοντες [αγορασωμεν]{.greek-omitted} [αγωρασωμεν]{.greek-added} [διακοσιων]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και [ανα]{.greek-omitted} πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} ευλογησεν και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} πασιν[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους [ως]{.greek-added} πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως ηναγκασεν τους μαθητας αυτου εμβηναι [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [και]{.greek-omitted} [προαγειν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} [προς]{.greek-omitted} [βηθσαιδαν]{.greek-omitted} [εως]{.greek-omitted} [αυτος]{.greek-omitted} [απολυση]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted}[6:45]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [ηναγκασεν]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [εμβηναι]{.greek-omitted} εις το πλοιον και προαγειν [αυτους]{.greek-added} [εις]{.greek-omitted} [το]{.greek-omitted} περαν προς βηθσαιδαν εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [τους]{.greek-added} [οχλους]{.greek-added}[6:45 | instance no. 2]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτ[ο]{.unclear}ς ερχεται [προς]{.greek-omitted} [π[ο]{.unclear}ρς]{.greek-added} [[πρρς]{.corr}]{.greek-added} αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ [αυτον]{.greek-omitted} ειδον και εταραχθησαν και ευθ[ε]{.unclear}ως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ αυτων η καρδια [πεπωρωμενη]{.greek-omitted} [πεπορρωμενη]{.greek-added}[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρεθ]{.greek-added} και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον [οι]{.greek-added} [ανδρες]{.greek-added} [του]{.greek-added} [τοπου]{.greek-added}[6:54]{.aside}

περιδραμοντες ολην την [περιχωρον]{.greek-omitted} [περιχωρ]{.greek-added} εκεινην ηρξαντο επι τοις [κραββατοις]{.greek-omitted} [κραβαττοις]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει εστιν[6:55]{.aside}

και οπου αν εισεπορευετο εις [πολεις]{.greek-added} [η]{.greek-added} [εις]{.greek-added} κωμας [η]{.greek-omitted} [πολεις]{.greek-omitted} η αγρους εν ταις αγοραις [ετιθουν]{.greek-omitted} [ετηθουν]{.greek-added} τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} [και]{.corr} οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις χερσιν τουτ εστιν ανιπτοις εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη [βαπτισωνται]{.greek-omitted} [βαπτισονται]{.greek-added} ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα π[ο]{.unclear}λλα εστιν α παρελα[β]{.unclear}ο[ν]{.unclear} [κρατειν]{.greek-omitted} [βαπτισμους]{.greek-omitted} [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [χαλκιων]{.greek-omitted} [και]{.greek-omitted} [κλινων]{.greek-omitted}[7:4]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [αγορας]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [βαπτισωνται]{.greek-omitted} [ουκ]{.greek-omitted} [εσθιουσιν]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [πολλα]{.greek-omitted} [εστιν]{.greek-omitted} [α]{.greek-omitted} [παρελαβον]{.greek-omitted} κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4 | instance no. 2]{.aside}

[επειτα]{.greek-omitted} [επιτα]{.greek-added} επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την παραδοσιν των πρεσβυτερων [αλλα]{.greek-omitted} [αλλ]{.greek-added} ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις χειλεσιν με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα [τοιαυτα]{.greek-added} παρομοια [τοιαυτα]{.greek-omitted} πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως [αθετ[ι]{.unclear}τε]{.greek-added} [αθετειτε]{.corr} την εντολην του [θεου]{.greek-abbr} ινα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων τηρησητε[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σ[ου]{.unclear} και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} [θανατω]{.greek-omitted} [θανατο]{.greek-added} τελευτατω[7:10]{.aside}

υμεις δε λεγετε [οτι]{.greek-added} εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο εστιν δωρον ο [εαν]{.greek-omitted} εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} [αυτου]{.greek-omitted} η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωσει]{.greek-added} υμων η παρεδωκατε [και]{.corr} [π[αρομοια]{.greek-supplied}]{.corr} [τοια[υτα]{.greek-supplied}]{.corr} [πο[λ]{.unclear}[λα]{.greek-supplied}]{.corr} [ποιειτε]{.greek-omitted}[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις [ακουσατε]{.greek-added} [ακουετε]{.corr} μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο [ου]{.greek-added} δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου [εκεινα]{.greek-omitted} [εκοινα]{.greek-added} εστιν τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [βρωματα]{.greek-omitted}[7:19]{.aside}

ελεγεν δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-omitted} [οι]{.greek-omitted} [διαλογισμοι]{.greek-omitted} [οι]{.greek-omitted} [κακοι]{.greek-omitted} [εκπορευονται]{.greek-omitted} [μοιχειαι]{.greek-omitted} [πορνειαι]{.greek-omitted} [φονοι]{.greek-omitted}[7:21]{.aside}

[εσωθεν]{.greek-omitted} [γαρ]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι [φονοι]{.greek-omitted} [[κλω[παι]{.greek-supplied}]{.corr}]{.greek-added}[7:21 | instance no. 2]{.aside}

[κλοπαι]{.greek-omitted} [πλεονεξιαι]{.greek-omitted} [[πλαι[ονεξ]{.greek-supplied}ιαι]{.corr}]{.greek-added} [[πονηρ]{.greek-supplied}ιαι]{.corr} δολος [ασελγεια]{.greek-omitted} [ασελγειαι]{.greek-added} οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

[ακουσασα]{.greek-omitted} [ακουσας]{.greek-added} γαρ γυνη περι αυτου ης ειχεν το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα προσεπεσεν [προς]{.greek-omitted} [εις]{.greek-added} τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συροφοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον [εκ]{.greek-omitted} [απο]{.greek-added} της θυγατρος σου[7:29]{.aside}

και [απελθουσα]{.greek-omitted} [ελθουσα]{.greek-added} εις τον οικον αυτης ευρεν το δαιμονιον [εξεληλυθος]{.greek-omitted} [εξεληλυθως]{.greek-added} και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος ηλθεν προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον [μογγιλαλον]{.greek-omitted} [μογιλαλον]{.greek-added} και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου [πτυσας]{.greek-added} εις τα ωτα αυτου και [πτυσας]{.greek-omitted} ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} εστεναξεν και λεγει αυτω εφφαθα ο εστιν διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα [μηδενι]{.greek-omitted} [μηδεν]{.greek-added} ειπωσιν οσον δε [αυτοις]{.greek-added} αυτος [αυτοις]{.greek-omitted} διεστελλετο μαλλον περισσοτερον [εκηρυσσον]{.greek-omitted} [εκηρι]{.greek-added}[7:36]{.aside}

[σσων]{.greek-added} [και]{.greek-omitted} [διεστειλατο]{.greek-omitted} [αυτοις]{.greek-omitted} [ινα]{.greek-omitted} [μηδενι]{.greek-omitted} [ειπωσιν]{.greek-omitted} [οσον]{.greek-omitted} [δε]{.greek-omitted} [αυτος]{.greek-omitted} [αυτοις]{.greek-omitted} [διεστελλετο]{.greek-omitted} [μαλλον]{.greek-omitted} [περισσοτερον]{.greek-omitted} [εκηρυσσον]{.greek-omitted}[7:36 | instance no. 2]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις παμπολλου οχλου οντος και μη εχοντων τι φαγωσιν προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας [αυτου]{.greek-omitted} λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [παραμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχωσι]{.greek-added} τι φαγωσιν[8:2]{.aside}

και εαν [αυτους]{.greek-added} απολυσω [αυτους]{.greek-omitted} νηστεις εις [οικον]{.greek-omitted} [τους]{.greek-added} [οικους]{.greek-added} αυτων εκλυθησονται [εν]{.greek-omitted} [εκ]{.greek-added} τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκασιν]{.greek-added}[8:3]{.aside}

και απεκριθησαν [αυτω]{.greek-omitted} οι μαθηται αυτου ποθεν [τουτους]{.greek-omitted} [αυτους]{.greek-added} δυνησεται τις ωδε χορτασαι αρτων επ ερημιας[8:4]{.aside}

και [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγηλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας εκλασεν και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παρατιθωσιν]{.greek-added} και παρεθηκαν τω [οχλω]{.greek-omitted} [οχω]{.greek-added}[8:6]{.aside}

και ειχον ιχθυδια ολιγα και [αυτα]{.greek-added} ευλογησας ειπεν [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα [ταυτη]{.greek-omitted} [αυτη]{.greek-added} σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} λαβειν αρτους και ει [μη]{.greek-omitted} [μι]{.greek-added} ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε [βλεπετε]{.greek-omitted} απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους [λεγοντες]{.greek-omitted} [οτι]{.greek-omitted} [αρτους]{.greek-omitted} [ουκ]{.greek-omitted} [εχομεν]{.greek-omitted}[8:16]{.aside}

[και]{.greek-omitted} [διελογιζοντο]{.greek-omitted} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} λεγοντες οτι αρτους ουκ εχομεν[8:16 | instance no. 2]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους [πληρεις]{.greek-omitted} κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπ[υ]{.unclear}ριδων πληρωματα [κ]{.unclear}λασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις πως [ου]{.greek-omitted} [ουπω]{.greek-added} συνιετε[8:21]{.aside}

και ερχεται εις βηθσαιδαν και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω [επηρωτα]{.greek-omitted} [επιρωτα]{.greek-added} αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας ελεγεν βλεπω τους [ανθρωπους]{.greek-abbr} [οτι]{.greek-omitted} ως δενδρα [ορω]{.greek-omitted} περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψεν]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων [μηδε]{.greek-omitted} [υπαγε]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [εαν]{.greek-added} εις την κωμην εισελθης [μηδενι]{.greek-added} [μηδε]{.greek-omitted} [μηδεν]{.greek-added} ειπης [τινι]{.greek-omitted} εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας [καισαρειας]{.greek-omitted} [καισαριας]{.greek-added} της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [αυτω]{.greek-added} [οι]{.greek-added} [μεν]{.greek-added} ιωαννην τον βαπτιστην [και]{.greek-omitted} αλλοι [δε]{.greek-added} ηλιαν αλλοι [δε]{.greek-omitted} ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε [ο]{.greek-omitted} πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και [αποδοκιμασθηναι]{.greek-omitted} [αποδοκιμασθειναι]{.greek-added} [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και των αρχιερεων και των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι [και]{.corr} [μετα]{.corr} [τρ[ει]{.unclear}ς]{.corr} [ημερα[ς]{.unclear}]{.corr} [[αναστηναι]{.greek-supplied}]{.corr}[8:31]{.aside}

και παρρησια [τον]{.greek-omitted} [λογον]{.greek-omitted} [ελαλει]{.greek-omitted} [και]{.greek-omitted} [προσλαβομενος]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [ηρξατο]{.greek-omitted} [επιτιμαν]{.greek-omitted} [αυτω]{.greek-omitted}[8:32]{.aside}

[και]{.greek-omitted} [παρρησια]{.greek-omitted} τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32 | instance no. 2]{.aside}

ο δε [επιστραφεις]{.greek-omitted} [στραφεις]{.greek-added} και ιδων τους μαθητας αυτου επετιμησεν τω πετρω λεγων υπαγε [οπις]{.greek-added} [οπισω]{.corr} μου σατανα οτι ου φρονεις τα [τω]{.greek-added} [του]{.corr} [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [ει]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελει οπισω μου [ακολουθειν]{.greek-omitted} [ακουλουθειν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακουλουθειτω]{.greek-added} μοι[8:34]{.aside}

ος γαρ αν θελη [τ]{.unclear}ην ψυχ[η]{.unclear}ν αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την [εαυτου]{.greek-omitted} ψυχην [αυτου]{.greek-added} ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ [ωφελησει]{.greek-omitted} [οφελησει]{.greek-added} [τον]{.greek-added} [ανθρωπον]{.greek-abbr} εαν [κερδηση]{.greek-omitted} τον κοσμον ολον [κερδηση]{.greek-added} και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλα[γ]{.unclear}μα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη [μοιχαλιδι]{.greek-omitted} [και]{.greek-omitted} αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη [του]{.greek-omitted} [πατρος]{.greek-omitted} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι εισιν τινες των ωδε [εστηκοτων]{.greek-omitted} [εστικοτων]{.greek-added} οιτινες ου μη γευσωνται θανατου εως αν ιδωσιν την βασιλειαν του [θεου]{.greek-abbr} [εληλυθ[―]{.gap}αν]{.greek-added} [εληλυθυιαν]{.corr} εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον [ιωαννην]{.greek-added} [και]{.greek-added} ιακωβον [και]{.greek-omitted} [ιωαννην]{.greek-omitted} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματ[ι]{.unclear}α αυτου εγενοντο στιλβοντα λευκα λιαν ως χιων οια γναφευς επι της γης ου [δ]{.unclear}υναται λευκαναι[9:3]{.aside}

και [ωφθη]{.greek-omitted} [ωφθησαν]{.greek-added} αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυσει]{.greek-added} και ησαν [συλλαλουντες]{.greek-omitted} [συνλαλουντες]{.greek-added} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} [ραββι]{.greek-omitted} [ραββει]{.greek-added} καλον εστιν ημας ωδε ειναι και [θελεις]{.greek-added} ποιησωμεν σ[κην]{.unclear}α[ς]{.unclear} τρεις σοι μιαν και [μωση]{.greek-omitted} [μω[υσ]{.unclear}[ει]{.greek-supplied}]{.greek-added} μιαν και [ηλια]{.greek-omitted} [ηλιαν]{.greek-added} μια[ν]{.unclear}[9:5]{.aside}

ου γ[α]{.unclear}ρ ηδει τι λαλησει ησαν [γ]{.unclear}[αρ]{.greek-supplied} [ε]{.greek-supplied}κφοβοι[9:6]{.aside}

και [ιδου]{.greek-added} [εγενετω]{.greek-added} [εγενετο]{.corr} νεφελη επισκιαζουσα αυτοις και ηλθεν φωνη εκ της [νεφελης]{.greek-omitted} [φελης]{.greek-added} [λεγουσα]{.greek-added} ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητο[ς]{.greek-supplied} αυτου ακο[υ]{.unclear}ετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδ[ε]{.unclear}να [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλα τον [ιησουν]{.greek-abbr} μονο[ν]{.unclear} μεθ εαυτων[9:8]{.aside}

[καταβα[ι]{.unclear}]{.greek-added} [καταβαινοντων]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ορους]{.greek-omitted} [διεστειλατο]{.greek-omitted} [αυτοις]{.greek-omitted} [ινα]{.greek-omitted} [μηδενι]{.greek-omitted} [διηγησωνται]{.greek-omitted} [α]{.greek-omitted} [ειδον]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [οταν]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} [αναστη]{.greek-omitted}[9:9]{.aside}

[καταβαινοντων]{.greek-omitted} [νοντων]{.greek-added} δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγισονται]{.greek-added} [διηγησωνται]{.greek-omitted} [[διηγησονται]{.corr}]{.greek-added} α [ειδον]{.greek-omitted} [ιδον]{.greek-added} ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9 | instance no. 2]{.aside}

[και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} τον λογον εκρατησαν προς εαυτους συζητουντες τι εστιν το εκ νεκρων αναστηναι[9:10]{.aside}

και [επηρωτων]{.greek-omitted} [επηρωτον]{.greek-added} αυτον [οι]{.greek-added} [γραμματεις]{.greek-added} λεγοντες οτι λεγουσιν [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας εληλυθεν [[εληληθεν]{.corr}]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο ο[χ]{.unclear}λος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς [αυτους]{.greek-omitted} [αλληλους]{.greek-added}[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη [ρ]{.unclear}ησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και [ειπον]{.greek-omitted} [ει[πα]{.unclear}]{.greek-added} τοις μαθηταις σου ινα [αυτο]{.greek-omitted} [αυτον]{.greek-added} εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

[ο]{.greek-omitted} [[ω]{.unclear}]{.greek-added} δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτ[ε]{.unclear} προς υμας [εσομαι]{.greek-omitted} [εσωμαι]{.greek-added} εως ποτε ανεξομα[ι]{.unclear} υμων φερετε αυτον προς με[9:19]{.aside}

κα[ι]{.unclear} ηνε[γ]{.unclear}καν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γη[ς]{.unclear} εκυλιετο αφριζων[9:20]{.aside}

και επηρωτησεν τον [πατερα]{.greek-abbr} αυτου [ε[ξ]{.unclear}]{.greek-added} [ου]{.greek-added} [ποσος]{.greek-omitted} [χρονος]{.greek-omitted} [εστιν]{.greek-omitted} [ως]{.greek-omitted} τουτο γεγονεν αυτω ο δε ειπεν [παιδιοθεν]{.greek-omitted} [παιδοθεν]{.greek-added}[9:21]{.aside}

και πολλακις αυτον και εις το πυρ εβαλεν και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασα[ι]{.unclear} βοηθησον ημιν [σπ]{.unclear}λαγχνισθεις εφ ημας [[κυριε]{.greek-abbr}]{.greek-added}[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-omitted} [το]{.greek-omitted} [ει]{.greek-omitted} [δυνασαι]{.greek-omitted} [πιστευσαι]{.greek-omitted} [παντα]{.greek-omitted} [δυνατα]{.greek-omitted} [τω]{.greek-omitted} [πιστευοντι]{.greek-omitted}[9:23]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} αυτω [το]{.greek-omitted} ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23 | instance no. 2]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει [μου]{.greek-omitted} [μοι]{.greek-added} τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος επετιμησεν τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν [πολλα]{.greek-added} και [πολλα]{.greek-omitted} σπαραξαν αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον κατ ιδιαν [δια]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις [τ]{.unclear}ουτο το γενος εν ουδενι [δυναται]{.greek-omitted} [δυνατε]{.greek-added} εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε [ηγνωουν]{.greek-added} [ηγνοουν]{.corr} το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις [ειη]{.greek-added} μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι εσται παντων [εσχατος]{.greek-omitted} [και]{.greek-omitted} [παντων]{.greek-omitted} διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο [εν]{.greek-omitted} [μεσω]{.greek-omitted} [ανα]{.greek-added} [μεσον]{.greek-added} αυτων και εναγκαλισαμενος αυτο ειπεν αυτοι[ς]{.unclear}[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ο[ς]{.unclear} εαν εμε δεξηται ουκ εμε [δεχεται]{.greek-omitted} [δεχε]{.greek-added} αλλα τον αποστειλαντα με[9:37]{.aside}

[απ[ο]{.unclear}κριθη]{.greek-added} [απεκριθη]{.corr} δε αυτω ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} [τινα]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [σου]{.greek-omitted} [εκβαλλοντα]{.greek-omitted} [δαιμονια]{.greek-omitted} [ος]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

[απεκριθη]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} [ιωαννης]{.greek-omitted} [λεγων]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ειδομεν]{.greek-omitted} τινα τω ονοματι σου [δαιμονια]{.greek-added} εκβαλλοντα [δαιμονια]{.greek-omitted} ος ουκ ακολουθει ημιν και εκωλυσαμεν αυτον οτι ουκ ακολουθει ημιν[9:38 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και [δυνησεται]{.greek-omitted} [δυνησηται]{.greek-added} ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ εστιν καθ υμων υπερ υμων εστιν[9:40]{.aside}

[και]{.greek-added} ος [γαρ]{.greek-omitted} [αν]{.greek-omitted} [εαν]{.greek-added} [ποτιση]{.greek-omitted} [ποτηση]{.greek-added} υμας ποτηριον υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει περικειται [μυ]{.greek-added} [λιθος]{.corr} [μυλι[―]{.gap}κος]{.greek-added} [μυλικος]{.corr} περι τον τραχηλον αυτου και [βεβλητε]{.greek-added} [βεβληται]{.corr} εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι εστιν [κυλο]{.greek-added} [κυλλον]{.corr} [εις]{.greek-omitted} [εστιν]{.greek-added} [τιν]{.greek-added} [την]{.corr} ζωην εισελθειν η τας δυο χειρ[ας]{.unclear} εχοντα [απελθειν]{.greek-omitted} [βληθηναι]{.greek-added} εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ [αυτων]{.greek-added} ου [σβεννυται]{.greek-omitted} [σβενυντε]{.greek-added}[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον [αυτον]{.greek-omitted} [απο]{.greek-added} [σου]{.greek-added} καλον [σοι]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκοληξ]{.greek-added} αυτων ου τελευτα και το πυρ [αυτων]{.greek-added} ου [σβεννυται]{.greek-omitted} [σβεστννυται]{.greek-added}[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σο[ι]{.unclear} [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} του πυρος[9:47]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκοληξ]{.greek-added} αυτων ου τελευτα και το πυρ ου [σβεννυται]{.greek-omitted} [σβεννυτε]{.greek-added}[9:48]{.aside}

πας γαρ πυρι [αλισθ[ι]{.unclear}σεται]{.greek-added} [αλισθησεται]{.corr} και πασα θυσια [αλι]{.greek-omitted} αλισθησετα[ι]{.unclear}[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχετα[ι]{.unclear} εις τα ορια της ιουδαιας δια του περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [υμιν]{.greek-omitted} [ενετειλατο]{.greek-omitted} [μωσης]{.greek-omitted}[10:3]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3 | instance no. 2]{.aside}

οι δε [ειπον]{.greek-omitted} [ειπων]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} επετρεψεν βιβλιον αποστασιου γραψαι και απ[ολυ]{.unclear}σαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

[και]{.greek-added} [ειπεν]{.greek-added} ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσ[ον]{.unclear}τ[αι]{.unclear} οι δυο εις σαρκα μι[α]{.unclear}ν ωστε ουκετι εισιν δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} [συνεζευξεν]{.greek-omitted} [εζευξεν]{.greek-added} [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [του]{.greek-omitted} [τουτου]{.greek-added} αυτου επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα α[υτο]{.unclear}υ και [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} αλλην [μ]{.unclear}οιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον αν[δ]{.unclear}ρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον [αυτω]{.greek-omitted} παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσι[ν]{.unclear}[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} ηγανακτησεν και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με μη κωλ[υ]{.unclear}ετε [αυτα]{.greek-omitted} [ταυτα]{.greek-added} των [γ]{.unclear}αρ τοιουτων εστιν η βασιλεια το[υ]{.unclear} [θεου]{.greek-abbr}[10:14]{.aside}

[α]{.unclear}μην λεγω υμιν ος εαν [μ]{.unclear}η δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και [ε]{.unclear}ναγκαλισαμενος αυτα τιθ[εις]{.unclear} τας χειρας επ αυτα ευλογει αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} προσδραμων [εις]{.greek-omitted} και γονυπετησας [αυτον]{.greek-omitted} [αυτω]{.greek-added} επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην [αιωνιον]{.greek-omitted} κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευ[σ]{.unclear}ης μη φ[ον]{.unclear}ευσης μη κλεψης μη [ψευδομαρτυρησης]{.greek-omitted} [ψευδομαρτυρηση]{.greek-added} μη αποστερησης τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε [αποκριθεις]{.greek-omitted} [αποκριθης]{.greek-added} ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν σοι υστερει υπαγε [πολησον]{.greek-added} οσα εχεις [πωλησον]{.greek-omitted} και δος [πτωχοις]{.greek-omitted} [[πτω]{.unclear}χ[ω]{.unclear}ις]{.greek-added} [και]{.greek-omitted} [εξεις]{.greek-omitted} [θησαυρον]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [δευρο]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [αρας]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted}[10:21]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [εμβλεψας]{.greek-omitted} [αυτω]{.greek-omitted} [ηγαπησεν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [υστερει]{.greek-omitted} [υπαγε]{.greek-omitted} [οσα]{.greek-omitted} [εχεις]{.greek-omitted} [πωλησον]{.greek-omitted} [και]{.greek-omitted} [δος]{.greek-omitted} [πτωχοις]{.greek-omitted} και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21 | instance no. 2]{.aside}

[ο]{.greek-omitted} [ω]{.greek-added} δε στυγνασας επι [τω]{.greek-omitted} [το]{.greek-added} λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολω[ς]{.unclear} [οι]{.unclear} τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις [τεκνα]{.greek-omitted} [τεκνια]{.greek-added} πως δυσκολον εστιν τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον εστιν καμηλον δια της [τρυμαλιας]{.greek-omitted} [τριμαλυας]{.greek-added} [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσω[ς]{.unclear} εξεπλησσοντο λεγοντες προ[ς]{.unclear} εαυτους και τις δυναται σωθηνα[ι]{.unclear}[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρ[α]{.unclear} [τω]{.greek-added} [θεω]{.greek-abbr} παν[τ]{.unclear}α γαρ δυνατα εστιν παρα [τω]{.greek-omitted} [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν [πα]{.unclear}ντα και ηκολουθησαμεν σοι[10:28]{.aside}

[[και]{.unclear}]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπ[ε]{.unclear}ν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [[μητερα]{.greek-abbr}]{.greek-added} [η]{.greek-added} [πατερα]{.greek-abbr} [η]{.greek-omitted} [μητερα]{.greek-omitted} η γυναικα η τεκν[α]{.unclear} η αγρ[ου]{.unclear}ς ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [μητερας]{.greek-abbr} και τ[ε]{.unclear}κνα και αγρ[ου]{.unclear}ς μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλα[β]{.unclear}ων παλιν τους δωδεκα ηρξατο αυτοις λ[ε]{.unclear}γει[ν]{.unclear} τα μελλοντα αυτω συμ[β]{.unclear}αινειν[10:32]{.aside}

οτι [ι]{.unclear}δ[ου]{.unclear} αναβαινομεν ε[ις]{.unclear} [ιε]{.unclear}ροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευ]{.greek-added} [και]{.greek-omitted} [γραμματευσιν]{.greek-omitted} [και]{.greek-omitted} [κατακρινουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [θανατω]{.greek-omitted} [και]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted}[10:33]{.aside}

[σιν]{.greek-added} [οτι]{.greek-omitted} [ιδου]{.greek-omitted} [αναβαινομεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} και [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδοθησεται]{.greek-omitted} τοις [αρχιερευσιν]{.greek-omitted} [και]{.greek-omitted} [γραμματευσιν]{.greek-omitted} [γραματευσιν]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33 | instance no. 2]{.aside}

και εμπαιξουσιν [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} αυτον και [μαστιγοσουσιν]{.greek-added} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης οι υιοι ζεβεδαιου λεγοντες διδα[σ]{.unclear}καλε θελομεν ιν[α]{.unclear} ο [ε]{.unclear}αν [σε]{.greek-added} αιτησωμεν ποιησης ημιν[10:35]{.aside}

ο δε ειπεν α[υ]{.unclear}τοις τι [θ]{.unclear}ελε[τ]{.unclear}ε [με]{.greek-added} ποιησαι [με]{.greek-omitted} υμ[ι]{.unclear}ν[10:36]{.aside}

οι δε ειπ[ο]{.unclear}ν αυτω δος ημιν ινα εις [ε]{.unclear}κ δεξιων σου και εις [ε]{.unclear}ξ [ευωνυμων]{.greek-omitted} [ευ[ο]{.unclear}νυμ[ω]{.unclear}ν]{.greek-added} σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη [δο]{.unclear}ξη σου[10:37]{.aside}

ο δ[ε]{.unclear} [ιησους]{.greek-omitted} ειπεν αυ[τ]{.unclear}οις ουκ οιδατε τι α[ιτ]{.unclear}εισ[θε]{.unclear} δυνασθε [π]{.unclear}ιειν [το]{.unclear} [π]{.unclear}ο[τ]{.unclear}ηριον [ο]{.unclear} [ε]{.unclear}γω π[ιν]{.unclear}ω και [τ]{.unclear}ο βα[π]{.unclear}τισμα [ο]{.unclear} εγω βα[π]{.unclear}τιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το με[ν]{.unclear} ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησε[σ]{.unclear}[θ]{.unclear}αι]{.greek-added}[10:39]{.aside}

το δε καθισα[ι]{.unclear} εκ δεξιων μ[ου]{.unclear} και εξ ευωνυμων ουκ ε[σ]{.unclear}τιν εμον [δουναι]{.greek-omitted} αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ι[α]{.unclear}κωβ[ο]{.unclear}υ και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων [και]{.unclear} οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν [θ]{.unclear}ελη γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν [υμων]{.greek-added} θελη [υμων]{.greek-omitted} γενεσ[θ]{.unclear}αι πρωτο[ς]{.unclear} ε[στ]{.unclear}αι παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλ[θ]{.unclear}εν δι[α]{.unclear}κον[η]{.unclear}θη[ναι]{.unclear} αλλα διακον[η]{.unclear}σαι και δουναι την ψ[υχ]{.unclear}ην αυτο[υ]{.greek-supplied} λυ[τ]{.unclear}[ρον]{.greek-supplied} [αντι]{.greek-supplied} [πο]{.greek-supplied}[λ]{.unclear}λω[ν]{.greek-supplied}[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου [απ]{.unclear}ο ιεριχω και των μαθητων αυτου και [οχ]{.unclear}λου [ικανου]{.greek-omitted} [οικανου]{.greek-added} υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσα[ι]{.unclear}τ[ω]{.unclear}ν[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ν[α]{.unclear}ζω[ρα]{.unclear}ιος εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεη[σο]{.unclear}ν με[10:47]{.aside}

και επετιμω[ν]{.unclear} αυτ[ω]{.unclear} [π]{.unclear}ολλοι [ινα]{.greek-omitted} [σιωπηση]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [πολλω]{.greek-omitted} [μαλλον]{.greek-omitted} [εκραζεν]{.greek-omitted} [υιε]{.greek-omitted} [δαυιδ]{.greek-omitted} [ελεησον]{.greek-omitted} [με]{.greek-omitted}[10:48]{.aside}

[και]{.greek-omitted} [επετιμων]{.greek-omitted} [αυτω]{.greek-omitted} [πολλοι]{.greek-omitted} ινα σιωπηση ο δε πολλω μαλλον εκραζεν [[κυριε]{.greek-abbr}]{.greek-added} [υιε]{.greek-abbr} [δαυιδ]{.greek-abbr} ελεησον με[10:48 | instance no. 2]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας ηλθεν προς [ον]{.greek-added} [τον]{.corr} [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις [ινα]{.greek-added} [π]{.unclear}[ο]{.greek-supplied}[ι]{.unclear}ησω σοι ο δε τυφλος ειπεν αυτω ραββουνι ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου σεσωκεν σε και ευθεως ανεβλεψεν και ηκολουθει [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} ε[ν]{.unclear} τ[η]{.unclear} οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσι[ν]{.unclear} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} και βηθανιαν προς το ορος των ελαιων α[π]{.greek-supplied}[ο]{.unclear}[σ]{.greek-supplied}[τελ]{.unclear}[λ]{.greek-supplied}[ει]{.unclear} [δυο]{.unclear} [των]{.unclear} [μα]{.unclear}[θη]{.greek-supplied}[των]{.unclear} [αυτου]{.greek-supplied}[11:1]{.aside}

[και]{.greek-supplied} [λεγει]{.greek-supplied} [αυ]{.greek-supplied}τοις υπ[α]{.unclear}γετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.greek-omitted} [ευρησητε]{.greek-added} πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} κεκαθικεν λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι [ποιειτε]{.greek-omitted} [τουτο]{.greek-omitted} [λυετε]{.greek-added} [τον]{.greek-added} [πωλον]{.greek-added} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς [τ]{.unclear}ον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και εκαθισεν επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε σ[τ]{.unclear}οιβαδας εκοπτον εκ των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδ[ω]{.unclear}]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες [ω]{.unclear}σαννα [τω]{.greek-added} [υψιστ[ω]{.unclear}]{.greek-added} ευλογημενος ο ερχ[ο]{.unclear}[μ]{.unclear}ε[ν]{.unclear}ος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν [ο]{.unclear}νοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοι[ς]{.unclear} υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-omitted} [[υιος]{.greek-abbr}]{.greek-added} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη [επαυριον]{.greek-omitted} [επαυριων]{.greek-added} [εξελθοντων]{.greek-omitted} αυτων [απο]{.greek-omitted} [βηθανιας]{.greek-omitted} [επεινασεν]{.greek-omitted}[11:12]{.aside}

[και]{.greek-omitted} [τη]{.greek-omitted} [επαυριον]{.greek-omitted} εξελθοντων [αυτων]{.greek-omitted} απο βηθανιας επεινασεν[11:12 | instance no. 2]{.aside}

και ιδων συκην μακροθεν εχουσαν φυλλα ηλθεν ει αρα [τι]{.greek-added} ευρησει [τι]{.greek-omitted} εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα [μονον]{.greek-added} ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις [το]{.greek-omitted} [ιερον]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκβαλλειν]{.greek-omitted} [τους]{.greek-omitted} [πωλουντας]{.greek-omitted} [και]{.greek-omitted} [αγοραζοντας]{.greek-omitted} [εν]{.greek-omitted} τ[ω]{.unclear} ιερω και [τ]{.unclear}ας τραπεζας των κολλυβιστων και [τ]{.unclear}ας καθεδρας των [πωλουντων]{.greek-omitted} [πολουντων]{.greek-added} [τ]{.unclear}ας περιστερα[ς]{.unclear} [κ]{.unclear}ατεστρεψεν[11:15]{.aside}

και ουκ [ηφιεν]{.greek-omitted} [αφηκαν]{.greek-added} ι[ν]{.unclear}α τις [διενεγκη]{.greek-omitted} [ενεγκη]{.greek-added} σκε[υο]{.greek-supplied}ς δι[α]{.unclear} του ιερου[11:16]{.aside}

και εδ[ι]{.unclear}δασκεν λεγων αυτοις ου γεγραπται [οτι]{.greek-omitted} ο οικος μου οικος προσευχης [κληθησεται]{.greek-omitted} [κλησεται]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι γραμματεις και οι αρχιερεις και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτο[υ]{.unclear}[11:18]{.aside}

και οτε οψε [εγενετο]{.greek-omitted} [εγινετο]{.greek-added} [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και [αναμνησθεις]{.greek-omitted} [αναμνησθης]{.greek-added} ο πετρος λεγει αυτω [ραββι]{.greek-omitted} [ραββει]{.greek-added} [ιδε]{.greek-omitted} [ιδου]{.greek-added} η συκη ην κατηρασω [ε]{.unclear}ξηρανται[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λ[ε]{.unclear}γω υμιν οτι ος αν ειπη [τ]{.unclear}ω [ορ]{.unclear}ει τουτω αρθητι και βλ[η]{.unclear}θητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα πιστευση οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθαι]{.greek-added} πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκετε]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιε[τε]{.unclear} [ου]{.unclear}δε ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω [υμιν]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιω]{.greek-omitted}[11:29]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [επερωτησω]{.greek-omitted} [υμας]{.greek-omitted} [και]{.greek-omitted} [εγω]{.greek-omitted} [ενα]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [αποκριθητε]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [ερω]{.greek-omitted} υμιν εν ποια εξουσια ταυτα ποιω[11:29 | instance no. 2]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και ελ[ο]{.unclear}γιζοντο προς [εαυτους]{.greek-omitted} [αλληλους]{.greek-added} λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

[αλλ]{.greek-omitted} [αν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφ[ο]{.unclear}βουντο τον [λαον]{.greek-omitted} [οχλον]{.greek-added} απ[αν]{.unclear}τες γαρ ειχον τον ιωαννην οτι [οντως]{.greek-omitted} [οντ[ο]{.unclear}ς]{.greek-added} προφητης ην[11:32]{.aside}

και απ[ο]{.unclear}κριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελων[α]{.unclear} [ε]{.greek-supplied}[φ]{.unclear}υτε[υ]{.unclear}σεν ανθρωπος [και]{.greek-supplied} [περιε]{.greek-supplied}[θη]{.unclear}κεν φραγμον και ωρυ[ξ]{.unclear}[εν]{.greek-supplied} [υποληνι]{.greek-supplied}[ον]{.unclear} και ωκοδομη[σ]{.unclear}[εν]{.greek-supplied} [πυργον]{.greek-supplied} [και]{.greek-supplied} [ε]{.greek-supplied}ξεδοτο αυτον γεωργ[οις]{.greek-supplied} και απεδημησεν[12:1]{.aside}

και απεστειλεν προς τους γεωργους τω καιρω δουλον ινα παρα των [γεωργων]{.greek-omitted} [γεοργω[ν]{.unclear}]{.greek-added} λαβη απο του καρπο[υ]{.unclear} του αμπελωνος[12:2]{.aside}

οι δ[ε]{.unclear} λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και [απεστειλεν]{.greek-added} παλιν [απεστειλεν]{.greek-omitted} προς αυτους αλλον δουλον κακεινον λιθοβολησαντες [ε]{.unclear}κεφαλαι[ωσα]{.unclear}ν και απεστειλαν [η]{.unclear}τιμωμενον[12:4]{.aside}

και παλιν [απεστειλεν]{.greek-added} αλλον [απεστειλεν]{.greek-omitted} κακεινο[ν]{.unclear} απεκτειναν και πολλους αλλους τους μεν [δεροντες]{.greek-omitted} [δ[ι]{.unclear}ροντ[ε]{.unclear}ς]{.greek-added} τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα [υιον]{.greek-abbr} εχων αγαπητον αυτου απεστειλεν και αυτον προς αυτους εσχατον λεγων οτι εντρα[π]{.unclear}η[σ]{.unclear}ονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [θεασαμενοι]{.greek-added} [αυτον]{.greek-added} [ερχομενον]{.greek-added} ειπον προς εαυτους οτ[ι]{.unclear} ουτος εστιν ο κληρον[ο]{.unclear}μος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και [εξε]{.unclear}βαλον [αυτον]{.greek-added} ε[ξ]{.unclear}ω του αμπ[ε]{.unclear}λω[ν]{.unclear}ος[12:8]{.aside}

τι ουν ποι[η]{.unclear}σει ο κυριος του αμπε[λωνο]{.greek-supplied}[ς]{.unclear} ελευσεται και α[π]{.unclear}[ολεσει]{.greek-supplied} [τ]{.greek-supplied}ους γεωργους και δωσ[ει]{.unclear} [τ]{.unclear}ον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδωκιμασαν]{.greek-added} οι ο[ι]{.unclear}κοδομουντες ουτος εγενηθη εις κεφαλ[ην]{.unclear} γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενε[τ]{.unclear}ο αυτη και εστι[ν]{.unclear} θαυμαστη εν [ο]{.unclear}φθ[αλ]{.unclear}μοις ημων[12:11]{.aside}

κα[ι]{.unclear} εζητουν αυτον κρατη[σ]{.unclear}αι και [[ε]{.unclear}φοβησ[α]{.unclear}ν]{.greek-added} [[ε]{.unclear}φοβηθησ[α]{.unclear}ν]{.corr} τον [ο]{.unclear}χλον εγνωσαν γαρ ο[τι]{.unclear} [προς]{.unclear} αυτους την παρ[α]{.unclear}βολην [ταυτην]{.greek-added} ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [απ[ο]{.unclear}στελλουσι]{.greek-added} προς αυτον [τιν]{.unclear}ας των φαρισ[αι]{.unclear}ων και τ[ω]{.unclear}ν ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι [δε]{.unclear} ελθοντες [επηρωτων]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [δολω]{.greek-added} [και]{.greek-added} λεγουσιν αυτω διδ[α]{.unclear}[σ]{.unclear}καλε οιδαμεν οτι αληθης [ει]{.greek-omitted} [η]{.greek-added} και ου μελει [σοι]{.unclear} [πε]{.unclear}ρι ουδενος ου γαρ βλεπει[ς]{.unclear} εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [ειπε]{.greek-added} [ουν]{.greek-added} [ημιν]{.greek-added} [τι]{.greek-added} [σοι]{.greek-added} [[δο]{.unclear}[κ]{.unclear}ει]{.greek-added} εξεστιν [κηνσον]{.greek-omitted} [κινσον]{.greek-added} [δουναι]{.greek-added} καισαρι [δουναι]{.greek-omitted} η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυ[τω]{.unclear}ν την υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν [κ]{.unclear}αι λεγει αυτοις τ[ι]{.unclear}νος η [εικων]{.greek-omitted} [εικον]{.greek-added} αυτη και [η]{.greek-omitted} επιγραφη οι δε ειπον αυτω καισ[α]{.unclear}ρος[12:16]{.aside}

και αποκριθεις [ο]{.unclear} [ιησους]{.greek-abbr} ειπεν αυτοις [α]{.unclear}ποδοτε τα καισαρος [τ[ω]{.unclear}]{.greek-added} καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και [εθαυμασαν]{.greek-omitted} [εξ[ε]{.unclear}θαυμασαν]{.greek-added} επ αυτω[12:17]{.aside}

και ερχονται [σαδδουκαιοι]{.greek-omitted} προς αυτον [σαδδουκ[αι]{.greek-supplied}οι]{.greek-added} οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν ημιν οτι εαν τινος [ο]{.greek-added} αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι ησαν [παρ]{.greek-added} [ημιν]{.greek-added} και ο [πρωτος]{.greek-omitted} [προτος]{.greek-added} ελαβεν γυναικα και [αποθνησκων]{.greek-omitted} [αποθνη[σ]{.unclear}κον]{.greek-added} ουκ [α]{.unclear}φηκεν σπερμα[12:20]{.aside}

και ο [δ]{.unclear}ευτερος ελαβεν αυτην και απεθανεν και ουδε [ουδε]{.greek-added} [αυτος]{.greek-omitted} [[ο]{.unclear}υτος]{.greek-added} [αφηκεν]{.greek-omitted} [αφη[κε]{.unclear}]{.greek-added} σπερμα και ο τριτος ωσαυτω[ς]{.unclear}[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπε[ρμ]{.unclear}α εσχατη παντων απεθανεν και η γυνη[12:22]{.aside}

εν τη [ουν]{.greek-added} αναστ[α]{.unclear}[σ]{.greek-supplied}ει οταν αναστωσιν τινο[ς]{.unclear} [αυτων]{.greek-omitted} εσται γυνη οι γα[ρ]{.unclear} επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη ειδοτες [τ]{.unclear}ας γραφας μηδε τ[η]{.unclear}ν δ[υνα]{.unclear}μιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ [ε]{.unclear}κ νεκρων αναστωσιν ουτε γαμ[ο]{.unclear}υσιν ουτε γαμισκονται αλλ [ει]{.unclear}σιν [ως]{.greek-omitted} [ος]{.greek-added} αγγελοι [οι]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} εν το[ι]{.unclear}ς [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των [νε]{.greek-added} [νεκρων]{.greek-omitted} [οτι]{.greek-omitted} [εγειρονται]{.greek-omitted} [ουκ]{.greek-omitted} [ανεγνωτε]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [βιβλω]{.greek-omitted} [μωσεως]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [βατου]{.greek-omitted} [ως]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [λεγων]{.greek-omitted} [εγω]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [αβρααμ]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ισαακ]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ιακωβ]{.greek-omitted}[12:26]{.aside}

[περι]{.greek-omitted} [δε]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [κρων]{.greek-added} οτι εγειρονται ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} επι του βατου [ως]{.greek-omitted} [ος]{.greek-added} ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} [αβραμ]{.greek-added} [αβρααμ]{.corr} και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26 | instance no. 2]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} [[θεος]{.greek-abbr}]{.greek-added} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων εις των γραμματεων ακουσας αυτων συζητουντων ειδως οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια εστιν [η]{.greek-added} πρωτη παντων εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω οτι [πρωτη]{.greek-omitted} [πρωτι]{.greek-added} παν[τω]{.unclear}ν [των]{.greek-omitted} εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου [εξ]{.corr} [ολης]{.corr} [της]{.corr} [καρδιας]{.corr} [σου]{.corr} [και]{.greek-omitted} εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως σεαυτον μειζων τουτων [παντων]{.greek-added} αλλη εντολη ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} εστιν και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και [τ[α]{.unclear}]{.greek-added} [το]{.corr} αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον [πλειον]{.greek-omitted} [πλειονα]{.greek-added} [εστιν]{.greek-omitted} παντων των ολοκαυτωματων [εστιν]{.greek-added} και [των]{.greek-added} θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} εστιν [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γα[ρ]{.unclear} [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου [υποποδιον]{.greek-omitted} [υποκατω]{.greek-added} των ποδω[ν]{.unclear} σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου εστιν και ο πολυς οχλος ηκο[υε]{.unclear}ν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των γραμματεων των [θ]{.unclear}ελοντων εν στολαις περιπατ[ε]{.unclear}ιν [και]{.corr} [[φιλο[υν]{.unclear}[των]{.greek-supplied}]{.corr}]{.greek-added} [και]{.greek-added} ασπασμους εν ταις αγοραις [[αγωραις]{.corr}]{.greek-added}[12:38]{.aside}

[και]{.corr} [πρωτοκαθεδριας]{.greek-omitted} [[προτοκαθεδριας]{.corr}]{.greek-added} [εν]{.corr} [[τα]{.unclear}ις]{.corr} [[σ]{.unclear}υναγωγαις]{.corr} και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιαις]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [εστως]{.greek-added} ο [ιησους]{.greek-abbr} [κατεναντι]{.greek-omitted} [κατεναν]{.greek-added} [του]{.greek-omitted} [γαζοφυλακιου]{.greek-omitted} [εθεωρει]{.greek-omitted} [πως]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [βαλλει]{.greek-omitted} [χαλκον]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [γαζοφυλακιον]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [πλουσιοι]{.greek-omitted} [εβαλλον]{.greek-omitted} [πολλα]{.greek-omitted}[12:41]{.aside}

[τι]{.greek-added} [και]{.greek-omitted} [καθισας]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [κατεναντι]{.greek-omitted} του [γαζοφυλακιου]{.greek-omitted} [γαζοφυλακειου]{.greek-added} εθεωρει πως ο οχλος βαλλει χαλκον εις το [γαζοφυλακιον]{.greek-omitted} [γαζοφυλακειον]{.greek-added} και πολλοι πλουσιοι εβαλλον πολλα[12:41 | instance no. 2]{.aside}

και ελθουσα μια χηρα πτωχη εβαλεν λεπτα δυο ο εστιν κοδραντης[12:42]{.aside}

και προσκαλεσαμενος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων βεβληκεν των βαλλοντων εις το [γαζοφυλακιον]{.greek-omitted} [γαζοφυλακειον]{.greek-added}[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθ[ο]{.unclear}ι και [ποταπαι]{.greek-omitted} οικοδομαι[13:1]{.aside}

και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτ[ω]{.unclear} βλεπεις ταυτας τας μεγαλας οικοδομας [αμην]{.greek-added} [λεγω]{.greek-added} [σοι]{.greek-added} ου μη αφεθη λιθος επι λιθω ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του [ι]{.unclear}ερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} και πολλους πλανησουσιν[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουετε]{.greek-added} πολεμους και ακοας πολεμων μη [θροεισθε]{.greek-omitted} [θορυβεισσθε]{.greek-added} δει γαρ γενεσθαι αλλ ουπω [το]{.greek-omitted} [τω]{.greek-added} τελος[13:7]{.aside}

εγερθησεται γαρ εθνος [επι]{.greek-omitted} [επ]{.greek-added} εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται [ταραχαι]{.greek-added} [και]{.greek-added} λιμοι [και]{.greek-omitted} [ταραχαι]{.greek-omitted} αρχαι ωδινων ταυτα [παντα]{.greek-added}[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγε[μ]{.unclear}ονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει [κηρυχθηναι]{.greek-added} πρωτον [κηρυχθηναι]{.greek-omitted} το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [προμεμεριμνατε]{.greek-added} τι λαλησητε μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ [υμεις]{.greek-added} εστε [υμεις]{.greek-omitted} οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και [θανατωσουσιν]{.greek-omitted} [θανατοσουσιν]{.greek-added} αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε [υπομεινας]{.greek-omitted} [εις]{.greek-omitted} [τελος]{.greek-omitted} [ουτος]{.greek-omitted} [σωθησεται]{.greek-omitted}[13:13]{.aside}

[και]{.greek-omitted} [εσεσθε]{.greek-omitted} [μισουμενοι]{.greek-omitted} [υπο]{.greek-omitted} [παντων]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} υπομεινας εις τελος ουτος σωθησεται[13:13 | instance no. 2]{.aside}

οταν δε [ιδητε]{.greek-omitted} [ιδη]{.greek-added} το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου [εστως]{.greek-omitted} [εστος]{.greek-added} οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο [δε]{.greek-omitted} επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις [εν]{.greek-omitted} [γαστρι]{.greek-omitted} [εγγαστρι]{.greek-added} εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου γεγονεν τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβοσεν]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκ[λ]{.unclear}εκτους ους εξελεξατο εκολοβωσεν τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και δωσουσιν σημεια και τερατα προς το αποπλαναν [ει]{.greek-omitted} [δυνατον]{.greek-omitted} και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η [σεληνη]{.greek-omitted} [σελινη]{.greek-added} ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} [εσονται]{.greek-omitted} [πεσουνται]{.greek-added} [εκπιπτοντες]{.greek-omitted} [και]{.corr} [[αι]{.greek-supplied}]{.corr} [δυναμει[ς]{.unclear}]{.corr} [[τω[ν]{.unclear}]{.corr}]{.greek-added} [[[ουρανων]{.greek-abbr}]{.corr}]{.greek-added} [αι]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[σαλευθησον]{.greek-supplied}τα[ι]{.unclear}]{.corr}[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επι[σ]{.unclear}υναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης [ηδη]{.greek-omitted} ο κλαδος [ηδη]{.greek-added} απαλος γενηται και εκφυη τα φυλλα γινωσκετε οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν ταυτα ιδητε γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} [ου]{.greek-omitted} [παντα]{.greek-omitted} ταυτα γενηται [παντα]{.greek-added}[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε [λο]{.greek-added} [λογοι]{.greek-omitted} [μου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [παρελθωσιν]{.greek-omitted}[13:31]{.aside}

[ο]{.greek-omitted} [ουρανος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [παρελευσεται]{.greek-omitted} [οι]{.greek-omitted} [γοι]{.greek-added} [δε]{.greek-omitted} [λογοι]{.greek-omitted} μου ου μη παρελθωσιν[13:31 | instance no. 2]{.aside}

περι δε της ημερας [και]{.greek-added} [ωρας]{.greek-added} εκεινης [η]{.greek-omitted} [ωρας]{.greek-omitted} ουδεις οιδεν ουδε οι αγγελοι [τ[ω]{.unclear}ν]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

[γρ]{.unclear}ηγορειτε ουν ουκ οιδατε γαρ ποτε [ο]{.unclear} κυριος [της]{.greek-omitted} [τες]{.greek-added} οικιας ερχεται οψε η [μ]{.unclear}εσονυκτιου η αλε[κ]{.unclear}τοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης [ευρη]{.greek-omitted} [ευρησει]{.greek-added} υμας καθ[ευ]{.unclear}δοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πα[σι]{.unclear}]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το [π]{.unclear}α[σ]{.unclear}χα και τα αζυμα με[τ]{.unclear}α δυο ημερα[ς]{.unclear} και ε[ζη]{.unclear}τουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω κρατησαντες απ[οκ]{.unclear}τεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυ[β]{.unclear}ος εστα[ι]{.unclear} [του]{.unclear} λαου[14:2]{.aside}

και οντ[ο]{.unclear}ς αυ[του]{.unclear} εν βηθανια εν [τ]{.unclear}η οικ[ι]{.unclear}α [σιμωνος]{.greek-omitted} [σ[ι]{.unclear}μονος]{.greek-added} το[υ]{.unclear} λεπρο[υ]{.unclear} κατακειμενου αυτου ηλθεν γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η [απωλεια]{.greek-omitted} [απολεια]{.greek-added} αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ [το]{.greek-added} [μυρον]{.greek-added} τουτο πραθηναι επανω τριακοσιων δηναριων και [δοθηναι]{.greek-omitted} [δωθηναι]{.greek-added} [τοις]{.greek-omitted} πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον [ειργασατο]{.greek-omitted} [ηργασατο]{.greek-added} εν εμοι[14:6]{.aside}

παντοτε γαρ [[ε]{.unclear}χετε]{.greek-added} τους πτωχους [εχετε]{.greek-omitted} μεθ εαυτων και οταν [θελητε]{.greek-omitted} [θελετε]{.greek-added} δυνασθε [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ευ ποιησα[ι]{.unclear} εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη εποιησεν προελα[β]{.unclear}εν μυρισαι μου το σωμα [εις]{.greek-omitted} [προς]{.greek-added} τον [ενταψιασμον]{.greek-added} [εντα[φ]{.unclear}ιασμον]{.corr}[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τ[ο]{.unclear}ν κοσμον και ο εποιησεν αυτη [λα]{.unclear}ληθη[σ]{.unclear}ετ[α]{.unclear}ι εις μνημοσυνον αυτης[14:9]{.aside}

και ο ι[ο]{.unclear}υδας ο ισκαριωτης [ο]{.greek-added} εις των δωδεκα α[πη]{.unclear}λθεν προς τ[ο]{.unclear}υς αρχι[ερ]{.unclear}ει[ς]{.unclear} ινα παραδω αυτον αυτ[οι]{.unclear}ς[14:10]{.aside}

ο[ι]{.unclear} δε ακουσαντες εχα[ρ]{.unclear}ησαν και επηγ[γ]{.unclear}ειλαντο [αυ]{.unclear}τω αργυριον δουναι και εζητει [αυτον]{.greek-added} πως [ευκαιρως]{.greek-omitted} [ευκαι]{.greek-added} [αυτον]{.greek-omitted} [παραδω]{.greek-omitted}[14:11]{.aside}

[ρως]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [ακουσαντες]{.greek-omitted} [εχαρησαν]{.greek-omitted} [και]{.greek-omitted} [επηγγειλαντο]{.greek-omitted} [αυτω]{.greek-omitted} [αργυριον]{.greek-omitted} [δουναι]{.greek-omitted} [και]{.greek-omitted} [εζητει]{.greek-omitted} [πως]{.greek-omitted} [ευκαιρως]{.greek-omitted} [αυτον]{.greek-omitted} παραδω[14:11 | instance no. 2]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν [σοι]{.greek-added} [ινα]{.greek-omitted} [φαγης]{.greek-omitted} το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και [εισελθοντων]{.greek-added} [υμων]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [πολιν]{.greek-added} απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη [οτι]{.greek-omitted} ο διδασκαλος λεγει που εστιν το καταλυμα οπου το πασχα μετα των μαθητων μ[ου]{.unclear} [φ]{.unclear}[αγω]{.greek-supplied}[14:14]{.aside}

[κ]{.unclear}αι α[υ]{.unclear}[τος]{.greek-supplied} [υμιν]{.greek-supplied} [δειξει]{.greek-supplied} [ανωγεον]{.greek-omitted} [[ανα]{.greek-supplied}γαι[ον]{.greek-supplied}]{.greek-added} [με]{.greek-supplied}[γα]{.unclear} [εστρ]{.unclear}ωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον [ετοιμασαι]{.greek-added} [αυτω]{.greek-added} οι [μ]{.unclear}αθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και [εσ]{.unclear}θιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω [κ[αι]{.unclear}]{.corr} [[α]{.unclear}λλο[ς]{.unclear}]{.corr} [μ[η]{.unclear}τι]{.corr} [εγω]{.corr}[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο [εμβαπτομενος]{.greek-omitted} [εμβαπτωμενος]{.greek-added} μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον [και]{.greek-added} ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον ευχαριστησας [εδωκεν]{.greek-omitted} [εδωκενκεν]{.greek-added} αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο εστιν το αιμα μου [το]{.greek-omitted} της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εω[ς]{.unclear} της ημ[ε]{.unclear}ρας ε[κ]{.unclear}εινης οταν αυτο [καινον]{.greek-added} πινω [καινον]{.greek-omitted} εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντε[ς]{.unclear} εξηλθον εις το [ο]{.unclear}ρος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες [σκανδαλισθησονται]{.greek-omitted} [αλλ]{.greek-omitted} [ουκ]{.greek-omitted} [εγω]{.greek-omitted}[14:29]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} [εφη]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [παντες]{.greek-omitted} σκανδαλισθησονται αλλ ουκ εγω[14:29 | instance no. 2]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν [ι]{.greek-added} [η]{.greek-omitted} [δις]{.greek-omitted} αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε εκπερισσου ελεγεν μαλλον εα[ν]{.unclear} [[δ]{.unclear}εη]{.greek-added} με [συν]{.greek-added} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} σοι [αποθανειν]{.greek-added} ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησωμε]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεδσημανη]{.greek-added} και λεγει τοις μαθηταις αυτου καθισατε ωδε εως προσευξωμαι[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι [παρενεγκε]{.greek-omitted} [παρενεγκαι]{.greek-added} το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

[γρηγορειται]{.greek-added} [γρηγορειτε]{.corr} και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενη[ς]{.unclear}[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καταβαρημενοι]{.greek-added} και ουκ ηδεισαν τι αυτω αποκριθωσιν[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει [το]{.greek-added} [τελος]{.greek-added} ηλθεν η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των [αμαρτωλων]{.greek-omitted} [αμαρτολων]{.greek-added}[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις ων των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} [γρα[μματεων]{.greek-supplied}]{.corr} [και]{.greek-omitted} [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον [συσσημον]{.greek-omitted} [συσσομον]{.greek-added} αυτοις λεγων ον αν φιλησω αυτος εστιν κρατησατε α[υ]{.unclear}τον και απαγαγετε ασφαλως[14:44]{.aside}

και [ελθων]{.greek-omitted} ευθεως προσελθων αυτω λεγει [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} [ραββει]{.greek-added} [ραββι]{.greek-omitted} και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας [αυτων]{.greek-omitted} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος [την]{.greek-omitted} μαχαιραν επαισεν τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-omitted} [ως]{.greek-omitted} [επι]{.greek-omitted} [ληστην]{.greek-omitted} [εξηλθετε]{.greek-omitted} [μετα]{.greek-omitted} [μαχαιρων]{.greek-omitted} [και]{.greek-omitted} [ξυλων]{.greek-omitted} [συλλαβειν]{.greek-omitted} [με]{.greek-omitted}[14:48]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} αυτοις ως επι [ληστην]{.greek-omitted} [λιστην]{.greek-added} [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48 | instance no. 2]{.aside}

καθ ημεραν ημην προς υμας [διδασκων]{.greek-added} εν τω ιερω [διδασκων]{.greek-omitted} και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον [οι]{.greek-added} [μαθηται]{.greek-added} παντες εφυγον[14:50]{.aside}

και εις τις νεα[ν]{.unclear}ισκος ηκολουθησεν αυτω περιβεβλημενος [σινδονα]{.greek-omitted} [σινδωνα]{.greek-added} επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω [παν]{.greek-added} [παντ[ες]{.unclear}]{.corr} οι αρχιερεις και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added} και οι [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added}[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις [ηκουσαμεν]{.greek-omitted} [ακουσαμεν]{.greek-added} [αυτου]{.greek-omitted} λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον [οικοδομησω]{.greek-omitted} [οικοδωμησω]{.greek-added}[14:58]{.aside}

και ουδε ουτως ιση [ην]{.greek-omitted} η μαρτυρια αυτων[14:59]{.aside}

και [αστας]{.greek-added} [αναστας]{.corr} ο αρχιερευς εις μεσον επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς [επηρωτα]{.greek-omitted} [επιρωτα]{.greek-added} αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο υιος του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-omitted} [αποκριθεις]{.greek-added} ειπεν [αυτω]{.greek-added} [συ]{.greek-added} [ειπας]{.greek-added} [οτι]{.greek-added} εγω ειμι και οψεσθε [τ]{.unclear}ον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιω[ν]{.unclear} καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας [αυτου]{.greek-added} τους [χιτωνας]{.greek-omitted} [χειτωνας]{.greek-added} [αυτου]{.greek-omitted} λεγει τι ετι χρειαν [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} μαρτυρων[14:63]{.aside}

ηκουσατε [της]{.greek-omitted} [παντες]{.greek-added} [την]{.greek-added} [βλασφημιας]{.greek-omitted} [βλασφημιαν]{.greek-added} [του]{.greek-added} [στοματος]{.greek-added} [αυτου]{.greek-added} τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [νυν]{.greek-added} [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται [ραπισμασιν]{.greek-omitted} [αυτον]{.greek-omitted} [εβαλλον]{.greek-omitted}[14:65]{.aside}

[και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [τινες]{.greek-omitted} [εμπτυειν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [περικαλυπτειν]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [κολαφιζειν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} [προφητευσον]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [υπηρεται]{.greek-omitted} ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added}[14:65 | instance no. 2]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα [[ιησου]{.greek-abbr}]{.greek-added} του [ναζαρηνου]{.greek-omitted} [ναζαρινου]{.greek-added} [ιησου]{.greek-omitted} ησθα[14:67]{.aside}

ο δε [ηρνησατο]{.greek-omitted} [ηρνισατο]{.greek-added} λεγων ουκ οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} [επισταμαι]{.greek-omitted} [επισταμε]{.greek-added} τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ εφωνησεν[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παστηκοσιν]{.greek-added} [παρεστηκοσιν]{.corr} οτι [και]{.greek-added} ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνησατο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδ[α]{.unclear} τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ εφωνησεν και ανεμνησθη ο πετρος [το]{.greek-omitted} [του]{.greek-added} [ρημα]{.greek-omitted} [ο]{.greek-omitted} [ρηματος]{.greek-added} [ως]{.greek-added} ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι [αρχιερες]{.greek-added} [αρχιερεις]{.corr} μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος παλιν [επηρωτησεν]{.greek-omitted} [ηρωτα]{.greek-added} αυτον [πολλα]{.greek-added} λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} [ουκετι]{.greek-omitted} ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμι[ο]{.unclear}ν ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος βαραββ[α]{.unclear}ς μετα των [σ]{.unclear}υστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αν[α]{.unclear}βοησας ο οχλος [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} [αιτεισθαι]{.greek-omitted} [αιτεισθε]{.greek-added} καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} αυτοις λεγων θελετε απολυσω υμιν [τον]{.unclear} [βα]{.unclear}σιλεα των ιουδαιων[15:9]{.aside}

εγινωσκε[ν]{.greek-supplied} γαρ οτι δια [φθονον]{.greek-omitted} [φθ[ο]{.unclear}φθονον]{.greek-added} παρ[α]{.unclear}δ[ε]{.unclear}δωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσει[σαν]{.unclear} τον οχλον ινα μαλλον τον βαραββαν [απολυση]{.greek-omitted} [απολυσω]{.greek-added} αυτοις[15:11]{.aside}

ο δε πιλατο[ς]{.unclear} [[α]{.unclear}]{.greek-added} [αποκριθεις]{.greek-omitted} [παλιν]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [ουν]{.greek-omitted} [θελετε]{.greek-omitted} [ποιησω]{.greek-omitted} [ον]{.greek-omitted} [λεγετε]{.greek-omitted} [βασιλεα]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted}[15:12]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ποκριθεις]{.greek-added} παλιν ειπεν αυτοις [το]{.greek-added} [τι]{.corr} ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12 | instance no. 2]{.aside}

οι δε παλιν [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} σταυρωσον αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσοτερος]{.greek-added} [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν α[υ]{.unclear}τοις τον βαραββαν και παρεδωκεν τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον [εσω]{.greek-omitted} [εως]{.greek-added} της αυλης ο εστιν [πρε]{.greek-added} [πραιτωριον]{.corr} και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυ[ου]{.greek-supplied}σιν αυτον [χλαμυδα]{.greek-added} [κοκκινην]{.greek-added} [και]{.greek-added} πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτ[ω]{.unclear} κα[ι]{.unclear} τιθεντες τα γονατα [π]{.unclear}ρ[ο]{.greek-supplied}σ[ε]{.unclear}κυνουν αυτω[15:19]{.aside}

και [οτε]{.greek-omitted} [οται]{.greek-added} ενεπαιξαν αυτω [εξ]{.unclear}[εδυσ]{.greek-supplied}[α]{.unclear}ν [αυτον]{.greek-omitted} [ατον]{.greek-added} [την]{.greek-added} [χλα[μ]{.greek-supplied}υδα]{.greek-added} [και]{.greek-added} την πορ[φ]{.greek-supplied}υραν και ενε[δυ]{.greek-supplied}[σ]{.unclear}αν αυτον τα [ιματια]{.greek-supplied} [τα]{.greek-supplied} ιδια και εξαγου[σιν]{.unclear} [αυτο]{.unclear}ν ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και αγγαρευουσιν πα[ρ]{.unclear}αγοντα τινα σιμωνα [κυρηναιον]{.greek-omitted} [κυριναιον]{.greek-added} ερχομενον απ αγρου τον [πατερα]{.greek-abbr} [α]{.unclear}λεξα[ν]{.unclear}δρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα [[γολγοθαν]{.corr}]{.greek-added} τοπον ο εστ[ι]{.greek-supplied}ν μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδ[ι]{.unclear}δουν αυτω πιειν [οινον]{.greek-added} [εσ]{.unclear}μυρνισμενον [οινον]{.greek-omitted} [ο]{.unclear} δε ουκ [ε]{.unclear}λαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου [βαλλοντες]{.greek-omitted} [βαλοντες]{.greek-added} κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-abbr} δυ[ο]{.unclear} ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο [καταλυον]{.greek-added} [καταλυων]{.corr} τον ναον και εν [τρισιν]{.greek-omitted} [τρισσιν]{.greek-added} ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [καταβηθι]{.greek-added} απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν αυτω και οι [συνεσταυρωμενοι]{.greek-abbr} αυτω [ονει]{.greek-added} [ωνειδιζον]{.greek-omitted} [αυτον]{.greek-omitted}[15:32]{.aside}

[διζον]{.greek-added} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [του]{.greek-omitted} [ισραηλ]{.greek-omitted} [καταβατω]{.greek-omitted} [νυν]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [σταυρου]{.greek-omitted} [ινα]{.greek-omitted} [ιδωμεν]{.greek-omitted} [και]{.greek-omitted} [πιστευσωμεν]{.greek-omitted} αυτω [και]{.greek-omitted} [οι]{.greek-omitted} [συνεσταυρωμενοι]{.greek-omitted} [αυτω]{.greek-omitted} [ωνειδιζον]{.greek-omitted} [αυτον]{.greek-omitted}[15:32 | instance no. 2]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και τη ωρα τη ενατη εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λαιμα]{.greek-added} σαβαχθανι ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου εις τι με [εγκατελιπες]{.greek-omitted} [εγκατελειπες]{.greek-added}[15:34]{.aside}

και [τινες]{.greek-omitted} [τιναις]{.greek-added} των παρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο [απο]{.greek-omitted} [απ]{.greek-added} ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι [ουτως]{.greek-omitted} [ουτος]{.greek-added} κραξας εξ[ε]{.unclear}πνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος υιος ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην και μαρια η [μαγδαληνη]{.greek-omitted} [μαγδα[λι]{.unclear}νη]{.greek-added} [[και]{.unclear}]{.greek-added} [μ[α]{.unclear}[―]{.gap}]{.greek-added} και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σ[α]{.unclear}λωμη[15:40]{.aside}

αι και οτε ην ε[ν]{.unclear} τ[η]{.unclear} γαλιλαια ηκολουθουν α[υ]{.unclear}τω και [διηκονουν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο εστιν [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} [ο]{.greek-added} ιωσηφ ο απο [αριμαθαιας]{.greek-omitted} [αριμαθιας]{.greek-added} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} [τολμησας]{.greek-omitted} [τολμη]{.greek-added} εισηλθεν [[εισηλθε]{.corr}]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και [αγορασας]{.greek-omitted} [αγωρασας]{.greek-added} [σινδονα]{.greek-omitted} [σ[ι]{.unclear}νδωνα]{.greek-added} και καθελω[ν]{.unclear} αυτον [ενειλησεν]{.greek-omitted} [ενε[ι]{.unclear}λισεν]{.greek-added} τη σινδονι και [κατεθηκεν]{.greek-omitted} [καθηκεν]{.greek-added} αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλησε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιωση εθεωρουν που [τιθεται]{.greek-omitted} [τεθηται]{.greek-added}[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατο[υ]{.unclear} μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρι[α]{.unclear} [ιακωβου]{.greek-omitted} [η]{.greek-added} [του]{.greek-added} [ηακω]{.greek-added} και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν [αυτον]{.greek-omitted} [αυτων]{.greek-added}[16:1]{.aside}

και λιαν πρωι της μιας [των]{.greek-added} σαββατων ερχονται επι το μνημειο[ν]{.unclear} ανατειλαντος του ηλιου[16:2]{.aside}

και [ε]{.unclear}λεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

[ην]{.greek-added} [γαρ]{.greek-added} [μεγας]{.greek-added} [σφοδρα]{.greek-added} και αναβλεψασαι θεωρουσιν ο[τι]{.unclear} αποκεκυλισται ο λ[ιθ]{.unclear}[ος]{.greek-supplied} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [μεγας]{.greek-omitted} [σφοδρα]{.greek-omitted}[16:4]{.aside}

και εισελθουσαι εις το μνημειον [ειδον]{.greek-omitted} [ιδων]{.greek-added} νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [ναζαρινον]{.greek-added} τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε [εκει]{.greek-added} ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε [και]{.greek-added} ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου ειχεν [[ειχε]{.corr}]{.greek-added} δε αυτας τρομος και [εξ[σ]{.unclear}στασις]{.greek-added} [εκστασις]{.greek-omitted} [[εξστασις]{.corr}]{.greek-added} και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη [πρωτον]{.greek-omitted} [πρωτη]{.greek-added} μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης [εκβεβληκει]{.greek-omitted} [εκβεβληκη]{.greek-added} επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα απηγγειλεν τοις μετ αυτου γενομενοις πενθουσιν και κλαιουσιν[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

[υ]{.unclear}στερον [δε]{.greek-added} ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την [απιστιαν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} σκληροκαρδιαν οτι τοις θεασαμενοις αυτον [εγηγερμενον]{.greek-omitted} [εκ]{.greek-added} [νεκρων]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη [κτισει]{.greek-omitted} [κτιση]{.greek-added}[16:15]{.aside}

[οτι]{.greek-added} ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα [παρακολουθησει]{.greek-omitted} [πακολουθησει]{.greek-added} εν τω ονοματι μου δαιμονια εκβαλουσιν [γλωσσαις]{.greek-omitted} [γλωσσες]{.greek-added} λαλησουσιν καιναις[16:17]{.aside}

[και]{.greek-added} [εν]{.greek-added} [τες]{.greek-added} [χερσιν]{.greek-added} οφεις αρουσιν καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας επιθησουσιν και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των [επακολουθουντων]{.greek-omitted} [επακουλουθουντων]{.greek-added} σημειων αμην[16:20]{.aside}

