---
title: "Collation of Byz^RP^ vs 30250 (250)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 250 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30250).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 250                                   	| λογος                              	|
| 250 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 250 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 250               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 250                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 250 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 250                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποσ[τε]{.unclear}ιλας [δ]{.unclear}ια του αγγελου αυτου [τω]{.greek-omitted} [τωι]{.greek-added} [δουλω]{.greek-omitted} [δουλωι]{.greek-added} αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα ειδεν[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν [τη]{.greek-omitted} [[τηι]{.unclear}]{.greek-added} ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος [και]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [πνευματων]{.greek-omitted} [α]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [αυτου]{.greek-omitted}[1:4]{.aside}

[ιωαννης]{.greek-omitted} [ταις]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [ταις]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ασια]{.greek-omitted} [χαρις]{.greek-omitted} [υμιν]{.greek-omitted} [και]{.greek-omitted} [ειρηνη]{.greek-omitted} [απο]{.greek-omitted} [θεου]{.greek-omitted} [ο]{.greek-omitted} [ων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ερχομενος]{.greek-omitted} και απο των επτα [πνευματων]{.greek-abbr} α ενωπιον του θρονου αυτου[1:4 | instance no. 2]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [ο]{.greek-omitted} [ος]{.greek-added} μαρτυς [ο]{.greek-omitted} πιστος [εστιν]{.greek-added} ο πρωτοτοκος των νεκρων και ο αρχων των βασιλεων της γης [τω]{.greek-omitted} [αγαπωντι]{.greek-omitted} [ος]{.greek-added} [ηγαπησεν]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [ελουσεν]{.greek-added} ημας απο των αμαρτιων ημων εν [τω]{.greek-omitted} [τωι]{.greek-added} αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα [των]{.greek-omitted} νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συγκοινωνος]{.greek-added} εν [τη]{.greek-omitted} [τηι]{.greek-added} θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν [τη]{.greek-omitted} [τηι]{.greek-added} [νησω]{.greek-omitted} [νησωι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} καλουμενη [πατμω]{.greek-omitted} [πατμωι]{.greek-added} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted}[1:9]{.aside}

[εγω]{.greek-omitted} [ιωαννης]{.greek-omitted} [ο]{.greek-omitted} [αδελφος]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [κοινωνος]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θλιψει]{.greek-omitted} [και]{.greek-omitted} [βασιλεια]{.greek-omitted} [και]{.greek-omitted} [υπομονη]{.greek-omitted} [εν]{.greek-omitted} [χριστω]{.greek-omitted} [ιησου]{.greek-omitted} [εγενομην]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νησω]{.greek-omitted} [τη]{.greek-omitted} [καλουμενη]{.greek-omitted} [πατμω]{.greek-omitted} δια τον λογον του [θεου]{.greek-abbr} και [δια]{.greek-omitted} την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9 | instance no. 2]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν [τη]{.greek-omitted} [τηι]{.greek-added} [κυριακη]{.greek-omitted} [κυριακηι]{.greek-added} ημερα και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} οπισω μου [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} ως σαλπιγγος[1:10]{.aside}

λεγουσης [ο]{.greek-omitted} [αι]{.greek-added} βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις σμυρναν και εις περγαμον και εις θυατειρα και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

και [εκει]{.greek-omitted} επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των επτα λυχνιων [των]{.greek-added} [χρυσων]{.greek-added} ομοιον [υιω]{.greek-omitted} [υιον]{.greek-added} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον [προς]{.greek-omitted} [εν]{.greek-added} τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι [και]{.greek-added} ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [φωνη]{.greek-omitted} [υδατων]{.greek-omitted} [πολλων]{.greek-omitted}[1:15]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [ποδες]{.greek-omitted} [αυτου]{.greek-omitted} [ομοιοι]{.greek-omitted} [χαλκολιβανω]{.greek-omitted} [ως]{.greek-omitted} [εν]{.greek-omitted} [καμινω]{.greek-omitted} [πεπυρωμενοι]{.greek-omitted} και η φωνη αυτου ως φωνη υδατων πολλων[1:15 | instance no. 2]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν [τη]{.greek-omitted} [τηι]{.greek-added} [δεξια]{.greek-omitted} [δεξιαι]{.greek-added} [χειρι]{.greek-added} αυτου [χειρι]{.greek-omitted} αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν [τη]{.greek-omitted} [τηι]{.greek-added} δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον επεσα προς τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} την δεξιαν αυτου επ εμε λεγων μη φοβου εγ[ω]{.unclear} ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας κλεις του θανατου και του [αδου]{.greek-omitted} [αιδου]{.greek-added}[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν και αι [επτα]{.greek-added} λυχνιαι αι επτα [επτα]{.greek-omitted} εκκλησιαι εισιν[1:20]{.aside}

### Chapter 2

[τω]{.greek-omitted} [τωι]{.greek-added} [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} [της]{.greek-omitted} [εν]{.greek-omitted} [εφεσω]{.greek-omitted} [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [κρατων]{.greek-omitted} [τους]{.greek-omitted} [επτα]{.greek-omitted} [αστερας]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δεξια]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [περιπατων]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιων]{.greek-omitted} [των]{.greek-omitted} [χρυσων]{.greek-omitted}[2:1]{.aside}

[τω]{.greek-omitted} [αγγελω]{.greek-omitted} της εν εφεσω εκκλησιας γραψον ταδε λεγει [[κυριος]{.greek-abbr}]{.greek-added} ο κρατων τους επτα αστερας εν [τη]{.greek-omitted} [τηι]{.greek-added} δεξια [χειρι]{.greek-added} αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1 | instance no. 2]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ εισιν και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις και εβαστασας δια το ονομα μου και [ουκ]{.greek-omitted} [οὐκ]{.greek-added} [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

αλλα εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [τω]{.greek-omitted} [νικωντι]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [φαγειν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [παραδεισω]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted}[2:7]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} ταις εκκλησιαις [τω]{.greek-omitted} [τωι]{.greek-added} νικωντι δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} φαγειν εκ του ξυλου της ζωης ο εστιν εν [τω]{.greek-omitted} [μεσω]{.greek-added} [του]{.greek-added} [παραδεισω]{.greek-omitted} [παραδεισου]{.greek-added} του [θεου]{.greek-abbr} μου[2:7 | instance no. 2]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν [σου]{.greek-added} εκ των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βάλλειν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας [γραψον]{.greek-omitted} [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [την]{.greek-omitted} [ρομφαιαν]{.greek-omitted} [την]{.greek-omitted} [διστομον]{.greek-omitted} [την]{.greek-omitted} [οξειαν]{.greek-omitted}[2:12]{.aside}

[και]{.greek-omitted} [τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [περγαμω]{.greek-omitted} [εκκλησιας]{.greek-omitted} γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12 | instance no. 2]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις εν αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς μου ο πιστος [ος]{.greek-omitted} απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} και φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην [των]{.greek-omitted} νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν [τη]{.greek-omitted} [τηι]{.greek-added} ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις [τω]{.greek-omitted} [τωι]{.greek-added} νικωντι δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} του μαννα [φαγειν]{.greek-added} του κεκρυμμενου [και]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [ψηφον]{.greek-omitted} [λευκην]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [ψηφον]{.greek-omitted} [ονομα]{.greek-omitted} [καινον]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [ο]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [λαμβανων]{.greek-omitted}[2:17]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [τω]{.greek-omitted} [νικωντι]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [του]{.greek-omitted} [μαννα]{.greek-omitted} [του]{.greek-omitted} [κεκρυμμενου]{.greek-omitted} και δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17 | instance no. 2]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου οτι [αφεις]{.greek-omitted} [αφιης]{.greek-added} την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα [αυτη]{.greek-omitted} [αυτηι]{.greek-added} χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην [εαν]{.greek-omitted} [μη]{.greek-omitted} [μετανοησωσιν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [εργων]{.greek-omitted} [αυτης]{.greek-omitted}[2:22]{.aside}

[ιδου]{.greek-omitted} [βαλλω]{.greek-omitted} [αυτην]{.greek-omitted} [εις]{.greek-omitted} [κλινην]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μοιχευοντας]{.greek-omitted} [μετ]{.greek-omitted} [αυτης]{.greek-omitted} [εις]{.greek-omitted} [θλιψιν]{.greek-omitted} [μεγαλην]{.greek-omitted} εαν μη μετανοησωσιν εκ των εργων αυτης[2:22 | instance no. 2]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα [κεραμικα]{.greek-omitted} [κεραμεικα]{.greek-added} συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και [τω]{.greek-omitted} [τωι]{.greek-added} [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} της εν σαρδεσιν [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [τα]{.greek-omitted} [επτα]{.greek-omitted} [πνευματα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [επτα]{.greek-omitted} [αστερας]{.greek-omitted} [οιδα]{.greek-omitted} [σου]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [οτι]{.greek-omitted} [ονομα]{.greek-omitted} [εχεις]{.greek-omitted} [οτι]{.greek-omitted} [ζης]{.greek-omitted} [και]{.greek-omitted} [νεκρος]{.greek-omitted} [ει]{.greek-omitted}[3:1]{.aside}

[και]{.greek-omitted} [τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [σαρδεσιν]{.greek-omitted} εκκλησιας γραψον ταδε λεγει [[κυριος]{.greek-abbr}]{.greek-added} ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι ζης και νεκρος ει[3:1 | instance no. 2]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [στηριξον]{.greek-added} τα λοιπα α [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [εμελλον]{.greek-added} [αποθανειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευ[ε]{.unclear} ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη [γρηγορησης]{.greek-omitted} [γρηγορησηις]{.greek-added} ηξω επι σε ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωση]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} αγγελω της εν φιλαδελφεια εκκλησιας γραψον ταδε λεγει [[κυριος]{.greek-abbr}]{.greek-added} ο αγιος [ο]{.greek-omitted} [και]{.greek-added} αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει [και]{.greek-added} [κλειων]{.greek-added} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} και ουδεις ανοιξει[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν [ανεωγμενην]{.greek-omitted} [ηνεωγμενην]{.greek-added} ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης [ερχεσθαι]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [οικουμενης]{.greek-omitted} [ολης]{.greek-omitted} [πειρασαι]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[3:10]{.aside}

[οτι]{.greek-omitted} [ετηρησας]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [της]{.greek-omitted} [υπομονης]{.greek-omitted} [μου]{.greek-omitted} [καγω]{.greek-omitted} [σε]{.greek-omitted} [τηρησω]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [ωρας]{.greek-omitted} [του]{.greek-omitted} [πειρασμου]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10 | instance no. 2]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις [λαβη]{.greek-omitted} [λαβηι]{.greek-added} τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα μου το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος οφελον ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος μελλω σε εμεσαι [[και]{.corr}]{.greek-added} [[ελ[ε]{.unclear}[γχω]{.greek-supplied}]{.corr}]{.greek-added} [[[σε]{.greek-supplied}]{.corr}]{.greek-added} εκ του στοματος μου[3:16]{.aside}

οτι λεγεις [πλουσιος]{.greek-omitted} [ειμι]{.greek-omitted} [και]{.greek-omitted} [πεπλουτηκα]{.greek-omitted} [και]{.greek-omitted} [ουδενος]{.greek-omitted} [χρειαν]{.greek-omitted} [εχω]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [οιδας]{.greek-omitted} οτι [πλου]{.greek-added} [συ]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [ταλαιπωρος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ελεεινος]{.greek-omitted} [και]{.greek-omitted} [πτωχος]{.greek-omitted} [και]{.greek-omitted} [τυφλος]{.greek-omitted} [και]{.greek-omitted} [γυμνος]{.greek-omitted}[3:17]{.aside}

[σιος]{.greek-added} [οτι]{.greek-omitted} [λεγεις]{.greek-omitted} [πλουσιος]{.greek-omitted} ειμι και πεπλουτηκα και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και ο ελεεινος και πτωχος και τυφλος και γυμνος[3:17 | instance no. 2]{.aside}

συμβουλευω σοι αγορασαι χρυσιον [παρ]{.greek-omitted} [εμου]{.greek-omitted} πεπυρωμενον εκ πυρος ινα [πλουτησης]{.greek-omitted} [πλουτησηις]{.greek-added} και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος σου και κολλυριον ινα εγχριση τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλευε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις [ακουση]{.greek-omitted} [ακουσηι]{.greek-added} της φωνης μου και ανοιξη την θυραν και εισελευσομα[ι]{.unclear} προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} καθισαι μετ εμου εν [τω]{.greek-omitted} [τωι]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν [τω]{.greek-omitted} [τωι]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} αυτου[3:21]{.aside}

ο εχων ους ακουσατω [τι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [λεγει]{.greek-omitted} [ταις]{.greek-omitted} [εκκλησιαις]{.greek-omitted}[3:22]{.aside}

[ο]{.greek-omitted} [εχων]{.greek-omitted} [ους]{.greek-omitted} [ακουσατω]{.greek-omitted} τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22 | instance no. 2]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και επι τον θρονον καθημενος[4:2]{.aside}

ομοιος ορασει λιθω ιασπιδι και σαρδιω και [ιρις]{.greek-omitted} [ἴρις]{.greek-added} κυκλοθεν του θρονου [ομοιως]{.greek-omitted} [ομοια]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδω]{.greek-added}[4:3]{.aside}

και κυκλοθεν του θρονου [θρονοι]{.greek-omitted} [θρονους]{.greek-added} [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} και επι τους θρονους τους [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου [α]{.greek-added} [αι]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} [πνευματα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[4:5]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [εκπορευονται]{.greek-omitted} [αστραπαι]{.greek-omitted} [και]{.greek-omitted} [φωναι]{.greek-omitted} [και]{.greek-omitted} [βρονται]{.greek-omitted} [και]{.greek-omitted} [επτα]{.greek-omitted} [λαμπαδες]{.greek-omitted} [πυρος]{.greek-omitted} [καιομεναι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [αυτου]{.greek-omitted} [αι]{.greek-omitted} εισιν επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5 | instance no. 2]{.aside}

και ενωπιον του θρονου ως θαλασσα υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον εχον προσωπον [ανθρωπου]{.greek-abbr} και το τεταρτον [ζωον]{.greek-omitted} ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} [εστως]{.greek-added} εχον ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσι]{.greek-added} τα [τεσσαρα]{.greek-added} ζωα δοξαν και τιμην και ευχαριστιαν [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επι του θρονου [τω]{.greek-omitted} [τωι]{.greek-added} ζωντι εις τους αιωνας [των]{.greek-omitted} [αιωνων]{.greek-omitted}[4:9]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [δωσιν]{.greek-omitted} [τα]{.greek-omitted} [ζωα]{.greek-omitted} [δοξαν]{.greek-omitted} [και]{.greek-omitted} [τιμην]{.greek-omitted} [και]{.greek-omitted} [ευχαριστιαν]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} των αιωνων[4:9 | instance no. 2]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισι]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον [αλλον]{.greek-added} αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ανω ουτε επι της γης ουτε υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} ο ανοιγων το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον [και]{.greek-added} [ιδου]{.greek-added} εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως εσφαγμενον εχον κερατα επτα και οφθαλμους επτα α [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} του [θεου]{.greek-abbr} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και ηλθεν και ειληφεν εκ της δεξιας του καθημενου επι του θρονου [[το]{.corr}]{.greek-added} [[βιβλιον]{.corr}]{.greek-added}[5:7]{.aside}

και [οτε]{.greek-omitted} [οτι]{.greek-added} [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι επεσον ενωπιον του αρνιου εχοντες εκαστος κιθαραν και φια[λ]{.unclear}ας χρυσας γεμουσας θυμιαματων αι [εισιν]{.greek-omitted} [εισι]{.greek-added} [[αι]{.corr}]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} [καινην]{.greek-added} ωδην [καινην]{.greek-omitted} λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας [τω]{.greek-omitted} [θεω]{.greek-omitted} ημας [τωι]{.greek-added} [[θωι]{.greek-abbr}]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και ειδον και ηκουσα ως φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και τον πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και επι της γης και υποκατω της γης και επι της θαλασσης [οσα]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις [παντας]{.greek-omitted} [παντα]{.greek-added} [ηκουσα]{.greek-omitted} [λεγοντας]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [αρνιω]{.greek-omitted} [η]{.greek-omitted} [ευλογια]{.greek-omitted} και η [τιμη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [κρατος]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [αμην]{.greek-omitted}[5:13]{.aside}

[κουσα]{.greek-added} [λεγοντων]{.greek-added} [τωι]{.greek-added} [καθημενωι]{.greek-added} [επι]{.greek-added} [τωι]{.greek-added} [θρονωι]{.greek-added} και [παν]{.greek-omitted} [κτισμα]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted} [παντας]{.greek-omitted} [ηκουσα]{.greek-omitted} [λεγοντας]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added} η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων [αμην]{.greek-omitted}[5:13 | instance no. 2]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγεν]{.greek-added} το αμην και οι πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των επτα σφραγιδων και [ηκουσα]{.greek-omitted} [ηκουσαν]{.greek-added} ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνὴ]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ιδε]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα [νικηση]{.greek-omitted} [νικησηι]{.greek-added}[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [την]{.greek-added} [σφραγιδα]{.greek-added} την δευτεραν [σφραγιδα]{.greek-omitted} ηκουσα του δευτερου ζωου λεγοντος ερχου [και]{.greek-added} [ιδε]{.greek-added}[6:3]{.aside}

και [ειδον]{.greek-added} [και]{.greek-added} [ιδου]{.greek-added} εξηλθεν αλλος ιππος πυρος και [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επ αυτον εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} λαβειν την ειρηνην εκ της γης [και]{.greek-added} ινα αλληλους σφα[ξ]{.unclear}ωσιν και [εδοθη]{.greek-omitted} [εδοθηι]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και ιδε και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες κριθης δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ιδε]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο θανατος και ο αδης ηκολουθει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [και]{.corr} εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν [λιμω]{.greek-omitted} [λιμωι]{.greek-added} και εν [θανατω]{.greek-omitted} [θανατωι]{.greek-added} και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των [εσφα]{.greek-added} [εσφαγμενων]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [ην]{.greek-omitted} [ειχον]{.greek-omitted}[6:9]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [πεμπτην]{.greek-omitted} [σφραγιδα]{.greek-omitted} [ειδον]{.greek-omitted} [υποκατω]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [τας]{.greek-omitted} [ψυχας]{.greek-omitted} [των]{.greek-omitted} [εσφαγμενων]{.greek-omitted} [γμενων]{.greek-added} δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} ην ειχον[6:9 | instance no. 2]{.aside}

και εκραξαν [φωνη]{.greek-omitted} [φωνην]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαλην]{.greek-added} λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα αναπαυσωνται ετι χρονον εως [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκτεννεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος μελας εγενετο ως σακκος τριχινος και η σεληνη [ολη]{.greek-omitted} εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλουσα]{.greek-added} τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον ελισσομενον και παν ορος και νησος [εκ]{.greek-omitted} [των]{.greek-omitted} [τοπων]{.greek-omitted} [αυτων]{.greek-omitted} [εκινηθησαν]{.greek-omitted}[6:14]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ουρανος]{.greek-omitted} [απεχωρισθη]{.greek-omitted} [ως]{.greek-omitted} [βιβλιον]{.greek-omitted} [ελισσομενον]{.greek-omitted} [και]{.greek-omitted} [παν]{.greek-omitted} [ορος]{.greek-omitted} [και]{.greek-omitted} [νησος]{.greek-omitted} εκ των τοπων αυτων εκινηθησαν[6:14 | instance no. 2]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι [τωι]{.greek-added} [θρονωι]{.greek-added} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυνατα[ι]{.unclear} [σταθηναι]{.greek-omitted} [στηναι]{.greek-added}[6:17]{.aside}

### Chapter 7

και μετα τουτο ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους τεσσαρας ανεμους της γης ινα μη [πνεη]{.greek-omitted} [πνευσηι]{.greek-added} ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη [με]{.greek-added} [μεγαλη]{.greek-omitted} [τοις]{.greek-omitted} [τεσσαρσιν]{.greek-omitted} [αγγελοις]{.greek-omitted} [οις]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτοις]{.greek-omitted} [αδικησαι]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted}[7:2]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αλλον]{.greek-omitted} [αγγελον]{.greek-omitted} [αναβαινοντα]{.greek-omitted} [απο]{.greek-omitted} [ανατολης]{.greek-omitted} [ηλιου]{.greek-omitted} [εχοντα]{.greek-omitted} [σφραγιδα]{.greek-omitted} [θεου]{.greek-omitted} [ζωντος]{.greek-omitted} [και]{.greek-omitted} [εκραξεν]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [γαλη]{.greek-added} τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2 | instance no. 2]{.aside}

λεγων μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον και τεσσαρακοντα τεσσαρες χιλιαδες εσφραγισμενων εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης [ρουβιμ]{.greek-omitted} [ρουβειν]{.greek-added} δωδεκα χιλιαδες εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ δωδεκα χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι δωδεκα χιλιαδες εκ φυλης ισαχαρ δωδεκα χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων δωδεκα χιλιαδες [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [ιωσηφ]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [βενιαμιν]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} [εσφραγισμεναι]{.greek-omitted}[7:8]{.aside}

[εκ]{.greek-omitted} [φυλης]{.greek-omitted} [ζαβουλων]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} εκ φυλης ιωσηφ δωδεκα χιλιαδες εκ φυλης βενιαμιν δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added}[7:8 | instance no. 2]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εκ παντος εθνους και φυλων και λαων και γλωσσων εστωτας ενωπιον του θρονου και ενωπιον του αρνιου περιβεβλημενους στολας λευκας και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} ημων [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επι [τω]{.greek-omitted} [τωι]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} και [τω]{.greek-omitted} [τωι]{.greek-added} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added}[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου [αυτου]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} ημων εις τους αιωνας των [αιωνων]{.greek-omitted} [αμην]{.greek-omitted}[7:12]{.aside}

[λεγοντες]{.greek-omitted} [αμην]{.greek-omitted} [η]{.greek-omitted} [ευλογια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [ευχαριστια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [τιμη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δυναμις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [ισχυς]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [ημων]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} αιωνων αμην[7:12 | instance no. 2]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [κυριε]{.greek-abbr} μου συ οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν εν [τω]{.greek-omitted} [τωι]{.greek-added} αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ημερας και νυκτος εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν [ετι]{.greek-omitted} ουδ ου μη [πεση]{.greek-omitted} [πεσηι]{.greek-added} επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου ποιμαινει αυτους και οδηγει αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και [οτε]{.greek-omitted} [οτι]{.greek-added} [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην [και]{.greek-added} εγενετο [σιγη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [ως]{.greek-omitted} [ημιωριον]{.greek-omitted}[8:1]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [την]{.greek-omitted} [εβδομην]{.greek-omitted} [εγενετο]{.greek-omitted} σιγη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ως [ημιωριον]{.greek-omitted} [ἡμιώιρον]{.greek-added}[8:1 | instance no. 2]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος ηλθεν και εσταθη επι του θυσιαστηριου εχων λιβανωτον χρυσουν και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δωσ[ει]{.unclear}]{.greek-added} τ[αι]{.unclear}ς προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} βρονται και φωναι και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα [εν]{.greek-omitted} [αιματι]{.greek-omitted} [και]{.greek-omitted} [εβληθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [κατεκαη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [δενδρων]{.greek-omitted} [κατεκαη]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [χορτος]{.greek-omitted} [χλωρος]{.greek-omitted} [κατεκαη]{.greek-omitted}[8:7]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [χαλαζα]{.greek-omitted} [και]{.greek-omitted} [πυρ]{.greek-omitted} [μεμιγμενα]{.greek-omitted} εν αιματι και [εβληθη]{.greek-omitted} [εβληθησαν]{.greek-added} εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7 | instance no. 2]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα [πυρι]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον [μερος]{.greek-added} της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον [μερος]{.greek-added} των κτισματων [των]{.greek-added} εν τη [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος εσαλπισεν και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων [ινα]{.greek-omitted} [και]{.greek-added} [σκοτισθη]{.greek-omitted} [εσκοτισθη]{.greek-added} το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [ουκ]{.greek-added} [εφαινε]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος αετου πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος [ως]{.greek-omitted} [ωσπερ]{.greek-added} καπνος καμινου καιομενης και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου [εξηλθον]{.greek-omitted} [ακριδες]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυταις]{.greek-omitted} [εξουσια]{.greek-omitted} [ως]{.greek-omitted} [εχουσιν]{.greek-omitted} [εξουσιαν]{.greek-omitted} [οι]{.greek-omitted} [σκορπιοι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[9:3]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [καπνου]{.greek-omitted} εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν ο[ι]{.unclear} σκορπιοι της γης[9:3 | instance no. 2]{.aside}

και ερρεθη [αυταις]{.greek-omitted} [αυτoις]{.greek-added} ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χ[λωρ]{.unclear}ον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} [ο]{.unclear}ιτινες ουκ [εχουσιν]{.greek-omitted} [εχου[σι]{.greek-supplied}]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και εδοθη αυ[τ]{.unclear}αις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανιθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [ανθρωπον]{.greek-omitted} [[παιση]{.unclear}[ανθρωπον]{.greek-abbr}]{.greek-added}[9:5]{.aside}

και εν ταις ημεραις εκει[ν]{.unclear}αις [ζητη]{.greek-supplied}σουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον [και]{.greek-supplied} [ου]{.greek-supplied} [μ]{.greek-supplied}η [ευρησουσιν]{.greek-omitted} [εὕρωσιν]{.greek-added} αυτον και επιθυμη[σουσιν]{.greek-supplied} αποθανειν και φευξεται απ αυτων ο θανατος[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοι[ς]{.unclear} εις πολεμον και επι τας κεφα[λας]{.greek-supplied} αυτων ως στεφ[αν]{.greek-supplied}οι [χρυσοι]{.greek-omitted} [ομοιοι]{.greek-added} [χρυ[σω]{.unclear}]{.greek-added} και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας [ως]{.greek-omitted} [τριχας]{.greek-omitted} [γυναικων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [οδοντες]{.greek-omitted} [αυτων]{.greek-omitted} [ως]{.greek-omitted} [λεοντων]{.greek-omitted} [ησαν]{.greek-omitted}[9:8]{.aside}

[και]{.greek-omitted} [ειχον]{.greek-omitted} [τριχας]{.greek-omitted} ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8 | instance no. 2]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[και]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσι]{.greek-added} βασιλεα επ αυτων αγγελον της αβυσσου ονομα [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εβραιστι [αββαδων]{.greek-omitted} [αββααδων]{.greek-added} εν δε [τη]{.greek-omitted} [τηι]{.greek-added} [ελληνικη]{.greek-omitted} [ελληνικηι]{.greek-added} ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ηκουσα φωνην [μιαν]{.greek-omitted} [μεγαλην]{.greek-added} εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

λεγουσαν [τω]{.greek-omitted} [τωι]{.greek-added} εκτω [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} [ο]{.greek-omitted} [εχων]{.greek-omitted} [τωι]{.greek-added} [εχοντι]{.greek-added} την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι [τω]{.greek-omitted} [τωι]{.greek-added} [ποταμω]{.greek-omitted} [ποταμωι]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [μεγαλω]{.greek-omitted} [μεγαλωι]{.greek-added} [ευφρατη]{.greek-omitted}[9:14]{.aside}

[λεγουσαν]{.greek-omitted} [τω]{.greek-omitted} [εκτω]{.greek-omitted} [αγγελω]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [την]{.greek-omitted} [σαλπιγγα]{.greek-omitted} [λυσον]{.greek-omitted} [τους]{.greek-omitted} [τεσσαρας]{.greek-omitted} [αγγελους]{.greek-omitted} [τους]{.greek-omitted} [δεδεμενους]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [ποταμω]{.greek-omitted} [τω]{.greek-omitted} [μεγαλω]{.greek-omitted} [ευφρατη]{.greek-omitted} [ευφρατηι]{.greek-added}[9:14 | instance no. 2]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του ιππου μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν [τη]{.greek-omitted} [τηι]{.greek-added} ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ [εξουσια]{.greek-omitted} [εξουσιαν]{.greek-added} των ιππων εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων [ομοιαι]{.greek-omitted} [οφεων]{.greek-omitted} [εχουσαι]{.greek-omitted} [κεφαλας]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [αυταις]{.greek-omitted} [αδικουσιν]{.greek-omitted}[9:19]{.aside}

[η]{.greek-omitted} [γαρ]{.greek-omitted} [εξουσια]{.greek-omitted} [των]{.greek-omitted} [ιππων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [αυτων]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ουραις]{.greek-omitted} [αυτων]{.greek-omitted} [αι]{.greek-omitted} [γαρ]{.greek-omitted} [ουραι]{.greek-omitted} [αυτων]{.greek-omitted} ομοιαι οφεων εχουσαι κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19 | instance no. 2]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και εχων εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου βιβλιον [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [τον]{.greek-omitted} [δε]{.greek-omitted} [ευωνυμον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[10:2]{.aside}

[και]{.greek-omitted} [εχων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτου]{.greek-omitted} [βιβλιον]{.greek-omitted} [ανεωγμενον]{.greek-omitted} [και]{.greek-omitted} [εθηκεν]{.greek-omitted} [τον]{.greek-omitted} [ποδα]{.greek-omitted} [αυτου]{.greek-omitted} [τον]{.greek-omitted} [δεξιον]{.greek-omitted} επι της θαλασσης τον δε ευωνυμον επι της γης[10:2 | instance no. 2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης ηρεν την χειρα αυτου την δεξιαν εις τον ουρανον[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμοσε]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον ουρανον και τα εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και την γην και τα εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} και την θαλασσαν και τα εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν [μελλη]{.greek-omitted} [μελληι]{.greek-added} σαλπιζειν και ετελεσθη το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους [δου]{.greek-added} [δουλους]{.greek-omitted} [αυτου]{.greek-omitted} [τους]{.greek-omitted} [προφητας]{.greek-omitted}[10:7]{.aside}

[αλλ]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [της]{.greek-omitted} [φωνης]{.greek-omitted} [του]{.greek-omitted} [εβδομου]{.greek-omitted} [αγγελου]{.greek-omitted} [οταν]{.greek-omitted} [μελλη]{.greek-omitted} [σαλπιζειν]{.greek-omitted} [και]{.greek-omitted} [ετελεσθη]{.greek-omitted} [το]{.greek-omitted} [μυστηριον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ως]{.greek-omitted} [ευηγγελισεν]{.greek-omitted} [τους]{.greek-omitted} [λους]{.greek-added} [δουλους]{.greek-omitted} αυτου τους προφητας[10:7 | instance no. 2]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα μετ εμου και λεγουσα υπαγε λαβε το βιβλιδαριον το [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δουναι μοι το βιβλιδαριον και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτό]{.greek-added} και ην εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι μου ως μελι γλυκυ και [οτε]{.greek-omitted} [εφαγον]{.greek-omitted} [αυτο]{.greek-omitted} επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω [και]{.greek-added} [ειστηκει]{.greek-added} [ο]{.greek-added} [αγγελος]{.greek-added} λεγων εγειραι και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον [και]{.greek-omitted} [τους]{.greek-omitted} [προσκυνουντας]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted}[11:1]{.aside}

[και]{.greek-omitted} [εδοθη]{.greek-omitted} [μοι]{.greek-omitted} [καλαμος]{.greek-omitted} [ομοιος]{.greek-omitted} [ραβδω]{.greek-omitted} [λεγων]{.greek-omitted} [εγειραι]{.greek-omitted} [και]{.greek-omitted} [μετρησον]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [θυσιαστηριον]{.greek-omitted} και τους προσκυνουντας εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[11:1 | instance no. 2]{.aside}

και την αυλην την [εξωθεν]{.greek-omitted} [εσωθεν]{.greek-added} του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην [μετρησης]{.greek-omitted} [μετρησηις]{.greek-added} οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα [και]{.greek-omitted} δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι [αι]{.greek-omitted} ενωπιον του [κυριου]{.greek-abbr} της γης [εστωσαι]{.greek-omitted} [εστωτες]{.greek-added}[11:4]{.aside}

και ει τις [θελει]{.greek-added} αυτους [θελει]{.greek-omitted} αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους αδικησαι ουτως δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον [ουρανον]{.greek-abbr} εξουσιαν κλεισαι ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην οσακις εαν θελησωσιν [εν]{.greek-omitted} [παση]{.greek-omitted} [πληγη]{.greek-omitted}[11:6]{.aside}

[ουτοι]{.greek-omitted} [εχουσιν]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [υετος]{.greek-omitted} [βρεχη]{.greek-omitted} [τας]{.greek-omitted} [ημερας]{.greek-omitted} [της]{.greek-omitted} [προφητειας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχουσιν]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [υδατων]{.greek-omitted} [στρεφειν]{.greek-omitted} [αυτα]{.greek-omitted} [εις]{.greek-omitted} [αιμα]{.greek-omitted} [και]{.greek-omitted} [παταξαι]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [οσακις]{.greek-omitted} [εαν]{.greek-omitted} [θελησωσιν]{.greek-omitted} εν παση πληγη[11:6 | instance no. 2]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσω]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματικως]{.greek-omitted} [[πνευματι]{.greek-abbr}]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} σοδομα και αιγυπτος οπου [και]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [[α]{.unclear}φησουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και ευφρανθησονται και δωρα δωσουσιν αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν εις αυτους και εστησαν επι τους ποδας [αυτων]{.greek-omitted} [και]{.greek-omitted} [φοβος]{.greek-omitted} [μεγας]{.greek-omitted} [επεσεν]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [θεωρουντας]{.greek-omitted} [αυτους]{.greek-omitted}[11:11]{.aside}

[και]{.greek-omitted} [μετα]{.greek-omitted} [τας]{.greek-omitted} [τρεις]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [ημισυ]{.greek-omitted} [πνευμα]{.greek-omitted} [ζωης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [εστησαν]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} αυτων και φοβος μεγας επεσεν επι τους θεωρουντας αυτους[11:11 | instance no. 2]{.aside}

και [ηκουσα]{.greek-omitted} [ηκουσαν]{.greek-added} φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν [τη]{.greek-omitted} [τηι]{.greek-added} [νεφελη]{.greek-omitted} [νεφεληι]{.greek-added} και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη [τη]{.greek-omitted} [τηι]{.greek-added} ημερα εγενετο σεισμος μεγας και το δεκατον της πολεως επεσεν και απεκτανθησαν εν [τω]{.greek-omitted} [τωι]{.greek-added} [σεισμω]{.greek-omitted} [σεισμωι]{.greek-added} ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν η ουαι η τριτη ιδου ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} λεγουσαι εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι οι ενωπιον του θρονου του [θεου]{.greek-abbr} [οι]{.greek-added} [καθηντες]{.greek-added} [καθημενοι]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [θρονους]{.greek-omitted} [αυτων]{.greek-omitted} [επεσον]{.greek-omitted} [επι]{.greek-omitted} [τα]{.greek-omitted} [προσωπα]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[11:16]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [οι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [καθημενοι]{.greek-omitted} επι τους θρονους αυτων επεσον επι τα προσωπα αυτων και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added}[11:16 | instance no. 2]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους [διαφθειροντας]{.greek-omitted} [διαφθειραντας]{.greek-added} την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} [ο]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και ωφθη η κιβωτος της διαθηκης [του]{.greek-omitted} [αυτου]{.greek-added} [κυριου]{.greek-omitted} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} αυτου και εγενοντο αστραπαι και [βρονται]{.greek-added} [και]{.greek-added} φωναι και [βρονται]{.greek-omitted} [σεισμοι]{.greek-added} και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων [αυτης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [αυτης]{.greek-omitted} [στεφανος]{.greek-omitted} [αστερων]{.greek-omitted} [δωδεκα]{.greek-omitted}[12:1]{.aside}

[και]{.greek-omitted} [σημειον]{.greek-omitted} [μεγα]{.greek-omitted} [ωφθη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [γυνη]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [τον]{.greek-omitted} [ηλιον]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1 | instance no. 2]{.aside}

και εν γαστρι εχουσα εκραζεν ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και ιδου δρακων πυρος μεγας εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἕστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν [τεκη]{.greek-omitted} [τεκηι]{.greek-added} το τεκνον αυτης καταφαγη [αυτο]{.greek-added}[12:4]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας χιλιας [[σξ]{.greek-abbr}]{.greek-added} [διακοσιας]{.greek-omitted} [εξηκοντα]{.greek-omitted}[12:6]{.aside}

και εγενετο πολεμος εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ετι εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [ουρανωι]{.greek-added} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν [την]{.greek-omitted} [ψυχην]{.greek-omitted} [τας]{.greek-added} [ψυχας]{.greek-added} αυτων αχρι θανατου[12:11]{.aside}

δια τουτο [ευφραινεσθε]{.greek-omitted} [ουρανοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted} [σκηνουντες]{.greek-omitted} [ουαι]{.greek-omitted} [τη]{.greek-omitted} [γη]{.greek-omitted} [και]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [οτι]{.greek-omitted} [κατεβη]{.greek-omitted} [ο]{.greek-omitted} [διαβολος]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [εχων]{.greek-omitted} [θυμον]{.greek-omitted} [μεγαν]{.greek-omitted} [ειδως]{.greek-omitted} [οτι]{.greek-omitted} [ολιγον]{.greek-omitted} [καιρον]{.greek-omitted} [εχει]{.greek-omitted}[12:12]{.aside}

[δια]{.greek-omitted} [τουτο]{.greek-omitted} ευφραινεσθε [ουρανοι]{.greek-abbr} και οι εν αυτοις σκηνουντες ουαι [τη]{.greek-omitted} [τηι]{.greek-added} [γη]{.greek-omitted} [γηι]{.greek-added} και [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12 | instance no. 2]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν [τη]{.greek-omitted} [τηι]{.greek-added} γυναικι δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον αυτης οπως τρεφηται εκει καιρον και καιρους και [ημισυ]{.greek-omitted} [ημυσυ]{.greek-added} καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην π[ο]{.unclear}ταμοφορητον [ποιηση]{.greek-omitted} [ποιησηι]{.greek-added}[12:15]{.aside}

και εβοηθησεν η γη [τη]{.greek-omitted} [τηι]{.greek-added} γυναικι και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [η]{.greek-omitted} [γη]{.greek-omitted} το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι [τη]{.greek-omitted} [τηι]{.greek-added} γυναικι και απηλθεν [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [λοιπων]{.greek-omitted} [του]{.greek-omitted} [σπερματος]{.greek-omitted} [αυτης]{.greek-omitted} [των]{.greek-omitted} [τηρουντων]{.greek-omitted} [τας]{.greek-omitted} [εντολας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [εχοντων]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted}[12:17]{.aside}

[και]{.greek-omitted} [ωργισθη]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [γυναικι]{.greek-omitted} [και]{.greek-omitted} [απηλθεν]{.greek-omitted} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17 | instance no. 2]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον εχον κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον [ομοιον]{.greek-added} ην [ομοιον]{.greek-omitted} παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα λεοντος και εδωκεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου ωσει εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [οτι]{.greek-added} [εδωκε]{.greek-added} την εξουσιαν [τω]{.greek-omitted} [τωι]{.greek-added} [θη]{.greek-added} [θηριω]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [λεγοντες]{.greek-omitted} [τις]{.greek-omitted} [ομοιος]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [και]{.greek-omitted} [τις]{.greek-omitted} [δυνατος]{.greek-omitted} [πολεμησαι]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[13:4]{.aside}

[ριωι]{.greek-added} και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [δρακοντι]{.greek-omitted} [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} λεγοντες τις ομοιος [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} και τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4 | instance no. 2]{.aside}

και εδ[ο]{.unclear}θη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημα]{.greek-added} και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξουσια πολεμον ποιησαι μηνας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} δυο[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις [βλασφημιαν]{.greek-omitted} [βλασφημιας]{.greek-added} προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου τους εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [ουρανωι]{.greek-added} σκηνουντας[13:6]{.aside}

και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [πολεμον]{.greek-added} ποιησαι [πολεμον]{.greek-omitted} μετα των αγιων και νικησαι αυτους και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξουσια επι πασαν φυλην και λαον και γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες επι της γης ων ου γεγραπται το ονομα εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} αιχμαλωσιαν [υπαγει]{.greek-omitted} [απαγει]{.greek-added} [ει]{.greek-omitted} [τις]{.greek-omitted} [εν]{.greek-omitted} [μαχαιρα]{.greek-omitted} [αποκτενει]{.greek-omitted} [δει]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [μαχαιρα]{.greek-omitted} [αποκτανθηναι]{.greek-omitted} [ωδε]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [υπομονη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πιστις]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted}[13:10]{.aside}

[ει]{.greek-omitted} [εις]{.greek-added} [τις]{.greek-omitted} [εχει]{.greek-omitted} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτέννει]{.greek-added} δει αυτον εν μαχαιρα [αποκτανθηναι]{.greek-omitted} [ἀποκτανθῆναι]{.greek-added} ωδε εστιν η υπομονη και η πιστις των αγιων[13:10 | instance no. 2]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και ειχεν κερατα δυο ομοια αρνιω και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν [ποιει]{.greek-omitted} [ποιησει]{.greek-added} ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιησει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} [το]{.greek-omitted} [θηριον]{.greek-omitted} [το]{.greek-omitted} [πρωτον]{.greek-omitted} [τωι]{.greek-added} [θηριωι]{.greek-added} [τωι]{.greek-added} [πρωτωι]{.greek-added} ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και [ποιει]{.greek-omitted} [ποιησει]{.greek-added} [μεγαλα]{.greek-added} σημεια [μεγαλα]{.greek-omitted} [ινα]{.greek-added} και πυρ [ινα]{.greek-omitted} [ποιηση]{.greek-added} εκ του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [καταβηναι]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [ὃς]{.greek-added} [εχει]{.greek-added} την πληγην [και]{.greek-omitted} [εζησεν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

[και]{.greek-omitted} [πλανα]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} της [μαχαιρας]{.greek-added} [γης]{.greek-omitted} [δια]{.greek-omitted} [τα]{.greek-omitted} [σημεια]{.greek-omitted} [α]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [ποιησαι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [λεγων]{.greek-omitted} [τοις]{.greek-omitted} [κατοικουσιν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ποιησαι]{.greek-omitted} [εικονα]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [την]{.greek-omitted} [πληγην]{.greek-omitted} και εζησεν [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14 | instance no. 2]{.aside}

και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [πνευμα]{.greek-abbr} δουναι [τη]{.greek-omitted} [τηι]{.greek-added} εικονι του θηριου ινα και λαληση η εικων του θηριου και [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} εικονι του θηριου αποκτανθωσιν[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} αυτοις [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της χειρος αυτων της δεξιας η επι το μετωπον αυτων[13:16]{.aside}

και ινα [μηδεις]{.greek-added} [μη]{.greek-omitted} [τις]{.greek-omitted} [δυναται]{.greek-omitted} [δυνηται]{.greek-added} [πωλησαι]{.greek-added} [η]{.greek-added} αγορασαι [ετι]{.greek-added} [η]{.greek-omitted} [πωλησαι]{.greek-omitted} ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ ανθρωπου εστιν [και]{.greek-omitted} ο αριθμος αυτου [[χξς]{.greek-abbr}]{.greek-added} [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και ειδον και ιδου [το]{.greek-omitted} αρνιον [εστηκος]{.greek-omitted} [εστως]{.greek-added} επι το ορος σιων και μετ αυτου αριθμος εκατον τεσσαρακοντα τεσσαρες [χιλιαδες]{.greek-omitted} [εχουσαι]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [αυτου]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[14:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [το]{.greek-omitted} [αρνιον]{.greek-omitted} [εστηκος]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [ορος]{.greek-omitted} [σιων]{.greek-omitted} [και]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [αριθμος]{.greek-omitted} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων αυτων[14:1 | instance no. 2]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλης και η φωνη ην ηκουσα ως κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυν[α]{.unclear}το]{.greek-added} μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι εισιν οι ακολουθουντες [τω]{.greek-omitted} [τωι]{.greek-added} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added} οπου αν υπαγη ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} και τω αρνιω[14:4]{.aside}

και ουχ ευρεθη εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι αυτων ψευδος αμωμοι γαρ εισιν [ουτοι]{.greek-added} [εισιν]{.greek-added} [οι]{.greek-added} [ακολουθουντες]{.greek-added} [τωι]{.greek-added} [αρνιωι]{.greek-added}[14:5]{.aside}

και ειδον αγγελον [αλλον]{.greek-added} πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον [ευαγγελισαι]{.greek-omitted} [ευαγγελισασθαι]{.greek-added} [επι]{.greek-added} τους καθημενους επι της γης και επι παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-abbr} και δοτε [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε [τωι]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [ποιησαντι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος δευτερος αγγελος [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη [η]{.greek-added} εκ του οινου του θυμου της πορνειας αυτης [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις προσκυνει το θηριον και την εικο[ν]{.unclear}α αυτου και λαμβανει [το]{.greek-added} χαραγμα επι του μετωπου αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του κεκερασμενου [ακρατου]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ποτηριω]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [βασανισθησεται]{.greek-omitted} [εν]{.greek-omitted} [πυρι]{.greek-omitted} [και]{.greek-omitted} [θειω]{.greek-omitted} [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [αγγελων]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted}[14:10]{.aside}

[και]{.greek-omitted} [αυτος]{.greek-omitted} [πιεται]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [κεκερασμενου]{.greek-omitted} ακρατου εν [τω]{.greek-omitted} [τωι]{.greek-added} [ποτηριω]{.greek-omitted} [ποτηριωι]{.greek-added} της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10 | instance no. 2]{.aside}

και ο καπνος του βασανισμου αυτων εις αιωνας αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} ινα αναπαυσωνται εκ των κοπων αυτων τα δε εργα αυτων ακολουθει μετ αυτων[14:13]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην καθημενον ομοιον υιω [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον [χρυσουν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτου]{.greek-omitted} [δρεπανον]{.greek-omitted} [οξυ]{.greek-omitted}[14:14]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [νεφελη]{.greek-omitted} [λευκη]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [νεφελην]{.greek-omitted} [καθημενον]{.greek-omitted} [ομοιον]{.greek-omitted} [υιω]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εχων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [αυτου]{.greek-omitted} [στεφανον]{.greek-omitted} χρυσουν και εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου δρεπανον οξυ[14:14 | instance no. 2]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου κραζων εν φωνη μεγαλη [τω]{.greek-omitted} [τωι]{.greek-added} καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και [αγγελος]{.greek-added} αλλος [αγγελος]{.greek-omitted} εξηλθεν εκ του ναου του εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι [ηκμασαν]{.greek-omitted} [ηκμασεν]{.greek-added} [αι]{.greek-omitted} [η]{.greek-added} [σταφυλαι]{.greek-omitted} [σταφυλη]{.greek-added} [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[14:18]{.aside}

και [εβαλεν]{.greek-omitted} [εξεβαλεν]{.greek-added} ο αγγελος το δρεπανον αυτου εις την γην και ετρυγησεν την [αμπελον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ληνον]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τον]{.greek-omitted} [μεγαν]{.greek-omitted}[14:19]{.aside}

[και]{.greek-omitted} [εβαλεν]{.greek-omitted} [ο]{.greek-omitted} [αγγελος]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [ετρυγησεν]{.greek-omitted} [την]{.greek-omitted} αμπελον της γης και εβαλεν εις την ληνον [την]{.greek-added} [μεγαλην]{.greek-added} του θυμου του [θεου]{.greek-abbr} [τον]{.greek-omitted} [μεγαν]{.greek-omitted}[14:19 | instance no. 2]{.aside}

και επατηθη η [λινος]{.greek-added} [ληνος]{.corr} εξωθεν της πολεως και εξηλθεν αιμα εκ της [λινου]{.greek-added} [ληνου]{.corr} αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} μεγα και θαυμαστον αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην [την]{.greek-added} [μεμιγμενην]{.greek-added} [πυρι]{.greek-added} εχοντας [τας]{.greek-added} κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην μωυσεως [του]{.greek-omitted} [[μωυσεος]{.corr}]{.greek-added} δουλου του [θεου]{.greek-abbr} και την [ωδην]{.greek-omitted} [φωνην]{.greek-added} του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [παντοκρατωρ]{.greek-omitted} [δικαιαι]{.greek-omitted} [και]{.greek-omitted} [αληθιναι]{.greek-omitted} [αι]{.greek-omitted} [οδοι]{.greek-omitted} [σου]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted}[15:3]{.aside}

[και]{.greek-omitted} [αδουσιν]{.greek-omitted} [την]{.greek-omitted} [ωδην]{.greek-omitted} [μωυσεως]{.greek-omitted} [του]{.greek-omitted} [δουλου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [ωδην]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [λεγοντες]{.greek-omitted} [μεγαλα]{.greek-omitted} [και]{.greek-omitted} [θαυμαστα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [κυριε]{.greek-omitted} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3 | instance no. 2]{.aside}

τις ου μη φοβηθη σε [κυριε]{.greek-abbr} και δοξαση το ονομα σου οτι μονος αγιος οτι [παντες]{.greek-added} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} οι ησαν ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος [εκ]{.greek-added} [του]{.greek-added} καπνου [εκ]{.greek-omitted} της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα [πληγαι]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αγγελων]{.greek-omitted}[15:8]{.aside}

[και]{.greek-omitted} [εγεμισθη]{.greek-omitted} [ο]{.greek-omitted} [ναος]{.greek-omitted} [καπνου]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [δοξης]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [εισελθειν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθωσιν]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} πληγαι των επτα αγγελων[15:8 | instance no. 2]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας επτα φιαλας του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος [αγγελος]{.greek-added} και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας [τη]{.greek-omitted} [τηι]{.greek-added} εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη [ζωσα]{.greek-omitted} απεθανεν εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added}[16:3]{.aside}

και ο τριτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην [ο]{.greek-omitted} οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν [και]{.greek-omitted} [αιμα]{.greek-omitted} [αυτοις]{.greek-omitted} [εδωκας]{.greek-omitted} [πιειν]{.greek-omitted} [αξιοι]{.greek-omitted} [εισιν]{.greek-omitted}[16:6]{.aside}

[οτι]{.greek-omitted} [αιμα]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [προφητων]{.greek-omitted} [εξεχεαν]{.greek-omitted} και αιμα αυτοις [εδωκας]{.greek-omitted} [ε[ι]{.unclear}δωκας]{.greek-added} πιειν αξιοι εισιν[16:6 | instance no. 2]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο [τεταρτος]{.greek-omitted} [τεταρχος]{.greek-added} αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} καυματισαι εν πυρι τους ανθρωπους[16:8]{.aside}

και εκαυματισθησαν οι ανθρωποι καυμα μεγα και εβλασφημησαν οι ανθρωποι το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δοξαν[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και [εμασωντο]{.greek-omitted} [εμασσωντο]{.greek-added} τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [αγγελος]{.greek-added} εξεχεεν [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [ποταμον]{.greek-omitted} [τον]{.greek-omitted} [μεγαν]{.greek-omitted} [ευφρατην]{.greek-omitted} [και]{.greek-omitted} [εξηρανθη]{.greek-omitted} [το]{.greek-omitted} [υδωρ]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [ετοιμασθη]{.greek-omitted} [η]{.greek-omitted} [οδος]{.greek-omitted} [των]{.greek-omitted} [βασιλεων]{.greek-omitted} [των]{.greek-omitted} [απο]{.greek-omitted} [ανατολης]{.greek-omitted} [ηλιου]{.greek-omitted}[16:12]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [εξεχεεν]{.greek-omitted} την φιαλην αυτου επι τον ποταμον τον μεγαν [τον]{.greek-added} ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12 | instance no. 2]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου [πνευματα]{.greek-abbr} ακαθαρτα τρια ως βατραχοι[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ [πνευματα]{.greek-abbr} δαιμονιων ποιουντα σημεια α εκπορευεται επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος [περιπατη]{.greek-omitted} [περιπατηι]{.greek-added} και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἁρμαγεδών]{.greek-added}[16:16]{.aside}

και ο [εβδομος]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου [επι]{.greek-omitted} [τον]{.greek-omitted} [αερα]{.greek-omitted} [και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [λεγουσα]{.greek-omitted} [γεγονεν]{.greek-omitted}[16:17]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [εβδομος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} επι τον αερα και εξηλθεν φωνη μεγαλη απο του ναου του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα γεγονεν[16:17 | instance no. 2]{.aside}

και εγενοντο αστραπαι και βρονται και φωναι και σεισμος μεγας οιος ουκ εγενετο αφ ου οι [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων επεσον και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι [αυτη]{.greek-omitted} [αυτηι]{.greek-added} το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα νησος εφυγεν και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι ανθρωποι τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι [το]{.greek-omitted} [κριμα]{.greek-omitted} [της]{.greek-omitted} [πορνης]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [της]{.greek-omitted} [καθημενης]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [υδατων]{.greek-omitted} [των]{.greek-omitted} [πολλων]{.greek-omitted}[17:1]{.aside}

[και]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [εχοντων]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [φιαλας]{.greek-omitted} [και]{.greek-omitted} [ελαλησεν]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [λεγων]{.greek-omitted} [δευρο]{.greek-omitted} [δειξω]{.greek-omitted} [σοι]{.greek-omitted} το κριμα της πορνης της μεγαλης της καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1 | instance no. 2]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον κοκκινον γεμον [ονοματα]{.greek-omitted} [ονοματων]{.greek-added} βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἦν]{.greek-added} περιβεβλημενη [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον [κεχρυσωμενη]{.greek-omitted} [περικεχρυσωμενη]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσιωι]{.greek-added} και [λιθω]{.greek-omitted} [λιθωι]{.greek-added} [τιμιω]{.greek-omitted} [τιμιωι]{.greek-added} και μαργαριταις εχουσα ποτηριον χρυσουν εν τη χειρι αυτης γεμον βδελυγματων και τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν [εκ]{.greek-omitted} του αιματος των αγιων εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} [και]{.greek-omitted} [εθαυμασα]{.greek-omitted} [ιδων]{.greek-omitted} [αυτην]{.greek-omitted} [θαυμα]{.greek-omitted} [μεγα]{.greek-omitted}[17:6]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [μεθυουσαν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [αιματος]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [αιματος]{.greek-omitted} [των]{.greek-omitted} [μαρτυρων]{.greek-omitted} [ιησου]{.greek-omitted} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6 | instance no. 2]{.aside}

και ειπεν μοι ο αγγελος δια τι εθαυμασας εγω ερω σοι το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ εστιν και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες επι της γης ων ου γεγραπται τα ονοματα επι το βιβλιον της ζωης απο καταβολης κοσμου βλεποντων οτι ην το θηριον και ουκ εστιν και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [εισιν]{.greek-added} [επτα]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε επεσον ο εις εστιν ο αλλος ουπω ηλθεν και οταν [ελθη]{.greek-omitted} [ελθηι]{.greek-added} ολιγον δει αυτον μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ εστιν και αυτος ογδοος εστιν και εκ των επτα εστιν και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την δυναμιν και [την]{.greek-omitted} εξουσιαν αυτων [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου πολεμησουσιν και το αρνιον νικησει αυτους οτι κυριος κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι εισιν και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην ποιησουσιν αυτην και γυμνην ποιησουσιν αυτην και τας σαρκας αυτης φαγονται και αυτην [κατακαυσουσιν]{.greek-omitted} [κατακαυσουσι]{.greek-added} [εν]{.greek-omitted} πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι [γνωμην]{.greek-omitted} [μιαν]{.greek-omitted} [και]{.greek-omitted} [δουναι]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [αυτων]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθωσιν]{.greek-omitted} [οι]{.greek-omitted} [λογοι]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[17:17]{.aside}

[ο]{.greek-omitted} [γαρ]{.greek-omitted} [θεος]{.greek-omitted} [εδωκεν]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [καρδιας]{.greek-omitted} [αυτων]{.greek-omitted} [ποιησαι]{.greek-omitted} [την]{.greek-omitted} [γνωμην]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ποιησαι]{.greek-omitted} γνωμην μιαν και δουναι την βασιλειαν αυτων [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17 | instance no. 2]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} μετα ταυτα ειδον [αγγελον]{.greek-added} αλλον [αγγελον]{.greek-omitted} καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν ισχυρα [φωνη]{.greek-omitted} [φωνηι]{.greek-added} λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος πνευματος ακαθαρτου και φυλακη παντος ορνεου ακαθαρτου και [φυλακη]{.greek-added} [παντος]{.greek-added} [θηριου]{.greek-added} [ακαθαρτου]{.greek-added} [και]{.greek-added} μεμισημενου[18:2]{.aside}

οτι εκ του οινου του θυμου της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκασι]{.greek-added} παντα τα εθν[η]{.unclear} και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του ουρανου λεγουσαν εξελθε εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του ουρανου και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν και διπλωσατε [αυτη]{.greek-omitted} [αυτηι]{.greek-added} διπλα κατα τα εργα αυτης εν [τω]{.greek-omitted} [τωι]{.greek-added} [ποτηριω]{.greek-omitted} [ποτηριωι]{.greek-added} [ω]{.greek-omitted} [ωι]{.greek-added} εκερασεν κερασατε αυτη διπλουν[18:6]{.aside}

οσα εδοξασεν [αυτην]{.greek-omitted} [εαυτην]{.greek-added} και [εστρηνιασεν]{.greek-omitted} [εστρηνιασε]{.greek-added} τοσουτον δοτε αυτη βασανισμον και πενθος οτι εν [τη]{.greek-omitted} [τηι]{.greek-added} [καρδια]{.greek-omitted} [καρδιαι]{.greek-added} αυτης λεγει οτι [εγω]{.greek-added} καθημαι βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν [μια]{.greek-omitted} [μιαι]{.greek-added} [ημερα]{.greek-omitted} [ημεραι]{.greek-added} ηξουσιν αι πληγαι αυτης θανατος [και]{.greek-omitted} πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο [κρινων]{.greek-added} [κρινας]{.greek-omitted} [αυτην]{.greek-omitted}[18:8]{.aside}

[δια]{.greek-omitted} [τουτο]{.greek-omitted} [εν]{.greek-omitted} [μια]{.greek-omitted} [ημερα]{.greek-omitted} [ηξουσιν]{.greek-omitted} [αι]{.greek-omitted} [πληγαι]{.greek-omitted} [αυτης]{.greek-omitted} [θανατος]{.greek-omitted} [και]{.greek-omitted} [πενθος]{.greek-omitted} [και]{.greek-omitted} [λιμος]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [πυρι]{.greek-omitted} [κατακαυθησεται]{.greek-omitted} [οτι]{.greek-omitted} [ισχυρος]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [κρινας]{.greek-omitted} αυτην[18:8 | instance no. 2]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και κοψονται επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του βασανισμου αυτης λεγοντες ουαι ουαι [ουαι]{.greek-added} η πολις η μεγαλη [η]{.greek-added} βαβυλων η πολις η ισχυρα οτι [μια]{.greek-omitted} [μιαι]{.greek-added} ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και πενθησουσιν επ [αυτη]{.greek-omitted} [αυτηι]{.greek-added} οτι τον γομον αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και μαργαριτου και βυσσινου και [πορφυρου]{.greek-omitted} [πορφυρας]{.greek-added} και σηρικου και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κινναμωμον]{.greek-added} [και]{.greek-added} [αμωμον]{.greek-added} και θυμιαματα και μυρον και λιβανον και [οινον]{.greek-omitted} [και]{.greek-omitted} ελαιον [και]{.greek-omitted} [σεμιδαλιν]{.greek-omitted} [και]{.greek-omitted} [σιτον]{.greek-omitted} [και]{.greek-omitted} [προβατα]{.greek-omitted} [και]{.greek-omitted} [κτηνη]{.greek-omitted} [και]{.greek-omitted} [ιππων]{.greek-omitted} [και]{.greek-omitted} [ραιδων]{.greek-omitted} [και]{.greek-omitted} [σωματων]{.greek-omitted} [και]{.greek-omitted} [ψυχας]{.greek-omitted} [ανθρωπων]{.greek-omitted}[18:13]{.aside}

[και]{.greek-omitted} [κιναμωμον]{.greek-omitted} [και]{.greek-omitted} [θυμιαματα]{.greek-omitted} [και]{.greek-omitted} [μυρον]{.greek-omitted} [και]{.greek-omitted} [λιβανον]{.greek-omitted} και οινον [και]{.greek-omitted} [ελαιον]{.greek-omitted} και σεμιδαλιν και σιτον και προβατα και κτηνη και ιππων και ραιδων και σωματων [και]{.greek-omitted} ψυχας [ανθρωπων]{.greek-abbr}[18:13 | instance no. 2]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα απωλετο απο σου και ουκετι [αυτα]{.greek-omitted} ου μη [ευρης]{.greek-omitted} [ευρησουσιν]{.greek-added} [αυτα]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15]{.aside}

και λεγοντες [ουαι]{.greek-added} ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον και κεχρυσωμενη [χρυσιω]{.greek-omitted} [χρυσιωι]{.greek-added} και [λιθω]{.greek-omitted} [λιθωι]{.greek-added} τιμιω και μαργαριταις[18:16]{.aside}

οτι [μια]{.greek-omitted} [μιαι]{.greek-added} [ωρα]{.greek-omitted} [ωραι]{.greek-added} ηρημωθη ο τοσουτος πλουτος και πας κυβερνητης και πας ο επι [τοπον]{.greek-omitted} [των]{.greek-added} [πλοιων]{.greek-added} πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και εκραζον [βλεποντες]{.greek-omitted} [τον]{.greek-omitted} [καπνον]{.greek-omitted} [της]{.greek-omitted} [πυρωσεως]{.greek-omitted} [αυτης]{.greek-omitted} [λεγοντες]{.greek-omitted} [τις]{.greek-omitted} [ομοια]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [τη]{.greek-omitted} [μεγαλη]{.greek-omitted}[18:18]{.aside}

[και]{.greek-omitted} [εκραζον]{.greek-omitted} βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια [τη]{.greek-omitted} [τηι]{.greek-added} πολει [τη]{.greek-omitted} [τηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added}[18:18 | instance no. 2]{.aside}

και εβαλον χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες και λεγοντες ουαι ουαι [ουαι]{.greek-added} η πολις η μεγαλη εν [η]{.greek-omitted} [ηι]{.greek-added} επλουτησαν παντες οι εχοντες τα πλοια εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} εκ της τιμιοτητος αυτης οτι [μια]{.greek-omitted} [μιαι]{.greek-added} [ωρα]{.greek-omitted} [ωραι]{.greek-added} ηρημωθη[18:19]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη [ευρεθη]{.greek-omitted} [ευρεθηι]{.greek-added} ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης πασης τεχνης ου μη [ευρεθη]{.greek-omitted} [ευρεθηι]{.greek-added} εν σοι ετι και [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22]{.aside}

[και]{.greek-omitted} [φωνη]{.greek-omitted} [κιθαρωδων]{.greek-omitted} [και]{.greek-omitted} [μουσικων]{.greek-omitted} [και]{.greek-omitted} [αυλητων]{.greek-omitted} [και]{.greek-omitted} [σαλπιστων]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [τεχνιτης]{.greek-omitted} [πασης]{.greek-omitted} [τεχνης]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} φωνη μυλου ου μη [ακουσθη]{.greek-omitted} [φανηι]{.greek-added} εν σοι ετι[18:22 | instance no. 2]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [φανῆι]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη [ακουσθη]{.greek-omitted} [ακουσθηι]{.greek-added} εν σοι ετι οτι οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν [τη]{.greek-omitted} [τηι]{.greek-added} φαρμακεια σου [επλανηθησαν]{.greek-omitted} [επλανησας]{.greek-added} παντα τα εθνη[18:23]{.aside}

και εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} αιματα προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα ηκουσα ως φωνην μεγαλην οχλου πολλου εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η δυναμις και η δοξα του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [διεφθειρε]{.greek-added} την γην εν [τη]{.greek-omitted} [τηι]{.greek-added} [πορνεια]{.greek-omitted} [πορνειαι]{.greek-added} αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ χειρος αυτης[19:2]{.aside}

και [εκ]{.greek-added} [δευτερον]{.greek-omitted} [δευτερου]{.greek-added} [ειρηκεν]{.greek-omitted} [ειρηκασιν]{.greek-added} αλληλουια και ο καπνος αυτης αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι [πρεσβυ]{.greek-added} [πρεσβυτεροι]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [τεσσαρα]{.greek-omitted} [ζωα]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [λεγοντες]{.greek-omitted} [αμην]{.greek-omitted} [αλληλουια]{.greek-omitted}[19:4]{.aside}

[τεροι]{.greek-added} [και]{.greek-omitted} [επεσον]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} οι εικοσι τεσσαρες και τα τεσσαρα ζωα και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τωι]{.greek-added} [θρονωι]{.greek-added} λεγοντες αμην αλληλουια[19:4 | instance no. 2]{.aside}

και φωνη απο του θρονου εξηλθεν λεγουσα αινειτε τον [θεον]{.greek-abbr} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και [η]{.unclear}κουσα ως φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων λεγ[ον]{.unclear}τες α[λ]{.unclear}λ[η]{.unclear}λουια οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημω]{.unclear}ν ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και αγαλλιωμεθα και δωμεν την δοξαν [αυτω]{.greek-omitted} [αυτου]{.greek-added} οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη [αυτη]{.greek-omitted} [αυτηι]{.greek-added} ινα περιβαληται βυσσινον λαμπρον και καθαρον το γαρ βυσσινον τα δικαιωματα των [αγιω]{.greek-supplied}ν εστιν[19:8]{.aside}

και λεγει μοι γραψον μακαρ[ιοι]{.unclear} οι εις το δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι [οι]{.greek-omitted} [λογοι]{.greek-omitted} [αληθινοι]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισιν]{.greek-omitted}[19:9]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [δειπνον]{.greek-omitted} [του]{.greek-omitted} [γαμου]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [κεκλημενοι]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [ουτοι]{.greek-omitted} οι λογοι αληθινοι του [θεου]{.greek-abbr} εισιν[19:9 | instance no. 2]{.aside}

και [επεσα]{.greek-omitted} [επεσον]{.greek-added} εμπροσθεν των ποδων αυτου προσκυνησαι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} προσκυνησον η γαρ μαρτυρια του [ιησου]{.greek-abbr} εστιν το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον καλουμενος πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου [ως]{.greek-added} φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων ονοματα γεγραμμενα και ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον βεβαμμενον [εν]{.greek-added} αιματι και καλειται το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα τα εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ηκολουθει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} επι ιπποις λευκοις [ενδεδυ]{.greek-added} [ενδεδυμενοι]{.greek-omitted} [βυσσινον]{.greek-omitted} [λευκον]{.greek-omitted} [καθαρον]{.greek-omitted}[19:14]{.aside}

[μενοι]{.greek-added} [και]{.greek-omitted} [τα]{.greek-omitted} [στρατευματα]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [ηκολουθει]{.greek-omitted} [αυτω]{.greek-omitted} [επι]{.greek-omitted} [ιπποις]{.greek-omitted} [λευκοις]{.greek-omitted} [ενδεδυμενοι]{.greek-omitted} βυσσινον λευκον καθαρον[19:14 | instance no. 2]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} [παταξη]{.greek-omitted} [παταξηι]{.greek-added} τα εθνη και αυτος ποιμανει αυτους εν [ραβδω]{.greek-omitted} [ραβδωι]{.greek-added} [σιδηρα]{.greek-omitted} [σιδηραι]{.greek-added} και αυτος πατει την ληνον του οινου του θυμου της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον [ενα]{.greek-added} [αλλον]{.greek-added} αγγελον εστωτα εν [τω]{.greek-omitted} [τωι]{.greek-added} [ηλιω]{.greek-omitted} [[η]{.unclear}λιωι]{.greek-added} και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι δευτε συναχθητε εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον [το]{.greek-omitted} [τον]{.greek-added} [μεγα]{.greek-omitted} [μεγαν]{.greek-added} του [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων και μικρων [τε]{.greek-omitted} και μεγαλων[19:18]{.aside}

και [ειδον]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [στρατευματα]{.greek-omitted} [αυτων]{.greek-omitted} [συνηγμενα]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [ιππου]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [στρατευματος]{.greek-omitted} [αυτου]{.greek-omitted}[19:19]{.aside}

[και]{.greek-omitted} ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19 | instance no. 2]{.aside}

και επιασθη το θηριον και ο μετ αυτου ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας [τη]{.greek-omitted} [τηι]{.greek-added} εικονι αυτου ζωντες εβληθησαν οι δυο εις την λιμνην του πυρος την καιομενην εν [τωι]{.greek-added} [θειω]{.greek-omitted} [θειωι]{.greek-added}[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν [τη]{.greek-omitted} [τηι]{.greek-added} [ρομφαια]{.greek-omitted} [ρομφαιαι]{.greek-added} του καθημενου επι του ιππου [τη]{.greek-omitted} [τηι]{.greek-added} [εξελθουση]{.greek-omitted} [εξελθουσηι]{.greek-added} εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την κλειν της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντ[α]{.unclear} [τον]{.greek-omitted} [οφιν]{.greek-omitted} [τον]{.greek-omitted} [αρχαιον]{.greek-omitted} [ος]{.greek-omitted} [εστιν]{.greek-omitted} [διαβολος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [ο]{.greek-omitted} [πλανων]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} [ολην]{.greek-omitted} [και]{.greek-omitted} [εδησεν]{.greek-omitted} [αυτον]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted}[20:2]{.aside}

[και]{.greek-omitted} [εκρατησεν]{.greek-omitted} [τον]{.greek-omitted} [δρακοντα]{.greek-omitted} τον οφιν τον αρχαιον ος εστιν διαβολος και ο σατανας ο πλανων την οικουμενην ολην και εδησεν αυτον χιλια ετη[20:2 | instance no. 2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλεισε]{.greek-added} και εσφραγισεν επανω αυτου ινα μη [πλανα]{.greek-omitted} [πλανα[ι]{.unclear}]{.greek-added} ετι τα εθνη αχρι [τελεσθη]{.greek-omitted} [τελεσθηι]{.greek-added} τα χιλια ετη και μετα ταυτα δει αυτον λυθηναι μικρον χρονον[20:3]{.aside}

και ειδον θρονους και εκαθισαν επ αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν [το]{.greek-omitted} [θηριον]{.greek-omitted} [τωι]{.greek-added} [θηριωι]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} την εικονα αυτου και ουκ ελαβον το χαραγμα επι το μετωπον και επι την χειρα αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} [τα]{.greek-omitted} χιλια ετη[20:4]{.aside}

και οι λοιποι των [νεκρων]{.greek-omitted} [ανθρωπον]{.greek-added} [[ανθρωπων]{.corr}]{.greek-added} ουκ εζησαν αχρι [τελεσθη]{.greek-omitted} [τελεσθηι]{.greek-added} τα χιλια ετη αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν [τη]{.greek-omitted} [τηι]{.greek-added} αναστασει [τη]{.greek-omitted} [τηι]{.greek-added} [πρωτη]{.greek-omitted} [πρωτηι]{.greek-added} επι τουτων ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου χιλια ετη[20:6]{.aside}

και οταν [τελεσθη]{.greek-omitted} [τελεσθηι]{.greek-added} τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης τον γωγ και τον μαγωγ [και]{.greek-added} συναγαγειν αυτους εις [τον]{.greek-omitted} πολεμον ων ο αριθμος ως η αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και εκυκλωσαν την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ εκ του ουρανου απο του [θεου]{.greek-abbr} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και [του]{.greek-added} θειου οπου και το θηριον [και]{.greek-omitted} [ο]{.greek-omitted} [ψευδοπροφητης]{.greek-omitted} [και]{.greek-omitted} [βασανισθησονται]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [νυκτος]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[20:10]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [διαβολος]{.greek-omitted} [ο]{.greek-omitted} [πλανων]{.greek-omitted} [αυτους]{.greek-omitted} [εβληθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [λιμνην]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [θειου]{.greek-omitted} [οπου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10 | instance no. 2]{.aside}

και ειδον θρονον [λευκον]{.greek-added} μεγαν [λευκον]{.greek-omitted} και τον καθημενον επ αυτον ου απο προσωπου εφυγεν η γη και ο ουρανος και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον τους νεκρους [εστωτας]{.greek-added} [τους]{.greek-added} [μικρους]{.greek-added} [και]{.greek-added} τους μεγαλους [και]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} [εστωτας]{.greek-omitted} ενωπιον του θρονου και βιβλια [ηνεωχθησαν]{.greek-omitted} [ηνοιχθησαν]{.greek-added} και αλλο βιβλιον ηνεωχθη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} και ο θανατος και ο [αδης]{.greek-omitted} [αιδης]{.greek-added} εδωκαν τους νεκρους τους εν αυτοις και εκριθησαν εκαστος κατα τα εργα [αυτων]{.greek-omitted} [αυτου]{.greek-added}[20:13]{.aside}

και ο θανατος και ο [αδης]{.greek-omitted} [αιδης]{.greek-added} εβληθησαν εις την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ει τις [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [γεγραμμενος]{.greek-omitted} [εβληθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [λιμνην]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted}[20:15]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} ουχ ευρεθη εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15 | instance no. 2]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη απηλθον και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} ητοιμασμενην ως νυμφην κεκοσμημενην [τω]{.greek-omitted} [τωι]{.greek-added} ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} εσται μετ αυτων[21:3]{.aside}

και εξαλειψει παν δακρυον απο των οφθαλμων αυτων και ο θανατος ουκ εσται ετι ουτε πενθος ουτε κραυγη ουτε πονος ουκ εσται ετι οτι τα πρωτα [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added}[21:4]{.aside}

και ειπεν ο καθημενος επι [τω]{.greek-omitted} [τω[ι]{.unclear}]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} ιδου παντα καινα ποιω [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [γραψον]{.greek-omitted} [οτι]{.greek-omitted} [ουτοι]{.greek-omitted} [οι]{.greek-omitted} [λογοι]{.greek-omitted} [αληθινοι]{.greek-omitted} [και]{.greek-omitted} [πιστοι]{.greek-omitted} [εισιν]{.greek-omitted}[21:5]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [ο]{.greek-omitted} [καθημενος]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [θρονω]{.greek-omitted} [ιδου]{.greek-omitted} [παντα]{.greek-omitted} [καινα]{.greek-omitted} [ποιω]{.greek-omitted} και λεγει μοι γραψον οτι ουτοι οι λογοι [αλη]{.greek-supplied}θινοι και πιστοι [εισιν]{.greek-omitted} [εισι]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added}[21:5 | instance no. 2]{.aside}

και ειπεν μοι γε[γ]{.unclear}ονα [εγω]{.greek-added} το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και [τ]{.greek-supplied}ο [ω]{.greek-abbr} η αρχη και το τελος εγω τω διψωντι δωσω [αυτωι]{.greek-added} εκ της πηγης του υδατος της ζωης δωρεαν[21:6]{.aside}

ο νικων [κληρονομησει]{.greek-omitted} [δωσω]{.greek-added} [αυτωι]{.greek-added} ταυτα και εσομαι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [θεος]{.greek-abbr} και αυτος εσται μοι υιος[21:7]{.aside}

τοις δε δειλοις και απιστοις και αμαρτωλοις και εβδε[λυ]{.unclear}γμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} και πορνοις και φαρμακοις και ειδωλολατραις [και]{.greek-supplied} [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων [εν]{.greek-supplied} [[τηι]{.greek-supplied}]{.greek-added} [λιμνηι]{.greek-added} τη [λιμνη]{.greek-omitted} [τη]{.greek-omitted} [καιομενη]{.greek-omitted} [καιομενηι]{.greek-added} πυρι και θει[ω]{.greek-supplied} [ο]{.greek-supplied} [εστι]{.unclear}ν ο θανατος ο δευτερος[21:8]{.aside}

και ηλ[θεν]{.greek-supplied} [ει]{.greek-supplied}ς εκ των ε[πτα]{.unclear} αγγελων των εχοντων [τας]{.unclear} επτα φιαλας γεμουσας [των]{.greek-omitted} επτα πλη[γων]{.greek-supplied} [τω]{.greek-supplied}ν εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου [λεγων]{.greek-supplied} δευρο δειξω σοι την [[νυ]{.unclear}μφην]{.greek-added} [[τη]{.unclear}ν]{.greek-added} γυναικα [την]{.greek-omitted} [νυμφην]{.greek-omitted} του αρνιου[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [επ]{.greek-omitted} [ορος]{.greek-omitted} [μεγα]{.greek-omitted} [και]{.greek-omitted} [υψηλον]{.greek-omitted} [και]{.greek-omitted} [εδειξεν]{.greek-omitted} [μοι]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [μεγαλην]{.greek-omitted} [την]{.greek-omitted} [αγιαν]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [καταβαινουσαν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[21:10]{.aside}

[και]{.greek-omitted} [απηνεγκεν]{.greek-omitted} [με]{.greek-omitted} εν [πνευματι]{.greek-abbr} επ ορος μεγα και υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι την πολιν την μεγαλην [την]{.greek-omitted} [και]{.greek-added} αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν [απο]{.greek-added} [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} εκ του [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr}[21:10 | instance no. 2]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης [ομοος]{.greek-added} [ομοιος]{.corr} [λιθω]{.greek-omitted} [λιθωι]{.greek-added} [τιμιωτατω]{.greek-omitted} [τιμιωτατωι]{.greek-added} ως [λιθω]{.greek-omitted} [λιθωι]{.greek-added} ιασπιδι κρυσταλλιζοντι[21:11]{.aside}

εχουσα τειχος μεγα και υψηλον εχουσα πυλωνας δωδεκα και επι τ[οις]{.greek-supplied} πυλωσιν αγγελους δωδεκα και ονοματα επιγεγραμμενα α εστιν ονοματα τ[ων]{.greek-supplied} δωδεκα φυλων [των]{.greek-omitted} υιων [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο ανατολων πυλωνες τρεις και απο βορρα πυλωνες τρεις και απο νοτου πυλωνες τρεις και απο δυσμων πυλωνες τρεις[21:13]{.aside}

και το τειχος της πολεως εχον θεμελιους δωδεκα και ε[π]{.greek-supplied} [αυ]{.greek-supplied}των δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ [εμου]{.greek-supplied} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} μετρον καλαμον χρυσουν ινα [μ[ε]{.greek-supplied}]{.greek-added} [μετρηση]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πυλωνας]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τειχος]{.greek-omitted} [αυτης]{.greek-omitted}[21:15]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [λαλων]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [ειχεν]{.greek-omitted} [μετρον]{.greek-omitted} [καλαμον]{.greek-omitted} [χρυσουν]{.greek-omitted} [ινα]{.greek-omitted} [μετρηση]{.greek-omitted} [τρησηι]{.greek-added} την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15 | instance no. 2]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν [εν]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [καλαμω]{.greek-omitted} [καλαμωι]{.greek-added} επι σταδιους [δωδεκα]{.greek-omitted} [δεκαδυο]{.greek-added} χιλιαδων δωδεκα το μηκος και το πλατος και το υψος αυτης ισα εστιν[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} το τειχος αυτης εκατον τεσσαρακοντα τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον ομοιον [υελω]{.greek-omitted} [υαλωι]{.greek-added} [καθαρω]{.greek-omitted} [καθαρωι]{.greek-added}[21:18]{.aside}

οι θεμελιοι του τειχους της πολεως παντι λιθω [τιμιω]{.greek-omitted} [τιμιωι]{.greek-added} κεκοσμημενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος [σαρδονυξ]{.greek-omitted} [σαρδωνυξ]{.greek-added} ο εκτος σαρδιον ο εβδομος χρυσολιθος ο ογδοος βηρυλλος ο ενατος τοπαζιον [ο]{.greek-omitted} [δεκατος]{.greek-omitted} [χρυσοπρασος]{.greek-omitted} [ο]{.greek-omitted} [ενδεκατος]{.greek-omitted} [υακινθος]{.greek-omitted} [ο]{.greek-omitted} [δωδεκατος]{.greek-omitted} [αμεθυσος]{.greek-omitted}[21:20]{.aside}

[ο]{.greek-omitted} [πεμπτος]{.greek-omitted} [σαρδονυξ]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [σαρδιον]{.greek-omitted} [ο]{.greek-omitted} [εβδομος]{.greek-omitted} [χρυσολιθος]{.greek-omitted} [ο]{.greek-omitted} [ογδοος]{.greek-omitted} [βηρυλλος]{.greek-omitted} [ο]{.greek-omitted} [ενατος]{.greek-omitted} [τοπαζιον]{.greek-omitted} ο δεκατος χρυ[σο]{.unclear}πρασος ο ενδεκατος υακινθος ο δωδεκατος αμεθυσος[21:20 | instance no. 2]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται ανα εις εκαστος των πυλωνων ην εξ ενος μαργαριτου και η πλατεια της πολεως χρυσιον καθαρον ως [υελος]{.greek-omitted} [υαλος]{.greek-added} διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν [αυτη]{.greek-omitted} [αυ[τηι]{.greek-supplied}]{.greek-added} η γαρ δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην [και]{.greek-supplied} ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατη[σου]{.unclear}σ[ι]{.unclear}]{.greek-added} τα εθνη δια του φωτος αυτης κα[ι]{.unclear} οι βασιλεις της γης [φερουσιν]{.greek-omitted} [φερουσι]{.greek-added} [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν και [την]{.greek-added} τιμην των εθνων εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην[21:26]{.aside}

και ου μη [εισελθη]{.greek-omitted} [εισελθηι]{.greek-added} [εις]{.greek-omitted} [αυτην]{.greek-omitted} [παν]{.greek-omitted} [κοινον]{.greek-omitted} [και]{.greek-omitted} [ποιουν]{.greek-omitted} [βδελυγμα]{.greek-omitted} [και]{.greek-omitted} [ψευδος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [οι]{.greek-omitted} [γεγραμμενοι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted}[21:27]{.aside}

[και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [εισελθη]{.greek-omitted} εις αυτην παν κοινον και ποιουν βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} της ζωης του αρνιου[21:27 | instance no. 2]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον καθαρον υδατος ζωης λαμπρον [ως]{.greek-omitted} [ωσει]{.greek-added} κρυσταλλον εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και εκειθεν ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα εκαστο[ν]{.unclear} [αποδιδους]{.greek-omitted} [αποδιδον]{.greek-added} τον καρπον αυτου και τα φυλλα του ξυλου [καταγγελλεται]{.greek-added} εις θεραπειαν των εθνων[22:2]{.aside}

και παν καταθεμ[α]{.unclear} ουκ ε[σται]{.greek-supplied} [ετι]{.greek-omitted} [εκει]{.greek-added} και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} εσται και οι δουλοι αυτου λατρ[ευσ]{.unclear}ουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των μετωπων αυτων[22:4]{.aside}

και νυξ ουκ εσται εκει και χρειαν ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} λυχνου και φωτος [η]{.unclear}λιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [φωτιει]{.greek-omitted} [φωτιζει]{.greek-added} αυτους και [βασιλευσουσιν]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[22:5]{.aside}

[και]{.greek-omitted} [νυξ]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [εκει]{.greek-omitted} [και]{.greek-omitted} [χρειαν]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [λυχνου]{.greek-omitted} [και]{.greek-omitted} [φωτος]{.greek-omitted} [ηλιου]{.greek-omitted} [οτι]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [φωτιει]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} βασιλευσουσιν εις τους αιωνας των αιωνων[22:5 | instance no. 2]{.aside}

και [λεγει]{.greek-omitted} [ειπεν]{.greek-added} μοι ουτοι οι λογοι πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-abbr} των [αγιων]{.greek-added} προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

[και]{.greek-omitted} ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

[καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} ιωαννης ο [βλεπων]{.greek-added} [και]{.greek-added} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} ταυτα και οτε ηκουσα και εβλεψα επεσον προσκυνησαι εμπροσθεν των ποδων του αγγελου του δεικνυοντος μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι [εγω]{.greek-added} και των αδελφων σου των προφητων και των τηρουντων τους λογους του βιβλιου τουτου [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} προσκυνησον[22:9]{.aside}

και λεγει μοι μη [σφραγισης]{.greek-omitted} [σφραγισηις]{.greek-added} τους λογους της προφητειας του βιβλιου τουτου ο καιρος γαρ εγγυς εστιν[22:10]{.aside}

[και]{.greek-added} ο αδικων αδικησατω [ετι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ρυπαρος]{.greek-omitted} [ρυπαρευθητω]{.greek-omitted} ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

ιδου [ερ]{.greek-added} [ερχομαι]{.greek-omitted} [ταχυ]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [μισθος]{.greek-omitted} [μου]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [αποδουναι]{.greek-omitted} [εκαστω]{.greek-omitted} [ως]{.greek-omitted} [το]{.greek-omitted} [εργον]{.greek-omitted} [εσται]{.greek-omitted} [αυτου]{.greek-omitted}[22:12]{.aside}

[ιδου]{.greek-omitted} [ερχομαι]{.greek-omitted} [χομαι]{.greek-added} ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον [αυτου]{.greek-added} εσται [αυτου]{.greek-omitted}[22:12 | instance no. 2]{.aside}

εγω το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} ο πρωτος και ο εσχατος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι φονεις και οι ειδωλολατραι και πας [ο]{.greek-added} [ποιων]{.greek-added} [και]{.greek-added} φιλων [και]{.greek-omitted} [ποιων]{.greek-omitted} ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα επι ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} [και]{.greek-added} ο αστηρ ο [πρωινος]{.greek-added} [ο]{.greek-added} λαμπρος [ο]{.greek-omitted} [πρωινος]{.greek-omitted}[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν ερχου και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

[μαρτυρω]{.greek-omitted} [μαρτυρομαι]{.greek-added} εγω παντι [τω]{.greek-omitted} [τωι]{.greek-added} ακουοντι τους λογους της προφητειας του βιβλιου τουτου εαν τις [επιθη]{.greek-omitted} [επιθηι]{.greek-added} επ αυτα [επιθησαι]{.greek-omitted} [επιθησει]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [τας]{.greek-omitted} [πληγας]{.greek-omitted} [τας]{.greek-omitted} [γεγραμμενας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [τουτω]{.greek-omitted}[22:18]{.aside}

[μαρτυρω]{.greek-omitted} [εγω]{.greek-omitted} [παντι]{.greek-omitted} [τω]{.greek-omitted} [ακουοντι]{.greek-omitted} [τους]{.greek-omitted} [λογους]{.greek-omitted} [της]{.greek-omitted} [προφητειας]{.greek-omitted} [του]{.greek-omitted} [βιβλιου]{.greek-omitted} [τουτου]{.greek-omitted} [εαν]{.greek-omitted} [τις]{.greek-omitted} [επιθη]{.greek-omitted} [επιθησει]{.greek-added} επ [αυτον]{.greek-added} [αυτα]{.greek-omitted} [επιθησαι]{.greek-omitted} ο [θεος]{.greek-abbr} [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας [επτα]{.greek-added} πληγας [τας]{.greek-supplied} γεγραμμενας εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} [τουτω]{.greek-omitted} [του[τ]{.unclear}ωι]{.greek-added}[22:18 | instance no. 2]{.aside}

και εα[ν]{.unclear} τις αφελη απο των λογων του βιβλιου της προφητειας ταυτης [αφελοι]{.greek-omitted} [αφελει]{.greek-added} ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της [α]{.unclear}γιας των γεγραμμενων εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} [τουτω]{.greek-omitted} [τουτωι]{.greek-added}[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην [ναι]{.greek-omitted} ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων αμην[22:21]{.aside}

