---
title: "Collation of Byz^RP^ vs 30279 (279)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 279 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30279).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 279                                   	| λογος                              	|
| 279 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 279 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 279               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 279                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 279 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 279                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

βιβλος γενεσεως [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου [δαυιδ]{.greek-abbr} υιου αβρααμ[1:1]{.aside}

αβρααμ εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον ισαακ ισαακ δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον ιακωβ ιακωβ δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον ιουδαν και τους αδελφους αυτου[1:2]{.aside}

ιουδας δε εγεννησεν τον φαρες και τον ζαρα εκ της θαμαρ φαρες δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον εσρωμ εσρωμ δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον αραμ[1:3]{.aside}

αραμ δε εγεννησεν τον αμιναδαβ αμιναδαβ δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον [αασσων]{.greek-added} [ναασσων]{.corr} ναασσων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλμων[1:4]{.aside}

σαλμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [βοοζ]{.greek-omitted} [βοος]{.greek-added} [εκ]{.greek-omitted} [της]{.greek-omitted} [ραχαβ]{.greek-omitted} [βοοζ]{.greek-omitted} [βοος]{.greek-added} δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον [ωβηδ]{.greek-omitted} [ιωβηδ]{.greek-added} [εκ]{.greek-omitted} [της]{.greek-omitted} [ρουθ]{.greek-omitted} [ωβηδ]{.greek-omitted} [ιωβηδ]{.greek-added} δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον ιεσσαι[1:5]{.aside}

ιεσσαι δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον [δαυιδ]{.greek-abbr} τον βασιλεα [δαυιδ]{.greek-abbr} δε ο βασιλευς εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον [σολομωνα]{.greek-omitted} [σολομων]{.greek-added} εκ της του ουριου[1:6]{.aside}

σολομων δε εγεννησεν [[εγεννησε]{.corr}]{.greek-added} τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ασα[1:7]{.aside}

ασα δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσαφατ ιωσαφατ δε [εγεννησεν]{.greek-omitted} [γεννησε]{.greek-added} τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεν[νη]{.unclear}σε]{.greek-added} τον [οζειαν]{.greek-added} [οζιαν]{.corr}[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωαθαμ ιωαθαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχαζ αχαζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εζεκιαν[1:9]{.aside}

εζεκιας δε [εγενησε]{.greek-added} [εγεννησεν]{.greek-omitted} [[εγεννησε]{.corr}]{.greek-added} τον μανασση μανασσης δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [αμων]{.greek-omitted} [αμως]{.greek-added} [αμων]{.greek-omitted} [αμως]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεχονιαν και τους αδελφους αυτου επι της μετοικεσιας βαβυλωνος[1:11]{.aside}

μετα δε την μετοικεσιαν βαβυλωνος ιεχονιας [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλαθιηλ σαλαθιηλ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [ζοροβαβελ]{.greek-omitted}[1:12]{.aside}

[ζοροβαβελ]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} τον αβιουδ αβιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιακειμ ελιακειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχειμ αχειμ δε [εγενησεν]{.greek-added} [εγεννησεν]{.corr} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελεαζαρ ελεαζαρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

πασαι ουν αι γενεαι απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεαι δεκατεσσαρες και απο [δαυιδ]{.greek-abbr} εως της μετοικεσιας βαβυλωνος γενεαι δεκατεσσαρες και απο της μετοικεσιας βαβυλωνος εως του [χριστου]{.greek-abbr} γενεαι δεκατεσσαρες[1:17]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην μνηστευθεισης γαρ της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν η [συνελθεν]{.greek-added} [συνελθειν]{.corr} αυτους [ηυρεθ]{.greek-added} [ευρεθη]{.greek-omitted} [[ηυρεθη]{.corr}]{.greek-added} εν [γαστρι]{.greek-omitted} [γασρι]{.greek-added} εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ [δε]{.greek-omitted} ο ανηρ αυτης δικαιος ων και μη θελων αυτην παραδειγματισαι εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} [φαινεται]{.greek-added} κατ οναρ [εφανη]{.greek-omitted} [αυτω]{.greek-omitted} [τω]{.greek-added} [ιωσηφ]{.greek-added} λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη φοβηθης παραλαβειν μαριαμ την γυναικα σου το γαρ εν αυτη γεννηθεν [εστιν]{.greek-added} εκ [πνευματος]{.greek-abbr} [εστιν]{.greek-omitted} αγιου[1:20]{.aside}

τεξεται δε υιον και [καλεσεις]{.greek-omitted} [καλεσης]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο [του]{.greek-omitted} [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται υιον και [καλεσουσιν]{.greek-omitted} [καλεσουσι]{.greek-added} το ονομα αυτου εμμανουηλ ο εστιν [μεθ[―]{.gap}μηνευομενον]{.greek-added} [μεθερμηνευομενον]{.corr} μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε [ο]{.greek-omitted} ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και παρελαβεν την γυναικα αυτου[1:24]{.aside}

και ουκ [εγινωσκεν]{.greek-omitted} [εγνω]{.greek-added} αυτην εως ου ετεκεν [[ετεκε]{.corr}]{.greek-added} τον υιον [αυτης]{.greek-omitted} [αυτου]{.greek-added} τον πρωτοτοκον και εκαλεσεν [[εκαλεσε]{.corr}]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

του δε [ιησου]{.greek-abbr} γεννηθεντος εν βηθλεεμ της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις [ιεροσολυμα]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added}[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι αυτω[2:2]{.aside}

ακουσας δε [ηρωδης]{.greek-omitted} ο βασιλευς [ηρωδης]{.greek-added} εταραχθη και πασα [η]{.greek-added} ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και γραμματεις του λαου επυνθανετο παρ αυτων που ο [χριστος]{.greek-abbr} γενναται[2:4]{.aside}

οι δε ειπον αυτω εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ουδαμως ελαχιστη ει εν τοις ηγεμοσιν ιουδα εκ σου γαρ εξελευσεται ηγουμενος οστις [ποιμανει]{.greek-omitted} [ποιμανι]{.greek-added} [[ποιμανη]{.corr}]{.greek-added} τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πορευθεντες [εξετασατε]{.greek-added} ακριβως [εξετασατε]{.greek-omitted} περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο [αστ[ρ]{.unclear}]{.greek-added} [αστηρ]{.corr} ον ειδον εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα [εχαρησαν]{.greek-omitted} [εχαρισαν]{.greek-added} χαραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες εις την οικιαν ειδον το παιδιον μετα [[της]{.corr}]{.greek-added} μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσεκυνησαν αυτω και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ [[καθ]{.corr}]{.greek-added} οναρ μη ανακαμψαι προς ηρωδην δι [αλλης]{.greek-omitted} [αλης]{.greek-added} οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων [δε]{.greek-omitted} [αυτων]{.greek-omitted} [των]{.greek-added} [μαγων]{.greek-added} ιδου αγγελος [κυριου]{.greek-abbr} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις [αιγυπτον]{.greek-omitted} [αιγυπτων]{.greek-added} και [ισθι]{.greek-omitted} [ισθη]{.greek-added} εκει εως αν ειπω σοι μελλει [γαρ]{.greek-omitted} [ο]{.greek-added} ηρωδης ζητειν το παιδιον του απολεσαι [αυτο]{.greek-omitted} [αυτω]{.greek-added}[2:13]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου [ινα]{.greek-omitted} [οπως]{.greek-added} πληρωθη το ρηθεν υπο [του]{.greek-omitted} [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον υιον μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη λιαν και αποστειλας [ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} παντας τους παιδας τους εν βηθλεεμ και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις οριοις αυτης απο διετους και [κατωτερω]{.greek-omitted} [κατοτερους]{.greek-added} κατα τον χρονον ον [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρα των μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν [υπο]{.greek-omitted} [δια]{.greek-added} ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη [θρηνος]{.greek-omitted} [και]{.greek-omitted} κλαυθμος και οδυρμος πολυς ραχηλ [[ραχι[η]{.unclear}λ]{.corr}]{.greek-added} κλαιουσα τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρακληθηναι οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added}[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} [φαινεται]{.greek-added} κατ οναρ [φαινεται]{.greek-omitted} τω ιωσηφ [εν]{.greek-omitted} [αιγυπτω]{.greek-omitted}[2:19]{.aside}

λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} [τεθνηκασιν]{.greek-omitted} [τεθνηκασι]{.greek-added} γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου και [ηλθεν]{.greek-omitted} [εισηλθον]{.greek-added} εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι [ο]{.greek-added} αρχελαος βασιλευει [επι]{.greek-omitted} της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρ[η]{.unclear}σεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων [κατωκησεν]{.greek-omitted} [κατωκισεν]{.greek-added} ει[ς]{.unclear} πολιν λεγομενην ναζαρετ οπως πληρωθη το ρηθεν δια των προφητων οτι ναζωραιος κληθησεται[2:23]{.aside}

### Chapter 3

εν [δε]{.greek-omitted} ταις ημεραις εκειναις παραγινεται ιωαννης ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

[και]{.greek-omitted} λεγων μετανοειτε ηγγικεν γαρ η βασιλεια των ουρανων[3:2]{.aside}

ουτος γαρ εστιν ο ρηθεις υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε [ο]{.greek-omitted} ιωαννης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον [πασα]{.greek-added} ιεροσολυμα και πασα [η]{.greek-omitted} ιουδαια και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο εν τω ιορδανη [ποταμω]{.greek-added} υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισμα [αυτου]{.greek-omitted} ειπεν αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν εαυτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις [το]{.greek-added} πυρ βαλλεται[3:10]{.aside}

εγω μεν βαπτιζω υμας εν υδατι [και]{.greek-added} εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα [υποδηματα]{.greek-omitted} [υποδυματα]{.greek-added} βαστασαι αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον [αυτου]{.greek-omitted} εις την αποθηκην [αυτου]{.greek-added} το δε [αχυρον]{.greek-omitted} [αχαυρον]{.greek-added} κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον ιωαννην του [βαπτισθηναι]{.greek-omitted} [βαπισθηναι]{.greek-added} υπ αυτου[3:13]{.aside}

ο δε ιωαννης [διεκωλυεν]{.greek-omitted} [διεκωλνει]{.greek-added} αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ [ερχη]{.greek-omitted} [ερχει]{.greek-added} προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν [προς]{.greek-omitted} [αυτον]{.greek-omitted} [αυτων]{.greek-added} αφες αρτι [ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ πρεπον [εστιν]{.greek-omitted} [ημιν]{.greek-added} ημιν πληρωσαι πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και βαπτισθεις ο [ιησους]{.greek-abbr} ανεβη ευθυς απο του υδατος και ιδου ανεωχθησαν αυτω οι [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} καταβαινον ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο υιος μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[3:17]{.aside}

### Chapter 4

τοτε [ανηχθη]{.greek-added} ο [ιησους]{.greek-abbr} [ανηχθη]{.greek-omitted} εις την ερημον υπο του [πνευματος]{.greek-abbr} πειρασθηναι υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας τεσσαρακοντα [και]{.greek-omitted} [νυκτας]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} υστερον επεινασεν[4:2]{.aside}

και προσελθων [αυτω]{.greek-omitted} ο πειραζων ειπεν [αυτω]{.greek-added} ει υιος ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι γενωνται[4:3]{.aside}

ο δε αποκριθεις ειπεν γεγραπται ουκ επ αρτω μονω ζησεται [ανθρωπος]{.greek-abbr} αλλ επι παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει υιος ει του [θεου]{.greek-abbr} βαλε σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} παλιν γεγραπται ουκ [εκπειρασεις]{.greek-omitted} [εκπειρασης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν παραλαμβανει αυτον ο διαβολος εις ορος υψηλον λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων [προσκυνησης]{.greek-omitted} [προσκυνησεις]{.greek-added} μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται [γαρ]{.greek-omitted} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω μονω [λατρευσεις]{.greek-omitted} [λατρευσης]{.greek-added}[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} οτι ιωαννης [παρεδοθη]{.greek-omitted} [παρεδωθη]{.greek-added} ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την ναζαρετ ελθων [κατωκησεν]{.greek-omitted} εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και νεφθαλειμ[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη νεφθαλειμ οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} [ειδε]{.greek-added} φως μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} δυο αδελφους σιμωνα τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω υμας αλιεις [ανθρωπων]{.greek-abbr}[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν ειδεν αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας τα δικτυα αυτων και εκαλεσεν αυτους[4:21]{.aside}

οι δε ευθεως αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν [ολην]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted} ο [ιησους]{.greek-abbr} [εν]{.greek-added} [ολη]{.greek-added} [τη]{.greek-added} [γαλιλαια]{.greek-added} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και [απηλθεν]{.greek-omitted} [εξηλθεν]{.greek-added} η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και βασανοις συνεχομενους [και]{.greek-omitted} δαιμονιζομενους και σεληνιαζομενους και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της [δεκαπολεως]{.greek-added} [και]{.greek-added} γαλιλαιας [και]{.greek-omitted} [δεκαπολεως]{.greek-omitted} και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων [[ειδων]{.corr}]{.greek-added} δε τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον [αυτω]{.greek-omitted} οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους λεγων[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι [παρακληθησονται]{.greek-omitted} [παρακλιθησονται]{.greek-added} [[παρακλoιθησονται]{.corr}]{.greek-added}[5:4]{.aside}

μακαριοι οι πραεις [ο]{.greek-added} [οτι]{.corr} αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομησουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι [πεινωντες]{.greek-omitted} [π[―]{.gap}ντες]{.greek-added} [[πηνοντες]{.corr}]{.greek-added} και διψωντες [την]{.greek-omitted} [τυ]{.greek-added} [δικαιοσυνην]{.greek-omitted} [δηκαιοσυν]{.greek-added} οτι αυτοι χορτασθησονται[5:6]{.aside}

μακαριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι [ειρηνοποιοι]{.greek-omitted} [ειρινοποιοι]{.greek-added} οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι [εστε]{.greek-omitted} [εσται]{.greek-added} οταν [ονειδισωσιν]{.greek-omitted} [ονειδισωσην]{.greek-added} υμας και [διωξωσιν]{.greek-omitted} [διωξωσι]{.greek-added} και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ [υμων]{.greek-omitted} [υμον]{.greek-added} ψευδομενοι ενεκεν εμου[5:11]{.aside}

[χαιρετε]{.greek-omitted} [χαιρεται]{.greek-added} και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις [ουρανοις]{.greek-abbr} ουτως γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το αλας της γης εαν δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν [ισχυει]{.greek-omitted} [ισχυι]{.greek-added} ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και τιθεασιν αυτον υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων εμπροσθεν των [ανθρωπων]{.greek-abbr} οπως ιδωσιν υμων τα [καλα]{.greek-omitted} [καλλα]{.greek-added} εργα και [δοξασωσιν]{.greek-omitted} [δοξασωσι]{.greek-added} τον [πατερα]{.greek-abbr} υμων [[ημων]{.corr}]{.greek-added} τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον [η]{.greek-omitted} [και]{.greek-added} τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η μια [κεραια]{.greek-omitted} [καιρεα]{.greek-added} ου μη παρελθη απο του νομου εως [αν]{.greek-omitted} παντα γενηται[5:18]{.aside}

ος [εαν]{.greek-omitted} [αν]{.greek-added} ουν λυση μιαν των εντολων τουτων των ελαχιστων και [διδαξει]{.greek-added} [διδαξη]{.corr} ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} και [διδαξη]{.greek-omitted} [διδαξει]{.greek-added} ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη [περισσευση]{.greek-omitted} [περισσευσει]{.greek-added} [υμων]{.greek-added} η δικαιοσυνη [υμων]{.greek-omitted} πλειον των [γραμματ[ει]{.unclear}ων]{.greek-added} [γραμματεων]{.corr} και [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν [φονευση]{.greek-omitted} [φονευσει]{.greek-added} ενοχος εσται τη κρισει[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν [ειπη]{.greek-omitted} [ειπει]{.greek-added} τω αδελφω αυτου ρακα ενοχος εσται τω συνεδριω ος δ αν ειπη μωρε ενοχος εσται εις την γεενναν του πυρος[5:22]{.aside}

εαν ουν [προσφερης]{.greek-omitted} [προσφερεις]{.greek-added} το δωρον σου επι το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

[ισθι]{.greek-omitted} [ισθη]{.greek-added} ευνοων τω αντιδικω σου ταχυ εως οτου ει [μετ]{.greek-added} [αυτου]{.greek-added} εν τη οδω [μετ]{.greek-omitted} [αυτου]{.greek-omitted} μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης [σε]{.greek-omitted} [παραδω]{.greek-omitted} τω υπηρετη και εις φυλακην [βληθησει]{.greek-added} [βληθηση]{.corr}[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως [αν]{.greek-omitted} [ου]{.greek-added} αποδως [και]{.greek-added} τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη ου [μοιχευσεις]{.greek-omitted} [μοιχευσης]{.greek-added}[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα προς το επιθυμησαι [αυτην]{.greek-omitted} ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιος σκανδαλιζει σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ [σκανδαλιζει]{.greek-omitted} [σκανδαλιζη]{.greek-added} σε εκκοψον [αυτη[ς]{.unclear}]{.greek-added} [αυτη[ν]{.unclear}]{.corr} και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απωληται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου [βληθη]{.greek-omitted} εις γεενναν [βληθη]{.greek-added}[5:30]{.aside}

[ηκουσατε]{.greek-added} [οτι]{.greek-added} ερρεθη [δε]{.greek-omitted} [οτι]{.greek-omitted} ος αν απολυση την γυναικα αυτου δοτω αυτη [βιβλιον]{.greek-added} [αποστασιον]{.greek-omitted} [αποστασιου]{.greek-added}[5:31]{.aside}

εγω δε λεγω υμιν οτι [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} [πας]{.greek-added} [ο]{.greek-added} [απολυων]{.greek-added} την γυναικα αυτου παρεκτος λογου πορνειας ποιει αυτην [μοιχασθαι]{.greek-omitted} [μ[ο]{.unclear}ιχευθηναι]{.greek-added} και ος [εαν]{.greek-omitted} [αν]{.greek-added} απολελυμενην [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ [επιορκησεις]{.greek-omitted} [επιορκισης]{.greek-added} [αποδωσεις]{.greek-omitted} [αποδωσης]{.greek-added} δε [τω]{.greek-omitted} [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη [ομοσαι]{.greek-omitted} [ωμοσαι]{.greek-added} ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος [εστιν]{.greek-omitted} [εσιν]{.greek-added} του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον [εστιν]{.greek-omitted} [εσιν]{.greek-added} των ποδων [αυτου]{.greek-omitted} [αυτω]{.greek-added} μητε εις ιεροσολυμα οτι πολις [εστιν]{.greek-omitted} [εστι]{.greek-added} του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου [ομοσης]{.greek-omitted} [ωμοσης]{.greek-added} οτι ου δυνασαι μιαν [τριχα]{.greek-omitted} [τριχαν]{.greek-added} λευκην [ποιησαι]{.greek-added} η μελαιναν [ποιησαι]{.greek-omitted}[5:36]{.aside}

εστω [δε]{.greek-omitted} ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου ε[σ]{.unclear}τιν[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη [αντιστηναι]{.greek-omitted} [αντισταθηναι]{.greek-added} τω πονηρω αλλ ο[σ]{.unclear}τις σε ραπισει [επι]{.greek-omitted} [εις]{.greek-added} την δεξιαν σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και [τω]{.greek-omitted} [το]{.greek-added} θελοντι σοι [[σε]{.corr}]{.greek-added} κριθηναι και [τον]{.greek-omitted} [χιτωνα]{.greek-omitted} [πυχιτωνα]{.greek-added} σου λαβειν αφες αυτω και το ιματιον [σου]{.greek-added}[5:40]{.aside}

και οστις [αγγαρευσει]{.greek-added} σε [αγγαρευσει]{.greek-omitted} μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω αιτουντι σε [δ[ο]{.unclear}]{.greek-added} [διδου]{.corr} και τον θελοντα απο σου [δανισασθαι]{.greek-added} [δανεισασθαι]{.corr} μη [αποστραφης]{.greek-omitted} [αποστραφεις]{.greek-added}[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και [μισησεις]{.greek-omitted} [μισησης]{.greek-added} τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων [ευλογειτε]{.greek-omitted} [τους]{.greek-omitted} [καταρωμενους]{.greek-omitted} [υμας]{.greek-omitted} [καλως]{.greek-omitted} [ποιειτε]{.greek-omitted} [τοις]{.greek-omitted} [μισουσιν]{.greek-omitted} [υμας]{.greek-omitted} και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} υπερ των [επηρεαζοντων]{.greek-omitted} [υμας]{.greek-omitted} [και]{.greek-omitted} διωκοντων υμας[5:44]{.aside}

οπως γενησθε υιοι του [πατρος]{.greek-abbr} υμων του εν τοις [ουρανοις]{.greek-abbr} οτι τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ αγαπησητε τους [αγαπωντας]{.greek-omitted} [αγαποντας]{.greek-added} υμας τινα μισθον εχετε ουχι και οι τελωναι το [αυτ[ω]{.unclear}]{.greek-added} [αυτο]{.corr} [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[5:46]{.aside}

και εαν ασπασησθε τους [φιλους]{.greek-omitted} [αδελφους]{.greek-added} υμων μονον τι περισσον ποιειτε ουχι και οι [τελωναι]{.greek-omitted} [ουτως]{.greek-omitted} [εθνηκοι]{.greek-added} [το]{.greek-added} [αυτο]{.greek-added} ποιουσιν[5:47]{.aside}

εσεσθε ουν υμεις τελειοι [ωσπερ]{.greek-omitted} [ως]{.greek-added} ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} τελειος [εστιν]{.greek-omitted} [εστι]{.greek-added}[5:48]{.aside}

### Chapter 6

προσεχετε την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν [ποιης]{.greek-omitted} [ποιεις]{.greek-added} ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω [αυτος]{.greek-omitted} αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται οτι φιλουσιν εν ταις συναγωγαις και εν ταις γωνιαις των πλατειων εστωτες [προσευχεσθαι]{.greek-omitted} [προσευχονται]{.greek-added} οπως [αν]{.greek-omitted} [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} [ως]{.greek-added} [δικαιοι]{.greek-added} αμην λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το ταμιειον σου και [κ]{.unclear}λεισας την θυραν σου προσευξαι τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη βαττολογησητε ωσπερ οι [εθνικοι]{.greek-omitted} [υποκριται]{.greek-added} [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν [τη]{.greek-omitted} πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν ομοιωθητε αυτοις [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} υμων ων χρειαν [εχεται]{.greek-added} [εχετε]{.corr} προ του υμας [αιτησαι]{.greek-omitted} [αιτεισαι]{.greek-added} αυτον[6:8]{.aside}

ουτως ουν [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} υμεις [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το ονομα σου[6:9]{.aside}

[θετω]{.greek-added} [ελθετω]{.corr} η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[6:10]{.aside}

τον αρ[τ]{.unclear}ον ημων τον [επ[η]{.unclear}ουσιον]{.greek-added} [επιουσιον]{.corr} δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων ως και ημεις αφιεμεν τοις οφειλεταις ημων[6:12]{.aside}

και μη εισενεγκης ημας εις πειρασμον [αλλ]{.greek-added} [αλλα]{.corr} ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα εις τους αιωνας αμην[6:13]{.aside}

εαν γαρ αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} [τα]{.greek-added} [παραπτωματα]{.greek-added} [υμων]{.greek-added}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [αυτων]{.greek-omitted} ουδε ο [πατηρ]{.greek-abbr} υμων αφησει τα παραπτωματα υμων[6:15]{.aside}

οταν δε νηστευητε μη γινεσθε ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:16]{.aside}

συ δ[ε]{.greek-supplied} νηστευων [αλειψαι]{.greek-omitted} [αλειψε]{.greek-added} σου την κεφαλην και το προσωπον σου [νιψαι]{.greek-omitted} [νιψε]{.greek-added}[6:17]{.aside}

οπως μη φανης [νηστευων]{.greek-added} τοις [ανθρωποις]{.greek-abbr} [νηστευων]{.greek-omitted} αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι [εν]{.greek-added} [τω]{.greek-added} [φανερω]{.greek-added}[6:18]{.aside}

μη θησαυριζετε [υμιν]{.greek-omitted} [υμεις]{.greek-added} θησαυρους επι της γης οπου σης και βρωσις αφανιζει και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορυσσουσι]{.greek-added} και [κλεπτουσιν]{.greek-omitted} [κλεπτουσι]{.greek-added}[6:19]{.aside}

θησαυριζετε δε [υμιν]{.greek-omitted} [υμεις]{.greek-added} θησαυρους εν [ουρανω]{.greek-abbr} οπου ουτε σης ουτε βρωσις αφανιζει και οπου κλεπται ου [διορυσσουσιν]{.greek-omitted} [διορυσσουσι]{.greek-added} [ουδε]{.greek-omitted} [και]{.greek-added} κλεπτουσιν[6:20]{.aside}

οπου γαρ [εστιν]{.greek-omitted} [εσται]{.greek-added} ο θησαυρος [υμων]{.greek-omitted} [σου]{.greek-added} εκει εσται και η καρδια [υμων]{.greek-omitted} [σου]{.greek-added}[6:21]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους [η]{.greek-omitted} [ει]{.greek-added} ολον το σωμα σου [φοτινον]{.greek-added} [φωτεινον]{.greek-omitted} [[φωτινον]{.corr}]{.greek-added} εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος [η]{.greek-omitted} [ει]{.greek-added} ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος [εστιν]{.greek-omitted} [εσι]{.greek-added} το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η [του]{.greek-added} ενος ανθεξεται και του ετερου καταφρονησει ου δυνασθε [θεω]{.greek-abbr} δουλευειν και μαμωνα[6:24]{.aside}

δια τουτο λεγω υμιν μη μεριμνατε τη ψυχη υμων τι φαγητε [και]{.greek-omitted} [η]{.greek-added} τι [πιητε]{.greek-omitted} [πιετε]{.greek-added} μηδε τω σωματι υμων τι [ενδυσησθε]{.greek-omitted} [ονδυσησθε]{.greek-added} ουχι η ψυχη πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα πετεινα του [ουρανου]{.greek-abbr} οτι ου [σπειρουσιν]{.greek-omitted} [σπειρη]{.greek-added} ουδε [θεριζουσιν]{.greek-omitted} [θεριζει]{.greek-added} ουδε [συναγουσιν]{.greek-omitted} [συναγει]{.greek-added} εις αποθηκας και ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} τρεφει αυτα ουχ υμεις μαλλον διαφερετε [[διαφερεται]{.corr}]{.greek-added} αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται [προσθειναι]{.greek-omitted} [προσθηναι]{.greek-added} επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε [νηθει]{.greek-omitted} [νηθη]{.greek-added}[6:28]{.aside}

λεγω δε υμιν [οτι]{.greek-omitted} ουδε σολομων εν παση τη δοξη αυτου [περιεβαλετο]{.greek-omitted} [περιεβαλλετο]{.greek-added} ως εν τουτων[6:29]{.aside}

[ει]{.greek-omitted} [ι]{.greek-added} δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλο[―]{.gap}μενον [[βαλλομενον]{.corr}]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ουτως]{.greek-omitted} [αμφιεννυσιν]{.greek-omitted} ου [πολω]{.greek-added} [πολλω]{.corr} μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν μεριμνησητε λεγοντες τι φαγωμεν η τι πιωμεν η τι [περιβαλωμεθα]{.greek-omitted} [περιβαλλομεθα]{.greek-added}[6:31]{.aside}

παντα γαρ ταυτα τα εθνη επιζητει [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} οτι χρηζετε τουτων απαντων[6:32]{.aside}

ζητειτε [δε]{.greek-omitted} [δη]{.greek-added} πρωτον την βασιλειαν του [θεου]{.greek-abbr} και την δικαιοσυνην αυτου και ταυτα παντα [προστεθησεται]{.greek-omitted} [προστεθεσεται]{.greek-added} υμιν[6:33]{.aside}

μη ουν [μεριμνησητε]{.greek-omitted} [μεριμν[α]{.unclear}σητε]{.greek-added} εις την αυριον η γαρ αυριον [μεριμνησει]{.greek-omitted} [μεριμνηση]{.greek-added} [τα]{.greek-omitted} [τω]{.greek-added} [εξ]{.greek-added} [εαυτης]{.greek-omitted} [αυτης]{.greek-added} αρ[κετο]{.greek-supplied}ν τη ημερα η κακια [αυτης]{.greek-omitted} [αυσης]{.greek-added}[6:34]{.aside}

### Chapter 7

μη κρινετε ινα μη κριθητε[7:1]{.aside}

εν [ω]{.greek-omitted} [η]{.greek-added} γαρ κριματι κρινετε κριθησεσθε και εν ω μετρω μετρειτε [μετρηθησεται]{.greek-omitted} [μετρηθησετε]{.greek-added} υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος [το]{.greek-omitted} [τω]{.greek-added} εν τω οφθαλμω του αδελφου σου την δε [δοκον]{.greek-added} [την]{.greek-added} εν τω σω οφθαλμω [δοκον]{.greek-omitted} ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος απο του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη [δωτε]{.greek-omitted} [δοτε]{.greek-added} το αγιον τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε βαλητε τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε καταπατησωσιν αυτους εν τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

[αιτ[―]{.gap}τε]{.greek-added} [αιτειτε]{.corr} και δοθησεται [[δοθησετε]{.corr}]{.greek-added} υμιν ζητειτε και ευρησετε κρουετε και ανοιγησεται υμιν[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις εστιν εξ υμων [ανθρωπος]{.greek-abbr} [ον]{.greek-omitted} [ος]{.greek-added} εαν [αιτηση]{.greek-omitted} [αιτησει]{.greek-added} ο υιος αυτου αρτον μη λιθον επιδω[σ]{.unclear}[ει]{.greek-supplied} [αυ]{.unclear}τω[7:9]{.aside}

ει ουν υμεις πονηροι οντες οιδα[τε]{.greek-supplied} [δ]{.greek-supplied}οματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν αυτ[ο]{.unclear}ν [αυτον]{.greek-added}[7:11]{.aside}

παντα ουν οσα [[οσ]{.unclear}[α]{.greek-supplied}]{.greek-added} αν [θελητε]{.greek-omitted} [θελετε]{.greek-added} [ινα]{.greek-omitted} [ο[―]{.gap}α]{.greek-added} [α]{.greek-added} [[ονα]{.corr}]{.greek-added} ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} ουτως και υμεις ποιειτε αυτοις [ουτος]{.greek-omitted} [ουτως]{.greek-added} γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

εισελθετε δια της [στενη]{.greek-added} [στενης]{.corr} πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

τι στενη η πυλη και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι [ευρισκοτες]{.greek-added} [ευρισκοντες]{.corr} αυτην[7:14]{.aside}

προσεχετε δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε εισιν λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων [επιγνωσεσθε]{.greek-omitted} [επιγνωσεσθαι]{.greek-added} αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ου[δ]{.unclear}[ε]{.greek-supplied} [δε]{.greek-supplied}[ν]{.unclear}δρον σαπρον καρπους καλους π[οι]{.unclear}ειν[7:18]{.aside}

παν [ουν]{.greek-added} δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις [το]{.greek-added} πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων [επιγνωσεσθε]{.greek-omitted} [επιγνωσεσθαι]{.greek-added} αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} [εισελευσεται]{.greek-added} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου τω σω ονοματι προεφητευσαμεν και τω σω ονοματι δαιμονια [εξεβαλομεν]{.greek-omitted} [εξεβαλλομεν]{.greek-added} και τω σω ονοματι δυναμεις [εποιησαμεν]{.greek-added} πολλας [εποιησαμεν]{.greek-omitted}[7:22]{.aside}

και τοτε ομολογησω αυτοις οτι ουδεποτε εγνων υμας αποχωρειτε απ εμου [παντες]{.greek-added} οι εργαζομενοι την ανομιαν[7:23]{.aside}

πας ουν οστις ακουει μου τους λογους τουτους και ποιει αυτους ομοιωσω αυτον ανδρι φρονιμω οστις ωκοδομησεν [αυτου]{.greek-added} την οικιαν [αυτου]{.greek-omitted} επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και [επνευσειν]{.greek-added} [επνευσαν]{.corr} οι ανεμοι και [προσεπεσον]{.greek-omitted} [προσεπεσαν]{.greek-added} τη οικια εκεινη και ουκ επεσεν τεθεμελιωτο γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω οστις ωκοδομησεν την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεκοψαν τη οικια εκεινη και επεσεν και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγενετο οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις [αυτων]{.greek-added} [και]{.greek-added} [οι]{.greek-added} [φαρισαιοι]{.greek-added}[7:29]{.aside}

### Chapter 8

καταβαντι δε αυτω απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου λεπρος ελθων προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} εαν θελης δυνασαι με καθαρισαι[8:2]{.aside}

και εκτεινας την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω καθαρισθητι και ευθεως [εκαθαρισθη]{.greek-omitted} [εκαθερισθη]{.greek-added} [απ]{.greek-added} αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι ειπης [αλλα]{.greek-omitted} [αλλ]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} το δωρον ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον [αυτοις]{.greek-omitted} [αυτης]{.greek-added}[8:4]{.aside}

εισελθοντι δε [αυτω]{.greek-omitted} [αυτου]{.greek-added} εις καπερναουμ [προ]{.greek-added} προσηλθεν αυτω εκατονταρχος παρακαλων [αυτον]{.greek-omitted} [αυτων]{.greek-added}[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου βεβληται εν τη οικια παραλυτικος δεινως βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε [λογω]{.greek-omitted} [λογον]{.greek-added} και [ιαθησεται]{.greek-omitted} [καθησεται]{.greek-added} ο παις μου[8:8]{.aside}

και [γαρ]{.greek-omitted} εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν εχων υπ [εμαυτον]{.greek-omitted} [εμαυτου]{.greek-added} στρατιωτας και λεγω [τουτω]{.corr} πορευθητι και [πορευεται]{.greek-omitted} [πωρευεται]{.greek-added} και [αλλο]{.greek-added} [αλλω]{.corr} ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} εθαυμασεν και ειπεν τοις ακολουθουσιν [αυτω]{.greek-added} αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και [ανακλιθησονται]{.greek-omitted} [ανακληθησονται]{.greek-added} μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω εκατονταρχη υπαγε [και]{.greek-omitted} ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου [απο]{.greek-added} [της]{.greek-added} [ωρας]{.greek-added} [εκεινης]{.greek-added} [και]{.greek-added} [υποστρεψας]{.greek-added} [ο]{.greek-added} [εκατονταρχος]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [αυτου]{.greek-added} εν [αυτη]{.greek-added} τη ωρα [εκεινη]{.greek-omitted} [ευρεν]{.greek-added} [αυτον]{.greek-added} [υγιαινοντα]{.greek-added}[8:13]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [οιδεν]{.greek-added} την πενθεραν αυτου [βεβλημενην]{.greek-omitted} [βεβλημμενην]{.greek-added} και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και εξεβαλεν τα [πνευματα]{.greek-abbr} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας ασθενειας [ημων]{.greek-omitted} ελαβεν και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [πολλους]{.greek-omitted} [τους]{.greek-added} οχλους περι αυτον [εκελευσεν]{.greek-omitted} [απελθειν]{.greek-omitted} [απηλθεν]{.greek-added} εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν απερχη[8:19]{.aside}

[και]{.greek-omitted} λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες [φωλεους]{.greek-omitted} [φολεους]{.greek-added} [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κλιναι]{.greek-added}[8:20]{.aside}

[ειπε]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added} [και]{.greek-added} [ετερος]{.greek-added} [των]{.greek-added} [μαθητων]{.greek-added} [ακολουθησω]{.greek-added} [σοι]{.greek-added} [αλλ]{.greek-added} [επιτρεψον]{.greek-added} [μοι]{.greek-added} [πρωτον]{.greek-added} [πορευθεντα]{.greek-added} [αποταξασθαι]{.greek-added} [τοις]{.greek-added} [ιδιοις]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ειπεν]{.greek-added} [αυτω]{.greek-added} [ουδεις]{.greek-added} [επιβαλων]{.greek-added} [την]{.greek-added} [χειρα]{.greek-added} [επ]{.greek-added} [αροτρον]{.greek-added} [και]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [οπισω]{.greek-added} [βλεπων]{.greek-added} [ευθετος]{.greek-added} [εστιν]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις το [πλ[ε]{.unclear}ιον]{.greek-added} [πλοιον]{.corr} ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το [πλοιον]{.greek-omitted} [πλειον]{.greek-added} καλυπτεσθαι υπο των κυματων αυτος δε [εκαθευδεν]{.greek-omitted} [εκαθευδε]{.greek-added}[8:24]{.aside}

και προσελθοντες οι μαθηται [ηγειραν]{.greek-omitted} [ηγεραν]{.greek-added} αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι τοτε εγερθεις [επετι]{.greek-added} [επετιμησεν]{.greek-omitted} [[επεττιμησε]{.corr}]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο [γαληνη]{.greek-omitted} [γαλινη]{.greek-added} μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν λεγοντες ποταπος εστιν ουτος [ο]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

και ελθοντι αυτω εις το περαν εις την χωραν των γεργεσηνων υπηντησαν αυτω δυο [δαιμονιζομεναι]{.greek-added} [δαιμονιζομενοι]{.corr} εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου [εκραξαν]{.greek-omitted} [ηρξαντο]{.greek-added} λεγοντες τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων πολλων βοσκομενη[8:30]{.aside}

οι δε δαιμονες [παρεκαλουν]{.greek-omitted} [επαρεκαλουν]{.greek-added} αυτον λεγοντες ει [εκβαλλεις]{.greek-omitted} [εκβαλλης]{.greek-added} ημας επιτρεψον ημιν απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου ωρμησεν πασα η αγελη των χοιρων κατα του [κρημνου]{.greek-omitted} [κριμνου]{.greek-added} εις την θαλασσαν και απεθανον εν τοις [υδασιν]{.greek-omitted} [υδασι]{.greek-added}[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις [εξηλθεν]{.greek-omitted} [εξηλθον]{.greek-added} εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβ[α]{.unclear}ς εις το πλοιον διεπερασεν και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την [πιστην]{.greek-added} [πιστιν]{.corr} αυτων ειπεν τω παραλυτικω [θαρσει]{.greek-omitted} [θαρση]{.greek-added} τεκνον [αφεωνται]{.greek-omitted} [αφεοντε]{.greek-added} σοι αι αμαρτιαι σου[9:2]{.aside}

και ιδου τινες των γραμματεων [ειπον]{.greek-omitted} [ειπαν]{.greek-added} εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και ιδων ο [ιησους]{.greek-abbr} [τοις]{.greek-added} [τας]{.corr} ενθυμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις [ενθυμεισθε]{.greek-omitted} [[ενθυμεισθαι]{.corr}]{.greek-added} πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν ευκοπωτερον ειπειν [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σου αι αμαρτιαι η ειπειν εγειραι και περιπατει[9:5]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ιδητε]{.greek-added} οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

και παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} καθημενον επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες [συν[―]{.gap}οντο]{.greek-added} [συνανεκειντο]{.corr} τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα [των]{.greek-omitted} τελωνων και αμαρτωλων [εσθιει]{.greek-omitted} ο διδασκαλος υμων [εσθιει]{.greek-added}[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν [ελεον]{.greek-omitted} [ελεος]{.greek-added} θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται ιωαννου λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε μαθηται σου ου νηστευουσιν[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται [οι]{.greek-omitted} υιοι του νυμφωνος πενθειν εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

ουδεις [δε]{.greek-omitted} [επιβαλλει]{.greek-omitted} [επιβαλλη]{.greek-added} επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και χειρον σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος εκχειται και οι ασκοι απολουνται αλλα βαλλουσιν οινον νεον εις ασκους καινους και αμφοτεροι συντηρουνται[9:17]{.aside}

ταυτα αυτου λαλουντος [αυτοις]{.greek-omitted} ιδου αρχων [εις]{.greek-omitted} [ελθων]{.greek-omitted} [εἷς]{.greek-added} [ἐλθὼν]{.greek-added} προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν αλλα ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον [αψωμαι]{.greek-omitted} [αψομαι]{.greek-added} του ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} θαρσει θυγατερ η πιστις σου σεσωκεν σε και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ απεθανεν το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

[οταν]{.greek-added} [οτε]{.greek-omitted} [δε]{.greek-omitted} εξεβληθη ο οχλος εισελθων εκρατησεν της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αυτου]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

και παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας [υιε]{.greek-omitted} [υιος]{.greek-added} [δαυιδ]{.greek-abbr}[9:27]{.aside}

ελθοντι δε εις την οικιαν προσηλθον αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων αυτων λεγων κατα την πιστιν υμων γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες [διεφημισαν]{.greek-omitted} [διεφημησαν]{.greek-added} αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} [κοφον]{.greek-added} [κωφον]{.corr} δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες ουδεποτε εφανη [ουτως]{.greek-omitted} [τοιουτος]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε φαρισαιοι ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολεις πασας και τας κωμας διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[9:35]{.aside}

ιδων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν εσκυλμενοι και [ερριμμενοι]{.greek-omitted} [ερρημενοι]{.greek-added} ωσει προβατα μη εχοντα ποιμενα[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του κυριου τ[ου]{.unclear} θερισμου οπως [εκβαλη]{.greek-omitted} [εκβαλα]{.greek-added} εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

και προσκαλεσαμενος τους δωδεκα μαθητας αυτου εδωκεν αυτοις εξουσιαν [πνευματων]{.greek-abbr} ακαθαρτων ωστε εκβαλλειν αυτα και θεραπευειν πασαν νοσον και πασαν μαλακιαν [εν]{.greek-added} [τω]{.greek-added} [λαω]{.greek-added}[10:1]{.aside}

των [δε]{.greek-omitted} δωδεκα αποστολων τα ονοματα εστιν ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου ιακωβος ο του ζεβεδαιου και ιωαννης ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και [λεββαιος]{.greek-omitted} [δεββαιος]{.greek-added} ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο [κανανιτης]{.greek-omitted} [καναναιος]{.greek-added} και ιουδας ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους δωδεκα [απεστειλεν]{.greek-omitted} [απεστηλεν]{.greek-added} ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν σαμαρειτων μη εισελθητε[10:5]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} δε μαλλον προς τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

[πορευομενοι]{.greek-omitted} [πορευομενει]{.greek-added} δε [κηρυσσετε]{.greek-omitted} [κηρυσσεται]{.greek-added} λεγοντες οτι [ηγγικεν]{.greek-omitted} [ιγγικεν]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας θεραπευετε λεπρους καθαριζετε δαιμονια εκβαλλετε δωρεαν ελαβετε [δωρεαν]{.greek-omitted} [δορεαν]{.greek-added} δοτε[10:8]{.aside}

μη κτησησθε χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε ραβδους αξιος γαρ ο εργατης της τροφης αυτου εστιν[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις εν αυτη αξιος εστιν κακει [μεινατε]{.greek-omitted} [μενετε]{.greek-added} εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν ασπασασθε αυτην[10:12]{.aside}

και εαν μεν η η οικια αξια ελθετω η ειρηνη υμων επ αυτην εαν δε μη η αξια η [οικια]{.greek-added} [η]{.greek-added} ειρηνη υμων προς υμας επιστραφητω[10:13]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της οικιας η της πολεως εκεινης εκτιναξατε τον κονιορτον [εκ]{.greek-added} των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν ανεκτοτερον εσται γη σοδομων και [γομορρων]{.greek-omitted} [γομορρας]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων γινεσθε ουν φρονιμοι [ωσει]{.greek-added} [ως]{.greek-omitted} [οι]{.greek-omitted} οφεις και [ακ[―]{.gap}ραιοι]{.greek-added} [ακεραιοι]{.corr} ως αι περιστεραι[10:16]{.aside}

προσεχετε [δε]{.greek-omitted} απο των [ανθρωπων]{.greek-abbr} [και]{.greek-added} [παραδωσουσιν]{.corr} γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε παραδιδωσιν υμας μη μεριμνησητε πως η τι λαλησητε δοθησεται γαρ [υμιν]{.greek-omitted} εν εκεινη τη ωρα [υμιν]{.greek-added} τι [λαλησετε]{.greek-omitted} [λαλησητε]{.greek-added}[10:19]{.aside}

ου γαρ υμεις [εστ[α]{.unclear}ι]{.greek-added} [εστε]{.corr} οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι [υπο]{.greek-omitted} [υπ]{.greek-added} [παντων]{.greek-omitted} [απανπαντων]{.greek-added} δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[10:22]{.aside}

οταν δε διωκωσιν υμας εν τη πολει ταυτη φευγετε εις την αλλην αμην [γαρ]{.greek-omitted} λεγω υμιν [οτι]{.greek-added} ου μη [τελεσηται]{.greek-added} [τελεσητε]{.corr} τας [πολ[α]{.unclear}ς]{.greek-added} [πολεις]{.corr} του [ισραηλ]{.greek-abbr} εως αν ελθη ο υιος του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ εστιν μαθητης υπερ τον διδασκαλον ουδε δουλος υπερ τον κυριον αυτου[10:24]{.aside}

[αρνετον]{.greek-added} [αρκετον]{.corr} τω μαθητη ινα γενηται ως ο διδασκαλος αυτου και ο δουλος ως ο [κυρο]{.greek-added} [κυριος]{.corr} αυτου ει τον [οικοδεσποτην]{.greek-omitted} [δεσποτην]{.greek-added} βεελζεβουλ [εκαλεσαν]{.greek-omitted} [επεκαλεσαντο]{.greek-added} ποσω μαλλον τους [οικειακους]{.greek-omitted} [οικιακους]{.greek-added} αυτου[10:25]{.aside}

μη ουν φοβηθητε αυτους ουδεν γαρ εστιν [ουδεν]{.greek-added} [εστι]{.greek-added} κεκαλυμμενον ο ουκ [αποκαλυφθησεται]{.greek-omitted} [αποκαλυφθησετε]{.greek-added} και κρυπτον ο ου γνωσθησεται[10:26]{.aside}

ο λεγω υμιν εν τη [σκοτεια]{.greek-added} [σκοτια]{.corr} ειπατε εν τω φωτι και ο εις το ους [ακουετε]{.greek-omitted} [ηκουσατε]{.greek-added} κηρυξατε επι των δωματων [υμων]{.greek-added}[10:27]{.aside}

και μη [φοβεισθε]{.greek-omitted} [φοβηθητε]{.greek-added} απο των αποκτενοντων το σωμα την δε ψυχην μη [δυναμενων]{.greek-omitted} [δυναμενον]{.greek-added} αποκτειναι φοβηθητε [δε]{.greek-omitted} μαλλον τον δυναμενον και [την]{.greek-omitted} ψυχην και [το]{.greek-omitted} σωμα απολεσαι εν γεεννη[10:28]{.aside}

ουχι δυο στρουθια ασσαριου [πωλειται]{.greek-omitted} [πολειται]{.greek-added} και εν εξ αυτων [ου]{.corr} [πεσειται]{.greek-omitted} [πεσηται]{.greek-added} επι την γην ανευ του [πατρος]{.greek-abbr} υμων[10:29]{.aside}

υμων δε [και]{.greek-omitted} αι τριχες της κεφαλης πασαι ηριθμημεναι εισιν[10:30]{.aside}

μη ουν [φοβηθητε]{.greek-omitted} [φοβησθε]{.greek-added} πολλων στρουθιων διαφερετε υμεις[10:31]{.aside}

πας ουν οστις ομολογησει εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν ουρανοις[10:32]{.aside}

οστις δ αν [αρνησηται]{.greek-omitted} [απαρνησηται]{.greek-added} με εμπροσθεν των [ανθρωπων]{.greek-abbr} [αρνησομαι]{.greek-omitted} [απαρνησομαι]{.greek-added} [καγω]{.greek-added} αυτον [καγω]{.greek-omitted} εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:33]{.aside}

μη νομισητε οτι ηλθον βαλειν ειρηνην επι την γην ουκ ηλθον βαλειν ειρηνην αλλα μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και [θυγατερα]{.greek-omitted} [θυγατεραν]{.greek-added} κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και εχθροι του [ανθρωπου]{.greek-abbr} οι [οικειακοι]{.greek-omitted} [οικιακοι]{.greek-added} αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} η [μητερα]{.greek-abbr} υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος και ο φιλων [υιον]{.greek-abbr} η θυγατερα υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψεται[10:41]{.aside}

και ος εαν ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν [ου]{.greek-omitted} [ουκ]{.greek-added} [μη]{.greek-omitted} απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις [δωδεκα]{.greek-omitted} μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε [ιωαννης]{.greek-omitted} [ιωανης]{.greek-added} ακουσας εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-abbr} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} και [χωλοι]{.greek-omitted} [χολοι]{.greek-added} περιπατουσιν λεπροι καθαριζονται και κωφοι ακουουσιν [και]{.greek-added} νεκροι εγειρονται και [πτωχοι]{.greek-omitted} [πωχοι]{.greek-added} ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος [εαν]{.greek-omitted} [αν]{.greek-added} μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} [λεγει]{.greek-added} [λεγειν]{.corr} τοις οχλοις περι ιωαννου τι εξηλθετε εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι εξηλθετε ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι εξηλθετε ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ [εγηγερται]{.greek-omitted} [εγηγερτε]{.greek-added} εν [γεννητοις]{.greek-omitted} [γενητοις]{.greek-added} γυναικων μειζων ιωαννου του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων ιωαννου του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες [γαρ]{.greek-omitted} οι προφηται και ο νομος εως ιωαννου [προεφητευσαν]{.greek-omitted} [επροεφητευσαν]{.greek-added}[11:13]{.aside}

και ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια εστιν παιδιοις [καθημενοις]{.greek-added} εν [ταις]{.greek-added} αγοραις [α]{.greek-added} [καθημενοις]{.greek-omitted} [και]{.greek-omitted} [προσφωνουσιν]{.greek-omitted} [προσφωνουντα]{.greek-added} τοις [εταιροις]{.greek-omitted} [ετεροις]{.greek-added} [αυτων]{.greek-omitted}[11:16]{.aside}

[και]{.greek-omitted} λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ ωρχησασθε εθρηνησαμεν [υμιν]{.greek-omitted} και ουκ εκοψασθε[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ιωαννης μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης τελωνων φιλος και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ονειδιζειν τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χωραζιν]{.greek-added} ουαι σοι βηθσαιδα οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι αν εν σακκω και σποδω [καθημεναι]{.greek-added} μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι ανεκτοτερον εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ [η]{.greek-omitted} [μη]{.greek-added} εως του [ουρανου]{.greek-abbr} [υψωθεισα]{.greek-omitted} [υψωθηση]{.greek-added} εως αδου καταβιβασθηση οτι ει εν σοδομοις [εγενοντο]{.greek-omitted} [εγενηθησαν]{.greek-added} αι δυναμεις αι γενομεναι εν σοι [εμειναν]{.greek-omitted} [εμεινεν]{.greek-added} αν μεχρι της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι γη σοδομων ανεκτοτερον εσται εν ημερα κρισεως η σοι[11:24]{.aside}

εν εκεινω τω καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [εξομολογουμ[―]{.gap}]{.greek-added} [εξομολογουμαι]{.corr} σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως [ευδοκια]{.greek-added} εγενετο [ευδοκια]{.greek-omitted} εμπροσθεν σου[11:26]{.aside}

παντα μοι παρεδοθη υπο του [πατρος]{.greek-abbr} μου και ουδεις επιγινωσκει τον υιον ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο [υιος]{.greek-abbr} και ω εαν [βουληται]{.greek-omitted} [βουλητε]{.greek-added} ο [υιος]{.greek-abbr} αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι κοπιωντες και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου χρηστος και το φορτιον μου ελαφρον εστιν[11:30]{.aside}

### Chapter 12

εν εκεινω τω καιρω επορευθη ο [ιησους]{.greek-abbr} τοις σαββασιν δια των σποριμων οι δε μαθηται αυτου επεινασαν και ηρξαντο τιλλειν [τους]{.greek-added} σταχυας και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντες ειπον αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ποιειν εν σαββατω[12:2]{.aside}

ο δε ειπεν αυτοις ουκ ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε επεινασεν [αυτος]{.greek-omitted} και οι μετ αυτου[12:3]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως εφαγεν ους ουκ [εξων]{.greek-added} [εξον]{.corr} ην αυτω φαγειν ουδε τοις μετ αυτου ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} [μονοις]{.greek-omitted} [μονον]{.greek-added}[12:4]{.aside}

η ουκ ανεγνωτε εν τω νομω οτι τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} οι ιερεις εν τω ιερω το σαββατον βεβηλουσιν και αναιτιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[12:5]{.aside}

λεγω δε υμιν οτι του ιερου μειζον εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε τι [εστιν]{.greek-omitted} [εστι]{.greek-added} ελεον θελω και ου θυσιαν ουκ αν κατεδικασατε τους αναιτιους[12:7]{.aside}

[κυριος]{.greek-abbr} γαρ εστιν [του]{.greek-omitted} [σαββατου]{.greek-omitted} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [του]{.greek-added} [σαββατου]{.greek-added}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} ην την χειρα εχων ξηραν και επηρωτησαν αυτον λεγοντες ει εξεστιν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις [εσται]{.greek-omitted} εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει αυτο και εγ[ε]{.unclear}ρει[12:11]{.aside}

ποσω ουν διαφερει [ο]{.greek-added} [ανθρωπος]{.greek-abbr} προβατου ωστε εξεστιν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} καλως ποιειν[12:12]{.aside}

τοτε [λεγει]{.corr} τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} [η]{.greek-added} [χειρ]{.greek-added} [αυτου]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

οι δε φαρισαιοι συμβουλιον ελαβον κατ αυτου [εξελθοντες]{.greek-omitted} οπως αυτον [απωσιν]{.greek-added} [απολεσωσιν]{.greek-omitted} [[απωλεσιν]{.corr}]{.greek-added}[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και επετιμησεν αυτοις ινα μη φανερον [ποιησωσιν]{.greek-added} αυτον [ποιησωσιν]{.greek-omitted}[12:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον ηρετισα ο αγαπητος μου εις ον ευδοκησεν η ψυχη μου [θησω]{.greek-omitted} [θησομαι]{.greek-added} το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν [απαγγελει]{.greek-omitted} [αναγγελει]{.greek-added}[12:18]{.aside}

ουκ [ερισει]{.greek-omitted} [ερησει]{.greek-added} ουδε κραυγασει ουδε ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον τυφομενον ου σβεσει εως αν [εκβαλει]{.greek-added} [εκβαλη]{.greek-omitted} [[εκβαλλη]{.corr}]{.greek-added} εις νικος την κρισιν[12:20]{.aside}

και τω ονοματι αυτου εθνη [ελπιουσιν]{.greek-omitted} [ελπιουσι]{.greek-added}[12:21]{.aside}

τοτε προσηνεχθη αυτω [δαιμονιζομενος]{.greek-omitted} [δαιμομονιζομενος]{.greek-added} τυφλος και κωφος και εθεραπευσεν αυτον ωστε τον τυφλον και κωφον και λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο παντες οι οχλοι και ελεγον μητι ουτος εστιν ο υιος [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες ειπον ουτος ουκ εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

[ειδως]{.greek-omitted} [ιδων]{.greek-added} δε ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν αυτοις πασα βασιλεια μερισθεισα καθ εαυτης ερημουται και πασα πολις η οικια μερισθεισα καθ εαυτης ου σταθησεται[12:25]{.aside}

και ει ο σατανας [α[υ]{.unclear}]{.greek-added} [[τ]{.unclear}ον]{.greek-added} [τον]{.corr} σαταναν εκβαλλει εφ εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

και ει εγω εν βεελζεβουλ εκβαλλω τα δαιμονια οι υιοι υμων εν τινι [εκβαλλουσιν]{.greek-omitted} [εκβαλλουσι]{.greek-added} δια τουτο αυτοι [κριται]{.greek-added} υμων εσονται [κριται]{.greek-omitted}[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} [εγω]{.greek-omitted} εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

η πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου διαρπασαι εαν μη πρωτον δηση τον ισχυρον και τοτε την οικιαν αυτου διαρπασει[12:29]{.aside}

ο μη ων μετ εμου κατ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

δια τουτο λεγω υμιν πασα [αμαρτια]{.greek-omitted} [και]{.greek-omitted} βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} η δε του [πνευματος]{.greek-abbr} βλασφημια ουκ αφεθησεται [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted}[12:31]{.aside}

[και]{.greek-omitted} ος εαν [ειπη]{.greek-omitted} [ειπει]{.greek-added} λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω ος δ αν [ειπη]{.greek-omitted} [ειπει]{.greek-added} κατα του [πνευματος]{.greek-abbr} του αγιου ουκ αφεθησεται αυτω ουτε εν [τουτω]{.greek-added} τω [νυν]{.greek-omitted} αιωνι ουτε εν τω μελλοντι[12:32]{.aside}

η ποιησατε το δενδρον καλον και τον καρπον αυτου [καλ[λ]{.unclear}ον]{.greek-added} [καλον]{.corr} η ποιησατε το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον γινωσκεται[12:33]{.aside}

γεννηματα εχιδνων πως [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} αγαθα λαλειν πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου [εκβαλλει]{.greek-omitted} [αγαθα]{.greek-omitted} [της]{.greek-added} [καρδιας]{.greek-added} [αυτου]{.greek-added} [προφερει]{.greek-added} [το]{.greek-added} [αγαθον]{.greek-added} και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου [εκβαλλει]{.greek-omitted} [της]{.greek-added} [καρδιας]{.greek-added} [αυτου]{.greek-added} [προφερει]{.greek-added} [το]{.greek-added} [πονηρα]{.greek-omitted} [πονηρον]{.greek-added}[12:35]{.aside}

λεγω δε υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσουσι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων [σου]{.corr} δικαιωθηση και εκ των λογων [σου]{.corr} καταδικασθηση[12:37]{.aside}

τοτε απεκριθησαν τινες των γραμματεων και φαρισαιων λεγοντες διδασκαλε θελομεν απο σου σημειον ιδειν[12:38]{.aside}

[ο]{.greek-omitted} [ος]{.greek-added} δε αποκριθεις ειπεν αυτοις [λεγων]{.greek-added} γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ γαρ ην ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας ουτως εσται ο υιος του [ανθρωπου]{.greek-abbr} εν τη καρδια της γης τρεις ημερας και τρεις νυκτας[12:40]{.aside}

ανδρες [νινευιται]{.greek-omitted} [νευιται]{.greek-added} αναστησονται εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

[βασιλισσα]{.greek-omitted} [βασιλεισσα]{.greek-added} νοτου εγερθησεται [εν]{.greek-omitted} [τη]{.greek-omitted} [κρισει]{.greek-omitted} μετα της γενεας ταυτης [εν]{.greek-added} [τη]{.greek-added} [κρισει]{.greek-added} και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν σολομωνος [και]{.greek-omitted} [ιδου]{.greek-omitted} [πλειον]{.greek-omitted} [σολομωνος]{.greek-omitted} ωδε[12:42]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητο[υν]{.unclear} αναπαυσιν και ουχ ευρισκει[12:43]{.aside}

τοτε [λεγει]{.greek-omitted} [λεγη]{.greek-added} επιστρεψω εις τον οικον μου οθεν εξηλθον και [ελθον]{.greek-omitted} [ελθων]{.greek-added} ευρισκει [σχολαζοντα]{.greek-omitted} [σχολαζονται]{.greek-added} [σεσαρωμενον]{.greek-omitted} [σεσταραμενον]{.greek-added} και κεκοσμημενον[12:44]{.aside}

[τοτε]{.greek-omitted} πορευεται και [παραλαμβανει]{.greek-omitted} [λαμβανει]{.greek-added} μεθ εαυτου επτα ετερα [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} [τα]{.greek-added} πονηροτερα εαυτου και εισελθοντα κατοικει εκει και γινεται τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου χειρονα των πρωτων [ουτω]{.greek-added} [ουτως]{.corr} εσται [και]{.greek-omitted} [εν]{.greek-added} τη γενεα ταυτη τη πονηρα[12:45]{.aside}

ετι [δε]{.greek-omitted} αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και οι αδελφοι αυτου [ειστηκεισαν]{.greek-omitted} [ιστηκεισαν]{.greek-added} εξω ζητουντες αυτω λαλησαι[12:46]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε [αυτω]{.greek-added} τις [αυτω]{.greek-omitted} ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εξω [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} ζητουντες σοι λαλησαι[12:47]{.aside}

ο δε [αποκριθεις]{.corr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω ειποντι [αυτω]{.greek-omitted} τις εστιν η [μητηρ]{.greek-abbr} μου και τινες [εισιν]{.greek-omitted} οι αδελφοι μου[12:48]{.aside}

οστις γαρ [αν]{.greek-omitted} [εαν]{.greek-added} ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr} [αυτος]{.greek-omitted} [ουτος]{.greek-added} μου αδελφος και αδελφη και [μητηρ]{.greek-abbr} εστιν[12:50]{.aside}

### Chapter 13

εν δε τη ημερα εκεινη εξελθων ο [ιησους]{.greek-abbr} απο της οικιας εκαθητο παρα την θαλασσαν[13:1]{.aside}

και συνηχθησαν προς αυτον οχλοι πολλοι ωστε αυτον [εις]{.greek-omitted} το [πλει]{.greek-added} [πλοιον]{.corr} εμβαντα καθησθαι και πας ο οχλος [εις]{.greek-added} επι τον αιγιαλον [ειστηκει]{.greek-omitted} [ιστηκει]{.greek-added}[13:2]{.aside}

και ελαλησεν αυτοις [πολλα]{.greek-omitted} εν παραβολαις [πολλα]{.greek-added} λεγων ιδου εξηλθεν ο σπειρων του [σπειρειν]{.greek-omitted} [σπειραι]{.greek-added}[13:3]{.aside}

και εν τω σπειρειν αυτον α μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν αυτα[13:4]{.aside}

αλλα δε επεσεν επι τα πετρωδη οπου ουκ ειχεν γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν [βαθος]{.greek-omitted} [γης]{.greek-omitted}[13:5]{.aside}

[ριζαν]{.greek-added} [ηλιου]{.greek-omitted} [δε]{.greek-omitted} [ανατειλαντος]{.greek-omitted} [εκαυματισθη]{.greek-omitted} και [δια]{.greek-omitted} [το]{.greek-omitted} [μη]{.greek-omitted} [εχειν]{.greek-omitted} [ριζαν]{.greek-omitted} εξηρανθη[13:6]{.aside}

αλλα δε επεσεν επι τας ακανθας και ανεβησαν αι ακανθαι και απεπνιξαν αυτα[13:7]{.aside}

αλλα δε επεσεν επι την γην την καλην και εδιδου καρπον ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:8]{.aside}

ο εχων ωτα ακουειν ακουετω[13:9]{.aside}

και προσελθοντες οι μαθηται [αυτου]{.greek-added} [ειπον]{.greek-omitted} [ειπαν]{.greek-added} αυτω δια τι εν παραβολαις λαλεις αυτοις[13:10]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι υμιν δεδοται γνωναι τα μυστηρια της βασιλειας των [ουρανων]{.greek-abbr} εκεινοις δε ου δεδοται[13:11]{.aside}

οστις γαρ εχει δοθησεται αυτω και περισσευθησεται οστις δε ουκ εχει και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[13:12]{.aside}

δια τουτο εν παραβολαις αυτοις λαλω οτι βλεποντες ου [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και ακουοντες ουκ ακουουσιν ουδε [συνιουσιν]{.greek-omitted} [συνιουσι]{.greek-added}[13:13]{.aside}

και αναπληρουται αυτοις η προφητεια ησαιου [η]{.greek-omitted} λεγουσα ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} [[ακουσηται]{.corr}]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη ιδητε[13:14]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν ακουσωσιν και τη καρδια [συνωσιν]{.greek-omitted} [συνιωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και ιασομαι αυτους[13:15]{.aside}

υμων δε μακαριοι οι οφθαλμοι οτι [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και τα ωτα υμων οτι [ακουει]{.greek-omitted} [ακουουσιν]{.greek-added}[13:16]{.aside}

αμην γαρ λεγω υμιν οτι πολλοι προφηται και δικαιοι επεθυμησαν ιδειν α βλεπετε και ουκ ειδον και ακουσαι α ακουετε και ουκ ηκουσαν[13:17]{.aside}

υμεις ουν ακουσατε την παραβολην του σπειροντος[13:18]{.aside}

παντος ακουοντος τον λογον της βασιλειας και μη συνιεντος ερχεται ο πονηρος και αρπαζει το εσπαρμενον εν τη καρδια αυτου ουτος εστιν ο παρα την οδον σπαρεις[13:19]{.aside}

ο δε επι τα πετρωδη σπαρεις ουτος εστιν ο τον λογον ακουων και ευθυς μετα χαρας λαμβανων αυτον[13:20]{.aside}

ουκ εχει δε ριζαν εν εαυτω αλλα προσκαιρος [εστιν]{.greek-omitted} [εστι]{.greek-added} γενομενης δε θλιψεως η [διωγμου]{.greek-omitted} [διωγμωυ]{.greek-added} δια τον λογον ευθυς σκανδαλιζεται[13:21]{.aside}

ο δε εις τας ακανθας σπαρεις ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} ο τον λογον ακουων και η μεριμνα του αιωνος τουτου και η απατη του πλουτου συμπνιγει τον λογον και ακαρπος γινεται[13:22]{.aside}

ο δε επι την [καλην]{.greek-added} γην [την]{.greek-omitted} [καλην]{.greek-omitted} σπαρεις ουτος εστιν ο τον λογον ακουων και συνιων ος δη καρποφορει και ποιει ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:23]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} [σπειροντι]{.greek-omitted} [σπειραντι]{.greek-added} καλον σπερμα εν τω αγρω αυτου[13:24]{.aside}

εν δε τω [κα[―]{.gap}θευδειν]{.greek-added} [καθευδειν]{.corr} τους [ανθρωπους]{.greek-abbr} ηλθεν αυτου ο εχθρος και [εσπειρεν]{.greek-omitted} [επεσπειρεν]{.greek-added} ζιζανια ανα μεσον του σιτου και απηλθεν[13:25]{.aside}

οτε δε εβλαστησεν ο χορτος και καρπον [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοτε εφανη και τα ζιζανια[13:26]{.aside}

προσελθοντες δε οι δουλοι του οικοδεσποτου ειπον αυτω [κυριε]{.greek-abbr} ουχι καλον σπερμα εσπειρας εν τω [σω]{.greek-omitted} αγρω ποθεν ουν εχει ζιζανια[13:27]{.aside}

ο δε εφη αυτοις εχθρος [ανθρωπος]{.greek-abbr} τουτο εποιησεν οι δε δουλοι ειπον [αυτω]{.greek-omitted} θελεις ουν απελθοντες [συλλεξομεν]{.greek-omitted} [συλλεξωμεν]{.greek-added} αυτα[13:28]{.aside}

ο δε εφη ου μηποτε συλλεγοντες τα ζιζανια εκριζωσητε αμα αυτοις τον σιτον[13:29]{.aside}

αφετε [ουν]{.greek-added} [συναυξανεσθαι]{.greek-omitted} [αυξανεσθαι]{.greek-added} αμφοτερα μεχρι του θερισμου και εν καιρω του θερισμου ερω τοις θερισταις συλλεξατε πρωτον τα ζιζανια και δησατε αυτα [εις]{.greek-omitted} δεσμας προς το κατακαυσαι αυτα τον δε σιτον συναγαγετε εις την αποθηκην μου[13:30]{.aside}

αλλην παραβολην [παρεθηκεν]{.greek-omitted} [ελαλησεν]{.greek-added} αυτοις λεγων ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} κοκκω σιναπεως ον λαβων [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο μικροτερον μεν [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των σπερματων οταν δε αυξηθη μειζον των λαχανων [εστιν]{.greek-omitted} [εστι]{.greek-added} και γινεται δενδρον ωστε [ελθειν]{.greek-omitted} τα πετεινα του [ουρανου]{.greek-abbr} [ελθειν]{.greek-added} και κατασκηνουν εν τοις κλαδοις αυτου[13:32]{.aside}

αλλην παραβολην ελαλησεν αυτοις ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} ζυμη ην λαβουσα γυνη εκρυψεν εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33]{.aside}

ταυτα παντα ελαλησεν ο [ιησους]{.greek-abbr} εν παραβολαις τοις οχλοις και χωρις παραβολης ουκ [ελαλησεν]{.greek-added} [ελαλει]{.corr} αυτοις[13:34]{.aside}

οπως πληρωθη το ρηθεν δια [ησαιου]{.greek-added} του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου ερευξομαι κεκρυμμενα απο καταβολης [κοσμου]{.corr}[13:35]{.aside}

τοτε αφεις τους οχλους ηλθεν εις την οικιαν [αυτου]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} και προσηλθον αυτω οι μαθηται [αυτου]{.greek-omitted} λεγον[τ]{.unclear}ες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις ο σπειρων το καλον σπερμα εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του πονηρου[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστιν οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν συλλεγεται τα ζιζανια και πυρι [καιεται]{.greek-omitted} [κατακαιεται]{.greek-added} ουτως εσται εν τη συντελεια του αιωνος [τουτου]{.greek-omitted}[13:40]{.aside}

αποστελει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και [βαλουσιν]{.greek-omitted} [βαλλουσιν]{.greek-added} αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν τω αγρω ον ευρων [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας αυτου υπαγει και [πωλει]{.greek-added} παντα οσα εχει [πωλει]{.greek-omitted} και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

[ος]{.greek-omitted} ευρων [δε]{.greek-added} ενα πολυτιμον μαργαριτην απελθων [πεπρακεν]{.greek-omitted} [πεπρακε]{.greek-added} παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη [βληθη]{.greek-added} [βληθειση]{.corr} εις την θαλασσαν και εκ παντος γενους [συναγαγουση]{.greek-omitted} [συναγουση]{.greek-added}[13:47]{.aside}

ην οτε επληρωθη αναβιβασαντες επι τον αιγιαλον και καθισαντες συνελεξαν τα καλα εις [αγγεια]{.greek-omitted} [αγγη]{.greek-added} τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται [η]{.greek-added} [βασιλεια]{.greek-added} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [συντελεια]{.greek-omitted} [του]{.greek-omitted} [αιωνος]{.greek-omitted} εξελευσονται [οι]{.greek-omitted} αγγελοι και [αφοριουσιν]{.greek-omitted} [αφοριουσι]{.greek-added} τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και [βαλουσιν]{.greek-omitted} [βαλλουσιν]{.greek-added} αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των [οδοντων]{.greek-omitted} [οδωντων]{.greek-added}[13:50]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα λεγουσιν [αυτω]{.greek-omitted} ναι [κυριε]{.greek-omitted}[13:51]{.aside}

ο δε ειπεν αυτοις δια τουτο πας γραμματευς μαθητευθεις [εις]{.greek-omitted} [την]{.greek-omitted} [τη]{.greek-added} [βασιλειαν]{.greek-omitted} [βασιλεια]{.greek-added} των [ουρανων]{.greek-abbr} ομοιος εστιν ανθρωπω οικοδεσποτη οστις εκβαλλει εκ του θησαυρου αυτου καινα και παλαια[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας μετηρεν εκειθεν[13:53]{.aside}

και ελθων εις την πατριδα αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων ωστε εκπληττεσθαι αυτους και λεγειν ποθεν τουτω η σοφια αυτη [και]{.greek-omitted} [αι]{.greek-omitted} [δυναμεις]{.greek-omitted}[13:54]{.aside}

ουχ ουτος εστιν ο του τεκτονος [υιος]{.greek-abbr} ουχι η [μητηρ]{.greek-abbr} αυτου [λεγετε]{.greek-added} [λεγεται]{.corr} μαριαμ και οι αδελφοι αυτου ιακωβος και [ιωσης]{.greek-omitted} [ιωαννης]{.greek-added} και σιμων και [ο]{.greek-added} ιουδας[13:55]{.aside}

και αι αδελφαι αυτου ουχι πασαι προς ημας [εισιν]{.greek-omitted} [εισι]{.greek-added} ποθεν ουν τουτω ταυτα παντα[13:56]{.aside}

και εσκανδαλιζοντο εν [αυτω]{.greek-omitted} [εαυτω]{.greek-added} ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη πατριδι αυτου και εν τη οικια αυτου[13:57]{.aside}

και ουκ εποιησεν εκει δυναμεις πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο τετραρχης την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και ειπεν τοις παισιν αυτου ουτος εστιν ιωαννης ο βαπτιστης [αυτος]{.greek-omitted} [ουτος]{.greek-added} ηγερθη απο των νεκρων και δια τουτο αι δυναμεις ενεργουσιν εν αυτω[14:2]{.aside}

ο γαρ ηρωδης κρατησας τον ιωαννην εδησεν αυτον και [εθετο]{.greek-omitted} [απεθετο]{.greek-added} εν [τη]{.greek-added} φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου[14:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω ο ιωαννης ουκ εξεστιν σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον [παντες]{.greek-added}[14:5]{.aside}

γενεσιων δε αγομενων του ηρωδου [ωρχησατο]{.greek-omitted} [ορχησατο]{.greek-added} η θυγατηρ της ηρωδιαδος εν τω μεσω και [ηρεσεν]{.greek-omitted} [ηρεσε]{.greek-added} τω ηρωδη[14:6]{.aside}

οθεν μεθ ορκου [ωμολογησεν]{.greek-omitted} [ομολογησεν]{.greek-added} αυτη δουναι ο εαν αιτησηται[14:7]{.aside}

η δε προβιβασθεισα υπο της [μητρος]{.greek-abbr} αυτης δος μοι φησιν ωδε επι πινακι την κεφαλην ιωαννου του βαπτιστου[14:8]{.aside}

και ελυπηθη ο βασιλευς δια δε τους ορκους και τους συνανακειμενους [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλησε]{.greek-added} τον ιωαννην εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι πινακι και εδοθη τω κορασιω και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το σωμα και εθαψαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} ανεχωρησεν [εκειθεν]{.greek-omitted} εν πλοιω εις ερημον τοπον κατ ιδιαν και ακουσαντες οι οχλοι ηκολουθησαν αυτω [πεζη]{.greek-omitted} [πεζοι]{.greek-added} απο των πολεων[14:13]{.aside}

και [εξελθων]{.greek-omitted} [εξηλθ[―]{.gap}]{.greek-added} [[εξηλθεν]{.corr}]{.greek-added} ο [ιησους]{.greek-abbr} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [πολ[―]{.gap}]{.greek-added} [πολυν]{.corr} οχλον και εσπλαγχνισθη επ [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} τους [αρρωστους]{.greek-omitted} [αρωστους]{.greek-added} αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται αυτου λεγοντες [αυτω]{.greek-added} ερημος [[―]{.gap}η]{.greek-added} [εστιν]{.corr} ο τοπος και η ωρα ηδη παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας [κωμας]{.greek-omitted} [κομας]{.greek-added} αγορασωσιν εαυτοις βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου χρειαν εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} φερετε μοι αυτους ωδε[14:18]{.aside}

και κελευσας τους οχλους ανακλιθηναι επι τους χορτους [και]{.greek-added} λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ηυλογησεν]{.greek-added} [αυτους]{.greek-added} και κλασας [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων δωδεκα κοφινους [πληρης]{.greek-added} [πληρεις]{.corr}[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες ωσει [πενταχι]{.greek-added} [πεντακισχιλιοι]{.corr} χωρις γυναικων και παιδιων[14:21]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας εμβηναι εις το πλοιον και προαγειν αυτον εις το περαν εως ου απολυση τους οχλους[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος κατ ιδιαν προσευξασθαι οψιας δε γενομενης μονος ην εκει[14:23]{.aside}

το δε [πλοιον]{.greek-omitted} [πλοιοι]{.greek-added} ηδη μεσον της θαλασσης ην βασανιζομενον [υπο]{.greek-omitted} [απο]{.greek-added} των κυματων ην γαρ εναντιος [ο]{.greek-omitted} ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς αυτους [ο]{.greek-omitted} [ιησους]{.greek-omitted} περιπατων επι της θαλασσης[14:25]{.aside}

και ιδοντες αυτον οι μαθηται επι [την]{.greek-omitted} [της]{.greek-added} [θαλασσαν]{.greek-omitted} [θαλασσης]{.greek-added} περιπατουντα εταραχθησαν λεγοντες οτι φαντασμα [εστιν]{.greek-omitted} [εστι]{.greek-added} και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} λεγων θαρσειτε εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} ει συ ει κελευσον με [ελθειν]{.greek-added} προς σε [ελθειν]{.greek-omitted} επι τα υδατα[14:28]{.aside}

ο δε ειπεν ελθε και καταβας απο του πλοιου ο πετρος περιεπατησεν επι τα υδατα [ελθειν]{.greek-omitted} [και]{.greek-added} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[14:29]{.aside}

βλεπων δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα επελαβετο αυτου και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω ελθοντες προσεκυνησαν αυτω λεγοντες αληθως [θεου]{.greek-abbr} υιος ει[14:33]{.aside}

και διαπερασαντες ηλθον [εις]{.greek-omitted} [επι]{.greek-added} την γην [εις]{.greek-added} γεννησαρετ[14:34]{.aside}

και επιγνοντες αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον [αψωνται]{.greek-omitted} [αψονται]{.greek-added} του κρασπεδου του ιματιου αυτου και [οσοι]{.greek-omitted} [ως]{.greek-added} ηψαντο διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτε προσερχονται τω [ιησου]{.greek-abbr} οι απο ιεροσολυμων γραμματεις και φαρισαιοι λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου [παραβαινουσιν]{.greek-omitted} [παραβαινουσι]{.greek-added} την παραδοσιν των πρεσβυτερων ου γαρ νιπτονται τας χειρας αυτων οταν αρτ[ο]{.unclear}ν εσθιωσιν[15:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και [υμ[―]{.gap}]{.greek-added} [υμεις]{.corr} παραβαινετε την εντολην του [θεου]{.greek-abbr} δια την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} ενετειλατο λεγων τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[15:4]{.aside}

υμεις δε λεγετε ος αν ειπη τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} δωρον ο εαν εξ εμου ωφεληθης [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[και]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [τιμησει]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [η]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} και ηκυρωσατε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:6]{.aside}

υποκριται καλως [προεφητευσεν]{.greek-omitted} [προεφητευσε]{.greek-added} περι υμων ησαιας λεγων[15:7]{.aside}

εγγιζει μοι ο λαος ουτος τω στοματι αυτων και τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[15:8]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις ακουετε και συνιετε[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} αλλα το εκπορευομενον εκ του στοματος τουτο κοινοι τον [ανθρωπον]{.greek-abbr}[15:11]{.aside}

τοτε προσελθοντες [αυτω]{.greek-added} οι μαθηται αυτου ειπον αυτω οιδας οτι οι φαρισαιοι ακουσαντες τον λογον εσκανδαλισθησαν[15:12]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πασα [φυτεια]{.greek-omitted} [φυτια]{.greek-added} ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο [ουρανιος]{.greek-abbr} εκριζωθησεται[15:13]{.aside}

αφετε αυτους [τυφλοι]{.greek-added} [εισιν]{.greek-added} οδηγοι [εισιν]{.greek-omitted} [τυφλοι]{.greek-omitted} τυφλων τυφλος δε τυφλον εαν οδηγη αμφοτεροι εις βοθυνον πεσουνται[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω [φρασον]{.greek-omitted} [φρασσον]{.greek-added} ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν ακμην και υμεις ασυνετοι εστε[15:16]{.aside}

ουπω νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ της καρδιας εξερχεται κακεινα κοινοι τον [ανθρωπον]{.greek-abbr}[15:18]{.aside}

εκ γαρ της καρδιας εξερχονται διαλογισμοι πονηροι φονοι [μοιχειαι]{.greek-omitted} [μοιχιαι]{.greek-added} πορνειαι κλοπαι ψευδομαρτυριαι βλασφημιαι[15:19]{.aside}

ταυτα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr} [το]{.greek-omitted} [δε]{.greek-omitted} [ανιπτοις]{.greek-omitted} [χερσιν]{.greek-omitted} [φαγειν]{.greek-omitted} [ου]{.greek-omitted} [κοινοι]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[15:20]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα μερη τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη [χαναναια]{.greek-omitted} [χαναια]{.greek-added} απο των οριων εκεινων εξελθουσα [εκραυγασεν]{.greek-omitted} [εκραυγαζεν]{.greek-added} αυτω λεγουσα ελεησον με [κυριε]{.greek-abbr} υιε [δαυιδ]{.greek-abbr} η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην ει μη εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

η δε ελθουσα προσεκυνησεν αυτω λεγουσα [κυριε]{.greek-abbr} βοηθει μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν [ουκ]{.greek-omitted} [ου]{.greek-added} [καλον]{.greek-added} εστιν [καλον]{.greek-omitted} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε ειπεν ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των [ψιχιων]{.greek-omitted} [ψυχιων]{.greek-added} των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη ω γυναι μεγαλη σου η πιστις γενηθητω σοι ως [θελεις]{.greek-omitted} [θελης]{.greek-added} και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος εκαθητο εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι [πολο]{.greek-added} [πολλοι]{.corr} εχοντες μεθ εαυτων χωλους [κωφους]{.greek-added} τυφλους [κωφους]{.greek-omitted} κυλλους και ετερους πολλους και ερριψαν αυτους παρα τους ποδας του [ιησου]{.greek-abbr} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε [τους]{.greek-omitted} [οχλους]{.greek-omitted} [τον]{.greek-added} [οχλον]{.greek-added} θαυμασαι βλεποντας κωφους λαλουντας κυλλους υγιεις [και]{.greek-added} χωλους περιπατουντας και τυφλους βλεποντας και [εδοξασαν]{.greek-omitted} [εδοξαζον]{.greek-added} τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου ειπεν [αυτοις]{.greek-added} σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχωσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} και απολυσαι αυτους νηστεις ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν [εν]{.greek-omitted} [ερημια]{.greek-omitted} [επ]{.greek-added} [ερημω]{.greek-added} [τοπω]{.greek-added} αρτοι τοσουτοι ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} [οχλοις]{.greek-omitted} [οχλους]{.greek-added} αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις αυτου οι δε μαθηται τω οχλω[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας πληρεις[15:37]{.aside}

οι δε εσθιοντες ησαν τετρακισχιλιοι ανδρες χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους [ενεβη]{.greek-omitted} [ανεβη]{.greek-added} εις το πλοιον και ηλθεν εις τα ορια μαγδαλα[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε ευδια [πυρραζει]{.greek-omitted} [πυραζει]{.greek-added} γαρ ο [ουρανος]{.greek-abbr}[16:2]{.aside}

και [πρωι]{.greek-omitted} [πρωιας]{.greek-added} σημερον χειμων [πυρραζει]{.greek-omitted} [πυραζει]{.greek-added} γαρ στυγναζων ο [ουρανος]{.greek-abbr} υποκριται το μεν προσωπον του [ουρανου]{.greek-abbr} [διακρινειν]{.greek-added} γινωσκετε [διακρινειν]{.greek-omitted} τα δε σημεια των καιρων ου [δυνασθε]{.greek-omitted} [γινωσκετε]{.greek-added}[16:3]{.aside}

γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} αυτους [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν επελαθοντο αρτους λαβειν[16:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ορατε και προσεχετε απο της ζυμης των φαρισαιων και σαδδουκαιων[16:6]{.aside}

οι δε διελογιζοντο εν εαυτοις λεγοντες οτι αρτους ουκ ελαβομεν[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτοις]{.greek-omitted} τι διαλογιζεσθε εν εαυτοις ολιγοπιστοι οτι αρτους ουκ ελαβετε[16:8]{.aside}

ουπω νοειτε ουδε [μνημονευετ[―]{.gap}]{.greek-added} [μνημονευετε]{.corr} τους πεντε αρτους των πεντακισχιλιων και ποσους κοφινους ελαβετε[16:9]{.aside}

ουδε τους επτα αρτους των τετρακισχιλιων και ποσας σπυριδας ελαβετε[16:10]{.aside}

πως ου νοειτε οτι [ου]{.corr} [περι]{.greek-omitted} [υπερ]{.greek-added} αρτου ειπον [υμιν]{.corr} προσεχειν [αλλα]{.greek-added} απο της ζυμης των φαρισαιων και σαδδουκαιων[16:11]{.aside}

τοτε συνηκαν οτι ουκ ειπεν προσεχειν απο της ζυμης του αρτου αλλα απο της διδαχης των φαρισαιων [και]{.greek-omitted} [σαδδουκαιων]{.greek-omitted}[16:12]{.aside}

ελθων δε ο [ιησους]{.greek-abbr} εις τα μερη καισαρειας της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι τον υιον του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον [ο]{.unclear}ι μεν ιωαννην τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λεγει αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} υμεις δε τινα με λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος ειπεν συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτω μακαριος ει σιμων βαριωνα οτι σαρξ και αιμα ουκ απεκαλυψεν σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις [ουρανοις]{.greek-abbr}[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι [τη]{.greek-added} ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι αδου ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν τοις [ουρανοις]{.greek-abbr} και ο εαν λυσης επι της γης εσται λελυμενον εν τοις [ουρανοις]{.greek-abbr}[16:19]{.aside}

τοτε διεστειλατο τοις μαθηταις αυτου ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} δεικνυειν τοις μαθηταις αυτου οτι δει αυτον απελθ[ει]{.unclear}ν εις ιεροσολυμα και πολλα παθειν απο των πρεσβυτερων και αρχιερεων και γραμματεων και αποκτανθηναι και τη τριτη ημερα [εγερθηναι]{.greek-omitted} [αναστηναι]{.greek-added}[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος [ηρξατο]{.greek-omitted} επιτιμαν [αυτον]{.greek-added} [αυτω]{.corr} [λεγων]{.greek-omitted} [και]{.greek-added} [λεγειν]{.greek-added} ιλεως σοι [κυριε]{.greek-abbr} ου μη εσται σοι τουτο[16:22]{.aside}

ο δε στραφεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω πετρω υπαγε οπισω μου σατανα σκανδαλον μου ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ει τις [θελη]{.greek-added} [θελει]{.corr} οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[16:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [θελη]{.greek-omitted} [θελει]{.greek-added} την ψυχην αυτου σωσαι απολεσει [[απωλεσει]{.corr}]{.greek-added} αυτην ος δ αν [απολεση]{.greek-omitted} [απωλεσει]{.greek-added} την ψυχην αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι γαρ ωφελειται [ανθρωπος]{.greek-abbr} εαν τον κοσμον ολον κερδηση την δε ψυχην αυτου ζημιωθη η τι δωσει [ανθρωπος]{.greek-abbr} [ανταλαγμα]{.greek-added} [ανταλλαγμα]{.corr} της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο υιος του [ανθρωπου]{.greek-abbr} ερχεσθαι εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων αυτου και τοτε αποδωσει εκαστω κατα την [πραξιν]{.greek-omitted} [ταξιν]{.greek-added} αυτου[16:27]{.aside}

αμην λεγω υμιν [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες [των]{.greek-added} ωδε [εστωτες]{.greek-omitted} [εστωτων]{.greek-added} οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} [ερχομενον]{.greek-omitted} εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και ιωαννην τον αδελφον αυτου και αναφερει αυτους εις ορος υψηλον κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και [ελαμψεν]{.greek-omitted} [ελαμψε]{.greek-added} το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου εγενοντο λευκα ως το φως[17:2]{.aside}

και ιδου ωφθησαν αυτοις [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ηλιας μετ αυτου [συλαλουντες]{.greek-added} [συλλαλουντες]{.corr} [[συλαλουντες]{.corr}]{.greek-added}[17:3]{.aside}

αποκριθεις δε ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω [ιησου]{.greek-abbr} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι ει θελεις ποιησωμεν ωδε τρεις σκηνας σοι μιαν και μωση μιαν και [ηλια]{.greek-added} μιαν [ηλια]{.greek-omitted}[17:4]{.aside}

ετι αυτου λαλουντος ιδου νεφελη [φωτεινη]{.greek-omitted} [φωτινη]{.greek-added} επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο υιος μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added} αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται [αυτου]{.greek-added} [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν εγερθητε και μη φοβεισθε[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινοντων αυτων [εκ]{.corr} [του]{.corr} ορους ενετειλατο αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι ειπητε το οραμα εως ου ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[17:9]{.aside}

και επηρωτησαν αυτον οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν δει ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις ηλιας [μεν]{.corr} ερχεται πρωτον και αποκαταστησει παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας ηδη [ηλθεν]{.greek-omitted} [εληλυθε]{.greek-added} και ουκ επεγνωσαν αυτον αλλα εποιησαν [εν]{.greek-omitted} αυτω οσα ηθελησαν ουτως και ο υιος του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι ιωαννου του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον προσηλθεν αυτω [ανθρωπος]{.greek-abbr} γονυπετων αυτον[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι σεληνιαζεται και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και [προσηνεγκα]{.greek-omitted} [προσηνεγκαν]{.greek-added} αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν αυτον θεραπευσαι[17:16]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε [μεθ]{.greek-added} [ημων]{.greek-added} εσομαι [μεθ]{.greek-omitted} [υμων]{.greek-omitted} εως ποτε ανεξομαι υμων [φερετε]{.greek-omitted} [φερεται]{.greek-added} μοι αυτον ωδε[17:17]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε προσελθοντες οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν [εκβαλειν]{.greek-omitted} [εκβαλλειν]{.greek-added} αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην γαρ λεγω υμιν [οτι]{.greek-added} εαν εχητε πιστιν ως [κοκο]{.greek-added} [κοκκον]{.corr} σιναπεως [ερειτε]{.greek-omitted} [ερειται]{.greek-added} τω ορει τουτω μεταβηθι εντευθεν [εκει]{.greek-omitted} και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ εκπορευεται ει μη εν προσευχη και νηστεια[17:21]{.aside}

αναστρεφομενων δε αυτων εν τη γαλιλαια ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα [εγερθησεται]{.greek-omitted} [αναστησεται]{.greek-added} και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε αυτων εις καπερναουμ προσηλθον οι τα διδραχμα λαμβανοντες τω πετρω και ειπον ο διδασκαλος υμων ου τελει τα διδραχμα[17:24]{.aside}

[και]{.greek-added} λεγει ναι και οτε [εισηλθεν]{.greek-omitted} [ηλθον]{.greek-added} εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο [τινων]{.greek-omitted} [τινος]{.greek-added} [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} [τα]{.greek-added} τελη η κηνσον απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

λεγει αυτω ο πετρος απο των αλλοτριων εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις την θαλασσαν βαλε αγκιστρον και τον [αναβαινοντα]{.greek-omitted} [αναβαντα]{.greek-added} πρωτον ιχθυν αρον και ανοιξας το στομα αυτου ευρησεις στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ωρα προσηλθον [αυτω]{.greek-added} οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες τις αρα μειζων εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη στραφητε και γενησθε ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο ουτος εστιν ο μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος εαν δεξηται παιδιον τοιουτον [εν]{.greek-omitted} επι τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν σκανδαλιση ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος εις τον τραχηλον αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ [εστιν]{.greek-omitted} ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

ει δε η χειρ σου η ο πους σου σκανδαλιζει σε εκκοψον αυτα και βαλε απο σου καλον σοι εστιν εισελθειν εις την ζωην χωλον η κυλλον η δυο χειρας η δυο ποδας εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και ει [ο]{.greek-omitted} οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι εστιν μονοφθαλμον εις την ζωην εισελθειν η [τους]{.greek-added} δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

ορατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} το προσωπον του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο υιος του [ανθρωπου]{.greek-abbr} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει [ε]{.unclear}αν γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα ενενηκοντα εννεα επι τα ορη πορευθεις ζητει το πλανωμενον[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η επι τοις [ενε[―]{.gap}ηκοντα]{.greek-added} [ενενηκοντα]{.corr} εννεα τοις μη πεπλανημενοις[18:13]{.aside}

ουτως ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} θελημα εμπροσθεν του [πατρος]{.greek-abbr} [ημων]{.greek-added} [υμων]{.corr} του εν [ουρανοις]{.greek-abbr} ινα αποληται εις των μικρων τουτων[18:14]{.aside}

εαν δε [αμαρτηση]{.greek-omitted} [αμαρτησει]{.greek-added} εις σε ο αδελφος σου υπαγε [και]{.greek-omitted} ελεγξον αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη [σου]{.greek-added} ακουση παραλαβε μετα [σου]{.greek-omitted} [σεαυτου]{.greek-added} ετι [ενα]{.greek-omitted} [εναν]{.greek-added} η δυο ινα επι στοματος δυο μαρτυρων [σταθησεται]{.greek-added} [η]{.greek-omitted} [τριων]{.greek-omitted} [σταθη]{.greek-omitted} παν ρημα[18:16]{.aside}

εαν δε παρακουση αυτων ειπε τη εκκλησια εαν δε και της εκκλησιας παρακουση εστω σοι ωσπερ ο εθνικος και ο τελωνης[18:17]{.aside}

αμην [γαρ]{.greek-added} λεγω υμιν οσα εαν δησητε επι της γης εσται δεδεμενα εν τω [ουρανω]{.greek-abbr} και οσα εαν λυσητε επι της γης εσται λελυμενα εν τω [ουρανω]{.greek-abbr}[18:18]{.aside}

παλιν αμην λεγω υμιν οτι εαν δυο υμων [συμφωνησωσιν]{.greek-omitted} [συμφωνησουσιν]{.greek-added} επι της γης περι παντος πραγματος ου εαν [αιτησωνται]{.greek-omitted} [αιτησονται]{.greek-added} γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[18:19]{.aside}

ου γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο η τρεις συνηγμενοι εις το εμον ονομα εκει ειμι εν μεσω αυτων[18:20]{.aside}

τοτε προσελθων αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} ποσακις αμαρτησει [ο]{.greek-added} [εις]{.corr} εμε ο αδελφος μου και αφησω αυτω εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} [ε[―]{.gap}]{.greek-added} [ου]{.corr} λεγω σοι εως επτακις αλλ εως εβδομηκοντακις επτα[18:22]{.aside}

δια τουτο [ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος ηθελησεν συναραι λογον μετα των δουλων [αυτου]{.greek-omitted} [αυτων]{.greek-added}[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν [αυτον]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα ειχεν και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος [εκεινος]{.greek-added} προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} [μακροθυμησον]{.greek-omitted} [μακροθυμισον]{.greek-added} επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο [κυριος]{.greek-abbr} του δουλου εκεινου απελυσεν αυτον και το δανειον αφηκεν αυτω[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον δηναρια και κρατησας αυτον [επνιγεν]{.greek-omitted} [επνιγε]{.greek-added} λεγων αποδος μοι ει τι [οφειλεις]{.greek-omitted} [οφειλης]{.greek-added}[18:28]{.aside}

πεσων ουν ο συνδουλος αυτου εις τους ποδας αυτου παρεκαλει αυτον λεγων μακροθυμησον επ εμοι και [παντα]{.greek-added} [σοι]{.greek-added} αποδωσω [σοι]{.greek-omitted}[18:29]{.aside}

ο δε ουκ ηθελεν [αλλα]{.greek-omitted} [αλλ]{.greek-added} απελθων εβαλεν αυτον εις φυλακην εως ου αποδω το οφειλομενον[18:30]{.aside}

ιδοντες [δε]{.greek-omitted} οι συνδουλοι αυτου τα γενομενα ελυπηθησαν σφοδρα και ελθοντες διεσαφησαν τω [κυριω]{.greek-abbr} [εαυτων]{.greek-omitted} [αυτων]{.greek-added} παντα τα γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο [κυριος]{.greek-abbr} [αυτου]{.greek-omitted} λεγει αυτω δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι επει παρεκαλεσας με[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως και εγω σε ηλεησα[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} αυτου παρεδωκεν αυτον τοις βασανισταις εως ου αποδω παν το οφειλομενον αυτω[18:34]{.aside}

ουτως και ο [πατηρ]{.greek-abbr} μου ο [[ουνοος]{.greek-abbr}]{.greek-added} [επουρανιος]{.greek-omitted} [[[ουρανιος]{.greek-abbr}]{.corr}]{.greek-added} ποιησει υμιν εαν μη αφητε εκαστος τω αδελφω αυτου απο των καρδιων υμων τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και [οκολουθησαν]{.greek-added} [ηκολουθησαν]{.corr} αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και προσηλθον αυτω οι φαρισαιοι πειραζοντες αυτον και λεγοντες [αυτω]{.greek-omitted} ει εξεστιν [ανθρωπω]{.greek-abbr} [α[―]{.gap}πολυσαι]{.greek-added} [απολυσαι]{.corr} την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ ανεγνωτε οτι ο ποιησας απ [αρχης]{.greek-omitted} [αρχεις]{.greek-added} αρσεν και θηλυ εποιησεν αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταλιψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-added} και την [μητερα]{.greek-abbr} και προσκολληθησεται τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ενετειλατο δουναι βιβλιον αποστασιου και απολυσαι αυτην[19:7]{.aside}

λεγει αυτοις οτι [μωσης]{.greek-omitted} [μωυσης]{.greek-added} προς την σκληροκαρδιαν υμων επετρεψεν υμιν απολυσαι τας γυναικας υμων απ αρχης δε ου γεγονεν ουτως[19:8]{.aside}

λεγω δε υμιν [οτι]{.greek-omitted} ος [αν]{.greek-omitted} [εαν]{.greek-added} απολυση την γυναικα [αυτου]{.greek-omitted} [εαυτου]{.greek-added} μη επι πορνεια [ποιει]{.greek-added} [αυτην]{.greek-added} [μοιχευθηναι]{.greek-added} [και]{.greek-omitted} [γαμηση]{.greek-omitted} [αλλην]{.greek-omitted} [μοιχαται]{.greek-omitted} και ο απολελυμενην [γαμησας]{.greek-omitted} [γαμων]{.greek-added} μοιχαται[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτως εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφερει γαμησαι[19:10]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτοις ου παντες [χωρουσιν]{.greek-omitted} [χωρουσι]{.greek-added} τον λογον τουτον αλλ οις δεδοται[19:11]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ ευνουχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} εγεννηθησαν ουτως [και]{.corr} [εισιν]{.corr} [ευνουχοι]{.corr} [οιτινες]{.corr} [ευνουχισθησαν]{.corr} [υπο]{.corr} [των]{.corr} [[ανθρωπων]{.greek-abbr}]{.corr} και εισιν ευνουχοι οιτινες [ευνουχισαν]{.greek-omitted} [ευνουχησαν]{.greek-added} εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε προσηνεχθη αυτω παιδια ινα τας χειρας επιθη αυτοις και [προσευξ[οι]{.unclear}ται]{.greek-added} [προσευξηται]{.corr} οι δε μαθηται [επετιμησ[ει]{.unclear}]{.greek-added} [επετιμησαν]{.corr} αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε τα παιδια και μη [κωλυετε]{.greek-omitted} [κολυετε]{.greek-added} αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και επιθεις [αυτοις]{.greek-omitted} τας χειρας [αυτοις]{.greek-added} επορευθη εκειθεν[19:15]{.aside}

και ιδου [εις]{.greek-omitted} [τις]{.greek-added} προσελθων ειπεν αυτω διδασκαλε αγαθε τι αγαθον ποιησω [ιν]{.greek-added} [ινα]{.corr} εχω ζωην αιωνιον[19:16]{.aside}

ο δε ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr} ει δε [θελης]{.greek-added} [θελεις]{.greek-omitted} [εισελθειν]{.greek-omitted} εις την ζωην [εισελθειν]{.greek-added} τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το ου φονευσεις ου μοιχευσεις [ου]{.corr} [κλεψεις]{.corr} ου [ψευδομαρτυρησεις]{.greek-omitted} [ψευδομαρτυρισεις]{.greek-added} [ου]{.greek-added} [κλεψεις]{.greek-added}[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} και την [μητερα]{.greek-abbr} και [αγαπησεις]{.greek-omitted} τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[19:19]{.aside}

λεγει αυτω ο νεανισκος παντα ταυτα εφυλαξαμην εκ νεοτητος μου τι ετι υστερω [εγω]{.greek-added}[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελεις τελειος ειναι υπαγε πωλησον σου τα υπαρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι [αρας]{.greek-added} [τον]{.greek-added} [[σταυρον]{.greek-abbr}]{.greek-added}[19:21]{.aside}

ακουσας δε ο νεανισκος [τουτον]{.greek-added} τον λογον απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως πλουσιος εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν δε λεγω υμιν [οτι]{.greek-added} ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} [καμηλον]{.greek-omitted} [καμιλον]{.greek-added} δια [τρυπηματος]{.greek-omitted} [τρυμαλιας]{.greek-added} ραφιδος [διελθειν]{.greek-omitted} η [πλουσιο[―]{.gap}]{.greek-added} [πλουσιον]{.corr} [εισελθειν]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} [εισελθειν]{.greek-omitted}[19:24]{.aside}

ακουσαντες δε οι μαθηται αυτου εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

εμβλεψας δε [ο]{.greek-omitted} [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα δε [θεω]{.greek-abbr} παντα δυνατα[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν [καθιση]{.greek-omitted} [καθισει]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου [καθισεσθε]{.greek-omitted} [καθησεσθε]{.greek-added} και [υμεις]{.greek-omitted} [αυτοι]{.greek-added} επι δωδεκα θρονους κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας [ος]{.greek-omitted} [οστις]{.greek-added} αφηκεν οικιας η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν του ονοματος μου εκατονταπλασιονα ληψεται και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[19:30]{.aside}

### Chapter 20

[ομοι]{.greek-added} [ομοια]{.corr} γαρ εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

[και]{.greek-omitted} συμφωνησας [δε]{.greek-added} μετα των εργατων εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι τριτην ωραν [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

[και]{.greek-omitted} [εκεινοις]{.greek-omitted} [κακεινοις]{.greek-added} ειπεν υπαγετε και υμεις εις τον αμπελωνα [μου]{.greek-added} και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε [απηλθον]{.greek-omitted} [απηλθαν]{.greek-added} παλιν εξελθων περι [την]{.greek-added} εκτην [και]{.greek-omitted} [ενατην]{.greek-omitted} ωραν εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο λεγει αυτοις υπαγετε και υμεις εις τον αμπελωνα [μου]{.greek-added} και ο εαν η δικαιον [ληψεσθε]{.greek-omitted} [λημψεσθε]{.greek-added}[20:7]{.aside}

οψιας δε γενομενης λεγει ο κυριος του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι πλειονα [ληψονται]{.greek-omitted} [λημψονται]{.greek-added} και ελαβον και αυτοι ανα δηναριον[20:10]{.aside}

λαβοντες δε εγογγυζον κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι ουτοι [οι]{.greek-omitted} [εσχατην]{.greek-added} [εσχατοι]{.corr} μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις [βαστασασιν]{.greek-omitted} [βαστασασι]{.greek-added} το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν [ενι]{.greek-omitted} αυτων εταιρε ουκ αδικω σ[ε]{.unclear} ουχι δηναριου συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω εσχατω δουναι ως και [συ]{.greek-added} [σοι]{.corr}[20:14]{.aside}

η ουκ εξεστιν μοι ποιησαι ο θελω εν τοις εμοις [ει]{.greek-omitted} [η]{.greek-added} ο οφθαλμος σου πονηρος εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι και οι πρωτοι εσχατοι πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

και [αναβαινων]{.greek-omitted} [αναβαινον]{.greek-added} ο [ιησους]{.greek-abbr} εις ιεροσολυμα παρελαβεν τους δωδεκα μαθητας κατ ιδιαν εν τη οδω και ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω[20:18]{.aside}

και παραδωσουσιν αυτον τοις [εθνεσι]{.greek-added} [εθνεσιν]{.corr} εις το εμπ[αι]{.unclear}ξαι [[εμπεξαι]{.corr}]{.greek-added} και μαστιγωσαι και [σταυρωσαι]{.greek-abbr} και τη τριτη ημερα αναστησεται[20:19]{.aside}

τοτε προσηλθεν αυτω [ο]{.greek-added} [η]{.corr} [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων [αυτης]{.greek-omitted} [αυτοις]{.greek-added} προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι θελεις λεγει αυτω ειπε ινα [καθισωσιν]{.greek-omitted} [καθησουσιν]{.greek-added} ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω μελλω πινειν η το βαπτισμα ο εγω βαπτιζομαι [βαπτισθηναι]{.greek-omitted} [βαπτισθειναι]{.greek-added} λεγουσιν αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον [μου]{.greek-omitted} πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε το δε [καθησαι]{.greek-added} [καθισαι]{.corr} εκ δεξιων μου και εξ ευωνυμων μου ουκ εστιν εμον [τουτο]{.greek-added} δουναι αλλ οις ητοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριευσουσιν]{.greek-added} αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως [δε]{.greek-omitted} εσται εν υμιν αλλ ος εαν θελη [μεγας]{.greek-added} [γενεσθαι]{.greek-added} εν υμιν [μεγας]{.greek-omitted} [γενεσθαι]{.greek-omitted} εσται υμων διακονος[20:26]{.aside}

και ος εαν θελη εν υμιν ειναι πρωτος [εστω]{.greek-omitted} [υμων]{.greek-omitted} [εσται]{.greek-added} [παντων]{.greek-added} δουλος[20:27]{.aside}

ωσπερ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και εκπορευομενων αυτων απο ιεριχω [ηκολουθ[―]{.gap}]{.greek-added} [ηκολουθησεν]{.corr} αυτω οχλος πολυς[20:29]{.aside}

και [ιδου]{.greek-omitted} δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

ο δε οχλος επετιμησεν αυτοις ινα σιωπησωσιν [οι]{.corr} [δε]{.corr} [μειζον]{.corr} [εκραζον]{.greek-omitted} [εκραξαν]{.greek-added} λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-abbr} εφωνησεν αυτους και [ειπει]{.greek-added} [ειπεν]{.greek-omitted} [[ειπε]{.corr}]{.greek-added} τι θελετε ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-abbr} ινα [ανοιχθωσιν]{.greek-omitted} [ανοιγωσιν]{.greek-added} ημων οι οφθαλμοι[20:33]{.aside}

σπλαγχνισθεις δε ο [ιησους]{.greek-abbr} [[―]{.gap}ψατο]{.greek-added} [ηψατο]{.corr} των οφθαλμων αυτων και ευθεως ανεβλεψαν αυτων οι οφθαλμοι και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε ηγγισαν εις ιεροσολυμα και ηλθον εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} [και]{.greek-added} [βηθανιαν]{.greek-added} προς το ορος των ελαιων τοτε ο [ιησους]{.greek-abbr} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} δυο μαθητας[21:1]{.aside}

λεγων αυτοις πορευθητε εις την κωμην την απεναντι υμων και ευθεως ευρησετε ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι [ερειτε]{.greek-omitted} [ρρειτε]{.greek-added} οτι ο κυριος αυτων χρειαν εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον και πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται [και]{.greek-omitted} [ποιησαντες]{.greek-omitted} [εποιησαν]{.greek-added} καθως προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

[και]{.greek-added} ηγαγον την ονον και τον πωλον και επεθηκαν επανω αυτων τα ιματια αυτων και επεκαθισεν επανω αυτων[21:7]{.aside}

ο δε πλειστος οχλος εστρωσαν [εαυτων]{.greek-omitted} τα ιματια [αυτων]{.greek-added} εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} [ευλογημενος]{.greek-omitted} [ευλογιμενος]{.greek-added} ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα [εσεισθη]{.greek-omitted} [εστεισθη]{.greek-added} πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-omitted} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

και εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον του [θεου]{.greek-abbr} και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} παντας τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο οικος μου οικος προσευχης κληθησεται υμεις δε αυτον εποιησατε σπηλαιον ληστων[21:13]{.aside}

και προσηλθον αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

[και]{.greek-added} ιδοντες [δε]{.greek-omitted} οι αρχιερεις και οι γραμματεις τα θαυμασια α [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων κατηρτισω αινον[21:16]{.aside}

και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη εκει[21:17]{.aside}

πρωιας δε επαναγων εις την πολιν [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει μη φυλλα μονον και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη [παραχρημα]{.greek-omitted} η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν εχητε πιστιν και μη [διακριθηται]{.greek-added} [διακριθητε]{.corr} ου μονον το της συκης [ποιησετε]{.greek-omitted} [ποιησητε]{.greek-added} αλλα καν τω ορει τουτω ειπητε αρθητι και βληθητι εις την θαλασσαν γενησεται[21:21]{.aside}

και παντα οσα [εαν]{.greek-omitted} [αν]{.greek-added} αιτησητε εν τη προσευχη πιστευοντες [ληψεσθε]{.greek-omitted} [λημψεσθε]{.greek-added}[21:22]{.aside}

και ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις [συ]{.greek-added} [σοι]{.corr} [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω [καγω]{.greek-added} υμας [καγω]{.greek-omitted} [ενα]{.greek-added} λογον [ενα]{.greek-omitted} ον εαν ειπητε μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα ιωαννου ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο παρ εαυτοις λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει ημιν δια τι ουν ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον ιωαννην ως προφητην[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} ειπον ουκ οιδαμεν εφη [αυτοις]{.greek-omitted} και αυτος ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} [τις]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} τεκνα δυο και προσελθων τω πρωτω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι [μου]{.greek-omitted}[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε [μεταμεληθεις]{.greek-omitted} [μεταμελιθεις]{.greek-added} απηλθεν [[απηλθε]{.corr}]{.greek-added}[21:29]{.aside}

και προσελθων τω [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν ωσαυτως ο δε αποκριθεις ειπεν [ε]{.unclear}γω [κυριε]{.greek-abbr} και ουκ [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:30]{.aside}

τις εκ των δυο [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} το θελημα του [πατρος]{.greek-abbr} [αυτων]{.greek-added} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και [αι]{.corr} πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ [ιωαννης]{.greek-added} προς υμας [ιωαννης]{.greek-omitted} εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω οι δε τελωναι και αι πορναι επιστευσαν αυτω [υμεις]{.corr} [δε]{.corr} [ιδοντες]{.corr} [ου]{.corr} [μετεμεληθη[τ]{.greek-supplied}[ε]{.unclear}]{.corr} [υστερ[ο]{.unclear}[ν]{.greek-supplied}]{.corr} [του]{.corr} [πιστευσαι]{.corr} [αυτω]{.corr}[21:32]{.aside}

αλλην παραβολην ακουσατε [ανθρωπος]{.greek-abbr} [τις]{.greek-omitted} ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} και ωρυξεν εν αυτω ληνον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε ηγγισεν ο καιρος των καρπων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους τον υιον αυτου λεγων εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λ[α]{.unclear}βοντες αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα εκδωσεται αλλοις γεωργοις οιτινες [ασποδωσουσιν]{.greek-added} [αποδωσουσιν]{.corr} αυτω τους καρπους εν τοις καιροις αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε ανεγνωτε εν ταις γραφαις λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις [ημων]{.greek-omitted} [υμων]{.greek-added}[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται [εθνει]{.greek-omitted} [εθνη]{.greek-added} ποιουντι τους καρπους [αυτης]{.greek-omitted} [αυτου]{.greek-added}[21:43]{.aside}

και ακουσαντες οι αρχιερεις και οι φαρισαιοι [τας]{.greek-omitted} [[1]{.greek-supplied}ην]{.greek-added} [[την]{.corr}]{.greek-added} [παραβολας]{.greek-omitted} [παραβολην]{.greek-added} αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους [επειδη]{.greek-omitted} [επει]{.greek-added} [ως]{.greek-omitted} [εις]{.greek-added} προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-abbr} παλιν ειπεν αυτοις εν παραβολαις λεγων[22:1]{.aside}

[ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω αυτου[22:2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον [μου]{.greek-omitted} ητοιμασα οι ταυροι μου και τα σιτιστα [τεθυμενα]{.greek-omitted} [τεθημενα]{.greek-added} και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους [δολους]{.greek-added} [δουλους]{.corr} αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος ωργισθη και πεμψας τα στρατευματα αυτου [απωλεσεν]{.greek-omitted} [απωλεσε]{.greek-added} τους φονεις εκεινους και την πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενεπρησε]{.greek-added}[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε [δουλοι]{.greek-added} κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον παντας ο[σ]{.unclear}ους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος [των]{.greek-added} ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε [εφιμωθη]{.greek-omitted} [εφημωθη]{.greek-added}[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου ποδας και χειρας αρατε αυτον και [εκβαλετε]{.greek-omitted} [βαλετε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον ελαβον οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου [μελει]{.greek-omitted} [μελλε]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι κηνσον καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων ειπεν [[ειπε]{.corr}]{.greek-added} τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του κηνσου οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις αποδοτε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι [οι]{.greek-omitted} λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης ειπεν εαν τις αποθανη μη εχων τεκνα [επι]{.greek-added} [επιγαμβρευσει]{.greek-omitted} [γαμβρευσει]{.greek-added} ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος [γαμησας]{.greek-omitted} [γημας]{.greek-added} [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και μη εχων σπερμα [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} την γυναικα [αυτου]{.greek-omitted} τω αδελφω αυτου[22:25]{.aside}

ομοιως [δε]{.greek-added} και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων απεθανεν [και]{.greek-omitted} η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε [γαμιζονται]{.greek-added} [εκγαμιζονται]{.greek-omitted} [[εγγαμιζονται]{.corr}]{.greek-added} αλλ [[―]{.gap}σιν]{.greek-added} [[εισιν]{.corr}]{.greek-added} ως [οι]{.greek-added} αγγελοι [του]{.greek-omitted} [θεου]{.greek-omitted} εν [τω]{.greek-added} [ουρανω]{.greek-abbr} [εισιν]{.greek-omitted}[22:30]{.aside}

περι δε της [αναστασεως]{.greek-omitted} [εξαναστασεως]{.greek-added} των νεκρων ουκ [α]{.unclear}νεγνωτε το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-omitted} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημωσε]{.greek-added} τους σαδδουκαιους συνηχθησαν επι το αυτο[22:34]{.aside}

[και]{.greek-added} [επηρωτησεν]{.greek-added} και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} [εφη]{.greek-omitted} [ειπεν]{.greek-added} αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη εστιν πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα [δε]{.greek-omitted} ομοια [αυτη]{.greek-omitted} [αὐτῆ]{.greek-added} [αγαπησης]{.greek-added} [αγαπησεις]{.corr} τον πλησιον σου [ω]{.unclear}ς [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} κυριον αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} καλει αυτον [κυριον]{.greek-abbr} πως υιος αυτου εστιν [ει]{.greek-added} [ουν]{.greek-added} [[δαυιδ]{.greek-abbr}]{.greek-added} [καλει]{.greek-added} [αυτον]{.greek-added} [[κυριον]{.greek-abbr}]{.greek-added} [πως]{.greek-added} [υιος]{.greek-added} [αυτου]{.greek-added} [εστι]{.greek-added}[22:45]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [εδυνηθη]{.greek-added} αυτω αποκριθηναι λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι [και]{.greek-added} [ουδεις]{.greek-added} [εδυν[1-2]{.greek-supplied}το]{.greek-added} [[εδυνατο]{.corr}]{.greek-added} [αυτω]{.greek-added} [αποκριθηναι]{.greek-added} [λογον]{.greek-added} [ουδε]{.greek-added} [ετολμησε]{.greek-added} [τις]{.greek-added} [απ]{.greek-added} [εκεινης]{.greek-added} [της]{.greek-added} [ημερας]{.greek-added} [επερωτησαι]{.greek-added} [αυτον]{.greek-added} [ουκετι]{.greek-added}[22:46]{.aside}

### Chapter 23

τοτε [ο]{.greek-omitted} [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου [τοτε]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ελαλησε]{.greek-added} [τοις]{.greek-added} [οχλοις]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [μαθηταις]{.greek-added} [αυτου]{.greek-added}[23:1]{.aside}

[λεγων]{.greek-added} [επι]{.greek-added} [της]{.greek-added} [μωσεως]{.greek-added} [καθεδρας]{.greek-added} λεγων επι της μωσεως καθεδρας εκαθισαν οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και ποιειτε κατα δε τα εργα αυτων μη ποιειτε [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} γαρ φορτια βαρεα και δυσβαστακτα και [επιτιθεασιν]{.greek-omitted} [επιτιθεασι]{.greek-added} επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} [δε]{.greek-omitted} [γαρ]{.greek-added} τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα [σκρασπεδα]{.greek-added} [κρασπεδα]{.corr} των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} τε την πρωτοκλισιαν εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και [τους]{.greek-omitted} [τοις]{.greek-added} [ασπασμους]{.greek-omitted} [ασπασμοις]{.greek-added} εν ταις [αγοραις]{.greek-omitted} [αγωραις]{.greek-added} και [το]{.greek-added} καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι [ραββι]{.greek-omitted}[23:7]{.aside}

υμεις δε μη κληθητε ραββι εις γαρ εστιν υμων ο [διδασκαλος]{.greek-added} [καθηγητης]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-abbr} [παντες]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [αδελφοι]{.greek-omitted} [εστε]{.greek-omitted}[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε υμων επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} [υμεις]{.greek-added} [δε]{.greek-added} [παντες]{.greek-added} [αδελφοι]{.greek-added} [εστε]{.greek-added}[23:9]{.aside}

[μηδε]{.greek-omitted} [μη]{.greek-added} κληθητε καθηγηται εις γαρ υμων [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και [φαρισ[σ]{.unclear}αιοι]{.greek-added} [φαρισαιοι]{.corr} υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλιετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χειρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι περιαγετε την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν γενηται ποιειτε αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν ομοση εν τω ναω ουδεν εστιν ος δ αν ομοση εν τω χρυσω του ναου οφειλει[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος εαν ομοση εν τω θυσιαστηριω ουδεν εστιν ος δ αν ομοση εν τω δωρω τω [[το[υ]{.unclear}]{.corr}]{.greek-added} επανω αυτου οφειλει[23:18]{.aside}

μωροι [[μ[ο]{.unclear}ροι]{.corr}]{.greek-added} και τυφλοι τι γαρ μειζον το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο [ομοσας]{.greek-omitted} [ομασας]{.greek-added} εν τω ναω ομνυει εν αυτω και εν τω [κατοικησαντι]{.greek-omitted} [κατοικο[υν]{.unclear}τι]{.greek-added} [αυτον]{.greek-omitted} [εν]{.greek-added} [αυτω]{.greek-added}[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το [κυμιο]{.greek-added} [κυμινον]{.corr} και [αφηκατε]{.greek-omitted} [αφιετε]{.greek-added} τα βαρυτερα του νομου την κρισιν και τον ελεον και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι [υποκριται]{.greek-omitted} οτι καθαριζετε [το]{.greek-omitted} [τω]{.greek-added} εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και αδικιας[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι παρομοιαζετε ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

ουτως και υμεις εξωθεν μεν φαινεσθε τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι εστε υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι οικοδομειτε τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει [ημεν]{.greek-omitted} [ημεθα]{.greek-added} εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν [ημεν]{.greek-omitted} [ημεθα]{.greek-added} κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω [προφη]{.greek-added} [προς]{.greek-omitted} [υμας]{.greek-omitted} [προφητας]{.corr} και σοφους και γραμματεις και εξ αυτων [α[σ]{.unclear}ποκτενειτε]{.greek-added} [αποκτενειτε]{.corr} και [σταυρωσετε]{.greek-abbr} και εξ αυτων μαστιγωσετε εν ταις συναγωγαις υμων και διωξετε απο πολεως εις πολιν[23:34]{.aside}

οπως ελθη εφ [[η]{.unclear}μας]{.greek-added} [υμας]{.corr} παν αιμα δικαιον εκχυνομενον επι της γης απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου υιου βαραχιου ον εφονευσατε [με[π]{.unclear}αξυ]{.greek-added} [μεταξυ]{.corr} του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η αποκτενουσα τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα [σου]{.greek-omitted} [του]{.greek-added} ον τροπον επισυναγει ορνις [τα]{.greek-omitted} [τω]{.greek-added} νοσσια [[νοσια]{.corr}]{.greek-added} εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου [αφιεται]{.greek-omitted} [αφιετε]{.greek-added} υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη με ιδητε απ [αρτι]{.greek-omitted} [αρτη]{.greek-added} εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτου επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου βλεπετε παντα ταυτα αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου [καταλυθησεται]{.greek-omitted} [κατηλυθησεται]{.greek-added}[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται [αυτου]{.greek-added} κατ ιδιαν λεγοντες ειπε [[υ]{.unclear}μιν]{.greek-added} [[η]{.unclear}μιν]{.corr} ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added}[24:5]{.aside}

μελλησετε δε ακουειν πολεμους και ακοας πολεμων ορατε μη θροεισθε δει γαρ παντα γενεσθαι αλλ [ουπω]{.greek-omitted} [εστιν]{.greek-omitted} [ουκ]{.greek-added} [ευθεως]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και [λοιμοι]{.greek-omitted} [λιμοι]{.greek-added} και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη ωδινων[24:8]{.aside}

τοτε παραδωσουσιν υμας εις [θλιψιν]{.greek-omitted} [θλιψεις]{.greek-added} και αποκτενουσιν [[αποκτεννουσιν]{.corr}]{.greek-added} υμας και εσεσθε μισουμενοι υπο παντων [των]{.greek-omitted} [εθνων]{.greek-omitted} δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} και [μισησι]{.greek-added} [μισησουσιν]{.corr} αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν [ψυγησεται]{.greek-omitted} [ψηγησεται]{.greek-added} η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται τουτο το ευαγγελιον της βασιλειας εν ολη τη οικουμενη εις μαρτυριον [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν [ιδητε]{.greek-omitted} [ειδητε]{.greek-added} το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου εστως εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν επι τα ορη[24:16]{.aside}

ο επι του δωματος μη καταβαινετω αραι τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω [εις]{.greek-added} [τα]{.greek-added} οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων [εν]{.greek-added} [χειμωνος]{.greek-omitted} [χειμωνι]{.greek-added} μηδε σαββατω[24:20]{.aside}

εσται γαρ τοτε [θλιψεις]{.greek-added} [θλιψις]{.corr} μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν ουδ ου μη γενηται[24:21]{.aside}

και ει μη [εκολοβωθησαν]{.greek-omitted} [εκολοβοθησαν]{.greek-added} αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλ[ε]{.unclear}κτους [κολοβωθησονται]{.greek-omitted} [κολοβοθησονται]{.greek-added} αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια μεγαλα και τερατα ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} υμιν ιδου εν τη ερημω [εστιν]{.greek-omitted} [εστι]{.greek-added} μη εξελθητε ιδου εν τοις ταμειοις μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και [φαινεται]{.greek-omitted} [φαινετε]{.greek-added} εως δυσμων ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ εαν η το πτωμα εκει συναχθησονται [και]{.greek-added} οι αετοι[24:28]{.aside}

ευθεως [δε]{.greek-omitted} [ουν]{.greek-added} μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και [τοτε]{.greek-omitted} κοψονται πασαι αι φυλαι της γης και οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου μετα σαλπιγγος φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξουσι]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος αυτης γενηται απαλος και τα [φυλλα]{.greek-omitted} [φυλα]{.greek-added} εκφυη γινωσκετε οτι εγγυς το θερος[24:32]{.aside}

ουτως και υμεις οταν ιδητε ταυτα παντα γινωσκετε οτι εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} επι θυραις[24:33]{.aside}

αμην λεγω υμιν [ο]{.unclear}υ μη παρελθη η γενεα αυτη εως αν παντα [ταυτα]{.greek-omitted} γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσ[εται]{.unclear}]{.greek-added} [παρελευσονται]{.corr} οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[24:35]{.aside}

περι δε της ημερας εκεινης και [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [των]{.greek-omitted} [ουρανων]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται [και]{.greek-omitted} η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις προ του κατακλυσμου τρωγοντες και πινοντες γαμουντες και εκγαμιζοντες αχρι ης ημερας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο αληθουσαι εν τω μυλωνι μια παραλαμβανεται και μια αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει ηδει ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν [ειασεν]{.greek-omitted} [αφηκεν]{.greek-added} διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετο[ι]{.unclear}μοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της θεραπειας αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο κυριος αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος [εν]{.greek-omitted} [τη]{.greek-omitted} [καρδια]{.greek-omitted} [αυτου]{.greek-omitted} χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [εσθιειν]{.greek-omitted} [εσθιη]{.greek-added} δε και [πινειν]{.greek-omitted} [πινη]{.greek-added} μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυ[―]{.gap}]{.greek-added} [κυριος]{.corr} του δουλου εκεινου εν ημερ[α]{.unclear} η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και [[―]{.gap}χο[ρ]{.unclear}ομησει]{.greek-added} [[δ]{.unclear}ιχοτομησει]{.corr} αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των [μετα]{.greek-added} [των]{.greek-added} λαμπαδων αυτων[25:4]{.aside}

[χρ[ω]{.unclear}νιζοντος]{.greek-added} [χρ[ο]{.unclear}νιζοντος]{.corr} δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε ημιν εκ του ελαιου υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε ουκ αρκεση ημιν και υμιν πορευεσθε δε [μαλλον]{.corr} προς τους πωλουντας [μαλλον]{.greek-added} και αγορασατε [εαυτ[ες]{.unclear}]{.greek-added} [εαυταις]{.corr}[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ [αυτου]{.greek-omitted} [αυτων]{.greek-added} εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι [λι]{.greek-added} [λοιπαι]{.corr} παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν εν η ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο [εκερδησεν]{.greek-omitted} [εκερδησε]{.greek-added} και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν [εν]{.greek-omitted} τη γη και [απεκρυψεν]{.greek-omitted} [απεκρυψε]{.greek-added} το αργυριον του κυριου αυτου[25:18]{.aside}

μετα δε χρονον [πολυν]{.greek-omitted} [πολυ]{.greek-added} ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και συναιρει μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι [παρεδω[―]{.gap}ας]{.greek-added} [παρεδωκας]{.corr} ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη [δε]{.greek-omitted} αυτω ο κυριος αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ [αυτ[η]{.unclear}]{.greek-added} [αυτοις]{.corr}[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του κυριου σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [[ιησους]{.greek-abbr}]{.greek-added} [[κυριος]{.greek-abbr}]{.corr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε ηδεις οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις [τραπεζιταις]{.greek-omitted} [τραπεζηταις]{.greek-added} και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον εκβαλετε εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των [οδοντων]{.greek-omitted} [οδωντων]{.greek-added}[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε καθισει επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και [εδωκατε]{.greek-omitted} [εδοκατε]{.greek-added} μοι φαγειν [εδηψησα]{.greek-added} [εδιψησα]{.corr} και εποτισατε με ξενος ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και επεσκεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε [[―]{.gap}ε]{.greek-added} [σε]{.corr} ειδομεν [πεινωντα]{.greek-omitted} [πεινοντα]{.greek-added} και [εθρεψαμ[1-2]{.greek-supplied}ν]{.greek-added} [εθρεψαμεν]{.corr} η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και συνηγαγομεν η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων [των]{.corr} ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το [σταυρωθηναι]{.greek-abbr}[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω κρατησωσιν και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν [επ[ε]{.unclear}]{.greek-added} [επι]{.corr} [την]{.greek-omitted} [της]{.greek-added} [κεφαλην]{.greek-omitted} [κεφαλης]{.greek-added} αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους παρεχετε τη γυναικι εργον γαρ καλον ειργασατο εις εμε[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} τους πτωχους [γαρ]{.greek-added} [παντοτε]{.greek-added} εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το [ενταφιασε]{.greek-added} [ενταφιασαι]{.corr} με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε μοι δουναι καγω υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που [θελεις]{.greek-omitted} [θελης]{.greek-added} [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα[26:20]{.aside}

και εσθιοντων αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω τρυβλιω την χειρα ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδοτε]{.greek-added} καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε [ο]{.greek-added} ιουδας ο παραδιδους αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μητι εγω ειμι ραββι λεγει αυτω συ ειπας[26:25]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του [γεννηματος]{.greek-omitted} [γενηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν αυτο πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις σκανδαλισθησεσθε εν εμοι εν τη [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} ταυτη γεγραπται γαρ παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω δε ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον γεθσημανη και λεγει τοις μαθηταις καθισατε αυτου εως ου απελθων [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added} εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και [αναστας]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [προσευχης]{.greek-added} ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται τουτο το ποτηριον παρελθειν απ εμου εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων ευρισκει αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον[26:48]{.aside}

κα[ι]{.unclear} ευθεως προσελθων τω [ιησου]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} χαιρε ραββι και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ [ω]{.greek-omitted} [ο]{.greek-added} παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [του]{.greek-added} [ιησου]{.greek-abbr} εκτεινας την χειρα [απεσπασεν]{.greek-omitted} [απεσπασε]{.greek-added} την μαχαιραν αυτ[ου]{.unclear} και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον σου την μαχαιραν εις τον [τον]{.greek-added} τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν μαχαιρα αποθανουνται[26:52]{.aside}

η δοκεις οτι ου δυναμαι αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ [εκρατησατε]{.greek-omitted} [εκρατησετε]{.greek-added} με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος [ηκολουθει]{.greek-omitted} [ηκολουθησεν]{.greek-added} αυτω απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και το συνεδριον ολον εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως θανατωσωσιν αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματια αυτου λεγων οτι [εβλασφημησεν]{.greek-omitted} [εβλασφημησε]{.greek-added} τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου [εστιν]{.greek-omitted} [εστι]{.greek-added}[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και [εκολαφισαν]{.greek-omitted} [εκολαφησαν]{.greek-added} αυτον οι δε ερραπισαν[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν αυτων παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει αυτοις εκει και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου [δηλον]{.corr} [σε]{.corr} [ποιει]{.corr}[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ εφωνησεν[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος του [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν αυτον ποντιω [πιλατω]{.greek-omitted} [πηλατω]{.greek-added} τω ηγεμονι[27:2]{.aside}

τοτε ιδων ιουδας ο παραδιδους αυτον οτι κατεκριθη μεταμεληθεις [απεστρεψεν]{.greek-omitted} [επεστρεψεν]{.greek-added} τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτερο[ις]{.unclear}[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε ειπον τι προς ημας συ οψει[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω ανεχωρησεν και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον κορβαναν επει τιμη αιματος [εστιν]{.greek-omitted} [εστι]{.greek-added}[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο [και]{.greek-added} εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα [συνεταξεν]{.greek-omitted} [συνεταξε]{.greek-added} μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και των πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ [α]{.greek-added} [ακουεις]{.greek-omitted} [κουεις]{.greek-added} ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και ουκ [α]{.unclear}πεκριθη αυτω προς [ουδε]{.greek-omitted} [ουδ]{.greek-added} εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον [επισημον]{.greek-omitted} [επισημο]{.greek-added} λεγομενον βαραββαν[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν βαραββαν η ιησουν τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα [αιτησωνται]{.greek-omitted} [αιτησονται]{.greek-added} τον βαραββαν τον δε [ιησουν]{.greek-abbr} [απο[λ]{.unclear}λεσωσιν]{.greek-added} [απολεσωσιν]{.corr}[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε [α[―]{.gap}]{.greek-added} [απο]{.corr} των δυο απολυσω υμιν οι δε ειπον [βαββαν]{.greek-added} [βαραββαν]{.corr}[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν αυτω παντες [σταυρωθητω]{.greek-abbr}[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες [σταυρωθητω]{.greek-abbr}[27:23]{.aside}

ιδων δε ο πιλατος οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν [αυτοις]{.greek-omitted} τον [βαραββαν]{.greek-omitted} [βαρββαν]{.greek-added} τον δε ιησουν [φραγελλωσας]{.greek-omitted} [φραγελωσας]{.greek-added} παρεδωκεν ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και γονυπετησαντες εμπροσθεν αυτου ενεπαιζον [αυτω]{.greek-omitted} [αυτον]{.greek-added} λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγομενος κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} πιειν[27:34]{.aside}

[σταυρωσαντες]{.greek-abbr} δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

[και]{.corr} καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν [επν]{.greek-added} [επανω]{.corr} της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-omitted} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουντε]{.greek-added} [σταυρουνται]{.corr} συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} καταβηθι απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως δε και οι αρχιερεις εμπαιζοντες μετα των γραμματεων και πρεσβυτερων και φαρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω νυν αυτον ει θελει αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι [συσταυρωθεντες]{.greek-abbr} αυτω ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας [εγενετο]{.greek-added} σκοτος [εγενετο]{.greek-omitted} επι πασαν την γην εως ωρας ενατης[27:45]{.aside}

περι δε την ενατην ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι [λιμα]{.greek-omitted} [λειμα]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβαχθανει]{.greek-added} τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελιπες[27:46]{.aside}

τινες δε των [ε[―]{.gap}ει]{.greek-added} [εκει]{.corr} εστωτων ακουσαντες ελεγον οτι ηλιαν φωνει ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας [σωσων]{.greek-omitted} [και]{.greek-added} [σωσει]{.greek-added} αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη εσεισθη και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια ανεωχθησαν και πολλα σωματα των κεκοιμ[η]{.unclear}μενων αγιων [ηγερθη]{.greek-omitted} [ηγερθησαν]{.greek-added}[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον ιησουν ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} υιος ην ουτος[27:54]{.aside}

ησαν δε εκει [και]{.greek-added} γυναικες πολλαι απο μακροθεν θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η μαγδαληνη και μαρια η του ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ ος και αυτος [εμαθητευσεν]{.greek-omitted} [εμαθητευσε]{.greek-added} τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω [ητησατο]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [τοτε]{.greek-omitted} [ο]{.greek-omitted} [πιλατος]{.greek-omitted} εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων [αυτο]{.greek-added} [το]{.greek-omitted} [σωμα]{.greek-omitted} ο ιωσηφ ενετυλιξεν αυτο σινδονι καθαρα[27:59]{.aside}

και [εθηκεν]{.greek-omitted} [εθεκεν]{.greek-added} αυτο εν τω καινω αυτου μνημειω ο [[ω]{.corr}]{.greek-added} ελατομησεν εν τη πετρα και προσκυλισας λιθον μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η μαγδαληνη και η αλλη μαρια καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς πιλατον[27:62]{.aside}

λεγοντες κυριε εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου νυκτος κλεψωσιν αυτον και [ειπωσιν]{.greek-omitted} [τω]{.greek-omitted} [λαω]{.greek-omitted} [ηγερθη]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [και]{.greek-omitted} εσται η εσχατη πλανη [χειρων]{.greek-omitted} [χειρον]{.greek-added} της πρωτης[27:64]{.aside}

εφη δε αυτοις ο πιλατος εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε δε σαββατων τη επιφωσκουση εις μιαν σαββατων [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} μαρια η μαγδαληνη και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} προσελθων [απεκυλισεν]{.greek-omitted} [απεκυλισε]{.greek-added} τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο [δε]{.greek-omitted} του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} μη [φοβησθε]{.greek-added} [φοβεισθε]{.corr} υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον [εσταυρωμενον]{.greek-abbr} ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ [πορευθεισαι]{.greek-omitted} [πορευθησαι]{.greek-added} ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

[ως]{.greek-omitted} [δε]{.greek-omitted} [επορευοντο]{.greek-omitted} [απαγγειλαι]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} και ιδου [ιησους]{.greek-abbr} απηντησεν αυταις λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} [απαντα]{.greek-omitted} [παντα]{.greek-added} τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

[λεγοντες]{.greek-omitted} ειπατε οτι οι μαθηται αυτου νυκτος ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις [πεισωμεν]{.greek-added} [πεισομεν]{.corr} αυτον και υμας αμεριμνους ποιησομεν[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως [εδια]{.greek-added} [εδιδαχθησαν]{.corr} και διεφημισθη ο λογο[ς]{.unclear} ουτος παρα ιουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

