---
title: "Collation of Byz^RP^ vs 30295 (295)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 295 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30295).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 295                                   	| λογος                              	|
| 295 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 295 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 295               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 295                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 295 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 295                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

βιβλος [γενεσεως]{.greek-omitted} [γενεως]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [υ]{.unclear}ιου [δαυιδ]{.greek-omitted} [δαβιδ]{.greek-added} [υιου]{.greek-omitted} [υου]{.greek-added} αβρ[α]{.unclear}[α]{.unclear}μ[1:1]{.aside}

αβρααμ [εγεννησεν]{.greek-omitted} [εγενν[η]{.unclear}σε]{.greek-added} τον ισαακ ισαακ [δε]{.greek-supplied} [εγεννησεν]{.greek-omitted} [[ε]{.unclear}γεννησε]{.greek-added} τον ιακωβ [ι]{.greek-supplied}ακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ι]{.unclear}[ου]{.greek-supplied}δαν και τους αδελφ[ους]{.greek-supplied} [α]{.unclear}υτου[1:2]{.aside}

ιουδας δε [εγεννησεν]{.greek-omitted} [εγεν[ν]{.unclear}ησε]{.greek-added} τον φαρες και [τ]{.greek-supplied}ον ζαρα εκ της θ[α]{.greek-supplied}[μ]{.greek-supplied}αρ φαρες δε [εγεν[νη]{.greek-supplied}]{.greek-added} [[ε]{.unclear}γεννη]{.greek-added} [εγεννησεν]{.greek-omitted} [[[ε]{.unclear}γεννησε]{.corr}]{.greek-added} τον εσρωμ εσρ[ωμ]{.greek-supplied} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αραμ[1:3]{.aside}

[α]{.greek-supplied}ραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμ[ιν]{.greek-supplied}αδαβ αμιναδαβ δε [εγεννησεν]{.greek-omitted} [ε[γεν]{.greek-supplied}νησε]{.greek-added} τον ναασσων να[ασσων]{.greek-supplied} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλ[μων]{.greek-supplied}[1:4]{.aside}

σαλμων δε εγεννη[σ]{.unclear}[εν]{.greek-supplied} τον βοοζ εκ της ραχ[αβ]{.greek-supplied} βοοζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τ]{.unclear}[ον]{.greek-supplied} ωβηδ εκ της ρουθ [ω]{.unclear}βηδ δε [εγεννησεν]{.greek-omitted} [εγεννη]{.greek-added} τον ι[ε]{.greek-supplied}σσαι[1:5]{.aside}

ιεσσαι δε [εγεννησεν]{.greek-omitted} [εγεν[νη]{.greek-supplied}σε]{.greek-added} τον [δαυιδ]{.greek-omitted} [δαβιδ]{.greek-added} τον βασ[ιλεα]{.greek-supplied} [δαυιδ]{.greek-abbr} δε ο βασιλευς [εγεννησεν]{.greek-omitted} [εγε[ν]{.greek-supplied}νησε]{.greek-added} τον σολομωνα ε[κ]{.greek-supplied} [τ]{.greek-supplied}ης του ουριου[1:6]{.aside}

σολομων δε [εγεννησεν]{.greek-omitted} [[εγ]{.greek-supplied}εννησε]{.greek-added} τον ροβοαμ ροβ[ο]{.greek-supplied}[α]{.greek-supplied}μ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [αβια]{.greek-omitted} [αβια]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} [τον]{.greek-omitted} [ασα]{.greek-omitted}[1:7]{.aside}

[ασα]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} τον ιωσ[αφατ]{.greek-supplied} [ι]{.greek-supplied}ωσαφατ δε [εγεννησεν]{.greek-omitted} [εγεννησ[ε]{.greek-supplied}]{.greek-added} [τον]{.greek-supplied} [ι]{.greek-supplied}[ω]{.unclear}ραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγενν[η]{.unclear}[σε]{.greek-supplied}]{.greek-added} [τ]{.unclear}ον [οζιαν]{.greek-omitted} [οζια]{.greek-added}[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγενν[ησε]{.greek-supplied}]{.greek-added} [τ]{.unclear}ον ιωαθαμ ιωαθαμ [δε]{.greek-supplied} [εγεννησεν]{.greek-omitted} [[ε]{.greek-supplied}γεννησε]{.greek-added} τον αχαζ αχ[αζ]{.greek-supplied} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εζ[ε]{.greek-supplied}[κ]{.greek-supplied}ιαν[1:9]{.aside}

εζεκιας δε [εγεννησεν]{.greek-omitted} [εγενν[η]{.greek-supplied}[σ]{.greek-supplied}ε]{.greek-added} τον μανασση μαν[α]{.unclear}[σσης]{.greek-supplied} [δ]{.greek-supplied}ε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμω[ν]{.unclear} [α]{.unclear}μων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τ[ον]{.greek-supplied} [ι]{.greek-supplied}ωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγε[ν]{.greek-supplied}[ν]{.greek-supplied}ησε]{.greek-added} τον ιεχονιαν και τους αδελφους αυτου επι της μετοικεσιας βαβυ[λ]{.unclear}[ω]{.greek-supplied}νος[1:11]{.aside}

μετα δε την [μετοικεσιαν]{.greek-omitted} [μετ[οι]{.greek-supplied}]{.greek-added} [κεσιας]{.greek-added} βαβυλωνος ιεχονιας [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλαθιηλ σαλ[α]{.unclear}θιηλ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβιουδ αβιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιακειμ ελιακειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [αζωρ]{.greek-omitted}[1:13]{.aside}

[αζωρ]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [αχειμ]{.greek-omitted} [αχειμ]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελεαζαρ ελεαζαρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

πασαι ουν [αι]{.greek-omitted} γενεαι απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεαι [δεκατεσσαρες]{.greek-omitted} [δεκατεσερες]{.greek-added} και απο [δαυιδ]{.greek-abbr} εως της μετοικεσιας βαβυλωνος γενεαι δεκατεσσαρες [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μετοικεσιας]{.greek-omitted} [βαβυλωνος]{.greek-omitted} [εως]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [γενεαι]{.greek-omitted} [δεκατεσσαρες]{.greek-omitted}[1:17]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην μνηστευθεισης γαρ της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν η συνελθειν αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην παραδειγματισαι εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

τ[αυτ]{.unclear}α δε αυτου [ενθυμηθεντος]{.greek-omitted} [ενθυμηθεντες]{.greek-added} ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ εφανη αυτω λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη φοβηθης παραλαβειν [μαριαμ]{.greek-omitted} [μαριαν]{.greek-added} την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

τεξεται δε υιον και καλεσεις το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ [σωσει]{.greek-omitted} [σωσοι]{.greek-added} τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται υιον και [καλεσουσιν]{.greek-omitted} [καλεσουσι]{.greek-added} το ονομα αυτου εμμανουηλ ο εστιν μεθερμηνευομενον μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε ο ιωσηφ [απο]{.greek-omitted} [α]{.greek-added} του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου ετεκεν τον υιον αυτης τον πρωτοτοκον και [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

[τ]{.greek-supplied}ου δε [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} γεννηθεντος εν βηθλεεμ της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων ειδομεν γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι αυτω[2:2]{.aside}

ακουσας δε ηρωδης ο βασιλευς εταραχθη και πασα ιεροσολυμ[α]{.unclear} [[ιερουσαλυμ]{.corr}]{.greek-added} μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και γραμματεις του λαου επυνθανετο παρ [αυτων]{.greek-omitted} [αυτου]{.greek-added} που ο [χριστος]{.greek-abbr} γενναται[2:4]{.aside}

οι δε ειπον αυτω εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ουδαμως ελαχιστη ει εν τοις ηγεμοσιν ιουδα εκ σου γαρ εξελευσεται ηγουμενος οστις ποιμανει τον λαον [μου]{.corr} τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησ[ω]{.unclear} αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλε[ως]{.greek-supplied} [ε]{.greek-supplied}πορευθησαν και ιδου ο αστηρ ον [ει]{.greek-supplied}δον εν τη ανατολη προηγεν [α]{.unclear}[υ]{.greek-supplied}τους εως ελθων εστη επανω [ο]{.unclear}[υ]{.greek-supplied} ην το παιδιον[2:9]{.aside}

ιδοντες δε τον α[στε]{.greek-supplied}ρα εχαρησαν χαραν μεγαλην σφοδ[ρα]{.greek-supplied}[2:10]{.aside}

και ελθοντες εις την οικιαν ειδον το [π]{.unclear}[αι]{.greek-supplied}διον μετα μαριας της [μητρος]{.greek-abbr} αυτο[υ]{.unclear} και πεσοντες προσεκυνησαν αυτω [και]{.greek-supplied} ανοιξαντες τους θησαυρους αυτων [προσηνεγκαν]{.greek-omitted} [προσυνεγκαν]{.greek-added} αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και [χρηματισθεντες]{.greek-omitted} κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδου αγγελος [κυριου]{.greek-abbr} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης [ζητην]{.greek-added} [ζητειν]{.corr} το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις [αιγυπτον]{.greek-omitted} [αι]{.greek-added}[2:14]{.aside}

### Chapter 4

[γη]{.greek-omitted} [ζαβουλων]{.greek-omitted} [και]{.greek-omitted} [γη]{.greek-omitted} [νεφθαλειμ]{.greek-omitted} [οδον]{.greek-omitted} [θαλασσης]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} [γαλιλαια]{.greek-omitted} [λιλαια]{.greek-added} των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει ειδεν φως μεγα [και]{.greek-supplied} [τοις]{.greek-omitted} [της]{.greek-added} καθημενοις εν χωρα και σκια θανατου φως ανετειλεν [αυ]{.greek-supplied}τοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} [κηρυσσειν]{.greek-omitted} [κηρυσσον]{.greek-added} και λεγειν [[λεγων]{.corr}]{.greek-added} μετανοειτε ηγγικε[ν]{.unclear} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

πε[ρι]{.greek-supplied}πατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} δυο αδελφους σιμωνα τον λεγομενον πετρον και ανδρεαν τον α[δ]{.unclear}ελ[φ]{.unclear}ον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω υμας αλιεις [ανθρωπων]{.greek-omitted} [ανθρωπον]{.greek-added}[4:19]{.aside}

[οι]{.greek-omitted} [ι]{.greek-added} δε ευθεως αφεντες [τα]{.greek-omitted} [το]{.greek-added} [δικτυα]{.greek-omitted} [δικτυον]{.greek-added} ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν ειδεν αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας τα δικτυα αυτων και εκαλεσεν αυτους[4:21]{.aside}

οι δε ευθεως αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων [ηκολουθησαν]{.greek-omitted} [ηκουλουθησαν]{.greek-added} αυτω[4:22]{.aside}

και περιηγεν ολην την γαλιλαιαν ο [ιησους]{.greek-abbr} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν [νοσον]{.greek-omitted} [νοσων]{.greek-added} και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και απηλθεν η [ακοη]{.greek-omitted} [ακωη]{.greek-added} αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και βασανοις συνεχομενους και [δαιμονιζομενους]{.greek-omitted} [δεμονιζομενους]{.greek-added} [και]{.greek-omitted} [σεληνιαζομενους]{.greek-omitted} και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

[και]{.greek-omitted} ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και [ιεροσολυμων]{.greek-omitted} [ιεροσολυμον]{.greek-added} και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον [αυτω]{.greek-omitted} οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους λεγων[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν η [βασιλεια]{.greek-omitted} [βασι]{.greek-added} [λεια]{.greek-added} των [ουρανων]{.greek-abbr}[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθησονται[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομησουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι πεινωντες και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

[μ]{.greek-supplied}ακαριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι [οι]{.greek-added} εστε οταν ονειδισωσιν υμας και [διωξωσιν]{.greek-omitted} [διωξωσι]{.greek-added} και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις [ουρανοις]{.greek-abbr} [ουτως]{.greek-omitted} [ουτος]{.greek-added} γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το [α]{.greek-added} [αλας]{.greek-omitted} [λας]{.greek-added} της γης εαν δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι ει μη β[λη]{.unclear}θηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους [κειμενη]{.greek-omitted} [κειμενει]{.greek-added}[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και [τιθεασιν]{.greek-omitted} [τεθεασιν]{.greek-added} αυτον υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει πασιν τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων εμπροσθεν των [ανθρωπων]{.greek-abbr} οπως ιδωσιν υμων τα καλα εργα και [δοξασωσιν]{.greek-omitted} [δοξασωσι]{.greek-added} τον [πατερα]{.greek-abbr} υμων τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πλ[η]{.unclear}ρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η [μια]{.greek-omitted} [μηα]{.greek-added} κεραια ου μη παρελθη απο του νομου εως αν παντα γενηται[5:18]{.aside}

ος εαν ουν λυση μιαν των [εντολων]{.greek-omitted} [τουτων]{.greek-omitted} [των]{.greek-omitted} ελαχιστων και [διδαξη]{.greek-omitted} [διδαξει]{.greek-added} ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [ποιηση]{.greek-omitted} [και]{.greek-omitted} [διδαξη]{.greek-omitted} [ουτος]{.greek-omitted} [μεγας]{.greek-omitted} [κληθησεται]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted}[[5:19 *(lacunose)*]{.lacunose}]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση [υμων]{.greek-added} η δικαιοσυνη [υμων]{.greek-omitted} πλειον των γραμματεων και φαρισαιων ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν φονευση ενοχος εσται τη κρισει[5:21]{.aside}

[εγω]{.greek-omitted} [δε]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οργιζομενος]{.greek-omitted} [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [αυτου]{.greek-omitted} [εικη]{.greek-omitted} [ενοχος]{.greek-omitted} [εσται]{.greek-omitted} [τη]{.greek-omitted} [κρισει]{.greek-omitted} ος δ αν ειπη τω αδελφω αυτου ρακα ενοχος εσται τω συνεδριω ος [δ]{.greek-supplied} αν ειπη μωρε ενοχος εσται εις την [γεεναν]{.greek-added} [γεενναν]{.corr} του πυρος[5:22]{.aside}

εαν ουν προσφερης το [δωρον]{.greek-omitted} [δωρων]{.greek-added} [σου]{.greek-omitted} επι το θυσιαστηριον και εκει μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου [μ]{.greek-supplied}ηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην βληθηση[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως αν αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε [οτι]{.greek-omitted} ερρεθη ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων [γυναικα]{.greek-omitted} [γυναικαν]{.greek-added} προς το επιθυμησαι αυτην ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

[ει]{.greek-omitted} [ι]{.greek-added} δε ο οφθαλμος σου ο δεξιος σκανδαλιζει σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ σκανδαλιζει σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και [μη]{.greek-omitted} [μ[οι]{.unclear}]{.greek-added} ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη δε [οτι]{.greek-omitted} ος [δ]{.greek-added} αν απολυση την γυναικα αυτου [δοτω]{.greek-omitted} [δοτο]{.greek-added} αυτη αποστασιον[5:31]{.aside}

εγω δε λεγω υμιν οτι ος αν απολυση την γυναικα αυτου παρεκτος λογου [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} ποιει αυτην [μοιχασθαι]{.greek-omitted} [μοιχασθηναι]{.greek-added} και ος εαν απολελυμενην γαμηση μοιχαται[5:32]{.aside}

[παλιν]{.greek-omitted} [παλλιν]{.greek-added} ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις [αποδωσεις]{.greek-omitted} [αποδωσει]{.greek-added} δε [τω]{.greek-omitted} [τωι]{.greek-added} [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη ομοσαι ολως μητε εν τω ουρανω οτι θρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον [εστιν]{.greek-omitted} [εστι]{.greek-added} των ποδων αυτου μητε εις ιεροσολυμα οτι πολις εστιν του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου ομοσης οτι ου δυνασαι μιαν [τριχα]{.greek-omitted} [τριχαν]{.greek-added} λευκην η μελαιναν ποιησαι[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου εστιν[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστην[αι]{.unclear} τω π[ο]{.unclear}νηρω αλλ οστις σε ραπισει επι την δεξιαν [σου]{.greek-added} σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και τω θελοντι σοι κριθηναι και τον χιτωνα σου λαβειν αφες αυτω και το ιματιον[5:40]{.aside}

και οστις σε [αγγαρευσει]{.greek-omitted} [αγγαρευει]{.greek-added} μιλι[ον]{.unclear} εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω [αιτουντι]{.greek-omitted} [ετουντι]{.greek-added} σε διδου και τον θελοντα απο σου δανεισασθαι μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και μισησεις τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων ευλογειτε τους καταρωμενους υμας [καλως]{.greek-omitted} [καλος]{.greek-added} [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} τοις μισουσιν υμας και [προσευχεσθε]{.greek-omitted} [προσσευχεσθε]{.greek-added} υπερ των [επηρεαζοντων]{.greek-omitted} [πηρεαζοντων]{.greek-added} υμας και διωκοντων υμας[5:44]{.aside}

οπως γενησθε υιοι του [πατρος]{.greek-abbr} υμων του εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} οτι τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ αγαπησητε τους αγαπωντας υμας τινα μισθον εχετε ουχι και [οι]{.greek-omitted} [η]{.greek-added} [τελωναι]{.greek-omitted} [τελωνε]{.greek-added} το αυτο [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[5:46]{.aside}

και εαν ασπασησθε τους φιλους υμων μονον τι περισσον ποιειτε ουχι και οι τελ[ω]{.unclear}ναι [ο]{.unclear}υτως ποιουσιν[5:47]{.aside}

εσεσθε ουν υμεις τελειοι ωσπερ ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} τελειος εστιν[5:48]{.aside}

### Chapter 6

προσεχετε την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν ποιης ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} [α]{.greek-supplied}μην λεγω υμιν [οτι]{.greek-added} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω [κρυπτω]{.greek-omitted} [κριπτω]{.greek-added} και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω [κρυπτω]{.greek-omitted} [κριπτω]{.greek-added} [αυτος]{.greek-omitted} αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται οτι φιλουσιν εν ταις συναγωγαις και εν ταις γωνιαις των πλατειων εστωτες προσευχεσθαι οπως αν [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το ταμιειον σου και κλεισας την θυραν σου προσευξαι τω [πατρι]{.greek-abbr} [σου]{.greek-omitted} τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη [βατολογησητε]{.greek-added} [βαττολογησητε]{.corr} ωσπερ οι εθνικοι [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν ομοιωθητε αυτοις [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} υμων ων χρειαν εχετε προ του υμας αιτησαι αυτον[6:8]{.aside}

ουτως ουν προσευχεσθε υμεις [πατερ]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} ο εν τοις [ουρανοις]{.greek-abbr} αγιασθ[ητω]{.greek-supplied} το ονομα σου[6:9]{.aside}

ελθετω η βασ[ι]{.greek-supplied}λεια σου γενηθητω το θελη[μ]{.unclear}[α]{.greek-supplied} σου ως εν [ουρανω]{.greek-abbr} και επι της γ[ης]{.greek-supplied}[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων ως και ημεις αφιεμεν τοις οφειλεταις ημων[6:12]{.aside}

και μη εισενεγκης ημας εις πειρ[ασ]{.greek-supplied}μον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια [κ]{.unclear}αι η δυναμις και η δοξα εις τους αιωνας αμην[6:13]{.aside}

εαν γαρ [αφητε]{.greek-omitted} [αφι[η]{.unclear}[τε]{.greek-supplied}]{.greek-added} τοις ανθρωποις τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων αφησει τα παραπτωματα υμων[6:15]{.aside}

οταν δε νηστευητε μη γινεσθε ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην [αμην]{.greek-added} λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων αλειψαι σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι[6:18]{.aside}

μη θησαυριζετε υμιν θησαυρους επι της γης οπου σης και βρωσις αφανιζει και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορυσσουσι]{.greek-added} και [κλεπτουσιν]{.greek-omitted} [κλεπτουσι]{.greek-added}[6:19]{.aside}

θησαυριζετε δε υμιν [θησαυρους]{.greek-omitted} [θυσαυρους]{.greek-added} εν [ουρανω]{.greek-abbr} οπου ουτε σης [ο]{.unclear}υτε βρωσις αφανιζει και οπου κλεπται ου διορυσσουσιν ουδε κλεπτουσιν[6:20]{.aside}

οπου γαρ εστιν ο θησαυρος υμων εκει εσται [και]{.unclear} η καρδια υμων[6:21]{.aside}

[ο]{.greek-omitted} λυχνος του [σωματος]{.greek-omitted} [σοματος]{.greek-added} εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους η ολον το σωμα σου φωτεινον εσται[6:22]{.aside}

εαν δε [ο]{.greek-supplied} οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος [εστιν]{.greek-omitted} [εστι]{.greek-added} το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η [του]{.greek-added} ενος ανθεξεται και του ετερου καταφρονησει ου [δυ]{.greek-added} [δυνασθε]{.greek-omitted} [νασθε]{.greek-added} [θεω]{.greek-abbr} δουλευειν και μαμωνα[6:24]{.aside}

δια τουτο λεγω υμιν μη μεριμνατ[ε]{.greek-supplied} τη ψυχη υμων τι φαγητε και τι πιητε μηδε τω σωματι υμων τι ενδυσησθ[ε]{.greek-supplied} ουχι η ψυχη πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα πετεινα του [ουρανου]{.greek-abbr} οτι ου σπειρουσιν ουδε θεριζουσιν ουδε συναγουσιν εις [τ]{.greek-added} [αποθηκας]{.corr} και ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} τρεφει αυτα ουχ υμεις μαλλον διαφερετε αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται προσθειναι επι την ηλικιαν αυτου πηχ[υν]{.greek-supplied} ενα[6:27]{.aside}

και περι ενδυματος τι μεριμ[να]{.greek-supplied}τε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε νηθει[6:28]{.aside}

λεγω δε υμιν οτι ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον [βαλλομενον]{.greek-omitted} [καταβαλλομενον]{.greek-added} ο [θεος]{.greek-abbr} ουτως αμφιεννυσιν ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μ[η]{.unclear} ουν μεριμνησητε λεγοντες τι [φαγωμεν]{.greek-omitted} [φαγ[ω]{.unclear}]{.greek-added} [μεν]{.greek-added} η τι πιωμεν η τι [περιβαλωμεθα]{.greek-omitted} [περιβαλλομεθα]{.greek-added}[6:31]{.aside}

παντα γαρ ταυτα τα εθνη επι[ζ]{.unclear}ητει [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} οτι χρηζετε τουτων απαντων[6:32]{.aside}

ζητειτε δε πρωτον την βασιλειαν του [θεου]{.greek-abbr} και την δικαιοσυνην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν μεριμνησητε εις την αυριον [η]{.greek-supplied} γαρ αυριον μεριμνησει [τα]{.greek-omitted} εαυτης αρκετον τη ημερα η κακια [αυτης]{.greek-omitted} [εαυτης]{.greek-added}[6:34]{.aside}

### Chapter 7

[μ]{.greek-supplied}η κρινετε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε κριθησεσθε και εν ω μετρω μετρειτε μετρηθησεται υμιν[7:2]{.aside}

τι δε [βλεπ[―]{.gap}]{.greek-added} [βλεπεις]{.corr} το [καρφος]{.corr} [το]{.greek-omitted} εν τω [οφθαλμω]{.greek-omitted} [οφθαμω]{.greek-added} του αδελφου σου την δε εν τω σω οφθαλμω δοκον ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος [απο]{.greek-omitted} [εκ]{.greek-added} του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του [αδελφου]{.greek-omitted} [αδελ]{.greek-added} [φου]{.greek-added} σου[7:5]{.aside}

μη [δωτε]{.greek-omitted} [δοτε]{.greek-added} το αγιον τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε βαλητε τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε [καταπατησωσιν]{.greek-omitted} [καταπησωσιν]{.greek-added} αυτους εν τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

α[ι]{.greek-supplied}τειτε και δοθησεται υμιν ζητειτε και ευρησετε κρουετε και ανοιγησ[ε]{.greek-supplied}τ[αι]{.greek-supplied} [υμιν]{.greek-omitted}[7:7]{.aside}

η τις εστιν εξ υμων [ανθρωπος]{.greek-abbr} ον εαν αιτηση ο υιος αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

και εαν ιχθυν αιτηση μη οφιν επιδωσει αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν α[υ]{.unclear}[τον]{.greek-supplied}[7:11]{.aside}

παντα ουν οσα [αν]{.greek-omitted} [εαν]{.greek-added} θελητε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} ουτως και υμεις ποιειτε αυτ[οις]{.greek-supplied} ουτος γαρ εστιν ο νομος και οι προφ[η]{.unclear}[ται]{.greek-supplied}[7:12]{.aside}

[εισελθετε]{.greek-omitted} [εισελθατε]{.greek-added} δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

τι στ[ε]{.unclear}νη η πυλη και [τεθλιμμενη]{.greek-omitted} [τεθλιμενη]{.greek-added} η οδος η απαγουσα εις την ζω[ην]{.unclear} [κ]{.greek-supplied}αι ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

προσεχετε δε απο των ψευδοπροφητων οιτινες ερχονται προς [υμας]{.greek-omitted} [ημας]{.greek-added} εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} παν δενδρον [α]{.greek-supplied}γαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον σαπρον καρπους καλους ποιειν[7:18]{.aside}

παν δενδρον μη ποιουν καρπον καλον [εκκοπτεται]{.greek-omitted} [εκοπτεται]{.greek-added} και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων [μ]{.greek-supplied}οι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου [τω]{.greek-omitted} [σω]{.greek-omitted} [ονοματι]{.greek-omitted} [προεφητευσαμεν]{.greek-omitted} [και]{.greek-omitted} τω σω ονοματι δαιμονια εξεβαλομεν και τω σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε ομολογησω αυτοις οτι ουδ[ε]{.greek-supplied}ποτε εγνων υμας αποχωρειτε α[π]{.greek-supplied} [ε]{.greek-supplied}μου οι εργαζομενοι την ανομιαν[7:23]{.aside}

πα[ς]{.greek-supplied} ουν οστις ακουει μου τους λογους του[τους]{.greek-supplied} και ποιει αυτους ομοιωσω [αυτον]{.greek-omitted} [αυτην]{.greek-added} α[ν]{.unclear}δρι φρονιμω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την πετραν[7:24]{.aside}

και κα[τε]{.greek-supplied}βη η βροχη και ηλθον οι ποταμο[ι]{.greek-supplied} [και]{.greek-supplied} επνευσαν οι ανεμοι και [προσεπεσον]{.greek-omitted} [προσεπ[ε]{.unclear}σαν]{.greek-added} τη οικια εκεινη και ουκ [επεσεν]{.greek-omitted} [επεσε]{.greek-added} [τε]{.greek-supplied}θεμελιωτο γαρ επι την πετραν[7:25]{.aside}

[και]{.greek-supplied} πας ο ακουων μου τους λογους τουτου[ς]{.greek-supplied} και [μη]{.greek-omitted} [μοι]{.greek-added} ποιων αυτους ομοιωθησε[ται]{.greek-supplied} ανδρι μωρω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομ[η]{.unclear}σε]{.greek-added} την οικιαν αυτου επι την αμμον[7:26]{.aside}

και [κα]{.greek-supplied}τεβη η βροχη και ηλθον οι πο[τα]{.greek-supplied}μοι και επνευσαν οι ανεμοι και [π]{.unclear}[ρο]{.greek-supplied}σεκοψαν τη οικια εκεινη και επεσ[εν]{.greek-supplied} και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγε[νετο]{.greek-supplied} οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους το[υτους]{.greek-supplied} εξεπλησσοντο οι οχλοι επι τη διδ[αχη]{.greek-supplied} αυτου[7:28]{.aside}

ην γαρ διδασκων αυτ[ους]{.greek-supplied} ως εξουσιαν εχων και ουχ ως οι γραμμ[ατεις]{.greek-supplied}[7:29]{.aside}

### Chapter 8

καταβαντι δε αυτω απο του ορους [ηκολουθησαν]{.greek-omitted} [ηκολ[ουθη]{.greek-supplied}]{.greek-added} [σαν]{.greek-added} αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου [λλεπρος]{.greek-added} [λεπρος]{.corr} [ελθων]{.greek-omitted} [προσελθων]{.greek-added} προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} εαν θελης δυνασαι με καθαρισαι[8:2]{.aside}

[κ]{.greek-supplied}αι εκτεινας την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω καθαρισθητι και ευθεως [εκαθαρισθη]{.greek-omitted} [εκαθερισθη]{.greek-added} αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω [ο]{.greek-omitted} [ιησους]{.greek-omitted} ορα μηδενι ειπης [αλλα]{.greek-omitted} [αλλ]{.greek-added} υπαγε [σεαυτον]{.greek-omitted} [σεαυτω]{.greek-added} δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγγε]{.greek-added} το δωρον [σου]{.greek-added} ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε αυτω εις καπερναουμ προσηλθεν αυτω εκατονταρχος παρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου βεβληται εν τη οικια παραλυτικος [δεινως]{.greek-omitted} [δυνως]{.greek-added} βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον [τουτο]{.greek-omitted} [του]{.greek-added} [το]{.greek-added} και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} [εθαυμασεν]{.greek-omitted} [εθαυμασε]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις ακολουθουσιν [αμην]{.greek-omitted} [αμιν]{.greek-added} λεγω υμιν [ουδε]{.greek-omitted} [ουδεν]{.greek-added} εν τω [ισραηλ]{.greek-abbr} τ[ο]{.unclear}σαυτην πιστιν ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και [ανακλιθησονται]{.greek-omitted} [ανακληθησονται]{.greek-added} μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το [εξωτερον]{.greek-omitted} [εξοτερον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω [εκατονταρχη]{.greek-omitted} [κατονταρχη]{.greek-added} υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη[8:13]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο τη[ς]{.unclear} χειρος αυτης και αφηκεν αυτην ο πυ[ρε]{.greek-supplied}τος [και]{.greek-omitted} [ηγερθη]{.greek-omitted} [και]{.greek-omitted} [διηκονει]{.greek-omitted} [αυτω]{.greek-omitted}[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα [πνευματα]{.greek-abbr} λογω και παντ[ας]{.greek-supplied} [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και τας [νο]{.greek-added} [νοσους]{.greek-omitted} [σους]{.greek-added} εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω [σοι]{.greek-omitted} [σι]{.greek-added} οπου [εαν]{.greek-omitted} [αν]{.greek-added} απερχη[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην κλινη[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-omitted} [και]{.greek-added} επιτρεψον μοι [πρωτον]{.greek-omitted} [προτον]{.greek-added} απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις [το]{.greek-omitted} πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων αυτος δε [εκαθευδεν]{.greek-omitted} [εκαθευδε]{.greek-added}[8:24]{.aside}

και προσελθοντες οι μαθηται [αυτου]{.greek-added} ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι τοτε εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} [ε]{.greek-added} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακ[ου]{.unclear}ουσιν [αυτω]{.greek-omitted} [αυτου]{.greek-added}[8:27]{.aside}

και [ελθοντι]{.greek-omitted} [ελθοντος]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} εις το περαν εις την χωραν των [γεργεσηνων]{.greek-omitted} [γαδαρηνων]{.greek-added} υπηντησαν αυτω δυο δαιμονιζομενοι εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δι[α]{.greek-supplied} της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και σοι [υιοι]{.greek-added} [ιησου]{.greek-omitted} [υιε]{.greek-omitted} του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων πολλων [βοσκομενη]{.greek-omitted} [βοσκομενοι]{.greek-added}[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει εκβαλλεις ημας [επιστρεψον]{.greek-added} [επιτρεψον]{.corr} [ημιν]{.greek-omitted} [ημας]{.greek-added} απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων [και]{.greek-omitted} [ιδου]{.greek-omitted} [ωρμησεν]{.greek-omitted} [πασα]{.greek-omitted} [η]{.greek-omitted} [αγελη]{.greek-omitted} [των]{.greek-omitted} [χοιρων]{.greek-omitted} κατα του κρημνου εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δ[ε]{.unclear} βοσκοντες εφυγον και απελθοντες εις την [πολιν]{.greek-omitted} [πολην]{.greek-added} απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον [παρεκαλεσαν]{.greek-omitted} [παρεκαλουν]{.greek-added} οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις το πλοιον διεπερασεν [[διεπερασε]{.corr}]{.greek-added} και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω παραλυτικω θαρσει τεκνον αφεωνται σοι αι αμαρτιαι σου[9:2]{.aside}

και ιδου τινες των γραμματεων ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και ιδων ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις ενθυμεισθε πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} ειπειν αφεωνται σου αι αμαρτιαι η ειπειν εγειραι και [περιπατει]{.greek-omitted} [παραπατει]{.greek-added}[9:5]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ηδητε]{.greek-added} οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

[ιδοντες]{.greek-omitted} [οιδοντες]{.greek-added} δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

και παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} καθημενον επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων εσθιει ο διδασκαλος υμων[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν [ελεον]{.greek-omitted} [ελεος]{.greek-added} θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} λεγοντες δια τι ημεις και οι φαρισαιοι ν[η]{.unclear}στευομεν πολλα οι δε μαθηται σου ου νηστευουσιν[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του [νυμ]{.greek-added} [νυμφωνος]{.greek-omitted} [φωνος]{.greek-added} πενθειν εφ οσον μετ αυτων εστιν ο νυμφιος [ελευσονται]{.greek-omitted} [δε]{.greek-omitted} [ημεραι]{.greek-omitted} [οταν]{.greek-omitted} [απαρθη]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted} [ο]{.greek-omitted} [νυμφιος]{.greek-omitted} και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευουσιν]{.greek-added}[9:15]{.aside}

ουδεις δε επιβαλλει επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και χειρον [σχισμα]{.greek-omitted} [σχιμα]{.greek-added} γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος εκχειται και οι ασκοι απολουνται αλλα [βαλλουσιν]{.greek-omitted} [βαλουσιν]{.greek-added} οινον νεον εις ασκους καινους και αμφοτεροι συντηρουνται[9:17]{.aside}

ταυτα αυτου λαλουντος αυτοις ιδου αρχων [εις]{.greek-omitted} [ελθων]{.greek-omitted} [εἶς]{.greek-added} [ἐλθὼν]{.greek-added} προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν [αλλα]{.greek-omitted} [αλλ]{.greek-added} ελθων επιθες την [χειρα]{.greek-omitted} [χειραν]{.greek-added} σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη [αιμορροουσα]{.greek-omitted} [αιμορρουσα]{.greek-added} δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

ελεγεν γαρ εν εαυτη εαν μονον [αψωμαι]{.greek-omitted} [αψω]{.greek-added} [[αψων]{.corr}]{.greek-added} του ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην ειπεν θαρσει θυγατερ η [πιστις]{.greek-omitted} [πιστης]{.greek-added} σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισ[ελθων]{.greek-supplied} [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} της χειρος αυτης και [η]{.greek-supplied}γερθη το κορασιον[9:25]{.aside}

και εξηλθεν η [φη]{.greek-supplied}μη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

και παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολ[ου]{.greek-supplied}θησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

ε[λ]{.unclear}θοντι δε εις την οικιαν προσηλθ[ον]{.greek-supplied} αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} [π]{.unclear}[ι]{.greek-supplied}στευετε οτι [δυναμαι]{.greek-omitted} [δυναμε]{.greek-added} τουτο ποιησ[αι]{.greek-supplied} λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψα[το]{.greek-supplied} των οφθαλμων αυτων λεγων κατα [την]{.greek-supplied} πιστιν υμων γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμ[οι]{.greek-supplied} [κ]{.greek-supplied}αι [ενεβριμησατο]{.greek-omitted} [ανεβριμησατο]{.greek-added} [αυτοις]{.greek-omitted} [αυτης]{.greek-added} ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες διεφημισαν αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν [ο]{.greek-supplied} [κωφος]{.greek-omitted} [κοφος]{.greek-added} και εθαυμασαν οι οχλοι [λε]{.greek-supplied}γοντες [ουδεποτε]{.greek-omitted} [ουδεπο]{.greek-added} εφανη ουτως [ε]{.greek-supplied}ν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε φαρισαιοι ελε[γον]{.greek-supplied} εν τω αρχοντι των δαιμονιων [εκβαλλει]{.greek-omitted} [[ε]{.greek-supplied}κβαλει]{.greek-added} τα δαιμονια[9:34]{.aside}

και περι[η]{.greek-supplied}γεν ο [ιησους]{.greek-abbr} τας πολεις πασας και τας [κ]{.greek-supplied}[ω]{.unclear}μας διδασκων εν ταις συνα[γω]{.greek-supplied}γαις αυτων και κηρυσσων το [ευα]{.greek-supplied}γγελιον της βασιλειας και [θεραπευων]{.greek-omitted} [[θε]{.greek-supplied}[ρ]{.unclear}απευον]{.greek-added} πασαν νοσον και πασαν [μα]{.greek-supplied}λακιαν [εν]{.greek-omitted} [τω]{.greek-omitted} [λαω]{.greek-omitted}[9:35]{.aside}

ιδων δε τους οχλους [εσπλ]{.greek-supplied}αγχνισθη περι αυτων οτι ησαν [εσκ]{.greek-supplied}υλμενοι και ερριμμενοι ωσει [προβατα]{.greek-supplied} μη εχοντα ποιμενα[9:36]{.aside}

τοτε λεγει [τοις]{.greek-supplied} μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως εκβαλη εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

και προσκαλεσαμενος τους δωδεκα μαθητας αυτου εδωκεν αυτοις εξουσιαν [πνευματων]{.greek-abbr} ακαθαρτων ωστε [εκβαλλειν]{.greek-omitted} [εκβαλειν]{.greek-added} αυτα και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

των δε δωδεκα αποστολων τα ονοματα [εστιν]{.greek-omitted} [εστι]{.greek-added} ταυτα πρωτος σιμων ο λεγομενος πετρος κ[αι]{.greek-supplied} ανδρεας ο αδελφος αυτου ιακ[ω]{.greek-supplied}βος ο του ζεβεδαιου και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο αδε[λ]{.greek-supplied}φος αυτου[10:2]{.aside}

φιλιππος και [βαρθολομαιος]{.greek-omitted} [βαρθαλομαιος]{.greek-added} θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και [λεββαιος]{.greek-omitted} [λεβαιος]{.greek-added} ο επικληθεις θαδδαι[ος]{.greek-supplied}[10:3]{.aside}

σιμων ο [κανανιτης]{.greek-omitted} [καννανιτης]{.greek-added} και ιουδα[ς]{.greek-supplied} [ο]{.greek-added} [ισκαριωτης]{.greek-omitted} [σκαριωτι[ς]{.unclear}]{.greek-added} ο και παραδους α[υτον]{.greek-supplied}[10:4]{.aside}

τουτους τους δωδεκα απεστειλ[ε]{.unclear}[ν]{.greek-supplied} ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδο[ν]{.greek-supplied} εθνων μη απελθητε και εις πολιν σα[μ]{.unclear}[α]{.greek-supplied}ρειτων [[σα[μ]{.unclear}[α]{.greek-supplied}ριτων]{.corr}]{.greek-added} μη εισελθητε[10:5]{.aside}

πορευεσθ[ε]{.greek-supplied} δε μαλλον προς τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρυσσετε λεγοντες οτι ηγγικεν η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας θεραπευετε λεπρους καθαριζετε δαιμονια [εκβαλλετε]{.greek-omitted} [εκβαλετε]{.greek-added} [δωρεαν]{.greek-omitted} [ελαβετε]{.greek-omitted} δωρεαν δοτε[10:8]{.aside}

μη κτησησθε χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

[μη]{.greek-omitted} [πηραν]{.greek-omitted} [εις]{.greek-omitted} [οδον]{.greek-omitted} μηδε [δυο]{.greek-omitted} [χιτωνας]{.greek-omitted} [μηδε]{.greek-omitted} [υποδηματα]{.greek-omitted} [υποδιματα]{.greek-added} μηδε ραβδους αξιος γαρ ο εργατης της τροφης αυτου εστιν[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε [εξετασατε]{.greek-omitted} [εξετασετε]{.greek-added} τις εν αυτη αξιος [εστιν]{.greek-omitted} [εστι]{.greek-added} κακει μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν [ασπασασθε]{.greek-omitted} [ασπαζεσθε]{.greek-added} αυτην[10:12]{.aside}

και εαν μεν η η οικια αξια ελθετω η ειρηνη υμων επ αυτην εαν δε μη η αξια η ειρηνη υμων προς υμας επιστραφητω[10:13]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της οικιας η της πολεως [εκεινης]{.greek-omitted} [εκτιναξατε]{.greek-omitted} [τον]{.greek-omitted} [κονιορτον]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} υμων[10:14]{.aside}

αμη[ν]{.unclear} λεγω υμιν ανεκτοτερον εσται γη σοδομων και γομορρων εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων γινεσθε ουν [φρονιμοι]{.greek-omitted} [φρονημοι]{.greek-added} ως οι οφεις κ[αι]{.unclear} ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσ[ε]{.greek-supplied}χετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συ[να]{.greek-supplied}γωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε παραδιδ[ω]{.unclear}σιν υμας μη μεριμνησητε πως η τι λαλησητε δοθησεται γαρ υμιν ε[ν]{.greek-supplied} [ε]{.greek-supplied}κεινη τη ωρα τι [λαλησετε]{.greek-omitted} [λαλησητε]{.greek-added}[10:19]{.aside}

ου γαρ υμ[εις]{.greek-supplied} εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατ[ον]{.greek-supplied} και [πατηρ]{.greek-abbr} τεκνον και [επαναστησονται]{.greek-omitted} [επαναστησον]{.greek-added} τεκν[α]{.unclear} επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι υπο παντων δια τ[ο]{.unclear} ονομα μου ο δε υπομεινας εις τ[ε]{.unclear}λος ουτος σωθησεται[10:22]{.aside}

οταν δε διωκωσιν υμας εν τη πολει ταυτη φευγ[ετε]{.greek-supplied} εις την [αλλην]{.greek-omitted} [πολιν]{.greek-added} αμην γαρ λεγω υμιν ου μ[η]{.greek-supplied} τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο υιος του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης υπερ τον διδασκαλον ουδε δουλος υπερ τον κυριον αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα γενηται ως ο διδασκαλος αυτου και ο δουλος ως ο [κυριος]{.greek-omitted} [κυριως]{.greek-added} αυτου ει τον οικοδεσποτην βεελζεβουλ εκαλεσαν ποσω μαλλον τους οικειακους αυτου[10:25]{.aside}

[μ]{.unclear}η ουν φοβηθητε αυτους ουδεν γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} κεκαλυμμενον ο ουκ αποκαλυφθησεται και κρυπτον ο ου γνωσθησεται[10:26]{.aside}

ο λεγω υμιν εν τη σκοτια ειπατε εν τω φωτι και ο εις το ους ακουετε κηρυξατε επι των δωματων[10:27]{.aside}

και μη φοβεισθε απο των αποκτενοντων το σωμα την δε ψυχην μη δυναμενων αποκτειναι φοβηθητε δε μαλλον τον δυναμενον και την ψυχην και το σωμα απολεσαι εν γεεννη[10:28]{.aside}

ουχι δυο στρου[θι]{.unclear}α ασσαριου πωλειται και εν εξ [αυτου]{.greek-added} [αυτων]{.corr} ου πεσειται επι την γην ανευ του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added}[10:29]{.aside}

υμων δε και [αι]{.greek-omitted} [τριχες]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [πασαι]{.greek-omitted} [ηριθμημεναι]{.greek-omitted} [εισιν]{.greek-omitted}[10:30]{.aside}

### Chapter 11

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [πο]{.greek-supplied}ρευθεντες απαγγειλατε [ιωαννη]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} α ακ[ου]{.greek-supplied}ετε και βλεπετε[11:4]{.aside}

τυφλοι αναβλεπου[σ]{.unclear}[ιν]{.greek-supplied} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι [κα]{.greek-supplied}θαριζονται και κωφοι ακουου[σιν]{.greek-supplied} [[και]{.greek-supplied}]{.greek-added} νεκροι εγειρονται και πτωχο[ι]{.greek-supplied} [ε]{.greek-supplied}υαγγελιζονται[11:5]{.aside}

και μακαριος εστιν [ος]{.greek-supplied} εαν μη σκανδαλισθη εν εμο[ι]{.greek-supplied}[11:6]{.aside}

τουτων δε πορευομενων ηρξατο [ο]{.greek-supplied} [ιησους]{.greek-abbr} [λεγειν]{.greek-omitted} τοις οχλοις [λεγειν]{.greek-added} περι [ιωαννου]{.greek-abbr} τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} εις την ερημον θεασασ[θαι]{.greek-supplied} καλαμον υπο ανεμου σαλευο[μ]{.unclear}[ενον]{.greek-supplied}[11:7]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μ[α]{.unclear}[λα]{.greek-supplied}κοις ιματιοις ημφιεσμενον ι[δ]{.unclear}[ου]{.greek-supplied} οι τα μαλακα φορουντες εν τ[οις]{.greek-supplied} οικοις των βασιλειων εισιν[11:8]{.aside}

αλλα [τι]{.greek-supplied} [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν προφητην ναι λεγω υ[μιν]{.greek-supplied} και περισσοτερον προφητου[11:9]{.aside}

ουτο[ς]{.unclear} [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω [α]{.greek-supplied}ποστελλω τον αγγελον μου προ προσ[ωπου]{.greek-supplied} σου ος κατασκευασει την οδ[ον]{.greek-supplied} [σου]{.greek-supplied} εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν [ου]{.greek-supplied}κ εγηγερται εν γεννητοις γυναικων μειζων [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων ιωαννου του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} προεφητευσαν[11:13]{.aside}

και ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι [δε]{.greek-omitted} ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις εν [αγοραις]{.greek-omitted} [αγορα]{.greek-added} καθημενοις και [προσφωνουσιν]{.greek-omitted} [προσφωνουσι]{.greek-added} τοις [εταιροις]{.greek-omitted} [ετεροις]{.greek-added} αυτων[11:16]{.aside}

και λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ ωρχησασθε εθρηνησαμεν υμιν και ουκ εκοψασθε[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ιωαννης μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο υιος του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης τελωνων φιλος και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο ονειδιζειν τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χωραζιν]{.greek-added} ουαι σοι βηθσαιδα οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι αν εν σακκω και σποδω μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι ανεκτοτερον εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ η εως του [ουρανου]{.greek-abbr} υψωθεισα εως αδου καταβιβασθηση οτι ει εν σοδομοις εγενοντο αι δυναμεις αι γενομεναι εν σοι εμειναν αν μεχρι της σημερον[11:23]{.aside}

πλην λεγω υμιν [οτι]{.greek-omitted} γη σοδομων ανεκτοτερον [εσται]{.greek-omitted} [εστοι]{.greek-added} εν ημερα κρισεως η σοι[11:24]{.aside}

εν εκεινω τω καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας [ταυτα]{.greek-omitted} [αυτα]{.greek-added} απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι [παρεδοθη]{.greek-omitted} [παρεδωθη]{.greek-added} υπο του [πατρος]{.greek-abbr} μου και ουδεις επιγινωσκει τον υιον ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει [μη]{.greek-omitted} [μι]{.greek-added} ο υιος και ω [εαν]{.greek-omitted} [αν]{.greek-added} βουληται ο υιος αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι κοπιωντες και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και ευρησετε αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου [χρηστος]{.greek-omitted} [χριστος]{.greek-added} και το φορτιον μου ελαφρον εστιν[11:30]{.aside}

### Chapter 12

εν εκεινω τω καιρω επορευθη ο [ιησους]{.greek-abbr} τοις [σαββασιν]{.greek-omitted} [σαμββασι]{.greek-added} δια των σποριμων οι δε μαθηται αυτου επεινασαν και ηρξαντο τιλλειν σταχυας και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντες ειπον αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [ποιειν]{.greek-omitted} [πιειν]{.greek-added} εν σαββατω[12:2]{.aside}

ο δε ειπεν αυτοις ουκ ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added} [αυτος]{.greek-omitted} και οι μετ αυτου[12:3]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως εφαγεν ους ουκ εξον ην αυτω φαγειν ουδε τοις μετ αυτου ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} μονοις[12:4]{.aside}

η ουκ ανεγνωτε εν [τω]{.greek-omitted} νομω οτι τοις σαββασιν οι ιερεις εν τω ιερω το σαββατον [βεβηλουσιν]{.greek-omitted} [βεβηλουσι]{.greek-added} και αναιτιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[12:5]{.aside}

[ο]{.greek-added} [λεγω]{.corr} δε υμιν οτι του ιερου μειζον εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε τι εστιν ελεον θελω και ου θυσιαν ουκ αν κατεδικασατε τους [αναιτιους]{.greek-omitted} [ανετιους]{.greek-added}[12:7]{.aside}

[κυριος]{.greek-abbr} γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} του σαββατου ο υιος του [ανθρωπου]{.greek-abbr}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} ην την χειρα εχων ξηραν και επηρωτησαν αυτον λεγοντες ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις εσται εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει αυτο και εγερει[12:11]{.aside}

ποσω ουν διαφερει [ο]{.greek-added} [ανθρωπος]{.greek-abbr} προβατου ωστε [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} καλως ποιειν[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και αποκατεσταθη υγιης ως η αλλη[12:13]{.aside}

οι δε φαρισαιοι συμβουλιον ελαβον κατ αυτου εξελθοντες οπως αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και [ηκολουθησαν]{.greek-omitted} [ηκουλουθησαν]{.greek-added} αυτω οχλοι πολλοι και εθεραπευσεν αυτους [παντας]{.greek-omitted} [παντα]{.greek-added}[12:15]{.aside}

και επετιμησεν αυτοις ινα μη φανερον αυτον ποιησωσιν[12:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον ηρετ[ι]{.unclear}σα [[ηρετησα]{.corr}]{.greek-added} ο αγαπητος μου εις ον ευδοκησεν η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει ουδε ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον [τυφομενον]{.greek-omitted} [τυφωμενον]{.greek-added} ου σβεσει εως αν εκβαλη εις νικος την κρισιν[12:20]{.aside}

και τω ονοματι αυτου εθνη [ελπιουσιν]{.greek-omitted} [ελπιουσι]{.greek-added}[12:21]{.aside}

τοτε προσηνεχθη αυτω δαιμονιζομενος τυφλος και κωφος και εθεραπευσεν αυτον ωστε τον τυφλον και κωφον και λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο παντες οι οχλοι και ελεγον [μητι]{.greek-omitted} [μη]{.greek-added} ουτος εστιν ο υιος [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες ειπον ουτος ουκ εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

ειδως δε ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν αυτοι[ς]{.greek-supplied} πασα βασιλεια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ερημουται και πασα πολις η οικια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν [εκβαλλει]{.greek-omitted} [εκβαλει]{.greek-added} εφ εαυτον [εμερισθε]{.greek-added} [εμερισθη]{.corr} πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

και ει εγω εν βεελζεβουλ [εκβαλλω]{.greek-omitted} [εκβαλω]{.greek-added} τα δαιμονια οι υιοι υμων εν τινι [εκβαλλουσιν]{.greek-omitted} [εκβαλουσιν]{.greek-added} δια τουτο αυτοι υμων εσονται κριται[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} εγω [εκβαλλω]{.greek-omitted} [εκβαλω]{.greek-added} τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

η πως δυναται [τις]{.greek-omitted} [τοις]{.greek-added} εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου διαρπασαι εαν μη πρωτον δηση τον ισχυρον και τοτε την οικιαν αυτου διαρπασει[12:29]{.aside}

ο μη ων μετ εμου κατ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

δια τουτο λεγω υμιν πασα αμαρτια και βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} η δε του [πνευματος]{.greek-abbr} βλασφημια ουκ αφεθησεται τοις [ανθρωποις]{.greek-abbr}[12:31]{.aside}

και ος εαν ειπη λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω ος δ αν [ειπη]{.greek-omitted} [ει]{.greek-added} κατα του [πνευματος]{.greek-abbr} του αγιου ουκ αφεθησεται αυτω ουτε εν τω νυν αιωνι ουτε εν τω μελλοντι[12:32]{.aside}

η ποιησατε το δενδρον καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον [γινωσκεται]{.greek-omitted} [γινοσκεται]{.greek-added}[12:33]{.aside}

γεννηματα εχιδνων πως δυνασθε αγαθα [λαβειν]{.greek-added} [λαλειν]{.corr} πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου [εκβαλλει]{.greek-omitted} [εκβαλει]{.greek-added} αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου εκβαλλει πονηρα[12:35]{.aside}

λεγ[ω]{.unclear} δε υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσουσι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

[ε]{.greek-supplied}κ γαρ των λογων σου δικαιωθηση και εκ των λογων σου καταδικασθηση[12:37]{.aside}

τοτε απεκριθησαν τινες των γραμματεων και φαρισαιων λεγοντες διδασκαλε θελομεν απο σου σημειον ιδειν[12:38]{.aside}

[ο]{.greek-supplied} δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτοις]{.greek-omitted} γενεα πονηρα και [μοιχαλις]{.greek-omitted} [μηχαλις]{.greek-added} σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του [προ]{.greek-added} [προφητου]{.greek-omitted} [φητου]{.greek-added}[12:39]{.aside}

ωσπερ γαρ ην ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας ουτως εσται ο υιος του [ανθρωπου]{.greek-abbr} εν τη καρδια της γης τρεις ημερας και τρεις νυκτας[12:40]{.aside}

ανδρες [νινευηται]{.greek-added} [νινευιται]{.corr} αναστησονται εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα [του]{.greek-added} ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

βασιλισσα νοτου εγερθησεται εν τη κρισει μετα της γενεας ταυτης και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν σολομωνος και ιδου πλειον [σολομωνος]{.greek-omitted} [σολομωντος]{.greek-added} ωδε[12:42]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη [απο]{.greek-omitted} [εκ]{.greek-added} του [ανθρωπου]{.greek-abbr} [[―]{.gap}ρχεται]{.greek-added} [διερχεται]{.corr} δι ανυδρων τοπων ζητουν [αναπαυσιν]{.greek-omitted} [αναπασιν]{.greek-added} και ουχ ευρισκει[12:43]{.aside}

τοτε λεγει επιστρεψω εις τον οικον μου οθεν εξηλθον και ελθον [ων]{.greek-added} ευρισκει σχολαζοντα σεσαρωμενον και κεκοσμημενον[12:44]{.aside}

τοτε πορευεται και παραλαμβανει μεθ εαυτου επτα ετερα [πνευματα]{.greek-abbr} πονηροτερα εαυτου και [εισελθοντα]{.greek-omitted} [εισελθοντη]{.greek-added} [κατοικει]{.greek-omitted} [κατοικοι]{.greek-added} εκει και [γινεται]{.greek-omitted} [γινονται]{.greek-added} τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου [χειρονα]{.greek-omitted} [χειρον]{.greek-added} [των]{.greek-omitted} [αυτων]{.greek-added} [πρωτων]{.greek-omitted} ουτως εσται [και]{.greek-omitted} τη γενεα ταυτη τη πονηρα[12:45]{.aside}

ετι [δε]{.greek-omitted} αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και οι αδελφοι αυτου ειστηκεισαν εξω [ζητουντες]{.greek-omitted} [ζητουντε]{.greek-added} αυτω λαλησαι[12:46]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εξω [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} ζητουντες σ[οι]{.unclear} λαλησαι[12:47]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω ειποντι αυτω τις εστιν η [μητηρ]{.greek-abbr} μου και τινες εισιν οι αδελφοι μου[12:48]{.aside}

και εκτεινας την χειρα αυτου επι τους [μα]{.greek-added} [μαθητας]{.greek-omitted} [θητας]{.greek-added} αυτου ειπεν ιδου η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[12:49]{.aside}

[οστις]{.greek-omitted} [ος]{.greek-added} γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr} αυτος μου αδελφος και [αδελφη]{.greek-omitted} [αδελφοι]{.greek-added} και [μητηρ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:50]{.aside}

### Chapter 13

εν [δ]{.greek-supplied}ε τη ημερα εκεινη [εξελθον]{.greek-added} [εξελθων]{.corr} ο [ιησους]{.greek-abbr} απο της οικιας εκαθητο παρα την θαλασσαν[13:1]{.aside}

και συνηχθησαν προς αυτον οχλοι πολλοι ωστε αυτον εις το πλοιον εμβαντα καθησθαι και πας ο οχλος επι τον αιγιαλον ειστηκει[13:2]{.aside}

και ελαλησεν αυτοις [[κυριος]{.greek-abbr}]{.greek-added} πολλα εν παραβολαις λεγων ιδου εξηλθεν ο σπειρων του σπειρειν[13:3]{.aside}

και εν τω σπειρειν αυτον α μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και [και]{.greek-added} κατεφαγεν αυτα[13:4]{.aside}

αλλα δε επεσεν επι τα πετρωδη οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[13:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[13:6]{.aside}

αλλα δε επεσεν επι τας ακανθας και ανεβησαν [αι]{.greek-omitted} [ε]{.greek-added} ακανθαι και απεπνιξαν αυτα[13:7]{.aside}

αλλα δε επεσεν επι την γην [την]{.greek-omitted} καλην και εδιδου καρπον ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:8]{.aside}

ο εχων ωτα ακουειν ακουετω[13:9]{.aside}

και προσελθοντες οι μαθηται ειπον αυτω δια τι εν παραβολαις λαλεις [αυτοις]{.greek-omitted} [αυτων]{.greek-added}[13:10]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι υμιν δεδοται γνωναι τα μυστηρια της βασιλειας των [ουρανων]{.greek-abbr} εκεινοις δε ου δεδοται[13:11]{.aside}

οστις γαρ εχει δοθησεται αυτω και [περιευ]{.greek-added} [περισσευθησεται]{.greek-omitted} [[περισευθησεται]{.corr}]{.greek-added} [αυτω]{.greek-added} [οστις]{.corr} δε ουκ εχει και ο εχει αρθησεται απ αυτου[13:12]{.aside}

δια τουτο εν παραβολαις αυτοις λαλω οτι βλεποντες ου [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και ακουοντες ουκ [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} ουδε συνιουσιν[13:13]{.aside}

και αναπληρουται αυτοις η προφητεια ησαιου η λεγουσα ακοη [ακουσετε]{.greek-omitted} [ηκουσατε]{.greek-added} και ου μη συνητε και βλεποντες βλεψετε και ου μη [ιδητε]{.greek-omitted} [ηδητε]{.greek-added}[13:14]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων [εκαμμυσαν]{.greek-omitted} [εκαμμησαν]{.greek-added} μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνιωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και ιασομαι αυτους[13:15]{.aside}

υμων δε μακαριοι [οι]{.greek-omitted} οφθαλμοι οτι βλεπουσιν και τα ωτα υμων οτι ακουει[13:16]{.aside}

αμην γαρ λεγω υμιν οτι πολλοι προφηται και δικαιοι επεθυμησαν ιδειν α [βλεπετε]{.greek-omitted} [βλεπτε]{.greek-added} και ουκ ειδον και ακουσαι α [α]{.unclear}κ[ουετε]{.unclear} [α]{.greek-added} [ακουετε]{.greek-added} και ουκ [ηκουσαν]{.greek-omitted} [εικουσαν]{.greek-added}[13:17]{.aside}

υμεις ουν ακουσατε την παραβολην του σπειροντος[13:18]{.aside}

παντος ακουοντος τον λογον της βασιλειας και μη συνιεντος ερχεται ο πονηρος και αρπαζει το [εσπαρμενον]{.greek-omitted} [επαρμενον]{.greek-added} εν τη καρδια αυτου ουτος εστιν ο παρα την οδον σπαρεις[13:19]{.aside}

ο δε επι τα πετρωδη σπαρεις ουτος εστιν ο τον λογον ακουων και ευθυς μετα χαρας λαμβανων αυτον[13:20]{.aside}

ουκ εχει δε ριζαν εν εαυτω αλλα προσκαιρος [εστιν]{.greek-omitted} [εστι]{.greek-added} γενομενης δε θλιψεως η διωγμου δια τον λογον ευθυς σκανδαλιζεται[13:21]{.aside}

ο δε εις τας ακανθας σπαρεις ουτος εστιν ο τον λογον ακουων και η [μεριμνα]{.greek-omitted} [μερημνα]{.greek-added} του αιωνος τουτου και η απατη του πλουτου συμπνιγει τον λογον και ακαρπος γινεται[13:22]{.aside}

ο δε επι την γην την καλην σπαρεις ουτος εστιν ο τον λογον ακουων και συνιων ος δη καρποφορει και ποιει ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:23]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων [ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} σπειροντι καλον σπερμα εν τω αγρω αυτου[13:24]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} καθευδειν τους [ανθρωπους]{.greek-abbr} ηλθεν [αυτου]{.greek-omitted} ο εχθρος [αυτου]{.greek-added} και [εσπειρεν]{.greek-omitted} [εσπειρε]{.greek-added} ζιζανια ανα μεσον του σιτου και απηλθεν[13:25]{.aside}

οτε δε εβλαστησεν ο χορτος και καρπον [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοτε εφανη και τα ζιζανια[13:26]{.aside}

προσελθοντες δε οι δουλοι του οικοδεσποτου [ειπον]{.greek-omitted} [ειπεν]{.greek-added} αυτω [κυριε]{.greek-abbr} ουχι καλον σπερμα [εσπειρας]{.greek-omitted} [εσπειρες]{.greek-added} εν τω [σω]{.greek-omitted} αγρω ποθεν ουν [εχει]{.greek-omitted} [εχι]{.greek-added} [ζιζανια]{.greek-omitted} [ζανια]{.greek-added}[13:27]{.aside}

ο δε εφη αυτοις εχθρος [ανθρωπος]{.greek-abbr} τουτο εποιησεν οι δε δουλοι ειπον αυτω θελεις ουν απελθοντες συλλεξομεν αυτα[13:28]{.aside}

ο δε εφη ου μηποτε συλλεγοντες τα ζιζανια εκριζωσητε αμα αυτοις τον σιτον[13:29]{.aside}

αφετε συναυξανεσθαι αμφοτερα μεχρι του θερισμου και εν [τω]{.greek-added} καιρω του θερισμου ερω τοις θερισταις συλλεξατε πρωτον τα ζιζανια και δησατε αυτα εις δεσμας προς το κατακαυσαι αυτα τον δε σιτον συναγαγετε εις την αποθηκην μου[13:30]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} κοκκω σιναπεως ον λαβων [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο μικροτερον μεν [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των σπερματων οταν δε αυξηθη μειζον των λαχανων [εστιν]{.greek-omitted} [εστι]{.greek-added} και γινεται δενδρον ωστε ελθειν τα πετεινα του [ουρανου]{.greek-abbr} και κατασκηνουν εν τοις κλαδοις αυτου[13:32]{.aside}

αλλην [παραβολην]{.greek-omitted} [παρα]{.greek-added} [ολην]{.greek-added} ελαλησεν αυτοις ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ζυμη]{.greek-omitted} ην λαβουσα γυνη εκρυψεν εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33]{.aside}

ταυτα [π]{.greek-supplied}αντα ελαλησεν ο [ιησους]{.greek-abbr} εν παραβολαις τοις οχλοις και χωρις παραβολης ουκ ελαλει αυτοις[13:34]{.aside}

οπως πληρωθη το ρηθεν δια του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου [ερευξομαι]{.greek-omitted} [κεκρυμμενα]{.greek-omitted} [απο]{.greek-omitted} [καταβολης]{.greek-omitted} [κοσμου]{.greek-omitted}[13:35]{.aside}

τοτε αφεις τους οχλους ηλθεν εις την οικιαν ο [ιησους]{.greek-abbr} και προσηλθον αυτω οι μαθηται αυτου λεγοντες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις [ο]{.unclear} [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} το καλον σπερμα εστιν ο υιος του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε [καλον]{.greek-omitted} σπερμα ουτοι εισιν οι υιοι της βασιλειας τα [δε]{.greek-omitted} ζιζανια εισιν οι υιοι του πονηρου[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος [εστιν]{.greek-omitted} [εστι]{.greek-added} οι δε [θ]{.unclear}ερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν συλλεγεται τα ζιζανια και πυρι καιεται ουτως εσται εν τη συντελεια του αιωνος τουτου[13:40]{.aside}

αποστελει ο υιος του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν τω αγρω ον [ευρων]{.greek-omitted} [ευρον]{.greek-added} [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας αυτου υπαγει και παντα οσα εχει [πωλει]{.greek-omitted} [πολει]{.greek-added} και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν [η]{.unclear} βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορ[ω]{.unclear} ζητ[ουν]{.unclear}τι καλους μαργαριτας[13:45]{.aside}

ος ευρων ενα [[πο]{.unclear}]{.greek-added} [πολυτιμον]{.greek-omitted} [λυτιμον]{.greek-added} μαργαριτην απελθων [πεπρακεν]{.greek-omitted} [πεπρακε]{.greek-added} παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη βληθειση εις την θαλασσαν και εκ παντος γενους συναγαγουση[13:47]{.aside}

ην οτε επληρωθη [αναβιβασαντες]{.greek-omitted} [αναβηβασαντες]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} τον αιγιαλον και καθισαντες συνελεξαν τα καλα εις αγγεια τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εστ[αι]{.unclear} εν τη συντελεια του α[ιων]{.unclear}ος εξελευσονται οι αγγελοι και [αφοριουσιν]{.greek-omitted} [αφοριουσι]{.greek-added} τους πονηρους εκ μεσου [των]{.greek-omitted} [τον]{.greek-added} δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος τ[ων]{.unclear} οδοντων[13:50]{.aside}

λεγει [α]{.greek-supplied}υτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} συνηκατε ταυτα παντα λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[13:51]{.aside}

ο δε ειπεν αυτοις δια τουτο πας γραμματευς μαθητευθεις εις την βασιλειαν των [ουρανων]{.greek-abbr} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εκβαλλει εκ του θησαυρου αυτου καινα και παλαια[13:52]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας [και]{.greek-added} [εγενετο]{.greek-added} μετηρεν εκειθεν[13:53]{.aside}

και ελθων εις την [πατριδα]{.greek-abbr} αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων ωστε [εκπληττεσθαι]{.greek-omitted} [εκπλησσεσθε]{.greek-added} αυτους [και]{.greek-omitted} λεγειν ποθεν τουτω η σοφια αυτη και αι δυναμεις[13:54]{.aside}

ουχ ουτος [εστιν]{.greek-omitted} [εστην]{.greek-added} ο του τεκτονος υιος ουχι η [μητηρ]{.greek-abbr} αυτου λεγεται μαριαμ και οι αδελφοι αυτου ιακωβος και ιωσης και σιμων και ιουδας[13:55]{.aside}

και αι αδελφαι αυτου ουχι πασαι προς ημας [εισιν]{.greek-omitted} [εισι]{.greek-added} ποθεν ουν τουτω ταυτα [παντα]{.greek-omitted}[13:56]{.aside}

και εσκανδαλιζοντο εν [αυτω]{.greek-omitted} [εαυτω]{.greek-added} ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ εστιν προφητης ατιμος ει μη εν τη [ιδια]{.greek-added} [πατριδι]{.greek-abbr} [αυτου]{.greek-omitted} και εν τη οικια αυτου[13:57]{.aside}

και ουκ εποιησεν εκει [δυναμεις]{.greek-omitted} [δυνα]{.greek-added} [μεις]{.greek-added} πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο [τετραρχης]{.greek-omitted} [τεταρχης]{.greek-added} την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις παισιν αυτου ουτος εστιν [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο βαπτιστης αυτος ηγερθη απο των νεκρων και δια τουτο αι δυναμεις ενεργουσιν [εν]{.greek-omitted} αυτω[14:2]{.aside}

ο γαρ ηρωδης κρατησας τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εδησεν αυτον και εθετο εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου[14:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων δε αγομενων του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και [ηρεσεν]{.greek-omitted} [ηρεσε]{.greek-added} τω ηρωδη[14:6]{.aside}

[οθεν]{.greek-omitted} [ωστε]{.greek-added} [και]{.greek-added} μεθ ορκου ωμολογησεν αυτη δουναι ο εαν αιτησηται[14:7]{.aside}

η δε προβιβασθεισα υπο της [μητρος]{.greek-abbr} αυτης δος [μοι]{.greek-omitted} [μη]{.greek-added} φησιν ωδε επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[14:8]{.aside}

και [ελυπηθη]{.greek-omitted} [εληπηθη]{.greek-added} ο βασιλευς δια δε τους ορκους και τους συνανακειμενους [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [επεκεφαλισε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι πινακι και εδοθη τω κορασιω και ηνεγκεν τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το [σωμα]{.greek-omitted} [πτωμα]{.greek-added} και εθαψαν [αυτο]{.greek-omitted} [αυτον]{.greek-added} και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} ανεχωρησεν εκειθεν εν πλοιω εις ερημον τοπον κατ ιδιαν και ακουσαντες οι οχλοι ηκολουθησαν αυτω πεζη απο των πολεων[14:13]{.aside}

και εξελθων ο [ιησους]{.greek-abbr} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον [αυτω]{.greek-omitted} [αυτων]{.greek-added} οι μαθηται αυτου λεγοντες ερημος εστιν ο τοπος και η ωρα ηδη παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας κωμας αγορασωσιν [εαυτοις]{.greek-omitted} [αυτοις]{.greek-added} βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου χρειαν εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

[και]{.greek-omitted} [κελευσας]{.greek-omitted} [τους]{.greek-omitted} [οχλους]{.greek-omitted} [ανακλιθηναι]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [χορτους]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και κλασας [εδωκεν]{.greek-omitted} [εδοκεν]{.greek-added} τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες ωσει πεντακισχιλιοι χωρις γυναικων και παιδιων[14:21]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας εμβηναι εις το πλοιον και προαγειν αυτον εις το περαν εως [ου]{.greek-omitted} [του]{.greek-added} απολυση τους οχλους[14:22]{.aside}

και απολυσας [τ]{.greek-supplied}ους οχλους ανεβη εις το ορος κατ ιδιαν προσευξασθαι οψιας δε γενομενης [μονης]{.greek-added} [μονος]{.corr} ην εκει[14:23]{.aside}

το δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος απηλθεν προς αυτους [ο]{.greek-omitted} [ιησους]{.greek-omitted} περιπατων επι της θαλασσης[14:25]{.aside}

και ιδοντες αυτον οι μαθηται επι την θαλασσαν περιπατουντα εταραχθησαν λεγοντες οτι φαντασμα [εστιν]{.greek-omitted} [εστι]{.greek-added} και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} λεγων θαρσειτε εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε [αυτω]{.greek-omitted} ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} ει συ ει κελευσον με προς σε ελθειν επι τα υδατα[14:28]{.aside}

ο δε ειπεν ελθε και καταβας απο του πλοιου ο πετρος περιεπατησεν επι τα υδατα ελθειν προς τον [ιησουν]{.greek-abbr}[14:29]{.aside}

βλεπων δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα επελαβετο αυτου και λεγει αυτω [ολιγοπιστε]{.greek-omitted} [ολιγοπιστη]{.greek-added} εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω ελθοντες προσεκυνησαν αυτω λεγοντες αληθως [θεου]{.greek-abbr} υιος ει[14:33]{.aside}

και διαπερασαντες ηλθον εις την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added}[14:34]{.aside}

και επιγνοντες αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον [αψωνται]{.greek-omitted} [αψονται]{.greek-added} του κρασπεδου του ιματιου αυτου και οσοι ηψαντο διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτε προσερχονται τω [ιησου]{.greek-abbr} οι απο ιεροσολυμων γραμματεις και φαρισαιοι λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου [παραβαινουσιν]{.greek-omitted} [παραβαινουσι]{.greek-added} την παραδοσιν των πρεσβυτερων ου γαρ νιπτονται τας χειρας αυτων οταν [τον]{.greek-added} αρτον [εσθιωσιν]{.greek-omitted} [εσθιωσι]{.greek-added}[15:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και [υ]{.greek-added} [υμεις]{.greek-omitted} [μεις]{.greek-added} παραβαινετε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} ενετειλατο λεγων τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[15:4]{.aside}

υμεις δε λεγετε ος [αν]{.greek-omitted} [εαν]{.greek-added} ειπη τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} δωρον ο εαν εξ εμου [ωφεληθης]{.greek-omitted} [ωφηληθης]{.greek-added} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[και]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [τιμησει]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [η]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} και ηκυρωσατε την εντολην του [θεου]{.greek-abbr} δια την [παραδοσιν]{.greek-omitted} [παδοσιν]{.greek-added} υμων[15:6]{.aside}

υποκριται καλως προεφητευσεν περι υμων ησαιας λεγων[15:7]{.aside}

εγγιζει μοι ο λαος ουτος τω στοματι αυτων και τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[15:8]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις ακουετε και συνιετε[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} αλλα το εκπορευομενον εκ του στοματος τουτο κοινοι τον [ανθρωπον]{.greek-abbr}[15:11]{.aside}

τοτε προσελθοντες οι μαθηται αυτου ειπον αυτω οιδας οτι οι φαρισαιοι ακουσαντες τον λογον εσκανδαλισθησαν[15:12]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πασα φυτεια ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο [ουρανιος]{.greek-abbr} εκριζωθησεται[15:13]{.aside}

αφετε αυτους οδηγοι [εισιν]{.greek-omitted} [εισι]{.greek-added} τυφλοι τυφλων τυφλος δε τυφλον εαν οδηγη [αμφοτεροι]{.greek-omitted} [αφοτεροι]{.greek-added} εις βοθυνον [πεσουνται]{.greek-omitted} [εμπεσουνται]{.greek-added}[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-added} ακμην [και]{.greek-omitted} υμεις ασυνετοι [εστε]{.greek-omitted} [ετε]{.greek-added}[15:16]{.aside}

ουπω νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ της καρδιας [εξερχεται]{.greek-omitted} [κακεινα]{.greek-omitted} [κοινοι]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[15:18]{.aside}

[εκ]{.greek-omitted} [γαρ]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} εξερχονται διαλογισμοι πονηροι φονοι μοιχειαι πορνειαι κλοπαι ψευδομαρτυριαι βλασφημιαι[15:19]{.aside}

ταυτα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr} το δε ανιπτοις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} φαγειν ου κοινοι τον [ανθρωπον]{.greek-abbr}[15:20]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα μερη τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη [χαναναια]{.greek-omitted} [χαναναι]{.greek-added} απο των οριων εκεινων εξελθουσα [εκραυγασεν]{.greek-omitted} [εκρατησεν]{.greek-added} αυτω λεγουσα ελεησον με [κυριε]{.greek-abbr} υιε [δαυιδ]{.greek-abbr} η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε ουκ απεκριθη αυτη [λογον]{.greek-omitted} [λεγον]{.greek-added} και προσελθοντες οι μαθηται αυτου ηρωτων αυτον λεγοντες απολυσον αυτην οτι κραζει [οπισθεν]{.greek-omitted} [οπιθεν]{.greek-added} ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην [ει]{.greek-omitted} [η]{.greek-added} μη εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

[η]{.greek-omitted} [ι]{.greek-added} δε [ελθουσα]{.greek-omitted} [προσελθουσα]{.greek-added} [π]{.greek-supplied}ροσεκυνησεν αυτω λεγουσα [κυριε]{.greek-abbr} βοηθει μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των [ψιχιων]{.greek-omitted} [ψυχιων]{.greek-added} των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη ω γυναι μεγαλη σου η πιστις γενηθητω σοι ως θελεις και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μετα[β]{.greek-supplied}ας εκειθεν ο [ιησους]{.greek-abbr} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος εκαθητο εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ [εαυτων]{.greek-omitted} [αυτους]{.greek-added} χωλους τυφλους κωφους κυλλους και ετερους πολλους και ερριψαν αυτους παρα τους ποδας του [ιησου]{.greek-abbr} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους λαλουντας κυλλους υγιεις χωλους περιπατουντας και τυφλους βλεποντας και εδοξασαν τον [θεον]{.greek-abbr} [ισραηλ]{.greek-omitted}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} και απολυσαι αυτους νηστεις ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια αρτοι τοσουτοι ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τοις οχλοις αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους [δυο]{.greek-added} ιχθυας [[κ]{.unclear}[αι]{.greek-supplied}]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις αυτου οι δε μαθηται τω οχλω[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας πληρεις[15:37]{.aside}

οι δε εσθιοντες ησαν τετρακισχιλιοι [ανδρες]{.greek-omitted} χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους [ενεβη]{.greek-omitted} [ανεβη]{.greek-added} εις το πλοιον και ηλθεν εις τα ορια μαγδαλα[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε [ευδια]{.greek-omitted} [ευδιω]{.greek-added} πυρραζει γαρ [ο]{.greek-omitted} [ουρανος]{.greek-abbr}[16:2]{.aside}

και [πρωι]{.greek-omitted} [πρωιας]{.greek-added} σημερον χειμων πυρραζει γαρ [σ]{.unclear}τυγναζων [ο]{.greek-omitted} [ουρανος]{.greek-abbr} υποκριται το [μεν]{.greek-omitted} προσωπον του [ουρανου]{.greek-abbr} γινωσκετε διακρινειν τα δε σημεια των καιρων ου δυνασθε[16:3]{.aside}

γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} αυτη ει μη το σημειον ιωνα του προφητου και καταλιπων αυτους [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν επελαθοντο αρτους λαβειν[16:5]{.aside}

ο δε [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπει]{.greek-added} αυτοις ορατε και [προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} απο της ζυμης των φαρισαιων και σαδδουκαιων[16:6]{.aside}

οι δε διελογιζοντο εν εαυτοις λεγοντες οτι αρτους ουκ [ελαβομεν]{.greek-omitted} [εχομεν]{.greek-added}[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι διαλογιζεσθε εν εαυτοις ολιγοπιστοι οτι αρτους ουκ ελαβετε[16:8]{.aside}

ουπω νοειτε ουδε μνημονευετε τους πεντε αρτους των πεντακισχιλιων και ποσους κοφινους ελαβετε[16:9]{.aside}

ουδε τους επτα αρτους των τετρακισχιλιων και ποσας σπυριδας ελαβετε[16:10]{.aside}

πως ου νοειτε οτι ου περι αρτου ειπον υμιν προσεχειν [αλλα]{.greek-added} απο της ζυμης των φαρισαιων και σαδδουκαιων[16:11]{.aside}

ελθων δε ο [ιησους]{.greek-abbr} εις τα μερη [και]{.greek-added} [καισαρειας]{.greek-omitted} [της]{.greek-omitted} [φιλιππου]{.greek-omitted} [ηρωτα]{.greek-omitted} τους μαθητας αυτου λεγων τινα με λεγουσιν οι ανθρωποι ειναι τον υιον του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον οι μεν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην αλλοι [δε]{.greek-omitted} ηλιαν ετεροι δε ιερεμιαν [η]{.greek-omitted} [[ι]{.unclear}]{.greek-added} ενα των προφητων[16:14]{.aside}

λεγει αυτοις υμεις δε τινα με λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

και αποκρι[θ]{.greek-supplied}εις ο [ιησους]{.greek-abbr} ειπεν αυτω μακαριος ει σιμων βαριωνα [ο]{.greek-added} [λυψε]{.greek-added} [οτι]{.greek-omitted} [σαρξ]{.greek-omitted} [και]{.greek-omitted} [αιμα]{.greek-omitted} [ουκ]{.greek-omitted} [απεκαλυψεν]{.greek-omitted} σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις [ουρανοις]{.greek-abbr}[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι αδου ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν τοις [ουρανοις]{.greek-abbr} και ο εαν λυσης επι της γης εσται λελυμενον εν τοις [ουρανοις]{.greek-abbr}[16:19]{.aside}

τοτε διεστειλατο τοις μαθηταις αυτου ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-omitted} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο το[τ]{.greek-supplied}ε ηρξατο ο [ιησους]{.greek-abbr} δεικνυειν τοις μαθηταις αυτου οτι [δει]{.greek-omitted} [δι]{.greek-added} αυτον απελθειν εις ιεροσολυμα και πολλα παθειν απο των πρεσβυτερων και αρχιερεων και γραμματεων και αποκτανθηναι και τη τριτη ημερα εγερθηναι[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω λεγων ιλεως σοι [κυριε]{.greek-abbr} ου μη εσται σοι τουτο[16:22]{.aside}

ο δε στραφεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω πετρω υπαγε οπισω μου σατανα [σκανδαλον]{.greek-omitted} [σκανδαλλον]{.greek-added} μου ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} ειπεν τοις μαθηταις αυτου ει τις θελει οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[16:24]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την ψυχην αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι γαρ ωφελειται [ανθρωπος]{.greek-abbr} εαν τον κοσμον ολον κερδηση την δε ψυχην αυτου ζημιωθη η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο υιος του [ανθρωπου]{.greek-abbr} ερχεσθαι εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων αυτου και τοτε αποδωσει εκαστω κατα την πραξιν αυτου[16:27]{.aside}

αμην λεγω υμιν [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες [των]{.greek-added} ωδε [εστωτες]{.greek-omitted} [εστωτων]{.greek-added} οιτινες ου μη γευσωνται θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αναφερει αυτους εις ορος υψηλον κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και [ελαμψεν]{.greek-omitted} [ελαμψε]{.greek-added} το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου εγενοντο λευκα ως το φως[17:2]{.aside}

και ιδου ωφθησαν αυτοις μωσης και ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

αποκριθεις δε ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω [ιησου]{.greek-abbr} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι ει θελεις [ποιησωμεν]{.greek-omitted} [ποιησομεν]{.greek-added} [ωδε]{.greek-omitted} τρεις σκηνας σοι μιαν και [μωση]{.greek-omitted} [μωσει]{.greek-added} μιαν και μιαν [ηλια]{.greek-omitted} [ηλιαν]{.greek-added}[17:4]{.aside}

ετι αυτου λαλουντος ιδου νεφελη φωτεινη επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο υιος μου ο αγαπητος εν ω ευδοκησα αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται επεσον επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν εγερθητε και μη φοβεισθε[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και [καταβαινοντων]{.greek-omitted} [καταβαι]{.greek-added} [νοντων]{.greek-added} αυτων [εκ]{.greek-omitted} [απο]{.greek-added} του ορους ενετειλατο αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι ειπητε το οραμα εως ου ο υιος του [ανθρωπου]{.greek-abbr} εκ ν[ε]{.unclear}κρων αναστη[17:9]{.aside}

και επηρωτησαν αυτον οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν [δει]{.greek-omitted} ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθης]{.greek-added} [αποκριθεις]{.corr} ειπεν αυ[τοις]{.unclear} ηλιας μεν ερχεται πρωτον και αποκαταστησει παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας ηδη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ουκ επεγνωσαν αυτον [αλλα]{.greek-omitted} [αλλ]{.greek-added} εποιησαν εν αυτω οσα ηθελησαν [ουτως]{.greek-omitted} [ουτω]{.greek-added} [δη]{.greek-added} και ο υιος του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον προσηλθεν αυτω [ανθρωπος]{.greek-abbr} [τις]{.greek-added} γονυπετων [αυτον]{.greek-omitted} [αυτων]{.greek-added}[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι σεληνιαζεται και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και προσηνεγκα αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν αυτον θεραπευσαι[17:16]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε εσομαι μεθ υμων εως ποτε [ανεξομαι]{.greek-omitted} [αντεξομαι]{.greek-added} υμων φερετε μοι [αυτον]{.greek-omitted} [αυτων]{.greek-added} ωδε[17:17]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε προσελθοντες οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην γαρ λεγω υμιν εαν εχητε πιστιν ως κοκκον σιναπεως ερειτε τω ορει τουτω [μεταβηθι]{.greek-omitted} [μεταβηθη]{.greek-added} εντευθεν εκει και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ [εκπορευεται]{.greek-omitted} [εκπορευετε]{.greek-added} ει μη εν προσευχη και νηστεια[17:21]{.aside}

αναστρεφομενων δε αυτων εν τη γαλιλαια ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα εγερθησεται και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε αυτων εις [κ]{.greek-supplied}απερναουμ προσηλθον οι τα διδραχμα λαμβανοντες τω πετρω και ειπον ο διδασκαλος υμων ου τελει τα διδραχμα[17:24]{.aside}

λεγει ναι και οτε εισηλθεν εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο τινων [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} τελη η κηνσον απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

[λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [αλλοτριων]{.greek-omitted} εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις την θαλασσαν βαλε αγκιστρον και τον [αναβαινοντα]{.greek-omitted} [αναβαντα]{.greek-added} πρωτον ιχθυν αρον και ανοιξας το στομα αυτου ευρησεις στατηρα εκεινον λαβων δος [αυτοις]{.greek-omitted} αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ω[ρα]{.unclear} προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες τις αρα μειζων εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη στραφητε και γενησθε ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο ουτος εστιν ο μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} δεξηται παιδιον τοιουτον εν επι τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν σκανδαλιση ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα [κρεμασθη]{.greek-omitted} [μυλος]{.greek-omitted} [μυλονος]{.greek-added} ονικος [εις]{.greek-omitted} [επι]{.greek-added} τον τραχηλον αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [του]{.greek-added} ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

ει δε η χειρ σου η ο πους σου σκανδαλιζει σε εκκοψον αυτα και βαλε απο σου καλον σοι [εστιν]{.greek-omitted} εισελθειν εις την ζωην χωλον η κυλλον η δυο χειρας η δυο ποδας εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και ει [ο]{.greek-omitted} οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι εστιν μονοφθαλμον [εισελθειν]{.greek-added} εις την ζωην [εισελθειν]{.greek-omitted} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

ορατε μη καταφρονησητε ενος των μικρων τουτων [λεγω]{.greek-omitted} [γαρ]{.greek-omitted} [υμιν]{.greek-omitted} οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} το προσωπον του [πατρος]{.greek-abbr} μου του εν ουρανοις[18:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο υιος του [ανθρωπου]{.greek-abbr} [ζητησαι]{.greek-added} [και]{.greek-added} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει [εαν]{.greek-omitted} [ε[―]{.gap}εν]{.greek-added} [[εεν]{.corr}]{.greek-added} γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα ενενηκοντα εννεα επι τα ορη [και]{.greek-added} πορευθεις [ζητει]{.greek-omitted} [ζητη]{.greek-added} το πλανωμενον[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ [αυτω]{.greek-omitted} [αυτο]{.greek-added} μαλλον η επι τοις ενενηκοντα εννεα τοις μη [πεπλανημενοις]{.greek-omitted} [πλανηθεισιν]{.greek-added}[18:13]{.aside}

ουτως ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} θελημα εμπροσθεν του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [μου]{.greek-added} του εν [ουρανοις]{.greek-abbr} ινα αποληται εις των μικρων τουτων[18:14]{.aside}

εαν δε [αμαρτηση]{.greek-omitted} [αμαρτη]{.greek-added} εις σε ο αδελφος σου υπαγε [και]{.greek-omitted} [ελεγξον]{.greek-omitted} [ελεξον]{.greek-added} αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη ακουση παραλαβε μετα [σου]{.greek-omitted} [σεαυτου]{.greek-added} ετι ενα η δυο ινα επι στοματος δυο μαρτυρων [η]{.greek-omitted} [και]{.greek-added} τριων [σταθη]{.greek-omitted} [σταθησεται]{.greek-added} παν ρημα[18:16]{.aside}

εαν δε παρακουση αυτων ειπε τη εκκλησια εαν δε και της εκκλησιας [παρακουση]{.greek-omitted} [παρα]{.greek-added} [κουση]{.greek-added} εστω σοι ωσπερ ο εθνικος και ο τελωνης[18:17]{.aside}

[παλιν]{.greek-omitted} αμην λεγω υμιν οτι εαν δυο υμων συμφωνησωσιν επι της γης περι παντος πραγματος ου εαν αιτησωνται γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[18:19]{.aside}

ου γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο η τρεις συνηγμενοι εις το εμον ονομα εκει ειμι εν μεσω αυτων[18:20]{.aside}

τοτε προσελθων αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-omitted} ποσακις αμαρτησει εις εμε ο αδελφος μου και αφησω αυτω εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} ου λεγω σοι εως επτακις αλλ εως εβδομηκοντακις επτα[18:22]{.aside}

δια τουτο ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος [ηθελησεν]{.greek-omitted} [ηθελησε]{.greek-added} [συναραι]{.greek-omitted} [συναγαι]{.greek-added} [λογον]{.greek-omitted} [λογων]{.greek-added} μετα των δουλων αυτου[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε [αυτου]{.greek-omitted} [αυτον]{.greek-added} αποδουναι εκελευσεν αυτον ο [κυριος]{.greek-abbr} αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος [εκεινος]{.greek-added} προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} μακροθυμησον επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο [κυριος]{.greek-abbr} του δουλου εκεινου απελυσεν αυτον και το δανειον αφηκεν αυτω[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον [δηναρια]{.greek-omitted} [διναρια]{.greek-added} και κρατησας αυτον [επνιγεν]{.greek-omitted} [επνιγε]{.greek-added} λεγων αποδος μοι ει τι οφειλεις[18:28]{.aside}

πεσων ουν ο συνδουλος [αυτου]{.greek-omitted} εις τους ποδας αυτου παρεκαλει αυτον λεγων μακροθυμησον επ εμοι και [παντα]{.greek-added} [σοι]{.greek-added} αποδωσω [σοι]{.greek-omitted}[18:29]{.aside}

ο δε ουκ ηθελεν [αλλα]{.greek-omitted} [αλλ]{.greek-added} απελθων εβαλεν αυτον εις φυλακην εως ου αποδω [παν]{.greek-added} το οφειλομενον[18:30]{.aside}

ιδοντες δε οι συνδουλοι [αυτου]{.greek-omitted} τα γενομενα ελυπηθησαν σφοδρα και ελθοντες διεσαφησαν τω [κυριω]{.greek-abbr} [εαυτων]{.greek-omitted} [αυτων]{.greek-added} παντα τα γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο [κυριος]{.greek-abbr} αυτου λεγει αυτω δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι επει παρεκαλεσας με[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως και εγω σε [ηλεησα]{.greek-omitted} [ελεησα]{.greek-added}[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} αυτου παρεδωκεν αυτον τοις βασανισταις εως ου αποδω παν το οφειλομενον αυτω[18:34]{.aside}

ουτως και ο [πατηρ]{.greek-abbr} [μου]{.greek-omitted} [ημων]{.greek-added} ο [επουρανιος]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} ποιησει υμιν εαν μη αφητε εκαστος τω αδελφω αυτου απο των καρδιων υμων τα παραπτωματα [αυτων]{.greek-omitted} [αυτου]{.greek-added}[18:35]{.aside}

### Chapter 19

και εγενετο οτε [ετελεσεν]{.greek-omitted} [ετελεσε]{.greek-added} ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και [ηκολουθησαν]{.greek-omitted} [ηκουλουθησαν]{.greek-added} αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και προσηλθον [αυτω]{.greek-omitted} οι φαρισαιοι [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} πειραζοντες αυτον και λεγοντες [αυτω]{.greek-omitted} ει εξεστιν [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν [αυτοις]{.greek-omitted} [αυτου]{.greek-added} ουκ ανεγνωτε οτι ο ποιησας απ αρχης αρσεν και θηλυ [εποιησεν]{.greek-omitted} [εποιη]{.greek-added} [σεν]{.greek-added} αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-added} και την [μητερα]{.greek-abbr} και προσκολληθησεται τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ενετειλατο δουναι βιβλιον αποστασιου και απολυσαι αυτην[19:7]{.aside}

λεγει αυτοις οτι [μωσης]{.greek-omitted} [μωυσης]{.greek-added} προς την σκληροκαρδιαν υμων επετρεψεν υμιν απολυσαι τας γυναικας υμων [απ]{.greek-omitted} [εξ]{.greek-added} αρχης δε ου [γεγονεν]{.greek-omitted} [γεγραπται]{.greek-added} [ουτος]{.greek-added} [ουτως]{.corr}[19:8]{.aside}

λεγω δε υμιν οτι ος αν απολυση την γυναικα αυτου μη επι πορνεια και [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} αλλην μοιχαται [και]{.greek-omitted} [ο]{.greek-omitted} [απολελυμενην]{.greek-omitted} [γαμησας]{.greek-omitted} [μοιχαται]{.greek-omitted}[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτως εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου [συμφερει]{.greek-omitted} [συμφερε]{.greek-added} γαμησαι[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες [χωρουσιν]{.greek-omitted} [χωρουσι]{.greek-added} τον λογον τουτον αλλ οις δεδοται[19:11]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ ευνουχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} εγεννηθησαν ουτως και εισιν ευνουχοι οιτινες ευνουχισθησαν υπο των [ανθρωπων]{.greek-abbr} και εισιν ευνουχοι οιτινες ευνουχισαν εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε προσηνεχθη αυτω παιδια ινα τας χειρας επιθη αυτοις και προσευξηται οι δε μαθηται [επετιμησαν]{.greek-omitted} [επετημησαν]{.greek-added} αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-added} αφετε τα παιδια και μη κωλυετε αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

[και]{.greek-omitted} [επιθεις]{.greek-omitted} [αυτοις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} επορευθη εκειθεν[19:15]{.aside}

και ιδου [εις]{.greek-omitted} [προσελθων]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [νεανισκος]{.greek-added} [αυτον]{.greek-added} [και]{.greek-added} [λεγων]{.greek-added} διδασκαλε αγαθε τι αγαθον ποιησω ινα [εχω]{.greek-omitted} ζωην αιωνιον [κληρονομησω]{.greek-added}[19:16]{.aside}

ο δε [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr} ει δε θελεις εισελθειν εις την [ζωην]{.greek-omitted} [βασιλειαν]{.greek-added} τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το ου φονευσεις ου μοιχευσεις ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} [[σου]{.unclear}]{.greek-added} και αγαπησεις τον πλησιον σου ως [σ]{.greek-supplied}εαυτον[19:19]{.aside}

λεγει αυτω ο νεανισκος παντα ταυτα εφυλαξαμην εκ [νεοτητος]{.greek-omitted} [νε]{.greek-added} [οτιτος]{.greek-added} μου τι ετι υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελεις τελειος ειναι υπαγε πωλησον σου τα υπαρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει [μοι]{.greek-omitted} [μη]{.greek-added}[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον απηλθεν λυπουμενος ην γαρ [εχων]{.greek-omitted} [εχω]{.greek-added} κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως [εισελευσεται]{.greek-added} πλουσιος [εισελευσεται]{.greek-omitted} εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν [δε]{.greek-omitted} λεγω υμιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} εστιν καμηλον δια [τρυπηματος]{.greek-omitted} [τριμαλιας]{.greek-added} ραφιδος διελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[19:24]{.aside}

ακουσαντες δε [οι]{.greek-omitted} [ει]{.greek-added} μαθηται αυτου εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

εμβλεψας δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} [παρα]{.greek-omitted} [δε]{.greek-omitted} [θεω]{.greek-omitted} [παντα]{.greek-omitted} [δυνατα]{.greek-omitted}[19:26]{.aside}

[τοτε]{.greek-omitted} αποκριθεις [δε]{.greek-added} ο πετρος ειπεν αυτω [[κυριε]{.greek-abbr}]{.greek-added} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν [καθηση]{.greek-added} [καθιση]{.corr} ο υιος του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου [καθισεσθε]{.greek-omitted} [καθησεσθε]{.greek-added} και υμεις επι δωδεκα θρονους κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας [ος]{.greek-omitted} [αφηκεν]{.greek-omitted} [οστις]{.greek-added} [αφηκας]{.greek-added} οικιας [η]{.greek-added} [αγρους]{.greek-added} η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα [η]{.greek-omitted} [αγρους]{.greek-omitted} ενεκεν του ονοματος μου [εκατονταπλασιονα]{.greek-omitted} [πολλαπλασιονα]{.greek-added} ληψεται και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι [και]{.greek-omitted} εσχατοι πρωτοι[19:30]{.aside}

### Chapter 20

ομοια [γ]{.greek-supplied}αρ εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

και συμφωνησας μετα των εργατων [αυτου]{.greek-added} εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι τριτην ωραν ειδεν αλλους εστωτας εν τη [αγορα]{.greek-omitted} [αγωρα]{.greek-added} αργους[20:3]{.aside}

και εκεινοις ειπεν υπαγετε και υμεις εις τον αμπελωνα και ο [[αν]{.unclear}]{.greek-added} [εαν]{.corr} [η]{.greek-omitted} δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν [δε]{.greek-added} εξελθων περι εκτην και ενατην ωραν εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι [ωδε]{.greek-omitted} [εστηκατε]{.greek-omitted} ολην την ημεραν [ωδε]{.greek-added} [εστηκατε]{.greek-added} αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις [ημας]{.greek-omitted} [υμας]{.greek-added} εμισθωσατο λεγει αυτοις υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον ληψεσθε[20:7]{.aside}

οψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι πλειονα ληψονται και ελαβον και [αυτοι]{.greek-omitted} [αυτη]{.greek-added} ανα δηναριον[20:10]{.aside}

[λαβοντες]{.greek-omitted} [λαβον]{.greek-added} [τες]{.greek-added} δε [εγογγυζον]{.greek-omitted} [διεγογγυζον]{.greek-added} κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι [ουτοι]{.greek-omitted} [ουτι]{.greek-added} οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις [βαστασασε]{.greek-added} [βαστασασιν]{.greek-omitted} [[βαστασασι]{.corr}]{.greek-added} το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων εταιρε ουκ αδικω σε ουχι [δηναριου]{.greek-omitted} [δ[―]{.gap}ναριου]{.greek-added} [[δυναριου]{.corr}]{.greek-added} συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω εσχατω δουναι ως και [σοι]{.greek-omitted} [συ]{.greek-added}[20:14]{.aside}

η ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι [ποιησαι]{.greek-omitted} ο θελω [ποιησαι]{.greek-added} εν τοις εμοις ει [ο]{.greek-omitted} οφθαλμος σου [προ]{.greek-added} [πονηρος]{.corr} εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι και οι πρωτοι εσχατοι πολλοι γαρ [εισιν]{.greek-omitted} [εισοι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

[κ]{.greek-supplied}αι αναβαινων ο [ιησους]{.greek-abbr} εις ιεροσολυμα [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} τους δωδεκα μαθητας [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [αυτου]{.greek-added} [και]{.greek-added} εν τη οδω [και]{.greek-omitted} ειπεν αυτοις[20:17]{.aside}

ιδου [αναβαινομεν]{.greek-omitted} [αναβενομεν]{.greek-added} εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον [θανατω]{.greek-omitted}[20:18]{.aside}

[και]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} τοις εθνεσιν εις το [εμπεξαι]{.greek-added} [εμπαιξαι]{.corr} και [μαστηγωσαι]{.greek-added} [μαστιγωσαι]{.corr} και σταυρωσαι και τη τριτη ημερα αναστησεται[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και [αιτουσα]{.greek-omitted} [ετουσα]{.greek-added} τι παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι θελεις [ο]{.greek-added} [δε]{.greek-added} λεγει αυτω ειπε ινα καθισωσιν [ουτοι]{.greek-omitted} [ουτη]{.greek-added} οι δυο [μου]{.greek-added} υιοι [μου]{.greek-omitted} εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν [αυτη]{.greek-added} ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω μελλω πινειν η το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

[και]{.greek-omitted} λεγει αυτοις το μεν ποτηριον μου [πιεσθε]{.greek-omitted} [πιεσθαι]{.greek-added} και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} το δε καθισαι εκ δεξιων μου και εξ ευωνυμων μου ουκ εστιν εμον δουναι αλλ οις ητοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμ[εν]{.greek-supplied}ος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη εν υμιν μεγας γενεσθαι [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[20:26]{.aside}

και ος εαν θελη εν υμιν ειναι πρωτος εστω υμων δουλος[20:27]{.aside}

ωσπερ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και εκπορευο[μ]{.greek-supplied}ενων αυτων απο ιεριχω ηκολουθησεν αυτω οχλος πολυς[20:29]{.aside}

και ιδου δυο τυφλοι καθημενοι παρα την οδον [ακουσαντες]{.greek-omitted} [ηκουσαν]{.greek-added} οτι ιησους παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} υιος [δαυιδ]{.greek-abbr}[20:30]{.aside}

[ο]{.greek-omitted} [οι]{.greek-added} δε [οχλος]{.greek-omitted} [οχλοι]{.greek-added} [επετιμησεν]{.greek-omitted} [επετιμησαν]{.greek-added} αυτοις ινα σιωπησωσιν οι δε μειζον [εκραζον]{.greek-omitted} [εκραξαν]{.greek-added} λεγοντες [[κυριε]{.greek-abbr}]{.greek-added} ελεησον ημας [κυριε]{.greek-omitted} υιος [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-abbr} [ε]{.greek-supplied}φωνησεν αυτους και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε [ινα]{.greek-added} ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-abbr} ινα [ανοιχθωσιν]{.greek-omitted} [ανοιγωσιν]{.greek-added} [ημων]{.greek-omitted} οι οφθαλμοι [ημων]{.greek-added}[20:33]{.aside}

σπλαγχνισθεις δε ο [ιησους]{.greek-abbr} ηψατο των οφθαλμων αυτων και ευθεως ανεβλεψαν [αυτων]{.greek-omitted} [οι]{.greek-omitted} [οφθαλμοι]{.greek-omitted} και [ηκολουθησαν]{.greek-omitted} [ηκολουθη]{.greek-added} [σαν]{.greek-added} αυτω[20:34]{.aside}

### Chapter 21

και οτε ηγγισαν εις ιεροσολυμα και ηλθον εις [βηθσφαγη]{.greek-omitted} [βηθσφαγην]{.greek-added} [και]{.greek-added} [βηθανιαν]{.greek-added} προς το ορος των ελαιων τοτε ο [ιησους]{.greek-abbr} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} δυο μαθητας[21:1]{.aside}

λεγων [αυτοις]{.greek-omitted} [αυτων]{.greek-added} [πορευθητε]{.greek-omitted} [πορευεσθε]{.greek-added} εις την κωμην την [απεναντι]{.greek-omitted} [κατεναντι]{.greek-added} υμων και ευθεως ευρησετε ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο [κυριος]{.greek-abbr} αυτων χρειαν εχει [και]{.greek-added} ευθεως [δε]{.greek-omitted} αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι [πραυς]{.greek-omitted} [πραος]{.greek-added} και επιβεβηκως επι ονον και [επι]{.greek-added} πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες καθως προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και τον πωλον και επεθηκαν επανω αυτων τα ιματια αυτων και [επεκαθισεν]{.greek-omitted} [εκαθισεν]{.greek-added} επανω αυτων[21:7]{.aside}

ο δε πλειστος οχλος εστρωσαν [εαυτων]{.greek-omitted} τα ιματια [αυτων]{.greek-added} εν τη οδω αλλοι δε εκοπ[τον]{.greek-supplied} κλαδους απο των δενδρων και εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

και εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον [του]{.greek-omitted} [θεου]{.greek-omitted} και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} παντας τους [πωλουντας]{.greek-omitted} [πολουντας]{.greek-added} και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added} και τας καθεδρας [των]{.greek-omitted} [τον]{.greek-added} πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο οικος μου οικος προσευχης κληθησεται υμεις δε αυτον εποιησατε σπηλαιον ληστων[21:13]{.aside}

και [π]{.greek-supplied}ροσηλθον αυτω [τυφλοι]{.greek-added} [και]{.greek-added} χωλοι [και]{.greek-omitted} [τυφλοι]{.greek-omitted} εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α εποιησεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων κατηρτισω αινον[21:16]{.aside}

και καταλιπων αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη [εκ[η]{.unclear}]{.greek-added} [εκει]{.corr}[21:17]{.aside}

πρωιας δε επαναγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις την πολιν επεινασεν [[επεινασε]{.corr}]{.greek-added}[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν [εν]{.greek-omitted} [αυτη]{.greek-omitted} ει μη φυλλα μονον και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη παραχρημα η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

[αποκρηθεις]{.greek-added} [αποκριθεις]{.corr} δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν εχητε πιστιν και μη διακριθητε ου μονον το της συκης ποιησετε αλλα καν τω ορει τουτω ειπητε αρθητι και βληθητι εις την θαλασσαν γενησεται[21:21]{.aside}

και παντα οσα [εαν]{.greek-omitted} [αν]{.greek-added} αιτησητε εν τη προσευχη πιστευοντες ληψεσθε[21:22]{.aside}

και ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις σοι [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω υμας καγω [ενα]{.greek-added} λογον [ενα]{.greek-omitted} ον εαν ειπητε μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο [παρ]{.greek-omitted} [εαυτοις]{.greek-omitted} λεγοντες εαν [ειπωμεν]{.greek-omitted} [ειπω]{.greek-added} εξ [ουρανου]{.greek-abbr} ερει ημιν δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ [εχουσιν]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} ως προφητην [εχουσι]{.greek-added} [τον]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added}[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} ειπον ουκ οιδαμεν εφη αυτοις και αυτος ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} [τις]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} τεκνα δυο και προσελθων τω πρωτω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε μεταμεληθεις [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:29]{.aside}

και προσελθων τω [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν ωσαυτως ο δε αποκριθεις ειπεν εγω [κυριε]{.greek-abbr} και ουκ απηλθεν [[απηλθε]{.corr}]{.greek-added}[21:30]{.aside}

τις εκ των δυο [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} το θελημα του [πατρος]{.greek-abbr} [λεγουσιν]{.greek-omitted} [λεγου]{.greek-added} [σιν]{.greek-added} αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} [αμην]{.greek-omitted} [αμιν]{.greek-added} λεγω υμιν οτι οι τελωναι και αι πορναι [προαγουσιν]{.greek-omitted} [υμας]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[21:31]{.aside}

[ηλθεν]{.greek-omitted} [γαρ]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [ιωαννης]{.greek-omitted} [εν]{.greek-omitted} [οδω]{.greek-omitted} [δικαιοσυνης]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [επιστευσατε]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [τελωναι]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [πορναι]{.greek-omitted} επιστευσαν αυτω υμεις δε ιδοντες ου μετεμεληθητε υστερον του πιστευσαι αυτω[21:32]{.aside}

[αλλην]{.greek-omitted} [αλην]{.greek-added} παραβολην [ακουσατε]{.greek-omitted} [ηκουσατε]{.greek-added} [ανθρωπος]{.greek-abbr} τις ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} και ωρυξεν εν αυτω ληνον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε [ηγγισεν]{.greek-omitted} [ηγγικεν]{.greek-added} ο [καιρος]{.greek-omitted} [κερος]{.greek-added} των καρπων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους τον υιον αυτου λεγων εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον ειπον εν εαυτοις ουτος εστιν ο κληρονομος [δευτε]{.greek-omitted} [δευ]{.greek-added} αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

[λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} κακους κακως απολεσει αυτους και τον αμπελωνα [εκδωσεται]{.greek-omitted} [εκδοσεται]{.greek-added} αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις καιροις αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε ανεγνωτε εν ταις γραφαις λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται εθνει ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση [λικμησει]{.greek-omitted} [λικμισει]{.greek-added} αυτον[21:44]{.aside}

και ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παραβολας [αυτου]{.greek-omitted} [αυτων]{.greek-added} εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι [εφοβηθησαν]{.greek-omitted} [εφοβηθη]{.greek-added} [σαν]{.greek-added} τους οχλους [επειδη]{.greek-omitted} [επιδη]{.greek-added} ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} ειπεν αυτοις εν παραβολαις [λεγων]{.greek-omitted}[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω αυτου[22:2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα σιτιστα τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και [ακουσαν]{.greek-added} [ακουσας]{.corr} ο βασιλευς εκεινος ωργισθη και πεμψας τα [στρατευματα]{.greek-omitted} [στρατευμα]{.greek-added} αυτου [απωλεσεν]{.greek-omitted} [απολεσε]{.greek-added} τους φονεις εκεινους και την πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενπρησε]{.greek-added}[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας [διεξοδους]{.greek-omitted} [διεξο]{.greek-added} [δους]{.greek-added} των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον [παντας]{.greek-omitted} οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ [ενδεδυμενον]{.greek-omitted} [ενδεδιμενον]{.greek-added} ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε [εφιμωθη]{.greek-omitted} [εφημωθη]{.greek-added}[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου [χειρας]{.greek-added} [και]{.greek-added} ποδας [και]{.greek-omitted} [χειρας]{.greek-omitted} αρατε αυτον και [εκβαλετε]{.greek-omitted} [εκβαλλετε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον ελαβον οπως [παγιδευσωσιν]{.greek-added} αυτον [παγιδευσωσιν]{.greek-omitted} εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι αληθης ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι κηνσον καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του κηνσου οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις αποδοτε [ουν]{.greek-omitted} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον [απηλθον]{.greek-omitted} [απηλθαν]{.greek-added}[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι οι λεγοντες μη ειναι αναστασιν και [επηρωτησαν]{.greek-omitted} [επιρωτησαν]{.greek-added} αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης ειπεν εαν τις αποθανη μη εχων τεκνα επιγαμβρευσει ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος γαμησας [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και μη εχων σπερμα [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε [γαμουσιν]{.greek-omitted} [γαμουνται]{.greek-added} ουτε [εκγαμιζονται]{.greek-omitted} [ενγαμιζονται]{.greek-added} αλλ ως αγγελοι του [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημωσε]{.greek-added} τους σαδδουκαιους συνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια [εντολη]{.greek-omitted} [εντωλη]{.greek-added} μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη [τη]{.greek-added} [καρδια]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [ολη]{.greek-omitted} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη εστιν πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων [επηρωτησεν]{.greek-omitted} [επιρωτησεν]{.greek-added} αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} καλει αυτον [κυριον]{.greek-abbr} πως υιος αυτου εστιν[22:45]{.aside}

και ουδεις εδυνατο [αποκριθηναι]{.greek-added} αυτω [αποκριθηναι]{.greek-omitted} λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαληπε]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας εκαθισαν οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

[παντα]{.greek-omitted} [παντες]{.greek-added} ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και ποιειτε κατα δε τα εργα αυτων μη ποιειτε [λεγουσιν]{.greek-omitted} [λεγου]{.greek-added} [σι]{.greek-added} γαρ και ου [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} γαρ φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων [πι]{.greek-added} [ποιουσιν]{.greek-omitted} [[ποιουσι]{.corr}]{.greek-added} προς το [θεαθηναι]{.greek-omitted} [θεαθυναι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} δε τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} τε την πρωτοκλισιαν εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} [ραββι]{.greek-omitted} [ραμβι]{.greek-added} [ραββι]{.greek-omitted} [ραμβι]{.greek-added}[23:7]{.aside}

υμεις δε μη κληθητε [ραββι]{.greek-omitted} [ραμβι]{.greek-added} εις γαρ [εστιν]{.greek-omitted} [υμων]{.greek-omitted} ο καθηγητης ο [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε υμων επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr}[23:9]{.aside}

μηδε κληθητε καθηγηται εις γαρ [υμων]{.greek-omitted} εστιν [ημων]{.greek-added} ο καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων εσται υμων διακονος[23:11]{.aside}

οστις δε υψωσει [εαυτον]{.greek-omitted} [αυτον]{.greek-added} ταπεινωθησεται και οστις ταπεινωσει εαυτον [υψω]{.greek-added} [υψωθησεται]{.greek-omitted} [θησεται]{.greek-added}[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρσαιοι]{.greek-added} υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χειρων]{.greek-added} [και]{.greek-added} [προφανει]{.greek-added} [[προφασει]{.corr}]{.greek-added} [μακαρ]{.greek-added} [[μικαρ]{.corr}]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι περιαγετε την θαλασσαν και την [ξηραν]{.greek-omitted} [ξυραν]{.greek-added} ποιησαι ενα προσηλυτον και οταν γενηται [ποιειτε]{.greek-omitted} [ποιειστε]{.greek-added} αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν ομοση εν τω ναω ουδεν εστιν ος δ αν ομοση εν τω χρυσω του ναου οφειλει[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και [ος]{.greek-omitted} [εαν]{.greek-omitted} [ομοση]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [θυσιαστηριω]{.greek-omitted} [ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} ος δ αν ομοση εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι τι γαρ μειζον το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω [θυσιαστηριω]{.greek-omitted} [θυσιαστη]{.greek-added} [ριω]{.greek-added} ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο [ομ[ω]{.unclear}σας]{.greek-added} [ομοσας]{.corr} εν τω ναω ομνυει εν αυτω και εν τω κατοικησαντι αυτον[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το κυμινον και αφηκατε τα βαρυτερα του νομου την κρισιν και [τον]{.greek-omitted} [το]{.greek-added} ελεον και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα [και]{.greek-added} την [δε]{.greek-omitted} καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι καθαριζετε το εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και αδικιας[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [παρομοιαζετε]{.greek-omitted} [παρομοια]{.greek-added} [ζετε]{.greek-added} [ταφοις]{.greek-omitted} [ταφους]{.greek-added} κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις εξωθεν μεν [φαινεσθε]{.greek-omitted} [φενεσθε]{.greek-added} τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι εστε [υποκρισεως]{.greek-omitted} [και]{.greek-omitted} [ανομιας]{.greek-omitted}[23:28]{.aside}

[ουαι]{.greek-omitted} [υμιν]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [φαρισαιοι]{.greek-omitted} υποκριται οτι οικοδομειτε τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει ημεν εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν ημεν κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και σταυρωσετε και εξ αυτων μαστιγωσετε εν ταις συναγωγαις υμων και διωξετε απο πολεως εις πολιν[23:34]{.aside}

οπως ελθη εφ υμας παν αιμα δικαιον εκχυνομενον επι της γης απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεινουσα]{.greek-added} τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον τροπον επισυναγει ορνις τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται [υμιν]{.greek-omitted} ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη με ιδητε απ αρτι εως αν [ειπητε]{.greek-omitted} [ειπειτε]{.greek-added} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

[και]{.greek-omitted} εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτου επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου βλεπετε [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου [μη]{.greek-added} καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον [αυτω]{.greek-omitted} οι μαθηται [αυτω]{.greek-added} κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added}[24:5]{.aside}

[μελλησετε]{.greek-omitted} [μελλησεται]{.greek-added} δε ακουειν πολεμους και ακοας πολεμων ορατε μη θροεισθε δει γαρ παντα γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εστι]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος [ε]{.unclear}πι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και λοιμοι και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη ωδινων[24:8]{.aside}

τοτε παραδωσουσιν υμας εις θλιψιν και αποκτενουσιν υμας και εσεσθε μισουμενοι υπο παντων των εθνων δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησον[ται]{.greek-supplied} πολλοι και αλληλους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} και μισησουσιν αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} πολλους[24:11]{.aside}

και δια το πλ[η]{.unclear}θυνθηναι την αν[ο]{.unclear}μιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και [κη]{.greek-added} [κη]{.greek-added} [ρηχθησεται]{.greek-added} [κηρυχθησεται]{.greek-omitted} [ρυχθησεται]{.greek-added} [τουτο]{.greek-omitted} το ευαγγελιον [τουτο]{.greek-added} της βασιλειας εν ολη τη οικουμενη εις μαρτυριον [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν ιδητε το βδελυγμα της ερημωσεως το ρηθεν δια [δανιηλ]{.greek-omitted} του προφητου εστως εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν επι τα ορη[24:16]{.aside}

ο επι του δωματος μη καταβαινετω [αραι]{.greek-omitted} [αρε]{.greek-added} τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος μηδε σαββατω[24:20]{.aside}

εσται γαρ τοτε θλιψις μεγαλη οια ου γεγονεν απ αρχης κοσμου [εως]{.greek-omitted} [μεχρι]{.greek-added} του νυν ουδ ου μη γενηται[24:21]{.aside}

και ει μη εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι ημεραι [εκειναι]{.greek-omitted} [εκεινναι]{.greek-added}[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ [ψευδοχρηστοι]{.greek-added} [ψευδοχριστοι]{.corr} και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια μεγαλα και τερατα ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω εστιν μη εξελθητε ιδου εν τοις ταμειοις μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται [και]{.greek-omitted} η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ [εαν]{.greek-omitted} [αν]{.greek-added} η το πτωμα εκει συναχθησονται οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του ουρανου και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε κοψονται πασαι αι φυλαι της γης και οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου μετα σαλπιγγος φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξουσι]{.greek-added} τους εκλεκτους [αυτου]{.greek-omitted} εκ των [τεσσαρων]{.greek-omitted} [τεσαρων]{.greek-added} ανεμων απ ακρων [ουρανων]{.greek-abbr} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος [αυτης]{.greek-omitted} [γενηται]{.greek-omitted} απαλος και τα φυλλα εκφυη γινωσκετε οτι εγγυς [το]{.greek-omitted} [θερος]{.greek-omitted}[24:32]{.aside}

[ουτως]{.greek-omitted} [και]{.greek-omitted} [υμεις]{.greek-omitted} [οταν]{.greek-omitted} [ιδητε]{.greek-omitted} [ταυτα]{.greek-omitted} [παντα]{.greek-omitted} [γινωσκετε]{.greek-omitted} [οτι]{.greek-omitted} [εγγυς]{.greek-omitted} εστιν επι θυραις[24:33]{.aside}

αμην λεγω υμιν ου μη παρελθη η γενεα αυτη εως αν παντα [ταυτα]{.greek-omitted} γενηται[24:34]{.aside}

[ο]{.greek-omitted} [ουρανος]{.greek-abbr} και η γη [παρελευσονται]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [λογοι]{.greek-omitted} [μου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[24:35]{.aside}

περι δε της ημερας εκεινης και ωρας ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις προ του κατακλυσμου τρωγοντες και πινοντες γαμουντες και εκγαμιζοντες αχρι ης ημερας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο αληθουσαι εν τω μυλωνι μια παραλαμβανεται και μια αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει [ηδει]{.greek-omitted} [ηδι]{.greek-added} ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ [αν]{.greek-omitted} [ειασεν]{.greek-omitted} [ειασε]{.greek-added} διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της θεραπειας αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [αυτου]{.greek-added} εσθιειν δε και πινειν μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και [ο]{.greek-omitted} βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε [ημιν]{.greek-omitted} [υμιν]{.greek-added} εκ του ελαιου υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε [ου]{.greek-added} [μη]{.greek-added} [ουκ]{.corr} [αρκεση]{.greek-omitted} [αρκεσει]{.greek-added} ημιν και υμιν πορευεσθε δε μαλλον προς τους πωλουντας και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-omitted} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν [εν]{.greek-omitted} [η]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ερχεται]{.greek-omitted}[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων [ηργασατο]{.greek-added} [ειργασατο]{.corr} εν αυτοις και εποιησεν αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο [εκερδησεν]{.greek-omitted} [εκερδησε]{.greek-added} και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και [απεκρυψεν]{.greek-omitted} [απεκρυψε]{.greek-added} το αργυριον του [κυριου]{.greek-abbr} αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και συναιρει μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα [επ]{.greek-omitted} [εν]{.greek-added} αυτοις[25:20]{.aside}

εφη δε αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων [δε]{.greek-omitted} και ο τα δυο ταλαντα λαβων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και [συναγων]{.greek-omitted} [συνα]{.greek-added} [γων]{.greek-added} οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε ηδεις οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν [τοκω]{.greek-omitted} [τωκω]{.greek-added}[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι [παντι]{.greek-omitted} δοθησεται και [περισσευθησεται]{.greek-omitted} [περισευθησεται]{.greek-added} απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον [εκεινον]{.greek-added} [εκβαλετε]{.greek-omitted} [βαλετε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε καθισει επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην [α]{.greek-added} [φορισει]{.greek-added} [αυτους]{.greek-added} [απ]{.greek-added} [αλληλων]{.greek-added} [ωσπερ]{.greek-added} [ο]{.greek-added} [ποιμην]{.greek-added} αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με ξενος ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με [ησθενησα]{.greek-omitted} [[α]{.unclear}σθενησα]{.greek-added} και επεσκεψασθε με εν φυλακη ημην και [ηλθετε]{.greek-omitted} [ηλθατε]{.greek-added} προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και συνηγαγομεν [η]{.greek-omitted} [γυμνον]{.greek-omitted} [και]{.greek-omitted} [περιεβαλομεν]{.greek-omitted}[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} εφ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε [απ]{.greek-omitted} [α]{.greek-added} [π]{.greek-added} εμου οι [κατηραμενοι]{.greek-omitted} [κατηραμενη]{.greek-added} εις το πυρ το αιωνιον το [ητοιμασμενον]{.greek-omitted} [ημασμενον]{.greek-added} τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ [εδωκατε]{.greek-omitted} [αιδωκατε]{.greek-added} μοι φαγειν εδιψησα και ουκ [εποτισατε]{.greek-omitted} [αιποτισατε]{.greek-added} με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου [περιεβαλετε]{.greek-omitted} [περιευαλετε]{.greek-added} με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται [και]{.greek-added} αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδοθησεται]{.greek-added} εις το σταυρωθηναι[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον ιησουν δολω [κρατησωσιν]{.greek-omitted} [κρατησωσι]{.greek-added} και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε ιησου γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα [βαρυτιμου]{.greek-omitted} [βαριτιμου]{.greek-added} και [κατεχεεν]{.greek-omitted} [κατεχε]{.greek-added} επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η [απωλεια]{.greek-omitted} [απολεια]{.greek-added} αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι [τοις]{.greek-added} πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους παρεχετε τη γυναικι εργον γαρ καλον ειργασατο εις εμε[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} τους πτωχους [γαρ]{.greek-added} [παντοτε]{.greek-added} εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το ενταφιασαι με [εποιησεν]{.greek-omitted} [πεποιηκεν]{.greek-added}[26:12]{.aside}

αμην [γαρ]{.greek-added} λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον [αυτης]{.greek-omitted} [αυτοις]{.greek-added}[26:13]{.aside}

τοτε πορευθεις [εις]{.greek-omitted} [ις]{.greek-added} των δωδεκα ο λεγομενος ιουδας [ισκαριωτης]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [αρχιερεις]{.greek-omitted}[26:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε μοι δουναι καγω υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που θελεις ετοιμασομεν σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα[26:20]{.aside}

και [εσθιοντων]{.greek-omitted} [ευθιοντων]{.greek-added} αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και [λυπουμενοι]{.greek-omitted} [λυπου]{.greek-added} [μενοι]{.greek-added} σφοδρα ηρξαντο λεγειν αυτω εκαστος αυτων [μητι]{.greek-omitted} [μιτη]{.greek-added} εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω τρυβλιω την [χειρα]{.greek-omitted} [χειραν]{.greek-added} ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ [εγεννηθη]{.greek-omitted} [εγενηθη]{.greek-added} ο ανθρωπος εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μητι εγω ειμι [ραββι]{.greek-omitted} [ραμβι]{.greek-added} λεγει αυτω συ ειπας[26:25]{.aside}

[εσθιοντων]{.greek-omitted} [ησθιοντων]{.greek-added} δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [μου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν [οτι]{.greek-omitted} ου μη πιω απ αρτι εκ τουτου του [γεννηματος]{.greek-omitted} [γενηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν αυτο πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω δε ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ομοιως δε [και]{.greek-omitted} παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον [γεθσημανη]{.greek-omitted} [γεθσιμανη]{.greek-added} και λεγει τοις μαθηταις [αυτου]{.greek-added} καθισατε αυτου εως ου απελθων [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added} εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και [προσελθων]{.greek-omitted} [προσελθον]{.greek-added} μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ [και]{.greek-added} [αναστας]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [προσευχης]{.greek-added}[26:39]{.aside}

[και]{.greek-omitted} ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται τουτο το ποτηριον [παρελθειν]{.greek-omitted} [απελθειν]{.greek-added} απ εμου εαν μη αυτο πιω γενηθητω το [θελημα]{.greek-omitted} [θελη]{.greek-added} [μα]{.greek-added} σου[26:42]{.aside}

και ελθων ευρισκει αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο υιος του ανθρωπου παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και [των]{.greek-added} πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον [αν]{.greek-omitted} [εαν]{.greek-added} φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} χαιρε [ραββι]{.greek-omitted} [ραμβι]{.greek-added} και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ ω παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} [εκ]{.greek-added} [εκτεινας]{.greek-omitted} [τεινας]{.greek-added} την χειρα [απεσπασεν]{.greek-omitted} [απεσπασε]{.greek-added} την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} [αποστρεψον]{.greek-omitted} [υποστρεψον]{.greek-added} σου την μαχαιραν εις τον τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν μαχαιρα αποθανουνται[26:52]{.aside}

η δοκεις οτι ου δυναμαι αρτι [παρακαλεσαι]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ου[τ]{.greek-supplied}ως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος ηκολουθει αυτω απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και το συνεδριον ολον εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως [θανατωσωσιν]{.greek-omitted} [θανατωσουσιν]{.greek-added} αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων [ημερων]{.greek-omitted} οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-omitted} [[χριστος]{.greek-abbr}]{.greek-added} συ ειπας πλην λεγω υμιν απ αρτι οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματια αυτου λεγων οτι [εβλασφημησεν]{.greek-omitted} [εβλασφημησε]{.greek-added} τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου [εστιν]{.greek-omitted} [εστι]{.greek-added}[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και [εκολαφισαν]{.greek-omitted} [εκολαφησαν]{.greek-added} αυτον οι δε ερραπισαν[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} [τις]{.greek-omitted} [τι]{.greek-added} εστιν ο [παισας]{.greek-omitted} [πεσας]{.greek-added} σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μια [παιδισκη]{.greek-omitted} [πεδισκη]{.greek-added} λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του [του]{.greek-added} γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν αυτων παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει αυτοις εκει και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος [του]{.greek-omitted} [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και [δησαντες]{.greek-omitted} [δυσαντες]{.greek-added} αυτον απηγαγον και παρεδωκαν αυτον [ποντιω]{.greek-omitted} [ποντιο]{.greek-added} πιλατω τω ηγεμονι[27:2]{.aside}

τοτε ιδων ιουδας ο παραδιδους αυτον οτι κατεκριθη μεταμεληθεις [απεστρεψεν]{.greek-omitted} [απεστρεψε]{.greek-added} τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε ειπον τι προς ημας συ οψει[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} και απελθων [απηγξατο]{.greek-omitted} [απηγξατω]{.greek-added}[27:5]{.aside}

οι δε [αρχιερεις]{.greek-omitted} [αρχι]{.greek-added} [ερεις]{.greek-added} λαβοντες τα αργυρια ειπον [ου]{.greek-supplied}κ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον [κορβαναν]{.greek-omitted} [κορβοναν]{.greek-added} επει τιμη αιματος [εστιν]{.greek-omitted} [εστι]{.greek-added}[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του [τετιμημενου]{.greek-omitted} [τετημημενου]{.greek-added} ον ετιμησαντο [απο]{.greek-omitted} [υπο]{.greek-added} υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα [συνεταξεν]{.greek-omitted} [συνεταξε]{.greek-added} μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν [τ]{.greek-supplied}ου ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και των πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις [ποσα]{.greek-omitted} [τι]{.greek-added} [ουτοι]{.greek-added} σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και ουκ απεκριθη αυτω προς [ουδε]{.greek-omitted} [ουδεν]{.greek-added} εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν [ενα]{.greek-omitted} τω οχλω [ενα]{.greek-added} δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added}[27:16]{.aside}

[συνηγμενων]{.greek-omitted} [συνηγμενον]{.greek-added} ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

[εγινωσκεν]{.greek-added} [ηδει]{.greek-omitted} [γαρ]{.greek-omitted} οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} τον δε [ιησουν]{.greek-abbr} [απολεσωσιν]{.greek-omitted} [απολεσωσοι]{.greek-added}[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν αυτω παντες [σταυρωθητω]{.greek-abbr}[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες [σταυρωθητω]{.greek-abbr}[27:23]{.aside}

ιδων δε ο πιλατος οτι [ουδεν]{.greek-omitted} [δεν]{.greek-added} [ωφελει]{.greek-omitted} [oφελει]{.greek-added} αλλα [μαλον]{.greek-added} [μαλλον]{.corr} θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος [ειμι]{.greek-omitted} [ειμη]{.greek-added} απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις [πας]{.greek-omitted} ο λαος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το αιμα αυτου εφ ημας και επι τα τεκνα [ημων]{.greek-omitted} [υμων]{.greek-added}[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φραγελλωσας παρεδωκεν [αυτοις]{.greek-added} ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την [σπειραν]{.greek-omitted} [σπηραν]{.greek-added}[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα [κοκκινην]{.greek-omitted} [κοκινην]{.greek-added}[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον [επι]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [δεξιαν]{.greek-omitted} [δεξια]{.greek-added} αυτου και γονυπετησαντες εμπροσθεν αυτου [ενεπαιζον]{.greek-omitted} [ενεπεζον]{.greek-added} αυτω λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν [αυτον]{.greek-omitted} [την]{.greek-omitted} [χλαμυδα]{.greek-omitted} [και]{.greek-omitted} [ενεδυσαν]{.greek-omitted} αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

[ε]{.greek-added} [εξερχομενοι]{.greek-omitted} [ξερχομενοι]{.greek-added} δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα [ο]{.greek-omitted} [ος]{.greek-added} εστιν [λεγομενος]{.greek-omitted} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω [οξος]{.greek-added} πιειν [οξος]{.greek-omitted} μετα χολης μεμιγμενον και γευσαμενος ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} πιειν[27:34]{.aside}

[σταυρωσαντες]{.greek-abbr} δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-omitted} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουνται]{.greek-omitted} [στραυρουνται]{.greek-added} συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι [εβλασφημουν]{.greek-omitted} [ευλασφημουν]{.greek-added} αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} [καταβηθι]{.greek-omitted} [καταβηθη]{.greek-added} απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως [δε]{.greek-omitted} και οι αρχιερεις εμπαιζοντες μετα των γραμματεων και πρεσβυτερων και [φ]{.greek-supplied}αρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} εστιν καταβατω νυν απο του [σταυρου]{.greek-abbr} και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} [επ]{.greek-omitted} αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω [νυν]{.greek-omitted} αυτον ει θελει αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι συσταυρωθεντες αυτω ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[27:45]{.aside}

περι δε την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι λιμα σαβαχθανι τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελιπες[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες ελεγον οτι ηλιαν φωνει ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας σωσων αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} [κραξας]{.greek-added} παλιν [κραξας]{.greek-omitted} φωνη μεγαλη [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη εσεισθη και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια ανεωχθησαν και πολλα σωματα των κεκοιμημενων αγιων ηγερθη[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε [εκατονταρχος]{.greek-omitted} [εκατοταρχος]{.greek-added} και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} υιος ην ουτος[27:54]{.aside}

ησαν δε εκει [και]{.greek-added} γυναικες πολλαι απο μακροθεν θεωρουσαι αιτινες [ηκολουθησαν]{.greek-omitted} [ηκουλουθησαν]{.greek-added} τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} μαρια η του ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ ος και αυτος [εμαθητευσεν]{.greek-omitted} [εμαθητευσε]{.greek-added} τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν [αποδοθηναι]{.greek-omitted} [αποδωθηναι]{.greek-added} το σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ ενετυλιξεν αυτο σινδονι καθαρα[27:59]{.aside}

και εθηκεν [αυτο]{.greek-omitted} [αυτον]{.greek-added} εν τω [καινω]{.greek-omitted} [κενω]{.greek-added} αυτου μνημειω ο ελατομησεν εν τη πετρα και προσκυλισας λιθον μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η μαγδαληνη και η αλλη μαρια καθημεναι [απεναντι]{.greek-omitted} [εναντι]{.greek-added} του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς πιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι [εκεινος]{.greek-omitted} ο πλανος [εκεινος]{.greek-added} ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως [της]{.greek-omitted} τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου νυκτος κλεψωσιν αυτον και ειπωσιν τω λαω [οτι]{.greek-added} ηγερθη απο των νεκρων και εσται η εσχατη πλανη χειρων της πρωτης[27:64]{.aside}

εφη δε αυτοις ο πιλατος εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε [δε]{.greek-omitted} σαββατων τη επιφωσκουση [εις]{.greek-omitted} [ει]{.greek-added} μιαν σαββατων [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} μαρια η μαγδαληνη και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} [και]{.greek-added} προσελθων [απεκυλισεν]{.greek-omitted} [απεκυλισε]{.greek-added} τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} μη φοβεισθε υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον [τον]{.greek-added} εσταυρωμενον ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη [γαρ]{.greek-omitted} καθως ειπεν δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ πορευθεισαι ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και [ιδου]{.greek-omitted} προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

[ως]{.greek-omitted} [δε]{.greek-omitted} [επορευοντο]{.greek-omitted} [απαγγειλαι]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} απηντησεν αυταις λεγων χαιρ[ε]{.unclear}τε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν [αυτ[ους]{.unclear}]{.greek-added} [αυτω]{.corr}[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με [οψονται]{.greek-omitted} [οψοντε]{.greek-added}[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της [κουστωδιας]{.greek-omitted} [κουστουδιας]{.greek-added} ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον [τε]{.greek-omitted} λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

[λεγοντες]{.greek-added} [αργυρια]{.greek-added} [ικανα]{.greek-added} [εδωκαν]{.greek-added} [τοις]{.greek-added} [στρατιωταις]{.greek-added} λεγοντες ειπατε οτι οι μαθηται αυτου νυκτος ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις πεισομεν αυτον και υμας αμεριμνους ποιησομεν[28:14]{.aside}

οι δε λαβοντες τα αργυρια [ε]{.greek-supplied}ποιησαν ως εδιδαχθησαν και [διεφημισθη]{.greek-omitted} [δηεφημισθη]{.greek-added} ο λογος ουτος παρα [ιουδαιοις]{.greek-omitted} [ιουδαιων]{.greek-added} μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και [του]{.greek-omitted} αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

