---
title: "Collation of Byz^RP^ vs 30309 (309)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 309 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30309).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 309                                   	| λογος                              	|
| 309 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 309 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 309               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 309                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 309 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 309                                                     	| [―]{.gap}                        	|
:::

## First Thessalonians

### Chapter 1

ωστε γενεσθαι υμας [τυπους]{.greek-omitted} [τυπον]{.greek-added} πασιν τοις πιστευουσιν εν τη μακεδονια και [εν]{.greek-added} τη αχαια[1:7]{.aside}

αφ υμων γαρ εξηχηται ο λογος του [κυριου]{.greek-abbr} ου μονον εν τη μακεδονια και εν τη αχαια [αλλα]{.greek-omitted} [αλλ]{.greek-added} [και]{.greek-omitted} εν παντι τοπω η πιστις υμων η προς τον [θεον]{.greek-abbr} εξεληλυθεν ωστε μη χρειαν [εχειν]{.greek-added} ημας [εχειν]{.greek-omitted} λαλειν τι[1:8]{.aside}

αυτοι γαρ περι ημων απαγγελλουσιν οποιαν εισοδον εσχομεν προς υμας και πως επεστρεψατε προς τον [θεον]{.greek-abbr} απο των ειδωλων δουλευειν [θεω]{.greek-abbr} ζωντι και αληθινω[1:9]{.aside}

και αναμενειν τον [υιον]{.greek-abbr} αυτου εκ των [ουρανων]{.greek-abbr} ον ηγειρεν εκ των νεκρων [ιησουν]{.greek-abbr} τον ρυομενον ημας [απο]{.greek-omitted} [εκ]{.greek-added} της οργης της ερχομενης[1:10]{.aside}

### Chapter 2

αυτοι γαρ οιδατε αδελφοι την εισοδον ημων την προς υμας οτι ου κενη γεγονεν[2:1]{.aside}

αλλα προπαθοντες και υβρισθεντες [καθως]{.greek-omitted} [καθ]{.greek-added} [ο]{.greek-added} οιδατε εν φιλιπποις επαρρησιασαμεθα εν τω [θεω]{.greek-abbr} ημων λαλησαι προς υμας το ευαγγελιον του [θεου]{.greek-abbr} εν πολλω αγωνι[2:2]{.aside}

η γαρ παρακλησις ημων ουκ εκ πλανης ουδε εξ ακαθαρσιας ουτε εν δολω[2:3]{.aside}

αλλα καθως δεδοκιμασμεθα υπο του [θεου]{.greek-abbr} πιστευθηναι το ευαγγελιον ουτως λαλουμεν ουχ ως [ανθρωποις]{.greek-abbr} αρεσκοντες αλλα τω [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} δοκιμαζοντι τας καρδιας ημων[2:4]{.aside}

ουτε γαρ ποτε εν λογω κολακειας εγενηθημεν καθως οιδατε ουτε εν προφασει πλεονεξιας [θεος]{.greek-abbr} μαρτυς[2:5]{.aside}

ουτε ζητουντες εξ [ανθρωπων]{.greek-abbr} δοξαν ουτε αφ υμων ουτε απο αλλων [δυναμενοι]{.greek-omitted} [εν]{.greek-omitted} [βαρει]{.greek-omitted} [ειναι]{.greek-omitted} [ως]{.greek-omitted} [χριστου]{.greek-omitted} [αποστολοι]{.greek-omitted}[2:6]{.aside}

[δυναμενοι]{.greek-added} [εν]{.greek-added} [βαρει]{.greek-added} [ειναι]{.greek-added} [ως]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} [αποστολοι]{.greek-added} αλλ εγενηθημεν [ηπιοι]{.greek-omitted} [νηπιοι]{.greek-added} εν μεσω υμων ως αν τροφος [θαλπη]{.greek-omitted} [θαλπει]{.greek-added} τα εαυτης τεκνα[2:7]{.aside}

ουτως ομειρομενοι υμων ευδοκουμεν μεταδουναι υμιν ου μονον το ευαγγελιον του [θεου]{.greek-abbr} αλλα και τας εαυτων ψυχας διοτι αγαπητοι ημιν [γεγενησθε]{.greek-omitted} [εγενησθε]{.greek-added}[2:8]{.aside}

μνημονευετε γαρ αδελφοι τον κοπον ημων και τον μοχθον νυκτος [γαρ]{.greek-omitted} και ημερας εργαζομενοι προς το μη επιβαρησαι τινα υμων εκηρυξαμεν εις υμας το ευαγγελιον του [θεου]{.greek-abbr}[2:9]{.aside}

υμεις μαρτυρες και ο [θεος]{.greek-abbr} ως οσιως και δικαιως και αμεμπτως υμιν τοις πιστευουσιν εγενηθημεν[2:10]{.aside}

καθαπερ οιδατε ως ενα εκαστον υμων ως [πατηρ]{.greek-abbr} τεκνα εαυτου [παρακαλουντες]{.greek-omitted} [υμας]{.greek-omitted} [και]{.greek-omitted} [παραμυθουμενοι]{.greek-omitted}[2:11]{.aside}

[παρακαλουντες]{.greek-added} [υμας]{.greek-added} και [παραμυθουμενοι]{.greek-added} [και]{.greek-added} [μαρτυρομενοι]{.greek-omitted} [μαρτυρουμενοι]{.greek-added} εις το περιπατησαι υμας αξιως του [θεου]{.greek-abbr} του καλουντος υμας εις την εαυτου βασιλειαν και δοξαν[2:12]{.aside}

δια τουτο και ημεις ευχαριστουμεν τω [θεω]{.greek-abbr} αδιαλειπτως οτι παραλαβοντες λογον ακοης παρ ημων του [θεου]{.greek-abbr} εδεξασθε ου λογον [ανθρωπων]{.greek-abbr} αλλα καθως εστιν αληθως λογον [θεου]{.greek-abbr} ος και [ενερ]{.greek-added} [ενεργειται]{.greek-omitted} [γειται]{.greek-added} εν υμιν τοις πιστευουσιν[2:13]{.aside}

υμεις γαρ μιμηται εγενηθητε αδελφοι των εκκλησιων του [θεου]{.greek-abbr} των ουσων εν [τη]{.greek-omitted} [τηι]{.greek-added} ιουδαια εν [χριστω]{.greek-omitted} [[χωι]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr} οτι τα αυτα επαθετε και υμεις υπο των ιδιων συμφυλετων καθως και αυτοι υπο των ιουδαιων[2:14]{.aside}

των και τον [κυριον]{.greek-abbr} αποκτειναντων [ιησουν]{.greek-abbr} και τους ιδιους προφητας και ημας εκδιωξαντων και [θεω]{.greek-abbr} μη αρεσκοντων και πασιν [ανθρωποις]{.greek-abbr} εναντιων[2:15]{.aside}

κωλυοντων ημας τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} λαλησαι ινα σωθωσιν εις το αναπληρωσαι αυτων τας αμαρτιας παντοτε [εφθασεν]{.greek-omitted} [εφθασε]{.greek-added} δε επ αυτους η οργη εις τελος[2:16]{.aside}

ημεις δε αδελφοι απορφανισθεντες αφ υμων προς καιρον ωρας προσωπω ου καρδια περισσοτερως εσπουδασαμεν το προσωπον υμων ιδειν εν πολλη επιθυμια[2:17]{.aside}

διο ηθελησαμεν ελθειν προς υμας εγω μεν παυλος και απαξ και δις και ενεκοψεν ημας ο σατανας[2:18]{.aside}

τις γαρ ημων ελπις η χαρα η στεφανος καυχησεως η ουχι και υμεις εμπροσθεν του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} εν [τη]{.greek-omitted} [τηι]{.greek-added} αυτου παρουσια[2:19]{.aside}

υμεις γαρ εστε η δοξα ημων και η χαρα[2:20]{.aside}

### Chapter 3

διο μηκετι στεγοντες ευδοκησαμεν καταλειφθηναι εν αθηναις μονοι[3:1]{.aside}

και επεμψαμεν τιμοθεον τον αδελφον ημων και διακονον του [θεου]{.greek-abbr} και συνεργον [ημων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ευαγγελιω]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [στηριξαι]{.greek-omitted} [υμας]{.greek-omitted} [και]{.greek-omitted} [παρακαλεσαι]{.greek-omitted} [υμας]{.greek-omitted} [περι]{.greek-omitted} [της]{.greek-omitted} [πιστεως]{.greek-omitted} [υμων]{.greek-omitted}[3:2]{.aside}

