---
title: "Collation of Byz^RP^ vs 30310 (310)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 310 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30310).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 310                                   	| λογος                              	|
| 310 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 310 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 310               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 310                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 310 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 310                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

σολομων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ασα[1:7]{.aside}

ασα δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ιωσαφατ]{.greek-omitted} [ιωασαφατ]{.greek-added} ιωσαφατ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ο]{.unclear}ζιαν[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωαθαμ ιωαθαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχαζ αχαζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εζεκιαν[1:9]{.aside}

εζεκιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [μανασση]{.greek-omitted} [μανασην]{.greek-added} [μανασσης]{.greek-omitted} [μανασης]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγενησε]{.greek-added} τον αμων αμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεχονιαν και τους αδελφους αυτου [επι]{.greek-omitted} [εκ]{.greek-added} της μετοικεσιας βαβυλωνος[1:11]{.aside}

μετα δε την μετοικεσιαν βαβυλωνος ιεχονιας [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλαθιηλ σαλαθιηλ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβιουδ αβιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιακειμ ελιακειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχειμ αχειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελεαζαρ ελεαζαρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην μνηστευθεισης [γαρ]{.greek-omitted} της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν η συνελθειν αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-omitted} [[πριν]{.greek-abbr}]{.greek-added} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην παραδειγματισαι εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ εφανη αυτω λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη φοβηθης παραλαβειν [μαριαμ]{.greek-omitted} [μαριαν]{.greek-added} την γυναικα σου [το]{.greek-supplied} [γαρ]{.greek-supplied} [εν]{.greek-supplied} αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

[τεξεται]{.greek-omitted} [δε]{.greek-omitted} [υιον]{.greek-omitted} [και]{.greek-omitted} [καλεσεις]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [ιησουν]{.greek-omitted} αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} [δια]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [λεγοντος]{.greek-omitted}[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται [υιον]{.greek-abbr} και [καλεσουσιν]{.greek-omitted} [καλεσουσι]{.greek-added} το ονομα αυτου εμμανουηλ ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

[διεγερθεις]{.greek-omitted} [εγερθεις]{.greek-added} δε ο ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} [μαριαμ]{.greek-added} την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον [υιον]{.greek-abbr} αυτης τον πρωτοτοκον και [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

του δε [ιησου]{.greek-abbr} γεννηθεντος εν [βηθλεεμ]{.greek-omitted} [βιθλεεμ]{.greek-added} της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων ειδομεν γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι αυτω[2:2]{.aside}

ακουσας δε ηρωδης [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} εταραχθη και πασα ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και γραμματεις του λαου επυνθανετο παρ αυτων που ο [χριστος]{.greek-abbr} γενναται[2:4]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} εν [βηθλεεμ]{.greek-omitted} [βιθλεεμ]{.greek-added} της ιουδαιας [ουτως]{.greek-omitted} [γαρ]{.greek-omitted} [γεγραπται]{.greek-omitted} [δια]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted}[2:5]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

[και]{.greek-omitted} [πεμψας]{.greek-omitted} [καλεσας]{.greek-added} [ουν]{.greek-added} αυτους [φησι]{.greek-added} [εις]{.greek-omitted} [βηθλεεμ]{.greek-omitted} [ειπεν]{.greek-omitted} πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ακουσαντες]{.greek-omitted} [του]{.greek-omitted} [βασιλεως]{.greek-omitted} [επορευθησαν]{.greek-omitted} και ιδου [ο]{.greek-omitted} αστηρ ον ειδον εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

[κ]{.unclear}αι ελθοντες [εις]{.greek-omitted} [επι]{.greek-added} την οικιαν ειδον το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσεκυνησαν αυτω και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν [[κ]{.unclear}αι]{.greek-added} [ελθοντες]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [οικιαν]{.greek-added} [ειδον]{.greek-added} [το]{.greek-added} [παιδιον]{.greek-added} [μετα]{.greek-added} [μαριας]{.greek-added} [της]{.greek-added} [[μητρος]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [πεσοντες]{.greek-added} [προσεκυνησαν]{.greek-added} [αυτω]{.greek-added} [και]{.greek-added} [ανοιξαντες]{.greek-added} [τους]{.greek-added} [θησαυρους]{.greek-added} [αυτων]{.greek-added} [προσηνεγκαν]{.greek-added} [αυτω]{.greek-added} [δωρα]{.greek-added} [χρυσον]{.greek-added} [και]{.greek-added} [λιβανον]{.greek-added} [και]{.greek-added} [σμυρναν]{.greek-added}[2:11]{.aside}

και χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδου αγγελος [κυριου]{.greek-omitted} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

[εγερθεις]{.greek-added} [παραλαβε]{.greek-added} [το]{.greek-added} [παιδιον]{.greek-added} [και]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον υιον μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη λιαν [και]{.greek-omitted} [αποστειλας]{.greek-omitted} [ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} παντας τους παιδας τους εν βηθλεεμ και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις οριοις [αυτης]{.greek-omitted} [αυτου]{.greek-added} απο διετους και κατωτερω κατα τον χρονον ον [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρα των μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν [υπο]{.greek-omitted} [δια]{.greek-added} ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ [κλαιουσα]{.greek-omitted} [κλεουσα]{.greek-added} τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ φαινεται τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} [τεθνηκασιν]{.greek-omitted} [τεθνηκασι]{.greek-added} γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει [επι]{.greek-omitted} της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη [εκει]{.greek-omitted} [εκεισε]{.greek-added} απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν εις πολιν λεγομενην ναζαρετ οπως πληρωθη το ρηθεν δια των προφητων οτι [ναζωραιος]{.greek-omitted} [ναζαρηνος]{.greek-added} κληθησεται[2:23]{.aside}

### Chapter 3

εν [δε]{.greek-omitted} ταις ημεραις εκειναις παραγινεται [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

και λεγων [μετανοειτε]{.greek-omitted} [μετανοητε]{.greek-added} [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

ουτος γαρ εστιν ο ρηθεις υπο [ησαιου]{.greek-omitted} [ισαιου]{.greek-added} του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε ο ιωαννης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} πασα η ιουδαια [και]{.greek-added} [ιεροσολυμα]{.greek-added} και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο [εν]{.greek-omitted} [τω]{.greek-omitted} [ιορδανη]{.greek-omitted} υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και σαδδουκαιων ερχομενους επι το βαπτισμα αυτου ειπεν αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν εαυτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των λιθων τουτων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} τεκνα [τω]{.greek-omitted} [τωι]{.greek-added} αβρααμ[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[3:10]{.aside}

εγω μεν βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος [τα]{.greek-omitted} [τον]{.greek-added} [ιμαντα]{.greek-added} [του]{.greek-added} [υποδηματα]{.greek-omitted} [υποδηματος]{.greek-added} [βαστασαι]{.greek-omitted} [λυσαι]{.greek-added} αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον [αυτου]{.greek-omitted} εις την αποθηκην το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας [επι]{.greek-omitted} [εις]{.greek-added} τον ιορδανην προς τον ιωαννην του βαπτισθηναι υπ αυτου[3:13]{.aside}

[και]{.greek-added} ο [δε]{.greek-omitted} ιωαννης [διεκωλυεν]{.greek-omitted} [διακωλυει]{.greek-added} αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

[αποκριθεις]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [αφες]{.greek-omitted} [αρτι]{.greek-omitted} ουτως [[ουτω]{.corr}]{.greek-added} γαρ [πρεπον]{.greek-omitted} [πρεπων]{.greek-added} [εστιν]{.greek-omitted} ημιν [εστι]{.greek-added} πληρωσαι πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και βαπτισθεις ο [ιησους]{.greek-abbr} ανεβη [ευθυς]{.greek-omitted} απο του υδατος και ιδου ανεωχθησαν αυτω οι [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} καταβαινον ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[3:17]{.aside}

### Chapter 4

τοτε [ανηχθη]{.greek-added} ο [ιησους]{.greek-abbr} [ανηχθη]{.greek-omitted} εις την ερημον υπο του [πνευματος]{.greek-abbr} πειρασθηναι υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} και νυκτας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} υστερον επεινασεν[4:2]{.aside}

[και]{.greek-omitted} [επειδη]{.greek-added} [γαρ]{.greek-added} [επεινασε]{.greek-added} προσελθων [αυτω]{.greek-omitted} ο πειραζων ειπεν [αυτω]{.greek-added} ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} ειπε ινα οι [λιθοι]{.greek-omitted} [λοιθοι]{.greek-added} ουτοι αρτοι γενωνται[4:3]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [γεγραπται]{.greek-omitted} [ουκ]{.greek-added} [επ]{.greek-added} [αρτω]{.greek-added} [μονω]{.greek-added} [ζησεται]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} ουκ επ αρτω μονω ζησεται [ανθρωπος]{.greek-abbr} αλλ επι παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει υιος ει του [θεου]{.greek-abbr} βαλε σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

[εφη]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [παλιν]{.greek-omitted} γεγραπται ουκ εκπειρασεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

[παλιν]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [και]{.greek-added} [αναγαγων]{.greek-added} αυτον [ο]{.greek-omitted} [διαβολος]{.greek-omitted} εις ορος υψηλον λιαν [και]{.greek-omitted} δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν [αυτων]{.greek-omitted} [αυτον]{.greek-added}[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω μονω λατρευσεις[4:10]{.aside}

τοτε αφιησιν αυτον ο [διαβολος]{.greek-omitted} [σατα[νας]{.unclear}]{.greek-added} και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} οτι ιωαννης παρεδοθη ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την ναζαρετ ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και νεφθαλειμ[4:13]{.aside}

ινα πληρωθη το ρηθεν δια [ησαιου]{.greek-omitted} του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη νεφθαλειμ οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} φως [ειδε]{.greek-added} μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

[και]{.greek-added} περιπατων [δε]{.greek-omitted} παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} δυο αδελφους σιμωνα τον [λεγομενον]{.greek-omitted} [επικαλουμενον]{.greek-added} πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω υμας αλιεις [ανθρωπων]{.greek-abbr}[4:19]{.aside}

οι δε [ευθεως]{.greek-omitted} αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν ειδεν αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου εν [τω]{.greek-omitted} [τωι]{.greek-added} [πλοιω]{.greek-omitted} [πλοιωι]{.greek-added} μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας τα δικτυα αυτων και εκαλεσεν αυτους[4:21]{.aside}

οι δε [ευθεως]{.greek-omitted} αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν ολην την γαλιλαιαν ο [ιησους]{.greek-abbr} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και απηλθεν η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και βασανοις συνεχομενους και δαιμονιζομενους και σεληνιαζομενους και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον [αυτω]{.greek-omitted} οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους λεγων[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθησονται[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομησουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι πεινωντες και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

μακαριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι εστε οταν ονειδισωσιν υμας και [διωξωσιν]{.greek-omitted} [διωξωσι]{.greek-added} και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις [ουρανοις]{.greek-abbr} [ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το αλας της γης [εαν]{.greek-omitted} [αν]{.greek-added} δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι [ει]{.greek-omitted} [μη]{.greek-omitted} βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου [ο]{.greek-supplied}υ δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και τιθεασιν αυτον υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων εμπροσθεν των [ανθρωπων]{.greek-abbr} οπως [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} [υμων]{.greek-omitted} τα καλα εργα [υμων]{.greek-added} και [δοξασωσιν]{.greek-omitted} [δοξασωσι]{.greek-added} τον [πατερα]{.greek-abbr} υμων τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η μια κεραια ου μη παρελθη απο του νομου εως αν παντα γενηται[5:18]{.aside}

ος εαν ουν λυση μιαν των εντολων τουτων των ελαχιστων και διδαξη ουτως τους [ανθρωπους]{.greek-abbr} [ουτος]{.greek-added} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν ποιηση και διδαξη ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση [υμων]{.greek-added} η δικαιοσυνη [υμων]{.greek-omitted} [πλειον]{.greek-omitted} [πλεον]{.greek-added} των γραμματεων και [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} ου μη εισελθητε εις την βασιλειαν των ουρανων[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [φονευση]{.greek-omitted} [ενοχος]{.greek-omitted} [εσται]{.greek-omitted} [τη]{.greek-omitted} [κρισει]{.greek-omitted}[5:21]{.aside}

εγω δε λεγω υμιν οτι [πας]{.greek-omitted} ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν ειπη [τω]{.greek-omitted} [τωι]{.greek-added} αδελφω αυτου ρακα ενοχος εσται τω συνεδριω [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [ειπη]{.greek-omitted} [μωρε]{.greek-omitted} [ενοχος]{.greek-omitted} [εσται]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γεενναν]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted}[5:22]{.aside}

εαν ουν προσφερης το δωρον σου επι το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

[ισθι]{.greek-omitted} [ισθη]{.greek-added} ευνοων τω αντιδικω σου [ταχυ]{.greek-omitted} εως οτου ει [μετ]{.greek-added} [αυτου]{.greek-added} εν τη οδω [μετ]{.greek-omitted} [αυτου]{.greek-omitted} μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και [ι]{.greek-added} [εις]{.corr} φυλακην βληθηση[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως αν αποδως [και]{.greek-added} τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη [τοις]{.greek-added} [αρχαιοις]{.greek-added} ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο [βλεπων]{.greek-omitted} [εμβλεψας]{.greek-added} [γυναικα]{.greek-omitted} [γυναικι]{.greek-added} προς το επιθυμησαι αυτην ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιος σκανδαλιζει σε εξελε αυτον και βαλε απο σου συμφερει γαρ [σι]{.greek-added} [σοι]{.corr} ινα αποληται εν των [μελλ]{.greek-added} [μελων]{.corr} σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

και [η]{.greek-added} [ει]{.corr} η δεξια σου χειρ σκανδαλιζει σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη [δε]{.greek-omitted} οτι ος αν απολυση την γυναικα αυτου δοτω αυτη [βιβλιον]{.greek-added} [αποστασιον]{.greek-omitted} [αποστασιου]{.greek-added}[5:31]{.aside}

εγω δε λεγω υμιν οτι ος αν απολυση την γυναικα αυτου παρεκτος λογου πορνειας [ποιει]{.greek-omitted} [ποιη]{.greek-added} αυτην μοιχασθαι και ος [εαν]{.greek-omitted} [αν]{.greek-added} απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε [τω]{.greek-omitted} [τωι]{.greek-added} [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη ομοσαι ολως μητε εν [τω]{.corr} [ουρανω]{.greek-abbr} οτι θρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον [εστιν]{.greek-omitted} [εστι]{.greek-added} των ποδων αυτου μητε εις ιεροσολυμα οτι πολις [εστιν]{.greek-omitted} [εστι]{.greek-added} [του]{.greek-added} [βασιλεως]{.greek-added} του μεγαλου [βασιλεως]{.greek-omitted}[5:35]{.aside}

μητε εν τη κεφαλη σου ομοσης οτι ου δυνασαι [ποιησαι]{.greek-added} μιαν τριχα λευκην η [μελαιναν]{.greek-omitted} [μελεναν]{.greek-added} [ποιησαι]{.greek-omitted}[5:36]{.aside}

ηκουσατε οτι ερρεθη [τοις]{.greek-added} [αρχαιοις]{.greek-added} οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω αλλ οστις σε ραπισει [επι]{.greek-omitted} [εις]{.greek-added} την δεξιαν σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} θελοντι σοι κριθηναι και [τον]{.greek-omitted} [το]{.greek-added} [χιτωνα]{.greek-omitted} [ιματιον]{.greek-added} σου λαβειν αφες αυτω και [το]{.greek-omitted} [τον]{.greek-added} [ιματιον]{.greek-omitted} [χιτονα]{.greek-added}[5:40]{.aside}

και [εαν]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} σε [αγγαρευσει]{.greek-omitted} [αγγαρευση]{.greek-added} μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω αιτουντι σε διδου και τον θελοντα απο σου δανεισασθαι μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και μισησεις τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων ευλογειτε τους καταρωμενους υμας καλως ποιειτε τοις μισουσιν υμας και προσευχεσθε υπερ των επηρεαζοντων υμας και διωκοντων υμας[5:44]{.aside}

οπως [γενησθε]{.greek-omitted} [γενοισθε]{.greek-added} [υιοι]{.greek-omitted} [ομοιοι]{.greek-added} του [πατρος]{.greek-abbr} υμων του εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} οτι [ανατελλει]{.greek-added} τον ηλιον αυτου [ανατελλει]{.greek-omitted} επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν [γαρ]{.greek-omitted} [αγαπησητε]{.greek-omitted} [αγαπατε]{.greek-added} τους αγαπωντας υμας τινα μισθον εχετε ουχι και οι τελωναι το αυτο ποιουσιν[5:46]{.aside}

και εαν ασπασησθε τους φιλους υμων μονον τι περισσον ποιειτε ουχι και οι τελωναι [ουτως]{.greek-omitted} [το]{.greek-added} [αυτο]{.greek-added} ποιουσιν[5:47]{.aside}

εσεσθε ουν υμεις τελειοι ωσπερ ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} τελειος [εστιν]{.greek-omitted} [εστι]{.greek-added}[5:48]{.aside}

### Chapter 6

προσεχετε [δε]{.greek-added} την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν ποιης ελεημοσυνην μη σαλπισης [εμπροσθεν]{.greek-omitted} [σου]{.greek-omitted} ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν [οτι]{.greek-added} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη [γνωτω]{.greek-omitted} [γνωτο]{.greek-added} η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αυτος αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται οτι φιλουσιν εν ταις συναγωγαις και εν ταις γωνιαις των πλατειων εστωτες προσευχεσθαι οπως αν [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις ανθρωποις αμην [αμην]{.greek-added} λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το ταμιειον σου και κλεισας την θυραν σου προσευξαι [τω]{.greek-omitted} [τωι]{.greek-added} [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν [τω]{.greek-omitted} [τωι]{.greek-added} φανερω[6:6]{.aside}

προσευχομενοι δε μη [βαττολογησητε]{.greek-omitted} [βατολογησητε]{.greek-added} ωσπερ οι εθνικοι [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν ομοιωθητε αυτοις [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} υμων ων [χρειαν]{.greek-omitted} [χρειαναν]{.greek-added} εχετε προ του υμας αιτησαι αυτον[6:8]{.aside}

[ουτως]{.greek-omitted} [ουν]{.greek-omitted} [προσευχεσθε]{.greek-omitted} [υμεις]{.greek-omitted} [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το ονομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων ως και ημεις [αφιημεν]{.greek-added} [αφιεμεν]{.corr} τοις οφειλεταις ημων[6:12]{.aside}

και μη εισενεγκης ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [και]{.greek-added} [του]{.greek-added} [υιου]{.greek-added} [και]{.greek-added} [του]{.greek-added} [αγιου]{.greek-added} [[πνευματος]{.greek-abbr}]{.greek-added} εις τους αιωνας αμην[6:13]{.aside}

εαν γαρ αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων αφησει τα παραπτωματα υμων[6:15]{.aside}

οταν δε νηστευητε μη γινεσθε ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων αλειψαι σου την κεφαλην και το προσωπον [σου]{.greek-omitted} νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι[6:18]{.aside}

μη θησαυριζετε [υμιν]{.greek-omitted} θησαυρους επι της γης οπου σης και βρωσις αφανιζει και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορυττουσι]{.greek-added} και [κλεπτουσιν]{.greek-omitted} [κλεπτουσι]{.greek-added}[6:19]{.aside}

θησαυριζετε [δε]{.greek-omitted} υμιν θησαυρους εν [ουρανω]{.greek-abbr} οπου ουτε σης ουτε βρωσις αφανιζει και οπου κλεπται ου διορυσσουσιν ουδε κλεπτουσιν[6:20]{.aside}

οπου γαρ εστιν ο θησαυρος υμων εκει εσται και η καρδια υμων[6:21]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους η ολον το σωμα σου φωτεινον εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει [ουν]{.greek-omitted} το φως το εν σοι σκοτος [εστιν]{.greek-omitted} το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον [αγαπηση]{.greek-added} [αγαπησει]{.corr} η [του]{.greek-added} ενος ανθεξεται και του ετερου καταφρονησει [ου]{.greek-omitted} [δυνασθε]{.greek-omitted} [θεω]{.greek-omitted} [δουλευειν]{.greek-omitted} [και]{.greek-omitted} [μαμωνα]{.greek-omitted}[6:24]{.aside}

δια τουτο λεγω υμιν μη [μεριμνατε]{.greek-omitted} [μεριμνησητε]{.greek-added} τη ψυχη υμων τι φαγητε και τι πιητε μηδε τω σωματι υμων τι [ενδυσησθε]{.greek-omitted} [ενδυσεσθε]{.greek-added} [ουχι]{.greek-omitted} [η]{.greek-omitted} [ψυχη]{.greek-omitted} [πλειον]{.greek-omitted} [εστιν]{.greek-omitted} [της]{.greek-omitted} [τροφης]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ενδυματος]{.greek-omitted}[6:25]{.aside}

τις δε εξ υμων μεριμνων δυναται [προσθειναι]{.greek-omitted} [προσθηναι]{.greek-added} επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε νηθει[6:28]{.aside}

λεγω δε υμιν οτι ουδε σολομων εν παση [τη]{.greek-omitted} [τηι]{.greek-added} δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλομενον ο [θεος]{.greek-abbr} ουτως αμφιεννυσιν ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

ζητειτε δε πρωτον την βασιλειαν του [θεου]{.greek-abbr} και την δικαιοσυνην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν μεριμνησητε εις την αυριον η γαρ αυριον [μεριμνησι]{.greek-added} [μεριμνησει]{.corr} τα εαυτης αρκετον [γαρ]{.greek-added} τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

μη κρινετε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε κριθησεσθε και εν ω μετρω [μετρειτε]{.greek-omitted} [μετρητε]{.greek-added} [μετρηθησεται]{.greek-omitted} [αντιμετριθησεται]{.greek-added} υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος [το]{.greek-omitted} [τωι]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} οφθαλμω του αδελφου σου την δε εν τω σω οφθαλμω δοκον ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος απο του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

η τις εστιν εξ υμων [ανθρωπος]{.greek-abbr} [ον]{.greek-omitted} [ος]{.greek-added} εαν αιτηση ο υιος αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

και εαν ιχθυν αιτηση μη οφιν επιδωσει αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

παντα ουν οσα [αν]{.greek-omitted} [εαν]{.greek-added} θελητε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} [ουτως]{.greek-omitted} και υμεις ποιειτε αυτοις [ουτος]{.greek-omitted} [ουτως]{.greek-added} γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

εισελθετε δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

[τι]{.greek-omitted} [και]{.greek-added} στενη η πυλη και [τεθλιμενη]{.greek-added} [τεθλιμμενη]{.corr} η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

προσεχετε δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυματι]{.greek-added} προβατων εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

ουτως παν [δενδρον]{.greek-omitted} [δενδρων]{.greek-added} αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον σαπρον καρπους καλους ποιειν[7:18]{.aside}

αρα [γε]{.greek-omitted} [ουν]{.greek-added} απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου τω σω ονοματι προεφητευσαμεν και [τω]{.greek-omitted} [τωι]{.greek-added} σω ονοματι δαιμονια εξεβαλομεν και [τω]{.greek-omitted} [τωι]{.greek-added} σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε ομολογησω αυτοις οτι ουδεποτε εγνων υμας αποχωρειτε απ εμου [παντες]{.greek-added} οι εργαζομενοι την ανομιαν[7:23]{.aside}

πας [ουν]{.greek-omitted} οστις ακουει μου τους λογους τουτους [και]{.greek-omitted} [ποιει]{.greek-omitted} [αυτους]{.greek-omitted} ομοιωσω αυτον ανδρι φρονιμω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεπεσον τη οικια εκεινη και ουκ [επεσεν]{.greek-omitted} [επεσε]{.greek-added} τεθεμελιωτο γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη [π[ο]{.unclear}ων]{.greek-added} [π[ο]{.unclear}ιων]{.corr} αυτους ομοιωθησεται ανδρι μωρω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και [προσεκοψαν]{.greek-omitted} [προσερρηξαν]{.greek-added} τη οικια εκεινη και [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και ην η πτωσις [αυτης]{.greek-omitted} [αυτου]{.greek-added} μεγαλη[7:27]{.aside}

και εγενετο οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο [παντες]{.greek-added} οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ [αυτους]{.greek-added} διδασκων [αυτους]{.greek-omitted} ως εξουσιαν εχων και ουχ ως οι γραμματεις[7:29]{.aside}

### Chapter 8

λεγω δε [ημιν]{.greek-added} [υμιν]{.corr} [οτι]{.greek-omitted} πολλοι απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και ανακλιθησονται μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

[και]{.greek-omitted} ειπεν ο [ιησους]{.greek-abbr} [αυτωι]{.greek-added} [τω]{.greek-omitted} [εκατονταρχη]{.greek-omitted} υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου [εν]{.greek-omitted} [απο]{.greek-added} [τη]{.greek-omitted} [της]{.greek-added} [ωρα]{.greek-omitted} [ωρας]{.greek-added} [εκεινη]{.greek-omitted} [εκεινης]{.greek-added}[8:13]{.aside}

και [ελθων]{.greek-omitted} [εισελθων]{.greek-added} ο [ιησους]{.greek-abbr} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} την πενθεραν αυτου βεβλημενην και [πυρεσσουσαν]{.greek-omitted} [πυρεσουσαν]{.greek-added}[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα πνευματα [απ]{.greek-added} [αυτων]{.greek-added} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου [οτι]{.greek-added} [λεγοντος]{.greek-omitted} [αυτος]{.greek-omitted} τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} διδασκαλε ακολουθησω σοι οπου [εαν]{.greek-omitted} [αν]{.greek-added} απερχη[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην κλινη[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις το πλοιον ηκολουθησαν [αυτω]{.greek-omitted} οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων αυτος δε [εκαθευδεν]{.greek-omitted} [εκαθευδε]{.greek-added}[8:24]{.aside}

και προσελθοντες οι μαθηται [αυτου]{.greek-added} ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι τοτε εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-omitted} [οχλοι]{.greek-added} [εθαυμασαν]{.greek-omitted} [εθαυμαζον]{.greek-added} λεγοντες ποταπος εστιν ουτος [ο]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} οτι [και]{.greek-added} [η]{.greek-added} [θαλασσα]{.greek-added} και οι ανεμοι [και]{.greek-omitted} [η]{.greek-omitted} [θαλασσα]{.greek-omitted} υπακουουσιν αυτω[8:27]{.aside}

και ελθοντι αυτω εις το περαν εις την χωραν των γεργεσηνων υπηντησαν αυτω δυο δαιμονιζομενοι εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων [πολλων]{.greek-omitted} [βοσκομενη]{.greek-omitted} [βοσκομενων]{.greek-added}[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει [εκβαλλεις]{.greek-omitted} [εκβαλης]{.greek-added} ημας επιτρεψον [ημιν]{.greek-omitted} [ημας]{.greek-added} απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου [ωρμησεν]{.greek-omitted} [ωρμησε]{.greek-added} πασα η αγελη των χοιρων κατα του κρημνου εις την θαλασσαν και [απεθανον]{.greek-omitted} [απεπνιγη]{.greek-added} εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως [μεταβη]{.greek-omitted} [μετα]{.greek-added} [βη]{.greek-added} απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις το πλοιον [διεπερασεν]{.greek-omitted} [διεπερασε]{.greek-added} και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου [προσεφερον]{.greek-omitted} [προσηνεγκαν]{.greek-added} αυτω παραλυτικον επι κλινης [βεβλημενον]{.greek-omitted} [βεβλημμενον]{.greek-added} και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω παραλυτικω θαρσει τεκνον αφεωνται σοι αι αμαρτιαι σου[9:2]{.aside}

και ιδου τινες των γραμματεων ειπον εν [εαυτοις]{.greek-omitted} [[σ]{.unclear}εαυτοις]{.greek-added} ουτος βλασφημει[9:3]{.aside}

και ιδων ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} [υμεις]{.greek-omitted} [ενθυμεισθε]{.greek-omitted} [ενθυμεισθαι]{.greek-added} πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν ευκοπωτερον ειπειν αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[9:5]{.aside}

ινα δε ειδητε οτι [επι]{.greek-added} [της]{.greek-added} [γης]{.greek-added} εξουσιαν εχει [αφιεναι]{.greek-added} [αμαρτιας]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [αφιεναι]{.greek-omitted} [αμαρτιας]{.greek-omitted} τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο [τω]{.greek-omitted} [τωι]{.greek-added} [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα [των]{.greek-omitted} τελωνων και αμαρτωλων εσθιει ο διδασκαλος υμων[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν ελεον θελω και ου θυσιαν [ου]{.greek-omitted} [ουκ]{.greek-added} [γαρ]{.greek-omitted} ηλθον καλεσαι δικαιους [αλλα]{.greek-omitted} [αλλ]{.greek-added} αμαρτωλους εις μετανοιαν[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε μαθηται σου ου νηστευουσιν[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος [πενθειν]{.greek-omitted} [νηστευειν]{.greek-added} εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

ουδεις δε [επιβαλλει]{.greek-omitted} [βαλλει]{.greek-added} επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα [αυτου]{.greek-omitted} απο [τουτου]{.greek-added} [του]{.greek-omitted} [ιματιου]{.greek-omitted} και [χειρον]{.greek-omitted} [χειρονα]{.greek-added} σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους [ει]{.greek-omitted} [δε]{.greek-omitted} [μηγε]{.greek-omitted} [ρηγνυνται]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [εκχειται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [απολουνται]{.greek-omitted} [αλλα]{.greek-omitted} [βαλλουσιν]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [καινους]{.greek-omitted} [και]{.greek-omitted} [αμφοτεροι]{.greek-omitted} [συντηρουνται]{.greek-omitted}[9:17]{.aside}

ταυτα αυτου λαλουντος [αυτοις]{.greek-omitted} ιδου αρχων [εις]{.greek-omitted} [ελθων]{.greek-omitted} [εἳς]{.greek-added} [ἐλθὼν]{.greek-added} προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν [αλλα]{.greek-omitted} ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον αψωμαι του [κρασπεδου]{.greek-added} [του]{.greek-added} ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} θαρσει θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ απεθανεν [αλλα]{.greek-added} [καθευδη]{.greek-added} το κορασιον [αλλα]{.greek-omitted} [καθευδει]{.greek-omitted} και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισελθων [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} της χειρος [αυτης]{.greek-omitted} και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

και παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

[ελθοντι]{.greek-omitted} [ελθοντες]{.greek-added} δε εις την οικιαν προσηλθον αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} πιστευετε οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων αυτων [λεγων]{.greek-omitted} [και]{.greek-added} [ειπε]{.greek-added} κατα την πιστιν [υμων]{.greek-omitted} [ημων]{.greek-added} γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες [διεφημισαν]{.greek-omitted} [διεφημησαν]{.greek-added} αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγκαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος [και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} [οχλοι]{.greek-added} εθαυμασαν [οι]{.greek-omitted} [οχλοι]{.greek-omitted} λεγοντες ουδεποτε [εφανη]{.greek-omitted} [εφανει]{.greek-added} ουτως εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε φαρισαιοι ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολεις πασας και τας κωμας διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν [εν]{.greek-omitted} [τω]{.greek-omitted} [λαω]{.greek-omitted}[9:35]{.aside}

ιδων δε τους οχλους [εσπλαγχνισθη]{.greek-omitted} [ευσπλαγχνισθη]{.greek-added} περι αυτων οτι ησαν εσκυλμενοι και ερριμμενοι [ωσει]{.greek-omitted} [ως]{.greek-added} προβατα μη εχοντα ποιμενα[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

και προσκαλεσαμενος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους δωδεκα μαθητας αυτου εδωκεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} εξουσιαν [κατα]{.greek-added} [πνευματων]{.greek-abbr} ακαθαρτων ωστε εκβαλλειν αυτα και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

των δε δωδεκα αποστολων τα ονοματα [εστιν]{.greek-omitted} [εισι]{.greek-added} ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου ιακωβος ο του ζεβεδαιου και ιωαννης ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και [λεββαιος]{.greek-omitted} [λεβαιος]{.greek-added} ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο κανανιτης και ιουδας [ο]{.greek-added} ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους δωδεκα απεστειλεν ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν σαμαρειτων μη εισελθητε[10:5]{.aside}

πορευεσθε δε μαλλον προς τα προβατα τα [απολωλοτα]{.greek-omitted} [απολωτα]{.greek-added} οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρυσσετε λεγοντες οτι ηγγικεν η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας [θεραπευετη]{.greek-added} [θεραπευετε]{.corr} λεπρους καθαριζετε δαιμονια εκβαλλετε δωρεαν ελαβετε δωρεαν δοτε[10:8]{.aside}

μη κτησησθε χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε ραβδους αξιος γαρ ο εργατης της τροφης αυτου εστιν[10:10]{.aside}

εις ην δ αν πολιν η [κωμην]{.greek-omitted} [κομην]{.greek-added} εισελθητε εξετασατε τις εν αυτη αξιος [εστιν]{.greek-omitted} [εστι]{.greek-added} κακει μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν ασπασασθε αυτην[10:12]{.aside}

[και]{.greek-omitted} εαν μεν η η οικια αξια ελθετω η ειρηνη [υμων]{.greek-omitted} επ αυτην [εαν]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [η]{.greek-omitted} [αξια]{.greek-omitted} [η]{.greek-omitted} [ειρηνη]{.greek-omitted} [υμων]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [επιστραφητω]{.greek-omitted}[10:13]{.aside}

και ος [αν]{.greek-added} [εαν]{.corr} [μη]{.corr} δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της [οικιας]{.greek-omitted} [πολεως]{.greek-added} η της [πολεως]{.greek-omitted} [οικιας]{.greek-added} εκεινης [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον κονιορτον των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν ανεκτοτερον εσται γη σοδομων και γομορρων εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων γινεσθε [ουν]{.corr} φρονιμοι [ωσει]{.greek-added} [ως]{.greek-omitted} [οι]{.greek-omitted} οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συναγωγαις [αυτων]{.greek-omitted} [υμων]{.greek-added} [μαστιγωσουσιν]{.greek-omitted} [μαστηγωσουσιν]{.greek-added} υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε [παραδιδωσιν]{.greek-omitted} [παραδιδωασιν]{.greek-added} υμας μη μεριμνησητε πως η τι [λαλησητε]{.greek-omitted} [δοθησεται]{.greek-omitted} [γαρ]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [τι]{.greek-omitted} λαλησετε[10:19]{.aside}

ου γαρ υμεις εστε οι [λα]{.greek-added} [λαλουντες]{.greek-omitted} [λουντες]{.greek-added} αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος [σωθησεται]{.greek-omitted} [ωθησεται]{.greek-added}[10:22]{.aside}

οταν δε διωκωσιν υμας εν [τηδε]{.greek-added} τη πολει [ταυτη]{.greek-omitted} φευγετε εις την αλλην αμην γαρ λεγω υμιν ου μη τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added}[10:23]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης υπερ τον διδασκαλον [αυτου]{.greek-added} ουδε δουλος υπερ τον κυριον αυτου[10:24]{.aside}

αρκετον [τω]{.greek-omitted} [τωι]{.greek-added} μαθητη ινα γενηται ως ο διδασκαλος αυτου [και]{.greek-omitted} [ο]{.greek-omitted} [δουλος]{.greek-omitted} [ως]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [αυτου]{.greek-omitted} ει τον οικοδεσποτην βεελζεβουλ [εκαλεσαν]{.greek-omitted} [απεκαλεσαν]{.greek-added} ποσω μαλλον τους [οικειακους]{.greek-omitted} [οικιακους]{.greek-added} αυτου[10:25]{.aside}

μη ουν [φοβεισθε]{.greek-added} [φοβηθητε]{.greek-omitted} [αυτους]{.greek-omitted} ουδεν γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [κεκαλυμμενον]{.greek-omitted} [κεκαλυμενον]{.greek-added} ο ουκ αποκαλυφθησεται και κρυπτον ο ου γνωσθησεται[10:26]{.aside}

[ο]{.greek-omitted} [α]{.greek-added} λεγω υμιν εν τη σκοτια ειπατε εν τω φωτι και ο εις το ους ακουετε κηρυξατε επι των [δωματων]{.greek-omitted} [δοματων]{.greek-added}[10:27]{.aside}

και μη φοβεισθε απο των αποκτενοντων το σωμα την δε ψυχην μη δυναμενων αποκτειναι φοβηθητε δε μαλλον τον δυναμενον και [την]{.greek-omitted} ψυχην και [το]{.greek-omitted} σωμα απολεσαι εν γεεννη[10:28]{.aside}

ουχι δυο στρουθια ασσαριου πωλειται και εν εξ αυτων ου πεσειται επι την γην ανευ του [πατρος]{.greek-abbr} υμων[10:29]{.aside}

υμων δε και αι τριχες της κεφαλης πασαι ηριθμημεναι εισιν[10:30]{.aside}

μη ουν [φοβ[ι]{.unclear}θητε]{.greek-added} [φοβηθητε]{.corr} πολλων στρουθιων [διαφερετε]{.greek-omitted} [διαφε]{.greek-added} [ρετε]{.greek-added} υμεις[10:31]{.aside}

πας ουν οστις ομολογησει εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:32]{.aside}

οστις δ αν αρνησηται με εμπροσθεν των [ανθρωπων]{.greek-abbr} αρνησομαι [καγω]{.greek-added} αυτον [καγω]{.greek-omitted} εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:33]{.aside}

μη νομισητε οτι ηλθον βαλειν ειρηνην επι την γην ουκ ηλθον βαλειν ειρηνην αλλα μαχαιραν[10:34]{.aside}

ηλθον [γαρ]{.greek-omitted} διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και θυγατερα κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και εχθροι του [ανθρωπου]{.greek-abbr} οι [οικειακοι]{.greek-omitted} [οικιακοι]{.greek-added} αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος και ο φιλων [υιον]{.greek-abbr} η θυγατερα υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψεται[10:41]{.aside}

και ος εαν ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε ιωαννης ακουσας εν [τω]{.greek-omitted} [τωι]{.greek-added} δεσμωτηριω τα εργα του [χριστου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε [ιωαννη]{.greek-omitted} [τω]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται και κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος [εστιν]{.greek-omitted} ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωαννου τι εξηλθετε εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι εξηλθετε ιδειν [ανθρωπον]{.greek-abbr} εν [μαλακοις]{.greek-omitted} [μαλακιοις]{.greek-added} ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι εξηλθετε ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου [αλλα]{.greek-added} [τι]{.greek-added} [εξηλθετε]{.greek-added} [ιδειν]{.greek-added} [προφητην]{.greek-added} [ναι]{.greek-added} [λεγω]{.greek-added} [υμιν]{.greek-added} [και]{.greek-added} [περισσοτερον]{.greek-added} [προφητου]{.greek-added}[11:9]{.aside}

ουτος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ [εγηγερται]{.greek-omitted} [εγειγερται]{.greek-added} εν γεννητοις γυναικων μειζων ιωαννου του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων ιωαννου του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως ιωαννου προεφητευσαν[11:13]{.aside}

και ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις [εν]{.greek-omitted} [αγοραις]{.greek-omitted} καθημενοις [επι]{.greek-added} [της]{.greek-added} [αγορας]{.greek-added} [και]{.greek-omitted} [προσφωνουσιν]{.greek-omitted} [τοις]{.greek-omitted} [εταιροις]{.greek-omitted} [αυτων]{.greek-omitted}[11:16]{.aside}

και λεγουσιν ηυλησαμεν υμιν και ουκ ωρχησασθε [εθρηνησαμεν]{.greek-omitted} [εθρινησαμεν]{.greek-added} υμιν και ουκ [εκο]{.greek-added} [εκοψασθε]{.greek-omitted} [ψασθε]{.greek-added}[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ [ο]{.greek-added} ιωαννης μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο [υιος]{.greek-omitted} [[ιησους]{.greek-abbr}]{.greek-added} του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης τελωνων φιλος και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} ονειδιζειν τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι χοραζιν ουαι σοι [βηθσαιδα]{.greek-omitted} [βιθσαιδα]{.greek-added} οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι [γενομεναι]{.greek-omitted} [γινομεναι]{.greek-added} εν υμιν παλαι αν εν σακκω και σποδω μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι ανεκτοτερον εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ η εως του [ουρανου]{.greek-abbr} υψωθεισα εως αδου καταβιβασθηση οτι ει εν σοδομοις εγενοντο αι δυναμεις αι γενομεναι εν σοι εμειναν αν μεχρι της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι γη σοδομων ανεκτοτερον εσται εν ημερα κρισεως η σοι[11:24]{.aside}

εν εκεινω [τω]{.greek-omitted} [τωι]{.greek-added} καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι παρεδοθη υπο του [πατρος]{.greek-abbr} μου και ουδεις [επιγινωσκει]{.greek-omitted} [γινωσκει]{.greek-added} τον [υιον]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο [υιος]{.greek-abbr} και ω εαν [βουλεται]{.greek-added} [βουληται]{.corr} ο [υιος]{.greek-abbr} αποκαλυψαι[11:27]{.aside}

δευτε [προς]{.corr} [με]{.corr} παντες οι κοπιωντες και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και ευρησετε αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου χρηστος και το φορτιον μου ελαφρον εστιν[11:30]{.aside}

### Chapter 12

εν εκεινω [τω]{.greek-omitted} [τωι]{.greek-added} καιρω επορευθη ο [ιησους]{.greek-abbr} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων οι δε μαθηται αυτου επεινασαν και ηρξαντο τιλλειν σταχυας και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντες ειπον αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ποιειν εν σαββατω[12:2]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} ουκ ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε επεινασεν αυτος και οι μετ αυτου[12:3]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως εφαγεν ους ουκ εξον [ην]{.greek-omitted} αυτω φαγειν ουδε τοις μετ αυτου ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} [μονοις]{.greek-omitted} [μονης]{.greek-added}[12:4]{.aside}

η ουκ ανεγνωτε εν [τω]{.greek-omitted} [τωι]{.greek-added} νομω οτι τοις σαββασιν οι ιερεις εν [τω]{.greek-omitted} [τωι]{.greek-added} ιερω το σαββατον βεβηλουσιν και αναιτιοι εισιν[12:5]{.aside}

λεγω δε υμιν οτι του ιερου μειζον εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε τι εστιν ελεον θελω και ου θυσιαν ουκ αν κατεδικασατε τους αναιτιους[12:7]{.aside}

κυριος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} του σαββατου ο υιος του [ανθρωπου]{.greek-abbr}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} ην την χειρα εχων ξηραν και επηρωτησαν αυτον λεγοντες ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} τις [εσται]{.greek-omitted} [εστιν]{.greek-added} εξ υμων [ανθρωπος]{.greek-abbr} [ος]{.greek-omitted} [ως]{.greek-added} εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει [αυτο]{.greek-omitted} και εγερει [αυτο]{.greek-added}[12:11]{.aside}

ποσω ουν διαφερει [ο]{.greek-added} [ανθρωπος]{.greek-abbr} προβατου ωστε [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} καλως ποιειν[12:12]{.aside}

τοτε λεγει [τω]{.greek-omitted} [τωι]{.greek-added} [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

οι δε φαρισαιοι συμβουλιον ελαβον κατ αυτου εξελθοντες οπως αυτον [απολεσωσιν]{.greek-omitted} [απωλεσωσιν]{.greek-added}[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} [αυτοις]{.greek-omitted} [τοις]{.greek-added} [θεραπευθεισιν]{.greek-added} ινα μη φανερον αυτον ποιησωσιν[12:16]{.aside}

οπως πληρωθη το ρηθεν [δια]{.greek-omitted} [υπο]{.greek-added} ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον [ηρετισα]{.greek-omitted} [ηρετησα]{.greek-added} ο αγαπητος μου εις [ο]{.unclear}ν ευδοκησεν η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν [απαγγελει]{.greek-omitted} [αναγγελει]{.greek-added}[12:18]{.aside}

[και]{.greek-added} ουκ [ερισει]{.greek-omitted} [ερησει]{.greek-added} ουδε κραυγασει ουδε ακουσει τις εν [ταις]{.greek-omitted} πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον τυφομενον ου σβεσει εως αν [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εις νικος την κρισιν[12:20]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} ονοματι αυτου εθνη ελπιουσιν[12:21]{.aside}

[τοτε]{.greek-omitted} [και]{.greek-added} προσηνεχθη αυτω δαιμονιζομενος τυφλος [και]{.greek-omitted} [κωφος]{.greek-omitted} και εθεραπευσεν αυτον ωστε τον τυφλον και [κωφον]{.greek-omitted} [και]{.greek-omitted} λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο [παντες]{.greek-omitted} οι οχλοι και ελεγον μητι ουτος εστιν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες ειπον ουτος ουκ εκβαλλει τα δαιμονια ει [μη]{.greek-omitted} [μι]{.greek-added} εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

ειδως δε ο [ιησους]{.greek-abbr} τ[α]{.unclear}ς ενθυμησεις αυτων ειπεν αυτοις πασα β[α]{.unclear}σιλεια μερισθεισα καθ εαυτης ερημουται και πασα πολις η οικια μερισθεισα καθ εαυτης ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν [ε]{.unclear}κβαλλει εφ εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

και ει εγω εν βεελζεβουλ εκβαλλω τα δαιμονια οι υιοι υμων εν τινι εκβαλλουσιν δια τουτο αυτοι υμων εσονται κριται[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} [εκβαλλω]{.greek-added} εγω [εκβαλλω]{.greek-omitted} τα δαιμονια [αρα]{.greek-omitted} [ορα]{.greek-added} εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

η πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τ[α]{.unclear} σκευη αυτου [διαρπασαι]{.greek-omitted} [αρπασαι]{.greek-added} εαν μη πρωτον δηση τον ισχυρον και τοτε την οικιαν αυτου [διαρπασει]{.greek-omitted} [διαρπαση]{.greek-added}[12:29]{.aside}

ο μη ων μετ εμου κατ εμου εστιν και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

δια τουτο λεγω υμιν [οτι]{.greek-added} πασα αμαρτια και βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} η δε του [πνευματος]{.greek-abbr} βλασφημια ουκ αφεθησεται [τοις]{.greek-omitted} [αυτοις]{.greek-added} [ανθρωποις]{.greek-omitted}[12:31]{.aside}

και ος εαν ειπη λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω ος δ αν [ε]{.unclear}ιπη [λογον]{.greek-added} κατα του [πνευματος]{.greek-abbr} του αγιου ουκ αφεθησεται αυτω ουτε εν τω νυν αιωνι ουτε εν [τω]{.greek-omitted} [τωι]{.greek-added} μελλοντι[12:32]{.aside}

η ποιησατε το δ[ε]{.unclear}νδρον καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον σαπρον και [τον]{.greek-omitted} [το]{.greek-added} καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον [γινωσκεται]{.greek-omitted} [επιγινωσκεται]{.greek-added}[12:33]{.aside}

[γεννηματα]{.greek-omitted} [γεννημα]{.greek-added} εχιδ[ν]{.unclear}ων πως δυνασθε αγαθα λαλειν πονηροι [ο]{.unclear}ντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} [εκ]{.unclear} του αγαθου θησαυρου εκβαλλει αγαθα κ[α]{.unclear}[ι]{.greek-supplied} ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρο[υ]{.unclear} εκβαλλει πονηρα[12:35]{.aside}

λεγω δε υμιν οτι παν ρημα [αργον]{.greek-omitted} [αγιον]{.greek-added} ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσοσι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων σου δικαιω[θ]{.unclear}[η]{.greek-supplied}ση και εκ των λογων σου [καταδικασθηση]{.greek-omitted} [κατακριθηση]{.greek-added}[12:37]{.aside}

### Chapter 16

[γ]{.greek-supplied}ενεα πονηρα και [μοι]{.greek-supplied}χαλις σημειον επιζητει και σημειον ου δοθησεται α[υ]{.greek-supplied}τη ει μ[η]{.unclear} το [σημ]{.unclear}ειον ιωνα του προφητου [και]{.greek-omitted} [καταλιπων]{.greek-omitted} [αυτους]{.greek-omitted} [απηλθεν]{.greek-omitted}[16:4]{.aside}

