---
title: "Collation of Byz^RP^ vs 30326 (326)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 326 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30326).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 326                                   	| λογος                              	|
| 326 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 326 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 326               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 326                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 326 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 326                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

τον μεν πρωτον λογον εποιησαμην περι παντων ω θεοφιλε ων ηρξατο ο [ιησους]{.greek-abbr} ποιειν τε και διδασκειν[1:1]{.aside}

αχρι ης ημερας εντειλαμενος τοις αποστολοις δια [πνευματος]{.greek-abbr} αγιου ους εξελεξατο ανεληφθη[1:2]{.aside}

οις και παρεστησεν [εαυτον]{.greek-omitted} ζωντα μετα το παθειν αυτον εν πολλοις τεκμηριοις δι ημερων τεσσαρακοντα οπτανομενος αυτοις και λεγων τα περι της βασιλειας του [θεου]{.greek-abbr}[1:3]{.aside}

και [συναλιζομενος]{.greek-omitted} [συναυλιζομενος]{.greek-added} παρηγγειλεν αυτοις απο ιεροσολυμων μη χωριζεσθαι αλλα περιμενειν την [επαγγελιαν]{.greek-omitted} [επαγγελειαν]{.greek-added} του [πατρος]{.greek-abbr} ην ηκουσατε μου[1:4]{.aside}

οτι ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω ου μετα πολλας ταυτας ημερας[1:5]{.aside}

οι μεν ουν συνελθοντες επηρωτων αυτον λεγοντες [κυριε]{.greek-abbr} ει εν τω χρονω τουτω αποκαθιστανεις την βασιλειαν [τω]{.greek-omitted} [του]{.greek-added} [ισραηλ]{.greek-abbr}[1:6]{.aside}

ειπεν δε προς αυτους ουχ υμων εστιν γνωναι χρονους η καιρους ους ο [πατηρ]{.greek-abbr} εθετο εν τη ιδια εξουσια[1:7]{.aside}

αλλα ληψεσθε δυναμιν επελθοντος του αγιου [πνευματος]{.greek-abbr} εφ υμας και εσεσθε μοι μαρτυρες εν τε [ιερουσαλημ]{.greek-abbr} και εν παση τη ιουδαια και σαμαρεια και εως εσχατου της γης[1:8]{.aside}

και ταυτα ειπων βλεποντων αυτων επηρθη και νεφελη υπελαβεν αυτον απο των οφθαλμων αυτων[1:9]{.aside}

και ως ατενιζοντες ησαν εις τον [ουρανον]{.greek-abbr} [πορευομενου]{.greek-omitted} [πορευμενου]{.greek-added} αυτου και ιδου ανδρες δυο [παρειστηκεισαν]{.greek-omitted} [παριστηκησαν]{.greek-added} αυτοις εν εσθητι λευκη[1:10]{.aside}

οι και ειπον ανδρες γαλιλαιοι τι εστηκατε εμβλεποντες εις τον [ουρανον]{.greek-abbr} ουτος ο [ιησους]{.greek-abbr} ο αναληφθεις αφ υμων [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} ουτως ελευσεται [παλιν]{.greek-added} ον τροπον εθεασασθε αυτον πορευομενον εις τον ουρανον[1:11]{.aside}

τοτε υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} απο ορους του καλουμενου ελαιωνος ο εστιν εγγυς [ιερουσαλημ]{.greek-abbr} σαββατου εχον οδον[1:12]{.aside}

και οτε εισηλθον ανεβησαν εις το υπερωον ου ησαν καταμενοντες ο τε πετρος και ιακωβος και ιωαννης και ανδρεας [και]{.greek-added} φιλιππος και θωμας [και]{.greek-added} βαρθολομαιος και ματθαιος ιακωβος αλφαιου και σιμων ο ζηλωτης και ιουδας ιακωβου[1:13]{.aside}

ουτοι παντες ησαν προσκαρτερουντες ομοθυμαδον τη προσευχη και τη δεησει συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και μαρια τη [μητρι]{.greek-abbr} του [ιησου]{.greek-abbr} και συν τοις αδελφοις αυτου[1:14]{.aside}

και εν ταις ημεραις ταυταις αναστας πετρος εν μεσω των μαθητων ειπεν ην τε οχλος ονοματων επι το [αυτο]{.greek-omitted} [αυτω]{.greek-added} ως εκατον εικοσι[1:15]{.aside}

ανδρες αδελφοι εδει πληρωθηναι την γραφην ταυτην ην [προειπεν]{.greek-omitted} [προειπε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον δια στοματος [δαυιδ]{.greek-abbr} περι ιουδα του γενομενου οδηγου τοις [συλλαβουσιν]{.greek-omitted} [συλλαβουσι]{.greek-added} τον [ιησουν]{.greek-abbr}[1:16]{.aside}

οτι κατηριθμημενος ην συν ημιν και [ελαχεν]{.greek-omitted} [ελαχε]{.greek-added} τον κληρον της διακονιας ταυτης[1:17]{.aside}

ουτος μεν ουν εκτησατο χωριον εκ [του]{.greek-added} μισθου της αδικιας και [πρηνης]{.greek-omitted} [πρινης]{.greek-added} γενομενος [ελακησεν]{.greek-omitted} [ελακησε]{.greek-added} μεσος και εξεχυθη παντα τα σπλαγχνα αυτου[1:18]{.aside}

και γνωστον εγενετο [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} ωστε κληθηναι το χωριον εκεινο τη ιδια διαλεκτω αυτων ακελδαμα τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} χωριον αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω ψαλμων γενηθητω η επαυλις [αυτου]{.greek-omitted} [αυτων]{.greek-added} ερημος και μη εστω ο κατοικων εν αυτη και την επισκοπην αυτου λαβοι ετερος[1:20]{.aside}

δει ουν των συνελθοντων ημιν ανδρων εν παντι χρονω εν ω εισηλθεν και εξηλθεν εφ ημας ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βαπτισματος ιωαννου εως της ημερας ης ανεληφθη αφ ημων μαρτυρα της αναστασεως αυτου γενεσθαι συν ημιν ενα τουτων[1:22]{.aside}

και εστησαν δυο ιωσηφ τον καλουμενον [βαρσαβαν]{.greek-omitted} [βαρσαββαν]{.greek-added} ος επεκληθη ιουστος και ματθιαν[1:23]{.aside}

και προσευξαμενοι ειπον συ [κυριε]{.greek-abbr} καρδιογνωστα παντων αναδειξον ον εξελεξω εκ τουτων των δυο ενα[1:24]{.aside}

λαβειν τον κληρον της διακονιας ταυτης και αποστολης [εξ]{.greek-omitted} [αφ]{.greek-added} ης παρεβη ιουδας πορευθηναι εις τον τοπον τον ιδιον[1:25]{.aside}

και εδωκαν κληρους αυτων και επεσεν ο κληρος επι ματθιαν και συγκατεψηφισθη μετα των ενδεκα αποστολων[1:26]{.aside}

### Chapter 2

και εν τω συμπληρουσθαι την ημεραν της πεντηκοστης ησαν [απαντες]{.greek-omitted} [παντες]{.greek-added} [οι]{.greek-added} [αποστολοι]{.greek-added} ομοθυμαδον επι το αυτο[2:1]{.aside}

και εγενετο αφνω εκ του ουρανου ηχος ωσπερ φερομενης πνοης βιαιας και επληρωσεν [ολον]{.greek-omitted} τον οικον ου ησαν καθημενοι[2:2]{.aside}

και ωφθησαν αυτοις διαμεριζομεναι γλωσσαι ωσει πυρος εκαθισεν τε εφ ενα εκαστον αυτων[2:3]{.aside}

και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετεραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου αυτοις αποφθεγγεσθαι[2:4]{.aside}

ησαν δε εν [ιερουσαλημ]{.greek-abbr} κατοικουντες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο [τον]{.greek-omitted} [των]{.greek-added} [ουρανον]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added}[2:5]{.aside}

γενομενης δε της φωνης ταυτης [συνηλθεν]{.greek-omitted} [συνεισηλθε]{.greek-added} το πληθος και συνεχυθη οτι ηκουον εις εκαστος τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

εξισταντο δε παντες και εθαυμαζον λεγοντες προς αλληλους ουκ ιδου παντες ουτοι εισιν [γαλιλαιοι]{.greek-added} οι λαλουντες [γαλιλαιοι]{.greek-omitted}[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η [εγενηθημεν]{.greek-added} [εγεννηθημεν]{.corr}[2:8]{.aside}

παρθοι [και]{.greek-omitted} μηδοι και ελαμιται και οι κατοικουντες την μεσοποταμιαν ιουδαιαν τε και καππαδοκιαν ποντον και την ασιαν[2:9]{.aside}

φρυγιαν τε και παμφυλιαν αιγυπτον και τα μερη της λιβυης της κατα κυρηνην και οι επιδημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[ιουδαιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυτοι]{.greek-added} κρητες και αραβες ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα μεγαλεια του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και διηπορουν [αλλος]{.greek-added} αλλος προς αλλον λεγοντες τι αν θελοι τουτο ειναι[2:12]{.aside}

ετεροι δε χλευαζοντες ελεγον οτι γλευκους μεμεστωμενοι εισιν[2:13]{.aside}

σταθεις δε πετρος συν τοις ενδεκα [επηρεν]{.greek-omitted} [επηρε]{.greek-added} την φωνην αυτου και απεφθεγξατο αυτοις ανδρες [ιουδαιοι]{.greek-omitted} [ιουδαιον]{.greek-added} και οι κατοικουντες [ιερουσαλημ]{.greek-abbr} απαντες τουτο υμιν γνωστον εστω και [ενωτισασθε]{.greek-omitted} [ενωτησασθε]{.greek-added} τα ρηματα μου [και]{.greek-added} [ενωτησασθε]{.greek-added} [τα]{.greek-added} [ρηματα]{.greek-added} [μου]{.greek-added}[2:14]{.aside}

ου γαρ ως υμεις υπολαμβανετε ουτοι μεθυουσιν εστιν γαρ ωρα τριτη της ημερας [ου]{.greek-added} [γαρ]{.greek-added} [ως]{.greek-added} [υμεις]{.greek-added} [υπολαμβανετε]{.greek-added} [ουτοι]{.greek-added} [μεθυουσιν]{.greek-added} [εστιν]{.greek-added} [γαρ]{.greek-added} [ωρα]{.greek-added} [τριτη]{.greek-added} [της]{.greek-added} [ημερας]{.greek-added}[2:15]{.aside}

αλλα τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το [ειρημενον]{.greek-omitted} [ηρημενον]{.greek-added} δια του προφητου ιωηλ [αλλα]{.greek-added} [τουτο]{.greek-added} [εστι]{.greek-added} [το]{.greek-added} [ηρημενον]{.greek-added} [δια]{.greek-added} [του]{.greek-added} [προφητου]{.greek-added} [ιωηλ]{.greek-added}[2:16]{.aside}

και εσται εν [ται]{.greek-added} [ταις]{.corr} εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υιοι υμων και αι [θυγατεραις]{.greek-added} [θυγατερες]{.corr} υμων και οι νεανισκοι υμων ορασεις οψονται και οι πρεσβυτεροι υμων ενυπνια ενυπνιασθησονται [και]{.greek-added} [εσται]{.greek-added} [εν]{.greek-added} [ται]{.greek-added} [[ταις]{.corr}]{.greek-added} [εσχαταις]{.greek-added} [ημεραις]{.greek-added} [λεγει]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκχεω]{.greek-added} [απο]{.greek-added} [του]{.greek-added} [[πνευματος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} [επι]{.greek-added} [πασαν]{.greek-added} [σαρκα]{.greek-added} [και]{.greek-added} [προφητευσουσιν]{.greek-added} [οι]{.greek-added} [υιοι]{.greek-added} [υμων]{.greek-added} [και]{.greek-added} [αι]{.greek-added} [θυγατεραις]{.greek-added} [[θυγατερες]{.corr}]{.greek-added} [υμων]{.greek-added} [και]{.greek-added} [οι]{.greek-added} [νεανισκοι]{.greek-added} [υμων]{.greek-added} [ορασεις]{.greek-added} [οψονται]{.greek-added} [και]{.greek-added} [οι]{.greek-added} [πρεσβυτεροι]{.greek-added} [υμων]{.greek-added} [ενυπνια]{.greek-added} [ενυπνιασθησονται]{.greek-added}[2:17]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις [και]{.greek-added} εκχεω απο του [πνευματος]{.greek-abbr} μου και [προφητευσουσιν]{.greek-omitted} [προφητευσουσι]{.greek-added} [και]{.greek-added} [γε]{.greek-added} [επι]{.greek-added} [τους]{.greek-added} [δουλους]{.greek-added} [μου]{.greek-added} [και]{.greek-added} [επι]{.greek-added} [τας]{.greek-added} [δουλας]{.greek-added} [μου]{.greek-added} [εν]{.greek-added} [ταις]{.greek-added} [ημεραις]{.greek-added} [εκειναις]{.greek-added} [και]{.greek-added} [εκχεω]{.greek-added} [απο]{.greek-added} [του]{.greek-added} [[πνευματος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} [και]{.greek-added} [προφητευσουσι]{.greek-added}[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω και σημεια επι της γης κατω αιμα και πυρ και ατμιδα καπνου [και]{.greek-added} [δωσω]{.greek-added} [τερατα]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [[ουρανω]{.greek-abbr}]{.greek-added} [ανω]{.greek-added} [και]{.greek-added} [σημεια]{.greek-added} [επι]{.greek-added} [της]{.greek-added} [γης]{.greek-added} [κατω]{.greek-added} [αιμα]{.greek-added} [και]{.greek-added} [πυρ]{.greek-added} [και]{.greek-added} [ατμιδα]{.greek-added} [καπνου]{.greek-added}[2:19]{.aside}

ο ηλιος μεταστραφησεται εις σκοτος και η σεληνη εις αιμα πριν η ελθειν την ημεραν [κυριου]{.greek-abbr} την μεγαλην και επιφανη [ο]{.greek-added} [ηλιος]{.greek-added} [μεταστραφησεται]{.greek-added} [εις]{.greek-added} [σκοτος]{.greek-added} [και]{.greek-added} [η]{.greek-added} [σεληνη]{.greek-added} [εις]{.greek-added} [αιμα]{.greek-added} [πριν]{.greek-added} [η]{.greek-added} [ελθειν]{.greek-added} [την]{.greek-added} [ημεραν]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [την]{.greek-added} [μεγαλην]{.greek-added} [και]{.greek-added} [επιφανη]{.greek-added}[2:20]{.aside}

και εσται πας ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθησεται [και]{.greek-added} [εσται]{.greek-added} [πας]{.greek-added} [ος]{.greek-added} [αν]{.greek-added} [επικαλεσηται]{.greek-added} [το]{.greek-added} [ονομα]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [σωθησεται]{.greek-added}[2:21]{.aside}

ανδρες ισραηλιται ακουσατε τους λογους τουτους [ιησουν]{.greek-abbr} τον ναζωραιον ανδρα απο του [θεου]{.greek-abbr} αποδεδειγμενον εις υμας [δυναμεσιν]{.greek-omitted} [δυναμεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και σημειοις οις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δι αυτου ο [θεος]{.greek-abbr} εν μεσω υμων καθως και αυτοι οιδατε [ανδρες]{.greek-added} [ισραηλιται]{.greek-added} [ακουσατε]{.greek-added} [τους]{.greek-added} [λογους]{.greek-added} [τουτους]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [τον]{.greek-added} [ναζωραιον]{.greek-added} [ανδρα]{.greek-added} [απο]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [αποδεδειγμενον]{.greek-added} [εις]{.greek-added} [υμας]{.greek-added} [δυναμεσι]{.greek-added} [και]{.greek-added} [τερασι]{.greek-added} [και]{.greek-added} [σημειοις]{.greek-added} [οις]{.greek-added} [εποιησε]{.greek-added} [δι]{.greek-added} [αυτου]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εν]{.greek-added} [μεσω]{.greek-added} [υμων]{.greek-added} [καθως]{.greek-added} [και]{.greek-added} [αυτοι]{.greek-added} [οιδατε]{.greek-added}[2:22]{.aside}

τουτον τη ωρισμενη βουλη και προγνωσει του [θεου]{.greek-abbr} εκδοτον λαβοντες δια χειρων ανομων προσπηξαντες [ανειλετε]{.greek-omitted} [ανειλατε]{.greek-added} [τουτον]{.greek-added} [τη]{.greek-added} [ωρισμενη]{.greek-added} [βουλη]{.greek-added} [και]{.greek-added} [προγνωσει]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [εκδοτον]{.greek-added} [λαβοντες]{.greek-added} [δια]{.greek-added} [χειρων]{.greek-added} [ανομων]{.greek-added} [προσπηξαντες]{.greek-added} [ανειλατε]{.greek-added}[2:23]{.aside}

ον ο [θεος]{.greek-abbr} ανεστησεν λυσας τας ωδινας του θανατου καθοτι ουκ ην δυνατον κρατεισθαι αυτον υπ αυτου [ον]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [ανεστησεν]{.greek-added} [λυσας]{.greek-added} [τας]{.greek-added} [ωδινας]{.greek-added} [του]{.greek-added} [θανατου]{.greek-added} [καθοτι]{.greek-added} [ουκ]{.greek-added} [ην]{.greek-added} [δυνατον]{.greek-added} [κρατεισθαι]{.greek-added} [αυτον]{.greek-added} [υπ]{.greek-added} [αυτου]{.greek-added}[2:24]{.aside}

[δαυιδ]{.greek-abbr} γαρ λεγει εις αυτον [προωρωμην]{.greek-omitted} [προ]{.greek-added} [ωρομην]{.greek-added} τον [κυριον]{.greek-abbr} ενωπιον μου δια παντος οτι εκ δεξιων μου εστιν ινα μη σαλευθω [[δαυιδ]{.greek-abbr}]{.greek-added} [γαρ]{.greek-added} [λεγει]{.greek-added} [εις]{.greek-added} [αυτον]{.greek-added} [προ]{.greek-added}[2:25]{.aside}

δια τουτο ευφρανθη η καρδια μου και ηγαλλιασατο η γλωσσα μου ετι δε και η σαρξ μου κατασκηνωσει επ ελπιδι[2:26]{.aside}

οτι ουκ εγκαταλειψεις την ψυχην μου εις αδου ουδε δωσεις τον οσιον σου ιδειν διαφθοραν[2:27]{.aside}

εγνωρισας μοι οδους ζωης πληρωσεις με ευφροσυνης μετα του προσωπου σου[2:28]{.aside}

ανδρες αδελφοι εξον ειπειν μετα παρρησιας προς υμας περι του πατριαρχου [δαυιδ]{.greek-abbr} οτι και ετελευτησεν και εταφη και το μνημα αυτου εστιν εν [ημιν]{.greek-omitted} [υμιν]{.greek-added} αχρι της ημερας ταυτης[2:29]{.aside}

προφητης ουν υπαρχων και ειδως οτι ορκω ωμοσεν αυτω ο [θεος]{.greek-abbr} εκ καρπου της οσφυος αυτου το κατα σαρκα [αναστησειν]{.greek-omitted} [αναστησιν]{.greek-added} τον [χριστον]{.greek-abbr} [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} επι του θρονου αυτου[2:30]{.aside}

[προιδων]{.greek-omitted} [προϊδων]{.greek-added} ελαλησεν περι της αναστασεως του [χριστου]{.greek-abbr} οτι [ου]{.greek-omitted} [ουκ]{.greek-added} [κατελειφθη]{.greek-omitted} [εγκατεληφθη]{.greek-added} [εις]{.greek-added} [αδην]{.greek-added} η ψυχη αυτου [εις]{.greek-omitted} [αδου]{.greek-omitted} [ουδε]{.greek-omitted} [ουτε]{.greek-added} η σαρξ αυτου ειδεν διαφθοραν[2:31]{.aside}

τουτον τον [ιησουν]{.greek-abbr} ανεστησεν ο [θεος]{.greek-abbr} ου παντες ημεις εσμεν μαρτυρες[2:32]{.aside}

τη δεξια ουν του [θεου]{.greek-abbr} υψωθεις την τε επαγγελιαν του αγιου [πνευματος]{.greek-abbr} λαβων παρα του [πατρος]{.greek-abbr} εξεχεεν τουτο ο νυν υμεις βλεπετε και ακουετε[2:33]{.aside}

ου γαρ [δαυιδ]{.greek-abbr} ανεβη εις τους [ουρανους]{.greek-abbr} λεγει δε αυτος ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου[2:34]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[2:35]{.aside}

ασφαλως ουν γινωσκετω πας οικος ισραηλ οτι και [κυριον]{.greek-abbr} και [χριστον]{.greek-abbr} αυτον ο [θεος]{.greek-abbr} εποιησεν τουτον [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [ον]{.greek-omitted} [υμεις]{.greek-omitted} [εσταυρωσατε]{.greek-omitted}[2:36]{.aside}

[αινουντες]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [και]{.greek-omitted} [εχοντες]{.greek-omitted} [χαριν]{.greek-omitted} [προς]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} ο δε [προσετιθει]{.greek-added} [κυριος]{.greek-abbr} [προσετιθει]{.greek-omitted} τους σωζομενους καθ ημεραν τη εκκλησια[2:47]{.aside}

### Chapter 3

επι το αυτο δε πετρος και ιωαννης ανεβαινον εις το ιερον επι την ωραν της προσευχης την ενατην[3:1]{.aside}

και τις ανηρ χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων εβασταζετο ον ετιθουν καθ ημεραν προς την θυραν του ιερου την λεγομενην ωραιαν του αιτειν ελεημοσυνην παρα των εισπορευομενων εις το ιερον[3:2]{.aside}

ος ιδων πετρον και ιωαννην μελλοντας εισιεναι εις το ιερον ηρωτα ελεημοσυνην[3:3]{.aside}

[ατενισας]{.greek-omitted} [ατενησας]{.greek-added} δε πετρος εις αυτον συν τω ιωαννη ειπεν βλεψον εις ημας[3:4]{.aside}

ο δε [επειχεν]{.greek-omitted} [επεισχεν]{.greek-added} [[επεσχεν]{.corr}]{.greek-added} αυτοις προσδοκων τι παρ αυτων λαβειν[3:5]{.aside}

ειπεν δε πετρος αργυριον και χρυσιον ουχ υπαρχει μοι ο δε εχω τουτο σοι [διδωμι]{.greek-omitted} [διδομι]{.greek-added} εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[3:6]{.aside}

και πιασας αυτον της δεξιας χειρος ηγειρεν παραχρημα δε εστερεωθησαν αυτου αι βασεις και τα σφυρα[3:7]{.aside}

και εξαλλομενος εστη και περιεπατει και εισηλθεν συν αυτοις εις το ιερον [περιπατον]{.greek-added} [περιπατων]{.corr} και αλλομενος και αινων τον [θεον]{.greek-abbr}[3:8]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτον πας ο λαος περιπατουντα και αινουντα τον [θεον]{.greek-abbr}[3:9]{.aside}

επεγινωσκον τε αυτον οτι ουτος ην ο προς την ελεημοσυνην καθημενος επι τη ωραια πυλη του ιερου και επλησθησαν θαμβους και εκστασεως επι τω συμβεβηκοτι αυτω[3:10]{.aside}

κρατουντος δε του ιαθεντος χωλου τον πετρον και ιωαννην συνεδραμεν προς αυτους πας ο λαος επι τη στοα τη καλουμενη σολομωντος εκθαμβοι[3:11]{.aside}

ιδων δε πετρος απεκρινατο προς τον λαον ανδρες ισραηλιται τι θαυμαζετε επι τουτω η ημιν τι ατενιζετε ως ιδια δυναμει η ευσεβεια [πεποιηκοσιν]{.greek-omitted} [πεποιηκοσι]{.greek-added} του περιπατειν αυτον[3:12]{.aside}

ο [θεος]{.greek-abbr} αβρααμ και ισαακ και ιακωβ ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [εδοξασεν]{.greek-omitted} [εδοξασε]{.greek-added} τον παιδα αυτου [ιησουν]{.greek-abbr} ον υμεις μεν παρεδωκατε και ηρνησασθε αυτον κατα προσωπον πιλατου κριναντος εκεινου απολυειν[3:13]{.aside}

υμεις δε τον αγιον και δικαιον ηρνησασθε και ητησασθε ανδρα φονεα χαρισθηναι [ημιν]{.greek-added} [υμιν]{.corr}[3:14]{.aside}

τον δε αρχηγον της ζωης απεκτεινατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων ου ημεις μαρτυρες εσμεν[3:15]{.aside}

και επι τη πιστει του ονοματος αυτου τουτον ον θεωρειτε και οιδατε [εστερεωσεν]{.greek-omitted} [εστερεωσε]{.greek-added} το ονομα αυτου και η πιστις η δι αυτου εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[3:16]{.aside}

και νυν αδελφοι οιδα οτι κατα αγνοιαν επραξατε ωσπερ και οι αρχοντες υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α προκατηγγειλεν δια στοματος παντων των προφητων αυτου παθειν τον [χριστον]{.greek-abbr} επληρωσεν ουτως[3:18]{.aside}

μετανοησατε ουν και [επιστρεψατε]{.greek-omitted} [επιστραψατε]{.greek-added} εις το [εξαλειφθηναι]{.greek-omitted} [εξαληφθηναι]{.greek-added} υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσι]{.greek-added} [καιροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και αποστειλη τον προκεχειρισμενον υμιν [[ιησουν]{.greek-abbr}]{.greek-added} [χριστον]{.greek-abbr} [ιησουν]{.greek-omitted}[3:20]{.aside}

ον δει [ουρανον]{.greek-abbr} μεν δεξασθαι αχρι χρονων αποκαταστασεως παντων ων ελαλησεν ο [θεος]{.greek-abbr} δια στοματος παντων των αγιων αυτου προφητων απ αιωνος[3:21]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} μεν [γαρ]{.greek-omitted} [ειπεν]{.greek-added} προς τους [πατερας]{.greek-abbr} [ειπεν]{.greek-omitted} [ημων]{.greek-added} οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων εκ των αδελφων υμων ως εμε αυτου [ακουσεσθε]{.greek-omitted} [ακουσεσθαι]{.greek-added} κατα παντα οσα αν λαληση προς υμας[3:22]{.aside}

εσται δε πασα ψυχη ητις [εαν]{.greek-omitted} [αν]{.greek-added} μη ακουση του προφητου εκεινου εξολοθρευθησεται εκ του λαου[3:23]{.aside}

και παντες δε οι προφηται απο σαμουηλ και των καθεξης οσοι ελαλησαν και [κατηγγειλαν]{.greek-omitted} [προκατηγγειλαν]{.greek-added} τας ημερας ταυτας[3:24]{.aside}

υμεις εστε υιοι των προφητων και της διαθηκης ης διεθετο ο [θεος]{.greek-abbr} προς τους [πατερας]{.greek-abbr} ημων λεγων προς αβρααμ και εν τω σπερματι σου ενευλογηθησονται πασαι αι πατριαι της γης[3:25]{.aside}

υμιν πρωτον ο [θεος]{.greek-abbr} αναστησας τον παιδα αυτου [ιησουν]{.greek-abbr} απεστειλεν αυτον ευλογουντα υμας εν τω αποστρεφειν εκαστον απο των πονηριων υμων[3:26]{.aside}

### Chapter 4

λαλουντων δε αυτων προς τον λαον επεστησαν αυτοις οι ιερεις και ο στρατηγος του ιερου και οι σαδδουκαιοι[4:1]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον λαον και καταγγελλειν εν τω [ιησου]{.greek-abbr} την αναστασιν των νεκρων[4:2]{.aside}

και επεβαλον αυτοις τας χειρας και εθεντο [αυτους]{.greek-added} εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι δε των ακουσαντων τον λογον επιστευσαν και εγενηθη ο αριθμος των ανδρων ωσει χιλιαδες πεντε[4:4]{.aside}

εγενετο δε επι την αυριον συναχθηναι αυτων τους αρχοντας και πρεσβυτερους και γραμματεις εις [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και ανναν τον [αρ]{.greek-added} [αρχιερεα]{.greek-omitted} [χιερεα]{.greek-added} και [καιαφαν]{.greek-omitted} [καϊαφαν]{.greek-added} και ιωαννην και αλεξανδρον και οσοι ησαν εκ γενους αρχιερατικου[4:6]{.aside}

και στησαντες αυτους εν μεσω επυνθανοντο εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος πλησθεις [πνευματος]{.greek-abbr} αγιου ειπεν προς αυτους αρχοντες του λαου και πρεσβυτεροι του [λαου]{.greek-added} [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα επι ευεργεσια [ανθρωπου]{.greek-abbr} ασθενους εν τινι ουτος σεσωσται[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω ισραηλ οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις [εσταυρωσατε]{.greek-abbr} ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν τουτω [ουτος]{.greek-omitted} [ουτως]{.greek-added} παρεστηκεν ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ υμων των οικοδομουντων ο γενομενος εις κεφαλην γωνιας[4:11]{.aside}

και ουκ εστιν εν αλλω ουδενι η [σωτηρια]{.greek-abbr} [ουτε]{.greek-omitted} [ουδε]{.greek-added} γαρ ονομα [ετερον]{.greek-added} εστιν [ετερον]{.greek-omitted} [υπο]{.greek-added} [τον]{.greek-added} [[ουρανον]{.greek-abbr}]{.greek-added} το δεδομενον εν [ανθρωποις]{.greek-abbr} εν ω δει σωθηναι ημας[4:12]{.aside}

θεωρουντες δε την του πετρου παρρησιαν και ιωαννου και καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι εισιν και ιδιωται εθαυμαζον επεγινωσκον τε αυτους οτι συν τω [ιησου]{.greek-abbr} ησαν[4:13]{.aside}

τον [δε]{.greek-omitted} [τε]{.greek-added} [ανθρωπον]{.greek-abbr} [βλεποντες]{.greek-omitted} [θεωρουντες]{.greek-added} συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου απελθειν συνεβαλλον προς αλληλους[4:15]{.aside}

λεγοντες τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} τοις ανθρωποις τουτοις οτι μεν [γνωστον]{.greek-added} γαρ [γνωστον]{.greek-omitted} σημειον γεγονεν δι αυτων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} φανερον και ου δυναμεθα αρνησασθαι[4:16]{.aside}

αλλ ινα μη επι πλειον διανεμηθη εις τον λαον απειλη [απειλησομεθα]{.greek-omitted} [απειλησωμεθα]{.greek-added} αυτοις μηκετι λαλειν επι τω ονοματι τουτω μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και καλεσαντες αυτους παρηγγειλαν [αυτοις]{.greek-omitted} το καθολου μη φθεγγεσθαι μηδε διδασκειν επι τω ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

ο δε πετρος και ιωαννης αποκριθεντες προς αυτους ειπον ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ ημεις α ειδομεν και ηκουσαμεν μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως κολασονται [[κολασωνται]{.corr}]{.greek-added} αυτους δια τον λαον οτι παντες εδοξαζον τον [θεον]{.greek-abbr} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων τεσσαρακοντα ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε [οι]{.greek-added} [αποστολοι]{.greek-added} ηλθον προς τους ιδιους και απηγγειλαν οσα προς αυτους οι αρχιερεις και οι πρεσβυτεροι ειπον[4:23]{.aside}

οι δε ακουσαντες ομοθυμαδον ηραν φωνην προς τον [θεον]{.greek-abbr} και ειπον δεσποτα συ ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[4:24]{.aside}

ο δια στοματος [δαυιδ]{.greek-abbr} [του]{.greek-added} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

παρεστησαν οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} [[[χριστου]{.greek-abbr}]{.corr}]{.greek-added} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας επι τον αγιον παιδα σου [ιησουν]{.greek-abbr} ον [εχρισας]{.greek-omitted} [εχρησας]{.greek-added} ηρωδης τε και ποντιος πιλατος συν [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και [λαοις]{.greek-omitted} [λαος]{.greek-added} [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η βουλη σου [προωρισεν]{.greek-omitted} [προωρησε]{.greek-added} γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} επιδε επι τας απειλας αυτων και δος τοις δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την χειρα σου εκτεινειν σε εις ιασιν και σημεια [και]{.greek-omitted} τερατα γινεσθαι δια του ονοματος του αγιου παιδος σου [ιησου]{.greek-abbr}[4:30]{.aside}

και δεηθεντων αυτων εσαλευθη ο τοπος εν ω ησαν συνηγμενοι και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ελαλουν τον λογον του [θεου]{.greek-abbr} μετα παρρησιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και ουδε εις τι των υπαρχοντων αυτων ελεγεν ιδιον ειναι αλλ ην αυτοις απαντα κοινα[4:32]{.aside}

και μεγαλη δυναμει απεδιδουν [οι]{.greek-added} [αποστολοι]{.greek-added} το μαρτυριον [οι]{.greek-omitted} [αποστολοι]{.greek-omitted} της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} χαρις τε μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις υπηρχεν εν αυτοις οσοι γαρ κτητορες χωριων η οικιων υπηρχον [πωλουντες]{.greek-omitted} [πολουντες]{.greek-added} εφερον τας τιμας των [πιπρασκοντων]{.greek-added} [πιπρασκομενων]{.corr}[4:34]{.aside}

και ετιθουν παρα τους ποδας των αποστολων [διεδιδοτο]{.greek-omitted} [διεδιδετο]{.greek-added} δε εκαστω καθοτι αν τις χρειαν ειχεν[4:35]{.aside}

ιωσης δε ο επικληθεις βαρναβας απο των αποστολων ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον υιος παρακλησεως λευιτης κυπριος τω γενει[4:36]{.aside}

υπαρχοντος [αυτω]{.greek-omitted} [αυτου]{.greek-added} αγρου πωλησας [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} το χρημα και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις ανανιας ονοματι συν [σαπφειρη]{.greek-omitted} [σαπφιρη]{.greek-added} τη γυναικι αυτου [επωλησεν]{.greek-omitted} [επω]{.greek-added} [λησε]{.greek-added} κτημα[5:1]{.aside}

και ενοσφισατο απο της τιμης [συνειδυιας]{.greek-omitted} [συνηδυιας]{.greek-added} και της γυναικος αυτου και ενεγκας μερος τι παρα τους ποδας των αποστολων εθηκεν[5:2]{.aside}

ειπεν δε πετρος ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι σε απο της τιμης του χωριου[5:3]{.aside}

ουχι μενον σοι εμενεν και πραθεν εν τη ση εξουσια υπηρχεν τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε ο ανανιας τους λογους τουτους πεσων εξεψυξεν και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι [νεωτεροι]{.greek-omitted} [νεοτεροι]{.greek-added} [συνεστειλαν]{.greek-omitted} [συνεεστειλαν]{.greek-added} αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων διαστημα και η γυνη αυτου μη ειδυια το γεγονος εισηλθεν[5:7]{.aside}

απεκριθη δε αυτη ο πετρος ειπε μοι ει τοσουτου το χωριον απεδοσθε η δε ειπεν ναι τοσουτου[5:8]{.aside}

ο δε πετρος ειπεν προς αυτην τι οτι συνεφωνηθη υμιν πειρασαι το [πνευμα]{.greek-abbr} κυριου ιδου οι ποδες των θαψαντων τον ανδρα σου επι τη θυρα και [εξοισουσιν]{.greek-omitted} [εξυσουσι]{.greek-added} σε[5:9]{.aside}

επεσεν δε παραχρημα παρα τους ποδας αυτου και εξεψυξεν εισελθοντες δε οι νεανισκοι ευρον αυτην νεκραν και εξενεγκαντες εθαψαν προς τον ανδρα αυτης[5:10]{.aside}

και εγενετο φοβος μεγας εφ ολην την εκκλησιαν και επι παντα[ς]{.unclear} τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων εγινετο [ση]{.greek-added} [σημεια]{.greek-omitted} [μεια]{.greek-added} και τερατα [πολλα]{.greek-added} εν τω λαω [πολλα]{.greek-omitted} και ησαν ομοθυμαδον απαντες εν τη στοα [σολομωντος]{.greek-omitted} [σολομωνος]{.greek-added}[5:12]{.aside}

των δε λοιπων ουδεις ετολμα κολλασθαι αυτοις αλλ εμεγαλυνεν αυτους ο λαος[5:13]{.aside}

μαλλον δε [προσετιθ[ο]{.unclear}ντο]{.greek-added} [προσετιθεντο]{.corr} [οι]{.greek-added} πιστευοντες τω [κυριω]{.greek-abbr} πληθη ανδρων τε και γυναικων[5:14]{.aside}

ωστε κατα τας πλατειας εκφερειν τους ασθενεις και τιθεναι επι κλινων και [κραββατων]{.greek-omitted} [κραβαττων]{.greek-added} ινα ερχομενου πετρου καν η σκια [επισκιασει]{.greek-added} [επισκιαση]{.corr} τινι αυτων[5:15]{.aside}

συνηρχετο δε και το πληθος των περιξ πολεων εις [ιερουσαλημ]{.greek-abbr} φεροντες ασθενεις και οχλουμενους υπο [πνευματων]{.greek-abbr} ακαθαρτων οιτινες εθεραπευοντο απαντες[5:16]{.aside}

αναστας δε ο αρχιερευς και παντες οι συν αυτω η ουσα αιρεσις των σαδδουκαιων επλησθησαν ζηλου[5:17]{.aside}

και επεβαλον τας χειρας αυτων επι τους αποστολους και εθεντο αυτους εν [τηρησει]{.greek-omitted} [τηρηση]{.greek-added} δημοσια[5:18]{.aside}

αγγελος δε [κυριου]{.greek-abbr} δια της νυκτος [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τας θυρας της φυλακης εξαγαγων τε αυτους ειπεν[5:19]{.aside}

πορευεσθε και σταθεντες λαλειτε εν τω ιερω [τω]{.greek-omitted} [λαω]{.greek-omitted} παντα τα ρηματα της ζωης ταυτης[5:20]{.aside}

ακουσαντες δε εισηλθον υπο τον ορθρον εις το ιερον και εδιδασκον παραγενομενος δε ο αρχιερευς και οι συν αυτω [[αυτο[ις]{.unclear}]{.corr}]{.greek-added} συνεκαλεσαν το συνεδριον και πασαν την γερουσιαν των υιων [ισραηλ]{.greek-abbr} και απεστειλαν εις το δεσμωτηριον αχθηναι αυτους[5:21]{.aside}

οι δε υπηρεται παραγενομενοι ουχ ευρον αυτους εν τη φυλακη αναστρεψαντες δε απηγγειλαν[5:22]{.aside}

λεγοντες οτι το μεν δεσμωτηριον [ευρομεν]{.greek-omitted} [ευραμεν]{.greek-added} κεκλεισμενον εν παση ασφαλεια και τους φυλακας εστωτας προ των θυρων ανοιξαντες δε εσω ουδενα [ευρομεν]{.greek-omitted} [ευραμεν]{.greek-added}[5:23]{.aside}

ως δε ηκουσαν τους λογους τουτους ο τε ιερευς και ο στρατηγος του ιερου και οι αρχιερεις διηπορουν περι αυτων τι αν γενοιτο τουτο[5:24]{.aside}

παραγενομενος δε τις απηγγειλεν αυτοις οτι ιδου οι ανδρες ους εθεσθε εν τη φυλακη εισιν εν τω ιερω εστωτες και διδασκοντες τον λαον[5:25]{.aside}

τοτε απελθων ο στρατηγος συν τοις υπηρεταις ηγαγεν αυτους ου μετα βιας εφοβουντο γαρ τον λαον ινα μη λιθασθωσιν[5:26]{.aside}

αγαγοντες δε αυτους εστησαν εν τω συνεδριω και επηρωτησεν αυτους ο αρχιερευς[5:27]{.aside}

λεγων ου [παραγγελια]{.greek-omitted} [παραγγελεια]{.greek-added} παρηγγειλαμεν υμιν μη διδασκειν επι τω ονοματι τουτω και ιδου πεπληρωκατε την [ιερουσαλημ]{.greek-abbr} της διδαχης υμων και βουλεσθε επαγαγειν εφ ημας το αιμα του [ανθρωπου]{.greek-abbr} τουτου[5:28]{.aside}

αποκριθεις δε πετρος και οι αποστολοι ειπον πειθαρχειν δει [θεω]{.greek-abbr} μαλλον η [ανθρωποις]{.greek-abbr}[5:29]{.aside}

ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων ηγειρεν [ιησουν]{.greek-abbr} ον υμεις διεχειρισασθε κρεμασαντες επι ξυλου[5:30]{.aside}

τουτον ο [θεος]{.greek-abbr} αρχηγον και [σωτηρα]{.greek-abbr} υψωσεν τη δεξια αυτου δουναι μετανοιαν τω [ισραηλ]{.greek-abbr} και αφεσιν αμαρτιων[5:31]{.aside}

και ημεις εσμεν αυτου μαρτυρες των ρηματων τουτων και το [πνευμα]{.greek-abbr} [δε]{.greek-omitted} το αγιον ο εδωκεν ο [θεος]{.greek-abbr} τοις πειθαρχουσιν αυτω[5:32]{.aside}

οι δε ακουοντες διεπριοντο και εβουλευοντο ανελειν αυτους[5:33]{.aside}

αναστας δε τις εν τω συνεδριω φαρισαιος ονοματι γαμαλιηλ νομοδιδασκαλος τιμιος παντι τω λαω εκελευσεν εξω βραχυ τι τους αποστολους ποιησαι[5:34]{.aside}

ειπεν τε προς αυτους ανδρες ισραηλιται προσεχετε εαυτοις επι τοις [ανθρωποις]{.greek-abbr} τουτοις τι μελλετε πρασσειν[5:35]{.aside}

προ γαρ τουτων των ημερων ανεστη θευδας λεγων ειναι τινα εαυτον [μεγαν]{.greek-added} ω προσεκληθη αριθμος ανδρων [ωσει]{.greek-omitted} [ως]{.greek-added} τετρακοσιων ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις [ουδεν]{.greek-omitted} [ουθεν]{.greek-added}[5:36]{.aside}

μετα τουτον ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της απογραφης και απεστησεν [ικανον]{.greek-added} λαον [ικανον]{.greek-omitted} οπισω αυτου κακεινος απωλετο και παντες οσοι επειθοντο αυτω διεσκορπισθησαν[5:37]{.aside}

και τα νυν λεγω υμιν αποστητε απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε αυτους οτι εαν η εξ [ανθρωπων]{.greek-abbr} η βουλη [αυτη]{.greek-added} η το εργον τουτο καταλυθησεται[5:38]{.aside}

ει δε εκ [θεου]{.greek-abbr} εστιν ου [δυνασθε]{.greek-omitted} [δυνησεσθε]{.greek-added} καταλυσαι αυτο μηποτε και θεομαχοι ευρεθητε [επισθησαν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added}[5:39]{.aside}

[επεισθησαν]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} και προσκαλεσαμενοι τους αποστολους δειραντες παρηγγειλαν μη λαλειν επι τω ονοματι του [ιησου]{.greek-abbr} και απελυσαν αυτους[5:40]{.aside}

οι μεν ουν επορευοντο χαιροντες απο προσωπου του συνεδριου οτι υπερ του ονοματος [του]{.greek-omitted} [ιησου]{.greek-abbr} κατηξιωθησαν ατιμασθηναι[5:41]{.aside}

πασαν τε ημεραν εν τω ιερω και κατ οικον ουκ επαυοντο διδασκοντες και ευαγγελιζομενοι [ιησουν]{.greek-omitted} τον [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added}[5:42]{.aside}

### Chapter 6

εν δε ταις ημεραις ταυταις πληθυνοντων των μαθητων εγενετο γογγυσμος των ελληνιστων προς τους εβραιους οτι παρεθεωρουντο εν τη διακονια τη καθημερινη αι [χηραι]{.greek-omitted} [χειραι]{.greek-added} αυτων[6:1]{.aside}

προσκαλεσαμενοι δε οι δωδεκα το πληθος των μαθητων ειπον ουκ αρεστον εστιν [καταλειποντας]{.greek-added} ημας [καταλειψαντας]{.greek-omitted} τον λογον του [θεου]{.greek-abbr} διακονειν τραπεζαις[6:2]{.aside}

επισκεψασθε ουν αδελφοι ανδρας εξ υμων μαρτυρουμενους επτα πληρεις [πνευματος]{.greek-abbr} αγιου και σοφιας ους καταστησωμεν επι της χρειας ταυτης[6:3]{.aside}

ημεις δε τη προσευχη και τη διακονια του λογου [προσκαρτερησομεν]{.greek-omitted} [προσκαρτερησωμεν]{.greek-added}[6:4]{.aside}

και ηρεσεν ο λογος ενωπιον παντος του πληθους και εξελεξαντο [ανδρα]{.greek-added} στεφανον [ανδρα]{.greek-omitted} [ονοματι]{.greek-added} πληρης πιστεως και [πνευματος]{.greek-abbr} αγιου και φιλιππον και προχορον και νικανορα και τιμωνα και παρμεναν και νικολαον προσηλυτον αντιοχεα[6:5]{.aside}

ους εστησαν ενωπιον των αποστολων και προσευξαμενοι επεθηκαν αυτοις τας χειρας[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} ηυξανεν και επληθυνετο ο αριθμος των μαθητων εν [ιερουσαλημ]{.greek-abbr} σφοδρα πολυς τε οχλος των ιερεων υπηκουον τη πιστει[6:7]{.aside}

στεφανος δε πληρης [πιστεως]{.greek-omitted} [χαριτος]{.greek-added} και δυναμεως εποιει τερατα και σημεια μεγαλα εν τω λαω [δια]{.greek-added} [του]{.greek-added} [ονοματος]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added}[6:8]{.aside}

ανεστησαν δε τινες των εκ της συναγωγης [της]{.greek-omitted} [των]{.greek-added} [λεγομενης]{.greek-omitted} [λεγομενων]{.greek-added} λιβερτινων και [κυρηναιων]{.greek-omitted} [κυριναιων]{.greek-added} και αλεξανδρεων και των απο κιλικιας και ασιας συζητουντες τω στεφανω[6:9]{.aside}

και ουκ ισχυον αντιστηναι τη σοφια και τω [πνευματι]{.greek-abbr} ω ελαλει[6:10]{.aside}

τοτε υπεβαλον ανδρας λεγοντας οτι ακηκοαμεν αυτου λαλουντος ρηματα βλασφημα εις [μωσην]{.greek-omitted} [μωυσην]{.greek-added} και τον [θεον]{.greek-abbr}[6:11]{.aside}

συνεκινησαν τε τον λαον και τους πρεσβυτερους και τους γραμματεις και επισταντες συνηρπασαν αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας ψευδεις λεγοντας ο [ανθρωπος]{.greek-abbr} ουτος ου παυεται [ρηματα]{.greek-omitted} [βλασφημα]{.greek-omitted} [λαλων]{.greek-omitted} κατα του τοπου του αγιου [τουτου]{.greek-added} και του νομου [λαλων]{.greek-added} [ρηματα]{.greek-added} [βλασφημα]{.greek-added}[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος καταλυσει τον τοπον τουτον και αλλαξει τα εθη α παρεδωκεν ημιν [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[6:14]{.aside}

και [ατενισαντες]{.greek-omitted} [ατενησαντες]{.greek-added} εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω ειδον το προσωπον αυτου ωσει προσωπον αγγελου[6:15]{.aside}

### Chapter 7

ειπεν δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} ημων αβρααμ οντι εν τη μεσοποταμια πριν η κατοικησαι αυτον εν χαρραν[7:2]{.aside}

και ειπεν προς αυτον εξελθε εκ της γης σου και εκ της [συγγενειας]{.greek-omitted} [συγγενιας]{.greek-added} σου και δευρο εις γην ην αν σοι δειξω[7:3]{.aside}

τοτε εξελθων εκ γης χαλδαιων κατωκησεν εν χαρραν κακειθεν μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μετωκησεν]{.greek-added} αυτον εις την γην ταυτην εις ην υμεις νυν κατοικειτε[7:4]{.aside}

και ουκ εδωκεν αυτω κληρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι [αυτω]{.greek-omitted} [αυτην]{.greek-added} εις κατασχεσιν [αυτην]{.greek-omitted} [αυτω]{.greek-added} και τω σπερματι αυτου μετ αυτον ουκ οντος αυτω τεκνου[7:5]{.aside}

ελαλησεν δε ουτως ο [θεος]{.greek-abbr} οτι εσται το σπερμα αυτου παροικον εν γη αλλοτρια και δουλωσουσιν [αυτο]{.greek-omitted} [αυτω]{.greek-added} και κακωσουσιν ετη τετρακοσια[7:6]{.aside}

και το εθνος ω εαν δουλευσωσιν κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και λατρευσουσιν μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και ουτως [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ και περιετεμεν αυτον τη ημερα τη ογδοη και ο ισαακ τον ιακωβ και ο ιακωβ τους δωδεκα πατριαρχας[7:8]{.aside}

και οι πατριαρχαι ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και [εξειλετο]{.greek-omitted} [εξειλατο]{.greek-added} αυτον εκ πασων των θλιψεων αυτου και εδωκεν αυτω χαριν και σοφιαν [εναντιον]{.greek-omitted} [εναντιων]{.greek-added} φαραω βασιλεως αιγυπτου και κατεστησεν αυτον ηγουμενον επ αιγυπτον και ολον τον οικον αυτου[7:10]{.aside}

ηλθεν δε λιμος εφ ολην την γην αιγυπτου και χανααν και θλιψις μεγαλη και ουχ ευρισκον χορτασματα οι [πατερες]{.greek-abbr} ημων[7:11]{.aside}

ακουσας δε ιακωβ οντα σιτα εν αιγυπτω εξαπεστειλεν τους [πατερας]{.greek-abbr} ημων πρωτον[7:12]{.aside}

και εν τω δευτερω ανεγνωρισθη ιωσηφ τοις αδελφοις αυτου και φανερον εγενετο τω φαραω το γενος του ιωσηφ[7:13]{.aside}

αποστειλας δε ιωσηφ μετεκαλεσατο τον [πατερα]{.greek-abbr} αυτου ιακωβ και πασαν την [συγγενειαν]{.greek-omitted} [συγγενιαν]{.greek-added} εν [ψυχαις]{.greek-omitted} εβδομηκοντα πεντε [ψυχαις]{.greek-added}[7:14]{.aside}

κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν αυτος και οι [πατερες]{.greek-abbr} ημω[ν]{.greek-supplied}[7:15]{.aside}

και μετετεθησαν εις συχεμ και ετεθησαν εν τω μνηματι [ο]{.greek-omitted} [ω]{.greek-added} ωνησατο αβρααμ τιμης αργυριου παρα των υιων [εμμορ]{.greek-omitted} [εμορ]{.greek-added} του συχεμ[7:16]{.aside}

καθω[ς]{.unclear} δε ηγγιζεν ο χρονος της επαγγελιας ης ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος ος ουκ ηδει τον [[ιω]{.greek-abbr}]{.greek-added} [ιωσηφ]{.corr}[7:18]{.aside}

ουτος κατασοφισαμενος το γενος ημων [εκακωσεν]{.greek-omitted} [εκακωσε]{.greek-added} τους [πατερας]{.greek-abbr} ημων του [ποιειν]{.greek-omitted} [πιειν]{.greek-added} εκθετα τα βρεφη αυτων εις το μη ζωογονεισθαι[7:19]{.aside}

εν ω καιρω εγεννηθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ην [αστειος]{.greek-omitted} [αστει]{.greek-added} [ος]{.greek-added} τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr} [αυτου]{.greek-added}[7:20]{.aside}

εκτεθεντα δε αυτον ανειλετο η θυγατηρ φαραω και ανεθρεψατο αυτον εαυτη εις υιον[7:21]{.aside}

και επαιδευθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σοφια αιγυπτιων ην δε δυνατος εν [εργοις]{.greek-added} [και]{.greek-added} λογοις [και]{.greek-omitted} [εργοις]{.greek-omitted}[7:22]{.aside}

ως δε επληρουτο αυτω τεσσαρακονταετης χρονος ανεβη επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον ημυνατο και εποιησεν εκδικησιν τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

ενομιζεν δε [συνιεναι]{.greek-omitted} [συνειεναι]{.greek-added} τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις [σωτηριαν]{.greek-abbr} οι δε ου συνηκαν[7:25]{.aside}

τη τε επιουση ημερα ωφθη αυτοις μαχομενοις και [συνηλασεν]{.greek-omitted} [συνηλλασεν]{.greek-added} [[συνηλλασσεν]{.corr}]{.greek-added} αυτους εις ειρηνην ειπων ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} αδικειτε αλληλους[7:26]{.aside}

ο δε αδικων τον πλησ[ι]{.unclear}ον απωσατο αυτον ειπων τις σε κατεστησεν αρχοντα και δικαστην εφ [ημας]{.greek-omitted} [ημων]{.greek-added}[7:27]{.aside}

μη ανελειν με συ θελεις ον τροπον ανειλες χθες τον αιγυπτιον[7:28]{.aside}

[εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων τεσσαρακοντα ωφθη [αυτω]{.greek-omitted} [μωυση]{.greek-added} εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-abbr} εν φλογι πυρος βατου[7:30]{.aside}

ο δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [εθαυμασεν]{.greek-added} ιδων [εθαυμαζεν]{.greek-omitted} το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} προς αυτον[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} σου ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ εντρομος δε γενομενος [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουκ ετολμα κατανοησαι[7:32]{.aside}

ειπεν δε αυτω ο [κυριος]{.greek-abbr} λυσον το υποδημα των ποδων σου ο γαρ τοπος εν ω εστηκας γη αγια εστιν[7:33]{.aside}

ιδων ειδον την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και κατεβην εξελεσθαι αυτους και νυν δευρο αποστελω σε εις αιγυπτον[7:34]{.aside}

τουτον τον [μωσην]{.greek-omitted} [μωυσην]{.greek-added} ον [ηρνησαντο]{.greek-omitted} [ηρνισαντο]{.greek-added} ειποντες τις σε κατεστησεν αρχοντα και δικαστην [εφ]{.greek-added} [ημων]{.greek-added} τουτον ο [θεος]{.greek-abbr} αρχοντα και λυτρωτην απεστειλεν εν χειρι αγγελου του οφθεντος αυτω εν τη βατω[7:35]{.aside}

ουτος εξηγαγεν αυτους ποιησας τερατα και σημεια εν γη αιγυπτω και εν ερυθρα θαλασση και εν τη ερημω ετη τεσσαρακοντα[7:36]{.aside}

ουτος εστιν ο [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην [αναστησει]{.greek-added} υμιν [αναστησει]{.greek-omitted} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε [αυτου]{.greek-added} [ακουσασθε]{.greek-added}[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο [λογον]{.greek-omitted} [λογια]{.greek-added} ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθελησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων αλλ απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

ειποντες τω ααρων ποιησον ημιν θεους οι προπορευσονται ημων ο γαρ [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις εκειναις και ανηγαγον θυσιαν τω ειδωλω και ευφραινοντο εν τοις εργοις των χειρων αυτων[7:41]{.aside}

εστρεψεν δε ο [θεος]{.greek-abbr} και παρεδωκεν αυτους λατρευειν τη στρατια του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη σφαγια και θυσιας προσηνεγκατε μοι ετη τεσσαρακοντα εν τη ερημω οικος [ισραηλ]{.greek-abbr}[7:42]{.aside}

και ανελαβετε την σκηνην του [μολοχ]{.greek-omitted} [μελοχ]{.greek-added} και το αστρον του [θεου]{.greek-abbr} υμων [ρεμφαν]{.greek-omitted} [ραιμφαν]{.greek-added} τους τυπους ους εποιησατε προσκυνειν αυτοις και μετοικιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου ην τοις πατρασιν [ημων]{.greek-omitted} εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωϋση]{.greek-added} ποιησαι αυτην κατα τον τυπον ον εωρακει[7:44]{.aside}

ην και εισηγαγον διαδεξαμενοι οι [πατερες]{.greek-abbr} ημων μετα [ιησου]{.greek-abbr} εν τη κατασχεσει των εθνων ων εξωσεν ο [θεος]{.greek-abbr} απο προσωπου των [πατερων]{.greek-abbr} ημων εως των ημερων [δαυιδ]{.greek-abbr}[7:45]{.aside}

ος [ευρεν]{.greek-omitted} [ευρε]{.greek-added} χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν αυτω οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις ναοις κατοικει καθως ο προφητης λεγει[7:48]{.aside}

ο ουρανος μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον [οικοδομησετε]{.greek-omitted} [οικοδομησατε]{.greek-added} μοι λεγει [κυριος]{.greek-abbr} η τις τοπος της καταπαυσεως μου[7:49]{.aside}

ουχι η χειρ μου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} ταυτα παντα[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια και τοις ωσιν υμεις αει τω [πνευματι]{.greek-abbr} τω αγιω αντιπιπτετε ως [και]{.greek-added} οι [πατερες]{.greek-abbr} υμων και υμεις[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι [πατερες]{.greek-abbr} υμων και απεκτειναν τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις προδοται και φονεις γεγενησθε[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

[ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} δε ταυτα διεπριοντο ταις καρδιαις αυτων και εβρυχον τους οδοντας επ αυτον[7:54]{.aside}

υπαρχων δε [στεφανος]{.greek-added} [πληρης]{.greek-omitted} [πληρις]{.greek-added} [πνευματος]{.greek-abbr} αγιου [ατενισας]{.greek-omitted} [ατενησας]{.greek-added} εις τον ουρανον ειδεν δοξαν [θεου]{.greek-abbr} και [ιησουν]{.greek-abbr} εστωτα εκ δεξιων του [θεου]{.greek-abbr}[7:55]{.aside}

και ειπεν ιδου θεωρω τους [ουρανους]{.greek-abbr} ανεωγμενους και τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη συνεσχον τα ωτα αυτων και [ωρμησαν]{.greek-omitted} [ορμησαν]{.greek-added} ομοθυμαδον επ αυτον[7:57]{.aside}

και εκβαλοντες εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τα ιματια [αυτων]{.greek-added} παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added} δεξα[ι]{.greek-supplied} το [πνευμα]{.greek-abbr} μου[7:59]{.aside}

θεις δε τα γονατα [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη [κυριε]{.greek-abbr} μη στησης αυτοι[ς]{.greek-supplied} την αμαρτιαν ταυτην και τουτο ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

σαυλος δε ην συνευδοκ[ων]{.greek-supplied} τη αναιρεσει αυτου εγενετο δε εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις [και]{.greek-added} παντες [δε]{.greek-omitted} διεσπαρησαν κατα τας χωρας της ιουδαιας κ[αι]{.greek-supplied} σαμαρειας πλην των αποστολων[8:1]{.aside}

συνεκομισαν δε τον στεφανον ανδρες ευλαβεις και εποιησαντο κοπετον μεγαν επ αυτω[8:2]{.aside}

σαυλος δε ελυμαινετο την εκκλησιαν κατα τους οικους εισπορευομενος συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπαρεντες διηλθον ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος δε κατελθων εις πολιν της σαμαρειας εκηρυσσεν αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον τε οι οχλοι τοις λεγομενοις υπο του φιλιππου ομοθυμαδον εν τω ακουειν αυτους και βλεπειν τα σημεια α εποιει[8:6]{.aside}

πολλων γαρ των εχοντων [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} ακαθαρτα βοωντα φωνη μεγαλη [εξηρχετο]{.greek-omitted} [εξηρχοντο]{.greek-added} πολλοι δε παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

και εγενετο χαρα μεγαλη εν τη [πολει]{.greek-omitted} [πολη]{.greek-added} εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι σιμων προυπηρχεν εν τη πολει μαγευων και εξιστων το εθνος της σαμαρειας λεγων ειναι τινα εαυτον μεγαν[8:9]{.aside}

ω προσειχον [παντες]{.greek-added} απο μικρου εως μεγαλου λεγοντες ουτος εστιν η δυναμις του [θεου]{.greek-abbr} η μεγαλη[8:10]{.aside}

προσειχον δε αυτω δια [το]{.greek-omitted} [τω]{.greek-added} ικανω χρονω ταις [μαγειαις]{.greek-omitted} [μαγιαις]{.greek-added} εξεστακεναι αυτους[8:11]{.aside}

[οτε]{.greek-omitted} [ως]{.greek-added} δε επιστευσαν τω φιλιππω ευαγγελιζομενω τα περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος επιστευσεν και βαπτισθεις ην προσκαρτερων τω φιλιππω θεωρων τε [σημεια]{.greek-added} [και]{.greek-added} δυναμεις [μεγαλας]{.greek-added} [και]{.greek-omitted} [σημεια]{.greek-omitted} [γινομενα]{.greek-omitted} [γινομενας]{.greek-added} εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} [απεστειλαν]{.greek-omitted} [εξαπεστειλαν]{.greek-added} προς αυτους τον πετρον και ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως [λαβωσιν]{.greek-omitted} [λαβωσι]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

ουπω γαρ ην [[πνευμα]{.greek-abbr}]{.greek-added} [αγιον]{.greek-added} επ ουδενι αυτων [επιπεπτωκος]{.greek-omitted} [επιπεπτωκως]{.greek-added} μονον δε βεβαπτισμενοι [υπηρχον]{.greek-omitted} [υπηρχων]{.greek-added} εις το ονομα [[κυριου]{.greek-abbr}]{.greek-added} [του]{.greek-omitted} [χριστου]{.greek-omitted} [ιησου]{.greek-abbr}[8:16]{.aside}

τοτε επετιθουν τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

θεασαμενος δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω εαν επιθω τας χειρας λαμβανη [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε ειπεν προς αυτον το αργυριον σου συν σοι ειη εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} [ενομισας]{.greek-omitted} [ενομησας]{.greek-added} δια χρηματων κτασθαι[8:20]{.aside}

ουκ εστιν σοι μερις ουδε κληρος εν τω λογω τουτω η γαρ καρδια σου ουκ εστιν ευθεια ενωπιον του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} [ει]{.greek-omitted} [η]{.greek-added} αρα αφεθησ[ε]{.greek-supplied}ται σοι η επινοια της καρδιας σου[8:22]{.aside}

εις γαρ χολην πικριας και συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

[α]{.unclear}ποκριθεις δε ο σιμων ειπεν δεηθητε υμεις υπερ εμου προς τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι μεν ουν διαμαρτυραμενοι και λαλησαντες τον λογον του [κυριου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} πολλας τε κωμας των σαμαρειτων ευηγγελισαντο[8:25]{.aside}

αγγελ[ος]{.greek-supplied} [δε]{.greek-omitted} [κυριου]{.greek-abbr} ελαλησεν προς φιλιππον λεγων αναστηθι και πορευου κατα μεσημβριαν επι την οδον την καταβαινουσαν απο [ιερουσαλημ]{.greek-abbr} εις γαζαν αυτ[η]{.unclear} εστιν ερημος[8:26]{.aside}

και αναστα[ς]{.unclear} επορευθη και ιδου ανηρ αιθιοψ ευνουχος δυναστης κανδακης της βασιλισσης αιθιοπων ος ην επι πασης της γαζης αυτης ος εληλυθει προσκυνησων εις [ιερουσαλημ]{.greek-abbr}[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου [και]{.greek-omitted} ανεγινωσκεν τον προφητην ησαιαν[8:28]{.aside}

ειπεν δε το [πνευμα]{.greek-abbr} τω φιλιππω προσελθε και κολληθητι τω αρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος τον προφητην ησαιαν και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε ειπεν πως γαρ αν [δυναιμην]{.greek-omitted} [δυναμην]{.greek-added} εαν μη τις οδηγηση με παρεκαλεσεν τε τον φιλιππον αναβαντα καθισαι συν αυτω[8:31]{.aside}

η δε περιοχη της γραφης ην ανεγινωσκεν ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του [κειροντος]{.greek-omitted} [κειραντος]{.greek-added} αυτον αφωνος ουτως ουκ ανοιγει το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω ειπεν δεομαι σου περι τινος ο προφητης λεγει τουτο περι εαυτου [η]{.greek-omitted} [ει]{.greek-added} περι [ετερου]{.greek-omitted} [αλλου]{.greek-added} τινος[8:34]{.aside}

ανοιξας δε ο φιλιππος το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο [αυτω]{.greek-omitted} [αυτο]{.greek-added} τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο κατα την οδον ηλθον επι [τι]{.greek-omitted} [το]{.greek-added} υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

και εκελευσεν στηναι το αρμα και κατεβησαν αμφοτεροι εις το υδωρ ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν εκ του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} [ηρπασεν]{.greek-omitted} [ηρπασε]{.greek-added} τον φιλιππον και ουκ ειδεν αυτον ουκετι ο ευνουχος επορευετο γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις καισαρειαν[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις δαμασκον προς τας συναγωγας οπως εαν τινας ευρη της οδου οντας ανδρας τε και γυναικας δεδεμενους [αγαγη]{.greek-omitted} [εισαγαγη]{.greek-added} εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε τω πορευεσθαι εγενετο αυτον εγγιζειν τη δαμασκω και εξαιφνης περιηστραψεν αυτον φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην ηκουσεν φωνην λεγουσαν αυτω σαου[λ]{.unclear} σαουλ τι με διωκεις[9:4]{.aside}

ειπε[ν]{.greek-supplied} δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[9:5]{.aside}

αλλα αναστηθι και εισελθε εις την πολιν [και]{.greek-omitted} [κακει]{.greek-added} λαληθησ[ε]{.greek-supplied}ται σοι τι σε δει ποιειν[9:6]{.aside}

[ο]{.unclear}[ι]{.greek-supplied} δε ανδρες οι συνοδευοντες αυτω ειστηκεισαν ενεοι ακουοντες μεν της φωνης μηδενα δε θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων [τε]{.greek-omitted} [δε]{.greek-added} των οφθαλμων αυτου ουδενα εβλεπεν χειραγωγουντες δε αυτον εισηγαγον εις δαμασκον[9:8]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις [μαθητης]{.greek-omitted} εν δαμασκω [μαθητης]{.greek-added} ονοματι ανανιας [κ]{.unclear}[αι]{.greek-supplied} ειπεν προς αυτον ο [κυριος]{.greek-abbr} εν οραματι ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} εν οραματι ανδρα ονοματι ανανιαν εισελθοντα και επιθεντα αυτω χειρα οπως αναβλεψη[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και ωδε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

ειπεν δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει αυτον υπερ του ονοματος μου παθειν[9:16]{.aside}

απηλθεν δε ανανιας και εισηλθεν εις την οικιαν και επιθεις επ αυτον τας χειρας ειπεν σαουλ αδελφε ο [κυριος]{.greek-abbr} απεσταλκεν με ο οφθεις σοι εν τη οδω η ηρχου οπως αναβλεψης και [πλησθης]{.greek-omitted} [πλησθεις]{.greek-added} [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

[και]{.greek-omitted} ευθεως απεπεσον απο των οφθαλμων αυτου ωσει λεπιδες ανεβλεψεν τε [παραχρημα]{.greek-added} και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε [ο]{.greek-omitted} [σαυλος]{.greek-omitted} μετα των εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} τον [χριστον]{.greek-abbr} οτι ουτος εστιν ο υιος του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγον ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους αγαγη επι τους αρχιερεις[9:21]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και [συνεχυνεν]{.greek-omitted} [συνεχυνε]{.greek-added} τους ιουδαιους τους κατοικουντας εν δαμασκω [συμβιβαζων]{.greek-omitted} [συμβηβαζων]{.greek-added} οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω η επιβουλη αυτων παρετηρουν τε τας πυλας ημερας τε και νυκτος οπως αυτον ανελωσιν[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος [καθηκαν]{.greek-omitted} [καθεικαν]{.greek-added} [αυτον]{.greek-added} δια του τειχους χαλασαντες εν [σπυριδι]{.greek-omitted} [σπυριδη]{.greek-added}[9:25]{.aside}

παραγενομενος δε ο [σαυλος]{.greek-omitted} [παυλος]{.greek-added} εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι εστιν μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ειδε]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν τω ονοματι του [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr}[9:27]{.aside}

[om]{.greek-added} [και]{.greek-omitted} [ην]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted} [εισπορευομενος]{.greek-omitted} [εις]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [και]{.greek-omitted} [παρρησιαζομενος]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [ιησου]{.greek-omitted}[9:28]{.aside}

ελαλει τε και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

[επιγνοντες]{.greek-omitted} [επιγν[ω]{.unclear}ντες]{.greek-added} δε οι αδελφοι κατηγαγον [αυτον]{.greek-omitted} εις καισαρειαν και εξαπεστειλαν [αυτον]{.greek-omitted} εις ταρσον[9:30]{.aside}

αι μεν ουν εκκλησιαι καθ ολης της ιουδαιας και γαλιλαιας και σαμαρειας ειχον ειρηνην οικοδομουμεναι και πορευομεναι τω φοβω του [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} επληθυνοντο[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας [λυδδαν]{.greek-omitted} [λυδδα]{.greek-added}[9:32]{.aside}

ευρεν δε εκει ανθρωπον τινα [ονοματι]{.greek-added} αινεαν [ονοματι]{.greek-omitted} εξ ετων οκτω κατακειμενον επι [κραββατω]{.greek-omitted} [κραβαττω]{.greek-added} ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον σεαυτω και ευθεως ανεστη[9:34]{.aside}

και ειδον αυτον παντες οι κατοικουντες [λυδδαν]{.greek-omitted} [λυδδα]{.greek-added} και τον [ασσαρωνα]{.greek-omitted} [σαρωνα]{.greek-added} οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι ταβηθα η διερμηνευομενη λεγεται δορκας αυτη ην [πληρης]{.greek-omitted} [πληρις]{.greek-added} αγαθων εργων και ελεημοσυνων ων [εποιει]{.greek-omitted} [εποιη]{.greek-added}[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασα[ν]{.greek-supplied} αυτην αποθανειν λουσαντες δε αυτην εθηκαν [αυτην]{.greek-added} εν υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν προς αυτον παρακαλουντες μη [οκνησαι]{.greek-omitted} [οκνισαι]{.greek-added} διελθειν εως αυτων[9:38]{.aside}

αναστας δε πετρος συνηλθεν αυτοις ον παραγενομενον ανηγαγον εις το υπερωον και παρεστησαν αυτω πασαι αι [χειραι]{.greek-added} [χηραι]{.corr} κλαιουσαι και επιδεικνυμεναι [χιτωνας]{.greek-omitted} [χειτωνας]{.greek-added} και ιματια οσα εποιει μετ αυτων ουσα η δορκας[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος θεις τα γονατα προσηυξατο και επιστρεψας προς το σωμα ειπεν [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} αναστηθι η δε [ηνοιξεν]{.greek-omitted} [διηνοιξεν]{.greek-added} τους οφθαλμους αυτης και ιδουσα τον πετρον ανεκαθισεν[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην φωνησας δε τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωσ[τ]{.unclear}ον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι αυτον εν ιοππη παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις [ην]{.greek-omitted} εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ σπειρης της καλουμενης ιταλικης[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

ειδεν εν οραματι φανερως ωσει ωραν ενατην της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε [ατενισας]{.greek-omitted} [ατενησας]{.greek-added} αυτω και εμφοβος γενομενος ειπεν τι εστιν [κυριε]{.greek-abbr} ειπεν δε αυτω αι προσευχαι σου και [αι]{.greek-omitted} [ελεημοσυναι]{.greek-omitted} [αιλεημοσυναι]{.greek-added} σου ανεβησαν εις μν[η]{.unclear}μοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και μεταπε[μ]{.unclear}ψαι σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν οικια παρα θαλασσαν[10:6]{.aside}

ως δ[ε]{.unclear} απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην [ευσεβη]{.greek-omitted} [ευσεβει]{.greek-added} των προσκαρτερουντ[ω]{.unclear}[ν]{.greek-supplied} αυτω[10:7]{.aside}

[και]{.greek-omitted} εξηγησαμενος αυτοις απαντα απεστειλεν αυτους εις την ιοππην[10:8]{.aside}

τη δε επαυριον οδοιπορ[ουν]{.greek-supplied}των εκεινων και τη πολ[ει]{.greek-supplied} εγγιζοντων ανεβη πετρος επι το δωμα προσ[ευ]{.greek-supplied}ξασθαι περι ωραν εκτη[ν]{.unclear}[10:9]{.aside}

εγενετο δε [προσπεινος]{.greek-omitted} [προσπινος]{.greek-added} και ηθελεν γευσασθαι παρασκευαζοντων δε εκεινων επεπεσεν επ αυτον ε[κ]{.unclear}στασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεωγμενον και καταβαινον επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} σκευος τι ως οθονην μεγαλην [και]{.greek-added} τεσσαρσιν αρχαις δεδεμενον και καθιεμενον επι της γης[10:11]{.aside}

εν ω υπηρχεν παντα τα τετραποδα [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [θηρια]{.greek-omitted} και τα ερπετα [της]{.greek-added} [γης]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} [και]{.greek-added} [τα]{.greek-added} [θηρια]{.greek-added} [της]{.greek-added} [γης]{.greek-added}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστας πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος ειπεν μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον η ακαθαρτον[10:14]{.aside}

και φωνη παλιν εκ δευτερου προς αυτον α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαρισε]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και [ευθεως]{.greek-added} [ανεληφθη]{.greek-added} παλιν [ανεληφθη]{.greek-omitted} το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο πετρος τι αν ειη το οραμα ο ειδεν και ιδου οι ανδρες οι απεσταλμενοι απο του κορνηλιου διερωτησαντες την οικιαν [του]{.greek-added} σιμωνος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει σιμων ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες ζητουσιν σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους[10:20]{.aside}

καταβας δε [ο]{.greek-added} πετρος προς τους ανδρας [τους]{.greek-added} [απεσταλμενους]{.greek-added} [απο]{.greek-added} [κορνηλιου]{.greek-added} ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο [αγιου]{.greek-added} αγγελου [αγιου]{.greek-omitted} μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος [ουν]{.greek-omitted} [[δε]{.corr}]{.greek-added} αυτους [εξενισεν]{.greek-omitted} [εξενησεν]{.greek-added} τη δε επαυριον [ο]{.greek-omitted} [αναστας]{.greek-added} πετρος [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} συν αυτοις και τινες των αδελφων των απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος [ηγειρεν]{.greek-added} αυτον [ηγειρεν]{.greek-omitted} λεγων αναστηθι [καγω]{.greek-omitted} [και]{.greek-added} [γαρ]{.greek-added} [εγω]{.greek-added} αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω εισηλθεν και ευρισκει συνεληλυθοτας πολλο[υ]{.unclear}ς[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως αθεμιτον εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και αναντιρρητως ηλθον μεταπεμφθεις [υφ]{.greek-added} [υμων]{.greek-added} πυνθανομαι ουν τινι λογω μετεπεμψασθε με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης [της]{.greek-added} ημερας μεχρι ταυτης της ωρας ημην νηστευων και την ενατην ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και φησιν [κορνηλιε]{.greek-omitted} εισηκουσθη σου η προσευχη και [αι]{.greek-omitted} [ελεημοσυναι]{.greek-omitted} [αιλεημοσυναι]{.greek-added} σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και μετακαλεσαι σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος βυρσεως παρα θαλασσαν ος [παραγενομενος]{.greek-omitted} [παραγεναμενος]{.greek-added} λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιησας [παραγενομενος]{.greek-omitted} [παραγεναμενος]{.greek-added} νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα ειπεν επ αληθειας καταλαμβανομαι οτι ουκ εστιν προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι εθνει ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην δεκτος αυτω εστιν[10:35]{.aside}

τον λογον ον απεστειλεν τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος εστιν παντων [κυριος]{.greek-omitted} [εις]{.greek-added}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το βαπτισμα ο εκηρυξεν ιωαννης[10:37]{.aside}

[[ιησουν]{.greek-abbr}]{.greek-added} [τον]{.greek-added} [ιησουν]{.greek-abbr} [τον]{.unclear} απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ως εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-abbr} ον και [ανειλον]{.greek-omitted} [ανειλαν]{.greek-added} κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} ηγειρεν τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες συνεφαγομεν και συνεπιομεν αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι αυτος εστιν ο ωρισμενος υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του [[θεου]{.greek-abbr}]{.greek-added} [και]{.greek-added} [του]{.greek-added} αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη [ο]{.greek-omitted} πετρος[10:46]{.aside}

μητι το υδωρ [δυναται]{.greek-added} κωλυσαι [δυναται]{.greek-omitted} τις του [μη]{.greek-omitted} βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

προσεταξεν [τε]{.greek-omitted} [δε]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} [βαπτισθηναι]{.greek-omitted} εν τω ονοματι [του]{.greek-omitted} [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} [βαπτισθηναι]{.greek-added} τοτε ηρωτησαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε ο πετρος εξετιθετο αυτοις [καθεξης]{.greek-omitted} [καθεξοις]{.greek-added} λεγων[11:4]{.aside}

εγω ημην εν πολει ιοππη προσευχομενος και ειδον εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην [ατενισας]{.greek-omitted} [ατενησας]{.greek-added} κατενοουν και ειδον τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε [και]{.greek-added} φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαρισε]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και [ανεσπασθη]{.greek-added} παλιν [ανεσπασθη]{.greek-omitted} απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η ημην απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

ειπεν δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν [διακρινομενον]{.greek-omitted} [διακρινομενος]{.greek-added} ηλθον δε [συν]{.greek-omitted} [εμοι]{.greek-omitted} και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

απηγγειλεν [τε]{.greek-omitted} [δε]{.greek-added} ημιν πως ειδεν τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην [ανδρας]{.greek-omitted} και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις [σωθηση]{.greek-omitted} [σωθησει]{.greek-added} συ και πας ο οικος σου[11:14]{.aside}

εν δε τω [αρξασθαι]{.greek-omitted} [αρξασθε]{.greek-added} με λαλειν [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την [ισην]{.greek-omitted} [ισιν]{.greek-added} δωρεαν εδωκεν [αυτοις]{.greek-omitted} ο [θεος]{.greek-abbr} [αυτοις]{.greek-added} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω δε τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες αρα γε και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν [εδωκεν]{.greek-omitted} εις ζωην [εδωκεν]{.greek-added}[11:18]{.aside}

οι μεν ουν διασπαρεντες απο της θλιψεως της γενομενης επι στεφανω διηλθον εως φοινικης και κυπρου και αντιοχειας μηδενι λαλουντες τον λογον ει μη μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων ανδρες κυπριοι και [κυρηναιοι]{.greek-omitted} [κυριναιοι]{.greek-added} οιτινες εισελθοντες εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της εν ιεροσολυμοις περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος [παραγενομενος]{.greek-omitted} [παραγεναμενος]{.greek-added} και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει παντας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και [πληρης]{.greek-omitted} [πληρις]{.greek-added} [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

εξηλθεν δε εις ταρσον ο βαρναβας αναζητησαι σαυλον[11:25]{.aside}

και ευρων ηγαγεν αυτον εις αντιοχειαν εγενετο δε [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ενιαυτον ολον συναχθηναι [εν]{.greek-added} τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος [εσημανεν]{.greek-omitted} [εσιμανεν]{.greek-added} δια του [πνευματος]{.greek-abbr} λιμον μεγαν μελλειν εσεσθαι εφ ολην την οικουμενην οστις [και]{.greek-omitted} εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως ευπορειτο τις [ωρισαν]{.greek-omitted} [ωρησαν]{.greek-added} εκαστος [αυτων]{.greek-omitted} εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

ο και εποιησαν αποστειλαντες [προ]{.unclear}[ς]{.greek-supplied} τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον [δε]{.greek-omitted} τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της εκκλησιας[12:1]{.aside}

ανειλεν δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

και ιδων οτι αρεστον εστιν τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε αι ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος [ετηρειτο]{.greek-omitted} [ετηρειτω]{.greek-added} εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε [εμελλεν]{.greek-omitted} [ημελεν]{.greek-added} [αγειν]{.greek-added} αυτον [προαγειν]{.greek-omitted} ο ηρωδης τη νυκτι εκεινη ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και εξεπεσον αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

ειπεν τε ο αγγελος προς αυτον περιζωσαι και υποδησαι τα σανδαλια σου εποιησεν δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και ακολουθει μοι[12:8]{.aside}

και εξελθων ηκολουθει αυτω και ουκ [ηδει]{.greek-omitted} [ειδει]{.greek-added} οτι αληθες [εστιν]{.greek-omitted} [εστι]{.greek-added} το γινομενον δια του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν [εις]{.greek-omitted} [επι]{.greek-added} την πολιν ητις [αυτοματη]{.greek-omitted} [αυτοματι]{.greek-added} [ηνοιχθη]{.greek-omitted} [ηνοιγει]{.greek-added} αυτοις και εξελθοντες προηλθον ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος [γενομενος]{.greek-omitted} εν εαυτω [γενομενος]{.greek-added} ειπεν νυν οιδα αληθως οτι εξαπεστειλεν [ο]{.greek-added} [κυριος]{.greek-abbr} τον αγγελον αυτου και [εξειλετο]{.greek-omitted} [εξειλατο]{.greek-added} με εκ χειρος ηρωδου και πασης της προσδοκιας του λαου των ιουδαιων[12:11]{.aside}

συνιδων [τε]{.greek-omitted} [δε]{.greek-added} [ο]{.greek-added} [πετρος]{.greek-added} ηλθεν επι την οικιαν [της]{.greek-added} μαριας της [μητρος]{.greek-abbr} ιωαννου του επικαλουμενου μαρκου ου ησαν ικανοι συνηθροισμενοι και προσευχομενοι[12:12]{.aside}

κρουσαντος δε [του]{.greek-omitted} [αυτου]{.greek-added} [πετρου]{.greek-omitted} την θυραν του πυλωνος προσηλθεν παιδισκη υπακουσαι ονοματι ροδη[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ ηνοιξεν τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον μαινη η δε [διισχυριζετο]{.greek-omitted} [διϊσχυριζετο]{.greek-added} ουτως εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος επεμενεν κρουων ανοιξαντες δε [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον και εξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις τη χειρι σιγαν διηγησατο [αυτοις]{.greek-omitted} πως ο [κυριος]{.greek-abbr} [εξηγαγεν]{.greek-added} αυτον [εξηγαγεν]{.greek-omitted} εκ της φυλακης ειπεν [δε]{.greek-omitted} [τε]{.greek-added} απαγγειλατε ιακωβω και τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις [την]{.greek-omitted} καισαρειαν διετριβεν[12:19]{.aside}

ην δε [ο]{.greek-omitted} [ηρωδης]{.greek-omitted} [θυμομαχων]{.greek-omitted} [θυμωμαχων]{.greek-added} τυριοις και [σιδωνιοις]{.greek-omitted} [σιδονιοις]{.greek-added} ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι αυτων την [χωραν]{.greek-omitted} [πολιν]{.greek-added} απο της βασιλικης[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα βασιλικην και καθισας επι του βηματος [εδημηγορει]{.greek-omitted} [εδημιγορει]{.greek-added} προς αυτους[12:21]{.aside}

ο δε δημος επεφωνει [[θεου]{.greek-abbr}]{.greek-added} φωνη [θεου]{.greek-omitted} και ουκ ανθρωπου[12:22]{.aside}

παραχρημα δε επαταξεν αυτον αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ εδωκεν [δοξαν]{.greek-omitted} [αινον]{.greek-added} τω [θεω]{.greek-abbr} και γενομενος σκωληκοβρωτος εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και επληθυνετο[12:24]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} πληρωσαντες την διακονιαν συμπαραλαβοντες και ιωαννην τον [επικληθεντα]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε [τινες]{.greek-omitted} εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος ο [κυρηναιος]{.greek-omitted} [κυριναιος]{.greek-added} μαναην τε ηρωδου του τετραρχου συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον [αφορισατε]{.greek-omitted} [αφορησατε]{.greek-added} δη μοι τον βαρναβαν και τον σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες τας χειρας αυτοις απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεντες υπο του [αγιου]{.greek-added} [πνευματος]{.greek-abbr} [του]{.greek-omitted} [αγιου]{.greek-omitted} κατηλθον [εις]{.greek-omitted} [ει]{.greek-added} [την]{.greek-omitted} [σελευκειαν]{.greek-omitted} [σελευκιαν]{.greek-added} εκειθεν [δε]{.greek-omitted} [τε]{.greek-added} απεπλευσαν εις [την]{.greek-omitted} κυπρον[13:4]{.aside}

και γενομενοι εν [σαλαμινι]{.greek-omitted} [σαλαμινη]{.greek-added} κατηγγελλον τον λογον του [θεου]{.greek-abbr} εν ταις συναγωγαις των ιουδαιων ειχον δε και ιωαννην υπηρετην[13:5]{.aside}

διελθοντες δε [ολην]{.greek-added} την νησον αχρι παφου ευρον [ανδρα]{.greek-added} τινα μαγον ψευδοπροφητην [ιουδαιον]{.greek-omitted} [ιουδαιων]{.greek-added} ω [ονομα]{.greek-omitted} [ονοματι]{.greek-added} [βαριησους]{.greek-omitted} [βαριησουν]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω παυλω ανδρι συνετω ουτος προσκαλεσαμενος [βαρναβαν]{.greek-omitted} [βαρναβα]{.greek-added} και [σαυλον]{.greek-omitted} [σαυλω]{.greek-added} επεζητησεν ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μαγος ουτως γαρ μεθερμηνευεται το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου [και]{.greek-omitted} [ατενισας]{.greek-omitted} [ατενησας]{.greek-added} εις αυτον[13:9]{.aside}

ειπεν ω [πληρης]{.greek-omitted} [πληρεις]{.greek-added} παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου [παυση]{.greek-omitted} [παυει]{.greek-added} διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον αχρι καιρου παραχρημα δε επεπεσεν επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το [γεγονος]{.greek-omitted} [γεγονως]{.greek-added} επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε αποχωρησας απ αυτων υπεστρεψεν εις ιεροσολυμα[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει εστιν [λογος]{.greek-omitted} εν υμιν [λογος]{.greek-added} παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη [αιγυπτω]{.greek-omitted} [αιγυπτου]{.greek-added} και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον ετροποφορησεν αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη επτα εν γη χανααν κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

και μετα ταυτα ως [ετεσιν]{.greek-omitted} [ετεσι]{.greek-added} τετρακοσιοις και πεντηκοντα [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ υιον [κις]{.greek-omitted} [κει]{.greek-added} ανδρα εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμειν]{.greek-added} ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα [ω]{.greek-omitted} [ων]{.greek-added} και ειπεν μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν ηγαγεν τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-abbr}[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας [παντι]{.greek-added} τω [λαω]{.greek-added} [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου [ο]{.greek-omitted} ιωαννης τον δρομον ελεγεν τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} [υμιν]{.greek-omitted} [ημιν]{.greek-added} ο λογος [ο]{.greek-added} της [σωτηριας]{.greek-abbr} ταυτης [απεσταλη]{.greek-omitted} [εξαπεσταλη]{.greek-added}[13:26]{.aside}

οι γαρ κατοικουντες [εν]{.greek-omitted} [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον αγνοησαντες και τας φωνας των προφητων τας κατα παν σαββατον αναγινωσκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις μνημειον[13:29]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [εισιν]{.greek-omitted} [εισι]{.greek-added} [νυν]{.greek-added} μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκεν]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω [γεγραπται]{.greek-added} τω δευτερω [γεγραπται]{.greek-omitted} υιος μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον εκ νεκρω[ν]{.unclear} μηκετι μελλοντα υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και ειδεν διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ [ειδεν]{.greek-omitted} [οιδεν]{.greek-added} διαφθοραν[13:37]{.aside}

γνωστον [εστω]{.greek-added} ουν [εστω]{.greek-omitted} υμιν ανδρες αδελφοι οτι δια [τουτου]{.greek-omitted} [τουτο]{.greek-added} [υμιν]{.greek-omitted} αφεσις αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [νομω]{.greek-added} [μωυσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται και θαυμασατε και αφανισθητε οτι εργον [εργαζομαι]{.greek-added} εγω [εργαζομαι]{.greek-omitted} εν ταις ημεραις υμων ο ου μη πιστευσητε εαν τις [εκδιηγηται]{.greek-omitted} [εκδιηγησεται]{.greek-added} υμιν[13:41]{.aside}

εξιοντων δε [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [ιουδαιων]{.greek-omitted} παρεκαλουν [τα]{.greek-omitted} [εθνη]{.greek-omitted} εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

λυθεισης δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και τω βαρναβα οιτινες προσλαλουντες [αυτοις]{.greek-added} επειθον αυτους [επιμενειν]{.greek-omitted} [προσμενειν]{.greek-added} τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω [τε]{.greek-omitted} [δε]{.greek-added} [ερχομενω]{.greek-omitted} [εχομενω]{.greek-added} σαββατω σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλου [λεγομενοις]{.greek-omitted} [λαλουμενοις]{.greek-added} [αντιλεγοντες]{.greek-omitted} [και]{.greek-omitted} βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος και ο βαρναβας ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} [επειδη]{.greek-omitted} [επει]{.greek-added} δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

ουτως γαρ εντεταλται ημιν ο [κυριος]{.greek-abbr} [τεθεικα]{.greek-omitted} [τεθηκα]{.greek-added} σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον [τον]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added} [και]{.greek-added} τον λογον του [κυριου]{.greek-abbr} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-abbr} [δι]{.greek-omitted} [καθ]{.greek-added} ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας [και]{.greek-omitted} τας ευσχημονας και τους πρωτους της πολεως και επηγειραν διωγμον επι τον παυλον και τον βαρναβαν και εξεβαλον [αυτους]{.greek-omitted} [αυτον]{.greek-added} απο των οριων αυτων[13:50]{.aside}

οι δε εκτιναξαμενοι τον κονιορτον των ποδων αυτων επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι [δε]{.greek-omitted} [τε]{.greek-added} μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το [αυτο]{.greek-omitted} [αυτω]{.greek-added} εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων τε και ελληνων πολυ πληθος[14:1]{.aside}

οι δε [απειθουντες]{.greek-omitted} [απειθησαντες]{.greek-added} ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου διδοντι σημεια και τερατα γινεσθαι δια των χειρω[ν]{.greek-supplied} αυτων[14:3]{.aside}

εσχισθη δε το πλ[η]{.unclear}θος της πολεως και οι με[ν]{.unclear} ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και [λιθοβολησαι]{.greek-omitted} [λιθωβολησαι]{.greek-added} αυτους[14:5]{.aside}

[συνιδοντες]{.greek-omitted} [συνιδοτες]{.greek-added} κατεφυγον [οι]{.greek-added} [αποστολοι]{.greek-added} εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει [ευαγγελιζομενοι]{.greek-added} ησαν [ευαγγελιζομενοι]{.greek-omitted}[14:7]{.aside}

και τις ανηρ ε[ν]{.greek-supplied} λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου [υπαρχων]{.greek-omitted} ο[ς]{.greek-supplied} ουδεποτε περιπεπατηκει[14:8]{.aside}

ουτος ηκουσεν του παυλου λαλουντος ος ατενισας αυτω και ιδων οτι πιστιν εχει του σωθηναι[14:9]{.aside}

ειπεν μεγαλη τη φωνη αναστηθι επι τους ποδας σου [ορθως]{.greek-omitted} [ορθος]{.greek-added} και [ηλλετο]{.greek-omitted} [ηλλατο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν [ο]{.greek-omitted} παυλος επηραν την φωνην αυτων [λυκαονιστι]{.greek-omitted} [λυκαονιστη]{.greek-added} λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν δια τον δε παυλον ερμην επειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο δε ιερευς του διος του οντος προ της πολεως [αυτων]{.greek-omitted} ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις ηθελεν θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων εισεπηδησαν εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε και ημεις [ομοιοπαθεις]{.greek-omitted} [ομοιωπαθεις]{.greek-added} εσμεν υμιν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο τουτων των ματαιων επιστρεφειν επι τον [θεον]{.greek-abbr} τον ζωντα ος [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις [παρωχημεναις]{.greek-omitted} [παροχημεναις]{.greek-added} γενεαις [ειασεν]{.greek-omitted} [ειασε]{.greek-added} παντα τα εθνη πορευεσθαι ταις οδοις αυτων[14:16]{.aside}

[καιτοιγε]{.greek-omitted} [καιτοι]{.greek-added} [γε]{.greek-added} ουκ αμαρτυρον εαυτον αφηκεν αγαθοποιων [ουρανοθεν]{.greek-abbr} υμιν υετους διδους και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας ημων[14:17]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν αυτοις [αλλα]{.greek-added} [πορευεσθαι]{.greek-added} [εκαστον]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ιδια]{.greek-added}[14:18]{.aside}

[διατριβοντων]{.greek-added} [δε]{.greek-added} [αυτων]{.greek-added} [και]{.greek-added} [διδασκοντων]{.greek-added} επηλθον [δε]{.greek-omitted} απο αντιοχειας και ικονιου ιουδαιοι και [πεισαντες]{.greek-omitted} [διαλεγομενων]{.greek-added} [αυτων]{.greek-added} [παρρησια]{.greek-added} [ανεπησαν]{.greek-added} τους οχλους [αποστηναι]{.greek-added} [αυτων]{.greek-added} [λεγοντες]{.greek-added} [οτι]{.greek-added} [ουδεν]{.greek-added} [αληθες]{.greek-added} [λεγουσιν]{.greek-added} [αλλα]{.greek-added} [παντα]{.greek-added} [ψευδονται]{.greek-added} και λιθασαντες τον παυλον εσυρον εξω της πολεως [νομισαντες]{.greek-omitted} [νομησαντες]{.greek-added} αυτον τεθναναι[14:19]{.aside}

κυκλωσαντων δε [αυτον]{.greek-omitted} των μαθητων [αυτον]{.greek-added} αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν [ο]{.greek-added} [παυλος]{.greek-added} συν τω βαρναβα εις δερβην[14:20]{.aside}

ευαγγελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις [την]{.greek-omitted} λυστραν και [εις]{.greek-added} ικονιον και αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει [ημας]{.greek-omitted} [υμας]{.greek-added} εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις [πρεσβυτερους]{.greek-omitted} κατ εκκλησιαν [πρεσβυτερους]{.greek-added} προσευξαμενοι μετα νηστειων παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον πεπιστευκεισαν[14:23]{.aside}

κα[ι]{.greek-supplied} διελθοντες την πισιδιαν ηλθον εις παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} κατεβησαν εις ατταλειαν[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν [παραδεδομενοι]{.greek-omitted} [παραδιδομενοι]{.greek-added} τη χαριτι τ[ου]{.unclear} [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν [ανηγγειλαν]{.greek-omitted} [ανηγγελλον]{.greek-added} οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} [θυραν]{.greek-omitted} [θυρα]{.greek-added} πιστεως[14:27]{.aside}

διετριβον δε [εκει]{.greek-omitted} χρονον ουκ [ο]{.unclear}λιγον συν τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι [ε]{.unclear}αν μη [περιτεμνησθε]{.greek-omitted} [περιτεμνεσθε]{.greek-added} τω [εθει]{.greek-omitted} [εθη]{.greek-added} μωυσεως ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης [ουν]{.greek-omitted} [δε]{.greek-added} στασεως και ζητησεως ουκ ολιγης τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την φοινικην και σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις αδελφοις[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} [απεδεχθησαν]{.greek-omitted} [παρεδεχθησαν]{.greek-added} υπο της εκκλησιας και των αποστολων και των πρεσβυτερων ανηγγειλαν τε οσα ο [θεος]{.greek-abbr} εποιησεν μετ αυτων[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων πεπιστευκοτες λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον μωυσεως[15:5]{.aside}

συνηχθησαν δε οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε [συζητησεως]{.greek-omitted} [ζητησεως]{.greek-added} γενομενης αναστας πετρος ειπεν προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων [ο]{.greek-omitted} [θεος]{.greek-omitted} εν ημι[ν]{.unclear} εξελεξατο [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} δια του στοματος μου ακουσαι τα εθνη τον λογον του [[κυριου]{.greek-abbr}]{.greek-added} [και]{.greek-added} [του]{.greek-added} ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και ουδεν διεκρινεν μεταξυ ημων τε και αυτων τη πιστει [καθαρισας]{.greek-omitted} [καθαρησας]{.greek-added} τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} επιθειναι ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

εσιγησεν δε [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δι αυτων[15:12]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον επι τω ονοματι αυτου[15:14]{.aside}

και [τουτω]{.greek-omitted} [τουτο]{.greek-added} συμφωνουσιν οι λογοι των προφητων [καθως]{.greek-omitted} [ως]{.greek-added} γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα [κατεσκαμμενα]{.greek-omitted} [κατεστραμμενα]{.greek-added} αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ον[ο]{.unclear}μα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων ταυτα παντα[15:17]{.aside}

γνωστα απ αιωνος εστιν τω [θεω]{.greek-abbr} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} επιστειλαι αυτοις του απεχεσθαι απο των αλισγηματων των ειδωλων και της πορνειας και του πνικτου και του αιματος[15:20]{.aside}

μωυσης γαρ εκ γενεων αρχαιων κατα πολιν τους κηρυσσοντας αυτον εχει εν ταις συναγωγαις κατα παν σαββατον αναγινωσκομενος[15:21]{.aside}

τοτε [εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν [τω]{.greek-added} παυλω και [τω]{.greek-added} βαρναβα ιουδαν τον επικαλουμενον [βαρσαββαν]{.greek-omitted} [βαρσαβαν]{.greek-added} και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων εξελθοντες εταραξαν υμας λογοις ανασκευαζοντες τας ψυχας υμων λεγοντες περιτεμνεσθαι και τηρειν τον νομον οις ου διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον εκλεξαμενους ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα και παυλω[15:25]{.aside}

ανθρωποις [παραδεδοκοσι]{.greek-added} [παραδεδωκοσιν]{.greek-omitted} [[παραδεδωκοσι]{.corr}]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

[εδοξεν]{.greek-omitted} [εδωξε]{.greek-added} γαρ τω [[πνευματι]{.greek-abbr}]{.greek-added} [τω]{.greek-added} αγιω [πνευματι]{.greek-omitted} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην [των]{.greek-omitted} [τουτων]{.greek-added} επαναγκες [τουτων]{.greek-omitted}[15:28]{.aside}

απεχεσθαι [ειδωλοθυτων]{.greek-omitted} [ειδωλωθυτων]{.greek-added} και αιματος και πνικτου και πορνειας εξ ων διατηρουντες εαυτους ευ [πραξετε]{.greek-omitted} [πραξατε]{.greek-added} ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες [ηλθον]{.greek-omitted} [κατηλθον]{.greek-added} εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

[αναγνοντες]{.greek-omitted} [αναγνωντες]{.greek-added} δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης απο των αδελφων προς τους αποστολους[15:33]{.aside}

[εδοξε]{.greek-added} [τω]{.greek-added} [σιλα]{.greek-added} [επιμειναι]{.greek-added} [αυτου]{.greek-added}[15:34]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας ειπεν [παυλος]{.greek-omitted} προς βαρναβαν [ο]{.greek-added} [παυλος]{.greek-added} επιστρεψαντες [δη]{.greek-omitted} [δει]{.greek-added} επισκεψωμεθα τους αδελφους ημων κατα πασαν πολιν εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως εχουσιν[15:36]{.aside}

βαρναβας δε εβουλευσατο συμπαραλαβειν [τον]{.greek-omitted} [και]{.greek-added} ιωαννην τον [καλουμενον]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη συμπαραλαβειν τουτον[15:38]{.aside}

εγενετο [ουν]{.greek-omitted} [δε]{.greek-added} παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων τον τε βαρναβαν παραλαβοντ[α]{.greek-supplied} τον μαρκον εκπλευσα[ι]{.unclear} εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν εξηλθεν παραδοθεις τη χαριτι του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και κιλικιαν επιστηριζων τας εκκλησιας[15:41]{.aside}

### Chapter 16

κατηντησεν δε εις δερβην και λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος υιος γυναικος [τινος]{.greek-omitted} ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τοποις εκεινοις [ηδεισαν]{.greek-omitted} [ηδησαν]{.greek-added} γαρ απαντες [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} οτι ελλην [ο]{.greek-added} [[πατηρ]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις παρεδιδουν αυτοις φυλασσειν τα δογματα τα [κεκριμενα]{.greek-omitted} [κεκρυμμενα]{.greek-added} υπο των αποστολων και [των]{.greek-omitted} πρεσβυτερων των εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και επερισσευον τω αριθμω καθ ημεραν[16:5]{.aside}

[διελθοντες]{.greek-omitted} [διηλθον]{.greek-added} δε την φρυγιαν και [την]{.greek-omitted} γαλατικην χω[ρ]{.greek-supplied}αν κωλυθεντες υπο του [α]{.unclear}γιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες [δε]{.greek-added} κατα την μυσιαν επειραζον [κατα]{.greek-omitted} [εις]{.greek-added} την [βιθυνιαν]{.greek-omitted} [βηθυνιαν]{.greek-added} [πορευεσθαι]{.greek-omitted} [πορευθηναι]{.greek-added} και ουκ ειασεν αυτους το [πνευμα]{.greek-abbr}[16:7]{.aside}

παρελθοντες δε την μυσιαν κατεβησαν εις τρωαδα[16:8]{.aside}

και οραμα δια της νυκτος [ωφθη]{.greek-omitted} τω παυλω [ωφθη]{.greek-added} ανηρ [μακεδων]{.greek-added} τις ην [μακεδων]{.greek-omitted} εστως παρακαλων αυτον και λεγων διαβας εις [μακεδονιαν]{.greek-omitted} [μακεδωνιαν]{.greek-added} βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα ειδεν ευθεως εζητησαμεν [εξελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις [την]{.greek-omitted} [μακεδονιαν]{.greek-omitted} [μακεδωνιαν]{.greek-added} συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-omitted} [[θεος]{.greek-abbr}]{.greek-added} ευαγγελισασθαι [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[16:10]{.aside}

αναχθεντες [ουν]{.greek-omitted} [δε]{.greek-added} απο [της]{.greek-omitted} τρωαδος ευθυδρομησαμεν εις σαμοθρακην τη [τε]{.greek-omitted} [δε]{.greek-added} επιουση εις νεαπολιν[16:11]{.aside}

[εκειθεν]{.greek-omitted} [κακειθεν]{.greek-added} [τε]{.greek-omitted} εις φιλιππους ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη της μεριδος [της]{.greek-omitted} [μακεδονιας]{.greek-omitted} [μακεδωνιας]{.greek-added} πολις κολωνεια ημεν δε εν [αυτη]{.greek-omitted} [ταυτη]{.greek-added} τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη [τε]{.greek-omitted} [δε]{.greek-added} ημερα των σαββατων εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο [προσευχη]{.greek-omitted} [προσευχην]{.greek-added} ειναι και [καθισαντες]{.greek-omitted} [καθησαντες]{.greek-added} ελαλουμεν ταις συνελθουσαις γυναιξιν[16:13]{.aside}

και τις γυνη ονοματι λυδια [πορφυροπωλις]{.greek-omitted} [πορφυροπολις]{.greek-added} πολεως [θυατειρων]{.greek-omitted} [θυατηρων]{.greek-added} σεβομενη τον [θεον]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουσεν]{.greek-added} ης ο [κυριος]{.greek-abbr} διηνοιξεν την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης παρεκαλεσεν λεγουσα ει κεκρικατε με πιστην τω [κυριω]{.greek-abbr} ειναι εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην παιδισκην τινα [εχουσαν]{.greek-omitted} [εχουσα]{.greek-added} [πνευμα]{.greek-abbr} [πυθωνος]{.greek-omitted} [πυθωνα]{.greek-added} [απαντησαι]{.greek-omitted} [υπαντησαι]{.greek-added} ημιν ητις εργασιαν πολλην [παρειχεν]{.greek-omitted} [παρειχε]{.greek-added} τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και ημιν [εκραζεν]{.greek-omitted} [εκραζε]{.greek-added} λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον [σωτηριας]{.greek-abbr}[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} ειπεν παραγγελλω σοι εν [τω]{.greek-omitted} ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της εργασιας αυτων επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και καταγγελλουσιν εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις ουσιν[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι περιρρηξαντες αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην ειληφως εβαλεν αυτους εις την εσωτεραν φυλακην και τους ποδας αυτων [ησφαλισατο]{.greek-omitted} [ησφαλησατο]{.greek-added} εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [επηκροωντο]{.greek-omitted} [επικροωντο]{.greek-added} δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του [δεσμωτηριου]{.greek-omitted} [δεσμοτηριου]{.greek-added} [ανεωχθησαν]{.greek-omitted} [ηνεωχθησαν]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν εμελλεν [εαυτον]{.greek-omitted} [αυτον]{.greek-added} αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

εφωνησεν δε φωνη μεγαλη ο παυλος λεγων μηδεν [πραξης]{.greek-omitted} [πραξεις]{.greek-added} σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα εισεπηδησεν και εντρομος γενομενος [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και [σωθηση]{.greek-omitted} [σωθησει]{.greek-added} συ και [πας]{.greek-added} ο οικος σου[16:31]{.aside}

και ελαλησαν αυτω τον λογον του [κυριου]{.greek-abbr} [και]{.greek-omitted} [συν]{.greek-added} πασιν τοις εν τη οικια αυτου[16:32]{.aside}

και [παραβων]{.greek-added} [παραλαβων]{.corr} αυτους εν εκεινη τη ωρα της νυκτος ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου παντες παραχρημα[16:33]{.aside}

αναγαγων [τε]{.greek-omitted} [δε]{.greek-added} αυτους εις τον οικον αυτου παρεθηκεν τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασαντο]{.greek-added} πανοικι [πεπιστευκως]{.greek-omitted} [πεπιστευκοτες]{.greek-added} τω [θεω]{.greek-omitted} [[κυριω]{.greek-abbr}]{.greek-added}[16:34]{.aside}

ημερας δε γενομενης [απεστειλαν]{.greek-omitted} [επεστειλαν]{.greek-added} οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

απηγγειλεν δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας [εκβαλλουσιν]{.greek-omitted} [εκβαλουσιν]{.greek-added} ου γαρ αλλα ελθοντες αυτοι [ημας]{.greek-added} εξαγαγετωσαν[16:37]{.aside}

[ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} δε τοις στρατηγοις οι ραβδουχοι τα ρηματα ταυτα [και]{.greek-omitted} εφοβηθησαν [δε]{.greek-added} ακουσαντες οτι ρωμαιοι εισιν[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και εξαγαγοντες ηρωτων εξελθειν της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες τους αδελφους παρεκαλεσαν αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και απολλωνιαν ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το ειωθος τω παυλω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν ο [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων επεισθησαν και προσεκληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων πολυ πληθος γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

[προσλαβομενοι]{.greek-omitted} [ζηλωσαντες]{.greek-added} δε οι ιουδαιοι [οι]{.greek-omitted} [απειθουντες]{.greek-omitted} [και]{.greek-added} [προσλαβομενοι]{.greek-added} των αγοραιων τινας ανδρας πονηρους και οχλοποιησαντες εθορυβουν την πολιν [και]{.greek-added} επισταντες [τε]{.greek-omitted} τη οικια [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} εζητουν αυτους αγαγειν εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τον [ιασονα]{.greek-omitted} [ιασωνα]{.greek-added} και τινας αδελφους [επι]{.greek-omitted} [προς]{.greek-added} τους πολιταρχας βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι και ενθαδε [παρεισιν]{.greek-omitted} [παρησιν]{.greek-added}[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος πρασσουσιν βασιλεα λεγοντες ετερον ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον οχλον και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια της νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις βεροιαν οιτινες παραγενομενοι εις την συναγωγην [απηεσαν]{.greek-omitted} των ιουδαιων [απηεσαν]{.greek-added}[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας [το]{.greek-omitted} καθ ημεραν ανακρινοντες τας γραφας ει εχοι ταυτα ουτως[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της [θεσσαλονικης]{.greek-omitted} [θεσαλονικης]{.greek-added} ιουδαιοι οτι και εν τη βεροια [κατηγγελη]{.greek-omitted} [κατηγγελλει]{.greek-added} υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες [και]{.greek-added} [ταρασσοντες]{.greek-added} τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι ως επι την θαλασσαν [υπεμενον]{.greek-omitted} [δε]{.greek-omitted} [επεμειναν]{.greek-added} [τε]{.greek-added} ο [τε]{.greek-omitted} σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε καθιστωντες τον παυλον ηγαγον [αυτον]{.greek-omitted} εως αθηνων και λαβοντες εντολην προς [τον]{.greek-omitted} σιλαν και τιμοθεον ινα ως ταχιστα [ελθωσιν]{.greek-omitted} [ελθωσι]{.greek-added} προς αυτον [εξηεσαν]{.greek-omitted} [εξιεσαν]{.greek-added}[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου [παρωξυνετο]{.greek-omitted} [παροξυνετο]{.greek-added} το [πνευμα]{.greek-abbr} αυτου εν αυτω θεωρουντι [κατειδωλον]{.greek-omitted} [κατειδωλων]{.greek-added} ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις σεβομενοις και εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε και των επικουρειων και των [στοικων]{.greek-omitted} [στωικων]{.greek-added} φιλοσοφων συνεβαλλον αυτω και τινες ελεγον τι αν θελοι ο σπερμολογος ουτος λεγει[ν]{.unclear} οι δε ξενων δαιμονιων δοκει καταγγελευς ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο [αυτοις]{.greek-added}[17:18]{.aside}

επιλαβομενοι [τε]{.greek-omitted} [δε]{.greek-added} αυτου επι τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι τι αν θελοι ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added} η λεγειν τι και ακουειν καινοτερον[17:21]{.aside}

σταθεις δε [ο]{.greek-omitted} παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως δεισιδαιμονεστερους υμας θεωρω[17:22]{.aside}

διερχομενος [γαρ]{.greek-omitted} [δε]{.greek-added} και αναθεωρων τα σεβασματα υμων ευρον και βωμον εν ω [επεγεγραπτο]{.greek-omitted} [επεγεγραπτω]{.greek-added} αγνωστω [θεω]{.greek-abbr} ον [ουν]{.greek-omitted} αγνοουντες ευσεβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [κυριος]{.greek-abbr} υπαρχων ουκ εν χειροποιητοις ναοις [κατοικει]{.greek-omitted} [κατοικειν]{.greek-added}[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} θεραπευεται προσδεομενος τινος αυτος διδους [πασιν]{.greek-omitted} [πασι]{.greek-added} ζωην και πνοην κατα παντα[17:25]{.aside}

εποιησεν τε εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ει αρα γε [ψηλαφησειαν]{.greek-omitted} [ψηλαφησαιεν]{.greek-added} αυτον και ευροιεν και γε ου μακραν απο ενος εκαστου ημων υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ [υμας]{.greek-omitted} [ημας]{.greek-added} ποιητων ειρηκασιν του γαρ και [γενους]{.greek-added} [γενος]{.corr} εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν [χρυσω]{.greek-omitted} [χρυσιω]{.greek-added} η αργυρω η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} [πασιν]{.greek-omitted} [πασι]{.greek-added} πανταχου μετανοειν[17:30]{.aside}

διοτι εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω [ωρισεν]{.greek-omitted} [ωρισε]{.greek-added} πιστιν παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον [ακουσομεθα]{.greek-omitted} [ακουσωμεθα]{.greek-added} σου παλιν περι τουτου[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα [ιουδαιον]{.greek-omitted} [ιουδαιων]{.greek-added} ονοματι ακυλαν ποντικον τω γενει προσφατως εληλυθοτα απο της ιταλιας και πρισκιλλαν [την]{.greek-added} γυναικα αυτου δια το τεταχεναι κλαυδιον χωριζεσθαι παντας τους ιουδαιους [εκ]{.greek-omitted} [απο]{.greek-added} της ρωμης προσηλθεν αυτοις[18:2]{.aside}

και δια το ομοτεχνον ειναι [εμενεν]{.greek-omitted} [εμενε]{.greek-added} παρ αυτοις και ειργαζετο ησαν γαρ σκηνοποιοι την τεχνην[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον [επειθεν]{.greek-omitted} [επειθε]{.greek-added} τε ιουδαιους [τε]{.greek-added} και ελληνας[18:4]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και ο τιμοθεος συνειχετο τω [πνευματι]{.greek-abbr} ο παυλος διαμαρτ[υ]{.greek-supplied}ρομενος τοις ιουδαιοι[ς]{.unclear} τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλ[α]{.greek-supplied}σφημουντων εκτιναξαμενος τα ιματια [αυτου]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας εκειθεν [ηλθεν]{.greek-omitted} [εισηλθεν]{.greek-added} εις οικιαν τινος ονοματι ιουστου σεβομενου τον [θεον]{.greek-abbr} ου [ην]{.greek-added} η οικια [ην]{.greek-omitted} συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος επιστευσεν τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων ακουοντες επιστευον και εβαπτιζοντο[18:8]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} [εν]{.greek-added} [νυκτι]{.greek-added} δι οραματος [εν]{.greek-omitted} [νυκτι]{.greek-omitted} τω παυλω μη φοβου αλλα [λαλη]{.greek-added} [λαλει]{.corr} και μη [σιωπησης]{.greek-omitted} [σιοπησης]{.greek-added}[18:9]{.aside}

διοτι εγω ειμι μετα σου και ουδεις επιθησεται [σε]{.greek-added} [σ[οι]{.unclear}]{.corr} του κακωσαι σε διοτι λαος [εστιν]{.greek-omitted} [εστι]{.greek-added} μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

[εκαθισεν]{.greek-omitted} [εκαθισε]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} ενιαυτον και μηνας εξ διδασκων εν αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

[γαλλιωνος]{.greek-omitted} [γαλλιονος]{.greek-added} δε [ανθυπατευοντος]{.greek-omitted} [ανθυπατου]{.greek-added} [οντος]{.greek-added} της αχαιας κατεπεστησαν ομοθυμαδον οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον [αναπειθει]{.greek-added} ουτος [αναπειθει]{.greek-omitted} τους [ανθρωπους]{.greek-abbr} [σεβεσθε]{.greek-added} [σεβεσθαι]{.corr} τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο [γαλλιων]{.greek-omitted} [γαλλιον]{.greek-added} προς τους ιουδαιους ει μεν ουν ην αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν [ηνεσχομην]{.greek-omitted} [ανεσχομην]{.greek-added} υμων[18:14]{.aside}

ει δε ζητημα εστιν περι λογου και ονοματων και νομου του καθ υμας οψεσθε αυτοι κριτης γαρ [τουτων]{.greek-added} εγω [τουτων]{.greek-omitted} ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι δε παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω [γαλλιωνι]{.greek-omitted} [γαλλιονι]{.greek-added} [ελλεν]{.greek-added} [εμελλεν]{.corr}[18:17]{.aside}

ο δε παυλος ετι [προσμεινας]{.greek-omitted} [προσμηνας]{.greek-added} ημερας ικανας τοις αδελφοις αποταξαμενος εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος την κεφαλην εν [κεγχρεαις]{.greek-omitted} [κεχρεαις]{.greek-added} ειχεν γαρ ευχην[18:18]{.aside}

κατηντησεν δε εις εφεσον [και]{.greek-omitted} [εκεινους]{.greek-omitted} [κακεινους]{.greek-added} [κατελιπεν]{.greek-omitted} [κατελειπεν]{.greek-added} [αυτου]{.greek-omitted} [εκει]{.greek-added} αυτος δε εισελθων εις την συναγωγην διελεχθη τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε αυτων επι πλειονα χρονον μειναι παρ αυτοις ουκ [επενευσεν]{.greek-omitted} [επνευσεν]{.greek-added}[18:20]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} απεταξατο αυτοις ειπων δει με παντως την εορτην την ερχομενην ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

και κατελθων [ο]{.greek-added} [παυλος]{.greek-added} εις καισαρειαν αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα εξηλθεν διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος [κατηνσεν]{.greek-added} [κατηντησεν]{.corr} εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και [ζεων]{.greek-omitted} [ζεον]{.greek-added} τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-omitted} [[χριστου]{.greek-abbr}]{.greek-added} επισταμενος μ[ο]{.unclear}νον το βαπτισμα ιωαν[νου]{.unclear}[18:25]{.aside}

ουτος τε ηρξατο παρρησ[ι]{.greek-supplied}αζεσθαι εν τη συναγωγη ακουσαντες δε αυτου ακ[υ]{.unclear}λας και πρισκιλλα προσ[ε]{.unclear}λαβοντο αυτον και ακριβεστερον αυτω εξεθεντο την [οδον]{.greek-added} του [θεου]{.greek-abbr} [οδον]{.greek-omitted}[18:26]{.aside}

[βουλομενου]{.greek-omitted} [καλουμενου]{.greek-added} δε αυτου διελθειν εις την αχαιαν προτρεψαμενοι οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος [συνεβαλετο]{.greek-omitted} [συνεβαλε]{.greek-added} πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπιστευκοσι]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω τον απολλω ειναι εν κορινθω [παυλον]{.greek-omitted} [παυλω]{.greek-added} διελθοντα [αυτω]{.greek-added} τα [ανω]{.greek-added} [ανωτερικα]{.greek-omitted} [τερικα]{.greek-added} μερη [ελθειν]{.greek-omitted} [κατελθειν]{.greek-added} εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

ειπεν προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε ειπον προς αυτον αλλ [ουδε]{.greek-omitted} [ουδ]{.greek-added} ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

[ο]{.greek-added} [δε]{.greek-added} ειπεν [τε]{.greek-omitted} προς αυτους εις τι ουν εβαπτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

ειπεν δε παυλος ιωαννης μεν εβαπτισεν βαπτισμα μετανοιας τω λαω λεγων εις τον ερχομενον μετ αυτον ινα [πιστευσωσιν]{.greek-omitted} [πιστευσωσι]{.greek-added} τουτ εστιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου [τας]{.greek-omitted} χειρας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και [προεφητευον]{.greek-omitted} [επροφητευον]{.greek-added}[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει δεκαδυο[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους αποστας απ αυτων [αφωρισεν]{.greek-omitted} [αφωρισε]{.greek-added} τους μαθητας καθ ημεραν διαλεγομενος εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι ετη δυο ωστε παντας τους κατοικουντας την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας [εποιει]{.greek-omitted} ο [θεος]{.greek-abbr} [εποιει]{.greek-added} δια των χειρων παυλου[19:11]{.aside}

ωστε και επι τους ασθενουντας επιφερεσθαι απο του χρωτος αυτου σουδαρια η σιμικινθια και απαλλασσεσθαι απ αυτων τας νοσους τα τε [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} τα πονηρα εξερχεσθαι απ αυτων[19:12]{.aside}

επεχειρησαν δε τινες [απο]{.greek-omitted} [και]{.greek-added} των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους εχοντας τα πνευματα τα πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-omitted} λεγοντες [ορκιζομεν]{.greek-omitted} [ορκιζωμεν]{.greek-added} υμας τον [ιησουν]{.greek-abbr} ον ο παυλος κηρυσσει[19:13]{.aside}

ησαν δε τινες υιοι σκευα ιουδαιου αρχιερεως επτα οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε το [πνευμα]{.greek-abbr} το πονηρον ειπεν [αυτοις]{.greek-added} τον [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και εφαλλομενος [ο]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} επ αυτους [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον [και]{.greek-omitted} [κατακυριευσαν]{.greek-omitted} [κατακυριευσας]{.greek-added} αυτων [ισχυσεν]{.greek-omitted} [ισχυσε]{.greek-added} κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν εκ του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον πασιν ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} τοις [κατοικουσιν]{.greek-omitted} [κατοικουσι]{.greek-added} την εφεσον και [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} φοβος επι παντας αυτους και εμεγαλυνετο το ονομα το[υ]{.unclear} [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι τε των πεπιστευκοτων ηρχοντο εξομολογουμενοι και αναγγελλοντες τας πραξεις αυτων[19:18]{.aside}

ικανοι δε των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και συνεψηφισαν τας τιμας αυτων και ευρον [αναργυριου]{.greek-added} [αργυριου]{.corr} [αυτων]{.greek-added} μυριαδας πεντε [[πεντηκοντα]{.corr}]{.greek-added}[19:19]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} κατα κρατος ο λογος του [κυριου]{.greek-abbr} ηυξανεν και ισχυεν[19:20]{.aside}

ως δε επληρωθη ταυτα εθετο ο παυλος εν τω [πνευματι]{.greek-abbr} διελθων την [μακεδονιαν]{.greek-omitted} [μακεδωνιαν]{.greek-added} και [την]{.greek-added} αχαιαν πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις την [μακεδονιαν]{.greek-omitted} [μακε]{.greek-added} [δωνιαν]{.greek-added} δυο των διακονουντων αυτω τιμοθεον και εραστον αυτος [επεσχεν]{.greek-omitted} [επεσχε]{.greek-added} χρονον εις την ασιαν[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος περι της οδου[19:23]{.aside}

δημητριος γαρ τις ονοματι αργυροκοπος ποιων ναους αργυρους [ισος]{.greek-added} [κιβωρια]{.greek-added} [μικρα]{.greek-added} αρτεμιδος παρειχετο τοις τεχνιταις [εργασιαν]{.greek-omitted} ουκ ολιγην [εργασιαν]{.greek-added}[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας ειπεν ανδρες επιστασθε οτι εκ ταυτης της εργασιας η ευπορια ημων εστιν[19:25]{.aside}

και θεωρειτε και ακουετε οτι ου μονον εφεσου αλλα σχεδον πασης της ασιας ο παυλος ουτος πεισας μετεστησεν ικανον οχλον λεγων οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} θεοι οι δια χειρων [ανθρωπων]{.greek-added} γινομενοι[19:26]{.aside}

ου μονον δε τουτο κινδυνευει ημιν το μερος εις απελεγμον ελθειν αλλα και το της μεγαλης θεας [αρτεμιδος]{.greek-added} ιερον [αρτεμιδος]{.greek-omitted} εις ουθεν λογισθηναι μελλειν [δε]{.greek-omitted} [τε]{.greek-added} και καθαιρεισθαι την [μεγαλειοτητα]{.greek-omitted} [μεγαλιοτητα]{.greek-added} αυτης ην ολη η ασια και η οικουμενη σεβεται[19:27]{.aside}

ακουσαντες δε και γενομενοι [πληρεις]{.greek-omitted} [πληρις]{.greek-added} θυμου εκραζον λεγοντες μεγαλη η αρτεμις εφεσιων[19:28]{.aside}

και επλησθη η πολις ολη της συγχυσεως ωρμησαν τε ομοθυμαδον εις το θεατρον συναρπασαντες γαιον και αρισταρχον [μακεδονας]{.greek-omitted} [μακεδωνας]{.greek-added} συνεκδημους παυλου[19:29]{.aside}

του δε παυλου βουλομενου εισελθειν εις τον δημον ουκ ειων αυτον οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες αυτω φιλοι πεμψαντες προς αυτον παρεκαλουν μη δουναι εαυτον εις το θεατρον[19:31]{.aside}

αλλοι μεν ουν αλλο τι εκραζον ην γαρ η εκκλησια συγκεχυμενη και οι πλειους ουκ ηδεισαν τινος [ενεκεν]{.greek-omitted} [ενεκα]{.greek-added} συνεληλυθεισαν[19:32]{.aside}

εκ δε του οχλου προεβιβασαν αλεξανδρον προβαλοντων αυτον των ιουδαιων ο δε αλεξανδρος κατασεισας την χειρα ηθελεν απολογεισθαι τω δημω[19:33]{.aside}

επιγνοντες δε οτι ιουδαιος εστιν φωνη εγενετο μια εκ παντων [ως]{.greek-omitted} [επι]{.greek-omitted} [ωσει]{.greek-added} [περι]{.greek-added} ωρας δυο κραζοντων μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλας δε ο γραμματευς τον οχλον φησιν ανδρες εφεσιοι τις γαρ εστιν [ανθρωπος]{.greek-abbr} ος ου γινωσκει την εφεσιων πολιν νεωκορον ουσαν της μεγαλης θεας αρτεμιδος και του διοπετους[19:35]{.aside}

αναντιρρητων ουν οντων τουτων δεον εστιν υμας κατεσταλμενους υπαρχειν και μηδεν προπετες πρασσειν[19:36]{.aside}

ηγαγετε γαρ τους ανδρας τουτους ουτε ιεροσυλο[υς]{.unclear} ουτε βλασφημουντας [την]{.greek-omitted} θεον υμων[[19:37 *(lacunose)*]{.lacunose}]{.aside}

ει μεν ουν δημητριος και οι συν αυτω [τεχνιται]{.greek-omitted} [τεχνηται]{.greek-added} [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν εγκαλειτωσαν αλληλοις[19:38]{.aside}

ει δε τι περι [ετερων]{.greek-omitted} [ετερω]{.greek-added} επιζητειτε εν τη εννομω εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι της σημερον μηδενος αιτιου υπαρχοντος περι ου ου δυνησομεθα [δουναι]{.greek-omitted} [αποδουναι]{.greek-added} λογον [περι]{.greek-added} της [συστροφης]{.greek-omitted} [σοστροφης]{.greek-added} ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσε]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον θορυβον [προσκα]{.greek-added} [προσκαλεσαμενος]{.greek-omitted} [λεσαμενος]{.greek-added} ο παυλος τους μαθητας και [παρακαλεσας]{.greek-added} ασπασαμενος εξηλθεν [πορευθηναι]{.greek-omitted} [πορευεσθαι]{.greek-added} εις [την]{.greek-omitted} μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας τε μηνας τρεις γενομενης [επιβουλης]{.greek-added} αυτω [επιβουλης]{.greek-omitted} υπο των ιουδαιων μελλοντι αναγεσθαι εις την συριαν εγενετο [γνωμη]{.greek-omitted} [γνωμης]{.greek-added} του υποστρεφειν δια μακεδονιας[20:3]{.aside}

συνειπετο δε αυτω αχρι της ασιας σωπατρος βεροιαιος θεσσαλονικεων δε αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος ασιανοι δε τυχικος και τροφιμος[20:4]{.aside}

ουτοι [δε]{.greek-added} [προσελθοντες]{.greek-omitted} [προελθοντες]{.greek-added} εμενον ημας εν [τρωαδι]{.greek-omitted} [τρωαδη]{.greek-added}[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και ηλθομεν προς αυτους εις την τρωαδα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ημερων πεντε ου διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων [δε]{.greek-added} [των]{.corr} μαθητων κλασαι αρτον ο παυλος διελεγετο αυτοις μελλων εξιεναι τη επαυριον παρετεινεν τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε λαμπαδες ικαναι εν τω υπερωω ου ημεν συνηγμενοι[20:8]{.aside}

καθημενος δε τις νεανιας ονοματι ευτυχος επι της θυριδος καταφερομενος υπνω βαθει διαλεγομενου του παυλου επι πλειον κατενεχθεις απο του υπνου επεσεν απο του τριστεγου κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και [συμπεριλαβων]{.greek-omitted} [συμπαραλαβων]{.greek-added} ειπεν μη θορυβεισθε η γαρ ψυχη αυτου εν αυτω εστιν[20:10]{.aside}

αναβας δε και κλασας αρτον και γευσαμενος εφ ικανον τε ομιλησας [αχρι]{.greek-omitted} [αχρις]{.greek-added} αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον δε τον παιδα ζωντα και παρεκληθησαν ου μετριως[20:12]{.aside}

ημεις δε προσελθοντες επι το πλοιον ανηχθημεν εις την ασσον εκειθεν μελλοντες αναλαμβανειν τον παυλον ουτως γαρ ην διατεταγμενος μελλων αυτος [πεζευειν]{.greek-omitted} [παιζευγειν]{.greek-added}[20:13]{.aside}

ως δε συνεβαλεν ημιν εις την ασσον αναλαβοντες αυτον ηλθομεν εις μιτυληνην[20:14]{.aside}

κακειθεν αποπλευσαντες τη [επιουση]{.greek-omitted} [επιουσι]{.greek-added} κατηντησαμεν [αντικρυ]{.greek-omitted} [αντικρυς]{.greek-added} χιου τη δε ετερα παρεβαλομεν εις σαμον και μειναντες εν [τρωγυλλιω]{.greek-omitted} [τρογυλιω]{.greek-added} τη εχομενη ηλθομεν εις μιλητον[20:15]{.aside}

εκρινεν γαρ ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια εσπευδεν γαρ ει δυνατον ην αυτω την ημεραν της πεντηκοστης γενεσθαι εις ιεροσολυμα[20:16]{.aside}

απο δε της μιλητου πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον ειπεν αυτοις υμεις επιστασθε απο πρωτης ημερας αφ ης επεβην εις την ασιαν πως μεθ υμων τον παντα χρονον εγενομην[20:18]{.aside}

[δουλευων]{.greek-omitted} [δουλευειν]{.greek-added} τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και πολλων δακρυων και πειρασμων των συμβαντων μοι εν ταις επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων του μη αναγγειλαι [υμιν]{.greek-omitted} [ημιν]{.greek-added} και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

διαμαρτυρομενος ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} την εις τον [θεον]{.greek-abbr} μετανοιαν και πιστιν την εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr} [[χριστον]{.greek-abbr}]{.greek-added}[20:21]{.aside}

και νυν ιδου [δεδεμενος]{.greek-added} εγω [δεδεμενος]{.greek-omitted} τω [πνευματι]{.greek-abbr} πορευομαι εις [ιερουσαλημ]{.greek-abbr} τα εν αυτη συναντησοντα μοι μη ειδως[20:22]{.aside}

πλην οτι το [πνευμα]{.greek-abbr} το αγιον κατα πολιν διαμαρτυρεται [λεγον]{.greek-omitted} [λεγων]{.greek-added} οτι δεσμα [με]{.greek-omitted} και θλιψεις [με]{.greek-added} μενουσιν[20:23]{.aside}

αλλ ουδενος λογον ποιουμαι ουδε εχω την ψυχην μου τιμιαν εμαυτω ως τελειωσαι τον δρομον μου μετα χαρας και την διακονιαν ην ελαβον παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι οψεσθε το προσωπον μου υμεις παντες εν οις διηλθον κηρυσσων την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

[διοτι]{.greek-omitted} [διο]{.greek-added} μαρτυρομαι υμιν εν τη σημερον ημερα οτι καθαρος εγω απο του αιματος παντων [υμων]{.greek-added}[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι [υμιν]{.greek-omitted} πασαν την βουλην του [θεου]{.greek-abbr} [υμιν]{.greek-added}[20:27]{.aside}

προσεχετε ουν εαυτοις και παντι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επισκοπους ποιμαινειν την εκκλησιαν του [κυριου]{.greek-abbr} και [θεου]{.greek-abbr} ην περιεποιησατο δια του [αιματος]{.greek-added} [του]{.greek-added} ιδιου [αιματος]{.greek-omitted}[20:28]{.aside}

εγω γαρ οιδα τουτο οτι εισελευσονται μετα την αφιξιν μου λυκοι βαρεις εις υμας μη φειδομενοι του ποιμνιου[20:29]{.aside}

και εξ υμων αυτων αναστησονται ανδρες λαλουντες διεστραμμενα του αποσπαν τους μαθητας οπισω αυτων[20:30]{.aside}

διο γρηγορειτε μνημονευοντες οτι τριετιαν νυκτα και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον[20:31]{.aside}

και τα νυν παρατιθεμαι υμας [αδελφοι]{.greek-omitted} τω [θεω]{.greek-omitted} [[κυριω]{.greek-abbr}]{.greek-added} και τω λογω της χαριτος αυτου τω δυναμενω εποικοδομησαι και δουναι υμιν [την]{.greek-added} κληρονομιαν εν τοις ηγιασμενοις πασιν[20:32]{.aside}

αργυριου η χρυσιου η ιματισμου ουδενος επεθυμησα[20:33]{.aside}

αυτοι γινωσκετε οτι ταις χρειαις μου και τοις ουσιν μετ εμου υπηρετησαν αι χειρες αυται[20:34]{.aside}

παντα υπεδειξα υμιν οτι ουτως κοπιωντας δει αντιλαμβανεσθαι των ασθενουντων μνημονευειν τε των λογων [του]{.greek-omitted} [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} οτι αυτος ειπεν μακαριον εστιν μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα γονατα αυτου συν πασιν αυτοις προσηυξατο[20:36]{.aside}

ικανος δε [κλαυθμος]{.greek-added} εγενετο [κλαυθμος]{.greek-omitted} παντων και επιπεσοντες επι τον τραχηλον του παυλου κατεφιλουν αυτον[20:37]{.aside}

οδυνωμενοι μαλιστα επι τω λογω ω ειρηκει οτι ουκετι μελλουσιν το προσωπον αυτου θεωρειν προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας αποσπασθεντας απ αυτων ευθυδρομησαντες ηλθομεν εις την κων τη δε εξης εις την ροδον κακειθεν εις παταρα[21:1]{.aside}

και ευροντες πλοιον διαπερων εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

αναφανεντες δε την κυπρον και [καταλιποντες]{.greek-omitted} [καταλειποντες]{.greek-added} αυτην ευωνυμον επλεομεν εις συριαν και [κατηχθημεν]{.greek-omitted} [κατηλθομεν]{.greek-added} εις τυρον [ε]{.greek-added} [εκεισε]{.greek-omitted} [κεισε]{.greek-added} γαρ [ην]{.greek-omitted} το πλοιον [ην]{.greek-added} αποφορτιζομενον τον γομον[21:3]{.aside}

[και]{.greek-omitted} ανευροντες [δε]{.greek-added} [τους]{.greek-added} μαθητας επεμειναμεν αυτου ημερας επτα οιτινες τω παυλω ελεγον δια του [πνευματος]{.greek-abbr} μη αναβαινειν εις [ιερουσαλημ]{.greek-abbr}[21:4]{.aside}

οτε δε εγενετο ημας [εξαρτισαι]{.greek-omitted} [εξαρτησαι]{.greek-added} τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και τεκνοις εως εξω της πολεως και θεντες τα γονατα επι τον αιγιαλον [προσηυξαμεθα]{.greek-omitted} [προσευξαμεθα]{.greek-added}[21:5]{.aside}

και ασπασαμενοι αλληλους επεβημεν εις το πλοιον εκεινοι δε υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν [διανυσαντες]{.greek-omitted} [διανοισαντες]{.greek-added} απο τυρου κατηντησαμεν εις πτολεμαιδα και ασπασαμενοι τους αδελφους εμειναμεν ημεραν μιαν παρ αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες οι περι τον παυλον [ηλθον]{.greek-omitted} [ηλθομεν]{.greek-added} εις καισαρειαν και εισελθοντες εις τον οικον φιλιππου του ευαγγελιστου [οντος]{.greek-omitted} [οντως]{.greek-added} εκ των επτα εμειναμεν παρ αυτω[21:8]{.aside}

τουτω δε ησαν θυγατερες [παρθενοι]{.greek-omitted} τεσσαρες [παρνοι]{.greek-added} [[παρθνοι]{.corr}]{.greek-added} προφητευουσαι[21:9]{.aside}

επιμενοντων δε ημων ημερας πλειους κατηλθεν τις απο της ιουδαιας προφητης ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρας την ζωνην του παυλου δησας [τε]{.greek-omitted} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} τους ποδας και τας χειρας ειπεν ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τον ανδρα ου εστιν η ζωνη αυτη ουτως δησουσιν εν [ιερουσαλημ]{.greek-abbr} οι ιουδαιοι και παραδωσουσιν εις χειρας εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκαλουμεν ημεις τε και οι εντοπιοι του μη αναβαινειν αυτον εις [ιερουσαλημ]{.greek-abbr}[21:12]{.aside}

απεκριθη [τε]{.greek-omitted} [δε]{.greek-added} ο παυλος [και]{.greek-added} [ειπεν]{.greek-added} τι ποιειτε κλαιοντες και συνθρυπτοντες μου την καρδιαν εγω γαρ ου μονον δεθηναι αλλα και αποθανειν εις [ιερουσαλημ]{.greek-abbr} ετοιμως εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου ησυχασαμεν ειποντες το θελημα του [κυριου]{.greek-abbr} [γενεσθω]{.greek-omitted} [γινεσθω]{.greek-added}[21:14]{.aside}

μετα δε τας ημερας ταυτας επισκευασαμενοι ανεβαινομεν εις [ιερουσαλημ]{.greek-abbr}[21:15]{.aside}

συνηλθον δε και των μαθητων απο καισαρειας συν ημιν αγοντες παρ ω ξενισθωμεν [μνασωνι]{.greek-omitted} [μνασσωνι]{.greek-added} τινι κυπριω αρχαιω μαθητη[21:16]{.aside}

γενομενων δε ημων εις ιεροσολυμα ασμενως [εδεξαντο]{.greek-omitted} [απεδεξαντο]{.greek-added} ημας οι αδελφοι[21:17]{.aside}

τη δε επιουση [εισηει]{.greek-omitted} [εισειει]{.greek-added} ο παυλος συν ημιν προς ιακωβον παντες τε παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος αυτους [εξηγειτο]{.greek-omitted} [εξηγειτω]{.greek-added} καθ εν εκαστον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις εθνεσιν δια της διακονιας αυτου[21:19]{.aside}

οι δε ακουσαντες εδοξαζον τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ειποντες αυτω θεωρεις αδελφε ποσαι μυριαδες εισιν [ιουδαιων]{.greek-omitted} [εν]{.greek-added} [τοις]{.greek-added} [ιουδαιοις]{.greek-added} των πεπιστευκοτων και παντες ζηλωται του νομου υπαρχουσιν[21:20]{.aside}

κατηχηθησαν δε περι σου οτι αποστασιαν διδασκεις απο μωυσεως τους κατα τα εθνη παντας ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} περιπατειν[21:21]{.aside}

τι ουν εστιν παντως δει [συνελθειν]{.greek-added} πληθος [συνελθειν]{.greek-omitted} ακουσονται γαρ οτι εληλυθας[21:22]{.aside}

τουτο ουν ποιησον ο σοι λεγομεν [[λεγωμεν]{.corr}]{.greek-added} εισιν ημιν ανδρες τεσσαρες ευχην εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων αγνισθητι συν αυτοις και δαπανησον επ [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ινα [ξυρησωνται]{.greek-omitted} [ξυρησονται]{.greek-added} την κεφαλην και [γνωσιν]{.greek-omitted} [γνωσονται]{.greek-added} παντες οτι ων κατηχηνται περι σου ουδεν εστιν αλλα [στοιχεις]{.greek-omitted} [στυχεις]{.greek-added} και αυτος [φυλασσων]{.greek-added} τον νομον [φυλασσων]{.greek-omitted}[21:24]{.aside}

περι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες μηδεν τοιουτον τηρειν αυτους ει μη φυλασσεσθαι αυτους το τε ειδωλοθυτον και το αιμα και πνικτον και πορνειαν[21:25]{.aside}

τοτε [παραλαβων]{.greek-added} ο παυλος [παραλαβων]{.greek-omitted} τους ανδρας τη εχομενη ημερα συν αυτοις αγνισθεις [εισηει]{.greek-omitted} [εισειει]{.greek-added} εις το ιερον [διαγγελλων]{.greek-omitted} [διαγγελων]{.greek-added} την εκπληρωσιν των ημερων του αγνισμου εως ου προσηνεχθη υπερ ενος εκαστου αυτων η προσφορα[21:26]{.aside}

ως δε εμελλον αι επτα ημεραι συντελεισθαι οι απο της ασιας ιουδαιοι θεασαμενοι αυτον εν τω ιερω συνεχεον παντα τον οχλον και επεβαλον τας χειρας επ αυτον[21:27]{.aside}

κραζοντες ανδρες ισραηλιται [βοηθειτε]{.greek-omitted} [βοηθειται]{.greek-added} ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου τουτου παντας πανταχου διδασκων ετι τε και ελληνας εισηγαγεν εις το ιερον και [κεκοινωκεν]{.greek-omitted} [κεκοινωκε]{.greek-added} τον αγιον τοπον τουτον[21:28]{.aside}

ησαν γαρ εωρακοτες [τροφημον]{.greek-added} [τροφιμον]{.corr} τον εφεσιον εν τη πολει συν αυτω ον ενομιζον οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

εκινηθη τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του παυλου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

[ζητουντων]{.greek-omitted} [ζητουν]{.greek-added} [των]{.greek-added} δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της [σπειρης]{.greek-omitted} [σπειρας]{.greek-added} οτι ολη συγκεχυται [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και [εκατονταρχους]{.greek-omitted} [εκατονταρχας]{.greek-added} κατεδραμεν επ αυτους οι δε ιδοντες τον χιλιαρχον και τους στρατιωτας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

εγγισας δε ο χιλιαρχος επελαβετο αυτου και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δεθηναι [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} και επυνθανετο τις αν ειη και τι [εστιν]{.greek-omitted} [εστι]{.greek-added} πεποιηκως[21:33]{.aside}

αλλοι δε αλλο τι εβοων εν τω οχλω μη δυναμενος δε γνωναι το ασφαλες δια τον θορυβον εκελευσεν αγεσθαι αυτον εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον υπο των στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

ηκολουθει γαρ το πληθος του λαου [κραζον]{.greek-omitted} [κραζων]{.greek-added} αιρε αυτον[21:36]{.aside}

μελλων τε εισαγεσθαι εις την παρε[μ]{.unclear}βολην ο παυλος λεγει τω χιλιαρχω ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι ειπειν προς σε ο δε εφη ελληνιστι γινωσκεις[21:37]{.aside}

ουκ αρα συ ει ο αιγυπτιος ο προ τουτων των ημερων αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

ειπεν δε ο παυλος εγω [μεν]{.greek-added} [ανθρωπος]{.greek-abbr} [μεν]{.greek-omitted} ειμι ιουδαιος ταρσευς της κιλικιας ουκ ασημου πολεως πολιτης δεομαι δε σου επιτρεψον μοι λαλησαι προς τον λαον[21:39]{.aside}

επιτρεψαντος δε αυτου ο παυλος εστως επι των αναβαθμων [κατεσεισεν]{.greek-omitted} [κατεσεισε]{.greek-added} τη χειρι τω λαω πολλης δε σιγης [γενομενης]{.greek-omitted} [γεναμενης]{.greek-added} [προσεφωνει]{.greek-omitted} [προσεφωνησε]{.greek-added} τη εβραιδι διαλεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς υμας νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη εβραιδι διαλεκτω [προσεφωνει]{.greek-omitted} [προσφωνει]{.greek-added} [αυτοις]{.greek-omitted} [αυτους]{.greek-added} μαλλον παρεσχον ησυχιαν και φησιν[22:2]{.aside}

εγω μεν ειμι ανηρ ιουδαιος [γεγεννημενος]{.greek-omitted} [γεγενημενος]{.greek-added} εν ταρσω της κιλικιας ανατεθραμμενος δε εν τη πολει ταυτη παρα τους ποδας γαμαλιηλ πεπαιδευμενος [δε]{.greek-added} κατα ακριβειαν του πατρωου νομου ζηλωτης υπαρχων του [θεου]{.greek-abbr} καθως παντες υμεις εστε σημερον[22:3]{.aside}

ος ταυτην την οδον εδιωξα [αχρι]{.greek-omitted} [μεχρι]{.greek-added} θανατου δεσμευων και παραδιδους εις φυλακας ανδρας τε και γυναικας[22:4]{.aside}

ως και ο αρχιερευς μαρτυρει μοι και παν το πρεσβυτεριον παρ ων και επιστολας δεξαμενος προς τους αδελφους εις δαμασκον επορευομην [δε]{.greek-added} αξων και τους εκεισε οντας δεδεμενους εις [ιερουσαλημ]{.greek-abbr} ινα τιμωρηθωσιν[22:5]{.aside}

εγενετο δε μοι πορευομενω και εγγιζοντι τη δαμασκω περι μεσημβριαν εξαιφνης εκ του [ουρανου]{.greek-abbr} περιαστραψαι φως ικανον περι εμε[22:6]{.aside}

επεσα τε εις το εδαφος και ηκουσα φωνης λεγουσης μοι σαουλ σαουλ τι με διωκεις[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} ειπεν τε προς με εγω ειμι [ιησους]{.greek-abbr} ο ναζωραιος ον συ διωκεις[22:8]{.aside}

οι δε συν εμοι οντες το μεν φως εθεασαντο [και]{.greek-omitted} [εμφοβοι]{.greek-omitted} [εγενοντο]{.greek-omitted} την δε φωνην ουκ ηκουσαν του λαλουντος μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς με αναστας πορευου εις δαμασκον κακει σοι λαληθησεται [τι]{.greek-added} [σε]{.greek-added} [δει]{.greek-added} [ποιειν]{.greek-added} [περι]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [τετακται]{.greek-omitted} [σοι]{.greek-omitted} [ποιησαι]{.greek-omitted}[22:10]{.aside}

ως δε [και]{.greek-added} ουκ ενεβλεπον απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι ηλθον εις δαμασκον[22:11]{.aside}

ανανιας δε τις ανηρ [ευσεβης]{.greek-omitted} [ευλαβης]{.greek-added} κατα τον νομον μαρτυρουμενος υπο παντων των κατοικουντων [εν]{.greek-added} [δαμασκω]{.greek-added} ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας ειπεν μοι σαουλ αδελφε αναβλεψον καγω αυτη τη ωρα ανεβλεψα εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [προεχειρισατο]{.greek-omitted} [προεχειρησατο]{.greek-added} σε γνωναι το θελημα αυτου και ιδειν [τον]{.greek-omitted} [το]{.greek-added} δικαιον και ακουσαι φωνην εκ του στοματος [σου]{.greek-added} [αυτου]{.corr}[22:14]{.aside}

οτι εση μαρτυς αυτω προς παντας [ανθρωπους]{.greek-abbr} ων εωρακας και ηκουσας[22:15]{.aside}

και νυν τι μελλεις αναστας βαπτισαι και απολουσαι τας αμαρτιας σου επικαλεσαμενος το ονομα του [κυριου]{.greek-abbr}[22:16]{.aside}

εγενετο δε μοι υποστρεψαντι εις [ιερουσαλημ]{.greek-abbr} και προσευχομενου μου εν τω ιερω γενεσθαι με εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον και εξελθε εν ταχει εξ [ιερουσαλημ]{.greek-abbr} διοτι ου παραδεξονται σου την μαρτυριαν περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω ημην φυλακιζων και δερων κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε [εξεχειτο]{.greek-omitted} [εξεχει]{.greek-added} το αιμα στεφανου του μαρτυρος σου και αυτος ημην εφεστως και συνευδοκων τη αναιρεσει αυτου φυλασσων τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς με πορευου οτι εγω εις εθνη μακραν εξαποστελω σε[22:21]{.aside}

ηκουον δε αυτου αχρι τουτου του λογου και επηραν την φωνην αυτων λεγοντες αιρε απο της γης τον τοιουτον ου γαρ καθηκεν αυτον ζην[22:22]{.aside}

[κραζοντων]{.greek-omitted} [κραυγαζοντων]{.greek-added} δε αυτων και [ριπτουντων]{.greek-omitted} [ριπτοντων]{.greek-added} τα ιματια και κονιορτον βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν αυτον ο χιλιαρχος αγεσθαι εις την παρεμβολην ειπων μαστιξιν ανεταζεσθαι αυτον ινα επιγνω δι ην αιτιαν ουτως επεφωνουν αυτω[22:24]{.aside}

[ως]{.greek-omitted} [ο]{.greek-added} δε προετεινεν αυτον τοις ιμασιν [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς τον εστωτα εκατονταρχον ο παυλος ει [ανθρωπον]{.greek-abbr} ρωμαιον και ακατακριτον εξεστιν υμιν μαστιζειν[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων [απηγγειλεν]{.greek-omitted} τω χιλιαρχω [απηγγειλεν]{.greek-added} λεγων ορα τι μελλεις ποιειν ο γαρ [ανθρωπος]{.greek-abbr} ουτος ρωμαιος εστιν[22:26]{.aside}

προσελθων δε ο χιλιαρχος ειπεν αυτω λεγε μοι [ει]{.greek-omitted} συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκριθη τε ο χιλιαρχος εγω πολλου κεφαλαιου την πολιτειαν ταυτην εκτησαμην ο δε παυλος εφη εγω δε και [γεγεννημαι]{.greek-omitted} [γεγενημαι]{.greek-added}[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες [ανεταζειν]{.greek-added} αυτον [ανεταζειν]{.greek-omitted} και ο χιλιαρχος δε εφοβηθη επιγνους οτι ρωμαιος εστιν και οτι ην αυτον δεδεκως[22:29]{.aside}

τη δε επαυριον βουλομενος γνωναι το ασφαλες το τι κατηγορειται παρα των ιουδαιων ελυσεν αυτον απο των δεσμων και εκελευσεν ελθειν τους αρχιερεις και ολον το συνεδριον αυτων και καταγαγων τον παυλον εστησεν εις αυτους[22:30]{.aside}

### Chapter 23

ατενισας δε ο παυλος τω συνεδριω ειπεν ανδρες αδελφοι εγω παση συνειδησει αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι ταυτης της ημερας[23:1]{.aside}

ο δε αρχιερευς ανανιας [επεταξεν]{.greek-omitted} [επεταξε]{.greek-added} τοις παρεστωσιν αυτω τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον ειπεν τυπτειν σε μελλει ο [θεος]{.greek-abbr} τοιχε [κεκονιαμεναι]{.greek-added} [κεκονιαμεν[ε]{.unclear}]{.corr} και συ καθη κρινων με κατα τον νομον και παρανομων κελευεις με τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες ειπον τον αρχιερεα του [θεου]{.greek-abbr} λοιδορεις[23:4]{.aside}

εφη τε ο παυλος ουκ ηδειν αδελφοι οτι εστιν αρχιερευς γεγραπται γαρ αρχοντα του λαου [σου]{.greek-omitted} ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος [εστιν]{.greek-omitted} [εστι]{.greek-added} σαδδουκαιων το δε ετερον φαρισ[αι]{.unclear}ων εκραξεν εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμ[ι]{.greek-supplied} υιος φαρισαιου περι ελπιδος και αναστασεως νεκρων εγω κρινομαι[23:6]{.aside}

τουτο δε αυτου λαλησαντος εγενετο στασις των φαρισαιων και [των]{.greek-added} [σαδδουκαιων]{.greek-added} [και]{.greek-added} εσχισθη το πληθος[23:7]{.aside}

σαδδουκαιοι μεν γαρ λεγουσιν μη ειναι αναστασιν [μηδε]{.greek-omitted} [μητε]{.greek-added} αγγελον μητε [πνευμα]{.greek-abbr} φαρισαιοι δε [ομολογουσιν]{.greek-omitted} [ομολογουσι]{.greek-added} τα αμφοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και ανασταντες οι γραμματεις του μερους των φαρισαιων διεμαχοντο λεγοντες ουδεν κακον ευρισκομεν εν τω [ανθρωπω]{.greek-abbr} τουτω ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω [η]{.greek-omitted} [ει]{.greek-added} αγγελος μη θεομαχωμεν[23:9]{.aside}

πολλης δε γενομενης στασεως [ευλαβηθεις]{.greek-omitted} [ευλαβηθης]{.greek-added} ο χιλιαρχος μη διασπασθη ο παυλος υπ αυτων [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} το στρατευμα [αυτου]{.greek-added} καταβηναι και αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση νυκτι επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν θαρσει παυλε ως γαρ διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} ουτως σε δει και εις ρωμην [μαρτυρησαι]{.greek-omitted} [μαρτυρισαι]{.greek-added}[23:11]{.aside}

γενομενης δε ημερας ποιησαντες τινες των ιουδαιων συστροφην [ανεθεματισαν]{.greek-omitted} [ανεθεματησαν]{.greek-added} εαυτους λεγοντες μητε φαγειν μητε πιειν εως ου [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} τον παυλον[23:12]{.aside}

ησαν δε πλειους τεσσαρακοντα οι ταυτην την συνωμοσιαν πεποιηκοτες[23:13]{.aside}

οιτινες προσελθοντες τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις ειπον [αναθεματι]{.greek-omitted} [ανεθεματισαμεν]{.greek-omitted} [αναθεματισαμεν]{.greek-added} εαυτους μηδενος γευσασθαι εως ου αποκτεινωμεν τον παυλον[23:14]{.aside}

νυν ουν υμεις εμφανισατε τω χιλιαρχω συν τω συνεδριω οπως αυριον αυτον [καταγαγη]{.greek-omitted} [καταγαγει]{.greek-added} προς υμας ως μελλοντας διαγινωσκειν ακριβεστερον τα περι αυτου ημεις δε προ του εγγισαι αυτον ετοιμοι εσμεν του ανελειν αυτον[23:15]{.aside}

ακουσας δε ο υιος της αδελφης παυλου το ενεδρον παραγενομενος και εισελθων εις την παρεμβολην απηγγειλεν τω παυλω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων εφη τον νεανιαν τουτον [απαγαγε]{.greek-omitted} [επαναγαγε]{.greek-added} [εις]{.greek-added} [προς]{.corr} τον χιλιαρχον εχει γαρ τι απαγγειλαι αυτω[23:17]{.aside}

ο μεν ουν παραλαβων αυτον [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} προς τον χιλιαρχον [ειπων]{.greek-added} [και]{.greek-omitted} [φησιν]{.greek-omitted} ο δεσμιος παυλος προσκαλεσαμενος με [ηρωτησεν]{.greek-omitted} [ηρωτησε]{.greek-added} τουτον τον νεανιαν αγαγειν προς σε εχοντα τι λαλησαι [σοι]{.greek-omitted} [προς]{.greek-added} [σε]{.greek-added}[23:18]{.aside}

επιλαβομενος δε της χειρος αυτου ο χιλιαρχος και αναχωρησας κατ ιδιαν επυνθανετο τι εστιν ο εχεις απαγγειλαι μοι[23:19]{.aside}

ειπεν δε οτι οι ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον εις το συνεδριον καταγαγης τον παυλον ως μελλοντα τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ ουν μη πεισθης αυτοις [ενεδρευουσιν]{.greek-omitted} [ενεδρευουσι]{.greek-added} γαρ αυτον εξ αυτων ανδρες πλειους τεσσαρακοντα οιτινες [ανεθεματισαν]{.greek-omitted} [αναθεματισαν]{.greek-added} εαυτους μητε φαγειν μητε πιειν εως ου ανελωσιν αυτον και νυν ετοιμοι [εισιν]{.greek-omitted} [εισι]{.greek-added} προσδεχομενοι την απο σου επαγγελ[ι]{.unclear}αν[23:21]{.aside}

ο μεν ουν χιλιαρχος [απελυσεν]{.greek-omitted} [απελυσε]{.greek-added} τον νεανια[ν]{.unclear} παραγγειλας μηδενι εκλαλησαι οτι ταυτα εν[ε]{.unclear}φανισας προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους οπω[ς]{.unclear} πορευθωσιν εως καισαρειας και ιππεις εβδομηκοντα και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

κτηνη τε παραστησαι ινα [επιβιβασαντες]{.greek-omitted} [επιβηβασαντες]{.greek-added} τον παυλον [διασωσωσιν]{.greek-omitted} [διασωσωσι]{.greek-added} προς [φηλικα]{.greek-omitted} [φιληκα]{.greek-added} τον ηγεμονα[23:24]{.aside}

γραψας επιστολην περιεχουσαν τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω [ηγεμονι]{.greek-omitted} [ηγεμωνι]{.greek-added} [φηλικι]{.greek-omitted} [φιλικι]{.greek-added} χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο των ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι [εξειλομην]{.greek-omitted} [εξειλαμην]{.greek-added} αυτον μαθων οτι ρωμαιος εστιν[23:27]{.aside}

βουλομενος δε γνωναι την αιτιαν δι ην ενεκαλουν αυτω κατηγαγον αυτον εις το συνεδριον αυτων[23:28]{.aside}

ον ευρον εγκαλουμενον περι ζητηματων του νομου αυτων μηδεν [δε]{.greek-added} αξιον θανατου η δεσμων [εχοντα]{.greek-added} εγκλημα [εχοντα]{.greek-omitted}[23:29]{.aside}

μηνυθεισης δε μοι επιβουλης εις τον ανδρα μελλειν εσεσθαι υπο των ιουδαιων εξαυτης επεμψα προς σε παραγγειλας και τοις κατηγοροις λεγειν τα προς αυτον επι σου [ερρωσο]{.greek-omitted} [ερρωσθε]{.greek-added}[23:30]{.aside}

οι μεν ουν στρατιωται κατα το διατεταγμενον αυτοις αναλαβοντες τον παυλον ηγαγον δια της νυκτος εις την αντιπατριδα[23:31]{.aside}

τη δε επαυριον εασαντες τους ιππεις πορευεσθαι συν αυτω υπεστρεψαν εις την παρεμβολην[23:32]{.aside}

οιτινες εισελθοντες εις την καισαρειαν και αναδοντες την επιστολην τω [ηγεμονι]{.greek-omitted} [ηγεμονη]{.greek-added} παρεστησαν και τον παυλον αυτω[23:33]{.aside}

αναγνους δε ο ηγεμων και επερωτησας εκ ποιας [επαρχιας]{.greek-omitted} [επαρχειας]{.greek-added} εστιν και πυθομενος οτι απο κιλικιας[23:34]{.aside}

διακουσομαι σου εφη οταν και οι κατηγοροι σου [παραγενωνται]{.greek-omitted} [παραγενονται]{.greek-added} [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τε αυτον εν τω πραιτωριω ηρωδου φυλασσεσθαι[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη ο αρχιερευς ανανιας μετα των πρεσβυτερων και ρητορος τερτυλλου τινος οιτινες ενεφανισαν τω [ηγεμονι]{.greek-omitted} [ηγεμονη]{.greek-added} κατα του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο [κατηγορειν]{.greek-omitted} ο τερτυλλος [κατηγορειν]{.greek-added} λεγων [πο]{.greek-added} [πολλης]{.greek-omitted} [λλης]{.greek-added} ειρηνης τυγχανοντες δια σου και κατορθωματων γινομενων τω [εθνει]{.greek-omitted} [εθνη]{.greek-added} τουτω δια της σης προνοιας[24:2]{.aside}

[παντη]{.greek-omitted} [παντι]{.greek-added} τε και πανταχου αποδεχομεθα κρατιστε [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} μετα πασης [ευχαριστιας]{.greek-omitted} [ευχαριστειας]{.greek-added}[24:3]{.aside}

ινα δε μη επι πλειον σε εγκοπτω παρακαλω ακουσαι σε ημων συντομως τη ση επιεικεια[24:4]{.aside}

ευροντες γαρ τον ανδρα τουτον [λοιμον]{.greek-omitted} και κινουντα στασιν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ιουδαιοις τοις κατα την οικουμενην πρωτοστατην τε της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον επειρασεν βεβηλωσαι ον και εκρατησαμεν[24:6]{.aside}

παρ ου δυνηση αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

συνεπεθεντο δε και οι ιουδαιοι φασκοντες ταυτα ουτως εχειν[24:9]{.aside}

απεκριθ[η]{.unclear} δε ο παυλος νευσαντος αυτω του ηγεμονος λεγει[ν]{.greek-supplied} εκ πολλων ετων οντα σε κρ[ι]{.greek-supplied}την τω [εθνει]{.greek-omitted} [εθνη]{.greek-added} τουτω επισταμενος ευθυμοτερον τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} οτι ου πλειους [εισιν]{.greek-omitted} [εισι]{.greek-added} μοι ημεραι δεκαδυο [αφ]{.greek-omitted} [ης]{.greek-omitted} ανεβην προσκυνησων εν [ιερουσαλημ]{.greek-abbr}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η επισυστασιν ποιουντα οχλου ουτε εν ταις συναγωγαις ουτε κατα την πολιν[24:12]{.aside}

ουτε παραστησαι με [νυν]{.greek-added} δυνανται περι ων νυν [κατηγορουσιν]{.greek-omitted} [κατηγορουσι]{.greek-added} [μου]{.greek-omitted} [μο[ι]{.unclear}]{.greek-added}[24:13]{.aside}

ομολογω δε τουτο σοι οτι κατα την οδον ην λεγουσιν αιρεσιν ουτως λατρευω τω πατρωω [θεω]{.greek-abbr} πιστευων πασιν τοις κατα τον νομον και τοις [προ]{.greek-added} [προφηταις]{.greek-omitted} [φηταις]{.greek-added} γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι προσδεχονται αναστασιν μελλειν εσεσθαι νεκρων δικαιων τε και αδικων[24:15]{.aside}

εν τουτω δε αυτος ασκω απροσκοπον συνειδησιν εχων προς [τε]{.greek-added} τον [θεον]{.greek-abbr} και τους [ανθρωπους]{.greek-abbr} δια παντος[24:16]{.aside}

δι ετων δε πλειονων παρεγενομην ελεημοσυνας ποιησων εις το εθνος μου και προσφορας[24:17]{.aside}

εν οις ευρον με ηγνισμενον εν τω ιερω ου μετα οχλου ουδε μετα θορυβου [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιοι]{.greek-added} ους δει επι σου παρειναι και κατηγορειν ει τι εχοιεν προς με[24:19]{.aside}

η αυτοι ουτοι ειπατωσαν τι ευρον εν εμοι αδικημα σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας ταυτης φωνης ης εκραξα εστως εν αυτοις οτι περι αναστασεως νεκρων εγω κρινομαι σημερον υφ υμων[24:21]{.aside}

ακουσας δε ταυτα ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} ανεβαλετο αυτους ακριβεστερον ειδως τα περι της οδου ειπων οταν λυσιας ο χιλιαρχος καταβη διαγνωσομαι τα καθ υμας[24:22]{.aside}

διαταξαμενος τε τω [εκατονταρχη]{.greek-omitted} [εκατονταρχει]{.greek-added} [τηρεισθαι]{.greek-omitted} [τηρειν]{.greek-added} τον παυλον εχειν τε ανεσιν και μηδενα κωλυειν των ιδιων αυτου υπηρετειν η προσερχεσθαι αυτω[24:23]{.aside}

μετα δε ημερας τινας παραγενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} συν δρουσιλλη τη γυναικι ουση ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου περι της εις [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του μελλοντος εσεσθαι εμφοβος γενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} απεκριθη το νυν εχον πορευου καιρον δε μεταλαβων μετακαλεσομαι σε[24:25]{.aside}

αμα και ελπιζων οτι χρηματα δοθησεται αυτω υπο του παυλου οπως λυση αυτον διο και [πυκνοτερον]{.greek-omitted} [ποικνοτερον]{.greek-added} αυτον μεταπεμπομενος ωμιλει αυτω[24:26]{.aside}

διετιας δε πληρωθεισης ελαβεν διαδοχον ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} πορκιον φηστον θελων τε χαριτας καταθεσθαι τοις ιουδαιοις ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [κατελιπεν]{.greek-omitted} [κατελιπε]{.greek-added} τον παυλον δεδεμενον[24:27]{.aside}

### Chapter 25

φηστος ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη εις ιεροσολυμα απο καισαρειας[25:1]{.aside}

ενεφανισαν δε αυτω ο αρχιερευς και οι πρωτοι των ιουδαιων κατα του παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται α[υ]{.unclear}τον εις [ιερουσαλημ]{.greek-abbr} ενεδραν [π]{.unclear}[οι]{.greek-supplied}ουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν ουν φηστος απεκριθη τηρεισθαι τον παυλον εν καισαρεια εαυτον δε μελλειν [εν]{.greek-omitted} [ταχει]{.greek-omitted} εκπορευεσθαι[25:4]{.aside}

οι ουν δυνατοι εν υμιν φησιν συγκαταβαντες ει τι εστιν εν τω ανδρι τουτω κατηγορειτωσαν αυτου[25:5]{.aside}

διατριψας δε εν αυτοις ημερας πλειους η δεκα καταβας εις καισαρειαν τη επαυριον [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τον παυλον αχθηναι[25:6]{.aside}

παραγενομενου δε αυτου περιεστησαν οι απο ιεροσολυμων καταβεβηκοτες ιουδαιοι πολλα και βαρεα αιτιωματα φεροντες κατα του παυλου α ουκ ισχυον αποδειξαι[25:7]{.aside}

απολογουμενου αυτου οτι ουτε εις τον νομον των ιουδαιων ουτε εις το ιερον ουτε εις καισαρα τι ημαρτον[25:8]{.aside}

ο φηστος δε τοις ιουδαιοις θελων χαριν καταθεσθαι αποκριθεις τω παυλω ειπεν θελεις εις ιεροσολυμα αναβας εκει περι τουτων κρινεσθαι [επ]{.greek-omitted} [υπ]{.greek-added} εμου[25:9]{.aside}

ειπεν δε ο παυλος επι του βηματος καισαρος εστως ειμι ου με δει κρινεσθαι ιουδαιους [μεν]{.greek-added} ουδεν ηδικησα ως και συ καλλιον επιγινωσκεις[25:10]{.aside}

ει μεν γαρ αδικω και αξιον θανατου πεπραχα τι ου παραιτουμαι το αποθανειν ει δε ουδεν εστιν ων ουτοι [κατηγορουσιν]{.greek-omitted} [κατηγορουσι]{.greek-added} [μου]{.greek-omitted} [μοι]{.greek-added} ουδεις με δυναται αυτοις χαρισασθαι καισαρα επικαλουμαι[25:11]{.aside}

τοτε [ο]{.greek-omitted} φηστος συλλαλησας μετα του συμβουλιου απεκριθη καισαρα επικεκλησαι [επι]{.greek-omitted} [προς]{.greek-added} καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τινων αγριππας ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν ασπασαμενοι τον φηστον[25:13]{.aside}

ως δε πλειους ημερας διετριβεν εκει ο φηστος τ[ω]{.unclear} βασιλει ανεθετο [τα]{.corr} κατα τον παυλον λεγων ανηρ τις εστιν καταλελειμμενος υπο [φηλικος]{.greek-omitted} [φιλικος]{.greek-added} δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις ιεροσολυμα ενεφανισαν οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} εις απωλειαν πριν η ο κατηγορουμενος κατα προσωπον εχοι τους [κατη]{.greek-added} [κατηγορους]{.greek-omitted} [γορους]{.greek-added} τοπον τε απολογιας λαβοι [περι]{.greek-omitted} [κατα]{.greek-added} του εγκληματος[25:16]{.aside}

συνελθοντων ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη εξης [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν επεφερον ων υπενοουν εγω[25:18]{.aside}

ζητηματα δε τινα περι της ιδιας δεισιδαιμονιας ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τεθνηκοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω την περι τουτου ζητησιν ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-abbr} κακει κρινεσθαι περι τουτων[25:20]{.aside}

του δε παυλου επικαλεσαμενου τηρηθηναι [αυτον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [του]{.greek-omitted} [σεβαστου]{.greek-omitted} [διαγνωσιν]{.greek-omitted} [εκελευσα]{.greek-omitted} [τηρεισθαι]{.greek-omitted} αυτον εως ου πεμψω αυτον προς καισαρα[25:21]{.aside}

αγριππας δε προς τον φηστον εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της βερνικης μετα πολλης φαντασιας και εισελθοντων εις το ακροατηριον συν τε τοις χιλιαρχοις και [ανδρασιν]{.greek-omitted} [ανδρασι]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} κατ εξοχην [ουσιν]{.greek-omitted} [ουσι]{.greek-added} της πολεως και κελευσαντος του φηστου ηχθη ο παυλος[25:23]{.aside}

και φησιν ο φηστος αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες θεωρειτε τουτον περι ου [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος των ιουδαιων ενετυχον μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν ζην αυτον μηκετι[25:24]{.aside}

εγω δε καταλαβομενος μηδεν αξιον θανατου αυτον πεπραχεναι και αυτου δε τουτου επικαλεσαμενου τον σεβαστον [καισαρα]{.greek-added} εκρινα πεμπειν αυτον[25:25]{.aside}

περι ου ασφαλες τι γραψαι τω κυριω ουκ εχω διο προηγαγον αυτον εφ υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} σχω τι γραψαι[25:26]{.aside}

αλογον γαρ μοι δοκει πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη επιτρεπεται σοι υπερ σεαυτου λεγειν τοτε ο παυλος απελογειτο εκτεινας την χειρα[26:1]{.aside}

περι παντων ων εγκαλουμαι υπο ιουδαιων βασιλευ αγριππα ηγημαι εμαυτον μακαριον επι σου μελλων απολογεισθαι σημερον[26:2]{.aside}

μαλιστα γνωστην οντα σε παντων των κατα ιουδαιους ηθων τε και ζητηματων διο δεομαι σου μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ νεοτητος την απ αρχης γενομενην εν τω εθνει μου εν ιεροσολυμοις [ισασιν]{.greek-omitted} [ισασι]{.greek-added} παντες οι ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν θελωσιν μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας θρησκειας εζησα φαρισαιος[26:5]{.aside}

και νυν επ ελπιδι της προς τους [πατερας]{.greek-abbr} επαγγελιας γενομενης υπο του [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν [εκτενεια]{.greek-omitted} [εκτενια]{.greek-added} νυκτα και ημεραν [λατρευον]{.greek-omitted} [λατρευων]{.greek-added} ελπιζει καταντησαι περι ης ελπιδος εγκαλουμαι βασιλευ αγριππα υπο ιουδαιων[26:7]{.aside}

τι απιστον κρινεται παρ υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησα εν ιεροσολυμοις και πολλους των αγιων εγω φυλακαις κατεκλεισα την παρα των αρχιερεων εξουσιαν λαβων αναιρουμενων τε αυτων κατηνεγκα ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν περισσως τε εμμαινομενος αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις και πορευομενος εις την δαμασκον μετ εξουσιας και επιτροπης της παρα των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον ειδον βασιλευ [ουρανοθεν]{.greek-abbr} υπερ την λαμπροτητα του ηλιου περιλαμψαν με φως και τους συν εμοι πορευομενους[26:13]{.aside}

παντω[ν]{.greek-supplied} δε καταπεσοντων ημω[ν]{.greek-supplied} εις την γην ηκουσα φωνην λαλουσαν προς με [και]{.greek-omitted} [λεγουσαν]{.greek-omitted} τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε ειπον τις ει [κυριε]{.greek-abbr} ο δε ειπεν εγω ειμι [ιησους]{.greek-abbr} ον [συ]{.greek-omitted} [σοι]{.greek-added} διωκεις[26:15]{.aside}

αλλα αναστηθι και στηθι [επι]{.greek-omitted} [υπο]{.greek-added} τους ποδας σου εις τουτο γαρ ωφθην σοι προχειρισασθαι σε υπηρετην και μαρτυρα ων τε ειδες ων τε οφθησομαι σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου και των εθνων εις ους εγω σε αποστελλω[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του υποστρεψαι απο σκοτους εις φως και της [εξουσιας]{.greek-omitted} [εξου]{.greek-added} [σιας]{.greek-added} του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν [βασιλευ]{.greek-omitted} [βασιλευς]{.greek-added} αγριππα ουκ εγενομην απειθης τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον και ιεροσολυμοις εις πασαν τε την χωραν της ιουδαιας και τοις εθνεσιν [απαγγελλων]{.greek-omitted} [απαγγελω]{.greek-added} μετανοειν και επιστρεφειν επι τον [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων [με]{.greek-added} οι ιουδαιοι [με]{.greek-omitted} [συλλαβομενοι]{.greek-omitted} [συλλαμβανομενοι]{.greek-added} εν τω ιερω επειρωντο διαχειρισασθαι[26:21]{.aside}

επικουριας ουν τυχων της παρα του [θεου]{.greek-abbr} αχρι της ημερας ταυτης εστηκα μαρτυρομενος μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και μωυσης[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως μελλει καταγγελλειν τω [τε]{.greek-added} λαω και τοις εθνεσιν[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο φηστος μεγαλη τη φωνη εφη [μαινη]{.greek-omitted} [μαινει]{.greek-added} παυλε τα πολλα σε γραμματα εις μανιαν περιτρεπει[26:24]{.aside}

ο δε ου μαινομαι [φησιν]{.greek-omitted} [φησι]{.greek-added} κρατιστε φηστε αλλα αληθειας και σωφροσυνης ρηματα [αποφθεγγομαι]{.greek-omitted} [φθεγγομαι]{.greek-added}[26:25]{.aside}

[επιστατε]{.greek-added} [επισταται]{.corr} γαρ περι τουτων ο βασιλευς προς ον και παρρησιαζομενος λαλω λανθανειν γαρ αυτον τι τουτων ου πειθομαι ουδεν ου γαρ εν γωνια πεπραγμενον τουτο[26:26]{.aside}

πιστευεις [βασιλευ]{.greek-omitted} [βασιλευς]{.greek-added} αγριππα τοις προφηταις [και]{.greek-added} οιδα οτι πιστευεις[26:27]{.aside}

ο δε αγριππας προς τον παυλον εφη εν ολιγω με πειθεις χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος [ειπεν]{.greek-omitted} [εφη]{.greek-added} [ευξαιμην]{.greek-omitted} [ευξαμην]{.greek-added} αν τω [θεω]{.greek-abbr} και εν ολιγω και εν πολλω ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος καγω ειμι παρεκτος των δεσμων τουτων[26:29]{.aside}

και ταυτα ειποντος αυτου ανεστη ο βασιλευς και ο ηγεμων η τε βερνικη και οι συγκαθημενοι αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν θανατου αξιον η δεσμων πρασσει ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

[αγριππας]{.greek-omitted} [δε]{.greek-omitted} [τω]{.greek-omitted} [φηστω]{.greek-omitted} [εφη]{.greek-omitted} [απολελυσθαι]{.greek-omitted} [εδυνατο]{.greek-omitted} [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} [ουτος]{.greek-omitted} ει μη επεκεκλητο καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν [ημας]{.greek-omitted} [τους]{.greek-added} [περι]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} εις την ιταλιαν παρεδιδουν τον τε παυλον και τινας ετερους δεσμωτας εκατονταρχη ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω [αδραμυττηνω]{.greek-omitted} [ατραμυττηνω]{.greek-added} [μελλοντες]{.greek-omitted} [μελλοντος]{.greek-added} πλειν τους κατα την ασιαν τοπους ανηχθημεν οντος συν ημιν αρισταρχου μακεδονος θεσσαλονικεως[27:2]{.aside}

τη τε ετερα κατηχθημεν εις σιδωνα φιλανθρωπως τε ο ιουλιος τω παυλω χρησαμενος [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το τους [τοπους]{.greek-added} ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες κατηλθομεν εις μυρα της λυκιας[27:5]{.aside}

κακει ευρων ο εκατονταρχος πλοιον αλεξανδρινον πλεον εις την ιταλιαν [ενεβιβασεν]{.greek-omitted} [ανεβηβασεν]{.greek-added} ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις βραδυπλοουντες και μολις γενομενοι κατα την κνιδον μη προσεωντος [[εωντος]{.corr}]{.greek-added} ημας του ανεμου υπεπλευσαμεν την [κρητην]{.greek-omitted} [κριτην]{.greek-added} κατα [σαλμωνην]{.greek-omitted} [σαλμονην]{.greek-added}[27:7]{.aside}

μολις τε παραλεγομενοι αυτην ηλθομεν εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς [ην]{.greek-omitted} [ει]{.greek-added} πολις λασαια[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος ηδη επισφαλους του πλοος δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των ψυχων ημων μελλειν εσεσθαι τον πλουν[27:10]{.aside}

ο δε εκατονταρχης τω [κυβερνητη]{.greek-omitted} [κυβερνιτη]{.greek-added} και τω ναυκληρω επειθετο μαλλον η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι πλειους εθεντο βουλην αναχθηναι κακειθεν ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της [κρητης]{.greek-omitted} [κριτης]{.greek-added} βλεποντα κατα λιβα και κατα χωρον[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες ασσον παρελεγοντο την κρητην[27:13]{.aside}

μετ ου πολυ δε εβαλεν κατ αυτης ανεμος τυφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι υποδραμοντες [καλουμενον]{.greek-omitted} [κλαυδην]{.greek-omitted} μολις ισχυσαμεν [περι]{.greek-added} [περικρατεις]{.greek-omitted} [κρατεις]{.greek-added} γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες [βοηθειας]{.greek-added} [βοηθειαις]{.corr} εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη εις την συρτην [εκπεσωσιν]{.greek-omitted} [εκπεσωσι]{.greek-added} χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως δε χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη αυτοχειρες την σκευην του πλοιου ερριψαμεν[27:19]{.aside}

μητε δε ηλιου μητε αστρων επιφαινοντων επι [πλειονας]{.greek-omitted} [πλειους]{.greek-added} ημερας χειμωνος τε ουκ ολιγου επικειμενου λοιπον περιηρειτο πασα ελπις του σωζεσθαι ημας[27:20]{.aside}

πολλης δε ασιτιας υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης κερδησαι τε την υβριν ταυτη[ν]{.unclear} και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης ουδεμια εσται εξ υμων πλ[ην]{.greek-supplied} του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι αγγελος του [θεου]{.greek-abbr} ου ειμι [ω]{.greek-omitted} [ο]{.greek-added} [και]{.corr} λατρε[υ]{.unclear}ω[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει [παραστηναι]{.greek-omitted} [παραστειναι]{.greek-added} και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα μεσον της νυκτος υπενοουν οι ναυται προσαγειν τινα αυτοις χωρα[ν]{.unclear}[27:27]{.aside}

και [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας εικοσι βραχυ δε διαστησαντες και παλιν [βο]{.greek-added} [βολισαντες]{.greek-omitted} [λησαντες]{.greek-added} ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι τε μηπως εις τραχεις τοπους [εκπεσωμεν]{.greek-omitted} [εκπεσωσιν]{.greek-added} εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ πρωρας μελλοντων αγκυρας εκτεινειν[27:30]{.aside}

ειπεν ο παυλος τω εκατονταρχη και τοις στρατιωταις εαν μη ουτοι μεινωσιν εν τω πλοιω υμεις σωθηναι ου δυνασθε[27:31]{.aside}

τοτε οι στρατιωται απεκοψαν τα σχοινια της σκαφης και ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου ημελλεν ημερα [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων [τεσσαρεσκαιδεκατην]{.greek-omitted} [τεσσαρισκαιδεκατην]{.greek-added} σημερον ημεραν προσδοκωντες ασιτοι [διατελειτε]{.greek-omitted} [διατελειται]{.greek-added} μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας προσλαβειν τροφης τουτο γαρ προς της [υμετερας]{.greek-omitted} [ημετερας]{.greek-added} [σωτηριας]{.greek-abbr} υπαρχει ουδενος γαρ υμων θριξ εκ της κεφαλης [πεσειται]{.greek-omitted} [απολειται]{.greek-added}[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον ευχαριστησεν τω [θεω]{.greek-abbr} ενωπιον παντων και [κλασας]{.greek-omitted} ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

ημεν δε εν τω πλοιω [αι]{.greek-omitted} πασαι ψυχαι διακοσιαι εβδομηκοντα εξ[27:37]{.aside}

κορεσθεντες δε της τροφης εκουφιζον το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον εβουλευσαντο ει δυνατον εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των πηδαλιων και επαραντες τον [αρτεμονα]{.greek-omitted} [αρτεμωνα]{.greek-added} τη πνεουση κατειχον εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον [επωκειλαν]{.greek-omitted} [επωκιλαν]{.greek-added} την ναυν και η μεν πρωρα ερεισασα εμεινεν ασαλευτος η δε [πρυμνα]{.greek-omitted} [πρυνα]{.greek-added} ελυετο υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας αποκτεινωσιν μη τις εκκολυμβησας [[κολυμβησας]{.corr}]{.greek-added} διαφυγη[27:42]{.aside}

ο δε εκατονταρχος βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του βουληματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τε τους δυναμενους κολυμβαν απορριψαντας πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους μεν επι σανισι[ν]{.unclear} ους δε επι τινων των απο του πλοιου και ουτως εγενετο παντας διασωθηναι επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες τοτε επεγνωσαν οτι μελιτη η νησος καλειται[28:1]{.aside}

οι δε βαρβαροι παρειχον ου την τυχουσαν [φιλανθρωπιαν]{.greek-abbr} ημιν αναψαντες γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον [εφεστωτα]{.greek-omitted} [υφεστωτα]{.greek-added} και δια το ψυχος[28:2]{.aside}

συστρεψαντος δε του παυλου φρυγανων πληθος και επιθεντος επι την πυραν εχιδνα εκ της θερμης διεξελθουσα [καθηψεν]{.greek-omitted} [καθηψε]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε ειδον οι βαρβαροι κρεμαμενον το θηριον εκ της χειρος αυτου ελεγον προς αλληλους [παντως]{.greek-omitted} [παντος]{.greek-added} φονευς εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν αποτιναξας το θηριον εις το πυρ επαθεν ουδεν κακον[28:5]{.aside}

οι δε [προσεδοκων]{.greek-omitted} [προσεδωκων]{.greek-added} αυτον μελλειν πιμπρασθαι η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων προσδοκωντων και θεωρουντων μηδεν ατοπον εις αυτον γινομενον μεταβαλλομενοι ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6]{.aside}

εν δε τοις περι τον τοπον εκεινον [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} χωρια τω πρωτω της νησου ονοματι ποπλιω ος αναδεξαμενος ημας τρεις ημερας φιλοφρονως εξενισεν[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του ποπλιου πυρετοις και [δυσεντερια]{.greek-omitted} [δυσεντεριω]{.greek-added} συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις τας χειρας αυτω ιασατο αυτον[28:8]{.aside}

τουτου [ουν]{.greek-omitted} [δε]{.greek-added} γενομενου και οι λοιποι οι εχοντες ασθενειας εν τη νησω προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρειαν[28:10]{.aside}

μετα δε τρεις μηνας ηχθημεν [εν]{.greek-omitted} [παρα]{.greek-added} πλοιω παρακεχειμακοτι εν τη νησω αλεξανδρινω [παρασημω]{.greek-omitted} [παρασιμω]{.greek-added} [διοσκουροις]{.greek-omitted} [διοσκοροις]{.greek-added}[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες κατηντησαμεν εις ρηγιον και μετα μιαν ημεραν επιγενομενου νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις [επιμειναι]{.greek-omitted} [επιμειναντες]{.greek-added} ημερας επτα και ουτως εις την ρωμην ηλθομεν[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περι ημων εξηλθον εις απαντησιν ημιν [αχρι]{.greek-omitted} [αχρις]{.greek-added} αππιου φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} θαρσος[28:15]{.aside}

οτε δε ηλθομεν εις ρωμην ο εκατονταρχος [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τους δεσμιους τω [στρατοπεδαρχη]{.greek-omitted} [στρατοπεδαρχω]{.greek-added} τω δε παυλω [επετραπη]{.greek-omitted} [επετραπει]{.greek-added} μενειν καθ εαυτον συν τω φυλασσοντι αυτον στρατιωτη[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι τον παυλον τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} προς αυτους ανδρες αδελφοι εγω ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} τοις πατρωοις δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας τω[ν]{.unclear} ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με [εβουλοντο]{.greek-omitted} [ηβουλοντο]{.greek-added} απολυσαι δια το μηδεμιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων [αυτον]{.greek-added} ηναγκασθην επικαλεσασθαι καισαρα [ουχ]{.greek-omitted} [ως]{.greek-omitted} [του]{.greek-omitted} [εθνους]{.greek-omitted} [μου]{.greek-omitted} [εχων]{.greek-omitted} [τι]{.greek-omitted} [κατηγορησαι]{.greek-omitted}[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι ενεκεν γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε γραμματα περι σου εδεξαμεθα απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν η ελαλησεν τι περι σου πονηρον[28:21]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον εστιν ημιν οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι δε αυτω ημεραν ηκον προς αυτον εις την ξενιαν πλειονες οις εξετιθετο διαμαρτυρομενος την βασιλειαν του [θεου]{.greek-abbr} [πειθων]{.greek-omitted} [πειθον]{.greek-added} τε αυτους τα περι του [ιησου]{.greek-abbr} απο τε του νομου μωυσεως και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις [υπο]{.greek-added} [του]{.greek-added} [παυλου]{.greek-added} οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον ελαλησεν δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added}[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και ειπον ακοη ακουσετε και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη ιδητε[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και [ιασομαι]{.greek-omitted} [ιασωμαι]{.greek-added} αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και ταυτα αυτου ειποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις συζητησιν[28:29]{.aside}

εμεινεν δε ο παυλος διετιαν ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους προς αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} [και]{.greek-added} [θεραπευων]{.greek-added} [πασαν]{.greek-added} [νοσον]{.greek-added} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} μετα πασης παρρησιας ακωλυτως[28:31]{.aside}

