---
title: "Collation of Byz^RP^ vs 30343 (343)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 343 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30343).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 343                                   	| λογος                              	|
| 343 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 343 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 343               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 343                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 343 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 343                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Luke

### Chapter 1

επειδηπερ πολλοι επεχειρησαν αναταξασθαι διηγησιν περι των πεπληροφορημενων εν ημιν πραγματων[1:1]{.aside}

καθως παρεδοσαν [η]{.greek-added} [ημιν]{.greek-omitted} [μιν]{.greek-added} οι απ αρχης αυτοπται και υπηρεται γενομενοι του λογου[1:2]{.aside}

[εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} καμοι παρηκολουθηκοτι ανωθεν πασιν ακριβως καθεξης σοι γραψαι κρατιστε θεοφιλε[1:3]{.aside}

ινα επιγνως περι ων κατηχηθης λογων την ασφαλειαν[1:4]{.aside}

εγενετο εν ταις ημεραις ηρωδου του βασιλεως της ιουδαιας ιερευς τις ονοματι ζαχαριας εξ εφημεριας αβια και η γυνη αυτου εκ των θυγατερων ααρων και το ονομα αυτης ελισαβετ[1:5]{.aside}

ησαν δε δικαιοι αμφοτεροι ενωπιον του [θεου]{.greek-abbr} πορευομενοι εν πασαις ταις εντολαις και [δικαιωμασιν]{.greek-omitted} [δικαιωμασι]{.greek-added} του [κυριου]{.greek-abbr} αμεμπτοι[1:6]{.aside}

και ουκ ην αυτοις τεκνον καθοτι η ελισαβετ ην στειρα και αμφοτεροι προβεβηκοτες εν ταις ημεραις αυτων ησαν[1:7]{.aside}

εγενετο δε εν τω ιερατευειν αυτον εν τη ταξει της εφημεριας αυτου εναντι του [θεου]{.greek-abbr}[1:8]{.aside}

κατα το εθος της [ιερατειας]{.greek-omitted} [ιερατιας]{.greek-added} [ελαχεν]{.greek-omitted} [ελαχε]{.greek-added} του θυμιασαι εισελθων εις τον ναον του [κυριου]{.greek-abbr}[1:9]{.aside}

και παν το πληθος ην του λαου προσευχομενον εξω τη ωρα του θυμιαματος[1:10]{.aside}

ωφθη δε αυτω αγγελος [κυριου]{.greek-abbr} εστως εκ δεξιων του θυσιαστηριου του θυμιαματος[1:11]{.aside}

και εταραχθη ζαχαριας ιδων και φοβος επεπεσεν επ αυτον[1:12]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτον ο αγγελος μη φοβου ζαχαρια διοτι εισηκουσθη η δεησις σου και η γυνη σου ελισαβετ γεννησει [υιον]{.greek-abbr} σοι και καλεσεις το ονομα αυτου ιωαννην[1:13]{.aside}

και εσται χαρα σοι και αγαλλιασις και πολλοι επι τη γεννησει αυτου χαρησονται[1:14]{.aside}

εσται γαρ μεγας ενωπιον του [κυριου]{.greek-abbr} και οινον και σικερα ου μη πιη και [πνευματος]{.greek-abbr} αγιου πλησθησεται ετι εκ κοιλιας [μητρος]{.greek-abbr} αυτου[1:15]{.aside}

και πολλους των υιων [ισραηλ]{.greek-abbr} επιστρεψει επι [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} αυτων[1:16]{.aside}

και αυτος προελευσεται ενωπιον αυτου εν [πνευματι]{.greek-abbr} και δυναμει ηλιου επιστρεψαι καρδιας [πατερων]{.greek-abbr} επι τεκνα και απειθεις εν φρονησει δικαιων ετοιμασαι [κυριω]{.greek-abbr} λαον [κατεσκευασμενον]{.greek-omitted} [κατασκευασμενον]{.greek-added}[1:17]{.aside}

και ειπεν ζαχαριας προς τον αγγελον κατα τι γνωσομαι τουτο εγω γαρ ειμι πρεσβυτης και η γυνη μου προβεβηκυια εν ταις ημεραις αυτης[1:18]{.aside}

και αποκριθεις ο αγγελος ειπεν αυτω εγω ειμι γαβριηλ ο παρεστηκως ενωπιον του [θεου]{.greek-abbr} και απεσταλην λαλησαι προς σε και ευαγγελισασθαι σοι ταυτα[1:19]{.aside}

και ιδου εση σιωπων και μη δυναμενος λαλησαι αχρι ης ημερας γενηται ταυτα ανθ ων ουκ επιστευσας τοις λογοις μου οιτινες πληρωθησονται εις τον καιρον αυτων[1:20]{.aside}

και ην ο λαος προσδοκων τον ζαχαριαν και εθαυμαζον εν τω χρονιζειν αυτον εν τω ναω[1:21]{.aside}

εξελθων δε ουκ ηδυνατο λαλησαι αυτοις και [επεγνωσαν]{.greek-omitted} [εγνωσαν]{.greek-added} οτι οπτασιαν εωρακεν εν τω ναω και αυτος ην διανευων αυτοις και [διεμενεν]{.greek-omitted} [διεμενε]{.greek-added} κωφος[1:22]{.aside}

και εγενετο ως επλησθησαν αι ημεραι της λειτουργιας αυτου απηλθεν εις τον οικον αυτου[1:23]{.aside}

[μετα]{.greek-omitted} [με]{.greek-added} [τα]{.greek-added} δε ταυτας τας ημερας συνελαβεν ελισαβετ η γυνη αυτου και περιεκρυβεν εαυτην μηνας πεντε λεγουσα[1:24]{.aside}

οτι ουτως μοι πεποιηκεν ο [κυριος]{.greek-abbr} εν ημεραις αις επειδεν αφελειν το ονειδος μου εν [ανθρωποις]{.greek-abbr}[1:25]{.aside}

εν δε τω μηνι τω εκτω απεσταλη [ο]{.greek-omitted} αγγελος γαβριηλ υπο του [θεου]{.greek-abbr} εις πολιν της γαλιλαιας η ονομα [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added}[1:26]{.aside}

προς παρθενον μεμνηστευμενην ανδρι ω ονομα ιωσηφ εξ οικου [δαυιδ]{.greek-abbr} και το ονομα της παρθενου μαριαμ[1:27]{.aside}

και εισελθων ο αγγελος προς αυτην ειπεν χαιρε κεχαριτωμενη ο [κυριος]{.greek-abbr} μετα σου ευλογημενη συ εν γυναιξιν[1:28]{.aside}

η δε ιδουσα διεταραχθη επι τω λογω αυτου και διελογιζετο ποταπος ειη ο [ασπασμος]{.greek-omitted} [ασπμος]{.greek-added} ουτος[1:29]{.aside}

και ειπεν ο αγγελος αυτη μη φοβου μαριαμ ευρες γαρ χαριν παρα τω [θεω]{.greek-abbr}[1:30]{.aside}

και ιδου συλληψη εν γαστρι και [τεξη]{.greek-omitted} [τεξεις]{.greek-added} [υιον]{.greek-abbr} και καλεσεις το ονομα αυτου [ιησουν]{.greek-abbr}[1:31]{.aside}

ουτος εσται μεγας και [υιος]{.greek-abbr} υψιστου [κλη]{.greek-added} [κληθησεται]{.greek-omitted} [θησεται]{.greek-added} και δωσει αυτω [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} τον θρονον [δαυιδ]{.greek-abbr} του [πατρος]{.greek-abbr} αυτου[1:32]{.aside}

και βασιλευσει επι τον οικον ιακωβ εις τους αιωνας και της βασιλειας αυτου ουκ εσται τελος[1:33]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε μαριαμ προς τον αγγελον πως εσται τουτο επει ανδρα ου γινωσκω[1:34]{.aside}

και αποκριθεις ο αγγελος ειπεν αυτη [πνευμα]{.greek-abbr} αγιον επελευσεται επι σε και δυναμις υψιστου επισκιασει σοι διο και το [γεννωμενον]{.greek-omitted} [γεννομενον]{.greek-added} αγιον κληθησεται [υιος]{.greek-abbr} [θεου]{.greek-abbr}[1:35]{.aside}

και ιδου ελισαβετ η συγγενης σου και αυτη συνειληφυια [υιον]{.greek-abbr} εν [γηρει]{.greek-omitted} [γηρα]{.greek-added} αυτης και ουτος μην εκτος εστιν αυτη τη καλουμενη στειρα[1:36]{.aside}

οτι ουκ αδυνατησει παρα τω [θεω]{.greek-abbr} παν ρημα[1:37]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε μαριαμ ιδου η δουλη [κυριου]{.greek-abbr} γενοιτο μοι κατα το ρημα σου και απηλθεν απ αυτης ο αγγελος[1:38]{.aside}

αναστασα δε μαριαμ εν ταις ημεραις ταυταις επορευθη εις την ορεινην μετα σπουδης εις πολιν ιουδα[1:39]{.aside}

και εισηλθεν εις τον οικον ζαχαριου και [η]{.greek-added} [ησπασατο]{.greek-omitted} [σπασατο]{.greek-added} την ελισαβετ[1:40]{.aside}

και εγενετο ως ηκουσεν η ελισαβετ τον ασπασμον της μαριας [εσκιρτησεν]{.greek-omitted} [εσκιρτησε]{.greek-added} το βρεφος εν τη κοιλια αυτης και επλησθη [πνευματος]{.greek-abbr} αγιου η ελισαβετ[1:41]{.aside}

και [ανεφωνησεν]{.greek-omitted} [ανεφωνησε]{.greek-added} φωνη μεγαλη και ειπεν ευλογημενη συ εν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και ευλογημενος ο καρπος της κοιλιας σου[1:42]{.aside}

και ποθεν μοι τουτο ινα ελθη η [μητηρ]{.greek-abbr} του [κυριου]{.greek-abbr} μου προς με[1:43]{.aside}

ιδου γαρ ως εγενετο η φωνη του ασπασμου σου εις τα ωτα μου [εσκιρτησεν]{.greek-omitted} [εσκιρτησε]{.greek-added} το βρεφος εν αγαλλιασει εν τη κοιλια μου[1:44]{.aside}

και μακαρια η πιστευσασα οτι εσται τελειωσις τοις λελαλημενοις αυτη παρα [κυριου]{.greek-abbr}[1:45]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μαριαμ μεγαλυνει η ψυχη μου τον [κυριον]{.greek-abbr}[1:46]{.aside}

και [ηγαλλιασεν]{.greek-omitted} [ηγαλλιασε]{.greek-added} το [πνευμα]{.greek-abbr} μου επι τω [θεω]{.greek-abbr} τω [σωτηρι]{.greek-abbr} μου[1:47]{.aside}

οτι επεβλεψεν επι την ταπεινωσιν της δουλης αυτου ιδου γαρ απο του νυν [μακαριουσιν]{.greek-omitted} [μακαριουσι]{.greek-added} με πασαι αι γενεαι[1:48]{.aside}

οτι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} μοι μεγαλεια ο δυνατος και αγιον το ονομα [αυ]{.greek-added} [αυτου]{.greek-omitted} [του]{.greek-added}[1:49]{.aside}

και το ελεος αυτου εις [γενεας]{.greek-omitted} [γενεαν]{.greek-added} [και]{.greek-added} [γενεων]{.greek-omitted} [γενεαν]{.greek-added} τοις φοβουμενοις αυτον[1:50]{.aside}

εποιησεν κρατος εν βραχιονι αυτου διεσκορπισεν [υπερηφανους]{.greek-omitted} [υπερηφανων]{.greek-added} διανοια καρδιας αυτων[1:51]{.aside}

[καθειλεν]{.greek-omitted} [καθειλε]{.greek-added} δυναστας απο θρονων και [υψωσεν]{.greek-omitted} [υψωσε]{.greek-added} ταπεινους[1:52]{.aside}

πεινωντας ενεπλησεν αγαθων και πλουτουντας [εξαπεστειλεν]{.greek-omitted} [εξαπεστειλε]{.greek-added} κενους[1:53]{.aside}

αντελαβετο [ισραηλ]{.greek-abbr} παιδος αυτου μνησθηναι ελεους[1:54]{.aside}

καθως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} προς τους [πατερας]{.greek-abbr} ημων τω αβρααμ και τω σπερματι αυτου εις τον αιωνα[1:55]{.aside}

[εμεινεν]{.greek-omitted} [εμεινε]{.greek-added} δε μαριαμ συν αυτη ωσει μηνας τρεις και υπεστρεψεν εις τον οικον αυτης[1:56]{.aside}

τη δε ελισαβετ επλησθη ο χρονος του τεκειν αυτην και εγεννησεν [υιον]{.greek-abbr}[1:57]{.aside}

και ηκουσαν οι περιοικοι και οι συγγενεις αυτης οτι [εμεγαλυνεν]{.greek-omitted} [εμεγαλυνε]{.greek-added} [κυριος]{.greek-abbr} το ελεος αυτου μετ αυτης και συνεχαιρον αυτη[1:58]{.aside}

και εγενετο εν τη ογδοη ημερα ηλθον περιτεμειν το παιδιον και εκαλουν αυτο επι τω ονοματι του [πατρος]{.greek-abbr} αυτου ζαχαριαν[1:59]{.aside}

και αποκριθεισα η [μητηρ]{.greek-abbr} αυτου ειπεν ουχι αλλα κληθησεται ιωαννης[1:60]{.aside}

και ειπον προς αυτην οτι ουδεις εστιν εν τη συγγενεια σου ος καλειται τω ονοματι τουτω[1:61]{.aside}

ενενευον δε τω [πατρι]{.greek-abbr} αυτου το τι αν θελοι καλεισθαι [αυτον]{.greek-omitted} [αυτο]{.greek-added}[1:62]{.aside}

και αιτησας πινακιδιον [εγραψεν]{.greek-omitted} [εγραψε]{.greek-added} λεγων ιωαννης [εστιν]{.greek-omitted} [εστι]{.greek-added} το ονομα αυτου και εθαυμασαν παντες[1:63]{.aside}

ανεωχθη δε το στομα αυτου παραχρημα και η γλωσσα αυτου [διηρθρωθη]{.greek-added} και ελαλει ευλογων τον [θεον]{.greek-abbr}[1:64]{.aside}

και εγενετο επι παντας φοβος τους περιοικουντας αυτους και εν ολη τη ορεινη της ιουδαιας διελαλειτο παντα τα ρηματα ταυτα[1:65]{.aside}

και εθεντο παντες οι ακουσαντες εν τη καρδια αυτων λεγοντες τι αρα το παιδιον τουτο εσται και χειρ [κυριου]{.greek-abbr} ην μετ αυτου[1:66]{.aside}

και ζαχαριας ο [πατηρ]{.greek-abbr} αυτου επλησθη [πνευματος]{.greek-abbr} αγιου και [προεφητευσεν]{.greek-omitted} [προεφητευσε]{.greek-added} λεγων[1:67]{.aside}

ευλογητος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} του [ισραηλ]{.greek-abbr} οτι επεσκεψατο και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} λυτρωσιν τω λαω αυτου[1:68]{.aside}

και [ηγειρεν]{.greek-omitted} [ηγειρε]{.greek-added} κερας [σωτηριας]{.greek-abbr} ημιν εν τω οικω [δαυιδ]{.greek-abbr} του παιδος αυτου[1:69]{.aside}

καθως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δια στοματος των αγιων των απ αιωνος προφητων αυτου[1:70]{.aside}

[σωτηριαν]{.greek-abbr} εξ εχθρων ημων και εκ χειρος παντων των μισουντων ημας[1:71]{.aside}

ποιησαι ελεος μετα των [πατερων]{.greek-abbr} ημων και μνησθηναι διαθηκης αγιας αυτου[1:72]{.aside}

ορκον ον [ωμοσεν]{.greek-omitted} [ωμοσε]{.greek-added} προς αβρααμ τον [πατερα]{.greek-abbr} ημων του δουναι ημιν[1:73]{.aside}

αφοβως εκ χειρος των εχθρων ημων ρυσθεντας λατρευειν αυτω[1:74]{.aside}

εν οσιοτητι και δικαιοσυνη ενωπιον αυτου πασας τας ημερας της ζωης ημων[1:75]{.aside}

και συ παιδιον προφητης υψιστου κληθηση προπορευση γαρ προ προσωπου [κυριου]{.greek-abbr} ετοιμασαι οδους αυτου[1:76]{.aside}

του δουναι γνωσιν [σωτηριας]{.greek-abbr} τω λαω αυτου εν αφεσει αμαρτιων αυτων[1:77]{.aside}

δια σπλαγχνα ελεους [θεου]{.greek-abbr} ημων εν οις επεσκεψατο ημας ανατολη εξ υψους[1:78]{.aside}

επιφαναι τοις εν σκοτει και σκια θανατου [κα]{.greek-added} [καθημενοις]{.greek-omitted} [θημενοις]{.greek-added} του [κατευθυναι]{.greek-omitted} [κατευθηναι]{.greek-added} τους ποδας ημων εις οδον ειρηνης[1:79]{.aside}

το δε παιδιον [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και εκραταιουτο [πνευματι]{.greek-abbr} και ην εν ταις ερημοις εως ημερας αναδειξεως αυτου προς τον [ισραηλ]{.greek-abbr}[1:80]{.aside}

### Chapter 2

εγενετο δε εν ταις ημεραις εκειναις [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δογμα παρα καισαρος αυγουστου απογραφεσθαι πασαν την οικουμενην[2:1]{.aside}

αυτη η απογραφη πρωτη εγενετο ηγεμονευοντος της συριας κυρηνιου[2:2]{.aside}

και [επορευοντο]{.greek-omitted} [εξεπορευοντο]{.greek-added} παντες απογραφεσθαι εκαστος εις την ιδιαν πολιν[2:3]{.aside}

ανεβη δε και ιωσηφ απο της γαλιλαιας εκ πολεως [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} εις την ιουδαιαν εις πολιν [δαυιδ]{.greek-abbr} ητις καλειται βηθλεεμ δια το ειναι αυτον εξ οικου και [πατριας]{.greek-abbr} [δαυιδ]{.greek-abbr}[2:4]{.aside}

απογραψασθαι συν μαριαμ τη μεμνηστευμενη αυτω γυναικι ουση εγκυω[2:5]{.aside}

εγενετο δε εν τω ειναι αυτους εκει επλησθησαν αι ημεραι του τεκειν αυτην[2:6]{.aside}

και [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον [υιον]{.greek-abbr} αυτης τον πρωτοτοκον και εσπαργανωσεν αυτον και ανεκλινεν αυτον εν τη φατνη διοτι ουκ ην αυτοις τοπος εν τω καταλυματι[2:7]{.aside}

και ποιμενες ησαν εν τη χωρα τη αυτη αγραυλουντες και φυλασσοντες φυλακας της νυκτος επι την ποιμνην αυτων[2:8]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη αυτοις και δοξα [κυριου]{.greek-abbr} περιελαμψεν αυτους και εφοβηθησαν φοβον μεγαν[2:9]{.aside}

και ειπεν αυτοις ο αγγελος μη φοβεισθε ιδου γαρ ευαγγελιζομαι υμιν χαραν μεγαλην ητις εσται παντι τω λαω[2:10]{.aside}

οτι ετεχθη υμιν σημερον [σωτηρ]{.greek-abbr} ος [εστιν]{.greek-omitted} [εστι]{.greek-added} [χριστος]{.greek-abbr} [κυριος]{.greek-abbr} εν πολει [δαυιδ]{.greek-abbr}[2:11]{.aside}

και τουτο υμιν το σημειον ευρησετε βρεφος εσπαργανωμενον κειμενον εν φατνη[2:12]{.aside}

και εξαιφνης εγενετο συν τω αγγελω πληθος στρατιας [ουρανιου]{.greek-abbr} αινουντων τον [θεον]{.greek-abbr} και λεγοντων[2:13]{.aside}

δοξα εν υψιστοις [θεω]{.greek-abbr} και επι γης ειρηνη εν [ανθρωποις]{.greek-abbr} ευδοκια[2:14]{.aside}

και εγενετο ως απηλθον απ αυτων εις τον [ουρανον]{.greek-abbr} οι αγγελοι και οι [ανθρωποι]{.greek-abbr} οι ποιμενες ειπον προς αλληλους διελθωμεν δη εως βηθλεεμ και ιδωμεν το ρημα τουτο το γεγονος ο ο [κυριος]{.greek-abbr} εγνωρισεν ημιν[2:15]{.aside}

και ηλθον σπευσαντες και ανευρον την τε μαριαμ και τον ιωσηφ και το βρεφος κειμενον εν τη φατνη[2:16]{.aside}

ιδοντες δε διεγνωρισαν περι του ρηματος του λαληθεντος αυτοις περι του παιδιου τουτου[2:17]{.aside}

και παντες οι ακουσαντες εθαυμασαν περι των λαληθεντων υπο των ποιμενων προς αυτους[2:18]{.aside}

η δε μαριαμ παντα συνετηρει τα ρηματα ταυτα συμβαλλουσα εν τη καρδια αυτης[2:19]{.aside}

και υπεστρεψαν οι ποιμενες δοξαζοντες και αινουντες τον [θεον]{.greek-abbr} επι πασιν οις ηκουσαν και ειδον καθως ελαληθη προς αυτους[2:20]{.aside}

και οτε επλησθησαν ημεραι οκτω του περιτεμειν αυτον και εκληθη το ονομα αυτου [ιησους]{.greek-abbr} το κληθεν υπο του αγγελου προ του συλληφθηναι αυτον εν τη κοιλια[2:21]{.aside}

και οτε επλησθησαν αι ημεραι του καθαρισμου αυτων κατα τον νομον μωσεως ανηγαγον αυτον εις ιεροσολυμα παραστησαι τω [κυριω]{.greek-abbr}[2:22]{.aside}

καθως γεγραπται εν νομω [κυριου]{.greek-abbr} οτι παν αρσεν διανοιγον μητραν αγιον τω [κυριω]{.greek-abbr} κληθησεται[2:23]{.aside}

και του δουναι θυσιαν κατα το ειρημενον εν νομω [κυριου]{.greek-abbr} ζευγος τρυγονων η δυο νεοσσους περιστερων[2:24]{.aside}

και ιδου ην [ανθρωπος]{.greek-abbr} εν [ιερουσαλημ]{.greek-abbr} ω ονομα συμεων και ο [ανθρωπος]{.greek-abbr} ουτος δικαιος και ευλαβης προσδεχομενος παρακλησιν του [ισραηλ]{.greek-abbr} και [πνευμα]{.greek-abbr} ην αγιον επ αυτον[2:25]{.aside}

και ην αυτω κεχρηματισμενον υπο του [πνευματος]{.greek-abbr} του αγιου μη ιδειν θανατον πριν η ιδη τον [χριστον]{.greek-abbr} [κυριου]{.greek-abbr}[2:26]{.aside}

και ηλθεν εν τω [πνευματι]{.greek-abbr} εις το ιερον και εν τω εισαγαγειν τους γονεις το παιδιον [ιησουν]{.greek-abbr} του ποιησαι αυτους κατα το ειθισμενον του νομου περι αυτου[2:27]{.aside}

και αυτος εδεξατο [αυτο]{.greek-omitted} [αυτον]{.greek-added} εις τας αγκαλας αυτου και ευλογησεν τον [θεον]{.greek-abbr} και ειπεν[2:28]{.aside}

νυν απολυεις τον δουλον σου δεσποτα κατα το ρημα σου εν ειρηνη[2:29]{.aside}

οτι ειδον οι οφθαλμοι μου το [σωτηριον]{.greek-abbr} σου[2:30]{.aside}

ο ητοιμασας κατα προσωπον παντων των λαων[2:31]{.aside}

φως εις αποκαλυψιν εθνων και δοξαν λαου σου [ισραηλ]{.greek-abbr}[2:32]{.aside}

και ην ιωσηφ και η [μητηρ]{.greek-abbr} αυτου θαυμαζοντες επι τοις λαλουμενοις περι αυτου[2:33]{.aside}

και ευλογησεν αυτους συμεων και ειπεν προς μαριαμ την [μητερα]{.greek-abbr} αυτου ιδου ουτος κειται εις πτωσιν και αναστασιν πολλων εν τω [ισραηλ]{.greek-abbr} και εις σημειον αντιλεγομενον[2:34]{.aside}

και σου δε αυτης την ψυχην διελευσεται ρομφαια οπως αν αποκαλυφθωσιν εκ πολλων καρδιων διαλογισμοι[2:35]{.aside}

και ην αννα προφητις θυγατηρ φανουηλ εκ φυλης ασηρ αυτη προβεβηκυια εν ημεραις πολλαις ζησασα [ετη]{.greek-omitted} μετα ανδρος [ετη]{.greek-added} επτα απο της παρθενιας αυτης[2:36]{.aside}

και αυτη χηρα ως ετων ογδοηκοντα [τεσσαρων]{.greek-omitted} [τεσσα]{.greek-added} [ρων]{.greek-added} η ουκ αφιστατο απο του ιερου νηστειαις και [δεησεσιν]{.greek-omitted} [δεησεσι]{.greek-added} λατρευουσα νυκτα και ημεραν[2:37]{.aside}

και αυτη αυτη τη ωρα επιστασα [ανθωμολογειτο]{.greek-omitted} [ανθωμολογειτω]{.greek-added} τω [κυριω]{.greek-abbr} και ελαλει περι αυτου [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις προσδεχομενοις λυτρωσιν εν [ιερουσαλημ]{.greek-abbr}[2:38]{.aside}

και ως ετελεσαν απαντα τα κατα τον νομον [κυριου]{.greek-abbr} υπεστρεψαν εις την γαλιλαιαν εις την πολιν [εαυτων]{.greek-omitted} [αυτων]{.greek-added} [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added}[2:39]{.aside}

το δε παιδιον [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και εκραταιουτο [πνευματι]{.greek-abbr} πληρουμενον σοφιας και χαρις [θεου]{.greek-abbr} ην επ αυτο[2:40]{.aside}

και επορευοντο οι γονεις αυτου κατ ετος εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} τη εορτη του πασχα[2:41]{.aside}

και οτε εγενετο ετων δωδεκα αναβαντων αυτων εις ιεροσολυμα κατα το εθος της εορτης[2:42]{.aside}

και τελειωσαντων τας ημερας εν τω υποστρεφειν αυτους υπεμεινεν [ιησους]{.greek-abbr} ο παις εν ιερουσαλημ και ουκ εγνω ιωσηφ και η [μητηρ]{.greek-abbr} αυτου[2:43]{.aside}

νομισαντες δε αυτον εν τη συνοδια ειναι ηλθον ημερας οδον και [ανε]{.greek-added} [ανεζητουν]{.greek-omitted} [ζητουν]{.greek-added} αυτον εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} και εν τοις γνωστοις[2:44]{.aside}

και μη ευροντες αυτον υπεστρεψαν εις ιερουσαλημ ζητουντες αυτον[2:45]{.aside}

και εγενετο μεθ ημερας τρεις ευρον αυτον εν τω ιερω καθεζομενον εν μεσω των διδασκαλων και ακουοντα αυτων και επερωτωντα αυτους[2:46]{.aside}

εξισταντο δε παντες οι ακουοντες αυτου επι τη συνεσει και ταις αποκρισεσιν αυτου[2:47]{.aside}

και ιδοντες αυτον εξεπλαγησαν και προς αυτον η [μητηρ]{.greek-abbr} αυτου ειπεν τεκνον τι εποιησας ημιν ουτως ιδου ο [πατηρ]{.greek-abbr} σου καγω οδυνωμενοι εζητουμεν σε[2:48]{.aside}

και ειπεν προς αυτους τι οτι εζητειτε με ουκ ηδειτε οτι εν τοις του [πατρος]{.greek-abbr} μου δει ειναι με[2:49]{.aside}

και αυτοι ου συνηκαν το ρημα ο ελαλησεν αυτοις[2:50]{.aside}

και κατεβη μετ αυτων και ηλθεν εις [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} και ην υποτασσομενος αυτοις και η [μητηρ]{.greek-abbr} αυτου διετηρει παντα τα ρηματα ταυτα εν τη καρδια αυτης[2:51]{.aside}

και [ιησους]{.greek-abbr} [προεκοπτεν]{.greek-omitted} [προε]{.greek-added} [κοπτε]{.greek-added} σοφια και ηλικια και χαριτι παρα [θεω]{.greek-abbr} και [ανθρωποις]{.greek-abbr}[2:52]{.aside}

### Chapter 3

εν ετει δε πεντεκαιδεκατω της ηγεμονιας τιβεριου καισαρος ηγεμονευοντος ποντιου πιλατου της ιουδαιας και τετραρχουντος της γαλιλαιας ηρωδου φιλιππου δε του αδελφου αυτου τετραρχουντος της ιτουραιας και τραχωνιτιδος χωρας και λυσανιου της αβιληνης τετραρχουντος[3:1]{.aside}

επι αρχιερεως αννα και καιαφα εγενετο ρημα [θεου]{.greek-abbr} επι ιωαννην τον [του]{.greek-added} ζαχαριου [υιον]{.greek-abbr} εν τη ερημω[3:2]{.aside}

και ηλθεν εις πασαν την περιχωρον του ιορδανου κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[3:3]{.aside}

ως γεγραπται εν βιβλω λογων ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:4]{.aside}

πασα φαραγξ πληρωθησεται και παν ορος και βουνος ταπεινωθησεται και εσται τα σκολια εις ευθειαν και αι τραχειαι εις οδους λειας[3:5]{.aside}

και οψεται πασα σαρξ το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr}[3:6]{.aside}

ελεγεν ουν τοις εκπορευομενοις οχλοις βαπτισθηναι υπ αυτου γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν καρπους αξιους της μετανοιας και μη αρξησθε λεγειν εν εαυτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ[3:8]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[3:9]{.aside}

και επηρωτων αυτον οι οχλοι λεγοντες τι ουν ποιησομεν[3:10]{.aside}

αποκριθεις δε λεγει αυτοις ο εχων δυο χιτωνας μεταδοτω τω μη εχοντι και ο εχων βρωματα ομοιως ποιειτω[3:11]{.aside}

ηλθον δε και τελωναι [βαπτισθηναι]{.greek-omitted} [βαπτι]{.greek-added} [σθηναι]{.greek-added} και ειπον προς αυτον διδασκαλε τι ποιησομεν[3:12]{.aside}

ο δε ειπεν προς αυτους μηδεν πλεον παρα το διατεταγμενον υμιν πρασσετε[3:13]{.aside}

επηρωτων δε αυτον και στρατευομενοι λεγοντες και ημεις τι ποιησομεν και ειπεν προς αυτους μηδενα διασεισητε μηδε συκοφαντησητε και αρκεισθε τοις οψωνιοις υμων[3:14]{.aside}

προσδοκωντος δε του λαου και διαλογιζομενων παντων εν ταις καρδιαις αυτων περι του ιωαννου μηποτε αυτος ειη ο [χριστος]{.greek-abbr}[3:15]{.aside}

απεκρινατο ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [απασιν]{.greek-omitted} [απασι]{.greek-added} λεγων εγω μεν υδατι βαπτιζω υμας ερχεται δε ο ισχυροτερος μου ου ουκ ειμι ικανος λυσαι τον ιμαντα των υποδηματων αυτου αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω και πυρι[3:16]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον εις την αποθηκην αυτου το δε αχυρον [κατα]{.greek-added} [κατακαυσει]{.greek-omitted} [καυσει]{.greek-added} πυρι ασβεστω[3:17]{.aside}

πολλα μεν ουν και ετερα παρακαλων ευηγγελιζετο τον λαον[3:18]{.aside}

ο δε ηρωδης ο τετραρχης ελεγχομενος υπ αυτου περι ηρωδιαδος της γυναικος του αδελφου αυτου και περι παντων ων εποιησεν πονηρων ο ηρωδης[3:19]{.aside}

[προσεθηκεν]{.greek-omitted} [προσεθηκε]{.greek-added} και τουτο επι [πασιν]{.greek-omitted} [πασι]{.greek-added} και [κατεκλεισεν]{.greek-omitted} [κατεκλεισε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εν τη φυλακη[3:20]{.aside}

εγενετο δε εν τω βαπτισθηναι απαντα τον λαον και [ιησου]{.greek-abbr} βαπτισθεντος και προσευχομενου ανεωχθηναι τον [ουρανον]{.greek-abbr}[3:21]{.aside}

και καταβηναι το [πνευμα]{.greek-abbr} το αγιον σωματικω ειδει ωσει περιστεραν επ αυτον και φωνην εξ ουρανου γενεσθαι λεγουσαν συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν σοι [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[3:22]{.aside}

και αυτος ην ο [ιησους]{.greek-abbr} ωσει ετων τριακοντα αρχομενος ων ως ενομιζετο [υιος]{.greek-abbr} ιωσηφ του [ηλι]{.greek-omitted} [ηλει]{.greek-added}[3:23]{.aside}

του [ματθατ]{.greek-omitted} [ματθα]{.greek-added} του λευι του μελχι του ιαννα του ιωσηφ[3:24]{.aside}

του ματταθιου του αμως του ναουμ του [εσλι]{.greek-omitted} [εσλει]{.greek-added} του ναγγαι[3:25]{.aside}

του μααθ του ματταθιου του σεμει του ιωσηφ του ιουδα[3:26]{.aside}

του [ιωαναν]{.greek-omitted} [ιωαννα]{.greek-added} του ρησα του ζοροβαβελ του σαλαθιηλ του [νηρι]{.greek-omitted} [νηρει]{.greek-added}[3:27]{.aside}

του μελχι του [αδδι]{.greek-omitted} [αδδει]{.greek-added} του κωσαμ του ελμωδαμ του ηρ[3:28]{.aside}

του ιωση του ελιεζερ του ιωρειμ του [ματθατ]{.greek-omitted} [ματθα]{.greek-added} του λευι[3:29]{.aside}

του συμεων του ιουδα του ιωσηφ του ιωναν του ελιακειμ[3:30]{.aside}

του μελεα του μαιναν του ματταθα του ναθαν του [δαυιδ]{.greek-abbr}[3:31]{.aside}

του ιεσσαι του ωβηδ του βοοζ του σαλμων του ναασσων[3:32]{.aside}

του [αμιναδαβ]{.greek-omitted} [αμιναδαμ]{.greek-added} του αραμ [του]{.greek-added} [ιωραμ]{.greek-added} του εσρωμ του φαρες του ιουδα[3:33]{.aside}

του ιακωβ του ισαακ του αβρααμ του [θαρα]{.greek-omitted} [θαρρα]{.greek-added} του ναχωρ[3:34]{.aside}

του σερουχ του ραγαυ του [φαλεγ]{.greek-omitted} [φαλεκ]{.greek-added} του εβερ του σαλα[3:35]{.aside}

του [καιναν]{.greek-omitted} [καινα]{.greek-added} του αρφαξαδ του σημ του νωε του λαμεχ[3:36]{.aside}

του μαθουσαλα του ενωχ του ιαρεδ του μαλελεηλ του καιναν[3:37]{.aside}

του ενως του σηθ του αδαμ του [θεου]{.greek-abbr}[3:38]{.aside}

### Chapter 4

[ιησους]{.greek-abbr} δε [πνευματος]{.greek-abbr} αγιου πληρης υπεστρεψεν απο του ιορδανου και ηγετο εν τω [πνευματι]{.greek-abbr} εις την ερημον[4:1]{.aside}

ημερας τεσσαρακοντα πειραζομενος υπο του διαβολου και ουκ εφαγεν ουδεν εν ταις ημεραις εκειναις και συντελεσθεισων αυτων υστερον επεινασεν[4:2]{.aside}

και ειπεν αυτω ο [δια]{.greek-added} [διαβολος]{.greek-omitted} [βολος]{.greek-added} ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} ειπε τω λιθω τουτω ινα γενηται αρτος[4:3]{.aside}

και απεκριθη [ιησους]{.greek-abbr} προς αυτον λεγων γεγραπται οτι ουκ επ αρτω μονω ζησεται [ανθρωπος]{.greek-abbr} αλλ επι παντι ρηματι [θεου]{.greek-abbr}[4:4]{.aside}

και αναγαγων αυτον ο διαβολος εις ορος υψηλον εδειξεν αυτω πασας τας βασιλειας της οικουμενης εν στιγμη χρονου[4:5]{.aside}

και ειπεν αυτω ο διαβολος σοι δωσω την εξουσιαν ταυτην απασαν και την δοξαν αυτων οτι εμοι παραδεδοται και ω εαν θελω διδωμι αυτην[4:6]{.aside}

συ ουν εαν προσκυνησης ενωπιον [εμου]{.greek-omitted} [μου]{.greek-added} εσται σου πασα[4:7]{.aside}

και αποκριθεις αυτω ειπεν ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται προσκυνησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου και αυτω μονω λατρευσεις[4:8]{.aside}

και ηγαγεν αυτον εις [ιερουσαλημ]{.greek-abbr} και εστησεν αυτον επι το πτερυγιον του ιερου και ειπεν αυτω ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} βαλε σεαυτον εντευθεν κατω[4:9]{.aside}

γεγραπται γαρ οτι τοις αγγελοις αυτου εντελειται περι σου του διαφυλαξαι σε[4:10]{.aside}

και [οτι]{.greek-added} επι χειρων [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:11]{.aside}

και αποκριθεις ειπεν αυτω ο [ιησους]{.greek-abbr} οτι ειρηται ουκ εκπειρασεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:12]{.aside}

και συντελεσας παντα πειρασμον ο διαβολος απεστη απ αυτου αχρι καιρου[4:13]{.aside}

και υπεστρεψεν ο [ιησους]{.greek-abbr} εν τη δυναμει του [πνευματος]{.greek-abbr} εις την γαλιλαιαν και φημη [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} καθ ολης της περιχωρου περι αυτου[4:14]{.aside}

και αυτος εδιδασκεν εν ταις συναγωγαις αυτων δοξαζομενος υπο παντων[4:15]{.aside}

και ηλθεν εις την [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ου ην τεθραμμενος και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} κατα το ειωθος αυτω εν τη ημερα των σαββατων εις την συναγωγην και ανεστη αναγνωναι[4:16]{.aside}

και επεδοθη αυτω βιβλιον ησαιου του προφητου και αναπτυξας το βιβλιον [ευρεν]{.greek-omitted} [ευρε]{.greek-added} τον τοπον ου ην γεγραμμενον[4:17]{.aside}

[πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} επ εμε ου [ει]{.greek-added} [εινεκεν]{.greek-omitted} [νεκεν]{.greek-added} [εχρισεν]{.greek-omitted} [εχρισε]{.greek-added} με ευαγγελισασθαι πτωχοις [απεσταλκεν]{.greek-omitted} [απεσταλκε]{.greek-added} με ιασασθαι τους συντετριμμενους την καρδιαν κηρυξαι αιχμαλωτοις αφεσιν και τυφλοις αναβλεψιν αποστειλαι τεθραυσμενους εν αφεσει[4:18]{.aside}

κηρυξαι ενιαυτον [κυριου]{.greek-abbr} δεκτον[4:19]{.aside}

και πτυξας το βιβλιον αποδους τω υπηρετη εκαθισεν και παντων εν τη συναγωγη οι οφθαλμοι ησαν ατενιζοντες αυτω[4:20]{.aside}

ηρξατο δε λεγειν προς αυτους οτι σημερον πεπληρωται η γραφη αυτη εν τοις ωσιν υμων[4:21]{.aside}

και παντες εμαρτυρουν αυτω και εθαυμαζον επι τοις λογοις της χαριτος τοις εκπορευομενοις εκ του στοματος αυτου και ελεγον [ουχ]{.greek-omitted} [ουχι]{.greek-added} ουτος εστιν ο [υιος]{.greek-abbr} ιωσηφ[4:22]{.aside}

και ειπεν προς αυτους παντως ερειτε μοι την παραβολην ταυτην ιατρε θεραπευσον σεαυτον οσα ηκουσαμεν γενομενα εν τη καπερναουμ ποιησον [ωδε]{.greek-added} και [ωδε]{.greek-omitted} εν τη πατριδι σου[4:23]{.aside}

ειπεν δε αμην [υμιν]{.greek-added} λεγω [υμιν]{.greek-omitted} οτι ουδεις προφητης δεκτος εστιν εν τη πατριδι αυτου[4:24]{.aside}

επ αληθειας δε λεγω υμιν πολλαι χηραι ησαν εν ταις ημεραις ηλιου εν τω [ισραηλ]{.greek-abbr} οτε εκλεισθη ο [ουρανος]{.greek-abbr} επι ετη τρια και μηνας εξ ως εγενετο λιμος μεγας επι πασαν την γην[4:25]{.aside}

και προς ουδεμιαν αυτων επεμφθη ηλιας ει μη εις σαρεπτα της σιδωνος προς γυναικα χηραν[4:26]{.aside}

και πολλοι λεπροι ησαν επι ελισσαιου του προφητου εν τω [ισραηλ]{.greek-abbr} και ουδεις αυτων εκαθαρισθη ει μη νεεμαν ο συρος[4:27]{.aside}

και επλησθησαν παντες θυμου εν τη συναγωγη ακουοντες ταυτα[4:28]{.aside}

και ανασταντες εξεβαλον αυτον εξω της πολεως και ηγαγον αυτον εως οφρυος του ορους εφ ου η πολις αυτων ωκοδομητο εις το [κατακρημνισαι]{.greek-omitted} [κατακριμνησαι]{.greek-added} αυτον[4:29]{.aside}

αυτος δε διελθων δια μεσου αυτων επορευετο[4:30]{.aside}

και κατηλθεν εις καπερναουμ πολιν της γαλιλαιας και ην διδασκων αυτους εν τοις [σαββασιν]{.greek-omitted} [σαββα]{.greek-added} [σι]{.greek-added}[4:31]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου οτι εν εξουσια ην ο λογος αυτου[4:32]{.aside}

και εν τη συναγωγη ην [ανθρωπος]{.greek-abbr} εχων [πνευμα]{.greek-abbr} δαιμονιου ακαθαρτου και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added} φωνη μεγαλη [λεγων]{.greek-added}[4:33]{.aside}

[λεγων]{.greek-omitted} εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[4:34]{.aside}

και επετιμησεν [αυτω]{.greek-omitted} [αυτο]{.greek-added} ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου και ριψαν αυτον το δαιμονιον εις μεσον εξηλθεν απ αυτου μηδεν βλαψαν αυτον[4:35]{.aside}

και εγενετο θαμβος επι παντας και συνελαλουν προς αλληλους λεγοντες τις ο λογος ουτος οτι εν εξουσια και δυναμει επιτασσει τοις ακαθαρτοις [πνευμασιν]{.greek-omitted} [[πνασι]{.greek-abbr}]{.greek-added} και εξερχονται[4:36]{.aside}

και εξεπορευετο ηχος περι αυτου εις παντα τοπον της περιχωρου[4:37]{.aside}

αναστας δε εκ της συναγωγης εισηλθεν εις την οικιαν σιμωνος πενθερα δε του σιμωνος ην συνεχομενη πυρετω μεγαλω και ηρωτησαν αυτον περι αυτης[4:38]{.aside}

και επιστας επανω αυτης [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πυρετω και αφηκεν αυτην παραχρημα δε αναστασα διηκονει αυτοις[4:39]{.aside}

δυνοντος δε του ηλιου παντες οσοι ειχον ασθενουντας νοσοις ποικιλαις ηγαγον αυτους προς αυτον ο δε ενι εκαστω αυτων τας χειρας [επιθεις]{.greek-omitted} [επιτιθεις]{.greek-added} [εθεραπευσεν]{.greek-omitted} [εθεραπευεν]{.greek-added} αυτους[4:40]{.aside}

εξηρχετο δε και δαιμονια απο πολλων κραζοντα και λεγοντα οτι συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} και επιτιμων ουκ εια αυτα λαλειν οτι ηδεισαν τον [χριστον]{.greek-abbr} αυτον ειναι[4:41]{.aside}

γενομενης δε ημερας εξελθων επορευθη εις [ερημον]{.greek-omitted} [ετερον]{.greek-added} τοπον και οι οχλοι επεζητουν αυτον και [ηλθον]{.greek-omitted} [εξηλθον]{.greek-added} εως αυτου και κατειχον αυτον του μη πορευεσθαι απ αυτων[4:42]{.aside}

ο δε ειπεν προς αυτους οτι και [εν]{.greek-added} ταις ετεραις πολεσιν ευαγγελισασθαι με δει την βασιλειαν του [θεου]{.greek-abbr} οτι εις τουτο [απεσταλμαι]{.greek-omitted} [απεσταλην]{.greek-added}[4:43]{.aside}

και ην κηρυσσων εν ταις συναγωγαις της γαλιλαιας[4:44]{.aside}

### Chapter 5

εγενετο δε εν τω τον οχλον επικεισθαι αυτω του ακουειν τον λογον του [θεου]{.greek-abbr} και αυτος ην [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εστως παρα την λιμνην γεννησαρετ[5:1]{.aside}

και ειδεν δυο πλοια εστωτα παρα την λιμνην οι δε αλιεις αποβαντες απ αυτων [απεπλυναν]{.greek-omitted} [απεπλυνον]{.greek-added} τα δικτυα[5:2]{.aside}

εμβας δε εις εν των πλοιων ο ην του σιμωνος ηρωτησεν αυτον απο της γης επαναγαγειν ολιγον και καθισας εδιδασκεν εκ του πλοιου τους οχλους[5:3]{.aside}

ως δε επαυσατο λαλων ειπεν προς τον σιμωνα επαναγαγε εις το βαθος και χαλασατε τα δικτυα υμων εις αγραν[5:4]{.aside}

και αποκριθεις ο σιμων ειπεν αυτω επιστατα δι ολης της νυκτος κοπιασαντες ουδεν ελαβομεν επι δε τω ρηματι σου χαλασω το δικτυον[5:5]{.aside}

και τουτο ποιησαντες [συνεκλεισαν]{.greek-omitted} [συνελαβον]{.greek-added} πληθος ιχθυων πολυ διερρηγνυτο δε το δικτυον αυτων[5:6]{.aside}

και κατενευσαν τοις μετοχοις τοις εν τω ετερω πλοιω του ελθοντας συλλαβεσθαι αυτοις και ηλθον και επλησαν αμφοτερα τα πλοια ωστε βυθιζεσθαι αυτα[5:7]{.aside}

ιδων δε σιμων πετρος [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} τοις γονασιν [ιησου]{.greek-abbr} λεγων εξελθε απ εμου οτι ανηρ αμαρτωλος ειμι [κυριε]{.greek-abbr}[5:8]{.aside}

θαμβος γαρ περιεσχεν αυτον και παντας τους συν αυτω επι τη αγρα των ιχθυων η συνελαβον[5:9]{.aside}

ομοιως δε και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} υιους ζεβεδαιου οι ησαν κοινωνοι τω σιμωνι και ειπεν προς τον σιμωνα ο [ιησους]{.greek-abbr} μη φοβου απο του νυν [ανθρωπους]{.greek-abbr} εση ζωγρων[5:10]{.aside}

και καταγαγοντες τα πλοια επι την γην αφεντες απαντα ηκολουθησαν αυτω[5:11]{.aside}

και εγενετο εν τω ειναι αυτον εν μια των πολεων και ιδου ανηρ πληρης λεπρας και ιδων τον [ιησουν]{.greek-abbr} πεσων επι προσωπον εδεηθη αυτου λεγων [κυριε]{.greek-abbr} εαν θελης δυνασαι με καθαρισαι[5:12]{.aside}

και εκτεινας την χειρα ηψατο αυτου ειπων [θελω]{.greek-omitted} [θε]{.greek-added} [λω]{.greek-added} καθαρισθητι και ευθεως η λεπρα απηλθεν απ αυτου[5:13]{.aside}

και αυτος παρηγγειλεν αυτω μηδενι ειπειν αλλα απελθων δειξον σεαυτον τω ιερει και προσενεγκε περι του καθαρισμου σου καθως [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[5:14]{.aside}

διηρχετο δε μαλλον ο λογος περι αυτου και συνηρχοντο οχλοι πολλοι ακουειν και θεραπευεσθαι υπ αυτου απο των ασθενειων αυτων[5:15]{.aside}

αυτος δε ην υποχωρων εν ταις ερημοις και προσευχομενος[5:16]{.aside}

και εγενετο εν μια των ημερων και αυτος ην διδασκων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} και ησαν καθημενοι φαρισαιοι και νομοδιδασκαλοι οι ησαν εληλυθοτες εκ πασης κωμης της γαλιλαιας και ιουδαιας και [ιερουσαλημ]{.greek-abbr} και δυναμις [κυριου]{.greek-abbr} ην εις το ιασθαι αυτους[5:17]{.aside}

και ιδου ανδρες φεροντες επι κλινης [ανθρωπον]{.greek-abbr} ος ην παραλελυμενος και εζητουν αυτον εισενεγκειν και θειναι ενωπιον αυτου[5:18]{.aside}

και μη ευροντες ποιας εισενεγκωσιν αυτον δια τον οχλον αναβαντες επι το δωμα δια των κεραμων καθηκαν αυτον συν τω κλινιδιω εις το μεσον εμπροσθεν του [ιησου]{.greek-abbr}[5:19]{.aside}

και ιδων την πιστιν αυτων ειπεν αυτω [ανθρωπε]{.greek-abbr} αφεωνται σοι αι αμαρτιαι σου[5:20]{.aside}

και ηρξαντο διαλογιζεσθαι οι γραμματεις και οι φαρισαιοι λεγοντες τις εστιν ουτος ος λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη μονος ο [θεος]{.greek-abbr}[5:21]{.aside}

επιγνους δε ο [ιησους]{.greek-abbr} τους διαλογισμους αυτων αποκριθεις ειπεν προς αυτους τι διαλογιζεσθε εν ταις καρδιαις υμων[5:22]{.aside}

τι εστιν ευκοπωτερον ειπειν αφεωνται σοι αι αμαρτιαι σου η ειπειν εγειραι και περιπατει[5:23]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας ειπεν τω παραλελυμενω σοι λεγω εγειραι και αρας το κλινιδιον σου πορευου εις τον οικον σου[5:24]{.aside}

και παραχρημα αναστας ενωπιον αυτων αρας εφ ο κατεκειτο απηλθεν εις τον οικον αυτου δοξαζων τον [θεον]{.greek-abbr}[5:25]{.aside}

και εκστασις ελαβεν απαντας και εδοξαζον τον [θεον]{.greek-abbr} και επλησθησαν [φοβου]{.greek-omitted} [θαμβους]{.greek-added} λεγοντες οτι ειδομεν παραδοξα σημερον[5:26]{.aside}

και μετα ταυτα [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εθεασατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τελωνην ονοματι λευιν καθημενον επι το τελωνιον και ειπεν αυτω ακολουθει μοι[5:27]{.aside}

και καταλιπων απαντα αναστας ηκολουθησεν αυτω[5:28]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δοχην μεγαλην λευις αυτω εν τη οικια αυτου και ην οχλος τελωνων πολυς και αλλων οι ησαν μετ αυτων κατακειμενοι[5:29]{.aside}

και εγογγυζον οι γραμματεις αυτων και οι φαρισαιοι προς τους μαθητας αυτου λεγοντες δια τι μετα των τελωνων και αμαρτωλων εσθιετε και πινετε[5:30]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν προς αυτους ου χρειαν εχουσιν οι [υγιαινοντες]{.greek-omitted} [υγιαινον]{.greek-added} [τες]{.greek-added} ιατρου αλλ οι κακως [εχοντες]{.greek-omitted} [πασχοντες]{.greek-added}[5:31]{.aside}

ουκ εληλυθα καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[5:32]{.aside}

οι δε ειπον προς αυτον δια τι οι μαθηται ιωαννου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added} πυκνα και δεησεις ποιουνται ομοιως και οι των φαρισαιων οι δε σοι [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και πινουσιν[5:33]{.aside}

ο δε ειπεν προς αυτους μη δυνασθε τους υιους του νυμφωνος εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} ποιησαι νηστευειν[5:34]{.aside}

ελευσονται δε ημεραι και οταν απαρθη απ αυτων ο νυμφιος τοτε [νηστευσουσιν]{.greek-omitted} [νηστευουσιν]{.greek-added} εν εκειναις ταις ημεραις[5:35]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε και παραβολην προς αυτους οτι ουδεις επιβλημα ιματιου καινου επιβαλλει επι ιματιον παλαιον ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} και το καινον σχιζει και τω παλαιω ου συμφωνει το απο του καινου[5:36]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηξει ο [οινος]{.greek-added} [ο]{.greek-added} νεος [οινος]{.greek-omitted} τους ασκους και αυτος εκχυθησεται και οι ασκοι απολουνται[5:37]{.aside}

αλλα οινον νεον εις ασκους καινους βλητεον και αμφοτεροι συντηρουνται[5:38]{.aside}

και ουδεις πιων παλαιον ευθεως θελει νεον λεγει γαρ ο παλαιος χρηστοτερος εστιν[5:39]{.aside}

### Chapter 6

εγενετο δε εν σαββατω δευτεροπρωτω διαπορευεσθαι αυτον δια των σποριμων και ετιλλον οι μαθηται αυτου τους σταχυας και ησθιον ψωχοντες ταις [χερσιν]{.greek-omitted} [χερσι]{.greek-added}[6:1]{.aside}

τινες δε των φαρισαιων ειπον [προς]{.greek-added} [αυτοις]{.greek-omitted} [αυτους]{.greek-added} τι ποιειτε ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ποιειν εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added}[6:2]{.aside}

και αποκριθεις [ειπεν]{.greek-added} προς αυτους [ειπεν]{.greek-omitted} ο [ιησους]{.greek-abbr} ουδε τουτο ανεγνωτε ο [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οποτε επεινασεν αυτος και οι μετ αυτου οντες[6:3]{.aside}

ως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και [εφαγεν]{.greek-omitted} [εφαγε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις μετ αυτου ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη μονους τους ιερεις[6:4]{.aside}

και ελεγεν αυτοις οτι κυριος εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[6:5]{.aside}

εγενετο δε και [εν]{.corr} ετερω σαββατω εισελθειν αυτον εις την συναγωγην και διδασκειν και ην εκει [ανθρωπος]{.greek-abbr} και η χειρ αυτου η δεξια ην ξηρα[6:6]{.aside}

παρετηρουν δε οι γραμματεις και οι φαρισαιοι ει εν τω σαββατω θεραπευσει ινα [ευρωσιν]{.greek-omitted} [ευρωσι]{.greek-added} κατηγοριαν αυτου[6:7]{.aside}

αυτος δε ηδει τους διαλογισμους αυτων και ειπεν τω [ανθρωπω]{.greek-abbr} τω ξηραν εχοντι την χειρα εγειραι και στηθι εις το μεσον ο δε αναστας εστη[6:8]{.aside}

ειπεν ουν ο [ιησους]{.greek-abbr} προς αυτους επερωτησω υμας τι [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι[6:9]{.aside}

και περιβλεψαμενος παντας αυτους ειπεν αυτω εκτεινον την χειρα σου ο δε εποιησεν και αποκατεσταθη η χειρ αυτου υγιης ως η αλλη[6:10]{.aside}

αυτοι δε επλησθησαν ανοιας και διελαλουν προς αλληλους τι αν ποιησειαν τω [ιησου]{.greek-abbr}[6:11]{.aside}

εγενετο δε εν ταις ημεραις [ταυταις]{.greek-omitted} [ταυ]{.greek-added} [ταις]{.greek-added} εξηλθεν εις το ορος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} προσευξασθαι και ην διανυκτερευων εν τη προσευχη του [θεου]{.greek-abbr}[6:12]{.aside}

και οτε εγενετο ημερα [προσεφωνησεν]{.greek-omitted} [προσεφωνησε]{.greek-added} τους μαθητας αυτου και εκλεξαμενος απ αυτων δωδεκα ους και αποστολους ωνομασεν[6:13]{.aside}

σιμωνα ον και [ωνομασεν]{.greek-omitted} [ωνομασε]{.greek-added} πετρον και ανδρεαν τον αδελφον αυτου ιακωβον και ιωαννην φιλιππον και βαρθολομαιον[6:14]{.aside}

ματθαιον και θωμαν ιακωβον τον του αλφαιου και σιμωνα τον καλουμενον ζηλωτην[6:15]{.aside}

ιουδαν ιακωβου και ιουδαν ισκαριωτην ος και εγενετο προδοτης[6:16]{.aside}

και καταβας μετ αυτων εστη επι [τοπου]{.greek-omitted} [του]{.greek-added} πεδινου και οχλος μαθητων αυτου και πληθος πολυ του λαου απο πασης της ιουδαιας και [ιερουσαλημ]{.greek-abbr} και της παραλιου τυρου και σιδωνος [οι]{.greek-omitted} [ηλθον]{.greek-omitted} [ακουσαι]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ιαθηναι]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [νοσων]{.greek-omitted} [αυτων]{.greek-omitted}[6:17]{.aside}

[οι]{.greek-added} [ηλθον]{.greek-added} [ακουσαι]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [ιαθηναι]{.greek-added} [απο]{.greek-added} [των]{.greek-added} [νοσων]{.greek-added} [αυτων]{.greek-added} και οι οχλουμενοι [υπο]{.greek-omitted} [απο]{.greek-added} πνευματων ακαθαρτων [και]{.greek-omitted} εθεραπευοντο[6:18]{.aside}

και πας ο οχλος εζητει απτεσθαι αυτου οτι δυναμις παρ αυτου εξηρχετο και ιατο παντας[6:19]{.aside}

και αυτος επαρας τους οφθαλμους αυτου εις τους μαθητας αυτου ελεγεν μακαριοι οι πτωχοι οτι υμετερα εστιν η βασιλεια του [θεου]{.greek-abbr}[6:20]{.aside}

μακαριοι οι πεινωντες [ο]{.greek-added} [νυν]{.corr} οτι χορτασθησεσθε μακαριοι οι κλαιοντες νυν οτι γελασετε[6:21]{.aside}

μακαριοι εστε οταν μισησωσιν υμας οι [ανθρωποι]{.greek-abbr} και οταν αφορισωσιν υμας και [ονειδισωσιν]{.greek-omitted} [ονειδισωσι]{.greek-added} και [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} το ονομα υμων ως πονηρον ενεκα του υιου του [ανθρωπου]{.greek-abbr}[6:22]{.aside}

χαρητε εν εκεινη τη ημερα και σκιρτησατε ιδου γαρ ο μισθος υμων πολυς εν τω [ουρανω]{.greek-abbr} κατα ταυτα γαρ εποιουν τοις προφηταις οι [πατερες]{.greek-abbr} αυτων[6:23]{.aside}

πλην ουαι υμιν τοις πλουσιοις οτι απεχετε την παρακλησιν υμων[6:24]{.aside}

ουαι υμιν οι [εμπεπλησμενοι]{.greek-omitted} [εμπεπλησμε]{.greek-added} [νοι]{.greek-added} οτι πεινασετε ουαι υμιν οι γελωντες νυν οτι πενθησετε και κλαυσετε[6:25]{.aside}

ουαι οταν καλως [ειπωσιν]{.greek-added} υμας [ειπωσιν]{.greek-omitted} [παντες]{.greek-added} οι [ανθρωποι]{.greek-abbr} κατα ταυτα γαρ εποιουν τοις ψευδοπροφηταις οι [πατερες]{.greek-abbr} αυτων[6:26]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υμιν λεγω τοις ακουουσιν αγαπατε τους εχθρους υμων καλως ποιειτε τοις μισουσιν υμας[6:27]{.aside}

ευλογειτε τους καταρωμενους [υμιν]{.greek-omitted} [υμας]{.greek-added} [και]{.greek-added} προσευχεσθε υπερ των επηρεαζοντων υμας[6:28]{.aside}

τω τυπτοντι σε επι την σιαγονα παρεχε και την αλλην και απο του αιροντος σου το ιματιον και τον χιτωνα μη κωλυσης[6:29]{.aside}

παντι δε τω αιτουντι σε διδου και απο του αιροντος τα σα μη απαιτει[6:30]{.aside}

και καθως θελετε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} και υμεις ποιειτε αυτοις ομοιως[6:31]{.aside}

και ει αγαπατε τους αγαπωντας υμας ποια υμιν χαρις [εστιν]{.greek-omitted} [εστι]{.greek-added} και γαρ οι αμαρτωλοι τους αγαπωντας [αυ]{.greek-added} [αυτους]{.greek-omitted} [τους]{.greek-added} [αγαπωσιν]{.greek-omitted} [αγαπωσι]{.greek-added}[6:32]{.aside}

και εαν αγαθοποιητε τους αγαθοποιουντας υμας ποια υμιν χαρις [εστιν]{.greek-omitted} [εστι]{.greek-added} και γαρ οι αμαρτωλοι το αυτο [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[6:33]{.aside}

και εαν δανειζητε παρ ων ελπιζετε απολαβειν ποια υμιν χαρις [εστιν]{.greek-omitted} [εστι]{.greek-added} και γαρ αμαρτωλοι αμαρτωλοις δανειζουσιν ινα [απολαβωσιν]{.greek-omitted} [απολαβωσι]{.greek-added} τα ισα[6:34]{.aside}

πλην αγαπατε τους εχθρους υμων και αγαθοποιειτε και δανειζετε μηδεν απελπιζοντες και εσται ο μισθος υμων πολυς και εσεσθε υιοι υψιστου οτι αυτος χρηστος εστιν επι τους αχαριστους και πονηρους[6:35]{.aside}

γινεσθε ουν οικτιρμονες καθως και ο [πατηρ]{.greek-abbr} υμων οικτιρμων [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:36]{.aside}

και μη κρινετε και ου μη κριθητε μη [καταδικαζετε]{.greek-omitted} [καταδικαζητε]{.greek-added} και ου μη καταδικασθητε απολυετε και απολυθησεσθε[6:37]{.aside}

διδοτε και δοθησεται υμιν μετρον καλον πεπιεσμενον και σεσαλευμενον και υπερεκχυνομενον δωσουσιν εις τον κολπον υμων τω γαρ αυτω μετρω ω μετρειτε αντιμετρηθησεται υμιν[6:38]{.aside}

ειπεν δε παραβολην αυτοις [μητι]{.greek-omitted} [μη]{.greek-added} δυναται τυφλος τυφλον οδηγειν ουχι αμφοτεροι εις βοθυνον πεσουνται[6:39]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης υπερ τον διδασκαλον αυτου κατηρτισμενος δε πας εσται ως ο διδασκαλος αυτου[6:40]{.aside}

τι δε βλεπεις το καρφος το εν τω οφθαλμω του αδελφου σου την δε δοκον την εν τω ιδιω οφθαλμω ου κατανοεις[6:41]{.aside}

η πως δυνασαι λεγειν τω αδελφω σου αδελφε αφες εκβαλω το καρφος το εν τω οφθαλμω σου αυτος την εν τω οφθαλμω σου δοκον ου βλεπων υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος το εν τω οφθαλμω του αδελφου σου[6:42]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} δενδρον καλον ποιουν καρπον σαπρον ουδε δενδρον σαπρον ποιουν καρπον καλον[6:43]{.aside}

εκαστον γαρ δενδρον εκ του ιδιου καρπου γινωσκεται ου γαρ εξ ακανθων [συλλεγουσιν]{.greek-omitted} [συλλεγουσι]{.greek-added} συκα ουδε εκ βατου [τρυγωσιν]{.greek-omitted} [τρυγωσι]{.greek-added} σταφυλην[6:44]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου της καρδιας αυτου προφερει το αγαθον και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου της καρδιας αυτου προφερει το πονηρον εκ γαρ του περισσευματος της καρδιας λαλει το στομα αυτου[6:45]{.aside}

τι δε με καλειτε [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} και ου ποιειτε α λεγω[6:46]{.aside}

πας ο ερχομενος προς με και ακουων μου των λογων και ποιων αυτους υποδειξω υμιν τινι εστιν ομοιος[6:47]{.aside}

ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδομουντι οικιαν ος [εσκαψεν]{.greek-omitted} [εσκαψε]{.greek-added} και [εβαθυνεν]{.greek-omitted} [εβαθυνε]{.greek-added} και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} θεμελιον επι την πετραν πλημμυρας δε γενομενης προσερρηξεν ο ποταμος τη οικια εκεινη και ουκ [ισχυσεν]{.greek-omitted} [ισχυσε]{.greek-added} σαλευσαι αυτην τεθεμελιωτο γαρ επι την πετραν[6:48]{.aside}

ο δε ακουσας και μη ποιησας ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδομησαντι οικιαν επι την γην χωρις θεμελιου η προσερρηξεν ο ποταμος και ευθεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και εγενετο το ρηγμα της οικιας εκεινης μεγα[6:49]{.aside}

### Chapter 7

[επει]{.greek-omitted} [οτε]{.greek-added} δε [επληρωσεν]{.greek-omitted} [επληρωσε]{.greek-added} παντα τα ρηματα αυτου εις τας ακοας του λαου εισηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις καπερναουμ[7:1]{.aside}

εκατονταρχου δε τινος δουλος κακως εχων [εμελλεν]{.greek-omitted} [ημελλε]{.greek-added} τελευταν ος ην αυτω εντιμος[7:2]{.aside}

ακουσας δε περι του [ιησου]{.greek-abbr} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτον πρεσβυτερους των ιουδαιων ερωτων αυτον οπως ελθων διασωση τον δουλον αυτου[7:3]{.aside}

οι δε παραγενομενοι προς τον [ιησουν]{.greek-abbr} παρεκαλουν αυτον σπουδαιως λεγοντες [αυτω]{.greek-added} οτι αξιος εστιν ω παρεξει τουτο[7:4]{.aside}

αγαπα γαρ το εθνος ημων και την συναγωγην αυτος ωκοδομησεν ημιν[7:5]{.aside}

ο δε [ιησους]{.greek-abbr} επορευετο συν αυτοις ηδη δε αυτου ου μακραν απεχοντος απο της οικιας [επεμψεν]{.greek-omitted} [επεμψε]{.greek-added} προς αυτον ο εκατονταρχος φιλους λεγων αυτω [κυριε]{.greek-abbr} μη [σκυλλου]{.greek-omitted} [σκυλου]{.greek-added} ου γαρ ειμι ικανος ινα [μου]{.greek-added} υπο την στεγην [μου]{.greek-omitted} εισελθης[7:6]{.aside}

διο ουδε εμαυτον ηξιωσα προς σε ελθειν αλλ ειπε λογω και ιαθησεται ο παις μου[7:7]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν τασσομενος εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[7:8]{.aside}

ακουσας δε ταυτα ο [ιησους]{.greek-abbr} εθαυμασεν αυτον και στραφεις τω ακολουθουντι αυτω οχλω ειπεν λεγω υμιν ουτε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[7:9]{.aside}

και υποστρεψαντες οι πεμφθεντες εις τον οικον ευρον τον ασθενουντα δουλον υγιαινοντα[7:10]{.aside}

και εγενετο εν τω εξης επορευετο εις πολιν καλουμενην ναιν και [συνεπορευοντο]{.greek-omitted} [συνεπορευ]{.greek-added} [οντο]{.greek-added} αυτω οι μαθηται αυτου ικανοι και οχλος πολυς[7:11]{.aside}

ως δε [ηγγισεν]{.greek-omitted} [ηγγισε]{.greek-added} τη πυλη της πολεως και ιδου εξεκομιζετο τεθνηκως [υιος]{.greek-abbr} μονογενης τη [μητρι]{.greek-abbr} αυτου και αυτη χηρα και οχλος [της]{.greek-omitted} [πολεως]{.greek-omitted} ικανος συν αυτη[7:12]{.aside}

και ιδων αυτην ο [κυριος]{.greek-abbr} εσπλαγχνισθη επ αυτη και ειπεν αυτη μη κλαιε[7:13]{.aside}

και προσελθων ηψατο της σορου οι δε βασταζοντες εστησαν και ειπεν νεανισκε σοι λεγω εγερθητι[7:14]{.aside}

και [ανεκαθισεν]{.greek-omitted} [ανεκαθησεν]{.greek-added} ο νεκρος και ηρξατο λαλειν και εδωκεν αυτον τη [μητρι]{.greek-abbr} αυτου[7:15]{.aside}

[ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} δε φοβος παντας και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες οτι προφητης μεγας εγηγερται εν ημιν και οτι επεσκεψατο ο [θεος]{.greek-abbr} τον λαον αυτου[7:16]{.aside}

και εξηλθεν ο λογος ουτος εν ολη τη ιουδαια περι αυτου και εν παση τη περιχωρω[7:17]{.aside}

και απηγγειλαν ιωαννη οι μαθηται αυτου περι παντων τουτων [και]{.greek-added} [προσκαλεσαμενος]{.greek-added} [δυο]{.greek-added} [τινας]{.greek-added} [των]{.greek-added} [μαθητων]{.greek-added} [αυτου]{.greek-added} [ο]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added}[7:18]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [δυο]{.greek-omitted} [τινας]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [ιωαννης]{.greek-omitted} [επεμψεν]{.greek-omitted} [επεμψε]{.greek-added} προς τον [ιησουν]{.greek-abbr} λεγων συ ει ο ερχομενος η αλλον προσδοκωμεν[7:19]{.aside}

παραγενομενοι δε προς αυτον οι ανδρες ειπον ιωαννης ο βαπτιστης απεσταλκεν ημας προς σε λεγων συ ει ο ερχομενος η αλλον προσδοκωμεν[7:20]{.aside}

εν αυτη δε τη ωρα [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους απο νοσων και μαστιγων και [πνευματων]{.greek-abbr} πονηρων και τυφλοις πολλοις [εχαρισατο]{.greek-omitted} [εχαρησατο]{.greek-added} το βλεπειν[7:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε [ιωαννη]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} α [ειδετε]{.greek-omitted} [ιδετε]{.greek-added} και ηκουσατε οτι τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται πτωχοι ευαγγελιζονται[7:22]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[7:23]{.aside}

απελθοντων δε των αγγελων ιωαννου ηρξατο λεγειν [προς]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} [οχλοις]{.greek-omitted} [οχλους]{.greek-added} περι ιωαννου τι εξεληλυθατε εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[7:24]{.aside}

αλλα τι εξεληλυθατε ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι εν ιματισμω ενδοξω και τρυφη υπαρχοντες εν τοις βασιλειοις εισιν[7:25]{.aside}

αλλα τι εξεληλυθατε ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[7:26]{.aside}

ουτος [γαρ]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[7:27]{.aside}

λεγω γαρ υμιν μειζων εν γεννητοις γυναικων προφητης ιωαννου του βαπτιστου ουδεις εστιν ο δε μικροτερος εν τη βασιλεια του [θεου]{.greek-abbr} μειζων αυτου εστιν[7:28]{.aside}

και πας ο λαος ακουσας και οι τελωναι εδικαιωσαν τον [θεον]{.greek-abbr} βαπτισθεντες το βαπτισμα ιωαννου[7:29]{.aside}

οι δε φαρισαιοι και οι νομικοι την βουλην του [θεου]{.greek-abbr} ηθετησαν εις εαυτους μη [βαπτισθεντες]{.greek-omitted} [βαπτι]{.greek-added} [σθεντες]{.greek-added} υπ αυτου[7:30]{.aside}

τινι ουν ομοιωσω τους [ανθρωπους]{.greek-abbr} της γενεας ταυτης και τινι εισιν ομοιοι[7:31]{.aside}

ομοιοι [εισιν]{.greek-omitted} [εισι]{.greek-added} παιδιοις τοις εν αγορα καθημενοις και προσφωνουσιν αλληλοις και λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ ωρχησασθε εθρηνησαμεν υμιν και ουκ εκλαυσατε[7:32]{.aside}

[εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} γαρ ιωαννης ο βαπτιστης μητε αρτον εσθιων μητε οινον πινων και λεγετε δαιμονιον εχει[7:33]{.aside}

εληλυθεν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγετε ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης φιλος τελωνων και αμαρτωλων[7:34]{.aside}

και εδικαιωθη η σοφια απο των τεκνων αυτης παντων[7:35]{.aside}

ηρωτα δε τις αυτον των φαρισαιων ινα φαγη μετ αυτου και εισελθων εις την οικιαν του φαρισαιου ανεκλιθη[7:36]{.aside}

και ιδου γυνη εν τη πολει ητις ην αμαρτωλος [και]{.greek-added} επιγνουσα οτι ανακειται εν τη οικια του φαρισαιου κομισασα αλαβαστρον μυρου[7:37]{.aside}

και στασα [παρα]{.greek-omitted} [πα]{.greek-added} [ρα]{.greek-added} τους ποδας αυτου οπισω κλαιουσα ηρξατο βρεχειν τους ποδας αυτου τοις [δακρυσιν]{.greek-omitted} [δακρυσι]{.greek-added} και ταις [θριξιν]{.greek-omitted} [θριξι]{.greek-added} της κεφαλης αυτης [εξεμασσεν]{.greek-omitted} [εξεμασσε]{.greek-added} και κατεφιλει τους ποδας αυτου και [ηλειφεν]{.greek-omitted} [ηλειφε]{.greek-added} τω μυρω[7:38]{.aside}

ιδων δε ο φαρισαιος ο καλεσας αυτον ειπεν εν εαυτω λεγων ουτος ει ην προφητης εγινωσκεν αν τις και ποταπη η γυνη ητις απτεται αυτου οτι αμαρτωλος [εστιν]{.greek-omitted} [εστι]{.greek-added}[7:39]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν προς αυτον σιμων εχω σοι τι ειπειν ο δε [φησιν]{.greek-omitted} [φησι]{.greek-added} διδασκαλε ειπε[7:40]{.aside}

δυο χρεωφειλεται ησαν δανειστη τινι ο εις [ωφειλεν]{.greek-omitted} [ωφειλε]{.greek-added} δηναρια πεντακοσια ο δε ετερος πεντηκοντα[7:41]{.aside}

μη εχοντων δε αυτων αποδουναι αμφοτεροις [εχαρισατο]{.greek-omitted} [εχαρησατο]{.greek-added} τις ουν αυτων ειπε πλειον αυτον αγαπησει[7:42]{.aside}

αποκριθεις δε ο σιμων ειπεν υπολαμβανω οτι ω το πλειον [εχαρισατο]{.greek-omitted} [εχαρησατο]{.greek-added} ο δε ειπεν αυτω ορθως εκρινας[7:43]{.aside}

και στραφεις προς την γυναικα τω σιμωνι εφη βλεπεις ταυτην την γυναικα εισηλθον σου εις την οικιαν υδωρ επι τους ποδας μου ουκ εδωκας αυτη δε [τοις]{.greek-omitted} δακρυσιν [εβρεξεν]{.greek-omitted} [εβρεξε]{.greek-added} μου τους ποδας και ταις θριξιν της κεφαλης αυτης [εξεμαξεν]{.greek-omitted} [εξεμαξε]{.greek-added}[7:44]{.aside}

φιλημα μοι ουκ εδωκας αυτη δε αφ ης εισηλθον ου [διελιπεν]{.greek-omitted} [διελιπε]{.greek-added} καταφιλουσα μου τους ποδας[7:45]{.aside}

ελαιω την κεφαλην μου ουκ ηλειψας αυτη δε μυρω [ηλειψεν]{.greek-omitted} [ηλειψε]{.greek-added} μου τους ποδας[7:46]{.aside}

ου χαριν λεγω σοι αφεωνται αι αμαρτιαι αυτης αι πολλαι οτι [ηγαπησεν]{.greek-omitted} [ηγαπησε]{.greek-added} πολυ ω δε ολιγον αφιεται ολιγον αγαπα[7:47]{.aside}

ειπεν δε αυτη αφεωνται σου αι αμαρτιαι[7:48]{.aside}

και ηρξαντο οι συνανακειμενοι λεγειν εν εαυτοις τις ουτος εστιν ος και αμαρτιας αφιησιν[7:49]{.aside}

ειπεν δε προς την γυναικα η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε πορευου εις ειρηνην[7:50]{.aside}

### Chapter 8

και εγενετο εν τω καθεξης και αυτος [διωδευεν]{.greek-omitted} [διωδευε]{.greek-added} κατα πολιν και κωμην κηρυσσων και ευαγγελιζομενος την βασιλειαν του [θεου]{.greek-abbr} και οι δωδεκα συν αυτω[8:1]{.aside}

και γυναικες τινες αι ησαν τεθεραπευμεναι απο [πνευματων]{.greek-abbr} πονηρων και ασθενειων μαρια η καλουμενη μαγδαληνη αφ ης δαιμονια επτα εξεληλυθει[8:2]{.aside}

και ιωαννα γυνη χουζα επιτροπου ηρωδου και σουσαννα και ετεραι πολλαι αιτινες διηκονουν αυτοις απο των υπαρχοντων αυταις[8:3]{.aside}

[συνιοντος]{.greek-omitted} [συνοντος]{.greek-added} δε οχλου πολλου και των κατα πολιν επιπορευομενων προς αυτον ειπεν δια παραβολης[8:4]{.aside}

εξηλθεν ο σπειρων του σπειραι τον σπορον αυτου και εν τω σπειρειν αυτον ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και κατεπατηθη και τα πετεινα του [ουρανου]{.greek-abbr} κατεφαγεν αυτο[8:5]{.aside}

και ετερον επεσεν επι την πετραν και φυεν εξηρανθη δια το μη εχειν ικμαδα[8:6]{.aside}

και ετερον επεσεν εν μεσω των [ακανθων]{.greek-omitted} [ακαν]{.greek-added} [θων]{.greek-added} και [συμφυεισαι]{.greek-omitted} [συμφυησαι]{.greek-added} αι ακανθαι απεπνιξαν αυτο[8:7]{.aside}

και ετερον επεσεν εις την γην την αγαθην και φυεν [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} καρπον εκατονταπλασιονα ταυτα λεγων εφωνει ο εχων ωτα ακουειν ακουετω[8:8]{.aside}

επηρωτων δε αυτον οι μαθηται αυτου λεγοντες τις ειη η παραβολη αυτη[8:9]{.aside}

ο δε ειπεν υμιν δεδοται γνωναι τα μυστηρια της βασιλειας του [θεου]{.greek-abbr} τοις δε λοιποις εν παραβολαις ινα βλεποντες μη [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και ακουοντες μη συνιωσιν[8:10]{.aside}

[εστιν]{.greek-omitted} [εστι]{.greek-added} δε αυτη η παραβολη ο σπορος εστιν ο λογος του [θεου]{.greek-abbr}[8:11]{.aside}

οι δε παρα την οδον εισιν οι ακουοντες ειτα ερχεται ο διαβολος και αιρει τον λογον απο της καρδιας αυτων ινα μη πιστευσαντες σωθωσιν[8:12]{.aside}

οι δε επι της πετρας οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} μετα χαρας δεχονται τον λογον και ουτοι ριζαν ουκ εχουσιν οι προς καιρον [πιστευουσιν]{.greek-omitted} [πιστευουσι]{.greek-added} και εν καιρω πειρασμου [αφι]{.greek-added} [αφιστανται]{.greek-omitted} [στανται]{.greek-added}[8:13]{.aside}

το δε εις τας ακανθας πεσον ουτοι εισιν οι [ακουσαντες]{.greek-omitted} [ακουοντες]{.greek-added} και υπο μεριμνων και πλουτου και [υπο]{.greek-added} ηδονων του βιου πορευομενοι [συμπνιγονται]{.greek-omitted} [συμπνιγουσι]{.greek-added} και ου [τελεσφορουσιν]{.greek-omitted} [τελεσφορουσι]{.greek-added}[8:14]{.aside}

το δε εν τη καλη γη ουτοι εισιν οιτινες εν καρδια καλη και αγαθη ακουσαντες τον λογον [κατεχουσιν]{.greek-omitted} [κατεχουσι]{.greek-added} και καρποφορουσιν εν υπομονη[8:15]{.aside}

ουδεις δε λυχνον αψας καλυπτει αυτον σκευει η υποκατω κλινης τιθησιν αλλ επι [λυχνιας]{.greek-omitted} [λυχνιαν]{.greek-added} [επιτιθησιν]{.greek-omitted} [τιθησιν]{.greek-added} ινα οι εισπορευομενοι [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} το φως[8:16]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} κρυπτον ο ου φανερον γενησεται ουδε αποκρυφον ο ου γνωσθησεται και εις φανερον ελθη[8:17]{.aside}

βλεπετε [ουν]{.greek-omitted} πως ακουετε ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} εχη δοθησεται αυτω και ος [εαν]{.greek-omitted} [αν]{.greek-added} μη εχη [και]{.greek-omitted} ο δοκει εχειν αρθησεται απ αυτου[8:18]{.aside}

παρεγενοντο δε προς αυτον η [μητηρ]{.greek-abbr} και οι αδελφοι αυτου και ουκ ηδυναντο συντυχειν αυτω δια τον οχλον[8:19]{.aside}

[και]{.greek-omitted} [απηγγελη]{.greek-omitted} [απηγγελ]{.greek-added} [λη]{.greek-added} [δε]{.greek-added} αυτω λεγοντων [οτι]{.greek-added} η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εστηκασιν εξω ιδειν σε θελοντες[8:20]{.aside}

ο δε αποκριθεις ειπεν προς αυτους [μητηρ]{.greek-abbr} μου και αδελφοι μου ουτοι εισιν οι τον λογον του [θεου]{.greek-abbr} ακουοντες και ποιουντες [αυτον]{.greek-omitted}[8:21]{.aside}

[και]{.greek-omitted} εγενετο [δε]{.greek-added} εν μια των ημερων και αυτος ενεβη εις πλοιον και οι μαθηται αυτου και ειπεν προς αυτους διελθωμεν [δη]{.greek-added} εις το περαν της λιμνης και ανηχθησαν[8:22]{.aside}

πλεοντων δε αυτων [αφυπνωσεν]{.greek-omitted} [αφυπνωσε]{.greek-added} και κατεβη λαιλαψ ανεμου εις την λιμνην και συνεπληρουντο και εκινδυνευον[8:23]{.aside}

προσελθοντες δε διηγειραν αυτον λεγοντες επιστατα επιστατα απολλυμεθα ο δε εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και τω κλυδωνι του υδατος και επαυσαντο και εγενετο γαληνη [μεγαλη]{.greek-added}[8:24]{.aside}

ειπεν δε αυτοις που εστιν η πιστις υμων φοβηθεντες δε εθαυμασαν [λεγοντες]{.greek-omitted} προς αλληλους [λεγοντες]{.greek-added} τις αρα ουτος εστιν [οτι]{.greek-omitted} [ος]{.greek-added} και τοις ανεμοις επιτασσει και τω υδατι και υπακουουσιν αυτω[8:25]{.aside}

[και]{.greek-omitted} κατεπλευσαν [δε]{.greek-added} εις την χωραν των [γαδαρηνων]{.greek-omitted} [γαδαρινων]{.greek-added} ητις εστιν [αντιπεραν]{.greek-omitted} [αντιπερα]{.greek-added} της γαλιλαιας[8:26]{.aside}

εξελθοντι δε αυτω επι την γην υπηντησεν αυτω ανηρ τις εκ της πολεως ος [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δαιμονια εκ χρονων ικανων και ιματιον ουκ ενεδιδυσκετο και εν οικια ουκ εμενεν αλλ εν τοις μνημασιν[8:27]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [και]{.greek-omitted} [ανακραξας]{.greek-omitted} προσεπεσεν αυτω και [ανακραξας]{.greek-added} φωνη μεγαλη ειπεν τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου δεομαι σου μη με βασανισης[8:28]{.aside}

[παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} γαρ τω [πνευματι]{.greek-abbr} τω ακαθαρτω εξελθειν απο του [ανθρωπου]{.greek-abbr} πολλοις γαρ χρονοις συνηρπακει αυτον και εδεσμειτο [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} και πεδαις φυλασσομενος και διαρρησσων τα δεσμα ηλαυνετο υπο του δαιμονος εις τας ερημους[8:29]{.aside}

[επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} δε αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι εστιν ονομα ο δε ειπεν λεγεων οτι [εισηλθε]{.greek-added} δαιμονια πολλα [εισηλθεν]{.greek-omitted} εις αυτον[8:30]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον ινα μη επιταξη αυτοις εις την αβυσσον απελθειν[8:31]{.aside}

ην δε εκει αγελη χοιρων ικανων [βοσκομενων]{.greek-omitted} [βοσκομενη]{.greek-added} εν τω ορει και παρεκαλουν αυτον ινα επιτρεψη αυτοις εις εκεινους εισελθειν και επετρεψεν αυτοις[8:32]{.aside}

εξελθοντα δε τα δαιμονια απο του [ανθρωπου]{.greek-abbr} εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την λιμνην και απεπνιγη[8:33]{.aside}

ιδοντες δε οι βοσκοντες το γεγενημενον εφυγον και απηγγειλαν εις την πολιν και εις τους αγρους[8:34]{.aside}

[και]{.greek-added} εξηλθον [δε]{.greek-omitted} ιδειν το γεγονος και ηλθον προς τον [ιησουν]{.greek-abbr} και ευρον [καθημενον]{.greek-omitted} τον [ανθρωπον]{.greek-abbr} [καθημενον]{.greek-added} αφ ου τα δαιμονια [εξεληλυθει]{.greek-omitted} [εξηλθεν]{.greek-added} ιματισμενον και σωφρονουντα παρα τους ποδας του [ιησου]{.greek-abbr} [και]{.greek-omitted} εφοβηθησαν[8:35]{.aside}

απηγγειλαν δε αυτοις και οι ιδοντες πως εσωθη ο δαιμονισθεις[8:36]{.aside}

και ηρωτησαν αυτον απαν το πληθος της περιχωρου των [γαδαρηνων]{.greek-omitted} [γαδαρινων]{.greek-added} απελθειν απ αυτων οτι φοβω μεγαλω συνειχοντο αυτος δε εμβας εις το πλοιον υπεστρεψεν[8:37]{.aside}

εδεετο δε αυτου ο ανηρ αφ ου εξεληλυθει τα δαιμονια ειναι συν αυτω [απελυσεν]{.greek-omitted} [απελυσε]{.greek-added} δε αυτον ο [ιησους]{.greek-abbr} λεγων[8:38]{.aside}

υποστρεφε εις τον οικον σου και διηγου οσα εποιησεν σοι ο [θεος]{.greek-abbr} [και]{.greek-omitted} [απηλθεν]{.greek-omitted} [καθ]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [κηρυσσων]{.greek-omitted} [οσα]{.greek-omitted} [εποιησεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted}[8:39]{.aside}

εγενετο δε εν τω υποστρεψαι τον [ιησουν]{.greek-abbr} απεδεξατο αυτον ο οχλος [χαιρων]{.greek-added} ησαν γαρ παντες προσδοκωντες αυτον[8:40]{.aside}

και ιδου ηλθεν ανηρ ω ονομα ιαειρος και [αυτος]{.greek-omitted} [ουτος]{.greek-added} αρχων της συναγωγης [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} και πεσων παρα τους ποδας του [ιησου]{.greek-abbr} παρεκαλει αυτον εισελθειν εις τον οικον αυτου[8:41]{.aside}

οτι θυγατηρ μονογενης ην αυτω ως ετων δωδεκα και αυτη [απεθνησκεν]{.greek-omitted} [απεθνησκε]{.greek-added} [και]{.greek-added} [εγενετο]{.greek-added} εν [δε]{.greek-omitted} τω υπαγειν αυτον οι οχλοι συνεπνιγον αυτον[8:42]{.aside}

και γυνη ουσα εν ρυσει αιματος απο ετων δωδεκα ητις ιατροις προσαναλωσασα ολον τον βιον ουκ ισχυσεν υπ ουδενος θεραπευθηναι[8:43]{.aside}

προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου και παραχρημα εστη η ρυσις του αιματος αυτης[8:44]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τις ο αψαμενος μου αρνουμενων δε παντων ειπεν ο πετρος και οι [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [συν]{.greek-added} [αυτω]{.greek-added} επιστατα οι οχλοι [συνεχουσιν]{.greek-omitted} [συνεχουσι]{.greek-added} σε και [αποθλιβουσιν]{.greek-omitted} [αποθλιβουσι]{.greek-added} και λεγεις τις ο αψαμενος μου[8:45]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν ηψατο μου τις εγω γαρ εγνων δυναμιν εξελθουσαν απ εμου[8:46]{.aside}

ιδουσα δε η γυνη οτι ουκ [ελαθεν]{.greek-omitted} [ελαθε]{.greek-added} τρεμουσα [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσπεσουσα αυτω δι ην αιτιαν ηψατο αυτου απηγγειλεν αυτω ενωπιον παντος του λαου και ως ιαθη παραχρημα[8:47]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτη θαρσει θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε πορευου εις ειρηνην[8:48]{.aside}

ετι αυτου λαλουντος ερχεται τις παρα του αρχισυναγωγου λεγων αυτω οτι τεθνηκεν η θυγατηρ σου μη σκυλλε τον διδασκαλον[8:49]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας απεκριθη [αυτω]{.greek-omitted} [τω]{.greek-added} [[πατρι]{.greek-abbr}]{.greek-added} [της]{.greek-added} [παιδος]{.greek-added} λεγων μη φοβου μονον πιστευε και σωθησεται[8:50]{.aside}

ελθων δε εις την οικιαν ουκ αφηκεν εισελθειν [ουδενα]{.greek-omitted} [συν]{.greek-added} [αυτω]{.greek-added} [τινα]{.greek-added} ει μη πετρον και ιωαννην και ιακωβον και τον [πατερα]{.greek-abbr} της παιδος και την [μητερα]{.greek-abbr}[8:51]{.aside}

εκλαιον δε παντες και εκοπτοντο αυτην ο δε ειπεν μη κλαιετε [ουκ]{.greek-omitted} [ου]{.greek-added} [γαρ]{.greek-added} απεθανεν αλλα καθευδει[8:52]{.aside}

και κατεγελων αυτου [παντες]{.greek-added} ειδοτες οτι απεθανεν[8:53]{.aside}

αυτος δε εκβαλων [παντας]{.greek-added} εξω [παντας]{.greek-omitted} και κρατησας της χειρος αυτης [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} λεγων η παις [εγειρου]{.greek-omitted} [εγειραι]{.greek-added}[8:54]{.aside}

και [επεστρεψεν]{.greek-omitted} [επεστρεψε]{.greek-added} το [πνευμα]{.greek-abbr} αυτης και ανεστη [πα]{.greek-added} [παραχρημα]{.greek-omitted} [ραχρημα]{.greek-added} και [διεταξεν]{.greek-omitted} [διεταξε]{.greek-added} [δοθηναι]{.greek-added} αυτη [δοθηναι]{.greek-omitted} φαγειν[8:55]{.aside}

[και]{.greek-omitted} εξεστησαν [δε]{.greek-added} οι γονεις αυτης ο δε παρηγγειλεν αυτοις μηδενι ειπειν το γεγονος[8:56]{.aside}

### Chapter 9

συγκαλεσαμενος δε τους δωδεκα εδωκεν αυτοις δυναμιν και εξουσιαν επι παντα τα δαιμονια και νοσους θεραπευειν[9:1]{.aside}

και απεστειλεν αυτους κηρυσσειν την βασιλειαν του [θεου]{.greek-abbr} και ιασθαι τους ασθενουντας[9:2]{.aside}

και ειπεν [προς]{.greek-omitted} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} μηδεν αιρετε εις την οδον [μητε]{.greek-omitted} [μη]{.greek-added} ραβδους μητε πηραν μητε αρτον μητε αργυριον μητε ανα δυο χιτωνας εχειν[9:3]{.aside}

και εις ην αν οικιαν εισελθητε εκει μενετε και εκειθεν εξερχεσθε[9:4]{.aside}

και οσοι [εαν]{.greek-omitted} [αν]{.greek-added} μη [δετωνται]{.greek-added} [δεξωνται]{.corr} υμας εξερχομενοι απο της πολεως εκεινης και τον κονιορτον απο των ποδων υμων αποτιναξατε εις μαρτυριον [επ]{.greek-omitted} [αυτους]{.greek-omitted} [εαυτοις]{.greek-added}[9:5]{.aside}

εξερχομενοι δε διηρχοντο κατα τας κωμας ευαγγελιζομενοι και θεραπευοντες πανταχου[9:6]{.aside}

[ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} δε ηρωδης ο τετραρχης τα γινομενα υπ αυτου παντα και διηπορει δια το λεγεσθαι υπο τινων οτι ιωαννης εγηγερται εκ νεκρων[9:7]{.aside}

υπο τινων δε οτι ηλιας εφανη αλλων δε οτι προφητης [εις]{.greek-omitted} [τις]{.greek-added} των αρχαιων ανεστη[9:8]{.aside}

και ειπεν ηρωδης ιωαννην εγω απεκεφαλισα τις δε εστιν ουτος περι ου εγω ακουω τοιαυτα και εζητει ιδειν αυτον[9:9]{.aside}

και υποστρεψαντες οι αποστολοι διηγησαντο αυτω οσα εποιησαν και παραλαβων αυτους [υπεχωρησεν]{.greek-omitted} [υπεχωρησε]{.greek-added} κατ ιδιαν εις τοπον ερημον πολεως καλουμενης βηθσαιδαν[9:10]{.aside}

οι δε οχλοι γνοντες ηκολουθησαν αυτω και δεξαμενος αυτους ελαλει αυτοις περι της βασιλειας του [θεου]{.greek-abbr} και τους χρειαν εχοντας θεραπειας ιατο[9:11]{.aside}

η δε ημερα ηρξατο κλινειν προσελθοντες δε οι δωδεκα ειπον αυτω απολυσον τον οχλον ινα απελθοντες εις τας κυκλω κωμας και τους αγρους [καταλυσωσιν]{.greek-omitted} [καταλυσωσι]{.greek-added} και ευρωσιν επισιτισμον οτι ωδε εν ερημω τοπω εσμεν[9:12]{.aside}

ειπεν δε προς αυτους δοτε αυτοις υμεις φαγειν οι δε ειπον ουκ εισιν ημιν πλειον η πεντε αρτοι και ιχθυες δυο ει μητι πορευθεντες ημεις [αγορασωμεν]{.greek-omitted} [αγορασομεν]{.greek-added} εις παντα τον λαον τουτον βρωματα[9:13]{.aside}

ησαν γαρ ωσει ανδρες πεντακισχιλιοι ειπεν δε προς τους μαθητας αυτου κατακλινατε αυτους κλισιας ανα πεντηκοντα[9:14]{.aside}

και εποιησαν ουτως και ανεκλιναν απαντας[9:15]{.aside}

λαβων δε τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} ευλογησεν αυτους και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} και εδιδου τοις μαθηταις παρατιθεναι τω οχλω[9:16]{.aside}

και εφαγον και εχορτασθησαν παντες και [ηρθη]{.greek-omitted} [ηραν]{.greek-added} το περισσευσαν αυτοις κλασματων κοφινοι δωδεκα[9:17]{.aside}

και εγενετο εν τω ειναι αυτον προσευχομενον [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} συνησαν αυτω οι μαθηται και επηρωτησεν αυτους λεγων τινα με λεγουσιν οι [οχλοι]{.greek-omitted} [[ανθρωποι]{.greek-abbr}]{.greek-added} ειναι[9:18]{.aside}

οι δε αποκριθεντες ειπον ιωαννην τον βαπτιστην αλλοι δε ηλιαν αλλοι δε οτι προφητης τις των αρχαιων ανεστη[9:19]{.aside}

ειπεν δε αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε [ο]{.greek-omitted} πετρος ειπεν τον [χριστον]{.greek-abbr} του [θεου]{.greek-abbr}[9:20]{.aside}

ο δε επιτιμησας αυτοις [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} μηδενι [ειπειν]{.greek-omitted} [λεγειν]{.greek-added} τουτο[9:21]{.aside}

ειπων οτι δει [τον]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και αρχιερεων και γραμματεων και αποκτανθηναι και τη τριτη ημερα [αναστηναι]{.greek-omitted} [εγερθηναι]{.greek-added}[9:22]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε προς παντας ει τις θελει οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθει]{.greek-added} [τω]{.greek-added} μοι[9:23]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την ψυχην αυτου ενεκεν εμου ουτος σωσει αυτην[9:24]{.aside}

τι γαρ ωφελειται [ανθρωπος]{.greek-abbr} κερδησας τον κοσμον ολον εαυτον δε απολεσας η ζημιωθεις[9:25]{.aside}

ος γαρ αν επαισχυνθη με και τους εμους λογους τουτον ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται οταν ελθη εν τη δοξη αυτου και του [πατρος]{.greek-abbr} και των αγιων αγγελων[9:26]{.aside}

λεγω δε υμιν αληθως [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστωτων οι ου μη γευσωνται θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr}[9:27]{.aside}

εγενετο δε μετα τους λογους τουτους ωσει ημεραι οκτω και παραλαβων πετρον και ιωαννην και ιακωβον ανεβη εις το ορος προσευξασθαι[9:28]{.aside}

και εγενετο εν τω προσευχεσθαι αυτον το ειδος του προσωπου αυτου ετερον και ο ιματισμος αυτου λευκος εξαστραπτων[9:29]{.aside}

και ιδου ανδρες δυο συνελαλουν αυτω οιτινες ησαν μωσης και ηλιας[9:30]{.aside}

οι οφθεντες εν δοξη ελεγον την εξοδον αυτου ην [εμελλεν]{.greek-omitted} [εμελλε]{.greek-added} πληρουν εν [ιερουσαλημ]{.greek-abbr}[9:31]{.aside}

ο δε πετρος και οι συν αυτω ησαν βεβαρημενοι υπνω διαγρηγορησαντες δε ειδον την δοξαν αυτου και τους δυο ανδρας τους συνεστωτας αυτω[9:32]{.aside}

και εγενετο εν τω διαχωριζεσθαι αυτους απ αυτου ειπεν [ο]{.greek-added} πετρος προς τον [ιησουν]{.greek-abbr} επιστατα καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις μιαν σοι και μιαν μωση και μιαν ηλια μη ειδως ο λεγει[9:33]{.aside}

ταυτα δε αυτου λεγοντος εγενετο νεφελη και επεσκιασεν αυτους εφοβηθησαν δε εν τω εκεινους εισελθειν εις την νεφελην[9:34]{.aside}

και φωνη εγενετο εκ της νεφελης λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:35]{.aside}

και εν τω γενεσθαι την φωνην ευρεθη ο [ιησους]{.greek-abbr} μονος και αυτοι εσιγησαν και [ουδενι]{.greek-omitted} [ουδε]{.greek-added} [νι]{.greek-added} απηγγειλαν εν εκειναις ταις ημεραις ουδεν ων εωρακασιν[9:36]{.aside}

εγενετο δε εν τη εξης ημερα κατελθοντων αυτων απο του ορους συνηντησεν αυτω οχλος πολυς[9:37]{.aside}

και ιδου ανηρ απο του οχλου [ανεβοησεν]{.greek-omitted} [ανεβοησε]{.greek-added} λεγων διδασκαλε δεομαι σου [επιβλεψαι]{.greek-omitted} [επιβλεψον]{.greek-added} επι τον [υιον]{.greek-abbr} μου οτι μονογενης [εστιν]{.greek-omitted} [εστι]{.greek-added} μοι[9:38]{.aside}

και ιδου [πνευμα]{.greek-abbr} λαμβανει αυτον και εξαιφνης κραζει και σπαρασσει αυτον μετα αφρου και μογις αποχωρει απ αυτου συντριβον αυτον[9:39]{.aside}

και εδεηθην των μαθητων σου ινα εκβαλωσιν αυτο και ουκ ηδυνηθησαν[9:40]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε εσομαι [προς]{.greek-omitted} [υμας]{.greek-omitted} [μεθ]{.greek-added} [υμων]{.greek-added} και ανεξομαι υμων προσαγαγε τον [υιον]{.greek-abbr} σου ωδε[9:41]{.aside}

ετι δε προσερχομενου αυτου [ερρηξεν]{.greek-omitted} [ερριψεν]{.greek-added} αυτον το δαιμονιον και συνεσπαραξεν [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} δε ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} τω [ακαθαρτω]{.greek-omitted} [ακαθαρ]{.greek-added} [τω]{.greek-added} και ιασατο τον παιδα και απεδωκεν αυτον τω [πατρι]{.greek-abbr} αυτου[9:42]{.aside}

εξεπλησσοντο δε παντες επι τη μεγαλειοτητι του [θεου]{.greek-abbr} παντων δε θαυμαζοντων επι πασιν οις [εποιησεν]{.greek-omitted} [εποιει]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν προς τους μαθητας αυτου[9:43]{.aside}

θεσθε υμεις εις τα ωτα υμων τους λογους τουτους ο γαρ [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} μελλει παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[9:44]{.aside}

οι δε ηγνοουν το ρημα τουτο και ην παρακεκαλυμμενον απ αυτων ινα μη αισθωνται αυτο και εφοβουντο ερωτησαι αυτον περι του ρηματος τουτου[9:45]{.aside}

[εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} δε διαλογισμος εν αυτοις το τις αν ειη μειζων αυτων[9:46]{.aside}

ο δε [ιησους]{.greek-abbr} ιδων τον διαλογισμον της καρδιας αυτων επιλαβομενος παιδιου εστησεν αυτο παρ εαυτω[9:47]{.aside}

και ειπεν αυτοις ος εαν δεξηται τουτο το παιδιον επι τω ονοματι μου εμε [δεχεται]{.greek-omitted} [δεχετε]{.greek-added} και ος εαν εμε δεξηται [δεχεται]{.greek-omitted} [δε]{.greek-added} [χετε]{.greek-added} τον αποστειλαντα με ο γαρ μικροτερος εν πασιν υμιν υπαρχων ουτος εσται μεγας[9:48]{.aside}

αποκριθεις δε [ο]{.greek-omitted} ιωαννης ειπεν επιστατα ειδομεν τινα επι τω ονοματι σου εκβαλλοντα δαιμονια και εκωλυσαμεν αυτον οτι ουκ ακολουθει μεθ ημων[9:49]{.aside}

και ειπεν προς [αυτον]{.greek-omitted} [αυτους]{.greek-added} ο [ιησους]{.greek-abbr} μη κωλυετε ος γαρ ουκ [εστι]{.greek-added} [καθ]{.greek-added} [υμων]{.greek-added} [υπερ]{.greek-added} [υμων]{.greek-added} εστιν [καθ]{.greek-omitted} [ημων]{.greek-omitted} [υπερ]{.greek-omitted} [ημων]{.greek-omitted} [εστιν]{.greek-omitted}[9:50]{.aside}

εγενετο δε εν τω συμπληρουσθαι τας ημερας της αναληψεως αυτου και αυτος το προσωπον αυτου [εστηριξεν]{.greek-omitted} [εστηριξε]{.greek-added} του πορευεσθαι εις [ιερουσαλημ]{.greek-abbr}[9:51]{.aside}

και απεστειλεν αγγελους προ προσωπου [αυτου]{.greek-omitted} [εαυτου]{.greek-added} και πορευθεντες εισηλθον εις κωμην σαμαρειτων ωστε ετοιμασαι αυτω[9:52]{.aside}

και ουκ εδεξαντο αυτον οτι το προσωπον αυτου ην πορευομενον εις [ιερουσαλημ]{.greek-abbr}[9:53]{.aside}

ιδοντες δε οι μαθηται αυτου ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ειπον [κυριε]{.greek-abbr} θελεις ειπωμεν πυρ καταβηναι απο του [ουρανου]{.greek-abbr} και αναλωσαι αυτους ως και ηλιας εποιησεν[9:54]{.aside}

στραφεις δε επετιμησεν αυτοις [και]{.greek-omitted} [ειπεν]{.greek-omitted} [ουκ]{.greek-omitted} [οιδατε]{.greek-omitted} [οιου]{.greek-omitted} [πνευματος]{.greek-omitted} [εστε]{.greek-omitted} [υμεις]{.greek-omitted}[9:55]{.aside}

[ο]{.greek-omitted} [γαρ]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ουκ]{.greek-omitted} [ηλθεν]{.greek-omitted} [ψυχας]{.greek-omitted} [ανθρωπων]{.greek-omitted} [απολεσαι]{.greek-omitted} [αλλα]{.greek-omitted} [σωσαι]{.greek-omitted} και επορευθησαν εις ετεραν κωμην[9:56]{.aside}

εγενετο δε πορευομενων αυτων εν τη οδω ειπεν τις [αυτω]{.greek-added} [προς]{.greek-omitted} [αυτον]{.greek-omitted} ακολουθησω σοι οπου αν απερχη [κυριε]{.greek-abbr}[9:57]{.aside}

και ειπεν αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κλινει]{.greek-added}[9:58]{.aside}

ειπεν δε προς ετερον ακολουθει μοι ο δε ειπεν [κυριε]{.greek-abbr} επιτρεψον μοι απελθοντι πρωτον θαψαι τον [πατερα]{.greek-abbr} μου[9:59]{.aside}

ειπεν δε αυτω ο [ιησους]{.greek-abbr} αφες τους νεκρους θαψαι τους εαυτων νεκρους συ δε απελθων διαγγελλε την βασιλειαν του [θεου]{.greek-abbr}[9:60]{.aside}

ειπεν δε και ετερος ακολουθησω σοι [κυριε]{.greek-abbr} πρωτον δε επιτρεψον μοι αποταξασθαι τοις εις τον οικον μου[9:61]{.aside}

ειπεν δε [προς]{.greek-added} [αυτον]{.greek-added} ο [ιησους]{.greek-abbr} [προς]{.greek-omitted} [αυτον]{.greek-omitted} ουδεις επιβαλων την χειρα αυτου επ αροτρον και βλεπων εις τα [οπισω]{.greek-omitted} [οπι]{.greek-added} [σω]{.greek-added} ευθετος εστιν εις την βασιλειαν του [θεου]{.greek-abbr}[9:62]{.aside}

### Chapter 10

μετα δε ταυτα ανεδειξεν ο [κυριος]{.greek-abbr} και ετερους εβδομηκοντα και απεστειλεν αυτους ανα δυο προ προσωπου [αυτου]{.greek-omitted} [εαυτου]{.greek-added} εις πασαν πολιν και [τοπον]{.greek-omitted} [χωραν]{.greek-added} ου [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} αυτος ερχεσθαι[10:1]{.aside}

ελεγεν ουν προς αυτους ο μεν θερισμος πολυς οι δε εργαται ολιγοι δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως εκβαλη εργατας εις τον θερισμον αυτου[10:2]{.aside}

υπαγετε ιδου εγω αποστελλω υμας ως αρνας εν μεσω λυκων[10:3]{.aside}

μη βασταζετε [βαλαντιον]{.greek-omitted} [βαλλαντιον]{.greek-added} μη πηραν [μηδε]{.greek-omitted} [μη]{.greek-added} υποδηματα και μηδενα κατα την οδον ασπασησθε[10:4]{.aside}

εις ην δ αν οικιαν εισερχησθε πρωτον λεγετε ειρηνη τω οικω τουτω[10:5]{.aside}

και εαν η εκει [υιος]{.greek-abbr} ειρηνης επαναπαυσεται επ αυτον η ειρηνη υμων ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} εφ υμας ανακαμψει[10:6]{.aside}

εν αυτη δε τη οικια μενετε εσθιοντες και πινοντες τα παρ αυτων αξιος γαρ ο εργατης του μισθου αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} μη μεταβαινετε εξ οικιας εις οικιαν[10:7]{.aside}

και εις ην αν πολιν εισερχησθε και [δεχωνται]{.greek-omitted} [δεχονται]{.greek-added} υμας εσθιετε τα παρατιθεμενα υμιν[10:8]{.aside}

και θεραπευετε τους εν αυτη ασθενεις και λεγετε αυτοις ηγγικεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[10:9]{.aside}

εις ην δ αν πολιν εισερχησθε και μη [δεχωνται]{.greek-omitted} [δεχονται]{.greek-added} υμας εξελθοντες εις τας πλατειας αυτης ειπατε[10:10]{.aside}

και τον κονιορτον τον κολληθεντα ημιν εκ της πολεως υμων [εις]{.greek-added} [τους]{.greek-added} [ποδας]{.greek-added} [ημων]{.greek-added} απομασσομεθα υμιν πλην τουτο γινωσκετε οτι ηγγικεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[10:11]{.aside}

λεγω υμιν οτι σοδομοις εν τη ημερα εκεινη ανεκτοτερον εσται η τη πολει εκεινη[10:12]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χοραζειν]{.greek-added} ουαι σοι [βηθσαιδα]{.greek-omitted} [βηθσαιδαν]{.greek-added} οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι αν εν σακκω και σποδω καθημεναι μετενοησαν[10:13]{.aside}

πλην τυρω και σιδωνι [ανε]{.greek-added} [ανεκτοτερον]{.greek-omitted} [κτοτερον]{.greek-added} εσται εν τη κρισει η υμιν[10:14]{.aside}

και συ καπερναουμ η εως του [ουρανου]{.greek-abbr} υψωθεισα εως αδου καταβιβασθηση[10:15]{.aside}

ο ακουων υμων εμου ακουει και ο αθετων υμας εμε αθετει ο δε εμε αθετων αθετει τον αποστειλαντα με[10:16]{.aside}

υπεστρεψαν δε οι εβδομηκοντα μετα χαρας λεγοντες [κυριε]{.greek-abbr} και τα δαιμονια υποτασσεται ημιν εν τω ονοματι σου[10:17]{.aside}

ειπεν δε αυτοις εθεωρουν τον σαταναν ως αστραπην εκ του [ουρανου]{.greek-abbr} πεσοντα[10:18]{.aside}

ιδου διδωμι υμιν την εξουσιαν του πατειν επανω οφεων και σκορπιων και επι πασαν την δυναμιν του εχθρου και ουδεν υμας ου μη αδικηση[10:19]{.aside}

πλην εν τουτω μη χαιρετε οτι τα [πνευματα]{.greek-abbr} υμιν υποτασσεται χαιρετε δε οτι τα ονοματα υμων εγραφη εν τοις [ουρανοις]{.greek-abbr}[10:20]{.aside}

εν αυτη [δε]{.greek-added} τη ωρα ηγαλλιασατο τω [πνευματι]{.greek-abbr} ο [ιησους]{.greek-abbr} και ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι [α]{.greek-added} [απεκρυψας]{.greek-omitted} [πεκρυψας]{.greek-added} ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[10:21]{.aside}

[και]{.greek-omitted} [στραφεις]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [ειπεν]{.greek-omitted} παντα μοι παρεδοθη υπο του [πατρος]{.greek-abbr} μου και ουδεις [γινωσκει]{.greek-omitted} [επιγινωσκει]{.greek-added} τις εστιν ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} και τις εστιν ο [πατηρ]{.greek-abbr} ει μη ο [υιος]{.greek-abbr} και ω εαν βουληται ο [υιος]{.greek-abbr} αποκαλυψαι[10:22]{.aside}

και στραφεις προς τους μαθητας κατ ιδιαν ειπεν μακαριοι οι οφθαλμοι οι βλεποντες α βλεπετε[10:23]{.aside}

λεγω γαρ υμιν οτι πολλοι προφηται και βασιλεις ηθελησαν ιδειν α υμεις βλεπετε και ουκ ειδον και ακουσαι α ακουετε και ουκ ηκουσαν[10:24]{.aside}

και ιδου νομικος τις ανεστη [εκπειραζων]{.greek-omitted} [πειραζων]{.greek-added} αυτον και λεγων διδασκαλε τι ποιησας ζωην αιωνιον κληρονομησω[10:25]{.aside}

ο δε ειπεν προς αυτον εν τω νομω τι γεγραπται πως αναγινωσκεις[10:26]{.aside}

ο δε αποκριθεις ειπεν αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της ισχυος σου και εξ ολης της διανοιας σου και τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[10:27]{.aside}

ειπεν δε αυτω ορθως απεκριθης τουτο ποιει και ζηση[10:28]{.aside}

ο δε θελων δικαιουν εαυτον ειπεν προς τον [ιησουν]{.greek-abbr} και τις [εστιν]{.greek-omitted} [εστι]{.greek-added} μου πλησιον[10:29]{.aside}

υπολαβων δε [ειπεν]{.greek-added} ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ανθρωπος]{.greek-abbr} τις κατεβαινεν απο [ιερουσαλημ]{.greek-abbr} εις ιεριχω και λησταις περιεπεσεν οι και εκδυσαντες αυτον και πληγας επιθεντες απηλθον αφεντες ημιθανη τυγχανοντα[10:30]{.aside}

κατα συγκυριαν δε ιερευς τις κατεβαινεν εν τη οδω εκεινη και ιδων αυτον αντιπαρηλθεν[10:31]{.aside}

ομοιως δε και λευιτης γενομενος κατα τον τοπον ελθων και ιδων [αυτον]{.greek-added} αντιπαρηλθεν[10:32]{.aside}

σαμαρειτης δε τις οδευων [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} κατ αυτον και ιδων αυτον εσπλαγχνισθη[10:33]{.aside}

και προσελθων [κατεδησεν]{.greek-omitted} [κατεδησε]{.greek-added} τα τραυματα αυτου επιχεων ελαιον και οινον επιβιβασας δε αυτον επι το ιδιον κτηνος ηγαγεν αυτον εις πανδοχειον και επεμεληθη αυτου[10:34]{.aside}

και επι την αυριον εξελθων εκβαλων δυο δηναρια [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τω πανδοχει και ειπεν αυτω επιμεληθητι αυτου και ο τι αν προσδαπανησης εγω εν τω επανερχεσθαι με αποδωσω σοι[10:35]{.aside}

τις ουν [τουτων]{.greek-omitted} των τριων [πλησιον]{.greek-omitted} [τουτων]{.greek-added} δοκει σοι [πλησιον]{.greek-added} γεγονεναι του εμπεσοντος εις τους ληστας[10:36]{.aside}

ο δε ειπεν ο ποιησας το ελεος μετ αυτου ειπεν [ουν]{.greek-omitted} [δε]{.greek-added} αυτω ο [ιησους]{.greek-abbr} πορευου και συ ποιει ομοιως[10:37]{.aside}

εγενετο δε εν τω πορευεσθαι αυτους και αυτος εισηλθεν εις κωμην τινα γυνη δε τις ονοματι μαρθα υπεδεξατο αυτον εις τον οικον αυτης[10:38]{.aside}

και τηδε ην αδελφη καλουμενη μαρια η και [παρακαθισασα]{.greek-omitted} [παρακαθησασα]{.greek-added} παρα τους ποδας του [ιησου]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added} τον λογον αυτου[10:39]{.aside}

η δε μαρθα περιεσπατο περι πολλην διακονιαν επιστασα δε ειπεν [κυριε]{.greek-abbr} ου μελει σοι οτι η αδελφη μου μονην με [κατελειπεν]{.greek-omitted} [κατελιπε]{.greek-added} διακονειν ειπε ουν αυτη ινα μοι συναντιλαβηται[10:40]{.aside}

αποκριθεις δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτη [ο]{.greek-omitted} [ιησους]{.greek-omitted} μαρθα μαρθα μεριμνας και τυρβαζη περι πολλα[10:41]{.aside}

ενος δε [εστιν]{.greek-omitted} [εστι]{.greek-added} χρεια μαρια δε την αγαθην μεριδα εξελεξατο ητις ουκ αφαιρεθησεται απ αυτης[10:42]{.aside}

### Chapter 11

και εγενετο εν τω ειναι αυτον εν τοπω τινι προσευχομενον ως επαυσατο ειπεν τις των μαθητων αυτου προς αυτον [κυριε]{.greek-abbr} διδαξον ημας προσευχεσθαι καθως και ιωαννης [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τους μαθητας αυτου[11:1]{.aside}

ειπεν δε αυτοις οταν προσευχησθε λεγετε [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το ονομα σου ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[11:2]{.aside}

τον αρτον ημων τον επιουσιον διδου ημιν το καθ ημεραν[11:3]{.aside}

και αφες ημιν τας αμαρτιας ημων και γαρ αυτοι αφιεμεν παντι οφειλοντι ημιν και μη εισενεγκης ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου[11:4]{.aside}

και ειπεν προς αυτους τις εξ υμων εξει φιλον και πορευσεται προς αυτον μεσονυκτιου και [ειπη]{.greek-omitted} [ερει]{.greek-added} αυτω φιλε χρησον μοι τρεις αρτους[11:5]{.aside}

επειδη φιλος [μου]{.greek-added} παρεγενετο εξ οδου προς με και ουκ εχω ο παραθησω αυτω[11:6]{.aside}

[και]{.greek-added} [κακεινος]{.greek-omitted} [εκεινος]{.greek-added} εσωθεν αποκριθεις ειπη μη μοι κοπους παρεχε ηδη η θυρα κεκλεισται και τα παιδια μου μετ εμου εις την κοιτην εισιν ου δυναμαι αναστας δουναι σοι[11:7]{.aside}

λεγω υμιν ει και ου δωσει αυτω αναστας δια το ειναι αυτου φιλον δια γε την αναιδειαν αυτου εγερθεις δωσει αυτω οσον χρηζει[11:8]{.aside}

καγω υμιν λεγω αιτειτε και δοθησεται υμιν ζητειτε και ευρησετε κρουετε και [ανοιγησεται]{.greek-omitted} [ανοιχθησεται]{.greek-added} υμιν[11:9]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι [α]{.greek-added} [ανοιγησεται]{.greek-omitted} [νοιχθησεται]{.greek-added}[11:10]{.aside}

τινα δε [εξ]{.greek-added} υμων τον [πατερα]{.greek-abbr} αιτησει ο [υιος]{.greek-abbr} αρτον μη λιθον επιδωσει αυτω η [και]{.greek-omitted} ιχθυν μη αντι ιχθυος οφιν επιδωσει αυτω[11:11]{.aside}

η και εαν αιτηση ωον μη επιδωσει αυτω σκορπιον[11:12]{.aside}

ει ουν υμεις πονηροι [υπαρχοντες]{.greek-omitted} [οντες]{.greek-added} οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} [υμων]{.greek-added} ο εξ [ουρανου]{.greek-abbr} δωσει [πνευμα]{.greek-abbr} αγιον τοις αιτουσιν αυτον[11:13]{.aside}

και ην εκβαλλων δαιμονιον και αυτο ην κωφον εγενετο δε του δαιμονιου εξελθοντος ελαλησεν ο κωφος και εθαυμασαν οι οχλοι[11:14]{.aside}

τινες δε εξ αυτων ειπον εν βεελζεβουλ [τω]{.greek-added} αρχοντι των δαιμονιων εκβαλλει τα δαιμονια [ο]{.greek-added} [δε]{.greek-added} [αποκριθεις]{.greek-added} [ειπεν]{.greek-added} [πως]{.greek-added} [δυναται]{.greek-added} [σατανας]{.greek-added} [σαταναν]{.greek-added} [εκβαλλειν]{.greek-added}[11:15]{.aside}

ετεροι δε πειραζοντες σημειον παρ αυτου εζητουν εξ [ουρανου]{.greek-abbr}[11:16]{.aside}

αυτος δε ειδως αυτων τα διανοηματα ειπεν αυτοις πασα βασιλεια εφ εαυτην [διαμερισθεισα]{.greek-omitted} [διαμερισθησα]{.greek-added} ερημουται και οικος επι οικον πιπτει[11:17]{.aside}

ει δε και ο σατανας εφ εαυτον [διεμερισθη]{.greek-omitted} [διαμερισθη]{.greek-added} πως σταθησεται η βασιλεια αυτου οτι λεγετε εν βεελζεβουλ [τω]{.greek-added} [αρχοντι]{.greek-added} εκβαλλειν με τα δαιμονια[11:18]{.aside}

ει δε εγω εν βεελζεβουλ εκβαλλω τα δαιμονια οι υιοι υμων εν τινι [εκβαλλουσιν]{.greek-omitted} [εκβαλλουσι]{.greek-added} δια τουτο [αυτοι]{.greek-added} κριται υμων [αυτοι]{.greek-omitted} εσονται[11:19]{.aside}

ει δε [εγω]{.greek-added} εν δακτυλω [θεου]{.greek-abbr} εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[11:20]{.aside}

οταν ο ισχυρος [καθωπλισμενος]{.greek-omitted} [καθοπλισμενος]{.greek-added} φυλασση την εαυτου αυλην εν ειρηνη [εστιν]{.greek-omitted} [εστι]{.greek-added} τα υπαρχοντα [αυτου]{.greek-omitted} [αυτω]{.greek-added}[11:21]{.aside}

επαν δε ο ισχυροτερος αυτου επελθων νικηση αυτον την πανοπλιαν αυτου αιρει εφ η επεποιθει και τα σκυλα αυτου διαδιδωσιν[11:22]{.aside}

ο μη ων μετ εμου κατ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο μη συναγων μετ εμου σκορπιζει[11:23]{.aside}

οταν το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητουν αναπαυσιν και μη ευρισκον λεγει υποστρεψω εις τον οικον μου οθεν εξηλθον[11:24]{.aside}

και [ελθον]{.greek-omitted} [ελθων]{.greek-added} ευρισκει σεσαρωμενον και κεκοσμημενον[11:25]{.aside}

τοτε πορευεται και παραλαμβανει επτα ετερα [πνευματα]{.greek-abbr} πονηροτερα εαυτου και [ελθοντα]{.greek-omitted} [εισελθοντα]{.greek-added} κατοικει εκει και γινεται τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου χειρονα των πρωτων[11:26]{.aside}

εγενετο δε εν τω λεγειν αυτον ταυτα επαρασα τις γυνη φωνην εκ του οχλου ειπεν αυτω μακαρια η κοιλια η βαστασασα σε και μαστοι ους εθηλασας[11:27]{.aside}

αυτος δε ειπεν [μενουνγε]{.greek-omitted} [μενουν]{.greek-added} [γε]{.greek-added} μακαριοι οι ακουοντες τον λογον του [θεου]{.greek-abbr} και φυλασσοντες αυτον[11:28]{.aside}

των δε οχλων επαθροιζομενων ηρξατο λεγειν η γενεα αυτη πονηρα [εστιν]{.greek-omitted} [εστι]{.greek-added} σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[11:29]{.aside}

καθως γαρ εγενετο [ο]{.greek-added} ιωνας σημειον τοις [νινευιταις]{.greek-omitted} [νηνευιταις]{.greek-added} ουτως εσται και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} τη γενεα ταυτη[11:30]{.aside}

βασιλισσα [νο]{.greek-added} [νοτου]{.greek-omitted} [του]{.greek-added} εγερθησεται εν τη κρισει μετα των ανδρων της γενεας ταυτης και κατακρινει αυτους οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν σολομωνος και ιδου πλειον σολομωνος ωδε[11:31]{.aside}

ανδρες [νινευι]{.greek-omitted} [νηνευιαν]{.greek-added} [αναστησονται]{.greek-omitted} [αστησονται]{.greek-added} εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[11:32]{.aside}

ουδεις [δε]{.greek-omitted} λυχνον αψας εις κρυπτην τιθησιν ουδε υπο τον μοδιον αλλ επι την λυχνιαν ινα οι εισπορευομενοι το φεγγος βλεπωσιν[11:33]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος οταν ουν ο οφθαλμος σου απλους η και ολον το σωμα σου φωτεινον εστιν [επαν]{.greek-omitted} [οταν]{.greek-added} δε [ο]{.greek-added} [οφθαλμος]{.greek-added} [σου]{.greek-added} πονηρος η και το σωμα σου σκοτεινον [εσται]{.greek-added}[11:34]{.aside}

σκοπει ουν μη το φως το εν σοι σκοτος εστιν[11:35]{.aside}

ει ουν το σωμα σου ολον φωτεινον μη εχον [μερος]{.greek-added} τι [μερος]{.greek-omitted} σκοτεινον εσται φωτεινον ολον ως οταν ο λυχνος τη αστραπη φωτιζη σε[11:36]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} λαλησαι [αυτον]{.greek-added} ηρωτα αυτον φαρισαιος τις οπως αριστηση παρ αυτω εισελθων δε ανεπεσεν[11:37]{.aside}

ο δε φαρισαιος [ιδων]{.greek-omitted} [εθαυμασεν]{.greek-omitted} [ηρξατο]{.greek-added} [διακρινομενος]{.greek-added} [εν]{.greek-added} [εαυτω]{.greek-added} [λεγειν]{.greek-added} οτι ου πρωτον εβαπτισθη προ του αριστου[11:38]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} προς αυτον νυν υμεις οι φαρισαιοι το εξωθεν του ποτηριου και του πινακος καθαριζετε το δε εσωθεν υμων γεμει αρπαγης και πονηριας[11:39]{.aside}

αφρονες ουχ ο ποιησας το [εξωθεν]{.greek-omitted} [εσωθεν]{.greek-added} και το [εσωθεν]{.greek-omitted} [εξωθεν]{.greek-added} εποιησεν[11:40]{.aside}

πλην τα ενοντα δοτε ελεημοσυνην και ιδου παντα καθαρα υμιν εστιν[11:41]{.aside}

αλλ ουαι υμιν τοις φαρισαιοις οτι αποδεκατουτε το ηδυοσμον και το πηγανον και παν λαχανον και παρερχεσθε την κρισιν και την αγαπην του [θεου]{.greek-abbr} ταυτα εδει ποιησαι κακεινα μη αφιεναι[11:42]{.aside}

ουαι υμιν τοις φαρισαιοις οτι αγαπατε την πρωτοκαθεδριαν εν ταις συναγωγαις και τους ασπασμους εν ταις αγοραις[11:43]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι εστε ως τα μνημεια τα αδηλα και οι [ανθρωποι]{.greek-abbr} περιπατουντες επανω ουκ οιδασιν[11:44]{.aside}

αποκριθεις δε τις των νομικων λεγει αυτω διδασκαλε ταυτα λεγων και ημας υβριζεις[11:45]{.aside}

ο δε ειπεν και υμιν τοις νομικοις ουαι οτι φορτιζετε τους [ανθρωπους]{.greek-abbr} φορτια δυσβαστακτα και αυτοι ενι των δακτυλων υμων ου προσψαυετε τοις φορτιοις[11:46]{.aside}

ουαι υμιν οτι οικοδομειτε τα μνημεια των προφητων οι δε [πατερες]{.greek-abbr} υμων απεκτειναν αυτους[11:47]{.aside}

αρα μαρτυρειτε και συνευδοκειτε τοις εργοις των [πατερων]{.greek-abbr} υμων οτι αυτοι μεν απεκτειναν αυτους υμεις δε οικοδομειτε αυτων τα μνημεια[11:48]{.aside}

δια τουτο και η σοφια του [θεου]{.greek-abbr} ειπεν αποστελω εις [αυ]{.greek-added} [αυτους]{.greek-omitted} [τους]{.greek-added} προφητας και αποστολους και εξ αυτων [αποκτενουσιν]{.greek-omitted} [αποκτενουσι]{.greek-added} και εκδιωξουσιν[11:49]{.aside}

ινα εκζητηθη το αιμα παντων των προφητων το εκχυνομενον απο καταβολης κοσμου απο της γενεας ταυτης[11:50]{.aside}

απο του αιματος αβελ εως του αιματος ζαχαριου [υιου]{.greek-added} [βαραχιου]{.greek-added} του απολομενου μεταξυ του θυσιαστηριου και του οικου ναι λεγω υμιν εκζητηθησεται απο της γενεας ταυτης[11:51]{.aside}

ουαι υμιν τοις νομικοις οτι ηρατε την κλειδα της γνωσεως αυτοι ουκ εισηλθετε και τους εισερχομενους εκωλυσατε[11:52]{.aside}

λεγοντος δε αυτου ταυτα προς αυτους ηρξαντο οι γραμματεις και οι φαρισαιοι δεινως ενεχειν και [αποστοματιζειν]{.greek-omitted} [αποστομιζειν]{.greek-added} αυτον περι πλειονων[11:53]{.aside}

ενεδρευοντες αυτον ζητουντες θηρευσαι τι εκ του στοματος αυτου ινα κατηγορησωσιν αυτου[11:54]{.aside}

### Chapter 12

εν οις επισυναχθεισων των μυριαδων του οχλου ωστε καταπατειν αλληλους ηρξατο λεγειν προς τους μαθητας αυτου πρωτον προσεχετε εαυτοις απο της ζυμης των φαρισαιων ητις εστιν υποκρισις[12:1]{.aside}

ουδεν δε συγκεκαλυμμενον εστιν ο ουκ αποκαλυφθησεται και κρυπτον ο ου γνωσθησεται[12:2]{.aside}

ανθ ων οσα [ειπατε]{.greek-added} εν τη σκοτια [ειπατε]{.greek-omitted} εν τω φωτι ακουσθησεται και ο προς το ους ελαλησατε εν τοις ταμειοις κηρυχθησεται επι των δωματων[12:3]{.aside}

λεγω δε υμιν τοις φιλοις μου μη φοβηθητε απο των αποκτενοντων το σωμα και μετα ταυτα μη εχοντων περισσοτερον τι ποιησαι[12:4]{.aside}

υποδειξω δε υμιν τινα φοβηθητε φοβηθητε τον μετα το αποκτειναι [εχοντα]{.greek-added} εξουσιαν [εχοντα]{.greek-omitted} εμβαλειν εις την γεενναν ναι λεγω υμιν τουτον φοβηθητε[12:5]{.aside}

ουχι πεντε στρουθια πωλειται ασσαριων δυο και εν εξ αυτων ουκ εστιν επιλελησμενον ενωπιον του [θεου]{.greek-abbr}[12:6]{.aside}

αλλα και αι τριχες της κεφαλης υμων πασαι ηριθμηνται μη ουν [φοβεισθε]{.greek-omitted} [φοβησθε]{.greek-added} πολλων στρουθιων διαφερετε[12:7]{.aside}

λεγω δε υμιν πας ος αν ομολογηση εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ομολογησει εν αυτω εμπροσθεν των αγγελων του [θεου]{.greek-abbr}[12:8]{.aside}

ο δε αρνησαμενος με ενωπιον των [ανθρωπων]{.greek-abbr} απαρνηθησεται [ενωπιον]{.greek-omitted} [εμπροσθεν]{.greek-added} των [αγιων]{.greek-added} αγγελων του [θεου]{.greek-abbr}[12:9]{.aside}

και πας ος ερει λογον εις τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω τω δε εις το [[πνευμα]{.greek-abbr}]{.greek-added} [το]{.greek-added} αγιον [πνευμα]{.greek-omitted} βλασφημησαντι ουκ αφεθησεται [αυτω]{.greek-added}[12:10]{.aside}

οταν δε [προσφερωσιν]{.greek-omitted} [προσφερουσιν]{.greek-added} υμας επι τας συναγωγας και τας αρχας και τας εξουσιας μη μεριμνατε πως η τι απολογησησθε η τι ειπητε[12:11]{.aside}

το γαρ αγιον [πνευμα]{.greek-abbr} διδαξει υμας εν αυτη τη ωρα α δει ειπειν[12:12]{.aside}

ειπεν δε τις αυτω εκ του οχλου διδασκαλε ειπε τω αδελφω μου μερισασθαι μετ εμου την κληρονομιαν[12:13]{.aside}

ο δε ειπεν αυτω [ανθρωπε]{.greek-abbr} τις με κατεστησεν δικαστην η μεριστην εφ υμας[12:14]{.aside}

ειπεν δε προς αυτους ορατε και φυλασσεσθε απο [της]{.greek-omitted} [πασης]{.greek-added} πλεονεξιας οτι ουκ εν τω περισσευειν τινι η ζωη [αυτω]{.greek-omitted} [αυτου]{.greek-added} εστιν εκ των υπαρχοντων αυτου[12:15]{.aside}

ειπεν δε παραβολην προς αυτους λεγων [ανθρωπου]{.greek-abbr} τινος πλουσιου ευφορησεν η χωρα[12:16]{.aside}

και διελογιζετο εν εαυτω λεγων τι ποιησω οτι ουκ εχω που συναξω τους καρπους μου[12:17]{.aside}

και ειπεν τουτο ποιησω καθελω μου τας αποθηκας και μειζονας οικοδομησω και συναξω εκει παντα τα γενηματα μου και τα αγαθα μου[12:18]{.aside}

και ερω τη ψυχη μου ψυχη εχεις πολλα αγαθα κειμενα εις ετη πολλα αναπαυου φαγε πιε ευφραινου[12:19]{.aside}

ειπεν δε αυτω ο [θεος]{.greek-abbr} αφρον ταυτη τη νυκτι την ψυχην σου απαιτουσιν απο σου α δε ητοιμασας τινι εσται[12:20]{.aside}

ουτως ο θησαυριζων εαυτω και μη εις [θεον]{.greek-abbr} πλουτων[12:21]{.aside}

ειπεν δε προς τους μαθητας αυτου δια τουτο υμιν λεγω μη μεριμνατε τη ψυχη υμων τι φαγητε μηδε τω σωματι [υμων]{.greek-added} τι ενδυσησθε[12:22]{.aside}

η [γαρ]{.greek-added} ψυχη πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} της τροφης και το σωμα του ενδυματος[12:23]{.aside}

κατανοησατε τους κορακας οτι ου σπειρουσιν ουδε θεριζουσιν οις ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} ταμειον ουδε αποθηκη και ο [θεος]{.greek-abbr} τρεφει αυτους ποσω μαλλον υμεις διαφερετε των πετεινων[12:24]{.aside}

τις δε εξ υμων μεριμνων δυναται προσθειναι επι την ηλικιαν αυτου πηχυν ενα[12:25]{.aside}

ει ουν ουτε ελαχιστον δυνασθε τι περι των λοιπων μεριμνατε[12:26]{.aside}

κατανοησατε τα κρινα πως αυξανει ου κοπια ουδε νηθει λεγω δε υμιν [οτι]{.greek-added} ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[12:27]{.aside}

ει δε τον χορτον [σημερον]{.greek-added} [τον]{.greek-added} εν τω αγρω [σημερον]{.greek-omitted} οντα και αυριον εις κλιβανον βαλλομενον ο [θεος]{.greek-abbr} ουτως [αμφιεννυσιν]{.greek-omitted} [αμφιεννυσι]{.greek-added} ποσω μαλλον υμας ολιγοπιστοι[12:28]{.aside}

και υμεις μη ζητειτε τι φαγητε η τι πιητε και μη μετεωριζεσθε[12:29]{.aside}

ταυτα γαρ παντα τα εθνη του κοσμου επιζητει υμων δε ο [πατηρ]{.greek-abbr} οιδεν οτι [χρηζετε]{.greek-omitted} [χρειζετε]{.greek-added} τουτων[12:30]{.aside}

πλην ζητειτε την βασιλειαν του [θεου]{.greek-abbr} και ταυτα παντα προστεθησεται υμιν[12:31]{.aside}

μη φοβου το μικρον ποιμνιον οτι ευδοκησεν ο [πατηρ]{.greek-abbr} υμων δουναι υμιν την βασιλειαν[12:32]{.aside}

πωλησατε τα υπαρχοντα υμων και δοτε ελεημοσυνην ποιησατε εαυτοις [βαλαντια]{.greek-omitted} [βαλλαντια]{.greek-added} μη παλαιουμενα θησαυρον ανεκλειπτον εν τοις [ουρανοις]{.greek-abbr} οπου κλεπτης ουκ εγγιζει ουδε σης διαφθειρει[12:33]{.aside}

οπου γαρ εστιν ο θησαυρος υμων εκει και η καρδια υμων εσται[12:34]{.aside}

εστωσαν [υμων]{.greek-omitted} αι οσφυες [υμων]{.greek-added} περιεζωσμεναι και οι λυχνοι [και]{.greek-added} [καιομενοι]{.greek-omitted} [ομενοι]{.greek-added}[12:35]{.aside}

και υμεις ομοιοι [ανθρωποις]{.greek-abbr} προσδεχομενοις τον κυριον εαυτων ποτε [αναλυση]{.greek-omitted} [αναλυσει]{.greek-added} εκ των γαμων ινα ελθοντος και κρουσαντος [αυτου]{.greek-added} ευθεως ανοιξωσιν αυτω[12:36]{.aside}

μακαριοι οι δουλοι εκεινοι ους ελθων ο κυριος ευρησει γρηγορουντας αμην λεγω υμιν οτι περιζωσεται και ανακλινει αυτους και παρελθων διακονησει αυτοις[12:37]{.aside}

και εαν ελθη εν τη δευτερα φυλακη και [εαν]{.greek-added} εν τη τριτη φυλακη ελθη και ευρη ουτως μακαριοι εισιν οι δουλοι εκεινοι[12:38]{.aside}

τουτο δε γινωσκετε οτι ει ηδει ο οικοδεσποτης ποια ωρα ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} διορυγηναι τον οικον αυτου[12:39]{.aside}

και υμεις ουν γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχεται[12:40]{.aside}

ειπεν δε αυτω ο πετρος [κυριε]{.greek-abbr} προς ημας την παραβολην ταυτην λεγεις η [και]{.greek-omitted} προς παντας[12:41]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} τις αρα εστιν ο πιστος οικονομος και φρονιμος ον καταστησει ο [κυριος]{.greek-abbr} επι της θεραπειας αυτου του διδοναι εν καιρω το σιτομετριον[12:42]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο κυριος αυτου ευρησει ποιουντα ουτως[12:43]{.aside}

αληθως λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[12:44]{.aside}

εαν δε ειπη ο [κακος]{.greek-added} δουλος εκεινος εν τη καρδια αυτου χρονιζει ο κυριος μου ερχεσθαι και αρξηται τυπτειν τους παιδας και τας παιδισκας εσθιειν τε και πινειν και μεθυσκεσθαι[12:45]{.aside}

ηξει ο κυριος του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει και διχοτομησει αυτον και το μερος αυτου μετα των απιστων θησει[12:46]{.aside}

εκεινος δε ο δουλος ο γνους το θελημα του κυριου εαυτου και μη ετοιμασας μηδε ποιησας προς το θελημα αυτου δαρησεται πολλας[12:47]{.aside}

ο δε μη γνους ποιησας δε αξια πληγων δαρησεται ολιγας παντι δε ω εδοθη πολυ πολυ ζητηθησεται παρ αυτου και ω παρεθεντο πολυ περισσοτερον [αιτησουσιν]{.greek-omitted} [απαιτησουσιν]{.greek-added} αυτον[12:48]{.aside}

πυρ ηλθον βαλειν εις την γην και τι θελω ει ηδη ανηφθη[12:49]{.aside}

βαπτισμα δε εχω βαπτισθηναι και πως συνεχομαι εως [ου]{.greek-omitted} [οτου]{.greek-added} τελεσθη[12:50]{.aside}

δοκειτε οτι ειρηνην παρεγενομην δουναι εν τη γη ουχι λεγω υμιν αλλ η διαμερισμον[12:51]{.aside}

εσονται γαρ απο του νυν πεντε εν οικω ενι διαμεμερισμενοι τρεις επι [δυσιν]{.greek-omitted} [δυσι]{.greek-added} και δυο επι [τρισιν]{.greek-omitted} [τρισι]{.greek-added}[12:52]{.aside}

διαμερισθησεται [πατηρ]{.greek-abbr} επι υιω και [υιος]{.greek-abbr} επι [πατρι]{.greek-abbr} [μητηρ]{.greek-abbr} επι θυγατρι και θυγατηρ επι [μητρι]{.greek-abbr} πενθερα επι την νυμφην αυτης και νυμφη επι την πενθεραν αυτης[12:53]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε και τοις οχλοις οταν ιδητε την νεφελην ανατελλουσαν [απο]{.greek-omitted} [επι]{.greek-added} δυσμων ευθεως λεγετε ομβρος ερχεται και γινεται ουτως[12:54]{.aside}

και οταν νοτον [πνεοντα]{.greek-omitted} [πνεον]{.greek-added} [τα]{.greek-added} λεγετε οτι καυσων εσται και γινεται[12:55]{.aside}

υποκριται το προσωπον της γης και του [ουρανου]{.greek-abbr} οιδατε δοκιμαζειν τον δε καιρον τουτον πως ου δοκιμαζετε[12:56]{.aside}

τι δε και αφ εαυτων ου κρινετε το δικαιον[12:57]{.aside}

ως γαρ υπαγεις μετα του αντιδικου σου επ αρχοντα εν τη οδω δος εργασιαν απηλλαχθαι απ αυτου μηποτε κατασυρη σε προς τον κριτην και ο κριτης σε παραδω τω πρακτορι και ο πρακτωρ σε βαλη εις φυλακην[12:58]{.aside}

λεγω σοι ου μη εξελθης εκειθεν εως ου και [τον]{.greek-omitted} [το]{.greek-added} εσχατον λεπτον αποδως[12:59]{.aside}

### Chapter 13

παρησαν δε τινες εν αυτω τω καιρω [απαγγελλοντες]{.greek-omitted} [απαγγελοντες]{.greek-added} αυτω περι των γαλιλαιων ων το αιμα [ο]{.greek-added} πιλατος [εμιξεν]{.greek-omitted} [εμιξε]{.greek-added} μετα των θυσιων αυτων[13:1]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις δοκειτε οτι οι [γαλιλαιοι]{.greek-omitted} [γαλιλαι]{.greek-added} ουτοι αμαρτωλοι παρα παντας τους γαλιλαιους εγενοντο οτι τοιαυτα πεπονθασιν[13:2]{.aside}

ουχι λεγω υμιν αλλ εαν μη μετανοητε παντες ωσαυτως απολεισθε[13:3]{.aside}

η εκεινοι οι δεκα και οκτω εφ ους επεσεν ο πυργος εν τω σιλωαμ και απεκτεινεν αυτους δοκειτε οτι [ουτοι]{.greek-omitted} [αυτοι]{.greek-added} [οφειλεται]{.greek-omitted} [οφειλετε]{.greek-added} εγενοντο παρα παντας [ανθρωπους]{.greek-abbr} τους κατοικουντας [εν]{.greek-omitted} [ιερουσαλημ]{.greek-abbr}[13:4]{.aside}

ουχι λεγω υμιν αλλ εαν μη μετανοητε παντες [ομοιως]{.greek-omitted} [ωσαυτως]{.greek-added} απολεισθε[13:5]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε ταυτην την παραβολην συκην [ειχεν]{.greek-omitted} [ειχε]{.greek-added} τις εν τω αμπελωνι αυτου πεφυτευμενην και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} ζητων καρπον εν αυτη και ουχ ευρεν[13:6]{.aside}

ειπεν δε προς τον αμπελουργον ιδου τρια ετη ερχομαι ζητων καρπον εν τη συκη ταυτη και ουχ ευρισκω εκκοψον [ουν]{.greek-added} αυτην [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} και την γην [καταργει]{.greek-omitted} [καταργη]{.greek-added}[13:7]{.aside}

ο δε αποκριθεις λεγει αυτω [κυριε]{.greek-abbr} αφες αυτην και τουτο το ετος εως οτου σκαψω περι αυτην και βαλω κοπρια[13:8]{.aside}

καν μεν ποιηση [καρπον]{.greek-omitted} [καρ]{.greek-added} [πον]{.greek-added} ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} εις το μελλον εκκοψεις αυτην[13:9]{.aside}

ην δε διδασκων εν μια των συναγωγων εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added}[13:10]{.aside}

και ιδου γυνη ην πνευμα εχουσα ασθενειας ετη δεκα και οκτω και ην συγκυπτουσα και μη δυναμενη ανακυψαι εις το παντελες[13:11]{.aside}

ιδων δε αυτην ο [ιησους]{.greek-abbr} [προσεφωνησεν]{.greek-omitted} [προσεφωνησε]{.greek-added} και ειπεν αυτη γυναι απολελυσαι [απο]{.greek-added} της ασθενειας σου[13:12]{.aside}

και επεθηκεν [επ]{.greek-added} αυτη τας χειρας και παραχρημα ανωρθωθη και [εδοξαζεν]{.greek-omitted} [εδοξαζε]{.greek-added} τον [θεον]{.greek-abbr}[13:13]{.aside}

αποκριθεις δε ο αρχισυναγωγος αγανακτων οτι τω σαββατω εθεραπευσεν ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τω οχλω εξ ημεραι εισιν εν αις δει εργαζεσθαι εν ταυταις ουν ερχομενοι θεραπευεσθε και μη τη ημερα του σαββατου[13:14]{.aside}

απεκριθη ουν αυτω ο [κυριος]{.greek-abbr} και ειπεν υποκριται εκαστος υμων τω σαββατω ου λυει τον βουν αυτου η τον ονον απο της φατνης και [απαγαγων]{.greek-omitted} [απαγα]{.greek-added} [γων]{.greek-added} ποτιζει[13:15]{.aside}

ταυτην δε [θυγατερα]{.greek-omitted} [θυγατεραν]{.greek-added} αβρααμ ουσαν ην εδησεν ο σατανας ιδου δεκα και οκτω ετη ουκ εδει λυθηναι απο του δεσμου τουτου τη ημερα του σαββατου[13:16]{.aside}

και ταυτα λεγοντος αυτου κατησχυνοντο παντες οι αντικειμενοι αυτω και πας ο οχλος εχαιρεν επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ενδοξοις τοις γινομενοις υπ αυτου[13:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε τινι ομοια εστιν η βασιλεια του [θεου]{.greek-abbr} και τινι ομοιωσω αυτην[13:18]{.aside}

ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} κοκκω σιναπεως ον λαβων [ανθρωπος]{.greek-abbr} εβαλεν εις κηπον εαυτου και [ηυξησεν]{.greek-omitted} [ηυξησε]{.greek-added} και εγενετο εις δενδρον μεγα και τα πετεινα του [ουρανου]{.greek-abbr} κατεσκηνωσεν εν τοις κλαδοις αυτου[13:19]{.aside}

παλιν ειπεν τινι ομοιωσω την βασιλειαν του [θεου]{.greek-abbr}[13:20]{.aside}

ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} ζυμη ην λαβουσα γυνη ενεκρυψεν εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:21]{.aside}

και διεπορευετο κατα πολεις και κωμας διδασκων και πορειαν ποιουμενος εις [ιερουσαλημ]{.greek-abbr}[13:22]{.aside}

ειπεν δε τις αυτω [κυριε]{.greek-abbr} ει ολιγοι οι σωζομενοι ο δε ειπεν προς αυτους[13:23]{.aside}

αγωνιζεσθε εισελθειν δια της στενης πυλης οτι πολλοι λεγω υμιν ζητησουσιν εισελθειν και ουκ ισχυσουσιν[13:24]{.aside}

αφ ου αν εγερθη ο οικοδεσποτης και αποκλειση την θυραν και αρξησθε εξω εσταναι και κρουειν την θυραν λεγοντες [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν και αποκριθεις ερει υμιν ουκ οιδα υμας ποθεν εστε[13:25]{.aside}

τοτε [αρξεσθε]{.greek-omitted} [αρξησθε]{.greek-added} λεγειν εφαγομεν ενωπιον σου και επιομεν και εν ταις πλατειαις ημων εδιδαξας[13:26]{.aside}

και ερει λεγω υμιν ουκ οιδα υμας ποθεν εστε αποστητε απ εμου παντες οι εργαται της αδικιας[13:27]{.aside}

εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων οταν [οψησθε]{.greek-omitted} [οψεσθε]{.greek-added} αβρααμ και ισαακ και ιακωβ και παντας τους προφητας εν τη [βα]{.greek-added} [βασιλεια]{.greek-omitted} [σιλεια]{.greek-added} του [θεου]{.greek-abbr} υμας δε εκβαλλομενους εξω[13:28]{.aside}

και ηξουσιν απο ανατολων και δυσμων και βορρα και νοτου και ανακλιθησονται εν τη βασιλεια του [θεου]{.greek-abbr}[13:29]{.aside}

και ιδου εισιν εσχατοι οι εσονται πρωτοι και [εισιν]{.greek-omitted} [εισι]{.greek-added} πρωτοι οι εσονται εσχατοι[13:30]{.aside}

εν αυτη τη ημερα προσηλθον τινες φαρισαιοι λεγοντες αυτω εξελθε και πορευου εντευθεν οτι ηρωδης θελει σε αποκτειναι[13:31]{.aside}

και ειπεν αυτοις πορευθεντες ειπατε τη αλωπεκι ταυτη ιδου εκβαλλω δαιμονια και ιασεις επιτελω σημερον και αυριον και τη τριτη τελειουμαι[13:32]{.aside}

πλην δει με σημερον και αυριον και τη εχομενη πορευεσθαι οτι ουκ ενδεχεται προφητην απολεσθαι εξω [ιερουσαλημ]{.greek-abbr}[13:33]{.aside}

[ιερουσαλημ]{.greek-abbr} ιερουσαλημ η αποκτενουσα τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα [επισυναξαι]{.greek-omitted} [επισυνα]{.greek-added} [ξαι]{.greek-added} τα τεκνα σου ον τροπον ορνις την εαυτης νοσσιαν υπο τας πτερυγας και ουκ ηθελησατε[13:34]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος λεγω δε υμιν οτι ου μη με ιδητε εως αν [ηξει]{.greek-omitted} [οτε]{.greek-omitted} [ηξη]{.greek-added} [οταν]{.greek-added} ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[13:35]{.aside}

### Chapter 14

και εγενετο εν τω ελθειν αυτον εις οικον τινος των αρχοντων των φαρισαιων σαββατω φαγειν αρτον και αυτοι ησαν παρατηρουμενοι αυτον[14:1]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} τις ην [υδρωπικος]{.greek-omitted} [υδροπικος]{.greek-added} εμπροσθεν αυτου[14:2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν προς τους νομικους και φαρισαιους λεγων ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τω σαββατω θεραπευειν[14:3]{.aside}

οι δε ησυχασαν και επιλαβομενος ιασατο αυτον και απελυσεν[14:4]{.aside}

και αποκριθεις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ειπεν]{.greek-added} προς αυτους [ειπεν]{.greek-omitted} τινος υμων [υιος]{.greek-abbr} η βους εις φρεαρ [εμπεσειται]{.greek-omitted} [πεσειται]{.greek-added} [και]{.greek-omitted} ουκ ευθεως ανασπασει αυτον εν τη ημερα του σαββατου[14:5]{.aside}

και ουκ ισχυσαν [αντα]{.greek-added} [ανταποκριθηναι]{.greek-omitted} [ποκριθηναι]{.greek-added} αυτω προς ταυτα[14:6]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε προς τους κεκλημενους παραβολην επεχων πως τας πρωτοκλισιας εξελεγοντο λεγων προς αυτους[14:7]{.aside}

οταν κληθης υπο τινος εις γαμους μη κατακλιθης εις την πρωτοκλισιαν μηποτε εντιμοτερος σου η κεκλημενος υπ αυτου[14:8]{.aside}

και ελθων ο σε και αυτον καλεσας ερει σοι δος τουτω τοπον και τοτε αρξη [μετ]{.greek-omitted} [μετα]{.greek-added} αισχυνης τον εσχατον τοπον κατεχειν[14:9]{.aside}

αλλ οταν κληθης πορευθεις αναπεσε εις τον εσχατον τοπον ινα οταν ελθη ο [κεκληκως]{.greek-omitted} [κεκληκος]{.greek-added} σε ειπη σοι φιλε προσαναβηθι ανωτερον τοτε εσται σοι δοξα ενωπιον των συνανακειμενων σοι[14:10]{.aside}

οτι πας ο υψων εαυτον ταπεινωθησεται και ο ταπεινων εαυτον υψωθησεται[14:11]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε και τω κεκληκοτι αυτον οταν ποιης αριστον η δειπνον μη φωνει τους φιλους σου μηδε τους αδελφους σου μηδε τους συγγενεις σου μηδε γειτονας πλουσιους μηποτε και αυτοι σε [αντικαλεσωσιν]{.greek-omitted} [αντικαλεσωσι]{.greek-added} και γενηται σοι ανταποδομα[14:12]{.aside}

αλλ οταν ποιης δοχην καλει [πτωχους]{.greek-omitted} [πτοχους]{.greek-added} αναπηρους χωλους τυφλους[14:13]{.aside}

και μακαριος εση οτι ουκ εχουσιν ανταποδουναι σοι ανταποδοθησεται γαρ σοι εν τη αναστασει των δικαιων[14:14]{.aside}

ακουσας δε τις των συνανακειμενων ταυτα ειπεν αυτω μακαριος ος φαγεται αριστον εν τη βασιλεια του [θεου]{.greek-abbr}[14:15]{.aside}

ο δε ειπεν αυτω [ανθρωπος]{.greek-abbr} τις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δειπνον μεγα και [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} πολλους[14:16]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον δουλον αυτου τη ωρα του δειπνου ειπειν τοις κεκλημενοις ερχεσθε οτι ηδη ετοιμα [εστιν]{.greek-omitted} [εστι]{.greek-added} παντα[14:17]{.aside}

και ηρξαντο απο μιας παραιτεισθαι παντες ο πρωτος ειπεν αυτω αγρον ηγορασα και εχω αναγκην εξελθειν και ιδειν αυτον ερωτω σε εχε με παρητημενον[14:18]{.aside}

και ετερος ειπεν ζευγη βοων ηγορασα πεντε και πορευομαι δοκιμασαι αυτα ερωτω σε εχε με παρητημενον[14:19]{.aside}

και ετερος ειπεν γυναικα εγημα και δια τουτο ου [δυναμαι]{.greek-omitted} [δυναμε]{.greek-added} ελθειν[14:20]{.aside}

και παραγενομενος ο δουλος [εκεινος]{.greek-omitted} [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τω [κυριω]{.greek-abbr} αυτου ταυτα τοτε οργισθεις ο οικοδεσποτης ειπεν τω δουλω αυτου εξελθε ταχεως εις τας πλατειας και ρυμας της πολεως και τους πτωχους και αναπηρους και [τυφλους]{.greek-added} [και]{.greek-added} χωλους [και]{.greek-omitted} [τυφλους]{.greek-omitted} εισαγαγε ωδε[14:21]{.aside}

και ειπεν ο δουλος [κυριε]{.greek-abbr} γεγονεν ως επεταξας και ετι τοπος [εστιν]{.greek-omitted} [εστι]{.greek-added}[14:22]{.aside}

και ειπεν ο κυριος προς τον δουλον εξελθε εις τας οδους και φραγμους και αναγκασον εισελθειν ινα γεμισθη ο οικος μου[14:23]{.aside}

λεγω γαρ υμιν οτι ουδεις των ανδρων εκεινων των κεκλημενων γευσεται μου του δειπνου [πολλοι]{.greek-omitted} [γαρ]{.greek-omitted} [εισιν]{.greek-omitted} [κλητοι]{.greek-omitted} [ολιγοι]{.greek-omitted} [δε]{.greek-omitted} [εκλεκτοι]{.greek-omitted}[14:24]{.aside}

συνεπορευοντο δε αυτω οχλοι πολλοι και στραφεις ειπεν προς αυτους[14:25]{.aside}

ει τις ερχεται προς με και ου μισει τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και την γυναικα και τα τεκνα και τους αδελφους και τας αδελφας ετι δε και την εαυτου ψυχην ου δυναται μου μαθητης ειναι[14:26]{.aside}

και [οστις]{.greek-omitted} [ος]{.greek-added} ου βασταζει τον [σταυρον]{.greek-abbr} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} και ερχεται οπισω μου ου δυναται [μου]{.greek-added} ειναι [μου]{.greek-omitted} μαθητης[14:27]{.aside}

τις γαρ εξ υμων ο θελων πυργον οικοδομησαι ουχι πρωτον καθισας ψηφιζει την δαπανην ει εχει τα εις απαρτισμον[14:28]{.aside}

ινα μηποτε θεντος αυτου θεμελιον και μη ισχυοντος εκτελεσαι παντες οι θεωρουντες αρξωνται [αυτω]{.greek-added} εμπαιζειν [αυτω]{.greek-omitted}[14:29]{.aside}

λεγοντες οτι ουτος ο [ανθρωπος]{.greek-abbr} ηρξατο οικοδομειν και ουκ ισχυσεν εκτελεσαι[14:30]{.aside}

η τις βασιλευς πορευομενος συμβαλειν ετερω [βασιλει]{.greek-omitted} [βασι]{.greek-added} [λει]{.greek-added} εις πολεμον ουχι καθισας πρωτον βουλευεται ει δυνατος εστιν εν δεκα χιλιασιν απαντησαι τω μετα εικοσι χιλιαδων ερχομενω επ αυτον[14:31]{.aside}

ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ετι πορρω αυτου οντος πρεσβειαν αποστειλας ερωτα τα προς ειρηνην[14:32]{.aside}

ουτως ουν πας εξ υμων ος ουκ αποτασσεται πασιν τοις εαυτου υπαρχουσιν ου δυναται μου ειναι μαθητης[14:33]{.aside}

καλον το αλας εαν δε το αλας μωρανθη εν τινι αρτυθησεται[14:34]{.aside}

ουτε εις γην ουτε εις κοπριαν ευθετον εστιν εξω [βαλλουσιν]{.greek-omitted} [βαλουσιν]{.greek-added} αυτο ο εχων ωτα ακουειν ακουετω[14:35]{.aside}

### Chapter 15

ησαν δε [αυτω]{.greek-added} εγγιζοντες [αυτω]{.greek-omitted} παντες οι τελωναι και οι αμαρτωλοι ακουειν αυτου[15:1]{.aside}

και [διεγογγυζον]{.greek-omitted} [εγογγυζον]{.greek-added} οι φαρισαιοι και οι γραμματεις λεγοντες οτι ουτος αμαρτωλους προσδεχεται και συνεσθιει αυτοις[15:2]{.aside}

ειπεν δε προς αυτους την παραβολην ταυτην λεγων[15:3]{.aside}

τις [ανθρωπος]{.greek-abbr} εξ υμων εχων εκατον προβατα και απολεσας εν εξ αυτων ου καταλειπει τα ενενηκοντα εννεα εν τη ερημω και πορευεται επι το απολωλος εως ευρη αυτο[15:4]{.aside}

και ευρων επιτιθησιν επι τους ωμους εαυτου χαιρων[15:5]{.aside}

και ελθων εις τον οικον [συγκαλει]{.greek-omitted} [συγκαλειται]{.greek-added} τους φιλους και τους γειτονας λεγων αυτοις συγχαρητε μοι οτι ευρον το προβατον μου το απολωλος[15:6]{.aside}

λεγω υμιν οτι ουτως χαρα εσται εν τω [ουρανω]{.greek-abbr} επι ενι αμαρτωλω μετανοουντι η επι ενενηκοντα εννεα δικαιοις οιτινες ου χρειαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} μετανοιας[15:7]{.aside}

η τις γυνη δραχμας εχουσα δεκα εαν απολεση δραχμην μιαν ουχι απτει λυχνον και σαροι την οικιαν και ζητει επιμελως εως [οτου]{.greek-omitted} ευρη[15:8]{.aside}

και ευρουσα συγκαλειται τας φιλας και τας γειτονας λεγουσα συγχαρητε μοι οτι ευρον την δραχμην ην απωλεσα[15:9]{.aside}

ουτως λεγω υμιν χαρα γινεται ενωπιον των αγγελων του [θεου]{.greek-abbr} επι ενι αμαρτωλω μετανοουντι[15:10]{.aside}

ειπεν δε [ανθρωπος]{.greek-abbr} τις [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δυο υιους[15:11]{.aside}

και ειπεν ο νεωτερος αυτων τω [πατρι]{.greek-abbr} [πατερ]{.greek-abbr} δος μοι το επιβαλλον μερος της ουσιας και διειλεν αυτοις τον βιον[15:12]{.aside}

και μετ ου πολλας ημερας συναγαγων [απαντα]{.greek-omitted} [παντα]{.greek-added} ο νεωτερος [υιος]{.greek-abbr} απεδημησεν εις χωραν μακραν και εκει [διεσκορπισεν]{.greek-omitted} [διεσκορπισε]{.greek-added} την ουσιαν αυτου ζων ασωτως[15:13]{.aside}

δαπανησαντος δε αυτου παντα εγενετο λιμος ισχυρος κατα την χωραν εκεινην και αυτος ηρξατο υστερεισθαι[15:14]{.aside}

και πορευθεις εκολληθη ενι των πολιτων της χωρας εκεινης και επεμψεν αυτον [ο]{.greek-added} [πολιτης]{.greek-added} εις [τους]{.greek-omitted} [αγρους]{.greek-omitted} [τον]{.greek-added} [αγρον]{.greek-added} αυτου βοσκειν χοιρους[15:15]{.aside}

και επεθυμει [χορτασθηναι]{.greek-added} [εκ]{.greek-added} [γεμισαι]{.greek-omitted} [την]{.greek-omitted} [κοιλιαν]{.greek-omitted} [αυτου]{.greek-omitted} [απο]{.greek-omitted} των κερατιων ων ησθιον οι χοιροι και ουδεις εδιδου [αυτω]{.greek-omitted} [αυτον]{.greek-added}[15:16]{.aside}

εις εαυτον δε ελθων ειπεν ποσοι μισθιοι του [πατρος]{.greek-abbr} μου περισσευουσιν αρτων εγω δε λιμω [απολλυμαι]{.greek-omitted} [ωδε]{.greek-added} [απολ]{.greek-added} [λυμαι]{.greek-added}[15:17]{.aside}

αναστας πορευσομαι προς τον [πατερα]{.greek-abbr} μου και ερω αυτω [πατερ]{.greek-abbr} ημαρτον εις τον [ουρανον]{.greek-abbr} και ενωπιον σου[15:18]{.aside}

και ουκετι ειμι αξιος κληθηναι [υιος]{.greek-abbr} σου ποιησον με ως ενα των μισθιων σου[15:19]{.aside}

και αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [πατερα]{.greek-abbr} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} ετι δε αυτου μακραν απεχοντος ειδεν αυτον ο [πατηρ]{.greek-abbr} αυτου και εσπλαγχνισθη και δραμων επεπεσεν επι τον τραχηλον αυτου και κατεφιλησεν αυτον[15:20]{.aside}

ειπεν δε αυτω ο [υιος]{.greek-abbr} [πατερ]{.greek-abbr} ημαρτον εις τον [ουρανον]{.greek-abbr} και ενωπιον σου και ουκετι ειμι αξιος κληθηναι [υιος]{.greek-abbr} σου[15:21]{.aside}

ειπεν δε ο [πατηρ]{.greek-abbr} προς τους δουλους αυτου εξενεγκατε την στολην την πρωτην και ενδυσατε αυτον και δοτε δακτυλιον εις την χειρα αυτου και υποδηματα εις τους ποδας [αυτου]{.greek-added}[15:22]{.aside}

και ενεγκαντες τον μοσχον τον σιτευτον θυσατε και φαγοντες ευφρανθωμεν[15:23]{.aside}

οτι ουτος ο [υιος]{.greek-abbr} μου νεκρος ην και [ανεζησεν]{.greek-omitted} [ανε]{.greek-added} [ζησε]{.greek-added} και [απολωλως]{.greek-omitted} [απολωλος]{.greek-added} [ην]{.greek-omitted} και ευρεθη και ηρξαντο ευφραινεσθαι[15:24]{.aside}

ην δε ο [υιος]{.greek-abbr} αυτου ο πρεσβυτερος εν αγρω και ως ερχομενος ηγγισεν τη οικια [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} συμφωνιας και χορων[15:25]{.aside}

και προσκαλεσαμενος ενα των [παιδων]{.greek-omitted} [δουλων]{.greek-added} επυνθανετο τι ειη ταυτα[15:26]{.aside}

ο δε ειπεν αυτω οτι ο αδελφος σου ηκει και εθυσεν ο [πατηρ]{.greek-abbr} σου τον μοσχον τον σιτευτον οτι υγιαινοντα αυτον απελαβεν[15:27]{.aside}

ωργισθη δε και ουκ ηθελεν εισελθειν ο ουν [πατηρ]{.greek-abbr} αυτου εξελθων παρεκαλει αυτον[15:28]{.aside}

ο δε αποκριθεις ειπεν τω [πατρι]{.greek-abbr} ιδου τοσαυτα ετη [εχω]{.greek-added} [δουλευω]{.greek-omitted} [δουλευων]{.greek-added} σοι και ουδεποτε εντολην σου παρηλθον και εμοι ουδεποτε εδωκας εριφον ινα μετα των φιλων μου ευφρανθω[15:29]{.aside}

οτε δε ο [υιος]{.greek-abbr} σου ουτος ο καταφαγων σου τον βιον μετα πορνων ηλθεν εθυσας αυτω τον μοσχον τον σιτευτον[15:30]{.aside}

ο δε ειπεν αυτω τεκνον συ παντοτε μετ εμου ει και παντα τα εμα σα εστιν[15:31]{.aside}

ευφρανθηναι δε και χαρηναι εδει οτι ο αδελφος σου ουτος νεκρος ην και [ανεζησεν]{.greek-omitted} [ανεζησε]{.greek-added} και [απολωλως]{.greek-omitted} [απολωλος]{.greek-added} ην και ευρεθη[15:32]{.aside}

### Chapter 16

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε και προς τους μαθητας αυτου [ανθρωπος]{.greek-abbr} τις ην πλουσιος ος ειχεν οικονομον και ουτος διεβληθη αυτω ως διασκορπιζων τα υπαρχοντα αυτου[16:1]{.aside}

και φωνησας αυτον ειπεν αυτω τι τουτο ακουω περι σου αποδος τον λογον της οικονομιας σου ου γαρ δυνηση ετι οικονομειν[16:2]{.aside}

ειπεν δε εν εαυτω ο οικονομος τι ποιησω οτι ο κυριος μου [αφαιρειται]{.greek-omitted} [αφαιρειτε]{.greek-added} την οικονομιαν απ εμου σκαπτειν ουκ ισχυω επαιτειν αισχυνομαι[16:3]{.aside}

εγνων τι ποιησω ινα οταν μετασταθω της οικονομιας δεξωνται με εις τους οικους αυτων[16:4]{.aside}

και προσκαλεσαμενος ενα εκαστον των χρεωφειλετων του κυριου [εαυτου]{.greek-omitted} [αυτου]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τω πρωτω [πο]{.greek-added} [ποσον]{.greek-omitted} [σον]{.greek-added} οφειλεις τω κυριω μου[16:5]{.aside}

ο δε ειπεν εκατον βατους ελαιου και ειπεν αυτω δεξαι σου το γραμμα και καθισας ταχεως γραψον πεντηκοντα[16:6]{.aside}

επειτα ετερω ειπεν συ δε ποσον οφειλεις ο δε ειπεν εκατον κορους σιτου και λεγει αυτω δεξαι σου το γραμμα και γραψον ογδοηκοντα[16:7]{.aside}

και επηνεσεν ο κυριος τον οικονομον της αδικιας οτι φρονιμως εποιησεν οτι οι υιοι του αιωνος τουτου φρονιμωτεροι υπερ τους υιους του φωτος εις την γενεαν την εαυτων [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:8]{.aside}

καγω υμιν λεγω ποιησατε εαυτοις φιλους εκ του μαμωνα της αδικιας ινα οταν [εκλιπητε]{.greek-omitted} [εκλειπητε]{.greek-added} δεξωνται υμας εις τας αιωνιους σκηνας[16:9]{.aside}

ο πιστος εν ελαχιστω και εν πολλω πιστος [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο εν ελαχιστω αδικος και εν πολλω αδικος εστιν[16:10]{.aside}

ει ουν εν τω αδικω μαμωνα πιστοι ουκ εγενεσθε το [αληθινον]{.greek-omitted} [αληθι]{.greek-added} [νον]{.greek-added} τις υμιν πιστευσει[16:11]{.aside}

και ει εν τω αλλοτριω πιστοι ουκ εγενεσθε το υμετερον τις υμιν δωσει[16:12]{.aside}

ουδεις οικετης δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η ενος ανθεξεται και του ετερου καταφρονησει ου δυνασθε [θεω]{.greek-abbr} δουλευειν και μαμωνα[16:13]{.aside}

ηκουον δε ταυτα παντα και οι φαρισαιοι φιλαργυροι υπαρχοντες και εξεμυκτηριζον αυτον[16:14]{.aside}

και ειπεν αυτοις υμεις εστε οι δικαιουντες εαυτους ενωπιον των [ανθρωπων]{.greek-abbr} ο δε [θεος]{.greek-abbr} γινωσκει τας καρδιας υμων οτι το εν [ανθρωποις]{.greek-abbr} υψηλον βδελυγμα ενωπιον του [θεου]{.greek-abbr}[16:15]{.aside}

ο νομος και οι προφηται εως ιωαννου απο τοτε η βασιλεια του [θεου]{.greek-abbr} ευαγγελιζεται και πας [εις]{.greek-omitted} [τις]{.greek-added} αυτην βιαζεται[16:16]{.aside}

ευκοπωτερον δε [εστιν]{.greek-omitted} [εστι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην παρελθειν η του νομου μιαν [κεραιαν]{.greek-omitted} [καιρεαν]{.greek-added} πεσειν[16:17]{.aside}

πας ο απολυων την γυναικα αυτου και γαμων ετεραν μοιχευει και πας ο απολελυμενην απο ανδρος γαμων μοιχευει[16:18]{.aside}

[ανθρωπος]{.greek-abbr} δε τις ην πλουσιος και ενεδιδυσκετο πορφυραν και βυσσον ευφραινομενος καθ ημεραν λαμπρως[16:19]{.aside}

πτωχος δε τις ην ονοματι λαζαρος ος εβεβλητο προς τον πυλωνα αυτου [ηλκωμενος]{.greek-omitted} [ειλκωμενος]{.greek-added}[16:20]{.aside}

και επιθυμων χορτασθηναι απο των ψιχιων των πιπτοντων απο της τραπεζης του πλουσιου αλλα και οι κυνες ερχομενοι απελειχον τα ελκη αυτου[16:21]{.aside}

εγενετο δε αποθανειν τον πτωχον και απενεχθηναι αυτον υπο των αγγελων εις τον κολπον [του]{.greek-added} αβρααμ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} δε και ο πλουσιος και εταφη[16:22]{.aside}

και εν τω αδη επαρας τους οφθαλμους αυτου υπαρχων εν βασανοις ορα τον αβρααμ απο μακροθεν και λαζαρον εν τοις κολποις αυτου[16:23]{.aside}

και αυτος φωνησας ειπεν [πατερ]{.greek-abbr} [αβρααμ]{.greek-omitted} [αβρα]{.greek-added} [αμ]{.greek-added} ελεησον με και πεμψον λαζαρον ινα βαψη το ακρον του δακτυλου αυτου υδατος και καταψυξη την γλωσσαν μου οτι οδυνωμαι εν τη φλογι ταυτη[16:24]{.aside}

ειπεν δε αβρααμ τεκνον μνησθητι οτι απελαβες συ τα αγαθα σου εν τη ζωη σου και λαζαρος ομοιως τα κακα νυν δε [ωδε]{.greek-omitted} [οδε]{.greek-added} παρακαλειται συ δε οδυνασαι[16:25]{.aside}

και επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τουτοις μεταξυ ημων και υμων χασμα μεγα εστηρικται οπως οι θελοντες διαβηναι ενθεν προς υμας μη δυνωνται μηδε οι εκειθεν προς ημας διαπερωσιν[16:26]{.aside}

ειπεν δε ερωτω [σε]{.greek-added} ουν [σε]{.greek-omitted} [πατερ]{.greek-abbr} ινα πεμψης αυτον εις τον οικον του [πατρος]{.greek-abbr} μου[16:27]{.aside}

εχω γαρ πεντε αδελφους οπως διαμαρτυρηται αυτοις ινα μη και αυτοι ελθωσιν εις τον τοπον τουτον της βασανου[16:28]{.aside}

λεγει αυτω αβρααμ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} μωσεα και τους [προ]{.greek-added} [προφητας]{.greek-omitted} [φητας]{.greek-added} ακουσατωσαν αυτων[16:29]{.aside}

ο δε ειπεν ουχι [πατερ]{.greek-abbr} αβρααμ αλλ εαν τις απο νεκρων πορευθη προς αυτους μετανοησουσιν[16:30]{.aside}

ειπεν δε αυτω ει μωσεως και των προφητων ουκ ακουουσιν ουδε εαν τις εκ νεκρων αναστη πεισθησονται[16:31]{.aside}

### Chapter 17

ειπεν δε προς τους μαθητας [αυτου]{.greek-added} ανενδεκτον [εστιν]{.greek-omitted} [εστι]{.greek-added} του μη ελθειν τα σκανδαλα ουαι δε δι ου ερχεται[17:1]{.aside}

λυσιτελει αυτω ει μυλος ονικος περικειται περι τον τραχηλον αυτου και [ερριπται]{.greek-omitted} [εριπται]{.greek-added} εις την θαλασσαν η ινα σκανδαλιση ενα των μικρων τουτων[17:2]{.aside}

προσεχετε εαυτοις εαν δε αμαρτη εις σε ο αδελφος σου επιτιμησον αυτω και εαν μετανοηση αφες αυτω[17:3]{.aside}

και εαν επτακις της ημερας αμαρτη εις σε και επτακις της ημερας επιστρεψη λεγων μετανοω αφησεις αυτω[17:4]{.aside}

και ειπον οι αποστολοι τω [κυριω]{.greek-abbr} προσθες ημιν πιστιν[17:5]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} ει εχετε πιστιν ως κοκκον σιναπεως ελεγετε αν τη συκαμινω ταυτη εκριζωθητι και φυτευθητι εν τη θαλασση και υπηκουσεν αν υμιν[17:6]{.aside}

τις δε εξ υμων δουλον εχων αροτριωντα η ποιμαινοντα ος εισελθοντι εκ του αγρου ερει ευθεως παρελθων αναπεσε[17:7]{.aside}

αλλ ουχι ερει αυτω ετοιμασον τι δειπνησω και περιζωσαμενος διακονει μοι εως φαγω και πιω και μετα ταυτα φαγεσαι και πιεσαι συ[17:8]{.aside}

μη χαριν εχει τω δουλω εκεινω οτι εποιησεν τα διαταχθεντα ου δοκω[17:9]{.aside}

ουτως και υμεις οταν ποιησητε [ταυτα]{.greek-added} παντα τα διαταχθεντα υμιν λεγετε οτι [αχρειοι]{.greek-added} δουλοι [αχρειοι]{.greek-omitted} εσμεν οτι ο [οφειλομεν]{.greek-omitted} [ωφειλομεν]{.greek-added} ποιησαι πεποιηκαμεν[17:10]{.aside}

και εγενετο εν τω πορευεσθαι αυτον εις [ιερουσαλημ]{.greek-abbr} και αυτος διηρχετο δια μεσου [σαμαρειας]{.greek-omitted} [σαμαριας]{.greek-added} και γαλιλαιας[17:11]{.aside}

και εισερχομενου αυτου εις τινα κωμην απηντησαν αυτω δεκα λεπροι ανδρες οι εστησαν πορρωθεν[17:12]{.aside}

και αυτοι ηραν φωνην λεγοντες [ιησου]{.greek-abbr} επιστατα ελεησον ημας[17:13]{.aside}

και ιδων ειπεν αυτοις πορευθεντες επιδειξατε εαυτους τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και εγενετο εν τω υπαγειν αυτους εκαθαρισθησαν[17:14]{.aside}

εις δε εξ αυτων ιδων οτι ιαθη υπεστρεψεν μετα φωνης μεγαλης δοξαζων τον [θεον]{.greek-abbr}[17:15]{.aside}

και επεσεν επι προσωπον παρα τους ποδας [αυτου]{.greek-omitted} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} ευχαριστων αυτω και αυτος ην σαμαρειτης[17:16]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουχι οι δεκα εκαθαρισθησαν οι δε εννεα που[17:17]{.aside}

ουχ ευρεθησαν υποστρεψαντες δουναι δοξαν τω [θεω]{.greek-abbr} ει μη ο αλλογενης ουτος[17:18]{.aside}

και ειπεν αυτω αναστας πορευου η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε[17:19]{.aside}

επερωτηθεις δε υπο των φαρισαιων ποτε ερχεται η βασιλεια του [θεου]{.greek-abbr} απεκριθη αυτοις και ειπεν ουκ ερχεται η βασιλεια του [θεου]{.greek-abbr} μετα παρατηρησεως[17:20]{.aside}

ουδε ερουσιν ιδου ωδε η ιδου εκει ιδου γαρ η βασιλεια του [θεου]{.greek-abbr} εντος υμων εστιν[17:21]{.aside}

ειπεν δε προς τους μαθητας ελευσονται ημεραι οτε επιθυμησετε μιαν των ημερων του υιου του [ανθρωπου]{.greek-abbr} ιδειν και ουκ οψεσθε[17:22]{.aside}

και ερουσιν υμιν ιδου ωδε η ιδου εκει μη απελθητε μηδε διωξητε[17:23]{.aside}

ωσπερ γαρ η αστραπη η αστραπτουσα εκ της υπ [ουρανον]{.greek-abbr} εις την υπ [ουρανον]{.greek-abbr} λαμπει ουτως εσται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τη ημερα αυτου[17:24]{.aside}

πρωτον δε δει αυτον πολλα παθειν και αποδοκιμασθηναι απο της γενεας ταυτης[17:25]{.aside}

και καθως εγενετο εν ταις ημεραις νωε ουτως εσται και εν ταις ημεραις του υιου του [ανθρωπου]{.greek-abbr}[17:26]{.aside}

ησθιον επινον εγαμουν [και]{.greek-added} εξεγαμιζοντο αχρι ης ημερας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} νωε εις την κιβωτον και ηλθεν ο κατακλυσμος και απωλεσεν απαντας[17:27]{.aside}

ομοιως και ως εγενετο εν ταις ημεραις λωτ ησθιον επινον ηγοραζον επωλουν εφυτευον ωκοδομουν[17:28]{.aside}

η δε ημερα [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} λωτ απο σοδομων [εβρεξεν]{.greek-omitted} [εβρεξε]{.greek-added} [θειον]{.greek-added} [και]{.greek-added} πυρ [και]{.greek-omitted} [θειον]{.greek-omitted} απ [ουρανου]{.greek-abbr} και απωλεσεν απαντας[17:29]{.aside}

κατα ταυτα εσται η ημερα [εν]{.greek-added} [η]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αποκαλυπτεται[17:30]{.aside}

εν εκεινη τη ημερα ος εσται επι του δωματος και τα σκευη αυτου εν τη οικια μη καταβατω αραι αυτα και ο εν [τω]{.greek-omitted} αγρω ομοιως μη επιστρεψατω εις τα οπισω[17:31]{.aside}

μνημονευετε της γυναικος λωτ[17:32]{.aside}

ος εαν ζητηση την ψυχην αυτου σωσαι απολεσει αυτην και ος εαν απολεση αυτην ζωογονησει αυτην[17:33]{.aside}

λεγω [δε]{.greek-added} υμιν [ταυτη]{.greek-omitted} [αυτη]{.greek-added} τη νυκτι [δυο]{.greek-added} εσονται [δυο]{.greek-omitted} επι κλινης μιας [ο]{.greek-added} εις παραληφθησεται και ο ετερος αφεθησεται[17:34]{.aside}

δυο εσονται αληθουσαι επι το αυτο μια παραληφθησεται και η ετερα αφεθησεται[17:35]{.aside}

και αποκριθεντες λεγουσιν αυτω που [κυριε]{.greek-abbr} ο δε ειπεν αυτοις οπου το σωμα εκει συναχθησονται οι αετοι[17:37]{.aside}

### Chapter 18

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε και παραβολην αυτοις προς το δειν παντοτε προσευχεσθαι [αυτους]{.greek-added} και μη εκκακειν[18:1]{.aside}

λεγων κριτης τις ην εν τινι πολει τον [θεον]{.greek-abbr} μη φοβουμενος και [ανθρωπον]{.greek-abbr} μη εντρεπομενος[18:2]{.aside}

χηρα δε ην εν τη πολει εκεινη και ηρχετο προς αυτον λεγουσα εκδικησον με απο του αντιδικου μου[18:3]{.aside}

και ουκ [ηθελησεν]{.greek-omitted} [ηθελεν]{.greek-added} επι χρονον μετα δε ταυτα ειπεν εν εαυτω ει και τον [θεον]{.greek-abbr} ου φοβουμαι και [ανθρωπον]{.greek-abbr} ουκ εντρεπομαι[18:4]{.aside}

δια γε το παρεχειν μοι κοπον την χηραν ταυτην εκδικησω αυτην ινα μη εις τελος ερχομενη [υποπιαζη]{.greek-omitted} [υπωπιαζει]{.greek-added} με[18:5]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} ακουσατε τι ο κριτης της αδικιας λεγει[18:6]{.aside}

ο δε [θεος]{.greek-abbr} ου μη ποιηση την εκδικησιν των εκλεκτων αυτου των βοωντων προς αυτον ημερας και νυκτος και μακροθυμων επ αυτοις[18:7]{.aside}

λεγω υμιν [οτι]{.greek-omitted} ποιησει την εκδικησιν αυτων εν ταχει πλην ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ελθων αρα ευρησει την πιστιν επι της γης[18:8]{.aside}

ειπεν δε προς τινας τους πεποιθοτας εφ εαυτοις οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} δικαιοι και εξουθενουντας τους λοιπους την παραβολην ταυτην[18:9]{.aside}

[ανθρωποι]{.greek-abbr} δυο ανεβησαν εις το ιερον προσευξασθαι ο εις φαρισαιος και ο ετερος τελωνης[18:10]{.aside}

ο φαρισαιος σταθεις προς εαυτον ταυτα προσηυχετο ο [θεος]{.greek-abbr} ευχαριστω σοι οτι ουκ ειμι ωσπερ οι λοιποι των [ανθρωπων]{.greek-abbr} αρπαγες αδικοι μοιχοι η και ως ουτος ο τελωνης[18:11]{.aside}

νηστευω δις του σαββατου αποδεκατω παντα οσα κτωμαι[18:12]{.aside}

και ο τελωνης μακροθεν εστως ουκ ηθελεν ουδε τους οφθαλμους [αυτου]{.greek-added} εις τον [ουρανον]{.greek-abbr} επαραι αλλ ετυπτεν εις το στηθος αυτου λεγων ο [θεος]{.greek-abbr} ιλασθητι μοι τω αμαρτωλω[18:13]{.aside}

λεγω υμιν κατεβη ουτος δεδικαιωμενος εις τον οικον αυτου η γαρ εκεινος οτι πας ο υψων εαυτον ταπεινωθησεται ο δε ταπεινων εαυτον υψωθησεται[18:14]{.aside}

προσεφερον δε αυτω και τα βρεφη ινα αυτων απτηται ιδοντες δε οι μαθηται επετιμησαν αυτοις[18:15]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτα ειπεν αφετε τα παιδια ερχεσθαι προς με και μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[18:16]{.aside}

αμην λεγω υμιν ος [εαν]{.greek-omitted} [αν]{.greek-added} μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[18:17]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τις αυτον αρχων λεγων διδασκαλε αγαθε τι ποιησας ζωην αιωνιον κληρονομησω[18:18]{.aside}

ειπεν δε αυτω ο [ιησους]{.greek-abbr} τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[18:19]{.aside}

τας εντολας οιδας μη μοιχευσης μη [κλεψης]{.greek-added} [μη]{.greek-added} φονευσης [μη]{.greek-omitted} [κλεψης]{.greek-omitted} μη ψευδομαρτυρησης τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-omitted}[18:20]{.aside}

ο δε ειπεν ταυτα παντα [εφυλαξαμην]{.greek-omitted} [εφυλαξα]{.greek-added} [μην]{.greek-added} εκ νεοτητος μου[18:21]{.aside}

ακουσας δε ταυτα ο [ιησους]{.greek-abbr} ειπεν αυτω [ετι]{.greek-omitted} [οτι]{.greek-added} εν σοι λειπει παντα οσα εχεις πωλησον και διαδος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι[18:22]{.aside}

ο δε ακουσας ταυτα περιλυπος εγενετο ην γαρ πλουσιος σφοδρα[18:23]{.aside}

ιδων δε αυτον ο [ιησους]{.greek-abbr} περιλυπον γενομενον ειπεν πως δυσκολως οι τα χρηματα εχοντες εισελευσονται εις την βασιλειαν του [θεου]{.greek-abbr}[18:24]{.aside}

ευκοπωτερον γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια τρυμαλιας ραφιδος [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[18:25]{.aside}

ειπον δε οι ακουσαντες και τις δυναται σωθηναι[18:26]{.aside}

ο δε ειπεν τα αδυνατα παρα [ανθρωποις]{.greek-abbr} δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[18:27]{.aside}

ειπεν δε [ο]{.greek-added} πετρος ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[18:28]{.aside}

ο δε ειπεν αυτοις αμην λεγω υμιν οτι ουδεις εστιν ος αφηκεν οικιαν η γονεις η αδελφους η γυναικα η τεκνα ενεκεν της βασιλειας του [θεου]{.greek-abbr}[18:29]{.aside}

ος ου μη απολαβη πολλαπλασιονα εν τω καιρω τουτω και εν τω αιωνι τω ερχομενω ζωην αιωνιον[18:30]{.aside}

παραλαβων δε τους δωδεκα ειπεν προς αυτους ιδου αναβαινομεν εις ιεροσολυμα και τελεσθησεται παντα τα γεγραμμενα δια των προφητων τω υιω του [ανθρωπου]{.greek-abbr}[18:31]{.aside}

παραδοθησεται γαρ τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και εμπαιχθησεται και υβρισθησεται και εμπτυσθησεται[18:32]{.aside}

και μαστιγωσαντες αποκτενουσιν αυτον και τη [τριτη]{.greek-added} ημερα [τη]{.greek-omitted} [τριτη]{.greek-omitted} αναστησεται[18:33]{.aside}

και αυτοι ουδεν τουτων συνηκαν και ην το ρημα τουτο κεκρυμμενον απ αυτων και ουκ εγινωσκον τα λεγομενα[18:34]{.aside}

εγενετο δε εν τω εγγιζειν αυτον εις ιεριχω τυφλος τις εκαθητο παρα την οδον προσαιτων[18:35]{.aside}

[ακουσας]{.greek-omitted} [ακου]{.greek-added} [σας]{.greek-added} δε οχλου διαπορευομενου επυνθανετο τι ειη τουτο[18:36]{.aside}

απηγγειλαν δε αυτω οτι [ιησους]{.greek-abbr} ο ναζωραιος παρερχεται[18:37]{.aside}

και [εβοησεν]{.greek-omitted} [εβοησε]{.greek-added} λεγων [ιησου]{.greek-abbr} υιε [δαυιδ]{.greek-abbr} ελεησον με[18:38]{.aside}

και οι προαγοντες επετιμων αυτω ινα σιωπηση αυτος δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[18:39]{.aside}

σταθεις δε ο [ιησους]{.greek-abbr} εκελευσεν [αυτον]{.greek-omitted} αχθηναι προς αυτον εγγισαντος δε αυτου επηρωτησεν αυτον [λεγων]{.greek-added}[18:40]{.aside}

[λεγων]{.greek-omitted} τι σοι θελεις ποιησω ο δε ειπεν [κυριε]{.greek-abbr} ινα αναβλεψω[18:41]{.aside}

και ο [ιησους]{.greek-abbr} ειπεν αυτω αναβλεψον η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε[18:42]{.aside}

και παραχρημα [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και [ηκολουθει]{.greek-omitted} [ηκολουθησεν]{.greek-added} αυτω δοξαζων τον [θεον]{.greek-abbr} και πας ο λαος ιδων εδωκεν αινον τω [θεω]{.greek-abbr}[18:43]{.aside}

### Chapter 19

και εισελθων διηρχετο την ιεριχω[19:1]{.aside}

και ιδου ανηρ ονοματι καλουμενος ζακχαιος και αυτος ην αρχιτελωνης και ουτος ην πλουσιος[19:2]{.aside}

και εζητει ιδειν τον [ιησουν]{.greek-abbr} τις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ ηδυνατο απο του οχλου οτι τη ηλικια μικρος ην[19:3]{.aside}

και προδραμων εμπροσθεν ανεβη επι συκομωραιαν ινα ιδη αυτον οτι εκεινης [εμελλεν]{.greek-omitted} [ημελλε]{.greek-added} διερχεσθαι[19:4]{.aside}

και ως ηλθεν επι τον τοπον αναβλεψας ο [ιησους]{.greek-abbr} ειδεν αυτον και ειπεν προς αυτον ζακχαιε σπευσας καταβηθι σημερον γαρ εν τω οικω σου δει με μειναι[19:5]{.aside}

και σπευσας κατεβη και υπεδεξατο αυτον χαιρων[19:6]{.aside}

και ιδοντες παντες διεγογγυζον λεγοντες οτι παρα αμαρτωλω ανδρι [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} καταλυσαι[19:7]{.aside}

σταθεις δε ζακχαιος ειπεν προς τον [κυριον]{.greek-abbr} ιδου τα ημιση των υπαρχοντων μου [κυριε]{.greek-abbr} διδωμι τοις πτωχοις και ει τινος τι εσυκοφαντησα αποδιδωμι τετραπλουν[19:8]{.aside}

ειπεν δε προς αυτον ο [ιησους]{.greek-abbr} οτι σημερον [σωτηρια]{.greek-abbr} τω οικω τουτω εγενετο καθοτι και αυτος [υιος]{.greek-abbr} αβρααμ εστιν[19:9]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ζητησαι και σωσαι το απολωλος[19:10]{.aside}

ακουοντων δε αυτων ταυτα προσθεις ειπεν παραβολην δια το εγγυς αυτον ειναι [ιερουσαλημ]{.greek-abbr} και δοκειν αυτους οτι παραχρημα μελλει η βασιλεια του [θεου]{.greek-abbr} αναφαινεσθαι[19:11]{.aside}

ειπεν ουν [ανθρωπος]{.greek-abbr} τις ευγενης επορευθη εις χωραν μακραν λαβειν εαυτω βασιλειαν και υποστρεψαι[19:12]{.aside}

καλεσας δε δεκα δουλους [εαυτου]{.greek-omitted} [αυτου]{.greek-added} εδωκεν αυτοις δεκα μνας και ειπεν προς αυτους πραγματευσασθε [εως]{.greek-omitted} [εν]{.greek-added} [ω]{.greek-added} ερχομαι[19:13]{.aside}

οι δε πολιται αυτου εμισουν αυτον και απεστειλαν πρεσβειαν οπισω αυτου λεγοντες ου θελομεν τουτον βασιλευσαι εφ ημας[19:14]{.aside}

και εγενετο εν τω επανελθειν αυτον λαβοντα την βασιλειαν και ειπεν φωνηθηναι αυτω τους δουλους τουτους οις εδωκεν το αργυριον ινα γνω τις τι διεπραγματευσατο[19:15]{.aside}

παρεγενετο δε ο πρωτος λεγων [κυριε]{.greek-abbr} η [μνα]{.greek-omitted} [μνας]{.greek-added} σου προσειργασατο δεκα μνας[19:16]{.aside}

και ειπεν αυτω ευ [αγαθε]{.greek-omitted} [αγα]{.greek-added} [θε]{.greek-added} δουλε οτι εν ελαχιστω πιστος εγενου ισθι εξουσιαν εχων επανω δεκα πολεων[19:17]{.aside}

και ηλθεν ο δευτερος λεγων [κυριε]{.greek-abbr} η [μνα]{.greek-omitted} [μνας]{.greek-added} σου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} πεντε μνας[19:18]{.aside}

ειπεν δε και τουτω και συ γινου επανω πεντε πολεων[19:19]{.aside}

και ετερος ηλθεν λεγων [κυριε]{.greek-abbr} ιδου η [μνα]{.greek-omitted} [μνας]{.greek-added} σου ην ειχον αποκειμενην εν σουδαριω[19:20]{.aside}

εφοβουμην γαρ σε οτι [ανθρωπος]{.greek-abbr} [ει]{.greek-added} αυστηρος [ει]{.greek-omitted} αιρεις ο ουκ εθηκας και θεριζεις ο ουκ εσπειρας[19:21]{.aside}

λεγει δε αυτω εκ του στοματος σου κρινω σε πονηρε δουλε ηδεις οτι εγω [ανθρωπος]{.greek-abbr} αυστηρος ειμι αιρων ο ουκ εθηκα και θεριζων ο ουκ εσπειρα[19:22]{.aside}

και δια τι ουκ εδωκας το αργυριον μου επι τραπεζαν και [ελθων]{.greek-added} εγω [ελθων]{.greek-omitted} συν τοκω αν επραξα αυτο[19:23]{.aside}

και τοις παρεστωσιν ειπεν αρατε απ αυτου την μναν και δοτε τω τας δεκα μνας εχοντι[19:24]{.aside}

και ειπον αυτω [κυριε]{.greek-abbr} εχει δεκα μνας[19:25]{.aside}

λεγω γαρ υμιν οτι παντι τω εχοντι δοθησεται απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου[19:26]{.aside}

πλην τους εχθρους μου εκεινους τους μη θελησαντας με βασιλευσαι επ αυτους αγαγετε ωδε και κατασφαξατε εμπροσθεν μου[19:27]{.aside}

και ειπων ταυτα επορευετο εμπροσθεν αναβαινων εις ιεροσολυμα[19:28]{.aside}

και εγενετο ως ηγγισεν εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} και βηθανιαν προς το ορος το καλουμενον ελαιων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} δυο των μαθητων αυτου[19:29]{.aside}

ειπων υπαγετε εις την κατεναντι κωμην εν η εισπορευομενοι ευρησετε πωλον δεδεμενον εφ ον ουδεις πωποτε [ανθρωπων]{.greek-abbr} εκαθισεν λυσαντες αυτον αγαγετε[19:30]{.aside}

και εαν τις [υμας]{.greek-omitted} [υμιν]{.greek-added} ερωτα δια τι λυετε ουτως ερειτε αυτω οτι ο κυριος αυτου χρειαν εχει[19:31]{.aside}

απελθοντες δε οι απεσταλμενοι ευρον καθως ειπεν αυτοις[19:32]{.aside}

λυοντων δε αυτων τον πωλον ειπον οι κυριοι αυτου προς αυτους τι λυετε τον πωλον[19:33]{.aside}

οι δε ειπον [οτι]{.greek-added} ο κυριος αυτου χρειαν εχει[19:34]{.aside}

και ηγαγον αυτον προς τον [ιησουν]{.greek-abbr} και επιρριψαντες [εαυτων]{.greek-omitted} [αυτων]{.greek-added} τα ιματια επι τον πωλον επεβιβασαν τον [ιησουν]{.greek-abbr}[19:35]{.aside}

πορευομενου δε αυτου υπεστρωννυον [εαυτων]{.greek-added} τα ιματια [αυτων]{.greek-omitted} εν τη οδω[19:36]{.aside}

εγγιζοντος δε αυτου ηδη προς τη καταβασει του ορους των ελαιων ηρξαντο απαν το πληθος των μαθητων χαιροντες αινειν τον [θεον]{.greek-abbr} φωνη μεγαλη περι πασων ων ειδον δυναμεων[19:37]{.aside}

λεγοντες ευλογημενος ο ερχομενος βασιλευς εν ονοματι [κυριου]{.greek-abbr} ειρηνη εν [ουρανω]{.greek-abbr} και δοξα εν υψιστοις[19:38]{.aside}

και τινες των φαρισαιων απο του οχλου ειπον προς αυτον διδασκαλε επιτιμησον τοις μαθηταις σου[19:39]{.aside}

και αποκριθεις ειπεν αυτοις λεγω υμιν οτι εαν ουτοι σιωπησωσιν οι λιθοι [κεκραξονται]{.greek-omitted} [κεκραξωνται]{.greek-added}[19:40]{.aside}

και ως ηγγισεν ιδων την πολιν εκλαυσεν επ [αυτη]{.greek-omitted} [αυτην]{.greek-added}[19:41]{.aside}

λεγων οτι ει εγνως και συ και γε εν τη ημερα σου ταυτη τα προς ειρηνην σου νυν δε εκρυβη απο [των]{.greek-added} οφθαλμων σου[19:42]{.aside}

οτι ηξουσιν ημεραι επι σε και περιβαλουσιν οι εχθροι σου χαρακα σοι και [περικυκλωσουσιν]{.greek-omitted} [περικυκλωσουσι]{.greek-added} σε και [συνεξουσιν]{.greek-omitted} [συνεξουσι]{.greek-added} σε παντοθεν[19:43]{.aside}

και [εδαφιουσιν]{.greek-omitted} [εκδαφιουσι]{.greek-added} σε και τα τεκνα σου εν σοι και ουκ [αφησουσιν]{.greek-omitted} [αφιασιν]{.greek-added} εν σοι λιθον επι λιθω ανθ ων ουκ εγνως τον καιρον της επισκοπης σου[19:44]{.aside}

και εισελθων εις το ιερον ηρξατο εκβαλλειν τους πωλουντας εν αυτω και αγοραζοντας[19:45]{.aside}

λεγων αυτοις γεγραπται ο οικος μου οικος προσευχης [εστιν]{.greek-omitted} [κληθησεται]{.greek-added} υμεις δε αυτον εποιησατε σπηλαιον ληστων[19:46]{.aside}

και ην διδασκων το καθ ημεραν εν τω ιερω οι δε αρχιερεις και οι γραμματεις εζητουν αυτον απολεσαι και οι πρωτοι του λαου[19:47]{.aside}

και ουχ ευρισκον το τι [ποιησωσιν]{.greek-omitted} [ποιησουσιν]{.greek-added} ο λαος γαρ απας εξεκρεματο [αυ]{.greek-added} [αυτου]{.greek-omitted} [του]{.greek-added} ακουων[19:48]{.aside}

### Chapter 20

και εγενετο εν μια των ημερων εκεινων διδασκοντος αυτου τον λαον εν τω ιερω και ευαγγελιζομενου επεστησαν οι ιερεις και οι γραμματεις συν τοις πρεσβυτεροις[20:1]{.aside}

και ειπον προς αυτον λεγοντες ειπε ημιν εν ποια εξουσια ταυτα ποιεις η τις εστιν ο δους σοι την εξουσιαν ταυτην[20:2]{.aside}

αποκριθεις δε ειπεν προς αυτους ερωτησω υμας καγω ενα λογον και ειπατε μοι[20:3]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr}[20:4]{.aside}

οι δε συνελογισαντο προς εαυτους λεγοντες οτι εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι [ουν]{.greek-added} ουκ επιστευσατε αυτω[20:5]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} πας ο λαος καταλιθασει ημας πεπεισμενος γαρ εστιν ιωαννην προφητην ειναι[20:6]{.aside}

και απεκριθησαν μη ειδεναι ποθεν[20:7]{.aside}

και ο [ιησους]{.greek-abbr} ειπεν αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[20:8]{.aside}

[ηρ]{.greek-added} [ηρξατο]{.greek-omitted} [ξατο]{.greek-added} δε προς τον λαον λεγειν την παραβολην ταυτην [ανθρωπος]{.greek-abbr} εφυτευσεν αμπελωνα και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added} χρονους ικανους[20:9]{.aside}

και εν καιρω [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους δουλον ινα απο του καρπου του αμπελωνος δωσιν αυτω οι δε γεωργοι δειραντες αυτον [εξαπεστειλ[ο]{.unclear}ν]{.greek-added} [εξαπεστειλαν]{.corr} κενον[20:10]{.aside}

και προσεθετο πεμψαι ετερον δουλον οι δε κακεινον δειραντες και ατιμασαντες εξαπεστειλαν κενον[20:11]{.aside}

και προσεθετο πεμψαι τριτον οι δε και τουτον τραυματισαντες εξεβαλον[20:12]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησω πεμψω τον [υιον]{.greek-abbr} μου τον αγαπητον ισως τουτον ιδοντες εντραπησονται[20:13]{.aside}

ιδοντες δε αυτον οι γεωργοι διελογιζοντο προς εαυτους λεγοντες ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον ινα ημων γενηται η κληρονομια[20:14]{.aside}

και εκβαλοντες αυτον εξω του αμπελωνος απεκτειναν τι ουν ποιησει αυτοις ο κυριος του αμπελωνος[20:15]{.aside}

ελευσεται και απολεσει τους γεωργους τουτους και δωσει τον αμπελωνα αλλοις ακουσαντες δε ειπον μη γενοιτο[20:16]{.aside}

ο δε εμβλεψας αυτοις ειπεν τι ουν [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγραμμενον [τουτο]{.greek-omitted} λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[20:17]{.aside}

πας ο πεσων [επ]{.greek-omitted} [επι]{.greek-added} [εκεινον]{.greek-omitted} τον λιθον [εκεινον]{.greek-added} συνθλασθησεται εφ ον δ αν πεση λικμησει αυτον[20:18]{.aside}

και εζητησαν οι αρχιερεις και οι γραμματεις επιβαλειν επ αυτον τας χειρας εν αυτη τη ωρα και εφοβηθησαν [τον]{.greek-added} [λαον]{.greek-added} εγνωσαν γαρ οτι προς αυτους την παραβολην ταυτην ειπεν[20:19]{.aside}

και παρατηρησαντες απεστειλαν εγκαθετους [υποκρινομενους]{.greek-omitted} [υποκριναμενους]{.greek-added} εαυτους δικαιους ειναι ινα επιλαβωνται αυτου [λογου]{.greek-omitted} [λογον]{.greek-added} εις το παραδουναι αυτον τη αρχη και τη εξουσια του ηγεμονος[20:20]{.aside}

και επηρωτησαν αυτον λεγοντες διδασκαλε οιδαμεν οτι ορθως λεγεις και διδασκεις και ου λαμβανεις προσωπον αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις[20:21]{.aside}

εξεστιν ημιν καισαρι φορον δουναι η ου[20:22]{.aside}

κατανοησας δε αυτων την πανουργιαν ειπεν προς αυτους τι με πειραζετε[20:23]{.aside}

επιδειξατε μοι δηναριον τινος εχει εικονα και επιγραφην αποκριθεντες δε ειπον καισαρος[20:24]{.aside}

ο δε ειπεν αυτοις αποδοτε τοινυν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[20:25]{.aside}

και ουκ ισχυσαν επιλαβεσθαι αυτου ρηματος εναντιον του λαου και θαυμασαντες επι τη αποκρισει αυτου εσιγησαν[20:26]{.aside}

προσελθοντες δε τινες των σαδδουκαιων οι αντιλεγοντες αναστασιν μη ειναι επηρωτησαν αυτον[20:27]{.aside}

λεγοντες διδασκαλε μωσης εγραψεν ημιν εαν τινος αδελφος αποθανη εχων γυναικα και ουτος ατεκνος [αποθανη]{.greek-omitted} ινα λαβη ο αδελφος αυτου την γυναικα και εξαναστηση σπερμα τω αδελφω αυτου[20:28]{.aside}

επτα ουν αδελφοι ησαν και ο πρωτος λαβων γυναικα απεθανεν ατεκνος[20:29]{.aside}

και ελαβεν ο δευτερος την γυναικα και ουτος απεθανεν ατεκνος[20:30]{.aside}

και ο τριτος ελαβεν αυτην ωσαυτως [ωσαυτως]{.greek-omitted} δε και οι επτα [και]{.greek-added} ου κατελιπον [τεκνα]{.greek-omitted} [σπερμα]{.greek-added} και απεθανον[20:31]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[20:32]{.aside}

εν τη ουν αναστασει τινος αυτων γινεται γυνη οι γαρ επτα εσχον αυτην γυναικα[20:33]{.aside}

και αποκριθεις ειπεν αυτοις ο [ιησους]{.greek-abbr} οι υιοι του αιωνος τουτου [γαμουσιν]{.greek-omitted} [γαμουσι]{.greek-added} και [εκγαμισκονται]{.greek-omitted} [εκγαμιζονται]{.greek-added}[20:34]{.aside}

οι δε καταξιωθεντες του αιωνος εκεινου τυχειν και της αναστασεως [των]{.greek-added} [της]{.greek-omitted} [εκ]{.greek-omitted} νεκρων ουτε γαμουσιν ουτε [εκγαμιζονται]{.greek-omitted} [εκγαμισκονται]{.greek-added}[20:35]{.aside}

[ουτε]{.greek-omitted} [ουδε]{.greek-added} γαρ αποθανειν ετι δυνανται ισαγγελοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} και υιοι [εισιν]{.greek-omitted} [εισι]{.greek-added} του [θεου]{.greek-abbr} της αναστασεως υιοι οντες[20:36]{.aside}

οτι δε εγειρονται οι νεκροι και μωσης εμηνυσεν επι της βατου ως λεγει [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} αβρααμ και τον [θεον]{.greek-abbr} ισαακ και τον [θεον]{.greek-abbr} ιακωβ[20:37]{.aside}

[θεος]{.greek-abbr} δε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} νεκρων αλλα ζωντων παντες γαρ αυτω ζωσιν[20:38]{.aside}

αποκριθεντες δε τινες των γραμματεων ειπον διδασκαλε καλως ειπας[20:39]{.aside}

ουκετι δε ετολμων [επερωταν]{.greek-omitted} [επερωτησαι]{.greek-added} αυτον ουδεν[20:40]{.aside}

ειπεν δε προς αυτους πως [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τον [χριστον]{.greek-abbr} [υιον]{.greek-abbr} [δαυιδ]{.greek-abbr} ειναι[20:41]{.aside}

και αυτος [δαυιδ]{.greek-abbr} λεγει εν βιβλω ψαλμων ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου[20:42]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[20:43]{.aside}

[δαυιδ]{.greek-abbr} ουν [κυριον]{.greek-abbr} αυτον καλει και πως [αυτου]{.greek-added} [υιος]{.greek-abbr} [αυτου]{.greek-omitted} εστιν[20:44]{.aside}

ακουοντος δε παντος του λαου ειπεν τοις μαθηταις αυτου[20:45]{.aside}

προσεχετε απο των γραμματεων των θελοντων [περιπατειν]{.greek-omitted} εν στολαις [περιπατειν]{.greek-added} και φιλουντων ασπασμους εν ταις [α]{.greek-added} [αγοραις]{.greek-omitted} [γοραις]{.greek-added} και πρωτοκαθεδριας εν ταις συναγωγαις και πρωτοκλισιας εν τοις δειπνοις[20:46]{.aside}

οι [κατεσθιουσιν]{.greek-omitted} [κατεσθιουσι]{.greek-added} τας οικιας των χηρων και προφασει μακρα προσευχονται ουτοι ληψονται περισσοτερον κριμα[20:47]{.aside}

### Chapter 21

αναβλεψας δε ειδεν τους βαλλοντας τα δωρα αυτων εις το [γαζοφυλακιον]{.greek-omitted} [γαζοφυλακειον]{.greek-added} πλουσιους[21:1]{.aside}

ειδεν δε τινα και χηραν [πενιχραν]{.greek-omitted} [πενηχραν]{.greek-added} βαλλουσαν εκει δυο λεπτα[21:2]{.aside}

και ειπεν αληθως λεγω υμιν οτι η χηρα η πτωχη αυτη [πλειον]{.greek-omitted} [πλειω]{.greek-added} παντων εβαλεν[21:3]{.aside}

απαντες γαρ ουτοι εκ του περισσευοντος αυτοις εβαλον εις τα δωρα του [θεου]{.greek-abbr} αυτη δε εκ του υστερηματος αυτης απαντα τον βιον ον ειχεν [εβαλεν]{.greek-omitted} [εβαλλεν]{.greek-added}[21:4]{.aside}

και τινων λεγοντων περι του ιερου οτι λιθοις καλοις και [αναθημασιν]{.greek-omitted} [αναθημασι]{.greek-added} κεκοσμηται ειπεν[21:5]{.aside}

ταυτα α θεωρειτε ελευσονται ημεραι εν αις ουκ αφεθησεται λιθος επι λιθω ος ου καταλυθησεται[21:6]{.aside}

[επηρωτησαν]{.greek-omitted} [επηρω]{.greek-added} [τησαν]{.greek-added} δε αυτον λεγοντες διδασκαλε ποτε ουν ταυτα εσται και τι το σημειον οταν μελλη ταυτα γινεσθαι[21:7]{.aside}

ο δε ειπεν βλεπετε μη πλανηθητε πολλοι γαρ ελευσονται επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου λεγοντες οτι εγω ειμι και ο καιρος [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} μη ουν πορευθητε οπισω αυτων[21:8]{.aside}

οταν δε ακουσητε πολεμους και ακαταστασιας μη πτοηθητε δει γαρ ταυτα γενεσθαι πρωτον αλλ ουκ ευθεως το τελος[21:9]{.aside}

τοτε ελεγεν αυτοις εγερθησεται εθνος επι εθνος και βασιλεια επι βασιλειαν[21:10]{.aside}

σεισμοι τε μεγαλοι κατα τοπους και λιμοι και λοιμοι εσονται φοβητρα τε και σημεια [μεγαλα]{.greek-added} απ [ουρανου]{.greek-abbr} [μεγαλα]{.greek-omitted} εσται[21:11]{.aside}

προ δε τουτων παντων επιβαλουσιν εφ υμας τας χειρας αυτων και [διωξουσιν]{.greek-omitted} [διωξουσι]{.greek-added} παραδιδοντες εις συναγωγας και φυλακας αγομενους επι βασιλεις και ηγεμονας ενεκεν του ονοματος μου[21:12]{.aside}

[α]{.greek-added} [αποβησεται]{.greek-omitted} [ποβησεται]{.greek-added} δε υμιν εις μαρτυριον[21:13]{.aside}

θεσθε ουν [εις]{.greek-omitted} [εν]{.greek-added} [τας]{.greek-omitted} [ταις]{.greek-added} [καρδιας]{.greek-omitted} [καρδιαις]{.greek-added} υμων μη προμελεταν απολογηθηναι[21:14]{.aside}

εγω γαρ δωσω υμιν στομα και σοφιαν η ου δυνησονται αντειπειν ουδε αντιστηναι παντες οι αντικειμενοι υμιν[21:15]{.aside}

παραδοθησεσθε δε και υπο γονεων και [αδελφων]{.greek-added} [και]{.greek-added} συγγενων και φιλων και [αδελφων]{.greek-omitted} [και]{.greek-omitted} θανατωσουσιν εξ υμων[21:16]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου[21:17]{.aside}

και θριξ εκ της κεφαλης υμων ου μη αποληται[21:18]{.aside}

εν τη υπομονη υμων κτησασθε τας ψυχας υμων[21:19]{.aside}

οταν δε ιδητε κυκλουμενην υπο στρατοπεδων την [ιερουσαλημ]{.greek-abbr} τοτε γνωτε οτι ηγγικεν η ερημωσις αυτης[21:20]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη και οι εν μεσω αυτης εκχωρειτωσαν και οι εν ταις χωραις μη εισερχεσθωσαν εις αυτην[21:21]{.aside}

οτι ημεραι εκδικησεως αυται [εισιν]{.greek-omitted} [εισι]{.greek-added} του [πλησθηναι]{.greek-omitted} [πληρωθηναι]{.greek-added} παντα τα γεγραμμενα[21:22]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις εσται γαρ αναγκη μεγαλη επι της γης και οργη εν τω λαω τουτω[21:23]{.aside}

και πεσουνται στοματι μαχαιρας και αιχμαλωτισθησονται εις παντα τα εθνη και [ιερουσαλημ]{.greek-abbr} εσται πατουμενη υπο εθνων αχρι [πληρωθωσιν]{.greek-omitted} [πληρωθωσι]{.greek-added} καιροι εθνων[21:24]{.aside}

και εσται σημεια εν ηλιω και σεληνη και αστροις και επι της γης συνοχη εθνων εν απορια ηχουσης θαλασσης και σαλου[21:25]{.aside}

αποψυχοντων [ανθρωπων]{.greek-abbr} απο φοβου και προσδοκιας των επερχομενων τη οικουμενη αι γαρ δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[21:26]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελη μετα δυναμεως και δοξης πολλης[21:27]{.aside}

αρχομενων δε τουτων γινεσθαι ανακυψατε και επαρατε τας κεφαλας υμων διοτι [εγγιζει]{.greek-omitted} [ηγγικεν]{.greek-added} η απολυτρωσις υμων[21:28]{.aside}

και ειπεν παραβολην αυτοις ιδετε την συκην και παντα τα δενδρα[21:29]{.aside}

οταν προβαλωσιν ηδη βλεποντες αφ εαυτων γινωσκετε οτι [ηδη]{.greek-omitted} εγγυς το θερος εστιν[21:30]{.aside}

ουτως και υμεις οταν ιδητε ταυτα γινομενα γινωσκετε οτι εγγυς εστιν η βασιλεια του [θεου]{.greek-abbr}[21:31]{.aside}

αμην λεγω υμιν [οτι]{.greek-omitted} ου μη παρελθη η γενεα αυτη εως αν παντα γενηται[21:32]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσονται οι δε λογοι μου ου μη παρελθωσιν[21:33]{.aside}

προσεχετε δε εαυτοις μηποτε βαρηθωσιν [υμων]{.greek-omitted} αι καρδιαι [υμων]{.greek-added} εν [κραιπαλη]{.greek-omitted} [κρεπαλη]{.greek-added} και μεθη και μεριμναις βιωτικαις και αιφνιδιος εφ υμας επιστη η ημερα εκεινη[21:34]{.aside}

ως παγις γαρ επελευσεται επι παντας τους καθημενους επι προσωπον πασης της γης[21:35]{.aside}

αγρυπνειτε ουν εν παντι καιρω δεομενοι ινα καταξιωθητε εκφυγειν παντα τα μελλοντα γινεσθαι και σταθηναι εμπροσθεν του υιου του [ανθρωπου]{.greek-abbr}[21:36]{.aside}

ην δε τας ημερας εν τω ιερω [διδασκων]{.greek-omitted} [διδα]{.greek-added} [σκων]{.greek-added} τας δε νυκτας εξερχομενος ηυλιζετο εις το ορος το καλουμενον ελαιων[21:37]{.aside}

και πας ο λαος [ωρθριζεν]{.greek-omitted} [ωρθριζε]{.greek-added} προς αυτον εν τω ιερω ακουειν αυτου[21:38]{.aside}

### Chapter 22

[ηγγιζεν]{.greek-omitted} [ηγγισε]{.greek-added} δε η εορτη των αζυμων η λεγομενη πασχα[22:1]{.aside}

και εζητουν οι αρχιερεις και οι γραμματεις το πως ανελωσιν αυτον εφοβουντο γαρ τον λαον[22:2]{.aside}

[εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} δε σατανας εις ιουδαν τον επικαλουμενον ισκαριωτην οντα εκ του αριθμου των δωδεκα[22:3]{.aside}

και απελθων [συνελαλησεν]{.greek-omitted} [συνελαλησε]{.greek-added} τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και στρατηγοις το πως αυτον παραδω αυτοις[22:4]{.aside}

και εχαρησαν και συνεθεντο αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι[22:5]{.aside}

και [εξωμολογησεν]{.greek-omitted} [εξομολογησε]{.greek-added} και εζητει ευκαιριαν του παραδουναι αυτον αυτοις ατερ οχλου[22:6]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} δε η ημερα των αζυμων εν η εδει θυεσθαι το πασχα[22:7]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} πετρον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ειπων πορευθεντες ετοιμασατε ημιν το πασχα ινα φαγωμεν[22:8]{.aside}

οι δε ειπον αυτω που [θε]{.greek-added} [θελεις]{.greek-omitted} [λεις]{.greek-added} ετοιμασομεν[22:9]{.aside}

ο δε ειπεν αυτοις ιδου εισελθοντων υμων εις την πολιν συναντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω εις την οικιαν ου εισπορευεται[22:10]{.aside}

και ερειτε τω [οικοδεσποτη]{.greek-omitted} [οικωδεσποτη]{.greek-added} της οικιας λεγει σοι ο διδασκαλος που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[22:11]{.aside}

κακεινος υμιν δειξει [αναγαιον]{.greek-added} [ανωγεον]{.greek-omitted} [μεγα]{.greek-omitted} [εστρωμενον]{.greek-omitted} [εστρωμμενον]{.greek-added} εκει ετοιμασατε[22:12]{.aside}

απελθοντες δε ευρον καθως ειρηκεν αυτοις και ητοιμασαν το πασχα[22:13]{.aside}

και οτε εγενετο η ωρα [ανεπεσεν]{.greek-omitted} [ανεπεσε]{.greek-added} και οι δωδεκα αποστολοι συν αυτω[22:14]{.aside}

και ειπεν προς αυτους επιθυμια επεθυμησα τουτο το πασχα φαγειν μεθ υμων προ του με παθειν[22:15]{.aside}

λεγω γαρ υμιν οτι ουκετι ου μη φαγω εξ αυτου εως οτου πληρωθη εν τη βασιλεια του [θεου]{.greek-abbr}[22:16]{.aside}

και δεξαμενος ποτηριον ευχαριστησας ειπεν λαβετε τουτο και διαμερισατε εαυτοις[22:17]{.aside}

λεγω γαρ [υ]{.greek-added} [υμιν]{.greek-omitted} [μιν]{.greek-added} οτι ου μη πιω [απο]{.greek-omitted} [εκ]{.greek-added} του γενηματος της αμπελου εως οτου η βασιλεια του [θεου]{.greek-abbr} ελθη[22:18]{.aside}

και λαβων αρτον ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις λεγων τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου το υπερ υμων διδομενον τουτο ποιειτε εις την εμην αναμνησιν[22:19]{.aside}

ωσαυτως και το ποτηριον μετα το δειπνησαι λεγων τουτο το ποτηριον η καινη διαθηκη εν τω αιματι μου το υπερ υμων εκχυνομενον[22:20]{.aside}

πλην ιδου η χειρ του παραδιδοντος με μετ εμου επι της τραπεζης[22:21]{.aside}

και ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πορευεται κατα το ωρισμενον πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου παραδιδοται[22:22]{.aside}

και αυτοι ηρξαντο συζητειν προς [εαυτους]{.greek-omitted} [αυτοις]{.greek-added} το τις αρα ειη εξ αυτων ο τουτο μελλων πρασσειν[22:23]{.aside}

εγενετο δε και φιλονεικια εν αυτοις το τις αυτων δοκει ειναι μειζων[22:24]{.aside}

ο δε ειπεν αυτοις οι βασιλεις των εθνων [κυριευουσιν]{.greek-omitted} [κυριευσουσιν]{.greek-added} αυτων και οι εξουσιαζοντες αυτων ευεργεται [κα]{.greek-added} [καλουνται]{.greek-omitted} [λουνται]{.greek-added}[22:25]{.aside}

υμεις δε ουχ ουτως αλλ ο μειζων εν υμιν γενεσθω ως ο νεωτερος και ο ηγουμενος ως ο διακονων[22:26]{.aside}

τις γαρ μειζων ο ανακειμενος η ο διακονων ουχι ο ανακειμενος εγω δε ειμι εν μεσω υμων ως ο διακονων[22:27]{.aside}

υμεις δε εστε οι διαμεμενηκοτες μετ εμου εν τοις πειρασμοις μου[22:28]{.aside}

καγω διατιθεμαι υμιν καθως διεθετο μοι ο [πατηρ]{.greek-abbr} μου βασιλειαν[22:29]{.aside}

ινα εσθιητε και πινητε επι της τραπεζης μου [εν]{.greek-added} [τη]{.greek-added} [βασιλεια]{.greek-added} [μου]{.greek-added} και καθισεσθε επι [δωδεκα]{.greek-added} θρονων κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[22:30]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} σιμων σιμων ιδου ο σατανας εξητησατο υμας του σινιασαι ως τον σιτον[22:31]{.aside}

εγω δε εδεηθην περι σου ινα μη [εκλιπη]{.greek-omitted} [εκλειπη]{.greek-added} η πιστις σου και συ ποτε επιστρεψας στηριξον τους αδελφους σου[22:32]{.aside}

ο δε ειπεν [αυτω]{.greek-omitted} [κυριε]{.greek-abbr} μετα σου ετοιμος ειμι και εις φυλακην και εις θανατον πορευεσθαι[22:33]{.aside}

ο δε ειπεν λεγω σοι πετρε ου μη φωνηση σημερον αλεκτωρ πριν [η]{.greek-omitted} τρις απαρνηση μη ειδεναι με[22:34]{.aside}

και ειπεν αυτοις οτε απεστειλα υμας ατερ [βαλαντιου]{.greek-omitted} [βαλλαντιου]{.greek-added} και πηρας και υποδηματων μη τινος υστερησατε οι δε ειπον ουθενος[22:35]{.aside}

ειπεν ουν αυτοις αλλα νυν ο εχων [βαλαντιον]{.greek-omitted} [βαλλαντιον]{.greek-added} αρατω ομοιως και πηραν και ο μη εχων πωλησει το ιματιον αυτου και αγορασει μαχαιραν[22:36]{.aside}

λεγω γαρ υμιν οτι ετι τουτο το γεγραμμενον δει τελεσθηναι εν εμοι το και μετα ανομων ελογισθη και γαρ τα περι εμου τελος εχει[22:37]{.aside}

οι δε ειπον [κυριε]{.greek-abbr} ιδου μαχαιραι ωδε δυο ο δε ειπεν αυτοις ικανον [εστιν]{.greek-omitted} [εστι]{.greek-added}[22:38]{.aside}

και εξελθων επορευθη κατα το εθος εις το ορος των ελαιων ηκολουθησαν δε αυτω και οι μαθηται [αυτου]{.greek-omitted}[22:39]{.aside}

γενομενος δε επι του τοπου ειπεν αυτοις προσευχεσθε μη εισελθειν εις πειρασμον[22:40]{.aside}

και αυτος απεσπασθη απ αυτων ωσει λιθου βολην και θεις τα γονατα προσηυχετο[22:41]{.aside}

λεγων [πατερ]{.greek-abbr} ει βουλει παρενεγκειν το ποτηριον τουτο απ εμου πλην μη [το]{.corr} θελημα μου αλλα το σον [γενεσθω]{.greek-omitted} [γινεσθω]{.greek-added}[22:42]{.aside}

ωφθη δε αυτω αγγελος απ [ουρανου]{.greek-abbr} ενισχυων αυτον[22:43]{.aside}

και γενομενος εν αγωνια εκτενεστερον προσηυχετο εγενετο δε ο ιδρως αυτου ωσει θρομβοι αιματος [καταβαινοντες]{.greek-omitted} [καταβαινον]{.greek-added} επι την γην[22:44]{.aside}

και αναστας απο της προσευχης ελθων προς τους μαθητας ευρεν αυτους κοιμωμενους απο της λυπης[22:45]{.aside}

και ειπεν αυτοις τι καθευδετε ανασταντες προσευχεσθε ινα μη εισελθητε εις πειρασμον[22:46]{.aside}

ετι δε αυτου λαλουντος ιδου οχλος και ο λεγομενος ιουδας εις των δωδεκα προηρχετο αυτους και [ηγγισεν]{.greek-omitted} [ηγγισε]{.greek-added} τω [ιησου]{.greek-abbr} φιλησαι αυτον [τουτο]{.greek-added} [γαρ]{.greek-added} [σημειον]{.greek-added} [δεδωκει]{.greek-added} [αυτοις]{.greek-added} [ον]{.greek-added} [αν]{.greek-added} [φιλησω]{.greek-added} [αυτος]{.greek-added} [εστιν]{.greek-added}[22:47]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω ιουδα φιληματι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδως[22:48]{.aside}

ιδοντες δε οι περι αυτον το εσομενον [ει]{.greek-added} [ειπον]{.greek-omitted} [πον]{.greek-added} αυτω [κυριε]{.greek-abbr} ει παταξομεν εν μαχαιρα[22:49]{.aside}

και επαταξεν εις τις εξ αυτων τον δουλον του αρχιερεως και αφειλεν αυτου το ους το δεξιον[22:50]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν εατε εως τουτου και αψαμενος του ωτιου αυτου ιασατο αυτον[22:51]{.aside}

ειπεν δε ο [ιησους]{.greek-abbr} προς τους παραγενομενους επ αυτον αρχιερεις και στρατηγους του ιερου και πρεσβυτερους ως επι ληστην εξεληλυθατε μετα μαχαιρων και ξυλων[22:52]{.aside}

καθ ημεραν οντος μου μεθ υμων εν τω ιερω ουκ εξετεινατε τας χειρας επ εμε αλλ αυτη υμων εστιν η ωρα και η εξουσια του σκοτους[22:53]{.aside}

συλλαβοντες δε αυτον ηγαγον και εισηγαγον αυτον εις τον οικον του αρχιερεως ο δε πετρος ηκολουθει μακροθεν[22:54]{.aside}

αψαντων δε πυρ εν μεσω της αυλης και [συγκαθισαντων]{.greek-omitted} [συνκαθισαντων]{.greek-added} αυτων εκαθητο ο πετρος εν μεσω αυτων[22:55]{.aside}

ιδουσα δε αυτον παιδισκη τις καθημενον προς το φως και ατενισασα αυτω ειπεν και [ου]{.greek-added} [ουτος]{.greek-omitted} [τος]{.greek-added} συν αυτω ην[22:56]{.aside}

ο δε ηρνησατο αυτον λεγων γυναι ουκ οιδα αυτον[22:57]{.aside}

και μετα βραχυ ετερος ιδων αυτον εφη και συ εξ αυτων ει ο δε πετρος ειπεν [ανθρωπε]{.greek-abbr} ουκ ειμι[22:58]{.aside}

και διαστασης ωσει ωρας μιας αλλος τις διισχυριζετο λεγων επ αληθειας και ουτος μετ αυτου ην και γαρ γαλιλαιος εστιν[22:59]{.aside}

ειπεν δε ο πετρος [ανθρωπε]{.greek-abbr} ουκ οιδα ο λεγεις και παραχρημα ετι λαλουντος αυτου εφωνησεν αλεκτωρ[22:60]{.aside}

και στραφεις ο [κυριος]{.greek-abbr} [ενεβλεψεν]{.greek-omitted} [ενεβλεψε]{.greek-added} τω πετρω και υπεμνησθη ο πετρος του λογου του [κυριου]{.greek-abbr} ως ειπεν αυτω οτι πριν αλεκτορα φωνησαι απαρνηση με τρις[22:61]{.aside}

και εξελθων εξω [ο]{.greek-omitted} [πετρος]{.greek-omitted} [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[22:62]{.aside}

και οι ανδρες οι συνεχοντες τον [ιησουν]{.greek-abbr} ενεπαιζον αυτω δεροντες[22:63]{.aside}

και περικαλυψαντες αυτον ετυπτον αυτου το προσωπον και επηρωτων αυτον λεγοντες προφητευσον τις εστιν ο παισας σε[22:64]{.aside}

και ετερα πολλα βλασφημουντες ελεγον εις αυτον[22:65]{.aside}

και ως εγενετο [ημερα]{.greek-omitted} [ημε]{.greek-added} [ρα]{.greek-added} συνηχθη το πρεσβυτεριον του λαου αρχιερεις και γραμματεις και ανηγαγον αυτον εις το συνεδριον [αυτων]{.greek-omitted} [εαυτων]{.greek-added} [λεγοντες]{.greek-omitted}[22:66]{.aside}

[λεγοντες]{.greek-added} ει συ ει ο [χριστος]{.greek-abbr} ειπε ημιν ειπεν δε αυτοις εαν υμιν ειπω ου μη πιστευσητε[22:67]{.aside}

εαν δε και ερωτησω [υμας]{.greek-added} ου μη αποκριθητε μοι η απολυσητε[22:68]{.aside}

απο του νυν εσται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} καθημενος εκ δεξιων της δυναμεως του [θεου]{.greek-abbr}[22:69]{.aside}

ειπον δε παντες συ ουν ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο δε προς αυτους εφη υμεις λεγετε οτι εγω ειμι[22:70]{.aside}

οι δε ειπον τι ετι χρειαν εχομεν μαρτυριας αυτοι γαρ ηκουσαμεν απο του στοματος αυτου[22:71]{.aside}

### Chapter 23

και ανασταν απαν το πληθος αυτων ηγαγον αυτον επι τον πιλατον[23:1]{.aside}

ηρξαντο δε κατηγορειν αυτου λεγοντες τουτον ευρομεν διαστρεφοντα το εθνος και κωλυοντα καισαρι φορους διδοναι λεγοντα εαυτον [χριστον]{.greek-abbr} βασιλεα ειναι[23:2]{.aside}

ο δε πιλατος επηρωτησεν αυτον λεγων συ ει ο [βα]{.greek-added} [βασιλευς]{.greek-omitted} [σιλευς]{.greek-added} των ιουδαιων ο δε αποκριθεις αυτω εφη συ λεγεις[23:3]{.aside}

ο δε πιλατος ειπεν προς τους αρχιερεις και τους οχλους ουδεν ευρισκω αιτιον εν τω [ανθρωπω]{.greek-abbr} τουτω[23:4]{.aside}

οι δε [επισχυον]{.greek-omitted} [ενισχυον]{.greek-added} λεγοντες οτι ανασειει τον λαον [διδασκων]{.greek-omitted} [διδασκει]{.greek-added} καθ ολης της ιουδαιας αρξαμενος απο της γαλιλαιας εως ωδε[23:5]{.aside}

πιλατος δε ακουσας γαλιλαιαν επηρωτησεν ει ο [ανθρωπος]{.greek-abbr} γαλιλαιος [εστιν]{.greek-omitted} [εστι]{.greek-added}[23:6]{.aside}

και επιγνους οτι εκ της εξουσιας ηρωδου εστιν ανεπεμψεν αυτον προς ηρωδην οντα και αυτον εν ιεροσολυμοις εν ταυταις ταις ημεραις[23:7]{.aside}

ο δε ηρωδης ιδων τον [ιησουν]{.greek-abbr} εχαρη λιαν ην γαρ [θελων]{.greek-omitted} εξ ικανου [θελων]{.greek-added} ιδειν αυτον δια το ακουειν πολλα περι αυτου και [ηλπιζεν]{.greek-omitted} [ηλπιζε]{.greek-added} τι σημειον ιδειν υπ αυτου γινομενον[23:8]{.aside}

επηρωτα δε αυτον εν λογοις ικανοις αυτος δε ουδεν απεκρινατο αυτω[23:9]{.aside}

ειστηκεισαν δε οι αρχιερεις και οι γραμματεις ευτονως κατηγορουντες αυτου[23:10]{.aside}

εξουθενησας δε αυτον ο ηρωδης συν τοις στρατευμασιν αυτου και εμπαιξας περιβαλων αυτον εσθητα λαμπραν ανεπεμψεν αυτον τω πιλατω[23:11]{.aside}

εγενοντο δε φιλοι ο τε πιλατος και [ο]{.greek-omitted} ηρωδης εν αυτη τη ημερα μετ αλληλων προυπηρχον γαρ εν εχθρα οντες προς εαυτους[23:12]{.aside}

πιλατος δε συγκαλεσαμενος τους αρχιερεις και τους αρχοντας και τον λαον[23:13]{.aside}

ειπεν προς αυτους προσηνεγκατε μοι τον [ανθρωπον]{.greek-abbr} τουτον ως αποστρεφοντα τον λαον και ιδου εγω ενωπιον υμων ανακρινας ουδεν ευρον εν τω [ανθρωπω]{.greek-abbr} τουτω αιτιον ων κατηγορειτε κατ αυτου[23:14]{.aside}

αλλ ουδε ηρωδης ανεπεμψα γαρ υμας προς αυτον και ιδου ουδεν αξιον θανατου [εστιν]{.greek-omitted} [εστι]{.greek-added} πεπραγμενον αυτω[23:15]{.aside}

παιδευσας ουν αυτον απολυσω[23:16]{.aside}

αναγκην δε ειχεν απολυειν αυτοις κατα εορτην ενα[23:17]{.aside}

ανεκραξαν δε παμπληθει λεγοντες αιρε τουτον απολυσον δε ημιν βαραββαν[23:18]{.aside}

οστις ην δια στασιν [τινα]{.greek-omitted} [γενομενην]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} και φονον βεβλημενος εις φυλακην[23:19]{.aside}

παλιν ουν ο πιλατος [προσεφωνησεν]{.greek-omitted} [προσεφωνησε]{.greek-added} θελων απολυσαι τον [ιησουν]{.greek-abbr}[23:20]{.aside}

οι δε επεφωνουν λεγοντες [σταυρωσον]{.greek-abbr} σταυρωσον αυτον[23:21]{.aside}

ο δε τριτον ειπεν προς αυτους τι γαρ κακον εποιησεν ουτος ουδεν αιτιον θανατου ευρον εν αυτω παιδευσας ουν αυτον απολυσω[23:22]{.aside}

οι δε επεκειντο φωναις μεγαλαις αιτουμενοι αυτον [σταυρωθηναι]{.greek-abbr} και κατισχυον αι φωναι αυτων και των αρχιερεων[23:23]{.aside}

ο δε πιλατος [επεκρινεν]{.greek-omitted} [επεκρινε]{.greek-added} γενεσθαι το αιτημα αυτων[23:24]{.aside}

[απελυσεν]{.greek-omitted} [απελυσε]{.greek-added} δε τον δια στασιν και φονον βεβλημενον εις την φυλακην ον ητουντο τον δε [ιησουν]{.greek-abbr} [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τω θεληματι αυτων[23:25]{.aside}

και ως απηγαγον αυτον επιλαβομενοι σιμωνος τινος κυρηναιου ερχομενου απ αγρου επεθηκαν αυτω τον [σταυρον]{.greek-abbr} φερειν οπισθεν του [ιησου]{.greek-abbr}[23:26]{.aside}

ηκολουθει δε αυτω πολυ πληθος του λαου και γυναικων αι και εκοπτοντο και εθρηνουν αυτον[23:27]{.aside}

στραφεις δε προς αυτας ο [ιησους]{.greek-abbr} ειπεν θυγατερες [ιερουσαλημ]{.greek-abbr} μη κλαιετε επ εμε πλην εφ εαυτας κλαιετε και επι τα τεκνα υμων[23:28]{.aside}

οτι ιδου ερχονται ημεραι εν αις [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μακαριαι αι στειραι και κοιλιαι αι ουκ εγεννησαν και μαστοι οι ουκ εθηλασαν[23:29]{.aside}

τοτε αρξονται λεγειν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} πεσετε εφ ημας και τοις βουνοις καλυψατε ημας[23:30]{.aside}

οτι ει εν τω υγρω ξυλω ταυτα ποιουσιν εν τω ξηρω τι γενηται[23:31]{.aside}

ηγοντο δε και ετεροι δυο κακουργοι συν αυτω αναιρεθηναι[23:32]{.aside}

και οτε απηλθον επι τον τοπον τον καλουμενον κρανιον εκει εσταυρωσαν αυτον και τους κακουργους ον μεν εκ δεξιων ον δε εξ αριστερων[23:33]{.aside}

ο δε [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} [πατερ]{.greek-abbr} αφες αυτοις ου γαρ [οιδασιν]{.greek-omitted} [οιδα]{.greek-added} [σι]{.greek-added} τι ποιουσιν διαμεριζομενοι δε τα ιματια αυτου [εβαλον]{.greek-omitted} [εβαλλον]{.greek-added} κληρον[23:34]{.aside}

και ειστηκει ο λαος θεωρων εξεμυκτηριζον δε και οι αρχοντες συν αυτοις λεγοντες αλλους εσωσεν σωσατω εαυτον ει ουτος εστιν ο [χριστος]{.greek-abbr} ο του [θεου]{.greek-abbr} εκλεκτος[23:35]{.aside}

ενεπαιζον δε αυτω και οι στρατιωται προσερχομενοι και οξος προσφεροντες αυτω[23:36]{.aside}

και λεγοντες ει συ ει ο βασιλευς των ιουδαιων σωσον σεαυτον[23:37]{.aside}

ην δε και επιγραφη γεγραμμενη επ αυτω γραμμασιν ελληνικοις και ρωμαικοις και εβραικοις ουτος εστιν ο βασιλευς των ιουδαιων[23:38]{.aside}

εις δε των κρεμασθεντων κακουργων εβλασφημει αυτον λεγων ει συ ει ο [χριστος]{.greek-abbr} σωσον σεαυτον και ημας[23:39]{.aside}

αποκριθεις δε ο ετερος επετιμα [αυτω]{.greek-omitted} [αυτον]{.greek-added} λεγων ουδε φοβη συ τον [θεον]{.greek-abbr} οτι εν τω αυτω κριματι ει[23:40]{.aside}

και ημεις μεν δικαιως αξια γαρ ων επραξαμεν [απολαμβανομεν]{.greek-omitted} [απολαμβα]{.greek-added} [νομεν]{.greek-added} ουτος δε ουδεν ατοπον [επραξεν]{.greek-omitted} [επραξε]{.greek-added}[23:41]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τω [ιησου]{.greek-abbr} μνησθητι μου [κυριε]{.greek-abbr} οταν ελθης εν τη βασιλεια σου[23:42]{.aside}

[και]{.greek-omitted} ειπεν [δε]{.greek-added} αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι σημερον μετ εμου εση εν τω παραδεισω[23:43]{.aside}

ην δε ωσει ωρα εκτη και σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[23:44]{.aside}

και εσκοτισθη ο ηλιος και εσχισθη το καταπετασμα του ναου μεσον[23:45]{.aside}

και φωνησας φωνη μεγαλη ο [ιησους]{.greek-abbr} ειπεν [πατερ]{.greek-abbr} εις χειρας σου [παραθησομαι]{.greek-omitted} [παρατιθημι]{.greek-added} το [πνευμα]{.greek-abbr} μου και ταυτα ειπων εξεπνευσεν[23:46]{.aside}

ιδων δε ο εκατονταρχος το γενομενον [εδοξασεν]{.greek-omitted} [εδοξασε]{.greek-added} τον [θεον]{.greek-abbr} λεγων οντως ο [ανθρωπος]{.greek-abbr} ουτος δικαιος ην[23:47]{.aside}

και παντες οι συμπαραγενομενοι οχλοι επι την θεωριαν ταυτην θεωρουντες τα γενομενα τυπτοντες εαυτων τα στηθη υπεστρεφον[23:48]{.aside}

ειστηκεισαν δε παντες οι γνωστοι αυτου μακροθεν και γυναικες αι [συνακολουθησασαι]{.greek-omitted} [συνακολουθησα]{.greek-added} [σαι]{.greek-added} αυτω απο της γαλιλαιας ορωσαι ταυτα[23:49]{.aside}

και ιδου ανηρ ονοματι ιωσηφ βουλευτης υπαρχων ανηρ αγαθος και δικαιος[23:50]{.aside}

ουτος ουκ ην συγκατατεθειμενος τη βουλη και τη πραξει αυτων απο αριμαθαιας πολεως των ιουδαιων ος και προσεδεχετο και αυτος την βασιλειαν του [θεου]{.greek-abbr}[23:51]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr}[23:52]{.aside}

και καθελων αυτο ενετυλιξεν αυτο σινδονι και εθηκεν αυτο εν μνηματι λαξευτω ου ουκ ην [ουδεις]{.greek-added} ουδεπω [ουδεις]{.greek-omitted} κειμενος[23:53]{.aside}

και ημερα ην παρασκευη σαββατον [επεφωσκεν]{.greek-omitted} [επεφωσκε]{.greek-added}[23:54]{.aside}

κατακολουθησασαι δε γυναικες αιτινες ησαν συνεληλυθυιαι αυτω εκ της γαλιλαιας εθεασαντο το μνημειον και ως ετεθη το σωμα αυτου[23:55]{.aside}

υποστρεψασαι δε ητοιμασαν αρωματα και μυρα και το μεν σαββατον ησυχασαν κατα την εντολην[23:56]{.aside}

### Chapter 24

τη δε μια των σαββατων ορθρου [βαθεος]{.greek-omitted} [βα]{.greek-added} [θεως]{.greek-added} ηλθον επι το μνημα φερουσαι α ητοιμασαν αρωματα και τινες συν αυταις[24:1]{.aside}

ευρον δε τον λιθον αποκεκυλισμενον απο του μνημειου[24:2]{.aside}

και εισελθουσαι ουχ ευρον το σωμα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[24:3]{.aside}

και εγενετο εν τω διαπορεισθαι αυτας περι τουτου και ιδου ανδρες δυο επεστησαν αυταις εν εσθησεσιν αστραπτουσαις[24:4]{.aside}

εμφοβων δε γενομενων αυτων και κλινουσων το προσωπον εις την γην ειπον προς αυτας τι ζητειτε τον ζωντα μετα των νεκρων[24:5]{.aside}

ουκ εστιν ωδε αλλ ηγερθη μνησθητε ως ελαλησεν υμιν ετι ων εν τη γαλιλαια[24:6]{.aside}

λεγων οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθηναι εις χειρας [ανθρωπων]{.greek-abbr} αμαρτωλων και [σταυρωθηναι]{.greek-abbr} και τη τριτη ημερα αναστηναι[24:7]{.aside}

και εμνησθησαν των ρηματων αυτου[24:8]{.aside}

και υποστρεψασαι απο του μνημειου απηγγειλαν [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted} τοις ενδεκα και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [λοιποις]{.greek-omitted} [λυποις]{.greek-added}[24:9]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} η [μαγ]{.greek-added} [μαγδαληνη]{.greek-omitted} [δαληνη]{.greek-added} μαρια και ιωαννα και μαρια ιακωβου και αι λοιπαι συν αυταις αι ελεγον προς τους αποστολους ταυτα[24:10]{.aside}

και εφανησαν ενωπιον αυτων ωσει ληρος τα ρηματα αυτων και ηπιστουν αυταις[24:11]{.aside}

ο δε πετρος αναστας εδραμεν επι το μνημειον και παρακυψας βλεπει τα οθονια κειμενα μονα και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς εαυτον [θαυμαζων]{.greek-omitted} [θαυμαζον]{.greek-added} το γεγονος[24:12]{.aside}

και ιδου δυο εξ αυτων ησαν πορευομενοι εν αυτη τη ημερα εις κωμην απεχουσαν σταδιους εξηκοντα απο [ιερουσαλημ]{.greek-abbr} η ονομα εμμαους[24:13]{.aside}

και αυτοι ωμιλουν προς αλληλους περι παντων των συμβεβηκοτων τουτων[24:14]{.aside}

και εγενετο εν τω ομιλειν αυτους και συζητειν και αυτος ο [ιησους]{.greek-abbr} εγγισας συνεπορευετο αυτοις[24:15]{.aside}

οι δε οφθαλμοι αυτων εκρατουντο του μη επιγνωναι αυτον[24:16]{.aside}

ειπεν δε προς αυτους τινες οι λογοι ουτοι ους αντιβαλλετε προς αλληλους περιπατουντες και εστε σκυθρωποι[24:17]{.aside}

αποκριθεις δε ο εις ω ονομα κλεοπας ειπεν προς αυτον συ μονος παροικεις [ιερουσαλημ]{.greek-abbr} και ουκ εγνως τα γενομενα εν αυτη εν ταις ημεραις ταυταις[24:18]{.aside}

και ειπεν αυτοις ποια οι δε ειπον αυτω τα περι [ιησου]{.greek-abbr} του ναζωραιου ος εγενετο ανηρ προφητης δυνατος εν εργω και λογω εναντιον του [θεου]{.greek-abbr} και παντος του λαου[24:19]{.aside}

οπως τε παρεδωκαν αυτον οι αρχιερεις και οι αρχοντες ημων εις κριμα θανατου και [εσταυρωσαν]{.greek-abbr} αυτον[24:20]{.aside}

ημεις δε ηλπιζομεν οτι αυτος εστιν ο μελλων λυτρουσθαι τον [ισραηλ]{.greek-abbr} αλλα γε συν [πασιν]{.greek-omitted} [πασι]{.greek-added} τουτοις τριτην ταυτην ημεραν αγει σημερον αφ ου ταυτα εγενετο[24:21]{.aside}

αλλα και γυναικες τινες εξ ημων εξεστησαν ημας γενομεναι ορθριαι επι το μνημειον[24:22]{.aside}

και μη ευρουσαι το σωμα αυτου ηλθον λεγουσαι και οπτασιαν αγγελων εωρακεναι οι λεγουσιν αυτον ζην[24:23]{.aside}

και απηλθον τινες των συν ημιν επι το μνημειον και ευρον ουτως καθως και αι γυναικες ειπον αυτον δε ουκ ειδον[24:24]{.aside}

και αυτος ειπεν προς αυτους ω ανοητοι και βραδεις τη καρδια του πιστευειν επι πασιν οις ελαλησαν οι προφηται[24:25]{.aside}

ουχι ταυτα εδει παθειν τον [χριστον]{.greek-abbr} και εισελθειν εις την δοξαν αυτου[24:26]{.aside}

και αρξαμενος απο μωσεως και απο παντων των προφητων διηρμηνευεν αυτοις εν πασαις ταις γραφαις τα περι εαυτου[24:27]{.aside}

και ηγγισαν εις την κωμην ου επορευοντο και αυτος προσεποιειτο [πορρωτερω]{.greek-omitted} [πορροτερω]{.greek-added} πορευεσθαι[24:28]{.aside}

και παρεβιασαντο αυτον λεγοντες μεινον μεθ ημων οτι προς εσπεραν [εστιν]{.greek-omitted} [εστι]{.greek-added} και κεκλικεν η ημερα και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} του μειναι συν αυτοις[24:29]{.aside}

και εγενετο εν τω κατακλιθηναι αυτον μετ αυτων λαβων τον αρτον [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και κλασας επεδιδου αυτοις[24:30]{.aside}

αυτων δε διηνοιχθησαν οι οφθαλμοι και επεγνωσαν αυτον και αυτος αφαντος εγενετο απ αυτων[24:31]{.aside}

και ειπον προς αλληλους ουχι η καρδια ημων καιομενη ην εν ημιν ως ελαλει ημιν εν τη οδω και ως διηνοιγεν ημιν τας γραφας[24:32]{.aside}

και ανασταντες αυτη τη ωρα υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} και ευρον συνηθροισμενους τους ενδεκα και τους συν αυτοις[24:33]{.aside}

λεγοντας οτι ηγερθη ο [κυριος]{.greek-abbr} οντως και ωφθη σιμωνι[24:34]{.aside}

και αυτοι εξηγουντο τα εν τη οδω και ως εγνωσθη αυτοις εν τη κλασει του αρτου[24:35]{.aside}

ταυτα δε αυτων λαλουντων αυτος ο [ιησους]{.greek-abbr} εστη εν μεσω αυτων και λεγει αυτοις ειρηνη υμιν[24:36]{.aside}

πτοηθεντες δε και εμφοβοι γενομενοι εδοκουν πνευμα θεωρειν[24:37]{.aside}

και ειπεν αυτοις τι τεταραγμενοι εστε και δια τι διαλογισμοι αναβαινουσιν εν ταις καρδιαις υμων[24:38]{.aside}

ιδετε τας χειρας μου και τους ποδας μου οτι αυτος εγω ειμι ψηλαφησατε με και ιδετε οτι [πνευμα]{.greek-abbr} σαρκα και οστεα ουκ εχει καθως εμε θεωρειτε εχοντα[24:39]{.aside}

και τουτο ειπων επεδειξεν αυτοις τας χειρας και τους ποδας[24:40]{.aside}

ετι δε απιστουντων αυτων απο της χαρας και θαυμαζοντων ειπεν αυτοις εχετε τι βρωσιμον ενθαδε[24:41]{.aside}

οι δε επεδωκαν αυτω ιχθυος οπτου μερος και απο [μελισσιου]{.greek-omitted} [μελλισσιου]{.greek-added} [κηριου]{.greek-omitted} [κηριον]{.greek-added}[24:42]{.aside}

και λαβων ενωπιον αυτων εφαγεν[24:43]{.aside}

ειπεν δε αυτοις ουτοι οι λογοι ους ελαλησα προς υμας ετι ων συν υμιν οτι δει πληρωθηναι παντα τα γεγραμμενα εν τω νομω μωσεως και προφηταις και ψαλμοις περι εμου[24:44]{.aside}

τοτε διηνοιξεν αυτων τον νουν του συνιεναι τας γραφας[24:45]{.aside}

και ειπεν αυτοις οτι ουτως γεγραπται και ουτως εδει παθειν τον [χριστον]{.greek-abbr} και αναστηναι εκ νεκρων τη τριτη ημερα[24:46]{.aside}

και [κηρυ]{.greek-added} [κηρυχθηναι]{.greek-omitted} [χθηναι]{.greek-added} επι τω ονοματι αυτου μετανοιαν και αφεσιν αμαρτιων εις παντα τα εθνη αρξαμενον απο [ιερουσαλημ]{.greek-abbr}[24:47]{.aside}

υμεις δε εστε μαρτυρες τουτων[24:48]{.aside}

και ιδου εγω αποστελλω την επαγγελιαν του [πατρος]{.greek-abbr} μου εφ υμας υμεις δε καθισατε εν τη πολει [ιερουσαλημ]{.greek-abbr} εως ου ενδυσησθε δυναμιν εξ υψους[24:49]{.aside}

[εξηγαγεν]{.greek-omitted} [εξηγαγε]{.greek-added} δε αυτους εξω εως εις βηθανιαν και επαρας τας χειρας αυτου ευλογησεν αυτους[24:50]{.aside}

και εγενετο εν τω ευλογειν αυτον αυτους διεστη απ αυτων και ανεφερετο εις τον [ουρανον]{.greek-abbr}[24:51]{.aside}

και αυτοι προσκυνησαντες αυτον υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} μετα χαρας μεγαλης[24:52]{.aside}

και ησαν δια παντος εν τω ιερω αινουντες και ευλογουντες τον [θεον]{.greek-abbr} αμην[24:53]{.aside}

