---
title: "Collation of Byz^RP^ vs 30349 (349)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 349 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30349).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 349                                   	| λογος                              	|
| 349 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 349 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 349               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 349                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 349 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 349                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ πρ[ο]{.greek-supplied}σωπου σου ος κατασκευασ[ε]{.unclear}[ι]{.greek-supplied} [τ]{.greek-supplied}[η]{.unclear}ν οδον σου εμπροσθεν σου[1:2]{.aside}

φω[ν]{.unclear}η βοωντος εν τη ερημω ετοιμ[α]{.unclear}σατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μ[ε]{.unclear}τανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευτο]{.greek-added} προς αυτον πασα η ιουδαια χωρα [και]{.greek-omitted} [οι]{.greek-omitted} [ιεροσολυμιται]{.greek-omitted} [και]{.greek-omitted} [εβαπτιζοντο]{.greek-omitted} [παντες]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιορδανη]{.greek-omitted} [ποταμω]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} [εξομολογουμενοι]{.greek-omitted} [τας]{.greek-omitted} [αμαρτιας]{.greek-omitted} [αυτων]{.greek-omitted}[1:5]{.aside}

και [εξεπορευετο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πασα]{.greek-omitted} [η]{.greek-omitted} [ιουδαια]{.greek-omitted} [χωρα]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5 | instance no. 2]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και [εσθιων]{.greek-omitted} [εσθηων]{.greek-added} ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα [υμας]{.greek-omitted} [ημας]{.greek-added} εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη [υπο]{.greek-omitted} [ιωαννου]{.greek-omitted} εις τον ιορδανην [υπο]{.greek-added} [ιωανου]{.greek-added}[1:9]{.aside}

και ευθεως [αναβαινων]{.greek-omitted} [αναβενων]{.greek-added} απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} [και]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ωσει]{.greek-omitted} [περιστεραν]{.greek-omitted} [καταβαινον]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted}[1:10]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [αναβαινων]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [υδατος]{.greek-omitted} [ειδεν]{.greek-omitted} [σχιζομενους]{.greek-omitted} [τους]{.greek-omitted} [ουρανους]{.greek-omitted} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον επ αυτον[1:10 | instance no. 2]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω ευδοκησα[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} [αυτον]{.greek-added} το [πνευμα]{.greek-abbr} [αυτον]{.greek-omitted} εκβαλλει εις την [ερημον]{.greek-omitted} [ερημων]{.greek-added}[1:12]{.aside}

και ην εκει [τεσσαρακοντα]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} ημερας [τεσσαρακοντα]{.greek-omitted} πειραζομενος υπο του σατανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και [ηγγικεν]{.greek-omitted} [ηγγεικεν]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου [του]{.greek-omitted} [σιμωνος]{.greek-omitted} [βαλλοντας]{.greek-omitted} [αμφιβληστρον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [αλιεις]{.greek-omitted}[1:16]{.aside}

[περιπατων]{.greek-omitted} [δε]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [ειδεν]{.greek-omitted} [σιμωνα]{.greek-omitted} [και]{.greek-omitted} [ανδρεαν]{.greek-omitted} [τον]{.greek-omitted} [αδελφον]{.greek-omitted} [αυτου]{.greek-omitted} του σιμωνος βαλλοντας αμφιβληστρον [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσαν]{.greek-added} ησαν γαρ αλιεις[1:16 | instance no. 2]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και [ευθεως]{.greek-omitted} [ευθεσως]{.greek-added} αφεντες τα [δικτυα]{.greek-omitted} [δυκτυα]{.greek-added} [αυτων]{.greek-omitted} ηκολουθησαν αυτω[1:18]{.aside}

και προβας [εκειθεν]{.greek-omitted} ολιγον ειδεν ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω [πλοιω]{.greek-omitted} [πληω]{.greek-added} καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται [μετ]{.greek-added} [αυτου]{.greek-added} εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [και]{.greek-added} [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και [εξεπλη]{.greek-added} [εξεπλησσοντο]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [διδασκων]{.greek-omitted} [αυτους]{.greek-omitted} [ως]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχων]{.greek-omitted} [και]{.greek-omitted} [ουχ]{.greek-omitted} [ως]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted}[1:22]{.aside}

[σσοντο]{.greek-added} [και]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} επι τη [δαχη]{.greek-added} [διδαχη]{.corr} αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22 | instance no. 2]{.aside}

και [[ει]{.unclear}ν]{.greek-added} [ην]{.corr} εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες [απολεσαι]{.greek-omitted} [απολεσε]{.greek-added} ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και [επετιμησεν]{.greek-omitted} [επετοιμησεν]{.greek-added} αυτω ο [ιησους]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} λεγων φιμωθητι και εξελθε [εξ]{.greek-omitted} [[απ]{.corr}]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε [συζητειν]{.greek-omitted} [ζητην]{.greek-added} προς εαυτους λεγοντας τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξου[―]{.gap}σιαν [[εξουσιαν]{.corr}]{.greek-added} και τοις πνευμασιν τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

[και]{.greek-added} εξηλθεν [δε]{.greek-omitted} η ακοη αυτου [ευθυς]{.greek-omitted} εις [ολην]{.greek-omitted} την [περιχωρον]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted}[1:28]{.aside}

[εξηλθεν]{.greek-omitted} [δε]{.greek-omitted} [η]{.greek-omitted} [ακοη]{.greek-omitted} [αυτου]{.greek-omitted} [ευθυς]{.greek-omitted} [εις]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} περιχωρον [τ[ου]{.unclear}]{.greek-added} [της]{.corr} γαλιλαιας[1:28 | instance no. 2]{.aside}

και ευθεως [εξελθων]{.greek-added} εκ της συναγωγης [εξελθοντες]{.greek-omitted} [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο [πυρεσσουσα]{.greek-omitted} [πειρεσσουσα]{.greek-added} και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων [ηγερεν]{.greek-added} [ηγειρεν]{.corr} αυτην κρατησας της χειρος αυτης και [αφηκεν]{.greek-omitted} [αφηκαιν]{.greek-added} αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε [εδυ]{.greek-omitted} [εδυσε]{.greek-added} ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και [ην]{.greek-added} [ολη]{.greek-added} η [πολις]{.greek-omitted} [ολη]{.greek-omitted} [πολη]{.greek-added} επισυνηγμενη [ην]{.greek-omitted} προς την θυραν[1:33]{.aside}

και εθεραπευσεν [πολλους]{.greek-omitted} [παντας]{.greek-added} [τους]{.greek-added} κακως εχοντας ποικιλαις νοσοις και [δαι]{.greek-added} [δαιμονια]{.greek-omitted} [πολλα]{.greek-omitted} [εξεβαλεν]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηφιεν]{.greek-omitted} [λαλειν]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [οτι]{.greek-omitted} [ηδεισαν]{.greek-omitted} [αυτον]{.greek-omitted}[1:34]{.aside}

[και]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [πολλους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [ποικιλαις]{.greek-omitted} [νοσοις]{.greek-omitted} [και]{.greek-omitted} [δαιμονια]{.greek-omitted} [μονια]{.greek-added} πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34 | instance no. 2]{.aside}

και [πρωι]{.greek-omitted} [προι]{.greek-added} [εννυχον]{.greek-omitted} [εννυχα]{.greek-added} λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις [ερημον]{.greek-omitted} [ερημων]{.greek-added} τοπον κακει προσηυχετο[1:35]{.aside}

και κατεδιωξαν αυτον ο [τε]{.greek-added} σιμων και οι [μετ]{.greek-omitted} [μαθηται]{.greek-added} αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες [σε]{.greek-omitted} [ε]{.greek-added} [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας [κωμοπολεις]{.greek-omitted} [κωμωπολλεις]{.greek-added} ινα και εκει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα [δε]{.greek-added} [δαιμονια]{.corr} εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων [αυτον]{.greek-omitted} [αυτων]{.greek-added} και γονυπετων αυτον και λεγων αυτω οτι [ε]{.greek-added} [εαν]{.greek-omitted} [θελης]{.greek-omitted} [δυνασαι]{.greek-omitted} [με]{.greek-omitted} [καθαρισαι]{.greek-omitted}[1:40]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [λεπρος]{.greek-omitted} [παρακαλων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [γονυπετων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγων]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [εαν]{.greek-omitted} [αν]{.greek-added} θελης [δυνασε]{.greek-added} [δυνασαι]{.corr} με καθαρισαι[1:40 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως [η]{.greek-added} [λεπρα]{.greek-added} απηλθεν απ αυτου [η]{.greek-omitted} [λεπρα]{.greek-omitted} [ευθεως]{.greek-added} [του]{.greek-added} [λογου]{.greek-added} [ηποντος]{.greek-added} και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος [αυτω]{.greek-omitted} ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι [αυτον]{.greek-omitted} δυνασθαι [αυτων]{.greek-added} φανερως εις πολιν εισελθειν αλλ [ε]{.greek-added} [εξω]{.greek-omitted} [εν]{.greek-omitted} [ερημοις]{.greek-omitted} [τοποις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ηρχοντο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πανταχοθεν]{.greek-omitted}[1:45]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εξελθων]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [πολλα]{.greek-omitted} [και]{.greek-omitted} [διαφημιζειν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ωστε]{.greek-omitted} [μηκετι]{.greek-omitted} [αυτον]{.greek-omitted} [δυνασθαι]{.greek-omitted} [φανερως]{.greek-omitted} [εις]{.greek-omitted} [πολιν]{.greek-omitted} [εισελθειν]{.greek-omitted} [αλλ]{.greek-omitted} [εξω]{.greek-omitted} [ξω]{.greek-added} εν ερημοις τοποις ην και ηρχοντο προς αυτον [πανχοθεν]{.greek-added} [πανταχοθεν]{.corr}[1:45 | instance no. 2]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι [ωστε]{.greek-omitted} [ωσστε]{.greek-added} μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω [τεκνον]{.greek-omitted} [αφεωνται]{.greek-omitted} [σοι]{.greek-omitted} [αι]{.greek-omitted} [αμαρτιαι]{.greek-omitted} [σου]{.greek-omitted}[2:5]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [παραλυτικω]{.greek-omitted} τεκνον αφεωνται σοι αι αμαρτιαι σου[2:5 | instance no. 2]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραματεων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως λαλει βλασφημιας [τις]{.greek-omitted} [της]{.greek-added} δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν [τω[―]{.gap}]{.greek-added} [τω]{.corr} παραλυτικω αφεωνται σου αι αμαρτιαι η ειπειν εγειραι [και]{.greek-omitted} αρον [τον]{.greek-added} [κραβατον]{.greek-added} σου [τον]{.greek-omitted} [κραββατον]{.greek-omitted} και περιπατει[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ειδη]{.greek-added} [οτι]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχει]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [αφιεναι]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [αμαρτιας]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [παραλυτικω]{.greek-omitted}[2:10]{.aside}

[τε]{.greek-added} [ινα]{.greek-omitted} [δε]{.greek-omitted} [ειδητε]{.greek-omitted} οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιεναι]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10 | instance no. 2]{.aside}

σοι λεγω εγειραι [και]{.greek-omitted} αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και [ευθεως]{.greek-added} ηγερθη [ευθεως]{.greek-omitted} και αρας τον κραββατον εξηλθεν [εναντιον]{.greek-omitted} [ενωπιον]{.greek-added} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως ειδομεν[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την [θαλασσαν]{.greek-omitted} [θαλασαν]{.greek-added} και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων ειδεν [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του [αλφαιου]{.greek-omitted} [αλφεου]{.greek-added} καθημενον επι το τελωνιον και λεγει αυτω ακολουθει [μοι]{.greek-omitted} [μει]{.greek-added} και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και [εγε]{.greek-added} [εγενετο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κατακεισθαι]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [τελωναι]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλοι]{.greek-omitted} [συνανεκειντο]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted}[2:15]{.aside}

[νετο]{.greek-added} [και]{.greek-omitted} [εγενετο]{.greek-omitted} εν [τω]{.greek-omitted} [το]{.greek-added} κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15 | instance no. 2]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα [των]{.greek-omitted} [τον]{.greek-added} τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων [εσθιει]{.greek-omitted} [εσθηετε]{.greek-added} και [πινει]{.greek-omitted} [πινετε]{.greek-added}[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες [ουκ]{.greek-omitted} [ου]{.greek-added} [γαρ]{.greek-added} ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται [ιωαννου]{.greek-omitted} [ιωανου]{.greek-added} και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται [ιω]{.greek-added} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευουσιν]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [σοι]{.greek-omitted} [μαθηται]{.greek-omitted} [ου]{.greek-omitted} [νηστευουσιν]{.greek-omitted}[2:18]{.aside}

[ανου]{.greek-added} [και]{.greek-omitted} [ησαν]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευοντες]{.greek-omitted} [και]{.greek-omitted} [ερχονται]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18 | instance no. 2]{.aside}

και ειπεν αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

[και]{.greek-omitted} ουδεις επιβλημα ρακους αγναφου επιρραπτει επι ιματιω παλαιω ει δε [μη]{.greek-omitted} [αιρει]{.greek-omitted} [μηγε]{.greek-added} [ερει]{.greek-added} το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [καινους]{.greek-omitted} [βλητεον]{.greek-omitted}[2:22]{.aside}

[και]{.greek-omitted} [ουδεις]{.greek-omitted} [βαλλει]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [παλαιους]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [ρησσει]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [ο]{.greek-omitted} [νεος]{.greek-omitted} [τους]{.greek-omitted} [ασκους]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [εκχειται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [απολουνται]{.greek-omitted} [αλλα]{.greek-omitted} [[α]{.greek-supplied}λλ]{.greek-added} οινον νεον εις ασκους καινους βλητεον[2:22 | instance no. 2]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} [εν]{.greek-omitted} τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ [αρχιερεως]{.greek-omitted} [αρχιερεαν]{.greek-added} και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το [σαββατον]{.greek-omitted} [σαββα]{.greek-added}[2:27]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [το]{.greek-omitted} [σαββατον]{.greek-omitted} [δια]{.greek-omitted} τον [ανθρωπον]{.greek-omitted} [εγενετο]{.greek-omitted} [ουχ]{.greek-omitted} [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [σαββατον]{.greek-omitted}[2:27 | instance no. 2]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηρανμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα εγειραι εις το [μεσον]{.greek-omitted} [μεσων]{.greek-added}[3:3]{.aside}

και λεγει αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η [αποκτειναι]{.greek-omitted} [απολεσαι]{.greek-added} οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη πωρωσει της καρδιας [αυτων]{.greek-omitted} [αυτον]{.greek-added} λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η [χειρ]{.greek-omitted} [αυτου]{.greek-omitted} [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[3:5]{.aside}

[και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [μετ]{.greek-omitted} [οργης]{.greek-omitted} [συλλυπουμενος]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [πωρωσει]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [εκτεινον]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξετεινεν]{.greek-omitted} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} [η]{.greek-omitted} χειρ αυτου υγιης ως η αλλη[3:5 | instance no. 2]{.aside}

και εξελθοντες οι φαρισαιοι [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου [προς]{.greek-omitted} [παρα]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ [ηκολουθησαν]{.greek-added} ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον προσκαρτερη αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} [οσοι]{.greek-omitted} [ειχον]{.greek-omitted} [μαστιγας]{.greek-omitted}[3:10]{.aside}

[πολλους]{.greek-omitted} [γαρ]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [ωστε]{.greek-omitted} [επιπιπτειν]{.greek-omitted} [αυτω]{.greek-omitted} [ινα]{.greek-omitted} [αυτου]{.greek-omitted} [αψωνται]{.greek-omitted} οσοι ειχον μαστιγας[3:10 | instance no. 2]{.aside}

και τα [πνευματα]{.corr} τα ακαθαρτα οταν αυτον [εθεωρει]{.greek-omitted} [εθεωρουν]{.greek-added} [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραυγαζον]{.greek-added} λεγοντα οτι συ ει ο [[χριστος]{.greek-abbr}]{.greek-added} [ο]{.greek-added} υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και [επετιμησεν]{.greek-added} [αυτοις]{.greek-added} πολλα [επετιμα]{.greek-omitted} [αυτοις]{.greek-omitted} ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και [εκβαλλ[―]{.gap}]{.greek-added} [εκβαλλειν]{.greek-omitted} [[εκβαλλιν]{.corr}]{.greek-added} τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον του [[―]{.gap}βου]{.greek-added} [ιακωβου]{.corr} και [επεθηκεν]{.greek-omitted} [επεθη]{.greek-added} [αυτοις]{.greek-omitted} [ονοματα]{.greek-omitted} [βοανεργες]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [υιοι]{.greek-omitted} [βροντης]{.greek-omitted}[3:17]{.aside}

[κεν]{.greek-added} [και]{.greek-omitted} [ιακωβον]{.greek-omitted} [τον]{.greek-omitted} [του]{.greek-omitted} [ζεβεδαιου]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [τον]{.greek-omitted} [αδελφον]{.greek-omitted} [του]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [επεθηκεν]{.greek-omitted} αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17 | instance no. 2]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και [σιμωνα]{.greek-omitted} [σιμωναν]{.greek-added} τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται [παλιν]{.greek-omitted} οχλος ωστε μη δυνασθαι αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον [κρατησαι]{.greek-omitted} [κρατησε]{.greek-added} αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι [γραμματεις]{.greek-omitted} [γραματεις]{.greek-added} οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις [πως]{.greek-omitted} [δυναται]{.greek-omitted} [σατανας]{.greek-omitted} [σαταναν]{.greek-omitted} [εκβαλλειν]{.greek-omitted}[3:23]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [πως]{.greek-omitted} [ως]{.greek-added} δυναται σατανας σαταναν εκβαλλειν[3:23 | instance no. 2]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται σταθηναι [η]{.greek-omitted} [οικια]{.greek-omitted} [εκεινη]{.greek-omitted}[3:25]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [ανεστη]{.greek-omitted} [εφ]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [μεμερισται]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [σταθηναι]{.greek-omitted} αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα [αφεθησεται]{.greek-omitted} [αφεθησετε]{.greek-added} τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι [οσα[―]{.gap}]{.greek-added} [οσας]{.corr} αν βλασφημησωσιν[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον [εχει]{.greek-omitted}[3:30]{.aside}

[οτι]{.greek-omitted} [ελεγον]{.greek-omitted} [πνευμα]{.greek-omitted} [ακαθαρτον]{.greek-omitted} εχει[3:30 | instance no. 2]{.aside}

ερχονται ουν [η]{.greek-added} [[μητηρ]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} οι αδελφοι [και]{.greek-omitted} [η]{.greek-omitted} [μητηρ]{.greek-omitted} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} [πολυς]{.greek-added} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει ιδε η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον [καθησθαι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [και]{.greek-omitted} [κα]{.greek-added} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ην]{.greek-omitted}[4:1]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-omitted} [ηρξατο]{.greek-omitted} [διδασκειν]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [συνηχθη]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [ωστε]{.greek-omitted} [αυτον]{.greek-omitted} [εμβαντα]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [καθησθαι]{.greek-omitted} [θησθαι]{.greek-added} εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1 | instance no. 2]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} εν τη διδαχη αυτου[4:2]{.aside}

[ακουετε]{.greek-omitted} [ακουσατε]{.greek-added} ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη [εχειν]{.greek-omitted} [εχην]{.greek-added} βαθος γης[4:5]{.aside}

[και]{.greek-added} [οτε]{.greek-added} [ανετειλεν]{.greek-added} [ο]{.greek-added} [ηλιου]{.greek-omitted} [ηλιος]{.greek-added} [δε]{.greek-omitted} [ανατειλαντος]{.greek-omitted} εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και [συνεπνιξαν]{.greek-omitted} [αυτο]{.greek-omitted} [και]{.greek-omitted} [καρπον]{.greek-omitted} [ουκ]{.greek-omitted} [εδωκεν]{.greek-omitted}[4:7]{.aside}

[απεπνιξαν]{.greek-added} [και]{.greek-omitted} [αλλο]{.greek-omitted} [επεσεν]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [ακανθας]{.greek-omitted} [και]{.greek-omitted} [ανεβησαν]{.greek-omitted} [αι]{.greek-omitted} [ακανθαι]{.greek-omitted} [και]{.greek-omitted} [συνεπνιξαν]{.greek-omitted} αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7 | instance no. 2]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα [γινεται]{.greek-omitted} [λεγεται]{.greek-added}[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουουσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [και]{.greek-omitted} [αφεθη]{.greek-omitted} [αυτοις]{.greek-omitted} [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted}[4:12]{.aside}

[ινα]{.greek-omitted} [βλεποντες]{.greek-omitted} [βλεπωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [μηποτε]{.greek-omitted} [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12 | instance no. 2]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} ο σατανας και αιρει [τον]{.greek-omitted} [αυτον]{.greek-added} λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον [ευθεως]{.greek-omitted} μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν [εαυτοις]{.greek-omitted} [αυτοις]{.greek-added} αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον [ευ]{.greek-added} [ευθεως]{.greek-omitted} [σκανδαλιζονται]{.greek-omitted}[4:17]{.aside}

[και]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [ριζαν]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} [αλλα]{.greek-omitted} [προσκαιροι]{.greek-omitted} [εισιν]{.greek-omitted} [ειτα]{.greek-omitted} [γενομενης]{.greek-omitted} [θλιψεως]{.greek-omitted} [η]{.greek-omitted} [διωγμου]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ευθεως]{.greek-omitted} [θεως]{.greek-added} σκανδαλιζονται[4:17 | instance no. 2]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις [μητι]{.greek-omitted} [μητει]{.greek-added} ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον [ο]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [φανερωθη]{.greek-omitted} [ουδε]{.greek-omitted} [εγενετο]{.greek-omitted} [αποκρυφον]{.greek-omitted} [αλλ]{.greek-omitted} [ινα]{.greek-omitted} [εις]{.greek-omitted} [φανερον]{.greek-omitted} [ελθη]{.greek-omitted}[4:22]{.aside}

[ου]{.greek-omitted} [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [τι]{.greek-omitted} [κρυπτον]{.greek-omitted} ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22 | instance no. 2]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε μετρηθησεται υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} εχη δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και [καθευδη]{.greek-omitted} [καθευδει]{.greek-added} και εγειρηται νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη [καρποφορει]{.greek-omitted} [καρποφο]{.greek-added} [πρωτον]{.greek-omitted} [χορτον]{.greek-omitted} [ειτα]{.greek-omitted} [σταχυν]{.greek-omitted} [ειτα]{.greek-omitted} [πληρη]{.greek-omitted} [σιτον]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σταχυι]{.greek-omitted}[4:28]{.aside}

[ρει]{.greek-added} [αυτοματη]{.greek-omitted} [γαρ]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [καρποφορει]{.greek-omitted} πρωτον χορτον ειτα σταχυν ειτα πληρη [τον]{.greek-added} σιτον εν τω σταχυι[4:28 | instance no. 2]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσομεν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} [παραβαλομεν]{.greek-added} αυτην[4:30]{.aside}

ως κοκκον σιναπεως ος οταν σπαρη επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη [αναβε]{.greek-added} [αναβαινει]{.corr} και γινεται [μειζον]{.greek-added} παντων των λαχανων [μειζων]{.greek-omitted} και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} [κατασκηνουν]{.greek-omitted}[4:32]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [σπαρη]{.greek-omitted} [αναβαινει]{.greek-omitted} [και]{.greek-omitted} [γινεται]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} [λαχανων]{.greek-omitted} [μειζων]{.greek-omitted} [και]{.greek-omitted} [ποιει]{.greek-omitted} [κλαδους]{.greek-omitted} [μεγαλους]{.greek-omitted} [ωστε]{.greek-omitted} [δυνασθαι]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [σκιαν]{.greek-omitted} [αυτου]{.greek-omitted} [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} κατασκηνουν[4:32 | instance no. 2]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως εδυναντο ακουειν[4:33]{.aside}

[χωρις]{.greek-omitted} [χορις]{.greek-added} δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε [πλοιαρια]{.greek-omitted} [πλοια]{.greek-added} ην μετ αυτου[4:36]{.aside}

και γινεται λαιλαψ ανεμου μεγαλη τα δε κυματα επεβαλλεν εις το πλοιον ωστε αυτο ηδη [γεμιζεσθαι]{.greek-omitted} [βυθιζεσθαι]{.greek-added}[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι [το]{.greek-omitted} [προσκεφαλαιον]{.greek-omitted} [προσκεφαλεον]{.greek-added} καθευδων [και]{.greek-omitted} [διεγειρουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [οτι]{.greek-omitted} [απολλυμεθα]{.greek-omitted}[4:38]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [αυτος]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [πρυμνη]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [προσκεφαλαιον]{.greek-omitted} [καθευδων]{.greek-omitted} και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38 | instance no. 2]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την [χωραν]{.greek-omitted} [χοραν]{.greek-added} των γαδαρηνων[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως [υπηντη]{.greek-added} [απηντησεν]{.greek-omitted} [αυτω]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [μνημειων]{.greek-omitted} [ανθρωπος]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [ακαθαρτω]{.greek-omitted}[5:2]{.aside}

[σεν]{.greek-added} [και]{.greek-omitted} [εξελθοντι]{.greek-omitted} [αυτω]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [πλοιου]{.greek-omitted} [ευθεως]{.greek-omitted} [απηντησεν]{.greek-omitted} αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2 | instance no. 2]{.aside}

ος την κατοικησιν ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [ισχυεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας [και]{.greek-added} εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις μνημασιν ην κραζων και [κατακοπτων]{.greek-omitted} [κατακοπτον]{.greek-added} εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας [φ[η]{.unclear}]{.greek-added} [φωνη]{.corr} μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και [σοι]{.greek-omitted} [ιησου]{.greek-omitted} [υιε]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [υψιστου]{.greek-omitted} [ορκιζω]{.greek-omitted} [σε]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [μη]{.greek-omitted} [με]{.greek-omitted} [βασανισης]{.greek-omitted}[5:7]{.aside}

[και]{.greek-omitted} [κραξας]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [ειπεν]{.greek-omitted} [τι]{.greek-omitted} [εμοι]{.greek-omitted} [και]{.greek-omitted} σοι [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με [[―]{.gap}νισης]{.greek-added} [βασανισης]{.corr}[5:7 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον [εκ]{.greek-omitted} [απο]{.greek-added} του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [επηρωτησεν]{.greek-added} [αυτω]{.greek-added} τι [ονομα]{.greek-added} σοι [ονομα]{.greek-omitted} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει [αγελη]{.greek-added} [χοιρων]{.greek-added} [μεγαλη]{.greek-added} προς τω ορει [αγελη]{.greek-omitted} [χοιρων]{.greek-omitted} [μεγαλη]{.greek-omitted} βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους [εισελθωμεν]{.greek-omitted} [εισσελθωμεν]{.greek-added}[5:12]{.aside}

και επετρεψεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα πνευματα τα ακαθαρτα εισηλθον εις τους χοιρους και [ωρμησεν]{.greek-omitted} [η]{.greek-omitted} [αγελη]{.greek-omitted} [κατα]{.greek-omitted} [του]{.greek-omitted} [κρημνου]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [ησαν]{.greek-omitted} [δε]{.greek-omitted} [ως]{.greek-omitted} [δισχιλιοι]{.greek-omitted} [και]{.greek-omitted} [επνιγοντο]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted}[5:13]{.aside}

[και]{.greek-omitted} [επετρεψεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εξελθοντα]{.greek-omitted} [τα]{.greek-omitted} [πνευματα]{.greek-omitted} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [εισηλθον]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [και]{.greek-omitted} [ωρμησεν]{.greek-omitted} [ωρμησε]{.greek-added} [πασα]{.greek-added} η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13 | instance no. 2]{.aside}

[και]{.greek-added} οι [δε]{.greek-omitted} βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι εστιν το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον [δαιμονιζομενον]{.greek-omitted} [δεμονιζομενον]{.greek-added} καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

διηγησαντο δε αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των [χοιρων]{.greek-omitted} [χειρων]{.greek-added}[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων [αυτον]{.greek-added} [αυτων]{.corr}[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει [αυτον]{.greek-omitted} [ο]{.greek-omitted} [δαιμονισθεις]{.greek-omitted} [ινα]{.greek-omitted} [η]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[5:18]{.aside}

[και]{.greek-omitted} [εμβαντος]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [παρεκαλει]{.greek-omitted} αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} μετ αυτου [η]{.greek-added}[5:18 | instance no. 2]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι [ιαειρος]{.greek-omitted} [αειρος]{.greek-added} και [ιδων]{.greek-omitted} [ιδον]{.greek-added} αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου [εσχατως]{.greek-omitted} [εχει]{.greek-omitted} [ινα]{.greek-omitted} [ελθων]{.greek-omitted} [επιθης]{.greek-omitted} [αυτη]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [οπως]{.greek-omitted} [σωθη]{.greek-omitted} [και]{.greek-omitted} [ζησεται]{.greek-omitted}[5:23]{.aside}

[και]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [πολλα]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [μου]{.greek-omitted} εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23 | instance no. 2]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και ηκολουθει αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα [παρ]{.greek-omitted} [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [εν]{.greek-added} [εαυτη]{.greek-added} οτι [εαν]{.greek-added} [αψωμαι]{.greek-added} καν των ιματιων αυτου [αψωμαι]{.greek-omitted} σωθησομαι[5:28]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} εξηρανθη η πηγη του [αιματος]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [εγνω]{.greek-omitted} [τω]{.greek-omitted} [σωματι]{.greek-omitted} [οτι]{.greek-omitted} [ιαται]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαστιγος]{.greek-omitted}[5:29]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [εξηρανθη]{.greek-omitted} [η]{.greek-omitted} [πηγη]{.greek-omitted} [του]{.greek-omitted} αιματος αυτης και εγνω τω σωματι οτι [ιαται]{.greek-omitted} [ιατε]{.greek-added} απο της [μαστιγος]{.greek-omitted} [μαστηγος]{.greek-added}[5:29 | instance no. 2]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν [επιστραφεις]{.greek-omitted} [επιστραφης]{.greek-added} εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα [ειδυια]{.greek-omitted} [ειδεια]{.greek-added} ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και [ισθι]{.greek-omitted} [υγιης]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαστιγος]{.greek-omitted} [σου]{.greek-omitted}[5:34]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} [θυγατερ]{.greek-omitted} [η]{.greek-omitted} [πιστις]{.greek-omitted} [σου]{.greek-omitted} [σεσωκεν]{.greek-omitted} [σε]{.greek-omitted} [υπαγε]{.greek-omitted} [εις]{.greek-omitted} [ειρηνην]{.greek-omitted} [και]{.greek-omitted} ισθι υγιης απο [της]{.greek-omitted} [τεις]{.greek-added} μαστιγος σου[5:34 | instance no. 2]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλεις]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω [συνακολουθησαι]{.greek-omitted} [συνακολουθουσαι]{.greek-added} ει μη πετρον και [ιακωβον]{.greek-omitted} [ιακοβον]{.greek-added} και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι θορυβεισθε και κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και [κατε]{.greek-added} [κατεγελων]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [εκβαλων]{.greek-omitted} [παντας]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [του]{.greek-omitted} [παιδιου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εισπορευεται]{.greek-omitted} [οπου]{.greek-omitted} [ην]{.greek-omitted} [το]{.greek-omitted} [παιδιον]{.greek-omitted} [ανακειμενον]{.greek-omitted}[5:40]{.aside}

[γελων]{.greek-added} [και]{.greek-omitted} [κατεγελων]{.greek-omitted} αυτου ο δε [εκβαλων]{.greek-omitted} [εκβαλλων]{.greek-added} παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους [μετ]{.greek-omitted} [μαιτ]{.greek-added} αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40 | instance no. 2]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη [ταλιθα]{.greek-omitted} [ταβλιθα]{.greek-added} [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω εγειραι[5:41]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα [μηδεις]{.greek-omitted} [μειδεις]{.greek-added} γνω τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και [γενο]{.greek-added} [γενομενου]{.greek-omitted} [σαββατου]{.greek-omitted} [ηρξατο]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [συναγωγη]{.greek-omitted} [διδασκειν]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [ακουοντες]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [ποθεν]{.greek-omitted} [τουτω]{.greek-omitted} [ταυτα]{.greek-omitted} [και]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [η]{.greek-omitted} [δοθεισα]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [δυναμεις]{.greek-omitted} [τοιαυται]{.greek-omitted} [δια]{.greek-omitted} [των]{.greek-omitted} [χειρων]{.greek-omitted} [αυτου]{.greek-omitted} [γινονται]{.greek-omitted}[6:2]{.aside}

[μενου]{.greek-added} [και]{.greek-omitted} [γενομενου]{.greek-omitted} σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η σοφια η δοθεισα αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2 | instance no. 2]{.aside}

ουχ ουτος εστιν ο τεκτων ο υιος [της]{.greek-added} μαριας [και]{.greek-added} αδελφος [δε]{.greek-omitted} [ιακωβου]{.greek-omitted} [ιακοβου]{.greek-added} και ιωση και ιουδα και [σιμωνος]{.greek-omitted} [συμωνος]{.greek-added} και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο [εν]{.greek-omitted} [επ]{.greek-added} αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη πατριδι αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} [αυτου]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει [ουδεμιαν]{.greek-omitted} [ουδαιμιαν]{.greek-added} δυναμιν ποιησαι ει μη ολιγοις [αρρω]{.greek-added} [αρρωστοις]{.greek-omitted} [επιθεις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [εθεραπευσεν]{.greek-omitted}[6:5]{.aside}

[στοις]{.greek-added} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνατο]{.greek-omitted} [εκει]{.greek-omitted} [ουδεμιαν]{.greek-omitted} [δυναμιν]{.greek-omitted} [ποιησαι]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ολιγοις]{.greek-omitted} [αρρωστοις]{.greek-omitted} επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5 | instance no. 2]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα [μαθητας]{.greek-added} [αυτου]{.greek-added} και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των [ακαθαρτων]{.greek-omitted} [ακαθαρτον]{.greek-added}[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδεδυσθαι]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις [οπου]{.greek-omitted} [ο]{.greek-added} [εαν]{.greek-omitted} [αν]{.greek-added} εισελθητε εις [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι αν μη [δε]{.greek-added} [δεξωνται]{.greek-omitted} [υμας]{.greek-omitted} [μηδε]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [υμων]{.greek-omitted} [εκπορευομενοι]{.greek-omitted} [εκειθεν]{.greek-omitted} [εκτιναξατε]{.greek-omitted} [τον]{.greek-omitted} [χουν]{.greek-omitted} [τον]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [η]{.greek-omitted} [γομορροις]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [εκεινη]{.greek-omitted}[6:11]{.aside}

[και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [μη]{.greek-omitted} [δεξωνται]{.greek-omitted} [ξωνται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των [ποδων]{.greek-omitted} [υποδ[―]{.gap}ιματων]{.greek-added} [[υποδηιματων]{.corr}]{.greek-added} υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η γομορροις εν ημερα κρισεως η τη [πολει]{.greek-omitted} [πολη]{.greek-added} εκεινη[6:11 | instance no. 2]{.aside}

και εξελθοντες εκ[η]{.unclear}ρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακουην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων [εκ]{.greek-omitted} [ηγερθη]{.greek-added} [απο]{.greek-added} [των]{.greek-added} νεκρων [ηγερθη]{.greek-omitted} και δια τουτο [ενεργουσιν]{.greek-omitted} αι [δυνα]{.greek-added} [δυναμεις]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted}[6:14]{.aside}

[μεις]{.greek-added} [και]{.greek-omitted} [ηκουσεν]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [ηρωδης]{.greek-omitted} [φανερον]{.greek-omitted} [γαρ]{.greek-omitted} [εγενετο]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [οτι]{.greek-omitted} [ιωαννης]{.greek-omitted} [ο]{.greek-omitted} [βαπτιζων]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} [ηγερθη]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} ενεργουσιν [αι]{.greek-omitted} [δυναμεις]{.greek-omitted} εν αυτω[6:14 | instance no. 2]{.aside}

αλλοι ελεγον οτι ηλιας εστιν αλλοι [δε]{.greek-omitted} ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον εγω απεκεφαλισα ιωαννην ουτος εστιν αυτος ηγερθη [εκ]{.greek-omitted} [απο]{.greek-added} [των]{.greek-added} νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο ιωαννης τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης [ε]{.greek-added} [εφοβειτο]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [ειδως]{.greek-omitted} [αυτον]{.greek-omitted} [ανδρα]{.greek-omitted} [δικαιον]{.greek-omitted} [και]{.greek-omitted} [αγιον]{.greek-omitted} [και]{.greek-omitted} [συνετηρει]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ακουσας]{.greek-omitted} [αυτου]{.greek-omitted} [πολλα]{.greek-omitted} [εποιει]{.greek-omitted} [και]{.greek-omitted} [ηδεως]{.greek-omitted} [αυτου]{.greek-omitted} [ηκουεν]{.greek-omitted}[6:20]{.aside}

[ο]{.greek-omitted} [γαρ]{.greek-omitted} [ηρωδης]{.greek-omitted} [εφοβειτο]{.greek-omitted} [φοβειτο]{.greek-added} τον [ιωαννην]{.greek-omitted} [ιωανην]{.greek-added} ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδε[―]{.gap}ως [[ηδεως]{.corr}]{.greek-added} αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20 | instance no. 2]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις [της]{.greek-omitted} [τοις]{.greek-added} γαλιλαι[α]{.unclear}ς[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω [σοι]{.greek-omitted} [σι]{.greek-added}[6:22]{.aside}

και [ωμοσεν]{.greek-omitted} [ομοσεν]{.greek-added} αυτη οτι ο εαν με αιτησης δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} [αυ]{.greek-added} [αυτης]{.greek-omitted} [τι]{.greek-omitted} [αιτησομαι]{.greek-omitted} [η]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [ιωαννου]{.greek-omitted} [του]{.greek-omitted} [βαπτιστου]{.greek-omitted}[6:24]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [εξελθουσα]{.greek-omitted} [ειπεν]{.greek-omitted} [τη]{.greek-omitted} [της]{.greek-added} [μητρι]{.greek-omitted} [αυτης]{.greek-omitted} τι αιτησομαι η δε ειπεν την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:24 | instance no. 2]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα [μοι]{.greek-omitted} [μη]{.greek-added} [δως]{.greek-omitted} [δω]{.greek-added} εξαυτης επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται [αυτου]{.greek-omitted} [ηλθον]{.greek-omitted} [και]{.greek-omitted} [ηραν]{.greek-omitted} [το]{.greek-omitted} [πτωμα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εθηκαν]{.greek-omitted} [αυτο]{.greek-omitted} [εν]{.greek-omitted} [μνημειω]{.greek-omitted}[6:29]{.aside}

[και]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29 | instance no. 2]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και αναπαυεσθε ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και απηλθον εις ερημον τοπον [τω]{.greek-omitted} [εν]{.greek-added} πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και [πεζη]{.greek-omitted} [πεζοι]{.greek-added} απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους [και]{.greek-omitted} [συνηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ειδε]{.greek-added} [πο]{.greek-added} [πολυν]{.greek-omitted} [οχλον]{.greek-omitted} [και]{.greek-omitted} [εσπλαγχνισθη]{.greek-omitted} [επ]{.greek-omitted} [αυτοις]{.greek-omitted} [οτι]{.greek-omitted} [ησαν]{.greek-omitted} [ως]{.greek-omitted} [προβατα]{.greek-omitted} [μη]{.greek-omitted} [εχοντα]{.greek-omitted} [ποιμενα]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [διδασκειν]{.greek-omitted} [αυτους]{.greek-omitted} [πολλα]{.greek-omitted}[6:34]{.aside}

[και]{.greek-omitted} [εξελθων]{.greek-omitted} [ειδεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [πολυν]{.greek-omitted} [λυν]{.greek-added} οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο [αυτους]{.greek-added} διδασκειν [αυτους]{.greek-omitted} πολλα[6:34 | instance no. 2]{.aside}

και [ηδη]{.greek-omitted} [δη]{.greek-added} ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται αυτου λεγουσιν οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας [αγορασωσιν]{.greek-omitted} [αγωρασωσιν]{.greek-added} εαυτοις αρτους τι γαρ φαγωσιν ουκ [εχουσιν]{.greek-omitted} [εχουν]{.greek-added}[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν [διακοσιων]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} αρτους και [δωμεν]{.greek-omitted} [δωσωμεν]{.greek-added} [αυτοις]{.greek-omitted} [αυτους]{.greek-added} φαγειν[6:37]{.aside}

ο δε [λεγει]{.greek-omitted} [λεγοι]{.greek-added} α[υ]{.unclear}τοις ποσους αρτους εχετε υπαγετε και [ιδετε]{.greek-omitted} [ειδετε]{.greek-added} και γνοντες [λεγουσιν]{.greek-omitted} [πεντε]{.greek-omitted} [και]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted}[6:38]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ποσους]{.greek-omitted} [αρτους]{.greek-omitted} [εχετε]{.greek-omitted} [υπαγετε]{.greek-omitted} [και]{.greek-omitted} [ιδετε]{.greek-omitted} [και]{.greek-omitted} [γνοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38 | instance no. 2]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [περισσευματα]{.greek-added} κλασματων δωδεκα κοφινους [πληρεις]{.greek-omitted} [πληρης]{.greek-added} και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και [ευθεως]{.greek-omitted} [ηναγκασεν]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [εμβηναι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [και]{.greek-omitted} [προαγειν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} [προς]{.greek-omitted} [βηθσαιδαν]{.greek-omitted} [εως]{.greek-omitted} [αυτος]{.greek-omitted} [απολυση]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted}[6:45]{.aside}

[και]{.greek-omitted} ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} εως [αυτος]{.greek-omitted} [αυτο]{.greek-added} απολυση τον οχλον[6:45 | instance no. 2]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν [φαντασμα]{.greek-omitted} [ειναι]{.greek-omitted} [και]{.greek-omitted} [ανεκραξαν]{.greek-omitted}[6:49]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [περιπατουντα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [εδοξαν]{.greek-omitted} φαντασμα ειναι και ανεκραξαν[6:49 | instance no. 2]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις [αλλ]{.greek-added} ην [γαρ]{.greek-omitted} αυτων η καρδια πεπωρωμενη[6:52]{.aside}

και διαπερασαντες [ηλθον]{.greek-omitted} [απηλθον]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν [οπου]{.greek-omitted} [ηκουον]{.greek-omitted} [οτι]{.greek-omitted} [εκει]{.greek-omitted} [εστιν]{.greek-omitted}[6:55]{.aside}

[περιδραμοντες]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [περιχωρον]{.greek-omitted} [εκεινην]{.greek-omitted} [ηρξαντο]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [κραββατοις]{.greek-omitted} [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [περιφερειν]{.greek-omitted} οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55 | instance no. 2]{.aside}

και οπου [αν]{.greek-omitted} [εαν]{.greek-added} [εισεπορευετο]{.greek-omitted} [εισπορευετο]{.greek-added} εις κωμας η [εις]{.greek-added} πολεις η [εις]{.greek-added} αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας αρτους [εμεμψαντο]{.greek-omitted}[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη βαπτισωνται ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα [ε]{.greek-added} [εστιν]{.greek-omitted} [α]{.greek-omitted} [παρελαβον]{.greek-omitted} [κρατειν]{.greek-omitted} [βαπτισμους]{.greek-omitted} [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [χαλκιων]{.greek-omitted} [και]{.greek-omitted} [κλινων]{.greek-omitted}[7:4]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [αγορας]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [βαπτισωνται]{.greek-omitted} [ουκ]{.greek-omitted} [εσθιουσιν]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [πολλα]{.greek-omitted} [εστιν]{.greek-omitted} [στιν]{.greek-added} α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4 | instance no. 2]{.aside}

[επειτα]{.greek-omitted} [επιτα]{.greek-added} επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι [ου]{.greek-added} [περιπατουσιν]{.greek-added} οι μαθηται σου [ου]{.greek-omitted} [περιπατουσιν]{.greek-omitted} κατα την παραδοσιν των πρεσβυτερων αλλα ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως [προεφητευσεν]{.greek-omitted} [προεφυτευσεν]{.greek-added} ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χιλεσι]{.greek-added} με τιμα η δε καρδια [αυτων]{.greek-omitted} [αυτον]{.greek-added} πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και [ποτηριων]{.greek-omitted} [ποτηριον]{.greek-added} και αλλα παρομοια [τοιαυτα]{.greek-omitted} [πολλα]{.greek-omitted} [ποιειτε]{.greek-omitted}[7:8]{.aside}

[αφεντες]{.greek-omitted} [γαρ]{.greek-omitted} [την]{.greek-omitted} [εντολην]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [κρατειτε]{.greek-omitted} [την]{.greek-omitted} [παραδοσιν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [βαπτισμους]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [παρομοια]{.greek-omitted} τοιαυτα πολλα ποιειτε[7:8 | instance no. 2]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

[μωσης]{.greek-omitted} [μωησης]{.greek-added} γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} [αυτου]{.greek-omitted} η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

[τ]{.greek-added} [[τη]{.corr}]{.greek-added} [ακυρουντες]{.greek-omitted} [κυρουντες]{.greek-added} τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και [συνιετε]{.greek-omitted} [συνετε]{.greek-added}[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-omitted} [[ανου]{.greek-abbr}]{.greek-added} εισπορευομενον εις αυτον ο [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [εκπορευομενα]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [εκεινα]{.greek-omitted} [εστιν]{.greek-omitted} [τα]{.greek-omitted} [κοινουντα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[7:15]{.aside}

[ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [εξωθεν]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εισπορευομενον]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15 | instance no. 2]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

[εσωθεν]{.greek-omitted} [γαρ]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος [α]{.greek-added} [ασελγεια]{.greek-omitted} [οφθαλμος]{.greek-omitted} [πονηρος]{.greek-omitted} [βλασφημια]{.greek-omitted} [υπερηφανια]{.greek-omitted} [αφροσυνη]{.greek-omitted}[7:22]{.aside}

[κλοπαι]{.greek-omitted} [πλεονεξιαι]{.greek-omitted} [πονηριαι]{.greek-omitted} [δολος]{.greek-omitted} [ασελγεια]{.greek-omitted} [σελγειαι]{.greek-added} οφθαλμος πονηρος [βλασφημια]{.greek-omitted} [βλασφημιαι]{.greek-added} [υπερηφανια]{.greek-omitted} [υπεριφανια]{.greek-added} αφροσυνη[7:22 | instance no. 2]{.aside}

[ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα [μεθορια]{.greek-omitted} [μερη]{.greek-added} τυρου και σιδωνος και εισελθων εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ [η]{.greek-added} γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν [τοις]{.greek-omitted} [κυναριοις]{.greek-omitted}[7:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} [αφες]{.greek-omitted} [πρωτον]{.greek-omitted} [χορτασθηναι]{.greek-omitted} [τα]{.greek-omitted} [τεκνα]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [λαβειν]{.greek-omitted} [τον]{.greek-omitted} [αρτον]{.greek-omitted} [των]{.greek-omitted} [τεκνων]{.greek-omitted} [και]{.greek-omitted} [βαλειν]{.greek-omitted} τοις κυναριοις[7:27 | instance no. 2]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των [ψιχιων]{.greek-omitted} [ψυχιων]{.greek-added} των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον [εξεληλυθος]{.greek-omitted} [εξελυληθος]{.greek-added} και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη [αυτω]{.greek-omitted} [αυτων]{.greek-added} την χειρα[7:32]{.aside}

και απολαβομενος [αυ]{.greek-added} [αυτον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [οχλου]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [εβαλεν]{.greek-omitted} [τους]{.greek-omitted} [δακτυλους]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ωτα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [πτυσας]{.greek-omitted} [ηψατο]{.greek-omitted} [της]{.greek-omitted} [γλωσσης]{.greek-omitted} [αυτου]{.greek-omitted}[7:33]{.aside}

[και]{.greek-omitted} [απολαβομενος]{.greek-omitted} [αυτον]{.greek-omitted} [τον]{.greek-added} [απο]{.greek-omitted} [εκ]{.greek-added} του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33 | instance no. 2]{.aside}

και αναβλεψας εις τον ουρανον [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου [αι]{.greek-omitted} [ε]{.greek-added} ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει [ορθως]{.greek-omitted} [ορθος]{.greek-added}[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πε[π]{.unclear}οιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παμπολλου]{.greek-omitted} [παμπολου]{.greek-added} οχλου οντος και μη [εχον]{.greek-added} [εχοντων]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted}[8:1]{.aside}

[των]{.greek-added} [εν]{.greek-omitted} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [παμπολλου]{.greek-omitted} [οχλου]{.greek-omitted} [οντος]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [εχοντων]{.greek-omitted} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος ο [ιησους]{.greek-abbr} τους μαθητας αυτου λεγει αυτοις[8:1 | instance no. 2]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους [νηστεις]{.greek-omitted} [νιστις]{.greek-added} εις οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκασι]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις [ωδε]{.greek-omitted} χορτασαι αρτων επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους [εχετε]{.greek-omitted} αρτους [εχεται]{.greek-added} οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου [ινα]{.greek-omitted} [παραθωσιν]{.greek-omitted} [και]{.greek-omitted} [παρεθηκαν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted}[8:6]{.aside}

[και]{.greek-omitted} [παρηγγειλεν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [αναπεσειν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [επτα]{.greek-omitted} [αρτους]{.greek-omitted} [ευχαριστησας]{.greek-omitted} [εκλασεν]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} ινα [παραθωσιν]{.greek-omitted} [παρατιθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6 | instance no. 2]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [αυτα]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθειναι]{.greek-omitted} [παρατιθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως [τετρακισχιλιοι]{.greek-omitted} [τετρασκισχιλιοι]{.greek-added} και απελυσεν αυτους[8:9]{.aside}

και ευθεως εμβας εις το πλοιον μετα των μαθητων αυτου [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [μερη]{.greek-omitted} [δαλμανουθα]{.greek-omitted}[8:10]{.aside}

[και]{.greek-omitted} [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} οι φαρισαιοι και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και [αφεις]{.greek-omitted} [αφεντες]{.greek-added} αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου [μνημονευετε]{.greek-omitted} [μνημονεβετε]{.greek-added} [[μνημονεβεται]{.corr}]{.greek-added}[8:18]{.aside}

οτε τους πεντε αρτους [εκλασα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [πεντακισχιλιους]{.greek-omitted} [ποσους]{.greek-omitted} [κοφινους]{.greek-omitted} [πληρεις]{.greek-omitted} [κλασματων]{.greek-omitted} [ηρατε]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δωδεκα]{.greek-omitted}[8:19]{.aside}

[οτε]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} εκλασα εις [τους]{.greek-omitted} πεντακισχιλιους [και]{.greek-added} ποσους κοφινους [κλασματων]{.greek-added} πληρεις [κλασματων]{.greek-omitted} ηρατε λεγουσιν αυτω δωδεκα[8:19 | instance no. 2]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις [ουπω]{.greek-added} [πως]{.greek-omitted} [ου]{.greek-omitted} συνιετε[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βηθ[―]{.gap}σαιδα]{.greek-added} [[βηθσαιδα]{.corr}]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα [αυτου]{.greek-omitted} [αυτων]{.greek-added} αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα [ομματα]{.greek-omitted} [οματα]{.greek-added} αυτου επιθεις τας χειρας αυτω επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} [βλεπω]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [οτι]{.greek-omitted} [ως]{.greek-omitted} [δενδρα]{.greek-omitted} [ορω]{.greek-omitted} [περιπατουντας]{.greek-omitted}[8:24]{.aside}

[και]{.greek-omitted} [αναβλεψας]{.greek-omitted} [ελεγεν]{.greek-omitted} βλεπω τους [ανθρωπους]{.greek-abbr} [οτι]{.greek-omitted} ως δενδρα [ορω]{.greek-omitted} περιπατουντας[8:24 | instance no. 2]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και αποκατεσταθη και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμ[―]{.gap}ην [[κωμην]{.corr}]{.greek-added} εισελθης μηδε [ειπης]{.greek-omitted} [ειπεις]{.greek-added} τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου [λεγων]{.greek-omitted} [λεγον]{.greek-added} αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [οι]{.greek-added} [μεν]{.greek-added} ιωαννην τον βαπτιστην και αλλοι [ηλιαν]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [ενα]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted}[8:28]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [απεκριθησαν]{.greek-omitted} [ιωαννην]{.greek-omitted} [τον]{.greek-omitted} [βαπτιστην]{.greek-omitted} [και]{.greek-omitted} [αλλοι]{.greek-omitted} ηλιαν αλλοι δε ενα των προφητων[8:28 | instance no. 2]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι [και]{.greek-added} αποκριθεις [δε]{.greek-omitted} ο πετρος [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον υιον του ανθρωπου πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και [των]{.greek-omitted} αρχιερεων και των γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} και [προσλαβομενος]{.greek-omitted} [προσκαλεσαμενος]{.greek-added} αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε [οπισω]{.greek-omitted} [μου]{.greek-omitted} [σατανα]{.greek-omitted} [οτι]{.greek-omitted} [ου]{.greek-omitted} [φρονεις]{.greek-omitted} [τα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted}[8:33]{.aside}

[οπ[―]{.gap}ω]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [επιστραφεις]{.greek-omitted} [και]{.greek-omitted} [ιδων]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [επετιμησεν]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [λεγων]{.greek-omitted} [υπαγε]{.greek-omitted} [οπισω]{.corr} μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33 | instance no. 2]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου ουτος σωσει αυτην[8:35]{.aside}

τι γαρ [ωφελησει]{.greek-omitted} [ωφελη]{.greek-added} [ανθρωπον]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} εαν κερδηση τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ εαν [επαισχυνθη]{.greek-omitted} [επαισχηνθη]{.greek-added} με και τους εμους λογους εν τη γενεα ταυτη τη [μοιχαλιδι]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλω]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [επαισχυνθησεται]{.greek-omitted} [αυτον]{.greek-omitted} [οταν]{.greek-omitted} [ελθη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δοξη]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [αυτου]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted}[8:38]{.aside}

[ος]{.greek-omitted} [γαρ]{.greek-omitted} [εαν]{.greek-omitted} [επαισχυνθη]{.greek-omitted} [με]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [λογους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [γενεα]{.greek-omitted} [ταυτη]{.greek-omitted} [τη]{.greek-omitted} μοιχαλιδι και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} [επαισχυνθησεται]{.greek-omitted} [επεσχυνθησεται]{.greek-added} αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38 | instance no. 2]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη γευσωνται θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} [εληλυι]{.greek-added} [εληλυθυιαν]{.greek-omitted} [[εληλυθιαν]{.corr}]{.greek-added} εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και [τον]{.greek-added} [ιωαννην]{.greek-abbr} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν [αυτων]{.greek-omitted} [αυτον]{.greek-added}[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν ως χιων οια [γναφευς]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [λευκαναι]{.greek-omitted}[9:3]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτου]{.greek-omitted} [εγενοντο]{.greek-omitted} [στιλβοντα]{.greek-omitted} [λευκα]{.greek-omitted} [λιαν]{.greek-omitted} [ως]{.greek-omitted} [χιων]{.greek-omitted} [οια]{.greek-omitted} γναφευς επι της γης ου δυναται λευκαναι[9:3 | instance no. 2]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωσει]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου [ακουετε]{.greek-omitted} [ακουεται]{.greek-added}[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων [δε]{.greek-omitted} [δαι]{.greek-added} αυτων απο του ορους διεστειλατο αυτοις ινα [μηδενι]{.greek-omitted} [μηδε]{.greek-added} [διηγησωνται]{.greek-omitted} [α]{.greek-omitted} [ειδον]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [οταν]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} [αναστη]{.greek-omitted}[9:9]{.aside}

[νι]{.greek-added} [καταβαινοντων]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ορους]{.greek-omitted} [διεστειλατο]{.greek-omitted} [αυτοις]{.greek-omitted} [ινα]{.greek-omitted} [μηδενι]{.greek-omitted} διηγησωνται α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9 | instance no. 2]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και [επηρωτων]{.greek-omitted} [επηρωτον]{.greek-added} αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων [πρωτον]{.greek-omitted} [πρωτος]{.greek-added} αποκαθιστα παντα και πως γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις [συζητουντας]{.greek-omitted} [αυτοις]{.greek-omitted} [σι]{.greek-added} [συ]{.greek-added}[9:14]{.aside}

[και]{.greek-omitted} [ελθων]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [ειδεν]{.greek-omitted} [οχλον]{.greek-omitted} [πολυν]{.greek-omitted} [περι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [γραμματεις]{.greek-omitted} [συζητουντας]{.greek-omitted} [ζητουντας]{.greek-added} [[ζητουντας]{.corr}]{.greek-added} αυτοις[9:14 | instance no. 2]{.aside}

και ευθεως πας ο οχλος [ιδοντες]{.greek-added} [ιδων]{.greek-omitted} [αυτον]{.greek-omitted} [εξεθαμβηθη]{.greek-omitted} [και]{.greek-omitted} [προστρεχοντες]{.greek-omitted} ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς [αυτους]{.greek-omitted} [εαυτους]{.greek-added}[9:16]{.aside}

και αποκριθεις εις εκ του οχλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} διδασκαλε ηνεγκα τον υιον μου προς [σε]{.greek-omitted} [σαι]{.greek-added} εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι [υμων]{.greek-omitted} [προς]{.greek-added} [υμας]{.greek-added} φερετε αυτον προς [με]{.greek-omitted} [μαι]{.greek-added}[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και [ιδων]{.greek-omitted} [ιδον]{.greek-added} [αυτον]{.greek-omitted} [ευθεως]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [εσπαραξεν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [πεσων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [εκυλιετο]{.greek-omitted} [αφριζων]{.greek-omitted}[9:20]{.aside}

[και]{.greek-omitted} [ηνεγκαν]{.greek-omitted} [αυτον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ιδων]{.greek-omitted} αυτον ευθεως [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20 | instance no. 2]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις [υδατι]{.greek-added} [υδατα]{.corr} ινα [απολεση]{.greek-omitted} [απολεσει]{.greek-added} αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} βοηθει μου [τη]{.greek-omitted} [τει]{.greek-added} απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} [το]{.greek-omitted} [αλαλον]{.greek-omitted} [και]{.greek-omitted} [κωφον]{.greek-omitted} [εγω]{.greek-omitted} [σοι]{.greek-omitted} [επιτασσω]{.greek-omitted} [εξελθε]{.greek-omitted} [εξ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [μηκετι]{.greek-omitted} [εισελθης]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted}[9:25]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [επισυντρεχει]{.greek-omitted} [οχλος]{.greek-omitted} [επετιμησεν]{.greek-omitted} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [τω]{.greek-omitted} [ακαθαρτω]{.greek-omitted} [λεγων]{.greek-omitted} [αυτω]{.greek-omitted} το [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αλαλον]{.greek-omitted} [αλλαλον]{.greek-added} και κωφον εγω σοι επιτασσω [εξελθε]{.greek-omitted} εξ αυτου και μηκετι εισελθης εις αυτον[9:25 | instance no. 2]{.aside}

και κραξαν και πολλα σπαραξαν αυτον [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν οτι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και [εκειθεν]{.greek-omitted} [εκηθεν]{.greek-added} εξελθοντες [παρεπορευοντο]{.greek-omitted} [παρεπορεβοντο]{.greek-added} δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδιδοται]{.greek-omitted} [εις]{.greek-omitted} [χειρας]{.greek-omitted} [ανθρωπων]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [αποκτανθεις]{.greek-omitted} [τη]{.greek-omitted} [τριτη]{.greek-omitted} [ημερα]{.greek-omitted} [αναστησεται]{.greek-omitted}[9:31]{.aside}

[εδιδασκεν]{.greek-omitted} [γαρ]{.greek-omitted} [τους]{.greek-omitted} μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31 | instance no. 2]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα [τους]{.greek-added} [μαθητας]{.greek-added} [αυτους]{.greek-omitted} [αυτου]{.greek-added} τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εστω]{.greek-added} [εσται]{.greek-omitted} [παντων]{.greek-omitted} [εσχατος]{.greek-omitted} [και]{.greek-omitted} παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων [και]{.greek-omitted} [εναγκαλισαμενος]{.greek-omitted} [αυτο]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted}[9:36]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [παιδιον]{.greek-omitted} [εστησεν]{.greek-omitted} [αυτο]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [αυτων]{.greek-omitted} και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36 | instance no. 2]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος [εαν]{.greek-omitted} [αν]{.greek-added} εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε αυτω ιωαννης λεγων διδασκαλε ειδομεν τινα τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη κωλυετε αυτον [ουδεις]{.greek-omitted} [ου]{.greek-added} γαρ εστιν [ος]{.greek-omitted} [ποιησει]{.greek-omitted} [ο]{.greek-added} [ποιησας]{.greek-added} [ησει]{.greek-added} δυναμιν [επι]{.greek-omitted} [εν]{.greek-added} τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καθ υμων υπερ υμων εστιν[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι μου οτι [χριστου]{.greek-abbr} εστε [αμην]{.greek-omitted} [αμιν]{.greek-added} λεγω υμιν ου μη [απο]{.greek-added} [απολεση]{.greek-omitted} [τον]{.greek-omitted} [μισθον]{.greek-omitted} [αυτου]{.greek-omitted}[9:41]{.aside}

[λεση]{.greek-added} [ος]{.greek-omitted} [γαρ]{.greek-omitted} [αν]{.greek-omitted} [ποτιση]{.greek-omitted} [υμας]{.greek-omitted} [ποτηριον]{.greek-omitted} [υδατος]{.greek-omitted} [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [οτι]{.greek-omitted} [χριστου]{.greek-omitted} [εστε]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [απολεση]{.greek-omitted} τον μισθον αυτου[9:41 | instance no. 2]{.aside}

και ος εαν σκανδαλιση ενα των μικρων [τουτων]{.greek-added} των [πιστευοντων]{.greek-omitted} [πιστεβοντων]{.greek-added} εις εμε καλον εστιν αυτω μαλλον ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι εστιν κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [σοι]{.greek-added} εστιν [σοι]{.greek-omitted} [εισελθειν]{.greek-omitted} εις την ζωην [εισελθειν]{.greek-added} χωλον η [τους]{.greek-omitted} δυο ποδας εχοντα βληθηναι εις την γεενναν εις το [πυρ]{.greek-omitted} [το]{.greek-omitted} [ασβεστον]{.greek-omitted}[9:45]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [ο]{.greek-omitted} [πους]{.greek-omitted} [σου]{.greek-omitted} [σκανδαλιζη]{.greek-omitted} [σε]{.greek-omitted} [αποκοψον]{.greek-omitted} [αυτον]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [σοι]{.greek-omitted} [εισελθειν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ζωην]{.greek-omitted} [χωλον]{.greek-omitted} [η]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ποδας]{.greek-omitted} [εχοντα]{.greek-omitted} [βληθηναι]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γεενναν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} πυρ το ασβεστον[9:45 | instance no. 2]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκωλυξ]{.greek-added} [αυτων]{.greek-omitted} [αυτον]{.greek-added} ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο [οφθαλμος]{.greek-omitted} [οφθαλαμος]{.greek-added} σου σκανδαλιζη σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα [βληθηναι]{.greek-omitted} [βλυθηναι]{.greek-added} εις την γεενναν του πυρος[9:47]{.aside}

οπου [ο]{.greek-omitted} [σκωληξ]{.greek-omitted} [σκωλυξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια [αλι]{.greek-omitted} αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

[κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} αναστας ερχεται εις τα ορια της [ιουδαιας]{.greek-omitted} [ιουδαι]{.greek-added} [δια]{.greek-omitted} [του]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} [και]{.greek-omitted} [συμπορευονται]{.greek-omitted} [παλιν]{.greek-omitted} [οχλοι]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [ειωθει]{.greek-omitted} [παλιν]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [αυτους]{.greek-omitted}[10:1]{.aside}

[ας]{.greek-added} [κακειθεν]{.greek-omitted} [αναστας]{.greek-omitted} [ερχεται]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορια]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} [δια]{.greek-omitted} [του]{.greek-omitted} περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1 | instance no. 2]{.aside}

και προσελθοντες [η]{.greek-added} φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν [ενετειλατο]{.greek-omitted} [ενετειλατω]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [επετρεψεν]{.greek-omitted} [επετρεψαι]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν [υμιν]{.greek-omitted} την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ [εποι]{.greek-added} [εποιησεν]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted}[10:6]{.aside}

[ησεν]{.greek-added} [απο]{.greek-omitted} [δε]{.greek-omitted} [αρχης]{.greek-omitted} [κτισεως]{.greek-omitted} [αρσεν]{.greek-omitted} [και]{.greek-omitted} [θηλυ]{.greek-omitted} [εποιησεν]{.greek-omitted} αυτους ο [θεος]{.greek-abbr}[10:6 | instance no. 2]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται [περι]{.greek-added} αυτου [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [επυρωτησαν]{.greek-added} αυτον[10:10]{.aside}

και λεγει αυτοις ος [εαν]{.greek-omitted} [αν]{.greek-added} απολυση την γυναικα αυτου και γαμηση αλλην [μοιχατε]{.greek-added} [μοιχαται]{.corr} επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και [προσεφερον]{.greek-omitted} [προσεφεροον]{.greek-added} αυτω παιδια ινα αψηται αυτων οι δε [μαθηται]{.greek-omitted} [επετιμων]{.greek-omitted} [τοις]{.greek-omitted} [προσφερουσιν]{.greek-omitted}[10:13]{.aside}

[και]{.greek-omitted} [προσεφερον]{.greek-omitted} [αυτω]{.greek-omitted} [παιδια]{.greek-omitted} [ινα]{.greek-omitted} [αψηται]{.greek-omitted} [αυτων]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} μαθηται επετιμων τοις προσφερουσιν[10:13 | instance no. 2]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα ευλογει αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον [ουδεις]{.greek-omitted} [αγαθος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εις]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted}[10:18]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [τι]{.greek-omitted} [με]{.greek-omitted} [λεγεις]{.greek-omitted} [αγαθον]{.greek-omitted} ουδεις αγαθος ει [μη]{.greek-omitted} [μει]{.greek-added} εις ο [θεος]{.greek-abbr}[10:18 | instance no. 2]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης μη αποστερησης τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω εν [σοι]{.greek-omitted} [σε]{.greek-added} υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} και δευρο ακολουθει μοι αρας τον σταυρον[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ [εχων]{.greek-omitted} [εχον]{.greek-added} κτηματα πολλα[10:22]{.aside}

και [περιβλεψαμενος]{.greek-omitted} [περιβλεψασμενος]{.greek-added} ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται [εθαμβουντο]{.greek-omitted} [εθαβουντο]{.greek-added} επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστην]{.greek-added} τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον εστιν καμηλον δια [της]{.greek-omitted} [τρυμαλιας]{.greek-omitted} [τρυμμαλιας]{.greek-added} [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις [δυναται]{.greek-omitted} [δυνατε]{.greek-added} σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει [παρα]{.greek-omitted} [ανθρωποις]{.greek-omitted} [αδυνατον]{.greek-omitted} [αλλ]{.greek-omitted} [ου]{.greek-omitted} [παρα]{.greek-omitted} [θεω]{.greek-omitted} [παντα]{.greek-omitted} [γαρ]{.greek-omitted} [δυνατα]{.greek-omitted} [εστιν]{.greek-omitted} [παρα]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[10:27]{.aside}

[εμβλεψας]{.greek-omitted} [δε]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγει]{.greek-omitted} παρα [ανθρωποις]{.greek-abbr} [τουτο]{.greek-added} αδυνατον [εστιν]{.greek-added} αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27 | instance no. 2]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [[πατερας]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-abbr} [και]{.greek-added} [γυναικας]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω [συμβαινειν]{.greek-omitted} [συμβενειν]{.greek-added}[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γρααμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και [εμπε]{.greek-added} [εμπαιξουσιν]{.greek-omitted} [[εμπαιζουσιν]{.corr}]{.greek-added} αυτω και μαστιγωσουσιν αυτον και εμπτυσουσιν αυτω και αποκτενουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} και τη [τριτη]{.greek-omitted} [τρι]{.greek-added} [ημερα]{.greek-omitted} [αναστησεται]{.greek-omitted}[10:34]{.aside}

[και]{.greek-omitted} [εμπαιξουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} τη [τριτη]{.greek-omitted} ημερα [αναστησεται]{.greek-omitted} [αναστησετε]{.greek-added}[10:34 | instance no. 2]{.aside}

και προσπορευονται αυτω ιακωβος και [[ιω]{.greek-abbr}]{.greek-added} [ιωαννης]{.greek-omitted} [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν αιτησωμεν ποιησης ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε [πιειν]{.greek-omitted} [ποιειν]{.greek-added} το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον [μου]{.greek-added} [ο]{.greek-omitted} [εγω]{.greek-omitted} [πινω]{.greek-omitted} πιεσθε και το βαπτισμα [ο]{.greek-omitted} [εγω]{.greek-omitted} [βαπτιζομαι]{.greek-omitted} [βαπτισθησεσθε]{.greek-omitted}[10:39]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [δυναμεθα]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [το]{.greek-omitted} [μεν]{.greek-omitted} [ποτηριον]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [πινω]{.greek-omitted} [πιεσθε]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [βαπτισμα]{.greek-omitted} ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added}[10:39 | instance no. 2]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν [εμον]{.greek-omitted} [εμων]{.greek-added} δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-abbr}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριεβουσιν]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος [εαν]{.greek-omitted} [αν]{.greek-added} θελη [μεγας]{.greek-added} γενεσθαι [μεγας]{.greek-omitted} εν υμιν [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[10:43]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} θελη υμων γενεσθαι πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο υιος [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ουκ]{.greek-omitted} [ηλθεν]{.greek-omitted} [διακονηθηναι]{.greek-omitted} [αλλα]{.greek-omitted} [διακονησαι]{.greek-omitted} [και]{.greek-omitted} [δουναι]{.greek-omitted} [την]{.greek-omitted} [ψυχην]{.greek-omitted} [αυτου]{.greek-omitted} [λυτρον]{.greek-omitted} [αντι]{.greek-omitted} [πολλων]{.greek-omitted}[10:45]{.aside}

[και]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45 | instance no. 2]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν [ο]{.greek-omitted} υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον [φω]{.greek-added} [φωνηθηναι]{.greek-omitted} [και]{.greek-omitted} [φωνουσιν]{.greek-omitted} [τον]{.greek-omitted} [τυφλον]{.greek-omitted} [λεγοντες]{.greek-omitted} [αυτω]{.greek-omitted} [θαρσει]{.greek-omitted} [εγειραι]{.greek-omitted} [φωνει]{.greek-omitted} [σε]{.greek-omitted}[10:49]{.aside}

[νηθηναι]{.greek-added} και [στας]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτον]{.greek-omitted} [φωνηθηναι]{.greek-omitted} [και]{.greek-omitted} [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει εγειραι φωνει σε[10:49 | instance no. 2]{.aside}

ο δε [αποβολων]{.greek-added} [αποβαλων]{.corr} το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι [σοι]{.greek-added} θελεις ποιησω [σοι]{.greek-omitted} ο δε τυφλος ειπεν αυτω [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} [και]{.greek-added} [ηλθον]{.greek-added} εις βηθσφαγη και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την [κατεναντι]{.greek-omitted} [κατεναν]{.greek-added} [υμων]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [εισπορευομενοι]{.greek-omitted} [εις]{.greek-omitted} [αυτην]{.greek-omitted} [ευρησετε]{.greek-omitted} [πωλον]{.greek-omitted} [δεδεμενον]{.greek-omitted} [εφ]{.greek-omitted} [ον]{.greek-omitted} [ουδεις]{.greek-omitted} [ανθρωπων]{.greek-omitted} [κεκαθικεν]{.greek-omitted} [λυσαντες]{.greek-omitted} [αυτον]{.greek-omitted} [αγαγετε]{.greek-omitted}[11:2]{.aside}

[τι]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [κωμην]{.greek-omitted} [την]{.greek-omitted} [κατεναντι]{.greek-omitted} [υμων]{.greek-omitted} [ημων]{.greek-added} και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθικε]{.greek-added} λυσαντες αυτον αγαγετε[11:2 | instance no. 2]{.aside}

και εαν τις υμιν ειπη τι ποιειτε τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την [θυραν]{.greek-omitted} [θηραν]{.greek-added} εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

[και]{.greek-omitted} [κε]{.greek-added} τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και [επεβαλον]{.greek-omitted} [αυτω]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εκαθισεν]{.greek-omitted} [επ]{.greek-omitted} [επε]{.greek-added} [αυτω]{.greek-omitted}[11:7]{.aside}

[και]{.greek-omitted} [ηγαγον]{.greek-omitted} [τον]{.greek-omitted} [πωλον]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [και]{.greek-omitted} [επεβαλον]{.greek-omitted} [βαλον]{.greek-added} αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[11:7 | instance no. 2]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ των δενδρων και εστρωννυον εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

[και]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [παντα]{.greek-omitted} [οψιας]{.greek-omitted} [ηδη]{.greek-omitted} [ουσης]{.greek-omitted} [της]{.greek-omitted} [ωρας]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εις]{.greek-omitted} [βηθανιαν]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} δωδεκα[11:11]{.aside}

και [εισηλθεν]{.greek-omitted} [εισειλθεν]{.greek-added} εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης [της]{.greek-omitted} [ωρας]{.greek-omitted} εξηλθεν εις βηθανιαν μετα των [δωδεκα]{.greek-omitted}[11:11 | instance no. 2]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην μακροθεν [εχουσαν]{.greek-omitted} [εχουσα]{.greek-added} φυλλα ηλθεν ει αρα ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον [φαγοι]{.greek-omitted} [φαγη]{.greek-added} και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας [των]{.greek-omitted} [τον]{.greek-added} [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} και τας καθεδρας [των]{.greek-omitted} [πωλουντων]{.greek-omitted} [τας]{.greek-omitted} [περιστερας]{.greek-omitted} [κατεστρεψεν]{.greek-omitted}[11:15]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [εισελθων]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκβαλλειν]{.greek-omitted} [τους]{.greek-omitted} [πωλουντας]{.greek-omitted} [και]{.greek-omitted} [αγοραζοντας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [τραπεζας]{.greek-omitted} [των]{.greek-omitted} [κολλυβιστων]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [καθεδρας]{.greek-omitted} των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15 | instance no. 2]{.aside}

και [ουκ]{.greek-omitted} [ουουκ]{.greek-added} ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι γραμματεις και οι αρχιερεις και εζητουν πως αυτον [απολεσωσιν]{.greek-omitted} [απολεσουσιν]{.greek-added} εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη [διδαχη]{.greek-omitted} [διδαχοι]{.greek-added} αυτου[11:18]{.aside}

και οτε οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και [πρωι]{.greek-omitted} [προι]{.greek-added} παραπορευομενοι ειδον την [συκην]{.greek-omitted} [σηκην]{.greek-added} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και αναμνησθεις [ο]{.greek-omitted} [πετρος]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} [ιδε]{.greek-omitted} [η]{.greek-omitted} [συκη]{.greek-omitted} [ην]{.greek-omitted} [κατηρασω]{.greek-omitted} [εξηρανται]{.greek-omitted}[11:21]{.aside}

[και]{.greek-omitted} [αναμνησθεις]{.greek-omitted} ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηρανθη]{.greek-added}[11:21 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και [μη]{.greek-omitted} διακριθη εν τη καρδια αυτου [αλλα]{.greek-omitted} [ααλλα]{.greek-added} [πιστευση]{.greek-omitted} [πιστευει]{.greek-added} οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθαι]{.greek-added} [πιστευετε]{.greek-omitted} [πιστεβετε]{.greek-added} οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [υμων]{.greek-omitted}[11:25]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [στηκητε]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [αφιετε]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} [εχετε]{.greek-omitted} [κατα]{.greek-omitted} [τινος]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25 | instance no. 2]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται [παλιν]{.greek-omitted} [παλλιν]{.greek-added} εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι [αρχιερεις]{.greek-omitted} [αρχοιερεις]{.greek-added} και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και [τις]{.greek-omitted} [της]{.greek-added} σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα ποιης[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω υμιν εν [ποια]{.greek-omitted} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιω]{.greek-omitted}[11:29]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [επερωτησω]{.greek-omitted} [υμας]{.greek-omitted} [και]{.greek-omitted} [εγω]{.greek-omitted} [ενα]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [αποκριθητε]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [ερω]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} ποια εξουσια ταυτα ποιω[11:29 | instance no. 2]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ ουρανου ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον απαντες γαρ ειχον τον [ιωαννην]{.greek-abbr} οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν [υποληνιον]{.greek-omitted} [και]{.greek-omitted} [ωκοδομησεν]{.greek-omitted} [πυργον]{.greek-omitted} [και]{.greek-omitted} [εξεδοτο]{.greek-omitted} [αυτον]{.greek-omitted} [γεωργοις]{.greek-omitted} [και]{.greek-omitted} [απεδημησεν]{.greek-omitted}[12:1]{.aside}

[και]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [λεγειν]{.greek-omitted} [αμπελωνα]{.greek-omitted} [εφυτευσεν]{.greek-omitted} [ανθρωπος]{.greek-omitted} [και]{.greek-omitted} [περιεθηκεν]{.greek-omitted} [φραγμον]{.greek-omitted} [και]{.greek-omitted} [ωρυξεν]{.greek-omitted} υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1 | instance no. 2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων λαβη απο [του]{.greek-omitted} [καρπου]{.greek-omitted} [των]{.greek-added} [καρπων]{.greek-added} του αμπελωνος[12:2]{.aside}

[και]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον λιθοβολησαντες εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε [αποκτενοντες]{.greek-omitted} [απο]{.greek-added}[12:5]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-omitted} [αλλον]{.greek-omitted} [απεστειλεν]{.greek-omitted} [κακεινον]{.greek-omitted} [απεκτειναν]{.greek-omitted} [και]{.greek-omitted} [πολλους]{.greek-omitted} [αλλους]{.greek-omitted} [τους]{.greek-omitted} [μεν]{.greek-omitted} [δεροντες]{.greek-omitted} [τους]{.greek-omitted} [δε]{.greek-omitted} [αποκτενοντες]{.greek-omitted} [κτενοντες]{.greek-added}[12:5 | instance no. 2]{.aside}

ετι ουν ενα υιον [εχων]{.greek-omitted} [εχον]{.greek-added} αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον [εσχατον]{.greek-added} προς αυτους [εσχατον]{.greek-omitted} λεγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [ειπον]{.greek-omitted} [θεασαμενοι]{.greek-added} [αυτων]{.greek-added} [ερχομενον]{.greek-added} προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [ειπων]{.greek-added} οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και [εξεβαλον]{.greek-omitted} [εξευαλον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

[ου]{.greek-added} [ουδε]{.greek-omitted} [την]{.greek-omitted} [γραφην]{.greek-omitted} [ταυτην]{.greek-omitted} [ανεγνωτε]{.greek-omitted} [λιθον]{.greek-omitted} [ον]{.greek-omitted} [απεδοκιμασαν]{.greek-omitted} [οι]{.greek-omitted} [οικοδομουντες]{.greek-omitted} [ουτος]{.greek-omitted} [εγενηθη]{.greek-omitted} [εις]{.greek-omitted} [κεφαλην]{.greek-omitted} [γωνιας]{.greek-omitted}[12:10]{.aside}

[ουδε]{.greek-omitted} [δε]{.greek-added} την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[12:10 | instance no. 2]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν [γαρ]{.greek-omitted} οτι προς αυτους την παραβολην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις [προσωπον]{.greek-omitted} [προσω]{.greek-added} [ανθρωπων]{.greek-omitted} [αλλ]{.greek-omitted} [επ]{.greek-omitted} [αληθειας]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [διδασκεις]{.greek-omitted} [εξεστιν]{.greek-omitted} [κηνσον]{.greek-omitted} [καισαρι]{.greek-omitted} [δουναι]{.greek-omitted} [η]{.greek-omitted} [ου]{.greek-omitted}[12:14]{.aside}

[πον]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [ελθοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [οιδαμεν]{.greek-omitted} [οτι]{.greek-omitted} [αληθης]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [περι]{.greek-omitted} [ουδενος]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [βλεπεις]{.greek-omitted} [εις]{.greek-omitted} [προσωπον]{.greek-omitted} [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added} αλλ επ [αληθειας]{.greek-omitted} [αλληθειας]{.greek-added} την οδον του [θεου]{.greek-abbr} διδασκεις [ειπε]{.greek-added} [ουν]{.greek-added} [ημιν]{.greek-added} [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δομεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [ειδομεν]{.greek-added} [[δομεν]{.corr}]{.greek-added}[12:14 | instance no. 2]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι [δηναριον]{.greek-omitted} [δυναριον]{.greek-added} ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος [καισαρι]{.greek-omitted} [καισαροι]{.greek-added} και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν [ανα]{.greek-added} [αναστασιν]{.greek-omitted} [μη]{.greek-omitted} [ειναι]{.greek-omitted} [και]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγοντες]{.greek-omitted}[12:18]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [σαδδουκαιοι]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [οιτινες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αναστασιν]{.greek-omitted} [στασιν]{.greek-added} μη ειναι και επηρωτησαν [αυτον]{.greek-omitted} [αυτων]{.greek-added} λεγοντες[12:18 | instance no. 2]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [ουν]{.greek-added} αδελφοι ησαν και ο πρωτος ελαβεν γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκαι]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκαι]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα εσχατη παντων [απεθανεν]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted}[12:22]{.aside}

[και]{.greek-omitted} [ελαβον]{.greek-omitted} [αυτην]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [αφηκαν]{.greek-omitted} [σπερμα]{.greek-omitted} [εσχατη]{.greek-omitted} [παντων]{.greek-omitted} [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22 | instance no. 2]{.aside}

εν τη αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των [εκ]{.greek-added} [νερ]{.greek-added} [νεκρων]{.corr} οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεος]{.greek-added} επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν [ο]{.greek-omitted} [θεος]{.greek-omitted} [νεκρων]{.greek-omitted} [αλλα]{.greek-omitted} [θεος]{.greek-omitted} [ζωντων]{.greek-omitted} [υμεις]{.greek-omitted} [ουν]{.greek-omitted} [πολυ]{.greek-omitted} [πλανασθε]{.greek-omitted}[12:27]{.aside}

[ουκ]{.greek-omitted} [εστιν]{.greek-omitted} ο [θεος]{.greek-abbr} [[θεος]{.greek-abbr}]{.greek-added} [νεκρων]{.greek-omitted} [νεκρον]{.greek-added} αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ πλανασθε[12:27 | instance no. 2]{.aside}

και προσελθων εις των γραμματεων ακουσας αυτων συζητουντων ειδως οτι καλως [απεκριθη]{.greek-added} αυτοις [απεκριθη]{.greek-omitted} επηρωτησεν αυτον ποια [εντολη]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη παντων [εντολη]{.greek-omitted}[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω οτι πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολυ]{.greek-added} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον [πλη]{.greek-added} [πλησιον]{.greek-omitted} [σου]{.greek-omitted} [ως]{.greek-omitted} [σεαυτον]{.greek-omitted} [μειζων]{.greek-omitted} [τουτων]{.greek-omitted} [αλλη]{.greek-omitted} [εντολη]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted}[12:31]{.aside}

[σιον]{.greek-added} [και]{.greek-omitted} [δευτερα]{.greek-omitted} [ομοια]{.greek-omitted} [αυτη]{.greek-omitted} [αγαπησεις]{.greek-omitted} [τον]{.greek-omitted} [πλησιον]{.greek-omitted} σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} [μειζων]{.greek-omitted} [μειζον]{.greek-added} τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31 | instance no. 2]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ [αληθειας]{.greek-omitted} [αληθει]{.greek-added} ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της [συνεσεως]{.greek-omitted} [ψυχης]{.greek-added} και εξ ολης της [ψυχης]{.greek-omitted} [συνεσεως]{.greek-added} και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα [επερωτησαι]{.greek-added} αυτον [επερωτησαι]{.greek-omitted}[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω [ιερω]{.greek-omitted} [πως]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [υιος]{.greek-omitted} [εστιν]{.greek-omitted} [δαυιδ]{.greek-omitted}[12:35]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ελεγεν]{.greek-omitted} [διδασκων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος [[δαυιδ]{.greek-abbr}]{.greek-added} εστιν [δαυιδ]{.greek-omitted}[12:35 | instance no. 2]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} [λεγει]{.greek-omitted} [καλει]{.greek-added} αυτον [κυριον]{.greek-abbr} και ποθεν υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις [περιπατειν]{.greek-omitted} [περιπατην]{.greek-added} και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτωκλισιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των [χηρων]{.greek-omitted} [χειρων]{.greek-added} και προφασει μακρα προσευχομενοι ουτοι [ληψονται]{.greek-omitted} [ληψον]{.greek-added} περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} [πολλα]{.greek-omitted} [πωλλα]{.greek-added}[12:41]{.aside}

και ελθουσα μια χηρα [πτωχη]{.greek-omitted} [πτωχει]{.greek-added} [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [κοδραντης]{.greek-omitted} [κοδαντης]{.greek-added} [[κοδρντης]{.corr}]{.greek-added}[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ [εκ]{.greek-omitted} [του]{.greek-omitted} [περισσευοντος]{.greek-omitted} [αυτοις]{.greek-omitted} [εβαλον]{.greek-omitted} [αυτη]{.greek-omitted} [δε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [υστερησεως]{.greek-omitted} [αυτης]{.greek-omitted} [παντα]{.greek-omitted} [οσα]{.greek-omitted} [ειχεν]{.greek-omitted} [εβαλεν]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [βιον]{.greek-omitted} [αυτης]{.greek-omitted}[12:44]{.aside}

[παντες]{.greek-omitted} [γαρ]{.greek-omitted} εκ του [περισσευοντος]{.greek-omitted} [περισσευματος]{.greek-added} [αυτοις]{.greek-omitted} [αυτων]{.greek-added} εβαλον αυτη δε εκ της [υστερησεως]{.greek-omitted} [υστερισεως]{.greek-added} αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44 | instance no. 2]{.aside}

### Chapter 13

και εκπο[ρ]{.unclear}ευομενου αυτου εκ του ιερου λεγει αυτω εις [των]{.greek-omitted} [τον]{.greek-added} μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις [τ[―]{.gap}τας]{.greek-added} [ταυτας]{.corr} τας μεγαλας οικοδομας ου μη αφεθη λιθος επι λιθω ος ου μη καταλυθη[13:2]{.aside}

και [καθημενου]{.greek-omitted} [καμενου]{.greek-added} αυτου εις το ορος των [ελε]{.greek-added} [ελαιων]{.corr} κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης [και]{.greek-omitted} [ανδρεας]{.greek-omitted}[13:3]{.aside}

[και]{.greek-omitted} [καθημενου]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ορος]{.greek-omitted} [των]{.greek-omitted} [ελαιων]{.greek-omitted} [κατεναντι]{.greek-omitted} [του]{.greek-omitted} [ιερου]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [πετρος]{.greek-omitted} [και]{.greek-omitted} [ιακωβος]{.greek-omitted} [και]{.greek-omitted} [ιωαννης]{.greek-omitted} και ανδρεας[13:3 | instance no. 2]{.aside}

[ειπε]{.greek-omitted} [πε]{.greek-added} ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις [ειπεν]{.greek-added} αυτοις [ηρξατο]{.greek-omitted} [λεγειν]{.greek-omitted} βλεπετε μη τις υμας [πλανηση]{.greek-omitted} [απατησ[η]{.unclear}]{.greek-added}[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και [ταραχε]{.greek-added} [ταραχαι]{.corr} [αρχαι]{.greek-omitted} [αρχη]{.greek-added} ωδινων [ταυτα]{.greek-omitted}[13:8]{.aside}

[εγερθησεται]{.greek-omitted} [γαρ]{.greek-omitted} [εθνος]{.greek-omitted} [επι]{.greek-omitted} [εθνος]{.greek-omitted} [και]{.greek-omitted} [βασιλεια]{.greek-omitted} [επι]{.greek-omitted} [βασιλειαν]{.greek-omitted} [και]{.greek-omitted} [εσονται]{.greek-omitted} [σεισμοι]{.greek-omitted} [κατα]{.greek-omitted} [τοπους]{.greek-omitted} [και]{.greek-omitted} [εσονται]{.greek-omitted} [λιμοι]{.greek-omitted} [και]{.greek-omitted} [ταραχαι]{.greek-omitted} [αρχαι]{.greek-omitted} [ωδινων]{.greek-omitted} ταυτα[13:8 | instance no. 2]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις [συναγωγας]{.greek-omitted} [σειναγωγας]{.greek-added} δαρησεσθε και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον [κ[υ]{.unclear}ρυχθηναι]{.greek-added} [κηρυχθηναι]{.corr} το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [μεριμνατε]{.greek-added} τι [λαλησητε]{.greek-omitted} [λαλησεται]{.greek-added} μηδε μελετατε αλλ ο εαν δοθη υμιν [εν]{.greek-omitted} [εεν]{.greek-added} εκεινη τη ωρα τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

[παραδωσει]{.greek-omitted} [δε]{.greek-omitted} [αδελφος]{.greek-omitted} [αδελφον]{.greek-omitted} [εις]{.greek-omitted} [θανατον]{.greek-omitted} [και]{.greek-omitted} [πατηρ]{.greek-omitted} [τεκνον]{.greek-omitted} και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον [και]{.greek-omitted} [επαναστησονται]{.greek-omitted} [τεκνα]{.greek-omitted} [επι]{.greek-omitted} [γονεις]{.greek-omitted} [και]{.greek-omitted} [θανατωσουσιν]{.greek-omitted} [αυτους]{.greek-omitted}[13:12 | instance no. 2]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως [εν]{.greek-added} [τοπω]{.greek-added} οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις [το]{.greek-added} [τον]{.corr} αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν [γαστρι]{.greek-omitted} [εχουσαις]{.greek-omitted} [και]{.greek-omitted} [ταις]{.greek-omitted} [θηλαζουσαις]{.greek-omitted} [εν]{.greek-omitted} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted}[13:17]{.aside}

[ουαι]{.greek-omitted} [δε]{.greek-omitted} [ταις]{.greek-omitted} [εν]{.greek-omitted} γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17 | instance no. 2]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων [χειμωνος]{.greek-omitted} [χημωνος]{.greek-added} [μηδε]{.greek-added} [σαββατου]{.greek-added}[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added}[13:20]{.aside}

[και]{.greek-added} τοτε [εαν]{.greek-omitted} [αν]{.greek-added} τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} [η]{.greek-omitted} ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και [και]{.greek-added} ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και [τερατα]{.greek-omitted} [προς]{.greek-omitted} [το]{.greek-omitted} [αποπλαναν]{.greek-omitted} [ει]{.greek-omitted} [δυνατον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted}[13:22]{.aside}

[εγερθησονται]{.greek-omitted} [γαρ]{.greek-omitted} [ψευδοχριστοι]{.greek-omitted} [και]{.greek-omitted} [ψευδοπροφηται]{.greek-omitted} [και]{.greek-omitted} [δωσουσιν]{.greek-omitted} [σημεια]{.greek-omitted} [και]{.greek-omitted} τερατα προς το αποπλαναν ει δυνατον και τους [εκλεκτους]{.greek-omitted} [εκλετους]{.greek-added}[13:22 | instance no. 2]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα [δυναμεως]{.greek-omitted} [δυναμεος]{.greek-added} [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως [ακρου]{.greek-omitted} [ακροου]{.greek-added} [[ακρο]{.corr}]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

[α]{.greek-added} [απο]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [συκης]{.greek-omitted} [μαθετε]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [οταν]{.greek-omitted} [αυτης]{.greek-omitted} [ηδη]{.greek-omitted} [ο]{.greek-omitted} [κλαδος]{.greek-omitted} [απαλος]{.greek-omitted} [γενηται]{.greek-omitted} [και]{.greek-omitted} [εκφυη]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [γινωσκετε]{.greek-omitted} [οτι]{.greek-omitted} [εγγυς]{.greek-omitted} [το]{.greek-omitted} [θερος]{.greek-omitted} [εστιν]{.greek-omitted}[13:28]{.aside}

[απο]{.greek-omitted} [πο]{.greek-added} δε της συκης μαθετε την παραβολην οταν αυτης [ηδη]{.greek-omitted} ο κλαδος [γενηται]{.greek-added} απαλος [γενηται]{.greek-omitted} και εκφυη τα φυλλα [γινωσκετε]{.greek-omitted} [γινωσσκετε]{.greek-added} οτι εγγυς το θερος εστιν[13:28 | instance no. 2]{.aside}

ουτως και υμεις οταν ταυτα ιδητε [γινομενα]{.greek-omitted} [γινομαινα]{.greek-added} γινωσκετε οτι εγγυς εστιν [επι]{.greek-omitted} [εεπι]{.greek-added} θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσαιται]{.greek-added} οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[13:31]{.aside}

περι δε της ημερας εκεινης η [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι οι εν [τω]{.greek-added} [ουρανω]{.greek-abbr} ουδε ο υιος ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο [καιρος]{.greek-omitted} [εστιν]{.greek-omitted}[13:33]{.aside}

[βλεπετε]{.greek-omitted} [αγρυπνειτε]{.greek-omitted} [και]{.greek-omitted} [προσευχεσθε]{.greek-omitted} [ουκ]{.greek-omitted} [οιδατε]{.greek-omitted} [γαρ]{.greek-omitted} [ποτε]{.greek-omitted} [ο]{.greek-omitted} καιρος εστιν[13:33 | instance no. 2]{.aside}

ως [ανθρωπος]{.greek-abbr} [αποδημος]{.greek-omitted} [αποδημων]{.greek-added} [αφεις]{.greek-omitted} [αφιεις]{.greek-added} την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη υμας [καθευδοντας]{.greek-omitted} [καθευδωντας]{.greek-added}[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω κρατησαντες [αποκτεινωσιν]{.greek-omitted} [αποκτεινουσιν]{.greek-added}[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

[και]{.greek-omitted} [οντος]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} βηθανια εν τη οικια σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη [εχου]{.greek-added} [εχουσα]{.corr} αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3 | instance no. 2]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε [αυ]{.greek-added} [αυτους]{.greek-omitted} [ευ]{.greek-omitted} [ποιησαι]{.greek-omitted} [εμε]{.greek-omitted} [δε]{.greek-omitted} [ου]{.greek-omitted} [παντοτε]{.greek-omitted} [εχετε]{.greek-omitted}[14:7]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} [τους]{.greek-omitted} [τοις]{.greek-added} [πτωχους]{.greek-omitted} [εχετε]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [και]{.greek-omitted} [οταν]{.greek-omitted} [θελητε]{.greek-omitted} [δυνασθε]{.greek-omitted} [αυτους]{.greek-omitted} ευ ποιησαι εμε δε ου παντοτε εχετε[14:7 | instance no. 2]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιη[σ]{.unclear}εν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν [και]{.greek-omitted} [αι]{.greek-added} [επηγγειλαντο]{.greek-omitted} [επηγγηλαντο]{.greek-added} αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον [λεγουσιν]{.greek-omitted} [λεγου]{.greek-added} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [που]{.greek-omitted} [θελεις]{.greek-omitted} [απελθοντες]{.greek-omitted} [ετοιμασωμεν]{.greek-omitted} [ινα]{.greek-omitted} [φαγης]{.greek-omitted} [το]{.greek-omitted} [πασχα]{.greek-omitted}[14:12]{.aside}

[σιν]{.greek-added} [και]{.greek-omitted} [τη]{.greek-omitted} [πρωτη]{.greek-omitted} [ημερα]{.greek-omitted} [των]{.greek-omitted} [αζυμων]{.greek-omitted} [οτε]{.greek-omitted} [το]{.greek-omitted} [πασχα]{.greek-omitted} [εθυον]{.greek-omitted} [λεγουσιν]{.greek-omitted} αυτω οι μαθηται αυτου που θελεις απελθοντες [ετοιμασωμεν]{.greek-omitted} [ετοιμασομεν]{.greek-added} ινα φαγης το πασχα[14:12 | instance no. 2]{.aside}

και αποστελλει δυο [των]{.greek-omitted} [τον]{.greek-added} μαθητων αυτου και λεγει αυτοις [υπαγετε]{.greek-omitted} [παγετε]{.greek-added} εις την πολιν και [απαντησει]{.greek-omitted} [αυπαντησει]{.greek-added} υμιν [ανθρωπος]{.greek-abbr} [κεραμιον]{.greek-omitted} [καιραμιον]{.greek-added} υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα [τον]{.greek-added} [των]{.corr} μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει [ανωγεον]{.greek-omitted} [ανογειων]{.greek-added} μεγα [εστρωμενον]{.greek-omitted} [εστρωμμενον]{.greek-added} ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται [αυτου]{.greek-omitted} και ηλθον εις την πολιν και ευρον καθως [ειπεν]{.greek-omitted} [ενετειλατο]{.greek-added} αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης [ερχετε]{.greek-added} [ερχεται]{.corr} [μετα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted}[14:17]{.aside}

[και]{.greek-omitted} [οψιας]{.greek-omitted} [γενομενης]{.greek-omitted} [ερχεται]{.greek-omitted} μετα των δωδεκα[14:17 | instance no. 2]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου εις το [τρυτρυβλιον]{.greek-added} [τρυβλιον]{.corr}[14:20]{.aside}

ο μεν [ουν]{.greek-added} [ο]{.greek-added} υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων [λαβων]{.greek-omitted} [λαβον]{.greek-added} ο [ιησους]{.greek-abbr} [αρτον]{.greek-omitted} [αρτων]{.greek-added} ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} σωμα μου[14:22]{.aside}

και λαβων το ποτηριον [ε]{.unclear}υχαριστησας [ε]{.unclear}δωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οτι ουκετι ου μη πιω εκ του [γενηματος]{.greek-omitted} [γεννηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες [σκανδα]{.greek-added} [σκανδαλισθησονται]{.greek-omitted} [αλλ]{.greek-omitted} [ουκ]{.greek-omitted} [εγω]{.greek-omitted}[14:29]{.aside}

[λισθησεσται]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} [εφη]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [παντες]{.greek-omitted} [σκανδαλισθησονται]{.greek-omitted} αλλ ουκ [εγω]{.greek-omitted} [αιγω]{.greek-added}[14:29 | instance no. 2]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} ταυτη πριν η [δις]{.greek-omitted} [δ[υ]{.unclear}ς]{.greek-added} [αλεκτορα]{.greek-omitted} [αλεκτορ]{.greek-added} φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} [απαρνηση]{.greek-omitted} [απαρνησοι]{.greek-added} [με]{.greek-omitted} [μαι]{.greek-added}[14:30]{.aside}

ο δε [πετρος]{.greek-added} [εκπερισσου]{.greek-omitted} [εκπερισου]{.greek-added} ελεγεν [μαλλον]{.greek-omitted} εαν [με]{.greek-omitted} δεη [συναποθανειν]{.greek-omitted} [μαι]{.greek-added} [συν]{.greek-added} σοι [αποθανειν]{.greek-added} ου μη [σε]{.greek-omitted} [σοι]{.greek-added} απαρνησωμαι [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added} δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και [παραλαμα]{.greek-added} [παραλαμβανει]{.corr} τον πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης [και]{.greek-omitted} [προσηυχετο]{.greek-omitted} [ινα]{.greek-omitted} [ει]{.greek-omitted} [δυνατον]{.greek-omitted} [εστιν]{.greek-omitted} [παρελθη]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted}[14:35]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [μικρον]{.greek-omitted} [επεσεν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35 | instance no. 2]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι [παρενεγκε]{.greek-omitted} [παρενεγκαι]{.greek-added} το ποτηριον απ εμου τουτο αλλ ου τι εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [ει]{.greek-added} τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον [ειπων]{.greek-omitted} [ειπον]{.greek-added}[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι [αυτων]{.greek-omitted} [αυτον]{.greek-added} βεβαρημενοι [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδεισαν]{.greek-omitted} [τι]{.greek-omitted} [αυτω]{.greek-omitted} [αποκριθωσιν]{.greek-omitted}[14:40]{.aside}

[και]{.greek-omitted} [υποστρεψας]{.greek-omitted} [ευρεν]{.greek-omitted} [αυτους]{.greek-omitted} [παλιν]{.greek-omitted} [καθευδοντας]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [οφθαλμοι]{.greek-omitted} [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} και ουκ [ηδεισαν]{.greek-omitted} [ηδεισαντο]{.greek-added} τι αυτω [αποκριθωσιν]{.greek-omitted} [αποκριθωσι]{.greek-added}[14:40 | instance no. 2]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added}[14:42]{.aside}

και [ευθεως]{.greek-omitted} [ευθεος]{.greek-added} ετι αυτου λαλουντος [παραγινεται]{.greek-omitted} [παραγινενεται]{.greek-added} ιουδας εις [ων]{.greek-omitted} [ω]{.greek-added} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και των γραμματεων και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} [κρα]{.greek-added} [κρατησατε]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [απαγαγετε]{.greek-omitted} [ασφαλως]{.greek-omitted}[14:44]{.aside}

[δεδωκει]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [παραδιδους]{.greek-omitted} [αυτον]{.greek-omitted} [συσσημον]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} [ον]{.greek-omitted} [αν]{.greek-omitted} [φιλησω]{.greek-omitted} [αυτος]{.greek-omitted} [εστιν]{.greek-omitted} [κρατησατε]{.greek-omitted} [τησατε]{.greek-added} αυτον και απαγαγετε ασφαλως[14:44 | instance no. 2]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των [παρεστηκοτων]{.greek-omitted} [παρεστηκωτων]{.greek-added} σπασαμενος [την]{.greek-omitted} [μαχε]{.greek-added} [μαχαιραν]{.corr} [επαισεν]{.greek-omitted} [επεσεν]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου [το]{.greek-omitted} [τω]{.greek-added} ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε [μ[η]{.unclear}]{.greek-added} [μ[ε]{.unclear}τα]{.corr} μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν [ημην]{.greek-omitted} [ημιν]{.greek-added} προς υμας εν τω ιερω διδασκων και ουκ [εκρατησατε]{.greek-omitted} [αικρατησατε]{.greek-added} με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον [εφυ]{.greek-added} [παντες]{.greek-omitted} [εφυγον]{.greek-omitted}[14:50]{.aside}

[γον]{.greek-added} [και]{.greek-omitted} [αφεντες]{.greek-omitted} [αυτον]{.greek-omitted} παντες [εφυγον]{.greek-omitted}[14:50 | instance no. 2]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος [σινδονα]{.greek-omitted} [σινδον]{.greek-added} επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα [των]{.greek-omitted} [τον]{.greek-added} υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ [εψευδομαρτυρουν]{.greek-omitted} [εψευδομαρ]{.greek-added} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ισαι]{.greek-omitted} [αι]{.greek-omitted} [μαρτυριαι]{.greek-omitted} [ουκ]{.greek-omitted} [ησαν]{.greek-omitted}[14:56]{.aside}

[τυρουν]{.greek-added} [πολλοι]{.greek-omitted} [γαρ]{.greek-omitted} [εψευδομαρτυρουν]{.greek-omitted} κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56 | instance no. 2]{.aside}

και τινες ανασταντες [εψευδομαρτυρουν]{.greek-omitted} [ευψευδομαρτυρουν]{.greek-added} κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω [τον]{.greek-omitted} [το]{.greek-added} ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον [αχειροποιητον]{.greek-omitted} [αχειροποι]{.greek-added} [οικοδομησω]{.greek-omitted} [ηκοδομησω]{.greek-added}[14:58]{.aside}

και ουδε [ουτως]{.greek-omitted} [ουτος]{.greek-added} ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει [αυτω]{.greek-omitted} [αυτον]{.greek-added} συ ει ο [χριστος]{.greek-abbr} ο υιος του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [και]{.greek-omitted} [ερχομενον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [νεφελων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[14:62]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [και]{.greek-omitted} [οψεσθε]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [καθημενον]{.greek-omitted} της δυναμεως και ερχομενον [μετα]{.greek-omitted} [επι]{.greek-added} των νεφελων του [ουρανου]{.greek-abbr}[14:62 | instance no. 2]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν [φαινεται]{.greek-omitted} [φενεται]{.greek-added} οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι [υπηρεται]{.greek-omitted} [υπειρεται]{.greek-added} ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του [αρχιερεως]{.greek-omitted} [αρχειερεως]{.greek-added}[14:66]{.aside}

και ιδουσα τον πετρον [θερμαινομενον]{.greek-omitted} [θερμενομενον]{.greek-added} [εμβεψασα]{.greek-added} [εμβλεψασα]{.corr} αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-omitted} [ησθα]{.greek-omitted}[14:67]{.aside}

[και]{.greek-omitted} [ιδουσα]{.greek-omitted} [τον]{.greek-omitted} [πετρον]{.greek-omitted} [θερμαινομενον]{.greek-omitted} [εμβλεψασα]{.greek-omitted} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} [και]{.greek-omitted} [συ]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [ναζαρηνου]{.greek-omitted} [ιησου]{.greek-abbr} ησθα[14:67 | instance no. 2]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε επισταμαι τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι [και]{.greek-added} ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον [παλιν]{.greek-omitted} [παλλιν]{.greek-added} οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η [λαλια]{.greek-omitted} [λαληα]{.greek-added} σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και [ανεμνησθη]{.greek-omitted} [εμνησθη]{.greek-added} ο πετρος [το[υ]{.unclear}]{.greek-added} [το]{.corr} ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις [α]{.greek-added} [απαρνηση]{.greek-omitted} [με]{.greek-omitted} [τρις]{.greek-omitted} [και]{.greek-omitted} [επιβαλων]{.greek-omitted} [εκλαιεν]{.greek-omitted}[14:72]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [δευτερου]{.greek-omitted} [αλεκτωρ]{.greek-omitted} [εφωνησεν]{.greek-omitted} [και]{.greek-omitted} [ανεμνησθη]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [το]{.greek-omitted} [ρημα]{.greek-omitted} [ο]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [πριν]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} [δις]{.greek-omitted} [απαρνηση]{.greek-omitted} [παρνηση]{.greek-added} με τρις και επιβαλων [εκλαιεν]{.greek-omitted} [εκλαιε]{.greek-added}[14:72 | instance no. 2]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε [εορτην]{.greek-omitted} [εωρτην]{.greek-added} απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει [αυτων]{.greek-added} φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον [βατ]{.greek-added} [βασιλεα]{.corr} των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον παραδεδωκεισαν αυτον [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted}[15:10]{.aside}

οι [δε]{.corr} αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν σταυρωσον αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν [οι]{.greek-omitted} [ο]{.greek-added} δε περισσοτερως εκραξαν σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγελωσας]{.greek-added} ινα σταυρωθη[15:15]{.aside}

οι δε στρατιωται απηγαγον [αυτον]{.greek-omitted} [εσω]{.greek-omitted} [της]{.greek-omitted} [αυλης]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [πραιτωριον]{.greek-omitted} [και]{.greek-omitted} [συγκαλουσιν]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [σπειραν]{.greek-omitted}[15:16]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [στρατιωται]{.greek-omitted} [απηγαγον]{.greek-omitted} αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16 | instance no. 2]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [βασιλευ]{.greek-added} των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενε[―]{.gap}πτυον [[ενεπτυον]{.corr}]{.greek-added} αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα [ι]{.greek-added} [ιδια]{.greek-omitted} [και]{.greek-omitted} [εξαγουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [σταυρωσωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[15:20]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ενεπαιξαν]{.greek-omitted} [αυτω]{.greek-omitted} [εξεδυσαν]{.greek-omitted} [αυτον]{.greek-omitted} [την]{.greek-omitted} [πορφυραν]{.greek-omitted} [και]{.greek-omitted} [ενεδυσαν]{.greek-omitted} [αυτον]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [[ματ]{.unclear}ια]{.greek-added} [τα]{.greek-omitted} [ιδια]{.corr} και εξαγουσιν αυτον ινα σταυρωσωσιν αυτον[15:20 | instance no. 2]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου [βαλλοντες]{.greek-omitted} [κληρον]{.greek-omitted} [επ]{.greek-omitted} [αυτα]{.greek-omitted} τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου [επιγε]{.greek-added} [επιγεγραμμενη]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted}[15:26]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [η]{.greek-omitted} [επιγραφη]{.greek-omitted} [της]{.greek-omitted} [αιτιας]{.greek-omitted} [αυτου]{.greek-omitted} [επιγεγραμμενη]{.greek-omitted} [γραμμενη]{.greek-added} ο βασιλευς των [ιουδαιων]{.greek-omitted} [ιδυδαιων]{.greek-added}[15:26 | instance no. 2]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [σταυρουσι]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων [αυτου]{.greek-omitted}[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο [του]{.greek-omitted} [σταυρου]{.greek-omitted} [ινα]{.greek-omitted} [ιδωμεν]{.greek-omitted} [και]{.greek-omitted} [πιστευσωμεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [συνεσταυρωμενοι]{.greek-omitted} [αυτω]{.greek-omitted} [ωνειδιζον]{.greek-omitted} [αυτον]{.greek-omitted}[15:32]{.aside}

[ο]{.greek-omitted} [χριστος]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [του]{.greek-omitted} [ισραηλ]{.greek-omitted} [καταβατω]{.greek-omitted} [νυν]{.greek-omitted} [απο]{.greek-omitted} του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν αυτω και οι συνεσταυρωμενοι αυτω ωνειδιζον αυτον[15:32 | instance no. 2]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη ωρα τη [ενατη]{.greek-omitted} [εννατη]{.greek-added} [εβοησεν]{.greek-omitted} [εβοησε]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} φωνη μεγαλη λεγων ελωι ελωι λιμα σαβαχθανι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου [εις]{.greek-omitted} [ινα]{.greek-added} τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε [ιδωμεν]{.greek-omitted} [ει]{.greek-omitted} [ερχεται]{.greek-omitted} [ηλιας]{.greek-omitted} [καθελειν]{.greek-omitted} [αυτον]{.greek-omitted}[15:36]{.aside}

[δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γεμισας]{.greek-omitted} [σπογγον]{.greek-omitted} [οξους]{.greek-omitted} [περιθεις]{.greek-omitted} [τε]{.greek-omitted} [καλαμω]{.greek-omitted} [εποτιζεν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο [κεντυριων]{.greek-omitted} [κεντυριον]{.greek-added} ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος υιος ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια η [του]{.greek-omitted} [ιακωβου]{.greek-omitted} [του]{.greek-omitted} [μικρου]{.greek-omitted} [και]{.greek-omitted} [ιωση]{.greek-omitted} [μητηρ]{.greek-omitted} [και]{.greek-omitted} [σαλωμη]{.greek-omitted}[15:40]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [γυναικες]{.greek-omitted} [απο]{.greek-omitted} [μακροθεν]{.greek-omitted} [θεωρουσαι]{.greek-omitted} [εν]{.greek-omitted} [αις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40 | instance no. 2]{.aside}

αι και οτε ην εν τη [γ]{.unclear}αλιλαια ηκολουθουν αυτω και διηκονουν αυτω [και]{.greek-omitted} [αλλαι]{.greek-omitted} [πολλαι]{.greek-omitted} [αι]{.greek-omitted} [συναναβασαι]{.greek-omitted} [αυτω]{.greek-omitted} εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο [αριμαθαιας]{.greek-omitted} [αριματθαιας]{.greek-added} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα [του]{.greek-omitted} [ιησου]{.greek-omitted}[15:43]{.aside}

[ηλθεν]{.greek-omitted} [ιωσηφ]{.greek-omitted} [ο]{.greek-omitted} [απο]{.greek-omitted} [αριμαθαιας]{.greek-omitted} [ευσχημων]{.greek-omitted} [βουλευτης]{.greek-omitted} [ος]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ην]{.greek-omitted} [προσδεχομενος]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τολμησας]{.greek-omitted} [εισηλθεν]{.greek-omitted} [προς]{.greek-omitted} [πιλατον]{.greek-omitted} [και]{.greek-omitted} [ητησατο]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} του [ιησου]{.greek-abbr}[15:43 | instance no. 2]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισσε]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην [λελατομημενον]{.greek-omitted} [λελατωμημενον]{.greek-added} εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν [που]{.greek-omitted} [τιθεται]{.greek-omitted}[15:47]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [ιωση]{.greek-omitted} [εθεωρουν]{.greek-omitted} που τιθεται[15:47 | instance no. 2]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια [η]{.greek-added} [του]{.greek-added} ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι [εις]{.greek-omitted} [το]{.greek-omitted} [μνημειον]{.greek-omitted} [ειδον]{.greek-omitted} [νεανισκον]{.greek-omitted} [καθημενον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [δεξιοις]{.greek-omitted} [περιβεβλημενον]{.greek-omitted} [στολην]{.greek-omitted} [λευκην]{.greek-omitted} [και]{.greek-omitted} [εξεθαμβηθησαν]{.greek-omitted}[16:5]{.aside}

[και]{.greek-omitted} [εισελθουσαι]{.greek-omitted} εις το μνημειον ειδον νεανισκον [καθημενον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [δεξιοις]{.greek-omitted} [περιβεβλημενον]{.greek-omitted} [στολην]{.greek-omitted} [λευκην]{.greek-omitted} [και]{.greek-omitted} [εξεθαμβηθησαν]{.greek-omitted}[16:5 | instance no. 2]{.aside}

[και]{.greek-omitted} [εισελθουσαι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [μνημειον]{.greek-omitted} [ειδον]{.greek-omitted} [νεανισκον]{.greek-omitted} καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και [ξεθαμβηθησαν]{.greek-added} [εξεθαμβηθησαν]{.corr}[16:5 | instance no. 3]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον εσταυρωμενον ηγερθη ουκ εστιν ωδε ιδε ο [αμ[νε]{.unclear}ς]{.greek-added} τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [δε]{.greek-omitted} [αυτας]{.greek-omitted} [τρομος]{.greek-omitted} [και]{.greek-omitted} [εκστασις]{.greek-omitted} [και]{.greek-omitted} [ουδενι]{.greek-omitted} [ουδεν]{.greek-omitted} [ειπον]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted}[16:8]{.aside}

[και]{.greek-omitted} [εξελθουσαι]{.greek-omitted} [εφυγον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [μνημειου]{.greek-omitted} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8 | instance no. 2]{.aside}

αναστας δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις [αγρον]{.greek-omitted} [α]{.greek-added}[16:12]{.aside}

[μετα]{.greek-omitted} [δε]{.greek-omitted} [ταυτα]{.greek-omitted} [δυσιν]{.greek-omitted} [εξ]{.greek-omitted} [αυτων]{.greek-omitted} [περιπατουσιν]{.greek-omitted} [εφανερωθη]{.greek-omitted} [εν]{.greek-omitted} [ετερα]{.greek-omitted} [μορφη]{.greek-omitted} [πορευομενοις]{.greek-omitted} [εις]{.greek-omitted} [αγρον]{.greek-omitted} [γρον]{.greek-added}[16:12 | instance no. 2]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον [εκ]{.greek-added} [νεκρων]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα [παρα]{.greek-added} [παρακολουθησει]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [δαιμονια]{.greek-omitted} [εκβαλουσιν]{.greek-omitted} [γλωσσαις]{.greek-omitted} [λαλησουσιν]{.greek-omitted} [καιναις]{.greek-omitted}[16:17]{.aside}

[σημεια]{.greek-omitted} [δε]{.greek-omitted} [τοις]{.greek-omitted} [πιστευσασιν]{.greek-omitted} [ταυτα]{.greek-omitted} [παρακολουθησει]{.greek-omitted} [κολουθησει]{.greek-added} εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17 | instance no. 2]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθυσουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των [επακολουθουντων]{.greek-omitted} [επακολοθουντων]{.greek-added} σημειων αμην[16:20]{.aside}

