---
title: "Collation of Byz^RP^ vs 30365 (365)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 365 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30365).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 365                                   	| λογος                              	|
| 365 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 365 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 365               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 365                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 365 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 365                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

τον μεν πρωτον λογον εποιησαμην περι παντων ω θεοφιλε ων ηρξατο ο [ιησους]{.greek-abbr} ποιειν τε και διδασκειν[1:1]{.aside}

αχρι ης ημερας εντειλαμενος τοις αποστολοις δια [πνευματος]{.greek-abbr} αγιου ους εξελεξατο ανεληφθη[1:2]{.aside}

οις και παρεστησεν εαυτον ζωντα μετα το παθειν [αυτον]{.greek-omitted} εν πολλοις τεκμηριοις δι ημερων τεσσαρακοντα οπτανομενος αυτοις και λεγων τα περι της βασιλειας του [θεου]{.greek-abbr}[1:3]{.aside}

και [συ]{.greek-added} [συναλιζομενος]{.greek-omitted} [παρηγγειλεν]{.greek-omitted} [αυτοις]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [μη]{.greek-omitted} [χωριζεσθαι]{.greek-omitted} [αλλα]{.greek-omitted} [περιμενειν]{.greek-omitted} [την]{.greek-omitted} [επαγγελιαν]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [ην]{.greek-omitted} [ηκουσατε]{.greek-omitted} [μου]{.greek-omitted}[1:4]{.aside}

[και]{.greek-omitted} [συναλιζομενος]{.greek-omitted} [ναλιζομενος]{.greek-added} παρηγγειλεν αυτοις απο ιεροσολυμων μη χωριζεσθαι αλλα περιμενειν την [επαγγελιαν]{.greek-omitted} [επαγγελειαν]{.greek-added} του [πατρος]{.greek-abbr} ην ηκουσατε μου[1:4 | instance no. 2]{.aside}

οτι ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω ου μετα πολλας ταυτας ημερας[1:5]{.aside}

οι μεν ουν συνελθοντες επηρωτων αυτον λεγοντες [κυριε]{.greek-abbr} ει εν τω χρονω τουτω [αποκαθιστανεις]{.greek-omitted} [αποκαθιστανης]{.greek-added} την βασιλειαν [τω]{.greek-omitted} [του]{.greek-added} [ισραηλ]{.greek-abbr}[1:6]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτους [ουχ]{.greek-supplied} [υ]{.greek-supplied}μων [εστιν]{.greek-omitted} [εστι]{.greek-added} γνωναι χρ[ο]{.unclear}νους η καιρους ους ο [πατηρ]{.greek-abbr} [εθε]{.greek-supplied}το ε[ν]{.unclear} τη ιδια εξουσια[1:7]{.aside}

αλλα ληψεσθε δυν[αμιν]{.greek-supplied} επελθοντος του αγιου [πνευματος]{.greek-abbr} εφ υμας κ[αι]{.greek-supplied} [ε]{.greek-supplied}σεσθε μοι μαρτυρες εν τε [ιερουσαλημ]{.greek-abbr} και εν [πασ]{.greek-supplied}η τ[η]{.greek-supplied} ιουδαια και σαμαρεια και εως εσχατου τη[ς]{.greek-supplied} γης[1:8]{.aside}

και ταυτα ειπων βλεποντων αυτων επηρθη και νεφελη υπελαβεν αυτον απο των οφθαλμων αυτων[1:9]{.aside}

και ως ατε[ν]{.unclear}ιζοντες ησαν εις τον [ουρανον]{.greek-abbr} πορευομενου αυτου και ιδου ανδρες δυο παρειστηκεισαν αυτοις εν εσθητι λευκη[1:10]{.aside}

οι και ειπον ανδρες γαλιλαιοι τι εστηκατ[ε]{.unclear} [εμβλεποντες]{.greek-omitted} [βλεποντες]{.greek-added} εις τον [ουρανον]{.greek-abbr} ουτος ο [ιησους]{.greek-abbr} ο αναληφθεις αφ υμων εις τον [ουρανον]{.greek-abbr} ουτως ελευσεται ον τροπον εθεασασθε αυτον πορευομενον εις τον [ουρανον]{.greek-abbr}[1:11]{.aside}

τοτε υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} απο ορους του καλουμενου ελαιωνος ο εστιν εγγυς ιερουσαλημ σαββατου εχον οδον[1:12]{.aside}

και οτε εισηλθον ανεβησαν εις το υπερωον ου ησαν καταμενοντες ο τε πετρος και ιακωβος και ιωαννης και ανδρεας φιλιππος και θωμας βαρθολομαιος και ματθαιος ιακωβος αλφαιου και σιμων ο ζηλωτης και ιουδας ιακωβου[1:13]{.aside}

ουτοι παντες ησαν προσκαρτερουντες ομοθυμαδον τη προσευχη και τη δεησει συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και μαρια τη [μητρι]{.greek-abbr} του [ιησου]{.greek-abbr} και συν τοις αδελφοις αυτου[1:14]{.aside}

και εν ταις [ημεραις]{.greek-omitted} [ταυταις]{.greek-omitted} [αναστας]{.greek-omitted} [πετρος]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [ειπεν]{.greek-omitted} [ην]{.greek-omitted} [τε]{.greek-omitted} [οχλος]{.greek-omitted} [ονοματων]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [αυτο]{.greek-omitted} [ως]{.greek-omitted} [εκατον]{.greek-omitted} [εικοσι]{.greek-omitted}[1:15]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} ημεραις ταυταις αναστας πετρος εν μεσω των μαθητων ειπεν ην τε οχλος ονοματων επι το αυτο ως εκατον εικοσι[1:15 | instance no. 2]{.aside}

ανδρες αδελφοι εδει πληρωθηναι την γραφην ταυτην ην [προειπεν]{.greek-omitted} [προειπε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον δια στοματος [δαυιδ]{.greek-abbr} περι ιουδα του γενομενου οδηγου τοις [συλλαβουσιν]{.greek-omitted} [συλλαβουσι]{.greek-added} τον [ιησουν]{.greek-abbr}[1:16]{.aside}

οτι κατηριθμημενος ην συν ημιν και [ελαχεν]{.greek-omitted} [ελαχε]{.greek-added} τον κλη[ρο]{.greek-supplied}ν της διακονιας ταυτης[1:17]{.aside}

ουτος μεν ουν εκτη[σατο]{.greek-supplied} χωριον εκ μισθου της αδικιας και πρη[νη]{.unclear}ς [γεν]{.greek-supplied}ομενος [ελακησεν]{.greek-omitted} [ελακησε]{.greek-added} μεσος και εξεχυθη παν[τα]{.greek-supplied} τα σπλαγχνα αυτου[1:18]{.aside}

και γνωστον εγενετο [πασιν]{.greek-omitted} [πασι]{.greek-added} [τ]{.unclear}[οις]{.greek-supplied} [κ]{.greek-supplied}ατοικουσιν ιερουσαλημ ωστε κληθη[ν]{.unclear}αι το χωριον εκεινο τη ιδια διαλεκτω αυτων ακελδαμα τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} χωριον αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω [ψαλμων]{.greek-omitted} [ψαλμω]{.greek-added} γενηθητω η επαυλις αυτου ερημος και μη εστω ο κατοικων εν αυτη και την επισκοπην αυτου λαβοι ετερος[1:20]{.aside}

[δει]{.greek-omitted} [δη]{.greek-added} ουν των συνελθοντων ημιν ανδρων εν παντι χρονω εν ω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} και εξηλθεν εφ ημας ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βαπτισματος ιωαννου εως της ημερας ης ανεληφθη αφ ημων μαρτυρα της αναστασεως αυτου [γενεσθαι]{.greek-omitted} συν ημιν [γενεσθαι]{.greek-added} ενα τουτων[1:22]{.aside}

και εστησαν δυ[ο]{.greek-supplied} ιωσηφ τον καλουμενον βαρσαβαν ος επεκληθη ιουστος και ματθιαν[1:23]{.aside}

και [προσευξαμενοι]{.greek-omitted} [προσεξαμενοι]{.greek-added} ειπον συ [κυριε]{.greek-abbr} καρδιογνωστα παντων αναδειξον ον εξελεξω εκ τουτων των δυο ενα[1:24]{.aside}

λαβειν τον κληρον της διακονιας ταυτης και αποστολης [εξ]{.greek-omitted} [αφ]{.greek-added} ης παρεβη ιουδας πορευθηναι εις τον τοπον τον ιδιον[1:25]{.aside}

και εδωκαν κληρους αυτων και επεσεν ο κληρος επι [ματθιαν]{.greek-omitted} [μαθιαν]{.greek-added} και συγκατεψηφισθη μετα των ενδεκα αποστολων[1:26]{.aside}

### Chapter 2

[και]{.greek-omitted} εν τω [συμπληρουσθαι]{.greek-omitted} [συμπληρουσθε]{.greek-added} την ημεραν της πεντηκοστης ησαν [α]{.greek-added} [απαντες]{.greek-omitted} [ομοθυμαδον]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [αυτο]{.greek-omitted}[2:1]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [συμπληρουσθαι]{.greek-omitted} [την]{.greek-omitted} [ημεραν]{.greek-omitted} [της]{.greek-omitted} [πεντηκοστης]{.greek-omitted} [ησαν]{.greek-omitted} [απαντες]{.greek-omitted} [παντες]{.greek-added} ομοθυμαδον επι το αυτο[2:1 | instance no. 2]{.aside}

και εγενετο αφνω εκ του [ουρανου]{.greek-abbr} ηχος ωσπερ [φερομενης]{.greek-omitted} [φαιρομενης]{.greek-added} πνοης βιαιας και επληρωσεν ολον τον οικον ου ησαν καθημενοι[2:2]{.aside}

και ωφθησαν αυτοις διαμεριζομεναι γλωσσαι ωσει πυρος εκαθισεν τε εφ ενα εκαστον αυτων[2:3]{.aside}

και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετεραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου αυτοις αποφθεγγεσθαι[2:4]{.aside}

ησαν δε εν ιερουσαλημ κατοικουντες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο [τον]{.greek-omitted} [των]{.greek-added} [ουρανον]{.greek-abbr}[2:5]{.aside}

γενομενης δε της φωνης ταυτης [συνηλθεν]{.greek-omitted} [συνηλθε]{.greek-added} το πληθος και συνεχυθη οτι ηκουον εις εκαστος τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

εξισταντο δε παντες και εθαυμαζον λεγοντες προς αλληλους ουκ ιδου παντες ουτοι εισιν οι λαλουντες γαλιλαιοι[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η εγεννηθημεν[2:8]{.aside}

παρθοι και μηδοι και ελαμιται και οι κατοικουντες την μεσοποταμιαν ιουδαιαν τε και [καππαδοκιαν]{.greek-omitted} [καπποδοκιαν]{.greek-added} ποντον και την ασιαν[2:9]{.aside}

φρυγιαν τε και παμφυλιαν αιγυπτον και τα μερη της λιβυης της κατα κυρηνην και οι επιδημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[ιουδαιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυτοι]{.greek-added} κρητες και αραβες ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα μεγαλεια του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και διηπορουν αλλος προς αλλον λεγοντες τι αν θελοι τουτο ειναι[2:12]{.aside}

ετεροι δε [χλευαζοντες]{.greek-omitted} [διαχλευβαζοντες]{.greek-added} ελεγον οτι γλευκους μεμεστωμενοι εισιν[2:13]{.aside}

σταθεις δε πετρος συν τοις ενδεκα [επηρεν]{.greek-omitted} [επηρε]{.greek-added} την φωνην αυτου και απεφθεγξατο αυτοις ανδρες ιουδαιοι και οι κατοικουντες ιερουσαλημ απαντες τουτο [υμιν]{.greek-omitted} [ημιν]{.greek-added} γνωστον εστω [και]{.greek-omitted} [ενωτισασθε]{.greek-omitted} [τα]{.greek-omitted} [ρηματα]{.greek-omitted} [μου]{.greek-omitted}[2:14]{.aside}

[σταθεις]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} [συν]{.greek-omitted} [τοις]{.greek-omitted} [ενδεκα]{.greek-omitted} [επηρεν]{.greek-omitted} [την]{.greek-omitted} [φωνην]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [απεφθεγξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [ανδρες]{.greek-omitted} [ιουδαιοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [κατοικουντες]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [απαντες]{.greek-omitted} [τουτο]{.greek-omitted} [υμιν]{.greek-omitted} [γνωστον]{.greek-omitted} [εστω]{.greek-omitted} και ενωτισασθε τα ρηματα μου[2:14 | instance no. 2]{.aside}

ου γαρ ως υμεις υπολαμβανετε ουτοι μεθυουσιν εστιν γαρ ωρα τριτη της ημερας[2:15]{.aside}

αλλα τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το ειρημενον δια του προφητου ιωηλ[2:16]{.aside}

και εσται [μετα]{.greek-added} [ταυτα]{.greek-added} εν ταις εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υιοι υμων [και]{.greek-omitted} [αι]{.greek-omitted} [θυγατερες]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted} [υμων]{.greek-omitted} ορασεις οψονται και οι πρεσβυτεροι υμων ενυπνια ενυπνιασθησονται[2:17]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις εκχεω απο του [πνευματος]{.greek-abbr} μου και [προφητευσουσιν]{.greek-omitted} [προφητευσουσι]{.greek-added}[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω και σημεια επι της γης κατω αιμα και πυρ και ατμιδα καπνου[2:19]{.aside}

ο ηλιος μεταστραφησεται εις σκοτος και η σεληνη εις αιμα [πριν]{.greek-omitted} [πλην]{.greek-added} η ελθειν την ημεραν [κυριου]{.greek-abbr} την [μεγαλην]{.greek-omitted} [μεγαλη]{.greek-added} και επιφανη[2:20]{.aside}

και εσται πας ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθησεται[2:21]{.aside}

ανδρες ισραηλιται ακουσατε τους λογους τουτους [ιησουν]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} τον ναζωραιον ανδρα απο του [θεου]{.greek-abbr} αποδεδειγμενον εις υμας [δυναμεσιν]{.greek-omitted} [δυναμεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και σημειοις οις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δι αυτου ο [θεος]{.greek-abbr} εν μεσω υμων καθως και αυτοι οιδατε[2:22]{.aside}

τουτον τη [ωρισμενη]{.greek-omitted} [ορισμενη]{.greek-added} βουλη και προγνωσει του [θεου]{.greek-abbr} εκδοτον λαβοντες δια χειρων ανομων προσπηξαντες [ανειλετε]{.greek-omitted} [ανειλατε]{.greek-added}[2:23]{.aside}

ον ο [θεος]{.greek-abbr} [ανεστησεν]{.greek-omitted} [ανεστησε]{.greek-added} λυσας τας ωδινας του θανατου καθοτι ουκ ην δυνατον [κρατεισθαι]{.greek-omitted} [κρατεισθε]{.greek-added} αυτον υπ αυτου[2:24]{.aside}

[δαυιδ]{.greek-abbr} γαρ λεγει εις αυτον προωρωμην τον [κυριον]{.greek-abbr} ενωπιον μου δια παντος οτι εκ [δεξιων]{.greek-omitted} [δεξιω]{.greek-added} μου εστιν ινα μη σαλευθω[2:25]{.aside}

δια τουτο [ευφρανθη]{.greek-omitted} [ηυφρανθη]{.greek-added} η καρδια μου και ηγαλλιασατο η γλωσσα μου ετι δε και η σαρξ μου κατασκηνωσει επ ελπιδι[2:26]{.aside}

οτι ουκ εγκαταλειψεις την ψυχην μου εις αδου ουδε [δωσεις]{.greek-omitted} [τον]{.greek-omitted} [οσιον]{.greek-omitted} [σου]{.greek-omitted} [ιδειν]{.greek-omitted} [διαφθοραν]{.greek-omitted}[2:27]{.aside}

[οτι]{.greek-omitted} [ουκ]{.greek-omitted} [εγκαταλειψεις]{.greek-omitted} [την]{.greek-omitted} [ψυχην]{.greek-omitted} [μου]{.greek-omitted} [εις]{.greek-omitted} [αδου]{.greek-omitted} [ουδε]{.greek-omitted} δωσεις τον οσιον σου ιδειν διαφθοραν[2:27 | instance no. 2]{.aside}

εγνωρισας μοι οδους ζωης πληρωσεις με ευφροσυνης μετα του προσωπου σου[2:28]{.aside}

ανδρες αδελφοι εξον ειπειν μετα παρρησιας προς υμας περι του πατριαρχου [δαυιδ]{.greek-abbr} οτι και [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και εταφη και το μνημα αυτου εστιν εν ημιν αχρι της ημερας ταυτης[2:29]{.aside}

προφητης ουν υπαρχων και ειδως οτι ορκω ωμοσεν αυτω ο [θεος]{.greek-abbr} εκ καρπου της οσφυος αυτου το κατα σαρκα αναστησειν τον [χριστον]{.greek-abbr} καθισαι επι του θρονου αυτου[2:30]{.aside}

[προιδων]{.greek-omitted} [προειδων]{.greek-added} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} περι της αναστασεως του [χριστου]{.greek-abbr} οτι ου κατελειφθη η ψυχη αυτου εις [αδου]{.greek-omitted} [αδην]{.greek-added} ουδε η σαρξ αυτου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[2:31]{.aside}

τουτον τον [ιησουν]{.greek-abbr} ανεστησεν ο [θεος]{.greek-abbr} ου παντες ημεις εσμεν μαρτυρες[2:32]{.aside}

τη δεξια ουν του [θεου]{.greek-abbr} υψωθεις την τε επαγγελιαν του αγιου [πνευματος]{.greek-abbr} λαβων παρα του [πατρος]{.greek-abbr} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} τουτο ο νυν υμεις βλεπετε και ακουετε[2:33]{.aside}

ου γαρ [δαυιδ]{.greek-abbr} ανεβη εις τους [ουρανους]{.greek-abbr} λεγει δε αυτος ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου[2:34]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[2:35]{.aside}

ασφαλως ουν γινωσκετω πας οικος [ισραηλ]{.greek-abbr} οτι και [κυριον]{.greek-abbr} και [χριστον]{.greek-abbr} αυτον ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τουτον τον [ιησουν]{.greek-abbr} ον υμεις εσταυρωσατε[2:36]{.aside}

ακουσαντες δε κατενυγησαν τη καρδια ειπον [τε]{.greek-omitted} [δε]{.greek-added} προς τον πετρον και τους λοιπους αποστολους τι ποιησομεν ανδρες αδελφοι[2:37]{.aside}

πετρος δε εφη προς αυτους μετανοησατε και βαπτισθητω εκαστος υμων επι τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εις αφεσιν [αμαρτιων]{.greek-omitted} [και]{.greek-omitted} [ληψεσθε]{.greek-omitted} [την]{.greek-omitted} [δωρεαν]{.greek-omitted} [του]{.greek-omitted} [αγιου]{.greek-omitted} [πνευματος]{.greek-omitted}[2:38]{.aside}

[πετρος]{.greek-omitted} [δε]{.greek-omitted} [εφη]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [μετανοησατε]{.greek-omitted} [και]{.greek-omitted} [βαπτισθητω]{.greek-omitted} [εκαστος]{.greek-omitted} [υμων]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} [εις]{.greek-omitted} [αφεσιν]{.greek-omitted} αμαρτιων και ληψεσθε την δωρεαν του αγιου [πνευματος]{.greek-abbr}[2:38 | instance no. 2]{.aside}

υμιν γαρ εστιν η επαγγελια [του]{.greek-added} [και]{.corr} τοις τεκνοις υμων και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εις μακραν οσους αν προσκαλεσηται [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων[2:39]{.aside}

ετεροις τε λογοις [πλειοσιν]{.greek-omitted} [πλειοσι]{.greek-added} [διεμαρτυρετο]{.greek-omitted} [διεμαρτυρατο]{.greek-added} και παρεκαλει λεγων σωθητε απο της γενεας της [σκολιας]{.greek-omitted} [πονηρας]{.greek-added} ταυτης[2:40]{.aside}

οι μεν ουν ασμενως αποδεξαμενοι τον λογον αυτου εβαπτισθησαν και προσετεθησαν [εν]{.greek-added} τη ημερα εκεινη ψυχαι ωσει τρισχιλιαι[2:41]{.aside}

ησαν δε προσκαρτερουντες τη διδαχη των αποστολων και τη κοινωνια και τη κλασει του αρτου και ταις προσευχαις[2:42]{.aside}

εγενετο δε παση ψυχη φοβος πολλα [τε]{.greek-omitted} [δε]{.greek-added} τερατα και σημεια δια των αποστολων [εγινετο]{.greek-omitted} [εν]{.greek-added} [[ιερουσαλημ]{.greek-abbr}]{.greek-added} [φοβος]{.greek-added} [τε]{.greek-added} [ην]{.greek-added} [μεγας]{.greek-added} [επι]{.greek-added} [παντας]{.greek-added}[2:43]{.aside}

[και]{.greek-added} παντες δε οι [πιστευοντες]{.greek-omitted} [πιστευσαντες]{.greek-added} ησαν επι το αυτο και ειχον απαντα κοινα[2:44]{.aside}

και τα κτηματα και τας υπαρξεις επιπρασκον και διεμεριζον αυτα [πασιν]{.greek-omitted} [πασι]{.greek-added} καθοτι αν τις χρειαν [ειχεν]{.greek-omitted} [ειχε]{.greek-added}[2:45]{.aside}

καθ ημεραν τε προσκαρτερουντες ομοθυμαδον εν τω ιερω κλωντες τε κατ οικον αρτον μετελαμβανον τροφης εν αγαλλιασει και αφελοτητι καρδιας[2:46]{.aside}

αινουντες τον [θεον]{.greek-abbr} και εχοντες χαριν προς ολον τον λαον ο δε [κυριος]{.greek-abbr} [προσετιθει]{.greek-omitted} [προσετιθη]{.greek-added} [προς]{.greek-added} τους σωζομενους καθ ημεραν [επι]{.greek-added} [το]{.greek-added} [αυτο]{.greek-added} τη εκκλησια[2:47]{.aside}

### Chapter 3

[πετρος]{.greek-added} [επι]{.greek-omitted} [το]{.greek-omitted} [αυτο]{.greek-omitted} δε [πετρος]{.greek-omitted} και ιωαννης ανεβαινον εις το ιερον επι την ωραν της προσευχης την [ενατην]{.greek-omitted} [εννατην]{.greek-added}[3:1]{.aside}

και τις ανηρ χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων εβασταζετο ον ετιθουν καθ ημεραν προς την θυραν του ιερου την λεγομενην ωραιαν του [αιτειν]{.greek-omitted} [ελεημοσυνην]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} [εισπορευομενων]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted}[3:2]{.aside}

[και]{.greek-omitted} [τις]{.greek-omitted} [ανηρ]{.greek-omitted} [χωλος]{.greek-omitted} [εκ]{.greek-omitted} [κοιλιας]{.greek-omitted} [μητρος]{.greek-omitted} [αυτου]{.greek-omitted} [υπαρχων]{.greek-omitted} [εβασταζετο]{.greek-omitted} [ον]{.greek-omitted} [ετιθουν]{.greek-omitted} [καθ]{.greek-omitted} [ημεραν]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted} [του]{.greek-omitted} [ιερου]{.greek-omitted} [την]{.greek-omitted} [λεγομενην]{.greek-omitted} [ωραιαν]{.greek-omitted} [του]{.greek-omitted} αιτειν ελεημοσυνην παρα των εισπορευομενων εις το ιερον[3:2 | instance no. 2]{.aside}

ος ιδων πετρον και ιωαννην μελλοντας εισιεναι εις το ιερον ηρωτα ελεημοσυνην[3:3]{.aside}

ατενισας δε πετρος [εις]{.greek-omitted} [αυτον]{.greek-omitted} συν τω ιωαννη [εις]{.greek-added} [αυτον]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} βλεψον εις ημας[3:4]{.aside}

ο δε επειχεν αυτοις προσδοκων τι παρ αυτων λαβειν[3:5]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε πετρος [αργυριον]{.greek-omitted} [αργυριου]{.greek-added} και [χρυσιον]{.greek-omitted} [χρυσιου]{.greek-added} ουχ υπαρχει μοι ο δε εχω τουτο σοι διδωμι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου εγειραι και περιπατει[3:6]{.aside}

και πιασας αυτον της δεξιας χειρος [ηγειρεν]{.greek-omitted} [ηγειρε]{.greek-added} παραχρημα δε εστερεωθησαν αυτου αι βασεις και τα σφυρα[3:7]{.aside}

και εξαλλομενος εστη και περιεπατει και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} συν αυτοις εις το ιερον περιπατων και αλλομενος και αινων τον [θεον]{.greek-abbr}[3:8]{.aside}

και ειδεν αυτον πας ο λαος περιπατουντα και αινουντα τον [θεον]{.greek-abbr}[3:9]{.aside}

επεγινωσκον [τε]{.greek-omitted} [δε]{.greek-added} αυτον οτι ουτος ην ο προς την ελεημοσυνην καθημενος επι τη ωραια πυλη του ιερου και επλησθησαν θαμβους και εκστασεως επι τω συμβεβηκοτι αυτω[3:10]{.aside}

κρατουντος δε του ιαθεντος χωλου τον πετρον και ιωαννην [συνεδραμεν]{.greek-omitted} [συνεδραμε]{.greek-added} προς αυτους πας ο λαος επι τη στοα τη καλουμενη σολομωντος εκθαμβοι[3:11]{.aside}

ιδων δε πετρος απεκρινατο προς τον λαον ανδρες ισραηλιται τι θαυμαζετε επι τουτω η ημιν τι ατενιζετε ως ιδια δυναμει η ευσεβεια [πεποιηκοσιν]{.greek-omitted} [πεποιηκοσι]{.greek-added} του περιπατειν αυτον[3:12]{.aside}

ο [θεος]{.greek-abbr} αβρααμ και ισαακ και ιακωβ ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [εδοξασεν]{.greek-omitted} [εδοξασε]{.greek-added} τον παιδα αυτου [ιησουν]{.greek-abbr} ον υμεις [μεν]{.greek-omitted} παρεδωκατε και ηρνησασθε αυτον [κατα]{.greek-omitted} [προσωπον]{.greek-omitted} [πιλατου]{.greek-omitted} [κριναντος]{.greek-omitted} [εκεινου]{.greek-omitted} [απολυειν]{.greek-omitted}[[3:13 *(lacunose)*]{.lacunose}]{.aside}

[υμεις]{.greek-omitted} [δε]{.greek-omitted} [τον]{.greek-omitted} [αγιον]{.greek-omitted} [και]{.greek-omitted} [δικαιον]{.greek-omitted} [ηρνησασθε]{.greek-omitted} και ητησασθε ανδρα φονεα χαρισθηναι υμιν[[3:14 *(lacunose)*]{.lacunose}]{.aside}

τον δε αρχηγον της ζωης [απεκτεινατε]{.greek-omitted} [απεκτει]{.greek-added} [ον]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ηγειρεν]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} [ου]{.greek-omitted} [ημεις]{.greek-omitted} [μαρτυρες]{.greek-omitted} [εσμεν]{.greek-omitted}[3:15]{.aside}

[νατε]{.greek-added} [τον]{.greek-omitted} [δε]{.greek-omitted} [αρχηγον]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [απεκτεινατε]{.greek-omitted} ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων ου ημεις μαρτυρες εσμεν[3:15 | instance no. 2]{.aside}

και επι τη πιστει του ονοματος αυτου τουτον ον θεωρειτε και οιδατε [εστερεωσεν]{.greek-omitted} [εστερεωσε]{.greek-added} το ονομα αυτου και η πιστις η δι αυτου εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[3:16]{.aside}

και νυν αδελφοι οιδα οτι κατα αγνοιαν επραξατε ωσπερ και οι αρχοντες υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α [προκατηγγειλεν]{.greek-omitted} [προκατηγγειλε]{.greek-added} δια στοματος παντων των προφητων αυτου παθειν τον [χριστον]{.greek-abbr} επληρωσεν ουτως[3:18]{.aside}

μετανοησατε ουν και επιστρεψατε εις το εξαλειφθηναι υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσι]{.greek-added} [καιροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και αποστειλη τον προκεχειρισμενον υμιν [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[3:20]{.aside}

ον δει [ουρανον]{.greek-abbr} μεν δεξασθαι αχρι χρονων αποκαταστασεως παντων ων ελαλησεν ο [θεος]{.greek-abbr} δια στοματος παντων των αγιων αυτου προφητων απ αιωνος[3:21]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} μεν γαρ προς τους [πατερας]{.greek-abbr} ειπεν οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε αυτου ακουσεσθε κατα παντα οσα αν λαληση προς υμας[3:22]{.aside}

εσται δε πασα ψυχη ητις εαν μη ακουση του προφητου εκεινου εξολοθρευθησεται εκ του λαου[3:23]{.aside}

και παντες δε οι προφηται απο σαμουηλ και των καθεξης οσοι ελαλησαν και [κατηγγειλαν]{.greek-omitted} [προκατηγγειλαν]{.greek-added} τας ημερας ταυτας[3:24]{.aside}

υμεις εστε [οι]{.greek-added} υιοι των προφητων και της διαθηκης ης διεθετο ο [θεος]{.greek-abbr} προς τους [πατερας]{.greek-abbr} ημων λεγων προς αβρααμ και εν τω σπερματι σου ενευλογηθησονται πασαι αι πατριαι της γης[3:25]{.aside}

υμιν πρωτον ο [θεος]{.greek-abbr} αναστησας τον παιδα αυτου [ιησουν]{.greek-abbr} απεστειλεν αυτον ευλογουντα υμας εν τω [αποστρεφειν]{.greek-omitted} [εκαστον]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [πονηριων]{.greek-omitted} [υμων]{.greek-omitted}[3:26]{.aside}

[εν]{.greek-added} [τω]{.greek-added} [σπερματι]{.greek-added} [σου]{.greek-added} [υμιν]{.greek-omitted} [πρωτον]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [αναστησας]{.greek-omitted} [τον]{.greek-omitted} [παιδα]{.greek-omitted} [αυτου]{.greek-omitted} [ιησουν]{.greek-omitted} [απεστειλεν]{.greek-omitted} [αυτον]{.greek-omitted} [ευλογουντα]{.greek-omitted} [υμας]{.greek-omitted} εν τω αποστρεφειν εκαστον απο των πονηριων υμων[3:26 | instance no. 2]{.aside}

### Chapter 4

λαλουντων δε [αυτων]{.greek-omitted} [αυτον]{.greek-added} προς τον λαον επεστησαν αυτοις οι ιερεις και ο στρατηγος του ιερου και οι σαδδουκαιοι[4:1]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον λαον και καταγγελλειν εν τω [ιησου]{.greek-abbr} την αναστασιν των νεκρων[4:2]{.aside}

και επεβαλον αυτοις τας χειρας και εθεντο εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι δε των ακουσαντων τον λογον επιστευσαν και εγενηθη ο αριθμος των ανδρων ωσει χιλιαδες πεντε[4:4]{.aside}

εγενετο δε [επι]{.greek-omitted} [την]{.greek-omitted} [τη]{.greek-added} [αυριον]{.greek-omitted} [επαυριον]{.greek-added} συναχθηναι αυτων τους αρχοντας και πρεσβυτερους και γραμματεις εις [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και ανναν τον αρχιερεα και καιαφαν και ιωαννην και αλεξανδρον και οσοι ησαν εκ γενους αρχιερατικου[4:6]{.aside}

και στησαντες αυτους εν [τω]{.greek-added} μεσω επυνθανοντο εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος πλησθεις [πνευματος]{.greek-abbr} αγιου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους αρχοντες του λαου και πρεσβυτεροι του [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα επι ευεργεσια [ανθρωπου]{.greek-abbr} ασθενους εν τινι ουτος σεσωσται[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω [ισραηλ]{.greek-abbr} οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις εσταυρωσατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν τουτω ουτος παρεστηκεν ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ υμων των οικοδομουντων ο γενομενος εις κεφαλην γωνιας[4:11]{.aside}

και ουκ εστιν εν αλλω [εν]{.greek-added} ουδενι η σωτηρια ουτε γαρ ονομα εστιν ετερον το δεδομενον εν [ανθρωποις]{.greek-abbr} [εν]{.greek-omitted} [ω]{.greek-omitted} [δει]{.greek-omitted} [σωθηναι]{.greek-omitted} [ημας]{.greek-omitted}[4:12]{.aside}

[και]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [εν]{.greek-omitted} [αλλω]{.greek-omitted} [ουδενι]{.greek-omitted} [η]{.greek-omitted} [σωτηρια]{.greek-omitted} [ουτε]{.greek-omitted} [γαρ]{.greek-omitted} [ονομα]{.greek-omitted} [εστιν]{.greek-omitted} [ετερον]{.greek-omitted} [το]{.greek-omitted} [δεδομενον]{.greek-omitted} [εν]{.greek-omitted} [ανθρωποις]{.greek-omitted} εν ω δει σωθηναι ημας[4:12 | instance no. 2]{.aside}

θεωρουντες δε την του πετρου [παρρησιαν]{.greek-omitted} [παρουσιαν]{.greek-added} και ιωαννου και καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και ιδιωται εθαυμαζον επεγινωσκον τε αυτους οτι συν τω [ιησου]{.greek-abbr} ησαν[4:13]{.aside}

τον δε [ανθρωπον]{.greek-abbr} βλεποντες συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου απελθειν συνεβαλλον προς αλληλους[4:15]{.aside}

λεγοντες τι ποιησομεν τοις [ανθρωποις]{.greek-abbr} τουτοις οτι μεν γαρ γνωστον σημειον [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} δι αυτων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} φανερον και ου δυναμεθα αρνησασθαι[4:16]{.aside}

αλλ ινα μη επι πλειον διανεμηθη εις τον λαον απειλη [απειλησομεθα]{.greek-omitted} [απειλησωμεθα]{.greek-added} αυτοις μηκετι λαλειν επι τω ονοματι τουτω μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και καλεσαντες αυτους παρηγγειλαν αυτοις το καθολου μη φθεγγεσθαι μηδε διδασκειν επι τω ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

ο δε πετρος και ιωαννης αποκριθεντες προς αυτους ειπον ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ [ημεις]{.greek-omitted} [υμεις]{.greek-added} α ειδομεν και ηκουσαμεν μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως κολασονται αυτους δια τον λαον οτι παντες εδοξαζον τον [θεον]{.greek-abbr} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων τεσσαρακοντα ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε ηλθον προς τους ιδιους και απηγγειλαν οσα προς αυτους οι αρχιερεις και οι πρεσβυτεροι ειπον[4:23]{.aside}

οι δε ακουσαντες [ομοθυμαδον]{.greek-omitted} ηραν [φωνην]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [και]{.greek-omitted} [ειπον]{.greek-omitted} [δεσποτα]{.greek-omitted} [συ]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [ποιησας]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted}[4:24]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ακουσαντες]{.greek-omitted} [ομοθυμαδον]{.greek-omitted} [ηραν]{.greek-omitted} φωνην προς τον [θεον]{.greek-abbr} και ειπον δεσποτα συ ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[4:24 | instance no. 2]{.aside}

ο δια στοματος [δαυιδ]{.greek-abbr} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

παρεστησαν οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας επι τον αγιον παιδα σου [ιησουν]{.greek-abbr} ον εχρισας ηρωδης τε και ποντιος πιλατος συν [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και λαοις [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η βουλη σου [προωρισεν]{.greek-omitted} [προωρισε]{.greek-added} γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} [επιδε]{.greek-omitted} [επειδε]{.greek-added} επι τας απειλας αυτων και δος τοις δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την χειρα σου εκτεινειν σε εις ιασιν και σημεια και τερατα γινεσθαι δια του ονοματος του αγιου παιδος σου [ιησου]{.greek-abbr}[4:30]{.aside}

και δεηθεντων αυτων εσαλευθη ο τοπος εν ω ησαν συνηγμενοι και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ελαλουν τον λογον του [θεου]{.greek-abbr} μετα παρρησιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και ουδε εις τι των υπαρχοντων αυτων ελεγεν ιδιον ειναι αλλ ην αυτοις απαντα κοινα[4:32]{.aside}

και μεγαλη δυναμει απεδιδουν το μαρτυριον οι αποστολοι της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} χαρις τε μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις [υπηρχον]{.greek-added} [υπηρχεν]{.corr} [εν]{.greek-omitted} αυτοις οσοι γαρ κτητορες χωριων η οικιων υπηρχον πωλουντες εφερον τας τιμας των πιπρασκομενων[4:34]{.aside}

και ετιθουν παρα τους ποδας των αποστολων διεδιδοτο δε εκαστω [καθοτι]{.greek-omitted} [καθο]{.greek-added} [αν]{.greek-omitted} τις χρειαν ειχεν[4:35]{.aside}

ιωσης δε [ο]{.greek-omitted} [επικληθεις]{.greek-omitted} [βαρναβας]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [αποστολων]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [μεθερμηνευομενον]{.greek-omitted} [υιος]{.greek-omitted} [παρακλησεως]{.greek-omitted} [λευιτης]{.greek-omitted} [κυπριος]{.greek-omitted} [τω]{.greek-omitted} [γενει]{.greek-omitted}[4:36]{.aside}

[ιωσης]{.greek-omitted} [δε]{.greek-omitted} ο επικληθεις βαρναβας απο των αποστολων ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον υιος παρακλησεως λευιτης κυπριος τω γενει[4:36 | instance no. 2]{.aside}

υπαρχοντος [αυτω]{.greek-omitted} [αυτου]{.greek-added} αγρου πωλησας [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} το χρημα και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις ανανιας ονοματι συν σαπφειρη τη γυναικι αυτου [επωλησεν]{.greek-omitted} [επωλησε]{.greek-added} κτημα[5:1]{.aside}

και ενοσφισατο απο της τιμης συνειδυιας και της γυναικος αυτου και ενεγκας μερος τι παρα τους ποδας των αποστολων εθηκεν[5:2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε πετρος ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι σε απο της τιμης του χωριου[5:3]{.aside}

[μονον]{.greek-added} ουχι μενον σοι [εμενεν]{.greek-omitted} [εμενε]{.greek-added} και πραθεν εν τη ση εξουσια υπηρχεν τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε ο ανανιας τους λογους τουτους πεσων [εξεψυξεν]{.greek-omitted} [εξεψυξε]{.greek-added} και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι νεωτεροι συνεστειλαν αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων διαστημα και η γυνη αυτου μη ειδυια το γεγονος εισηλθεν[5:7]{.aside}

απεκριθη δε αυτη ο πετρος ειπε μοι ει τοσουτου το χωριον απεδοσθε η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ναι τοσουτου[5:8]{.aside}

ο δε πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτην τι οτι συνεφωνηθη υμιν πειρασαι το [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ιδου οι ποδες των θαψαντων τον ανδρα σου επι τη θυρα και [εξοισουσιν]{.greek-omitted} [εξοισουσι]{.greek-added} σε[5:9]{.aside}

[επεσεν]{.greek-omitted} [επεσε]{.greek-added} δε παραχρημα παρα τους ποδας αυτου και εξεψυξεν εισελθοντες δε οι νεανισκοι ευρον [αυτην]{.greek-omitted} [νεκραν]{.greek-omitted} [και]{.greek-omitted} [εξενεγκαντες]{.greek-omitted} [εθαψαν]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [ανδρα]{.greek-omitted} [αυτης]{.greek-omitted}[5:10]{.aside}

[επεσεν]{.greek-omitted} [δε]{.greek-omitted} [παραχρημα]{.greek-omitted} [παρα]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εξεψυξεν]{.greek-omitted} [εισελθοντες]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted} [ευρον]{.greek-omitted} αυτην νεκραν και εξενεγκαντες εθαψαν προς τον ανδρα αυτης[5:10 | instance no. 2]{.aside}

και εγενετο φοβος μεγας εφ ολην την εκκλησιαν και επι παντας τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων [εγινετο]{.greek-omitted} [εγενετο]{.greek-added} σημεια και τερατα εν τω λαω πολλα και ησαν ομοθυμαδον απαντες εν τη στοα σολομωντος[5:12]{.aside}

των δε λοιπων ουδεις ετολμα κολλασθαι αυτοις αλλ εμεγαλυνεν αυτους ο λαος[5:13]{.aside}

μαλλον δε προσετιθεντο πιστευοντες τω [κυριω]{.greek-abbr} πληθη ανδρων τε και γυναικων[5:14]{.aside}

ωστε κατα τας πλατειας εκφερειν τους ασθενεις και τιθεναι επι κλινων και κραββατων ινα ερχομενου πετρου καν η σκια επισκιαση τινι αυτων[5:15]{.aside}

συνηρχετο δε και το πληθος των περιξ πολεων εις [ιερουσαλημ]{.greek-abbr} φεροντες ασθενεις και οχλουμενους υπο [πνευματων]{.greek-abbr} [ακαθαρτων]{.greek-omitted} [ακαρθαρτων]{.greek-added} οιτινες εθεραπευοντο απαντες[5:16]{.aside}

αναστας δε ο αρχιερευς και παντες οι συν αυτω η ουσα αιρεσις των σαδδουκαιων επλησθησαν ζηλου[5:17]{.aside}

και επεβαλον τας χειρας αυτων επι τους αποστολους και εθεντο αυτους εν τηρησει δημοσια[5:18]{.aside}

αγγελος δε [κυριου]{.greek-abbr} δια της νυκτος [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τας θυρας της φυλακης εξαγαγων τε αυτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added}[5:19]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} και σταθεντες [λαλειτε]{.greek-omitted} [καλειτε]{.greek-added} εν τω ιερω [τω]{.greek-omitted} [λαω]{.greek-omitted} [τον]{.greek-added} [λαον]{.greek-added} παντα τα ρηματα της ζωης ταυτης[5:20]{.aside}

ακουσαντες δε εισηλθον υπο τον ορθρον εις το ιερον και [εδιδασκον]{.greek-omitted} [εδιδαξον]{.greek-added} παραγενομενος δε ο αρχιερευς και οι συν αυτω συνεκαλεσαν το συνεδριον και πασαν την γερουσιαν των υιων [ισραηλ]{.greek-abbr} και απεστειλαν εις το δεσμωτηριον αχθηναι αυτους[5:21]{.aside}

οι δε υπηρεται παραγενομενοι ουχ ευρον [αυτους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} [αναστρεψαντες]{.greek-omitted} [δε]{.greek-omitted} [απηγγειλαν]{.greek-omitted}[5:22]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [υπηρεται]{.greek-omitted} [παραγενομενοι]{.greek-omitted} [ουχ]{.greek-omitted} [ευρον]{.greek-omitted} αυτους εν τη φυλακη αναστρεψαντες δε απηγγειλαν[5:22 | instance no. 2]{.aside}

λεγοντες οτι το μεν δεσμωτηριον ευρομεν κεκλεισμενον εν παση ασφαλεια και τους φυλακας εστωτας προ των θυρων ανοιξαντες δε [εσω]{.greek-omitted} [εξω]{.greek-added} ουδενα ευρομεν[5:23]{.aside}

ως δε ηκουσαν τους λογους τουτους ο τε ιερευς και ο στρατηγος του ιερου και οι αρχιερεις διηπορουν περι αυτων τι αν γενοιτο τουτο[5:24]{.aside}

παραγενομενος δε τις απηγγειλεν αυτοις οτι ιδου οι ανδρες ους εθεσθε εν τη φυλακη εισιν εν τω ιερω εστωτες και διδασκοντες τον λαον[5:25]{.aside}

τοτε απελθων ο στρατηγος συν τοις υπηρεταις ηγαγεν αυτους ου μετα βιας εφοβουντο γαρ τον λαον ινα μη λιθασθωσιν[5:26]{.aside}

αγαγοντες δε αυτους εστησαν εν τω συνεδριω και επηρωτησεν αυτους ο αρχιερευς[5:27]{.aside}

λεγων ου παραγγελια παρηγγειλαμεν υμιν μη διδασκειν επι τω ονοματι τουτω και ιδου πεπληρωκατε την [ιερουσαλημ]{.greek-abbr} της διδαχης υμων και βουλεσθε επαγαγειν εφ ημας το αιμα [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} τουτου[5:28]{.aside}

αποκριθεις δε πετρος και οι αποστολοι ειπον πειθαρχειν δει [θεω]{.greek-abbr} μαλλον η [ανθρωποις]{.greek-abbr}[5:29]{.aside}

ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων ηγειρεν [ιησουν]{.greek-abbr} ον υμεις [διεχειρισασθε]{.greek-omitted} [διεγχειρησασθε]{.greek-added} κρεμασαντες επι ξυλου[5:30]{.aside}

τουτον ο [θεος]{.greek-abbr} αρχηγον και [σωτηρα]{.greek-abbr} [υψωσεν]{.greek-omitted} [υψωσε]{.greek-added} τη δεξια αυτου δουναι μετανοιαν τω [ισραηλ]{.greek-abbr} και αφεσιν αμαρτιων[5:31]{.aside}

και ημεις εσμεν αυτου μαρτυρες των ρηματων τουτων και το [πνευμα]{.greek-abbr} δε το αγιον ο εδωκεν ο [θεος]{.greek-abbr} τοις πειθαρχουσιν αυτω[5:32]{.aside}

οι δε ακουοντες διεπριοντο και εβουλευοντο ανελειν αυτους[5:33]{.aside}

αναστας δε τις εν τω συνεδριω φαρισαιος ονοματι γαμαλιηλ νομοδιδασκαλος τιμιος παντι τω λαω εκελευσεν εξω βραχυ τι τους αποστολους ποιησαι[5:34]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε προς αυτους ανδρες ισραηλιται [προσεχετε]{.greek-omitted} [εαυτοις]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted} [τουτοις]{.greek-omitted} [τι]{.greek-omitted} [μελλετε]{.greek-omitted} [πρασσειν]{.greek-omitted}[5:35]{.aside}

[ειπεν]{.greek-omitted} [τε]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [ανδρες]{.greek-omitted} [ισραηλιται]{.greek-omitted} προσεχετε εαυτοις επι τοις [ανθρωποις]{.greek-abbr} τουτοις τι μελλετε πρασσειν[5:35 | instance no. 2]{.aside}

προ γαρ τουτων των ημερων ανεστη θευδας λεγων ειναι τινα εαυτον ω προσεκληθη αριθμος ανδρων ωσει τετρακοσιων ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις ουδεν[5:36]{.aside}

μετα τουτον ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της απογραφης και [απεστησεν]{.greek-omitted} [απεστησε]{.greek-added} λαον ικανον οπισω αυτου κακεινος απωλετο και παντες οσοι επειθοντο αυτω διεσκορπισθησαν[5:37]{.aside}

και τα νυν λεγω υμιν αποστητε απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε αυτους [οτι]{.greek-omitted} [επει]{.greek-added} εαν η εξ [ανθρωπων]{.greek-abbr} η βουλη η το εργον τουτο καταλυθησεται[5:38]{.aside}

ει δε εκ [θεου]{.greek-abbr} εστιν ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} καταλυσαι αυτο μηποτε και θεομαχοι ευρεθητε [επεισθησαν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added}[5:39]{.aside}

[επεισθησαν]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} και προσκαλεσαμενοι τους αποστολους δειραντες παρηγγειλαν μη λαλειν επι τω ονοματι του [ιησου]{.greek-abbr} και απελυσαν αυτους[5:40]{.aside}

οι μεν ουν επορευοντο χαιροντες απο προσωπου του συνεδριου οτι υπερ του ονοματος [του]{.greek-omitted} [ιησου]{.greek-omitted} κατηξιωθησαν ατιμασθηναι[5:41]{.aside}

πασαν τε ημεραν εν τω ιερω και κατ οικον ουκ επαυοντο διδασκοντες και ευαγγελιζομενοι [τον]{.greek-added} [ιησουν]{.greek-abbr} [τον]{.greek-omitted} [χριστον]{.greek-abbr}[5:42]{.aside}

### Chapter 6

εν δε ταις ημεραις ταυταις πληθυνοντων των μαθητων εγενετο γογγυσμος των ελληνιστων προς τους εβραιους οτι παρεθεωρουντο εν τη διακονια τη καθημερινη αι χηραι αυτων[6:1]{.aside}

προσκαλεσαμενοι δε οι δωδεκα το πληθος των μαθητων ειπον ουκ αρεστον εστιν ημας καταλειψαντας τον λογον του [θεου]{.greek-abbr} διακονειν τραπεζαις[6:2]{.aside}

επισκεψασθε ουν αδελφοι ανδρας εξ υμων μαρτυρουμενους επτα [πληρεις]{.greek-omitted} [πληρης]{.greek-added} [πνευματος]{.greek-abbr} αγιου και σοφιας ους [καταστησωμεν]{.greek-omitted} [καταστησομεν]{.greek-added} επι της χρειας ταυτης[6:3]{.aside}

ημεις δε τη προσευχη και [τη]{.greek-omitted} [διακονια]{.greek-omitted} [του]{.greek-omitted} [λογου]{.greek-omitted} [προσκαρτερησομεν]{.greek-omitted}[6:4]{.aside}

[ημεις]{.greek-omitted} [δε]{.greek-omitted} [τη]{.greek-omitted} [προσευχη]{.greek-omitted} [και]{.greek-omitted} τη διακονια του λογου προσκαρτερησομεν[6:4 | instance no. 2]{.aside}

και ηρεσεν ο λογος ενωπιον παντος του πληθους και εξελεξαντο στεφανον ανδρα πληρης πιστεως και [πνευματος]{.greek-abbr} αγιου και φιλιππον και [προχορον]{.greek-omitted} [προχωρον]{.greek-added} και νικανορα και τιμωνα και παρμεναν και νικολαον προσηλυτον αντιοχεα[6:5]{.aside}

ους εστησαν ενωπιον των αποστολων και προσευξαμενοι επεθηκαν αυτοις τας χειρας[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και επληθυνετο ο αριθμος των μαθητων εν ιερουσαλημ σφοδρα πολυς τε οχλος των ιερεων υπηκουον τη πιστει[6:7]{.aside}

στεφανος δε πληρης πιστεως και δυναμεως εποιει τερατα και σημεια μεγαλα εν τω λαω[6:8]{.aside}

ανεστησαν δε τινες των εκ της συναγωγης της λεγομενης λιβερτινων και κυρηναιων και αλεξανδρεων και των απο κιλικιας και ασιας συζητουντες τω στεφανω[6:9]{.aside}

και ουκ ισχυον αντιστηναι τη σοφια και τω [πνευματι]{.greek-abbr} ω ελαλει[6:10]{.aside}

τοτε [υπεβαλον]{.greek-omitted} [υπεβαλλον]{.greek-added} ανδρας λεγοντας οτι ακηκοαμεν αυτου λαλουντος ρηματα βλασφημα εις [μωσην]{.greek-omitted} [μωυσην]{.greek-added} και τον [θεον]{.greek-abbr}[6:11]{.aside}

συνεκινησαν τε τον λαον και τους πρεσβυτερους και τους γραμματεις και επισταντες συνηρπασαν αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας ψευδεις λεγοντας ο [ανθρωπος]{.greek-abbr} ουτος ου παυεται ρηματα βλασφημα λαλων κατα του τοπου του αγιου και του νομου[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος [καταλυσει]{.greek-omitted} [καταταλυσει]{.greek-added} τον τοπον τουτον και αλλαξει τα εθη α παρεδωκεν ημιν μωσης[6:14]{.aside}

και ατενισαντες εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω ειδον το προσωπον αυτου ωσει προσωπον αγγελου[6:15]{.aside}

### Chapter 7

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} ημων αβρααμ οντι εν τη μεσοποταμια πριν η κατοικησαι αυτον εν χαρραν[7:2]{.aside}

και ειπεν προς αυτον [εξελθε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [συγγενειας]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [δευρο]{.greek-omitted} [εις]{.greek-omitted} [γην]{.greek-omitted} [ην]{.greek-omitted} [αν]{.greek-omitted} [σοι]{.greek-omitted} [δειξω]{.greek-omitted}[7:3]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} εξελθε εκ της γης σου και εκ της συγγενειας σου και δευρο εις γην ην αν σοι δειξω[7:3 | instance no. 2]{.aside}

τοτε εξελθων εκ γης χαλδαιων κατωκησεν εν χαρραν [και]{.greek-added} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου μετωκισεν αυτον εις την γην ταυτην εις ην [υμεις]{.greek-omitted} [ημεις]{.greek-added} νυν κατοικειτε[7:4]{.aside}

και ουκ εδωκεν αυτω κληρονομιαν εν αυτη ουδε βημα [το]{.greek-added} ποδος και [επηγγειλατο]{.greek-omitted} [απηγγειλατο]{.greek-added} δουναι αυτω εις κατασχεσιν αυτην και τω σπερματι αυτου μετ αυτον [ουκ]{.greek-omitted} [οντος]{.greek-omitted} [αυτω]{.greek-omitted} [τεκνου]{.greek-omitted}[7:5]{.aside}

[ελαλησεν]{.greek-omitted} [δε]{.greek-omitted} [ουτως]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} οτι εσται το σπερμα αυτου παροικον εν γη αλλοτρια και δουλωσουσιν αυτο και κακωσουσιν ετη τετρακοσια[7:6]{.aside}

και το εθνος ω εαν [δουλευσωσιν]{.greek-omitted} [δουλευσωσι]{.greek-added} κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και [λατρευσουσιν]{.greek-omitted} [λατρευσωσι]{.greek-added} μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και ουτως [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ και περιετεμεν αυτον τη ημερα τη ογδοη και ο ισαακ τον ιακωβ και ο ιακωβ τους [δωδεκα]{.greek-omitted} [δεδωκα]{.greek-added} [πατριαρχας]{.greek-abbr}[7:8]{.aside}

και οι [πατριαρχαι]{.greek-abbr} ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και εξειλετο αυτον εκ πασων των θλιψεων αυτου και εδωκεν αυτω χαριν και σοφιαν εναντιον φαραω βασιλεως αιγυπτου και κατεστ[η]{.unclear}σεν αυτον ηγουμενον επ αιγυπτον και ολον τον οικον αυτου[7:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} δε λιμος εφ ολην την γην αιγυπτου και χανααν και θλιψις μεγαλη και ουχ ευρισκον χορτασματα οι [πατερες]{.greek-abbr} ημων[7:11]{.aside}

ακουσας δε ιακωβ οντα σιτα εν αιγυπτω [εξαπεστειλεν]{.greek-omitted} [εξαπεστειλε]{.greek-added} τους [πατερας]{.greek-abbr} ημων πρωτον[7:12]{.aside}

και εν τω δευτερω ανεγνωρισθη ιωσηφ τοις αδελφοις αυτου [και]{.greek-omitted} [φανερον]{.greek-omitted} [εγενετο]{.greek-omitted} [τω]{.greek-omitted} [φαραω]{.greek-omitted} [το]{.greek-omitted} [γενος]{.greek-omitted} [του]{.greek-omitted} [ιωσηφ]{.greek-omitted}[7:13]{.aside}

αποστειλας δε ιωσηφ μετεκαλεσατο τον [πατερα]{.greek-abbr} αυτου ιακωβ και πασαν την συγγενειαν εν ψυχαις εβδομηκοντα πεντε[7:14]{.aside}

κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν αυτος και οι [πατερες]{.greek-abbr} ημων[7:15]{.aside}

και μετετεθησαν εις συχεμ και [ε]{.greek-added} [ετεθησαν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [μνηματι]{.greek-omitted} [ο]{.greek-omitted} [ωνησατο]{.greek-omitted} [αβρααμ]{.greek-omitted} [τιμης]{.greek-omitted} [αργυριου]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} [υιων]{.greek-omitted} [εμμορ]{.greek-omitted} [του]{.greek-omitted} [συχεμ]{.greek-omitted}[7:16]{.aside}

[και]{.greek-omitted} [μετετεθησαν]{.greek-omitted} [εις]{.greek-omitted} [συχεμ]{.greek-omitted} [και]{.greek-omitted} [ετεθησαν]{.greek-omitted} [τεθησαν]{.greek-added} εν τω μνηματι ο ωνησατο αβρααμ τιμης αργυριου παρα των υιων εμμορ του συχεμ[7:16 | instance no. 2]{.aside}

καθως δε ηγγιζεν ο χρονος της επαγγελιας [ης]{.greek-omitted} [ην]{.greek-added} ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος ος ουκ [ηδει]{.greek-omitted} [ηδη]{.greek-added} τον ιωσηφ[7:18]{.aside}

ουτος κατασοφισαμενος το γενος ημων [εκακωσεν]{.greek-omitted} [εκακωσε]{.greek-added} τους πατερας ημων του ποιειν εκθετα τα βρεφη αυτων εις το μη [ζωογονεισθαι]{.greek-omitted} [ζωογονειται]{.greek-added}[7:19]{.aside}

εν ω καιρω εγεννηθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ην αστειος τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr}[7:20]{.aside}

εκτε[θ]{.greek-supplied}εντα δε αυτον ανειλετο [αυτον]{.greek-added} η θυγατηρ φαραω και ανεθρεψατο αυτον εαυτη εις υιον[7:21]{.aside}

και επαιδευθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σοφια αιγυπτιων ην [δε]{.greek-omitted} δυνατος εν λογοις και [εν]{.greek-added} εργοις[7:22]{.aside}

ως δε επληρουτο αυτω τεσσαρακονταετης χρονος ανεβη επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον ημυνατο και εποιησεν [εκδικησιν]{.greek-omitted} [εκδηγησιν]{.greek-added} τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

[ενομιζεν]{.greek-omitted} [ενομιζε]{.greek-added} δε συνιεναι τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις [σωτηριαν]{.greek-abbr} οι δε ου συνηκαν[7:25]{.aside}

τη τε επιουση ημερα ωφθη αυτοις μαχομενοις και συνηλασεν αυτους εις ειρηνην ειπων ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} [αδικειτε]{.greek-omitted} [αδικητε]{.greek-added} αλληλους[7:26]{.aside}

ο δε [αδικων]{.greek-omitted} [αδικον]{.greek-added} τον πλησιον απωσατο αυτον ειπων τις σε κατεστησεν αρχοντα και δικαστην εφ [ημας]{.greek-omitted} [ημων]{.greek-added}[7:27]{.aside}

μη ανελειν με συ θελεις ον τροπον ανειλες χθες τον αιγυπτιον[7:28]{.aside}

[εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων τεσσαρακοντα ωφθη αυτω εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-omitted} [εν]{.greek-omitted} [φλογι]{.greek-omitted} [πυρος]{.greek-omitted} [βατου]{.greek-omitted}[7:30]{.aside}

[και]{.greek-omitted} [πληρωθεντων]{.greek-omitted} [ετων]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [ωφθη]{.greek-omitted} [αυτω]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [του]{.greek-omitted} [ορους]{.greek-omitted} [σινα]{.greek-omitted} [αγγελος]{.greek-omitted} [κυριου]{.greek-abbr} εν φλογι πυρος βατου[7:30 | instance no. 2]{.aside}

ο δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ιδων [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} προς αυτον[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} σου ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ εντρομος δε γενομενος [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουκ ετολμα κατανοησαι[7:32]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε αυτω ο [κυριος]{.greek-abbr} λυσον το υποδημα των ποδων σου ο γαρ τοπος εν ω εστηκας γη αγια εστιν[7:33]{.aside}

ιδων ειδον την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και κατεβην [του]{.greek-added} εξελεσθαι αυτους και νυν δευρο [αποστελω]{.greek-omitted} [εξαποστελω]{.greek-added} σε εις αιγυπτον[7:34]{.aside}

τουτον τον [μωσην]{.greek-omitted} [μωυσην]{.greek-added} ον ηρνησαντο ειποντες τις σε κατεστησεν αρχοντα και δικαστην τουτον ο [θεος]{.greek-abbr} αρχοντα και λυτρωτην απεστειλεν εν χειρι αγγελου του οφθεντος αυτω εν τη βατω[7:35]{.aside}

[ουτος]{.greek-omitted} [ουτως]{.greek-added} εξηγαγεν αυτους ποιησας τερατα και σημεια εν [γη]{.greek-omitted} [τη]{.greek-added} αιγυπτω και εν ερυθρα θαλασση και εν τη ερημω ετη τεσσαρακοντα[7:36]{.aside}

ουτος εστιν ο [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην [υμιν]{.greek-omitted} [ημιν]{.greek-added} αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο λογον ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθελησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων αλλ απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

ειποντες τω [αρρων]{.greek-added} [ααρων]{.corr} [ποιησον]{.greek-omitted} [ποιη]{.greek-added} ημιν θεους οι προπορευσονται ημων ο γαρ [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις εκειναις και ανηγαγον θυσιαν τω ειδωλω και ευφραινοντο εν τοις εργοις των χειρων αυτων[7:41]{.aside}

[εστρεψεν]{.greek-omitted} [εστρεψε]{.greek-added} δε ο [θεος]{.greek-abbr} και παρεδωκεν αυτους λατρευειν τη [στριατια]{.greek-added} [στρατια]{.corr} του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη [σφαγια]{.greek-omitted} [και]{.greek-omitted} [θυσιας]{.greek-omitted} [προσηνεγκατε]{.greek-omitted} [μοι]{.greek-omitted} [ετη]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [οικος]{.greek-omitted} [ισραηλ]{.greek-omitted}[7:42]{.aside}

[εστρεψεν]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [και]{.greek-omitted} [παρεδωκεν]{.greek-omitted} [αυτους]{.greek-omitted} [λατρευειν]{.greek-omitted} [τη]{.greek-omitted} [στρατια]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [καθως]{.greek-omitted} [γεγραπται]{.greek-omitted} [εν]{.greek-omitted} [βιβλω]{.greek-omitted} [των]{.greek-omitted} [προφητων]{.greek-omitted} [μη]{.greek-omitted} σφαγια και θυσιας προσηνεγκατε μοι ετη τεσσαρακοντα [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} οικος [ισραηλ]{.greek-abbr}[7:42 | instance no. 2]{.aside}

και ανελαβετε την σκηνην του μολοχ και το αστρον του [θεου]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} [ρεμφαν]{.greek-omitted} [ρεφφαν]{.greek-added} τους τυπους ους εποιησατε προσκυνειν αυτοις και μετοικιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου ην τοις πατρασιν ημων εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωυση]{.greek-added} ποιησαι αυτην κατα τον τυπον ον εωρακει[7:44]{.aside}

ην και εισηγαγον διαδεξαμενοι οι [πατερες]{.greek-abbr} ημων μετα ιησου εν τη κατασχεσει των εθνων ων εξωσεν ο [θεος]{.greek-abbr} απο προσωπου των [πατερων]{.greek-abbr} ημων εως των ημερων [δαυιδ]{.greek-abbr}[7:45]{.aside}

ος [ευρεν]{.greek-omitted} [ευρε]{.greek-added} χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν αυτω οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις ναοις κατοικει καθως ο προφητης λεγει[7:48]{.aside}

ο [ουρανος]{.greek-abbr} μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον [οικοδομησετε]{.greek-omitted} [οικοδομησατε]{.greek-added} μοι λεγει [κυριος]{.greek-abbr} η τις τοπος της καταπαυσεως μου[7:49]{.aside}

ουχι η χειρ μου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted}[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια και τοις ωσιν υμεις αει τω [πνευματι]{.greek-abbr} τω αγιω [αντιπιπτετε]{.greek-omitted} [αντιπιπτεται]{.greek-added} ως οι [πατερες]{.greek-abbr} υμων και υμεις[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι [πατερες]{.greek-abbr} υμων και απεκτειναν τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις [προδοται]{.greek-omitted} [προδοτε]{.greek-added} και φονεις γεγενησθε[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

ακουοντες δε ταυτα διεπριοντο ταις καρδιαις αυτων και εβρυχον τους οδοντας επ αυτον[7:54]{.aside}

υπαρχων δε πληρης [πνευματος]{.greek-abbr} αγιου ατενισας εις τον [ουρανον]{.greek-abbr} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} δοξαν [θεου]{.greek-abbr} [και]{.greek-omitted} [ιησουν]{.greek-omitted} [εστωτα]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[7:55]{.aside}

[υπαρχων]{.greek-omitted} [δε]{.greek-omitted} [πληρης]{.greek-omitted} [πνευματος]{.greek-omitted} [αγιου]{.greek-omitted} [ατενισας]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [ειδεν]{.greek-omitted} [δοξαν]{.greek-omitted} [θεου]{.greek-omitted} και [ιησουν]{.greek-abbr} εστωτα εκ δεξιων τ[ο]{.unclear}υ [θεου]{.greek-abbr}[7:55 | instance no. 2]{.aside}

και ειπεν ιδου θεωρω τους [ουρανους]{.greek-abbr} ανεωγμενους και τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη συνεσχον τα ωτα αυτων και ωρμησαν ομοθυμαδον επ αυτον[7:57]{.aside}

και [εκβαλοντες]{.greek-omitted} [εκβαλλοντες]{.greek-added} εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τα ιματια παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} δεξαι το [πνευμα]{.greek-abbr} μου[7:59]{.aside}

θεις δε τα γονατα [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη [κυριε]{.greek-abbr} μη στησης αυτοις την αμαρτιαν ταυτην και τουτο ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

[σαυλος]{.greek-omitted} [παυλος]{.greek-added} δε ην συνευδοκων τη αναιρεσει αυτου εγενετο δε εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις παντες δε [διεσπαρησαν]{.greek-omitted} [διεσπαρισαν]{.greek-added} κατα τας χωρας της ιουδαιας και σαμαρειας πλην των αποστολων[8:1]{.aside}

συνεκομισαν δε τον στεφανον ανδρες ευλαβεις και [εποιησαντο]{.greek-omitted} [εποιησαν]{.greek-added} [το]{.greek-added} κοπετον μεγαν επ αυτω[8:2]{.aside}

σαυλος δε ελυμαινετο την εκκλησιαν κατα τους οικους εισπορευομ[ε]{.unclear}νος συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπαρεντες διηλθον ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος δε κατελθων εις πολιν της σαμαρειας εκηρυσσεν αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον τε οι οχλοι τοις λεγομενοις υπο του φιλιππου ομοθυμαδον εν τω ακουειν αυτους και βλεπειν τα σημεια α εποιει[8:6]{.aside}

πολλων γαρ των εχοντων [πνευματα]{.greek-abbr} ακαθαρτα βοωντα φωνη μεγαλη εξηρχετο πολλοι δε παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

και εγενετο χαρα μεγαλη εν τη πολει εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι [σιμων]{.greek-omitted} [προυπηρχεν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [μαγευων]{.greek-omitted} [και]{.greek-omitted} [εξιστων]{.greek-omitted} [το]{.greek-omitted} [εθνος]{.greek-omitted} [της]{.greek-omitted} [σαμαρειας]{.greek-omitted} [λεγων]{.greek-omitted} [ειναι]{.greek-omitted} [τινα]{.greek-omitted} [εαυτον]{.greek-omitted} [μεγαν]{.greek-omitted}[8:9]{.aside}

[ανηρ]{.greek-omitted} [δε]{.greek-omitted} [τις]{.greek-omitted} [ονοματι]{.greek-omitted} σιμων [προυπηρχεν]{.greek-omitted} [προυπηρχε]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} μαγευων και εξιστων το εθνος της σαμαρειας λεγων ειναι τινα εαυτον μεγαν[8:9 | instance no. 2]{.aside}

ω προσειχον απο μ[ι]{.unclear}κρου εως μ[ε]{.unclear}γαλου λεγοντες ουτος εστιν η δυναμις του [θεου]{.greek-abbr} η μεγαλη[8:10]{.aside}

προσειχον δε [αυτω]{.greek-omitted} [αυτο]{.greek-added} δια το ικανω χρονω ταις μαγειαις εξεστακεναι αυτους[8:11]{.aside}

οτε δε επιστευσαν τω φιλιππω ευαγγελιζομενω τα περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος [επιστευσεν]{.greek-omitted} [επιστευσε]{.greek-added} και βαπτισθεις ην [προσκαρτερων]{.greek-omitted} [προσκαρτερω]{.greek-added} τω φιλιππω θεωρων τε δυναμεις και σημεια [γινομενα]{.greek-omitted} [γενομενα]{.greek-added} εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} απεστειλαν προς αυτους τον πετρον και [τον]{.greek-added} ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως [λαβωσιν]{.greek-omitted} [λαβωσι]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

ουπω γαρ ην επ ουδενι [αυτων]{.greek-omitted} επιπεπτωκος μονον δε βεβαπτισμενοι [υπηρ]{.greek-added} [υπηρχον]{.corr} εις το ονομα του [χριστου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr}[8:16]{.aside}

τοτε επετιθουν [επ]{.greek-added} [αυτους]{.greek-added} τας χειρας [επ]{.greek-omitted} [αυτους]{.greek-omitted} και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

θεασαμενος δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την [εξουσιαν]{.greek-omitted} [ξουσιαν]{.greek-added} ταυτην ινα ω [εαν]{.greek-omitted} [αν]{.greek-added} επιθω τας χειρας [λαμβανη]{.greek-omitted} [λαμβανει]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον το αργυριον σου συν σοι ειη εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} ενομισας [δε]{.greek-added} δια χρηματων κτασθαι[8:20]{.aside}

ουκ εστιν σοι μερις ουδε κληρος εν τω λογω τουτω η γαρ καρδια σου ουκ εστιν ευθεια ενωπιον του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} ει αρα αφεθησεται σοι [η]{.greek-omitted} [επινοια]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [σου]{.greek-omitted}[8:22]{.aside}

[μετανοησον]{.greek-omitted} [ουν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [κακιας]{.greek-omitted} [σου]{.greek-omitted} [ταυτης]{.greek-omitted} [και]{.greek-omitted} [δεηθητι]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ει]{.greek-omitted} [αρα]{.greek-omitted} [αφεθησεται]{.greek-omitted} [σοι]{.greek-omitted} η επινοια της καρδιας σου[8:22 | instance no. 2]{.aside}

εις γαρ χολην πικριας και συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

αποκριθεις δε ο σιμων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δεηθητε υμεις υπερ εμου προς τον [κυριον]{.greek-abbr} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι μεν ουν [διαμαρτυραμενοι]{.greek-omitted} [διαμαρτυρομενοι]{.greek-added} και λαλησαντες τον λογον του [κυριου]{.greek-abbr} υπεστρεψαν εις ιερουσαλημ πολλας τε κωμας των σαμαρειτων ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} προς [τον]{.greek-added} φιλιππον λεγων αναστηθι και πορευου κατα μεσημβριαν επι την οδον την καταβαινουσαν απο [ιερουσαλημ]{.greek-abbr} εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ αιθιοψ ευνουχος δυναστης κανδακης της βασιλισσης αιθιοπων ος ην επι πασης της γαζης αυτης ος εληλυθει προσκυνησων εις [ιερουσαλημ]{.greek-abbr}[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου και [ανεγινωσκεν]{.greek-omitted} [ανεγινωσκε]{.greek-added} τον προφητην ησαιαν[8:28]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε το [πνευμα]{.greek-abbr} τω φιλιππω προσελθε και κολληθητι τω αρματι τουτω[8:29]{.aside}

[προσδραμων]{.greek-omitted} [προδραμων]{.greek-added} δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος τον προφητην ησαιαν και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε ειπεν πως γαρ αν δυναιμην εαν μη τις οδηγηση με [παρεκαλεσεν]{.greek-omitted} [παρεκαλεσε]{.greek-added} τε τον φιλιππον αναβαντα καθισαι συν αυτω[8:31]{.aside}

η δε περιοχη της γραφης ην ανεγινωσκεν ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του [κειροντος]{.greek-omitted} [κειραντος]{.greek-added} αυτον αφωνος [ουτως]{.greek-omitted} [ουτος]{.greek-added} ουκ ανοιγει το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δεομαι σου περι τινος ο προφητης λεγει τουτο περι [εαυτου]{.greek-omitted} [η]{.greek-omitted} [περι]{.greek-omitted} [ετερου]{.greek-omitted} [τινος]{.greek-omitted}[8:34]{.aside}

[αποκριθεις]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ευνουχος]{.greek-omitted} [τω]{.greek-omitted} [φιλιππω]{.greek-omitted} [ειπεν]{.greek-omitted} [δεομαι]{.greek-omitted} [σου]{.greek-omitted} [περι]{.greek-omitted} [τινος]{.greek-omitted} [ο]{.greek-omitted} [προφητης]{.greek-omitted} [λεγει]{.greek-omitted} [τουτο]{.greek-omitted} [περι]{.greek-omitted} εαυτου η περι ετερου τινος[8:34 | instance no. 2]{.aside}

ανοιξας δε ο φιλιππος το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο [αυτω]{.greek-omitted} τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο κατα την οδον ηλθον επι τι υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} στηναι το αρμα και κατεβησαν αμφοτεροι εις το υδωρ ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν εκ του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} [ηρπασεν]{.greek-omitted} [ηρπασε]{.greek-added} τον φιλιππον και ουκ ειδεν αυτον ουκετι ο ευνουχος επορευετο γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις καισαρειαν[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις δαμασκον προς τας συναγωγας οπως εαν τινας ευρη της οδου οντας ανδρας τε και γυναικας δεδεμενους αγαγη εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε τω πορευεσθαι εγενετο αυτον εγγιζειν τη δαμασκω και εξαιφνης περιηστραψεν αυτον φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} φωνην λεγουσαν αυτω σαουλ σαουλ τι με διωκεις[9:4]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[9:5]{.aside}

αλλα αναστηθι και εισελθε εις την πολιν και λαληθησεται σοι τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι συνοδευοντες αυτω ειστηκεισαν [ενεοι]{.greek-omitted} [εννεοι]{.greek-added} ακουοντες μεν της φωνης μηδενα [δε]{.greek-omitted} θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων τε των οφθαλμων αυτου ουδενα [εβλεπεν]{.greek-omitted} [εθεωρει]{.greek-added} χειραγωγουντες δε αυτον [εισηγαγον]{.greek-omitted} [εισηγα]{.greek-added} [εις]{.greek-omitted} [δαμασκον]{.greek-omitted}[9:8]{.aside}

[γον]{.greek-added} [ηγερθη]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [σαυλος]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ανεωγμενων]{.greek-omitted} [τε]{.greek-omitted} [των]{.greek-omitted} [οφθαλμων]{.greek-omitted} [αυτου]{.greek-omitted} [ουδενα]{.greek-omitted} [εβλεπεν]{.greek-omitted} [χειραγωγουντες]{.greek-omitted} [δε]{.greek-omitted} [αυτον]{.greek-omitted} [εισηγαγον]{.greek-omitted} εις δαμασκον[9:8 | instance no. 2]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον ο [κυριος]{.greek-abbr} εν οραματι ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} [ειπε]{.greek-added} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και ειδεν εν οραματι ανδρα ονοματι ανανιαν εισελθοντα και επιθεντα αυτω χειρα οπως αναβλεψη[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και ωδε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει αυτον υπερ του ονοματ[ο]{.unclear}ς μου παθειν[9:16]{.aside}

[απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} δε ανανιας και εισηλθεν εις την οικιαν και επιθεις επ αυτον τας χειρας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} σαουλ αδελφε ο [κυριος]{.greek-abbr} [απεσταλκεν]{.greek-omitted} [απεσταλκε]{.greek-added} με ο οφθεις σοι εν τη οδω η ηρχου οπως αναβλεψης και πλησθης [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

και ευθεως απεπεσον απο των οφθαλμων αυτου ωσει λεπιδες [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τε [παραχρημα]{.greek-added} και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε ο σαυλος μετα των [οντων]{.greek-added} εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} τον [χριστον]{.greek-abbr} οτι ουτος εστιν ο υιος του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες [και]{.greek-omitted} [ελεγον]{.greek-omitted} [ουχ]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [πορθησας]{.greek-omitted} [εν]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [τους]{.greek-omitted} [επικαλουμενους]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [τουτο]{.greek-omitted} [και]{.greek-omitted} [ωδε]{.greek-omitted} [εις]{.greek-omitted} [τουτο]{.greek-omitted} [εληλυθεν]{.greek-omitted} [ινα]{.greek-omitted} [δεδεμενους]{.greek-omitted} [αυτους]{.greek-omitted} [αγαγη]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [αρχιερεις]{.greek-omitted}[9:21]{.aside}

[εξισταντο]{.greek-omitted} [δε]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [ακουοντες]{.greek-omitted} και ελεγον ουχ ουτο[ς]{.unclear} εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους αγαγη επι τους αρχιερεις[9:21 | instance no. 2]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και [συνεχυνεν]{.greek-omitted} [συνεχυνε]{.greek-added} τους ιουδαιους τους κατοικουντας εν δαμασκω συμβιβαζων οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω η επιβουλη αυτων παρετηρουν τε τας πυλας ημερας [τε]{.greek-omitted} και νυκτος οπως αυτον [ανελωσιν]{.greek-omitted} [ανελωσι]{.greek-added}[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος [καθηκαν]{.greek-omitted} [καθεικαν]{.greek-added} δια του τειχους χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ειδε]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν τω ονοματι του [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος εις [ιερουσαλημ]{.greek-abbr} και παρρησιαζομενος εν τω ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

ελαλει τε και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

επιγνοντες δε οι αδελφοι κατηγαγον αυτον εις καισαρειαν και εξαπεστειλαν αυτον εις ταρσον[9:30]{.aside}

αι μεν ουν εκκλησιαι καθ ολης της [ιουδαιας]{.greek-omitted} [και]{.greek-omitted} γαλιλαιας και σαμαρειας ειχον ειρηνην οικοδομουμεναι και πορευομεναι τω φοβω του [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} επληθυνοντο[9:31]{.aside}

εγενετο δε πετρον [διερ]{.greek-added} [διερχομενον]{.greek-omitted} [δια]{.greek-omitted} [παντων]{.greek-omitted} [κατελθειν]{.greek-omitted} [και]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [αγιους]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [λυδδαν]{.greek-omitted}[9:32]{.aside}

[εγενετο]{.greek-omitted} [δε]{.greek-omitted} [πετρον]{.greek-omitted} [διερχομενον]{.greek-omitted} [χομενον]{.greek-added} δια παντων κατελθειν και προς τους αγιους τους κατοικουντας λυδδαν[9:32 | instance no. 2]{.aside}

[ευρεν]{.greek-omitted} [ευρε]{.greek-added} δε εκει [ανθρωπον]{.greek-abbr} τινα αινεαν ονοματι εξ ετων οκτω κατακειμενον επι κραββατω ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον σεαυτω και ευθεως ανεστη[9:34]{.aside}

και ειδον αυτον παντες οι κατοικουντες λυδδαν και τον [ασσαρωνα]{.greek-omitted} [σαρωναν]{.greek-added} οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} η διερμηνευομενη λεγεται δορκας αυτη ην πληρης αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις [ασθενησ]{.greek-supplied}ασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν εν υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν προς αυτον παρακαλουντες μη οκνησαι διελθειν εως αυτων[9:38]{.aside}

αναστας δε πετρος συνηλθεν αυτοις ον παραγενομενον ανηγαγον εις το υπερωον και παρεστησαν αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μετ αυτων ουσα η δορκας[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος θεις τα γονατα προσηυξατο και επιστρεψας προς το σωμα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} αναστηθι η δε [ηνοιξεν]{.greek-omitted} [διηνοιξε]{.greek-added} τους οφθαλμους αυτης και ιδουσα τον πετρον [ανεκαθισεν]{.greek-omitted} [ανεκαθισε]{.greek-added}[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην φωνησας δε τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωστον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι αυτον εν ιοππη παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις ην εν [και]{.greek-added} [καισαρεια]{.greek-omitted} [ονοματι]{.greek-omitted} [κορνηλιος]{.greek-omitted} [εκατονταρχης]{.greek-omitted} [εκ]{.greek-omitted} [σπειρης]{.greek-omitted} [της]{.greek-omitted} [καλουμενης]{.greek-omitted} [ιταλικης]{.greek-omitted}[10:1]{.aside}

[ανηρ]{.greek-omitted} [δε]{.greek-omitted} [τις]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [καισαρεια]{.greek-omitted} [σαρεια]{.greek-added} ονοματι κορνηλιος εκατονταρχης εκ σπειρης της καλουμενης ιταλικης[10:1 | instance no. 2]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

ειδεν εν οραματι φανερως ωσει ωραν [ενατην]{.greek-omitted} [εννατην]{.greek-added} της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε ατενισας αυτω και εμφοβος γενομενος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} [κυριε]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε αυτω αι προσευχαι σου και αι ελεημοσυναι σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν οικια παρα θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην ευσεβη των προσκαρτερουντων αυτω[10:7]{.aside}

και εξηγησαμενος αυτοις απαντα απεσ[τ]{.unclear}ειλεν αυτους εις την ιοππην[10:8]{.aside}

τη δε επαυριον οδοιπορουντων εκεινων και τη πολει εγγιζοντων ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν εκτην[10:9]{.aside}

εγενετο δε προσπεινος και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γευσασθαι παρασκευαζοντων δε εκεινων [επεπεσεν]{.greek-omitted} [επεσεν]{.greek-added} επ αυτον εκστασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεωγμενον και καταβαινον επ αυτον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις δεδεμενον και καθιεμενον επι της γης[10:11]{.aside}

εν ω [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} παντα τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστας πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος [ειπεν]{.greek-omitted} [μηδαμως]{.greek-omitted} [κυριε]{.greek-omitted} [οτι]{.greek-omitted} [ουδεποτε]{.greek-omitted} [εφαγον]{.greek-omitted} [παν]{.greek-omitted} [κοινον]{.greek-omitted} [η]{.greek-omitted} [ακαθαρτον]{.greek-omitted}[10:14]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον η ακαθαρτον[10:14 | instance no. 2]{.aside}

και φωνη παλιν εκ δευτερου προς αυτον α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαρισε]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι τρις και παλιν ανεληφθη το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο πετρος τι αν ειη το οραμα ο [ειδεν]{.greek-omitted} [ειδε]{.greek-added} και ιδου οι ανδρες οι [απεσταλμενοι]{.greek-omitted} [αποσταλμενοι]{.greek-added} απο του κορνηλιου διερωτησαντες την οικιαν σιμωνος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει σιμων ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι [εγω]{.greek-omitted} [καγω]{.greek-added} απεσταλκα αυτους[10:20]{.aside}

καταβας δε πετρος προς τους ανδρας ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος [και]{.greek-omitted} φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου [του]{.greek-omitted} εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος ουν αυτους [εξενισεν]{.greek-omitted} [εξενισε]{.greek-added} τη δε επαυριον ο πετρος [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} συν αυτοις και τινες των αδελφων [των]{.greek-omitted} απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον [εισηλθον]{.greek-omitted} [συνηλθον]{.greek-added} εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας [αυτου]{.greek-added} προσεκυνησεν[10:25]{.aside}

ο δε πετρος [αυτον]{.greek-omitted} [ηγειρεν]{.greek-omitted} [λεγων]{.greek-omitted} [αναστηθι]{.greek-omitted} [καγω]{.greek-omitted} [αυτος]{.greek-omitted} [ανθρωπος]{.greek-omitted} [ειμι]{.greek-omitted}[10:26]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} αυτον [ηγειρεν]{.greek-omitted} [ηγειρε]{.greek-added} λεγων αναστηθι καγω αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26 | instance no. 2]{.aside}

και συνομιλων αυτω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} και ευρισκει συνεληλυθοτας πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως αθεμιτον εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και αναντιρρητως ηλθον μεταπεμφθεις πυνθανομαι ουν τινι λογω μετεπεμψασθε με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και [φησιν]{.greek-omitted} [φησι]{.greek-added} κορνηλιε εισηκουσθη σου η προσευχη και αι ελεημοσυναι σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και [μετακαλεσαι]{.greek-omitted} [μετακαλεσε]{.greek-added} σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια [σ[ω]{.unclear}μωνος]{.greek-added} [σιμωνος]{.corr} βυρσεως παρα θαλασσαν ος παραγενομενος λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα [αυτου]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} επ αληθειας καταλαμβανομαι οτι ουκ εστιν προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι εθνει ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην [δεκτος]{.greek-omitted} [δεκτως]{.greek-added} αυτω [εστιν]{.greek-omitted} [εστι]{.greek-added}[10:35]{.aside}

τον λογον ον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον [ρημα]{.greek-omitted} [καθ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} [αρξαμενον]{.greek-omitted} απο της γαλιλαιας μετα το βαπτισμα ο εκηρυξεν ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο ναζαρετ [ως]{.greek-omitted} [ος]{.greek-added} εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω [και]{.greek-omitted} [δυναμει]{.greek-omitted} [ος]{.greek-omitted} [διηλθεν]{.greek-omitted} [ευεργετων]{.greek-omitted} [και]{.greek-omitted} [ιωμενος]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [καταδυναστευομενους]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [διαβολου]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ην]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[10:38]{.aside}

[ιησουν]{.greek-omitted} [τον]{.greek-omitted} [απο]{.greek-omitted} [ναζαρετ]{.greek-omitted} [ως]{.greek-omitted} [εχρισεν]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [πνευματι]{.greek-omitted} [αγιω]{.greek-omitted} και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38 | instance no. 2]{.aside}

και ημεις εσμεν μαρτυρες [παντων]{.greek-omitted} ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-abbr} ον και ανειλον κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} [ηγειρεν]{.greek-omitted} [ηγειρε]{.greek-added} τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες [συνεφαγομεν]{.greek-omitted} [συνεφαγωμεν]{.greek-added} και [συνεπιομεν]{.greek-omitted} [συνεπιωμεν]{.greek-added} αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι αυτος εστιν ο ωρισμενος υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη ο πετρος[10:46]{.aside}

μητι το υδωρ κωλυσαι δυναται τις του μη βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

[προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} τε αυτους βαπτισθηναι εν τω ονοματι του [κυριου]{.greek-abbr} τοτε ηρωτησαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε ο πετρος εξετιθετο αυτοις καθεξης λεγων[11:4]{.aside}

εγω ημην εν πολει ιοππη προσευχομενος και ειδον εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και ειδον τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added}[11:6]{.aside}

ηκουσα δε φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα [μου]{.greek-omitted}[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθερισε]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι τρις και παλιν ανεσπασθη απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η ημην απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν διακρινομενον ηλθον δε συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

απηγγειλεν τε ημιν πως ειδεν τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις [σωθηση]{.greek-omitted} [[σω]{.unclear}θησει]{.greek-added} συ και πας ο οικος σου[11:14]{.aside}

εν δε τω αρξασθαι μ[ε]{.unclear} λαλειν [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [του]{.greek-added} [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} [εγω]{.greek-omitted} [δε]{.greek-omitted} [τις]{.greek-omitted} [ημην]{.greek-omitted} [δυνατος]{.greek-omitted} [κωλυσαι]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted}[11:17]{.aside}

[ει]{.greek-omitted} [ουν]{.greek-omitted} [την]{.greek-omitted} [ισην]{.greek-omitted} [δωρεαν]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ως]{.greek-omitted} [και]{.greek-omitted} [ημιν]{.greek-omitted} [πιστευσασιν]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [κυριον]{.greek-omitted} [ιησουν]{.greek-omitted} [χριστον]{.greek-omitted} εγω δε τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17 | instance no. 2]{.aside}

[ακουσαντες]{.greek-omitted} [αακουσαντες]{.greek-added} δε ταυτα ησυχασαν και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες αρα γε και τοις εθνεσιν ο [θεος]{.greek-abbr} [εδωκεν]{.greek-added} την μετανοιαν [εδωκεν]{.greek-omitted} εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες απο της θλιψεως της γενομενης επι στεφανω διηλθον εως φοινικης και κυπρου και αντιοχειας μηδενι λαλουντες τον λογον ει μη μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων ανδρες κυπριοι και κυρηναιοι οιτινες εισελθοντες εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος [πι]{.unclear}στευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας [της]{.greek-omitted} [τοις]{.greek-added} εν ιεροσολυμοις περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει παντας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και πληρης [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε εις ταρσον ο βαρναβας αναζητησαι σαυλον[11:25]{.aside}

και ευρων [αυτον]{.greek-added} ηγαγεν αυτον εις αντιοχειαν εγενετο δε αυτους ενιαυτον ολον συναχθηναι [εν]{.greek-added} τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε τ[αι]{.unclear}ς ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος εσημανεν δια του [πνευματος]{.greek-abbr} λιμον μεγαν μελλειν εσεσθαι εφ ολην την οικουμενην οστις και εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως [ευπορειτο]{.greek-omitted} [ευπορει]{.greek-added} [τις]{.greek-omitted} [ωρισαν]{.greek-omitted} [εκαστος]{.greek-omitted} [αυτων]{.greek-omitted} [εις]{.greek-omitted} [διακονιαν]{.greek-omitted} [πεμψαι]{.greek-omitted} [τοις]{.greek-omitted} [κατοικουσιν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ιουδαια]{.greek-omitted} [αδελφοις]{.greek-omitted}[11:29]{.aside}

[το]{.greek-added} [των]{.greek-omitted} [δε]{.greek-omitted} [μαθητων]{.greek-omitted} [καθως]{.greek-omitted} [ευπορειτο]{.greek-omitted} τις ωρισαν εκαστος αυτων εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29 | instance no. 2]{.aside}

ο και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της εκκλησιας[12:1]{.aside}

[ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

και ιδων οτι αρεστον [εστιν]{.greek-omitted} [εστι]{.greek-added} τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε αι ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} τετραδιοις στρατιωτων [φυλασσειν]{.greek-omitted} [φυλαττειν]{.greek-added} αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} αυτον προαγειν ο ηρωδης τη νυκτι εκεινη ην ο πετρος [κοιμωμενος]{.greek-omitted} [κιμωμενος]{.greek-added} μεταξυ δυο στρατιωτων δεδεμενος [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δυσιν]{.greek-omitted} [δυσι]{.greek-added} φυλακες τε προ της θυρ[ας]{.unclear} ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου [ηγειρεν]{.greek-omitted} [εγειρεν]{.greek-added} αυτον λεγων αναστα εν ταχει και εξεπεσον [αυτου]{.greek-omitted} [εαυτου]{.greek-added} αι αλυσεις εκ των χειρων[12:7]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε ο αγγελος προς αυτον περιζωσαι και υποδησαι τα σανδαλια σου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι[12:8]{.aside}

και εξελθων ηκολουθει αυτω και ουκ [ηδει]{.greek-omitted} [ηδη]{.greek-added} οτι [αληθες]{.greek-omitted} [αληθης]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} το γινομενον δια του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν εις την [πολιν]{.greek-omitted} [ητις]{.greek-omitted} [αυτοματη]{.greek-omitted} [ηνοιχθη]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [εξελθοντες]{.greek-omitted} [προηλθον]{.greek-omitted} [ρυμην]{.greek-omitted} [μιαν]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [απεστη]{.greek-omitted} [ο]{.greek-omitted} [αγγελος]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted}[12:10]{.aside}

[διελθοντες]{.greek-omitted} [δε]{.greek-omitted} [πρωτην]{.greek-omitted} [φυλακην]{.greek-omitted} [και]{.greek-omitted} [δευτεραν]{.greek-omitted} [ηλθον]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [πυλην]{.greek-omitted} [την]{.greek-omitted} [σιδηραν]{.greek-omitted} [την]{.greek-omitted} [φερουσαν]{.greek-omitted} [εις]{.greek-omitted} την πολιν ητις αυτοματη ηνοιχθη αυτοις και εξελθοντες [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10 | instance no. 2]{.aside}

και ο πετρος γενομενος εν εαυτω ειπεν νυν οιδα αληθως οτι [εξαπεστειλεν]{.greek-omitted} [εξαπεστειλε]{.greek-added} [κυριος]{.greek-abbr} τον αγγελον αυτου και εξειλετο με εκ χειρος ηρωδου και πασης της [προσδοκιας]{.greek-omitted} [προδοκιας]{.greek-added} του λαου των ιουδαιων[12:11]{.aside}

[συνελθοντες]{.greek-added} [συνιδων]{.greek-omitted} [τε]{.greek-omitted} ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} ιωαννου του [επικαλουμενου]{.greek-omitted} [επικουμενου]{.greek-added} μαρκου ου ησαν ικανοι συνηθροισμενοι και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του πετρου την θυραν του πυλωνος [προσηλθεν]{.greek-omitted} [προσηλθε]{.greek-added} παιδισκη υπακουσαι ονοματι ροδη[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον μαινη η δε [διισχυριζετο]{.greek-omitted} [διησχυριζετο]{.greek-added} ουτως [εχειν]{.greek-omitted} [εχει]{.greek-added} οι δε ελεγον ο αγγελος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:15]{.aside}

ο δε πετρος [επεμενεν]{.greek-omitted} [επεμενε]{.greek-added} κρουων ανοιξαντες δε ειδον αυτον και εξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξηγαγεν εκ της φυλακης [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε απαγγειλατε ιακωβω και τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας [ην]{.greek-omitted} ταραχος ουκ [ολιγος]{.greek-omitted} [ολιγον]{.greek-added} εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις την καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης [θυμομαχων]{.greek-omitted} [θυμομομαχων]{.greek-added} τυριοις και σιδωνιοις ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως [ητουντο]{.greek-omitted} [ειτουντο]{.greek-added} ειρηνην δια το τρεφεσθαι αυτων την χωραν [απο]{.greek-omitted} [της]{.greek-omitted} [βασιλικης]{.greek-omitted}[12:20]{.aside}

[ην]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ηρωδης]{.greek-omitted} [θυμομαχων]{.greek-omitted} [τυριοις]{.greek-omitted} [και]{.greek-omitted} [σιδωνιοις]{.greek-omitted} [ομοθυμαδον]{.greek-omitted} [δε]{.greek-omitted} [παρησαν]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [πεισαντες]{.greek-omitted} [βλαστον]{.greek-omitted} [τον]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [κοιτωνος]{.greek-omitted} [του]{.greek-omitted} [βασιλεως]{.greek-omitted} [ητουντο]{.greek-omitted} [ειρηνην]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [τρεφεσθαι]{.greek-omitted} [αυτων]{.greek-omitted} [την]{.greek-omitted} [χωραν]{.greek-omitted} απο της βασιλικης[12:20 | instance no. 2]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα βασιλικην και καθισας επι του βηματος εδημηγορει προς αυτους[12:21]{.aside}

ο δε δημος [επεφωνει]{.greek-omitted} [επεφωνη]{.greek-added} φωνη [θεου]{.greek-abbr} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε επαταξεν αυτον [ο]{.greek-added} αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} δοξαν τω [θεω]{.greek-abbr} και γενομενος σκωληκοβρωτος [εξεψυξεν]{.greek-omitted} [εξεψυξε]{.greek-added}[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και επληθυνετο[12:24]{.aside}

βαρναβας δε και σ[αυ]{.unclear}λος υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} πληρωσαντες την διακονιαν συμπαραλαβοντες και ιωαννην τον επικληθεντα μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε τινες εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος ο κυρηναιος μαναην τε ηρωδου του τετραρχου συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον αφορισατε δη μοι τον βαρναβαν και τον σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες τας χειρας αυτοις απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεντες υπο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις την σελευκειαν εκειθεν δε απεπλευσαν εις την κυπρον[13:4]{.aside}

και γενομενοι εν [σαλαμινι]{.greek-omitted} [σαλμινι]{.greek-added} [κατηγγελλον]{.greek-omitted} [κατηγγελον]{.greek-added} τον λογον του [θεου]{.greek-abbr} εν ταις συναγωγαις των ιουδαιων ειχον δε και ιωαννην υπηρετην[13:5]{.aside}

διελθοντες δε την νησον αχρι παφου ευρον τινα μαγον ψευδοπροφητην ιουδαιον ω ονομα [βαριησους]{.greek-omitted} [[βαριν]{.greek-abbr}]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω παυλω ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επ[ε]{.unclear}ζητησεν ακουσαι τον λογον του [θεου]{.greek-omitted}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μαγος ουτως γαρ [μεθερ]{.greek-added} [μεθερμηνευεται]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [ζητων]{.greek-omitted} [διαστρεψαι]{.greek-omitted} [τον]{.greek-omitted} [ανθυπατον]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [πιστεως]{.greek-omitted}[13:8]{.aside}

[ανθιστατο]{.greek-omitted} [δε]{.greek-omitted} [αυτοις]{.greek-omitted} [ελυμας]{.greek-omitted} [ο]{.greek-omitted} [μαγος]{.greek-omitted} [ουτως]{.greek-omitted} [γαρ]{.greek-omitted} [μεθερμηνευεται]{.greek-omitted} [μηνευεται]{.greek-added} το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8 | instance no. 2]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου και ατενισας εις αυτον[13:9]{.aside}

ειπεν ω πληρης παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου [παυση]{.greek-omitted} [παυη]{.greek-added} διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον αχρι καιρου παραχρημα δε επεπεσεν επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου [οι]{.greek-omitted} [ει]{.greek-added} περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε [αποχωρησας]{.greek-omitted} [αποχωρισας]{.greek-added} απ αυτων υπεστρεψεν εις ιεροσολυμα[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει [εστιν]{.greek-omitted} [εστι]{.greek-added} λογος εν υμιν παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη αιγυπτω και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον ετροποφορησεν αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη επτα εν γη [χα]{.greek-added} [χανααν]{.greek-omitted} [κατεκληρονομησεν]{.greek-omitted} [αυτοις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [αυτων]{.greek-omitted}[13:19]{.aside}

[και]{.greek-omitted} [καθελων]{.greek-omitted} [εθνη]{.greek-omitted} [επτα]{.greek-omitted} [εν]{.greek-omitted} [γη]{.greek-omitted} [χανααν]{.greek-omitted} [νααν]{.greek-added} κατεκληρονομησεν αυτοις [την]{.greek-omitted} [γην]{.greek-omitted} [αυτων]{.greek-omitted} [αυτην]{.greek-added}[13:19 | instance no. 2]{.aside}

και μετα ταυτα ως [ετεσιν]{.greek-omitted} [ετεσι]{.greek-added} τετρακοσιοις και πεντηκοντα [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} κριτας εως σαμουηλ του [π]{.greek-supplied}ροφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα [κ]{.unclear}[αι]{.greek-supplied} εδωκεν αυτοις [ο]{.greek-omitted} [θεος]{.greek-omitted} τον σαουλ υιον κις ανδρα εκ φυλης βενιαμιν ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} τω [ισραηλ]{.greek-abbr} σωτηριαν[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας τω [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου [ο]{.greek-omitted} ιωαννης τον δρομον [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} [υμιν]{.greek-omitted} [ημιν]{.greek-added} ο λογος της σωτηριας ταυτης απεσταλη[13:26]{.aside}

οι γαρ κατοικουντες εν [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον αγνοησαντες και τας φωνας των προφητων τας κατα παν σαββατον αναγινωσκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις μνημει[ον]{.greek-supplied}[13:29]{.aside}

[ο]{.greek-supplied} δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφ[θη]{.greek-supplied} [επ]{.greek-supplied}ι ημερας πλειους τοις συναναβασιν αυτω [απ]{.greek-supplied}ο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [εισιν]{.greek-omitted} [εισι]{.greek-added} μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκε]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω τω δευτερω γεγραπται υιος μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον εκ νεκρων μηκετι μελλοντα υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν ανδρες αδελφοι οτι δια τουτου υμιν αφεσις αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωυσεος]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται και θαυμασατε και αφανισθητε οτι εργον εγω εργαζομαι εν ταις ημεραις υμων ο ου μη πιστευσητε εαν τις [εκδιηγηται]{.greek-omitted} [εκδιηγειται]{.greek-added} υμιν[13:41]{.aside}

εξιοντων δε εκ της συναγωγης των ιουδαιων παρεκαλουν τα εθνη εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα[13:42]{.aside}

[λυθεισης]{.greek-omitted} [λυθησης]{.greek-added} δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και τω βαρναβα οιτινες προσλαλουντες επειθον αυτους επιμενειν τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω τε ερχομενω σαββατω σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-abbr}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλου λεγομενοις αντιλεγοντες και βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι δε [ο]{.greek-omitted} [παυλος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [βαρναβας]{.greek-omitted} [ειπον]{.greek-omitted} [υμιν]{.greek-omitted} [ην]{.greek-omitted} [αναγκαιον]{.greek-omitted} [πρωτον]{.greek-omitted} [λαληθηναι]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επειδη]{.greek-omitted} [δε]{.greek-omitted} [απωθεισθε]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [αξιους]{.greek-omitted} [κρινετε]{.greek-omitted} [εαυτους]{.greek-omitted} [της]{.greek-omitted} [αιωνιου]{.greek-omitted} [ζωης]{.greek-omitted} [ιδου]{.greek-omitted} [στρεφομεθα]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted}[13:46]{.aside}

[παρρησιασαμενοι]{.greek-omitted} [δε]{.greek-omitted} ο παυλος και ο βαρναβας ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} επειδη δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46 | instance no. 2]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ εντεταλται ημιν ο [κυριος]{.greek-abbr} τεθεικα σε εις φως εθνων του ειναι σε εις σωτηριαν εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρε]{.greek-added} και εδοξαζον τον λογον του [κυριου]{.greek-abbr} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-abbr} δι ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας και τας ευσχημονας και τους πρωτους της πολεως και επηγειραν διωγμον επι τον παυλον και τον βαρναβαν και εξεβαλον αυτους απο των οριων αυτων[13:50]{.aside}

οι δε εκτιναξαμενοι τον κονιορτον των ποδων αυτων επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι δε μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων τε και ελληνων [πληθος]{.greek-added} πολυ [πληθος]{.greek-omitted}[14:1]{.aside}

οι δε απειθουντες ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου διδοντι σημεια και [τερατα]{.greek-omitted} [τερα]{.greek-added} γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και [λιθοβολησαι]{.greek-omitted} [λιθοβολισαι]{.greek-added} αυτους[14:5]{.aside}

συνιδοντες [κατεφυγον]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [πολεις]{.greek-omitted} [της]{.greek-omitted} [λυκαονιας]{.greek-omitted} [λυστραν]{.greek-omitted} [και]{.greek-omitted} [δερβην]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [περιχωρον]{.greek-omitted}[14:6]{.aside}

[συνιδοντες]{.greek-omitted} κατεφυγον εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6 | instance no. 2]{.aside}

κακει ησαν ευαγγελιζομενοι[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων ος ουδεποτε περιπεπατηκει[14:8]{.aside}

ουτος [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} του παυλου λαλουντος ος ατενισας αυτω και ιδων οτι πιστιν εχει το[υ]{.unclear} σωθηναι[14:9]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} μεγαλη τη φωνη αναστηθι επι τους ποδας σου ορθως και [ηλλετο]{.greek-omitted} [ηλλατο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν ο παυλος επηραν την φωνην αυτων λυκαονιστι λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν δια τον δε παυλον ερμην επειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο δε ιερευς του διος του οντος προ της πολεως αυτων ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις [ηθελεν]{.greek-omitted} [ηθελον]{.greek-added} θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων εισεπηδησαν εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε και ημεις ομοιοπαθεις εσμεν υμιν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο τουτων των ματαιων επιστρεφειν επι τον [θεον]{.greek-abbr} τον ζωντα ος [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις παρωχημεναις γενεαις [ειασεν]{.greek-omitted} [ειασε]{.greek-added} παντα τα εθνη πορευεσθαι [εν]{.greek-added} [ταις]{.greek-omitted} [τοις]{.greek-added} οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρ[ο]{.unclear}ν εαυτον αφηκεν αγαθοποιων [ουρανοθεν]{.greek-abbr} [υμιν]{.greek-omitted} [ημιν]{.greek-added} υετους διδους και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας [καρδιας]{.greek-omitted} [ημων]{.greek-omitted}[14:17]{.aside}

[καιτοιγε]{.greek-omitted} [ουκ]{.greek-omitted} [αμαρτυρον]{.greek-omitted} [εαυτον]{.greek-omitted} [αφηκεν]{.greek-omitted} [αγαθοποιων]{.greek-omitted} [ουρανοθεν]{.greek-omitted} [υμιν]{.greek-omitted} [υετους]{.greek-omitted} [διδους]{.greek-omitted} [και]{.greek-omitted} [καιρους]{.greek-omitted} [καρποφορους]{.greek-omitted} [εμπιπλων]{.greek-omitted} [τροφης]{.greek-omitted} [και]{.greek-omitted} [ευφροσυνης]{.greek-omitted} [τας]{.greek-omitted} καρδιας ημων[14:17 | instance no. 2]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν αυτοις[14:18]{.aside}

επηλθον δε απο αντιοχειας και ικονιου ιουδαιοι και πεισαντες τους οχλους και λιθασαντες τον παυλον εσυρον εξω της πολεως νομισαντες αυτον τεθναναι[14:19]{.aside}

κυκλωσαντων δε [αυτον]{.greek-omitted} [αυτων]{.greek-added} των μαθητων αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν συν τω βαρναβα εις δερβην[14:20]{.aside}

ευ[α]{.unclear}γγελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν και ικονιον και αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει ημας [εισελθειν]{.greek-omitted} εις την βασιλειαν του [θεου]{.greek-abbr} [εισελθειν]{.greek-added}[14:22]{.aside}

χειρ[ο]{.greek-supplied}τονησαντες δε αυτοις πρεσβυτερους κα[τ]{.unclear} [ε]{.unclear}κκλησιαν προσευξαμενοι μετα νηστειων παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον πεπιστευκ[εισα]{.unclear}ν[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον ει[ς]{.unclear} παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη το[ν]{.unclear} λογον κατεβησαν εις [ατταλειαν]{.greek-omitted} [αταλειαν]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν παραδεδομενοι τη χαριτι του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} θυραν πιστεως[14:27]{.aside}

διετριβον δε εκει χρονον ουκ ολιγον συν τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη περιτεμνησθε τω εθει [μωυσεως]{.greek-omitted} [μωυσεος]{.greek-added} ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης ουν στασεως και ζητησεως ουκ ολιγης [τω]{.greek-omitted} [παυλω]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [βαρναβα]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [εταξαν]{.greek-omitted} [αναβαινειν]{.greek-omitted} [παυλον]{.greek-omitted} [και]{.greek-omitted} [βαρναβαν]{.greek-omitted} [και]{.greek-omitted} [τινας]{.greek-omitted} [αλλους]{.greek-omitted} [εξ]{.greek-omitted} [αυτων]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [αποστολους]{.greek-omitted} [και]{.greek-omitted} [πρεσβυτερους]{.greek-omitted} [εις]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [ζητηματος]{.greek-omitted} [τουτου]{.greek-omitted}[15:2]{.aside}

[γενομενης]{.greek-omitted} [ουν]{.greek-omitted} [στασεως]{.greek-omitted} [και]{.greek-omitted} [ζητησεως]{.greek-omitted} [ουκ]{.greek-omitted} [ολιγης]{.greek-omitted} τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2 | instance no. 2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την φοινικην και σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις αδελφοις[15:3]{.aside}

[παραγενομενοι]{.greek-omitted} [γενομενοι]{.greek-added} δε εις [ιερουσαλημ]{.greek-abbr} απεδεχθησαν υπο της εκκλησιας και των αποστολων και των πρεσβυτερων ανηγγειλαν τε οσα ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} μετ αυτων[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων πεπιστευκοτες λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον [μωυσεως]{.greek-omitted} [μωυσεος]{.greek-added}[15:5]{.aside}

συνηχθησαν δε οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε συζητησεως γενομενης αναστας πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων ο [θεος]{.greek-abbr} εν ημιν εξελεξατο δια του στοματος μου ακουσαι τα εθνη τον λογον του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις [δους]{.greek-omitted} [δος]{.greek-added} αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και ουδεν [διεκρινεν]{.greek-omitted} [διεκρινε]{.greek-added} μεταξυ ημων τε και αυτων τη πιστει καθαρισας τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} επιθειναι ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

[εσιγησεν]{.greek-omitted} [εσιγησε]{.greek-added} δε παν το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια [και]{.greek-omitted} [τερατα]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted} [δι]{.greek-omitted} [αυτων]{.greek-omitted}[15:12]{.aside}

[εσιγησεν]{.greek-omitted} [δε]{.greek-omitted} [παν]{.greek-omitted} [το]{.greek-omitted} [πληθος]{.greek-omitted} [και]{.greek-omitted} [ηκουον]{.greek-omitted} [βαρναβα]{.greek-omitted} [και]{.greek-omitted} [παυλου]{.greek-omitted} [εξηγουμενων]{.greek-omitted} [οσα]{.greek-omitted} [εποιησεν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [σημεια]{.greek-omitted} και τερατα εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δι αυτων[15:12 | instance no. 2]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον επι τω ονοματι αυτου[15:14]{.aside}

και τουτω συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted}[15:17]{.aside}

γνωστα απ αιωνος [εστιν]{.greek-omitted} [εστι]{.greek-added} τω [θεω]{.greek-omitted} [[κυριω]{.greek-abbr}]{.greek-added} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

αλλα επιστειλαι αυτοις του απεχεσθαι απο των αλισγηματων των ειδωλων και της πορνειας και του πνικτου και του αιματος[15:20]{.aside}

μωυσης γαρ εκ γενεων αρχαιων κατα πολιν τους κηρυσσοντας αυτον εχει εν ταις συναγωγαις κατα παν σαββατον αναγινωσκομενος[15:21]{.aside}

τοτε [εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν παυλω και βαρναβα ιουδαν τον επικαλουμενον [βαρσαββαν]{.greek-omitted} [βαρσαβαν]{.greek-added} και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων εξελθοντες εταραξαν υμας λογοις ανασκευαζοντες τας ψυχας υμων [λεγοντες]{.greek-omitted} [περιτεμνεσθαι]{.greek-omitted} [και]{.greek-omitted} [τηρειν]{.greek-omitted} [τον]{.greek-omitted} [νομον]{.greek-omitted} [οις]{.greek-omitted} [ου]{.greek-omitted} [διεστειλαμεθα]{.greek-omitted}[15:24]{.aside}

[επειδη]{.greek-omitted} [ηκουσαμεν]{.greek-omitted} [οτι]{.greek-omitted} [τινες]{.greek-omitted} [εξ]{.greek-omitted} [ημων]{.greek-omitted} [εξελθοντες]{.greek-omitted} [εταραξαν]{.greek-omitted} [υμας]{.greek-omitted} [λογοις]{.greek-omitted} [ανασκευαζοντες]{.greek-omitted} [τας]{.greek-omitted} [ψυχας]{.greek-omitted} [υμων]{.greek-omitted} λεγοντες περιτεμνεσθαι και τηρειν τον νομον οις ου διεστειλαμεθα[15:24 | instance no. 2]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον εκλεξαμενους ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα και παυλω[15:25]{.aside}

[ανθρωποις]{.greek-abbr} [παραδεδωκοσιν]{.greek-omitted} [παραδεδωκοσι]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

[εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} γαρ τω αγιω [πνευματι]{.greek-abbr} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην των επαναγκες τουτων[15:28]{.aside}

απεχεσθαι ειδωλοθυτων και αιματος και πνικτου και πορνειας εξ ων διατηρουντες εαυτους ευ πραξετε ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες ηλθον εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

αναγνοντες δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης απο των αδελφων προς τους αποστολους[15:33]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παυλος προς βαρναβαν επιστρεψαντες [δη]{.greek-omitted} [δε]{.greek-added} επισκεψωμεθα τους αδελφους ημων κατα πασαν πολιν εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως εχ[ου]{.unclear}σιν[15:36]{.aside}

βαρναβας δε εβουλευσατο συμπαραλαβειν τον ιωαννην τον καλουμενον μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων [απο]{.greek-omitted} [παμφυλιας]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνελθοντα]{.greek-omitted} [αυτοις]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [εργον]{.greek-omitted} [μη]{.greek-omitted} [συμπαραλαβειν]{.greek-omitted} [τουτον]{.greek-omitted}[15:38]{.aside}

[παυλος]{.greek-omitted} [δε]{.greek-omitted} [ηξιου]{.greek-omitted} [τον]{.greek-omitted} [αποσταντα]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted} απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη συμπαραλαβειν τουτον[15:38 | instance no. 2]{.aside}

εγενετο ουν παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων [τοτε]{.greek-added} [τον]{.corr} [τε]{.corr} βαρναβαν παραλαβοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν [εξηλθεν]{.greek-omitted} [εξηλθες]{.greek-added} παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και κιλικιαν επιστηριζων τας εκκλησιας[15:41]{.aside}

### Chapter 16

[κατηντησεν]{.greek-omitted} [κατηντησε]{.greek-added} δε εις δερβην και [εις]{.greek-added} λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος υιος γυναικος τινος ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τοποις εκεινοις ηδεισαν γαρ απαντες τον [πατερα]{.greek-abbr} αυτου οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις παρεδιδουν αυτοις φυλασσειν τα δογματα τα κεκριμενα υπο των αποστολων και των πρεσβυτερων των εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και επερισσευον τω αριθμω καθ ημεραν[16:5]{.aside}

διελθοντες δε την φρυγιαν και την γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} [λαλησαι]{.greek-omitted} [λαλειν]{.greek-added} τον λογον εν τη ασια[16:6]{.aside}

ελθοντες κατα την μυσιαν επειραζον κατα την [βυθυνιαν]{.greek-added} [βιθυνιαν]{.corr} πορευεσθαι και ουκ ειασεν αυτους το [πνευμα]{.greek-abbr}[16:7]{.aside}

παρελθοντες δε την μυσιαν κατεβησαν εις τρωαδα[16:8]{.aside}

και οραμα δια της νυκτος ωφθη τω παυλω ανηρ τις ην μακεδων εστως παρακαλων αυτον και λεγων διαβας εις μακεδονιαν βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα ειδεν ευθεως εζητησαμεν εξελθειν εις την μακεδονιαν συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[16:10]{.aside}

αναχθεντες ουν απο της τρωαδος ευθυδρο[μη]{.unclear}σαμεν εις σαμοθρακην τη τε επιουση εις νεαπολιν[16:11]{.aside}

εκειθεν τε εις φιλιππους ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη της μεριδος της μακεδονιας πολις κολωνεια ημεν δε εν αυτη τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των σαββατων εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο προσευχη ειναι και καθισαντες ελαλουμεν ταις συνελθουσαις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added}[16:13]{.aside}

και τις γυνη ονοματι λυδια [πορφυροπωλις]{.greek-omitted} [πορφυροπολις]{.greek-added} πολεως θυατειρων σεβομενη τον [θεον]{.greek-abbr} ηκουεν ης ο [κυριος]{.greek-abbr} [διηνοιξεν]{.greek-omitted} [διηνοιξε]{.greek-added} την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης [παρεκαλεσεν]{.greek-omitted} [παρεκαλεσε]{.greek-added} λεγουσα ει κεκρικατε με πιστην [τω]{.greek-omitted} [κυριω]{.greek-omitted} ειναι εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην παιδισκην τινα εχουσαν πνευμα πυθωνος απαντησαι ημιν ητις εργασιαν πολλην [παρειχεν]{.greek-omitted} [παρειχε]{.greek-added} τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και ημιν [εκραζεν]{.greek-omitted} [εκραζε]{.greek-added} λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον σωτηριας[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παραγγελλω σοι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης [οτι]{.greek-omitted} [και]{.greek-added} εξηλθεν [αυτη]{.greek-added} [τη]{.greek-added} [ωρα]{.greek-added} η ελπις της εργασιας αυτων [επιλαβομενοι]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [σιλαν]{.greek-omitted} [ειλκυσαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [αγοραν]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [αρχοντας]{.greek-omitted}[16:19]{.aside}

[ιδοντες]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [κυριοι]{.greek-omitted} [αυτης]{.greek-omitted} [οτι]{.greek-omitted} [εξηλθεν]{.greek-omitted} [η]{.greek-omitted} [ελπις]{.greek-omitted} [της]{.greek-omitted} [εργασιας]{.greek-omitted} [αυτων]{.greek-omitted} επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19 | instance no. 2]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και καταγγελλουσιν εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις ουσιν[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι περιρρηξαντες αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην ειληφως εβαλεν αυτους εις την [εσωτεραν]{.greek-omitted} [εσοτεραν]{.greek-added} φυλακην και τους ποδας αυτων ησφαλισατο εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [επηκροωντο]{.greek-omitted} [επικροωντο]{.greek-added} δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του δεσμωτηριου ανεωχθησαν τε παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν εμελλεν εαυτον αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

[εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} δε φωνη μεγαλη [λεγων]{.greek-added} ο παυλος [λεγων]{.greek-omitted} μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα [εισεπηδησεν]{.greek-omitted} [εισεπηδησε]{.greek-added} και εντρομος γενομενος [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και ο οικος σου[16:31]{.aside}

και ελαλησαν αυτω τον λογον του [κυριου]{.greek-abbr} και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [της]{.greek-omitted} [νυκτος]{.greek-omitted} [ελουσεν]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [πληγων]{.greek-omitted} [και]{.greek-omitted} [εβαπτισθη]{.greek-omitted} [αυτος]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αυτου]{.greek-omitted} [παντες]{.greek-omitted} [παραχρημα]{.greek-omitted}[16:33]{.aside}

[και]{.greek-omitted} [παραλαβων]{.greek-omitted} [αυτους]{.greek-omitted} εν εκεινη τη ωρα της νυκτος ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου παντες παραχρημα[16:33 | instance no. 2]{.aside}

αναγαγων τε αυτους εις τον οικον αυτου [παρεθηκεν]{.greek-omitted} [παρεθηκε]{.greek-added} τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασατο]{.greek-added} πανοικι πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενομενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

[απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} δε ο [δεσμοφυλαξ]{.greek-omitted} [δεσμοφυλακας]{.greek-added} τους λογους τουτους προς [τον]{.greek-omitted} παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας [εκβαλλουσιν]{.greek-omitted} [εκβαλλουσι]{.greek-added} ου γαρ αλλα ελθοντες αυτοι εξαγαγετωσαν[16:37]{.aside}

ανηγγειλαν δε τοις στρατηγοις οι ραβδουχοι τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και [εξαγαγοντες]{.greek-omitted} [εξαγαγωντες]{.greek-added} ηρωτων εξελθειν [εκ]{.greek-added} της πολεως[16:39]{.aside}

εξελθοντες δε εκ της [φαλακης]{.greek-added} [φυλακης]{.corr} εισηλθον προς την λυδιαν και ιδοντες τους αδελφους παρεκαλεσαν αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και απολλωνιαν ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το ειωθος τω παυλω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν ο [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω [καταγγελλω]{.greek-omitted} [καταγγελω]{.greek-added} υμιν[17:3]{.aside}

και τινες εξ αυτων επεισθησαν και προσεκληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων πολυ πληθος γυναικων τε των [πρωτων]{.greek-omitted} [ουκ]{.greek-omitted} [ολιγαι]{.greek-omitted}[17:4]{.aside}

[και]{.greek-omitted} [τινες]{.greek-omitted} [εξ]{.greek-omitted} [αυτων]{.greek-omitted} [επεισθησαν]{.greek-omitted} [και]{.greek-omitted} [προσεκληρωθησαν]{.greek-omitted} [τω]{.greek-omitted} [παυλω]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [σιλα]{.greek-omitted} [των]{.greek-omitted} [τε]{.greek-omitted} [σεβομενων]{.greek-omitted} [ελληνων]{.greek-omitted} [πολυ]{.greek-omitted} [πληθος]{.greek-omitted} [γυναικων]{.greek-omitted} [τε]{.greek-omitted} [των]{.greek-omitted} πρωτων ουκ ολιγαι[17:4 | instance no. 2]{.aside}

προσλαβομενοι δε οι ιουδαιοι οι απειθουντες των αγοραιων τινας ανδρας πονηρους και οχλοποιησαντες εθορυβουν την πολιν επισταντες τε τη οικια [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} εζητουν αυτους αγαγειν εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τον ιασονα και τινας αδελφους επι τους πολιταρχας βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι και ενθαδε παρεισιν[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος [πρασσουσιν]{.greek-omitted} [πρασσουσι]{.greek-added} βασιλεα λεγοντες ετερον ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε [τον]{.greek-omitted} [οχλον]{.greek-omitted} [τους]{.greek-added} [οχλους]{.greek-added} και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι [εκ]{.greek-added} [ευθεως]{.greek-omitted} [δια]{.greek-omitted} της νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις βεροιαν οιτινες παραγενομενοι εις την συναγωγην απηεσαν των ιουδαιων[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας το καθ ημεραν ανακρινοντες τας γραφας ει [εχοι]{.greek-omitted} [εχει]{.greek-added} ταυτα ουτως[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της θεσσαλονικης ιουδαιοι οτι και εν τη βεροια [κατηγγελη]{.greek-omitted} [κατηγγελλη]{.greek-added} υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον [εξαπειλαν]{.greek-added} [εξαπεστειλαν]{.corr} οι αδελφοι πορευεσθαι ως επι την θαλασσαν υπεμενον δε ο τε σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε καθιστωντες τον παυλον ηγαγον αυτον εως αθηνων και λαβοντες εντολην προς τον σιλαν και τιμοθεον ινα ως [ταχιστα]{.greek-omitted} [ταχηστα]{.greek-added} [ελθωσιν]{.greek-omitted} [ηλθον]{.greek-added} προς αυτον εξηεσαν[17:15]{.aside}

εν δε ταις [α]{.greek-added} [αθηναις]{.greek-omitted} [εκδεχομενου]{.greek-omitted} [αυτους]{.greek-omitted} [του]{.greek-omitted} [παυλου]{.greek-omitted} [παρωξυνετο]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted} [θεωρουντι]{.greek-omitted} [κατειδωλον]{.greek-omitted} [ουσαν]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted}[17:16]{.aside}

[θηνες]{.greek-added} [εν]{.greek-omitted} [δε]{.greek-omitted} [ταις]{.greek-omitted} [αθηναις]{.greek-omitted} εκδεχομενου αυτους του παυλου παρωξυνετο το [πνευμα]{.greek-abbr} αυτου εν αυτω [θεωρουντι]{.greek-omitted} [θεορουντι]{.greek-added} κατειδωλον ουσαν την πολιν[17:16 | instance no. 2]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις σεβομενοις και εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε και των επικουρειων και των στοικων φιλοσοφων συνεβαλλον αυτω και τινες ελεγον τι αν [θελοι]{.greek-omitted} ο σπερμολογος ουτος λεγειν οι δε ξενων δαιμονιων δοκει καταγγελευς ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο[17:18]{.aside}

επιλαβομενοι [τε]{.greek-omitted} αυτου επι τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη [η]{.greek-omitted} υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι τι αν θελοι ταυτα ειναι[17:20]{.aside}

[αθηναιοι]{.greek-omitted} [δε]{.greek-omitted} [παντες]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [επιδημουντες]{.greek-omitted} [ξενοι]{.greek-omitted} εις ουδεν ετερον ευκαιρουν η λεγειν τι και ακουειν καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως δεισιδαιμονεστερους υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και [αναθεωρων]{.greek-omitted} [θεωρων]{.greek-added} τα σεβασματα υμων ευρον και βωμον εν ω επεγεγραπτο αγνωστω [θεω]{.greek-abbr} ον ουν αγνοουντες ευσεβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [κυριος]{.greek-abbr} υπαρχων ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} θεραπευεται προσδεομενος τινος αυτος διδους [πασιν]{.greek-omitted} [πασι]{.greek-added} ζωην και πνοην κατα παντα[17:25]{.aside}

εποιησεν τε εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-abbr} ει αρα γε [ψηλαφησειαν]{.greek-omitted} [ψηλαφησει]{.greek-added} αυτον και ευροιεν [καιτοιγε]{.greek-added} [και]{.greek-omitted} [γε]{.greek-omitted} ου μακραν απο ενος εκαστου ημων υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ υμας [ποιη]{.greek-added} [ποιητων]{.greek-omitted} [ειρηκασιν]{.greek-omitted} [του]{.greek-omitted} [γαρ]{.greek-omitted} [και]{.greek-omitted} [γενος]{.greek-omitted} [εσμεν]{.greek-omitted}[17:28]{.aside}

[εν]{.greek-omitted} [αυτω]{.greek-omitted} [γαρ]{.greek-omitted} [ζωμεν]{.greek-omitted} [και]{.greek-omitted} [κινουμεθα]{.greek-omitted} [και]{.greek-omitted} [εσμεν]{.greek-omitted} [ως]{.greek-omitted} [και]{.greek-omitted} [τινες]{.greek-omitted} των [καθ]{.greek-omitted} [υμας]{.greek-omitted} [ποιητων]{.greek-omitted} ειρηκασιν του γαρ [και]{.greek-omitted} γενος εσμεν[17:28 | instance no. 2]{.aside}

[γενος]{.greek-omitted} [γενους]{.greek-added} ουν [υπαρχοντες]{.greek-omitted} [υπαρχοντος]{.greek-added} του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν χρυσω η αργυρω η λιθω χαραγματι τεχνης και [ενθυμησεως]{.greek-omitted} [ενθυμισεως]{.greek-added} [ανθρωπου]{.greek-abbr} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπερ[ι]{.unclear}δων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} [πασιν]{.greek-omitted} [πασι]{.greek-added} πανταχου μετανοειν[17:30]{.aside}

[διοτι]{.greek-omitted} [διο]{.greek-added} εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω ωρισεν πιστιν παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

[ακουσαντες]{.greek-omitted} [ακουσαν]{.greek-added} δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον ακουσομεθα σου παλιν περι τουτου[17:32]{.aside}

και [ουτως]{.greek-omitted} [ουτος]{.greek-added} ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεο[πα]{.unclear}γιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και [ευρων]{.greek-omitted} [ευρον]{.greek-added} τινα ιουδαιον ονοματι ακυλαν ποντικον τω γενει προσφατως εληλυθοτα απο της ιταλιας και [πρισκιλλαν]{.greek-omitted} [πρισκιλλα]{.greek-added} γυναικα αυτου δια το [τεταχεναι]{.greek-omitted} [διατεταχθεναι]{.greek-added} κλαυδιον χωριζεσθαι παντας τους ιουδαιους εκ της ρωμης προσηλθεν αυτοις[18:2]{.aside}

και δια το ομοτεχνον ειναι [εμενεν]{.greek-omitted} [εμεινε]{.greek-added} παρ αυτοις και ειργαζετο ησαν γαρ σκηνοποιοι [την]{.greek-omitted} [τη]{.greek-added} [τεχνην]{.greek-omitted} [τεχνη]{.greek-added}[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον επειθεν τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και ο τιμοθεος συνειχετο τω [πνευματι]{.greek-abbr} ο παυλος [διαμαρτυρομενος]{.greek-omitted} [διαμαρτυρουμενος]{.greek-added} τοις ιουδαιοις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων [εκτιναξαμενος]{.greek-omitted} [εκτιναξανος]{.greek-added} τα ιματια [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας εκειθεν ηλθεν εις οικιαν τινος ονοματι ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια ην συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος [επιστευσεν]{.greek-omitted} [επιστευσε]{.greek-added} τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων ακουοντες επιστευον και εβαπτιζοντο[18:8]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο [κυριος]{.greek-abbr} δι οραματος εν νυκτι τω παυλω μη φοβου αλλα λαλει και μη σιωπησης[18:9]{.aside}

διοτι εγω ειμι μετα σου και ουδεις επιθησεται σοι του κακωσαι σε διοτι λαος [εστιν]{.greek-omitted} [εστι]{.greek-added} μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

[εκαθισεν]{.greek-omitted} [εκαθισε]{.greek-added} [τε]{.greek-omitted} [ται]{.greek-added} ενιαυτον [ενα]{.greek-added} και μηνας εξ διδασκων εν αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της αχαιας κατεπεστησαν ομοθυμαδον οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον ουτος αναπειθει τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν ουν [ην]{.greek-omitted} αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν ηνεσχομην υμων[18:14]{.aside}

ει δε ζητημα [εστιν]{.greek-omitted} [εστι]{.greek-added} περι λογου και ονοματων και νομου του καθ υμας [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι δε παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω γαλλιωνι εμελλεν[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος την κεφαλην εν κεγχρεαις [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γαρ ευχην[18:18]{.aside}

[κατηντησεν]{.greek-omitted} [κατηντησε]{.greek-added} δε εις εφεσον και εκεινους κατελιπεν αυτου αυτος δε εισελθων εις την συναγωγην [διελεχθη]{.greek-omitted} [διελεγχθη]{.greek-added} τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε [αυτων]{.greek-omitted} [αυτον]{.greek-added} επι πλειονα χρονον μειναι παρ αυτοις ου[κ]{.unclear} επενευσεν[18:20]{.aside}

αλλ απεταξατο αυτοις ειπων δ[ει]{.unclear} [μ]{.unclear}ε παντως την εορτην την ερχομενην ποιησαι [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [παλιν]{.greek-omitted} [δε]{.greek-omitted} [ανακαμψω]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [θελοντος]{.greek-omitted} [ανηχθη]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [εφεσου]{.greek-omitted}[18:21]{.aside}

[αλλ]{.greek-omitted} [απεταξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [ειπων]{.greek-omitted} [δει]{.greek-omitted} [με]{.greek-omitted} [παντως]{.greek-omitted} [την]{.greek-omitted} [εορτην]{.greek-omitted} [την]{.greek-omitted} [ερχομενην]{.greek-omitted} [ποιησαι]{.greek-omitted} εις ιεροσολυμα [πα]{.unclear}λιν δε [ανακαμψω]{.greek-omitted} [αναμψω]{.greek-added} προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} αν[η]{.unclear}χθη απο της εφεσου[18:21 | instance no. 2]{.aside}

και κατελθων εις καισαρειαν αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-abbr} επισταμενος [μονον]{.greek-omitted} [μονω]{.greek-added} το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε α[υ]{.unclear}τ[ου]{.unclear} ακυλας και πρισκιλλα προσελαβοντο αυτον και ακρ[ι]{.unclear}βεστερον αυτω εξεθεντο την του [θεου]{.greek-abbr} οδον[18:26]{.aside}

βουλομενου δε αυτου διελθειν εις την αχαιαν [προτρεψαμενοι]{.greek-omitted} [προ[π]{.unclear}εμψαμενοι]{.greek-added} οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος συνεβαλετο πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπιστευκοσι]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν [τω]{.greek-omitted} [τον]{.greek-omitted} [το]{.greek-added} [των]{.greek-added} [απολλω]{.greek-omitted} [απολλων]{.greek-added} ειναι εν [κ]{.unclear}ορινθω παυ[λον]{.greek-supplied} διελθοντα τα ανωτερικα μερη ελθειν ει[ς]{.unclear} εφεσον και ευρων τινας μαθητας[19:1]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} [πρ]{.unclear}[ος]{.greek-supplied} [αυτ]{.greek-supplied}[ο]{.unclear}υς ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευ[σ]{.unclear}[αντες]{.greek-supplied} οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγι[ον]{.unclear} [εσ]{.unclear}τιν ηκουσαμεν[19:2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε προς αυτους εις [τι]{.greek-supplied} [ου]{.unclear}ν ε[β]{.unclear}απτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε παυλος ιω[ανν]{.unclear}ης μεν [εβαπτισεν]{.greek-omitted} [εβαπ[τισ]{.unclear}ε]{.greek-added} βαπτισμα μετανοιας τω λαω λεγων εις τον ερχομενον μετ αυτον ινα [πιστευσωσιν]{.greek-omitted} [πιστευσωσι]{.greek-added} τουτ [ε]{.unclear}στιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε [εβαπτισθησαν]{.greek-omitted} [εβαπτισθη]{.greek-added} [εις]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [ιησου]{.greek-omitted}[19:5]{.aside}

[σαν]{.greek-added} [ακουσαντες]{.greek-omitted} [δε]{.greek-omitted} [εβαπτισθησαν]{.greek-omitted} εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5 | instance no. 2]{.aside}

και επιθεντ[ο]{.unclear}ς αυτοις του παυλου τας χειρας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και προεφητευον[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει δεκαδυο[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι [μηνας]{.greek-omitted} [μεινας]{.greek-added} τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την ιταλιαν παρεδιδουν τον τε παυλον και τινας ετερους δεσμωτας [εκατονταρχη]{.greek-omitted} [εκατονταρχι]{.greek-added} ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω αδρα[μυ]{.unclear}ττηνω μελλοντες πλειν τους κατα την ασιαν τοπους ανηχθημεν [οντος]{.greek-omitted} [οντως]{.greek-added} συν ημιν αρισταρχου μακεδονος θεσσαλονικεως[27:2]{.aside}

τη τε ετερα κατηχθημεν εις σιδωνα φιλανθρωπως [τε]{.greek-omitted} ο ιουλιος τω παυλω χρησαμενος [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν [αναχθεντες]{.greek-omitted} [ανεχθεντες]{.greek-added} υπεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες κατηλθομεν εις μυρα της λυκιας[27:5]{.aside}

κακει ευρων ο εκατονταρχος πλοιον αλεξανδρινον πλεον εις την ιταλιαν ενεβιβασεν ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις [βραδυπλοουντες]{.greek-omitted} [βραδυπλουντες]{.greek-added} και μολις γενομενοι κατα την κνιδον μη προσεωντος ημας του ανεμου υπεπλευσαμεν την [κρητην]{.greek-omitted} [κριτην]{.greek-added} κατα [την]{.greek-added} σαλμωνην[27:7]{.aside}

μολις τε παραλεγομενοι αυτην ηλθομεν εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις λασαια[27:8]{.aside}

ικανου δε χρονου διαγενομενου και [οντος]{.greek-omitted} [οντως]{.greek-added} [ηδη]{.greek-omitted} [ηδει]{.greek-added} επισφαλους του πλοος δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των [ψυχων]{.greek-omitted} [ημων]{.greek-omitted} [μελλειν]{.greek-omitted} [εσεσθαι]{.greek-omitted} [τον]{.greek-omitted} [πλουν]{.greek-omitted}[27:10]{.aside}

[λεγων]{.greek-omitted} [αυτοις]{.greek-omitted} [ανδρες]{.greek-omitted} [θεωρω]{.greek-omitted} [οτι]{.greek-omitted} [μετα]{.greek-omitted} [υβρεως]{.greek-omitted} [και]{.greek-omitted} [πολλης]{.greek-omitted} [ζημιας]{.greek-omitted} [ου]{.greek-omitted} [μονον]{.greek-omitted} [του]{.greek-omitted} [φορτιου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [πλοιου]{.greek-omitted} [αλλα]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} ψυχων ημων μελλειν εσεσθαι τον πλουν[27:10 | instance no. 2]{.aside}

ο δε εκατονταρχης τω [κυβερνητη]{.greek-omitted} [κυβερνιτη]{.greek-added} και τω ναυκληρω επειθετο μαλλον η τοις υπο του [παυλου]{.greek-omitted} [πηλου]{.greek-added} λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς [παραχειμασιαν]{.greek-omitted} [παρεχειμασιαν]{.greek-added} οι πλειους [εθεντο]{.greek-omitted} [εθετο]{.greek-added} βουλην αναχθηναι κακειθεν ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της [κρητης]{.greek-omitted} [κριτης]{.greek-added} [βλεποντα]{.greek-omitted} [βλεπον]{.greek-added} κατα λιβα και κατα χωρον[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες ασσον παρελεγοντο την [κρητην]{.greek-omitted} [κριτην]{.greek-added}[27:13]{.aside}

μετ ου πολυ δε [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} κατ αυτης ανεμος τυφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι υποδραμοντες καλουμενον [κλαυδην]{.greek-omitted} [γλαυδην]{.greek-added} μολις ισχυσαμεν περικρατεις γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες [βοηθειαις]{.greek-omitted} [βοηθειας]{.greek-added} εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη εις την συρτην [εκπεσωσιν]{.greek-omitted} [εκπεσωσι]{.greek-added} χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως δε χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη αυτοχειρες την σκευην του [πλοιου]{.greek-omitted} [πλο[η]{.unclear}ου]{.greek-added} ερριψαμεν[27:19]{.aside}

μητε δε ηλιου μητε [αστρου]{.greek-added} [αστρων]{.corr} επιφαινοντων επι πλειονας ημερας χειμωνος τε ουκ ολιγου επικειμενου λοιπον περιηρειτο πασα ελπις του σωζεσθαι ημας[27:20]{.aside}

πολλης δε ασιτιας υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης [κερδησαι]{.greek-omitted} [κερδησεται]{.greek-added} [τε]{.greek-omitted} την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης ουδεμια εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη [τη]{.greek-omitted} [την]{.greek-added} νυκτι αγγελος του [θεου]{.greek-abbr} ου ειμι ω και λατρευω[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε [δει]{.greek-omitted} [παραστηναι]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [κεχαρισται]{.greek-omitted} [σοι]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [πλεοντας]{.greek-omitted} [μετα]{.greek-omitted} [σου]{.greek-omitted}[27:24]{.aside}

[λεγων]{.greek-omitted} [μη]{.greek-omitted} [φοβου]{.greek-omitted} [παυλε]{.greek-omitted} [καισαρι]{.greek-omitted} [σε]{.greek-omitted} δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24 | instance no. 2]{.aside}

διο ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα [το]{.greek-added} μεσον της νυκτος υπενοουν οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και βολισαντες ευρον οργυιας εικοσι βραχυ δε διαστησαντες και παλιν βολισαντες ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι τε [μη]{.greek-added} [μηπως]{.greek-omitted} [πως]{.greek-added} εις τραχεις [τοπους]{.greek-omitted} εκπεσωμεν εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο [ημεραν]{.greek-omitted} [ημερας]{.greek-added} γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ πρωρας μελλοντων αγκυρας [εκτεινειν]{.greek-omitted} [εκτεινην]{.greek-added}[27:30]{.aside}

ειπεν ο παυλος [προς]{.greek-added} τω εκατονταρχη και τοις στρατιωταις εαν μη [ουτοι]{.greek-omitted} [ουτος]{.greek-added} μεινωσιν εν τω πλοιω υμεις σωθηναι ου δυνασθε[27:31]{.aside}

τοτε οι στρατιωται απεκοψαν τα σχοινια της σ[κ]{.unclear}αφης και ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου [ημελλεν]{.greek-omitted} [εμελλεν]{.greek-added} ημερα γινεσθαι παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην σημερον ημεραν προσδοκωντες ασιτοι διατελειτε μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας [προσλαβειν]{.greek-omitted} [προσβαλειν]{.greek-added} τροφης τουτο γαρ προς της υμετερας [σωτηριας]{.greek-abbr} υπαρχει ουδενος γαρ υμων θριξ εκ της κεφαλης πεσειται[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον [ευχαριστησεν]{.greek-omitted} [ευχαριστησε]{.greek-added} τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

ημεν δε εν τω πλοιω αι πασαι ψυχαι διακοσιαι εβδομηκοντα εξ[27:37]{.aside}

κορεσθεντες δε της τροφης [εκου]{.greek-added} [εκουφιζον]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [εκβαλλομενοι]{.greek-omitted} [τον]{.greek-omitted} [σιτον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted}[27:38]{.aside}

[φιζον]{.greek-added} [κορεσθεντες]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [τροφης]{.greek-omitted} [εκουφιζον]{.greek-omitted} το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38 | instance no. 2]{.aside}

οτε δε ημερα εγενετο την γην ουκ [επεγινωσκον]{.greek-omitted} [εγινωσκον]{.greek-added} κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον εβουλευσαντο ει δυνατον εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των πηδαλιων και επαραντες τον αρτεμονα τη πνεουση κατειχον εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον [δια]{.greek-added} [διθαλασσον]{.greek-omitted} [θαλασσον]{.greek-added} επωκειλαν την [ναυν]{.greek-omitted} [ναυ]{.greek-added} και η μεν πρωρα ερεισασα εμεινεν ασαλευτος η δε πρυμνα ελυετο υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} μη [τις]{.greek-omitted} [τι]{.greek-added} εκκολυμβησας διαφυγη[27:42]{.aside}

ο δε εκατονταρχος βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του [βουληματος]{.greek-omitted} [βηματος]{.greek-added} [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τε τους δυναμενους κολυμβαν απορριψαντας πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους [ους]{.greek-omitted} [μεν]{.greek-omitted} [επι]{.greek-omitted} [σανισιν]{.greek-omitted} [ους]{.greek-omitted} [δε]{.greek-omitted} [επι]{.greek-omitted} [τινων]{.greek-omitted} [των]{.greek-omitted} [απο]{.greek-omitted} του πλοιου και ουτως εγενετο παντας [διασωθηναι]{.greek-omitted} [σωθηναι]{.greek-added} επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες τοτε επεγνωσαν οτι μελιτη η νησος καλειται[28:1]{.aside}

οι δε βαρβαροι παρειχον ου την τυχουσαν φιλανθρωπιαν ημιν [αναψαντες]{.greek-omitted} [αναμψαντες]{.greek-added} γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον εφεστωτα και δια το ψυχος[28:2]{.aside}

[συστρεψαντος]{.greek-omitted} [συνστρεψαντος]{.greek-added} δε του παυλου φρυγανων πληθος και επιθεντος επι την πυραν εχιδνα εκ της θερμης διεξελθουσα [καθηψεν]{.greek-omitted} [καθηψε]{.greek-added} της χειρος αυτου[28:3]{.aside}

[ως]{.greek-omitted} [δε]{.greek-omitted} [ειδον]{.greek-omitted} [οι]{.greek-omitted} [βαρβαροι]{.greek-omitted} [κρεμαμενον]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [αυτου]{.greek-omitted} ελεγον προς αλληλους παντως φονευς εστιν ο ανθρωπος ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν αποτιναξας το θηριον εις το πυρ επαθεν ουδεν κακον[28:5]{.aside}

οι δε προσεδοκων αυτον μελλειν πιμπρασθαι [η]{.greek-omitted} [καταπιπτειν]{.greek-omitted} [αφνω]{.greek-omitted} [νεκρον]{.greek-omitted} [επι]{.greek-omitted} [πολυ]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [προσδοκωντων]{.greek-omitted} [και]{.greek-omitted} [θεωρουντων]{.greek-omitted} [μηδεν]{.greek-omitted} [ατοπον]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted} [γινομενον]{.greek-omitted} [μεταβαλλομενοι]{.greek-omitted} [ελεγον]{.greek-omitted} [θεον]{.greek-omitted} [αυτον]{.greek-omitted} [ειναι]{.greek-omitted}[28:6]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [προσεδοκων]{.greek-omitted} [αυτον]{.greek-omitted} [μελλειν]{.greek-omitted} [πιμπρασθαι]{.greek-omitted} η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων [προσδοκωντων]{.greek-omitted} [προσδοκοντων]{.greek-added} και θεωρουντων μηδεν ατοπον εις αυτον γινομενον [μεταβαλλομενοι]{.greek-omitted} [μεταβαλομενοι]{.greek-added} ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6 | instance no. 2]{.aside}

εν δε τοις περι τον τοπον εκεινον [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} χωρια τω πρωτω της [νησου]{.greek-omitted} [νησω]{.greek-added} ονοματι ποπλιω [ος]{.greek-omitted} [ους]{.greek-added} αναδεξαμενος ημας τρεις ημερας φιλοφρονως [εξενισεν]{.greek-omitted} [εξενησε]{.greek-added}[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του ποπλιου πυρετοις και [δυσεντερια]{.greek-omitted} [δυσεντεριω]{.greek-added} συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις τας χειρας αυτω ιασατο αυτον[28:8]{.aside}

τουτου ουν γενομενου και οι λοιποι οι εχοντες ασθενειας εν τη νησω προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρειαν[28:10]{.aside}

μετα δε τρεις μηνας ηχθημεν εν πλοιω παρακεχειμακοτι εν τη νησω [αλεξανδρινω]{.greek-omitted} [αλεξανδριω]{.greek-added} παρασ[η]{.unclear}μω διοσκουροις[28:11]{.aside}

και [καταχθεντες]{.greek-omitted} [κατεχθεντες]{.greek-added} εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθε[ν]{.unclear} περιελθοντες κατ[η]{.unclear}ντησαμεν εις ρηγιον και μετα μιαν ημεραν [επιγενομενου]{.greek-omitted} [επιγινομενου]{.greek-added} νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις επιμειναι ημερας επτα και ουτως εις την ρωμην [ηλθομεν]{.greek-omitted} [ηλθωμεν]{.greek-added}[28:14]{.aside}

κακειθεν [οι]{.greek-omitted} αδελφοι ακουσαντες τα περι ημων εξηλθον εις [απαντησιν]{.greek-omitted} [απατησιν]{.greek-added} ημιν [αχρι]{.greek-omitted} [αχρις]{.greek-added} αππιου φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} θαρσος[28:15]{.aside}

οτε δε ηλθομεν εις ρωμην ο εκατονταρχος [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τους δ[ε]{.unclear}σμιους τω [στρατοπεδαρχη]{.greek-omitted} [στρατοπεδαρχω]{.greek-added} τω δε παυλω επετραπη μενειν καθ εαυτον συν τω [φυλασσοντι]{.greek-omitted} [φυλασσωντι]{.greek-added} [αυτον]{.greek-omitted} [αυτω]{.greek-added} στρατιωτη[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι τον παυλον τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} προς αυτους ανδρες αδελφοι εγω ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθνεσι]{.greek-added} [τοις]{.greek-omitted} [πατρωοις]{.greek-omitted} [δεσμιος]{.greek-omitted} [εξ]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [παρεδοθην]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [των]{.greek-omitted} [ρωμαιων]{.greek-omitted}[28:17]{.aside}

[εγενετο]{.greek-omitted} [δε]{.greek-omitted} [μετα]{.greek-omitted} [ημερας]{.greek-omitted} [τρεις]{.greek-omitted} [συγκαλεσασθαι]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [τους]{.greek-omitted} [οντας]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted} [πρωτους]{.greek-omitted} [συνελθοντων]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [ελεγεν]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [ανδρες]{.greek-omitted} [αδελφοι]{.greek-omitted} [εγω]{.greek-omitted} [ουδεν]{.greek-omitted} [εναντιον]{.greek-omitted} [ποιησας]{.greek-omitted} [τω]{.greek-omitted} [λαω]{.greek-omitted} [η]{.greek-omitted} [τοις]{.greek-omitted} [εθεσιν]{.greek-omitted} τοις πατρωοις δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας των ρωμαιων[28:17 | instance no. 2]{.aside}

οιτινες ανακριναντες με εβουλοντο απολυσαι δια το μηδεμιαν [θανατου]{.greek-added} αιτιαν [θανατου]{.greek-omitted} υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του [ε]{.unclear}θνους μου εχων τι κατηγορησαι[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε γραμματα περι σου εδεξαμεθα απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν η [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} [τι]{.greek-omitted} περι σου πονηρον[28:21]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον εστιν ημιν οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι δε αυτω ημεραν [ηλθον]{.greek-added} [ηκον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} εις την ξενιαν [προς]{.greek-added} [αυτον]{.greek-added} πλειονες οις εξετιθετο διαμαρτυρομενος [αυτοις]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους τα περι του [ιησου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} απο τε του νομου μωυσεως και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

[ασυμφωνοι]{.greek-omitted} [ασυμφονοι]{.greek-added} δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} ημων[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον [και]{.greek-omitted} ειπον ακοη ακουσετε και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεπετε]{.greek-added} και ου μη ιδητε[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και ιασομαι αυτους[28:27]{.aside}

γνωστον ουν εστω [υμιν]{.greek-omitted} [ημιν]{.greek-added} οτι τοις εθνεσιν απεσταλη το [σωτηριον]{.greek-abbr} [του]{.greek-omitted} [θεου]{.greek-omitted} [αυτοι]{.greek-omitted} [και]{.greek-omitted} [ακουσονται]{.greek-omitted}[28:28]{.aside}

[γνωστον]{.greek-omitted} [ουν]{.greek-omitted} [εστω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted} [απεσταλη]{.greek-omitted} [το]{.greek-omitted} [σωτηριον]{.greek-omitted} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28 | instance no. 2]{.aside}

και ταυτα αυτου ειποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις [συζητησιν]{.greek-omitted} [ζητησιν]{.greek-added}[28:29]{.aside}

[εμεινεν]{.greek-omitted} [εμεινε]{.greek-added} δε ο παυλος [διετιαν]{.greek-omitted} [διαιτιαν]{.greek-added} ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους προς αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα πασης παρρησιας ακωλυτως[28:31]{.aside}

