---
title: "Collation of Byz^RP^ vs 30427 (427)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 427 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30427).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 427                                   	| λογος                              	|
| 427 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 427 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 427               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 427                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 427 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 427                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και [οι]{.greek-omitted} [ιεροσολυμιται]{.greek-omitted} [ιεροσολυμηται]{.greek-added} και εβαπτιζοντο παντες εν τω [ιορδανη]{.greek-omitted} [ποταμω]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} [εξομολογουμενοι]{.greek-omitted} [τας]{.greek-omitted} [αμαρτιας]{.greek-omitted} [αυτων]{.greek-omitted}[1:5]{.aside}

[και]{.greek-omitted} [εξεπορευετο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πασα]{.greek-omitted} [η]{.greek-omitted} [ιουδαια]{.greek-omitted} [χωρα]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ιεροσολυμιται]{.greek-omitted} [και]{.greek-omitted} [εβαπτιζοντο]{.greek-omitted} [παντες]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5 | instance no. 2]{.aside}

ην δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ενδεδυμενος [τριχας]{.greek-omitted} [τρυχας]{.greek-added} καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} ο ισχυροτερος μου οπισω μου ου ουκ ειμι [ικανος]{.greek-omitted} [ικανως]{.greek-added} [κυψας]{.greek-omitted} [κηψας]{.greek-added} λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω [μεν]{.greek-omitted} [εβαπτισα]{.greek-omitted} [υμας]{.greek-omitted} [εν]{.greek-omitted} [υδατι]{.greek-omitted} [αυτος]{.greek-omitted} [δε]{.greek-omitted} [βαπτισει]{.greek-omitted} [υμας]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [αγιω]{.greek-omitted}[1:8]{.aside}

[εγω]{.greek-omitted} μεν [υμας]{.greek-added} εβαπτισα [υμας]{.greek-omitted} εν υδατι αυτος δε [υμας]{.greek-added} βαπτισει [υμας]{.greek-omitted} εν [πνευματι]{.greek-abbr} αγιω[1:8 | instance no. 2]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ιδε]{.greek-added} σχιζομενους τους ουρανους και το [πνευμα]{.greek-abbr} ωσει περιστεραν [καταβαινον]{.greek-omitted} [καταβαινων]{.greek-added} [[απο]{.unclear}]{.greek-added} [[τ]{.unclear}ου]{.greek-added} [επ]{.corr} [αυτον]{.corr}[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} [εκβαλλει]{.greek-added} αυτον [εκβαλλει]{.greek-omitted} εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι [πεπληρωται]{.greek-omitted} [ο]{.greek-omitted} [καιρος]{.greek-omitted} [και]{.greek-omitted} [ηγγικεν]{.greek-omitted} [ηγγυκεν]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} [μετανοειτε]{.greek-omitted} [μετανοηται]{.greek-added} και [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου [του]{.greek-omitted} [σιμωνος]{.greek-omitted} βαλλοντας αμφιβληστρον [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσαν]{.greek-added} ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} δευτε οπισω μου και ποιησω [υμας]{.greek-omitted} [ημας]{.greek-added} γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα [αυτων]{.greek-omitted} ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αυτους [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} καταρτιζοντας τα δικτυα [αυτων]{.greek-added}[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν [εισελθων]{.greek-omitted} [εισελθειν]{.greek-added} εις την συναγωγην εδιδασκεν[1:21]{.aside}

και εξεπλησσοντο [παντες]{.greek-added} επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαριναι]{.greek-added} ηλθες [ωδε]{.greek-added} απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων [φιμωθητι]{.greek-omitted} [ε]{.greek-added} [ξελθε]{.greek-added} [απ]{.greek-added} [αυτου]{.greek-added} και [φημωθητι]{.greek-added} [εξελθε]{.greek-omitted} [εξ]{.greek-omitted} [αυτου]{.greek-omitted}[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το [ακαθαρτον]{.greek-omitted} [ακαθαρ]{.greek-added} [τον]{.greek-added} και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [εστ[η]{.unclear}]{.greek-added} [εστιν]{.greek-omitted} [[εστι]{.corr}]{.greek-added} τουτο τις η διδαχη [αυτη]{.greek-added} η καινη [αυτη]{.greek-omitted} οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις [ακα]{.greek-added} [ακαθαρτοις]{.greek-omitted} [επιτασσει]{.greek-omitted} [και]{.greek-omitted} [υπακουουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[1:27]{.aside}

[και]{.greek-omitted} [εθαμβηθησαν]{.greek-omitted} [παντες]{.greek-omitted} [ωστε]{.greek-omitted} [συζητειν]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [λεγοντας]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [τουτο]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [διδαχη]{.greek-omitted} [η]{.greek-omitted} [καινη]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [κατ]{.greek-omitted} [εξουσιαν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [πνευμασιν]{.greek-omitted} [τοις]{.greek-omitted} [ακαθαρτοις]{.greek-omitted} [θαρτοις]{.greek-added} [επιτασσει]{.greek-omitted} [επιταττει]{.greek-added} και υπακουουσιν αυτω[1:27 | instance no. 2]{.aside}

εξηλθεν [δε]{.greek-omitted} [και]{.greek-added} η ακοη αυτου [ευθυς]{.greek-omitted} εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης [εξελθοντες]{.greek-omitted} [εξελθων]{.greek-added} [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις [την]{.greek-omitted} [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} σιμωνος και ανδρεου [και]{.greek-added} [ιακωβου]{.greek-added} μετα [[ιω]{.greek-abbr}]{.greek-added} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [ιωαννου]{.greek-omitted}[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο [πυρεσσουσα]{.greek-omitted} [πυρρεττουσα]{.greek-added} και ευθεως [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} αυτω περι αυτης [ο]{.greek-added} [πετρος]{.greek-added}[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας [δ]{.unclear}ε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη [επισυνηγμενη]{.greek-omitted} [συνηγμενη]{.greek-added} ην προς την [θυραν]{.greek-omitted} [θυρα]{.greek-added}[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [ποικιλαις]{.greek-omitted} [νοσοις]{.greek-omitted} και [παν]{.greek-added} [δαιμονια]{.greek-omitted} [πολλα]{.greek-omitted} [εξεβαλεν]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηφιεν]{.greek-omitted} [λαλειν]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [οτι]{.greek-omitted} [ηδεισαν]{.greek-omitted} [αυτον]{.greek-omitted}[1:34]{.aside}

[τας]{.greek-added} [τους]{.greek-added} [και]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [πολλους]{.greek-omitted} κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ειδεσαν]{.greek-added} αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34 | instance no. 2]{.aside}

και πρωι εννυχον [λιαν]{.greek-omitted} αναστας εξηλθεν και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας [εχομενας]{.greek-omitted} [εχωμενας]{.greek-added} [κωμοπολεις]{.greek-omitted} [κομοπολεις]{.greek-added} ινα και εκει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων [αυτον]{.greek-omitted} και λεγων αυτω οτι εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} δυνασαι με [καθαρισαι]{.greek-omitted} [καθαρησαι]{.greek-added}[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και [εμβριμησαμενος]{.greek-omitted} [εμβρυμησαμενος]{.greek-added} αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και προσενεγκε [[προσενεγκαι]{.corr}]{.greek-added} περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45]{.aside}

### Chapter 2

και [ελθων]{.greek-added} [εισηλθεν]{.greek-omitted} [παλιν]{.greek-omitted} [εις]{.greek-omitted} [καπερναουμ]{.greek-omitted} [δι]{.greek-omitted} [ημερων]{.greek-omitted} [και]{.greek-omitted} [ηκουσθη]{.greek-omitted} [οτι]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [εστιν]{.greek-omitted}[2:1]{.aside}

[και]{.greek-omitted} [εισηλθεν]{.greek-omitted} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον εστιν[2:1 | instance no. 2]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι [αυτους]{.greek-added} χωρειν μηδε τα προς την θυραν και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες [αιρομενον]{.greek-omitted} υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι [προσεγγισαι]{.greek-omitted} [προσεγγυσαι]{.greek-added} αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και [εξορυξαντες]{.greek-omitted} [εξωρυξαντες]{.greek-added} [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εφ ω ο [παραλυτικος]{.greek-omitted} [παραλιτικος]{.greek-added} κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφεοντε]{.greek-added} [σου]{.greek-added} [σοι]{.corr} αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους [τω]{.greek-added} [[πνευματι]{.greek-abbr}]{.greek-added} ο [ιησους]{.greek-abbr} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [αυτου]{.greek-omitted} οτι ουτως [αυτοι]{.greek-omitted} διαλογιζονται εν εαυτοις ειπεν [αυτοις]{.greek-omitted} τι ταυτα διαλογιζεσθε εν ταις καρδιαις [ημων]{.greek-added} [υμων]{.corr}[2:8]{.aside}

τι εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον σου τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ιδητε]{.greek-added} οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιεναι]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [σου]{.greek-added} τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} [σου]{.greek-omitted} και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εξηλθεν εναντιον παντων ωστε [εξισθασθαι]{.greek-added} [εξιστασθαι]{.corr} παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added}[2:12]{.aside}

και εξηλθεν παλιν παρα την θαλασσαν και πας ο οχλος [ηρχετο]{.greek-omitted} [ερχεται]{.greek-added} προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ιδε]{.greek-added} [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και [η]{.greek-added} [οι]{.corr} γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων [ελεγον]{.greek-omitted} [ειπον]{.greek-added} τοις μαθηταις αυτου [δια]{.greek-added} τι [ο]{.greek-added} [διδασκαλος]{.greek-added} [υμων]{.greek-added} [οτι]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} εσθιει και πινει [μετα]{.greek-added} [των]{.greek-added} [αμαρτωλων]{.greek-added} [και]{.greek-added} [τελωνων]{.greek-added}[2:16]{.aside}

[και]{.greek-omitted} ακουσας [δε]{.greek-added} ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι [ισχυοντες]{.greek-omitted} [υγιαινοντες]{.greek-added} ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων εστιν νηστευειν [οσον]{.greek-omitted} [χρονον]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [εχουσιν]{.greek-omitted} [τον]{.greek-omitted} [νυμφιον]{.greek-omitted} [ου]{.greek-omitted} [δυνανται]{.greek-omitted} [νηστευειν]{.greek-omitted}[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

[και]{.greek-omitted} ουδεις επιβλημα ρακους αγναφου επιρραπτει επι [ιματιον]{.greek-added} [ιματι[ω]{.unclear}]{.corr} παλαιω ει δε μη [αιρει]{.greek-omitted} [αιρη]{.greek-added} το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος [εκχειται]{.greek-omitted} [εκκεχυται]{.greek-added} και οι ασκοι [απολουνται]{.greek-omitted} [απωλουνται]{.greek-added} [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον εις ασκους καινους [βλητεον]{.greek-omitted} [βληταιον]{.greek-added}[2:22]{.aside}

και εγενετο [παραπορευεσθαι]{.greek-omitted} [πορευεσθαι]{.greek-added} αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν εσχεν και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

[ηλθε]{.greek-added} [και]{.greek-omitted} [εισηλθεν]{.greek-omitted} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις [σαβασιν]{.greek-added} [σαββασιν]{.corr} [θεραπευσει]{.greek-omitted} [θεραπευση]{.greek-added} αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} [εχοντι]{.greek-omitted} [εχοντα]{.greek-added} την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις [τι]{.greek-added} [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η [αποκτειναι]{.greek-omitted} [απολεσαι]{.greek-added} οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου [υγιης]{.greek-omitted} [υγιεις]{.greek-added} ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον [εποιουν]{.greek-omitted} [εποιησαν]{.greek-added} κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απωλεσωσιν]{.greek-added}[3:6]{.aside}

[και]{.greek-omitted} ο [δε]{.greek-added} [ιησους]{.greek-abbr} ανεχωρησεν [[ανεχωρησε]{.corr}]{.greek-added} μετα των μαθητων αυτου [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [ηκολουθησεν]{.greek-added} αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και [απο]{.greek-added} περαν του ιορδανου και οι περι τυρον και [σιδωνα]{.greek-omitted} [σιδονα]{.greek-added} πληθος πολυ ακουσαντες οσα εποιει [[εποιη]{.corr}]{.greek-added} ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερηση]{.greek-added} αυτω δια τον οχλον ινα μη [θλιβωσιν]{.greek-omitted} [θληβωσιν]{.greek-added} αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα οταν αυτον [εθεωρει]{.greek-omitted} [εθεωρη]{.greek-added} [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον του ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν [τον]{.greek-added} ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [οις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη δυνασθαι αυτους [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι [εξεστη]{.greek-omitted} [εξεστι]{.greek-added}[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και [οτι]{.greek-omitted} εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν [παραβολαις]{.greek-omitted} [παραβολη]{.greek-added} ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ [εαυτοις]{.greek-added} [εαυτην]{.greek-omitted} [[εαυτης]{.corr}]{.greek-added} [μερισθη]{.greek-omitted} [μερισθησα]{.greek-added} ου [δυναται]{.greek-omitted} [σταθηναι]{.greek-omitted} [σταθησεται]{.greek-added} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [εκεινη]{.greek-omitted}[3:24]{.aside}

και ει ο σατανας [τον]{.greek-added} [σαταναν]{.greek-added} [εκβαλλει]{.greek-added} ανεστη εφ [εαυτον]{.greek-omitted} [εαυτου]{.greek-added} και μεμερισται [και]{.greek-added} ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

[και]{.greek-added} ουδεις δυναται τα σκευη του ισχυρου [αρπασαι]{.greek-added} [[διαρπασαι]{.corr}]{.greek-added} εισελθων εις την οικιαν αυτου [ει]{.greek-added} [διαρπασαι]{.greek-omitted} [εαν]{.greek-omitted} μη πρωτον τον ισχυρον [δηση]{.greek-omitted} [δεση]{.greek-added} και τοτε την [οικειαν]{.greek-added} [οικιαν]{.corr} αυτου [διαρπασ[α]{.unclear}ι]{.greek-added} [διαρπαση]{.corr}[3:27]{.aside}

αμην λεγω υμιν [οτι]{.greek-omitted} παντα [αφεθησεται]{.greek-omitted} τα αμαρτηματα [αφεθησεται]{.greek-added} τοις [[ανθρωποις]{.greek-abbr}]{.greek-added} [υιοις]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} και βλασφημιαι [οσας]{.greek-omitted} [οσα]{.greek-added} αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημιση]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} [αγ[ι]{.unclear}ον]{.greek-added} [ακαθαρτον]{.corr} [εχει]{.greek-omitted} [εχειν]{.greek-added}[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο οχλος περι αυτον ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} εστιν[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο [κηρυσσειν]{.greek-added} [και]{.greek-added} διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον [καθησθαι]{.greek-omitted} [καθησαι]{.greek-added} εν τη θαλασση και πας ο οχλος προς την θαλασσαν [εγγυς]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted}[4:2]{.aside}

[ακουετε]{.greek-omitted} [ιδου]{.greek-omitted} εξηλθεν ο σπειρων του σπειραι [τον]{.greek-added} [σπορον]{.greek-added} [αυτου]{.greek-added}[4:3]{.aside}

και εγενετο εν τω σπειρειν [αυτον]{.greek-added} ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν [αυτο]{.greek-omitted} [αυτον]{.greek-added}[4:4]{.aside}

αλλο δε επεσεν επι [το]{.greek-omitted} [πετρωδες]{.greek-omitted} [τα]{.greek-added} [πετραν]{.greek-added} οπου ουκ ειχεν γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ εδωκεν[4:7]{.aside}

[και]{.greek-omitted} αλλο επεσεν εις την γην την [καλην]{.greek-omitted} [αγαθην]{.greek-added} και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

[και]{.greek-added} οτε [δε]{.greek-omitted} εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι [το]{.greek-omitted} [τα]{.greek-added} [μυστηριον]{.greek-omitted} [μυστηρια]{.greek-added} της βασιλειας [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} εκεινοις δε τοις εξω εν [παραβολαις]{.greek-omitted} [παραβολη]{.greek-added} τα παντα γινεται[4:11]{.aside}

ινα βλεποντες [μη]{.greek-added} [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουσουσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας [γνωσεσθε]{.greek-omitted} [γνωσεσθαι]{.greek-added}[4:13]{.aside}

ο σπειρων τον λογον [σπειρει]{.greek-omitted}[4:14]{.aside}

[ο]{.greek-omitted} [σπειρων]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [σπειρει]{.greek-omitted} [σπηρει]{.greek-added} [[σπειρη]{.corr}]{.greek-added}[4:14 | instance no. 2]{.aside}

[ουτοι]{.greek-omitted} [εισι]{.greek-added} δε [εισιν]{.greek-omitted} [και]{.greek-added} οι παρα την οδον οπου [σπειρεται]{.greek-omitted} [σπηρεται]{.greek-added} ο λογος [και]{.greek-omitted} [οι]{.greek-added} οταν [ακουσωσιν]{.greek-omitted} [ακουσωσωσιν]{.greek-added} ευθεως ερχεται ο σατανας και [αιρει]{.greek-omitted} [αιρη]{.greek-added} τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως [οι]{.greek-omitted} επι τα πετρωδη [σπειρομενοι]{.greek-omitted} [σπειρωμενοι]{.greek-added} [[σπειρωμενα]{.corr}]{.greek-added} [[σπειρωμενοι]{.corr}]{.greek-added} οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας [δεχονται]{.greek-added} [λαμβανουσιν]{.greek-omitted} [αυτον]{.greek-omitted}[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα [γενομενης]{.greek-omitted} [γινωμενης]{.greek-added} θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας [σπειρομενοι]{.greek-omitted} [σπηρομενοι]{.greek-added} οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και [αι]{.greek-omitted} [οι]{.greek-added} περι τα λοιπα [επιθυμιαι]{.greek-omitted} [επ[ε]{.unclear}θυμια]{.greek-added} [εισπορευομεναι]{.greek-omitted} [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος [γινεται]{.greek-omitted} [γινονται]{.greek-added}[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} [τριακοντα]{.greek-omitted} [[λ]{.greek-abbr}]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} [εξηκοντα]{.greek-omitted} [[ξ]{.greek-abbr}]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} [εκατον]{.greek-omitted} [[ρ]{.greek-abbr}]{.greek-added}[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα [υπο]{.greek-omitted} [επι]{.greek-added} τον [μωδιον]{.greek-added} [μοδιον]{.corr} τεθη η υπο την κλινην ουχ ινα [επι]{.greek-omitted} [υπο]{.greek-added} την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ εστιν [τι]{.greek-omitted} κρυπτον ο εαν μη [φανερωθη]{.greek-omitted} [αποκαλυφθη]{.greek-added} ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} [υμιν]{.greek-omitted} [και]{.greek-omitted} [προστεθησεται]{.greek-omitted} υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [εχει]{.greek-added} [εχη]{.corr} δοθησεται αυτω και ος ουκ εχει [και]{.greek-omitted} [ο]{.greek-omitted} [εχει]{.greek-omitted} αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρεαι]{.greek-added} νυκτα και [ημεραν]{.greek-omitted} [ημερα]{.greek-added} και ο σπορος βλαστανη και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

[αυτοματη]{.greek-omitted} [αυτοματι]{.greek-added} γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα [πληρη]{.greek-omitted} [πληρει]{.greek-added} σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι [ομοιωσωμεν]{.greek-omitted} [ωμοιωσωμαι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} [παραβαλλομαι]{.greek-added} αυτην[4:30]{.aside}

ως [κοκκον]{.greek-omitted} [κοκκων]{.greek-added} σιναπεως ος οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} επι της γης [μικροτερον]{.greek-added} [μικροτερος]{.corr} παντων των σπερματων εστιν των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [βλαστηση]{.greek-added} αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα [πατεινα]{.greek-added} [πετεινα]{.corr} του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ [ελαλ[η]{.unclear}]{.greek-added} [ελαλει]{.corr} αυτοις κατ [ιδιαν]{.greek-omitted} [ηδιαν]{.greek-added} δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα [αυτοις]{.greek-added}[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον [παραλαμβανουσιν]{.greek-omitted} [παραλαμβαννουσιν]{.greek-added} αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λελαψ]{.greek-added} ανεμου [μεγαλη]{.greek-omitted} [μεγαλου]{.greek-added} τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλον]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι [τη]{.greek-omitted} [πρυμνη]{.greek-omitted} [πρυμνης]{.greek-added} επι το προσκεφαλαιον [καθευδων]{.greek-omitted} [καθευδον]{.greek-added} και διεγειρουσιν αυτον [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [οτι]{.greek-omitted} [απολλυμεθα]{.greek-omitted}[4:38]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [αυτος]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [πρυμνη]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [προσκεφαλαιον]{.greek-omitted} [καθευδων]{.greek-omitted} [και]{.greek-omitted} [διεγειρουσιν]{.greek-omitted} [αυτον]{.greek-omitted} και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38 | instance no. 2]{.aside}

και [διεγερθεις]{.greek-omitted} [διδιεγερθεις]{.greek-added} [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [πεφημωσε]{.greek-added} και εκοπασεν ο ανεμος και εγενετο [γαληνη]{.greek-omitted} [γαλινη]{.greek-added} μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι [εσται]{.greek-added} [εστε]{.corr} ουτως πως ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} [πιστιν]{.greek-omitted} [πιστην]{.greek-added}[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα [εστιν]{.greek-added} ουτος [εστιν]{.greek-omitted} οτι [και]{.greek-omitted} ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις [την]{.greek-omitted} [χωραν]{.greek-omitted} [το]{.greek-added} [χωριον]{.greek-added} των [γαδαρηνων]{.greek-omitted} [γαδαρινων]{.greek-added}[5:1]{.aside}

και [εξελθοντι]{.greek-omitted} [εξελθον]{.greek-added} [συν]{.greek-added} αυτω εκ του πλοιου ευθεως [απηντησεν]{.greek-omitted} [απηνταισεν]{.greek-added} αυτω εκ των [μνημειων]{.greek-omitted} [μνημιων]{.greek-added} [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον [δησαι]{.greek-omitted} [δαμασαι]{.greek-added}[5:3]{.aside}

δια το αυτον πολλακις [πεδαις]{.greek-omitted} [πεδεσι]{.greek-added} και αλυσεσιν [[αλυσεσι]{.corr}]{.greek-added} δεδεσθαι και [διεσπασθαι]{.greek-omitted} [διασπασθαι]{.greek-added} υπ αυτου τας αλυσεις και τας [παιδας]{.greek-added} [πεδας]{.corr} συντετριφθαι και ουδεις [αυτον]{.greek-omitted} [ισχυεν]{.greek-omitted} [ισχυε]{.greek-added} δαμασαι[5:4]{.aside}

και δια παντος [νυτος]{.greek-added} [νυκτος]{.corr} και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} [διαγων]{.greek-added} και εν τοις μνημασιν [και]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο [μακροθεν]{.greek-omitted} [ακροθεν]{.greek-added} [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη ειπεν τι εμοι και [συ]{.greek-added} [σοι]{.greek-omitted} [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι ονομα και απεκριθη λεγων λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλη]{.greek-added} αυτον πολλα ινα μη [αποστειλη]{.greek-added} αυτους [αποστειλη]{.greek-omitted} εξω της χωρας [εκεινης]{.greek-added}[5:10]{.aside}

ην δε εκει προς [τω]{.greek-omitted} [ορει]{.greek-omitted} [το]{.greek-added} [ορος]{.greek-added} αγελη χοιρων [μεγαλη]{.greek-omitted} βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} τα ακαθαρτα [εισηλθον]{.greek-omitted} [εισηλθεν]{.greek-added} εις τους χοιρους και ωρμησεν η αγελη [των]{.greek-added} [χοιρων]{.greek-added} κατα του [κρημνου]{.greek-omitted} [κρυμνου]{.greek-added} εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσαν]{.greek-added}[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και ανηγγειλαν εις την [πολιν]{.greek-omitted} [πολην]{.greek-added} και εις τους αγρους [και]{.greek-omitted} [εξηλθον]{.greek-omitted} [ιδειν]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [γεγονος]{.greek-omitted}[5:14]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [βοσκοντες]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [εφυγον]{.greek-omitted} [και]{.greek-omitted} [ανηγγειλαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αγρους]{.greek-omitted} και εξηλθον ιδειν [το]{.greek-added} [γεγονως]{.greek-added} [τ]{.greek-supplied}ι εστιν [[εστι]{.corr}]{.greek-added} [το]{.greek-omitted} [γεγονος]{.greek-omitted}[5:14 | instance no. 2]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον [και]{.greek-omitted} ιματισμενον και [σωφρονουντα]{.greek-omitted} [σοφρονουντα]{.greek-added} τον [εσχηκοτα]{.greek-omitted} [εσχικωτα]{.greek-added} τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} [ουκ]{.greek-omitted} αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} [[ηλεησαι]{.corr}]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω [παλιν]{.greek-omitted} εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι [ιαειρος]{.greek-omitted} [ιαιρος]{.greek-added} και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλη]{.greek-added} αυτον [πολλα]{.greek-omitted} λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} [αυτη]{.greek-omitted} τας χειρας [αυτη]{.greek-added} οπως σωθη και ζησεται[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και [συνεθλιβον]{.greek-omitted} [συνεθληβεν]{.greek-added} αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ [αυτης]{.greek-omitted} [αυτοις]{.greek-added} παντα και μηδεν [ωφεληθεισα]{.greek-omitted} [οφεληθησα]{.greek-added} αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα [περι]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [ελθουσα]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [οπισθεν]{.greek-omitted} [ηψατο]{.greek-omitted} [του]{.greek-omitted} [ιματιου]{.greek-omitted} [αυτου]{.greek-omitted}[5:27]{.aside}

[ακουσασα]{.greek-omitted} περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι [εαν]{.greek-added} [μονον]{.greek-added} [καν]{.greek-omitted} [των]{.greek-omitted} [ιματιων]{.greek-omitted} [αυτου]{.greek-omitted} αψωμαι [σωθησομαι]{.greek-omitted} [σωθησωμαι]{.greek-added}[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως [επιγνους]{.greek-added} ο [ιησους]{.greek-abbr} [επιγνους]{.greek-omitted} [την]{.greek-added} εν εαυτω την εξ αυτου δυναμιν [εξελθουσαν]{.greek-omitted} [εεξελθουσαν]{.greek-added} επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη [φοβηθεισα]{.greek-omitted} [φοβηθησα]{.greek-added} και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και [ισθι]{.greek-omitted} [ισθη]{.greek-added} [υγιης]{.greek-omitted} [υγιεις]{.greek-added} απο της μαστιγος σου[5:34]{.aside}

ετι [λαλουτος]{.greek-added} αυτου [λαλουντος]{.greek-omitted} ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλης]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} [ευθεως]{.greek-omitted} ακουσας τον λογον [λαλουμενον]{.greek-omitted} [λεγομενον]{.greek-added} λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω συνακολουθησαι ει μη πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον ιακωβου[5:37]{.aside}

και [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} εις τον οικον του αρχισυναγωγου και θεωρει θορυβον κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβησθαι]{.greek-added} και [κλαιετε]{.greek-omitted} [κλαιεται]{.greek-added} [το]{.greek-omitted} [η]{.greek-added} [παιδιον]{.greek-omitted} [παιδις]{.greek-added} ουκ απεθανεν αλλα [καθευδει]{.greek-omitted} [καθευδη]{.greek-added}[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} [του]{.greek-omitted} [της]{.greek-added} [παιδιου]{.greek-omitted} [παιδος]{.greek-added} και την [μητερα]{.greek-abbr} και τους μετ αυτου και [εισπορευεται]{.greek-omitted} [εισπορευονται]{.greek-added} οπου ην το παιδιον [ανακειμενον]{.greek-omitted} [κατακειμενον]{.greek-added}[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει [αυτη]{.greek-omitted} ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και [περιεπατει]{.greek-omitted} [περιεπατη]{.greek-added} ην γαρ [ως]{.greek-added} ετων δωδεκα [και]{.greek-omitted} [εξεστησαν]{.greek-omitted} [εκστασει]{.greek-omitted} [μεγαλη]{.greek-omitted}[5:42]{.aside}

και [διεστειλατο]{.greek-omitted} [αυτοις]{.greek-omitted} [πολλα]{.greek-omitted} [ινα]{.greek-omitted} [μηδεις]{.greek-omitted} [γνω]{.greek-omitted} [τουτο]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και [ηλθεν]{.greek-omitted} εις την πατριδα αυτου [ηλθεν]{.greek-added} και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτα και τις η σοφια η [δοθεισα]{.greek-omitted} [δοθησα]{.greek-added} αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ [ουτος]{.greek-omitted} [ουτως]{.greek-added} εστιν ο [τεκτων]{.greek-omitted} [ο]{.greek-omitted} [του]{.greek-added} [τεκτονος]{.greek-added} υιος [δε]{.greek-added} μαριας αδελφος [δε]{.greek-omitted} ιακωβου και ιωση και ιουδα και σιμωνος [και]{.greek-omitted} ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} [οτι]{.greek-omitted} ουκ εστιν προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσιν]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας [κωμας]{.greek-omitted} [κομας]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγηλεν]{.greek-added} αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μονον [μη]{.greek-omitted} [και]{.greek-added} πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσεισθε]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει [μενετε]{.greek-omitted} [μενεται]{.greek-added} εως [αν]{.greek-omitted} εξελθητε εκειθεν[6:10]{.aside}

και [οσοι]{.greek-omitted} [οπου]{.greek-added} [αν]{.greek-omitted} [εαν]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι [εκειθεν]{.greek-omitted} [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον χουν τον [υποκατω]{.greek-omitted} [υπο]{.greek-added} των ποδων υμων [εις]{.greek-omitted} [οις]{.greek-added} μαρτυριον αυτοις αμην λεγω υμιν [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [σωδομοις]{.greek-added} η [γομορροις]{.greek-omitted} [γομορρας]{.greek-added} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} η τη πολει εκεινη [εν]{.greek-added} [ημερα]{.greek-added} [κρισεως]{.greek-added}[6:11]{.aside}

και [εξελθοντες]{.greek-omitted} [εξελθοντων]{.greek-added} εκηρυσσον ινα μετανοησωσιν[6:12]{.aside}

και δαιμονια πολλα [εξεβαλλον]{.greek-omitted} [εξεβαλον]{.greek-added} και [ηλειφον]{.greek-omitted} [ηλιφον]{.greek-added} [ελεω]{.greek-added} [ελαιω]{.corr} πολλους αρρωστους και εθεραπευον [πολλους]{.greek-added}[6:13]{.aside}

και ηκουσεν [ηρωδης]{.greek-added} ο βασιλευς [ηρωδης]{.greek-omitted} [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο [βαπτιζων]{.greek-omitted} [βαπτιστης]{.greek-added} εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως [εις]{.greek-omitted} [οις]{.greek-added} των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον [εγω]{.greek-omitted} [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

[αυτος]{.greek-omitted} [ουτος]{.greek-added} γαρ ο ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου [οτι]{.greek-omitted} [αυτην]{.greek-omitted} [εγαμησεν]{.greek-omitted}[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα [φιλιππου]{.greek-added} του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο [γαρ]{.greek-omitted} [δε]{.greek-added} ηρωδης εφοβειτο τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [και]{.greek-added} ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου ηκουεν [[ηκουε]{.corr}]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις [της]{.greek-omitted} [τοις]{.greek-added} γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και [ορχησαμενης]{.greek-omitted} [ορχισαμενης]{.greek-added} και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} και δωσω [[δοσω]{.corr}]{.greek-added} σοι[6:22]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [αιτησης]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted} εως ημισους [[ημισου]{.corr}]{.greek-added} της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι [αιτησομαι]{.greek-omitted} [αιτισωμαι]{.greek-added} η δε ειπεν την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα [ητησατο]{.greek-omitted} [ητισατο]{.greek-added} λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:25]{.aside}

και περιλυπος [γενομενος]{.greek-omitted} [γεναμενος]{.greek-added} ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον [δεδωκεν]{.greek-added} [εδωκεν]{.corr} αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και [εθηκαν]{.greek-omitted} [εθαψαν]{.greek-added} αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω [παντα]{.greek-omitted} [αντα]{.greek-added} [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε [υμεις]{.greek-omitted} αυτοι [υμοις]{.greek-added} κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι [υπαγοντες]{.greek-omitted} [απαγοντες]{.greek-added} πολλοι και ουδε [εις]{.greek-added} [το]{.greek-added} φαγειν ευκαιρουν[6:31]{.aside}

και απηλθον εις ερημον τοπον [τω]{.greek-omitted} [πλοιω]{.greek-omitted} [το]{.greek-added} [πλοιον]{.greek-added} κατ [ιδιαν]{.greek-omitted} [οιδιαν]{.greek-added}[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και [πεζη]{.greek-omitted} [παιζοι]{.greek-added} απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} [αυτους]{.greek-omitted} [αυτος]{.greek-added} και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ιδεν]{.greek-added} [οχλον]{.greek-added} πολυν [οχλον]{.greek-omitted} και [εσπλαγχνισθη]{.greek-omitted} [ευσπλαγχνησθη]{.greek-added} [[ευσπλαχνησθη]{.corr}]{.greek-added} επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν [αυτους]{.greek-omitted} πολλα[6:34]{.aside}

και ηδη ωρας πολλης [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} προσελθοντες αυτω οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα [απελθοντες]{.greek-omitted} [απελθωτες]{.greek-added} εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις αρτους τι [φαγω]{.greek-added} [γαρ]{.greek-omitted} [φαγωσιν]{.greek-omitted} ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν δηναριων διακοσιων αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους [εχετε]{.greek-omitted} [εχεται]{.greek-added} [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} και [ιδεται]{.greek-added} [ιδετε]{.corr} και [γνων]{.greek-added} [γνοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [πεντε]{.greek-omitted} [και]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted}[6:38]{.aside}

[τες]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ποσους]{.greek-omitted} [αρτους]{.greek-omitted} [εχετε]{.greek-omitted} [υπαγετε]{.greek-omitted} [και]{.greek-omitted} [ιδετε]{.greek-omitted} [και]{.greek-omitted} [γνοντες]{.greek-omitted} λεγουσιν [αυτω]{.greek-added} πεντε και δυο ιχθυας[6:38 | instance no. 2]{.aside}

και επεταξεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ανακλιναι παντας συμποσια συμποσια [συμποσια]{.greek-added} επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα [πεντηκοντα]{.greek-omitted} [πεντικοντα]{.greek-added}[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατακλασας]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερησε]{.greek-added} πασιν[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [απο]{.greek-added} [των]{.greek-added} κλασματων δωδεκα κοφινους [πληρεις]{.greek-omitted} [πληρις]{.greek-added} και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βιθσαιδα]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυσας]{.greek-added} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [τους]{.greek-added} [οχλους]{.greek-added}[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος [εναντιος]{.greek-omitted} [εναντιως]{.greek-added} αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασσαν]{.greek-added} εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλη]{.greek-added} μετ αυτων και [λεγει]{.greek-omitted} [ελεγεν]{.greek-added} αυτοις [θαρσειτε]{.greek-omitted} εγω [ειμει]{.greek-added} [ειμι]{.corr} μη [φοβεισθε]{.greek-omitted} [φοβησθαι]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι [τοις]{.greek-omitted} [της]{.greek-added} αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} [πεπωρωμενη]{.greek-omitted} [πεπορωμενη]{.greek-added}[6:52]{.aside}

και διαπερασαντες ηλθον [επι]{.greek-omitted} [εις]{.greek-added} την γην γεννησαρετ και [προσωρμισθησαν]{.greek-omitted} [προσορμησθησαν]{.greek-added}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις [κραββατοις]{.greek-omitted} [κραβαττοις]{.greek-added} τους [κακο[υ]{.unclear}ς]{.greek-added} [κακως]{.corr} εχοντας περιφερειν οπου ηκουον οτι εκει εστιν[6:55]{.aside}

και οπου αν [εισεπορευετο]{.greek-omitted} [εξεπορευετο]{.greek-added} εις κωμας η [εις]{.greek-added} πολεις [η]{.greek-omitted} [αγρους]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [αγοραις]{.greek-omitted} [ετιθουν]{.greek-omitted} [τους]{.greek-omitted} [ασθενουντας]{.greek-omitted} [και]{.greek-omitted} [παρεκαλουν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [καν]{.greek-omitted} [του]{.greek-omitted} [κρασπεδου]{.greek-omitted} [του]{.greek-omitted} [ιματιου]{.greek-omitted} [αυτου]{.greek-omitted} [αψωνται]{.greek-omitted} [και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [ηπτοντο]{.greek-omitted} [αυτου]{.greek-omitted} [εσωζοντο]{.greek-omitted}[6:56]{.aside}

[και]{.greek-omitted} [οπου]{.greek-omitted} [αν]{.greek-omitted} [εισεπορευετο]{.greek-omitted} [εις]{.greek-omitted} [κωμας]{.greek-omitted} [η]{.greek-omitted} [πολεις]{.greek-omitted} η αγρους εν ταις αγοραις [ετιθουν]{.greek-omitted} [επετιθουν]{.greek-added} τους [ασθενουντας]{.greek-omitted} [ασθενεις]{.greek-added} και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} και οσοι αν ηπτοντο αυτου εσωζοντο[6:56 | instance no. 2]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} [ελθοντες]{.greek-omitted} απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν [ανιπτοις]{.greek-omitted} [ανυπτοις]{.greek-added} [χερσιν]{.greek-added} εσθιοντας [αρτον]{.greek-added} [αρτους]{.corr} εμεμψαντο[7:2]{.aside}

οι [γαρ]{.greek-omitted} [δε]{.greek-added} φαρισαιοι και παντες οι [ιουδαιοι]{.greek-omitted} [ιδαιοι]{.greek-added} εαν μη [πυγμη]{.greek-omitted} [νιψωνται]{.greek-omitted} [νιψονται]{.greek-added} τας χειρας ουκ [εσθ[―]{.gap}]{.greek-added} [εσθιουσιν]{.corr} κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη [βαπτισωνται]{.greek-omitted} [νιψονται]{.greek-added} ουκ εσθιουσιν και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

[επειτα]{.greek-omitted} [και]{.greek-added} επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου περιπατουσιν κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων [αλλα]{.greek-omitted} [αλλ]{.greek-added} ανιπτοις χερσιν εσθιουσιν [τον]{.greek-omitted} αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν [αυτω]{.greek-added} [αυτοις]{.corr} οτι καλως προεφητευσεν [ησαιας]{.greek-omitted} [[προεφητευσε]{.corr}]{.greek-added} περι υμων [ησαιας]{.greek-added} των υποκριτων ως γεγραπται [λεγων]{.greek-added} ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω [απεχει]{.greek-omitted} [απεχη]{.greek-added} απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} [κρατειτε]{.greek-omitted} [κρατειται]{.greek-added} την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα [πολλα]{.greek-added} παρομοια [ποιειται]{.greek-added} [τοιαυτα]{.greek-omitted} [πολλα]{.greek-omitted} [ποιειτε]{.corr}[7:8]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} καλως [αθετειτε]{.greek-omitted} [αθετητε]{.greek-added} την εντολην του [θεου]{.greek-abbr} ινα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων [τηρησητε]{.greek-omitted} [τηρησηται]{.greek-added}[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε [λεγεται]{.greek-added} [λεγετε]{.corr} εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} [αυτου]{.greek-added} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου [ωφεληθης]{.greek-omitted} [ωφεληθη]{.greek-added}[7:11]{.aside}

και [ουκετι]{.greek-omitted} [αφιετε]{.greek-omitted} [ουκ]{.greek-added} [επ]{.greek-added} αυτον [αφιεται]{.greek-added} ουδεν [ποιησαι]{.greek-omitted} [ποιειτε]{.greek-added} τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωση]{.greek-added} υμων η [παρεδωκατε]{.greek-omitted} [παραδεδωκατε]{.greek-added} και παρομοια τοιαυτα πολλα [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added}[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ελεγεν αυτοις [ακουετε]{.greek-omitted} [ακουσατε]{.greek-added} μου παντες και [συνιετε]{.greek-omitted} [συνιεται]{.greek-added}[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα [απ]{.greek-omitted} [δι]{.greek-added} αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται [αυτου]{.greek-omitted} περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι [εστε]{.greek-omitted} [εσται]{.greek-added} ου [νοειτε]{.greek-omitted} [νοειται]{.greek-added} οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται [κοινωσαι]{.greek-added} αυτον [κοινωσαι]{.greek-omitted}[7:18]{.aside}

οτι ουκ εισπορευεται [αυτου]{.greek-omitted} [αυτω]{.greek-added} εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο [κοινοι]{.greek-omitted} [κοινει]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας [των]{.greek-omitted} [του]{.greek-added} [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος ασελγεια οφθαλμος πονηρος βλασφημια [υπερηφανια]{.greek-omitted} [υπεριφανια]{.greek-added} αφροσυνη[7:22]{.aside}

[ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου [ης]{.greek-omitted} [ως]{.greek-added} ειχεν το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη [ελληνις]{.greek-omitted} [ελλινις]{.greek-added} [συρος]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω [γενει]{.greek-omitted} [γενη]{.greek-added} και [ηρωτα]{.greek-omitted} [ηρωτησεν]{.greek-added} αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκ]{.greek-omitted} [εκβαλλει]{.greek-added} [απο]{.greek-added} της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} ειπεν αυτη αφες πρωτον χορτασθηναι [τα]{.greek-omitted} [τεκνα]{.greek-omitted} ου γαρ καλον εστιν [λαβειν]{.greek-omitted} [λαβη]{.greek-added} τον αρτον [των]{.greek-omitted} [τεκνων]{.greek-omitted} [τοις]{.greek-added} [τεκνοις]{.greek-added} και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη [λεγουσα]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των [ψιχιων]{.greek-omitted} [ψυχιων]{.greek-added} των [παιδιων]{.greek-omitted} [παιδων]{.greek-added}[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξελυληθεν]{.greek-added} το δαιμονιον [εκ]{.greek-omitted} [απο]{.greek-added} της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον [εξεληλυθος]{.greek-omitted} [εξελυληθως]{.greek-added} και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την θαλασσαν της γαλιλαιας ανα [μεσον]{.greek-omitted} [μεσων]{.greek-added} των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα [επιθει]{.greek-added} [επιθη]{.corr} αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον [απο]{.greek-omitted} [εκ]{.greek-added} του οχλου [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω [εφαθα]{.greek-added} [εφφαθα]{.corr} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις [διεστελλετο]{.greek-omitted} [διεστηλατο]{.greek-added} μαλλον [και]{.greek-added} περισσοτερον [εκηρυσσον]{.greek-omitted} [εκηρυττον]{.greek-added}[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα πεποιηκεν [[πεποιηκε]{.corr}]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν [εκειναις]{.greek-omitted} [δε]{.greek-added} ταις ημεραις [εκειναις]{.greek-added} [παν]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου οντος και μη εχοντων τι φαγωσιν προσκαλεσαμενος ο [ιησους]{.greek-abbr} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

[σπλαγχνιζομαι]{.greek-omitted} [σπλαχνιζομαι]{.greek-added} επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις [τον]{.greek-added} οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκον]{.greek-added}[8:3]{.aside}

και απεκριθησαν [αυτω]{.greek-omitted} οι μαθηται αυτου ποθεν τουτους [δυνησεται]{.greek-omitted} [δυνησηται]{.greek-added} τις ωδε [εν]{.greek-added} [ερημια]{.greek-added} χορτασαι αρτων [επ]{.greek-omitted} [ερημιας]{.greek-omitted}[8:4]{.aside}

και [επηρωτα]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτους ποσους [εχετε]{.greek-omitted} αρτους [εχεται]{.greek-added} οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγηλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους [και]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα παραθωσιν και [παρεθηκαν]{.greek-omitted} [παρεθηκε]{.greek-added} τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και [αυτα]{.greek-added} ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} [και]{.greek-omitted} [αυτα]{.greek-omitted}[8:7]{.aside}

εφαγον δε [παντες]{.greek-added} και εχορτασθησαν και ηραν περισσευματα κλασματων επτα [σπυριδας]{.greek-omitted} [σπηριδας]{.greek-added}[8:8]{.aside}

ησαν δε οι φαγοντες [ως]{.greek-omitted} [ωσει]{.greek-added} τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και ευθεως εμβας εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν [αυτον]{.greek-added} [αυτω]{.corr} ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και [αναστεναξας]{.greek-omitted} [στεναξας]{.greek-added} τω [πνευματι]{.greek-abbr} αυτου λεγει [τι]{.greek-omitted} [οτι]{.greek-added} η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} λαβειν αρτους και [μηδενα]{.greek-added} [ει]{.greek-omitted} [μη]{.greek-omitted} [ενα]{.greek-omitted} αρτον [ουκ]{.greek-omitted} ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων [ορατε]{.greek-omitted} [οραται]{.greek-added} [και]{.greek-added} [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς [αλληλους]{.greek-omitted} [αλλοιλους]{.greek-added} λεγοντες οτι αρτους ουκ [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added}[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} οτι αρτους ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} ουπω [νοειτε]{.greek-omitted} [νοειται]{.greek-added} ουδε [συνιετε]{.greek-omitted} [συνιεται]{.greek-added} ετι [πεπωρωμενην]{.greek-omitted} [πεπορωμενην]{.greek-added} [εχετε]{.greek-omitted} [εχεται]{.greek-added} την καρδιαν [υμων]{.greek-omitted}[8:17]{.aside}

οφθαλμους εχοντες ου [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} και ωτα εχοντες ουκ ακουετε και ου [μνημονευετε]{.greek-omitted} [μνημονευεται]{.greek-added}[8:18]{.aside}

[οτε]{.greek-omitted} [οτι]{.greek-added} τους [πεντε]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} αρτους εκλασα [εις]{.greek-omitted} [ειτα]{.greek-added} τους πεντακισχιλιους [και]{.greek-added} ποσους κοφινους [πληρεις]{.greek-omitted} [πληρις]{.greek-added} κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους [[ζ]{.greek-abbr}]{.greek-added} [επτα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-added} τετρακισχιλιους [ποσων]{.greek-omitted} [ποσους]{.greek-added} σπυριδων [πληρωματα]{.greek-omitted} κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως ου [συνιετε]{.greek-omitted} [συνιεται]{.greek-added}[8:21]{.aside}

και [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} [εις]{.greek-omitted} [ις]{.greek-added} [βηθσαιδαν]{.greek-omitted} [βιθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος [αυτου]{.greek-added} του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις [και]{.greek-added} τας χειρας [επ]{.greek-added} αυτω επηρωτα αυτον ει τι [βλεπει]{.greek-omitted} [βλεπειν]{.greek-added}[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλ[ε]{.unclear}ψαι]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

[και]{.greek-omitted} [απεστειλεν]{.corr} [αυτον]{.corr} [εις]{.corr} [τον]{.corr} [οικον]{.corr} [αυτου]{.corr} [λεγων]{.corr} [μηδε]{.corr} [εις]{.corr} [την]{.corr} [κωμην]{.corr} [εισελθης]{.corr} [μηδε]{.corr} [ειπης]{.corr} [τινι]{.corr} [εν]{.corr} [τη]{.corr} [κωμη]{.corr}[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας [καισαρειας]{.greek-omitted} [καισαριας]{.greek-added} της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγουσι]{.greek-added} περι αυτου[8:30]{.aside}

και [ηρξαντο]{.greek-added} [ηρξατο]{.corr} διδασκειν αυτους οτι δει τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και των αρχιερεων και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον [ελαλη]{.greek-added} [ελαλει]{.corr} και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετημησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθητο]{.greek-added} [ακολουθειτω]{.greek-omitted} [[ακολουθητω]{.corr}]{.greek-added} μοι[8:34]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} θελη την ψυχην αυτου σωσαι απολεσ[ει]{.unclear} [[απολεση]{.corr}]{.greek-added} αυτην ος δ αν απολεση την [ψυχην]{.greek-added} [αυτου]{.greek-added} [εαυτου]{.corr} [ψυχην]{.greek-omitted} ενεκεν εμου και του ευαγγελιου ουτος σωσει αυτην[8:35]{.aside}

τι γαρ [ωφελησει]{.greek-omitted} [ωφεληση]{.greek-added} [ανθρωπον]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} εαν κερδηση τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι [δωσει]{.greek-omitted} [δοση]{.greek-added} [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη [μοιχαλιδι]{.greek-omitted} [μοιχαλλιδι]{.greek-added} και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου [μετα]{.greek-omitted} [μετ]{.greek-added} [των]{.corr} αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις [αμην]{.greek-omitted} [αμιν]{.greek-added} λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των [οδε]{.greek-added} [ωδε]{.corr} εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον [[ιω]{.greek-abbr}]{.greek-added} [και]{.greek-added} [τον]{.greek-added} ιακωβον [και]{.greek-omitted} [ιωαννην]{.greek-omitted} και αναφερει αυτους εις ορος [υψηλον]{.greek-omitted} [υψυλον]{.greek-added} κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν [ως]{.greek-omitted} [ωσει]{.greek-added} χιων οια γναφευς επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν μωση και ησαν [συλλαλουντες]{.greek-omitted} [λαλουντες]{.greek-added} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας [ωδε]{.greek-omitted} [οδε]{.greek-added} ειναι [και]{.greek-omitted} ποιησωμεν σκηνας [ενταυθα]{.greek-added} τρεις [σοι]{.greek-omitted} [συ]{.greek-added} μιαν και μωση μιαν και [ηλιαν]{.greek-added} [ηλια]{.corr} μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ [εκφοβοι]{.greek-omitted} [εμφοβοι]{.greek-added}[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης [λεγουσα]{.greek-added} ουτος εστιν ο υιος μου ο αγαπητος αυτου [ακουετε]{.greek-omitted} [ακουεται]{.greek-added}[9:7]{.aside}

και [εξαπινα]{.greek-omitted} [εξαπεινα]{.greek-added} περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ [εαυτον]{.greek-added} [εαυτων]{.corr}[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους [διεστειλατο]{.greek-omitted} [διεστηλατο]{.greek-added} αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} [διηγησονται]{.greek-added} α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι [γραμματεις]{.greek-omitted} [γραμματοις]{.greek-added} οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις [ηλιας]{.greek-omitted} [ηλιαν]{.greek-added} μεν [ελθων]{.greek-omitted} [δει]{.greek-added} [ελθειν]{.greek-added} πρωτον [και]{.greek-added} [αποκαθιστα]{.greek-omitted} [αποκαθισταν]{.greek-added} παντα και πως γε[γ]{.greek-supplied}ραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} [εγω]{.greek-added} λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [ηλθεν]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ [αυτον]{.greek-omitted} [αυτω]{.greek-added}[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι [αυτους]{.greek-omitted} [αυτου]{.greek-added} και γραμματεις [συζητουντας]{.greek-omitted} [συζητουντες]{.greek-added} αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι [συζητειτε]{.greek-omitted} [συζητειται]{.greek-added} προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει [και]{.greek-omitted} [τριζει]{.greek-omitted} τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-added} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} ω γενεα απιστος εως ποτε [προς]{.greek-omitted} [υμας]{.greek-omitted} [εσομαι]{.greek-omitted} [εως]{.greek-omitted} [ποτε]{.greek-omitted} [ανεξομαι]{.greek-omitted} [ανεξωμαι]{.greek-added} υμων [φερετε]{.greek-omitted} [φερεται]{.greek-added} αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} [εσπαραξεν]{.greek-omitted} [εσπαραξε]{.greek-added} [αυτον]{.greek-omitted} και πεσων επι [της]{.greek-omitted} [γης]{.greek-omitted} [την]{.greek-added} [γην]{.greek-added} [εκυλιετο]{.greek-omitted} [εκυλυετο]{.greek-added} αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επιρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} [αυτη[ς]{.unclear}]{.greek-added} [αυτου]{.corr} ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παιδιοθεν]{.greek-omitted} [παιδιωθεν]{.greek-added}[9:21]{.aside}

και πολλακις αυτον και εις το πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις [τα]{.greek-added} υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν [σπλαγχνισθεις]{.greek-omitted} [σπλαχνισθης]{.greek-added} εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω [πιστευοντι]{.greek-omitted}[9:23]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [το]{.greek-omitted} [ει]{.greek-omitted} [δυνασαι]{.greek-omitted} [πιστευσαι]{.greek-omitted} [παντα]{.greek-omitted} [δυνατα]{.greek-omitted} [τω]{.greek-omitted} πιστευοντι[9:23 | instance no. 2]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [μου]{.greek-omitted} [βοηθη]{.greek-added} [μοι]{.greek-added} τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [συντρεχει]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετημησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και [κωφον]{.greek-omitted} [κοφον]{.greek-added} εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος [ηγειρεν]{.greek-omitted} [ηγηρεν]{.greek-added} αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν [δια]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ημεις ουκ [ηδυνηθημεν]{.greek-omitted} [ηδυνηθειμεν]{.greek-added} εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος [εν]{.greek-omitted} ουδενι [δυναται]{.greek-omitted} [δυνατε]{.greek-added} εξελθειν ει μη εν προσευχη και [νηστεια]{.greek-omitted} [νηστια]{.greek-added}[9:29]{.aside}

και [εκειθεν]{.greek-omitted} εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και [ηλθεν]{.greek-omitted} [απηλθεν]{.greek-added} εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους [διελογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added}[9:33]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εστω]{.greek-added} [εσται]{.greek-omitted} [παντων]{.greek-omitted} [εσχατος]{.greek-omitted} [και]{.greek-omitted} παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και [εναγκαλισαμενος]{.greek-omitted} [ενηγκαλησαμενος]{.greek-added} αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον [αποστειλαντα]{.greek-omitted} [πεμψαντα]{.greek-added} με[9:37]{.aside}

[απεκριθει]{.greek-added} [απεκριθη]{.corr} δε αυτω [ιωαννης]{.greek-omitted} [ο]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} λεγων διδασκαλε [ειδομεν]{.greek-omitted} [οιδαμεν]{.greek-added} [τινα]{.greek-omitted} [τινας]{.greek-added} τω ονοματι σου [εκβαλλοντα]{.greek-omitted} [εκβαλλοντας]{.greek-added} δαιμονια ος ουκ [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} ημιν και εκωλυσαμεν αυτον [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} αυτον ουδεις γαρ εστιν ος [ουκ]{.greek-added} ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ εστιν καθ [υμων]{.greek-omitted} [ημων]{.greek-added} υπερ [υμων]{.greek-omitted} [ημων]{.greek-added} εστιν[9:40]{.aside}

ος γαρ [αν]{.greek-omitted} ποτιση υμας ποτηριον υδατος εν ονοματι μου [οτι]{.greek-omitted} [οτε]{.greek-added} [χριστου]{.greek-abbr} εστε αμην [γαρ]{.greek-added} λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος εαν [σκανδαλ[η]{.unclear}ση]{.greek-added} [σκανδαλιση]{.corr} ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} [μαλλον]{.greek-added} αυτω [μαλλον]{.greek-omitted} ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [σκανδαλιζη]{.greek-omitted} [σκανδαληση]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι εστιν [καλλον]{.greek-added} [κυλλον]{.corr} εις την ζωην εισελθειν η τας δυο χειρας εχοντα [απελθειν]{.greek-omitted} [βληθηναι]{.greek-added} εις την γεενναν [εις]{.greek-omitted} [το]{.greek-omitted} [του]{.greek-added} [πυρ]{.greek-omitted} [πυρος]{.greek-added} [το]{.greek-omitted} [ασβεστον]{.greek-omitted}[9:43]{.aside}

και εαν ο οφθαλμος σου [σκανδαλιζη]{.greek-omitted} [σκανδαλιση]{.greek-added} σε εκβαλε αυτον καλον σοι εστιν μονοφθαλμον [εισελθειν]{.greek-omitted} εις την βασιλειαν του [θεου]{.greek-abbr} [εισελθειν]{.greek-added} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκοληξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι [αλισθησεται]{.greek-omitted} [δοκιμασθησεται]{.greek-added} και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν [δε]{.greek-omitted} το αλας αναλον [γενηται]{.greek-omitted} [γενοιται]{.greek-added} εν τινι αυτο [αρτυσετε]{.greek-omitted} [εχετε]{.greek-omitted} [αρτησηται]{.greek-added} [εχεται]{.greek-added} εν εαυτοις αλας και [ειρη]{.greek-added} [ειρηνευετε]{.greek-omitted} [εν]{.greek-omitted} [αλληλοις]{.greek-omitted}[9:50]{.aside}

[νευεται]{.greek-added} [καλον]{.greek-omitted} [το]{.greek-omitted} [αλας]{.greek-omitted} [εαν]{.greek-omitted} [δε]{.greek-omitted} [το]{.greek-omitted} [αλας]{.greek-omitted} [αναλον]{.greek-omitted} [γενηται]{.greek-omitted} [εν]{.greek-omitted} [τινι]{.greek-omitted} [αυτο]{.greek-omitted} [αρτυσετε]{.greek-omitted} [εχετε]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} [αλας]{.greek-omitted} [και]{.greek-omitted} [ειρηνευετε]{.greek-omitted} [εν]{.greek-omitted} αλληλοις[9:50 | instance no. 2]{.aside}

### Chapter 10

[και]{.greek-added} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} αναστας ερχεται εις τα [ορια]{.greek-omitted} [ορεια]{.greek-added} της ιουδαιας δια [του]{.greek-omitted} [το]{.greek-added} περαν του ιορδανου και συμπορευονται παλιν οχλοι [πολλοι]{.greek-added} προς αυτον και ως [ειωθει]{.greek-omitted} [ειωθη]{.greek-added} παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε [αποκριθεις]{.greek-omitted} [αποκρηθεις]{.greek-added} ειπεν αυτοις τι υμιν ενετειλατο μωσης[10:3]{.aside}

[οι]{.greek-omitted} [ει]{.greek-added} δε ειπον μωσης [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων [εγραψεν]{.greek-omitted} [εγραψε]{.greek-added} [υμιν]{.greek-omitted} την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

[ωστε]{.greek-added} ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταληψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και [προσκολληθησεται]{.greek-omitted} [προσκωλληθησεται]{.greek-added} προς την [γυναικα]{.greek-omitted} [γυναι]{.greek-added} [αυτου]{.greek-omitted}[10:7]{.aside}

[κα]{.greek-added} [ενεκεν]{.greek-omitted} [τουτου]{.greek-omitted} [καταλειψει]{.greek-omitted} [ανθρωπος]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} αυτου [και]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [και]{.greek-omitted} [προσκολληθησεται]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [αυτου]{.greek-omitted}[10:7 | instance no. 2]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν [ο]{.greek-omitted} [οι]{.greek-added} [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη [χωριζεσθ]{.greek-added} [χωριζετω]{.greek-omitted} [[χωριζετο]{.corr}]{.greek-added}[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι του αυτου επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και [γαμηθη]{.greek-omitted} [κοιμηθη]{.greek-added} αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται [επετιμων]{.greek-omitted} [επετημων]{.greek-added} τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} αυτα των γαρ τοιουτων εστιν η βασιλεια [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και [εναγκαλισαμενος]{.greek-omitted} [ενηγκαλησαμενος]{.greek-added} αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηυλογει]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων [εις]{.greek-omitted} [τις]{.greek-added} [πλουσιος]{.greek-added} και γονυπετησας [αυτον]{.greek-omitted} επηρωτα αυτον [λεγων]{.greek-added} διδασκαλε αγαθε τι [ποιησω]{.greek-omitted} [αγαθον]{.greek-added} ινα ζωην αιωνιον [κληρονομησω]{.greek-omitted} [κληρονομισω]{.greek-added}[10:17]{.aside}

ο δε [ο]{.greek-added} [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε [αποκρηθεις]{.greek-added} [αποκριθεις]{.corr} [ει]{.greek-added} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ταυτα]{.greek-omitted} [παντα]{.greek-omitted} [εφυλαξαμην]{.greek-omitted} [εκ]{.greek-omitted} [νεοτητος]{.greek-omitted} [μου]{.greek-omitted}[10:20]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [πεν]{.greek-added} αυτω [διδασκαλε]{.greek-omitted} ταυτα παντα εφυλαξαμην εκ νεοτητος μου [τι]{.greek-added} [ετι]{.greek-added} [υστερω]{.greek-added}[10:20 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-omitted} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν σοι υστερει υπαγε οσα εχεις [πωλησον]{.greek-omitted} [πωλυσον]{.greek-added} και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} και δευρο [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι αρας τον [σταυρον]{.greek-abbr} [σου]{.greek-added}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως [οι]{.greek-omitted} [ο]{.greek-added} τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται [εθαμβουντο]{.greek-omitted} [εθαυμαζον]{.greek-added} επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις [τεκνα]{.greek-omitted} πως [δυσκολον]{.greek-omitted} [δυσκολως]{.greek-added} [εστιν]{.greek-omitted} τους [πεποιθοτας]{.greek-omitted} [πεποιθωτας]{.greek-added} επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου [ημεις]{.greek-omitted} [ημοις]{.greek-added} αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και [αδελφας]{.greek-added} [αδελφους]{.corr} και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω [ερχωμενω]{.greek-added} [ερχομενω]{.corr} ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο [και]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} [παραλαβων]{.greek-omitted} [παλιν]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγειν]{.greek-omitted} [τα]{.greek-omitted} [μελλοντα]{.greek-omitted} [αυτω]{.greek-omitted} [συμβαινειν]{.greek-omitted}[10:32]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [αναβαινοντες]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} και [ακολουθουντες]{.greek-added} [ην]{.greek-omitted} [προαγων]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} εθαμβουντο και [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} παραλαβων [παλιν]{.greek-omitted} τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ηρξατο [αυτοις]{.greek-omitted} λεγειν τα μελλοντα αυτω συμβαινειν[10:32 | instance no. 2]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [τοις]{.greek-added} [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και [παραδωσουσιν]{.greek-omitted} [παραδοσουσιν]{.greek-added} αυτον τοις εθνεσιν[10:33]{.aside}

και [εμπαιξουσιν]{.greek-omitted} [εμπεξουσιν]{.greek-added} αυτω [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αυτον]{.greek-omitted} και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και [[ιω]{.greek-abbr}]{.greek-added} [ιωαννης]{.greek-omitted} [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες [θελωμεν]{.greek-added} διδασκαλε [θελομεν]{.greek-omitted} ινα ο εαν αιτησωμεν [ποιησης]{.greek-omitted} [ποιησεις]{.greek-added} ημιν[10:35]{.aside}

ο δε ειπεν [αυτοις]{.greek-omitted} τι [θελετε]{.greek-omitted} [θελεται]{.greek-added} ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω [δος]{.greek-omitted} [ημιν]{.greek-omitted} ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ [[η]{.unclear}δαται]{.greek-added} [οιδατε]{.greek-omitted} [[ιδατε]{.corr}]{.greek-added} τι [αιτεισθαι]{.greek-added} [αιτεισθε]{.corr} δυνασθε [ποιειν]{.greek-added} [πιειν]{.corr} το ποτηριον ο εγω πινω και το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζωμαι]{.greek-added} βαπτισθηναι[10:38]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} δυναμεθα [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [το]{.greek-omitted} [μεν]{.greek-omitted} [ποτηριον]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [πινω]{.greek-omitted} [πιεσθε]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [βαπτισμα]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [βαπτιζομαι]{.greek-omitted} [βαπτισθησεσθε]{.greek-omitted}[10:39]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [δυναμεθα]{.greek-omitted} ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω [πιεσθε]{.greek-omitted} [πιεσθαι]{.greek-added} και το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζωμαι]{.greek-added} [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added}[10:39 | instance no. 2]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ ευωνυμων ουκ εστιν εμον δουναι αλλ οις [ητοιμασται]{.greek-omitted} [ητιμασται]{.greek-added}[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο [λεγειν]{.greek-added} αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις [οιδατε]{.greek-omitted} [ιδατε]{.greek-added} οτι οι δοκουντες [αρχειν]{.greek-omitted} [αρχην]{.greek-added} των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριευσουσιν]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε [εσται]{.greek-omitted} [εστι]{.greek-added} εν υμιν αλλ ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} γενεσθαι μεγας [εστω]{.greek-added} [εν]{.greek-omitted} [υμιν]{.greek-omitted} [εσται]{.greek-omitted} υμων διακονος[10:43]{.aside}

και ος εαν θελη [υμων]{.greek-omitted} [ημων]{.greek-added} γενεσθαι πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται [εις]{.greek-omitted} [ει]{.greek-added} [ιεριχω]{.greek-omitted} [και]{.greek-omitted} [εκπορευομενου]{.greek-omitted} [αυτου]{.greek-omitted} [απο]{.greek-omitted} ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος [ονοματι]{.greek-added} [ο]{.greek-omitted} [τυφλος]{.greek-omitted} εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} [τον]{.greek-omitted} [τυφλον]{.greek-omitted} [τω]{.greek-added} [τυφλω]{.greek-added} λεγοντες [αυτω]{.greek-omitted} θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} [φωνει]{.greek-omitted} [φωνη]{.greek-added} σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

[και]{.greek-added} ο [δε]{.greek-omitted} [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} εις [βηθσφαγη]{.greek-omitted} [βιθσφαγη]{.greek-added} και [βηθανιαν]{.greek-omitted} [βιθανιαν]{.greek-added} [προς]{.greek-omitted} [εις]{.greek-added} το [ορος]{.greek-omitted} [των]{.greek-omitted} [ελαιων]{.greek-omitted} [αποστελλει]{.greek-omitted} [δυο]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted}[11:1]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [εγγιζουσιν]{.greek-omitted} [εις]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [εις]{.greek-omitted} [βηθσφαγη]{.greek-omitted} [και]{.greek-omitted} [βηθανιαν]{.greek-omitted} [προς]{.greek-omitted} [το]{.greek-omitted} ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1 | instance no. 2]{.aside}

και λεγει αυτοις υπαγετε εις την [κωμην]{.greek-omitted} [την]{.greek-omitted} κατεναντι υμων [πολιν]{.greek-added} και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} πωλον δεδεμενον εφ ον [ουπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκε]{.greek-added} [και]{.greek-added} λυσαντες αυτον [αγαγετε]{.greek-omitted} [αγαγεται]{.greek-added}[11:2]{.aside}

και εαν τις υμιν ειπη τι [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added} τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον [τον]{.greek-added} πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων [ελεγον]{.greek-omitted} [λεγουσιν]{.greek-added} αυτοις τι [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον [[επ]{.corr}]{.greek-added} αυτω τα ιματια αυτων και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια [και]{.greek-added} [εκαθησεν]{.greek-added} αυτων εστρωσαν [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδω]{.greek-added} [οδον]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [εκοπτον]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [δενδρων]{.greek-omitted} [και]{.greek-omitted} [εστρωννυον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

[και]{.greek-added} ευλογημενη η [ερχομενη]{.greek-omitted} βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} [ωσαννα]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [υψιστοις]{.greek-omitted}[11:10]{.aside}

και εισηλθεν [εις]{.greek-omitted} [ει]{.greek-added} ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος [παντα]{.greek-omitted} [παντας]{.greek-added} οψιας ηδη ουσης [της]{.greek-omitted} [ωρας]{.greek-omitted} εξηλθεν εις [βηθανιαν]{.greek-omitted} [βιθανιαν]{.greek-added} μετα των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[11:11]{.aside}

και τη επαυριον εξελθοντων [αυτων]{.greek-omitted} απο [βηθανιας]{.greek-omitted} [βιθανιας]{.greek-added} [επεινασεν]{.greek-omitted} [επινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην [μιαν]{.greek-added} μακροθεν εχουσαν [φυλλα]{.greek-omitted} [ηλθεν]{.greek-omitted} [ει]{.greek-omitted} [αρα]{.greek-omitted} [ευρησει]{.greek-omitted} [τι]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [και]{.greek-omitted} [ελθων]{.greek-omitted} [επ]{.greek-omitted} [αυτην]{.greek-omitted} [ουδεν]{.greek-omitted} [ευρεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου [καρπος]{.greek-added} εις τον αιωνα μηδεις καρπον [φαγοι]{.greek-omitted} [φαγη]{.greek-added} και ηκουον οι μαθηται [αυτου]{.greek-omitted}[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους [πωλουντας]{.greek-omitted} [πολουντας]{.greek-added} και αγοραζοντας εν τω ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [καθεδρας]{.greek-omitted} [των]{.greek-omitted} πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις [ου]{.greek-omitted} γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε [εποιησατε]{.greek-omitted} [εποιησαται]{.greek-added} αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [αρχιερεις]{.greek-added} [και]{.greek-added} γραμματεις [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ [αυτον]{.greek-omitted} οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε εγενετο [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος [λε]{.greek-added} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} [ιδε]{.greek-omitted} [η]{.greek-omitted} [συκη]{.greek-omitted} [ην]{.greek-omitted} [κατηρασω]{.greek-omitted} [εξηρανται]{.greek-omitted}[11:21]{.aside}

[και]{.greek-omitted} [αναμνησθεις]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [λεγει]{.greek-omitted} [γει]{.greek-added} αυτω ραββι ιδε [η]{.greek-omitted} [την]{.greek-added} [συκη]{.greek-omitted} [συκην]{.greek-added} ην κατηρασω [εξηρανται]{.greek-omitted} [εξηρανθη]{.greek-added}[11:21 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις [εχεται]{.greek-added} [εχετε]{.corr} πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα πιστευση οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθαι]{.greek-added} [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} οτι [λαμβανετε]{.greek-omitted} [λαμβανεται]{.greek-added} και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκετε]{.greek-added} προσευχομενοι αφιετε ει τι [εχετε]{.greek-omitted} [εχεται]{.greek-added} κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} [αφησει]{.greek-omitted} [αφηση]{.greek-added} τα παραπτωματα υμων[11:26]{.aside}

και ερχονται [προσβ]{.greek-added} [παλιν]{.corr} εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις [και]{.greek-omitted} [τις]{.greek-omitted} [σοι]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [ταυτην]{.greek-omitted} [εδωκεν]{.greek-omitted} [ινα]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιης]{.greek-omitted}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [λογον]{.greek-added} [ενα]{.greek-added} και [εγω]{.greek-omitted} [ενα]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [αποκριθητε]{.greek-omitted} [αποκριθητι]{.greek-added} [[αποκριθηται]{.corr}]{.greek-added} μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} [αποκριθητε]{.greek-omitted} [αποκριθηται]{.greek-added} μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} [προς]{.greek-omitted} [εν]{.greek-added} [εαυτους]{.greek-omitted} [εαυτοις]{.greek-added} λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει [ημιν]{.greek-added} δια τι [ουν]{.greek-omitted} ουκ [επιστευσατε]{.greek-omitted} [επιστευσαται]{.greek-added} αυτω[11:31]{.aside}

[αλλ]{.greek-omitted} [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} [εφοβουντο]{.greek-omitted} [φοβουμεθα]{.greek-added} τον [λαον]{.greek-omitted} [οχλον]{.greek-added} απαντες γαρ ειχον τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες λεγουσι[ν]{.unclear} [[λεγουσι]{.corr}]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστηλεν]{.greek-added} προς τους γεωργους [ενα]{.greek-added} [δουλον]{.greek-added} τω καιρω [δουλον]{.greek-omitted} ινα παρα [τω]{.greek-added} [καιρω]{.greek-added} [των]{.corr} [γεωργων]{.corr} λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε [γεωργοι]{.greek-added} λαβοντες αυτον εδειραν και [απεστειλαν]{.greek-omitted} [απεστηλαν]{.greek-added} [κενον]{.greek-omitted} [αυτον]{.greek-added} [καινον]{.greek-added}[12:3]{.aside}

και [παλιν]{.greek-omitted} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντος]{.greek-added} εκεφαλαιωσαν και [απεστειλαν]{.greek-omitted} [απεστηλαν]{.greek-added} ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους αλλους τους μεν [δεροντας]{.greek-added} [δεροντες]{.corr} τους δε [αποκτενοντες]{.greek-omitted} [αποκτειναντες]{.greek-added}[12:5]{.aside}

ετι ουν ενα υιον εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον προς αυτους [εσχατον]{.greek-omitted} λεγων [ο]{.greek-added} [οτι]{.greek-omitted} [εντραπησονται]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [μου]{.greek-omitted}[12:6]{.aside}

[ετι]{.greek-omitted} [τι]{.greek-added} [ουν]{.greek-omitted} [ενα]{.greek-omitted} [υιον]{.greek-omitted} [εχων]{.greek-omitted} [αγαπητον]{.greek-omitted} [αυτου]{.greek-omitted} [απεστειλεν]{.greek-omitted} [και]{.greek-omitted} [αυτον]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [εσχατον]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} εντραπησονται τον [υιον]{.greek-abbr} μου[12:6 | instance no. 2]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε [αποκτεινομεν]{.greek-added} [αποκτεινωμεν]{.corr} αυτον και ημων εσται η κληρονομια [αυτου]{.greek-added}[12:7]{.aside}

και [λαβοντες]{.greek-omitted} [λαβων]{.greek-added} αυτον απεκτειναν και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του [αμπελνος]{.greek-added} [αμπελωνος]{.corr} ελευσεται και [απολεσει]{.greek-omitted} [απολεση]{.greek-added} [[απωλεση]{.corr}]{.greek-added} τους γεωργους [εκεινους]{.greek-added} και [δοσει]{.greek-added} [δ[ω]{.unclear}σει]{.corr} τον αμπελωνα [γεωργοις]{.greek-added} αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδωκημασαν]{.greek-added} οι οικοδομουντες ουτος εγενηθη εις κεφαλην [γωνιας]{.greek-omitted} [γονιας]{.greek-added}[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις [ημων]{.greek-omitted} [υμων]{.greek-added}[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ [οτι]{.corr} [προς]{.greek-omitted} αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσοι]{.greek-added} λογω[12:13]{.aside}

οι δε [ελθοντες]{.greek-omitted} λεγουσιν αυτω διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και ου [μελει]{.greek-omitted} [μελλη]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις εξεστιν [κηνσον]{.greek-omitted} [καισαρι]{.greek-omitted} δουναι [κινσσον]{.greek-added} [καισαρει]{.greek-added} η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} [φερετε]{.greek-omitted} [φερεται]{.greek-added} μοι [δηναριον]{.greek-omitted} [δυναριον]{.greek-added} ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω [καισαρος]{.greek-omitted} [καισαρι]{.greek-added}[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [αποδοτε]{.greek-omitted} [αποδοται]{.greek-added} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και [ερχονται]{.greek-omitted} [εξερχονται]{.greek-added} σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και [επηρωτησαν]{.greek-omitted} [επιρωτησαν]{.greek-added} αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι [εαν]{.greek-omitted} [αν]{.greek-added} τινος αδελφος [αποθανη]{.greek-omitted} [αποθανει]{.greek-added} και [καταλιπη]{.greek-omitted} [καταληπη]{.greek-added} γυναικα και τεκνα μη [αφη]{.greek-omitted} [αφης]{.greek-added} ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

[επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αδελφοι ησαν και ο [πρωτος]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} ελαβεν γυναικα και [αποθνησκων]{.greek-omitted} [αποθνισκων]{.greek-added} ουκ αφηκεν σπερμα[12:20]{.aside}

και ο [δευτερος]{.greek-omitted} [ετερος]{.greek-added} ελαβεν αυτην και απεθανεν και ουδε αυτος αφηκεν σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και ουκ αφηκαν [σπερμα]{.greek-omitted} [σπερματα]{.greek-added} [εσχατη]{.greek-omitted} [και]{.greek-added} [αισχατον]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη [αν]{.greek-added} [[ουν]{.corr}]{.greek-added} αναστασει [τινος]{.greek-added} [των]{.greek-added} [[ων]{.corr}]{.greek-added} [εσται]{.greek-added} [γυνη]{.greek-added} οταν αναστωσιν [τινος]{.greek-omitted} [αυτων]{.greek-omitted} [εσται]{.greek-omitted} [γυνη]{.greek-omitted} οι γαρ [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added} μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [εγγαμιζονται]{.greek-added} αλλ εισιν ως αγγελοι [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} [επι]{.greek-omitted} [του]{.greek-omitted} [περι]{.greek-added} [της]{.greek-added} βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added}[12:27]{.aside}

και προσελθων εις [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματευς]{.greek-added} [και]{.greek-added} ακουσας αυτων [συζητουντων]{.greek-omitted} [συνζητουντων]{.greek-added} ειδως οτι καλως [αυτοις]{.greek-omitted} [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} [πρωτ[ο]{.unclear}]{.greek-added} [πρωτη]{.corr} [και]{.greek-added} [μεγαλη]{.greek-added} [εντολη]{.greek-added} παντων [εντολη]{.greek-omitted}[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη [και]{.greek-added} [λεγει]{.greek-added} αυτω οτι πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολη]{.greek-added} ακουε [[ισραηλ]{.greek-abbr}]{.greek-added} [[ισραηλ]{.greek-abbr}]{.corr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [σου]{.greek-added} [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της [ψυχης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη [μεγαλ]{.greek-added} [παντων]{.greek-added} εντολη[12:30]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως σεαυτον μειζων τουτων αλλη εντολη ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις εστιν και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον εστιν παντων των [ολοκαυτωματων]{.greek-omitted} [ολοκαυτοματων]{.greek-added} και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει [απο]{.greek-omitted} της βασιλειας του [θεου]{.greek-abbr} και ουδεις [ετολμα]{.greek-added} ουκετι [ετολμα]{.greek-omitted} αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ειπεν]{.greek-added} [ελεγεν]{.greek-omitted} [διδασκων]{.greek-omitted} εν τω ιερω [διδασκων]{.greek-added} πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [ο]{.greek-added} [δαυιδ]{.greek-abbr} ειπεν εν [αγιω]{.greek-added} [πνευματι]{.greek-abbr} [αγιω]{.greek-omitted} [λεγει]{.greek-omitted} [λεγων]{.greek-added} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και [ποθεν]{.greek-omitted} [πως]{.greek-added} [υιος]{.greek-abbr} αυτου εστιν και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου [βλεπεται]{.greek-added} [βλεπετε]{.corr} απο των [γραμματαιων]{.greek-added} [γραμματεων]{.corr} [και]{.greek-added} των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και [προτοκαθεδριας]{.greek-added} [πρωτοκαθεδριας]{.corr} εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [προτοκλησιας]{.greek-added} εν [τοις]{.greek-omitted} [δειπνοις]{.greek-omitted}[12:39]{.aside}

[και]{.greek-omitted} [πρωτοκαθεδριας]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [συναγωγαις]{.greek-omitted} [και]{.greek-omitted} [πρωτοκλισιας]{.greek-omitted} [εν]{.greek-omitted} τοις δειπνοις[12:39 | instance no. 2]{.aside}

οι [κατεσθιοντες]{.greek-omitted} [καταισθιοντες]{.greek-added} τας οικιας των [χειρων]{.greek-added} [χηρων]{.corr} και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} [δυο]{.greek-added} λεπτα [δυο]{.greek-omitted} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [κοδραντης]{.greek-omitted} [κοδραντις]{.greek-added}[12:42]{.aside}

και προσκαλεσαμενος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους μαθητας αυτου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη [πλειον]{.greek-omitted} [πλεον]{.greek-added} παντων [εβαλεν]{.greek-added} [βεβληκεν]{.greek-omitted} [των]{.greek-omitted} [βαλλοντων]{.greek-omitted} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισσευματος]{.greek-added} αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

[και]{.greek-omitted} ο [δε]{.greek-added} [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτω βλεπεις ταυτας τας [μεγαλας]{.greek-omitted} οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου [μη]{.greek-omitted} καταλυθη[13:2]{.aside}

και καθημενου [αυτου]{.greek-omitted} εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και ανδρεας[13:3]{.aside}

ειπε ημιν [ποτε]{.greek-omitted} [ποται]{.greek-added} ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} αποκριθεις [αυτοις]{.greek-omitted} ηρξατο λεγειν [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} μη τις υμας [πλανηση]{.greek-omitted} [πλανησει]{.greek-added}[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους [πλανησουσιν]{.greek-omitted} [πλανησωσιν]{.greek-added}[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουσηται]{.greek-added} πολεμους και ακοας πολεμων μη [θροεισθε]{.greek-omitted} [θροηθηται]{.greek-added} δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι [κατα]{.greek-omitted} [τοπους]{.greek-omitted} [και]{.greek-omitted} [εσονται]{.greek-omitted} [λιμοι]{.greek-omitted} [και]{.greek-omitted} [ταραχαι]{.greek-omitted} [αρχαι]{.greek-omitted} [ωδινων]{.greek-omitted} [ταυτα]{.greek-omitted}[13:8]{.aside}

[εγερθησεται]{.greek-omitted} [γαρ]{.greek-omitted} [εθνος]{.greek-omitted} [επι]{.greek-omitted} [εθνος]{.greek-omitted} [και]{.greek-omitted} [βασιλεια]{.greek-omitted} [επι]{.greek-omitted} [βασιλειαν]{.greek-omitted} [και]{.greek-omitted} [εσονται]{.greek-omitted} [σεισμοι]{.greek-omitted} κατα τοπους και εσονται λιμοι και ταραχαι [αρχαι]{.greek-omitted} [ωδινων]{.greek-omitted} [αρχη]{.greek-added} [οδυνων]{.greek-added} ταυτα[13:8 | instance no. 2]{.aside}

[βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} δε υμεις εαυτους παραδωσουσιν γαρ υμας εις συνεδρια και εις συναγωγας [δαρησεσθε]{.greek-omitted} [δαρησεσθαι]{.greek-added} και επι [ηγεμονων]{.greek-omitted} [ηγεμωνας]{.greek-added} και [βασιλεων]{.greek-omitted} [βασιλεις]{.greek-added} [σταθησεσθε]{.greek-omitted} [σταθησεσθαι]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και [εις]{.greek-omitted} [οις]{.greek-added} παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [μεριμναται]{.greek-added} τι [λαλησητε]{.greek-omitted} [λαλησηται]{.greek-added} μηδε [μελετατε]{.greek-omitted} [μελεταται]{.greek-added} αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο [λαλειτε]{.greek-omitted} [λαληται]{.greek-added} ου γαρ [εστε]{.greek-omitted} [υμεις]{.greek-omitted} [υμοις]{.greek-added} [εσται]{.greek-added} [[η]{.unclear}]{.greek-added} [οι]{.corr} λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις [[κ]{.unclear}αναδαλ]{.greek-added} [θανατον]{.corr} και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} [μισουμενοι]{.greek-omitted} [μησουμενοι]{.greek-added} υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν [δε]{.greek-omitted} ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως [εν]{.greek-added} οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα [ορη]{.greek-omitted} [ορει]{.greek-added}[13:14]{.aside}

ο [δε]{.corr} επι του δωματος μη καταβατω [αραι]{.greek-added} [τα]{.greek-added} [της]{.greek-added} [οικιας]{.greek-added} [μηδε]{.greek-added} [εισελθετω]{.greek-added} εις την οικιαν [μηδε]{.greek-omitted} [εισελθετω]{.greek-omitted} [αραι]{.greek-omitted} [τι]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [οικιας]{.greek-omitted} αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις [θηλαζουσαις]{.greek-omitted} [θυλαζουσαις]{.greek-added} εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται η φυγη υμων [εν]{.greek-added} [χειμωνος]{.greek-omitted} [χειμωνι]{.greek-added}[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} τοιαυτη απ αρχης [κτισεως]{.greek-omitted} [κτησεως]{.greek-added} ης [εκτισεν]{.greek-omitted} [εκτησεν]{.greek-added} ο [θεος]{.greek-abbr} εως του νυν [και]{.greek-omitted} [ουδ]{.greek-added} ου μη [γενηται]{.greek-omitted} [γενοιται]{.greek-added}[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας ουκ αν εσωθη πασα σαρξ [αλλα]{.greek-omitted} [δια]{.greek-omitted} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted} [ους]{.greek-omitted} [εξελεξατο]{.greek-omitted} [εκολοβωσεν]{.greek-omitted} [τας]{.greek-omitted} [ημερας]{.greek-omitted}[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η [ιδου]{.greek-omitted} εκει μη [πιστευετε]{.greek-omitted} [πιστευσηται]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δοσουσιν]{.greek-added} σημεια και τερατα προς το [αποπλαναν]{.greek-omitted} [αποπλανησαι]{.greek-added} ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εν εκειναις ταις ημεραις [και]{.greek-added} μετα την [θλιψιν]{.greek-omitted} [ταραχην]{.greek-added} εκεινην [και]{.greek-added} [θλιψην]{.greek-added} ο ηλιος σκοτισθησεται και η σεληνη ου [δωσει]{.greek-omitted} [δοσει]{.greek-added} το φεγγος αυτης[13:24]{.aside}

και οι αστερες [πεσουνται]{.greek-added} [απο]{.greek-added} του [ουρανου]{.greek-abbr} [εσονται]{.greek-omitted} [εκπιπτοντες]{.greek-omitted} [πιπτοντες]{.greek-added} και [αι]{.greek-omitted} [δυναμεις]{.greek-omitted} [αι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr} [αι]{.greek-added} [δυναμεις]{.greek-added} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους [αυτου]{.greek-omitted} και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ [ακρου]{.greek-omitted} [ακρων]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} [εως]{.greek-added} [ακρων]{.greek-added} [της]{.greek-added} γης [εως]{.greek-omitted} [ακρου]{.greek-omitted} [ουρανου]{.greek-omitted}[13:27]{.aside}

απο δε της συκης [μαθετε]{.greek-omitted} [μαθεται]{.greek-added} την παραβολην οταν [αυτης]{.greek-omitted} ηδη ο κλαδος [αυτης]{.greek-added} απαλος [γενηται]{.greek-omitted} [γενοιται]{.greek-added} και [εκφυη]{.greek-omitted} τα φυλλα [εκφυει]{.greek-added} [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος [εστιν]{.greek-omitted}[13:28]{.aside}

ουτως και [υμεις]{.greek-omitted} [ημεις]{.greek-added} οταν [ιδητε]{.greek-added} ταυτα [ιδητε]{.greek-omitted} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

[αμην]{.greek-omitted} [αμιν]{.greek-added} λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα [ταυτα]{.greek-omitted} [γενηται]{.greek-omitted} [γενοιται]{.greek-added}[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} ωρας ουδεις [οιδεν]{.greek-omitted} [ειδεν]{.greek-added} ουδε οι αγγελοι [των]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} ουδε ο [υιος]{.greek-abbr} ει [μι]{.greek-added} [μη]{.corr} ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε [αγρυπνειτε]{.greek-omitted} [αγρυπνειται]{.greek-added} και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους [την]{.greek-added} [εξουσιαν]{.greek-added} τοις δουλοις αυτου [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} και εκαστω [τω]{.greek-added} [το]{.corr} εργον αυτου και τω [θυρωρω]{.greek-omitted} [θυρορω]{.greek-added} ενετειλατο ινα [γρηγορη]{.greek-omitted} [γρηγορει]{.greek-added}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η μεσονυκτιου η [αλεκτοροφωνιας]{.greek-omitted} [αλεκτωροφωνιας]{.greek-added} η πρωι[13:35]{.aside}

μη ελθων [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} [ευρη]{.greek-omitted} [ευρει]{.greek-added} υμας καθευδοντας[13:36]{.aside}

[α]{.greek-omitted} [ο]{.greek-added} δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added}[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας [και]{.greek-omitted} εζητουν οι αρχιερεις και οι γραμματεις πως αυτον [εν]{.greek-omitted} δολω [κρατησαντες]{.greek-omitted} [κρατησωσι]{.greek-added} [και]{.greek-added} αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν [βηθανια]{.greek-omitted} [βυθανια]{.greek-added} εν τη οικια σιμωνος του λεπρου κατακειμενου αυτου ηλθεν γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης [πολυτελους]{.greek-omitted} [πολυτιμου]{.greek-added} και [συντριψασα]{.greek-omitted} [συντριψας]{.greek-added} το αλαβαστρον κατεχεεν [αυτο]{.greek-added} [κατα]{.greek-added} [κεφαλης]{.greek-added} αυτου [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους [και]{.greek-omitted} λεγοντες εις τι η [απωλεια]{.greek-omitted} [απολια]{.greek-added} αυτη του μυρου [γεγονεν]{.greek-omitted} [τουτου]{.greek-added} [εγενετο]{.greek-added}[14:4]{.aside}

ηδυνατο γαρ [το]{.greek-added} [μυρον]{.greek-added} τουτο πραθηναι επανω [τριακοσιων]{.greek-omitted} [δυακοσιων]{.greek-added} [δηναριων]{.greek-omitted} [δυναριων]{.greek-added} και δοθηναι [τοις]{.greek-omitted} πτωχοις και [ενεβριμωντο]{.greek-omitted} [ενεβρυμουντο]{.greek-added} αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αφετε]{.greek-omitted} [αφεται]{.greek-added} αυτην τι αυτη κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν [θελητε]{.greek-omitted} [θελεται]{.greek-added} δυνασθε αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη εποιησεν [προελαβεν]{.greek-omitted} [προσελαβε]{.greek-added} [μυρισαι]{.greek-omitted} [μυρησαι]{.greek-added} [μου]{.greek-omitted} το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου [εαν]{.greek-omitted} [αν]{.greek-added} κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη [λαληθησεται]{.greek-omitted} εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας [ο]{.greek-omitted} ισκαριωτης εις των δωδεκα απηλθεν προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [εθαυμασαν]{.greek-added} [και]{.greek-added} επηγγειλαντο αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως [ευκαιρως]{.greek-omitted} αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις [απελθοντες]{.greek-omitted} [ετοιμασωμεν]{.greek-omitted} [ετοιμασωμε]{.greek-added} [ινα]{.greek-omitted} [φαγης]{.greek-omitted} [σοι]{.greek-added} [φαγειν]{.greek-added} το πασχα[14:12]{.aside}

[και]{.greek-omitted} [ο]{.greek-added} [δε]{.greek-added} αποστελλει δυο των μαθητων αυτου και λεγει αυτοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} εις την πολιν και [απαντησει]{.greek-omitted} [απαντηση]{.greek-added} υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων [ακολουθησατε]{.greek-omitted} [ακολουθησαται]{.greek-added} αυτω[14:13]{.aside}

και οπου [εαν]{.greek-omitted} [αν]{.greek-added} [εισελθη]{.greek-omitted} [εισελθει]{.greek-added} ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει [[δειξη]{.corr}]{.greek-added} ανωγεον [μεγα]{.greek-omitted} εστρωμενον [ετοιμον]{.greek-omitted} [ετιμον]{.greek-added} εκει [ετοιμασατε]{.greek-omitted} [ετοιμασαται]{.greek-added} ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον [εις]{.greek-omitted} [προς]{.greek-added} την πολιν και ευρον καθως ειπεν αυτοις [και]{.greek-omitted} [ητοιμασαν]{.greek-omitted} [το]{.greek-omitted} [πασχα]{.greek-omitted}[14:16]{.aside}

[και]{.greek-omitted} [εξηλθον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [ευρον]{.greek-omitted} [καθως]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} και ητοιμασαν το πασχα[14:16 | instance no. 2]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων [παραδωσει]{.greek-omitted} [παραδοσει]{.greek-added} [με]{.greek-omitted} [μαι]{.greek-added} ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν [αυτω]{.greek-omitted} εις καθ εις μητι εγω [και]{.greek-omitted} [αλλος]{.greek-omitted} [μητι]{.greek-omitted} [εγω]{.greek-omitted}[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ο εμβαπτομενος μετ εμου [εις]{.greek-omitted} [το]{.greek-omitted} [τρυβλιον]{.greek-omitted} [εν]{.greek-added} [τω]{.greek-added} [τριβλιω]{.greek-added}[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[14:22]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [ευχαριστησας]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτοις]{.greek-omitted} και επιον εξ αυτου παντες[14:23]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεσθαι]{.greek-added} εν εμοι εν τη νυκτι ταυτη οτι γεγραπται παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα [της]{.greek-added} [ποιμνης]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και ει παντες σκανδαλισθησονται αλλ [ουκ]{.greek-omitted} [ακ]{.greek-added} εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν η δις [αλεκτορα]{.greek-omitted} [αλεκτωρ]{.greek-added} [φωνησαι]{.greek-omitted} [φωνησει]{.greek-added} [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με[14:30]{.aside}

ο δε εκπερισσου ελεγεν μαλλον εαν [δεει]{.greek-added} με [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} [αποθανειν]{.greek-added} [με]{.greek-added} [συν]{.greek-added} σοι ου μη σε απαρνησωμαι ωσαυτως [δε]{.greek-omitted} και παντες ελεγον[14:31]{.aside}

και ερχονται εις [χωριαν]{.greek-added} [χωριον]{.corr} [ου]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [τουνομα]{.greek-added} γεθσημανη και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον [και]{.corr} [ιακωβον]{.corr} και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [και]{.greek-added} μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και [λεγει]{.greek-omitted} [λεγειν]{.greek-added} αυτοις περιλυπος εστιν η ψυχη [μεχρι]{.greek-added} [μου]{.greek-omitted} [εως]{.greek-omitted} θανατου μεινατε ωδε και [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added}[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα [σοι]{.greek-added} δυνατα σοι παρενεγκε το ποτηριον [απ]{.greek-omitted} [εμου]{.greek-omitted} τουτο αλλ [ου]{.greek-omitted} [ουχ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω [συμων]{.greek-added} [σιμων]{.corr} καθευδεις ουκ ισχυσας μιαν ωραν [γρηγορησαι]{.greek-omitted} [αγρυπνησαι]{.greek-added}[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη [εισελθητε]{.greek-omitted} [ελθητε]{.greek-added} εις [πειρασμον]{.greek-omitted} [πυρασμον]{.greek-added} το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν [γαρ]{.greek-omitted} [δε]{.greek-added} [αυτων]{.greek-added} οι οφθαλμοι [αυτων]{.greek-omitted} βεβαρημενοι και ουκ [ηδεισαν]{.greek-omitted} [ηδησαν]{.greek-added} τι αυτω αποκριθωσιν[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις [καθευδετε]{.greek-omitted} [καθευδεται]{.greek-added} [το]{.greek-added} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε [αγωμεν]{.greek-omitted} [αγομεν]{.greek-added} [εντευθεν]{.greek-added} ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει δε [αυτοις]{.greek-added} ο παραδιδους αυτον [σημειον]{.greek-added} [συσσημον]{.greek-omitted} [αυτοις]{.greek-omitted} λεγων ον αν φιλησω αυτος εστιν κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει [αυτω]{.greek-omitted} ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας [αυτων]{.greek-omitted} και εκρατησαν αυτον[14:46]{.aside}

εις δε [τις]{.greek-omitted} των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επι]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και [αποκριθεις]{.greek-omitted} [αποκρηθεις]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην [προς]{.greek-omitted} [υμας]{.greek-omitted} εν τω ιερω διδασκων [υμας]{.greek-added} και ουκ [εκρατησατε]{.greek-omitted} [εκρατησαται]{.greek-added} με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες [και]{.greek-added} εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε [καταλιπων]{.greek-omitted} [καταλειπην]{.greek-added} την σινδονα [[σινδωνα]{.corr}]{.greek-added} γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν [ψευδομαρτυριαν]{.greek-added} κατα του [ιησου]{.greek-abbr} [ωστε]{.greek-added} [μαρτυριαν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου [και]{.greek-omitted} [ισαι]{.greek-omitted} [αι]{.greek-omitted} [μαρτυριαι]{.greek-omitted} [ουκ]{.greek-omitted} [ησαν]{.greek-omitted}[14:56]{.aside}

[και]{.greek-omitted} [τινες]{.greek-omitted} [ανασταντες]{.greek-omitted} [εψευδομαρτυρουν]{.greek-omitted} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} λεγοντες[14:57]{.aside}

οτι ημεις [[ο]{.unclear}ικουσαμεν]{.greek-added} [ηκουσαμεν]{.corr} αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επερωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων [ουκ]{.greek-omitted} [αποκρινη]{.greek-omitted} [ουδεν]{.greek-omitted} [τι]{.greek-omitted} [ουτοι]{.greek-omitted} [σου]{.greek-omitted} [καταμαρτυρουσιν]{.greek-omitted}[14:60]{.aside}

[και]{.greek-omitted} [αναστας]{.greek-omitted} [ο]{.greek-omitted} [αρχιερευς]{.greek-omitted} [εις]{.greek-omitted} [μεσον]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [λεγων]{.greek-omitted} ουκ [αποκρινη]{.greek-omitted} [απεκρινει]{.greek-added} ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60 | instance no. 2]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν [επερωτα]{.greek-added} [αυτον]{.greek-added} ο αρχιερευς [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον [μετα]{.greek-omitted} των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} μαρτυρων[14:63]{.aside}

[ηκουσατε]{.greek-omitted} [ηκουσαται]{.greek-added} της βλασφημιας [αυτου]{.greek-added} τι υμιν φαινεται οι δε παντες κατεκριναν [αυτον]{.greek-omitted} ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και [λεγειν]{.greek-omitted} [λεγουσιν]{.greek-added} αυτω προφητευσον και οι υπηρεται [ραπισμασιν]{.greek-omitted} [αυτον]{.greek-omitted} [ραπισματα]{.greek-added} [αυτω]{.greek-added} [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added}[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα [[ιησου]{.greek-abbr}]{.greek-added} του [ναζωραιου]{.greek-added} [ναζαρηνου]{.greek-omitted} [ιησου]{.greek-omitted} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα [ουδε]{.corr} [επισταμαι]{.corr} τι [συ]{.corr} λεγεις και εξηλθεν [εξω]{.greek-omitted} εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστικωσιν]{.greek-added} οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνησατο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει [οτι]{.greek-added} [και]{.greek-omitted} [γαρ]{.greek-omitted} [γαλιλαιος]{.greek-omitted} [ει]{.greek-omitted} και η λαλια σου [ομοιαζει]{.greek-omitted} [ομιαζει]{.greek-added}[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added}[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και [ανεμνησθη]{.greek-omitted} [εμνησθη]{.greek-added} ο πετρος [το]{.greek-omitted} [τω]{.greek-added} ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} [[αλεκτωρ]{.corr}]{.greek-added} φωνησαι δις απαρνηση [με]{.greek-omitted} [μαι]{.greek-added} [τρις]{.greek-omitted} [τρεις]{.greek-added} και επιβαλων [εκλι[σ]{.unclear}[―]{.gap}]{.greek-added} [εκλαιεν]{.greek-omitted} [[εκλαιε]{.corr}]{.greek-added}[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν [αυτον]{.greek-added} τω πιλατω[15:1]{.aside}

και επηρωτησεν [ο]{.greek-added} [πηλατος]{.greek-added} αυτον [ο]{.greek-omitted} [πιλατος]{.greek-omitted} συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα[15:3]{.aside}

ο δε [ουκ]{.greek-added} [απεκρινει]{.greek-added} [ουδεν]{.greek-added} πιλατος παλιν [επηρωτησεν]{.greek-omitted} [επερωτησεν]{.greek-added} αυτον λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} [ουδεν]{.greek-omitted} [ιδε]{.greek-omitted} [ποσα]{.greek-omitted} [σου]{.greek-omitted} [καταμαρτυρουσιν]{.greek-omitted}[15:4]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [παλιν]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [ουκ]{.greek-omitted} [αποκρινη]{.greek-omitted} ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντος]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των [συστασιαστων]{.greek-omitted} [στασιαστων]{.greek-added} δεδεμενος οιτινες [εν]{.greek-omitted} τη στασει φονον [πεποιηκεισαν]{.greek-omitted} [πεποιηκεσαν]{.greek-added}[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων [θελετε]{.greek-omitted} [θελεται]{.greek-added} απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παραδεδωκησαν]{.greek-added} αυτον [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted}[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεπησαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος [αποκριθεις]{.greek-omitted} παλιν [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις τι ουν [θελετε]{.greek-omitted} [θελεται]{.greek-added} [ινα]{.greek-added} ποιησω [[ιησουν]{.greek-abbr}]{.greek-added} ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν [εκραξαν]{.greek-omitted} [εκραυγασαν]{.greek-added} [αυτω]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος βουλομενος [τω]{.greek-omitted} [τωι]{.greek-added} οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και παρεδωκεν τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον [εσω]{.greek-omitted} [εως]{.greek-added} της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανο[ν]{.unclear}[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον [και]{.greek-added} [λεγειν]{.greek-added} χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και αγγαρευουσιν παραγοντα τινα σιμωνα [κυρηναιον]{.greek-omitted} [κηριναιον]{.greek-added} ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [γολγοθα]{.greek-omitted} [γολγοθαν]{.greek-added} τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω [πιειν]{.greek-omitted} [ποιειν]{.greek-added} εσμυρνισμενον οινον ο δε ουκ ελαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον [διαμεριζονται]{.greek-omitted} [διεμεριζον]{.greek-added} τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η [επιγραφη]{.greek-omitted} [αιτια]{.greek-added} της [επιγραφης]{.greek-added} [αιτιας]{.greek-omitted} [αυτου]{.greek-omitted} [επιγεγραμμενη]{.greek-omitted} [γεγραμμενη]{.greek-added} ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν [αυτω]{.corr} [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [καταβητι]{.greek-added} απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} προς αλληλους [μετα]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι [συνεσταυρωμενοι]{.greek-abbr} [[[συνεσταυρωμενοι]{.greek-abbr}]{.corr}]{.greek-added} αυτω [ωνειδιζον]{.greek-omitted} [ονιδαιζον]{.greek-added} αυτον[15:32]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη ωρα τη [ενατη]{.greek-omitted} [[θ]{.greek-abbr}]{.greek-added} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι λιμα [σαβαχθανι]{.greek-omitted} [σαβαχθανη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων [ακουσαντες]{.greek-omitted} ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις [εξ]{.greek-added} [αυτων]{.greek-added} και [γεμισας]{.greek-omitted} [γεμησας]{.greek-added} σπογγον οξους [εποτιζε]{.greek-added} περιθεις τε καλαμω [και]{.greek-added} [εποτιζεν]{.greek-omitted} [αυτον]{.greek-omitted} λεγων [αφετε]{.greek-omitted} [αφες]{.greek-added} ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο [κεντυριων]{.greek-omitted} [κεντηριων]{.greek-added} ο [παρεστηκως]{.greek-omitted} [παρεστικως]{.greek-added} εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος υιος [[θεου]{.greek-abbr}]{.greek-added} ην [θεου]{.greek-omitted}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις [η]{.greek-added} [ην]{.greek-omitted} [και]{.greek-omitted} μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια [ηκολουθουν]{.greek-omitted} [ηκολουθησαν]{.greek-added} [αυτω]{.greek-omitted} [και]{.greek-omitted} [διηκονουν]{.greek-omitted} αυτω και αλλαι πολλαι αι [συναναβασαι]{.greek-omitted} [συναναβησαι]{.greek-added} αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης [επει]{.greek-omitted} [επι]{.greek-added} ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

ηλθεν ιωσηφ [ο]{.greek-omitted} απο [αριμαθαιας]{.greek-omitted} [αριμαθιας]{.greek-added} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας εισηλθεν προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον [κεντυριωνα]{.greek-omitted} [κεντηριωνα]{.greek-added} επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους απο του [κεντυριωνος]{.greek-omitted} [κεντηριωνος]{.greek-added} [εδωρησατο]{.greek-omitted} [εδορησατο]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλησε]{.greek-added} τη σινδονι και κατεθηκεν [αυτον]{.greek-omitted} εν μνημειω ο ην [λελατομημενον]{.greek-omitted} [λελατωμημενον]{.greek-added} εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλησε]{.greek-added} λιθον [μεγαν]{.greek-added} επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [ηωση]{.greek-added} [ιωση]{.corr} εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι [αλειψωσιν]{.greek-omitted} [αλειψωσι]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις [αποκυλισει]{.greek-omitted} [αποκυλιση]{.greek-added} ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι [θεωρουσιν]{.greek-omitted} [ορωσιν]{.greek-added} οτι [αποκεκυλισται]{.greek-omitted} [αποκεκυλησθη]{.greek-added} ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον [καθημενον]{.greek-omitted} εν τοις [δεξιοις]{.greek-omitted} [περιβεβλημενον]{.greek-omitted} [στολην]{.greek-omitted} [λευκην]{.greek-omitted} [και]{.greek-omitted} [εξεθαμβηθησαν]{.greek-omitted}[16:5]{.aside}

[και]{.greek-omitted} [εισελθουσαι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [μνημειον]{.greek-omitted} [ειδον]{.greek-omitted} [νεανισκον]{.greek-omitted} [καθημενον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5 | instance no. 2]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβεισθαι]{.greek-added} [ιησουν]{.greek-abbr} [ζητειτε]{.greek-omitted} [ζητειται]{.greek-added} τον [ναζαρηνον]{.greek-omitted} [ναζηρινον]{.greek-added} τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} ειπατε τοις μαθηταις [αυτω]{.greek-added} [αυτου]{.corr} και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι [ουδεν]{.greek-omitted} ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας [δε]{.greek-omitted} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι [πρωτη]{.greek-omitted} [πρωτον]{.greek-added} [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης εκβεβληκει επτα [δαιμονια]{.greek-omitted} [δεμονια]{.greek-added}[16:9]{.aside}

εκεινη [πορευθεισα]{.greek-omitted} [πορευθησα]{.greek-added} [απηγγειλεν]{.greek-omitted} [απηγγειλαν]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλεουσι]{.greek-added} [κλαιουσιν]{.greek-omitted} [[κλαιουσι]{.corr}]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη [[εθεαθει]{.corr}]{.greek-added} υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα [μορφη]{.greek-omitted} [μωρφη]{.greek-added} πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι [απελθοντες]{.greek-omitted} [εξελθοντες]{.greek-added} [απειγειλαν]{.greek-added} [απηγγειλαν]{.greek-omitted} [[απηγειλαν]{.corr}]{.greek-added} τοις [λοιποις]{.greek-omitted} [λιποις]{.greek-added} ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ονειδησε]{.greek-added} την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον [εγηγερμενον]{.greek-omitted} [εγειγερμενον]{.greek-added} [εκ]{.greek-added} [νεκρων]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα [κηρυξατε]{.greek-omitted} [κηρυξαται]{.greek-added} το ευαγγελιον [παση]{.greek-omitted} [πασι]{.greek-added} τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε [απιστεισας]{.greek-added} [απιστησας]{.corr} κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα [παρακ[ω]{.unclear}λουθησει]{.greek-added} [παρακολουθησει]{.corr} εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις αρουσιν καν θανασιμον τι [ποουσιν]{.greek-added} [πιωσιν]{.greek-omitted} [[πιουσιν]{.corr}]{.greek-added} ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως [εξουσιν]{.greek-omitted} [εξωσιν]{.greek-added}[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις [τους]{.greek-added} [[ουρανους]{.greek-abbr}]{.greek-added} [τον]{.corr} [[ουρανον]{.greek-abbr}]{.corr} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-omitted} [[πατρος]{.greek-abbr}]{.greek-added}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

