---
title: "Collation of Byz^RP^ vs 30454 (454)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 454 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30454).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 454                                   	| λογος                              	|
| 454 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 454 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 454               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 454                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 454 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 454                                                     	| [―]{.gap}                        	|
:::

## First Timothy

### Chapter 1

παυλος αποστολος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} κατ επιταγην [θεου]{.greek-omitted} [του]{.greek-added} [σωτηρος]{.greek-abbr} ημων [και]{.greek-omitted} [κυριου]{.greek-omitted} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} της ελπιδος ημων[1:1]{.aside}

τιμοθεω γνησιω τεκνω εν πιστει χαρις ελεος ειρηνη απο [θεου]{.greek-abbr} [πατρος]{.greek-abbr} ημων και [χριστου]{.greek-abbr} [ιησου]{.greek-abbr} του [κυριου]{.greek-abbr} ημων[1:2]{.aside}

καθως [παρεκαλεσα]{.greek-omitted} [παρεκαλεσατε]{.greek-added} [σε]{.greek-omitted} προσμειναι εν εφεσω πορευομενος εις μακεδονιαν ινα παραγγειλης [τισιν]{.greek-omitted} [τισι]{.greek-added} μη ετεροδιδασκαλειν[1:3]{.aside}

μηδε προσεχειν μυθοις και γενεαλογιαις απεραντοις αιτινες ζητησεις [παρεχουσιν]{.greek-omitted} [παρεχουσι]{.greek-added} μαλλον η οικονομιαν [θεου]{.greek-abbr} την εν πιστει[1:4]{.aside}

το δε τελος της παραγγελιας εστιν αγαπη εκ καθαρας καρδιας και συνειδησεως αγαθης και πιστεως ανυποκριτου[1:5]{.aside}

ων [τινες]{.greek-omitted} [τινων]{.greek-added} αστοχησαντες εξετραπησαν εις ματαιολογιαν[1:6]{.aside}

θελοντες ειναι νομοδιδασκαλοι [μη]{.greek-omitted} [νοουντες]{.greek-omitted} [μητε]{.greek-omitted} [α]{.greek-omitted} [λεγουσιν]{.greek-omitted} [μητε]{.greek-omitted} [περι]{.greek-omitted} [τινων]{.greek-omitted} [διαβεβαιουνται]{.greek-omitted}[1:7]{.aside}

