---
title: "Collation of Byz^RP^ vs 30456 (456)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 456 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30456).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 456                                   	| λογος                              	|
| 456 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 456 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 456               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 456                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 456 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 456                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 2

[οιδα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [που]{.greek-omitted} [κατοικεις]{.greek-omitted} [οπου]{.greek-omitted} [ο]{.greek-omitted} θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις [εν]{.greek-omitted} αις [αντιπας]{.greek-omitted} [ἀντεῖπας]{.greek-added} ο μαρτυς μου ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος εδιδαξεν τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} [του]{.greek-added} φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην [των]{.greek-omitted} νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατειρη]{.greek-added} εκκλησιας γραψον ταδε [λεγει]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [τους]{.greek-omitted} [οφθαλμους]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [φλογα]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ποδες]{.greek-omitted} [αυτου]{.greek-omitted} [ομοιοι]{.greek-omitted} [χαλκολιβανω]{.greek-omitted}[2:18]{.aside}

