---
title: "Collation of Byz^RP^ vs 30472 (472)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 472 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30472).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 472                                   	| λογος                              	|
| 472 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 472 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 472               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 472                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 472 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 472                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [υιου]{.greek-abbr} του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [ιωανης]{.greek-added} βαπτιζων εν τη ερημω και [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα [η]{.greek-omitted} [ιουδαια]{.greek-omitted} [ιουδαιων]{.greek-added} χωρα και [οι]{.greek-omitted} [ιεροσολυμιται]{.greek-omitted} [ιεροσολυμειτε]{.greek-added} και εβαπτιζοντο παντες εν τω ιορδανη ποταμω [υπ]{.greek-omitted} [αυτου]{.greek-omitted} εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερμ[α]{.greek-supplied}τινην περι την οσφυν αυτου και [εσθιων]{.greek-omitted} [εσθ[η]{.unclear}ον]{.greek-added} ακριδας και [μελι]{.greek-omitted} [μελη]{.greek-added} αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσεν]{.greek-added} [λεγων]{.greek-omitted} [λεγο[ν]{.unclear}]{.greek-added} ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος [κυψας]{.greek-omitted} [κυμψας]{.greek-added} λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε [βαπτισει]{.greek-omitted} [βαπτι]{.greek-added} [υμας]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [αγιω]{.greek-omitted}[1:8]{.aside}

