---
title: "Collation of Byz^RP^ vs 30595 (595)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 595 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30595).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 595                                   	| λογος                              	|
| 595 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 595 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 595               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 595                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 595 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 595                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος [κατασκευασει]{.greek-omitted} [κατακλευασει]{.greek-added} [τ[ο]{.unclear}ν]{.greek-added} [την]{.corr} οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους [αυτου]{.greek-omitted} [ατου]{.greek-added}[1:3]{.aside}

εγενετο ιωαννης [βαπτιζων]{.greek-omitted} [βατιζων]{.greek-added} εν τη ερημω και κηρυσσων βαπτισμα μετανοιας [εις]{.greek-omitted} [αφεσιν]{.greek-omitted} [αμαρτιων]{.greek-omitted}[1:4]{.aside}

[εγενετο]{.greek-omitted} [ιωαννης]{.greek-omitted} [βαπτιζων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [και]{.greek-omitted} [κηρυσσων]{.greek-omitted} [βαπτισμα]{.greek-omitted} [μετανοιας]{.greek-omitted} εις αφεσιν αμαρτιων[1:4 | instance no. 2]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} προς αυτον πασα η ιουδαια χωρα και οι [ιεροσολυμιται]{.greek-omitted} [ιεροσολιμιται]{.greek-added} και [επτιζοντο]{.greek-added} [εβαπτιζοντο]{.corr} παντες εν τω [ιορδανη]{.greek-omitted} [ιοδανη]{.greek-added} ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην [δε]{.greek-omitted} ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην [δρματινην]{.greek-added} [δερματινην]{.corr} περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων [ερχεται]{.greek-omitted} [ερχαται]{.greek-added} ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν [εβαπτισα]{.greek-omitted} [εβαπισα]{.greek-added} υμας [εν]{.greek-omitted} υδατι αυτος [δε]{.corr} βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και [εγετο]{.greek-added} [εγενετο]{.corr} εν εκειναις ταις ημεραις [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και [βαπτισθη]{.greek-added} [εβαπτισθη]{.corr} υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} [ωσει]{.greek-omitted} [ως]{.greek-added} περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω ευδοκησα[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον [εκβαλλι]{.greek-added} [εκβαλλ[ε]{.unclear}ι]{.corr} εις την ερημον[1:12]{.aside}

και [εκει]{.greek-added} [ην]{.greek-added} [ην]{.corr} [εκει]{.corr} εν τη ερημω ημερας τεσσαρακοντα πειραζομενος [υπο]{.greek-omitted} [απο]{.greek-added} του σατανα και ην μετα των θηριων και [αγγελοι]{.greek-added} [οι]{.greek-added} [οι]{.corr} [αγγελοι]{.corr} διηκονουν αυτω[1:13]{.aside}

μετα δε [το]{.greek-omitted} παραδοθηναι [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [ιωαννης]{.greek-added} ηλθεν [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια [του]{.greek-omitted} [θεου]{.greek-omitted} [μετανοειτε]{.greek-omitted} [και]{.greek-omitted} [πιστευετε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ευαγγελιω]{.greek-omitted}[1:15]{.aside}

[και]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [πεπληρωται]{.greek-omitted} [ο]{.greek-omitted} [καιρος]{.greek-omitted} [και]{.greek-omitted} [ηγγικεν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω [ευαγγελιω]{.greek-omitted} [ευανγελιω]{.greek-added}[1:15 | instance no. 2]{.aside}

περιπατων δε παρα την θαλασσαν [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [σιμονα]{.greek-added} [σιμωνα]{.corr} και ανδρεαν [τον]{.greek-omitted} [αδελφον]{.greek-omitted} αυτου του σιμωνος [τον]{.greek-added} [αδελφον]{.greek-added} βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως [αφεντες]{.greek-omitted} τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον [ειδεν]{.greek-omitted} [ειδε]{.greek-added} ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και [εξεπλησοντο]{.greek-added} [εξεπλησσοντο]{.corr} επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και [ην]{.corr} εν τη [γ[ω]{.unclear}]{.greek-added} [συναγωγη]{.corr} αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [εκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} [το]{.greek-omitted} ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε [συζη]{.greek-added} [συζητειν]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [λεγοντας]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [τουτο]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [διδαχη]{.greek-omitted} [η]{.greek-omitted} [καινη]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [κατ]{.greek-omitted} [εξουσιαν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [πνευμασιν]{.greek-omitted} [τοις]{.greek-omitted} [ακαθαρτοις]{.greek-omitted} [επιτασσει]{.greek-omitted} [και]{.greek-omitted} [υπακουουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[1:27]{.aside}

[τειν]{.greek-added} [και]{.greek-omitted} [εθαμβηθησαν]{.greek-omitted} [παντες]{.greek-omitted} [ωστε]{.greek-omitted} [συζητειν]{.greek-omitted} προς εαυτους λεγοντας τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η [καινη]{.greek-omitted} [εκεινη]{.greek-added} αυτη οτι κατ εξουσιαν και [τοις]{.corr} [πνευμασιν]{.greek-omitted} [[πνασι]{.greek-abbr}]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27 | instance no. 2]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου [ευθυς]{.greek-omitted} εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν [σιμονος]{.greek-added} [σιμωνος]{.corr} και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος [κατεκειτο]{.greek-omitted} [κατεκρειτο]{.greek-added} [πυρεσουσα]{.greek-added} [πυρεσσουσα]{.corr} και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και [τους]{.corr} δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη [ην]{.greek-omitted} προς [την]{.greek-omitted} [τη]{.greek-added} [θυραν]{.greek-omitted} [θυρα]{.greek-added}[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας [και]{.greek-added} ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον[1:34]{.aside}

και πρωι εννυχον λιαν αναστας εξηλθεν και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο [σιμον]{.greek-added} [σιμων]{.corr} και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον [λεγουσιν]{.greek-omitted} [λειγουσιν]{.greek-added} αυτω οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει [κηρυσω]{.greek-added} [κηρυξω]{.corr} εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις [αυτων]{.greek-omitted} [εις]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [εκβαλλων]{.greek-omitted}[1:39]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [κηρυσσων]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [συναγωγαις]{.greek-omitted} αυτων εις ολην την γαλιλαιαν και τα δαιμονια [εκβαλλον]{.greek-added} [εκβαλλων]{.corr}[1:39 | instance no. 2]{.aside}

και [ερχετε]{.greek-added} [ερχεται]{.corr} προς αυτον λεπρος παρακαλων αυτον και γονυπετων [αυτων]{.greek-added} [αυτον]{.corr} και λεγων αυτω οτι εαν θελης δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και [εκαρισθη]{.greek-added} [εκαθαρισθη]{.corr}[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης [αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε [λθων]{.greek-added} [εξελθων]{.greek-omitted} [[εξλθων]{.corr}]{.greek-added} ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον [δυνασθ[ε]{.unclear}]{.greek-added} [δυνασθαι]{.corr} φανερως εις [πολην]{.greek-added} [πολιν]{.corr} εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την [θυραν]{.greek-omitted} [θυρα]{.greek-added} και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον [φερεντες]{.greek-added} [φεροντες]{.corr} αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω [ο]{.greek-omitted} παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω [τεκνον]{.greek-omitted} [αφεωνται]{.greek-omitted} [σοι]{.greek-omitted} [αι]{.greek-omitted} [αμαρτιαι]{.greek-omitted} [σου]{.greek-omitted}[2:5]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [παραλυτικω]{.greek-omitted} τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι αμαρτιαι σου[2:5 | instance no. 2]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως [λαλει]{.greek-omitted} [λαγει]{.greek-added} [βλασφεμιας]{.greek-added} [βλασφημιας]{.corr} τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου [οτι]{.greek-omitted} [ουτως]{.greek-omitted} [αυτοι]{.greek-omitted} [διαλογιζονται]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω [παραλυτικω]{.greek-omitted} [παραλυκω]{.greek-added} [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως ειδομεν[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος [ηχετο]{.greek-added} [ηρχετο]{.corr} προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ειδε]{.greek-added} λευι τον του [αλφαιου]{.greek-omitted} [αλφεου]{.greek-added} καθημενον επι το τελωνιον και λεγει αυτω ακολουθει [μου]{.greek-added} [μοι]{.corr} και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και [αμαρτωλοι]{.greek-omitted} [αμαρτολοι]{.greek-added} [συνακειντο]{.greek-added} [συνανεκειντο]{.corr} τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και [ηκολουθησαν]{.greek-omitted} [ακολουθησαν]{.greek-added} αυτω[2:15]{.aside}

και [οι]{.corr} γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και [αμαρτωλων]{.greek-omitted} [ελεγον]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [τι]{.greek-omitted} [οτι]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} [εσθιει]{.greek-omitted} [και]{.greek-omitted} [πινει]{.greek-omitted}[2:16]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [εσθιοντα]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} εσθιει και [πινει]{.greek-omitted} [πιει]{.greek-added}[2:16 | instance no. 2]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν [οι]{.greek-omitted} ισχυοντες [ιατρου]{.greek-omitted} [ιαπρου]{.greek-added} αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε [σοι]{.corr} μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν [εκεινες]{.greek-added} [εκειναις]{.corr} ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω [παλαιω]{.corr} ει δε [μη]{.greek-omitted} [αιρει]{.greek-omitted} [μει]{.greek-added} [ερει]{.greek-added} το πληρωμα αυτου το καινον του παλαιου και [κ[ο]{.unclear}]{.greek-added} χειρον [σχιμα]{.greek-added} [σχισμα]{.corr} γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος [εκχειται]{.corr} [και]{.corr} [οι]{.corr} [ασκοι]{.corr} [απολουνται]{.greek-omitted} [[απολλυνται]{.corr}]{.greek-added} [[αλλα]{.corr}]{.greek-added} [[οιονον]{.corr}]{.greek-added} [[εκχειται]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [[οι]{.corr}]{.greek-added} [[ασκοι]{.corr}]{.greek-added} [[απολλυνται]{.corr}]{.greek-added} [αλλα]{.corr} [οινον]{.corr} [νεος]{.greek-added} [νεον]{.corr} εις ασκους καινους βλητεον[2:22]{.aside}

και εγενετο [παραπορευεσθε]{.greek-added} [παραπορευεσθαι]{.corr} αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστει]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-omitted} [οτε]{.greek-omitted} [χρειαν]{.greek-omitted} [εσχεν]{.greek-omitted} [και]{.greek-omitted} [επεινασεν]{.greek-omitted} [αυτος]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[2:25]{.aside}

[και]{.greek-omitted} [αυτος]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ουδεποτε]{.greek-omitted} [ανεγνωτε]{.greek-omitted} [τι]{.greek-omitted} [εποιησεν]{.greek-omitted} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25 | instance no. 2]{.aside}

πως [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} [εγενετο]{.greek-omitted} [εγετνετο]{.greek-added} ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [και]{.greek-added} [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην εχων την χειρα[3:1]{.aside}

και [παρατηρουν]{.greek-added} [παρετηρουν]{.corr} αυτον ει [εν]{.greek-added} τ[ο]{.unclear}ις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει [αυτον]{.greek-omitted} ινα κατηγορησωσιν αυτου [[αυτον]{.corr}]{.greek-added}[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω εξηραμμενην εχοντι την χειρα [εγειραι]{.greek-omitted} [εγερε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγ[ει]{.unclear} αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η [κακοποιησαι]{.greek-omitted} [κακοσποιησαι]{.greek-added} ψυχην σωσαι η αποκτειναι οι δε [εσιωπων]{.greek-omitted} [εστιωπων]{.greek-added}[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πωρρωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και αποκατεσταθη η χειρ αυτου [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων [συμβουλον]{.greek-added} [συμβουλιον]{.corr} [εποιουν]{.greek-omitted} [ποισαν]{.greek-added} [[ποιησαν]{.corr}]{.greek-added} κατ αυτου οπως αυτον απολεσωσιν [[απολεσωσι]{.corr}]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [εχωρησε]{.greek-added} [ανεχωρησεν]{.greek-omitted} [[ανεχωρησε]{.corr}]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [ηκολουθησεν]{.greek-added} αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και [οι]{.greek-omitted} [περι]{.greek-omitted} [τυρον]{.greek-omitted} [και]{.greek-omitted} [σιδωνα]{.greek-omitted} [πληθος]{.greek-omitted} [πολυ]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οσα]{.greek-omitted} [εποιει]{.greek-omitted} [ηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[3:8]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} [και]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} [και]{.greek-omitted} οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8 | instance no. 2]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον προσκαρτερη αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ [εθεπευσεν]{.greek-added} [εθεραπευσεν]{.corr} ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [απτωνται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα οταν αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσεπιπτων]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο [υιος]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστειλη]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω [σιμωνι]{.greek-omitted} [σιμονι]{.greek-added} ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [του]{.greek-omitted} [αυτου]{.greek-added} [ιακωβου]{.greek-omitted} και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και [ματθαιον]{.greek-omitted} [μαθαιον]{.greek-added} και θωμαν και ιακωβον [τον]{.greek-omitted} του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

και [ερχονται]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [και]{.greek-added} [συνερχετε]{.greek-added} [συνερχεται]{.corr} παλιν [ο]{.greek-added} οχλος ωστε μη [δυνασθαι]{.greek-omitted} [δυναται]{.greek-added} [αυτοις]{.greek-added} [αυτους]{.corr} [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι [ε[στ]{.unclear}]{.greek-added} [εξεστη]{.greek-omitted} [[εξεστι]{.corr}]{.greek-added}[3:21]{.aside}

και οι γραμματεις οι απο [ιερο]{.greek-added} [ιεροσολυμων]{.greek-omitted} [καταβαντες]{.greek-omitted} [ελεγον]{.greek-omitted} [οτι]{.greek-omitted} [βεελζεβουλ]{.greek-omitted} [εχει]{.greek-omitted} [και]{.greek-omitted} [οτι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αρχοντι]{.greek-omitted} [των]{.greek-omitted} [δαιμονιων]{.greek-omitted} [εκβαλλει]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted}[3:22]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [οι]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [σολυμων]{.greek-added} καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των [δ[ε]{.unclear}]{.greek-added} [δαιμονιων]{.corr} εκβαλλει τα δαιμονια[3:22 | instance no. 2]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται [σταθηναι]{.greek-omitted} [στηναι]{.greek-added} η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου [εισελθων]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπασαι]{.greek-omitted} [αρπασαι]{.greek-added} εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [αρπαση]{.greek-added} [διαρπαση]{.corr}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ [εονχος]{.greek-added} [ενοχος]{.corr} εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω [εστωτες]{.greek-omitted} [εστωντες]{.greek-added} απεστειλαν προς αυτον φωνουντες [αυτον]{.greek-omitted} [αυτω]{.greek-added}[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και [απεκριθη]{.greek-omitted} [αποκριθη]{.greek-added} αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου [και]{.greek-omitted} [αδελφη]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [μητηρ]{.greek-omitted} [εστιν]{.greek-omitted}[3:35]{.aside}

[ος]{.greek-omitted} [γαρ]{.greek-omitted} [αν]{.greek-omitted} [ποιηση]{.greek-omitted} [το]{.greek-omitted} [θελημα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ουτος]{.greek-omitted} [αδελφος]{.greek-omitted} [μου]{.greek-omitted} και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} εστιν[3:35 | instance no. 2]{.aside}

### Chapter 4

και παλιν ηρξατο [διδασκειν]{.greek-omitted} [διδασκεν]{.greek-added} παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη [διδαχη]{.greek-omitted} [διδασκη]{.greek-added} αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα [πετεινα]{.greek-omitted} [πετηνα]{.greek-added} και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν [βαθος]{.greek-omitted} [βατος]{.greek-added} γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και [αναβαι]{.greek-added} αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκειν[ο]{.unclear}ις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρε]{.greek-added} [επιστρεψωσιν]{.greek-omitted} [και]{.greek-omitted} [αφεθη]{.greek-omitted} [αυτοις]{.greek-omitted} [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted}[4:12]{.aside}

[ψωσι]{.greek-added} [ινα]{.greek-omitted} [βλεποντες]{.greek-omitted} [βλεπωσιν]{.greek-omitted} και [αφεθησεται]{.greek-added} [μη]{.greek-omitted} [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [μηποτε]{.greek-omitted} [επιστρεψωσιν]{.greek-omitted} [και]{.greek-omitted} [αφεθη]{.greek-omitted} αυτοις τα αμαρτηματα[4:12 | instance no. 2]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας [τας]{.corr} παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη [σπειρομενοι]{.greek-omitted} [σπειρωμενοι]{.greek-added} οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα [προσκαιροι]{.greek-omitted} [προσκαινοι]{.greek-added} εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και [ουτοι]{.greek-omitted} [ουτι]{.greek-added} εισιν οι εις τας ακανθας [σπειρομενοι]{.greek-omitted} [σπειρωμενοι]{.greek-added} οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι [εισπορευομεναι]{.greek-omitted} [εισπαρευομεναι]{.greek-added} [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και [παραδεκονται]{.greek-added} [παραδεχονται]{.corr} και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι [ο]{.corr} λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην [ουχ]{.corr} ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον [ο]{.greek-omitted} εαν μη φανερωθη ουδε εγενετο [αποκρυθον]{.greek-added} [αποκρυφον]{.corr} αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει [τις]{.greek-omitted} [τι]{.greek-added} εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε [τι]{.greek-omitted} ακουετε εν ω μετρω [με]{.greek-added} [μετρειτε]{.greek-omitted} [μετρηθησεται]{.greek-omitted} [υμιν]{.greek-omitted} [και]{.greek-omitted} [προστεθησεται]{.greek-omitted} [υμιν]{.greek-omitted} [τοις]{.greek-omitted} [ακουουσιν]{.greek-omitted}[4:24]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [βλεπετε]{.greek-omitted} [τι]{.greek-omitted} [ακουετε]{.greek-omitted} [εν]{.greek-omitted} [ω]{.greek-omitted} [μετρω]{.greek-omitted} [μετρειτε]{.greek-omitted} [τρειτε]{.greek-added} μετρηθησεται υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24 | instance no. 2]{.aside}

ος γαρ αν εχη δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν τω [σταχυι]{.greek-omitted} [σταχυ]{.greek-added}[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως [αποστελλει]{.greek-omitted} [αποστελει]{.greek-added} το δρεπανον οτι παρεστηκεν ο [θερισμος]{.greek-omitted} [δερισμος]{.greek-added}[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσω]{.greek-added} την [βασιλειαν]{.greek-omitted} [βασιλειν]{.greek-added} του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως [κοκκον]{.greek-omitted} [κακκωσιν]{.greek-added} [[κακκω]{.corr}]{.greek-added} σιναπεως ος οταν σπαρη επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα [πετεινα]{.greek-omitted} [πετηνα]{.greek-added} του [ουρανου]{.greek-abbr} [κατασκουν]{.greek-added} [κατασκηνουν]{.corr}[4:32]{.aside}

και [αυταις]{.greek-added} [τοιαυταις]{.corr} παραβολαις πολλαις ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και [γινετε]{.greek-added} [γινεται]{.corr} [λαιλαψ]{.greek-omitted} [ανεμου]{.greek-omitted} [μεγαλη]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [κυματα]{.greek-omitted} [επεβαλλεν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [ωστε]{.greek-omitted} [αυτο]{.greek-omitted} [ηδη]{.greek-omitted} [γεμιζεσθαι]{.greek-omitted}[4:37]{.aside}

[και]{.greek-omitted} [γινεται]{.greek-omitted} λαιλαψ ανεμου μεγαλη τα δε κυματα επεβαλλεν εις [το]{.greek-omitted} πλοιον [ωσε]{.greek-added} [ωστε]{.corr} αυτο ηδη γεμιζεσθαι[4:37 | instance no. 2]{.aside}

και ην αυτος επι τη πρυμνη επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι [απολυμεθα]{.greek-added} [απολλυμεθα]{.corr}[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και [η]{.greek-omitted} θαλασσα [υπακουουσιν]{.greek-omitted} [υπακουσιν]{.greek-added} αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γαδδαρηνων]{.greek-added}[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την [κατοικησιν]{.greek-omitted} [κατοικισιν]{.greek-added} ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [ισχυσεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και [δια]{.corr} παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνησι]{.greek-added} [[μνημασι]{.corr}]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και [κραξασας]{.greek-added} [κραξας]{.corr} φωνη μεγαλη ειπεν τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω [εξελθε]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [το]{.greek-omitted} [ακαθαρτον]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted}[5:8]{.aside}

[ελεγεν]{.greek-omitted} [γαρ]{.greek-omitted} [αυτω]{.greek-omitted} εξελθε [το]{.greek-omitted} [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8 | instance no. 2]{.aside}

και επηρωτα αυτον τι σοι ονομα και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλοι]{.greek-added} αυτον πολλα ινα μη [αυτους]{.greek-omitted} αποστειλη [αυτον]{.greek-added} εξω της χωρας[5:10]{.aside}

ην δε [εκει]{.greek-omitted} [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων μεγαλη βοσκομενη [προς]{.greek-added} [τω]{.greek-added} [ορει]{.greek-added}[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον [παντες]{.greek-omitted} οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε [ως]{.greek-omitted} [ωσει]{.greek-added} δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και [απηνγειλαν]{.greek-added} [ανηγγειλαν]{.greek-omitted} [[απηγγειλαν]{.corr}]{.greek-added} εις την πολιν και εις τους αγρους και [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} [το]{.corr} γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} μετ αυτου [η]{.greek-added}[5:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και [αγγειλον]{.greek-added} [αναγγειλον]{.corr} αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιη[σ]{.unclear}ε]{.greek-added} [πεποιηκεν]{.greek-omitted} [[πεποιηκε]{.corr}]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει [οσα]{.greek-omitted} [εποιησεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [παντες]{.greek-omitted} [εθαυμαζον]{.greek-omitted}[5:20]{.aside}

[και]{.greek-omitted} [απηλθεν]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δεκαπολει]{.greek-omitted} οσα εποιησεν [αυτω]{.greek-omitted} [αυτο]{.greek-added} ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20 | instance no. 2]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος [πολυς]{.greek-omitted} [πολλους]{.greek-added} επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου [ερχετε]{.greek-added} [ερχεται]{.corr} εις των [αρχισυναχωγων]{.greek-added} [αρχισυναγωγων]{.corr} ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων επιθης αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και [ακολου]{.greek-added} [ηκολουθει]{.corr} αυτω οχλος [πολυς]{.greek-omitted} [πολλους]{.greek-added} και [θλιβον]{.greek-added} [συνεθλιβον]{.corr} αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [εν]{.greek-added} [αυτη]{.greek-added} [[εαυτη]{.corr}]{.greek-added} οτι καν [των]{.greek-omitted} [ιματιων]{.greek-omitted} [του]{.greek-added} [ιματιου]{.greek-added} αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου [δυνναμιν]{.greek-added} [δυναμιν]{.corr} εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [και]{.greek-omitted} [προσεπεσεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [πασαν]{.greek-omitted} [την]{.greek-omitted} [αληθειαν]{.greek-omitted}[5:33]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [γυνη]{.greek-omitted} [φοβηθεισα]{.greek-omitted} [και]{.greek-omitted} [τρεμουσα]{.greek-omitted} [ειδυια]{.greek-omitted} [ο]{.greek-omitted} [γεγονεν]{.greek-omitted} [επ]{.greek-omitted} [αυτη]{.greek-omitted} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33 | instance no. 2]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

[ετι]{.greek-omitted} [εττι]{.greek-added} αυτου λαλουντος ερχονται απο του [αρχη]{.greek-added} [αρχισυναγωγου]{.corr} λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλεις]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω [συνακολουθησαι]{.greek-omitted} [ακολουθησαι]{.greek-added} ει μη πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} κλ[α]{.unclear}ιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι θορυβεισθε και κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και [την]{.corr} [μητερα]{.greek-abbr} και τους μετ αυτου και [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα κουμι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [μεθερμηευομενον]{.greek-added} [μεθερμηνευομενον]{.corr} το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ [ως]{.greek-added} ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και [διεστ[ι]{.unclear}λατο]{.greek-added} [διεστειλατο]{.corr} αυτοις πολλα ινα μηδεις γνω τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την [πα]{.greek-added} [πα]{.greek-added} [πατριδα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ακολουθουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted}[6:1]{.aside}

[ηλθε]{.greek-added} και [προσεπεσεν]{.greek-added} [αυτω]{.greek-added} [εξηλθεν]{.greek-omitted} [εκειθεν]{.greek-omitted} [και]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πατριδα]{.greek-omitted} [τριδα]{.greek-added} [[τριδα]{.corr}]{.greek-added} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1 | instance no. 2]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη [διδασκειν]{.greek-omitted} [διδακειν]{.greek-added} και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η σοφια η [δοθεισα]{.greek-omitted} [δαθεισα]{.greek-added} αυτω [ινα]{.greek-added} [δε]{.greek-added} και [δυναμειν]{.greek-added} [δυναμεις]{.corr} τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

[ουκ]{.greek-added} [ουχ]{.corr} ουτος [εστιν]{.greek-omitted} [εσιν]{.greek-added} ο τεκτων [ο]{.corr} [υιος]{.greek-abbr} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και [σιμωνος]{.greek-omitted} [σιμονος]{.greek-added} και ουκ εισιν αι αδελφαι [αυται]{.greek-added} [αυτου]{.corr} ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [ο]{.greek-added} [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ [ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμασε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω [διδακων]{.greek-added} [διδασκων]{.corr}[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και [εδιδου]{.greek-omitted} [διδου]{.greek-added} αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν [αιρωσιν]{.greek-omitted} [αρωσιν]{.greek-added} εις οδον ει μη [ραβδον]{.greek-omitted} [ραυδον]{.greek-added} μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσασθαι]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκει[θ]{.unclear}εν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [η]{.greek-omitted} [γομορροις]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [εκεινη]{.greek-omitted}[6:11]{.aside}

[και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [μη]{.greek-omitted} [δεξωνται]{.greek-omitted} [υμας]{.greek-omitted} [μηδε]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [υμων]{.greek-omitted} [εκπορευομενοι]{.greek-omitted} [εκειθεν]{.greek-omitted} [εκτιναξατε]{.greek-omitted} [τον]{.greek-omitted} [χουν]{.greek-omitted} [τον]{.greek-omitted} υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η [γομρροις]{.greek-added} [γομορροις]{.corr} εν ημερα κρισεως η τη πολει [εκεινη]{.greek-omitted} [εκειμη]{.greek-added}[6:11 | instance no. 2]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [αμετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και [ακουσεν]{.greek-added} [ηκουσεν]{.corr} ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ [νερων]{.greek-added} [νεκρων]{.corr} [ηγερθη]{.greek-omitted} [ανεστη]{.greek-added} και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης [ηπεν]{.greek-added} [ειπεν]{.corr} οτι ον εγω απεκεφαλισα ιωαννην ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ [ο]{.greek-omitted} [ηρωδες]{.greek-added} [ηρωδης]{.corr} αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

[εγε]{.greek-added} [ελεγεν]{.greek-omitted} [[ελεγε]{.corr}]{.greek-added} γαρ ο [ιωανν[ο]{.unclear}ς]{.greek-added} [ιωαννης]{.corr} τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι [εχειν]{.greek-omitted} [εκειν]{.greek-added} την γυναικα του αδελφου [σου]{.corr}[6:18]{.aside}

η δε ηρωδιας ενειχεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και [ακουσας]{.greek-omitted} [α[υ]{.unclear}]{.greek-added} [[ακουων]{.corr}]{.greek-added} αυτου πολλα εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης [τοις]{.greek-omitted} [της]{.greek-added} γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν [αυτου]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [χιλιαρχοις]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [πρωτοις]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted}[6:21]{.aside}

[και]{.greek-omitted} [γενομενης]{.greek-omitted} [ημερας]{.greek-omitted} [ευκαιρου]{.greek-omitted} [οτε]{.greek-omitted} [ηρωδης]{.greek-omitted} [τοις]{.greek-omitted} [γενεσιοις]{.greek-omitted} [αυτου]{.greek-omitted} [δειπνον]{.greek-omitted} [εποιει]{.greek-omitted} [τοις]{.greek-omitted} [μεγιστασιν]{.greek-omitted} [αυτου]{.greek-omitted} και τοις [χιλιαρχοις]{.greek-omitted} [χιλιαρχαις]{.greek-added} και [τοις]{.corr} πρωτοις της γαλιλαιας[6:21 | instance no. 2]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με [και]{.greek-added} [δωσω]{.greek-added} [σοι]{.greek-added} ο εαν θελης [και]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted}[6:22]{.aside}

και [ωνοσεν]{.greek-added} [ωμοσεν]{.corr} αυτη οτι [ο]{.corr} εαν [αιτηση]{.greek-added} με [αιτησης]{.greek-omitted} δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} την κεφαλην [ιωανν[ο]{.unclear}ς]{.greek-added} [ιωαννου]{.corr} του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως [αποστειλας]{.greek-omitted} ο βασιλευς [αποστειλας]{.greek-added} σπεκουλατορα [απεκεφαλισεν]{.greek-added} [επεταξεν]{.greek-omitted} [ενεχθηναι]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [αυτου]{.greek-omitted} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι [πινακη]{.greek-added} [πινακι]{.corr} και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν [αυτ[ο]{.unclear}ν]{.greek-added} [αυτην]{.corr} τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι [μαθη]{.greek-added} [μαθηται]{.greek-omitted} [[μαθηαι]{.corr}]{.greek-added} αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυ[―]{.gap}θε]{.greek-added} [αναπαυεσθε]{.corr} ολιγον ησαν γαρ [οι]{.greek-omitted} [ερχομενοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [υπαγοντες]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ουδε]{.greek-omitted} [φαγειν]{.greek-omitted} [ευκαιρουν]{.greek-omitted}[6:31]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [δευτε]{.greek-omitted} [υμεις]{.greek-omitted} [αυτοι]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [εις]{.greek-omitted} [ερημον]{.greek-omitted} [τοπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [ολιγον]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} οι ερχομενοι και [οι]{.greek-omitted} υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31 | instance no. 2]{.aside}

και [απηλθον]{.greek-omitted} [απηλθαν]{.greek-added} εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ειδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο [αυτους]{.greek-added} [διδακειν]{.greek-added} [διδασκειν]{.corr} [αυτους]{.greek-omitted} πολλα[6:34]{.aside}

και ηδη [ωρα]{.greek-added} [ωρας]{.corr} [πολλης]{.greek-omitted} [πολλους]{.greek-added} γενομενης προσελθοντες [αυτω]{.greek-omitted} οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και [η]{.greek-added} [ωρα]{.greek-added} ηδη [ωρα]{.greek-omitted} πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν δηναριων διακοσιων αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και γνοντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και [λαβ[ον]{.unclear}]{.greek-added} [λαβων]{.corr} τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [αλογεισε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [παραθωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [εμερισεν]{.greek-omitted} [πασιν]{.greek-omitted}[6:41]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [αναβλεψας]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [ευλογησεν]{.greek-omitted} [και]{.greek-omitted} [κατεκλασεν]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} αυτου ινα [παραθωσιν]{.greek-omitted} [παρατιθωσιν]{.greek-added} αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41 | instance no. 2]{.aside}

και [εφαγον]{.greek-omitted} [εφρον]{.greek-added} παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι [φαγοντες]{.greek-omitted} [φροντες]{.greek-added} τους αρτους [πεντακιχιλιοι]{.greek-added} [πεντακισχιλιοι]{.corr} [αδρες]{.greek-added} [ανδρες]{.corr}[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου [εμβηναι]{.greek-omitted} [εβληναι]{.greek-added} εις το πλοιον και προαγειν εις [το]{.greek-omitted} περαν προς βηθσαιδαν εως αυτος απολυση τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον [μεσον]{.greek-added} [εν]{.greek-omitted} [μεσω]{.greek-omitted} της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος [ερχετε]{.greek-added} [ερχεται]{.corr} προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} [παρελθειν]{.greek-omitted} [περελθειν]{.greek-added} αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη [φοβ[η]{.unclear}σθε]{.greek-added} [φοβεισθε]{.corr}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και [εθαυμαο]{.greek-added} [εθαυμαζον]{.corr}[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} [πεπωρωμενη]{.greek-omitted} [πεπωρρωμενη]{.greek-added}[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γεννισαρετ]{.greek-added} [και]{.corr} [προσωρμισαν]{.greek-added} [προσωρμισθησαν]{.corr}[6:53]{.aside}

και εξελθοντων αυτων [εκ]{.greek-omitted} [απο]{.greek-added} του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας [πεφερειν]{.greek-added} [περιφερειν]{.corr} οπου [ηκουν]{.greek-added} [ηκουον]{.corr} οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις [ετιθουντ[ε]{.unclear}ς]{.greek-added} [ετιθουν]{.corr} τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο [αυτου]{.greek-omitted} εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και [πατες]{.greek-added} [παντες]{.corr} οι ιουδαιοι εαν μη πυγμη [νιψωται]{.greek-added} [νιψωνται]{.corr} τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και [απο]{.greek-omitted} [απ]{.greek-added} αγορας εαν μη [βαπτι[ζ]{.unclear}ονται]{.greek-added} [βαπτισωνται]{.greek-omitted} [[βαπτισονται]{.corr}]{.greek-added} ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και [χαλκιων]{.greek-omitted} [χαλκειων]{.greek-added} και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπαστουσι]{.greek-added} κατα την παραδοσιν των πρεσβυτερων αλλα ανιπτοις [χερισιν]{.greek-added} [χερσιν]{.corr} [εστ]{.greek-added} [εσθιουσιν]{.corr} [τον]{.greek-omitted} αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [με]{.greek-omitted} [τιμα]{.greek-omitted} [η]{.greek-omitted} [δε]{.greek-omitted} [καρδια]{.greek-omitted} [αυτων]{.greek-omitted} [πορρω]{.greek-omitted} [απεχει]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted}[7:6]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [οτι]{.greek-omitted} [καλως]{.greek-omitted} [προεφητευσεν]{.greek-omitted} [ησαιας]{.greek-omitted} [περι]{.greek-omitted} [υμων]{.greek-omitted} [των]{.greek-omitted} [υποκριτων]{.greek-omitted} [ως]{.greek-omitted} [γεγραπται]{.greek-omitted} [ουτος]{.greek-omitted} [ο]{.greek-omitted} [λαος]{.greek-omitted} [τοις]{.greek-omitted} [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6 | instance no. 2]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} [αυτου]{.greek-added} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και παρομοια τοιαυτα πολ[λ]{.unclear}α ποι[ε]{.unclear}ιτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} [τα]{.greek-omitted} κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο [του]{.corr} οχλου επηρωτων αυτον οι μαθηται αυτου περι της [παραβολ[ο]{.unclear}ς]{.greek-added} [παραβολης]{.corr}[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν [εισ]{.greek-added} [εισπορευομενον]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted}[7:18]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ουτως]{.greek-omitted} [και]{.greek-omitted} [υμεις]{.greek-omitted} [ασυνετοι]{.greek-omitted} [εστε]{.greek-omitted} [ου]{.greek-omitted} [νοειτε]{.greek-omitted} [οτι]{.greek-omitted} [παν]{.greek-omitted} [το]{.greek-omitted} [εξωθεν]{.greek-omitted} [εισπορευομενον]{.greek-omitted} [πορευομενον]{.greek-added} εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον [κοινωσαι]{.greek-omitted} [κοιμωσαι]{.greek-added}[7:18 | instance no. 2]{.aside}

οτι ουκ [εισπορευεται]{.greek-omitted} [εισπορευεσται]{.greek-added} αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα [εκπορευεται]{.greek-omitted} [πορευεται]{.greek-added} καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κ[ο]{.unclear}ινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι [δολος]{.greek-omitted} [δολοι]{.greek-added} [ασελγεια]{.greek-omitted} [ασελγειαι]{.greek-added} οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις [οικιαν]{.greek-omitted} [οικον]{.greek-added} ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια [εσθιει]{.greek-added} υποκατω της τραπεζης [εσθιει]{.greek-omitted} απο των ψιχιων των [πεδιον]{.greek-added} [παιδιων]{.corr}[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον [αυτης]{.greek-omitted} [ευρεν]{.greek-omitted} [το]{.greek-omitted} [δαιμονιον]{.greek-omitted} [εξεληλυθος]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [θυγατερα]{.greek-omitted} [βεβλημενην]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κλινης]{.greek-omitted}[7:30]{.aside}

[και]{.greek-omitted} [απελθουσα]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα [ββλημενην]{.greek-added} [βεβλημενην]{.corr} επι της κλινης[7:30 | instance no. 2]{.aside}

και παλιν εξελθων εκ των [οριων]{.greek-omitted} [οριον]{.greek-added} τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και [απολαβομενος]{.greek-omitted} [επιλαβομενος]{.greek-added} αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} [τους]{.corr} δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλωσης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [[ουρανων]{.greek-abbr}]{.greek-added} [[ουρανον]{.greek-abbr}]{.corr} [εστεναξεν]{.greek-omitted} [εστενεξε]{.greek-added} και λεγει αυτω [εφφαθα]{.greek-omitted} [εφαθα]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως [διηνοιχθησαν]{.greek-omitted} [δηνοιχθησαν]{.greek-added} αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει [ορθως]{.greek-omitted} [ορθων]{.greek-added}[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι [ειπωσιν]{.greek-omitted} [ειποσιν]{.greek-added} οσον δε αυτος αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και [τους]{.greek-omitted} αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παλυ]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου οντος και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

[σπα]{.greek-added} [σπλαγχνιζομαι]{.corr} επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων [απο]{.greek-added} μακροθεν ηκουσιν[8:3]{.aside}

και απεκριθησαν [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [ποθεν]{.greek-omitted} [τουτους]{.greek-omitted} [δυνησεται]{.greek-omitted} [τις]{.greek-omitted} [ωδε]{.greek-omitted} [χορτασαι]{.greek-omitted} [αρτων]{.greek-omitted} [επ]{.greek-omitted} [ερημιας]{.greek-omitted}[8:4]{.aside}

[και]{.greek-omitted} [απεκριθησαν]{.greek-omitted} αυτω οι μαθηται αυτου ποθεν τουτους [δυνησετε]{.greek-added} [δυνησεται]{.corr} τις ωδε χορτασαι αρτων επ ερημιας[8:4 | instance no. 2]{.aside}

και [επηρωτα]{.greek-omitted} [επληρωτα]{.greek-added} αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδιδου]{.greek-omitted} [διδου]{.greek-added} τοις μαθηταις αυτου ινα [παραδωσι]{.greek-added} [παραθωσιν]{.greek-omitted} [[παραθωσι]{.corr}]{.greek-added} και παρεθηκαν τω [οκλω]{.greek-added} [οχλω]{.corr}[8:6]{.aside}

και ειχον [και]{.greek-added} ιχθυδια ολιγα και [ταυτα]{.greek-added} ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παραθειναι και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν [παντες]{.greek-added} και ηραν [περισσε[υ]{.unclear}α]{.greek-added} [περισσευματα]{.greek-omitted} [[περισσε[υμ]{.unclear}α]{.corr}]{.greek-added} [τα]{.greek-added} κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες [ως]{.greek-omitted} [[ωσει]{.corr}]{.greek-added} τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} [ευτεως]{.greek-added} [ευθεως]{.corr} [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη [δαλμανουθα]{.greek-omitted} [μαλδανουθα]{.greek-added}[8:10]{.aside}

και εξηλθον οι φαρισαιοι και [ηρξατο]{.greek-added} [ηρξαντο]{.corr} συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει [δοθησετε]{.greek-added} [δοθησεται]{.corr} τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν [εις]{.corr} [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς [αλληλους]{.greek-omitted} [αγγηλους]{.greek-added} λεγοντες [οτι]{.greek-omitted} [αρτους]{.greek-omitted} [ουκ]{.greek-omitted} [εχομεν]{.greek-omitted}[8:16]{.aside}

[και]{.greek-omitted} [διελογιζοντο]{.greek-omitted} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [λεγοντες]{.greek-omitted} οτι αρτους ουκ εχομεν[8:16 | instance no. 2]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε [ουπο]{.greek-added} [ουπω]{.corr} νοειτε ουδε συνιετε ετι [πεπωρωμενην]{.greek-omitted} [πεπωρρωμενην]{.greek-added} εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους πληρεις κλασματων ηρατε λεγουσιν αυτω [δωδε[―]{.gap}]{.greek-added} [δωδεκα]{.corr}[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [[λεγει]{.corr}]{.greek-added} αυτοις [ουπω]{.greek-added} [πως]{.greek-omitted} [ου]{.greek-omitted} συνιετε[8:21]{.aside}

και ερχεται εις [βυθσαιδαν]{.greek-added} [βηθσαιδαν]{.corr} και φερουσιν αυτω τυφλον και [παρακουλουσιν]{.greek-added} [παρακαλουσιν]{.corr} αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος [την]{.greek-added} [της]{.corr} χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα [αυτ[ω]{.unclear}ν]{.greek-added} [αυτον]{.corr} ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως [δεδρα]{.greek-added} [δενδρα]{.corr} ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και αποκατεσταθη και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} [τηλαγως]{.greek-added} [τηλαυγως]{.corr} απαντας[8:25]{.aside}

και απεστειλεν αυτον εις [τον]{.greek-omitted} οικον αυτου λεγων μηδε εις την [κο[μ]{.unclear}]{.greek-added} [κωμην]{.corr} εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων [αυτοις]{.greek-omitted} [τινα]{.greek-omitted} [με]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} [ειναι]{.greek-omitted}[8:27]{.aside}

[και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [κωμας]{.greek-omitted} [καισαρειας]{.greek-omitted} [της]{.greek-omitted} [φιλιππου]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [επηρωτα]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγων]{.greek-omitted} αυτοις τινα με λεγουσιν οι [οι]{.greek-added} [ανθρωποι]{.greek-abbr} ειναι[8:27 | instance no. 2]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους [[και]{.unclear}]{.greek-added} [οτι]{.corr} δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παλλα]{.greek-added} [πολλα]{.corr} παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και [των]{.greek-omitted} αρχιερεων και [των]{.greek-omitted} γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και [παρ[―]{.gap}σια]{.greek-added} [παρρησια]{.corr} τον [λεγον]{.greek-added} [λογον]{.corr} ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} επιστραφεις [και]{.greek-omitted} ιδων τους μαθητας αυτου [επι]{.greek-added} [επετιμησεν]{.greek-omitted} [[επετιμησε]{.corr}]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου [ακολουθειν]{.greek-omitted} [ελθειν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[8:34]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την εαυτου ψυχην ενεκεν εμου και του [ευανγελιου]{.greek-added} [ευαγγελιου]{.corr} ουτος σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} εαν κερδηση τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη [μοιχα]{.greek-added} [μοιχαλιδι]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλω]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [επαισχυνθησεται]{.greek-omitted} [αυτον]{.greek-omitted} [οταν]{.greek-omitted} [ελθη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δοξη]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [αυτου]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted}[8:38]{.aside}

[λιδι]{.greek-added} [ος]{.greek-omitted} [γαρ]{.greek-omitted} [εαν]{.greek-omitted} [επαισχυνθη]{.greek-omitted} [με]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [λογους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [γενεα]{.greek-omitted} [ταυτη]{.greek-omitted} [τη]{.greek-omitted} [μοιχαλιδι]{.greek-omitted} και αμαρτωλω και [ο]{.greek-omitted} [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των [αγιων]{.greek-omitted} [αγειων]{.greek-added}[8:38 | instance no. 2]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} [εληλυθυιαν]{.greek-omitted} [εληλυθυαν]{.greek-added} εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ [παραλαμβανει]{.greek-omitted} [παραλαβανει]{.greek-added} ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και [μετεμ[―]{.gap}ωθη]{.greek-added} [μετεμορφωθη]{.corr} εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο [στη]{.greek-added} [στιλβοντα]{.corr} λευκα λιαν [ως]{.greek-omitted} [ωσει]{.greek-added} χιων οια [γναφευς]{.greek-omitted} [κναφευς]{.greek-added} επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις [ηλη]{.greek-added} [ηλιας]{.corr} συν [μωση]{.greek-omitted} [μωσει]{.greek-added} και ησαν συλλαλουντες [στω]{.greek-added} [τω]{.corr} [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυση]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα αυτοις και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα [ειδων]{.greek-added} [ειδον]{.corr} αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

[καταβε]{.greek-added} [καταβαινοντων]{.corr} δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι διηγησωνται α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} [αναστηναι]{.greek-omitted}[9:10]{.aside}

[και]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [εκρατησαν]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [συζητουντες]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} εκ νεκρων αναστηναι[9:10 | instance no. 2]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα [καθως]{.greek-added} [και]{.greek-omitted} [πως]{.greek-omitted} γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι [και]{.greek-omitted} ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν [εν]{.greek-added} αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [διδασκε]{.greek-added} [διδασκαλε]{.corr} ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} [αλλαλον]{.greek-added} [αλαλον]{.corr}[9:17]{.aside}

και οπου [αν]{.greek-omitted} [εαν]{.greek-added} αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και [ξηραινετε]{.greek-added} [ξηραινεται]{.corr} και [ειπον]{.greek-omitted} [ειπεν]{.greek-added} τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} και ουκ [ιχυσαν]{.greek-added} [ισχυσαν]{.corr}[9:18]{.aside}

ο δε αποκριθεις [αυτω]{.greek-omitted} [αυτοις]{.greek-added} λεγει ω [γεν[σ]{.unclear}αι]{.greek-added} [γενεα]{.greek-omitted} [[γενεαι]{.corr}]{.greek-added} [απιστος]{.greek-omitted} [απηστος]{.greek-added} εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι [την]{.greek-added} [της]{.corr} γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο [γεγονεν]{.greek-omitted} [γεγον]{.greek-added} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [παιδιοθεν]{.greek-omitted}[9:21]{.aside}

[εν]{.greek-added} [και]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [ποσος]{.greek-omitted} [χρονος]{.greek-omitted} [εστιν]{.greek-omitted} [ως]{.greek-omitted} [τουτο]{.greek-omitted} [γεγονεν]{.greek-omitted} αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21 | instance no. 2]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημι[ν]{.unclear} [σ]{.unclear}πλαγχνισθεις [εφ]{.greek-omitted} ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} [βοηθ[η]{.unclear}]{.greek-added} [βοηθει]{.corr} μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω [εξελθε]{.greek-omitted} [εξελε]{.greek-added} εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα [σπαξαν]{.greek-added} [σπαραξαν]{.corr} αυτον εξηλθεν και [εγενετο]{.greek-omitted} [εγινετο]{.greek-added} ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος [ηγειρεν]{.greek-omitted} [ηγερεν]{.greek-added} αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν [οτι]{.greek-omitted} [διατι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει [μ]{.unclear}η [εν]{.corr} [προσε[―]{.gap}χη]{.greek-added} [προσευχη]{.corr} και νηστεια[9:29]{.aside}

και [εκειθε]{.greek-added} [εκειθεν]{.corr} εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ [ηθεν]{.greek-added} [ηθελεν]{.corr} ινα τις γνω[9:30]{.aside}

[διδασκ[―]{.gap}]{.greek-added} [εδιδασκεν]{.greek-omitted} [[εδιδασκε]{.corr}]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το [ρ[ο]{.unclear}μα]{.greek-added} [ρημα]{.corr} και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν [εις]{.greek-omitted} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} καπερναουμ και εν τη οικια γενομενος [επηρωτα]{.greek-omitted} [επιρωτα]{.greek-added} αυτους τι εν τη οδω προς [εαυτους]{.greek-omitted} [διελογιζεσθε]{.greek-omitted}[9:33]{.aside}

[και]{.greek-omitted} [ηλθεν]{.greek-omitted} ει[ς]{.unclear} [[ε[π]{.unclear}]{.corr}]{.greek-added} [καπερναουμ]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [γενομενος]{.greek-omitted} [επηρωτα]{.greek-omitted} αυτους [τι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} διελογιζεσθε[9:33 | instance no. 2]{.aside}

οι δε εσιωπων προς αλληλους [γρ]{.greek-added} [γαρ]{.corr} [διελεχθησαν]{.greek-omitted} [διειλεχθησαν]{.greek-added} εν τη οδω τις [μηζων]{.greek-added} [μειζων]{.corr}[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι εσται παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

[ος]{.greek-omitted} [ως]{.greek-added} εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε [δεχεται]{.greek-omitted} [δεχετε]{.greek-added} και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε αυτω ιωαννης λεγων διδασκαλε ειδομεν τινα τω ονοματι σου [εκβαλλοντα]{.greek-omitted} [εκβαλοντα]{.greek-added} [δειμονια]{.greek-added} [δαιμονια]{.corr} ος ουκ [ακολουθη]{.greek-added} [ακολουθει]{.corr} ημιν [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και [δυνησ[―]{.gap}]{.greek-added} [δυνησεται]{.corr} ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστι]{.greek-added} [καθ]{.greek-added} [ημων]{.greek-added} [υπερ]{.greek-added} [ημων]{.greek-added} [η]{.greek-added} εστιν [καθ]{.greek-omitted} [υμων]{.greek-omitted} [υπερ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted}[9:40]{.aside}

ος γαρ αν ποτιση υμας [ποτηριο[―]{.gap}]{.greek-added} [ποτηριον]{.corr} υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεστη]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} [κυλλον]{.greek-omitted} [κυλον]{.greek-added} εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το [πυρ]{.greek-omitted} [τυρ]{.greek-added} το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και [εαν]{.corr} ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [γαρ]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν [σε]{.greek-added} εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το [ασβεστον]{.greek-omitted} [ασβλεστον]{.greek-added}[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το [πυρ]{.greek-omitted} [τυρ]{.greek-added} ου [σβεννυτε]{.greek-added} [σβεννυται]{.corr}[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις [την]{.greek-omitted} βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο [σκωξληξ]{.greek-added} [σκωληξ]{.corr} αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν [ανασας]{.greek-added} [αναστας]{.corr} ερχεται εις τα ορια της ιουδαιας δια του περαν του [ιοδανος]{.greek-added} [ιορδανου]{.greek-omitted} [[ιοδανου]{.corr}]{.greek-added} και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν [εδιδακεν]{.greek-added} [εδιδασκεν]{.corr} αυτους[10:1]{.aside}

και προσελθοντες φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μουσης]{.greek-added} [μωσης]{.greek-omitted} [[μωυσης]{.corr}]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης [κτη]{.greek-added} [κτισεως]{.corr} αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και [της]{.greek-added} [την]{.corr} [μητερα]{.greek-abbr} και [προσκολληθησεται]{.greek-omitted} [προς]{.greek-omitted} [προσ]{.greek-added} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [αυτου]{.greek-omitted}[10:7]{.aside}

[ενεκεν]{.greek-omitted} [τουτου]{.greek-omitted} [καταλειψει]{.greek-omitted} [ανθρωπος]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [και]{.greek-omitted} [προσκολληθησεται]{.greek-omitted} [σκολληθησεται]{.greek-added} προς την [γυναικαι]{.greek-added} [γυναικα]{.corr} αυτου[10:7 | instance no. 2]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη [οικινα]{.greek-added} [οικια]{.corr} παλιν οι μαθηται αυτου περι του αυτου επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις [ως]{.greek-added} [ος]{.corr} εαν απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν [η]{.greek-omitted} [ο]{.greek-added} βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη [εισελθειν]{.greek-added} [εισελθη]{.corr} εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ευλογησεν]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} [πλουσιος]{.greek-added} προσδραμων [εις]{.greek-omitted} και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} [τιμα]{.greek-omitted} [τινα]{.greek-added} τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν [[ειπε]{.corr}]{.greek-added} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} ταυτα παντα εφυλαξαμην εκ νεοτητος μου [τι]{.greek-added}[10:20]{.aside}

[ετι]{.greek-added} [υστερω]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ταυτα]{.greek-omitted} [παντα]{.greek-omitted} [εφυλαξαμην]{.greek-omitted} [εκ]{.greek-omitted} [νεοτητος]{.greek-omitted} [μου]{.greek-omitted}[10:20 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-omitted} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν [σοι]{.greek-omitted} [σε]{.greek-added} υστερει υπαγε οσα εχεις [πολησον]{.greek-added} [πωλησον]{.corr} και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} [λυπουμενος]{.greek-omitted} [λυπτουμενος]{.greek-added} ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες [εισελευσονται]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} [εισελευσονται]{.greek-omitted}[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις [τεκνα]{.greek-omitted} πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον [δυα]{.greek-added} [δια]{.corr} [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [τω]{.greek-added} [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η [δελφους]{.greek-added} [αδελφους]{.corr} η [δεφας]{.greek-added} [αδελφας]{.greek-omitted} [[αδεφας]{.corr}]{.greek-added} η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} του [ευαγγελιου]{.greek-omitted} [ευαλλελιου]{.greek-added}[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [μητερας]{.greek-omitted} [και]{.greek-omitted} [τεκνα]{.greek-omitted} [και]{.greek-omitted} [αγρους]{.greek-omitted} [μετα]{.greek-omitted} [διωγμων]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αιωνι]{.greek-omitted} [τω]{.greek-omitted} [ερχομενω]{.greek-omitted} [ζωην]{.greek-omitted} [αιωνιον]{.greek-omitted}[10:30]{.aside}

[εαν]{.greek-omitted} [μη]{.greek-omitted} [λαβη]{.greek-omitted} [εκατονταπλασιονα]{.greek-omitted} [νυν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [καιρω]{.greek-omitted} [τουτω]{.greek-omitted} [οικιας]{.greek-omitted} και [αδελφους]{.greek-omitted} [και]{.greek-omitted} [αδελφας]{.greek-omitted} [και]{.greek-omitted} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω [αιωνι]{.greek-omitted} [αιων]{.greek-added} τω ερχομενω ζωην αιωνιον[10:30 | instance no. 2]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν [τοδω]{.greek-added} [τη]{.corr} [οδω]{.corr} αναβαινοντες εις [ιεροσολυμα]{.greek-omitted} [ιεροσολιμα]{.greek-added} και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα [μελοντα]{.greek-added} [μελλοντα]{.corr} αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις [εις]{.greek-added} [ιεροσολυμα]{.greek-omitted} [ιεροσολιμα]{.greek-added} και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και εμπαιξουσιν [αυτον]{.greek-added} [αυτω]{.corr} και μαστιγωσουσιν αυτον και εμπτυσουσιν αυτω και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν [ινα]{.greek-omitted} ο εαν αιτησωμεν [ποιησι]{.greek-added} [ποιησης]{.corr} ημιν[10:35]{.aside}

[οι]{.greek-added} [δε]{.greek-added} [ειπον]{.greek-added} [αυτω]{.greek-added} ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτοις]{.greek-omitted} τι θελετε [ποιησαι]{.corr} [με]{.corr} υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ [ευωνυμ[ον]{.unclear}]{.greek-added} [ευωνυμων]{.corr} σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω [βαπτιομαι]{.greek-added} [βαπτιζομαι]{.corr} βαπτισθηναι[10:38]{.aside}

οι δε [ειπον]{.greek-omitted} [λεγουσιν]{.greek-added} αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω [πιεσθε]{.greek-omitted} [πινεσθε]{.greek-added} και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ευωνυμων]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [εμον]{.greek-omitted} [δουναι]{.greek-omitted} [αλλ]{.greek-omitted} [οις]{.greek-omitted} [ητοιμασται]{.greek-omitted}[10:40]{.aside}

[το]{.greek-omitted} [δε]{.greek-omitted} [καθισαι]{.greek-omitted} εκ δεξιων μου και εξ ευωνυμων ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40 | instance no. 2]{.aside}

και ακουσαντες οι [δεκα]{.greek-omitted} [δωδεκα]{.greek-added} ηρξαντο [αγανακτειν]{.greek-omitted} [αγανκτειν]{.greek-added} [[αγανκατειν]{.corr}]{.greek-added} περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων [[―]{.gap}τακυριβυουσιν]{.greek-added} [κατακυριευουσιν]{.greek-omitted} [[κατακυριβυουσιν]{.corr}]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη [γενεσται]{.greek-added} [γενεσθαι]{.corr} μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη υμων γενεσθαι πρωτος εσται παντων [δουλον]{.greek-added} [δουλος]{.corr}[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [ο]{.greek-added} [υιος]{.greek-abbr} τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} [ελεσον]{.greek-added} [ελεησον]{.corr} με[10:47]{.aside}

και επετιμων [αυτω]{.greek-omitted} [αυτων]{.greek-added} [[αυτον]{.corr}]{.greek-added} πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε δαυιδ ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει [σει]{.greek-added} [σε]{.corr}[10:49]{.aside}

ο δε αποβαλων το ιματιον [αυτον]{.greek-added} [αυτου]{.corr} αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} λεγει αυτω [ο]{.greek-omitted} [ιησους]{.greek-omitted} τι [σοι]{.greek-added} θελεις ποιησω [σοι]{.greek-omitted} ο δε τυφλος ειπεν αυτω [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ινα [αναβλεψω]{.greek-omitted}[10:51]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τι]{.greek-omitted} [θελεις]{.greek-omitted} [ποιησω]{.greek-omitted} [σοι]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [τυφλος]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ραββουνι]{.greek-omitted} [ινα]{.greek-omitted} αναβλεψω[10:51 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και [ηκολουθη]{.greek-added} [ηκολουθει]{.corr} τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερασαλημ]{.greek-added} [ιερουσαλημ]{.corr} εις [βηθσφαγη]{.greek-omitted} [βιθαφαγη]{.greek-added} και βηθανιαν προς το ορος των [ελ[ε]{.unclear}ων]{.greek-added} [ελαιων]{.corr} αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.corr} πωλον δεδεμενον εφ ον [ουπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκε]{.greek-added} λυσαντες αυτον [αγγετε]{.greek-added} [αγαγετε]{.corr}[11:2]{.aside}

και εαν τις [υμιν]{.greek-omitted} [υμις]{.greek-added} ειπη τι ποιειτε [τουτο]{.greek-omitted} [τουτω]{.greek-added} ειπατε οτι [ο]{.greek-omitted} [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον [τον]{.greek-added} [πολ]{.greek-added} [πωλον]{.corr} δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει [εστηκοτων]{.greek-omitted} [εστηκοντων]{.greek-added} ελεγον αυτοις τι [ποιητε]{.greek-added} [ποιειτε]{.corr} λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και [επε[ε]{.unclear}]{.greek-added} [επεβαλον]{.corr} [επ]{.greek-added} αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added} [και]{.greek-added} αλλοι [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ των δενδρων και [εστρωννυον]{.greek-omitted} [εστρωνυον]{.greek-added} [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

[και]{.greek-added} ευλογημενη η ερχομενη βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} [εν]{.greek-added} [ονοματι]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} ωσαννα εν τοις [υψιστοις]{.greek-omitted}[11:10]{.aside}

[ευλογημενη]{.greek-omitted} [η]{.greek-omitted} [ερχομενη]{.greek-omitted} [βασιλεια]{.greek-omitted} [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [ημων]{.greek-omitted} [δαυιδ]{.greek-omitted} [ωσαννα]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} υψιστοις[11:10 | instance no. 2]{.aside}

και εισηλθεν εις [ιεροσολυμα]{.greek-omitted} [ιεροσολιμα]{.greek-added} ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα [και]{.greek-added} οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην [μιαν]{.greek-added} [μακ[―]{.gap}οθεν]{.greek-added} [μακροθεν]{.corr} [ε[σ]{.unclear}χουσαν]{.greek-added} [εχουσαν]{.corr} φυλλα ηλθεν ει αρα ευρησει τι εν αυτη και ελθων επ αυτην ουδεν [ευρεν]{.greek-omitted} [ευρε]{.greek-added} ει μη [φιλλα]{.greek-added} [φυλλα]{.corr} ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον [φαγοι]{.greek-omitted} [φαγη]{.greek-added} και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις [ιεροσολυμα]{.greek-omitted} [ιεροσολιμα]{.greek-added} και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και αγοραζοντας εν τω ιερω και [τραπεζας]{.greek-added} [των]{.greek-added} [κολυβιστων]{.greek-added} [και]{.greek-added} τας τραπεζας [των]{.greek-omitted} [κολλυβιστων]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [καθεδρας]{.greek-omitted} των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [διδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε [αυτον]{.greek-added} εποιησατε [αυτον]{.greek-omitted} σπηλαιον [ληστων]{.greek-omitted} [ληστρων]{.greek-added}[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν [εφοβουντο]{.greek-omitted} [εφοβουν]{.greek-added} γαρ [αυτον]{.greek-omitted} οτι πας ο οχλος [εξεπλησσετο]{.greek-omitted} [εξεπλησσοντο]{.greek-added} επι τη [διδασχη]{.greek-added} [διδαχη]{.corr} αυτου[11:18]{.aside}

και [οτε]{.greek-omitted} [οταν]{.greek-added} οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην [εξηραμενην]{.greek-added} [εξηραμμενην]{.corr} εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω [ραββι]{.greek-omitted} [ιδε]{.greek-omitted} [η]{.greek-omitted} [συκη]{.greek-omitted} [ην]{.greek-omitted} [κατηρασω]{.greek-omitted} [εξηρανται]{.greek-omitted}[11:21]{.aside}

[και]{.greek-omitted} [αναμνησθεις]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα πιστευση οτι α λεγει γινεται εσται αυτω ο εαν ειπη [τω]{.greek-added}[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα [αν]{.greek-omitted} [εαν]{.greek-added} προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθε]{.greek-added} πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι αφιετε ει τι εχετε κατα τινος [ινα]{.greek-omitted} [ιν]{.greek-added} και ο [[πατρος]{.greek-abbr}]{.greek-added} [[πατηρ]{.greek-abbr}]{.corr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα [παραπταματα]{.greek-added} [παραπτωματα]{.corr} υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις [ιεροσολυμα]{.greek-omitted} [ιεροσολιμα]{.greek-added} και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added} και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added}[11:27]{.aside}

και λεγουσιν αυτω εν [ποια]{.greek-omitted} [πια]{.greek-added} εξουσια ταυτα ποιεις [και]{.corr} [τις]{.corr} [σοι]{.corr} [[εδωκε]{.corr}]{.greek-added} [την]{.corr} [εξουσιαν]{.greek-omitted} [[εξουεξουσιαν]{.corr}]{.greek-added} [ταυτην]{.corr} [εδωκεν]{.greek-omitted} [ινα]{.corr} [ταυτα]{.corr} [ποιης]{.corr}[11:28]{.aside}

ο [δε]{.corr} [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτοις επερωτησω [υμας]{.greek-omitted} και εγω [[καγω]{.corr}]{.greek-added} [υμας]{.greek-added} ενα λογον και αποκριθητε μοι και ερω υμιν εν [ποια]{.greek-omitted} [πια]{.greek-added} εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο [το]{.greek-added} [τον]{.corr} λαον απαντες γαρ ειχον τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν [και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ουδε]{.greek-omitted} [εγω]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιω]{.greek-omitted}[11:33]{.aside}

και [αποκριθεντες]{.greek-omitted} [αποκριθεις]{.greek-added} [λεγουσιν]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [ουκ]{.greek-omitted} [οιδαμεν]{.greek-omitted} [και]{.greek-omitted} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει [αυτον]{.greek-added} [αυτοις]{.corr} ουδε εγω λεγω υμιν εν [ποια]{.greek-omitted} [πια]{.greek-added} εξουσια ταυτα ποιω[11:33 | instance no. 2]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [αποστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον λιθοβολησαντες εκεφαλαιωσαν και απεστειλαν [ητιμωμενον]{.greek-omitted} [ητιμομενον]{.greek-added}[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} [και]{.greek-added} [κακεινον]{.greek-omitted} [εκεινον]{.greek-added} απεκτειναν και πολλους αλλους τους μεν [δερον]{.greek-added} [δεροντες]{.corr} τους δε [αποκτενοντες]{.greek-omitted} [αποκτεννοντες]{.greek-added}[12:5]{.aside}

[ετι]{.greek-omitted} [ει]{.greek-added} ουν ενα [υιον]{.greek-abbr} εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον [εσχατον]{.greek-added} προς αυτους [εσχατον]{.greek-omitted} λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν [ο]{.greek-omitted} [κληρονος]{.greek-added} [κληρονομος]{.corr} δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και [εφοβηθησαν]{.greek-omitted} [εφονησαν]{.greek-added} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [εγνωσαν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [ειπεν]{.greek-omitted} [και]{.greek-omitted} [αφεντες]{.greek-omitted} [αυτον]{.greek-omitted} [απηλθον]{.greek-omitted}[12:12]{.aside}

[και]{.greek-omitted} [εζητουν]{.greek-omitted} [αυτον]{.greek-omitted} [κρατησαι]{.greek-omitted} [και]{.greek-omitted} εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12 | instance no. 2]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των [ηρωδιανων]{.greek-omitted} [ηροδιανων]{.greek-added} ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι [αλ[ι]{.unclear}θης]{.greek-added} [αληθης]{.corr} ει και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις [πρωσωπον]{.greek-added} [προσωπον]{.corr} [ανθρωπων]{.greek-abbr} αλλ επ αληθειας [την]{.greek-omitted} [τον]{.greek-added} οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [κηνσον]{.greek-omitted} καισαρι δουναι [κηνσον]{.greek-added} η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις τι με πειραζετε φερετε μοι [δεναριον]{.greek-added} [δηναριον]{.corr} ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} [τω]{.corr} [[θεω]{.greek-abbr}]{.corr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται [οι]{.greek-added} [δαδδουκαιοι]{.greek-added} [σαδδουκαιοι]{.corr} προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα [εχ]{.greek-added} [εσχατη]{.greek-omitted} [[εσχατον]{.corr}]{.greek-added} [παντων]{.greek-omitted} [απεθανεν]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted}[12:22]{.aside}

[και]{.greek-omitted} [ελαβον]{.greek-omitted} [αυτην]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [αφηκαν]{.greek-omitted} [σπερμα]{.greek-omitted} [εσχατη]{.greek-omitted} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22 | instance no. 2]{.aside}

εν τη [ουν]{.greek-added} αναστασει [[αναστασε]{.corr}]{.greek-added} οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον [αυτην]{.greek-omitted} [την]{.greek-added} γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [ου]{.greek-omitted} δια τουτο πλανασθε μη [ειδοτες]{.greek-omitted} [ειδοντες]{.greek-added} τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε [των]{.corr} νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} επι [του]{.greek-omitted} [της]{.greek-added} βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} [ι[σα]{.unclear}]{.greek-added} [ιακωβ]{.corr}[12:26]{.aside}

ουκ [εσυν]{.greek-added} [εστιν]{.greek-omitted} [[εσ[τ]{.unclear}υν]{.corr}]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων εις των [γραμματων]{.greek-added} [γραμματεων]{.corr} ακουσας αυτων συζητουντων ειδως οτι [κακως]{.greek-added} [καλως]{.corr} αυτοις απεκριθη επηρωτησεν αυτον [ποια]{.greek-omitted} [πια]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη παντων εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω [οτη]{.greek-added} [οτι]{.corr} πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολη]{.greek-added} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της [ισχυος]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [εξ]{.greek-added} [ολης]{.greek-added} [της]{.greek-added} ψυχης σου και εξ ολης της διανοιας [[και]{.corr}]{.greek-added} [[εξ]{.corr}]{.greek-added} [[ολης]{.corr}]{.greek-added} [[της]{.corr}]{.greek-added} [[ψυχης]{.corr}]{.greek-added} [σου]{.corr} [[και]{.corr}]{.greek-added} [[εξ]{.corr}]{.greek-added} [[ολης]{.corr}]{.greek-added} [[της]{.corr}]{.greek-added} [[διανοιας]{.corr}]{.greek-added} [και]{.corr} [εξ]{.corr} [ολης]{.corr} [της]{.corr} [ισχυος]{.corr} [σου]{.corr} αυτη πρωτη [παντων]{.greek-added} εντολη[12:30]{.aside}

[και]{.greek-omitted} δευτερα [δε]{.greek-added} ομοια αυτη [αγαπασεις]{.greek-added} [αγαπησεις]{.corr} τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων [δε]{.greek-added} τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ [αγα]{.greek-added} [α[λ]{.unclear}ηθειας]{.corr} ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ [ολης]{.greek-omitted} [της]{.greek-omitted} [συνεσεως]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [αγαπαν]{.greek-omitted} [τον]{.greek-omitted} [πλησιον]{.greek-omitted} [ως]{.greek-omitted} [εαυτον]{.greek-omitted} [πλειον]{.greek-omitted} [εστιν]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} [ολοκαυτωματων]{.greek-omitted} [και]{.greek-omitted} [θυσιων]{.greek-omitted}[12:33]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [αγαπαν]{.greek-omitted} [αυτον]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το [απαν]{.greek-added} [αγαπαν]{.corr} τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33 | instance no. 2]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο [της]{.greek-omitted} βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

[και]{.corr} αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} [υιος]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου [εξ]{.greek-added} [εκ]{.corr} δεξιων μου εως αν θω τους [εχθρους]{.greek-omitted} [εχρους]{.greek-added} σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου εστιν και [ο]{.corr} [πολυς]{.greek-omitted} [πολους]{.greek-added} οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη [αυτω]{.greek-added} [αυτου]{.corr} βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του [γαζοφυλακιου]{.greek-omitted} [γαζοφυλακιω]{.greek-added} εθεωρει πως ο οχλος βαλλει χαλκον εις [το]{.corr} γαζοφυλακιον και πολλοι πλουσιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις αμην λεγω υμιν οτι η χηρα αυτη η [πτωχη]{.greek-omitted} [πλειον]{.greek-omitted} [παντων]{.greek-omitted} [βεβληκεν]{.greek-omitted} [των]{.greek-omitted} [βαλλοντων]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [γαζοφυλακιον]{.greek-omitted}[12:43]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [η]{.greek-omitted} [χηρα]{.greek-omitted} [αυτη]{.greek-omitted} [η]{.greek-omitted} πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43 | instance no. 2]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της [υν]{.greek-added} [υστερησεως]{.corr} αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον κατ ιδιαν πετρος και ιακωβος και [ανδρεα]{.greek-added} [και]{.greek-added} [ιωαννης]{.greek-added} [[ανδρεας]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [[ιωαννης]{.corr}]{.greek-added} [ιωαννης]{.corr} [και]{.corr} [ανδρεας]{.corr}[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν [μελλη]{.greek-omitted} [μελη]{.greek-added} [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [συνπελεισθαι]{.greek-added} [συντελεισθαι]{.corr}[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ [ελεσονται]{.greek-added} [ελευσονται]{.corr} επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη [θροεισθε]{.greek-omitted} [θροεισθαι]{.greek-added} δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και [ταρακαι]{.greek-added} [ταραχαι]{.corr} [αρχαι]{.greek-omitted} [αρχη]{.greek-added} [ωδιων]{.greek-added} [ωδινων]{.corr} ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι [ηγεμονον]{.greek-added} [ηγεμονων]{.corr} [και]{.greek-omitted} [βασιλεων]{.greek-omitted} [σταθησεσθε]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted}[13:9]{.aside}

[βλεπετε]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [εαυτους]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [γαρ]{.greek-omitted} [υμας]{.greek-omitted} [εις]{.greek-omitted} [συνεδρια]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [συναγωγας]{.greek-omitted} [δαρησεσθε]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [ηγεμονων]{.greek-omitted} και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9 | instance no. 2]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το [ευανγελιον]{.greek-added} [ευαγγελιον]{.corr}[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη προμεριμνατε τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και [θανατωσουσιν]{.greek-omitted} [θαναθωσουσιν]{.greek-added} αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια [το]{.corr} ονομα μου ο δε υπομεινας εις τελος ουτος [σωθησετε]{.greek-added} [σωθησεται]{.corr}[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο [αναγιωσκων]{.greek-added} [αναγινωσκων]{.corr} νοειτω τοτε [οι]{.corr} εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις [την]{.corr} οικιαν μηδε εισελθετω [τι]{.greek-added} αραι [τι]{.greek-omitted} εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον [αγρον]{.corr} ων μη επιστρεψατω [εις]{.greek-omitted} [τα]{.greek-omitted} οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρ[ι]{.unclear} εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου [γεγενε]{.greek-added} [γεγονεν]{.greek-omitted} [[γεγονε]{.corr}]{.greek-added} τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} [ουκ]{.greek-omitted} [αν]{.greek-omitted} [εσωθη]{.greek-omitted} [πασα]{.greek-omitted} [σαρξ]{.greek-omitted} [αλλα]{.greek-omitted} [δια]{.greek-omitted} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted} [ους]{.greek-omitted} [εξελεξατο]{.greek-omitted} [εκολοβωσεν]{.greek-omitted} [τας]{.greek-omitted} [ημερας]{.greek-omitted}[13:20]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [κυριος]{.greek-omitted} [εκολοβωσεν]{.greek-omitted} [τας]{.greek-omitted} [ημερας]{.greek-omitted} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας[13:20 | instance no. 2]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} [η]{.greek-omitted} [και]{.greek-added} ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το [αποπα]{.greek-added} [αποπλαναν]{.corr} ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν [παντα]{.greek-omitted} [απαντα]{.greek-added}[13:23]{.aside}

[αλλα]{.greek-added} [αλλ]{.corr} [εν]{.corr} εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και [οι]{.greek-omitted} αστερες [εσονται]{.greek-added} [εκ]{.greek-added} του [ουρανου]{.greek-abbr} [εσονται]{.greek-omitted} [εκπιπτοντες]{.greek-omitted} [πιπτοντες]{.greek-added} και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν [νεφελες]{.greek-added} [νεφελαις]{.corr} μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου [της]{.greek-added} γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν [αυτης]{.greek-omitted} [ηδη]{.greek-omitted} [ιδητε]{.greek-added} [οτι]{.greek-added} [ελαδος]{.greek-added} [ο]{.corr} [κλαδος]{.corr} [αυτης]{.greek-added} [γενηται]{.greek-added} απαλος [γενηται]{.greek-omitted} και εκφυη τα φυλλα [τοτε]{.greek-added} γινωσκετε οτι εγγυς το θερος [εστιν]{.greek-omitted}[13:28]{.aside}

[ωτως]{.greek-added} [ουτως]{.corr} και υμεις οταν [ιδητε]{.greek-added} ταυτα [ιδητε]{.greek-omitted} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν [οτι]{.greek-omitted} ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [ωρας]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ουδε]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [ουδε]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted}[13:32]{.aside}

[και]{.greek-added} [περι]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} [η]{.greek-omitted} ωρας ουδεις οιδεν ουδε οι αγγελοι [των]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32 | instance no. 2]{.aside}

βλεπετε [αγρουνειτε]{.greek-added} [αγρυπνειτε]{.greek-omitted} [[αγρουπνειτε]{.corr}]{.greek-added} και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα [γρη[ζ]{.unclear}ορη]{.greek-added} [γρηγορη]{.corr}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας [ερχετε]{.greek-added} [ερχεται]{.corr} οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω [γρη[ζ]{.unclear}ορειτε]{.greek-added} [γρηγορειτε]{.corr}[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και [οι]{.corr} γραμματεις πως αυτον εν δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης [πολυτους]{.greek-added} [πολυτελους]{.corr} και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο [το]{.greek-added} [μυρον]{.greek-added} πραθηναι επανω [τριακοσιον]{.greek-added} [τριακοσιων]{.corr} δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αφετε]{.greek-omitted} [αυτην]{.greek-omitted} [τι]{.greek-omitted} [αυτη]{.greek-omitted} [κοπους]{.greek-omitted} [παρεχετε]{.greek-omitted} [καλον]{.greek-omitted} [εργον]{.greek-omitted} [ειργασατο]{.greek-omitted} [εν]{.greek-omitted} [εμοι]{.greek-omitted}[14:6]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} αφετε αυτην τι αυτη κοπους παρεχετε καλον [ερον]{.greek-added} [εργον]{.corr} ειργασατο εν εμοι[14:6 | instance no. 2]{.aside}

παντοτε γαρ τους [πτωκους]{.greek-added} [πτωχους]{.corr} εχετε μεθ εαυτων και οταν θελητε δυνασθε [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην [[δε]{.corr}]{.greek-added} λεγω υμιν οπου [εαν]{.greek-omitted} [αν]{.greek-added} [κηρυχθη]{.greek-omitted} [κηνυχθη]{.greek-added} το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλαντο]{.greek-omitted} [επηγγειλατο]{.greek-added} αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως [[ο]{.unclear}]{.greek-added} [ευκαιρως]{.corr} αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες [ετοιμα[ι]{.unclear}]{.greek-added} [ετοιμασωμεν]{.greek-omitted} [[ετοιμασομεν]{.corr}]{.greek-added} ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το [καταλυμα]{.greek-omitted} [καταλιμα]{.greek-added} οπου το πασχα μετα των μαθητων [μου]{.greek-omitted} φαγω[14:14]{.aside}

και αυτος υμιν δειξει [ανωγεον]{.greek-omitted} [αναγαιον]{.greek-added} μεγα [εστρομενον]{.greek-added} [εστρωμενον]{.corr} ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν [το]{.greek-omitted} [πασχα]{.greek-omitted}[14:16]{.aside}

[και]{.greek-omitted} [εξηλθον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [ευρον]{.greek-omitted} [καθως]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [ητοιμασαν]{.greek-omitted} το πασχα[14:16 | instance no. 2]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν [αυτω]{.greek-omitted} εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} [[ο]{.unclear}]{.greek-added} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδοτε]{.greek-added} καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον [και]{.greek-added} ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν λαβετε [φαγετε]{.greek-omitted} τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων [εκχυνομενον]{.greek-omitted} [εκχυνομενος]{.greek-added}[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος τη[ς]{.unclear} αμπελου εως της ημερας εκεινης οταν αυτο [πινω]{.greek-omitted} [πιω]{.greek-added} καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεθε]{.greek-added} εν εμοι εν τη νυκτι ταυτη οτι γεγραπται [παταξω]{.greek-omitted} [πατοξω]{.greek-added} τον ποιμενα και διασκορπισθησεται τα προβατα [της]{.greek-added} [ποιμνης]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω [υμας]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted}[14:28]{.aside}

[αλλα]{.greek-omitted} [μετα]{.greek-omitted} [το]{.greek-omitted} [εγερθηναι]{.greek-omitted} [με]{.greek-omitted} [προαξω]{.greek-omitted} υμας εις την γαλιλαιαν[14:28 | instance no. 2]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν η δις αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε εκπερισσου [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν με δεη συναποθανειν σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσιμανι]{.greek-added} και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθισασε]{.greek-added} ωδε εως [αν]{.greek-added} [απελθων]{.greek-added} [προσευσομαι]{.greek-added} [προσευξωμαι]{.greek-omitted} [[προσευξομαι]{.corr}]{.greek-added}[14:32]{.aside}

και [παραλαμβανει]{.greek-omitted} [παραλαβανει]{.greek-added} τον πετρον και [τον]{.greek-added} ιακωβον και [τον]{.greek-added} ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημον[ε]{.unclear}ιν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και [γρεγορειτε]{.greek-added} [γρηγορειτε]{.corr}[14:34]{.aside}

και [προσελθων]{.greek-omitted} [προελθων]{.greek-added} μικρον επεσεν επι της γης και προσηυχετο ινα [ει]{.greek-omitted} [η]{.greek-added} δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε [απ]{.greek-added} [εμου]{.greek-added} το ποτηριον [απ]{.greek-omitted} [εμου]{.greek-omitted} τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν [αρ]{.greek-added} [γρ[―]{.gap}]{.greek-added} [γρηγορησαι]{.corr}[14:37]{.aside}

[γρηρορειτε]{.greek-added} [γρηγορειτε]{.corr} και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

[και]{.corr} υποστρεψας ευρεν αυτους παλιν [καθευ]{.greek-added} [καθευδοντας]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [οφθαλμοι]{.greek-omitted} [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδεισαν]{.greek-omitted} [τι]{.greek-omitted} [αυτω]{.greek-omitted} [αποκριθωσιν]{.greek-omitted}[14:40]{.aside}

[δοντας]{.greek-added} [και]{.greek-omitted} [υποστρεψας]{.greek-omitted} [ευρεν]{.greek-omitted} [αυτους]{.greek-omitted} [παλιν]{.greek-omitted} [καθευδοντας]{.greek-omitted} ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καβαρυνομενοι]{.greek-added} [[καταβαρυνομενοι]{.corr}]{.greek-added} και ουκ ηδεισαν τι αυτω [αποκριθωσιν]{.greek-omitted} [αποκριθωσι]{.greek-added}[14:40 | instance no. 2]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου [ο]{.greek-omitted} παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος [πολλους]{.greek-added} [πολυς]{.greek-omitted} [[πολους]{.corr}]{.greek-added} μετα μαχαιρων και ξυλων [παρα]{.greek-omitted} [απο]{.greek-added} των αρχιερεων και [των]{.greek-omitted} γραμματεων και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον [αυτη]{.greek-added} [αυτοις]{.corr} λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει [αυτω]{.greek-omitted} ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας αυτων [επ]{.greek-added} [αυτον]{.greek-added} και [εκρασαν]{.greek-added} [εκρατησαν]{.corr} αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην [προς]{.greek-omitted} [υμας]{.greek-omitted} [μεθ]{.greek-added} [υμων]{.greek-added} εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ[―]{.gap} [[αλλ]{.corr}]{.greek-added} ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος [σινδονα]{.corr} επι γυμνου και [κρατουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[14:51]{.aside}

[και]{.greek-omitted} [εις]{.greek-omitted} [τις]{.greek-omitted} [νεανισκος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted} [περιβεβλημενος]{.greek-omitted} [σινδονα]{.greek-omitted} [επι]{.greek-omitted} [γυμνου]{.greek-omitted} [και]{.greek-omitted} κρατουσιν αυτον οι νεανισκοι[14:51 | instance no. 2]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και [απηγαγαγον]{.greek-added} [απηγαγον]{.corr} τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και συνερχονται αυτω παντες οι αρχιερεις και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added} και [οι]{.corr} [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added}[14:53]{.aside}

και ο πετρος απο μακροθεν [ηκολουθησ[α]{.unclear}ν]{.greek-added} [ηκολουθησεν]{.corr} αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ [αυστου]{.greek-added} [αυτου]{.corr} λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον [τουτον]{.greek-omitted} [τουταν]{.greek-added} τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και [ουδε]{.greek-omitted} [ουδ]{.greek-added} ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις [μεσον]{.greek-omitted} [μεσαν]{.greek-added} [επηρωτησεν]{.greek-omitted} [επηρωτητε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη [ουδεν]{.greek-omitted} [ουδε]{.greek-added} τι ουτοι σου [καταμαρτυροσιν]{.greek-added} [καταμαρτυρουσιν]{.corr}[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους [χιτωναν]{.greek-added} [χιτωνας]{.corr} αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν φαινεται [οι]{.greek-omitted} [δε]{.greek-omitted} [παντες]{.greek-omitted} [κατεκριναν]{.greek-omitted} [αυτον]{.greek-omitted} [ειναι]{.greek-omitted} [ενοχον]{.greek-omitted} [θανατου]{.greek-omitted}[14:64]{.aside}

[ηκουσατε]{.greek-omitted} [της]{.greek-omitted} [βλασφημιας]{.greek-omitted} [τι]{.greek-omitted} [υμιν]{.greek-omitted} [φαινεται]{.greek-omitted} οι δε παντες [κατεκρ]{.greek-supplied}[ι]{.unclear}ναν αυτον ειναι [ε[α]{.unclear}]{.greek-added} [ενοχον]{.corr} θανατου[14:64 | instance no. 2]{.aside}

και η[ρξαντο]{.greek-supplied} [τιν]{.greek-supplied}ες εμπτυειν αυτω και περικαλυπτ[ει]{.unclear}[ν]{.greek-supplied} [το]{.greek-supplied} [προ]{.greek-supplied}σωπον αυτου και κολαφιζειν αυτον και λ[εγειν]{.greek-supplied} [αυτ]{.greek-supplied}ω προφητευσον και οι υπηρεται ραπ[ισμασι]{.greek-supplied}ν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου [εν]{.greek-supplied} [τη]{.greek-supplied} [α]{.unclear}υλη κατω ερχεται μια των παιδισκων του αρ[χ]{.unclear}[ιερ]{.greek-supplied}εως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο [αυτον]{.greek-added} λεγων ουκ [ειδα]{.greek-added} [οιδα]{.corr} ουδε επισταμαι τι συ λεγεις και εξηλθεν εξω εις [το]{.corr} προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστωσιν]{.greek-added} οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνει[ε]{.unclear}]{.greek-added} [ηρνειτο]{.corr} και μετα μικρον παλιν οι παρεστωτες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ [ειδα]{.greek-added} [οιδα]{.corr} τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και ανεμνησθη ο πετρος το ρημα [ο]{.greek-omitted} [ως]{.greek-added} ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των [πρεσβυτερων]{.greek-omitted} [πρεβυτερων]{.greek-added} και γραμματεων και ολον [το]{.greek-omitted} συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος [συ]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [συ]{.greek-omitted} [λεγεις]{.greek-omitted}[15:2]{.aside}

[και]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [πιλατος]{.greek-omitted} συ ει ο βασιλευς των ιο[υ]{.unclear}[δαι]{.greek-supplied}[ω]{.unclear}ν ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2 | instance no. 2]{.aside}

και [[κατη]{.greek-supplied}[ρ]{.unclear}ορουν]{.greek-added} [[κατη]{.greek-supplied}γορουν]{.corr} αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δ[ε]{.greek-supplied}]{.greek-added} [[ου]{.greek-supplied}[δ]{.unclear}εν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος [επηρωτα]{.greek-added} [παλιν]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [α]{.unclear}[υτον]{.greek-supplied} [λ]{.unclear}εγων ουκ αποκρινη [ουδουν]{.greek-added} [ουδεν]{.corr} ιδε ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [μαρτυρουσιν]{.greek-added}[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν [απεκριθη]{.greek-omitted} [αποκριθη]{.greek-added} ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο [λεγ[―]{.gap}μενος]{.greek-added} [λεγομενος]{.corr} βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων [τινα]{.greek-added} θελετε απολυσω υμιν τον βασιλεα των [ιουδε]{.greek-added} [ιουδαιων]{.corr}[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος [παλυν]{.greek-added} [[παλιν]{.corr}]{.greek-added} αποκριθεις [παλιν]{.greek-omitted} ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [λεγοντες]{.greek-added} σταυρωσον αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισως]{.greek-added} [περισσοτερως]{.greek-omitted} [[περισσως]{.corr}]{.greek-added} [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} φραγελλωσας ινα σταυρωθη[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω [της]{.greek-omitted} [αυλης]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [πραιτωριον]{.greek-omitted} [και]{.greek-omitted} [συγκαλουσιν]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [σπειραν]{.greek-omitted}[15:16]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [στρατιωται]{.greek-omitted} [απηγαγον]{.greek-omitted} [αυτον]{.greek-omitted} [εσω]{.greek-omitted} της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16 | instance no. 2]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον [αυαυτω]{.greek-added} [αυτω]{.corr} και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-omitted} [σταυρωσοσιν]{.greek-added} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και σταυρωσαντες αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε [τριτη]{.greek-added} ωρα [τριτη]{.greek-omitted} και [εσταρωσαν]{.greek-added} [εσταυρωσαν]{.corr} αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου [επιγεγραμμενη]{.greek-omitted} [επιγραμμενη]{.greek-added} ο βασιλευς των ιουδαιων[15:26]{.aside}

και [συνν]{.greek-added} [συν]{.corr} αυτω [σταυρουσιν]{.greek-omitted} [σταυρουσι]{.greek-added} δυο ληστας ενα [εκ]{.corr} δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα [ο]{.greek-omitted} [καταλυων]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τρισιν]{.greek-omitted} [ημεραις]{.greek-omitted} [οικοδομων]{.greek-omitted}[15:29]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [παραπορευομενοι]{.greek-omitted} [εβλασφημουν]{.greek-omitted} [αυτον]{.greek-omitted} [κινουντες]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουα]{.greek-omitted} ο καταλυων τον ναον και εν τρισιν [ημεραις]{.greek-omitted} [ημεραυς]{.greek-added} οικοδομων[15:29 | instance no. 2]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς [αυτους]{.greek-added} αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν αυτω και οι συνεσταυρωμενοι αυτω ωνειδιζον αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη ωρα τη [ενατη]{.greek-omitted} [εννατη]{.greek-added} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λ[―]{.gap}μα]{.greek-added} [λιμα]{.corr} σαβαχθανι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες [ε[γ]{.unclear}]{.greek-added} [ελεγον]{.corr} [οτι]{.greek-added} ιδου ηλιαν φωνει[15:35]{.aside}

δραμων [δε]{.greek-omitted} εις και γεμισας σπογγον [οξους]{.greek-omitted} [οσους]{.greek-added} περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν [υ]{.greek-added} [ει]{.corr} ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το [καπετασμα]{.greek-added} [καταπετασμα]{.corr} του ναου εσχισθη εις δυο απο [ανωθεν]{.greek-omitted} [ανοθεν]{.greek-added} εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και [γυνε]{.greek-added} [γυναικες]{.corr} απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και [σαλωμη]{.greek-omitted}[15:40]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [γυναικες]{.greek-omitted} [απο]{.greek-omitted} [μακροθεν]{.greek-omitted} [θεωρουσαι]{.greek-omitted} [εν]{.greek-omitted} [αις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [του]{.greek-omitted} [ιακωβου]{.greek-omitted} [του]{.greek-omitted} [μικρου]{.greek-omitted} [και]{.greek-omitted} [ιωση]{.greek-omitted} [μητηρ]{.greek-omitted} [και]{.greek-omitted} σαλωμη[15:40 | instance no. 2]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι [πολλαι]{.greek-omitted} [παλλαι]{.greek-added} αι συναναβασαι αυτω εις [ιεροσολυμα]{.greek-omitted} [ιεροσολιμα]{.greek-added}[15:41]{.aside}

και ηδη οψιας γενομενης επει [ην]{.greek-omitted} παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο αριμαθαιας [ευχημων]{.greek-added} [ευσχημων]{.corr} βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηθε]{.greek-added} [εισηλθεν]{.greek-omitted} [[εισηλθε]{.corr}]{.greek-added} προς [πιλατων]{.greek-added} [πιλατον]{.corr} και ητησατο το [σωμα]{.greek-omitted} [σωνα]{.greek-added} του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και [γνους]{.greek-omitted} [γους]{.greek-added} απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισε]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις [αποκυλισειν]{.greek-added} [αποκυλισει]{.corr} ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι [αποκεκυλισται]{.greek-omitted} [αποκεκυσαι]{.greek-added} ο λιθος [ην]{.greek-omitted} [γαρ]{.greek-omitted} [μεγας]{.greek-omitted} [σφοδρα]{.greek-omitted}[16:4]{.aside}

[και]{.greek-omitted} [αναβλεψασαι]{.greek-omitted} [θεωρουσιν]{.greek-omitted} [οτι]{.greek-omitted} [αποκεκυλισται]{.greek-omitted} [ο]{.greek-omitted} [λιθος]{.greek-omitted} ην γαρ μεγας [σφδρα]{.greek-added} [σφοδρα]{.corr}[16:4 | instance no. 2]{.aside}

και εισελθουσαι εις το μνημειον ειδον [νεαγ]{.greek-added} [νεανισκον]{.corr} καθημενον εν τοις δεξιοις [περιβεβλημενην]{.greek-added} [περιβεβλημενον]{.corr} στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταρωμενον]{.greek-added} [εσταυρωμενον]{.corr} ηγερθη ουκ εστιν ωδε ιδε ο [τοπον]{.greek-added} [τοπος]{.corr} οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και [ουδενι]{.greek-omitted} [ουδεν]{.greek-added} ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις [τον]{.greek-omitted} [κοσμον]{.greek-omitted} [τοσμον]{.greek-added} απαντα [κηρσ[σ]{.unclear}ατε]{.greek-added} [κηρυξατε]{.corr} το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις [σωθησεται]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [απιστησας]{.greek-omitted} [κατακριθησεται]{.greek-omitted}[16:16]{.aside}

[ο]{.greek-omitted} [πιστευσας]{.greek-omitted} [και]{.greek-omitted} [βαπτισθεις]{.greek-omitted} σωθησεται ο δε απιστησας κατακριθησεται[16:16 | instance no. 2]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρους]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους [βλαψη]{.greek-omitted} [βλαψει]{.greek-added} επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις [τον]{.corr} [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των [επακολουθουτων]{.greek-added} [επακολουθουντων]{.corr} σημειων αμην[16:20]{.aside}

