---
title: "Collation of Byz^RP^ vs 30620 (620)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 620 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30620).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 620                                   	| λογος                              	|
| 620 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 620 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 620               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 620                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 620 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 620                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος εμαρτυρησεν τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [εισιν]{.greek-added} [και]{.greek-added} [χρη]{.greek-added} [γενεσθαι]{.greek-added} [μετα]{.greek-added} [ταυτα]{.greek-added}[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας [ταυτης]{.greek-added} και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-omitted} ο ων και ο ην και ο ερχομενος και απο των επτα πνευματων α [εστιν]{.greek-added} ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο [πρωτοτοκος]{.greek-omitted} [προτοτοκος]{.greek-added} των νεκρων και ο αρχων των βασιλεων της γης [τω]{.greek-omitted} [αγαπωντι]{.greek-omitted} [ημας]{.greek-omitted} [και]{.greek-omitted} [λουσαντι]{.greek-omitted} [ημας]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [αμαρτιων]{.greek-omitted} [ημων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αιματι]{.greek-omitted} [αυτου]{.greek-omitted}[1:5]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [ο]{.greek-omitted} [πιστος]{.greek-omitted} [ο]{.greek-omitted} [πρωτοτοκος]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αρχων]{.greek-omitted} [των]{.greek-omitted} [βασιλεων]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} τω αγαπωντι ημας [και]{.greek-added} [λυσαντι]{.greek-added} [και]{.greek-added} [των]{.greek-added} [της]{.greek-added} [αμαρτιας]{.greek-added} [κιλιδων]{.greek-added} [λουσαντι]{.greek-added} [τη]{.greek-added} [εκχυσει]{.greek-added} [του]{.greek-added} [ζωοπιου]{.greek-added} [αιματος]{.greek-added} [και]{.greek-added} [υδατος]{.greek-added} [και]{.greek-added} [ποιησαντι]{.greek-added} [ημας]{.greek-added} [βασιλειον]{.greek-added} [ιερατευμα]{.greek-added} και λουσαντι ημας απο των αμαρτιων [ημων]{.greek-omitted} εν τω αιματι αυτου[1:5 | instance no. 2]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [και]{.greek-added} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και κοινωνος εν τη θλιψει και [εν]{.greek-added} [τη]{.greek-added} βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν [τη]{.greek-omitted} κυριακη ημερα και ηκουσα φωνην οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης [εγω]{.greek-added} [αλφα]{.greek-added} [και]{.greek-added} [το]{.greek-added} [[ω]{.greek-abbr}]{.greek-added} [πρωτος]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [εσχατος]{.greek-added} ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις [σμυρναν]{.greek-omitted} [μυρναν]{.greek-added} και εις περγαμον [και]{.greek-omitted} [εις]{.greek-omitted} [θυατειρα]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [σαρδεις]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [φιλαδελφειαν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [λαοδικειαν]{.greek-omitted}[1:11]{.aside}

[λεγουσης]{.greek-omitted} [ο]{.greek-omitted} [βλεπεις]{.greek-omitted} [γραψον]{.greek-omitted} [εις]{.greek-omitted} [βιβλιον]{.greek-omitted} [και]{.greek-omitted} [πεμψον]{.greek-omitted} [ταις]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [εις]{.greek-omitted} [εφεσον]{.greek-omitted} και εις [σμυρναν]{.greek-omitted} [θυατηρα]{.greek-added} και εις [περγαμον]{.greek-omitted} [αρδεις]{.greek-added} και εις [θυατειρα]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [σαρδεις]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [φιλαδελφειαν]{.greek-omitted} [φιλαδελφιαν]{.greek-added} και εις λαοδικειαν[1:11 | instance no. 2]{.aside}

και εκει επεστρεψα βλεπειν την φωνην ητις [ελαλει]{.greek-omitted} [ελαλησεν]{.greek-added} μετ εμου και επιστρεψας [ειδον]{.greek-omitted} [ιδων]{.greek-added} επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των επτα λυχνιων ομοιον [υιω]{.greek-omitted} [[υιον]{.greek-abbr}]{.greek-added} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς [τοις]{.greek-omitted} [της]{.greek-added} [μαστοις]{.greek-omitted} [μασθοις]{.greek-added} ζωνην [χρυσην]{.greek-omitted} [χρυσιν]{.greek-added}[1:13]{.aside}

η δε κεφαλη αυτου και [αι]{.greek-omitted} [τριχες]{.greek-omitted} [ετρυχες]{.greek-added} λευκαι ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

[και]{.greek-omitted} οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκωλιβανω]{.greek-added} ως εν καμινω [πεπυρωμενοι]{.greek-omitted} [πεπυρομενω]{.greek-added} και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια αυτου χειρι αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον επεσα προς τους ποδας αυτου ως νεκρος και εθηκεν την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας κλεις του θανατου και του αδου[1:18]{.aside}

γραψον [ουν]{.greek-omitted} α [ειδες]{.greek-omitted} [ιδες]{.greek-added} και α εισιν και α μελλει [γινεσθαι]{.greek-omitted} [γινεσθε]{.greek-added} μετα ταυτα[1:19]{.aside}

[το]{.greek-omitted} [τω]{.greek-added} μυστηριον των επτα αστερων ων [ειδες]{.greek-omitted} [ιδες]{.greek-added} επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν [και]{.greek-omitted} [αι]{.greek-omitted} [λυχνιαι]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαι]{.greek-omitted} [εισιν]{.greek-omitted}[1:20]{.aside}

[το]{.greek-omitted} [μυστηριον]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αστερων]{.greek-omitted} [ων]{.greek-omitted} [ειδες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιας]{.greek-omitted} [τας]{.greek-omitted} [χρυσας]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} [αστερες]{.greek-omitted} [αγγελοι]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιων]{.greek-omitted} [εισιν]{.greek-omitted} και αι λυχνιαι αι επτα επτα εκκλησιαι εισιν[1:20 | instance no. 2]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των [επτα]{.greek-omitted} λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου [δυνη]{.greek-omitted} [δυνει]{.greek-added} βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ εισιν και ευρες αυτους ψευδεις[2:2]{.aside}

[και]{.greek-added} [εβαστασας]{.greek-added} [με]{.greek-added} και υπομονην εχεις [και]{.greek-omitted} [εβαστασας]{.greek-omitted} δια το ονομα μου και [ουκ]{.greek-omitted} [εκοπιασας]{.greek-omitted} [κ[ε]{.unclear}κοπίασας]{.greek-added}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν [πεπτωκας]{.greek-omitted} [εκπεπτωκας]{.greek-added} και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη [μετανοησης]{.greek-omitted} [μετανοησεις]{.greek-added}[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω [μισω]{.greek-omitted} [μησω]{.greek-added}[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω [νικωντι]{.greek-omitted} [νικοντι]{.greek-added} δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν τω παραδεισω του [θεου]{.greek-abbr} μου[2:7]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την [πτωχειαν]{.greek-omitted} [πτωχιαν]{.greek-added} αλλα πλουσιος ει [και]{.greek-omitted} [την]{.greek-omitted} [βλασφημιαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [λεγοντων]{.greek-omitted} [ιουδαιους]{.greek-omitted} [ειναι]{.greek-omitted} [εαυτους]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εισιν]{.greek-omitted} [αλλα]{.greek-omitted} [συναγωγη]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted}[2:9]{.aside}

[οιδα]{.greek-omitted} [σου]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [θλιψιν]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [πτωχειαν]{.greek-omitted} [αλλα]{.greek-omitted} [πλουσιος]{.greek-omitted} [ει]{.greek-omitted} και την βλασφημιαν εκ των [λεγοντων]{.greek-omitted} [λεγωντων]{.greek-added} ιουδαιους ειναι [εαυτους]{.greek-omitted} και ουκ [εισιν]{.greek-omitted} [ησιν]{.greek-added} αλλα συναγωγη του σατανα[2:9 | instance no. 2]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχει]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βαλεῖν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και [δωσω]{.greek-omitted} [δοσω]{.greek-added} σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την [πιστιν]{.greek-omitted} [πιστι]{.greek-added} μου εν ταις ημεραις εν αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς μου ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος εδιδαξεν τον [βαλακ]{.greek-omitted} [βαλαακ]{.greek-added} βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} [του]{.greek-added} φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

[μετανοησον]{.greek-omitted} [ουν]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [ερχομαι]{.greek-omitted} [σοι]{.greek-omitted} [ταχυ]{.greek-omitted} και [πολεμησω]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted} εν τη [απειλη]{.greek-added} [η]{.greek-added} [[φιλανια]{.greek-abbr}]{.greek-added} [ρομφαια]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [μου]{.greek-omitted}[2:16 | instance no. 2]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω [νικωντι]{.greek-omitted} [νικοντι]{.greek-added} δωσω αυτω [φαγειν]{.greek-added} [απο]{.greek-added} του μαννα του κεκρυμμενου και δωσω αυτω ψηφον [λευκην]{.greek-omitted} [λευκον]{.greek-added} και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατηρη]{.greek-added} εκκλησιας γραψον ταδε λεγει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο εχων τους [οφθαλμους]{.greek-omitted} [οφθαμους]{.greek-added} αυτου ως φλογα πυρος και [οι]{.greek-omitted} [ποδες]{.greek-omitted} [υποδες]{.greek-added} αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκωλιβανω]{.greek-added}[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου οτι αφεις την γυναικα [σου]{.greek-omitted} ιεζαβελ η λεγει [εαυτην]{.greek-omitted} [αυτην]{.greek-added} [προφητιν]{.greek-omitted} [προφητην]{.greek-added} και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν [ειδωλοθυτα]{.greek-omitted} [ειδωλωθητα]{.greek-added}[2:20]{.aside}

και εδωκα [αυτη]{.greek-omitted} [αυτην]{.greek-added} χρονον ινα [μετανοηση]{.greek-omitted} [μετανοησει]{.greek-added} και ου [θελει]{.greek-omitted} [θελη]{.greek-added} μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι [οτι]{.greek-omitted} [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [ο]{.greek-omitted} [ερευνων]{.greek-omitted} [νεφρους]{.greek-omitted} [και]{.greek-omitted} [καρδιας]{.greek-omitted} [και]{.greek-omitted} [δωσω]{.greek-omitted} [υμιν]{.greek-omitted} [εκαστω]{.greek-omitted} [κατα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [υμων]{.greek-omitted}[2:23]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [τεκνα]{.greek-omitted} [αυτης]{.greek-omitted} [αποκτενω]{.greek-omitted} [εν]{.greek-omitted} [θανατω]{.greek-omitted} [και]{.greek-omitted} [γνωσονται]{.greek-omitted} [πασαι]{.greek-omitted} [αι]{.greek-omitted} [εκκλησιαι]{.greek-omitted} οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23 | instance no. 2]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν [θυατειροις]{.greek-omitted} [θυατηροις]{.greek-added} οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την [διδαχην]{.greek-omitted} [διδαχη]{.greek-added} ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθεά]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας [αλλο]{.greek-omitted} [αλλω]{.greek-added} βαρος[2:24]{.aside}

πλην ο [εχετε]{.greek-omitted} [εχεται]{.greek-added} κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

[και]{.greek-omitted} ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν [σαρδεσιν]{.greek-omitted} [σαρδεσι]{.greek-added} εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [στηριζων]{.greek-added} τα λοιπα α [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [ημελλεν]{.greek-added} [αποθανειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν [ουν]{.greek-omitted} μη [γρηγορησης]{.greek-omitted} [γρηγορησεις]{.greek-added} ηξω επι σε ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωσει]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατουσισιν]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο [νικων]{.greek-omitted} [νικον]{.greek-added} ουτος [περιβαλειται]{.greek-omitted} [περιβαλεται]{.greek-added} εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους [ακουσατω]{.greek-omitted} [ακουσατο]{.greek-added} τι [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφιας]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την [κλειν]{.greek-omitted} [κλιδα]{.greek-added} του [δαυιδ]{.greek-omitted} [αδου]{.greek-added} ο ανοιγων και ουδεις [κλεισει]{.greek-omitted} [κλειση]{.greek-added} αυτην ει [μη]{.greek-omitted} [μι]{.greek-added} ο ανοιγων και [κλειον]{.greek-added} [και]{.greek-added} ουδεις [ανοιξει]{.greek-omitted} [ανοιξη]{.greek-added}[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου [διδωμι]{.greek-omitted} [διδομι]{.greek-added} εκ της συναγωγης του σατανα των [λεγοντων]{.greek-omitted} [λεγωντων]{.greek-added} εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα ηξωσιν και προσκυνησωσιν [ενωπιον]{.greek-omitted} [ενωποιον]{.greek-added} των ποδων σου και γνωσιν οτι [εγω]{.greek-added} ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου [καγω]{.greek-omitted} [σε]{.greek-omitted} [τηρησω]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [ωρας]{.greek-omitted} [του]{.greek-omitted} [πειρασμου]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [οικουμενης]{.greek-omitted} [ολης]{.greek-omitted} [πειρασαι]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[3:10]{.aside}

[οτι]{.greek-omitted} [ετηρησας]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [της]{.greek-omitted} [υπομονης]{.greek-omitted} [μου]{.greek-omitted} καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης [ερχεσθαι]{.greek-omitted} [ερχεται]{.greek-added} επι της οικουμενης ολης [πειρασαι]{.greek-omitted} [πειρασε]{.greek-added} τους κατοικουντας επι της γης[3:10 | instance no. 2]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα [μηδεις]{.greek-omitted} [μη]{.greek-added} λαβη [τις]{.greek-added} [ταχυ]{.greek-added} τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον [πε]{.greek-added} εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} του [θεου]{.greek-abbr} μου και το ονομα [μου]{.greek-omitted} το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν [λαοδικεια]{.greek-omitted} [λαοδικια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος [και]{.greek-omitted} [ο]{.greek-added} αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος οφελον ψυχρος [ης]{.greek-omitted} [εις]{.greek-added} η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και [πεπλουτηκαι]{.greek-added} [πεπλουτηκα]{.corr} και ουδενος χρειαν [εχω]{.greek-omitted} [εχεις]{.greek-added} και ουκ οιδας οτι συ ει ο [ταλαιπωρος]{.greek-omitted} [ταλεπορος]{.greek-added} και ο [ελεεινος]{.greek-omitted} [ελεινος]{.greek-added} και πτωχος και [γυμνος]{.greek-added} [και]{.greek-added} τυφλος [και]{.greek-omitted} [γυμνος]{.greek-omitted}[3:17]{.aside}

συμβουλευω σοι [αγορασαι]{.greek-omitted} [αγωρασαι]{.greek-added} χρυσιον παρ εμου πεπυρωμενον εκ πυρος ινα πλουτησης [και]{.greek-omitted} [ιματια]{.greek-omitted} [λευκα]{.greek-omitted} [ινα]{.greek-omitted} [περιβαλη]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [φανερωθη]{.greek-omitted} [η]{.greek-omitted} [αισχυνη]{.greek-omitted} [της]{.greek-omitted} [γυμνοτητος]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [κολλυριον]{.greek-omitted} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [τους]{.greek-omitted} [οφθαλμους]{.greek-omitted} [σου]{.greek-omitted} [ινα]{.greek-omitted} [βλεπης]{.greek-omitted}[3:18]{.aside}

[συμβουλευω]{.greek-omitted} [σοι]{.greek-omitted} [αγορασαι]{.greek-omitted} [χρυσιον]{.greek-omitted} [παρ]{.greek-omitted} [εμου]{.greek-omitted} [πεπυρωμενον]{.greek-omitted} [εκ]{.greek-omitted} [πυρος]{.greek-omitted} [ινα]{.greek-omitted} [πλουτησης]{.greek-omitted} και ιματια λευκα ινα περιβαλη και μη φανερωθη η [αισχυνη]{.greek-omitted} [ασχημοσυνη]{.greek-added} της [γυμνοτητος]{.greek-omitted} [γυμνωτητος]{.greek-added} σου και κολλυριον [εχρισαι]{.greek-added} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} τους οφθαλμους σου ινα [βλεπης]{.greek-omitted} [βλεψεις]{.greek-added}[3:18 | instance no. 2]{.aside}

εγω οσους εαν φιλω ελεγχω και [παιδευω]{.greek-omitted} [πεδευω]{.greek-added} ζηλωσον [ουν]{.greek-omitted} και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν [και]{.greek-omitted} εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω [θρονω]{.greek-omitted} [θρονο]{.greek-added} μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω [θρονω]{.greek-omitted} [θρωνω]{.greek-added} αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου [θυρα]{.greek-omitted} [θυραν]{.greek-added} ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου [λεγων]{.greek-omitted} [και]{.greek-added} [λεγουσης]{.greek-added} αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος [εκειτο]{.greek-omitted} [εκειτω]{.greek-added} εν τω [ουρανω]{.greek-abbr} και επι τον θρονον καθημενος[4:2]{.aside}

[ομοιος]{.greek-omitted} [ομοιως]{.greek-added} ορασει λιθω ιασπιδι και σαρδιω και [ιρις]{.greek-omitted} [ἴρις]{.greek-added} [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} του θρονου [ομοιως]{.greek-omitted} [ομοια]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδινω]{.greek-added}[4:3]{.aside}

και [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} του θρονου θρονοι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [θρονους]{.greek-omitted} [τους]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} [πρεσβυτερους]{.greek-omitted} [καθημενους]{.greek-omitted} [περιβεβλημενους]{.greek-omitted} [εν]{.greek-omitted} [ιματιοις]{.greek-omitted} [λευκοις]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [στεφανους]{.greek-omitted} [χρυσους]{.greek-omitted}[4:4]{.aside}

[και]{.greek-omitted} [κυκλοθεν]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [θρονοι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} και επι τους θρονους τους [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4 | instance no. 2]{.aside}

και εκ του θρονου [εκπορευονται]{.greek-omitted} [εξεπορευοντο]{.greek-added} αστραπαι και φωναι και [βρονται]{.greek-omitted} [βρωνται]{.greek-added} και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα πνευματα του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου [αυτου]{.greek-added} ως [θαλασσα]{.greek-omitted} [θαλασσαν]{.greek-added} υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα [οφθαλμων]{.greek-omitted} [οφθαλμους]{.greek-added} εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον [εχον]{.greek-omitted} [εχων]{.greek-added} [το]{.greek-added} προσωπον [ως]{.greek-added} [ανθρωπου]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} και το τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν [οφθαλμων]{.greek-omitted} [οφθαλμους]{.greek-added} και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} [σαβαωθ]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-omitted} ο παντοκρατωρ ο ην και ο [ων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσωσι]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι [εικοσι]{.greek-omitted} [κοση]{.greek-added} [τεσσαρες]{.greek-omitted} [τεσσαρεις]{.greek-added} πρεσβυτεροι ενωπιον του καθημενου επι του θρονου [και]{.greek-omitted} [προσκυνησουσιν]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [και]{.greek-omitted} [βαλουσιν]{.greek-omitted} [τους]{.greek-omitted} [στεφανους]{.greek-omitted} [αυτων]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [λεγοντες]{.greek-omitted}[4:10]{.aside}

[πεσουνται]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} και προσκυνησουσιν τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλλοῦσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10 | instance no. 2]{.aside}

αξιος ει [[κυριε]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [και]{.greek-omitted} ο [θεος]{.greek-abbr} ημων [ο]{.greek-omitted} [αγιος]{.greek-omitted} λαβειν [την]{.greek-added} [δυναμιν]{.greek-added} [και]{.greek-added} την δοξαν και την τιμην [και]{.greek-omitted} [την]{.greek-omitted} [δυναμιν]{.greek-omitted} οτι συ [εκτισας]{.greek-omitted} [εκτησας]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισιν]{.greek-added} και [εκτισθησαν]{.greek-omitted} [εκτησθησαν]{.greek-added}[4:11]{.aside}

### Chapter 5

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο εν τω [ουρανω]{.greek-abbr} ανω [ουτε]{.greek-omitted} [ουδε]{.greek-added} επι της γης [ουτε]{.greek-omitted} [ουδε]{.greek-added} υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και [ιδον]{.greek-added} [ειδον]{.corr} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [και]{.greek-omitted} εν μεσω των πρεσβυτερων αρνιον [εστηκος]{.greek-omitted} [εστικως]{.greek-added} ως εσφαγμενον [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα επτα και οφθαλμους επτα α εισιν τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} [τα]{.greek-added} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και ηλθεν και ειληφεν [το]{.greek-added} [βιβλιον]{.greek-added} εκ [της]{.greek-added} [χειρος]{.greek-added} της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε ελαβεν το βιβλιον τα τεσσαρα ζωα και [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [ηικοση]{.greek-added} [[ικοση]{.corr}]{.greek-added} [τεσσαρες]{.greek-omitted} [τεσσαρεις]{.greek-added} πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του αρνιου εχοντες εκαστος [κιθαραν]{.greek-omitted} [κιθαρας]{.greek-added} και φιαλας χρυσας [γεμουσας]{.greek-omitted} [μεστας]{.greek-added} θυμιαματων αι εισιν [αι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι [εσφαγης]{.greek-omitted} [εσφαγεις]{.greek-added} και ηγορασας [ημας]{.greek-added} τω [θεω]{.greek-abbr} [ημας]{.greek-omitted} εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και [ειδον]{.greek-omitted} [ιδων]{.greek-added} και ηκουσα ως φωνην αγγελων [πολλων]{.greek-omitted} κυκλω του θρονου και των [ζωων]{.greek-omitted} [πρεσβυτερων]{.greek-added} και των [πρεσβυτερων]{.greek-omitted} [ζωον]{.greek-added} και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον εστιν το αρνιον το εσφαγμενον λαβειν την δυναμιν και [τον]{.greek-omitted} [των]{.greek-added} πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα [ο]{.greek-omitted} εν τω [ουρανω]{.greek-abbr} και επι της γης και υποκατω [της]{.greek-added} της γης και επι της θαλασσης εστιν και τα εν αυτοις παντας ηκουσα λεγοντας τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} τω [θρονω]{.greek-added} [αρνιω]{.greek-omitted} [η]{.greek-omitted} [ευλογια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [τιμη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [κρατος]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [αμην]{.greek-omitted}[5:13]{.aside}

[και]{.greek-omitted} [παν]{.greek-omitted} [κτισμα]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted} [παντας]{.greek-omitted} [ηκουσα]{.greek-omitted} [λεγοντας]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13 | instance no. 2]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} το αμην και οι πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και [ιδων]{.greek-added} [ειδον]{.greek-omitted} [[ειδων]{.corr}]{.greek-added} [οτι]{.greek-omitted} [οτε]{.greek-added} ηνοιξεν το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων [ζωων]{.greek-omitted} [ζωον]{.greek-added} [λεγοντος]{.greek-omitted} [λεγωντες]{.greek-added} ως [φωνη]{.greek-omitted} [φωνὴ]{.greek-added} βροντης ερχου και ιδε[6:1]{.aside}

[και]{.greek-added} [ιδον]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ [αυτον]{.greek-omitted} [αυτων]{.greek-added} εχων τοξον και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω στεφανος και εξηλθεν νικων και ινα [νικηση]{.greek-omitted} [νικησι]{.greek-added}[6:2]{.aside}

και οτε ηνοιξεν [την]{.greek-omitted} [τη]{.greek-added} δευτεραν σφραγιδα ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος πυρος και τω καθημενω επ αυτον [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω λαβειν την ειρηνην [εκ]{.greek-omitted} της γης ινα αλληλους σφαξωσιν και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [ιδον]{.greek-added} και ιδου ιππος μελας και ο καθημενος επ αυτον [εχων]{.greek-omitted} [εχον]{.greek-added} ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων [ζωων]{.greek-omitted} [ζωον]{.greek-added} λεγουσαν χοινιξ σιτου [δηναριου]{.greek-omitted} [διναριου]{.greek-added} και τρεις χοινικες κριθης [δηναριου]{.greek-omitted} [διναριου]{.greek-added} και το [ελαιον]{.greek-omitted} [ελεον]{.greek-added} και τον οινον μη [αδικησης]{.greek-omitted} [αδικησεις]{.greek-added}[6:6]{.aside}

και οτε ηνοι[ξ]{.greek-supplied}εν την [σφραγιδα]{.greek-omitted} [σφραγιδαν]{.greek-added} την τεταρτην [ηκουσα]{.greek-omitted} [του]{.greek-omitted} [τεταρτου]{.greek-omitted} [ζωου]{.greek-omitted} [λεγοντος]{.greek-omitted} [ερχου]{.greek-omitted} [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [την]{.greek-omitted} [τεταρτην]{.greek-omitted} ηκουσα του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7 | instance no. 2]{.aside}

[και]{.greek-added} [ιδον]{.greek-added} και ιδου ιππος [χλωρος]{.greek-omitted} [χλορος]{.greek-added} και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης ηκολουθει [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα [ειδον]{.greek-omitted} [ιδων]{.greek-added} υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν του αρνιου ην ειχον[6:9]{.aside}

και εκραξαν φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και [ο]{.greek-added} αληθινος ου [κρινεις]{.greek-omitted} [κρινης]{.greek-added} και εκδικεις το αιμα ημων [εκ]{.greek-omitted} [απο]{.greek-added} των κατοικουντων επι της γης[6:10]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτοις εκαστω στολη λευκη και [ερρεθη]{.greek-omitted} [ερεθη]{.greek-added} αυτοις ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} ετι χρονον εως πληρωσ[ω]{.unclear}σιν και οι συνδουλοι [αυτων]{.greek-omitted} [αυτου]{.greek-added} και ο[ι]{.unclear} αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} οτε ηνοιξεν την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος μελας εγενετο ως [σακκος]{.greek-omitted} [ακκος]{.greek-added} τριχινος και η σεληνη ολη εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλουσα]{.greek-added} τους ολυνθους αυτης υπο ανεμου μεγαλου [σειομενη]{.greek-omitted} [σειωμενη]{.greek-added}[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ελισσομενος]{.greek-added} και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις [δυναται]{.greek-omitted} [δυνατε]{.greek-added} σταθηναι[6:17]{.aside}

### Chapter 7

και μετα τουτο ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους τεσσαρας ανεμους της γης ινα μη πνεη ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και ειδον [αγγελον]{.greek-added} αλλον [αγγελον]{.greek-omitted} αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [του]{.greek-added} [θεου]{.greek-abbr} ζωντος και εκραξεν φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην [μητε]{.greek-omitted} [μηδε]{.greek-added} την θαλασσαν [μητε]{.greek-omitted} [μηδε]{.greek-added} τα δενδρα [αχρι]{.greek-omitted} [ου]{.greek-omitted} [σφραγισωμεν]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[7:3]{.aside}

[λεγων]{.greek-omitted} [μη]{.greek-omitted} [αδικησητε]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [μητε]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [μητε]{.greek-omitted} [τα]{.greek-omitted} [δενδρα]{.greek-omitted} [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3 | instance no. 2]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον [και]{.greek-omitted} τεσσαρακοντα τεσσαρες χιλιαδες εσφραγισμενων εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εσφραγισμεναι [εκ]{.corr} [φυλης]{.corr} [ρουβιμ]{.corr} [δωδεκα]{.greek-omitted} [[[ιβ]{.greek-abbr}]{.corr}]{.greek-added} [χιλιαδες]{.corr} εκ φυλης [γαδ]{.greek-omitted} [δωδεκα]{.greek-omitted} [ρουβημ]{.greek-added} [ιβ]{.greek-added} χιλιαδες [εκ]{.greek-added} [φυλης]{.greek-added} [δαν]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} [χιλιαδες]{.greek-added}[7:5]{.aside}

εκ φυλης ασηρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [νεφθαλειμ]{.greek-omitted} [νεφθαλιμ]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εκ]{.corr} [φυλης]{.corr} [μανασση]{.corr} [δωδεκα]{.greek-omitted} [χιλιαδες]{.corr} [[[ιβ]{.greek-abbr}]{.corr}]{.greek-added} [εκ]{.greek-added} [φυλης]{.greek-added} [συμεων]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} [χιλιαδες]{.greek-added}[7:6]{.aside}

[εκ]{.greek-omitted} [φυλης]{.greek-omitted} [συμεων]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} εκ φυλης λευι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ισαχαρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμην]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εσφραγισμεναι[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις εδυνατο εκ παντος εθνους και φυλων και λαων και γλωσσων εστωτας ενωπιον του θρονου και ενωπιον του αρνιου [περιβεβλημενους]{.greek-omitted} [περιβλημενους]{.greek-added} στολας λευκας και φοινικας εν ταις χερσιν αυτων[7:9]{.aside}

και κραζουσιν φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω θρονω και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων [και]{.greek-omitted} [επεσον]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [επι]{.greek-omitted} [τα]{.greek-omitted} [προσωπα]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[7:11]{.aside}

και [παντες]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [ειστηκεισαν]{.greek-omitted} [κυκλω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [και]{.greek-omitted} [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του θρονου [αυτου]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11 | instance no. 2]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες εισιν και ποθεν ηλθον[7:13]{.aside}

και ειπον αυτω κυριε μου συ οιδας και ειπεν μοι ουτοι εισιν οι [ερχομενοι]{.greek-omitted} [ερχομενη]{.greek-added} εκ της θλιψεως της μεγαλης και επλυναν τας στολας αυτων [και]{.greek-omitted} ελευκαναν εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι τω θρονω σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν ετι ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και οδηγει αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον [εκ]{.greek-omitted} [ααπο]{.greek-added} των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην [εγενετο]{.greek-omitted} [σιγη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [ως]{.greek-omitted} [ημιωριον]{.greek-omitted}[8:1]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [την]{.greek-omitted} [εβδομην]{.greek-omitted} εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1 | instance no. 2]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-omitted} [θρονου]{.greek-added} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος ηλθεν και εσταθη επι του θυσιαστηριου εχων λιβανωτον χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα δωση ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και [εγεμισεν]{.greek-omitted} [εγεμησεν]{.greek-added} αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο βρονται και φωναι και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι [οι]{.greek-omitted} εχοντες τας επτα [σαλπιγγας]{.greek-omitted} [σαλπηγγας]{.greek-added} ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος εσαλπισεν και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον [της]{.greek-added} [γης]{.greek-added} [κατεκαη]{.greek-added} [και]{.greek-added} [το]{.greek-added} [τριτον]{.greek-added} των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος εσαλπισεν και ως ορος μεγα καιομενον εβληθη εις την θαλασσαν [και]{.greek-omitted} [εγενετο]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [αιμα]{.greek-omitted}[8:8]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [ορος]{.greek-omitted} [μεγα]{.greek-omitted} [καιομενον]{.greek-omitted} [εβληθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} και εγενετο το τριτον της θαλασσης αιμα[8:8 | instance no. 2]{.aside}

και απεθανεν το τριτον των κτισματων εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9]{.aside}

και ο τριτος αγγελος εσαλπισεν και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας [πηγας]{.greek-omitted} [πιγας]{.greek-added} των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις [αψινθον]{.greek-omitted} [αψινθειον]{.greek-added} και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος εσαλπισεν και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και το τριτον αυτης μη φανη η ημερα και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος [αετου]{.greek-omitted} [αγγελου]{.greek-added} πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

[κ]{.greek-supplied}αι ο πεμπτος αγγελος εσαλπισεν και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις [του]{.greek-omitted} [φρεατος]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted}[9:1]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [πεμπτος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [ειδον]{.greek-omitted} [αστερα]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [πεπτωκοτα]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [η]{.greek-omitted} [κλεις]{.greek-omitted} του φρεατος της αβυσσου[9:1 | instance no. 2]{.aside}

και ηνοιξεν το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος ως καπνος καμινου καιομενης και [εσκοτισθη]{.greek-omitted} [εσκοτωθη]{.greek-added} ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και εδοθη αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [πεση]{.greek-added} [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [εὐρήσωσι]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευξηται]{.greek-added} απ αυτων ο θανατος[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι χρυσοι και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [των]{.greek-omitted} [πτερυγων]{.greek-omitted} [αυτων]{.greek-omitted} [ως]{.greek-omitted} [φωνη]{.greek-omitted} [αρματων]{.greek-omitted} [ιππων]{.greek-omitted} [πολλων]{.greek-omitted} [τρεχοντων]{.greek-omitted} [εις]{.greek-omitted} [πολεμον]{.greek-omitted}[9:9]{.aside}

[και]{.greek-omitted} [ειχον]{.greek-omitted} [θωρακας]{.greek-omitted} [ως]{.greek-omitted} [θωρακας]{.greek-omitted} [σιδηρους]{.greek-omitted} και η φωνη των πτερυγων αυτων ως φωνη αρματων [ιππων]{.greek-omitted} πολλων τρεχοντων εις πολεμον[9:9 | instance no. 2]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα και εν ταις ουραις αυτων εξουσιαν εχουσιν του αδικησαι τους [ανθρωπους]{.greek-omitted} [ανθροπους]{.greek-added} μηνας πεντε[9:10]{.aside}

εχουσαι βασιλεα επ αυτων αγγελον της αβυσσου ονομα αυτω εβραιστι [αββαδων]{.greek-omitted} [αββαδδων]{.greek-added} εν [δε]{.greek-omitted} τη ελληνικη [δε]{.greek-added} ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου ερχεται ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγοντος]{.greek-added} τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του ιππου μυριαδες μυριαδων ηκουσα [τον]{.greek-omitted} [των]{.greek-added} αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη ορασει και [το]{.greek-supplied}[υ]{.unclear}ς καθημενους επ αυτων [ε]{.greek-supplied}χοντας θωρακας πυρινους [και]{.greek-omitted} [υακινθινους]{.greek-omitted} [και]{.greek-omitted} [θειωδεις]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [κεφαλαι]{.greek-omitted} [των]{.greek-omitted} [ιππων]{.greek-omitted} [ως]{.greek-omitted} [κεφαλαι]{.greek-omitted} [λεοντων]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [στοματων]{.greek-omitted} [αυτων]{.greek-omitted} [εκπορευεται]{.greek-omitted} [πυρ]{.greek-omitted} [και]{.greek-omitted} [καπνος]{.greek-omitted} [και]{.greek-omitted} [θειον]{.greek-omitted}[9:17]{.aside}

και [ουτως]{.greek-omitted} [ειδον]{.greek-omitted} [τους]{.greek-omitted} [ιππους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ορασει]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [καθημενους]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted} [εχοντας]{.greek-omitted} [θωρακας]{.greek-omitted} [πυρινους]{.greek-omitted} [και]{.greek-omitted} [υακινθινους]{.greek-omitted} [ιακινθινους]{.greek-added} και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17 | instance no. 2]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων εστιν και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι οφεων εχουσαι κεφαλας και εν αυταις αδικουσιν[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα [χαλκα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον αγγελον [αλον]{.greek-added} ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και η ιρις επι της κεφαλης αυτου [και]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ποδες]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [στυλοι]{.greek-omitted} [πυρος]{.greek-omitted}[10:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αγγελον]{.greek-omitted} [ισχυρον]{.greek-omitted} [καταβαινοντα]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [περιβεβλημενον]{.greek-omitted} [νεφελην]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [ιρις]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [αυτου]{.greek-omitted} και το προσωπον αυτου ως [ο]{.greek-omitted} ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1 | instance no. 2]{.aside}

και εχων εν τη χειρι αυτου βιβλιον ανεωγμενον και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2]{.aside}

και εκραξεν φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι επτα βρονται [τας]{.greek-omitted} [εαυτων]{.greek-omitted} [φωνας]{.greek-omitted}[10:3]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ελαλησαν]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [βρονται]{.greek-omitted} εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο [αγγελος]{.greek-omitted} [αγγελον]{.greek-added} [ον]{.greek-omitted} [ειδον]{.greek-omitted} [ιδον]{.greek-added} εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμοσε]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων [αμην]{.greek-added} ος [εκτησε]{.greek-added} [εκτισεν]{.greek-omitted} [[εκτισε]{.corr}]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν και ετελεσθη το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα μετ εμου και λεγουσα υπαγε [λ]{.greek-supplied}αβε το βιβλιδαριον το ανεωγμενον [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [του]{.greek-omitted} [αγγελου]{.greek-omitted} [του]{.greek-omitted} [εστωτος]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[10:8]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [ην]{.greek-omitted} [ηκουσα]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [παλιν]{.greek-omitted} [λαλουσα]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [λεγουσα]{.greek-omitted} [υπαγε]{.greek-omitted} [λαβε]{.greek-omitted} [το]{.greek-omitted} [βιβλιδαριον]{.greek-omitted} το ανεωγμενον εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8 | instance no. 2]{.aside}

και [απηλθον]{.greek-omitted} [απηλθα]{.greek-added} προς τον αγγελον λεγων αυτω δουναι μοι το βιβλιδαριον και λεγει μοι λαβε και καταφαγε [αυτο]{.greek-omitted} [αυτω]{.greek-added} και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτό]{.greek-added} και ην εν τω στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε εξω και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα και δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και [αι]{.greek-omitted} [ε]{.greek-added} δυο λυχνιαι [αι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [εστωσαι]{.greek-omitted}[11:4]{.aside}

[ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} [αι]{.greek-omitted} [δυο]{.greek-omitted} [ελαιαι]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [δυο]{.greek-omitted} [λυχνιαι]{.greek-omitted} αι ενωπιον του [κυριου]{.greek-abbr} της γης [εστωσαι]{.greek-omitted} [εστωτες]{.greek-added}[11:4 | instance no. 2]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους αδικησαι ουτως δει [αυτον]{.greek-omitted} [αυτους]{.greek-added} αποκτανθηναι[11:5]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον [ουρανον]{.greek-abbr} εξουσιαν κλεισαι ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην οσακις εαν θελησωσιν εν παση πληγη[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και το πτωμα αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ αφησουσιν τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις [και]{.greek-omitted} [ευφρανθησονται]{.greek-omitted} [και]{.greek-omitted} [δωρα]{.greek-omitted} [δωσουσιν]{.greek-omitted} [αλληλοις]{.greek-omitted} [οτι]{.greek-omitted} [ουτοι]{.greek-omitted} [οι]{.greek-omitted} [δυο]{.greek-omitted} [προφηται]{.greek-omitted} [εβασανισαν]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[11:10]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [κατοικουντες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [χαιρουσιν]{.greek-omitted} [επ]{.greek-omitted} [αυτοις]{.greek-omitted} και ευφρανθησονται και δωρα δωσουσιν αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10 | instance no. 2]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν εις αυτους και εστησαν επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} [επεπεσεν]{.greek-added} επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [ἀνάβειτε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

[και]{.greek-omitted} εν εκεινη τη ημερα εγενετο σεισμος μεγας και το δεκατον της πολεως επεσεν και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν η ουαι η τριτη ιδου ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπιπισεν]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} [λεγουσαι]{.greek-omitted} [λεγοντες]{.greek-added} εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και [βασιλευσει]{.greek-omitted} [βασιλευει]{.greek-added} εις τους αιωνας των αιωνων[11:15]{.aside}

και οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι οι ενωπιον του θρονου του [θεου]{.greek-abbr} [καθημενοι]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [θρονους]{.greek-omitted} [αυτων]{.greek-omitted} [επεσον]{.greek-omitted} [επι]{.greek-omitted} [τα]{.greek-omitted} [προσωπα]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[11:16]{.aside}

[και]{.greek-omitted} οι [καθηνται]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [οι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [καθημενοι]{.greek-omitted} επι τους θρονους αυτων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16 | instance no. 2]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο [παντοκρατωρ]{.greek-omitted} [παντωκρατωρ]{.greek-added} ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των [νεκρων]{.greek-omitted} [εκρων]{.greek-added} κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους διαφθειροντας την γην[11:18]{.aside}

και [ηνοιγη]{.greek-omitted} [ηνοιχθη]{.greek-added} ο ναος του [θεου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης του [κυριου]{.greek-abbr} εν τω ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και [σημειον]{.greek-omitted} [σειμειον]{.greek-added} μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα εκραζεν ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και [ωφθη]{.greek-omitted} [οφθη]{.greek-added} αλλο σημειον εν τω [ουρανω]{.greek-abbr} και ιδου [δρακων]{.greek-omitted} [δρακον]{.greek-added} [πυρος]{.greek-omitted} [πυρρος]{.greek-added} μεγας εχων κεφαλας επτα [και]{.greek-omitted} [κερατα]{.greek-omitted} [δεκα]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτου]{.greek-omitted} [επτα]{.greek-omitted} [διαδηματα]{.greek-omitted}[12:3]{.aside}

[και]{.greek-omitted} [ωφθη]{.greek-omitted} [αλλο]{.greek-omitted} [σημειον]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [δρακων]{.greek-omitted} [πυρος]{.greek-omitted} [μεγας]{.greek-omitted} [εχων]{.greek-omitted} [κεφαλας]{.greek-omitted} [επτα]{.greek-omitted} και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3 | instance no. 2]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἔστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον υπο [του]{.greek-omitted} [θεου]{.greek-abbr} ινα εκει εκτρεφωσιν αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου [του]{.greek-added} πολεμησαι μετα του δρακοντος και ο δρακων επολεμησεν και οι αγγελοι αυτου[12:7]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη αυτω ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η σωτηρια [και]{.greek-omitted} [η]{.greek-omitted} [δυναμις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [εξουσια]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [εβληθη]{.greek-omitted} [ο]{.greek-omitted} [κατηγορος]{.greek-omitted} [των]{.greek-omitted} [αδελφων]{.greek-omitted} [ημων]{.greek-omitted} [ο]{.greek-omitted} [κατηγορων]{.greek-omitted} [αυτων]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [νυκτος]{.greek-omitted}[12:10]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [μεγαλην]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [λεγουσαν]{.greek-omitted} [αρτι]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [σωτηρια]{.greek-omitted} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10 | instance no. 2]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων [αχρι]{.greek-omitted} [μεχρι]{.greek-added} θανατου[12:11]{.aside}

δια τουτο ευφραινεσθε [ουρανοι]{.greek-abbr} και οι εν αυτοις [σκηνουντες]{.greek-omitted} [σκυνουντες]{.greek-added} ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην εδιωξεν την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν τη γυναικι δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον αυτης οπως τρεφηται εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον ποιηση[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και κατεπιεν τον ποταμον [ον]{.greek-omitted} [εβαλεν]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτου]{.greek-omitted}[12:16]{.aside}

[και]{.greek-omitted} [εβοηθησεν]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [τη]{.greek-omitted} [γυναικι]{.greek-omitted} [και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [το]{.greek-omitted} [στομα]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [κατεπιεν]{.greek-omitted} [τον]{.greek-omitted} [ποταμον]{.greek-omitted} ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16 | instance no. 2]{.aside}

και ωργισθη ο δρακων επι τη γυναικι και απηλθεν ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον εχον κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον ην ομοιον παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου [ωσει]{.greek-omitted} [ως]{.greek-added} [ει]{.greek-added} εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι τω δεδωκοτι την εξουσιαν τω θηριω και προσεκυνησαν τω θηριω λεγοντες τις ομοιος τω θηριω [και]{.greek-omitted} τις δυνατος πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα [και]{.greek-omitted} [βλασφημιαν]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσια]{.greek-omitted} [πολεμον]{.greek-omitted} [ποιησαι]{.greek-omitted} [μηνας]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [δυο]{.greek-omitted}[13:5]{.aside}

και [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [στομα]{.greek-omitted} [λαλουν]{.greek-omitted} [μεγαλα]{.greek-omitted} [και]{.greek-omitted} [βλασφημιαν]{.greek-omitted} [βλασφημιαι]{.greek-added} και εδοθη αυτω εξουσια πολεμον ποιησαι μηνας τεσσαρακοντα [και]{.greek-added} δυο[13:5 | instance no. 2]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου τους εν τω [ουρανω]{.greek-abbr} σκηνουντας[13:6]{.aside}

και εδοθη αυτω ποιησαι πολεμον μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και λαον και γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες επι της γης ων [ου]{.greek-omitted} [ουτε]{.greek-added} γεγραπται το ονομα εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις εχει αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτενεῖ]{.greek-added} δει αυτον εν μαχαιρα αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

[κ]{.greek-supplied}αι ειδον [αλλο]{.greek-omitted} [αλλον]{.greek-added} θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και ειχεν κερατα δυο ομοια [τω]{.greek-added} αρνιω και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα προσκυνησωσιν το θηριον [τω]{.greek-added} [πρωτω]{.greek-added} [το]{.greek-omitted} [πρωτον]{.greek-omitted} [ου]{.greek-omitted} [εθεραπευθη]{.greek-omitted} [η]{.greek-omitted} [πληγη]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [αυτου]{.greek-omitted}[13:12]{.aside}

[και]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [του]{.greek-omitted} [πρωτου]{.greek-omitted} [θηριου]{.greek-omitted} [πασαν]{.greek-omitted} [ποιει]{.greek-omitted} [ενωπιον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εποιει]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [κατοικουντας]{.greek-omitted} [ινα]{.greek-omitted} [προσκυνησωσιν]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [το]{.greek-omitted} [πρωτον]{.greek-omitted} ου εθεραπευθη η πληγη του θανατου αυτου[13:12 | instance no. 2]{.aside}

και ποιει [σημεια]{.greek-omitted} [σειμεια]{.greek-added} μεγαλα και πυρ ινα εκ του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [καταβαινει]{.greek-added} επι την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου [λεγων]{.greek-omitted} [λεγον]{.greek-added} τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ὧ]{.greek-added} ειχεν την πληγην και εζησεν απο της [πληγης]{.greek-added} [της]{.greek-added} μαχαιρας[13:14]{.aside}

και εδοθη αυτω [πνευμα]{.greek-abbr} δουναι τη [εικονι]{.greek-omitted} [εικων]{.greek-added} του θηριου [ινα]{.corr} [και]{.corr} [λαληση]{.greek-omitted} [[λαλησει]{.corr}]{.greek-added} [η]{.greek-omitted} [εικων]{.greek-omitted} [[εικον]{.corr}]{.greek-added} [του]{.corr} [θηριου]{.greek-omitted} [[θυριου]{.corr}]{.greek-added} και [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} οσοι εαν μη προσκυνησωσιν τη εικονι του θηριου αποκτανθωσιν[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους [ελευθερους]{.greek-omitted} [δουλους]{.greek-added} και τους [δουλους]{.greek-omitted} [ελευθερους]{.greek-added} ινα δωσωσιν αυτοις χαραγματα επι της [δεξιας]{.greek-added} [της]{.greek-added} χειρος αυτων [της]{.greek-omitted} [δεξιας]{.greek-omitted} η επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτων[13:16]{.aside}

και ινα μη τις δυναται αγορασαι η [πωλησαι]{.greek-omitted} [πολησαι]{.greek-added} ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων [νουν]{.greek-omitted} [ους]{.greek-added} [ψηφισατω]{.greek-omitted} [ψιφησατω]{.greek-added} [τον]{.greek-omitted} [των]{.greek-added} αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} εστιν [και]{.greek-omitted} ο αριθμος [αυτων]{.greek-added} [αυτου]{.greek-omitted} [εστιν]{.greek-omitted} εξακοσια εξηκοντα εξ[13:18]{.aside}

### Chapter 14

και ειδον και ιδου το αρνιον εστηκος επι το ορος σιων και μετ αυτου αριθμος [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} [χιλιαδες]{.greek-omitted} [εχουσαι]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [αυτου]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[14:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [το]{.greek-omitted} [αρνιον]{.greek-omitted} [εστηκος]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [ορος]{.greek-omitted} [σιων]{.greek-omitted} [και]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [αριθμος]{.greek-omitted} εκατον τεσσαρακοντα τεσσαρες χιλιαδες εχουσαι το ονομα αυτου και [το]{.greek-omitted} [ονομα]{.greek-omitted} του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των [μετωπων]{.greek-omitted} [μετοπον]{.greek-added} αυτων[14:1 | instance no. 2]{.aside}

και ηκουσα φωνην [εκ]{.corr} [του]{.corr} [[ουρανου]{.greek-abbr}]{.corr} [ως]{.corr} [φωνην]{.greek-omitted} [[φωνη]{.corr}]{.greek-added} υδατων πολλων και ως φωνην βροντης μεγαλης και η φωνη ην ηκουσα ως κιθαρωδων κιθαριζοντων [εν]{.greek-omitted} [εκ]{.greek-added} ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις εδυνατο μαθειν την ωδην ει μη [αι]{.greek-omitted} [εκατον]{.greek-omitted} [εκατων]{.greek-added} [τεσσαρακοντα]{.greek-omitted} [σαρακοντα]{.greek-added} [τεσσαρες]{.greek-omitted} [τεσσαρεις]{.greek-added} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι εισιν οι ακολουθουντες τω αρνιω οπου [αν]{.greek-omitted} [εαν]{.greek-added} [υπαγη]{.greek-omitted} [υπαγει]{.greek-added} ουτοι υπο [ιησου]{.greek-abbr} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} [απαρχη]{.greek-omitted} [απαρχης]{.greek-added} τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και ουχ ευρεθη εν τω στοματι αυτων ψευδος αμωμοι γαρ εισιν[14:5]{.aside}

και ειδον αγγελον πετομενον εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} εχοντα ευαγγελιον αιωνιον ευαγγελισαι τους καθημενους επι της γης και επι παν εθνος και [φυλην]{.greek-omitted} [φυλων]{.greek-added} και [γλωσσαν]{.greek-omitted} [γλωσσων]{.greek-added} και λαον[14:6]{.aside}

[λεγων]{.greek-omitted} εν φωνη μεγαλη [λεγων]{.greek-added} [φοβηθητε]{.greek-omitted} [φοβηθητο]{.greek-added} τον [κυριον]{.greek-abbr} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου [και]{.greek-omitted} [προσκυνησατε]{.greek-omitted} [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [πηγας]{.greek-omitted} [υδατων]{.greek-omitted}[14:7]{.aside}

[λεγων]{.greek-omitted} [εν]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [φοβηθητε]{.greek-omitted} [τον]{.greek-omitted} [κυριον]{.greek-omitted} [και]{.greek-omitted} [δοτε]{.greek-omitted} [αυτω]{.greek-omitted} [δοξαν]{.greek-omitted} [οτι]{.greek-omitted} [ηλθεν]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted} [της]{.greek-omitted} [κρισεως]{.greek-omitted} [αυτου]{.greek-omitted} και προσκυνησατε [αυτον]{.greek-omitted} [τον]{.greek-omitted} [αυτω]{.greek-added} [τω]{.greek-added} [ποιησαντα]{.greek-omitted} [ποιησαντι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και πηγας υδατων[14:7 | instance no. 2]{.aside}

και αλλος δευτερος αγγελος ηκολουθησεν [αυτοις]{.greek-added} λεγων [[εν]{.corr}]{.greek-added} [[φωνη]{.corr}]{.greek-added} [[μεγαλη]{.corr}]{.greek-added} επεσεν βαβυλων η μεγαλη εκ του οινου του θυμου της πορνειας [αυτης]{.greek-omitted} [ταυτης]{.greek-added} [πεποτικεν]{.greek-omitted} [πεποτηκεν]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις [προσκυνει]{.greek-omitted} [προσκυνη]{.greek-added} το θηριον και [την]{.greek-omitted} [τη]{.greek-added} [εικονα]{.greek-omitted} [εικονη]{.greek-added} αυτου και λαμβανει χαραγμα επι του [μετωπου]{.greek-omitted} [μετοπου]{.greek-added} αυτου η επι την [χειρα]{.greek-omitted} [χειραν]{.greek-added} αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του [κεκερασμενου]{.greek-omitted} [κερασμενου]{.greek-added} ακρατου [εν]{.greek-omitted} [τω]{.greek-omitted} [εκ]{.greek-added} [του]{.greek-added} [ποτηριω]{.greek-omitted} [ποτηριου]{.greek-added} της οργης αυτου και βασανισθησεται [εν]{.greek-omitted} [πυρι]{.greek-omitted} [και]{.greek-omitted} [θειω]{.greek-omitted} ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων [εις]{.greek-omitted} [αιωνας]{.greek-omitted} [αιωνων]{.greek-omitted} [αναβαινει]{.greek-omitted} και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και [την]{.greek-omitted} [τη]{.greek-added} [εικονα]{.greek-omitted} [οικονει]{.greek-added} αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν [ωδε]{.greek-added} οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [ἀπάρτι]{.greek-added} [απ]{.greek-omitted} [αρτι]{.greek-omitted} λεγει [τω]{.greek-added} [ναι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-abbr} ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} εκ των κοπων αυτων [τα]{.greek-omitted} [δε]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted} [ακολουθει]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσης]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [νεκροι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [κυριω]{.greek-omitted} [αποθνησκοντες]{.greek-omitted} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} [ναι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ινα]{.greek-omitted} [αναπαυσωνται]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κοπων]{.greek-omitted} [αυτων]{.greek-omitted} τα [δε]{.greek-omitted} [γαρ]{.greek-added} εργα αυτων [ακολουθει]{.greek-omitted} [ακουλουθει]{.greek-added} μετ αυτων[14:13 | instance no. 2]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην [καθημενον]{.greek-omitted} [καθημενος]{.greek-added} [ομοιον]{.greek-omitted} [ομοιως]{.greek-added} υιω [ανθρωπου]{.greek-omitted} [[ανθρωπω]{.greek-abbr}]{.greek-added} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του [ναου]{.greek-omitted} [ουνου]{.greek-added} κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν [σοι]{.greek-added} η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου [του]{.greek-omitted} εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} κραυγη μεγαλη τω [εχοντι]{.greek-omitted} [εχωντι]{.greek-added} το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους [βοτρυας]{.greek-omitted} [βοτριας]{.greek-added} της αμπελου της γης οτι [ηκμασαν]{.greek-omitted} [ηγμασαν]{.greek-added} αι σταφυλαι [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[14:18]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις [τ]{.unclear}ην ληνον του [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr} [τον]{.greek-omitted} [την]{.greek-added} [μεγαν]{.greek-omitted} [μεγαλην]{.greek-added}[14:19]{.aside}

[και]{.greek-omitted} [επατηθη]{.greek-omitted} [η]{.greek-omitted} [ληνος]{.greek-omitted} [εξωθεν]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [κ]{.greek-supplied}αι εξηλθεν αιμα εκ της ληνου [αχ]{.greek-supplied}ρι των [χαλινων]{.greek-omitted} [χαλινον]{.greek-added} των ιππων [απο]{.greek-omitted} [σταδιων]{.greek-omitted} [χιλιων]{.greek-omitted} [εξακοσιων]{.greek-omitted} [[και]{.greek-supplied}]{.greek-added} [[ε]{.unclear}πατηθη]{.greek-added} [η]{.greek-added} [ληνος]{.greek-added} [εξωθεν]{.greek-added} [της]{.greek-added} [πολεως]{.greek-added}[14:20]{.aside}

[και]{.greek-omitted} [επατηθη]{.greek-omitted} [η]{.greek-omitted} [ληνος]{.greek-omitted} [εξωθεν]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [αιμα]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [ληνου]{.greek-omitted} [αχρι]{.greek-omitted} [των]{.greek-omitted} [χαλινων]{.greek-omitted} [των]{.greek-omitted} [ιππων]{.greek-omitted} απο σταδιων [χιλιων]{.greek-omitted} [χιλιον]{.greek-added} εξακοσιων[14:20 | instance no. 2]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και [θαυμαστον]{.greek-omitted} [θαυμαστων]{.greek-added} αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους [νικωντας]{.greek-omitted} [νικοντας]{.greek-added} εκ του θηριου και [εκ]{.greek-omitted} της εικονος [αυτου]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [αριθμου]{.greek-omitted} [του]{.greek-omitted} [ονοματος]{.greek-omitted} αυτου εστωτας επι την θαλασσαν την [υαλινην]{.greek-omitted} [υελινην]{.greek-added} [εχοντας]{.greek-omitted} [εχωντας]{.greek-added} [τας]{.greek-added} κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και αδουσιν την ωδην μωυσεως [του]{.greek-omitted} δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} παντοκρατωρ δικαιαι και [αληθιναι]{.greek-omitted} [αληθηναι]{.greek-added} αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη [φοβηθη]{.greek-omitted} [φοβηθησι]{.greek-added} [σε]{.greek-omitted} [κυριε]{.greek-abbr} και [δοξαση]{.greek-omitted} [δοξασοι]{.greek-added} το ονομα σου οτι μονος αγιος οτι [παντες]{.greek-added} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} ηξουσιν και προσκυνησουσιν ενωπιον σου οτι τα [δικαιωματα]{.greek-omitted} [δικαιοματα]{.greek-added} σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και [ηνοιγη]{.greek-omitted} [οινοιγη]{.greek-added} ο ναος [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} της σκηνης του μαρτυριου εν τω ουρανω[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας εκ του ναου οι ησαν ενδεδυμενοι [λινον]{.greek-omitted} [ληνον]{.greek-added} καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και [εν]{.greek-omitted} εκ των τεσσαρων ζωων εδωκεν τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[15:7]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [εδωκεν]{.greek-omitted} [τοις]{.greek-omitted} [επτα]{.greek-omitted} [αγγελοις]{.greek-omitted} [επτα]{.greek-omitted} [φιαλας]{.greek-omitted} [χρυσας]{.greek-omitted} [γεμουσας]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [ζωντος]{.greek-omitted} εις τους αιωνας των αιωνων[15:7 | instance no. 2]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις εδυνατο [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις τον ναον αχρι [τελεσθωσιν]{.greek-omitted} [τελεσθωσι]{.greek-added} αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} λεγουσης τοις επτα αγγελοις υπαγετε [και]{.greek-omitted} εκχεατε τας επτα [φιαλας]{.greek-omitted} [φυαλας]{.greek-added} του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος και εξεχεεν την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας [του]{.greek-added} [θηριου]{.greek-added} το χαραγμα [του]{.greek-omitted} [θηριου]{.greek-omitted} και [τους]{.greek-omitted} [προσκυνουντας]{.greek-omitted} [προσκυνουντες]{.greek-added} τη [εικονι]{.greek-omitted} [εικον]{.greek-added} [η]{.greek-added} αυτου[16:2]{.aside}

και ο δευτερος αγγελος εξεχεεν την [φιαλην]{.greek-omitted} [φιαλλην]{.greek-added} αυτου εις την θαλασσαν και εγενετο [ως]{.greek-added} αιμα [ως]{.greek-omitted} νεκρου και πασα ψυχη ζωσα απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος εξεχεεν την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην [ο]{.greek-omitted} οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι [αιμα]{.greek-omitted} [αιματα]{.greek-added} [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα [α]{.unclear}υτοις εδωκας πιειν [οτι]{.greek-added} αξιοι [ει]{.greek-supplied}σιν[16:6]{.aside}

και ηκουσα του θυσιαστηρι[ο]{.greek-supplied}[υ]{.unclear} λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παν[το]{.greek-supplied}κρατωρ [αληθιναι]{.greek-omitted} [αληθηναι]{.greek-added} και δικαιαι αι [κρισεις]{.greek-omitted} [κρισει]{.greek-added} σου[16:7]{.aside}

και ο τεταρτος [αγγελος]{.greek-omitted} εξεχεεν την φιαλην αυτου επι τον ηλιον και εδοθη αυτω [καυματισαι]{.greek-omitted} [καυματησαι]{.greek-added} εν πυρι τους [ανθρωπους]{.greek-abbr}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος εξεχεεν την φιαλην αυτου επι [τον]{.greek-omitted} [των]{.greek-added} θρονον του θηριου και εγενετο η βασιλεια αυτου [εσκοτωμενη]{.greek-omitted} [εσκοτομενη]{.greek-added} και [εμασωντο]{.greek-omitted} [εμασσον]{.greek-added} [το]{.greek-added} τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ [των]{.greek-omitted} [ελκων]{.greek-omitted} [τα]{.greek-added} [ελκη]{.greek-added} αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [αγγελος]{.greek-added} εξεχεεν [αυτου]{.greek-added} την φιαλην [αυτου]{.greek-omitted} επι τον ποταμον τον μεγαν ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου [πνευματα]{.greek-abbr} [τρια]{.greek-added} ακαθαρτα [τρια]{.greek-omitted} ως βατραχοι[16:13]{.aside}

εισιν γαρ [πνευματα]{.greek-abbr} δαιμονιων ποιουντα σημεια α [εκπορευεται]{.greek-omitted} [εκπορευονται]{.greek-added} επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [παντοκρατορος]{.greek-omitted}[16:14]{.aside}

[εισιν]{.greek-omitted} [γαρ]{.greek-omitted} [πνευματα]{.greek-omitted} [δαιμονιων]{.greek-omitted} [ποιουντα]{.greek-omitted} [σημεια]{.greek-omitted} [α]{.greek-omitted} [εκπορευεται]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [οικουμενης]{.greek-omitted} [ολης]{.greek-omitted} [συναγαγειν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [πολεμον]{.greek-omitted} της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του [παντοκρατορος]{.greek-omitted} [παντοκρατωρος]{.greek-added}[16:14 | instance no. 2]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἁρμαγεδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον αερα και εξηλθεν φωνη μεγαλη απο του ναου του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα γεγονεν[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και φωναι και σεισμος μεγας οιος ουκ [εγενετο]{.greek-omitted} [[α]{.unclear}ιγενετο]{.greek-added} αφ ου οι [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και [ε]{.greek-added} [γενετο]{.greek-added} [εγενετο]{.corr} η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα νησος εφυγεν και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν [ο]{.greek-supplied}ι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης [τ]{.greek-supplied}[η]{.unclear}ς χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας και ελαλησεν μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι των υδατων των πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και απηνεγκεν με εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον κοκκινον γεμον ονοματα βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἢν]{.greek-added} περιβεβλημενη πορφυρουν και κοκκινον [κεχρυσωμενη]{.greek-omitted} [κεκαιχρυσωμενη]{.greek-added} χρυσιω και λιθω τιμιω και μαργαριταις εχουσα ποτηριον χρυσουν εν τη χειρι αυτης γεμον βδελυγματων και τα ακαθαρτα της πορνειας [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[17:4]{.aside}

και επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν [εκ]{.greek-omitted} του αιματος των αγιων εκ του αιματος των [αγιων]{.greek-added} μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και ειπεν μοι ο αγγελος δια τι εθαυμασας [εγω]{.greek-omitted} [ερω]{.greek-omitted} [σοι]{.greek-omitted} [το]{.greek-omitted} [μυστηριον]{.greek-omitted} [της]{.greek-omitted} [γυναικος]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [του]{.greek-omitted} [βασταζοντος]{.greek-omitted} [αυτην]{.greek-omitted} [του]{.greek-omitted} [εχοντος]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [κεφαλας]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [δεκα]{.greek-omitted} [κερατα]{.greek-omitted}[17:7]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [μοι]{.greek-omitted} [ο]{.greek-omitted} [αγγελος]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [εθαυμασας]{.greek-omitted} εγω ερω σοι το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7 | instance no. 2]{.aside}

το θηριον ο ειδες ην και ουκ εστιν και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων ου γεγραπται [τα]{.greek-omitted} [το]{.greek-added} [ονοματα]{.greek-omitted} [ονομα]{.greek-added} επι [το]{.greek-omitted} [του]{.greek-added} [βιβλιον]{.greek-omitted} [βιβλιου]{.greek-added} της ζωης απο καταβολης κοσμου βλεποντων οτι ην το θηριον και ουκ εστιν και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [βασιλεις]{.greek-added} [εισιν]{.greek-added} [επτα]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ο εις εστιν ο αλλος ουπω ηλθεν και οταν ελθη ολιγον δει αυτον μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ εστιν και [αυτος]{.greek-omitted} [ουτος]{.greek-added} ογδοος εστιν και εκ των επτα εστιν και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [ου]{.greek-added} λαμβανουσιν μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την [δ]{.unclear}υναμιν και [την]{.greek-omitted} εξουσιαν αυτων [τ]{.greek-supplied}[ω]{.unclear} θηριω διδοασιν[17:13]{.aside}

ουτοι μετα [το]{.greek-supplied}υ αρνιου πολεμησουσιν [και]{.greek-omitted} [το]{.greek-omitted} [αρνιον]{.greek-omitted} [νικησει]{.greek-omitted} [αυτους]{.greek-omitted} [οτι]{.greek-omitted} [κυριος]{.greek-omitted} [κυριων]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [βασιλευς]{.greek-omitted} [βασιλεων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [κλητοι]{.greek-omitted} [και]{.greek-omitted} [εκλεκτοι]{.greek-omitted} [και]{.greek-omitted} [πιστοι]{.greek-omitted}[17:14]{.aside}

[ουτοι]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [πολεμησουσιν]{.greek-omitted} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων εστιν και βασιλευς βασιλεων και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14 | instance no. 2]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισισουσιν]{.greek-added} την πορνην και ηρημωμενην [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [γυμνην]{.greek-omitted} ποιησουσιν αυτην και τας σαρκας αυτης φαγονται και αυτην κατακαυσουσιν εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων [ποιησαι]{.greek-omitted} [την]{.greek-omitted} [γνωμην]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} ποιησαι γνωμην μιαν και δουναι την βασιλειαν αυτων τω θηριω αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην [ειδες]{.greek-omitted} [ιδες]{.greek-added} εστιν [η]{.greek-omitted} [υ]{.greek-added} πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων [των]{.greek-added} [επι]{.greek-added} της γης[17:18]{.aside}

### Chapter 18

μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν [ισχυρα]{.greek-omitted} [ισχυραν]{.greek-added} [φωνη]{.greek-omitted} [φωνην]{.greek-added} λεγων επεσεν βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος [πνευματος]{.greek-abbr} [δαιμονιου]{.greek-added} ακαθαρτου [και]{.greek-added} [μεμισιμενου]{.greek-added} και φυλακη παντος ορνεου ακαθαρτου και μεμισημενου[18:2]{.aside}

οτι εκ του οινου του θυμου της πορνειας αυτης πεπτωκασιν παντα τα εθνη και [οι]{.greek-omitted} [η]{.greek-added} βασιλεις της γης [η]{.greek-added} μετ αυτης [επορνευσαν]{.greek-omitted} [πορνευσαντες]{.greek-added} και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα [αλλην]{.greek-omitted} [αλην]{.greek-added} φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε εξ αυτης ο λαος μου ινα μη [συγκοινωνησητε]{.greek-omitted} [συγκοινωνησεται]{.greek-added} ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης αι [αμαρτιαι]{.greek-added} αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν και διπλωσατε αυτη διπλα κατα τα εργα αυτης εν τω [ποτηριω]{.greek-omitted} [αυτης]{.greek-added} ω εκερασεν κερασατε [αυτη]{.greek-omitted} [αυτην]{.greek-added} διπλουν[18:6]{.aside}

οσα εδοξασεν αυτην και εστρηνιασεν τοσουτον δοτε [αυτη]{.greek-omitted} [αυτην]{.greek-added} βασανισμον και πενθος οτι εν τη καρδια αυτης λεγει [οτι]{.greek-omitted} [καθημαι]{.greek-omitted} [καθημε]{.greek-added} [βασιλισσα]{.greek-omitted} [βασιλεισα]{.greek-added} και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και κλαυσουσιν και κοψονται [ε]{.greek-supplied}π [αυτην]{.greek-omitted} [αυτων]{.greek-added} οι βασιλεις της γης [οι]{.greek-omitted} [μετ]{.greek-omitted} [αυτης]{.greek-omitted} [πορνευσαντες]{.greek-omitted} [και]{.greek-omitted} [στρηνιασαντες]{.greek-omitted} [οταν]{.greek-omitted} [βλεπωσιν]{.greek-omitted} [τον]{.greek-omitted} [καπνον]{.greek-omitted} [της]{.greek-omitted} [πυρωσεως]{.greek-omitted} [αυτης]{.greek-omitted}[18:9]{.aside}

[και]{.greek-omitted} [κλαυσουσιν]{.greek-omitted} [και]{.greek-omitted} [κοψονται]{.greek-omitted} [επ]{.greek-omitted} [αυτην]{.greek-omitted} [οι]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} οι μετ αυτης πορνευσαντες και [στρηνιασαντες]{.greek-omitted} [στρινιασαντες]{.greek-added} οταν βλεπωσιν τον καπνον της πυρωσεως αυτης[18:9 | instance no. 2]{.aside}

απο μακροθεν εστηκοτες δια τον [φοβον]{.greek-omitted} [φοβου]{.greek-added} του βασανισμου αυτης λεγοντες ουαι ουαι η [πολις]{.greek-omitted} [πολης]{.greek-added} η μεγαλη βαβυλων η πολις [η]{.greek-omitted} ισχυρα οτι μια ωρα ηλθεν η [κρισις]{.greek-omitted} [κρισι]{.greek-added} σου[18:10]{.aside}

και οι εμποροι της γης κλαυσουσιν [και]{.greek-omitted} [πενθησουσιν]{.greek-omitted} επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} οτι τον γομον αυτων ουδεις αγοραζει [και]{.greek-added} ουκετι[18:11]{.aside}

γομον [χρυσου]{.greek-omitted} [χρυσουν]{.greek-added} και αργυρου και λιθου τιμιου και μαργαριτου και βυσσινου και [πορφυρου]{.greek-omitted} [πορφυρας]{.greek-added} και [σηρικου]{.greek-omitted} [σιρικου]{.greek-added} και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος [εκ]{.greek-omitted} [ξυλου]{.greek-omitted} [εξυλου]{.greek-added} τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κιναμωμου]{.greek-added} και [θυμιαματα]{.greek-omitted} [θυμιαματων]{.greek-added} και μυρον και λιβανον και [οινον]{.greek-omitted} [και]{.greek-omitted} ελαιον και σεμιδαλιν και [σιτον]{.greek-omitted} [σιτου]{.greek-added} και προβατα και [κτηνη]{.greek-omitted} [κτινη]{.greek-added} και ιππων και ραιδων και σωματων και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα [λιπαρα]{.greek-omitted} [λειπαρα]{.greek-added} και τα λαμπρα [απωλετο]{.greek-omitted} [απολοντο]{.greek-added} απο σου και ουκετι αυτα ου μη [ευρης]{.greek-omitted} [ευρεις]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης [κλαιοντες]{.greek-omitted} [και]{.greek-omitted} [πενθουντες]{.greek-omitted}[18:15]{.aside}

[και]{.greek-added} [οι]{.greek-omitted} [εμποροι]{.greek-omitted} [τουτων]{.greek-omitted} [οι]{.greek-omitted} [πλουτησαντες]{.greek-omitted} [απ]{.greek-omitted} [αυτης]{.greek-omitted} [απο]{.greek-omitted} [μακροθεν]{.greek-omitted} [στησονται]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [φοβον]{.greek-omitted} [του]{.greek-omitted} [βασανισμου]{.greek-omitted} [αυτης]{.greek-omitted} κλαιοντες και πενθουντες[18:15 | instance no. 2]{.aside}

[και]{.greek-omitted} [λεγοντες]{.greek-omitted} [ουαι]{.greek-omitted} ουαι η πολις η μεγαλη [η]{.greek-omitted} [υ]{.greek-added} περιβεβλημενη βυσσινον και πορφυρουν και κοκκινον και [κεχρυσωμενη]{.greek-omitted} [κεχρυσομενη]{.greek-added} χρυσιω και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα [ηρημωθη]{.greek-omitted} [ηρειμωθη]{.greek-added} ο τοσουτος πλουτος και πας [κυβερνητης]{.greek-omitted} [κυβερνητις]{.greek-added} και πας ο επι τοπον [πλεων]{.greek-omitted} [πλεον]{.greek-added} και ναυται και οσοι την θαλασσαν [εργαζονται]{.greek-omitted} [εργαζουνται]{.greek-added} απο μακροθεν εστησαν[18:17]{.aside}

και εκραζον [βλεποντες]{.greek-omitted} [βλεπωντες]{.greek-added} [τον]{.greek-omitted} [των]{.greek-added} καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη [πολει]{.greek-omitted} [πολι]{.greek-added} τη μεγαλη[18:18]{.aside}

και [εβαλον]{.greek-omitted} [εβαλουν]{.greek-added} [χουν]{.greek-omitted} επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες και λεγοντες ουαι ουαι η πολις η μεγαλη εν η επλουτησαν παντες οι εχοντες τα πλοια εν τη θαλασση εκ της [τιμιοτητος]{.greek-omitted} [τιμιωτητος]{.greek-added} αυτης οτι μια ωρα [ηρημωθη]{.greek-omitted} [ειρημωθη]{.greek-added}[18:19]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων [οτι]{.greek-added} [ουτως]{.greek-omitted} [ουτος]{.greek-added} ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευ[ρ]{.unclear}εθη ετι[18:21]{.aside}

και [φωνη]{.greek-omitted} [φωνην]{.greek-added} κιθαρωδων [κ]{.greek-supplied}αι μουσικων και [αυλητων]{.greek-omitted} [και]{.greek-omitted} [σαλπιστων]{.greek-omitted} [αυλιστων]{.greek-added} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [τεχνιτης]{.greek-omitted} [πασης]{.greek-omitted} [τεχνης]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22]{.aside}

[και]{.greek-omitted} [φωνη]{.greek-omitted} [κιθαρωδων]{.greek-omitted} [και]{.greek-omitted} [μουσικων]{.greek-omitted} [και]{.greek-omitted} [αυλητων]{.greek-omitted} και σαλπιστων ου μη ακουσθη [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [τεχνιτης]{.greek-omitted} [πασης]{.greek-omitted} [τεχνης]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} εν σοι ετι και φωνη μυλου ου μη ακουσθη εν σοι ετι [και]{.greek-added} [πας]{.greek-added} [τεχνητης]{.greek-added} [πασης]{.greek-added} [τεχνοις]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [ευρεθη]{.greek-added} [εν]{.greek-added} [σοι]{.greek-added} [ετι]{.greek-added}[18:22 | instance no. 2]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [ακουσθη]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη ακουσθη εν σοι ετι οτι οι εμποροι σου ησαν οι μεγι[σ]{.unclear}τανες της γης οτι εν τη φαρμακεια σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων [ευρεθη]{.greek-omitted} [ευρεθησαν]{.greek-added} και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην μεγαλην οχλου [πολλου]{.greek-omitted} [πουλλου]{.greek-added} εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-omitted} [[σωτηρι]{.greek-abbr}]{.greek-added} και η [δυναμις]{.greek-omitted} [δυναμεις]{.greek-added} και η δοξα του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι εκρινεν την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [διεφθηρεν]{.greek-added} την γην εν τη πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδηκησεν]{.greek-added} το αιμα των δουλων αυτου εκ [της]{.greek-added} χειρος αυτης[19:2]{.aside}

και δευτερον ειρηκεν αλληλουια και ο καπνος αυτης αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και [επεσον]{.greek-omitted} οι πρεσβυτεροι [επεσαν]{.greek-added} οι [εικοσι]{.greek-omitted} [οικοσι]{.greek-added} [τεσσαρες]{.greek-omitted} [τεσσαρεις]{.greek-added} και τα τεσσαρα ζωα και [προσεκυνησαν]{.greek-omitted} [προσεκυνησσαν]{.greek-added} τω [θεω]{.greek-abbr} τω [καθημενω]{.greek-omitted} [καθημενου]{.greek-added} επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη απο του θρονου εξηλθεν λεγουσα [αινειτε]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [ημων]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [δουλοι]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [φοβουμενοι]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [μικροι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μεγαλοι]{.greek-omitted}[19:5]{.aside}

[και]{.greek-omitted} [φωνη]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [εξηλθεν]{.greek-omitted} [λεγουσα]{.greek-omitted} [αινειτε]{.greek-omitted} [αινειται]{.greek-added} τον [θεον]{.greek-abbr} ημων παντες [οι]{.greek-omitted} [ι]{.greek-added} δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5 | instance no. 2]{.aside}

και ηκουσα ως φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντος]{.greek-added} αλληλουια οτι εβασιλευσεν [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και [αγαλλιωμεθα]{.greek-omitted} [αγαλλιωμενθα]{.greek-added} και δωμεν την δοξαν αυτω οτι ηλθεν ο γαμος του αρνιου και η γυνη [αυτου]{.greek-omitted} ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα περιβαληται βυσσινον λαμπρον [και]{.greek-omitted} καθαρον το γαρ βυσσινον τα δικαιωματα των αγιων εστιν[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον [του]{.greek-omitted} [γαμου]{.greek-omitted} του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι αληθινοι του [θεου]{.greek-abbr} εισιν[19:9]{.aside}

και επεσα εμπροσθεν [των]{.greek-omitted} [ποδων]{.greek-omitted} [αυτου]{.greek-omitted} [του]{.greek-added} [αγγελου]{.greek-added} προσκυνησαι αυτω και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια του [ιησου]{.greek-abbr} εστιν το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον καλουμενος πιστος και αληθινος και εν δικαιοσυνη [κρινει]{.greek-omitted} [κρινη]{.greek-added} και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [αυτου]{.greek-omitted} [διαδηματα]{.greek-omitted} [πολλα]{.greek-omitted} [εχων]{.greek-omitted} [ονοματα]{.greek-omitted} [γεγραμμενα]{.greek-omitted} [και]{.greek-omitted} [ονομα]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [ο]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [αυτος]{.greek-omitted}[19:12]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [οφθαλμοι]{.greek-omitted} [αυτου]{.greek-omitted} [φλοξ]{.greek-omitted} [πυρος]{.greek-omitted} και επι την κεφαλην αυτου διαδηματα πολλα εχων ονοματα γεγραμμενα [και]{.greek-omitted} [ονομα]{.greek-omitted} [γεγραμμενον]{.greek-omitted} ο ουδεις οιδεν ει [μη]{.greek-omitted} [μι]{.greek-added} αυτος[19:12 | instance no. 2]{.aside}

και περιβεβλημενος ιματιον βεβαμμενον αιματι και καλειται το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα [τα]{.greek-omitted} εν τω [ουρανω]{.greek-abbr} [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω [επι]{.greek-omitted} [ενφ]{.greek-added} ιπποις λευκοις [ενδεδυμενοι]{.greek-omitted} [ενδεδειμενοι]{.greek-added} βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν αυτη [παταξη]{.greek-omitted} [παταξει]{.greek-added} τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος πατει την ληνον του οινου του θυμου της οργης [αυτου]{.greek-added} του [θεου]{.greek-abbr} του [παντοκρατορος]{.greek-omitted} [παντοκρατωρος]{.greek-added}[19:15]{.aside}

και εχει επι το ιματιον και επι τον [μηρον]{.greek-omitted} [μυρον]{.greek-added} αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον αγγελον εστωτα εν τω ηλιω και εκραξεν φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} δευτε συναχθητε εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον [το]{.greek-omitted} [τον]{.greek-added} [μεγα]{.greek-omitted} [μεγαν]{.greek-added} του [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων και [μικρων]{.greek-omitted} [μικρον]{.greek-added} τε και μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της [γης]{.greek-omitted} [οικουμενης]{.greek-added} [[οικουμενοις]{.corr}]{.greek-added} και τα στρατευματα αυτων [συνηγμενα]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [ιππου]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [στρατευματος]{.greek-omitted} [αυτου]{.greek-omitted}[19:19]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [στρατευματα]{.greek-omitted} [αυτων]{.greek-omitted} συνηγμενα ποιησαι [τον]{.greek-added} πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19 | instance no. 2]{.aside}

και επιασθη το θηριον και ο μετ αυτου ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις επλανησεν τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες εβληθησαν οι δυο εις την λιμνην του πυρος την καιομενην εν θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη [εξελθουση]{.greek-omitted} [εξελθουσι]{.greek-added} εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον [αλλον]{.greek-added} καταβαινοντα εκ του [ουρανου]{.greek-abbr} [εχοντα]{.greek-omitted} [εχον]{.greek-added} την [κλιδαν]{.greek-added} [κλειν]{.greek-omitted} [[κλειδαν]{.corr}]{.greek-added} της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και εκρατησεν τον δρακοντα τον οφιν τον αρχαιον ος εστιν διαβολος και [ο]{.greek-omitted} σατανας ο πλανων την οικουμενην ολην και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και εκλεισεν και εσφραγισεν επανω αυτου ινα μη πλανα ετι τα εθνη αχρι τελεσθη τα χιλια ετη [και]{.greek-omitted} μετα ταυτα δει [λυθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και ειδον θρονους και [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} επ αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου [προσεκυνησαν]{.greek-omitted} [προσεκεινησαν]{.greek-added} το θηριον [[θηριω]{.corr}]{.greek-added} ουδε [την]{.greek-omitted} [τη]{.greek-added} [εικονα]{.greek-omitted} [ει[κο]{.greek-supplied}[ν]{.unclear}η]{.greek-added} αυτου και ουκ ελαβον το χαραγμα επι [το]{.greek-omitted} [μετωπον]{.greek-omitted} [των]{.greek-added} [μετοπων]{.greek-added} και επι την χειρα αυτων και εζησαν και [εβασιλευσαν]{.greek-omitted} [ευασιλευσαν]{.greek-added} μετα του [χριστου]{.greek-abbr} τα χιλια ετη[20:4]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [οτι]{.greek-added} [λοιποι]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [ουκ]{.greek-omitted} [εζησαν]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθη]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν τη αναστασει τη πρωτη επι τουτων ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και βασιλευσουσιν [μετ]{.greek-omitted} [μετα]{.greek-added} [αυτου]{.greek-omitted} [ταυτα]{.greek-added} χιλια ετη[20:6]{.aside}

και [μετα]{.greek-added} [οταν]{.greek-omitted} [τελεσθη]{.greek-omitted} τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη τα εν ταις τεσσαρσιν γωνιαις της γης τον γωγ και τον μαγωγ συναγαγειν αυτους εις τον πολεμον ων ο αριθμος [ως]{.greek-omitted} [η]{.greek-omitted} [αυτων]{.greek-added} [ωσει]{.greek-added} αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και εκυκλωσαν την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος [και]{.greek-omitted} [του]{.greek-added} θειου [οπου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ψευδοπροφητης]{.greek-omitted} [και]{.greek-omitted} [βασανισθησονται]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [νυκτος]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[20:10]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [διαβολος]{.greek-omitted} [ο]{.greek-omitted} [πλανων]{.greek-omitted} [αυτους]{.greek-omitted} [εβληθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [λιμνην]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [θειου]{.greek-omitted} οπου και το θηριον [και]{.greek-omitted} ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10 | instance no. 2]{.aside}

και ειδον θρονον μεγαν λευκον και τον καθημενον επ αυτον ου απο προσωπου εφυγεν η γη και ο [ουρανος]{.greek-abbr} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον [τους]{.greek-omitted} [νεκρους]{.greek-omitted} τους μεγαλους και τους μικρους [τους]{.greek-added} [νεκρους]{.greek-added} εστωτας ενωπιον του θρονου και βιβλια [ηνεωχθησαν]{.greek-omitted} [ηνοιξεν]{.greek-added} και αλλο βιβλιον ηνεωχθη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν αυτη και [ο]{.greek-omitted} θανατος και ο αδης εδωκαν τους νεκρους τους εν αυτοις και εκριθησαν εκαστος κατα τα εργα αυτων[20:13]{.aside}

και ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ει τις ουχ ευρεθη εν τω βιβλιω της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη [απηλθον]{.greek-omitted} [παρηλθεν]{.greek-added} και [η]{.unclear} θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} ητοιμασμενην ως νυμφην κεκοσμημενην τω ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} [εσται]{.greek-omitted} μετ αυτων [εσται]{.greek-added}[21:3]{.aside}

και [εξαλειψει]{.greek-omitted} [εξαλειφη]{.greek-added} παν δακρυον απο των [οφθαλμων]{.greek-omitted} [οφθαλμον]{.greek-added} αυτων και ο θανατος ουκ εσται ετι ουτε πενθος ουτε κραυγη [ουτε]{.greek-omitted} [ου]{.greek-added} πονος ουκ εσται ετι οτι τα πρωτα [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added}[21:4]{.aside}

και ειπεν ο καθημενος επι τω θρονω ιδου παντα καινα ποιω και λεγει [μοι]{.greek-omitted} γραψον [οτι]{.greek-omitted} [οτοι]{.greek-added} ουτοι οι λογοι [πιστοι]{.greek-added} [και]{.greek-added} αληθινοι [και]{.greek-omitted} [πιστοι]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εισιν[21:5]{.aside}

και ειπεν μοι γεγονα το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} η αρχη και το τελος εγω τω [διψωντι]{.greek-omitted} [διψοντι]{.greek-added} δωσω εκ της πηγης του υδατος [της]{.greek-omitted} [ζωης]{.greek-omitted} δωρεαν[21:6]{.aside}

ο νικων [κληρονομησει]{.greek-omitted} [δωσω]{.greek-added} [αυτω]{.greek-added} ταυτα και εσομαι αυτω [θεος]{.greek-abbr} και αυτος εσται [μοι]{.greek-omitted} [μου]{.greek-added} υιος[21:7]{.aside}

τοις δε δειλοις και απιστοις και αμαρτωλοις και εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} και πορνοις και φαρμακοις και [ειδωλολατραις]{.greek-omitted} [ειδωλωλατραις]{.greek-added} και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ψευδεσιν το μερος αυτων [εν]{.greek-omitted} τη λιμνη τη καιομενη πυρι και θειω [ο]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted}[21:8]{.aside}

[τοις]{.greek-omitted} [δε]{.greek-omitted} [δειλοις]{.greek-omitted} [και]{.greek-omitted} [απιστοις]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλοις]{.greek-omitted} [και]{.greek-omitted} [εβδελυγμενοις]{.greek-omitted} [και]{.greek-omitted} [φονευσιν]{.greek-omitted} [και]{.greek-omitted} [πορνοις]{.greek-omitted} [και]{.greek-omitted} [φαρμακοις]{.greek-omitted} [και]{.greek-omitted} [ειδωλολατραις]{.greek-omitted} [και]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [ψευδεσιν]{.greek-omitted} [το]{.greek-omitted} [μερος]{.greek-omitted} [αυτων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [λιμνη]{.greek-omitted} [τη]{.greek-omitted} [καιομενη]{.greek-omitted} [πυρι]{.greek-omitted} [και]{.greek-omitted} [θειω]{.greek-omitted} ο εστιν ο θανατος ο δευτερος[21:8 | instance no. 2]{.aside}

και [ηλθεν]{.greek-omitted} [ειλλθεν]{.greek-added} εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας γεμουσας [των]{.greek-omitted} επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την γυναικα την νυμφην του αρνιου[21:9]{.aside}

και απηνεγκεν με εν [πνευματι]{.greek-abbr} επ ορος μεγα και υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} [μοι]{.greek-omitted} [με]{.greek-added} την πολιν [την]{.greek-omitted} [μεγαλην]{.greek-omitted} την αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του [θεου]{.greek-abbr}[21:10]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης ομοιος λιθω τιμιωτατω ως λιθω ιασπιδι κρυσταλλιζοντι[21:11]{.aside}

εχουσα τειχος μεγα και υψηλον εχουσα πυλωνας δωδεκα και επι τοις πυλωσιν αγγελους [δωδεκα]{.greek-omitted} [δεκαδυο]{.greek-added} και ονοματα επιγεγραμμενα α εστιν ονοματα των δωδεκα φυλων [των]{.greek-omitted} υιων [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο ανατολων πυλωνες τρεις και απο βορρα πυλωνες τρεις και απο νοτου πυλωνες τρεις και απο δυσμων πυλωνες τρεις[21:13]{.aside}

και το τειχος της πολεως εχον θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου ειχεν μετρον καλαμον χρυσουν [ινα]{.greek-omitted} [μετρηση]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πυλωνας]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τειχος]{.greek-omitted} [αυτης]{.greek-omitted}[21:15]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [λαλων]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [ειχεν]{.greek-omitted} [μετρον]{.greek-omitted} [καλαμον]{.greek-omitted} [χρυσουν]{.greek-omitted} ινα μετρηση την πολιν και τους πυλωνας αυτης [και]{.greek-omitted} [το]{.greek-omitted} [τειχος]{.greek-omitted} [αυτης]{.greek-omitted}[21:15 | instance no. 2]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν τω καλαμω επι σταδιους [δωδεκα]{.greek-omitted} [δεκαδυο]{.greek-added} χιλιαδων δωδεκα το μηκος και το πλατος και το υψος αυτης ισα εστιν[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} [εμετρισε]{.greek-added} το τειχος αυτης εκατον τεσσαρακοντα τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον ομοιον υελω καθαρω[21:18]{.aside}

οι θεμελιοι του τειχους της πολεως παντι λιθω τιμιω [κεκοσμημενοι]{.greek-omitted} [καικοσμημενοι]{.greek-added} ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος σαρδονυξ ο εκτος σαρδιον ο εβδομος χρυσολιθος ο ογδοος βηρυλλος ο ενατος τοπαζιον ο δεκατος [χρυσοπρασος]{.greek-omitted} [χρυσοπρασινος]{.greek-added} ο ενδεκατος υακινθος ο δωδεκατος [αμεθυσος]{.greek-omitted} [αμεθυστος]{.greek-added}[21:20]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται ανα εις εκαστος των πυλωνων ην εξ ενος μαργαριτου και η [πλαλετεια]{.greek-added} [πλατεια]{.corr} της πολεως χρυσιον καθαρον [ως]{.greek-omitted} [υελος]{.greek-omitted} [διαυγης]{.greek-omitted}[21:21]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [δωδεκα]{.greek-omitted} [πυλωνες]{.greek-omitted} [δωδεκα]{.greek-omitted} [μαργαριται]{.greek-omitted} [ανα]{.greek-omitted} [εις]{.greek-omitted} [εκαστος]{.greek-omitted} [των]{.greek-omitted} [πυλωνων]{.greek-omitted} [ην]{.greek-omitted} [εξ]{.greek-omitted} [ενος]{.greek-omitted} [μαργαριτου]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πλατεια]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [χρυσιον]{.greek-omitted} [καθαρον]{.greek-omitted} ως υελος διαυγης[21:21 | instance no. 2]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν αυτη [γαρ]{.greek-added} η [γαρ]{.greek-omitted} δοξα του [θεου]{.greek-abbr} [εφωτισεν]{.greek-omitted} [εφωτησεν]{.greek-added} αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης φερουσιν αυτω δοξαν και τιμην των εθνων εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην [ινα]{.greek-added} [εισελθωσιν]{.greek-added}[21:26]{.aside}

και ου μη εισελθη εις αυτην παν κοινον και [ποιουν]{.greek-omitted} [ο]{.greek-added} [ποιων]{.greek-added} βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον [καθαρον]{.greek-omitted} υδατος ζωης λαμπρον ως κρυσταλλον εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και εκειθεν ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα [αποδιδους]{.greek-added} εκαστον [αποδιδους]{.greek-omitted} [τον]{.greek-omitted} καρπον αυτου και τα φυλλα του ξυλου εις θεραπειαν των εθνων[22:2]{.aside}

και παν καταθεμα ουκ εσται ετι και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι δουλοι αυτου λατρευσουσιν αυτω[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των μετωπων αυτων[22:4]{.aside}

και νυξ ουκ εσται εκει και [ου]{.greek-added} [χρειαν]{.greek-omitted} [χρεια]{.greek-added} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} λυχνου και φωτος [ηλιου]{.greek-omitted} οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} φωτιει αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και λεγει μοι ουτοι οι λογοι πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των πνευματων των προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

και ιδου [ερχομαι]{.greek-omitted} [ερχομε]{.greek-added} ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

καγω ιωαννης ο ακουων και βλεπων ταυτα και οτε ηκουσα και [εβλεψα]{.greek-omitted} [οτε]{.greek-added} [ειδον]{.greek-added} επεσον προσκυνησαι [εμπροσθεν]{.greek-omitted} [εμπροσθε]{.greek-added} των ποδων του αγγελου του [δεικνυοντος]{.greek-omitted} [δεικνυντος]{.greek-added} μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των προφητων και των τηρουντων τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου ο καιρος [γαρ]{.greek-omitted} εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος ρυπαρευθητω ετι [και]{.greek-omitted} [ο]{.greek-omitted} [δικαιος]{.greek-omitted} [δικαιοσυνην]{.greek-omitted} [ποιησατω]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [αγιασθητω]{.greek-omitted} [ετι]{.greek-omitted}[22:11]{.aside}

[ο]{.greek-omitted} [αδικων]{.greek-omitted} [αδικησατω]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ρυπαρος]{.greek-omitted} [ρυπαρευθητω]{.greek-omitted} [ετι]{.greek-omitted} και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11 | instance no. 2]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον εσται αυτου[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} ο πρωτος και ο εσχατος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι φονεις και οι ειδωλολατραι και πας φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} [επεμψα]{.greek-omitted} [επεψα]{.greek-added} τον αγγελον μου μαρτυρησαι υμιν ταυτα επι ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} ο αστηρ ο λαμπρος ο πρωινος[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν ερχου και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι τω ακουοντι τους λογους της προφητειας του βιβλιου τουτου εαν τις επιθη επ αυτα επιθησαι ο [θεος]{.greek-abbr} επ αυτον τας πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και εαν τις αφελη απο των λογων του βιβλιου της προφητειας ταυτης [αφελοι]{.greek-omitted} [αφελαι]{.greek-added} ο [θεος]{.greek-abbr} το [μ]{.greek-supplied}ερος αυτου απο του ξυλου της ζωης [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [της]{.greek-omitted} [αγιας]{.greek-omitted} [των]{.greek-omitted} [γεγραμμενων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [τουτω]{.greek-omitted}[22:19]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [τις]{.greek-omitted} [αφελη]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [λογων]{.greek-omitted} [του]{.greek-omitted} [βιβλιου]{.greek-omitted} [της]{.greek-omitted} [προφητειας]{.greek-omitted} [ταυτης]{.greek-omitted} [αφελοι]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [το]{.greek-omitted} [μερος]{.greek-omitted} [αυτου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} και εκ της πολεως της αγιας των γεγραμμενων εν τω βιβλιω τουτω[22:19 | instance no. 2]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην ναι ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων αμην[22:21]{.aside}

