---
title: "Collation of Byz^RP^ vs 30632 (632)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 632 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30632).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 632                                   	| λογος                              	|
| 632 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 632 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 632               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 632                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 632 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 632                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 6

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [λεγουσαν]{.greek-omitted} χοινιξ σιτου δηναριου και τρεις χοινικες κριθης δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης ηκολουθει αυτω και εδοθη αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν του αρνιου ην ειχον[6:9]{.aside}

και [εκραξαν]{.greek-omitted} [εκραξον]{.greek-added} [[εκραζον]{.corr}]{.greek-added} [φωνην]{.greek-added} [μεγαλην]{.greek-added} [φωνη]{.corr} [μεγαλη]{.corr} λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις [εκαστω]{.corr} στολη λευκη και ερρεθη [[μικρον]{.corr}]{.greek-added} αυτοις ινα αναπαυσωνται ετι χρονον εως [πληρωσωσιν]{.greek-omitted} [πληρωσουσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων και οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος μελας εγενετο ως σακκος τριχινος και η σεληνη ολη εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον [εις]{.greek-omitted} [επι]{.greek-added} την γην ως συκη βαλουσα τους ολυνθους [αυτης]{.greek-omitted} [υπο]{.greek-omitted} [ανεμου]{.greek-omitted} [μεγαλου]{.greek-omitted} [σειομενη]{.greek-omitted}[6:13]{.aside}

