---
title: "Collation of Byz^RP^ vs 30687 (687)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 687 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30687).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 687                                   	| λογος                              	|
| 687 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 687 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 687               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 687                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 687 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 687                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 10

[οστις]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [αρνησηται]{.greek-omitted} [με]{.greek-omitted} [εμπροσθεν]{.greek-omitted} των [ανθρωπων]{.greek-abbr} αρνησομαι αυτον καγω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:33]{.aside}

μη [νομισητε]{.greek-omitted} [νομησητε]{.greek-added} οτι ηλθον βαλειν ειρηνην επι την γην ουκ ηλθον βαλειν ειρηνην αλλα μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και [θυγατερα]{.greek-omitted} [θυγατεραν]{.greek-added} κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

[κα]{.greek-supplied}ι εχθροι του [ανθρωπου]{.greek-abbr} οι [οικειακοι]{.greek-omitted} [οικιακοι]{.greek-added} αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος και ο φιλων [υιον]{.greek-abbr} η θυγατερα υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον σταυρον αυτου και ακολουθει οπισω μου ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε [δεχετε]{.greek-added} [δεχεται]{.corr} και ο εμε δεχομενος [δεχετ[ε]{.unclear}]{.greek-added} [δεχεται]{.corr} τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψ[ετ]{.unclear}αι[10:41]{.aside}

και ος εαν ποτιση ενα των μικρων τουτων ποτηριον [ψυχρου]{.greek-omitted} [ψυχρουν]{.greek-added} μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε [ετελεσεν]{.greek-omitted} [συνετελεσεν]{.greek-added} ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και [κη]{.greek-added} [κηρυσσειν]{.greek-omitted} [ρυσσειν]{.greek-added} εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε ιωαννης [[ακ]{.greek-supplied}ουσας]{.corr} εν τω δεσμωτηριω τα εργα [ακουσας]{.greek-added} του [χριστου]{.greek-abbr} πεμψας [δια]{.greek-added} [δυο]{.corr} των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι αναβλεπουσ[ιν]{.greek-supplied} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται και κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} [και]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωαννου τι εξηλθετε εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι εξηλθετε ιδειν ανθρωπον εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι εξηλθετε ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ εστιν περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων μειζων ιωαννου του βαπτιστου ο δε [μικρο]{.greek-added} [μικροτερος]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [μειζων]{.greek-omitted} [αυτου]{.greek-omitted} [εστιν]{.greek-omitted}[11:11]{.aside}

### Chapter 13

[παλιν]{.greek-omitted} [ομοια]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [θησαυρω]{.greek-omitted} [κεκρυμμενω]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αγρω]{.greek-omitted} [ον]{.greek-omitted} [ευρων]{.greek-omitted} [ανθρωπος]{.greek-omitted} [εκρυψεν]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [χαρας]{.greek-omitted} [αυτου]{.greek-omitted} [υπαγει]{.greek-omitted} [και]{.greek-omitted} [παντα]{.greek-omitted} [οσα]{.greek-omitted} [εχει]{.greek-omitted} [πωλει]{.greek-omitted} [και]{.greek-omitted} [αγοραζει]{.greek-omitted} [τον]{.greek-omitted} [αγρον]{.greek-omitted} [γρον]{.greek-added} εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των ουρανων [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

ος ευρων ενα πολυτιμον μαργαριτην απελθων πεπρακεν παντα οσα ειχεν και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των ουρανων σαγηνη βληθειση εις την θαλασ[σ]{.greek-supplied}αν και εκ παν[τος]{.greek-supplied} γενους συναγαγουση[13:47]{.aside}

ην οτε επληρωθη [αναβηβασαντες]{.greek-added} [αναβιβασαντες]{.corr} [αυτην]{.greek-added} επι τον αιγιαλον και [καθησαντες]{.greek-added} [καθισαντες]{.corr} συνελεξαν τα καλα εις αγγεια τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται εν τη συντελεια του αιωνος εξελευσονται οι αγγελοι και [αφοριουσιν]{.greek-omitted} [αφοριουσι]{.greek-added} τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:50]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα λεγουσιν αυτω ναι κυριε[13:51]{.aside}

ο δε ειπεν αυτοις δια τουτο πας γραμματευς μαθητευθεις [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [βασιλειαν]{.greek-omitted} [βασιλεια]{.greek-added} [τω]{.unclear}ν [ουρανων]{.greek-abbr} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εκβαλλει εκ του θησαυρου αυτου καινα και παλαια[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας μετηρεν εκειθεν[13:53]{.aside}

και ελθων εις την πατριδα αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων [ωστε]{.unclear} [εκπληττεσθαι]{.greek-omitted} [εκλησσεσθαι]{.greek-added} αυτους και λεγειν ποθεν [το]{.unclear}υτω η σοφια αυτη και αι δυναμεις[13:54]{.aside}

ουχ ουτος εστιν ο του τεκτονος [υιος]{.greek-abbr} [ουχι]{.greek-omitted} [ουχ]{.greek-added} η [μητηρ]{.greek-abbr} αυτου λεγεται μαριαμ και οι αδελφοι αυτ[ο]{.unclear}υ ιακωβος και ιωσης και σιμων και ιουδας[13:55]{.aside}

και αι αδελφαι αυτου ουχι πασαι προς ημας εισιν ποθεν ουν τουτω τα[υ]{.greek-supplied}τα παντα[13:56]{.aside}

και εσκανδαλιζοντο εν αυτω ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει [μη]{.greek-omitted} [μι]{.greek-added} εν τη πατριδι αυτου και εν τη οικια αυτου[13:57]{.aside}

και ουκ εποιησεν εκει δυναμεις πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο τετραρχης την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις παισιν αυτου ουτος εστιν ιωαννης ο βαπτιστης αυτος ηγερθη απο των νεκρ[ων]{.unclear} κ[αι]{.unclear} [δ]{.unclear}ια τ[ο]{.unclear}υτο αι [δυναμις]{.greek-added} [δυναμεις]{.corr} ενεργουσιν εν αυτω[14:2]{.aside}

ο γαρ ηρωδης κρατησας τον ιωαννην εδησεν αυτον και εθετο εν φυλακη δια ηρωδιαδα την [γ]{.unclear}υναικα φιλιπ[πο]{.greek-supplied}υ το[υ]{.unclear} αδελφο[υ]{.greek-supplied} αυτου[14:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω ο ιωαννης ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων δε αγομενων του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και [ηρεσεν]{.greek-omitted} [ηρεσε]{.greek-added} [τω]{.greek-omitted} [ηρωδη]{.greek-omitted}[14:6]{.aside}

### Chapter 15

[αφετε]{.greek-omitted} [αυτους]{.greek-omitted} [οδηγοι]{.greek-omitted} [εισιν]{.greek-omitted} [τυφλοι]{.greek-omitted} [τυφλων]{.greek-omitted} τυφλος δε τυφλον εαν οδηγη αμφοτεροι εις βοθυνον πεσουνται[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν ακμην και υμεις ασυνετοι εστε[15:16]{.aside}

ουπω νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευ[ομενα]{.greek-supplied} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [εξερχεται]{.greek-omitted} [κακεινα]{.greek-omitted} [κοινοι]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[15:18]{.aside}

[εκ]{.greek-omitted} [γαρ]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [εξερχονται]{.greek-omitted} [διαλογισμοι]{.greek-omitted} [πονηροι]{.greek-omitted} [φονοι]{.greek-omitted} [μοιχειαι]{.greek-omitted} [πορνειαι]{.greek-omitted} [κλοπαι]{.greek-omitted} [ψευδομαρτυριαι]{.greek-omitted} [βλασφημιαι]{.greek-omitted}[15:19]{.aside}

[ταυτα]{.greek-omitted} [εστιν]{.greek-omitted} [τα]{.greek-omitted} [κοινουντα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted} το δε ανιπτοις χερσιν φαγειν ου κοινοι τον ανθρωπον[[15:20 *(lacunose)*]{.lacunose}]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα μερη τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα [εκραυγασεν]{.greek-omitted} [εκραυγαζεν]{.greek-added} αυτω λεγουσα ελεησον με κυριε υιε δαυιδ η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε ουκ απεκριθη αυτη λογον και προσελθοντες οι μαθηται [αυτου]{.greek-omitted} [ηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [λεγοντες]{.greek-omitted} [απολυσον]{.greek-omitted} [αυτην]{.greek-omitted} [οτι]{.greek-omitted} [κραζει]{.greek-omitted} [οπισθεν]{.greek-omitted} [ημων]{.greek-omitted}[[15:23 *(lacunose)*]{.lacunose}]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [στι]{.greek-added} καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ναι κυριε και γαρ τα κυναρια εσθιει απο των ψιχιων των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη ω γυναι μεγαλη σου η πιστις γενηθητω σοι ως θελεις και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μετα[βας]{.greek-supplied} [εκειθεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ηλθεν]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [και]{.greek-omitted} [αναβας]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ορος]{.greek-omitted} [εκαθητο]{.greek-omitted} [εκει]{.greek-omitted}[[15:29 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [προσηλθον]{.greek-omitted} [αυτω]{.greek-omitted} [οχλοι]{.greek-omitted} [πολλοι]{.greek-omitted} [εχοντες]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [χωλους]{.greek-omitted} [τυφλους]{.greek-omitted} [κωφους]{.greek-omitted} [κυλλους]{.greek-omitted} [και]{.greek-omitted} [ετερους]{.greek-omitted} [πολλους]{.greek-omitted} [και]{.greek-omitted} [ερριψαν]{.greek-omitted} [αυτους]{.greek-omitted} [παρα]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} και εθεραπευσεν αυτους[[15:30 *(lacunose)*]{.lacunose}]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους λαλουντας κυλλους υγιεις [και]{.greek-added} χωλους περιπατουντας και τυφλους βλεποντας και εδοξασαν τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [σπλαγχνιζομαι]{.greek-omitted} [σπλαχνιζομαι]{.greek-added} επι τον οχλον οτι ηδη ημερ[αι]{.unclear} τρεις προσμενου[σιν]{.greek-supplied} [μοι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted} [και]{.greek-omitted} [απολυσαι]{.greek-omitted} [αυτους]{.greek-omitted} [νηστεις]{.greek-omitted} [ου]{.greek-omitted} [θελω]{.greek-omitted} [μηποτε]{.greek-omitted} [εκλυθωσιν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted}[[15:32 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ποσους]{.greek-omitted} [αρτους]{.greek-omitted} [εχετε]{.greek-omitted} οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τοις οχλοις αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις αυτου οι δε μαθηται [τω]{.greek-omitted} [οχλω]{.greek-omitted} [τοις]{.greek-added} [οχλοις]{.greek-added}[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας πληρεις[15:37]{.aside}

οι δε [εσ]{.greek-supplied}θιοντες ησαν τετρακισχιλιοι ανδρες χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους [ενεβη]{.greek-omitted} [ανεβη]{.greek-added} εις το πλοιον και ηλθεν εις τα ορια [μαγδαλα]{.greek-omitted} [μαγδαλαν]{.greek-added}[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε ευδια [πυραζει]{.greek-added} [πυρραζει]{.corr} γαρ ο [ουρανος]{.greek-abbr}[16:2]{.aside}

και πρωι σημερον χειμων πυρραζει γαρ στυγναζων ο [ουρανος]{.greek-abbr} [υποκριται]{.greek-omitted} το μεν προσωπον του [ουρανου]{.greek-abbr} γινωσκετε διακρινειν τα δε σημεια των καιρων ου δυνασθε [δοκιμαζειν]{.greek-added}[16:3]{.aside}

γενεα πονηρα και μοιχ[α]{.greek-supplied}[λ]{.unclear}ις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου και καταλιπων αυτους [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν επελαθοντο αρτους λαβειν[16:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ορατε και προσεχετε απο της ζυμης των [φαρισαιων]{.greek-omitted} [φαρισαι]{.greek-added} [ων]{.greek-added} και σαδδουκαιων[16:6]{.aside}

οι δε διελογιζοντο εν εαυτοις λεγοντες οτι αρτους ουκ ελαβομεν[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτοις]{.greek-omitted} τι [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν εαυτοις [λεγοντες]{.greek-added} ολιγοπιστοι οτι αρτους ουκ ελαβετε[16:8]{.aside}

ουπω νοειτε ουδε μνημονευετε τους πεντε αρτους των [πεντακισχιλιων]{.greek-omitted} [επτακισχιλιων]{.greek-added} και ποσους [κοφινους]{.greek-omitted} [κωφινους]{.greek-added} ελαβετε[16:9]{.aside}

ουδε τους επτα αρτους των τετρακισχιλιων και ποσας σπυριδας ελαβετε[16:10]{.aside}

πως ου νοειτε οτι ου περι [αρτου]{.greek-omitted} [αρτων]{.greek-added} ειπον υμιν προσεχειν απο της ζυμης των φαρισαιων και σαδδουκαιων[16:11]{.aside}

τοτε συνηκαν οτι ουκ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προσεχειν απο της ζυμης του αρτου αλλα απο της διδαχης των φαρισαιων και σαδδουκαιων[16:12]{.aside}

ελθων δε ο [ιησους]{.greek-abbr} εις τα μερη καισαρειας της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι ανθρωποι ειναι τον [υιον]{.greek-abbr} του ανθρωπου[16:13]{.aside}

οι δε ειπον οι μεν ιωαννην τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λεγει αυτοις υμεις δε τινα με λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σ[ιμ]{.greek-supplied}ων πετρος ειπε[ν]{.unclear} συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτω μακαριος ει σιμων βαριωνα οτι σαρξ και αιμα ουκ [απεκαλυψεν]{.greek-omitted} [απεκαλυψε]{.greek-added} σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις ουρανοις[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι αδου ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν τοις [ουρανοις]{.greek-abbr} και ο εαν λυσης επι της γης εσται λελυμενον εν τοις [ουρανοις]{.greek-abbr}[16:19]{.aside}

τοτε διεστειλατο τοις μαθηταις αυτου ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} δεικνυειν τοις μ[α]{.unclear}θηταις αυτου οτι δει αυτον απελθειν εις ιεροσολυμα και πολλα παθειν απο των πρεσβυτερων και αρχιερεων και γραμματεων και αποκτανθηναι και τη τριτη ημερα εγερθηναι[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω λεγων ιλεως σοι κυριε ου μη εσται σοι τουτο[16:22]{.aside}

ο δε στραφεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω πετρω υπαγε οπισω μου σατανα σκανδαλον [μου]{.greek-omitted} [μοι]{.greek-added} ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των ανθρωπων[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ει τις θελει οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον σταυρον αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[16:24]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την ψυχην αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι γαρ ωφελειται ανθρωπος εαν τον κοσμον ολον κερδηση την δε ψυχην αυτου ζημιωθη η τι δωσει ανθρωπος [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο [υιος]{.greek-abbr} του ανθρωπου ερχεσθαι εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων αυτου και τοτε αποδωσει εκαστω κατα την πραξιν αυτου[16:27]{.aside}

αμην λεγω υμιν [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες [των]{.greek-added} ωδε [εστωτες]{.greek-omitted} [εστηκοτων]{.greek-added} οιτινες ου μη γευσωνται θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τον [υιον]{.greek-abbr} του ανθρωπου ερχομενον εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και ιωαννην τον αδελφον αυτου και αναφερει αυτους εις ορος υψηλον κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και [ελαμψεν]{.greek-omitted} [ελαμψε]{.greek-added} το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} λευκα ως το φως[17:2]{.aside}

και ιδου ωφθησαν αυτοις [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

αποκριθεις δε ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω [ιησου]{.greek-abbr} κυριε καλον εστιν ημας ωδε ειναι ει θελεις ποιησωμεν ωδε τρεις σκηνας σοι μιαν και [μωση]{.greek-omitted} [μωυσει]{.greek-added} μιαν και [ηλια]{.greek-added} μιαν [ηλια]{.greek-omitted}[17:4]{.aside}

ετι αυτου λαλουντος ιδου νεφελη φωτεινη επεσκι[α]{.unclear}[σ]{.greek-supplied}[ε]{.unclear}ν αυτους και ι[δ]{.unclear}[ο]{.greek-supplied}υ φωνη εκ της νεφελης λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω ευδοκησα αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται επεσον επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν εγερθητε και μη φοβεισθε[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινοντων αυτων εκ του ορους ενετειλατο αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι ειπητε [τουτο]{.greek-added} το οραμα εως ου ο [υιος]{.greek-abbr} του ανθρωπου εκ νεκρων αναστη[17:9]{.aside}

και επηρωτησαν αυτον οι μαθηται αυτου λεγοντες τι [ο]{.greek-supplied}[υ]{.unclear}ν οι γραμματεις [λεγουσιν]{.greek-omitted} [οτι]{.greek-omitted} [ηλιαν]{.greek-omitted} [δει]{.greek-omitted} [ελθειν]{.greek-omitted} [πρωτον]{.greek-omitted}[17:10]{.aside}

[λεγω]{.greek-omitted} [δε]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [ηλιας]{.greek-omitted} [ηδη]{.greek-omitted} [ηλθεν]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [επεγνωσαν]{.greek-omitted} [αυτον]{.greek-omitted} [αλλα]{.greek-omitted} [εποιησαν]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted} [οσα]{.greek-omitted} [ηθελησαν]{.greek-omitted} [ουτως]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} του ανθρωπου μελλει πασχειν υπ αυτων[[17:12 *(lacunose)*]{.lacunose}]{.aside}

τοτε συνηκαν οι μαθηται οτι περι ιωαννου του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον προσηλθεν αυτω ανθρωπος γονυπετων αυτον[17:14]{.aside}

και λεγων [κυρι]{.greek-added} [κυριε]{.corr} ελεησον μου τον [υιον]{.greek-abbr} οτι σεληνιαζεται και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολ[λακις]{.greek-supplied} [εις]{.greek-omitted} [το]{.greek-omitted} [υδωρ]{.greek-omitted}[[17:15 *(lacunose)*]{.lacunose}]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε προσελθοντες οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην γαρ λεγω υμιν εαν εχητε πιστιν [ως]{.greek-omitted} [κοκκον]{.greek-omitted} [σιναπεως]{.greek-omitted} [ερειτε]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} [τουτω]{.greek-omitted} [μεταβηθι]{.greek-omitted} [εντευθεν]{.greek-omitted} [εκει]{.greek-omitted} [και]{.greek-omitted} [μεταβησεται]{.greek-omitted} [και]{.greek-omitted} [ουδεν]{.greek-omitted} [αδυνατησει]{.greek-omitted} [υμιν]{.greek-omitted}[17:20]{.aside}

[αναστρεφομενων]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [γαλιλαια]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} ο [ιησους]{.greek-abbr} μελλει ο [υιος]{.greek-abbr} του ανθρωπου παραδιδοσθαι εις χειρας ανθρωπων[[17:22 *(lacunose)*]{.lacunose}]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα εγερθησεται και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε αυτων εις καπερναουμ προσηλθον οι τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added} λαμβανοντες τω πετρω και ειπον ο διδασκαλος υμων ου τελει τα διδρα[χμα]{.greek-supplied}[17:24]{.aside}

[λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} αλλοτριων εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις [την]{.greek-omitted} θαλασσαν βαλε [αγκιστρον]{.greek-omitted} [αγγιστρον]{.greek-added} και τον αναβαινοντα πρωτον ιχθυν αρον και ανοιξας το στομα αυτου ευρησεις στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη [δε]{.greek-added} τη ωρα προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λ[ε]{.unclear}γοντες τις αρα μειζων εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη στραφητε και γενησθε ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο ουτος εστιν ο μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος εαν δεξηται παιδιον [τοιουτον]{.greek-omitted} [τοιουτο]{.greek-added} εν επι τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν [σκανδαλισει]{.greek-added} [σκανδαλιση]{.corr} ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος εις τον τραχηλον αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

ει δε η χειρ σου η ο πους σου σκανδαλιζει σε εκκοψον αυτα και βαλε απο σου καλον σοι εστιν εισελθειν εις την ζωην χωλον η κυλλον η δυο χειρας η δυο ποδας εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και ει ο οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εις την ζωην εισελθειν η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

ορατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} το προσωπον του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο [υιος]{.greek-abbr} του ανθρωπου [ζητησαι]{.greek-added} [και]{.greek-added} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει εαν γενηται τινι ανθρωπω εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα ενενηκοντα εννεα επι τα ορη πορευθεις ζητει το πλανωμενον[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η επι τοις ενενηκοντα εννεα τοις μη πεπλανημενοις[18:13]{.aside}

ουτως ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} θελημα εμπροσθεν του [πατρος]{.greek-abbr} υμων του εν [τοις]{.greek-added} ουρανοις ινα αποληται εις των μικρων τουτων[18:14]{.aside}

εαν δε αμαρτηση εις σε ο αδελφος σου υπαγε και ελεγξον αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη ακουση παραλαβε μετα [σου]{.greek-omitted} [σεαυτου]{.greek-added} ετι ενα [η]{.greek-omitted} [δυο]{.greek-omitted} [ινα]{.greek-omitted} [επι]{.greek-omitted} [στοματος]{.greek-omitted} [δυο]{.greek-omitted} [μαρτυρων]{.greek-omitted} [η]{.greek-omitted} [τριων]{.greek-omitted} [σταθη]{.greek-omitted} [παν]{.greek-omitted} [ρημα]{.greek-omitted}[18:16]{.aside}

