---
title: "Collation of Byz^RP^ vs 30709 (709)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 709 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30709).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 709                                   	| λογος                              	|
| 709 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 709 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 709               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 709                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 709 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 709                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

βιβλος [γενεσεως]{.greek-omitted} [γενεως]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου [δαυιδ]{.greek-abbr} υιου αβρααμ[1:1]{.aside}

αβρααμ [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ ισαακ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ια[κω]{.unclear}β ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιουδαν και τους αδελφους αυτου[1:2]{.aside}

ιουδας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον φαρες και τον ζαρα εκ της θαμαρ φαρες δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εσρωμ εσρωμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αραμ[1:3]{.aside}

αραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [αμιναδαβ]{.greek-omitted} [αμιναδαμ]{.greek-added} [αμιναδαβ]{.greek-omitted} [αμιναδαμ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ναασσων ναασσων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλμων[1:4]{.aside}

[σαλμων]{.greek-added} σαλμων δε [εγεννησεν]{.greek-omitted} [εγεννσε]{.greek-added} τον βοοζ εκ της ραχαβ βοοζ δε [εγεννησεν]{.greek-omitted} [εγενσε]{.greek-added} τον ωβηδ εκ της ρουθ ωβηδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεσσαι[1:5]{.aside}

ιεσσαι δε [εγεννησεν]{.greek-omitted} τον [δαυιδ]{.greek-abbr} τον βασιλεα [δαυιδ]{.greek-abbr} δε ο βασιλευς [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [σωλομωνα]{.greek-added} [σολομωνα]{.corr} εκ της του ουριου[1:6]{.aside}

σολομων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ασα]{.greek-omitted} [ασω]{.greek-added}[1:7]{.aside}

[ασα]{.greek-omitted} [ασω]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσαφατ ιωσαφατ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον οζιαν[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωαθαμ ιωαθαμ δε εγεννησεν τον αχαζ αχαζ δε εγεννησεν τον εζεκιαν[1:9]{.aside}

εζεκιας δε εγεννησεν τον μανασση μανασσης δε εγεννησεν τον αμων αμων δε εγεννησεν τον ιωσιαν[1:10]{.aside}

ιωσιας [δε]{.greek-added} [εγεννησεν]{.greek-added} [τον]{.greek-added} [ιωακειμ]{.greek-added} [ιωακειμ]{.greek-added} δε εγεννησεν τον ιεχονιαν και τους αδελφους αυτου επι της [μετοικεσιας]{.greek-omitted} [μετοικησιας]{.greek-added} βαβυλωνος[1:11]{.aside}

μετα δε τ[ην]{.unclear} [μετοικεσιαν]{.greek-omitted} [μετοικησιαν]{.greek-added} βαβυλωνος ιεχονια[ς]{.unclear} [ε]{.unclear}γεννησεν τον σαλαθιηλ σαλαθιηλ δε εγεννησεν τον [ζοροβαβελ]{.greek-omitted} [ζορομβαβελ]{.greek-added}[1:12]{.aside}

[ζοροβαβελ]{.greek-omitted} [ζορομβαβελ]{.greek-added} δε εγεννησεν τον αβιουδ αβιουδ δε εγεννησεν τον [ελιακειμ]{.greek-omitted} [ελιακιμ]{.greek-added} [ελιακειμ]{.greek-omitted} [ελιακιμ]{.greek-added} δε εγεννησεν τον αζωρ[1:13]{.aside}

αζωρ δε εγεννησεν τον σαδωκ σαδωκ δε εγεννησεν τον αχειμ αχειμ δε εγεννησεν τον ελιουδ[1:14]{.aside}

ελιουδ δε εγεννησεν τον ελεαζαρ ελεαζαρ δε εγεννησεν τον ματθαν ματθαν δε εγεννησεν τον ιακωβ[1:15]{.aside}

ιακωβ δε εγεννησεν τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομ[ε]{.greek-supplied}νος [χριστος]{.greek-abbr}[1:16]{.aside}

πασαι ουν αι [γεαι]{.greek-added} [γενεαι]{.corr} απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεαι δεκατεσσαρες και απο [δαυιδ]{.greek-abbr} εως της [μετοικεσιας]{.greek-omitted} [μετοικησιας]{.greek-added} βαβυλωνος γενεαι δεκατεσσαρες και απο της [μετοικεσιας]{.greek-omitted} [μετοικησιας]{.greek-added} βαβυλωνος εως του [χριστου]{.greek-abbr} γενεαι δεκατεσσαρες[1:17]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην μνηστευθεισης γαρ της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν η συνελθειν αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην παραδειγματισαι εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ εφανη αυτω λεγων ιωσηφ [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} μη φοβηθης παραλαβειν [μαριαμ]{.greek-omitted} [μαριαν]{.greek-added} την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

τ[εξεται]{.unclear} δε [υιον]{.greek-abbr} και καλεσεις το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται [υιον]{.greek-abbr} και καλεσουσιν το ονομα αυτου εμμανουηλ ο εστιν [μεθερμηνευομενον]{.greek-omitted} [μεθερμη]{.greek-added} [νευομενον]{.greek-added} μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε ο ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και παρελαβεν την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου ετεκεν τον [υιον]{.greek-abbr} αυτης τον πρωτοτοκον και εκαλεσεν το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

του δε [ιησου]{.greek-abbr} γεννηθεντος εν βηθλεεμ της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις [ιεροσολυμα]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added}[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων ειδομεν γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι αυτω[2:2]{.aside}

ακουσας δε ηρωδης ο βασιλευς εταραχθη και πα[σα]{.unclear} ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και γραμματεις του λαου επυνθανετο παρ αυτων που ο [χριστος]{.greek-abbr} γενναται[2:4]{.aside}

οι δε ειπον αυτω εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου[2:5]{.aside}

και συ β[ηθλε]{.unclear}εμ γη ιουδα ουδαμ[ως]{.unclear} ελαχιστη ει εν τοις ηγ[ε]{.unclear}μοσιν ιουδα εκ σο[υ]{.unclear} γαρ εξελευσεται [η]{.unclear}γουμενος οστις [ποιμανει]{.unclear} [τον]{.unclear} λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε [ηρ]{.unclear}ω[δη]{.unclear}ς λαθρα καλεσας τους μαγους ηκριβωσεν παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ ειπεν πορευθεντες ακριβως ε[ξ]{.unclear}ετ[α]{.unclear}σατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ ον ειδον εν τ[η]{.unclear} ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα εχαρησαν χαραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες εις την οικιαν ειδον το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσεκυνησαν αυτω και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδη[ν]{.unclear} δι [αλλ]{.unclear}ης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδου αγγελος [κυριου]{.greek-abbr} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε εγερθεις παρελαβεν το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον [υιον]{.greek-abbr} μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη λιαν και αποστειλας ανειλεν παντας τους παιδας τους εν βηθλεεμ και εν πασιν τοις οριοις αυτης απο διετους και κατωτερω κατα τον χρονον ον ηκρ[ι]{.unclear}βωσεν παρα των μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν υπο ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ ηθελεν παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ φαινετ[αι]{.unclear} τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} τεθνηκασιν γαρ οι [ζητουντες]{.greek-omitted} [ζητουν]{.greek-added} [τες]{.greek-added} την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις παρελαβεν το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει [επι]{.greek-omitted} της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν εις πολιν λεγομενην [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} οπως πληρωθη το ρηθεν δια των προφητων οτι ναζωραιος κληθησεται[2:23]{.aside}

### Chapter 3

εν [δε]{.greek-omitted} ταις ημεραις εκειναις παραγινεται ιωαννης ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

και λεγων μετανοειτε ηγγικεν γαρ η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

ουτος γαρ εστιν ο ρηθεις υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε ο ιωαννης ειχεν το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον ιεροσολυμα και πασα η [ο]{.greek-added} [ιουδαια]{.corr} και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο εν τω ιορδανη υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισμα αυτου ειπεν αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν εαυτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ [λεγω]{.greek-added} [γαρ]{.greek-added} [υμιν]{.greek-added}[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται [παν]{.corr} [ουν]{.corr} [δενδρον]{.corr} [μη]{.corr} [ποιουν]{.corr} [καρπον]{.corr} [καλον]{.corr} [εκκοπτεται]{.corr} [και]{.corr} [εις]{.corr} [πυρ]{.corr} [βαλλεται]{.corr}[3:10]{.aside}

εγω μεν βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον αυτου εις την αποθηκην το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον ιωαννην του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε ιωαννης διεκωλυεν αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν προς αυτον αφες αρτι ουτως γαρ πρεπον εστιν ημιν πληρωσαι πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και βαπτισθεις ο [ιησους]{.greek-abbr} ανεβη [[απο]{.unclear}]{.greek-added} ευθυς απο του υδατος και ιδου ανεωχθησαν αυτω οι [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} καταβαινον ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω ευδοκησα[3:17]{.aside}

### Chapter 4

τοτε ο [ιησους]{.greek-abbr} ανηχθη εις την ερημον υπο του πνευματος πειρασθηναι υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} [και]{.corr} [νυκτας]{.corr} [τεσσαρακοντα]{.greek-omitted} [[τεσσερακοντα]{.corr}]{.greek-added} υστερον επεινασεν[4:2]{.aside}

και προσελθων αυτω ο πειραζων ειπεν ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι γενωνται[4:3]{.aside}

ο δε αποκριθεις ειπεν γεγραπται ουκ επ αρτω μονω ζησεται [ο]{.greek-added} [ανθρωπος]{.greek-abbr} αλλ επι παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} βαλε σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων αρουσιν σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} παλιν γεγραπται ουκ εκπειρασεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν παραλαμβανει αυτον ο διαβολος εις ορος υψηλον λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω μονω λατρευσεις[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} οτι ιωαννης παρεδοθη ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και [νεφθαλειμ]{.greek-omitted} [νεφθαλιμ]{.greek-added}[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη [νεφθαλειμ]{.greek-omitted} [νεφθαλιμ]{.greek-added} οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} φως μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε ηγγικεν γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων [δε]{.corr} [[ο]{.corr}]{.greek-added} [[[ιησους]{.greek-abbr}]{.corr}]{.greek-added} παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} δυο αδελφους [σιμονα]{.greek-added} [σιμωνα]{.corr} τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω υμας αλιεις [ανθρωπων]{.greek-abbr}[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [αλλους]{.corr} δυο αδελφους ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας τα δικτυα αυτων και εκαλεσεν αυτους[4:21]{.aside}

οι δε ευθεως αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν [ολην]{.corr} την γαλιλαιαν ο [ιησους]{.greek-abbr} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και απηλθεν η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και βασανοις συνεχομενους και δαιμονιζομενους και σεληνιαζομενους και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και [δεκαπολεως]{.greek-omitted} [και]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [και]{.greek-omitted} [ιουδαιας]{.greek-omitted} [και]{.greek-omitted} περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον αυτω οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους λεγων[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν η βασιλεια των ουρανων[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθησονται[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι κληρ[ο]{.unclear}νομησουσιν την γην[5:5]{.aside}

μακαριοι οι πεινωντες και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

μακαριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι εστε οταν ονειδισωσιν υμας και διωξωσιν και ειπωσιν παν πονηρον ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις ουρανοις ουτως γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις [εστε]{.greek-omitted} [εσται]{.greek-added} το αλας της γης εαν δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε καιουσιν λυχνον και τιθεασιν αυτον υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει πασιν τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων εμπροσθεν των [ανθρωπων]{.greek-abbr} οπως ιδωσιν υμων τα καλα εργα και [δο]{.greek-added} [δοξασωσιν]{.greek-omitted} [ξασωσιν]{.greek-added} τον [πατερα]{.greek-abbr} υμων τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι [[τον]{.corr}]{.greek-added} [[νομον]{.corr}]{.greek-added} αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η μια κεραια ου μη παρελθη απο του νομου εως αν παντα γενηται[5:18]{.aside}

ος εαν ουν λυση μιαν των εντολων [[μου]{.corr}]{.greek-added} τουτων των ελαχιστων και διδαξη ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν ποιηση και διδαξη ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση [υμων]{.greek-added} η δικαιοσυνη [υμων]{.greek-omitted} πλειον των γραμματεων και φαρισαιων ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν φονευση ενοχος εσται τη κρισει[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν ειπη τω αδελφω αυτου ρακα ενοχος εσται τω συνεδριω ος δ αν ειπη μωρε ενοχος εσται εις την γεενναν του πυρος[5:22]{.aside}

εαν ουν προσφερης το δωρον σου επι το θυσιαστηριον και εκει μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην [βλ[υ]{.unclear}θηση]{.greek-added} [βληθηση]{.corr}[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως αν αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη [[τοις]{.corr}]{.greek-added} [[αρχαιοις]{.corr}]{.greek-added} ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα προς το επιθυμησαι αυτην ηδη εμοιχευσεν αυτην [εν]{.corr} [τη]{.corr} καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιος σκανδαλιζει σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ σκανδαλιζει σε εκκοψον αυτην και βαλε απο [σ]{.unclear}ου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη δε οτι ος αν απολυση την γυναικα αυτου δοτω αυτη αποστασιον[5:31]{.aside}

ε[γ]{.unclear}ω δε λεγω υμιν οτι ος αν απολυση την γυναικα αυτου παρεκτος λογου πορνειας ποιει αυτην μοιχασθαι και ος εαν απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε τω [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη ομοσαι ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος εστιν του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον εστιν των ποδων αυτου μητε εις ιεροσολυμα οτι πολις [εστιν]{.greek-omitted} [εστη]{.greek-added} του μεγαλου βασιλεως[5:35]{.aside}

μητε ε[ν]{.unclear} τη κεφαλη σου ομοσης οτι ου δυνασαι μιαν τριχα λευκην η μελαιναν ποιησαι[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου εστιν[5:37]{.aside}

[ακουσατε]{.greek-added} [ηκουσατε]{.corr} οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω [αλλ]{.unclear} [οστις]{.unclear} [σ]{.unclear}ε ραπισει [επι]{.greek-omitted} [την]{.greek-omitted} [δεξιαν]{.greek-omitted} [σιαγονα]{.greek-omitted} [στρεψον]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [αλλην]{.greek-omitted}[5:39]{.aside}

### Chapter 20

[ομοια]{.greek-omitted} [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [ανθρωπω]{.greek-omitted} [οικοδεσποτη]{.greek-omitted} [κοδεσποτη]{.greek-added} οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

και συμφωνησας μετα των εργατων εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθ[ων]{.unclear} [περι]{.unclear} τριτην ωραν [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

και εκεινοις ειπεν υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν εξελθων περι εκτην [και]{.corr} [ε[νατην]{.unclear}]{.corr} ωραν εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο λεγει α[υ]{.unclear}τοις υπαγετε και υμ[εις]{.unclear} εις τον αμπελωνα και ο εαν η δικαιον ληψεσθε[20:7]{.aside}

οψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι πλειονα ληψονται και ελαβον και αυτοι ανα δηναριον[20:10]{.aside}

λαβοντες δε [εγογγυζον]{.greek-omitted} [εγογγυσαν]{.greek-added} κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι ουτοι οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις βαστασασιν το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων εταιρε ουκ αδικω σε ουχι δηναριου συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω εσχατω δουναι ως και σοι[20:14]{.aside}

η ουκ εξεστιν μοι ποιησαι ο θελω εν τοις εμοις ει ο οφθαλμος σου πονηρος εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι και οι πρωτοι εσχατοι πολλοι γαρ εισιν κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

και αναβαινων ο [ιησους]{.greek-abbr} εις ιεροσολυμα παρελαβεν τους δωδεκα μαθητας κατ ιδιαν εν τη οδω και ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις αρχιερευσιν και γραμματευσιν και κατακρινουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} θανατω[20:18]{.aside}

και παραδωσουσιν αυτον τοις εθνεσιν εις το εμπαιξαι και μαστιγωσαι και σταυρωσαι και τη τριτη ημερα αναστησεται[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε ειπεν [αυτ[ω]{.unclear}]{.greek-added} [αυτη]{.corr} τι θελεις λεγει αυτω ειπε ινα καθισωσιν ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω μελλω πινειν η το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε το δε καθισαι εκ δεξιων μου και εξ ευωνυμων μου ουκ εστιν εμον δουναι αλλ οις ητοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως [δε]{.greek-omitted} εσται εν υμιν αλλ ος εαν θελη εν υμιν μεγας γενεσθαι εσται [υμων]{.greek-omitted} [υμιν]{.greek-added} διακονος[20:26]{.aside}

και ος εαν θελη εν υμιν ειναι πρωτος εστω υμων δουλος[20:27]{.aside}

ωσπερ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και εκπορευομενων αυτων απο ιεριχω ηκολουθησεν αυτω οχλος πολυς[20:29]{.aside}

και ιδου δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [[υιε]{.greek-abbr}]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

ο δε οχλος επετιμησεν αυτοις ινα σιωπησωσιν οι δε μειζον [[μειζω]{.corr}]{.greek-added} εκραζον λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [[υιε]{.greek-abbr}]{.greek-added} [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-abbr} εφωνησεν αυτους και ειπεν τι θελετε ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-abbr} ινα ανοιχθωσιν ημων οι οφθαλμοι[20:33]{.aside}

σπλαγχνισθεις δε ο [ιησους]{.greek-abbr} ηψατο των οφθαλμων αυτων και ευθεως ανεβλεψαν αυτων οι οφθαλμοι και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε ηγγισαν [εις]{.greek-added} [ιε]{.greek-added} [[ιε]{.corr}]{.greek-added} [ροσολυμα]{.greek-added} [ει]{.greek-supplied}ς [ιεροσολυμα]{.corr} και ηλθον εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} προς το ορος των ελαιων τοτε ο [ιησους]{.greek-abbr} απεστειλεν δυο μαθητας[21:1]{.aside}

λεγων αυτοις πορευθητε εις την κωμην την απεναντι υμων και ευθεως ευρησετε ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο [κυριος]{.greek-abbr} αυτων χρειαν εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου [λεγοντος]{.greek-omitted} [λεγοντες]{.greek-added}[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον και πωλον [υιον]{.greek-abbr} υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες καθως προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και τον πωλον και επεθηκαν επανω αυτων τα ιματια αυτων και επεκαθισεν επανω αυτων[21:7]{.aside}

ο δε πλειστος οχλος εστρωσαν εαυτων τα ιματια εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι [ακολουθουντες]{.greek-omitted} [ακολουθουν]{.greek-added} [τες]{.greek-added} εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} της γαλιλαιας[21:11]{.aside}

και εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον του [θεου]{.greek-abbr} και εξεβαλεν παντας τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων κατεστρεψεν και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο οικος μου οικος προσευχης κληθησεται υμεις δε αυτον εποιησατε σπηλαιον ληστων[21:13]{.aside}

και προσηλθον αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α εποιησεν και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και [ει]{.greek-added} [ειπον]{.greek-omitted} [πον]{.greek-added} αυτω ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων κατηρτισω αινον[21:16]{.aside}

και καταλιπων αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη εκει[21:17]{.aside}

πρωιας δε επαναγων [[ο]{.corr}]{.greek-added} [[[ιησους]{.greek-abbr}]{.corr}]{.greek-added} εις την πολιν επεινασεν[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει μη φυλλα μονον και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη παραχρημα η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν εχητε πιστιν και μη διακριθητε ου μονον το της συκης ποιησετε αλλα καν τω ορει τουτω ειπητε αρθητι και βληθητι εις την θαλασσαν γενησεται[21:21]{.aside}

και παντα οσα εαν αιτησητε εν τη προσευχη πιστευοντες ληψεσθε[21:22]{.aside}

και ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις σοι εδωκεν την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω υμας καγω λογον ενα ον εαν ειπητε μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα ιωαννου ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο παρ εαυτοις λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει ημιν δια τι ουν ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ εχουσιν τον ιωαννην ως προφητην[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} ειπον ουκ οιδαμεν εφη αυτοις και αυτος ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} [[τις]{.corr}]{.greek-added} ειχεν τεκνα δυο και προσελθων τω πρωτω ειπεν τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε μεταμεληθεις απηλθεν[21:29]{.aside}

και προσελθων τω [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν ωσαυτως ο δε αποκριθεις ειπεν εγω κυριε και ουκ απηλθεν[21:30]{.aside}

τις εκ των δυο εποιησεν το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

ηλθεν γαρ προς υμας ιωαννης εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω οι δε τελωναι και αι πορναι επιστευσαν αυτω υμεις δε ιδοντες ου μετεμεληθητε υστερον του πιστευσαι αυτω[21:32]{.aside}

αλλην παραβολην ακουσατε [ανθρωπος]{.greek-abbr} [τις]{.corr} ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω περιεθηκεν και ωρυξεν εν αυτω ληνον και ωκοδομησεν πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε ηγγισεν ο καιρος των καρπων απεστειλεν τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε [ελιβολησαν]{.greek-added} [ελιθοβολησαν]{.corr}[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε απεστειλεν προς αυτους τον [υιον]{.greek-abbr} αυτου λεγων [[ισος]{.corr}]{.greek-added} εντραπησονται τον [υιον]{.greek-abbr} μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον [υιον]{.greek-abbr} ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο κυριος του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα εκδωσεται αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις καιροις αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε ανεγνωτε εν ταις γραφαις λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται [εθνει]{.greek-omitted} [εθνη]{.greek-added} ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση λικμησει αυτον[21:44]{.aside}

και ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους επειδη ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} παλιν ειπεν αυτοις εν παραβολαις λεγων[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις εποιησεν γαμους τω υιω αυτου[22:2]{.aside}

και απεστειλεν τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα σιτιστα τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος ωργισθη και πεμψας τα στρατευματα αυτου απωλεσεν τους φονεις εκεινους και την πολιν αυτων ενεπρησεν[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι [εις]{.greek-omitted} [τας]{.greek-omitted} [οδους]{.greek-omitted} συνηγαγον παντας οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν [[ιδεν]{.corr}]{.greek-added} [εκει]{.corr} [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου [και]{.greek-added} [λεγει]{.greek-added} [αυτ]{.greek-added} ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου ποδας και χειρας αρατε αυτον και [εκβαλετε]{.greek-omitted} [εμβαλετε]{.greek-added} εις το σκοτος το [εξωτερον]{.greek-omitted} [εξοτερον]{.greek-added} εκει εσται ο κλαυθμος [και]{.corr} [ο]{.corr} [βρυγμος]{.corr} των οδοντων[22:13]{.aside}

πολλοι γαρ εισιν κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον ελαβον [[κατα]{.corr}]{.greek-added} [[του]{.corr}]{.greek-added} [[[ιησου]{.greek-abbr}]{.corr}]{.greek-added} οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετ[α]{.unclear} των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι αληθης ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει εξεστιν δουναι [κηνσον]{.greek-omitted} [κινσον]{.greek-added} καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων ειπεν τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του [κηνσου]{.greek-omitted} [κινσου]{.greek-added} οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγ[ε]{.unclear}ι αυτοις αποδοτε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι [οι]{.corr} λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης ειπεν εαν τις αποθανη μη εχων τεκνα επιγαμβρευσει ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος γαμησας ετελευτησεν και μη εχων σπερμα αφηκεν την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων απεθανεν και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε εκγαμιζονται αλλ ως αγγελοι του [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} εισιν[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι εφιμωσεν τους [σαδδουκαιους]{.greek-omitted} [σαδδουκαι]{.greek-added} [ους]{.greek-added} συνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη [[τη]{.corr}]{.greek-added} καρδια σου και εν ολη [καρδια]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [εν]{.greek-added} [ολη]{.greek-added} [[τη]{.corr}]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη εστιν πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως σεαυτον[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος [υιος]{.greek-abbr} εστιν λεγουσιν αυτω [του]{.greek-omitted} [τω]{.greek-added} [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου [υποποδιον]{.greek-omitted} [υποκατω]{.greek-added} των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} καλει αυτον [κυριον]{.greek-abbr} πως [υιος]{.greek-abbr} αυτου εστιν[22:45]{.aside}

και ουδεις εδυνατο αυτω αποκριθηναι λογον [ουδε]{.greek-omitted} [ου]{.greek-added} [δε]{.greek-added} ετολμησεν τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} ελαλησεν [[ο]{.corr}]{.greek-added} [[[ιησους]{.greek-abbr}]{.corr}]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας εκαθισαν οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και [ποιητε]{.greek-added} [ποιειτε]{.corr} κατα δε τα εργα αυτων μη ποιειτε λεγουσιν γαρ και ου ποιουσιν[23:3]{.aside}

δεσμευουσιν γαρ φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου θελουσιν κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων ποιουσιν προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} πλατυνουσιν δε τα φυλακτηρια αυτων και μεγαλυνουσιν τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

φιλουσιν τε την πρωτοκλισιαν εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι ραββι[23:7]{.aside}

υμεις δε μη κληθητε ραββι εις γαρ εστιν υμων ο καθηγητης ο [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε υμων επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις ουρανοις[23:9]{.aside}

μηδε κληθητε καθηγηται εις γαρ [υμων]{.corr} εστιν ο καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων εσται υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χηρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι περιαγετε την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν [ποι]{.greek-added} γενηται ποιειτε αυτον [υιον]{.greek-abbr} [γεενης]{.greek-added} [γεεννης]{.corr} διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν ομοση εν τω ναω ουδεν εστιν ος δ αν ομοση εν τω χρυσω του ναου οφειλει[23:16]{.aside}

[μωροι]{.corr} [και]{.corr} [τυφλοι]{.corr} [τις]{.corr} [γαρ]{.corr} [μειζων]{.corr} [εστιν]{.corr} [ο]{.corr} [χρυσος]{.corr} [η]{.corr} [ο]{.corr} [ναος]{.corr} [ο]{.corr} [αγιαζων]{.corr} [τον]{.corr} [χρυσον]{.corr}[23:17]{.aside}

[και]{.corr} [ος]{.corr} [εαν]{.corr} [ομοση]{.greek-omitted} [[ωμοσει]{.corr}]{.greek-added} [εν]{.corr} [τω]{.corr} [θυσιαστηριω]{.corr} [ουδεν]{.corr} [εστιν]{.corr} [ος]{.corr} [δ]{.corr} [αν]{.corr} [ομοση]{.greek-omitted} [[ωμοσει]{.corr}]{.greek-added} [εν]{.corr} [τω]{.corr} [δωρω]{.corr} [τω]{.corr} [επανω]{.corr} [αυτου]{.corr} [οφειλει]{.corr} [[και]{.corr}]{.greek-added} [[ος]{.corr}]{.greek-added} [[εαν]{.corr}]{.greek-added} [[ομοσει]{.corr}]{.greek-added} [[εν]{.corr}]{.greek-added} [[τω]{.corr}]{.greek-added} [[θυσιαστηριω]{.corr}]{.greek-added} [[ουδεν]{.corr}]{.greek-added} [[εστιν]{.corr}]{.greek-added} [[ος]{.corr}]{.greek-added} [[δ]{.corr}]{.greek-added} [[αν]{.corr}]{.greek-added} [[ομοσει]{.corr}]{.greek-added} [[εν]{.corr}]{.greek-added} [[τω]{.corr}]{.greek-added} [[δωρω]{.corr}]{.greek-added} [[τω]{.corr}]{.greek-added} [[επανω]{.corr}]{.greek-added} [[αυτου]{.corr}]{.greek-added} [[οφειλει]{.corr}]{.greek-added}[23:18]{.aside}

μωροι και τυφλοι τι γαρ μειζον [[μειζων]{.corr}]{.greek-added} το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω ομνυει εν αυτω και εν πασιν τοις επανω αυτου[23:20]{.aside}

και ο ομοσας εν τω ναω ομνυει εν αυτω και εν τω κατοικησαντι αυτον[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω [αυτου]{.greek-omitted} [αυτω]{.greek-added}[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το κυμινον και αφηκατε τα βαρυτερα του νομου την κρισιν και [τον]{.greek-omitted} [το]{.greek-added} ελεον και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι καθαριζετε το εξωθεν του ποτηριου και της παροψιδος [[του]{.corr}]{.greek-added} [[πινακος]{.corr}]{.greek-added} εσωθεν δε γεμουσιν εξ αρπαγης και αδικιας [[ακρασιας]{.corr}]{.greek-added}[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι παρομοιαζετε ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις εξωθεν μεν φαινεσθε τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι εστε υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι οικοδομειτε τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει [ημεν]{.greek-omitted} [ημεθα]{.greek-added} εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν [ημεν]{.greek-omitted} [ημεθα]{.greek-added} κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και σταυρωσετε και εξ αυτων μαστιγωσετε εν ταις συναγωγαις υμων και διωξετε απο πολεως εις πολιν[23:34]{.aside}

οπως ελθη εφ υμας παν αιμα δικαιον εκχυνομενον επι της γης απο του αιματος [αβελ]{.corr} [του]{.corr} [δικαιου]{.corr} [εως]{.corr} [του]{.corr} [αιματος]{.corr} ζαχαριου [υιου]{.greek-abbr} βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει παντα ταυτα επι την γενεαν ταυτη[ν]{.unclear}[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεινασα]{.greek-added} τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον τροπον επισυναγει ορνις τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν [[οτι]{.corr}]{.greek-added} ου μη με ιδητε απ αρτι εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτο[υ]{.unclear} επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου βλεπετε παντα ταυτα αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους πλανησουσιν[24:5]{.aside}

μελλησετε δε ακουειν [π[ω]{.unclear}λεμους]{.greek-added} [πολεμους]{.corr} και ακοας πολεμων ορατε μη θροεισθε δει γαρ παντα [[ταυτα]{.corr}]{.greek-added} γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εστι]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και λοιμοι και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη ωδινων[24:8]{.aside}

τοτε παραδωσουσιν υμας εις θλιψιν και αποκτενουσιν υμας και εσεσθε μισουμενοι υπο παντων των εθνων δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους παραδωσουσιν και μισησουσιν αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και πλανησουσιν πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται τουτο το ευαγγελιον της βασιλειας εν ολη τη οικουμενη εις μαρτυριον πασιν τοις εθνεσιν και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν ιδητε το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου [εστως]{.greek-omitted} [εστος]{.greek-added} εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν επι τα ορη[24:16]{.aside}

[[και]{.corr}]{.greek-added} ο επι του δωματος μη καταβαινετω αραι τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος μηδε σαββατω[24:20]{.aside}

εσται γαρ τοτε θλιψις μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν ουδ ου μη γενηται[24:21]{.aside}

και ει μη [εκολοβωθησαν]{.greek-omitted} [εκολοβωθη]{.greek-added} [σαν]{.greek-added} αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και δωσουσιν σημεια μεγαλα και τερατα ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω εστιν μη εξελθητε ιδου εν τοις [ταμειοις]{.greek-omitted} [ταμιειοις]{.greek-added} μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται [και]{.corr} η παρουσια του [υιου]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ εαν η το πτωμα εκει συναχθησονται οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του [υιου]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε κοψονται πασαι αι φυλαι της γης και οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και αποστελει τους αγγελους αυτου μετα σαλπιγγος [[και]{.corr}]{.greek-added} φωνης μεγαλης και επισυναξουσιν τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων ουρανων εως ακρων αυτων[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος αυτης γενηται απαλος και τα φυλλα εκφυη γινωσκετε οτι εγγυς το θερος[24:32]{.aside}

ουτως και υμεις οταν ιδητε [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted} γινωσκετε οτι εγγυς εστιν επι θυραις[24:33]{.aside}

αμην λεγω υμιν ου μη παρελθη η γενεα αυτη εως αν παντα [ταυτα]{.corr} γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσονται οι δε λογοι μου ου μη παρελθωσιν[24:35]{.aside}

περι δε της ημερας εκεινης και [[της]{.corr}]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} [ουδε]{.greek-added} [ο]{.greek-added} [[υιος]{.greek-abbr}]{.greek-added} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του [υιου]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις προ του [κατακλυσμου]{.greek-omitted} [κατακλυσ]{.greek-added} [μου]{.greek-added} τρωγοντες και πινοντες γαμουντες και εκγαμιζοντες αχρι ης ημερας εισηλθεν νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του [υιου]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο αληθουσαι εν τω [αγρ]{.greek-added} [μυλω]{.greek-added} [μυλωνι]{.corr} μια παραλαμβανεται και μια αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει ηδει ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν ειασεν διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο [υιος]{.greek-abbr} του ανθρωπου ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της [οικετιας]{.greek-added} θεραπειας αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο κυριος αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι πασιν τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο κυριος μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [εσθιειν]{.greek-omitted} [[αυτου]{.corr}]{.greek-added} [εσθιη]{.greek-added} δε και [πινειν]{.greek-omitted} [πινη]{.greek-added} μετα των μεθυοντων[24:49]{.aside}

ηξει ο κυριος του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου [και]{.greek-added} [της]{.greek-added} [νυμφης]{.greek-added}[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε ημιν εκ του ελαιου υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε [ουκ]{.greek-omitted} [ου]{.greek-added} [μη]{.greek-added} αρκεση ημιν και υμιν πορευεσθε δε μαλλον προς τους πωλουντας και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν εν η ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων εκαλεσεν τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν εδωκεν πεντε ταλαντα ω δε δυο ω δε εν [εκαστω]{.greek-omitted} [εκα]{.greek-added} [στω]{.greek-added} κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο εκερδησεν και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και απεκρυψεν το [αργυον]{.greek-added} [αργυριον]{.corr} του κυριου αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο κυριος των δουλων εκεινων και συναιρει μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη δε αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του κυριου σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων ειπεν κυριε δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο κυριος αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την [χα]{.greek-added} [χαραν]{.greek-omitted} [ραν]{.greek-added} του κυριου σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως ειπεν κυριε εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και [οκνηρε]{.greek-omitted} [οκ[ρ]{.unclear}ηρε]{.greek-added} ηδεις οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον εκβαλετε εις το σκοτος το [εξωτερον]{.greek-omitted} [εξοτερον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων [[ταυτα]{.corr}]{.greek-added} [[λεγων]{.corr}]{.greek-added} [[εφωνει]{.corr}]{.greek-added} [[ο]{.corr}]{.greek-added} [[εχων]{.corr}]{.greek-added} [[ωτα]{.corr}]{.greek-added} [[ακουειν]{.corr}]{.greek-added} [[ακουετω]{.corr}]{.greek-added}[25:30]{.aside}

οταν δε ελθη ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε [καθισει]{.greek-omitted} [καθησει]{.greek-added} επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} [εμπροσθεν]{.greek-omitted} [εμπρο]{.greek-added} [σθεν]{.greek-added} αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν [β]{.unclear}ασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με ξενος ημ[η]{.unclear}ν και συνηγαγετε με[25:35]{.aside}

[γυμνος]{.corr} [και]{.corr} [περιεβαλετε]{.corr} [με]{.corr} ησθενησα και επεσκεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και συνηγαγομεν η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου των [ελα]{.greek-added} [ελαχιστων]{.greek-omitted} [χιστων]{.greek-added} εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους ειπεν τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις το σταυρωθηναι[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω κρατησωσιν και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι [τοις]{.greek-added} πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους παρεχετε τη γυναικι εργον γαρ καλον ειργασατο εις εμε[26:10]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το [ενταφιασε]{.greek-added} [ενταφιασαι]{.corr} με εποιησεν[26:12]{.aside}

αμην λεγω υμιν [[οτι]{.corr}]{.greek-added} οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

ειπεν τι θελετε μοι δουναι [καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα [αργιρια]{.greek-added} [αργυρια]{.corr}[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που θελεις [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς εστιν προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα [μαθητων]{.greek-added} [αυτου]{.greek-added}[26:20]{.aside}

και εσθιοντων αυτων ειπεν αμην λεγω υμιν [οτι]{.greek-omitted} εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν αυτω εκαστος αυτων μητι εγω ειμι κυριε[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω τρυβλιω την χειρα ουτος με παραδωσει[26:23]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον ειπεν μητι εγω ειμι ραββι λεγει αυτω συ ειπας[26:25]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας εκλασεν και εδιδου τοις μαθηταις [[αυτου]{.corr}]{.greek-added} και ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ εστιν το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω [δε]{.greek-omitted} [γαρ]{.greek-added} υμιν οτι ου μη πιω απ αρτι εκ τουτου του [γεννηματος]{.greek-omitted} [γενηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν αυτο πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις [σκανδα]{.greek-added} [σκανδαλισθησεσθε]{.greek-omitted} [λισθησεσθε]{.greek-added} εν εμοι εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει [και]{.greek-added} παντες σκανδαλισθησονται εν σοι εγω δε ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε απαρνησωμαι ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον [γεθσημανη]{.greek-omitted} [γεθσημανι]{.greek-added} και λεγει τοις μαθηταις [αυτου]{.greek-added} καθισατε αυτου εως ου απελθων προσευξωμαι εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων [μι]{.greek-added} [μικρον]{.greek-omitted} [κρον]{.greek-added} επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον εστιν παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και [αναστας]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [προσευχης]{.greek-added} ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω [αυτοις]{.greek-added} ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται τουτο το ποτηριον παρελθειν απ εμου εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων ευρισκει αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας [αυτου]{.greek-omitted} και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν [[εντευθεν]{.corr}]{.greek-added} ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα ηλθεν και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον [αν]{.greek-omitted} [εαν]{.greek-added} φιλησω αυτος εστιν κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} ειπεν χαιρε ραββι και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ [ω]{.greek-omitted} [ο]{.greek-added} παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} εκτεινας την χειρα απεσπασεν την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον [σου]{.greek-omitted} την μαχαιραν εις τον τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν μαχαιρα αποθανουνται[26:52]{.aside}

η [δοκεις]{.greek-omitted} [δοκει]{.greek-added} [σοι]{.greek-added} οτι ου δυναμαι αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος ηκολουθει αυτω απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και το συνεδριον ολον εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως θανατωσωσιν αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [[τινες]{.corr}]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} [του]{.greek-added} [ζωντος]{.greek-added}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς διερρηξεν τα ιματια αυτου λεγων οτι εβλασφημησεν τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου εστιν[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και εκολαφισαν αυτον οι δε [ερραπισαν]{.greek-omitted} [εραπισαν]{.greek-added}[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε [ηρνησατο]{.greek-omitted} [ηρνη]{.greek-added} [σατο]{.greek-added} εμπροσθεν αυτων παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτον αλλη και λεγει αυτοις εκει και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ εφωνησεν[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος [του]{.greek-omitted} [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω εκλαυσεν πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν αυτον ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε ιδων ιουδας ο παραδιδους αυτον οτι κατεκριθη μεταμεληθεις απεστρεψεν τα τριακοντα αργυρια τοις αρχιερευσιν και τοις πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα [α]{.greek-added} [αθωον]{.greek-omitted} [θωον]{.greek-added} οι δε ειπον τι προς ημας συ [οψει]{.greek-omitted} [οψη]{.greek-added}[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω ανεχωρησεν και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ εξεστιν βαλειν αυτα εις τον [κορβαναν]{.greek-omitted} [κορβοναν]{.greek-added} επει τιμη αιματος εστιν[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα συνεταξεν μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και των πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου καταμαρτυρουσιν[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος απεστειλεν προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν αυτω παντες σταυρωθητω[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες σταυρωθητω[27:23]{.aside}

ιδων δε ο πιλατος οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος ειπεν το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φραγελλωσας παρεδωκεν ινα σταυρωθη[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και γονυπετησαντες εμπροσθεν αυτου ενεπαιζον αυτω λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το σταυρωσαι[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα ο εστιν [λεγομενος]{.greek-omitted} [λεγομενον]{.greek-added} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ ηθελεν πιειν[27:34]{.aside}

σταυρωσαντες δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και [θημενοι]{.greek-added} [καθημενοι]{.corr} ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-abbr} [ο]{.corr} [[ναζωραιος]{.corr}]{.greek-added} [ο]{.greek-added} βασιλευς των ιουδαιων[27:37]{.aside}

τοτε σταυρουνται συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} κατα[βη]{.unclear}θι απο του σταυρου[27:40]{.aside}

ομοιως δε και οι αρχιερεις εμπαιζοντες μετα των γραμματεων και πρεσβυτερων και φαρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου [δυναται]{.greek-omitted} [δυνα]{.greek-added} [ται]{.greek-added} σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} εστιν καταβατω νυν απο του [σταυρου]{.greek-abbr} και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω νυν αυτον ει θελει αυτον ειπεν γαρ οτι [θεου]{.greek-abbr} ειμι [υιος]{.greek-abbr}[27:43]{.aside}

το δ αυτο και οι λησται οι συσταυρωθεντες αυτω ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας ενατης[27:45]{.aside}

περι δε την ενατην ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι [λιμα]{.greek-omitted} [λειμα]{.greek-added} σαβαχθανι τουτ εστιν θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελιπες[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες ελεγον οτι ηλιαν φωνει ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας σωσων [[σωσαι]{.corr}]{.greek-added} αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη αφηκεν το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη εσεισθη και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια [ανεωχθησ]{.greek-added} [ανεωχθησαν]{.corr} και πολλα [σωματα]{.greek-omitted} [σωμα]{.greek-added} [τα]{.greek-added} των κεκοιμημενων αγιων ηγερθη[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν [πολ[―]{.gap}ν]{.greek-added} [πολιν]{.corr} και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} [υιος]{.greek-abbr} ην ουτος[27:54]{.aside}

ησαν δε εκει γυναικες πολλαι απο μακροθεν θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η μαγδαληνη και μαρια η του ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο [αριμαθαιας]{.greek-omitted} [αριμαθιας]{.greek-added} τουνομα ιωσηφ ος και αυτος εμαθητευσεν τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ ενετυλιξεν αυτο σινδονι καθαρα[27:59]{.aside}

και εθηκεν αυτο εν τω καινω αυτου [μνημειω]{.greek-omitted} [μνημνειω]{.greek-added} ο ελατομησεν εν τη πετρα και προσκυλισας λιθον μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η μαγδαληνη [και]{.corr} [η]{.corr} [αλλη]{.corr} [μαρια]{.corr} καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις εστιν μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς πιλατον[27:62]{.aside}

λεγοντες κυριε εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου [νυκτος]{.greek-omitted} κλεψωσιν αυτον και ειπωσιν τω λαω ηγερθη απο των νεκρων και εσται η εσχατη πλανη χειρων της πρωτης[27:64]{.aside}

εφη δε αυτοις ο πιλατος εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε δε σαββατων τη επιφωσκουση εις μιαν σαββατων ηλθεν μαρια η μαγδαληνη και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας [εξ]{.greek-omitted} [ε]{.greek-added} [ξ]{.greek-added} [ουρανου]{.greek-abbr} [και]{.greek-added} προσελθων απεκυλισεν τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος ειπεν ταις γυναιξιν μη φοβεισθε υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} [ζητειτε]{.greek-added} τον εσταυρωμενον ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως ειπεν δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ πορευθεισαι ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

ως δε επορευοντο απαγγειλαι τοις μαθηταις αυτου και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} απηντησεν αυταις λεγων [χαιρεται]{.greek-added} [χαιρετε]{.corr} αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε [απαγγειλατε]{.greek-omitted} [απαγγει]{.greek-added} [λατε]{.greek-added} τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

λεγοντες ειπατε οτι οι μαθηται αυτου νυκτος ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις πεισομεν αυτον και υμας αμεριμνους ποιησ[ο]{.unclear}μ[ε]{.unclear}ν[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και διεφημισθη ο λογος [ουτος]{.corr} παρα ιουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις [[παρρησια]{.corr}]{.greek-added} λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του [υιου]{.greek-abbr} και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους [τη]{.greek-added} [τηρειν]{.greek-omitted} [ρειν]{.greek-added} παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

