---
title: "Collation of Byz^RP^ vs 30716 (716)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 716 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30716).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 716                                   	| λογος                              	|
| 716 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 716 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 716               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 716                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 716 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 716                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε [ο]{.greek-omitted} ιωαννης ενδεδυμενος τριχας [καμηλου]{.greek-omitted} [καμιλου]{.greek-added} και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος βαλλοντας αμφιβληστρον [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσαν]{.greek-added} ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως [εκαλεσεν]{.greek-omitted} [εκελευσεν]{.greek-added} αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν [ελθων]{.greek-added} [εισελθων]{.corr} εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσι[―]{.gap}αν [[εξουσιαν]{.corr}]{.greek-added} εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαρινε]{.greek-added} [ηλθες]{.greek-omitted} [ηλθε]{.greek-added} απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης [εξελθοντες]{.greek-omitted} [εξελθων]{.greek-added} [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο [πυρεσσουσα]{.greek-omitted} [πυρεσουσα]{.greek-added} και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και [διηκονει]{.greek-omitted} [διηκονη]{.greek-added} αυτοις[1:31]{.aside}

οψιας δε [γενομενης]{.greek-omitted} [γενομενοις]{.greek-added} οτε εδυ ο ηλιος εφερον [προς]{.greek-omitted} [αυτον]{.greek-omitted} παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την [θυραν]{.greek-omitted} [θυρα]{.greek-added}[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον[1:34]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και κατεδιωξαν [α]{.unclear}υτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} προς αυτον λεπρος παρακαλων αυτον και γονυπετων [αυτον]{.greek-omitted} [αυτων]{.greek-added} και λεγων αυτω οτι εαν θελης δυνασαι με [καθαρισαι]{.greek-omitted} [καθαρησαι]{.greek-added}[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [σπλαγχνισθεις]{.greek-omitted} [σπλαχνισθεις]{.greek-added} εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε [σεαυτον]{.greek-omitted} [σεαυτω]{.greek-added} δειξον τω ιερει και προσενεγκε περι [αυτου]{.greek-added} του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [πανταχωθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και εισηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την [θυραν]{.greek-omitted} [θυρα]{.greek-added} και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και [εξορυξαντες]{.greek-omitted} [εξωρυξαντες]{.greek-added} [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον αφεωνται σοι αι [αμαρτιαι]{.greek-omitted} [αμαρτιαις]{.greek-added} σου[2:5]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} [ουτω]{.greek-added} λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους [ο]{.greek-omitted} [ιησους]{.greek-omitted} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτοις]{.greek-omitted} τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον σου τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ιδητε]{.greek-added} οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον [κραββατον]{.greek-omitted} [κραβατον]{.greek-added} εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως ειδομεν[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ειδεν λευι τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων [εσθιει]{.greek-omitted} [εσθιη]{.greek-added} και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων εστιν νηστευειν οσον χρονον [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} εχουσιν τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευουσιν]{.greek-added} εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω ει δε [μη]{.greek-omitted} [μηγε]{.greek-added} αιρει το πληρωμα [απ]{.greek-added} αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος [ο]{.greek-omitted} [νεος]{.greek-omitted} [τους]{.greek-omitted} [ασκους]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον εις ασκους [καινους]{.greek-omitted} [κενους]{.greek-added} βλητεον[2:22]{.aside}

και [εγενετο]{.greek-omitted} [εγενοντο]{.greek-added} [παραπορευεσθαι]{.greek-omitted} [παραπορευομενοι]{.greek-added} αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω [ιδε]{.greek-omitted} [ιδετε]{.greek-added} τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και εδωκεν και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορρωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου υγιης ως η αλλη[3:5]{.aside}

και [εξελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι [τυρον]{.greek-omitted} [τυρων]{.greek-added} και σιδωνα πληθος [πολυ]{.greek-omitted} [πολλοι]{.greek-added} ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου αψωνται οσοι ειχον μαστιγας[3:10]{.aside}

και τα πνευματα τα ακαθαρτα οταν αυτον εθεωρει προσεπιπτεν αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω [σιμωνι]{.greek-omitted} [σιμονι]{.greek-added} ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον του ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν [ισκαριωτην]{.greek-omitted} [ισκαριοτην]{.greek-added} ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

και [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} [και]{.greek-added} [συνερχεται]{.greek-omitted} [συνερχονται]{.greek-added} παλιν [οχλος]{.greek-omitted} [οχλοι]{.greek-added} ωστε μη δυνασθαι αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι [βεελζεβουλ]{.greek-omitted} [βεελζεβουηλ]{.greek-added} εχει [και]{.greek-omitted} [οτι]{.greek-omitted} εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια [η]{.greek-added} [γουν]{.greek-added} [φιλος]{.greek-added} [δαιμονιων]{.greek-added} [και]{.greek-added} [μαγος]{.greek-added}[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ [εαυτην]{.greek-omitted} [εαυτη]{.greek-added} μερισθη ου δυναται σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται [ου]{.greek-omitted} [δυναται]{.greek-omitted} [σταθηναι]{.greek-omitted} [αλλα]{.greek-omitted} [τελος]{.greek-omitted} [εχει]{.greek-omitted}[3:26]{.aside}

[ουδεις]{.greek-omitted} [ου]{.greek-added} δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον [δηση]{.greek-omitted} [δυση]{.greek-added} και τοτε την οικιαν αυτου διαρπαση[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημησει]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο οχλος περι αυτον ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και [οι]{.greek-added} αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις [το]{.greek-omitted} πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} [και]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [ιδωσι]{.greek-added} [και]{.greek-added} [ακουοντες]{.greek-added} [ακουσωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και [αιρει]{.greek-omitted} [ερει]{.greek-added} τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι [τα]{.greek-omitted} [τω]{.greek-added} πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα [γενομενης]{.greek-omitted} [γενομενοις]{.greek-added} θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [εχει]{.greek-added} [αν]{.greek-omitted} [εχη]{.greek-omitted} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η β[α]{.unclear}σιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και [καθευδη]{.greek-omitted} [καθευδει]{.greek-added} και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος βλαστανη και μηκυνηται ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα [πληρη]{.greek-omitted} [πληρης]{.greek-added} σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει [το]{.greek-omitted} [τον]{.greek-added} δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι [ομοιωσωμεν]{.greek-omitted} [ομοιοσωμεν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} [βαλωμεν]{.greek-added} αυτην[4:30]{.aside}

ως [κοκκον]{.greek-omitted} [κοκκω]{.greek-added} [σιναπεως]{.greek-omitted} [συναπεως]{.greek-added} ος οταν σπαρη επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις [πολλαις]{.greek-omitted} ελαλει αυτοις τον λογον καθως εδυναντο ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις [αυτου]{.greek-omitted} [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λελαψ]{.greek-added} ανεμου μεγαλη τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε [αυτο]{.greek-omitted} [αυτον]{.greek-added} [ηδη]{.greek-omitted} [ηδει]{.greek-added} γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλη]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις εδυνατο αυτον [δησαι]{.greek-omitted} [λυσαι]{.greek-added}[5:3]{.aside}

δια το αυτον πολλακις [πεδαις]{.greek-omitted} [παιδες]{.greek-added} και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} [δεδεσθαι]{.greek-omitted} [δεσθαι]{.greek-added} και διεσπασθαι υπ αυτου τας αλυσεις και τας [πεδας]{.greek-omitted} [παιδας]{.greek-added} συντετριφθαι και ουδεις [ισχυεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις μνημασιν [ην]{.greek-omitted} [υν]{.greek-added} κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν εδραμεν και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το πνευμα το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι ονομα και απεκριθη λεγων λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει προς [τω]{.greek-omitted} [το]{.greek-added} ορει αγελη χοιρων [μεγαλη]{.greek-omitted} βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι [δαιμονες]{.greek-omitted} [δαιμοναις]{.greek-added} λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα πνευματα τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως [δισχιλιοι]{.greek-omitted} [χιλιοι]{.greek-added} και επνιγοντο εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και ανηγγειλαν εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το [γεγονος]{.greek-omitted} [γεγονως]{.greek-added}[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και θεωρουσιν τον δαιμονιζομενον καθημενον και ιματισμενον και σωφρονουντα τον [εσχηκοτα]{.greek-omitted} [εσχικοτα]{.greek-added} τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο [τω]{.greek-omitted} δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ [αφηκεν]{.greek-omitted} [αφικεν]{.greek-added} αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον [πιπτει]{.greek-omitted} [πιστει]{.greek-added} προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} [επ]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν [ρυσει]{.greek-omitted} [ρυση]{.greek-added} αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι καν των ιματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον [συνθλιβοντα]{.greek-omitted} [συνθλιβοντας]{.greek-added} σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν [αυτη]{.greek-omitted} [θαρση]{.greek-added} θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και [ισθι]{.greek-omitted} [ισθη]{.greek-added} υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} [ακουσας]{.greek-added} ευθεως [ακουσας]{.greek-omitted} τον λογον [λαλουμενον]{.greek-omitted} [καλουμενον]{.greek-added} λεγει τω αρχισυναγωγω [μη]{.greek-omitted} [φοβου]{.greek-omitted} [μονον]{.greek-omitted} [πιστευε]{.greek-omitted}[5:36]{.aside}

[μη]{.greek-added} [φοβου]{.greek-added} [μονον]{.greek-added} [πιστευε]{.greek-added} και ουκ αφηκεν ουδενα [αυτω]{.greek-omitted} [αυτων]{.greek-added} συνακολουθησαι ει μη πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} εις τον οικον του αρχισυναγωγου και θεωρει θορυβον κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και [κλαιετε]{.greek-omitted} [κλεετε]{.greek-added} το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και [κατεγελων]{.greek-omitted} [καταγελλων]{.greek-added} αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη [ταλιθα]{.greek-omitted} [ταβηθα]{.greek-added} [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο [αυτοις]{.greek-omitted} [αυτης]{.greek-added} πολλα ινα μηδεις γνω τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτα και τις η σοφια η δοθεισα αυτω [ινα]{.greek-added} και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο τεκτων ο υιος μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν [αυτω]{.greek-omitted} [εαυτω]{.greek-added}[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγενευσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει [μη]{.greek-omitted} [μι]{.greek-added} ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και περιηγεν τας κωμας κυκλω [διδασκων]{.greek-omitted} [διδασκειν]{.greek-added}[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μονον μη [πηραν]{.greek-omitted} [πειραν]{.greek-added} μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη ενδυσησθε δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν [εισελθητε]{.greek-omitted} [εισελθη]{.greek-added} εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι αν μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον χουν [τον]{.greek-omitted} [των]{.greek-added} υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η γομορροις εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και εξελθοντες [οι]{.greek-added} [μαθηται]{.greek-added} εκηρυσσον ινα μετανοησωσιν[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους [αρρωστους]{.greek-omitted} [αρωστους]{.greek-added} και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο ενεργουσιν αι δυναμεις εν αυτω[6:14]{.aside}

[αλλοι]{.greek-omitted} [ελεγον]{.greek-omitted} [οτι]{.greek-omitted} [ηλιας]{.greek-omitted} [εστιν]{.greek-omitted} αλλοι δε ελεγον οτι προφητης εστιν [η]{.greek-added} ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} ιωαννην ουτος εστιν αυτος ηγερθη εκ [των]{.greek-added} νεκρων[6:16]{.aside}

αυτος γαρ [ο]{.greek-omitted} ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον ιωαννην και [εδησεν]{.greek-omitted} [εθηκεν]{.greek-added} αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο ιωαννης τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν [την]{.corr} γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητω]{.greek-added} τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα [εποιει]{.greek-omitted} [εποιη]{.greek-added} και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης [τοις]{.greek-omitted} [γενεσιοις]{.greek-omitted} [της]{.greek-added} [γενομενης]{.greek-added} αυτου δειπνον [εποιει]{.greek-omitted} [εποιη]{.greek-added} τοις μεγιστασιν αυτου και τοις χιλιαρχοις και [τοις]{.greek-omitted} [της]{.greek-added} πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν [αιτησεις]{.greek-added} με [αιτησης]{.greek-omitted} δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι [αιτησομαι]{.greek-omitted} [αιτισομαι]{.greek-added} η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα [ητησατο]{.greek-omitted} [ητισατο]{.greek-added} λεγουσα θελω ινα [μοι]{.greek-omitted} [μη]{.greek-added} δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-abbr} του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς [σπεκουλατορα]{.greek-omitted} [σπεκουλατωρα]{.greek-added} επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν [αυτου]{.greek-added} την κεφαλην [αυτου]{.greek-omitted} επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το [πτωμα]{.greek-omitted} [σωμα]{.greek-added} αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν [αυτω]{.greek-omitted} [αυτου]{.greek-added} παντα [και]{.greek-omitted} [οσα]{.greek-added} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγ[ε]{.unclear}ιν ευκαιρουν[6:31]{.aside}

και [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} αυτους και συνηλθον προς [αυτον]{.greek-omitted} [αυτους]{.greek-added}[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ειδεν]{.greek-added} πολυν οχλον και [εσπλαγχνισθη]{.greek-omitted} [εσπλαχνισθη]{.greek-added} επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης [γενομενης]{.greek-omitted} [γενομενομενης]{.greek-added} προσελθοντες αυτω οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας [αγορασωσιν]{.greek-omitted} [αγωρασωσιν]{.greek-added} εαυτοις αρτους τι [γαρ]{.greek-omitted} φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν δηναριων διακοσιων αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και γνοντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν [αυτοις]{.greek-omitted} [αυτου]{.greek-added} [ανακλιναι]{.greek-omitted} [ανακληθηναι]{.greek-added} παντας συμποσια συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παρατιθωσιν]{.greek-added} αυτοις και τους δυο ιχθυας [εμερισ[α]{.unclear}]{.greek-added} [εμερισεν]{.greek-omitted} [[μερισε]{.corr}]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους [πληρεις]{.greek-omitted} [πληρης]{.greek-added} και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους [αρ]{.greek-added} [αρτους]{.greek-omitted} [τους]{.greek-added} πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες [αυτον]{.greek-omitted} [αυτοις]{.greek-added} περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις [θαρσειτε]{.greek-omitted} [θαρσιτε]{.greek-added} εγω ειμι μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [περισου]{.greek-added} [εκπερισσου]{.greek-omitted} [[περισσου]{.corr}]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ αυτων η καρδια πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην [ηρξαντο]{.greek-omitted} [ηρξατο]{.greek-added} επι τοις [κραββατοις]{.greek-omitted} [κραμβατοις]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η [πολεις]{.greek-omitted} [πολις]{.greek-added} η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου [αυτου]{.greek-omitted} αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας [αρτους]{.greek-omitted} [εμεμψαντο]{.greek-omitted} [επεμψατο]{.greek-added}[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη [νιψωνται]{.greek-omitted} [νιψονται]{.greek-added} τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη [βαπτισωνται]{.greek-omitted} [βαπτιζονται]{.greek-added} ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και [ξεστων]{.greek-omitted} [εξεστων]{.greek-added} [και]{.greek-omitted} χαλκιων και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων [αλλα]{.greek-omitted} [αλλ]{.greek-added} ανιπτοις χερσιν εσθιουσιν [τον]{.greek-omitted} [αρτον]{.greek-omitted} [αρτων]{.greek-added}[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι [υμων]{.greek-omitted} [ημων]{.greek-added} των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} [κρατειτε]{.greek-omitted} [ινα]{.greek-added} την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} [η]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε [οτι]{.greek-added} εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} [αυτου]{.greek-added} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωσει]{.greek-added} υμων η παρεδωκατε και παρομοια [πολλα]{.greek-added} τοιαυτα [πολλα]{.greek-omitted} ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν [εξωθεν]{.greek-omitted} [εξω]{.greek-added} του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα [εκπορευομενα]{.greek-omitted} [εισπορευομενα]{.greek-added} απ αυτου εκεινα εστιν τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον [αφεδρωνα]{.greek-omitted} [αφαιδρωνα]{.greek-added} εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζονται]{.greek-added} παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο [κοινοι]{.greek-omitted} [κοινει]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι [φονοι]{.greek-omitted} [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος ασελγεια οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ [η]{.greek-added} γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς [τους]{.greek-added} τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη [ελληνις]{.greek-omitted} [ελυνις]{.greek-added} [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των [ψιχιων]{.greek-omitted} [ψυχιων]{.greek-added} των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την θαλασσαν της γαλιλαιας ανα [μεσον]{.greek-omitted} [μεσων]{.greek-added} των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον [μογγιλαλον]{.greek-omitted} [μογγιλαλων]{.greek-added} και παρακαλουσιν αυτον ινα επιθη [επ]{.greek-added} αυτω την χειρα[7:32]{.aside}

και [απολαβομενος]{.greek-omitted} [επιλαβομενος]{.greek-added} αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο [αυτοις]{.greek-omitted} [αυτης]{.greek-added} ινα μηδενι ειπωσιν οσον δε [αυτος]{.greek-omitted} αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους [ποιει]{.greek-omitted} [ποιειν]{.greek-added} ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παμπολλου]{.greek-omitted} [παμπολου]{.greek-added} οχλου [οντος]{.greek-omitted} [οντως]{.greek-added} και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος ο [ιησους]{.greek-abbr} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

[σπλαγχνιζομαι]{.greek-omitted} [σπλαχνιζομαι]{.greek-added} επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις οικον [αυτων]{.greek-omitted} [αυτον]{.greek-added} εκλυθησονται εν τη οδω τινες γαρ [αυτων]{.greek-omitted} [αυτον]{.greek-added} μακροθεν [ηκουσιν]{.greek-omitted} [ηκουσι]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε χορτασαι αρτων επ [ερημιας]{.greek-omitted} [ερημιαις]{.greek-added}[8:4]{.aside}

και επηρωτα αυτους ποσους [αρτους]{.greek-added} εχετε [αρτους]{.greek-omitted} οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και [ταυτα]{.greek-added} ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και ευθεως εμβας εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα [αρτον]{.greek-omitted} [αρτων]{.greek-added} ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε [συνιετε]{.greek-omitted} [συνιεται]{.greek-added} ετι [πεπωρωμενην]{.greek-omitted} [πεπυρωμενην]{.greek-added} εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου [βλεπετε]{.greek-omitted} [βλεπωσι]{.greek-added} και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

[οτε]{.greek-omitted} [οτι]{.greek-added} τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους [κοφινους]{.greek-omitted} [κωφινους]{.greek-added} [πληρεις]{.greek-omitted} [πληρης]{.greek-added} κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων [σπυ]{.greek-added} [σπυριδων]{.greek-omitted} [ριδων]{.greek-added} πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως ου [συνιετε]{.greek-omitted} [συνιεται]{.greek-added}[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα αυτον [ει]{.greek-omitted} [η]{.greek-added} τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψαι]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας [της]{.greek-omitted} [τοις]{.greek-added} φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγουσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και των αρχιερεων και των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο [επιτιμαν]{.greek-omitted} [επιτιαν]{.greek-added} αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου [ακολουθειν]{.greek-omitted} [ελθειν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[8:34]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι [απολεσει]{.greek-omitted} [απολεση]{.greek-added} αυτην [ο]{.greek-supplied}ς δ αν απολεση την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} εαν [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} [[ανθρωπος]{.greek-abbr}]{.greek-added} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ εαν επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου [μετα]{.greek-omitted} [με]{.greek-added} των αγγελων των αγιων [αυτου]{.greek-added}[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε [εστηκοτων]{.greek-omitted} [εστηκωτων]{.greek-added} οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ [παραλαμ[―]{.gap}νει]{.greek-added} [παραλαμβανει]{.corr} ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου [εγενοντο]{.greek-omitted} [εγενοντα]{.greek-added} στιλβοντα λευκα [ωσει]{.greek-added} [λιαν]{.greek-omitted} [ως]{.greek-omitted} χιων οια γναφευς επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν [ημας]{.greek-omitted} [υμας]{.greek-added} ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και μωση μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη [επισκιαζουσα]{.greek-omitted} [επισκι]{.greek-added} [αζουσα]{.greek-added} αυτοις και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα [μηδενι]{.greek-omitted} [μηδεν]{.greek-added} [διηγησωνται]{.greek-omitted} [διηγησονται]{.greek-added} α ειδον ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι [και]{.greek-omitted} ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν [εν]{.greek-added} αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας [ο]{.greek-omitted} οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα πνευμα αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη [ρησσει]{.greek-omitted} [ρισσει]{.greek-added} αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων [φερετε]{.greek-omitted} [φερεται]{.greek-added} αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και [ιδων]{.greek-omitted} [ειδων]{.greek-added} αυτον ευθεως το πνευμα εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [βοηθη]{.greek-added} μου τη [απιστια]{.greek-omitted} [απιστεια]{.greek-added}[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το πνευμα το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν [δια]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} [αμαρτωλων]{.greek-added} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

[οι]{.greek-omitted} [η]{.greek-added} δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους [διελογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added}[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ [διελεχθησαν]{.greek-omitted} [διηλεχθησαν]{.greek-added} εν τη οδω τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων [παιδιων]{.greek-omitted} [παιδιον]{.greek-added} δεξηται επι τω ονοματι μου εμε δεχεται και ος [εαν]{.greek-omitted} εμε δεξηται [ο]{.greek-supplied}υκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε αυτω ιωαννης λεγων διδασκαλε ειδομεν τινα [επι]{.greek-added} τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καθ υμων υπερ υμων εστιν[9:40]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [ποτιση]{.greek-omitted} [ποτησει]{.greek-added} υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου [σβεννυται]{.greek-omitted} [σβεννηται]{.greek-added}[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} σοι εισελθειν εις την ζωην χωλον η τους [δυο]{.greek-omitted} ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι εστιν μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ [αρτος]{.greek-added} πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο [αρτυσετε]{.greek-omitted} [αρτυσητε]{.greek-added} εχετε εν εαυτοις αλας και [ειρηνευετε]{.greek-omitted} [ειρηνευεται]{.greek-added} εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας δια του περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [επετρεψεν]{.greek-omitted} [επετρεψαι]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν [υμιν]{.greek-omitted} [ημιν]{.greek-added} [την]{.corr} εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [του]{.greek-omitted} αυτου επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην [γαρ]{.greek-added} λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα ευλογει αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον [κληρονομησω]{.greek-omitted} [κληρομησω]{.greek-added}[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτω]{.greek-omitted} διδασκαλε ταυτα παντα [εφυ]{.greek-added} [εφυλαξαμην]{.greek-omitted} [λαξαμην]{.greek-added} εκ νεοτητος μου [τι]{.greek-added} [υστερω]{.greek-added}[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελης]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν σοι υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι αρας τον [σταυρον]{.greek-omitted} [στρον]{.greek-added}[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} [τρυμαλιας]{.greek-omitted} [τριμαλιας]{.greek-added} [της]{.greek-omitted} ραφιδος [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο ο πετρος [λεγειν]{.greek-omitted} [λεγει]{.greek-added} αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [μητερας]{.greek-abbr} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην [προαγων]{.greek-omitted} [προαγον]{.greek-added} αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} θανατω και παραδωσουσιν [αυτω]{.greek-added} [αυτον]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted}[10:33]{.aside}

[και]{.greek-omitted} [εμπαιξουσιν]{.greek-omitted} [αυτω]{.greek-omitted} και μαστιγωσουσιν αυτον και εμπτυσουσιν αυτω και αποκτενουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν αιτησωμεν [ποιησης]{.greek-omitted} [ποιησεις]{.greek-added} [ημιν]{.greek-omitted} [υμιν]{.greek-added}[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι [με]{.greek-omitted} υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε [πιειν]{.greek-omitted} [ποιειν]{.greek-added} το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθηναι]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added}[10:38]{.aside}

[οι]{.greek-omitted} [ο]{.greek-added} δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθηναι]{.greek-added}[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριευσουσιν]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη υμων [γενεσθαι]{.greek-omitted} [γενεσθω]{.greek-added} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και φωνουσιν τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} λεγει αυτω [ο]{.greek-omitted} [ιησους]{.greek-omitted} τι [σοι]{.greek-added} θελεις ποιησω [σοι]{.greek-omitted} ο δε τυφλος ειπεν αυτω ραββουνι ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις ιερουσαλημ εις βηθσφαγη και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην [την]{.greek-omitted} κατεναντι υμων και ευθεως εισπορευομενοι [εις]{.corr} αυτην [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} πωλον δεδεμενον εφ ον [ουπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθικε]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις [υμιν]{.greek-omitted} [ημιν]{.greek-added} ειπη τι ποιειτε τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του [αμφοδου]{.greek-omitted} [μφοδου]{.greek-added} και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων [και]{.greek-omitted} [εκαθισεν]{.greek-omitted} [επ]{.greek-omitted} [αυτω]{.greek-omitted}[11:7]{.aside}

[πολλοι]{.greek-omitted} [δε]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτων]{.greek-omitted} εστρωσαν [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added} αλλοι δε στοιβαδας εκοπτον εκ των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην [μιαν]{.greek-added} μακροθεν [εχουσαν]{.greek-omitted} [εχουσα]{.greek-added} φυλλα ηλθεν [ει]{.greek-omitted} [εις]{.greek-added} αρα ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} και τας καθεδρας των [πωλουντων]{.greek-omitted} [πολουντων]{.greek-added} τας [περιστερας]{.greek-omitted} [περιστερρας]{.greek-added} [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις [ου]{.greek-omitted} γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη [διδαχη]{.greek-omitted} [δαχη]{.greek-added} αυτου[11:18]{.aside}

και [οτε]{.greek-omitted} [οταν]{.greek-added} οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω εξηρανται[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι [ος]{.greek-omitted} [οστις]{.greek-added} [αν]{.greek-omitted} [εαν]{.greek-added} ειπη τω [ορει]{.greek-omitted} [ορη]{.greek-added} τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα πιστευση οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθε]{.greek-added} πιστευετε οτι λαμβανετε και εσται [εν]{.greek-added} υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι [αφιετε]{.greek-omitted} [αφιεται]{.greek-added} ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων [λεγω]{.greek-added} [δε]{.greek-added} [υμιν]{.greek-added} [αιτειτε]{.greek-added} [και]{.greek-added} [δωθησεται]{.greek-added} [υμιν]{.greek-added} [κρουετε]{.greek-added} [και]{.greek-added} [ανοιγησεται]{.greek-added} [υμιν]{.greek-added} [πας]{.greek-added} [γαρ]{.greek-added} [ο]{.greek-added} [αιτων]{.greek-added} [λαμβανει]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [ζητων]{.greek-added} [ευρισκη]{.greek-added} [και]{.greek-added} [το]{.greek-added} [κρουοντι]{.greek-added} [ανοιγησεται]{.greek-added}[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-omitted} αποκριθεις ειπεν αυτοις επερωτησω [καγω]{.greek-added} υμας [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-omitted} [[ανων]{.greek-abbr}]{.greek-added} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν [ειπωμεν]{.greek-omitted} [ειπω]{.greek-added} [μεν]{.greek-added} εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον απαντες γαρ ειχον τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες λεγουσιν τω [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους [δουλον]{.greek-added} τω καιρω [δουλον]{.greek-omitted} ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

[και]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} λαβοντες αυτον εδειραν και απεστειλαν [κενον]{.greek-omitted} [καινον]{.greek-added}[12:3]{.aside}

και παλιν απεστειλεν προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους αλλους [τους]{.greek-omitted} [ους]{.greek-added} μεν [δεροντες]{.greek-omitted} [δαιροντες]{.greek-added} [τους]{.greek-omitted} [ους]{.greek-added} δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα [υιον]{.greek-abbr} εχων αγαπητον [αυτου]{.greek-omitted} [εαυτου]{.greek-added} [απε]{.greek-added} [απεστειλεν]{.greek-omitted} [στειλε]{.greek-added} και αυτον [εσχατον]{.greek-added} προς αυτους [εσχατον]{.greek-omitted} λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [θεασαμενον]{.greek-added} [αυτον]{.greek-added} [ερχομενον]{.greek-added} [προς]{.greek-added} [αυτους]{.greek-added} ειπον [προς]{.greek-omitted} [εαυτους]{.greek-omitted} οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες [απεκτειναν]{.greek-added} αυτον [απεκτειναν]{.greek-omitted} και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους [τουτους]{.greek-added} και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην [γωνιας]{.greek-omitted} [γονιας]{.greek-added}[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου [μελει]{.greek-omitted} [μελη]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [δουναι]{.greek-added} κηνσον καισαρι [δουναι]{.greek-omitted} η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} [υποκριται]{.greek-added} φερετε μοι [δηναριον]{.greek-omitted} [δυναριον]{.greek-added} ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε [ουν]{.greek-added} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν [αναστασιν]{.greek-omitted} μη ειναι [αναστασιν]{.greek-added} και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος [ωσαυτως]{.greek-omitted} [οσαυτως]{.greek-added}[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ [αφηκαν]{.greek-omitted} [αφηκεν]{.greek-added} σπερμα εσχατη παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη [ουν]{.greek-added} αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν [γαρ]{.greek-omitted} εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [γαμιζονται]{.greek-added} αλλ εισιν ως αγγελοι οι εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-abbr} ζωντων υμεις ουν [πολυ]{.greek-omitted} [πολλοι]{.greek-added} πλανασθε[12:27]{.aside}

και προσελθων εις των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ακουσας αυτων συζητουντων ειδως οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη παντων εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω οτι πρωτη παντων των εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ [ο]{.greek-added} [ολης]{.greek-omitted} [λης]{.greek-added} της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας [ειπας]{.greek-omitted} [ειπες]{.greek-added} οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις [ουκετι]{.greek-omitted} [αυτον]{.greek-added} ετολμα [αυτον]{.greek-omitted} επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη [πλειον]{.greek-omitted} [πλειω]{.greek-added} παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των βαλλοντων εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας [οικοδομας]{.greek-omitted} [οικομας]{.greek-added} ου μη αφεθη λιθος επι λιθω ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις [ηρξατο]{.greek-added} [λαλειν]{.greek-added} αυτοις [ηρξατο]{.greek-omitted} [λεγειν]{.greek-omitted} βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και [ε]{.greek-added} [επι]{.greek-omitted} [πι]{.greek-added} ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε αγαγωσιν υμας παραδιδοντες μη προμεριμνατε τι λαλησητε μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου [ουδεις]{.greek-added} [ου]{.greek-omitted} [δει]{.greek-omitted} ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη [υμων]{.greek-omitted} [ημων]{.greek-added} χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι [θλιψις]{.greek-omitted} [θλιψεις]{.greek-added} οια ου γεγονεν τοιαυτη απ αρχης κτισεως ης [εκτισεν]{.greek-omitted} [εκτησεν]{.greek-added} ο [θεος]{.greek-abbr} εως του νυν και ου μη [γενηται]{.greek-omitted} [γενητε]{.greek-added}[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη πιστευετε[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} [εως]{.greek-added} [ακρων]{.greek-added} γης [εως]{.greek-omitted} [ακρου]{.greek-omitted} [ουρανου]{.greek-omitted}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης ηδη ο κλαδος απαλος γενηται και εκφυη τα φυλλα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν ταυτα ιδητε γινομενα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν [οτι]{.greek-omitted} ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[13:31]{.aside}

περι [δε]{.greek-omitted} [ε]{.greek-added} της ημερας [και]{.greek-added} [εκεινης]{.greek-omitted} [η]{.greek-omitted} ωρας ουδεις οιδεν ουδε οι αγγελοι [τον]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανον]{.greek-abbr}]{.greek-added} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

[ως]{.greek-omitted} [ω]{.greek-added} [ανθρωπος]{.greek-abbr} αποδημος αφεις την [οικιαν]{.greek-omitted} [οιοιαν]{.greek-added} αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν ουκ [οιδατε]{.greek-omitted} [οιατε]{.greek-added} γαρ ποτε ο κυριος της οικιας ερχεται οψε η μεσονυκτιου η [αλεκτοροφωνιας]{.greek-omitted} [αλεκτο]{.greek-added} [ροφωνιας]{.greek-added} η πρωι[13:35]{.aside}

μη ελθων [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον [εν]{.greek-omitted} [ετα]{.greek-added} δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και [οντος]{.greek-omitted} [οντως]{.greek-added} αυτου εν βηθανια εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα [το]{.greek-omitted} [τον]{.greek-added} αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο πραθηναι επανω τριακοσιων δηναριων [και]{.greek-omitted} δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και [ο]{.greek-added} [οταν]{.greek-omitted} [ταν]{.greek-added} θελητε δυνασθε αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου [το]{.greek-omitted} [ο]{.greek-added} σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και ο ιουδας ο [ισκαριωτης]{.greek-omitted} [ισκαριωης]{.greek-added} εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλαντο]{.greek-omitted} [επηγγειλαντω]{.greek-added} αυτω [αργυριον]{.greek-omitted} [αργυριω]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και [τη]{.greek-omitted} [η]{.greek-added} πρωτη [ημερα]{.greek-omitted} των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα [φαγης]{.greek-omitted} [φαγεις]{.greek-added} το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν [δειξει]{.greek-omitted} [δειξη]{.greek-added} [ανωγεον]{.greek-omitted} [ανογεον]{.greek-added} μεγα εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων [κ]{.greek-supplied}αι εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω και αλλος [μ]{.greek-supplied}ητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις [ε]{.greek-supplied}κ των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου [ο]{.greek-supplied}υαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιον[τ]{.greek-supplied}ων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν [λ]{.greek-supplied}αβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα [μου]{.greek-omitted}[14:22]{.aside}

[κ]{.greek-supplied}αι λαβων το ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της [καινης]{.greek-omitted} [κενης]{.greek-added} διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οτι ουκετι ου μη [πιω]{.greek-omitted} [ποιω]{.greek-added} εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαν[τ]{.greek-supplied}ες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθη[σ]{.greek-supplied}εσθαι]{.greek-added} [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω τον ποιμενα και [διασκορπισθησε]{.greek-added} [διασκορπισθησεται]{.corr} τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πε[τ]{.greek-supplied}ρος εφη αυτω και ει παντες [σκανδαλισθησονται]{.greek-omitted} [σκανδαλισθησεται]{.greek-added} αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον [ε]{.greek-supplied}ν τη νυκτι ταυτη πριν η δις αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε [εκπερισσου]{.greek-omitted} [εκπερισου]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν με δεη συναποθανειν σοι ου μη σε απαρνησωμαι ωσαυτως [δε]{.greek-omitted} και παντες ελεγον[14:31]{.aside}

και [ε]{.greek-supplied}ρχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου [κ]{.greek-supplied}αθισατε ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και [π]{.greek-supplied}αραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο [εκθαμβεισθαι]{.greek-omitted} [[ε]{.greek-supplied}κθαμβησθαι]{.greek-added} και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επε[σ]{.greek-supplied}εν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι [παρε[―]{.gap}νεγκε]{.greek-added} [παρενεγκε]{.corr} το ποτηριον απ εμου τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και [ε]{.greek-supplied}ρχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελ[θ]{.greek-supplied}ων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

[κ]{.greek-supplied}αι υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ [ηδεισαν]{.greek-omitted} [ηδησαν]{.greek-added} τι αυτω [αποκριθωσιν]{.greek-omitted} [αποκριθωσι]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου πα[ρ]{.greek-supplied}αδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν [ι]{.greek-supplied}δου ο παραδιδους με [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added}[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει [δ]{.greek-supplied}ε ο παραδιδους αυτον συσσημον [αυτοις]{.greek-omitted} [αυτον]{.greek-added} λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατη[σ]{.greek-supplied}ατε αυτον και [απαγαγετε]{.greek-omitted} [υπαγεται]{.greek-added} ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας [αυτων]{.greek-omitted} [και]{.greek-omitted} [εκρατησαν]{.greek-omitted} αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπα[σ]{.greek-supplied}αμενος την μαχαιραν [επαισεν]{.greek-omitted} [επεσε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως [ε]{.greek-supplied}πι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς [υμας]{.greek-omitted} [ημας]{.greek-added} εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παν[τ]{.greek-supplied}ες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν [αυ]{.greek-added} [αυτον]{.greek-omitted} [[τ]{.greek-supplied}ον]{.greek-added} οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και α[π]{.greek-supplied}ηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και [ο]{.greek-omitted} πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι [δ]{.greek-supplied}ε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} [μαρτυριαν]{.greek-omitted} [ψευδομαρτυριαν]{.greek-added} εις το θανατωσαι αυτον και ουχ [ευρισκον]{.greek-omitted} [ευρισκων]{.greek-added}[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι [αι]{.greek-omitted} μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} [ο]{.greek-omitted} [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιε[ρ]{.greek-supplied}ευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν φαινεται οι δε [π]{.greek-supplied}αντες κατεκριναν αυτον [ειναι]{.greek-omitted} ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον και οι υπηρεται ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [ελαβον]{.greek-added}[14:65]{.aside}

και [οντος]{.greek-omitted} [οντως]{.greek-added} του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του [α]{.greek-supplied}ρχιερεως[14:66]{.aside}

και ιδουσα [τον]{.greek-omitted} [των]{.greek-added} πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε [επισταμαι]{.greek-omitted} [επισταμε]{.greek-added} τι συ λεγεις και [εξηλθεν]{.greek-omitted} [εξηλθον]{.greek-added} εξω εις το προαυ[λ]{.greek-supplied}ιον και αλεκτωρ εφωνησεν[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ [γαλιλαιος]{.greek-omitted} [λαλιαιος]{.greek-added} ει και η λαλια σου [ομοιαζει]{.greek-omitted} [ομοιαζη]{.greek-added}[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ εφωνησεν και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις απαρνηση με [τρις]{.greek-omitted} [τρεις]{.greek-added} και [επιβαλων]{.greek-omitted} [επιλαβων]{.greek-added} εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} [απηνεγκαν]{.greek-omitted} [απηγαγον]{.greek-added} και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα[15:3]{.aside}

ο δε πιλατος [παλιν]{.greek-omitted} επηρωτησεν αυτον λεγων ουκ α[π]{.greek-supplied}οκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} [ακουσας]{.greek-added} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

[κ]{.greek-supplied}ατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6]{.aside}

ην δε [ο]{.greek-omitted} λεγομενος [βαραββας]{.greek-omitted} [βα[ρ]{.greek-supplied}αβας]{.greek-added} μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει [εποιει]{.greek-omitted} [εποιη]{.greek-added} αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παραδεδωκησαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεπεισαν]{.greek-added} τον οχλον ινα μαλλον [[μαβον]{.corr}]{.greek-added} τον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκρι[θ]{.greek-supplied}εις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε [π]{.greek-supplied}αλιν εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσωτερως]{.greek-added} [εκραξαν]{.greek-omitted} [εκραξον]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω [τ]{.greek-supplied}ο ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγγελλωσας]{.greek-added} ινα σταυρωθη[15:15]{.aside}

οι δε στρατι[ω]{.greek-supplied}ται απηγαγον αυτον [εσω]{.greek-omitted} [εως]{.greek-added} της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [πραιτωριον]{.greek-omitted} [πραιτοριον]{.greek-added} και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενε[π]{.greek-supplied}αιξαν αυτω εξεδυσαν [αυτον]{.greek-omitted} [την]{.greek-omitted} [πορφυραν]{.greek-omitted} [και]{.greek-omitted} [ενεδυσαν]{.greek-omitted} αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγκαρευουσι]{.greek-added} [παραγοντα]{.greek-omitted} [παραγωντα]{.greek-added} τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω [πιειν]{.greek-omitted} [ποιειν]{.greek-added} εσμυρνισμενον οινον ο δε ουκ ελαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η επιγραφη της [αιτιας]{.greek-omitted} [αιτειας]{.greek-added} αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελεγον αλλους εσωσεν [εαυτον]{.greek-omitted} [εαυ]{.greek-added} [τον]{.greek-added} ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι συνεσταυρωμενοι αυτω [ωνειδιζον]{.greek-omitted} [ωνιδιζον]{.greek-added} αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και τη ωρα τη ενατη εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λειμα]{.greek-added} σαβαχθανι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν [φωνει]{.greek-omitted} [φωνη]{.greek-added}[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε [ιδωμεν]{.greek-omitted} [ιδομεν]{.greek-added} ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο [κεντυριων]{.greek-omitted} [κεντηριων]{.greek-added} ο παρεστηκως εξ εναντιας αυτου [οτι]{.greek-omitted} [οσι]{.greek-added} ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην και μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια [ηκολουθουν]{.greek-omitted} [ηκολου]{.greek-added} [θουν]{.greek-added} αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

ηλθεν ιωσηφ ο απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τ[ε]{.unclear}θνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους απο του [κεντυριωνος]{.greek-omitted} [κεντηριωνος]{.greek-added} εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και [αγορασας]{.greek-omitted} [αγωρασας]{.greek-added} σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισε]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι [αποκεκυλισται]{.greek-omitted} [αποκεκυλισθαι]{.greek-added} ο λιθος ην γαρ μεγας [σφοδρα]{.greek-omitted} [φοδρα]{.greek-added}[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβησθε]{.greek-added} [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι [ταχυ]{.greek-added} εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι [πρωτη]{.greek-omitted} [πρωτου]{.greek-added} σαββατου εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ [αυτης]{.greek-omitted} [αυτοις]{.greek-added} ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδησε]{.greek-added} την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον [εγηγερμενον]{.greek-omitted} [εγειγερμενον]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και [βαπτισθεις]{.greek-omitted} [βαπτιστης]{.greek-added} σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα [παρακολουθησει]{.greek-omitted} [παρακολουθουσει]{.greek-added} εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι [αρρωστους]{.greek-omitted} [αρωστους]{.greek-added} χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλ[η]{.unclear}σαι αυτοις ανεληφθη εις τον ουρανον και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των [επακολουθουντων]{.greek-omitted} [επακολουθουν]{.greek-added} [των]{.greek-added} σημειων αμην[16:20]{.aside}

