---
title: "Collation of Byz^RP^ vs 30728 (728)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 728 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30728).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 728                                   	| λογος                              	|
| 728 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 728 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 728               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 728                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 728 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 728                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν [τ[―]{.gap}ς]{.greek-added} [τοις]{.corr} προφηταις ιδου εγω [αποστελλω]{.greek-omitted} [αποστελω]{.greek-added} τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπτιζων εν [τη]{.greek-omitted} ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα [η]{.greek-omitted} ιουδαια χωρα και οι ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ενδεδυμενος τριχας καμηλου και ζωνην [δερματινην]{.greek-omitted} [δερματηνην]{.greek-added} περι την [οσφ[η]{.unclear}ν]{.greek-added} [οσφυν]{.corr} αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν [καταβαινων]{.greek-added} [καταβαινον]{.corr} επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω [ε]{.unclear}υδοκησα [[[η]{.unclear}υδοκησα]{.corr}]{.greek-added}[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} πει[ρ]{.unclear}αζομενος υπο του σατανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι [τον]{.greek-omitted} ιωαννην ηλθεν [ο]{.greek-omitted} [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν σιμωνα και ανδρεαν τον αδελφον αυτου [του]{.greek-omitted} σιμωνος [βαλλοντας]{.greek-omitted} [αμφιβαλλοντας]{.greek-added} αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα [δικτυα]{.greek-omitted} [δυκτια]{.greek-added} αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως [εκαλεσεν]{.greek-omitted} [εκελευσεν]{.greek-added} αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο [παντες]{.greek-added} επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και ανεκραξεν[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας [οιδα]{.greek-omitted} [οδα]{.greek-added} σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το πνευμα το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους λεγοντας τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοι[ς]{.unclear} [επιτασσει]{.greek-omitted} [επιτασει]{.greek-added} και υπακουουσιν αυτω[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις τη[ν]{.unclear} οικιαν σιμωνος και ανδρεου μετα ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην [κ]{.unclear}ρατησας της χειρος αυτης και α[φη]{.unclear}κεν αυτην ο πυρετος ευθεως [κα]{.unclear}ι διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη [ην]{.greek-added} επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας [ποικιλαις]{.greek-omitted} [πικοιλαις]{.greek-added} νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι εν[νυ]{.unclear}χον λι[α]{.unclear}ν α[ν]{.unclear}α[σ]{.unclear}τας [εξηλθεν]{.greek-omitted} [εξ[η]{.unclear}λθε]{.greek-added} κ[α]{.unclear}ι απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ε[ρη]{.unclear}μον τοπον κακε[ι]{.unclear} [π]{.unclear}ροσ[η]{.unclear}υχε[το]{.unclear}[1:35]{.aside}

[κ]{.greek-supplied}αι [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον [ο]{.greek-omitted} [σι]{.unclear}μων και οι μετ αυτου[1:36]{.aside}

και ε[υροντ]{.unclear}ες αυτον λ[ε]{.unclear}γουσιν αυτω οτι [παντε]{.unclear}ς σε [ζητουσιν]{.greek-omitted} [[ζη]{.unclear}τουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις [αγω]{.unclear}μεν εις [τ]{.unclear}ας [ε]{.unclear}χομενα[ς]{.unclear} κωμο[π]{.unclear}[ο]{.greek-supplied}[λ]{.unclear}εις [ιν]{.unclear}α [κ]{.unclear}αι εκει κηρυ[ξω]{.unclear} [εις]{.unclear} τ[ου]{.greek-supplied}το [γ]{.unclear}[αρ]{.greek-supplied} [εξε]{.greek-supplied}ληλυθα[1:38]{.aside}

και ην κηρυ[σσ]{.unclear}ων [εν]{.unclear} [ταις]{.unclear} συναγωγαις αυτων [ει]{.unclear}ς [ο]{.unclear}λην την γαλιλαιαν και τα δαιμονια ε[κ]{.unclear}βαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γον[υπ]{.unclear}ετων αυτον και λεγων αυτω οτι εαν θελης δυ[ν]{.unclear}ασαι με καθαρισα[ι]{.unclear}[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθει[ς]{.unclear} εκτε[ινας]{.unclear} την χειρα ηψατο [α]{.unclear}υτο[υ]{.unclear} [και]{.unclear} λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου [ε]{.unclear}υθεως απηλθεν απ αυτου η λ[επ]{.unclear}ρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι [φα[ρ]{.unclear}]{.greek-added} [φανερως]{.corr} εις πολιν [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισελθε]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [πα]{.unclear}λιν εις καπερναουμ δι [η]{.unclear}μ[ε]{.unclear}ρων και ηκουσθη οτι εις οικον εστιν[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες [αιρομενον]{.greek-omitted} [αιρωμενο[ν]{.unclear}]{.greek-added} υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι [αυτω]{.greek-added} αυτω δια [τ]{.unclear}ον οχλον [απεσ]{.unclear}τεγασα[ν]{.unclear} [τη]{.unclear}ν [στε]{.unclear}γ[η]{.unclear}ν [ο]{.unclear}που η[ν]{.unclear} [και]{.unclear} εξορυξα[ντ]{.unclear}ες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον [κραββατον]{.greek-omitted} [[κ]{.unclear}ρ[α]{.unclear}βατον]{.greek-added} εφ ω [ο]{.unclear} παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την [πισιν]{.greek-added} [πιστιν]{.corr} αυτων λε[γ]{.unclear}ει τω παραλυτ[ι]{.unclear}κω τεκνον [αφεωνται]{.greek-omitted} [αφεο[ν]{.unclear}ται]{.greek-added} σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογι[ζ]{.unclear}ομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

[τι]{.greek-omitted} [οτι]{.greek-added} ουτος [ουτως]{.greek-omitted} λαλει βλασφ[η]{.unclear}μιας τις δυναται αφιεναι αμαρ[τι]{.unclear}ας ει μη εις [ο]{.greek-omitted} [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους [ο]{.greek-omitted} [ιησους]{.greek-omitted} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν [εαυτοις]{.greek-omitted} [αυτοις]{.greek-added} ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σου αι αμαρτιαι [η]{.unclear} ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον σου τον κραββατον και περιπατει[2:9]{.aside}

ινα δε ειδ[η]{.unclear}τε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιεναι]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι [λεγω]{.greek-omitted} [λεγεις]{.greek-added} [εγειραι]{.greek-omitted} [εγειρ[ε]{.unclear}]{.greek-added} και αρον τον κραββατον σου και υ[παγε]{.unclear} εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεω[ς]{.unclear} και αρας τον κραββατον εξηλθεν [εναντιον]{.greek-omitted} [[ε]{.unclear}ναντιων]{.greek-added} παντων ωστε εξ[ιστασθαι]{.unclear} παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι [ουδεποτε]{.greek-omitted} [ουδεποται]{.greek-added} ουτως ειδομεν[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι [ιατ[ρου]{.unclear}]{.greek-added} ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και οι των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και οι των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} νηστευουσιν οι δε σοι μαθηται ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος [εν]{.greek-omitted} [νηστευειν]{.greek-added} [εφ]{.greek-added} ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον με[θ]{.unclear} [εαυτων]{.greek-omitted} [εαυτον]{.greek-added} [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου [δυνανται]{.greek-omitted} [δυναται]{.greek-added} νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευουσιν]{.greek-added} εν εκειναις ταις ημεραις[2:20]{.aside}

[και]{.greek-omitted} ουδεις επιβλημα [ρακους]{.greek-omitted} [ρακκους]{.greek-added} αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} [επι]{.greek-omitted} ιματιω παλαιω ει δε μη [αιρει]{.greek-omitted} [αιρη]{.greek-added} το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον [νεον]{.greek-omitted} [εον]{.greek-added} εις ασκους καινους βλητεον[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου [οδον]{.greek-omitted} [ποιειν]{.greek-omitted} [οδοποιειν]{.greek-added} τιλλοντες τους σταχυας[2:23]{.aside}

και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} [και]{.greek-omitted} τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον [ει]{.greek-omitted} [εν]{.greek-added} τοις σαββασιν θεραπευσει αυτον ινα κατηγορησωσιν αυτο[υ]{.unclear}[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τ[ω]{.unclear} [εξηραμμενην]{.greek-omitted} [ε[ξ]{.unclear}ηραμενην]{.greek-added} [εχοντι]{.greek-omitted} [εχ[ο]{.unclear}ν]{.greek-added} την [χειρα]{.greek-omitted} [χειραν]{.greek-added} [εγειραι]{.greek-omitted} [εγει[ρε]{.unclear}]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοι[ς]{.unclear} [[τι]{.unclear}]{.greek-added} ε[ξ]{.unclear}[ε]{.greek-supplied}στιν [εν]{.greek-added} τοις σαββασιν [αγαθοποιησαι]{.greek-omitted} [αγα[θον]{.unclear}]{.greek-added} [ποιησαι]{.greek-added} η κακοποιησαι ψ[υ]{.unclear}χην σωσαι η [αποκτειναι]{.greek-omitted} [απολεσαι]{.greek-added} οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργ[η]{.unclear}ς [συλλυπουμενος]{.greek-omitted} [συλυπουμενος]{.greek-added} επι τη [πωρωσει]{.greek-omitted} [πορρωσει]{.greek-added} της καρ[δ]{.unclear}ιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτ[ει]{.unclear}νον την χειρα σου και [εξετεινεν]{.greek-omitted} [ε[ξε]{.unclear}τεινε]{.greek-added} κα[ι]{.greek-supplied} [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου [υγιης]{.greek-omitted} [υγιη]{.greek-added} ως η αλλη[3:5]{.aside}

και εξελθοντες οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου [προς]{.greek-omitted} [εις]{.greek-added} [την]{.unclear} θαλασσαν και π[ο]{.unclear}λ[υ]{.unclear} [π]{.unclear}ληθος απο της γαλιλαια[ς]{.unclear} [ηκολουθησαν]{.greek-omitted} [ηκ[ολο]{.unclear}υ[θη]{.greek-supplied}[σεν]{.unclear}]{.greek-added} [αυτω]{.greek-omitted} [και]{.unclear} απο τ[ης]{.unclear} ιουδαια[ς]{.unclear}[3:7]{.aside}

κ[αι]{.unclear} α[πο]{.unclear} [ιερ]{.unclear}οσ[ο]{.unclear}λυ[μ]{.unclear}ων και α[π]{.unclear}ο της ιδουμαι[ας]{.unclear} και περαν του ιορδανου και οι περι τ[υρον]{.unclear} [και]{.unclear} σιδωνα πλ[η]{.unclear}θος πολυ [ακου]{.unclear}σαντες οσα [ε]{.unclear}ποιει ηλ[θον]{.unclear} προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [[ε]{.unclear}ιπ[ε]{.unclear}]{.greek-added} τοις μα[θη]{.unclear}ταις [αυτου]{.greek-omitted} ινα πλοι[αρ]{.unclear}[ι]{.greek-supplied}ον [προσκαρτερη]{.greek-omitted} [προσκαρτερ[ε]{.unclear}[ι]{.greek-supplied}]{.greek-added} αυτω δια τον οχ[λ]{.unclear}ον ινα μη θ[λι]{.unclear}βωσιν αυτον[3:9]{.aside}

πολλους γα[ρ]{.unclear} εθεραπευ[σ]{.unclear}εν ωστε επι[πιπ]{.unclear}τειν [αυτω]{.greek-omitted} [αυτον]{.greek-added} ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} οσ[οι]{.unclear} [ε]{.unclear}ιχον μαστιγ[ας]{.unclear}[3:10]{.aside}

και τα πν[ε]{.unclear}υματα τα ακαθαρτα [οταν]{.greek-omitted} [οτε]{.greek-added} αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσε[πι]{.unclear}πτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} [λεγοντα]{.greek-omitted} [λεγ[ο]{.unclear}ν]{.greek-added} οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει ει[ς]{.unclear} το ορος και προσκαλειται ους ηθελεν [αυτος]{.greek-omitted} [αυτους]{.greek-added} και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλει]{.greek-added} [αποστελλη]{.corr} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και [εκβαλλειν]{.greek-omitted} [εκβαλειν]{.greek-added} τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα [πετρον]{.greek-omitted} [πετρω]{.greek-added}[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον [του]{.greek-omitted} ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο [εστιν]{.greek-omitted} [εστι]{.greek-added} υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδ[α]{.unclear}ν [τον]{.greek-added} ισκαριωτην ος και παρεδωκ[ε]{.unclear}ν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη [δυνασθαι]{.greek-omitted} [δυσασθαι]{.greek-added} αυτους [μητε]{.greek-omitted} [[μ]{.unclear}ηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστ[η]{.unclear}[3:21]{.aside}

[και]{.greek-omitted} [καϊ]{.greek-added} οι γραμματεις [και]{.greek-added} οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους ε[ν]{.unclear} [πα]{.unclear}ραβολαις ελεγεν αυτοις πως δυ[ν]{.unclear}α[ται]{.greek-supplied} [ο]{.greek-added} σατανας σαταναν εκβαλλει[ν]{.unclear}[3:23]{.aside}

κ[αι]{.unclear} εαν βασιλεια εφ εαυτην μερισθ[η]{.unclear} [ου]{.unclear} δυναται σταθηναι η βασιλεια εκε[ινη]{.unclear}[3:24]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου διαρπαση[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

[ος]{.greek-omitted} [ως]{.greek-added} δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος [εστιν]{.greek-omitted} [εστι]{.greek-added} αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον [εχει]{.greek-omitted} [εχοι]{.greek-added}[3:30]{.aside}

ερχονται ου[ν]{.unclear} οι αδελφοι και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και [εκαθητο]{.greek-omitted} [εκαθοιτο]{.greek-added} οχλος περι αυτον ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και [περιβλεψαμενος]{.greek-omitted} [βλεψαμενος]{.greek-added} κυκλω τους περι αυτον καθημενους [λεγει]{.greek-omitted} [ιδε]{.greek-omitted} [λεγων]{.greek-added} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και [οι]{.greek-omitted} [η]{.greek-added} αδελφοι μου[3:34]{.aside}

ος γαρ αν [ποιησ[ει]{.unclear}]{.greek-added} [ποιηση]{.corr} το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [εστιν]{.greek-omitted}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη [διδαχη]{.greek-omitted} [διδασκαλια]{.greek-added} αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} εν τω σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} τα πετεινα και [κατεφαγεν]{.greek-omitted} [κατεφαγον]{.greek-added} αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην [πολλην]{.greek-omitted} [καλλην]{.greek-added} και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλαν]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν [ριζαν]{.greek-omitted} [ριζας]{.greek-added} εξηρανθη[4:6]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και [συνεπνιξαν]{.greek-omitted} [απεπνιξαν]{.greek-added} αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδοκει]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.corr} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα γινεται[4:11]{.aside}

ινα βλεποντες [μη]{.greek-added} [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον [εσπαρμενον]{.greek-omitted} [σπαρμενον]{.greek-added} εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προ[σκαιροι]{.unclear} [εισιν]{.greek-omitted} [[ει]{.unclear}σι]{.greek-added} ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι ει[ς]{.unclear} τας ακανθας σπειρομ[ενοι]{.unclear} [οι]{.unclear} τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη τ[ου]{.unclear} πλουτου και αι περι τα λοιπα [επιθυμιαι]{.greek-omitted} [επεθυμη]{.greek-added} εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [σ[υ]{.unclear}νπνιγουσι]{.greek-added} τον λογον [και]{.unclear} ακαρπος γινεται[4:19]{.aside}

κα[ι]{.unclear} [ου]{.unclear}τοι εισιν οι επι την γην την καλην σπαρ[εν]{.unclear}τες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφο[ρ]{.unclear}ουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα [υπο]{.greek-omitted} [επι]{.greek-added} τον μοδιον τεθη η [υπο]{.greek-omitted} [επι]{.greek-added} την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ εστιν [τι]{.greek-omitted} κρυπτον ο [εαν]{.greek-omitted} [μη]{.greek-omitted} φανερωθη ουδε εγενετο αποκρυ[φ]{.unclear}ον αλλ ινα ε[ις]{.unclear} [φ]{.unclear}αν[ε]{.unclear}ρον ελ[θη]{.unclear}[[4:22 *(lacunose)*]{.lacunose}]{.aside}

ει τις [εχ]{.unclear}ει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε μετρηθησεται υμιν [και]{.greek-omitted} [προστεθησεται]{.greek-omitted} [υμιν]{.greek-omitted} τοις [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added}[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [εχη]{.greek-omitted} [εχοι]{.greek-added} δοθησεται αυτω και ος ουκ [εχει]{.greek-omitted} [εχοι]{.greek-added} και ο [εχει]{.greek-omitted} [εχοι]{.greek-added} αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [βαλοι]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} [ως]{.greek-omitted} [και]{.greek-added} ουκ οιδεν αυτος[4:27]{.aside}

[αυτοματη]{.greek-omitted} [αυτοματως]{.greek-added} γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα [πληρη]{.greek-omitted} [πληρει]{.greek-added} σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσομεν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως κοκκον σιναπεως ος οταν σπαρη επι της γης [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις [πολλαις]{.greek-omitted} ελαλει αυτοις [τον]{.greek-omitted} [λογον]{.greek-omitted} [καθως]{.greek-omitted} [εδυναντο]{.greek-omitted} [ακουειν]{.greek-omitted}[4:33]{.aside}

[χωρις]{.greek-omitted} [δε]{.greek-omitted} [παραβολης]{.greek-omitted} [ουκ]{.greek-omitted} [ελαλει]{.greek-omitted} [αυτοις]{.greek-omitted} κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [απελυε]{.greek-added} παντα[4:34]{.aside}

και [λεγει]{.greek-omitted} [ελεγεν]{.greek-added} αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται λαιλαψ ανεμου [μεγαλη]{.greek-omitted} [μεγαλου]{.greek-added} τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε [αυτο]{.greek-omitted} ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι τη [πρυμνη]{.greek-omitted} [πριμνη]{.greek-added} επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι [απολλυμεθα]{.greek-omitted} [απολυμεθα]{.greek-added}[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχε[τε]{.unclear} πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα [εστι]{.greek-added} ουτος [εστιν]{.greek-omitted} οτ[ι]{.unclear} και ο ανεμος και η θαλασσα υπακουουσιν αυ[τω]{.unclear}[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και εξελθοντι [αυτω]{.greek-omitted} [αυτου]{.greek-added} εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν [ηδυνατο]{.greek-added} ουδεις [εδυνατο]{.greek-omitted} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις [πεδ[ε]{.unclear}ς]{.greek-added} [πεδαις]{.corr} και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις αυτον [ισχυεν]{.greek-omitted} [ισχυε]{.greek-added} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι εμοι και [συ]{.greek-added} [σοι]{.greek-omitted} [ιησου]{.greek-omitted} υιε [του]{.greek-omitted} [θεου]{.greek-omitted} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

ελεγεν γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι [το]{.greek-added} ονομα και απεκριθη λεγων λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει προς τω ορει αγελη χοιρων μεγαλη βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη [θαλασση]{.greek-omitted} [θαλαση]{.greek-added}[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και ανηγγειλαν εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον [και]{.greek-omitted} ιματισμενον και σωφρονουντα τον εσχηκοτα [τον]{.greek-omitted} λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} [αυτοις]{.greek-omitted} οι ιδοντες πως εγενετο τω δαιμονιζομενω και [περι]{.greek-omitted} [παρα]{.greek-added} των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} μετ αυτου [η]{.greek-added}[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν [τω]{.greek-added} [τη]{.corr} [δεκαπολει]{.greek-omitted} [δεκαπολη]{.greek-added} οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται [εις]{.greek-omitted} [τις]{.greek-added} των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα [ελθων]{.greek-omitted} [απελθων]{.greek-added} [επιθης]{.greek-omitted} [επιθησεις]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και απηλθεν μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο [πολλ[α]{.unclear}]{.greek-added} [[π]{.unclear}[―]{.gap}]{.greek-added} [πολλων]{.corr} ιατρων και [δαπανησασα]{.greek-omitted} [δαπανισασα]{.greek-added} τα παρ αυτης παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα [περι]{.greek-omitted} [παρα]{.greek-added} του [ιησου]{.greek-abbr} [ελθουσα]{.greek-omitted} εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι [καν]{.greek-omitted} [εαν]{.greek-added} των ιματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι [ιαται]{.greek-omitted} [ιαθη]{.greek-added} απο της [μαστηγος]{.greek-added} [μαστιγος]{.corr}[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν [εξελθουσαν]{.greek-omitted} [εξελθουσα]{.greek-added} επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις [τις]{.greek-omitted} [μου]{.greek-omitted} [ηψ]{.greek-supplied}ατο[5:31]{.aside}

και [περιε]{.unclear}βλεπετο ι[δ]{.unclear}ειν την [του]{.unclear}το [ποιησασαν]{.greek-omitted} [[ποιησ]{.unclear}ασα]{.greek-added}[5:32]{.aside}

η [δε]{.unclear} γυνη φο[βηθ]{.unclear}εισα [κα]{.unclear}ι τρεμουσα ειδυια ο γεγ[ο]{.unclear}νεν επ αυτη [ηλθεν]{.greek-omitted} [ηλ[θ]{.unclear}ε]{.greek-added} [κ]{.unclear}αι προσεπεσεν αυτω και ειπεν αυτω π[ασ]{.unclear}αν την αληθειαν[5:33]{.aside}

[ο]{.unclear} δε ειπεν αυτη θυγατερ η πι[στις]{.unclear} [σ]{.unclear}ου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος [σο]{.unclear}υ[5:34]{.aside}

ετι αυτου λαλουντος [ερχονται]{.greek-omitted} [ερχον]{.greek-added} απο του αρχισυναγωγου λεγοντες οτι η θυγατ[η]{.unclear}ρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλεις]{.greek-added} τον διδασκ[α]{.unclear}λον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας το[ν]{.unclear} [λ]{.unclear}ογον [λ]{.unclear}αλουμενον λεγε[ι]{.unclear} τω αρχισυναγωγω μη [φ]{.unclear}οβου μονον πιστευε[5:36]{.aside}

και ουκ [αφηκεν]{.greek-omitted} [αφεικ[ε]{.unclear}ν]{.greek-added} [αυτω]{.greek-added} [ο]{.unclear}υδενα [αυτω]{.greek-omitted} [συνακολουθησαι]{.greek-omitted} [ακολουθησαι]{.greek-added} ει μη πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον ιακωβου[5:37]{.aside}

και ερχ[ε]{.unclear}ται εις [τον]{.greek-omitted} [οικον]{.greek-omitted} το[υ]{.unclear} [αρχι]{.unclear}σ[υνα]{.unclear}γωγου και θεωρει θορυβον [κλαιον]{.unclear}τ[ας]{.unclear} και [αλαλαζοντας]{.greek-omitted} [αλλαλα[ζ]{.unclear}οντας]{.greek-added} πολλα[5:38]{.aside}

κα[ι]{.unclear} εισελθων λεγει αυτοις τι [θορυ]{.unclear}[βεισ]{.greek-supplied}θε και [κ]{.unclear}λαιετε το παι[δ]{.greek-supplied}[ιον]{.unclear} ο[υκ]{.unclear} απεθανεν αλλα καθευδει[5:39]{.aside}

[και]{.unclear} [κατεγελων]{.greek-omitted} [[κατε]{.unclear}γελουν]{.greek-added} αυτου ο δε εκ[βαλων]{.unclear} [παν]{.unclear}τας παραλαμβανει τον [πατερα]{.greek-abbr} του [παιδιου]{.greek-omitted} [παιδος]{.greek-added} και την [μητερα]{.greek-abbr} και [τους]{.greek-omitted} μ[ε]{.unclear}τ αυτου και ει[σ]{.unclear}πορευεται [ο]{.unclear}που ην τ[ο]{.unclear} παιδιον [ανακειμενον]{.greek-omitted} [κατακειμενον]{.greek-added}[5:40]{.aside}

κ[αι]{.unclear} [κ]{.unclear}ρατησας της χειρος του παιδιου [λεγει]{.greek-omitted} [αυτη]{.greek-omitted} [ταλιθα]{.greek-omitted} [ταβιθα]{.greek-added} [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [μεθερμηνευομενον]{.greek-omitted} [μεθερμηνευομεν]{.greek-added} το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και [διεστειλατο]{.greek-omitted} [ενετειλατο]{.greek-added} αυτοις π[ο]{.unclear}λλα ινα μηδεις γνω τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν [εκειθεν]{.greek-omitted} [εκειθε]{.greek-added} και ηλθεν εις την πατριδα αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτα και τις η [δοθεισα]{.greek-added} σοφια [η]{.greek-omitted} [δοθεισα]{.greek-omitted} αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} ο τεκτων ο υιος μαριας αδελφος δε ιακωβου και ιωση και ιου[δ]{.unclear}α και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε [αυτοις]{.greek-omitted} ο [ιησους]{.greek-abbr} [οτι]{.greek-omitted} [αυτοις]{.greek-added} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [πατριδι]{.greek-omitted} [[πριδι]{.greek-abbr}]{.greek-added} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ [ηδυνατο]{.greek-omitted} [ηδυναντο]{.greek-added} εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλ[ε]{.unclear}ιν δυ[ο]{.unclear} δυ[ο]{.unclear} και [εδιδου]{.greek-omitted} [ε[κ]{.unclear}διδου]{.greek-added} αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μ[ονον]{.unclear} μη [πηραν]{.greek-omitted} [πειραν]{.greek-added} μη αρτον [μ]{.unclear}η [εις]{.unclear} [την]{.unclear} ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} [υποδεδεμενους]{.greek-omitted} [υποδεδυμενους]{.greek-added} σανδαλ[ια]{.unclear} κα[ι]{.unclear} [μ]{.unclear}η [ενδυσ[ε]{.unclear}σθε]{.greek-added} [ενδυσησθε]{.corr} δυο χιτ[ωνα]{.unclear}[ς]{.greek-supplied}[6:9]{.aside}

[και]{.unclear} ελεγεν αυτοις ο[που]{.unclear} εαν εισελθητε εις οικια[ν]{.unclear} [εκ]{.unclear}ει με[ν]{.unclear}ετε εως αν εξελθη[τε]{.unclear} [ε]{.unclear}κειθε[ν]{.unclear}[6:10]{.aside}

και [οσοι]{.greek-omitted} [οπου]{.greek-added} [αν]{.greek-omitted} [εαν]{.greek-added} μ[η]{.unclear} [δε]{.unclear}ξωντα[ι]{.unclear} υμας μηδε ακουσω[σιν]{.unclear} υμων εκπορ[ε]{.unclear}υο[μ]{.unclear}ενο[ι]{.unclear} εκει[θε]{.unclear}ν εκ[τ]{.greek-supplied}ιναξατ[ε]{.unclear} τον χου[ν]{.unclear} [τον]{.greek-omitted} [[τ]{.unclear}ων]{.greek-added} υ[π]{.unclear}οκατω των ποδων [υμων]{.unclear} εις μαρτυριον αυτ[οι]{.unclear}ς [α]{.unclear}μ[η]{.unclear}ν λεγω [υμ]{.unclear}ιν [α]{.unclear}ν[ε]{.unclear}κτ[οτε]{.greek-supplied}ρον [ε]{.unclear}σται σο[δομοις]{.unclear} [η]{.unclear} [γομορροις]{.greek-omitted} [[γ]{.unclear}[ο]{.greek-supplied}μοροι[ς]{.unclear}]{.greek-added} εν ημ[ερα]{.unclear} κρι[σ]{.unclear}ε[ω]{.unclear}ς η τη [πολ]{.unclear}ει εκει[νη]{.unclear}[6:11]{.aside}

και ε[ξ]{.greek-supplied}ελθοντες εκηρυ[σ]{.unclear}σον ινα [μετανοησωσιν]{.greek-omitted} [μετανο[ησωσ]{.unclear}ι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλ[α]{.unclear} εξεβα[λ]{.unclear}λον και ηλειφον ελαιω πολλ[ους]{.unclear} [αρρωστους]{.greek-omitted} [[α]{.unclear}ρ[ω]{.unclear}στους]{.greek-added} κα[ι]{.unclear} εθεραπευον[6:13]{.aside}

και ηκουσεν [ηρωδης]{.greek-added} ο βασιλευς [ηρωδης]{.greek-omitted} [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και [ελεγεν]{.greek-omitted} [ελεγον]{.greek-added} οτι [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο [βαπτιζων]{.greek-omitted} [βαπτιστης]{.greek-added} εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν [οτι]{.greek-omitted} ον εγω [απεκεφαλισα]{.greek-omitted} [αποκεφαλισα]{.greek-added} [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ [ο]{.greek-omitted} ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο [ιωαννης]{.greek-omitted} [τω]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [τον]{.greek-added} [ηρωδη]{.greek-omitted} [ηρωδην]{.greek-added} οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν [την]{.greek-omitted} [αυτην]{.greek-added} γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ειδως αυτον ανδρα δικαιον και [αγιον]{.greek-omitted} [και]{.greek-omitted} [αγιως]{.greek-added} [συνετηρη]{.greek-added} [συνετηρει]{.corr} αυτον και ακουσας αυτου πολλα εποιει και [ηδεως]{.greek-omitted} [ειδεως]{.greek-added} αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις [γενεσιοις]{.greek-omitted} [γεννεσιοις]{.greek-added} αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις [πρωτοις]{.greek-omitted} [πρωτης]{.greek-added} της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν μ[ε]{.unclear} αιτησης δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:25]{.aside}

και περιλυπος [γ[―]{.gap}]{.greek-added} [γενομενος]{.corr} ο βασιλευ[ς]{.unclear} δια τους ορκους και τους συνανακειμενο[υς]{.unclear} ουκ ηθελησεν [αυτην]{.greek-omitted} [αυτον]{.greek-added} αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς [σπεκουλατορα]{.greek-omitted} [σπεκουλατωρα]{.greek-added} επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθ[η]{.unclear}ται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτον]{.greek-added} εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυσασθε]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added}[6:31]{.aside}

και [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και [πεζη]{.greek-omitted} [πεζοι]{.greek-added} απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [προηλθεν]{.greek-added} αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων ειδεν ο [ιησους]{.greek-abbr} [πολυν]{.greek-omitted} οχλον [πολλυν]{.greek-added} και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται αυτου [λεγουσιν]{.greek-omitted} [λεγοντες]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν [εαυτοις]{.greek-omitted} [αυτοις]{.greek-added} αρτους τι γαρ φαγωσιν ουκ [εχουσιν]{.greek-omitted} [εχωσιν]{.greek-added}[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} αυτω απελθοντες αγορασωμεν δηναριων διακοσιων αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

[και]{.greek-added} [λεγουσιν]{.greek-added} [αυτω]{.greek-added} [απελθοντες]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ποσους]{.greek-omitted} [αρτους]{.greek-omitted} [εχετε]{.greek-omitted} υπαγετε και [ιδετε]{.greek-omitted} [ειδετε]{.greek-added} και γνοντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [κλασματων]{.greek-omitted} [κλασματα]{.greek-added} δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

[και]{.greek-omitted} [ησαν]{.greek-omitted} οι [δε]{.greek-added} φαγοντες τους αρτους [πεντακισχιλιοι]{.greek-omitted} [πεντα[σ]{.unclear}κισχιλιοι]{.greek-added} ανδρες[6:44]{.aside}

και ευθεως ηναγκασεν τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς βηθσαιδαν εως αυτος απολυση τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους [βασανιζομενους]{.greek-omitted} [βασινιζομενους]{.greek-added} εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις [θαρσειτε]{.greek-omitted} εγω ειμι μη φοβεισθε[6:50]{.aside}

[και]{.greek-omitted} ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην [γαρ]{.greek-omitted} αυτων η καρδια πεπωρωμενη[6:52]{.aside}

και [διαπερασαντες]{.greek-omitted} [διασπαρασσαντες]{.greek-added} ηλθον επι την γην γεννησαρετ και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

[περιδραμοντες]{.greek-omitted} [παραδραμοντες]{.greek-added} ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η [εις]{.greek-added} πολεις η [εις]{.greek-added} αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι [φαρισαιοι]{.greek-omitted} [φαρισσαι]{.greek-added} και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [ο]{.greek-added} [λεγεται]{.greek-added} [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} ανιπτοις εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και παντες οι ιουδαιοι εαν μη πυγμ[η]{.unclear} [νιψωνται]{.greek-omitted} [νιψωσι]{.greek-added} τα[ς]{.unclear} χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

[επειτα]{.greek-omitted} [επερωτωσιν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [σου]{.greek-omitted} [ου]{.greek-omitted} [περιπατουσιν]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} [παραδοσιν]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} αλλα ανιπτοις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων κα[ι]{.unclear} ποτηριων και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σ[ου]{.unclear} και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε ε[α]{.unclear}ν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} [η]{.unclear} τ[η]{.unclear} [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιε[τ]{.unclear}ε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρε[δω]{.unclear}κατε [κα]{.unclear}ι [πα]{.unclear}ρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρ[ωτω]{.unclear}ν αυτον οι μαθη[τα]{.unclear}ι α[υ]{.unclear}του περι της παραβολης[7:17]{.aside}

και λε[γ]{.unclear}ε[ι]{.unclear} αυτοις ουτως και υμεις [ασ]{.unclear}υνετ[οι]{.unclear} εστε ου νοειτε οτι παν [το]{.unclear} [εξωθεν]{.greek-omitted} [εξοθε[ν]{.unclear}]{.greek-added} εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

ο[τ]{.unclear}ι [ουκ]{.unclear} ει[σ]{.unclear}πορευεται αυτου εις την καρδ[ια]{.unclear}ν αλλ ει[ς]{.unclear} την κοιλιαν και ει[ς]{.unclear} [το]{.greek-supplied}[ν]{.unclear} [α]{.unclear}[φε]{.greek-supplied}δρωνα εκπ[ο]{.unclear}ρευεται [καθαριζον]{.greek-omitted} [κ[αθαριζ]{.unclear}[ων]{.greek-supplied}]{.greek-added} π[α]{.unclear}ντα τ[α]{.unclear} [β]{.unclear}ρωματα[7:19]{.aside}

ελεγε[ν]{.greek-supplied} [δε]{.greek-supplied} οτι το [ε]{.unclear}κ το[υ]{.unclear} [ανθρωπου]{.greek-abbr} εκπορ[ευ]{.unclear}ομ[ε]{.unclear}[νον]{.greek-supplied} εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

ε[σωθεν]{.unclear} [γαρ]{.unclear} εκ της καρδι[ας]{.unclear} των [ανθρωπων]{.greek-abbr} ο[ι]{.unclear} δι[αλο]{.unclear}γισμοι ο[ι]{.unclear} [κακ]{.unclear}οι εκπορευονται μο[ι]{.unclear}χ[ε]{.unclear}ιαι πορνειαι φονοι [κλοπ[αι]{.unclear}]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλ[εο]{.unclear}νεξιαι πονηρι[αι]{.greek-supplied} [δ]{.unclear}ολ[ο]{.unclear}ς ασε[λγ]{.unclear}ει[α]{.unclear} ο[φθ]{.unclear}[αλ]{.greek-supplied}[μο]{.unclear}ς πονηρο[ς]{.unclear} βλ[α]{.greek-supplied}σφ[η]{.greek-supplied}μι[α]{.unclear} υπερηφ[α]{.unclear}νι[α]{.unclear} [α]{.unclear}φροσυ[νη]{.unclear}[7:22]{.aside}

π[αντα]{.unclear} ταυ[τα]{.unclear} [τα]{.greek-supplied} [πον]{.greek-supplied}[ηρα]{.unclear} [εσωθ]{.unclear}εν [εκπο]{.greek-supplied}ρευεται και κο[ιν]{.unclear}οι [το]{.unclear}ν [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελον]{.greek-added} γνωναι και ουκ [ηδυνηθη]{.greek-omitted} [ηδυνατο]{.greek-added} λαθειν[7:24]{.aside}

ακουσα[σ]{.unclear}α γαρ γυνη περι αυτου ης ειχ[ε]{.unclear}ν το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της [θ]{.unclear}υγατρος αυτ[η]{.unclear}ς[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν [το]{.unclear}ις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζ[ης]{.unclear} εσθιει απο των [ψυχιων]{.greek-added} [ψιχιων]{.corr} των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης ευρεν το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και [σιδωνου]{.greek-added} [σιδωνος]{.corr} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τ[ην]{.unclear} θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον [μογγιλαλον]{.greek-omitted} [μογιλαλον]{.greek-added} και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις [διεστελλετο]{.greek-omitted} [διεστειλατο]{.greek-added} μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους [αλαλους]{.greek-omitted} [αλους]{.greek-added} λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ται[ς]{.unclear} ημεραις [παμπολλου]{.greek-omitted} [πανπολλου]{.greek-added} οχλου οντος και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος ο [ιησους]{.greek-abbr} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις [τον]{.greek-added} οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκουσι]{.greek-added}[8:3]{.aside}

και απεκριθησαν [αυτω]{.greek-omitted} οι [μαθηται]{.greek-omitted} [μαθη]{.greek-added} αυτου ποθεν τουτους δυνησεται τις ωδε χορτασαι αρτων επ [εμ[―]{.gap}ας]{.greek-added} [ερημιας]{.corr}[8:4]{.aside}

και [επηρωτα]{.greek-omitted} [επηρωτων]{.greek-added} αυτους ποσους [αρτους]{.greek-added} [εχεται]{.greek-added} [εχετε]{.corr} [αρτους]{.greek-omitted} οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους [και]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και [παρεθηκαν]{.greek-omitted} [παρεθηκε]{.greek-added} τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παραθειναι και αυτα[8:7]{.aside}

εφαγον δε [παντες]{.greek-added} και εχορτασθησαν και ηραν [περισσευματα]{.greek-omitted} [περισσευματων]{.greek-added} [κλασματων]{.greek-omitted} [κλασματα]{.greek-added} επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες [ως]{.greek-omitted} [ωσει]{.greek-added} τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [ευθεως]{.greek-omitted} εμβα[ς]{.unclear} εις το πλοιον μετα των μαθητων αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και ηρξαντο [συζητειν]{.greek-omitted} [ζητειν]{.greek-added} αυτω ζητουντες παρ αυτο[υ]{.unclear} σημ[ε]{.unclear}ιον απο [του]{.greek-omitted} [ουρανου]{.greek-abbr} [πειραζοντες]{.greek-omitted} [πειραζον]{.greek-added} [αυτο]{.unclear}ν[8:11]{.aside}

και αναστεναξ[α]{.unclear}[ς]{.greek-supplied} τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γεν[εα]{.unclear} [α]{.unclear}υτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας [παλιν]{.greek-omitted} εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελ[α]{.unclear}θοντο [οι]{.greek-added} [μαθηται]{.greek-added} λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και [της]{.greek-omitted} ζυμης ηρωδου[8:15]{.aside}

[και]{.greek-supplied} [δ]{.greek-supplied}ιελογιζοντο προς αλληλους λ[ε]{.unclear}γο[ν]{.unclear}τες οτι αρτους ουκ [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added}[8:16]{.aside}

κ[αι]{.unclear} [γ]{.unclear}νους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε [[κα]{.unclear}ι]{.greek-added} ετι πεπωρωμενην εχετε τ[η]{.unclear}ν καρδι[α]{.unclear}ν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους πληρεις κλασματων ηρατε λεγουσιν αυτω [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[8:19]{.aside}

οτε [δε]{.greek-omitted} το[υς]{.unclear} επτα εις του[ς]{.unclear} τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως ου [συνιετε]{.greek-omitted} [σινιετε]{.greek-added}[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου [εξηγαγεν]{.greek-omitted} [εξηγεν]{.greek-added} αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα αυτον ει τι [βλεπει]{.greek-omitted} [βλεπεις]{.greek-added}[8:23]{.aside}

και αναβλεψας ελεγεν [βλεπ[εις]{.unclear}]{.greek-added} [βλεπω]{.corr} τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα [παλιν]{.greek-omitted} [πασιν]{.greek-added} [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην [εισελθης]{.greek-omitted} [εισελθεις]{.greek-added} μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων [αυτοις]{.greek-omitted} τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι [δ]{.unclear}ε απεκριθησαν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον [βαπτισθ]{.greek-added} [βαπτιστην]{.corr} και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λ[ε]{.unclear}γει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε [ο]{.unclear} πετρος [λεγει]{.greek-omitted} [και]{.greek-added} [ειπεν]{.greek-added} αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκ[ε]{.unclear}ι[ν]{.unclear} αυτους ο[τ]{.unclear}ι δει τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασ[θ]{.unclear}ηναι [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και των αρχιερεων και των γραμματ[ε]{.unclear}ων και απ[ο]{.unclear}κτανθηνα[ι]{.unclear} και μετα τρεις [η]{.unclear}μ[ε]{.unclear}ρ[α]{.unclear}ς αναστηναι[8:31]{.aside}

και παρρησια τον λ[ο]{.greek-supplied}γον ελαλει και προσλα[β]{.unclear}ομεν[ος]{.unclear} αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων το[υ]{.unclear}ς μαθητα[ς]{.unclear} αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω π[ε]{.unclear}τρω λεγων [υ]{.unclear}π[α]{.unclear}γε ο[π]{.unclear}ισω μ[ο]{.unclear}υ σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος [τον]{.greek-omitted} [οχλον]{.greek-omitted} συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι [απολεσει]{.greek-omitted} [απωλεσει]{.greek-added} αυτην ος δ αν απολεση την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου ουτος σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} εαν [κερδηση]{.greek-omitted} [κερδιση]{.greek-added} τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι [δωσει]{.greek-omitted} [δοση]{.greek-added} [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη [με]{.greek-omitted} [μοι]{.greek-added} και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} [θανατου]{.greek-omitted} [θανατω]{.greek-added} εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} στιλβοντα λευκα [λιαν]{.greek-omitted} ως χιων οια [γναφευς]{.greek-omitted} [αγναφευς]{.greek-added} επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωσει]{.greek-added} και ησαν [συλλαλουντες]{.greek-omitted} [συλαλουντες]{.greek-added} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωσει]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και ηλθεν φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και [εξαπινα]{.greek-omitted} [εξαπηνα]{.greek-added} περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλ[α]{.unclear}το αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} [διηγησονται]{.greek-added} α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα και πως γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} [εγω]{.greek-added} λεγω υμιν οτι και ηλιας εληλυθεν και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον [πολυν]{.greek-omitted} [πολ[ι]{.unclear}ν]{.greek-added} [περι]{.unclear} αυτους κα[ι]{.greek-supplied} γραμμ[ατει]{.unclear}ς συζ[η]{.unclear}τουντας [α]{.unclear}υτο[ις]{.unclear}[9:14]{.aside}

[κ]{.unclear}αι ευθε[ω]{.unclear}[ς]{.greek-supplied} [πα]{.greek-supplied}ς ο [ο]{.unclear}χλος ιδων α[υ]{.unclear}τον [εξεθαμβηθη]{.greek-omitted} [ε[ξ]{.unclear}εθα[μ]{.unclear}[β]{.greek-supplied}η[θ]{.unclear}[―]{.gap}]{.greek-added} [και]{.greek-omitted} [π]{.unclear}ρο[σ]{.unclear}τρεχοντες [η]{.unclear}[σ]{.unclear}παζ[ο]{.unclear}ντο [αυτον]{.unclear}[9:15]{.aside}

κ[αι]{.unclear} [επηρωτησεν]{.greek-omitted} [επηρωτ[η]{.unclear}σε]{.greek-added} του[ς]{.unclear} γρ[αμματε]{.unclear}[ι]{.greek-supplied}ς τι συζητειτ[ε]{.unclear} [π]{.unclear}[ρ]{.greek-supplied}ος αυτους[9:16]{.aside}

[κ]{.unclear}αι [αποκριθεις]{.greek-omitted} [αποκατ[α]{.unclear}πο[κ]{.unclear}ρ[ιθ]{.unclear}ει[ς]{.unclear}]{.greek-added} εις [εκ]{.unclear} τ[ο]{.unclear}υ [ο]{.unclear}χλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} διδα[σ]{.unclear}καλε [ηνεγκα]{.unclear} [τ]{.unclear}ον υ[ι]{.unclear}[ο]{.greek-supplied}ν μου προς σε [ε]{.unclear}χοντ[α]{.unclear} πνε[υμα]{.unclear} αλαλο[ν]{.unclear}[9:17]{.aside}

[κ]{.unclear}αι ο[πο]{.unclear}υ αν [α]{.unclear}υτον [κ]{.unclear}αταλ[α]{.unclear}βη ρησσ[ει]{.unclear} [αυ]{.unclear}τ[ον]{.unclear} και αφ[ριζ]{.unclear}ει [και]{.greek-omitted} [τριζει]{.greek-omitted} του[ς]{.unclear} οδ[ο]{.unclear}ντ[ας]{.unclear} [αυτου]{.greek-omitted} [κ]{.unclear}α[ι]{.greek-supplied} ξηραιν[ετ]{.unclear}αι και ει[π]{.unclear}ον τοις [μα]{.unclear}[θ]{.greek-supplied}[η]{.unclear}τ[α]{.unclear}ις σου [ι]{.unclear}να [αυ]{.unclear}το [εκβαλωσιν]{.greek-omitted} [εκβαλλ[ω]{.unclear}σι]{.greek-added} και [ου]{.greek-supplied}κ ισχυ[σα]{.unclear}ν[9:18]{.aside}

ο δε αποκριθεις [αυτω]{.greek-omitted} [αυτοις]{.greek-added} λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το πνευμα εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

[κ]{.unclear}αι [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ει[π]{.unclear}ε]{.greek-added} [παιδιοθεν]{.greek-omitted} [παιδιοθε]{.greek-added}[9:21]{.aside}

και πολλακις αυτον [και]{.greek-omitted} εις το πυρ [εβαλεν]{.greek-omitted} [εβαλλε]{.greek-added} και εις υδατα ινα απολεση αυτον αλλ ει [τι]{.greek-omitted} δυνασα[ι]{.unclear} [[―]{.gap}αι]{.greek-added} [βοηθησον]{.corr} ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτω το [ε]{.unclear}ι δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [συντρεχει]{.greek-added} [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω [σοι]{.greek-omitted} [ε]{.unclear}πιτασσω εξελθε εξ αυτου και [μ]{.unclear}ηκετι [εισελθης]{.greek-omitted} [εισελθεις]{.greek-added} εις [α]{.unclear}υτον[9:25]{.aside}

και κραξαν [πολλα]{.greek-added} και [πολλα]{.greek-omitted} σπαραξαν αυτον [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} [κ]{.unclear}ρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις [τον]{.greek-added} οικον οι μα[θη]{.unclear}ται αυτου [επηρωτων]{.greek-omitted} [ε[πηρ]{.greek-supplied}[ω]{.unclear}τησαν]{.greek-added} α[υ]{.unclear}τον [κα]{.unclear}τ ιδιαν [ο]{.unclear}τι [δια]{.greek-added} [τι]{.greek-added} ημ[εις]{.unclear} ουκ ηδυ[νηθημεν]{.unclear} εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και απο[κ]{.unclear}τανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε [ηγνοουν]{.greek-omitted} [ηγνουνουν]{.greek-added} το ρημα και εφοβουντο α[υ]{.unclear}τον επερωτησαι[9:32]{.aside}

και ηλθεν εις καπερνα[ουμ]{.unclear} [κα]{.unclear}ι ε[ν]{.unclear} τ[η]{.unclear} [ο]{.unclear}[ι]{.greek-supplied}κια γενομ[εν]{.unclear}ος [επ]{.unclear}ηρω[τ]{.greek-supplied}α [αυ]{.unclear}τ[ο]{.unclear}[υς]{.greek-supplied} τι [ε]{.unclear}ν τ[η]{.unclear} οδω προς [εαυτους]{.unclear} [δ]{.unclear}[ι]{.greek-supplied}ελογιζ[ε]{.unclear}σθε[9:33]{.aside}

ο[ι]{.unclear} [δε]{.greek-supplied} εσιωπ[ων]{.unclear} προς α[λ]{.unclear}[λη]{.greek-supplied}[λ]{.unclear}ου[ς]{.unclear} γ[α]{.greek-supplied}ρ [διελεχθησαν]{.greek-omitted} [[δ]{.unclear}ιελεγχ[θ]{.unclear}ησαν]{.greek-added} ε[ν]{.unclear} τη οδω τ[ι]{.greek-supplied}[ς]{.unclear} [μ]{.greek-supplied}[ει]{.unclear}ζ[ω]{.unclear}ν[9:34]{.aside}

και κ[αθ]{.unclear}ι[σ]{.unclear}α[ς]{.unclear} [εφωνησεν]{.greek-omitted} [εφων[η]{.unclear}σε]{.greek-added} του[ς]{.unclear} [δωδεκα]{.greek-omitted} [[ι[β]{.unclear}]{.greek-abbr}]{.greek-added} κα[ι]{.unclear} λε[γει]{.unclear} [αυτοις]{.greek-supplied} [ει]{.greek-supplied} [τις]{.greek-supplied} [θελ]{.unclear}ει πρωτος [ει]{.greek-supplied}ναι εστ[α]{.unclear}[ι]{.greek-supplied} πα[ν]{.greek-supplied}[των]{.unclear} [εσ]{.unclear}χ[α]{.greek-supplied}τος κ[αι]{.unclear} [πα]{.greek-supplied}[ν]{.unclear}τ[ω]{.unclear}ν [δι]{.unclear}α[κ]{.unclear}ον[ος]{.unclear}[9:35]{.aside}

[και]{.greek-supplied} λα[βω]{.unclear}ν [παιδιον]{.unclear} εστησεν αυτο εν μεσω αυτ[ω]{.unclear}ν [κα]{.unclear}ι ε[ν]{.unclear}αγ[κ]{.unclear}αλισ[αμε]{.unclear}νο[ς]{.unclear} [αυτο]{.greek-omitted} [[αυτ]{.unclear}ω]{.greek-added} ε[ιπεν]{.unclear} [αυ]{.unclear}το[ις]{.unclear}[9:36]{.aside}

ος εα[ν]{.unclear} [εν]{.greek-omitted} [ε[κ]{.unclear}]{.greek-added} [τ[ω]{.unclear}ν]{.greek-added} [πα[ι]{.unclear}διων]{.greek-added} [των]{.unclear} [τ]{.unclear}ο[ι]{.unclear}ουτω[ν]{.unclear} [παιδιων]{.greek-omitted} δε[ξ]{.unclear}η[ται]{.greek-supplied} επι τ[ω]{.unclear} ονο[ματι]{.unclear} μου [εμε]{.unclear} δεχετ[αι]{.unclear} [και]{.greek-supplied} ο[ς]{.unclear} εαν [ε]{.unclear}με δεξη[τ]{.unclear}αι ου[κ]{.unclear} ε[με]{.unclear} [δε]{.greek-supplied}χετ[αι]{.unclear} [α]{.unclear}λλα τον απ[ο]{.unclear}στ[ει]{.unclear}λαντα με[9:37]{.aside}

απεκριθη δε αυτω [ιωαννης]{.greek-omitted} [ο]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} λεγων διδασκαλε ειδομεν τινα [εν]{.greek-added} τω ονοματι σου [εκβαλλοντα]{.greek-omitted} [εκβαλλωντα]{.greek-added} δαιμονια ο[ς]{.unclear} ουκ [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} ημιν και εκωλυσαμεν αυτον οτι [ουκ]{.greek-omitted} [ετι]{.greek-added} [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καθ υμων [υπερ]{.greek-omitted} [α]{.greek-added} [υμων]{.greek-omitted} [ημων]{.greek-added} εστιν[9:40]{.aside}

ος γαρ αν ποτιση υμας [ποτηριον]{.greek-omitted} [ποτερον]{.greek-added} υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων εις εμε καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} [αυτω]{.greek-omitted} μαλλον ει περικειται [μυλικος]{.greek-added} λιθος [επι]{.greek-added} [μυλικος]{.greek-omitted} [περι]{.greek-omitted} τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιση]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την [γενναν]{.greek-added} [γεενναν]{.corr} [τουτου]{.greek-added} [πυρος]{.greek-added} εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [κωληξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν [ο]{.greek-omitted} οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} [μονοφθαλμον]{.greek-omitted} [μονοφθαλμος]{.greek-added} εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμου[ς]{.unclear} εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ [αυτων]{.greek-omitted} ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια [αλι]{.greek-omitted} αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο [αρτυσετε]{.greek-omitted} [αρτυσεται]{.greek-added} εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας [δια]{.greek-omitted} [εις]{.greek-added} [του]{.greek-omitted} [το]{.greek-added} περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και [ω]{.unclear}ς [ειωθει]{.greek-omitted} [ειωθη]{.greek-added} παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [μωσης]{.greek-omitted} [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

[ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και [προσκολληθησεται]{.greek-omitted} [προσκολλυθησεται]{.greek-added} προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα μια σαρξ[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} επηρω[τ]{.unclear}η[σ]{.unclear}αν αυτον[10:10]{.aside}

και λεγει αυτοις ος ε[αν]{.unclear} απολυσ[η]{.unclear} την γυναικα αυτου και [γαμηση]{.greek-omitted} [γαμ[η]{.unclear}σει]{.greek-added} [αλλη]{.unclear}ν μ[ο]{.unclear}ιχαται επ αυτην[10:11]{.aside}

και εαν [γυνη]{.greek-omitted} [[αυτη]{.greek-supplied}]{.greek-added} [α]{.unclear}πολυση τον ανδρα αυτης και γ[αμ]{.unclear}ηθη α[λλω]{.unclear} μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται [επετιμων]{.greek-omitted} [επετημων]{.greek-added} τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλε[ι]{.unclear}α του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ευλογησεν]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη [φονευσης]{.greek-omitted} [μη]{.greek-omitted} κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ε[ι]{.unclear}πεν αυτω διδασκαλε τα[υ]{.unclear}τα πα[ν]{.unclear}τα [εφυλαξαμην]{.greek-omitted} [εφυλαμην]{.greek-added} εκ νεοτ[η]{.unclear}τος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψα[ς]{.unclear} αυτω ηγαπησεν [αυτον]{.greek-omitted} [αυτω]{.greek-added} και ειπεν α[υ]{.unclear}τω εν σοι υστερει υπαγε οσα [εχεις]{.greek-omitted} [[ε]{.greek-supplied}χοις]{.greek-added} πωλησον και δος πτω[χοις]{.unclear} [κα]{.unclear}ι εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις [αυτ[ως]{.unclear}]{.greek-added} [αυτου]{.corr} πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} παλιν [αποκριθεις]{.greek-omitted} λεγει αυτοις τεκνα πως δυσκολον εστιν τους πεποιθοτας επι [χρημασιν]{.greek-omitted} [τα]{.greek-added} [χρηματα]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [τρυπηματος]{.greek-added} [της]{.greek-omitted} [τρυμαλιας]{.greek-omitted} [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} [του]{.greek-added} αδυνατον αλλ ου παρα [τω]{.greek-added} [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν [οικιαν]{.greek-omitted} [οικιας]{.greek-added} η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} του ευαγγελιου[10:29]{.aside}

εαν μη λαβη [εκατονπ]{.greek-added} [εκατονταπλ[α]{.unclear}σιονα]{.corr} νυν εν τω καιρω τουτω οικιας [και]{.greek-omitted} αδελφους [και]{.greek-omitted} αδελφας [και]{.greek-omitted} [μητερας]{.greek-abbr} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις [τα]{.greek-added} ιεροσολυμα και ην προαγων [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ηρξατο αυτοις [λεγειν]{.greek-omitted} [λεγων]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τα μελλοντα [αυτω]{.greek-omitted} [αυτοις]{.greek-added} συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και [ο]{.corr} υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και εμπαιξουσιν [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και [προσπορευονται]{.greek-omitted} [προπορευονται]{.greek-added} αυτω ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οι υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα [ο]{.greek-omitted} [οσα]{.greek-added} εαν αιτησωμεν [ποιησης]{.greek-omitted} [ποιησεις]{.greek-added} ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε [ποιησαι]{.greek-omitted} [ποιησομαι]{.greek-added} [με]{.greek-omitted} υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε [πιειν]{.greek-omitted} το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριευσουσιν]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν [εσται]{.greek-omitted} [υμων]{.greek-omitted} διακονος[10:43]{.aside}

και ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} υμων [γενεσθαι]{.greek-omitted} [γενεσθω]{.greek-added} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και [οχλου]{.greek-omitted} [οχλο[ο]{.unclear}]{.greek-added} ικανου υιο[ς]{.unclear} τιμαιου βαρτιμαιος ο τυφλος [εκαθητο]{.greek-omitted} [εκα[θ]{.unclear}οιτο]{.greek-added} [παρα]{.greek-omitted} [περι]{.greek-added} την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος [εστιν]{.greek-omitted} [εστι]{.greek-added} ηρξατο κραζειν και λεγειν ο υ[ι]{.unclear}ος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλ[ο]{.unclear}ι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υι[ε]{.unclear} [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στ[α]{.unclear}ς ο [ιησους]{.greek-abbr} ειπε[ν]{.unclear} [αυτον]{.greek-omitted} [αυτω]{.greek-added} φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} [το]{.unclear}ν τυφλον λεγοντες αυτω θαρσει [ε]{.unclear}γειραι [φωνει]{.greek-omitted} [σε]{.greek-omitted} [φωνη]{.greek-added} [σαι]{.greek-added}[10:49]{.aside}

ο δε αποβαλων το [ι]{.unclear}ματιον αυτ[ο]{.unclear}υ [α]{.unclear}ναστας [ηλθεν]{.greek-omitted} [[η]{.unclear}λ[θ]{.unclear}ε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθ[ε]{.unclear}ις λ[εγει]{.unclear} αυτω [ο]{.unclear} [ιησους]{.greek-abbr} τι θελ[ε]{.unclear}ις ποιησω σοι ο δε τυφλος ειπ[ε]{.unclear}ν αυτω ραβ[βουνι]{.unclear} [ι]{.unclear}να [α]{.unclear}ναβλεψω[10:51]{.aside}

ο δ[ε]{.unclear} [ιησους]{.greek-abbr} ειπεν αυτ[ω]{.unclear} υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανε[ψ]{.unclear}]{.greek-added} [ανεβλεψεν]{.greek-omitted} [[ανεβλε[ψ]{.unclear}ε]{.corr}]{.greek-added} και ηκ[ο]{.unclear}λουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

[και]{.corr} λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον [δεδεμενον]{.greek-omitted} [δεμενον]{.greek-added} εφ ον [ουδεπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκεν]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

[και]{.greek-omitted} εαν τις υμιν ειπη τι ποιειτε τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρ[ε]{.unclear}ιαν εχει και ευθεως αυτον [α]{.unclear}ποστελλ[ε]{.unclear}ι ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ε[ν]{.unclear}ετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επ[ε]{.unclear}βαλον αυτω τα ιματια αυτων και εκαθισεν επ αυτω[11:7]{.aside}

πολλ[οι]{.greek-supplied} δε τα ιματια αυτων εστρ[ω]{.unclear}σαν εις την οδον αλλοι δε στ[ο]{.unclear}ιβαδας εκοπτον εκ των δενδρων και εστρωννυον εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημε[νος]{.unclear} ο ερχ[ο]{.greek-supplied}μενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλ[ο]{.greek-supplied}γ[η]{.greek-supplied}μενη η ερχομενη β[α]{.unclear}σιλ[εια]{.unclear} ε[ν]{.unclear} ονοματι [κυριου]{.greek-abbr} [τ]{.unclear}ου [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσανν[α]{.unclear} ε[ν]{.unclear} τοι[ς]{.unclear} υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα [ο]{.greek-omitted} [ιησους]{.greek-omitted} και [ε]{.unclear}ις το ιερον και περιβλεψαμενος [παντα]{.greek-omitted} [π[αν]{.unclear}τας]{.greek-added} οψιας ηδη ουσης της [ω]{.unclear}ρας εξηλθεν ει[ς]{.unclear} βη[θ]{.unclear}ανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον [εξελθοντων]{.greek-omitted} [ε[ξελ]{.unclear}θοντες]{.greek-added} αυτων [α]{.unclear}πο βηθανια[ς]{.unclear} [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην μ[α]{.unclear}[κροθεν]{.greek-supplied} εχουσαν φυλλα ηλθεν [ινα]{.greek-added} [ει]{.greek-omitted} [αρα]{.greek-omitted} ε[υρ]{.unclear}ησ[ει]{.unclear} [τι]{.greek-omitted} [καρπον]{.greek-added} εν αυτη [κα]{.unclear}ι [ελ]{.unclear}θων [επ]{.unclear} [αυ]{.greek-supplied}την ουδεν [ε]{.unclear}υρ[ε]{.unclear}ν [ει]{.unclear} [μη]{.unclear} [φ]{.greek-supplied}υ[λλ]{.unclear}α [ου]{.greek-supplied} [γαρ]{.greek-supplied} ην [κ]{.unclear}αιρος συκων[11:13]{.aside}

[και]{.greek-supplied} [αποκριθεις]{.greek-supplied} [ο]{.greek-supplied} [ιησους]{.greek-abbr} ειπεν αυτη [μηκετι]{.unclear} [ε]{.unclear}κ [σ]{.unclear}[ου]{.greek-supplied} εις τον αιωνα μηδει[ς]{.unclear} [κα]{.unclear}ρ[πον]{.greek-supplied} [φαγοι]{.greek-supplied} και ηκουο[ν]{.unclear} οι μαθη[ται]{.unclear} αυτ[ο]{.unclear}υ[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας καθεδρας των πωλουντων τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και εδιδασκεν λεγων αυτοις ου γεγραπται οτι ο οικος μου οικο[ς]{.unclear} προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι γραμματεις και οι αρχιερεις και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε [εγενετο]{.greek-omitted} [εγινετο]{.greek-added} εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρο[ς]{.unclear} λεγει αυτω ραββι ιδε η συκη ην κατηρασω εξηρανται[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα πιστευση οτι [α]{.greek-omitted} [ο]{.greek-added} λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

[και]{.greek-added} δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθε]{.greek-added} πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα [ο]{.greek-added} [και]{.corr} ο [πατηρ]{.greek-abbr} [ημων]{.greek-added} [υμων]{.corr} ο εν τοις [ουρανοις]{.greek-abbr} [αφη]{.greek-omitted} [αφηση]{.greek-added} υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν τοις ουρανοις αφησει τα παραπτωματα υμων[11:26]{.aside}

και [ερχονται]{.greek-omitted} [ερχεται]{.greek-added} παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και [αποκριθητε]{.greek-omitted} [αποκριθειτε]{.greek-added} μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} [αποκριθητε]{.greek-omitted} [μοι]{.greek-omitted}[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[11:31]{.aside}

[αλλ]{.greek-omitted} [εαν]{.greek-added} [δε]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον [λαον]{.greek-omitted} [οχλον]{.greek-added} [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ ειχον τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} [τω]{.greek-omitted} [τον]{.greek-added} [ιησου]{.greek-omitted} [[ιησουν]{.greek-abbr}]{.greek-added} ουκ οιδαμεν [και]{.greek-omitted} ο [δε]{.greek-added} [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [αποστελει]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα [παρα]{.greek-omitted} [απο]{.greek-added} των [γε]{.greek-added} [γεωργων]{.greek-omitted} [ωργων]{.greek-added} λα[β]{.unclear}η [α]{.unclear}πο του καρπου του αμπελω[ν]{.unclear}ος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν [κ]{.greek-supplied}[αι]{.unclear} απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλαν]{.greek-added} προς αυτο[υ]{.unclear}ς αλλον δουλον κακεινον λιθοβολ[η]{.unclear}σαντες εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον απεστειλεν κακεινον απεκτειναν και πολλους αλλο[υ]{.unclear}[ς]{.greek-supplied} τους μεν δερο[ν]{.unclear}τες τους δε [αποκτενοντες]{.greek-omitted} [αποκτεννοντες]{.greek-added}[12:5]{.aside}

ετι ουν ενα υ[ι]{.unclear}ον εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απε[στε]{.unclear}ιλε]{.greek-added} [κ]{.greek-supplied}αι αυτον προς αυτους εσχατο[ν]{.unclear} [λ]{.unclear}εγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμ[εν]{.unclear} αυτον και ημων εσται η κληρονο[μ]{.unclear}ια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

[τι]{.greek-omitted} [ουν]{.greek-omitted} [ποιησει]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [του]{.greek-omitted} [αμπελωνος]{.greek-omitted} [ελευσεται]{.greek-omitted} [ελευσετε]{.greek-added} και απολεσε[ι]{.unclear} τους γεωργους και δωσει τον [αμ]{.unclear}πελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκι[μ]{.unclear}ασ[α]{.unclear}ν ο[ι]{.greek-supplied} οικοδομουντες ουτος [εγ]{.unclear}εν[η]{.unclear}[θη]{.greek-supplied} ει[ς]{.unclear} κεφαλην γωνιας[12:10]{.aside}

παρ[α]{.unclear} [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυ[μασ]{.unclear}[τ]{.greek-supplied}η εν οφθαλμοις ημων[12:11]{.aside}

και εζητου[ν]{.unclear} [α]{.unclear}υτον κρατησαι και εφοβηθ[ησ]{.greek-supplied}[α]{.unclear}ν τον οχλον εγνωσαν γαρ [ο]{.unclear}τ[ι]{.unclear} πρ[ο]{.unclear}ς αυτους την παραβολην [ει]{.unclear}πεν [κ]{.unclear}αι αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινα[ς]{.unclear} των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδ[α]{.greek-supplied}σκαλε οιδαμεν οτι αληθης ει [κ]{.unclear}[αι]{.greek-supplied} ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου [γ]{.unclear}[α]{.greek-supplied}[ρ]{.unclear} βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ [ε]{.unclear}π αληθειας την οδον [το]{.unclear}υ [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [κη]{.unclear}νσον [κ]{.unclear}[α]{.greek-supplied}ισαρι δουναι η ου [δωμ[εν]{.unclear}]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδω[ς]{.unclear} αυτων την υ[π]{.unclear}ο[κρ]{.unclear}ισιν ειπε[ν]{.unclear} αυτοις τι [με]{.greek-omitted} πειραζετε φερετε μοι δηναριον ινα ιδ[ω]{.unclear}[12:15]{.aside}

οι δε ηνεγκαν και λεγε[ι]{.greek-supplied} [αυ]{.greek-supplied}τοις τινος η εικων αυτη και η επιγρα[φ]{.unclear}η οι δε ειπον αυτω κα[ι]{.unclear}σαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυ[τ]{.unclear}οις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} [κ]{.unclear}αι [εθ]{.unclear}αυμ[α]{.unclear}σαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και [καταλιπη]{.greek-omitted} [καταλειπει]{.greek-added} γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και εξαναστηση σπερμα τω αδελ[φω]{.unclear} αυτου[12:19]{.aside}

επτα α[δ]{.unclear}ελφοι ησαν και ο πρωτος ελαβεν γυναικα και αποθνησκων ουκ αφηκεν σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν και ουδε αυτος αφηκεν [σπ]{.unclear}ερμα και ο τριτος [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added}[12:21]{.aside}

και ελαβον αυτην οι επτα και ου[κ]{.unclear} αφηκαν σπερμα εσχατη παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλ[α]{.unclear}νασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε γαμισκονται αλλ εισιν ως αγγελοι οι εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω μωσεως επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} νεκρων αλλα [ζωντων]{.greek-added} [θεος]{.greek-abbr} [ζωντων]{.greek-omitted} υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων εις των γραμματεων ακουσας αυτων συζητουντων ειδως οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη παντων εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω οτι πρωτη παντων των εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της [[διαν]{.unclear}]{.greek-added} ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως σεαυτον μειζων τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας [ειπας]{.greek-omitted} [ειπες]{.greek-added} οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και πρωτοκλισιας εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον [και]{.greek-omitted} [πολλοι]{.greek-omitted} [πλουσιοι]{.greek-omitted} [εβαλλον]{.greek-omitted} [πολλα]{.greek-omitted}[12:41]{.aside}

και ελθουσα μια χηρα πτωχη εβαλεν λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων βεβληκεν των βαλλοντων εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη [καταλυθη]{.greek-omitted} [καταλυθησεται]{.greek-added}[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ [ι]{.unclear}διαν πετρος και ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και ανδρεας[13:3]{.aside}

ειπε [ημιν]{.greek-omitted} [υμιν]{.greek-added} ποτε ταυτα εσται και τι το σημειον οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις [αυ]{.unclear}τοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι αρχαι ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους παραδωσουσιν γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγουσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [μεριμνατε]{.greek-added} τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν [αυτους]{.greek-omitted} [αυτον]{.greek-added}[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε [ιδητε]{.greek-omitted} [ηδητε]{.greek-added} το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο αναγινωσκων [νοειτω]{.greek-omitted} [νοειτο]{.greek-added} τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε [εισελθετω]{.greek-omitted} [εισελθητω]{.greek-added} [αραι]{.greek-omitted} [τι]{.greek-omitted} [τις]{.greek-added} εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το [ιματιον]{.greek-omitted} [ιματια]{.greek-added} αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ται[ς]{.unclear} ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου γεγονεν [τοιαυτη]{.greek-omitted} απ αρχης κτισεως [ης]{.greek-omitted} [ησαν]{.greek-added} εκτισεν ο [θεος]{.greek-abbr} [[ω]{.unclear}]{.greek-added} [εως]{.corr} του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [ο]{.greek-added} [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβ[ω]{.unclear}σε]{.greek-added} τας ημερας[13:20]{.aside}

τοτε εαν τις υμιν [ειπη]{.greek-omitted} [ειποι]{.greek-added} ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς [το]{.greek-omitted} [τω]{.greek-added} αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ [εν]{.greek-omitted} εκειναις ταις ημεραις μετα [την]{.greek-omitted} θλιψιν [οτι]{.greek-added} [εκεινην]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [αι]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν [νεφελαις]{.greek-omitted} [εφελαις]{.greek-added} μετα δυναμεως [πολλης]{.greek-omitted} και δοξης[13:26]{.aside}

και [τοτε]{.greek-omitted} [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου και [επισυναξει]{.greek-omitted} [επισυναξη]{.greek-added} τους εκλεκτους [αυτου]{.greek-omitted} εκ των τεσσαρων ανεμων απ ακρου [γης]{.greek-omitted} [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} εως ακρου [ουρανου]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης [ηδη]{.greek-omitted} ο κλαδος απαλος γενηται και [εκφυη]{.greek-omitted} τα φυλλα [εκφυει]{.greek-added} γινωσκετε οτι εγγυς το θερος [εστιν]{.greek-omitted} [εστι]{.greek-added}[13:28]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις οταν ταυτα ιδητε [γινομενα]{.greek-omitted} [γενωμενα]{.greek-added} γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.unclear} [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [οι]{.greek-omitted} εν [ουρανω]{.greek-abbr} ουδε ο υιος ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον [αυτου]{.greek-omitted} και τω θυρωρω [ενετειλατο]{.greek-omitted} [ενετειλλατο]{.greek-added} ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η [μεσονυκτιου]{.greek-omitted} [μεσονυκτιον]{.greek-added} η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη [υμας]{.greek-omitted} [ημας]{.greek-added} καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις π[ω]{.unclear}ς αυτον εν δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον [δε]{.greek-omitted} [γαρ]{.greek-added} μη εν τη εορτη [μηποτε]{.greek-omitted} [ινα]{.greek-added} [μη]{.greek-added} θορυβος [εσται]{.greek-omitted} [γενηται]{.greek-added} του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης πολυτελους και [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τινες [αγανακτουντες]{.greek-omitted} προς εαυτους [αγανακτουντες]{.greek-added} και λεγοντες εις τι η απωλεια αυτη του μυρου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[14:4]{.aside}

ηδυνατο γαρ τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι [τοις]{.greek-omitted} πτωχοις και ενεβριμωντο [αυτη]{.greek-omitted} [αυτου]{.greek-added}[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον [γαρ]{.greek-added} εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε αυτους ευ [ποιησαι]{.greek-omitted} [ποιειν]{.greek-added} εμε δε ου παντ[ο]{.unclear}τε εχετε[14:7]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιει]{.greek-added} [προελαβεν]{.greek-omitted} [π[ρ]{.unclear}οελαβε]{.greek-added} μυρισαι [μου]{.greek-omitted} το σωμα [μου]{.greek-added} εις τον ενταφιασμον[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου [εαν]{.greek-omitted} [αν]{.greek-added} κηρυχθη το ευαγγε[λι]{.unclear}ον τουτο εις [ολ[η]{.unclear}ν]{.greek-added} [ολον]{.corr} τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} [ιδου]{.greek-added} ιουδας ο ισκαριωτης εις των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παρ[α]{.unclear}δω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλαντο]{.greek-omitted} [επηγγειλλαντο]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} αργυριον δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων ο[τε]{.unclear} το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες [ε]{.unclear}τοιμασ[ω]{.unclear}μεν [σοι]{.greek-added} ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λε[γ]{.unclear}ει [α]{.unclear}υτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδ[α]{.unclear}τος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω [ο]{.unclear}ικοδεσ[π]{.unclear}οτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το [καταλυμα]{.greek-omitted} [καταλυμμα]{.greek-added} οπου το πασχ[α]{.unclear} μετα των μαθητων μου φαγω[14:14]{.aside}

[και]{.unclear} [α]{.unclear}υτος υμιν [δειξει]{.greek-omitted} [ανωγεον]{.greek-omitted} [δειξη]{.greek-added} [αν[α]{.unclear}γ[α]{.unclear}ιον]{.greek-added} μ[ε]{.unclear}γα [ε]{.unclear}στρωμενον [ετοιμον]{.greek-omitted} εκει ετοιμασατε [η]{.unclear}μιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και [ητοιμασ[―]{.gap}ν]{.greek-added} [ητοιμασαν]{.corr} το πασχα[14:16]{.aside}

και οψιας γενομενης ερχετ[α]{.unclear}ι μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου ει[ς]{.unclear} το τρυβλιον[14:20]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ [εν]{.greek-added} [εγεννηθη]{.corr} ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου [το]{.greek-omitted} της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και [λεγει]{.greek-omitted} [ελεγεν]{.greek-added} αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν η δις αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε εκπερισσου ελεγεν μαλλον εαν με δεη συναποθανειν σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και [παραλαμβανει]{.greek-omitted} [παραλαμλαμβανει]{.greek-added} τον πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και [λεγει]{.greek-omitted} [λεγειν]{.greek-added} αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον απ εμου τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ ηδεισαν τι αυτω αποκριθωσιν[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των [[ιβ]{.greek-abbr}]{.greek-added} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων [παρα]{.greek-omitted} [περι]{.greek-added} των αρχιερεων και [των]{.greek-omitted} γραμματεων και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγε[τ]{.unclear}ε ασφαλως[14:44]{.aside}

και ελθων [ευθε[―]{.gap}]{.greek-added} [ευθεως]{.corr} προσελθων αυτω λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν επαισεν τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και [ισαι]{.greek-omitted} [ησαι]{.greek-added} αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο υιος του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο [δε]{.greek-omitted} [δι]{.greek-added} αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσ[α]{.unclear}τε της [φλασφημιας]{.greek-added} [βλασφημιας]{.corr} τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφ[ι]{.unclear}ζειν αυτον και λεγειν αυτω προφητευσον και οι υπηρεται ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} επισταμαι τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ εφωνησεν[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοι[α]{.unclear}ζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και ομνυναι οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ εφωνησεν και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα[15:3]{.aside}

ο δε πιλατο[ς]{.unclear} παλιν επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των σ[υ]{.unclear}στασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λ[ε]{.unclear}γων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

εγινωσκεν γαρ οτι δια [φθονον]{.greek-omitted} [φονο[ν]{.unclear}]{.greek-added} παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [σταυρωσον]{.greek-omitted} [[στρωσον]{.greek-abbr}]{.greek-added} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε περισσοτερως εκραξαν [σταυρωσον]{.greek-omitted} [[στρωσον]{.greek-abbr}]{.greek-added} αυτον[15:14]{.aside}

ο δε [πιλατος]{.greek-omitted} [πιλατο]{.greek-added} βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και παρεδωκεν τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπα[ζ]{.unclear}εσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ [α]{.unclear}γρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και [φερουσ[ν]{.unclear}]{.greek-added} [φερουσιν]{.corr} αυτον επι [γολγοθα]{.greek-omitted} [γολγοθαν]{.greek-added} τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον [κρανι[ω]{.unclear}]{.greek-added} [κρανιου]{.corr} τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ ελαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου [βαλλοντες]{.greek-omitted} [βαλοντες]{.greek-added} κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες [τας]{.greek-added} τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [καταβατω]{.greek-added} απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι συνεσταυρωμενοι αυτω [ωνειδιζον]{.greek-omitted} [ονειδιζον]{.greek-added} αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη ωρα τη [ενατη]{.greek-omitted} [εννατη]{.greek-added} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λειμα]{.greek-added} σαβαχθανι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος υιος ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην και μαρια η μαγδαληνη και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

ηλθεν ιωσηφ ο απο αριμαθαιας ε[υ]{.unclear}σχημων βουλευτης ος και αυτος ην πρ[οσ]{.unclear}δεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας εισηλθεν προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκεν και προσκαλεσαμενος τον [κε]{.unclear}ντυριωνα επηρωτησεν αυτ[ον]{.unclear} ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον ενειλησεν τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και προσεκυλισεν λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυ[τ]{.unclear}ου και τω πετρω οτι προαγει υμ[α]{.unclear}ς εις την γαλιλαιαν εκει [α]{.unclear}υτον οψε[σ]{.unclear}θε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι [ταχυ]{.greek-added} ε[φ]{.unclear}υγον απο του [μνημ[―]{.gap}]{.greek-added} [μνημειου]{.corr} ειχεν δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη [πορευθησα]{.greek-added} [πορευθεισα]{.corr} [απηγγειλεν]{.greek-omitted} [απηγγελεν]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και ωνειδισεν την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον [εγηγερμενον]{.greek-omitted} [εγειγερμενον]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} [καιναις]{.greek-omitted} [κεν[αι]{.unclear}ς]{.greek-added}[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τ[ι]{.unclear} πιωσιν ου μη αυτους βλ[αψη]{.greek-supplied} επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

