---
title: "Collation of Byz^RP^ vs 30749 (749)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 749 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30749).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 749                                   	| λογος                              	|
| 749 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 749 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 749               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 749                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 749 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 749                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 3

[ε]{.greek-supplied}γω μεν βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον [αυτου]{.greek-omitted} εις την αποθηκην [αυτου]{.greek-added} το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} διεκωλυεν αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον αφες [αρτι]{.greek-supplied} [ο]{.greek-supplied}[υ]{.unclear}τως γαρ πρεπον εστιν ημιν πληρωσαι πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και βαπτισθεις ο [ιησους]{.greek-abbr} ανεβη ευθυς απο του υδατος [κα]{.unclear}ι ιδου ανεωχθησαν αυτω οι [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} καταβαινον ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} ο υιος μου ο αγαπητος εν ω ευδοκησα[3:17]{.aside}

### Chapter 4

[τ]{.greek-supplied}οτε ο [ιησους]{.greek-abbr} ανηχθη εις την ερημον υπο του [πνευματος]{.greek-abbr} πειρασθηναι υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας τεσσαρακοντα και νυκτας τεσσαρακοντα υστερον [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[4:2]{.aside}

### Chapter 7

και εγενετο οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[7:29]{.aside}

### Chapter 8

καταβαντι δε αυτω απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου λεπρος ελθων [προσεκυνει]{.greek-omitted} [προσεκυνη]{.greek-added} αυτω λεγων [κυριε]{.greek-abbr} εαν θελης δυνασαι με καθαρισαι[8:2]{.aside}

και εκτεινας την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω καθαρισθητι και ευθεως εκαθαρισθη αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι ειπης [αλλα]{.greek-omitted} [αλλ]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} το δωρον ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μ[ω]{.unclear}σης εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε αυτω εις καπερναουμ προσηλθεν αυτω εκατονταρχος παρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου βεβληται εν τη οικια παραλυτικος δεινως βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} [εθαυμασεν]{.greek-omitted} [εθαυμασε]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις ακολουθουσιν αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[8:10]{.aside}

[λ]{.greek-supplied}εγω δε υμιν οτι πολλοι απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και ανακλιθησονται μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω εκατονταρχη υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη [και]{.greek-added} [υποστρεψας]{.greek-added} [ο]{.greek-added} [εκατονταρχος]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [αυτου]{.greek-added} [εν]{.greek-added} [αυτη]{.greek-added} [τη]{.greek-added} [ωρα]{.greek-added} [ευρε]{.greek-added} [τον]{.greek-added} [παιδα]{.greek-added} [υγιαινοντα]{.greek-added}[8:13]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} την πενθεραν αυτου [βεβλημενην]{.greek-omitted} [βεβλημμενην]{.greek-added} και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα [πνευματα]{.greek-abbr} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι [αυτον]{.greek-omitted} [αυτων]{.greek-added} εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν απερχη[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κλιναι]{.greek-added}[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι [τον]{.greek-omitted} [των]{.greek-added} [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις το πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων αυτος δε [εκαθευδεν]{.greek-omitted} [εκαθευδε]{.greek-added}[8:24]{.aside}

και προσελθοντες οι μαθηται ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι τοτε εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

και ελθοντι αυτω εις το περαν εις την χωραν των γεργεσηνων υπηντησαν αυτω δυο δαιμονιζομενοι [ε]{.unclear}κ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και σοι [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων πολλων βοσκομενη[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει [εκβαλλεις]{.greek-omitted} [εκβαλεις]{.greek-added} ημας επιτρεψον ημιν απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου [ωρμησεν]{.greek-omitted} [ωρμησε]{.greek-added} πασα η αγελη των χοιρων κατα του κρημνου εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις [συναντησιν]{.greek-omitted} [υπαντησιν]{.greek-added} [τω]{.greek-omitted} [του]{.greek-added} [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις το πλοιον [διεπερασεν]{.greek-omitted} [διεπερασε]{.greek-added} και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω παραλυτικω θαρσει τεκνον [αφεωνται]{.greek-omitted} [αφενται]{.greek-added} σοι αι [αμαρτιαι]{.greek-omitted} [αμαριαι]{.greek-added} σου[9:2]{.aside}

και ιδου τινες των γραμματεων ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και [ιδων]{.greek-omitted} [ειδως]{.greek-added} ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις ενθυμεισθε πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν ευκοπωτερον ειπειν αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν εγειραι και περιπατει[9:5]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

και παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} καθημενον επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθητα[ι]{.greek-supplied}ς αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων εσθιει ο διδασκαλος υμων[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι [ισχυοντες]{.greek-omitted} [υγιαινοντες]{.greek-added} ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν ελεον θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε μαθηται σου ου νηστευουσιν[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος πενθειν εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

ουδεις δε επιβαλλει επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και χειρον σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος εκχειται και οι ασκοι απολουνται αλλα βαλλουσιν οινον νεον εις ασκους καινους και αμφοτεροι συντηρουνται[9:17]{.aside}

ταυτα αυτου λαλουντος αυτοις ιδου αρχων [εις]{.greek-omitted} [τις]{.greek-added} ελθων προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν αλλα ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον αψωμαι του [κρασπεδου]{.greek-added} [του]{.greek-added} ιματιου αυτου [σωθησομαι]{.greek-omitted} [σωθισομαι]{.greek-added}[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} θαρσει θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και εσωθη η γυνη απο της ωρας [εκεινης]{.greek-omitted} [εκυνης]{.greek-added}[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του [αρχοντος]{.greek-omitted} [αρχισυναγωγου]{.greek-added} και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισελθων [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

ελθοντι δε [αυτω]{.greek-added} εις την οικιαν προσηλθον αυτω οι τυφλοι [και]{.unclear} [λεγει]{.unclear} [αυτοις]{.unclear} [ο]{.unclear} [[ιησους]{.greek-abbr}]{.unclear} [πισ]{.unclear}τευετε οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων αυτων λεγων κατα την πιστιν υμων γενηθητω υμιν[9:29]{.aside}

και [ανεωχθησαν]{.greek-omitted} [ηνεωχθησαν]{.greek-added} αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες διεφημισαν αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες ουδεποτε εφανη ουτως εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε φαρισαιοι ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολεις πασας και τας κωμας διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[9:35]{.aside}

[ι]{.greek-supplied}δων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν [εσκυλμενοι]{.greek-omitted} [εκλελυμενοι]{.greek-added} και ερριμμενοι [ωσει]{.greek-omitted} [ως]{.greek-added} προβατα μη εχοντα ποιμενα[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως εκβαλη εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

και προσκαλεσαμενος τους δωδεκα μαθητας αυτου εδωκεν αυτοις εξουσιαν [κατα]{.greek-added} [πνευματων]{.greek-abbr} ακαθαρτων ωστε εκβαλλειν αυτα και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

[τ]{.unclear}ων δε δωδεκα αποστολων τα ονοματα [εστιν]{.greek-omitted} [εστι]{.greek-added} ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου [ι]{.greek-supplied}ακωβος ο του ζεβεδαιου και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και [λεββαιος]{.greek-omitted} [λεβαιος]{.greek-added} ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο κανανιτης και ιουδας [ο]{.greek-added} ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους δωδεκα απεστειλεν ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν σαμαρειτων μη εισελθητε[10:5]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} δε μαλλον προς τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρυσσετε λεγοντες οτι ηγγικεν η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας θεραπευετε λεπρους καθαριζετε δαιμονια εκβαλλετε δωρεαν ελαβετε δωρεαν [δοτε]{.greek-omitted} [δωτε]{.greek-added}[10:8]{.aside}

μη [κτησησθε]{.greek-omitted} [κτησεσθε]{.greek-added} χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε ραβδους αξιος γαρ ο εργατης της τροφης αυτου [εστιν]{.greek-omitted}[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις εν αυτη [αξιος]{.unclear} [εστιν]{.unclear} [κακει]{.unclear} μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν [ασπασασθε]{.greek-omitted} [ασπασασθαι]{.greek-added} αυτην[10:12]{.aside}

και εαν μεν η η οικια αξια [ελθετω]{.greek-omitted} [εισελθετω]{.greek-added} η ειρηνη υμων επ αυτην εαν δε μη η αξια η ειρηνη υμων προς υμας επιστραφητω[10:13]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της οικιας η της πολεως εκεινης [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον κονιορτον των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν ανεκτοτερον εσται γη σοδομων και [γομορρων]{.greek-omitted} [γομορρας]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων γινεσθε ουν φρονιμοι ως οι οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

[π]{.greek-supplied}ροσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις [αχθησεσθε]{.greek-omitted} [αχθη]{.greek-added} [σεσθε]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

[ο]{.greek-supplied}ταν δε παραδιδωσιν υμας μη [μεριμνησητε]{.greek-omitted} [μεριμνησετε]{.greek-added} πως η τι λαλησητε δοθησεται γαρ υμιν εν εκεινη τη ωρα τι λαλησετε[10:19]{.aside}

ου γαρ υμεις εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[10:22]{.aside}

οταν δε διωκωσιν υμας εν τη πολει ταυτη φευγετε εις την αλλην αμην γαρ λεγω υμιν ου μη τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο υιος του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης υπερ τον διδασκαλον [αυτου]{.greek-added} ουδε δουλος υπερ τον [κυριον]{.greek-abbr} αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα γενηται ως ο διδασκαλος αυτου και [ο]{.greek-omitted} [δουλος]{.greek-omitted} [τω]{.greek-added} [δουλω]{.greek-added} ως ο [κυριος]{.greek-abbr} αυτου ει τον οικοδεσποτην βεελζεβουλ [εκαλεσαν]{.greek-omitted} [απεκαλεσαν]{.greek-added} ποσω μαλλον τους [οικειακους]{.greek-omitted} [οικιακους]{.greek-added} αυτου[10:25]{.aside}

μη ουν φοβηθητε αυτους ουδεν γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} κεκαλυμμενον ο ουκ αποκαλυφθησεται και κρυπτον ο ου γνωσθησεται[10:26]{.aside}

ο λεγω υμιν εν τη σκοτια ειπατε εν τω φωτι και ο εις το ους [ακουετε]{.greek-omitted} [ακουσατε]{.greek-added} κηρυξατε επι των δωματων[10:27]{.aside}

και μη φοβεισθε απο των αποκτενοντων το σωμα την δε ψυχην μη δυναμενων αποκτειναι φοβηθητε δε μαλλον τον δυναμενον και την ψυχην και το σωμα απολεσαι εν γεεννη[10:28]{.aside}

ουχι δυο στρουθια ασσαριου πωλειται και εν εξ αυτων ου πεσειται επι την γην ανευ του [πατρος]{.greek-abbr} υμων[10:29]{.aside}

υμων δε και αι τριχες της κεφαλης πασαι ηριθμημεναι [εισιν]{.greek-omitted} [εισι]{.greek-added}[10:30]{.aside}

μη ουν φοβηθητε πολλων στρουθιων διαφερετε υμεις[10:31]{.aside}

πας ουν οστις ομολογησει εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[10:32]{.aside}

οστις δ αν αρνησηται με εμπροσθεν των [ανθρωπων]{.greek-abbr} αρνησομαι [καγω]{.greek-added} αυτον [καγω]{.greek-omitted} εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[10:33]{.aside}

μη νομισητε οτι ηλθον βαλειν ειρηνην επι την γην ουκ ηλθον βαλειν ειρηνην [α]{.greek-added} [αλλα]{.greek-omitted} [λλα]{.greek-added} μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και θυγατερα κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και εχθροι του [ανθρωπου]{.greek-abbr} οι [οικακοι]{.greek-added} [οικειακοι]{.greek-omitted} [[οικοιακοι]{.corr}]{.greek-added} αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος και ο φιλων υιον η θυγατερα υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:37]{.aside}

και ος [ου]{.corr} λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:38]{.aside}

[ο]{.unclear} ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

[ο]{.unclear} δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψεται[10:41]{.aside}

[κ]{.unclear}αι ος εαν ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις [πολεσιν]{.greek-omitted} [συναγωγαις]{.greek-added} αυτων[11:1]{.aside}

ο δε [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ακουσας εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-abbr} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε [ιωαννη]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται και κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τι εξηλθετε εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι εξηλθετε ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι εξηλθετε ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων μειζων [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} προεφητευσαν[11:13]{.aside}

και ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις [καθημενοις]{.greek-added} εν [τη]{.greek-added} [αγοραις]{.greek-omitted} [αγορα]{.greek-added} [καθημενοις]{.greek-omitted} και [προσφωνουσιν]{.greek-omitted} [προσφωνουσι]{.greek-added} τοις εταιροις αυτων[11:16]{.aside}

και λεγουσιν ηυλησαμεν υμιν και ουκ ωρχησασθε εθρηνησαμεν υμιν και ουκ εκοψασθε[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ [ιωαννης]{.greek-omitted} [ο]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο υιος του [ανθρωπου]{.greek-abbr} εσθιων και [πι]{.greek-added} [πινων]{.greek-omitted} [νων]{.greek-added} και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης [φιλος]{.greek-added} τελωνων [φιλος]{.greek-omitted} και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο ονειδιζειν [[ιησους]{.greek-abbr}]{.greek-added} τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χωραζιν]{.greek-added} ουαι σοι [βηθσαιδα]{.greek-omitted} [βησθαιδα]{.greek-added} οτι [ει]{.greek-omitted} εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι αν εν σακκω και σποδω [καθημεναι]{.greek-added} μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι ανεκτοτερον εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ η εως του [ουρανου]{.greek-abbr} [υψωθεισα]{.greek-omitted} [υψωθησα]{.greek-added} εως αδου καταβιβασθηση οτι ει εν σοδομοις εγενοντο αι δυναμεις αι γενομεναι εν σοι εμειναν αν μεχρι της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι γη σοδομων ανεκτοτερον εσται εν ημερα κρισεως η σοι[11:24]{.aside}

εν εκεινω τω καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι [ουτως]{.greek-omitted} [ουτος]{.greek-added} εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι παρεδοθη υπο του [πατρος]{.greek-abbr} μου και ουδεις επιγινωσκει τον υιον ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο υιος και [ω]{.greek-omitted} [ο]{.greek-added} εαν βουληται ο υιος αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι κοπιωντες και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και ευρησετε αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου χρηστος και το φορτιον μου ελαφρον [εστιν]{.greek-omitted} [εστι]{.greek-added}[11:30]{.aside}

### Chapter 19

[τοτε]{.greek-omitted} αποκριθεις ο πετρος ει[πεν]{.greek-supplied} [αυτω]{.greek-supplied} [ιδου]{.greek-supplied} [ημ]{.greek-supplied}[ει]{.unclear}ς [αφηκαμεν]{.greek-omitted} [αφικαμεν]{.greek-added} παντα και ηκο[λουθησαμεν]{.greek-supplied} [σοι]{.greek-supplied} [τι]{.greek-supplied} [α]{.unclear}ρα εσται ημιν[19:27]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυ[τοις]{.greek-supplied} [αμην]{.greek-supplied} [λεγω]{.greek-supplied} [υμιν]{.greek-supplied} οτι υμεις οι ακολουθησαντες [μοι]{.greek-supplied} [εν]{.greek-supplied} [τη]{.greek-supplied} [παλιγγενε]{.greek-supplied}σια οταν [καθιση]{.greek-omitted} [καθισει]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} [επι]{.greek-supplied} [θρονου]{.greek-supplied} [δοξης]{.greek-supplied} [α]{.unclear}υτου [καθισεσθε]{.greek-omitted} [καθησεσθε]{.greek-added} και υμεις επι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} [θρονους]{.greek-supplied} [κρινον]{.greek-supplied}τες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και [πας]{.greek-supplied} [ος]{.greek-omitted} [[οστις]{.greek-supplied}]{.greek-added} [αφηκεν]{.greek-supplied} [ο]{.greek-supplied}[ι]{.unclear}κιας η αδελφους η αδελφας [η]{.greek-supplied} [[πατερα]{.greek-abbr}]{.greek-supplied} [η]{.greek-supplied} [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν [του]{.greek-supplied} [ονο]{.greek-supplied}ματος μου εκατονταπλασιονα ληψεται και [ζωην]{.greek-supplied} [α]{.unclear}ιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρω[τοι]{.greek-supplied} εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[19:30]{.aside}

### Chapter 24

εαν ουν ει[π]{.unclear}[ωσιν]{.greek-supplied} [υμιν]{.greek-supplied} [ιδ]{.greek-supplied}ου εν τη ερημω [εστιν]{.greek-omitted} μη εξελθητε ιδου εν τοις τ[α]{.unclear}[μειοις]{.greek-supplied} [μη]{.greek-supplied} [πιστευ]{.greek-supplied}σητε[24:26]{.aside}

ωσ[π]{.unclear}[ερ]{.greek-supplied} [γαρ]{.greek-supplied} [η]{.greek-supplied} [αστρα]{.greek-supplied}πη εξερχεται απο ανατολων και φαι[νεται]{.greek-supplied} [εως]{.greek-supplied} [δυσμων]{.greek-supplied} ουτως εσται [και]{.greek-omitted} [η]{.greek-supplied} [παρουσ]{.greek-supplied}ια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου [γαρ]{.greek-omitted} εαν η το [πτωμα]{.greek-supplied} [εκει]{.greek-supplied} [συνα]{.greek-supplied}χθησονται [κ[αι]{.greek-supplied}]{.greek-added} [οι]{.greek-supplied} [αετοι]{.greek-supplied}[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται [και]{.greek-supplied} [η]{.greek-supplied} [σελη]{.greek-supplied}νη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} κ[αι]{.greek-supplied} [αι]{.greek-supplied} [δυνα]{.greek-supplied}μεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε κοψονται πασαι αι φυλαι της γης και οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον επι [των]{.greek-omitted} [τον]{.greek-added} νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και αποστελει τους αγγελους αυτου μετα σαλπιγγος φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξουσι]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-abbr} εως ακρων αυτων[24:31]{.aside}

[απο]{.greek-supplied} [δε]{.greek-supplied} [της]{.greek-supplied} [συκης]{.greek-supplied} μαθετε την παραβολην οτα[ν]{.unclear} [ηδη]{.greek-supplied} [ο]{.greek-supplied} [κλαδος]{.greek-supplied} [αυ]{.greek-supplied}της [απα[λος]{.greek-supplied}]{.greek-added} [γενηται]{.greek-supplied} [απαλος]{.greek-omitted} [και]{.greek-supplied} [τ]{.greek-supplied}[α]{.unclear} φυλλα εκφυη γινωσκετε οτ[ι]{.greek-supplied} [εγγυς]{.greek-supplied} [το]{.greek-supplied} [θερος]{.greek-supplied}[24:32]{.aside}

[ο]{.greek-supplied}υτως και [υμεις]{.greek-supplied} [οταν]{.greek-supplied} [ιδητ]{.greek-supplied}[ε]{.unclear} [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted} γινωσκετε οτι [ε]{.unclear}[γγυς]{.greek-supplied} [εστιν]{.greek-omitted} [επι]{.greek-supplied} [θυρ]{.greek-supplied}αις[24:33]{.aside}

[αμην]{.greek-supplied} [λεγ]{.greek-supplied}[ω]{.unclear} υμιν ου μη παρελθη η γενεα αυτη εως αν παντα ταυτα γενηται[24:34]{.aside}

[ο]{.greek-supplied} [[ουρανος]{.greek-abbr}]{.greek-supplied} [και]{.greek-supplied} η γη παρελευσονται οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[24:35]{.aside}

[πε]{.greek-supplied}ρι δε της ημερας εκεινης και [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε α[ι]{.greek-supplied} [ημεραι]{.greek-supplied} [του]{.greek-supplied} [ν]{.greek-supplied}ωε ουτως εσται και η παρουσια του υι[ο]{.unclear}[υ]{.greek-supplied} [του]{.greek-supplied} [[ανθρωπου]{.greek-abbr}]{.greek-supplied}[24:37]{.aside}

[ωσπερ]{.greek-omitted} [[ως]{.greek-supplied}]{.greek-added} γαρ ησαν [εν]{.greek-supplied} [ταις]{.greek-supplied} [ημερ]{.greek-supplied}αις ταις προ του κατακλυσμου [τ]{.unclear}[ρωγον]{.greek-supplied}τες [και]{.greek-omitted} [πινοντες]{.greek-omitted} γαμ[ουντες]{.greek-supplied} [και]{.greek-supplied} [ε]{.greek-supplied}κγαμιζοντες αχρι ης ημερας ειση[λ]{.unclear}[θεν]{.greek-supplied} [νωε]{.greek-supplied} [εις]{.greek-supplied} [την]{.greek-supplied} [κιβω]{.greek-supplied}τον[24:38]{.aside}

και ουκ [ε]{.unclear}[γνωσαν]{.greek-supplied} εως ηλθεν ο κατακλυσμος και ηρεν [α]{.unclear}[παντας]{.greek-supplied} [ουτως]{.greek-supplied} εσται και η παρ[ο]{.unclear}[υσια]{.greek-supplied} του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιε[τα]{.unclear}[ι]{.greek-supplied}[24:40]{.aside}

[δυο]{.greek-supplied} [αλη]{.greek-supplied}θουσαι εν τω μυλωνι μια παραλαμβανεται και μια αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα [ο]{.greek-supplied} [[κυριος]{.greek-abbr}]{.greek-supplied} υμων ερχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει ηδει ο οικοδεσποτης ποια φυλ[ακη]{.greek-supplied} ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν [ειασεν]{.greek-omitted} [ειασε]{.greek-added} διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της θεραπειας αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο κυριος αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκ[εινος]{.greek-supplied} [ε]{.greek-supplied}ν τη καρδια αυτου [χρονιζει]{.greek-supplied} [ο]{.greek-supplied} [[κυριος]{.greek-abbr}]{.greek-supplied} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους εσθιειν δε και πινειν [μετα]{.greek-supplied} [των]{.greek-supplied} [μεθ]{.greek-supplied}υοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα [και]{.greek-supplied} [εν]{.greek-supplied} [ωρα]{.greek-supplied} [η]{.greek-supplied} [ου]{.greek-supplied} γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των [υποκριτων]{.greek-supplied} θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

[το]{.greek-supplied}τε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι [τ]{.greek-supplied}ας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε η[σ]{.greek-supplied}αν εξ αυτων φρονιμοι και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λα[μ]{.greek-supplied}παδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε ημιν εκ του ελαιου υμων ο[τ]{.unclear}[ι]{.greek-supplied} [αι]{.greek-supplied} [λαμπα]{.greek-supplied}δες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δ[ε]{.greek-supplied} [αι]{.greek-supplied} [φρονιμοι]{.greek-supplied} [λεγου]{.greek-supplied}σαι μηπ[οτε]{.greek-supplied} [ουκ]{.greek-omitted} [[ου]{.greek-supplied}]{.greek-added} [[μη]{.greek-supplied}]{.greek-added} [αρκεση]{.greek-omitted} [[αρκε]{.greek-supplied}σει]{.greek-added} ημιν και υμιν πορευεσθε δε μαλ[λον]{.greek-supplied} [προς]{.greek-supplied} [τους]{.greek-supplied} [πω]{.greek-supplied}λουντας κ[αι]{.greek-supplied} [αγορασ]{.greek-supplied}ατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων [α]{.unclear}[γορασαι]{.greek-supplied} [ηλθεν]{.greek-supplied} [ο]{.greek-supplied} νυμφιος κα[ι]{.greek-supplied} [αι]{.greek-supplied} [ετοι]{.greek-supplied}μοι εισηλθον μετ αυτου εις τους γαμους κ[α]{.unclear}[ι]{.greek-supplied} [εκλεισθη]{.greek-supplied} [η]{.greek-supplied} [θυ]{.greek-supplied}ρα[25:10]{.aside}

υστερον δε [ερχ]{.unclear}ονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} [ανοιξον]{.greek-supplied} [ημιν]{.greek-supplied}[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγ[ο]{.unclear}[ρειτε]{.greek-supplied} [ουν]{.greek-supplied} [οτι]{.greek-supplied} [ου]{.greek-supplied}κ οιδατε την ημεραν ουδε την ωραν εν η ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} [τις]{.greek-added} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο [εκερδησεν]{.greek-omitted} [εκερδησε]{.greek-added} και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και [απεκρυψεν]{.greek-omitted} [απεκρυψε]{.greek-added} το αργυριον του κυριου αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο κυριος των δουλων εκεινων και συναιρει μετ αυτων λογον[25:19]{.aside}

[κ]{.greek-supplied}αι προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη [δε]{.greek-omitted} αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδ[η]{.unclear}σα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχει[ς]{.unclear} το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε ηδεις οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον εκβαλετε εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων [ταυτα]{.greek-added} [λεγων]{.greek-added} [εφωνει]{.greek-added} [ο]{.greek-added} [εχων]{.greek-added} [ωτα]{.greek-added} [ακουειν]{.greek-added} [ακουετω]{.greek-added}[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε καθισει επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησοντα]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

[τοτε]{.greek-supplied} [ερει]{.greek-supplied} [ο]{.greek-supplied} [β]{.greek-supplied}ασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου [κληρονομησατε]{.greek-omitted} [[κληρονομ]{.greek-supplied}οισατε]{.greek-added} την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσ[μου]{.greek-supplied}[25:34]{.aside}

[επει]{.greek-supplied}νασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με [ξενος]{.greek-supplied} [η]{.greek-supplied}[μ]{.unclear}ην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα [και]{.greek-supplied} [επεσ]{.greek-supplied}κεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκρι[θησοντα]{.greek-supplied}ι αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα και εθρε[ψαμεν]{.greek-supplied} η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και συνηγα[γομεν]{.greek-supplied} [η]{.unclear} γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη [και]{.greek-supplied} [ηλ]{.greek-supplied}[θ]{.unclear}ομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υ[μιν]{.greek-supplied} [ε]{.unclear}φ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι [εποι]{.greek-supplied}ησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακ[η]{.unclear} και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων [μου]{.greek-added} των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

[και]{.greek-supplied} [εγενετο]{.greek-supplied} [οτε]{.greek-supplied} ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις [αυτου]{.greek-supplied}[26:1]{.aside}

[οιδα]{.greek-supplied}τε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παρα[διδοται]{.greek-supplied} [ει]{.greek-supplied}ς το [σταυρωθηναι]{.greek-abbr}[26:2]{.aside}

[τοτε]{.greek-supplied} [συνη]{.greek-supplied}χθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου [εις]{.greek-supplied} [την]{.greek-supplied} [αυ]{.greek-supplied}λην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο [ινα]{.greek-supplied} [τον]{.greek-supplied} [[ιησουν]{.greek-abbr}]{.greek-supplied} δολω [κρατησωσιν]{.greek-omitted} [κρατησωσι]{.greek-added} και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη [ινα]{.greek-supplied} [μη]{.greek-supplied} [θο]{.greek-supplied}ρυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτ[η]{.unclear}[26:8]{.aside}

[ηδυνατο]{.greek-omitted} [[εδυ]{.greek-supplied}νατο]{.greek-added} γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι πτωχοι[ς]{.unclear}[26:9]{.aside}

[γνους]{.greek-supplied} δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους παρεχετε τη γυναικι εργον γαρ καλον ειρ[γ]{.unclear}[α]{.greek-supplied}σατο εις εμε[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} τους πτωχους [γαρ]{.greek-added} [παντοτε]{.greek-added} εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το [ενταφιασαι]{.greek-omitted} [ενταφια]{.greek-added} [[σαι]{.greek-supplied}]{.greek-added} [με]{.greek-supplied} [εποιησε]{.greek-supplied}[ν]{.unclear}[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχ[θη]{.greek-supplied} [το]{.greek-supplied} [ευαγγελιον]{.greek-supplied} [τ]{.greek-supplied}[ο]{.unclear}υτο εν ο[λω]{.greek-supplied} [τω]{.greek-supplied} [κοσμω]{.greek-supplied} [λα]{.greek-supplied}ληθησεται και ο εποιησεν αυτη ει[ς]{.greek-supplied} [μνημοσυνον]{.greek-supplied} [α]{.greek-supplied}υτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα [ο]{.greek-supplied} λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε μοι δουναι [καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που θελεις [[ε]{.unclear}τοιμασωμεν]{.greek-added} [[ε]{.unclear}τοιμασομεν]{.corr} σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα[26:20]{.aside}

και εσθιοντων αυτ[ω]{.unclear}[ν]{.greek-supplied} [ειπεν]{.greek-supplied} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδ[ρα]{.greek-supplied} [ηρξαν]{.greek-supplied}το λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω τρυβλιω την χειρα ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μητι εγω ειμι ραββι λεγει αυτω συ ειπας[26:25]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις [λεγων]{.greek-supplied} πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης δι[αθηκ]{.greek-supplied}[η]{.unclear}ς το περι πολλων [εκχυνομενον]{.greek-omitted} [εκχυννομενον]{.greek-added} εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του γεννηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησ[α]{.unclear}[ντες]{.greek-supplied} [εξηλ]{.greek-supplied}[θ]{.unclear}ον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις σκανδαλισθησεσθε εν εμ[ο]{.unclear}[ι]{.greek-supplied} [εν]{.greek-supplied} [τη]{.greek-supplied} [νυκτι]{.greek-supplied} [ταυ]{.greek-supplied}τη γεγραπται γαρ παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθη[σ]{.unclear}[ονται]{.greek-supplied}]{.greek-added} [τα]{.greek-supplied} [προ]{.greek-supplied}βατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις [την]{.greek-supplied} [γαλιλαιαν]{.greek-supplied}[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν [αυτω]{.greek-omitted} ει παντες σκανδαλισθησονται εν σοι εγω [δε]{.greek-omitted} ο[υ]{.greek-supplied}δεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον γεθσημανη και λεγει τοις μαθηταις καθισατε αυτου εως ου απελθων [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added} εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν [επι]{.greek-supplied} [προσωπον]{.greek-supplied} αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} [μου]{.greek-supplied} [ει]{.greek-supplied} [δυνατον]{.greek-supplied} [εστιν]{.greek-omitted} [[εσ]{.greek-supplied}τι]{.greek-added} [παρελθετω]{.greek-omitted} [παρελ[θατω]{.greek-supplied}]{.greek-added} [απ]{.greek-supplied} [εμου]{.greek-supplied} [το]{.greek-supplied} ποτηριον τουτο πλην ουχ ως [ε]{.unclear}[γω]{.greek-supplied} [θελω]{.greek-supplied} [αλλ]{.greek-supplied} [ως]{.greek-supplied} [σ]{.greek-supplied}υ[26:39]{.aside}

[κ]{.greek-supplied}αι ερχεται προς τους μαθητας [αυτου]{.greek-added} και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται [τουτο]{.greek-omitted} το ποτηριον [τουτο]{.greek-added} παρελθειν απ εμου εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων ευρισκει αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν [προσηυξατο]{.greek-omitted} [προσηυξα]{.greek-added} [εκ]{.greek-omitted} [τριτου]{.greek-omitted} [τον]{.greek-omitted} [αυτον]{.greek-omitted} [λογον]{.greek-omitted} [ειπων]{.greek-omitted}[26:44]{.aside}

