---
title: "Collation of Byz^RP^ vs 30780 (780)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 780 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30780).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 780                                   	| λογος                              	|
| 780 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 780 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 780               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 780                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 780 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 780                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου [προ[ς]{.unclear}]{.greek-added} [προ]{.corr} [προσωπου]{.corr} σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφε[σιν]{.unclear} αμαρτιων[1:4]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} προς αυτον πασα [η]{.greek-omitted} ιουδαια χωρα και οι ιεροσολυ[μι]{.unclear}ται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε [ο]{.greek-omitted} ιωαννης ενδεδυμενος τριχας καμηλου και [ζω]{.greek-supplied}νην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα [των]{.greek-omitted} [του]{.greek-added} [υποδηματων]{.greek-omitted} [υποδηματος]{.greek-added} αυτου[1:7]{.aside}

εγω μεν εβαπτισα [υμας]{.greek-omitted} [εν]{.greek-omitted} [υδατι]{.greek-omitted} [αυτος]{.greek-omitted} [δε]{.greek-omitted} [βαπτισει]{.greek-omitted} [υμας]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [αγιω]{.greek-omitted}[1:8]{.aside}

[εγω]{.greek-omitted} [μεν]{.greek-omitted} [εβαπτισα]{.greek-omitted} υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8 | instance no. 2]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} [ωσει]{.greek-omitted} [ως]{.greek-added} περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι [τον]{.greek-omitted} ιωαννην ηλθεν [ο]{.greek-omitted} [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

[και]{.greek-omitted} λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της [γαλι]{.greek-added} [γαλιλαιας]{.greek-omitted} [ειδεν]{.greek-omitted} [σιμωνα]{.greek-omitted} [και]{.greek-omitted} [ανδρεαν]{.greek-omitted} [τον]{.greek-omitted} [αδελφον]{.greek-omitted} [αυτου]{.greek-omitted} [του]{.greek-omitted} [σιμωνος]{.greek-omitted} [βαλλοντας]{.greek-omitted} [αμφιβληστρον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [αλιεις]{.greek-omitted}[1:16]{.aside}

[λαιας]{.greek-added} [περιπατων]{.greek-omitted} [δε]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} ειδεν σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16 | instance no. 2]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν [[εδιδασκε]{.corr}]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και [συ]{.greek-added} [σοι]{.greek-omitted} [ιησου]{.greek-omitted} [ναζαρηνε]{.greek-omitted} [ηλθες]{.greek-omitted} [απολεσαι]{.greek-omitted} [ημας]{.greek-omitted} [οιδα]{.greek-omitted} [σε]{.greek-omitted} [τις]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[1:24]{.aside}

[λεγων]{.greek-omitted} [εα]{.greek-omitted} [τι]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [σοι]{.greek-omitted} [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαρηναι]{.greek-added} ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24 | instance no. 2]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους λεγοντας τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η [καινη]{.greek-added} διδαχη [η]{.greek-omitted} [καινη]{.greek-omitted} αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος [εφερον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δαιμονιζομενους]{.greek-omitted}[1:32]{.aside}

[οψιας]{.greek-omitted} [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [οτε]{.greek-omitted} [εδυ]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} εφερον προς αυτον παντας τους κακως εχοντας και [τους]{.greek-omitted} δαιμονιζομενους[1:32 | instance no. 2]{.aside}

και η πολις ολη [επισυνηγμενη]{.greek-omitted} [επισυναγμενη]{.greek-added} ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ηιδεισαν]{.greek-added} αυτον[1:34]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και κατεδιωξαν αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων αυτω οτι εαν [θελης]{.greek-omitted} [θεληις]{.greek-added} δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει [αυτω]{.greek-omitted} [θελω]{.greek-omitted} [καθαρισθητι]{.greek-omitted}[1:41]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [σπλαγχνισθεις]{.greek-omitted} [εκτεινας]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [ηψατο]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} θελω καθαρισθητι[1:41 | instance no. 2]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και [εκαθαρισθη]{.greek-omitted} [εκαθερισθη]{.greek-added}[1:42]{.aside}

και εμβριμησαμενος αυτω [ευθεως]{.greek-omitted} εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν ειπης [αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45]{.aside}

### Chapter 2

και [εισηλθε]{.greek-added} [[τω]{.corr}]{.greek-added} [[καιρω]{.corr}]{.greek-added} [[εκεινω]{.corr}]{.greek-added} [εισηλθεν]{.corr} [[ο]{.corr}]{.greek-added} [[[ιησους]{.greek-abbr}]{.corr}]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον εστιν[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον [απεστεγασαν]{.greek-omitted} [την]{.greek-omitted} [στεγην]{.greek-omitted} [οπου]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [εξορυξαντες]{.greek-omitted} [χαλωσιν]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [εφ]{.greek-omitted} [ω]{.greek-omitted} [ο]{.greek-omitted} [παραλυτικος]{.greek-omitted} [κατεκειτο]{.greek-omitted}[2:4]{.aside}

[και]{.greek-omitted} [μη]{.greek-omitted} [δυναμενοι]{.greek-omitted} [προσεγγισαι]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω ο παραλυτικος [κατεκειτο]{.greek-omitted} [εκειτο]{.greek-added}[2:4 | instance no. 2]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει [καθημενοι]{.greek-omitted} [καθιμενοι]{.greek-added} και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι [σου]{.greek-added} η ειπειν εγειραι και αρον σου τον κραββατον και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} αφιεναι επι της γης αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω εγειραι και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως [και]{.greek-omitted} [αρας]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εναντιον]{.greek-omitted} [παντων]{.greek-omitted} [ωστε]{.greek-omitted} [εξιστασθαι]{.greek-omitted} [παντας]{.greek-omitted} [και]{.greek-omitted} [δοξαζειν]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [λεγοντας]{.greek-omitted} [οτι]{.greek-omitted} [ουδεποτε]{.greek-omitted} [ουτως]{.greek-omitted} [ειδομεν]{.greek-omitted}[2:12]{.aside}

[και]{.greek-omitted} [ηγερθη]{.greek-omitted} [ευθεως]{.greek-omitted} και αρας τον κραββατον εξηλθεν [εναντιον]{.greek-omitted} [εναντιων]{.greek-added} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added}[2:12 | instance no. 2]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι [συνανεκειντο]{.greek-omitted} [συνεκειντο]{.greek-added} τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και [οι]{.greek-omitted} των φαρισαιων νηστευοντες και ερχονται και λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν [απαρθη]{.greek-omitted} [απαρθηι]{.greek-added} απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευουσιν]{.greek-added} εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω [παλαιω]{.greek-omitted} [παλαιωι]{.greek-added} ει δε μη αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται αλλα οινον νεον εις ασκους καινους βλητεον[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [οδον]{.greek-omitted} [ποιειν]{.greek-omitted} [τιλλοντες]{.greek-omitted} [τους]{.greek-omitted} [σταχυας]{.greek-omitted}[2:23]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [παραπορευεσθαι]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [δια]{.greek-omitted} [των]{.greek-omitted} [σποριμων]{.greek-omitted} [και]{.greek-omitted} [ηρξαντο]{.greek-omitted} οι μαθηται αυτου οδον ποιειν τιλλοντες τους [σταχυας]{.greek-omitted} [ασταχυας]{.greek-added}[2:23 | instance no. 2]{.aside}

και οι φαρισαιοι ελεγον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ εξεστιν[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added} [και]{.greek-added} αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην [σωσαι]{.greek-omitted} [η]{.greek-omitted} [αποκτειναι]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [εσιωπων]{.greek-omitted}[3:4]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [εξεστιν]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [αγαθοποιησαι]{.greek-omitted} [η]{.greek-omitted} [κακοποιησαι]{.greek-omitted} [ψυχην]{.greek-omitted} σωσαι η [αποκτειναι[―]{.gap}]{.greek-added} [αποκτειναι]{.corr} οι δε εσιωπων[3:4 | instance no. 2]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη πωρωσει της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα [σου]{.greek-omitted} και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου υγιης ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και [σιδωνα]{.greek-omitted} [σιδονα]{.greek-added} πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον προσκαρτερη αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου αψωνται οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [οταν]{.greek-omitted} [αυτον]{.greek-omitted} [εθεωρει]{.greek-omitted} [προσεπιπτεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [εκραζεν]{.greek-omitted} [λεγοντα]{.greek-omitted} [οτι]{.greek-omitted} [συ]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[3:11]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [πνευματα]{.greek-omitted} τα ακαθαρτα οταν αυτον εθεωρει προσεπιπτεν αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11 | instance no. 2]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτ[ο]{.unclear}ς και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα αποστελλη αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και επεθηκεν τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον του ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη δυνασθαι αυτους μητε [αρτον]{.greek-omitted} [φαγειν]{.greek-omitted}[3:20]{.aside}

[και]{.greek-omitted} [συνερχεται]{.greek-omitted} [παλιν]{.greek-omitted} [οχλος]{.greek-omitted} [ωστε]{.greek-omitted} [μη]{.greek-omitted} [δυνασθαι]{.greek-omitted} [αυτους]{.greek-omitted} [μητε]{.greek-omitted} αρτον φαγειν[3:20 | instance no. 2]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων [και]{.greek-added} καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην [μερισθη]{.greek-omitted} [μερισθηι]{.greek-added} ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην [μερισθη]{.greek-omitted} [μερισθηι]{.greek-added} ου δυναται σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι [οσας]{.corr} [αν]{.corr} [βλασφημησω[σιν]{.unclear}]{.corr}[3:28]{.aside}

ος [δ]{.greek-omitted} [αν]{.greek-omitted} [βλασφημηση]{.greek-omitted} [βλασφημησ[―]{.gap}]{.greek-added} εις το [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αγιον]{.greek-omitted} [ουκ]{.greek-omitted} [εχει]{.greek-omitted} [αφεσιν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [αιωνα]{.greek-omitted} [αλλ]{.greek-omitted} [ενοχος]{.greek-omitted} [εστιν]{.greek-omitted} [αιωνιου]{.greek-omitted} [κρισεως]{.greek-omitted}[3:29]{.aside}

[ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [βλασφημηση]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29 | instance no. 2]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο οχλος περι αυτον ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει ιδε η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} εστιν[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} εν τη διδαχη αυτου[4:2]{.aside}

ακουετε [ιδου]{.greek-omitted} [εξηλθεν]{.greek-omitted} [ο]{.greek-omitted} [σπειρων]{.greek-omitted} [του]{.greek-omitted} [σπειραι]{.greek-omitted}[4:3]{.aside}

[ακουετε]{.greek-omitted} ιδου εξηλθεν ο σπειρων του σπειραι[4:3 | instance no. 2]{.aside}

και εγενετο εν τω σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι [το]{.greek-omitted} [τω]{.greek-added} πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην [την]{.greek-omitted} καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἑν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἑν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἑν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα γινεται[4:11]{.aside}

ινα [βλεποντες]{.greek-omitted} [βλεπωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [μηποτε]{.greek-omitted} [επιστρεψωσιν]{.greek-omitted} [και]{.greek-omitted} [αφεθη]{.greek-omitted} [αυτοις]{.greek-omitted} [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted}[4:12]{.aside}

[ινα]{.greek-omitted} βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12 | instance no. 2]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [ακαρπος]{.greek-omitted} [γινεται]{.greek-omitted}[4:19]{.aside}

[και]{.greek-omitted} [αι]{.greek-omitted} [μεριμναι]{.greek-omitted} [του]{.greek-omitted} [αιωνος]{.greek-omitted} [τουτου]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [απατη]{.greek-omitted} [του]{.greek-omitted} [πλουτου]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [περι]{.greek-omitted} [τα]{.greek-omitted} [λοιπα]{.greek-omitted} [επιθυμιαι]{.greek-omitted} [εισπορευομεναι]{.greek-omitted} [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19 | instance no. 2]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} τι κρυπτον ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν [ω]{.greek-omitted} [ωι]{.greek-added} μετρω μετρειτε μετρηθησεται υμιν κ[αι]{.unclear} προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ αν εχη δοθησεται [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν ανθρωπος [βαλη]{.greek-omitted} [βαληι]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και [καθευδη]{.greek-omitted} [καθευδηι]{.greek-added} και εγειρηται νυκτα και ημεραν και ο σπορος βλαστανη και μηκυνηται ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη [γαρ]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [καρποφορει]{.greek-omitted} [πρωτον]{.greek-omitted} [χορτον]{.greek-omitted} [ειτα]{.greek-omitted} [σταχυν]{.greek-omitted} [ειτα]{.greek-omitted} [πληρη]{.greek-omitted} [σιτον]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σταχυι]{.greek-omitted}[4:28]{.aside}

[αυτοματη]{.greek-omitted} γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν τω σταχυι[4:28 | instance no. 2]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει [το]{.greek-omitted} [τον]{.greek-added} δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσομεν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} [παραβαλουμεν]{.greek-added} αυτην[4:30]{.aside}

ως κοκκον [σιναπεως]{.greek-omitted} [σιναπεος]{.greek-added} ος οταν [σπαρη]{.greek-omitted} [σπαρηι]{.greek-added} επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [σπαρηι]{.greek-added} αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως εδυναντο ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη [τη]{.greek-omitted} [τηι]{.greek-added} ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον [παραλαμβανουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [ως]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [δε]{.greek-omitted} [πλοιαρια]{.greek-omitted} [ην]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[4:36]{.aside}

[και]{.greek-omitted} [αφεντες]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36 | instance no. 2]{.aside}

και γινεται λαιλαψ ανεμου μεγαλη τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και ειπεν τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και εξελθοντι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις [μνη]{.greek-added} [μνημασιν]{.greek-omitted} [και]{.greek-omitted} [ουτε]{.greek-omitted} [αλυσεσιν]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [αυτον]{.greek-omitted} [δησαι]{.greek-omitted}[5:3]{.aside}

[μασι]{.greek-added} [ος]{.greek-omitted} [την]{.greek-omitted} [κατοικησιν]{.greek-omitted} [ειχεν]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [μνημασιν]{.greek-omitted} και ουτε αλυσεσιν ουδεις εδυνατο αυτον δησαι[5:3 | instance no. 2]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι [τας]{.greek-added} [αλυσεις]{.greek-added} υπ αυτου [τας]{.greek-omitted} [αλυσεις]{.greek-omitted} και τας πεδας συντετριφθαι και ουδεις αυτον [ισχυεν]{.greek-omitted} [ισχυε]{.greek-added} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις μνημασιν ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[5:6]{.aside}

και κραξας φωνη μεγαλη ειπεν τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι ονομα και απεκριθη λεγων λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει προς τω ορει αγελη χοιρων μεγαλη βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα [εις]{.greek-omitted} [αυτους]{.greek-omitted} [εισελθωμεν]{.greek-omitted}[5:12]{.aside}

[και]{.greek-omitted} [παρεκαλεσαν]{.greek-omitted} [αυτον]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [δαιμονες]{.greek-omitted} [λεγοντες]{.greek-omitted} [πεμψον]{.greek-omitted} [ημας]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [ινα]{.greek-omitted} εις αυτους εισελθωμεν[5:12 | instance no. 2]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-omitted} [[πνατα]{.greek-abbr}]{.greek-added} τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και ανηγγειλαν εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

διηγησαντο δε αυτοις οι ιδοντες πως εγενετο τω [δαιμονιζομενω]{.greek-omitted} [δαιμονιζομενωι]{.greek-added} και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [εποιησε]{.greek-added} και ηλεησεν σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δεκαπολει]{.greek-omitted} [οσα]{.greek-omitted} [εποιησεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [παντες]{.greek-omitted} [εθαυμαζον]{.greek-omitted}[5:20]{.aside}

[και]{.greek-omitted} [απηλθεν]{.greek-omitted} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20 | instance no. 2]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων επιθης αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και ηκολουθει αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν [τω]{.greek-omitted} [τωι]{.greek-added} οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι καν των ιματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος [αυτης]{.greek-omitted} [και]{.greek-omitted} [εγνω]{.greek-omitted} [τω]{.greek-omitted} [σωματι]{.greek-omitted} [οτι]{.greek-omitted} [ιαται]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαστιγος]{.greek-omitted}[5:29]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [εξηρανθη]{.greek-omitted} [η]{.greek-omitted} [πηγη]{.greek-omitted} [του]{.greek-omitted} [αιματος]{.greek-omitted} αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29 | instance no. 2]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου σεσωκεν σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας [τον]{.greek-omitted} [λογον]{.greek-omitted} [λαλουμενον]{.greek-omitted} λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω συνακολουθησαι ει μη πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} εις τον οικον [του]{.greek-omitted} [αρχισυναγωγου]{.greek-omitted} [και]{.greek-omitted} [θεωρει]{.greek-omitted} [θορυβον]{.greek-omitted} [κλαιοντας]{.greek-omitted} [και]{.greek-omitted} [αλαλαζοντας]{.greek-omitted} [πολλα]{.greek-omitted}[5:38]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} του αρχισυναγωγου και θεωρει θορυβον κλαιοντας και αλαλαζοντας πολλα[5:38 | instance no. 2]{.aside}

και εισελθων λεγει αυτοις τι θορυβεισθε [και]{.greek-omitted} [μη]{.greek-added} κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} [του]{.greek-omitted} [της]{.greek-added} [παιδιου]{.greek-omitted} [παιδος]{.greek-added} και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα κουμι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω εγειραι[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστειλαντο]{.greek-added} αυτοις πολλα ινα μηδεις γνω τουτο και ειπεν δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν [τη]{.greek-omitted} [τηι]{.greek-added} συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} [ταυτα]{.greek-omitted} [και]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [η]{.greek-omitted} [δοθεισα]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [δυναμεις]{.greek-omitted} [τοιαυται]{.greek-omitted} [δια]{.greek-omitted} [των]{.greek-omitted} [χειρων]{.greek-omitted} [αυτου]{.greek-omitted} [γινονται]{.greek-omitted}[6:2]{.aside}

[και]{.greek-omitted} [γενομενου]{.greek-omitted} [σαββατου]{.greek-omitted} [ηρξατο]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [συναγωγη]{.greek-omitted} [διδασκειν]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [ακουοντες]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [ποθεν]{.greek-omitted} [τουτω]{.greek-omitted} ταυτα και τις η σοφια η δοθεισα αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2 | instance no. 2]{.aside}

ουχ ουτος εστιν ο τεκτων ο υιος μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι [αδελφαι]{.greek-omitted} [αδελφε]{.greek-added} αυτου ωδε προς ημας και εσκανδαλιζοντο εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη πατριδι αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκε[ι]{.unclear} [ου]{.unclear}δεμιαν δυναμιν ποιησαι ει μη ολιγο[ι]{.greek-supplied}ς αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγελλεν]{.greek-added} αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μονον μη πηραν μ[η]{.unclear} αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους [σανδαλια]{.greek-omitted} [σανδα]{.greek-added} [και]{.greek-omitted} [μη]{.greek-omitted} [ενδυσησθε]{.greek-omitted} [δυο]{.greek-omitted} [χιτωνας]{.greek-omitted}[6:9]{.aside}

[λια]{.greek-added} [αλλ]{.greek-omitted} [υποδεδεμενους]{.greek-omitted} [σανδαλια]{.greek-omitted} και μη ενδυσησθε δυο χιτωνας[6:9 | instance no. 2]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι αν μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η γομορροις εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και [ηκουσεν]{.greek-omitted} [ηκουσε]{.greek-added} [ο]{.greek-omitted} βασιλευς ηρωδης φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο ενεργουσιν αι δυναμεις εν αυτω[6:14]{.aside}

[αλλοι]{.greek-omitted} [ελεγον]{.greek-omitted} [οτι]{.greek-omitted} [ηλιας]{.greek-omitted} [εστιν]{.greek-omitted} αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} ιωαννην ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης [απο]{.greek-added} [αποστειλας]{.greek-omitted} [εκρατησεν]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [και]{.greek-omitted} [εδησεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [φυλακη]{.greek-omitted} [δια]{.greek-omitted} [ηρωδιαδα]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [φιλιππου]{.greek-omitted} [του]{.greek-omitted} [αδελφου]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [αυτην]{.greek-omitted} [εγαμησεν]{.greek-omitted}[6:17]{.aside}

[αυτος]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ηρωδης]{.greek-omitted} [αποστειλας]{.greek-omitted} [στειλας]{.greek-added} [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο ιωαννης τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω [κορασιω]{.greek-omitted} [κορασιωι]{.greek-added} αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν με [αιτησης]{.greek-omitted} [αιτησηις]{.greek-added} δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε [εξελ]{.greek-added} [εξελθουσα]{.greek-omitted} [ειπεν]{.greek-omitted} [τη]{.greek-omitted} [μητρι]{.greek-omitted} [αυτης]{.greek-omitted} [τι]{.greek-omitted} [αιτησομαι]{.greek-omitted} [η]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [ιωαννου]{.greek-omitted} [του]{.greek-omitted} [βαπτιστου]{.greek-omitted}[6:24]{.aside}

[θουσα]{.greek-added} [η]{.greek-omitted} [δε]{.greek-omitted} [εξελθουσα]{.greek-omitted} ειπεν τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε ειπεν την κεφαλην ιωαννου του βαπτιστου[6:24 | instance no. 2]{.aside}

και εισελθουσα [ευθεως]{.greek-omitted} μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το [πτωμα]{.greek-omitted} [σωμα]{.greek-added} αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και [συναγονται]{.greek-omitted} [συναγωνται]{.greek-added} οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις [ερη]{.greek-added} [ερημον]{.greek-omitted} [τοπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [ολιγον]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [ερχομενοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [υπαγοντες]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ουδε]{.greek-omitted} [φαγειν]{.greek-omitted} [ευκαιρουν]{.greek-omitted}[6:31]{.aside}

[μον]{.greek-added} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [δευτε]{.greek-omitted} [υμεις]{.greek-omitted} [αυτοι]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [εις]{.greek-omitted} [ερημον]{.greek-omitted} τοπον και αναπαυεσθε ολιγον ησαν γαρ οι ερχομενοι και [οι]{.greek-omitted} υπαγοντες πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added}[6:31 | instance no. 2]{.aside}

και απηλθον εις ερημον τοπον [τω]{.greek-omitted} [εν]{.greek-added} πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} αυτους [και]{.greek-omitted} [συνηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ειδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο [αυτους]{.greek-added} διδασκειν [αυτους]{.greek-omitted} πολλα[6:34]{.aside}

και [ηδη]{.greek-omitted} [δη]{.greek-added} ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται αυτου λεγουσιν οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν [εαυτοις]{.greek-omitted} [εαυτους]{.greek-added} αρτους τι γαρ [φαγωσιν]{.greek-omitted} [φαγουσιν]{.greek-added} ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν [διακοσιων]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} αρτους και [δωμεν]{.greek-omitted} [δωσωμεν]{.greek-added} αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε [και]{.greek-omitted} [γνοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [πεντε]{.greek-omitted} [και]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted}[6:38]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ποσους]{.greek-omitted} [αρτους]{.greek-omitted} [εχετε]{.greek-omitted} [υπαγετε]{.greek-omitted} και [ελθοντες]{.greek-added} [ιδετε]{.greek-omitted} [και]{.greek-omitted} [γνοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38 | instance no. 2]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και [ανεπεσον]{.greek-omitted} [ανεπεσαν]{.greek-added} πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κλασας]{.greek-added} τους αρτους [και]{.greek-omitted} εδιδου τοις μαθηταις [αυτου]{.greek-omitted} ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [περισσευματα]{.greek-added} κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως ηναγκασεν τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} εως αυτος απολυση τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [αυτους]{.greek-omitted} [βασανιζομενους]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ελαυνειν]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [εναντιος]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [περι]{.greek-omitted} [τεταρτην]{.greek-omitted} [φυλακην]{.greek-omitted} [της]{.greek-omitted} [νυκτος]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [περιπατων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

[ιδων]{.greek-added} [και]{.greek-omitted} [ειδεν]{.greek-omitted} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ [εναντιος]{.greek-added} ο ανεμος [εναντιος]{.greek-omitted} αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν αυτους[6:48 | instance no. 2]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν [και]{.greek-omitted} [ο]{.greek-added} [δε]{.greek-added} ευθεως ελαλησεν [μετ]{.greek-omitted} [αυτων]{.greek-omitted} και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις [εθαυμαζον]{.greek-added} [και]{.greek-added} εξισταντο [και]{.greek-omitted} [εθαυμαζον]{.greek-omitted}[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις [αλλ]{.greek-added} ην [γαρ]{.greek-omitted} αυτων η καρδια πεπωρωμενη[6:52]{.aside}

και διαπερασαντες [ηλθον]{.greek-omitted} [απηλθον]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} την γην γεννησαρετ και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

[περιδραμοντες]{.greek-omitted} [περιεδραμον]{.greek-added} ολην την [περιχωρον]{.greek-omitted} [χωραν]{.greek-added} εκεινην [και]{.greek-added} ηρξαντο επι [τοις]{.greek-omitted} [τους]{.greek-added} [κραββατοις]{.greek-omitted} [κραββατους]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει εστιν[6:55]{.aside}

και οπου αν [εισεπο]{.greek-added} [εισεπορευετο]{.greek-omitted} [εις]{.greek-omitted} [κωμας]{.greek-omitted} [η]{.greek-omitted} [πολεις]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [αγοραις]{.greek-omitted} [ετιθουν]{.greek-omitted} [τους]{.greek-omitted} [ασθενουντας]{.greek-omitted} [και]{.greek-omitted} [παρεκαλουν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [καν]{.greek-omitted} [του]{.greek-omitted} [κρασπεδου]{.greek-omitted} [του]{.greek-omitted} [ιματιου]{.greek-omitted} [αυτου]{.greek-omitted} [αψωνται]{.greek-omitted} [και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [ηπτοντο]{.greek-omitted} [αυτου]{.greek-omitted} [εσωζοντο]{.greek-omitted}[6:56]{.aside}

[ρευετο]{.greek-added} [και]{.greek-omitted} [οπου]{.greek-omitted} [αν]{.greek-omitted} [εισεπορευετο]{.greek-omitted} εις κωμας η πολεις η αγρους εν ταις αγοραις [ετιθουν]{.greek-omitted} [ετιθεσαν]{.greek-added} τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου [αυτω]{.greek-added} [αυτου]{.corr} αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56 | instance no. 2]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου [οτι]{.greek-added} κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας αρτους [εμεμψαντο]{.greek-omitted}[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται [τας]{.greek-omitted} χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} [κρατουντες]{.greek-omitted} [την]{.greek-omitted} [παραδοσιν]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted}[7:3]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [αγορας]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [βαπτισωνται]{.greek-omitted} [ουκ]{.greek-omitted} [εσθιουσιν]{.greek-omitted} και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι [ου]{.greek-added} [περιπατουσιν]{.greek-added} οι μαθηται σου [ου]{.greek-omitted} [περιπατουσιν]{.greek-omitted} κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων αλλα ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως [προεφητευσεν]{.greek-omitted} [προεφητευσε]{.greek-added} [ησαιας]{.greek-omitted} περι υμων [ησαιας]{.greek-added} των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων [πορρω]{.greek-omitted} [πορ]{.greek-added} [απεχει]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted}[7:6]{.aside}

[ρω]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [οτι]{.greek-omitted} [καλως]{.greek-omitted} [προεφητευσεν]{.greek-omitted} [ησαιας]{.greek-omitted} [περι]{.greek-omitted} [υμων]{.greek-omitted} [των]{.greek-omitted} [υποκριτων]{.greek-omitted} [ως]{.greek-omitted} [γεγραπται]{.greek-omitted} [ουτος]{.greek-omitted} [ο]{.greek-omitted} [λαος]{.greek-omitted} [τοις]{.greek-omitted} [χειλεσιν]{.greek-omitted} [με]{.greek-omitted} [τιμα]{.greek-omitted} [η]{.greek-omitted} [δε]{.greek-omitted} [καρδια]{.greek-omitted} [αυτων]{.greek-omitted} [πορρω]{.greek-omitted} απεχει απ εμου[7:6 | instance no. 2]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα ανθρωπων[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των ανθρωπων βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν [υμων]{.greek-omitted} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} τηρησητε[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} [αυτου]{.greek-omitted} η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και [αλλα]{.greek-added} παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και [συνιετε]{.greek-omitted} [συνετε]{.greek-added}[7:14]{.aside}

ουδεν εστιν [εξωθεν]{.greek-omitted} [εξω]{.greek-added} του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι [[―]{.gap}λλα]{.greek-added} [αλλα]{.corr} τα εκπορευομενα [απ]{.greek-omitted} [αυτου]{.greek-omitted} [εκεινα]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις [εχει]{.greek-omitted} [ωτα]{.greek-omitted} [ακουειν]{.greek-omitted} [ακουετω]{.greek-omitted}[7:16]{.aside}

[ει]{.greek-omitted} [τις]{.greek-omitted} εχει ωτα ακουειν ακουετω[7:16 | instance no. 2]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις [τον]{.greek-omitted} αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

ελεγεν δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος [ασελγεια]{.greek-omitted} [ασελγειαι]{.greek-added} οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

[ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [τα]{.greek-omitted} πονηρα εσωθεν [εκπορευεται]{.greek-omitted} [εκπορευονται]{.greek-added} και [κοινοι]{.greek-omitted} [κοινη]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

[και]{.greek-omitted} εκειθεν [δε]{.greek-added} αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι [αυ]{.greek-added} [αυτου]{.greek-omitted} [ης]{.greek-omitted} [ειχεν]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [αυτης]{.greek-omitted} [πνευμα]{.greek-omitted} [ακαθαρτον]{.greek-omitted} [ελθουσα]{.greek-omitted} [προσεπεσεν]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted}[7:25]{.aside}

[ακουσασα]{.greek-omitted} [γαρ]{.greek-omitted} [γυνη]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted} [του]{.greek-added} ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25 | instance no. 2]{.aside}

[η]{.greek-added} [δε]{.greek-added} [γυνη]{.greek-added} ην [δε]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} ελληνις [συραφοινικισσα]{.greek-omitted} [συροφοινικισσα]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} γενει και ηρωτα αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ [εστι]{.greek-added} καλον [εστιν]{.greek-omitted} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης [εσθιει]{.greek-omitted} [εσθιουσιν]{.greek-added} απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης ευρεν το [παιδιον]{.greek-added} [βεβλημενον]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [κλινην]{.greek-added} [και]{.greek-added} [το]{.greek-added} δαιμονιον εξεληλυθος [και]{.greek-omitted} [την]{.greek-omitted} [θυγατερα]{.greek-omitted} [βεβλημενην]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κλινης]{.greek-omitted}[7:30]{.aside}

και παλιν εξελθων [[ο]{.corr}]{.greek-added} [[[ιησους]{.greek-abbr}]{.corr}]{.greek-added} εκ των οριων τυρου και σιδωνος ηλθεν [προς]{.greek-omitted} [παρα]{.greek-added} την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω [την]{.greek-omitted} [χειρα]{.greek-omitted}[7:32]{.aside}

[και]{.greek-omitted} [φερουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [κωφον]{.greek-omitted} [μογγιλαλον]{.greek-omitted} [και]{.greek-omitted} [παρακαλουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [επιθη]{.greek-omitted} [αυτω]{.greek-omitted} την χειρα[7:32 | instance no. 2]{.aside}

και απολαβομενος αυτον [κατ]{.greek-added} [ιδιαν]{.greek-added} απο του οχλου [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} εβαλεν [αυτου]{.greek-added} τους δακτυλους [αυτου]{.greek-omitted} εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [διανοιχθητι]{.greek-omitted} [διανυχθητι]{.greek-added}[7:34]{.aside}

και ευθεως [διηνοιχθησαν]{.greek-omitted} [διηνυχθησαν]{.greek-added} αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} [περι]{.greek-added} [αυτου]{.greek-added} οσον δε αυτος αυτοις [διεστελλετο]{.greek-omitted} [διεστειλατο]{.greek-added} [αυτοι]{.greek-added} μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και [υπερπερισσως]{.greek-omitted} [υπερεκπερισσου]{.greek-added} εξεπλησσοντο λεγοντες καλως παντα πεποιηκεν και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παλιν]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου οντος και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον [τουτον]{.greek-added} οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις οικον αυτων [εκλυθησονται]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [τινες]{.greek-omitted} [γαρ]{.greek-omitted} [αυτων]{.greek-omitted} [μακροθεν]{.greek-omitted} [ηκουσιν]{.greek-omitted}[8:3]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [απολυσω]{.greek-omitted} [αυτους]{.greek-omitted} [νηστεις]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [αυτων]{.greek-omitted} εκλυθησονται εν τη οδω τινες γαρ αυτων [απο]{.greek-added} μακροθεν [ηκουσιν]{.greek-omitted} [ηκασι]{.greek-added}[8:3 | instance no. 2]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους [δ[α]{.unclear}νησεται]{.greek-added} [δυνησεται]{.corr} τις [ωδε]{.greek-omitted} χορτασαι αρτων επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους [αρτους]{.greek-added} εχετε [αρτους]{.greek-omitted} οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι [της]{.greek-omitted} [γης]{.greek-omitted} [την]{.greek-added} [γην]{.greek-added} και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις [αυτου]{.greek-omitted} ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [αυτα]{.greek-added} ειπεν [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν [παντες]{.greek-added} και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε [οι]{.greek-omitted} [φαγοντες]{.greek-omitted} ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [ευθεως]{.greek-omitted} εμβας [ευθυς]{.greek-added} εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα [μερη]{.greek-omitted} [ορια]{.greek-added} δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η [γενεα]{.greek-omitted} [αυτη]{.greek-omitted} [σημειον]{.greek-omitted} [επιζητει]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ει]{.greek-omitted} [δοθησεται]{.greek-omitted} [τη]{.greek-omitted} [γενεα]{.greek-omitted} [ταυτη]{.greek-omitted} [σημειον]{.greek-omitted}[8:12]{.aside}

[και]{.greek-omitted} [αναστεναξας]{.greek-omitted} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [αυτου]{.greek-omitted} [λεγει]{.greek-omitted} [τι]{.greek-omitted} [η]{.greek-omitted} γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα [ταυτη]{.greek-omitted} [αυτη]{.greek-added} σημειον[8:12 | instance no. 2]{.aside}

και αφεις αυτους [εμβας]{.greek-omitted} [παλιν]{.greek-omitted} [εις]{.greek-omitted} [πλοιον]{.greek-omitted} [απηλθεν]{.greek-omitted} εις το [περαν]{.greek-omitted} [πλοιον]{.greek-added} [απηλθε]{.greek-added} [παλιν]{.greek-added}[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και [διεστελλετο]{.greek-omitted} [διεστειλατο]{.greek-added} αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

[και]{.greek-omitted} γνους [δε]{.greek-added} ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε [ουδε]{.greek-added} [και]{.greek-omitted} [ου]{.greek-omitted} μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους πληρεις κλασματων ηρατε [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δωδεκα]{.greek-omitted}[8:19]{.aside}

[οτε]{.greek-omitted} [δε]{.greek-omitted} [τους]{.greek-omitted} [επτα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [τετρακισχιλιους]{.greek-omitted} [ποσων]{.greek-omitted} [σπυριδων]{.greek-omitted} [πληρωματα]{.greek-omitted} [κλασματων]{.greek-omitted} [ηρατε]{.greek-omitted} οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις πως [ου]{.greek-omitted} [ουπω]{.greek-added} συνιετε[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της [χειρος]{.greek-omitted} [του]{.greek-omitted} [τυφλου]{.greek-omitted} [εξηγαγεν]{.greek-omitted} [αυτον]{.greek-omitted} [εξω]{.greek-omitted} [της]{.greek-omitted} [κωμης]{.greek-omitted} [και]{.greek-omitted} [πτυσας]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ομματα]{.greek-omitted} [αυτου]{.greek-omitted} [επιθεις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [αυτω]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [ει]{.greek-omitted} [χει]{.greek-added} [τι]{.greek-omitted} [βλεπει]{.greek-omitted}[8:23]{.aside}

[ρος]{.greek-added} [και]{.greek-omitted} [επιλαβομενος]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα αυτον ει τι βλεπει[8:23 | instance no. 2]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τηλαυγως [απαντας]{.greek-omitted}[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων [μηδε]{.greek-omitted} [υπαγε]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [εαν]{.greek-added} εις την κωμην εισελθης [μηδε]{.greek-omitted} [μηδεν]{.greek-added} ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και [επετιμησεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ινα]{.greek-omitted} [μηδενι]{.greek-omitted} [λεγωσιν]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted}[8:30]{.aside}

[και]{.greek-omitted} επετιμησεν αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30 | instance no. 2]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και των αρχιερεων και των γραμματεων και αποκτανθηναι [και]{.corr} [μετα]{.corr} [τρεις]{.corr} [ημερας]{.corr} [αναστηναι]{.corr}[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[8:32]{.aside}

ο δε [επιστραφεις]{.greek-omitted} [στραφεις]{.greek-added} και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των ανθρωπων[8:33]{.aside}

και προσκαλεσαμενος τον οχλον σ[υ]{.unclear}ν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} [την]{.greek-omitted} [αυτην]{.greek-added} [εαυτου]{.greek-omitted} [ψυχην]{.greek-omitted} ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} εαν κερδηση τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-omitted} [ανταλλαγμα]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} [αυτου]{.greek-omitted}[8:37]{.aside}

[η]{.greek-omitted} [τι]{.greek-omitted} [δωσει]{.greek-omitted} [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37 | instance no. 2]{.aside}

ος γαρ [εαν]{.greek-omitted} επαισχυνθη με και τους εμους λογους εν τη γενεα [ταυτη]{.greek-omitted} [αυτη]{.greek-added} τη [μοιχαλιδι]{.greek-omitted} [μοιχαλλιδι]{.greek-added} και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη [δοξει]{.greek-added} [δοξη]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} στιλβοντα λευκα λιαν ως χιων οια γναφευς επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν μωση και ησαν [συλλαλουντες]{.greek-omitted} [συνλαλουντες]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} [ραββι]{.greek-omitted} [ραββει]{.greek-added} καλον εστιν ημας ωδε ειναι [και]{.greek-omitted} ποιησωμεν σκηνας τρεις σοι μιαν και μωση μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ [ηδει]{.greek-omitted} [τι]{.greek-omitted} [λαλησει]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [εκφοβοι]{.greek-omitted}[9:6]{.aside}

[ου]{.greek-omitted} [γαρ]{.greek-omitted} ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6 | instance no. 2]{.aside}

και εγενετο νεφελη επισκιαζουσα αυτοις και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης [λεγουσα]{.greek-added} ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

[και]{.greek-added} καταβαινοντων [δε]{.greek-omitted} αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι διηγησωνται α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις ηλιας μεν ελθων πρωτον [αποκαθιστα]{.greek-omitted} [αποκαθιστανει]{.greek-added} παντα και πως γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν [περι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [γραμματεις]{.greek-omitted} [συζητουντας]{.greek-omitted} [αυτοις]{.greek-omitted}[9:14]{.aside}

[και]{.greek-omitted} [ελθων]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [ειδεν]{.greek-omitted} [οχλον]{.greek-omitted} [πολυν]{.greek-omitted} περι αυτους και γραμματεις συζητουντας αυτοις[9:14 | instance no. 2]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς [αυτους]{.greek-omitted} [εαυτους]{.greek-added}[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε ηνεγκα τον υιον μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [λεγει]{.greek-added} αυτω [λεγει]{.greek-omitted} ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι [της]{.greek-omitted} [γης]{.greek-omitted} [την]{.greek-added} [γην]{.greek-added} εκυλιετο αφριζων[9:20]{.aside}

και επηρωτησεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο δε ειπεν παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα [ινα]{.greek-omitted} [απολεση]{.greek-omitted} [αυτον]{.greek-omitted} [αλλ]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} [δυνασαι]{.greek-omitted} [βοηθησον]{.greek-omitted} [ημιν]{.greek-omitted} [σπλαγχνισθεις]{.greek-omitted} [εφ]{.greek-omitted} [ημας]{.greek-omitted}[9:22]{.aside}

[και]{.greek-omitted} [πολλακις]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [εβαλεν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [υδατα]{.greek-omitted} ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [το]{.greek-omitted} ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [επισυντριχει]{.greek-added} [ο]{.greek-added} [οοχλος]{.greek-added} [οχλος]{.corr} [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε [εξ]{.greek-omitted} [απ]{.greek-added} αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον [λεγοντες]{.greek-added} κατ ιδιαν οτι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηθελεν]{.greek-omitted} [ινα]{.greek-omitted} [τις]{.greek-omitted} [γνω]{.greek-omitted}[9:30]{.aside}

[και]{.greek-omitted} [εκειθεν]{.greek-omitted} [εξελθοντες]{.greek-omitted} [παρεπορευοντο]{.greek-omitted} [δια]{.greek-omitted} της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30 | instance no. 2]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις [τη]{.greek-omitted} [τηι]{.greek-added} τριτη ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν [[ο]{.corr}]{.greek-added} [[[ιησους]{.greek-abbr}]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [[οι]{.corr}]{.greek-added} [[μαθηται]{.corr}]{.greek-added} [[αυτου]{.corr}]{.greek-added} εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν [των]{.greek-omitted} [τοιουτων]{.greek-omitted} [τοιουτον]{.greek-added} [παιδιων]{.greek-omitted} [παιδιον]{.greek-added} δεξηται [επι]{.greek-omitted} [εν]{.greek-added} τω ονοματι μου εμε δεχεται και ος [ε]{.unclear}αν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη [δε]{.greek-omitted} αυτω ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} τινα [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [σου]{.greek-omitted} [εκβαλλοντα]{.greek-omitted} [δαιμονια]{.greek-omitted} [ος]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

[απεκριθη]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} [ιωαννης]{.greek-omitted} [λεγων]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ειδομεν]{.greek-omitted} [τινα]{.greek-omitted} τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και εκωλυσαμεν αυτον οτι ουκ ακολουθει ημιν[9:38 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και [δυνησεται]{.greek-omitted} [δυνησηται]{.greek-added} ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καθ υμων υπερ υμων [εστιν]{.greek-omitted} [εστι]{.greek-added}[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεσει]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει περικειται [λιθος]{.greek-omitted} [μυλικος]{.greek-omitted} [μυλος]{.greek-added} [ονικος]{.greek-added} περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιση]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκωλιξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου [σκαν]{.greek-added} [σκανδαλιζη]{.greek-omitted} [σε]{.greek-omitted} [αποκοψον]{.greek-omitted} [αυτον]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [σοι]{.greek-omitted} [εισελθειν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ζωην]{.greek-omitted} [χωλον]{.greek-omitted} [η]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ποδας]{.greek-omitted} [εχοντα]{.greek-omitted} [βληθηναι]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γεενναν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [το]{.greek-omitted} [ασβεστον]{.greek-omitted}[9:45]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [ο]{.greek-omitted} [πους]{.greek-omitted} [σου]{.greek-omitted} [σκανδαλιζη]{.greek-omitted} [δαλιζη]{.greek-added} σε αποκοψον αυτον καλον [σοι]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45 | instance no. 2]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκωλιξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκωλιξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι [αυτο]{.greek-omitted} [αυτω]{.greek-added} αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας [δια]{.greek-omitted} [του]{.greek-omitted} περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον [και]{.greek-omitted} [ως]{.greek-omitted} [ειωθει]{.greek-omitted} [παλιν]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [αυτους]{.greek-omitted}[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι επηρωτησαν αυτον [ει]{.greek-omitted} εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [υμιν]{.greek-omitted} [ενετειλατο]{.greek-omitted} [μωσης]{.greek-omitted}[10:3]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} ειπεν αυτοις τι υμιν ενετειλατο μωσης[10:3 | instance no. 2]{.aside}

οι δε ειπον μωσης [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως [εγραψεν]{.greek-added} [οτι]{.greek-added} αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει ανθρωπος τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε [ουν]{.greek-added} ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} επηρωτησαν αυτον [περι]{.greek-added} [τουτου]{.greek-added}[10:10]{.aside}

και λεγει αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ος εαν απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη [αλλω]{.greek-omitted} [αλλωι]{.greek-added} μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αφετε]{.greek-omitted} [τα]{.greek-omitted} [παιδια]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted} [μη]{.greek-omitted} [κωλυετε]{.greek-omitted} [αυτα]{.greek-omitted} [των]{.greek-omitted} [γαρ]{.greek-omitted} [τοιουτων]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[10:14]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ηγανακτησεν]{.greek-omitted} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added}[10:14 | instance no. 2]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα ευλογει αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [προσδα]{.greek-added} [προσδραμων]{.corr} εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ηγαπησεν αυτον και ειπεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εν σοι [υστερει]{.greek-omitted} [υπολειπεται]{.greek-added} υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο [ακο]{.greek-added} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [αρας]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted}[10:21]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [εμβλεψας]{.greek-omitted} [αυτω]{.greek-omitted} [ηγαπησεν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [υστερει]{.greek-omitted} [υπαγε]{.greek-omitted} [οσα]{.greek-omitted} [εχεις]{.greek-omitted} [πωλησον]{.greek-omitted} [και]{.greek-omitted} [δος]{.greek-omitted} [πτωχοις]{.greek-omitted} [και]{.greek-omitted} [εξεις]{.greek-omitted} [θησαυρον]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [δευρο]{.greek-omitted} [ακολουθει]{.greek-omitted} [λουθει]{.greek-added} μοι αρας τον [σταυρον]{.greek-abbr}[10:21 | instance no. 2]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων [κτηματα]{.greek-omitted} [χρηματα]{.greek-added} πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι [χρημασιν]{.greek-omitted} [χρηματα]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

[ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [τω]{.greek-added} [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος [αφηκεν]{.greek-omitted} [οικιαν]{.greek-omitted} [η]{.greek-omitted} [αδελφους]{.greek-omitted} [η]{.greek-omitted} [αδελφας]{.greek-omitted} [η]{.greek-omitted} [πατερα]{.greek-omitted} [η]{.greek-omitted} [μητερα]{.greek-omitted} [η]{.greek-omitted} [γυναικα]{.greek-omitted} [η]{.greek-omitted} [τεκνα]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [ενεκεν]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted}[10:29]{.aside}

[αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ουδεις]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} αφηκεν οικιαν η αδελφους η αδελφας η [[μητερα]{.greek-abbr}]{.greek-added} [η]{.greek-added} [πατερα]{.greek-abbr} [η]{.greek-omitted} [μητερα]{.greek-omitted} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} του ευαγγελιου[10:29 | instance no. 2]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω [τουτω]{.greek-omitted} [τουτωι]{.greek-added} οικιας και αδελφους και αδελφας και [μητερας]{.greek-abbr} και τεκνα και αγρους μετα [διωγμων]{.greek-omitted} [διωγμον]{.greek-added} και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα [[και]{.corr}]{.greek-added} ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33]{.aside}

και εμπαιξουσιν [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} αυτον και εμπτυσουσιν αυτω και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και [προσπορευονται]{.greek-omitted} [αυτω]{.greek-omitted} [ιακωβος]{.greek-omitted} [και]{.greek-omitted} [ιωαννης]{.greek-omitted} [οι]{.greek-omitted} [υιοι]{.greek-omitted} [ζεβεδαιου]{.greek-omitted} [λεγοντες]{.greek-omitted} [διδασκαλε]{.greek-omitted} [θελομεν]{.greek-omitted} [ινα]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [αιτησωμεν]{.greek-omitted} [ποιησης]{.greek-omitted} [ημιν]{.greek-omitted}[10:35]{.aside}

[και]{.greek-omitted} προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν αιτησωμεν [ποιησης]{.greek-omitted} [δωσεις]{.greek-added} ημιν[10:35 | instance no. 2]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη [δοξη]{.greek-omitted} [δοξει]{.greek-added} σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθηναι]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added}[10:38]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [ιωαννου]{.greek-omitted} [των]{.greek-added} [δυο]{.greek-added} [αδελφων]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριευσουσιν]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε [εσται]{.greek-omitted} [εν]{.greek-omitted} [υμιν]{.greek-omitted} [αλλ]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [θελη]{.greek-omitted} [γενεσθαι]{.greek-omitted} [μεγας]{.greek-omitted} [εν]{.greek-omitted} [υμιν]{.greek-omitted} [εσται]{.greek-omitted} [υμων]{.greek-omitted} [διακονος]{.greek-omitted}[10:43]{.aside}

[ουχ]{.greek-omitted} [ουτως]{.greek-omitted} [δε]{.greek-omitted} εσται εν υμιν αλλ ος εαν θελη [μεγας]{.greek-added} γενεσθαι [μεγας]{.greek-omitted} εν υμιν εσται υμων διακονος[10:43 | instance no. 2]{.aside}

και ος εαν θελη υμων γενεσθαι πρωτος [εσται]{.greek-omitted} [εστω]{.greek-added} παντων δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλ[α]{.unclear} διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας ηλθεν προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω [σοι]{.greek-omitted} [σε]{.greek-added} ο δε τυφλος ειπεν αυτω ραββουνι ινα [αναβλεψω]{.greek-omitted} [βλεψω]{.greek-added}[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις [σου]{.greek-omitted} [σεσωκεν]{.greek-omitted} [σε]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [ανεβλεψεν]{.greek-omitted} [και]{.greek-omitted} [ηκολουθει]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted}[10:52]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [υπαγε]{.greek-omitted} [η]{.greek-omitted} [πιστις]{.greek-omitted} σου σεσωκεν σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52 | instance no. 2]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} [και]{.greek-added} εις βηθσφαγη και [βηθανιαν]{.greek-omitted} [βιθανιαν]{.greek-added} προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την [κατεναντι]{.greek-omitted} [απεναντι]{.greek-added} υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον [ουδεπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [εκαθισεν]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι ποιειτε τουτο [ειπατε]{.greek-omitted} [ερειτε]{.greek-added} οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως [αυτον]{.greek-omitted} αποστελλει [ωδε]{.greek-omitted} [αυτους]{.greek-added}[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς [την]{.greek-omitted} [τη]{.greek-added} [θυραν]{.greek-omitted} [θυρα]{.greek-added} εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [εκοπτον]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [δενδρων]{.greek-omitted} [και]{.greek-omitted} [εστρωννυον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted}[11:8]{.aside}

και οι [προαγοντες]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [εκραζον]{.greek-omitted} [λεγοντες]{.greek-omitted} [ωσαννα]{.greek-omitted} [ευλογημενος]{.greek-omitted} [ο]{.greek-omitted} [ερχομενος]{.greek-omitted} [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted}[11:9]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9 | instance no. 2]{.aside}

ευλογημενη η ερχομενη βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων [αυτων]{.greek-omitted} [αυτωι]{.greek-added} απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην [απο]{.greek-added} μακροθεν εχουσαν φυλλα ηλθεν ει αρα ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} μηκετι εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} και τας καθεδρας των πωλουντων τας [περιστερας]{.greek-omitted} [κατεστρεψεν]{.greek-omitted}[11:15]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [εισελθων]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκβαλλειν]{.greek-omitted} [τους]{.greek-omitted} [πωλουντας]{.greek-omitted} [και]{.greek-omitted} [αγοραζοντας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [τραπεζας]{.greek-omitted} [των]{.greek-omitted} [κολλυβιστων]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [καθεδρας]{.greek-omitted} [των]{.greek-omitted} [πωλουντων]{.greek-omitted} [τας]{.greek-omitted} περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15 | instance no. 2]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω [ραββι]{.greek-omitted} [ραββει]{.greek-added} ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην [γαρ]{.greek-omitted} λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθε]{.greek-added} πιστευετε [οτι]{.greek-omitted} [λαμβανετε]{.greek-omitted} [και]{.greek-omitted} [εσται]{.greek-omitted} [υμιν]{.greek-omitted}[11:24]{.aside}

[δια]{.greek-omitted} [τουτο]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [παντα]{.greek-omitted} [οσα]{.greek-omitted} [αν]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [αιτησθε]{.greek-omitted} [πιστευετε]{.greek-omitted} οτι λαμβανετε και εσται υμιν[11:24 | instance no. 2]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκετε]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις ουρανοις αφη [[αφησει]{.corr}]{.greek-added} υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν τοις ουρανοις αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} [δεδωκεν]{.greek-added} ινα ταυτα ποιης[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [και]{.greek-omitted} [εγω]{.greek-omitted} [καγω]{.greek-added} [λογον]{.greek-added} ενα [λογον]{.greek-omitted} και αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ ανθρωπων αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον [λαον]{.greek-omitted} [οχλον]{.greek-added} απαντες γαρ [ειχον]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [οτι]{.greek-omitted} [οντως]{.greek-omitted} [προφητης]{.greek-omitted} [ην]{.greek-omitted}[11:32]{.aside}

[αλλ]{.greek-omitted} [ειπωμεν]{.greek-omitted} [εξ]{.greek-omitted} [ανθρωπων]{.greek-omitted} [εφοβουντο]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [απαντες]{.greek-omitted} [γαρ]{.greek-omitted} ειχον τον ιωαννην οτι οντως προφητης ην[11:32 | instance no. 2]{.aside}

και αποκριθεντες λεγουσιν τω [ιησου]{.greek-abbr} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [ανεχωρησεν]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους [εν]{.greek-added} τω [καιρω]{.corr} δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} εκεφαλαιωσαν και [απεστειλαν]{.greek-omitted} [απελυσαν]{.greek-added} ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα υιον εχων αγαπητον [αυτου]{.greek-omitted} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον προς αυτους εσχατον λεγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε [οι]{.greek-omitted} [γεωργοι]{.greek-omitted} [ειπον]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [οτι]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [κληρονομος]{.greek-omitted} [δευτε]{.greek-omitted} [αποκτεινωμεν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ημων]{.greek-omitted} [εσται]{.greek-omitted} [η]{.greek-omitted} [κληρονομια]{.greek-omitted}[12:7]{.aside}

[εκεινοι]{.greek-omitted} [δε]{.greek-omitted} οι γεωργοι [θεασαμενοι]{.greek-added} [αυτον]{.greek-added} ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7 | instance no. 2]{.aside}

και λαβοντες αυτον απεκτειν[α]{.unclear}ν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο κυριος του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδο[μ]{.unclear}ουντες ουτος εγενηθη εις κεφαλην γ[ω]{.unclear}νιας [[γονιας]{.corr}]{.greek-added}[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποτελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [των]{.greek-added} [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} [διδασκεις]{.greek-omitted} [εξεστιν]{.greek-omitted} [κηνσον]{.greek-omitted} [καισαρι]{.greek-omitted} [δουναι]{.greek-omitted} [η]{.greek-omitted} [ου]{.greek-omitted}[12:14]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ελθοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [οιδαμεν]{.greek-omitted} [οτι]{.greek-omitted} [αληθης]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [περι]{.greek-omitted} [ουδενος]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [βλεπεις]{.greek-omitted} [εις]{.greek-omitted} [προσωπον]{.greek-omitted} [ανθρωπων]{.greek-omitted} [αλλ]{.greek-omitted} [επ]{.greek-omitted} [αληθειας]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} διδασκεις εξεστιν κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14 | instance no. 2]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις απ[ο]{.unclear}δοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} [τ]{.unclear}ω [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυν[α]{.unclear}ικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [ουν]{.greek-added} αδελφοι ησαν [παρ]{.greek-added} [ημιν]{.greek-added} και ο πρωτος ελαβεν γυναικα και αποθνησκων ουκ αφηκεν σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν και ουδε [αυτος]{.greek-omitted} [ουτος]{.greek-added} [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην [οι]{.greek-omitted} [επτα]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [αφηκαν]{.greek-omitted} [σπερμα]{.greek-omitted} [εσχατη]{.greek-omitted} [παντων]{.greek-omitted} [απεθανεν]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted}[12:22]{.aside}

[και]{.greek-omitted} [ελαβον]{.greek-omitted} [αυτην]{.greek-omitted} οι επτα και ουκ αφηκαν σπερμα εσχατη [δε]{.greek-added} παντων απεθανεν [και]{.greek-omitted} η γυνη[12:22 | instance no. 2]{.aside}

εν τη [ουν]{.greek-added} αναστασει [οταν]{.greek-omitted} [αναστωσιν]{.greek-omitted} τινος αυτων [εσται]{.greek-omitted} [εστι]{.greek-added} γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκρ[ι]{.unclear}θεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [ου]{.greek-omitted} δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [γαμιζονται]{.greek-added} αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται [ουκ]{.greek-omitted} [ανεγνωτε]{.greek-omitted} [τι]{.greek-added} [γεγραπται]{.greek-added} εν τη βιβλω μωσεως επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} [[θεος]{.greek-abbr}]{.greek-added} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων εις των γραμματεων ακουσας αυτων συζητουντων ειδως οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη παντων εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω οτι πρωτη παντων [των]{.greek-omitted} εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης [της]{.greek-omitted} [ψυχης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [διανοιας]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} [σου]{.greek-omitted} [αυτη]{.greek-omitted} [πρωτη]{.greek-omitted} [εντολη]{.greek-omitted}[12:30]{.aside}

[και]{.greek-omitted} [αγαπησεις]{.greek-omitted} [κυριον]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [σου]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30 | instance no. 2]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως [εαυτον]{.greek-added} [σεαυτον]{.corr} μειζων τουτων αλλη εντολη ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως [εαυτον]{.greek-omitted} [σεαυτον]{.greek-added} πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [ο]{.greek-added} [δαυιδ]{.greek-abbr} [λεγει]{.greek-omitted} [καλει]{.greek-added} αυτον [κυριον]{.greek-abbr} [και]{.greek-omitted} [ποθεν]{.greek-omitted} [υιος]{.greek-omitted} [αυτου]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πολυς]{.greek-omitted} [οχλος]{.greek-omitted} [ηκουεν]{.greek-omitted} [αυτου]{.greek-omitted} [ηδεως]{.greek-omitted}[12:37]{.aside}

[αυτος]{.greek-omitted} [ουν]{.greek-omitted} [δαυιδ]{.greek-omitted} [λεγει]{.greek-omitted} [αυτον]{.greek-omitted} [κυριον]{.greek-omitted} και ποθεν υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37 | instance no. 2]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των [χηρων]{.greek-omitted} [χειρων]{.greek-added} και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι [πο]{.greek-added} [πλουσιοι]{.corr} εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια [πτωχη]{.greek-added} χηρα [πτωχη]{.greek-omitted} [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους [δυο]{.greek-added} μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η [χηρα]{.greek-omitted} [χειρα]{.greek-added} αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισσευματος]{.greek-added} [αυτοις]{.greek-omitted} [αυτων]{.greek-added} [εβαλον]{.greek-omitted} [εβαλλον]{.greek-added} αυτη δε εκ της υστερησεως αυτης [παντα]{.greek-omitted} [οσα]{.greek-omitted} [ειχεν]{.greek-omitted} [εβαλεν]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [βιον]{.greek-omitted} [αυτης]{.greek-omitted}[12:44]{.aside}

[παντες]{.greek-omitted} [γαρ]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [περισσευοντος]{.greek-omitted} [αυτοις]{.greek-omitted} [εβαλον]{.greek-omitted} [αυτη]{.greek-omitted} [δε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [υστερησεως]{.greek-omitted} [αυτης]{.greek-omitted} παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44 | instance no. 2]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει [αυτω]{.greek-omitted} [αυτον]{.greek-added} εις [εκ]{.greek-added} των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και [ιδε]{.greek-added} ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας [πλανησει]{.greek-added} [πλανηση]{.corr}[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν [και]{.greek-omitted} [εσονται]{.greek-omitted} [σεισμοι]{.greek-omitted} [κατα]{.greek-omitted} [τοπους]{.greek-omitted} [και]{.greek-omitted} [εσονται]{.greek-omitted} [λιμοι]{.greek-omitted} [και]{.greek-omitted} [ταραχαι]{.greek-omitted} [αρχαι]{.greek-omitted} [ωδινων]{.greek-omitted} [ταυτα]{.greek-omitted}[13:8]{.aside}

[εγερθησεται]{.greek-omitted} [γαρ]{.greek-omitted} [εθνος]{.greek-omitted} [επι]{.greek-omitted} [εθνος]{.greek-omitted} [και]{.greek-omitted} [βασιλεια]{.greek-omitted} [επι]{.greek-omitted} [βασιλειαν]{.greek-omitted} και εσονται σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι [ταυτα]{.greek-added} [δε]{.greek-added} [παντα]{.greek-added} [αρχαι]{.greek-omitted} [αρχι]{.greek-added} ωδινων [ταυτα]{.greek-omitted}[13:8 | instance no. 2]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει [κηρυχθηναι]{.greek-added} πρωτον [κηρυχθηναι]{.greek-omitted} το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [μεριμνατε]{.greek-added} τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} μηδε [μελετατε]{.greek-omitted} [μεριμνατε]{.greek-added} [τι]{.greek-added} αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το [βδελυγμα]{.greek-omitted} [βδελλυγμα]{.greek-added} της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο αναγινωσκων [νοειτω]{.greek-omitted} [οειτω]{.greek-added} τοτε οι εν τη [ιου]{.greek-added} [ιουδαια]{.greek-omitted} [φευγετωσαν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορη]{.greek-omitted}[13:14]{.aside}

[δαια]{.greek-added} [οταν]{.greek-omitted} [δε]{.greek-omitted} [ιδητε]{.greek-omitted} [το]{.greek-omitted} [βδελυγμα]{.greek-omitted} [της]{.greek-omitted} [ερημωσεως]{.greek-omitted} [το]{.greek-omitted} [ρηθεν]{.greek-omitted} [υπο]{.greek-omitted} [δανιηλ]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [εστως]{.greek-omitted} [οπου]{.greek-omitted} [ου]{.greek-omitted} [δει]{.greek-omitted} [ο]{.greek-omitted} [αναγινωσκων]{.greek-omitted} [νοειτω]{.greek-omitted} [τοτε]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ιουδαια]{.greek-omitted} φευγετωσαν εις τα ορη[13:14 | instance no. 2]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον [ων]{.greek-omitted} μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ [αι]{.greek-omitted} [εν]{.greek-added} [ταις]{.greek-added} [ημεραι]{.greek-omitted} [ημεραις]{.greek-added} [εκειναι]{.greek-omitted} [εκειναις]{.greek-added} [θλιψις]{.greek-omitted} [θλιψεις]{.greek-added} [οια]{.greek-omitted} [οιαι]{.greek-added} ου [γεγονεν]{.greek-omitted} [γεγονασιν]{.greek-added} [ουδεποτε]{.greek-added} [τοιαυτη]{.greek-omitted} [τοιαυται]{.greek-added} [απ]{.greek-omitted} [απο]{.greek-added} αρχης [κοσμου]{.greek-added} [η]{.greek-added} κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη [γενηται]{.greek-omitted} [γενονται]{.greek-added}[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added}[13:20]{.aside}

[και]{.greek-added} τοτε [εαν]{.greek-omitted} [αν]{.greek-added} τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η [ιδου]{.greek-omitted} εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν [παντα]{.greek-omitted}[13:23]{.aside}

[υμεις]{.greek-omitted} [δε]{.greek-omitted} [βλεπετε]{.greek-omitted} [ιδου]{.greek-omitted} [προειρηκα]{.greek-omitted} [υμιν]{.greek-omitted} παντα[13:23 | instance no. 2]{.aside}

αλλ [εν]{.greek-omitted} εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως πολλης και δοξης[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης ηδη ο κλαδος απαλος γενηται και εκφυη τα φυλλα γινωσκετε οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν ταυτα ιδητε [γινομενα]{.greek-omitted} γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μ[ε]{.unclear}χρις]{.greek-added} ου [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης η [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι [αγγε]{.greek-added} [αγγελοι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [ουδε]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted}[13:32]{.aside}

[περι]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} [η]{.greek-omitted} [ωρας]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ουδε]{.greek-omitted} [οι]{.greek-omitted} [λοι]{.greek-added} [των]{.greek-added} [αγγελοι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} ουδε ο υιος ει μη [μονος]{.greek-added} ο [πατηρ]{.greek-abbr}[13:32 | instance no. 2]{.aside}

βλεπετε αγρυπνειτε [και]{.greek-omitted} προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την [ε]{.unclear}ξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο κυριος της οικιας ερχεται οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης [ευρη]{.greek-omitted} [ευρησει]{.greek-added} υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω [κρατησαντες]{.greek-omitted} [αποκτεινωσιν]{.greek-omitted} [κρατησωσι]{.greek-added} [και]{.greek-added} [απολεσωσιν]{.greek-added}[14:1]{.aside}

ελεγον δε μη εν τη εορτη [μηποτε]{.greek-omitted} [ινα]{.greek-added} [μη]{.greek-added} θορυβος [εσται]{.greek-omitted} [του]{.greek-omitted} [λαου]{.greek-omitted} [γενηται]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [λαω]{.greek-added}[14:2]{.aside}

και οντος αυτου εν [βηθανια]{.greek-omitted} [βιθανια]{.greek-added} εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτου ηλθεν γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης [πολυτελους]{.greek-omitted} [πολυτιμου]{.greek-added} και συντριψασα το αλαβαστρον [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

[και]{.greek-omitted} [οντος]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} κατεχεεν αυτου κατα της κεφαλης[14:3 | instance no. 2]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο [αυτη]{.greek-omitted} [αυτηι]{.greek-added}[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-added} αφετε αυτην τι [αυτη]{.greek-omitted} [αυτηι]{.greek-added} κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη εποιησεν [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο [λαληθησεται]{.greek-added} [εις]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [κοσμον]{.greek-omitted} και ο επ[ο]{.unclear}ιησεν αυτη [λαληθησεται]{.greek-omitted} εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας [ο]{.greek-omitted} ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο αυτω αργυριον δουναι και εζητει πως [ευκαιρως]{.greek-omitted} αυτον [εν]{.greek-added} [καιρω]{.greek-added} παραδω[14:11]{.aside}

και [τη]{.greek-omitted} [τηι]{.greek-added} πρωτη ημερα των αζυμων οτε [το]{.greek-omitted} πασχα [εθυον]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [που]{.greek-omitted} [θελεις]{.greek-omitted} [απελθοντες]{.greek-omitted} [ετοιμασωμεν]{.greek-omitted} [ινα]{.greek-omitted} [φαγης]{.greek-omitted} [το]{.greek-omitted} [πασχα]{.greek-omitted}[14:12]{.aside}

[και]{.greek-omitted} [τη]{.greek-omitted} [πρωτη]{.greek-omitted} [ημερα]{.greek-omitted} [των]{.greek-omitted} [αζυμων]{.greek-omitted} [οτε]{.greek-omitted} [το]{.greek-omitted} [πασχα]{.greek-omitted} εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις [απελθοντες]{.greek-omitted} ετοιμασωμεν ινα φαγης το πασχα[14:12 | instance no. 2]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και [απαντησει]{.greek-omitted} [υπαντησει]{.greek-added} υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει ανωγεον μεγα εστρωμενον ετοιμον εκει ετοιμασατε [ημιν]{.greek-omitted} [υμιν]{.greek-added}[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν [[ητοιμασεν]{.corr}]{.greek-added} το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγει[ν]{.greek-supplied} αυτω εις καθ εις μητι εγω [ειμι]{.greek-added} και αλλος μητι εγω [ειμι]{.greek-added}[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο [εμβαπτο]{.greek-added} [εμβαπτομενος]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [τρυβλιον]{.greek-omitted}[14:20]{.aside}

[μενος]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [ο]{.greek-omitted} [εμβαπτομενος]{.greek-omitted} μετ εμου εις το τρυβλιον[14:20 | instance no. 2]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον [ευλογησας]{.greek-omitted} [ευχαριστησας]{.greek-added} [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις [και]{.corr} [ειπεν]{.corr} [λαβετε]{.corr} [φαγετε]{.corr} [τουτο]{.corr} [εστιν]{.greek-omitted} [[εστι]{.corr}]{.greek-added} [το]{.corr} [σωμα]{.corr} [μου]{.corr}[14:22]{.aside}

[και]{.corr} [λαβων]{.corr} [το]{.corr} [ποτηριον]{.corr} [ευχαριστησας]{.corr} [εδωκεν]{.corr} [αυτοι[ς]{.unclear}]{.corr} και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον [[εκχυννομενον]{.corr}]{.greek-added}[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

[αλλα]{.greek-omitted} μετα [δε]{.greek-added} το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες [σκανδαλισθησονται]{.greek-omitted} [σκανδαλισθησον]{.greek-added} [εν]{.greek-added} [σοι]{.greek-added} αλλ [ουκ]{.greek-omitted} [ου]{.greek-added} [εγω]{.greek-omitted}[14:29]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πετρος]{.greek-omitted} [εφη]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [παντες]{.greek-omitted} [σκανδαλισθησονται]{.greek-omitted} αλλ ουκ εγω[14:29 | instance no. 2]{.aside}

και λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν η δις αλεκτορα φωνησαι [τρις]{.greek-omitted} απαρνηση με [τρις]{.greek-added}[14:30]{.aside}

ο δε [πετρος]{.greek-added} [εκπερισσου]{.greek-omitted} [εκπερισου]{.greek-added} ελεγεν [μαλλον]{.greek-omitted} εαν [δεη]{.greek-added} με [δεη]{.greek-omitted} συναποθανειν σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου [καθισατε]{.corr} [ωδε]{.corr} [εως]{.corr} [προσευξωμαι]{.greek-omitted} [[προσευξομαι]{.corr}]{.greek-added}[14:32]{.aside}

[και]{.corr} [παραλαμβανει]{.corr} [τον]{.corr} [πετρον]{.corr} [και]{.corr} [ιακωβον]{.corr} [και]{.corr} [ιωαννην]{.greek-omitted} [[[ιω]{.greek-abbr}]{.corr}]{.greek-added} [μεθ]{.corr} [εαυτου]{.corr} [και]{.corr} [ηρξατο]{.corr} [εκθαμβεισθαι]{.corr} [και]{.corr} [αδημονειν]{.corr}[14:33]{.aside}

[και]{.corr} [λεγει]{.corr} [αυτοις]{.corr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε [μετ]{.greek-added} [εμου]{.greek-added}[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον απ εμου τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγο[ρ]{.unclear}ειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καταβαρυνομενοι]{.greek-added} και ουκ ηδεισαν τι [αυτω]{.greek-omitted} [αποκριθωσιν]{.greek-omitted} [αποθωσιν]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει [το]{.greek-added} [τελος]{.greek-added} ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται [ο]{.greek-added} ιουδας εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος [πολυς]{.greek-omitted} μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γραμματεων και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει δε [αυτον]{.greek-added} ο παραδιδους αυτον συσσημον αυτοις λεγων ον [αν]{.greek-omitted} [εαν]{.greek-added} φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει [αυτω]{.greek-omitted} ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον [δουλον]{.greek-omitted} του αρχιερεως [δουλον]{.greek-added} και αφειλεν αυτου το ωτιον[14:47]{.aside}

και [α]{.greek-added} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ως]{.greek-omitted} [επι]{.greek-omitted} [ληστην]{.greek-omitted} [εξηλθετε]{.greek-omitted} [μετα]{.greek-omitted} [μαχαιρων]{.greek-omitted} [και]{.greek-omitted} [ξυλων]{.greek-omitted} [συλλαβειν]{.greek-omitted} [με]{.greek-omitted}[14:48]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48 | instance no. 2]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον [οι]{.greek-added} [μαθηται]{.greek-added} παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα [γυμνος]{.greek-omitted} εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} [προς]{.greek-omitted} [επι]{.greek-added} τον αρχιερεα [καιαφαν]{.greek-added} και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος [ηκολουθησεν]{.greek-added} [αυτωι]{.greek-added} απο μακροθεν [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted} εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ [εψευδομαρτυρουν]{.greek-omitted} [εψευδομαρτυ]{.greek-added} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ισαι]{.greek-omitted} [αι]{.greek-omitted} [μαρτυριαι]{.greek-omitted} [ουκ]{.greek-omitted} [ησαν]{.greek-omitted}[14:56]{.aside}

[ρουν]{.greek-added} [πολλοι]{.greek-omitted} [γαρ]{.greek-omitted} [εψευδομαρτυρουν]{.greek-omitted} κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56 | instance no. 2]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον [αχειροποιητον]{.greek-omitted} [χειροποιητον]{.greek-added} οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι [σου]{.greek-omitted} [σοι]{.greek-added} καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς [επηρωτα]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτον [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [εκ]{.greek-added} [δευτερου]{.greek-added} [λεγων]{.greek-added} συ ει ο [χριστος]{.greek-abbr} ο υιος του [ευλογητου]{.greek-omitted} [ευλογημενου]{.greek-added}[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν [αυτον]{.greek-omitted} [αυτωι]{.greek-added} και [λεγειν]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν τη αυλη [κατω]{.greek-omitted} ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδ[ο]{.unclear}υσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε επισταμαι τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και ομνυναι οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου [ο]{.greek-added} αλεκτωρ εφωνησεν και ανεμνησθη [ο]{.greek-omitted} [πετρος]{.greek-omitted} [το]{.greek-omitted} [ρημα]{.greek-omitted} [ο]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [πριν]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} [δις]{.greek-omitted} [απαρνηση]{.greek-omitted} [με]{.greek-omitted} [τρις]{.greek-omitted} [και]{.greek-omitted} [επιβαλων]{.greek-omitted} [εκλαιεν]{.greek-omitted}[14:72]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [δευτερου]{.greek-omitted} [αλεκτωρ]{.greek-omitted} [εφωνησεν]{.greek-omitted} [και]{.greek-omitted} [ανεμνησθη]{.greek-omitted} ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} [οτι]{.greek-omitted} πριν αλεκτορα φωνησαι δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72 | instance no. 2]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} [απηνεγκαν]{.greek-omitted} [απηγαγον]{.greek-added} και παρεδωκαν [τω]{.greek-omitted} [ποντιω]{.greek-added} πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος [παλιν]{.greek-omitted} επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος [απεκριθη]{.greek-omitted} [λεγει]{.greek-added} αυτοις [λεγων]{.greek-omitted} θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεστατωσαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσως]{.greek-added} εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και παρεδωκεν [αυτοις]{.greek-added} τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον [[τον]{.corr}]{.greek-added} [[[ιησουν]{.greek-abbr}]{.corr}]{.greek-added} αυτον εσω της αυλης [[του]{.corr}]{.greek-added} [[καιαφα]{.corr}]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον [χλαμυδα]{.greek-added} [κοκκινην]{.greek-added} [και]{.greek-added} πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι [αυτον]{.greek-omitted} [χαιρε]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted}[15:18]{.aside}

[και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [ασπαζεσθαι]{.greek-omitted} αυτον χαιρε ο [βασιλευς]{.greek-omitted} [βασιλευ]{.greek-added} των ιουδαιων[15:18 | instance no. 2]{.aside}

και ετυπτον [αυτου]{.greek-omitted} την κεφαλην [αυτου]{.greek-added} καλαμω και ενεπτυον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και τιθεντες τα γονατα προσεκυνουν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[15:19]{.aside}

και οτε ενεπαιξαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον [την]{.greek-added} [χλαμυδα]{.greek-added} [και]{.greek-added} την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και [εξαγουσιν]{.greek-omitted} [αγουσιν]{.greek-added} αυτον ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν [εσμυρνισμενον]{.greek-omitted} [εσμυρνησμενον]{.greek-added} οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και [ενα]{.greek-omitted} [εξ]{.greek-omitted} [ευωνυμων]{.greek-omitted} [αυτου]{.greek-omitted}[15:27]{.aside}

[και]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [σταυρουσιν]{.greek-omitted} [δυο]{.greek-omitted} [ληστας]{.greek-omitted} [ενα]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [και]{.greek-omitted} ενα εξ ευωνυμων αυτου[15:27 | instance no. 2]{.aside}

και επληρωθη η γραφη [η]{.greek-omitted} λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και [εν]{.greek-omitted} τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [καταβηθι]{.greek-added} απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και οι [συνεσταυρωμενοι]{.greek-abbr} [συν]{.greek-added} αυτω ωνειδιζον αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και [τη]{.greek-omitted} [τηι]{.greek-added} [ωρα]{.greek-omitted} [ωραι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} [ενατη]{.greek-omitted} [[θ]{.greek-abbr}]{.greek-added} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη [λεγων]{.greek-omitted} ελωι ελωι [λιμα]{.greek-omitted} [λειμα]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβαχθανη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων [δε]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γεμισας]{.greek-omitted} [σπογγον]{.greek-omitted} [οξους]{.greek-omitted} [περιθεις]{.greek-omitted} [τε]{.greek-omitted} [καλαμω]{.greek-omitted} [εποτιζεν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [ιδωμεν]{.greek-omitted} [ει]{.greek-omitted} [ερχεται]{.greek-omitted} [ηλιας]{.greek-omitted} [καθελειν]{.greek-omitted} [αυτον]{.greek-omitted}[15:36]{.aside}

[δραμων]{.greek-omitted} δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος υιος ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην και μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και διηκονουν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και αλλαι πολλαι αι [συναναβασαι]{.greek-omitted} [συνεληλυθυιαι]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ [ο]{.greek-omitted} απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον [και]{.greek-omitted} [ητησατο]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted}[15:43]{.aside}

[ηλθεν]{.greek-omitted} [ιωσηφ]{.greek-omitted} [ο]{.greek-omitted} [απο]{.greek-omitted} [αριμαθαιας]{.greek-omitted} [ευσχημων]{.greek-omitted} [βουλευτης]{.greek-omitted} [ος]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ην]{.greek-omitted} [προσδεχομενος]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τολμησας]{.greek-omitted} [εισηλθεν]{.greek-omitted} [προς]{.greek-omitted} [πιλατον]{.greek-omitted} και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43 | instance no. 2]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκε[ν]{.unclear} [[τεθνηκε]{.corr}]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

[και]{.greek-omitted} [ο]{.greek-added} [δε]{.greek-added} [ιωσηφ]{.greek-added} αγορασας [σινδωνα]{.greek-added} [σινδονα]{.corr} και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισε]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} [σινδωνι]{.greek-added} [σινδονι]{.corr} και [κατεθηκεν]{.greek-omitted} [εθηκεν]{.greek-added} αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι [την]{.greek-omitted} [τη]{.greek-added} [θυραν]{.greek-omitted} [θυρα]{.greek-added} του μνημειου[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-added} [του]{.greek-added} ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον [εκ]{.greek-omitted} [απο]{.greek-added} της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ [μεγας]{.greek-omitted} [σφοδρα]{.greek-omitted}[16:4]{.aside}

[και]{.greek-omitted} [αναβλεψασαι]{.greek-omitted} [θεωρουσιν]{.greek-omitted} [οτι]{.greek-omitted} [αποκεκυλισται]{.greek-omitted} [ο]{.greek-omitted} [λιθος]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} μεγας σφοδρα[16:4 | instance no. 2]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [ναζαρινον]{.greek-added} τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου ειχεν δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας [[ο]{.corr}]{.greek-added} [[[ιησους]{.greek-abbr}]{.corr}]{.greek-added} δε πρωι πρωτη [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη [πο]{.greek-added} [πορευομενοις]{.greek-omitted} [εις]{.greek-omitted} [αγρον]{.greek-omitted}[16:12]{.aside}

[μετα]{.greek-omitted} [δε]{.greek-omitted} [ταυτα]{.greek-omitted} [δυσιν]{.greek-omitted} [εξ]{.greek-omitted} [αυτων]{.greek-omitted} [περιπατουσιν]{.greek-omitted} [εφανερωθη]{.greek-omitted} [εν]{.greek-omitted} [ετερα]{.greek-omitted} [μορφη]{.greek-omitted} [πορευομενοις]{.greek-omitted} [ρευομενοις]{.greek-added} εις αγρον[16:12 | instance no. 2]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και ωνειδισεν την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

[οφεις]{.greek-omitted} [οφις]{.greek-added} αρουσιν καν θανασιμον τι πιωσιν ου μη αυτους [βλαψη]{.greek-omitted} [βλαψει]{.greek-added} επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

