---
title: "Collation of Byz^RP^ vs 30803 (803)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 803 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30803).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 803                                   	| λογος                              	|
| 803 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 803 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 803               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 803                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 803 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 803                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

[α]{.greek-supplied}ρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω [ετοιμασατε]{.greek-omitted} [ετοιματε]{.greek-added} την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η [ιουδαια]{.greek-omitted} [ουδαια]{.greek-added} χωρα και οι [ιεροσολυμιται]{.greek-omitted} [εροσολυμιται]{.greek-added} και [εβαπτιζοντο]{.greek-omitted} [ευαπτιζοντο]{.greek-added} παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι [ι]{.greek-added} [ικανος]{.greek-omitted} [κυψας]{.greek-omitted} [λυσαι]{.greek-omitted} [τον]{.greek-omitted} [ιμαντα]{.greek-omitted} [των]{.greek-omitted} [υποδηματων]{.greek-omitted} [αυτου]{.greek-omitted}[1:7]{.aside}

[και]{.greek-omitted} [εκηρυσσεν]{.greek-omitted} [λεγων]{.greek-omitted} [ερχεται]{.greek-omitted} [ο]{.greek-omitted} [ισχυροτερος]{.greek-omitted} [μου]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [ου]{.greek-omitted} [ουκ]{.greek-omitted} [ειμι]{.greek-omitted} [ικανος]{.greek-omitted} [κανος]{.greek-added} κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7 | instance no. 2]{.aside}

εγω μεν [εβαπτισα]{.greek-omitted} [υμας]{.greek-omitted} [εν]{.greek-omitted} [υδατι]{.greek-omitted} [αυτος]{.greek-omitted} [δε]{.greek-omitted} [βαπτισει]{.greek-omitted} [εβαπτισει]{.greek-added} υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο ιωαννου εις τον [ιορδανην]{.greek-omitted} [ιωρδανην]{.greek-added}[1:9]{.aside}

και ευθεως [αναβαινων]{.greek-omitted} [αναβαινον]{.greek-added} απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν [καταβαινον]{.greek-omitted} [καταβενον]{.greek-added} επ αυτον[1:10]{.aside}

και φωνη [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο [απητος]{.greek-added} [αγαπητος]{.corr} εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα [πειραζομενος]{.greek-omitted} [πειραζωμενος]{.greek-added} υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδ[ο]{.unclear}θηναι [και]{.greek-added} τον [ιωαννην]{.greek-omitted} [ιωανην]{.greek-added} ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-omitted}[1:14]{.aside}

[μετα]{.greek-omitted} [δε]{.greek-omitted} [το]{.greek-omitted} [παραδοθηναι]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [ηλθεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted} [κηρυσσων]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [της]{.greek-omitted} [βασιλειας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr}[1:14 | instance no. 2]{.aside}

και λεγων οτι [πεπληρωται]{.greek-omitted} [πεπληρωτε]{.greek-added} ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και [ανδρεαν]{.greek-omitted} [ανδρε]{.greek-added} τον αδελφον αυτου του σιμωνος βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα [αυτου]{.greek-added} [αυτων]{.greek-omitted} [[αυτον]{.corr}]{.greek-added} ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον του [ζεβεδαιου]{.greek-omitted} [ζευεδαιου]{.greek-added} και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων [απηλθων]{.greek-added} [απηλθον]{.corr} οπισω αυτου[1:20]{.aside}

και [εισπορευονται]{.greek-omitted} [εισπορευοντε]{.greek-added} εις καπερναουμ και ευθεως τοις σαββασιν [εισελθων]{.greek-omitted} [εισελθον]{.greek-added} εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

[και]{.greek-omitted} εξεπλησσοντο επι τη διδαχη αυτου ην γαρ [διδασκων]{.greek-omitted} [διδασκον]{.greek-added} αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και ανεκραξεν[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαρινε]{.greek-added} ηλθες [απολεσαι]{.greek-omitted} [απολεσε]{.greek-added} ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [[πνασι]{.greek-abbr}]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης [εξελθοντες]{.greek-omitted} [εξελθων]{.greek-added} [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις την οικιαν σιμωνος και [ανδρεου]{.greek-omitted} [ανδρε]{.greek-added} [μετα]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [ιωαννου]{.greek-omitted}[1:29]{.aside}

[ου]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} [εξελθοντες]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [σιμωνος]{.greek-omitted} [και]{.greek-omitted} [ανδρεου]{.greek-omitted} μετα ιακωβου και ιωαννου[1:29 | instance no. 2]{.aside}

η δε [πενθερα]{.greek-omitted} [θερα]{.greek-added} [του]{.greek-added} σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και [προσελθων]{.greek-omitted} [προσελθον]{.greek-added} ηγειρεν αυτην κρατησας [αυτην]{.greek-added} της χειρος [αυτης]{.greek-omitted} και [ευθεως]{.greek-added} αφηκεν αυτην ο πυρετος [ευθεως]{.greek-omitted} και [διηκονει]{.greek-omitted} [διηκον]{.greek-added} αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους [δαιμονιζομενους]{.greek-omitted} [δαιμονιζωμενους]{.greek-added}[1:32]{.aside}

και η πολις [ολη]{.greek-omitted} [ολ]{.greek-added} επισυνηγμενη ην προς την [θυραν]{.greek-omitted} [θυρα]{.greek-added}[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις [νοσοις]{.greek-omitted} [νοσεις]{.greek-added} και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον[1:34]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις [ερημον]{.greek-omitted} [ερημων]{.greek-added} τοπον κακει προσηυχετο[1:35]{.aside}

και κατεδιωξαν αυτον ο σιμων [και]{.corr} [οι]{.corr} [μετ]{.corr} [αυτου]{.corr}[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας [εχω]{.greek-added} [εχομενας]{.greek-omitted} [κωμοπολεις]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [εκει]{.greek-omitted} [κηρυξω]{.greek-omitted} [εις]{.greek-omitted} [τουτο]{.greek-omitted} [γαρ]{.greek-omitted} [εξεληλυθα]{.greek-omitted}[1:38]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [αγωμεν]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [εχομενας]{.greek-omitted} [μενας]{.greek-added} [κωμοπολεις]{.greek-omitted} [κωμωπολεις]{.greek-added} ινα και εκει κηρυξω εις τουτο γαρ εξεληλυθα[1:38 | instance no. 2]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} προς αυτον λεπρος παρακαλων αυτον και γονυπετων [αυτον]{.greek-omitted} και λεγων [αυτων]{.greek-added} [αυτω]{.corr} οτι εαν θελης [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις [εκ[αι]{.unclear}τεινας]{.greek-added} [εκτεινας]{.corr} την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} περι του καθαρισμου σου α προσεταξεν μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον [δυνασθαι]{.greek-omitted} [φανερως]{.greek-omitted} [εις]{.greek-omitted} [πολιν]{.greek-omitted} [εισελθειν]{.greek-omitted} [αλλ]{.greek-omitted} [εξω]{.greek-omitted} [εν]{.greek-omitted} [ερημοις]{.greek-omitted} [τοποις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ηρχοντο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πανταχοθεν]{.greek-omitted}[1:45]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εξελθων]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [πολλα]{.greek-omitted} [και]{.greek-omitted} [διαφημιζειν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ωστε]{.greek-omitted} [μηκετι]{.greek-omitted} [αυτον]{.greek-omitted} δυνασθαι φανερως [εις]{.greek-omitted} [ει]{.greek-added} πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45 | instance no. 2]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς [την]{.greek-omitted} [τη]{.greek-added} θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και [εξορυξαντες]{.greek-omitted} [ωρυξαντες]{.greek-added} [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

[ιδων]{.greek-omitted} [ειδων]{.greek-added} δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι [αμαρτιαι]{.greek-omitted} [αμαρτιαις]{.greek-added} σου[2:5]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} [ουτος]{.greek-added} λαλει βλασφημιας τις δυναται [αφιεναι]{.greek-omitted} [αμαρτιας]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εις]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted}[2:7]{.aside}

[τι]{.greek-omitted} [ουτος]{.greek-omitted} [ουτως]{.greek-omitted} [λαλει]{.greek-omitted} [βλασφημιας]{.greek-omitted} [τις]{.greek-omitted} [δυναται]{.greek-omitted} αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7 | instance no. 2]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} [τω]{.greek-omitted} [το]{.greek-added} [πνευματι]{.greek-abbr} αυτου οτι [ουτος]{.greek-added} [ουτως]{.corr} αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι [ταυ[―]{.gap}α]{.greek-added} [ταυτα]{.corr} [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις [υμων]{.greek-omitted} [ημων]{.greek-added}[2:8]{.aside}

τι εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον σου τον κραββατον και περιπατει[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ιδιτε]{.greek-added} οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} αφιεναι επι της γης αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι [λεγω]{.greek-omitted} [λεγων]{.greek-added} εγειραι και αρον τον κραββατον σου και [υπαγε]{.greek-omitted} [ειπαγε]{.greek-added} εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν [αναντιων]{.greek-added} [[εναντιων]{.corr}]{.greek-added} [εναντιον]{.greek-omitted} [εναντιοων]{.greek-added} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι [ουδεποτε]{.greek-omitted} [ουδεποται]{.greek-added} ουτως ειδομεν[2:12]{.aside}

και εξηλθεν παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και [εδιδασκεν]{.greek-omitted} [διδασκεν]{.greek-added} αυτους[2:13]{.aside}

και παραγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [λευι]{.greek-omitted} [τον]{.greek-omitted} [του]{.greek-omitted} [αλφαιου]{.greek-omitted} [καθημενον]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [τελωνιον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [αναστας]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted}[2:14]{.aside}

[και]{.greek-omitted} [παραγων]{.greek-omitted} [ειδεν]{.greek-omitted} [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[2:14 | instance no. 2]{.aside}

και εγενετο εν τω [κατακεισθαι]{.greek-omitted} [κατακισθαι]{.greek-added} αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι [γραμματ[―]{.gap}ις]{.greek-added} [γραμματεις]{.corr} και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων [ελεγον]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [τι]{.greek-omitted} [οτι]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι των [φαρισαιων]{.greek-omitted} [φαροισαιων]{.greek-added} [νηστευοντες]{.greek-omitted} [νηστευωντες]{.greek-added} και ερχονται και λεγουσιν αυτω δια τι οι μαθηται [ο]{.greek-added} ιωαννου και οι των [φαρισαιων]{.greek-omitted} [φαροισαιων]{.greek-added} [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added} οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται [υι]{.greek-added} [οι]{.greek-omitted} [υιοι]{.greek-omitted} [του]{.greek-omitted} [νυμφωνος]{.greek-omitted} [εν]{.greek-omitted} [ω]{.greek-omitted} [ο]{.greek-omitted} [νυμφιος]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted} [εστιν]{.greek-omitted} [νηστευειν]{.greek-omitted} [οσον]{.greek-omitted} [χρονον]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [εχουσιν]{.greek-omitted} [τον]{.greek-omitted} [νυμφιον]{.greek-omitted} [ου]{.greek-omitted} [δυνανται]{.greek-omitted} [νηστευειν]{.greek-omitted}[2:19]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [μη]{.greek-omitted} [δυνανται]{.greek-omitted} οι [υιοι]{.greek-omitted} του νυμφωνος εν ω ο [νυμφιος]{.greek-omitted} [νμφιος]{.greek-added} μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19 | instance no. 2]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευουσιν]{.greek-added} εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα [ρακους]{.greek-omitted} [ρακκους]{.greek-added} αγναφου επιρραπτει επι ιματιω παλαιω ει δε μη αιρει το [πληρωμα]{.greek-omitted} [πληρομα]{.greek-added} αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη [ρησσει]{.greek-omitted} [ρησει]{.greek-added} ο [οινος]{.greek-omitted} [οινον]{.greek-added} [ο]{.greek-omitted} [νεον]{.greek-added} [νεος]{.corr} [[ει]{.unclear}ς]{.greek-added} τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται αλλα οινον νεον εις ασκους καινους βλητεον[2:22]{.aside}

και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} παραπορευεσθαι αυτον εν τοις [σαββασιν]{.greek-omitted} [σαβ[β]{.unclear}ασι]{.greek-added} δια [τον]{.greek-added} [των]{.corr} σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι [φαρισαιοι]{.greek-omitted} [φαροισαιοι]{.greek-added} ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν [ο]{.greek-omitted} [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted}[2:24]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ελεγον]{.greek-omitted} [αυτω]{.greek-omitted} [ιδε]{.greek-omitted} [τι]{.greek-omitted} [ποιουσιν]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24 | instance no. 2]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι εποιησεν [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added} αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν [ε]{.greek-added} ει μη τοις [ιερευσιν]{.greek-omitted} [ερευσι]{.greek-added} [μονοις]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν [αυτω]{.greek-omitted} [α[―]{.gap}του]{.greek-added} [[αυτου]{.corr}]{.greek-added} [μετα]{.greek-added} [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ [ο]{.greek-omitted} [ου]{.greek-added} [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} [εχων]{.greek-omitted} [εχον]{.greek-added} την χειρα[3:1]{.aside}

και παρετηρουν αυτον [ει]{.greek-omitted} [εις]{.greek-added} τοις σαββασιν θεραπευσει αυτον ινα [κατηγορησωσιν]{.greek-omitted} [κατιγωρισωσιν]{.greek-added} αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις εξεστιν [εν]{.greek-added} τοις σαββασιν αγαθοποιησαι η [κακοποιησαι]{.greek-omitted} [κακοποιη]{.greek-added} [ψυχην]{.greek-omitted} [σωσαι]{.greek-omitted} [η]{.greek-omitted} [αποκτειναι]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [εσιωπων]{.greek-omitted}[3:4]{.aside}

[σαι]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [εξεστιν]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [αγαθοποιησαι]{.greek-omitted} [η]{.greek-omitted} [κακοποιησαι]{.greek-omitted} ψυχην σωσαι η αποκτειναι οι δε [εσιωπων]{.greek-omitted} [σιωπων]{.greek-added}[3:4 | instance no. 2]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πωρρωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και αποκατεσταθη η [χειρ]{.greek-omitted} [χειρα]{.greek-added} αυτου υγιης ως η αλλη[3:5]{.aside}

και εξελθοντες οι [φαρισαιοι]{.greek-omitted} [φαροισαιοι]{.greek-added} ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον απολεσωσιν[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} [τα]{.greek-added} [μετα]{.corr} των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο [της]{.greek-omitted} ιδουμαιας και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα [πλοιαριον]{.greek-omitted} [πληαριον]{.greek-added} [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη θλιβωσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added}[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε [επιτωπειν]{.greek-added} [επιπιπτειν]{.corr} αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} οσοι [ει]{.greek-added} [ειχον]{.greek-omitted} [μαστιγας]{.greek-omitted}[3:10]{.aside}

[πολλους]{.greek-omitted} [γαρ]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [ωστε]{.greek-omitted} [επιπιπτειν]{.greek-omitted} [αυτω]{.greek-omitted} [ινα]{.greek-omitted} [αυτου]{.greek-omitted} [αψωνται]{.greek-omitted} [οσοι]{.greek-omitted} [ειχον]{.greek-omitted} [χον]{.greek-added} μαστιγας[3:10 | instance no. 2]{.aside}

και τα [πευματα]{.greek-added} [πνευματα]{.corr} τα ακαθαρτα οταν αυτον [εθεωρει]{.greek-omitted} [προσεπιπτεν]{.greek-omitted} [εθεωρουν]{.greek-added} [προς]{.greek-added} [αυτον]{.greek-added} [επιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και [αν[ε]{.unclear}βαινει]{.greek-added} [αναβαινει]{.corr} εις το [ορος]{.greek-omitted} [ορ]{.greek-added} και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [ποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και [εκβαλλειν]{.greek-omitted} [εκβαλειν]{.greek-added} τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του [ζεβεδαιου]{.greek-omitted} [ζεβαιδαιου]{.greek-added} και ιωαννην τον αδελφον του [[αυτου]{.corr}]{.greek-added} ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο [εστιν]{.greek-omitted} [εστνι]{.greek-added} υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην [ος]{.greek-omitted} [ως]{.greek-added} και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

και [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} [και]{.greek-added} [συνερχεται]{.greek-omitted} [συνερχονται]{.greek-added} παλιν [οχλος]{.greek-omitted} [οχλοι]{.greek-added} ωστε μη [δυνασθαι]{.greek-omitted} [δυνασθε]{.greek-added} αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} [οτι]{.greek-omitted} [ο]{.greek-added} βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν [παραβολε]{.greek-added} [παραβολαις]{.corr} ελεγεν [αυτοις]{.greek-omitted} [αυτης]{.greek-added} πως δυναται [σατα[―]{.gap}ας]{.greek-added} [σατανας]{.corr} [σαταναν]{.greek-omitted} [σατανα]{.greek-added} [εκβαλλειν]{.greek-omitted} [εκβαλλει]{.greek-added}[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου [δυναται]{.greek-omitted} [δυναι]{.greek-added} σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και [μεμερισται]{.greek-omitted} [μερισται]{.greek-added} ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου [εισελθων]{.greek-omitted} [εισελθον]{.greek-added} εις την οικιαν αυτου διαρπασαι [εαν]{.greek-omitted} [ενα]{.greek-added} μη πρωτον τον [ισχυρον]{.greek-omitted} [εισχυρον]{.greek-added} δηση και τοτε [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπαση]{.greek-omitted}[3:27]{.aside}

[ουδεις]{.greek-omitted} [δυναται]{.greek-omitted} [τα]{.greek-omitted} [σκευη]{.greek-omitted} [του]{.greek-omitted} [ισχυρου]{.greek-omitted} [εισελθων]{.greek-omitted} [εις]{.greek-omitted} την οικιαν αυτου διαρπασαι [εαν]{.greek-omitted} [μη]{.greek-omitted} [πρωτον]{.greek-omitted} [τον]{.greek-omitted} [ισχυρον]{.greek-omitted} [δηση]{.greek-omitted} [και]{.greek-omitted} [τοτε]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπαση]{.greek-omitted}[3:27 | instance no. 2]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημιεις]{.greek-added} [βλασφημηση]{.greek-omitted} [[βλασφημισει]{.corr}]{.greek-added} [εις]{.corr} το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον πνευμα ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες [απεστειλαν]{.greek-omitted} [απεστηλαν]{.greek-added} προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο [περι]{.greek-added} [αυτων]{.greek-added} οχλος [πολυς]{.greek-added} [περι]{.greek-omitted} [αυτον]{.greek-omitted} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους [περι]{.greek-omitted} [περ]{.greek-added} αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ [αν]{.greek-omitted} [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} [το]{.greek-omitted} [θελημα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ουτος]{.greek-omitted} [αδελφος]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [αδελφη]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [μητηρ]{.greek-omitted} [εστιν]{.greek-omitted}[3:35]{.aside}

[ος]{.greek-omitted} [γαρ]{.greek-omitted} [αν]{.greek-omitted} [ποιηση]{.greek-omitted} το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35 | instance no. 2]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον [καθησθαι]{.greek-omitted} [καθησθε]{.greek-added} εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις [εν]{.greek-omitted} τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι [[τον]{.corr}]{.greek-added} [[σπορον]{.corr}]{.greek-added} [[αυτου]{.corr}]{.greek-added}[4:3]{.aside}

και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} εν τω σπειρειν ο μεν επεσεν παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το [[τα]{.corr}]{.greek-added} πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο [ε]{.greek-added} [επεσεν]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [ακανθας]{.greek-omitted} [και]{.greek-omitted} [ανεβησαν]{.greek-omitted} [αι]{.greek-omitted} [ακανθαι]{.greek-omitted} [και]{.greek-omitted} [συνεπνιξαν]{.greek-omitted} [αυτο]{.greek-omitted} [και]{.greek-omitted} [καρπον]{.greek-omitted} [ουκ]{.greek-omitted} [εδωκεν]{.greek-omitted}[4:7]{.aside}

[και]{.greek-omitted} [αλλο]{.greek-omitted} [επεσεν]{.greek-omitted} [πεσεν]{.greek-added} εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7 | instance no. 2]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} [εξηκοντα]{.greek-omitted} [ξηκοντα]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο [εχων]{.greek-omitted} [εχον]{.greek-added} ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μ[ω]{.unclear}νας]{.greek-added} [[μονας]{.corr}]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν [δεδοται]{.greek-omitted} [δεδωται]{.greek-added} [μονοις]{.greek-added} γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και [ου]{.greek-added} μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και [λεγει]{.greek-omitted} [ελεγει]{.greek-added} αυτοις ουκ οιδατε την παραβολην [ταυτην]{.greek-omitted} [και]{.greek-omitted} [πως]{.greek-omitted} [πασας]{.greek-omitted} [τας]{.greek-omitted} [παραβολας]{.greek-omitted} [γνωσεσθε]{.greek-omitted}[4:13]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ουκ]{.greek-omitted} [οιδατε]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} ταυτην και πως πασας τας παραβολας [γνωσεσθε]{.greek-omitted} [γνωσεσθαι]{.greek-added}[4:13 | instance no. 2]{.aside}

ο [σπειρον]{.greek-added} [σπειρων]{.corr} τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και [αιρει]{.greek-omitted} [ερει]{.greek-added} τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας [λαμβανουσιν]{.greek-omitted} [λαμββανουσιν]{.greek-added} αυτον[4:16]{.aside}

και ουκ εχουσιν ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης [θλιψεως]{.greek-omitted} [θληψεως]{.greek-added} η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας [ακαθας]{.greek-added} [ακανθας]{.corr} σπειρομενοι οι τον λογον [λογον]{.greek-added} ακουοντες[4:18]{.aside}

και [αι]{.greek-omitted} μεριμναι του αιωνος τουτου και η απατη του πλουτου και [αι]{.greek-omitted} [ε]{.greek-added} περι τα λοιπα επιθυμιαι εισπορευομεναι συμπνιγουσιν [[συμπνιγουσι]{.corr}]{.greek-added} τον λογον [και]{.greek-omitted} [ακαρπος]{.greek-omitted} [γινεται]{.greek-omitted}[4:19]{.aside}

και [αι]{.greek-omitted} [μεριμναι]{.greek-omitted} [του]{.greek-omitted} [αιωνος]{.greek-omitted} [τουτου]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [απατη]{.greek-omitted} [του]{.greek-omitted} [πλουτου]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [περι]{.greek-omitted} [τα]{.greek-omitted} [λοιπα]{.greek-omitted} [επιθυμιαι]{.greek-omitted} [εισπορευομεναι]{.greek-omitted} [συμπνιγουσιν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [ακαρπος]{.greek-omitted} [ακαρπον]{.greek-added} γινεται[4:19 | instance no. 2]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την [κλινην]{.greek-omitted} [κληνην]{.greek-added} ουχ ινα επι την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον ο εαν μη φανερωθη ουδε [εγενετο]{.greek-omitted} [εγεντο]{.greek-added} αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} τι [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} εν ω μετρω μετρειτε [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [εχη]{.greek-omitted} [εχει]{.greek-added} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν [ουτως]{.greek-omitted} [ουτος]{.greek-added} εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [βαλλει]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και καθευδη και εγειρ[η]{.unclear}ται [[εγειρεται]{.corr}]{.greek-added} νυκτα [και]{.greek-omitted} [ημεραν]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [σπορος]{.greek-omitted} [βλαστανη]{.greek-omitted} [και]{.greek-omitted} [μηκυνηται]{.greek-omitted} [ως]{.greek-omitted} [ουκ]{.greek-omitted} [οιδεν]{.greek-omitted} [αυτος]{.greek-omitted}[4:27]{.aside}

[και]{.greek-omitted} [καθευδη]{.greek-omitted} [και]{.greek-omitted} [εγειρηται]{.greek-omitted} [νυκτα]{.greek-omitted} και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και μηκυνηται ως ουκ οιδεν αυτος[4:27 | instance no. 2]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα [σταχυν]{.greek-omitted} [σταχειν]{.greek-added} ειτα πληρη σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσομεν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως κοκκον [σι[―]{.gap}απαιως]{.greek-added} [σιναπεως]{.greek-omitted} [[σιναπαιως]{.corr}]{.greek-added} ος οταν σπαρη επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [αυξηθη]{.greek-added} αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε [δυνασθαι]{.greek-omitted} [δυνασθε]{.greek-added} υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-omitted} [[ουνου]{.greek-abbr}]{.greek-added} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις [πολλ[ης]{.unclear}]{.greek-added} [πολλαις]{.corr} [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

[χωρις]{.greek-omitted} [χωρεις]{.greek-added} δε [παραβολης]{.greek-omitted} [παραβολην]{.greek-added} ουκ ελαλει αυτοις [κατ]{.greek-omitted} [κα]{.greek-added} [ιδιαν]{.greek-omitted} [δε]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [επελυεν]{.greek-omitted} [παντα]{.greek-omitted}[4:34]{.aside}

[τ]{.greek-added} [χωρις]{.greek-omitted} [δε]{.greek-omitted} [παραβολης]{.greek-omitted} [ουκ]{.greek-omitted} [ελαλει]{.greek-omitted} [αυτοις]{.greek-omitted} [κατ]{.greek-omitted} ιδιαν δε τοις μαθηταις [ε]{.greek-added} [αυτου]{.corr} [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34 | instance no. 2]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα [οψιας]{.greek-omitted} [οψειας]{.greek-added} γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην [εν]{.greek-omitted} [τω]{.greek-omitted} [εις]{.greek-added} [το]{.greek-added} πλοιω και αλλα δε [πλοιαρια]{.greek-omitted} [πλοια]{.greek-added} ην μετ αυτου[4:36]{.aside}

και γινεται λαιλαψ ανεμου [μεγαλη]{.greek-omitted} [μεγαλου]{.greek-added} τα δε [κυματα]{.greek-omitted} [κυμα]{.greek-added} [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε [αυτο]{.greek-omitted} [αυτω]{.greek-added} ηδη [γεμιζεσθαι]{.greek-omitted} [γεμηζεσθαι]{.greek-added}[4:37]{.aside}

και ην αυτος επι [τη]{.greek-omitted} [την]{.greek-added} πρυμνη επι το προσκεφαλαιον [καθευδων]{.greek-omitted} [καθευδον]{.greek-added} και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου μελει σοι οτι [απολυμεθα]{.greek-added} [απολλυμεθα]{.corr}[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι [δειλοι]{.greek-omitted} [διλοι]{.greek-added} [εστε]{.greek-omitted} [εσται]{.greek-added} ουτως πως ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον [μεγαν]{.greek-omitted} [μεγα]{.greek-added} [και]{.greek-omitted} [ελεγον]{.greek-omitted} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [τις]{.greek-omitted} [αρα]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [θαλασσα]{.greek-omitted} [υπακουουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[4:41]{.aside}

[και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted} [φοβον]{.greek-omitted} [μεγαν]{.greek-omitted} και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41 | instance no. 2]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γαδαρινων]{.greek-added}[5:1]{.aside}

και [εξελθοντι]{.greek-omitted} [εξεθοντι]{.greek-added} αυτω εκ του πλοιου ευθεως [απηντησεν]{.greek-omitted} [υπηντισεν]{.greek-added} αυτω εκ των [[ανθρωπος]{.greek-abbr}]{.greek-added} [εκ]{.greek-added} [των]{.greek-added} μνημειων [ανθρωπος]{.greek-omitted} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

[ος]{.greek-omitted} [ως]{.greek-added} την κατοικησιν ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις [εδυνατο]{.greek-omitted} [ηδυνατω]{.greek-added} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεισι]{.greek-added} [αλυσεσιν]{.greek-omitted} [[αλυσεσι]{.corr}]{.greek-added} δεδεσθαι και [διασπασασθε]{.greek-added} [διεσπασθαι]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} τας αλυσεις [αυ]{.greek-added} [[απ]{.corr}]{.greek-added} [αυτου]{.greek-added} και τας [πεδας]{.greek-omitted} [παιδας]{.greek-added} συντετριφθαι και ουδεις αυτον [ισχυεν]{.greek-omitted} [ισχυε]{.greek-added} δαμασαι[5:4]{.aside}

και δια [παντος]{.greek-omitted} [παντως]{.greek-added} νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις μνημασιν ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη [μεγαλει]{.greek-added} [μεγαλη]{.corr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [εγε]{.greek-added} γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι [[εστιν]{.corr}]{.greek-added} ονομα και απεκριθη λεγων [λεγ[―]{.gap}ν]{.greek-added} [λεγεων]{.corr} ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη αυτους [αποστειλη]{.greek-omitted} [αποστειλει]{.greek-added} εξω της χωρας[5:10]{.aside}

ην δε εκει προς τω ορει αγελη χοιρων [μεγαλει]{.greek-added} [μεγαλη]{.corr} βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον [παντες]{.greek-omitted} οι [δαιμονες]{.greek-omitted} [δαιμοναις]{.greek-added} λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους [ελθωμεν]{.greek-added} [εισελθωμεν]{.greek-omitted} [[ειελθωμεν]{.corr}]{.greek-added}[5:12]{.aside}

και [επετρεψεν]{.greek-omitted} [επεστρεψεν]{.greek-added} αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα πνευματα τα [ακαθαρτα]{.greek-omitted} [ακαθρτα]{.greek-added} εισηλθον [εις]{.greek-omitted} [προς]{.greek-added} τους χοιρους και [ωρμησεν]{.greek-omitted} [ορμησεν]{.greek-added} η αγελη κατα του [κρημνου]{.greek-omitted} [κριμνου]{.greek-added} εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους [αγρους]{.greek-omitted} [και]{.greek-omitted} [εξηλθον]{.greek-omitted} [ιδειν]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [γεγονος]{.greek-omitted}[5:14]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [βοσκοντες]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [εφυγον]{.greek-omitted} [και]{.greek-omitted} [ανηγγειλαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14 | instance no. 2]{.aside}

και [ερχονται]{.greek-omitted} [ερχωνται]{.greek-added} προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον [κιματισμενον]{.greek-added} και [ιματισμενον]{.greek-omitted} [και]{.greek-omitted} [σωφρονουντα]{.greek-omitted} [σοφρονουντα]{.greek-added} τον εσχηκοτα τον λεγεωνα και [εφοβηθησαν]{.greek-omitted} [εφοβοιθησαν]{.greek-added}[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω [δαιμονιζομενω]{.greek-omitted} [δαιμονιζωμενω]{.greek-added} και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβανοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

[ουδε]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} [συνηχθη]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted}[5:21]{.aside}

[και]{.greek-omitted} [διαπερασαντος]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} [παλιν]{.greek-omitted} εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21 | instance no. 2]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και [ιδων]{.greek-omitted} [ιδον]{.greek-added} [αυτον]{.greek-omitted} πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκουλουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν [ρυσει]{.greek-omitted} [ρυσσει]{.greek-added} αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα [παρ]{.corr} [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν [ωφεληθεισα]{.greek-omitted} [οφεληθεισα]{.greek-added} αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [εν]{.greek-added} [εαυτη]{.greek-added} οτι καν των ιματιων αυτου αψωμαι [σωθησομαι]{.greek-omitted} [σωθησωμαι]{.greek-added}[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης [και]{.greek-omitted} [εγνω]{.greek-omitted} [τω]{.greek-omitted} [σωματι]{.greek-omitted} [οτι]{.greek-omitted} [ιαται]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαστιγος]{.greek-omitted}[5:29]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [εξηρανθη]{.greek-omitted} [η]{.greek-omitted} [πηγη]{.greek-omitted} [του]{.greek-omitted} [αιματος]{.greek-omitted} [αυτης]{.greek-omitted} και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29 | instance no. 2]{.aside}

και ευθεως [επι]{.greek-added} ο [ιησους]{.greek-abbr} [επιγνους]{.greek-omitted} εν εαυτω την εξ αυτου δυναμιν εξελθουσαν [επιστραφεις]{.greek-omitted} [επιστραφης]{.greek-added} εν [τω]{.greek-omitted} [οχλω]{.greek-omitted} [το]{.greek-added} [οχλον]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον [συνθλιβοντα]{.greek-omitted} [συνθληβοντα]{.greek-added} σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη [φοβηθεισα]{.greek-omitted} [φοβηθησα]{.greek-added} και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε [υπαγε]{.greek-omitted} [ειπαγε]{.greek-added} εις ειρηνην και [ισθι]{.greek-omitted} [ισθη]{.greek-added} υγιης απο της [μαστιγος]{.greek-omitted} [μαστιγους]{.greek-added} σου[5:34]{.aside}

ετι αυτου λαλουντος [ερχονται]{.greek-omitted} [ερχον]{.greek-added} απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [επεθανε]{.greek-added} τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω [συνακολουθησαι]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [πετρον]{.greek-omitted} [και]{.greek-omitted} [ιακωβον]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [τον]{.greek-omitted} [αδελφον]{.greek-omitted} [ιακωβου]{.greek-omitted}[5:37]{.aside}

[και]{.greek-omitted} [ουκ]{.greek-omitted} [αφηκεν]{.greek-omitted} [ουδενα]{.greek-omitted} [αυτω]{.greek-omitted} συνακολουθησαι ει μη πετρον και ιακωβον και ιωαννην τον αδελφον [αυτου]{.greek-added} ιακωβου[5:37 | instance no. 2]{.aside}

και [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} εις τον οικον του [αρχισυναγωγου]{.greek-omitted} [αρχισυναγωγον]{.greek-added} και θεωρει θορυβον [και]{.greek-added} κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και [εισελθων]{.greek-omitted} [εισελθον]{.greek-added} λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβησθαι]{.greek-added} και [κλαιετε]{.greek-omitted} [κλαιεται]{.greek-added} [το]{.greek-omitted} [του]{.greek-added} παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και [κρατησας]{.greek-omitted} [κρατισας]{.greek-added} της χειρος του παιδιου λεγει αυτη [ταλιθα]{.greek-omitted} [ταληθα]{.greek-added} [κουμι]{.greek-omitted} [κουμη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι [λεγω]{.greek-omitted} [λεγων]{.greek-added} εγειραι[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων [δωδεκα]{.greek-omitted} [δωδακα]{.greek-added} και εξεστησαν [[οι]{.corr}]{.greek-added} [[γονεις]{.corr}]{.greek-added} [αυτης]{.greek-added} εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και [ειπεν]{.greek-omitted} [δοθηναι]{.greek-omitted} [αυτη]{.greek-omitted} [φαγειν]{.greek-omitted}[5:43]{.aside}

[και]{.greek-omitted} [διεστειλατο]{.greek-omitted} [αυτοις]{.greek-omitted} [πολλα]{.greek-omitted} [ινα]{.greek-omitted} [μηδεις]{.greek-omitted} [γνω]{.greek-omitted} [τουτο]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43 | instance no. 2]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η σοφια η δοθεισα αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ [ουπ]{.greek-added} [ουτος]{.corr} εστιν ο τεκτων ο υιος μαριας αδελφος δε [ιουδα]{.greek-added} [και]{.greek-added} ιακωβου και ιωση [και]{.greek-omitted} [ιουδα]{.greek-omitted} και σιμωνος και ουκ εισιν [αι]{.greek-omitted} αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ εστι[ν]{.unclear} [[εστι]{.corr}]{.greek-added} προφητης ατιμος ει [μη]{.greek-omitted} [μι]{.greek-added} εν τη [πατριδι]{.greek-abbr} αυτου και εν τοις συγγενεσιν [αυτου]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο [εκει]{.greek-omitted} ουδεμιαν δυναμιν ποιησαι [εκει]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμασε]{.greek-added} δια την [απι]{.greek-added} [απιστιαν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [περιηγεν]{.greek-omitted} [τας]{.greek-omitted} [κωμας]{.greek-omitted} [κυκλω]{.greek-omitted} [διδασκων]{.greek-omitted}[6:6]{.aside}

[και]{.greek-omitted} [εθαυμαζεν]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [απιστιαν]{.greek-omitted} [στιαν]{.greek-added} αυτων και [περιηγεν]{.greek-omitted} [περιη]{.greek-added} τας κωμας κυκλω διδασκων[6:6 | instance no. 2]{.aside}

και [προσκαλειται]{.greek-omitted} [προσκαλειτε]{.greek-added} τους δωδεκα και ηρξατο αυτους [αποστελλειν]{.greek-omitted} [αποτελλειν]{.greek-added} δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει [μη]{.greek-omitted} [μι]{.greek-added} ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδεδυσθαι]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η γομορροις εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και [εξελθοντες]{.greek-omitted} [εξελοντες]{.greek-added} εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησω]{.greek-added}[6:12]{.aside}

[σι]{.greek-added} [και]{.greek-omitted} [εξελθοντες]{.greek-omitted} [εκηρυσσον]{.greek-omitted} [ινα]{.greek-omitted} [μετανοησωσιν]{.greek-omitted}[6:12 | instance no. 2]{.aside}

και [δαιμονια]{.greek-omitted} [δαιμονι]{.greek-added} πολλα [εξεβαλλον]{.greek-omitted} [εξεβαλον]{.greek-added} και [ηλειφον]{.greek-omitted} [ειλειφον]{.greek-added} ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [φανερον]{.greek-omitted} [γαρ]{.greek-omitted} [εγενετο]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} και ελεγεν οτι [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον [ο]{.greek-added} [π[ρ]{.unclear}[ο]{.greek-supplied}φητ[ης]{.unclear}]{.greek-added} [οτι]{.corr} [ηλιας]{.corr} εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} [ιωαννην]{.greek-omitted} [ιωαννου]{.greek-added} [ουτος]{.greek-omitted} [αυτος]{.greek-added} εστιν αυτος ηγερθη εκ [των]{.greek-added} νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο ιωαννης τω ηρωδη οτι ουκ εξεστι[ν]{.unclear} σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ [ηδυνατο]{.greek-omitted} [η]{.greek-added}[6:19]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [ηρωδιας]{.greek-omitted} [ενειχεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [αυτον]{.greek-omitted} [αποκτειναι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνατο]{.greek-omitted} [δυνατο]{.greek-added}[6:19 | instance no. 2]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητο]{.greek-added} τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα [εποιει]{.greek-omitted} [εποιη]{.greek-added} και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν με αιτησης δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον [βασιλεα]{.greek-omitted} [βασιλειαν]{.greek-added} [ητη]{.greek-added} [ητησατο]{.greek-omitted} [λεγουσα]{.greek-omitted} [θελω]{.greek-omitted} [ινα]{.greek-omitted} [μοι]{.greek-omitted} [δως]{.greek-omitted} [εξαυτης]{.greek-omitted} [επι]{.greek-omitted} [πινακι]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [ιωαννου]{.greek-omitted} [του]{.greek-omitted} [βαπτιστου]{.greek-omitted}[6:25]{.aside}

[σατο]{.greek-added} [και]{.greek-omitted} [εισελθουσα]{.greek-omitted} [ευθεως]{.greek-omitted} [μετα]{.greek-omitted} [σπουδης]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [βασιλεα]{.greek-omitted} [ητησατο]{.greek-omitted} λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25 | instance no. 2]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα [επεταξεν]{.greek-omitted} [επαταξεν]{.greek-added} ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτου]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την [κεφαλην]{.greek-omitted} [φαλην]{.greek-added} αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και [ακουσαντες]{.greek-omitted} [ακουσαιτες]{.greek-added} [οι]{.greek-omitted} [[ακουσαστες]{.corr}]{.greek-added} [η]{.greek-added} μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπα]{.greek-added} [αναπαυεσθε]{.greek-omitted} [ολιγον]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [ερχομενοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [υπαγοντες]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ουδε]{.greek-omitted} [φαγειν]{.greek-omitted} [ευκαιρουν]{.greek-omitted}[6:31]{.aside}

[βεσθε]{.greek-added} [λιγον]{.greek-added} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [δευτε]{.greek-omitted} [υμεις]{.greek-omitted} [αυτοι]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [εις]{.greek-omitted} [ερημον]{.greek-omitted} [τοπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [ολιγον]{.corr} [ησαν]{.greek-omitted} [εισαν]{.greek-added} γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκεραιουν]{.greek-added}[6:31 | instance no. 2]{.aside}

και απηλθον εις ερημον [τοπον]{.greek-omitted} [τοπων]{.greek-added} τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και [πεζη]{.greek-omitted} [πεζοι]{.greek-added} απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} [αυτους]{.greek-omitted} [αυτου]{.greek-added} και συνηλθον προς αυτον[6:33]{.aside}

και [εξελθων]{.greek-omitted} [εξελθον]{.greek-added} [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ειδε]{.greek-added} [πολυν]{.greek-omitted} [πολην]{.greek-added} οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη [πολλης]{.greek-added} ωρας [πολλης]{.greek-omitted} γενομενης προσελθοντες αυτω οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν [εαυτοις]{.greek-omitted} [εαυτους]{.greek-added} αρτους τι γαρ φαγωσιν ουκ [εχουσιν]{.greek-omitted} [εχωσιν]{.greek-added}[6:36]{.aside}

ο δε [αποκριθεις]{.greek-omitted} [απεκριθεις]{.greek-added} ειπεν [αυ]{.greek-added} [αυτοις]{.greek-omitted} [δοτε]{.greek-omitted} [αυτοις]{.greek-omitted} [υμεις]{.greek-omitted} [φαγειν]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [απελθοντες]{.greek-omitted} [αγορασωμεν]{.greek-omitted} [δηναριων]{.greek-omitted} [διακοσιων]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [δωμεν]{.greek-omitted} [αυτοις]{.greek-omitted} [φαγειν]{.greek-omitted}[6:37]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-added} [δοτε]{.greek-omitted} [αυτοις]{.greek-omitted} [υμεις]{.greek-omitted} [φαγειν]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [απελθοντες]{.greek-omitted} [αγορασωμεν]{.greek-omitted} [δηναριων]{.greek-omitted} [διακοσιων]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [δωμεν]{.greek-omitted} [αυτοις]{.greek-omitted} [φαγειν]{.greek-omitted}[6:37 | instance no. 2]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} ποσους αρτους εχετε υπαγετε και ιδετε και [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και [επεταξεν]{.greek-omitted} [επαταξεν]{.greek-added} αυτοις ανακλιναι παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [ευλογησεν]{.greek-omitted} [ηυλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι [φαγοντες]{.greek-omitted} [φαγωντες]{.greek-added} τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου [εμβηναι]{.greek-omitted} [εμεναι]{.greek-added} εις το πλοιον και προαγειν εις το περαν [προς]{.greek-omitted} [βηθσαιδαν]{.greek-omitted} [εως]{.greek-omitted} [αυτος]{.greek-omitted} [απολυση]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted}[6:45]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [ηναγκασεν]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [εμβηναι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [και]{.greek-omitted} [προαγειν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} [προς]{.greek-omitted} [προ]{.greek-added} [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [τους]{.greek-added} [οχλους]{.greek-added}[6:45 | instance no. 2]{.aside}

και αποταξαμενος αυτοις [απηλθεν]{.greek-omitted} [ανηλθε]{.greek-added} εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος [μονος]{.corr} επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της [νυκτος]{.greek-omitted} [νυκτους]{.greek-added} ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48]{.aside}

[οι]{.greek-omitted} [ι]{.greek-added} δε ιδοντες αυτον περιπατουντα επι της [[τ]{.unclear}αλασσης]{.greek-added} [[θ]{.unclear}αλασσης]{.corr} εδοξαν [φαντασμα]{.greek-omitted} [φαντασμας]{.greek-added} ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως ελαλησεν μετ [αυτον]{.greek-added} [αυτων]{.corr} και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και [ανα]{.greek-added} [ανεβη]{.greek-omitted} [[ανευη]{.corr}]{.greek-added} προς αυτους εις το πλοιον και εκοπασεν ο ανεμος [και]{.greek-omitted} [λιαν]{.greek-omitted} [εκπερισσου]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} [εξισταντο]{.greek-omitted} [και]{.greek-omitted} [εθαυμαζον]{.greek-omitted}[6:51]{.aside}

[και]{.greek-omitted} [ανεβη]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [και]{.greek-omitted} [εκοπασεν]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51 | instance no. 2]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} πεπωρωμενη[6:52]{.aside}

[και]{.corr} [διαπερασαντες]{.greek-omitted} [δεαπερασαντες]{.greek-added} ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} και [προσωρμισθησαν]{.greek-omitted} [προσορμισθησαν]{.greek-added}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως [οι]{.greek-added} [οχλοι]{.greek-added} [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην [και]{.greek-added} ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου αν [εισεπορευετο]{.greek-omitted} [εισεπορευετε]{.greek-added} εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} και οσοι αν ηπτοντο αυτου [εσωζοντο]{.greek-omitted} [εσοζοντο]{.greek-added}[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} [ελθοντες]{.greek-omitted} [ελθον]{.greek-added} απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [κοιναις]{.greek-omitted} [χερσιν]{.greek-omitted} [τουτ]{.greek-omitted} [εστιν]{.greek-omitted} [ανιπτοις]{.greek-omitted} [εσθιοντας]{.greek-omitted} [αρτους]{.greek-omitted} [εμεμψαντο]{.greek-omitted}[7:2]{.aside}

[και]{.greek-omitted} [ιδοντες]{.greek-omitted} [τινας]{.greek-omitted} των μαθητων αυτου [κοιναις]{.greek-omitted} [κοινες]{.greek-added} [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας αρτους [εμεμψαντο]{.greek-omitted} [εμελβψατο]{.greek-added}[7:2 | instance no. 2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη [νιψωνται]{.greek-omitted} [νιψοντον]{.greek-added} τας [χειχας]{.greek-added} [χειρας]{.corr} ουκ [εσθιουσιν]{.greek-omitted} [εστιουσι]{.greek-added} κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη [βαπτισωνται]{.greek-omitted} [βαπτισανται]{.greek-added} ουκ [εσθιουσιν]{.greek-omitted} [εστιουσι]{.greek-added} και αλλα πολλα εστιν α [παρελαβον]{.greek-omitted} [περελαβον]{.greek-added} κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και [οι]{.greek-omitted} γραμματεις δια τι οι [μαθ[―]{.gap}ται]{.greek-added} [μαθηται]{.corr} σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων αλλα ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιονσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε [αποκριθις]{.greek-added} [αποκριθεις]{.corr} ειπεν αυτοις οτι καλως [προεφητευσεν]{.greek-omitted} [προεφυτευσεν]{.greek-added} ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε [σεβονται]{.greek-omitted} [σευονται]{.greek-added} με [διδασκοντες]{.greek-omitted} [διδασκαλιας]{.greek-omitted} [ενταλματα]{.greek-omitted} [ανθρωπων]{.greek-omitted}[7:7]{.aside}

[ματην]{.greek-omitted} [δε]{.greek-omitted} [σεβονται]{.greek-omitted} [με]{.greek-omitted} διδασκοντες διδασκαλιας ενταλματα ανθρωπων[7:7 | instance no. 2]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} [βαπτισμους]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [ποτηριων]{.greek-omitted} και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως [αθετειτε]{.greek-omitted} [αθετει]{.greek-added} την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε [οτι]{.greek-added} εαν [ειπη]{.greek-omitted} [ηπη]{.greek-added} [ανθρωπος]{.greek-abbr} [τω]{.greek-omitted} [πατρι]{.greek-omitted} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε [αυτων]{.greek-added} [αυτον]{.corr} ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-omitted} [εισπορευομενον]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [εκπορευομενα]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [εκεινα]{.greek-omitted} [εστιν]{.greek-omitted} [τα]{.greek-omitted} [κοινουντα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[7:15]{.aside}

[ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [εξωθεν]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15 | instance no. 2]{.aside}

[ει]{.greek-omitted} [τις]{.greek-omitted} εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου [επ[―]{.gap}ρωτων]{.greek-added} [επηρωτων]{.corr} αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα [εκπορευεται]{.greek-omitted} [εκβαλλεται]{.greek-added} [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον [εκεινο]{.greek-omitted} [εκοινο]{.greek-added} κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[πλε]{.greek-added} [κλοπαι]{.greek-omitted} [πλεονεξιαι]{.greek-omitted} [πονηριαι]{.greek-omitted} [δολος]{.greek-omitted} [ασελγεια]{.greek-omitted} [οφθαλμος]{.greek-omitted} [πονηρος]{.greek-omitted} [βλασφημια]{.greek-omitted} [υπερηφανια]{.greek-omitted} [αφροσυνη]{.greek-omitted}[7:22]{.aside}

[κλοπαι]{.greek-omitted} [πλεονεξιαι]{.greek-omitted} [ονεξιαι]{.greek-added} πονηριαι δολος [ασελγεια]{.greek-omitted} [ασελγειαι]{.greek-added} [οφθαλμος]{.greek-omitted} [οφθαλλμος]{.greek-added} πονηρος [βλασφημια]{.greek-omitted} [βλασφημιαι]{.greek-added} [υπερηφανια]{.greek-omitted} [υπεριφανια]{.greek-added} αφροσυνη[7:22 | instance no. 2]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλ[θ]{.unclear}εν εις τα [μεθορια]{.greek-omitted} [ορια]{.greek-added} τυρου και σιδωνος και [εισελθων]{.greek-omitted} [εισηλθων]{.greek-added} εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ηχε]{.greek-added} το θυγατριον [αυτης]{.greek-omitted} [πνευμα]{.greek-abbr} [ακαθαρτον]{.greek-omitted} [ακαθρτον]{.greek-added} ελθουσα προσεπεσεν [προς]{.greek-omitted} [εις]{.greek-added} τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συρα]{.greek-added} [φοινικησα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλλει]{.greek-added} εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον [χορτασθηναι]{.greek-omitted} [χορτασθηνε]{.greek-added} τα τεκνα ου γαρ [εστι]{.greek-added} καλον [εστιν]{.greek-omitted} λαβειν τον αρτον των [κνων]{.greek-added} [τεκνων]{.corr} και βαλειν τοις κυναριοις[7:27]{.aside}

[η]{.greek-omitted} δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο [των]{.greek-omitted} [ψιχιων]{.greek-omitted} [των]{.greek-omitted} [παιδιων]{.greek-omitted}[7:28]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [απεκριθη]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ναι]{.greek-omitted} [κυριε]{.greek-omitted} [και]{.greek-omitted} [γαρ]{.greek-omitted} [τα]{.greek-omitted} [κυναρια]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [τραπεζης]{.greek-omitted} [εσθιει]{.greek-omitted} [απο]{.greek-omitted} των [ψιχιων]{.greek-omitted} [ψυχιων]{.greek-added} των παιδιων[7:28 | instance no. 2]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον [εξελ[υ]{.unclear}λυθος]{.greek-added} [εξεληλυθος]{.corr} και την θυγατερα [βεβλημενην]{.greek-omitted} [μεβλημενην]{.greek-added} επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} κωφον μογγιλαλον και παρακαλουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} ινα επιθη αυτω την χειρα[7:32]{.aside}

και [απολαβομενος]{.greek-omitted} [επιλαβομενος]{.greek-added} αυτον απο του [οχλου]{.greek-omitted} [οχλο]{.greek-added} κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο εστιν διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και [ε]{.greek-added} [ελυθη]{.greek-omitted} [ο]{.greek-omitted} [δεσμος]{.greek-omitted} [της]{.greek-omitted} [γλωσσης]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ελαλει]{.greek-omitted} [ορθως]{.greek-omitted}[7:35]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [διηνοιχθησαν]{.greek-omitted} [αυτου]{.greek-omitted} [αι]{.greek-omitted} [ακοαι]{.greek-omitted} [και]{.greek-omitted} [ελυθη]{.greek-omitted} [λυθη]{.greek-added} ο δεσμος της [γλωττης]{.greek-added} [γλωσσης]{.greek-omitted} [αυτου]{.greek-omitted} και ελαλει ορθως[7:35 | instance no. 2]{.aside}

και [διεστι]{.greek-added} [διεστειλατο]{.corr} αυτοις ινα μηδενι ειπωσιν οσον δε αυτος [διεστελλετο]{.greek-added} αυτοις [διεστελλετο]{.greek-omitted} μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και [υπερπερισσως]{.greek-omitted} [υπερπερισσος]{.greek-added} εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} [και]{.greek-omitted} τους κωφους ποιει ακουειν και τους [[κ]{.unclear}αλαλους]{.greek-added} [αλαλους]{.corr} λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παμπολλου]{.greek-omitted} [πανπολλου]{.greek-added} οχλου [οντως]{.greek-added} [οντος]{.corr} και μη εχοντων τι φαγωσιν προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι [ημερας]{.greek-added} [τρεις]{.greek-added} ηδη [ημεραι]{.greek-omitted} [τρεις]{.greek-omitted} [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους νηστεις [εις]{.greek-omitted} [οικον]{.greek-omitted} [αυτων]{.greek-omitted} εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκασι]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου [ποθεν]{.greek-omitted} [τουτους]{.greek-omitted} [δυνησεται]{.greek-omitted} [τις]{.greek-omitted} [ωδε]{.greek-omitted} [χορτασαι]{.greek-omitted} [αρτων]{.greek-omitted} [επ]{.greek-omitted} [ερημιας]{.greek-omitted}[8:4]{.aside}

[και]{.greek-omitted} [απεκριθησαν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} ποθεν τουτους δυνησεται τις ωδε χορτασαι [αρτων]{.greek-omitted} [αρτον]{.greek-added} επ [ερημιας]{.greek-omitted} [ερηλιαις]{.greek-added}[8:4 | instance no. 2]{.aside}

και [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} αυτους ποσους [εχετε]{.greek-omitted} αρτους [εχεται]{.greek-added} οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον [και]{.greek-added} ιχθυδια ολιγα και [αυτα]{.greek-added} ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν [περισσευματα]{.greek-omitted} [περισευματα]{.greek-added} κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [ε[μ]{.unclear}βας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου [λεγει]{.greek-omitted} [τι]{.greek-omitted} [η]{.greek-omitted} [γενεα]{.greek-omitted} [αυτη]{.greek-omitted} [σημειον]{.greek-omitted} [επιζητει]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ει]{.greek-omitted} [δοθησεται]{.greek-omitted} [τη]{.greek-omitted} [γενεα]{.greek-omitted} [ταυτη]{.greek-omitted} [σημειον]{.greek-omitted}[8:12]{.aside}

[και]{.greek-omitted} [αναστεναξας]{.greek-omitted} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [αυτου]{.greek-omitted} λεγει τι η γενεα αυτη σημειον [επιζητει]{.greek-omitted} [επιζητειν]{.greek-added} αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12 | instance no. 2]{.aside}

και αφεις αυτους [εμβας]{.greek-omitted} [ευμμας]{.greek-added} παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και [διεστελλετο]{.greek-omitted} [διεστελετο]{.greek-added} αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και [διε[γι]{.unclear}]{.greek-added} [διελογιζοντο]{.corr} προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε [εν]{.greek-added} [εαυτοις]{.greek-added} οτι αρτους ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} ουπω νοειτε ουδε συνιετε ετι [πεπωρωμενην]{.greek-omitted} [πεπωωρωμενην]{.greek-added} [[πεποωρωμενην]{.corr}]{.greek-added} εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

[οτε]{.greek-omitted} [οταν]{.greek-added} τους πεντε αρτους εκλασα εις τους [πενταχιλιους]{.greek-added} [πεντακισχιλιους]{.corr} ποσους κοφινους πληρεις κλασματων ηρατε λεγουσιν [αυτω]{.greek-omitted} [δωδεκα]{.greek-omitted}[8:19]{.aside}

[οτε]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [εκλασα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [πεντακισχιλιους]{.greek-omitted} [ποσους]{.greek-omitted} [κοφινους]{.greek-omitted} [πληρεις]{.greek-omitted} [κλασματων]{.greek-omitted} [ηρατε]{.greek-omitted} [λεγουσιν]{.greek-omitted} αυτω δωδεκα[8:19 | instance no. 2]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον [αυτω]{.greek-added} επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις πως ου συνιετε[8:21]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} εις [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και [επιλαβομενος]{.greek-omitted} [επιλαζομενος]{.greek-added} της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας [αυτω]{.greek-omitted} [αυτου]{.greek-added} [επηρωτα]{.greek-omitted} [ηρωτα]{.greek-added} αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας ελεγεν βλεπω τους [ανθρωπους]{.greek-abbr} [ωσει]{.greek-added} [οτι]{.greek-omitted} [ως]{.greek-omitted} δενδρα [ορω]{.greek-omitted} [περιπατουντας]{.greek-omitted} [περιπατουντους]{.greek-added}[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους [οφθλμους]{.greek-added} [οφθαλμους]{.corr} αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατασταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψαι]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας [καισαρειας]{.greek-omitted} [καισσαρειας]{.greek-added} της φιλιππου και εν τη οδω [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} τους μαθητας αυτου λεγων [αυτοις]{.greek-omitted} [αυτω]{.greek-added} τινα με λεγουσιν οι [ανθρωποι]{.greek-omitted} [[ανοι]{.greek-abbr}]{.greek-added} ειναι[8:27]{.aside}

οι δε [απεκριθησαν]{.greek-omitted} [απεκρισαν]{.greek-added} ιωαννην [των]{.greek-added} [τον]{.corr} βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των [φητων]{.greek-added} [προφητων]{.corr}[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγουσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι α[―]{.gap}πο [[απο]{.corr}]{.greek-added} των πρεσβυτερων και των αρχιερεων και των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και [παρρησια]{.greek-omitted} [παρησια]{.greek-added} τον λογον ελαλει και προσλαβομενος αυτον ο [περ]{.greek-added} [πετρος]{.corr} ηρξατο [επιτιμα]{.greek-added} [α]{.greek-added} [επιτιμαν]{.corr} [αυτω]{.greek-omitted} [αυτων]{.greek-added}[8:32]{.aside}

ο δε [επιστραφεις]{.greek-omitted} [στραφεις]{.greek-added} και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [ειπε]{.greek-added} τω πετρω [λε]{.greek-added} [λεγων]{.greek-omitted} [υπαγε]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [σατανα]{.greek-omitted} [οτι]{.greek-omitted} [ου]{.greek-omitted} [φρονεις]{.greek-omitted} [τα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted}[8:33]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [επιστραφεις]{.greek-omitted} [και]{.greek-omitted} [ιδων]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [επετιμησεν]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [λεγων]{.greek-omitted} [γων]{.greek-added} υπαγε οπισω μου σατανα οτι ου [φρονεις]{.greek-omitted} [φρουνεις]{.greek-added} τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33 | instance no. 2]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν [αυτοις]{.greek-omitted} [αυτω]{.greek-added} [ο]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελει οπισω μου [ακολουθειν]{.greek-omitted} [ελθεν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακου]{.greek-added} [ακολουθειτω]{.corr} μοι[8:34]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την [εαυτου]{.greek-omitted} ψυχην [αυτου]{.greek-added} ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} εαν κερδηση [ολον]{.greek-added} τον κοσμον [ολον]{.greek-omitted} και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ εαν [επαισχυνθη]{.greek-omitted} [επαισχηνθη]{.greek-added} με και τους [[ο]{.unclear}μους]{.greek-added} [εμους]{.corr} λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} [επαισχυνθησεται]{.greek-omitted} [επαισχηνθησετε]{.greek-added} αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες [των]{.greek-omitted} [ωδε]{.greek-omitted} [εστηκοτων]{.greek-omitted} [οιτινες]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [γευσωνται]{.greek-omitted} [θανατου]{.greek-omitted} [εως]{.greek-omitted} [αν]{.greek-omitted} [ιδωσιν]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εληλυθυιαν]{.greek-omitted} [εν]{.greek-omitted} [δυναμει]{.greek-omitted}[9:1]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [εισιν]{.greek-omitted} [τινες]{.greek-omitted} των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την [βασιλειαν]{.greek-omitted} [βασιλιαν]{.greek-added} του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1 | instance no. 2]{.aside}

και μεθ [ημεραν]{.greek-added} [ημερας]{.corr} εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και [ιωαννην]{.greek-omitted} [ιωαννου]{.greek-added} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο [στιλβοντα]{.greek-omitted} [ως]{.greek-added} [τον]{.greek-added} [ηλιον]{.greek-added} λευκα λιαν ως χιων οια [γναφευς]{.greek-omitted} [κναφευς]{.greek-added} [επη]{.greek-added} [επι]{.corr} [τη[―]{.gap}]{.greek-added} [της]{.corr} γης ου δυναται [λευκαναι]{.greek-omitted} [λευκααν]{.greek-added}[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωσει]{.greek-added} και ησαν [συλλαλουντες]{.greek-omitted} [συλαλουντες]{.greek-added} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν [τρεις]{.greek-added} [σκανας]{.greek-added} [σκηνας]{.corr} [τρεις]{.greek-omitted} σοι μιαν και [μωση]{.greek-omitted} [μωσει]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και ηλθεν φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος [αυτου]{.greek-omitted} [ακουετε]{.greek-omitted}[9:7]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [νεφελη]{.greek-omitted} [επισκιαζουσα]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [ηλθεν]{.greek-omitted} [φωνη]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [νεφελης]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [μου]{.greek-omitted} [ο]{.greek-omitted} [αγαπητος]{.greek-omitted} αυτου ακουετε[9:7 | instance no. 2]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον [αλλα]{.greek-omitted} [ει]{.greek-added} [μη]{.greek-added} τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

[καταβαινοντων]{.greek-omitted} [καταβαινοντον]{.greek-added} δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} [διηγησονται]{.greek-added} α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες [τι]{.greek-added} οτι λεγουσιν οι γραμματεις οτι ηλιαν δει [ηλθειν]{.greek-added} [ελθειν]{.corr} πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα και πως γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα [πολλα]{.greek-omitted} [παλλα]{.greek-added} παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν [οτι]{.greek-omitted} και ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας [αυτου]{.greek-added} ειδεν οχλον πολυν περι αυτους και [γραμματεις]{.greek-omitted} συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και [προστρε]{.greek-added} [προστρεχοντες]{.greek-omitted} [ησπαζοντο]{.greek-omitted} [αυτον]{.greek-omitted}[9:15]{.aside}

[χοντες]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [ιδων]{.greek-omitted} [αυτον]{.greek-omitted} [εξεθαμβηθη]{.greek-omitted} [και]{.greek-omitted} [προστρεχοντες]{.greek-omitted} ησπαζοντο αυτον[9:15 | instance no. 2]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησαν]{.greek-added} τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} διδασκαλε ηνεγκα τον υιον μου [προς]{.greek-omitted} [προ]{.greek-added} σε εχοντα πνευμα [αλαλον]{.greek-omitted} [αλλον]{.greek-added}[9:17]{.aside}

[και]{.greek-omitted} οπου αν αυτον καταλαβη [ρησσει]{.greek-omitted} [ρησει]{.greek-added} αυτον και αφριζει και τριζει τους οδοντας αυτου και [ξηραιται]{.greek-added} [ξηραινεται]{.corr} και ειπον τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [λεγει]{.greek-added} αυτω [λεγει]{.greek-omitted} ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και [ηνεγκαν]{.greek-omitted} [ηνεγκα]{.greek-added} αυτον προς αυτον και ιδων αυτον ευθεως το πνευμα εσπαραξεν αυτον και πεσων επι της γης [κυλιετο]{.greek-added} [εκυλιετο]{.corr} αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις [υδατα]{.greek-omitted} [υδωρ]{.greek-added} ινα απολεση αυτον αλλ ει τι [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν [αυτω]{.greek-omitted} [το]{.greek-omitted} [ει]{.greek-omitted} [δυνασαι]{.greek-omitted} [πιστευσαι]{.greek-omitted} [παντα]{.greek-omitted} [δυνατα]{.greek-omitted} [τω]{.greek-omitted} [πιστευοντι]{.greek-omitted}[9:23]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23 | instance no. 2]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [βηηθει]{.greek-added} μου τη [απιστια]{.greek-omitted} [απιστεια]{.greek-added}[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρε[ρ]{.unclear}ει]{.greek-added} [επισυντρεχει]{.corr} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πνευματι τω ακαθαρτω λεγων αυτω το πνευμα το [αλλ]{.greek-added} [αλαλον]{.corr} και κωφον εγω σοι [επιτασσω]{.greek-omitted} [επιτασω]{.greek-added} εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον [εξελθε]{.greek-added} [εξηλθεν]{.greek-omitted} [[εξηλθε]{.corr}]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και [ανεστη]{.greek-omitted} [αναεστη]{.greek-added}[9:27]{.aside}

και [εισελθοντα]{.greek-omitted} [εισσελθοντα]{.greek-added} αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν οτι ημεις [ουκ]{.greek-omitted} [ηδυνηθημεν]{.greek-omitted} [εκβαλειν]{.greek-omitted} αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το [γενος]{.greek-omitted} [γενεον]{.greek-added} εν ουδενι δυναται εξελθειν ει [μη]{.greek-omitted} [μι]{.greek-added} εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες [παρεπορευοντο]{.greek-omitted} [επορευοντο]{.greek-added} δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδιδοται]{.greek-omitted} [εις]{.greek-omitted} [χειρας]{.greek-omitted} [ανθρωπων]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [αποκτανθεις]{.greek-omitted} [τη]{.greek-omitted} [τριτη]{.greek-omitted} [ημερα]{.greek-omitted} [αναστησεται]{.greek-omitted}[9:31]{.aside}

[εδιδασκεν]{.greek-omitted} [γαρ]{.greek-omitted} τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} εις χειρας [ανθρωπων]{.greek-abbr} και [αποκτενουσιν]{.greek-omitted} [αποκταινουσιν]{.greek-added} [αυτου]{.greek-added} [αυτον]{.corr} και αποκτανθεις τη τριτη ημερα αναστησεται[9:31 | instance no. 2]{.aside}

[οι]{.greek-omitted} [η]{.greek-added} δε ηγνοουν το ρημα και εφοβουντο αυτον [επηρωτησαι]{.greek-added} [επερωτησαι]{.corr}[9:32]{.aside}

και ηλθεν εις καπερναουμ [η]{.greek-added} [και]{.corr} εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς [αλληλους]{.greek-omitted} [αλληλλους]{.greek-added} γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις [θελει]{.greek-omitted} [θει]{.greek-added} πρωτος ειναι εσται παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των [τοι[―]{.gap}υτων]{.greek-added} [τοιουτων]{.corr} παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη [δε]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [και]{.greek-added} [ειπεν]{.greek-added} αυτω [ιωαννης]{.greek-omitted} [λεγων]{.greek-omitted} διδασκαλε [ειδομεν]{.greek-omitted} [τινα]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [σου]{.greek-omitted} [εκβαλλοντα]{.greek-omitted} [δαιμονια]{.greek-omitted} [ος]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

[απεκριθη]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} [ιωαννης]{.greek-omitted} [λεγων]{.greek-omitted} [διδασκαλε]{.greek-omitted} ειδομεν [τανα]{.greek-added} [τινα]{.corr} [επι]{.greek-added} τω ονοματι σου [εκβαλλοντα]{.greek-omitted} δαιμονια [εκκβαλλοντα]{.greek-added} [[εεκβαλλοντα]{.corr}]{.greek-added} ος ουκ [ακολουθει]{.greek-omitted} [ακουλουθει]{.greek-added} ημιν και εκωλυσαμεν αυτον [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38 | instance no. 2]{.aside}

[ουδις]{.greek-added} [[γ]{.unclear}[αρ]{.greek-supplied}]{.greek-added} [εστι[ν]{.unclear}]{.greek-added} [ο]{.corr} [δε]{.corr} [[ιησους]{.greek-abbr}]{.corr} [ειπεν]{.greek-omitted} [[ειπε]{.corr}]{.greek-added} μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και [δυνησεται]{.greek-omitted} [δυνησετε]{.greek-added} ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστι]{.greek-added} [καθ]{.greek-added} [ημων]{.greek-added} [υπ[ο]{.unclear}]{.greek-added} [[υπερ]{.corr}]{.greek-added} [ημων]{.greek-added} εστιν [καθ]{.greek-omitted} [υμων]{.greek-omitted} [υπερ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted}[9:40]{.aside}

ος γαρ [αν]{.greek-omitted} ποτιση υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι [μ[―]{.gap}]{.greek-added} [μου]{.corr} οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολυση]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει περικειται [λιθος]{.greek-omitted} [μυλικος]{.greek-omitted} [μυλος]{.greek-added} [περι]{.greek-omitted} [ονικος]{.greek-added} [επι]{.greek-added} τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιζει]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την [γεενναν]{.greek-omitted} [γενναν]{.greek-added} εις το πυρ το ασβεστον[9:43]{.aside}

οπου [ο]{.greek-omitted} [σκωληξ]{.greek-omitted} [αυτων]{.greek-omitted} [ου]{.greek-omitted} [τελευτα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [ου]{.greek-omitted} [σβεννυται]{.greek-omitted}[9:44]{.aside}

[οπου]{.greek-omitted} ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44 | instance no. 2]{.aside}

και εαν ο πους σου [σκανδαλιζη]{.greek-omitted} [σκανδαλιζει]{.greek-added} σε αποκοψον αυτον καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} [σοι]{.greek-omitted} [σε]{.greek-added} εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι [σε]{.greek-added} εις την [γεενναν]{.greek-omitted} [γενναν]{.greek-added} εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου [σκανδαλιζη]{.greek-omitted} [σκανδαλιζει]{.greek-added} σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο [οφθαλμον]{.greek-added} [οφθαλμους]{.corr} εχοντα βληθηναι εις την [γεενναν]{.greek-omitted} [γενναν]{.greek-added} του [πο]{.greek-added} [πυρος]{.corr}[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας [αναλον]{.greek-omitted} [αλαλον]{.greek-added} γενηται εν τινι αυτο αρτυσετε εχετε [αλας]{.greek-added} εν εαυτοις [αλας]{.greek-omitted} και ειρηνευετε εν [ανληλοις]{.greek-added} [αλληλοις]{.greek-omitted} [[ανλληλοις]{.corr}]{.greek-added}[9:50]{.aside}

### Chapter 10

κακειθεν αναστας [ερχε]{.greek-added} [ερχεται]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορια]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} [δια]{.greek-omitted} [του]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} [και]{.greek-omitted} [συμπορευονται]{.greek-omitted} [παλιν]{.greek-omitted} [οχλοι]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [ειωθει]{.greek-omitted} [παλιν]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [αυτους]{.greek-omitted}[10:1]{.aside}

[ται]{.greek-added} [κακειθεν]{.greek-omitted} [αναστας]{.greek-omitted} [ερχεται]{.greek-omitted} εις τα ορια [ταις]{.greek-added} [της]{.corr} ιουδαιας [δια]{.greek-omitted} [του]{.greek-omitted} περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1 | instance no. 2]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι [περ]{.greek-added} [πειραζοντες]{.corr} αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσ[α]{.unclear}ς]{.greek-added} [μωσης]{.corr}[10:3]{.aside}

οι δε ειπον μωσης [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} [βιβλον]{.greek-added} [βιβλιον]{.corr} αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και [προσκολληθησεται]{.greek-omitted} [προσκολληνθησεται]{.greek-added} προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις [σαρκα]{.greek-omitted} [σαρκαν]{.greek-added} μιαν [ωστε]{.greek-omitted} [ουκετι]{.greek-omitted} [εισιν]{.greek-omitted} [δυο]{.greek-omitted} [αλλα]{.greek-omitted} [μια]{.greek-omitted} [σαρξ]{.greek-omitted}[10:8]{.aside}

[και]{.greek-omitted} [εσονται]{.greek-omitted} [οι]{.greek-omitted} [δυο]{.greek-omitted} [εις]{.greek-omitted} [σαρκα]{.greek-omitted} [μιαν]{.greek-omitted} ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8 | instance no. 2]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη [χωριζ[η]{.unclear}τω]{.greek-added} [χωριζετω]{.corr}[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι του αυτου επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις ος [εαν]{.greek-omitted} [αν]{.greek-added} απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα [αυτων]{.greek-added} αψηται [αυτων]{.greek-omitted} οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η [βασιλεια]{.greek-omitted} [βασιλειαν]{.greek-added} του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα ευλογει αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [προσδραμων]{.greek-omitted} [προσδρα]{.greek-added} [εις]{.greek-omitted} [και]{.greek-omitted} [γονυπετησας]{.greek-omitted} [αυτον]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [διδασκαλε]{.greek-omitted} [αγαθε]{.greek-omitted} [τι]{.greek-omitted} [ποιησω]{.greek-omitted} [ινα]{.greek-omitted} [ζωην]{.greek-omitted} [αιωνιον]{.greek-omitted} [κληρονομησω]{.greek-omitted}[10:17]{.aside}

[μων]{.greek-added} και [εκπορευομενου]{.greek-omitted} [αυτου]{.greek-omitted} εις [οδον]{.greek-omitted} [προσδραμων]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} γονυπετησας [αυτον]{.greek-omitted} [αυτω]{.greek-added} επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη [μοιχευσης]{.greek-omitted} [μοιχευσεις]{.greek-added} μη φονευσης μη κλεψης μη ψευδομαρτυρησης μη αποστερησης τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν [αυτον]{.greek-omitted} [αυτων]{.greek-added} και ειπεν αυτω εν σοι υστερει υπαγε οσα εχεις [πωλησον]{.greek-omitted} [πωλυσον]{.greek-added} και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} και δευρο [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα [χρηματα]{.greek-omitted} [εχοντες]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισελευσονται]{.greek-omitted}[10:23]{.aside}

[και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγει]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [πως]{.greek-omitted} [δυσκολως]{.greek-omitted} [οι]{.greek-omitted} [τα]{.greek-omitted} [χρηματα]{.greek-omitted} [χριματα]{.greek-added} [εχοντες]{.greek-omitted} [εχωντες]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23 | instance no. 2]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως [δυκολον]{.greek-added} [δυσκολον]{.corr} [εστιν]{.greek-omitted} [εστι]{.greek-added} τους [πεποιθοτας]{.greek-omitted} [πεποιθωτας]{.greek-added} επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} τρυμαλιας της ραφιδος [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η [αδελφους]{.greek-omitted} [αδελφος]{.greek-added} [η]{.greek-omitted} [αδελφας]{.greek-omitted} η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η [τε]{.greek-added} [τεκνα]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [ενεκεν]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted}[10:29]{.aside}

[αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ουδεις]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} [αφηκεν]{.greek-omitted} [οικιαν]{.greek-omitted} [η]{.greek-omitted} [αδελφους]{.greek-omitted} [η]{.greek-omitted} [αδελφας]{.greek-omitted} [η]{.greek-omitted} [πατερα]{.greek-omitted} [η]{.greek-omitted} [μητερα]{.greek-omitted} [η]{.greek-omitted} [γυναικα]{.greek-omitted} [η]{.greek-omitted} [τεκνα]{.greek-omitted} [κνα]{.greek-added} η αγρους ενεκεν εμου και ενεκεν του [ευαγγελιου]{.greek-omitted} [ευγγελιου]{.greek-added}[10:29 | instance no. 2]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [μητερας]{.greek-abbr} και τεκνα και αγρους μετα διωγμων και εν τω [αιωνι]{.greek-omitted} [αιωνιον]{.greek-added} τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω [αναβαινοντες]{.greek-omitted} [αναβαιοντες]{.greek-added} εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και [παραλαβων]{.greek-omitted} [παραλαμβανων]{.greek-added} παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα [μελλοντα]{.greek-omitted} [μελλοντο]{.greek-added} αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33]{.aside}

και εμπαιξουσιν αυτω και μαστιγωσουσιν αυτον και εμπτυσουσιν αυτω [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [τη]{.greek-omitted} [τριτη]{.greek-omitted} [ημερα]{.greek-omitted} [αναστησεται]{.greek-omitted}[10:34]{.aside}

[και]{.greek-omitted} [εμπαιξουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34 | instance no. 2]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα [ο]{.greek-omitted} εαν [αιτησωμεν]{.greek-omitted} [αιτησαμεν]{.greek-added} ποιησης ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε [ινα]{.greek-added} [ποιησαι]{.greek-omitted} [ποιησω]{.greek-added} [με]{.greek-omitted} υμιν[10:36]{.aside}

οι δε ειπον αυτω [θελομεν]{.greek-added} [δος]{.greek-omitted} [ημιν]{.greek-omitted} ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ [οιδατο]{.greek-added} [οιδατε]{.corr} τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

[οι]{.greek-omitted} [ο]{.greek-added} δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων [[―]{.gap}ου]{.greek-added} [μου]{.corr} και εξ ευωνυμων ουκ εστιν [εμου]{.greek-added} [εμον]{.corr} δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα [ηρξαντο]{.greek-omitted} [ηρξατο]{.greek-added} αγανακτειν περι [[ιω]{.greek-abbr}]{.greek-added} [και]{.greek-added} ιακωβου [και]{.greek-omitted} [ιωαννου]{.greek-omitted}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις [οιδατε]{.greek-omitted} [οτι]{.greek-omitted} [οι]{.greek-omitted} [δοκουντες]{.greek-omitted} [αρχειν]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted} [κατακυριευουσιν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μεγαλοι]{.greek-omitted} [αυτων]{.greek-omitted} [κατεξουσιαζουσιν]{.greek-omitted} [αυτων]{.greek-omitted}[10:42]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} οιδατε οτι οι δοκουντες αρχειν των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριευοσιν]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42 | instance no. 2]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη [εν]{.greek-added} [υμων]{.greek-omitted} [υμιν]{.greek-added} [γενεσθαι]{.greek-omitted} [ειναι]{.greek-added} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου [βαρτιμαιο[υ]{.unclear}]{.greek-added} [βαρτιμαιος]{.corr} ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο [ναζωραιος]{.greek-omitted} [ναζοραιος]{.greek-added} εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [τον]{.greek-omitted} [τυφλον]{.greek-omitted} [λεγοντες]{.greek-omitted} [αυτω]{.greek-omitted} [θαρσει]{.greek-omitted} [εγειραι]{.greek-omitted} [φωνει]{.greek-omitted} [σε]{.greek-omitted}[10:49]{.aside}

[και]{.greek-omitted} [στας]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτον]{.greek-omitted} [φωνηθηναι]{.greek-omitted} [και]{.greek-omitted} [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49 | instance no. 2]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος ειπεν αυτω [ραββουνι]{.greek-omitted} [ραββονι]{.greek-added} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [εσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε [εγγιζουσιν]{.greek-omitted} [ειγγιζουσιν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} εις βηθσφαγη και βηθανιαν προς το ορος [ε]{.greek-added} [των]{.corr} ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ [ον]{.greek-omitted} [ων]{.greek-added} ουδεις ανθρωπων [κεκαθικεν]{.greek-omitted} [κεκαθικε]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως [α]{.greek-added} [αυτον]{.greek-omitted} [αποστελλει]{.greek-omitted} [ωδε]{.greek-omitted}[11:3]{.aside}

[ποστελλει]{.greek-added} [και]{.greek-omitted} [εαν]{.greek-omitted} [τις]{.greek-omitted} [υμιν]{.greek-omitted} [ειπη]{.greek-omitted} [τι]{.greek-omitted} [ποιειτε]{.greek-omitted} [τουτο]{.greek-omitted} [ειπατε]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [αυτου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχει]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} αυτον [αποστελλει]{.greek-omitted} ωδε[11:3 | instance no. 2]{.aside}

απηλθον δε και [ευρον]{.greek-omitted} [ευβρον]{.greek-added} πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως [ενετειλατο]{.greek-omitted} [εντειλατο]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και [επεβαλον]{.greek-omitted} [επευαλον]{.greek-added} αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added} [[―]{.gap}λλοι]{.greek-added} [αλλοι]{.corr} δε [στοιβαδας]{.greek-omitted} εκοπτον [βαγεια]{.greek-added} εκ των δενδρων και [εστρωννυον]{.greek-omitted} [εστωωννυον]{.greek-added} εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες [εκραζον]{.greek-omitted} [εκραζων]{.greek-added} λεγοντες [ωσαν[―]{.gap}α]{.greek-added} [ωσαννα]{.corr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις [το]{.greek-omitted} ιερον και περιβλεψαμενος παντα οψιας [ηδη]{.greek-omitted} [ιδη]{.greek-added} ουσης της [ωρας]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εις]{.greek-omitted} [βηθανιαν]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted}[11:11]{.aside}

[και]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [παντα]{.greek-omitted} [οψιας]{.greek-omitted} [ηδη]{.greek-omitted} [ουσης]{.greek-omitted} [της]{.greek-omitted} ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11 | instance no. 2]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην μακροθεν εχουσαν φυλλα ηλθεν ει αρα ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη [μηκετι]{.greek-omitted} [μηκετη]{.greek-added} εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και αγοραζοντας εν [τω]{.greek-omitted} ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [διδασκεν]{.greek-added} [αυτους]{.greek-added} λεγων [αυτοις]{.greek-omitted} ου γεγραπται [οτι]{.greek-omitted} ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [εζητουν]{.greek-omitted} [πως]{.greek-omitted} [αυτον]{.greek-omitted} [απολεσωσιν]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted} [αρ]{.greek-added} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [εξεπλησσετο]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted}[11:18]{.aside}

[χιερεις]{.greek-added} και [ηκουσαν]{.greek-omitted} οι γραμματεις [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο οχλος [εξεπλησσετο]{.greek-omitted} [εξεπλησετο]{.greek-added} επι τη διδαχη [αυτου]{.greek-omitted}[11:18 | instance no. 2]{.aside}

και οτε οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι [ιδε]{.greek-omitted} [ηδε]{.greek-added} η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη [διακριθη]{.greek-omitted} [διακρηθη]{.greek-added} εν τη καρδια αυτου αλλα πιστευση οτι α λεγει [γινεται]{.greek-omitted} [τινεται]{.greek-added} εσται αυτω ο εαν ειπη[11:23]{.aside}

δια [τουτο]{.greek-omitted} [τουτω]{.greek-added} λεγω υμιν παντα οσα αν προσευχομενοι αιτησθε πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι [αφιετε]{.greek-omitted} [αφιε]{.greek-added} ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις [ουκ]{.greek-omitted} [αφιετε]{.greek-omitted} [ουδε]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [αφησει]{.greek-omitted} [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [υμων]{.greek-omitted}[11:26]{.aside}

[ει]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο εν τοις [ουρανοις]{.greek-abbr} [[[ουρανοις]{.greek-abbr}]{.corr}]{.greek-added} αφησει [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [υμων]{.greek-omitted} [υμιν]{.greek-added}[11:26 | instance no. 2]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις [και]{.greek-omitted} [η]{.greek-added} τις σοι [την]{.greek-omitted} εξουσιαν ταυτην [εδωκεν]{.greek-omitted} [δεδωκεν]{.greek-added} ινα ταυτα [ποιεις]{.greek-added} [ποιης]{.corr}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} [απεκριθη]{.greek-added} ειπεν αυτοις επερωτησω υμας [και]{.greek-omitted} [εγω]{.greek-omitted} [καγω]{.greek-added} [λογον]{.greek-added} ενα [λογον]{.greek-omitted} και αποκριθητε μοι και ερω υμιν [εν]{.greek-omitted} [επι]{.greek-added} [[ε]{.corr}]{.greek-added} [ποια]{.corr} εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ ουρανου ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} [προς]{.greek-omitted} [εν]{.greek-added} [εαυτους]{.greek-omitted} [εαυτοις]{.greek-added} λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον [λαον]{.greek-omitted} [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ [τον]{.greek-added} [ιωαννη]{.greek-added} ειχον [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν [εν]{.greek-omitted} [ποια]{.greek-omitted} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιω]{.greek-omitted}[11:33]{.aside}

### Chapter 12

[οι]{.greek-omitted} [δε]{.greek-omitted} [ελθοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [οιδαμεν]{.greek-omitted} [οτι]{.greek-omitted} [αληθης]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [περι]{.greek-omitted} [ουδενος]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [βλεπεις]{.greek-omitted} [εις]{.greek-omitted} [προσωπον]{.greek-omitted} [ανθρωπων]{.greek-omitted} [αλλ]{.greek-omitted} [επ]{.greek-omitted} [αληθειας]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [διδασκεις]{.greek-omitted} [εξεστιν]{.greek-omitted} [κηνσον]{.greek-omitted} [καισαρι]{.greek-omitted} δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμων]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη [οι]{.corr} [δε]{.corr} [ειπων]{.greek-added} [ειπον]{.corr} αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε [ουν]{.greek-added} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και [ερχονται]{.greek-omitted} [ρχονται]{.greek-added} σαδδουκαιοι προς αυτον οιτινες λεγουσιν [αναστασιν]{.greek-omitted} μη ειναι [αναστασιν]{.greek-added} και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος [απο[α]{.unclear}]{.greek-added} [αποθανη]{.corr} και [καταλιπη]{.greek-omitted} [καταλυπη]{.greek-added} γυναικα και [τεν]{.greek-added} [τεκνα]{.corr} μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} [σπερμα]{.greek-omitted}[12:20]{.aside}

[επτα]{.greek-omitted} [αδελφοι]{.greek-omitted} [ησαν]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [ελαβεν]{.greek-omitted} [γυναικα]{.greek-omitted} [και]{.greek-omitted} [αποθνησκων]{.greek-omitted} [ουκ]{.greek-omitted} [αφηκεν]{.greek-omitted} σπερμα[12:20 | instance no. 2]{.aside}

και ο δευτερος [λαβεν]{.greek-added} [ελαβεν]{.corr} αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε [αυτος]{.greek-omitted} [αυτον]{.greek-added} [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ [αφηκαν]{.greek-omitted} [αφηκεν]{.greek-added} σπερμα εσχατη παντων [απεθανεν]{.greek-omitted} [απεθεν]{.greek-added} και η γυνη[12:22]{.aside}

εν τη [αναστε]{.greek-added} [αναστασει]{.corr} οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν [ουτε]{.greek-omitted} [οτε]{.greek-added} γαμισκονται αλλ εισιν ως αγγελοι [ει]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των [εκ]{.greek-added} νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω μωσεως επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν [πολυ]{.greek-omitted} [πολλυ]{.greek-added} πλανασθε[12:27]{.aside}

και προσελ[θων]{.greek-supplied} [εις]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [ακουσας]{.greek-omitted} [αυτων]{.greek-omitted} [συζητουντων]{.greek-omitted} [ειδως]{.greek-omitted} [οτι]{.greek-omitted} [καλως]{.greek-omitted} [αυτοις]{.greek-omitted} [απεκριθη]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ποια]{.greek-omitted} [εστιν]{.greek-omitted} [πρωτη]{.greek-omitted} [παντων]{.greek-omitted} [εντολη]{.greek-omitted}[12:28]{.aside}

[οι]{.greek-omitted} [κατεσθιοντες]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [των]{.greek-omitted} [χηρων]{.greek-omitted} [και]{.greek-omitted} [προ]{.greek-supplied}φασει [μακρα]{.greek-omitted} [μακραν]{.greek-added} προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το [γαζοφυκιον]{.greek-added} [γαζοφυλακιον]{.corr} και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [ευαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [ευαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων βεβληκεν των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισευοντος]{.greek-added} αυτοις εβαλον αυτη δε εκ [της]{.greek-omitted} [υστερησεως]{.greek-omitted} [του]{.greek-added} [υστερηματος]{.greek-added} αυτης παντα οσα ειχεν [εβαλεν]{.greek-omitted} [ευαλε]{.greek-added} ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις [εκ]{.greek-added} των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και [ποποι]{.greek-added} [ποταπαι]{.greek-omitted} [[ποταποι]{.corr}]{.greek-added} οικοδομαι[13:1]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτω βλεπεις ταυτας τας μεγαλας [οι]{.greek-added} [οικοδομας]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [αφεθη]{.greek-omitted} [λιθος]{.greek-omitted} [επι]{.greek-omitted} [λιθω]{.greek-omitted} [ος]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [καταλυθη]{.greek-omitted}[13:2]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [βλεπεις]{.greek-omitted} [ταυτας]{.greek-omitted} [τας]{.greek-omitted} [μεγαλας]{.greek-omitted} [οικοδομας]{.greek-omitted} [κοδομας]{.greek-added} ου μη αφεθη λιθος επι λιθω ος ου [μη]{.greek-omitted} καταλυθη[13:2 | instance no. 2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και ανδρεας[13:3]{.aside}

ειπε [ημιν]{.greek-omitted} [υμιν]{.greek-added} ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις [η[―]{.gap}ξατο]{.greek-added} [ηρξατο]{.corr} λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω [ειμι]{.greek-omitted} [ειμιν]{.greek-added} και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και [ακοας]{.greek-omitted} [ακουας]{.greek-added} πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και [εσονται]{.greek-omitted} λιμοι και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} [ωδινων]{.greek-omitted} [οδινων]{.greek-added} ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και [εις]{.corr} συναγωγας [δαρησεσθε]{.greek-omitted} [δαρησεσθαι]{.greek-added} [και]{.greek-omitted} [επι]{.greek-omitted} [ηγεμονων]{.greek-omitted} [και]{.greek-omitted} [βασιλεων]{.greek-omitted} [σταθησεσθε]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted}[13:9]{.aside}

[βλεπετε]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [εαυτους]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [γαρ]{.greek-omitted} [υμας]{.greek-omitted} [εις]{.greek-omitted} [συνεδρια]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [συναγωγας]{.greek-omitted} [δαρησεσθε]{.greek-omitted} και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9 | instance no. 2]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον [εις]{.greek-added} [μαρτυριον]{.greek-added} [αυτοις]{.greek-added}[13:10]{.aside}

οταν δε αγαγωσιν υμας παραδιδοντες μη προμεριμνατε τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} μηδε [μελετατε]{.greek-omitted} [μελεταται]{.greek-added} αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ [υμεις]{.greek-added} εστε [υμεις]{.greek-omitted} οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον [ων]{.greek-omitted} μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος [μηδε]{.greek-added} [σαββατω]{.greek-added}[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου γεγονεν [τοιαυτη]{.greek-omitted} απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη [γενητ[η]{.unclear}]{.greek-added} [γενηται]{.corr}[13:19]{.aside}

και ει μη [κυριος]{.greek-omitted} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η [ιδου]{.greek-omitted} εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted}[13:22]{.aside}

[εγερθησονται]{.greek-omitted} [γαρ]{.greek-omitted} [ψευδοχριστοι]{.greek-omitted} [και]{.greek-omitted} [ψευδοπροφηται]{.greek-omitted} [και]{.greek-omitted} [δωσουσιν]{.greek-omitted} [σημεια]{.greek-omitted} [και]{.greek-omitted} [τερατα]{.greek-omitted} [προς]{.greek-omitted} [το]{.greek-omitted} [αποπλαναν]{.greek-omitted} [ει]{.greek-omitted} [δυνατον]{.greek-omitted} [και]{.greek-omitted} τους εκλεκτους[13:22 | instance no. 2]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ [εν]{.greek-omitted} [εεν]{.greek-added} εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του ουρανου εσονται εκπιπτοντες και αι δυναμεις αι εν [τοις]{.greek-omitted} [ταις]{.greek-added} ουρανοις [[ουραννοις]{.corr}]{.greek-added} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν [νεφελαις]{.greek-omitted} [εφελαις]{.greek-added} μετα δυναμεως πολλης και δοξης[13:26]{.aside}

και τοτε [αποστελει]{.greek-omitted} [αποστειλει]{.greek-added} τους [αγγελους]{.greek-omitted} [αγγλους]{.greek-added} αυτου και επισυναξει τους εκλεκτους αυτου [εκ]{.greek-omitted} [απο]{.greek-added} των τεσσαρων ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης [μαθετε]{.greek-omitted} [μαθητε]{.greek-added} την παραβολην οταν [αυτης]{.greek-omitted} ηδη ο κλαδος [αυτης]{.greek-added} απαλος γενηται και εκφυη τα φυλλα γινωσκετε οτι εγγυς το θερος εστιν[13:28]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις οταν ταυτα ιδητε γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η [γενεα]{.greek-omitted} [γεν]{.greek-added} [αυτη]{.greek-omitted} [μεχρι]{.greek-omitted} [ου]{.greek-omitted} [παντα]{.greek-omitted} [ταυτα]{.greek-omitted} [γενηται]{.greek-omitted}[13:30]{.aside}

[εα]{.greek-added} [αυτη]{.greek-added} [εως]{.greek-added} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} ου [ταυτα]{.greek-added} [μη]{.greek-omitted} [παρελθη]{.greek-omitted} [η]{.greek-omitted} [γενεα]{.greek-omitted} [αυτη]{.greek-omitted} [μεχρι]{.greek-omitted} [ου]{.greek-omitted} παντα [ταυτα]{.greek-omitted} γενηται[13:30 | instance no. 2]{.aside}

[τοις]{.greek-added} ο ουρανος και η γη [παρελευσεται]{.greek-omitted} [παραλευσονται]{.greek-added} οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[13:31]{.aside}

περι δε της ημερας εκεινης η ωρας ουδεις οιδεν ουδε οι αγγελοι [οι]{.greek-omitted} εν [ουρανω]{.greek-abbr} ουδε ο υιος ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

[γρηγορη]{.greek-added} [γρηγορειτε]{.corr} ουν ουκ οιδατε γαρ ποτε ο κυριος της οικιας ερχεται οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω κρατησαντες [αποκτεινωσιν]{.greek-omitted} [αποκτεινουσιν]{.greek-added}[14:1]{.aside}

ελεγον [δε]{.greek-omitted} [μη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [εορτη]{.greek-omitted} [μηποτε]{.greek-omitted} [θορυβος]{.greek-omitted} [εσται]{.greek-omitted} [του]{.greek-omitted} [λαου]{.greek-omitted}[14:2]{.aside}

[ελεγον]{.greek-omitted} δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2 | instance no. 2]{.aside}

και [οντος]{.greek-omitted} [οντως]{.greek-added} αυτου εν βηθανια εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτου ηλθεν γυνη [εχουσα]{.greek-omitted} αλαβαστρον μυρου [εχουσα]{.greek-added} ναρδου [πικης]{.greek-added} [πιστικης]{.corr} πολυτελους και συντριψασα το αλα[β]{.unclear}αστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο [το]{.greek-added} [μυρω]{.greek-added} πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε [αυτους]{.greek-omitted} ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} [γαρ]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου [ε]{.greek-added} [εαν]{.greek-omitted} [κηρυχθη]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [τουτο]{.greek-omitted} [εις]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [κοσμον]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [εποιησεν]{.greek-omitted} [αυτη]{.greek-omitted} [λαληθησεται]{.greek-omitted} [εις]{.greek-omitted} [μνημοσυνον]{.greek-omitted} [αυτης]{.greek-omitted}[14:9]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οπου]{.greek-omitted} [εαν]{.greek-omitted} [αν]{.greek-added} κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9 | instance no. 2]{.aside}

και ο ιουδας ο [ισκαριωτης]{.greek-omitted} [ισχαριωτης]{.greek-added} εις των [δωδεκα]{.greek-omitted} [δωδεκ]{.greek-added} [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους [αρχιερεις]{.greek-omitted} [αρχιιερεις]{.greek-added} ινα [παραδω]{.greek-omitted} [παραδωσω]{.greek-added} αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη [ημερα]{.greek-omitted} των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και [απαντησει]{.greek-omitted} [απαντησι]{.greek-added} υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων [ακουλουθησατε]{.greek-added} [ακολουθησατε]{.corr} αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη [οτι]{.greek-omitted} ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει [ανωγεον]{.greek-omitted} [ανωγαιον]{.greek-added} μεγα εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και [λεγειν]{.greek-omitted} [λεγει]{.greek-added} αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις [εκ]{.greek-omitted} των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως [γεγραπται]{.greek-omitted} [γειγραπται]{.greek-added} περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος [[εκει]{.unclear}ν[ω]{.unclear}]{.greek-added} [του]{.corr} [[ανθρωπου]{.greek-abbr}]{.corr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} καλον ην αυτω ει ουκ εγεννηθη [ο]{.greek-omitted} [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} [τον]{.greek-added} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [λαβετε]{.greek-omitted} [λαβε]{.greek-added} [φαγετε]{.greek-omitted} [τουτο]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [μου]{.greek-omitted}[14:22]{.aside}

[τε]{.greek-added} [και]{.greek-omitted} [εσθιοντων]{.greek-omitted} [αυτων]{.greek-omitted} [λαβων]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αρτον]{.greek-omitted} [ευλογησας]{.greek-omitted} [εκλασεν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [λαβετε]{.greek-omitted} φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22 | instance no. 2]{.aside}

και λαβων το ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ [αυτον]{.greek-added} [αυτου]{.corr} παντες[14:23]{.aside}

και [ειπεν]{.corr} αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [εστι]{.greek-added} ου μη πιω εκ του [γενηματος]{.greek-omitted} [γεννηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον [εν]{.greek-omitted} [ε]{.greek-added} τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη οτι γεγραπται [πανταξω]{.greek-added} [παταξω]{.corr} [τον]{.greek-omitted} [τοι]{.greek-added} ποιμενα και [δισσκορπισθησεται]{.greek-added} [διασκορπισθησεται]{.corr} τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες [σκανδαλισθησονται]{.greek-omitted} [σκαδαλισθησονται]{.greek-added} αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω [ι]{.greek-added} [ο]{.corr} [ιησους]{.greek-abbr} αμην λεγω σοι οτι [συ]{.greek-omitted} σημερον εν τη [νυκτι]{.greek-omitted} [νυτι]{.greek-added} ταυτη πριν η δις αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [ελεγεν]{.greek-omitted} [μαλλον]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} [σοι]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [σε]{.greek-omitted} [απαρνησωμαι]{.greek-omitted} [ωσαυτως]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [παντες]{.greek-omitted} [ελεγον]{.greek-omitted}[14:31]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον [α]{.greek-added} [εαν]{.corr} [δεη]{.greek-added} με [δεη]{.greek-omitted} συναποθανειν σοι ου μη σε απαρνησωμαι [ωσαυτως]{.greek-omitted} [ωσσαυτως]{.greek-added} δε και παντες [ελεγων]{.greek-added} [ελεγον]{.corr}[14:31 | instance no. 2]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσιμανη]{.greek-added} και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον [πετρο[ς]{.unclear}]{.greek-added} [πετρον]{.corr} και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [μ[η]{.unclear}θ]{.greek-added} [μεθ]{.corr} εαυτου και ηρξατο [εκ[τ]{.unclear}αμβεισθε]{.greek-added} [εκθαμβεισθαι]{.greek-omitted} [[εκθαμβεισθε]{.corr}]{.greek-added} και [αδημονειν]{.greek-omitted} [αδδημονειν]{.greek-added}[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και [γρηρο]{.greek-added} [[γρηρειται]{.corr}]{.greek-added} [γρηγορειτε]{.greek-omitted} [[γρηγορειται]{.corr}]{.greek-added}[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα [ει]{.greek-omitted} δυνατον [εστιν]{.greek-omitted} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον απ εμου [τουτο]{.greek-omitted} [ουτο]{.greek-added} αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και [λεγει]{.greek-omitted} [λεγε]{.greek-added} τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα [μη]{.greek-omitted} [εισελθητε]{.greek-omitted} [εις]{.greek-omitted} [πειρασμον]{.greek-omitted} [το]{.greek-omitted} [μεν]{.greek-omitted} [πνευμα]{.greek-omitted} [προθυμον]{.greek-omitted} [η]{.greek-omitted} [δε]{.greek-omitted} [σαρξ]{.greek-omitted} [ασθενης]{.greek-omitted}[14:38]{.aside}

[γρηγορειτε]{.greek-omitted} [και]{.greek-omitted} [προσευχεσθε]{.greek-omitted} [ινα]{.greek-omitted} μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38 | instance no. 2]{.aside}

και παλιν απελθων προσηυξατο τον αυτον [λογον]{.greek-omitted} [λονγον]{.greek-added} ειπων[14:39]{.aside}

και [υποστρεψας]{.greek-omitted} [αποστρεψας]{.greek-added} ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ ηδεισαν τι αυτω [αποκριθωσιν]{.greek-omitted} [αποκριθωσι]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και [αναπαυεσθε]{.greek-omitted} [αναπαβεσθε]{.greek-added} απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added}[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται [ο]{.greek-added} ιουδας εις ων των [δωδεκε]{.greek-added} [δωδεκα]{.corr} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και [απαγαγετε]{.greek-omitted} [απαγαγε]{.greek-added} [ασφαλως]{.greek-omitted}[14:44]{.aside}

[τε]{.greek-added} [δεδωκει]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [παραδιδους]{.greek-omitted} [αυτον]{.greek-omitted} [συσσημον]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} [ον]{.greek-omitted} [αν]{.greek-omitted} [φιλησω]{.greek-omitted} [αυτος]{.greek-omitted} [εστιν]{.greek-omitted} [κρατησατε]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [απαγαγετε]{.greek-omitted} ασφαλως[14:44 | instance no. 2]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε [επεβαλον]{.greek-omitted} [επευαλον]{.greek-added} επ αυτον τας χειρας αυτων και [εκρατησαν]{.greek-omitted} [κρατησας]{.greek-added} αυτον[14:46]{.aside}

εις δε τις των [παρεστηκοτων]{.greek-omitted} [παραιστικοτων]{.greek-added} σπασαμενος [την]{.greek-omitted} [μαχε]{.greek-added} [μαχαιραν]{.corr} [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων [συλλαβειν]{.greek-omitted} [συλλβειν]{.greek-added} με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και [συν]{.greek-added} [συνερχονται]{.greek-omitted} [αυτω]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted}[14:53]{.aside}

[ερχοντον]{.greek-added} [και]{.greek-omitted} [απηγαγον]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [αρχιερεα]{.greek-omitted} [και]{.greek-omitted} [συνερχονται]{.greek-omitted} αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53 | instance no. 2]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην [συγκαθημενος]{.greek-omitted} [συνκαθημενος]{.greek-added} μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον [τ[ε]{.unclear}]{.greek-added} [το]{.corr} συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις [ηκουσαμεν]{.greek-omitted} [οικουσαμεν]{.greek-added} αυτου λεγοντος οτι εγω [καταλυσω]{.greek-omitted} [καταλεσω]{.greek-added} τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε [ουτως]{.greek-omitted} [ουτος]{.greek-added} ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις [το]{.greek-added} μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη [η]{.greek-added} ουδεν [τοιουτου]{.greek-added} [τι]{.greek-omitted} [ουτοι]{.greek-omitted} σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυ]{.greek-added}[14:60]{.aside}

[ρουσιν]{.greek-added} [και]{.greek-omitted} [αναστας]{.greek-omitted} [ο]{.greek-omitted} [αρχιερευς]{.greek-omitted} [εις]{.greek-omitted} [μεσον]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [λεγων]{.greek-omitted} [ουκ]{.greek-omitted} [αποκρινη]{.greek-omitted} [ουδεν]{.greek-omitted} [τι]{.greek-omitted} [ουτοι]{.greek-omitted} [σου]{.greek-omitted} [καταμαρτυρουσιν]{.greek-omitted}[14:60 | instance no. 2]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο υιος [του]{.greek-omitted} ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των [νεφελων]{.greek-omitted} [εφελων]{.greek-added} του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν φαινεται οι δε παντες κατεκρι[―]{.gap}ναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και [περικαλυπτειν]{.greek-omitted} [περικαλυπτει]{.greek-added} το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται [ραπισμασιν]{.greek-omitted} [ραπησμασιν]{.greek-added} αυτον [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added}[14:65]{.aside}

και [οντος]{.greek-omitted} [οντως]{.greek-added} του [περου]{.greek-added} [πετρου]{.corr} εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον [πε]{.greek-added} [πετρον]{.greek-omitted} [θερμαινομενον]{.greek-omitted} [εμβλεψασα]{.greek-omitted} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} [και]{.greek-omitted} [συ]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [ναζαρηνου]{.greek-omitted} [ιησου]{.greek-omitted} [ησθα]{.greek-omitted}[14:67]{.aside}

[και]{.greek-omitted} [ιδουσα]{.greek-omitted} [τον]{.greek-omitted} [τρον]{.greek-added} [πετρον]{.greek-omitted} θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του [ναζαρηνου]{.greek-omitted} [ναζαρινου]{.greek-added} [ιησου]{.greek-abbr} ησθα[14:67 | instance no. 2]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα [ουδε]{.greek-omitted} [ουε]{.greek-added} [[ουτε]{.corr}]{.greek-added} επισταμαι τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη [ιδουσα]{.greek-omitted} [ηδουσα]{.greek-added} αυτον παλιν [ηρνειτο]{.greek-added} [ηρξατο]{.corr} λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστικωσιν]{.greek-added} οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρειντο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο [αναθεματιζειν]{.greek-omitted} και [[καιταθεματιζειν]{.corr}]{.greek-added} [και]{.greek-added} [ομνυναι]{.greek-omitted} [ομνουναι]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον [λεγετε]{.greek-omitted} [λεγε[σ]{.unclear}τε]{.greek-added}[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} [φωνησαι]{.greek-omitted} [φωνησε]{.greek-added} δις απαρνηση με τρις και επιβαλων [εκλαιεν]{.greek-omitted} [εκλαιε]{.greek-added}[14:72]{.aside}

### Chapter 15

[και]{.greek-omitted} ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [γραμματεων]{.greek-omitted} [και]{.greek-omitted} [ολον]{.greek-omitted} [το]{.greek-omitted} [συνεδριον]{.greek-omitted} [δησαντες]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [απηνεγκαν]{.greek-omitted} [και]{.greek-omitted} [παρεδωκαν]{.greek-omitted} [τω]{.greek-omitted} [πιλατω]{.greek-omitted}[15:1]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [πρωι]{.greek-omitted} [συμβουλιον]{.greek-omitted} [ποιησαντες]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [μετα]{.greek-omitted} των πρεσβυτερων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1 | instance no. 2]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος [βαρββα[―]{.gap}ν]{.greek-added} [βαραββας]{.greek-omitted} [[βαρββας]{.corr}]{.greek-added} μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο [αιτη]{.greek-added} [αιτεισθαι]{.corr} καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω [υ]{.greek-added} [υμιν]{.greek-omitted} [τον]{.greek-omitted} [βασιλεα]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted}[15:9]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [απεκριθη]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} [θελετε]{.greek-omitted} [απολυσω]{.greek-omitted} [υμιν]{.greek-omitted} [μιν]{.greek-added} τον βασιλεα των ιουδαιων[15:9 | instance no. 2]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεπεισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν απολυση[―]{.gap} [[απολυση]{.corr}]{.greek-added} αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} τον [ιησουν]{.greek-abbr} [παρεδωκε]{.greek-added} [φραγελλωσας]{.greek-omitted} [φραγγελωσας]{.greek-added} ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες [ακανθινον]{.greek-omitted} στεφανον [ακανθιον]{.greek-added}[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον [και]{.greek-added} [λεγειν]{.greek-added} χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και [ενεπτυον]{.greek-omitted} [ενεπτυ]{.greek-added} [αυτω]{.greek-omitted} [και]{.greek-omitted} [τιθεντες]{.greek-omitted} [τα]{.greek-omitted} [γονατα]{.greek-omitted} [προσεκυνουν]{.greek-omitted} [αυτω]{.greek-omitted}[15:19]{.aside}

[ον]{.greek-added} [και]{.greek-omitted} [ετυπτον]{.greek-omitted} [αυτου]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [καλαμω]{.greek-omitted} [και]{.greek-omitted} [ενεπτυον]{.greek-omitted} αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19 | instance no. 2]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν [αυτον]{.greek-omitted} [αυτω]{.greek-added} την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον [[ιησουν]{.greek-abbr}]{.greek-added} [ι[ς]{.unclear}]{.greek-added} [ινα]{.corr} [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και αγγαρευουσιν παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} [γολγοθα]{.greek-omitted} [γολγοθαν]{.greek-added} τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και [εδιδουν]{.greek-omitted} [εδιδου]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} [[αυτον]{.corr}]{.greek-added} [πιειν]{.greek-omitted} [ποιειν]{.greek-added} εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον [διαμεριζονται]{.greek-omitted} [διαμεριζοντες]{.greek-added} τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα [τριτη]{.greek-omitted} [τρητη]{.greek-added} και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου [επιγεγραμμενη]{.greek-omitted} [επιγεγραμενη]{.greek-added} ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη [η]{.greek-omitted} [λεγουσα]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [ανομων]{.greek-omitted} [ελογισθη]{.greek-omitted}[15:28]{.aside}

[και]{.greek-omitted} [επληρωθη]{.greek-omitted} η [γραφη]{.greek-omitted} [η]{.greek-omitted} [λεγουσα]{.greek-omitted} [λεγουσαν]{.greek-added} και μετα ανομων ελογισθη[15:28 | instance no. 2]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως [δε]{.greek-added} και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελεγον αλλους [εσωσεν]{.greek-omitted} [εσωσε]{.greek-added} εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι [συνεσταυρωμενοι]{.greek-omitted} [[συνεστρωμενον]{.greek-abbr}]{.greek-added} [αυτω]{.greek-omitted} ωνειδιζον αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη ωρα τη [ενατη]{.greek-omitted} [εννατη]{.greek-added} [ευοησεν]{.greek-added} [εβοησεν]{.corr} ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων [ελωι]{.greek-omitted} [ελωι]{.greek-omitted} [λιμα]{.greek-omitted} [ηλια]{.greek-added} [ηλια]{.greek-added} [ιμας]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβακθανη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των [παρεστηκοτων]{.greek-omitted} [παρεστικοτων]{.greek-added} [ακουσαντες]{.greek-omitted} [ακουσαν]{.greek-added} [ελεγον]{.greek-omitted} [ιδου]{.greek-omitted} [ηλιαν]{.greek-omitted} [φωνει]{.greek-omitted}[15:35]{.aside}

[και]{.greek-omitted} [τινες]{.greek-omitted} [τες]{.greek-added} [των]{.greek-omitted} [παρεστηκοτων]{.greek-omitted} [ακουσαντες]{.greek-omitted} ελεγον [ιδου]{.greek-omitted} [οτι]{.greek-added} ηλιαν φωνει[15:35 | instance no. 2]{.aside}

δραμων δε εις [εξ]{.greek-added} [αυτων]{.greek-added} και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμε[―]{.gap}ν [[ιδωμεν]{.corr}]{.greek-added} ει [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} [αφεις]{.greek-omitted} [κραξας]{.greek-added} [φωνην]{.greek-omitted} [φωνη]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλη]{.greek-added} [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ [εναντι]{.greek-added} [εναντιας]{.corr} αυτου οτι ουτως κραξας εξεπνευσεν ειπεν [αθως]{.greek-added} [αληθως]{.corr} ο [ανθρωπος]{.greek-omitted} [ανθρωπως]{.greek-added} ουτος υιος ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προσαββατον]{.greek-omitted} [προς]{.greek-added} [σαββατων]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελων]{.greek-added} ιωσηφ [ο]{.greek-omitted} [απο]{.greek-omitted} [αριμαθαιας]{.greek-omitted} [ευσχημων]{.greek-omitted} [βουλευτης]{.greek-omitted} [ος]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ην]{.greek-omitted} [προσδεχομενος]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τολμησας]{.greek-omitted} [εισηλθεν]{.greek-omitted} [προς]{.greek-omitted} [πιλατον]{.greek-omitted} [και]{.greek-omitted} [ητησατο]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted}[15:43]{.aside}

[ηλθεν]{.greek-omitted} [ιωσηφ]{.greek-omitted} ο απο [αριμ[―]{.gap}θαιας]{.greek-added} [αριμαθαιας]{.corr} [ευσχημων]{.greek-omitted} [ευσχημο]{.greek-added} [βουλευτης]{.greek-omitted} [μαθητης]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43 | instance no. 2]{.aside}

ο δε πιλατος [[θ]{.unclear}]{.greek-added} [εθαυμασεν]{.corr} ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον [κεντυριωνα]{.greek-omitted} [κεντηριωνα]{.greek-added} επηρωτησεν αυτον ει [παλαι]{.greek-omitted} [παλιν]{.greek-added} [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και [γ[ν]{.unclear}ων]{.greek-added} [γνους]{.corr} απο του [κεντυριωνος]{.greek-omitted} [κεντηριωνος]{.greek-added} εδωρησατο το [σωματος]{.greek-added} [σωμα]{.greek-omitted} [τω]{.greek-omitted} ιωσηφ[15:45]{.aside}

και αγορασας [σινδονα]{.greek-omitted} [σινδωνα]{.greek-added} [και]{.greek-omitted} καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλησε]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλ[η]{.unclear}σε]{.greek-added} [προσεκυλισεν]{.greek-omitted} [[προσεκυλισε]{.corr}]{.greek-added} [λιθον]{.greek-omitted} [λιθων]{.greek-added} επι την θυραν του μνημει[ο]{.unclear}υ[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που [τιθεται]{.greek-omitted} [τεθηται]{.greek-added}[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα [ελθουσαι]{.greek-omitted} [ελθου]{.greek-added} [αλειψωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[16:1]{.aside}

[σαι]{.greek-added} [και]{.greek-omitted} [διαγενομενου]{.greek-omitted} [του]{.greek-omitted} [σαββατου]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [σαλωμη]{.greek-omitted} [ηγορασαν]{.greek-omitted} [αρωματα]{.greek-omitted} [ινα]{.greek-omitted} [ελθουσαι]{.greek-omitted} [αλειψωσιν]{.greek-omitted} [αληψωσιν]{.greek-added} αυτον[16:1 | instance no. 2]{.aside}

και λιαν πρωι της μιας σαββατων [ερχονται]{.greek-omitted} [ερχοται]{.greek-added} επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει [ημιν]{.greek-omitted} [υμιν]{.greek-added} τον λιθον [εκ]{.greek-omitted} [απο]{.greek-added} της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον [καθημενο[ς]{.unclear}]{.greek-added} [καθημενον]{.corr} εν τοις δεξιοις [περιβεβλημενον]{.greek-omitted} [περιβεβλημενος]{.greek-added} στολην λευκην και [εξεθαμβηθησαν]{.greek-omitted} [εξεθαμβηθησας]{.greek-added}[16:5]{.aside}

ο δε λεγει αυταις μη [εκθαμβ[η]{.unclear}]{.greek-added} [εκθαμβεισθε]{.corr} [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [αζαρηνον]{.greek-added} τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του [μνημειου]{.greek-omitted} [μνημειον]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν [ει]{.greek-added} [ειπον]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted}[16:8]{.aside}

[και]{.greek-omitted} [εξελθουσαι]{.greek-omitted} [εφυγον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [μνημειου]{.greek-omitted} [ειχεν]{.greek-omitted} [δε]{.greek-omitted} [αυτας]{.greek-omitted} [τρομος]{.greek-omitted} [και]{.greek-omitted} [εκστασις]{.greek-omitted} [και]{.greek-omitted} [ουδενι]{.greek-omitted} [ουδεν]{.greek-omitted} [ειπον]{.greek-omitted} [πον]{.greek-added} εφοβουντο γαρ[16:8 | instance no. 2]{.aside}

αναστας [δε]{.greek-omitted} [ε]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι πρωτη [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} [δε]{.greek-added} [εφανη]{.greek-omitted} [φανη]{.greek-added} πρωτον μαρια τη μαγδαληνη [η]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις [μετ]{.greek-omitted} [μετα]{.greek-added} [αυτου]{.greek-omitted} [του]{.greek-added} γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ [αυτον]{.greek-added} [αυτων]{.corr} περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες [απηγγειλαν]{.greek-omitted} [ανηγγειλαν]{.greek-added} τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον [δε]{.greek-added} ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδησε]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον [εγειγηρμενον]{.greek-added} [εγηγερμενον]{.corr} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον [απαντα]{.greek-omitted} [απατα]{.greek-added} κηρυξατ[ε]{.unclear} το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται [ο]{.greek-omitted} [δε]{.greek-omitted} [απιστησας]{.greek-omitted} [κατακριθησεται]{.greek-omitted}[16:16]{.aside}

[ο]{.greek-omitted} [πιστευσας]{.greek-omitted} [και]{.greek-omitted} [βαπτισθεις]{.greek-omitted} [σωθησεται]{.greek-omitted} ο δε απιστησας κατακριθησεται[16:16 | instance no. 2]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} [γλωσσαις]{.greek-omitted} [γλωσαις]{.greek-added} [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις [ανεληφθη]{.greek-omitted} [ανελινφθη]{.greek-added} εις τον [ουρανον]{.greek-abbr} [και]{.corr} [καθησεν]{.greek-added} [εκαθισεν]{.corr} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των [επακολουθουντων]{.greek-omitted} [επακολουλουντων]{.greek-added} σημειων αμην[16:20]{.aside}

