---
title: "Collation of Byz^RP^ vs 30842 (842)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 842 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30842).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 842                                   	| λογος                              	|
| 842 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 842 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 842               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 842                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 842 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 842                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

βιβλος γενεσεως ιησου [χριστου]{.greek-abbr} υιου [δαυιδ]{.greek-abbr} υιου αβρααμ[1:1]{.aside}

αβρααμ [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ ισαακ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιουδαν και τους αδελφους αυτου[1:2]{.aside}

ιουδας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον φαρες και τον ζαρα εκ της θαμαρ φαρες δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εσρωμ εσρωμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αραμ[1:3]{.aside}

αραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμιναδαβ αμιναδαβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ναασσων ναασσων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλμων[1:4]{.aside}

σαλμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον βοοζ εκ της ραχαβ βοοζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ωβηδ εκ της ρουθ ωβηδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τ[ο]{.unclear}ν ιεσσαι[1:5]{.aside}

ιεσσαι δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [δαυιδ]{.greek-abbr} τον βασιλεα [δαυιδ]{.greek-abbr} δε ο βασιλευς [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σολομωνα εκ της του ουριου[1:6]{.aside}

σολομων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ασα[1:7]{.aside}

ασα δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσαφατ ιωσαφατ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον οζιαν[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωαθαμ ιωαθαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχαζ αχαζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εζεκιαν[1:9]{.aside}

εζεκιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [μανασση]{.greek-omitted} [μανασσην]{.greek-added} μανασσης δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμων αμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεχονιαν και τους αδελφους αυτου επι της μετοικεσιας βαβυλωνος[1:11]{.aside}

μετα δε την μετοικεσιαν βαβυλωνος ιεχονιας [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλαθιηλ σαλαθιηλ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβιουδ αβιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιακειμ ελιακειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχειμ αχειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελεαζαρ ελεαζαρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

πασαι ουν αι γενεαι απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεαι δεκατεσσαρες και απο [δαυιδ]{.greek-abbr} εως της μετοικεσιας βαβυλωνος γενεαι δεκατεσσαρες και απο της μετοικεσιας βαβυλωνος εως του [χριστου]{.greek-abbr} γενεαι δεκατεσσαρες[1:17]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην μνηστευθεισης γαρ της μητρος αυτου μαριας τω ιωσηφ πριν η συνελθειν αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην παραδειγματισαι [εβουληθη]{.greek-omitted} [ηβουληθη]{.greek-added} λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ εφανη αυτω λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη φοβηθης παραλαβειν [μαριαμ]{.greek-omitted} [μαριαν]{.greek-added} την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

τεξεται δε υιον και καλεσεις το ονομα αυτου ιησουν αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων [αυτων]{.greek-omitted} [αυτου]{.greek-added}[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου [λεγοντος]{.greek-omitted}[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται υιον και [καλεσουσιν]{.greek-omitted} [καλεσουσι]{.greek-added} το ονομα αυτου εμμανουηλ ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε ο ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου ετεκεν τον υιον αυτης τον πρωτοτοκον και [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

του δε [ιησου]{.greek-abbr} γεννηθεντος εν βηθλεεμ της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων ειδομεν γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι [αυτω]{.greek-omitted} [αυτον]{.greek-added}[2:2]{.aside}

ακουσας δε ηρωδης ο βασιλευς εταραχθη και πασα [η]{.greek-added} ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και γραμματεις του λαου [επυνθανετο]{.greek-omitted} [παρ]{.greek-omitted} [αυτων]{.greek-omitted} [που]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [γενναται]{.greek-omitted}[2:4]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ουδαμως ελαχιστη ει εν τοις ηγεμοσιν ιουδα εκ σου γαρ εξελευσεται ηγουμενος οστις ποιμανει τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε [μοι]{.greek-omitted} οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ ον ειδον εν τη ανατολη προηγεν αυτους εως [ου]{.greek-added} ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα εχαρησαν χαραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες εις την οικιαν ειδον το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδου αγγελος [κυριου]{.greek-abbr} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε [εγερθεις]{.greek-omitted} [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον [υιον]{.greek-abbr} μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη λιαν και αποστειλας [ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} παντας τους παιδας τους εν βηθλεεμ [και]{.greek-omitted} [εν]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [οριοις]{.greek-omitted} [αυτης]{.greek-omitted} [απο]{.greek-omitted} [διετους]{.greek-omitted} [και]{.greek-omitted} [κατωτερω]{.greek-omitted} [κατα]{.greek-omitted} [τον]{.greek-omitted} [χρονον]{.greek-omitted} [ον]{.greek-omitted} [ηκριβωσεν]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} [μαγων]{.greek-omitted}[2:16]{.aside}

τοτε επληρωθη το ρηθεν υπο [ιερεμιου]{.greek-omitted} του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ φαινεται τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} [τεθνηκασιν]{.greek-omitted} [τεθνηκασι]{.greek-added} γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην ισραηλ[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει επι της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν εις πολιν [λεγομενην]{.greek-omitted} ναζαρετ οπως πληρωθη το ρηθεν [δια]{.greek-omitted} [υπο]{.greek-added} των προφητων οτι ναζωραιος κληθησεται[2:23]{.aside}

### Chapter 3

εν [δε]{.greek-omitted} ταις ημεραις εκειναις παραγινεται ιωαννης ο βαπτιστης [κηρυσσων]{.greek-omitted} εν τη ερημω της ιουδαιας [κηρυσσων]{.greek-added}[3:1]{.aside}

και λεγων μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των ουρανων[3:2]{.aside}

ουτος γαρ εστιν ο ρηθεις υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδ[ε]{.unclear}ς και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον [η]{.greek-added} ιεροσολυμα και πασα η ιουδαια και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο [εν]{.greek-omitted} [τω]{.greek-omitted} [ιορδανη]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισμα αυτου [ειπεν]{.greek-omitted} [ελεγεν]{.greek-added} αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν εαυτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} [και]{.greek-added} εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε [και]{.greek-omitted} η αξινη προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[3:10]{.aside}

εγω μεν [υμας]{.greek-added} βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον αυτου εις την αποθηκην το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} διεκωλυεν αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ ερχ[η]{.unclear} προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον αφες α[ρ]{.unclear}τι [ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ πρ[ε]{.unclear}πον [εστιν]{.greek-omitted} [εστι]{.greek-added} [ημιν]{.greek-omitted} πληρωσαι πασαν δικαιοσυνην [τοτε]{.greek-omitted} [αφιησιν]{.greek-omitted} [αυτον]{.greek-omitted}[3:15]{.aside}

και [βα]{.unclear}πτισθεις ο [ιησους]{.greek-abbr} [[ευ]{.unclear}θυς]{.greek-added} ανεβη [ευθυς]{.greek-omitted} απο του υδατος [κ]{.unclear}αι ιδου ανεωχθησαν [αυτω]{.greek-omitted} οι [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} κατα[βαι]{.unclear}νον ωσει περιστεραν και [ερχομενον]{.greek-omitted} [μενον]{.greek-added} επ αυτον[3:16]{.aside}

[και]{.greek-omitted} [ιδου]{.greek-omitted} [φωνη]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [λεγουσα]{.greek-omitted} ουτος εστιν ο υιος μου ο αγαπητος εν ω ευδοκησα[3:17]{.aside}

### Chapter 4

τοτε [ανηχθη]{.greek-added} ο [ιησους]{.greek-abbr} [ανηχθη]{.greek-omitted} εις την ερημον υπο του [πνευματος]{.greek-abbr} [πειρασθηναι]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [διαβολου]{.greek-omitted}[4:1]{.aside}

και νηστευσας ημερας τεσσαρακοντα και νυκτας τεσσαρακοντα υστερον επεινασεν[4:2]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [πειραζων]{.greek-omitted} [ειπεν]{.greek-omitted} ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι γενωνται[4:3]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} γεγραπται ουκ επ αρτω μονω ζησεται [ανθρωπος]{.greek-abbr} αλλ [επι]{.greek-omitted} [εν]{.greek-added} παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει υιος ει του [θεου]{.greek-abbr} βαλε σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου [εντελειται]{.greek-omitted} [εντελειτε]{.greek-added} περι σου και επι χειρων [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} παλιν γεγραπται ουκ εκπειρασεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν παραλαμβανει αυτον ο διαβολος εις ορος υψηλον λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω μονω λατρευσεις[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} οτι [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} παρεδοθη ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την ναζαρετ ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και νεφθαλειμ[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων [και]{.greek-omitted} γη νεφθαλειμ οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} [ειδε]{.greek-added} φως μεγα και τοις καθημενοις εν [χωρα]{.greek-omitted} [σκοτει]{.greek-added} και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν δυο αδελφους σιμωνα τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου [βαλλοντας]{.greek-omitted} [βαλλον]{.greek-added} αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω υμας αλιεις ανθρωπων[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν ειδεν αλλους δυο αδελφους ιακωβον τον [του]{.greek-omitted} ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας τα δικτ[υ]{.unclear}α αυτων [και]{.greek-omitted} [εκαλεσεν]{.greek-omitted} [αυτους]{.greek-omitted}[4:21]{.aside}

οι δε ευθεως αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ολην την γαλιλαιαν [ο]{.greek-omitted} [ιησους]{.greek-omitted} διδασκων εν ταις συναγω[γαις]{.unclear} [αυτων]{.unclear} [και]{.greek-omitted} [κηρυσσων]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [της]{.greek-omitted} [βασιλειας]{.greek-omitted} [και]{.greek-omitted} [θεραπευων]{.greek-omitted} [πασαν]{.greek-omitted} [νοσον]{.greek-omitted} [και]{.greek-omitted} [πασαν]{.greek-omitted} [μαλακιαν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [λαω]{.greek-omitted}[4:23]{.aside}

και [απηλθεν]{.greek-omitted} [εξηλθεν]{.greek-added} η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και βασανοις συνεχομενους και [δαιμονιζομενους]{.greek-omitted} [και]{.greek-omitted} σεληνιαζομενους και [παραλυτικους]{.greek-omitted} [παραλυτους]{.greek-added} και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

[και]{.greek-added} ιδων [δε]{.greek-omitted} τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον αυτω οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους [λεγων]{.greek-omitted}[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθησονται[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομησουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι πεινωντες και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

μακαριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι εστε οταν ονειδισωσιν υμας και [διωξωσιν]{.greek-omitted} [διωρωσι]{.greek-added} και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις [ουρανοις]{.greek-abbr} [ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το αλας της γης εαν δε το [α]{.unclear}λας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και τιθεασιν αυτον υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων εμπροσθεν των [ανθρωπων]{.greek-abbr} οπως ιδωσιν υμων τα καλα εργα και [δοξασωσιν]{.greek-omitted} [δοξασωσι]{.greek-added} τον [πατερα]{.greek-abbr} υμων τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν [παρελθη]{.greek-omitted} [παρελθοι]{.greek-added} ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η μια κεραια ου μη παρελθη [απο]{.greek-omitted} [εκ]{.greek-added} του νομου εως αν [ταυτα]{.greek-added} παντα γενηται[5:18]{.aside}

ος [εαν]{.greek-omitted} [αν]{.greek-added} [ουν]{.greek-omitted} λυση μιαν των εντολων τουτων των ελαχιστων και διδαξη ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν ποιηση και διδαξη ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση η δικαιοσυνη υμων πλειον των [φαρισαιων]{.greek-added} [και]{.greek-added} γραμματεων [και]{.greek-omitted} [φαρισαιων]{.greek-omitted} ου μη [εισελθητε]{.greek-omitted} [εισελθη]{.greek-added} εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι [ερρεθη]{.greek-omitted} [ερρηθη]{.greek-added} τοις αρχαιοις ου φονευσεις ος δ αν φονευση ενοχος εσται τη κρισει[5:21]{.aside}

εγω δε λεγω υμιν [οτι]{.greek-omitted} [πας]{.greek-omitted} ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν ειπη τω αδελφω αυτου [ρακα]{.greek-omitted} [ρακκα]{.greek-added} ενοχος εσται τω συνεδριω ος δ αν ειπη μωρε ενοχος εσται εις την γεενναν του πυρος[5:22]{.aside}

εαν [ουν]{.greek-omitted} προσφερης το δωρον σου επι το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες [εκει]{.greek-omitted} το δωρον σου εμπροσθεν του θυσιαστηριου και [υπαγε]{.greek-omitted} [απελθε]{.greek-added} πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην βληθηση[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης [εκειθεν]{.greek-omitted} [εκεισε]{.greek-added} εως [αν]{.greek-omitted} [ου]{.greek-added} αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη [ου]{.greek-omitted} [μη]{.greek-added} [μοιχευσεις]{.greek-omitted} [μοιχευσης]{.greek-added}[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο [βλεπων]{.greek-omitted} [εμβλεπων]{.greek-added} [γυναικα]{.greek-omitted} [γυναικι]{.greek-added} προς το επιθυμησαι [αυτην]{.greek-omitted} ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

[εαν]{.greek-added} [ει]{.greek-omitted} [δε]{.greek-omitted} ο οφθαλμος σου ο δεξιος [σκανδαλιζει]{.greek-omitted} [σκανδαλιζη]{.greek-added} σε [εξελε]{.greek-omitted} [εκκοψον]{.greek-added} αυτον και [βαλε]{.greek-omitted} [εκβαλε]{.greek-added} απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις [την]{.greek-added} γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ σκανδαλιζει σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων [σο]{.unclear}υ και μη ολον το σωμα σου βληθη εις [την]{.greek-added} γεενναν[5:30]{.aside}

ερρεθη δε οτι ος αν απολυση την γυναικα αυτου δοτω αυτη αποστασιον[5:31]{.aside}

εγω δε λεγω υμιν οτι ος αν απολυση την γυναικα αυτου παρεκτος λογου πορνειας ποιει αυτην μοιχασθαι και ος εαν απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε τω [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω [υμιν]{.greek-omitted} μη ομοσαι ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον [εστιν]{.greek-omitted} [εστι]{.greek-added} των ποδων αυτου μητε εις ιεροσολυμα οτι πολις [εστιν]{.greek-omitted} [εστι]{.greek-added} του μεγαλου βασιλεως[5:35]{.aside}

μητε [εν]{.greek-omitted} [κατα]{.greek-added} [τη]{.greek-omitted} [της]{.greek-added} [κεφαλη]{.greek-omitted} [κεφαλης]{.greek-added} σου ομοσης οτι ου δυνασαι μιαν τριχα λευκην η μελαιναν ποιησαι[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου εστιν[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω αλλ οστις σε [ραπισει]{.greek-omitted} [ραπιση]{.greek-added} επι την δεξιαν σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και τω θελοντι [σοι]{.greek-omitted} κριθηναι και τον χιτωνα σου λαβειν αφες αυτω και το ιματιον[5:40]{.aside}

και οστις σε αγγαρευσει μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

[τω]{.greek-omitted} [αιτουντι]{.greek-omitted} [σε]{.greek-omitted} [διδου]{.greek-omitted} και τον θελοντα [δανεισθηναι]{.greek-added} απο σου [δανεισασθαι]{.greek-omitted} μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και μισησεις τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων ευλογειτε τους καταρωμενους υμας [καλως]{.greek-omitted} [ποιειτε]{.greek-omitted} [τοις]{.greek-omitted} [μισουσιν]{.greek-omitted} [υμας]{.greek-omitted} και προσευχεσθε υπερ των επηρεαζοντων υμας και διωκοντων υμας[5:44]{.aside}

οπως γενησθε υιοι του [πατρος]{.greek-abbr} υμων του εν τοις [ουρανοις]{.greek-abbr} οτι τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ αγαπησητε τους αγαπωντας υμας τινα [μισθον]{.greek-omitted} [χαριν]{.greek-added} εχετε ουχι και οι [εθνικοι]{.greek-added} [τουτο]{.greek-added} [τελωναι]{.greek-omitted} [το]{.greek-omitted} [αυτο]{.greek-omitted} ποιουσι[ν]{.unclear}[5:46]{.aside}

[και]{.greek-omitted} εαν ασπασησθε τους φιλους υμων μονον τι περισσον ποιειτε ουχι και οι τελωναι [ουτως]{.greek-omitted} [ουτω]{.greek-added} ποιουσιν[5:47]{.aside}

εσεσθε ουν υμεις τελειοι ωσπερ ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} τελειος εστιν[5:48]{.aside}

### Chapter 6

προσεχετε την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν ποιης ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρ[υ]{.unclear}μαις [οπως]{.greek-omitted} [δοξασθωσιν]{.greek-omitted} [υπο]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} αμην λεγω υμιν [οτι]{.greek-added} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω [αυτος]{.greek-omitted} αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται οτι φιλουσιν εν ταις [συναγωγαις]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} γωνιαις των πλατειων εστωτες προσευχεσθαι οπως [αν]{.greek-omitted} [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το ταμιειον σου και κλεισας την θυραν σου προσευξαι τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [σου]{.greek-omitted} [ο]{.greek-omitted} [βλεπων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κρυπτω]{.greek-omitted} [αποδωσει]{.greek-omitted} [σοι]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [φανερω]{.greek-omitted}[6:6]{.aside}

προσευχομενοι δε μη βαττολογησητε ωσπερ οι εθνικοι [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

[μη]{.greek-omitted} [ουν]{.greek-omitted} [ομοιωθητε]{.greek-omitted} [αυτοις]{.greek-omitted} [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} υμων ων χρειαν εχετε προ του υμας αιτησαι αυτον[6:8]{.aside}

ουτως ουν προσευχεσθε [υμεις]{.greek-omitted} [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το ονομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων ως και ημεις αφιεμεν τοις οφειλεταις ημων[6:12]{.aside}

και μη εισενεγκης ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [αμην]{.greek-omitted}[6:13]{.aside}

εαν γαρ αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων αφησει τα παραπτωματα υμων[6:15]{.aside}

οταν δε νηστευητε μη γινεσθε ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [τον]{.greek-omitted} [μισθον]{.greek-omitted} [αυτων]{.greek-omitted}[6:16]{.aside}

συ δε νηστευων αλειψαι σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [σου]{.greek-omitted} [ο]{.greek-omitted} [βλεπων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κρυπτω]{.greek-omitted} [αποδωσει]{.greek-omitted} [σοι]{.greek-omitted}[6:18]{.aside}

μη θησαυριζετε υμιν θησαυρους επι της γης οπου σης και βρωσις αφανιζει και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορυσσουσι]{.greek-added} και [κλεπτουσιν]{.greek-omitted} [κλεπτουσι]{.greek-added}[6:19]{.aside}

θησαυριζετε δε υμιν θησαυρους εν [ουρανω]{.greek-abbr} οπου ουτε σης ουτε βρωσις αφανιζει και οπου κλεπται ου διορυσσουσιν ουδε κλεπτουσιν[6:20]{.aside}

οπου γαρ εστιν ο θησαυρος υμων εκει εσται και η καρδια υμων[6:21]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους [η]{.unclear} ολον το σωμα σου [φωτεινον]{.greek-omitted} [απλουν]{.greek-added} εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος [εστιν]{.greek-omitted} [εστι]{.greek-added} το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η [του]{.greek-added} ενος ανθεξεται και του ετερου καταφρονησει ου δυνασθε [θεω]{.greek-abbr} δουλευειν και μαμωνα[6:24]{.aside}

δια τουτο λεγω υμιν μη μεριμνατε τη ψυχη υμων τι φαγητε και τι πιητε μηδε τω σωματι υμων τι [ενδυσησθε]{.greek-omitted} [ενδυσεσθε]{.greek-added} [ουχι]{.greek-omitted} [οχι]{.greek-added} η ψυχη πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα πετεινα του [ουρανου]{.greek-abbr} οτι ου σπειρουσιν ουδε θεριζουσιν ουδε συναγουσιν εις [αποθηκας]{.greek-omitted} [αποθηκην]{.greek-added} και ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} τρεφει αυτα ουχ υμεις μαλλον διαφερετε αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται προσθειναι επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε νηθει[6:28]{.aside}

λεγω δε υμιν οτι ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλομενον [ο]{.unclear} [θεος]{.greek-abbr} ουτως αμφιεννυσιν ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν μεριμνησητε λεγοντες τι φαγωμεν [η]{.greek-omitted} [και]{.greek-added} τι πιωμεν η τι [περιβαλωμεθα]{.greek-omitted} [περιβαλλωμεθα]{.greek-added}[6:31]{.aside}

[ταυτα]{.greek-added} [γαρ]{.greek-added} παντα [γαρ]{.greek-omitted} [ταυτα]{.greek-omitted} τα εθνη επιζητει [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} οτι χρηζετε τουτων απαντων[6:32]{.aside}

ζητειτε δε πρωτον την βασιλειαν του [θεου]{.greek-abbr} και την δικαιοσυνην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν μεριμνησητε εις την αυριον η γαρ αυριον μεριμνησει [τα]{.greek-omitted} εαυτης αρκετον τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

μη κρινετε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε κριθησεσθε και εν ω μετρω μετρειτε μετρηθησεται υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος το εν τω οφθαλμω του αδελφου σου την δε εν τω σω οφθαλμω δοκον ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες [εκβαλω]{.greek-omitted} [εκβαλλω]{.greek-added} το καρφος απο του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη [δωτε]{.greek-omitted} [δοτε]{.greek-added} [το]{.greek-omitted} [αγιον]{.greek-omitted} [τα]{.greek-added} [αγια]{.greek-added} τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε βαλητε τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε καταπατησωσιν αυτους εν τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

αιτειτε και δοθησεται υμιν [ζητειτε]{.greek-omitted} [και]{.greek-omitted} [ευρησετε]{.greek-omitted} κρουετε και ανοιγησεται [υμιν]{.greek-omitted}[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις εστιν εξ υμων [ανθρωπος]{.greek-abbr} ον εαν αιτηση ο υιος αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

παντα ουν οσα αν θελητε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} [ουτως]{.greek-omitted} και υμεις ποιειτε αυτοις ουτος γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

εισελθετε δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

τι στενη η πυλη και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

προσεχετε [δε]{.greek-omitted} απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον σαπρον καρπους καλους ποιειν[7:18]{.aside}

παν [ουν]{.greek-added} δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου τω σω ονοματι προεφητευσαμεν και τω σω ονοματι δαιμονια εξεβαλομεν και τω σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε ομολογησω αυτοις οτι ουδεποτε εγνων υμας αποχωρειτε απ εμου οι εργαζομενοι την ανομιαν[7:23]{.aside}

πας ουν οστις ακουει μου τους λογους τουτους και ποιει αυτους ομοιωσω αυτον ανδρι φρονιμω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και [ηλθον]{.greek-omitted} [οι]{.greek-omitted} [ποταμοι]{.greek-omitted} [και]{.greek-omitted} επνευσαν οι ανεμοι και [προσεπεσον]{.greek-omitted} [προσεπεσ[α]{.unclear}ν]{.greek-added} τη οικια εκεινη και ουκ [επεσεν]{.greek-omitted} [επεσε]{.greek-added} τεθεμελιωτο γαρ επι [την]{.corr} πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη [και]{.greek-omitted} [ηλθον]{.greek-omitted} [οι]{.greek-omitted} [ποταμοι]{.greek-omitted} και επνευσαν οι ανεμοι και προσεκοψαν τη οικια εκεινη και [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγενετο οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[7:29]{.aside}

### Chapter 8

καταβαντι δε αυτω απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου λεπρος [ελθων]{.greek-omitted} [προσελθων]{.greek-added} προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} εαν θελης δυνασαι με καθαρισαι[8:2]{.aside}

[και]{.greek-omitted} [εκτεινας]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [ηψατο]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγων]{.greek-omitted} θελω καθαρισθητι και ευθεως εκαθαρισθη αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι ειπης αλλα υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} το δωρον ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε αυτω εις καπερναουμ προσηλθεν αυτω εκατονταρχος παρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου βεβλητ[α]{.unclear}ι εν τη οικια παραλυτικος δεινως βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος [εφη]{.greek-omitted} [φησι]{.greek-added} [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι [υπο]{.greek-omitted} [υπ]{.greek-added} εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} [εθαυμασεν]{.greek-omitted} [εθαυμασε]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις ακολουθουσιν αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[8:10]{.aside}

λεγω δε υμιν οτι [πολλοι]{.greek-omitted} απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και ανακλιθησονται μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω [εκατονταρχη]{.greek-omitted} [εκαντονταρχω]{.greek-added} υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη[8:13]{.aside}

και [ελθων]{.greek-omitted} [εισελθων]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα [πνευματα]{.greek-abbr} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο ιησους πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν απερχη[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κλιναι]{.greek-added}[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

[και]{.greek-omitted} εμβαντι [δε]{.greek-added} αυτω εις το πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων αυτος δε εκαθευδεν[8:24]{.aside}

και προσελθοντ[ε]{.unclear}ς οι μαθηται ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι [τοτε]{.greek-omitted} [και]{.greek-added} εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

και ελθοντι [αυτω]{.greek-added} αυτω εις το περαν εις την χωραν των γεργεσηνων υπηντησαν αυτω δυο δαιμονιζομενοι εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και σοι [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων [π]{.unclear}ολλων βοσκομενη[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει εκβαλλεις ημας επιτρεψον ημιν απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου [ωρμησεν]{.greek-omitted} [ωρμησε]{.greek-added} πασα η αγελη των χοιρων κατα του κρημνου εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις το πλοιον [διεπερασεν]{.greek-omitted} [διεπερασε]{.greek-added} και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω παραλυτικω θαρσει τεκνον αφεωνται σοι αι αμαρτιαι σου[9:2]{.aside}

και ιδου τινες των γραμματεων ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και ιδων ο [ιησους]{.greek-abbr} τα[ς]{.unclear} ενθυμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις [πονηρα]{.greek-added} ενθυμεισθε [πονηρα]{.greek-omitted} εν [ταις]{.greek-omitted} [τη]{.greek-added} [καρδιαις]{.greek-omitted} [καρδια]{.greek-added} υμων[9:4]{.aside}

τι γαρ εστιν ευκοπωτερον ειπειν αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι [σου]{.greek-added} η ειπειν εγειραι και περιπατει[9:5]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} επι [της]{.greek-omitted} γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

και παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} καθημενον επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων εσθιει [και]{.greek-added} [πινει]{.greek-added} ο διδασκαλος υμων[9:11]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ακουσας]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν ελεον θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε μαθηται σου ου νηστευουσιν[9:14]{.aside}

[και]{.greek-omitted} ειπεν [ουν]{.greek-added} αυτοις ο [ιησους]{.greek-abbr} μη [δυναται]{.greek-added} [δυνανται]{.corr} οι υιοι του νυμφωνος πενθειν εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

ουδεις [δε]{.greek-omitted} [εβαλλει]{.greek-added} [επιβαλλει]{.corr} επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και χειρον σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος εκχειται και οι ασκοι απολουνται αλλα βαλλουσιν οινον νεον εις ασκους καινους και αμφοτεροι συντηρουνται[9:17]{.aside}

ταυτα αυτου λαλουντος αυτοις ιδου αρχων [εις]{.greek-omitted} [ελθων]{.greek-omitted} [εἷς]{.greek-added} [ἐλ]{.greek-added} [θὼν]{.greek-added} προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν αλλα ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον αψωμαι του ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} θαρσει θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδ[ω]{.unclear}ν τους αυλητας και τον οχλον θορυβουμεν[ον]{.unclear}[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισελθων [εκρατησεν]{.greek-omitted} [εκρατη[σε]{.unclear}]{.greek-added} [της]{.unclear} χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

και παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

ελθοντι δε [αυτω]{.greek-added} εις την οικιαν προσηλθον αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} πιστευετε οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων αυτων λεγων κατα την πιστιν υμων γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες διεφημισαν αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες ουδεποτε [εφαν]{.greek-added} [εφανη]{.corr} ουτως εν τω ισραηλ[9:33]{.aside}

οι δε φαρισαιοι ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολ[ει]{.unclear}ς πασας και τας κωμας διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[9:35]{.aside}

ιδων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν [εσκυλμενοι]{.greek-omitted} [εκλελυμενοι]{.greek-added} και ερριμμενοι ωσει προβατα μη εχοντα ποιμενα[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του κυριου του θερισμου οπως εκβαλη εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

και προσκαλε[σ]{.unclear}αμενος τους δωδεκα μαθητας αυτου [εδωκεν]{.greek-omitted} [δεδωκεν]{.greek-added} αυτοις εξουσιαν [πνευματων]{.greek-abbr} ακαθαρτων ωστε εκβαλλειν αυτα και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

των δε δωδεκα αποστολων τα ονο[μ]{.unclear}ατα [εστιν]{.greek-omitted} [εστι]{.greek-added} ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου ιακωβος ο του ζεβεδαιου και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και [λεββαιος]{.greek-omitted} [λεβαιος]{.greek-added} ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο κανανιτης και ιουδας [ο]{.greek-added} ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους δωδεκα απεστειλεν ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν σαμαρειτων μη εισελθητε[10:5]{.aside}

πορευεσθε [δε]{.greek-omitted} μαλλον προς τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρ[υ]{.unclear}σσετε λεγοντες οτι ηγγικεν η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας θεραπευετε λεπρους καθαριζετε δαιμονια εκβαλλετε δωρεαν ελαβετε δωρεαν δοτε[10:8]{.aside}

μη κτησησθε χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε ραβδους αξιος γαρ ο εργατης της τροφης αυτου [εστιν]{.greek-omitted}[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις εν αυτη αξιος [εστιν]{.greek-omitted} [εστι]{.greek-added} κακει μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν ασπασασθε αυτην[10:12]{.aside}

και εαν μεν η η οικια αξια [ελθετω]{.greek-omitted} [εισελθετω]{.greek-added} η ειρηνη υμων επ αυτην εαν δε μη η αξια η ειρηνη υμων προς υμας επιστραφητω[10:13]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της οικιας η της πολεως εκεινης εκτιν[α]{.unclear}ξατε τον κονιορτον των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν ανεκτοτερον εσται γη σοδομων και γομορρων εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων γινεσθε ουν φρονιμοι [ωσει]{.greek-added} [ως]{.greek-omitted} [οι]{.greek-omitted} οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε παραδιδωσιν υμας μη [μερισητε]{.greek-added} [μεριμνησητε]{.corr} πως η τι λαλησητε [[λαλησετε]{.corr}]{.greek-added} δοθησεται γαρ υμιν εν εκεινη τη ωρα τι λαλησετε[10:19]{.aside}

ου γαρ υμεις εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν [υμιν]{.greek-omitted} [εμοι]{.greek-added}[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[10:22]{.aside}

οταν [δε]{.greek-omitted} διωκωσιν υμας εν τη πολει ταυτη φευγετε εις την αλλην αμην γαρ λεγω υμιν ου μη τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης υπερ τον διδασκαλον ουδε δουλος υπερ τον [κυριον]{.greek-abbr} αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα γενηται ως ο διδασκαλος αυτου και ο δουλος ως ο κυριος αυτου ει τον οικοδεσποτην βεελζεβουλ [εκαλεσαν]{.greek-omitted} [επεκαλεσαν]{.greek-added} ποσω μαλλον τους οικειακους αυτου[10:25]{.aside}

μη ουν φοβηθητε αυτους ουδεν γαρ εστιν κεκαλυμμενον ο ουκ [αποκαλυφθησεται]{.greek-omitted} [απολυφθησεται]{.greek-added} και κρυπτον ο [ου]{.greek-omitted} [ουχ]{.greek-added} γνωσθησεται[10:26]{.aside}

ο λεγω υμιν εν τη σκοτια ειπατε εν τω φωτι και ο εις το ους [ακουετε]{.greek-omitted} [ηκουσατε]{.greek-added} κηρυξατε επι των δωματων[10:27]{.aside}

και μη [φοβεισθε]{.greek-omitted} [φοβηθητε]{.greek-added} απο των [αποκτενοντων]{.greek-omitted} [αποκτεινοντων]{.greek-added} το σωμα την δε ψυχην μη δυναμενων αποκτειναι φοβηθητε δε μαλλον τον δυναμενον και [την]{.greek-omitted} ψυχην και [το]{.greek-omitted} σωμα απολεσαι εν [τη]{.greek-added} γεεννη[10:28]{.aside}

ουχι δυο στρουθια ασσαριου [πωλειται]{.greek-omitted} [πωλουνται]{.greek-added} και εν εξ αυτων ου [πεσειται]{.greek-omitted} [πεσουνται]{.greek-added} επι την γην ανευ του [πατρος]{.greek-abbr} υμων[10:29]{.aside}

υμων δε και αι τριχες της κεφαλης πασαι ηριθμημεναι [εισιν]{.greek-omitted} [εισι]{.greek-added}[10:30]{.aside}

μη ουν φοβηθητε πολλων στρουθιων διαφερετε υμεις[10:31]{.aside}

πας ουν οστις ομολογησει εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:32]{.aside}

οστις δ αν αρνησηται με εμπροσθεν των [ανθρωπων]{.greek-abbr} αρνησομαι αυτον καγω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:33]{.aside}

μη νομισητε οτι ηλθον βαλειν ειρηνην [επι]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [ουκ]{.greek-omitted} [ηλθον]{.greek-omitted} [βαλειν]{.greek-omitted} [ειρηνην]{.greek-omitted} αλλα μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και θυγατερα κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και εχθροι του [ανθρωπου]{.greek-abbr} οι οικειακοι αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος και ο φιλων υιον η θυγατερα υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:37]{.aside}

[και]{.greek-omitted} ος [γαρ]{.greek-added} [φησιν]{.greek-added} ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει [μοι]{.greek-added} [οπισω]{.greek-omitted} [μου]{.greek-omitted} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας [την]{.unclear} ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομ[ενος]{.unclear} δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφ[ητην]{.unclear} εις ονομα προφητου μισθον προφητου ληψεται και [ο]{.unclear} [δε]{.unclear}χομενο[ς]{.unclear} [δι]{.unclear}καιον εις ονομα δικαιου μισθ[ον]{.unclear} δικαιου [ληψετ]{.unclear}αι[10:41]{.aside}

και ος εαν ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις [πολεσιν]{.greek-omitted} [[σ]{.unclear}υναγωγαις]{.greek-added} αυτων[11:1]{.aside}

ο δε [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ακουσας εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-abbr} πεμψας [δυο]{.greek-omitted} [δια]{.greek-added} των μαθητων αυτου[11:2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτω]{.greek-omitted} συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

[και]{.greek-omitted} αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε [ιωαννη]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} α ακουετε και βλεπ[ε]{.unclear}τε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται και κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος [εστιν]{.greek-omitted} ος ε[αν]{.unclear} [μη]{.unclear} σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο [ο]{.greek-omitted} [ιησους]{.greek-omitted} λεγειν τοις οχλοις περι [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τι εξηλθετε εις την ερημον [θεασασθαι]{.greek-omitted} [ιδειν]{.greek-added} καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι εξηλθετε ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσ[μ]{.unclear}ενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι εξηλθετε ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω [αποστελλω]{.greek-omitted} [αποστελω]{.greek-added} τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου [εμπροσθεν]{.greek-omitted} [εμπροσθε]{.greek-added} σου[11:10]{.aside}

αμην λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων μειζων [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

[παντες]{.corr} [γαρ]{.corr} [οι]{.corr} [προφηται]{.corr} [και]{.corr} [ο]{.corr} [νομος]{.corr} [εως]{.corr} [ιωαννου]{.corr} [προεφητευσαν]{.corr}[11:13]{.aside}

και ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις εν [αγοραις]{.greek-omitted} [αγορα]{.greek-added} [καθημενοις]{.greek-omitted} [καθεζομενοις]{.greek-added} και [προσφωνουσιν]{.greek-omitted} [προσφωνουσι]{.greek-added} τοις [εταιροις]{.greek-omitted} [ετεροις]{.greek-added} αυτων[11:16]{.aside}

και λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ ωρχησασθε εθρηνησαμεν υμιν και ουκ εκοψασθε[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης [φιλος]{.greek-added} τελωνων [φιλος]{.greek-omitted} και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο ονειδιζειν τας πολεις εν αις [εγενοντο]{.greek-omitted} [εγινοντο]{.greek-added} αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι χοραζιν ουαι σοι βηθσαιδα οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι αν εν σακκω και σποδω μετενοησαν[11:21]{.aside}

πλην λεγω υμιν [τυρω]{.greek-omitted} [και]{.greek-omitted} [σιδωνι]{.greek-omitted} ανεκτοτερον εσται εν ημερα κρισεως [εκεινοις]{.greek-added} η υμιν[11:22]{.aside}

και συ καπερναουμ [η]{.greek-omitted} εως [του]{.greek-omitted} [ουρανου]{.greek-abbr} [υψωθεισα]{.greek-omitted} [υψωθης]{.greek-added} εως αδου [καταβιβασθηση]{.greek-omitted} [καταβληθηση]{.greek-added} οτι ει εν σοδομοις εγενοντο αι δυναμεις αι γενομεναι εν σοι εμειναν αν μεχρι της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι γη σοδομων ανεκτοτερον εσται εν ημερα κρισεως [η]{.greek-omitted} [σοι]{.greek-omitted}[11:24]{.aside}

εν εκεινω τω καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι παρεδοθη υπο του [πατρος]{.greek-abbr} μου και ουδεις [επιγινωσκει]{.greek-omitted} [γινωσκει]{.greek-added} τον υιον ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο υιος και ω εαν [βου]{.greek-added} [βουληται]{.greek-omitted} [ληται]{.greek-added} ο υιος αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι [κοπιωντες]{.greek-omitted} [κοποιωντες]{.greek-added} και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και ευρησετε αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου χρηστος και το φορτιον μου ελαφρον [εστιν]{.greek-omitted}[11:30]{.aside}

### Chapter 12

εν εκεινω τω καιρω [επορευθη]{.greek-omitted} [επορευετο]{.greek-added} ο [ιησους]{.greek-abbr} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων οι δε μαθηται αυτου επεινασαν και ηρξαντο τιλλειν [τους]{.greek-added} σταχυας και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντες ειπον αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ποιειν εν σαββατω[12:2]{.aside}

ο δε [αποκριθεις]{.greek-added} ειπεν αυτοις ουκ ανεγνωτε [τι]{.greek-omitted} [ο]{.greek-added} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε επεινασεν αυτος και οι μετ αυτου[12:3]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως εφαγεν ους ουκ [εξον]{.greek-omitted} [εξην]{.greek-added} [ην]{.greek-omitted} αυτω φαγειν ουδε τοις μετ αυτου [ει]{.greek-omitted} [μη]{.greek-omitted} [αλλα]{.greek-added} [μονοις]{.greek-added} τοις ιερευσιν [μονοις]{.greek-omitted}[12:4]{.aside}

η ουκ ανεγνωτε εν τω νομω οτι τοις σαββασιν οι ιερεις εν τω [ιερω]{.greek-omitted} [νομω]{.greek-added} το σαββατον [βεβηλουσιν]{.greek-omitted} [βεβηλουσι]{.greek-added} και αναιτιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[12:5]{.aside}

λεγω δε υμιν οτι του ιερου μειζον εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε τι εστιν [ελεον]{.greek-omitted} [ελαιον]{.greek-added} θελω και ου θυσιαν ουκ αν κατεδικασατε τους αναιτιους[12:7]{.aside}

κυριος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} του σαββατου ο υιος του [ανθρωπου]{.greek-abbr}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} ην την χειρα εχων ξηραν και επηρωτησαν αυτον λεγοντες ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις [εσται]{.greek-omitted} εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει αυτο και εγερει[12:11]{.aside}

ποσω ουν διαφερει [ανθρωπος]{.greek-abbr} προβατου ωστε [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} [καλως]{.greek-omitted} [ποιειν]{.greek-omitted} [καλοποιειν]{.greek-added}[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [και]{.greek-omitted} αποκατεσταθη υγιης ως η αλλη[12:13]{.aside}

οι δε φαρισαιοι συμβουλιον ελαβον κατ αυτου εξελθοντες οπως αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και επετιμησεν αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[12:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον [ηρετισα]{.greek-omitted} [ηρετισαμην]{.greek-added} ο αγαπητος μου εις ον ευδοκησεν η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει [ουδε]{.greek-omitted} [ακουσει]{.greek-omitted} [τις]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [πλατειαις]{.greek-omitted} [την]{.greek-omitted} [φωνην]{.greek-omitted} [αυτου]{.greek-omitted}[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον τυφομενον ου σβεσει εως [αν]{.greek-omitted} [ου]{.greek-added} εκβαλη εις νικος την κρισιν[12:20]{.aside}

και [εν]{.greek-added} τω ονοματι αυτου εθνη ελπιουσιν[12:21]{.aside}

τοτε προσηνεχθη αυτω δαιμονιζομενος τυφλος και κωφος και εθεραπευσεν αυτον ωστε τον τυφλον και κωφον και [[β]{.unclear}λεπειν]{.greek-added} [και]{.greek-added} λαλειν [και]{.greek-omitted} [βλεπειν]{.greek-omitted}[12:22]{.aside}

και [ε]{.greek-added} [εξισταντο]{.greek-omitted} [ξισταντο]{.greek-added} παντες οι οχλοι [λεγοντες]{.greek-added} [και]{.greek-omitted} [ελεγον]{.greek-omitted} μητι ουτος εστιν ο υιος [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες ειπον ουτος ουκ εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

ειδως δε ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν αυτοις πασα βασιλεια μερισθεισα καθ εαυτης ερημουται και πασα πολις η οικια μερισθεισα καθ [εαυτ[ο]{.unclear}ς]{.greek-added} [εαυτης]{.corr} ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν εκβαλλει εφ εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

και ει εγω εν [τω]{.greek-added} βεελζεβουλ εκβαλλω τα δαιμονια οι υιοι υμων εν τινι εκβαλλουσι[ν]{.unclear} δια τουτο αυτοι υμων εσονται κριται[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} [εγω]{.greek-omitted} εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

η πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου διαρπασαι [εαν]{.greek-omitted} [ει]{.greek-added} μη [πρωτον]{.greek-omitted} [δηση]{.greek-omitted} [προτερον]{.greek-added} [δησει]{.greek-added} τον ισχυρον και τοτε την οικιαν αυτου διαρπασει[12:29]{.aside}

ο μη ων μετ εμου κατ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

δια τουτο λεγω υμιν πασα αμαρτια και βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} [η]{.greek-omitted} [δε]{.greek-omitted} [του]{.greek-omitted} [πνευματος]{.greek-omitted} [βλασφημια]{.greek-omitted} [ουκ]{.greek-omitted} [αφεθησεται]{.greek-omitted} [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted}[12:31]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} [ειπη]{.greek-omitted} [ειποι]{.greek-added} λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω ος δ αν [ειπη]{.greek-omitted} [ειποι]{.greek-added} κατα του [πνευματος]{.greek-abbr} του αγιου ουκ αφεθησεται αυτω ουτε εν τω νυν αιωνι ουτε εν τω μελλοντι[12:32]{.aside}

η ποιησατε το δενδρον καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον [γινωσκεται]{.greek-omitted} [γνωριζεται]{.greek-added}[12:33]{.aside}

γεννηματα εχιδνων πως δυνασθε αγαθα λαλειν πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου εκβαλλει αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου εκβαλλει πονηρα[12:35]{.aside}

λεγω δε υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσουσι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων σου δικαιωθηση και εκ των λογων σου [καταδικασθηση]{.greek-omitted} [κατακριθηση]{.greek-added}[12:37]{.aside}

τοτε απεκριθησαν τινες των γραμματεων και φαρισαιων λεγοντες διδασκαλε θελομεν απο σου σημειον ιδειν[12:38]{.aside}

[αποκριθεις]{.greek-added} [δε]{.greek-added} ο [[ιησους]{.greek-abbr}]{.greek-added} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} ειπεν αυτοις γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ γαρ ην ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας ουτως εσται [και]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} εν τη [καρδια]{.greek-omitted} [κοιλια]{.greek-added} της γης τρεις ημερας και τρεις νυκτας[12:40]{.aside}

ανδρες νινευιται αναστησονται εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

βασιλισσα νοτου εγερθησεται εν τη κρισει μετα της γενεας ταυτης και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν σολομωνος και ιδου πλειον σολομωνος ωδε[12:42]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητουν αναπαυσιν και ουχ ευρισκει[12:43]{.aside}

τοτε λεγει επιστρεψω εις τον οικον μου οθεν εξηλθον και ελθον ευρισκει σχολαζοντα [και]{.greek-added} σεσαρωμενον [και]{.greek-omitted} [κεκοσμημενον]{.greek-omitted}[12:44]{.aside}

τοτε πορευεται και [παραλαμβανει]{.greek-omitted} [λαμβανει]{.greek-added} μεθ εαυτου επτα ετερα [πνευματα]{.greek-abbr} πονηροτερα εαυτου και εισελθοντα κατοικει εκει και γινεται τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου χειρονα των πρωτων ουτως εσται και τη γενεα ταυτη τη πονηρα[12:45]{.aside}

ετι δε αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και οι αδελφοι αυτου ειστηκεισαν εξω ζητουντες αυτω λαλησαι[12:46]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εξω [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} ζητουντες σοι λαλησαι[12:47]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω ειποντι αυτω τις εστιν η [μητηρ]{.greek-abbr} μου και τινες εισιν οι αδελφοι μου[12:48]{.aside}

και εκτεινας την χειρα αυτου επι τους μαθητας αυτου ειπεν ιδου η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[12:49]{.aside}

οστις γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr} αυτος μου αδελφος και αδελφη και [μητηρ]{.greek-abbr} εστιν[12:50]{.aside}

### Chapter 13

εν [δε]{.greek-omitted} τη ημερα εκεινη εξελθων ο [ιησους]{.greek-abbr} απο της οικιας εκαθητο παρα την θαλασσαν[13:1]{.aside}

και συνηχθησαν προς αυτον οχλοι πολλοι ωστε αυτον [εμβαντα]{.greek-added} εις το πλοιον [εμβαντα]{.greek-omitted} [καθησθαι]{.greek-omitted} [καθισαι]{.greek-added} και πας ο οχλος επι τον αιγιαλον ειστηκει[13:2]{.aside}

και ελαλησεν αυτοις πολλα εν παραβολαις [λεγων]{.greek-omitted} [ιδου]{.greek-omitted} εξηλθεν ο σπειρων του [σπειρειν]{.greek-omitted} [σπειραι]{.greek-added} [τον]{.greek-added} [σπορον]{.greek-added} [αυτου]{.greek-added}[13:3]{.aside}

και εν τω σπειρειν αυτον [α]{.greek-omitted} [ο]{.greek-added} μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα π[ε]{.unclear}τεινα και κατεφαγεν αυτα[13:4]{.aside}

αλλα δε επεσεν επι τα πετρωδη οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[13:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[13:6]{.aside}

αλλα δε επεσεν επι τας ακανθας και ανεβησαν αι ακανθαι και απεπνιξαν αυτα[13:7]{.aside}

αλλα δε επεσεν επι την γην την καλην και εδιδου καρπον ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:8]{.aside}

ο εχων ωτα ακουειν ακουετω[13:9]{.aside}

και προσελθοντες οι μαθηται ειπον αυτω δια τι εν παραβολαις [λαλεις]{.greek-omitted} [λεγεις]{.greek-added} αυτοις[13:10]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι υμιν δεδοται γνωναι τα μυστηρια της βασιλειας των [ουρανων]{.greek-abbr} εκεινοις δε ου δεδοται[13:11]{.aside}

οστις γαρ εχει δοθησεται αυτω και περισσευθησεται οστις δε ουκ εχει και ο εχει αρθησεται απ αυτου[13:12]{.aside}

δια τουτο εν παραβολαις αυτοις λαλω οτι βλεποντες ου [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και ακουοντες ουκ ακουουσιν ουδε συνιουσιν[13:13]{.aside}

και [αναπληρουται]{.greek-omitted} [πληρουται]{.greek-added} [επ]{.greek-added} αυτοις η προφητεια [ησαιου]{.greek-omitted} η λεγουσα [ησαιου]{.greek-added} ακοη ακουσετε και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεπετε]{.greek-added} και ου μη ιδητε[13:14]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και [τους]{.greek-omitted} [τοις]{.greek-added} [οφθαλμους]{.greek-omitted} [οφθαλμοις]{.greek-added} αυτων [εκαμμυσαν]{.greek-omitted} [εκαμυσαν]{.greek-added} μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και [ιασομαι]{.greek-omitted} [ιασωμαι]{.greek-added} αυτους[13:15]{.aside}

υμων δε μακαριοι οι οφθαλμοι οτι [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και τα ωτα υμων οτι ακουει[13:16]{.aside}

αμην [γαρ]{.greek-omitted} [αμην]{.greek-added} λεγω υμιν οτι πολλοι προφηται και δικαιοι επεθυμησαν ιδειν α βλεπετε και ουκ ειδον και ακουσαι α [ακουετε]{.greek-omitted} [ηκουσατε]{.greek-added} και ουκ ηκουσαν[13:17]{.aside}

υμεις ουν ακουσατε την παραβολην του σπειροντος[13:18]{.aside}

παντος ακουοντος τον λογον της βασιλειας και μη συνιεντος ερχεται ο πονηρος και αρπαζει το εσπαρμενον εν τη καρδια αυτου ουτος εστιν ο παρα την οδον σπαρεις[13:19]{.aside}

ο δε επι τα πετρωδη σπαρεις ουτος εστιν ο τον λογον ακουων και ευθυς μετα χαρας λαμβανων αυτον[13:20]{.aside}

ουκ εχει δε ριζαν εν εαυτω αλλα προσκαιρος [εστιν]{.greek-omitted} [εστι]{.greek-added} γενομενης δε θλιψεως η διωγμου δια τον λογον ευθυς σκανδαλιζεται[13:21]{.aside}

ο δε εις τας ακανθας σπαρεις ουτος εστιν ο τον λογον ακουων και η μεριμνα του αιωνος τουτου και η απατη του πλουτου συμπνιγει τον λογον και ακαρπος γινεται[13:22]{.aside}

ο δε επι την γην την καλην σπαρεις ουτος εστιν ο τον λογον ακουων και [συνιων]{.greek-omitted} [φυλαττων]{.greek-added} [ωτ[α]{.unclear}]{.greek-added} [δια]{.greek-added} [αυτα]{.greek-added} ος δη καρποφορει και ποιει ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:23]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} [τω]{.greek-added} [σπειροντι]{.greek-omitted} [σπειραντι]{.greek-added} καλον σπερμα εν τω αγρω αυτου[13:24]{.aside}

εν δε τω καθευδειν τους [ανθρωπους]{.greek-abbr} ηλθεν [αυτου]{.greek-omitted} ο εχθρος [αυτου]{.greek-added} και [εσπειρεν]{.greek-omitted} [εσπειρε]{.greek-added} ζιζανια ανα μεσον του σιτου και απηλθεν[13:25]{.aside}

οτε δε εβλαστησεν ο χορτος και καρπον [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοτε εφανη και τα ζιζανια[13:26]{.aside}

προσελθοντε[ς]{.unclear} δε οι δουλοι του οικοδεσποτου ειπον αυτω [κυριε]{.greek-abbr} ουχι καλον [σ]{.unclear}περμα εσπειρας εν τω [σω]{.greek-omitted} αγρω ποθεν ουν εχει ζιζανια[13:27]{.aside}

ο δε εφη [αυτοις]{.greek-omitted} εχθρος [ανθρωπος]{.greek-abbr} τουτο εποιησεν οι δε δουλοι ειπον αυτω θελεις ουν απελθοντες συλλεξομεν αυτα[13:28]{.aside}

ο δε εφη ου μηποτε συλλεγοντες τα ζιζανια εκριζωσητε αμα αυτοις τον σιτον[13:29]{.aside}

αφετε [συναυξανεσθαι]{.greek-omitted} [συναυξεσθαι]{.greek-added} αμφοτερα μεχρι του θερισμου και εν καιρω του θερισμου ερω τοις θερισταις συλλεξατε πρωτον τα ζιζανια και δησατε αυτα εις δεσμας προς το κατακαυσαι αυτα τον δε σιτον συναγαγετε εις την αποθηκην [μου]{.greek-omitted}[13:30]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} κοκκω σιναπεως ον λαβων [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο μικροτερον μεν [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των σπερματων οταν δε αυξηθη μειζον των λαχανων εστιν και γινεται δενδρον ωστε ελθειν τα πετεινα του [ουρανου]{.greek-abbr} και κατασκηνουν εν τοις κλαδοις αυτου[13:32]{.aside}

αλλην παραβολην [ελαλησεν]{.greek-omitted} [παρεθηκεν]{.greek-added} αυτοις [ομοια]{.greek-omitted} [εστιν]{.greek-omitted} [λεγων]{.greek-added} [ωμοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} ζυμη ην λαβουσα γυνη εκρυψεν εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33]{.aside}

ταυτα παντα ελαλησεν ο [ιησους]{.greek-abbr} εν παραβολαις τοις οχλοις και χωρις παραβολης ουκ ελαλει αυτοις[13:34]{.aside}

οπως πληρωθη το ρηθεν δια του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου ερευξομαι κεκρυμμενα απο καταβολης κοσμου[13:35]{.aside}

τοτε αφεις τους οχλους ηλθεν εις την οικιαν ο [ιησους]{.greek-abbr} και προσηλθον αυτω οι μαθηται αυτου λεγοντες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις ο σπειρων το καλον σπερμα εστιν ο υιος του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του πονηρου[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστιν οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν συλλεγεται τα ζιζανια και πυρι καιεται ουτως εσται εν τη συντελεια του αιωνος τουτου[13:40]{.aside}

αποστελει ο υιος του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν τω αγρω ον ευρων [ανθρωπος]{.greek-abbr} [εκρυψεν]{.greek-omitted} [εκρυψε]{.greek-added} και απο της χαρας αυτου υπαγει και παντα οσα εχει πωλει και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

ος [ευ]{.unclear}ρων ενα πολυτιμον μαργαριτην απελθων [πεπρακεν]{.greek-omitted} [πεπρακε]{.greek-added} παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη βληθειση εις την θαλασσαν και εκ παντος γενους [συναγαγουση]{.greek-omitted} [συναγουση]{.greek-added}[13:47]{.aside}

ην οτε επληρωθη αναβιβασαντες [αυτην]{.greek-added} επι τον αιγιαλον και καθισαντες συνελεξαν τα καλα εις αγγεια τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται εν τη [συντελεια]{.greek-omitted} [βασιλεια]{.greek-added} του αιωνος εξελευσονται οι αγγελοι και [αφοριουσιν]{.greek-omitted} [αφοριουσι]{.greek-added} τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:50]{.aside}

λ[εγει]{.greek-supplied} αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα λεγουσιν α[υτω]{.greek-supplied} ναι [κυριε]{.greek-abbr}[13:51]{.aside}

ο δε ειπεν αυτοις δια τουτο πας γραμμα[τευ]{.greek-supplied}ς μαθητευθεις εις την βασιλειαν των ουραν[ων]{.unclear} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη [οστις]{.greek-omitted} [ος]{.greek-added} εκβαλλει εκ του θησαυρου αυτου καινα και παλαια[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας [μετηρεν]{.greek-omitted} [μετεβη]{.greek-added} εκειθεν[13:53]{.aside}

και ελθων εις την [πατριδα]{.greek-abbr} αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων ωστε εκπληττεσθαι αυτους και λεγειν ποθεν τουτω η σοφια αυτη και αι δυναμεις[13:54]{.aside}

ουχ ουτος εστιν ο του τεκτονος υιος ουχι η [μητηρ]{.greek-abbr} αυτου λεγεται μαριαμ και οι αδελφοι αυτου ιακωβος και ιωσης και σιμων και ιουδας[13:55]{.aside}

και αι αδελφαι αυτου ουχι πασαι προς ημας [εισιν]{.greek-omitted} [εισι]{.greek-added} ποθεν ουν τουτω ταυτα παντα[13:56]{.aside}

και εσκανδαλιζοντο εν αυτω ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [ιδια]{.greek-added} [πατριδι]{.greek-abbr} αυτου [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [αυτου]{.greek-omitted}[13:57]{.aside}

και ουκ εποιησεν εκει δυναμεις πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο τετραρχης την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις παισιν αυτου ουτος εστιν [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο βαπτιστης αυτος ηγερθη απο των νεκρων και δια τουτο αι δυναμεις ενεργουσιν εν αυτω[14:2]{.aside}

ο γα[ρ]{.unclear} ηρωδης κρατησας τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εδησεν αυτον και εθετο εν [τη]{.greek-added} φυλακη δια ηρωδιαδα την γυναικα φιλιππ[ο]{.unclear}υ του αδελφου αυτου[14:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων [δε]{.greek-omitted} [γαρ]{.greek-added} αγομενων του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και [ηρεσεν]{.greek-omitted} [ηρεσε]{.greek-added} τω ηρωδη[14:6]{.aside}

οθεν μεθ ορκου ωμολογησεν αυτη δουναι ο εαν αιτησηται[14:7]{.aside}

η δε προβιβασθεισα υπο της [μητρος]{.greek-abbr} αυτ[ης]{.unclear} δος μοι φησιν ωδε επι [πινακι]{.greek-omitted} [πινακος]{.greek-added} την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[14:8]{.aside}

και ελυπηθη ο βασιλευς δια δε τους ορκους και τους συνανακειμενους [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλισε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι πινακι και εδοθη τω κορασιω και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το σωμα και εθαψαν αυτο και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} ανεχωρησεν εκειθεν [εν]{.greek-omitted} [πλοιω]{.greek-omitted} εις ερημον τοπον κατ ιδιαν και ακουσαντες οι οχλοι ηκολουθησαν αυτω πεζη απο των πολεων[14:13]{.aside}

και εξελθων ο [ιησους]{.greek-abbr} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται αυτου λεγοντες ερημος εστιν ο τοπος και η ωρα ηδη παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας κωμας αγορασωσιν εαυτοις βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου χρειαν εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} φερετε [μοι]{.greek-omitted} αυτους ωδε[14:18]{.aside}

και κελευσας τους οχλους ανακλιθηναι επι τους χορτους λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και κλασας [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το [περισσευον]{.greek-omitted} [περιττευον]{.greek-added} των κλασματων δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες ωσει πεντακισχιλιοι χωρις γυναικων και παιδιων[14:21]{.aside}

και ευθεως ηναγκασεν ο [ιησους]{.greek-abbr} τους μαθητας [αυτου]{.greek-added} εμβηναι εις το [πλοιον]{.greek-omitted} [πλειον]{.greek-added} και προαγειν αυτον εις το περαν εως ου απολυση τους οχλους[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος κατ ιδιαν προσευξασθαι οψιας δε [ηδη]{.greek-added} γενομενης μονος ην εκει[14:23]{.aside}

το δε [πλοιον]{.greek-omitted} [πλειον]{.greek-added} ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος [απηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς αυτους ο [ιησους]{.greek-abbr} περιπατων επι της θαλασσης[14:25]{.aside}

και ιδοντες αυτον οι μαθηται επι την θαλασσαν περιπατουντα εταραχθησαν λεγοντες οτι φαντασμα [εστιν]{.greek-omitted} [εστι]{.greek-added} και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} [αυτοις]{.greek-added} λεγων θαρσειτε εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} ει συ ει κελευσον με προς σε ελθειν επι [τα]{.greek-omitted} [υδατα]{.greek-omitted} [του]{.greek-added} [υδατος]{.greek-added}[14:28]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν ελθε και καταβας απο του πλοιου ο πετρος [περιεπατησεν]{.greek-omitted} [επατησεν]{.greek-added} επι τα υδατα ελθειν προς τον [ιησουν]{.greek-abbr}[14:29]{.aside}

βλεπων δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα επελαβετο αυτου και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω ελθοντες προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} λεγοντες αληθως [θεου]{.greek-abbr} υιος ει[14:33]{.aside}

και διαπερασαντες ηλθον εις την [γην]{.greek-omitted} [γεννησαρετ]{.greek-omitted} [γεννησαρεθ]{.greek-added}[14:34]{.aside}

και επιγνοντες αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον αψωνται του κρασπεδου του ιματιου αυτου και οσοι ηψαντο διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτ[ε]{.unclear} προσερχονται τω [ιησου]{.greek-abbr} οι απο ιεροσολυμων γραμματεις και φαρισαιοι λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου [παραβαινουσιν]{.greek-omitted} [παραβαινουσι]{.greek-added} την παραδοσιν των [πρεσβυτερων]{.greek-omitted} [πρεσβυ]{.greek-added} [τερων]{.greek-added} ου γαρ [νιπτονται]{.greek-omitted} [νιπτουσι]{.greek-added} τας χειρας αυτων οταν [αρτον]{.greek-omitted} εσθιωσιν[15:2]{.aside}

[αποκριθεις]{.greek-added} [δε]{.greek-added} ο [[ιησους]{.greek-abbr}]{.greek-added} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} ειπεν αυτοις δια τι [και]{.greek-omitted} υμεις παραβαινετε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} ενετειλατο λεγων τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} [σου]{.greek-added} και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[15:4]{.aside}

υμεις δε λεγετε ος [αν]{.greek-omitted} [εαν]{.greek-added} ειπη τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} δωρον ο εαν εξ εμου ωφεληθης [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[και]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [τιμηση]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [η]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} και ηκυρωσατε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:6]{.aside}

υποκριται [κ]{.unclear}αλως προεφ[η]{.unclear}τευσεν [περι]{.greek-supplied} [υμ]{.greek-supplied}ων ησαιας λεγων[15:7]{.aside}

εγγιζει μοι ο λαος ου[τος]{.unclear} [τω]{.unclear} [στομα]{.greek-supplied}τι αυτων και τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδ[ια]{.unclear} [αυτων]{.unclear} πορρω απεχει απ εμου[15:8]{.aside}

ματην δε [σεβοντ]{.greek-supplied}αι με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις ακουετε και συνιετε[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} αλλα το εκπορευομενον εκ του στοματος τουτο κοινοι τον [ανθρωπον]{.greek-abbr}[15:11]{.aside}

τοτε προσελθοντες οι μαθηται αυτου ειπον αυτω οιδας οτι οι φαρισαιοι ακουσαντες τον λογον εσκανδαλισθησαν[15:12]{.aside}

ο [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [γουν]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ακουσας]{.greek-added} [οτι]{.greek-added} [εσκανδαλισθησαν]{.greek-added} [οι]{.greek-added} [φαρισαιοι]{.greek-added} [φησι]{.greek-added} πασα φυτεια ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο [ουρανιος]{.greek-abbr} εκριζωθησεται[15:13]{.aside}

αφετε αυτους οδηγοι [εισιν]{.greek-omitted} [εισι]{.greek-added} [τυφλοι]{.greek-omitted} τυφλων τυφλος δε τυφλον εαν οδηγη αμφοτεροι εις βοθυνον πεσουνται[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν ακμην και υμεις ασυνετοι εστε[15:16]{.aside}

ουπω νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ της καρδιας εξερχεται κακεινα κοινοι τον [ανθρωπον]{.greek-abbr}[15:18]{.aside}

εκ γαρ της καρδιας εξερχονται διαλογισμοι πονηροι φονοι μοιχειαι πορνειαι κλοπαι ψευδομαρτυριαι [βλασ]{.unclear}φημιαι[15:19]{.aside}

ταυτα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr} το δε ανιπτοις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} φαγειν ου κοινοι τον [ανθρωπον]{.greek-abbr}[15:20]{.aside}

και εξελθων [εκειθεν]{.greek-omitted} ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα μερη τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα εκραυγασεν αυτω λεγουσα ελεησον με [κυριε]{.greek-abbr} υιε [δαυιδ]{.greek-abbr} η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε ουκ απεκριθη αυτη λογον και [προσελθοντες]{.greek-omitted} [παρελθοντες]{.greek-added} οι μαθηται αυτου ηρωτων αυτον λεγοντες απολυσον αυτην οτι κραζει οπισθεν ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν [οτι]{.greek-added} ουκ απεσταλην ει μη εις τα προβατα τα απολωλοτα οικου ισραηλ[15:24]{.aside}

η δε [ελθουσα]{.greek-omitted} [προσελθουσα]{.greek-added} προσεκυνησεν αυτω λεγουσα [κυριε]{.greek-abbr} βοηθει μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των ψιχιων των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη ω γυναι μεγαλη σου η πιστις γενηθητω σοι ως θελεις και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος εκαθητο εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ εαυτων χωλους τυφλους κωφους κυλλους και ετερους πολλους και ερριψαν αυτους παρα τους ποδας του [ιησου]{.greek-abbr} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους λαλουντας κυλλους υγιεις χωλους περιπατουντας και [δοξαζειν]{.greek-added} [τυφλους]{.greek-omitted} [βλεποντας]{.greek-omitted} [και]{.greek-omitted} [εδοξασαν]{.greek-omitted} τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} προσκαλεσαμενος τους μαθητας αυτου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} σπλαγχνιζομαι επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} και απολυσαι αυτο[υς]{.unclear} [νηστεις]{.greek-omitted} [[ν]{.unclear}ηστις]{.greek-added} ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32]{.aside}

[και]{.greek-omitted} λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια αρτοι τοσουτοι ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

[και]{.greek-omitted} λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} [οχλοις]{.greek-omitted} [οχλους]{.greek-added} αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους [επτα]{.greek-omitted} αρτους και τους ιχθυας ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις [αυτου]{.greek-omitted} οι δε μαθηται τω οχλω[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας πληρεις[15:37]{.aside}

οι δε εσθιοντες ησαν [ανδρες]{.greek-added} τετρακισχιλιοι [ανδρες]{.greek-omitted} χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους ενεβη εις το πλοιον και ηλθεν εις τα ορια μαγδαλα[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε [ευδια]{.greek-omitted} [ευδεια]{.greek-added} πυρραζει γαρ ο [ουρανος]{.greek-abbr}[16:2]{.aside}

και πρωι σημερον χειμων πυρραζει γαρ στυγναζων ο [ουρανος]{.greek-abbr} υποκριται το μεν προσωπον του [ουρανου]{.greek-abbr} γινωσκετε διακρινειν τα δε σημεια των καιρων ου [δυνασθε]{.greek-omitted} [συνιεται]{.greek-added}[16:3]{.aside}

γενεα πονηρα και μοιχαλις σημειον [επιζητει]{.greek-omitted} [αιτει]{.greek-added} και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου και καταλιπων αυτους απηλθεν[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν επελαθοντο αρτους λαβειν[16:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ορατε και προσεχετε απο της ζυμης των φαρισαιων και σαδδουκαιων[16:6]{.aside}

οι δε διελογιζοντο εν εαυτοις [λεγοντες]{.greek-omitted} οτι αρτους ουκ ελαβομεν[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι διαλογιζεσθε εν εαυτοις ολιγοπιστοι οτι αρτους ουκ ελαβετε[16:8]{.aside}

ουπω νοειτε ουδε μνημονευετε τους πεντε αρτους των πεντακισχιλιων και ποσους κοφινους ελαβετε[16:9]{.aside}

ουδε τους επτα αρτους των τετρακισχιλιων και ποσας σπυριδας ελαβετε[16:10]{.aside}

πως ου νοειτε οτι ου περι [αρτου]{.greek-omitted} [αρτων]{.greek-added} ειπον υμιν προσεχειν [αλλ]{.greek-added} απο της ζυμης των φαρισαιων και σαδδουκαιων[16:11]{.aside}

τοτε συνηκαν οτι ουκ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προσεχειν απο της ζυμης του αρτου [αλλα]{.greek-omitted} [αλλ]{.greek-added} απο της διδαχης των φαρισαιων και σαδδουκαιων[16:12]{.aside}

ελθων δε ο [ιησους]{.greek-abbr} εις τα μερη καισαρειας της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι τον υιον του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον [οι]{.greek-omitted} [ο]{.greek-added} μεν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λ[εγ]{.unclear}ει αυτοις υμεις [δε]{.greek-omitted} τιν[α]{.unclear} με λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτω]{.greek-omitted} μακαριος ει σιμων βαριωνα οτι σαρξ και αιμα ουκ [απεκαλυψεν]{.greek-omitted} [απεκαλυψε]{.greek-added} σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις [ουρανοις]{.greek-abbr}[16:17]{.aside}

[κα]{.unclear}γω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλ[αι]{.unclear} [αδου]{.unclear} ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν τοις ουρανοις και ο εαν λυσης επι της γης εσ[τ]{.unclear}αι λελυμενον εν τοις [ουρανοις]{.greek-abbr}[16:19]{.aside}

τοτε διεστειλατο τοις μαθηταις αυτου ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} δεικνυειν τοις μαθηταις αυτου οτι δει αυτον απελθειν εις ιεροσολυμα και πολλα παθειν απο των πρεσβυτερων και αρχιερεων και γραμματεων και αποκτανθηναι και τη τριτη ημερα εγερθηναι[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω λεγων ιλεως σοι [κυριε]{.greek-abbr} ου μη εσται σοι τουτο[16:22]{.aside}

[ο]{.greek-omitted} [στραφεις]{.greek-added} δε [στραφεις]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω πετρω υπαγε οπισω μου σατανα σκανδαλον μου ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ει τις θελει οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[16:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την ψυχην αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι γαρ ωφελειται [ανθρωπος]{.greek-abbr} εαν τον κοσμον ολον κερδηση την δε ψυχην αυτου ζημιωθη η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο υιος του [ανθρωπου]{.greek-abbr} ερχεσθαι εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων αυτου και τοτε αποδωσει εκαστω κατα [την]{.greek-omitted} [πραξιν]{.greek-omitted} [τα]{.greek-added} [εργα]{.greek-added} αυτου[16:27]{.aside}

αμην λεγω υμιν [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες [των]{.greek-added} ωδε [εστωτες]{.greek-omitted} [εστωτων]{.greek-added} οιτινες ου μη [γευσονται]{.greek-added} [γευσωνται]{.corr} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αναφερει αυτους εις ορος υψηλον κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και [ελαμψεν]{.greek-omitted} [ελαμψε]{.greek-added} το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου εγενοντο λευκα ως το φως[17:2]{.aside}

και ιδου ωφθησαν αυτοις [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

απο[κ]{.unclear}ριθεις [δ]{.unclear}ε ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω [ιησου]{.greek-abbr} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι [ει]{.greek-omitted} [θελεις]{.greek-omitted} ποιησωμεν ωδε τρεις σκηνας σοι μιαν και [μωση]{.greek-omitted} [μωσει]{.greek-added} μιαν και μιαν ηλια[17:4]{.aside}

ετι αυτου λαλουντος ιδου νεφελη φωτεινη επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω ευδοκησα αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται επεσον επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν εγερθητε και μη φοβεισθε[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινοντων αυτων εκ του ορους ενετειλατο αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι ειπητε το οραμα εως ου ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[17:9]{.aside}

και επηρωτησαν αυτον οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν δει ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις ηλιας μεν ερχεται πρωτον και αποκαταστησει παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας ηδη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ουκ επεγνωσαν αυτον αλλα εποιησαν εν αυτω οσα ηθελησαν ουτως και ο υιος του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον προσηλθεν αυτω [ανθρωπος]{.greek-abbr} γονυπετων [αυτον]{.greek-omitted} [αυτω]{.greek-added}[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι σεληνιαζεται και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και προσηνεγκα αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν αυτον θεραπευσαι[17:16]{.aside}

[αποκριθεις]{.greek-omitted} [αποκρι]{.greek-added} [θεις]{.greek-added} δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα [απιστος]{.greek-omitted} [απιστε]{.greek-added} και διεστραμμενη εως ποτε εσομαι μεθ υμων εως ποτε ανεξομαι υμων φερετε μοι αυτον ωδε[17:17]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις [αυτου]{.greek-added} απο της ωρας εκεινης[17:18]{.aside}

τοτε προσελθοντες οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτοις δια την απιστιαν υμων αμην [γαρ]{.greek-omitted} λεγω υμιν εαν εχητε πιστιν ως κοκκον σιναπεως ερειτε τω ορει τουτω μεταβηθι εντευθεν εκει και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ εκπορευεται ει μη εν προσευχη και νηστεια[17:21]{.aside}

αναστρεφομενων δε αυτων [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [γαλιλαια]{.greek-omitted} [γαλιλαιαν]{.greek-added} ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα εγερθησεται και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε αυτων εις καπερναουμ προσηλθον οι τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added} λαμβανοντες τω πετρω και ειπον ο διδασκαλος υμων ου τελει τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added}[17:24]{.aside}

λεγει ναι και οτε εισηλθεν εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο τινων [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} τελη η κηνσον απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

λεγει αυτω ο πετρος απο των αλλοτριων εφη αυτω ο ιησους αρα γε ελευθεροι εισιν [οι]{.corr} υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις την θαλασσαν βαλε αγκιστρον και τον αναβαινοντα πρωτον ιχθυν αρον και ανοιξας το στομα αυτου [ε]{.unclear}υρησεις στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ωρα προσηλθον οι μαθηται τω [ι[ς]{.unclear}]{.greek-added} [[ιησου]{.greek-abbr}]{.corr} λεγοντες τις αρα μειζων εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

[και]{.greek-omitted} [ος]{.greek-added} προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη στραφητε και γενησθε ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει [ε]{.unclear}αυτον ως το παιδιον τουτο ουτος εστιν ο μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος εαν δεξηται παιδιον τοιουτον εν επι τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν σκανδαλιση ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος εις τον τραχηλον αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} [εκεινω]{.greek-omitted} δι ου το σκανδαλον ερχεται[18:7]{.aside}

[ει]{.greek-omitted} [δε]{.greek-omitted} η χειρ σου η ο πους σου σκανδαλιζει σε εκκοψον [αυτα]{.greek-omitted} [αυτην]{.greek-added} και βαλε απο σου καλον σοι εστιν εισελθειν εις την ζωην χωλον η [κυ]{.unclear}λλον η δυο χειρας η δυο ποδας εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και ει ο οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον [εισελθειν]{.greek-added} εις την [βασιλε[ια]{.unclear}ν]{.greek-added} [ζωην]{.greek-omitted} [εισελθειν]{.greek-omitted} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

ορατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} το προσωπον του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο υιος του [ανθρωπου]{.greek-abbr} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει εαν γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα [[ϙθ]{.greek-abbr}]{.greek-added} [ενενηκοντα]{.greek-omitted} [εννεα]{.greek-omitted} επι τα ορη πορευθεις ζητει το [πλανωμενον]{.greek-omitted} [[α]{.unclear}πολλομενον]{.greek-added}[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η επι τοις [[ϙθ]{.greek-abbr}]{.greek-added} [ενενηκοντα]{.greek-omitted} [εννεα]{.greek-omitted} τοις μη πεπλανημενοις[18:13]{.aside}

ουτως ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} θελημα εμπροσθεν του [πατρος]{.greek-abbr} υμων του εν [ουρανοις]{.greek-abbr} ινα αποληται εις των μικρων τουτων[18:14]{.aside}

εαν δε [αμαρτηση]{.greek-omitted} [αμαρτη]{.greek-added} εις σε ο αδελφος σου υπαγε και ελεγξον αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη ακουση παραλαβε μετα σου ετι ενα η δυο ινα επι στοματος δυο μαρτυρων η τριων σταθη παν ρημα[18:16]{.aside}

εαν δε παρακουση αυτων ειπε τη εκκλησια εαν δε και της εκκλησιας παρακουση εστω [σοι]{.greek-omitted} ωσπερ ο εθνικος και ο τελωνης[18:17]{.aside}

παλιν αμην λεγω υμιν οτι εαν δυο υμων συμφωνησωσιν επι της γης περι παντος πραγματος ου εαν αιτησωνται [γενησεται]{.greek-omitted} [γενηται]{.greek-added} αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[18:19]{.aside}

τοτε προσελθων αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} [πο]{.greek-added} [ποσακις]{.greek-omitted} [σακις]{.greek-added} [εαν]{.greek-added} αμαρτησει εις εμε ο αδελφος μου [και]{.greek-omitted} αφησω αυτω εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} ου λεγω σοι εως επτακις αλλ εως εβδομηκοντακις επτα[18:22]{.aside}

δια τουτο ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος [ηθελησεν]{.greek-omitted} [ηθελησε]{.greek-added} συναραι λογον μετα των [δουλων]{.greek-omitted} [συνδουλων]{.greek-added} αυτου[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι [ερχε[σθ]{.unclear}αι]{.greek-added} [εκελευσεν]{.corr} [αυτον]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} μακροθυμησον επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο [κυριος]{.greek-abbr} του δουλου εκεινου απελ[υ]{.unclear}σεν [αυτον]{.greek-omitted} [αυτων]{.greek-added} και το δανειον αφηκεν αυτω[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον δηναρια και κρατησας αυτον [επνιγεν]{.greek-omitted} [επνιγε]{.greek-added} λεγων αποδος μοι ει τι οφειλεις[18:28]{.aside}

πεσων ουν ο [συνδουλος]{.greek-omitted} [δουλος]{.greek-added} αυτου εις τους ποδας [αυτου]{.greek-omitted} παρεκαλει αυτον λεγων μακροθυμησον επ εμοι και αποδωσω σοι[18:29]{.aside}

ο δε ουκ ηθελεν [αλλα]{.greek-omitted} [αλλ]{.greek-added} απελθων εβαλεν αυτον εις φυλακην εως ου αποδω το οφειλομενον[18:30]{.aside}

ιδοντες δε οι συνδουλοι [αυτου]{.greek-omitted} τα γενομενα ελυπηθησαν σφοδρα και [ελθοντες]{.greek-omitted} [εισελθοντες]{.greek-added} διεσαφησαν τω κυριω εαυτων παντα τα γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο [κυριος]{.greek-abbr} αυτου λεγει [αυτω]{.greek-omitted} δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι [επει]{.greek-omitted} [παρεκαλεσας]{.greek-omitted} [με]{.greek-omitted}[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως και εγω σε ηλεησα[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} αυτου παρεδωκεν [αυτον]{.greek-omitted} [αυτων]{.greek-added} τοις βασανισταις εως ου αποδω παν το οφειλομενον αυτω[18:34]{.aside}

ουτως [και]{.greek-omitted} ο [πατηρ]{.greek-abbr} μου ο [επουρανιος]{.greek-abbr} ποιησει υμιν εαν μη αφητε εκαστος τω αδελφω αυτου απο των καρδιων υμων τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε [ετελεσεν]{.greek-omitted} [συνετελεσεν]{.greek-added} ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα [ορια]{.greek-omitted} [ορη]{.greek-added} της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και προσηλθον αυτω οι φαρισαιοι πειραζοντες αυτον και λεγοντες αυτω ει εξεστιν [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ ανεγνωτε οτι ο ποιησας απ αρχης αρσεν και θηλυ εποιησεν αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} και την [μητερα]{.greek-abbr} και [προσκολληθησεται]{.greek-omitted} [κολληθησεται]{.greek-added} τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

[ωστε]{.greek-omitted} [ωσ]{.greek-added} [τε]{.greek-added} ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν μωσης ενετειλατο δουναι βιβλιον αποστασιου και απολυσαι αυτην[19:7]{.aside}

λεγει αυτοις οτι μωσης προς την σκληροκαρδιαν υμων επετρεψεν [υμιν]{.greek-omitted} [ημιν]{.greek-added} απολυσαι τας γυναικας υμων απ αρχης δε ου γεγονεν ουτως[19:8]{.aside}

λεγω δε υμιν οτι ος αν απολυση την γυναικα αυτου μη επι πορνεια και γαμηση αλλην μοιχαται [και]{.greek-omitted} [ο]{.greek-omitted} [απολελυμενην]{.greek-omitted} [γαμησας]{.greek-omitted} [μοιχαται]{.greek-omitted}[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτως εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφ[ερ]{.unclear}ει γαμησαι[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες [χωρουσιν]{.greek-omitted} [χωρουσι]{.greek-added} τον λογον [τουτον]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} αλλ οις δεδοται[19:11]{.aside}

εισιν [γαρ]{.greek-omitted} ευνουχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} εγεννηθησαν ουτως και εισιν ευνουχοι οιτινες ευνουχισθησαν υπο των [ανθρωπων]{.greek-abbr} και εισιν ευνουχοι οιτινες ευνουχισαν εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε προσηνεχθη αυτω [παιδια]{.greek-omitted} [παιδιον]{.greek-added} ινα τας χειρας επιθη αυτοις και προσευξηται οι δε μαθηται επετιμησαν αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε τα παιδια [και]{.greek-omitted} μη κωλυετε αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και επιθεις αυτοις τας χειρας επορευθη εκειθεν[19:15]{.aside}

και ιδου εις προσελθων ειπεν αυτω διδασκαλε αγαθε τι [ποιησω]{.greek-added} αγαθον [ποιησω]{.greek-omitted} ινα εχω ζωην αιωνιον[19:16]{.aside}

ο δε ειπεν αυτω τι με λεγεις αγαθον [ου]{.greek-added} [ουδεις]{.greek-omitted} [δεις]{.greek-added} αγαθος ει μη εις ο [θεος]{.greek-abbr} ει [δε]{.greek-omitted} θελεις εισελθειν εις την ζωην τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το ου φονευσεις ου μοιχευσεις ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} και την [μητερα]{.greek-abbr} και αγαπησεις τον πλησιον [σου]{.greek-omitted} ως σεαυτον[19:19]{.aside}

λεγει αυτω ο νεανισκος παντα ταυτα εφυλαξαμην εκ νεοτητος μου τι ετι υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελεις τελειος ειναι υπαγε πωλησον σου τα υπαρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} και δευρο ακολουθει μοι[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως πλουσιος εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν δε λεγω υμιν ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια τρυπηματος ραφιδος [διελθειν]{.greek-omitted} [εισελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[19:24]{.aside}

ακουσαντες δε οι μαθηται αυτου εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται [σω]{.greek-added} [σωθηναι]{.greek-omitted} [θηναι]{.greek-added}[19:25]{.aside}

εμβλεψας δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα δε [θεω]{.greek-abbr} παντα δυνατα[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

[αποκριθεις]{.greek-added} [δε]{.greek-added} ο [δε]{.greek-omitted} [ιησους]{.greek-abbr} ειπεν αυτοις [αμην]{.greek-added} αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν καθιση ο υιος του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου καθισεσθε και υμεις επι δωδεκα θρονους κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας [ος]{.greek-omitted} [οστις]{.greek-added} αφηκεν οικιας η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν του ονοματος μου εκατονταπλασιονα ληψεται και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[19:30]{.aside}

### Chapter 20

ομοια γαρ εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

[και]{.greek-omitted} συμφωνησας [δε]{.greek-added} μετα των εργατων εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι τριτην ωραν ειδεν αλλους εστωτας εν τη αγορα [αργους]{.greek-omitted}[20:3]{.aside}

και εκεινοις ειπεν υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν εξελθων περι εκτην [ωραν]{.greek-added} και [ενατην]{.greek-omitted} [εννατην]{.greek-added} [ωραν]{.greek-omitted} εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις [ημας]{.greek-omitted} [υμας]{.greek-added} εμισθωσατο λεγει αυτοις υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον ληψεσθε[20:7]{.aside}

οψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε [και]{.greek-added} οι πρωτοι ενομισαν οτι πλειονα ληψονται και ελαβον και αυτοι ανα δηναριον[20:10]{.aside}

λαβοντες δε εγογγυζον κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι ουτοι οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις [βαστασασιν]{.greek-omitted} [βαστασασι]{.greek-added} το βαρος [της]{.greek-omitted} [ημερας]{.greek-omitted} και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων εταιρε ουκ αδικω σε ουχι δηναριου συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω εσχατω δουναι ως και σοι[20:14]{.aside}

η ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι ποιησαι ο θελω εν τοις εμοις ει ο οφθαλμος σου πονηρος εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι και οι πρωτοι εσχατοι πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

τοτε προσηλθεν [αυτω]{.greek-omitted} η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτη τι θελεις λεγει αυτω ειπε ινα καθισωσιν ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω μελλω πινειν [η]{.greek-omitted} [και]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

### Chapter 21

λεγει αυτοις ο [ιησους]{.greek-abbr} [ουδεποτε]{.greek-omitted} [ουκ]{.greek-added} ανεγνωτε εν ταις γραφαις λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν [οτι]{.greek-omitted} αρθησεται αφ [[η]{.unclear}μων]{.greek-added} [υμων]{.corr} η βασιλεια του [θεου]{.greek-abbr} και δοθησεται εθνει ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση λικμησει αυτον[21:44]{.aside}

[και]{.greek-omitted} ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους επειδη ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} ειπεν αυτοις εν παραβολαις λεγων[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} [βα]{.greek-added} [βασιλει]{.greek-omitted} [σιλει]{.greek-added} οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω αυτου[22:2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου καλεσαι τους κεκλημενους εις [τους]{.greek-omitted} [γαμους]{.greek-omitted} [τον]{.greek-added} [γαμον]{.greek-added} και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα [σιτιστα]{.greek-omitted} [σιτευτα]{.greek-added} τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου [υβρισαν]{.greek-omitted} [ηβρισαν]{.greek-added} και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος ωργισθη και πεμψας τα στρατευματα αυτου [απωλεσεν]{.greek-omitted} [απωλεσε]{.greek-added} τους φονεις εκεινους και την πολιν αυτων ενεπρησεν[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας διεξοδους των οδων και οσους αν ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον [παντας]{.greek-omitted} οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου [χειρας]{.greek-added} [και]{.greek-added} ποδας [και]{.greek-omitted} [χειρας]{.greek-omitted} αρατε αυτον και [εκβαλετε]{.greek-omitted} [[β]{.unclear}αλεται]{.greek-added} εις το [σκοτος]{.greek-omitted} [πυρ]{.greek-added} το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον ελαβον οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι αληθης ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι κηνσον καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του κηνσου οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις αποδοτε [ουν]{.greek-omitted} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι [οι]{.greek-omitted} λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ειπεν εαν τις αποθανη μη εχων τεκνα επιγαμβρευσει ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ [ημιν]{.greek-omitted} [ημων]{.greek-added} επτα αδελφοι και ο πρωτος γαμησας [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και μη εχων σπερμα [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτοις]{.greek-omitted} πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε εκγαμιζονται αλλ ως αγγελοι του [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω [ειμι]{.greek-omitted} ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και [ακουσαντες]{.greek-omitted} [ακουοντες]{.greek-added} οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφιμωσε]{.greek-added} τους σαδδουκαιους συνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη καρδια σου και εν ολη ψυχη σου και εν [ο]{.greek-added} [ολη]{.greek-omitted} [λη]{.greek-added} τη διανοια σου[22:37]{.aside}

αυτη [εστιν]{.greek-omitted} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὐτῆ]{.greek-added} αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σο[υ]{.unclear}[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} καλει αυτον [κυριον]{.greek-abbr} πως υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added}[22:45]{.aside}

και ουδεις εδυνατο αυτω αποκριθηναι λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της [μωσεως]{.greek-omitted} [μωυσεος]{.greek-added} καθεδρας εκαθισαν οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα [εαν]{.greek-omitted} [αν]{.greek-added} ειπωσιν υμιν τηρειν τηρειτε και ποιειτε κατα δε τα εργα αυτων μη ποιειτε [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και [ου]{.greek-omitted} [ουκ]{.greek-added} ποιουσιν[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} γαρ φορτια [βαρε]{.greek-added} [βαρεα]{.corr} και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} δε τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [διλουσι]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} την πρωτοκλισιαν εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι ραββι[23:7]{.aside}

υμεις δε μη κληθητε ραββι εις γαρ εστιν υμων ο καθηγητης [ο]{.greek-omitted} [χριστος]{.greek-omitted} [παντες]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [αδελφοι]{.greek-omitted} [εστε]{.greek-omitted}[23:8]{.aside}

[μηδε]{.greek-omitted} [κληθητε]{.greek-omitted} [καθηγηται]{.greek-omitted} [εις]{.greek-omitted} [γαρ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [καθηγητης]{.greek-omitted} ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων εσται υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [[η]{.unclear}μιν]{.greek-added} [υμιν]{.corr} γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικ[ε]{.unclear}ιας]{.greek-added} [[οικιας]{.corr}]{.greek-added} των [χειρων]{.greek-added} [[χηρων]{.corr}]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [περιαγετε]{.greek-omitted} [περιαγεται]{.greek-added} την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν γενηται ποιειτε αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος [αν]{.greek-omitted} [εαν]{.greek-added} ομοση εν τω ναω ουδεν εστιν ος δ αν ομοση εν τω χρυσω του ναου οφειλει[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο [ναος]{.greek-omitted} [ο]{.greek-omitted} αγιαζων τον χρυσον[23:17]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} ομοση εν τω θυσιαστηριω [ουδεν]{.greek-added} [εστιν]{.greek-added} [ος]{.greek-added} [δ]{.greek-added} [αν]{.greek-added} [ομοση]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [ναω]{.greek-added} ουδεν εστιν ος δ αν ομοση εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι τι γαρ μειζον το δωρον η το [θυσιαστηριον]{.greek-omitted} [το]{.greek-omitted} αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο [ομοσας]{.greek-omitted} [ομνυων]{.greek-added} εν τω ναω ομνυει εν αυτω και εν τω [κατοικησαντι]{.greek-omitted} [κατοικουντι]{.greek-added} αυτον[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το κυμινον και αφηκατε τα βαρυτερα του [νο]{.greek-added} [νομου]{.greek-omitted} [μου]{.greek-added} την κρισιν και τον ελεον και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι καθαριζετε το [εξωθεν]{.greek-omitted} [εξω]{.greek-added} του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και αδικιας[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι παρομοιαζετε ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις εξωθεν μεν φαινεσθε τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι εστε υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι οικοδομειτε τους ταφους των προφητων και κοσμειτε [των]{.greek-added} [δικαιων]{.greek-added} τα μνημεια [των]{.greek-omitted} [δικαιων]{.greek-omitted}[23:29]{.aside}

και λεγετε ει [ημεν]{.greek-omitted} [ημεθα]{.greek-added} εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν [ημεν]{.greek-omitted} [ημεθα]{.greek-added} κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και [σταυρωσετε]{.greek-abbr} και εξ αυτων μαστιγωσετε εν ταις συναγωγαις υμων και διωξετε απο πολεως εις πολιν[23:34]{.aside}

οπως [ελθη]{.greek-omitted} [αν]{.greek-added} [ελθοι]{.greek-added} εφ υμας παν αιμα δικαιον εκχυνομενον επι της γης απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεινουσα]{.greek-added} τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον [τροπον]{.greek-omitted} [τρο]{.greek-added} [πον]{.greek-added} [ορνις]{.greek-added} επισυναγει [ορνις]{.greek-omitted} τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ [υμιν]{.greek-omitted} [ημιν]{.greek-added} ου μη με ιδητε απ αρτι εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτου επιδειξαι [αυτω]{.greek-omitted} τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου βλεπετε [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται [αυτου]{.greek-added} κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας [και]{.greek-omitted} [της]{.greek-omitted} [συντελειας]{.greek-omitted} [του]{.greek-omitted} [αιωνος]{.greek-omitted}[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added}[24:5]{.aside}

[μελλησετε]{.greek-omitted} [μελλησεται]{.greek-added} [δε]{.greek-omitted} [γαρ]{.greek-added} ακουειν πολεμους και ακοας πολεμων ορατε μη θροεισθε δει γαρ παντα γενεσθαι αλλ [ουπω]{.greek-omitted} [εστιν]{.greek-omitted} [ουκ]{.greek-added} [ευθυς]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και λοιμοι και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη ωδινων[24:8]{.aside}

τοτε παραδωσουσιν υμας εις θλιψιν και αποκτενουσιν υμας και εσεσθε μισουμενοι υπο παντων [των]{.greek-omitted} [εθνων]{.greek-omitted} δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} και μισησουσιν αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται [τουτο]{.greek-omitted} το ευαγγελιον της βασιλειας εν ολη τη οικουμενη εις μαρτυριον [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και τοτε ηξει το τελος[24:14]{.aside}

οταν [ουν]{.greek-omitted} [δε]{.greek-added} ιδητε το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου εστως εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν επι τα ορη[24:16]{.aside}

ο επι του δωματος μη καταβαινετω αραι τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος μηδε σαββατω[24:20]{.aside}

εσται γαρ τοτε θλιψις μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν ουδ ου μη γενηται[24:21]{.aside}

και ει μη εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια μεγαλα και τερατα ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα [υμιν]{.greek-omitted} [υμων]{.greek-added}[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω [εστιν]{.greek-omitted} [εστι]{.greek-added} μη εξελθητε ιδου εν τοις ταμειοις μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ [εαν]{.greek-omitted} [αν]{.greek-added} η το πτωμα εκει συναχθησονται [και]{.greek-added} οι αετοι[24:28]{.aside}

περι δε της ημερας εκεινης και [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις προ του κατακλυσμου τρωγοντες και πινοντες γαμουντες και [εκ]{.greek-added} [εκγαμιζοντες]{.greek-omitted} [γαμιζοντες]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} ης ημερας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως [ου]{.greek-added} ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο αληθουσαι εν τω μυλωνι μια παραλαμβανεται και μια αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει ηδει ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν [ειασεν]{.greek-omitted} [ειασε]{.greek-added} διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της θεραπειας αυτου [του]{.greek-omitted} διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους εσθιειν δε και πινειν μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις [απαντησιν]{.greek-omitted} [συναντησιν]{.greek-added} του νυμφιου[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και [αι]{.greek-omitted} πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον [μεθ]{.greek-omitted} [μετ]{.greek-added} [εαυτων]{.greek-omitted} [αυτων]{.greek-added} ελαιον[25:3]{.aside}

[αι]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} [φρονιμοι]{.greek-added} [ελαβον]{.greek-added} [μετ]{.greek-added} [αυτων]{.greek-added} [ελαιον]{.greek-added} [οι]{.greek-added} δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

[μεσης]{.greek-omitted} [μεσαυσης]{.greek-added} δε [της]{.greek-added} νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις [απαντησιν]{.greek-omitted} [συναντησιν]{.greek-added} αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε ημιν εκ του ελαιου υμων οτι αι λαμπαδες ημων [σβεννυνται]{.greek-omitted} [σβεννυντε]{.greek-added}[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε [ουκ]{.greek-omitted} [ου]{.greek-added} [μη]{.greek-added} αρκεση ημιν και υμιν πορευεσθε [δε]{.greek-omitted} μαλλον προς τους πωλουντας και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν [αμην]{.greek-added} αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν [ουδε]{.greek-omitted} [ουτε]{.greek-added} την ωραν εν η ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν [ευθεως]{.greek-omitted}[25:15]{.aside}

[ευθεως]{.greek-added} [δε]{.greek-added} πορευθεις [δε]{.greek-omitted} ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο [εκερδησεν]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [αλλα]{.greek-omitted} [δυο]{.greek-omitted}[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και [απεκρυψεν]{.greek-omitted} [απεκρυψε]{.greek-added} το αργυριον του [κυριου]{.greek-abbr} αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και συναιρει μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη δε αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα [λαβων]{.greek-omitted} [ειληφως]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων [εκρυψα]{.greek-omitted} [απεκρυψα]{.greek-added} το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε [ει]{.greek-added} ηδεις οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον εκβαλετε εις το σκοτος το [εξω]{.greek-added} [εξωτερον]{.greek-omitted} [τερον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε καθισει επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην [υμιν]{.greek-omitted} [ημιν]{.greek-added} βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με ξενος ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και επεσκεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και συνηγαγομεν η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο [βασιλευς]{.greek-omitted} [[ιησους]{.greek-abbr}]{.greek-added} ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι εποιησα[τ]{.unclear}ε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το [σταυρωθηναι]{.greek-abbr}[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω [κρατησωσιν]{.greek-omitted} [κρατησωσι]{.greek-added} και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους παρεχετε τη γυναικι εργον γαρ καλον [ειργασατο]{.greek-omitted} [εποιησεν]{.greek-added} εις εμε[26:10]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το ενταφιασαι με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω [λαληθησεται]{.greek-omitted} [κηρυχθησεται]{.greek-added} και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε μοι δουναι [καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που θελεις ετοιμασομεν σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως [συνεταξεν]{.greek-omitted} [προσεταξεν]{.greek-added} αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα[26:20]{.aside}

και εσθιοντων αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω τρυβλιω την χειρα ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον η[ν]{.unclear} [αυτ]{.greek-supplied}[ω]{.unclear} ει ουκ [εγεννηθη]{.greek-omitted} [εγενηθη]{.greek-added} ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του γεννηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω μεθ υμων [καινον]{.greek-omitted} εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει [αυτ[οις]{.unclear}]{.greek-added} [αυτοις]{.corr} [ο]{.corr} [[ιησους]{.greek-abbr}]{.corr} παντες υμεις σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον ποιμενα και διασκορπισθησεται τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω [δε]{.greek-omitted} ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησ[ο]{.unclear}μαι]{.greek-added} ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον γεθσημανη και λεγει τοις μαθηταις καθισατε αυτου εως [ου]{.greek-omitted} απελθων [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added} εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου [απελθων]{.greek-omitted} προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται [τουτο]{.greek-omitted} το ποτηριον [τουτο]{.greek-added} παρελθειν απ εμου εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων ευρισκει αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} χαιρε ραββι και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ ω παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} εκτεινας την χειρα [απεσπασεν]{.greek-omitted} [απεσπασε]{.greek-added} την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον σου την μαχαιραν εις τον τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν μαχαιρα αποθανουνται[26:52]{.aside}

η δοκεις οτι ου δυναμαι αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα [λεγεωνας]{.greek-omitted} [λεγιωνας]{.greek-added} αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος ηκολουθει αυτω απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και [ολον]{.greek-added} το συνεδριον [ολον]{.greek-omitted} εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως θανατωσωσιν αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

