---
title: "Collation of Byz^RP^ vs 30866 (866)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 866 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30866).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 866                                   	| λογος                              	|
| 866 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 866 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 866               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 866                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 866 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 866                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 7

[εν]{.greek-omitted} [ω]{.greek-omitted} [γαρ]{.greek-omitted} [κριματι]{.greek-omitted} [κρινετε]{.greek-omitted} [κριθησεσθε]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [ω]{.greek-omitted} [μετρω]{.greek-omitted} μετρειτε μετρηθησεται υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος το εν τω οφθαλμω του αδελφου σου την δε εν τω σω οφθαλμω δοκον ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος απο του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη δωτε το αγιον τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε βαλητε τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε καταπατησωσιν αυτους εν τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

αιτειτε και δοθησεται υμιν ζητειτε και ευρησετε κρουετε και ανοιγησεται υμιν[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις εστιν εξ υμων [ανθρωπος]{.greek-abbr} ον εαν αιτηση ο υιος αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

και εαν ιχθυν αιτηση μη οφιν επιδωσει αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

παντα ουν οσα αν θελητε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} ουτως και υμεις [ποι[―]{.gap}]{.greek-added} [ποιειτε]{.corr} αυτοις ουτος γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

εισελθετε δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την [απωλειαν]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [εισερχομενοι]{.greek-omitted} [δι]{.greek-omitted} [αυτης]{.greek-omitted}[7:13]{.aside}

[εισελθετε]{.greek-omitted} [δια]{.greek-omitted} [της]{.greek-omitted} [στενης]{.greek-omitted} [πυλης]{.greek-omitted} [οτι]{.greek-omitted} [πλατεια]{.greek-omitted} [η]{.greek-omitted} [πυλη]{.greek-omitted} [και]{.greek-omitted} [ευρυχωρος]{.greek-omitted} [η]{.greek-omitted} [οδος]{.greek-omitted} [η]{.greek-omitted} [απαγουσα]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13 | instance no. 2]{.aside}

τι στενη η πυλη και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

προσεχετε δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον σαπρον καρπους καλους ποιειν[7:18]{.aside}

παν [ουν]{.greek-added} δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου τω σω ονοματι προεφητευσαμεν και τω σω ονοματι δαιμονια εξεβαλομεν και τω σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε ομολογησω αυτοις οτι ουδεποτε εγνων υμας αποχωρειτε απ εμου οι εργαζομενοι την ανομιαν[7:23]{.aside}

[πας]{.greek-omitted} [ουν]{.greek-omitted} [οστις]{.greek-omitted} [ακουει]{.greek-omitted} [μου]{.greek-omitted} [τους]{.greek-omitted} [λογους]{.greek-omitted} [τουτους]{.greek-omitted} [και]{.greek-omitted} [ποιει]{.greek-omitted} [αυτους]{.greek-omitted} [ομοιωσω]{.greek-omitted} [αυτον]{.greek-omitted} [ανδρι]{.greek-omitted} [φρονιμω]{.greek-omitted} [οστις]{.greek-omitted} [ωκοδομησεν]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} αυτου επι την πετραν[7:24]{.aside}

πας ουν οστις ακουει μου τους λογους τουτους και ποιει αυτους ομοιωσω αυτον ανδρι φρονιμω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν [αυτου]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [πετραν]{.greek-omitted}[7:24 | instance no. 2]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεπεσον τη οικια εκεινη και ουκ [επεσεν]{.greek-omitted} [επεσε]{.greek-added} τεθεμελιωτο γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεκοψαν τη οικια εκεινη και [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγενετο οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[7:29]{.aside}

### Chapter 8

καταβαντι δε αυτω απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου λεπρος ελθων προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} εαν θελης δυνασαι με καθαρισαι[8:2]{.aside}

και εκτεινας την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω καθαρισθητι και ευθεως εκαθαρισθη αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι ειπης [αλλα]{.greek-omitted} [αλλ]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} το δωρον ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε αυτω εις καπερναουμ προσηλθεν αυτω εκατονταρχος παρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου βεβληται εν τη οικια παραλυτικος δεινως βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} [ουκ]{.greek-omitted} [ειμι]{.greek-omitted} [ικανος]{.greek-omitted} [ινα]{.greek-omitted} [μου]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [στεγην]{.greek-omitted} [εισελθης]{.greek-omitted} [αλλα]{.greek-omitted} [μονον]{.greek-omitted} [ειπε]{.greek-omitted} [λογω]{.greek-omitted} [και]{.greek-omitted} [ιαθησεται]{.greek-omitted} [ο]{.greek-omitted} [παις]{.greek-omitted} [μου]{.greek-omitted}[8:8]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [εκατονταρχος]{.greek-omitted} [εφη]{.greek-omitted} [κυριε]{.greek-omitted} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8 | instance no. 2]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι υπο εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} [εθαυμασεν]{.greek-omitted} [εθαυμασε]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις ακολουθουσιν αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και ανακλιθησονται μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη[8:13]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα πνευματα λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι [οπου]{.greek-omitted} [εαν]{.greek-omitted} [απερχη]{.greek-omitted}[8:19]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [εις]{.greek-omitted} [γραμματευς]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ακολουθησω]{.greek-omitted} [σοι]{.greek-omitted} οπου εαν απερχη[8:19 | instance no. 2]{.aside}

[και]{.greek-omitted} λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην κλινη[8:20]{.aside}

ετερος δε των μαθητων [αυτου]{.greek-omitted} ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις το πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων αυτος δε [εκαθευδεν]{.greek-omitted} [εκαθευδε]{.greek-added}[8:24]{.aside}

και προσελθοντες οι μαθηται ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι τοτε εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

και ελθοντι αυτω εις το περαν εις την χωραν των γεργεσηνων υπηντησαν αυτω δυο δαιμονιζομενοι εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων πολλων βοσκομενη[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει [εκβαλ]{.greek-added} [εκβαλλεις]{.greek-omitted} [ημας]{.greek-omitted} [επιτρεψον]{.greek-omitted} [ημιν]{.greek-omitted} [απελθειν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [αγελην]{.greek-omitted} [των]{.greek-omitted} [χοιρων]{.greek-omitted}[8:31]{.aside}

[λεις]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [δαιμονες]{.greek-omitted} [παρεκαλουν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγοντες]{.greek-omitted} [ει]{.greek-omitted} [εκβαλλεις]{.greek-omitted} ημας επιτρεψον ημιν απελθειν εις την αγελην των χοιρων[8:31 | instance no. 2]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου [ωρμησεν]{.greek-omitted} [ωρμησε]{.greek-added} πασα η αγελη των χοιρων κατα του κρημνου εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις το πλοιον [διεπερασεν]{.greek-omitted} [διεπερασε]{.greek-added} και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω παραλυτικω θαρσει τεκνον αφεωνται σοι αι αμαρτιαι σου[9:2]{.aside}

και ιδου τινες των γραμματεων ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και [ιδων]{.greek-omitted} [ειδως]{.greek-added} ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις ενθυμεισθε πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν ευκοπωτερον ειπειν αφεωνται σου αι αμαρτιαι η ειπειν εγειραι και περιπατει[9:5]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον [αυτου]{.greek-omitted}[9:7]{.aside}

[και]{.greek-omitted} [εγερθεις]{.greek-omitted} [απηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} αυτου[9:7 | instance no. 2]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

και παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} καθημενον επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων εσθιει [και]{.greek-added} [πινει]{.greek-added} ο διδασκαλος υμων[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν ελεον θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται ιωαννου λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε μαθηται σου ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος πενθειν εφ οσον [χρονον]{.greek-added} μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

ουδεις δε επιβαλλει επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και χειρον σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [ρηγνυνται]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [εκχειται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [απολουνται]{.greek-omitted} [αλλα]{.greek-omitted} [βαλλουσιν]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [καινους]{.greek-omitted} [και]{.greek-omitted} [αμφοτεροι]{.greek-omitted} [συντηρουνται]{.greek-omitted}[9:17]{.aside}

[μη]{.greek-added} [γε]{.greek-added} [ουδε]{.greek-omitted} [βαλλουσιν]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [παλαιους]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μηγε]{.greek-omitted} ρηγνυνται οι ασκοι και ο οινος εκχειται και οι ασκοι [απολουνται]{.greek-omitted} [απολλυνται]{.greek-added} αλλα βαλλουσιν οινον νεον εις ασκους καινους και αμφοτεροι συντηρουνται[9:17 | instance no. 2]{.aside}

ταυτα αυτου λαλουντος αυτοις ιδου αρχων [εις]{.greek-omitted} [τις]{.greek-added} ελθων προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν αλλα ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον αψωμαι του ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} θαρσει θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισελθων [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

και παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας [υιε]{.greek-omitted} [υιος]{.greek-added} [δαυιδ]{.greek-abbr}[9:27]{.aside}

ελθοντι δε εις την οικιαν προσηλθον αυτω οι τυφλοι και λεγει αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} πιστευετε οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων [αυτων]{.greek-omitted} [λεγων]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [υμων]{.greek-omitted} [γενηθητω]{.greek-omitted} [υμιν]{.greek-omitted}[9:29]{.aside}

[τοτε]{.greek-omitted} [ηψατο]{.greek-omitted} [των]{.greek-omitted} [οφθαλμων]{.greek-omitted} αυτων λεγων κατα την πιστιν υμων γενηθητω υμιν[9:29 | instance no. 2]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες διεφημισαν αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες [οτι]{.greek-added} ουδεποτε εφανη ουτως εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε φαρισαιοι ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολεις πασας και τας κωμας διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[9:35]{.aside}

ιδων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν εσκυλμενοι και ερριμμενοι [ωσει]{.greek-omitted} [ως]{.greek-added} προβατα μη εχοντα ποιμενα[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο μεν θερισμος [πολλυς]{.greek-added} [πολυς]{.corr} οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του κυριου του θερισμου οπως εκβαλη εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

και προσκαλεσαμενος τους δωδεκα μαθητας αυτου εδωκεν αυτοις εξουσιαν πνευματων ακαθαρτων ωστε εκβαλλειν αυτα και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

των δε δωδεκα αποστολων τα ονοματα [εστιν]{.greek-omitted} [εισι]{.greek-added} ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου ιακωβος ο του ζεβεδαιου και ιωαννης ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και λεββαιος ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο κανανιτης και ιουδας ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους δωδεκα απεστειλεν ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν σαμαρειτων μη εισελθητε[10:5]{.aside}

πορευεσθε δε μαλλον προς τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρυσσετε λεγοντες οτι ηγγικεν η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

[ασθενουντας]{.corr} [θεραπευετε]{.corr} [λεπρους]{.corr} [καθαριζετε]{.corr} δαιμονια εκβαλλετε δωρεαν ελαβετε δωρεαν δοτε[10:8]{.aside}

μη κτησησθε χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε ραβδους αξιος γαρ ο εργατης της τροφης αυτου εστιν[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις εν αυτη αξιος [εστιν]{.greek-omitted} [εστι]{.greek-added} κακει μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν ασπασασθε αυτην[10:12]{.aside}

και εαν μεν η η οικια αξια ελθετω η ειρηνη υμων επ αυτην εαν δε μη η αξια η ειρηνη υμων προς υμας επιστραφητω[10:13]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της οικιας η της πολεως εκεινης εκτιναξατε τον κονιορτον των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν ανεκτοτερον εσται γη σοδομων και γομορρων εν ημερα κρισεως η τη [πολει]{.greek-omitted} [εκεινη]{.greek-omitted}[10:15]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [γη]{.greek-omitted} [σοδομων]{.greek-omitted} [και]{.greek-omitted} [γομορρων]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} πολει εκεινη[10:15 | instance no. 2]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων γινεσθε ουν φρονιμοι ως οι οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε παραδιδωσιν υμας μη μεριμνησητε πως η τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} δοθησεται γαρ υμιν εν εκεινη τη ωρα τι λαλησετε[10:19]{.aside}

ου γαρ υμεις εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[10:22]{.aside}

οταν δε διωκωσιν υμας εν τη πολει ταυτη φευγετε εις την αλλην αμην γαρ λεγω υμιν ου μη τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο υιος του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης υπερ τον διδασκαλον ουδε δουλος υπερ τον κυριον αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα γενηται ως ο διδασκαλος αυτου και ο δουλος ως ο κυριος αυτου ει τον οικοδεσποτην βεελζεβουλ [εκαλεσαν]{.greek-omitted} [απεκαλεσαν]{.greek-added} ποσω μαλλον τους οικειακους αυτου[10:25]{.aside}

μη ουν φοβηθητε αυτους ουδεν γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} κεκαλυμμενον ο ουκ αποκαλυφθησεται και κρυπτον [ο]{.greek-omitted} [ου]{.greek-omitted} [γνωσθησεται]{.greek-omitted}[10:26]{.aside}

[ο]{.greek-omitted} [δεχομενος]{.greek-omitted} [υμας]{.greek-omitted} [εμε]{.greek-omitted} [δεχεται]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [εμε]{.greek-omitted} [δεχομενος]{.greek-omitted} [δεχεται]{.greek-omitted} [τον]{.greek-omitted} αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψεται[10:41]{.aside}

και ος εαν ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε ιωαννης ακουσας εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-abbr} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται και κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωαννου τι εξηλθετε εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι εξηλθετε ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι εξηλθετε ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω [τον]{.greek-omitted} [αγγελον]{.greek-omitted} [μου]{.greek-omitted} [προ]{.greek-omitted} [προσωπου]{.greek-omitted} [σου]{.greek-omitted} [ος]{.greek-omitted} [κατασκευασει]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [σου]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [σου]{.greek-omitted}[11:10]{.aside}

[ουτος]{.greek-omitted} [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [περι]{.greek-omitted} [ου]{.greek-omitted} [γεγραπται]{.greek-omitted} [ιδου]{.greek-omitted} [εγω]{.greek-omitted} [αποστελλω]{.greek-omitted} τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10 | instance no. 2]{.aside}

αμην λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων μειζων ιωαννου του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων ιωαννου του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως ιωαννου προεφητευσαν[11:13]{.aside}

και ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις εν [αγοραις]{.greek-omitted} [αγορα]{.greek-added} καθημενοις και [προσφωνουσιν]{.greek-omitted} [προσφωνουσι]{.greek-added} τοις εταιροις αυτων[11:16]{.aside}

και λεγουσιν ηυλησαμεν υμιν και ουκ ωρχησασθε εθρηνησαμεν υμιν και ουκ εκοψασθε[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ιωαννης μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο υιος του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης τελωνων φιλος και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ονειδιζειν τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χωραζιν]{.greek-added} ουαι σοι βηθσαιδα οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι αν εν σακκω και σποδω [[καθημεναι]{.corr}]{.greek-added} [μετενοησαν]{.corr}[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι ανεκτοτερον εσται εν ημερα [κρισεως]{.greek-omitted} [η]{.greek-omitted} [υμιν]{.greek-omitted}[11:22]{.aside}

