---
title: "Collation of Byz^RP^ vs 30949 (949)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 949 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30949).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 949                                   	| λογος                              	|
| 949 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 949 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 949               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 949                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 949 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 949                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευα[γ]{.unclear}γελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [υι[ου]{.unclear}]{.corr} του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας [ποιη]{.greek-added} [ποιειτε]{.corr} τας τριβους αυτου[1:3]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπ[τιζ]{.unclear}ων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} πρ[ος]{.unclear} αυτον πασα η ιουδαια χωρα και [οι]{.greek-omitted} ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ενδεδυμενος τριχας [κα]{.unclear}[μηλου]{.greek-supplied} και ζωνην δερματινην περι την [οσφυν]{.greek-omitted} [οσφην]{.greek-added} αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα [[η]{.unclear}μας]{.greek-added} [υμας]{.corr} εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθ[η]{.unclear} υπο [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εις τον ιορδανην[1:9]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν [καταβαιν[ω]{.unclear}ν]{.greek-added} [καταβαινον]{.corr} ε[π]{.unclear} αυτον[1:10]{.aside}

και φωνη εγενετο εκ των ουρανων συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω ευδοκησα[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερ[η]{.unclear}[μω]{.greek-supplied} [τε]{.greek-added} [[μ]{.greek-abbr}]{.greek-added} ημερας [τεσσαρακοντα]{.greek-omitted} πειραζομενος υπο του σατανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγε[λοι]{.greek-supplied} διηκονουν αυτω[1:13]{.aside}

μετα [[δε]{.unclear}]{.corr} το παραδοθηναι τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} [μετανοη]{.greek-added} [μετανοειτε]{.corr} και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

[περι]{.greek-added} [παντων]{.greek-added} [περιπατων]{.corr} δε παρα την θαλασσαν [την]{.greek-added} [της]{.corr} γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [σιμωνα]{.greek-omitted} [σιμονα]{.greek-added} και ανδρεαν τον αδελφον αυτου του σιμωνος [[σιμονος]{.corr}]{.greek-added} βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} δευτε οπισω μου και ποιησω υμας [α]{.greek-added} [γενεσθαι]{.corr} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα [αυτων]{.greek-omitted} ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον [του]{.greek-omitted} ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλε[σεν]{.greek-supplied} αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των [μισθωτων]{.greek-omitted} [μισθοτων]{.greek-added} απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασ[ιν]{.unclear} [ει]{.greek-supplied}σελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο [παντες]{.greek-added} επι τη διδα[χη]{.unclear} αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και [ην]{.corr} εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και [σου]{.greek-added} [σοι]{.corr} [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν [επ]{.greek-added} [εξ]{.corr} αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} [τι]{.greek-added} [εστι]{.greek-added} [τουτο]{.greek-added} τι εστιν [τουτο]{.greek-omitted} [τις]{.greek-omitted} η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν [αυτω]{.greek-omitted} [αυτου]{.greek-added}[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ τη[ς]{.unclear} [συ]{.greek-supplied}ναγωγης [εξελθοντες]{.greek-omitted} [εξελθων]{.greek-added} [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} σιμωνος και ανδρεου μετα ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[1:29]{.aside}

η [δ]{.unclear}[ε]{.greek-supplied} [πενθερα]{.greek-omitted} [πενθαρα]{.greek-added} σιμωνος κατεκειτο [πυρε[―]{.gap}σα]{.greek-added} [πυρεσσουσα]{.greek-omitted} [[πυρεττουσα]{.corr}]{.greek-added} και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και [προ]{.greek-supplied}σελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει [αυτη]{.greek-added} [αυτοις]{.corr}[1:31]{.aside}

οψ[ιας]{.greek-supplied} δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλον]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι εννυχον λιαν αναστας εξηλθεν και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν [αυτ[α]{.unclear}]{.greek-added} [αυτω]{.corr} οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων αυτω οτι εαν θελης δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμ[η]{.greek-supplied}σαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε [σ]{.unclear}[ε]{.greek-supplied}αυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου [α]{.greek-omitted} [ο]{.greek-added} [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [μωσης]{.greek-omitted} [μωυσ[ης]{.unclear}]{.greek-added} εις μαρτυριον [αυτ[α]{.unclear}ς]{.greek-added} [αυτοις]{.corr}[1:44]{.aside}

ο δε εξελθων [η]{.unclear}ρξατο κηρυσσειν πολλα και διαφημιζειν τον λο[γ]{.unclear}[ον]{.greek-supplied} ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45]{.aside}

### Chapter 2

και εισηλθεν [παλιν]{.greek-omitted} εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφεον]{.greek-added} [αφεωνται]{.corr} σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομεν[ο]{.unclear}[ι]{.greek-supplied} εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} λαλει [βλασφημιας]{.greek-omitted} [βλασφημει]{.greek-added} τις δυναται αφιενα[ι]{.unclear} αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογιζεσθαι]{.greek-added} [διαλογιζεσθε]{.corr} εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν εγειραι και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ειδειτε]{.greek-added} οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρ[ε]{.unclear}]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} και αρας τον κραβ[β]{.unclear}[ατον]{.greek-supplied} εξηλθεν [εναντιον]{.greek-omitted} [εναντιων]{.greek-added} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεπ[ο]{.unclear}τε ουτως ειδομεν[2:12]{.aside}

και εξηλθεν παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ειδε]{.greek-added} λευι τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα [των]{.greek-omitted} τελωνων και αμαρτωλων ελεγον τοις μαθηταις [αυτου]{.greek-omitted} τι οτι μετα [των]{.greek-omitted} τελωνων και αμαρτωλων [εσθιει]{.greek-omitted} [ε[σ]{.unclear}θειη]{.greek-added} και πινει[2:16]{.aside}

[και]{.greek-omitted} ακουσας [δε]{.greek-added} ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν [α]{.unclear}[υ]{.greek-supplied}τοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ [αυτων]{.greek-omitted} [αυτου]{.greek-added} εστιν νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευ[ου]{.unclear}σιν]{.greek-added} εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου επιρραπτει επι ιματιω παλαιω ει δε μη αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και [ουδεις]{.greek-omitted} [ουδε]{.greek-added} βαλλει οινον νεον εις ασκους παλαιους ει [δε]{.greek-omitted} μη ρησσει ο οινος [ο]{.greek-omitted} [νεος]{.greek-omitted} τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται αλλα οινον νεον εις [καινους]{.greek-added} ασκους [καινους]{.greek-omitted} βλητεον[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις σαββασιν δια των σποριμων και ηρξαντο οι μαθηται αυτου [οδον]{.greek-omitted} [ποιειν]{.greek-omitted} [οδοποιειν]{.greek-added} τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθ[ε]{.unclear}ν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και [τους]{.greek-omitted} αρτους [της]{.greek-omitted} [προθεσεως]{.greek-omitted} [εφαγεν]{.greek-omitted} [ους]{.greek-omitted} [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted} [φαγειν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τοις]{.greek-omitted} [ιερευσιν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [ουσιν]{.greek-omitted}[2:26]{.aside}

[πως]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [αβιαθαρ]{.greek-omitted} [αρχιερεως]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} της προθεσεως [εφαγεν]{.greek-omitted} [εφαγε]{.greek-added} ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν [αυτω]{.greek-omitted} [[α]{.unclear}[υ]{.greek-supplied}τοις]{.greek-added} [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26 | instance no. 2]{.aside}

και ελεγεν αυτοις το [σαβατον]{.greek-added} [σαββατον]{.corr} δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος [εστιν]{.greek-omitted} [εστι]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εξ[η]{.unclear}ραμενην]{.greek-added} εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις [τι]{.greek-added} [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοπ[ο]{.unclear}ι[η]{.greek-supplied}[σαι]{.unclear} η κακοποιησαι ψυχην σωσαι η [αποκτειναι]{.greek-omitted} [απολεσαι]{.greek-added} οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη πωρωσει της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατ[εστ]{.unclear}[αθη]{.greek-supplied}]{.greek-added} [η]{.greek-omitted} [χειρ]{.greek-omitted} [αυτου]{.greek-omitted} [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[3:5]{.aside}

[και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [μετ]{.greek-omitted} [οργης]{.greek-omitted} [συλλυπουμενος]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [πωρωσει]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [εκτεινον]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξετεινεν]{.greek-omitted} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} η χειρ αυτου υγιης ως [η]{.greek-omitted} αλλη[3:5 | instance no. 2]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν [αυτω]{.greek-omitted} και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} και περαν του ιορδανου και [οι]{.greek-omitted} [υπερ]{.greek-added} [περι]{.corr} τυρον και σιδωνα πληθος πολυ [α]{.unclear}κουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπον]{.greek-added} τοις μαθηταις [αυτου]{.greek-omitted} ινα πλοιαριον [προσκαρτερει]{.greek-added} [προσκαρτερη]{.corr} αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου αψωνται οσοι ειχον μαστιγας[3:10]{.aside}

και τα πνευματα τα ακαθαρτα [οταν]{.greek-omitted} [οτε]{.greek-added} αυτον εθεωρει προσεπιπτ[εν]{.unclear} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} [λεγοντα]{.greek-omitted} [λεγοντες]{.greek-added} οτι συ ει ο [υιος]{.greek-abbr} τ[ου]{.unclear} [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιη[σε]{.unclear}]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα αποστελλη [αυτους]{.greek-omitted} κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον [του]{.greek-omitted} [[―]{.gap}ωβου]{.greek-added} [ιακωβου]{.corr} και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμ[ων]{.greek-supplied}[α]{.unclear} τον κανανιτην[3:18]{.aside}

και ιουδαν [τον]{.greek-added} ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη δυνασθαι [αυτους]{.greek-omitted} [αυτον]{.greek-added} [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

[και]{.unclear} ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι [βεελζε]{.greek-supplied}βουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος [αυτους]{.greek-omitted} [αυτος]{.greek-added} εν [παραβολαις]{.greek-omitted} [παραβολη]{.greek-added} ελεγεν αυτοις πως δυναται σατανας σαταναν εκ[β]{.unclear}α[λλειν]{.greek-supplied}[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται στ[α]{.unclear}θηναι [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [εκεινη]{.greek-omitted}[3:24]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [οικια]{.greek-omitted} [εφ]{.greek-omitted} [εαυτην]{.greek-omitted} [μερισθη]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [σταθηναι]{.greek-omitted} η οικια [εκειν[οι]{.unclear}]{.greek-added} [εκεινη]{.corr}[3:25]{.aside}

και ει ο σατανας ανεστη ε[φ]{.unclear} [ε]{.unclear}αυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον [δ[υ]{.unclear}ση]{.greek-added} [δηση]{.corr} και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα [[ανθρωπων]{.greek-abbr}]{.greek-added} [αμαρτηματα]{.corr} τοις υιοις των [ανθρωπων]{.greek-abbr} [και]{.greek-omitted} βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου [και]{.greek-omitted} εξω εστωτες απεστειλαν [ουν]{.greek-added} [φωνουντ[α]{.unclear}ς]{.greek-added} [[φωνουντες]{.corr}]{.greek-added} [προν]{.greek-added} [προς]{.corr} αυτον [φωνουντες]{.greek-omitted} [αυτον]{.greek-omitted}[3:31]{.aside}

και εκαθητο οχλος περι αυτον ειπον δε αυτω [ιδου]{.greek-omitted} η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι [αυτον]{.greek-omitted} [αυτων]{.greek-added} καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν [ποιησει]{.greek-added} [ποιηση]{.corr} το θελημα του [θεου]{.greek-abbr} ουτος [αδελφος]{.greek-omitted} [αδελφοσς]{.greek-added} μου και [αδελφ[ο]{.unclear}ι]{.greek-added} [αδελφη]{.corr} μου και [μητηρ]{.greek-abbr} [εστιν]{.greek-omitted} [μου]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος [πολλ]{.greek-added} [πολυς]{.corr} ωστε [αυ]{.unclear}τον εμβαντα εις το πλοιον [καθησθαι]{.greek-omitted} [καθεισθαι]{.greek-added} εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted}[4:2]{.aside}

[και]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [πολλα]{.greek-omitted} κα[ι]{.greek-supplied} [ε]{.greek-supplied}λεγεν [αυτοις]{.greek-omitted} [αυτης]{.greek-added} εν τη διδαχη αυτου[4:2 | instance no. 2]{.aside}

[ακουετε]{.greek-omitted} [ακουσατε]{.greek-added} [οτι]{.greek-added} ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

[και]{.corr} εγενετο εν τ[ω]{.unclear} σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο [δε]{.greek-omitted} επεσεν επ[ι]{.greek-supplied} το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

η[λ]{.unclear}[ιου]{.greek-supplied} δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακ[α]{.unclear}[νθας]{.greek-supplied} και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν ει[ς]{.unclear} [την]{.greek-supplied} γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν εν [τριακοντα]{.greek-omitted} [[λ]{.greek-abbr}]{.greek-added} [και]{.greek-added} [ἐν]{.greek-added} [[ξ]{.greek-abbr}]{.greek-added} [και]{.unclear} [εν]{.greek-supplied} [[[ρ]{.greek-supplied}]{.greek-abbr}]{.greek-added} [εξηκοντα]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [εκατον]{.greek-omitted}[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι [το]{.greek-omitted} [τα]{.greek-added} [μυστηριον]{.greek-omitted} [μυστηρια]{.greek-added} τη[ς]{.unclear} βασιλειας του [θεου]{.greek-abbr} [εκεινοις]{.greek-omitted} [τοις]{.greek-added} δε [λοιποις]{.greek-added} [τοις]{.greek-omitted} [εξω]{.greek-omitted} εν παραβολαις [τα]{.greek-omitted} [παντα]{.greek-omitted} [γινεται]{.greek-omitted}[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και α[κ]{.unclear}[ου]{.greek-supplied}οντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} [μηποτε]{.greek-omitted} [μητε]{.greek-added} [επιστρεψωσιν]{.greek-omitted} [επιστρεψ[ω]{.unclear}σι]{.greek-added} και [α]{.unclear}φεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε [εισιν]{.greek-omitted} [ησιν]{.greek-added} οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι [οταν]{.greek-omitted} [ακουσωσιν]{.greek-omitted} τον λογον [[ακουοντες]{.corr}]{.greek-added} [και]{.greek-added} ευθεως μετα χαρας [λαμβανουσιν]{.greek-omitted} [λαμβανοντες]{.greek-added} αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι [του]{.greek-omitted} [αιωνος]{.greek-omitted} τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} [τριακοντα]{.greek-omitted} [[λ]{.greek-abbr}]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} [εξηκοντα]{.greek-omitted} [[ξ]{.greek-abbr}]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} [εκατον]{.greek-omitted} [[ρ]{.greek-abbr}]{.greek-added}[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο [τον]{.greek-omitted} [το]{.greek-added} μοδιον τε[θ]{.unclear}[η]{.greek-supplied} η υπο την κλινην ουχ ινα επι την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον ο εαν μη φανερωθη ουδε [ε]{.unclear}[γενετο]{.greek-supplied} αποκρυφον αλλ ινα εις φανερον [ελθη]{.greek-omitted} [ελθοι]{.greek-added}[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και [ελεγεν]{.greek-supplied} αυτοις βλεπετε τι ακουετε εν ω μετρω [μετρειτε]{.greek-omitted} μετρηθησεται [υμιν]{.greek-omitted} [και]{.greek-omitted} [προστεθησεται]{.greek-omitted} υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [εχη]{.greek-omitted} [ε[χει]{.greek-supplied}]{.greek-added} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

κ[α]{.unclear}ι ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστ[α]{.unclear}[νει]{.greek-supplied}]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα [στ]{.unclear}[αχυν]{.greek-supplied} ειτα πληρη σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει [το]{.greek-omitted} [τον]{.greek-added} δρεπανον οτι πα[ρε]{.greek-supplied}στηκεν ο θερισμος[4:29]{.aside}

και ελε[γ]{.unclear}[εν]{.greek-supplied} τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσω]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως κοκκον σ[ιναπ]{.unclear}[εως]{.greek-supplied} ος οταν σπ[α]{.unclear}ρη [[σπειρη]{.corr}]{.greek-added} επι της γης [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων [των]{.greek-omitted} σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινε[ι]{.unclear} και [γιν]{.unclear}[εται]{.greek-supplied} [παντων]{.greek-omitted} [των]{.greek-omitted} [λαχανων]{.greek-omitted} [μειζων]{.greek-omitted} [και]{.greek-omitted} [ποιει]{.greek-omitted} [κλαδους]{.greek-omitted} [μεγαλους]{.greek-omitted} [ωστε]{.greek-omitted} [δυνασθαι]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [σκιαν]{.greek-omitted} [αυτου]{.greek-omitted} [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [κατασκηνουν]{.greek-omitted}[4:32]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [σπαρη]{.greek-omitted} [αναβαινει]{.greek-omitted} [και]{.greek-omitted} [γινεται]{.greek-omitted} παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υ[πο]{.unclear} τ[ην]{.unclear} [σκιαν]{.greek-supplied} [αυτου]{.greek-supplied} [τα]{.greek-supplied} [πετ]{.greek-supplied}εινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32 | instance no. 2]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτο[ι]{.unclear}ς το[ν]{.unclear} λ[ογον]{.unclear} [κα]{.unclear}θως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε το[ι]{.unclear}ς μαθητ[αις]{.unclear} [αυ]{.unclear}το[υ]{.unclear} [επελυεν]{.greek-omitted} [[ε]{.unclear}πελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λελαψ]{.greek-added} ανεμου μεγαλη τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι τη [πρη]{.greek-added} [πρυμνη]{.corr} επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} αυτω διδασκαλε ου [μελλ]{.greek-added} [μελει]{.corr} σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις επετιμησεν τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [πεφημωσο]{.greek-added} και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι [δειλοι]{.greek-omitted} [δηλοι]{.greek-added} [εσται]{.greek-added} [εστε]{.corr} ουτως πως ουκ [εχεται]{.greek-added} [εχετε]{.corr} πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον [μεγαν]{.greek-omitted} [μεγα]{.greek-added} και [ελεγεν]{.greek-added} [ελεγον]{.corr} προς αλληλους τις [αρα]{.corr} [εστιν]{.greek-added} ουτος [εστιν]{.greek-omitted} οτι και ο ανεμος και η θαλασσα υπακουουσιν [αυτω]{.greek-omitted} [αυτου]{.greek-added}[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις [τ]{.unclear}[ην]{.greek-supplied} χωραν των γαδαρηνων[5:1]{.aside}

και [εξελθοντι]{.greek-omitted} [εξελθοντος]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} εκ του πλοιου ευθεως απηντησεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εκ των μνη[μει]{.greek-supplied}[ων]{.unclear} [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος [και]{.greek-added} την κατοικησιν [ηχεν]{.greek-added} [ειχεν]{.corr} εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ο[υ]{.greek-supplied}δεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι υπ [αυ]{.greek-supplied}του τας αλυσεις και τας πεδας συντετριφθαι και [ουδεις]{.greek-omitted} [ουδεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} [ισχυσε]{.greek-added} δαμασαι[5:4]{.aside}

και δια πα[ν]{.unclear}[τος]{.greek-supplied} νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [μνημειοις]{.greek-added} ην κραζων και κατακοπτων ε[α]{.unclear}[υτον]{.greek-supplied} [λιθοις]{.greek-supplied}[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι εμοι και σοι [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε [εις]{.greek-added} τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω [εξελθε]{.greek-omitted} [εξελθειν]{.greek-added} το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρ[ω]{.unclear}[τα]{.greek-supplied} [αυτον]{.greek-omitted} [αυτω]{.greek-added} τι σοι ονομα και απεκριθη [λεγων]{.greek-omitted} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον [πολλα]{.greek-omitted} [π[ο]{.greek-supplied}λλακις]{.greek-added} ινα [μη]{.greek-omitted} αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει προς τω ορει αγελη χοιρων [μεγαλη]{.greek-omitted} [μεγαλων]{.greek-added} βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον [παντες]{.greek-omitted} οι [δ]{.unclear}[αι]{.greek-supplied}μονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετ[ρ]{.unclear}[εψεν]{.greek-supplied} αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα πνευματα τα [ακαρθατα]{.greek-added} [ακαθαρτα]{.corr} εισηλθον εις τους χο[ι]{.unclear}[ρους]{.greek-supplied} και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επν[ι]{.unclear}γοντο εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και ανηγγειλαν εις την πολιν και ει[ς]{.greek-supplied} τους αγρους [και]{.greek-omitted} [εξηλθον]{.greek-omitted} [ιδειν]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [γεγονος]{.greek-omitted}[5:14]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [βοσκοντες]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [εφυγον]{.greek-omitted} [και]{.greek-omitted} [ανηγγειλαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αγρους]{.greek-omitted} και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14 | instance no. 2]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον [και]{.greek-omitted} ιματισμενον και σωφρονουντα τον εσχηκοτα [τον]{.greek-omitted} λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

[και]{.greek-omitted} ηρξαντο [παραλειν]{.greek-added} [παρακαλειν]{.corr} αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον [αυτοις]{.greek-omitted} [αυτω]{.greek-added} οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [σε]{.greek-omitted} [ελαλησε]{.greek-added} [σοι]{.greek-added}[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και απηλθεν μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν [ρησει]{.greek-added} [ρυσει]{.corr} αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης [παντα]{.corr} και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι [καν]{.greek-omitted} [εαν]{.greek-added} των ιματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν [εαυτω]{.greek-omitted} [αυτω]{.greek-added} την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω [οι]{.corr} μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν [αυτ[ω]{.unclear}]{.greek-added} [αυτη]{.corr} θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε [υπαγε]{.greek-omitted} [ειπαγε]{.greek-added} εις ειρηνην και [ισθι]{.greek-omitted} [ισθη]{.greek-added} υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος [ερχονται]{.greek-omitted} [ερχεται]{.greek-added} απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλλης]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} [ακουσας]{.greek-added} ευθεως [ακουσας]{.greek-omitted} τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω συνακολουθησαι ει μη πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον [οικον]{.greek-omitted} [οικιαν]{.greek-added} του αρχισυναγωγου και θεωρει θορυβον κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει [αυτοις]{.greek-omitted} [αυτω]{.greek-added} τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και κλαιετε το [παιδιον]{.greek-omitted} [παιδαριον]{.greek-added} ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και [κατεγελων]{.greek-omitted} [καταγελων]{.greek-added} [αυτου]{.greek-omitted} ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} [του]{.greek-omitted} [της]{.greek-added} [παιδιου]{.greek-omitted} [παιδος]{.greek-added} και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το [παιδιον]{.greek-omitted} [παιδα[ρ]{.unclear}ιον]{.greek-added} [ανακειμενον]{.greek-omitted} [κατακειμενον]{.greek-added}[5:40]{.aside}

και κρατησας της χειρος του [παιδιου]{.greek-omitted} [παιδος]{.greek-added} λεγει [αυτη]{.greek-omitted} [αυτω]{.greek-added} ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω εγειραι[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων [δωδεκα]{.greek-omitted} [[ι[β]{.unclear}]{.greek-abbr}]{.greek-added} και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις [γνω]{.greek-omitted} [γνωση]{.greek-added} τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο [εν]{.greek-omitted} [επι]{.greek-added} τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η [δ[ο]{.greek-supplied}θεισα]{.greek-added} σοφια [η]{.greek-omitted} [δοθεισα]{.greek-omitted} αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτ[ο]{.unclear}[ς]{.greek-supplied} εστιν ο τεκτων ο [υιος]{.greek-abbr} [της]{.greek-added} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνο[ς]{.unclear} και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} [οτι]{.greek-omitted} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου [και]{.greek-supplied} εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησα[ι]{.unclear} ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την α[π]{.unclear}[ι]{.greek-supplied}στιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και ηρξατ[ο]{.unclear} [αυ]{.greek-supplied}τους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των ακαθαρτων[6:7]{.aside}

και π[α]{.unclear}ρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μονον μ[η]{.unclear} π[η]{.unclear}ρ[α]{.unclear}[ν]{.greek-supplied} [μη]{.greek-supplied} αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους σανδαλια και μη ενδυσησθε δυ[ο]{.unclear} [χι]{.greek-supplied}τωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκ[ειθεν]{.greek-supplied}[6:10]{.aside}

και [οσοι]{.greek-omitted} [οπου]{.greek-added} [αν]{.greek-omitted} [εαν]{.greek-added} μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθε[ν]{.unclear} [[εκτι]{.greek-supplied}]{.greek-added} [εκτιναξατε]{.greek-omitted} [τον]{.greek-omitted} [χουν]{.greek-omitted} [τον]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [η]{.greek-omitted} [γομορροις]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [εκεινη]{.greek-omitted}[6:11]{.aside}

[ναξαντες]{.greek-added} [και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [μη]{.greek-omitted} [δεξωνται]{.greek-omitted} [υμας]{.greek-omitted} [μηδε]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [υμων]{.greek-omitted} [εκπορευομενοι]{.greek-omitted} [εκειθεν]{.greek-omitted} [εκτιναξατε]{.greek-omitted} τον χουν τον υπ[ο]{.unclear}κατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον [εστε]{.greek-added} [εσται]{.corr} σοδομοις η [γομορ[ρ]{.unclear}]{.greek-added} [γομορροις]{.greek-omitted} [[γομοροις]{.corr}]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[6:11 | instance no. 2]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα [εξεβαλλον]{.greek-omitted} [εκβαλον]{.greek-added} και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και [ελεγεν]{.greek-omitted} [ελεγον]{.greek-added} οτι [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο [βαπτιζων]{.greek-omitted} [βαπτιστης]{.greek-added} εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελ[ε]{.unclear}[γον]{.greek-supplied} οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν [ο]{.greek-supplied}τι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

[αυτος]{.greek-omitted} [ουτος]{.greek-added} γαρ [ο]{.greek-omitted} ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρα[τ]{.unclear}[η]{.greek-supplied}σε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου [ο]{.unclear}τι αυτην εγαμησεν[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [[ιω]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [ιωαννης]{.greek-omitted} τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε [η]{.greek-supplied}ρωδιας ενειχεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ειδω[ς]{.unclear} αυτον ανδρα δικαιον και αγιον και [συνετει]{.greek-added} [συνετηρει]{.corr} αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου [ηκουεν]{.greek-omitted} [[η]{.unclear}κουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας [ευκαιρου]{.greek-omitted} οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις [τ[οι]{.unclear}ς]{.greek-added} [της]{.corr} γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος [αυτης]{.greek-omitted} [αυτου]{.greek-added} της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν με αιτησης δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.corr} [τη]{.corr} [[μητρι]{.greek-abbr}]{.corr} [αυτης]{.corr} [τι]{.corr} [αιτησομαι]{.corr} [η]{.corr} [δε]{.corr} [ειπεν]{.corr} [την]{.corr} [κεφαλην]{.corr} [ιωαννου]{.greek-omitted} [[[ιω]{.greek-abbr}]{.corr}]{.greek-added} [του]{.corr} [βαπτιστου]{.corr}[6:24]{.aside}

[και]{.corr} [εισελθουσα]{.corr} ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα [μοι]{.greek-omitted} [μη]{.greek-added} δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν [μνημειω]{.greek-omitted} [μνημειον]{.greek-added}[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

κ[αι]{.greek-supplied} ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυσασθαι]{.greek-added} [αναπαυεσθε]{.greek-omitted} [[αναπαυσασθε]{.corr}]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

κ[α]{.unclear}[ι]{.greek-supplied} [ε]{.greek-supplied}ξελθων ειδεν ο [ιησους]{.greek-abbr} [οχλον]{.greek-added} πολυν [οχλον]{.greek-omitted} και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μ[η]{.unclear} [εχοντα]{.greek-supplied} ποιμενα και ηρξατο διδασκειν αυτο[υ]{.unclear}ς πολλα[6:34]{.aside}

και ηδη [πολλων]{.greek-added} [ωρας]{.greek-omitted} [πολλης]{.greek-omitted} [γενομενης]{.greek-omitted} [γενομενων]{.greek-added} προσελθοντες αυτ[ω]{.unclear} [οι]{.greek-supplied} μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτου[ς]{.unclear} [ι]{.greek-supplied}να απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις αρτους τι γαρ φ[αγω]{.greek-supplied}σιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν [αυτω]{.greek-omitted} [αυτοις]{.greek-added} απ[ε]{.unclear}[λθοντες]{.greek-supplied} αγορασωμεν δηναριων [διακοσιων]{.greek-omitted} [[σ]{.greek-abbr}]{.greek-added} αρτους και δωμεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρ[τ]{.unclear}[ους]{.greek-supplied} εχετε υπαγετε και ιδετε και γνοντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλι[ν]{.unclear}[αι]{.greek-supplied} παντας συμποσι[α]{.unclear} συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι [αν]{.unclear}[α]{.greek-supplied} [εκατον]{.greek-omitted} [[[ρ]{.greek-supplied}]{.greek-abbr}]{.greek-added} και ανα [πεντηκοντα]{.greek-omitted} [[ν]{.greek-abbr}]{.greek-added}[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ηυλογ[ησ]{.unclear}εν]{.greek-added} [και]{.greek-supplied} κατεκλασεν τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασ[θ]{.unclear}[ησαν]{.greek-supplied}[6:42]{.aside}

και ηραν [κλασματων]{.greek-omitted} [κλασματα]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγον[τες]{.greek-supplied} τους αρτους [πεντακισχιλιοι]{.greek-omitted} [πεντακισχιλι]{.greek-added} ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βησθαιδα]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν [εις]{.greek-omitted} [προς]{.greek-added} το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν [τω]{.greek-added} μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω [ελαυνην]{.greek-added} [ελαυνειν]{.corr} ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους [περι]{.greek-added} [παντων]{.greek-added} [περιπατων]{.corr} επι της θαλασσης [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

[και]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [περιπατουντα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων [εκ]{.greek-omitted} [απο]{.greek-added} του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον[6:54]{.aside}

[περιδραμοντες]{.greek-omitted} [παραδραμοντες]{.greek-added} ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου [αν]{.greek-omitted} εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμ[ματεων]{.greek-supplied} ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των [[φ]{.unclear}α[ρισαι]{.unclear}ων]{.greek-added} [μαθητων]{.corr} αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανι[π]{.unclear}[τοις]{.greek-supplied} εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγ[μη]{.greek-supplied} [νιψωνται]{.greek-omitted} [νιψωσι]{.greek-added} τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και απο αγορα[ς]{.unclear} εαν μη βαπτισωνται ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν α παρελαβον κρατειν [βαπτισμους]{.greek-omitted} [βαπτισμον]{.greek-added} ποτ[ηρι]{.greek-supplied}ων και ξεστων και [χαλκιων]{.greek-omitted} [χαλκης]{.greek-added} και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και [οι]{.greek-omitted} γραμματεις δ[ια]{.greek-supplied} τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την παραδοσιν των πρεσβυτερων [αλλα]{.greek-omitted} [αλλ]{.greek-added} ανιπ[τ]{.unclear}[οις]{.greek-supplied} χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι [ημων]{.greek-added} [υμων]{.corr} των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα [πολλα]{.greek-added} παρομοια [τοιαυτα]{.greek-omitted} [πολλα]{.greek-omitted} ποιειτε[7:8]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων [τη]{.unclear}ρησητε[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δ[ω]{.unclear}[ρον]{.greek-supplied} [ο]{.greek-supplied} εαν εξ εμου [ωφεληθης]{.greek-omitted} [ωφεληθη]{.greek-added}[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} [αυτου]{.greek-omitted}[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και παρομοια τοιαυτ[α]{.unclear} πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις [ακουετε]{.greek-omitted} [ακου[σατε]{.greek-supplied}]{.greek-added} [μου]{.greek-supplied} παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσα[ι]{.greek-supplied} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [εκπορευομενα]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [εκεινα]{.greek-omitted} [εστιν]{.greek-omitted} [τα]{.greek-omitted} [κοινουντα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[7:15]{.aside}

[ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [εξωθεν]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εισπορευομενον]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted} αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15 | instance no. 2]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} [εκπορευομενον]{.greek-omitted} [πορευομενον]{.greek-added} εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος ασελγεια οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

[ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [τα]{.greek-omitted} πονηρα εσωθεν [πορευονται]{.greek-added} [εκπορευεται]{.corr} και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκε[ι]{.unclear}θεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις [την]{.greek-added} οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα [δε]{.greek-added} [γαρ]{.corr} γυνη περι αυτου ης [ηχεν]{.greek-added} [ειχεν]{.greek-omitted} [[ειχε]{.corr}]{.greek-added} το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συρα]{.greek-added} [φονικησα]{.greek-added} [[συρα]{.corr}]{.greek-added} [[φοινικησα]{.corr}]{.greek-added} τω γενει και [ηρωτησ[ε]{.unclear}ν]{.greek-added} [ηρωτα]{.corr} αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εκ της θυγατρος [αυτου]{.greek-added} [αυτης]{.corr}[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα [κ[―]{.gap}]{.greek-added} [ου]{.corr} [γαρ]{.corr} καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν [και]{.greek-added} [βαλειν]{.greek-added} τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των [ψυχιων]{.greek-added} [ψιχιων]{.corr} των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος ηλθεν προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων [και]{.greek-added} δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον [μογγιλαλον]{.greek-omitted} [μογιλαλον]{.greek-added} και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν εβ[α]{.unclear}λεν τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο εστιν διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και [ελ[η]{.unclear}θη]{.greek-added} [ελυθη]{.corr} ο δεσμος της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε [αυτος]{.greek-omitted} αυτοις [διεστελλετο]{.greek-omitted} [διεστειλε]{.greek-added} μαλλον περισσοτερον [εκηρυσσον]{.greek-omitted} [εκηρυττον]{.greek-added}[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφ[ους]{.unclear} [ποιει[ν]{.unclear}]{.greek-added} [ποιει]{.corr} ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις παμπολλου οχλου οντος και μη εχοντων τι φαγωσιν προσκαλεσαμενος ο [ιησους]{.greek-abbr} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

[σπλαγχνιζομαι]{.greek-omitted} [σπλαχνιζομαι]{.greek-added} επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} τρεις [ημερας]{.greek-added} [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους [νηστεις]{.greek-omitted} [νηστις]{.greek-added} εις [τον]{.greek-added} οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκουσι]{.greek-added}[8:3]{.aside}

και απεκριθησαν [αυτω]{.greek-omitted} οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε [επ]{.greek-added} [ερημιας]{.greek-added} χορτασαι αρτων [επ]{.greek-omitted} [ερημιας]{.greek-omitted}[8:4]{.aside}

και επηρωτα αυτους ποσους [εχεται]{.greek-added} [εχετε]{.corr} αρτους οι δε ειπον επτα[8:5]{.aside}

και παρηγγειλεν τω οχλω αναπεσειν επι της γης και λαβων τους [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αρτους [και]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και [παρεθηκαν]{.greek-omitted} [παρεθηκε]{.greek-added} τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθηναι]{.greek-added} [παραθειναι]{.corr} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισσευματα [κλασματων]{.greek-omitted} [κλασματα]{.greek-added} [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες [ως]{.greek-omitted} [ωσει]{.greek-added} τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και ευθεως εμβας εις [το]{.greek-omitted} πλοιον μετα των μαθητων αυτου ηλθεν εις τα [ερη]{.greek-added} [μερη]{.corr} [δαλμανουθα]{.greek-omitted} [σαλμανουθα]{.greek-added}[8:10]{.aside}

και εξηλθον οι [φαρισαιοι]{.greek-omitted} [μαφαρισαιοι]{.greek-added} και [ηρξατο]{.greek-added} [ηρξαντο]{.corr} συζητειν αυτω ζητουντες [αυτω]{.greek-added} [παρ]{.greek-omitted} [αυτου]{.greek-omitted} [σημειον]{.greek-omitted} [σημεια]{.greek-added} απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστενα[ξ]{.unclear}[ας]{.greek-supplied} τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετ[ο]{.unclear} αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης [ηρωδου]{.greek-omitted} [ηρωδιανων]{.greek-added}[8:15]{.aside}

και [διελογιζοντο]{.greek-omitted} [ελογιζοντο]{.greek-added} προς αλληλους λεγοντες [οτι]{.greek-omitted} αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε [ετι]{.greek-omitted} [αλλ]{.greek-added} [[ο]{.unclear}τι]{.greek-added} πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και [ου]{.greek-supplied} μνημονευετε[8:18]{.aside}

[οτε]{.greek-omitted} [οτι]{.greek-added} τους [πεντε]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} αρτους [εκλασα]{.greek-omitted} [εκλασαν]{.greek-added} εις [τε]{.greek-added} [τους]{.corr} [πεντακισχιλιους]{.greek-omitted} [[εκισχιλιους]{.corr}]{.greek-added} ποσους κοφινους [κλασματων]{.greek-added} πληρεις [κλασματων]{.greek-omitted} ηρ[α]{.unclear}[τε]{.greek-supplied} λεγουσιν αυτω [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα [κλασματων]{.greek-omitted} ηρατε οι δε ειπον [επτα]{.greek-omitted} [[αυτω]{.greek-supplied}]{.greek-added} [[ζ]{.greek-abbr}]{.greek-added}[8:20]{.aside}

και ελεγεν αυτοις πως ου συνιετε[8:21]{.aside}

κα[ι]{.greek-supplied} ερχ[ε]{.unclear}ται εις [βηθσαιδαν]{.greek-omitted} [βησθαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψητα[ι]{.greek-supplied}[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομμ[α]{.unclear}τα αυτου επιθεις τας χειρας αυτω επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και [επ]{.unclear}[οι]{.greek-supplied}ησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τηλαυγως [απαντας]{.greek-omitted} [απαντα]{.greek-added}[8:25]{.aside}

και απεστειλεν αυτον εις τον οι[κον]{.greek-supplied} [αυτου]{.greek-omitted} [λεγων]{.greek-omitted} [μηδε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [κωμην]{.greek-omitted} [εισελθης]{.greek-omitted} [μηδε]{.greek-omitted} [ειπης]{.greek-omitted} [τινι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [κωμη]{.greek-omitted}[8:26]{.aside}

[και]{.greek-omitted} [απεστειλεν]{.greek-omitted} [αυτον]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26 | instance no. 2]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με [λεγουσι]{.greek-added} [λεγουσιν]{.corr} οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε [ο]{.greek-omitted} πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγουσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και των αρχιερεων και [των]{.greek-omitted} γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν [αυτ[―]{.gap}]{.greek-added} [αυτω]{.corr}[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [ως]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθει[τω]{.unclear} [μοι]{.greek-supplied}[8:34]{.aside}

ος [γαρ]{.greek-omitted} [δ]{.greek-added} α[ν]{.unclear} θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την [εαυτου]{.corr} ψυχην ενεκεν εμ[ου]{.unclear} και του ευαγγελιου ουτος σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [[ανθρωπον]{.greek-abbr}]{.greek-added} [[ανθρωπον]{.greek-abbr}]{.corr} εαν κερδηση τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} [επεσχυθη]{.greek-added} [επαισχυνθη]{.corr} με και τους εμ[ο]{.unclear}υς λογους εν [τη]{.unclear} γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο [υιος]{.greek-abbr} του [[ανθρωπου]{.greek-abbr}]{.corr} επαισχυνθησεται αυτον [ο]{.unclear}τ[αν]{.greek-supplied} [ελθη]{.greek-omitted} [ελθοι]{.greek-added} εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των [α]{.unclear}γιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν [οτι]{.greek-supplied} [εισιν]{.greek-omitted} [[ει]{.greek-supplied}σι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} [εληλυθυιαν]{.greek-omitted} [εληλυθυια]{.greek-added} εν δυναμει[9:1]{.aside}

και μεθ ημερας [εξ]{.greek-omitted} [[ϛ]{.greek-abbr}]{.greek-added} παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν ως χιων οια γναφευς επι της γης ου δυναται λευκαναι[9:3]{.aside}

και [ωφθη]{.greek-omitted} [ωφθης]{.greek-added} αυτοις ηλιας συν [μωση]{.greek-omitted} [μωσει]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις [ο]{.greek-omitted} πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυση]{.greek-added} μιαν και [ηλια]{.greek-omitted} [ηλιαν]{.greek-added} μιαν[9:5]{.aside}

ου γαρ [ηδει]{.greek-omitted} [ηδη]{.greek-added} τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και ηλθεν φωνη εκ της νεφελης [λ[―]{.gap}]{.greek-added} [ουτος]{.corr} εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγησονται]{.greek-added} [διηγησωνται]{.corr} α ειδον ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκ[ρω]{.unclear}[ν]{.greek-supplied} αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματει[ς]{.greek-supplied} οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτ[ο]{.unclear}[ν]{.greek-supplied} αποκαθιστα παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδεν[ω]{.unclear}[θη]{.greek-supplied}[9:12]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} [εγω]{.greek-added} λεγω υμιν οτι και ηλιας εληλυθεν και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ [αυτον]{.greek-supplied}[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυ[ν]{.unclear} περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και επηρωτησεν τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα πνευμα αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα [αυτο]{.greek-omitted} εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτε προς [[η]{.unclear}μας]{.greek-added} [υμας]{.corr} εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το πνευμα εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και επηρωτησεν τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις το πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του [παιδιου]{.greek-omitted} [παιδος]{.greek-added} μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} βοηθει μου τη [απιστια]{.greek-omitted} [απιστ[η]{.unclear}α]{.greek-added}[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [συντρεχει]{.greek-added} [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσ[ω]{.unclear} εξελθε εξ αυτου και μηκετι εισελθης εις [αυτον]{.greek-omitted} [αυτο]{.greek-added}[9:25]{.aside}

και [κραξαν]{.greek-omitted} [κραξας]{.greek-added} και πολλα [σπαραξαν]{.greek-omitted} [σπαραξας]{.greek-added} αυτον εξηλθεν και εγενετο [ει]{.greek-added} [ωσει]{.corr} νεκρος ωστε πολλους λεγειν οτι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και [εισελθοντων]{.greek-added} [αυτ[ω]{.unclear}ν]{.greek-added} [εισελθοντα]{.corr} [αυτον]{.corr} εις οικον οι μαθηται αυτου [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον κατ ιδιαν οτι [δια]{.greek-added} [τ[ι]{.unclear}]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος [εν]{.greek-omitted} [ουδενι]{.greek-omitted} [ουδεν]{.greek-added} δυναται [εξελθειν]{.greek-omitted} [διεξελθ[ειν]{.greek-supplied}]{.greek-added} ει μη εν προσευχη και νηστεια[9:29]{.aside}

και [εκειθεν]{.greek-omitted} [εξηλθον]{.greek-added} εξελθοντες παρεπορευοντο δια της γαλι[λαιας]{.greek-supplied} και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τ[ρ]{.unclear}[ιτη]{.greek-supplied} ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβο[υν]{.unclear}το [επερωτησαι]{.greek-added} αυτον [επερωτησαι]{.greek-omitted}[9:32]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους [διελογιζεσθε]{.greek-omitted} [δι[α]{.unclear}λογιζεσθε]{.greek-added}[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

και [κ]{.unclear}αθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι εστ[αι]{.unclear} [πα]{.unclear}[ν]{.greek-supplied}[τ]{.unclear}ων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted}[9:36]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [παιδιον]{.greek-omitted} [εστησεν]{.greek-omitted} [αυτο]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εναγκαλισαμενος]{.greek-omitted} [αυτο]{.greek-omitted} ειπεν αυτοις[9:36 | instance no. 2]{.aside}

ος εαν εν [τω]{.greek-added} [των]{.corr} τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε [δεχετε]{.greek-added} [δεχεται]{.corr} και ος εαν εμε δεξηται ουκ εμε [δ[η]{.unclear}χετε]{.greek-added} [δεχεται]{.corr} αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε αυτω [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} λεγων διδασκαλε ειδομεν τινα [εν]{.greek-added} τω ονοματι σου [εκ[―]{.gap}αλλοντα]{.greek-added} [εκβαλλοντα]{.corr} δαιμονια ος [ουκ]{.greek-omitted} ακολουθει ημιν και εκωλυσαμεν αυτον οτι [ετι]{.greek-added} ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ [κακολογησε]{.greek-added} [κακολογησαι]{.corr} με[9:39]{.aside}

ος γαρ ουκ [εστι]{.greek-added} [καθ]{.greek-added} [ημων]{.greek-added} [υπερ]{.greek-added} [ημων]{.greek-added} εστιν [καθ]{.greek-omitted} [υμων]{.greek-omitted} [υπερ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted}[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} [εστε]{.greek-omitted} [εσται]{.greek-added} αμην λεγω υμιν [οτι]{.greek-added} ου μη απολεσ[η]{.unclear} [[απολεσει]{.corr}]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων εις εμε καλον εστιν [αυτω]{.greek-omitted} μαλλον ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιση]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας [ε]{.unclear}χοντα απελθειν εις [την]{.corr} γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [σοι]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι [βληθηναι]{.greek-added} εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} [του]{.greek-added} [πυρος]{.greek-added} [εις]{.corr} [το]{.corr} [πυρ]{.corr} [το]{.corr} [ασβεστον]{.corr}[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ [ου]{.unclear} [σ]{.unclear}βεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε [εκβαλε]{.greek-omitted} [εκβαλον]{.greek-added} αυτον καλον σοι εστιν [[εστι]{.corr}]{.greek-added} μονοφθαλμον ει[σ]{.unclear}[ελθειν]{.greek-supplied} εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις [τ[ην]{.unclear}]{.corr} [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} του πυρος[9:47]{.aside}

οπου ο σκωλ[ηξ]{.unclear} [αυτων]{.greek-supplied} [ου]{.greek-supplied} [τε]{.greek-supplied}λευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλι[σ]{.unclear}θη[σε]{.unclear}τ[α]{.unclear}[ι]{.greek-supplied}[9:49]{.aside}

[κα]{.greek-supplied}λον [δε]{.greek-added} το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο [αρτυσεται]{.greek-added} [αρτυσετε]{.corr} εχετε εν εαυτοις αλα[ς]{.unclear} [και]{.greek-supplied} [ειρηνευεται]{.greek-added} [ειρηνευετε]{.corr} εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας [δια]{.greek-omitted} [εις]{.greek-added} [του]{.greek-omitted} [το]{.greek-added} περαν του ιο[ρ]{.unclear}δανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο μωσης [[μωυσης]{.corr}]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} επετρεψεν [[επετρεψε]{.corr}]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} [μια]{.greek-added} [μια]{.corr} [σαρξ]{.corr}[10:8]{.aside}

ο [ουν]{.greek-omitted} [γουν]{.greek-added} ο [θεος]{.greek-abbr} [συνεζευξε]{.greek-added} [συνεζευξεν]{.corr} [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [τουτου]{.greek-added} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επ]{.greek-supplied}ηρωτησαν [αυτων]{.greek-added} [αυτον]{.corr}[10:10]{.aside}

και λεγει αυτοις ος εαν [απολυση]{.greek-omitted} [απολυσας]{.greek-added} την γυναικα αυτου και γαμηση αλλην μοιχαται [επ]{.greek-supplied} αυτην[10:11]{.aside}

και εαν γυνη απολυσ[η]{.unclear} τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις [προσφερουσιν]{.greek-omitted} [προφερουσιν]{.greek-added}[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηλογησεν]{.greek-added} [αυτα]{.greek-omitted} [αυτο]{.greek-added}[10:16]{.aside}

και εκπορευομενου αυτου εις οδ[ον]{.greek-supplied} προσδραμων εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιων[ιον]{.greek-supplied} [κληρονομησω]{.greek-omitted}[10:17]{.aside}

[και]{.greek-omitted} [εκπορευομενου]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [οδον]{.greek-omitted} [προσδραμων]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γονυπετησας]{.greek-omitted} [αυτον]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [διδασκαλε]{.greek-omitted} [αγαθε]{.greek-omitted} [τι]{.greek-omitted} [ποιησω]{.greek-omitted} [ινα]{.greek-omitted} [ζωην]{.greek-omitted} [αιωνιον]{.greek-omitted} κληρονομησω[10:17 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [[ψευδομαρτυρησεις]{.corr}]{.greek-added} [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν [αυτ[ω]{.unclear}]{.greek-added} [αυτον]{.corr} και ειπεν αυτω εν σοι υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και [εξεις]{.greek-omitted} [εξης]{.greek-added} θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε [μαθηται]{.greek-omitted} [εθαμβουντο]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [λογοις]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [παλιν]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [τεκνα]{.greek-omitted} [πως]{.greek-omitted} [δυσκολον]{.greek-omitted} [εστιν]{.greek-omitted} [τους]{.greek-omitted} [πεποιθοτας]{.greek-omitted} [επι]{.greek-omitted} [χρημασιν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισελθειν]{.greek-omitted}[10:24]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24 | instance no. 2]{.aside}

[ο[ι]{.unclear}]{.greek-added} [[δε]{.unclear}]{.greek-added} [[περι]{.unclear}[σσως]{.greek-supplied}]{.greek-added} [[ε]{.greek-supplied}ξ[επ]{.greek-supplied}λ[ησσοντο]{.greek-supplied}]{.greek-added} [λ[ε]{.unclear}]{.greek-added} [ευκοπωτερον]{.greek-omitted} [[ευκοποτερον]{.corr}]{.greek-added} [εστιν]{.greek-omitted} [[εστι]{.corr}]{.greek-added} [καμηλον]{.corr} [δια]{.corr} [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} [τουτο]{.greek-added} αδυ[ν]{.unclear}[ατον]{.greek-supplied} αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα εστιν παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [αμην]{.greek-added} [αμ[ι]{.unclear}ν]{.greek-added} [αμην]{.corr} λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα [η]{.corr} [τεκνα]{.corr} η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα ν[υν]{.unclear} εν τω καιρω τουτω [οικιας]{.greek-omitted} [οικους]{.greek-added} και αδελφους και αδελφας και [μητερας]{.greek-omitted} [γυναικας]{.greek-added} και τεκνα [και]{.greek-added} [[μητερας]{.greek-abbr}]{.greek-added} και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω [αναβ[η]{.unclear}νοντες]{.greek-added} [αναβαινοντες]{.corr} εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [λεγειν]{.greek-added} αυτοις [λεγειν]{.greek-omitted} τα μελλοντα [αυτω]{.greek-omitted} [αυτοις]{.greek-added} συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο [[ιησους]{.greek-abbr}]{.greek-added} [[υιος]{.greek-abbr}]{.corr} του [ανθρωπου]{.greek-abbr} [παραδοθησεται]{.greek-omitted} [παραδιδοται]{.greek-added} τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και εμπαιξουσιν [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} αυτω και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και [[ιω]{.greek-abbr}]{.greek-added} [ιωαννης]{.greek-omitted} [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν [ινα]{.greek-omitted} ο εαν [αιτησωμεν]{.greek-omitted} [αιτησομεν]{.greek-added} ποιησης ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε [π[οι]{.unclear}ειν]{.greek-added} [πιειν]{.corr} το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το [μεν]{.greek-omitted} [ποτηριον]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [πινω]{.greek-omitted} [πιεσθε]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [βαπτισμα]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [βαπτιζομαι]{.greek-omitted} [βαπτισθησεσθε]{.greek-omitted}[10:39]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [αυτω]{.greek-omitted} [δυναμεθα]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [το]{.greek-omitted} μεν ποτηριον ο εγω πινω πιεσθε [και]{.corr} το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησθε]{.greek-added}[10:39 | instance no. 2]{.aside}

το δε καθισαι ε[κ]{.unclear} [δε]{.unclear}ξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν [εμων]{.greek-added} [εμον]{.corr} δουναι αλλ οις [ητοιμασθαι]{.greek-added} [ητοιμασται]{.corr}[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκ[α]{.unclear}λεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και ο[ι]{.unclear} μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη [γενεσθε]{.greek-added} [[γενεσθαι]{.corr}]{.greek-added} υμων [γενεσθαι]{.greek-omitted} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και [ερχετε]{.greek-added} [ερχονται]{.greek-omitted} [[ερχεται]{.corr}]{.greek-added} εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν [υιε]{.greek-omitted} [[υιος]{.greek-abbr}]{.greek-added} [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-added} [αυτον]{.corr} φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει [σαι]{.greek-added} [σε]{.corr}[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτω]{.greek-omitted} [ραβουνι]{.greek-added} [ραββουνι]{.corr} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις ιερουσαλημ εις βηθσφαγη και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην [ευρησεται]{.greek-added} [ευρησετε]{.corr} πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθ[η]{.unclear}κε]{.greek-added} [κεκαθικεν]{.greek-omitted} [[κεκαθικε]{.corr}]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και [εαν]{.greek-omitted} [αν]{.greek-added} τις υμιν ειπη τι ποιειτε [τουτο]{.greek-omitted} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων [ελεγον]{.greek-omitted} [λεγουσιν]{.greek-added} αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο [ημιν]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτων]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις [την]{.greek-omitted} [τον]{.greek-added} οδον αλλοι δε [στοιβαδας]{.greek-omitted} εκοπτον [στιβαδας]{.greek-added} εκ των δενδρων και εστρωννυον [[εν]{.unclear}]{.greek-added} [τη]{.greek-added} [οδ[ω]{.unclear}]{.greek-added} [εις]{.corr} [την]{.corr} [οδον]{.corr}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα [ο]{.greek-omitted} [ιησους]{.greek-omitted} και εις το ιερον και περιβλεψαμ[ενος]{.unclear} [παντα]{.greek-omitted} [[π]{.unclear}[αν]{.greek-supplied}τας]{.greek-added} [οψ]{.unclear}ιας ηδη ουσης [της]{.greek-omitted} [ωρας]{.greek-omitted} εξηλθεν εις βηθανιαν μετα των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο [της]{.greek-added} βηθαν[ιας]{.unclear} [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων [συκην]{.corr} μακροθεν εχουσαν φυλλα ηλθεν [ινα]{.greek-added} [ει]{.greek-omitted} [αρα]{.greek-omitted} ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν [ει]{.greek-supplied} μη φυλλα [ου]{.unclear} γαρ [ην]{.unclear} καιρος συκων[11:13]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [αυτ[οι]{.unclear}ς]{.greek-added} [αυτη]{.greek-omitted} [[αυτης]{.corr}]{.greek-added} μηκετι εκ σου [καρπος]{.greek-added} [γενηται]{.greek-added} εις τον αιωνα [μηδεις]{.greek-omitted} [μηδεν]{.greek-added} καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και [ερχονται]{.greek-omitted} [ερχεται]{.greek-added} εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας καθεδρας των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις [διενεγκη]{.greek-omitted} [ενεγκη]{.greek-added} σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται [οτι]{.greek-omitted} ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [παρα]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε [αυτον]{.greek-omitted} [αυτων]{.greek-added} σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι γραμματεις και οι αρχιερεις και εζητουν πως [αυτον]{.greek-omitted} απολεσ[ω]{.unclear}σιν [[απολεσουσιν]{.corr}]{.greek-added} εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη [δι[ω]{.unclear}]{.greek-added} [διδαχη]{.corr} αυτου[11:18]{.aside}

και οτε [εγενετο]{.greek-added} οψε [εγενετο]{.greek-omitted} εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι [παρα]{.greek-added} [παραπορευομενοι]{.greek-omitted} [ειδον]{.greek-omitted} [την]{.greek-omitted} [συκην]{.greek-omitted} [εξηραμμενην]{.greek-omitted} [εκ]{.greek-omitted} [ριζων]{.greek-omitted}[11:20]{.aside}

[και]{.greek-omitted} [πρωι]{.greek-omitted} [παραπορευομενοι]{.greek-omitted} [πορευομενοι]{.greek-added} ειδον την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20 | instance no. 2]{.aside}

και αναμνησθεις ο πετρος λεγει αυτ[ω]{.greek-supplied} ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμ[η]{.unclear}[ν]{.greek-supplied} γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακ[ρ]{.unclear}[ι]{.greek-supplied}[θ]{.unclear}η εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι [α]{.greek-omitted} [εαν]{.greek-added} λεγει [γ[η]{.unclear}νεται]{.greek-added} [γινεται]{.corr} εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν [αιτησησθε]{.greek-added} προσευχομενοι [αιτησθε]{.greek-omitted} πιστευετε οτι λαμβ[α]{.unclear}[νετε]{.greek-supplied} και εσται υμιν[11:24]{.aside}

και οταν στηκ[η]{.unclear}τε [[στηκειτε]{.corr}]{.greek-added} προσευχομενοι αφιετε [ει]{.greek-omitted} [τι]{.greek-omitted} εχετε κατα τινος ινα και [ο]{.unclear} [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο εν τοις [ουρανοις]{.greek-abbr} [αφησει]{.greek-added} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} τα παραπτ[ω]{.unclear}ματα [ημων]{.greek-added} [υμων]{.corr}[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} [ημων]{.greek-added} [[υ]{.unclear}μων]{.corr} ο εν τοις [ουρανοις]{.greek-abbr} [αφησει]{.greek-omitted} [αφισει]{.greek-added} τα [παραπτω[―]{.gap}ατα]{.greek-added} [παραπτωματα]{.corr} υμων[11:26]{.aside}

και ερχονται παλιν εις [ιεροσολυμα]{.greek-omitted} [ιροσολυμα]{.greek-added} και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και [τις]{.greek-omitted} [τι]{.greek-added} σοι την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας και εγω ενα [λογων]{.greek-added} [λογον]{.corr} και απ[ο]{.unclear}κριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ [ουρανου]{.greek-abbr} ην η εξ α[ν]{.unclear}θρωπων [αποκριθητε]{.greek-omitted} [μοι]{.greek-omitted}[11:30]{.aside}

και ελογιζοντο προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ ειχον τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια [εξου]{.greek-added} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιω]{.greek-omitted}[11:33]{.aside}

[σια]{.greek-added} [και]{.greek-omitted} [αποκριθεντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [ουκ]{.greek-omitted} [οιδαμεν]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ουδε]{.greek-omitted} [εγω]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} [εξουσια]{.greek-omitted} ταυτα ποιω[11:33 | instance no. 2]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και περιεθηκεν φραγμον και ωρυξεν υποληνιον και ωκοδομησεν πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και απεστειλεν προς τους γεωργους τω καιρω δουλον ινα [παρα]{.greek-omitted} [περι]{.greek-added} των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν [αυτον]{.greek-added} και απεστειλαν κενον[12:3]{.aside}

και παλιν απεστειλεν προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} εκεφαλαιωσαν και απεστειλαν [ητιμωμενον]{.greek-omitted} [ητοιμωμενον]{.greek-added}[12:4]{.aside}

και παλιν αλλον απεστειλεν κακεινον απεκτειναν και πολλους [και]{.greek-added} αλλους τους μεν [δεροντες]{.greek-omitted} [δεροντας]{.greek-added} τους δε [αποκτενοντες]{.greek-omitted} [αποκτενοντας]{.greek-added}[12:5]{.aside}

ετι ουν ενα [υιον]{.greek-abbr} [εχων]{.greek-omitted} [εχον]{.greek-added} αγαπητον αυτου απεστειλεν και αυτον προς αυτους εσχατον λεγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [οτι]{.greek-omitted} ουτος εστιν ο κληρονομος δευτε [αποκτεινωμεν]{.greek-omitted} [αποκτεινομεν]{.greek-added} αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και [απολεση]{.greek-added} [απολεσει]{.corr} τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

[ουδ[―]{.gap}]{.greek-added} [ουδε]{.corr} την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος [εγενηθη]{.greek-omitted} [εγεννηθη]{.greek-added} εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} και [α]{.greek-added} [αφεντες]{.greek-omitted} [αυτον]{.greek-omitted} [απηλθον]{.greek-omitted}[12:12]{.aside}

[και]{.greek-omitted} [εζητουν]{.greek-omitted} [αυτον]{.greek-omitted} [κρατησαι]{.greek-omitted} [και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [εγνωσαν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [ειπεν]{.greek-omitted} [και]{.greek-omitted} [αφεντες]{.greek-omitted} [φεντες]{.greek-added} αυτον απηλθον[12:12 | instance no. 2]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} [λογον]{.greek-added} [λογω]{.corr}[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την [υποκρισιν]{.greek-omitted} [αποκρισιν]{.greek-added} ειπεν αυτοις [τι]{.greek-omitted} [με]{.greek-omitted} [πειραζετε]{.greek-omitted} [φερετε]{.greek-omitted} [μοι]{.greek-omitted} [δηναριον]{.greek-omitted} [ινα]{.greek-omitted} [ιδω]{.greek-omitted}[12:15]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ηνεγκαν]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και εξαναστη[σ]{.unclear}η σπερμα τω αδελφω αυτου[12:19]{.aside}

[επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνη[σκ]{.unclear}ων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο [δευτερος]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added} ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη ανα[στασει]{.unclear} οταν αναστω[σ]{.unclear}ιν τινος [αυτων]{.greek-omitted} εσται γυνη οι γαρ επτα ε[σ]{.unclear}χον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτο[ι]{.unclear}ς [ου]{.greek-omitted} δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν [ουτε]{.greek-omitted} [γαμουσιν]{.greek-omitted} [ουτε]{.greek-omitted} [γαμισκονται]{.greek-omitted} [αλλ]{.greek-omitted} [εισιν]{.greek-omitted} [ως]{.greek-omitted} [αγγελοι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted}[12:25]{.aside}

[οταν]{.greek-omitted} [γαρ]{.greek-omitted} [εκ]{.greek-omitted} [νεκρων]{.greek-omitted} [αναστωσιν]{.greek-omitted} ουτε γαμουσιν ουτε γαμισκονται αλλ [εισιν]{.greek-omitted} [εισι]{.greek-added} ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25 | instance no. 2]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω μωσεως επι [του]{.greek-omitted} [της]{.greek-added} βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και [ο]{.greek-omitted} [θεος]{.greek-omitted} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-abbr} ζωντων υμεις ουν [πολυ]{.greek-omitted} πλανασθε[12:27]{.aside}

και προσελθων [παλιν]{.greek-added} εις των γραμματεων ακουσας αυτων συζητουντων ειδως οτι καλως αυτοις απεκριθη [επηρωτησεν]{.greek-omitted} [επηρωτα]{.greek-added} αυτον ποια εστιν [πρωτη]{.greek-omitted} παντων εντολη [μειζων]{.greek-added}[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} [απεκριθη]{.greek-omitted} [ειπεν]{.greek-added} αυτω οτι [πρωτη]{.greek-omitted} [πρωτον]{.greek-added} παντων των εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της [διανοια]{.greek-added} [διανοιας]{.corr} σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια αυτη [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων [εντολη]{.greek-added} αλλη [εντολη]{.greek-omitted} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων [αυτον]{.greek-omitted} οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι [ουχι]{.greek-added} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [υιος]{.greek-abbr} εστιν [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου εστιν και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και πρωτοκλισιας εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και [προφασ[η]{.unclear}]{.greek-added} [προφασει]{.corr} μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμ[α]{.unclear}[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλλε]{.greek-added} λεπτα δυο ο εστιν κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισευοντος]{.greek-added} αυτοις εβαλον [[εβαλλον]{.corr}]{.greek-added} αυτη δε εκ της υστερησεως [αυτης]{.greek-omitted} παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και [εκπορευομμενων]{.greek-added} [αυτ[ων]{.unclear}]{.greek-added} [εκπορευομενου]{.corr} [αυτου]{.corr} εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι λιθω ος ου μη [καταλη]{.greek-added} [καταλυθη]{.corr}[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} πετρος και ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται [επι]{.greek-omitted} [εν]{.greek-added} τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλαν[η]{.unclear}σουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και [βασι[―]{.gap}λεια]{.greek-added} [βασιλεια]{.corr} επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται [λιμοι]{.greek-omitted} [λοιμοι]{.greek-added} και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} [γαρ]{.greek-added} ωδινων ταυτα[13:8]{.aside}

βλεπετε δε [υμεις]{.corr} εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι [γεμονων]{.greek-added} [ηγεμονων]{.corr} και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη προμεριμνατε τι λαλησητε μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ [εσται]{.greek-added} [εστε]{.corr} υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

κα[ι]{.unclear} εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το [βλελυγμα]{.greek-added} [βδελυγμα]{.corr} της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο αναγινωσκων [νοητω]{.greek-added} [νοειτω]{.corr} τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

[και]{.greek-omitted} ο [δε]{.greek-added} εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη [γεν[ο]{.unclear}ι]{.greek-added} [γενηται]{.corr} η φυγη [υμων]{.greek-omitted} [ημων]{.greek-added} χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου γεγονεν [τοιαυτη]{.greek-omitted} απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους [κολοβω[―]{.gap}]{.greek-added} [[εκολοβωσεν]{.corr}]{.greek-added} ους εξελεξατο [εκολοβωσεν]{.greek-omitted} τας ημερας[13:20]{.aside}

τοτε εαν τις [υμιν]{.greek-omitted} [ημιν]{.greek-added} ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου [ουκ]{.greek-added} [ην]{.greek-added} [εκει]{.corr} μη πιστευ[ε]{.unclear}[τε]{.greek-supplied}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψ[ιν]{.unclear} εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος [αυτης]{.greek-omitted} [αυτοις]{.greek-added}[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} [εσονται]{.greek-omitted} εκπιπτοντες [εσωται]{.greek-added} και αι δυναμεις [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [αι]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως πολλης και δοξης[13:26]{.aside}

και [τοτε]{.greek-omitted} αποστελει τους αγγελους αυτου και επισυναξει τους [εκλεκτους]{.greek-omitted} [αγγελους]{.greek-added} αυτου εκ των τεσσαρων ανεμων απ ακρου [της]{.greek-added} γης εως [ακρου]{.greek-omitted} [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης [ηδη]{.greek-omitted} ο κλαδος απαλος γενηται και [εκφυη]{.greek-omitted} τα φυλλα [εκφυη]{.greek-added} γινωσκετε οτι [εγγυς]{.greek-omitted} το θερος [εγγυς]{.greek-added} εστιν[13:28]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [γεν[ο]{.unclear}ιτε]{.greek-added} [γενηται]{.corr}[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} [της]{.greek-added} ωρας [ουδεις]{.greek-omitted} [[ου[δ]{.greek-supplied}εν]{.corr}]{.greek-added} [οιδεν]{.corr} ουδε [οι]{.greek-omitted} αγγελοι οι εν [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε [αγρυπνιται]{.greek-added} [αγρυπνειτε]{.greek-omitted} [[αγρυπνιτε]{.corr}]{.greek-added} και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος [εστιν]{.greek-omitted} [εστι]{.greek-added}[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η μεσονυκτιου η αλεκτοροφωνιας η [πρωι]{.greek-omitted} [πρωιας]{.greek-added}[13:35]{.aside}

μη ελθων [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} [ευρη]{.greek-omitted} [ηυρη]{.greek-added} [υμας]{.greek-omitted} [ημας]{.greek-added} καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε τ[ο]{.unclear} πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις π[ω]{.unclear}[ς]{.greek-supplied} [αυτον]{.greek-omitted} εν δολω [αυτον]{.greek-added} [κρατησ[ω]{.unclear}σιν]{.greek-added} [κρατησαντες]{.corr} αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσ[τ]{.unclear}[αι]{.greek-supplied} του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτο[υ]{.greek-supplied} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες πρ[ο]{.unclear}[ς]{.greek-supplied} [αυτους]{.greek-added} [εαυτους]{.corr} και λεγοντες εις τι η απωλεια αυτη του μυρου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[14:4]{.aside}

ηδυνατο γαρ τουτο πραθηναι επ[α]{.unclear}[νω]{.greek-supplied} τριακοσιων δηναριων και δοθηναι [τοις]{.greek-omitted} πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} [εηπε]{.greek-added} [ειπεν]{.greek-omitted} [[ειπε]{.corr}]{.greek-added} αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον [ειργασατο]{.greek-omitted} [[η]{.unclear}[ρ]{.greek-supplied}γασατο]{.greek-added} εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε [αυτους]{.greek-omitted} [αυτο[ι]{.unclear}[ς]{.greek-supplied}]{.greek-added} ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

[ο]{.greek-omitted} [εσχεν]{.greek-omitted} [οπερ]{.greek-added} [γαρ]{.greek-added} αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι [μου]{.greek-omitted} το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν [οτι]{.greek-added} [οπου]{.corr} [εαν]{.greek-omitted} [[α]{.unclear}ν]{.greek-added} κηρυχθη το ευαγγελιον το[υτ]{.unclear}[ο]{.greek-supplied} εις [ο]{.unclear}λον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης εις των δωδεκα απηλθεν προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλατο]{.greek-added} [επηγγειλα[ν]{.unclear}το]{.corr} [αυτω]{.greek-omitted} [αυτων]{.greek-added} [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και [εζητει]{.greek-omitted} [εζητη]{.greek-added} πως [ευκαιρως]{.greek-omitted} [ηυκαιρως]{.greek-added} αυτον παραδω[14:11]{.aside}

και τη πρωτη [[ημερ]{.unclear}α]{.corr} των αζυμων [οτι]{.greek-added} [οτε]{.corr} το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα [φαγης]{.greek-omitted} [φαγεις]{.greek-added} το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και [απαντηση]{.greek-added} [απαντησει]{.corr} [ημιν]{.greek-added} [υμιν]{.corr} [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν [εισελθη]{.greek-omitted} [εισελθοι]{.greek-added} ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν [δειξει]{.greek-omitted} [δειξη]{.greek-added} [ανωγεον]{.greek-omitted} [ανωγαιον]{.greek-added} μεγα εστρωμενον [ετοιμον]{.greek-omitted} εκει ετοιμασατε [ημιν]{.greek-omitted} [υμιν]{.greek-added}[14:15]{.aside}

και [ε]{.unclear}[ξηλ]{.greek-supplied}θον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητ[οι]{.greek-supplied}μασαν το πασχα[14:16]{.aside}

[και]{.greek-omitted} οψιας [δε]{.greek-added} γενομενης [ερχετε]{.greek-added} [ερχεται]{.corr} μετα των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε η[ρ]{.unclear}ξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω [και]{.greek-omitted} [αλλος]{.greek-omitted} [μητι]{.greek-omitted} [εγω]{.greek-omitted}[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτ[οις]{.greek-supplied} εις εκ των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπ[α]{.unclear}[γει]{.greek-supplied} καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται κ[α]{.unclear}λον ην αυτω ει ουκ [αιγεννηθη]{.greek-added} [εγεννηθη]{.corr} ο [ανθρωπος]{.greek-abbr} [το[υ]{.unclear}]{.greek-added} [[ανθρωπου]{.greek-abbr}]{.greek-added} [εκεινος]{.corr}[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας εκλ[α]{.unclear}[σεν]{.greek-supplied} και εδωκεν αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις το[υ]{.unclear}το εστιν [το]{.greek-omitted} [αιμα]{.greek-omitted} [μου]{.greek-omitted} το της καινης διαθηκης το περι πολλων [ε]{.unclear}κχυνομενον[14:24]{.aside}

αμην λεγω υμιν ο[τι]{.unclear} [ουκετι]{.greek-omitted} [ου]{.corr} μη πιω εκ του [γενηματος]{.greek-omitted} [γεννηματος]{.greek-added} [τ[ου]{.unclear}]{.greek-added} [της]{.corr} αμπελου εως της ημερας εκεινης οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} πινω κα[ι]{.unclear}[νον]{.greek-supplied} εν τη βασιλεια [μου]{.greek-added} [του]{.greek-omitted} [θεου]{.greek-omitted}[14:25]{.aside}

και υμνησαντες [απηλθον]{.greek-added} [εξηλθον]{.corr} εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησ[θε]{.unclear}]{.greek-added} [σκανδαλισθησεσθε]{.corr} [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το [γερθηναι]{.greek-added} [εγερθηναι]{.corr} με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ [αιγω]{.greek-added} [εγω]{.corr}[14:29]{.aside}

και λεγει [αυτοις]{.greek-added} [αυτω]{.corr} ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν η δις [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με[14:30]{.aside}

ο δε [πετρος]{.greek-added} [εκπερισου]{.greek-added} [εκπερισσου]{.corr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν [δεη]{.greek-added} με [δεη]{.greek-omitted} συναποθανειν σοι ου μη σε [απαρνησωμεν]{.greek-added} [απαρνησωμαι]{.corr} ωσαυτως [δε]{.corr} και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα [σοι]{.greek-added} δυνατα [σοι]{.greek-omitted} παρενεγκε το ποτηριον απ εμου τουτο [αλλ]{.greek-omitted} [ου]{.greek-omitted} [τι]{.greek-omitted} [εγω]{.greek-omitted} [θελω]{.greek-omitted} [αλλα]{.greek-omitted} [τι]{.greek-omitted} [συ]{.greek-omitted}[14:36]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αββα]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [παντα]{.greek-omitted} [δυνατα]{.greek-omitted} [σοι]{.greek-omitted} [παρενεγκε]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted} [τουτο]{.greek-omitted} αλλ ου τι εγω θελω αλλα τι συ[14:36 | instance no. 2]{.aside}

και [ερχετε]{.greek-added} [ερχεται]{.corr} και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σι[μ]{.greek-supplied}ων καθευδεις ουκ [ισχυσας]{.greek-omitted} [ισχυσες]{.greek-added} μιαν ωραν [γρηγορησαι]{.greek-omitted} [γρηγορεισαι]{.greek-added}[14:37]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [και]{.greek-omitted} [ευρισκει]{.greek-omitted} [αυτους]{.greek-omitted} [καθευδοντας]{.greek-omitted} και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν [γρηγορησαι]{.greek-omitted} [γρηγορεισαι]{.greek-added}[14:37 | instance no. 2]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισε[λ]{.unclear}θητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

γρηγορειτε και πρ[ο]{.unclear}σευχεσθε [[πρ[ο]{.unclear}σευχεσθαι]{.corr}]{.greek-added} ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η [δε]{.greek-omitted} σαρξ ασθενης[14:38 | instance no. 2]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39 | instance no. 2]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [οφθαλμοι]{.greek-omitted} [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδεισαν]{.greek-omitted} [τι]{.greek-omitted} [αυτω]{.greek-omitted} [αποκριθωσιν]{.greek-omitted}[14:40]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ [αυτων]{.greek-added} οι οφθαλμοι [αυτων]{.greek-omitted} βεβαρημενοι και ουκ [ηδεισαν]{.greek-omitted} [ηδησαν]{.greek-added} τι [αυτω]{.greek-omitted} [αυτο]{.greek-added} [αποκριθ[η]{.unclear}ναι]{.greek-added} [αποκριθωσιν]{.corr}[14:40 | instance no. 2]{.aside}

και [ερχετε]{.greek-added} [ερχεται]{.corr} [το]{.greek-added} το τριτον και λεγει αυτοις καθευδετε λοιπον και αναπαυεσθε [απελθων]{.greek-added} [απεχ[ει]{.unclear}]{.corr} ηλθεν η ωρα [ιδου]{.greek-omitted} [ιου]{.greek-added} παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις τας χειρας [των]{.greek-omitted} [τω]{.greek-added} [αμαρτωλων]{.greek-omitted} [αμαρτωλον]{.greek-added}[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με [ηγγισ[ε]{.unclear}ν]{.greek-added} [ηγγικ[ε]{.unclear}ν]{.corr}[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων [παρα]{.greek-omitted} [περι]{.greek-added} των αρχιερεων και [των]{.corr} γραμματεων και των πρεσβυτερων[14:43]{.aside}

[δεδωκει]{.greek-omitted} [δεδοκει]{.greek-added} δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως [προσελθων]{.greek-omitted} [προσελθον]{.greek-added} [αυτω]{.corr} λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας [αυτων]{.corr} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις [των]{.corr} παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επεσε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς [ημας]{.greek-added} [υμας]{.corr} εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε [καταλ[οι]{.unclear}πον]{.greek-added} [καταλιπων]{.greek-omitted} [[καταλιπον]{.corr}]{.greek-added} την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι [δε]{.greek-omitted} αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκ[ον]{.greek-supplied}[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και [ισαι]{.greek-omitted} [ησαι]{.greek-added} [αι]{.greek-omitted} μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και [δια]{.greek-omitted} [τριων]{.greek-omitted} [ημερων]{.greek-omitted} αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και [ουδε]{.greek-omitted} [ουδ]{.greek-added} ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν [ο]{.greek-omitted} αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} εγω ειμι και οψεσθε τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτ[υ]{.unclear}ρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι [υμιν]{.greek-omitted} [ημιν]{.greek-added} φαινεται οι δε παντες κατεκριναν αυτον εινα[ι]{.unclear} [εχον]{.greek-added} [ενοχον]{.corr} θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω [και]{.greek-omitted} [περικαλυπτειν]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [κολαφιζειν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται [κ[―]{.gap}λ]{.greek-added} [[ραπισματα]{.corr}]{.greek-added} [ραπισμασιν]{.corr} αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν τη αυλη [κατω]{.greek-omitted} [ερχεται]{.greek-omitted} [κατερχεται]{.greek-added} μια των παιδισκων του αρχιερεως[14:66]{.aside}

και [ι]{.unclear}δουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε επισταμαι τι συ λεγεις [και]{.greek-omitted} εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added}[14:69]{.aside}

ο δε παλιν [ειρνειτο]{.greek-added} [ηρνειτο]{.corr} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και [ανεμνησθη]{.greek-omitted} [εμνησθη]{.greek-added} ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και [επηρωτα]{.greek-added} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} ο πιλατος [αυτον]{.greek-added} συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος [παλιν]{.greek-omitted} επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι [ουδεν]{.greek-omitted} [ουδ]{.greek-added} απεκριθη [ωσ]{.greek-added} [ωστε]{.greek-omitted} [θαυμαζειν]{.greek-omitted} [τον]{.greek-omitted} [πιλατον]{.greek-omitted}[15:5]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ουκετι]{.greek-omitted} [ουδεν]{.greek-omitted} [απεκριθη]{.greek-omitted} ωστε θαυμαζειν τον πιλατον[15:5 | instance no. 2]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητ[ο]{.unclear}[υντο]{.greek-supplied}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των [συστασιαστων]{.greek-omitted} [στασιαστων]{.greek-added} δεδεμενος οιτινες εν τη στασει φον[ον]{.greek-supplied} πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε π[ι]{.greek-supplied}λατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν [τον]{.greek-omitted} βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια [φθονον]{.greek-omitted} [φον[ον]{.unclear}]{.greek-added} παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεστησαν]{.greek-added} τον οχλον ινα μαλλ[ον]{.greek-supplied} τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσως]{.greek-added} [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος [το]{.greek-added} [ικανον]{.greek-added} τω οχλω [το]{.greek-omitted} [ικανον]{.greek-omitted} [ποιησαι]{.greek-omitted} απελυσεν αυτοις τον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον [και]{.greek-added} [λεγειν]{.greek-added} χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον [αυτου]{.greek-omitted} την κεφαλην [αυτου]{.greek-added} καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και [οτε]{.greek-omitted} [οταν]{.greek-added} ενεπαιξαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [γολγοθα]{.greek-omitted} [γολγοθαν]{.greek-added} τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και [εδιδουν]{.greek-omitted} [εδιδου]{.greek-added} αυτω πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρ[ο]{.unclear}ν επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας [αυτου]{.greek-omitted} επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τα[ς]{.greek-supplied} κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου [δυνατε]{.greek-added} [δυναται]{.corr} σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι [συνεσταυρωμενοι]{.greek-abbr} [συν]{.greek-added} αυτω ωνειδιζον αυτον[15:32]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [[θ]{.greek-abbr}]{.greek-added}[15:33]{.aside}

και τη ωρα [τη]{.greek-omitted} [την]{.greek-added} ενατη [[εννατη]{.corr}]{.greek-added} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων [ελωι]{.greek-omitted} [ελαι]{.greek-added} [ελωι]{.greek-omitted} [ελαι]{.greek-added} λιμα [σαβαχθανι]{.greek-omitted} [σαβαχθανη]{.greek-added} [ο[τ]{.unclear}]{.greek-added} [ο]{.corr} [εστην]{.greek-added} [εστιν]{.corr} μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου [εις]{.greek-omitted} τι με εγκατελιπες[15:34]{.aside}

και [τιν[αι]{.unclear}ς]{.greek-added} [τινες]{.corr} των παρεστηκοτων [ακουσαντες]{.greek-omitted} ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δ[ε]{.unclear} εις και γεμισας [σπογον]{.greek-added} [σπογγον]{.corr} οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο [[ε]{.unclear}καντονταρχος]{.greek-added} [κεντυριων]{.corr} ο παρεστηκως εξ εναντιας αυτου οτι [ουτως]{.greek-omitted} [κραξας]{.greek-omitted} εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} [[θεου]{.greek-abbr}]{.greek-added} ην [θεου]{.greek-omitted}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην και μαρια η μαγδαληνη και μαρια η του [ιακωβου]{.greek-omitted} [ηακωβου]{.greek-added} του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι [και]{.greek-omitted} οτε ην εν τη γαλιλαια ηκολουθουν αυτω και [διηκονουν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} αλλαι πολλαι [αι]{.greek-omitted} συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

ηλθεν ιωσηφ ο απο αριμαθαιας [[αριματθαιας]{.corr}]{.greek-added} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισσηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον [κεντυριωνα]{.greek-omitted} [κεντυριονα]{.greek-added} επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας [σινδ[ω]{.unclear}να]{.greek-added} [σινδονα]{.corr} και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλησε]{.greek-added} τη [σινδον[η]{.unclear}]{.greek-added} [σινδονι]{.corr} και [κατεθηκεν]{.greek-omitted} [εθηκεν]{.greek-added} αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [λιθον]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted} [του]{.greek-omitted} [μνημειου]{.greek-omitted}[15:46]{.aside}

[και]{.greek-omitted} [αγορασας]{.greek-omitted} [σινδονα]{.greek-omitted} [και]{.greek-omitted} [καθελων]{.greek-omitted} [αυτον]{.greek-omitted} [ενειλησεν]{.greek-omitted} [τη]{.greek-omitted} [σινδονι]{.greek-omitted} [και]{.greek-omitted} κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46 | instance no. 2]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που τιθε[ται]{.greek-supplied}[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις [αποκυλιση]{.greek-added} [αποκυλισει]{.corr} ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθ[ου]{.unclear}σαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος ο[π]{.unclear}ου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει [ημας]{.greek-added} [υμας]{.corr} εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν [ημιν]{.greek-added} [υμιν]{.corr}[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδεν[ι]{.greek-supplied} ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης [εκβεβληκη]{.greek-added} [εκβεβληκει]{.corr} [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} δαιμονια[16:9]{.aside}

εκεινη πορευθεισα απηγγειλεν τοις μετ αυτου [γενομενοις]{.greek-omitted} [γινομενοις]{.greek-added} [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις [ενδεκα]{.greek-omitted} [[ια]{.greek-abbr}]{.greek-added} εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδησε]{.greek-added} την απιστιαν αυτων και [[σκλη]{.greek-supplied}]{.greek-added} [σκληροκαρδιαν]{.greek-omitted} [οτι]{.greek-omitted} [τοις]{.greek-omitted} [θεασαμενοις]{.greek-omitted} [αυτον]{.greek-omitted} [εγηγερμενον]{.greek-omitted} [ουκ]{.greek-omitted} [επιστευσαν]{.greek-omitted}[16:14]{.aside}

[υστερον]{.greek-omitted} [ανακειμενοις]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-omitted} [ενδεκα]{.greek-omitted} [εφανερωθη]{.greek-omitted} [και]{.greek-omitted} [ωνειδισεν]{.greek-omitted} [την]{.greek-omitted} [απιστιαν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [σκληροκαρδιαν]{.greek-omitted} [ροκαρδιαν]{.greek-added} οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14 | instance no. 2]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη [κτισι]{.greek-added} [κτισει]{.corr}[16:15]{.aside}

ο πιστευσας και [βαπτισθης]{.greek-added} [βαπτισθεις]{.corr} σωθησεται ο δε απιστησας [τη]{.greek-added} [δ]{.greek-added} [ημερα]{.greek-added} κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα [παρακολουθηση]{.greek-added} [παρακολουθησει]{.corr} [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [δαιμονια]{.greek-omitted} [εκβαλουσιν]{.greek-omitted} [γλωσσαις]{.greek-omitted} [λαλησουσιν]{.greek-omitted} [καιναις]{.greek-omitted}[16:17]{.aside}

[εκεινοι]{.greek-omitted} [δε]{.greek-omitted} [εξελθοντες]{.greek-omitted} [εκηρυξαν]{.greek-omitted} [πανταχου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [συνεργουντος]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [βεβαιουντος]{.greek-omitted} δια των επακολουθουντων σημειων αμην[[16:20 *(lacunose)*]{.lacunose}]{.aside}

