---
title: "Collation of Byz^RP^ vs 30979 (979)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 979 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30979).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 979                                   	| λογος                              	|
| 979 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 979 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 979               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 979                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 979 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 979                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1 | instance no. 2]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2 | instance no. 2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3 | instance no. 2]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας [εις]{.greek-omitted} [αφεσιν]{.greek-omitted} [αμαρτιων]{.greek-omitted}[1:4]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας [εις]{.greek-omitted} [αφεσιν]{.greek-omitted} [αμαρτιων]{.greek-omitted}[1:4 | instance no. 2]{.aside}

[εγενετο]{.greek-omitted} [ιωαννης]{.greek-omitted} [βαπτιζων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [και]{.greek-omitted} [κηρυσσων]{.greek-omitted} [βαπτισμα]{.greek-omitted} [μετανοιας]{.greek-omitted} εις αφεσιν αμαρτιων[1:4 | instance no. 3]{.aside}

και εξεπορευετο προς αυτον πασα η [ο]{.greek-added} [ιουδαια]{.corr} χωρα και οι ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων [αυτω]{.greek-added} [αυτου]{.corr}[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν [εκειναις]{.greek-omitted} ταις ημεραις [εκειναις]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και [εβαπτισθη]{.greek-omitted} [υπο]{.greek-omitted} [ιωαννου]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ιορδανην]{.greek-omitted}[1:9]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [εν]{.greek-omitted} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [ηλθεν]{.greek-omitted} [ιησους]{.greek-omitted} [απο]{.greek-omitted} [ναζαρετ]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [και]{.greek-omitted} εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9 | instance no. 2]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των ουρανων συ ει ο υιος μου ο αγαπητος εν ω ευδοκησα[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε [εν]{.greek-omitted} τω ευαγγελιω[1:15]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [περιπατων]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [περιπατων]{.corr} [δε]{.corr} παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα [και]{.greek-omitted} [ανδρεαν]{.greek-omitted} [τον]{.greek-omitted} [αδελφον]{.greek-omitted} [αυτου]{.greek-omitted} [του]{.greek-omitted} [σιμωνος]{.greek-omitted} [βαλλοντας]{.greek-omitted} [αμφιβληστρον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [αλιεις]{.greek-omitted}[1:16]{.aside}

[περιπατων]{.greek-omitted} [δε]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [ειδεν]{.greek-omitted} [σιμωνα]{.greek-omitted} και ανδρεαν τον αδελφον αυτου [του]{.greek-omitted} σιμωνος [βαλλοντας]{.greek-omitted} [βαλλοντος]{.greek-added} [αμφιβληστρον]{.greek-omitted} [αμφιβλιστρον]{.greek-added} εν τη θαλασση ησαν γαρ αλιεις[1:16 | instance no. 2]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον [τον]{.greek-omitted} του [ζεβαιδαιου]{.greek-added} [ζεβεδαιου]{.corr} και [ιωαννην]{.greek-abbr} τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα [αυτων]{.greek-added}[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο [παντες]{.greek-added} επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι [γραμματεις]{.greek-omitted} [γρα]{.greek-added}[1:22]{.aside}

[και]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [διδασκων]{.greek-omitted} [αυτους]{.greek-omitted} [ως]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχων]{.greek-omitted} [και]{.greek-omitted} [ουχ]{.greek-omitted} [ως]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [μματεις]{.greek-added}[1:22 | instance no. 2]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ανος]{.greek-added} [τις]{.greek-added} [ην]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [συναγωγη]{.greek-added} [των]{.greek-added} [ιουδαιων]{.greek-added} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζαρινε]{.greek-added} ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων [φιμωθητι]{.greek-omitted} [και]{.greek-omitted} εξελθε εξ αυτου[1:25]{.aside}

και εθαμβηθησαν παντες ωστε [συζητειν]{.greek-omitted} [ζητειν]{.greek-added} προς [εαυτους]{.greek-omitted} [αλληλους]{.greek-added} [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα [σιμωνος]{.greek-omitted} [κατεκειτο]{.greek-omitted} [πυρεσσουσα]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [περι]{.greek-omitted} [αυτης]{.greek-omitted}[1:30]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [πενθερα]{.greek-omitted} σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30 | instance no. 2]{.aside}

και προσελθων ηγειρεν αυτην κρατησας [τ[σ]{.unclear}ς]{.greek-added} [της]{.corr} χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και [τους]{.greek-omitted} δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added} αυτον[1:34]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις ερημον τοπον κακει προσηυχετο [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [απηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [ερημον]{.greek-added} [κακει]{.greek-added} [προσηυχετο]{.greek-added}[1:35]{.aside}

και κατεδιωξαν αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και [ευροντες]{.greek-omitted} [αυτον]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [παντες]{.greek-omitted} [σε]{.greek-omitted} [ζητουσιν]{.greek-omitted}[1:37]{.aside}

[και]{.greek-omitted} ευροντες αυτον λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37 | instance no. 2]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας [κωμοπολ[ι]{.unclear}ς]{.greek-added} [κωμοπολεις]{.corr} ινα [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [εληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και [τα]{.greek-omitted} δαιμονια [εκβαλων]{.greek-added} [εκβαλλων]{.corr}[1:39]{.aside}

[και]{.corr} [ερχεται]{.corr} [προς]{.corr} [αυτον]{.corr} [λεπρος]{.corr} παρακαλων αυτον και γονυπετων [αυτον]{.greek-omitted} [αυτων]{.greek-added} και λεγων αυτω οτι εαν θελης δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [πολλα]{.greek-omitted} [και]{.greek-omitted} [διαφημιζειν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ωστε]{.greek-omitted} [μηκετι]{.greek-omitted} [αυτον]{.greek-omitted} [δυνασθαι]{.greek-omitted} [φανερως]{.greek-omitted} [εις]{.greek-omitted} [πολιν]{.greek-omitted} [εισελθειν]{.greek-omitted} [αλλ]{.greek-omitted} [εξω]{.greek-omitted} [εν]{.greek-omitted} [ερημοις]{.greek-omitted} [τοποις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ηρχοντο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πανταχοθεν]{.greek-omitted}[1:45]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εξελθων]{.greek-omitted} ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45 | instance no. 2]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν [εις]{.greek-added} [καπερναουμ]{.greek-added} [δι]{.greek-added} [ημερων]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως [συνηχθησαν]{.greek-omitted} [συνησθησαν]{.greek-added} πολλοι ωστε [μηκετι]{.greek-omitted} [μη]{.greek-added} χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη [διναμενοι]{.greek-added} [δυναμενοι]{.corr} προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και [εξορυξαντες]{.greek-omitted} [ορυξαντες]{.greek-added} [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον [κραββατον]{.greek-omitted} [κραβατον]{.greek-added} εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφε]{.greek-added} [αφεωνται]{.greek-omitted} [σοι]{.greek-omitted} [αι]{.greek-omitted} [αμαρτιαι]{.greek-omitted} [σου]{.greek-omitted}[2:5]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [παραλυτικω]{.greek-omitted} [τεκνον]{.greek-omitted} [αφεωνται]{.greek-omitted} [ωνται]{.greek-added} σοι αι αμαρτιαι σου[2:5 | instance no. 2]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} [ουτω]{.greek-added} λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω αφεωνται σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφ[ε]{.unclear}αιναι]{.greek-added} [[αφιαιναι]{.corr}]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω εγειραι και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν εναντιον παντων ωστε [εξιστασθαι]{.greek-omitted} [παντας]{.greek-omitted} [και]{.greek-omitted} [δοξαζειν]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [λεγοντας]{.greek-omitted} [οτι]{.greek-omitted} [ουδεποτε]{.greek-omitted} [ουτως]{.greek-omitted} [ειδομεν]{.greek-omitted}[2:12]{.aside}

[και]{.greek-omitted} [ηγερθη]{.greek-omitted} [ευθεως]{.greek-omitted} [και]{.greek-omitted} [αρας]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εναντιον]{.greek-omitted} [παντων]{.greek-omitted} [ωστε]{.greek-omitted} εξιστασθαι [παντας]{.greek-omitted} [παντες]{.greek-added} και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως ειδομεν[2:12 | instance no. 2]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} παραγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [λεβιν]{.greek-added} [λευι]{.greek-omitted} [[λευιν]{.corr}]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

[και]{.greek-added} και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και [ακουσας]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχουσιν]{.greek-omitted} [οι]{.greek-omitted} [ισχυοντες]{.greek-omitted} [ιατρου]{.greek-omitted} [αλλ]{.greek-omitted} [οι]{.greek-omitted} [κακως]{.greek-omitted} [εχοντες]{.greek-omitted} [ουκ]{.greek-omitted} [ηλθον]{.greek-omitted} [καλεσαι]{.greek-omitted} [δικαιους]{.greek-omitted} [αλλα]{.greek-omitted} [αμαρτωλους]{.greek-omitted} [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[2:17]{.aside}

[και]{.greek-omitted} ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17 | instance no. 2]{.aside}

και [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ησαν οι μαθηται [ιωαννου]{.greek-omitted} [του[ιωαννου]{.greek-abbr}]{.greek-added} και οι των φαρισαιων [νηστευοντες]{.greek-omitted} [νηστευωντες]{.greek-added} και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων εστιν νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο [νυμφιος]{.greek-omitted} [νιμφιος]{.greek-added} και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου επιρραπτει επι ιματιω παλαιω ει δε μη [αιρει]{.greek-omitted} [το]{.greek-omitted} [πληρωμα]{.greek-omitted} [αυτου]{.greek-omitted} [το]{.greek-omitted} [καινον]{.greek-omitted} [του]{.greek-omitted} [παλαιου]{.greek-omitted} [και]{.greek-omitted} [χειρον]{.greek-omitted} [σχισμα]{.greek-omitted} [γινεται]{.greek-omitted}[2:21]{.aside}

[και]{.greek-omitted} [ουδεις]{.greek-omitted} [επιβλημα]{.greek-omitted} [ρακους]{.greek-omitted} [αγναφου]{.greek-omitted} [επιρραπτει]{.greek-omitted} [επι]{.greek-omitted} [ιματιω]{.greek-omitted} [παλαιω]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21 | instance no. 2]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη [ρησσει]{.greek-omitted} [ρησει]{.greek-added} ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} [οινον]{.greek-omitted} [οινος]{.greek-added} [νεον]{.greek-omitted} [νεος]{.greek-added} εις ασκους καινους βλητεον[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον [εν]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [επορευετο]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι [ποιουσιν]{.greek-omitted} [ποισουσι]{.greek-added} [εν]{.greek-omitted} τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε [ανεγνωται]{.greek-added} [ανεγνωτε]{.corr} τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted} [φαγειν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τοις]{.greek-omitted} [ιερευσιν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [ουσιν]{.greek-omitted}[2:26]{.aside}

[πως]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [αβιαθαρ]{.greek-omitted} [αρχιερεως]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [της]{.greek-omitted} [προθεσεως]{.greek-omitted} [εφαγεν]{.greek-omitted} [ους]{.greek-omitted} ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26 | instance no. 2]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} [και]{.corr} του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμενην]{.greek-added} [εξηραμμενην]{.corr} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει [εν]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω εξηραμμενην εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-omitted} [[κυριω]{.greek-abbr}]{.greek-added} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} [η]{.greek-omitted} [χειρ]{.greek-omitted} [αυτου]{.greek-omitted} [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[3:5]{.aside}

και [περιβλεψαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [μετ]{.greek-omitted} [οργης]{.greek-omitted} [συλλυπουμενος]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [πωρωσει]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [εκτεινον]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξετεινεν]{.greek-omitted} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} [απεκατασταθη]{.greek-added} η χειρ αυτου υγιης ως η αλλη[3:5 | instance no. 2]{.aside}

και εξελθοντ[ε]{.unclear}ς οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον [εποιουν]{.greek-omitted} [εποιησαν]{.greek-added} κατ αυτου [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [συμβουλιον]{.greek-added} [εποιησαν]{.greek-added} [οι]{.greek-added} [φαρισαιοι]{.greek-added} [κατα]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [μετα]{.greek-added} [των]{.greek-added} [ηρωδιανων]{.greek-added} οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν [αυτω]{.greek-omitted} [ινα]{.greek-omitted} [αυτου]{.greek-omitted} [αψωνται]{.greek-omitted} [οσοι]{.greek-omitted} [ειχον]{.greek-omitted} [μαστιγας]{.greek-omitted}[3:10]{.aside}

[πολλους]{.greek-omitted} [γαρ]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [ωστε]{.greek-omitted} [επιπιπτειν]{.greek-omitted} αυτω ινα [αψωνται]{.greek-added} αυτου [αψωνται]{.greek-omitted} οσοι ειχον μαστιγας[3:10 | instance no. 2]{.aside}

και τα πνευματα τα ακαθαρτα οταν αυτον εθεωρει [προσεπιπτων]{.greek-added} [προσεπιπτεν]{.corr} αυτω και [εκραζεν]{.greek-omitted} [εκραζε]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει [εις]{.greek-added} [ορος]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ανεβη]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [του]{.greek-omitted} ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και [ματθαιον]{.greek-omitted} [και]{.greek-omitted} [θωμαν]{.greek-omitted} [και]{.greek-omitted} [ιακωβον]{.greek-omitted} [τον]{.greek-omitted} [του]{.greek-omitted} [αλφαιου]{.greek-omitted} [και]{.greek-omitted} [θαδδαιον]{.greek-omitted} [και]{.greek-omitted} [σιμωνα]{.greek-omitted} [τον]{.greek-omitted} [κανανιτην]{.greek-omitted}[3:18]{.aside}

[και]{.greek-omitted} [ανδρεαν]{.greek-omitted} [και]{.greek-omitted} [φιλιππον]{.greek-omitted} [και]{.greek-omitted} [βαρθολομαιον]{.greek-omitted} [και]{.greek-omitted} ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18 | instance no. 2]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

και [συνερχεται]{.greek-omitted} [ερχονται]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} [και]{.greek-added} [συνετρεχε]{.greek-added} παλιν [ο]{.greek-added} οχλος ωστε μη δυνασθαι αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλει[ν]{.unclear}[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται [σταθηναι]{.greek-omitted} [σταθη]{.greek-added} [η]{.greek-omitted} [οικια]{.greek-omitted} [εκεινη]{.greek-omitted}[3:25]{.aside}

[ναι]{.greek-added} [και]{.greek-omitted} [εαν]{.greek-omitted} [οικια]{.greek-omitted} [εφ]{.greek-omitted} [εαυτην]{.greek-omitted} [μερισθη]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [σταθηναι]{.greek-omitted} η οικια εκεινη[3:25 | instance no. 2]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την [οικιαν]{.greek-omitted} [οικοιαν]{.greek-added} αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και [βασφημιαι]{.greek-added} [βλασφημιαι]{.corr} οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον πνευμα ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες [αυτον]{.greek-omitted} [αυτω]{.greek-added}[3:31]{.aside}

και εκαθητο [ο]{.greek-added} οχλος περι αυτον [ειπον]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} [ιδου]{.greek-omitted} [η]{.greek-omitted} [μητηρ]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} [εξω]{.greek-omitted} [ζητουσιν]{.greek-omitted} [σε]{.greek-omitted}[3:32]{.aside}

[και]{.greek-omitted} [εκαθητο]{.greek-omitted} [οχλος]{.greek-omitted} [περι]{.greek-omitted} [αυτον]{.greek-omitted} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32 | instance no. 2]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει ιδε η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηρξατο]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

[ακουετε]{.greek-omitted} ιδου εξηλθεν ο σπειρων του σπειραι [τον]{.greek-added}[4:3]{.aside}

[σπορον]{.greek-added} [ακουετε]{.greek-omitted} [ιδου]{.greek-omitted} [εξηλθεν]{.greek-omitted} [ο]{.greek-omitted} [σπειρων]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-added} [σπειραι]{.greek-omitted}[4:3 | instance no. 2]{.aside}

και εγενετο εν τω σπειρειν ο μεν επεσεν παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα [πετειν[ε]{.unclear}]{.greek-added} [πετεινα]{.corr} [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι [το]{.greek-omitted} [τα]{.greek-added} πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [προσηλθον]{.greek-added} [οτε]{.greek-omitted} [δε]{.greek-omitted} [εγενετο]{.greek-omitted} [καταμονας]{.greek-omitted} [ηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted} οι [περι]{.greek-omitted} [αυτον]{.greek-omitted} [μαθηται]{.greek-added} [τω]{.greek-added} [ιυ]{.greek-added} [κατα]{.greek-added} [μονας]{.greek-added} συν τοις δωδεκα [την]{.greek-omitted} [και]{.greek-added} [ηρωτων]{.greek-added} [αυτον]{.greek-added} [πην]{.greek-added} παραβολην [του]{.greek-added} [σπορου]{.greek-added}[4:10 | instance no. 2]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι [το]{.greek-omitted} [τα]{.greek-added} [μυστηριον]{.greek-omitted} [μυστηρια]{.greek-added} της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και [ου]{.greek-added} μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουουσι]{.greek-added} και [ου]{.greek-added} μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και [αφεθη]{.greek-omitted} [αφεθησεται]{.greek-added} αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και [αιρει]{.corr} τον λογον τον εσπαρμενον εν ταις [καρδιαις]{.greek-omitted} [αυτων]{.greek-omitted}[4:15]{.aside}

[ουτοι]{.greek-omitted} [δε]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [οπου]{.greek-omitted} [σπειρεται]{.greek-omitted} [ο]{.greek-omitted} [λογος]{.greek-omitted} [και]{.greek-omitted} [οταν]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [ευθεως]{.greek-omitted} [ερχεται]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [και]{.greek-omitted} [αιρει]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [τον]{.greek-omitted} [εσπαρμενον]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} καρδιαις αυτων[4:15 | instance no. 2]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ εχουσιν ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την [γην]{.greek-added} [την]{.greek-added} καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο [λυ]{.greek-added} [λυχνος]{.greek-omitted} [ερχεται]{.greek-omitted} [ινα]{.greek-omitted} [υπο]{.greek-omitted} [τον]{.greek-omitted} [μοδιον]{.greek-omitted} [τεθη]{.greek-omitted} [η]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [κλινην]{.greek-omitted} [ουχ]{.greek-omitted} [ινα]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [λυχνιαν]{.greek-omitted} [επιτεθη]{.greek-omitted}[4:21]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [μητι]{.greek-omitted} [ο]{.greek-omitted} [λυχνος]{.greek-omitted} [χνος]{.greek-added} ερχεται ινα [υπο]{.greek-omitted} [επι]{.greek-added} τον μοδιον τεθη η υπο [την]{.greek-omitted} [κλινην]{.greek-omitted} [κληνην]{.greek-added} ουχ ινα [επι]{.greek-omitted} [υπο]{.greek-added} την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21 | instance no. 2]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} βλεπετε τι ακουετε εν ω μετρω μετρειτε μετρηθησεται υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [εχει]{.greek-added} [αν]{.greek-omitted} [εχη]{.greek-omitted} δοθησεται αυτω και ος ουκ εχει και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} [ως]{.greek-omitted} [ος]{.greek-added} εαν [ανθρωπος]{.greek-abbr} βαλη [τον]{.greek-omitted} σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [ερχεται]{.greek-added} νυκτα και ημεραν και ο σπορος βλαστανη και μηκυνηται ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη [γαρ]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [καρποφορει]{.greek-omitted} [πρωτον]{.greek-omitted} [χορτον]{.greek-omitted} [ειτα]{.greek-omitted} [σταχυν]{.greek-omitted} [ειτα]{.greek-omitted} [πληρη]{.greek-omitted} [σιτον]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σταχυι]{.greek-omitted}[4:28]{.aside}

[αυτοματη]{.greek-omitted} γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν [ειτα]{.greek-omitted} [επι]{.greek-added} [τα]{.greek-added} πληρη σιτον εν τω σταχυι[4:28 | instance no. 2]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσομεν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} [παραβαλουμεν]{.greek-added} αυτην[4:30]{.aside}

ως κοκκον σιναπεως ος οταν σπαρη επι της γης μικροτερος παντων των [σπερματων]{.greek-omitted} [σπαρματων]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις [πολλαις]{.greek-omitted} ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [απελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει [αυτοις]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ημερα]{.greek-omitted} [οψιας]{.greek-omitted} [γενομενης]{.greek-omitted} [διελθωμεν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted}[4:35]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} αυτοις εν εκεινη τη ημερα οψιας γενομενης [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} διελθωμεν εις το περαν[4:35 | instance no. 2]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λελαμψ]{.greek-added} ανεμου μεγαλη τα δε κυματα [επεβαλλεν]{.greek-omitted} [επαβαλεν]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και [ην]{.greek-omitted} αυτος επι τη πρυμνη επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου μελει σοι οτι [απολλυμεθα]{.greek-omitted} [απολυμεθα]{.greek-added}[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος [εστιν]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [θαλασσα]{.greek-omitted} [υπακουουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[4:41]{.aside}

[και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted} [φοβον]{.greek-omitted} [μεγαν]{.greek-omitted} [και]{.greek-omitted} [ελεγον]{.greek-omitted} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [τις]{.greek-omitted} [αρα]{.greek-omitted} [ουτος]{.greek-omitted} εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41 | instance no. 2]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το [περαν]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την [κατοικησιν]{.greek-omitted} [κατηκησιν]{.greek-added} ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις εδυνατο αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλησεσι]{.greek-added} δεδεσθαι και [διεσπασθαι]{.greek-omitted} [διασπασθαι]{.greek-added} [τας]{.greek-added} [αλυσεις]{.greek-added} υπ αυτου [τας]{.greek-omitted} [αλυσεις]{.greek-omitted} και τας [πεδας]{.greek-omitted} [πετρας]{.greek-added} συντετριφθαι και ουδεις αυτον [ισχυεν]{.greek-omitted} [ισχυε]{.greek-added} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και [εν]{.greek-omitted} τοις μνημασιν ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [τι]{.greek-omitted} [εμοι]{.greek-omitted} [και]{.greek-omitted} [σοι]{.greek-omitted} [ιησου]{.greek-omitted} [υιε]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [υψιστου]{.greek-omitted} [ορκιζω]{.greek-omitted} [σε]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [μη]{.greek-omitted} [με]{.greek-omitted} [βασανισης]{.greek-omitted}[5:7]{.aside}

[και]{.greek-omitted} [κραξας]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι εμοι και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το [πνευμα]{.greek-omitted} [το]{.greek-omitted} ακαθαρτον [εκ]{.greek-omitted} [απο]{.greek-added} του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι ονομα και απεκριθη [λεγων]{.greek-omitted} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον πολλα ινα μη αυτους [αποστειλη]{.greek-omitted} [αποστελη]{.greek-added} εξω της χωρας[5:10]{.aside}

ην δε εκει προς τω ορει αγελη χοιρων μεγαλη βοσκομενη[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον [παντες]{.greek-omitted} οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις [ευθεως]{.greek-omitted} [ενθεως]{.greek-added} ο [ιησους]{.greek-abbr} και εξελθοντα τα πνευματα τα ακαθαρτα [εισηλθον]{.greek-omitted} [εισηλθεν]{.greek-added} εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και ανηγγειλαν [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αγρους]{.greek-omitted} [και]{.greek-omitted} [εξηλθον]{.greek-omitted} [ιδειν]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [γεγονος]{.greek-omitted}[5:14]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [βοσκοντες]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [εφυγον]{.greek-omitted} [και]{.greek-omitted} [ανηγγειλαν]{.greek-omitted} εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το [γεγονως]{.greek-added} [γεγονος]{.corr}[5:14 | instance no. 2]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.corr} [ουκ]{.corr} αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου [προς]{.greek-omitted} [πρους]{.greek-added} τους σους [και]{.greek-omitted} αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω [παλιν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted} [συνηχθη]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted}[5:21]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς [επ]{.greek-omitted} [προς]{.greek-added} αυτον και ην παρα την θαλασσαν[5:21 | instance no. 2]{.aside}

και ιδου ερχεται [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ερχεται]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} εις των αρχισυναγωγων ονοματι ιαειρος και ιδων [αυτων]{.greek-added} [αυτον]{.corr} πιπτει προς τους ποδας αυτου[5:22]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλη]{.greek-added} αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} αυτη τας χειρας οπως [σωθη]{.greek-omitted} [και]{.greek-omitted} [ζησεται]{.greek-omitted} [σωθησεται]{.greek-added}[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και ηκολουθει αυτω οχλος πολυς [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηκολουθησε]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [οχλος]{.greek-added} [πολυς]{.greek-added} και [συνεθλιβον]{.greek-omitted} [συνεθλιβεν]{.greek-added} αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα [παρ]{.greek-omitted} [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν [ωφεληθεισα]{.greek-omitted} [αλλα]{.greek-omitted} [μαλλον]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [χειρον]{.greek-omitted} [ελθουσα]{.greek-omitted}[5:26]{.aside}

[και]{.greek-omitted} [πολλα]{.greek-omitted} [παθουσα]{.greek-omitted} [υπο]{.greek-omitted} [πολλων]{.greek-omitted} [ιατρων]{.greek-omitted} [και]{.greek-omitted} [δαπανησασα]{.greek-omitted} [τα]{.greek-omitted} [παρ]{.greek-omitted} [αυτης]{.greek-omitted} [παντα]{.greek-omitted} [και]{.greek-omitted} [μηδεν]{.greek-omitted} ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26 | instance no. 2]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [εν]{.greek-added} [εαυτη]{.greek-added} οτι καν των ιματιων αυτου αψωμαι [σωθησομαι]{.greek-omitted} [σωθησωμαι]{.greek-added}[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν [και]{.greek-added} επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη [θυγατερ]{.greek-omitted} [η]{.greek-omitted} [πιστις]{.greek-omitted} [σου]{.greek-omitted} [σεσωκεν]{.greek-omitted} [σε]{.greek-omitted} [υπαγε]{.greek-omitted} [εις]{.greek-omitted} [ειρηνην]{.greek-omitted} [και]{.greek-omitted} [ισθι]{.greek-omitted} [υγιης]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαστιγος]{.greek-omitted} [σου]{.greek-omitted}[5:34]{.aside}

[θαρσει]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34 | instance no. 2]{.aside}

ετι αυτου λαλουντος [και]{.greek-added} ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου [μονον]{.greek-omitted} [αλλα]{.greek-added} [μαλλον]{.greek-added} πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω συνακολουθησαι ει μη πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι θορυβεισθε και κλαι[ε]{.unclear}τε το παιδιον ουκ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εισπορευεται]{.greek-omitted} [οπου]{.greek-omitted} [ην]{.greek-omitted} [το]{.greek-omitted} [παιδιον]{.greek-omitted} [ανακειμενον]{.greek-omitted}[5:40]{.aside}

[και]{.greek-omitted} [κατεγελων]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [εκβαλων]{.greek-omitted} [παντας]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [του]{.greek-omitted} [παιδιου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον [κειμενον]{.greek-added} [ανακειμενον]{.corr}[5:40 | instance no. 2]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα κουμι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω εγειραι[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} [εκειθεν]{.greek-omitted} και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [[πατριδα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [ακολουθουσιν]{.greek-added} [αυτω]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added}[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτα και τις η σοφια η δοθεισα αυτω [ινα]{.greek-added} και [δυναμεις]{.greek-omitted} [δυναμις]{.greek-added} τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [τεκτων]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [μαριας]{.greek-omitted} [αδελφος]{.greek-omitted} [δε]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [ιωση]{.greek-omitted} [και]{.greek-omitted} [ιουδα]{.greek-omitted} [και]{.greek-omitted} [σιμωνος]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ου]{.greek-added} [εισιν]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [αυτου]{.greek-omitted} [ωδε]{.greek-omitted} [προς]{.greek-omitted} [ημας]{.greek-omitted} [και]{.greek-omitted} [εσκανδαλιζοντο]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted}[6:3]{.aside}

[ουχ]{.greek-omitted} [ουτος]{.greek-omitted} [τος]{.greek-added} εστιν ο τεκτων ο υιος μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει [μη]{.greek-omitted} [μι]{.greek-added} εν τη [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ [ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} εκει ουδεμιαν δυναμιν ποιησαι ει [μη]{.greek-omitted} [μι]{.greek-added} ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα [μαθητας]{.greek-added} [αυτου]{.greek-added} και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των ακαθαρτων [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [προσκαλεσαμενος]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [τους]{.greek-added} [δωδεκα]{.greek-added}[6:7]{.aside}

[μαθητας]{.greek-added} [αυτου]{.greek-added} [και]{.greek-omitted} [προσκαλειται]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των ακαθαρτων[6:7 | instance no. 2]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μονον μη πηραν μη αρτον [μη]{.greek-omitted} [μηδε]{.greek-added} εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη ενδυσησθε δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθητε εις οικιαν εκει [μενετε]{.greek-omitted} [μαινετε]{.greek-added} εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν [τον]{.greek-omitted} υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην [γαρ]{.greek-added} λεγω υμιν ανεκτοτερον εσται σοδομοις [η]{.greek-omitted} [και]{.greek-added} [γομορροις]{.greek-omitted} [γομοροις]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον [ελαιω]{.greek-omitted} [πολλους]{.greek-omitted} [αρρωστους]{.greek-omitted} [και]{.greek-omitted} [εθεραπευον]{.greek-omitted}[6:13]{.aside}

[και]{.greek-omitted} [δαιμονια]{.greek-omitted} [πολλα]{.greek-omitted} [εξεβαλλον]{.greek-omitted} [και]{.greek-omitted} [ηλειφον]{.greek-omitted} ελαιω πολλους αρρωστους και [εθεραπευον]{.greek-omitted} [εθεραπευοντο]{.greek-added}[6:13 | instance no. 2]{.aside}

και ηκουσεν [ηρωδης]{.greek-added} ο βασιλευς [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηκουσεν]{.greek-added} ηρωδης [ο]{.greek-added} [βασιλευς]{.greek-added} [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [εν]{.greek-omitted} [ενεργουσιν]{.greek-added} αυτω[6:14]{.aside}

αλλοι ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον εγω απεκεφαλισα ιωαννην ουτος εστιν αυτος ηγερθη [εκ]{.greek-omitted} [απο]{.greek-added} [των]{.greek-added} νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} [γαρ]{.greek-omitted} ο [ιωαννης]{.greek-abbr} [τω]{.greek-omitted} [ηρωδη]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted} [σοι]{.greek-omitted} [εχειν]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [του]{.greek-omitted} [αδελφου]{.greek-omitted} [σου]{.greek-omitted}[6:18]{.aside}

[ελεγεν]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ιωαννης]{.greek-omitted} τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα του αδελφου σου[6:18 | instance no. 2]{.aside}

η δε ηρωδιας ενειχεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητω]{.greek-added} τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και [ακουσας]{.greek-omitted} [ακουων]{.greek-added} αυτου πολλα εποιει και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον [με]{.greek-omitted} [μοι]{.greek-added} ο εαν θελης και δωσω σοι[6:22]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμωσεν]{.greek-added} αυτη οτι ο εαν με [αιτησης]{.greek-omitted} [αιτησεις]{.greek-added} δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [αιτησης]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted} [εως]{.greek-omitted} [ημισους]{.greek-omitted} της βασιλειας μου[6:23 | instance no. 2]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως [εξαυτης]{.greek-omitted} επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους [συνανακειμενους]{.greek-omitted} [ανακειμενους]{.greek-added} ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς [σπεκουλατορα]{.greek-omitted} [σπεκουλατωρα]{.greek-added} επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι [αποστολοι]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [και]{.greek-omitted} [απηγγειλαν]{.greek-omitted} [αυτω]{.greek-omitted} [παντα]{.greek-omitted} [και]{.greek-omitted} [οσα]{.greek-omitted} [εποιησαν]{.greek-omitted} [και]{.greek-omitted} [οσα]{.greek-omitted} [εδιδαξαν]{.greek-omitted}[6:30]{.aside}

[αποστολοι]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} και [απηγγειλαν]{.greek-added} [αυτω]{.greek-added} [παντα]{.greek-added} [οσα]{.greek-added} [εποιησαν]{.greek-added} [και]{.greek-added} [εδιδαξαν]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30 | instance no. 2]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον [η]{.greek-added} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [ολιγον]{.greek-omitted} [ησαν]{.greek-omitted} γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ειδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται αυτου λεγουσιν [οτι]{.greek-omitted} [ερημος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [τοπος]{.greek-omitted} [και]{.greek-omitted} [ηδη]{.greek-omitted} [ωρα]{.greek-omitted} [πολλη]{.greek-omitted}[6:35]{.aside}

[και]{.greek-omitted} [ηδη]{.greek-omitted} [ωρας]{.greek-omitted} [πολλης]{.greek-omitted} [γενομενης]{.greek-omitted} [προσελθοντες]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [λεγουσιν]{.greek-omitted} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35 | instance no. 2]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν [εαυτοις]{.greek-omitted} [εαυτους]{.greek-added} αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν δηναριων [διακοσιων]{.greek-omitted} [τριακοσιων]{.greek-added} αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και γνοντες [λεγουσιν]{.greek-omitted} [λεγουσουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακλιθηναι]{.greek-added} παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον ουρανον [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις [μαθη]{.greek-added} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [παραθωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [εμερισεν]{.greek-omitted} [πασιν]{.greek-omitted}[6:41]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [αναβλεψας]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [ευλογησεν]{.greek-omitted} [και]{.greek-omitted} [κατεκλασεν]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [τοις]{.greek-omitted} [ταις]{.greek-added} [μαθηταις]{.greek-omitted} αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41 | instance no. 2]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν [αυτον]{.greek-added} εις το περαν προς βηθσαιδαν εως αυτος απολυση τον οχλον [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηναγκασεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [τους]{.greek-added} [μαθητας]{.greek-added} [αυτου]{.greek-added} [εμβηναι]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [πλοιον]{.greek-added} [και]{.greek-added} [προαγειν]{.greek-added} [αυτους]{.greek-added} [εις]{.greek-added} [το]{.greek-added} [περαν]{.greek-added} [προς]{.greek-added} [βηθσαιδαν]{.greek-added} [εως]{.greek-added} [αυτος]{.greek-added} [απολυση]{.greek-added} [τον]{.greek-added} [οχλον]{.greek-added}[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος [προσευξασθαι]{.greek-omitted} [προσευξασθε]{.greek-added}[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω ελαυνειν [ην]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [εναντιος]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [περι]{.greek-omitted} [τεταρτην]{.greek-omitted} [φυλακην]{.greek-omitted} [της]{.greek-omitted} [νυκτος]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [περιπατων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

[και]{.greek-omitted} [ειδεν]{.greek-omitted} [αυτους]{.greek-omitted} [βασανιζομενους]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ελαυνειν]{.greek-omitted} ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48 | instance no. 2]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου [γαρ]{.corr} συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον [επι]{.greek-omitted} [εις]{.greek-added} την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων [εκ]{.greek-omitted} [απο]{.greek-added} του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επι[πι]{.unclear}γνοντες]{.greek-added} αυτον[6:54]{.aside}

περιδραμοντες [ολην]{.greek-omitted} [την]{.greek-omitted} [περιχωρον]{.greek-omitted} [εκεινην]{.greek-omitted} [ηρξαντο]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [κραββατοις]{.greek-omitted} [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [περιφερειν]{.greek-omitted} [οπου]{.greek-omitted} [ηκουον]{.greek-omitted} [οτι]{.greek-omitted} [εκει]{.greek-omitted} [εστιν]{.greek-omitted}[6:55]{.aside}

[περιδραμοντες]{.greek-omitted} ολην την περιχωρον εκεινην [ηρξατο]{.greek-added} [επι]{.greek-added} [τοις]{.greek-added} [κραβατοις]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [εξελθοντος]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} [πλοιου]{.greek-added} [επιγνοντες]{.greek-added} [αυτον]{.greek-added} [οι]{.greek-added} [της]{.greek-added} [γης]{.greek-added} [γενησαρετ]{.greek-added} [περιεδραμον]{.greek-added} [ολην]{.greek-added} [την]{.greek-added} [περιχορον]{.greek-added} [εκεινην]{.greek-added} [και]{.greek-added} ηρξαντο επι τοις [κραββατοις]{.greek-omitted} [κραβατοις]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55 | instance no. 2]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελθοντες απο ιεροσολυμων[7:1]{.aside}

και [ιδοντες]{.greek-omitted} [ιδωντες]{.greek-added} τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις [εσθιοντας]{.greek-omitted} [εσθιειν]{.greek-added} αρτους [εμεμψατο]{.greek-added} [εμεμψαντο]{.corr}[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας [χειρας]{.greek-omitted} [ουκ]{.greek-omitted} [εσθιουσιν]{.greek-omitted} [κρατουντες]{.greek-omitted} [την]{.greek-omitted} [παραδοσιν]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted}[7:3]{.aside}

[οι]{.greek-omitted} [γαρ]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [και]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [ιουδαιοι]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [πυγμη]{.greek-omitted} [νιψωνται]{.greek-omitted} [τας]{.greek-omitted} χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} [και]{.greek-added} κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3 | instance no. 2]{.aside}

και απο αγορας εαν μη βαπτισωνται ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν α παρελαβον κρατειν [βαπτισμους]{.greek-omitted} [βαπτεισμους]{.greek-added} ποτηριων και ξεστων και [χαλκιων]{.greek-omitted} [χαλκειων]{.greek-added} και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [επηρωτησαν]{.greek-added} [οι]{.greek-added} [γραμματεις]{.greek-added} [και]{.greek-added} [οι]{.greek-added} [φαρισαιοι]{.greek-added} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [δια]{.greek-added} [τι]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} [σου]{.greek-added} [ου]{.greek-added} [περιπατουσι]{.greek-added} κατα την παραδοσιν των πρεσβυτερων αλλα ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} [με]{.greek-omitted} [μα]{.greek-added} τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε [σεβονται]{.greek-omitted} [σεβωνται]{.greek-added} με [διδασκοντες]{.greek-omitted} [διδασκαλιας]{.greek-omitted} [ενταλματα]{.greek-omitted} [ανθρωπων]{.greek-omitted}[7:7]{.aside}

[ματην]{.greek-omitted} [δε]{.greek-omitted} [σεβονται]{.greek-omitted} [με]{.greek-omitted} διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7 | instance no. 2]{.aside}

αφεντες [γαρ]{.greek-omitted} την εντολην του [θεου]{.greek-abbr} κρατειτε [την]{.greek-omitted} [τας]{.greek-added} [παραδοσιν]{.greek-omitted} [παραδοσεις]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια [πολλα]{.greek-added} τοιαυτα [πολλα]{.greek-omitted} ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} [αυτου]{.greek-added} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} [αυτου]{.greek-omitted} η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα [τω]{.greek-added} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ακουετε]{.greek-omitted} [μου]{.greek-omitted} [παντες]{.greek-omitted} [και]{.greek-omitted} [καιρω]{.greek-added} [συνιετε]{.greek-omitted} [εκεινω]{.greek-added} [προσκαλεσαμενος]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [παντα]{.greek-added}[7:14]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [παντα]{.greek-omitted} τον οχλον ελεγεν αυτοις [ακουετε]{.greek-omitted} [ακουσατε]{.greek-added} μου παντες και [συνιετε]{.greek-omitted} [συνετε]{.greek-added}[7:14 | instance no. 2]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε [ου]{.greek-omitted} [ουπω]{.greek-added} νοειτε οτι παν το [εισπορευομεν]{.greek-added} εξωθεν [εισπορευομενον]{.greek-omitted} εις τον [ανθρωπον]{.greek-abbr} ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} αυτον κοινωσαι[7:18]{.aside}

οτι ουκ [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις [τον]{.greek-omitted} αφεδρωνα [εκπορευεται]{.greek-omitted} [εκβαλλετε]{.greek-added} [[εκβαλλετ[αι]{.unclear}]{.corr}]{.greek-added} [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το [εκπορευομενον]{.greek-added} εκ του [ανθρωπου]{.greek-abbr} [εκπορευομενον]{.greek-omitted} εκεινο [κοινοι]{.greek-omitted} [κοινη]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι [οι]{.greek-omitted} [κακοι]{.greek-omitted} [εκπορευονται]{.greek-omitted} [μοιχειαι]{.greek-omitted} [πορνειαι]{.greek-omitted} [φονοι]{.greek-omitted}[7:21]{.aside}

[εσωθεν]{.greek-omitted} [γαρ]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [οι]{.greek-omitted} [διαλογισμοι]{.greek-omitted} οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21 | instance no. 2]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος ασελγεια οφθαλμος πονηρος βλασφημια [υπερηφανια]{.greek-omitted} [υπεριφανια]{.greek-added} αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοιν[ο]{.unclear}ι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [μεθορια]{.greek-added} [τυρου]{.greek-added} [και]{.greek-added} [σιδωνος]{.greek-added} και εισελθων εις [την]{.greek-added} οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και [ου]{.greek-added} [δυνηθη]{.greek-added} [ουκ]{.corr} [ηδυνηθη]{.corr} λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι [τα]{.greek-omitted} [τεκνα]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [λαβειν]{.greek-omitted} [τον]{.greek-omitted} [αρτον]{.greek-omitted} [των]{.greek-omitted} [τεκνων]{.greek-omitted} [και]{.greek-omitted} [βαλειν]{.greek-omitted} [τοις]{.greek-omitted} [κυναριοις]{.greek-omitted}[7:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} [αφες]{.greek-omitted} [πρωτον]{.greek-omitted} [χορτασθηναι]{.greek-omitted} τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27 | instance no. 2]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} [το]{.greek-added} [παιδιον]{.greek-added} [βεβλημενον]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [κληνην]{.greek-added} [[κλ[ι]{.unclear}νην]{.corr}]{.greek-added} [και]{.greek-added} το δαιμονιον εξεληλυθος [και]{.greek-omitted} [την]{.greek-omitted} [θυγατερα]{.greek-omitted} [βεβλημενην]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κλινης]{.greek-omitted}[7:30]{.aside}

και παλιν εξελθων [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [εξελθων]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} [προς]{.greek-omitted} [παρα]{.greek-added} την θαλασσαν της γαλιλαιας ανα [μεσον]{.greek-omitted} [μεσων]{.greek-added} [των]{.greek-omitted} οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον [μογγιλαλον]{.greek-omitted} [μογγιλαλων]{.greek-added} και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους [δακτυ]{.greek-added} [δακτυλους]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ωτα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [πτυσας]{.greek-omitted} [ηψατο]{.greek-omitted} [της]{.greek-omitted} [γλωσσης]{.greek-omitted} [αυτου]{.greek-omitted}[7:33]{.aside}

[και]{.greek-omitted} [απολαβομενος]{.greek-omitted} [αυτον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [οχλου]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [εβαλεν]{.greek-omitted} [τους]{.greek-omitted} [λους]{.greek-added} [δακτυλους]{.greek-omitted} αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33 | instance no. 2]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν [αυτου]{.greek-omitted} αι ακοαι [αυτου]{.greek-added} και ελυθη ο δεσμος της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [παμπολλου]{.greek-omitted} [παμπολου]{.greek-added} οχλου οντος και μη [εχοντων]{.greek-omitted} [εχωντων]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος ο [ιησους]{.greek-abbr} [τους]{.greek-omitted} [τοις]{.greek-added} [μαθητας]{.greek-omitted} [μαθηταις]{.greek-added} αυτου λεγει αυτοις[8:1]{.aside}

[σπλαγχνιζομαι]{.greek-omitted} [σπλαγχνιζο]{.greek-added} επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και [ουκ]{.greek-omitted} [ου]{.greek-added} [εχουσιν]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted}[8:2]{.aside}

[κ]{.greek-added} [εχωσι]{.greek-added} [σπλαγχνιζομαι]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [οτι]{.greek-omitted} [ηδη]{.greek-omitted} [ημεραι]{.greek-omitted} [τρεις]{.greek-omitted} [προσμενουσιν]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2 | instance no. 2]{.aside}

και εαν απολυσω αυτους [νηστεις]{.greek-omitted} [νηστις]{.greek-added} εις οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκουσι]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε χορτασαι αρτων επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους εχετε αρτους οι δε [ειπον]{.greek-omitted} [ειπεν]{.greek-added} επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους [και]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου [ηλθεν]{.greek-omitted} [εξηλθεν]{.greek-added} εις τα [ορια]{.greek-added} [μερη]{.greek-omitted} [δαλμανουθα]{.greek-omitted}[8:10]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [εμβας]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [μερη]{.greek-omitted} [δαλμανουθα]{.greek-omitted} [δαμανουθα]{.greek-added}[8:10 | instance no. 2]{.aside}

και εξηλθον οι φαρισαιοι [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθον]{.greek-added} [οι]{.greek-added} [φαρισαιοι]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

[και]{.greek-omitted} γνους [δε]{.greek-added} ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε [ετι]{.greek-omitted} [πεπωρωμενην]{.greek-omitted} [εχετε]{.greek-omitted} [την]{.greek-omitted} [καρδιαν]{.greek-omitted} [υμων]{.greek-omitted}[8:17]{.aside}

[και]{.greek-omitted} [γνους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [διαλογιζεσθε]{.greek-omitted} [οτι]{.greek-omitted} [αρτους]{.greek-omitted} [ουκ]{.greek-omitted} [εχετε]{.greek-omitted} [ουπω]{.greek-omitted} [νοειτε]{.greek-omitted} [ουδε]{.greek-omitted} [συνιετε]{.greek-omitted} ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17 | instance no. 2]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα [εχοντες]{.greek-omitted} [εχωντες]{.greek-added} ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους [πληρεις]{.greek-omitted} [πληρις]{.greek-added} κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως [ου]{.greek-omitted} [ουπω]{.greek-added} συνιετε[8:21]{.aside}

και [ερχονται]{.greek-added} [εις]{.greek-added} [βηθσαιδαν]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} ερχεται [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις βηθσαιδαν και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα [αψηται]{.greek-added} αυτου [αψηται]{.greek-omitted}[8:22]{.aside}

και επιλαβομενος της χειρος [του]{.greek-omitted} [αυτου]{.greek-added} [τυφλου]{.greek-omitted} εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα [αυτον]{.greek-omitted} [αυτων]{.greek-added} [ει]{.greek-omitted} [τι]{.greek-omitted} [βλεπει]{.greek-omitted}[8:23]{.aside}

[και]{.greek-omitted} [επιλαβομενος]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [του]{.greek-omitted} [τυφλου]{.greek-omitted} [εξηγαγεν]{.greek-omitted} [αυτον]{.greek-omitted} [εξω]{.greek-omitted} [της]{.greek-omitted} [κωμης]{.greek-omitted} [και]{.greek-omitted} [πτυσας]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ομματα]{.greek-omitted} [αυτου]{.greek-omitted} [επιθεις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [αυτω]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} ει τι βλεπει[8:23 | instance no. 2]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και αποκατεσταθη και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε [εις]{.greek-omitted} [την]{.greek-omitted} [κωμην]{.greek-omitted} [εισελθης]{.greek-omitted} [μηδε]{.greek-omitted} ειπης τινι εν τη κωμη[8:26]{.aside}

και [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην [και]{.greek-omitted} αλλοι [δε]{.greek-added} ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις [ινα]{.greek-omitted} [μηδενι]{.greek-omitted} [λεγωσιν]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted}[8:30]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} επετιμησεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [αυτοις]{.greek-omitted} [τοις]{.greek-added} [μαθηταις]{.greek-added} [αυτου]{.greek-added} ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30 | instance no. 2]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και [των]{.greek-omitted} αρχιερεων και [των]{.greek-omitted} γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε [επι]{.greek-added} [επιστραφεις]{.greek-omitted} [[εστραφεις]{.corr}]{.greek-added} και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} οστις θελει οπισω μου [ακολουθειν]{.greek-omitted} [ελθειν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ακολουθειτω]{.greek-omitted} [μοι]{.greek-omitted}[8:34]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [συν]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [οστις]{.greek-omitted} [θελει]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [ακολουθειν]{.greek-omitted} [απαρνησασθω]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [αρατω]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34 | instance no. 2]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου ουτος σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} εαν [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} [ανταλαγμα]{.greek-added} [ανταλλαγμα]{.corr} της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων [―]{.gap}των [[των]{.corr}]{.greek-added} αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} παραλαμβανει ο [ιησους]{.greek-abbr} τον [πετρον]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [ιακωβον]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [και]{.greek-omitted} [αναφερει]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [ορος]{.greek-omitted} [υψηλον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [μονους]{.greek-omitted} [και]{.greek-omitted} [μετεμορφωθη]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [αυτων]{.greek-omitted}[9:2]{.aside}

[και]{.greek-omitted} [μεθ]{.greek-omitted} [ημερας]{.greek-omitted} [εξ]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τον]{.greek-omitted} πετρον και [τον]{.greek-omitted} ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν [μονους]{.greek-omitted} και μετεμορφωθη εμπροσθεν αυτων[9:2 | instance no. 2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν ως χιων οια [γναφευς]{.greek-omitted} [κναφευ]{.greek-added} επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν [συλλαλουντες]{.greek-omitted} [λαλουντες]{.greek-added} τω [μ]{.greek-added} [ιησου]{.greek-abbr}[9:4]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και μωση μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα αυτοις και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι διηγησωνται α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [εκρατησαν]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} [τον]{.greek-added} [λογον]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [προς]{.greek-added} [εαυτους]{.greek-added} συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα και πως γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε [προς]{.greek-omitted} [αυτους]{.greek-omitted}[9:16]{.aside}

[και]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [τους]{.greek-omitted} [γραμματεις]{.greek-omitted} [τι]{.greek-omitted} [συζητειτε]{.greek-omitted} προς αυτους[9:16 | instance no. 2]{.aside}

και αποκριθεις εις εκ του οχλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [προσηλθε]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [γονυπετων]{.greek-added} [αυτον]{.greek-added} [και]{.greek-added} [λεγων]{.greek-added} διδασκαλε ηνεγκα τον υιον μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρ[η]{.unclear}σσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το πνευμα εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [υδατα]{.greek-omitted} [ινα]{.greek-omitted} [απολεση]{.greek-omitted} [αυτον]{.greek-omitted} [αλλ]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} [δυνασαι]{.greek-omitted} [βοηθησον]{.greek-omitted} [ημιν]{.greek-omitted} [σπλαγχνισθεις]{.greek-omitted} [εφ]{.greek-omitted} [ημας]{.greek-omitted}[9:22]{.aside}

[εβαλε]{.greek-added} [και]{.greek-omitted} [πολλακις]{.greek-omitted} [αυτον]{.greek-omitted} και εις [τα]{.greek-added} [το]{.greek-omitted} [πυρ]{.greek-omitted} [εβαλεν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το πνευμα το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και [εισελθοντα]{.greek-omitted} [ελθοντα]{.greek-added} αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν οτι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και ηλθεν [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [και]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος [εν]{.greek-added} [υμιν]{.greek-added} ειναι εσται παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν [το]{.greek-added} μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν [εν]{.greek-omitted} των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα [τον]{.greek-omitted} [των]{.greek-added} αποστειλαντα με[9:37]{.aside}

[απεκριθη]{.greek-omitted} [αποκριθεις]{.greek-added} δε αυτω [ο]{.greek-added} ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} τινα [εν]{.greek-added} τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και εκωλυσαμεν αυτον οτι ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος [γαρ]{.greek-omitted} ουκ [εστι]{.greek-added} [καθ]{.greek-added} [ημων]{.greek-added} [υπερ]{.greek-added} [ημων]{.greek-added} εστιν [καθ]{.greek-omitted} [υμων]{.greek-omitted} [υπερ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted}[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτηση]{.greek-added} υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} ος εαν [σκανδαλιση]{.greek-omitted} [σκανδαλισει]{.greek-added} ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} [μαλλον]{.greek-added} αυτω [μαλλον]{.greek-omitted} ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η [τας]{.greek-omitted} δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} σοι [εισελθειν]{.greek-omitted} εις την ζωην [ελ]{.greek-added} [[εισελθειν]{.corr}]{.greek-added} χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν [εις]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [το]{.greek-omitted} [ασβεστον]{.greek-omitted}[9:45]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [ο]{.greek-omitted} [πους]{.greek-omitted} [σου]{.greek-omitted} [σκανδαλιζη]{.greek-omitted} [σε]{.greek-omitted} [αποκοψον]{.greek-omitted} [αυτον]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [σοι]{.greek-omitted} [εισελθειν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ζωην]{.greek-omitted} [χωλον]{.greek-omitted} [η]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ποδας]{.greek-omitted} [εχοντα]{.greek-omitted} [βληθηναι]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γεενναν]{.greek-omitted} εις το πυρ το ασβεστον[9:45 | instance no. 2]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν [τ[ω]{.unclear}]{.greek-added} [του]{.corr} [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον [το]{.greek-added} [αλας]{.greek-added} [εαν]{.greek-added} [δε]{.greek-added} το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε [εχετε]{.greek-omitted} [εχεται]{.greek-added} εν εαυτοις αλας και [ειρηνευεται]{.greek-added} [ειρηνευετε]{.corr} εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας δια του περαν του ιορδανο[υ]{.unclear} και συμπορευονται παλιν οχλοι προς αυτον και ω[ς]{.unclear} ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι [επη]{.greek-added} [επηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted} [ει]{.greek-omitted} [εξεστιν]{.greek-omitted} [ανδρι]{.greek-omitted} [γυναικα]{.greek-omitted} [απολυσαι]{.greek-omitted} [πειραζοντες]{.greek-omitted} [αυτον]{.greek-omitted}[10:2]{.aside}

[ρωτησαν]{.greek-added} [αυτον]{.greek-added} [τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [εκεινω]{.greek-added} προσελθοντες [οι]{.greek-added} φαρισαιοι [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [επηρωτησαν]{.greek-omitted} [επηρωτων]{.greek-added} αυτον ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2 | instance no. 2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο μωσης[10:3]{.aside}

οι δε ειπον μωσης [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

[και]{.greek-omitted} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [μια]{.greek-omitted} σαρξ [μιαν]{.greek-added}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια [παλιν]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted}[10:10]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} παλιν [γενομενοι]{.greek-added} οι μαθηται αυτου περι [τουτου]{.greek-added} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [επηρωτων]{.greek-added} αυτον[10:10 | instance no. 2]{.aside}

και λεγει αυτοις [λεγει]{.greek-added} [αυτο[ι]{.unclear}ς]{.greek-added} [[εαν]{.unclear}]{.greek-added} [απολ[υ]{.unclear}ση]{.greek-added} ος εαν απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν [μη]{.greek-omitted} δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ευλογησεν]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου [εις]{.greek-omitted} [οδον]{.greek-omitted} [προσδραμων]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γονυπετησας]{.greek-omitted} [αυτον]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [διδασκαλε]{.greek-omitted} [αγαθε]{.greek-omitted} [τι]{.greek-omitted} [ποιησω]{.greek-omitted} [ινα]{.greek-omitted} [ζωην]{.greek-omitted} [αιωνιον]{.greek-omitted} [κληρονομησω]{.greek-omitted}[10:17]{.aside}

[και]{.greek-omitted} [εκπορευομενου]{.greek-omitted} [αυτου]{.greek-omitted} εις οδον προσδραμων εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις [αγαθον]{.greek-omitted} [αθαθον]{.greek-added} ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη [ψευδομαρτυρησης]{.greek-omitted} [ψευδομαρτυρησεις]{.greek-added} μη [αποστερησης]{.greek-omitted} [αποστερησεις]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω εν σοι υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων [κτηματα]{.greek-omitted} [πολλα]{.greek-omitted}[10:22]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [στυγνασας]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [λογω]{.greek-omitted} [απηλθεν]{.greek-omitted} [λυπουμενος]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [εχων]{.greek-omitted} κτηματα πολλα[10:22 | instance no. 2]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} [λεγει]{.greek-omitted} [εφη]{.greek-added} παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} [παντα]{.greek-omitted} [γαρ]{.greek-omitted} [δυνατα]{.greek-omitted} [εστιν]{.greek-omitted} [παρα]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ουδεις]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} [αφηκεν]{.greek-omitted} [οικιαν]{.greek-omitted} [η]{.greek-omitted} [αδελφους]{.greek-omitted} [η]{.greek-omitted} [αδελφας]{.greek-omitted} [η]{.greek-omitted} [πατερα]{.greek-omitted} [η]{.greek-omitted} [μητερα]{.greek-omitted} [η]{.greek-omitted} [γυναικα]{.greek-omitted} [η]{.greek-omitted} [τεκνα]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [ενεκεν]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted}[10:29]{.aside}

[αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν [η]{.greek-omitted} [αδελφους]{.greek-omitted} η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} του ευαγγελιου[10:29 | instance no. 2]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [παραλαβων]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [τους]{.greek-added} [δωδεκα]{.greek-added} ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [και]{.greek-omitted} [γραμματευσιν]{.greek-omitted} [και]{.greek-omitted} [κατακρινουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [θανατω]{.greek-omitted} [και]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted}[10:33]{.aside}

[αρχιερευσι]{.greek-added} [οτι]{.greek-omitted} [ιδου]{.greek-omitted} [αναβαινομεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} και [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδοθησεται]{.greek-omitted} [τοις]{.greek-omitted} [αρχιερευσιν]{.greek-omitted} [και]{.greek-omitted} [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33 | instance no. 2]{.aside}

και εμπαιξουσιν [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} αυτω και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και [ιωανης]{.greek-added} [ιωαννης]{.corr} οι υιοι [του]{.greek-added} ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν αιτησωμεν ποιησης ημιν[10:35]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτοις τι θελετε [ποιησαι]{.greek-omitted} [ποιεισαι]{.greek-added} [με]{.greek-omitted} υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες [αρχειν]{.greek-omitted} [αρχην]{.greek-added} των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[10:43]{.aside}

και ος εαν θελη υμων [γενεσθαι]{.greek-omitted} [γενεσθω]{.greek-added} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [εκπορευομενου]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} απο [ιεριχω]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [οχλου]{.greek-omitted} [ικανου]{.greek-omitted} [υιος]{.greek-omitted} [τιμαιου]{.greek-omitted} [βαρτιμαιος]{.greek-omitted} [ο]{.greek-omitted} [τυφλος]{.greek-omitted} [εκαθητο]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [προσαιτων]{.greek-omitted}[10:46]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [ιεριχω]{.greek-omitted} [και]{.greek-omitted} [εκπορευομενου]{.greek-omitted} [αυτου]{.greek-omitted} [απο]{.greek-omitted} ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον [προσαιτων]{.greek-omitted} [προσετων]{.greek-added}[10:46 | instance no. 2]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει εγειραι φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος ειπεν αυτω ραββουνι ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η [πιστις]{.greek-omitted} [πιστης]{.greek-added} σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις ιερουσαλημ εις [βηθσφαγη]{.greek-omitted} [και]{.greek-omitted} [βηθανιαν]{.greek-omitted} [προς]{.greek-omitted} [το]{.greek-omitted} [ορος]{.greek-omitted} [των]{.greek-omitted} [ελαιων]{.greek-omitted} [αποστελλει]{.greek-omitted} [δυο]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted}[11:1]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [εγγιζουσιν]{.greek-omitted} [εις]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [εις]{.greek-omitted} βηθσφαγη και βηθανιαν [προς]{.greek-added} [το]{.greek-added} [ορος]{.greek-added} [των]{.greek-added} [ελαιων]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηγγειζεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [ιερουσαλημ]{.greek-added} [και]{.greek-added} [ηλθεν]{.greek-added} [εις]{.greek-added} [βηθσφαγη]{.greek-added} προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1 | instance no. 2]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην [ευρισεται]{.greek-added} [ευρησετε]{.greek-omitted} [[ευρισετε]{.corr}]{.greek-added} πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθικε]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις [υμιν]{.greek-omitted} [υμων]{.greek-added} ειπη τι ποιειτε τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον [τον]{.greek-added} [πολον]{.greek-added} [πωλον]{.corr} δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και εκαθισεν επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ των δενδρων και εστρωννυον εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [ιεροσολυμα]{.greek-added} και εις το ιερον και περιβλεψαμενος [παντα]{.greek-omitted} [απαντα]{.greek-added} οψιας [ηδη]{.greek-omitted} [ηδει]{.greek-added} ουσης της ωρας εξηλθεν εις βηθανιαν μετα των [δεκα]{.greek-added} [δωδεκα]{.corr} [μαθητων]{.greek-added}[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην μακροθεν [εχουσαν]{.greek-omitted} [εχουσα]{.greek-added} φυλλα ηλθεν ει [αρα]{.greek-omitted} [ευρησει]{.greek-omitted} [τι]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [και]{.greek-omitted} [ελθων]{.greek-omitted} [επ]{.greek-omitted} [αυτην]{.greek-omitted} [ουδεν]{.greek-omitted} [ευρεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [φυλλα]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [ην]{.greek-omitted} [καιρος]{.greek-omitted} [συκων]{.greek-omitted}[11:13]{.aside}

[και]{.greek-omitted} [ιδων]{.greek-omitted} [συκην]{.greek-omitted} [μακροθεν]{.greek-omitted} [εχουσαν]{.greek-omitted} [φυλλα]{.greek-omitted} [ηλθεν]{.greek-omitted} [ει]{.greek-omitted} αρα [ευρησει]{.greek-omitted} [ευρισει]{.greek-added} τι εν αυτη και ελθων [επ]{.greek-omitted} [εν]{.greek-added} [αυτην]{.greek-omitted} [αυτη]{.greek-added} ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους [πωλουντας]{.greek-omitted} [πολουντας]{.greek-added} και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας [καθεδρας]{.greek-omitted} [τραπεζας]{.greek-added} των [πωλουντων]{.greek-omitted} [πολουντων]{.greek-added} τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως [αυτον]{.greek-omitted} [αυτων]{.greek-added} απολεσωσιν εφοβουντο γαρ αυτον [οτι]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [εξεπλησσετο]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted}[11:18]{.aside}

[και]{.greek-omitted} [ηκουσαν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [εζητουν]{.greek-omitted} [πως]{.greek-omitted} [αυτον]{.greek-omitted} [απολεσωσιν]{.greek-omitted} [εφοβουντο]{.greek-omitted} [γαρ]{.greek-omitted} [αυτον]{.greek-omitted} οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18 | instance no. 2]{.aside}

και οτε οψε εγενετο [εξεπορευετο]{.greek-omitted} [επορευετο]{.greek-added} εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και [αναμνησθεις]{.greek-omitted} [αναμνησθης]{.greek-added} ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηρανθη]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} εχετε [πιστιν]{.greek-omitted} [πιστην]{.greek-added} [θεου]{.greek-abbr}[11:22]{.aside}

αμην [γαρ]{.greek-omitted} λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν [και]{.corr} μη διακριθη εν τη καρδια αυτου αλλα πιστευση οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι αιτησθε πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι [αφιετε]{.greek-omitted} [αφιεται]{.greek-added} ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο εν τοις [ουρανοις]{.greek-abbr} [αφησει]{.greek-added} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [υμων]{.greek-omitted}[11:25]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [στηκητε]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [αφιετε]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} [εχετε]{.greek-omitted} [κατα]{.greek-omitted} [τινος]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} τα παραπτωματα υμων[11:25 | instance no. 2]{.aside}

και ερχονται παλιν εις ιεροσολυμα [και]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [περιπατουντος]{.greek-omitted} [αυτου]{.greek-omitted} [ερχονται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted}[11:27]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [ερχονται]{.greek-omitted} [παλιν]{.greek-omitted} [ηλθεν]{.greek-added} [ο]{.greek-added} [ις]{.greek-added} εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27 | instance no. 2]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} [δεδωκεν]{.greek-added} ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω [καγω]{.greek-added} υμας [και]{.greek-omitted} [εγω]{.greek-omitted} ενα [λογον]{.greek-omitted} [λογων]{.greek-added} και αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} [και]{.greek-added} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

[αλλ]{.greek-omitted} [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον [λαον]{.greek-omitted} [οχλον]{.greek-added} απαντες γαρ ειχον τον ιωαννην οτι οντως [προ]{.greek-added} [προφητης]{.greek-omitted} [ην]{.greek-omitted}[11:32]{.aside}

[αλλ]{.greek-omitted} [ειπωμεν]{.greek-omitted} [εξ]{.greek-omitted} [ανθρωπων]{.greek-omitted} [εφοβουντο]{.greek-omitted} [τον]{.greek-omitted} [λαον]{.greek-omitted} [απαντες]{.greek-omitted} [γαρ]{.greek-omitted} [ειχον]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [οτι]{.greek-omitted} [οντως]{.greek-omitted} [προφητης]{.greek-omitted} [φητης]{.greek-added} [ην]{.greek-omitted} [εστι]{.greek-added}[11:32 | instance no. 2]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [την]{.greek-added} [παραβολην]{.greek-added} [ταυτην]{.greek-added} αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον [εδειραν]{.greek-omitted} [εδηραν]{.greek-added} και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους [αλλους]{.greek-omitted} [τους]{.greek-omitted} [μεν]{.greek-omitted} [δεροντες]{.greek-omitted} [τους]{.greek-omitted} [δε]{.greek-omitted} [αποκτενοντες]{.greek-omitted}[12:5]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-omitted} [αλλον]{.greek-omitted} [απεστειλεν]{.greek-omitted} [κακεινον]{.greek-omitted} [απεκτειναν]{.greek-omitted} [και]{.greek-omitted} [πολλους]{.greek-omitted} αλλους τους μεν [δεροντες]{.greek-omitted} [δαιροντες]{.greek-added} τους δε αποκτενοντες[12:5 | instance no. 2]{.aside}

ετι ουν ενα υιον εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον προς αυτους εσχατον λεγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστη]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους [την]{.greek-omitted} [παραβολην]{.greek-omitted} [ειπεν]{.greek-omitted} [και]{.greek-omitted} [αφεντες]{.greek-omitted} [αυτον]{.greek-omitted} [απηλθον]{.greek-omitted}[12:12]{.aside}

[και]{.greek-omitted} [εζητουν]{.greek-omitted} [αυτον]{.greek-omitted} [κρατησαι]{.greek-omitted} [και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [εγνωσαν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12 | instance no. 2]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [αποστελλουσιν]{.greek-added} [οι]{.greek-added} [αρχιερεις]{.greek-added} [και]{.greek-added} [οι]{.greek-added} [γραμματεις]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι [αληθεις]{.greek-added} [αληθης]{.corr} ει και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι [δηναριον]{.greek-omitted} [δυναριον]{.greek-added} ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και [ε]{.greek-added} [εθαυμασαν]{.greek-omitted} [επ]{.greek-omitted} [αυτω]{.greek-omitted}[12:17]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αποδοτε]{.greek-omitted} [τα]{.greek-omitted} [καισαρος]{.greek-omitted} [καισαρι]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [και]{.greek-omitted} [εθαυμασαν]{.greek-omitted} [θαυμασαν]{.greek-added} επ αυτω[12:17 | instance no. 2]{.aside}

και ερχονται σαδδουκαιοι προς αυτον [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ερχονται]{.greek-added} [σαδδουκαιοι]{.greek-added} [προς]{.greek-added} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} οιτινες λεγουσιν αναστασιν μη ειναι και [επηρωτησαν]{.greek-omitted} [επηρατησαν]{.greek-added} αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [δε]{.greek-added} αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα εσχατη [δε]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω μωσεως επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω [ο]{.greek-omitted} [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} [ι[α]{.unclear}]{.greek-added} [ισαακ]{.corr} και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} [[θεος]{.greek-abbr}]{.greek-added} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων εις των γραμματεων ακουσας αυτων συζητουντων [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [προσηλθεν]{.greek-added} [εις]{.greek-added} [των]{.greek-added} [γραμματεων]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [ακουσας]{.greek-added} [συζητουντων]{.greek-added} [των]{.greek-added} [σαδδουκαιων]{.greek-added} [μετ]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} ειδως οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη [παντων]{.greek-omitted} [πασων]{.greek-added} εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω [οτι]{.greek-omitted} πρωτη [παντων]{.greek-omitted} [των]{.greek-omitted} [εντολων]{.greek-omitted} [ακουε]{.greek-omitted} [ισραηλ]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ημων]{.greek-omitted} [κυριος]{.greek-omitted} [εις]{.greek-omitted} [εστιν]{.greek-omitted}[12:29]{.aside}

[πασων]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [απεκριθη]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [πρωτη]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29 | instance no. 2]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου [αυτη]{.greek-omitted} πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα [αυτον]{.greek-omitted} [επερωτησαι]{.greek-omitted}[12:34]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ιδων]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [νουνεχως]{.greek-omitted} [απεκριθη]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ου]{.greek-omitted} [μακραν]{.greek-omitted} [ει]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [βασιλειας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [ουκετι]{.greek-omitted} [ετολμα]{.greek-omitted} αυτον επερωτησαι[12:34 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} [του]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} [και]{.greek-omitted} ποθεν υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και [πρωτοκαθεδριας]{.greek-omitted} [προτοκαθεδριας]{.greek-added} εν ταις [συναγωγαις]{.greek-omitted} [συναγογαις]{.greek-added} και [πρωτοκλισιας]{.greek-omitted} [προτοκλισιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των [χηρων]{.greek-omitted} [χειρων]{.greek-added} και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του [γαζο]{.greek-added} [γαζοφυλακιου]{.greek-omitted} [εθεωρει]{.greek-omitted} [πως]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [βαλλει]{.greek-omitted} [χαλκον]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [γαζοφυλακιον]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [πλουσιοι]{.greek-omitted} [εβαλλον]{.greek-omitted} [πολλα]{.greek-omitted}[12:41]{.aside}

[και]{.greek-omitted} [καθισας]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [κατεναντι]{.greek-omitted} [του]{.greek-omitted} [γαζοφυλακιου]{.greek-omitted} [φυλακιου]{.greek-added} εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι εβαλλον πολλα[12:41 | instance no. 2]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των βαλλοντων εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισσευματος]{.greek-added} αυτοις [εβαλον]{.greek-omitted} [εβαλλον]{.greek-added} αυτη δε εκ [της]{.greek-omitted} [υστερησεως]{.greek-omitted} [του]{.greek-added} [υστερηματος]{.greek-added} αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου [εκ]{.greek-added} [του]{.greek-added} [ιερου]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [εκπορευομενου]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας [ου]{.greek-omitted} [μη]{.greek-omitted} [αφεθη]{.greek-omitted} [λιθος]{.greek-omitted} [επι]{.greek-omitted} [λιθω]{.greek-omitted} [ος]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [καταλυθη]{.greek-omitted}[13:2]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [βλεπεις]{.greek-omitted} [ταυτας]{.greek-omitted} [τας]{.greek-omitted} [μεγαλας]{.greek-omitted} [οικοδομας]{.greek-omitted} ου μη αφεθη [ωδε]{.greek-added} λιθος επι λιθω ος ου μη καταλυθη[13:2 | instance no. 2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και [ιωαννης]{.greek-added} [και]{.greek-added} ιακωβος και [ιωαννης]{.greek-omitted} [και]{.greek-omitted} ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη παντα ταυτα συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις [αυτοις]{.greek-omitted} ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι αρχαι ωδινων ταυτα[13:8]{.aside}

βλεπετε δε [υμεις]{.greek-omitted} [εαυτους]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [γαρ]{.greek-omitted} [υμας]{.greek-omitted} [εις]{.greek-omitted} [συνεδρια]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [συναγωγας]{.greek-omitted} [δαρησεσθε]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [ηγεμονων]{.greek-omitted} [και]{.greek-omitted} [βασιλεων]{.greek-omitted} [σταθησεσθε]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted}[13:9]{.aside}

[ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} βλεπετε [δε]{.greek-omitted} υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις [συναγωγας]{.greek-omitted} [υναγωγας]{.greek-added} δαρησεσθε και επι ηγεμονων και βασιλεων [σταθησεσθε]{.greek-omitted} [αχθησεσθε]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις[13:9 | instance no. 2]{.aside}

και εις παντα τα εθνη δ[ε]{.unclear}ι πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε αγαγωσιν υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [μεριμνατε]{.greek-added} τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ [υμεις]{.greek-added} εστε [υμεις]{.greek-omitted} οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [οταν]{.greek-added} ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

[και]{.greek-added} ο [δε]{.greek-omitted} επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον [ων]{.greek-omitted} μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι [θλιψις]{.greek-omitted} [θλιψεις]{.greek-added} οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας ουκ αν εσωθη πασα σαρξ [αλλα]{.greek-omitted} [δια]{.greek-omitted} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted} [ους]{.greek-omitted} [εξελεξατο]{.greek-omitted} [εκολοβωσεν]{.greek-omitted} [τας]{.greek-omitted} [ημερας]{.greek-omitted}[13:20]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [κυριος]{.greek-omitted} [εκολοβωσεν]{.greek-omitted} [τας]{.greek-omitted} [ημερας]{.greek-omitted} [ουκ]{.greek-omitted} [αν]{.greek-omitted} [εσωθη]{.greek-omitted} [πασα]{.greek-omitted} [σαρξ]{.greek-omitted} αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας[13:20 | instance no. 2]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη [πιστευετε]{.greek-omitted} [ποιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου [προειρηκα]{.greek-omitted} [προειρητα]{.greek-added} υμιν [παντα]{.greek-omitted} [απαντα]{.greek-added}[13:23]{.aside}

αλλ [εν]{.greek-added} [εκειναις]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτοις]{.greek-added} [μαθηταις]{.greek-added} εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις [αι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως πολλης και δοξης[13:26]{.aside}

και τοτε αποστελει τους [αγγε]{.greek-added} [αγγελους]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [επισυναξει]{.greek-omitted} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted} [αυτου]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ανεμων]{.greek-omitted} [απ]{.greek-omitted} [ακρου]{.greek-omitted} [γης]{.greek-omitted} [εως]{.greek-omitted} [ακρου]{.greek-omitted} [ουρανου]{.greek-omitted}[13:27]{.aside}

[και]{.greek-omitted} [τοτε]{.greek-omitted} [αποστελει]{.greek-omitted} [τους]{.greek-omitted} [λους]{.greek-added} [αγγελους]{.greek-omitted} αυτου και επισυναξει τους εκλεκτους αυτου εκ των [τεσσαρων]{.greek-omitted} [τεσαρων]{.greek-added} ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27 | instance no. 2]{.aside}

απο δε της συκης μαθετε την παραβολην οταν [αυτης]{.greek-omitted} ηδη ο κλαδος [αυτης]{.greek-added} απαλος γενηται και εκφυη τα φυλλα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος εστιν[13:28]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και [υμ[ι]{.unclear}]{.greek-added} [υμεις]{.corr} οταν [ιδητε]{.greek-added} ταυτα [ιδητε]{.greek-omitted} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν [οτι]{.greek-omitted} ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added} [ειπεν]{.greek-added} [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [εαυτου]{.greek-added} [μαθηταις]{.greek-added} [ο]{.greek-added} [[ουρανος]{.greek-abbr}]{.greek-added} [και]{.greek-added} [η]{.greek-added} [γη]{.greek-added} [παρελευσεται]{.greek-added} [οι]{.greek-added} [δε]{.greek-added} [λογοι]{.greek-added} [μου]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [παρελθωσι]{.greek-added}[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [οι]{.greek-omitted} εν [τω]{.greek-added} [ουρανω]{.greek-abbr} ουδε ο υιος ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε [και]{.greek-omitted} προσευχεσθε ουκ οιδατε γαρ ποτε ο [και]{.greek-added} [καιρος]{.greek-omitted} [εστιν]{.greek-omitted}[13:33]{.aside}

[ρος]{.greek-added} [βλεπετε]{.greek-omitted} [αγρυπνειτε]{.greek-omitted} [και]{.greek-omitted} [προσευχεσθε]{.greek-omitted} [ουκ]{.greek-omitted} [οιδατε]{.greek-omitted} [γαρ]{.greek-omitted} [ποτε]{.greek-omitted} [ο]{.greek-omitted} [καιρος]{.greek-omitted} εστιν[13:33 | instance no. 2]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις [αυτου]{.greek-omitted} την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η μεσονυκτιου η [αλεκτοροφωνιας]{.greek-omitted} [αλεκτριοφωνιας]{.greek-added} η πρωι[13:35]{.aside}

μη [εξαιφνης]{.greek-added} ελθων [εξαιφνης]{.greek-omitted} ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου [εν]{.greek-added} [βηθανια]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [οντος]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} εν βηθανια εν τη οικια σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

[και]{.greek-omitted} [οντος]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3 | instance no. 2]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο [το]{.greek-added} [μυρον]{.greek-added} πραθηναι επανω τριακοσιων δηναριων και δοθηναι [τοις]{.greek-omitted} πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι [αυτη]{.greek-omitted} κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν [θελητε]{.greek-omitted} [θεληται]{.greek-added} δυνασθε [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον [λαληθησεται]{.greek-added} και ο εποιησεν αυτη [λαληθησεται]{.greek-omitted} εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης [εις]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [απηλθεν]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [αρχιερεις]{.greek-omitted} [ινα]{.greek-omitted} [παραδω]{.greek-omitted} [αυτον]{.greek-omitted} [αυτοις]{.greek-omitted}[14:10]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [καιρω]{.greek-added} [ο]{.greek-omitted} [εκεινω]{.greek-added} ιουδας ο ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10 | instance no. 2]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλαντο]{.greek-omitted} [επηγγειλατο]{.greek-added} αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες [ετοιμασωμεν]{.greek-omitted} [ετοιμασομεν]{.greek-added} ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθη ειπατε τω οικοδεσποτη [οτι]{.greek-omitted} ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει [ανωγεον]{.greek-omitted} [ανωγεων]{.greek-added} μεγα εστρωμενον ετοιμον εκει [ετοι]{.greek-added} [ετοιμασατε]{.greek-omitted} [ημιν]{.greek-omitted}[14:15]{.aside}

[μασατε]{.greek-added} [και]{.greek-omitted} [αυτος]{.greek-omitted} υμιν [δειξει]{.greek-omitted} [ανωγεον]{.greek-omitted} [μεγα]{.greek-omitted} [εστρωμενον]{.greek-omitted} [ετοιμον]{.greek-omitted} [εκει]{.greek-omitted} [ετοιμασατε]{.greek-omitted} [ημιν]{.greek-omitted}[14:15 | instance no. 2]{.aside}

[και]{.greek-omitted} εξηλθον [ουν]{.greek-added} οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των [δυ[―]{.gap}δεκα]{.greek-added} [δωδεκα]{.corr}[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με [ο]{.greek-omitted} εσθιων μετ εμου[14:18]{.aside}

οι δε [ηρρξαντο]{.greek-added} [ηρξαντο]{.corr} [λυπεισθαι]{.greek-omitted} [και]{.greek-omitted} λεγειν αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν [αυτος]{.greek-added} [αυτοις]{.corr} εις εκ των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

[και]{.greek-added} ο μεν [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [υπαγει]{.greek-omitted} [καθως]{.greek-omitted} [γεγραπται]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted} [ουαι]{.greek-omitted} [δε]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [εκεινω]{.greek-omitted} [δι]{.greek-omitted} [ου]{.greek-omitted} [ο]{.greek-omitted} υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} [τον]{.greek-added} αρτον [και]{.greek-added} ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον ευχαριστησας εδωκεν αυτοις [και]{.greek-omitted} [επιον]{.greek-omitted} [εξ]{.greek-omitted} [αυτου]{.greek-omitted} [παντες]{.greek-omitted}[14:23]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [ευχαριστησας]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτοις]{.greek-omitted} και επιον εξ αυτου παντες[14:23 | instance no. 2]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [[π]{.unclear}κανδαλισθησεσθε]{.greek-added} [σκανδαλισθησεσθε]{.corr} εν εμοι εν τη νυκτι ταυτη οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα [της]{.greek-added} [ποιμνης]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν η δις αλεκτορα φωνησαι τρις [απαρνηση]{.greek-omitted} [απαρνη]{.greek-added} [με]{.greek-omitted}[14:30]{.aside}

[ση]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [σοι]{.greek-omitted} [οτι]{.greek-omitted} [συ]{.greek-omitted} [σημερον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} [πριν]{.greek-omitted} [η]{.greek-omitted} [δις]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} [τρις]{.greek-omitted} [απαρνηση]{.greek-omitted} με[14:30 | instance no. 2]{.aside}

ο δε εκπερισσου [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν [με]{.greek-omitted} δεη συναποθανειν σοι ου μη σε απαρνησωμαι ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου καθισατε ωδε εως προσευξωμαι[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και [προσελθων]{.greek-omitted} [προελθων]{.greek-added} μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον απ εμου τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις [ουκ]{.greek-omitted} [ισχυσας]{.greek-omitted} [μιαν]{.greek-omitted} [ωραν]{.greek-omitted} [γρηγορησαι]{.greek-omitted}[14:37]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [και]{.greek-omitted} [ευρισκει]{.greek-omitted} [αυτους]{.greek-omitted} [καθευδοντας]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [σιμων]{.greek-omitted} [καθευδεις]{.greek-omitted} ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37 | instance no. 2]{.aside}

[γρηγορειται]{.greek-added} [γρηγορειτε]{.corr} και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ ηδεισαν [τι]{.greek-omitted} αυτω [αποκριθωσιν]{.greek-omitted} [αποκριθηναι]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added}[14:42]{.aside}

και [ευθεως]{.greek-omitted} ετι αυτου λαλουντος [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ετι]{.greek-added} [λαλουντος]{.greek-added} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [προς]{.greek-added} [τους]{.greek-added} [μαθητας]{.greek-added} παραγινεται ιουδας εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των [αρχιερεων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted}[14:43]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [ετι]{.greek-omitted} [αυτου]{.greek-omitted} [λαλουντος]{.greek-omitted} [παραγινεται]{.greek-omitted} [ιουδας]{.greek-omitted} [εις]{.greek-omitted} [ων]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [μετα]{.greek-omitted} [μαχαιρων]{.greek-omitted} [και]{.greek-omitted} [ξυλων]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} αρχιερεων και [των]{.greek-omitted} γραμματεων και [των]{.greek-omitted} πρεσβυτερων[14:43 | instance no. 2]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και [απαγαγετε]{.greek-omitted} [απαγετε]{.greek-added} ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω [ραββι]{.greek-omitted} [ραβι]{.greek-added} [ραββι]{.greek-omitted} [ραβι]{.greek-added} και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστ[η]{.unclear}κοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος [σινδονα]{.greek-omitted} [συνδονα]{.greek-added} επι γυμνου και κρατουσιν [αυτον]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[14:51]{.aside}

[και]{.greek-omitted} [εις]{.greek-omitted} [τις]{.greek-omitted} [νεανισκος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted} [περιβεβλημενος]{.greek-omitted} [σινδονα]{.greek-omitted} [επι]{.greek-omitted} [γυμνου]{.greek-omitted} [και]{.greek-omitted} [κρατουσιν]{.greek-omitted} αυτον οι νεανισκοι[14:51 | instance no. 2]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν [ηκολουθησεν]{.greek-omitted} [ηκολουθει]{.greek-added} αυτω εως [εσω]{.greek-omitted} [εσωθεν]{.greek-added} εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι [αυτων]{.greek-added} ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι [και]{.greek-added} ημεις [ηκουσαμεν]{.greek-omitted} [ακηκοαμεν]{.greek-added} αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς [επηρωτα]{.greek-omitted} [απηρωτα]{.greek-added} αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο υιος του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας [αυτω]{.greek-added} [αυτου]{.corr} λεγει τι ετι χρειαν εχομεν [μαρτυρων]{.greek-omitted} [μαρτυριας]{.greek-added}[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν φαινεται οι δε παντες [κατεκριναν]{.greek-omitted} [κατεκρυναν]{.greek-added} αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} και οι υπηρεται ραπισμασιν [αυτον]{.greek-omitted} [εβαλλον]{.greek-omitted}[14:65]{.aside}

[και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [τινες]{.greek-omitted} [εμπτυειν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [περικαλυπτειν]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [κολαφιζειν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} [προφητευσον]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [υπηρεται]{.greek-omitted} [ραπισμασιν]{.greek-omitted} αυτον εβαλλον[14:65 | instance no. 2]{.aside}

και [οντος]{.greek-omitted} [οντως]{.greek-added} του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε επισταμαι τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και [ευθεως]{.greek-added} αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνησατο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} [τουτον]{.greek-omitted} ον [υμεις]{.greek-added} [λεγετε]{.greek-omitted} [λεγεται]{.greek-added}[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι [δις]{.greek-omitted} [απαρνηση]{.greek-omitted} [με]{.greek-omitted} [τρις]{.greek-omitted} [και]{.greek-omitted} [επιβαλων]{.greek-omitted} [εκλαιεν]{.greek-omitted}[14:72]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [δευτερου]{.greek-omitted} [αλεκτωρ]{.greek-omitted} [εφωνησεν]{.greek-omitted} [και]{.greek-omitted} [ανεμνησθη]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [το]{.greek-omitted} [ρημα]{.greek-omitted} [ο]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [πριν]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} δις απαρνηση με τρις και επιβαλων [εκλαιεν]{.greek-omitted} [εκλαιε]{.greek-added}[14:72 | instance no. 2]{.aside}

### Chapter 15

και ευθεως επι το πρωι [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} [απηνεγκαν]{.greek-omitted} [απηγαγον]{.greek-added} και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν [αυτου]{.greek-omitted} [αυτω]{.greek-added} οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος [βαραβας]{.greek-added} [βαραββας]{.corr} μετα των συστασιαστων δεδεμενος οιτινες εν [τη]{.greek-omitted} στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει [εποιησεν]{.greek-added} [εποιει]{.corr} αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον [παρεδωκαν]{.greek-added} παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεπεισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν σταυρωσον αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσως]{.greek-added} εκραξαν σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [σφαγγελλωσας]{.greek-added} ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης [ο]{.greek-omitted} [εστιν]{.greek-omitted} [πραιτωριον]{.greek-omitted} [και]{.greek-omitted} [συγκαλουσιν]{.greek-omitted} [ολην]{.greek-omitted} [την]{.greek-omitted} [σπειραν]{.greek-omitted}[15:16]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} οι [δε]{.greek-omitted} στρατιωται απηγαγον [αυτον]{.greek-omitted} [τον]{.greek-added} [εσω]{.greek-omitted} [της]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [αυλης]{.greek-omitted} [αυλην]{.greek-added} [του]{.greek-added} [καιαφα]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16 | instance no. 2]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον [και]{.greek-added} [λεγειν]{.greek-added} χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον [τω]{.greek-added} [καιρω]{.greek-added} [εκειω]{.greek-added} [οι]{.greek-added} [στρατιωται]{.greek-added} [παραλαβοντος]{.greek-added} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [εξαγουσιν]{.greek-added} [αυτον]{.greek-added} ινα [σταυρωσωσιν]{.greek-omitted} [σταυρωσουσιν]{.greek-added} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και [φε]{.greek-added} [φερουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [επι]{.greek-omitted} [γολγοθα]{.greek-omitted} [τοπον]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [μεθερμηνευομενον]{.greek-omitted} [κρανιου]{.greek-omitted} [τοπος]{.greek-omitted}[15:22]{.aside}

[και]{.greek-omitted} [φερουσιν]{.greek-omitted} [ρουσιν]{.greek-added} αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22 | instance no. 2]{.aside}

και [εδιδουν]{.greek-omitted} [εδωκαν]{.greek-added} αυτω πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [σταυρουσι]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις [οικοδομων]{.greek-omitted} [οικονομων]{.greek-added}[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως [δε]{.greek-added} και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [ελεγον]{.greek-omitted} [αλλους]{.greek-omitted} [εσωσεν]{.greek-omitted} [εαυτον]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [σωσαι]{.greek-omitted}[15:31]{.aside}

[εμπε]{.greek-added} [ομοιως]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [εμπαιζοντες]{.corr} προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31 | instance no. 2]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν αυτω και οι [συνεσταυρωμενοι]{.greek-omitted} [συσταυρωθεντες]{.greek-added} αυτω ωνειδιζον αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη [εννατη]{.greek-added} ωρα [τη]{.greek-omitted} [ενατη]{.greek-omitted} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι λιμα [σαβαχθανι]{.greek-omitted} [σαβαχανι]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις [τε]{.greek-omitted} καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας καθελειν [αυτον]{.greek-omitted} [αυτων]{.greek-added}[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν [αλληθος]{.greek-added} [αληθως]{.greek-omitted} [[αλληθως]{.corr}]{.greek-added} ο [ανθρωπος]{.greek-abbr} ουτος υιος ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και [γυναικες]{.greek-omitted} [γυναικαις]{.greek-added} απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και [η]{.greek-added} μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} προσαββατον[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [ελθων]{.greek-added} ιωσηφ ο απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ει]{.greek-omitted} [παλαι]{.greek-omitted} [απεθανεν]{.greek-omitted}[15:44]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [εθαυμασεν]{.greek-omitted} [ει]{.greek-omitted} [ηδη]{.greek-omitted} [τεθνηκεν]{.greek-omitted} [και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [κεντυριωνα]{.greek-omitted} επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44 | instance no. 2]{.aside}

και γνους απο του [κεντηριωνος]{.greek-added} [κεντ[υ]{.unclear}ριωνος]{.corr} εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων [αυτον]{.greek-omitted} [αυτο]{.greek-added} [ενειλησεν]{.greek-omitted} [ενειλησε]{.greek-added} τη σινδονι και [κατεθηκεν]{.greek-omitted} [εθηκεν]{.greek-added} [αυτον]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι [την]{.greek-omitted} [τη]{.greek-added} [θυραν]{.greek-omitted} [θυρα]{.greek-added} του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι [αλειψωσιν]{.greek-omitted} [αλειψωσι]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι [το]{.greek-omitted} [τω]{.greek-added} [μνημειον]{.greek-omitted} [μνημειω]{.greek-added} ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ε[ι]{.unclear}δον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον εσταυρωμενον ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [αναστας]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι πρωτη [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδανηνη]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [και]{.greek-omitted} [κλαιουσιν]{.greek-omitted}[16:10]{.aside}

[εκεινη]{.greek-omitted} [πορευθεισα]{.greek-omitted} [απηγγειλεν]{.greek-omitted} [τοις]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [γενομενοις]{.greek-omitted} [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10 | instance no. 2]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την απιστιαν αυτων και [σκη]{.greek-added} [σκληροκαρδιαν]{.greek-omitted} [[σκλωροκαρδιαν]{.corr}]{.greek-added} οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι [πιωσιν]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [αυτους]{.greek-omitted} [βλαψη]{.greek-omitted} [επι]{.greek-omitted} [πι]{.greek-added} [αρρωστους]{.greek-omitted} [χειρας]{.greek-omitted} [επιθησουσιν]{.greek-omitted} [και]{.greek-omitted} [καλως]{.greek-omitted} [εξουσιν]{.greek-omitted}[16:18]{.aside}

[οφεις]{.greek-omitted} [αρουσιν]{.greek-omitted} [καν]{.greek-omitted} [θανασιμον]{.greek-omitted} [τι]{.greek-omitted} [πιωσιν]{.greek-omitted} [ωσιν]{.greek-added} ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18 | instance no. 2]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

