---
title: "Collation of Byz^RP^ vs 30976 (976)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 976 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=30976).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 976                                   	| λογος                              	|
| 976 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 976 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 976               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 976                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 976 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 976                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 18

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [στραφητε]{.greek-omitted} [και]{.greek-omitted} [γενησθε]{.greek-omitted} [ως]{.greek-omitted} [τα]{.greek-omitted} [παιδια]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [εισελθητε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος εαν δεξητ[αι]{.unclear} παιδιον τοιουτον εν επι τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν σκανδαλιση ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος εις τον τραχηλον αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων [α]{.unclear}ν[α]{.unclear}γκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

ει δε [η]{.unclear} χειρ σου η ο πους σου σκανδαλιζει σε εκκοψον αυτα και βαλε απο σ[ου]{.unclear} καλον σοι εστιν εισελθειν εις την ζωην χωλον η κυλλον η δυο χειρας η δυο ποδας εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και ει [ο]{.greek-omitted} οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εις την ζωην εισελθειν η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

ορατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} το προσωπον του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο υιος του [ανθρωπου]{.greek-abbr} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει εαν γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα [ενενηκοντα]{.greek-omitted} [εννενηκοντα]{.greek-added} εννεα επι τα ορη πορευθεις ζητει το πλανωμενον[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η επι τοις [ενενηκοντα]{.greek-omitted} [εννενηκοντα]{.greek-added} εννεα τοις μη [πε]{.greek-added} [πεπλανημενοις]{.greek-omitted} [πλανημενοις]{.greek-added}[18:13]{.aside}

ουτως ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} θελημα εμπροσθεν του [πατρος]{.greek-abbr} υμων του εν [ουρανοις]{.greek-abbr} ινα [αποληται]{.greek-omitted} [απωληται]{.greek-added} [εμπροσθεν]{.greek-added} εις των μικρων τουτων[18:14]{.aside}

εαν δε αμαρτηση εις σε ο αδελφος σου υπαγε [και]{.greek-omitted} ελεγξον αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη ακουση παραλαβε μετα [σου]{.greek-omitted} [σεαυτου]{.greek-added} ετι ενα η δυο ινα επι στοματος δυο μαρτυρων η τριων σταθη παν ρημα[18:16]{.aside}

εαν δε παρακουση αυτων ειπε τη εκκλησια εαν δε και της εκκλησιας παρακουση εστω σοι ωσπερ ο εθνικος και ο τελωνης[18:17]{.aside}

αμην λεγω υμιν οσα εαν δησητε επι της γης εσται δεδεμενα εν [τω]{.greek-omitted} [ουρανω]{.greek-abbr} και οσα εαν [λυσητε]{.greek-omitted} [λυσηται]{.greek-added} επι της γης εσται λελυμενα εν τω [ουρανω]{.greek-abbr}[18:18]{.aside}

παλιν αμην λεγω υμιν οτι εαν δυο υμων συμφωνησωσιν επι της γης περι παντος πραγματος ου εαν αιτησωνται γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:19]{.aside}

ου γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο η τρεις συνηγμενοι εις το εμον ονομα εκει ειμι εν μεσω αυτων[18:20]{.aside}

τοτε προσελθων αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} ποσακις αμαρτησει εις εμε ο αδελφος μου και αφησω αυτω εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} ου λεγω σοι εως επτακις αλλ εως εβδομηκοντακις επτα[18:22]{.aside}

δια τουτο ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος [ηθελησεν]{.greek-omitted} [ηθελησε]{.greek-added} συναραι λογον μετα των δουλων αυτου[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν αυτον ο [κυριος]{.greek-abbr} αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} μακροθυμησον επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο [κυριος]{.greek-abbr} του δουλου εκεινου απελυσεν αυτον και το δανειον αφηκεν αυτω[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον δηναρια και κρατησας αυτον [επνιγεν]{.greek-omitted} [επνιγε]{.greek-added} λεγων αποδος μοι ει τι οφειλεις[18:28]{.aside}

πεσων ουν ο συνδουλος αυτου εις τους ποδας αυτου παρεκαλει αυτον λεγων μακροθυμησον επ εμοι και [παντα]{.greek-added} [σοι]{.greek-added} αποδωσω [σοι]{.greek-omitted}[18:29]{.aside}

ο δε ουκ ηθελεν αλλα απελθων εβαλεν αυτον εις φυλακην εως ου αποδω το οφειλομενον[18:30]{.aside}

ιδοντες δε οι συνδουλοι αυτου τα γενομενα ελυπηθησαν σφοδρα και ελθοντες διεσαφησαν τω [κυριω]{.greek-abbr} [εαυτων]{.greek-omitted} [αυτων]{.greek-added} παντα τα γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο [κυριος]{.greek-abbr} αυτου λεγει αυτω δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι επει παρεκαλεσας με[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} σε ηλεησα[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} [αυτου]{.greek-omitted} παρεδωκεν αυτον τοις βασανισταις εως ου αποδω παν το οφειλομενον αυτω[18:34]{.aside}

ουτως και ο [πατηρ]{.greek-abbr} μου ο [επουρανιος]{.greek-abbr} ποιησει υμιν εαν μη αφητε εκαστος τω αδελφω αυτου απο των καρδιων υμων τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και προσηλθον αυτω οι φαρισαιοι πειραζοντες αυτον και λεγοντες αυτω ει εξεστιν [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ ανεγνωτε οτι ο [ποιησας]{.greek-omitted} [ποι]{.greek-added} [ησας]{.greek-added} απ αρχης αρσεν και θηλυ εποιησεν αυτους[19:4]{.aside}

και ειπεν [ενεκεν]{.greek-omitted} [ενεκα]{.greek-added} τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-added} και την [μητερα]{.greek-abbr} και προσκολληθησεται τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ενετειλατο δουναι βιβλιον αποστασιου και απολυσαι αυτην[19:7]{.aside}

λεγει αυτοις οτι [μωσης]{.greek-omitted} [μωυσης]{.greek-added} προς την σκληροκαρδιαν υμων επετρεψεν υμιν απολυσαι τας γυναικας υμων απ αρχης δε ου γεγονεν ουτως[19:8]{.aside}

λεγω δε υμιν [οτι]{.greek-omitted} ος αν απολυση την γυναικα αυτου μη επι πορνεια και γαμηση αλλην μοιχαται και ο απολελυμενην γαμησας μοιχαται[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτως εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφερει γαμησαι[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες [χωρουσιν]{.greek-omitted} [χωρουσι]{.greek-added} τον λογον τουτον αλλ οις δεδοται[19:11]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ ευνουχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} εγεννηθησαν ουτως και εισιν ευνουχοι οιτινες ευνουχισθησαν υπο των [ανθρωπων]{.greek-abbr} και εισιν ευνουχοι οιτινες ευνουχισαν εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε προσηνεχθη αυτω παιδια ινα τας χειρας επιθη αυτοις και προσευξηται οι δε μαθηται επετιμησαν αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε τα παιδια και μη [κωλυετε]{.greek-omitted} [κωλυητε]{.greek-added} αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και επιθεις αυτοις τας χειρας επορευθη εκειθεν[19:15]{.aside}

και [ι]{.greek-supplied}δου εις προσελθων ειπεν αυτω διδασκαλε αγαθε τι αγαθον ποιησω ινα εχω ζωην αιωνιον[19:16]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr} ει δε θελεις εισελθειν εις την ζωην τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το ου φονευσεις ου μοιχευσεις ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} και αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[19:19]{.aside}

λεγει αυτω ο νεανισκος [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} εφυλαξαμην εκ νεοτητος μου τι ετι υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελεις τελειος ειναι υπαγε πωλησον σου τα υπαρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον [απηλθεν]{.greek-omitted} [απ[η]{.unclear}λθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως πλουσιος εισελευσεται εις την βασιλειαν των ουρανων[19:23]{.aside}

παλιν δε λεγω υμιν ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [τρυπηματος]{.greek-omitted} [τρυμαλιας]{.greek-added} ραφιδος διελθειν [η]{.unclear} πλουσιον εις την βασιλειαν [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} εισελθειν[19:24]{.aside}

[ακουσαντες]{.greek-omitted} [ακουσαν]{.greek-added} [τες]{.greek-added} δε οι μαθηται αυτου εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

εμβλεψας δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα δε [θεω]{.greek-abbr} παντα δυνατα [εστι]{.greek-added}[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν καθιση ο υιος του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου [καθισεσθε]{.greek-omitted} [καθησεσθε]{.greek-added} και υμεις επι δωδεκα θρονους κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας ος αφηκεν οικιας η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν του ονοματος μου εκατονταπλασιονα ληψεται και ζωην [αιωνιον]{.greek-omitted} [αιωνι]{.greek-added} [ον]{.greek-added} κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[19:30]{.aside}

### Chapter 20

ομοια γαρ εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

[και]{.greek-omitted} συμφωνησας [δε]{.greek-added} μετα των εργατων εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι [την]{.greek-added} τριτην ωραν ειδεν αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

και εκεινοις ειπεν υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν εξελθων περι [την]{.greek-added} εκτην και [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο λεγει αυτοις υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον ληψεσθε[20:7]{.aside}

[ο]{.unclear}ψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι πλειονα ληψονται και ελαβον και αυτοι ανα δ[η]{.unclear}ναριον[20:10]{.aside}

λαβοντες δε εγογγυζον κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι ουτοι οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις [βαστασασιν]{.greek-omitted} [βαστ[α]{.unclear}σασι]{.greek-added} το βαρος της ημερας και τον [καυ]{.greek-supplied}σωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων εταιρε ουκ αδικω σε ουχι δηναριου [συνεφωνησας]{.greek-omitted} [συνεφωνη]{.greek-added} [σας]{.greek-added} μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω εσχατω δουναι ως και σοι[20:14]{.aside}

η ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι ποιησαι ο θελω εν τοις εμοις ει ο οφθαλμος σου πονηρος εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι και οι πρωτοι εσχατοι πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

και αναβαινων ο [ιησους]{.greek-abbr} εις ιερο[σ]{.greek-supplied}ολυμα [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} τους δωδεκα μαθητας κατ ιδιαν εν τη οδω και ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω[20:18]{.aside}

και παραδωσουσιν αυτον τοις εθνεσιν εις το εμπαιξαι και μαστιγωσαι και [σταυρωσαι]{.greek-abbr} και τη τριτη ημερα αναστησεται[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι θελεις λεγει αυτω ειπε ινα καθισωσιν ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω μελλω πινειν [η]{.greek-omitted} [και]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε το δε καθισαι εκ δεξιων μου και εξ ευωνυμων μου ουκ εστιν εμον δουναι αλλ οις ητοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη εν υμιν μεγας γενεσθαι [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[20:26]{.aside}

και ος εαν θελη εν υμιν ειναι πρωτος εστω υμων δουλος[20:27]{.aside}

ωσπερ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και εκπορευομενων αυτων απο ιεριχω ηκολουθησεν αυτω οχλος πολυς[20:29]{.aside}

και ιδου δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

ο δε οχλος επετιμησεν αυτοις ινα σιωπησωσιν οι δε μειζον εκραζον λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} εφωνησεν αυτους και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-abbr} ινα ανοιχθωσιν [ημων]{.greek-omitted} [υμων]{.greek-added} οι οφθαλμοι[20:33]{.aside}

σπλαγχνισθεις δε ο [ιησους]{.greek-abbr} ηψατο των οφθαλμων αυτων και ευθεως ανεβλεψαν αυτων οι οφθαλμοι και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε ηγγισαν εις ιεροσολυμα και ηλθον εις βηθσφαγη προς το ορος των ελαιων τοτε ο [ιησους]{.greek-abbr} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} δυο μαθητας [αυτου]{.greek-added}[21:1]{.aside}

λεγων αυτοις [πορευθητε]{.greek-omitted} [πορευσθητε]{.greek-added} εις την κωμην την απεναντι υμων και ευθεως ευρησετε ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο [κυριος]{.greek-abbr} αυτων χρειαν εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον κα[ι]{.unclear} πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες καθως προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και τον πωλον και επεθηκαν επανω αυτων [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [επεκαθισεν]{.greek-omitted} [επανω]{.greek-omitted} [αυτων]{.greek-omitted}[21:7]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πλειστος]{.greek-omitted} [οχλος]{.greek-omitted} [εστρωσαν]{.greek-omitted} [εαυτων]{.greek-omitted} τα ιματια εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και [εβασταζον]{.greek-added} [αλλοι]{.greek-added} [δε]{.greek-added} εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και [εισελθοντος]{.greek-omitted} [ελθοντος]{.greek-added} αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

και εισηλθεν [ο]{.greek-omitted} [ιησους]{.greek-abbr} εις το ιερον του [θεου]{.greek-abbr} και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} παντας τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο [οι]{.greek-added} [οικος]{.greek-omitted} [κος]{.greek-added} μου οικος προσευχης κληθησεται υμεις δε [εποιησατε]{.greek-added} αυτον [εποιησατε]{.greek-omitted} σπηλαιον ληστων[21:13]{.aside}

και προσηλθον αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων κατηρτισω αινον[21:16]{.aside}

και καταλιπων αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη εκει[21:17]{.aside}

[πρωιας]{.greek-omitted} [πρωι]{.greek-added} δε επαναγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις την πολιν [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει μη φυλλα μονον και λεγει αυτη [μη]{.greek-added} [μηκετι]{.greek-omitted} [κετι]{.greek-added} εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη παραχρημα η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν εχητε πιστιν και μη διακριθητε ου μονον το της συκης [ποιησετε]{.greek-omitted} [ποιησητε]{.greek-added} αλλα καν τω ορει τουτω ειπητε αρθητι και βληθητι εις την θαλασσαν γενησεται[21:21]{.aside}

και παντα οσα εαν αιτησητε εν τη προσευχη πιστευοντες ληψεσθε[21:22]{.aside}

και ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις σοι [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω [υμας]{.greek-omitted} [καγω]{.greek-omitted} λογον ενα [καγω]{.greek-added} [υμας]{.greek-added} ον εαν ειπητε μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [το]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο παρ εαυτοις λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει ημιν δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ως προφητην[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} ειπον ουκ οιδαμεν εφη αυτοις και αυτος ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} [τις]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} τεκνα δυο και προσελθων τω πρωτω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε μεταμεληθεις [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:29]{.aside}

και προσελθων τω δευτερω ειπεν ωσαυτως ο δε αποκριθεις ειπεν εγω [κυριε]{.greek-abbr} και ουκ [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:30]{.aside}

τις εκ των δυο [εποιησεν]{.greek-omitted} [εποι]{.greek-added} [ησε]{.greek-added} το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added}[21:31]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ προς υμας [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω οι δε τελωναι και αι πορναι επιστευσαν αυτω υμεις δε ιδοντες ου μετεμεληθητε υστερον [του]{.greek-omitted} πιστευσαι αυτω[21:32]{.aside}

αλλην παραβολην ακουσατε [ανθρωπος]{.greek-abbr} τις ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} και ωρυξεν εν αυτω [ληνον]{.greek-omitted} [λ[υ]{.unclear}νον]{.greek-added} και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε ηγγισεν ο καιρος των καρπων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν [απεκτειναν]{.greek-added} [ον]{.greek-added} [δε]{.greek-added} εδειραν ον δε [απεκτειναν]{.greek-omitted} [ον]{.greek-omitted} [δε]{.greek-omitted} ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους τον υιον αυτου λεγων εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα [εκδωσεται]{.greek-omitted} [εκδοσεται]{.greek-added} αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις καιροις αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε ανεγνωτε εν ταις γραφαις λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην [γονιας]{.greek-added} [γωνιας]{.corr} παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται εθνει ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση λικμησει αυτον[21:44]{.aside}

και ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους επειδη ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} παλιν ειπεν αυτοις εν παραβολαις λεγων[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω αυτου[22:2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα [σιτιστα]{.greek-omitted} [σιτια]{.greek-added} [μου]{.greek-added} τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και ακουσας ο [βα]{.unclear}σιλευς εκεινος ωργισθη και πεμψ[α]{.unclear}ς τα [στρατευματα]{.greek-omitted} [στρατευμα]{.greek-added} αυτου [απωλεσεν]{.greek-omitted} [απωλεσε]{.greek-added} τους φονεις εκεινους και την πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενεπρησε]{.greek-added}[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε [κεκλημενοι]{.greek-omitted} [κεκλη]{.greek-added} [μενοι]{.greek-added} ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον παντας οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου ποδας και χειρας αρατε αυτον και [εκβαλετε]{.greek-omitted} [βαλετε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι [συμ]{.greek-added} [συμβουλιον]{.greek-omitted} [βουλιον]{.greek-added} ελαβον οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι αληθης ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι [κηνσον]{.greek-omitted} [κινσον]{.greek-added} καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του [κηνσου]{.greek-omitted} [κινσου]{.greek-added} οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η [υπογραφη]{.greek-added} [επιγραφη]{.corr}[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις αποδοτε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι [οι]{.greek-omitted} λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ειπεν εαν τις αποθανη μη εχων τεκνα επιγαμβρευσει ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος [γαμησας]{.greek-omitted} [γημας]{.greek-added} [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και μη εχων σπερμα [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτοις]{.greek-omitted} [μη]{.greek-added} πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε [εκγαμιζονται]{.greek-omitted} [γαμιζονται]{.greek-added} αλλ ως αγγελοι του [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε [φ]{.greek-supplied}αρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφιμωσε]{.greek-added} τους σαδδουκαιους συνηχθησαν επι το αυτο[22:34]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} [εις]{.greek-omitted} [τις]{.greek-added} εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη [τη]{.greek-added} καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὐτῆ]{.greek-added} αγαπησεις τον πλησιον σου ως σεαυτον[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} κυριον αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} [[κυριον]{.greek-abbr}]{.greek-added} [αυτον]{.greek-added} καλει [αυτον]{.greek-omitted} [κυριον]{.greek-omitted} πως υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added}[22:45]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} [αποκριθηναι]{.greek-added} αυτω [αποκριθηναι]{.greek-omitted} λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας εκαθισαν οι γραμματεις και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added}[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και ποιειτε κατα δε τα εργα αυτων μη ποιειτε [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου ποιουσιν[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} [γαρ]{.greek-omitted} φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα [εργα]{.greek-omitted} [ερ]{.greek-added} [γα]{.greek-added} αυτων [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι [τοις]{.greek-omitted} [αυτοις]{.greek-added} [ανθρωποις]{.greek-omitted} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} δε τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} τε την πρωτοκλισιαν εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι [ραββι]{.greek-omitted}[23:7]{.aside}

υμεις δε μη κληθητε ραββι εις γαρ [εστιν]{.greek-omitted} υμων [εστι]{.greek-added} [ραββι]{.greek-added} ο καθηγητης ο [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε υμων επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr}[23:9]{.aside}

μηδε κληθητε καθηγηται εις γαρ [εστιν]{.greek-added} υμων [εστιν]{.greek-omitted} ο καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων εσται υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον [υψω]{.greek-added} [υψωθησεται]{.greek-omitted} [θησεται]{.greek-added}[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χηρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι περιαγετε την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν γενηται ποιειτε αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν ομοση εν τω ναω ουδεν εστιν ος δ αν ομοση εν τω χρυσω του ναου οφειλει[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος εαν ομοση εν τω θυσιαστηριω ουδεν εστιν ος δ αν ομοση εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι τι γαρ μειζον το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο [ομοσας]{.greek-omitted} [ομνυων]{.greek-added} εν τω ναω ομνυει εν αυτω και εν τω [κατοικησαντι]{.greek-omitted} [κατοικουντι]{.greek-added} αυτον[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το κυμινον και αφηκατε τα βαρυτερα του νομου την κρισιν και τον ελεον και την πιστιν ταυτα [δε]{.greek-added} εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα [και]{.greek-added} την [δε]{.greek-omitted} καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι καθαριζετε το εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και αδικιας[23:25]{.aside}

[φαρισαιε]{.greek-omitted} [φαρισσαιε]{.greek-added} τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι παρομοιαζετε ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

ουτως και υμεις εξωθεν μεν φαινεσθε [τοις]{.greek-omitted} [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι εστε υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι οικοδομειτε τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε [οτι]{.greek-added} ει ημεν εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν ημεν κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και [σταυρωσετε]{.greek-abbr} και εξ αυτων μαστιγωσετε εν ταις συναγωγαις υμων και διωξετε απο πολεως εις πολιν[23:34]{.aside}

οπως ελθη εφ [υμας]{.greek-omitted} [ημας]{.greek-added} παν αιμα δικαιον εκχυνομενον [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει παντα ταυτα επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεννουσα]{.greek-added} τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον τροπον επισυναγει ορνις τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν [οτι]{.greek-added} ου μη με ιδητε απ αρτι εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτου επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου βλεπετε [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added}[24:5]{.aside}

μελλησετε δε ακουειν πολεμους και ακοας πολεμων ορατε μη θροεισθε δει γαρ παντα γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εστι]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και [λοιμοι]{.greek-omitted} [λιμοι]{.greek-added} και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη [ωδινων]{.greek-omitted} [ωδιννων]{.greek-added}[24:8]{.aside}

τοτε παραδωσουσιν υμας εις θλιψιν και αποκτενουσιν υμας και εσεσθε μισουμενοι υπο παντων των εθνων δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} και μισησουσιν αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται [τουτο]{.greek-omitted} το ευαγγελιον [τουτο]{.greek-added} της βασιλειας εν ολη τη οικουμενη εις μαρτυριον [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν ιδητε το [βδελυγμα]{.greek-omitted} [βδελλυγμα]{.greek-added} της ερημωσεως το ρηθεν δια δανιηλ του προφητου εστως εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν επι τα ορη[24:16]{.aside}

ο επι του δωματος μη [καταβαινετω]{.greek-omitted} [καταβατω]{.greek-added} αραι τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

προσευχεσθε [δε]{.greek-omitted} ινα μη γενηται η φυγη υμων χειμωνος μηδε [εν]{.greek-added} σαββατω[24:20]{.aside}

εσται γαρ τοτε θλιψις μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν ουδ ου μη γενηται[24:21]{.aside}

και ει μη εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι [ημεραι]{.greek-omitted} [ημε]{.greek-added} [ραι]{.greek-added} εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια μεγαλα και τερατα [εν]{.greek-added} [τω]{.greek-added} [λαω]{.greek-added} ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω εστιν μη εξελθητε ιδου εν τοις ταμειοις μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται [και]{.greek-omitted} η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ εαν η [το]{.greek-omitted} πτωμα εκει συναχθησονται οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν [εκεινων]{.greek-added} των ημερων [εκεινων]{.greek-omitted} ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε κοψονται πασαι αι φυλαι της γης και οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και αποστελει τους αγγελους αυτου μετα σαλπιγγος [και]{.greek-added} φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξουσι]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-abbr} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος αυτης γενηται απαλος και τα φυλλα εκφυη γινωσκετε οτι εγγυς [το]{.corr} [θερος]{.corr}[24:32]{.aside}

[ουτως]{.corr} [και]{.corr} [υμεις]{.corr} [οταν]{.greek-omitted} [[εαν]{.corr}]{.greek-added} [ιδητε]{.corr} [ταυτα]{.corr} [παντα]{.corr} [γινωσκετε]{.corr} [οτι]{.corr} [εγγυς]{.corr} εστιν επι θυραις[24:33]{.aside}

αμην λεγω υμιν ου μη παρελθη η γενεα αυτη εως αν παντα ταυτα γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσονται]{.greek-omitted} [παρελευσεται]{.greek-added} οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[24:35]{.aside}

περι δε της ημερας εκεινης και ωρας [ου]{.greek-added} [ουδεις]{.greek-omitted} [δεις]{.greek-added} οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} [ουδε]{.greek-added} [ο]{.greek-added} [υιος]{.greek-added} ει μη ο [πατηρ]{.greek-abbr} [μου]{.greek-omitted} μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του [υιου]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις προ του κατακλυσμου τρωγοντες και πινοντες γαμουντες και εκγαμιζοντες αχρι ης ημερας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο αληθουσαι εν τω μυλωνι μια παραλαμβανεται και μια αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει ηδει ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται [ε]{.greek-added} [εγρηγορησεν]{.greek-omitted} [γρηγορησεν]{.greek-added} αν και ουκ αν [ειασεν]{.greek-omitted} [ειασε]{.greek-added} διορυγηναι την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} [ερχεται]{.greek-omitted} [ερχετε]{.greek-added}[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της θεραπειας αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [εσθιειν]{.greek-omitted} [εσθιη]{.greek-added} δε και [πινειν]{.greek-omitted} [πινη]{.greek-added} μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και [αι]{.greek-omitted} πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε ημιν εκ του ελαιου υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε ουκ αρκεση ημιν και υμιν πορευεσθε δε μαλλον προς τους πωλουντας και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν εν η ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και [εποιησεν]{.greek-omitted} [εκερδησεν]{.greek-added} αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο [εκερδησεν]{.greek-omitted} [εκερδησε]{.greek-added} και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και [απεκρυψεν]{.greek-omitted} [απεκρυψε]{.greek-added} το αργυριον του [κυριου]{.greek-omitted} [κυ]{.greek-added} αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και συναιρει μετ αυτων [λογον]{.greek-omitted} [λεγων]{.greek-added}[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε [μοι]{.greek-added} ταλαντα [μοι]{.greek-omitted} παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα [επ]{.greek-omitted} [εν]{.greek-added} αυτοις[25:20]{.aside}

εφη [δε]{.greek-omitted} αυτω ο κυριος αυτου [ευ]{.greek-omitted} [δουλε]{.greek-omitted} [αγαθε]{.greek-omitted} [και]{.greek-omitted} [πιστε]{.greek-omitted} επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του κυριου σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον [σου]{.corr} εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε ηδεις οτι θεριζω οπου ουκ εσπειρα και [συναγω]{.greek-omitted} [συναγων]{.greek-added} οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου [ο]{.greek-added} [εχων]{.greek-added} [ωτα]{.greek-added} [ακουειν]{.greek-added} [ακουετω]{.greek-added}[25:29]{.aside}

και τον αχρειον δουλον εκβαλετε εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε καθισει επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με ξενος ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και επεσκεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε [α]{.greek-supplied}ποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και συνηγαγομεν η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των [αδελφων]{.greek-added} [μου]{.greek-added} [των]{.greek-added} ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} [παντας]{.greek-omitted} τους λογους τουτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το [σταυρωθηναι]{.greek-abbr}[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω κρατησωσιν και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα [βαρυτιμου]{.greek-omitted} [πολυτιμου]{.greek-added} και κατεχεεν επι [την]{.greek-omitted} [της]{.greek-added} [κεφαλην]{.greek-omitted} [κεφαλης]{.greek-added} αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι [τοις]{.greek-added} πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους παρεχετε τη γυναικι εργον γαρ καλον ειργασατο [εις]{.greek-omitted} [εμε]{.greek-omitted} [εν]{.greek-added} [εμοι]{.greek-added}[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} τους πτωχους [γαρ]{.greek-added} [παντοτε]{.greek-added} εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το ενταφιασαι με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε μοι δουναι [καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που θελεις ετοιμασομεν σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε [εις]{.corr} [την]{.corr} [πολιν]{.corr} προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα[26:20]{.aside}

και εσθιοντων αυτων ειπεν [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου [την]{.greek-added} [χειρα]{.greek-added} εν τω τρυβλιω [την]{.greek-omitted} [χειρα]{.greek-omitted} ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ [εγενηθη]{.greek-added} [εγεννηθη]{.corr} ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μητι εγω ειμι ραββι λεγει αυτω συ ειπας[26:25]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} [τον]{.greek-omitted} αρτον και ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του [γεννηματος]{.greek-omitted} [γενηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν αυτο πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις σκανδαλισθησεσθε [εν]{.greek-omitted} [εμοι]{.greek-omitted} εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον ποιμενα και διασκορπισθησεται τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω δε ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις [χω]{.greek-added} [χωριον]{.greek-omitted} [ριον]{.greek-added} λεγομενον [γεθσημανη]{.greek-omitted} [γεθσιμανη]{.greek-added} και λεγει τοις μαθηταις καθισατε αυτου εως ου απελθων προσευξωμαι εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν [και]{.greek-added} [εγενετο]{.greek-added} [ο]{.greek-added} [ιδρως]{.greek-added} [αυτου]{.greek-added} [ωσει]{.greek-added} [θρομμοι]{.greek-added} [αιματος]{.greek-added}[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν [γρηγορησαι]{.greek-omitted} [αγρυπνη]{.greek-added} [σαι]{.greek-added} μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται τουτο το ποτηριον παρελθειν απ εμου εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων ευρισκει αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} ειπεν χαιρε ραββι και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-omitted} εταιρε εφ ω παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} εκτεινας την χειρα [απεσπασεν]{.greek-omitted} [απεσπασε]{.greek-added} την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον σου την μαχαιραν εις τον τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν μαχαιρα αποθανουνται[26:52]{.aside}

η [ου]{.greek-added} δοκεις οτι ου δυναμαι αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη [ουν]{.greek-added} τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ [εκρατησατε]{.greek-omitted} [εκρατησετε]{.greek-added} με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται [αυτου]{.greek-added} παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος ηκολουθει [αυτω]{.greek-omitted} απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και το συνεδριον ολον εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως θανατωσωσιν αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-omitted} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και [ερχομενον]{.greek-omitted} [ερχο]{.greek-added} [μενον]{.greek-added} επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματια αυτου λεγων οτι [εβλασφημησεν]{.greek-omitted} [εβλασφημησε]{.greek-added} τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον [αυτω]{.greek-added} ενοχος θανατου [εστιν]{.greek-omitted} [εστι]{.greek-added}[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και εκολαφισαν αυτον οι δε ερραπισαν[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος [εξω]{.greek-omitted} εκαθητο εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν αυτων παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει αυτοις εκει και ουτος ην μετα [ιησου]{.greek-abbr} του [ναζωραιου]{.greek-omitted} [ναζιραιου]{.greek-added}[26:71]{.aside}

και παλιν ηρνησατο μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα [δε]{.greek-added} μικρον δε προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος [του]{.greek-omitted} [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν αυτον ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε ιδων ιουδας ο παραδιδους αυτον οτι κατεκριθη μεταμεληθεις απεστρεψεν τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε ειπον τι προς ημας συ οψει[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον κορβαναν επει τιμη αιματος [εστιν]{.greek-omitted} [εστι]{.greek-added}[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα [συνεταξεν]{.greek-omitted} [συνετα]{.greek-added} [ξεν]{.greek-added} μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και των πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} [τον]{.corr} λεγομενον [χριστον]{.greek-abbr} λεγουσιν αυτω παντες [σταυρωθητω]{.greek-abbr}[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες [σταυρωθητω]{.greek-abbr}[27:23]{.aside}

ιδων δε [ο]{.greek-omitted} πιλατος οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φραγελλωσας παρεδωκεν ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και γονυπετησαντες εμπροσθεν αυτου ενεπαιζον αυτω λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν [αυτω]{.greek-omitted} [αυ]{.greek-added} [τω]{.greek-added} εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα ο εστιν [λεγομενος]{.greek-omitted} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} πιειν[27:34]{.aside}

[σταυρωσαντες]{.greek-abbr} δε αυτον διεμερισαντο τα ιματια αυτου [βαλλοντες]{.greek-omitted} [βαλοντες]{.greek-added} κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-omitted} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουνται]{.greek-abbr} συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο [καταλυων]{.greek-omitted} [κατα]{.greek-added} [λυων]{.greek-added} τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} καταβηθι απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως δε και οι αρχιερεις εμπαιζοντες μετα των γραμματεων και πρεσβυτερων και [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} και πιστευσομεν επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω [νυν]{.greek-omitted} αυτον [ει]{.greek-omitted} [οτι]{.greek-added} θελει αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι [συσταυρωθεντες]{.greek-abbr} αυτω ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[27:45]{.aside}

περι δε την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι λιμα σαβαχθανι τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελιπες[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες ελεγον οτι ηλιαν φωνει ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας σωσων αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη εσεισθη και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια [ανεωχθησαν]{.greek-omitted} [ανεωχθη]{.greek-added} και πολλα σωματα των κεκοιμημενων αγιων ηγερθη[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου [τη]{.greek-added} [τηρουντες]{.greek-omitted} [ρουντες]{.greek-added} τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} [ην]{.greek-added} [[υιος]{.greek-abbr}]{.corr} [ην]{.greek-omitted} ουτος[27:54]{.aside}

ησαν δε εκει γυναικες πολλαι απο μακροθεν θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος [ο]{.greek-added} απο αριμαθαιας τουνομα ιωσηφ ος και αυτος [εμαθητευσεν]{.greek-omitted} [εμαθητευσε]{.greek-added} τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα [του]{.greek-omitted} [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ ενετυλιξεν αυτο [εν]{.greek-added} σινδονι καθαρα[27:59]{.aside}

και εθηκεν αυτο εν τω καινω αυτου μνημειω ο ελατομησεν εν τη πετρα και προσκυλισας [λι]{.greek-added} [λιθον]{.greek-omitted} [θον]{.greek-added} μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη μαρια καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς [π]{.greek-supplied}ιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν [οτι]{.greek-omitted} [οοτι]{.greek-added} [εκεινος]{.greek-omitted} ο πλανος [εκεινος]{.greek-added} ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου νυκτος κλεψωσιν αυτον και ειπωσιν τω λαω ηγερθη απο των νεκρων και εσται η εσχατη πλανη χειρων της πρωτης[27:64]{.aside}

εφη [δε]{.greek-omitted} αυτοις ο πιλατος εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε δε σαββατων τη επιφωσκουση εις μιαν σαββατων [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος [μεγας]{.greek-added} εγενετο [μεγας]{.greek-omitted} αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} προσελθων [απεκυλισεν]{.greek-omitted} [απεκυλισε]{.greek-added} τον λιθον απο της θυρας και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταις γυναιξιν μη φοβεισθε υμεις οιδα γαρ [οτι]{.greek-omitted} [ιησουν]{.greek-abbr} τον [εσταυρωμενον]{.greek-abbr} ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως ειπεν δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ πορευθεισαι ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

[ως]{.greek-omitted} [δε]{.greek-omitted} [επορευοντο]{.greek-omitted} [απαγγειλαι]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} απηντησεν αυταις λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

λεγοντες ειπατε οτι οι μαθηται αυτου νυκτος ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις πεισομεν αυτον και υμας αμεριμνους ποιησομεν[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και διεφημισθη ο λογος ουτος παρα ιουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

