---
title: "Collation of Byz^RP^ vs 31006 (1006)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1006 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31006).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1006                                   	| λογος                              	|
| 1006 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1006 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1006               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1006                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1006 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1006                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου [τω]{.greek-omitted} [τωι]{.greek-added} [δουλω]{.greek-omitted} [δουλωι]{.greek-added} αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα ειδεν[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν [τη]{.greek-omitted} [τηι]{.greek-added} [ασια]{.greek-omitted} [ασιαι]{.greek-added} χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος των νεκρων και ο αρχων των βασιλεων της γης [τω]{.greek-omitted} [τωι]{.greek-added} αγαπωντι ημας και λουσαντι ημας απο των αμαρτιων ημων εν [τω]{.greek-omitted} [τωι]{.greek-added} αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου [αυτω]{.greek-omitted} [αυτωι]{.greek-added} η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι α[μην]{.unclear}[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και κοινωνος εν [τη]{.greek-omitted} [τηι]{.greek-added} θλιψει και βασιλεια και [υπομονη]{.greek-omitted} [υπομονηι]{.greek-added} εν [χριστω]{.greek-omitted} [[χωι]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr} εγενομην εν [τηι]{.greek-added} [νησωι]{.greek-added} τη [νησω]{.greek-omitted} [τη]{.greek-omitted} [καλουμενη]{.greek-omitted} [καλουμενηι]{.greek-added} [πατμω]{.greek-omitted} [πατμωι]{.greek-added} δια τον λογον του [θεου]{.greek-abbr} και [δια]{.greek-omitted} την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [τωι]{.greek-added} [πνευματι]{.greek-abbr} εν [τη]{.greek-omitted} [τηι]{.greek-added} [κυριακη]{.greek-omitted} [κυριακηι]{.greek-added} ημερα και ηκουσα φωνην οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις σμυρναν και εις περγαμον και εις [θυατειρα]{.greek-omitted} [θυατειραν]{.greek-added} και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

και εκει επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των επτα λυχνιων ομοιον [υιω]{.greek-omitted} [υιωι]{.greek-added} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις [μαστοις]{.greek-omitted} [μαζοις]{.greek-added} ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκολιβανωι]{.greek-added} ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν [τη]{.greek-omitted} [τηι]{.greek-added} [δεξια]{.greek-omitted} [δεξιαι]{.greek-added} αυτου χειρι αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν [τη]{.greek-omitted} [τηι]{.greek-added} δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον [επεσα]{.greek-omitted} [επεσον]{.greek-added} προς τους ποδας αυτου [ως]{.greek-omitted} νεκρος και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας [κλεις]{.greek-omitted} [κλειδας]{.greek-added} του θανατου και του αδου[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων [εισιν]{.greek-omitted} [εισι]{.greek-added} και αι λυχνιαι αι επτα επτα εκκλησιαι [εισιν]{.greek-omitted} [εισι]{.greek-added}[1:20]{.aside}

### Chapter 2

[τω]{.greek-omitted} [τωι]{.greek-added} αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν [τη]{.greek-omitted} [τηι]{.greek-added} [δεξια]{.greek-omitted} [δεξιαι]{.greek-added} αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις και εβαστασας δια το ονομα μου και ουκ [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

αλλα εχω κατα σου οτι την αγαπην σου την πρωτην [αφηκας]{.greek-omitted} [αφηκες]{.greek-added}[2:4]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις [τω]{.greek-omitted} [τωι]{.greek-added} νικωντι δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν [τω]{.greek-omitted} [τωι]{.greek-added} παραδεισω του [θεου]{.greek-abbr} μου[2:7]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος [ος]{.greek-omitted} εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν εκ των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βαλεῖν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν [ημερων]{.greek-omitted} [ημερας]{.greek-added} δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη [αδικηθη]{.greek-omitted} [αδικηθηι]{.greek-added} εκ του θανατου του δευτερου[2:11]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} της εν [περγαμω]{.greek-omitted} [περγαμωι]{.greek-added} εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις [εν]{.greek-omitted} [αι]{.greek-added} [αις]{.corr} [αντιπας]{.greek-omitted} [ἀντεῖπας]{.greek-added} ο μαρτυς μου ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην [του]{.greek-added} βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} και φαγειν [ειδωλωθυτα]{.greek-added} [ειδωλοθυτα]{.corr} και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν [τη]{.greek-omitted} [τηι]{.greek-added} [ρομφαια]{.greek-omitted} [ρομφαιαι]{.greek-added} του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις [τω]{.greek-omitted} [τωι]{.greek-added} νικωντι δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} του μαννα του κεκρυμμενου και δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} αγγελω της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκολιβανωι]{.greek-added}[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου οτι [αφεις]{.greek-omitted} [αφιης]{.greek-added} την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα [αυτη]{.greek-omitted} [αυτηι]{.greek-added} χρονον ινα [μετανοηση]{.greek-omitted} [μετανοησηι]{.greek-added} και ου θελει μετανοησαι εκ της [πορ]{.greek-added} [πορνειας]{.greek-omitted} [νειας]{.greek-added} αυτης[2:21]{.aside}

ιδου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν [θανατω]{.greek-omitted} [θανατωι]{.greek-added} και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο [ερευνων]{.greek-omitted} [εραυνων]{.greek-added} [καρδιας]{.greek-added} [και]{.greek-added} νεφρους [και]{.greek-omitted} [καρδιας]{.greek-omitted} και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [ανοιξω]{.greek-added} [αν]{.greek-omitted} [ηξω]{.greek-omitted}[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν [ραβδω]{.greek-omitted} [ραβδωι]{.greek-added} [σιδηρα]{.greek-omitted} [σιδηραι]{.greek-added} ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και [τω]{.greek-omitted} [τωι]{.greek-added} [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [και]{.greek-added} ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και στηρισον τα λοιπα α [εμελλες]{.greek-omitted} [ημελλες]{.greek-added} αποβαλλειν ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας [και]{.greek-omitted} [ηκουσας]{.greek-omitted} [και]{.greek-omitted} [τηρει]{.greek-omitted} και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωσηι]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων [ουτος]{.greek-omitted} [ουτως]{.greek-added} περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ [της]{.greek-omitted} βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} αγγελω της εν φιλαδελφεια εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει αυτην ει μη ο ανοιγων και ουδεις [ανοιξει]{.greek-omitted} [ανοιγει]{.greek-added}[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξουσι]{.greek-added} και [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσιν]{.greek-added} ενωπιον των ποδων σου και [γνωσιν]{.greek-omitted} [γνωσωσιν]{.greek-added} οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις [λαβη]{.greek-omitted} [λαβηι]{.greek-added} τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [οικω]{.greek-added} του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα [μου]{.greek-omitted} το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και [τω]{.greek-omitted} [τωι]{.greek-added} αγγελω της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος [οφελον]{.greek-omitted} [ψυχρος]{.greek-omitted} [ης]{.greek-omitted} [η]{.greek-omitted} [ζεστος]{.greek-omitted}[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος μελλω σε εμεσαι [εκ]{.greek-omitted} [απο]{.greek-added} του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και [πεπλουτικα]{.greek-added} [πεπλουτηκα]{.corr} και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και ο ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι χρυσιον [παρ]{.greek-omitted} [απ]{.greek-added} εμου πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα [περιβαλη]{.greek-omitted} [περιβαληι]{.greek-added} και μη φανερωθη η αισχυνη της γυμνοτητος σου και κολλυριον ινα [εγχριση]{.greek-omitted} [εγχρισηι]{.greek-added} τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλευε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις [ακουση]{.greek-omitted} [ακουσηι]{.greek-added} της φωνης μου και ανοιξη την θυραν και εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω [αυτω]{.greek-omitted} [αυτωι]{.greek-added} καθισαι μετ εμου εν [τω]{.greek-omitted} [τωι]{.greek-added} θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν [τω]{.greek-omitted} [τωι]{.greek-added} θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

[και]{.greek-omitted} ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και επι τον θρονον καθημενος[4:2]{.aside}

ομοιος ορασει λιθω ιασπιδι και [σαρδιω]{.greek-omitted} [σαρδιωι]{.greek-added} και [ιρις]{.greek-omitted} [ἶρις]{.greek-added} [κυκλωθεν]{.greek-added} [κυκλοθεν]{.corr} του θρονου ομοιως ορασις σμαραγδινων[4:3]{.aside}

[και]{.greek-omitted} κυκλοθεν του θρονου θρονοι εικοσι τεσσαρες και επι τους θρονους τους εικοσι τεσσαρας πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα [υαλινη]{.greek-omitted} [υελινη]{.greek-added} ομοια [κρυσταλλω]{.greek-omitted} [κρυσταλλωι]{.greek-added} και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον [ζωον]{.greek-omitted} [ζωιον]{.greek-added} ομοιον [μοσχω]{.greek-omitted} [μοσχωι]{.greek-added} και το τριτον [ζωον]{.greek-omitted} [ζωιον]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} προσωπον [ανθρωπου]{.greek-abbr} και το τεταρτον [ζωον]{.greek-omitted} ομοιον αετω [πετομενω]{.greek-omitted} [πετομενωι]{.greek-added}[4:7]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα εν καθ εν [εχον]{.greek-omitted} [εχων]{.greek-added} ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν δωσιν τα ζωα δοξαν και τιμην και ευχαριστιαν [τω]{.greek-omitted} [τωι]{.greek-added} [καθημενω]{.greek-omitted} [καθημενωι]{.greek-added} επι του θρονου [[και]{.corr}]{.greek-added} [[προσκυνουσι]{.corr}]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

[πεσουνται]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} και [προσκυνησουσιν]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [και]{.greek-omitted} [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων [[αυτωι]{.corr}]{.greek-added} ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και [ο]{.greek-omitted} [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας παντα και δια το θελημα σου ησαν και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα εν φωνη [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-abbr} ανω [ουτε]{.greek-omitted} [ουδε]{.greek-added} επι της γης [ουτε]{.greek-omitted} [ουδε]{.greek-added} υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων [ο]{.greek-omitted} εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον [και]{.greek-added} [ιδου]{.greek-added} εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον [εστηκος]{.greek-omitted} [εστικος]{.greek-added} ως εσφαγμενον [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα επτα [οι]{.greek-added} [και]{.greek-omitted} [οφθαλμους]{.greek-omitted} [επτα]{.greek-omitted} [α]{.greek-omitted} [εισιν]{.greek-omitted} [εισι]{.greek-added} τα [επτα]{.greek-omitted} [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} [τα]{.greek-added} [αποστελλομενα]{.greek-omitted} [απεσταλμενα]{.greek-added} εις πασαν την γην[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και [ειληφεν]{.greek-omitted} [ειληφε]{.greek-added} [το]{.greek-added} [βιβλιον]{.greek-added} εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι επεσον ενωπιον του αρνιου εχοντες εκαστος κιθαραν και φιαλας χρυσας [γεμουσας]{.greek-omitted} [γεμου]{.greek-added} [σας]{.greek-added} θυμιαματων [α]{.greek-added} [εισιν]{.greek-added} αι [εισιν]{.greek-omitted} προσευχαι των αγιων[5:8]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} [καινην]{.greek-added} ωδην [καινην]{.greek-omitted} λεγοντες [αξιος]{.greek-omitted} [αξιως]{.greek-added} ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} ημας εν [τω]{.greek-omitted} [τωι]{.greek-added} αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και [βασιλευσουσιν]{.greek-omitted} [βασιλευουσιν]{.greek-added} επι της γης[5:10]{.aside}

και ειδον και ηκουσα ως φωνην αγγελων πολλων κυκλω του θρονου και των [ζωων]{.greek-omitted} [ζωιων]{.greek-added} και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων [και]{.greek-omitted} [χιλιαδες]{.greek-omitted} [χιλιαδων]{.greek-omitted}[5:11]{.aside}

λεγοντες [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και τον πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο εν [τω]{.greek-omitted} [ουρανω]{.greek-abbr} και επι της γης και υποκατω της γης και επι της θαλασσης [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις παντας ηκουσα λεγοντας [τω]{.greek-omitted} [τωι]{.greek-added} καθημενω επι του θρονου και [τω]{.greek-omitted} [τωι]{.greek-added} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added} η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων [αμην]{.greek-omitted}[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} [το]{.greek-omitted} αμην και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον [οτι]{.greek-omitted} [οτε]{.greek-added} ηνοιξεν το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων [ζωων]{.greek-omitted} [ζωιων]{.greek-added} λεγοντος ως [φωνη]{.greek-omitted} [φωνὴ]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων [και]{.greek-omitted} ινα νικηση[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την [δευτεραν]{.greek-omitted} σφραγιδα [την]{.greek-added} [ετεραν]{.greek-added} ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος [πυρος]{.greek-omitted} [πυρρος]{.greek-added} και [τω]{.greek-omitted} [τωι]{.greek-added} καθημενω επ αυτον εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} λαβειν την ειρηνην εκ της γης [και]{.greek-added} ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου [ζωου]{.greek-omitted} [ζωιου]{.greek-added} λεγοντος ερχου και [ιδε]{.greek-omitted} [ειδον]{.greek-added} και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων [ζωων]{.greek-omitted} [ζωιων]{.greek-added} λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες [κριθης]{.greek-omitted} [κριθων]{.greek-added} δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα [φωνην]{.greek-added} του τεταρτου [ζωου]{.greek-omitted} [ζωιου]{.greek-added} λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ο]{.greek-omitted} θανατος και ο [αδης]{.greek-omitted} [αιδης]{.greek-added} ηκολουθει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και εδοθη [αυτω]{.greek-omitted} [αυτοις]{.greek-added} εξουσια [αχρι]{.greek-added} επι το τεταρτον της γης αποκτειναι εν [ρομφαια]{.greek-omitted} [ρομφαιαι]{.greek-added} και εν λιμω και εν [θανατω]{.greek-omitted} [θανατωι]{.greek-added} και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} ην ειχον[6:9]{.aside}

και [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα αναπαυσωνται [χρονον]{.greek-added} ετι [χρονον]{.greek-omitted} [μικρον]{.greek-added} εως [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων [και]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} οι μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκτε]{.greek-added} [νεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος [εγενετο]{.greek-added} μελας [εγενετο]{.greek-omitted} ως σακκος τριχινος και η σεληνη [εγενετο]{.greek-added} ολη [εγενετο]{.greek-omitted} ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλει]{.greek-added} τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον ελισσομενον και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

[και]{.greek-omitted} μετα τουτο ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας [γωνιας]{.greek-omitted} [γονιας]{.greek-added} της γης κρατουντας [τους]{.greek-omitted} [τας]{.greek-added} τεσσαρας ανεμους της γης ινα μη [πνεη]{.greek-omitted} [πνεηι]{.greek-added} ανεμος επι της γης μητε επι [της]{.greek-omitted} θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη [αδικησητε]{.greek-omitted} [αδικησετε]{.greek-added} την γην μητε την [θα]{.greek-added} [θαλασσαν]{.greek-omitted} [λασσαν]{.greek-added} μητε τα δενδρα αχρι [ου]{.greek-omitted} [σφραγισωμεν]{.greek-omitted} [σφραγισομε]{.greek-added} τους δουλους του [θεου]{.greek-abbr} ημων επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον και [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} τεσσαρες χιλιαδες [εσφραγισμενων]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ πασης φυλης [υιων]{.greek-omitted} [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης [ρουβιμ]{.greek-omitted} [ρουβιν]{.greek-added} δωδεκα χιλιαδες εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ δωδεκα χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι δωδεκα χιλιαδες εκ φυλης [ισαχαρ]{.greek-omitted} [ισσαχαρ]{.greek-added} δωδεκα χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων δωδεκα χιλιαδες εκ φυλης ιωσηφ δωδεκα χιλιαδες εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμην]{.greek-added} δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι [αυτον]{.greek-added} [ουδεις]{.greek-omitted} [ουδε]{.greek-added} [εις]{.greek-added} εδυνατο εκ παντος εθνους και φυλων και λαων και γλωσσων εστωτας ενωπιον του θρονου [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} περιβεβλημενους στολας λευκας και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} λεγοντες η [σωτηρια]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} ημων [τω]{.greek-omitted} [τωι]{.greek-added} καθημενω επι [τω]{.greek-omitted} [τωι]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} και [τω]{.greek-omitted} [τωι]{.greek-added} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added}[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου επι τα προσωπα αυτων και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και [ειπον]{.greek-omitted} [ειρηκα]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} κυριε μου συ οιδας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι εισιν οι ερχομενοι [απο]{.greek-added} [εκ]{.greek-omitted} [της]{.greek-omitted} θλιψεως της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν [αυτας]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ημερας και νυκτος εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν [ετι]{.greek-omitted} [ουδ]{.greek-omitted} [ουδε]{.greek-added} [ου]{.greek-omitted} μη πεση επ αυτους ο ηλιος [ετι]{.greek-added} ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγησει]{.greek-added} αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και [οτε]{.greek-omitted} [οταν]{.greek-added} [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην εγενετο σιγη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι [του]{.greek-omitted} [το]{.greek-added} [θυσιαστηριου]{.greek-omitted} [θυσιαστηριον]{.greek-added} εχων λιβανωτον χρυσουν και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δω]{.greek-added} ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο βρονται και [φωναι]{.greek-omitted} [και]{.greek-omitted} αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα [πυρι]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον των κτισματων [των]{.greek-added} εν [τη]{.greek-omitted} [τηι]{.greek-added} θαλασση τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9]{.aside}

και ο τριτος [αγγελος]{.greek-omitted} [αγγελοι]{.greek-added} [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα [σκοτισθη]{.greek-omitted} [σκοτισθηι]{.greek-added} το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [μη]{.greek-added} [φανη]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος αετου πετομενου εν μεσουρανηματι [λε]{.greek-added} [λεγοντος]{.greek-omitted} [γοντος]{.greek-added} [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} ουαι ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος ως καπνος καμινου [καιομενης]{.greek-omitted} [μεγαλης]{.greek-added} και [εσκοτισθη]{.greek-omitted} [εσκοτωθη]{.greek-added} ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[9:4]{.aside}

και εδοθη αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν παιση [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [εὕρωσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευγει]{.greek-added} [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια [ιποις]{.greek-added} [ιπποις]{.corr} ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι [χρυσοι]{.greek-omitted} [ομοιοι]{.greek-added} [χρυσω]{.greek-added} και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον [θο]{.greek-added} [θωρακας]{.greek-omitted} [ρακας]{.greek-added} [ως]{.greek-omitted} [θωρακας]{.greek-omitted} σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας [[ομοιοις]{.corr}]{.greek-added} σκορπιοις και κεντρα και εν ταις ουραις αυτων [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[εχουσαι]{.greek-omitted} [εχουσιν]{.greek-added} [βασιλεα]{.greek-omitted} επ αυτων [βασιλεα]{.greek-added} [τον]{.greek-added} αγγελον της αβυσσου ονομα [αυτω]{.greek-omitted} [αυτωι]{.greek-added} εβραιστι [αββαδων]{.greek-omitted} [αβαδδων]{.greek-added} [και]{.greek-added} εν [δε]{.greek-omitted} [τη]{.greek-omitted} [τηι]{.greek-added} [εληνικη]{.greek-added} [ελληνικη]{.corr} ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου ερχεται ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγοντος]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι [τω]{.greek-omitted} [τωι]{.greek-added} [ποταμω]{.greek-omitted} [ποταμωι]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} μεγαλω [ευφρατη]{.greek-omitted} [εφρατηι]{.greek-added}[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και [εις]{.greek-omitted} [την]{.greek-omitted} ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [ιππου]{.greek-omitted} [ιππικου]{.greek-added} μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν [τη]{.greek-omitted} [τηι]{.greek-added} ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους [και]{.greek-omitted} υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του πυρος και [εκ]{.greek-added} του καπνου και [εκ]{.greek-added} του θειου του [εκπορευομενου]{.greek-omitted} [εκπορευο]{.greek-added} [μενου]{.greek-added} εκ [των]{.greek-omitted} [του]{.greek-added} [στοματων]{.greek-omitted} [στοματος]{.greek-added} αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι αυτων εστιν και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} εχουσαι κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} [περιβεβλημενον]{.greek-omitted} [περιβεβλημμενον]{.greek-added} νεφελην και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και εχων εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλιδαριον]{.greek-added} ανεωγμενον και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται [εμελλον]{.greek-omitted} [ημελλον]{.greek-added} γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την [δεξιαν]{.greek-omitted} [δεξι]{.greek-added} [αν]{.greek-added} εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και ωμοσεν [εν]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και την γην και τα εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} και την θαλασσαν και τα εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν [μελλει]{.greek-added} [μελλη]{.greek-omitted} [[μελληι]{.corr}]{.greek-added} σαλπιζειν και ετελεσθη το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και [η]{.greek-omitted} [φωνη]{.greek-omitted} [φωνην]{.greek-added} [ην]{.greek-omitted} ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν [λαλουντος]{.greek-added} [λαλουσα]{.greek-omitted} [[λαλουσαν]{.corr}]{.greek-added} μετ εμου και [λεγουσα]{.greek-omitted} [λεγουσαν]{.greek-added} υπαγε λαβε το [βιβλιδαριον]{.greek-omitted} [βιβλιον]{.greek-added} το ανεωγμενον εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δουναι μοι το [βιβλιδαριον]{.greek-omitted} [βιβλιον]{.greek-added} και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βιβλιδαριον]{.greek-added} εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτό]{.greek-added} και ην εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και [επι]{.greek-omitted} [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω λεγων εγειραι και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας [τεσσαρακοντα]{.greek-omitted} [τεσσαρακονταδυο]{.greek-added} [και]{.greek-omitted} [δυο]{.greek-omitted}[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου [λογον]{.greek-added} και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον [του]{.greek-omitted} [κυριου]{.greek-abbr} της γης εστωσαι[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις [θελει]{.greek-omitted} [θελησει]{.greek-added} αυτους αδικησαι ουτως δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι εχουσιν [εξουσιαν]{.greek-added} [κλεισαι]{.greek-added} τον [ουρανον]{.greek-abbr} [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα [εις]{.unclear} αιμα και παταξαι την γην [εν]{.greek-added} [πασηι]{.greek-added} [πληγηι]{.greek-added} οσακις εαν [θελησωσιν]{.greek-omitted} [θελησωσι]{.greek-added} [εν]{.greek-omitted} [παση]{.greek-omitted} [πληγη]{.greek-omitted}[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το αναβαινον εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και το πτωμα αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις [και]{.greek-added} ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφιασι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και [ευφρανθησονται]{.greek-omitted} [ευφραινονται]{.greek-added} και δωρα [δωσουσιν]{.greek-omitted} [πεμψουσιν]{.greek-added} αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης [εισηλθεν]{.greek-added} [εν]{.greek-added} [αυτοις]{.greek-added} εκ του [θεου]{.greek-abbr} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [αυτους]{.greek-omitted} και εστησαν επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} [επεπεσεν]{.greek-added} επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσαν]{.greek-omitted} [λεγουσης]{.greek-added} αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν [τη]{.greek-omitted} [τηι]{.greek-added} νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη [τη]{.greek-omitted} [τηι]{.greek-added} [ημερα]{.greek-omitted} [ωρα]{.greek-added} εγενετο σεισμος μεγας και το δεκατον της πολεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και απεκτανθησαν εν [τω]{.greek-omitted} [τωι]{.greek-added} [σεισμω]{.greek-omitted} [σεισμωι]{.greek-added} ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν [ιδου]{.greek-added} η ουαι η τριτη [ιδου]{.greek-omitted} ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [ουρανωι]{.greek-added} λεγουσαι εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι [οι]{.greek-omitted} ενωπιον του [θρονου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr} [καθημενοι]{.greek-omitted} [καθηνται]{.greek-added} επι τους θρονους αυτων [και]{.greek-added} επεσον επι τα προσωπα αυτων και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην [και]{.greek-added} [ο]{.greek-added} [ερχομενος]{.greek-added} οτι ειληφας την δυναμιν σου την [μεγαλην]{.greek-omitted} [μεγαλιν]{.greek-added} και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις [φο]{.greek-added} [φοβουμενοις]{.greek-omitted} [βουμενοις]{.greek-added} το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους διαφθειροντας την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} [ο]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης [του]{.greek-omitted} [αυτου]{.greek-added} [κυριου]{.greek-omitted} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ναω]{.greek-omitted} [ναωι]{.greek-added} αυτου και εγενοντο αστραπαι και φωναι και βρονται και [σεισμος]{.greek-added} [και]{.greek-added} χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα [και]{.greek-added} [εκραζεν]{.greek-omitted} [κραζει]{.greek-added} ωδινουσα και βασανιζομενη [του]{.greek-added} τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και ιδου δρακων [μεγας]{.greek-added} πυρος [μεγας]{.greek-omitted} εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και [εβαλεν]{.greek-omitted} [εβαλλεν]{.greek-added} αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἔστηκεν]{.greek-added} ενωπιον της γυναικος της [μελλουσης]{.greek-omitted} [μελουσης]{.greek-added} τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν υιον [αρρενα]{.greek-omitted} [αρσενα]{.greek-added} ος μελλει ποιμαινειν [παντα]{.greek-omitted} τα εθνη [εν]{.greek-omitted} ραβδω [σιδηρα]{.greek-omitted} [σιδηραι]{.greek-added} και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον [υπο]{.greek-omitted} [απο]{.greek-added} του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου [του]{.greek-added} πολεμησαι μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και ουκ [ισχυσεν]{.greek-omitted} [ισχυσαν]{.greek-added} ουδε τοπος ευρεθη αυτω ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο [οφις]{.greek-added} [ο]{.greek-added} μεγας [ο]{.greek-omitted} [οφις]{.greek-omitted} ο αρχαιος ο καλουμενος διαβολος και [ο]{.greek-added} σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην [εν]{.greek-omitted} [τω]{.greek-omitted} [εκ]{.greek-added} [του]{.greek-added} [ουρανω]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην [αυτων]{.greek-omitted} [αυτου]{.greek-added} αχρι θανατου[12:11]{.aside}

δια τουτο ευφραινεσθε [οι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν αυτοις σκηνουντες ουαι [τη]{.greek-omitted} [την]{.greek-added} [γη]{.greek-omitted} [γην]{.greek-added} και [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσαν]{.greek-added} οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον [αρρενα]{.greek-omitted} [αρσενα]{.greek-added}[12:13]{.aside}

και εδοθησαν τη γυναικι [αι]{.greek-added} δυο πτερυγες του αετου του μεγαλου ινα [πωθη]{.greek-added} [πετηται]{.corr} εις την ερημον εις τον τοπον αυτης [οπως]{.greek-omitted} [οπου]{.greek-added} [τρεφηται]{.greek-omitted} [τρεφεται]{.greek-added} εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτου]{.greek-omitted} οπισω της γυναικος υδωρ ως ποταμον ινα αυτην [ποταμοφορητον]{.greek-omitted} [ποταμοφοριτον]{.greek-added} [ποιηση]{.greek-omitted} [ποιησηι]{.greek-added}[12:15]{.aside}

και εβοηθησεν η γη [τη]{.greek-omitted} [τηι]{.greek-added} γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον [πο]{.greek-added} [ποταμον]{.greek-omitted} [ταμον]{.greek-added} ον [εβαλεν]{.greek-omitted} [εβαλλεν]{.greek-added} ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι [τη]{.greek-omitted} [τηι]{.greek-added} γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον [και]{.greek-added} μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου [ονοματα]{.greek-omitted} [ονομα]{.greek-added} βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον ην ομοιον παρδαλει και οι ποδες αυτου ως [αρκου]{.greek-omitted} [αρκτου]{.greek-added} και το στομα αυτου ως [στομα]{.greek-omitted} λεοντος και εδωκεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και [ειδον]{.greek-added} μιαν εκ των κεφαλων αυτου [ωσει]{.greek-omitted} [ως]{.greek-added} εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} δρακοντι [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [οτι]{.greek-added} [εδωκε]{.greek-added} την εξουσιαν [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} θηριω λεγοντες τις ομοιος [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} και τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημιαι]{.greek-added} και εδοθη αυτω εξουσια [πολεμον]{.greek-omitted} ποιησαι μηνας τεσσαρακοντα δυο[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις [βλασφημιαν]{.greek-omitted} [βλασφημιας]{.greek-added} προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου τους εν [τω]{.greek-omitted} [ουρανω]{.greek-abbr} σκηνουντας[13:6]{.aside}

και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ποιησαι [πολεμον]{.greek-omitted} [πολε]{.greek-added} [μον]{.greek-added} μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και [λαον]{.greek-omitted} [και]{.greek-omitted} γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν αυτω παντες οι κατοικουντες επι της γης ων ου γεγραπται [το]{.greek-omitted} [τα]{.greek-added} [ονομα]{.greek-omitted} [ονοματα]{.greek-added} [αυτων]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιλιωι]{.greek-added} [βιβλιω]{.greek-omitted} [[βιβλιωι]{.corr}]{.greek-added} της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτέννει]{.greek-added} δει αυτον εν μαχαιρα αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και [ειχεν]{.greek-omitted} [ειχε]{.greek-added} κερατα δυο ομοια [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added} και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου [πασαν]{.greek-omitted} [παντα]{.greek-added} ποιει ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} [το]{.greek-omitted} [θηριον]{.greek-omitted} [το]{.greek-omitted} [πρωτον]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-added} [τωι]{.greek-added} [πρωτωι]{.greek-added} ου εθεραπευθη η πληγη του θανατου [αυτου]{.greek-omitted}[13:12]{.aside}

και [ποιει]{.greek-omitted} [ποιηση]{.greek-added} σημεια μεγαλα [ινα]{.greek-added} και πυρ [ινα]{.greek-omitted} [ποιει]{.greek-added} εκ του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [καταβαινειν]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} [ο]{.greek-omitted} [ὃ]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} την πληγην [της]{.greek-added} [μαχαιρας]{.greek-added} και εζησεν [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [δουναι]{.greek-added} [πνευμα]{.greek-abbr} [δουναι]{.greek-omitted} [τηι]{.greek-added} [εικονι]{.greek-added} [του]{.greek-added} [θηριου]{.greek-added} [ινα]{.greek-added} [λαλησηι]{.greek-added} [η]{.greek-added} [εικων]{.greek-added} [του]{.greek-added} [θηριου]{.greek-added} [και]{.greek-added} [ποιησηι]{.greek-added} [ινα]{.greek-added} [οσοι]{.greek-added} [μη]{.greek-added} [προσκυνησωσι]{.greek-added} [[προσκυνησουσι]{.corr}]{.greek-added} τη εικονι του θηριου ινα [και]{.greek-omitted} [λαληση]{.greek-omitted} [η]{.greek-omitted} [εικων]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [και]{.greek-omitted} [ποιηση]{.greek-omitted} [οσοι]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [προσκυνησωσιν]{.greek-omitted} [τη]{.greek-omitted} [εικονι]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους [και]{.greek-omitted} [τους]{.greek-omitted} [πλουσιους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πτωχους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [ελευθερους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} ινα [δωσωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [λα]{.greek-added} [βωσιν]{.greek-added} [το]{.greek-added} [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} [αυτου]{.greek-added} επι της χειρος αυτων της δεξιας η επι το μετωπον αυτων[13:16]{.aside}

και ινα μη τις δυναται αγορασαι η πωλησαι ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν [ψηφισατω]{.greek-omitted} [ψηφησατω]{.greek-added} τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο αριθμος αυτου εστιν εξακοσια εξηκοντα εξ[13:18]{.aside}

### Chapter 14

και ειδον και ιδου το αρνιον [εστηκος]{.greek-omitted} [εστως]{.greek-added} επι το ορος σιων και μετ αυτου [αριθμος]{.greek-omitted} εκατον τεσσαρακοντα τεσσαρες χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλης και η φωνη ην ηκουσα ως κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν [ως]{.greek-added} ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις εδυνατο μαθειν την ωδην ει μη αι εκατον τεσσαρακοντα τεσσαρες χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι [εισιν]{.greek-omitted} οι ακολουθουντες [τω]{.greek-omitted} [τωι]{.greek-added} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added} οπου αν [υπαγη]{.greek-omitted} [υπαγηι]{.greek-added} ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} και [τω]{.greek-omitted} [τωι]{.greek-added} [αρνιω]{.greek-omitted} [αρνιωι]{.greek-added}[14:4]{.aside}

και [εν]{.greek-added} [τωι]{.greek-added} [στοματι]{.greek-added} [αυτων]{.greek-added} ουχ ευρεθη [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [αυτων]{.greek-omitted} ψευδος [αμωμοι]{.greek-omitted} [αμωμητοι]{.greek-added} γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added}[14:5]{.aside}

και ειδον [αλλον]{.greek-added} αγγελον πετομενον εν μεσουρανηματι εχοντα [ευαγγελιον]{.greek-omitted} [ευαγγε]{.greek-added} [λιον]{.greek-added} αιωνιον ευαγγελισαι τους καθημενους επι της γης και επι παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} και δοτε [αυτω]{.greek-omitted} [αυτωι]{.greek-added} δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε [τωι]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [ποιησαντι]{.greek-added} τον ουρανον και την γην και [την]{.greek-omitted} θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος δευτερος [αγγελος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων επεσεν [επεσε]{.greek-added} βαβυλων η μεγαλη [η]{.greek-added} εκ του οινου του θυμου της πορνειας αυτης [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} ει τις προσκυνει [το]{.greek-omitted} [θηριον]{.greek-omitted} [τωι]{.greek-added} [θηριωι]{.greek-added} και [την]{.greek-omitted} [τηι]{.greek-added} [εικονα]{.greek-omitted} [εικονι]{.greek-added} αυτου και λαμβανει [το]{.greek-added} χαραγμα επι του μετωπου αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν [τω]{.greek-omitted} [τωι]{.greek-added} ποτηριω της οργης αυτου και [βασανισθησεται]{.greek-omitted} [βασανισθησονται]{.greek-added} εν πυρι και θειω ενωπιον [των]{.greek-omitted} [αγγελων]{.greek-added} αγιων [αγγελων]{.greek-omitted} και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις αιωνας αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες [το]{.greek-omitted} [θηριον]{.greek-omitted} [τωι]{.greek-added} [θηριωι]{.greek-added} και [την]{.greek-omitted} [τηι]{.greek-added} [εικονα]{.greek-omitted} [εικονι]{.greek-added} αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added} [οι]{.greek-omitted} [των]{.greek-added} [τηρουντες]{.greek-omitted} [τηρουντων]{.greek-added} τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [ἀπ]{.greek-added} [αρτι]{.greek-omitted} [ἄρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} ινα αναπαυσωνται εκ των κοπων αυτων τα [δε]{.greek-omitted} [γαρ]{.greek-added} εργα αυτων ακολουθει μετ αυτων[14:13]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην καθημενον ομοιον υιω [ανθρωπου]{.greek-abbr} [εχων]{.greek-omitted} [εχοντα]{.greek-added} επι της κεφαλης αυτου στεφανον χρυσουν και εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου κραζων εν φωνη [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα [του]{.greek-added} θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου του εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} [κραυγη]{.greek-omitted} [φωνη]{.greek-added} μεγαλη [τω]{.greek-omitted} [τωι]{.greek-added} εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι ηκμασαν αι σταφυλαι αυτης[14:18]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις την ληνον του θυμου του [θεου]{.greek-abbr} τον [μεγαν]{.greek-omitted} [μεγαλην]{.greek-added}[14:19]{.aside}

και επατηθη η ληνος εξωθεν της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν [υεληνην]{.greek-added} [υαλινην]{.greek-omitted} [[υελινην]{.corr}]{.greek-added} μεμιγμενην πυρι και τους νικωντας εκ [της]{.greek-added} [εικονος]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} του θηριου [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [εικονος]{.greek-omitted} [αυτου]{.greek-omitted} και εκ του αριθμου του ονοματος αυτου [εστωτας]{.greek-omitted} [εστωτες]{.greek-added} επι την θαλασσαν την [υαλινην]{.greek-omitted} [υελινην]{.greek-added} εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην μωυσεως [του]{.greek-omitted} δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των [εθνων]{.greek-omitted} [αιωνων]{.greek-added}[15:3]{.aside}

τις [σε]{.greek-added} ου [μη]{.greek-omitted} φοβηθη [σε]{.greek-omitted} [κυριε]{.greek-abbr} και δοξαση το ονομα σου οτι μονος αγιος [ει]{.greek-added} οτι παντα [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} [σε]{.greek-added} [[κυριε]{.greek-abbr}]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} [σου]{.greek-omitted} [συ]{.greek-added} [[κυριε]{.greek-abbr}]{.greek-added} οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι [οι]{.greek-omitted} εχοντες τας επτα πληγας εκ του ναου [οι]{.greek-omitted} [ησαν]{.greek-omitted} ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων [ζωων]{.greek-omitted} [ζωιων]{.greek-added} [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα [μεγαλης]{.greek-added} φωνης [μεγαλης]{.greek-omitted} εκ του ναου λεγουσης τοις επτα αγγελοις υπαγετε και [εκχεατε]{.greek-omitted} [εκχεετε]{.greek-added} τας επτα φιαλας του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον [ε]{.greek-added} [επι]{.greek-omitted} [πι]{.greek-added} τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας [τη]{.greek-omitted} [τηι]{.greek-added} εικονι αυτου[16:2]{.aside}

και ο δευτερος [αγγελος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη [ζωσα]{.greek-omitted} [ζωης]{.greek-added} [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} [των]{.greek-added} εν τη [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added}[16:3]{.aside}

και ο τριτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την [φιαλην]{.greek-omitted} [φιαλη]{.greek-added} αυτου εις τους ποταμους και [εις]{.greek-omitted} τας πηγας των υδατων και [εγενετο]{.greek-omitted} [εγενοντο]{.greek-added} αιμα[16:4]{.aside}

και ηκουσα του αγγελου [του]{.greek-added} [επι]{.greek-added} των υδατων λεγοντος δικαιος ει ο ων και ο ην [και]{.greek-added} ο οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν αξιοι [ησι]{.greek-added} [εισιν]{.greek-omitted} [[εισι]{.corr}]{.greek-added}[16:6]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος [αγγελος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} καυματισαι [τους]{.greek-added} [[ανθρωπους]{.greek-abbr}]{.greek-added} εν πυρι [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν [κατα]{.greek-added} [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} [το]{.greek-omitted} [του]{.greek-added} [ονομα]{.greek-omitted} [ονοματος]{.greek-added} του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και [εμασωντο]{.greek-omitted} [εμασσοντο]{.greek-added} τας [γλωσσας]{.greek-omitted} [γλωσας]{.greek-added} αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ποταμον τον μεγαν [τον]{.greek-added} [ευφρατην]{.greek-omitted} [εφρατην]{.greek-added} και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου [πνευματα]{.greek-abbr} [ακαθαρτα]{.greek-omitted} τρια ως βατραχοι[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ [πνευματα]{.greek-abbr} δαιμονιων [ακαθαρτων]{.greek-added} ποιουντα σημεια [α]{.greek-omitted} [εκπορευεται]{.greek-omitted} [εκπορευεσθαι]{.greek-added} επι [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον [της]{.greek-omitted} [ημερας]{.greek-omitted} [εκεινης]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος [περιπατει]{.greek-added} [περιπατη]{.corr} και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἁρμαγεδῶν]{.greek-added}[16:16]{.aside}

και ο εβδομος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη απο του ναου [εκ]{.greek-added} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} του θρονου λεγουσα γεγονεν[16:17]{.aside}

και εγενοντο αστραπαι και [φωναι]{.greek-added} [και]{.greek-added} βρονται και [φωναι]{.greek-omitted} [και]{.greek-omitted} σεισμος [εγενετο]{.greek-added} μεγας οιος ουκ εγενετο αφ ου [οι]{.greek-omitted} [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος ουτως μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων επεσον και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι αυτη [το]{.greek-omitted} ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα [η]{.greek-added} νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις [εκ]{.greek-omitted} των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της [μεγαλης]{.greek-omitted} [της]{.greek-omitted} καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της [πορνειας]{.greek-omitted} [πορνιας]{.greek-added} αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον [τοπον]{.greek-added} εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον κοκκινον [γεμον]{.greek-omitted} [γεμων]{.greek-added} ονοματα βλασφημιας [εχον]{.greek-omitted} [εχων]{.greek-added} κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἦν]{.greek-added} περιβεβλημενη πορφυρουν και κοκκινον [κεχρυσωμενη]{.greek-omitted} [κεχρυσωμενον]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις εχουσα ποτηριον χρυσουν εν τη χειρι αυτης [γεμον]{.greek-omitted} [γεμων]{.greek-added} βδελυγματων και τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν εκ του αιματος των αγιων [και]{.greek-added} εκ του αιματος των μαρτυρων [του]{.greek-added} [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος δια τι εθαυμασας εγω ερω σοι το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες επι της γης ων ου γεγραπται [τα]{.greek-omitted} [ονοματα]{.greek-omitted} [επι]{.greek-omitted} το [βιβλιον]{.greek-omitted} [ονομα]{.greek-added} [εν]{.greek-added} [τωι]{.greek-added} [βιβλιωι]{.greek-added} της ζωης απο καταβολης κοσμου βλεποντων [το]{.greek-added} [θηριον]{.greek-added} οτι ην [το]{.greek-omitted} [θηριον]{.greek-omitted} και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [επτα]{.greek-added} [εισιν]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε επεσον ο εις εστιν ο αλλος ουπω [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και οταν ελθη ολιγον [αυτον]{.greek-added} δει [αυτον]{.greek-omitted} μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και [αυτος]{.greek-omitted} [ουτος]{.greek-added} ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} και εκ των επτα [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον [αλλ]{.greek-omitted} [αλλα]{.greek-added} εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} γνωμην [εχουσι]{.greek-added} και την δυναμιν και [την]{.greek-omitted} εξουσιαν αυτων [τω]{.greek-omitted} [τωι]{.greek-added} θηριω διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου πολεμησουσιν και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην ποιησουσιν αυτην και γυμνην [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} και τας σαρκας αυτης φαγονται και αυτην [κατακαυσουσιν]{.greek-omitted} [κατακαυσωσιν]{.greek-added} εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι [μιαν]{.greek-added} γνωμην [μιαν]{.greek-omitted} [αυτων]{.greek-added} και δουναι την βασιλειαν αυτων [τω]{.greek-omitted} [τωι]{.greek-added} [θηριω]{.greek-omitted} [θηριωι]{.greek-added} αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν [εν]{.greek-added} ισχυρα φωνη λεγων [επεσεν]{.greek-added} επεσεν βαβυλων η μεγαλη και εγενετο κατοικητηριον [δαιμονων]{.greek-omitted} [δαιμονιων]{.greek-added} και φυλακη παντος [πνευματος]{.greek-abbr} ακαθαρτου και φυλακη παντος ορνεου ακαθαρτου και μεμισημενου[18:2]{.aside}

οτι εκ του οινου του θυμου της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπτωκασι]{.greek-added} [[πεπωκασι]{.corr}]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του [στρηνους]{.greek-omitted} [στηνους]{.greek-added} [[θρηνους]{.corr}]{.greek-added} αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν [εξελθε]{.greek-omitted} [εξελθετε]{.greek-added} εξ αυτης ο λαος μου ινα μη [συγκυνωνησητε]{.greek-added} συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν και διπλωσατε [αυτη]{.greek-omitted} διπλα κατα τα εργα αυτης εν [τω]{.greek-omitted} [τωι]{.greek-added} [ποτηριω]{.greek-omitted} [ποτηριωι]{.greek-added} [ω]{.greek-omitted} [ο]{.greek-added} εκερασεν κερασατε αυτη διπλουν[18:6]{.aside}

οσα εδοξασεν [αυτην]{.greek-omitted} [εαυτην]{.greek-added} και εστρηνιασεν τοσουτον δοτε αυτη βασανισμον και πενθος οτι εν [τη]{.greek-omitted} [τηι]{.greek-added} [καρδια]{.greek-omitted} [καρδιαι]{.greek-added} αυτης λεγει οτι καθημα[ι]{.unclear} [β]{.unclear}ασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια [ημερα]{.greek-omitted} [ημεραι]{.greek-added} ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-omitted} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και κοψονται επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον [του]{.corr} [βασανισμου]{.corr} αυτης λεγοντες ουαι ουαι η πολις η μεγαλη βαβυλων η πολις η ισχυρα οτι [μια]{.greek-omitted} [μιαν]{.greek-added} [ωρα]{.greek-omitted} [ωραν]{.greek-added} ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαιουσι]{.greek-added} και [πενθησουσιν]{.greek-omitted} [πενθουσιν]{.greek-added} επ [αυτη]{.greek-omitted} [αυτηι]{.greek-added} οτι τον γομον αυτων ουδεις αγοραζει [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [ετι]{.greek-added}[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και [μαργαριτου]{.greek-omitted} [μαργαριτων]{.greek-added} και βυσσινου και [πορφυρου]{.greek-omitted} [πορ]{.greek-added} [φυρας]{.greek-added} και [σηρικου]{.greek-omitted} [σιρικου]{.greek-added} και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ [ξυλου]{.greek-omitted} [λιθου]{.greek-added} τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμων]{.greek-added} [κιναμωμον]{.corr} και [θυμιαματα]{.greek-omitted} [θυμιαμα]{.greek-added} και μυρον και λιβανον και οινον και ελαιον και σεμιδαλιν και σιτον και [κτηνη]{.greek-added} [και]{.greek-added} προβατα και [ιππους]{.greek-added} [κτηνη]{.greek-omitted} [και]{.greek-omitted} [ιππων]{.greek-omitted} και ραιδων και σωματων και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η οπωρα [σου]{.greek-added} της επιθυμιας της ψυχης [σου]{.greek-omitted} [απηλθεν]{.greek-omitted} [απηλθον]{.greek-added} απο σου και παντα τα λιπαρα [σου]{.greek-added} και τα λαμπρα απωλετο απο σου και ουκετι [αυτα]{.greek-omitted} ου μη [αυτα]{.greek-added} ευρης[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15]{.aside}

[και]{.greek-omitted} λεγοντες ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και πορφυρουν και [κοκκινον]{.greek-omitted} [κοκινον]{.greek-added} [και]{.greek-omitted} κεχρυσωμενη [χρυσιω]{.greek-omitted} [χρυσιωι]{.greek-added} και λιθω [τιμιω]{.greek-omitted} [τιμιωι]{.greek-added} και [μαργαριταις]{.greek-omitted} [μαργαριτηι]{.greek-added}[18:16]{.aside}

οτι [μια]{.greek-omitted} [μιαι]{.greek-added} [ωρα]{.greek-omitted} [ωραι]{.greek-added} ηρημωθη [ο]{.greek-omitted} τοσουτος πλουτος και πας κυβερνητης και πας ο επι τοπον πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και [εκραζον]{.greek-omitted} [εκραξαν]{.greek-added} βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια [τη]{.greek-omitted} [τηι]{.greek-added} πολει [τη]{.greek-omitted} [τηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added}[18:18]{.aside}

και [εβαλον]{.greek-omitted} [επεβαλλον]{.greek-added} χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες [και]{.greek-omitted} λεγοντες [ουαι]{.greek-omitted} ουαι η πολις η μεγαλη εν [η]{.greek-omitted} [ηι]{.greek-added} επλουτησαν παντες οι εχοντες τα πλοια εν [τη]{.greek-omitted} [τηι]{.greek-added} θαλασση εκ της τιμιοτητος αυτης οτι [μια]{.greek-omitted} [μιαι]{.greek-added} [ωρα]{.greek-omitted} [ωραι]{.greek-added} ηρημωθη[18:19]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και [εβαλεν]{.greek-omitted} [εβα]{.greek-added} [λεν]{.greek-added} εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης πασης τεχνης ου μη ευρεθη εν σοι ετι και φωνη μυλου ου μη [ακουσθη]{.greek-omitted} [ακουσθηι]{.greek-added} εν σοι ετι[18:22]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [φανῆ]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη [ακουσθη]{.greek-omitted} [ακουσθηι]{.greek-added} εν σοι ετι οτι [οι]{.greek-omitted} εμποροι σου ησαν οι μεγιστανες της γης οτι εν [τη]{.greek-omitted} [τηι]{.greek-added} [φαρμακεια]{.greek-omitted} [φαρμακειαι]{.greek-added} σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} αιματα προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην μεγαλην οχλου πολλου εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δοξα]{.greek-added} και η [δοξα]{.greek-omitted} [δυναμις]{.greek-added} του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [εφθειρε]{.greek-added} την γην εν [τη]{.greek-omitted} [τηι]{.greek-added} πορνεια αυτης και [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ χειρος αυτης[19:2]{.aside}

και δευτερον [ειρηκεν]{.greek-omitted} [ειρηκασιν]{.greek-added} αλληλουια και ο καπνος αυτης αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι πρεσβυτεροι οι εικοσι τεσσαρες και τα τεσσαρα ζωα και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τωι]{.greek-added} [θρονωι]{.greek-added} λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη απο του θρονου [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} λεγουσα αινειτε τον [θεον]{.greek-abbr} ημων [αινειτε]{.greek-added} παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα [ως]{.greek-omitted} φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως [φω]{.greek-added} [φωνην]{.greek-omitted} [νην]{.greek-added} βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντων]{.greek-added} αλληλουια οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και [αγαλλιωμεθα]{.greek-omitted} [αγαλλιωμεν]{.greek-added} και δωμεν την δοξαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν [αυτην]{.greek-added} [εαυτην]{.corr}[19:7]{.aside}

και εδοθη [αυτη]{.greek-omitted} [αυτηι]{.greek-added} ινα [περιβαληται]{.greek-omitted} [περιβαλληται]{.greek-added} βυσσινον λαμπρον [και]{.greek-omitted} καθαρον το γαρ βυσσινον τα δικαιωματα των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις το δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι [αληθινοι]{.greek-omitted} του [θεου]{.greek-abbr} [αληθινοι]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added}[19:9]{.aside}

και [επεσα]{.greek-omitted} [επεσον]{.greek-added} εμπροσθεν των ποδων [αυτου]{.greek-omitted} [του]{.greek-added} [αγγελου]{.greek-added} προσκυνησαι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και λεγει μοι ορα μη [ποιησης]{.greek-added} συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια [του]{.greek-omitted} [ιησου]{.greek-abbr} εστιν το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον [και]{.greek-added} καλουμενος πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου [ως]{.greek-added} φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων ονοματα γεγραμμενα και ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον [βεβαμμενον]{.greek-omitted} [ερραντισμενον]{.greek-added} αιματι και [καλειται]{.greek-omitted} [κεκληται]{.greek-added} το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα τα εν [[ουνωι]{.greek-abbr}]{.greek-added} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} ηκολουθει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [επι]{.greek-omitted} [εφ]{.greek-added} ιπποις λευκοις ενδεδυμενοι [λευκο]{.greek-added} βυσσινον [λευκον]{.greek-omitted} καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν αυτη [παταξη]{.greek-omitted} [παταξηι]{.greek-added} τα εθνη και αυτος ποιμανει αυτους εν [ραβδω]{.greek-omitted} [ραβδωι]{.greek-added} [σιδηρα]{.greek-omitted} [σιδηραι]{.greek-added} και αυτος πατει την ληνον του [οινου]{.greek-omitted} [θυμου]{.greek-added} του [θυμου]{.greek-omitted} [οι]{.greek-added} [νου]{.greek-added} της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το [ιματιον]{.greek-omitted} [μετωπον]{.greek-added} και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον [ενα]{.greek-added} αγγελον εστωτα εν [τω]{.greek-omitted} [τωι]{.greek-added} [ηλιω]{.greek-omitted} [ηλιωι]{.greek-added} και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} [φωνη]{.greek-omitted} [φωνηι]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι δευτε συναχθητε εις το δειπνον το μεγα του [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων και μικρων [τε]{.greek-omitted} και [των]{.greek-added} μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων [συνηγμενα]{.greek-omitted} [συναγμενα]{.greek-added} ποιησαι πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον και ο μετ αυτου ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες εβληθησαν [οι]{.greek-omitted} [δυο]{.greek-omitted} εις την λιμνην του πυρος την καιομενην εν θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν [τη]{.greek-omitted} [τηι]{.greek-added} [ρομφαια]{.greek-omitted} [ρομφαιαι]{.greek-added} του καθημενου επι του ιππου [τη]{.greek-omitted} [τηι]{.greek-added} [εξελθουση]{.greek-omitted} [εξελθουσηι]{.greek-added} εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον [καταβαινοντα]{.greek-omitted} [καταταβαινοντα]{.greek-added} εκ του [ουρανου]{.greek-abbr} εχοντα την κλειν της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντα τον οφιν τον [αρχαιον]{.greek-omitted} [αρχαι]{.greek-added} [ον]{.greek-added} ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και ο σατανας [ο]{.greek-omitted} [πλανων]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} [ολην]{.greek-omitted} και εδησεν αυτον χιλια ετη [σημειον]{.greek-added}[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλεισε]{.greek-added} και [εσφραγισεν]{.greek-omitted} [εσφραγησεν]{.greek-added} επανω αυτου ινα μη [πλανα]{.greek-omitted} [πλανηση]{.greek-added} ετι τα εθνη αχρι τελεσθη τα χιλια ετη [και]{.greek-omitted} μετα ταυτα δει [λυθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και ειδον θρονους και εκαθισαν επ αυτους και κριμα εδοθη αυτοις και [ειδον]{.greek-added} τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν [το]{.greek-omitted} [θηριον]{.greek-omitted} [τωι]{.greek-added} [θηριωι]{.greek-added} ουδε [την]{.greek-omitted} [τηι]{.greek-added} [εικονα]{.greek-omitted} [εικονι]{.greek-added} αυτου και ουκ ελαβον το χαραγμα [του]{.greek-added} [θηριου]{.greek-added} επι το μετωπον και επι την χειρα αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} τα χιλια ετη[20:4]{.aside}

και οι λοιποι των νεκρων ουκ εζησαν αχρι τελεσθη τα χιλια [ετη]{.greek-omitted} [ετι]{.greek-added} αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν [τη]{.greek-omitted} [τηι]{.greek-added} αναστασει [τη]{.greek-omitted} [τηι]{.greek-added} [πρωτη]{.greek-omitted} [πρωτηι]{.greek-added} επι [τουτων]{.greek-omitted} [τουτον]{.greek-added} ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου χιλια ετη[20:6]{.aside}

και οταν τελεσθη τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης τον γωγ και τον μαγωγ συναγαγειν αυτους εις τον πολεμον ων ο αριθμος [αυτων]{.greek-added} ως [η]{.greek-omitted} [ο]{.greek-added} αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και [εκυκλωσαν]{.greek-omitted} [εκυκλευσαν]{.greek-added} την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ [απο]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και [του]{.greek-added} θειου οπου και το θηριον και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10]{.aside}

και ειδον θρονον μεγαν λευκον και τον καθημενον επ [αυτον]{.greek-omitted} [αυτου]{.greek-added} ου απο [του]{.greek-added} προσωπου [αυτου]{.greek-added} εφυγεν η γη και ο [ουρανος]{.greek-abbr} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον τους νεκρους τους μεγαλους και τους μικρους εστωτας ενωπιον του θρονου και βιβλια [ηνεωχθησαν]{.greek-omitted} [ηνοιχθησαν]{.greek-added} και αλλο βιβλιον ηνεωχθη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} και ο θανατος και ο [αδης]{.greek-omitted} [αιδης]{.greek-added} εδωκαν τους νεκρους τους εν αυτοις και εκριθησαν εκαστος κατα τα εργα αυτων[20:13]{.aside}

και ο θανατος και ο [αδης]{.greek-omitted} [αιδης]{.greek-added} εβληθησαν εις την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ει τις ουχ ευρεθη εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλω]{.greek-added} της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη απηλθον και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του [θεου]{.greek-abbr} ητοιμασμενην ως νυμφην κεκοσμημενην [τω]{.greek-omitted} [τωι]{.greek-added} ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} [εσται]{.greek-omitted} μετ αυτων [εσται]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added}[21:3]{.aside}

και εξαλειψει [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} παν δακρυον απο των οφθαλμων αυτων και ο θανατος ουκ [ετι]{.greek-added} εσται [ετι]{.greek-omitted} ουτε πενθος ουτε κραυγη ουτε πονος ουκ εσται ετι [οτι]{.greek-omitted} τα πρωτα απηλθον[21:4]{.aside}

και ειπεν ο καθημενος [επι]{.greek-omitted} [εν]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} [θρονω]{.greek-omitted} [θρονωι]{.greek-added} ιδου [παντα]{.greek-omitted} καινα ποιω [παντα]{.greek-added} και λεγει μοι γραψον οτι ουτοι οι λογοι [πιστοι]{.greek-added} [και]{.greek-added} αληθινοι [και]{.greek-omitted} [πιστοι]{.greek-omitted} [εισιν]{.greek-omitted} [εισι]{.greek-added}[21:5]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι [γεγονα]{.greek-omitted} [γεγονασιν]{.greek-added} [εγω]{.greek-added} [ειμι]{.greek-added} το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} η αρχη και το τελος εγω [τω]{.greek-omitted} [τωι]{.greek-added} διψωντι δωσω εκ της πηγης του υδατος της ζωης δωρεαν[21:6]{.aside}

ο νικων κληρονομησει ταυτα και εσομαι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [θεος]{.greek-abbr} και [αυτος]{.greek-omitted} εσται μοι υιος[21:7]{.aside}

τοις δε δειλοις και απιστοις και [αμαρτωλοις]{.greek-omitted} [και]{.greek-omitted} εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} και πορνοις και φαρμακοις και ειδωλολατραις και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν [τη]{.greek-omitted} [τηι]{.greek-added} [λιμνη]{.greek-omitted} [λιμνηι]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} καιομενη πυρι και [θειω]{.greek-omitted} [θειωι]{.greek-added} ο εστιν ο θανατος ο δευτερος[21:8]{.aside}

και ηλθεν εις [εκ]{.greek-omitted} των επτα αγγελων των εχοντων τας επτα φιαλας [τας]{.greek-added} γεμουσας των επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την [νυμφην]{.greek-added} [την]{.greek-added} γυναικα [την]{.greek-omitted} [νυμφην]{.greek-omitted} του αρνιου[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εν [πνευματι]{.greek-abbr} [επ]{.greek-omitted} [επι]{.greek-added} ορος μεγα και υψηλον και εδειξεν μοι την πολιν την [μεγαλην]{.greek-omitted} [την]{.greek-omitted} αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν εκ του ουρανου απο του [θεου]{.greek-abbr}[21:10]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης ομοιος λιθω [τιμιωτατω]{.greek-omitted} [τιμιωτατωι]{.greek-added} ως [λιθω]{.greek-omitted} [λιθωι]{.greek-added} ιασπιδι κρυσταλλιζοντι[21:11]{.aside}

εχουσα τειχος μεγα και υψηλον [εχουσα]{.greek-omitted} [εχου]{.greek-added} [σα]{.greek-added} πυλωνας δωδεκα και επι τοις πυλωσιν αγγελους δωδεκα και ονοματα επιγεγραμμενα α [τινα]{.greek-added} εστιν ονοματα των δωδεκα φυλων [του]{.greek-added} [των]{.greek-omitted} [υιων]{.greek-omitted} [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο [ανατολων]{.greek-omitted} [ανατολης]{.greek-added} πυλωνες τρεις και απο βορρα πυλωνες τρεις και απο [νοτου]{.greek-omitted} [πυλωνες]{.greek-omitted} [τρεις]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} δυσμων πυλωνες τρεις[21:13]{.aside}

και το τειχος της πολεως [εχον]{.greek-omitted} [εχων]{.greek-added} θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} μετρον καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον [και]{.greek-added} το πλατος και εμετρησεν την πολιν [τω]{.greek-omitted} [τωι]{.greek-added} [καλαμω]{.greek-omitted} [καλαμωι]{.greek-added} επι σταδιους δωδεκα χιλιαδων [δωδεκα]{.greek-omitted} το μηκος και το πλατος και το υψος αυτης ισα εστιν[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} το τειχος αυτης εκατον τεσσαρακοντα τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον ομοιον υελω [καθαρω]{.greek-omitted} [καθαρωι]{.greek-added}[21:18]{.aside}

οι θεμελιοι του τειχους της πολεως παντι λιθω [τιμιω]{.greek-omitted} [τιμιωι]{.greek-added} κεκοσμημενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος [σαρδονυξ]{.greek-omitted} [σαρδωνυξ]{.greek-added} ο εκτος σαρδιον ο εβδομος χρυσολιθος ο [ογδοος]{.greek-omitted} [ογδος]{.greek-added} [βρυλλος]{.greek-added} [βηρυλλος]{.corr} ο ενατος τοπαζιον ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος ο δωδεκατος αμεθυσος[21:20]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται ανα εις εκαστος των πυλωνων [ην]{.greek-omitted} εξ ενος μαργαριτου και η πλατεια της πολεως χρυσιον καθαρον ως υελος διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} η γαρ δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης [φερουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [φερωσι]{.greek-added} [την]{.greek-added} δοξαν [και]{.greek-omitted} [τιμην]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [εθνων]{.greek-omitted} εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη [κλεισθωσιν]{.greek-omitted} [κλεισθησωσιν]{.greek-added} ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην[21:26]{.aside}

και ου μη εισελθη εις αυτην παν κοινον και [ποιουν]{.greek-omitted} [ποιων]{.greek-added} βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν [τω]{.greek-omitted} [τωι]{.greek-added} βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον [καθαρον]{.greek-omitted} υδατος ζωης λαμπρον ως κρυσταλλον εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και εκειθεν ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα εκαστον [αποδιδους]{.greek-omitted} [αποδιδον]{.greek-added} τον καρπον αυτου και τα φυλλα του ξυλου εις θεραπειαν των εθνων[22:2]{.aside}

και παν καταθεμα ουκ εσται ετι και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι δουλοι αυτου λατρευσουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added}[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των μετωπων αυτων[22:4]{.aside}

και νυξ ουκ εσται [εκει]{.greek-omitted} [ετι]{.greek-added} και [ουχ]{.greek-added} [εξουσι]{.greek-added} χρειαν [φωτος]{.greek-added} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} λυχνου και φωτος ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [φωτιει]{.greek-omitted} [φωτισει]{.greek-added} [επ]{.greek-added} αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και [λεγει]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι [οι]{.greek-omitted} [ο]{.greek-added} λογοι πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-abbr} των προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} [με]{.greek-added} τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

και ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

καγω ιωαννης ο [βλεπων]{.greek-added} [και]{.greek-added} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} ταυτα και οτε ηκουσα και εβλεψα επεσον προσκυνησαι εμπροσθεν των ποδων του αγγελου του [δεικνυοντος]{.greek-omitted} [δεικνυντος]{.greek-added} μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη [ποιησης]{.greek-added} συνδουλος σου ειμι και των αδελφων σου των προφητων και των τηρουντων τους λογους του βιβλιου [τουτου]{.greek-omitted} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου ο καιρος γαρ εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος ρυπαρευθητω ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον [εσται]{.greek-omitted} [εστιν]{.greek-added} αυτου[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} ο πρωτος και ο εσχατος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι [ποιουντες]{.greek-omitted} [πλυνοντες]{.greek-added} τας [εντολας]{.greek-omitted} [στολας]{.greek-added} [αυτου]{.greek-omitted} [αυτων]{.greek-added} ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και ο[ι]{.unclear} φαρμακοι και οι πορνοι και οι φονεις και οι ειδωλολατραι και πας φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα [επι]{.greek-omitted} [εν]{.greek-added} ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} ο αστηρ ο λαμπρος [ο]{.greek-omitted} [και]{.greek-added} πρωινος[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν [ερχου]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ακουων]{.greek-omitted} [ειπατω]{.greek-omitted} ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι [τω]{.greek-omitted} [τωι]{.greek-added} [ακουοντι]{.greek-omitted} [αακουοντι]{.greek-added} τους λογους της προφητειας του βιβλιου τουτου εαν τις [επιθη]{.greek-omitted} [επιθηι]{.greek-added} επ αυτα [επιθησαι]{.greek-omitted} [επιθησει]{.greek-added} ο [θεος]{.greek-abbr} επ αυτον τας πληγας τας [γεγραμμενας]{.greek-omitted} [γεγραμενας]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλιωι]{.greek-added} τουτω[22:18]{.aside}

και εαν τις αφελη απο των λογων του βιβλιου της προφητειας ταυτης [αφελοι]{.greek-omitted} [αφελει]{.greek-added} ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν [τω]{.greek-omitted} [τωι]{.greek-added} βιβλιω [τουτω]{.greek-omitted} [τουτωι]{.greek-added}[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην [ναι]{.greek-omitted} ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων [αμην]{.greek-omitted}[22:21]{.aside}

