---
title: "Collation of Byz^RP^ vs 31009 (1009)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1009 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31009).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1009                                   	| λογος                              	|
| 1009 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1009 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1009               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1009                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1009 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1009                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως [γεγραπται]{.greek-omitted} [γαιγραπται]{.greek-added} εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας [ποιη]{.greek-added} [ποιειτε]{.greek-omitted} [[ποιειται]{.corr}]{.greek-added} τας τριβους αυτου[1:3]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα [η]{.greek-omitted} ιουδαια χωρα και [οι]{.greek-omitted} [ιεροσολυμιται]{.greek-omitted} [ιεροσολυμειτε]{.greek-added} και εβαπτιζοντο παντες εν τω ιορδανη ποταμω [υπ]{.greek-omitted} [αυτου]{.greek-omitted} εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην [δερματινην]{.greek-omitted} [δερματι]{.greek-added} [περι]{.greek-omitted} [την]{.greek-omitted} [οσφυν]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εσθιων]{.greek-omitted} [ακριδας]{.greek-omitted} [και]{.greek-omitted} [μελι]{.greek-omitted} [αγριον]{.greek-omitted}[1:6]{.aside}

[ην]{.greek-omitted} [νην]{.greek-added} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιωαννης]{.greek-omitted} [ενδεδυμενος]{.greek-omitted} [τριχας]{.greek-omitted} [καμηλου]{.greek-omitted} [και]{.greek-omitted} [ζωνην]{.greek-omitted} [δερματινην]{.greek-omitted} περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6 | instance no. 2]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν [καταβαινον]{.greek-omitted} [καταβαινων]{.greek-added} επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω ευδοκησα[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} [αυτον]{.greek-omitted} [αυτων]{.greek-added} εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα [και]{.greek-added} [νυκτας]{.greek-added} [τεσσερακοντα]{.greek-added} πειραζομενος υπο του σατανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι [[ιω]{.greek-abbr}]{.greek-added} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} ηλθεν [ο]{.greek-omitted} [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται [ο]{.greek-omitted} [καιρος]{.greek-omitted} [και]{.greek-omitted} [ηγγικεν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μετανοειτε]{.greek-omitted} [και]{.greek-omitted} [πιστευετε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ευαγγελιω]{.greek-omitted}[1:15]{.aside}

[και]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [πεπληρωται]{.greek-omitted} ο καιρος και [ηγγικεν]{.greek-omitted} [ηγγηκεν]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} [μετανοειτε]{.greek-omitted} [μετανοητε]{.greek-added} και πιστευετε εν τω ευαγγελιω[1:15 | instance no. 2]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [σιμωνα]{.greek-omitted} [σιμονα]{.greek-added} και ανδρεαν τον αδελφον αυτου του [σιμωνος]{.greek-omitted} [σιμονος]{.greek-added} βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα [δικτυα]{.greek-omitted} [δεικτυα]{.greek-added} αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα [δικτυα]{.greek-omitted} [δεικτυα]{.greek-added} [αυτων]{.greek-added}[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των [μισθωτων]{.greek-omitted} [μισθοτων]{.greek-added} απηλθον οπισω αυτου[1:20]{.aside}

και [εισπορευονται]{.greek-omitted} [εισπορευοντε]{.greek-added} εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις [αυτων]{.greek-added}[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [ακαθαρτω]{.greek-omitted} [και]{.greek-omitted} [ανεκραξεν]{.greek-omitted}[1:23]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [συναγωγη]{.greek-omitted} [αυτων]{.greek-omitted} [ανθρωπος]{.greek-omitted} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [εκραξεν]{.greek-added}[1:23 | instance no. 2]{.aside}

λεγων εα τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζωρινε]{.greek-added} ηλθες [απολεσαι]{.greek-omitted} [απωλεσαι]{.greek-added} ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων [φιμωθητι]{.greek-omitted} [φημωθητι]{.greek-added} και εξελθε [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι εστιν τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα [του]{.greek-added} σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον [παν]{.greek-added} [παντας]{.greek-omitted} [τους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δαιμονιζομενους]{.greek-omitted}[1:32]{.aside}

[τας]{.greek-added} [οψιας]{.greek-omitted} [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [οτε]{.greek-omitted} [εδυ]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [εφερον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [παντας]{.greek-omitted} τους κακως εχοντας και τους δαιμονιζομενους[1:32 | instance no. 2]{.aside}

και η [πολις]{.greek-omitted} [πολης]{.greek-added} ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και εθεραπευσεν [πολλους]{.greek-omitted} [παντας]{.greek-added} [τους]{.greek-added} κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα εξεβαλεν και ουκ ηφιεν λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ιδεισαν]{.greek-added} αυτον [τον]{.greek-added} [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι εννυχον λιαν αναστας εξηλθεν και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και κατεδιωξαν αυτον ο [σιμων]{.greek-omitted} [σιμον]{.greek-added} και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας [κωμοπολεις]{.greek-omitted} [κομοπολεις]{.greek-added} ινα [και]{.greek-omitted} εκει κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} προς αυτον λεπρος παρακαλων αυτον και γονυπετων [αυτων]{.greek-added} [αυτον]{.corr} και λεγων αυτω οτι εαν θελης δυνασαι με [καθαρισαι]{.greek-omitted} [καθαρησαι]{.greek-added}[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω [θελω]{.greek-omitted} [εθελω]{.greek-added} καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και [εμβριμησαμενος]{.greek-omitted} [αυτω]{.greek-omitted} [ευθεως]{.greek-omitted} [εξεβαλεν]{.greek-omitted} [αυτον]{.greek-omitted}[1:43]{.aside}

[και]{.greek-omitted} εμβριμησαμενος [αυτω]{.greek-omitted} [αυτον]{.greek-added} ευθεως εξεβαλεν αυτον[1:43 | instance no. 2]{.aside}

και λεγει αυτω ορα [μηδεν]{.greek-added} [ειπεις]{.greek-added} μηδενι [μηδεν]{.greek-omitted} [ειπης]{.greek-omitted} αλλ υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον [δυνασθαι]{.greek-omitted} [δυνασθε]{.greek-added} φανερως εις [πολιν]{.greek-omitted} [πολην]{.greek-added} εισελθειν [αλλ]{.greek-omitted} [αλλα]{.greek-added} εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και εισηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} παλιν εις καπερναουμ δι ημερων και [ηκουσθη]{.greek-omitted} [εικουσθη]{.greek-added} οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον[2:2]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} προς αυτον παραλυτικον [φεροντες]{.greek-omitted} [φαιροντες]{.greek-added} αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι [προσεγγισαι]{.greek-omitted} [προσεγγεισαι]{.greek-added} αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες χαλωσιν τον κραββατον εφ [ω]{.greek-omitted} [ο]{.greek-added} ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [α]{.greek-added} [αφεωνται]{.greek-omitted} [σοι]{.greek-omitted} [αι]{.greek-omitted} [αμαρτιαι]{.greek-omitted} [σου]{.greek-omitted}[2:5]{.aside}

[φαιονται]{.greek-added} [σου]{.greek-added} [ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [παραλυτικω]{.greek-omitted} [τεκνον]{.greek-omitted} [αφεωνται]{.greek-omitted} [σοι]{.greek-omitted} αι αμαρτιαι σου[2:5 | instance no. 2]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} λαλει [βλασφημιας]{.greek-omitted} [βλασφημειας]{.greek-added} τις [δυναται]{.greek-omitted} [δυνατε]{.greek-added} αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι [διαλογιζονται]{.greek-omitted} [διαλογιζοντε]{.greek-added} εν εαυτοις ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφαιονται]{.greek-added} σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιεναι]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

[σοι]{.greek-omitted} [συ]{.greek-added} λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν [εναντιον]{.greek-omitted} [ενωπιον]{.greek-added} παντων ωστε [εξιστασθαι]{.greek-omitted} [εξιστασθε]{.greek-added} παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added}[2:12]{.aside}

και εξηλθεν παλιν παρα την θαλασσαν και πας ο οχλος [ηρχετο]{.greek-omitted} [ηρχοντο]{.greek-added} προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και [παραγων]{.greek-omitted} [ειδεν]{.greek-omitted} [λευι]{.greek-omitted} [τον]{.greek-omitted} [του]{.greek-omitted} [αλφαιου]{.greek-omitted} [καθημενον]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [τελωνιον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ακολουθει]{.greek-omitted} [μοι]{.greek-omitted} [και]{.greek-omitted} [αναστας]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted}[2:14]{.aside}

[και]{.greek-omitted} παραγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[2:14 | instance no. 2]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη [οικια]{.greek-omitted} [οικεια]{.greek-added} αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων [ελεγον]{.greek-added} [τοις]{.greek-added} [μαθηταις]{.greek-added} [αυτου]{.greek-added} εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και [ησαν]{.greek-omitted} [εισαν]{.greek-added} οι μαθηται ιωαννου και οι των φαρισαιων νηστευοντες και [ερχονται]{.greek-omitted} [ερχουντε]{.greek-added} και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του [νυμ]{.greek-added} [νυμφωνος]{.greek-omitted} [εν]{.greek-omitted} [ω]{.greek-omitted} [ο]{.greek-omitted} [νυμφιος]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted} [εστιν]{.greek-omitted} [νηστευειν]{.greek-omitted} [οσον]{.greek-omitted} [χρονον]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτων]{.greek-omitted} [εχουσιν]{.greek-omitted} [τον]{.greek-omitted} [νυμφιον]{.greek-omitted} [ου]{.greek-omitted} [δυνανται]{.greek-omitted} [νηστευειν]{.greek-omitted}[2:19]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [μη]{.greek-omitted} [δυνανται]{.greek-omitted} [οι]{.greek-omitted} [υιοι]{.greek-omitted} [του]{.greek-omitted} [νυμφωνος]{.greek-omitted} [φωνος]{.greek-added} εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον μεθ [εαυτων]{.greek-omitted} [εαυτον]{.greek-added} [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19 | instance no. 2]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ [αυτων]{.greek-omitted} [αυτον]{.greek-added} ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευουσιν]{.greek-added} εν [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [εκεινη]{.greek-added} [τη]{.greek-added} [ημεραις]{.greek-omitted} [ημερα]{.greek-added}[2:20]{.aside}

[και]{.greek-omitted} ουδεις [δε]{.greek-added} επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι [ιματιω]{.greek-omitted} [ιματτιω]{.greek-added} παλαιω ει δε μη αιρει το πληρωμα [απ]{.greek-added} αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι [απολουνται]{.greek-omitted} [απωλουνται]{.greek-added} [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον εις ασκους [καινους]{.greek-omitted} [κενους]{.greek-added} [βλητεον]{.greek-omitted} [βληταιον]{.greek-added}[2:22]{.aside}

και εγενετο [εν]{.greek-added} [τω]{.greek-added} παραπορευεσθαι αυτον εν τοις [σαβασιν]{.greek-added} [σαββασιν]{.corr} δια των [σποριμων]{.greek-omitted} [σπορημων]{.greek-added} και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω [ιδε]{.greek-omitted} [ειδε]{.greek-added} τι ποιουσιν [εν]{.greek-omitted} [οι]{.greek-added} [μαθηται]{.greek-added} [σου]{.greek-added} τοις σαββασιν ο ουκ εξεστιν[2:24]{.aside}

και [αυτοι]{.greek-added} [αυτος]{.corr} ελεγεν αυτοις ουδεποτε ανεγνωτε τι εποιησεν [δαυιδ]{.greek-abbr} οτε χρειαν εσχεν και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [αβιαθαρ]{.greek-omitted} [αρχιερεως]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [της]{.greek-omitted} [προθεσεως]{.greek-omitted} [εφαγεν]{.greek-omitted} [ους]{.greek-omitted} [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted} [φαγειν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τοις]{.greek-omitted} [ιερευσιν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [ουσιν]{.greek-omitted}[2:26]{.aside}

[πως]{.greek-omitted} εισηλθεν εις τον οικον του [θεου]{.greek-abbr} [επι]{.greek-omitted} [αβιαθαρ]{.greek-omitted} [αρχιερεως]{.greek-omitted} και τους αρτους της προθεσεως εφαγεν [επι]{.greek-added} [αβιαθαρ]{.greek-added} [του]{.greek-added} [αρχιερεως]{.greek-added} ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις [συν]{.greek-omitted} [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26 | instance no. 2]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και [παρετηρουν]{.greek-omitted} [παρετηρουντο]{.greek-added} αυτον ει τοις σαββασιν θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} [τω]{.greek-omitted} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [το]{.greek-added} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις εξεστιν τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε [εσιωπων]{.greek-omitted} [εσιωπον]{.greek-added}[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορρωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου υγιης [ωσει]{.greek-added} [ως]{.greek-omitted} [η]{.greek-omitted} αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως [μετα]{.greek-omitted} [των]{.greek-omitted} [ηρωδιανων]{.greek-omitted} [συμβουλιον]{.greek-omitted} [εποιουν]{.greek-omitted} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} [οπως]{.greek-omitted} [αυτον]{.greek-omitted} [απολεσωσιν]{.greek-omitted}[3:6]{.aside}

[και]{.greek-omitted} [εξελθοντες]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ευθεως]{.greek-omitted} μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απωλεσωσι]{.greek-added}[3:6 | instance no. 2]{.aside}

και ο [ιησους]{.greek-abbr} ανεχωρησεν μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} και περαν του ιορδανου και οι περι τυρον και [σιδωνα]{.greek-omitted} [σιδονα]{.greek-added} πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα [πλοιαριον]{.greek-omitted} [πλοιαρειον]{.greek-added} [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψοντε]{.greek-added} οσοι ειχον [μαστιγας]{.greek-omitted} [μαστηγας]{.greek-added}[3:10]{.aside}

και τα πνευματα τα ακαθαρτα οταν αυτον [εθεωρει]{.greek-omitted} [εθεορουν]{.greek-added} [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και εποιησεν δωδεκα ινα ωσιν μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και [εκβαλλειν]{.greek-omitted} [εκβαλειν]{.greek-added} τα δαιμονια[3:15]{.aside}

και επεθηκεν τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του [ζεβεδαιου]{.greek-omitted} [ζεβαιδεου]{.greek-added} και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον [αυτου]{.greek-added} του ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον [και]{.greek-omitted} βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και [σιμωνα]{.greek-omitted} [σιμονα]{.greek-added} τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχοντε]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη [δυνασθαι]{.greek-omitted} [δυνασθε]{.greek-added} αυτους [μητε]{.greek-omitted} [μειτε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι [εξεστη]{.greek-omitted} [εξεστιν]{.greek-added}[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των [δαιμονιων]{.greek-omitted} [δαιμονων]{.greek-added} [εκβαλλει]{.greek-omitted} [εκβαλει]{.greek-added} τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια [εφ]{.greek-omitted} εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν [οικια]{.greek-omitted} [οικεια]{.greek-added} εφ εαυτην μερισθη ου δυναται σταθηναι η [οικια]{.greek-omitted} [οικεια]{.greek-added} εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον [και]{.greek-omitted} [μεμερισται]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [σταθηναι]{.greek-omitted} [αλλα]{.greek-omitted} [τελος]{.greek-omitted} [εχει]{.greek-omitted}[3:26]{.aside}

και [ει]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [ανεστη]{.greek-omitted} [εφ]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [μεμερισται]{.greek-omitted} [μεμεριστε]{.greek-added} ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} σταθηναι αλλα τελος εχει[3:26 | instance no. 2]{.aside}

ουδεις [δυναται]{.greek-omitted} [δυνατε]{.greek-added} τα [σκευη]{.greek-omitted} [σκευει]{.greek-added} του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον [δηση]{.greek-omitted} [δησει]{.greek-added} και τοτε την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} αυτου [διαρπαση]{.greek-omitted} [διαρπασαι]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και [βλασφημιαι]{.greek-omitted} [βλασφημειαι]{.greek-added} οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημησει]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ [ενοχος]{.greek-omitted} [ενωχος]{.greek-added} εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον πνευμα ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και [εκαθητο]{.greek-omitted} [εκαθειτο]{.greek-added} [περι]{.greek-added} [αυτων]{.greek-added} οχλος [περι]{.greek-omitted} [αυτον]{.greek-omitted} ειπον δε αυτω [ιδου]{.greek-omitted} η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω ζητουσιν σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη [μου]{.greek-omitted} και [μητηρ]{.greek-abbr} εστιν [[εστι]{.corr}]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο [διδασ]{.greek-added} [διδασκειν]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [συνηχθη]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [ωστε]{.greek-omitted} [αυτον]{.greek-omitted} [εμβαντα]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [καθησθαι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οχλος]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ην]{.greek-omitted}[4:1]{.aside}

[κειν]{.greek-added} [και]{.greek-omitted} [παλιν]{.greek-omitted} [ηρξατο]{.greek-omitted} [διδασκειν]{.greek-omitted} παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις [το]{.greek-omitted} πλοιον [καθησθαι]{.greek-omitted} [καθεισθαι]{.greek-added} εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1 | instance no. 2]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} εν τη διδαχη αυτου[4:2]{.aside}

ακουετε [ιδου]{.greek-omitted} εξηλθεν ο [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} του σπειραι[4:3]{.aside}

και εγενετο εν τω [σπειρειν]{.greek-omitted} [σπειρην]{.greek-added} [αυτον]{.greek-added} ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και ηλθεν τα πετεινα [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν αυτο[4:4]{.aside}

[αλλο]{.greek-omitted} [αλλα]{.greek-added} δε επεσεν επι το πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο [επεσ[―]{.gap}ν]{.greek-added} [επεσεν]{.corr} [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και [συνεπνιξαν]{.greek-omitted} [συνεπνηξαν]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added} και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον [οι]{.greek-omitted} [περι]{.greek-omitted} [αυτον]{.greek-omitted} [συν]{.greek-omitted} [τοις]{.greek-omitted} [δωδεκα]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted}[4:10]{.aside}

[οτε]{.greek-omitted} [δε]{.greek-omitted} [εγενετο]{.greek-omitted} [καταμονας]{.greek-omitted} [ηρωτησαν]{.greek-omitted} [αυτον]{.greek-omitted} οι περι αυτον συν τοις δωδεκα την παραβολην[4:10 | instance no. 2]{.aside}

και ελεγεν αυτοις υμιν [δεδοται]{.greek-omitted} [δεδωται]{.greek-added} γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα [γινεται]{.greek-omitted} [δεδωται]{.greek-added}[4:11]{.aside}

ινα βλεποντες βλεπωσιν και [ου]{.greek-added} μη ιδωσιν και ακουοντες [ακουωσιν]{.greek-omitted} [ακουουσιν]{.greek-added} και μη συνιωσιν μηποτε επιστρεψωσιν [[επιστρεψωσι]{.corr}]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας [γνωσεσθε]{.greek-omitted} [γνωσεσθαι]{.greek-added}[4:13]{.aside}

ο [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} τον [λογον]{.greek-omitted} [σπορον]{.greek-added} [σπειρει]{.greek-omitted} [σπειρη]{.greek-added}[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον [σπειρωμενοι]{.greek-added} οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και [αιρει]{.greek-omitted} [ερει]{.greek-added} τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα [πετρωδη]{.greek-omitted} [πετρωδει]{.greek-added} σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχωσι]{.greek-added} [ριζαν]{.greek-omitted} [ριζας]{.greek-added} εν εαυτοις αλλα προσκαιροι [εισιν]{.greek-omitted} [εισι]{.greek-added} ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως [σκανδαλιζονται]{.greek-omitted} [κανδαλιζοντε]{.greek-added}[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας [σπειρομενοι]{.greek-omitted} [σπειρωμενοι]{.greek-added} οι τον λογον [ακουοντες]{.greek-omitted} [α]{.greek-added}[4:18]{.aside}

[και]{.greek-omitted} [ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [ακανθας]{.greek-omitted} [σπειρομενοι]{.greek-omitted} [οι]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ακουοντες]{.greek-omitted} [κουοντες]{.greek-added}[4:18 | instance no. 2]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και [αι]{.corr} περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και [παραδεχονται]{.greek-omitted} [παραδεχοντε]{.greek-added} και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη [η]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [κλινην]{.greek-omitted} ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} τι κρυπτον ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις [φανερων]{.greek-added} [φανερον]{.corr} ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω [μετρειτε]{.greek-omitted} [μετριτε]{.greek-added} [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} υμιν και προστεθησεται [υμιν]{.greek-omitted} [ημιν]{.greek-added} τοις [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added}[4:24]{.aside}

ος γαρ αν [εχη]{.greek-omitted} [εχει]{.greek-added} [δοθησεται]{.greek-omitted} [δοθησετε]{.greek-added} αυτω και ος ουκ εχει [και]{.greek-omitted} ο εχει [αρθησεται]{.greek-omitted} [αρθησετε]{.greek-added} απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [βαλει]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνειται]{.greek-added} [ως]{.greek-omitted} [ος]{.greek-added} ουκ οιδεν αυτος[4:27]{.aside}

[αυτοματη]{.greek-omitted} [αυτοματι]{.greek-added} γαρ η γη καρποφορει πρωτον [χορτον]{.greek-omitted} [χορτων]{.greek-added} ειτα σταχυν ειτα [πληρη]{.greek-omitted} [πληρης]{.greek-added} σιτον εν τω [σταχυι]{.greek-omitted} [σταχυει]{.greek-added}[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως [κοκκον]{.greek-omitted} [κοκον]{.greek-added} σιναπεως ος οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} επι της γης [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων [εστιν]{.greek-added} των σπερματων [εστιν]{.greek-omitted} των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} αναβαινει και γινεται παντων των λαχανων [μειζων]{.greek-omitted} [μειζον]{.greek-added} και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον καθως εδυναντο ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε [τοις]{.greek-omitted} [τους]{.greek-added} [μαθηταις]{.greek-omitted} [μαθητας]{.greek-added} αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης [διελθωμεν]{.greek-omitted} [διελθομεν]{.greek-added} εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε [πλοιαρια]{.greek-omitted} [πλοια]{.greek-added} ην μετ [αυτου]{.greek-omitted} [αυτων]{.greek-added}[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [ανεμου]{.greek-omitted} [μεγαλη]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [κυματα]{.greek-omitted} [επεβαλλεν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [ωστε]{.greek-omitted} [αυτο]{.greek-omitted} [ηδη]{.greek-omitted} [γεμιζεσθαι]{.greek-omitted}[4:37]{.aside}

[λελαψ]{.greek-added} [και]{.greek-omitted} [γινεται]{.greek-omitted} [λαιλαψ]{.greek-omitted} ανεμου [μεγαλη]{.greek-omitted} [μεγαλου]{.greek-added} τα δε [κυματα]{.greek-omitted} [κοιματα]{.greek-added} [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε αυτο [ηδη]{.greek-omitted} [ειδη]{.greek-added} [γεμιζεσθαι]{.greek-omitted} [γεμιζεσθε]{.greek-added}[4:37 | instance no. 2]{.aside}

και ην αυτος επι τη πρυμνη επι το [προσκεφαλαιον]{.greek-omitted} [προσκεφαλον]{.greek-added} καθευδων και διεγειρουσιν [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} αυτω [λεγοντες]{.greek-added} διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις επετιμησεν τω ανεμω και ειπεν τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [πεφημωσο]{.greek-added} και εκοπασεν ο ανεμος και εγενετο [γαληνη]{.greek-omitted} [γαλινη]{.greek-added} μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχετε [πιστιν]{.greek-omitted} [πιστην]{.greek-added}[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} οτι και [ο]{.greek-omitted} [οι]{.greek-added} [ανεμος]{.greek-omitted} [ανεμοι]{.greek-added} και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γαδαρινων]{.greek-added}[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως [απηντησεν]{.greek-omitted} [υπηντησεν]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

[ος]{.greek-omitted} [ον]{.greek-added} την κατοικησιν ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις εδυνατο αυτον [δησαι]{.greek-omitted} [δεισαι]{.greek-added}[5:3]{.aside}

[δια]{.greek-omitted} [το]{.greek-omitted} [αυτον]{.greek-omitted} [πολλακις]{.greek-omitted} [πεδαις]{.greek-omitted} [και]{.greek-omitted} [αλυσεσιν]{.greek-omitted} [δεδεσθαι]{.greek-omitted} και διεσπασθαι υπ αυτου τας αλυσεις και τας [πεδας]{.greek-omitted} [παιδας]{.greek-added} συντετριφθαι και ουδεις αυτον [ισχυεν]{.greek-omitted} [ισχυσεν]{.greek-added} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας [εν]{.greek-omitted} [τοις]{.greek-omitted} [ορεσιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [μνημασιν]{.greek-omitted} [ην]{.greek-omitted} [κραζων]{.greek-omitted} [και]{.greek-omitted} [κατακοπτων]{.greek-omitted} [εαυτον]{.greek-omitted} [λιθοις]{.greek-omitted}[5:5]{.aside}

[εν]{.greek-added} [τοις]{.greek-added} [μνημασι]{.greek-added} και [δια]{.greek-omitted} [παντος]{.greek-omitted} [νυκτος]{.greek-omitted} [και]{.greek-omitted} [ημερας]{.greek-omitted} εν τοις ορεσιν [ην]{.greek-added} [κραζον]{.greek-added} και [εν]{.greek-omitted} [τοις]{.greek-omitted} [μνημασιν]{.greek-omitted} [ην]{.greek-omitted} [κραζων]{.greek-omitted} [και]{.greek-omitted} [κατακοπτων]{.greek-omitted} [κατακοπτον]{.greek-added} εαυτον λιθοις[5:5 | instance no. 2]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν εδραμεν και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με [βασανισης]{.greek-omitted} [βασανισεις]{.greek-added}[5:7]{.aside}

ελεγεν γαρ αυτω εξελθε το [ακαθαρτον]{.greek-added} [πνευμα]{.greek-abbr} [το]{.greek-omitted} [ακαθαρτον]{.greek-omitted} εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι ονομα και απεκριθη λεγων λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει προς τω ορει αγελη [χοιρων]{.greek-omitted} [χηρων]{.greek-added} μεγαλη [βοσκομενη]{.greek-omitted} [βοσκωμενη]{.greek-added}[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους [χοιρους]{.greek-omitted} [χηρους]{.greek-added} ινα εις αυτους [εισελθωμεν]{.greek-omitted} [εισελθομεν]{.greek-added}[5:12]{.aside}

και [επετρεψεν]{.greek-omitted} [απετρεψεν]{.greek-added} αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα πνευματα τα ακαθαρτα εισηλθον εις τους [χοιρους]{.greek-omitted} [χηρους]{.greek-added} και [ωρμησεν]{.greek-omitted} [ορμησεν]{.greek-added} η [αγελη]{.greek-omitted} [αγελει]{.greek-added} κατα του [κριμου]{.greek-added} [κρημνου]{.greek-omitted} [[κριμνου]{.corr}]{.greek-added} εις την θαλασσαν ησαν δε ως [δισχιλιοι]{.greek-omitted} [διαχιλιοι]{.greek-added} και [επνιγοντο]{.greek-omitted} [επνηγοντο]{.greek-added} εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους [χ[η]{.unclear}ρους]{.greek-added} [χοιρους]{.corr} εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και [εις]{.greek-omitted} [τους]{.greek-omitted} [αγρους]{.greek-omitted} [και]{.greek-omitted} [εξηλθον]{.greek-omitted} [ιδειν]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [γεγονος]{.greek-omitted}[5:14]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [βοσκοντες]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [εφυγον]{.greek-omitted} [και]{.greek-omitted} [ανηγγειλαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} εις τους αγρους και εξηλθον ιδειν τι εστιν το [γεγονος]{.greek-omitted} [γεγονως]{.greek-added}[5:14 | instance no. 2]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεορουσιν]{.greek-added} τον δαιμονιζομενον [καθημενον]{.greek-omitted} [και]{.greek-omitted} ιματισμενον και [σωφρονουντα]{.greek-omitted} [σοφρονουντα]{.greek-added} τον [εσχηκοτα]{.greek-omitted} [εσχικωτα]{.greek-added} τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

διηγησαντο δε αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν [αυτον]{.greek-omitted} [αυτων]{.greek-added} απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} [ει]{.greek-added} μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} πεποιηκεν και ηλεησεν σε[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη [δεκαπολει]{.greek-omitted} [δεκαπολη]{.greek-added} οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται [εις]{.greek-omitted} [τις]{.greek-added} των αρχισυναγωγων ονοματι [ιαριος]{.greek-added} [ιαειρος]{.greek-omitted} [[ιαιρος]{.corr}]{.greek-added} και ιδων [αυτον]{.greek-omitted} [αυτων]{.greek-added} πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων [οτι]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [μου]{.greek-omitted} [εσχατως]{.greek-omitted} [εχει]{.greek-omitted} [ινα]{.greek-omitted} [ελθων]{.greek-omitted} [επιθης]{.greek-omitted} [αυτη]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [οπως]{.greek-omitted} [σωθη]{.greek-omitted} [και]{.greek-omitted} [ζησεται]{.greek-omitted}[5:23]{.aside}

[και]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [πολλα]{.greek-omitted} [λεγων]{.greek-omitted} οτι το θυγατριον μου [εσχατως]{.greek-omitted} [εσχατων]{.greek-added} εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23 | instance no. 2]{.aside}

και απηλθεν μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος [ετη]{.greek-omitted} [ετι]{.greek-added} δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

ελεγεν γαρ οτι καν των ιματιων αυτου [αψωμαι]{.greek-omitted} [αψομαι]{.greek-added} [σωθησομαι]{.greek-omitted} [σωθησωμαι]{.greek-added}[5:28]{.aside}

και ευθεως εξηρανθη η [πηγη]{.greek-omitted} [πιγη]{.greek-added} του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν [επιστραφεις]{.greek-omitted} [επιστραφης]{.greek-added} εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα [ειδυια]{.greek-omitted} [ιδυια]{.greek-added} ο [γε]{.greek-added} [γεγονεν]{.greek-omitted} [επ]{.greek-omitted} [αυτη]{.greek-omitted} [ηλθεν]{.greek-omitted} [και]{.greek-omitted} [προσεπεσεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [πασαν]{.greek-omitted} [την]{.greek-omitted} [αληθειαν]{.greek-omitted}[5:33]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [γυνη]{.greek-omitted} [φοβηθεισα]{.greek-omitted} [και]{.greek-omitted} [τρεμουσα]{.greek-omitted} [ειδυια]{.greek-omitted} [ο]{.greek-omitted} [γεγονεν]{.greek-omitted} [γονεν]{.greek-added} επ αυτη ηλθεν και [προσεπετεν]{.greek-added} [προσεπεσεν]{.corr} αυτω και ειπεν αυτω πασαν την αληθειαν[5:33 | instance no. 2]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου σεσωκεν σε υπαγε εις ειρηνην και [ισθι]{.greek-omitted} [ισθη]{.greek-added} υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} απο του [αρχισυναγωγου]{.greek-omitted} [αρχησυναγωγου]{.greek-added} λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλης]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω [αρχισυναγωγω]{.greek-omitted} [αρχησυναγωγω]{.greek-added} μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν [ουδ[υν]{.unclear}]{.greek-added} [ουδενα]{.corr} αυτω συνακολουθησαι ει [μη]{.greek-omitted} [μι]{.greek-added} πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του [αρχισυναγωγου]{.greek-omitted} [αρχησυναγωγου]{.greek-added} και [θεωρει]{.greek-omitted} [θεορει]{.greek-added} θορυβον κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και κλαιετε το παιδιον ουκ απεθανεν αλλα [καθευδει]{.greek-omitted} [καθευδη]{.greek-added}[5:39]{.aside}

και [κατεγελων]{.greek-omitted} [κατεγελουν]{.greek-added} αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της [χειρος]{.greek-omitted} [του]{.greek-omitted} [παιδιου]{.greek-omitted} [λεγει]{.greek-omitted} [αυτη]{.greek-omitted} [ταλιθα]{.greek-omitted} [κουμι]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [μεθερμηνευομενον]{.greek-omitted} [το]{.greek-omitted} [κορασιον]{.greek-omitted} [σοι]{.greek-omitted} [λεγω]{.greek-omitted} [εγειραι]{.greek-omitted}[5:41]{.aside}

[και]{.greek-omitted} [κρατησας]{.greek-omitted} [της]{.greek-omitted} χειρος του παιδιου λεγει αυτη ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον [σοι]{.greek-omitted} [συ]{.greek-added} λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41 | instance no. 2]{.aside}

και ευθεως ανεστη το κορασιον και [περιεπατει]{.greek-omitted} [περιεπατη]{.greek-added} ην γαρ ετων δωδεκα και εξεστησαν [εκστασει]{.greek-omitted} [εκστασε]{.greek-added} μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και ειπεν δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την πατριδα αυτου και ακολουθουσιν αυτω οι [μαθηται]{.greek-omitted} [μαθητε]{.greek-added} αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτα και τις η σοφια η δοθεισα αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο τεκτων ο υιος μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν [αυτω]{.greek-omitted} [εαυτω]{.greek-added}[6:3]{.aside}

ελεγεν δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ εστιν προφητης ατιμος ει [μη]{.greek-omitted} [μι]{.greek-added} εν τη [πατριδι]{.greek-omitted} [πατριδη]{.greek-added} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συνγγενεσιν]{.greek-added} και εν τη [οικια]{.greek-omitted} [οικεια]{.greek-added} αυτου[6:4]{.aside}

και ουκ [ηδυ]{.greek-added} [ηδυνατο]{.greek-omitted} [εκει]{.greek-omitted} [ουδεμιαν]{.greek-omitted} [δυναμιν]{.greek-omitted} [ποιησαι]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ολιγοις]{.greek-omitted} [αρρωστοις]{.greek-omitted} [επιθεις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [εθεραπευσεν]{.greek-omitted}[6:5]{.aside}

[νατο]{.greek-added} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνατο]{.greek-omitted} εκει ουδεμιαν δυναμιν ποιησαι ει [μη]{.greek-omitted} [μι]{.greek-added} [ολιγοις]{.greek-omitted} [ολιγους]{.greek-added} [αρρωστοις]{.greek-omitted} [αρρωστους]{.greek-added} επιθεις τας χειρας εθεραπευσεν[6:5 | instance no. 2]{.aside}

και εθαυμαζεν δια την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και περιηγεν τας κωμας κυκλω διδασκων[6:6]{.aside}

και [προσκαλειται]{.greek-omitted} [προσκαλεσαμενος]{.greek-added} τους δωδεκα [και]{.greek-omitted} [μαθητας]{.greek-added} ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν [των]{.greek-omitted} [κατα]{.greek-added} πνευματων [των]{.greek-omitted} ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν [αιρωσιν]{.greek-omitted} [ερωσιν]{.greek-added} εις οδον ει [μη]{.greek-omitted} [μι]{.greek-added} ραβδον μονον μη [πηραν]{.greek-omitted} [πειραν]{.greek-added} μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσεισθε]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθητε εις [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} εκει μενετε εως αν [εξελθητε]{.greek-omitted} [εξελθειτε]{.greek-added} εκειθεν[6:10]{.aside}

και οσοι αν μη [δεξωνται]{.greek-omitted} [δεξοντε]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται σοδομοις η γομορροις εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα μετανοησωσιν[6:12]{.aside}

και δαιμονια πολλα [εξε]{.greek-added} [εξεβαλλον]{.greek-omitted} [και]{.greek-omitted} [ηλειφον]{.greek-omitted} [ελαιω]{.greek-omitted} [πολλους]{.greek-omitted} [αρρωστους]{.greek-omitted} [και]{.greek-omitted} [εθεραπευον]{.greek-omitted}[6:13]{.aside}

[βαλον]{.greek-added} και [ειλιφον]{.greek-added} [δαιμονια]{.greek-omitted} [πολλα]{.greek-omitted} [εξεβαλλον]{.greek-omitted} [και]{.greek-omitted} [ηλειφον]{.greek-omitted} ελαιω πολλους αρρωστους και εθεραπευον[6:13 | instance no. 2]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

[αλλοις]{.greek-added} [ελεγ[―]{.gap}ν]{.greek-added} [αλλοι]{.corr} [ελεγον]{.greek-omitted} [οτι]{.greek-omitted} [ηλιας]{.greek-omitted} [εστιν]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [ελεγον]{.corr} οτι [προφητης]{.corr} εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης [αποστειλας]{.greek-added} ειπεν οτι ον εγω απεκεφαλισα ιωαννην ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης [αποστηλας]{.greek-added} [αποστειλας]{.corr} [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και εδησεν αυτον εν [φυλακη]{.greek-omitted} [φυλακι]{.greek-added} δια ηρωδιαδα [φ]{.greek-added} την γυναικα φιλιππου του αδελφου αυτου οτι αυτην [εγαμησεν]{.greek-omitted} [εγαμησε]{.greek-added}[6:17]{.aside}

ελεγεν γαρ ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας [ενειχεν]{.greek-omitted} [ενηχεν]{.greek-added} αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητω]{.greek-added} τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και [συνετηρει]{.greek-omitted} [συνετειρη]{.greek-added} αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας [ευ]{.greek-added} [ευκαιρου]{.greek-omitted} [οτε]{.greek-omitted} [ηρωδης]{.greek-omitted} [τοις]{.greek-omitted} [γενεσιοις]{.greek-omitted} [αυτου]{.greek-omitted} [δειπνον]{.greek-omitted} [εποιει]{.greek-omitted} [τοις]{.greek-omitted} [μεγιστασιν]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [χιλιαρχοις]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [πρωτοις]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted}[6:21]{.aside}

[και]{.greek-omitted} [γενομενης]{.greek-omitted} [ημερας]{.greek-omitted} [ευκαιρου]{.greek-omitted} [καιρου]{.greek-added} οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει [και]{.greek-added} [ηδεως]{.greek-added} [αυτου]{.greek-added} [ηκου[ε]{.unclear}ν]{.greek-added} [[η]{.unclear}μερας]{.greek-added} τοις μεγιστασιν αυτου και τοις [χιλιαρχοις]{.greek-omitted} [χειλιαρχοις]{.greek-added} και τοις πρωτοις της γαλιλαιας[6:21 | instance no. 2]{.aside}

και [εισελθουσης]{.greek-omitted} [εισελθουσεις]{.greek-added} της θυγατρος αυτης της ηρωδιαδος και [ορχησαμενης]{.greek-omitted} [ορχισαμενης]{.greek-added} και [αρεσασης]{.greek-omitted} [αρεσασεις]{.greek-added} τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω [αιτησον]{.greek-omitted} [αιτισον]{.greek-added} [με]{.greek-omitted} [μοι]{.greek-added} ο εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη [οτι]{.greek-omitted} ο εαν με [αιτησης]{.greek-omitted} [αιτησεις]{.greek-added} δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι [αιτησομαι]{.greek-omitted} [αιτισωμε]{.greek-added} η δε ειπεν την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα [ητησατο]{.greek-omitted} [ητισατο]{.greek-added} λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλ[ε]{.unclear}υς δια τους ορκους και τους συνανακειμενους ουκ [ηθελησεν]{.greek-omitted} [ηθελεν]{.greek-added} αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added}[6:27]{.aside}

[απεκεφαλησεν]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [αποστειλας]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [σπεκουλατορα]{.greek-omitted} [επεταξεν]{.greek-omitted} [ενεχθηναι]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [αυτου]{.greek-omitted} [αυτον]{.greek-added}[6:27 | instance no. 2]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και [συναγονται]{.greek-omitted} [συναγοντε]{.greek-added} οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και αναπαυεσθε ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν [ευκ[ι]{.unclear}]{.greek-added} [ευκαιρουν]{.corr}[6:31]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ιδεν]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι [ησαν]{.greek-omitted} [εισαν]{.greek-added} ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και [ηδη]{.greek-omitted} [ειδη]{.greek-added} ωρας πολλης [γενομενης]{.greek-omitted} [γεναμενης]{.greek-added} προσελθοντες αυτω [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οτι]{.greek-omitted} [ερημος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [τοπος]{.greek-omitted} [και]{.greek-omitted} [ηδη]{.greek-omitted} [ωρα]{.greek-omitted} [πολλη]{.greek-omitted}[6:35]{.aside}

[και]{.greek-omitted} [ηδη]{.greek-omitted} [ωρας]{.greek-omitted} [πολλης]{.greek-omitted} [γενομενης]{.greek-omitted} [προσελθοντες]{.greek-omitted} [αυτω]{.greek-omitted} οι μαθηται αυτου λεγουσιν οτι ερημος εστιν ο τοπος και [ηδη]{.greek-omitted} [ειδη]{.greek-added} ωρα πολλη[6:35 | instance no. 2]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους [και]{.greek-omitted} [κωμας]{.greek-omitted} [κομας]{.greek-added} [αγορασωσιν]{.greek-omitted} [αγιασωσιν]{.greek-added} εαυτοις αρτους τι γαρ φαγωσιν ουκ [εχουσιν]{.greek-omitted} [εχωσιν]{.greek-added}[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν δηναριων [δινκοσιων]{.greek-added} [διακοσιων]{.corr} αρτους [και]{.greek-omitted} [δωμεν]{.greek-omitted} [αυτοις]{.greek-omitted} [φαγειν]{.greek-omitted}[6:37]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ποσους]{.greek-omitted} [αρτους]{.greek-omitted} εχετε υπαγετε και ιδετε και [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} [ανακλιναι]{.greek-omitted} [ανακληναι]{.greek-added} παντας [συμποσια]{.greek-omitted} συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και ανεπεσον [ανα]{.greek-added} πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ηυλογησεν]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} πασιν[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα [κοφινους]{.greek-omitted} [κωφινους]{.greek-added} [πληρεις]{.greek-omitted} [πληρης]{.greek-added} και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους [πεντακισχιλιοι]{.greek-omitted} [πεντακισχιλι]{.greek-added} [ανδρες]{.greek-omitted}[6:44]{.aside}

[και]{.greek-omitted} [ησαν]{.greek-omitted} οι [φαγοντες]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [πεντακισχιλιοι]{.greek-omitted} ανδρες[6:44 | instance no. 2]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηνεγκασεν]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν [αυτον]{.greek-added} εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βιθσαιδαν]{.greek-added} εως [ου]{.greek-added} αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος [προσευξασθαι]{.greek-omitted} [προσευξασθε]{.greek-added}[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος [ην]{.greek-added} επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις [φοδρα]{.greek-added} [[σφοδρα]{.corr}]{.greek-added} και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον [περιπατουντα]{.greek-omitted} επι της θαλασσης [περιπατουντα]{.greek-added} εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον [ειδον]{.greek-omitted} [ιδον]{.greek-added} και εταραχθησαν και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτον]{.greek-added} [πεπωρωμενη]{.greek-omitted} [πεπορωμενη]{.greek-added}[6:52]{.aside}

και διαπερασαντες ηλθον επι την [γην]{.greek-omitted} [γεννησαρετ]{.greek-omitted} [και]{.greek-omitted} [προσωρμισθησαν]{.greek-omitted}[6:53]{.aside}

[γην]{.greek-added} [γενισαρετ]{.greek-added} και [διαπερασαντες]{.greek-omitted} [ηλθον]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [γεννησαρετ]{.greek-omitted} [και]{.greek-omitted} [προσωρμισθησαν]{.greek-omitted} [προσορμισθησαν]{.greek-added}[6:53 | instance no. 2]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον [οι]{.greek-added} [ανδρες]{.greek-added} [του]{.greek-added} [τοπου]{.greek-added} [εκεινου]{.greek-added}[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις [φερειν]{.greek-added} [παντας]{.greek-added} τους κακως εχοντας [περιφερειν]{.greek-omitted} [περιεφερον]{.greek-added} [γαρ]{.greek-added} [αυτους]{.greek-added} οπου [αν]{.greek-added} [ηκουον]{.greek-omitted} [ηκουσαν]{.greek-added} [οτι]{.greek-omitted} [εκει]{.greek-omitted} [εστιν]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου [αυτου]{.greek-omitted} [αψωνται]{.greek-omitted} [αυτων]{.greek-added} [αψοντε]{.greek-added} και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και [συναγονται]{.greek-omitted} [συναγοντε]{.greek-added} προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου [κοιναις]{.greek-omitted} [κοινες]{.greek-added} [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν [ανιπτοις]{.greek-omitted} [ανηπτοις]{.greek-added} [εσθιοντας]{.greek-omitted} [εσθιοντες]{.greek-added} [τους]{.greek-added} αρτους [εμεμψαντο]{.greek-omitted} [εμεψαντο]{.greek-added}[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη [νιψωνται]{.greek-omitted} [νιψοντε]{.greek-added} τας χειρας ουκ εσθιουσιν κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και απο αγορας [δε]{.greek-added} [οταν]{.greek-added} [εισελθωσιν]{.greek-added} εαν μη [βαπτισωνται]{.greek-omitted} [βαπτισοντε]{.greek-added} ουκ εσθιουσιν και αλλα [πολλα]{.greek-omitted} [εστιν]{.greek-omitted} [α]{.greek-omitted} [παρελαβον]{.greek-omitted} [κρατειν]{.greek-omitted} [βαπτισμους]{.greek-omitted} [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [χαλκιων]{.greek-omitted} [και]{.greek-omitted} [κλινων]{.greek-omitted}[7:4]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [αγορας]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [βαπτισωνται]{.greek-omitted} [ουκ]{.greek-omitted} [εσθιουσιν]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4 | instance no. 2]{.aside}

[επι]{.greek-added} [επειτα]{.corr} επερωτωσιν αυτον οι φαρισαιοι και [οι]{.greek-omitted} [αι]{.greek-added} γραμματεις [λεγοντες]{.greek-added} δια τι οι μαθηται σου ου περιπατουσιν κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων αλλα ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως [γεγραπται]{.greek-omitted} [γαιγραπται]{.greek-added} ουτος ο λαος τοις χειλεσιν με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα [παρομοια]{.greek-omitted} [παρομια]{.greek-added} τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων [τηρησητε]{.greek-omitted} [τυρησειτε]{.greek-added}[7:9]{.aside}

μωσης γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω [τελευτατω]{.greek-omitted} [τελευτατα]{.greek-added}[7:10]{.aside}

υμεις δε λεγετε εαν [ειπη]{.greek-omitted} [ειπει]{.greek-added} [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο εστιν δωρον [ο]{.greek-omitted} [εαν]{.greek-omitted} [εξ]{.greek-omitted} [εμου]{.greek-omitted} [ωφεληθης]{.greek-omitted}[7:11]{.aside}

[υμεις]{.greek-omitted} [δε]{.greek-omitted} [λεγετε]{.greek-omitted} [εαν]{.greek-omitted} [ειπη]{.greek-omitted} [ανθρωπος]{.greek-omitted} [τω]{.greek-omitted} [πατρι]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [μητρι]{.greek-omitted} [κορβαν]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [δωρον]{.greek-omitted} ο εαν εξ εμου [ωφεληθης]{.greek-omitted} [ωφεληθεις]{.greek-added}[7:11 | instance no. 2]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωσει]{.greek-added} υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον [ο]{.greek-omitted} [ου]{.greek-added} [δυναται]{.greek-omitted} [δυνατε]{.greek-added} αυτον [κοινωσαι]{.greek-omitted} [κοινωσε]{.greek-added} αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα [κοινουντα]{.greek-omitted} [κεινουντα]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε [εισηλθεν]{.greek-omitted} [εισηλθον]{.greek-added} εις οικον απο του οχλου επηρωτων αυτον οι [μαθηται]{.greek-omitted} [μαθητε]{.greek-added} αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε [ου]{.greek-omitted} [ουπω]{.greek-added} νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφ[ε]{.unclear}δρωνα [εκπορευεται]{.greek-omitted} [[αφαιδρωνα]{.corr}]{.greek-added} [εκβαλλεται]{.greek-added} [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα [τα]{.greek-omitted} βρωματα[7:19]{.aside}

ελεγεν δε οτι το [εκ]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} εκπορευομενον εκεινο [κοινοι]{.greek-omitted} [κεινη]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ [της]{.greek-omitted} [καρδιας]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [οι]{.greek-omitted} [διαλογισμοι]{.greek-omitted} [οι]{.greek-omitted} [κακοι]{.greek-omitted} [εκπορευονται]{.greek-omitted} [μοιχειαι]{.greek-omitted} [πορνειαι]{.greek-omitted} [φονοι]{.greek-omitted}[7:21]{.aside}

[εσωθεν]{.greek-omitted} [γαρ]{.greek-omitted} [εκ]{.greek-omitted} της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι [καλοι]{.greek-added} [κακοι]{.corr} εκπορευονται [μοιχειαι]{.greek-omitted} [μοιχιαι]{.greek-added} πορνειαι φονοι [κλοπαι]{.greek-added}[7:21 | instance no. 2]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος [ασελγεια]{.greek-omitted} [ασελγια]{.greek-added} οφθαλμος πονηρος βλασφημια [υπερηφανια]{.greek-omitted} [υπερηφανεια]{.greek-added} αφροσυνη[7:22]{.aside}

[ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} τα πονηρα εσωθεν [εκπορευεται]{.greek-omitted} [εκπορευετε]{.greek-added} και [κοινοι]{.greek-omitted} [κεινη]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και [εκει]{.greek-added} [εκειθεν]{.corr} αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} ουδενα [ηθελεν]{.greek-omitted} [ηθελησεν]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης ειχεν το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα προσεπεσεν προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη [ελληνις]{.greek-omitted} [ελληνης]{.greek-added} [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικησσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλλει]{.greek-added} εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη [και]{.greek-omitted} [λεγει]{.greek-omitted} αυτω [λεγουσα]{.greek-added} ναι [κυριε]{.greek-abbr} και γαρ τα [κυναρια]{.greek-omitted} [κοιναρια]{.greek-added} υποκατω της τραπεζης [εσθιει]{.greek-omitted} [εσθιουσιν]{.greek-added} απο των [ψιχιων]{.greek-omitted} [ψυχιων]{.greek-added} [των]{.greek-added} [πιπτοντων]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [τραπεζης]{.greek-added} των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον [υπαγε]{.greek-omitted} [εξεληλυθεν]{.greek-omitted} [το]{.greek-omitted} [δαιμονιον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [θυγατρος]{.greek-omitted} [σου]{.greek-omitted}[7:29]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} [δια]{.greek-omitted} [τουτον]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29 | instance no. 2]{.aside}

και απελθουσα εις τον οικον αυτης ευρεν το δαιμονιον [εξεληλυθος]{.greek-omitted} [εξεληλυθως]{.greek-added} και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

[και]{.greek-added} και παλιν εξελθων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εκ των οριων τυρου και σιδωνος ηλθεν προς την θαλασσαν της γαλιλαιας ανα [μεσον]{.greek-omitted} [μεσων]{.greek-added} των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω [κοφων]{.greek-added} [κωφον]{.greek-omitted} [[κοφον]{.corr}]{.greek-added} μογγιλαλον και παρακαλουσιν [αυτον]{.greek-omitted} ινα [επιθη]{.greek-omitted} [επιθει]{.greek-added} αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν εβαλεν τους δακτυλους αυτου εις τα [ωτα]{.greek-omitted} [ωματα]{.greek-added} αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} εστεναξεν και λεγει αυτω εφφαθα ο εστιν διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ορθως [ωστε]{.greek-added} [παντας]{.greek-added} [εξιστασθαι]{.greek-added}[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε [αυτος]{.greek-omitted} αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως [εξεπλησσοντο]{.greek-omitted} [εξεπληττοντο]{.greek-added} λεγοντες καλως παντα πεποιηκεν [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} και τους κωφους ποιει [ακουειν]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [αλαλους]{.greek-omitted} [λαλειν]{.greek-omitted}[7:37]{.aside}

[και]{.greek-omitted} [υπερπερισσως]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [καλως]{.greek-omitted} [παντα]{.greek-omitted} [πεποιηκεν]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [κωφους]{.greek-omitted} [ποιει]{.greek-omitted} ακουειν και τους αλαλους λαλειν[7:37 | instance no. 2]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παλιν]{.greek-added} [παμπολλου]{.greek-omitted} [πανπολλου]{.greek-added} οχλου [οντος]{.greek-omitted} [οντως]{.greek-added} και μη εχοντων τι φαγωσιν προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενωσιν]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχωσιν]{.greek-added} τι φαγωσιν[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις [τον]{.greek-added} οικον αυτων [εκλυθησονται]{.greek-omitted} [εκλυθησοντε]{.greek-added} εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκασιν]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους [δυνησεται]{.greek-omitted} [δυνησετε]{.greek-added} τις ωδε χορτασαι [αρτων]{.greek-omitted} [αρτον]{.greek-added} επ ερημιας[8:4]{.aside}

και επηρωτα αυτους [λεγων]{.greek-added} ποσους [εχετε]{.greek-omitted} αρτους [εχεται]{.greek-added} οι δε ειπον επτα[8:5]{.aside}

και παρηγγειλεν τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας εκλασεν [[εκλασε]{.corr}]{.greek-added} και [εδιδου]{.greek-omitted} [εδυδου]{.greek-added} τοις μαθηταις αυτου ινα παραθωσιν και παρεθηκαν τω οχλω[8:6]{.aside}

και [ειχον]{.greek-omitted} [ηχον]{.greek-added} ιχθυδια ολιγα και [ευλογησας]{.greek-omitted} [ευχαριστησας]{.greek-added} ειπεν [παραθειναι]{.greek-omitted} και αυτα [παρατεθηναι]{.greek-added}[8:7]{.aside}

εφαγον δε και εχορτασθησαν [παντες]{.greek-added} και ηραν [το]{.greek-added} [περισσευματα]{.greek-omitted} [περισσευμα]{.greek-added} [των]{.greek-added} κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν [αυτους]{.greek-omitted}[8:9]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [φαγοντες]{.greek-omitted} [ως]{.greek-omitted} [τετρακισχιλιοι]{.greek-omitted} [και]{.greek-omitted} [απελυσεν]{.greek-omitted} αυτους[8:9 | instance no. 2]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις [το]{.greek-omitted} πλοιον μετα των μαθητων αυτου ηλθεν εις τα [μερη]{.greek-omitted} [μερει]{.greek-added} δαλμανουθα[8:10]{.aside}

και [εξηλθον]{.greek-omitted} [εξηλθαν]{.greek-added} οι φαρισαιοι και ηρξαντο [συζητειν]{.greek-omitted} [συνζητειν]{.greek-added} αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει [τη]{.greek-added} [τι]{.corr} η [γενεα]{.greek-omitted} [γεναια]{.greek-added} αυτη σημειον επιζητει αμην λεγω υμιν [ει]{.greek-omitted} [η]{.greek-added} [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} τη [γενεα]{.greek-omitted} [γεναια]{.greek-added} ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει [μη]{.greek-omitted} [μι]{.greek-added} ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added}[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε [εν]{.greek-added} [ταις]{.greek-added} [καρδιαις]{.greek-added} [υμων]{.greek-added} [ολιγοπιστοι]{.greek-added} οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε [ετι]{.greek-omitted} [οτι]{.greek-added} [πεπωρωμενην]{.greek-omitted} [πεπορωμενην]{.greek-added} εχετε την καρδιαν υμων[8:17]{.aside}

[ο[θ]{.unclear}]{.greek-added} [οφθαλμους]{.corr} εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους [πεντακισ]{.greek-added} [πεντακισχιλιους]{.greek-omitted} [ποσους]{.greek-omitted} [κοφινους]{.greek-omitted} [πληρεις]{.greek-omitted} [κλασματων]{.greek-omitted} [ηρατε]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δωδεκα]{.greek-omitted}[8:19]{.aside}

[χηλιους]{.greek-added} [οτε]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [εκλασα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [πεντακισχιλιους]{.greek-omitted} ποσους [κοφινους]{.greek-omitted} [κωφινους]{.greek-added} [πληρεις]{.greek-omitted} [πληρης]{.greek-added} κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19 | instance no. 2]{.aside}

οτε δε τους επτα εις τους [τετρακισχιλιους]{.greek-omitted} [τετρακισχηλιους]{.greek-added} ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως [ου]{.greek-omitted} [ουπω]{.greek-added} συνιετε[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βιθσαιδαν]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα [αυτου]{.greek-omitted} [αυτον]{.greek-added} [αψηται]{.greek-omitted} [αψητε]{.greek-added}[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω [επηρωτα]{.greek-omitted} [επειρωτα]{.greek-added} αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} [οτι]{.greek-omitted} ως δενδρα [ορω]{.greek-omitted} περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψεν]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην [εισελθης]{.greek-omitted} [εισελθεις]{.greek-added} μηδε [ειπης]{.greek-omitted} [ειπεις]{.greek-added} τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} τους μαθητας αυτου [λεγων]{.greek-omitted} [αυτοις]{.greek-omitted} [τινα]{.greek-omitted} [με]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} [ειναι]{.greek-omitted}[8:27]{.aside}

[και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [κωμας]{.greek-omitted} [καισαρειας]{.greek-omitted} [της]{.greek-omitted} [φιλιππου]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [επηρωτα]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27 | instance no. 2]{.aside}

οι δε απεκριθησαν ιωαννην [τον]{.greek-omitted} [τ[η]{.unclear}ν]{.greek-added} βαπτιστην [και]{.greek-omitted} [αλλοι]{.greek-omitted} [ηλιαν]{.greek-omitted} αλλοι δε [ηλιαν]{.greek-added} [ετεροι]{.greek-added} [δε]{.greek-added} [ιερεμιαν]{.greek-added} [η]{.greek-added} ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι [αποκριθεις]{.greek-omitted} [ποκριθεις]{.greek-added} δε ο πετρος λεγει [αυτω]{.greek-omitted} συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι λεγωσιν περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι [δει]{.greek-omitted} [δη]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και των αρχιερεων [και]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου επετιμησεν τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν [απαρνησασθω]{.greek-omitted} [απαρνισασθω]{.greek-added} εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθη]{.greek-added} [ακολουθειτω]{.greek-omitted} [μοι]{.greek-omitted}[8:34]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [συν]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [οστις]{.greek-omitted} [θελει]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [ακολουθειν]{.greek-omitted} [απαρνησασθω]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [αρατω]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ακολουθειτω]{.greek-omitted} μοι[8:34 | instance no. 2]{.aside}

ος γαρ αν [θελη]{.greek-omitted} [θελει]{.greek-added} την ψυχην αυτου [σωσαι]{.greek-omitted} [σωσε]{.greek-added} απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απωλεσει]{.greek-added} την [εαυτου]{.greek-omitted} ψυχην [αυτου]{.greek-added} ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} [ουτως]{.greek-added} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-omitted} [ανθρωπος]{.greek-added} εαν [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ εαν επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη [μοιχαλιδι]{.greek-omitted} [μοιχαλιδη]{.greek-added} και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι εισιν τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσοντε]{.greek-added} θανατου εως αν ιδωσιν την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και [εν]{.greek-added} [τω]{.greek-added} [προσευχεσθαι]{.greek-added} [αυτον]{.greek-added} μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν ως χιων οια γναφευς επι της γης ου δυναται [λευκαναι]{.greek-omitted} [ουτως]{.greek-added}[9:3]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτου]{.greek-omitted} [εγενοντο]{.greek-omitted} [στιλβοντα]{.greek-omitted} [λευκα]{.greek-omitted} [λιαν]{.greek-omitted} [ως]{.greek-omitted} [χιων]{.greek-omitted} [οια]{.greek-omitted} [γναφευς]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} λευκαναι[9:3 | instance no. 2]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν [συλλαλουντες]{.greek-omitted} [συνλαλουντες]{.greek-added} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} [ραββι]{.greek-omitted} [ραββη]{.greek-added} καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις [σοι]{.greek-omitted} [συ]{.greek-added} μιαν και μωση μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ [ηδει]{.greek-omitted} [ειδη]{.greek-added} τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και ηλθεν φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα [ειδον]{.greek-omitted} [ιδων]{.greek-added} αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} [διηγησοντε]{.greek-added} α [ειδον]{.greek-omitted} [ιδων]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους [συζητουντες]{.greek-omitted} [συνζητουντες]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν [δει]{.greek-omitted} [δη]{.greek-added} ελθειν πρωτον[9:11]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ηλιας]{.greek-omitted} [μεν]{.greek-omitted} [ελθων]{.greek-omitted} [πρωτον]{.greek-omitted} αποκαθιστα παντα [καθως]{.greek-added} [και]{.greek-omitted} [πως]{.greek-omitted} [γεγραπται]{.greek-omitted} [γαιγραπται]{.greek-added} επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι [και]{.greek-omitted} ηλιας εληλυθεν και εποιησαν αυτω οσα [ηθε]{.greek-added} [ηθελησαν]{.greek-omitted} [καθως]{.greek-omitted} [γεγραπται]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted}[9:13]{.aside}

[αλλα]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [ηλιας]{.greek-omitted} [εληλυθεν]{.greek-omitted} [και]{.greek-omitted} [εποιησαν]{.greek-omitted} [αυτω]{.greek-omitted} [οσα]{.greek-omitted} [ηθελησαν]{.greek-omitted} [λησαν]{.greek-added} καθως γεγραπται επ αυτον[9:13 | instance no. 2]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [πολυν]{.greek-added} οχλον [πολυν]{.greek-omitted} περι αυτους και γραμματεις [συζητουντας]{.greek-omitted} [συνζητουντας]{.greek-added} αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και επηρωτησεν τους γραμματεις τι [συζητειτε]{.greek-omitted} [συνζητειτε]{.greek-added} προς [αυτους]{.greek-omitted} [αλληλους]{.greek-added}[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν [διδασκαλε]{.greek-omitted} [ηνεγκα]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [μου]{.greek-omitted} [προς]{.greek-omitted} [σε]{.greek-omitted} [εχοντα]{.greek-omitted} [πνευμα]{.greek-omitted} [αλαλον]{.greek-omitted}[9:17]{.aside}

[τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [προσηλθεν]{.greek-added} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [γονυπετων]{.greek-added} [αυτου]{.greek-added} και [λεγον]{.greek-added} [αποκριθεις]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οχλου]{.greek-omitted} [ειπεν]{.greek-omitted} διδασκαλε ηνεγκα τον υιον μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17 | instance no. 2]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα [αυτο]{.greek-omitted} [αυτω]{.greek-added} εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

[και]{.greek-added} [αποκριθεις]{.greek-added} ο [[ιησους]{.greek-abbr}]{.greek-added} [ειπεν]{.greek-added} [αυτοις]{.greek-added} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} ω γεν[ε]{.unclear}α [[γεναια]{.corr}]{.greek-added} απιστος εως ποτε [εσωμε]{.greek-added} προς υμας [εσομαι]{.greek-omitted} εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και επηρωτησεν τον [πατερα]{.greek-abbr} αυτου ποσος χρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} ως τουτο γεγονεν αυτω [ο]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [παιδιοθεν]{.greek-omitted}[9:21]{.aside}

[και]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [ποσος]{.greek-omitted} [χρονος]{.greek-omitted} [εστιν]{.greek-omitted} [ως]{.greek-omitted} [τουτο]{.greek-omitted} [γεγονεν]{.greek-omitted} [αυτω]{.greek-omitted} ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παιδιοθεν]{.greek-omitted} [παιδιωθεν]{.greek-added}[9:21 | instance no. 2]{.aside}

και πολλακις αυτον και εις το πυρ εβαλεν και εις υδατα ινα [απολεση]{.greek-omitted} [απωλεσει]{.greek-added} αυτον αλλ [ει]{.greek-omitted} [η]{.greek-added} τι [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [το]{.greek-omitted} ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη [απιστια]{.greek-omitted} [απιστεια]{.greek-added}[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [συντρεχει]{.greek-added} [ο]{.greek-added} οχλος επετιμησεν τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι [εισελθης]{.greek-omitted} [εισελθεις]{.greek-added} εις αυτον[9:25]{.aside}

και κραξαν και [πολλα]{.greek-omitted} σπαραξαν αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας [αυτον]{.greek-omitted} [αυτου]{.greek-added} της χειρος ηγειρεν [αυτον]{.greek-omitted} και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν [λεγοντες]{.greek-added} [δια]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι [δυναται]{.greek-omitted} [δυνατε]{.greek-added} εξελθειν ει [μη]{.greek-omitted} [μι]{.greek-added} εν προσευχη και νηστεια[9:29]{.aside}

και [ε]{.greek-added} [εκειθεν]{.greek-omitted} [εξελθοντες]{.greek-omitted} [παρεπορευοντο]{.greek-omitted} [δια]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηθελεν]{.greek-omitted} [ινα]{.greek-omitted} [τις]{.greek-omitted} [γνω]{.greek-omitted}[9:30]{.aside}

[και]{.greek-omitted} [εκειθεν]{.greek-omitted} [κειθεν]{.greek-added} [εξελθοντες]{.greek-omitted} [εξελθων]{.greek-added} [παρεπορευοντο]{.greek-omitted} [παρεπορευετο]{.greek-added} δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30 | instance no. 2]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδοτε]{.greek-added} εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε [ηγνοουν]{.greek-omitted} [ηγνωουν]{.greek-added} το ρημα και εφοβουντο αυτον [επερωτησαι]{.greek-omitted} [ερωτησαι]{.greek-added}[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη [οικια]{.greek-omitted} [οικεια]{.greek-added} γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε [εσιωπων]{.greek-omitted} [εσιωπον]{.greek-added} προς αλληλους γαρ [διελεγχθσαν]{.greek-added} [διελεχθησαν]{.greek-omitted} [[διελεγχθησαν]{.corr}]{.greek-added} εν τη οδω τις [μειζων]{.greek-omitted} [μειζον]{.greek-added}[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} εφωνησεν τους δωδεκα [μαθητας]{.greek-added} και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μεσω αυτων και εναγκαλισαμενος [αυτο]{.greek-omitted} [αυτω]{.greek-added} ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος [εαν]{.greek-omitted} [αν]{.greek-added} εμε [δεξηται]{.greek-omitted} [δεχηται]{.greek-added} ουκ εμε δεχεται αλλα τον αποστειλαντα [με]{.greek-omitted} [μαι]{.greek-added}[9:37]{.aside}

απεκριθη δε αυτω ιωαννης λεγων διδασκαλε ειδομεν τινα τω ονοματι σου [εκβαλλοντα]{.greek-omitted} [εκβαλοντα]{.greek-added} [δαιμονια]{.greek-omitted} [δαιμονι]{.greek-added} [ος]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

[α]{.greek-added} [απεκριθη]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} [ιωαννης]{.greek-omitted} [λεγων]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ειδομεν]{.greek-omitted} [τινα]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [σου]{.greek-omitted} [εκβαλλοντα]{.greek-omitted} [δαιμονια]{.greek-omitted} ος ουκ [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} ημιν [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ εστιν καθ υμων υπερ [υμων]{.greek-omitted} [ημων]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added}[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτησει]{.greek-added} υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι μου οτι [χριστου]{.greek-abbr} [εστε]{.greek-omitted} [εσται]{.greek-added} αμην λεγω υμιν [οτι]{.greek-added} ου μη [απολεση]{.greek-omitted} [απωλεσει]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει [περικειται]{.greek-omitted} [περικειτε]{.greek-added} λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι εστιν [κυλλον]{.greek-omitted} εις την ζωην εισελθειν [κυλον]{.greek-added} η τας δυο χειρας [εχοντα]{.greek-omitted} [εχον]{.greek-added} απελθειν εις την γεενναν [η]{.greek-added} εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκολιξ]{.greek-added} αυτ[ω]{.unclear}ν ου τελευτα και το πυρ ου [σβεννυται]{.greek-omitted} [σβεννυτε]{.greek-added}[9:44]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι εστιν μονοφθαλμον [εισελθεν]{.greek-added} [εισελθειν]{.corr} εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και [το]{.greek-omitted} [τω]{.greek-added} πυρ [αυτων]{.greek-added} ου σβεννυται[9:48]{.aside}

[οπου]{.greek-omitted} [και]{.greek-added} [εαν]{.greek-added} ο [οφθαλμος]{.greek-added} [σκωληξ]{.greek-omitted} [αυτων]{.greek-omitted} [ου]{.greek-omitted} [σου]{.greek-added} [σκανδαλιζη]{.greek-added} [σε]{.greek-added} [εκβαλε]{.greek-added} [αυτον]{.greek-added} [τελευτα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [ου]{.greek-omitted} [σβεννυται]{.greek-omitted}[9:48 | instance no. 2]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια [αλι]{.greek-omitted} αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον [γενηται]{.greek-omitted} [γενητε]{.greek-added} εν τινι [αυτο]{.greek-omitted} [αυτω]{.greek-added} [αρθυσετε]{.greek-added} [αρτυσετε]{.corr} εχετε εν εαυτοις αλας και ειρηνευετε [εν]{.greek-omitted} [μετα]{.greek-added} αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας [και]{.greek-added} [δια]{.greek-omitted} [του]{.greek-omitted} περαν του ιορδανου και [συμπορευονται]{.greek-omitted} [συμπορευοντε]{.greek-added} παλιν οχλοι προς αυτον και ως [ειωθει]{.greek-omitted} [ιωθη]{.greek-added} παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι [επηρωτησαν]{.greek-omitted} [επηρωτουν]{.greek-added} αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο μωσης[10:3]{.aside}

οι δε ειπον μωσης [επετρεψεν]{.greek-omitted} [ενετειλατο]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταληψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο [αλλα]{.greek-omitted} [μια]{.greek-omitted} [σαρξ]{.greek-omitted}[10:8]{.aside}

[και]{.greek-omitted} [εσονται]{.greek-omitted} [οι]{.greek-omitted} [δυο]{.greek-omitted} [εις]{.greek-omitted} [σαρκα]{.greek-omitted} [μιαν]{.greek-omitted} [ωστε]{.greek-omitted} [ουκετι]{.greek-omitted} [εισιν]{.greek-omitted} [δυο]{.greek-omitted} αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8 | instance no. 2]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [τουτου]{.greek-added} [του]{.greek-omitted} [αυτου]{.greek-omitted} επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου και [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα [αψηται]{.greek-omitted} [αψητε]{.greek-added} αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} ηγανακτησεν και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω [υμιν]{.greek-omitted} [ημιν]{.greek-added} ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα ευλογει αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} [πλουσιος]{.greek-added} προσδραμων [εις]{.greek-omitted} και γονυπετησας [αυτον]{.greek-omitted} [αυτω]{.greek-added} επηρωτα αυτον [λεγων]{.greek-added} διδασκαλε αγαθε τι ποιησω ινα ζωην [αιωνιον]{.greek-omitted} [ιωνιον]{.greek-added} κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος [ει]{.greek-omitted} [μη]{.greek-omitted} [εις]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted}[10:18]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [τι]{.greek-omitted} [με]{.greek-omitted} [λεγεις]{.greek-omitted} [αγαθον]{.greek-omitted} [ουδεις]{.greek-omitted} [αγαθος]{.greek-omitted} ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[10:18 | instance no. 2]{.aside}

τας εντολας [οιδας]{.greek-omitted} [ωδας]{.greek-added} μη [μοιχευσης]{.greek-omitted} [μ[οι]{.unclear}χουσις]{.greek-added} μη [φονευσης]{.greek-omitted} [φονευσεις]{.greek-added} μη κλεψης μη [ψευδομαρτυρησης]{.greek-omitted} [ψευδομαρτυρισης]{.greek-added} μη [αποστερησης]{.greek-omitted} [αποστερησεις]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου [τι]{.greek-added} [ετι]{.greek-added} [υστερω]{.greek-added}[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν σοι υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι αρας τον [σταυρον]{.greek-abbr} [σου]{.greek-added}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} [εισελευσονται]{.greek-omitted} [εισελευσοντε]{.greek-added}[10:23]{.aside}

οι δε μαθηται [εθαμβουντο]{.greek-omitted} [εθαυμαζον]{.greek-added} επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις [τεκνα]{.greek-omitted} πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους [πεποιθοτας]{.greek-omitted} [πεποιθωτας]{.greek-added} επι χρημασιν εις [την]{.greek-omitted} [τιν]{.greek-added} βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-omitted} [αδυνατον]{.greek-omitted} [αλλ]{.greek-omitted} [ου]{.greek-omitted} [παρα]{.greek-omitted} [θεω]{.greek-omitted} [παντα]{.greek-omitted} [γαρ]{.greek-omitted} [δυνατα]{.greek-omitted} [εστιν]{.greek-omitted} [παρα]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted}[10:27]{.aside}

[εμβλεψας]{.greek-omitted} [δε]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγει]{.greek-omitted} [παρα]{.greek-omitted} [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27 | instance no. 2]{.aside}

[και]{.greek-added} [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} αμην λεγω υμιν [οτι]{.greek-added} ουδεις εστιν ος αφηκεν [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω [τουτω]{.greek-omitted} [τουτο]{.greek-added} οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον [κληρονομησει]{.greek-added}[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην [προαγων]{.greek-omitted} [πρωαγων]{.greek-added} αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο [αυτοις]{.greek-omitted} [αυτους]{.greek-added} λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου [αναβαινομεν]{.greek-omitted} [αναβαινωμεν]{.greek-added} εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσει]{.greek-added} και κατακρινουσιν [αυ]{.greek-added} [αυτον]{.greek-omitted} [θανατω]{.greek-omitted} [και]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted}[10:33]{.aside}

[οτι]{.greek-omitted} [ιδου]{.greek-omitted} [αναβαινομεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδοθησεται]{.greek-omitted} [τοις]{.greek-omitted} [αρχιερευσιν]{.greek-omitted} [και]{.greek-omitted} [γραμματευσιν]{.greek-omitted} [και]{.greek-omitted} [κατακρινουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [τον]{.greek-added} θανατω και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33 | instance no. 2]{.aside}

και [εμπαιξουσιν]{.greek-omitted} [εμπεξουσιν]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} και μαστιγωσουσιν αυτον και [εμπτυσουσιν]{.greek-omitted} [εμπτυσωσιν]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και [προσπορευονται]{.greek-omitted} [προσπορευοντε]{.greek-added} αυτω ιακωβος και ιωαννης οι υιοι [ζεβεδαιου]{.greek-omitted} [ζεβαιδαιου]{.greek-added} λεγοντες διδασκαλε θελομεν ινα ο εαν [αιτησωμεν]{.greek-omitted} [σε]{.greek-added} [ετισωμεν]{.greek-added} [ποιησης]{.greek-omitted} [ποιησις]{.greek-added} ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζωμε]{.greek-added} βαπτισθησεσθε[10:39]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι [οι]{.greek-omitted} [δοκουντες]{.greek-omitted} [αρχειν]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted} [κατακυριευουσιν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μεγαλοι]{.greek-omitted} [αυτων]{.greek-omitted} [κατεξουσιαζουσιν]{.greek-omitted} [αυτων]{.greek-omitted}[10:42]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [οιδατε]{.greek-omitted} [οτι]{.greek-omitted} οι δοκουντες [αρχειν]{.greek-omitted} [αρχην]{.greek-added} των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων [κατεξουσιαζουσιν]{.greek-omitted} [κατεξουσιαζωσιν]{.greek-added} αυτων[10:42 | instance no. 2]{.aside}

ουχ ουτως δε [εσται]{.greek-omitted} [εστε]{.greek-added} εν υμιν αλλ ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} [γενεσθαι]{.greek-omitted} [γενεσθε]{.greek-added} μεγας εν υμιν [εσται]{.greek-omitted} [εστε]{.greek-added} υμων διακονος[10:43]{.aside}

και ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} υμων [γενεσθαι]{.greek-omitted} [γενεσθε]{.greek-added} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [ιδου]{.greek-added} [ο]{.greek-added} υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και [επετιμων]{.greek-omitted} [επετιμον]{.greek-added} αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν [[ιησου]{.greek-abbr}]{.greek-added} υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [αυτον]{.greek-omitted} [εκελευσεν]{.greek-added} [αυτω]{.greek-added} φωνηθηναι και φωνουσιν τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} [φωνει]{.greek-omitted} [σε]{.greek-omitted} [φωνη]{.greek-added} [σαι]{.greek-added}[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας ηλθεν προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ραββουνι]{.greek-omitted} [ινα]{.greek-omitted} [αναβλεψω]{.greek-omitted}[10:51]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τι]{.greek-omitted} [θελεις]{.greek-omitted} [ποιησω]{.greek-omitted} [σοι]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [τυφλος]{.greek-omitted} ειπεν αυτω [ραββουνι]{.greek-omitted} [ραβουνη]{.greek-added} ινα αναβλεψω[10:51 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου σεσωκεν σε και ευθεως ανεβλεψεν και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε [εγγιζουσιν]{.greek-omitted} [ηγγησαν]{.greek-added} εις ιερουσαλημ εις [βηθσφαγη]{.greek-omitted} [βιθσφαγην]{.greek-added} και [βηθανιαν]{.greek-omitted} [βιθανειαν]{.greek-added} προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

[και]{.greek-omitted} [κε]{.greek-added} λεγει αυτοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} εις την κωμην [εις]{.greek-added} την [κατεναντι]{.greek-omitted} [απεναντι]{.greek-added} υμων και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.greek-omitted} [ευρησειτε]{.greek-added} [πωλον]{.greek-omitted} [πολον]{.greek-added} δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [π[ο]{.unclear}τε]{.greek-added} [κεκαθικεν]{.greek-omitted} [κεκαθηκε]{.greek-added} λυσαντες [αυτον]{.greek-omitted} αγαγετε [μοι]{.greek-added}[11:2]{.aside}

και εαν τις υμιν [ειπη]{.greek-omitted} [ειπει]{.greek-added} τι ποιειτε τουτο ειπατε [οτι]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον [τον]{.greek-added} [πωλον]{.greek-omitted} [πολον]{.greek-added} δεδεμενον [εξω]{.greek-added} προς την θυραν [εξω]{.greek-omitted} επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} [ελεγον]{.greek-omitted} [ελεγεν]{.greek-added} αυτοις [τι]{.greek-omitted} [ποιειτε]{.greek-omitted} [λυοντες]{.greek-omitted} [τον]{.greek-omitted} [πωλον]{.greek-omitted}[11:5]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [αυτοις]{.greek-omitted} καθως ενετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον [πωλον]{.greek-omitted} [πολον]{.greek-added} προς τον [ιησουν]{.greek-abbr} και [επεβαλον]{.greek-omitted} [επεθηκαν]{.greek-added} αυτω τα ιματια αυτων και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ των δενδρων [και]{.greek-omitted} [εστρωννυον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted}[11:8]{.aside}

[πολλοι]{.greek-omitted} [δε]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτων]{.greek-omitted} [εστρωσαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [εκοπτον]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [δενδρων]{.greek-omitted} και [εστρωννυον]{.greek-omitted} [εστρωννοιον]{.greek-added} [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8 | instance no. 2]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις [βηθανιαν]{.greek-omitted} [βυθανειαν]{.greek-added} μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο [βηθανιας]{.greek-omitted} [βιθανειας]{.greek-added} επεινασεν[11:12]{.aside}

και ιδων [απο]{.greek-added} [μακροθεν]{.greek-added} [μιαν]{.greek-added} συκην [μακροθεν]{.greek-omitted} εχουσαν φυλλα ηλθεν ει αρα ευρησει τι εν αυτη και ελθων επ αυτην ουδεν [ευρεν]{.greek-omitted} [ευρε]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον [φαγοι]{.greek-omitted} [φαγει]{.greek-added} και ηκουον οι μαθηται αυτου[11:14]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας καθεδρας των πωλουντων τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ [ηφιεν]{.greek-omitted} [ηφι]{.greek-added} [ινα]{.greek-omitted} [τις]{.greek-omitted} [διενεγκη]{.greek-omitted} [σκευος]{.greek-omitted} [δια]{.greek-omitted} [του]{.greek-omitted} [ιερου]{.greek-omitted}[11:16]{.aside}

[εν]{.greek-added} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηφιεν]{.greek-omitted} ινα τις [διενεγκη]{.greek-omitted} [διενεγκει]{.greek-added} σκευος δια του ιερου[11:16 | instance no. 2]{.aside}

και εδιδασκεν λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται πασιν τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και [ηκουσαν]{.greek-omitted} [ηκουον]{.greek-added} [οι]{.greek-added} [αρχιερεις]{.greek-added} [και]{.greek-added} οι γραμματεις [και]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} και εζητουν πως αυτον [απολεσωσιν]{.greek-omitted} [απωλεσωσι]{.greek-added} εφοβουντο γαρ αυτον οτι πας ο οχλος [εξεπλησσετο]{.greek-omitted} [εξεπλησετο]{.greek-added} επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε εγενετο [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι [ειδον]{.greek-omitted} [ιδον]{.greek-added} την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω [ραββι]{.greek-omitted} [ραββη]{.greek-added} ιδε η [συκη]{.greek-omitted} [συκι]{.greek-added} ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε [πιστιν]{.greek-omitted} [πιστην]{.greek-added} [θεου]{.greek-abbr}[11:22]{.aside}

αμην [γαρ]{.greek-omitted} λεγω υμιν οτι ος αν [ειπη]{.greek-omitted} [ειπει]{.greek-added} τω ορει [τουτω]{.greek-omitted} [τουτο]{.greek-added} αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευει]{.greek-added} οτι α λεγει γινεται εσται αυτω [ο]{.greek-omitted} [οσα]{.greek-added} [αν]{.greek-added} [εαν]{.corr} [ειπη]{.greek-omitted} [ειπει]{.greek-added}[11:23]{.aside}

δια [τουτο]{.greek-omitted} [τουτω]{.greek-added} λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθε]{.greek-added} πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκετε]{.greek-added} προσευχομενοι αφιετε ει τι [εχετε]{.greek-omitted} [κατα]{.greek-omitted} [τινος]{.greek-omitted} [ινα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [υμων]{.greek-omitted}[11:25]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [στηκητε]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [αφιετε]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη [υμιν]{.greek-omitted} [υμων]{.greek-added} τα παραπτωματα υμων[11:25 | instance no. 2]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} [αφησει]{.greek-omitted} [αφη]{.greek-added} [υμιν]{.greek-added} τα παραπτωματα υμων[11:26]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} προς αυτον οι αρχιερεις και οι [γραμματ[ε]{.unclear}]{.greek-added} [γραμματεις]{.corr} και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις [και]{.greek-omitted} [η]{.greek-added} τις σοι [εδωκεν]{.greek-added} την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και [εαν]{.greek-added} αποκριθητε μοι [και]{.greek-omitted} ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν [ειπωμεν]{.greek-omitted} [ειπομεν]{.greek-added} εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} [εαν]{.greek-added} [ειπωμεν]{.greek-omitted} [ειπομεν]{.greek-added} εξ [ανθρωπων]{.greek-abbr} [εφοβουντο]{.greek-omitted} [φοβουμεθα]{.greek-added} τον λαον απαντες γαρ [ειχον]{.greek-omitted} [ηχον]{.greek-added} τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες λεγουσιν τω [ιησου]{.greek-abbr} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν [ποια]{.greek-omitted} [ποι]{.greek-added} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιω]{.greek-omitted}[11:33]{.aside}

[α]{.greek-added} [και]{.greek-omitted} [αποκριθεντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [ουκ]{.greek-omitted} [οιδαμεν]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ουδε]{.greek-omitted} [εγω]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} εξουσια ταυτα ποιω[11:33 | instance no. 2]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και περιεθηκεν [αυτω]{.greek-added} φραγμον και [ωρυξεν]{.greek-omitted} [ορυξεν]{.greek-added} [υποληνιον]{.greek-omitted} [υποληνων]{.greek-added} και ωκοδομησεν πυργον και [εξεδοτο]{.greek-omitted} [εξεδωτο]{.greek-added} αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και απεστειλεν προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν απεστειλεν προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} [εκεφαλαιωσαν]{.greek-omitted} [εκεφαλεωσαν]{.greek-added} και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον απεστειλεν κακεινον απεκτειναν και πολλους αλλους [τους]{.greek-omitted} [ους]{.greek-added} μεν δεροντες [τους]{.greek-omitted} [ους]{.greek-added} δε αποκτενοντες[12:5]{.aside}

[υστερον]{.greek-added} [δε]{.greek-added} ετι [ουν]{.greek-omitted} ενα [υιον]{.greek-abbr} εχων αγαπητον αυτου απεστειλεν και αυτον προς αυτους εσχατον λεγων οτι [εντραπησονται]{.greek-omitted} [εντραπησοντε]{.greek-added} τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [θεασαμενοι]{.greek-added} [αυτον]{.greek-added} [ερχομενον]{.greek-added} ειπον προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [οτι]{.greek-omitted} ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον [απε]{.greek-added} [απεκτειναν]{.greek-omitted} [και]{.greek-omitted} [εξεβαλον]{.greek-omitted} [εξω]{.greek-omitted} [του]{.greek-omitted} [αμπελωνος]{.greek-omitted}[12:8]{.aside}

[και]{.greek-omitted} [λαβοντες]{.greek-omitted} [αυτον]{.greek-omitted} [απεκτειναν]{.greek-omitted} [κτειναν]{.greek-added} και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8 | instance no. 2]{.aside}

τι ουν ποιησει ο κυριος του αμπελωνος [τοις]{.greek-added} [γεωργοις]{.greek-added} [λεγουσιν]{.greek-added} [αυτω]{.greek-added} [ελευσεται]{.greek-omitted} [ελευσετε]{.greek-added} και [απολεσει]{.greek-omitted} [απωλεσει]{.greek-added} τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

[λεγει]{.greek-added} [αυτοις]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην [γωνιας]{.greek-omitted} [γονειας]{.greek-added}[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} και αφεντες αυτον [απηλθον]{.greek-omitted} [απηλθων]{.greek-added}[12:12]{.aside}

και αποστελλουσιν προς αυτον τινας των φαρισαιων [και]{.greek-omitted} [των]{.greek-omitted} [ηρωδιανων]{.greek-omitted} ινα αυτον αγρευσωσιν λογω[12:13]{.aside}

[και]{.greek-added} [ελθοντες]{.greek-added} οι [δε]{.greek-omitted} [φαρισαιοι]{.greek-added} [επηρωτων]{.greek-added} [αυτον]{.greek-added} [ελθοντες]{.greek-omitted} [λεγοντες]{.greek-added} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [ειπε]{.greek-added} [ουν]{.greek-added} [ημιν]{.greek-added} εξεστιν [δουναι]{.greek-added} [κηνσον]{.greek-omitted} [κινσον]{.greek-added} καισαρι [δουναι]{.greek-omitted} η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την [υποκρισιν]{.greek-omitted} [αποκρισιν]{.greek-added} ειπεν αυτοις [τι]{.greek-omitted} [με]{.greek-omitted} [πειραζετε]{.greek-omitted} [φερετε]{.greek-omitted} [μοι]{.greek-omitted} [δηναριον]{.greek-omitted} [ινα]{.greek-omitted} [ιδω]{.greek-omitted}[12:15]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ειδως]{.greek-omitted} [αυτων]{.greek-omitted} [την]{.greek-omitted} [υποκρισιν]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} τι με πειραζετε φερετε μοι δηναριον ινα ιδω[12:15 | instance no. 2]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [αποδοτε]{.greek-omitted} [αποδωτε]{.greek-added} [ουν]{.greek-added} τα καισαρος καισαρι και τα του [θεου]{.greek-omitted} [[θεω]{.greek-abbr}]{.greek-added} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος [αποθανη]{.greek-omitted} [αποθανει]{.greek-added} και [καταλιπη]{.greek-omitted} [καταλειπη]{.greek-added} γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [ουν]{.greek-added} αδελφοι ησαν και ο πρωτος ελαβεν γυναικα και αποθνησκων ουκ αφηκεν σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν και ουδε αυτος αφηκεν σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα εσχατη [δε]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη [ουν]{.greek-added} αναστασει οταν αναστωσιν τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην [γυναικα]{.greek-omitted} [γυναι]{.greek-added}[12:23]{.aside}

[κα]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [αναστασει]{.greek-omitted} [οταν]{.greek-omitted} [αναστωσιν]{.greek-omitted} [τινος]{.greek-omitted} [αυτων]{.greek-omitted} [εσται]{.greek-omitted} [γυνη]{.greek-omitted} [οι]{.greek-omitted} [γαρ]{.greek-omitted} [επτα]{.greek-omitted} [εσχον]{.greek-omitted} [αυτην]{.greek-omitted} [γυναικα]{.greek-omitted}[12:23 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added} μη [ειδοτες]{.greek-omitted} [ιδωτες]{.greek-added} τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

[οταν]{.greek-omitted} [οτε]{.greek-added} γαρ εκ νεκρων αναστωσιν ουτε [γαμουσιν]{.greek-omitted} [γαμωσιν]{.greek-added} ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι [εγειρονται]{.greek-omitted} [εγειροντε]{.greek-added} ουκ ανεγνωτε εν [τη]{.greek-omitted} [τω]{.greek-added} βιβλω μωσεως επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω [ειμι]{.greek-added} ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστ[ι]{.unclear}ν ο [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} [ζωντων]{.greek-omitted} [ζοντων]{.greek-added} υμεις ουν [πολυ]{.greek-omitted} [πολλοι]{.greek-added} [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added}[12:27]{.aside}

και προσελθων εις [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματευς]{.greek-added} ακουσας αυτων [συζητουντων]{.greek-omitted} [συνζητουντων]{.greek-added} [ειδως]{.greek-omitted} [ιδων]{.greek-added} οτι καλως [αυτοις]{.greek-omitted} απεκριθη επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη παντων εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω οτι πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολη]{.greek-added} ακουε [[ι]{.unclear}λ]{.greek-added} [[ισραηλ]{.greek-abbr}]{.corr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της [διανοια]{.greek-added} [ψυχης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [διανοιας]{.corr} σου και εξ ολης της ισχυος σου αυτη πρωτ[η]{.unclear} εντολη[12:30]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} [μειζων]{.greek-omitted} [μηζων]{.greek-added} τουτων αλλη [εν]{.greek-added} [εντολη]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted}[12:31]{.aside}

[και]{.greek-omitted} [δευτερα]{.greek-omitted} [ομοια]{.greek-omitted} [αυτη]{.greek-omitted} [αγαπησεις]{.greek-omitted} [τον]{.greek-omitted} [πλησιον]{.greek-omitted} [σου]{.greek-omitted} [ως]{.greek-omitted} [σεαυτον]{.greek-omitted} [μειζων]{.greek-omitted} [τουτων]{.greek-omitted} [αλλη]{.greek-omitted} [εντολη]{.greek-omitted} [τολη]{.greek-added} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31 | instance no. 2]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις εστιν [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας [σου]{.greek-added} και εξ ολης της [συνεσεως]{.greek-omitted} [συναισεως]{.greek-added} και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον [επερωτησαι]{.greek-omitted} [περωτησαι]{.greek-added}[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [εστιν]{.greek-omitted} [δαυιδ]{.greek-abbr} [εστι]{.greek-added}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν δαυιδ λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο πολυς οχλος [ηκουεν]{.greek-omitted} [ηκουον]{.greek-added} αυτου [ηδεως]{.greek-omitted} [ειδεως]{.greek-added}[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και [πρωτοκα]{.greek-added} [πρωτοκαθεδριας]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [συναγωγαις]{.greek-omitted} [και]{.greek-omitted} [πρωτοκλισιας]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [δειπνοις]{.greek-omitted}[12:39]{.aside}

[θεδριας]{.greek-added} [και]{.greek-omitted} [πρωτοκαθεδριας]{.greek-omitted} εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιαις]{.greek-added} εν τοις δειπνοις[12:39 | instance no. 2]{.aside}

οι [κατεσθιοντες]{.greek-omitted} [καταισθιοντες]{.greek-added} τας [οικιας]{.greek-omitted} [οικειας]{.greek-added} των χηρων και προφασει μακρα προσευχομενοι [ουτοι]{.greek-omitted} [ληψονται]{.greek-omitted} [ουτω]{.greek-added} [λειψοντε]{.greek-added} περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου [εθεωρει]{.greek-omitted} [εθεορει]{.greek-added} πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη εβαλεν λεπτα δυο ο εστιν κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων βεβληκεν των βαλλοντων εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα [ειχεν]{.greek-omitted} [ηχεν]{.greek-added} εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου [διδασκαλε]{.greek-omitted} ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

[και]{.greek-omitted} καθημενου αυτου εις το ορος [των]{.greek-omitted} [ελαιων]{.greek-omitted} [κατεναντι]{.greek-omitted} [του]{.greek-omitted} [ιερου]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [πετρος]{.greek-omitted} [και]{.greek-omitted} [ιακωβος]{.greek-omitted} [και]{.greek-omitted} [ιωαννης]{.greek-omitted} [και]{.greek-omitted} [ανδρεας]{.greek-omitted}[13:3]{.aside}

[και]{.greek-omitted} [καθημενου]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ορος]{.greek-omitted} των ελαιων [κατεναντι]{.greek-omitted} [κατεναναντι]{.greek-added} του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3 | instance no. 2]{.aside}

ειπε ημιν ποτε ταυτα [εσται]{.greek-omitted} [εστε]{.greek-added} και τι το σημειον οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας [πλανηση]{.greek-omitted} [πλανησει]{.greek-added}[13:5]{.aside}

πολλοι γαρ [ελευσονται]{.greek-omitted} [ελευσοντε]{.greek-added} επι τω ονοματι μου λεγοντες οτι [εγ[―]{.gap}]{.greek-added} [εγω]{.corr} [ειμι]{.corr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανησωσιν]{.greek-added}[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουετε]{.greek-added} πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και [εσονται]{.greek-omitted} [εσοντε]{.greek-added} [σεισμοι]{.greek-omitted} [σισμοι]{.greek-added} κατα τοπους και [εσονται]{.greek-omitted} [εσοντε]{.greek-added} λιμοι και [ταραχαι]{.greek-omitted} [ταραχε]{.greek-added} [ταυτα]{.greek-added} [παντα]{.greek-added} αρχαι [ωδινων]{.greek-omitted} [οδινων]{.greek-added} [ταυτα]{.greek-omitted}[13:8]{.aside}

βλεπετε δε υμεις εαυτους παραδωσουσιν γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη προμεριμνατε τι [λα]{.greek-added} [λαλησητε]{.greek-omitted} [μηδε]{.greek-omitted} [μελετατε]{.greek-omitted} [αλλ]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [δοθη]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [τουτο]{.greek-omitted} [λαλειτε]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [εστε]{.greek-omitted} [υμεις]{.greek-omitted} [οι]{.greek-omitted} [λαλουντες]{.greek-omitted} [αλλα]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αγιον]{.greek-omitted}[13:11]{.aside}

[λησεται]{.greek-added} [οταν]{.greek-omitted} [δε]{.greek-omitted} [αγαγωσιν]{.greek-omitted} [υμας]{.greek-omitted} [παραδιδοντες]{.greek-omitted} [μη]{.greek-omitted} [προμεριμνατε]{.greek-omitted} [τι]{.greek-omitted} [λαλησητε]{.greek-omitted} μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ [υμεις]{.greek-added} εστε [υμεις]{.greek-omitted} οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11 | instance no. 2]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και [επαναστησονται]{.greek-omitted} [επαναστησοντε]{.greek-added} τεκνα επι γονεις και θανατω[σ]{.unclear}ουσιν αυτους[13:12]{.aside}

και εσεσθ[ε]{.unclear} [[εσεσθαι]{.corr}]{.greek-added} μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε [ιδητε]{.greek-omitted} [ιδειτε]{.greek-added} το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου [δει]{.greek-omitted} [δη]{.greek-added} ο αναγινωσκων [νοειτω]{.greek-omitted} [νοητω]{.greek-added} τοτε οι εν τη ιουδαια φευγετωσαν [εις]{.greek-omitted} [επι]{.greek-added} τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} μηδε [εισελθετω]{.greek-omitted} [ισθετω]{.greek-added} αραι τι εκ της [οικιας]{.greek-omitted} [οικειας]{.greek-added} αυτου[13:15]{.aside}

και ο εις τον [αγρ[―]{.gap}ν]{.greek-added} [αγρον]{.corr} [ων]{.greek-omitted} μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις [ημερας]{.greek-added} [ημεραις]{.corr}[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη [γενητ[ε]{.unclear}]{.greek-added} [γενηται]{.corr} η φυγη υμων χειμωνος [η]{.greek-added} [εν]{.greek-added} [σαββατω]{.greek-added}[13:18]{.aside}

εσονται γαρ [αι]{.greek-omitted} [ε]{.greek-added} ημεραι εκειναι [θλιψις]{.greek-omitted} [θληψις]{.greek-added} οια ου [γεγο]{.greek-added} [γεγονεν]{.greek-omitted} [τοιαυτη]{.greek-omitted} [απ]{.greek-omitted} [αρχης]{.greek-omitted} [κτισεως]{.greek-omitted} [ης]{.greek-omitted} [εκτισεν]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εως]{.greek-omitted} [του]{.greek-omitted} [νυν]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [γενηται]{.greek-omitted}[13:19]{.aside}

[νε]{.greek-added} [εσονται]{.greek-omitted} [γαρ]{.greek-omitted} [αι]{.greek-omitted} [ημεραι]{.greek-omitted} [εκειναι]{.greek-omitted} [θλιψις]{.greek-omitted} [οια]{.greek-omitted} [ου]{.greek-omitted} [γεγονεν]{.greek-omitted} τοιαυτη απ αρχης κτισεως ης [εκτισεν]{.greek-omitted} [εκτησεν]{.greek-added} ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19 | instance no. 2]{.aside}

και ει [μη]{.greek-omitted} [μι]{.greek-added} [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκωλοβωσεν]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκωλοβωσεν]{.greek-added} τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν [ειπη]{.greek-omitted} [ειπει]{.greek-added} ιδου ωδε ο [χριστος]{.greek-abbr} [η]{.greek-omitted} ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added}[13:21]{.aside}

[εγερθησονται]{.greek-omitted} [εγερθησοντε]{.greek-added} γαρ ψευδοχριστοι και ψευδοπροφηται και δωσουσιν σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου [γαρ]{.greek-added} προειρηκα υμιν [παντα]{.greek-omitted} [απαντα]{.greek-added}[13:23]{.aside}

αλλ εν [εκειναις]{.greek-omitted} [εκεινες]{.greek-added} ταις ημεραις μετα την [θλιψιν]{.greek-omitted} [θληψιν]{.greek-added} εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι [αστερες]{.greek-omitted} [αστεραις]{.greek-added} [εκ]{.greek-added} του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} [σαλευθησονται]{.greek-omitted} [σαλευθησοντε]{.greek-added}[13:25]{.aside}

και τοτε [οψονται]{.greek-omitted} [οψοντε]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου [και]{.greek-omitted} επισυναξει τους [ε[κ]{.unclear}κλεκτους]{.greek-added} [εκλεκτους]{.corr} αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την [παραβολην]{.greek-omitted} [οταν]{.greek-omitted} [αυτης]{.greek-omitted} [ηδη]{.greek-omitted} [ο]{.greek-omitted} [κλαδος]{.greek-omitted} [απαλος]{.greek-omitted} [γενηται]{.greek-omitted} [και]{.greek-omitted} [εκφυη]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [γινωσκετε]{.greek-omitted} [οτι]{.greek-omitted} [εγγυς]{.greek-omitted} [το]{.greek-omitted} [θερος]{.greek-omitted} [εστιν]{.greek-omitted}[13:28]{.aside}

[απο]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [συκης]{.greek-omitted} [μαθετε]{.greek-omitted} [την]{.greek-omitted} παραβολην οταν [αυτης]{.greek-omitted} [ηδη]{.greek-omitted} ο κλαδος [αυτης]{.greek-added} απαλος γενηται και [εκφυη]{.greek-omitted} [εκφυει]{.greek-added} τα [φυλλα]{.greek-omitted} [φυλα]{.greek-added} γινωσκετε οτι εγγυς το θερος [εστιν]{.greek-omitted} [εστι]{.greek-added}[13:28 | instance no. 2]{.aside}

ουτως και υμεις οταν ταυτα [ιδητε]{.greek-omitted} [ειδητε]{.greek-added} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν [οτι]{.greek-omitted} ου μη παρελθη η [γενεα]{.greek-omitted} [γεναια]{.greek-added} αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσοντε]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} [της]{.greek-added} ωρας ουδεις [[ε]{.unclear}]{.greek-added} [οιδεν]{.corr} ουδε οι αγγελοι [οι]{.greek-omitted} εν [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει [μη]{.greek-omitted} [μι]{.greek-added} ο [πατηρ]{.greek-abbr}[13:32]{.aside}

[βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} [αγρυπνειτε]{.greek-omitted} [αγρυπνητε]{.greek-added} και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

[ως]{.greek-omitted} [ωσπερ]{.greek-added} [γαρ]{.greek-added} [ανθρωπος]{.greek-abbr} [αποδημος]{.greek-omitted} [αποδημων]{.greek-added} αφεις την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα [γρηγορη]{.greek-omitted} [γρηγορει]{.greek-added}[13:34]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της [οικιας]{.greek-omitted} [οικειας]{.greek-added} [αυτου]{.greek-added} ερχεται οψε η [μεσονυκτιου]{.greek-omitted} [μεσονυκτιω]{.greek-added} η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω πασιν λεγω [γρηγορειτε]{.greek-omitted} [γρηγορητε]{.greek-added}[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [πως]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [δολω]{.greek-omitted} [κρατησαντες]{.greek-omitted} [αποκτεινωσιν]{.greek-omitted}[14:1]{.aside}

[ην]{.greek-omitted} [δε]{.greek-omitted} [το]{.greek-omitted} [πασχα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [αζυμα]{.greek-omitted} [μετα]{.greek-omitted} [δυο]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [εζητουν]{.greek-omitted} οι αρχιερεις και οι γραμματεις πως αυτον εν δολω κρατησαντες αποκτεινωσιν[14:1 | instance no. 2]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν [βηθανια]{.greek-omitted} [βιθανεια]{.greek-added} εν τη [οικια]{.greek-omitted} [οικεια]{.greek-added} σιμωνος του λεπρου κατακειμενου αυτου ηλθεν γυνη [εχουσα]{.greek-omitted} αλαβαστρον μυρου [εχουσα]{.greek-added} ναρδου [πιστικης]{.greek-omitted} [πιστηκης]{.greek-added} πολυτελους και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

[ησαν]{.greek-omitted} [εισαν]{.greek-added} δε τινες αγανακτουντες προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και [ενεβριμωντο]{.greek-omitted} [ενεβρημουντο]{.greek-added} αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη εποιησεν προελαβεν [μυρισαι]{.greek-omitted} [μυρησαι]{.greek-added} μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον [τουτο]{.greek-omitted} [του]{.greek-added} [εις]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [κοσμον]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [εποιησεν]{.greek-omitted} [αυτη]{.greek-omitted} [λαληθησεται]{.greek-omitted} [εις]{.greek-omitted} [μνημοσυνον]{.greek-omitted} [αυτης]{.greek-omitted}[14:9]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οπου]{.greek-omitted} [εαν]{.greek-omitted} [κηρυχθη]{.greek-omitted} το [ευαγγελιον]{.greek-omitted} [τουτο]{.greek-omitted} εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9 | instance no. 2]{.aside}

και ο ιουδας ο ισκαριωτης εις των δωδεκα απηλθεν προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλαντο]{.greek-omitted} [απηγγειλαντο]{.greek-added} αυτω αργυριον δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το [καταλυμμ[―]{.gap}]{.greek-added} [καταλυμα]{.greek-omitted} [[καταλυμμα]{.corr}]{.greek-added} οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει ανωγεον μεγα [εστρωμενον]{.greek-omitted} [εστρομενον]{.greek-added} ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης [ερχεται]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted}[14:17]{.aside}

[και]{.greek-omitted} [οψιας]{.greek-omitted} [γενομενης]{.greek-omitted} ερχεται μετα των δωδεκα[14:17 | instance no. 2]{.aside}

[και]{.greek-omitted} [οψιας]{.greek-omitted} [γενομενης]{.greek-omitted} ερχεται μετα των δωδεκα[14:17 | instance no. 3]{.aside}

και [ανακειμενων]{.greek-omitted} [ανακειενων]{.greek-added} αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο [εσθιων]{.greek-omitted} [εσθιον]{.greek-added} μετ εμου[14:18]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λε[γ]{.unclear}ω υμιν οτι εις εξ υμων παραδωσει με ο [εσθιων]{.greek-omitted} [εσθιον]{.greek-added} μετ εμου[14:18 | instance no. 2]{.aside}

οι δε [ηρξαντο]{.greek-omitted} [ειρξαντο]{.greek-added} λυπεισθαι και λεγειν αυτω εις καθ εις [μητι]{.greek-omitted} [εγω]{.greek-omitted} [και]{.greek-omitted} [αλλος]{.greek-omitted} [μητι]{.greek-omitted} [εγω]{.greek-omitted}[14:19]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19 | instance no. 2]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} αποκριθεις ειπεν αυτοις εις [τον]{.greek-added} [εκ]{.greek-omitted} [των]{.greek-omitted} δωδεκα ο [εμβαπτομενος]{.greek-omitted} [ενβαπτωμενος]{.greek-added} μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως [γεγραπται]{.greek-omitted} [γαιγραπται]{.greek-added} περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} καλον ην αυτω [ει]{.greek-omitted} [η]{.greek-added} ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[14:22]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο εστιν το αιμα μου το της καινης διαθηκης το [περι]{.greek-omitted} [πολλων]{.greek-omitted} [εκχυνομενον]{.greek-omitted}[14:24]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τουτο]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [αιμα]{.greek-omitted} [μου]{.greek-omitted} [το]{.greek-omitted} [της]{.greek-omitted} [καινης]{.greek-omitted} [διαθηκης]{.greek-omitted} [το]{.greek-omitted} περι πολλων εκχυνομενον [εις]{.greek-added} [αφεσιν]{.greek-added} [αμαρτιων]{.greek-added}[14:24 | instance no. 2]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεσθαι]{.greek-added} εν εμοι εν τη νυκτι ταυτη οτι [γεγραπται]{.greek-omitted} [γαιγραπται]{.greek-added} παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησοντε]{.greek-added} τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω [και]{.greek-omitted} ει παντες σκανδαλισθησονται [εν]{.greek-added} [σοι]{.greek-added} αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι [συ]{.greek-omitted} σημερον εν τη νυκτι ταυτη πριν [η]{.greek-omitted} [δις]{.greek-omitted} αλεκτορα [δεις]{.greek-added} [φωνησαι]{.greek-omitted} [φωνησει]{.greek-added} [τρις]{.greek-omitted} [τρεις]{.greek-added} [απαρνηση]{.greek-omitted} [απαρνησει]{.greek-added} με[14:30]{.aside}

ο δε [πετρος]{.greek-added} εκπερισσου [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν [δεει]{.greek-added} με [συν]{.greek-added} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} σοι [αποθανειν]{.greek-added} ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε [ως]{.greek-added} [εως]{.corr} [ου]{.greek-added} [απελθων]{.greek-added} [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ [εαυ]{.greek-added} [εαυτου]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκθαμβεισθαι]{.greek-omitted} [και]{.greek-omitted} [αδημονειν]{.greek-omitted}[14:33]{.aside}

[του]{.greek-added} [και]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [τον]{.greek-omitted} [πετρον]{.greek-omitted} [και]{.greek-omitted} [ιακωβον]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτου]{.greek-omitted} και ηρξατο [εκθαμβεισθαι]{.greek-omitted} [εκθαμβεισθε]{.greek-added} και [ακηδιαν]{.greek-added} [και]{.greek-added} [τοτε]{.greek-added} [αδημονειν]{.greek-omitted} [αδημονων]{.greek-added}[14:33 | instance no. 2]{.aside}

[και]{.greek-omitted} λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι [της]{.greek-omitted} [γης]{.greek-omitted} [προσωπον]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [γην]{.greek-added} και προσηυχετο [η]{.greek-added} [δυνατον]{.greek-added} [εστι]{.greek-added} ινα [ει]{.greek-omitted} [δυνατον]{.greek-omitted} [εστιν]{.greek-omitted} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε [απ]{.greek-added} [εμου]{.greek-added} το ποτηριον [απ]{.greek-omitted} [εμου]{.greek-omitted} τουτο αλλ ου τι εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [τι]{.greek-omitted} [συ]{.greek-omitted} [ως]{.greek-added} [σοι]{.greek-added} [θελεις]{.greek-added}[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω [σιμων]{.greek-omitted} [σιμον]{.greek-added} [καθευδεις]{.greek-omitted} [καθευδης]{.greek-added} ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορηται]{.greek-added} και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καταβεβαρημενοι]{.greek-added} και ουκ [ηδεισαν]{.greek-omitted} [ιδησαν]{.greek-added} τι αυτω αποκριθωσιν[14:40]{.aside}

και [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} απεχει [το]{.greek-added} [τελος]{.greek-added} ηλθεν η ωρα ιδου [παραδιδοται]{.greek-omitted} [παραδιδοτε]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-omitted} [[ανου]{.greek-abbr}]{.greek-added} εις τας χειρας των αμαρτωλων[14:41]{.aside}

[εγειρεσθε]{.greek-omitted} [εγειρεσ]{.greek-added} [αγωμεν]{.greek-omitted} [ιδου]{.greek-omitted} [ο]{.greek-omitted} [παραδιδους]{.greek-omitted} [με]{.greek-omitted} [ηγγικεν]{.greek-omitted}[14:42]{.aside}

[εγειρεσθε]{.greek-omitted} [θε]{.greek-added} [αγωμεν]{.greek-omitted} [αγομεν]{.greek-added} ιδου [ηγκηκεν]{.greek-added} ο παραδιδους με [ηγγικεν]{.greek-omitted}[14:42 | instance no. 2]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος εστιν κρατησατε αυτον και απαγαγετε [αυτον]{.greek-added} ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω [ραββι]{.greek-omitted} [ραββη]{.greek-added} [ραββι]{.greek-omitted} [ραββη]{.greek-added} και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας [αυτων]{.greek-omitted} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την [μαχαιραν]{.greek-omitted} [μαχαιρα]{.greek-added} [επαισεν]{.greek-omitted} [επεσε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας [διδασκων]{.greek-added} εν τω ιερω [διδασκων]{.greek-omitted} και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι [των]{.greek-added} [προφητων]{.greek-added}[14:49]{.aside}

[και]{.greek-omitted} [τοτε]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω [περι]{.greek-added} [περιβεβλημενος]{.greek-omitted} [σινδονα]{.greek-omitted} [επι]{.greek-omitted} [γυμνου]{.greek-omitted} [και]{.greek-omitted} [κρατουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[14:51]{.aside}

[και]{.greek-omitted} [εις]{.greek-omitted} [τις]{.greek-omitted} [νεανισκος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted} [περιβεβλημενος]{.greek-omitted} [βεβλημενος]{.greek-added} σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51 | instance no. 2]{.aside}

ο δε [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και [απηγαγον]{.greek-omitted} [πηγαγον]{.greek-added} τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και [συνερχονται]{.greek-omitted} [συνερχοντε]{.greek-added} αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην [συγκαθημενος]{.greek-omitted} [συνκαθημενος]{.greek-added} μετα των υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το [θανατωσαι]{.greek-omitted} [θανατωσε]{.greek-added} αυτον και ουχ [ευρισκον]{.greek-omitted} [ευρον]{.greek-added}[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και [ισαι]{.greek-omitted} [εισαι]{.greek-added} αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως [ιση]{.greek-omitted} [εισι]{.greek-added} ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε [εσιωπα]{.greek-omitted} [εσιω]{.greek-added} [και]{.greek-omitted} [ουδεν]{.greek-omitted} [απεκρινατο]{.greek-omitted} [παλιν]{.greek-omitted} [ο]{.greek-omitted} [αρχιερευς]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [συ]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ευλογητου]{.greek-omitted}[14:61]{.aside}

[πα]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [εσιωπα]{.greek-omitted} και ουδεν απεκρινατο παλιν ο αρχιερευς [επηρωτα]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτον [και]{.greek-omitted} [λεγει]{.greek-omitted} [εκ]{.greek-added} [δευτερου]{.greek-added} [λεγων]{.greek-added} αυτω συ ει ο [χριστος]{.greek-abbr} ο υιος του [ευλογητου]{.greek-omitted} [ευλογημενου]{.greek-added}[14:61 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-added} [συ]{.greek-added} [ειπας]{.greek-added} [οτι]{.greek-added} εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον [μετα]{.greek-omitted} [επι]{.greek-added} των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς [διαρρηξας]{.greek-omitted} [ριξας]{.greek-added} [τους]{.greek-added} [αρχιερευς]{.greek-added} [ριξας]{.greek-added} τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε [παντες]{.greek-added} της βλασφημιας [του]{.greek-added} [στοματος]{.greek-added} [αυτου]{.greek-added} τι υμιν [φαινεται]{.greek-omitted} [φενεται]{.greek-added} οι δε παντες κατεκριναν αυτον ειναι [ενοχον]{.greek-omitted} [ενωχον]{.greek-added} θανατου[14:64]{.aside}

και [ηρξαντο]{.greek-omitted} [ηρξατο]{.greek-added} τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν [αυτον]{.greek-omitted} [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added}[14:65]{.aside}

και [οντος]{.greek-omitted} [οντως]{.greek-added} του πετρου εν τη αυλη [κατω]{.greek-omitted} ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον [θερμαινομενον]{.greek-omitted} [θερμενομενον]{.greek-added} εμβλεψασα αυτω λεγει και [συ]{.greek-omitted} [σοι]{.greek-added} μετα του [ναζαρηνου]{.greek-omitted} [ναζωρινου]{.greek-added} [ιησου]{.greek-abbr} [ησθα]{.greek-omitted} [εισθα]{.greek-added}[14:67]{.aside}

ο δε [ηρνησατο]{.greek-omitted} [ηρνισατο]{.greek-added} λεγων ουκ οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} επισταμαι τι [συ]{.greek-omitted} [σοι]{.greek-added} λεγεις και εξηλθεν εξω εις [το]{.greek-omitted} [προαυλιον]{.greek-omitted} [και]{.greek-omitted} [αλεκτωρ]{.greek-omitted} [εφωνησεν]{.greek-omitted}[14:68]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ηρνησατο]{.greek-omitted} [λεγων]{.greek-omitted} [ουκ]{.greek-omitted} [οιδα]{.greek-omitted} [ουδε]{.greek-omitted} [επισταμαι]{.greek-omitted} [τι]{.greek-omitted} [συ]{.greek-omitted} [λεγεις]{.greek-omitted} [και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εξω]{.greek-omitted} [εις]{.greek-omitted} το προαυλιον και αλεκτωρ εφωνησεν[14:68 | instance no. 2]{.aside}

και η [παιδισκη]{.greek-omitted} [παιδισκει]{.greek-added} ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστηκωσιν]{.greek-added} οτι ουτος εξ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added}[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνισατο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και [γαρ]{.greek-added} η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και [ευθεως]{.greek-added} εκ δευτερου αλεκτωρ εφωνησεν και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι [δις]{.greek-omitted} [δεις]{.greek-added} [απαρνηση]{.greek-omitted} [απαρνησει]{.greek-added} [με]{.greek-omitted} [μαι]{.greek-added} [τρις]{.greek-omitted} [τρεις]{.greek-added} και [επιβαλων]{.greek-omitted} [επιλαβομενος]{.greek-added} [εκλαιεν]{.greek-omitted} [εκλαιε]{.greek-added}[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [ουκ]{.greek-omitted} [αποκρινη]{.greek-omitted} [ουδεν]{.greek-omitted} [ιδε]{.greek-omitted} [ποσα]{.greek-omitted} [σου]{.greek-omitted} [καταμαρτυρουσιν]{.greek-omitted}[15:4]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [παλιν]{.greek-omitted} [επηρωτησεν]{.greek-omitted} αυτον λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον [πεποιηκεισαν]{.greek-omitted} [πεποιηκησαν]{.greek-added}[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

εγινωσκεν γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδωκαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε [τον]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} [ανασιωμενοι]{.greek-added} [υπο]{.greek-added} [των]{.greek-added} [αρχιερεων]{.greek-added} [και]{.greek-added} [ελεγον]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσως]{.greek-added} [εκραξαν]{.greek-omitted} [εκραξον]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [φραγελλωσας]{.greek-omitted} [ινα]{.greek-omitted} [σταυρωθη]{.greek-omitted}[15:15]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [βουλομενος]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [το]{.greek-omitted} [ικανον]{.greek-omitted} [ποιησαι]{.greek-omitted} [απελυσεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τον]{.greek-omitted} [βαραββαν]{.greek-omitted} [και]{.greek-omitted} παρεδωκεν τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγγελωσας]{.greek-added} ινα [σταυρωθη]{.greek-abbr}[15:15 | instance no. 2]{.aside}

οι δε [στρατιωται]{.greek-omitted} [στρατειωται]{.greek-added} απηγαγον αυτον [εσω]{.greek-omitted} [εως]{.greek-added} της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [πραιτωριον]{.greek-omitted} [πραιτοριον]{.greek-added} και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον [αυτου]{.greek-omitted} [αυτω]{.greek-added} την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον [[αυτω]{.corr}]{.greek-added} [τα]{.greek-omitted} [ιματια]{.greek-omitted} τα ιδια [ιματια]{.greek-added} [αυτου]{.greek-added} και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και αγγαρευουσιν παραγοντα τινα [σιμωνα]{.greek-omitted} [σιμονα]{.greek-added} [κυρηναιον]{.greek-omitted} [κυριναιον]{.greek-added} ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ ελαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον [διαμεριζονται]{.greek-omitted} [διεμεριζοντο]{.greek-added} τα ιματια αυτου [βαλλοντες]{.greek-omitted} [βαλοντες]{.greek-added} κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην [η]{.greek-omitted} [επιγραφη]{.greek-omitted} [της]{.greek-omitted} [αιτιας]{.greek-omitted} [αυτου]{.greek-omitted} [επιγεγραμμενη]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted}[15:26]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26 | instance no. 2]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν [αυτον]{.greek-omitted} [αυτω]{.greek-added} κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} προς αλληλους μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελεγον αλλους εσωσεν εαυτον ου δυναται [σωσαι]{.greek-omitted} [σωσε]{.greek-added}[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα [ιδωμεν]{.greek-omitted} [ιδομεν]{.greek-added} και πιστευσωμεν αυτω και οι [συνεσταυρωμενοι]{.greek-abbr} αυτω [ωνειδιζον]{.greek-omitted} [ονειδιζον]{.greek-added} [αυτον]{.greek-omitted} [αυτω]{.greek-added}[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη [ωρα]{.greek-omitted} [τη]{.greek-omitted} [ενατη]{.greek-omitted} [εννατη]{.greek-added} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι λιμα [σαβαχθανι]{.greek-omitted} [σαβαχθανει]{.greek-added} ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου [εις]{.greek-omitted} [ινα]{.greek-added} τι με [εγκατελιπες]{.greek-omitted} [εγκατελειπας]{.greek-added}[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον [ιδου]{.greek-omitted} [ιδε]{.greek-added} ηλιαν [φωνει]{.greek-omitted} [φωνη]{.greek-added}[15:35]{.aside}

[δρα]{.greek-added} [δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γεμισας]{.greek-omitted} [σπογγον]{.greek-omitted} [οξους]{.greek-omitted} [περιθεις]{.greek-omitted} [τε]{.greek-omitted} [καλαμω]{.greek-omitted} [εποτιζεν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [ιδωμεν]{.greek-omitted} [ει]{.greek-omitted} [ερχεται]{.greek-omitted} [ηλιας]{.greek-omitted} [καθελειν]{.greek-omitted} [αυτον]{.greek-omitted}[15:36]{.aside}

[δραμων]{.greek-omitted} [μων]{.greek-added} δε εις και [γεμισας]{.greek-omitted} [γεμησας]{.greek-added} σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε [ιδωμεν]{.greek-omitted} [ιδομεν]{.greek-added} [ει]{.greek-omitted} [η]{.greek-added} ερχεται ηλιας [καθελ[η]{.unclear}ν]{.greek-added} [καθελειν]{.corr} αυτον[15:36 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο [παρεστηκως]{.greek-omitted} [παρεστικως]{.greek-added} εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος υιος ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν [θεωρουσαι]{.greek-omitted} [θεορουσαι]{.greek-added} εν αις ην [και]{.greek-omitted} μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

[αι]{.greek-omitted} και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμ[α]{.unclear}[15:41]{.aside}

και [ηδη]{.greek-omitted} [ειδη]{.greek-added} οψιας γενομενης επει ην παρασκευη ο εστιν [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

ηλθεν ιωσηφ [ο]{.greek-omitted} απο [αριμαθαιας]{.greek-omitted} [αριμαθειας]{.greek-added} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας εισηλθεν προς πιλατον και [ητησατο]{.greek-omitted} [ητισατο]{.greek-added} το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκεν και [προσκα]{.greek-added} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [κεντυριωνα]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ει]{.greek-omitted} [παλαι]{.greek-omitted} [απεθανεν]{.greek-omitted}[15:44]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [εθαυμασεν]{.greek-omitted} [ει]{.greek-omitted} [ηδη]{.greek-omitted} [τεθνηκεν]{.greek-omitted} [και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [λεσαμενος]{.greek-added} τον κεντυριωνα επηρωτησεν αυτον ει [παλαι]{.greek-omitted} [απεθανεν]{.greek-omitted} [ηδη]{.greek-added} [τεθνηκεν]{.greek-added}[15:44 | instance no. 2]{.aside}

και γνους απο του κεντυριωνος εδωρησατο [το]{.greek-omitted} [τω]{.greek-added} σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον ενειλησεν τη [σινδονι]{.greek-omitted} [σινδονα]{.greek-added} και [κατεθηλων]{.greek-added} [κατεθηκεν]{.corr} αυτον εν [μνημειω]{.greek-omitted} [μνημιω]{.greek-added} ο ην [λελατομημενον]{.greek-omitted} [λαιλατομημενον]{.greek-added} εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυνησεν]{.greek-added} λιθον επι την θυραν του [μνημειου]{.greek-omitted} [μνημιου]{.greek-added}[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [ιωση]{.greek-omitted} [ηακωβου]{.greek-added} [και]{.greek-added} [σαλωμη]{.greek-added} [εθεωρουν]{.greek-omitted} [εθεορουν]{.greek-added} που [τιθεται]{.greek-omitted} [τεθηται]{.greek-added}[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι [αλειψωσιν]{.greek-omitted} [αλιψωσι]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[16:1]{.aside}

και λιαν πρωι της μιας σαββατων [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς [εαυτας]{.greek-omitted} [εαυτους]{.greek-added} τις αποκυλισει ημιν τον λιθον εκ της θυρας του [μνημειου]{.greek-omitted} [μνημιου]{.greek-added}[16:3]{.aside}

και αναβλεψασαι [θεωρουσιν]{.greek-omitted} [θεορουσιν]{.greek-added} οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον [ειδον]{.greek-omitted} [ιδον]{.greek-added} νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και [εξεθαμβηθησαν]{.greek-omitted} [εξεθαυβηθησαν]{.greek-added}[16:5]{.aside}

ο δε λεγει [αυταις]{.greek-omitted} [μη]{.greek-omitted} [εκθαμβεισθε]{.greek-omitted} [ιησουν]{.greek-omitted} [ζητειτε]{.greek-omitted} [τον]{.greek-omitted} [ναζαρηνον]{.greek-omitted} [τον]{.greek-omitted} [εσταυρωμενον]{.greek-omitted} [ηγερθη]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [ωδε]{.greek-omitted} [ιδε]{.greek-omitted} [ο]{.greek-omitted} [τοπος]{.greek-omitted} [οπου]{.greek-omitted} [εθηκαν]{.greek-omitted} [αυτον]{.greek-omitted}[16:6]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [λεγει]{.greek-omitted} αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβεισθαι]{.greek-added} [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [ναζωρινον]{.greek-added} τον [[εσταυρωμενον]{.greek-abbr}]{.greek-added} [[εσταυρωμενον]{.greek-abbr}]{.corr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6 | instance no. 2]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του [μνημειου]{.greek-omitted} [μνημιου]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} [εφανη]{.greek-omitted} [εφανει]{.greek-added} πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ [ης]{.greek-omitted} [εις]{.greek-added} εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα απηγγειλεν [τοις]{.greek-omitted} [της]{.greek-added} μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

[κακεινοι]{.greek-omitted} [εκεινοι]{.greek-added} ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον [δε]{.greek-added} ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ονειδησεν]{.greek-added} την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον [ουκ]{.greek-omitted} [ου]{.greek-added} [επιστευσαν]{.greek-omitted}[16:14]{.aside}

[κ]{.greek-added} [υστερον]{.greek-omitted} [ανακειμενοις]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-omitted} [ενδεκα]{.greek-omitted} [εφανερωθη]{.greek-omitted} [και]{.greek-omitted} [ωνειδισεν]{.greek-omitted} [την]{.greek-omitted} [απιστιαν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [σκληροκαρδιαν]{.greek-omitted} [οτι]{.greek-omitted} [τοις]{.greek-omitted} [θεασαμενοις]{.greek-omitted} [αυτον]{.greek-omitted} [εγηγερμενον]{.greek-omitted} [ουκ]{.greek-omitted} επιστευσαν[16:14 | instance no. 2]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον [παση]{.greek-omitted} [πασι]{.greek-added} τη [κτισει]{.greek-omitted} [κτησει]{.greek-added}[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια εκβαλουσιν γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησωσι]{.greek-added} [καιναις]{.greek-omitted} [κενες]{.greek-added}[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως [εξουσιν]{.greek-omitted} [εξουσι]{.greek-added}[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [εν]{.greek-added} [δεξια]{.greek-added} του [θεου]{.greek-omitted} [[πατρος]{.greek-abbr}]{.greek-added}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

