---
title: "Collation of Byz^RP^ vs 31043 (1043)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1043 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31043).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1043                                   	| λογος                              	|
| 1043 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1043 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1043               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1043                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1043 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1043                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

βιβλος γενεσεως [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου [δαυιδ]{.greek-abbr} υιου αβρααμ[1:1]{.aside}

αβρααμ [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ ισαακ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιουδαν και τους αδελφους αυτου[1:2]{.aside}

ιουδας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον φαρες και τον ζαρα εκ της θαμαρ φαρες δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εσρωμ εσρωμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αραμ[1:3]{.aside}

αραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [αμιναδαβ]{.greek-omitted} [αμιναδαμ]{.greek-added} [αμιναδαβ]{.greek-omitted} [αμιναδαμ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ναασσων]{.greek-omitted} [ναασων]{.greek-added} [ναασσων]{.greek-omitted} [ναασων]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλμων[1:4]{.aside}

σαλμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον βοοζ εκ της ραχαβ βοοζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ωβηδ εκ της ρουθ ωβηδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεσσαι[1:5]{.aside}

ιεσσαι δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [δαυιδ]{.greek-abbr} τον βασιλεα [δαυιδ]{.greek-abbr} δε ο βασιλευς [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [σολομωνα]{.greek-omitted} [σολομωντα]{.greek-added} εκ της του ουριου[1:6]{.aside}

σολομων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ασα[1:7]{.aside}

ασα δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσαφατ ιωσαφατ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον οζιαν[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωαθαμ ιωαθαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχαζ αχαζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εζεκιαν[1:9]{.aside}

εζεκιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [μανασση]{.greek-omitted} [μανασσην]{.greek-added} μανασσης δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμων αμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ιεχονιαν]{.greek-omitted} [ιεχωνιαν]{.greek-added} και τους αδελφους αυτου επι της μετοικεσιας βαβυλωνος[1:11]{.aside}

μετα δε την μετοικεσιαν βαβυλωνος [ιεχονιας]{.greek-omitted} [ιεχωνιας]{.greek-added} [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλαθιηλ σαλαθιηλ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβιουδ αβιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιακειμ ελιακειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχειμ αχειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελεαζαρ ελεαζαρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

πασαι ουν αι γενεαι απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεα[ι]{.unclear} [δε]{.greek-supplied}κατεσσαρες και απο [δαυιδ]{.greek-abbr} εως της μετοικεσιας βαβυλωνος γενεαι δεκατεσσαρες και απο της μετοικεσιας βαβυλωνος εως του [χριστου]{.greek-abbr} γενεαι δεκατεσσαρες[1:17]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η γεννησις ουτως ην μνηστευθεισης γαρ της [μητρος]{.greek-abbr} αυτ[ου]{.greek-supplied} μαριας τω ιωσηφ πριν η συνελθειν αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων [παραδειγματισαι]{.greek-added} αυτην [παραδειγματισαι]{.greek-omitted} εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ εφανη αυτω λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη φοβηθης παραλαβειν [μαριαμ]{.greek-omitted} [μαριαν]{.greek-added} την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

τεξεται δε υιον και καλεσεις το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ σωσει τον λαον αυτου [απο]{.greek-omitted} [των]{.greek-omitted} [αμαρτιων]{.greek-omitted} [αυτων]{.greek-omitted}[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται υιον και [καλεσουσιν]{.greek-omitted} [καλεσουσι]{.greek-added} το ονομα αυτου εμμανουηλ ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε [ο]{.greek-omitted} ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον υιον αυτης τον [πρωτοτοκον]{.greek-omitted} [πρωτοκον]{.greek-added} και [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} το ονομα αυτου ιησουν[1:25]{.aside}

### Chapter 2

του δε [ιησου]{.greek-abbr} γεννηθεντος εν βηθλεεμ της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων ειδομεν γαρ [αυτου]{.greek-omitted} τον αστερα [αυτου]{.greek-added} εν τη ανατολη και ηλθομεν προσκυνησαι [αυτω]{.greek-omitted} [αυτων]{.greek-added}[2:2]{.aside}

ακουσας δε ηρωδης ο βασιλευς εταραχθη και πασα ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και γραμματεις του λαου επυνθανετο παρ αυτων που ο [χριστος]{.greek-abbr} γεν[ν]{.unclear}αται[2:4]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ουδαμως ελαχιστη ει εν τοις ηγεμοσιν ιουδα εκ σου γαρ εξελευσεται ηγουμενος οστις ποιμανει τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω [αυτω]{.greek-omitted} [αυτο]{.greek-added}[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ [ον]{.greek-omitted} [ειδον]{.greek-omitted} εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα εχαρησαν χ[α]{.unclear}ραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες εις την οικιαν ειδον το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και πεσοντες προσεκυνησαν αυτω [[αυτον]{.corr}]{.greek-added} και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ οναρ [μη]{.greek-supplied} ανακαμψαι προς ηρωδην δι αλλης [οδο]{.greek-supplied}υ ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

[αναχ]{.greek-supplied}ωρησαντων δε αυτων ιδου αγγελος [[κυριου]{.greek-abbr}]{.greek-supplied} [φαινεται]{.greek-omitted} κατ οναρ [φαινεται]{.greek-added} τω ιωσηφ λεγων [εγερ]{.greek-supplied}θεις παραλαβε το παιδιον και [την]{.greek-supplied} [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον υιον μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη λιαν και αποστειλας [ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} παντας τους παιδας τους εν βηθλεεμ και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις οριοις αυτης απο διετους και κατωτερω κατα τον χρονον ον [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρα των μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν υπο ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη [γαρ]{.greek-added} [φησιν]{.greek-added} εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ φαινεται τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} [τεθνηκασιν]{.greek-omitted} [τεθνηκασι]{.greek-added} γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει επι της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

[και]{.greek-omitted} ελθων [δε]{.greek-added} κατωκησεν εις πολιν λεγομενην ναζαρετ οπως πληρωθη το ρηθεν δια των προφητων οτι [ναζωραιος]{.greek-omitted} [ναζοραιος]{.greek-added} κληθησεται[2:23]{.aside}

### Chapter 3

εν δε ταις ημεραις εκειναις παραγινεται ιωαννης ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

και λεγων [μετα]{.greek-added} [μετανοειτε]{.greek-omitted} [νοειτε]{.greek-added} [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

ουτος γαρ εστιν ο ρηθεις υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [του]{.greek-added} [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε ο [ιωαννης]{.greek-abbr} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το ενδυμα αυτου [απο]{.greek-omitted} [εκ]{.greek-added} τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε [εξεπορευετο]{.greek-omitted} [εξεπορευθη]{.greek-added} προς αυτον ιεροσολυμα και πασα [η]{.greek-omitted} ιουδαια και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο εν τω ιορδανη [ποταμω]{.greek-added} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} εξομολογουμενοι τας αμαρτιας αυτ[ω]{.unclear}ν[3:6]{.aside}

ιδων δε πολλους των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και [σαδδουκαιων]{.greek-omitted} [σαδουκαιων]{.greek-added} ερχομενους επι το βαπτισμα αυτου ειπεν αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν [καρπον]{.greek-omitted} [καρπους]{.greek-added} [αξιον]{.greek-omitted} [αξιους]{.greek-added} της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν εαυτοις [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} [και]{.greek-added} εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ[3:9]{.aside}

### Chapter 4

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και [ιστησιν]{.greek-omitted} [εστησεν]{.greek-added} αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει υιος [ει]{.greek-omitted} του [θεου]{.greek-abbr} [βαλε]{.greek-omitted} [σεαυτον]{.greek-omitted} [κατω]{.greek-omitted} [γεγραπται]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [τοις]{.greek-omitted} [αγγελοις]{.greek-omitted} [αυτου]{.greek-omitted} [εντελειται]{.greek-omitted} [περι]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [χειρων]{.greek-omitted} [αρουσιν]{.greek-omitted} [σε]{.greek-omitted} [μηποτε]{.greek-omitted} [προσκοψης]{.greek-omitted} [προς]{.greek-omitted} [λιθον]{.greek-omitted} [τον]{.greek-omitted} [ποδα]{.greek-omitted} [σου]{.greek-omitted}[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} παλιν γεγραπται ουκ εκπειρασεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν παραλαμβανει αυτον ο διαβολος εις ορος υψηλον λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται [γαρ]{.greek-omitted} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω μονω λατρευσεις[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβο[λος]{.greek-supplied} και ιδου αγγελοι προσηλθον και διηκονου[ν]{.greek-supplied} α[υ]{.unclear}[τω]{.greek-supplied}[4:11]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} οτι [ιωαννης]{.greek-abbr} παρεδοθη ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την ναζαρετ ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και νεφθαλειμ[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη νεφθαλειμ οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} [φως]{.greek-omitted} [μεγα]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [καθημενοις]{.greek-omitted} [εν]{.greek-omitted} [χωρα]{.greek-omitted} και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε [ηρξατο]{.greek-omitted} ο [ιησους]{.greek-abbr} [ηρξατο]{.greek-added} κηρυσσειν και λεγειν μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} δυο αδελφους σιμωνα τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω [υμας]{.greek-omitted} [ημας]{.greek-added} αλιεις [ανθρωπων]{.greek-abbr}[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν ειδεν αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων [καταρτιζοντας]{.greek-omitted} [καταρτιζοντες]{.greek-added} τα δικτυα αυτων [και]{.greek-omitted} [εκαλεσεν]{.greek-omitted} [αυτους]{.greek-omitted}[4:21]{.aside}

οι δε [ευθεως]{.greek-omitted} αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ολην την γαλιλαιαν [ο]{.greek-omitted} [ιησους]{.greek-omitted} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και [απηλθεν]{.greek-omitted} [εξηλθεν]{.greek-added} η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και [βασανοις]{.greek-omitted} [συνεχομενους]{.greek-omitted} [και]{.greek-omitted} [δαιμονιζομενους]{.greek-omitted} [και]{.greek-omitted} σεληνιαζομενους και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον αυτω οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους [λεγων]{.greek-omitted}[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθησονται[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομισουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι πεινωντες και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

μακαριοι οι ελεημονες οτι αυτοι ελεηθησοντ[αι]{.greek-supplied}[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η [βασειλεια]{.greek-added} [βασιλεια]{.corr} των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι εστε οταν ονειδισωσιν υμας και διωξωσιν και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ [η]{.greek-added} [υμων]{.corr} ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις [ουρανοις]{.greek-abbr} ουτως γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το αλας της γης εαν δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και τιθεασιν [αυτον]{.greek-omitted} υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων εμπροσθεν των [ανθρωπων]{.greek-abbr} οπως ιδωσιν υμων τα καλα εργα και [δοξασωσιν]{.greek-omitted} [δοξασωσι]{.greek-added} τον [πατερα]{.greek-abbr} [η]{.greek-added} [υμων]{.corr} τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην [γαρ]{.greek-omitted} [αμην]{.greek-added} λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη [η]{.greek-added} ιωτα εν η μια κεραια ου μη παρελθη απο του νομου εως αν παντα γενηται[5:18]{.aside}

ος εαν [ουν]{.greek-omitted} λυση μιαν των εντολων τουτων των ελαχιστων και διδαξη ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν ποιηση και διδαξη ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση η δικαιοσυνη υμων πλειον των γραμματεων και φαρισαιων ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν [φονευσει]{.greek-added} [φονευση]{.corr} ενοχος εσται τη κρισει[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν ειπη τω αδελφω αυτου ρακα ενοχος εσται τω συνεδριω ος δ αν ειπη [τω]{.greek-added} [αδελφω]{.greek-added} [αυτου]{.greek-added} μωρε ενοχος εσται εις την γεενναν του πυρος[5:22]{.aside}

εαν ουν προσφερης το δωρον σου επι το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην βληθηση[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως [αν]{.greek-omitted} [ου]{.greek-added} αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα προς το επιθυμησαι [αυτην]{.greek-omitted} [αυτης]{.greek-added} ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

[ει]{.greek-omitted} [εαν]{.greek-added} δε ο οφθαλμος σου ο δεξιος [σκανδαλιζει]{.greek-omitted} [σκανδαλιζη]{.greek-added} σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολ[υ]{.unclear}ται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ σκανδαλιζει σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ [σο]{.greek-supplied}ι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη [δε]{.greek-omitted} οτι ος αν απολυση την γυναικα αυτου δοτω αυτη αποστασιον[5:31]{.aside}

εγω δε λεγω υμιν [πας]{.greek-added} [ο]{.greek-added} [απολυων]{.greek-added} [οτι]{.greek-omitted} [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} την γυναικα αυτου παρεκτος λογου πορνειας ποιει αυτην μοιχασθαι και ος εαν απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε τω [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη ομοσαι ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον [εστιν]{.greek-omitted} [εστι]{.greek-added} των ποδων αυτου μητε εις ιεροσολυμα οτι πολις [εστιν]{.greek-omitted} [εστι]{.greek-added} του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου ομοσης οτι ου δυνασαι μιαν τριχα λευκην η μελαιναν ποιησαι[5:36]{.aside}

εστω δε ο λογος [η]{.greek-added} [υμων]{.corr} ναι ναι ου ου το δε [περισσον]{.greek-omitted} [περιττον]{.greek-added} τουτων εκ του πονηρου [εστιν]{.greek-omitted} [εστι]{.greek-added}[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω αλλ οστις σε ραπισει [επι]{.greek-omitted} [εις]{.greek-added} την δεξιαν σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και τω θελοντι σοι κριθηναι και τον χιτωνα σου λαβειν αφες αυτω και το ιματιον[5:40]{.aside}

και οστις σε αγγαρευσει μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω αιτουντι σε διδου και τον θελοντα απο σου δανεισασθαι μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και μισησεις τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων ευλογειτε τους [καταρωμενους]{.greek-omitted} [ταταρωμενους]{.greek-added} υμας καλως ποιειτε τοις μισουσι[ν]{.greek-supplied} υμας και προσευχεσθε υπερ των επηρεαζοντων [υμας]{.greek-omitted} και διωκοντων [[διωκουντων]{.corr}]{.greek-added} υμας[5:44]{.aside}

οπως γενησθε υιοι του [πατρος]{.greek-abbr} υμων του εν τοις [ουρανοις]{.greek-abbr} οτι τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ [αγαπησητε]{.greek-omitted} [αγαπατε]{.greek-added} τους αγαπωντας υμας τινα μισθον εχετε ουχι και οι τελωναι το αυτο ποιουσιν[5:46]{.aside}

και εαν [ασπασησθε]{.greek-omitted} [ασπαζησθε]{.greek-added} τους φιλους υμων μονον τι περισσον ποιειτε ουχι και οι τελωναι ουτως ποιουσιν[5:47]{.aside}

εσεσθε ουν υμεις τελειοι ωσπερ ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} τελειος εστιν[5:48]{.aside}

### Chapter 6

προσεχετε την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις ουρανοις[6:1]{.aside}

οταν ουν ποιης ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν [οτι]{.greek-added} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω [αυτος]{.greek-omitted} αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται οτι φιλουσιν εν ταις συναγωγαις και εν ταις γωνιαις των πλατειων εστωτες [προσευχεσθαι]{.greek-omitted} [προσευχονται]{.greek-added} οπως αν [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το [ταμιειον]{.greek-omitted} [ταμειον]{.greek-added} σου και κλεισας την θυραν [σου]{.greek-omitted} [προσευξαι]{.greek-omitted} [προσευξε]{.greek-added} τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη βαττολογησητε ωσπερ οι εθνικοι [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ [οτι]{.greek-omitted} εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν ομοιωθητε αυτοις [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} υμων ων χρειαν εχετε προ του υμας αιτησαι αυτον[6:8]{.aside}

ουτως ουν προσευχεσθε [υμεις]{.greek-omitted} [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το ονομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων ως και ημεις [αφιεμεν]{.greek-omitted} [αφιομεν]{.greek-added} τοις οφειλεταις ημων[6:12]{.aside}

και μη εισενεγκης ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η [δυναμις]{.greek-omitted} [δυμαμις]{.greek-added} και η δοξα εις τους [αιωνας]{.greek-omitted} [ανωνας]{.greek-added} αμην[6:13]{.aside}

εαν [γαρ]{.greek-omitted} αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο [ουρανιος]{.greek-abbr}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων [ο]{.greek-added} [[ουρανιος]{.greek-abbr}]{.greek-added} αφησει τα παραπτωματα υμων[6:15]{.aside}

οταν δε νηστευητε μη γινεσθε ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην [αμην]{.greek-added} λεγω υμιν [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων [αλειψαι]{.greek-omitted} [αλειψε]{.greek-added} σου την κεφαλην και το προσωπον σου [νιψαι]{.greek-omitted} [νηψε]{.greek-added}[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι[6:18]{.aside}

μη θησαυριζετε υμιν θησαυρους επι της γης οπου σης και βρωσις αφανιζει και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορυσσουσι]{.greek-added} [και]{.greek-omitted} [κλεπτουσιν]{.greek-omitted}[6:19]{.aside}

[θησαυριζετε]{.greek-omitted} [θησαυριζεται]{.greek-added} δε υμιν θησαυρους εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} οπου ουτε σης ουτε βρωσις αφανιζει και οπου κλεπται ου διορυσσουσιν [ουδε]{.greek-omitted} [κλεπτουσιν]{.greek-omitted}[6:20]{.aside}

οπου γαρ [εστιν]{.greek-omitted} ο θησαυρος υμων εκει [εσται]{.greek-omitted} και η καρδια υμων [εσται]{.greek-added}[6:21]{.aside}

[ο]{.unclear} [λυχν]{.unclear}ος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους η ολον το σωμα σου φωτεινον εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος [εστιν]{.greek-omitted} το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η [του]{.greek-added} ενος ανθεξεται και του ετερου καταφρονησει [ου]{.greek-omitted} [δυνασθε]{.greek-omitted} [θεω]{.greek-omitted} [δουλευειν]{.greek-omitted} [και]{.greek-omitted} [μαμωνα]{.greek-omitted}[6:24]{.aside}

δια τουτο λεγω υμιν μη μεριμνατε τη ψυχη υμων τι [φαγητε]{.greek-omitted} [φαγετε]{.greek-added} [και]{.greek-omitted} [η]{.greek-added} τι [π[―]{.gap}τε]{.greek-added} [πιητε]{.greek-omitted} [[πιετε]{.corr}]{.greek-added} μηδε τω σωματι υμων τι [ενδυσησθε]{.greek-omitted} [ενδυσεσθε]{.greek-added} ουχι η ψυχη πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα πετεινα του [ουρανου]{.greek-abbr} οτι ου σπειρουσιν ουδε θεριζουσιν ουδε συναγουσιν εις αποθηκας και ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο [ουρανιος]{.greek-abbr} τρεφει αυτα ουχ υμεις μαλλον διαφερετε αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται προσθειναι επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε νηθει[6:28]{.aside}

λεγω δε υμιν οτι ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλομενον ο [θεος]{.greek-abbr} ουτως [αμφι]{.greek-added} [αμφιεννυσιν]{.greek-omitted} [εννυσιν]{.greek-added} ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν μεριμνησητε λεγοντες τι φαγωμεν η τι πιωμεν η τι [περιβαλωμεθα]{.greek-omitted} [περιβαλλωμεθα]{.greek-added}[6:31]{.aside}

[ταυτα]{.greek-added} [γαρ]{.greek-added} παντα [γαρ]{.greek-omitted} [ταυτα]{.greek-omitted} τα εθνη επιζητει [οιδεν]{.greek-omitted} [ιδε]{.greek-added} γαρ ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο [ουρανιος]{.greek-abbr} [οτι]{.greek-omitted} [ων]{.greek-added} [χρηζεται]{.greek-added} [χρηζετε]{.corr} [τουτων]{.greek-omitted} [απαντων]{.greek-omitted}[6:32]{.aside}

ζητειτε δε [πρωτον]{.greek-omitted} την βασιλειαν του [θεου]{.greek-abbr} και την δικαιοσυνην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν μεριμνησητε εις την αυριον η γαρ αυριον μεριμνησει τα εαυτης αρκετον τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

μη κρινετε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε κριθησ[εσθε]{.unclear} και εν ω μετρω μετρειτε μετρηθησεται υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος [το]{.greek-omitted} [τω]{.greek-added} εν τω οφθαλμω του αδελφου σου την δε εν τω [σω]{.greek-omitted} οφθαλμω [σου]{.greek-added} δοκον ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες [εκβαλω]{.greek-omitted} [εκβαλλω]{.greek-added} το καρφος απο του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη [δωτε]{.greek-omitted} [δοτε]{.greek-added} [το]{.greek-omitted} [αγιον]{.greek-omitted} [τα]{.greek-added} [αγια]{.greek-added} τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε [βαλητε]{.greek-omitted} [βαλλητε]{.greek-added} τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε καταπατησωσιν αυτους εν τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

αιτειτε και δοθησεται υμιν ζητειτε και ευρησετε κρουετε και ανοιγησεται υμιν[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

[η]{.greek-omitted} τις εστιν [[ανθρωπος]{.greek-abbr}]{.greek-added} εξ υμων [ω]{.greek-added} [ανθρωπος]{.greek-omitted} [ον]{.greek-omitted} εαν [αιτηση]{.greek-omitted} [αιτησει]{.greek-added} ο υιος αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

και εαν ιχθυν αιτηση μη οφιν επιδωσει αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

παντα ουν οσα αν θελητε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} [ουτως]{.greek-omitted} και υμεις ποιειτε αυτοις [ουτος]{.greek-omitted} [ουτως]{.greek-added} γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

εισελθετε δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

τι στενη η πυλη και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

προσεχετε δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει [το]{.greek-omitted} [δε]{.greek-omitted} [σαπρον]{.greek-omitted} [δενδρον]{.greek-omitted} [καρπους]{.greek-omitted} [πονηρους]{.greek-omitted} [ποιει]{.greek-omitted}[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους [ποιειν]{.greek-omitted} [ουδε]{.greek-omitted} [δενδρον]{.greek-omitted} [σαπρον]{.greek-omitted} [καρπους]{.greek-omitted} [καλους]{.greek-omitted} [ποιειν]{.greek-omitted}[7:18]{.aside}

### Chapter 8

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και ανακλιθησονται μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} υπαγε και ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη [και]{.greek-added} [υποστρεψας]{.greek-added} [ο]{.greek-added} [εκατονταρχος]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [αυτου]{.greek-added} [εν]{.greek-added} [αυτη]{.greek-added} [τη]{.greek-added} [ωρα]{.greek-added} [ευρε]{.greek-added} [τον]{.greek-added} [παιδα]{.greek-added} [υγιαινοντα]{.greek-added}[8:13]{.aside}

και [ελθων]{.greek-omitted} [εισελθων]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις την οικιαν πετρου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} την πενθεραν αυτου βεβλημενην [πυρετω]{.greek-added} [και]{.greek-omitted} [πυρεσσουσαν]{.greek-omitted}[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα πνευματα λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου [λεγοντος]{.greek-omitted} αυτος τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν απερχη[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κλιναι]{.greek-added}[8:20]{.aside}

ετερος δε των μαθητων [αυτου]{.greek-omitted} ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον απελθειν [και]{.greek-omitted} θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω ακολουθει μοι και αφες τους νεκρους [θαψαι]{.greek-omitted} [θαψον]{.greek-added} τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις [το]{.greek-omitted} πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων αυτος δε [εκαθευδεν]{.greek-omitted} [εκαθευδε]{.greek-added}[8:24]{.aside}

και προσελθοντες οι μαθηται ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και λεγει αυτοις τι δειλοι εστε ολιγοπιστοι τοτε εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τοις ανεμοις και τη θαλασση και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

και [ελθοντι]{.greek-omitted} [ελθωντι]{.greek-added} αυτω εις το περαν εις την χωραν των γεργεσηνων υπηντησαν αυτω δυο δαιμονιζομενοι [εκ]{.greek-omitted} [των]{.greek-omitted} [μνημειων]{.greek-omitted} [εξερχομενοι]{.greek-omitted} [χαλεποι]{.greek-omitted} [λιαν]{.greek-omitted} [ωστε]{.greek-omitted} [μη]{.greek-omitted} [ισχυειν]{.greek-omitted} [τινα]{.greek-omitted} [παρελθειν]{.greek-omitted} [δια]{.greek-omitted} [της]{.greek-omitted} [οδου]{.greek-omitted} [εκεινης]{.greek-omitted}[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι [ημιν]{.greek-omitted} [υμιν]{.greek-added} και [συ]{.greek-added} [σοι]{.greek-omitted} [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων [πολλων]{.greek-omitted} βοσκομενη [[βοσκομενων]{.corr}]{.greek-added}[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει [εκβαλλεις]{.greek-omitted} [εκβαλεις]{.greek-added} ημας επιτρεψον ημιν απελθειν εις την αγελην των χοιρων[8:31]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [εξελθοντες]{.greek-omitted} [απηλθον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [αγελην]{.greek-omitted} [των]{.greek-omitted} [χοιρων]{.greek-omitted} και ιδου [ωρμησεν]{.greek-omitted} [ωρμησε]{.greek-added} πασα η αγελη των χοιρων κατα του κρημνου εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα [και]{.greek-omitted} τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις [το]{.greek-omitted} πλοιον [διεπερασεν]{.greek-omitted} [διεπερασε]{.greek-added} και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω παραλυτικω θαρσει τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι αμαρτιαι σου[9:2]{.aside}

και ιδου τινες των γραμματεων ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και [ιδων]{.greek-omitted} [ειδως]{.greek-added} ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις ενθυμεισθε πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι [γαρ]{.greek-omitted} εστιν ευκοπωτερον ειπειν [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σου]{.greek-omitted} [σο[ι]{.unclear}]{.greek-added} αι αμαρτιαι [σου]{.greek-added} η ειπειν εγειραι και περιπατει[9:5]{.aside}

ινα δε ειδητε οτι εξουσιαν [εχει]{.greek-omitted} [εχη]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} επι [της]{.greek-omitted} γης αφιεναι αμαρτιας [ειπε]{.greek-added} [τοτε]{.greek-omitted} [λεγει]{.greek-omitted} τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθε[ν]{.unclear} εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον [[θεον]{.greek-abbr}]{.greek-added} [τον]{.greek-added} δοντα εξουσιαν τοιαυτην τοις ανθρωποις[9:8]{.aside}

και παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} [καθημεν[ω]{.unclear}ν]{.greek-added} [καθημενον]{.corr} επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων εσθιει ο διδασκαλος υμων[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες [ιατρου]{.greek-omitted} [οιατρου]{.greek-added} αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι [εστιν]{.greek-omitted} [εστι]{.greek-added} [το]{.greek-added} ελεον θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται ιωαννου λεγοντες δια τι ημεις και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} νηστευομεν πολλα οι δε μαθηται σου ου νηστευουσιν[9:14]{.aside}

[και]{.greek-omitted} ειπεν [ουν]{.greek-added} αυτοις ο [ιησους]{.greek-abbr} [μη]{.greek-omitted} [ου]{.greek-added} δυνανται οι υιοι του νυμφωνος πενθειν εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε [νηστευσουσιν]{.greek-omitted} [νηστευσουσι]{.greek-added}[9:15]{.aside}

ουδεις δε επιβαλλει επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα [αυτου]{.greek-omitted} απο του ιματιου και χειρον σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος εκχειται [και]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [απολουνται]{.greek-omitted} αλλα βαλλουσιν οινον νεον εις ασκους καινους και [αμφοτεροι]{.greek-omitted} [αμφοτερα]{.greek-added} συντηρουνται[9:17]{.aside}

ταυτα αυτου λαλουντος αυτοις ιδου αρχων [τις]{.greek-added} [εις]{.greek-omitted} [ελθων]{.greek-omitted} προσεκυνει αυτω λεγων [οτι]{.greek-omitted} η θυγατηρ μου αρτι ετελευτησεν αλλα [ελθων]{.greek-omitted} [απελθων]{.greek-added} επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} ηκολουθησεν αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου [του]{.greek-omitted} [ιματιου]{.greek-omitted} αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον αψωμαι του ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} θαρσει θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και [εσωθη]{.greek-omitted} [ιαθη]{.greek-added} η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον [θορυβουμενον]{.greek-omitted} [θορυβουμενους]{.greek-added}[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε [δε]{.greek-omitted} [ουν]{.greek-added} [εξεβληθη]{.greek-omitted} [εξεβη]{.greek-added} ο οχλος εισελθων [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

και παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες [και]{.greek-omitted} [λεγοντες]{.greek-omitted} ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

ελθοντι δε εις την οικιαν προσηλθον αυτω οι τυφλοι και λεγει αυτοις ο [ιησους]{.greek-abbr} πιστευετε οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων αυτων λεγων κατα την πιστιν υμων γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες [διεφημισαν]{.greek-omitted} [διεφημησαν]{.greek-added} αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων [ιδου]{.greek-omitted} προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και εκβληθεντος του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες ουδεποτε εφανη ουτως εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ελεγον εν τω αρχον[τι]{.greek-supplied} των δαιμονιων εκβαλλει τα δαιμον[ια]{.greek-supplied}[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολεις [πασας]{.greek-omitted} και τας κωμας διδασκων εν ταις συναγωγαις [αυτων]{.greek-omitted} και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[9:35]{.aside}

ιδων δε τους οχλους εσπλαγχνισθη [περι]{.greek-omitted} [αυτων]{.greek-omitted} [επ]{.greek-added} [αυτους]{.greek-added} οτι ησαν εσκυλμενοι και [ερριμμενοι]{.greek-omitted} [ερριμενοι]{.greek-added} ωσει προβατα μη εχοντα ποιμ[ενα]{.unclear}[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

και προσκαλεσαμενος τους δωδεκα μαθητας αυτου εδωκεν αυτοις εξουσιαν [κατα]{.greek-added} [πνευματων]{.greek-abbr} ακαθαρτων ωστε [αυτα]{.greek-added} εκβαλλειν [αυτα]{.greek-omitted} και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

των δε δωδεκα αποστολων τα ονοματα [εστιν]{.greek-omitted} [εισι]{.greek-added} ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου ιακωβος ο του ζεβεδαιου και [ιωαννης]{.greek-abbr} ο αδελφος αυτου[10:2]{.aside}

φιλιππος [και]{.greek-omitted} βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και [λεββαιος]{.greek-omitted} [λεβαιοις]{.greek-added} ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο κανανιτης και ιουδας [ο]{.greek-added} ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους δωδεκα [αποστολους]{.greek-added} απεστειλεν ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν σαμαρειτων μη εισελθητε[10:5]{.aside}

πορευεσθε δε μαλλον προς τα προβατα τα απολω[λ]{.unclear}ο[τα]{.unclear} οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρυσσετε λεγοντες οτι ηγγικεν η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας θεραπευετε λεπρους καθαριζετε δαιμονια εκβαλλετε δωρεαν ελαβετε δωρεαν δοτε[10:8]{.aside}

μη κτησησθε χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε ραβδους αξιος γαρ ο εργατης της τροφης αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added}[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις εν αυτη αξιος [εστιν]{.greek-omitted} [εστι]{.greek-added} κακει μεινατε εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν ασπασασθε αυτην[10:12]{.aside}

και εαν μεν η η οικια αξια [ελθετω]{.greek-omitted} [εστω]{.greek-added} η ειρηνη υμων επ αυτην εαν δε μη η αξια η ειρηνη υμων προς υμας [επιστραφητω]{.greek-omitted} [επαναστραφητω]{.greek-added}[10:13]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι [εκ]{.greek-added} της οικιας [η]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} εκεινης εκτιναξατε τον κονιορτον των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν ανεκτοτερον εσται γη σοδομων και γομορρων εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων γινεσθε ουν φρονιμοι [ωσει]{.greek-added} [ως]{.greek-omitted} [οι]{.greek-omitted} οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι ηγεμονας δε και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε [παραδιδωσιν]{.greek-omitted} [παραδωσουσιν]{.greek-added} υμας μη μεριμνησητε πως η τι λαλησητε δοθησεται γαρ υμιν εν εκεινη τη ωρα τι λαλησετε[10:19]{.aside}

ου γαρ υμεις εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [μου]{.greek-added} το λαλουν εν υμιν[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[10:22]{.aside}

οταν δε διωκωσιν υμας εν τη πολει ταυτη φευγετε εις την αλλην αμην [γαρ]{.greek-omitted} λεγω υμιν ου μη τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο υιος του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης υπερ τον διδασκαλον ουδε δουλος υπερ τον κυριον αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα γενηται ως ο διδασκαλος αυτου και ο δουλος ως ο κυριος αυτου ει [ουν]{.greek-added} τον οικοδεσποτην βεελζεβουλ [εκαλεσαν]{.greek-omitted} [απεκαλεσαν]{.greek-added} ποσω μαλλον τους οικειακους αυτου[10:25]{.aside}

μη ουν φοβηθητε αυτους ουδεν γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} κεκαλυμμενον ο ουκ αποκαλυφθησεται και κρυπτον ο ου γνωσθησεται[10:26]{.aside}

[ο]{.unclear} λεγω υμιν εν τη σκοτια ειπατε εν τω φωτι και ο εις το ους [ακουετε]{.greek-omitted} [ηκουσατε]{.greek-added} κηρυξατε επι των δωματων[10:27]{.aside}

και μη [φοβεισθε]{.greek-omitted} [φοθητε]{.greek-added} απο των αποκτενοντων το σωμα την δε ψυχην μη δυναμενων αποκτειναι φοβηθητε δε μαλλον τον δυναμενον [και]{.greek-omitted} [την]{.greek-omitted} ψυχην και [το]{.greek-omitted} σωμα απολεσαι εν γεεννη[10:28]{.aside}

ουχι δυο στρουθια ασσαριου πωλειται και εν εξ αυτων ου πεσειται επι την γην ανευ του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [μου]{.greek-added}[10:29]{.aside}

υμων δε και αι τριχες της κεφαλης πασαι ηριθμημεναι [εισιν]{.greek-omitted} [εισι]{.greek-added}[10:30]{.aside}

μη ουν φοβηθητε πολλων στρουθιων διαφερετε υμεις[10:31]{.aside}

πας ουν οστις ομολογησει εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[10:32]{.aside}

μη νομισητε οτι ηλθον βαλειν ειρηνην επι την γην ουκ ηλθον βαλειν ειρηνην αλλα μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και θυγατερα κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και εχθροι του [ανθρωπου]{.greek-abbr} οι οικειακοι αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος και ο φιλων υιον η θυγατερα υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:38]{.aside}

ο ευρων την ψυχην [αυ]{.unclear}του απολεσει αυτην και ο απολεσ[ας]{.unclear} την ψυχην αυτου ενεκεν [ε]{.unclear}μου [ευρησει]{.greek-omitted} [απολεσει]{.greek-added} αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται [και]{.greek-omitted} ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψεται[10:41]{.aside}

και ος εαν [ποτιση]{.greek-omitted} [ποτηση]{.greek-added} ενα των μικρων [τουτων]{.greek-omitted} ποτηριον [ψυχρου]{.greek-omitted} [ψυχρουν]{.greek-added} μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} [διατασσων]{.greek-omitted} [διδασκων]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} δωδεκα [μαθηταις]{.greek-omitted} [μαθητας]{.greek-added} αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε [ιωαννης]{.greek-abbr} ακουσας εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-abbr} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

[και]{.greek-omitted} αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-added} [αυτοις]{.corr} πορευθεντες απαγγειλατε [ιωαννη]{.greek-abbr} α ακουετε και [α]{.greek-added} βλεπετε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται και κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο [ο]{.greek-omitted} [ιησους]{.greek-omitted} λεγειν τοις οχλοις περι [ιωαννου]{.greek-abbr} τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι εξηλθετε ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των βασιλειων εισιν[11:8]{.aside}

αλλα τι εξηλθετε ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

α[μ]{.greek-supplied}[ην]{.unclear} λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων μειζων ιωαννου του βαπτιστου ο δε μικροτερος εν τη βασιλεια των [ουρανων]{.greek-abbr} μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων [ιωαννου]{.greek-abbr} του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως [ιωαννου]{.greek-abbr} [προεφητευσαν]{.greek-omitted} [κρεμανται]{.greek-added}[11:13]{.aside}

και ει θελετε δεξασ[θαι]{.unclear} αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις [καθημενοις]{.greek-added} εν [αγοραις]{.greek-omitted} [αγορα]{.greek-added} [καθημενοις]{.greek-omitted} και [προσφωνουσιν]{.greek-omitted} [προσφωνουσι]{.greek-added} τοις εταιροις αυτων[11:16]{.aside}

και λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ [ωρχησασθε]{.greek-omitted} [ορχησασθε]{.greek-added} εθρηνησαμεν υμιν και ουκ εκοψασθε[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ [ο]{.greek-added} [ιωαννης]{.greek-abbr} μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο υιος του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης [φιλος]{.greek-added} τελωνων [φιλος]{.greek-omitted} και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ονειδιζειν τας πολει[ς]{.unclear} εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χωραζιν]{.greek-added} ουαι σοι βηθσαιδα οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι αν εν σακκω και σποδω μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ η εως του [ουρανου]{.greek-abbr} υψωθεισα εως αδου καταβιβασθηση οτι ει εν σοδομοις εγενοντο αι δυναμεις αι γενομεναι εν σοι εμειναν αν [μεχρι]{.greek-omitted} [αχρι]{.greek-added} της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι γη σοδομων [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται εν ημερα κρισεως η σοι[11:24]{.aside}

εν εκεινω τω καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι [απεκρυψας]{.greek-omitted} [απεκριψας]{.greek-added} ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι παρεδοθη υπο του [πατρος]{.greek-abbr} μου και ουδεις επιγινωσκει τον υιον ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο υιος και [ω]{.greek-omitted} [ο]{.greek-added} εαν βουληται ο υιος αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι κοπιωντες και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και ευρησετε αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγο[ς]{.greek-supplied} μου χρηστος και το φορτιον μου ελαφρον [εστιν]{.greek-omitted}[11:30]{.aside}

### Chapter 12

εν εκεινω τω καιρω [επορευθη]{.greek-omitted} [επορευετο]{.greek-added} ο [ιησους]{.greek-abbr} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων οι δε μαθηται αυτου επεινασαν και ηρξαντο τιλλειν [τους]{.greek-added} σταχυας και εσθιειν[12:1]{.aside}

οι δε [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ιδοντες ειπον αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ποιειν εν σαββατω[12:2]{.aside}

ο δε ειπεν αυτοις ουκ ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added} [αυτος]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[12:3]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως [εφαγεν]{.greek-omitted} [εφαγον]{.greek-added} ους ουκ εξον [ην]{.greek-omitted} αυτω φαγειν [ουδε]{.greek-omitted} [αλλα]{.greek-added} τοις [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τοις]{.greek-omitted} [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} μονοις[12:4]{.aside}

[η]{.greek-omitted} ουκ ανεγνωτε εν τω νομω οτι τοις σαββασιν οι ιερεις εν τω ιερω το σαββατον [βεβηλουσιν]{.greek-omitted} [βεβηλουσι]{.greek-added} και αναιτιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[12:5]{.aside}

λεγω δε υμιν οτι του ιερου μειζον εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε [το]{.greek-added} τι εστιν ελεον θελω και ου θυσιαν ουκ αν κατεδικασατε τους αναιτιους[12:7]{.aside}

κυριος γαρ εστι[ν]{.unclear} του σαββατου ο υιος του [ανθρωπου]{.greek-abbr}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} [ην]{.greek-omitted} [εκει]{.greek-added} την χειρα εχων ξηραν και επηρωτησαν αυτον λεγοντες ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις [εσται]{.greek-omitted} [εστιν]{.greek-added} εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει αυτο και εγερει[12:11]{.aside}

ποσω ουν διαφερει [ανθρωπος]{.greek-abbr} προβατου ωστε [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} καλως ποιειν[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} [η]{.greek-added} [χειρ]{.greek-added} [αυτου]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

οι δε φαρισαιοι συμβουλιον ελαβον κατ αυτου εξελθοντες οπως [ανον]{.greek-added} αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και επετιμησεν αυτοις ινα μη φανερον αυτον ποιησωσιν[12:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον ηρετισα ο αγαπητος μου εις ον ευδοκησεν η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει ουδε ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον [τυφομενον]{.greek-omitted} [τυφωμενον]{.greek-added} ου σβεσει εως αν [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εις νικος την κρισιν[12:20]{.aside}

και τω ονοματι αυτου εθνη ελπιουσιν[12:21]{.aside}

τοτε προσηνεχθη αυτω δαιμονιζομενος τυφλος και κωφος και εθεραπευσεν αυτον ωστε τον τυφλον και κωφον και λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο παντες οι οχλοι και ελεγον μητι ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} ο [υιος]{.greek-omitted} [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ακουσαντες ειπον ουτος ουκ εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

ειδως δε ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν αυτοις πασα βασιλεια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} [ερημουται]{.greek-omitted} [ου]{.greek-added} [σταθησεται]{.greek-added} και πασα πολις η οικια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν εκβαλλει εφ εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

και ει εγω εν βεελζεβουλ εκβαλλω τα δαιμονια οι υιοι υμων εν τινι [εκβαλλουσιν]{.greek-omitted} [εκβαλλουσι]{.greek-added} δια τουτο αυτοι υμων εσονται κριται[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} [εγω]{.greek-omitted} εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

[η]{.greek-omitted} πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου διαρπασαι [εαν]{.greek-omitted} [ει]{.greek-added} μη [πρωτον]{.greek-omitted} [προτερον]{.greek-added} δηση τον ισχυρον [και]{.greek-omitted} [τοτε]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπασει]{.greek-omitted}[12:29]{.aside}

ο μη ων μετ εμου κατ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

δια τουτο λεγω υμιν πασα αμαρτια και βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} η δε του [πνευματος]{.greek-abbr} βλασφημια ουκ αφεθησεται [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted}[12:31]{.aside}

και ος εαν ειπη λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω [και]{.greek-added} [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [ειπη]{.greek-omitted} [κατα]{.greek-omitted} [του]{.greek-omitted} [πνευματος]{.greek-omitted} [του]{.greek-omitted} [αγιου]{.greek-omitted} [ουκ]{.greek-omitted} [αφεθησεται]{.greek-omitted} [αυτω]{.greek-omitted} [ουτε]{.greek-omitted} εν τω νυν αιωνι [ουτε]{.greek-omitted} [και]{.greek-added} εν τω μελλοντι[12:32]{.aside}

η ποιησατε το δενδρον [αυτου]{.greek-added} καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον [αυτου]{.greek-added} σαπρο[ν]{.unclear} και τον καρπον αυτου σαπρον εκ γαρ τ[ου]{.unclear} καρπου το δενδρον γινωσκεται[12:33]{.aside}

γεννηματα εχιδνων πως δυνασθε αγαθα λαλειν πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου εκβαλλει [τα]{.greek-added} αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου εκβαλλει [τα]{.greek-added} πονηρα[12:35]{.aside}

λεγω δε υμιν οτι παν ρημα αργον ο εαν λαλησω[σι]{.unclear}[ν]{.greek-supplied} οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσουσι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων σου δικαιωθηση και εκ των λογων σου καταδικασθηση[12:37]{.aside}

τοτε απεκριθησαν τινες των γραμματεων [και]{.greek-omitted} [φαρισαιων]{.greek-omitted} λεγοντες διδασκαλε θελομεν απο σου σημειον ιδειν[12:38]{.aside}

ο δε αποκριθεις ειπεν αυτοις γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ γαρ ην ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας ουτως εσται [και]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} εν τη καρδια της γης τρεις ημερας και τρεις νυκτας[12:40]{.aside}

ανδρες νινευιται αναστησονται εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

βασιλισσα νοτου εγερθησεται εν τη κρισει μετα της γενεας ταυτης και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν σολομωνος και ιδου πλειον σολομωνος ωδε[12:42]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητουν αναπαυσιν και [ουχ]{.greek-omitted} [μη]{.greek-added} [ευρισκει]{.greek-omitted} [ευρισκον]{.greek-added}[12:43]{.aside}

[τοτε]{.greek-omitted} λεγει επιστρεψω εις τον οικον μου οθεν εξηλθον και ελθον [ευρισκει]{.greek-omitted} [ει]{.greek-added} [ευρη]{.greek-added} [τον]{.greek-added} [[ανθρωπον]{.greek-abbr}]{.greek-added} σχολαζοντα [και]{.greek-added} σεσαρωμενον και κεκοσμημενον[12:44]{.aside}

τοτε πορευεται και παραλαμβανει μεθ εαυτου [ε[τ]{.greek-supplied}[ερα]{.unclear}]{.greek-added} επ[τ]{.unclear}α [ετερα]{.greek-omitted} πνευματα [πονηροτερα]{.greek-omitted} [εαυτου]{.greek-omitted} και εισελθοντα κατοικει εκει και γινεται τα εσχατα του ανθρωπου εκεινου χειρονα των πρωτων ουτως εσται και τη γενεα ταυτη τη πονηρα[12:45]{.aside}

ετι δε αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και οι [α]{.greek-added} αδελφοι αυτου ει[στη]{.unclear}κεισαν εξω ζητουντες [αυτον]{.greek-added} [αυτω]{.greek-omitted} [λαλησαι]{.greek-omitted}[12:46]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εξω [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} ζητουντες [σοι]{.greek-omitted} [σε]{.greek-added} λαλησαι[12:47]{.aside}

ο δε αποκριθεις ειπεν [τω]{.greek-omitted} [ειποντι]{.greek-omitted} αυτω τ[ι]{.unclear}ς εστιν η [μητηρ]{.greek-abbr} μου και τινες [εισιν]{.greek-omitted} οι αδελφοι μου[12:48]{.aside}

και εκτεινας την χειρα αυτου επι τους μαθητας αυτου ειπεν ιδου η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[12:49]{.aside}

οστις γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr} αυτος μου αδελφος και [αδελφη]{.greek-omitted} [και]{.greek-omitted} [μητηρ]{.greek-abbr} εστιν[12:50]{.aside}

### Chapter 13

εν δε τη ημερα εκεινη εξελθων ο [ιησους]{.greek-abbr} απο της οικιας εκαθητο παρα την θαλασσαν[13:1]{.aside}

και συνηχθησαν προς αυτον οχλοι πολλοι ωστε αυτον εις [το]{.greek-omitted} πλοιον εμβαντα καθησθαι και πας ο οχλος επι τον αιγιαλον ειστηκει[13:2]{.aside}

και ελαλησεν [αυτοις]{.greek-omitted} [πολλα]{.greek-omitted} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} [λεγων]{.greek-omitted} ιδου εξηλθεν ο [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} του [σπειρειν]{.greek-omitted} [σπειραι]{.greek-added} [τον]{.greek-added} [σπορον]{.greek-added} [αυτου]{.greek-added}[13:3]{.aside}

και εν τω σπειρειν αυτον α μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν αυτα[13:4]{.aside}

αλλα δε επεσεν επι τα πετρωδη οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} [γην]{.greek-omitted} [πολλην]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [εξανετειλεν]{.greek-omitted} [δια]{.greek-omitted} [το]{.greek-omitted} [μη]{.greek-omitted} [εχειν]{.greek-omitted} βαθος γης[13:5]{.aside}

[και]{.greek-added} ηλιου [δε]{.greek-omitted} ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[13:6]{.aside}

αλλα δε [επεσεν]{.greek-omitted} [επησεν]{.greek-added} επι τας ακανθας και ανεβησαν αι ακανθαι και απεπνιξαν αυτα[13:7]{.aside}

αλλα δε επεσεν επι την γην την καλην και εδιδου καρπον ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:8]{.aside}

ο εχων ωτα ακουειν ακουετω[13:9]{.aside}

και προσελθοντες οι μαθηται [αυτου]{.greek-added} ει[π]{.unclear}ον αυτω δια τι εν παραβολαις λαλεις αυτοις[13:10]{.aside}

ο δε αποκριθεις ειπεν αυτοις [οτι]{.greek-omitted} υμιν δεδοται γνωναι τα μυστηρια της βασιλειας των [ουρανων]{.greek-abbr} εκεινοις δε ου δεδοται[13:11]{.aside}

οστις γαρ εχει δοθησεται αυτω και περισσευθησεται οστις δε ουκ εχει και ο εχει αρθησεται απ αυτου[13:12]{.aside}

δια τουτο εν παραβολαις αυτοις λαλω οτι βλεποντες ου [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και ακουοντες ουκ ακουουσιν ουδε [συνιουσιν]{.greek-omitted} [συνιουσι]{.greek-added}[13:13]{.aside}

και [αναπληρουται]{.greek-omitted} [πληρουται]{.greek-added} [επ]{.greek-added} αυτοις η προφητεια ησαιου [η]{.greek-omitted} λεγουσα ακοη ακουσετε και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη ιδητε[13:14]{.aside}

επαχυνθη γαρ [η]{.unclear} καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και [τους]{.greek-omitted} [τοις]{.greek-added} [οφθαλμους]{.greek-omitted} [οφθαλμοις]{.greek-added} αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και ιασομαι αυτους[13:15]{.aside}

υμων δε μακαριοι οι οφθαλμοι οτι [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και τα ωτα υμων οτι [ακουει]{.greek-omitted} [ακουουσιν]{.greek-added}[13:16]{.aside}

αμην [γαρ]{.greek-omitted} λεγω υμιν οτι πολλοι προφηται και δικαιοι επεθυμησαν ιδειν α βλεπετε και ουκ ειδον και ακουσαι α [ακουεται]{.greek-added} [ακουετε]{.corr} και ουκ ηκουσαν[13:17]{.aside}

υμεις ουν ακουσατε την παραβολην του [σπειροντος]{.greek-omitted} [σπειραντος]{.greek-added}[13:18]{.aside}

παντος ακουοντος τον λογον της βασιλειας και μη συνιεντος ερχεται ο πονηρος και αρπαζει το εσπαρμενον [εν]{.greek-omitted} [εκ]{.greek-added} [τη]{.greek-omitted} [της]{.greek-added} [καρδια]{.greek-omitted} [καρδιας]{.greek-added} αυτου ουτος εστιν ο παρα την οδον σπαρεις[13:19]{.aside}

ο δε επι τα πετρωδη σπαρεις ουτος εστιν ο τον [λογων]{.greek-added} [λογον]{.corr} ακουων και ευθυς μετα χαρας λαμβανων αυτον[13:20]{.aside}

ουκ εχει δε ριζαν εν εαυτω αλλα προσκαιρος [εστιν]{.greek-omitted} [εστι]{.greek-added} γενομενης δε θλιψεως η διωγμου δια τον λογον ευθυς σκανδαλιζεται[13:21]{.aside}

ο δε εις τας ακανθας σπαρεις ουτος εστιν ο τον λογον ακουων και η μεριμνα του αιωνος τουτου και η απατη του πλουτου συμπνιγει τον λογον και ακαρπος γινεται[13:22]{.aside}

ο δε επι την γην την καλην σπαρεις ουτος εστιν ο τον λογον ακουων και συνιων ος δη καρποφορει [και]{.greek-omitted} [ποιει]{.greek-omitted} ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:23]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} σπειροντι καλον σπερμα εν τω αγρω αυτου[13:24]{.aside}

εν δε τω καθευδειν τους [ανθρωπους]{.greek-abbr} ηλθεν αυτου ο εχθρος και [εσπειρεν]{.greek-omitted} [εσπειρε]{.greek-added} ζιζανια ανα μεσον του σιτου και απηλθεν[13:25]{.aside}

οτε δε εβλαστησεν ο χορτος και καρπον [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοτε εφανη και τα ζιζανια[13:26]{.aside}

προσελθοντες δε οι δουλοι του οικοδεσποτου ειπον αυτω κ[υ]{.unclear}[ρι]{.greek-supplied}ε ουχι καλον σπερμα εσπειρας εν τω [σω]{.greek-omitted} αγρω ποθεν ουν εχει ζιζανια[13:27]{.aside}

ο δε εφη [αυτοις]{.greek-omitted} εχθρος [ανθρωπος]{.greek-abbr} τουτο εποιησεν οι δε δουλοι ειπον αυτω θελεις [ουν]{.greek-omitted} απελθοντες [συλλεξομεν]{.greek-omitted} [συλλεξωμεν]{.greek-added} αυτα[13:28]{.aside}

ο δε εφη ου μηποτε συλλεγοντες τα ζιζανια εκριζωσητε αμα αυτοις τον σιτον[13:29]{.aside}

αφετε [ουν]{.greek-added} συναυξανεσθαι αμφοτερα μεχρι του θερισμου και εν [τω]{.greek-added} καιρω του θερισμου ερ[ω]{.unclear} τοις θερισταις συλλεξατε πρωτον τα ζιζανια και δησατε αυτα εις δεσμας προς το κατακαυσαι αυτα τον δε σιτον συναγαγετε εις την αποθηκην μου[13:30]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} κοκκω σιναπεως ον λαβων [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο μικροτερον μεν [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των σπερματων οταν δε αυξηθη μειζον [παντων]{.greek-added} των λαχανων [εστιν]{.greek-omitted} [εστι]{.greek-added} και [γινεται]{.greek-omitted} [εγενετο]{.greek-added} δενδρον ωστε ελθειν τα πετεινα του [ουρανου]{.greek-abbr} και κατασκηνουν [ε]{.unclear}ν τοις κλαδοις αυτου[13:32]{.aside}

αλλην παραβολην ελαλησεν αυτοις ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} ζυμη ην λαβουσα γυνη εκρυψεν εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33]{.aside}

[τ]{.greek-supplied}αυτα παντα ελαλησεν [εν]{.greek-added} [παραβολαις]{.greek-added} ο [ιησους]{.greek-abbr} [εν]{.greek-omitted} [παραβολαις]{.greek-omitted} τοις οχλοις και χωρις παραβολης ουκ ελαλει αυτοις[13:34]{.aside}

οπως πληρωθη το ρηθεν δια του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου ερευξομαι [κ]{.unclear}εκρυμμενα απο καταβολης κοσμου[13:35]{.aside}

[το]{.greek-supplied}τε αφεις τους οχλους ηλθεν εις [τ]{.greek-supplied}ην οικιαν ο [ιησους]{.greek-abbr} [κα]{.greek-supplied}ι προσηλθον αυτω οι μαθηται αυτου [λ]{.greek-supplied}εγοντες φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις ο σπειρων το καλον σπερμα εστιν ο υιος του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του πονηρου[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστιν οι δε [θερινσται]{.greek-added} [θερισται]{.corr} αγγελοι [εισιν]{.greek-omitted}[13:39]{.aside}

ωσπερ ουν συλλεγεται τα ζιζανια και πυρι καιεται ουτως εσται εν τη συντελεια του αιωνος τουτου[13:40]{.aside}

αποστελει ο υιος του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν [τω]{.greek-omitted} αγρω ον ευρων [ανθρωπος]{.greek-abbr} [εκρυψεν]{.greek-omitted} [εκρυψε]{.greek-added} και απο της χαρας αυτου υπαγει και [πωλει]{.greek-added} παντα οσα εχει [πωλει]{.greek-omitted} και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

ος ευρων ενα πολυτιμον μαργαριτην απελθων [πεπρακεν]{.greek-omitted} [πεπρακε]{.greek-added} παντα οσα [ει]{.greek-added} [ειχεν]{.greek-omitted} [[ειχε]{.corr}]{.greek-added} και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη βληθειση εις την θαλασσαν και εκ παντος γενους [συναγαγουση]{.greek-omitted} [συναγουση]{.greek-added}[13:47]{.aside}

ην οτε επληρωθη αναβιβασαντες [επι]{.greek-omitted} [τον]{.greek-omitted} [αιγιαλον]{.greek-omitted} [και]{.greek-omitted} [καθισαντες]{.greek-omitted} συνελεξαν τα [καλα]{.greek-omitted} [καλλιστα]{.greek-added} εις αγγεια τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως [εσται]{.greek-omitted} [εσονται]{.greek-added} εν τη συντελεια του αιωνος εξελευσονται οι αγγελοι και [αφοριουσιν]{.greek-omitted} [αφοριουσι]{.greek-added} τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:50]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα λεγουσιν [αυτω]{.greek-omitted} [αυτοι]{.greek-added} [[αυτοις]{.corr}]{.greek-added} ναι [κυριε]{.greek-abbr}[13:51]{.aside}

ο δε ειπεν αυτοις δια τουτο πας γραμματευς μαθητευθεις εις την βασιλειαν των [ουρανων]{.greek-abbr} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εκβαλλει εκ του θησαυρου αυτου καινα και παλαια[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας μετηρεν ε[κ]{.greek-supplied}ειθεν[13:53]{.aside}

και ελθων ει[ς]{.unclear} τ[ην]{.unclear} [πατριδα]{.greek-abbr} αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων ωστε εκπληττεσθαι αυτους και λεγειν ποθεν τουτω η σοφια αυτη και αι δυναμεις[13:54]{.aside}

ουχ ουτος εστιν ο του τεκτονος υιος [ουχι]{.greek-omitted} [ουχ]{.greek-added} η [μητηρ]{.greek-abbr} αυτου λεγεται μαριαμ και οι αδελφοι αυτου ιακωβος και [ιωσης]{.greek-omitted} [ιωσηφ]{.greek-added} και σιμων και ιουδας[13:55]{.aside}

και αι αδελφαι α[υτου]{.unclear} ουχι πασαι προς ημας [εισιν]{.greek-omitted} [εισι]{.greek-added} ποθεν ουν [τουτω]{.greek-omitted} ταυτα παντα[13:56]{.aside}

και εσκανδαλιζοντο [εν]{.greek-omitted} [αυτω]{.greek-omitted} ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου και εν τη οικια αυτου[13:57]{.aside}

και ουκ εποιησεν εκει δυναμεις πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο [τετραρχης]{.greek-omitted} [τεταρχης]{.greek-added} την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις παισιν αυτου ουτος [εστην]{.greek-added} [εστιν]{.corr} ιωαννης ο βαπτιστης αυτος ηγερθη απο των νεκρων και δια τουτο αι δυναμεις ενεργουσιν εν αυτω[14:2]{.aside}

ο γαρ ηρωδης κρατησας τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εδησεν αυτον και εθετο εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου[14:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω ο [ιωαννης]{.greek-abbr} ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

[γενεσιων]{.greek-omitted} [γενεσιουν]{.greek-added} δε αγομενων του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και ηρεσεν τω ηρωδ[η]{.unclear}[14:6]{.aside}

οθεν μεθ ορκου ωμολογησεν αυτη δουν[α]{.unclear}ι ο εαν αιτησηται[14:7]{.aside}

η δε προβιβασθεισα υπο της [μητρος]{.greek-abbr} αυτης δος μοι φησιν ωδε επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[14:8]{.aside}

και ελυπηθη ο βασιλευς δια δε τους ορκους και τους συνανακειμενους [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλισε]{.greek-added} τον [ιωαννην]{.greek-abbr} εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι πινακι και εδοθη τω κορασιω και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το σωμα και εθαψαν αυτο και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

και ακουσας [ο]{.greek-omitted} [ιησους]{.greek-abbr} ανεχωρησεν εκειθεν εν πλοιω εις ερημον τοπον κατ ιδιαν και ακουσαντες οι οχλοι ηκολουθησαν αυτω πεζη απο των πολεων[14:13]{.aside}

και εξελθων ο [ιησους]{.greek-abbr} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται αυτου λεγοντες ερημος εστιν ο τοπος και η ωρα ηδη παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας [κυκλω]{.greek-added} κωμας αγορασωσιν εαυτοις βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου χρειαν εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} φερετε μοι αυτους ωδε[14:18]{.aside}

και κελευσας τους οχλους ανακλιθηναι επι τους χορτους λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} ευλογησεν [[αυ]{.unclear}[τ]{.greek-supplied}[ους]{.unclear}]{.greek-added} και κλασας [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τ[ο]{.unclear}ις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες ωσει πεντακισχιλιοι χωρις γυναικων και παιδιων[14:21]{.aside}

και ευθεως ηναγκασεν ο [ιησους]{.greek-abbr} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} εμβηναι εις το πλοιον και προαγειν αυτον εις το περαν εως ου απολυση τους οχλους[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος κατ ιδιαν προσευξασθαι οψιας δε γενομενης μονος ην εκει[14:23]{.aside}

το δε πλοιον [ηδη]{.greek-omitted} μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς αυτους ο [ιησους]{.greek-abbr} περιπατων επι της θαλασσης[14:25]{.aside}

και ιδοντες αυτον οι μαθηται [επι]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [περιπατουντα]{.greek-omitted} εταραχθησαν λεγοντες οτι [φαντασμα]{.greek-omitted} [φανταμα]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} λεγων [θαρσειτε]{.greek-omitted} εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} ει συ ει κελευσον με προς σε ελθειν επι τα υδατα[14:28]{.aside}

ο δε ειπεν ελθε και καταβας απο του πλοιου [ο]{.greek-omitted} [πετρος]{.greek-omitted} [περιεπατησεν]{.greek-omitted} [περιεπατει]{.greek-added} επι τα υδατα [ελθειν]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted}[14:29]{.aside}

βλεπων δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα επελαβετο α[υ]{.greek-supplied}του και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω ελθοντες προσεκυνησαν αυτω λεγοντες αληθως [θεου]{.greek-abbr} υιος ει[14:33]{.aside}

και διαπερασαντες ηλθον εις την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added}[14:34]{.aside}

και επιγνοντες αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον αψωνται του κρασπεδου του ιματιου αυτου και οσοι ηψαντο διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτε προσερχονται τω [ιησου]{.greek-abbr} οι απο ιεροσολυμων γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου [παραβαινουσιν]{.greek-omitted} [παραβαινουσι]{.greek-added} την παραδοσιν των πρεσβυτερων ου γαρ νιπτονται τας χειρας αυτων οταν αρτον εσθιωσιν[15:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και υμεις παραβαινετε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} ενετειλατο λεγων τιμα τον [πατερα]{.greek-abbr} και την [μητερα]{.greek-abbr} και ο κακολογων [τον]{.greek-added} [πατερα]{.greek-abbr} η [την]{.greek-added} [μητερα]{.greek-abbr} θανατω τελευτατω[15:4]{.aside}

υμεις δε λεγετε ος αν ειπη τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} δωρον ο εαν εξ εμου ωφεληθης [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[και]{.greek-added} [ου]{.greek-added} [μ[ι]{.unclear}]{.greek-added} [[μη]{.corr}]{.greek-added} [τιμηση]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [η]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} και ηκυρωσατε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:6]{.aside}

υποκριται καλως [προεφητευσεν]{.greek-omitted} [προεφητευσε]{.greek-added} περι υμων ησαιας λεγων[15:7]{.aside}

εγγιζει μοι ο λαος ουτος τω στοματι αυτων και τ[ο]{.unclear}ις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[15:8]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα ανθρωπων[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις ακουετε και [συνιτε]{.greek-added} [συνιετε]{.greek-omitted} [συνοιετε]{.greek-added}[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} αλλα το εκπορευομενον εκ του στοματος τουτο κοινοι τον [ανθρωπον]{.greek-abbr}[15:11]{.aside}

τοτε προσελθοντες οι μαθηται [αυτου]{.greek-omitted} ειπον αυτω οιδας οτι οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ακουσαντες [τον]{.greek-omitted} [των]{.greek-added} [λογον]{.greek-omitted} [λογων]{.greek-added} [ε]{.unclear}σκανδαλισθησαν[15:12]{.aside}

ο δε αποκριθεις [ει]{.greek-supplied}πεν [αυτοις]{.greek-added} πασα φυτεια ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο [ουρανιος]{.greek-abbr} εκριζωθησεται[15:13]{.aside}

αφετε αυτους οδηγοι [εισιν]{.greek-omitted} [εισι]{.greek-added} τυφλοι τυφλων τυφλος δε τυφλον εαν οδηγη αμφοτεροι εις βοθυνον πεσουνται[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν ακμην και υμεις ασυνετοι εστε[15:16]{.aside}

ουπω νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ [της]{.unclear} [κ]{.unclear}αρδιας εξερχεται [και]{.greek-added} [κακεινα]{.greek-omitted} [εκεινα]{.greek-added} κοινοι τον [ανθρωπον]{.greek-abbr}[15:18]{.aside}

εκ γαρ της καρδιας εξερχονται διαλογισμοι πονηροι φονοι μοιχειαι πορνειαι κλοπαι ψευδομαρτυριαι βλασφημιαι[15:19]{.aside}

ταυτα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr} το δε ανιπτοις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} φαγειν ου κοινοι τον ανθρωπον[15:20]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα μερη τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα εκραυγασεν αυτω λεγουσα ελεησον με [κυριε]{.greek-omitted} υιε [δαυιδ]{.greek-abbr} η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε ουκ απεκριθη αυτη λογο[ν]{.unclear} και προσελθοντες οι μαθηται αυτου ηρωτων αυτον λεγοντες απολυσον αυτην οτι κραζει οπισθεν ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην ει μη εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

η δε ελθουσα προσεκυνησεν αυτω λεγουσα [κυριε]{.greek-abbr} βοηθει μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των ψιχιων των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη [ω]{.greek-omitted} [γυναι]{.greek-omitted} μεγαλη σου η πιστις γενηθητω σοι ως θελεις και ιαθη η θυγατηρ αυτης απο της ω[ρ]{.unclear}ας [ε]{.greek-supplied}[κ]{.unclear}ει[ν]{.greek-supplied}ης[15:28]{.aside}

και μεταβας εκει[θε]{.greek-supplied}ν ο [ιησους]{.greek-abbr} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος εκαθητο εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ εαυτων χωλους τυφλους κωφους κυλλους και ετερους πολλους [οι]{.greek-added} και ερριψαν αυτους παρα τους ποδας του [ιησου]{.greek-abbr} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας [κω]{.unclear}φους λαλουντας κυλλους υγιεις χωλους περιπατουντας και τυφλους βλεποντας και εδοξασαν τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγειν]{.greek-added} και απολυσαι αυτους νηστεις ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια αρτοι τοσουτοι ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} [οχλοις]{.greek-omitted} [οχλους]{.greek-added} αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις αυτου οι δε μαθηται τω οχλω[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας πληρεις[15:37]{.aside}

οι δε εσθιοντες ησαν τετρακισχιλιοι ανδρες χωρις γυναικων και παιδ[ιων]{.greek-supplied}[15:38]{.aside}

και απολυσας τους οχλους [ενεβη]{.greek-omitted} [ανεβη]{.greek-added} εις το πλοιον και ηλθεν εις τα ορια μαγδαλα[15:39]{.aside}

### Chapter 16

και προσελθοντες οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε [οτι]{.greek-added} ευδια [εστι]{.greek-added} πυρραζει γαρ ο [ουρανος]{.greek-abbr}[16:2]{.aside}

και [παλιν]{.greek-added} [πρωι]{.greek-omitted} [πρωιας]{.greek-added} [σημερον]{.greek-omitted} [ουσης]{.greek-added} χειμων [εστι]{.greek-added} πυρραζει γαρ στυγναζων ο [ουρανος]{.greek-abbr} υποκριται το [μεν]{.greek-omitted} προσωπον του [ουρανου]{.greek-abbr} [γινωσκεται]{.greek-added} [γινωσκετε]{.corr} διακρινειν τα δε σημεια των καιρων ου δυνασθε [διακρινειν]{.greek-added}[16:3]{.aside}

γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου και καταλιπων αυτους απηλθεν[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν επελαθοντο αρτους λαβειν[16:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ορατε και προσεχετε απο της ζυμης των [φαρισαιων]{.greek-omitted} [σαδδουκαιων]{.greek-added} και [σαδδουκαιων]{.greek-omitted} [φαρισσαιων]{.greek-added}[16:6]{.aside}

οι δε διελογιζοντο εν εαυτοις λεγοντες οτι αρτους ουκ ελαβομεν[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι διαλογιζεσθε εν εαυτοις ολιγοπιστοι οτι αρτους ουκ ελαβετε[16:8]{.aside}

ουπω νοειτε ουδε μνημονευετε [των]{.greek-added} [πεντε]{.greek-added} [αρτων]{.greek-added} [εις]{.greek-added} τους [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [των]{.greek-omitted} [πεντακισχιλιων]{.greek-omitted} [πεντακισχιλιους]{.greek-added} και ποσους κοφινους ελαβετε[16:9]{.aside}

ουδε [των]{.greek-added} [επτα]{.greek-added} [αρτων]{.greek-added} [εις]{.greek-added} τους [επτα]{.greek-omitted} [αρτους]{.greek-omitted} [των]{.greek-omitted} [τετρακισχιλιων]{.greek-omitted} [τετρακισχιλιους]{.greek-added} και ποσας σπυριδας ελαβετε[16:10]{.aside}

πως ου νοειτε οτι ου περι αρτου ειπον υμιν προσεχειν απο της ζυμης των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και σαδδουκαιων[16:11]{.aside}

τοτε συνηκαν οτι ουκ ειπεν [αυτοις]{.greek-added} [περι]{.greek-added} [προσεχειν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ζυμης]{.greek-omitted} [του]{.greek-omitted} αρτου αλλα [απο]{.greek-omitted} [περι]{.greek-added} της διδαχης των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} [και]{.greek-omitted} [σαδδουκαιων]{.greek-omitted}[16:12]{.aside}

ελθων δε ο [ιησους]{.greek-abbr} εις τα μερη καισαρειας της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι τον υιον του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον οι μεν ιωαννην τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λεγει αυτοις υμεις δε τινα με λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτω μακαριος ει σιμων βαριωνα οτι σαρξ και αιμα ουκ [απεκαλυψεν]{.greek-omitted} [απεκαλυψε]{.greek-added} σοι αλλ ο πατηρ μου ο εν τοις ουρανοις[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι αδου ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [τω]{.greek-added} [[ουρανω]{.greek-abbr}]{.greek-added} και ο εαν λυσης επι της γης εσται λελυμενον εν [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [τω]{.greek-added} [ουρανω]{.greek-added}[16:19]{.aside}

τοτε [διεστειλατο]{.greek-omitted} [ενετειλατο]{.greek-added} τοις μαθηταις [αυτου]{.greek-omitted} ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-omitted} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} [δεικνυειν]{.greek-omitted} [λεγειν]{.greek-added} τοις μαθηταις αυτου οτι δει αυτον [απελθειν]{.greek-omitted} [απηλθειν]{.greek-added} εις ιεροσολυμα και πολλα παθειν απο των πρεσβυτερων και αρχιερεων και γραμματεων και αποκτανθηναι και τη τριτη ημερα εγερθηναι[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω λεγων ιλεως σοι [κυριε]{.greek-abbr} ου μη εσται σοι τουτο[16:22]{.aside}

ο δε στραφεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω πετρω υπαγε οπισω μου σατανα σκανδαλον μου ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των ανθρωπων[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ει [τις]{.greek-omitted} [της]{.greek-added} θελει οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[16:24]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι [απολεσει]{.greek-omitted} [απωλεσει]{.greek-added} αυτην ος δ αν απολεση την ψυχην αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι [γαρ]{.greek-omitted} ωφελειται [ανθρωπος]{.greek-abbr} εαν τον κοσμον ολον κερδηση την δε ψυχην αυτου ζημιωθη η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο υιος του [ανθρωπου]{.greek-abbr} ερχεσθαι εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων αυτου και τοτε αποδωσει εκαστω κατα [την]{.greek-omitted} [πραξιν]{.greek-omitted} [τα]{.greek-added} [εργα]{.greek-added} αυτου[16:27]{.aside}

[αμην]{.greek-added} αμην λεγω υμιν [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες ωδε εστωτες οιτινες ου μη γευσωνται θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και [ιωαννην]{.greek-abbr} τον αδελφον αυτου και αναφερει αυτους εις ορος υψηλον κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και [ελαμψεν]{.greek-omitted} [ελαμψε]{.greek-added} το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου εγενοντο λευκα ως το φως[17:2]{.aside}

και ιδου ωφθησαν [αυτοις]{.greek-omitted} [αυτω]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [και]{.greek-added} και ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

αποκριθεις δε ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω [ιησου]{.greek-abbr} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι ει θελεις ποιησωμεν [ωδε]{.greek-omitted} τρεις σκηνας σοι μιαν και [μωση]{.greek-omitted} [μωσει]{.greek-added} μιαν και μιαν [ηλια]{.greek-omitted} [ηλιαν]{.greek-added}[17:4]{.aside}

ετι αυτου λαλουντος ιδου νεφελη φωτεινη επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο υιος μου ο αγαπητος εν ω ευδοκησα αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται επεσον επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν εγερθητε και μη φοβεισθε[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινον[τ]{.unclear}ων αυτων εκ του ορους ενετειλατο αυτοις ο [ιησους]{.greek-abbr} [λεγων]{.greek-omitted} [ινα]{.greek-added} μηδενι [ειπητε]{.greek-omitted} [ειπωσι]{.greek-added} το οραμα [τουτο]{.greek-added} εως [ου]{.greek-omitted} [[α]{.unclear}[―]{.gap}]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αν[α]{.unclear}στη[17:9]{.aside}

και επηρωτησαν αυτον οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν δει ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις ηλιας μεν ερχεται πρωτον και αποκαταστησει παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας [ηδη]{.greek-omitted} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ουκ επεγνωσαν αυτον [αλλα]{.greek-omitted} [αλλ]{.greek-added} εποιησαν [εν]{.greek-omitted} αυτω οσα ηθελησαν [ουτως]{.greek-omitted} [ουτω]{.greek-added} και ο υιος του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι ιωαννου του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον [προσηλθεν]{.greek-omitted} [προσηλθε]{.greek-added} [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [ανθρωπος]{.greek-abbr} γονυπετων αυτον[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι σεληνιαζεται και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και προσηνεγκα αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν αυτον θεραπευσ[αι]{.unclear}[17:16]{.aside}

απο[κ]{.unclear}ριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστ[ο]{.greek-supplied}ς και διεστραμμεν[η]{.unclear} εως ποτε εσο[μ]{.greek-supplied}αι μεθ υμων εως ποτε ανεξομαι υμων φερετε μοι αυτον ωδε[17:17]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} [το]{.greek-added} [δαιμονιον]{.greek-added} απ αυτου [το]{.greek-omitted} [δαιμονιον]{.greek-omitted} και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε προσελθοντες οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην γαρ λεγω υμιν εαν εχητε πιστιν ως κοκκον [σιναπεως]{.greek-omitted} [συναπεως]{.greek-added} ερειτε τω ορει τουτω μεταβηθι εντευθεν [εκει]{.greek-omitted} και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ εκπορευεται ει μη εν προσευχη και νηστεια[17:21]{.aside}

αναστρεφομενων δε αυτων εν τη γαλιλαια ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα εγερθησεται και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε αυτων εις καπερναουμ προσηλθον οι τα διδραχμα λαμβανοντες τω πετρω και ειπον [και]{.greek-added} ο διδασκαλος υμων ου τελει τα διδραχμα[17:24]{.aside}

λεγει ναι και οτε εισηλθεν εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο τινων [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} τελη η κηνσον απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

λεγει αυτω ο πετρος απο των αλλοτριων εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις την θαλασσαν βαλε αγκιστρον και τον [αναβαινοντα]{.greek-omitted} [αναβαντα]{.greek-added} πρωτον ιχθυν αρον και ανοιξας το στομα αυτου ευρησεις στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ωρα προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες τις αρα μειζων εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν [αμην]{.greek-added} αμην λεγω υμιν εαν μη στραφητε και γενησθε ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο ουτος εστιν [ο]{.greek-omitted} [μειζων]{.greek-omitted} εν τη βασιλεια των [ουρανων]{.greek-abbr} [μειζων]{.greek-added}[18:4]{.aside}

και ος εαν δεξηται παιδιον [τοιουτον]{.greek-omitted} εν [επι]{.greek-omitted} [εν]{.greek-added} τω ονοματι μου εμε [δεχεται]{.greek-omitted} [δεχετε]{.greek-added}[18:5]{.aside}

ος δ αν σκανδαλιση ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος [εις]{.greek-omitted} [επι]{.greek-added} τον τραχηλον αυτου και καταποντισθη εν [τω]{.greek-omitted} [πελαγει]{.greek-omitted} [της]{.greek-omitted} [τη]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασση]{.greek-added}[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

ει δε η χειρ σου η ο πους σου σκανδαλιζει σε εκκοψον αυτα και βαλε απο σου καλον σοι εστιν [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις την ζωην χωλον η [κυλλον]{.greek-omitted} [κοιλον]{.greek-added} η δυο χειρας [η]{.greek-omitted} [δυο]{.greek-omitted} [ποδας]{.greek-omitted} εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και ει ο οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εις την ζωην εισελθειν η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

ορατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} το προσωπον του [[θεου]{.greek-abbr}]{.greek-added} [πατρος]{.greek-omitted} [μου]{.greek-omitted} [του]{.greek-omitted} [εν]{.greek-omitted} [ουρανοις]{.greek-omitted}[18:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο υιος του [ανθρωπου]{.greek-abbr} σωσαι το απολωλος[18:11]{.aside}

τι υμιν [δοκει]{.greek-omitted} [δοκη]{.greek-added} εαν γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα ενενηκοντα εννεα επι τα ορη πορευθεις ζητει το πλανωμενον[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η επι τοις ενενηκοντα εννεα τοις μη [πεπλανημενοις]{.greek-omitted} [πεπλαπλανημενοις]{.greek-added}[18:13]{.aside}

ουτως ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} θελημα εμπροσθεν του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr} ινα [αποληται]{.greek-omitted} [απωληται]{.greek-added} εις των μικρων τουτων[18:14]{.aside}

εαν δε αμαρτηση εις σε ο αδελφος σου υπαγε [και]{.greek-omitted} ελεγξον αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη ακουση παραλαβε μετα σου ετι ενα η δυο ινα επι στοματος δυο μαρτυρων η τριων [σταθη]{.greek-omitted} [σταθησεται]{.greek-added} παν ρημα[18:16]{.aside}

εαν δε παρακουση [αυτων]{.greek-omitted} [ειπε]{.greek-omitted} [τη]{.greek-omitted} [εκκλησια]{.greek-omitted} [εαν]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [της]{.greek-omitted} [εκκλησιας]{.greek-omitted} [παρακουση]{.greek-omitted} εστω σοι [ωσπερ]{.greek-omitted} [ως]{.greek-added} ο εθνικος και ο τελωνης[18:17]{.aside}

αμην λεγω υμιν οσα εαν δησητε επι της γης εσται δεδεμενα εν τω [ουρανω]{.greek-abbr} και οσα εαν λυσητε επι της γης εσται λελυμενα εν τω [ουρανω]{.greek-abbr}[18:18]{.aside}

παλιν αμην λεγω υμιν οτι εαν δυο υμων συμφωνησωσιν επι της γης περι παντος πραγματος ου εαν αιτησωνται γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:19]{.aside}

ου γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο η τρεις συνηγμενοι εις το εμον ονομα εκει ειμι εν μεσω αυτων[18:20]{.aside}

τοτε προσελθων αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} ποσακις αμαρτησει εις εμε ο αδελφος μου και αφησω αυτω εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} ου λεγω σοι εως επτακις [αλλ]{.greek-omitted} [αλλα]{.greek-added} εως εβδομηκοντακις επτα[18:22]{.aside}

δια τουτο ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος [ηθελησεν]{.greek-omitted} [ηθελησε]{.greek-added} συναραι λογον μετα των [δουλων]{.greek-omitted} [συνδουλων]{.greek-added} αυτου[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν αυτον ο κυριος αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} μακροθυμησον επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο κυριος του δουλου εκεινου απελυσεν αυτον και το δανειον αφηκεν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[18:27]{.aside}

εξελθων [δε]{.greek-omitted} [ουν]{.greek-added} ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον δηναρια και κρατησας αυτον [επνιγεν]{.greek-omitted} [επνιγε]{.greek-added} λεγων αποδος μοι ει τι οφειλεις[18:28]{.aside}

πεσων ουν ο συνδουλος [αυτου]{.greek-omitted} εις τους ποδας αυτου παρεκαλει αυτον λεγων μακροθυμησον επ εμοι και αποδωσω σοι[18:29]{.aside}

ο δε ουκ [ηθελεν]{.greek-omitted} [ηθελησεν]{.greek-added} [αλλα]{.greek-omitted} [αλλ]{.greek-added} απελθων εβαλεν αυτον εις φυλακην εως ου αποδω [παν]{.greek-added} το οφειλομενον[18:30]{.aside}

ιδοντες δε οι συνδουλοι αυτου τα γενομενα ελυπηθησαν σφοδρα και ελθοντες διεσαφησαν τω κυριω [εαυτων]{.greek-omitted} [αυτων]{.greek-added} παντα τα γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο κυριος αυτου λεγει αυτω δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι επει παρεκαλεσας με[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως και εγω σε ηλεησα[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} αυτου παρεδωκεν αυτον τοις βασανισταις εως ου αποδω παν το οφειλομενον [αυτω]{.greek-omitted}[18:34]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και ο [πατηρ]{.greek-abbr} μου ο [επουρανιος]{.greek-abbr} ποιησει υμιν εαν μη αφητε εκαστος τω αδελφω αυτου απο των καρδιων υμων τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

[κ]{.unclear}αι προσηλθον αυτω οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} πειραζοντες αυτον και λεγοντες [αυτω]{.greek-omitted} ει εξεστιν [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ ανεγνωτε οτι ο ποιησας απ αρχης αρσεν και θηλυ εποιησεν αυτους[19:4]{.aside}

και ειπεν [ενεκεν]{.greek-omitted} [ενεκα]{.greek-added} τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} και την [μητερα]{.greek-abbr} και προσκολληθησεται τη [ιδια]{.greek-added} γυναικι [αυτου]{.greek-omitted} και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

ωστε [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν μωσης ενετειλατο δουναι βιβλιον αποστασιου και [απολυσαι]{.greek-omitted} [απολυειν]{.greek-added} αυτην[19:7]{.aside}

λεγει αυτοις οτι μωσης προς την σκληροκαρδιαν υμων επετρεψεν υμιν [απολυσαι]{.greek-omitted} [απολυειν]{.greek-added} τας γυναικας υμων απ αρχης δε ου γεγονεν ουτως[19:8]{.aside}

λεγω δε υμιν οτι ος αν απολυση την γυναικα αυτου μη επι πορνεια και γαμηση αλλην μοιχαται και ο απολελυμενην γαμησας μοιχαται[19:9]{.aside}

λεγουσιν αυτω οι μαθηται [αυτου]{.greek-omitted} ει ουτως εστιν η αιτια του ανθρωπου μετα της γυναικος ου συμφερει γαμησαι[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες [χωρουσιν]{.greek-omitted} [χωρουσι]{.greek-added} τον λογον τουτον αλλ οις δεδοται[19:11]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ [ευνο]{.greek-supplied}υχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} εγε[ν]{.greek-supplied}νηθησαν ουτως και εισιν ευνου[χο]{.greek-supplied}ι οιτινες ευνουχισθησαν υπο [τ]{.greek-supplied}ων [ανθρωπων]{.greek-abbr} και εισιν ευνουχοι οιτινες ευνουχισαν εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε [προσηνεχθη]{.greek-omitted} [προσηνεχθησαν]{.greek-added} αυτω παιδια ινα τας χειρας επιθη αυτοις και προσευξηται οι δε μαθηται επετιμησαν αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-added} αφετε τα παιδια και μη κωλυετε αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και επιθεις αυτοις τας χειρας επορευθη εκειθεν[19:15]{.aside}

και ιδου εις [τις]{.greek-added} προσελθων ειπεν αυτω διδασκαλε αγαθε τι αγαθον ποιησω ινα εχω ζωην αιωνιον[19:16]{.aside}

ο δε ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr} ει [δε]{.greek-omitted} θελεις [εισελθειν]{.greek-omitted} εις την ζωην [εισελθειν]{.greek-added} τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το ου φονευσεις ου μοιχευσεις ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} και την [μητερα]{.greek-abbr} και αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[19:19]{.aside}

λεγει αυτω ο νεανισκος [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} εφυλαξαμην εκ νεοτητος μου τι ετι υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελει[ς]{.greek-supplied} τελ[ει]{.unclear}ος ειναι υπαγε πωλησον σου τα υπ[α]{.unclear}ρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως πλουσιος εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν δε λεγω υμιν [οτι]{.greek-added} ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια τρυπηματος ραφιδος [διελθειν]{.greek-omitted} [εισελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} [εισελθειν]{.greek-omitted}[19:24]{.aside}

[ακουσαντες]{.greek-omitted} [ακουοντες]{.greek-added} δε οι μαθηται [αυτου]{.greek-omitted} εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

εμβλεψας δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα δε [θεω]{.greek-abbr} παντα δυνατα [εστιν]{.greek-added}[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω [[κυριε]{.greek-abbr}]{.greek-added} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-omitted} [αυτω]{.greek-added} αμην λεγω [υμιν]{.greek-omitted} [σοι]{.greek-added} οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν καθιση ο υιος του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου [καθισεσθε]{.greek-omitted} [καθησεσθε]{.greek-added} και υμεις επι δωδεκα θρονους κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας ος [αν]{.greek-added} αφηκεν οικιας η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν του ονοματος μου εκατονταπλασιονα ληψεται και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[19:30]{.aside}

### Chapter 20

ομοια γαρ εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

και συμφωνησας μετα των εργατων εκ δηναριου [τη]{.unclear}ν ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι τριτην ωραν ειδεν αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

[κακεινους]{.greek-added} [και]{.greek-omitted} [εκεινοις]{.greek-omitted} ειπεν υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν εξελθων περι εκτην και ενατην ωραν εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο λεγει αυτοις υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον ληψεσθε[20:7]{.aside}

οψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι [πλειονα]{.greek-omitted} [πλειον]{.greek-added} ληψονται και ελαβον και αυτοι ανα δηναριον[20:10]{.aside}

[λαβοντες]{.greek-omitted} [εγογγυζον]{.greek-added} δε [εγογγυζον]{.greek-omitted} κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι [ουτοι]{.greek-omitted} οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας [τοις]{.greek-omitted} [της]{.greek-added} [βαστασασιν]{.greek-omitted} [βαστασασι]{.greek-added} το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων εταιρε ουκ αδικω σε ουχι δηναριου συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε [τουτω]{.greek-omitted} τω εσχατω [τουτω]{.greek-added} δουναι ως και σοι[20:14]{.aside}

η ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι ποιησαι ο θελω εν τοις εμοις ει ο οφθαλμος σου πονηρος εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι [και]{.greek-omitted} [οι]{.greek-omitted} [πρωτοι]{.greek-omitted} [εσχατοι]{.greek-omitted} πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

[κ]{.unclear}αι αναβαινων ο [ιησους]{.greek-abbr} εις ιεροσολυμα [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} τους δωδεκα μαθητας [αυτου]{.greek-added} κατ ιδιαν εν τη οδω και ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω[20:18]{.aside}

και [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} αυτον τοις εθνεσιν εις το εμπαιξαι και μαστιγωσαι και [σταυρωσαι]{.greek-abbr} και τη τριτη ημερα αναστησεται[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι θελεις λεγει αυτω ειπε ινα καθισωσιν ουτοι οι δυο [μου]{.greek-added} υιοι [μου]{.greek-omitted} εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω μελλω [πινειν]{.greek-omitted} [πιειν]{.greek-added} [η]{.greek-omitted} [και]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-omitted} ουκ εστιν εμον δουναι αλλ οις ητοιμασται [υπο]{.greek-omitted} [παρα]{.greek-added} του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα [η]{.greek-supplied}γαν[α]{.unclear}κτησαν περι των δυο [αδελφων]{.greek-omitted}[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη εν υμιν μεγας γενεσθαι [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[20:26]{.aside}

και ος εαν θελη εν υμιν ειναι πρωτος εστω υμων δουλος[20:27]{.aside}

ωσπερ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και εκπορευομενων αυτων απο ιεριχω ηκολουθησεν αυτω οχλος πολυς[20:29]{.aside}

και ιδου δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} υιος [δαυιδ]{.greek-abbr}[20:30]{.aside}

ο δε οχλος επετιμησεν αυτοις ινα σιωπησωσιν οι δε [μειζον]{.greek-omitted} [μειζων]{.greek-added} [εκραζον]{.greek-omitted} [εκραξαν]{.greek-added} λεγοντες ελεησον ημας [κυριε]{.greek-omitted} υιος [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-abbr} [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} [αυτους]{.greek-omitted} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-abbr} ινα ανοιχθωσιν ημων οι οφθαλμοι[20:33]{.aside}

σπλαγχνισθεις δε ο [ιησους]{.greek-abbr} ηψατο των οφθαλμων αυτων και ευθεως ανεβλεψαν αυτων οι οφθαλμοι και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε ηγγισαν εις ιεροσολυμα και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις [βηθσφαγη]{.greek-omitted} [βηθσφαγην]{.greek-added} προς το ορος των ελαιων [τοτε]{.greek-omitted} [απεστειλεν]{.greek-added} ο [ιησους]{.greek-abbr} [απεστειλεν]{.greek-omitted} δυο [μαθητας]{.greek-omitted} [των]{.greek-added} [μαθητων]{.greek-added} [αυτου]{.greek-added}[21:1]{.aside}

λεγων [αυτοις]{.greek-omitted} πορευθητε εις την κωμην [την]{.greek-omitted} απεναντι υμων και ευθεως ευρησετε ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο κυριος αυτων χρειαν εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον και πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται [και]{.greek-omitted} [ποιησαντες]{.greek-omitted} [εποιησαν]{.greek-added} [καθως]{.greek-omitted} [ως]{.greek-added} προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

[και]{.greek-added} ηγαγον την ονον και τον πωλον και επεθηκαν επανω αυτων τα ιματια αυτων και [επεκαθισεν]{.greek-omitted} [εκαθισεν]{.greek-added} επανω αυτων[21:7]{.aside}

ο δε πλειστος οχλος εστρωσαν [εαυτων]{.greek-omitted} τα ιματια [αυτων]{.greek-added} εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

και εισηλθ[εν]{.greek-supplied} [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις το ιερον του [θεου]{.greek-abbr} και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} παντας το[υ]{.unclear}[ς]{.greek-supplied} πωλουντας και αγοραζοντας εν τω [ιε]{.greek-supplied}ρω και τας τραπεζας των κολλυβιστων [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις [γεγραπται]{.greek-omitted} ο οικος μου οικος προσευχης κληθησεται υμεις δε [εποιησατε]{.greek-added} αυτον [εποιησατε]{.greek-omitted} σπηλαιον ληστων[21:13]{.aside}

και προσηλθον αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω [ουκ]{.greek-added} ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων κατηρτισω αινον[21:16]{.aside}

και καταλιπων αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη εκει[21:17]{.aside}

πρωιας δε επαναγων εις την πολιν [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει μη φυλλα [μονον]{.greek-omitted} [μονα]{.greek-added} και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη παραχρημα η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη [η]{.greek-omitted} [συκη]{.greek-omitted}[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν εχητε πιστιν και μη διακριθητε ου μονον το της συκης ποιησετε αλλα καν τω ορει τουτω ειπητε αρθητι και βληθητι εις την θαλασσαν γενησεται[21:21]{.aside}

και παντα οσα [εαν]{.greek-omitted} [αν]{.greek-added} αιτησητε εν τη προσευχη πιστευοντες ληψεσθε[21:22]{.aside}

και ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις σοι [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω υμας καγω λογον ενα ον εαν ειπητε μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο παρ εαυτοις λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει ημιν δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ως προφητην[21:26]{.aside}

και αποκριθεντες [τω]{.greek-omitted} [ιησου]{.greek-omitted} ειπον ουκ οιδαμεν εφη [αυτοις]{.greek-omitted} και αυτος [αυτοις]{.greek-added} ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} τεκνα δυο και προσελθων τω πρωτω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

[εγω]{.greek-added} [[κυριε]{.greek-abbr}]{.greek-added} [και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [ου]{.greek-omitted} [ουκ]{.greek-added} [θελω]{.greek-omitted} [υστερον]{.greek-omitted} [δε]{.greek-omitted} [μεταμεληθεις]{.greek-omitted} [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:29]{.aside}

[και]{.greek-omitted} προσελθων [δε]{.greek-added} [εν]{.greek-added} τω δευτερω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [ωσαυτως]{.greek-omitted} [τεκνον]{.greek-added} [υπαγε]{.greek-added} [εργαζου]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [αμπελωνι]{.greek-added} [μου]{.greek-added} ο δε αποκριθεις ειπεν [εγω]{.greek-omitted} [κυριε]{.greek-omitted} [ου]{.greek-added} [δυναμαι]{.greek-added} και [ουκ]{.greek-omitted} [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:30]{.aside}

τις [ουν]{.greek-added} εκ των δυο [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο [πρωτος]{.greek-omitted} [δευτερος]{.greek-added} λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ προς υμας [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω οι δε τελωναι και αι πορναι επιστευσαν αυτω υμεις δε ιδοντες ου μετεμεληθητε υστερον του πιστευσαι αυτω[21:32]{.aside}

αλλην παραβολην ακουσατε [ανθρωπος]{.greek-abbr} τις ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} και ωρυξεν εν αυτω ληνον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε ηγγισεν ο καιρος των καρπων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους [αυτου]{.greek-omitted} [αυτων]{.greek-added}[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν [και]{.greek-added} αυτοις ωσαυτως[21:36]{.aside}

υστερον [δε]{.greek-omitted} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους τον υιον αυτου λεγων εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν [αυτον]{.greek-added}[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις ε[κ]{.unclear}εινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα [εκδωσεται]{.greek-omitted} [εκδοσεται]{.greek-added} αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις καιροις αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε ανεγνωτε εν [ταις]{.greek-omitted} [γραφαις]{.greek-omitted} [τη]{.greek-added} [γραφη]{.greek-added} λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται εθνει ποιουντι τους καρπους [αυτης]{.greek-omitted} [αυτου]{.greek-added}[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση λικμησει αυτον[21:44]{.aside}

και ακουσαντες οι αρχιερεις και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} [εγνωσαν]{.greek-added} [οτι]{.greek-added} [προς]{.greek-added} [αυτους]{.greek-added} τας παραβολας [ταυτας]{.greek-added} [ειπε]{.greek-added} [αυτου]{.greek-omitted} [εγνωσαν]{.greek-omitted} [οτι]{.greek-omitted} [περι]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted}[21:45]{.aside}

και [ζητουντες]{.greek-omitted} [εζητουν]{.greek-added} αυτον κρατησαι εφοβηθησαν [δε]{.greek-added} τους οχλους [επειδη]{.greek-omitted} [οτι]{.greek-added} ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις [παλιν]{.greek-added} ο [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} ειπεν αυτοις εν παραβολαις λεγων[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω αυτου[22:2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου καλεσαι τους κεκλημενους εις [τους]{.greek-omitted} [γαμους]{.greek-omitted} [τον]{.greek-added} [γαμον]{.greek-added} και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα σιτιστα τεθυμενα [εισι]{.greek-added} και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον [ο]{.greek-omitted} [ος]{.greek-added} δε εις την [εμποριαν]{.greek-omitted} [εμπ[ο]{.greek-supplied}ρειαν]{.greek-added} αυτου[22:5]{.aside}

οι δε λοι[π]{.unclear}οι κρατησαντ[ες]{.greek-supplied} τους δουλου[ς]{.unclear} αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς [εκεινος]{.greek-omitted} ωργισθη και πεμψας τα στρατευματα αυτου [απωλεσεν]{.greek-omitted} [απωλεσε]{.greek-added} τους φονεις εκεινους και την πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενεπρησε]{.greek-added}[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και [εξελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} οι δουλοι εκεινοι εις τας οδους συνηγαγον παντας οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

[ε]{.greek-supplied}ισελθων δε ο [βασ]{.unclear}ιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου [χειρας]{.greek-added} [και]{.greek-added} ποδας [και]{.greek-omitted} [χειρας]{.greek-omitted} αρατε αυτον [εντευθεν]{.greek-added} και [εκβαλετε]{.greek-omitted} [βαλλετε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} συμβουλιον ελαβον οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των ηρωδιανων [λεγοντες]{.greek-omitted} διδασκαλε οιδαμεν οτι αληθης ει και την οδον του [θεου]{.greek-abbr} [εν]{.greek-omitted} [αληθεια]{.greek-omitted} διδασκεις και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι κηνσον καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του κηνσου οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις [αποδοτε]{.greek-omitted} [απο]{.greek-added} [δοτε]{.greek-added} ου[ν]{.unclear} [τ]{.unclear}α καισαρ[ος]{.greek-supplied} [και]{.greek-supplied}σαρι και τα του [θεου]{.greek-abbr} τ[ω]{.greek-supplied} [θεω]{.greek-abbr}[22:21]{.aside}

[και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} ακουσαντες εθαυμασαν και [α]{.greek-supplied}φεντες αυτον απηλθον[22:22]{.aside}

[εν]{.greek-supplied} εκεινη τη ημερα προση[λ]{.unclear}θον αυτω [οι]{.greek-added} σαδδουκαιοι οι λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης ειπεν εαν τις αποθανη μη εχων τεκνα επιγαμβρευσει ο αδελφος αυτου [την]{.greek-omitted} [τη]{.greek-added} [γυναικα]{.greek-omitted} [γυναικι]{.greek-added} αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος γαμησας ετελευτησεν και μη εχων σπερμα [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} την γυναικα [αυτου]{.greek-omitted} τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ [ομοιως]{.greek-added} εσχον αυτην[22:28]{.aside}

αποκριθεις δε [ο]{.greek-supplied} [ιησους]{.greek-abbr} ειπεν αυτοις πλανασθε μη ειδοτες τας γραφας μηδε την δυναμι[ν]{.unclear} του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμου[σιν]{.greek-supplied} ουτε εκγαμιζονται αλλ ως αγγελοι του [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ [και]{.greek-omitted} ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε [φαρισαιοι]{.greek-omitted} [φαρισσα[ιο]{.greek-supplied}ι]{.greek-added} ακουσαντες [ο]{.unclear}τι [εφιμωσεν]{.greek-omitted} [απεστομισε]{.greek-added} τους σαδδουκαιους [σ]{.greek-supplied}υνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [[κυριος]{.greek-abbr}]{.greek-added} [[κυριον]{.greek-abbr}]{.corr} τον [θεον]{.greek-abbr} σου εν ολη [τη]{.greek-added} καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὐτῆ]{.greek-added} αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος εστιν λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν [θω]{.greek-omitted} [[θεω]{.greek-abbr}]{.greek-added} τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} [[κυριον]{.greek-abbr}]{.greek-added} [αυτον]{.greek-added} καλει [αυτον]{.greek-omitted} [κυριον]{.greek-omitted} πως υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added}[22:45]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} [αποκριθηναι]{.greek-added} αυτω [αποκριθηναι]{.greek-omitted} λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλης]{.greek-added} τοις οχλοις [και]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted}[23:1]{.aside}

λεγων επι της μωσεως καθεδρας εκαθισαν οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα [εαν]{.greek-omitted} [αν]{.greek-added} ειπωσιν υμιν [ποιειν]{.greek-added} [τηρειν]{.greek-omitted} [τηρειτε]{.greek-omitted} [και]{.greek-omitted} ποιειτε κατα δε τα εργα αυτων μη ποιειτε [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου ποιουσιν[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [[δε]{.greek-supplied}σμευουσι]{.greek-added} γαρ φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε [τα]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted} [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} [δε]{.greek-omitted} [γαρ]{.greek-added} τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} την πρωτοκλισιαν εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

[και]{.greek-omitted} [τους]{.greek-omitted} [ασπασμους]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [αγοραις]{.greek-omitted} και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι ραββι[23:7]{.aside}

υμεις δε μη κληθητε ραββι εις γαρ εστιν υμων [διδασκαλος]{.greek-added} [ο]{.greek-omitted} [καθηγητης]{.greek-omitted} ο [χριστος]{.greek-abbr} [παντες]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [αδελφοι]{.greek-omitted} [εστε]{.greek-omitted}[23:8]{.aside}

και [πατερα]{.greek-abbr} μη [καλεσητε]{.greek-omitted} [καλεσετε]{.greek-added} υμων επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} [υμ[ει]{.unclear}ς]{.greek-added} [δε]{.greek-added} [π[α]{.unclear}ντες]{.greek-added} [αδελφοι]{.greek-added} [εστε]{.greek-added}[23:9]{.aside}

μηδε [κληθητε]{.greek-omitted} [κληθειτε]{.greek-added} καθηγηται εις γαρ [εστιν]{.greek-added} υμω[ν]{.greek-supplied} [εστιν]{.greek-omitted} [ο]{.greek-omitted} καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} και [ο[υ]{.greek-supplied}δε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθ[ειν]{.greek-supplied}]{.greek-added} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χηρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι περιαγετε την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν γενηται ποιειτε αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν ομοση εν τω ναω ουδεν [εστιν]{.greek-omitted} [εστι]{.greek-added} ος δ αν ομοση εν τω χρυσω του ναου οφειλει[23:16]{.aside}

μωροι και τυφλοι τις [γαρ]{.greek-omitted} μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} ομοσ[η]{.greek-supplied} [ε]{.unclear}ν τω θυσιαστηριω ουδεν εστιν ος δ αν [ομ]{.unclear}οση εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι [τι]{.greek-omitted} [τις]{.greek-added} γαρ μειζον το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ε]{.greek-supplied}πανω αυτου[23:20]{.aside}

και ο ομοσας εν τω ναω [ο]{.unclear}μνυει εν αυτω και εν τω κατοικησαντι [αυτον]{.greek-omitted} [αυτω]{.greek-added}[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι αποδεκατουτε το ηδυοσμον και το [ανηθον]{.greek-omitted} [ανιθον]{.greek-added} και το [κυμινον]{.greek-omitted} [κυμηνον]{.greek-added} και αφηκατε τα βαρυτερα του νομου την κρισιν και τον ελεον και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιε[ν]{.unclear}αι[23:23]{.aside}

[οδηγοι]{.greek-omitted} τυφλοι οι διυλιζοντες τον κωνωπα την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι [υμ[―]{.gap}]{.greek-added} [υμιν]{.corr} γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι καθαριζετε το εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και αδικιας[23:25]{.aside}

[φαρισαιε]{.greek-omitted} [φαρισσαιε]{.greek-added} τυφλε καθαρισον πρωτον το εντος του ποτηριου [και]{.greek-omitted} [της]{.greek-omitted} [παροψιδος]{.greek-omitted} ινα γενηται και το εκτος [αυτων]{.greek-omitted} [αυτου]{.greek-added} καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} υποκριται οτι παρομοιαζετε ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν [οστεων]{.greek-omitted} [οστεα]{.greek-added} νεκρων και πασης ακαθαρσιας[23:27]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις εξωθεν μεν φαινεσθε τοις [ανθρωποις]{.greek-abbr} δικαιοι [ε]{.unclear}σωθεν δε μεστοι εστε υποκρισεως και [α]{.unclear}νομιας[23:28]{.aside}

ουαι υμιν γραμματεις και [φαρισαιοι]{.greek-omitted} [φαρισσαι[οι]{.unclear}]{.greek-added} υποκριται οτι οικοδομειτε τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει ημεν εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν ημεν κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε [εαυτοις]{.greek-omitted} [αυτοις]{.greek-added} οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως [φυγητε]{.greek-omitted} [φυγετε]{.greek-added} απο της κρισεως της γεεννης[23:33]{.aside}

[δ]{.unclear}ια τουτο ιδου εγω [αποστελλω]{.greek-omitted} [αποστελω]{.greek-added} προς υμας προφητας και σοφους και γραμματεις [και]{.unclear} εξ αυτων αποκτενειτε και [σταυρωσετε]{.greek-abbr} [κ]{.unclear}αι εξ αυτων μαστιγωσετε εν [ταις]{.greek-omitted} [τη]{.greek-added} [συναγωγαις]{.greek-omitted} [συνα[γ]{.greek-supplied}ωγη]{.greek-added} υμων και διωξετε απο πολεως [ε]{.greek-supplied}ις πολιν[23:34]{.aside}

οπως ελθη εφ υμας παν αιμα δικαιον εκχυνομενον επι της γης απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η αποκτενουσα τους προφητας και λιθοβολουσα τους [απεσταλμενους]{.greek-omitted} [αποσταλμενους]{.greek-added} προς αυτην ποσακις ηθελησα επισυναγαγειν [τα]{.corr} τεκνα σου ον τροπον επισυναγει ορνις τα [νοσσια]{.greek-omitted} [νοσια]{.greek-added} εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη με ιδητε απ αρτι εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτου επιδειξαι [αυτω]{.greek-omitted} τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις [ου]{.greek-omitted} βλεπετε [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου [μη]{.greek-added} καταλυθησεται [[καταλυθη]{.corr}]{.greek-added}[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται [αυτου]{.greek-added} κατ ιδιαν λεγοντες [διδασκαλε]{.greek-added} ειπε ημιν [ταυτα]{.greek-added} ποτε [ταυτα]{.greek-omitted} εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [β]{.unclear}[λεπετε]{.greek-supplied} μη τις υμας πλανηση[24:4]{.aside}

πολλοι γ[αρ]{.greek-supplied} [ε]{.greek-supplied}λευσονται επι τω ονοματι μου [λεγοντες]{.greek-supplied} [οτι]{.greek-added} εγω ειμι ο [χριστος]{.greek-abbr} και πολλους πλανησ[ουσιν]{.greek-supplied}[24:5]{.aside}

[μελλησετε]{.greek-omitted} [μελησετε]{.greek-added} δε ακουειν πολεμους και ακοας πολεμ[ων]{.greek-supplied} ορατε μη θροεισθε δει γαρ παντα γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εστι]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και [λι]{.greek-added} [λοιμοι]{.corr} και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη ωδινων[24:8]{.aside}

τοτε [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} υμας εις [θλιψιν]{.greek-omitted} [θλιψεις]{.greek-added} και [αποκε]{.greek-added} [αποκτενουσιν]{.corr} υμας και εσεσθε μισουμενοι υπο παντων [των]{.greek-omitted} [εθνων]{.greek-omitted} δια το [ονο]{.greek-supplied}μα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται [πολλ]{.greek-supplied}οι και αλληλους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} και [μισ]{.greek-supplied}ησουσιν αλληλους[24:10]{.aside}

και πολλοι ψευδο[προ]{.greek-supplied}φηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} [πο]{.greek-supplied}λλους[24:11]{.aside}

και δια το πληθυνθηναι την [αν]{.unclear}ομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

[ο]{.greek-supplied} δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται [τουτο]{.greek-omitted} το ευαγγελιον [τουτο]{.greek-added} της βασιλειας εν ολη τη οικουμενη εις μαρτυριον [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν ιδητε το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου εστως [[εστος]{.corr}]{.greek-added} εν τοπω αγιω [αυτου]{.greek-added} ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν [επι]{.greek-omitted} [εις]{.greek-added} τα ορη[24:16]{.aside}

ο επι του δωματος μη [καταβαινετω]{.greek-omitted} [καταβατω]{.greek-added} αραι τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων [εν]{.greek-added} [χειμωνος]{.greek-omitted} [χειμωνι]{.greek-added} [μηδε]{.greek-omitted} [η]{.greek-added} [εν]{.greek-added} σαββατω[24:20]{.aside}

εσται γαρ τοτε θλιψις μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν ουδ ου μη γενηται[24:21]{.aside}

και ει μη εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ω[δε]{.unclear} ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια [μεγαλα]{.greek-omitted} [και]{.greek-supplied} τερατα ωστε πλανησαι ει δυνα[τον]{.greek-supplied} και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υ[μιν]{.greek-supplied}[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω [εστιν]{.greek-omitted} [εστι]{.greek-added} μη εξελθητε ιδου εν τοις ταμειοις μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου [γαρ]{.greek-omitted} εαν η το πτωμα εκει [συναχθ]{.unclear}[η]{.greek-supplied}σονται [και]{.greek-added} οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο [του]{.greek-omitted} [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανη[σε]{.greek-supplied}τ[αι]{.greek-supplied} το σημει[ο]{.greek-supplied}ν του [υιου]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και [τοτε]{.greek-omitted} κοψονται [πασαι]{.greek-omitted} α[ι]{.unclear} φυλαι [πασ[ε]{.unclear}]{.greek-added} της γης και οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και αποστελει τους αγγελους αυτου μετα [φωνης]{.greek-added} σαλπιγγος [φωνης]{.greek-omitted} μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξουσι]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-abbr} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος αυτης γενηται απαλος και τα φυλλα εκφυη γινωσκετε οτι εγγυς το θερος[24:32]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις οταν ιδητε ταυτα παντα γινωσκετε οτι εγγυς εστιν επι θυραις[24:33]{.aside}

αμην λεγω υμιν ου μη παρελθη η γενεα αυτη εως αν [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσονται οι δε λογοι μου ου μη παρελθωσιν[24:35]{.aside}

περι δε της ημερας [και]{.greek-added} [της]{.greek-added} [ωρας]{.greek-added} εκεινης [και]{.greek-omitted} [ωρας]{.greek-omitted} ουδεις οιδεν ουδε οι αγγελοι [των]{.greek-omitted} [ουρανων]{.greek-omitted} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

[και]{.greek-added} ωσπερ [γαρ]{.greek-omitted} ησαν εν ταις ημεραις ταις προ του κατακλυσμου τρωγοντες και πινοντες γαμουντες και εκγαμιζοντες [αχρι]{.greek-omitted} [αχρις]{.greek-added} ης ημερας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

[τοτε]{.greek-supplied} [δυ]{.greek-supplied}ο εσονται εν τω αγρω ο εις παρα[λαμβαν]{.greek-supplied}εται και ο εις αφιεται[24:40]{.aside}

δυο αλη[θουσαι]{.greek-supplied} [ε]{.greek-supplied}ν τω μυλωνι μια παραλαμβανεται [και]{.greek-supplied} [μι]{.greek-supplied}[α]{.unclear} αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι [ο]{.greek-supplied}υκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων [ε]{.greek-supplied}ρχεται[24:42]{.aside}

εκεινο δε γινωσκετε οτι ει ηδει ο [οικοδεσ[―]{.gap}οτης]{.greek-added} [οικοδεσποτης]{.corr} ποια φυ[λ]{.unclear}ακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν [ειασεν]{.greek-omitted} [ειασε]{.greek-added} [διορυγηναι]{.greek-omitted} [διωρυγηναι]{.greek-added} την οικιαν αυτου[24:43]{.aside}

δια τουτο [ουν]{.greek-added} [κ]{.unclear}αι [υμεις]{.greek-omitted} [ημεις]{.greek-added} γινεσθε ετοιμοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον κατεστησεν ο [κυριος]{.greek-abbr} [αυτου]{.greek-omitted} επι της θεραπειας αυτου του διδοναι [αυτοις]{.greek-omitted} [αυτω]{.greek-added} την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

[αμην]{.greek-added} αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασ[ι]{.unclear}]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους σ[υνδ]{.greek-supplied}ουλο[υ]{.greek-supplied}ς [αυ[τ]{.greek-supplied}ου]{.greek-added} [εσ]{.unclear}θιειν [δε]{.greek-omitted} [τε]{.greek-added} και πινειν μ[ε]{.unclear}τα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις [απαντησιν]{.greek-omitted} [συναντησιν]{.greek-added} του νυμφιου[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και [αι]{.greek-omitted} πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον [εν]{.greek-added} [τοις]{.greek-added} [αγγειοις]{.greek-added} [αυτων]{.greek-added}[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρ[ονιζοντος]{.greek-supplied} δε του νυμφιου ενυσταξαν [π]{.unclear}[ασαι]{.greek-supplied} [και]{.greek-supplied} [εκαθευδον]{.greek-supplied}[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε [ηγερθησαν]{.greek-omitted} [εγερθησαν]{.greek-added} πασαι αι παρθενοι [εκειναι]{.greek-omitted} και εκοσμησαν [[εκοσμισαν]{.corr}]{.greek-added} τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε [υμιν]{.greek-added} [ημιν]{.corr} εκ του ελαιου υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε ουκ αρκεση [υμιν]{.greek-added} [ημιν]{.corr} και υμιν πορευεσθε δε μαλλον προς τους πωλουντας και αγορασατε [εαυταις]{.greek-omitted}[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους [και]{.greek-omitted} [εκλεισθη]{.greek-omitted} [η]{.greek-omitted} [θυρα]{.greek-omitted}[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα [υμας]{.unclear}[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την [ημε]{.unclear}ραν [ουδε]{.greek-omitted} [ουτε]{.greek-added} την ωραν εν η ο υιος του [αν]{.unclear}θρωπου ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα [αυτου]{.greek-omitted} [αυτω]{.greek-added}[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα πεντε [ταλλαντα]{.greek-added} [ταλαντα]{.corr}[25:16]{.aside}

ωσαυτως και ο τα δυο [εκερδησεν]{.greek-omitted} [εκερδησε]{.greek-added} και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και [απεκρυψεν]{.greek-omitted} [απεκρυψε]{.greek-added} το αργυριον του [κυριου]{.greek-abbr} αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο κυριος των δουλων εκεινων και συναιρει μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη [δε]{.greek-omitted} αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ει[λ]{.unclear}ηφως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} [εγνως]{.greek-added} [εγνων]{.corr} σε οτι σκληρος [[ανθρωπος]{.greek-abbr}]{.greek-added} ει [ανθρωπος]{.greek-omitted} θεριζων οπου ουκ εσπει[ρ]{.greek-supplied}ας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις α[πελθων]{.greek-supplied} [εκρυψα]{.greek-omitted} [απεκρυψα]{.greek-added} το ταλαντον σου εν τη γη [ιδε]{.greek-supplied} [εχεις]{.greek-supplied} το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ει[πεν]{.greek-supplied} αυτω πονηρε δουλε και οκνηρε ηδεις [οτι]{.greek-supplied} θεριζω οπου ουκ εσπειρα και συν[αγω]{.greek-supplied} οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν [βα[λειν]{.greek-supplied}]{.greek-added} [σε]{.greek-supplied} [βαλειν]{.greek-omitted} το αργυριον μου τοις τραπεζιτ[αις]{.greek-supplied} και ελθων εγω εκομισαμην αν [το]{.greek-supplied} [εμον]{.greek-supplied} συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το [τα]{.greek-supplied}λαντον και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον [εκβαλετε]{.greek-omitted} [εκβαλλετε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο [κλαυθμος]{.greek-omitted} [κλαθμος]{.greek-added} και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε καθισει επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και [αφοριει]{.greek-omitted} [αφορισει]{.greek-added} αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και [εδωκατε]{.greek-omitted} [εδοκατε]{.greek-added} μοι φαγειν εδιψησα και εποτισατε με ξενος ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και [περιεβαλετε]{.greek-omitted} [περιεβαλλετε]{.greek-added} με ησθενησα και επεσκεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτ[ε]{.greek-supplied} [σε]{.greek-supplied} [ε]{.unclear}ιδομεν πεινωντα και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και συνηγαγομεν η γυμνον και [περιεβαλομεν]{.greek-omitted} [περιεβαλλομεν]{.greek-added}[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων πορευεσθε απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοι[ς]{.unclear} αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμ[νος]{.greek-supplied} [και]{.greek-supplied} ου [περιεβαλετε]{.greek-omitted} [περιεβαλλετε]{.greek-added} με ασθενης κ[αι]{.greek-supplied} [εν]{.greek-supplied} [φυ]{.greek-supplied}λακη και ουκ επεσκεψασθε με[25:43]{.aside}

[τοτε]{.greek-supplied} αποκριθησονται και αυτοι λεγο[ντες]{.greek-supplied} [κυριε]{.greek-abbr} ποτε σε ειδομεν πεινωντα η δι[ψωντα]{.greek-supplied} η ξενον η γυμνον η ασθενη η εν [φυλακη]{.greek-supplied} και ου διηκονησαμεν σοι[25:44]{.aside}

το[τε]{.greek-supplied} [απο]{.greek-supplied}κριθησεται αυτοις λεγων [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} εφ οσ[ον]{.greek-supplied} [ου]{.greek-supplied}κ εποιησατε ενι τουτων των ελαχ[ιστων]{.greek-supplied} ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} [μαθηταις]{.greek-omitted} [μαθητας]{.greek-added} αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το σταυρωθηναι[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και [συνεβουλευσαντο]{.greek-omitted} [εβουλευσαντο]{.greek-added} ινα τον [ιησουν]{.greek-abbr} δολω [κρατησωσιν]{.greek-omitted} [κρατησωσι]{.greek-added} και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον [μ]{.unclear}υρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} [ειπε]{.greek-supplied}ν αυτοις τι κοπους παρεχετε τη γυ[ναικ]{.greek-supplied}ι εργον [γαρ]{.greek-omitted} καλον ειργασατο εις εμε[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} [τους]{.greek-supplied} πτωχους [γαρ]{.greek-added} [παντοτε]{.greek-added} εχετε με[θ]{.greek-supplied} [ε]{.greek-supplied}αυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον [τουτο]{.greek-omitted} επι του σωματος μου προς το ενταφιασαι με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε μοι δουναι καγω [η]{.greek-added} [υμιν]{.corr} παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες αυτω που θελεις [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν τ[ο]{.unclear} πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μ[ετα]{.greek-supplied} των δωδεκα[26:20]{.aside}

και εσθιοντων αυτω[ν]{.greek-supplied} ειπεν αμην λεγω υμιν [οτι]{.greek-omitted} εις εξ υμ[ω]{.unclear}[ν]{.greek-supplied} παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρ[α]{.unclear} ηρξαντο λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω τρυβλιω την χειρα ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου [αι]{.greek-added} [ουαι]{.corr} δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μητι εγω ειμι ραββι λεγει αυτω συ ειπας[26:25]{.aside}

[ε]{.greek-supplied}σθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} [τον]{.greek-omitted} αρτον και ευχαριστησας [ε[―]{.gap}λασε]{.greek-added} [εκλασεν]{.greek-omitted} [[εκλασε]{.corr}]{.greek-added} και [εδιδου]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστη]{.greek-added} [εστιν]{.greek-omitted} [[εστι]{.corr}]{.greek-added} το σωμα μου [το]{.greek-added} [υπερ]{.greek-added} [υμων]{.greek-added} [κλω[μ]{.unclear}ενον]{.greek-added} [εις]{.greek-added} [αφεσιν]{.greek-added} [αμαρτιων]{.greek-added}[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του γεννηματος της αμπελου εως [τ[α]{.unclear}ς]{.greek-added} [της]{.corr} ημερας εκεινης οταν αυτο πινω μεθ υμων καινον εν τη βασιλεια του πατρος μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες [υ]{.unclear}[μεις]{.greek-supplied} σκανδαλισθησεσθε εν εμοι εν τ[η]{.greek-supplied} [νυκτι]{.greek-supplied} ταυτη γεγραπται γαρ παταξ[ω]{.unclear} [τον]{.greek-supplied} ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησ[ονται]{.greek-supplied}]{.greek-added} τα προβατα της ποιμνης[26:31]{.aside}

μ[ετα]{.greek-supplied} [δε]{.greek-supplied} το εγερθηναι με προαξω υμας εις τ[ην]{.greek-supplied} [γαλιλαιαν]{.greek-supplied}[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω [δε]{.greek-omitted} ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν [δε]{.unclear}η με συν σοι αποθανειν ου μη σε [απ]{.greek-supplied}αρνησωμαι ομοιως [δε]{.greek-omitted} και παντες [οι]{.greek-supplied} μαθηται ειπον[26:35]{.aside}

τοτε ερχεται με[τ]{.greek-supplied} αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον [γ]{.greek-supplied}εθσημανη και λεγει τοις μαθηταις [αυτου]{.greek-added} καθισατε αυτου εως ου απελθων προσευξωμαι [εκει]{.greek-omitted}[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και [προσελθων]{.greek-omitted} [προελθων]{.greek-added} μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ [και]{.greek-added} [αναστας]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [προσευχης]{.greek-added}[26:39]{.aside}

[και]{.greek-omitted} ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} [προ]{.greek-added} [προθυμον]{.greek-omitted} [θυμον]{.greek-added} η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} [μου]{.greek-omitted} ει ου δυναται [τουτο]{.greek-omitted} το ποτηριον παρελθειν [απ]{.greek-omitted} [εμου]{.greek-omitted} εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων ευρισκει αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου [γαρ]{.greek-added} ηγγικεν η ω[ρα]{.greek-supplied} [και]{.greek-supplied} ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται [εις]{.greek-supplied} [χειρας]{.greek-supplied} [[ανθρωπων]{.greek-abbr}]{.greek-added} αμαρτωλων[26:45]{.aside}

εγειρεσθε α[γωμεν]{.greek-supplied} ιδου ηγγικεν ο παραδιδους [με]{.greek-supplied}[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} χαιρε ραββι και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ ω παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις [τον]{.greek-added} [των]{.corr} μετα [ιησου]{.greek-abbr} εκτεινας την χειρα [απεσπασεν]{.greek-omitted} [την]{.greek-omitted} [μαχαιραν]{.greek-omitted} αυτου και [παταξας]{.greek-omitted} [σπασαμενος]{.greek-added} [μαχαιραν]{.greek-added} [επαταξε]{.greek-added} τον δουλον του αρχιερεως [και]{.greek-added} αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον σου την μαχαιραν εις [τον]{.greek-omitted} [τοπον]{.greek-omitted} [την]{.greek-added} [θηκην]{.greek-added} αυτης παντες γαρ οι λαβοντες μαχαιραν εν μαχαιρα αποθανουνται[26:52]{.aside}

η δοκεις οτι ου δυναμαι αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην [εξηλθετ[ο]{.unclear}]{.greek-added} [εξηλθετε]{.corr} μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται [παντες]{.greek-omitted} αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες [τον]{.greek-omitted} [αυτον]{.greek-added} [ιησουν]{.greek-omitted} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος ηκολουθει αυτω [απο]{.greek-omitted} μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και [ολον]{.greek-added} το συνεδριον [ολον]{.greek-omitted} εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως θανατωσωσιν αυτον[26:59]{.aside}

[και]{.greek-omitted} [ουχ]{.greek-omitted} [ευρον]{.greek-omitted} και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας [πλην]{.greek-omitted} [αμην]{.greek-added} λεγω υμιν απ αρτι οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων τ[ου]{.greek-supplied} [[ουρανου]{.greek-abbr}]{.greek-supplied}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματι[α]{.greek-supplied} αυτου λεγων οτι [εβλασφημησεν]{.greek-omitted} [εβλασφημησε]{.greek-added} τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε [αποκριθεντες]{.greek-omitted} [αποκριθεντος]{.greek-added} ειπον ενοχος θανατου εστιν[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και εκολαφισαν αυτον οι δε ερραπισαν[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του [γαλιλαιο]{.greek-supplied}υ[26:69]{.aside}

ο δε ηρ[ν]{.greek-supplied}ησατο εμπροσθεν [αυτων]{.greek-supplied} [π]{.greek-supplied}αντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

[εξελθοντα]{.greek-omitted} [[―]{.gap}ν]{.greek-added} δε [αυτον]{.greek-omitted} εις τον πυλωνα ειδεν αυτον [αλλη]{.greek-supplied} [κ]{.greek-supplied}[α]{.unclear}ι λεγει [αυτοις]{.greek-omitted} [αυτω]{.greek-added} εκει και ουτος ην [μετα]{.greek-supplied} [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν [ηρνησα]{.greek-supplied}το μεθ ορκου οτι ουκ οιδα [τον]{.greek-supplied} [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες [οι]{.greek-supplied} [εστω]{.greek-supplied}τες ειπον τω πετρω αληθως και [συ]{.greek-supplied} [εξ]{.greek-supplied} αυτων ει και γαρ η λαλια σου δηλον [σε]{.greek-supplied} [π]{.greek-supplied}οιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν [κ]{.greek-supplied}αι ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} [κ]{.unclear}αι ευθεως αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[26:74]{.aside}

και [ε]{.greek-supplied}μνησθη ο πετρος του ρηματος του [ιησου]{.greek-abbr} [ε]{.greek-supplied}ιρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν [αυτον]{.greek-omitted} ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε ιδων ιουδας ο [παραδιδους]{.greek-omitted} [παραδους]{.greek-added} αυτον οτι κατεκριθη μεταμεληθεις [απεστρεψεν]{.greek-omitted} [απεστρεψε]{.greek-added} τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε ειπον τι προς ημας συ [οψει]{.greek-omitted} [οψη]{.greek-added}[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον κορβαναν επει τιμη αιματος [εστιν]{.greek-omitted} [εστι]{.greek-added}[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο [και]{.greek-added} εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και [ε]{.unclear}δωκαν αυτα εις τον αγρον του κεραμεως καθα [συνεταξεν]{.greek-omitted} [συνεταξε]{.greek-added} μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του [ηγεμωνος]{.greek-added} [ηγεμονος]{.corr} και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον [υπο]{.greek-omitted} [απο]{.greek-added} των αρχιερεων και [των]{.greek-omitted} πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε [την]{.greek-added} εορτην [ειωθει]{.greek-omitted} [ειωθεν]{.greek-added} ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον [βαραβαν]{.greek-added} [βαραββαν]{.corr}[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος [απεστειλεν]{.greek-omitted} [αποστελλει]{.greek-added} προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον [σημερον]{.greek-omitted} κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-omitted} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν αυτω παντες [σταυρωθητω]{.greek-abbr}[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες [σταυρωθητω]{.greek-abbr}[27:23]{.aside}

ιδων δε ο πιλατος οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγελωσας]{.greek-added} παρεδωκεν ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ο[λ]{.greek-supplied}ην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον π[ε]{.unclear}[ρι]{.greek-supplied}εθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και γονυπετησαντες [εμπροσθεν]{.greek-omitted} [αυτου]{.greek-omitted} [αυτον]{.greek-added} [ενεπαιζον]{.greek-omitted} [αυτω]{.greek-omitted} [λεγοντες]{.greek-omitted} [χαιρε]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [των]{.greek-omitted} [ιουδαιων]{.greek-omitted}[27:29]{.aside}

[και]{.greek-omitted} [εμπτυσαντες]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted} ελαβον τον καλαμον και ετυπτον [εις]{.greek-omitted} την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} [κυρ[ι]{.unclear}ναιον]{.greek-added} [κυρηναιον]{.corr} ονοματι σιμωνα [τουτον]{.greek-omitted} [του]{.greek-added} ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον [γολγοθα]{.greek-omitted} [γολγοθαν]{.greek-added} [ο]{.greek-omitted} [ος]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} [λεγομενος]{.greek-omitted} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} πιειν[27:34]{.aside}

[σταυρωσαντες]{.greek-abbr} δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον [εκει]{.greek-omitted}[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-omitted} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουνται]{.greek-abbr} συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} [και]{.greek-added} καταβηθι απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως [δε]{.greek-omitted} και οι [αρχιερεις]{.greek-omitted} [αρχιρεις]{.greek-added} εμπαιζοντες μετα των γραμματεων και πρεσβυτερων και φαρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} [ινα]{.greek-added} [ιδωμεν]{.greek-added} και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω [νυν]{.greek-omitted} αυτον ει θελει αυτον [ειπεν]{.greek-omitted} [ειπαι]{.greek-added} γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι [συσταυρωθεντες]{.greek-abbr} αυτω ωνειδιζον [αυτον]{.greek-omitted} [αυτω]{.greek-added}[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας ενατης[27:45]{.aside}

περι δε την ενατην ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη [λεγων]{.greek-omitted} [και]{.greek-added} [ειπεν]{.greek-added} ηλι ηλι λιμα σαβαχθανι τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελ[ι]{.greek-supplied}πες[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες ελεγον οτι ηλιαν φωνει [ουτος]{.greek-omitted}[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας σωσων αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως [κατω]{.greek-omitted} [κατωθεν]{.greek-added} και η γη εσεισθη και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια ανεωχθησαν και πολλα σωματα των κεκοιμημενων αγιων ηγερθη[27:52]{.aside}

και [εξεθ]{.greek-added} [εξελθοντες]{.corr} εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} [υιος]{.greek-omitted} ην ουτος[27:54]{.aside}

ησαν δε εκει γυναικες πολλαι απο μακροθεν θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η μαγδαληνη και μαρια η του ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων [ζεβεδαιου]{.greek-omitted} [ζεβεδ[α]{.unclear}ιουν]{.greek-added}[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο [αριμαθαιας]{.greek-omitted} [αριμαθιας]{.greek-added} τουνομα ιωσηφ ος και αυτος [εμαθητευσεν]{.greek-omitted} [εμαθητευθη]{.greek-added} τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα [τω]{.greek-added} [ιωσηφ]{.greek-added}[27:58]{.aside}

και λαβων [το]{.greek-omitted} [σωμα]{.greek-omitted} [ο]{.greek-omitted} [ιωσηφ]{.greek-omitted} [ενετυλιξεν]{.greek-omitted} αυτο [ενετυλιξε]{.greek-added} σινδονι καθαρα[27:59]{.aside}

και εθηκεν αυτο εν τω καινω αυτου μνημειω ο [ην]{.greek-added} [ελατομησεν]{.greek-omitted} [λελατομημενον]{.greek-added} [εκ]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [πετρα]{.greek-omitted} [πετρας]{.greek-added} και προσκυλισας λιθον μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μ[αρ]{.unclear}ια η μαγδαληνη και η αλλη μαρια καθημ[εν]{.greek-supplied}αι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς πιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι [εκεινος]{.greek-omitted} ο πλανος [εκεινος]{.greek-added} ειπεν ετι ζων [οτι]{.greek-added} μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου [νυκτος]{.greek-omitted} κλεψωσιν αυτον [νυκτος]{.greek-added} και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} τω λαω ηγερθη απο των νεκρων και εσται η εσχατη πλανη χειρων της πρωτης[27:64]{.aside}

εφη δε αυτοις ο πιλατος [ε[χη]{.unclear}τε]{.greek-added} [ε[χ]{.unclear}ετε]{.corr} κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε δε σαββατων τη επιφωσκουση εις μιαν σαββατων [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} μαρια η μαγδαληνη και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-omitted} [[ουρανοθεν]{.greek-abbr}]{.greek-added} [και]{.greek-added} προσελθων [απεκυλισεν]{.greek-omitted} [απεκυλισε]{.greek-added} τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο [ως]{.greek-added} [ωσει]{.corr} νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} μη φοβεισθε υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον [εσταυρωμενον]{.greek-abbr} ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη [γαρ]{.greek-omitted} καθως ειπεν δευτε ιδετε [τον]{.greek-omitted} [τοπον]{.greek-omitted} οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ πορευθεισαι ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μ[νη]{.unclear}μειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

[ως]{.greek-omitted} [δε]{.greek-omitted} [επορευοντο]{.greek-omitted} [απαγγειλαι]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} και ιδου [ιησους]{.greek-abbr} απηντησεν αυταις λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με [οψονται]{.greek-omitted} [οψωνται]{.greek-added}[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

[κ]{.unclear}αι συνα[χθεντες]{.greek-supplied} μετα των πρεσβυτερων συμ[β]{.unclear}[ου]{.greek-supplied}λιον τε λαβοντες αργυρια ικ[ανα]{.greek-supplied} εδωκαν τοις στρατιωταις[28:12]{.aside}

λ[ε]{.unclear}[γοντες]{.greek-supplied} ειπατε οτι οι μαθηται αυτου [νυκτος]{.greek-supplied} ελθοντες εκλεψαν αυτον ημ[ων]{.greek-supplied} κοιμωμενων[28:13]{.aside}

και εαν ακουσ[θη]{.greek-supplied} τουτο επι του ηγεμονος ημει[ς]{.greek-supplied} [πεισομεν]{.greek-omitted} [πεισωμεν]{.greek-added} αυτον και [υμας]{.greek-omitted} [ημας]{.greek-added} αμε[ριμνους]{.greek-supplied} [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added}[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθη[σαν]{.greek-supplied} και διεφημισθη ο λογος ουτος παρα ιουδαιοις μεχρι της ση[μερον]{.unclear}[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του α[γιο]{.greek-supplied}υ [πνευματος]{.greek-abbr}[28:19]{.aside}

δι[δ]{.greek-supplied}ασκοντες αυτους τηρειν [παντ]{.unclear}α οσα [ενετειλαμην]{.greek-omitted} [ανετειλαμην]{.greek-added} [υμειν]{.greek-added} [υμιν]{.corr} και ι[δο]{.unclear}υ εγω μεθ υμων ειμι πασας τας [ημερ]{.unclear}ας εως της συντελειας του αιωνος αμην[28:20]{.aside}

