---
title: "Collation of Byz^RP^ vs 31067 (1067)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1067 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31067).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1067                                   	| λογος                              	|
| 1067 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1067 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1067               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1067                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1067 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1067                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 27

[μετ]{.greek-omitted} [ου]{.greek-omitted} [π]{.unclear}ολυ δε [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} κατ αυτης ανεμος τυφωνικος ο καλ[ουμενος]{.greek-supplied} [ευροκλυδων]{.greek-omitted} [[ευρακυλων]{.greek-supplied}]{.greek-added}[27:14]{.aside}

[συν]{.greek-supplied}αρ[πασ]{.greek-supplied}[θ]{.unclear}εντος δε τ[ου]{.greek-supplied} [πλοι]{.greek-supplied}ου [και]{.greek-supplied} μη δυναμενου αντοφθαλ[μειν]{.greek-supplied} [τω]{.greek-supplied} [ανε]{.greek-supplied}μω επιδοντες εφερ[ομε]{.greek-supplied}θα[27:15]{.aside}

νησιον δε τι υποδραμοντ[ες]{.unclear} κ[αλ]{.unclear}[ου]{.greek-supplied}μεν[ον]{.unclear} [κλαυδην]{.greek-omitted} [κλαυδα]{.greek-added} μολις ισχυσαμεν περικρατεις γενεσθαι της σκ[α]{.unclear}φ[ης]{.greek-supplied}[27:16]{.aside}

ην αραντες βοηθειαις εχρωντο [υποζωννυντες]{.greek-omitted} [υποζων[υ]{.unclear}ντες]{.greek-added} το πλοιον φοβου[μενοι]{.greek-supplied} τε μη εις την συρτην [εκπεσωσιν]{.greek-omitted} [εκπεσωσι]{.greek-added} χαλασαντες [το]{.greek-supplied} [σκευος]{.greek-supplied} [ουτω]{.greek-supplied}ς εφεροντο[27:17]{.aside}

σφοδρως [δε]{.greek-omitted} [τε]{.greek-added} χειμαζομενων ημων [τ]{.unclear}[η]{.greek-supplied} [εξης]{.greek-supplied} [ε]{.unclear}κβολην εποιουντο[27:18]{.aside}

και τη τριτη [ημερα]{.greek-added} αυτοχειρες [την]{.greek-supplied} σκευην του πλοιου [ερριψαμεν]{.greek-omitted} [ερριψαν]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [θαλασσαν]{.greek-added}[27:19]{.aside}

μητε δε [η]{.unclear}λιου μητ[ε]{.unclear} [αστ]{.greek-supplied}ρων [επιφαινοντων]{.greek-omitted} [επιφανεντων]{.greek-added} επι πλειονας ημερας χειμωνος τε ουκ [ολιγ]{.greek-supplied}ου επικειμενου λοιπον περιηρειτο [ελπις]{.greek-added} πασα [ελπις]{.greek-omitted} του σωζεσ[θ]{.unclear}αι ημας[27:20]{.aside}

πολλης [δε]{.greek-omitted} [τε]{.greek-added} ασιτιας υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων [ειπ]{.unclear}εν εδει μεν ω ανδρες π[ει]{.unclear}θαρχησαντας μοι μη αναγεσθαι απο της κρητης κερδησαι τε τ[η]{.unclear}ν υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα ν[υν]{.unclear} π[α]{.unclear}[ραι]{.greek-supplied}νω [[π]{.unclear}αντας]{.greek-added} υμας ευθυμειν αποβολη γαρ ψυχης ουδε[μια]{.greek-supplied} [εσται]{.greek-supplied} εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι αγγελος του [θεου]{.greek-abbr} ου ειμι ω [και]{.greek-omitted} λατρευω[27:23]{.aside}

λεγων μη φοβου παυλε καισα[ρ]{.unclear}ι σε [δ]{.unclear}[ει]{.greek-supplied} παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντα[ς]{.unclear} τους πλεοντ[ας]{.unclear} μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες πιστευω γ[α]{.unclear}ρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο δ[ιαφερομε]{.greek-supplied}νων ημων εν τω αδρια κατα μεσον της νυκτος υ[π]{.unclear}[ενοουν]{.greek-supplied} οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και β[ολ]{.unclear}ισαντ[ες]{.unclear} ευρ[ον]{.unclear} [οργυιας]{.greek-omitted} [εικοσι]{.greek-omitted} [βραχυ]{.greek-omitted} [δε]{.greek-omitted} [διαστησαντες]{.greek-omitted} [και]{.greek-omitted} [παλιν]{.greek-omitted} [βολισαντες]{.greek-omitted} [ευρον]{.greek-omitted} [οργυιας]{.greek-omitted} [δεκαπεντε]{.greek-omitted}[27:28]{.aside}

[και]{.greek-omitted} [βολισαντες]{.greek-omitted} [ευρον]{.greek-omitted} [οργυιας]{.greek-supplied} εικοσι βραχυ δε διαστησαντες και παλιν βολισαντες [ευρον]{.greek-supplied} [ο]{.greek-supplied}ργυιας δεκαπεντε[27:28 | instance no. 2]{.aside}

φοβουμενοι τε [μηπως]{.greek-omitted} [εις]{.greek-omitted} [μη]{.greek-added} [που]{.greek-added} [κατα]{.greek-added} τραχει[ς]{.unclear} τοπους [εκπεσωμεν]{.greek-omitted} [εμπεσωμεν]{.greek-added} εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ [πρωρας]{.greek-omitted} [πρωρης]{.greek-added} [αγκυρας]{.greek-added} μελλοντων [αγκυρας]{.greek-omitted} εκτεινειν[27:30]{.aside}

ειπεν ο παυλος τω εκατονταρχη και τοις στρατιωταις εαν μη ουτοι μεινωσιν εν τω πλοιω υμεις σωθηναι ου δυνασθε[27:31]{.aside}

τοτε [αποκοψαντες]{.greek-added} οι στρατιωται [απεκοψαν]{.greek-omitted} τα σχοινια της σκαφης [και]{.greek-omitted} ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου [ημελλεν]{.greek-omitted} ημερα [εμελλε]{.greek-added} γινεσθαι παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην [ημεραν]{.greek-added} σημερον [ημεραν]{.greek-omitted} προσδοκωντες ασιτοι διατελειτε μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας [προσλαβειν]{.greek-omitted} [μεταλαβειν]{.greek-added} τροφης τουτο γαρ προς της [υμετερας]{.greek-omitted} [ημετερας]{.greek-added} [σωτηριας]{.greek-abbr} υπαρχει ουδενος γαρ υμων θριξ εκ της κεφαλης [πεσειται]{.greek-omitted} [απολειται]{.greek-added}[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον [ευχαριστησεν]{.greek-omitted} [ηυχαριστησε]{.greek-added} τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

[ημεν]{.greek-omitted} [ημεθα]{.greek-added} δε [πασαι]{.greek-added} [ψυχαι]{.greek-added} εν τω πλοιω [αι]{.greek-omitted} [πασαι]{.greek-omitted} [ψυχαι]{.greek-omitted} διακοσιαι [εβδομηκοντα]{.greek-omitted} [εβδομηκοτα]{.greek-added} εξ[27:37]{.aside}

κορεσθεντες δε [της]{.greek-omitted} τροφης εκουφιζον το πλοιον [εκβαλλομενοι]{.greek-omitted} [εκβαλομενοι]{.greek-added} τον σιτον εις την θαλασσαν[27:38]{.aside}

[οτε]{.greek-omitted} [ως]{.greek-added} δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον [εβουλευσαντο]{.greek-omitted} [εβουλευοντο]{.greek-added} ει [δυνατον]{.greek-omitted} [δυναιντο]{.greek-added} εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα [ανεντες]{.greek-omitted} [ανιεντες]{.greek-added} τας ζευκτη[ρι]{.unclear}ας των πηδαλιων και επαραντες τον [αρτεμονα]{.greek-omitted} [αντιμονα]{.greek-added} τη πνεουση κατειχον [εις]{.greek-omitted} [τον]{.greek-omitted} [αιγιαλον]{.greek-omitted}[27:40]{.aside}

[και]{.greek-omitted} [τας]{.greek-omitted} [αγκυρας]{.greek-omitted} [περιελοντες]{.greek-omitted} [ειων]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [αμα]{.greek-omitted} [ανεντες]{.greek-omitted} [τας]{.greek-omitted} [ζευκτηριας]{.greek-omitted} [των]{.greek-omitted} [πηδαλιων]{.greek-omitted} [και]{.greek-omitted} [επαραντες]{.greek-omitted} [τον]{.greek-omitted} [αρτεμονα]{.greek-omitted} [τη]{.greek-omitted} [πνεουση]{.greek-omitted} [κατειχον]{.greek-omitted} εις τον αιγιαλον[27:40 | instance no. 2]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον [επωκειλαν]{.greek-omitted} [επεκιλαν]{.greek-added} την ναυν και η μεν πρωρα [ερεισασα]{.greek-omitted} [κρουσασα]{.greek-added} εμεινεν ασαλευτος η δε πρυμνα [ελυετο]{.greek-omitted} [διελυετο]{.greek-added} υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} μη τις εκκολυμβησας διαφυγη[27:42]{.aside}

ο δε [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του βουληματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τε τους δυναμενους κολυμβαν απορριψαντας πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους [μ]{.unclear}εν επι σανισιν ους δε επι τινων των απο του πλοιου και ουτως εγενετο παντας διασωθηναι επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες τοτε [επεγνωσαν]{.greek-omitted} [επεγνωμεν]{.greek-added} οτι [μελιτη]{.greek-omitted} [μελητη]{.greek-added} η νησος καλειται[28:1]{.aside}

οι [δε]{.greek-omitted} [τε]{.greek-added} βαρβαροι [π]{.unclear}αρειχον ου την τυχουσαν [φιλανθρωπιαν]{.greek-abbr} ημιν αναψαντες γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον εφεστωτα και δια το ψυχος[28:2]{.aside}

συστρεψαντος δε του παυλου φρυγανων [τι]{.greek-added} πληθος και επιθεντος επι την πυραν εχιδνα [εκ]{.greek-omitted} [απο]{.greek-added} της θερμης [διεξελθουσα]{.greek-omitted} [εξελθουσα]{.greek-added} [καθηψεν]{.greek-omitted} [καθηψε]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε ειδον οι βαρβαροι [κρεμαμενον]{.greek-omitted} [κρεμαμενοι]{.greek-added} το θηριον εκ της χειρος αυτου ελεγον προς αλληλους παντως φονευς εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν [αποτιναξας]{.greek-omitted} [αποτιναξαμενος]{.greek-added} το θηριον εις το πυρ επαθεν ουδεν κακον[28:5]{.aside}

οι δε προσεδοκων αυτον μελλειν [πιμπρασθαι]{.greek-omitted} [εμπιπρασθαι]{.greek-added} η καταπιπτειν [αφνω]{.greek-omitted} [αφων]{.greek-added} [[αφον]{.corr}]{.greek-added} νεκρον επι πολυ δε αυτων προσδοκωντων και θεωρουντων μηδεν ατοπον εις αυτον [γινομενον]{.greek-omitted} [γενομενον]{.greek-added} [μεταβαλλομενοι]{.greek-omitted} [μεταβαλλο]{.greek-added} [ελεγον]{.greek-omitted} [θεον]{.greek-omitted} [αυτον]{.greek-omitted} [ειναι]{.greek-omitted}[28:6]{.aside}

[μενοι]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [προσεδοκων]{.greek-omitted} [αυτον]{.greek-omitted} [μελλειν]{.greek-omitted} [πιμπρασθαι]{.greek-omitted} [η]{.greek-omitted} [καταπιπτειν]{.greek-omitted} [αφνω]{.greek-omitted} [νεκρον]{.greek-omitted} [επι]{.greek-omitted} [πολυ]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [προσδοκωντων]{.greek-omitted} [και]{.greek-omitted} [θεωρουντων]{.greek-omitted} [μηδεν]{.greek-omitted} [ατοπον]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted} [γινομενον]{.greek-omitted} [μεταβαλλομενοι]{.greek-omitted} ελεγον [θεον]{.greek-omitted} αυτον ειναι [[θεον]{.greek-abbr}]{.greek-added}[28:6 | instance no. 2]{.aside}

εν δε τοις περι τον τοπον εκεινον [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} χωρια τω πρωτω της νησου ονοματι [ποπλιω]{.greek-omitted} [πουπλιω]{.greek-added} ος αναδεξαμενος ημας [ημερας]{.greek-added} τρεις [ημερας]{.greek-omitted} φιλοφρονως εξενισεν[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του [ποπλιου]{.greek-omitted} [πουπλιου]{.greek-added} πυρετοις και δυσεντερια συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις τας χειρας αυτω ιασατο αυτον[28:8]{.aside}

τουτου [ουν]{.greek-omitted} [δε]{.greek-added} γενομενου και οι λοιποι οι [εχοντες]{.greek-omitted} [ασθενειας]{.greek-omitted} εν τη νησω [εχοντες]{.greek-added} [ασθενειας]{.greek-added} προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρειαν[28:10]{.aside}

μετα δε τρεις [μηνας]{.greek-omitted} [ημερας]{.greek-added} [ηχθημεν]{.greek-omitted} [ανηχθημεν]{.greek-added} εν [τω]{.greek-added} πλοιω παρακεχειμακοτι εν τη νησω αλεξανδρινω παρασημω [διοσκουροις]{.greek-omitted} [διοσκοροις]{.greek-added}[28:11]{.aside}

και καταχθεντες εις [συρακουσας]{.greek-omitted} [συρρακουσας]{.greek-added} επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες κατηντησαμεν εις ρηγιον και μετα μιαν ημεραν επιγενομενου νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν [επ]{.greek-omitted} [παρ]{.greek-added} αυτοις επιμειναι ημερας επτα και ουτως εις [την]{.greek-omitted} ρωμην ηλθομεν[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περι ημων [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} εις απαντησιν [ημιν]{.greek-omitted} [ημων]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} αππιου φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} θαρσος[28:15]{.aside}

οτε δε [ηλθομεν]{.greek-omitted} [εισηλθομεν]{.greek-added} εις ρωμην ο εκατονταρχος [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τους δεσμιους τω στρατοπεδαρχη τω δε παυλω επετραπη μενειν [καθ]{.greek-omitted} [εαυτον]{.greek-omitted} [παρ]{.greek-added} [εαυτω]{.greek-added} συν τω φυλασσοντι [αυτω]{.greek-added} [αυτον]{.greek-omitted} [στρατιωτη]{.greek-omitted}[28:16]{.aside}

[οτε]{.greek-omitted} [δε]{.greek-omitted} [ηλθομεν]{.greek-omitted} [εις]{.greek-omitted} [ρωμην]{.greek-omitted} [ο]{.greek-omitted} [εκατονταρχος]{.greek-omitted} [παρεδωκεν]{.greek-omitted} [τους]{.greek-omitted} [δεσμιους]{.greek-omitted} [τω]{.greek-omitted} [στρατοπεδαρχη]{.greek-omitted} [τω]{.greek-omitted} [δε]{.greek-omitted} [παυλω]{.greek-omitted} [επετραπη]{.greek-omitted} [μενειν]{.greek-omitted} [καθ]{.greek-omitted} [εαυτον]{.greek-omitted} [συν]{.greek-omitted} [τω]{.greek-omitted} [φυλασσοντι]{.greek-omitted} [αυτον]{.greek-omitted} στρατιωτη[28:16 | instance no. 2]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι τον παυλον τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} προς αυτους ανδρες αδελφοι εγω ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθνεσι]{.greek-added} τοις [πατρωοις]{.greek-abbr} δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με εβουλοντο απολυσαι δια το μη[δε]{.unclear}μιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου εχων τι κατηγορησαι[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδ[ειν]{.unclear} και προσλαλησαι ενεκεν γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσ[ιν]{.unclear} ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε [γ]{.unclear}[ρα]{.greek-supplied}μματα περι σου εδεξαμεθα απο της ιουδαιας ουτε πα[ρα]{.greek-supplied}γενομενος τις των αδελφων απηγγειλεν η [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τι περι σου πονηρον[28:21]{.aside}

αξιουμεν δε [ακουσαι]{.greek-added} παρα σου [ακουσαι]{.greek-omitted} α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον εστιν ημιν οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι δε αυτω ημεραν ηκον προς αυτον εις την ξενιαν πλειονες οις εξετιθετο διαμαρτυρομενος την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους [τα]{.greek-omitted} περι του [ιησου]{.greek-abbr} απο τε του νομου [μωυσεως]{.greek-omitted} [μωυσεος]{.greek-added} και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δια ησαιου του προφητου προς [τους]{.greek-omitted} [πατερας]{.greek-omitted} [ημων]{.greek-omitted}[28:25]{.aside}

[ασυμφωνοι]{.greek-omitted} [δε]{.greek-omitted} [οντες]{.greek-omitted} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [απελυοντο]{.greek-omitted} [ειποντος]{.greek-omitted} [του]{.greek-omitted} [παυλου]{.greek-omitted} [ρημα]{.greek-omitted} [εν]{.greek-omitted} [οτι]{.greek-omitted} [καλως]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αγιον]{.greek-omitted} [ελαλησεν]{.greek-omitted} [δια]{.greek-omitted} [ησαιου]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [προς]{.greek-omitted} τους [πατερας]{.greek-abbr} ημων[28:25 | instance no. 2]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και [ειπον]{.greek-omitted} [ειπε]{.greek-added} ακοη ακουσετε και ου μη συνητε και βλεποντες βλεψετε και ου μη [ιδητε]{.greek-omitted} [ιδετε]{.greek-added}[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων [εκαμμυσαν]{.greek-omitted} [εκαμυσαν]{.greek-added} μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [συνωσι]{.greek-added} και ιασομαι αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και ταυτα αυτου ειποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις συζητησιν[28:29]{.aside}

[εμεινεν]{.greek-omitted} [εμεινε]{.greek-added} δε ο παυλος διετιαν ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους προς αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} μετα πασης παρρησιας ακωλυτως[28:31]{.aside}

