---
title: "Collation of Byz^RP^ vs 31071 (1071)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1071 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31071).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1071                                   	| λογος                              	|
| 1071 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1071 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1071               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1071                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1071 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1071                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

[ως]{.greek-omitted} [καθως]{.greek-added} γεγραπται εν [τοις]{.greek-omitted} [ησαια]{.greek-added} [τω]{.greek-added} [προφηταις]{.greek-omitted} [προφητι]{.greek-added} ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την [δον]{.greek-added} [οδον]{.corr} σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και οι [ιεροσολυμιται]{.greek-omitted} [ιεροσολυμειται]{.greek-added} [παντες]{.greek-added} και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και εκηρυσσεν λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος [κυψας]{.greek-omitted} λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν [εκειναις]{.greek-omitted} ταις ημεραις [εκεινες]{.greek-added} ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} της γαλιλαιας και εβαπτισθη [εις]{.greek-added} [τον]{.greek-added} [ιορδανη]{.greek-added} υπο ιωαννου [εις]{.greek-omitted} [τον]{.greek-omitted} [ιορδανην]{.greek-omitted}[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος ειδεν σχιζομενους τους [ουρανους]{.greek-abbr} [και]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ωσει]{.greek-omitted} [περιστεραν]{.greek-omitted} [καταβαινον]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted}[1:10]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [αναβαινων]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [υδατος]{.greek-omitted} [ειδεν]{.greek-omitted} [σχιζομενους]{.greek-omitted} [τους]{.greek-omitted} [ουρανους]{.greek-omitted} και το [πνευμα]{.greek-abbr} [ωσει]{.greek-omitted} [ως]{.greek-added} περιστεραν καταβαινον επ αυτον[1:10 | instance no. 2]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη [ερημω]{.greek-omitted} [ερημων]{.greek-added} ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

[και]{.greek-omitted} λεγων οτι πεπληρωται ο καιρος και [ηγγικεν]{.greek-omitted} [ηγγεικεν]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και [πιστευετε]{.greek-omitted} [πιστευσεται]{.greek-added} εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδων]{.greek-added} [ειδεν]{.corr} σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος βαλλοντας [αμφιβληστρον]{.greek-omitted} [αμφιβλιστρον]{.greek-added} εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [ιαννην]{.greek-added} τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα [αυτων]{.greek-added}[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες το[ν]{.unclear} [πατερα]{.greek-abbr} [αυτων]{.greek-omitted} [αυτον]{.greek-added} ζεβεδαιον εν τω πλοιω [μετα]{.greek-omitted} [ματα]{.greek-added} των [μισθωτων]{.greek-omitted} [μισθοτων]{.greek-added} απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτο[υ]{.greek-supplied} ην γαρ διδασκων αυτους ως εξουσιαν [ε]{.unclear}[χων]{.greek-supplied} και ουχ ως οι γραμματεις[1:22]{.aside}

και ην ε[ν]{.unclear} [τη]{.greek-supplied} συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθ[α]{.unclear}[ρτω]{.greek-supplied} και ανεκραξεν [φωνη]{.greek-added} [μεγαλη]{.greek-added}[1:23]{.aside}

λεγων ε[α]{.greek-supplied} τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απ[ολε]{.greek-supplied}σαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φ[ιμω]{.greek-supplied}θητι και εξελθε εξ [αυτου]{.greek-omitted} [αυτων]{.greek-added}[1:25]{.aside}

και σπαρ[α]{.unclear}[ξαν]{.greek-supplied} αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και [κραξαν]{.greek-omitted} [φ[ω]{.greek-supplied}νησαν]{.greek-added} φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και [εθαμβηθησαν]{.greek-omitted} [εθαμβιθησαν]{.greek-added} [παντες]{.greek-omitted} [απαντες]{.greek-added} ωστε [συζητειν]{.greek-omitted} [συνζητειν]{.greek-added} προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [ε]{.greek-supplied}στιν τουτο [ει]{.greek-added} τις η διδαχη η καινη αυτ[η]{.unclear} οτι κατ εξουσιαν και τοις πνευμασι[ν]{.unclear} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της [συναγωγης]{.greek-omitted} [συναγω]{.greek-added} [εξελθοντες]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [σιμωνος]{.greek-omitted} [και]{.greek-omitted} [ανδρεου]{.greek-omitted} [μετα]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [ιωαννου]{.greek-omitted}[1:29]{.aside}

[γης]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29 | instance no. 2]{.aside}

[η]{.greek-omitted} [[ι]{.unclear}]{.greek-added} δε πενθερα [του]{.greek-added} σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και [διηκονει]{.greek-omitted} [διηκονι]{.greek-added} αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και [ην]{.greek-added} [ολη]{.greek-added} η πολις [ολη]{.greek-omitted} επισυνηγμενη [ην]{.greek-omitted} προς την θυραν[1:33]{.aside}

και εθεραπευσεν πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα εξεβαλεν και ουκ ηφιεν λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ηδισαν]{.greek-added} αυτον[1:34]{.aside}

και πρωι εννυχον λιαν αναστας εξηλθεν και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο [τε]{.greek-added} σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις [ολην]{.greek-omitted} [ολιν]{.greek-added} την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων [αυτον]{.greek-omitted} [αυτων]{.greek-added} και γονυπετων [αυτον]{.greek-omitted} [αυτω]{.greek-added} και λεγων αυτω οτι εαν θελης [[κυριε]{.greek-abbr}]{.greek-added} δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [σπλαγχνισθεις]{.greek-omitted} [σπλαγχνησθης]{.greek-added} εκτεινας την χειρα [αυτου]{.greek-added} ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν [απ]{.greek-omitted} [αυτου]{.greek-omitted} η λεπρα [αυτου]{.greek-added} και [εκαθαρισθη]{.greek-omitted} [εκαθερισθη]{.greek-added}[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν [ειπης]{.greek-omitted} [ειπεις]{.greek-added} αλλ υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} περι του καθαρισμου σου α προσεταξεν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι [δυνασθαι]{.greek-added} αυτον [δυνασθαι]{.greek-omitted} [φανερως]{.greek-omitted} εις πολιν [φανερως]{.greek-added} εισελθειν [αλλ]{.greek-omitted} [εξω]{.greek-omitted} [εν]{.greek-omitted} [ερημοις]{.greek-omitted} [τοποις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ηρχοντο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πανταχοθεν]{.greek-omitted}[1:45]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εξελθων]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [πολλα]{.greek-omitted} [και]{.greek-omitted} [διαφημιζειν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ωστε]{.greek-omitted} [μηκετι]{.greek-omitted} [αυτον]{.greek-omitted} [δυνασθαι]{.greek-omitted} [φανερως]{.greek-omitted} [εις]{.greek-omitted} [πολιν]{.greek-omitted} [εισελθειν]{.greek-omitted} αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45 | instance no. 2]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισελθεν]{.greek-added} παλιν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις καπερναουμ δι ημερων και ηκουσθη οτι [εις]{.greek-omitted} [οικον]{.greek-omitted} [εν]{.greek-added} [οικω]{.greek-added} εστιν[2:1]{.aside}

και [ευθεως]{.greek-omitted} [ευθεος]{.greek-added} συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον[2:2]{.aside}

και ερχονται [φεροντες]{.greek-added} προς αυτον παραλυτικον [φεροντες]{.greek-omitted} αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και [εξορυξαντες]{.greek-omitted} [εξωρυξαντες]{.greek-added} χαλωσιν τον κραββατον εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφαιωνται]{.greek-added} [σοι]{.greek-omitted} [σου]{.greek-added} αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} [ουτω]{.greek-added} λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι [ουτως]{.greek-omitted} [ουτος]{.greek-added} αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [σου]{.greek-omitted} [αφαιονται]{.greek-added} [σοι]{.greek-added} αι αμαρτιαι η ειπειν εγειραι και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιεναι]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} [και]{.greek-omitted} αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν [εναντιον]{.greek-omitted} [ενοπιον]{.greek-added} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε [ουτως]{.greek-omitted} [ουτος]{.greek-added} ειδομεν[2:12]{.aside}

και εξηλθεν παλιν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} παρα την θαλασσαν και πας ο οχλος [ηρχετο]{.greek-omitted} [ηρχοντο]{.greek-added} προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων ειδεν [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν [τω]{.greek-omitted} [το]{.greek-added} κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις [και]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [εσθιοντα]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} [ελεγον]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [τι]{.greek-omitted} [οτι]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [τελωνων]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλων]{.greek-omitted} [εσθιει]{.greek-omitted} [και]{.greek-omitted} [πινει]{.greek-omitted}[2:16]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει [ο]{.greek-added} [διδασκαλος]{.greek-added} [υμων]{.greek-added}[2:16 | instance no. 2]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις [οτι]{.greek-added} ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες [ουκ]{.greek-omitted} [ου]{.greek-added} [γαρ]{.greek-added} ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι [απο]{.greek-added} των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι [μαθηται]{.greek-added} των φαρισαιων νηστευουσιν οι δε [σοι]{.greek-omitted} μαθηται [σου]{.greek-added} ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων εστιν νηστευειν οσον χρονον μεθ εαυτων εχουσιν τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

[και]{.greek-omitted} ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω ει δε μη αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον ν[ε]{.unclear}ον εις ασκους καινους [βλητεον]{.greek-omitted} [βληταιον]{.greek-added}[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον [εν]{.greek-omitted} τοις σαββασιν δια των σποριμων και [ηρξαντο]{.greek-omitted} οι μαθηται αυτου [ηρξαντο]{.greek-added} οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω [ιδε]{.greek-omitted} [ειδε]{.greek-added} τι ποιουσιν [οι]{.greek-added} [μαθηται]{.greek-added} [σου]{.greek-added} εν τοις σαββασιν ο ουκ εξεστιν[2:24]{.aside}

και αυτος [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [επιησεν]{.greek-added} [δαυιδ]{.greek-abbr} οτε [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εσχεν και [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added} αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ [του]{.greek-added} αρχιερεως [και]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [της]{.greek-omitted} [προθεσεως]{.greek-omitted} [εφαγεν]{.greek-omitted} [ους]{.greek-omitted} [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted} [φαγειν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τοις]{.greek-omitted} [ιερευσιν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [ουσιν]{.greek-omitted}[2:26]{.aside}

[πως]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [αβιαθαρ]{.greek-omitted} [αρχιερεως]{.greek-omitted} και τους αρτους της προθ[ε]{.unclear}σεως εφαγεν ους ουκ εξεστιν φαγειν ει [μη]{.greek-omitted} [μι]{.greek-added} τοις ιερευσιν [μονον]{.greek-added} και εδωκεν και τοις συν αυτω ουσιν[2:26 | instance no. 2]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ [ος]{.greek-added} ο [ανθρωπος]{.greek-abbr} δια το σαββατο[ν]{.unclear}[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις σαββασιν θεραπευσει αυτον ινα [κατηγορησωσιν]{.greek-omitted} [κατηγωρησωσιν]{.greek-added} [αυτου]{.greek-omitted} [αυτον]{.greek-added}[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} [τω]{.greek-omitted} [το]{.greek-added} εξηραμμενην εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις εξεστιν τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη πωρωσει της καρδι[α]{.unclear}ς αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου υγιης [ωσει]{.greek-added} [ως]{.greek-omitted} [η]{.greek-omitted} αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} μετα των ηρωδιανων συμβουλιον [εποιουν]{.greek-omitted} [εποιησαν]{.greek-added} κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απωλεσωσιν]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [γνους]{.greek-added} ανεχωρησεν μετα των μαθητων αυτου [προς]{.greek-omitted} [παρα]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted} και απο της ιουδαιας [ηκολουθησαν]{.greek-added} [αυτω]{.greek-added}[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα εποιει [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον προσκαρτερη αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε [επιπιπτειν]{.greek-omitted} [επιπιπτιν]{.greek-added} αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα οταν αυτον [εθεωρει]{.greek-omitted} [εθεορουν]{.greek-added} [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις [ινα]{.greek-omitted} [μη]{.greek-omitted} [φανερον]{.greek-omitted} [αυτον]{.greek-omitted} [ποιησωσιν]{.greek-omitted}[3:12]{.aside}

[ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [και]{.greek-omitted} [πολλα]{.greek-omitted} [επετιμα]{.greek-omitted} [αυτοις]{.greek-omitted} ινα μη φανερον αυτον ποιησωσιν[3:12 | instance no. 2]{.aside}

και αναβαινει εις το ορος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και εποιησεν δωδεκα ινα ωσιν μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστειλη]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και επεθηκεν [αυτοις]{.greek-added} [ονοματα]{.greek-added} τω σιμωνι [ονομα]{.greek-omitted} πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [του]{.greek-omitted} ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον [τον]{.greek-added} [τελονην]{.greek-added} και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη δυνασθαι αυτους [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου [δυναται]{.greek-omitted} [δυνησηται]{.greek-added} [σταθηναι]{.greek-omitted} η οικια εκεινη [σταθηναι]{.greek-added}[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος [εχει]{.greek-omitted} [εχειν]{.greek-added}[3:26]{.aside}

[αλλ]{.greek-added} ουδεις δυναται [τα]{.greek-omitted} [σκευη]{.greek-omitted} [εις]{.greek-added} [την]{.greek-added} [οικιαν]{.greek-added} του ισχυρου εισελθων [τα]{.greek-added} [σκευη]{.greek-added} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση [και]{.greek-omitted} [τοτε]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπαση]{.greek-omitted}[3:27]{.aside}

[ουδεις]{.greek-omitted} [δυναται]{.greek-omitted} [τα]{.greek-omitted} [σκευη]{.greek-omitted} [του]{.greek-omitted} [ισχυρου]{.greek-omitted} [εισελθων]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπασαι]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [πρωτον]{.greek-omitted} [τον]{.greek-omitted} [ισχυρον]{.greek-omitted} [δηση]{.greek-omitted} και τοτε την οικιαν αυτου διαρπαση[3:27 | instance no. 2]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted} τοις υιοις των [ανθρωπων]{.greek-abbr} [τα]{.greek-added} [αμαρτιματα]{.greek-added} και [αι]{.greek-added} βλασφημιαι οσας [αν]{.greek-omitted} [εαν]{.greek-added} [βλασφημησωσιν]{.greek-omitted} [βλασφημισωσιν]{.greek-added} [αφεθησεται]{.greek-added} [αυτοις]{.greek-added}[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημησει]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις [το]{.greek-added} [τον]{.corr} αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [οτι]{.greek-added} [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

[και]{.greek-added} ερχονται [ουν]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [και]{.greek-omitted} η [μητηρ]{.greek-abbr} αυτου και [οι]{.greek-added} [αδελφοι]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} εξω εστωτες [απεστειλαν]{.greek-omitted} [απεστηλαν]{.greek-added} προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [ειπον]{.greek-omitted} [δε]{.greek-omitted} [οχλος]{.greek-added} [πολυς]{.greek-added} [και]{.greek-added} [λεγουσιν]{.greek-added} αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω ζητουσιν σε[3:32]{.aside}

και [απεκριθη]{.greek-omitted} [αποκριθεις]{.greek-added} αυτοις [λεγων]{.greek-omitted} [λεγει]{.greek-added} τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ειδε]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου [ου]{.greek-added} [τι]{.greek-added} [εισιν]{.greek-added}[3:34]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} εστιν[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν [ην]{.greek-added} επι της γης [ην]{.greek-omitted}[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} του σπειραι [τον]{.greek-added} [σπορον]{.greek-added} [αυτου]{.greek-added}[4:3]{.aside}

και εγενετο εν τω σπειρειν [αυτον]{.greek-added} ο μεν επεσεν παρα την οδον και ηλθεν τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

[και]{.greek-added} αλλο [δε]{.greek-omitted} επεσεν επι το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [εχε]{.greek-added} γην πολλην και ευθεως εξανετειλεν δια το [μη]{.greek-omitted} [μι]{.greek-added} εχειν [γης]{.greek-added} βαθος [γης]{.greek-omitted}[4:5]{.aside}

[και]{.greek-added} [οτε]{.greek-added} [ανετειλεν]{.greek-added} [ο]{.greek-added} [ηλιου]{.greek-omitted} [ηλιος]{.greek-added} [δε]{.greek-omitted} [ανατειλαντος]{.greek-omitted} εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδοκεν]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και [αυξανοντα]{.greek-omitted} [αυξανομενα]{.greek-added} και εφερεν [εν]{.greek-omitted} [εις]{.greek-added} τριακοντα και [εν]{.greek-omitted} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο [εχων]{.greek-omitted} [εχον]{.greek-added} ωτα ακουειν ακουετω[4:9]{.aside}

[και]{.greek-added} οτε [δε]{.greek-omitted} εγενετο [καταμονας]{.greek-omitted} [ηρωτησαν]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} [ηρωτων]{.greek-added} αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα [γινεται]{.greek-omitted} [λεγεται]{.greek-added}[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεψωσιν]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ειδωσιν]{.greek-added} και ακουοντες ακουωσιν και μη [συνιωσιν]{.greek-omitted} [συνωσιν]{.greek-added} μηποτε επιστρεψωσιν και αφεθη αυτοις τα [αμαρτηματα]{.greek-omitted} [αμαρτιματα]{.greek-added}[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας [γνωσεσθε]{.greek-omitted} [γνωσεσθαι]{.greek-added}[4:13]{.aside}

ο [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι [ομοιως]{.greek-added} εισιν [ομοιως]{.greek-omitted} οι επι τα πετρωδη σπειρομενοι οι οταν ακουσωσιν τον λογον [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ εχουσιν ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added}[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα [επιθυμιαι]{.greek-omitted} [αιπεθυμιαι]{.greek-added} εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνηγουσιν]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες ακουουσιν τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγον]{.greek-added} αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην [ουχ]{.greek-omitted} [ου]{.greek-added} [ινα]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [λυχνιαν]{.greek-omitted} [επιτεθη]{.greek-omitted}[4:21]{.aside}

[χι]{.greek-added} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [μητι]{.greek-omitted} [ο]{.greek-omitted} [λυχνος]{.greek-omitted} [ερχεται]{.greek-omitted} ινα υπο [τον]{.greek-omitted} [μοδιον]{.greek-omitted} [τεθη]{.greek-omitted} [η]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [κλινην]{.greek-omitted} [ουχ]{.greek-omitted} [ινα]{.greek-omitted} [επι]{.greek-omitted} την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21 | instance no. 2]{.aside}

ου γαρ εστιν τι κρυπτον ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα [ελθη]{.greek-added} εις φανερον [ελθη]{.greek-omitted}[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω [μετρειτε]{.greek-omitted} [μετριτε]{.greek-added} [μετρηθησεται]{.greek-omitted} [αντιμετριθησεται]{.greek-added} υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [εχη]{.greek-omitted} [εχει]{.greek-added} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν [αυτοις]{.greek-added} [ουτως]{.greek-omitted} [ουτος]{.greek-added} εστιν η βασιλεια του [θεου]{.greek-abbr} [ως]{.greek-omitted} [ος]{.greek-added} εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρετε]{.greek-added} νυκτα και ημεραν και ο σπορος βλαστανη και μηκυνηται ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν τω [σταχυι]{.greek-omitted} [σταχυει]{.greek-added}[4:28]{.aside}

οταν δε [παραδω]{.greek-omitted} [παρωδω]{.greek-added} ο καρπος ευθεως αποστελλει το δρεπανον οτι [παρεστηκεν]{.greek-omitted} [παρεστικεν]{.greek-added} ο θερισμος[4:29]{.aside}

και ελεγεν τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως κοκκον σιναπεως ος οταν σπαρη επι της γης [μικροτερος]{.greek-omitted} [μηκροτερον]{.greek-added} [ον]{.greek-added} παντων των σπερματων [εστιν]{.greek-omitted} των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} αναβαινει και γινεται [μειζων]{.greek-added} παντων των λαχανων [μειζων]{.greek-omitted} [των]{.greek-added} [επι]{.greek-added} [της]{.greek-added} [γης]{.greek-added} και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα [πετεινα]{.greek-omitted} [πετινα]{.greek-added} του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως εδυναντο ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις κατ ιδιαν δε τοις [ιδιοις]{.greek-added} μαθηταις αυτου επελυεν παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις [το]{.greek-omitted} περαν[4:35]{.aside}

και αφεντες τον οχλον [παραλαμβανουσιν]{.greek-omitted} [παραλαμβα]{.greek-added} [αυτον]{.greek-omitted} [ως]{.greek-omitted} [ην]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [δε]{.greek-omitted} [πλοιαρια]{.greek-omitted} [ην]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[4:36]{.aside}

[νουσιν]{.greek-added} [και]{.greek-omitted} [αφεντες]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [παραλαμβανουσιν]{.greek-omitted} αυτον ως ην εν τω πλοιω και αλλα δε [πλοιαρια]{.greek-omitted} [πλοια]{.greek-added} ην μετ αυτου[4:36 | instance no. 2]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λελαψ]{.greek-added} ανεμου μεγαλη [και]{.greek-added} τα [δε]{.greek-omitted} κυματα επεβαλλεν εις το πλοιον ωστε [αυτο]{.greek-omitted} ηδη γεμιζεσθαι [αυτω]{.greek-added}[4:37]{.aside}

και [αυτος]{.greek-added} ην [εν]{.greek-added} [αυτος]{.greek-omitted} [επι]{.greek-omitted} τη πρυμνη επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελη]{.greek-added} σοι οτι [απολλυμεθα]{.greek-omitted} [απολλοιμεθα]{.greek-added}[4:38]{.aside}

και [διεγερθεις]{.greek-omitted} [διεγερθης]{.greek-added} επετιμησεν τω ανεμω και ειπεν τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [πεφημωσε]{.greek-added} και εκοπασεν ο [ανεμος]{.greek-omitted} [ανεμως]{.greek-added} και εγενετο [[εγενητο]{.corr}]{.greek-added} [γαληνη]{.greek-omitted} [γαλινη]{.greek-added} μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι [δειλοι]{.greek-omitted} [διλοι]{.greek-added} εστε ουτως πως ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και [ο]{.greek-omitted} [οι]{.greek-added} [ανεμος]{.greek-omitted} [ανεμοι]{.greek-added} και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γεργεσινων]{.greek-added}[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως [απηντησεν]{.greek-omitted} [υπηντησεν]{.greek-added} αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις μνημασιν και ουτε αλυσεσιν [ουτε]{.greek-added} [πεδες]{.greek-added} ουδεις εδυνατο αυτον δησαι[5:3]{.aside}

δια το [αυτον]{.greek-omitted} πολλακις [πεδαις]{.greek-omitted} [πεδες]{.greek-added} και αλυσεσιν δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [εδυνατο]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και [ην]{.greek-added} δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημασιν]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και [κατακοπτων]{.greek-omitted} [κατακοπτον]{.greek-added} εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν εδραμεν και προσεκυνησεν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και σοι [ιησου]{.greek-abbr} [υιε]{.greek-abbr} του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

ελεγεν γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι ονομα και απεκριθη λεγων λεγεων ονομα μοι οτι [πο]{.greek-added} [πολλοι]{.greek-omitted} [εσμεν]{.greek-omitted}[5:9]{.aside}

[και]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [τι]{.greek-omitted} [σοι]{.greek-omitted} [ονομα]{.greek-omitted} [και]{.greek-omitted} [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγεων]{.greek-omitted} [ονομα]{.greek-omitted} [μοι]{.greek-omitted} [οτι]{.greek-omitted} [πολλοι]{.greek-omitted} [λλοι]{.greek-added} εσμεν[5:9 | instance no. 2]{.aside}

και παρεκαλει αυτον πολλα ινα μη αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει προς [τω]{.greek-omitted} [το]{.greek-added} ορει αγελη χοιρων μεγαλη βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι [δαιμονες]{.greek-omitted} [δαιμωνες]{.greek-added} λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευμα]{.greek-added} [πνευματα]{.corr} τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη [πασα]{.greek-added} κατα του [κρημνου]{.greek-omitted} [κριμνου]{.greek-added} εις την θαλασσαν ησαν δε ως δισχιλιοι και [επνιγοντο]{.greek-omitted} [επνηγοντο]{.greek-added} εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και ανηγγειλαν εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και θεωρουσιν τον δαιμονιζομενον καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο δε αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν [απο]{.greek-omitted} [απω]{.greek-added} των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο [δαιμονισθεις]{.greek-omitted} [δαιμονησθεις]{.greek-added} ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} πεποιηκεν και ηλεησεν σε [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added}[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και [παρεκαλει]{.greek-omitted} [παρακαλει]{.greek-added} αυτον πολλα [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [μου]{.greek-omitted} [εσχατως]{.greek-omitted} [εχει]{.greek-omitted} [ινα]{.greek-omitted} [ελθων]{.greek-omitted} [επιθης]{.greek-omitted} [αυτη]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [οπως]{.greek-omitted} [σωθη]{.greek-omitted} [και]{.greek-omitted} [ζησεται]{.greek-omitted}[5:23]{.aside}

[και]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [πολλα]{.greek-omitted} λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθησει]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23 | instance no. 2]{.aside}

και απηλθεν μετ αυτου και ηκολουθει αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του [κρασπεδου]{.greek-added} [του]{.greek-added} ιματιου αυτου[5:27]{.aside}

ελεγεν γαρ οτι καν των ιματιων αυτου αψωμαι [σωθησομαι]{.greek-omitted} [σωθησωμαι]{.greek-added}[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι [ιαται]{.greek-omitted} [ιατε]{.greek-added} απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα [διο]{.greek-added} [πεποιηκεν]{.greek-added} ειδυια ο γεγονεν επ αυτη ηλθεν και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου σεσωκεν σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου απεθανεν τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα [μετ]{.greek-added} αυτω συνακολουθησαι ει [μη]{.greek-omitted} [μι]{.greek-added} πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [ιωανην]{.greek-added} τον αδελφον ιακωβου[5:37]{.aside}

και [ερχεται]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [του]{.greek-omitted} [αρχισυναγωγου]{.greek-omitted} [και]{.greek-omitted} [θεωρει]{.greek-omitted} [θορυβον]{.greek-omitted} [κλαιοντας]{.greek-omitted} [και]{.greek-omitted} [αλαλαζοντας]{.greek-omitted} [πολλα]{.greek-omitted}[5:38]{.aside}

[και]{.greek-omitted} ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον κλαιοντας και αλαλαζοντας πολλα[5:38 | instance no. 2]{.aside}

και εισελθων λεγει αυτοις τι θορυβεισθε και κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και [περιεπατει]{.greek-omitted} [περιεπατη]{.greek-added} ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και ειπεν δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την πατριδα αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} [ταυτα]{.greek-omitted} [παντα]{.greek-added} και τις η σοφια η [δοθεισα]{.greek-omitted} [δοθησα]{.greek-added} αυτω και δυναμεις τοιαυται δια των χειρων αυτου [γινονται]{.greek-omitted} [γινωνται]{.greek-added}[6:2]{.aside}

ουχ ουτος εστιν ο [τεκον]{.greek-added} [τεκτων]{.greek-omitted} [[τεκτον]{.corr}]{.greek-added} ο [υιος]{.greek-abbr} μαριας αδελφος [δε]{.greek-omitted} ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

ελεγεν δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει [μη]{.greek-omitted} [μι]{.greek-added} εν τη [πατριδι]{.greek-omitted} [πατριδη]{.greek-added} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσιν]{.greek-added} [αυτου]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει [μιαν]{.greek-added} [ουδεμιαν]{.corr} δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας εθεραπευσεν[6:5]{.aside}

και εθαυμαζεν δια την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και περιηγεν τας κωμας κυκλω διδασκων[6:6]{.aside}

και [προσ]{.greek-added} [προσκαλειται]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτους]{.greek-omitted} [αποστελλειν]{.greek-omitted} [δυο]{.greek-omitted} [δυο]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [αυτοις]{.greek-omitted} [εξουσιαν]{.greek-omitted} [των]{.greek-omitted} [πνευματων]{.greek-omitted} [των]{.greek-omitted} [ακαθαρτων]{.greek-omitted}[6:7]{.aside}

[και]{.greek-omitted} [προσκαλειται]{.greek-omitted} [καλειται]{.greek-added} τους δωδεκα [μαθητας]{.greek-added} [αυτου]{.greek-added} και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των ακαθαρτων[6:7 | instance no. 2]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγελλεν]{.greek-added} αυτοις ινα μηδεν [αιρωσιν]{.greek-omitted} [ερωσιν]{.greek-added} εις οδον ει μη ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη ενδυσησθε δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει [μενετε]{.greek-omitted} [μενεται]{.greek-added} εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [ου]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον [εσται]{.greek-omitted} [εστε]{.greek-added} σοδομοις [η]{.greek-omitted} [και]{.greek-added} γομορροις εν ημερα κρισεως η τη [πολει]{.greek-omitted} [πολι]{.greek-added} εκεινη[6:11]{.aside}

και εξελθοντες [εκηρυσσον]{.greek-omitted} [εκηρυσσαν]{.greek-added} ινα μετανοησωσιν[6:12]{.aside}

και δαιμονια πολλα [εξεβαλλον]{.greek-omitted} [εξεβαλον]{.greek-added} και [ηλειφον]{.greek-omitted} [ειληφον]{.greek-added} ελαιω πολλους αρρωστους και [εθεραπευον]{.greek-omitted} [εθεραπευοντο]{.greek-added}[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο ενεργουσιν αι δυναμεις εν αυτω[6:14]{.aside}

αλλοι ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} ιωαννην ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης αποστειλας εκρατησεν [τον]{.greek-omitted} [των]{.greek-added} ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο ιωαννης τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ [ηδυνατο]{.greek-omitted} [η]{.greek-added}[6:19]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [ηρωδιας]{.greek-omitted} [ενειχεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [αυτον]{.greek-omitted} [αποκτειναι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνατο]{.greek-omitted} [δυνατο]{.greek-added}[6:19 | instance no. 2]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητο]{.greek-added} τον [ιωαννην]{.greek-omitted} [ιωανην]{.greek-added} ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και [γενομενης]{.greek-omitted} [γεναμενης]{.greek-added} ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν [με]{.greek-omitted} αιτησης δωσω σοι εως [ημισους]{.greek-omitted} [ημησους]{.greek-added} της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι [αιτησομαι]{.greek-omitted} [αιτησωμαι]{.greek-added} η δε ειπεν την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [ιαννου]{.greek-added} του βαπτιστου[6:25]{.aside}

και [περιλυπος]{.greek-omitted} [περιλοιπος]{.greek-added} [γενομενος]{.greek-omitted} [γεναμενος]{.greek-added} ο βασιλευς δια [δε]{.greek-added} τους ορκους και τους συνανακειμενους ουκ [ηθελησεν]{.greek-omitted} [ειθελεν]{.greek-added} αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το [πτομα]{.greek-added} [πτωμα]{.corr} αυτου και [εθηκαν]{.greek-omitted} [εθηκεν]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε [υμεις]{.greek-omitted} [αυτοι]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [εις]{.greek-omitted} [ερημον]{.greek-omitted} [τοπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [ολιγον]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [ερχομενοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [υπαγοντες]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ουδε]{.greek-omitted} [φαγειν]{.greek-omitted} [ευκαιρουν]{.greek-omitted}[6:31]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [δευτε]{.greek-omitted} υμεις αυτοι κατ ιδιαν εις [τοπον]{.greek-added} ερημον [τοπον]{.greek-omitted} και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και [οι]{.greek-omitted} υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31 | instance no. 2]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους [και]{.greek-omitted} [συνηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[6:33]{.aside}

και εξελθων ειδεν ο [ιησους]{.greek-abbr} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν [αυτους]{.greek-omitted} [αυτοις]{.greek-added} πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες [αυτω]{.greek-omitted} οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν δηναριων διακοσιων αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και [γνοντες]{.greek-omitted} [επιγνοντες]{.greek-added} λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακλιθηναι]{.greek-added} παντας συμποσια συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και [ανεπεσον]{.greek-omitted} [αν[ε]{.unclear}πεσαν]{.greek-added} πρασιαι πρασιαι ανα [εκατον]{.greek-omitted} [εκατων]{.greek-added} και ανα [πεντηκοντα]{.greek-omitted} [πεντικοντα]{.greek-added}[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} ευλογησεν και κατεκλασεν τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας εμερισεν πασιν[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν [οι]{.greek-omitted} [φαγοντες]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [πεντακισχιλιοι]{.greek-omitted} [ανδρες]{.greek-omitted}[6:44]{.aside}

[και]{.greek-omitted} [ησαν]{.greek-omitted} οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44 | instance no. 2]{.aside}

και ευθεως ηναγκασεν τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς βηθσαιδαν εως αυτος απολυση [τον]{.greek-omitted} [οχλον]{.greek-omitted} [τους]{.greek-added} [οχλους]{.greek-added}[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας [γενομενης]{.greek-omitted} [γεναμενης]{.greek-added} ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48]{.aside}

οι δε [ιδοντες]{.greek-omitted} [ειδοντες]{.greek-added} αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελασε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ αυτων η καρδια πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} και [προσωρμισθησαν]{.greek-omitted} [προσορμησθησαν]{.greek-added}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον [οι]{.greek-added} [ανδρες]{.greek-added} [του]{.greek-added} [τοπου]{.greek-added} [εκεινου]{.greek-added}[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις [κραββατοις]{.greek-omitted} [κραβαττοις]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει εστιν[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται [και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [ηπτοντο]{.greek-omitted} [αυτου]{.greek-omitted} [εσωζοντο]{.greek-omitted}[6:56]{.aside}

[και]{.greek-omitted} [οπου]{.greek-omitted} [αν]{.greek-omitted} [εισεπορευετο]{.greek-omitted} [εις]{.greek-omitted} [κωμας]{.greek-omitted} [η]{.greek-omitted} [πολεις]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [αγοραις]{.greek-omitted} [ετιθουν]{.greek-omitted} [τους]{.greek-omitted} [ασθενουντας]{.greek-omitted} [και]{.greek-omitted} [παρεκαλουν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [καν]{.greek-omitted} [του]{.greek-omitted} [κρασπεδου]{.greek-omitted} [του]{.greek-omitted} [ιματιου]{.greek-omitted} [αυτου]{.greek-omitted} [αψωνται]{.greek-omitted} και οσοι αν ηπτοντο αυτου εσωζοντο[6:56 | instance no. 2]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου [οτι]{.greek-added} κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας χειρας ουκ εσθιουσιν [αρτον]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη [βαπτισωνται]{.greek-omitted} [βαπτισονται]{.greek-added} ουκ εσθιουσιν και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου περιπατουσιν κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων αλλα ανιπτοις χερσιν εσθιουσιν τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις [οτι]{.greek-omitted} καλως [προεφητευσεν]{.greek-omitted} [επροφητευσεν]{.greek-added} ησαιας περι υμων των υποκριτων ως γεγραπται [ουτος]{.greek-omitted} [οτι]{.greek-added} ο λαος [ουτος]{.greek-added} τοις χειλεσιν με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε [σεβονται]{.greek-omitted} [σεβοντε]{.greek-added} με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added}[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων τηρησητε[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} [οτι]{.greek-added} εαν ειπη [ο]{.greek-added} [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-omitted} [[μητηρ]{.greek-abbr}]{.greek-added} [κορβαν]{.greek-omitted} [κωρβαν]{.greek-added} ο εστιν δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου [η]{.greek-omitted} [τη]{.greek-omitted} [μητρι]{.greek-omitted} [αυτου]{.greek-omitted}[7:12]{.aside}

[και]{.greek-omitted} [ουκετι]{.greek-omitted} [αφιετε]{.greek-omitted} [αυτον]{.greek-omitted} [ουδεν]{.greek-omitted} [ποιησαι]{.greek-omitted} [τω]{.greek-omitted} [πατρι]{.greek-omitted} [αυτου]{.greek-omitted} η τη [μητρι]{.greek-abbr} αυτου[7:12 | instance no. 2]{.aside}

[ακυρουντες]{.greek-omitted} [ακυρουνταις]{.greek-added} τον λογον του [θεου]{.greek-abbr} [δια]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [παραδοσει]{.greek-omitted} [παραδωσιν]{.greek-added} υμων [η]{.greek-omitted} [ην]{.greek-added} παρεδωκατε και παρομοια τοιαυτα πολλα [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added}[7:13]{.aside}

και προσκαλεσαμενος παντα [τον]{.greek-omitted} [των]{.greek-added} οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται [κοινωσαι]{.greek-added} αυτον [κοινωσαι]{.greek-omitted} αλλα τα εκπορευομενα απ αυτου εκεινα εστιν τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

[ο]{.greek-added} [εχων]{.greek-added} [ει]{.greek-omitted} [τις]{.greek-omitted} [εχει]{.greek-omitted} ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου [επηρωτων]{.greek-omitted} [επηρωτουν]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το [εξωθεν]{.greek-omitted} [εξοθεν]{.greek-added} εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

ελεγεν δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον [εκεινο]{.greek-omitted} [εκεινω]{.greek-added} κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται [μοιχειαι]{.greek-omitted} [μοιχεια]{.greek-added} πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος ασελγεια οφθαλμος πονηρος βλασφημια [υπερηφανια]{.greek-omitted} [υπεριφανια]{.greek-added} αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα προσεπεσεν προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συροφοινικισσα]{.greek-added} [τω]{.greek-omitted} [γενει]{.greek-omitted} [το]{.greek-added} [γενη]{.greek-added} και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον [χορ]{.greek-added} [χορτασθηναι]{.greek-omitted} [τα]{.greek-omitted} [τεκνα]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [λαβειν]{.greek-omitted} [τον]{.greek-omitted} [αρτον]{.greek-omitted} [των]{.greek-omitted} [τεκνων]{.greek-omitted} [και]{.greek-omitted} [βαλειν]{.greek-omitted} [τοις]{.greek-omitted} [κυναριοις]{.greek-omitted}[7:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} [αφες]{.greek-omitted} [πρωτον]{.greek-omitted} [χορτασθηναι]{.greek-omitted} [τασθηναι]{.greek-added} τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον [των]{.greek-omitted} [τον]{.greek-added} τεκνων και βαλειν τοις [κυναριοις]{.greek-omitted} [κοιναριοις]{.greek-added}[7:27 | instance no. 2]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης [εσθιει]{.greek-omitted} [εσθιουσιν]{.greek-added} απο των ψιχιων των [παιδιων]{.greek-omitted} [πιπτοντων]{.greek-added}[7:28]{.aside}

και ειπεν αυτ[η]{.unclear} δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξελιλυθεν]{.greek-added} [το]{.greek-omitted} [δαιμονιον]{.greek-omitted} εκ της θυγατρος σου [το]{.greek-added} [δαιμονιον]{.greek-added}[7:29]{.aside}

και απελθουσα εις τον οικον αυτης ευρεν το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι [της]{.greek-omitted} [την]{.greek-added} [κλινης]{.greek-omitted} [κλινην]{.greek-added}[7:30]{.aside}

και παλιν εξελθων [εκ]{.greek-omitted} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [απο]{.greek-added} των οριων τυρου και σιδωνος ηλθεν προς την θαλασσαν της γαλιλαιας ανα [μεσον]{.greek-omitted} [μεσων]{.greek-added} των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν εβαλεν τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} εστεναξεν και λεγει αυτω εφφαθα ο εστιν [διανοιχθητι]{.greek-omitted} [διανυχθητι]{.greek-added}[7:34]{.aside}

και ευθεως [διηνοιχθησαν]{.greek-omitted} [διηνυχθησαν]{.greek-added} αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστηλατο]{.greek-added} αυτοις ινα [μηδενι]{.greek-omitted} [μηδενη]{.greek-added} ειπωσιν οσον δε [αυτοις]{.greek-added} αυτος [αυτοις]{.greek-omitted} διεστελλετο [αυτοι]{.greek-added} μαλλον [περισσοτερον]{.greek-omitted} [περισσοτερως]{.greek-added} εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα πεποιηκεν και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παλιν]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου οντος και [μη]{.greek-omitted} [μι]{.greek-added} εχοντων τι φαγωσιν προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον [τουτον]{.greek-added} οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμεν[ο]{.unclear}υσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχωσιν]{.greek-added} τι φαγωσιν[8:2]{.aside}

και εαν [απολυσω]{.greek-omitted} [απολυσαι]{.greek-added} αυτους [νηστεις]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [αυτων]{.greek-omitted} [εκλυθησονται]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [τινες]{.greek-omitted} [γαρ]{.greek-omitted} [αυτων]{.greek-omitted} [μακροθεν]{.greek-omitted} [ηκουσιν]{.greek-omitted}[8:3]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [απολυσω]{.greek-omitted} [αυτους]{.greek-omitted} [νηστεις]{.greek-omitted} [νηστις]{.greek-added} εις οικον [αυτων]{.greek-omitted} [αυτον]{.greek-added} εκλυθησονται εν τη οδω τινες γαρ αυτων [απο]{.greek-added} μακροθεν [ηκουσιν]{.greek-omitted} [ηκασιν]{.greek-added}[8:3 | instance no. 2]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις [ωδε]{.greek-omitted} χορτασαι αρτων επ ερημιας[8:4]{.aside}

και [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και παρηγγειλεν [αυτοις]{.greek-added} [τω]{.greek-omitted} [οχλω]{.greek-omitted} αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας εκλασεν και εδιδου τοις μαθηταις αυτου ινα παραθωσιν και [παρεθηκαν]{.greek-omitted} [παρεθηκεν]{.greek-added} τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [αυτα]{.greek-added} ειπεν [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} [και]{.greek-omitted} αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν [παντες]{.greek-added} και ηραν [περισσευματα]{.greek-omitted} [περισευματα]{.greek-added} κλασματων επτα σπυριδας [πληρις]{.greek-added}[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι [ανδρες]{.greek-added} και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των [μαθητων]{.greek-omitted} [μαθιτων]{.greek-added} αυτου [και]{.greek-added} ηλθεν εις τα [μερη]{.greek-omitted} [ορη]{.greek-added} δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο [συζητειν]{.greek-omitted} [συνζητειν]{.greek-added} αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν [ει]{.greek-omitted} [ου]{.greek-added} δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους [παλιν]{.greek-added} εμβας [παλιν]{.greek-omitted} εις πλοιον [απηλθεν]{.greek-omitted} [διηλθεν]{.greek-added} εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} λαβειν αρτους και ει [μη]{.greek-omitted} [μι]{.greek-added} ενα αρτον [μονον]{.greek-added} ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις [λεγων]{.greek-omitted} [λεγον]{.greek-added} ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [εν]{.greek-added} [εαυτοις]{.greek-added} λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} οτι αρτους ουκ εχετε ουπω [νοειτε]{.greek-omitted} [νοειται]{.greek-added} ουδε [συνιετε]{.greek-omitted} [συνιεται]{.greek-added} ετι πεπωρωμενην [εχετε]{.greek-omitted} [εχεται]{.greek-added} την καρδιαν υμων[8:17]{.aside}

[οφθαλ]{.greek-added} [οφθαλμους]{.greek-omitted} [εχοντες]{.greek-omitted} [ου]{.greek-omitted} [βλεπετε]{.greek-omitted} [και]{.greek-omitted} [ωτα]{.greek-omitted} [εχοντες]{.greek-omitted} [ουκ]{.greek-omitted} [ακουετε]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μνημονευετε]{.greek-omitted}[8:18]{.aside}

[οφθαλμους]{.greek-omitted} [μους]{.greek-added} εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18 | instance no. 2]{.aside}

οτε τους [πεντες]{.greek-added} [πεντε]{.corr} αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους [πληρεις]{.greek-omitted} κλασματων ηρατε [πληρις]{.greek-added} λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε [ειπον]{.greek-omitted} [ειπων]{.greek-added} επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις πως [ου]{.greek-omitted} [ουπω]{.greek-added} [συνιετε]{.greek-omitted} [συνιεται]{.greek-added}[8:21]{.aside}

και [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} εις [βηθσαιδαν]{.greek-omitted} [βιθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν [αυτον]{.greek-omitted} [αυτων]{.greek-added} ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ειπεν]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} [οτι]{.greek-omitted} ως δενδρα [ορω]{.greek-omitted} περιπατουντας[8:24]{.aside}

ειτα παλιν επεθηκεν τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και ενεβλεψεν [τηλαυγως]{.greek-omitted} [τηλαυγος]{.greek-added} απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων [υπαγε]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [εαν]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [κομην]{.greek-added} [εισελθης]{.greek-added} μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας [καισαρειας]{.greek-omitted} [κεσαριας]{.greek-added} της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε [απεκριθησαν]{.greek-omitted} [απεκρισθησαν]{.greek-added} [λεγοντες]{.greek-added} ιωαννην τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι λεγωσιν περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν [και]{.greek-omitted} [αποδοκιμασθηναι]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [αρχιερεων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [και]{.greek-omitted} [αποκτανθηναι]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [τρεις]{.greek-omitted} [ημερας]{.greek-omitted} [αναστηναι]{.greek-omitted}[8:31]{.aside}

και [ηρξατο]{.greek-omitted} [διδασκειν]{.greek-omitted} [αυτους]{.greek-omitted} [οτι]{.greek-omitted} [δει]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [πολλα]{.greek-omitted} [παθειν]{.greek-omitted} [και]{.greek-omitted} [αποδοκιμασθηναι]{.greek-omitted} [αποδωκιμασθηναι]{.greek-added} [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και των αρχιερεων και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθην[αι]{.greek-supplied} και μετα τρεις ημερας [αναστηναι]{.greek-omitted} [αναστειναι]{.greek-added}[8:31 | instance no. 2]{.aside}

και παρρησια τον λογον [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} επιστραφεις και [ιδων]{.greek-omitted} [ειδων]{.greek-added} τους μαθητας αυτου επετιμησεν τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [ει]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελει [οπισω]{.greek-omitted} [οπησω]{.greek-added} μου [ακολουθειν]{.greek-omitted} [ελθειν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34]{.aside}

ος γαρ αν [θελη]{.greek-omitted} [θελει]{.greek-added} την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την [εαυτου]{.greek-omitted} ψυχην [αυτου]{.greek-added} ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [τον]{.greek-added} [ανθρωπον]{.greek-abbr} εαν [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} [ολον]{.greek-added} τον κοσμον [ολον]{.greek-omitted} και [ζημιωθη]{.greek-omitted} [ζημειωθη]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ εαν [επαισχυνθη]{.greek-omitted} [επεσχυνθη]{.greek-added} με και τους εμους λογους εν τη γενεα ταυτη τη [μοιχαλιδι]{.greek-omitted} [μοιχαλλιδι]{.greek-added} και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι εισιν τινες των ωδε [εστηκοτων]{.greek-omitted} [εστικοτων]{.greek-added} οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ειδωσιν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και ιωαννην και αναφερει αυτους εις ορος [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν [ως]{.greek-omitted} [ωσει]{.greek-added} χιων [οια]{.greek-omitted} [γναφευς]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [λευκαναι]{.greek-omitted}[9:3]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτου]{.greek-omitted} [εγενοντο]{.greek-omitted} [στιλβοντα]{.greek-omitted} [λευκα]{.greek-omitted} [λιαν]{.greek-omitted} [ως]{.greek-omitted} [χιων]{.greek-omitted} οια γναφευς επι της γης ου δυναται λευκαναι [ουτως]{.greek-added}[9:3 | instance no. 2]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και [θελης]{.greek-added} ποιησωμεν [τρεις]{.greek-added} σκηνας [τρεις]{.greek-omitted} σοι μιαν και [μωση]{.greek-omitted} [μωυση]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι [λαλησει]{.greek-omitted} [λαλησαι]{.greek-added} ησαν γαρ εκφοβοι[9:6]{.aside}

και [ιδου]{.greek-added} εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και ηλθεν φωνη εκ της νεφελης [λεγουσα]{.greek-added} ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος [ακουετε]{.greek-added} αυτου [ακουετε]{.greek-omitted}[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον [αλλα]{.greek-omitted} [αλλ]{.greek-added} [η]{.greek-added} τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

[και]{.greek-added} καταβαινοντων [δε]{.greek-omitted} αυτων απο του [ορους]{.greek-omitted} [ορος]{.greek-added} διεστειλατο αυτοις ινα [μηδενι]{.greek-omitted} [μηδενη]{.greek-added} [διηγησωνται]{.greek-omitted} [διηγησονται]{.greek-added} α ειδον ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [αναστει]{.greek-added} εκ νεκρων [αναστη]{.greek-omitted}[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους [συζητουντες]{.greek-omitted} [συνζητουντες]{.greek-added} τι εστιν το εκ νεκρων [αναστηναι]{.greek-omitted} [αναστειναι]{.greek-added}[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων [πρωτον]{.greek-omitted} [πρωτος]{.greek-added} αποκαθιστα παντα [καθως]{.greek-added} [και]{.greek-omitted} [πως]{.greek-omitted} γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και [εξουδενωθη]{.greek-omitted} [εξουθενηθη]{.greek-added}[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας εληλυθεν και εποιησαν αυτω [παντα]{.greek-added} οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις [συζητουντας]{.greek-omitted} [συνζητουντας]{.greek-added} αυτοις[9:14]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} πας ο οχλος [ιδων]{.greek-omitted} [ιδοντες]{.greek-added} αυτον [εξεθαμβηθη]{.greek-omitted} [εξεθαμβηθησαν]{.greek-added} και προστρεχοντες [ησπαζοντο]{.greek-omitted} [εισπαζοντο]{.greek-added} αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επερωτησεν]{.greek-added} τους [γραμματεις]{.greek-omitted} [γραμματης]{.greek-added} τι [συζητειτε]{.greek-omitted} [συνζητειται]{.greek-added} προς [αυτους]{.greek-omitted} [εαυτους]{.greek-added}[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε [ηνεγκα]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [μου]{.greek-omitted} [προς]{.greek-omitted} [σε]{.greek-omitted} [εχοντα]{.greek-omitted} [πνευμα]{.greek-omitted} [αλαλον]{.greek-omitted}[9:17]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οχλου]{.greek-omitted} [ειπεν]{.greek-omitted} [διδασκαλε]{.greek-omitted} ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον [και]{.greek-added} [κοφον]{.greek-added}[9:17 | instance no. 2]{.aside}

και οπου [αν]{.greek-omitted} [εαν]{.greek-added} αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και [ξηραινεται]{.greek-omitted} [ξηρενεται]{.greek-added} και ειπον τοις μαθηταις σου ινα [αυτο]{.greek-omitted} [αυτω]{.greek-added} εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-added} αυτω [λεγει]{.greek-omitted} ω γενεα απιστος εως ποτε προς υμας [εσομαι]{.greek-omitted} [εσωμαι]{.greek-added} εως ποτε ανεξομαι υμων [φερετε]{.greek-omitted} [φερεται]{.greek-added} αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και επηρωτησεν τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε ειπεν παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ εβαλεν και εις υδατα ινα [απολεση]{.greek-omitted} [απωλεσει]{.greek-added} αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας [[κυριε]{.greek-abbr}]{.greek-added}[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [το]{.greek-omitted} ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος επετιμησεν [τω]{.greek-omitted} [το]{.greek-added} [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε [τους]{.greek-added} πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και [εισελθοντα]{.greek-omitted} [εισελθοντος]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added} εις οικον οι μαθηται αυτου [κατ]{.greek-added} [ιδιαν]{.greek-added} επηρωτων αυτον [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [δια]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν [αυτοις]{.greek-omitted} [τουτο]{.greek-omitted} [το]{.greek-omitted} [γενος]{.greek-omitted} [εν]{.greek-omitted} [ουδενι]{.greek-omitted} [δυναται]{.greek-omitted} [εξελθειν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εν]{.greek-omitted} [προσευχη]{.greek-omitted} [και]{.greek-omitted} [νηστεια]{.greek-omitted}[9:29]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} αυτοις τουτο [το]{.corr} γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29 | instance no. 2]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον [επερωτησαι]{.greek-omitted} [επερωτησε]{.greek-added}[9:32]{.aside}

και ηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν [τη]{.greek-omitted} [τι]{.greek-added} οδω [διελογιζεσθαι]{.greek-added} προς εαυτους [διελογιζεσθε]{.greek-omitted}[9:33]{.aside}

οι δε εσιωπων προς [αλληλους]{.greek-omitted} [αλλιλους]{.greek-added} γαρ διελεχθησαν εν τη οδω τις [η]{.greek-added} μειζων[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} εφωνησεν τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι εσται παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο [εν]{.greek-omitted} [μεσω]{.greek-omitted} [εμμεσω]{.greek-added} αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου εμε [δεχεται]{.greek-omitted} [δεχετε]{.greek-added} και ος εαν εμε [δεξηται]{.greek-omitted} [δεξητε]{.greek-added} ουκ εμε [δεχεται]{.greek-omitted} [δεχετε]{.greek-added} αλλα τον αποστειλαντα με[9:37]{.aside}

[εφη]{.greek-added} [απεκριθη]{.greek-omitted} [δε]{.greek-omitted} αυτω [ο]{.greek-added} ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} τινα [εν]{.greek-added} τω ονοματι σου εκβαλλοντα [τα]{.greek-added} δαιμονια [ος]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted} και [εκωλυσαμεν]{.greek-omitted} [εκολυσαμεν]{.greek-added} αυτον οτι ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος [ποιησει]{.greek-omitted} [ποιησας]{.greek-added} δυναμιν επι τω ονοματι μου και [δυνησεται]{.greek-omitted} [δυνησειτε]{.greek-added} ταχυ [κακολογησαι]{.greek-omitted} [κακολογησε]{.greek-added} με[9:39]{.aside}

ος γαρ ουκ εστιν καθ [υμων]{.greek-omitted} [ημων]{.greek-added} υπερ [υμων]{.greek-omitted} [ημων]{.greek-added} εστιν[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτησει]{.greek-added} υμας ποτηριον υδατος εν ονοματι [μου]{.greek-omitted} οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν [οτι]{.greek-added} ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος εαν [σκανδαλιση]{.greek-omitted} [σκανδαλισει]{.greek-added} [ενα]{.greek-omitted} [των]{.greek-omitted} [μικρων]{.greek-omitted} [των]{.greek-omitted} [πιστευοντων]{.greek-omitted} [εις]{.greek-omitted} [εμε]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [αυτω]{.greek-omitted} [μαλλον]{.greek-omitted} [ει]{.greek-omitted} [περικειται]{.greek-omitted} [λιθος]{.greek-omitted} [μυλικος]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [τραχηλον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [βεβληται]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted}[9:42]{.aside}

[και]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [σκανδαλιση]{.greek-omitted} ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον εστιν αυτω [μαλλον]{.greek-omitted} [μαλλων]{.greek-added} ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42 | instance no. 2]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι εστιν κυλλον εις την ζωην εισελθειν η [τας]{.greek-omitted} δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκωλιξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε [αποκοψον]{.greek-omitted} [εκκοψον]{.greek-added} αυτον καλον [γαρ]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} σοι εισελθειν εις την ζωην χωλον [η]{.greek-omitted} [ει]{.greek-added} τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι εστιν μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι [αλισθησεται]{.greek-omitted} [αλησθησεται]{.greek-added} και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον [γενηται]{.greek-omitted} [γενητε]{.greek-added} εν τινι αυτο [αρτυσετε]{.greek-omitted} [αρτυσεται]{.greek-added} εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας [και]{.greek-added} δια του περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι [επηρωτησαν]{.greek-omitted} [επηρωτων]{.greek-added} αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} επετρεψεν βιβλιον αποστασιου [γραψαι]{.greek-omitted} [και]{.greek-omitted} [απολυσαι]{.greek-omitted}[10:4]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [μωσης]{.greek-omitted} [επετρεψεν]{.greek-omitted} [βιβλιον]{.greek-omitted} [αποστασιου]{.greek-omitted} γραψαι και απολυσαι[10:4 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε [αρχης]{.greek-omitted} [αρχις]{.greek-added} κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

[και]{.greek-added} [ειπεν]{.greek-added} ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταλιψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι εισιν δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [του]{.greek-omitted} [τουτου]{.greek-added} αυτου [επηρωτησαν]{.greek-omitted} [επηρωτων]{.greek-added} αυτον[10:10]{.aside}

και λεγει αυτοις ος [εαν]{.greek-omitted} [αν]{.greek-added} απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτισεν]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηνλογει]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} [πλουσιος]{.greek-added} προσδραμων [εις]{.greek-omitted} και γονυπετησας αυτον [επηρωτα]{.greek-omitted} [επιρωτα]{.greek-added} αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις [αγαθον]{.greek-omitted} [αγαθων]{.greek-added} ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας [εντολας]{.greek-omitted} [εντωλας]{.greek-added} οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης μη [αποστερησης]{.greek-omitted} [αποστερισης]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ [νε]{.greek-added} [νεοτητος]{.greek-omitted} [μου]{.greek-omitted}[10:20]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ταυτα]{.greek-omitted} [παντα]{.greek-omitted} [εφυλαξαμην]{.greek-omitted} [εκ]{.greek-omitted} [νεοτητος]{.greek-omitted} [οτητος]{.greek-added} μου [τι]{.greek-added} [ετι]{.greek-added} [υστερω]{.greek-added}[10:20 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω εν [σε]{.greek-added} [σοι]{.corr} υστερει [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} υπαγε οσα εχεις πωλησον και δος πτωχοις και [εξεις]{.greek-omitted} [εξης]{.greek-added} θησαυρον εν [ουρανω]{.greek-omitted} [[ουνω]{.greek-abbr}]{.greek-added} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι αρας τον [σταυρον]{.greek-abbr} [σου]{.greek-added}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν [λυπουμενος]{.greek-omitted} [λειπουμενος]{.greek-added} ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} [τους]{.greek-added} [μαθητας]{.greek-added} [αυτου]{.greek-added} λεγει [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} πως δυσκολως οι τα χρηματα [εχοντες]{.greek-omitted} [εχωντες]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις [τεκνα]{.greek-omitted} [τεκνια]{.greek-added} πως δυσκολον εστιν τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον εστιν καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} [λεγει]{.greek-omitted} [εφη]{.greek-added} παρα [ανθρωποις]{.greek-abbr} [τουτο]{.greek-added} αδυνατον [εστιν]{.greek-added} αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα εστιν παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας [και]{.greek-added} [[πατερας]{.greek-abbr}]{.greek-added} και [μητερας]{.greek-abbr} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον [κληρονομησει]{.greek-added}[10:30]{.aside}

πολλοι δε εσονται [πρω]{.greek-added} [πρωτοι]{.greek-omitted} [εσχατοι]{.greek-omitted} [και]{.greek-omitted} [εσχατοι]{.greek-omitted} [πρωτοι]{.greek-omitted}[10:31]{.aside}

[τοι]{.greek-added} [πολλοι]{.greek-omitted} [δε]{.greek-omitted} [εσονται]{.greek-omitted} [πρωτοι]{.greek-omitted} εσχατοι και εσχατοι πρωτοι[10:31 | instance no. 2]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις αρχιερευσιν και γραμματευσιν και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33]{.aside}

και [εμπαιξουσιν]{.greek-omitted} [εμπεξουσιν]{.greek-added} [αυτω]{.greek-added} [και]{.greek-added} [εμπτυσουσιν]{.greek-added} αυτω και μαστιγωσουσιν αυτον και [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [απωκτενουσιν]{.greek-added} αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι [του]{.greek-added} ζεβεδαιου λεγοντες [αυτω]{.greek-added} [διδασκαλε]{.greek-omitted} [διδασκελε]{.greek-added} [θελομεν]{.greek-omitted} [θελωμεν]{.greek-added} ινα ο εαν αιτησωμεν [σε]{.greek-added} ποιησης ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι [θελετε]{.greek-omitted} [θελεται]{.greek-added} ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι [αιτεισθε]{.greek-omitted} [αιτεισθαι]{.greek-added} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπιζομαι]{.greek-added} βαπτισθησεσθε[10:39]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις [ητοιμασται]{.greek-omitted} [ειτοιμαστε]{.greek-added} [υπο]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added}[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι [δοκουντες]{.greek-omitted} [αρχειν]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted} [κατακυριευουσιν]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μεγαλοι]{.greek-omitted} [αυτων]{.greek-omitted} [κατεξουσιαζουσιν]{.greek-omitted} [αυτων]{.greek-omitted}[10:42]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [οιδατε]{.greek-omitted} [οτι]{.greek-omitted} [οι]{.greek-omitted} δοκουντες [αρχειν]{.greek-omitted} [αρχιν]{.greek-added} των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42 | instance no. 2]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} [μεγας]{.greek-added} γενεσθαι [μεγας]{.greek-omitted} εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} υμων [γενεσθαι]{.greek-omitted} πρωτος [ειναι]{.greek-added} εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [υιος]{.greek-abbr} τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση [ο]{.greek-omitted} [αυτος]{.greek-added} δε πολλω μαλλον [εκραζεν]{.greek-omitted} [εκραξεν]{.greek-added} [[κυριε]{.greek-abbr}]{.greek-added} [υιε]{.greek-abbr} [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και φωνουσιν το[ν]{.unclear} τυφλον λεγοντες αυτω θαρσει εγειραι φωνει [σε]{.greek-omitted} [σαι]{.greek-added}[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου [αναστας]{.greek-omitted} [αναπηδησας]{.greek-added} ηλθεν προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις [λεγει]{.greek-omitted} αυτω ο [ιησους]{.greek-abbr} [ειπεν]{.greek-added} τι [σοι]{.greek-added} θελεις ποιησω [σοι]{.greek-omitted} ο δε τυφλος ειπεν αυτω ραββουνι ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου σεσωκεν σε και ευθεως ανεβλεψεν και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [και]{.greek-added} [η]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} [και]{.greek-added} [ηλθεν]{.greek-added} εις [βηθσφαγη]{.greek-omitted} [βιθσφαγη]{.greek-added} και [βηθανιαν]{.greek-omitted} [βιθανιαν]{.greek-added} προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} εις την [κωμην]{.greek-omitted} [κωμιν]{.greek-added} την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκεν]{.greek-added} [λυσαντες]{.greek-omitted} [αυτον]{.greek-omitted} [αγαγετε]{.greek-omitted}[11:2]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [κωμην]{.greek-omitted} [την]{.greek-omitted} [κατεναντι]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [εισπορευομενοι]{.greek-omitted} [εις]{.greek-omitted} [αυτην]{.greek-omitted} [ευρησετε]{.greek-omitted} [πωλον]{.greek-omitted} [δεδεμενον]{.greek-omitted} [εφ]{.greek-omitted} [ον]{.greek-omitted} [ουδεις]{.greek-omitted} [ανθρωπων]{.greek-omitted} [κεκαθικεν]{.greek-omitted} λυσαντες αυτον αγαγετε [μοι]{.greek-added}[11:2 | instance no. 2]{.aside}

και εαν τις υμιν ειπη τι [ποιειτε]{.greek-omitted} [τουτο]{.greek-omitted} [λυεται]{.greek-added} [τον]{.greek-added} [πολον]{.greek-added} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον [δεδεμενον]{.greek-added} [τον]{.greek-added} πωλον [δεδεμενον]{.greek-omitted} προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και [ηγαγον]{.greek-omitted} [φερουσιν]{.greek-added} τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια [αυτων]{.greek-omitted} [εαυτων]{.greek-added} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επ αυτω[11:7]{.aside}

[και]{.greek-added} πολλοι [δε]{.greek-omitted} τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} [εκοπτον]{.greek-omitted} [εκοπτων]{.greek-added} εκ των δενδρων και [εστρωννυον]{.greek-omitted} [εστρωνυον]{.greek-added} εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα [τω]{.greek-added} [υψιστω]{.greek-added} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

[και]{.greek-added} ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} [και]{.greek-omitted} εις το ιερον και περιβλεψαμενος παντα οψιας [ηδη]{.greek-omitted} [ετι]{.greek-added} ουσης της ωρας εξηλθεν εις [βηθανιαν]{.greek-omitted} [βιθανιαν]{.greek-added} μετα των δωδεκα[11:11]{.aside}

και τη [επαυριον]{.greek-omitted} [επαυρον]{.greek-added} εξελθοντων αυτων απο [βηθανιας]{.greek-omitted} [βιθανιας]{.greek-added} [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added}[11:12]{.aside}

και ιδων συκην [απο]{.greek-added} μακροθεν εχουσαν φυλλα ηλθεν ει αρα [τι]{.greek-added} ευρησει [τι]{.greek-omitted} εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα [μονον]{.greek-added} ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη [μηκετι]{.greek-omitted} [μηκαιτι]{.greek-added} [εκ]{.greek-omitted} [σου]{.greek-omitted} εις τον αιωνα [εκ]{.greek-added} [σου]{.greek-added} [καρπον]{.greek-added} μηδεις [καρπον]{.greek-omitted} φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας [καθεδρας]{.greek-omitted} [των]{.greek-omitted} [πωλουντων]{.greek-omitted} [τας]{.greek-omitted} [περιστερας]{.greek-omitted} [κατεστρεψεν]{.greek-omitted}[11:15]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [εισελθων]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκβαλλειν]{.greek-omitted} [τους]{.greek-omitted} [πωλουντας]{.greek-omitted} [και]{.greek-omitted} [αγοραζοντας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [τραπεζας]{.greek-omitted} [των]{.greek-omitted} [κολλυβιστων]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} καθεδρας των πωλουντων τας περιστερας κατεστρεψεν[11:15 | instance no. 2]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και εδιδασκεν λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται πασιν τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον [απολεσωσιν]{.greek-omitted} [απωλεσωσιν]{.greek-added} εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και [οτε]{.greek-omitted} [οταν]{.greek-added} οψε εγενετο [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} εξω της πολεως[11:19]{.aside}

και [παραπορευομενοι]{.greek-added} πρωι [παραπορευομενοι]{.greek-omitted} [ειδον]{.greek-omitted} [ειδων]{.greek-added} την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι [ιδε]{.greek-omitted} [ιδου]{.greek-added} η συκη ην κατηρασω εξηρανται[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις [ει]{.greek-added} εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη [τω]{.greek-omitted} [το]{.greek-added} ορει τουτω αρθητι και βληθητι εις την θαλασσαν και [μη]{.greek-omitted} [μι]{.greek-added} διακριθη εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πειστευειτε]{.greek-added} οτι [α]{.greek-omitted} [ο]{.greek-added} λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν [οτι]{.greek-added} παντα οσα [αν]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [αιτησθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} [και]{.greek-added} [αιτεισθαι]{.greek-added} πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκεται]{.greek-added} προσευχομενοι [αφιετε]{.greek-omitted} [αφετε]{.greek-added} ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς [αυτον]{.greek-omitted} [αυτων]{.greek-added} οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις [και]{.greek-omitted} [η]{.greek-added} τις σοι [εδωκεν]{.greek-added} την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} [ινα]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιης]{.greek-omitted}[11:28]{.aside}

[ινα]{.greek-added} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} [εξουσια]{.greek-omitted} ταυτα ποιεις [και]{.greek-omitted} [τις]{.greek-omitted} [σοι]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [ταυτην]{.greek-omitted} [εδωκεν]{.greek-omitted} [ινα]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιης]{.greek-omitted}[11:28 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-omitted} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [ενα]{.greek-added} [λογων]{.greek-added} και [εγω]{.greek-omitted} [ενα]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [αποκριθητε]{.greek-omitted} [αποκριθηται]{.greek-added} μοι [και]{.greek-omitted} [καγω]{.greek-added} [υμιν]{.greek-added} ερω [υμιν]{.greek-omitted} εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου [ποθεν]{.greek-added} [ην]{.greek-added} εξ [ουρανου]{.greek-abbr} [ην]{.greek-omitted} η εξ [ανθρωπων]{.greek-abbr} [αποκριθητε]{.greek-omitted} [αποκριθηται]{.greek-added} μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ ουρανου ερει δια τι [ουν]{.greek-omitted} ουκ [επιστευσατε]{.greek-omitted} [επιστευσαται]{.greek-added} αυτω[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-omitted} [[ανων]{.greek-abbr}]{.greek-added} εφοβουντο τον λαον απαντες γαρ ειχον τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} τω [ιησου]{.greek-abbr} [λεγουσιν]{.greek-added} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα [[ανθρωπος]{.greek-abbr}]{.greek-added} εφυτευσεν [ανθρωπος]{.greek-omitted} και περιεθηκεν φραγμον και ωρυξεν υποληνιον και ωκοδομησεν [αυτω]{.greek-added} πυργον και [εξεδοτο]{.greek-omitted} [εξεδετο]{.greek-added} αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και απεστειλεν προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων [λαβη]{.greek-omitted} [λαβει]{.greek-added} απο [του]{.greek-omitted} [καρπου]{.greek-omitted} [των]{.greek-added} [καρπων]{.greek-added} του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν απεστειλεν προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και [απεστειλεν]{.greek-added} παλιν αλλον [απεστειλεν]{.greek-omitted} κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα [ειχεν]{.greek-added} [υιον]{.greek-abbr} [εχων]{.greek-omitted} αγαπητον [αυτου]{.greek-omitted} [αυτον]{.greek-added} [και]{.greek-added} απεστειλεν [και]{.greek-omitted} αυτον [εσχατον]{.greek-added} προς αυτους [εσχατον]{.greek-omitted} λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [ειπον]{.greek-omitted} [θεασαμενοι]{.greek-added} [αυτον]{.greek-added} [ερχομενον]{.greek-added} προς εαυτους [ειπον]{.greek-added} οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται [η]{.greek-omitted} [κληρονομια]{.greek-omitted}[12:7]{.aside}

[εκεινοι]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [γεωργοι]{.greek-omitted} [ειπον]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [οτι]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [κληρονομος]{.greek-omitted} [δευτε]{.greek-omitted} [αποκτεινωμεν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ημων]{.greek-omitted} [εσται]{.greek-omitted} η κληρονομια[12:7 | instance no. 2]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδοκημασαν]{.greek-added} οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις [ημων]{.greek-omitted} [υμων]{.greek-added}[12:11]{.aside}

και εζητουν αυτον κρατησαι και [εφοβηθησαν]{.greek-omitted} [εφοβουντο]{.greek-added} τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην [ταυτην]{.greek-added} ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και αποστελλουσιν προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον αγρευσωσιν λογω[12:13]{.aside}

[και]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} [ει]{.greek-omitted} [η]{.greek-added} και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [ειπε]{.greek-added} [ουν]{.greek-added} [ημιν]{.greek-added} εξεστιν [επικεφαλεον]{.greek-added} [δουναι]{.greek-added} κηνσον [καισαρι]{.greek-omitted} [καισαρει]{.greek-added} [δουναι]{.greek-omitted} η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι δηναριον ινα [ιδω]{.greek-omitted} [ειδω]{.greek-added}[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος [το]{.greek-added} καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και [εθαυμασαν]{.greek-omitted} [εθαυμαζον]{.greek-added} επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και [επηρωτησαν]{.greek-omitted} [επηρωτων]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} λεγοντες[12:18]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν ημιν [οτι]{.greek-omitted} [ινα]{.greek-added} εαν τινος αδελφος [αποθανη]{.greek-omitted} [αποθανει]{.greek-added} και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [ουν]{.greek-added} αδελφοι ησαν [παρ]{.greek-added} [ημιν]{.greek-added} και ο πρωτος ελαβεν γυναικα και [απεθανεν]{.greek-added} [και]{.greek-added} [αποθνησκων]{.greek-omitted} [αποθνισκων]{.greek-added} ουκ αφηκεν σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν [μη]{.greek-added} [καταλειπων]{.greek-added} [και]{.greek-omitted} [ουδε]{.greek-omitted} [αυτος]{.greek-omitted} [αφηκεν]{.greek-omitted} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και [οι]{.greek-added} [επτα]{.greek-added} ελαβον αυτην [οι]{.greek-omitted} [επτα]{.greek-omitted} και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} παντων [απεθανεν]{.greek-omitted} και η γυνη [απεθανεν]{.greek-added}[12:22]{.aside}

εν τη αναστασει [ουν]{.greek-added} οταν αναστωσιν τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added} μη [ειδοτες]{.greek-omitted} [ιδοτες]{.greek-added} τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [γαμηζονται]{.greek-added} αλλ εισιν ως αγγελοι [οι]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω [ειμι]{.greek-added} ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} [ισαακ]{.greek-omitted} [ιακωβ]{.greek-added} και ο [θεος]{.greek-abbr} [ιακωβ]{.greek-omitted} [ισαακ]{.greek-added}[12:26]{.aside}

ουκ εστιν [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added}[12:27]{.aside}

και προσελθων εις των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ακουσας αυτων [συζητουντων]{.greek-omitted} [συνζητουντων]{.greek-added} [ειδως]{.greek-omitted} [ιδων]{.greek-added} οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια εστιν πρωτη παντων εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω οτι πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολη]{.greek-added} ακουε [ισραηλ]{.greek-omitted} [[ηλ]{.greek-abbr}]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη [εστιν]{.greek-added} [η]{.greek-added} πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια [αυτη]{.greek-omitted} [αυτης]{.greek-added} [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} τον πλησιον σου ως σεαυτον μειζων τουτων αλλη εντολη ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις εστιν [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας [σου]{.greek-added} και εξ ολης [της]{.greek-omitted} [συνεσεως]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [αγαπαν]{.greek-omitted} [τον]{.greek-omitted} [πλησιον]{.greek-omitted} [ως]{.greek-omitted} [εαυτον]{.greek-omitted} [πλειον]{.greek-omitted} [εστιν]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} [ολοκαυτωματων]{.greek-omitted} [και]{.greek-omitted} [θυσιων]{.greek-omitted}[12:33]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [αγαπαν]{.greek-omitted} [αυτον]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον εστιν παντων των [ολοκαυτωματων]{.greek-omitted} [ολοκαυτοματων]{.greek-added} και [των]{.greek-added} θυσιων[12:33 | instance no. 2]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις [ουκετι]{.greek-omitted} [ουκ]{.greek-added} ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω ιερω πως λεγουσιν οι [γραμματεις]{.greek-omitted} [γραμματης]{.greek-added} οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [[δαυιδ]{.greek-abbr}]{.greek-added} εστιν [δαυιδ]{.greek-omitted}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και [ποθεν]{.greek-omitted} [πως]{.greek-added} [υιος]{.greek-abbr} αυτου εστιν και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου [βλεπετε]{.greek-omitted} [λεπεται]{.greek-added} απο των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και [προφασει]{.greek-omitted} [πρωφασει]{.greek-added} [μακρα]{.greek-omitted} [μακραν]{.greek-added} προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} ο [ιησους]{.greek-abbr} [κατενω]{.greek-added} [κατεναντι]{.corr} του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη εβαλεν λεπτα δυο ο εστιν κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη [πλειον]{.greek-omitted} [πλιον]{.greek-added} παντων βεβληκεν των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτω εις των μαθητων αυτου διδασκαλε [ιδε]{.greek-omitted} [ειδε]{.greek-added} ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη [ωδε]{.greek-added} λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το [σημειον]{.greek-omitted} [συμειον]{.greek-added} οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας [πλανηση]{.greek-omitted} [πλανησει]{.greek-added}[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} και πολλους πλανησουσιν[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουσηται]{.greek-added} πολεμους και ακοας πολεμων [ορατε]{.greek-added} μη [θροεισθε]{.greek-omitted} [θροεισθαι]{.greek-added} δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται [σεισμοι]{.greek-omitted} [σισμοι]{.greek-added} κατα τοπους και εσονται λιμοι και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} [ωδινων]{.greek-omitted} [ωδηνων]{.greek-added} ταυτα [παντα]{.greek-added}[13:8]{.aside}

[βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} δε [υμεις]{.greek-omitted} [υμας]{.greek-added} εαυτους [παραδωσουσιν]{.greek-omitted} [παραδοσουσιν]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας [δαρησεσθε]{.greek-omitted} [δαρησεσθαι]{.greek-added} και επι [ηγεμονων]{.greek-omitted} [ηγεμωνας]{.greek-added} και [βασιλεων]{.greek-omitted} [βασιλεις]{.greek-added} [σταθησεσθε]{.greek-omitted} [σταθησεσθαι]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη [πρωτον]{.greek-added} δει [πρωτον]{.greek-omitted} κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε αγαγωσιν υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [προμεριμνησηται]{.greek-added} τι [λαλησητε]{.greek-omitted} [μηδε]{.greek-omitted} [μελετατε]{.greek-omitted} [αλλ]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [δοθη]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [τουτο]{.greek-omitted} [λαλειτε]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [εστε]{.greek-omitted} [υμεις]{.greek-omitted} [οι]{.greek-omitted} [λαλουντες]{.greek-omitted} [αλλα]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αγιον]{.greek-omitted}[13:11]{.aside}

[οταν]{.greek-omitted} [δε]{.greek-omitted} [αγαγωσιν]{.greek-omitted} [υμας]{.greek-omitted} [παραδιδοντες]{.greek-omitted} [μη]{.greek-omitted} [προμεριμνατε]{.greek-omitted} [τι]{.greek-omitted} λαλησητε μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο [λαλειτε]{.greek-omitted} [λαλητε]{.greek-added} ου γαρ [εστε]{.greek-omitted} [εσται]{.greek-added} υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11 | instance no. 2]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-omitted} [τεκνον]{.greek-omitted} [και]{.greek-omitted} επαναστησονται τεκνα επι [γονεις]{.greek-omitted} [γωνεις]{.greek-added} και θανατωσουσιν αυτους[13:12]{.aside}

και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} [μισουμενοι]{.greek-omitted} [μησουμενοι]{.greek-added} υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε [ιδητε]{.greek-omitted} [ειδητε]{.greek-added} το [βδελυγμα]{.greek-omitted} [βδελλυγμα]{.greek-added} της ερημωσεως το ρηθεν υπο δανιηλ του προφητου [εστως]{.greek-omitted} [εστος]{.greek-added} [εν]{.greek-added} [τοπω]{.greek-added} οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν [τη]{.greek-omitted} [τι]{.greek-added} ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε [εισελθετω]{.greek-omitted} [εισελθατω]{.greek-added} [αραι]{.greek-omitted} [αρε]{.greek-added} τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται η φυγη υμων [χειμωνος]{.greek-omitted} [χιμωνος]{.greek-added} [μηδε]{.greek-added} [σαββατου]{.greek-added}[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου γεγονεν τοιαυτη απ αρχης κτισεως [ης]{.greek-omitted} [κοσμου]{.greek-added} [η]{.greek-added} εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη [γενηται]{.greek-omitted} [γενητε]{.greek-added}[13:19]{.aside}

και ει μη [κυριος]{.greek-omitted} [εκολοβωσεν]{.greek-omitted} [εκολοβοσεν]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο εκολοβωσεν τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσωσιν]{.greek-added} σημεια [και]{.greek-omitted} [[κυριε]{.greek-abbr}]{.greek-added} τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την [θλιψιν]{.greek-omitted} [θλιψην]{.greek-added} [των]{.greek-added} [ημερων]{.greek-added} [εκεινην]{.greek-omitted} [εκεινων]{.greek-added} ο ηλιος [σκοτισθησεται]{.greek-omitted} [σκοτησθησεται]{.greek-added} και η [σεληνη]{.greek-omitted} [σελινη]{.greek-added} ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι [αστερες]{.greek-omitted} [αστεραις]{.greek-added} του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} [σαλευθησονται]{.greek-omitted} [σαλευθη]{.greek-added}[13:25]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [αστερες]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [εσονται]{.greek-omitted} [σονται]{.greek-added} [εκπιπτοντες]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [δυναμεις]{.greek-omitted} [αι]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [σαλευθησονται]{.greek-omitted}[13:25 | instance no. 2]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα [δυναμεως]{.greek-omitted} [διναμεως]{.greek-added} [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης [μαθετε]{.greek-omitted} [μαθεται]{.greek-added} την παραβολην οταν [αυτης]{.greek-omitted} ηδη ο κλαδος [αυτης]{.greek-added} απαλος γενηται και εκφυη τα φυλλα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν [ειδηται]{.greek-added} ταυτα [ιδητε]{.greek-omitted} γινομενα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης η [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [των]{.greek-added} [[ουνων]{.greek-abbr}]{.greek-added} [οι]{.greek-omitted} [εν]{.greek-omitted} [ουρανω]{.greek-omitted} [ουδε]{.greek-omitted} [ουτε]{.greek-added} ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} [μονος]{.greek-added}[13:32]{.aside}

βλεπετε αγρυπνειτε και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [γαρ]{.greek-added} [ανθρωπος]{.greek-abbr} αποδημος [αφεις]{.greek-omitted} [αφης]{.greek-added} την οικιαν αυτου και δους τοις δουλοις [αυτου]{.greek-omitted} [εαυτου]{.greek-added} την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα [γρηγορη]{.greek-omitted} [γρηγορηση]{.greek-added}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} [ευρη]{.greek-omitted} [ευρησει]{.greek-added} υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω πασιν λεγω [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added}[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω κρατησαντες [αποκτεινωσιν]{.greek-omitted} [αποκτινωσιν]{.greek-added}[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν τη οικια σιμωνος του λεπρου κατακειμενου αυτου ηλθεν γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης [πολυτελους]{.greek-omitted} [πολυτιμου]{.greek-added} και συντριψασα [το]{.greek-omitted} [τον]{.greek-added} αλαβαστρον κατεχεεν αυτου κατα της [κεφαλης]{.greek-omitted}[14:3]{.aside}

[και]{.greek-omitted} [οντος]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} κεφαλης[14:3 | instance no. 2]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η [απωλεια]{.greek-omitted} [απωλια]{.greek-added} αυτη του μυρου γεγονεν[14:4]{.aside}

[ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} γαρ τουτο [το]{.greek-added} [μυρων]{.greek-added} πραθηναι επανω [τριακοσιων]{.greek-omitted} [τριακωσιων]{.greek-added} δηναριων και δοθηναι τοις πτωχοις και [ενεβριμωντο]{.greek-omitted} [ενεβρημωντο]{.greek-added} αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν [θελητε]{.greek-omitted} [θεληται]{.greek-added} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} [παντοτε]{.greek-added} ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη εποιησεν προελαβεν μυρισαι [μου]{.greek-omitted} το σωμα [μου]{.greek-added} εις τον ενταφιασμον[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας [ο]{.greek-omitted} ισκαριωτης εις των δωδεκα απηλθεν προς τους αρχιερεις ινα [αυτον]{.greek-added} παραδω [αυτης]{.greek-added} [αυτον]{.greek-omitted} [αυτοις]{.greek-omitted}[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλαντο]{.greek-omitted} [επηγγιλαντο]{.greek-added} αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως [αυτον]{.greek-added} ευκαιρως [αυτον]{.greek-omitted} παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις [απελθοντες]{.greek-omitted} [απελθωντες]{.greek-added} ετοιμασωμεν ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου [λεγων]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} αυτοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που εστιν το καταλυμα [μου]{.greek-added} οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος [υμιν]{.greek-omitted} [ημιν]{.greek-added} [δειξει]{.greek-omitted} [δειξη]{.greek-added} ανωγεον μεγα εστρωμενον ετοιμον [και]{.greek-added} εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον [ετοιμασε]{.greek-added} [αυτω]{.greek-added} οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης [ερχεται]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [δωδεκα]{.greek-omitted}[14:17]{.aside}

[και]{.greek-omitted} [οψιας]{.greek-omitted} [γενομενης]{.greek-omitted} [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} μετα των δωδεκα[14:17 | instance no. 2]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι [και]{.greek-added} [αδημονειν]{.greek-added} και λεγειν αυτω εις καθ εις μητι εγω [ειμι]{.greek-added} και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο [εμβαπτομενος]{.greek-omitted} [εμβπτομενος]{.greek-added} μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} καλον ην αυτω [ει]{.greek-omitted} [η]{.greek-added} ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον [και]{.greek-added} ευλογησας εκλασεν και εδωκεν αυτοις και ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο εστιν το αιμα μου το της καινης διαθηκης το περι πολλων [εκχυνομενον]{.greek-omitted} [εκχυννομενον]{.greek-added} [εις]{.greek-added} [αφεσιν]{.greek-added} [αμαρτιων]{.greek-added}[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της [αμπελου]{.greek-omitted} [απελου]{.greek-added} εως της ημερας εκεινης οταν αυτο πινω [καινον]{.greek-omitted} [καινων]{.greek-added} εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεσθαι]{.greek-added} εν εμοι εν τη νυκτι ταυτη οτι γεγραπται παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα [της]{.greek-added} [ποιμνης]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω [ει]{.greek-added} και [ει]{.greek-omitted} παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} ταυτη πριν η δις [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με[14:30]{.aside}

ο δε [πετρος]{.greek-added} εκπερισσου ελεγεν μαλλον εαν [δεη]{.greek-added} με [συν]{.greek-added} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} σοι [αποθανειν]{.greek-added} ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added} [δε]{.greek-omitted} [και]{.greek-omitted} [παντες]{.greek-omitted} [ελεγον]{.greek-omitted}[14:31]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εκπερισσου]{.greek-omitted} [ελεγεν]{.greek-omitted} [μαλλον]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} [σοι]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [σε]{.greek-omitted} [απαρνησωμαι]{.greek-omitted} [ωσαυτως]{.greek-omitted} δε και παντες ελεγον[14:31 | instance no. 2]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added}[14:34]{.aside}

και προσελθων μικρον [επισεν]{.greek-added} [επεσεν]{.corr} επι της γης και προσηυχετο ινα ει δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ ου τι εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [ο]{.greek-added} τι συ[14:36]{.aside}

και ερχεται [προς]{.greek-added} [τους]{.greek-added} [μαθητας]{.greek-added} και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν [γρηγορησαι]{.greek-omitted} [γρηγορεισαι]{.greek-added}[14:37]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} [ουν]{.greek-added} και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ινα [μη]{.greek-omitted} [μι]{.greek-added} [εισελθητε]{.greek-omitted} [εισελθηται]{.greek-added} εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και [υποστρεψας]{.greek-omitted} [υπωστρ[ε]{.unclear}ψας]{.greek-added} ευρεν αυτους παλιν καθευδοντας ησαν γαρ [αυτων]{.greek-added} οι οφθαλμοι [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} [βεβαρυμενοι]{.greek-added} και ουκ [ηδεισαν]{.greek-omitted} [ηδησαν]{.greek-added} τι [αποκριθωσιν]{.greek-added} αυτω [αποκριθωσιν]{.greek-omitted}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις [καθευδετε]{.greek-omitted} [καθευδεται]{.greek-added} [το]{.greek-added} λοιπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} απεχει [το]{.greek-added} [τελος]{.greek-added} ηλθεν η ωρα ιδου [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

[εγειρεσθε]{.greek-omitted} [εγειρεσθαι]{.greek-added} αγωμεν ιδου ο παραδιδους [μου]{.greek-added} με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας [ο]{.greek-added} [ησκαριοτης]{.greek-added} εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον [αυτοις]{.greek-omitted} [αυτης]{.greek-added} λεγων ον [αν]{.greek-omitted} [εαν]{.greek-added} φιλησω αυτος εστιν κρατησατε αυτον και [απαγαγετε]{.greek-omitted} [απαγαγεται]{.greek-added} ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει [αυτω]{.greek-omitted} ραββι ραββι [και]{.greek-omitted} [κατεφιλησεν]{.greek-omitted} [αυτον]{.greek-omitted}[14:45]{.aside}

[και]{.greek-omitted} [ελθων]{.greek-omitted} [ευθεως]{.greek-omitted} [προσελθων]{.greek-omitted} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} [ραββι]{.greek-omitted} και κατεφιλησεν αυτον[14:45 | instance no. 2]{.aside}

οι δε επεβαλον [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας [αυτων]{.greek-omitted} [αυτω]{.greek-added} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των [παρεστηκοτων]{.greek-omitted} [παρεστικοτων]{.greek-added} σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επεσεν]{.greek-added} τον δουλον του αρχιερεως και [αφειλεν]{.greek-omitted} [αφιλεν]{.greek-added} [αυτου]{.greek-omitted} το ωτιον [αυτου]{.greek-added}[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν [ημην]{.greek-omitted} [ημιν]{.greek-added} προς υμας εν τω ιερω διδασκων και ουκ [εκρατησατε]{.greek-omitted} [εκρατησαται]{.greek-added} με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον [οι]{.greek-added} [μαθηται]{.greek-added} [εφυγον]{.greek-added} παντες [εφυγον]{.greek-omitted}[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} την σινδονα [εφυγεν]{.greek-added} γυμνος [εφυγεν]{.greek-omitted} απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν [ινα]{.greek-added} [εις]{.greek-omitted} [το]{.greek-omitted} [θανατωσαι]{.greek-omitted} αυτον [θανατωσουσιν]{.greek-added} και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και [ισαι]{.greek-omitted} [εισαι]{.greek-added} αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον [χειροποιητον]{.greek-omitted} [αχειροποιητον]{.greek-added} και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως [ιση]{.greek-omitted} [ειση]{.greek-added} [ην]{.greek-omitted} η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις [το]{.greek-added} μεσον επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και [ουκ]{.greek-added} [απεκρινατο]{.greek-added} ουδεν [απεκρινατο]{.greek-omitted} παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} ειπεν [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [και]{.greek-omitted} [οψεσθε]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [καθημενον]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [και]{.greek-omitted} [ερχομενον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [νεφελων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[14:62]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-added} [συ]{.greek-added} [ειπας]{.greek-added} [οτι]{.greek-added} εγω ειμι και [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [καθημενον]{.greek-added} εκ δεξιων [καθημενον]{.greek-omitted} της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62 | instance no. 2]{.aside}

ο δε αρχιερευς [διαρρηξας]{.greek-omitted} [διαρριξας]{.greek-added} τους χιτωνας αυτου λεγει τι ετι [χρειαν]{.greek-omitted} [χριαν]{.greek-added} [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας [αυτου]{.greek-added} τι υμιν φαινεται οι δε παντες κατεκριναν αυτον [ειναι]{.greek-omitted} ενοχον θανατου [ειναι]{.greek-added}[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν [αυτω]{.greek-added} το προσωπον [αυτου]{.greek-omitted} και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [νυν]{.greek-added} [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισα]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου [κατω]{.greek-added} εν τη αυλη [κατω]{.greek-omitted} ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον [θερμαινομενον]{.greek-omitted} [θερμενομενον]{.greek-added} εμβλεψασα αυτω λεγει και συ μετα του [ναζαρηνου]{.greek-omitted} [ναζαρινου]{.greek-added} [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων [ουκ]{.greek-omitted} [ουτε]{.greek-added} οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} [επισταμαι]{.greek-omitted} [επισταμε]{.greek-added} [συ]{.greek-added} τι [συ]{.greek-omitted} λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ εφωνησεν[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστωσιν]{.greek-added} οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνητο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added}[14:71]{.aside}

και εκ δευτερου αλεκτωρ εφωνησεν και ανεμνησθη ο πετρος το ρημα [ο]{.greek-omitted} [ως]{.greek-added} ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} [φωνησαι]{.greek-omitted} [φωνεισε]{.greek-added} [δις]{.greek-omitted} [δεις]{.greek-added} [απαρνηση]{.greek-omitted} [απαρνησει]{.greek-added} με [τρις]{.greek-omitted} [τρεις]{.greek-added} και επιβαλων [εκλαιεν]{.greek-omitted} [εκλεεν]{.greek-added}[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν [ιδε]{.greek-omitted} [ειδε]{.greek-added} ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν [απεκριθη]{.greek-omitted} [αποκριθει]{.greek-added} ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην [απελυεν]{.greek-omitted} [απελυσεν]{.greek-added} αυτοις [[αυτους]{.corr}]{.greek-added} ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

εγινωσκεν γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδοκασιν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεπεισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} αυτοις[15:11]{.aside}

ο δε πιλατος [παλιν]{.greek-added} αποκριθεις [παλιν]{.greek-omitted} ειπεν αυτοις τι ουν [θελετε]{.greek-omitted} [θελεται]{.greek-added} ποιησω ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} [τον]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν [εκραξαν]{.greek-omitted} [εκραυγαζων]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσωτερος]{.greek-added} [εκραξαν]{.greek-omitted} [εκραυγαζων]{.greek-added} [[στρωσον]{.greek-abbr}]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον [ποιησαι]{.greek-omitted} [ποιειν]{.greek-added} απελυσεν αυτοις τον βαραββαν και παρεδωκεν τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον [εσω]{.greek-omitted} [εξω]{.greek-added} της αυλης ο [ε]{.unclear}στιν πραιτωριον και συγκαλουσιν [ολην]{.greek-omitted} [ολιν]{.greek-added} την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον [χλαμιδα]{.greek-added} [κοκκινην]{.greek-added} [και]{.greek-added} πορφυραν και περιτιθεασιν αυτω πλεξαντες [ακανθινον]{.greek-omitted} [ακανθηνον]{.greek-added} στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και [ετυ]{.greek-added} [ετυπτον]{.greek-omitted} [αυτου]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [καλαμω]{.greek-omitted} [και]{.greek-omitted} [ενεπτυον]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [τιθεντες]{.greek-omitted} [τα]{.greek-omitted} [γονατα]{.greek-omitted} [προσεκυνουν]{.greek-omitted} [αυτω]{.greek-omitted}[15:19]{.aside}

[πτον]{.greek-added} [και]{.greek-omitted} [ετυπτον]{.greek-omitted} αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19 | instance no. 2]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον [την]{.greek-added} [χλαμιδα]{.greek-added} [και]{.greek-added} την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και αγγαρευουσιν παραγοντα τινα σιμωνα [κυρηναιον]{.greek-omitted} [κυριναιον]{.greek-added} ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} γολγοθα τοπον ο εστιν [μεθερμηνευομενον]{.greek-omitted} [μεθερμινευομενον]{.greek-added} κρανιου τοπος[15:22]{.aside}

και [εδιδουν]{.greek-omitted} [διδουσιν]{.greek-added} αυτω πιειν [εσμυρνισμενον]{.greek-omitted} [εσλαψινισμενον]{.greek-added} οινον ο δε ουκ ελαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-omitted} [[στρωσαντες]{.greek-abbr}]{.greek-added} [δε]{.greek-added} αυτον [διαμεριζονται]{.greek-omitted} [διεμερισαντο]{.greek-added} τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη [και]{.greek-omitted} [οτε]{.greek-added} [εσταυρωσαν]{.greek-omitted} [[εστρωσαν]{.greek-abbr}]{.greek-added} αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων [ουτος]{.greek-added}[15:26]{.aside}

και συν αυτω σταυρουσιν δυο ληστας ενα εκ δεξιων και ενα εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν [αυτον]{.greek-omitted} [αυτων]{.greek-added} κινου[ν]{.unclear}τες τας κεφαλας αυτων και [και]{.greek-added} λεγοντες ουα ο [καταλυων]{.greek-omitted} [καταλυον]{.greek-added} τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [καταβηθη]{.greek-added} απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως [δε]{.greek-added} και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} προς [αλληλους]{.greek-omitted} [αλλιλους]{.greek-added} μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

[ει]{.greek-added} ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} [εστιν]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα [ιδωμεν]{.greek-omitted} [ειδωμεν]{.greek-added} και πιστευσωμεν αυτω και οι συνεσταυρωμενοι αυτω ωνειδιζον αυτον[15:32]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατις]{.greek-added}[15:33]{.aside}

και [τη]{.greek-omitted} [τι]{.greek-added} [εννατη]{.greek-added} ωρα [τη]{.greek-omitted} [ενατη]{.greek-omitted} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λειμα]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβαχθανει]{.greek-added} ο εστιν μεθερμηνευομενον [ο]{.greek-omitted} [θεος]{.greek-omitted} [μου]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [μου]{.greek-omitted} [εις]{.greek-omitted} [τι]{.greek-omitted} [με]{.greek-omitted} [εγκατελιπες]{.greek-omitted}[15:34]{.aside}

[και]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [τη]{.greek-omitted} [ενατη]{.greek-omitted} [εβοησεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [λεγων]{.greek-omitted} [ελωι]{.greek-omitted} [ελωι]{.greek-omitted} [λιμα]{.greek-omitted} [σαβαχθανι]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [μεθερμηνευομενον]{.greek-omitted} ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34 | instance no. 2]{.aside}

και τινες των [παρεστηκοτων]{.greek-omitted} [παρεστικοτων]{.greek-added} ακουσαντες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} [ιδου]{.greek-omitted} [ειδε]{.greek-added} ηλιαν φωνει[15:35]{.aside}

[δραμων]{.greek-omitted} [δραμον]{.greek-added} δε εις και [γεμισας]{.greek-omitted} [γεμησας]{.greek-added} σπογγον οξους περιθεις [τε]{.greek-omitted} καλαμω εποτιζεν αυτον λεγων αφετε [ιδωμεν]{.greek-omitted} [ειδωμεν]{.greek-added} [ει]{.greek-omitted} [η]{.greek-added} ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο [παρεστηκως]{.greek-omitted} [παρεστικως]{.greek-added} εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως [[θεου]{.greek-abbr}]{.greek-added} [[υιος]{.greek-abbr}]{.greek-added} [ην]{.greek-added} ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-omitted} [ην]{.greek-omitted} [θεου]{.greek-omitted}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [μαρια]{.greek-added} [η]{.greek-added} [μαγδαλινη]{.greek-added} και μαρια [η]{.corr} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι [και]{.greek-omitted} οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις [ιεροσολυμα]{.greek-omitted} [ιερωσολυμα]{.greek-added}[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο εστιν [προσαββατον]{.greek-omitted} [προς]{.greek-added} [σαββατων]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο [αριμαθαιας]{.greek-omitted} [αριμαθιας]{.greek-added} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας εισηλθεν προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν [ει]{.greek-omitted} [η]{.greek-added} ηδη τεθνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο [το]{.greek-omitted} [τω]{.greek-added} σωμα τω [ισηφ]{.greek-added} [ιωσηφ]{.corr}[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενηλισεν]{.greek-added} τη σινδονι και [κατεθηκεν]{.greek-omitted} [κατεθεικεν]{.greek-added} [αυτον]{.greek-omitted} [αυτο]{.greek-added} εν μνημειω ο ην λελατομημενον εκ πετρας και προσεκυλισεν λιθον [επι]{.greek-omitted} [εις]{.greek-added} την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιωση εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι [αλειψωσιν]{.greek-omitted} [αλιψωσιν]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[16:1]{.aside}

και λιαν πρωι [της]{.greek-omitted} [τη]{.greek-added} [μιας]{.greek-omitted} [μια]{.greek-added} [των]{.greek-added} σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον [προς]{.greek-omitted} [εαυτας]{.greek-omitted} [τις]{.greek-omitted} [αποκυλισει]{.greek-omitted} [ημιν]{.greek-omitted} [τον]{.greek-omitted} [λιθον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [θυρας]{.greek-omitted} [του]{.greek-omitted} [μνημειου]{.greek-omitted}[16:3]{.aside}

[και]{.greek-omitted} [ελεγον]{.greek-omitted} προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3 | instance no. 2]{.aside}

και αναβλεψασαι θεωρουσιν οτι [αποκεκυλισται]{.greek-omitted} [αποκεκυλιστε]{.greek-added} ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον [νεανισκον]{.greek-omitted} [νεανισκων]{.greek-added} καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαβησθαι]{.greek-added} [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [ναζωρηνον]{.greek-added} τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε [ιδε]{.greek-omitted} [ειδε]{.greek-added} ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι [ταχυ]{.greek-added} εφυγον απο του μνημειου ειχεν δε αυτας τρομος και εκστασις και [ουδεν]{.greek-added} [ουδενι]{.corr} ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι πρωτη σαββατου εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη [πορευθεισα]{.greek-omitted} [πορευθησα]{.greek-added} [απηγγειλεν]{.greek-omitted} [απηγγειλον]{.greek-added} τοις μετ αυτου γενομενοις πενθουσιν και κλαιουσιν[16:10]{.aside}

[κακεινοι]{.greek-omitted} [εκεινοι]{.greek-added} ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνιδησεν]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον [εκ]{.greek-added} [νεκρων]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

[οτι]{.greek-added} ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις πιστευσασιν ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια εκβαλουσιν γλωσσαις [λαλησουσιν]{.greek-omitted} [καιναις]{.greek-omitted}[16:17]{.aside}

[σημεια]{.greek-omitted} [δε]{.greek-omitted} [τοις]{.greek-omitted} [πιστευσασιν]{.greek-omitted} [ταυτα]{.greek-omitted} [παρακολουθησει]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [δαιμονια]{.greek-omitted} [εκβαλουσιν]{.greek-omitted} [γλωσσαις]{.greek-omitted} λαλησουσιν [καιναις]{.greek-omitted} [καινες]{.greek-added}[16:17 | instance no. 2]{.aside}

οφεις αρουσιν καν θανασιμον τι πιωσιν ου μη αυτους [βλαψη]{.greek-omitted} [βλαψει]{.greek-added} επι αρρωστους χειρας επιθησουσιν και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} [[ιησους]{.greek-abbr}]{.greek-added} μετα το λαλησαι [αυτις]{.greek-added} [αυτοις]{.corr} ανεληφθη εις τον [ουρανον]{.greek-abbr} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

