---
title: "Collation of Byz^RP^ vs 31162 (1162)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1162 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31162).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1162                                   	| λογος                              	|
| 1162 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1162 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1162               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1162                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1162 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1162                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

τον μεν πρωτον λογον εποιησαμην περι παντων ω θεοφιλε ων ηρξατο ο [ιησους]{.greek-abbr} ποιειν τε και διδασκειν[1:1]{.aside}

αχρι ης ημερας εντειλαμενος τοις αποστολοις δια [πνευματος]{.greek-abbr} αγιου ους εξελεξατο ανεληφθη[1:2]{.aside}

οις και παρεστησεν εαυτον ζωντα μετα το παθειν αυτον εν πολλοις τεκμηριοις δι ημερων τεσσαρακοντα οπτανομενος αυτοις και λεγων τα περι της βασιλειας του [θεου]{.greek-abbr}[1:3]{.aside}

και συναλιζομενος παρηγγειλεν αυτοις απο ιεροσολυμων μη χωριζεσθαι αλλα περιμενειν την [επαγγελιαν]{.greek-omitted} [επαγγελειαν]{.greek-added} του [πατρος]{.greek-abbr} ην ηκουσατε μου[1:4]{.aside}

οτι ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω ου μετα πολλας ταυτας ημερας[1:5]{.aside}

οι μεν ουν συνελθοντες επηρωτων αυτον λεγοντες [κυριε]{.greek-abbr} ει εν τω χρονω τουτω αποκαθιστανεις την βασιλειαν τω [ισραηλ]{.greek-abbr}[1:6]{.aside}

ειπεν δε προς αυτους ουχ υμων εστιν γνωναι χρονους η καιρους ους ο [πατηρ]{.greek-abbr} εθετο εν τη [ιδια]{.greek-omitted} εξουσια[1:7]{.aside}

αλλα ληψεσθε δυναμιν επελθοντος του αγιου [πνευματος]{.greek-abbr} εφ υμας και εσεσθε μοι μαρτυρες εν τε [ιερουσαλημ]{.greek-abbr} και εν παση τη ιουδαια και σαμαρεια και εως εσχατου της γης[1:8]{.aside}

και ταυτα ειπων βλεποντων αυτων επηρθη και νεφελη [υπελαβεν]{.greek-omitted} [υπελαμβανεν]{.greek-added} αυτον απο των οφθαλμων αυτων[1:9]{.aside}

και ως ατενιζοντες ησαν εις τον [ουρανον]{.greek-abbr} πορευομενου αυτου και ιδου ανδρες δυο παρειστηκεισαν αυτοις εν εσθητι λευκη[1:10]{.aside}

οι και ειπον ανδρες γαλιλαιοι τι εστηκατε εμβλεποντες εις τον [ουρανον]{.greek-abbr} ουτος ο [ιησους]{.greek-abbr} ο αναληφθεις αφ υμων εις τον [ουρανον]{.greek-abbr} ουτως ελευσεται ον τροπον εθεασασθε αυτον πορευομενον εις τον [ουρανον]{.greek-abbr}[1:11]{.aside}

τοτε υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} απο ορους του καλουμενου ελαιωνος ο εστιν εγγυς [ιερουσαλημ]{.greek-abbr} σαββατου εχον οδον[1:12]{.aside}

και οτε [εισηλθον]{.greek-omitted} [εισηλ]{.greek-added} [θον]{.greek-added} ανεβησαν εις το υπερωον ου ησαν καταμενοντες ο τε πετρος και ιακωβος και ιωαννης και ανδρεας φιλιππος και θωμας βαρθολομαιος και ματθαιος ιακωβος αλφαιου και σιμων ο ζηλωτης και ιουδας ιακωβου[1:13]{.aside}

ουτοι παντες ησαν προσκαρτερουντες ομοθυμαδον τη προσευχη και τη δεησει συν γυναιξιν και μαρια τη [μητρι]{.greek-abbr} του [ιησου]{.greek-abbr} και συν τοις αδελφοις αυτου[1:14]{.aside}

και εν ταις ημεραις ταυταις αναστας πετρος εν μεσω των μαθητων ειπεν ην τε οχλος ονοματων επι το αυτο [ως]{.greek-omitted} [ωσει]{.greek-added} εκατον εικοσι[1:15]{.aside}

ανδρες αδελφοι εδει πληρωθηναι την γραφην ταυτην ην προειπεν το [πνευμα]{.greek-abbr} το αγιον δια στοματος [δαυιδ]{.greek-abbr} περι ιουδα του γενομενου οδηγου τοις συλλαβουσιν τον [ιησουν]{.greek-abbr}[1:16]{.aside}

οτι κατηριθμημενος ην συν ημιν και ελαχεν τον κληρον της διακονιας ταυτης[1:17]{.aside}

ουτος μεν ουν εκτησατο χωριον εκ μισθου της αδικιας και [πρηνης]{.greek-omitted} [πρινης]{.greek-added} γενομενος ελακησεν μεσος και εξεχυθη παντα τα [σ]{.unclear}πλαγχνα αυτου[1:18]{.aside}

και γνωστον εγενετο πασιν τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} ωστε κληθηναι το χωριον εκεινο τη ιδια διαλεκ[τω]{.unclear} αυτων ακελδαμα τουτ εστιν χωριον αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω ψαλμων γενηθητω η επαυλις αυτου ερημος και μη εστω ο κατοικων εν αυτη και την επισκοπην αυτου λαβοι ετερος[1:20]{.aside}

δει ουν των συνελθοντων ημιν ανδρων εν παντ[ι]{.unclear} χρονω εν ω εισηλθεν και εξηλθεν εφ ημας ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βα[πτισ]{.unclear}ματος ιωαννου εως της ημερας ης ανεληφθη αφ ημων μαρτυρα της αναστασεως αυτου γεν[εσθαι]{.greek-supplied} συν ημιν ενα τουτων[1:22]{.aside}

και εστησαν δυο ιωσηφ τον καλουμενον [βαρσαβαν]{.greek-omitted} [βαρσαββαν]{.greek-added} ος επεκληθη ιουστος και ματθιαν[1:23]{.aside}

και προσευξαμενοι ειπον συ [κυριε]{.greek-abbr} καρδιογνωστα παντων αναδειξον ον εξελεξω εκ τουτων των δυο ενα[1:24]{.aside}

λαβειν τον κληρον της διακονιας ταυτης και αποστολης εξ ης παρεβη ιουδας πορευθηναι εις τον τοπον τον ιδιον[1:25]{.aside}

και εδωκαν κληρους αυτων και επεσεν ο κληρος επι ματθιαν και [συγκατεψηφισθη]{.greek-omitted} [συνκατεψηφισθη]{.greek-added} μετα των ενδεκα αποστολων[1:26]{.aside}

### Chapter 2

και εν τω συμπληρουσθαι την [η]{.greek-added} [ημεραν]{.greek-omitted} [μεραν]{.greek-added} της [πεντηκοστης]{.greek-omitted} [πεντικοστης]{.greek-added} ησαν απαντες ομοθυμαδον επι το αυτο[2:1]{.aside}

και εγενετο αφνω εκ του [ουρανου]{.greek-abbr} ηχος ωσπερ φερομενης πνοης βιαιας και επληρωσεν ολον τον οικον ου ησαν καθημενοι[2:2]{.aside}

και ωφθησαν αυτοις διαμεριζομεναι γλωσσαι ωσει πυρος εκαθισεν τε εφ ενα εκαστον αυτων[2:3]{.aside}

και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετεραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου αυτοις αποφθεγγεσθαι[2:4]{.aside}

ησαν δε εν [ιερουσαλημ]{.greek-omitted} [[ιλημ]{.greek-abbr}]{.greek-added} κατοικουντες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο τον [ουρανον]{.greek-abbr}[2:5]{.aside}

γενομενης δε της φωνης ταυτης συνηλθεν το πληθος και συνεχυθη οτι ηκουον εις εκα[στος]{.unclear} τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

εξισταντο δε [παντες]{.greek-omitted} και εθαυμαζον [λεγοντες]{.greek-omitted} προς αλληλους ουκ ιδου παντες ουτοι εισιν οι λαλουντες γαλιλαιοι[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η [εγεννηθημεν]{.greek-omitted} [εγενηθημεν]{.greek-added}[2:8]{.aside}

παρθοι και μηδοι και [ελαμιται]{.greek-omitted} [ελαμειται]{.greek-added} και οι κατοικουντες την μεσοποταμιαν ιουδαι[αν]{.greek-supplied} [τ]{.greek-supplied}[ε]{.unclear} και καππαδοκιαν [πον]{.greek-supplied}τον και την ασιαν[2:9]{.aside}

φρυγιαν τε και παμφυλιαν αιγυπτον και τα μερη της λιβυης της κατα [κυρηνην]{.greek-omitted} [κυρινην]{.greek-added} και οι επιδημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[ιουδαιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυτοι]{.greek-added} [κρητες]{.greek-omitted} [κρηταις]{.greek-added} και αραβες ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα [μεγαλεια]{.greek-omitted} [μεγαλια]{.greek-added} του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και διηπορουν αλλος προς αλλον λεγοντες τι αν θελοι τουτο ειναι[2:12]{.aside}

ετεροι δε χλευαζοντες ελεγον οτι γλευκους μεμεστωμενοι εισιν[2:13]{.aside}

σταθεις δε πετρος συν τοις ενδεκα επηρεν την φωνην αυτου και απεφθεγξατο αυτοις ανδρες ιουδ[α]{.unclear}ι[ο]{.unclear}ι και οι κατοικουντες [ιερουσαλημ]{.greek-abbr} απαντες τουτο υμιν γνωστον εστω και ενωτισασθε τα ρηματα μου[2:14]{.aside}

ου γαρ ως υμεις υπολαμβανετε ουτοι μεθυουσιν εστιν γαρ ωρα τριτη της ημερας[2:15]{.aside}

αλλα τουτο εστιν το ειρημενον δια του προφητου ιωηλ[2:16]{.aside}

και εσται εν ταις εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υιοι υμων και αι θυγατερες υμων και οι νεανισκοι υμων ορασεις οψονται και οι πρεσβυτεροι υμων ενυπνια ενυπνιασθησονται[2:17]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις εκχεω απο του [πνευματος]{.greek-abbr} μου και προφητευσουσιν[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω και σημεια επι της γης κατω αιμα και πυρ και ατμιδα καπνου[2:19]{.aside}

ο ηλιος μεταστραφησεται εις σκοτος και [η]{.greek-omitted} [ει]{.greek-added} σεληνη εις αιμα πριν [η]{.greek-omitted} [ελθειν]{.greek-omitted} την ημεραν [κυριου]{.greek-abbr} [ελθειν]{.greek-added} την μεγαλην και επιφανη[2:20]{.aside}

και εσται πας ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθησεται[2:21]{.aside}

ανδρες [ισραηλιται]{.greek-omitted} [ισραηλειται]{.greek-added} ακουσατε τους λογους τουτους [ιησουν]{.greek-abbr} τον ναζωραιον ανδρα απο του [θεου]{.greek-abbr} αποδεδειγμενον εις υμας [δυναμεσιν]{.greek-omitted} [δυναμεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και σημειοις οις εποιησεν δι αυτου ο [θεος]{.greek-abbr} εν μεσω υμων καθως και αυτοι οιδατε[2:22]{.aside}

τουτον τη ωρισμενη βουλη και προγνωσει του [θεου]{.greek-abbr} εκδοτον λαβοντες δια χειρων ανομων προσπηξαντες [ανειλετε]{.greek-omitted} [ανειλατε]{.greek-added}[2:23]{.aside}

ον ο [θεος]{.greek-abbr} ανεστησεν λυσας τας [ωδινας]{.greek-omitted} [οδυνας]{.greek-added} του θανατου καθοτι ουκ ην δυνατον κρατεισθαι αυτον υπ αυτου[2:24]{.aside}

[δαυιδ]{.greek-abbr} γαρ λεγει εις αυτον προωρωμην τον [κυριον]{.greek-abbr} ενωπιον μου δια παντος οτι εκ δεξιων μου εστιν ινα μη σαλευθω[2:25]{.aside}

δια τουτο [ευφρανθη]{.greek-omitted} [ηυφρανθη]{.greek-added} η καρδια μου και ηγαλλιασατο η γλωσσα μου ετι δε και η σαρξ μου κατασκηνωσει επ ελπιδι[2:26]{.aside}

οτι ουκ [εγκαταλειψεις]{.greek-omitted} [εγκαταληψεις]{.greek-added} την ψυχην μου εις [αδου]{.greek-omitted} [αδην]{.greek-added} ουδε δωσεις τον οσιον σου ιδειν διαφθοραν[2:27]{.aside}

εγνωρισας μοι οδους ζωης πληρωσεις με ευφροσυνης μετα του προσωπου σου[2:28]{.aside}

ανδρες αδελφοι εξον ειπειν μετα παρρησιας προς υμας περι του [πατριαρχου]{.greek-abbr} [δαυιδ]{.greek-abbr} οτι και ετελευτησεν και εταφη και το μνημα αυτου εστιν εν ημιν αχρι της ημερας ταυτης[2:29]{.aside}

προφητης ουν υπαρχων και ειδως οτι ορκω ωμοσεν αυτω ο [θεος]{.greek-abbr} εκ καρπου της οσφυος αυτου το κατα σαρκα αναστησειν τον [χριστον]{.greek-abbr} καθισαι επι του θρονου αυτου[2:30]{.aside}

[προιδων]{.greek-omitted} [προειδων]{.greek-added} ελαλησεν περι της αναστασεως του [χριστου]{.greek-abbr} οτι [ου]{.greek-omitted} [ουκ]{.greek-added} [κατελειφθη]{.greek-omitted} [εγκατεληφθη]{.greek-added} η ψυχη αυτου εις αδου ουδε η σαρξ αυτου ειδεν διαφθοραν[2:31]{.aside}

τουτον τον [ιησουν]{.greek-abbr} ανεστησεν ο [θεος]{.greek-abbr} ου παντες ημεις εσμεν μαρτυρες[2:32]{.aside}

τη δεξια ουν του [θεου]{.greek-abbr} υψωθεις την τε επαγγελιαν του αγιου [πνευματος]{.greek-abbr} λαβων παρα του [πατρος]{.greek-abbr} εξεχεεν τουτο ο νυν [υμ]{.greek-supplied}εις βλεπετε και ακουετε[2:33]{.aside}

ου γαρ [δαυιδ]{.greek-abbr} ανεβη εις [τους]{.greek-omitted} [τον]{.greek-added} [ουρανους]{.greek-omitted} [[ουρανον]{.greek-abbr}]{.greek-added} λεγει δε αυτος ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου[2:34]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[2:35]{.aside}

ασφαλως ουν γινωσκετω πας οικος [του]{.greek-added} [ισραηλ]{.greek-abbr} οτι και [κυριον]{.greek-abbr} [αυτον]{.greek-added} και [χριστον]{.greek-abbr} [αυτον]{.greek-omitted} ο [θεος]{.greek-abbr} εποιησεν τουτον τον [ιησουν]{.greek-abbr} ον υμεις [εσταυρωσατε]{.greek-abbr}[2:36]{.aside}

ακουσαντες δε [κατενυγησαν]{.greek-omitted} [κατηνυγησαν]{.greek-added} τη καρδια ειπον τε προς τον πετρον και τους λοιπους αποστολους τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} ανδρες αδελφοι[2:37]{.aside}

πετρος δε εφη προς αυτους μετανοησατε και βαπτισθητω εκαστος υμων επι τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εις αφεσιν αμαρτιων και ληψεσθε την δωρεαν του αγιου [πνευματος]{.greek-abbr}[2:38]{.aside}

υμιν γαρ εστιν η επαγγελια και τοις τεκνοις υμων και πασιν τοις εις μακραν οσους αν προσκαλεσηται [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων[2:39]{.aside}

ετεροις τε λογοις πλειοσιν διεμαρτυρετο και παρεκαλει λεγων σωθητε απο της γενεας της σκολιας ταυτης[2:40]{.aside}

οι μεν ουν ασμενως [αποδεξαμενοι]{.greek-omitted} [υποδεξαμενοι]{.greek-added} τον λογον αυτου εβαπτισθησαν και προσετεθησαν τη ημερα εκεινη ψυχαι ωσει τρισχιλιαι[2:41]{.aside}

ησαν δε προσκαρτερουντες τη διδαχη των αποστολων και τη κοινωνια και τη κλασει του αρτου και ταις προσευχαις[2:42]{.aside}

εγενετο δε παση ψυχη φοβος πολλα τε τερατα και σημεια δια των αποστολων [εγινετο]{.greek-omitted} [εγενετο]{.greek-added}[2:43]{.aside}

παντες δε οι πιστευοντες ησαν επι το αυτο και ειχον απαντα κοινα[2:44]{.aside}

και τα κτηματα και τας υπαρξεις επιπρασκον και διεμεριζον αυτα πασιν καθοτι αν τις χρειαν ειχεν[2:45]{.aside}

καθ ημεραν τε προσκαρτερουντες ομοθυμαδον εν τω ιερω κλωντες [τε]{.greek-omitted} κατ οικον αρτον μετελαμβανον τροφης εν αγαλλιασει και αφελοτητι καρδιας[2:46]{.aside}

αινουντες τον [θεον]{.greek-abbr} και εχοντες χαριν προς ολον τον [λαον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ο δε [κυριος]{.greek-abbr} προσετιθει τους σωζομενους καθ ημεραν τη εκκλησια[2:47]{.aside}

### Chapter 3

επι το αυτο δε πετρος και ιωαννης ανεβαινον εις το ιερον επι την ωραν της προσευχης την ενατην[3:1]{.aside}

και τις ανηρ χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων εβασταζετο ον ετιθουν καθ ημεραν προς την θυραν του ιερου την λεγομενην ωραιαν του αιτειν ελεημοσυνην παρα των εισπορευομενων εις το ιερον[3:2]{.aside}

ος ιδων πετρον και ιωαννην μελλοντας εισιεναι εις το ιερον ηρωτα ελεημοσυνην[3:3]{.aside}

ατενισας δε πετρος εις αυτον συν τω ιωαννη ειπεν βλεψον εις ημας[3:4]{.aside}

ο δε επειχεν αυτοις προσδοκων τι παρ αυτων λαβειν[3:5]{.aside}

ειπεν δε πετρος αργυριον και χρυσιον ουχ υπαρχει μοι ο δε εχω τουτο σοι διδωμι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[3:6]{.aside}

και πιασας αυτον της δεξιας χειρος ηγειρεν παραχρημα δε εστερεωθησαν αυτου αι βασεις και τα σφυρα[3:7]{.aside}

και εξαλλομενος εστη και περιεπατει και εισηλθεν συν αυτοις εις το ιερον περιπατων και αλλομενος και αινων τον [θεον]{.greek-abbr}[3:8]{.aside}

και ειδεν αυτον πας ο λαος περιπατουντα και αινουντα τον [θεον]{.greek-abbr}[3:9]{.aside}

επεγινωσκον τε αυτον οτι ουτος [ην]{.greek-omitted} [εστιν]{.greek-added} ο προς την ελεημοσυνην καθημενος επι τη ωραια πυλη του ιερου και επλησθησαν θαμβους και εκστασεως επι τω συμβεβηκοτι αυτω[3:10]{.aside}

κρατουντος δε του [ιαθεντος]{.greek-omitted} [ιαθεντου]{.greek-added} χωλου τον πετρον και ιωαννην συνεδραμεν [προς]{.unclear} [αυτους]{.greek-omitted} [[α]{.unclear}υτον]{.greek-added} πας ο λαος επ[ι]{.unclear} [τη]{.greek-supplied} [σ]{.greek-supplied}το[α]{.unclear} τη καλουμενη [σολομ]{.greek-supplied}ωντος εκθαμβοι[3:11]{.aside}

ιδων δε [[ο]{.greek-supplied}]{.greek-added} [πε]{.unclear}[τρος]{.unclear} [απ]{.unclear}εκρινατο προς [τ]{.greek-supplied}[ον]{.unclear} λα[ο]{.greek-supplied}ν ανδρε[ς]{.unclear} [ισραηλιται]{.greek-omitted} [ισ[ραη]{.unclear}λειται]{.greek-added} τι θαυμαζετε επι τουτω η ημιν τι ατενιζετε ως [ιδια]{.greek-omitted} [ηδια]{.greek-added} δυναμει η ευσεβεια πεποιηκοσιν του περιπατειν αυτον[3:12]{.aside}

ο [θεος]{.greek-abbr} αβρααμ και ισαακ και ιακωβ ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων εδοξασεν τον παιδα αυτου [ιησουν]{.greek-abbr} ον υμεις μεν παρεδωκατε και ηρνησασθε αυτον κατα προσωπον πιλατου κριναντος εκεινου απολυειν[3:13]{.aside}

υμεις δε τον αγιον και δικαιον ηρνησασθε και ητησασθε ανδρα φονεα χαρισθηναι υμιν[3:14]{.aside}

τον δε αρχηγον της ζωης απεκτεινατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων ου ημεις μαρτυρες εσμεν[3:15]{.aside}

και επι τη πιστει του ονοματος αυτου τουτον ον θεωρειτε και οιδατε εστερεωσεν το ονομα αυτου και η πιστις η δι αυτου εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[3:16]{.aside}

και νυν αδελφοι οιδα οτι κατα αγνοιαν επραξατε ωσπερ και οι αρχοντες υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α προκατηγγειλεν δια στοματος παντων των προφητων αυτου παθειν τον [χριστον]{.greek-abbr} επληρωσεν ουτως[3:18]{.aside}

μετανοησατε ουν και επιστρεψατε εις το εξαλειφθηναι υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσιν]{.greek-added} [καιροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και αποστειλη τον προκεχειρισμενον υμιν [[ιησουν]{.greek-abbr}]{.greek-added} [χριστον]{.greek-abbr} [ιησουν]{.greek-omitted}[3:20]{.aside}

ον δει [ουρανον]{.greek-abbr} μεν δεξασθαι αχρι χρονων αποκαταστασεως παντων ων ελαλησεν ο [θεος]{.greek-abbr} δια στοματος παντων των αγιων αυτου προφητων απ αιωνος[3:21]{.aside}

μωσης μεν [γαρ]{.greek-omitted} προς τους πατερας ειπεν οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε αυτου ακουσεσθε κατα παντα οσα αν [λαληση]{.greek-omitted} [λαλησει]{.greek-added} προς υμας[3:22]{.aside}

εσται δε πασα ψυχη ητις εαν μη ακουση του προφητου εκεινου εξολοθρευθησεται εκ του λαου[3:23]{.aside}

και παντες δε οι προφηται απο σαμουηλ και των καθεξης οσοι ελαλησαν και κατηγγειλαν τας ημερας ταυτας[3:24]{.aside}

υμεις εστε [οι]{.greek-added} υιοι των προφητων και της διαθηκης ης διεθετο ο [θεος]{.greek-abbr} προς τους [πατερας]{.greek-abbr} ημων λεγων προς αβρααμ και εν τω σπερμα[τι]{.unclear} σ[ου]{.unclear} ενευλογηθησονται πασαι αι πατριαι της γης[3:25]{.aside}

υμιν πρωτον ο [θεος]{.greek-abbr} αναστησας τον παιδα αυτου [ιησουν]{.greek-omitted} απεστειλεν αυτον ευλογουντα [υμας]{.greek-omitted} [ημας]{.greek-added} εν τω αποστρεφειν εκαστον απο των πονηριων υμων[3:26]{.aside}

### Chapter 4

λαλουντων δε αυτων προς τον λαον επεστησαν αυτοις οι ιερεις και ο στρατηγος του ιερου και οι σαδδουκαιοι[4:1]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον λαον και [καταγγελλειν]{.greek-omitted} [καταγγελειν]{.greek-added} εν τω [ιησου]{.greek-abbr} την αναστασιν των νεκρων[4:2]{.aside}

και [επεβαλον]{.greek-omitted} [επεβαλεν]{.greek-added} αυτοις τας χειρας και εθεντο εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι δε των ακουσαντων τον λογον επιστευσαν και εγενηθη ο αριθμος των ανδρων ωσει χιλιαδες πεντε[4:4]{.aside}

εγενετο δε επι την αυριον συναχθηναι αυτων τους αρχοντας και πρεσβυτερους και γραμματεις [εις]{.greek-omitted} [εν]{.greek-added} [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και ανναν τον αρχιερεα και καιαφαν και ιωαννην και αλεξανδρον και οσοι ησαν εκ γενους αρχιερατικου[4:6]{.aside}

και στησαντες αυτους εν μεσω επυνθανοντο εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος [πλησθεις]{.greek-omitted} [πλεισθεις]{.greek-added} [πνευματος]{.greek-abbr} αγιου ειπεν προς αυτους αρχοντες του λαου και πρεσβυτεροι του [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα επι ευεργεσια [ανθρωπου]{.greek-abbr} [ασθενους]{.greek-omitted} [ασθε]{.greek-added} [νους]{.greek-added} εν τινι ουτος [σεσωσται]{.greek-omitted} [σεσωται]{.greek-added}[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω [ισραηλ]{.greek-abbr} οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις [εσταυρωσατε]{.greek-omitted} [[εστρωσατε]{.greek-abbr}]{.greek-added} ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν τουτω ουτος [παρεστηκεν]{.greek-omitted} [παρεστικεν]{.greek-added} ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ [υμων]{.greek-omitted} [ημων]{.greek-added} των οικοδομουντων ο γενομενος εις κεφαλην γωνιας[4:11]{.aside}

και ουκ εστιν εν αλλω ουδενι η [σωτηρια]{.greek-abbr} ουτε γαρ ονομα εστιν ετερον το δεδομενον εν [ανθρωποις]{.greek-abbr} εν ω δει σωθηναι ημας[4:12]{.aside}

θεωρουντες δε την του πετρου παρρησιαν και ιωαννου και καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι εισιν και ιδιωται εθαυμαζον επεγινωσκον τε αυτους οτι [ησαν]{.greek-added} συν τω [ιησου]{.greek-abbr} [ησαν]{.greek-omitted}[4:13]{.aside}

τον δε [ανθρωπον]{.greek-abbr} βλεποντες συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου απελθειν συνεβαλλον προς αλληλους[4:15]{.aside}

λεγοντες τι ποιησομεν τοις [ανθρωποις]{.greek-abbr} τουτοις οτι μεν γαρ γνωστον σημειον γεγονεν δι αυτων πασιν τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} φανερον και ου δυναμεθα αρνησασθαι[4:16]{.aside}

αλλ ινα μη επι πλειον [διανεμηθη]{.greek-omitted} [διανιμηθει]{.greek-added} εις τον λαον απειλη απειλησομεθα αυτοις μηκετι λαλειν επι τω ονοματι [τουτω]{.greek-omitted} [τουτο]{.greek-added} μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και καλεσαντες αυτους παρηγγειλαν αυτοις το καθολου μη φθεγγεσθαι μηδε διδασκειν επι τω ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

ο δε πετρος και ιωαννης αποκριθεντες προς αυτους ειπον ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ ημεις α [ειδομεν]{.greek-omitted} [ειδωμεν]{.greek-added} και ηκουσαμεν μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως κολασονται αυτους δια τον λαον οτι παντες εδοξαζον [τον]{.greek-omitted} [θεον]{.greek-omitted} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων τεσσαρακοντα ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε ηλθον προς τους ιδιους και απηγγειλαν οσα προς αυτους οι αρχιερεις και οι πρεσβυτεροι ειπον[4:23]{.aside}

οι δε ακουσαντες ομοθυμαδον [ηραν]{.greek-omitted} [η]{.greek-added} φωνην προς τον [θεον]{.greek-abbr} και [ειπον]{.greek-omitted} [ειπαν]{.greek-added} δεσποτα συ ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην [και]{.greek-omitted} την θαλασσαν και παντα τα εν αυτοις[4:24]{.aside}

ο δια στοματος [δαυιδ]{.greek-abbr} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

παρεστησαν οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας επι τον αγιον παιδα σου [ιησουν]{.greek-abbr} ον [εχρισας]{.greek-omitted} [εχρησας]{.greek-added} ηρωδης τε και ποντιος πιλατος συν εθνεσιν και λαοις [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η βουλη σου [προωρισεν]{.greek-omitted} [προωρησεν]{.greek-added} γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} [επιδε]{.greek-omitted} [εφιδε]{.greek-added} επι τας απειλας αυτων και δος τοις δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την χειρα σου εκτεινειν σε εις ιασιν και σημεια και τερατα γινεσθαι δια του ονοματος του αγιου παιδος σου [ιησου]{.greek-abbr}[4:30]{.aside}

και δεηθεντων αυτων εσαλευθη ο τοπος εν ω ησαν συνηγμενοι και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ελαλουν τον λογον του [θεου]{.greek-abbr} μετα παρρησιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και ουδε εις τι των υπαρχοντων αυτων [ελεγεν]{.greek-omitted} [ελεγον]{.greek-added} ιδιον ειναι αλλ ην αυτοις απαντα κοινα[4:32]{.aside}

και μεγαλη δυναμει απεδιδουν το μαρτυριον οι αποστολοι της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} χαρις τε μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις υπηρχεν εν αυτοις οσοι γαρ κτητορες χωριων η οικιων υπηρχον πωλουντες εφερον τας τιμας των πιπρασκομενων[4:34]{.aside}

και ετιθουν παρα τους ποδας των αποστολων διεδιδοτο δε εκαστω [καθοτι]{.greek-omitted} [καθο]{.greek-added} [αν]{.greek-omitted} τις χρειαν ειχεν[4:35]{.aside}

ιωσης δε ο επικληθεις βαρναβας απο των αποστολων ο εστιν μεθερμηνευομενον [υιος]{.greek-abbr} παρακλησεως λευιτης κυπριος τω γενει[4:36]{.aside}

υπαρχοντος αυτω αγρου πωλησας ηνεγκεν το χρημα και εθηκεν παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις ανανιας ονοματι συν σαπφειρη τη γυναικι αυτου επωλησεν κτημα[5:1]{.aside}

και ενοσφισατο απο της τιμης συνειδυιας και της γυναικος αυτου και ενεγκας μερος τι παρα τους ποδας των αποστολων [εθηκεν]{.greek-omitted} [εθηκον]{.greek-added}[5:2]{.aside}

ειπεν δε πετρος ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι σε απο της τιμης του χωριου[5:3]{.aside}

ουχι μενον σοι εμενεν και πραθεν εν τη ση εξουσια υπηρχεν τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε ο ανανιας τους λογους τουτους πεσων εξεψυξεν και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι νεωτεροι συνεστειλαν αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων διαστημα και η γυνη αυτου μη [ειδυια]{.greek-omitted} [ιδυια]{.greek-added} το [γεγονος]{.greek-omitted} [γεγονως]{.greek-added} εισηλθεν[5:7]{.aside}

απεκριθη δε αυτη ο πετρος ειπε μοι ει τοσουτου το χωριον απεδοσθε η δε ειπεν ναι τοσουτου[5:8]{.aside}

ο δε πετρος ειπεν προς αυτην τι οτι συνεφωνηθη υμιν πειρασαι [το]{.unclear} [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ιδου οι ποδες [των]{.unclear} [θ]{.unclear}αψαντων τον [αν]{.unclear}δρα σου επι τη θυρα [και]{.unclear} εξοισουσιν σε[5:9]{.aside}

επεσεν [δ]{.unclear}ε παραχρημα παρα τους ποδας αυτου και εξεψυξεν εισελθοντες δε οι νεανισκοι ευρον αυτην νεκραν και εξενεγκαντες εθαψαν προς τον ανδρα αυτης[5:10]{.aside}

και εγενετο φοβος μεγας εφ ολην την εκκλησιαν και επι παντας τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων [εγινετο]{.greek-omitted} [εγενετο]{.greek-added} σημεια και τερατα [μεγαλα]{.greek-added} εν τω λαω πολλα και ησαν ομοθυμαδον απαντες εν τη στοα [σολομωντος]{.greek-omitted} [σολομωνος]{.greek-added}[5:12]{.aside}

των δε λοιπων ουδεις ετολμα κολλασθαι αυτοις αλλ εμεγαλυνεν αυτους ο λαος[5:13]{.aside}

μαλλον δε [προσετιθεντο]{.greek-omitted} [προσετιθοντο]{.greek-added} πιστευοντες τω [κυριω]{.greek-abbr} πληθη ανδρων τε και γυναικων[5:14]{.aside}

ωστε κατα τας πλατειας εκφερειν τους ασθενεις και τιθεναι επι κλινων και [κραββατων]{.greek-omitted} [κραβατων]{.greek-added} ινα ερχομενου πετρου καν η σκια επισκιαση τινι αυτων[5:15]{.aside}

συνηρχετο δε και το πληθος των περιξ πολεων [εις]{.greek-omitted} [ιερουσαλημ]{.greek-abbr} φεροντες ασθενεις και οχλουμενους υπο [πνευματων]{.greek-abbr} ακαθαρτων οιτινες εθεραπευοντο απαντες[5:16]{.aside}

αναστας δε ο αρχιερευς και πα[ν]{.unclear}τες οι συν αυτω η ουσα αιρεσις των σαδδουκαιων επλησθησαν ζηλου[5:17]{.aside}

και [ε]{.greek-added} [επεβαλον]{.greek-omitted} [πεβαλον]{.greek-added} τας χειρας αυτων επι τους αποστολους και εθεντο αυτους εν τηρησει δημοσια[5:18]{.aside}

αγγελος δε [κυριου]{.greek-abbr} δια [της]{.greek-omitted} νυκτος ηνοιξεν τας θυρας της φυλακης εξαγαγων τε αυτους ειπεν[5:19]{.aside}

πορευεσθε και σταθεντες λαλειτε εν τω ιερω τω λαω παντα τα ρηματα της ζωης ταυτης[5:20]{.aside}

ακουσαντες δε εισηλθον υπο τον ορθρον εις το ιερον και εδιδασκον παραγενομενος δε ο αρχιερευς και οι συν αυτω συνεκαλεσαν το συνεδριον και πασαν την γερουσιαν των υιων [ισραηλ]{.greek-abbr} και απεστειλαν εις το [δεσμωτηριον]{.greek-omitted} [δεσμοτηριον]{.greek-added} αχθηναι αυτους[5:21]{.aside}

οι δε υπηρεται παραγενομενοι ουχ ευρον αυτους εν τη φυλακη αναστρεψαντες δε απηγγειλαν[5:22]{.aside}

λεγοντες οτι το μεν [δεσμωτηριον]{.greek-omitted} [δεσμοτηριον]{.greek-added} ευρομεν κεκλεισμενον εν παση ασφαλεια και τους φυλακας εστωτας προ των θυρων ανοιξαντες δε εσω ουδενα ευρομεν[5:23]{.aside}

ως δε ηκουσαν τους λογους τουτους ο τε ιερευς και ο στρατηγος του ιερου και οι αρχιερεις διηπορουν περι αυτων τι αν γενοιτο τουτο[5:24]{.aside}

παραγενομενος δε τις απηγγειλεν αυτοις οτι ιδου οι ανδρες ους εθεσθε εν τη φυλακη εισιν εν τω ιερω εστωτες και διδασκοντες τον λαον[5:25]{.aside}

τοτε απελθων ο στρατηγος συν τοις υπηρεταις ηγαγεν αυτους ου μετα βιας εφοβουντο γαρ τον λαον ινα μη λιθασθωσιν[5:26]{.aside}

αγαγοντες δε αυτους εστησαν εν τω συνεδριω και επηρωτησεν αυτους ο αρχιερευς[5:27]{.aside}

λεγων ου [παραγγελια]{.greek-omitted} [παραγγελιαν]{.greek-added} παρηγγειλαμεν υμιν μη διδασκειν επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι [τουτω]{.greek-omitted} [τουτο]{.greek-added} και ιδου πεπληρωκατε την [ιερουσαλημ]{.greek-abbr} της διδαχης υμων και βουλεσθε επαγαγειν εφ ημας το αιμα του [ανθρωπου]{.greek-abbr} τουτου[5:28]{.aside}

αποκριθεις δε πετρος και οι αποστολοι ειπον πειθαρχειν δει [θεω]{.greek-abbr} μαλλον η [ανθρωποις]{.greek-abbr}[5:29]{.aside}

ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων ηγειρεν [ιησουν]{.greek-abbr} ον υμεις [διεχειρισασθε]{.greek-omitted} [διεχειρησασθε]{.greek-added} κρεμασαντες επι ξυλου[5:30]{.aside}

τουτον ο [θεος]{.greek-abbr} αρχηγον και [σωτηρα]{.greek-abbr} υψωσεν τη δεξια αυτου δουναι μετανοιαν τω [ισραηλ]{.greek-abbr} και αφεσιν αμαρτιων[5:31]{.aside}

και ημεις εσμεν αυτου μαρτυρες των ρηματων τουτων και το [πνευμα]{.greek-abbr} δε το αγιον ο [εδωκεν]{.greek-omitted} [εδω]{.greek-added} [κεν]{.greek-added} ο [θεος]{.greek-abbr} τοις πειθαρχουσιν αυτω[5:32]{.aside}

οι δε [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} διεπριοντο και εβουλευοντο [του]{.greek-added} ανελειν αυτους[5:33]{.aside}

αναστας δε τις εν τω συνεδριω φαρισαιος ονοματι γαμαλιηλ νομοδιδασκαλος τιμιος παντι τω λαω εκελευσεν εξω βραχυ τι τους αποστολους ποιησαι[5:34]{.aside}

ειπεν τε προς αυτους ανδρες ισραηλιται προσεχετε εαυτοις επι τοις [ανθρωποις]{.greek-abbr} τουτοις τι μελλετε πρασσειν[5:35]{.aside}

προ γαρ τουτων των ημερων ανεστη θευδας λεγων ειναι τινα εαυτον ω [προσεκληθη]{.greek-omitted} [προσεκολληθη]{.greek-added} αριθμος ανδρων ωσει τετρακοσιων ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις ουδεν[5:36]{.aside}

μετα [δε]{.greek-added} τουτον ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της απογραφης και απεστησεν λαον ικανον οπισω αυτου κακεινος απωλετο και παντες οσοι επειθοντο αυτω διεσκορπισθησαν[5:37]{.aside}

και τα νυν λεγω υμιν [αποστητε]{.greek-omitted} [αποστειτε]{.greek-added} απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε αυτους οτι εαν η εξ [ανθρωπων]{.greek-abbr} η βουλη η το εργον τουτο καταλυθησεται[5:38]{.aside}

ει δε εκ [θεου]{.greek-abbr} εστιν ου [δυνασθε]{.greek-omitted} [δυνησεσθε]{.greek-added} καταλυσαι αυτο μηποτε και θεομαχοι ευρεθητε [επεισθησαν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added}[5:39]{.aside}

[επεισθησαν]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} και προσκαλεσαμενοι τους αποστολους δειραντες παρηγγειλαν μη λαλειν επι τω ονοματι του [ιησου]{.greek-abbr} και απελυσαν αυτους[5:40]{.aside}

οι μεν ουν επορευοντο χαιροντες απο προσωπου του συνεδριου οτι υπερ του ονοματος του [ιησου]{.greek-omitted} [[χριστου]{.greek-abbr}]{.greek-added} κατηξιωθησαν ατιμασθηναι[5:41]{.aside}

πασαν τε ημεραν εν τω ιερω και κατ οικον ουκ επαυοντο διδασκοντες και ευαγγελιζομενοι [ιησουν]{.greek-abbr} τον [χριστον]{.greek-abbr}[5:42]{.aside}

### Chapter 6

εν δε ταις ημεραις ταυταις πληθυνοντων των μαθητων εγενετο γογγυσμος των ελληνιστων προς τους εβραιους οτι παρεθεωρουντο εν τη διακονια [αι]{.greek-added} [χειραι]{.greek-added} [αυτων]{.greek-added} τη καθημερινη [αι]{.greek-omitted} [χηραι]{.greek-omitted} [αυτων]{.greek-omitted}[6:1]{.aside}

προσκαλεσαμενοι δε οι δωδεκα το πληθος των μαθητων ειπον ουκ αρεστον εστιν ημας καταλειψαντας τον λογον του [θεου]{.greek-abbr} διακονειν τραπεζαις[6:2]{.aside}

επισκεψασθε ουν αδελφοι ανδρας εξ υμων μαρτυρουμενους επτα πληρεις [πνευματος]{.greek-abbr} αγιου και σοφιας ους καταστησωμεν επι της χρειας ταυτης[6:3]{.aside}

ημεις δε τη προσευχη και τη [διακονια]{.greek-omitted} [δια]{.greek-added} [νια]{.greek-added} του λογου [προσκαρτερησομεν]{.greek-omitted} [προσκαρτερησωμεν]{.greek-added}[6:4]{.aside}

και ηρεσεν ο λογος ενωπιον παντος του πληθους και εξελεξαντο στεφανον ανδρα [πληρης]{.greek-omitted} [πληρεις]{.greek-added} πιστεως και [πνευματος]{.greek-abbr} αγιου και φιλιππον και προχορον και νικανορα και [τιμωνα]{.greek-omitted} [τιμονα]{.greek-added} και παρμεναν και νικολαον προσηλυτον αντιοχεα[6:5]{.aside}

ους εστησαν ενωπιον των αποστολων και προσευξαμενοι επεθηκαν αυτοις τας χειρας[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} ηυξανεν και επληθυνετο ο αριθμος των μαθητων εν [ιερουσαλημ]{.greek-abbr} σφοδρα πολυς τε οχλος των ιερεων υπηκουον τη πιστει[6:7]{.aside}

στεφανος δε [πληρης]{.greek-omitted} [πληρεις]{.greek-added} [πιστεως]{.greek-omitted} [χαριτος]{.greek-added} και δυναμεως εποιει τερατα και σημεια μεγαλα εν τω λαω [δια]{.greek-added} [του]{.greek-added} [ονοματος]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added}[6:8]{.aside}

ανεστησαν δε τινες των εκ της συναγωγης [της]{.greek-omitted} [των]{.greek-added} [λεγομενης]{.greek-omitted} [λεγομενων]{.greek-added} λιβερτινων και [κυρηναιων]{.greek-omitted} [κυριναιων]{.greek-added} [και]{.greek-omitted} [αλεξανδρεων]{.greek-omitted} και των απο κιλικιας και ασιας συζητουντες τω στεφανω[6:9]{.aside}

και ουκ ισχυον αντιστηναι τη σοφια και τω [πνευματι]{.greek-abbr} ω ελαλει[6:10]{.aside}

τοτε υπεβαλον ανδρας λεγοντας οτι ακηκοαμεν αυτου λαλουντος ρηματα βλασφημα εις [μωσην]{.greek-omitted} [μωυσην]{.greek-added} και τον [θεον]{.greek-abbr}[6:11]{.aside}

[συνεκινησαν]{.greek-omitted} [συνεκεινησαν]{.greek-added} τε τον λαον και τους πρεσβυτερους και τους γραμματεις και επισταντες συνηρπασαν αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας ψευδεις λεγοντας ο [ανθρωπος]{.greek-abbr} ουτος ου παυεται [ρηματα]{.greek-omitted} [βλασφημα]{.greek-omitted} [λαλων]{.greek-omitted} κατα του τοπου του αγιου [τουτου]{.greek-added} και του νομου [ρηματα]{.greek-added} [λαλων]{.greek-added} [βλασφημα]{.greek-added}[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος καταλυσει τον τοπον τουτον και αλλαξει τα [εθη]{.greek-omitted} [εθει]{.greek-added} α παρεδωκεν ημιν μωσης[6:14]{.aside}

και ατενισαντες εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω [ειδον]{.greek-omitted} [ιδον]{.greek-added} το προσωπον αυτου ωσει προσωπον αγγελου[6:15]{.aside}

### Chapter 7

ειπεν δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} ημων αβρααμ οντι εν τη μεσοποταμια πριν η κατοικησαι αυτον εν χαρραν[7:2]{.aside}

και ειπεν προς αυτον εξελθε εκ της γης σου και εκ της [συγγενειας]{.greek-omitted} [συγγενιας]{.greek-added} σου και δευρο εις [την]{.greek-added} γην ην αν σοι δειξω[7:3]{.aside}

τοτε εξελθων εκ γης χαλδαιων κατωκησεν εν χαρραν κακειθεν μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μετωκησεν]{.greek-added} αυτον εις την γην ταυτην εις ην υμεις νυν κατοικειτε[7:4]{.aside}

και ουκ [εδωκεν]{.greek-omitted} [εδωκαν]{.greek-added} αυτω κληρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι [αυτω]{.greek-omitted} [αυτην]{.greek-added} εις κατασχεσιν [αυτην]{.greek-omitted} [αυτω]{.greek-added} και τω σπερματι αυτου μετ αυτον ουκ [οντος]{.greek-omitted} [οντως]{.greek-added} αυτω τεκνου[7:5]{.aside}

ελαλησεν δε [ουτως]{.greek-omitted} [αυτω]{.greek-added} ο [θεος]{.greek-abbr} οτι εσται το σπερμα αυτου παροικον εν γη αλλοτρια και δουλωσουσιν αυτο και κακωσουσιν ετη [τετρακοσια]{.greek-omitted} [τριακοσια]{.greek-added}[7:6]{.aside}

και το εθνος ω εαν δουλευσωσιν κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και λατρευσουσιν μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και ουτως εγεννησεν τον ισαακ και περιετεμεν αυτον τη ημερα [τη]{.greek-omitted} ογδοη και [ο]{.greek-omitted} ισαακ τον ιακωβ και [ο]{.greek-omitted} ιακωβ τους δωδεκα [πατριαρχας]{.greek-abbr}[7:8]{.aside}

και οι [πατριαρχαι]{.greek-abbr} ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και [εξειλετο]{.greek-omitted} [εξιλατο]{.greek-added} αυτον εκ πασων των θλιψεων αυτου και εδωκεν αυτω χαριν και σοφιαν [εναντιον]{.greek-omitted} [εναντι]{.greek-added} φαραω βασιλεως αιγυπτου και κατεστησεν αυτον ηγουμενον επ αιγυπτον και ολον τον οικον αυτου[7:10]{.aside}

ηλθεν δε λιμος εφ ολην την γην αιγυπτου και χανααν και θλιψις μεγαλη και ουχ ευρισκον χορτασματα [οι]{.greek-omitted} [πατερες]{.greek-omitted} [ημων]{.greek-omitted}[7:11]{.aside}

ακουσας δε ιακωβ οντα σιτα εν αιγυπτω εξαπεστειλεν τους [πατερας]{.greek-abbr} ημων πρωτον[7:12]{.aside}

και εν τω δευτερω ανεγνωρισθη ιωσηφ τοις αδελφοις αυτου και φανερον εγενετο τω φαραω το γενος του ιωσηφ[7:13]{.aside}

αποστειλας δε ιωσηφ μετεκαλεσατο τον [πατερα]{.greek-abbr} αυτου ιακωβ και πασαν την συγγενειαν εν [ψυχαις]{.greek-omitted} εβδομηκοντα πεντε [ψυχαις]{.greek-added}[7:14]{.aside}

κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν αυτος και οι [πατερες]{.greek-abbr} ημων[7:15]{.aside}

και μετετεθησαν εις συχεμ και ετεθησαν εν τω μνηματι ο ωνησατο αβρααμ τιμης αργυριου παρα των υιων εμμορ του συχεμ[7:16]{.aside}

καθως δε ηγγιζεν [ο]{.greek-omitted} [χρονος]{.greek-omitted} της επαγγελιας ης ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος ος ουκ [ηδει]{.greek-omitted} [ειδει]{.greek-added} τον ιωσηφ[7:18]{.aside}

ουτος κατασοφισαμενος το γενος ημων εκακωσεν τους [πατερας]{.greek-abbr} ημων του ποιειν εκθετα τα βρεφη αυτων εις το μη ζωογονεισθαι[7:19]{.aside}

εν ω καιρω εγεννηθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ην αστειος τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr} [αυτου]{.greek-added}[7:20]{.aside}

εκτεθεντα δε αυτον [ανειλετο]{.greek-omitted} [ανηλατο]{.greek-added} η θυγατηρ φαραω και ανεθρεψατο αυτον εαυτη εις υιον[7:21]{.aside}

και επαιδευθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σοφια αιγυπτιων ην δε δυνατος εν λογοις και [εργοις]{.greek-omitted} [ενεργοις]{.greek-added}[7:22]{.aside}

ως δε [επληρουτο]{.greek-omitted} [επληρουντο]{.greek-added} αυτω τεσσαρακονταετης χρονος ανεβη επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον ημυνατο και εποιησεν εκδικησιν τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

ενομιζεν δε συνιεναι τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις [σωτηριαν]{.greek-abbr} οι δε ου συνηκαν[7:25]{.aside}

τη τε επιουση ημερα ωφθη αυτοις μαχομενοις και [συνηλασεν]{.greek-omitted} [συνηλλασσεν]{.greek-added} αυτους εις ειρηνην ειπων [α]{.greek-added} ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} αδικειτε αλληλους[7:26]{.aside}

ο δε [αδικων]{.greek-omitted} [αδικον]{.greek-added} τον πλησιον απωσατο αυτον ειπων τις σε κατεστησεν αρχοντα και δικαστην εφ [ημας]{.greek-omitted} [ημων]{.greek-added}[7:27]{.aside}

μη ανελειν με συ θελεις ον τροπον ανειλες χθες τον αιγυπτιον[7:28]{.aside}

εφυγεν δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων τεσσαρακοντα ωφθη αυτω εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-abbr} εν φλογι πυρος βατου[7:30]{.aside}

ο δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [εθαυμασεν]{.greek-added} ιδων [εθαυμαζεν]{.greek-omitted} το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} σου ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ εντρομος δε γενομενος [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουκ ετολμα κατανοησαι[7:32]{.aside}

ειπεν δε αυτω ο [κυριος]{.greek-abbr} λυσον το υποδημα [εκ]{.greek-added} των ποδων σου ο γαρ τοπος εν ω εστηκας γη αγια εστιν[7:33]{.aside}

ιδων [ειδον]{.greek-omitted} [ιδον]{.greek-added} την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και κατεβην εξελεσθαι αυτους και νυν δευρο αποστελω σε εις αιγυπτον[7:34]{.aside}

τουτον τον [μωσην]{.greek-omitted} [μωυσην]{.greek-added} ον ηρνησαντο ειποντες τις σε κατεστησεν αρχοντα και δικαστην [εφ]{.greek-added} [ημων]{.greek-added} τουτον ο [θεος]{.greek-abbr} αρχοντα και λυτρωτην [απεστειλεν]{.greek-omitted} [απεσταλκεν]{.greek-added} [εν]{.greek-omitted} [συν]{.greek-added} χειρι αγγελου του [οφθεντος]{.greek-omitted} [ωφθεντος]{.greek-added} αυτω εν τη βατω[7:35]{.aside}

ουτος εξηγαγεν αυτους ποιησας τερατα και σημεια εν γη αιγυπτω και εν ερυθρα θαλασση και εν τη ερημω ετη τεσσαρακοντα[7:36]{.aside}

ουτος εστιν ο [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε [αυτου]{.greek-added} [ακουσεσθε]{.greek-added}[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο [λογον]{.greek-omitted} [λογια]{.greek-added} ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθελησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων [αλλ]{.greek-omitted} [αλλα]{.greek-added} απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

ειποντες τω ααρων ποιησον ημιν θεους οι προπορευσονται ημων ο γαρ [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις εκειναις και ανηγαγον θυσιαν τω ειδωλω και ευφραινοντο εν τοις εργοις των χειρων αυτων[7:41]{.aside}

εστρεψεν δε ο [θεος]{.greek-abbr} και παρεδωκεν αυτους λατρευειν τη στρατια του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη σφαγια και θυσιας προσηνεγκατε μοι ετη τεσσαρακοντα εν τη ερημω οικος [ισραηλ]{.greek-abbr}[7:42]{.aside}

και ανελαβετε την σκηνην [του]{.greek-omitted} μολοχ και το αστρον του [θεου]{.greek-abbr} υμων [ρεμφαν]{.greek-omitted} [ρεφαν]{.greek-added} τους τυπους ους εποιησατε προσκυνειν αυτοις και μετοικιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου ην [εν]{.greek-added} τοις πατρασιν [ημων]{.greek-omitted} εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωυση]{.greek-added} ποιησαι αυτην κατα τον τυπον ον εωρακει[7:44]{.aside}

ην και εισηγαγον διαδεξαμενοι οι [πατερες]{.greek-abbr} ημων μετα [ιησου]{.greek-abbr} εν τη κατασχεσει των εθνων ων [εξωσεν]{.greek-omitted} [εξεωσεν]{.greek-added} ο [θεος]{.greek-abbr} απο προσωπου των [πατερων]{.greek-abbr} ημων εως των ημερων [δαυιδ]{.greek-abbr}[7:45]{.aside}

ος ευρεν χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν αυτω οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις [κατ]{.greek-added} [οικει]{.greek-added} ναοις [κατοικει]{.greek-omitted} καθως ο προφητης λεγει[7:48]{.aside}

ο [ουρανος]{.greek-abbr} μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον [οικοδομησετε]{.greek-omitted} [ωκοδομησεται]{.greek-added} μοι λεγει [κυριος]{.greek-abbr} η τις τοπος της καταπαυσεως μου[7:49]{.aside}

ουχι η χειρ μου εποιησεν ταυτα παντα[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια και τοις ωσιν υμεις αει τω [πνευματι]{.greek-abbr} τω αγιω αντιπιπτετε ως οι [πατερες]{.greek-abbr} υμων και υμεις[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι [πατερες]{.greek-abbr} υμων και [απεκτειναν]{.greek-omitted} [απεκτηναν]{.greek-added} τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις προδοται και φονεις [γεγενησθε]{.greek-omitted} [εγενεσθε]{.greek-added}[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

ακουοντες δε ταυτα διεπριοντο ταις καρδιαις αυτων και εβρυχον τους οδοντας επ αυτον[7:54]{.aside}

υπαρχων δε [πληρης]{.greek-omitted} [πληρεις]{.greek-added} [πνευματος]{.greek-abbr} αγιου ατενισας εις τον [ουρανον]{.greek-abbr} ειδεν δοξαν [θεου]{.greek-abbr} και [ιησουν]{.greek-abbr} εστωτα εκ δεξιων του [θεου]{.greek-abbr}[7:55]{.aside}

και ειπεν ιδου θεωρω τους [ουρανους]{.greek-abbr} ανεωγμενους και [το]{.unclear}ν [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη [συνεσχον]{.greek-omitted} [συνεσχων]{.greek-added} τα ωτα αυτων και ωρμησαν ομοθυμαδον επ αυτον[7:57]{.aside}

και εκβαλοντες [αυτον]{.greek-added} εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τα ιματια [αυτων]{.greek-added} παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} δεξαι το [πνευμα]{.greek-abbr} μου[7:59]{.aside}

θεις δε τα [γονατα]{.greek-omitted} [γωνατα]{.greek-added} εκραξεν φωνη μεγαλη [κυριε]{.greek-abbr} μη στησης αυτοις την αμαρτιαν ταυτην και τουτο ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

σαυλος δε ην συνευδοκων τη αναιρεσει αυτου εγενετο δε εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις [και]{.greek-added} παντες [δε]{.greek-omitted} διεσπαρησαν κατα τας χωρας της ιουδαιας και [σαμαρειας]{.greek-omitted} [σαμαριας]{.greek-added} πλην των αποστολων[8:1]{.aside}

[συνεκομισαν]{.greek-omitted} [συνεκομησαν]{.greek-added} δε τον στεφανον ανδρες ευλαβεις και [εποιησαντο]{.greek-omitted} [εποιησαν]{.greek-added} κοπετον μεγαν επ αυτω[8:2]{.aside}

σαυλος δε ελυμαινετο την εκκλησιαν κατα τους οικους εισπορευομενος συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπαρεντες διηλθον ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος δε κατελθων εις πολιν της [σαμαρειας]{.greek-omitted} [σαμαριας]{.greek-added} εκηρυσσεν αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον τε οι οχλοι τοις λεγομενοις υπο του φιλιππου ομοθυμαδον εν τω ακουειν αυτους και βλεπειν τα σημεια α εποιει[8:6]{.aside}

πολλων γαρ των εχοντων [πνευματα]{.greek-abbr} ακαθαρτα βοωντα φωνη μεγαλη [εξηρχετο]{.greek-omitted} [εξηρχοντο]{.greek-added} πολλοι δε [και]{.greek-added} παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

και εγενετο χαρα μεγαλη εν τη πολει εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι σιμων προυπηρχεν εν τη πολει μαγευων και εξιστων το εθνος της [σαμαρειας]{.greek-omitted} [σαμαριας]{.greek-added} λεγων ειναι τινα εαυτον μεγαν[8:9]{.aside}

ω προσειχον [παντες]{.greek-added} απο μικρου εως μεγαλου λεγοντες ουτος εστιν η δυναμις του [θεου]{.greek-abbr} η [καλουμενη]{.greek-added} μεγαλη[8:10]{.aside}

προσειχον δε αυτω δια το ικανω χρονω ταις μαγειαις εξεστακεναι αυτους[8:11]{.aside}

[οτε]{.greek-omitted} [ως]{.greek-added} δε επιστευσαν τω φιλιππω ευαγγελιζομενω [τα]{.greek-omitted} περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος επιστευ[σε]{.unclear}ν κ[αι]{.greek-supplied} [βαπτισθεις]{.greek-supplied} [ην]{.greek-supplied} [προ]{.unclear}[σ]{.greek-supplied}καρτερων τω φιλιππω θεωρων τε [σημεια]{.greek-added} [και]{.greek-added} δυναμεις [μεγαλας]{.greek-added} [και]{.greek-omitted} [σημεια]{.greek-omitted} [γινομενα]{.greek-omitted} [γινομενας]{.greek-added} εξιστατο[8:13]{.aside}

[ακουσαντες]{.greek-omitted} [ακουοντες]{.greek-added} δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η [σαμαρεια]{.greek-omitted} [σαμαρια]{.greek-added} τον λογον του [θεου]{.greek-abbr} [απεστειλαν]{.greek-omitted} [εξαπεστειλαν]{.greek-added} προς αυτους [τον]{.greek-omitted} πετρον και ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως λαβωσιν [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

[ουπω]{.greek-omitted} [ουδεπω]{.greek-added} γαρ ην επ ουδενι αυτων [επιπεπτωκος]{.greek-omitted} [επελελυθως]{.greek-added} μονον [δε]{.greek-omitted} [βεβαπτισμενοι]{.greek-omitted} [βαπτισμενοι]{.greek-added} υπηρχον εις το ονομα του [χριστου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr}[8:16]{.aside}

τοτε επετιθουν τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

[θεασαμενος]{.greek-omitted} [ιδων]{.greek-added} δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω εαν επιθω τας χειρας [λαμβανη]{.greek-omitted} [λαμβανει]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε ειπεν προς αυτον το αργυριον σου συν σοι ειη εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} ενομισας δια χρηματων κτασθαι[8:20]{.aside}

ουκ [εστιν]{.unclear} [σοι]{.unclear} μερις ουδε κλη[ρος]{.unclear} [εν]{.unclear} [τω]{.unclear} [λογω]{.unclear} [του]{.unclear}τω η γαρ [κα]{.unclear}ρδι[α]{.unclear} [σου]{.unclear} ουκ [ε]{.unclear}στιν ε[υθεια]{.unclear} [ενωπιον]{.greek-omitted} [[εναντι]{.unclear}]{.greek-added} του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} ει αρα αφεθησεται [σοι]{.greek-omitted} [σου]{.greek-added} η επινοια της καρδιας σου[8:22]{.aside}

εις γαρ χολην πικριας και συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

αποκριθεις δε ο σιμων ειπεν δεηθητε υμεις υπερ εμου προς τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι μεν ουν διαμαρτυραμενοι και λαλησαντες τον λογον του [κυριου]{.greek-abbr} υπεστρεψαν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} πολλας τε [κωμας]{.greek-omitted} [κομας]{.greek-added} των [σαμαρειτων]{.greek-omitted} [σαμαριτων]{.greek-added} ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} ελαλησεν προς φιλιππον λεγων αναστηθι και πορευου κατα μεσημβριαν επι την οδον την καταβαινουσαν απο [ιερουσαλημ]{.greek-abbr} εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ αιθιοψ ευνουχος δυναστης κανδακης [της]{.greek-omitted} [βασιλισσης]{.greek-omitted} [βασιλεισσης]{.greek-added} αιθιοπων ος ην επι πασης της γαζης αυτης ος [εληλυθει]{.greek-omitted} [εληλυθη]{.greek-added} προσκυνησων εις [ιερουσαλημ]{.greek-abbr}[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου και ανεγινωσκεν τον προφητην ησαιαν[8:28]{.aside}

ειπεν δε το [πνευμα]{.greek-abbr} τω φιλιππω προσελθε και κολληθητι τω αρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος τον προφητην ησαιαν και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε ειπεν πως γαρ αν δυναιμην εαν μη τις [οδηγηση]{.greek-omitted} [οδηγησει]{.greek-added} [με]{.greek-omitted} [μαι]{.greek-added} παρεκαλεσεν τε τον φιλιππον αναβαντα καθισαι [συν]{.greek-omitted} [εν]{.greek-added} αυτω[8:31]{.aside}

η δε περιοχη της γραφης ην ανεγινωσκεν ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του [κειροντος]{.greek-omitted} [κειραντος]{.greek-added} αυτον αφωνος ουτως ουκ [ανοιγει]{.greek-omitted} [ανοιγη]{.greek-added} το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω ειπεν δεομαι σου περι τινος ο προφητης λεγει τουτο περι εαυτου η περι ετερου τινος[8:34]{.aside}

ανοιξας δε [ο]{.greek-omitted} [φιλιππος]{.greek-omitted} το στομα αυτου [ο]{.greek-added} [φιλιππος]{.greek-added} και αρξαμενος απο της γραφης ταυτης ευηγγελισατο αυτω τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε [επορευοντο]{.greek-omitted} [επορευετο]{.greek-added} κατα την οδον ηλθον επι τι υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

και εκελευσεν στηναι το αρμα και κατεβησαν [αμφοτεροι]{.greek-omitted} εις το υδωρ [αμφοτεροι]{.greek-added} ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν [εκ]{.greek-omitted} [απο]{.greek-added} του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ηρπασεν τον φιλιππον και ουκ [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτον ουκετι ο ευνουχος επορευετο γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις [καισαρειαν]{.greek-omitted} [καισαριαν]{.greek-added}[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις δαμασκον προς τας συναγωγας οπως εαν τινας ευρη της οδου οντας ανδρας τε και γυναικας δεδεμενους αγαγη εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} πορευεσθαι [αυτον]{.greek-added} εγενετο αυτον εγγιζειν [τη]{.greek-omitted} [εν]{.greek-added} δαμασκω και εξαιφνης περιηστραψεν [αυτον]{.greek-omitted} [αντον]{.greek-added} φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην ηκουσεν φωνην λεγουσαν αυτω σαουλ σαουλ τι με διωκεις[9:4]{.aside}

ειπεν δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[9:5]{.aside}

αλλα αναστηθι και εισελθε εις την πολιν [και]{.greek-omitted} [κακει]{.greek-added} λαληθησεται σοι [ο]{.greek-added} τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι συνοδευοντες αυτω [ειστηκεισαν]{.greek-omitted} [ιστηκεισαν]{.greek-added} ενεοι ακουοντες μεν της φωνης μηδενα δε θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων [τε]{.greek-omitted} [δε]{.greek-added} των οφθαλμων αυτου ουδενα εβλεπεν χειραγωγουντες δε αυτον εισηγαγον εις δαμασκον[9:8]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και ειπεν προς αυτον ο [κυριος]{.greek-abbr} εν οραματι ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} εν οραματι ανδρα ονοματι ανανιαν εισελθοντα και επιθεντα αυτω χειρα οπως αναβλεψη[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα εποιησεν τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και [ωδε]{.greek-omitted} [οδε]{.greek-added} εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

ειπεν δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει αυτον υπερ του ονοματος μου παθειν[9:16]{.aside}

απηλθεν δε ανανιας και εισηλθεν εις την οικιαν και επιθεις επ αυτον τας χειρας ειπεν σαουλ αδελφε ο [κυριος]{.greek-abbr} απεσταλκεν με [[ιησους]{.greek-abbr}]{.greek-added} ο [οφθεις]{.greek-omitted} [ωφθεις]{.greek-added} σοι εν τη οδω η ηρχου οπως αναβλεψης και [πλησθης]{.greek-omitted} [πλησθεις]{.greek-added} [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

και ευθεως [απεπεσον]{.greek-omitted} [απεπεσαν]{.greek-added} απο των οφθαλμων αυτου ωσει λεπιδες ανεβλεψεν τε [παραχρημα]{.greek-added} και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε [ο]{.greek-omitted} [σαυλος]{.greek-omitted} μετα των [οντων]{.greek-added} εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις εκηρυσσεν τον [χριστον]{.greek-omitted} [[ιησουν]{.greek-abbr}]{.greek-added} οτι ουτος εστιν ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγον ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα [τι]{.greek-added} τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους αγαγη επι τους αρχιερεις[9:21]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και συνεχυνεν τους ιουδαιους τους κατοικουντας εν δαμασκω συμβιβαζων οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω η επιβουλη αυτων παρετηρουν τε τας πυλας ημερας τε και νυκτος οπως αυτον ανελωσιν[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος καθηκαν [αυτον]{.greek-added} δια του τειχους χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι εστιν μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον [η]{.greek-added} [ηγαγεν]{.greek-omitted} [γαγεν]{.greek-added} προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν τω ονοματι του [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος εις [ιερουσαλημ]{.greek-abbr} [και]{.greek-omitted} παρρησιαζομενος εν τω ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

[ελαλει]{.greek-omitted} [ελαλη]{.greek-added} τε και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

[επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} δε οι αδελφοι κατηγαγον αυτον εις καισαρειαν και εξαπεστειλαν αυτον εις ταρσον[9:30]{.aside}

[αι]{.greek-omitted} [η]{.greek-added} μεν ουν [εκκλησιαι]{.greek-omitted} [εκκλησια]{.greek-added} καθ ολης της ιουδαιας και γαλιλαιας και σαμαρειας [ειχον]{.greek-omitted} [ειχεν]{.greek-added} ειρηνην [οικοδομουμεναι]{.greek-omitted} [οικοδομουμενη]{.greek-added} και [πορευομεναι]{.greek-omitted} [πορευομενη]{.greek-added} τω φοβω [του]{.greek-omitted} [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} [επληθυνοντο]{.greek-omitted} [επληθυνετο]{.greek-added}[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας [λυδδαν]{.greek-omitted} [λυδδα]{.greek-added}[9:32]{.aside}

ευρεν δε εκει [ανθρωπον]{.greek-abbr} τινα [ονοματι]{.greek-added} αινεαν [ονοματι]{.greek-omitted} εξ ετων οκτω κατακειμενον επι [κραββατω]{.greek-omitted} [κραβαττω]{.greek-added} ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ιησους]{.greek-abbr} [ο]{.greek-omitted} [χριστος]{.greek-abbr} αναστηθι και στρωσον σεαυτω και ευθεως ανεστη[9:34]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον παντες οι κατοικουντες [λυδδαν]{.greek-omitted} [λυδδα]{.greek-added} και τον [ασσαρωνα]{.greek-omitted} [σαρωναν]{.greek-added} οιτινες επεστρεψαν [προς]{.greek-added} [επι]{.greek-omitted} [τον]{.greek-omitted} [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} η διερμηνευομενη λεγεται δορκας αυτη ην πληρης αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασαν [αποθανειν]{.greek-added} αυτην [αποθανειν]{.greek-omitted} λουσαντες δε αυτην εθηκαν εν [τω]{.greek-added} υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν [δυο]{.greek-added} [ανδρας]{.greek-added} προς αυτον παρακαλουντες μη οκνησαι διελθειν εως αυτων[9:38]{.aside}

αναστας δε πετρος συνηλθεν αυτοις ον παραγενομενον ανηγαγον εις το υπερωον και [παρεστησαν]{.greek-omitted} [περιεστησαν]{.greek-added} αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μετ αυτων ουσα η δορκας[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος θεις τα γονατα προσηυξατο και επιστρεψας προς το σωμα ειπεν [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} αναστηθι η δε [ηνοιξεν]{.greek-omitted} [διηνοιξεν]{.greek-added} τους οφθαλμους αυτης και ιδουσα τον πετρον ανεκαθισεν[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην [και]{.greek-added} φωνησας [δε]{.greek-omitted} τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωστον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι [αυτον]{.greek-omitted} εν ιοππη παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις [ην]{.greek-omitted} εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ σπειρης της καλουμενης ιταλικης[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

[ειδεν]{.greek-omitted} [ιδεν]{.greek-added} εν οραματι φανερως ωσει [περι]{.greek-added} ωραν ενατην της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε ατενισας αυτω και εμφοβος γενομενος ειπεν τι εστιν [κυριε]{.greek-abbr} ειπεν δε αυτω αι προσευχαι σου και αι ελεημοσυναι σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και [μεταπεμψαι]{.greek-omitted} [μεταπεμψε]{.greek-added} σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν οικια παρα θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην ευσεβη των προσκαρτερουντων αυτω[10:7]{.aside}

και εξηγησαμενος αυτοις [απαντα]{.greek-omitted} [παντα]{.greek-added} απεστειλεν αυτους [εις]{.greek-omitted} [προς]{.greek-added} την ιοππην[10:8]{.aside}

τη δε επαυριον οδοιπορουντων [εκεινων]{.greek-omitted} [αυτων]{.greek-added} και τη πολει εγγιζοντων ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν εκτην[10:9]{.aside}

εγενετο δε προσπεινος και ηθελεν γευσασθαι παρασκευαζοντων δε [εκεινων]{.greek-omitted} [αυτων]{.greek-added} επεπεσεν επ αυτον εκστασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεωγμενον και [καταβαινον]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [τεσσαρσιν]{.greek-added} [αρχαις]{.greek-added} [δεδεμενον]{.greek-added} σκευος τι ως οθονην μεγαλην [καταβαινον]{.greek-added} [[καταβαι[νον]{.greek-supplied}]{.corr}]{.greek-added} [[σκευος]{.corr}]{.greek-added} [[τι]{.corr}]{.greek-added} [[ω[ς]{.greek-supplied}]{.corr}]{.greek-added} [[[οθονην]{.greek-supplied}]{.corr}]{.greek-added} [[μεγαλην]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [τεσσαρσιν]{.corr} [αρχαις]{.corr} [δεδεμενον]{.corr} και [καθιεμενον]{.greek-omitted} [καθημενον]{.greek-added} επι της γης[10:11]{.aside}

εν ω υπηρχεν παντα τα τετραποδα [της]{.greek-omitted} [γης]{.greek-omitted} και τα θηρια και τα ερπετα [της]{.greek-added} [γης]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστας πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος ειπεν μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον [η]{.greek-omitted} [και]{.greek-added} ακαθαρτον[10:14]{.aside}

και φωνη [παλιν]{.greek-omitted} εκ δευτερου προς αυτον α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθερισεν]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν ανεληφθη το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο πετρος τι αν ειη το οραμα ο ειδεν και ιδου οι ανδρες οι απεσταλμενοι [απο]{.greek-omitted} [υπο]{.greek-added} του κορνηλιου διερωτησαντες την οικιαν [του]{.greek-added} σιμωνος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει [σιμων]{.greek-omitted} [σημων]{.greek-added} ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες ζητουσιν σε[10:19]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα [αυ]{.greek-added} αυτους[10:20]{.aside}

καταβας δε πετρος προς τους ανδρας ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος ουν αυτους εξενισεν τη δε επαυριον [αναστας]{.greek-added} ο πετρος εξηλθεν [εις]{.greek-added} [καισαρειαν]{.greek-added} συν αυτοις και τινες των αδελφων των απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος [ηγειρεν]{.greek-added} αυτον [ηγειρεν]{.greek-omitted} λεγων αναστηθι [καγω]{.greek-omitted} [και]{.greek-added} [γαρ]{.greek-added} [εγω]{.greek-added} αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω εισηλθεν και ευρισκει [συνεληλυθοτας]{.greek-omitted} [συνεληλυθωτας]{.greek-added} πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως [αθεμιτον]{.greek-omitted} [αθεμητον]{.greek-added} εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και αναντιρρητως ηλθον μεταπεμφθεις [υφ]{.greek-added} [ημων]{.greek-added} [πυνθανομαι]{.greek-omitted} [πυνθαννομαι]{.greek-added} ουν τινι λογω [μετεπεμψασθε]{.greek-omitted} [μετεπεμψασθαι]{.greek-added} με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και την ενατην ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν [εσθητι]{.greek-omitted} [αισθητι]{.greek-added} λαμπρα[10:30]{.aside}

και φησιν κορνηλιε εισηκουσθη σου η προσευχη και αι ελεημοσυναι σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και [μετακαλεσαι]{.greek-omitted} [μετακαλεσε]{.greek-added} [σιμωνα]{.greek-omitted} [σημωνα]{.greek-added} ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος βυρσεως παρα θαλασσαν ος παραγενομενος λαλησει σοι[10:32]{.aside}

εξαυτης [ουν]{.greek-omitted} επεμψα προς σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added}[10:33]{.aside}

ανοιξας δε πετρος το στομα ειπεν επ αληθειας καταλαμβανομαι οτι ουκ εστιν προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι εθνει ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην δεκτος αυτω εστιν[10:35]{.aside}

τον λογον ον απεστειλεν τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος εστιν παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το βαπτισμα ο εκηρυξεν ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ως εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-omitted} [ιεροσολυμοις]{.greek-added} ον και [ανειλον]{.greek-omitted} [ανειλαν]{.greek-added} κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} ηγειρεν τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα μαρτυσιν τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες συνεφαγομεν και [συνεπιομεν]{.greek-omitted} [συνεπιωμεν]{.greek-added} αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι [αυτος]{.greek-omitted} [ουτος]{.greek-added} εστιν ο [ωρισμενος]{.greek-omitted} [ορισμενος]{.greek-added} υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη ο πετρος [́]{.greek-added}[10:46]{.aside}

μητι το υδωρ κωλυσαι δυναται τις του μη βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

προσεταξεν [τε]{.greek-omitted} [δε]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} βαπτισθηναι εν τω ονοματι [του]{.greek-omitted} [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} τοτε ηρωτησαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας [εισηλθες]{.greek-omitted} [εισηλθεν]{.greek-added} και [συνεφαγες]{.greek-omitted} [συνεφαγεν]{.greek-added} αυτοις[11:3]{.aside}

αρξαμενος δε [ο]{.greek-omitted} πετρος εξετιθετο αυτοις καθεξης λεγων[11:4]{.aside}

εγω ημην εν πολει ιοππη προσευχομενος και [ειδον]{.greek-omitted} [ιδον]{.greek-added} εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και [ειδον]{.greek-omitted} [ιδον]{.greek-added} τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι [παν]{.greek-omitted} κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθερισεν]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν [απαντα]{.greek-added} ανεσπασθη [εκ]{.greek-added} [απαντα]{.greek-omitted} [εις]{.greek-omitted} τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η [ημην]{.greek-omitted} [ημεν]{.greek-added} απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

ειπεν δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν [διακρινομενον]{.greek-omitted} [διακριναντα]{.greek-added} ηλθον δε συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

απηγγειλεν τε ημιν πως [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην ανδρας και [μεταπεμψαι]{.greek-omitted} [μεταπεμψε]{.greek-added} σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις σωθηση συ και πας ο οικος σου[11:14]{.aside}

εν δε τω αρξασθαι με λαλειν επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [του]{.greek-added} [κυριου]{.greek-abbr} [ως]{.greek-omitted} [ος]{.greek-added} ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω [δε]{.greek-omitted} τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες αρα [γε]{.greek-omitted} και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες απο της θλιψεως της γενομενης επι στεφανω διηλθον εως φοινικης και [κυπρου]{.greek-omitted} [και]{.greek-omitted} αντιοχειας μηδενι λαλουντες τον λογον ει [μη]{.greek-omitted} [μι]{.greek-added} μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων [κυπριοι]{.greek-added} ανδρες [κυπριοι]{.greek-omitted} και [κυρηναιοι]{.greek-omitted} [κυριναιοι]{.greek-added} οιτινες εισελθοντες εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της [ουσης]{.greek-added} εν ιεροσολυμοις [τα]{.greek-added} περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει παντας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και πληρης [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος [ικανος]{.greek-omitted} [ικανως]{.greek-added} τω [κυριω]{.greek-abbr}[11:24]{.aside}

εξηλθεν δε εις ταρσον ο βαρναβας [αναζητησαι]{.greek-omitted} [επιζητησαι]{.greek-added} σαυλον[11:25]{.aside}

και ευρων [αυτον]{.greek-added} ηγαγεν [αυτον]{.greek-omitted} εις αντιοχειαν εγενετο δε [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ενιαυτον ολον συναχθηναι [εν]{.greek-added} τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια [τους]{.greek-omitted} [μαθητας]{.greek-omitted} χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος εσημανεν δια του [πνευματος]{.greek-abbr} [λιμον]{.greek-omitted} [λειμον]{.greek-added} [μεγαν]{.greek-omitted} [μεγαλην]{.greek-added} [μελλειν]{.greek-omitted} εσεσθαι εφ ολην την οικουμενην [ητις]{.greek-added} [οστις]{.greek-omitted} [και]{.greek-omitted} εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων [καθως]{.greek-omitted} [καθω]{.greek-added} ευπορειτο τις ωρισαν εκαστος αυτων εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

ο και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της εκκλησιας[12:1]{.aside}

ανειλεν δε ιακωβον τον αδελφον ιωαννου [μαχαιρα]{.greek-omitted} [μαχαιρη]{.greek-added}[12:2]{.aside}

[και]{.greek-omitted} ιδων [δε]{.greek-added} οτι αρεστον εστιν τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε αι ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους τεσσαρσιν τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα [το]{.greek-omitted} [πασχα]{.greek-omitted} [την]{.greek-added} [εορτην]{.greek-added} αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} [υπερ]{.greek-omitted} [περι]{.greek-added} αυτου[12:5]{.aside}

οτε δε [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} [προσαγειν]{.greek-added} αυτον [προαγειν]{.greek-omitted} ο ηρωδης τη νυκτι εκεινη ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δυσιν φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και [εξεπεσον]{.greek-omitted} [εξεπεσαν]{.greek-added} αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

ειπεν [τε]{.greek-omitted} [δε]{.greek-added} ο αγγελος προς αυτον [περιζωσαι]{.greek-omitted} [ζωσαι]{.greek-added} και υποδησαι τα σανδαλια σου εποιησεν δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και ακολουθει μοι[12:8]{.aside}

και εξελθων [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και ουκ [ηδει]{.greek-omitted} [ειδη]{.greek-added} οτι αληθες [εστιν]{.greek-omitted} [εστι]{.greek-added} το γινομενον δια του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν εις την πολιν ητις αυτοματη [ηνοιχθη]{.greek-omitted} [ηνοιγη]{.greek-added} αυτοις και εξελθοντες προηλθον ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος γενομενος εν εαυτω ειπεν νυν οιδα αληθως οτι εξαπεστειλεν [κυριος]{.greek-abbr} τον αγγελον αυτου και [εξειλετο]{.greek-omitted} [εξηλατο]{.greek-added} με εκ χειρος ηρωδου και πασης της προσδοκιας του λαου των ιουδαιων[12:11]{.aside}

συνιδων [τε]{.greek-omitted} [δε]{.greek-added} ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} ιωαννου του επικαλουμενου μαρκου ου ησαν ικανοι συνηθροισμενοι και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του πετρου την θυραν του πυλωνος προσηλθεν παιδισκη υπακουσαι ονοματι ροδη[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ ηνοιξεν τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον μαινη η δε διισχυριζετο ουτως εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος επεμενεν κρουων ανοιξαντες δε [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον και εξεστησαν[12:16]{.aside}

[κατασεισας]{.greek-omitted} [κατασισας]{.greek-added} δε αυτοις τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξηγαγεν εκ της φυλακης ειπεν δε απαγγειλατε ιακωβω και τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις την καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης θυμομαχων τυριοις και σιδωνιοις [ομοθυμαδον]{.greek-omitted} [παρησαν]{.greek-added} δε [παρησαν]{.greek-omitted} [ομοθυμαδων]{.greek-added} προς αυτον και πεισαντες βλαστον [τινα]{.greek-added} τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια [το]{.greek-omitted} [του]{.greek-added} τρεφεσθαι αυτων την χωραν απο της [βασιλικης]{.greek-omitted} [βασιλεικης]{.greek-added}[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα βασιλικην και καθισας επι του βηματος εδημηγορει προς αυτους[12:21]{.aside}

ο δε δημος [επεφωνει]{.greek-omitted} [επεφωνη]{.greek-added} φωνη [θεου]{.greek-abbr} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε [αυτον]{.greek-added} επαταξεν [αυτον]{.greek-omitted} αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ [εδωκεν]{.greek-omitted} [εδοκεν]{.greek-added} δοξαν τω [θεω]{.greek-abbr} και γενομενος σκωληκοβρωτος εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} ηυξανεν και επληθυνετο[12:24]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν [εις]{.greek-omitted} [απο]{.greek-added} ιερουσαλημ πληρωσαντες την διακονιαν συμπαραλαβοντες και ιωαννην τον [επικληθεντα]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε τινες εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος ο [κυρηναιος]{.greek-omitted} [κυριναιος]{.greek-added} μαναην τε ηρωδου του [τετραρχου]{.greek-omitted} [τετετραρχου]{.greek-added} συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων ειπεν το [πνευμα]{.greek-abbr} το αγιον αφορισατε δη μοι τον βαρναβαν και [τον]{.greek-omitted} σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες [αυτοις]{.greek-added} τας χειρας [αυτοις]{.greek-omitted} απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεντες υπο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις [την]{.greek-omitted} σελευκειαν [εκειθεν]{.greek-omitted} [κακειθεν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} απεπλευσαν εις [την]{.greek-omitted} κυπρον[13:4]{.aside}

και γενομενοι εν [σαλαμινι]{.greek-omitted} [σαλαμηνι]{.greek-added} [κατηγγελλον]{.greek-omitted} [κατηγγελον]{.greek-added} τον λογον του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} εν ταις συναγωγαις των ιουδαιων ειχον δε και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} υπηρετην[13:5]{.aside}

διελθοντες δε [ολην]{.greek-added} την νησον αχρι παφου [ευρον]{.greek-omitted} [ευρων]{.greek-added} [ανδρα]{.greek-added} τινα μαγον ψευδοπροφητην ιουδαιον ω ονομα [βαριησους]{.greek-omitted} [βαριησουν]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω παυλω ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επεζητησεν ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μαγος ουτως γαρ [μεθερμηνευεται]{.greek-omitted} [ερμηνευεται]{.greek-added} το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου και ατενισας εις αυτον[13:9]{.aside}

ειπεν ω [πληρης]{.greek-omitted} [πληρεις]{.greek-added} παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου παυση διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον αχρι καιρου παραχρημα δε επεπεσεν επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε αποχωρησας απ αυτων υπεστρεψεν εις ιεροσολυμα[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει εστιν λογος εν υμιν παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και [κατασεισας]{.greek-omitted} [κατασισας]{.greek-added} τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου [[ισραηλ]{.greek-abbr}]{.greek-added} εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη αιγυπτω και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον [ετροποφορησεν]{.greek-omitted} [ετροφοφορησεν]{.greek-added} αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη [επτα]{.greek-omitted} εν γη χανααν [επτα]{.greek-added} κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

και μετα ταυτα ως [ετεσιν]{.greek-omitted} [ετεσι]{.greek-added} τετρακοσιοις και πεντηκοντα εδωκεν κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ υιον κις ανδρα εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμην]{.greek-added} ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και ειπεν μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν [ηγαγεν]{.greek-omitted} [ηγειρεν]{.greek-added} τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-omitted} [[σωτηρα]{.greek-abbr}]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας [παντι]{.greek-added} τω [λαω]{.greek-added} [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου [ο]{.greek-omitted} ιωαννης τον δρομον ελεγεν τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος της [σωτηριας]{.greek-abbr} ταυτης [απεσταλη]{.greek-omitted} [εξαπεσταλη]{.greek-added}[13:26]{.aside}

οι γαρ κατοικουντες [εν]{.greek-omitted} [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον αγνοησαντες και τας φωνας των προφητων τας κατα παν σαββατον αναγινωσκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες [ητησαντο]{.greek-omitted} [ητισαντο]{.greek-added} πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις μνημειον[13:29]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [νυν]{.greek-added} εισιν μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκεν]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω τω δευτερω γεγραπται [υιος]{.greek-abbr} μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον εκ νεκρων μηκετι μελλοντα [αυτον]{.greek-added} υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

[διο]{.greek-omitted} [διοτι]{.greek-added} και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ ειδεν διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν ανδρες αδελφοι οτι δια τουτου υμιν αφεσις αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωυσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} εν [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} [εν]{.greek-omitted} [τουτω]{.greek-omitted} [τουτο]{.greek-added} πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται [και]{.greek-added} [επιβλεψατε]{.greek-added} και θαυμασατε και αφανισθητε οτι εργον [εργαζομαι]{.greek-added} εγω [εργαζομαι]{.greek-omitted} εν ταις ημεραις υμων ο ου μη πιστευσητε εαν τις εκδιηγηται υμιν[13:41]{.aside}

εξιοντων δε [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [ιουδαιων]{.greek-omitted} παρεκαλουν [τα]{.greek-omitted} [εθνη]{.greek-omitted} εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

λυθεισης δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων [προσηλυτων]{.greek-omitted} [προηλυτων]{.greek-added} τω παυλω και τω βαρναβα οιτινες προσλαλουντες [αυτοις]{.greek-added} επειθον αυτους [επιμενειν]{.greek-omitted} [προσμενειν]{.greek-added} τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω [τε]{.greek-omitted} [δε]{.greek-added} ερχομενω σαββατω [σχεδον]{.greek-omitted} [σχεδων]{.greek-added} πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-abbr}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλου λεγομενοις [αντιλεγοντες]{.greek-omitted} [και]{.greek-omitted} βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος και ο βαρναβας ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} επειδη δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ εντεταλται ημιν ο [κυριος]{.greek-abbr} [τεθεικα]{.greek-omitted} [τεθηκα]{.greek-added} σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακο[υ]{.unclear}οντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον τον λογον του [κυριου]{.greek-abbr} και επ[ιστευ]{.greek-supplied}σαν οσοι ησαν τετα[γμε]{.greek-supplied}νοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος το[υ]{.greek-supplied} [κυριου]{.greek-omitted} [δι]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} [καθ]{.greek-added} ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι [παρωτρυναν]{.greek-omitted} [παρωτρυ]{.greek-added} [ναν]{.greek-added} τας σεβομενας γυναικας [και]{.greek-omitted} τας ευσχημονας και τους πρωτους της πολεως και [επηγειραν]{.greek-omitted} [επεγειραν]{.greek-added} διωγμον επι τον παυλον και [τον]{.greek-omitted} βαρναβαν και εξεβαλον αυτους απο των οριων αυτων[13:50]{.aside}

οι δε εκτιναξαμενοι τον κονιορτον των ποδων [αυτων]{.greek-omitted} επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι [δε]{.greek-omitted} [τε]{.greek-added} μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων [τε]{.greek-omitted} και ελληνων [πληθος]{.greek-added} πολυ [πληθος]{.greek-omitted}[14:1]{.aside}

οι δε [απειθουντες]{.greek-omitted} [απειθησαντες]{.greek-added} ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου διδοντι σημεια και τερατα γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και [λιθοβολησαι]{.greek-omitted} [λιθοβολισαι]{.greek-added} αυτους[14:5]{.aside}

συνιδοντες κατεφυγον εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει [ευαγγελιζομενοι]{.greek-added} ησαν [ευαγγελιζομενοι]{.greek-omitted}[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου [υπαρχων]{.greek-omitted} ος ουδεποτε [περιπεπατηκει]{.greek-omitted} [περιεπατησεν]{.greek-added}[14:8]{.aside}

ουτος ηκουσεν του παυλου λαλουντος ος ατενισας αυτω και ιδων οτι [πιστιν]{.greek-omitted} [πιστην]{.greek-added} εχει του σωθηναι[14:9]{.aside}

ειπεν μεγαλη τη φωνη αναστηθι επι τους ποδας σου ορθως και [ηλλετο]{.greek-omitted} [ηλλατο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι [ιδοντες]{.greek-omitted} [ιδωντες]{.greek-added} ο εποιησεν [ο]{.greek-omitted} παυλος επηραν την φωνην αυτων λυκαονιστι λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν [δια]{.greek-omitted} [διαν]{.greek-added} τον δε παυλον ερμην επειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο [δε]{.greek-omitted} [τε]{.greek-added} [ιερευς]{.greek-omitted} [αρχιερευς]{.greek-added} του διος του οντος προ της πολεως [αυτων]{.greek-omitted} ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις ηθελεν θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων [εισεπηδησαν]{.greek-omitted} [εξεπιδησαν]{.greek-added} εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε και ημεις ομοιοπαθεις εσμεν υμιν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο τουτων των ματαιων επιστρεφειν επι [τον]{.greek-omitted} [θεον]{.greek-abbr} [τον]{.greek-omitted} ζωντα ος εποιησεν τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν [ταις]{.greek-omitted} [τοις]{.greek-added} παρωχημεναις γενεαις [ειασεν]{.greek-omitted} [ιασεν]{.greek-added} παντα τα εθνη πορευεσθαι ταις οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρον εαυτον αφηκεν [αγαθοποιων]{.greek-omitted} [αγαθουργων]{.greek-added} [ουρανοθεν]{.greek-omitted} [[ουνωθεν]{.greek-abbr}]{.greek-added} υμιν [διδους]{.greek-added} υετους [διδους]{.greek-omitted} και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας [ημων]{.greek-omitted} [υμων]{.greek-added}[14:17]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν αυτοις [αλλα]{.greek-added} [πορευεσθαι]{.greek-added} [εκαστον]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ιδια]{.greek-added}[14:18]{.aside}

[επηλθον]{.greek-omitted} [διατριβοντων]{.greek-added} δε [αυτων]{.greek-added} [και]{.greek-added} [διδασκοντων]{.greek-added} [επηλθαν]{.greek-added} απο αντιοχειας και ικονιου ιουδαιοι [και]{.greek-added} [διαλεγομενων]{.greek-added} [αυτων]{.greek-added} [παρρησια]{.greek-added} [επεισαν]{.greek-added} [τους]{.greek-added} [οχλους]{.greek-added} [αποστηναι]{.greek-added} [απ]{.greek-added} [αυτων]{.greek-added} [λεγοντες]{.greek-added} [οτι]{.greek-added} [ουδεν]{.greek-added} [αληθες]{.greek-added} [λεγουσιν]{.greek-added} [αλλα]{.greek-added} [παντα]{.greek-added} [ψευδονται]{.greek-added} και πεισαντες τους οχλους και λιθασαντες τον παυλον [εσυρον]{.greek-omitted} [εσυραν]{.greek-added} εξω της πολεως [νομισαντες]{.greek-omitted} [νομησαντες]{.greek-added} αυτον [τεθναναι]{.greek-omitted} [τεθνηκεναι]{.greek-added}[14:19]{.aside}

κυκλωσαντων δε [αυτον]{.greek-omitted} των μαθητων [αυτον]{.greek-added} αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν συν τω βαρναβα [εις]{.greek-omitted} [δερβην]{.greek-omitted}[14:20]{.aside}

ευαγγελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν και ικονιον και αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων παρακαλουντες [εμμενειν]{.greek-omitted} [ενμενειν]{.greek-added} τη πιστει και οτι δια πολλων θλιψεων δει ημας εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις [πρεσβυτερους]{.greek-omitted} κατ εκκλησιαν [πρεσβυτερους]{.greek-added} προσευξαμενοι μετα νηστειων παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον πεπιστευκεισαν[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον εις [την]{.greek-added} παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} κατεβησαν εις [ατταλειαν]{.greek-omitted} [ατταλιαν]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν παραδεδομενοι τη χαριτι του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι ηνοιξεν τοις εθνεσιν θυραν πιστεως[14:27]{.aside}

διετριβον [δε]{.greek-omitted} [τε]{.greek-added} εκει χρονον ουκ ολιγον συν τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη [περιτεμνησθε]{.greek-omitted} [περιτμηθητε]{.greek-added} τω εθει μωυσεως ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης [ουν]{.greek-omitted} στασεως και ζητησεως ουκ ολιγης τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την φοινικην και σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις αδελφοις[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} [απεδεχθησαν]{.greek-omitted} [προσεδεχθησαν]{.greek-added} υπο της εκκλησιας [και]{.greek-added} [των]{.greek-added} [αποστολων]{.greek-added} και των αποστολων και των πρεσβυτερων ανηγγειλαν τε οσα [εποιησεν]{.greek-added} ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} μετ αυτων[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων πεπιστευκοτες λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added}[15:5]{.aside}

συνηχθησαν [δε]{.greek-omitted} [τε]{.greek-added} οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε συζητησεως γενομενης αναστας πετρος ειπεν προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων [εν]{.greek-added} [υμιν]{.greek-added} [εξελεξατο]{.greek-added} ο [θεος]{.greek-abbr} [εν]{.greek-omitted} [ημιν]{.greek-omitted} [εξελεξατο]{.greek-omitted} δια του στοματος μου ακουσαι τα εθνη τον λογον του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} δους αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και ουδεν διεκρινεν μεταξυ ημων τε και αυτων τη πιστει καθαρισας τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} επιθειναι ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι [καθ]{.greek-omitted} ον τροπον κακεινοι[15:11]{.aside}

εσιγησεν δε παν το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις εθνεσιν δι αυτων[15:12]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον [επι]{.greek-omitted} τω ονοματι αυτου[15:14]{.aside}

και τουτω συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} [ο]{.greek-omitted} ποιων [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted}[15:17]{.aside}

γνωστα απ αιωνος εστιν τω [θεω]{.greek-abbr} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

αλλα επιστειλαι αυτοις του απεχεσθαι απο των [αλισγηματων]{.greek-omitted} [αλιγησματων]{.greek-added} των ειδωλων και της πορν[ει]{.unclear}ας και του πνικτου και του αιματος[15:20]{.aside}

μωυσης γαρ εκ γενεων αρχαιων κατα πολιν τους κηρυσσοντας αυτον εχει εν ταις συναγωγαις κατα παν σαββατον αναγινωσκομενος[15:21]{.aside}

τοτε εδοξεν τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν [τω]{.greek-added} παυλω και βαρναβα ιουδαν τον [επικαλουμενον]{.greek-omitted} [καλουμενον]{.greek-added} βαρσαββαν και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων εξελθοντες εταραξαν υμας λογοις ανασκευαζοντες τας ψυχας υμων λεγοντες περιτεμνεσθαι και τηρειν τον νομον οις [ου]{.greek-omitted} διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον [εκλεξαμενους]{.greek-omitted} [εκλεξαμενοις]{.greek-added} ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα [τε]{.greek-added} και παυλω[15:25]{.aside}

[ανθρωποις]{.greek-abbr} παραδεδωκοσιν τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

εδοξεν γαρ τω [[πνευματι]{.greek-abbr}]{.greek-added} [τω]{.greek-added} αγιω [πνευματι]{.greek-omitted} και ημιν μηδεν πλεον [επιτιθεσθαι]{.greek-omitted} [επιτειθεσθαι]{.greek-added} υμιν βαρος πλην [των]{.greek-omitted} [τουτων]{.greek-added} επαναγκες [τουτων]{.greek-omitted}[15:28]{.aside}

απεχεσθαι ειδωλοθυτων και [πνικτου]{.greek-added} [και]{.greek-added} αιματος [και]{.greek-omitted} [πνικτου]{.greek-omitted} και πορνειας εξ ων διατηρουντες εαυτους ευ [πραξετε]{.greek-omitted} [πραξητε]{.greek-added} ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες [ηλθον]{.greek-omitted} [κατηλθον]{.greek-added} εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

αναγνοντες δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και [επεστηριξαν]{.greek-omitted} [επεστηρισαν]{.greek-added}[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης απο των αδελφων προς τους αποστολους[15:33]{.aside}

[εδοξεν]{.greek-added} [δε]{.greek-added} [τω]{.greek-added} [σιλα]{.greek-added} [επιμειναι]{.greek-added} [αυτου]{.greek-added}[15:34]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας ειπεν παυλος προς βαρναβαν επιστρεψαντες δη επισκεψωμεθα τους αδελφους [ημων]{.greek-omitted} κατα [πολιν]{.greek-added} πασαν [πολιν]{.greek-omitted} εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως εχουσιν[15:36]{.aside}

βαρναβας δε εβουλευσατο συμπαραλαβειν [τον]{.greek-omitted} [και]{.greek-added} ιωαννην τον [καλουμενον]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη [συμπαραλαβειν]{.greek-omitted} [συμπαραλαμβανειν]{.greek-added} τουτον[15:38]{.aside}

εγενετο [ουν]{.greek-omitted} [δε]{.greek-added} [παροξυσμος]{.greek-omitted} [παρωξυσμος]{.greek-added} ωστε [αποχωρισθηναι]{.greek-omitted} [χωρισθηναι]{.greek-added} αυτους απ αλληλων τον τε βαρναβαν παραλαβοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν εξηλθεν παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και κιλικιαν επιστηριζων τας εκκλησιας[15:41]{.aside}

### Chapter 16

[κατηντησεν]{.greek-omitted} [κατηντησαν]{.greek-added} δε [και]{.greek-added} [εις]{.greek-added} [λυστραν]{.greek-added} [και]{.greek-added} εις δερβην [και]{.greek-omitted} [λυστραν]{.greek-omitted} και ιδου μαθητης τις ην εκει ονοματι τιμοθεος [υιος]{.greek-abbr} γυναικος [τινος]{.greek-omitted} ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τοποις εκεινοις ηδεισαν [γαρ]{.greek-omitted} απαντες τον [πατερα]{.greek-abbr} αυτου οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις παρεδιδουν αυτοις φυλασσειν τα δογματα τα [κεκριμενα]{.greek-omitted} [κεκρυμμενα]{.greek-added} υπο των αποστολων και των πρεσβυτερων των εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και [επερισσευον]{.greek-omitted} [περισσευον]{.greek-added} τω αριθμω καθ ημεραν[16:5]{.aside}

[διελθοντες]{.greek-omitted} [διηλθον]{.greek-added} δε την φρυγιαν και [την]{.greek-omitted} γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες [δε]{.greek-added} κατα την μυσιαν [επειραζον]{.greek-omitted} [κατα]{.greek-omitted} [την]{.greek-omitted} [βιθυνιαν]{.greek-omitted} [πορευεσθαι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ειασεν]{.greek-omitted} [αυτους]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted}[16:7]{.aside}

[παρελθοντες]{.greek-omitted} [δε]{.greek-omitted} [την]{.greek-omitted} [μυσιαν]{.greek-omitted} κατεβησαν εις τρωαδα[16:8]{.aside}

και οραμα δια της νυκτος ωφθη τω παυλω ανηρ τις ην μακεδων εστως [και]{.greek-added} παρακαλων αυτον και λεγων διαβας εις μακεδονιαν βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ευθεως εζητησαμεν [εξελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις [την]{.greek-omitted} μακεδονιαν συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[16:10]{.aside}

αναχθεντες ουν απο [της]{.greek-omitted} τρωαδος ευθυδρομησαμεν εις σαμοθρακην τη [τε]{.greek-omitted} [δε]{.greek-added} επιουση εις [νεα]{.greek-added} [νεαπολιν]{.greek-omitted} [πολιν]{.greek-added}[16:11]{.aside}

εκειθεν τε εις φιλιππους ητις εστιν πρωτη της [μεριδος]{.greek-omitted} [της]{.greek-omitted} μακεδονιας πολις κολωνεια ημεν δε εν [αυτη]{.greek-omitted} [ταυτη]{.greek-added} τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των σαββατων εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο [προσευχη]{.greek-omitted} [προσευχην]{.greek-added} ειναι και καθισαντες ελαλουμεν ταις συνελθουσαις γυναιξιν[16:13]{.aside}

και τις γυνη ονοματι λυδια [πορφυροπωλις]{.greek-omitted} [πορφυροπολις]{.greek-added} πολεως θυατειρων σεβομενη τον [θεον]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουσεν]{.greek-added} ης ο [κυριος]{.greek-abbr} διηνοιξεν την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης παρεκαλεσεν λεγουσα ει κεκρικατε με πιστην [ειναι]{.greek-added} τω [κυριω]{.greek-abbr} [ειναι]{.greek-omitted} εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην παιδισκην τινα εχουσαν [πνευμα]{.greek-abbr} πυθωνος απαντησαι ημιν ητις εργασιαν πολλην παρειχεν τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και ημιν εκραζεν λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον [σωτηριας]{.greek-abbr}[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} ειπεν παραγγελλω σοι εν [τω]{.greek-omitted} ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της εργασιας αυτων [επιλαβομενοι]{.greek-omitted} [λαβομενοι]{.greek-added} τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και καταγγελλουσιν εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις ουσιν[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι [περιρρηξαντες]{.greek-omitted} [περιρηξαντες]{.greek-added} αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω [δεσμοφυλακι]{.greek-omitted} [δεσμωφυλακει]{.greek-added} ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην ειληφως εβαλεν αυτους εις την εσωτεραν φυλακην και τους ποδας αυτων [ησφαλισατο]{.greek-omitted} [εισφαλισατο]{.greek-added} εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [επηκροωντο]{.greek-omitted} [επικροωντο]{.greek-added} δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του δεσμωτηριου ανεωχθησαν [τε]{.greek-omitted} [δε]{.greek-added} παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο [δεσμοφυλαξ]{.greek-omitted} [δεσμωφυλαξ]{.greek-added} και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} [εαυτον]{.greek-omitted} [αυτον]{.greek-added} αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

εφωνησεν δε φωνη μεγαλη [ο]{.greek-omitted} παυλος λεγων μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα [εισεπηδησεν]{.greek-omitted} [εισεπιδησεν]{.greek-added} και εντρομος [γενομενος]{.greek-omitted} [υπαρχων]{.greek-added} προσεπεσεν τω παυλω και τω σιλα[16:29]{.aside}

και [προαγαγων]{.greek-omitted} [παραγαγων]{.greek-added} αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και [πας]{.greek-added} ο οικος σου[16:31]{.aside}

και ελαλησαν αυτω τον λογον του [κυριου]{.greek-abbr} και πασιν τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα της νυκτος ελουσεν [αυτους]{.greek-added} απο των πληγων και εβαπτισθη αυτος και οι αυτου παντες παραχρημα[16:33]{.aside}

αναγαγων [τε]{.greek-omitted} [δε]{.greek-added} αυτους εις τον οικον αυτου παρεθηκεν [αυτοις]{.greek-added} τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλλιασατο]{.greek-added} [πανοικι]{.greek-omitted} [πανοικε[ι]{.unclear}]{.greek-added} πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενομενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

[απηγγειλεν]{.greek-omitted} [απειγγειλεν]{.greek-added} δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους [δειραντες]{.greek-omitted} [δηραντες]{.greek-added} ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας [εκβαλλουσιν]{.greek-omitted} [εκβαλουσιν]{.greek-added} ου γαρ αλλα ελθοντες αυτοι [ημας]{.greek-added} εξαγαγετωσαν[16:37]{.aside}

ανηγγειλαν δε τοις στρατηγοις οι ραβδουχοι τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι εισιν[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και εξαγαγοντες ηρωτων εξελθειν [απο]{.greek-added} της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες τους αδελφους παρεκαλεσαν αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και απολλωνιαν ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το [ειωθος]{.greek-omitted} [ιωθος]{.greek-added} τω παυλω εισηλθεν προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος [αυτοις]{.greek-added} οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν ο [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων [επεισθησαν]{.greek-omitted} [επισθησαν]{.greek-added} και προσεκληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων [πληθος]{.greek-added} πολυ [πληθος]{.greek-omitted} γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

[προσλαβομενοι]{.greek-omitted} [ζηλωσαντες]{.greek-added} δε οι [απειθουντες]{.greek-added} ιουδαιοι [οι]{.greek-omitted} [απειθουντες]{.greek-omitted} [και]{.greek-added} [προσλαβομενοι]{.greek-added} των αγοραιων [ανδρας]{.greek-added} τινας [ανδρας]{.greek-omitted} πονηρους και οχλοποιησαντες εθορυβουν την πολιν [και]{.greek-added} επισταντες [τε]{.greek-omitted} τη οικια [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} εζητουν αυτους [αγαγειν]{.greek-omitted} [προσαγαγειν]{.greek-added} εις [τον]{.greek-omitted} [δημον]{.greek-omitted} [τους]{.greek-added} [δημους]{.greek-added}[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τον ιασονα και [τι]{.greek-added} [τινας]{.greek-omitted} [νας]{.greek-added} αδελφους επι τους πολιταρχας βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι και ενθαδε παρεισιν[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος πρασσουσιν βασιλεα [ετερον]{.greek-added} λεγοντες [ετερον]{.greek-omitted} ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

[εταραξαν]{.greek-omitted} [εταραξεν]{.greek-added} δε [τον]{.greek-omitted} [οχλον]{.greek-omitted} [τους]{.greek-added} [οχλους]{.greek-added} και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του ιασονος και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια [της]{.greek-omitted} νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις βεροιαν οιτινες [παραγενομενοι]{.greek-omitted} [παραγεναμενοι]{.greek-added} εις την συναγωγην [απηεσαν]{.greek-omitted} των ιουδαιων [απειησαν]{.greek-added}[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας [το]{.greek-omitted} καθ ημεραν ανακρινοντες τας γραφας ει εχοι ταυτα ουτως[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της θεσσαλονικης ιουδαιοι οτι και εν τη βεροια κατηγγελη υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες [και]{.greek-added} [ταρασσοντες]{.greek-added} τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι ως επι την θαλασσαν [υπεμενον]{.greek-omitted} [υπεμειναν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} ο τε σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε καθιστωντες τον παυλον ηγαγον αυτον εως αθηνων και λαβοντες εντολην προς τον σιλαν και [τον]{.greek-added} τιμοθεον ινα ως ταχιστα ελθωσιν προς αυτον εξηεσαν[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου παρωξυνετο το [πνευμα]{.greek-abbr} αυτου εν αυτω [θεωρουντι]{.greek-omitted} [θεωρουντος]{.greek-added} κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη [τοις]{.greek-omitted} [ιουδαιοις]{.greek-omitted} [και]{.greek-omitted} τοις σεβομενοις και εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε [των]{.greek-added} [επικουριων]{.greek-added} και [των]{.greek-omitted} [επικουρειων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} στοικων φιλοσοφων συνεβαλλον αυτω και τινες ελεγον τι αν θελοι [λεγειν]{.greek-added} ο σπερμολογος ουτος [λεγειν]{.greek-omitted} οι δε ξενων δαιμονιων [δοκει]{.greek-omitted} καταγγελευς ειναι [δοκει]{.greek-added} οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο [αυτοις]{.greek-added}[17:18]{.aside}

επιλαβομενοι τε αυτου επι τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι τι αν θελοι ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον ευκαιρουν η λεγειν τι και ακουειν καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως δεισιδαιμονεστερους υμας [θεωρω]{.greek-omitted} [θεορω]{.greek-added}[17:22]{.aside}

διερχομενος γαρ και αναθεωρων τα σεβασματα υμων ευρον και βωμον εν ω [επεγεγραπτο]{.greek-omitted} [επεγεγραπτω]{.greek-added} αγνωστω [θεω]{.greek-abbr} ον ουν αγνοουντες ευσεβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [υπαρχων]{.greek-added} [κυριος]{.greek-abbr} [υπαρχων]{.greek-omitted} ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} [θεραπευεται]{.greek-omitted} [θεραπευετε]{.greek-added} προσδεομενος τινος αυτος διδους πασιν ζωην και πνοην κατα παντα[17:25]{.aside}

εποιησεν [τε]{.greek-omitted} [δε]{.greek-added} εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ει αρα γε [ψηλαφησειαν]{.greek-omitted} [ψηλαφισειεν]{.greek-added} αυτον και ευροιεν και [τοι]{.greek-added} γε ου μακραν απο ενος εκαστου [ημων]{.greek-omitted} [υμων]{.greek-added} υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και [τινες]{.greek-omitted} των καθ υμας ποιητων [τινες]{.greek-added} ειρηκασιν του γαρ και γενος εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν [χρυσω]{.greek-omitted} [χρυσιω]{.greek-added} η [αργυρω]{.greek-omitted} [αργυριω]{.greek-added} η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} πασιν πανταχου μετανοειν[17:30]{.aside}

διοτι εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω ωρισεν πιστιν παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον ακουσομεθα σου παλιν περι τουτου[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα ιουδαιον ονοματι ακυλαν ποντικον τω γενει προσφατως [εληλυθοτα]{.greek-omitted} [εληλυθωτα]{.greek-added} απο της ιταλιας και πρισκιλλαν γυναικα αυτου δια το τεταχεναι κλαυδιον χωριζεσθαι παντας τους ιουδαιους [εκ]{.greek-omitted} [απο]{.greek-added} της ρωμης προσηλθεν αυτοις[18:2]{.aside}

[και]{.greek-omitted} δια το ομοτεχνον ειναι [και]{.greek-added} εμενεν παρ αυτοις και [ειργαζετο]{.greek-omitted} [ηργαζετο]{.greek-added} ησαν γαρ σκηνοποιοι την τεχνην[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον επειθεν τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και ο τιμοθεος συνειχετο τω [πνευματι]{.greek-abbr} ο παυλος διαμαρτυρομενος τοις ιουδαιοις [ειναι]{.greek-added} τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων [εκτιναξαμενος]{.greek-omitted} [εκτειναξαμενος]{.greek-added} τα ιματια ειπεν προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας εκειθεν [ηλθεν]{.greek-omitted} εις οικιαν τινος ονοματι [τιτου]{.greek-added} ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια [ην]{.greek-omitted} συνο[μο]{.unclear}ρουσα τη συναγωγ[η]{.unclear}[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος επιστευσεν τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} [επιστευον]{.greek-omitted} [επιστευσαν]{.greek-added} και εβαπτιζοντο[18:8]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} δι οραματος εν νυκτι τω παυλω μη φοβου αλλα [λαλει]{.greek-omitted} [λαλη]{.greek-added} και μη [σιωπησης]{.greek-omitted} [σιωπισης]{.greek-added}[18:9]{.aside}

διοτι εγω ειμι μετα σου και ουδεις επιθησεται σοι του κακωσαι σε διοτι λαος εστιν μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

εκαθισεν τε ενιαυτον και μηνας εξ διδασκων εν αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της αχαιας [κατεπεστησαν]{.greek-omitted} [κατεστησαν]{.greek-added} [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον [αναπειθει]{.greek-added} ουτος [αναπειθει]{.greek-omitted} τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν ουν ην αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν ηνεσχομην υμων[18:14]{.aside}

ει δε [ζητημα]{.greek-omitted} [ζητηματα]{.greek-added} [εστιν]{.greek-omitted} [εισιν]{.greek-added} περι λογου και ονοματων και νομου του καθ υμας [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και [απηλασεν]{.greek-omitted} [απειλασεν]{.greek-added} αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι [δε]{.greek-omitted} [τε]{.greek-added} παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω γαλλιωνι εμελλεν[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας [κειραμενος]{.greek-omitted} [κηραμενος]{.greek-added} [εν]{.greek-added} [κεγχρεαις]{.greek-added} την κεφαλην [εν]{.greek-omitted} [κεγχρεαις]{.greek-omitted} ειχεν γαρ ευχην[18:18]{.aside}

[κατηντησεν]{.greek-omitted} [κατηντησαν]{.greek-added} δε εις εφεσον [και]{.greek-omitted} [κακει]{.greek-added} [εκεινους]{.greek-omitted} [κατελιπεν]{.greek-omitted} [κατελειπεν]{.greek-added} [αυτου]{.greek-omitted} [αυτους]{.greek-added} αυτος δε εισελθων εις την συναγωγην [διελεχθη]{.greek-omitted} [διελεγετο]{.greek-added} τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε αυτων επι [πλειονα]{.greek-omitted} [πλειωνα]{.greek-added} χρονον μειναι παρ αυτοις ουκ επενευσεν[18:20]{.aside}

αλλ απεταξατο αυτοις ειπων δει με παντως την εορτην [την]{.greek-omitted} ερχομενην ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

και κατελθων εις καισαρειαν αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα εξηλθεν διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων [παντας]{.greek-omitted} τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον [του]{.greek-omitted} [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-abbr} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος [τε]{.greek-omitted} ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε αυτου [πρισκιλλα]{.greek-added} [και]{.greek-added} ακυλας [και]{.greek-omitted} [πρισκιλλα]{.greek-omitted} προσελαβοντο αυτον και ακριβεστερον αυτω εξεθεντο την [οδον]{.greek-added} του [θεου]{.greek-abbr} [οδον]{.greek-omitted}[18:26]{.aside}

βουλομενου δε αυτου διελθειν εις την αχαιαν προτρεψαμενοι οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος [συνεβαλετο]{.greek-omitted} [συνεβαλλετο]{.greek-added} πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπιστευκοσι]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω τον απολλω ειναι εν κορινθω παυλον διελθοντα τα ανωτερικα μερη [ελθειν]{.greek-omitted} [κατελθειν]{.greek-added} εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

ειπεν προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε ειπον προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

[ο]{.greek-added} [δε]{.greek-added} ειπεν [τε]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} εις τι ουν εβαπτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

ειπεν δε παυλος ιωαννης μεν εβαπτισεν βαπτισμα μετανοιας τω λαω λεγων εις τον ερχομενον μετ αυτον ινα πιστευσωσιν τουτ εστιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας ηλθεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και [προεφητευον]{.greek-omitted} [επροεφητευον]{.greek-added}[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει [δεκαδυο]{.greek-omitted} [δωδεκα]{.greek-added}[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους αποστας απ αυτων [αφωρισεν]{.greek-omitted} [αφορησεν]{.greek-added} τους μαθητας καθ ημεραν [δι]{.greek-added} [διαλεγομενος]{.greek-omitted} [αλεγομενος]{.greek-added} εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι ετη δυο ωστε παντας τους κατοικουντας την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-omitted} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας [εποιει]{.greek-omitted} ο [θεος]{.greek-abbr} [εποιει]{.greek-added} δια των χειρων [του]{.greek-added} παυλου[19:11]{.aside}

ωστε και επι τους ασθενουντας [επιφερεσθαι]{.greek-omitted} [αποφερεσθαι]{.greek-added} απο του χρωτος αυτου σουδαρια η σιμικινθια και [απαλλασσεσθαι]{.greek-omitted} [απαλαττεσθαι]{.greek-added} απ αυτων τας νοσους τα τε [πνευματα]{.greek-abbr} τα πονηρα [εκπορευεσθαι]{.greek-added} [εξερχεσθαι]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted}[19:12]{.aside}

επεχειρησαν δε τινες απο των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους εχοντας τα [πνευματα]{.greek-abbr} τα πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} λεγοντες ορκιζομεν υμας τον [ιησουν]{.greek-abbr} ον [ο]{.greek-omitted} παυλος κηρυσσει[19:13]{.aside}

ησαν δε [τινες]{.greek-omitted} [τινος]{.greek-added} υιοι σκευα ιουδαιου αρχιερεως επτα οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε το [πνευμα]{.greek-abbr} το πονηρον ειπεν τον [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και εφαλλομενος επ αυτους ο [ανθρωπος]{.greek-abbr} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον και κατακυριευσαν αυτων ισχυσεν κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν [εκ]{.greek-omitted} του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον [πασιν]{.greek-omitted} [πασι]{.greek-added} [τοις]{.greek-added} ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} τοις κατοικουσιν την εφεσον και επεπεσεν φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι [τε]{.greek-omitted} [δε]{.greek-added} των πεπιστευκοτων ηρχοντο εξομολογουμενοι και αναγγελλοντες τας πραξεις αυτων[19:18]{.aside}

ικανοι δε των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και [συνεψηφισαν]{.greek-omitted} [συνεψιφησαν]{.greek-added} τας τιμας αυτων και ευρον αργυριου μυριαδας πεντε[19:19]{.aside}

ουτως κατα κρατος ο λογος του [κυριου]{.greek-abbr} ηυξανεν και ισχυεν[19:20]{.aside}

ως δε [επληρωθη]{.greek-omitted} [επληρουν]{.greek-added} ταυτα εθετο ο παυλος εν τω [πνευματι]{.greek-abbr} διελθων την μακεδονιαν και αχαιαν [πορευεσθαι]{.greek-omitted} [πορευθηναι]{.greek-added} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις την μακεδονιαν δυο των διακονουντων αυτω τιμοθεον και εραστον αυτος επεσχεν χρονον εις την ασιαν[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος περι της οδου[19:23]{.aside}

δημητριος γαρ τις ονοματι αργυροκοπος ποιων ναους αργυρους [αρτεμιδος]{.greek-omitted} [αρτεμηδος]{.greek-added} παρειχετο τοις [τεχνιταις]{.greek-omitted} [τεχνηταις]{.greek-added} [εργασιαν]{.greek-omitted} ουκ ολιγην [εργασιαν]{.greek-added}[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας [ειπεν]{.greek-omitted} [ειπειν]{.greek-added} ανδρες [επιστασθε]{.greek-omitted} [οτι]{.greek-omitted} εκ ταυτης [επιστασθε]{.greek-added} της εργασιας η ευπορια [ημων]{.greek-omitted} [υμων]{.greek-added} εστιν[19:25]{.aside}

και θεωρειτε και ακουετε οτι ου μονον εφεσου αλλα σχεδον πασης της ασιας ο παυλος ουτος [πεισας]{.greek-omitted} [πισας]{.greek-added} μετεστησεν ικανον οχλον λεγων οτι ουκ εισιν θεοι οι δια χειρων [[ανθρωπων]{.greek-abbr}]{.greek-added} γινομενοι[19:26]{.aside}

ου μονον δε τουτο κινδυνευει ημιν το μερος εις απελεγμον ελθειν αλλα και το της μεγαλης θεας [αρτεμιδος]{.greek-added} ιερον [αρτεμιδος]{.greek-omitted} [λογισθηναι]{.greek-added} εις [ουθεν]{.greek-omitted} [ουδεν]{.greek-added} [λογισθηναι]{.greek-omitted} μελλειν δε και καθαιρεισθαι την [μεγαλειοτητα]{.greek-omitted} [μεγαλιοτητα]{.greek-added} αυτης ην ολη η ασια και η οικουμενη σεβεται[19:27]{.aside}

ακουσαντες δε και γενομενοι πληρεις θυμου εκραζον λεγοντες μεγαλη η [αρτεμις]{.greek-omitted} [αρτεμης]{.greek-added} εφεσιων[19:28]{.aside}

και επλησθη η πολις [ολη]{.greek-omitted} της συγχυσεως ωρμησαν τε [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} εις το θεατρον συναρπασαντες γαιον και αρισταρχον μακεδονας συνεκδημους παυλου[19:29]{.aside}

του [παυλου]{.greek-added} δε [παυλου]{.greek-omitted} βουλομενου εισελθειν εις τον δημον ουκ ειων αυτον οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες αυτω φιλοι πεμψαντες [αυτω]{.greek-added} [προς]{.greek-omitted} [αυτον]{.greek-omitted} παρεκαλουν μη δουναι εαυτον εις το θεατρον[19:31]{.aside}

αλλοι μεν [ουν]{.greek-omitted} αλλο τι εκραζον ην γαρ η εκκλησια [ολη]{.greek-added} συγκεχυμενη και οι πλειους ουκ [ηδεισαν]{.greek-omitted} [ηδησαν]{.greek-added} τινος ενεκεν συνεληλυθεισαν[19:32]{.aside}

εκ δε του οχλου προεβιβασαν αλεξανδρον [προβαλοντων]{.greek-omitted} [προβαλλοντων]{.greek-added} αυτον των ιουδαιων ο [δε]{.greek-omitted} [ουν]{.greek-added} αλεξανδρος κατασεισας την χειρα ηθελεν [απολογεισθαι]{.greek-omitted} [απολογισασθαι]{.greek-added} τω δημω[19:33]{.aside}

[επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} [δε]{.greek-omitted} οτι ιουδαιος εστιν φωνη εγενετο μια εκ παντων ως επι ωρας δυο κραζοντων μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλας δε ο γραμματευς τον οχλον φησιν ανδρες [ε]{.greek-added} [εφεσιοι]{.greek-omitted} [φεσιοι]{.greek-added} τις γαρ εστιν [ανθρωπος]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} ος ου [γινωσκει]{.greek-omitted} [γινωσκη]{.greek-added} την εφεσιων πολιν νεωκορον ουσαν της μεγαλης [θεας]{.greek-omitted} αρτεμιδος και του διοπετους[19:35]{.aside}

αναντιρρητων ουν οντων τουτων δεον εστιν υμας κατεσταλμενους υπαρχειν και μηδεν προπετες πρασσειν[19:36]{.aside}

ηγαγετε γαρ τους ανδρας τουτους ουτε ιεροσυλους ουτε βλασφημουντας την [θεον]{.greek-omitted} [θεαν]{.greek-added} υμων[19:37]{.aside}

ει μεν ουν δημητριος και οι συν αυτω τεχνιται [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν εγκαλειτωσαν αλληλοις[19:38]{.aside}

ει δε τι [περι]{.greek-omitted} [ετερων]{.greek-omitted} [περετερων]{.greek-added} [επιζητειτε]{.greek-omitted} [ζητειτε]{.greek-added} εν [τη]{.greek-omitted} [τω]{.greek-added} [εννομω]{.greek-omitted} [νομω]{.greek-added} εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι της σημερον μηδενος αιτιου υπαρχοντος περι ου [ου]{.greek-omitted} [δυνησομεθα]{.greek-omitted} [δυνησωμεθα]{.greek-added} [δουναι]{.greek-omitted} [αποδουναι]{.greek-added} λογον [περι]{.greek-added} της συστροφης ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσεν]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον [θορυβον]{.greek-omitted} [θωρυβον]{.greek-added} προσκαλεσαμενος ο παυλος τους μαθητας [και]{.greek-omitted} ασπασαμενος εξηλθεν πορευθηναι εις [την]{.greek-omitted} μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας τε μηνας τρεις γενομενης αυτω επιβουλης υπο των ιουδαιων μελλοντι αναγεσθαι εις την συριαν εγενετο γνωμη του [υποστρεφειν]{.greek-omitted} [υποστρεφαι]{.greek-added} δια μακεδονιας[20:3]{.aside}

[συνειπετο]{.greek-omitted} [συνηπετο]{.greek-added} δε αυτω αχρι της ασιας [σωπατρος]{.greek-omitted} [σωσιπατρος]{.greek-added} βεροιαιος [θεσσαλονικεων]{.greek-omitted} [θεσσαλονικαιων]{.greek-added} [δε]{.greek-omitted} αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος ασιανοι δε τυχικος και [τροφιμος]{.greek-omitted} [τροφημος]{.greek-added}[20:4]{.aside}

ουτοι προσελθοντες εμενον ημας εν τρωαδι[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και [ηλθομεν]{.greek-omitted} [ηλθωμεν]{.greek-added} προς αυτους εις την τρωαδα αχρι [ημερων]{.greek-omitted} [ημερας]{.greek-added} πεντε ου διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων των μαθητων κλασαι αρτον ο παυλος διελεγετο αυτοις μελλων εξιεναι τη επαυριον παρετεινεν τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε λαμπαδες ικαναι εν τω υπερωω ου ημεν συνηγμενοι[20:8]{.aside}

καθημενος δε τις νεανιας ονοματι ευτυχος επι της θυριδος καταφερομενος υπνω βαθει διαλεγομενου του παυλου επι πλειον κατενεχθεις απο του υπνου επεσεν απο του τριστεγου κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και συμπεριλαβων ειπεν μη [θορυβεισθε]{.greek-omitted} [θωρυβεισθε]{.greek-added} η γαρ ψυχη αυτου εν αυτω εστιν[20:10]{.aside}

αναβας δε και κλασας αρτον και γευσαμενος εφ ικανον τε ομιλησας [αχρι]{.greek-omitted} [αχρις]{.greek-added} αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον δε τον παιδα ζωντα και παρεκληθησαν ου μετριως[20:12]{.aside}

ημεις δε προσελθοντες επι το πλοιον ανηχθημεν [εις]{.greek-omitted} [επι]{.greek-added} την ασσον εκειθεν μελλοντες [αναλαμβανειν]{.greek-omitted} [αναλαβειν]{.greek-added} τον παυλον [ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ [διατεταγμενος]{.greek-added} ην [διατεταγμενος]{.greek-omitted} μελλων αυτος πεζευειν[20:13]{.aside}

ως δε συνεβαλεν ημιν εις την ασσον αναλαβοντες αυτον ηλθομεν [εις]{.greek-omitted} [μιτυληνην]{.greek-omitted}[20:14]{.aside}

[κακειθεν]{.greek-omitted} [αποπλευσαντες]{.greek-omitted} [τη]{.greek-omitted} [επιουση]{.greek-omitted} [κατηντησαμεν]{.greek-omitted} [αντικρυ]{.greek-omitted} [αντικρυς]{.greek-added} χιου [τη]{.greek-omitted} [δε]{.greek-omitted} [ετερα]{.greek-omitted} [παρεβαλομεν]{.greek-omitted} εις σαμον και [μειναντες]{.greek-omitted} [μηναντες]{.greek-added} εν [τρωγυλλιω]{.greek-omitted} [τρωγγυλιω]{.greek-added} τη εχομενη ηλθομεν εις [μιλητον]{.greek-omitted} [μηλητον]{.greek-added}[20:15]{.aside}

[εκρινεν]{.greek-omitted} [κεκρικεν]{.greek-added} γαρ ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια εσπευδεν γαρ ει δυνατον ην αυτω την ημεραν της [πεντηκοστης]{.greek-omitted} [πεντικοστης]{.greek-added} γενεσθαι εις [ιεροσολυμα]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added}[20:16]{.aside}

απο δε της [μιλητου]{.greek-omitted} [μηλητου]{.greek-added} πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον ειπεν αυτοις υμεις επιστασθε απο πρωτης ημερας αφ ης επεβην εις την ασιαν πως μεθ υμων τον παντα χρονον εγενομην[20:18]{.aside}

δουλευων τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και πολλων δακρυων και πειρασμων των συμβαντων μοι εν ταις επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων του μη αναγγειλαι υμιν και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

[διαμαρτυρομενος]{.greek-omitted} [διαμαρτυρωμενος]{.greek-added} ιουδαιοις τε και ελλησιν την εις [τον]{.greek-omitted} [θεον]{.greek-abbr} μετανοιαν και πιστιν την εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr} [[χριστον]{.greek-abbr}]{.greek-added}[20:21]{.aside}

και νυν ιδου [δεδεμενος]{.greek-added} εγω [δεδεμενος]{.greek-omitted} τω [πνευματι]{.greek-abbr} πορευομαι εις [ιερουσαλημ]{.greek-abbr} τα εν αυτη συναντησοντα μοι μη ειδως[20:22]{.aside}

πλην οτι το [πνευμα]{.greek-abbr} το αγιον κατα πολιν διαμαρτυρεται [λεγον]{.greek-omitted} οτι δεσμα [με]{.greek-omitted} και θλιψεις [με]{.greek-added} μενουσιν[20:23]{.aside}

αλλ ουδενος [τουτων]{.greek-added} λογον ποιουμαι ουδε εχω την ψυχην [μου]{.greek-omitted} τιμιαν [εμαυτω]{.greek-omitted} [εαυτω]{.greek-added} [ως]{.greek-omitted} [ωστε]{.greek-added} τελειωσαι τον δρομον μου [μετα]{.greek-omitted} [χαρας]{.greek-omitted} και την διακονιαν ην ελαβον παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι οψεσθε το προσωπον μου υμεις παντες εν οις διηλθον [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

διοτι [μαρτυρομαι]{.greek-omitted} [μαρτυρωμαι]{.greek-added} υμιν εν τη σημερον ημερα οτι καθαρος εγω απο του αιματος παντων[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι [υμιν]{.greek-omitted} πασαν την βουλην του [θεου]{.greek-abbr}[20:27]{.aside}

προσεχετε ουν εαυτοις και παντι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επισκοπους [ποιμαινειν]{.greek-omitted} [ποιμενειν]{.greek-added} την εκκλησιαν του [κυριου]{.greek-abbr} και [θεου]{.greek-abbr} ην περιεποιησατο δια του ιδιου αιματος[20:28]{.aside}

εγω γαρ οιδα τουτο οτι εισελευσονται μετα την [αφιξιν]{.greek-omitted} [αφηξιν]{.greek-added} μου λυκοι βαρεις εις υμας μη φειδομενοι του ποιμνιου[20:29]{.aside}

και εξ υμων αυτων αναστησονται ανδρες λαλουντες διεστραμμενα του αποσπαν τους μαθητας οπισω αυτων[20:30]{.aside}

διο γρηγορειτε μνημονευοντες οτι τριετιαν νυκτα και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον [υμων]{.greek-added}[20:31]{.aside}

και τα νυν παρατιθεμαι υμας αδελφοι τω [θεω]{.greek-omitted} [[κυριω]{.greek-abbr}]{.greek-added} και τω λογω της χαριτος αυτου τω δυναμενω εποικοδομησαι και δουναι υμιν κληρονομιαν εν τοις ηγιασμενοις πασιν[20:32]{.aside}

αργυριου η χρυσιου η ιματισμου [ουδενος]{.greek-omitted} [ουθενος]{.greek-added} επεθυμησα[20:33]{.aside}

αυτοι γινωσκετε οτι ταις χρειαις μου και τοις ουσιν μετ εμου υπηρετησαν αι χειρες αυται[20:34]{.aside}

παντα υπεδειξα υμιν οτι ουτως κοπιωντας δει αντιλαμβανεσθαι των ασθενουντων μνημονευειν τε των λογων του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} οτι αυτος ειπεν μακαριον εστιν μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα [γονατα]{.greek-omitted} [γωνατα]{.greek-added} [αυτου]{.greek-omitted} συν πασιν αυτοις προσηυξατο[20:36]{.aside}

ικανος δε [κλαυθμος]{.greek-added} εγενετο [κλαυθμος]{.greek-omitted} παντων και επιπεσοντες επι τον τραχηλον του παυλου κατεφιλουν αυτον[20:37]{.aside}

[οδυνωμενοι]{.greek-omitted} [ωδυνομενοι]{.greek-added} μαλιστα επι τω λογω ω ειρηκει οτι ουκετι μελλουσιν το προσωπον αυτου θεωρειν προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας αποσπασθεντας απ αυτων ευθυδρομησαντες ηλθομεν εις την [κων]{.greek-omitted} [κω]{.greek-added} τη δε εξης εις την ροδον κακειθεν εις παταρα[21:1]{.aside}

και ευροντες πλοιον διαπερων εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

αναφανεντες δε την κυπρον και [καταλιποντες]{.greek-omitted} [καταλειποντες]{.greek-added} αυτην ευωνυμον επλεομεν εις συριαν και [κατηχθημεν]{.greek-omitted} [κατηλθομεν]{.greek-added} εις τυρον εκεισε γαρ [ην]{.greek-omitted} το πλοιον [ην]{.greek-added} αποφορτιζομενον τον γομον[21:3]{.aside}

και ανευροντες μαθητας επεμειναμεν αυτου ημερας επτα οιτινες τω παυλω ελεγον δια του [πνευματος]{.greek-abbr} μη αναβαινειν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added}[21:4]{.aside}

οτε δε εγενετο ημας [εξαρτισαι]{.greek-omitted} [εξαρτησαι]{.greek-added} τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και [τ]{.unclear}εκνοις εως εξω της πολεως και θεντες τα [γονατα]{.greek-omitted} [γωνατα]{.greek-added} [επι]{.greek-omitted} [τον]{.greek-omitted} [αιγιαλον]{.greek-omitted} [προσηυξαμεθα]{.greek-omitted} [προσευξαμεθα]{.greek-added}[21:5]{.aside}

και [ασπασαμενοι]{.greek-omitted} [απασαμενοι]{.greek-added} αλληλους [επεβημεν]{.greek-omitted} [ενεβημεν]{.greek-added} εις το πλοιον εκεινοι δε υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν διανυσαντες απο τυρου κατηντησαμεν εις πτολεμαιδα και ασπασαμενοι τους αδελφους εμειναμεν ημεραν μιαν [παρ]{.greek-omitted} [συν]{.greek-added} αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες [οι]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [ηλθον]{.greek-omitted} [ηλθομεν]{.greek-added} εις καισαρειαν και εισελθοντες εις τον οικον φιλιππου του ευαγγελιστου οντος εκ των επτα εμειναμεν παρ αυτω[21:8]{.aside}

του[τ]{.unclear}ω δε ησαν θυγατερες [τεσσαρες]{.greek-added} παρθενοι [τεσσαρες]{.greek-omitted} προφητευουσαι[21:9]{.aside}

επιμενοντων δε [ημων]{.greek-omitted} ημερας πλειους κατηλθεν τις απο της ιουδαιας προφητης ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρας την ζωνην του παυλου δησας τε αυτου τους ποδας και τας χειρας ειπεν ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τον ανδρα ου εστιν η ζωνη αυτη ουτως δησουσιν εν [ιερουσαλημ]{.greek-abbr} οι ιουδαιοι και παραδωσουσιν εις χειρας εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκαλουμεν ημεις τε και οι εντοπιοι του μη αναβαινειν αυτον εις [ιερουσαλημ]{.greek-abbr}[21:12]{.aside}

απεκριθη τε ο παυλος [και]{.greek-added} [ειπεν]{.greek-added} τι ποιειτε κλαιοντες και συνθρυπτοντες μου την καρδιαν εγω γαρ ου μονον δεθηναι αλλα και αποθανειν [εις]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} ετοιμως εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου ησυχασαμεν ειποντες [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} το θελημα [του]{.greek-omitted} [κυριου]{.greek-omitted} γενεσθω[21:14]{.aside}

μετα δε τας ημερας ταυτας επισκευασαμενοι [ανεβαινομεν]{.greek-omitted} [ανεβημεν]{.greek-added} εις [ιερουσαλημ]{.greek-abbr}[21:15]{.aside}

συνηλθον δε και των [μαθητων]{.greek-omitted} απο καισαρειας συν ημιν αγοντες παρ ω ξενισθωμεν μνασωνι τινι κυπριω αρχαιω [μαθητη]{.greek-omitted} [μαθητι]{.greek-added}[21:16]{.aside}

γενομενων δε ημων εις ιεροσολυμα [ασμενως]{.greek-omitted} [ασπασαμενοι]{.greek-added} [εδεξαντο]{.greek-omitted} [απεδεξαντο]{.greek-added} ημας οι αδελφοι[21:17]{.aside}

τη δε επιουση εισηει ο παυλος συν ημιν προς ιακωβον παντες τε παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος αυτους εξηγειτο καθ εν εκαστον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις εθνεσιν δια της διακονιας αυτου[21:19]{.aside}

οι δε [ακουσαντες]{.greek-omitted} [ακουοντες]{.greek-added} εδοξαζον τον [κυριον]{.greek-omitted} [ειποντες]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} [ειπαν]{.greek-added} [τε]{.greek-added} αυτω θεωρεις αδελφε [μυριαδες]{.greek-added} ποσαι [μυριαδες]{.greek-omitted} εισιν [των]{.greek-added} ιουδαιων των πεπιστευκοτων και παντες ζηλωται του νομου υπαρχουσιν[21:20]{.aside}

κατηχηθησαν δε περι σου οτι αποστασιαν [διδασκεις]{.greek-omitted} [διδασκης]{.greek-added} απο μωυσεως τους κατα τα εθνη [παντας]{.greek-omitted} [παντα]{.greek-added} ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} περιπατειν[21:21]{.aside}

τι ουν εστιν παντως δει [συνελθειν]{.greek-added} πληθος [συνελθειν]{.greek-omitted} ακουσονται γαρ οτι εληλυθας[21:22]{.aside}

τουτο ουν ποιησον ο σοι [λεγομεν]{.greek-omitted} [λεγωμεν]{.greek-added} εισιν ημιν ανδρες τεσσαρες ευχην εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων [αγνισθητι]{.greek-omitted} [αγνησθητι]{.greek-added} συν αυτοις και δαπανησον επ [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ινα [ξυρησωνται]{.greek-omitted} [ξυρησονται]{.greek-added} την κεφαλην και [γνωσιν]{.greek-omitted} [γνωσονται]{.greek-added} παντες οτι ων [κατηχηνται]{.greek-omitted} [κατηχεινται]{.greek-added} περι σου ουδεν εστιν αλλα [στοιχεις]{.greek-omitted} [στυχεις]{.greek-added} και αυτ[ος]{.unclear} [φυλασσων]{.greek-added} τον νομ[ον]{.unclear} [φυλασσων]{.greek-omitted}[21:24]{.aside}

[π]{.unclear}ερι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες μηδεν [τοιουτον]{.greek-omitted} [τοιουτο]{.greek-added} τηρειν αυτους [ει]{.greek-omitted} [η]{.greek-added} μη φυλασσεσθαι αυτους το τε ειδωλοθυτον και το αιμα και πνικτον και πορνειαν[21:25]{.aside}

τοτε ο παυλος παραλαβων τους ανδρας τη εχομενη ημερα συν αυτοις [αγνισθεις]{.greek-omitted} [αγνησθεις]{.greek-added} εισηει εις το ιερον διαγγελλων την εκπληρωσιν των ημερων του [αγνισμου]{.greek-omitted} [αγνησμου]{.greek-added} εως ου [προσηνεχθη]{.greek-omitted} [προσενεχθη]{.greek-added} υπερ ενος εκαστου αυτων η προσφορα[21:26]{.aside}

ως δε εμελλον αι επτα ημεραι συντελεισθαι οι απο της ασιας ιουδαιοι θεασαμενοι αυτον εν τω ιερω συνεχεον παντα τον οχλον και επεβαλον [επ]{.greek-added} [αυτον]{.greek-added} τας χειρας [επ]{.greek-omitted} [αυτον]{.greek-omitted}[21:27]{.aside}

[κραζοντες]{.greek-omitted} [λεγοντες]{.greek-added} ανδρες [ισραηλιται]{.greek-omitted} [ισραηλειται]{.greek-added} βοηθειτε ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου τουτου παντας [πανταχου]{.greek-omitted} [πανταχη]{.greek-added} διδασκων ετι τε και ελληνας εισηγαγεν εις το ιερον και κεκοινωκεν τον αγιον τοπον τουτον[21:28]{.aside}

ησαν γαρ [εωρακοτες]{.greek-omitted} [προεωρακωτες]{.greek-added} [τροφιμον]{.greek-omitted} [τροφημον]{.greek-added} τον εφεσιον εν τη πολει συν αυτω ον ενομιζον οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

εκινηθη τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του παυλου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

ζητουντων δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της σπειρης οτι ολη συγκεχυται [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και εκατονταρχους κατεδραμεν επ αυτους οι δε ιδοντες τον χιλιαρχον και τους στρατιωτας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

εγγισας δε ο χιλιαρχος επελαβετο αυτου και εκελευσεν δεθηναι αλυσεσιν δυσιν [και]{.greek-omitted} [επυνθανετο]{.greek-omitted} [τις]{.greek-omitted} [αν]{.greek-omitted} [ειη]{.greek-omitted} [και]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [πεποιηκως]{.greek-omitted}[21:33]{.aside}

αλλοι δε αλλο τι [εβοων]{.greek-omitted} [επεφωνουν]{.greek-added} εν τω οχλω μη [δυναμενος]{.greek-omitted} [δυναμενου]{.greek-added} δε [αυτου]{.greek-added} γνωναι το ασφαλες δια τον [θορυβον]{.greek-omitted} [θωρυβον]{.greek-added} εκελευσεν αγεσθαι αυτον εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον [υπο]{.greek-omitted} [των]{.greek-omitted} στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

ηκολουθει γαρ το πληθος του λαου [κραζον]{.greek-omitted} [κραζοντες]{.greek-added} αιρε αυτον[21:36]{.aside}

μελλων [τε]{.greek-omitted} [δε]{.greek-added} εισαγεσθαι εις την παρεμβολην ο παυλος λεγει τω χιλιαρχω ει εξεστιν μοι ειπειν [τι]{.greek-added} προς σε ο δε εφη ελληνιστι γινωσκεις[21:37]{.aside}

[ουκ]{.greek-omitted} [ου]{.greek-added} [κ]{.greek-added} αρα συ ει ο αιγυπτιος ο προ [μικρου]{.greek-added} [τουτων]{.greek-omitted} [των]{.greek-omitted} [ημερων]{.greek-omitted} αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

ειπεν δε ο παυλος εγω [ανθρωπος]{.greek-abbr} [μεν]{.greek-omitted} ειμι ιουδαιος ταρσευς της κιλικιας ουκ [ασημου]{.greek-omitted} [ασιμου]{.greek-added} πολεως πολιτης δεομαι [δε]{.greek-omitted} σου επιτρεψον μοι λαλησαι προς τον λαον[21:39]{.aside}

επιτρεψαντος δε αυτου ο παυλος [εστως]{.greek-omitted} επι των αναβαθμων κατεσεισεν τη χειρι [τω]{.greek-omitted} [λαω]{.greek-omitted} [τον]{.greek-added} [λαον]{.greek-added} πολλης δε [γενομενης]{.greek-added} σιγης [εφωνησεν]{.greek-added} [γενομενης]{.greek-omitted} [προσεφωνει]{.greek-omitted} τη εβραιδι διαλεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς υμας νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη εβραιδι διαλεκτω προσεφωνει αυτοις μαλλον παρεσχον ησυχιαν και φησιν[22:2]{.aside}

εγω μεν ειμι ανηρ ιουδαιος γεγεννημενος [δε]{.greek-added} εν ταρσω της κιλικιας ανατεθραμμενος δε εν τη πολει ταυτη παρα τους ποδας [του]{.greek-added} γαμαλιηλ πεπαιδευμενος [δε]{.greek-added} κατα ακριβειαν [του]{.greek-omitted} [τω]{.greek-added} [πατρωου]{.greek-omitted} [πατρωω]{.greek-added} [νομου]{.greek-omitted} [νομω]{.greek-added} ζηλωτης υπαρχων του [θεου]{.greek-abbr} καθως παντες υμεις εστε σημερον[22:3]{.aside}

ος ταυτην την οδον εδιωξα [αχρι]{.greek-omitted} [εως]{.greek-added} θανατου δεσμευων και παραδιδους εις φυλακας ανδρας τε και γυναικας[22:4]{.aside}

ως και ο αρχιερευς μαρτυρει μοι και [παν]{.greek-omitted} [απαν]{.greek-added} το πρεσβυτεριον παρ ων και επιστολας δεξαμενος προς τους αδελφους εις δαμασκον επορευομην αξων και τους εκεισε οντας δεδεμενους εις ιερουσαλημ ινα [τιμωρηθωσιν]{.greek-omitted} [τιμωριθωσιν]{.greek-added}[22:5]{.aside}

εγενετο δε μοι πορευομενω και εγγιζοντι τη δαμασκω περι μεσημβριαν εξαιφνης εκ του [ουρανου]{.greek-omitted} [[ουνου]{.greek-abbr}]{.greek-added} [περιαστραψαι]{.greek-omitted} [περιηστραψεν]{.greek-added} φως ικανον περι εμε[22:6]{.aside}

[επεσα]{.greek-omitted} [επεσον]{.greek-added} τε εις το εδαφος και ηκουσα φωνης λεγουσης μοι σαουλ σαουλ τι με [διωκεις]{.greek-omitted} [διωκης]{.greek-added}[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} ειπεν τε προς με εγω ειμι [ιησους]{.greek-abbr} ο ναζωραιος ον συ διωκεις[22:8]{.aside}

οι δε συν εμοι οντες το μεν φως εθεασαντο [και]{.greek-omitted} [εμφοβοι]{.greek-omitted} [εγενοντο]{.greek-omitted} την δε φωνην ουκ [ηκουσαν]{.greek-omitted} [ηκουον]{.greek-added} του λαλουντος μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν προς με αναστας πορευου εις δαμασκον κακει σοι [λαληθησεται]{.greek-omitted} [λαληθη]{.greek-added} [σεται]{.greek-added} περι παντων ων τετακται σοι ποιησαι[22:10]{.aside}

ως δε ουκ [ενεβλεπον]{.greek-omitted} [εβλεπον]{.greek-added} απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι ηλθον εις δαμασκον[22:11]{.aside}

ανανιας δε τις ανηρ [ευσεβης]{.greek-omitted} [ευλαβης]{.greek-added} κατα τον νομον μαρτυρουμενος υπο παντων των κατοικουντων ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας ειπεν μοι σαουλ αδελφε αναβλεψον καγω αυτη τη ωρα ανεβλεψα εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [προεχειρισατο]{.greek-omitted} [προεχειρησατο]{.greek-added} σε γνωναι το θελημα αυτου και ιδειν τον δικαιον και ακουσαι φωνην εκ [του]{.greek-omitted} στοματος αυτου[22:14]{.aside}

οτι εση μαρτυς αυτω προς παντας [ανθρωπους]{.greek-abbr} ων εωρακας και ηκουσας[22:15]{.aside}

και νυν τι [μελλεις]{.greek-omitted} [μελλης]{.greek-added} αναστας [βαπτισαι]{.greek-omitted} [βαπτισε]{.greek-added} και [απολουσαι]{.greek-omitted} [απολουσε]{.greek-added} τας αμαρτιας σου επικαλεσαμενος το ονομα του [κυριου]{.greek-abbr} [[ιησου]{.greek-abbr}]{.greek-added}[22:16]{.aside}

εγενετο [δε]{.corr} μοι υποστρεψαντι εις [ιερουσαλημ]{.greek-abbr} και προσευχομενου μου εν τω ιερω γενεσθαι με εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον και εξελθε εν ταχει εξ ιερουσαλημ διοτι ου παραδεξονται σου [την]{.greek-omitted} μαρτυριαν περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω ημην φυλακιζων και δερων κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε εξεχειτο το αιμα στεφανου του μαρτυρος σου και αυτος ημην εφεστως και συνευδοκων τη αναιρεσει αυτου [και]{.greek-added} φυλασσων τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και ειπεν προς με πορευου οτι εγω εις εθνη μακραν εξαποστελω σε[22:21]{.aside}

ηκουον δε αυτου αχρι τουτου του λογου και επηραν την φωνην αυτων λεγοντες αιρε απο της γης τον τοιουτον ου γαρ καθηκεν αυτον ζην[22:22]{.aside}

[κραζοντων]{.greek-omitted} [κραυγαζοντων]{.greek-added} δε αυτων και [ριπτουντων]{.greek-omitted} [ριπτοντων]{.greek-added} τα ιματια και [κονιορτον]{.greek-omitted} [κονιορτων]{.greek-added} βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν [αυτον]{.greek-omitted} ο χιλιαρχος [αγεσθαι]{.greek-omitted} [εισαγεσθαι]{.greek-added} [αυτον]{.greek-added} εις την παρεμβολην [ειπων]{.greek-omitted} [ειπεν]{.greek-added} [δε]{.greek-added} μαστιξιν ανεταζεσθαι αυτον ινα επιγνω δι ην αιτιαν ουτως επεφωνουν αυτω[22:24]{.aside}

ως δε προετεινεν αυτον τοις ιμασιν ειπεν προς τον [εστωτα]{.greek-omitted} [εφεστωτα]{.greek-added} [εκατονταρχον]{.greek-omitted} [εκατον]{.greek-added} [ταρχον]{.greek-added} ο παυλος ει [ανθρωπον]{.greek-abbr} ρωμαιον και ακατακριτον εξεστιν υμιν μαστιζειν[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων [απηγγειλεν]{.greek-omitted} τω χιλιαρχω [απηγγειλεν]{.greek-added} λεγων ορα τι [μελλεις]{.greek-omitted} [μελλης]{.greek-added} ποιειν ο γαρ [ανθρωπος]{.greek-omitted} [[ανος]{.greek-abbr}]{.greek-added} ουτος ρωμαιος εστιν[22:26]{.aside}

προσελθων δε ο χιλιαρχος ειπεν αυτω λεγε μοι ει συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκριθη [τε]{.greek-omitted} [δε]{.greek-added} ο χιλιαρχος εγω πολλου κεφαλαιου την πολιτειαν ταυτην [εκτησαμην]{.greek-omitted} [εκτισαμην]{.greek-added} ο δε παυλος εφη εγω δε και γεγεννημαι[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες αυτον ανεταζειν και ο χιλιαρχος δε [εφοβηθη]{.greek-omitted} επιγνους οτι ρωμαιος εστιν [εφοβηθη]{.greek-added} και οτι ην αυτον δεδεκως[22:29]{.aside}

τη δε επαυριον βουλομενος [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} το ασφαλες το τι κατηγορειται [παρα]{.greek-omitted} [υπο]{.greek-added} των ιουδαιων ελυσεν αυτον απο των δεσμων και εκελευσεν [ελθειν]{.greek-omitted} [συνελθειν]{.greek-added} τους αρχιερεις και [ολον]{.greek-omitted} [παν]{.greek-added} το συνεδριον [αυτων]{.greek-omitted} [και]{.greek-omitted} καταγαγων τον παυλον εστησεν εις αυτους[22:30]{.aside}

### Chapter 23

ατενισας δε ο παυλος τω συνεδριω ειπεν ανδρες αδελφοι εγω παση [συνειδησει]{.greek-omitted} [συνειδηση]{.greek-added} αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι ταυτης της ημερας[23:1]{.aside}

ο δε αρχιερευς ανανιας επεταξεν τοις παρεστωσιν αυτω τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον ειπεν τυπτειν σε μελλει ο [θεος]{.greek-abbr} τοιχε κεκονιαμενε και συ καθη κρινων με κατα τον νομον και παρανομων κελευεις με τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες [ειπον]{.greek-omitted} [ειπαν]{.greek-added} τον αρχιερεα του [θεου]{.greek-abbr} λοιδορεις[23:4]{.aside}

εφη τε ο παυλος ουκ ηδειν αδελφοι οτι εστιν αρχιερευς γεγραπται γαρ [οτι]{.greek-added} αρχοντα του λαου σου ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος εστιν σαδδουκαιων το δε ετερον φαρισαιων [εκραξεν]{.greek-omitted} [εκραζεν]{.greek-added} εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμι υιος φαρισαιου περι ελπιδος και αναστασεως νεκρων εγω [κρινομαι]{.greek-omitted} [κρινωμαι]{.greek-added}[23:6]{.aside}

τουτο δε αυτου [λαλησαντος]{.greek-omitted} [ειποντος]{.greek-added} εγενετο στασις των φαρισαιων και εσχισθη το πληθος[23:7]{.aside}

σαδδουκαιοι μεν γαρ λεγουσιν μη ειναι αναστασιν [μηδε]{.greek-omitted} [μητε]{.greek-added} αγγελον μητε πνευμα φαρισαιοι δε ομολογουσιν τα αμφοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και ανασταντες [οι]{.greek-omitted} [τινες]{.greek-added} γραμματεις του μερους των φαρισαιων διεμαχοντο λεγοντες ουδεν κακον ευρισκομεν εν τω [ανθρωπω]{.greek-abbr} [τουτω]{.greek-omitted} [τουτο]{.greek-added} ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω η αγγελος [μη]{.greek-omitted} [θεομαχωμεν]{.greek-omitted}[23:9]{.aside}

πολλης δε γενομενης στασεως ευλαβηθεις ο χιλιαρχος μη διασπασθη ο παυλος υπ αυτων εκελευσεν το στρατευμα καταβηναι και αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση νυκτι επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν θαρσει παυλε ως γαρ διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} [ουτως]{.greek-omitted} [ουτω]{.greek-added} σε δει και εις ρωμην μαρτυρησαι[23:11]{.aside}

γενομενης δε ημερας ποιησαντες [συστροφην]{.greek-added} τινες των ιουδαιων [συστροφην]{.greek-omitted} ανεθεματισαν [εαυτους]{.greek-omitted} [αυτους]{.greek-added} λεγοντες μητε φαγειν μητε πιειν εως ου αποκτεινωσιν τον παυλον[23:12]{.aside}

ησαν δε πλειους τεσσαρακοντα οι ταυτην την [συνωμοσιαν]{.greek-omitted} [συνομοσιαν]{.greek-added} πεποιηκοτες[23:13]{.aside}

οιτινες προσελθοντες τοις αρχιερευσιν και τοις πρεσβυτεροις [ειπον]{.greek-omitted} [ειπαν]{.greek-added} αναθεματι ανεθεματισαμεν εαυτους [μηδενος]{.greek-omitted} [μηθενος]{.greek-added} γευσασθαι εως ου αποκτεινωμεν τον παυλον[23:14]{.aside}

νυν ουν υμεις [εμφανισατε]{.greek-omitted} [εμφανησατε]{.greek-added} τω χιλιαρχω συν τω συνεδριω οπως αυριον [καταγαγει]{.greek-added} αυτον [καταγαγη]{.greek-omitted} προς υμας ως [μελλοντας]{.greek-omitted} [μελλοντα]{.greek-added} διαγινωσκειν ακριβεστερον τα περι αυτου ημεις δε προ του εγγισαι [αυτον]{.greek-omitted} [αυτω]{.greek-added} ετοιμοι εσμεν του ανελειν αυτον[23:15]{.aside}

ακουσας δε ο [υιος]{.greek-abbr} της αδελφης παυλου [το]{.greek-omitted} [την]{.greek-added} [ενεδρον]{.greek-omitted} [ενεδραν]{.greek-added} [και]{.greek-added} παραγενομενος [και]{.greek-omitted} εισελθων εις την παρεμβολην απηγγειλεν τω παυλω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων εφη τον νεανιαν τουτον απαγαγε προς τον χιλιαρχον [εχει]{.greek-omitted} [γαρ]{.greek-omitted} [τι]{.greek-omitted} [απαγγειλαι]{.greek-omitted} [αυτω]{.greek-omitted}[23:17]{.aside}

[ο]{.greek-omitted} [μεν]{.greek-omitted} [ουν]{.greek-omitted} [παραλαβων]{.greek-omitted} [αυτον]{.greek-omitted} [ηγαγεν]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [χιλιαρχον]{.greek-omitted} και φησιν ο δεσμιος παυλος προσκαλεσαμενος με ηρωτησεν τουτον τον νεανιαν αγαγειν προς σε εχοντα τι λαλησαι σοι[23:18]{.aside}

επιλαβομενος δε της χειρος αυτου ο χιλιαρχος και αναχωρησας κατ ιδιαν [επυνθανετο]{.greek-omitted} [επυνθα]{.greek-added} [νετο]{.greek-added} τι εστιν ο εχεις απαγγειλαι μοι[23:19]{.aside}

ειπεν δε οτι [οι]{.greek-omitted} ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον [καταγαγης]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} εις το συνεδριον [καταγαγης]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} ως μελλοντα τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ ουν μη [πεισθης]{.greek-omitted} [πισθεις]{.greek-added} αυτοις ενεδρευουσιν [γαρ]{.greek-omitted} [αυτον]{.greek-omitted} εξ αυτων ανδρες πλειους τεσσαρακοντα οιτινες ανεθεματισαν εαυτους μητε φαγειν μητε πιειν εως ου ανελωσιν αυτον και νυν ετοιμοι εισιν προσδεχομενοι την απο σου επαγγελιαν[23:21]{.aside}

ο μεν ουν χιλιαρχος απελυσεν τον νεανιαν παραγγειλας μηδενι εκλαλησαι οτι ταυτα [ενεφανισας]{.greek-omitted} [ενεφανησας]{.greek-added} προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους [ενοπλους]{.greek-added} οπως πορευθωσιν εως καισαρειας και ιππεις εβδομηκοντα και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

κτηνη τε παραστησαι ινα [επιβιβασαντες]{.greek-omitted} [επιβηβασαντες]{.greek-added} τον παυλον [διασωσωσιν]{.greek-omitted} [διασωσητε]{.greek-added} προς [φηλικα]{.greek-omitted} [φιλικα]{.greek-added} τον ηγεμονα[23:24]{.aside}

γραψας επιστολην περιεχουσαν τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω ηγεμονι [φηλικι]{.greek-omitted} [φιλικι]{.greek-added} χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο των ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι [εξειλομην]{.greek-omitted} [εξειλαμην]{.greek-added} αυτον μαθων οτι ρωμαιος εστιν[23:27]{.aside}

βουλομενος δε [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} την αιτιαν δι ην ενεκαλουν αυτω κατηγαγον [αυτον]{.greek-omitted} εις το συνεδριον αυτων[23:28]{.aside}

ον ευρον εγκαλουμενον περι ζητηματων του νομου αυτων μηδεν [δε]{.greek-added} αξιον θανατου η δεσμων [εχοντα]{.greek-added} εγκλημα [εχοντα]{.greek-omitted}[23:29]{.aside}

[μηνυθεισης]{.greek-omitted} [μηνυθησης]{.greek-added} δε μοι επιβουλης εις τον ανδρα μελλειν εσεσθαι υπο των ιουδαιων εξαυτης επεμψα προς σε παραγγειλας και τοις κατηγοροις λεγειν τα προς αυτον επι σου [ερρωσο]{.greek-omitted} [ερρωθε]{.greek-added}[23:30]{.aside}

οι μεν ουν στρατιωται κατα το διατεταγμενον αυτοις αναλαβοντες τον παυλον ηγαγον δια [της]{.greek-omitted} νυκτος εις την αντιπατριδα[23:31]{.aside}

τη δε επαυριον εασαντες τους ιππεις [πορευεσθαι]{.greek-omitted} [απερχεσθαι]{.greek-added} συν αυτω υπεστρεψαν εις την παρεμβολην[23:32]{.aside}

οιτινες εισελθοντες εις την καισαρειαν και [αναδοντες]{.greek-omitted} [επιδοντες]{.greek-added} την επιστολην τω ηγεμονι παρεστησαν και τον παυλον αυτω[23:33]{.aside}

αναγνους δε ο ηγεμων και επερωτησας εκ ποιας επαρχιας εστιν και [πυθομενος]{.greek-omitted} [πειθομενος]{.greek-added} οτι απο κιλικιας[23:34]{.aside}

διακουσομαι σου εφη οταν και οι κατηγοροι σου [παραγενωνται]{.greek-omitted} [παραγενονται]{.greek-added} [κελευσας]{.greek-added} [δε]{.greek-added} [εκελευσεν]{.greek-omitted} [τε]{.greek-omitted} [αυτον]{.greek-omitted} εν τω [πραιτωριω]{.greek-omitted} [πρετωριω]{.greek-added} [του]{.greek-added} ηρωδου φυλασσεσθαι [αυτον]{.greek-added}[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη ο αρχιερευς ανανιας μετα [των]{.greek-omitted} πρεσβυτερων [τινων]{.greek-added} και ρητορος τερτυλλου τινος οιτινες [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} τω ηγεμονι κατα του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο κατηγορειν ο τερτυλλος λεγων πολλης ειρηνης τυγχανοντες δια σου και [κατορθωματων]{.greek-omitted} [διορθωματων]{.greek-added} γινομενων τω εθνει τουτω δια της σης προνοιας[24:2]{.aside}

[παντη]{.greek-omitted} [παντι]{.greek-added} τε και πανταχου αποδεχομεθα κρατιστε [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} μετα πασης [ευχαριστιας]{.greek-omitted} [ευχαριστειας]{.greek-added}[24:3]{.aside}

ινα δε μη επι πλειον σε [εγκοπτω]{.greek-omitted} [εγκοτω]{.greek-added} παρακαλω ακουσαι σε ημων συντομως τη ση [επιεικεια]{.greek-omitted} [επιεικια]{.greek-added}[24:4]{.aside}

ευροντες γαρ τον ανδρα τουτον λοιμον και κινουντα [πασιν]{.greek-added} στασιν [πασιν]{.greek-omitted} τοις ιουδαιοις [τοις]{.greek-omitted} κατα την οικουμενην πρωτοστατην τε της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον [επειρασεν]{.greek-omitted} [επειρασε]{.greek-added} βεβηλωσαι ον και εκρατησαμεν[24:6]{.aside}

παρ ου [δυνηση]{.greek-omitted} [δυνησει]{.greek-added} αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

συνεπεθεντο δε και οι ιουδαιοι φασκοντες ταυτα ουτως εχειν[24:9]{.aside}

απεκριθη δε ο παυλος νευσαντος αυτω του ηγεμονος λεγειν εκ πολλων ετων οντα σε κριτην τω εθνει τουτω επισταμενος ευθυμοτερον τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} οτι ου πλειους εισιν μοι ημεραι δεκαδυο αφ ης ανεβην προσκυνησων [εν]{.greek-omitted} [εις]{.greek-added} [ιερουσαλημ]{.greek-abbr}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η [επισυστασιν]{.greek-omitted} [επιστασιν]{.greek-added} ποιουντα οχλου ουτε εν ταις συναγωγαις ουτε κατα την πολιν [́]{.greek-added}[24:12]{.aside}

ουτε παραστησαι [με]{.greek-omitted} δυνανται [σοι]{.greek-added} περι ων νυν κατηγορουσιν μου[24:13]{.aside}

ομολογω δε τουτο σοι οτι κατα την οδον ην λεγουσιν αιρεσιν ουτως λατρευω τω πατρωω [θεω]{.greek-abbr} πιστευων πασιν τοις κατα τον νομον και τοις προφηταις γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι προσδεχονται αναστασιν μελλειν εσεσθαι [νεκρων]{.greek-omitted} δικαιων τε και αδικων[24:15]{.aside}

εν τουτω [δε]{.greek-omitted} [και]{.greek-added} αυτος ασκω απροσκοπον συνειδησιν [εχων]{.greek-omitted} [εχειν]{.greek-added} προς τον [θεον]{.greek-abbr} και τους [ανθρωπους]{.greek-abbr} δια παντος[24:16]{.aside}

δι ετων δε πλειονων παρεγενομην ελεημοσυνας ποιησων εις το εθνος μου και προσφορας[24:17]{.aside}

εν οις ευρον με [ηγνισμενον]{.greek-omitted} [ηγνησμενον]{.greek-added} εν τω ιερω ου μετα οχλου ουδε μετα [θορυβου]{.greek-omitted} [θωρυβου]{.greek-added} [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [δε]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιοι]{.greek-added} ους δει επι σου παρειναι και κατηγορειν ει τι εχοιεν προς με[24:19]{.aside}

η αυτοι ουτοι ειπατωσαν τι ευρον εν εμοι αδικημα σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας [φωνης]{.greek-added} ταυτης [φωνης]{.greek-omitted} ης [εκραξα]{.greek-omitted} [εκεκραξα]{.greek-added} [εστως]{.greek-omitted} εν αυτοις [εστως]{.greek-added} οτι περι αναστασεως νεκρων εγω [κρινομαι]{.greek-omitted} [κρινωμαι]{.greek-added} σημερον υφ υμων[24:21]{.aside}

ακουσας δε ταυτα ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} ανεβαλετο αυτους ακριβεστερον ειδως τα περι της οδου ειπων οταν λυσιας ο χιλιαρχος καταβη διαγνωσομαι τα καθ υμας[24:22]{.aside}

διαταξαμενος τε τω [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} τηρεισθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} εχειν τε ανεσιν και μηδενα κωλυειν των ιδιων αυτου υπηρετειν η προσερχεσθαι αυτω[24:23]{.aside}

μετα δε ημερας τινας παραγενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} συν δρουσιλλη τη [ιδια]{.greek-added} γυναικι ουση ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου περι της εις [χριστον]{.greek-abbr} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του μελλοντος εσεσθαι εμφοβος γενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} απεκριθη το νυν [εχον]{.greek-omitted} [εχων]{.greek-added} πορευου καιρον δε [μεταλαβων]{.greek-omitted} [λαβων]{.greek-added} μετακαλεσομαι σε[24:25]{.aside}

αμα και ελπιζων οτι χρηματα δοθησεται αυτω υπο του παυλου οπως λυση αυτον διο και πυκνοτερον αυτον μεταπεμπομενος [ωμιλει]{.greek-omitted} [ομιλει]{.greek-added} αυτω[24:26]{.aside}

διετιας δε πληρωθεισης ελαβεν διαδοχον ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} πορκιον φηστον θελων [τε]{.greek-omitted} [χαριτας]{.greek-omitted} [δε]{.greek-added} [χαριν]{.greek-added} καταθεσθαι τοις ιουδαιοις ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [κατελιπεν]{.greek-omitted} [κατελειπεν]{.greek-added} τον παυλον δεδεμενον[24:27]{.aside}

### Chapter 25

[φηστος]{.greek-omitted} [φιστος]{.greek-added} ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη εις ιεροσολυμα απο καισαρειας[25:1]{.aside}

[ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} αυτω ο αρχιερευς και οι πρωτοι των ιουδαιων κατα του παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται αυτον εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} ενεδραν ποιουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν ουν [φηστος]{.greek-omitted} [φιστος]{.greek-added} [απεκριθη]{.greek-omitted} [επεκριθη]{.greek-added} τηρεισθαι τον παυλον [εν]{.greek-omitted} [εις]{.greek-added} [καισαρεια]{.greek-omitted} [καισαρειαν]{.greek-added} εαυτον δε μελλειν εν ταχει εκπορευεσθαι[25:4]{.aside}

οι ουν δυνατοι εν υμιν φησιν συγκαταβαντες ει τι εστιν εν τω ανδρι τουτω κατηγορειτωσαν αυτου[25:5]{.aside}

διατριψας δε εν αυτοις [ου]{.greek-added} [πλειονας]{.greek-added} ημερας πλειους η δεκα καταβας εις καισαρειαν τη επαυριον καθισας επι του βηματος εκελευσεν [αχθηναι]{.greek-added} τον παυλον [αχθηναι]{.greek-omitted}[25:6]{.aside}

παραγενομενου δε αυτου περιεστησαν [οι]{.greek-omitted} απο ιεροσολυμων [καταβεβηκοτες]{.greek-omitted} [καταβαντες]{.greek-added} ιουδαιοι πολλα και βαρεα αιτιωματα φεροντες κατα του παυλου α ουκ ισχυον αποδειξαι[25:7]{.aside}

απολογουμενου [αυτου]{.greek-omitted} οτι ουτε εις τον νομον των ιουδαιων ουτε εις [το]{.greek-omitted} [ιερον]{.greek-omitted} [ουτε]{.greek-omitted} [εις]{.greek-omitted} καισαρα τι ημαρτον[25:8]{.aside}

ο [φηστος]{.greek-omitted} [φιστος]{.greek-added} δε [θελων]{.greek-added} τοις ιουδαιοις [θελων]{.greek-omitted} χαριν καταθεσθαι αποκριθεις τω παυλω ειπεν θελεις εις ιεροσολυμα αναβας εκει περι τουτων [κρινεσθαι]{.greek-omitted} [κριθηναι]{.greek-added} [επ]{.greek-omitted} [επι]{.greek-added} εμου[25:9]{.aside}

ειπεν δε ο παυλος επι του βηματος καισαρος εστως ειμι ου με δει κρινεσθαι ιουδαιους ουδεν ηδικησα ως και συ καλλιον επιγινωσκεις[25:10]{.aside}

ει μεν [γαρ]{.greek-omitted} [αδικω]{.greek-omitted} [ουν]{.greek-added} [αδικον]{.greek-added} και αξιον θανατου [πεπραχα]{.greek-omitted} [πεπρα]{.greek-added} [χα]{.greek-added} τι ου παραιτουμαι το αποθανειν ει δε ουδεν εστιν ων ουτοι κατηγορουσιν μου ουδεις με δυναται αυτοις [χαρισασθαι]{.greek-omitted} [χαρησασθαι]{.greek-added} καισαρα επικαλουμαι[25:11]{.aside}

τοτε ο [φηστος]{.greek-omitted} [φιστος]{.greek-added} συλλαλησας μετα του συμβουλιου απεκριθη καισαρα [επικεκλησαι]{.greek-omitted} [επικακλεισε]{.greek-added} επι καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τινων αγριππας ο βασιλευς και βερνικη [κατηντησαν]{.greek-omitted} [κατηντισαν]{.greek-added} εις καισαρειαν ασπασαμενοι τον [φηστον]{.greek-omitted} [φιστον]{.greek-added}[25:13]{.aside}

ως δε πλειους ημερας [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added} εκει ο [φηστος]{.greek-omitted} [φιστος]{.greek-added} τω βασιλει ανεθετο τα κατα τον παυλον λεγων ανηρ τις εστιν [καταλελειμμενος]{.greek-omitted} [καταλελημμενος]{.greek-added} υπο [φηλικος]{.greek-omitted} [φιλικος]{.greek-added} δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις ιεροσολυμα [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} εις απωλειαν πριν η ο κατηγορουμενος κατα προσωπον εχοι τους κατηγορους τοπον τε απολογιας λαβοι περι του εγκληματος[25:16]{.aside}

[συνελθοντων]{.greek-omitted} [συνελθοτων]{.greek-added} ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη εξης καθισας επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν επεφερον ων [εγω]{.greek-added} υπενοουν [εγω]{.greek-omitted} [πονηραν]{.greek-added}[25:18]{.aside}

ζητηματα δε τινα περι της [ιδιας]{.greek-omitted} [εαυτων]{.greek-added} [δεισιδαιμονιας]{.greek-omitted} [δισιδαιμονιας]{.greek-added} ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τεθνηκοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω την περι [τουτου]{.greek-omitted} [τουτων]{.greek-added} ζητησιν ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} κακει κρινεσθαι περι τουτων[25:20]{.aside}

του δε παυλου [επικαλεσαμενου]{.greek-omitted} [επικαλουμενου]{.greek-added} [τηρηθηναι]{.greek-omitted} [τηριθηναι]{.greek-added} αυτον εις την του σεβαστου διαγνωσιν εκελευσα τηρεισθαι αυτον εως ου [πεμψω]{.greek-omitted} [αναπεμψω]{.greek-added} αυτον [προς]{.greek-omitted} [εις]{.greek-added} καισαρα[25:21]{.aside}

αγριππας δε προς τον [φηστον]{.greek-omitted} [φιστον]{.greek-added} εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της [βερνικης]{.greek-omitted} [βερνι]{.greek-added} [κης]{.greek-added} μετα πολλης φαντασιας και εισελθοντων εις το ακροατηριον συν τε [τοις]{.greek-omitted} χιλιαρχοις και ανδρασιν τοις κατ εξοχην [ουσιν]{.greek-omitted} της πολεως [ουσιν]{.greek-added} και κελευσαντος του [φηστου]{.greek-omitted} [φιστου]{.greek-added} ηχθη ο παυλος[25:23]{.aside}

και φησιν ο [φηστος]{.greek-omitted} [φιστος]{.greek-added} αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες θεωρειτε [το]{.greek-added} [πληθος]{.greek-added} [πε]{.greek-added} τουτον περι ου [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος των ιουδαιων [ενετυχον]{.greek-omitted} [ενετυχων]{.greek-added} μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν [αυτον]{.greek-added} ζην [αυτον]{.greek-omitted} μηκετι[25:24]{.aside}

εγω δε καταλαβομενος μηδεν αξιον θανατου αυτον πεπραχεναι και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα πεμπειν [αυτον]{.greek-omitted}[25:25]{.aside}

περι ου ασφαλες τι [γραψαι]{.greek-omitted} τω [κυριω]{.greek-abbr} [γραψαι]{.greek-added} ουκ εχω διο προηγαγον αυτον εφ υμων και [μαλιστα]{.greek-omitted} [μαλλιστα]{.greek-added} επι σου βασιλευ αγριππα οπως της ανακρισεως [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} σχω τι γραψαι[25:26]{.aside}

αλογον γαρ μοι δοκει πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη επιτρεπεται σοι [υπερ]{.greek-omitted} [περι]{.greek-added} σεαυτου λεγειν τοτε ο παυλος [απελογειτο]{.greek-omitted} εκτεινας την χειρα [απελογειτο]{.greek-added}[26:1]{.aside}

περι παντων ων εγκαλουμαι υπο ιουδαιων βασιλευ αγριππα ηγημαι εμαυτον μακαριον επι σου μελλων [σημερον]{.greek-added} απολογεισθαι [σημερον]{.greek-omitted}[26:2]{.aside}

[μαλιστα]{.greek-omitted} [μαλλιστα]{.greek-added} γνωστην οντα σε [παντων]{.greek-omitted} των κατα ιουδαιους [ηθων]{.greek-omitted} [εθων]{.greek-added} τε και ζητηματων διο δεομαι [σου]{.greek-omitted} μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ νεοτητος την απ αρχης γενομενην εν τω εθνει μου εν [τε]{.greek-added} ιεροσολυμοις ισασιν παντες οι ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν θελωσιν μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας [θρησκειας]{.greek-omitted} [θρισκειας]{.greek-added} εζησα φαρισαιος[26:5]{.aside}

και νυν επ ελπιδι της [προς]{.greek-omitted} [εις]{.greek-added} τους [πατερας]{.greek-abbr} επαγγελιας [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} υπο του [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν [εκτενεια]{.greek-omitted} [εκτενια]{.greek-added} νυκτα και ημεραν λατρευον ελπιζει [καταντησαι]{.greek-omitted} [καταντισαι]{.greek-added} περι ης ελπιδος εγκαλουμαι [υπο]{.greek-added} [ιουδαιων]{.greek-added} βασιλευ αγριππα [υπο]{.greek-omitted} [ιουδαιων]{.greek-omitted}[26:7]{.aside}

τι απιστον [κρινεται]{.greek-omitted} [κρινετε]{.greek-added} [παρ]{.greek-omitted} [εν]{.greek-added} υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησα εν ιεροσολυμοις και πολλους των αγιων εγω [εν]{.greek-added} φυλακαις κατεκλεισα την παρα των αρχιερεων εξουσιαν λαβων αναιρουμενων τε αυτων κατηνεγκα ψηφον[26:10]{.aside}

[και]{.greek-omitted} κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν περισσως τε εμμαινομενος αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις και πορευομενος εις [την]{.greek-omitted} δαμασκον μετ εξουσιας και επιτροπης της παρα των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον [ειδον]{.greek-omitted} [ιδον]{.greek-added} βασιλευ [αγριππα]{.greek-added} [ουρανοθεν]{.greek-omitted} [[ουνοθεν]{.greek-abbr}]{.greek-added} υπερ την λαμπροτητα του ηλιου περιλαμψαν με φως και τους συν εμοι πορευομενους[26:13]{.aside}

παντων δε καταπεσοντων ημων εις [την]{.greek-omitted} γην ηκουσα φωνην [λαλουσαν]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted} [και]{.greek-omitted} λεγουσαν [μοι]{.greek-added} τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε [ειπον]{.greek-omitted} [ειπα]{.greek-added} τις ει [κυριε]{.greek-abbr} ο δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[26:15]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} αναστηθι [και]{.greek-omitted} [στηθι]{.greek-omitted} επι τους ποδας σου εις τουτο γαρ ωφθην σοι [προχειρισασθαι]{.greek-omitted} [προχειρησασθαι]{.greek-added} σε [υπηρετην]{.greek-omitted} [υπηρετειν]{.greek-added} και μαρτυρα ων τε ειδες ων τε [οφθησομαι]{.greek-omitted} [ωφθησομαι]{.greek-added} σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου και [εκ]{.greek-added} των εθνων εις ους εγω [αποστελω]{.greek-added} σε [αποστελλω]{.greek-omitted}[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του [υποστρεψαι]{.greek-omitted} [αποστρεψαι]{.greek-added} απο σκοτους εις φως και της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην απειθης τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον και ιεροσολυμοις εις πασαν [τε]{.greek-omitted} την χωραν της ιουδαιας και τοις εθνεσιν [απαγγελλων]{.greek-omitted} [απηγγελλον]{.greek-added} μετανοειν και επιστρεφειν επι τον [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων [οι]{.greek-omitted} [με]{.greek-added} ιουδαιοι [με]{.greek-omitted} [συλ]{.greek-added} [συλλαβομενοι]{.greek-omitted} [λαβομενοι]{.greek-added} εν τω ιερω επειρωντο [διαχειρισασθαι]{.greek-omitted} [διαχειρησασθαι]{.greek-added}[26:21]{.aside}

επικουριας ουν τυχων της παρα του [θεου]{.greek-abbr} αχρι της ημερας ταυτης εστηκα μαρτυρομενος μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και [μωυσης]{.greek-omitted} [μωσης]{.greek-added}[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως [μελλει]{.greek-omitted} [μελλειν]{.greek-added} καταγγελλειν τω λαω και τοις εθνεσιν[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο [φηστος]{.greek-omitted} [φιστος]{.greek-added} μεγαλη τη φωνη [εφη]{.greek-omitted} [φησιν]{.greek-added} μαινη παυλε τα πολλα σε γραμματα εις μανιαν [περιτρεπει]{.greek-omitted} [τρεπει]{.greek-added}[26:24]{.aside}

ο δε ου μαινομαι φησιν κρατιστε [φηστε]{.greek-omitted} [φιστε]{.greek-added} [αλλα]{.greek-omitted} [αλλ]{.greek-added} αληθειας και [σωφροσυνης]{.greek-omitted} [σοφροσυνης]{.greek-added} ρηματα αποφθεγγομαι[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον και παρρησιαζομενος λαλω λανθανειν γαρ αυτον τι τουτων ου πειθομαι ουδεν ου γαρ [εστιν]{.greek-added} εν γωνια πεπραγμενον τουτο[26:26]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

ο δε αγριππας προς τον παυλον εφη εν ολιγω με πειθεις χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος ειπεν [ευξαιμην]{.greek-omitted} [ευξαμην]{.greek-added} αν τω [θεω]{.greek-abbr} και εν ολιγω και εν [πολλω]{.greek-omitted} [μεγαλω]{.greek-added} ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος καγω ειμι παρεκτος των δεσμων τουτων[26:29]{.aside}

[και]{.greek-omitted} ταυτα ειποντος αυτου ανεστη ο βασιλευς και ο ηγεμων η τε βερνικη και οι συγκαθημενοι αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν θανατου [αξιον]{.greek-omitted} η δεσμων [αξιον]{.greek-added} [τι]{.greek-added} πρασσει ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω [φηστω]{.greek-omitted} [φιστω]{.greek-added} εφη απολελυσθαι εδυνατο [ουτος]{.greek-added} ο [ανθρωπος]{.greek-abbr} [ουτος]{.greek-omitted} ει μη [επεκεκλητο]{.greek-omitted} [επικεκλητο]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την ιταλιαν παρεδιδουν τον τε παυλον και τινας ετερους δεσμωτας εκατονταρχη ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω [αδραμυττηνω]{.greek-omitted} [αδραμυντινω]{.greek-added} [μελλοντες]{.greek-omitted} [μελλοντι]{.greek-added} πλειν [εις]{.greek-added} τους κατα την ασιαν τοπους ανηχθημεν οντος συν ημιν αρισταρχου μακεδονος [θεσσαλονικεως]{.greek-omitted} [θεσσαλονικαιως]{.greek-added}[27:2]{.aside}

τη [τε]{.greek-omitted} [δε]{.greek-added} ετερα κατηχθημεν εις σιδωνα φιλανθρωπως [τε]{.greek-omitted} [δε]{.greek-added} ο ιουλιος τω παυλω χρησαμενος επετρεψεν προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες κατηλθομεν εις [μυρα]{.greek-omitted} [μυραν]{.greek-added} της λυκιας[27:5]{.aside}

κακει ευρων ο εκατονταρχος πλοιον αλεξανδρινον πλεον εις την ιταλιαν [ενεβιβασεν]{.greek-omitted} [ανεβηβασεν]{.greek-added} ημας εις αυτο[27:6]{.aside}

εν [ικαναις]{.greek-omitted} [ικανες]{.greek-added} δε ημεραις βραδυπλοουντες και μολις [γενομενοι]{.greek-omitted} [γεναμενοι]{.greek-added} κατα την [κνιδον]{.greek-omitted} [κνηδον]{.greek-added} μη προσεωντος ημας του ανεμου υπεπλευσαμεν την κρητην κατα σαλμωνην[27:7]{.aside}

μολις τε παραλεγομενοι αυτην ηλθομεν εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις λασαια[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος [ηδη]{.greek-omitted} επισφαλους του πλοος δια το και την νηστειαν ηδη παρεληλυθεναι [παρηνει]{.greek-omitted} [παρεινη]{.greek-added} ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των ψυχων ημων μελλειν εσεσθαι τον πλουν[27:10]{.aside}

ο δε εκατονταρχης τω κυβερνητη και τω ναυκληρω [μαλλον]{.greek-added} επειθετο [μαλλον]{.greek-omitted} η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι πλειους εθεντο βουλην αναχθηναι [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της κρητης βλεποντα κατα λιβα και κατα [χωρον]{.greek-omitted} [χωραν]{.greek-added}[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες [ασσον]{.greek-omitted} [ασον]{.greek-added} παρελεγοντο την κρητην[27:13]{.aside}

μετ ου πολυ δε εβαλεν κατ αυτης ανεμος τυφωνικος ο καλουμενος [ευροκλυδων]{.greek-omitted} [ευρακλυδων]{.greek-added}[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι [υποδραμοντες]{.greek-omitted} [υποδραμωντες]{.greek-added} καλουμενον [κλαυδην]{.greek-omitted} [κλαυδαν]{.greek-added} μολις ισχυσαμεν περικρατεις γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες βοηθειαις εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη [πως]{.greek-added} εις την συρτην εκπεσωσιν χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως [δε]{.greek-omitted} [τε]{.greek-added} χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη [ημερα]{.greek-added} αυτοχειρες την σκευην του πλοιου [ερριψαμεν]{.greek-omitted} [ερρηψαμεν]{.greek-added}[27:19]{.aside}

μητε δε ηλιου μητε αστρων επιφαινοντων επι [πλειονας]{.greek-omitted} [πλειωνας]{.greek-added} ημερας [χειμωνος]{.greek-omitted} [χειμονος]{.greek-added} τε ουκ ολιγου επικειμενου λοιπον περιηρειτο [ελπις]{.greek-added} πασα [ελπις]{.greek-omitted} του σωζεσθαι ημας[27:20]{.aside}

πολλης δε ασιτιας υπαρχουσης τοτε [σταθεις]{.greek-omitted} ο παυλος [σταθεις]{.greek-added} εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης κερδησαι τε την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης ουδεμια εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι αγγελος του [θεου]{.greek-abbr} [ου]{.greek-omitted} [ω]{.greek-added} ειμι ω και λατρευω[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω [αδρεα]{.greek-added} [αδρια]{.corr} κατα μεσον της νυκτος υπενοουν οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας εικοσι βραχυ δε διαστησαντες και [παλιν]{.greek-omitted} [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι τε [μη]{.greek-added} [μηπως]{.greek-omitted} [πως]{.greek-added} [εις]{.greek-omitted} [κατα]{.greek-added} τραχεις τοπους [εκπεσωμεν]{.greek-omitted} [εκπεσωσιν]{.greek-added} εκ πρυμνης ριψαντες αγκυρας [τεσσαρας]{.greek-omitted} [τεσσαρες]{.greek-added} ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} προφασει ως εκ πρωρας μελλοντων [εκτεινειν]{.greek-added} αγκυρας [εκτεινειν]{.greek-omitted}[27:30]{.aside}

ειπεν ο παυλος τω εκατονταρχη και τοις στρατιωταις εαν μη ουτοι μεινωσιν εν τω πλοιω υμεις σωθηναι ου δυνασθε[27:31]{.aside}

τοτε [αποκοψαντες]{.greek-added} οι στρατιωται [απεκοψαν]{.greek-omitted} τα σχοινια της σκαφης [και]{.greek-omitted} ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου ημελλεν ημερα γινεσθαι παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην [ημεραν]{.greek-added} σημερον [ημεραν]{.greek-omitted} προσδοκωντες ασιτοι διατελειτε μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας [προσλαβειν]{.greek-omitted} [μεταλαβειν]{.greek-added} τροφης τουτο γαρ προς της υμετερας [σωτηριας]{.greek-abbr} υπαρχει ουδενος γαρ [υμων]{.greek-omitted} [ημων]{.greek-added} θριξ [εκ]{.greek-omitted} [απο]{.greek-added} της κεφαλης πεσειται[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον ευχαριστησεν τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

ημεν δε [πασαι]{.greek-added} [ψυχαι]{.greek-added} εν τω πλοιω [αι]{.greek-omitted} [πασαι]{.greek-omitted} [ψυχαι]{.greek-omitted} διακοσιαι εβδομηκοντα εξ[27:37]{.aside}

κορεσθεντες δε της τροφης εκουφιζον το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον [εβουλευσαντο]{.greek-omitted} [εβουλευοντο]{.greek-added} ει δυνατον εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας [περιελοντες]{.greek-omitted} [περιελωντες]{.greek-added} ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των [πηδαλιων]{.greek-omitted} [πιδαλιων]{.greek-added} και επαραντες τον αρτεμονα τη πνεουση [κατειχον]{.greek-omitted} [κατηχοντο]{.greek-added} εις τον αιγιαλον[27:40]{.aside}

[περιπεσοντες]{.greek-omitted} [περιπεσοντος]{.greek-added} δε εις τοπον διθαλασσον [επωκειλαν]{.greek-omitted} [επεκειλαν]{.greek-added} την ναυν και η μεν πρωρα [ερεισασα]{.greek-omitted} [ερησασα]{.greek-added} εμεινεν ασαλευτος η δε πρυμνα ελυετο [υπο]{.greek-omitted} [απο]{.greek-added} της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας αποκτεινωσιν μη τις [εκκολυμβησας]{.greek-omitted} [εκκολυμβισας]{.greek-added} διαφυγη[27:42]{.aside}

ο δε [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του βουληματος εκελευσεν τε τους δυναμενους κολυμβαν [απορριψαντας]{.greek-omitted} [απορριψαντες]{.greek-added} πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους μεν επι σανισιν ους δε επι τινων των απο του πλοιου και ουτως εγενετο παντας διασωθηναι επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες τοτε [επεγνωσαν]{.greek-omitted} [επεγνωμεν]{.greek-added} οτι μελιτη η νησος καλειται[28:1]{.aside}

οι [δε]{.greek-omitted} [τε]{.greek-added} βαρβαροι παρειχον ου την τυχουσαν [φιλανθρωπιαν]{.greek-omitted} [[φιλανιαν]{.greek-abbr}]{.greek-added} ημιν [αναψαντες]{.greek-omitted} [αψαντες]{.greek-added} γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον εφεστωτα και δια το ψυχος[28:2]{.aside}

συστρεψαντος δε του παυλου φρυγανων [τι]{.greek-added} πληθος και επιθεντος επι την πυραν εχιδνα [εκ]{.greek-omitted} [απο]{.greek-added} της θερμης [διεξελθουσα]{.greek-omitted} [εξελθουσα]{.greek-added} [καθηψεν]{.greek-omitted} [καθηψε]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε [ειδον]{.greek-omitted} [ιδον]{.greek-added} οι βαρβαροι κρεμαμενον το θηριον εκ της χειρος αυτου ελεγον προς αλληλους παντως φονευς εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ [ειασεν]{.greek-omitted} [εασεν]{.greek-added}[28:4]{.aside}

ο μεν ουν αποτιναξας το θηριον εις το πυρ επαθεν ουδεν κακον[28:5]{.aside}

οι δε [προσεδοκων]{.greek-omitted} [προσεδοκουν]{.greek-added} αυτον μελλειν πιμπρασθαι η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων [προσδοκωντων]{.greek-omitted} [προσδοκοντων]{.greek-added} και θεωρουντων μηδεν ατοπον εις αυτον γινομενον μεταβαλλομενοι ελεγον [αυτον]{.greek-added} [θεον]{.greek-abbr} [αυτον]{.greek-omitted} ειναι[28:6]{.aside}

εν δε τοις περι τον τοπον εκεινον υπηρχεν χωρια τω πρωτω της νησου ονοματι [ποπλιω]{.greek-omitted} [πουπλιω]{.greek-added} ος αναδεξαμενος ημας [ημερας]{.greek-added} τρεις [ημερας]{.greek-omitted} φιλοφρονως [εξενισεν]{.greek-omitted} [εξενησεν]{.greek-added}[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του ποπλιου πυρετοις και [δυσεντερια]{.greek-omitted} [δυσεντεριω]{.greek-added} συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις τας χειρας [αυτω]{.greek-omitted} [αυτου]{.greek-added} ιασατο αυτον[28:8]{.aside}

τουτου [ουν]{.greek-omitted} [δε]{.greek-added} γενομενου και οι λοιποι οι [εχοντες]{.greek-omitted} [ασθενειας]{.greek-omitted} εν τη νησω [εχοντες]{.greek-added} [ασθενειας]{.greek-added} προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρειαν[28:10]{.aside}

μετα δε τρεις μηνας [ηχθημεν]{.greek-omitted} [ανηχθημεν]{.greek-added} εν πλοιω παρακεχειμακοτι εν τη νησω αλεξανδρινω [παρασημω]{.greek-omitted} [παρασιμωνι]{.greek-added} [διοσκουροις]{.greek-omitted} [διοσκοροις]{.greek-added}[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες [κατηντησαμεν]{.greek-omitted} [κατην]{.greek-added} [τησαμεν]{.greek-added} εις [ρηγιον]{.greek-omitted} [ριγιον]{.greek-added} και μετα μιαν ημεραν [επιγενομενου]{.greek-omitted} [επιγινομενου]{.greek-added} νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις επιμειναι ημερας επτα και ουτως [ηλθομεν]{.greek-added} εις [την]{.greek-omitted} ρωμην [ηλθομεν]{.greek-omitted}[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περι ημων [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} εις απαντησιν [ημιν]{.greek-omitted} [ημων]{.greek-added} αχρι [αππιου]{.greek-omitted} [απφιου]{.greek-added} φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} ελαβεν θαρσος[28:15]{.aside}

οτε δε [ηλθομεν]{.greek-omitted} [ηλθωμεν]{.greek-added} εις ρωμην ο εκατονταρχος παρεδωκεν τους δεσμιους τω [στρατοπεδαρχη]{.greek-omitted} [στρατοπαιδαρχη]{.greek-added} τω δε παυλω [επετραπη]{.greek-omitted} [επετραπει]{.greek-added} μενειν καθ εαυτον συν τω φυλασσοντι αυτον στρατιωτη[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων ελεγεν προς αυτους ανδρες αδελφοι εγω ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθνεσιν]{.greek-added} τοις πατρωοις δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με εβουλοντο [με]{.greek-added} απολυσαι δια το μηδεμιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

[αντιλεγειν]{.greek-added} [αντιλεγοντων]{.corr} δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου εχων τι [κατηγορησαι]{.greek-omitted} [κατηγορειν]{.greek-added}[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι ενεκεν γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον [ειπον]{.greek-omitted} [ειπαν]{.greek-added} ημεις ουτε γραμματα [εδεξαμεθα]{.greek-added} περι σου [εδεξαμεθα]{.greek-omitted} απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν [η]{.greek-omitted} [ελαλησεν]{.greek-omitted} τι περι σου πονηρον[28:21]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον [ημιν]{.greek-added} εστιν [ημιν]{.greek-omitted} οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι δε αυτω ημεραν [ηλθον]{.greek-added} [ηκον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} εις την ξενιαν [προς]{.greek-added} [αυτον]{.greek-added} πλειονες οις [εξετιθετο]{.greek-omitted} [εξετειθετο]{.greek-added} διαμαρτυρομενος την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους τα περι του [ιησου]{.greek-abbr} απο τε του νομου μωυσεως και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον ελαλησεν δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added}[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και ειπον ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη [ιδητε]{.greek-omitted} [ειδετε]{.greek-added}[28:26]{.aside}

[επαχυνθη]{.greek-omitted} [επανχυνθη]{.greek-added} γαρ η καρδια του λαου τουτου και τοις ωσιν βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε ιδωσιν τοις οφθαλμοις και τοις ωσιν ακουσωσιν και τη καρδια συνωσιν και επιστρεψωσιν και [ιασομαι]{.greek-omitted} [ιασωμαι]{.greek-added} αυτους[28:27]{.aside}

γνωστον [ουν]{.greek-omitted} εστω υμιν [[ο]{.unclear}[―]{.gap}]{.greek-added} οτι τοις εθνεσιν απεσταλη [τουτο]{.greek-added} το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και ταυτα αυτου ειποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις συζητησιν[28:29]{.aside}

[εμεινεν]{.greek-omitted} [ενεμεινεν]{.greek-added} δε ο παυλος διετιαν ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους προς αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} μετα πασης παρρησιας ακωλυτως[28:31]{.aside}

