---
title: "Collation of Byz^RP^ vs 31160 (1160)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1160 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31160).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1160                                   	| λογος                              	|
| 1160 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1160 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1160               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1160                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1160 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1160                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1 | instance no. 2]{.aside}

ως γεγραπται εν τοις προφηταις [ιδου]{.greek-omitted} [εγω]{.greek-omitted} [αποστελλω]{.greek-omitted} [τον]{.greek-omitted} [αγγελον]{.greek-omitted} [μου]{.greek-omitted} [προ]{.greek-omitted} [προσωπου]{.greek-omitted} [σου]{.greek-omitted} [ος]{.greek-omitted} [κατασκευασει]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [σου]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [σου]{.greek-omitted}[1:2]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2 | instance no. 2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και [οι]{.greek-omitted} ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν [εκειναις]{.greek-omitted} ταις ημεραις [εκειναις]{.greek-added} ηλθεν [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω ευδοκησα[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} [εκβαλλει]{.greek-added} αυτον [εκβαλλει]{.greek-omitted} εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων [οτι]{.greek-omitted} πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος [βαλλοντας]{.greek-omitted} [αμφιβαλλοντας]{.greek-added} αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και [εισπορευονται]{.greek-omitted} [εισπορευεται]{.greek-added} εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εισπορευονται εις καπερναουμ [και]{.greek-omitted} [ευθεως]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [εισελθων]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [συναγωγην]{.greek-omitted} [εδιδασκεν]{.greek-omitted}[1:21 | instance no. 2]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις [αυτων]{.greek-added}[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν πνευματι ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το πνευμα το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη [αυτη]{.greek-added} η καινη [αυτη]{.greek-omitted} οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα [του]{.greek-added} σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και κατεδιωξαν αυτον [ο]{.greek-omitted} σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων αυτω [οτι]{.greek-omitted} εαν θελης δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και [ειποντος]{.greek-omitted} [αυτου]{.greek-omitted} [ευθεως]{.greek-omitted} [απηλθεν]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [λεπρα]{.greek-omitted} [και]{.greek-omitted} [εκαθαρισθη]{.greek-omitted}[1:42]{.aside}

[και]{.greek-omitted} ειποντος αυτου ευθεως [η]{.greek-added} [λεπρα]{.greek-added} απηλθεν απ αυτου [η]{.greek-omitted} [λεπρα]{.greek-omitted} και εκαθαρισθη[1:42 | instance no. 2]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου [α]{.greek-omitted} [ο]{.greek-added} [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν [πολλα]{.greek-omitted} και διαφημιζειν [πολλα]{.greek-added} τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν αλλ εξω [εν]{.greek-omitted} [επ]{.greek-added} ερημοις τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον αφεωνται σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογι]{.greek-added} [διαλογιζεσθε]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [καρδιαις]{.greek-omitted} [υμων]{.greek-omitted}[2:8]{.aside}

[ζεσθε]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [επιγνους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τω]{.greek-omitted} [πνευματι]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [ουτως]{.greek-omitted} [αυτοι]{.greek-omitted} [διαλογιζονται]{.greek-omitted} [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [ταυτα]{.greek-omitted} [διαλογιζεσθε]{.greek-omitted} εν ταις καρδιαις υμων[2:8 | instance no. 2]{.aside}

τι εστιν ευκοπωτερον ειπειν [τω]{.greek-omitted} [τωι]{.greek-added} παραλυτικω αφεωνται σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιεναι]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως ειδομεν[2:12]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ειδε]{.greek-added} λευι τον του αλφαιου καθημενον επι το τελωνιον και [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτω [[η]{.unclear}κολουθει]{.greek-added} [ακολουθει]{.corr} μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου [και]{.greek-omitted} πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [φαρισαιοι]{.greek-added} [νηστευοντες]{.greek-omitted} [νηστεις]{.greek-added} και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν [ω]{.greek-omitted} [οσω]{.greek-added} ο νυμφιος μετ αυτων εστιν νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [εκεινη]{.greek-added} [τη]{.greek-added} [ημεραις]{.greek-omitted} [ημερα]{.greek-added}[2:20]{.aside}

[και]{.greek-omitted} ουδεις επιβλημα ρακους αγναφου επιρραπτει επι ιματιω παλαιω ει δε μη αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον εις ασκους καινους βλητεον[2:22]{.aside}

και εγενετο [αυτον]{.greek-added} παραπορευεσθαι [αυτον]{.greek-omitted} εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} [εν]{.greek-omitted} τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [ποιειν]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted} [φαγειν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τοις]{.greek-omitted} [ιερευσιν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [ουσιν]{.greek-omitted}[2:26]{.aside}

[πως]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [αβιαθαρ]{.greek-omitted} [αρχιερεως]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [της]{.greek-omitted} [προθεσεως]{.greek-omitted} [εφαγεν]{.greek-omitted} [ους]{.greek-omitted} ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26 | instance no. 2]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην εχων την χειρα[3:1]{.aside}

και [παρετηρουν]{.greek-omitted} [παρετηρουντο]{.greek-added} αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω εξηραμμενην εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος [επι]{.greek-omitted} [τη]{.greek-omitted} [πωρωσει]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [εκτεινον]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξετεινεν]{.greek-omitted} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} [η]{.greek-omitted} [χειρ]{.greek-omitted} [αυτου]{.greek-omitted} [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[3:5]{.aside}

[και]{.greek-omitted} [περιβλεψαμενος]{.greek-omitted} [αυτους]{.greek-omitted} [μετ]{.greek-omitted} [οργης]{.greek-omitted} [συλλυπουμενος]{.greek-omitted} επι [τη]{.greek-omitted} [τηι]{.greek-added} πωρωσει της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα [σου]{.greek-omitted} και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} [η]{.greek-omitted} [χειρ]{.greek-omitted} [αυτου]{.greek-omitted} υγιης ως η αλλη[3:5 | instance no. 2]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον [εποιουν]{.greek-omitted} [εποιησαν]{.greek-added} κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted} και απο της ιουδαιας [ηκολουθησεν]{.greek-added}[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα [εποιει]{.greek-omitted} [εποιησεν]{.greek-added} ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον προσκαρτερη αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου αψωνται οσοι ειχον μαστιγας[3:10]{.aside}

και [τα]{.greek-omitted} πνευματα τα ακαθαρτα οταν αυτον [εθεωρει]{.greek-omitted} [εθεωρουν]{.greek-added} [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον [ποιωσιν]{.greek-added} αυτον [ποιησωσιν]{.greek-omitted}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα [ους]{.greek-added} [και]{.greek-added} [αποστολους]{.greek-added} [ωνομασεν]{.greek-added} ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα αποστελλη αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και επεθηκεν [αυτοις]{.greek-added} [ονοματα]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [του]{.greek-omitted} ιακωβου [και]{.greek-omitted} επεθηκεν αυτοις [ο]{.unclear}νοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη δυνασθαι αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ [αυτου]{.greek-omitted} [αυτω]{.greek-added} εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν [τω]{.greek-omitted} [τωι]{.greek-added} αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται σταθηναι η οικια εκεινη[3:25]{.aside}

[και]{.greek-omitted} ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου διαρπαση[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και [απεκριθη]{.greek-omitted} [αποκριθεις]{.greek-added} αυτοις [λεγει]{.greek-added} [λεγων]{.greek-omitted} [τις]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [μητηρ]{.greek-omitted} [μου]{.greek-omitted} [η]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [μου]{.greek-omitted}[3:33]{.aside}

[και]{.greek-omitted} [απεκριθη]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33 | instance no. 2]{.aside}

και περιβλεψαμενος [κυκλω]{.greek-omitted} [κυκλωι]{.greek-added} τους περι αυτον καθημενους λεγει ιδε η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος [και]{.greek-added} αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις [το]{.greek-omitted} πλοιον [καθησθαι]{.greek-omitted} [καθησαι]{.greek-added} εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν [αυτοις]{.greek-omitted} εν τη διδαχη αυτου[4:2]{.aside}

ακουετε [ιδου]{.greek-omitted} [εξηλθεν]{.greek-omitted} [ο]{.greek-omitted} [σπειρων]{.greek-omitted} [του]{.greek-omitted} [σπειραι]{.greek-omitted}[4:3]{.aside}

[ακουετε]{.greek-omitted} ιδου εξηλθεν ο σπειρων του σπειραι[4:3 | instance no. 2]{.aside}

και εγενετο εν τω σπε[ι]{.unclear}ρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και [αυξανοντα]{.greek-omitted} [αυξανομενα]{.greek-added} και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι [το]{.greek-omitted} [τα]{.greek-added} [μυστηριον]{.greek-omitted} [μυστηρια]{.greek-added} της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα [δε]{.greek-added} γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [μηποτε]{.greek-omitted} [επιστρεψωσιν]{.greek-omitted} [και]{.greek-omitted} [αφεθη]{.greek-omitted} [αυτοις]{.greek-omitted} [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted}[4:12]{.aside}

[ινα]{.greek-omitted} [βλεποντες]{.greek-omitted} [βλεπωσιν]{.greek-omitted} [και]{.greek-omitted} μη [ιδωσιν]{.greek-omitted} [και]{.greek-omitted} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα [αυτων]{.greek-added}[4:12 | instance no. 2]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν [αυτου]{.greek-added} ευθεως ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν [εαυτοις]{.greek-omitted} [αυτοις]{.greek-added} αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} τι κρυπτον [ο]{.greek-omitted} εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} βλεπετε τι ακουετε εν ω μετρω μετρειτε μετρηθησεται υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ αν εχη δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως [εαν]{.greek-omitted} [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [βαλλει]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και [καθευδη]{.greek-omitted} [καθευδει]{.greek-added} και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσω]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} [παραβαλουμεν]{.greek-added} αυτην[4:30]{.aside}

ως κοκκον σιναπεως ος οταν σπαρη επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων [μειζων]{.greek-omitted} [μειζον]{.greek-added} και ποιει κλαδους [μεγαλους]{.greek-omitted} [μεγιστους]{.greek-added} ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως εδυναντο ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [ελυε]{.greek-added} παντα[4:34]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [α]{.greek-added} [ελεγεν]{.greek-added} αυτοις εν εκεινη τη ημερα οψιας [δε]{.greek-added} γενομενης [διελθωμεν]{.greek-omitted} [διηλθομεν]{.greek-added} εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε [πλοιαρια]{.greek-omitted} [πλοια]{.greek-added} ην μετ αυτου[4:36]{.aside}

και γινεται λαιλαψ ανεμου μεγαλη τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι το προσκεφαλαιον [καθευδων]{.greek-omitted} [καθημενος]{.greek-added} και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου μελει σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [τη]{.greek-omitted} [τηι]{.greek-added} θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και [ε]{.greek-added} [ελεγον]{.greek-omitted} [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [τις]{.greek-omitted} [αρα]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [θαλασσα]{.greek-omitted} [υπακουουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[4:41]{.aside}

[και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted} [φοβον]{.greek-omitted} [μεγαν]{.greek-omitted} [και]{.greek-omitted} [ελεγον]{.greek-omitted} [λεγον]{.greek-added} προς αλληλους τις αρα ουτος εστιν οτι και [ο]{.greek-omitted} [οι]{.greek-added} [ανεμος]{.greek-omitted} [ανεμοι]{.greek-added} και η θαλασσα υπακουουσιν αυτω[4:41 | instance no. 2]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν πνευματι ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις εδυνατο αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις [και]{.greek-omitted} [η]{.greek-added} [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και [διεσπασθαι]{.greek-omitted} [διασπασθαι]{.greek-added} υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [εδυνατο]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημασι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων [και]{.greek-omitted} [κατακοπτων]{.greek-omitted} [εαυτον]{.greek-omitted} [λιθοις]{.greek-omitted}[5:5]{.aside}

[και]{.greek-omitted} [δια]{.greek-omitted} [παντος]{.greek-omitted} [νυκτος]{.greek-omitted} [και]{.greek-omitted} [ημερας]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ορεσιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [μνημασιν]{.greek-omitted} [ην]{.greek-omitted} [κραζων]{.greek-omitted} και κατακοπτων εαυτον λιθοις[5:5 | instance no. 2]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και σοι [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το πνευμα το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι [σοι]{.greek-omitted} [το]{.greek-added} ονομα [σου]{.greek-added} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι [εστιν]{.greek-added} οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη [αποστειλη]{.greek-added} αυτους [αποστειλη]{.greek-omitted} εξω της χωρας[5:10]{.aside}

ην δε εκει [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων μεγαλη βοσκομενη [προς]{.greek-added} [τω]{.greek-added} [ορει]{.greek-added}[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις [ευθεως]{.greek-omitted} ο [ιησους]{.greek-abbr} και εξελθοντα τα πνευματα τα ακαθαρτα [απο]{.greek-added} [του]{.greek-added} [[ανθρωπου]{.greek-abbr}]{.greek-added} εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

[και]{.greek-added} οι [δε]{.greek-omitted} βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο [δαιμονισθεις]{.greek-omitted} [ιαθεις]{.greek-added} ινα [η]{.greek-omitted} μετ αυτου [η]{.greek-added}[5:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-omitted} [[θεος]{.greek-abbr}]{.greek-added} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απλθε]{.greek-added} [απηλθεν]{.greek-omitted} [[απηλθε]{.corr}]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων επιθης [αυτω]{.greek-added} [αυτη]{.corr} τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και ηκολουθει αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω [οπισθεν]{.greek-omitted} ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ειπε]{.greek-added} γαρ οτι καν των ιματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι [ιαται]{.greek-omitted} [ιαθη]{.greek-added} απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν [εαυτω]{.greek-omitted} [εαυτωι]{.greek-added} την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο [ιδειν]{.greek-omitted} την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτη θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι [δε]{.greek-added} αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα [αυτω]{.greek-omitted} [αυτωι]{.greek-added} συνακολουθησαι ει μη πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} εις τον οικον του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} κλαιοντας και αλαλαζοντας [πολλα]{.greek-omitted} [πολλους]{.greek-added}[5:38]{.aside}

και εισελθων λεγει αυτοις [τι]{.greek-omitted} [μη]{.greek-added} θορυβεισθε και κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και [κατε]{.greek-added} [κατεγελων]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [εκβαλων]{.greek-omitted} [παντας]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [του]{.greek-omitted} [παιδιου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εισπορευεται]{.greek-omitted} [οπου]{.greek-omitted} [ην]{.greek-omitted} [το]{.greek-omitted} [παιδιον]{.greek-omitted} [ανακειμενον]{.greek-omitted}[5:40]{.aside}

[γελουν]{.greek-added} [και]{.greek-omitted} [κατεγελων]{.greek-omitted} αυτου ο δε [[ιησους]{.greek-abbr}]{.greek-added} εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40 | instance no. 2]{.aside}

και κρατησας της χειρος του παιδιου λεγει [αυτη]{.greek-omitted} [αυτω]{.greek-added} [ταλιθα]{.greek-omitted} [ταβηθα]{.greek-added} [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο εστιν μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ [ως]{.greek-added} ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν [και]{.greek-omitted} [ηλθεν]{.greek-omitted} εις την πατριδα αυτου και [ακολουθουσιν]{.greek-omitted} [ακουλουθουσιν]{.greek-added} αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η σοφια η δοθεισα αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο [του]{.greek-added} [τεκτων]{.greek-omitted} [τεκτωνος]{.greek-added} [ο]{.greek-omitted} υιος [και]{.greek-added} μαριας αδελφος [δε]{.greek-omitted} ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη πατριδι αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν [ποιησαι]{.greek-added} δυναμιν [ποιησαι]{.greek-omitted} ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας [κυκλω]{.greek-omitted} [παντοθεν]{.greek-added} διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν [των]{.greek-omitted} [κατα]{.greek-added} πνευματων [των]{.greek-omitted} ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις [την]{.greek-added} οδον [ει]{.greek-omitted} μη ραβδον [μονον]{.greek-omitted} μη πηραν μη αρτον [μη]{.greek-omitted} [μητε]{.greek-added} εις [την]{.greek-omitted} [ζωνην]{.greek-omitted} [τας]{.greek-added} [ζωνας]{.greek-added} χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσασθε]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η γομορροις εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον [αυτους]{.greek-added}[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο ενεργουσιν αι δυναμεις εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον εγω απεκεφαλισα ιωαννην ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης αποστειλας [ε]{.greek-added} [εκρατησεν]{.greek-omitted} [[ε]{.unclear}κρατησε]{.greek-added} τον ιωαννην και [εδησεν]{.greek-omitted} [εθηκεν]{.greek-added} αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην [εγαμησεν]{.greek-omitted}[6:17]{.aside}

[αυτος]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ηρωδης]{.greek-omitted} [αποστειλας]{.greek-omitted} [εκρατησεν]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [και]{.greek-omitted} [εδησεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [φυλακη]{.greek-omitted} [δια]{.greek-omitted} [ηρωδιαδα]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [φιλιππου]{.greek-omitted} [του]{.greek-omitted} [αδελφου]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [αυτην]{.greek-omitted} [εγαμησεν]{.greek-omitted} [εγαμισεν]{.greek-added}[6:17 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο ιωαννης τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας [ενειχεν]{.greek-omitted} [εβαινετο]{.greek-added} αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και [τοις]{.greek-omitted} χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

[και]{.greek-omitted} εισελθουσης της θυγατρος [αυτης]{.greek-omitted} [αυτου]{.greek-added} της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο [θελεις]{.greek-added} [εαν]{.greek-omitted} [θελης]{.greek-omitted} και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν [αιτησης]{.greek-added} με [αιτησης]{.greek-omitted} δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης [τι]{.corr} [αιτησομαι]{.corr} [η]{.corr} [δε]{.corr} [ειπεν]{.greek-omitted} [[ειπε]{.corr}]{.greek-added} [την]{.corr} [κεφαλην]{.corr} [ιωαννου]{.greek-omitted} [[[ιω]{.greek-abbr}]{.corr}]{.greek-added} [του]{.corr} [βαπτιστου]{.corr}[6:24]{.aside}

[και]{.corr} [εισελθουσα]{.corr} [ευθεως]{.corr} [μετα]{.corr} [σπουδης]{.corr} [προς]{.corr} [τον]{.corr} [βασιλεα]{.corr} [ητησατο]{.corr} [λεγουσα]{.corr} [θελω]{.corr} [ινα]{.corr} [μοι]{.corr} [δως]{.corr} [εξαυτης]{.corr} [επι]{.corr} [πινακι]{.corr} [την]{.corr} [κεφαλην]{.corr} [ιωαννου]{.greek-omitted} [[[ιω]{.greek-abbr}]{.corr}]{.greek-added} [του]{.corr} [βαπτιστου]{.corr}[6:25]{.aside}

[και]{.corr} [περιλυπος]{.corr} [γενομενος]{.corr} [ο]{.corr} [βασιλευς]{.corr} [δια]{.corr} [τους]{.corr} [ορκους]{.corr} [και]{.corr} [τους]{.corr} [συνανακειμενους]{.corr} [ουκ]{.corr} [ηθελησεν]{.corr} [αυτην]{.corr} [αθετησαι]{.corr}[6:26]{.aside}

[και]{.corr} [ευθεως]{.corr} [αποστειλας]{.corr} [ο]{.corr} [βασιλευς]{.corr} [σπεκουλατορα]{.greek-omitted} [[σπεκουλατωρα]{.corr}]{.greek-added} [επεταξεν]{.corr} [ενεχθηναι]{.corr} [την]{.corr} [κεφαλην]{.corr} [αυτου]{.corr} [[ο]{.corr}]{.greek-added} [[δε]{.corr}]{.greek-added} [[απελθων]{.corr}]{.greek-added} [[απεκεφαλισεν]{.corr}]{.greek-added} [[αυτον]{.corr}]{.greek-added} [[εν]{.corr}]{.greek-added} [[τη]{.corr}]{.greek-added} [[φυλακη]{.corr}]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} [και]{.corr} [ηνεγκεν]{.greek-omitted} [[ηνεγκε]{.corr}]{.greek-added} [την]{.corr} [κεφαλην]{.corr} [αυτου]{.corr} [επι]{.corr} [πινακι]{.corr} [και]{.corr} εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και [απηγγειλαν]{.greek-omitted} [ανηγγειλαν]{.greek-added} αυτω παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυσασθε]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} πολλοι [αυτους]{.greek-added} και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ειδεν]{.greek-added} [οχλον]{.greek-added} πολυν [οχλον]{.greek-omitted} και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας [πολλης]{.greek-omitted} [γενομενης]{.greek-omitted} [προσελθοντες]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οτι]{.greek-omitted} [ερημος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [τοπος]{.greek-omitted} [και]{.greek-omitted} [ηδη]{.greek-omitted} [ωρα]{.greek-omitted} [πολλη]{.greek-omitted}[6:35]{.aside}

[και]{.greek-omitted} [ηδη]{.greek-omitted} [ωρας]{.greek-omitted} πολλης γενομενης προσελθοντες αυτω οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35 | instance no. 2]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν [διακοσιων]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και γνοντες λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακλιθηναι]{.greek-added} παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους [πληρεις]{.greek-omitted} και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και [ευθεως]{.greek-omitted} [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν [αυτον]{.greek-added} εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βησθαιδα]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και [εταραχθησαν]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [ελαλησεν]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [θαρσειτε]{.greek-omitted} [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [μη]{.greek-omitted} [φοβεισθε]{.greek-omitted}[6:50]{.aside}

[παντες]{.greek-omitted} [γαρ]{.greek-omitted} [αυτον]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50 | instance no. 2]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον [οι]{.greek-added} [ανδρες]{.greek-added} [του]{.greek-added} [τοπου]{.greek-added}[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων [―]{.gap}ελθοντες [[ελθοντες]{.corr}]{.greek-added} απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοι[ς]{.unclear} εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας χειρα[ς]{.unclear} ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη βαπτισωνται ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν α [παρελαβον]{.greek-omitted} [κρατειν]{.greek-omitted} [βαπτισμους]{.greek-omitted} [ποτηριων]{.greek-omitted} [και]{.greek-omitted} [ξεστων]{.greek-omitted} [και]{.greek-omitted} [χαλκιων]{.greek-omitted} [και]{.greek-omitted} [κλινων]{.greek-omitted}[7:4]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [αγορας]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [βαπτισωνται]{.greek-omitted} [ουκ]{.greek-omitted} [εσθιουσιν]{.greek-omitted} [και]{.greek-omitted} [αλλα]{.greek-omitted} [πολλα]{.greek-omitted} [εστιν]{.greek-omitted} [α]{.greek-omitted} παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και [χαλκιων]{.greek-omitted} [χαλκειων]{.greek-added} και κλινων[7:4 | instance no. 2]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και [οι]{.greek-omitted} γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την παραδοσιν των πρεσβυτερων [αλλα]{.greek-omitted} [αλλ]{.greek-added} ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως [γεγραπται]{.greek-omitted} [προγεγραπται]{.greek-added} ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι [τω]{.greek-omitted} [τωι]{.greek-added} [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} [δια]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [παραδοσει]{.greek-omitted} [παραδοσιν]{.greek-added} υμων [η]{.greek-omitted} [ην]{.greek-added} παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος [παντα]{.greek-omitted} τον οχλον ελεγεν αυτοις ακουετε μου παντες και [συνιετε]{.greek-omitted} [συνετε]{.greek-added}[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται [αυτου]{.greek-omitted} εις την καρδιαν [αλλ]{.greek-omitted} [αλλα]{.greek-added} εις την κοιλιαν και εις [τον]{.greek-omitted} αφεδρωνα εκπορευεται καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι [πονηριαι]{.greek-added} φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι [πονηριαι]{.greek-omitted} δολος [ασελγεια]{.greek-omitted} [ασελγειαι]{.greek-added} οφθαλμος πονηρος [βλασφημια]{.greek-omitted} [βλασφημιαι]{.greek-added} [υπερηφανια]{.greek-omitted} [υπερηφανιαι]{.greek-added} αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν εκπορευεται [και]{.greek-omitted} [κακεινα]{.greek-added} κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελησε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} [προς]{.greek-omitted} [παρα]{.greek-added} τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συροφοινισσα]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} γενει και [η]{.unclear}ρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε [αποκριθεισα]{.greek-added} [απεκριθη]{.greek-omitted} [και]{.greek-omitted} λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των ψιχιων [των]{.greek-omitted} [παιδιων]{.greek-omitted}[7:28]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [απεκριθη]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ναι]{.greek-omitted} [κυριε]{.greek-omitted} [και]{.greek-omitted} [γαρ]{.greek-omitted} [τα]{.greek-omitted} [κυναρια]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [τραπεζης]{.greek-omitted} [εσθιει]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [ψιχιων]{.greek-omitted} των παιδιων[7:28 | instance no. 2]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι [της]{.greek-omitted} κλινης[7:30]{.aside}

και παλιν εξελθων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις παμπολλου οχλου οντος και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις [οικον]{.greek-omitted} [οικους]{.greek-added} αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκασι]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε χορτασαι αρτων επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} [τω]{.greek-omitted} [τωι]{.greek-added} οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και [ταυτα]{.greek-added} ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παραθειναι και αυτα[8:7]{.aside}

[και]{.greek-added} εφαγον [δε]{.greek-omitted} και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες [ως]{.greek-omitted} [ωσει]{.greek-added} τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [ευθεως]{.greek-omitted} εμβας εις [το]{.greek-omitted} πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη [δαλμανουθα]{.greek-omitted} [δαλμανουθε]{.greek-added}[8:10]{.aside}

και εξηλθον οι [φαρι]{.greek-added} [φαρισαιοι]{.greek-omitted} [και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [συζητειν]{.greek-omitted} [αυτω]{.greek-omitted} [ζητουντες]{.greek-omitted} [παρ]{.greek-omitted} [αυτου]{.greek-omitted} [σημειον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [πειραζοντες]{.greek-omitted} [αυτον]{.greek-omitted}[8:11]{.aside}

[σαιοι]{.greek-added} [και]{.greek-omitted} [εξηλθον]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} και ηρξαντο συζητειν αυτω ζητουντες [παρ]{.greek-omitted} [αυτου]{.greek-omitted} [σημειον]{.greek-omitted} απο του [ουρανου]{.greek-abbr} [σημειον]{.greek-added} [απ]{.greek-added} [αυτου]{.greek-added} πειραζοντες αυτον[8:11 | instance no. 2]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε [εν]{.greek-added} [ταις]{.greek-added} [καρδιαις]{.greek-added} [υμων]{.greek-added} [ολιγοπιστοι]{.greek-added} οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους πληρεις κλασματων [ηρατε]{.greek-omitted} [ελαβετε]{.greek-added} λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις πως [ου]{.greek-omitted} [ουπω]{.greek-added} συνιετε[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βησθαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος [αυτου]{.greek-added} του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} [οτι]{.greek-omitted} ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν [αυτον]{.greek-omitted} [αναβλεψαι]{.greek-omitted} [και]{.greek-omitted} [αποκατεσταθη]{.greek-omitted} [και]{.greek-omitted} [ενεβλεψεν]{.greek-omitted} [τηλαυγως]{.greek-omitted} [απαντας]{.greek-omitted}[8:25]{.aside}

[ειτα]{.greek-omitted} [παλιν]{.greek-omitted} [επεθηκεν]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [οφθαλμους]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εποιησεν]{.greek-omitted} αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τηλαυγως απαντας[8:25 | instance no. 2]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν [τη]{.greek-omitted} [τηι]{.greek-added} κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι [υπο]{.greek-added} [απο]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} των αρχιερεων και [των]{.greek-omitted} γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον [ο]{.greek-omitted} [πετρος]{.greek-omitted} [ηρξατο]{.greek-omitted} [επιτιμαν]{.greek-omitted} [αυτω]{.greek-omitted}[8:32]{.aside}

[και]{.greek-omitted} [παρρησια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ελαλει]{.greek-omitted} [και]{.greek-omitted} [προσλαβομενος]{.greek-omitted} [αυτον]{.greek-omitted} ο πετρος ηρξατο επιτιμαν αυτω[8:32 | instance no. 2]{.aside}

ο δε [επιστραφεις]{.greek-omitted} [στραφεις]{.greek-added} και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [οστις]{.greek-omitted} [θελει]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [ακολουθειν]{.greek-omitted} [απαρνησασθω]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [αρατω]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ακολουθειτω]{.greek-omitted} [μοι]{.greek-omitted}[8:34]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [συν]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[8:34 | instance no. 2]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου ουτος σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} εαν [κερδηση]{.greek-omitted} τον κοσμον ολον [κερδηση]{.greek-added} και [ζημιωθη]{.greek-omitted} την ψυχην αυτου [ζημιωθη]{.greek-added}[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν [ως]{.greek-omitted} [ωσει]{.greek-added} χιων οια γναφευς επι της γης ου δυναται λευκαναι[9:3]{.aside}

και [ωφθη]{.greek-omitted} [ωφθησαν]{.greek-added} αυτοις ηλιας συν [μωση]{.greek-omitted} [μωσει]{.greek-added} και ησαν συλλαλουντες [τω]{.greek-omitted} [τωι]{.greek-added} [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωσει]{.greek-added} μιαν και [ηλια]{.greek-omitted} [ηλιαν]{.greek-added} μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ [εκφοβοι]{.greek-omitted} [ε[μ]{.unclear}φοβοι]{.greek-added}[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ινα μηδενι διηγησωνται α ειδον ει μη [οταν]{.greek-omitted} ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

κ[αι]{.unclear} τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες [οτι]{.greek-omitted} [τι]{.greek-added} λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα [τα]{.greek-added} παντα [καθως]{.greek-added} [γεγραπται]{.greek-added} και [πως]{.greek-omitted} [γεγραπται]{.greek-omitted} επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι [και]{.greek-omitted} ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ [αυτον]{.greek-omitted} [αυτω]{.greek-added}[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς [αυτους]{.greek-omitted} [εαυτους]{.greek-added}[9:16]{.aside}

και αποκριθεις εις εκ του οχλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} διδασκαλε ηνεγκα τον υιον μου προς σε εχοντα πνευμα αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και [ιδων]{.greek-omitted} [ιδον]{.greek-added} αυτον ευθεως το πνευμα εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος [χρονος]{.greek-omitted} [εστιν]{.greek-omitted} [ως]{.greek-omitted} [τουτο]{.greek-omitted} [γεγονεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [παιδιοθεν]{.greek-omitted}[9:21]{.aside}

[και]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [ποσος]{.greek-omitted} [χρονος]{.greek-omitted} εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παιδιοθεν]{.greek-omitted} [παιδοθεν]{.greek-added}[9:21 | instance no. 2]{.aside}

και πολλακις αυτον και εις το πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [το]{.greek-omitted} ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πνευματι τω ακαθαρτω λεγων αυτω το πνευμα το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου [επηρωτων]{.greek-omitted} [επερωτων]{.greek-added} αυτον κατ ιδιαν οτι [δια]{.greek-added} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και [ηλθεν]{.greek-omitted} [ελθοντες]{.greek-added} εις καπερνα[ο]{.unclear}υμ [και]{.greek-omitted} εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και [λαβων]{.greek-omitted} [ιδων]{.greek-added} παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δ[ε]{.unclear}χεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη [δε]{.greek-omitted} αυτω [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} λεγων διδασκαλε ειδομεν τινα τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και εκωλυσαμεν αυτον οτι ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστι]{.greek-added} [καθ]{.greek-added} [ημων]{.greek-added} [υπερ]{.greek-added} [ημων]{.greek-added} εστιν [καθ]{.greek-omitted} [υμων]{.greek-omitted} [υπερ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted}[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν ονοματι [μου]{.greek-omitted} οτι [χριστου]{.greek-abbr} [εστε]{.greek-omitted} [εσται]{.greek-added} αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεσει]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει περικειται [λιθος]{.greek-omitted} [μυλικος]{.greek-omitted} [μυλος]{.greek-added} [ονικος]{.greek-added} περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιση]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν [η]{.greek-added} εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} σοι εισελθειν εις την ζωην χωλον η [τους]{.greek-omitted} δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια [αλι]{.greek-omitted} αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο [αρτυσετε]{.greek-omitted} [αρτυσεται]{.greek-added} εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας δια του περαν του ιορδανου και συμπορευονται [οχλοι]{.greek-added} παλιν [οχλοι]{.greek-omitted} προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι επηρωτησαν αυτον ει εξεστιν [ανδρι]{.greek-omitted} [ανδρα]{.greek-added} γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε [απο]{.greek-added} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [υμιν]{.greek-omitted} [ενετειλατο]{.greek-omitted} [μωσης]{.greek-omitted}[10:3]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [κριθεις]{.greek-added} ειπεν αυτοις τι υμιν ενετειλατο μωσης[10:3 | instance no. 2]{.aside}

οι δε ειπον μωσης [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων [εγραψεν]{.greek-omitted} [επετρεψεν]{.greek-added} υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} [αυτου]{.greek-added} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [τουτου]{.greek-added} [του]{.greek-omitted} [αυτου]{.greek-omitted} επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ [αυτην]{.greek-omitted} [αυτη]{.greek-added}[10:11]{.aside}

και εαν γυνη απολυση τον [ιδιον]{.greek-added} ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη [εις]{.greek-omitted} [εν]{.greek-added} [αυτην]{.greek-omitted} [αυτη]{.greek-added}[10:15]{.aside}

και [[―]{.gap}γκαλισαμενος]{.greek-added} [εναγκαλισαμενος]{.greek-omitted} [[αγκαλισαμενος]{.corr}]{.greek-added} αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ευλογησεν]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη [εις]{.corr} ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης μη αποστερησης τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα [παντα]{.greek-omitted} [εφυλαξαμην]{.greek-omitted} [εκ]{.greek-omitted} [νεοτητος]{.greek-omitted} [μου]{.greek-omitted}[10:20]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ταυτα]{.greek-omitted} παντα εφυλαξαμην εκ νεοτητος μου [τι]{.greek-added} [ετι]{.greek-added} [υστερω]{.greek-added}[10:20 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν σοι υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} και δευρο ακολουθει μοι αρας τον [σταυρον]{.greek-abbr} [σου]{.greek-added}[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις [τεκνα]{.greek-omitted} [τεκνια]{.greek-added} πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια της τρυμαλιας της ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε [αυτοις]{.greek-omitted} ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [τω]{.greek-added} [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν [τη]{.greek-omitted} [τηι]{.greek-added} οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και [εθαμβουντο]{.greek-omitted} [εξεθαμβουντο]{.greek-added} και ακολουθουντες εφοβουντο [και]{.greek-omitted} [παραλαβων]{.greek-omitted} [παλιν]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγειν]{.greek-omitted} [τα]{.greek-omitted} [μελλοντα]{.greek-omitted} [αυτω]{.greek-omitted} [συμβαινειν]{.greek-omitted}[10:32]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [αναβαινοντες]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [προαγων]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εθαμβουντο]{.greek-omitted} [και]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} και παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32 | instance no. 2]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [τοις]{.greek-added} [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και εμπαιξουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και μαστιγωσουσιν αυτον και εμπτυσουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι [του]{.greek-added} ζεβεδαιου λεγοντες [διδασκαλε]{.greek-omitted} θελομεν ινα ο εαν αιτησωμεν [σε]{.greek-added} ποιησης ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-omitted} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-omitted} προσκαλεσαμενος [αυτους]{.greek-omitted} λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι [μεγας]{.greek-omitted} εν υμιν [μεγας]{.greek-added} εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη [γενεσθαι]{.greek-added} [εν]{.greek-added} [υμιν]{.greek-added} [πρωτος]{.greek-added} [εστω]{.greek-added} [παντων]{.greek-added} υμων [γενεσθαι]{.greek-omitted} [πρωτος]{.greek-omitted} [εσται]{.greek-omitted} [παντων]{.greek-omitted} δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [ο]{.greek-added} υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος [[ναζοραιος]{.corr}]{.greek-added} εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-omitted} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς [αυτον]{.greek-added} τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος ειπεν αυτω [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} εις βηθσφαγη και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον [ουδεπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκε]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι ποιειτε [τουτο]{.greek-omitted} [τουτω]{.greek-added} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει [[αποστελει]{.corr}]{.greek-added} ωδε[11:3]{.aside}

απηλθον δε και ευρον [τον]{.greek-added} πωλον δεδεμενον προς την θυραν εξω επι [του]{.greek-omitted} [της]{.greek-added} αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επ [αυτω]{.greek-omitted} [αυτον]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ των δενδρων και εστρωννυον εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

[ευλογημενη]{.corr} [η]{.corr} [ερχομενη]{.corr} βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος [παντα]{.greek-omitted} [παντας]{.greek-added} οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινα]{.greek-added}[11:12]{.aside}

[σε]{.greek-added} [και]{.greek-omitted} [τη]{.greek-omitted} [επαυριον]{.greek-omitted} [εξελθοντων]{.greek-omitted} [αυτων]{.greek-omitted} [απο]{.greek-omitted} [βηθανιας]{.greek-omitted} [επεινασεν]{.greek-omitted}[11:12 | instance no. 2]{.aside}

και ιδων συκην [απο]{.greek-added} μακροθεν εχουσαν φυλλα ηλθεν ει αρα ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον [φαγοι]{.greek-omitted} [φαγη]{.greek-added} και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα [και]{.greek-omitted} [εισελθων]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [ιερον]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκβαλλειν]{.greek-omitted} [τους]{.greek-omitted} [πωλουντας]{.greek-omitted} [και]{.greek-omitted} [αγοραζοντας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [τραπεζας]{.greek-omitted} [των]{.greek-omitted} [κολλυβιστων]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [καθεδρας]{.greek-omitted} [των]{.greek-omitted} [πωλουντων]{.greek-omitted} [τας]{.greek-omitted} [περιστερας]{.greek-omitted} [κατεστρεψεν]{.greek-omitted}[11:15]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} και εισελθων [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15 | instance no. 2]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε [εποιησατε]{.greek-omitted} [ποιειτε]{.greek-added} αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν [[απολεσουσιν]{.corr}]{.greek-added} εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηρανθη]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι α [λεγει]{.greek-omitted} [ειπη]{.greek-added} [γινεται]{.greek-omitted} [γινονται]{.greek-added} εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι αιτησθε [πιστευετε]{.greek-omitted} [πιστευοντες]{.greek-added} οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και [οταν]{.greek-omitted} [οτε]{.greek-added} [στηκητε]{.greek-omitted} [στηκετε]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

[ει]{.corr} [δε]{.corr} [υμεις]{.corr} [ουκ]{.corr} [αφιετε]{.corr} [ουδε]{.corr} [ο]{.corr} [[πατηρ]{.greek-abbr}]{.corr} [υμων]{.corr} [ο]{.corr} [εν]{.corr} [τοις]{.corr} [[ουρανοις]{.greek-abbr}]{.corr} [αφησει]{.greek-omitted} [[αφη]{.corr}]{.greek-added} [[υμιν]{.corr}]{.greek-added} [τα]{.corr} [παραπτωματα]{.corr} [υμων]{.corr} [[λεγω]{.corr}]{.greek-added} [[δε]{.corr}]{.greek-added} [[υμιν]{.corr}]{.greek-added} [[αι[τ]{.unclear}ειτε]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [[δοθησεται]{.corr}]{.greek-added} [[υμιν]{.corr}]{.greek-added} [[ζητειτε]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [[ευρησετε]{.corr}]{.greek-added} [[κρουετε]{.corr}]{.greek-added} [[[και]{.unclear}]{.corr}]{.greek-added} [[ανοιγησεται]{.corr}]{.greek-added} [[υμιν]{.corr}]{.greek-added} [[πας]{.corr}]{.greek-added} [[γαρ]{.corr}]{.greek-added} [[ο]{.corr}]{.greek-added} [[αιτων]{.corr}]{.greek-added} [[λαμβανει]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [[ο]{.corr}]{.greek-added} [[ζητων]{.corr}]{.greek-added} [[ευρησκει]{.corr}]{.greek-added} [[και]{.corr}]{.greek-added} [[τω]{.corr}]{.greek-added} [[κρουοντι]{.corr}]{.greek-added} [[ανοιγησεται]{.corr}]{.greek-added}[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις [και]{.greek-omitted} [τις]{.greek-omitted} [σοι]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [ταυτην]{.greek-omitted} [εδωκεν]{.greek-omitted} [ινα]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιης]{.greek-omitted}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον [λαον]{.greek-omitted} [οχλον]{.greek-added} απαντες γαρ ειχον τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον λιθοβολησαντες εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους [αλλους]{.greek-omitted} [δουλους]{.greek-added} τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα υιον εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον προς αυτους εσχατον λεγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε [αποκτεινωμεν]{.greek-omitted} [αποκτεινομεν]{.greek-added} αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και [εξε]{.greek-added} [εξεβαλον]{.greek-omitted} [εξω]{.greek-omitted} [του]{.greek-omitted} [αμπελωνος]{.greek-omitted}[12:8]{.aside}

[και]{.greek-omitted} [λαβοντες]{.greek-omitted} [αυτον]{.greek-omitted} [απεκτειναν]{.greek-omitted} [και]{.greek-omitted} [εξεβαλον]{.greek-omitted} [βαλον]{.greek-added} εξω του αμπελωνος[12:8 | instance no. 2]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την [υποκρισιν]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τι]{.greek-omitted} [με]{.greek-omitted} [πειραζετε]{.greek-omitted} [φερετε]{.greek-omitted} [μοι]{.greek-omitted} [δηναριον]{.greek-omitted} [ινα]{.greek-omitted} [ιδω]{.greek-omitted}[12:15]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ειδως]{.greek-omitted} [αυτων]{.greek-omitted} [την]{.greek-omitted} υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι δηναριον ινα ιδω[12:15 | instance no. 2]{.aside}

οι δε ηνεγκαν [αυτω]{.greek-added} και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και εξαναστηση σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και [οι]{.greek-added} [επτα]{.greek-added} ελαβον αυτην [οι]{.greek-omitted} [επτα]{.greek-omitted} και ουκ αφηκαν σπερμα εσχατη παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε γαμισκονται αλλ [εισιν]{.greek-omitted} ως αγγελοι [οι]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} [εισιν]{.greek-added} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-abbr} ζωντων υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων εις των γραμματεων ακουσας αυτων συζητουντων ειδως οτι καλως αυτοις απεκριθη [επη]{.greek-added} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [ποια]{.greek-omitted} [εστιν]{.greek-omitted} [πρωτη]{.greek-omitted} [παντων]{.greek-omitted} [εντολη]{.greek-omitted}[12:28]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [εις]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [ακουσας]{.greek-omitted} [αυτων]{.greek-omitted} [συζητουντων]{.greek-omitted} [ειδως]{.greek-omitted} [οτι]{.greek-omitted} [καλως]{.greek-omitted} [αυτοις]{.greek-omitted} [απεκριθη]{.greek-omitted} επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη [παντων]{.greek-omitted} [πασων]{.greek-added} εντολη[12:28 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω [οτι]{.greek-omitted} [αυτη]{.greek-added} πρωτη [πασων]{.greek-added} [παντων]{.greek-omitted} [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολη]{.greek-added} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

[και]{.greek-omitted} αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης [της]{.greek-omitted} καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και [των]{.greek-added} θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} [του]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} [και]{.greek-omitted} [ποθεν]{.greek-omitted} [πως]{.greek-added} [ουν]{.greek-added} [εστιν]{.greek-added} [αυτου]{.greek-added} υιος [αυτου]{.greek-omitted} [εστιν]{.greek-omitted} και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και [φιλουντων]{.greek-added} ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και πρωτοκλισιας εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες [τας]{.greek-omitted} [οικιας]{.greek-omitted} [των]{.greek-omitted} [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [ουτοι]{.greek-omitted} [ληψονται]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted}[12:40]{.aside}

[οι]{.greek-omitted} [κατεσθιοντες]{.greek-omitted} τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40 | instance no. 2]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} ο [ιησους]{.greek-abbr} κατεναντι του [γαζοφυλακο]{.greek-added} [γαζοφυλακιου]{.corr} εθεωρει πως ο οχλος βαλλει χαλκον εις το [γαζοφυλακιον]{.greek-omitted} [γαζοφυλακειον]{.greek-added} και πολλοι πλουσιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν [οτι]{.greek-omitted} [οτη]{.greek-added} η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και [ιδε]{.greek-added} ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη [ωδε]{.greek-added} λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη παντα ταυτα συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-omitted} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι [ταυτα]{.greek-added} αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και [εσονται]{.greek-omitted} [εσοντε]{.greek-added} σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι [ηγεμονων]{.greek-omitted} [ηγεμονας]{.greek-added} και [βασιλεων]{.greek-omitted} [βασιλεις]{.greek-added} [σταθησεσθε]{.greek-omitted} [αχθησεσθε]{.greek-added} ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε αγαγωσιν υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [μεριμνατε]{.greek-added} τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το [βδελυγμα]{.greek-omitted} [βδελλυγμα]{.greek-added} της ερημωσεως το ρηθεν [υπο]{.greek-omitted} [δια]{.greek-added} δανιηλ του προφητου εστως [οπου]{.greek-omitted} [εν]{.greek-added} [τοπω]{.greek-added} [ω]{.greek-added} ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο [δε]{.greek-omitted} επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος [η]{.greek-added} [εν]{.greek-added} [σαββατω]{.greek-added}[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το [αποπλαναν]{.greek-omitted} [αποπλανησαι]{.greek-added} ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος [σκοτισθησεται]{.greek-omitted} [σκοτασθησεται]{.greek-added} και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης ηδη ο κλαδος απαλος γενηται και εκφυη τα φυλλα γινωσκετε οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν ταυτα [γινομενα]{.greek-added} ιδητε [γινομενα]{.greek-omitted} γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [αχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης η ωρας ουδεις οιδεν ουδε οι αγγελοι οι εν [ουρανω]{.greek-abbr} ουδε ο υιος ει μη ο [πατηρ]{.greek-abbr} [μου]{.greek-added} [μονος]{.greek-added}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν [και]{.greek-omitted} εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η [μεσονυκτιου]{.greek-omitted} [μεσονυκτιω]{.greek-added} η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης [ευρη]{.greek-omitted} [ευρησει]{.greek-added} υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον [εν]{.greek-omitted} δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο [το]{.greek-added} [μυρον]{.greek-added} πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-added} αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε [αυτους]{.greek-omitted} ευ ποιησαι [αυτους]{.greek-added} εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη εποιησεν [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα [εις]{.greek-omitted} [προς]{.greek-added} τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και ο ιουδας ο ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν [την]{.greek-added} [απεναντι]{.greek-added} [υμων]{.greek-added} και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει [ανωγεον]{.greek-omitted} [ανωγαιον]{.greek-added} μεγα εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

[και]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} [τον]{.greek-added} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του [γενηματος]{.greek-omitted} [γεννηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη οτι γεγραπται παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω [ει]{.greek-added} και [ει]{.greek-omitted} παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν η [δις]{.greek-omitted} αλεκτορα φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε εκπερισσου [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν με δεη συναποθανειν σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ [ου]{.greek-omitted} [ουχ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους [καθευ]{.greek-added} [καθευδοντας]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [σιμων]{.greek-omitted} [καθευδεις]{.greek-omitted} [ουκ]{.greek-omitted} [ισχυσας]{.greek-omitted} [μιαν]{.greek-omitted} [ωραν]{.greek-omitted} [γρηγορησαι]{.greek-omitted}[14:37]{.aside}

[δοντας]{.greek-added} [και]{.greek-omitted} [ερχεται]{.greek-omitted} [και]{.greek-omitted} [ευρισκει]{.greek-omitted} [αυτους]{.greek-omitted} [καθευδοντας]{.greek-omitted} και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37 | instance no. 2]{.aside}

γρηγορειτε και προσευχεσθε ινα μη [εισελθητε]{.greek-omitted} [ελθητε]{.greek-added} εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ [αυτων]{.greek-added} οι οφθαλμοι [καταβαρουμενοι]{.greek-added} [αυτων]{.greek-omitted} [βεβαρημενοι]{.greek-omitted} και ουκ ηδεισαν τι αυτω αποκριθωσι[ν]{.unclear} [[αποκριθωσι]{.corr}]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις ων των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γραμματεων και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

[και]{.greek-omitted} ο [δε]{.greek-added} πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις [το]{.greek-added} μεσον [επηρωτησεν]{.greek-omitted} [επερωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο υιος του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν [αυτω]{.greek-added} εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας [αυτου]{.greek-added} τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added}[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα [[ιησου]{.greek-abbr}]{.greek-added} του [ναζωραιου]{.greek-added} [ναζαρηνου]{.greek-omitted} [ιησου]{.greek-omitted} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε επισταμαι τι συ λεγεις και [εξηλθεν]{.greek-omitted} [εξελθων]{.greek-added} εξω εις το [προαυλιον]{.greek-omitted} [προαυλειον]{.greek-added} και [ο]{.greek-added} αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνησατο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια [σου]{.greek-omitted} [σοι]{.greek-added} ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι [ουκ]{.greek-omitted} [ου]{.greek-added} [οιδα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted} [τουτον]{.greek-omitted} [ον]{.greek-omitted} [λεγετε]{.greek-omitted}[14:71]{.aside}

[κ]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ηρξατο]{.greek-omitted} [αναθεματιζειν]{.greek-omitted} [και]{.greek-omitted} [ομνυναι]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71 | instance no. 2]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις απαρνηση με τρις και [επιβαλων]{.greek-omitted} [επιλαβων]{.greek-added} [εκλαιεν]{.greek-omitted} [εκλαιε]{.greek-added}[14:72]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος [παλιν]{.greek-omitted} επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [επεγινωσκε]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδεδωκεισαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεπεισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [λεγοντες]{.greek-added} σταυρωσον αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε περισσοτερως εκραξαν σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} φραγελλωσας ινα σταυρωθη[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον [εσω]{.greek-omitted} [εως]{.greek-added} της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα σταυρωσωσιν αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} [παραγοντα]{.greek-omitted} τινα [σιμωνα]{.greek-omitted} [κυρηναιον]{.greek-omitted} [ερχομενον]{.greek-omitted} [απ]{.greek-omitted} [αγρου]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αλεξανδρου]{.greek-omitted} [και]{.greek-omitted} [ρουφου]{.greek-omitted} [ινα]{.greek-omitted} [αρη]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted} [αυτου]{.greek-omitted}[15:21]{.aside}

[και]{.greek-omitted} [αγγαρευουσιν]{.greek-omitted} παραγοντα [τινα]{.greek-omitted} σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον σταυρον αυτου[15:21 | instance no. 2]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και σταυρωσαντες αυτον [διαμεριζονται]{.greek-omitted} [διεμερισαντο]{.greek-added} τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου [επιγεγραμμενη]{.greek-omitted} [γεγραμμενη]{.greek-added} ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [σταυρουσι]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και [καταβα]{.greek-omitted} [καταβηθι]{.greek-added} απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

[ομοιως]{.greek-omitted} [και]{.greek-omitted} οι [δε]{.greek-added} αρχιερεις εμπαιζοντες προς αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν αυτω και οι συνεσταυρωμενοι αυτω ωνειδιζον αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο [εφ]{.greek-omitted} [ολην]{.greek-omitted} [εν]{.greek-added} [παση]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [γην]{.greek-omitted} [γη]{.greek-added} εως ωρας ενατης[15:33]{.aside}

και τη ωρα τη ενατη εβοησεν ο [ιησους]{.greek-abbr} φωνη [μεγαλη]{.greek-omitted} [μεγαληι]{.greek-added} λεγων ελωι ελωι λιμα [σαβαχθανι]{.greek-omitted} [σαβαχθανη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος υιος ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και [η]{.greek-added} σαλωμη[15:40]{.aside}

αι [και]{.greek-omitted} οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι [ηκολουθησαν]{.greek-added} αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο [αριμαθαιας]{.greek-omitted} [αριματθαιας]{.greek-added} ευσχημων βουλευτης [ος]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ην]{.greek-omitted} [προσδεχομενος]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τολμησας]{.greek-omitted} [εισηλθεν]{.greek-omitted} [προς]{.greek-omitted} [πιλατον]{.greek-omitted} [και]{.greek-omitted} [ητησατο]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted}[15:43]{.aside}

[ηλθεν]{.greek-omitted} [ιωσηφ]{.greek-omitted} [ο]{.greek-omitted} [απο]{.greek-omitted} [αριμαθαιας]{.greek-omitted} [ευσχημων]{.greek-omitted} [βουλευτης]{.greek-omitted} ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43 | instance no. 2]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισσε]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που [τιθεται]{.greek-omitted} [τεθειται]{.greek-added}[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια [η]{.greek-added} [του]{.greek-added} ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον εσταυρωμενον ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω [πετρω]{.greek-omitted} [πετρωι]{.greek-added} οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε [καθως]{.greek-omitted} [ιδου]{.greek-added} [ειπεν]{.greek-omitted} [ειπον]{.greek-added} υμιν[16:7]{.aside}

και εξελθουσαι [ταχυ]{.greek-added} εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

[αναστας]{.greek-omitted} [[αναστας]{.greek-added} δε πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} [και]{.greek-omitted} [κλαιουσιν]{.greek-omitted}[16:10]{.aside}

[εκεινη]{.greek-omitted} [πορευθεισα]{.greek-omitted} [απηγγειλεν]{.greek-omitted} [τοις]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [γενομενοις]{.greek-omitted} [πενθουσιν]{.greek-omitted} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10 | instance no. 2]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον [εκ]{.greek-added} [νεκρων]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση [τη]{.greek-omitted} [τηι]{.greek-added} κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες [εκηρυξαν]{.greek-omitted} [εκηρυττον]{.greek-added} πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

