---
title: "Collation of Byz^RP^ vs 31295 (1295)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1295 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31295).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1295                                   	| λογος                              	|
| 1295 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1295 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1295               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1295                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1295 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1295                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 13

[και]{.greek-omitted} [εσκανδαλιζοντο]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [προφητης]{.greek-omitted} [ατιμος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πατριδι]{.greek-omitted} [αυτου]{.greek-omitted} και εν τη οικια αυτου[13:57]{.aside}

και ουκ εποιησεν εκει δυναμεις πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο τετραρχης την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και ειπεν τοις παισιν αυτου ουτος εστιν ιωαννης ο βαπτιστης αυτος ηγερθη απο των νεκρων και δια τουτο αι δυναμεις ενεργουσιν [εν]{.greek-omitted} αυτω[14:2]{.aside}

ο γαρ ηρωδης [τοτε]{.greek-added} κρατησας τον ιωαννην εδησεν αυτον και εθετο εν [τη]{.greek-added} φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου[14:3]{.aside}

ελεγεν γαρ αυτω ο ιωαννης ουκ εξεστιν σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων δε [αγομενων]{.greek-omitted} [[γεν]{.unclear}ομεν[οι]{.unclear}ς]{.greek-added} του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και ηρεσεν τω ηρωδη[14:6]{.aside}

οθεν μεθ ορκο[υ]{.unclear} [ω]{.unclear}μολο[γησεν]{.greek-supplied} αυτη δ[ουνα]{.unclear}ι ο εαν [αι]{.unclear}τησηται[14:7]{.aside}

[η]{.greek-supplied} [δε]{.greek-supplied} [προ]{.greek-supplied}βιβασθεισα [υπο]{.greek-supplied} [της]{.greek-supplied} [μητρος]{.greek-abbr} αυτης [ει[πε]{.unclear}ν]{.greek-added} δος μοι φησιν ωδε επι [πι]{.unclear}νακι την κεφαλην ιωαννου του βαπτι[στου]{.greek-supplied}[14:8]{.aside}

και ελυπηθη ο βασιλ[ευς]{.unclear} δια δε τους ορκους και τους συνανακειμενους εκελευσεν δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλησεν]{.greek-added} τον ιωαννην εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι πινακι και εδοθη τω κορασιω και ηνεγκεν τ[η]{.unclear} [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθον[τ]{.unclear}ες οι μαθηται α[υ]{.unclear}του ηραν [αυτου]{.greek-added} το σωμα και εθαψαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} ανεχωρησεν εκειθεν εν πλοιω εις ερημον τοπον κατ ιδιαν και ακουσαντες οι οχλοι ηκολουθησαν αυτω πεζη απο των πολεων[14:13]{.aside}

και εξελθων ο [ιησους]{.greek-abbr} ειδεν πολυν οχλον και εσπλαγχνισθη επ αυτοις και εθεραπευσεν τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται αυτου λεγοντες ερημος εστιν ο τοπος και η ωρα ηδη παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας κωμας αγορασωσιν εαυτοις βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε ειπεν [φερετε]{.greek-omitted} [φερεται]{.greek-added} μοι αυτους ωδε[14:18]{.aside}

και [κελευσας]{.greek-omitted} [εκελευσεν]{.greek-added} τους οχλους ανακλιθηναι επι [τους]{.greek-omitted} [του]{.greek-added} [χορτους]{.greek-omitted} [χορτου]{.greek-added} [και]{.greek-added} λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} ευλογησεν και κλασας εδωκεν τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε [εσθιοντες]{.greek-omitted} [αισθιοντες]{.greek-added} ησαν ανδρες ωσει πεντακισχιλιοι χωρις γυναικων και παιδιων[14:21]{.aside}

και ευθεως ηναγκασεν [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας εμβηναι εις το πλοιον και προαγειν [αυτον]{.greek-omitted} εις το περαν εως ου απολυση τους οχλους[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος κατ ιδιαν προσευξασθαι οψιας δε γενομενης μονος ην εκει[14:23]{.aside}

το δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον [υπο]{.greek-omitted} [απο]{.greek-added} των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος [απηλθεν]{.greek-omitted} [ηλθεν]{.greek-added} προς αυτους [ο]{.greek-omitted} [ιησους]{.greek-omitted} περιπατων επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασσαν]{.greek-added}[14:25]{.aside}

[και]{.greek-omitted} ιδοντες [δε]{.greek-added} αυτον οι μαθηται [περιπατουντα]{.greek-added} επι [την]{.greek-omitted} [της]{.greek-added} [θαλασσαν]{.greek-omitted} [θαλασσης]{.greek-added} [περιπατουντα]{.greek-omitted} εταραχθησαν λεγοντες οτι φαντασμα εστιν και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} λεγων θαρσειτε εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε αυτω ο πετρος ειπεν [κυριε]{.greek-abbr} ει συ ει κελευσον με προς σε ελθειν [επι]{.greek-omitted} [επει]{.greek-added} τα υδατα[14:28]{.aside}

ο δε ειπεν ελθε και καταβας [ο]{.greek-added} [πετρος]{.greek-added} απο του πλοιου [ο]{.greek-omitted} [πετρος]{.greek-omitted} περιεπατησεν επι τα υδατα ελθειν προς τον [ιησουν]{.greek-abbr}[14:29]{.aside}

[βλεπων]{.greek-omitted} [βλεπον]{.greek-added} δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι εκραξεν λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} [εκτεινας]{.greek-omitted} [εκτινας]{.greek-added} την χειρα επελαβετο αυτου και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και [εμβαντων]{.greek-omitted} [ενβαντων]{.greek-added} αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω [ελθοντες]{.greek-omitted} προσεκυνησαν αυτω λεγοντες αληθως [θεου]{.greek-abbr} [υιος]{.greek-abbr} ει[14:33]{.aside}

και διαπερασαντες ηλθον [εις]{.greek-omitted} [επι]{.greek-added} την γην [γεννησαρετ]{.greek-omitted} [γεννησαρεθ]{.greek-added}[14:34]{.aside}

και [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον [αψωνται]{.greek-omitted} [αψονται]{.greek-added} του κρασπεδου του ιματιου αυτου και οσοι [αν]{.greek-added} ηψαντο διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτε προσερχονται [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [οι]{.greek-omitted} απο ιεροσολυμων [φαρισαιοι]{.greek-added} [και]{.greek-added} γραμματεις [και]{.greek-omitted} [φαρισαιοι]{.greek-omitted} λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου παραβαινουσιν την παραδοσιν των πρεσβυτερων ου γαρ νιπτονται τας χειρας αυτων οταν αρτον [εσθιωσιν]{.greek-omitted} [αισθιωσιν]{.greek-added}[15:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και υμεις [παραβαινετε]{.greek-omitted} [παραβαινεται]{.greek-added} την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} ενετειλατο λεγων τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} [σου]{.greek-added} και ο [κακολογων]{.greek-omitted} [κακολογον]{.greek-added} [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[15:4]{.aside}

υμεις δε λεγετε ος αν ειπη τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} δωρον ο εαν εξ εμου ωφεληθης [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[και]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [τιμησει]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [η]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} και ηκυρωσατε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:6]{.aside}

υποκριται καλως προεφητευσεν [ησαιας]{.greek-added} περι υμων [ησαιας]{.greek-omitted} λεγων[15:7]{.aside}

[εγγιζει]{.greek-omitted} [μοι]{.greek-omitted} ο λαος ουτος [τω]{.greek-omitted} [στοματι]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} τοις χειλεσιν με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[15:8]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις [ακουετε]{.greek-omitted} [ακουσατε]{.greek-added} και συνιετε[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} αλλα το εκπορευομενον εκ του στοματος τουτο κοινοι τον [ανθρωπον]{.greek-abbr}[15:11]{.aside}

τοτε προσελθοντες οι μαθηται αυτου ειπον αυτω οιδας οτι οι φαρισαιοι ακουσαντες τον λογον εσκανδαλισθησαν[15:12]{.aside}

ο δε αποκριθεις ειπεν πασα φυτεια ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο ουρανιος εκριζωθησεται[15:13]{.aside}

αφετε αυτους οδηγοι εισιν τυφλοι τυφλων τυφλος δε τυφλον εαν [οδηγη]{.greek-omitted} [οδηγει]{.greek-added} αμφοτεροι εις βοθυνον [πεσουνται]{.greek-omitted} [εμπεσουνται]{.greek-added}[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν ακμην και υμεις ασυνετοι [εστε]{.greek-omitted} [εσται]{.greek-added}[15:16]{.aside}

ουπω [νοειτε]{.greek-omitted} [νοειται]{.greek-added} οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ της καρδιας [εξερχεται]{.greek-omitted} [εξερχονται]{.greek-added} κακεινα κοινοι τον [ανθρωπον]{.greek-abbr}[15:18]{.aside}

εκ γαρ της καρδιας εξερχονται διαλογισμοι πονηροι φονοι μοιχειαι πορνειαι κλοπαι ψευδομαρτυριαι βλασφημιαι[15:19]{.aside}

ταυτα εστιν τα κοινουντα τον [ανθρωπον]{.greek-abbr} το δε ανιπτοις χερσιν φαγειν ου κοινοι τον [ανθρωπον]{.greek-abbr}[15:20]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα μερη τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα [εκραυγασεν]{.greek-omitted} [εκραξεν]{.greek-added} αυτω λεγουσα ελεησον με [κυριε]{.greek-abbr} [υιε]{.greek-omitted} [υιος]{.greek-added} [δαυιδ]{.greek-abbr} η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε ουκ απεκριθη αυτη λογον και προσελθοντες οι μαθηται αυτου ηρωτων αυτον λεγοντες απολυσον αυτην οτι κραζει οπισθεν ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην ει μη εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

η δε ελθουσα [προσεκυνησεν]{.greek-omitted} [προσεκυνη]{.greek-added} αυτω λεγουσα [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [βοηθη]{.greek-added} μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ εστιν καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε ειπεν ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των ψιχιων των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη ω γυναι μεγαλη σου η [πιστις]{.greek-omitted} [πιστης]{.greek-added} γενηθητω σοι ως θελεις και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} ηλθεν παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος εκαθητο εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ εαυτων χωλους τυφλους [κυλλους]{.greek-added} κωφους [κυλλους]{.greek-omitted} και ετερους πολλους και [ερριψαν]{.greek-omitted} [εριψαν]{.greek-added} αυτους παρα τους ποδας του [ιησου]{.greek-abbr} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους λαλουντας κυλλους υγιεις [και]{.greek-added} χωλους περιπατουντας και τυφλους βλεποντας και εδοξασαν τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου ειπεν σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις προσμενουσιν μοι και ουκ εχουσιν τι φαγωσιν και απολυσαι αυτους νηστεις ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια αρτοι τοσουτοι ωστε χορτασαι [τοσουτον]{.greek-added} οχλον [τοσουτον]{.greek-omitted}[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και εκελευσεν τοις οχλοις αναπεσειν επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας εκλασεν και εδωκεν τοις μαθηταις αυτου οι δε μαθηται τω οχλω[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας πληρεις[15:37]{.aside}

οι δε [εσθιοντες]{.greek-omitted} [αισθιοντες]{.greek-added} ησαν [ωσει]{.greek-added} [τετρακισχιλιοι]{.greek-omitted} [τετρακισχειλιοι]{.greek-added} ανδρες χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους [ενεβη]{.greek-omitted} [ανεβη]{.greek-added} εις το πλοιον και ηλθεν εις τα ορια μαγδαλα[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} ευδια πυρραζει γαρ ο [ουρανος]{.greek-abbr}[16:2]{.aside}

και πρωι σημερον χειμων πυρραζει γαρ στυγναζων ο [ουρανος]{.greek-abbr} [υποκριται]{.greek-omitted} το μεν προσωπον του [ουρανου]{.greek-abbr} [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} διακρινειν τα δε σημεια των καιρων ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added}[16:3]{.aside}

γενεα πονηρα και [μοιχαλις]{.greek-omitted} [μοιχαλλις]{.greek-added} [σημειον]{.greek-omitted} [σημιον]{.greek-added} επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} αυτους απηλθεν[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν επελαθοντο [του]{.greek-added} [λαβειν]{.greek-added} αρτους [λαβειν]{.greek-omitted}[16:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις [ορατε]{.greek-omitted} [οραται]{.greek-added} και [προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} απο της ζυμης των φαρισαιων και σαδδουκαιων[16:6]{.aside}

οι δε διελογιζοντο εν εαυτοις λεγοντες οτι αρτους ουκ ελαβομεν[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-omitted} τι [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν εαυτοις ολιγοπιστοι οτι αρτους ουκ [ελαβετε]{.greek-omitted} [εχεται]{.greek-added}[16:8]{.aside}

ουπω [νοειτε]{.greek-omitted} [νοειται]{.greek-added} ουδε [μνημονευετε]{.greek-omitted} [μνημονευεται]{.greek-added} τους πεντε αρτους των [πεντακισχιλιων]{.greek-omitted} [πεντακισχιλειων]{.greek-added} και ποσους κοφινους ελαβετε[16:9]{.aside}

ουδε τους επτα αρτους των [τετρακισχιλιων]{.greek-omitted} [τετρακισχιλειων]{.greek-added} και ποσας σπυριδας ελαβετε[16:10]{.aside}

πως ου [νοειτε]{.greek-omitted} [νοειται]{.greek-added} οτι ου περι [αρτου]{.greek-omitted} [αρτων]{.greek-added} ειπον υμιν προσεχειν απο της ζυμης των φαρισαιων και σαδδουκαιων[16:11]{.aside}

τοτε συνηκαν οτι ουκ ειπεν προσεχειν απο της ζυμης [του]{.greek-omitted} [αρτου]{.greek-omitted} [των]{.greek-added} [φ[αρι]{.unclear}]{.greek-added} [[αρτων]{.corr}]{.greek-added} αλλα απο της διδαχης των φαρισαιων και σαδδουκαιων[16:12]{.aside}

ελθων δε ο [ιησους]{.greek-abbr} εις τα μερη [καισαρειας]{.greek-omitted} [καισαριας]{.greek-added} της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον οι μεν ιωαννην τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λεγει αυτοις υμεις δε τινα με [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος ειπεν συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

[και]{.greek-omitted} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτω μακαριος ει σιμων βαριωνα οτι σαρξ και αιμα ουκ απεκαλυψεν σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις [ουρανοις]{.greek-abbr}[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι αδου ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν τοις [ουρανοις]{.greek-abbr} και ο εαν λυσης επι της γης εσται λελυμενον εν τοις [ουρανοις]{.greek-abbr}[16:19]{.aside}

τοτε διεστειλατο τοις μαθηταις αυτου ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} δεικνυειν τοις μαθηταις αυτου οτι δει αυτον απελθειν εις ιεροσολυμα και πολλα παθειν απο των πρεσβυτερων και αρχιερεων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και τη τριτη ημερα εγερθηναι[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω λεγων ιλεως σοι [κυριε]{.greek-abbr} ου μη εσται σοι τουτο[16:22]{.aside}

ο δε στραφεις ειπεν τω πετρω υπαγε οπισω μου σατανα σκανδαλον μου ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} ειπεν τοις μαθηταις αυτου ει τις θελει οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[16:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την ψυχην αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι γαρ [ωφελειται]{.greek-omitted} [ωφελησει]{.greek-added} [ανθρωπος]{.greek-abbr} εαν τον κοσμον ολον κερδηση την δε ψυχην αυτου ζημιωθη η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο υιος του [ανθρωπου]{.greek-abbr} ερχεσθαι εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων αυτου και τοτε αποδωσει εκαστω κατα την πραξιν αυτου[16:27]{.aside}

αμην λεγω υμιν [οτι]{.greek-added} εισιν τινες [των]{.greek-added} ωδε [εστωτες]{.greek-omitted} [εστηκοτων]{.greek-added} οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν ιδωσιν τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και ιωαννην τον αδελφον αυτου και αναφερει αυτους εις ορος υψηλον κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και ελαμψεν το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} λευκα ως το φως[17:2]{.aside}

και ιδου ωφθησαν αυτοις μωσης και ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

αποκριθεις δε ο πετρος ειπεν [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι ει [θελεις]{.greek-omitted} [θελης]{.greek-added} ποιησωμεν ωδε τρεις σκηνας σοι μιαν και μωση μιαν και [ηλια]{.greek-added} μιαν [ηλια]{.greek-omitted}[17:4]{.aside}

ετι αυτου λαλουντος ιδου νεφελη [φωτεινη]{.greek-omitted} [φωτινη]{.greek-added} επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added} αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν [εγερθητε]{.greek-omitted} [εγερθηται]{.greek-added} και μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινοντων αυτων εκ του ορους ενετειλατο αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι ειπητε το οραμα εως ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[17:9]{.aside}

και επηρωτησαν αυτον οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν δει ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις ηλιας μεν ερχεται [πρωτον]{.greek-omitted} [πρωτος]{.greek-added} και αποκαταστησει παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας ηδη ηλθεν και ουκ επεγνωσαν αυτον αλλα εποιησαν εν αυτω οσα ηθελησαν ουτως και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι ιωαννου του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον προσηλθεν αυτω [ανθρωπος]{.greek-abbr} γονυπετων αυτον[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι σεληνιαζεται και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και προσηνεγκα αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν αυτον θεραπευσαι[17:16]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε [εσομαι]{.greek-omitted} μεθ υμων [εσομαι]{.greek-added} εως ποτε ανεξομαι υμων [φερετε]{.greek-omitted} [φερεται]{.greek-added} μοι αυτον ωδε[17:17]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε προσελθοντες οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην γαρ λεγω υμιν εαν εχητε πιστιν ως κοκκον σιναπεως ερειτε τω ορει τουτω [μεταβηθι]{.greek-omitted} [μεταβηθει]{.greek-added} εντευθεν εκει και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ εκπορευεται ει μη εν προσευχη και [νηστεια]{.greek-omitted} [νηστια]{.greek-added}[17:21]{.aside}

αναστρεφομενων δε αυτων εν τη γαλιλαια ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα εγερθησεται και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε [αυτων]{.greek-omitted} εις καπερναουμ προσηλθον οι τα διδραχμα λαμβανοντες τω πετρω και ειπον ο διδασκαλος υμων ου τελει τα διδραχμα[17:24]{.aside}

λεγει ναι και οτε [εισηλθεν]{.greek-omitted} [εισηλθον]{.greek-added} εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο τινων λαμβανουσιν τελη η κηνσον απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

λεγει αυτω ο πετρος απο των αλλοτριων εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις [την]{.greek-omitted} θαλασσαν βαλε αγκιστρον και τον [αναβαινοντα]{.greek-omitted} [αναβαντα]{.greek-added} πρωτον ιχθυν αρον και ανοιξας το στομα αυτου ευρησεις στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ωρα προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες τις αρα μειζων εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη [στραφητε]{.greek-omitted} [στραφηται]{.greek-added} και [γενησθε]{.greek-omitted} [γενησθαι]{.greek-added} ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο [ουτος]{.greek-omitted} [ουτως]{.greek-added} εστιν ο μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος εαν δεξηται [τοιουτον]{.greek-added} παιδιον [τοιουτον]{.greek-omitted} [εν]{.greek-omitted} [επι]{.greek-omitted} [επει]{.greek-added} τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν σκανδαλιση ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος [εις]{.greek-omitted} [περι]{.greek-added} τον τραχηλον αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

ει δε η χειρ σου η ο πους σου [σκανδαλιζει]{.greek-omitted} [σκανδαλιζη]{.greek-added} σε εκκοψον [αυτα]{.greek-omitted} [αυτω]{.greek-added} και [βαλε]{.greek-omitted} [βαλαι]{.greek-added} απο σου καλον [γαρ]{.greek-added} σοι εστιν εισελθειν εις την ζωην χωλον η κυλλον η δυο χειρας η δυο ποδας εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και [ει]{.greek-omitted} [η]{.greek-added} ο οφθαλμος σου [σκανδαλιζει]{.greek-omitted} [σκανδαλιζη]{.greek-added} σε εξελε αυτον και βαλε απο σου καλον σοι εστιν μονοφθαλμον εις την ζωην εισελθειν η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

ορατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν ουρανοις δια παντος βλεπουσιν το προσωπον του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[18:10]{.aside}

ηλθεν γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει εαν γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα ενενηκοντα εννεα [επι]{.greek-omitted} [επει]{.greek-added} τα ορη πορευθεις ζητει το πλανωμενον[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η [επι]{.greek-omitted} [επει]{.greek-added} τοις ενενηκοντα εννεα τοις μη πεπλανημενοις[18:13]{.aside}

ουτως ουκ εστιν θελημα εμπροσθεν του [πατρος]{.greek-abbr} υμων του εν [ουρανοις]{.greek-abbr} ινα [αποληται]{.greek-omitted} [απωληται]{.greek-added} [εις]{.greek-omitted} [εν]{.greek-added} των μικρων τουτων[18:14]{.aside}

εαν δε αμαρτηση εις σε ο αδελφος σου υπαγε [και]{.greek-omitted} ελεγξον αυτον [μεταξυ]{.greek-omitted} [μετα]{.greek-added} σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη ακουση παραλαβε μετα [σου]{.greek-omitted} [σεαυτου]{.greek-added} ετι ενα η δυο ινα επι στοματος δυο μαρτυρων η τριων σταθη παν ρημα[18:16]{.aside}

εαν δε παρακουση αυτων ειπε τη εκκλησια εαν δε [και]{.greek-omitted} [της]{.greek-omitted} [τη]{.greek-added} [εκκλησιας]{.greek-omitted} [εκκλησια]{.greek-added} παρακουση εστω σοι ωσπερ ο [εθνικος]{.greek-omitted} [εθνηκος]{.greek-added} και ο τελωνης[18:17]{.aside}

αμην λεγω υμιν οσα εαν δησητε επι της γης [εσται]{.greek-omitted} [εστε]{.greek-added} δεδεμενα εν [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [τοις]{.greek-added} [[ουρανοις]{.greek-abbr}]{.greek-added} και οσα εαν λυσητε [επι]{.greek-omitted} [επει]{.greek-added} της γης [εσται]{.greek-omitted} [εστε]{.greek-added} λελυμενα εν [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [τοις]{.greek-added} [[ουρανοις]{.greek-abbr}]{.greek-added}[18:18]{.aside}

παλιν [αμην]{.greek-omitted} [δε]{.greek-added} λεγω υμιν οτι εαν δυο [συμφωνησουσιν]{.greek-added} [εξ]{.greek-added} υμων [συμφωνησωσιν]{.greek-omitted} επι της γης περι παντος πραγματος ου εαν [αιτησωνται]{.greek-omitted} [αιτησονται]{.greek-added} γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[18:19]{.aside}

ου γαρ εισιν δυο η τρεις συνηγμενοι εις το εμον ονομα εκει [ειμι]{.greek-omitted} [ειμοι]{.greek-added} εν μεσω αυτων[18:20]{.aside}

τοτε προσελθων [αυτω]{.greek-omitted} ο πετρος ειπεν [αυτω]{.greek-added} [κυριε]{.greek-abbr} ποσακις αμαρτησει εις εμε ο αδελφος μου και αφησω αυτω εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} ου λεγω σοι εως επτακις αλλ εως [εβδομηκοντακις]{.greek-omitted} [εβδομικοντακις]{.greek-added} επτα[18:22]{.aside}

δια τουτο [ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει [ος]{.greek-omitted} [οστις]{.greek-added} ηθελησεν [συναραι]{.greek-omitted} [συναρε]{.greek-added} λογον μετα των δουλων αυτου[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν αυτον ο [κυριος]{.greek-abbr} αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα ειχεν και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος [προσεκυνει]{.greek-omitted} [προσεκυνη]{.greek-added} αυτω λεγων [κυριε]{.greek-abbr} μακροθυμησον επ εμοι και παντα [αποδωσω]{.greek-added} σοι [αποδωσω]{.greek-omitted}[18:26]{.aside}

σπλαγχνισθεις δε ο [κυριος]{.greek-abbr} του δουλου εκεινου απελυσεν αυτον και το δανειον [α]{.greek-added} [αφηκεν]{.greek-omitted} [φηκεν]{.greek-added} αυτω[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον δηναρια και κρατησας αυτον επνιγεν λεγων αποδος μοι ει τι [οφειλεις]{.greek-omitted} [ωφιλεις]{.greek-added}[18:28]{.aside}

πεσων ουν ο συνδουλος [αυτου]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} αυτου παρεκαλει αυτον λεγων μακροθυμησον επ εμοι και [παντα]{.greek-added} αποδωσω σοι[18:29]{.aside}

ο δε ουκ ηθελεν αλλα απελθων εβαλεν αυτον εις φυλακην εως ου αποδω [παν]{.greek-added} το [οφειλομενον]{.greek-omitted} [οφιλομενον]{.greek-added}[18:30]{.aside}

[ιδοντες]{.greek-omitted} [ειδοντες]{.greek-added} δε οι συνδουλοι αυτου τα γενομενα ελυπηθησαν σφοδρα και ελθοντες διεσαφησαν τω [κυριω]{.greek-abbr} [εαυτων]{.greek-omitted} [αυτων]{.greek-added} παντα τα γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο [κυριος]{.greek-abbr} αυτου λεγει αυτω δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι επει παρεκαλεσας με[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως και εγω σε ηλεησα[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} αυτου παρεδωκεν αυτον τοις [βασανισταις]{.greek-omitted} [βανισταις]{.greek-added} εως ου αποδω παν το [οφειλομενον]{.greek-omitted} [οφιλομενον]{.greek-added} αυτω[18:34]{.aside}

ουτως και ο [πατηρ]{.greek-abbr} [μου]{.greek-omitted} [υμων]{.greek-added} ο [επουρανιος]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} ποιησει υμιν εαν μη αφητε εκαστος [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [αυτου]{.greek-omitted} απο των καρδιων υμων τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και προσηλθον αυτω οι φαρισαιοι πειραζοντες αυτον και λεγοντες [αυτω]{.greek-omitted} ει εξεστιν [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} οτι ο ποιησας απ αρχης αρσεν και θηλυ εποιησεν αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταλιψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-added} και την [μητερα]{.greek-abbr} και προσκολληθησεται τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

ωστε ουκετι εισιν δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν μωσης ενετειλατο [δουναι]{.greek-omitted} [δουνε]{.greek-added} βιβλιον αποστασιου και [απολυσαι]{.greek-omitted} [απολυσε]{.greek-added} [αυτην]{.greek-omitted}[19:7]{.aside}

λεγει αυτοις οτι μωσης προς την σκληροκαρδιαν υμων επετρεψεν υμιν απολυσαι τας γυναικας υμων απ [αρχης]{.greek-omitted} [αρχεις]{.greek-added} δε ου γεγονεν ουτως[19:8]{.aside}

λεγω δε υμιν οτι ος αν απολυση την γυναικα αυτου μη επι [πορνεια]{.greek-omitted} [πορνια]{.greek-added} και γαμηση αλλην μοιχαται και ο απολελυμενην γαμησας [μοιχαται]{.greek-omitted} [μυχαται]{.greek-added}[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτως εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφερει γαμησαι[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες χωρουσιν τον λογον τουτον αλλ οι[ς]{.unclear} δεδοται[19:11]{.aside}

εισιν γαρ ευνουχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} εγεννηθησαν ουτως και εισιν ευνουχοι οιτινες ευνουχισθησαν υπο των [ανθρωπων]{.greek-abbr} και εισιν ευνουχοι οιτινες [ευνουχισαν]{.greek-omitted} [ευνουχησαν]{.greek-added} εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε [προσηνεχθη]{.greek-omitted} [προσηνεχθησαν]{.greek-added} αυτω παιδια ινα τας χειρας [επιθη]{.greek-omitted} [επειθη]{.greek-added} αυτοις και προσευξηται οι δε μαθηται επετιμησαν αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αφετε]{.greek-omitted} [αυτοις]{.greek-added} [αφεται]{.greek-added} τα παιδια και μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και [επιθεις]{.greek-omitted} [επειθεις]{.greek-added} αυτοις τας χειρας επορευθη εκειθεν[19:15]{.aside}

και ιδου εις προσελθων ειπεν αυτω διδασκαλε αγαθε τι αγαθον ποιησω ινα εχω ζωην αιωνιον[19:16]{.aside}

ο δε ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr} ει δε θελεις εισελθειν εις την ζωην τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} ειπεν το ου φονευσεις ου μοιχευσεις ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} και αγαπησεις τον πλησιον σου ως σεαυτον[19:19]{.aside}

λεγει αυτω ο νεανισκος [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} εφυλαξαμην εκ νεοτητος μου τι ετι υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει [θελεις]{.greek-omitted} [θελις]{.greek-added} [τελειος]{.greek-omitted} [τελιος]{.greek-added} ειναι υπαγε πωλησον σου τα υπαρχοντα και δος πτωχοις και [εξεις]{.greek-omitted} [εξης]{.greek-added} θησαυρον εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} και δευρο ακολουθει μοι[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως πλουσιος εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν δε λεγω υμιν ευκοπωτερον εστιν καμηλον δια τρυπηματος ραφιδος [διελθειν]{.greek-omitted} [εισελθειν]{.greek-added} η πλουσιον εις την βασιλειαν [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισελθειν]{.greek-omitted}[19:24]{.aside}

ακουσαντες δε οι μαθηται [αυτου]{.greek-omitted} εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

εμβλεψας δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον εστιν παρα δε [θεω]{.greek-abbr} παντα δυνατα [εστιν]{.greek-added}[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω ιδου ημεις [αφηκαμεν]{.greek-omitted} [αφικαμεν]{.greek-added} παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν [καθιση]{.greek-omitted} [καθησει]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου [καθισεσθε]{.greek-omitted} [καθησεσθαι]{.greek-added} και υμεις [επι]{.greek-omitted} [επει]{.greek-added} δωδεκα θρονους κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας [ος]{.greek-omitted} [οστις]{.greek-added} αφηκεν [οικιας]{.greek-omitted} [η]{.greek-omitted} αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους [η]{.greek-added} [οικιας]{.greek-added} ενεκεν [του]{.greek-omitted} [ονοματος]{.greek-omitted} [μου]{.greek-omitted} [εμου]{.greek-added} εκατονταπλασιονα ληψεται και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι [εσχατοι]{.greek-omitted} [αισχατοι]{.greek-added} και [εσχατοι]{.greek-omitted} [αισχατοι]{.greek-added} πρωτοι[19:30]{.aside}

### Chapter 20

ομοια γαρ εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

[και]{.greek-omitted} [συμ]{.greek-added} [συμφωνησας]{.greek-omitted} [φωνησας]{.greek-added} [δε]{.greek-added} μετα των εργατων εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι τριτην ωραν ειδεν αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

και εκεινοις ειπεν [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} και υμεις εις τον αμπελωνα [μου]{.greek-added} και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν εξελθων περι εκτην και ενατην ωραν εποιησεν [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added}[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι [εστηκατε]{.greek-added} ωδε [εστηκατε]{.greek-omitted} ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο λεγει αυτοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} και υμεις εις τον αμπελωνα και ο εαν η δικαιον [ληψεσθε]{.greek-omitted} [ληψεσθαι]{.greek-added}[20:7]{.aside}

οψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των [εσχατων]{.greek-omitted} [αισχατων]{.greek-added} εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα [διναριον]{.greek-added} [δηναριον]{.corr}[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι πλειονα ληψονται και ελαβον και αυτοι ανα δηναριον[20:10]{.aside}

λαβοντες δε εγογγυζον κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι ουτοι οι [εσχατοι]{.greek-omitted} [αισχατοι]{.greek-added} μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις βαστασασιν το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων [εταιρε]{.greek-omitted} [ετεραι]{.greek-added} ουκ [αδικω]{.greek-omitted} [α]{.greek-added} [δηκω]{.greek-added} σε ουχι δηναριου συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω [εσχατω]{.greek-omitted} [αισχατω]{.greek-added} δουναι ως και σοι[20:14]{.aside}

η ουκ εξεστιν μοι ποιησαι ο θελω εν τοις εμοις ει ο οφθαλμος σου πονηρος εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι [εσχατοι]{.greek-omitted} πρωτοι [αισχατοι]{.greek-added} και οι [αισχατοι]{.greek-added} πρωτοι [εσχατοι]{.greek-omitted} πολλοι γαρ εισιν κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

και αναβαινων [εις]{.greek-added} [ιεροσολυμα]{.greek-added} ο [ιησους]{.greek-abbr} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} παρελαβεν τους δωδεκα μαθητας κατ ιδιαν [και]{.greek-added} εν τη οδω [και]{.greek-omitted} ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις αρχιερευσιν και γραμματευσιν και κατακρινουσιν αυτον θανατω[20:18]{.aside}

και παραδωσουσιν αυτον τοις εθνεσιν εις το εμπαιξαι και μαστιγωσαι και σταυρωσαι και τη τριτη ημερα [αναστησεται]{.greek-omitted} [εγερθησεται]{.greek-added}[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι θελεις [λεγει]{.greek-omitted} [η]{.greek-added} [δε]{.greek-added} [ειπεν]{.greek-added} αυτω ειπε ινα [καθισωσιν]{.greek-omitted} [καθησωσιν]{.greek-added} ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν [αυτη]{.greek-added} ουκ οιδατε τι [αιτεισθε]{.greek-omitted} [αιτισθαι]{.greek-added} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} πιειν το ποτηριον ο εγω μελλω πινειν η το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζομε]{.greek-added} βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου [πιεσθε]{.greek-omitted} [πιεσθαι]{.greek-added} και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-omitted} ουκ [εστιν]{.greek-omitted} [εστην]{.greek-added} εμον δουναι αλλ οις ητοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν [θελη]{.greek-omitted} [θεληση]{.greek-added} εν υμιν μεγας γενεσθαι [εσται]{.greek-omitted} [εστε]{.greek-added} υμων διακονος[20:26]{.aside}

και ος εαν θελη εν υμιν ειναι πρωτος [εστω]{.greek-omitted} [εστε]{.greek-added} υμων δουλος[20:27]{.aside}

ωσπερ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και εκπορευομενων αυτων απο ιεριχω ηκολουθησεν αυτω οχλος πολυς[20:29]{.aside}

και ιδου δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [[υιε]{.greek-abbr}]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

[ο]{.greek-omitted} [οι]{.greek-added} δε [οχλος]{.greek-omitted} [οχλοι]{.greek-added} επετιμησεν αυτοις ινα σιωπησωσιν οι δε μειζον εκραζον λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [[υιε]{.greek-abbr}]{.greek-added} [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-abbr} εφωνησεν αυτους και ειπεν τι θελετε ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-abbr} ινα ανοιχθωσιν [ημων]{.greek-omitted} οι οφθαλμοι [ημων]{.greek-added}[20:33]{.aside}

[σπλαγχνισθεις]{.greek-omitted} [σπλαγχνισθις]{.greek-added} δε ο [ιησους]{.greek-abbr} ηψατο των οφθαλμων αυτων και ευθεως ανεβλεψαν αυτων οι οφθαλμοι και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε ηγγισαν εις ιεροσολυμα [και]{.greek-omitted} [ηλθον]{.greek-omitted} εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} προς το ορος των ελαιων τοτε ο [ιησους]{.greek-abbr} απεστειλεν δυο μαθητας[21:1]{.aside}

λεγων αυτοις [πορευθητε]{.greek-omitted} [πορευεσθαι]{.greek-added} εις την κωμην την απεναντι υμων και ευθεως [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο [κυριος]{.greek-abbr} αυτων [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον και πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες καθως προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και [των]{.greek-added} [τον]{.corr} πωλον και επεθηκαν [επανω]{.greek-omitted} [επ]{.greek-added} αυτων τα ιματια αυτων και [επεκαθισεν]{.greek-omitted} [επεκαθησεν]{.greek-added} επανω αυτων[21:7]{.aside}

ο δε [πλειστος]{.greek-omitted} [πλιστος]{.greek-added} οχλος εστρωσαν εαυτων τα ιματια εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα [εσεισθη]{.greek-omitted} [εσισθη]{.greek-added} πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο [ναζαρετ]{.greek-omitted} [ναζαραιθ]{.greek-added} της γαλιλαιας[21:11]{.aside}

και εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον [του]{.greek-omitted} [θεου]{.greek-omitted} και εξεβαλεν παντας τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων κατεστρεψεν και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο οικος μου οικος προσευχης κληθησεται υμεις δε αυτον εποιησατε [σπηλαιον]{.greek-omitted} [σπηλεον]{.greek-added} ληστων[21:13]{.aside}

και προσηλθον αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α εποιησεν και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων [κατηρτισω]{.greek-omitted} [κατηρτησω]{.greek-added} αινον[21:16]{.aside}

και καταλιπων αυτους εξηλθεν εξω της πολεως εις [βηθανιαν]{.greek-omitted} [βιθανιαν]{.greek-added} και ηυλισθη εκει[21:17]{.aside}

πρωιας δε επαναγων εις την πολιν [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added}[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει μη φυλλα μονον και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη παραχρημα η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν εχητε πιστιν και μη διακριθητε ου μονον το της συκης [ποιησετε]{.greek-omitted} [ποιησητε]{.greek-added} αλλα καν τω ορει τουτω ειπητε αρθητι και βληθητι εις την θαλασσαν γενησεται[21:21]{.aside}

και παντα οσα εαν αιτησητε εν τη προσευχη πιστευοντες [ληψεσθε]{.greek-omitted} [ληψεσθαι]{.greek-added}[21:22]{.aside}

και ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις σοι εδωκεν την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω υμας καγω [ενα]{.greek-added} λογον [ενα]{.greek-omitted} ον εαν [ειπητε]{.greek-omitted} [ειπηται]{.greek-added} μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα ιωαννου ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο [παρ]{.greek-omitted} [εν]{.greek-added} εαυτοις λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} [ερει]{.greek-omitted} [αιρει]{.greek-added} ημιν δια τι ουν ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-omitted} [ανθροπων]{.greek-added} φοβουμεθα τον οχλον παντες γαρ εχουσιν τον ιωαννην [ως]{.greek-omitted} [ω]{.greek-added} προφητην[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} ειπον ουκ οιδαμεν εφη αυτοις και αυτος ουδε εγω [υμιν]{.greek-added} λεγω [υμιν]{.greek-omitted} εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} ειχεν τεκνα δυο και προσελθων τω πρωτω ειπεν τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι [μου]{.greek-omitted}[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε μεταμεληθεις απηλθεν[21:29]{.aside}

και προσελθων [τω]{.greek-omitted} [το]{.greek-added} [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added} ο δε αποκριθεις ειπεν εγω [κυριε]{.greek-abbr} και ουκ απηλθεν[21:30]{.aside}

τις εκ των δυο εποιησεν το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

ηλθεν γαρ προς υμας ιωαννης εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω οι δε τελωναι και αι πορναι επιστευσαν αυτω υμεις δε [ιδοντες]{.greek-omitted} [ειδοντες]{.greek-added} ου μετεμεληθητε υστερον του πιστευσαι αυτω[21:32]{.aside}

αλλην παραβολην ακουσατε [ανθρωπος]{.greek-abbr} [τις]{.greek-omitted} ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω περιεθηκεν και ωρυξεν εν αυτω ληνον και ωκοδομησεν πυργον και [εξεδοτο]{.greek-omitted} [εξεδετο]{.greek-added} αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε ηγγισεν ο καιρος των καρπων απεστειλεν τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν [εδειραν]{.greek-omitted} [εδηραν]{.greek-added} ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε απεστειλεν προς αυτους τον [υιον]{.greek-abbr} αυτου λεγων εντραπησονται τον [υιον]{.greek-abbr} μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον [υιον]{.greek-abbr} ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την [κληρονομιαν]{.greek-omitted} [κληρονο]{.greek-added} [μιαν]{.greek-added} αυτου[21:38]{.aside}

και λαβοντες αυτον [εξεβαλον]{.greek-omitted} [εξεβαλλον]{.greek-added} εξω του αμπελωνος και [απεκτειναν]{.greek-omitted} [απεκτιναν]{.greek-added}[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα εκδωσεται αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις καιροις αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε ανεγνωτε εν ταις γραφαις λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται [εθνει]{.greek-omitted} [εθνη]{.greek-added} ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο [πεσων]{.greek-omitted} [πεσον]{.greek-added} επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση λικμησει αυτον[21:44]{.aside}

και ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους επειδη ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} παλιν ειπεν αυτοις εν παραβολαις λεγων[22:1]{.aside}

[ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις εποιησεν γαμους τω υιω αυτου[22:2]{.aside}

και απεστειλεν τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου ητοιμασα οι ταυροι μου και τα σιτιστα τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου υβρισαν και [απεκτειναν]{.greek-omitted} [απεκτιναν]{.greek-added}[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος ωργισθη και πεμψας τα στρατευματα αυτου απωλεσεν τους [φωνεις]{.greek-added} [φονεις]{.corr} εκεινους και την πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενεπρισεν]{.greek-added}[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον παντας οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω [εταιρε]{.greek-omitted} [ετερε]{.greek-added} πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε [ειπεν]{.greek-omitted} ο βασιλευς [ειπεν]{.greek-added} τοις διακονοις δησαντες αυτου ποδας και χειρας αρατε αυτον και εκβαλετε εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ εισιν κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον ελαβον οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι αληθης ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει εξεστιν δουναι κηνσον καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων ειπεν τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} υποκριται[22:18]{.aside}

[επιδειξατε]{.greek-omitted} [επειδειξατε]{.greek-added} μοι το νομισμα [του]{.greek-omitted} [κηνσου]{.greek-omitted} οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η [εικων]{.greek-omitted} [ικων]{.greek-added} αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις αποδοτε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι [οι]{.greek-omitted} λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης [ειπεν]{.greek-omitted} [εγραψεν]{.greek-added} εαν τις αποθανη μη εχων τεκνα επιγαμβρευσει ο αδελφος αυτου την γυναικα αυτου και [αναστησει]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος γαμησας ετελευτησεν και μη εχων σπερμα αφηκεν την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων απεθανεν και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added} μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε [εκγαμιζονται]{.greek-omitted} [γαμισκονται]{.greek-added} αλλ ως αγγελοι [του]{.greek-omitted} [θεου]{.greek-abbr} [εισιν]{.greek-added} εν [ουρανω]{.greek-abbr} [εισιν]{.greek-omitted}[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν υμιν υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-omitted} νεκρων αλλα [ζωντων]{.greek-omitted} [ζοντων]{.greek-added}[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημωσεν]{.greek-added} τους σαδδουκαιους συνηχθησαν [επι]{.greek-omitted} [επει]{.greek-added} το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη εστιν πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὐτῆς]{.greek-added} αγαπησεις τον πλησιον σου ως σεαυτον[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται [κρεμανται]{.greek-omitted} [κρεμαται]{.greek-added}[22:40]{.aside}

συνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος [υιος]{.greek-abbr} εστιν λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} καλει αυτον [κυριον]{.greek-abbr} πως υιος αυτου εστιν[22:45]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} [αποκριθηναι]{.greek-added} αυτω [αποκριθηναι]{.greek-omitted} λογον ουδε ετολμησεν τις απ εκεινης της ημερας [επερωτησαι]{.greek-omitted} [επερωτησε]{.greek-added} αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} ελαλησεν τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν [τηρειτε]{.greek-omitted} [τηρειται]{.greek-added} και ποιειτε κατα δε τα εργα αυτων μη ποιειτε λεγουσιν γαρ και ου ποιουσιν[23:3]{.aside}

δεσμευουσιν γαρ φορτια βαρεα [και]{.greek-omitted} δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου θελουσιν [κινησαι]{.greek-omitted} [κινησε]{.greek-added} αυτα[23:4]{.aside}

παντα δε τα εργα αυτων ποιουσιν προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} πλατυνουσιν δε τα φυλακτηρια αυτων και μεγαλυνουσιν τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

φιλουσιν [τε]{.greek-omitted} [δε]{.greek-added} την [πρωτοκλισιαν]{.greek-omitted} [πρωτοκλησιαν]{.greek-added} εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} [ραββι]{.greek-omitted} [ραββει]{.greek-added} [ραββι]{.greek-omitted} [ραββει]{.greek-added}[23:7]{.aside}

υμεις δε μη κληθητε [ραββι]{.greek-omitted} [ραββει]{.greek-added} εις γαρ εστιν υμων ο καθηγητης ο [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε υμων [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr}[23:9]{.aside}

μηδε κληθητε καθηγηται εις γαρ [υμων]{.greek-omitted} εστιν ο καθηγητης [υμων]{.greek-added} ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων εσται υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθαι]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιεται]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιεται]{.greek-added} [τας]{.greek-added} [οικειας]{.greek-added} των [χηρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [περιαγετε]{.greek-omitted} [περιαγεται]{.greek-added} την θαλασσαν και την ξηραν [ποιησαι]{.greek-omitted} [ποιεισαι]{.greek-added} ενα προσηλυτον και οταν [γενηται]{.greek-omitted} [γενητε]{.greek-added} ποιειτε αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος [αν]{.greek-omitted} [εαν]{.greek-added} ομοση εν τω ναω ουδεν εστιν ος [δε]{.greek-added} [δ]{.greek-omitted} [αν]{.greek-omitted} ομοση εν τω χρυσω του ναου [οφειλει]{.greek-omitted} [οφιλει]{.greek-added}[23:16]{.aside}

μωροι και τυφλοι [τις]{.greek-omitted} [τι]{.greek-added} γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} ομοση εν τω θυσιαστηριω ουδεν εστιν ος δ αν ομοση εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι τι γαρ [μειζον]{.greek-omitted} [μειζων]{.greek-added} το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω ομνυει εν αυτω και εν πασιν τοις επανω αυτου[23:20]{.aside}

και ο ομοσας εν τω ναω ομνυει εν αυτω και εν τω [κατοικησαντι]{.greek-omitted} [κατοικουντι]{.greek-added} αυτον[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [αποδεκατουτε]{.greek-omitted} [αποδεκατουται]{.greek-added} το ηδυοσμον και το ανηθον και το [κυμινον]{.greek-omitted} [κυμηνον]{.greek-added} και αφηκατε τα βαρυτερα του νομου την κρισιν και [τον]{.greek-omitted} [το]{.greek-added} ελεον και την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} ταυτα [δε]{.greek-added} εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [καθαριζετε]{.greek-omitted} [καθαριζεται]{.greek-added} το εξωθεν του ποτηριου και της [παροψιδος]{.greek-omitted} [παραψιδος]{.greek-added} εσωθεν δε γεμουσιν εξ αρπαγης και [αδικιας]{.greek-omitted} [ακαθαρσιας]{.greek-added}[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της [παροψιδος]{.greek-omitted} [παραψιδος]{.greek-added} ινα γενηται και το [εκτος]{.greek-omitted} [εντος]{.greek-added} αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [παρομοιαζετε]{.greek-omitted} [παρομοιαζεται]{.greek-added} ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

ουτως και υμεις εξωθεν μεν φαινεσθε τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι [εστε]{.greek-omitted} [εσται]{.greek-added} υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [οικοδομειτε]{.greek-omitted} [οικοδομειται]{.greek-added} τους ταφους των προφητων και [κοσμειτε]{.greek-omitted} [κοσμειται]{.greek-added} τα [μνημεια]{.greek-omitted} [μνημια]{.greek-added} των δικαιων[23:29]{.aside}

και λεγετε ει [ημεν]{.greek-omitted} [ημεθα]{.greek-added} εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν [ημεν]{.greek-omitted} [ημεθα]{.greek-added} [αυτων]{.greek-added} κοινωνοι [αυτων]{.greek-omitted} εν τω αιματι των προφητων[23:30]{.aside}

ωστε [μαρτυρειτε]{.greek-omitted} [μαρτυρειται]{.greek-added} εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και σταυρωσετε και εξ αυτων μαστιγωσετε εν ταις συναγωγαις υμων και [διωξετε]{.greek-omitted} [διωξεται]{.greek-added} απο πολεως εις πολιν[23:34]{.aside}

οπως ελθη εφ υμας παν αιμα δικαιον [εκχυνομενον]{.greek-omitted} [εκχυννομενον]{.greek-added} επι της γης απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου [υιου]{.greek-abbr} βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει παντα ταυτα [επι]{.greek-omitted} [επει]{.greek-added} την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεινουσα]{.greek-added} τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον τροπον [ορνις]{.greek-added} επισυναγει [ορνις]{.greek-omitted} τα [εαυτης]{.greek-added} νοσσια [εαυτης]{.greek-omitted} υπο τας πτερυγας και ουκ [ηθελησατε]{.greek-omitted} [ηθελησαται]{.greek-added}[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη με [ιδητε]{.greek-omitted} [ειδητε]{.greek-added} απ [αρτι]{.greek-omitted} [αρτη]{.greek-added} εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} [εκ]{.greek-added} [επορευετο]{.greek-omitted} [απο]{.greek-omitted} του ιερου [επορευετο]{.greek-added} και προσηλθον οι μαθηται αυτου επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-omitted} [αποκριθεις]{.greek-added} ειπεν αυτοις [ου]{.greek-omitted} βλεπετε παντα ταυτα αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου [μη]{.greek-added} καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας [πλανηση]{.greek-omitted} [πλανησει]{.greek-added}[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω [νοματι]{.greek-added} [ονοματι]{.corr} μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους πλανησουσιν[24:5]{.aside}

[μελλησετε]{.greek-omitted} [μελλησεται]{.greek-added} δε ακουειν πολεμους και ακοας πολεμων ορατε μη [θροεισθε]{.greek-omitted} [θροεισθαι]{.greek-added} δει γαρ παντα γενεσθαι αλλ ουπω εστιν το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και λοιμοι και [σεισμοι]{.greek-omitted} [σισμοι]{.greek-added} κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη [ωδινων]{.greek-omitted} [ωδεινων]{.greek-added}[24:8]{.aside}

τοτε παραδωσουσιν υμας εις θλιψιν και αποκτενουσιν υμας και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μισουμενοι υπο παντων των εθνων δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους παραδωσουσιν και [μισησουσιν]{.greek-omitted} [μεισησουσιν]{.greek-added} αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και πλανησουσιν πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται [τουτο]{.greek-omitted} το ευαγγελιον της βασιλειας εν ολη τη οικουμενη εις μαρτυριον πασιν τοις εθνεσιν και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν [ιδητε]{.greek-omitted} [ειδητε]{.greek-added} το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου εστως εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν [επι]{.greek-omitted} [εις]{.greek-added} τα ορη[24:16]{.aside}

[και]{.greek-added} ο [επι]{.greek-omitted} [επει]{.greek-added} του δωματος μη [καταβαινετω]{.greek-omitted} [καταβατω]{.greek-added} [αραι]{.greek-omitted} [τα]{.greek-omitted} [αρε]{.greek-added} [τι]{.greek-added} εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω [εις]{.greek-added} [τα]{.greek-added} οπισω αραι [τα]{.greek-omitted} [το]{.greek-added} [ιματια]{.greek-omitted} [ιματιον]{.greek-added} αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται η φυγη υμων χειμωνος μηδε σαββατω[24:20]{.aside}

εσται γαρ τοτε [θλιψις]{.greek-omitted} [θλιψεις]{.greek-added} μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν ουδ ου μη γενηται[24:21]{.aside}

και [ει]{.greek-omitted} μη [εκολοβωθησαν]{.greek-omitted} [εκολοβοθησαν]{.greek-added} αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και δωσουσιν σημεια μεγαλα και τερατα ωστε πλανησαι [ει]{.greek-omitted} [η]{.greek-added} δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω εστιν μη [εξελθητε]{.greek-omitted} [εξελθηται]{.greek-added} ιδου εν τοις [ταμειοις]{.greek-omitted} [ταμιοις]{.greek-added} μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται [και]{.greek-omitted} η παρουσια του [υιου]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου [γαρ]{.greek-omitted} εαν η το πτωμα εκει συναχθησονται οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του [υιου]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε κοψονται πασαι αι φυλαι της γης και οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και αποστελει τους αγγελους αυτου μετα σαλπιγγος [και]{.greek-added} φωνης μεγαλης και επισυναξουσιν τους εκλεκτους αυτου εκ [τ]{.unclear}ων τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-abbr} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης [μαθετε]{.greek-omitted} [μαθεται]{.greek-added} την παραβολην οταν ηδη ο κλαδος αυτης γενηται απαλος και τα φυλλα εκφυη [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος[24:32]{.aside}

ουτως και υμεις οταν [ιδητε]{.greek-omitted} [ειδηται]{.greek-added} ταυτα παντα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς εστιν επι θυραις[24:33]{.aside}

αμην λεγω υμιν [οτι]{.greek-added} ου μη παρελθη η γενεα αυτη εως αν παντα ταυτα γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσονται οι δε λογοι μου ου μη παρελθωσιν[24:35]{.aside}

περι δε της ημερας [εκεινης]{.greek-omitted} και ωρας [εκεινης]{.greek-added} ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} [ουδε]{.greek-added} [ο]{.greek-added} [[υιος]{.greek-abbr}]{.greek-added} ει μη ο [πατηρ]{.greek-abbr} [μου]{.greek-omitted} μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται [και]{.greek-omitted} η παρουσια του [υιου]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις [εκειναις]{.greek-added} ταις προ του κατακλυσμου τρωγοντες και πινοντες γαμουντες και εκγαμιζοντες αχρι ης ημερας εισηλθεν νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του [υιου]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις [παραλαμβανεται]{.greek-omitted} [παραλαμβανετε]{.greek-added} και ο εις αφιεται[24:40]{.aside}

δυο αληθουσαι εν τω μυλωνι μια [παραλαμβανεται]{.greek-omitted} [παραλαμβανετε]{.greek-added} και μια αφιεται[24:41]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} ουν [οτι]{.greek-omitted} ουκ οιδατε [γαρ]{.greek-added} ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

εκεινο δε [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι ει [ηδει]{.greek-omitted} [ηδη]{.greek-added} ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ [αφηκεν]{.greek-added} [αν]{.greek-omitted} [ειασεν]{.greek-omitted} [διορυγηναι]{.greek-omitted} την οικιαν αυτου [διορυγηναι]{.greek-added}[24:43]{.aside}

δια τουτο και υμεις [γινεσθε]{.greek-omitted} [γεινεσθαι]{.greek-added} ετοιμοι οτι η ωρα ου [δοκειτε]{.greek-omitted} [δοκειται]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον [κατεστησεν]{.greek-omitted} [καταστησει]{.greek-added} ο [κυριος]{.greek-abbr} [αυτου]{.greek-omitted} επι της [θεραπειας]{.greek-omitted} [οικειας]{.greek-added} αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι πασιν τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [αυτου]{.greek-added} [εσθιειν]{.greek-omitted} [αισθιειν]{.greek-added} δε και πινειν μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των [υποκριτων]{.greek-omitted} [απιστων]{.greek-added} θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε [ομοιωθησεται]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε [ησαν]{.greek-omitted} εξ αυτων [ησαν]{.greek-added} φρονιμοι και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται [εξερχεσθε]{.greek-omitted} [εξερχεσθαι]{.greek-added} εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις [ειπον]{.greek-omitted} [ειπαν]{.greek-added} δοτε ημιν εκ του [ελαιου]{.greek-omitted} [ελεου]{.greek-added} υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε [ουκ]{.greek-omitted} [ου]{.greek-added} [μη]{.greek-added} αρκεση ημιν και υμιν [πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} δε μαλλον προς τους πωλουντας και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και [εκλεισθη]{.greek-omitted} [εκλισθη]{.greek-added} η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι [λοιπαι]{.greek-omitted} [λυπαι]{.greek-added} παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν [εν]{.greek-omitted} [η]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ερχεται]{.greek-omitted}[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων εκαλεσεν τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν εδωκεν πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και [απεδημησεν]{.greek-omitted} [απεδιμησεν]{.greek-added} [ευθεως]{.greek-omitted}[25:15]{.aside}

[ευθεως]{.greek-added} [δε]{.greek-added} πορευθεις [δε]{.greek-omitted} ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και [εποιησεν]{.greek-omitted} [εκερδησεν]{.greek-added} [εν]{.greek-added} [αυτοις]{.greek-added} αλλα πεντε ταλαντα[25:16]{.aside}

[ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added} και ο τα δυο εκερδησεν και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων [ωρυξεν]{.greek-omitted} [ορυξεν]{.greek-added} εν τη γη και απεκρυψεν το αργυριον του [κυριου]{.greek-abbr} αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και συναιρει [λογον]{.greek-added} μετ αυτων [λογον]{.greek-omitted}[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας [ιδε]{.greek-omitted} [ειδε]{.greek-added} αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη [δε]{.greek-omitted} αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [εις]{.greek-added} πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα λαβων ειπεν [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας [ιδε]{.greek-omitted} [ειδε]{.greek-added} αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [εις]{.greek-added} πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως ειπεν [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ [εσπειρας]{.greek-omitted} [εσπηρας]{.greek-added} και συναγων οθεν ου [διεσκορπισας]{.greek-omitted} [διεσκορπησας]{.greek-added}[25:24]{.aside}

και φοβηθεις απελθων εκρυψα [σου]{.greek-added} το ταλαντον [σου]{.greek-omitted} εν τη γη [ιδε]{.greek-omitted} [ειδε]{.greek-added} εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε [ηδεις]{.greek-omitted} [ειδεις]{.greek-added} οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου [διεσκορπισα]{.greek-omitted} [διεσκορπησα]{.greek-added}[25:26]{.aside}

εδει [σε]{.greek-added} ουν [σε]{.greek-omitted} βαλειν το αργυριον μου τοις [τραπεζιταις]{.greek-omitted} [τραπεζηταις]{.greek-added} και ελθων εγω εκομισαμην αν το εμον συν [τω]{.greek-added} τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και δοτε [τω]{.greek-omitted} [το]{.greek-added} εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον εκβαλετε εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τη δοξη [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε [καθισει]{.greek-omitted} [καθησει]{.greek-added} επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε [ερει]{.greek-omitted} [αιρει]{.greek-added} ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

[επεινασα]{.greek-omitted} [επινασα]{.greek-added} γαρ και εδωκατε μοι φαγειν [και]{.greek-added} [εδειψησα]{.greek-added} [εδιψησα]{.corr} και εποτισατε με ξενος ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και επεσκεψασθε με εν φυλακη ημην και [ηλθετε]{.greek-omitted} [ηλθαται]{.greek-added} προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} [πεινωντα]{.greek-omitted} [πινωντα]{.greek-added} και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και συνηγαγομεν η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε ειδομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς [ερει]{.greek-omitted} [αιρει]{.greek-added} αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι εποιησατε[25:40]{.aside}

τοτε [ερει]{.greek-omitted} [αιρει]{.greek-added} και τοις εξ ευωνυμων [πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} απ εμου [παντες]{.greek-added} οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ εποτισατε με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε ειδομεν [πεινωντα]{.greek-omitted} [πινωντα]{.greek-added} η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν [αι]{.greek-added} [αιωνιον]{.greek-omitted} [ωνιον]{.greek-added} οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους ειπεν τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις το σταυρωθηναι[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω κρατησωσιν και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη [εχουσα]{.greek-added} αλαβαστρον μυρου [εχουσα]{.greek-omitted} βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους [παρεχετε]{.greek-omitted} [παρεχεται]{.greek-added} τη γυναικι εργον γαρ καλον ειργασατο εις εμε[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} τους πτωχους [γαρ]{.greek-added} [παντοτε]{.greek-added} εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη [τουτο]{.greek-added} το μυρον [τουτο]{.greek-omitted} επι του σωματος μου προς το [ενταφιασαι]{.greek-omitted} [ενταφιασε]{.greek-added} με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των [δωδεκα]{.greek-omitted} [δοδεκα]{.greek-added} ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

ειπεν τι θελετε μοι δουναι [καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει [ευκαιριαν]{.greek-omitted} [ευκεριαν]{.greek-added} ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες [αυτω]{.greek-omitted} που θελεις [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν το πασχα[26:17]{.aside}

ο δε [ειπεν]{.greek-omitted} [λεγει]{.greek-added} [αυτοις]{.greek-added} υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς εστιν προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται [ως]{.greek-omitted} [καθως]{.greek-added} συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα [μαθητων]{.greek-added}[26:20]{.aside}

και [εσθιοντων]{.greek-omitted} [αισθιοντων]{.greek-added} αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν αυτω [εις]{.greek-added} εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο [εμβαψας]{.greek-omitted} [ενβαψας]{.greek-added} μετ εμου [την]{.greek-added} [χειρα]{.greek-added} εν τω τρυβλιω [την]{.greek-omitted} [χειρα]{.greek-omitted} ουτος με παραδωσει[26:23]{.aside}

[και]{.greek-added} ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω [ει]{.greek-omitted} [η]{.greek-added} ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον ειπεν μητι εγω ειμι [ραββι]{.greek-omitted} [ραββει]{.greek-added} λεγει αυτω συ ειπας[26:25]{.aside}

[εσθιοντων]{.greek-omitted} [αισθιοντων]{.greek-added} δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας εκλασεν και εδιδου τοις μαθηταις [αυτου]{.greek-added} και ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[26:26]{.aside}

και λαβων το ποτηριον [και]{.greek-omitted} ευχαριστησας εδωκεν αυτοις λεγων [πιετε]{.greek-omitted} [πιεται]{.greek-added} εξ αυτου παντες[26:27]{.aside}

τουτο γαρ εστιν το αιμα μου το της καινης διαθηκης το περι πολλων [εκχυνομενον]{.greek-omitted} [εκχυννομενον]{.greek-added} εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του [γεννηματος]{.greek-omitted} [γενηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις [σκανδαλισθησεσθε]{.greek-omitted} [σκανδα]{.greek-added} [λισθησεσθαι]{.greek-added} εν εμοι εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον [ποιμενα]{.greek-omitted} [ποιμαινα]{.greek-added} και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω δε ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν [τη]{.greek-added} [νυκτη]{.greek-added} [[νυκτι]{.corr}]{.greek-added} ταυτη [τη]{.greek-omitted} [νυκτι]{.greek-omitted} πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομε]{.greek-added} [ομοιως]{.greek-omitted} [ομοιος]{.greek-added} δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις χωριον λεγομενον [γεθσημανη]{.greek-omitted} [γεθσημανει]{.greek-added} και λεγει τοις μαθηταις [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} αυτου εως ου απελθων [προσευξωμαι]{.greek-omitted} εκει [προσευξομε]{.greek-added}[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους [ζεβα]{.greek-added} [ζεβεδαιου]{.corr} ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον εστιν [παρελθετω]{.greek-omitted} [παρελθατω]{.greek-added} απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} [μου]{.greek-omitted} ει ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} τουτο το ποτηριον παρελθειν απ εμου εαν μη [αυτο]{.greek-omitted} [αυτω]{.greek-added} πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων [ευρισκει]{.greek-omitted} [ευρεν]{.greek-added} αυτους παλιν καθευδοντας ησαν γαρ [αυτων]{.greek-omitted} οι οφθαλμοι [αυτων]{.greek-added} βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων [προσηυξατο]{.greek-added} παλιν [προσηυξατο]{.greek-omitted} [εκ]{.greek-omitted} [τριτου]{.greek-omitted} τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις [καθευδετε]{.greek-omitted} [καθευδεται]{.greek-added} το [λοιπον]{.greek-omitted} [λυπον]{.greek-added} και αναπαυεσθε ιδου ηγγικεν η ωρα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

[εγειρεσθε]{.greek-omitted} [εγειρεσθαι]{.greek-added} αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα ηλθεν και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των [αρχιερεων]{.greek-omitted} [αρχιεραιων]{.greek-added} και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον [αν]{.greek-omitted} [εαν]{.greek-added} φιλησω αυτος εστιν κρατησατε αυτον[26:48]{.aside}

και [ευ]{.greek-added} [ευθεως]{.greek-omitted} [θεως]{.greek-added} προσελθων τω [ιησου]{.greek-abbr} ειπεν χαιρε [ραββι]{.greek-omitted} [ραββει]{.greek-added} και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [εταιρε]{.greek-omitted} [ετερε]{.greek-added} εφ [ω]{.greek-omitted} [ο]{.greek-added} παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} [εκτεινας]{.greek-omitted} [εκτινας]{.greek-added} την χειρα απεσπασεν την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον σου την μαχαιραν εις τον τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν [μαχαιρα]{.greek-omitted} [μαχαιρη]{.greek-added} [αποθανουνται]{.greek-omitted} [απολουνται]{.greek-added}[26:52]{.aside}

η δοκεις οτι ου [δυναμαι]{.greek-omitted} [δυνομαι]{.greek-added} αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθαται]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος ηκολουθει αυτω απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και [ολον]{.greek-added} το συνεδριον [ολον]{.greek-omitted} εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως [θανατωσωσιν]{.greek-omitted} αυτον [θανατωσουσιν]{.greek-added}[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [τινες]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[26:63]{.aside}

[και]{.greek-added} λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον [επι]{.greek-omitted} [επει]{.greek-added} των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς διερρηξεν τα ιματια αυτου λεγων οτι εβλασφημησεν τι ετι [χρειαν]{.greek-omitted} [χριαν]{.greek-added} εχομεν μαρτυρων [ιδε]{.greek-omitted} [ειδε]{.greek-added} νυν ηκουσατε την [βλασ]{.greek-added} [βλασφημιαν]{.greek-omitted} [φημιαν]{.greek-added} αυτου[26:65]{.aside}

τι [υμιν]{.greek-omitted} [υμειν]{.greek-added} δοκει οι δε αποκριθεντες ειπον ενοχος θανατου εστιν[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και εκολαφισαν αυτον οι δε [ερραπισαν]{.greek-omitted} [εραπισαν]{.greek-added} [αυτον]{.greek-added}[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο [παισας]{.greek-omitted} [πεσας]{.greek-added} σε[26:68]{.aside}

ο δε πετρος [εκαθητο]{.greek-added} εξω [εκαθητο]{.greek-omitted} εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν [αυτων]{.greek-omitted} παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει αυτοις εκει και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο [μεθ]{.greek-omitted} [μετα]{.greek-added} ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα [δε]{.greek-added} μικρον [δε]{.greek-omitted} προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ εφωνησεν[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος [του]{.greek-omitted} [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω εκλαυσεν πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και οι πρεσβυτεροι [του]{.greek-omitted} [λαου]{.greek-omitted} [των]{.greek-added} [ιουδαιων]{.greek-added} κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και [δη]{.greek-added} [δησαντες]{.greek-omitted} [σαντες]{.greek-added} αυτον απηγαγον και παρεδωκαν αυτον ποντιω πιλατω τω [ηγεμονι]{.greek-omitted} [ηγεμωνι]{.greek-added}[27:2]{.aside}

τοτε ιδων ιουδας ο παραδιδους αυτον οτι κατεκριθη [μεταμεληθεις]{.greek-omitted} [μεταμεληθης]{.greek-added} απεστρεψεν τα τριακοντα αργυρια τοις αρχιερευσιν και τοις πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε ειπον τι προς ημας συ [οψει]{.greek-omitted} [οψη]{.greek-added}[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω ανεχωρησεν και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ εξεστιν βαλειν αυτα εις τον κορβαναν επει τιμη αιματος εστιν[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του [τετιμημενου]{.greek-omitted} [τετημημενου]{.greek-added} ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα συνεταξεν μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του [ηγεμονος]{.greek-omitted} [ηγεμωνος]{.greek-added} και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω [κατηγορεισθαι]{.greek-omitted} [κατηγορεισθε]{.greek-added} αυτον υπο των αρχιερεων και [πρεσβυ]{.greek-added} [των]{.greek-omitted} [τερων]{.greek-added} [πρεσβυτερων]{.greek-omitted} ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου καταμαρτυρουσιν[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον [ηγεμονα]{.greek-omitted} [ηγεμωνα]{.greek-added} λιαν[27:14]{.aside}

κατα δε εορτην [ειωθει]{.greek-omitted} [ειωθη]{.greek-added} ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα [θελετε]{.greek-omitted} [θελεται]{.greek-added} απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

[ηδει]{.greek-omitted} [ειδη]{.greek-added} γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος απεστειλεν προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα [αιτησωνται]{.greek-omitted} [αιτισονται]{.greek-added} τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον [τον]{.greek-added} βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν [αυτω]{.greek-omitted} παντες σταυρωθητω[27:22]{.aside}

[λεγει]{.greek-added} [αυτοις]{.greek-added} ο [δε]{.greek-omitted} ηγεμων [εφη]{.greek-omitted} τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες σταυρωθητω[27:23]{.aside}

ιδων δε ο πιλατος οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added}[27:24]{.aside}

και αποκριθεις πας ο λαος ειπεν το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φραγελλωσας παρεδωκεν [αυτοις]{.greek-added} ινα σταυρωθη[27:26]{.aside}

τοτε οι στρατιωται του [ηγεμονος]{.greek-omitted} [ηγεμωνος]{.greek-added} παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων [επεθηκαν]{.greek-omitted} [εθηκαν]{.greek-added} επι την κεφαλην αυτου και καλαμον [επι]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [δεξιαν]{.greek-omitted} [δεξια]{.greek-added} αυτου και γονυπετησαντες εμπροσθεν αυτου [ενεπεζαν]{.greek-added} [ενεπαιζον]{.greek-omitted} [[ενεπεζον]{.corr}]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το σταυρωσαι[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα ο εστιν [λεγομενος]{.greek-omitted} [λεγομενον]{.greek-added} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης [μεμιγμενον]{.greek-omitted} [μεμηγμενον]{.greek-added} και γευσαμενος ουκ [ηθελεν]{.greek-omitted} [ηθελησεν]{.greek-added} πιειν[27:34]{.aside}

σταυρωσαντες δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-abbr} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε σταυρουνται συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον [ει]{.greek-omitted} [η]{.greek-added} [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} καταβηθι απο του σταυρου[27:40]{.aside}

ομοιως δε και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} μετα των [γραμματεων]{.greek-omitted} [πρεσβυτερων]{.greek-added} και [πρεσβυτερων]{.greek-omitted} [γραμματαιων]{.greek-added} και φαρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} εστιν [καταβατω]{.greek-omitted} [καταβητω]{.greek-added} νυν απο του σταυρου και [πιστευσομεν]{.greek-omitted} [πιστευομεν]{.greek-added} επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω νυν αυτον ει θελει αυτον ειπεν γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι [συσταυρωθεντες]{.greek-omitted} [συνσταυρωθεντες]{.greek-added} αυτω ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας ενατης[27:45]{.aside}

περι δε την ενατην ωραν [ανεβωησεν]{.greek-added} [ανεβοησεν]{.corr} ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι λιμα σαβαχθανι τουτ εστιν θεε μου θεε μου [ινα]{.greek-omitted} [εισ]{.greek-added} τι με [εγκατελιπες]{.greek-omitted} [εγκατελειπες]{.greek-added}[27:46]{.aside}

τινες δε των εκει [εστωτων]{.greek-omitted} [εστηκοτων]{.greek-added} ακουσαντες ελεγον οτι ηλιαν [φωνει]{.greek-omitted} [φωνη]{.greek-added} ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας σωσων αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη αφηκεν το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη [εσεισθη]{.greek-omitted} [εσισθη]{.greek-added} και αι πετραι εσχισθησαν[27:51]{.aside}

και τα [μνημεια]{.greek-omitted} [μνημια]{.greek-added} ανεωχθησαν και πολλα σωματα των κεκοιμημενων αγιων ηγερθη[27:52]{.aside}

και εξελθοντες εκ των [μνημειων]{.greek-omitted} [μνημιων]{.greek-added} μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον [σεισμον]{.greek-omitted} [σισμον]{.greek-added} και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} [υιος]{.greek-abbr} ην ουτος[27:54]{.aside}

ησαν δε εκει γυναικες πολλαι απο μακροθεν [θεωρουσαι]{.greek-omitted} [θεορουσαι]{.greek-added} αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια η του ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε [γενομενης]{.greek-omitted} [γεναμενης]{.greek-added} ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ ος και αυτος εμαθητευσεν τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ [ενετυλιξεν]{.greek-omitted} [ενετυληξεν]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added} σινδονι καθαρα[27:59]{.aside}

και εθηκεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν τω καινω αυτου [μνημειω]{.greek-omitted} [μνημιω]{.greek-added} ο ελατομησεν εν τη πετρα και προσκυλισας λιθον μεγαν τη θυρα του [μνημειου]{.greek-omitted} [μνηματος]{.greek-added} απηλθεν[27:60]{.aside}

ην δε εκει μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη μαρια καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις εστιν μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι [και]{.greek-added} [οι]{.greek-added} [πρεσβυτεροι]{.greek-added} προς πιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου [νυκτος]{.greek-omitted} κλεψωσιν αυτον και ειπωσιν τω λαω ηγερθη απο των νεκρων και [εσται]{.greek-omitted} [εστε]{.greek-added} η εσχατη πλανη χειρων της πρωτης[27:64]{.aside}

εφη δε αυτοις ο πιλατος εχετε κουστωδιαν υπαγετε [ασφαλισασθε]{.greek-omitted} [ασφαλισασθαι]{.greek-added} ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε [δε]{.greek-omitted} σαββατων τη επιφωσκουση εις μιαν σαββατων ηλθεν μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου [σεισμος]{.greek-omitted} [σισμος]{.greek-added} εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} [προσελθων]{.greek-omitted} [προσελθον]{.greek-added} απεκυλισεν τον λιθον απο της θυρας και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η [ιδεα]{.greek-omitted} [ειδεα]{.greek-added} αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου [εσεισθησαν]{.greek-omitted} [εσισθησαν]{.greek-added} οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος ειπεν ταις [γυναιξειν]{.greek-added} [γυναιξιν]{.corr} μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added} υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον εσταυρωμενον ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως ειπεν δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ πορευθεισαι ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του [μνημειου]{.greek-omitted} [μνημιου]{.greek-added} μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

ως δε επορευοντο απαγγειλαι τοις μαθηταις αυτου και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} απηντησεν αυταις λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added} υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν και εκει με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

λεγοντες ειπατε οτι οι μαθηται αυτου νυκτος ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο [επι]{.greek-omitted} [επει]{.greek-added} του [ηγεμονος]{.greek-omitted} [ηγεμωνος]{.greek-added} ημεις [πεισομεν]{.greek-omitted} [πισομεν]{.greek-added} αυτον και υμας αμεριμνους [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added}[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και διεφημισθη ο λογος ουτος παρα ιουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι [της]{.greek-added} γης[28:18]{.aside}

πορευθεντες μαθητευσατε παντα τα [εθνη]{.greek-omitted} [αιθνη]{.greek-added} βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του [υιου]{.greek-abbr} και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

