---
title: "Collation of Byz^RP^ vs 31306 (1306)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1306 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31306).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1306                                   	| λογος                              	|
| 1306 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1306 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1306               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1306                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1306 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1306                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 26

[λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [καν]{.greek-omitted} [δεη]{.greek-omitted} [με]{.greek-omitted} [συν]{.greek-omitted} [σοι]{.greek-omitted} [αποθανειν]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [σε]{.greek-omitted} [απαρνησωμαι]{.greek-omitted} [νησωμαι]{.greek-added} ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε [ε]{.unclear}ρχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον γεθσημανη και λεγει τοις μαθηταις καθισατε αυτου εως [ου]{.greek-omitted} [αν]{.greek-added} απελθων προσευξωμαι εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θα[νατου]{.unclear} μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και [προσελθων]{.greek-omitted} [προελθων]{.greek-added} μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθετω [α]{.unclear}π εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει τω πετρω ουτως ουκ ι[σ]{.unclear}χυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων [προ]{.greek-added} [προσηυξατο]{.greek-omitted} [σηυξατο]{.greek-added} λεγων [πατερ]{.greek-abbr} μου ει ου δυναται τουτο το ποτηριον παρελθειν απ εμου εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων [ευρισκει]{.greek-omitted} [ευρεν]{.greek-added} αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφ[εις]{.unclear} αυτους απελθων παλιν προσηυξ[α]{.unclear}το εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα [ηλθεν]{.greek-omitted} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε πα[ρ]{.unclear}αδιδους αυτον εδωκεν αυτοις σημειον λεγων ον [αν]{.greek-omitted} [εαν]{.greek-added} φιλησω αυτος [εστιν]{.unclear} κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} χαιρε ραβ[βι]{.unclear} και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ ω παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [ιησου]{.greek-abbr} εκτεινας την χειρα [απεσπασεν]{.greek-omitted} [απεσπασε]{.greek-added} την μαχαιραν αυτου και παταξας τον δουλον του αρχι[ε]{.unclear}ρεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον σου την μαχαιραν εις τον τοπον αυτης παντ[ες]{.unclear} γαρ οι λαβοντες μαχαιραν εν [μαχαιρα]{.greek-omitted} [μαχαιρη]{.greek-added} [αποθανουνται]{.greek-omitted} [απολουνται]{.greek-added}[26:52]{.aside}

η δοκεις οτι ου δυναμαι αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην [διδασκων]{.greek-omitted} εν τω ιερω [διδασκων]{.greek-added} και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα [πληρωθωσιν]{.greek-omitted} [πληρωθωσι]{.greek-added} αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος ηκολουθει [αυτω]{.greek-omitted} απο μακροθεν εως της αυλης [του]{.unclear} αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και το συνεδριον ολον εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως θανατωσωσιν αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρ[ες]{.unclear}]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} [ειπον]{.greek-omitted} [ειπαν]{.greek-added} ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

[και]{.unclear} αναστας ο αρχιερευς ειπεν αυτω ουδεν αποκρινη τι ουτοι σου κατα[μα]{.unclear}ρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω [εξορκιζω]{.greek-omitted} [ορκιζω]{.greek-added} σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην [λεγω]{.greek-omitted} [λε]{.greek-added} [γω]{.greek-added} υμιν απ αρτι οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματια αυτου λεγων οτι [εβλασφημησεν]{.greek-omitted} [εβλασφημησε]{.greek-added} τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου εστιν[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και εκολαφισαν αυτον οι δε [ερραπισαν]{.greek-omitted} [εραπισαν]{.greek-added}[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-omitted} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν αυτων παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει [αυτοις]{.greek-omitted} [τοις]{.greek-added} εκει και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο [μεθ]{.greek-omitted} [μετα]{.greek-added} ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δ[η]{.unclear}λον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος του [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι [τρις]{.greek-omitted} [τρ[ει]{.unclear}ς]{.greek-added} απαρνηση με και εξελθων εξω [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι αρχιερεις και [οι]{.greek-omitted} πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν αυτον ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε ιδων ιουδας ο παραδιδους αυτον οτι κατεκριθη μεταμεληθεις [απεστρεψεν]{.greek-omitted} [απεστρεψε]{.greek-added} τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχ[ιε]{.unclear}ρευ[σι]{.unclear}]{.greek-added} και [τοις]{.greek-omitted} πρεσβυτεροις[27:3]{.aside}

λεγων [ημαρ]{.unclear}τον παραδους αιμα αθωον οι δε ειπον τι προς ημας συ [οψει]{.greek-omitted} [οψη]{.greek-added}[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω ανεχωρησεν και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον [κορβαναν]{.greek-omitted} [κορβοναν]{.greek-added} επει τιμη αιματος [εστιν]{.greek-omitted} [εστι]{.greek-added}[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα [συνεταξεν]{.greek-omitted} [συνεταξε]{.greek-added} μοι [ο]{.greek-added} [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και των πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου [κα]{.greek-added} [καταμαρτυρουσιν]{.greek-omitted} [ταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτον η γυνη αυτου λε[γου]{.unclear}σα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραβ[β]{.unclear}αν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} [λεγουσιν]{.greek-omitted} [λεγου[σι]{.unclear}]{.greek-added} [αυτω]{.greek-omitted} παντες [σταυρωθητω]{.greek-abbr} [[σταυρωθητω]{.greek-abbr}]{.greek-added}[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον [λεγοντες]{.greek-omitted} [σταυρωθητω]{.greek-abbr}[27:23]{.aside}

ιδων δε ο πιλατος οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φ[ρα]{.unclear}γελλωσας παρεδωκεν ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων [επεθηκαν]{.greek-omitted} [εθηκαν]{.greek-added} επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και γονυπετησαντες εμπροσθεν αυτου ενεπαιζον αυτω λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα [ο]{.greek-omitted} [ος]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγομενος κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ ηθελεν πιειν[27:34]{.aside}

[σταυρωσαντες]{.greek-abbr} δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμ[ενην]{.unclear} ουτος εστιν [ιησους]{.greek-abbr} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουνται]{.greek-abbr} συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημ[ουν]{.unclear} αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον να[ον]{.unclear} και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} καταβηθι απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως [δε]{.greek-omitted} και οι αρχιερεις εμπαιζοντες μετα των γραμματεων και πρεσβυτερων και φαρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} και πιστευσομεν επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω [νυν]{.greek-omitted} αυτον ει θελει αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι [συσταυρωθεντες]{.greek-abbr} αυτω ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας ενατης[27:45]{.aside}

περι δε την ενατην ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι λιμα σαβαχθανι τ[ου]{.unclear}τ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου [θεε]{.greek-omitted} [θε]{.greek-added} μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελιπες[27:46]{.aside}

τινες δε των εκει [εστωτων]{.greek-omitted} [εστητων]{.greek-added} ακουσαντες ελεγον οτι ηλιαν φωνει ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας σωσων αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη εσεισθη και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια [ανεωχθησαν]{.greek-omitted} [ανεωχθη]{.greek-added} και πολλα σωματα των κεκοιμημενων αγιων [ηγερθη]{.greek-omitted} [ηγερθησαν]{.greek-added}[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλ[οις]{.unclear}[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} υιος ην ουτος[27:54]{.aside}

ησαν δε εκει [και]{.greek-added} γυναικες πολλαι [απο]{.greek-omitted} μακροθεν θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν [αις]{.unclear} [ην]{.unclear} μαρια η μαγδαληνη και μαρια η του ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων [ζε]{.unclear}βεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ [ος]{.unclear} και αυτος [εμαθητευσεν]{.greek-omitted} [εμαθητευσε]{.greek-added} τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος [προ]{.greek-added} [προσελθων]{.greek-omitted} [σελθων]{.greek-added} τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ ενετυλιξεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} σινδονι καθαρα[27:59]{.aside}

και εθηκεν αυτο εν τω καινω αυτου μνημειω ο ελατομησεν εν τη πετρα και προσκυλισας λιθον μεγαν τη θυρα του μνημειου [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[27:60]{.aside}

ην δε εκει μαρια η μαγδαληνη και η αλλη μαρια καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς πιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου [νυκτος]{.greek-omitted} κλεψωσιν αυτον και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} τω λαω ηγ[ερ]{.unclear}θη απο των νεκρων και εσται η εσχατη πλανη χειρων της πρωτης[27:64]{.aside}

εφη [δε]{.greek-omitted} αυτοις ο πιλατος εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον [σφραγισαντες]{.greek-omitted} [τον]{.greek-omitted} [λιθον]{.greek-omitted} μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε δε σαββατων τη επιφωσκουση εις μιαν σαββατων [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} μαρια η μαγδαληνη και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ ουρανου προσελθων [απεκυλισεν]{.greek-omitted} [απεκυλισε]{.greek-added} τον λιθον απο της θυρας και εκαθητο επανω αυτου[28:2]{.aside}

ην δε [η]{.greek-omitted} [ιδεα]{.greek-omitted} [[ει]{.unclear}δεα]{.greek-added} αυτου ως αστραπη και το ενδυμα αυτου λευκον [ωσει]{.greek-omitted} [ως]{.greek-added} χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

αποκριθεις δε ο αγγελος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταις [γυναιξιν]{.greek-omitted} [γ[υν]{.unclear}αιξι]{.greek-added} μη φοβεισθε υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον [εσταυρωμενον]{.greek-abbr} ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δευτε ιδετε τον το[πον]{.unclear} οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ πορευθεισαι ειπατε τοις μαθ[ηταις]{.unclear} α[υτου]{.unclear} οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την [γα]{.greek-added} [γαλιλαιαν]{.greek-omitted} [λιλαιαν]{.greek-added} εκει αυτον οψεσθε ιδου ειπον υμιν[28:7]{.aside}

και [εξελθουσαι]{.greek-omitted} [απελθουσαι]{.greek-added} ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

ως δε επορευοντο απαγγειλαι τοις μαθηταις αυτου και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} [απηντησεν]{.greek-omitted} [υπηντησεν]{.greek-added} αυταις λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν και εκει με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχ[θεν]{.unclear}τες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

λεγοντες ειπατε οτι οι μαθηται αυτου νυκ[τος]{.unclear} ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις πεισομεν αυτον και υμας αμεριμνους ποιησομεν[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και διεφημισθη ο λογος ουτος παρα ιουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτ[ον]{.unclear} προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησ[εν]{.unclear} αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθ[εν]{.unclear}τες μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

