---
title: "Collation of Byz^RP^ vs 31337 (1337)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1337 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31337).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1337                                   	| λογος                              	|
| 1337 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1337 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1337               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1337                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1337 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1337                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [υιου]{.greek-omitted} του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη [βοωντος]{.greek-omitted} [βοοντος]{.greek-added} εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγεν[ε]{.unclear}το [ιωαννης]{.greek-abbr} βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο [ιωαννης]{.greek-abbr} ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ου[κ]{.unclear} ειμι [ι]{.unclear}κανος κυψας λυσαι τον ιμα[ν]{.unclear}τα των υποδηματων αυτου [και]{.greek-added} [εκηρυσσε]{.greek-added} [λεγων]{.greek-added} [ερχετε]{.greek-added} [ο]{.greek-added} [ισχυριτερος]{.greek-added} [μου]{.greek-added} [οπισω]{.greek-added} [μου]{.greek-added}[1:7]{.aside}

εγ[ω]{.unclear} [μεν]{.greek-omitted} [εβα]{.unclear}πτισ[α]{.unclear} [υμας]{.unclear} [εν]{.unclear} [υ]{.unclear}δατι α[υ]{.unclear}το[ς]{.unclear} [δε]{.unclear} βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη υπο [ιωαννου]{.greek-abbr} εις τ[ον]{.greek-supplied} ιορδανην [και]{.greek-added} [εγενετο]{.greek-added} [εν]{.greek-added} [εκειναις]{.greek-added} [ταις]{.greek-added} [ημεραις]{.greek-added} [ηλθεν]{.greek-added} [ο]{.greek-added} [ιησους]{.greek-added} [απο]{.greek-added} [ναζαρετ]{.greek-added}[1:9]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} αναβαινων απο του υδατος ειδεν σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και [φω]{.unclear}νη εγενετο εκ των [ουρανων]{.greek-abbr} συ [ει]{.unclear} ο υιος μου ο αγαπητος εν ω ευδοκησα[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον [ευθυς]{.greek-added} [το]{.greek-added} [[πνευμα]{.greek-abbr}]{.greek-added} [αυτον]{.greek-added} [εκβαλλει]{.greek-added} [εις]{.greek-added} [την]{.greek-added} [ερημον]{.greek-added}[1:12]{.aside}

και ην εκει εν τη ερημω [τεσσαρακοντα]{.greek-added} ημ[ερ]{.unclear}ας [τεσσαρακοντα]{.greek-omitted} πειραζομενος υπο του σατανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δ[ε]{.unclear} το παραδοθηναι [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [ηλθεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted} [κηρυσσων]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [της]{.greek-omitted} [βασιλειας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[[1:14 *(lacunose)*]{.lacunose}]{.aside}

[και]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [πεπληρωται]{.greek-omitted} [ο]{.greek-omitted} [καιρος]{.greek-omitted} [και]{.greek-omitted} [ηγγικεν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μετανοειτε]{.greek-omitted} [και]{.greek-omitted} [πιστευετε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ευαγγελιω]{.greek-omitted}[[1:15 *(lacunose)*]{.lacunose}]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου [του]{.greek-omitted} σιμωνος βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και [ειπ]{.unclear}εν αυτ[οις]{.greek-supplied} ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υ[μ]{.unclear}ας [γενεσθαι]{.greek-omitted} αλι[ε]{.unclear}ις [ανθρωπων]{.greek-abbr} [γενεσθαι]{.greek-added}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα [αυτων]{.greek-omitted} ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον [τον]{.greek-omitted} του ζεβεδαιου και [ιωαννην]{.greek-abbr} τον αδελφον αυτου [και]{.unclear} αυτ[ους]{.greek-supplied} εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτ[ων]{.greek-supplied} ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν[1:21]{.aside}

και εξεπλησσοντο [παντες]{.greek-added} επι τη διδαχη αυτου ην γαρ διδασκων [αυτους]{.greek-omitted} ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και [επετιμησεν]{.greek-omitted} [επετιμησας]{.greek-added} αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν [παντες]{.greek-omitted} [απαντες]{.greek-added} ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις [εστιν]{.greek-added} η διδαχη [η]{.greek-omitted} καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-abbr} τοις ακαθαρτοις επιτασσ[ει]{.unclear} και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν [δε]{.greek-omitted} η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και [ευθεως]{.unclear} [εκ]{.unclear} της σ[υν]{.unclear}αγωγης εξελθον[τες]{.greek-supplied} [ηλθ]{.greek-supplied}[ο]{.unclear}ν εις τ[ην]{.unclear} [οι]{.greek-supplied}κ[ιαν]{.unclear} [σι]{.unclear}μωνος και αν[δρ]{.unclear}εου μετα ιακωβου και [ιωαννου]{.greek-omitted} [[ιωαννης]{.greek-abbr}]{.greek-added}[1:29]{.aside}

η [δε]{.greek-supplied} π[ε]{.unclear}νθε[ρα]{.unclear} [σι]{.unclear}μωνος [κατεκ]{.unclear}ειτο πυρεσσουσα και [ευ]{.unclear}θε[ως]{.unclear} λε[γ]{.unclear}ουσιν [αυτω]{.greek-supplied} [περι]{.greek-supplied} [αυτης]{.greek-supplied}[1:30]{.aside}

και προσελθων [ηγειρ]{.unclear}εν αυτην κρ[ατη]{.unclear}[σας]{.greek-supplied} της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε [εδυ]{.greek-omitted} [ε[δυσεν]{.unclear}]{.greek-added} ο ηλιος [εφερον]{.greek-supplied} [προς]{.greek-supplied} [αυτον]{.greek-supplied} [παντας]{.greek-supplied} [τους]{.greek-supplied} [κακως]{.greek-supplied} [εχοντας]{.greek-supplied} και τους [δαι]{.greek-supplied}[μονιζομενους]{.greek-supplied}[1:32]{.aside}

[και]{.greek-supplied} [[ολη]{.greek-supplied}]{.greek-added} [η]{.greek-supplied} [πολις]{.greek-supplied} [ολη]{.greek-omitted} [επισυνηγμενη]{.greek-supplied} ην προ[ς]{.unclear} την [θυραν]{.greek-supplied}[1:33]{.aside}

[και]{.greek-supplied} [εθεραπευσεν]{.greek-supplied} [π]{.unclear}[ολ]{.greek-supplied}λους κακως εχοντας ποικι[λαι]{.unclear}ς νοσ[οι]{.unclear}[ς]{.greek-supplied} [και]{.greek-supplied} [δαιμονια]{.greek-supplied} [πο]{.unclear}λλα εξεβαλ[εν]{.unclear} [και]{.greek-supplied} [ουκ]{.greek-supplied} [ηφιεν]{.greek-omitted} [[η]{.unclear}φ[ιε]{.unclear}]{.greek-added} λαλειν τα [δαιμονι]{.greek-supplied}α οτι [ηδεισαν]{.unclear} [αυτον]{.greek-omitted} [το[ν]{.unclear}]{.greek-added} [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι ε[ν]{.unclear}[νυχον]{.greek-supplied} [λιαν]{.unclear} α[ν]{.unclear}αστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερ[ημον]{.greek-supplied} τ[ο]{.unclear}[πον]{.greek-supplied} κακει [πρ]{.unclear}οσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} οτι [παντες]{.greek-omitted} [παν]{.greek-added} [τες]{.greek-added} σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει [κηρυξω]{.greek-omitted} [κηρυξωμεν]{.greek-added} εις τουτο γαρ [εξε]{.greek-added} [εξεληλυθα]{.greek-omitted} [ληλυθα]{.greek-added}[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων αυτω οτι εαν θελης δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο [αυτου]{.greek-omitted} και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και [ε]{.unclear}μ[βρ]{.unclear}ιμ[η]{.unclear}σαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σε[αυ]{.unclear}τον [δ]{.unclear}ειξον τω ιερει και προσενεγκε περι του καθαρισμου σου [α]{.greek-omitted} [ο]{.greek-added} [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων [ηρ]{.greek-supplied}ξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μ[η]{.unclear}κετι αυτον δυνασθαι φανερως εις πολιν [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45]{.aside}

### Chapter 2

και εισηλθεν [παλιν]{.greek-omitted} εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον [κραββατον]{.greek-omitted} [κραβατον]{.greek-added} εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως [λαλει]{.greek-omitted} [βλασφημιας]{.greek-omitted} [βλασφημει]{.greek-added} τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} [τω]{.greek-omitted} [το]{.greek-added} [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον σου τον κραββατον και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} αφιεναι [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

[σοι]{.greek-omitted} [συ]{.greek-added} λεγω εγειραι και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και [εγερθεις]{.greek-added} [ευθυς]{.greek-added} [ηγερθη]{.greek-omitted} [ευθεως]{.greek-omitted} [και]{.greek-omitted} αρας τον κραββατον εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως ειδομεν[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο [τω]{.greek-omitted} [μετα]{.greek-added} [του]{.greek-added} [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και [εγενετο]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [κατακεισθαι]{.greek-added} οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις [αυτου]{.greek-omitted} τι οτι μετα [των]{.greek-omitted} τελωνων και αμαρτωλων εσθιει και [πινει]{.greek-omitted} [πινη]{.greek-added}[2:16]{.aside}

[και]{.greek-omitted} ακουσας [δε]{.greek-added} ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται [ιωαννου]{.greek-abbr} και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται [ιωαννου]{.greek-abbr} και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων εστιν νηστευειν οσον χρονον μεθ [εαυτων]{.greek-omitted} [αυτων]{.greek-added} εχουσιν τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται [δε]{.greek-omitted} [δ]{.greek-added} [αι]{.greek-added} ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω ει δε μη αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται αλλα οινον νεον εις ασκους καινους [βλητεον]{.greek-omitted} [βληται]{.greek-added}[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν [τιλλοντες]{.greek-omitted} [τιλοντες]{.greek-added} τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ εξεστιν[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι εποιησεν [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ εξεστιν φαγειν ει [μη]{.greek-omitted} [μι]{.greek-added} τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουση]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις σαββασιν θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} [τω]{.greek-omitted} [το]{.greek-added} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα εγειραι εις τ[ο]{.unclear} μεσον[3:3]{.aside}

και λεγει αυτοις [τι]{.greek-added} [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου υγιης ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον απολεσωσιν[3:6]{.aside}

και ο [ιησους]{.greek-abbr} ανεχωρησεν μετα των μαθητων αυτου [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν και [πολυ]{.greek-omitted} [πολλυ]{.greek-added} πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπον]{.greek-added} τοις μαθηταις [αυτου]{.greek-omitted} ινα πλοιαριον προσκαρτερη αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου αψωνται οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα [οταν]{.greek-omitted} [οτε]{.greek-added} αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} [λεγοντα]{.greek-omitted} [λεγοντες]{.greek-added} οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις [το]{.greek-omitted} ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ινα ωσιν μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} [αυτους]{.greek-omitted} κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν [τας]{.greek-added} [νοσσους]{.greek-added} θεραπευειν [τας]{.greek-omitted} [νοσους]{.greek-omitted} και [εκβαλλειν]{.greek-omitted} [εκβαλειν]{.greek-added} τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [αυτου]{.greek-added} του ιακωβου και επεθηκεν αυτοις ονοματα [ο]{.greek-added} βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν [τον]{.greek-added} ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν [ο]{.greek-added} οχλος ωστε μη δυνασθαι [αυτους]{.greek-omitted} [αυτον]{.greek-added} [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων [εκβαλλει]{.greek-omitted} [εκβαλει]{.greek-added} τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [εκεινη]{.greek-omitted} [αλλα]{.greek-added} [τελος]{.greek-added} [εχει]{.greek-added}[3:24]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται [τοις]{.greek-added} [[ανθρωποις]{.greek-abbr}]{.greek-added} τα αμαρτηματα [τοις]{.greek-omitted} [υιοις]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [και]{.greek-omitted} [βλασφημιαι]{.greek-omitted} [βλασφημιας]{.greek-added} οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημησει]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου [εξωθεν]{.greek-added} [και]{.greek-omitted} [εξω]{.greek-omitted} εστωτες απεστειλαν [ουν]{.greek-added} [φωνουντες]{.greek-added} προς αυτον [φωνουντες]{.greek-omitted} [αυτον]{.greek-omitted}[3:31]{.aside}

και εκαθητο οχλος περι αυτον ειπον δε αυτω [οι]{.greek-added} [ιδου]{.greek-omitted} [η]{.greek-omitted} [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και μητηρ [εστιν]{.greek-omitted} [μου]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον [καθησθαι]{.greek-omitted} [καθεισθαι]{.greek-added} εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

[ακουετε]{.greek-omitted} [ακουσατε]{.greek-added} [οτι]{.greek-added} ιδου εξηλθεν ο [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} του σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν επεσεν παρα την οδον και ηλθεν τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο [δε]{.greek-omitted} επεσεν επι το πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου [δε]{.unclear} ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

[και]{.greek-omitted} αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα [και]{.greek-omitted} [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} εκατον[4:8]{.aside}

και ελεγεν [ο]{.greek-omitted} [ος]{.greek-added} εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν [δεδοται]{.greek-omitted} [δεδωται]{.greek-added} γνωναι [το]{.greek-omitted} [τα]{.greek-added} [μυστηριον]{.greek-omitted} [μυστηρια]{.greek-added} της βασιλειας του [θεου]{.greek-abbr} [εκεινοις]{.greek-omitted} [τοις]{.greek-added} δε [λοιποις]{.greek-added} [τοις]{.greek-omitted} [εξω]{.greek-omitted} εν παραβολαις [τα]{.greek-omitted} [παντα]{.greek-omitted} [γινεται]{.greek-omitted}[4:11]{.aside}

ινα βλεποντες βλεπωσιν και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και [αφεθη]{.greek-omitted} [αφεθησεται]{.greek-added} αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας [γνωσεσθε]{.greek-omitted} [γνωσεσθαι]{.greek-added}[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και [αιρει]{.greek-omitted} [ερει]{.greek-added} τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτ[οι]{.greek-supplied} [εισιν]{.greek-omitted} [ομοιως]{.greek-omitted} οι επι τα πετρωδη σπειρομενοι οι [οταν]{.greek-omitted} [ακουσωσιν]{.greek-omitted} τον λογον [ακο[υσωσιν]{.greek-supplied}]{.greek-added} [και]{.greek-added} [ευ]{.greek-supplied}θεως μετα χαρας λαμβανουσιν αυτον[[4:16 *(lacunose)*]{.lacunose}]{.aside}

και ουκ εχ[ουσιν]{.greek-supplied} [ριζ]{.greek-supplied}αν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομ[ενης]{.greek-supplied} [θλιψεως]{.greek-supplied} η διωγμου δια τον λογον ευθεως σκανδαλιζοντα[ι]{.unclear}[4:17]{.aside}

[και]{.greek-supplied} ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι συμπνιγουσιν τον λογον και ακαρπος [γινεται]{.greek-omitted} [γινονται]{.greek-added}[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν εν τριακοντα και εν εξηκοντα και εν εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα [επι]{.greek-omitted} [υπο]{.greek-added} την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21]{.aside}

ου γαρ εστιν [τι]{.greek-omitted} κρυπτον ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν [ακουεται]{.greek-added} [ακουετω]{.corr}[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω [μετρειτε]{.greek-omitted} [μετρητε]{.greek-added} μετρηθησεται [υμιν]{.greek-omitted} [και]{.greek-omitted} [προστεθησεται]{.greek-omitted} υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ αν εχη δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και [καθευθει]{.greek-added} [καθευδη]{.greek-omitted} [[καθευδωι]{.corr}]{.greek-added} και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα [και]{.greek-added} [ημεραν]{.greek-added} και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον [ειτα]{.greek-omitted} [επειτα]{.greek-added} σταχυν ειτα [πληρη]{.greek-omitted} [πληρης]{.greek-added} σιτον εν τω σταχυι[4:28]{.aside}

[οταν]{.greek-omitted} [οτε]{.greek-added} δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} [παραβαλλωμεν]{.greek-added} αυτην[4:30]{.aside}

ως κοκκο[ν]{.unclear} σιναπεως ο[ς]{.unclear} οταν [σπαρη]{.greek-omitted} [σπειρη]{.greek-added} επι της γης [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων των σπερματων εστιν [των]{.greek-omitted} επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως [ε]{.unclear}δυναντο ακου[ειν]{.greek-supplied}[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [[ε]{.unclear}πελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν [τω]{.greek-omitted} [το]{.greek-added} πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λελαψ]{.greek-added} ανεμου [μεγαλη]{.greek-omitted} [μεγας]{.greek-added} τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι το προσκεφαλαιον [καθευδων]{.greek-omitted} [καθευδον]{.greek-added} και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

[και]{.unclear} διεγερθεις επετιμησεν τω ανεμω και ειπεν τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως [πως]{.unclear} ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα [εστιν]{.greek-added} ουτος [εστιν]{.greek-omitted} οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και [εξελθοντι]{.greek-omitted} [εξελθοντος]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} εκ του πλοιου ευθεως [απηντησεν]{.greek-omitted} [υπηντησεν]{.greek-added} αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και αλυσεσιν δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις αυτον [ισχυεν]{.greek-omitted} [ισχυσε]{.greek-added} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [μνημειοις]{.greek-added} ην κραζων και κατακοπτων εαυτον [λιθοις]{.greek-supplied}[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν εδραμεν και προσεκυνησεν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[5:6]{.aside}

και κραξας φωνη μεγαλη ειπεν τι εμοι και σοι [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [[ε]{.unclear}λεγε]{.greek-added} γαρ αυτω [εξελθε]{.greek-omitted} [εξελθειν]{.greek-added} το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και [επηρωτα]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτον τι [σοι]{.greek-omitted} ονομα και απεκριθη λεγων [λεγεων]{.greek-omitted} ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα [μη]{.greek-omitted} [αποστειλη]{.greek-added} αυτους [αποστειλη]{.greek-omitted} εξω της χωρας[5:10]{.aside}

ην δε [εκ]{.unclear}ει προς τ[ω]{.greek-supplied} [ορει]{.greek-supplied} αγελη χοιρων μεγαλη βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον [παντες]{.greek-omitted} [λεγοντες]{.greek-added} οι δαιμονες [λεγοντες]{.greek-omitted} πεμψον ημας [εις]{.unclear} [τους]{.unclear} [χοιρ]{.unclear}ους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρε[ψε]{.unclear}ν [αυτοις]{.unclear} [ευ]{.unclear}θεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} τα [ακαθαρτα]{.greek-omitted} [καθαρ[τα]{.greek-supplied}]{.greek-added} [εισηλθον]{.greek-supplied} εις τ[ους]{.unclear} χοιρους και [ωρμησεν]{.greek-omitted} [ορμησεν]{.greek-added} η αγελη κατα τ[ου]{.unclear} κρημνου εις τ[ην]{.unclear} θ[αλασσαν]{.greek-supplied} ησαν δε ως δισχιλιοι και επνιγοντο εν τ[η]{.greek-supplied} [θαλασση]{.greek-supplied}[5:13]{.aside}

[οι]{.unclear} [δε]{.unclear} [β]{.unclear}οσ[κ]{.unclear}οντες τους χοιρους εφυγον και α[ν]{.unclear}η[γγ]{.unclear}ειλα[ν]{.greek-supplied} [εις]{.greek-supplied} [την]{.greek-supplied} πολιν και εις τους αγρους [και]{.greek-supplied} [εξηλθον]{.greek-omitted} [[ηλθον]{.greek-supplied}]{.greek-added} [ιδειν]{.greek-supplied} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} [και]{.greek-supplied} [θεωρουσιν]{.greek-supplied} τον δαιμονιζομενον καθημενον [και]{.greek-omitted} ιματισμενον [και]{.greek-supplied} [σωφρονουντα]{.greek-supplied} [τον]{.greek-supplied} [εσ]{.greek-supplied}χηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[[και]{.greek-supplied}]{.greek-added} [διηγησαντο]{.greek-supplied} [δε]{.greek-omitted} [αυτοι]{.greek-supplied}ς οι ιδοντες πως εγενετο τω δαιμον[ι]{.unclear}[ζομενω]{.greek-supplied} [και]{.greek-supplied} [περι]{.greek-supplied} [των]{.greek-supplied} χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον [απ]{.unclear}[ελθειν]{.greek-supplied} [απο]{.greek-supplied} [των]{.greek-supplied} οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το π[λοιον]{.unclear} παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτ[ον]{.unclear} αλλα λεγει αυτ[ω]{.unclear} υπαγε εις τον οικον σου προς τους σ[ο]{.unclear}[υς]{.greek-supplied} και αναγγειλ[ον]{.unclear} [αυτοις]{.greek-omitted} [αυτους]{.greek-added} οσα [σοι]{.greek-omitted} ο [κυριος]{.greek-abbr} [σοι]{.greek-added} πεποιηκεν και ηλεησεν σε[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των [αρχισυναγωγων]{.greek-omitted} [αρχησυναγωγων]{.greek-added} ονοματι ιαειρο[ς]{.unclear} και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και [παρεκαλει]{.greek-omitted} [πα[ρα]{.greek-supplied}κα[λει]{.greek-supplied}]{.greek-added} [αυ]{.greek-supplied}τον πολλα λεγων οτι το θυγατριον μου εσχατως [εχει]{.greek-supplied} [ινα]{.greek-supplied} [ελ]{.greek-supplied}θων επιθης αυτη τας χειρας οπως σωθη κ[αι]{.unclear} [ζ]{.unclear}ησεται[5:23]{.aside}

και απηλθεν μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη τις ουσα εν [ρυσει]{.greek-omitted} [ρυση]{.greek-added} αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

ελεγεν γαρ οτι [καν]{.greek-omitted} [εαν]{.greek-added} των ιματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και ελε[γ]{.unclear}ον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} επ αυτη ηλθεν και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη [θυγατερ]{.greek-omitted} [θυγατηρ]{.greek-added} η πιστις σου σεσωκεν σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου απεθανεν τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

[ο]{.unclear} [δε]{.unclear} [ιησους]{.greek-abbr} [ακουσας]{.greek-added} ευθεως [ακουσας]{.greek-omitted} τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα [συνακολουθησαι]{.greek-added} αυτω [συνακολουθησαι]{.greek-omitted} ει μη πετρον και ιακωβον και [ιωαννην]{.greek-abbr} τον αδελφον [του]{.greek-added} ιακωβου[5:37]{.aside}

[και]{.unclear} ερχεται εις [τον]{.greek-omitted} [οικον]{.greek-omitted} [την]{.greek-added} [οικιαν]{.greek-added} του αρχισυναγωγου και θεωρει θορυ[βον]{.unclear} κ[λ]{.unclear}αιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει [αυτοις]{.greek-omitted} [αυτω]{.greek-added} τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων [αυτου]{.greek-omitted} ο δε [εκβαλων]{.greek-omitted} [εκβαλλων]{.greek-added} παντας παραλαμβανει τον [πατερα]{.greek-abbr} [του]{.greek-omitted} [της]{.greek-added} [παιδιου]{.greek-omitted} [παιδος]{.greek-added} και την [μητερα]{.greek-abbr} και τους μετ αυτου και [εισ]{.unclear}πορευεται οπου ην το παιδιον [ανακειμενον]{.greek-omitted} [κατακειμενον]{.greek-added}[5:40]{.aside}

και κρατησ[ας]{.unclear} [της]{.greek-supplied} [χει]{.greek-supplied}ρος του παιδιου [λεγει]{.greek-supplied} [αυτη]{.greek-supplied} ταλιθα κουμι ο εστιν μεθερμηνευομ[ενον]{.greek-supplied} [το]{.greek-supplied} κορ[α]{.unclear}σιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περ[ι]{.unclear}επατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η [δοθεισα]{.greek-added} σοφια [η]{.greek-omitted} [δοθεισα]{.greek-omitted} αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο τεκτων ο υιος [της]{.greek-added} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

ελεγεν δε αυτοις ο [ιησους]{.greek-abbr} [οτι]{.greek-omitted} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης [α]{.unclear}τιμος [ει]{.greek-supplied} [μη]{.greek-supplied} εν τη [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγε[νε]{.unclear}[υσιν]{.greek-supplied}]{.greek-added} [[αυτου]{.greek-supplied}]{.greek-added} [και]{.greek-supplied} [εν]{.greek-supplied} [τη]{.greek-supplied} [οικια]{.greek-supplied} αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας εθεραπευσεν[6:5]{.aside}

και εθαυμαζεν δια την απιστιαν αυτων και περιηγεν τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον [μονον]{.greek-omitted} [μονην]{.greek-added} [μη]{.greek-omitted} [και]{.greek-added} πηραν μη αρτον μη εις [την]{.greek-supplied} [ζ]{.unclear}ωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} [υποδεδεμενους]{.greek-omitted} [υποδεδεμενος]{.greek-added} σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσησθαι]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και [οσοι]{.greek-omitted} [οπου]{.greek-added} [αν]{.greek-omitted} [εαν]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων [εκπορευομενοι]{.greek-omitted} [εκπορευομενος]{.greek-added} εκειθεν [εκτιναξατε]{.greek-omitted} [εκτειναξαντες]{.greek-added} τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερο[ν]{.unclear} εσται [σοδομοις]{.greek-omitted} [σο]{.greek-added} [[γη]{.corr}]{.greek-added} [σοδομων]{.greek-added} η [γομορροις]{.greek-omitted} [γομορας]{.greek-added} εν ημερα κρισεως [η]{.greek-omitted} [[ε]{.unclear}ν]{.greek-added} τη πολει εκεινη[6:11]{.aside}

κ[αι]{.greek-supplied} εξ[ελθον]{.greek-supplied}τες [εκ]{.unclear}ηρυσσον ινα μετανοησωσιν[6:12]{.aside}

και δαι[μονια]{.greek-supplied} πολλα [εξεβαλλον]{.greek-omitted} [[εξε]{.unclear}βαλλωσι]{.greek-added} και [ηλειφον]{.greek-omitted} [ηληφον]{.greek-added} ελαιω πολλους αρ[ρωσ]{.unclear}τους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν [οτι]{.greek-omitted} [ιωαννης]{.greek-abbr} ο [βαπτιζων]{.greek-omitted} [βαπτιστης]{.greek-added} εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω απεκεφαλισα [ιωαννην]{.greek-abbr} ουτος εστι[ν]{.unclear} [α]{.unclear}υτος ηγερθη εκ νεκρων[6:16]{.aside}

α[υ]{.unclear}τος γαρ [ο]{.greek-omitted} ηρωδης αποστειλας εκρατησεν τον [ιωαννην]{.greek-abbr} και εδησεν αυτον εν [φυλακη]{.greek-omitted} [φυλακι]{.greek-added} δια ηρωδιαδα [την]{.greek-omitted} γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [ο]{.greek-omitted} ιωαννης τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα [και]{.greek-added} [φιλιππου]{.greek-added} του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον ιωαννην ει[δως]{.unclear} αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης [και]{.greek-omitted} αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμωσεν]{.greek-added} αυτη [οτι]{.greek-omitted} ο [τι]{.greek-added} εαν με [αιτησης]{.greek-omitted} [αιτησεις]{.greek-added} δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι [αιτησομαι]{.greek-omitted} [αιτησωμαι]{.greek-added} η δε ειπεν την κεφαλην [ιωαννου]{.greek-abbr} του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-abbr} του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους [συνανακειμενους]{.greek-omitted} [ανακειμενους]{.greek-added} ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν [ενεχθηναι]{.greek-omitted} [εναχθηναι]{.greek-added} την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλαξη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυσασθε]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added}[6:31]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξε[λ]{.unclear}θων ειδεν ο [ιησους]{.greek-abbr} [οχλον]{.greek-added} πολυν [οχλον]{.greek-omitted} και εσπλαγχνισθη επ [αυτοις]{.greek-omitted} [αυταις]{.greek-added} [οτι]{.greek-supplied} [ησαν]{.greek-supplied} ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν [αυτου]{.greek-supplied}ς πολλα[6:34]{.aside}

και ηδη [πολλων]{.greek-added} [λεγομενων]{.greek-added} [ωρας]{.greek-omitted} [πολλης]{.greek-omitted} [γενομενης]{.greek-omitted} προσελθοντες αυτω οι μαθ[η]{.unclear}ται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη [ωρα]{.greek-supplied} [πο]{.unclear}λλη[6:35]{.aside}

απολυσ[ον]{.unclear} [αυ]{.unclear}τους ινα απελθοντες εις [τους]{.greek-omitted} [τας]{.greek-added} [κ[ω]{.unclear}μας]{.greek-added} [[και]{.unclear}]{.greek-added} [αγρους]{.greek-added} κυκλω αγρους [και]{.greek-omitted} [κωμας]{.greek-omitted} αγορασωσιν εαυ[τοις]{.unclear} αρτους τι γαρ φα[γωσιν]{.greek-supplied} [ου]{.greek-supplied}κ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν [α]{.unclear}υτοις δοτε αυτοι[ς]{.unclear} [υ]{.unclear}μ[εις]{.unclear} φαγειν και [λε]{.unclear}γουσιν αυτω [απ]{.unclear}ελθοντ[ες]{.unclear} αγορασωμεν [διακοσιων]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} αρτους και δωμεν αυτο[ις]{.unclear} φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγε[τε]{.unclear} και ιδετε [και]{.unclear} [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακληθηναι]{.greek-added} παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασι[α]{.unclear}ι πρασιαι ανα [εκατον]{.greek-omitted} [[ρ]{.greek-abbr}]{.greek-added} και [ανα]{.greek-omitted} πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και [τους]{.greek-omitted} δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ηυλογησε]{.greek-added} και κατεκλασεν τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [το]{.greek-added} [περισευων]{.greek-added} [των]{.greek-added} κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως ηναγκασεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βισθαιδαν]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν [εις]{.greek-omitted} [προς]{.greek-added} το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

[και]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [περιπατουντα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} και [προσωρμισθησαν]{.greek-omitted} [προσορμισθη]{.greek-added}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον[6:54]{.aside}

[περιδραμοντες]{.greek-omitted} [παραδραμοντες]{.greek-added} ολην την περιχωρον εκεινην [και]{.greek-added} ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εσται]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας [η]{.greek-omitted} [και]{.greek-added} πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη [νιψωνται]{.greek-omitted} [νιψωσι]{.greek-added} τας χειρας ουκ εσθιουσιν κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και [απο]{.greek-omitted} [απ]{.greek-added} αγορας εαν μη [βαπτισωνται]{.greek-omitted} [βαπτισονται]{.greek-added} ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν α παρελαβον κρατειν [βαπτισμους]{.greek-omitted} [βαπτισμον]{.greek-added} ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και [οι]{.greek-omitted} γραμματεις δια τι οι μαθηται σου ου περιπατουσιν κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των π[ρεσ]{.unclear}βυτερων αλλα ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} τον αρτον [αισθιουσιν]{.greek-added}[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων τ[ων]{.unclear} [υπο]{.unclear}κριτων ως γεγραπται ουτος ο λαος τοις χειλεσιν με τιμα [η]{.unclear} [δε]{.unclear} καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται μ[ε]{.unclear} διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα [πολλα]{.greek-added} παρομοια [τοιαυτα]{.greek-omitted} [πολλα]{.greek-omitted} ποιειτε[7:8]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων τηρησητε[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ ει[πεν]{.greek-supplied} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο εστιν δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι [αφιετε]{.greek-omitted} [αφιεται]{.greek-added} αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωσει]{.greek-added} υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συν[ι]{.unclear}ετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον [κοινωσαι]{.greek-omitted} [κοινησαι]{.greek-added} αλλα τα εκπορευομενα απ αυτου εκεινα εστιν τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το [εισπορευομενον]{.greek-added} εξωθεν [εισπορευομενον]{.greek-omitted} εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} [δε]{.greek-omitted} [γαρ]{.greek-added} οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοι[νο]{.greek-supplied}ι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} [οι]{.greek-omitted} διαλογισμοι οι κακοι [εκ]{.unclear}πορευονται μοιχειαι πορνειαι φονοι [[κλοπ]{.unclear}αι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} [πλ]{.unclear}εονεξιαι [πον]{.greek-supplied}ηρ[ι]{.unclear}αι δολος ασελγεια οφθαλμος πο[νηρος]{.greek-supplied} [βλασφημια]{.greek-omitted} [[β]{.unclear}λ[ασ]{.unclear}φημεια]{.greek-added} [υ]{.unclear}περηφανια αφροσυνη[7:22]{.aside}

παντα [ταυ]{.unclear}τα τα πονηρα [εσωθεν]{.greek-supplied} [ε]{.unclear}κπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα [γαρ]{.greek-omitted} γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα προσεπεσεν προς τους ποδας αυτου[7:25]{.aside}

ην [δε]{.unclear} η γυνη ελληνι[ς]{.greek-supplied} [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και [ηρωτα]{.greek-omitted} [ηρωτησεν]{.greek-added} αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλει]{.greek-added} εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτω [ν]{.unclear}αι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε [δια]{.greek-added} [τουτον]{.greek-added} [τον]{.greek-added} [λογον]{.greek-added} εξ[ε]{.unclear}ληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα [βεβλημενην]{.greek-omitted} [βεβλημενον]{.greek-added} επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος ηλθεν προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} εστεναξεν και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου και ελαλει ορθως[7:35]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστιλατο]{.greek-added} αυτοις ινα μηδενι ειπωσιν οσον δε [αυτος]{.greek-omitted} αυτοις [διεστελλετο]{.greek-omitted} [διεστ[ι]{.unclear}λατο]{.greek-added} μαλλον περισσοτερον [εκηρυσσον]{.greek-omitted} [εκηρυττον]{.greek-added}[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παλιν]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου [οντος]{.greek-omitted} [οντως]{.greek-added} και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος ο [ιησους]{.greek-abbr} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} τρεις [ημερας]{.greek-added} προσμενουσιν μοι και ουκ [εχουσιν]{.greek-omitted} [εχωσι]{.greek-added} τι φαγωσιν[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις [τον]{.greek-added} οικον αυτων [ε]{.greek-added} [εκλυθησονται]{.greek-omitted} [κλυθησονται]{.greek-added} εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκ[α]{.unclear}σι]{.greek-added}[8:3]{.aside}

και απεκριθησαν [αυτω]{.greek-omitted} οι μαθηται αυτου ποθεν τουτους δυ[ν]{.unclear}ησεται τις [ωδε]{.corr} [επ]{.greek-added} [ερημο[ν]{.unclear}]{.greek-added} χορτασαι αρτων [επ]{.greek-omitted} [ερημιας]{.greek-omitted}[8:4]{.aside}

και επηρωτα αυτους ποσους [αρτους]{.greek-added} εχετε [αρτους]{.greek-omitted} οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγκειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους [και]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} [κ]{.unclear}αι αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισ[σ]{.unclear}ευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και ευθεως εμβας εις [το]{.greek-omitted} πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη [δαλμανουθα]{.greek-omitted} [σαλμανουθα]{.greek-added}[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν αυτω ζητουντες [αυτω]{.greek-added} [παρ]{.greek-omitted} [αυτου]{.greek-omitted} [σημειον]{.greek-omitted} [σημεια]{.greek-added} απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθ[ε]{.unclear}ν εις το περαν[8:13]{.aside}

και [επελαθοντο]{.greek-omitted} [επελθοντες]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} [αυτου]{.greek-added} λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και [διεστελλετο]{.greek-omitted} [διεστελετο]{.greek-added} αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης [ηρωδου]{.greek-omitted} [των]{.greek-added} [ηρωδιανων]{.greek-added}[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες [οτι]{.greek-omitted} αρτους ουκ [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added}[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε [αλλ]{.greek-added} ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε [και]{.greek-omitted} ου μνημονευετε[8:18]{.aside}

[οτε]{.greek-omitted} [οτι]{.greek-added} τους πεντε αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους [κλασματων]{.greek-added} πληρεις [κλασματων]{.greek-omitted} ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε [και]{.greek-added} τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} επτα[8:20]{.aside}

και ελεγεν αυτοις πως ου συνιετε[8:21]{.aside}

και ερχεται εις βηθσαιδαν και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα [αυτον]{.greek-omitted} [αυτω]{.greek-added} ει τι [βλεπει]{.greek-omitted} [βλεπεις]{.greek-added}[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} [οτι]{.greek-omitted} ως δενδρα [ορω]{.greek-omitted} περιπατουντας[8:24]{.aside}

ειτα παλιν επεθηκεν τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τηλαυγως [απαντας]{.greek-omitted} [απαντα]{.greek-added}[8:25]{.aside}

και απεστειλεν [αυτον]{.greek-omitted} εις τον οικον αυτου λεγων [μηδε]{.greek-omitted} [μηδεν]{.greek-added} εις την κωμην εισελθης μη[δε]{.unclear} ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε [ο]{.greek-omitted} πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι λεγωσιν περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και [των]{.greek-omitted} [αρχιερεων]{.greek-omitted} [αρχηερεων]{.greek-added} και [των]{.greek-omitted} γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τ[ον]{.greek-supplied} [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34]{.aside}

ος [γαρ]{.greek-omitted} [δ]{.greek-added} αν [θελη]{.greek-omitted} [θελει]{.greek-added} την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την εαυτου ψυχην [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} εμου και του ευα[γγελ]{.unclear}ιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} εαν κερδηση τον κοσμον ολον και [ζημιωθη]{.greek-omitted} [ζημιωθηναι]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι [[γαρ]{.greek-supplied}]{.greek-added} [δω]{.greek-supplied}σει [ανθρωπος]{.greek-abbr} [ανταλλαγμα]{.greek-omitted} [ανταλαγμα]{.greek-added} της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι εισιν τινες των ωδε εστηκοτων [οιτινες]{.greek-omitted} [οι]{.greek-added} ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} [στιλβοντα]{.greek-omitted} λευκα λιαν [ως]{.greek-omitted} [ωσει]{.greek-added} χιων οια γναφευς επι της γης ου δυναται λευκα[ναι]{.unclear}[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυσ[ει]{.greek-supplied}]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησ[ω]{.greek-supplied}μεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυσει]{.greek-added} μιαν και ηλια μια[ν]{.greek-supplied}[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφε[λη]{.greek-supplied} επισκιαζουσα αυτοις και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπι[να]{.greek-supplied} περιβλεψαμεν[οι]{.unclear} ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ [ε]{.unclear}αυτων[9:8]{.aside}

[και]{.greek-added} καταβαινοντων [δε]{.greek-omitted} αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι διηγησωνται α ειδον ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον [αποκαθιστα]{.greek-omitted} [αποκαθιστανει]{.greek-added} παντα και πως γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και [εξουδε[νη]{.unclear}θ[η]{.unclear}]{.greek-added} [επι]{.greek-added} [τ[ον]{.unclear}]{.greek-added} [υιον]{.greek-added} [του]{.greek-added} [[ανθρωπου]{.greek-abbr}]{.greek-added} [ινα]{.greek-added} [πολλα]{.greek-added} [παθη]{.greek-added} [και]{.greek-added} εξουδενωθη[9:12]{.aside}

[αλ[λ]{.unclear}α]{.greek-added} [λ[ε]{.unclear}γω]{.greek-added} [υμιν]{.greek-added} [οτι]{.greek-added} [και]{.greek-added} [ηλιας]{.greek-added} [εληλυθεν]{.greek-added} [και]{.greek-added} [εποιησαν]{.greek-added} [αυτω]{.greek-added} [οσα]{.greek-added} [ηθελησαν]{.greek-added} [καθως]{.greek-added} [γεγραπται]{.greek-added} αλλα λεγω υμιν οτι και ηλιας εληλυθεν και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ειδον]{.greek-added} οχλον πολυν περι αυτους και γραμματεις [συζ[η]{.unclear}]{.greek-added} [συζητουντας]{.greek-omitted} [τουντας]{.greek-added} αυτοις[9:14]{.aside}

και ευθεως [π]{.unclear}ας ο οχλος ιδων αυτον εξεθ[α]{.unclear}μβ[η]{.unclear}θη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και επηρωτ[ησεν]{.greek-supplied} τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} διδασκαλε ηνεγκα τον υιον μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν [αυτον]{.greek-omitted} καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα [αυτο]{.greek-omitted} [εκβαλωσιν]{.greek-omitted} [εκβαλλωσιν]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} [εσπαραξεν]{.greek-omitted} [εσπαραξαν]{.greek-added} αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτα]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε ειπεν παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις το πυρ εβαλεν και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημ[ας]{.greek-supplied}[[9:22 *(lacunose)*]{.lacunose}]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα [τω]{.greek-omitted} [το]{.greek-added} πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του [παιδιου]{.greek-omitted} [παιδος]{.greek-added} μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [συντρεχει]{.greek-added} [ο]{.greek-added} οχλος επετιμησεν τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και [κραξαν]{.greek-omitted} [κραξας]{.greek-added} και πολλα [σπαραξαν]{.greek-omitted} [σπαραξας]{.greek-added} αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος [[αυτου]{.unclear}]{.greek-added} [η]{.unclear}γειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα [αυτον]{.greek-omitted} [αυτου]{.greek-added} εις [τον]{.greek-added} οικον οι μαθηται αυτου [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον κατ ιδιαν οτι [δια]{.greek-added} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και [εκειθεν]{.greek-omitted} εξελθοντες παρεπορευοντο δια της [γαλιλαιας]{.greek-omitted} [γαλη[λαι]{.unclear}ας]{.greek-added} και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη [ημερα]{.greek-omitted} [ημερας]{.greek-added} αναστησεται[9:31]{.aside}

ο[ι]{.unclear} δε ηγνο[ουν]{.greek-supplied} το ρημα και εφοβουν[το]{.greek-supplied} [επερωτησαι]{.greek-added} αυτον [επερωτησαι]{.greek-omitted}[9:32]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} εις [καπερναουμ]{.greek-omitted} [καφαρναουμ]{.greek-added} και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους [διελογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added}[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ [διελεχθησαν]{.greek-omitted} [διηλεχθησαν]{.greek-added} εν τη οδω τις μειζων[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} εφωνησεν τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν [α]{.unclear}υτο [ε]{.unclear}ν μεσω αυτων και [εναγκαλισαμενος]{.greek-omitted} [ε[ν]{.unclear}αγγαλισαμενος]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added} ειπεν αυτοις[9:36]{.aside}

ος εαν [εν]{.greek-omitted} [εκ]{.greek-added} των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε αυτω [ο]{.greek-added} [ιωαννης]{.greek-abbr} λεγων διδασκαλε ειδομεν τινα [εν]{.greek-added} τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και εκωλυσαμεν αυτον οτι ουκ [ακολουθει]{.greek-omitted} [ηκολουθει]{.greek-added} ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ εστιν καθ [υμων]{.greek-omitted} [ημων]{.greek-added} υπερ [υμων]{.greek-omitted} [ημων]{.greek-added} εστιν[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} σκανδαλιση ενα των μικρων των πιστευοντων εις εμε [καλον]{.greek-omitted} [καλλον]{.greek-added} εστιν [αυτω]{.greek-omitted} μαλλον ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιση]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν [εις]{.greek-omitted} [το]{.greek-omitted} [του]{.greek-added} [πυρ]{.greek-omitted} [πυρος]{.greek-added} [το]{.greek-omitted} [ασβεστον]{.greek-omitted}[9:43]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκοληξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

[και]{.greek-added} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} αναστας ερχεται εις τα ορια της ιουδαιας [δια]{.greek-omitted} [εις]{.greek-added} [του]{.greek-omitted} [το]{.greek-added} περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες [οι]{.greek-added} φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} επετρεψεν βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν [υμιν]{.greek-omitted} την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν [τουτου]{.greek-omitted} [τουτο]{.greek-added} [καταλειψει]{.greek-omitted} [καταληψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-omitted} και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε [ουκετι]{.greek-omitted} [ουκ]{.greek-added} εισιν δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [οικια]{.greek-omitted} [οικιαν]{.greek-added} παλιν οι μαθηται αυτου περι [τουτου]{.greek-added} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [ηρωτησαν]{.greek-added} αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν [απολυση]{.greek-omitted} [απολυσας]{.greek-added} την γυναικα αυτου και [γαμηση]{.greek-omitted} [γαμησας]{.greek-added} αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον ανδρα αυτης και γαμηθη [αλλω]{.greek-omitted} [αλλον]{.greek-added} μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμ[ω]{.unclear}ν τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} ηγανακτησεν και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηυλογησεν]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις και γονυπετησας αυτον [επηρωτα]{.greek-omitted} [επηρωτησ[εν]{.unclear}]{.greek-added} αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω [ινα]{.greek-added} [ζωην]{.greek-added} [αιωνιον]{.greek-added} [κλη]{.greek-added} [ρονομησω]{.greek-added}[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδ[εις]{.unclear} αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη [κλεψης]{.greek-omitted} [μη]{.greek-omitted} ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω εν [σοι]{.greek-omitted} [σ[ε]{.unclear}]{.greek-added} υστερει υπαγε οσα εχεις πωλησον και δος [τοις]{.greek-added} πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} [εισελευσονται]{.greek-omitted} [εισελθειν]{.greek-added}[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον εστιν τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δ[υνα]{.unclear}ται σωθηναι[10:26]{.aside}

εμβλεψας δε [αυτοις]{.greek-omitted} ο [ιησους]{.greek-abbr} λεγει [αυτοις]{.greek-added} παρα [ανθρωποις]{.greek-abbr} [τουτο]{.greek-added} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [αμην]{.greek-added} αμην λεγω υμιν ουδεις εστιν ος αφηκεν [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} η [αδελφην]{.greek-added} [αδελφους]{.greek-omitted} [η]{.greek-omitted} [αδελφας]{.greek-omitted} η [πατερα]{.greek-abbr} [η]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω [τουτω]{.greek-omitted} [τουτο]{.greek-added} οικιας και αδελφους και αδελφας και [μητερας]{.greek-omitted} [γυναικας]{.greek-added} και τεκνα [και]{.greek-added} [[μητερας]{.greek-abbr}]{.greek-added} και αγρους μετα διωγμων και εν τω αιωνι τω [ερχομενω]{.greek-omitted} [επερχομενω]{.greek-added} ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται [οι]{.greek-added} πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [λεγειν]{.greek-added} αυτοις [λεγειν]{.greek-omitted} τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} [παραδοθησεται]{.greek-omitted} [παραδιδοται]{.greek-added} τοις αρχιερευσιν και γραμματευσιν και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33]{.aside}

και εμπαιξουσιν [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} αυτον [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} και αποκτενουσιν αυτον και τη τριτ[η]{.greek-supplied} [ημερα]{.greek-omitted} [ημερας]{.greek-added} αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος [και]{.unclear} ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε [θελομεν]{.greek-omitted} [θελωμεν]{.greek-added} [ινα]{.greek-omitted} ο εαν αιτησωμεν [σε]{.greek-added} [ποιησης]{.greek-omitted} [ποιησεις]{.greek-added} ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι [αιτεισθε]{.greek-omitted} [αιτεισθαι]{.greek-added} δυνασθε [πιειν]{.greek-omitted} [ποιειν]{.greek-added} το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω [πιεσθε]{.greek-omitted} [πιεσθαι]{.greek-added} και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added}[10:39]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και [εξ]{.greek-omitted} [ε]{.greek-added} [ξ]{.greek-added} ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει [αυτοις]{.greek-omitted} [αυτους]{.greek-added} οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[10:43]{.aside}

και ος εαν θελη [γενεσθαι]{.greek-added} υμων [γενεσθαι]{.greek-omitted} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και [ερχονται]{.greek-omitted} [ερχετε]{.greek-added} εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [[ο]{.unclear}]{.greek-added} υιος τιμαιου βαρτιμαιος [ο]{.greek-omitted} τυφλος εκαθητο παρα την οδον [προσαιτων]{.greek-omitted} [προσετων]{.greek-added}[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο υιος [δαυιδ]{.greek-abbr} [ιησου]{.greek-omitted} ελεησον με[10:47]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και φωνουσιν τον τυφλον λεγοντες αυτω θαρσει εγειραι [φωνει]{.greek-omitted} [σε]{.greek-omitted} [φωνη]{.greek-added} [σαι]{.greek-added}[10:49]{.aside}

ο δε [αποβαλων]{.greek-omitted} [αποβαλλων]{.greek-added} [το]{.greek-omitted} [τα]{.greek-added} [ιματιον]{.greek-omitted} [ιματια]{.greek-added} αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι [θελεις]{.greek-omitted} [θελης]{.greek-added} ποιησω σοι ο δε τυφλος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτω]{.greek-omitted} [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η [πιστις]{.greek-omitted} [πιστης]{.greek-added} σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως ανεβλεψεν και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} εις [βηθσφαγη]{.greek-omitted} [βησφαγη]{.greek-added} και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} πωλον δεδεμενον εφ ον [[ανθρωπων]{.greek-abbr}]{.greek-added} ουδεις [ανθρωπων]{.greek-omitted} [κεκαθικεν]{.greek-omitted} [κεκαθηκε]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι ποιειτε [τουτο]{.greek-omitted} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον [δε]{.greek-omitted} και [ευρον]{.greek-omitted} [ευρων]{.greek-added} πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων [ελεγον]{.greek-omitted} [λεγουσιν]{.greek-added} αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο [ημιν]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και [η]{.unclear}γαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και [επεβαλον]{.greek-omitted} [επεβαλλον]{.greek-added} αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτων]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} εκοπτον [στιβαδας]{.greek-added} εκ των δενδρων και [εστρωννυον]{.greek-omitted} [εστρωνυον]{.greek-added} εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

[ευλογημενη]{.greek-omitted} [η]{.greek-omitted} [ερχομενη]{.greek-omitted} [βασιλεια]{.greek-omitted} [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης [της]{.greek-omitted} [ωρας]{.greek-omitted} εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο [της]{.greek-added} βηθανιας επεινασεν[11:12]{.aside}

και ιδων σ[υκ]{.unclear}ην μακροθεν εχουσαν [φυλλα]{.greek-omitted} [φυλα]{.greek-added} ηλθεν [ινα]{.greek-added} [ει]{.greek-omitted} [αρα]{.greek-omitted} ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη [φυλλα]{.greek-omitted} [φυλα]{.greek-added} [μονον]{.greek-added} ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου [καρπος]{.greek-added} [γενηται]{.greek-added} εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και [ερχονται]{.greek-omitted} [ερχεται]{.greek-added} εις ιεροσολυμα και [εισελθων]{.greek-omitted} [ελθων]{.greek-added} ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των κολ[λυ]{.unclear}βιστων και τας καθεδρας των πωλουντων τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [περι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμ]{.greek-added} [γραμματεις]{.greek-omitted} [ματεις]{.greek-added} και οι αρχιερεις και εζητουν πως [απολεσωσιν]{.greek-added} αυτον [απολεσωσιν]{.greek-omitted} εφοβουντο γαρ αυτον οτι πας [γαρ]{.greek-added} ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και οτε [εγενετο]{.greek-added} οψε [εγενετο]{.greek-omitted} εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηρατε]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι [ος]{.greek-omitted} [ως]{.greek-added} αν ειπη τω ορει [τουτω]{.greek-omitted} [τουτο]{.greek-added} αρθητι και βληθητι εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν [αιτεισθαι]{.greek-added} προσευχομενοι [αιτησθε]{.greek-omitted} πιστευετε οτι [λαμβανετε]{.greek-omitted} [λαμβανεται]{.greek-added} και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκηται]{.greek-added} προσευχομενοι αφιετε [ει]{.greek-omitted} [τι]{.greek-omitted} [οτι]{.greek-added} εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ο εν τοις [ουρανοις]{.greek-abbr} [αφησει]{.greek-added} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} τα παραπτωματα υμων[11:25]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι [αρχιερεις]{.greek-omitted} [αρχη[ε]{.unclear}ρεις]{.greek-added} και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια [ταυτα]{.greek-omitted} [ταυ]{.greek-added} [τα]{.greek-added} ποιεις και [τις]{.greek-omitted} [τι]{.greek-added} σοι [εδωκεν]{.greek-added} την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω [καγω]{.greek-added} υμας [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-abbr} εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} [αποκριθητε]{.greek-omitted} [μοι]{.greek-omitted}[11:30]{.aside}

κ[αι]{.greek-supplied} [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν [ειπωμεν]{.greek-omitted} [ειπομεν]{.greek-added} εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} [ειπωμεν]{.greek-omitted} [ειπομεν]{.greek-added} εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον [λαον]{.greek-omitted} [οχλον]{.greek-added} [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ ειχον τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες λεγουσιν τω [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και περιεθηκεν φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκωδομησε]{.greek-added} πυργον και [εξεδοτο]{.greek-omitted} [εξεδετο]{.greek-added} αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και απεστειλεν προς τους γεωργους τω καιρω δουλον ινα [παρα]{.greek-omitted} [απο]{.greek-added} των γεωργων λαβη απο το[υ]{.unclear} καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν [αυτον]{.greek-added} και απεστειλαν κενον[12:3]{.aside}

και παλιν απεστειλεν προς αυτους αλλον δουλον κακεινον λιθοβολησαντες [εκεφαλαιωσαν]{.greek-omitted} [εκεφαλεωσαν]{.greek-added} και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απε[στ]{.unclear}]{.greek-added} [ειλεν]{.greek-added} κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε [αποκτενοντες]{.greek-omitted} [αποκταινοντες]{.greek-added}[12:5]{.aside}

ετι ουν ενα υιον εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον προς αυτους εσχατον λεγων [οτι]{.greek-omitted} [εν]{.unclear}τραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους [οτι]{.greek-omitted} ουτος εστιν ο κληρονομος δευτε [αποκτεινωμεν]{.greek-omitted} [αποκτεινομεν]{.greek-added} αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γ[ω]{.unclear}νιας[12:10]{.aside}

[παρα]{.greek-omitted} [περι]{.greek-added} [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστη]{.greek-added} θαυμασ[τ]{.unclear}η εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} [λογω]{.greek-omitted} [λογον]{.greek-added}[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ [αληθειας]{.greek-omitted} [αληθεια]{.greek-added} την οδον του [θεου]{.greek-abbr} διδασκεις εξεστιν κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} φερετε μοι δηναριον ινα [ιδω]{.greek-omitted} [δω]{.greek-added}[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και [αποκριθεις]{.greek-omitted} [αποκρηθεις]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε [ουν]{.greek-added} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται [σαδδουκαιοι]{.greek-omitted} προς αυτον [οι]{.greek-added} [σαδδουκαιοι]{.greek-added} οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθ[α]{.unclear}νη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [ουν]{.greek-added} αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε [α]{.unclear}υτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθαν[ε]{.unclear}]{.greek-added} και η γυνη[12:22]{.aside}

εν τη αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος [αυτων]{.greek-omitted} εσται [η]{.greek-added} γυνη οι γαρ επτα εσχον αυτην [γυναικα]{.greek-omitted}[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [ου]{.greek-omitted} δια τουτο πλανασθε μη ειδοτες τας γραφας μη[δε]{.unclear} την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ [εκ]{.greek-omitted} [εκκ]{.greek-added} νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [εκγαμιζονται]{.greek-added} αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω μωσεως [επι]{.greek-omitted} [απο]{.greek-added} του βατο[υ]{.unclear} [ως]{.greek-omitted} [[π]{.unclear}ως]{.greek-added} ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και [ο]{.greek-omitted} [θεος]{.greek-omitted} ισαακ και [ο]{.greek-omitted} [θεος]{.greek-omitted} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-abbr} [ζωντων]{.greek-omitted} [ζοντων]{.greek-added} υμεις ουν [πολυ]{.greek-omitted} πλανασθε[12:27]{.aside}

και προσελθων [παλιν]{.greek-added} εις των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ακουσας [αυτων]{.greek-omitted} [αυτον]{.greek-added} συζητουντων ειδως οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} [πρωτη]{.greek-omitted} παντων εντολη [μειζων]{.greek-added}[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} [απεκριθη]{.greek-omitted} [ειπεν]{.greek-added} αυτω οτι πρωτη παντων των εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-omitted} [[θεος]{.greek-abbr}]{.greek-added} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και [αγαπησεις]{.greek-omitted} [αγαπηση[ς]{.unclear}]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια αυτη [αγαπησεις]{.greek-omitted} [αγαπησης]{.greek-added} τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων [εντολη]{.greek-added} αλλη [εντολη]{.greek-omitted} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας [σου]{.greek-added} [και]{.unclear} εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως [εαυτον]{.greek-omitted} [σεαυτον]{.greek-added} πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των [ολοκαυτωματων]{.greek-omitted} [ολοκαυτοματων]{.greek-added} και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων [αυτον]{.greek-omitted} οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου [εκ]{.greek-supplied} δεξ[ι]{.greek-supplied}ων [μου]{.greek-supplied} ε[ως]{.unclear} αν θω [τους]{.unclear} [εχθρους]{.unclear} [σου]{.unclear} υποπ[οδιον]{.unclear} [των]{.unclear} ποδων σου[12:36]{.aside}

αυ[τος]{.unclear} [ουν]{.unclear} [δαυιδ]{.greek-supplied} [λεγει]{.greek-supplied} αυτον [κυριον]{.greek-abbr} και ποθεν υιος αυτου εστιν και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε α[πο]{.unclear} [τ]{.unclear}ων [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} των θελο[ν]{.unclear}των εν στολαις περιπατειν [και]{.unclear} [ασπ]{.unclear}ασμ[ους]{.unclear} εν ταις αγοραις[12:38]{.aside}

και [πρωτοκαθεδριας]{.greek-omitted} [πρωτοκαθεδρας]{.greek-added} εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας ο[ικ]{.unclear}ι[ας]{.unclear} των χηρων και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον [κριμα]{.greek-omitted} [κρι[μ]{.unclear}μα]{.greek-added}[12:40]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} ο [ιησους]{.greek-abbr} κατ[ε]{.unclear}να[ν]{.unclear}τι του γαζοφυλακιου [εθεωρει]{.greek-omitted} [εθεορει]{.greek-added} πως ο οχλος βαλλει χαλ[κ]{.unclear}ον εις το γαζοφυλακιον και πολλοι π[λου]{.greek-supplied}σιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα [χηρα]{.greek-added} μια [χηρα]{.greek-omitted} πτωχη [εβαλεν]{.greek-omitted} [εβαλλ[εν]{.greek-supplied}]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [κοδραντης]{.greek-omitted} [κοδραντ[α]{.unclear}]{.greek-added}[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας [αυτου]{.greek-omitted} λεγει [αυτοις]{.greek-omitted} [αυτους]{.greek-added} αμην λεγω υμιν οτι η χηρα αυτη η πτωχη π[λει]{.greek-supplied}ον [παντων]{.greek-omitted} [απαντων]{.greek-added} [[ε]{.greek-supplied}βαλε]{.greek-added} [βεβληκεν]{.greek-omitted} [[βεβληκε]{.corr}]{.greek-added} των βαλλοντων εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ [ε]{.unclear}[κ]{.greek-supplied} του περισσευ[ον]{.unclear}τος αυτοις [εβαλον]{.greek-omitted} [εβαλλον]{.greek-added} αυτη δε εκ της υστερησεως [αυτης]{.greek-omitted} π[αν]{.unclear}τα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει α[υ]{.unclear}τω εις των μ[α]{.unclear}θητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθ[ον]{.unclear}]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαι[ων]{.unclear} κατεν[αντι]{.unclear} [του]{.unclear} [ιε]{.unclear}ρ[ου]{.unclear} [επηρωτων]{.greek-omitted} [επηρωτα]{.greek-added} αυτον [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} πετρο[ς]{.unclear} και ιακωβο[ς]{.greek-supplied} και [ιωαννης]{.greek-abbr} και ανδρεας[13:3]{.aside}

[ειπε]{.greek-omitted} [ειπον]{.greek-added} ημιν ποτε ταυτα εσται και τι το [ση]{.unclear}μειον οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται [επι]{.greek-omitted} [εν]{.greek-added} τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουσηται]{.greek-added} πολεμους [και]{.greek-added} [αναστασιας]{.greek-added} και ακοας πολεμων μη [θροεισθε]{.greek-omitted} [θρο[η]{.unclear}σθαι]{.greek-added} δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους [και]{.greek-omitted} εσονται λιμοι και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους παραδωσουσιν [γαρ]{.greek-omitted} υμας εις συνεδρια και εις συναγωγας [δαρησεσθε]{.greek-omitted} [δαρησεσθαι]{.greek-added} [και]{.unclear} επι ηγεμονων και βασιλεων σταθησεσθε [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} [εμου]{.greek-omitted} [μου]{.greek-added} εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προ]{.greek-supplied}μεριμνατε τι λαλησητε μηδε μελετατε αλλ ο εαν [δοθη]{.greek-supplied} [υμιν]{.greek-supplied} [ε]{.unclear}ν εκεινη τη ωρα τουτο [λαλειτε]{.greek-omitted} [λαλ[η]{.unclear}ται]{.greek-added} ου γαρ [υμεις]{.greek-added} [εστε]{.greek-supplied} [υμεις]{.greek-omitted} [οι]{.greek-supplied} [λαλουντες]{.greek-supplied} αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε [αδελφος]{.greek-omitted} [αδ[ε]{.unclear}λ[ελφος]{.greek-supplied}]{.greek-added} [αδελφον]{.greek-supplied} [εις]{.greek-supplied} [θανατο]{.greek-supplied}ν [και]{.unclear} [πατηρ]{.greek-abbr} τεκνον και επανα[στησονται]{.unclear} τεκνα επι γονεις [και]{.unclear} [θα]{.unclear}νατωσουσιν αυτους[13:12]{.aside}

και εσεσ[θε]{.unclear} μισο[υ]{.unclear}με[ν]{.unclear}οι υπο π[α]{.unclear}[ντων]{.greek-supplied} [δι]{.greek-supplied}α το ονομα μου ο δε υπομεινας [εις]{.greek-supplied} [τελος]{.greek-supplied} [ουτος]{.greek-supplied} [σωθησεται]{.greek-supplied}[13:13]{.aside}

οταν δε ιδητε το β[δ]{.unclear}ελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητ[ου]{.unclear} εστως οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω [αραι]{.greek-omitted} [αρε]{.greek-added} τι εκ της οικιας αυτου[13:15]{.aside}

[και]{.greek-omitted} ο [δε]{.greek-added} εις τον αγρον [ω]{.unclear}ν μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζο[υ]{.unclear}σαις εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι [θλιψις]{.greek-omitted} [θλιψεις]{.greek-added} οια ου γεγονεν [τοιαυτη]{.greek-omitted} [απ]{.unclear} αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους [εκολοβωσεν]{.greek-added} ους εξελεξατο [εκολοβωσεν]{.greek-omitted} τας ημερας[13:20]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} [η]{.greek-omitted} ιδου εκει μη πιστευετε[13:21]{.aside}

εγερθησονται γαρ [ψευδοχριστοι]{.greek-omitted} [ψευδοχρηστοι]{.greek-added} και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σ[η]{.unclear}μεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες [εκ]{.greek-added} του [ουρανου]{.greek-abbr} [εκπιπτοντες]{.greek-added} εσονται [εκπιπτοντες]{.greek-omitted} και αι δυναμεις [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [αι]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και [τοτε]{.greek-omitted} αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τ[εσ]{.unclear}σαρων ανεμων απ ακρου [της]{.greek-added} γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης [ηδη]{.greek-omitted} ο κλαδος απαλος γενηται και [εκφυη]{.greek-omitted} τα φυλλα [γινωσκετε]{.greek-omitted} [εκφυη]{.greek-added} [[γι]{.unclear}νοσκεται]{.greek-added} οτι [εγγυς]{.greek-omitted} το θερος [εγγυς]{.greek-added} εστιν[13:28]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι [δε]{.unclear} της ημερας εκειν[ης]{.unclear} [η]{.unclear} [[τη]{.unclear}ς]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι οι εν [ουρανω]{.greek-abbr} ουδε [ο]{.unclear} [υιος]{.unclear} [ει]{.unclear} μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και [προσευχεσθε]{.greek-omitted} [προσευχ[εσ]{.unclear}θαι]{.greek-added} ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου [και]{.unclear} δους τ[οι]{.unclear}ς δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα γρηγορη[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} τη[ς]{.unclear} οικιας ερχεται [οψε]{.unclear} η [μεσονυκτιου]{.greek-omitted} [μεσονυκτιον]{.greek-added} η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη [εξεφ[ναις]{.unclear}]{.greek-added} [ελθων]{.greek-omitted} [εξαιφνης]{.greek-omitted} ευρη υμας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω πασιν λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας [και]{.greek-supplied} εζητουν οι αρχιερεις και οι γραμματεις πως [αυτον]{.greek-omitted} εν δολω [αυτ[ον]{.unclear}]{.greek-added} κρατησαντες αποκτεινωσιν[14:1]{.aside}

ε[λ]{.unclear}εγον δε μη εν τη εορτ[η]{.unclear} μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτο[υ]{.unclear} εν [βηθανια]{.greek-omitted} [βιθανι[α]{.greek-supplied}]{.greek-added} εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτου ηλθ[εν]{.greek-supplied} [γυνη]{.unclear} εχου[σα]{.unclear} αλα[βαστρον]{.greek-supplied} μυρου ναρδου πιστικης [πολητειμ[ου]{.unclear}]{.greek-added} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συν]{.unclear}τριψασα [το]{.greek-omitted} [την]{.greek-added} αλαβαστρον κατεχεεν αυτου κατα της κ[εφ]{.unclear}[α]{.greek-supplied}[λης]{.unclear}[14:3]{.aside}

ησαν [δ]{.unclear}ε τινες αγανακτουντες προς [ε]{.unclear}αυτους κα[ι]{.greek-supplied} [λε]{.greek-supplied}[γοντες]{.unclear} [[η]{.unclear}]{.greek-added} εις τι η [απωλεια]{.greek-omitted} [απολεια]{.greek-added} αυτη του μυρου [γ]{.unclear}εγονεν[14:4]{.aside}

ηδυν[ατο]{.unclear} γαρ τουτο πραθηναι επανω τρ[ι]{.unclear}ακοσιων δηναριων [και]{.unclear} δοθηναι τοις [πτ]{.unclear}ωχοις και ενεβριμωντο αυτη[14:5]{.aside}

και [ο]{.greek-omitted} [ιδου]{.greek-added} ιουδας [ο]{.greek-omitted} ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερει[ς]{.unclear} ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και [επηγγειλαντο]{.greek-omitted} [επηγκειλαντο]{.greek-added} αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη [ημερα]{.greek-omitted} των αζυμων [ημερα]{.greek-added} οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που [θελεις]{.greek-omitted} [θελης]{.greek-added} απελθοντες [ετοιμασωμεν]{.greek-omitted} [ετιμασωμεν]{.greek-added} ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις [υπαγετε]{.greek-omitted} [υπαγε]{.greek-added} εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλ[υ]{.unclear}μα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν [δειξει]{.greek-omitted} [δειξη]{.greek-added} [α]{.unclear}ν[ω]{.unclear}γεον [μεγα]{.greek-omitted} εστρωμενον [ετοιμον]{.greek-omitted} εκει ετοιμασατε [ημιν]{.greek-omitted} [υμιν]{.greek-added}[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις [τ]{.unclear}[ην]{.greek-supplied} πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} μετα των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[14:17]{.aside}

και ανακειμενων αυτων και εσθι[ο]{.unclear}ντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

[[και]{.unclear}]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητ[ι]{.unclear} εγω [και]{.greek-omitted} [αλλος]{.greek-omitted} [μητι]{.greek-omitted} [εγω]{.greek-omitted}[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτο[ι]{.unclear}ς εις εκ των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ο εμβαπτ[ο]{.unclear}μενος μετ εμου εις [τ[―]{.gap}ιβλιον]{.greek-added} [το]{.corr} [τρυβλιον]{.greek-omitted} [[τριβλιον]{.corr}]{.greek-added}[14:20]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκ[εινω]{.greek-supplied} δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται [καλον]{.greek-omitted} [καλλον]{.greek-added} ην αυτω ει ουκ [εγεννηθη]{.greek-omitted} [εγενη[θη]{.unclear}]{.greek-added} ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων [ο]{.greek-supplied} [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων [το]{.greek-omitted} ποτ[ηριον]{.greek-supplied} ευχαριστησας [ε]{.unclear}δωκεν αυτοις και επιον εξ αυτου παντ[ε]{.unclear}[ς]{.greek-supplied}[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το τ[ης]{.unclear} καιν[ης]{.unclear} διαθηκης το περι πολλων [εκχυνομενον]{.greek-omitted} [εκχυννομενον]{.greek-added}[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γεν[η]{.unclear}ματος της αμπελου εως της ημερας ε[κει]{.unclear}ν[ης]{.unclear} οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεσθαι]{.greek-added} εν εμοι εν τη ν[υκτι]{.unclear} ταυτη οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες [σκ]{.unclear}ανδαλισθησονται [εν]{.greek-added} [σοι]{.greek-added} αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι [συ]{.greek-omitted} σημερον εν τη νυκτι ταυτη πριν η δις [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε [εκπερισσου]{.greek-omitted} [εκπερισου]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν [δεη]{.greek-added} με [δεη]{.greek-omitted} συναποθανειν σοι ου μη σε απαρνησωμαι ωσαυτως [δε]{.greek-omitted} και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσημαν[ει]{.unclear}]{.greek-added} και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξ[ο]{.unclear}μ[ε]{.unclear}]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον [και]{.greek-supplied} ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε [ω]{.unclear}δε [μετ]{.greek-added} [εμου]{.greek-added} και [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added}[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και [προση[υχ]{.unclear}ομεν]{.greek-added} [προσηυχετο]{.corr} ινα ει δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον απ εμου τουτο αλλ ου τι εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [ε[ι]{.unclear}]{.greek-added} τι συ[14:36]{.aside}

και ερχεται και ευρισκ[ει]{.unclear} αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μι[αν]{.unclear} ωραν γρηγορησαι[14:37]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καταβαρυνομενο[ι]{.unclear}]{.greek-added} και ουκ ηδεισαν τι [αυτ[ου]{.unclear}]{.greek-added} [αυτ[ω]{.unclear}]{.corr} αποκριθωσιν[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις τ[ας]{.greek-supplied} χειρ[ας]{.unclear} των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με [ηγγικεν]{.greek-omitted} [ηγκικεν]{.greek-added}[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις ων των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων [παρα]{.greek-omitted} [περι]{.greek-added} των αρχιερεων και [των]{.greek-omitted} γραμματεων και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον [συσσημον]{.greek-omitted} [σημειον]{.greek-added} αυτοις λεγων ον αν φιλησω αυτος εστιν κρατησατε αυ[τ]{.unclear}ον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως [και]{.greek-added} προσελθων αυτω λ[εγ]{.unclear}ει αυτω ραββι [ραββι]{.greek-omitted} και κατεφιλησεν αυτον[14:45]{.aside}

[οι]{.greek-omitted} [ο]{.greek-added} δε [επεβαλον]{.greek-omitted} [επεβαλλον]{.greek-added} επ αυτον τας χειρας αυτων [και]{.unclear} εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επεσε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-added} [αυτοις]{.corr} ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν η[μ]{.unclear}[ην]{.greek-supplied} προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε [με]{.greek-omitted} [μοι]{.greek-added} αλλ ινα [π[λη]{.greek-supplied}]{.greek-added} [πληρωθωσιν]{.greek-omitted} [ρωθωσιν]{.greek-added} αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι [γυμν]{.unclear}ου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} πρ[ος]{.unclear} τον αρχιερεα και συνερχονται αυτω παντ[ες]{.greek-supplied} οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτ[ω]{.unclear} εως εσω εις την αυλην του αρχ[ι]{.unclear}ερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και [ολον]{.greek-omitted} το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι [ου]{.unclear}κ ησ[αν]{.greek-supplied}[14:56]{.aside}

και τινες [ψευδομαρτυρες]{.greek-added} ανασταντες εψευδομαρτυρουν [κ[α]{.unclear}[ι]{.greek-supplied}]{.greek-added} κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος ο[τ]{.unclear}[ι]{.greek-supplied} εγω καταλυσω τον ναον τουτον τον [χειροποιητον]{.greek-omitted} [αχειροποιητον]{.greek-added} και δια τριων η[μ]{.unclear}[ε]{.greek-supplied}ρων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν τι ουτοι σου καταμαρτυρουσ[ιν]{.unclear}[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επ[η]{.unclear}ρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο υιος του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθη[μ]{.unclear}[ενον]{.greek-supplied} της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς δ[ι]{.greek-supplied}αρρηξας τους [χιτωνας]{.greek-omitted} [χιτονας]{.greek-added} αυτου λεγει τι ετι χρειαν εχομεν μαρτ[υ]{.greek-supplied}ρων[14:63]{.aside}

ηκουσατε [της]{.greek-omitted} [την]{.greek-added} [βλασφημιας]{.greek-omitted} [βλασφημιαν]{.greek-added} [αυτου]{.greek-added} τι υμιν φαινεται οι δε παν[τ]{.unclear}[ες]{.greek-supplied} κατεκριναν αυτον ειναι [θανατου]{.greek-added} ενοχον [θανατου]{.greek-omitted}[14:64]{.aside}

και ηρξαντο τινες [εμπεζειν]{.greek-added} [και]{.greek-added} εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κ[ο]{.greek-supplied}λαφιζειν [αυτον]{.greek-omitted} [αυτω]{.greek-added} και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τι[ς]{.unclear}]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισα]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατ[ω]{.unclear} ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα [αυτω]{.greek-omitted} [αυτον]{.greek-added} λεγει και συ μετα του [ναζαρηνου]{.greek-omitted} [ναζωραιου]{.greek-added} [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα ουδε επισταμαι τι [συ]{.corr} λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις παρεστηκοσιν οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνησατο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ εφωνησεν και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι δις απαρνηση με τρις και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος [επηρωτησεν]{.greek-added} παλιν [επηρωτησεν]{.greek-omitted} αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [παρητουντο]{.greek-added}[15:6]{.aside}

ην [δε]{.greek-omitted} [ο]{.unclear} λεγομενος βαραββας μετα των συστασια[σ]{.unclear}των δεδεμενος οιτινες εν τη στασει φονον [πεποιηκεισαν]{.greek-omitted} [πεποιεικησαν]{.greek-added}[15:7]{.aside}

και αναβοησας ο οχλος [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος [α]{.greek-supplied}πεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδ[α]{.unclear}[ι]{.greek-supplied}ων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον παραδεδωκεισαν αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν [θελετε]{.greek-omitted} [θελεται]{.greek-added} ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγγελωσας]{.greek-added} ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [πραιτωριον]{.greek-omitted} [το]{.greek-added} [πρετοριον]{.greek-added} και συγκαλουσιν [ολην]{.greek-omitted} την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} πλεξαντες ακ[α]{.unclear}νθινον στεφανον[15:17]{.aside}

και ηρξαντο [αυτον]{.greek-added} ασπαζεσθαι [αυτον]{.greek-omitted} [και]{.greek-added} [λεγειν]{.greek-added} [αυτω]{.greek-added} χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον [αυτου]{.greek-omitted} την κεφαλην [αυτου]{.greek-added} καλαμω και ενεπτυον αυτω και τιθεντες τα [γονατα]{.greek-omitted} [γωνατα]{.greek-added} προσεκυνουν αυ[τ]{.unclear}ω[15:19]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την πορφυραν και ε[ν]{.unclear}εδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και αγγαρευουσιν παραγοντα τινα [σιμωνα]{.greek-omitted} [συμωνα]{.greek-added} κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα [[α]{.unclear}]{.greek-added} αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ ελαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η επιγρα[φ]{.unclear}η της αιτιας αυτου [επιγεγραμμενη]{.greek-omitted} [γεγραμμενη]{.greek-added} ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} αυτου[15:27]{.aside}

και επληρω[θη]{.greek-supplied} η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον [κινουντες]{.greek-omitted} [κοινουντες]{.greek-added} τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις [οι]{.greek-added} [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} προς αλληλους [μετα]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα [ιδωμεν]{.greek-omitted} [ιδομεν]{.greek-added} και πιστευσωμεν [αυτω]{.greek-omitted} και οι [συνεσταυρωμενοι]{.greek-omitted} [[συνεστρωμενοι]{.greek-abbr}]{.greek-added} αυτω ωνειδιζον αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης [ο]{.greek-added} σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και τη ωρα τη ενατη εβοησεν ο [ιησους]{.greek-abbr} [μεγαλη]{.greek-added} φωνη [μεγαλη]{.greek-omitted} λεγων ελωι ελωι λιμα σαβαχθανι ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με [εγκατελιπες]{.greek-omitted} [εκατελιπες]{.greek-added}[15:34]{.aside}

και [τινες]{.greek-omitted} [τοινες]{.greek-added} των παρεστηκοτων ακουσαντες ελεγον [ιδου]{.greek-omitted} [οτι]{.greek-added} ηλιαν φωνει[15:35]{.aside}

δραμων δε ει[ς]{.greek-supplied} και [γεμισας]{.greek-omitted} [γεμησας]{.greek-added} [ογγο]{.greek-added} [σπογγον]{.corr} [οξους]{.greek-omitted} [οξος]{.greek-added} περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε [ιδωμεν]{.greek-omitted} [ιδομεν]{.greek-added} ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το καταπετασμα του ναου [εσχισθη]{.greek-omitted} εις δυο [εσχισθη]{.greek-added} απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο [παρεστηκως]{.greek-omitted} [παρεστικως]{.greek-added} εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος υιος [[θεου]{.greek-abbr}]{.greek-added} ην [θεου]{.greek-omitted}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην και μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και [ηδη]{.greek-omitted} [ηδης]{.greek-added} οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} προσαββατον[15:42]{.aside}

ηλθεν ιωσηφ [ο]{.greek-omitted} απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} το[λ]{.greek-supplied}μησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς [πιλατον]{.greek-omitted} [π[ε]{.unclear}ιλατον]{.greek-added} και [ητησατο]{.greek-omitted} [ητοισατο]{.greek-added} το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο [το]{.greek-omitted} [τω]{.greek-added} σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλησε]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην [λε]{.unclear}λατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκηλυσε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-added} ιωση [εθεωρουν]{.greek-omitted} [εθεορουν]{.greek-added} που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μα[ρ]{.unclear}[ια]{.greek-supplied} [[η]{.unclear}]{.greek-added} ιακωβου και σαλωμη ηγ[ο]{.unclear}ρασαν αρωματα ινα ελθουσαι [αλειψωσιν]{.greek-omitted} [αλειψωσι]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[16:1]{.aside}

και λιαν πρω[ι]{.unclear} της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον [εκ]{.greek-omitted} [απο]{.greek-added} της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις [περιβεβλημενον]{.greek-omitted} [περιβεβλημμενον]{.greek-added} στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [[ν]{.greek-supplied}αζαρινον]{.greek-added} τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει [υμας]{.greek-omitted} [ημας]{.greek-added} εις τ[η]{.unclear}ν γαλιλαιαν εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} καθως ειπεν [υμιν]{.greek-omitted} [ημιν]{.greek-added}[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγκειλεν]{.greek-added} τοις μετ [α]{.unclear}υτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης [ηπιστησαν]{.greek-omitted} [υπηστησαν]{.greek-added}[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατο[υ]{.unclear}σιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες [απηγγειλαν]{.greek-omitted} [απηγκειλαν]{.greek-added} τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη [και[ω]{.greek-supplied}νειδησε]{.greek-added} [και]{.greek-omitted} [ωνειδισεν]{.greek-omitted} την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και σκληροκαρδιαν ο[τ]{.unclear}[ι]{.greek-supplied} τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[[16:14 *(lacunose)*]{.lacunose}]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαν[τ]{.unclear}α κηρυξατε το ευαγγελιον παση τη [κτισει]{.greek-omitted} [κτιση]{.greek-added}[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν [θανασιμον]{.greek-omitted} [θανα[σ]{.unclear}ημον]{.greek-added} τ[ι]{.unclear} πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

