---
title: "Collation of Byz^RP^ vs 31390 (1390)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1390 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31390).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1390                                   	| λογος                              	|
| 1390 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1390 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1390               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1390                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1390 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1390                                                     	| [―]{.gap}                        	|
:::

## First Timothy

### Chapter 1

παυλος αποστολος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} κατ επιταγην [θεου]{.greek-abbr} [σωτηρος]{.greek-abbr} ημων και [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} της ελπιδος ημων[1:1]{.aside}

τιμοθεω γνησιω τεκνω εν πιστει χαρις ελεος ειρηνη απο [θεου]{.greek-abbr} [πατρος]{.greek-abbr} ημων και [χριστου]{.greek-abbr} [ιησου]{.greek-abbr} του [κυριου]{.greek-abbr} ημων[1:2]{.aside}

καθως παρεκαλεσα σε προσμειναι εν εφεσω πορευομενος [εις]{.greek-omitted} [μακεδονιαν]{.greek-omitted} [ινα]{.greek-omitted} [παραγγειλης]{.greek-omitted} [τισιν]{.greek-omitted} [μη]{.greek-omitted} [ετεροδιδασκαλειν]{.greek-omitted}[1:3]{.aside}

[καθως]{.greek-omitted} [παρεκαλεσα]{.greek-omitted} [σε]{.greek-omitted} [προσμειναι]{.greek-omitted} [εν]{.greek-omitted} [εφεσω]{.greek-omitted} [πορευομενος]{.greek-omitted} εις μακεδονιαν ινα παραγγειλης τισιν μη ετεροδιδασκαλειν[1:3 | instance no. 2]{.aside}

μηδε προσεχειν μυθοις και γενεαλογιαις απεραντοις αιτινες ζητησεις παρεχουσιν μαλλον η [οικονομιαν]{.greek-omitted} [οικοδομιαν]{.greek-added} [θεου]{.greek-abbr} την εν πιστει[1:4]{.aside}

το δε τελος της παραγγελιας εστιν αγαπη εκ καθαρας καρδιας και συνειδησεως αγαθης και πιστεως ανυποκριτου[1:5]{.aside}

ων τινες αστοχησαντες εξετραπησαν εις ματαιολογιαν[1:6]{.aside}

θελοντες ειναι νομοδιδασκαλοι μη νοουντες μητε α λεγουσιν μητε περι τινων διαβεβαιουνται[1:7]{.aside}

οιδαμεν δε οτι καλος ο νομος εαν τις αυτω νομιμως χρηται[1:8]{.aside}

ειδως τουτο οτι δικαιω νομος ου κειται ανομοις δε και ανυποτακτοις ασεβεσιν και αμαρτωλοις ανοσιοις και βεβηλοις [πατρολωαις]{.greek-omitted} [πατραλωαις]{.greek-added} και [μητρολωαις]{.greek-omitted} [μητραλωαις]{.greek-added} ανδροφονοις[1:9]{.aside}

πορνοις αρσενοκοιταις ανδραποδισταις ψευσταις επιορκοις και ει τι ετερον τη υγιαινουση διδασκαλια αντικειται[1:10]{.aside}

κατα το ευαγγελιον της δοξης του μακαριου [θεου]{.greek-abbr} ο επιστευθην εγω[1:11]{.aside}

και χαριν εχω τω ενδυναμωσαντι με [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} τω [κυριω]{.greek-abbr} ημων οτι πιστον με ηγησατο θεμενος εις διακονιαν[1:12]{.aside}

τον προτερον οντα βλασφημον και διωκτην και υβριστην αλλα [και]{.greek-added} ηλεηθην οτι αγνοων εποιησα εν απιστια[1:13]{.aside}

υπερεπλεονασεν δε η χαρις του [κυριου]{.greek-abbr} ημων μετα πιστεως και αγαπης της εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr}[1:14]{.aside}

πιστος ο λογος και πασης αποδοχης αξιος οτι [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ηλθεν εις τον κοσμον αμαρτωλους σωσαι ων πρωτος ειμι εγω[1:15]{.aside}

αλλα δια τουτο ηλεηθην ινα εν εμοι πρωτω ενδειξηται [ιησους]{.greek-abbr} [χριστος]{.greek-abbr} την πασαν μακροθυμιαν προς υποτυπωσιν των μελλοντων πιστευειν επ αυτω εις ζωην αιωνιον[1:16]{.aside}

τω δε βασιλει των αιωνων αφθαρτω αορατω μονω σοφω [θεω]{.greek-abbr} τιμη [και]{.greek-omitted} δοξα εις τους αιωνας [των]{.greek-omitted} [αιωνων]{.greek-omitted} αμην[1:17]{.aside}

ταυτην την παραγγελιαν [παρατιθεμαι]{.greek-omitted} [τιθεμαι]{.greek-added} σοι τεκνον τιμοθεε κατα τας [προαγουσας]{.greek-omitted} [επι]{.greek-omitted} [σε]{.greek-omitted} [προφητειας]{.greek-omitted} [ινα]{.greek-omitted} [στρατευη]{.greek-omitted} [εν]{.greek-omitted} [αυταις]{.greek-omitted} [την]{.greek-omitted} [καλην]{.greek-omitted} [στρατειαν]{.greek-omitted}[1:18]{.aside}

[ταυτην]{.greek-omitted} [την]{.greek-omitted} [παραγγελιαν]{.greek-omitted} [παρατιθεμαι]{.greek-omitted} [σοι]{.greek-omitted} [τεκνον]{.greek-omitted} [τιμοθεε]{.greek-omitted} [κατα]{.greek-omitted} [τας]{.greek-omitted} προαγουσας επι σε προφητειας ινα στρατευη εν αυταις την καλην στρατειαν[1:18 | instance no. 2]{.aside}

εχων πιστιν και αγαθην συνειδησιν ην τινες απωσαμενοι περι την πιστιν εναυαγησαν[1:19]{.aside}

ων εστιν υμεναιος και αλεξανδρος ους παρεδωκα τω σατανα ινα παιδευθωσιν μη βλασφημειν[1:20]{.aside}

### Chapter 2

παρακαλω ουν πρωτον παντων ποιεισθαι δεησεις προσευχας εντευξεις ευχαριστιας υπερ παντων [ανθρωπων]{.greek-abbr}[2:1]{.aside}

υπερ βασιλεων και παντων των εν υπεροχη οντων ινα ηρεμον και ησυχιον βιον διαγωμεν εν παση ευσεβεια και σεμνοτητι[2:2]{.aside}

τουτο γαρ καλον και αποδεκτον ενωπιον του [σωτηρος]{.greek-abbr} ημων [θεου]{.greek-abbr}[2:3]{.aside}

ος παντας [ανθρωπους]{.greek-abbr} θελει σωθηναι και εις επιγνωσιν αληθειας ελθειν[2:4]{.aside}

εις γαρ [θεος]{.greek-abbr} εις και μεσιτης [θεου]{.greek-abbr} και [ανθρωπων]{.greek-abbr} [ανθρωπος]{.greek-abbr} [χριστος]{.greek-abbr} [ιησους]{.greek-abbr}[2:5]{.aside}

ο δους εαυτον αντιλυτρον υπερ παντων το μαρτυριον καιροις ιδιοις[2:6]{.aside}

εις ο ετεθην εγω κηρυξ [και]{.greek-omitted} αποστολος αληθειαν λεγω [εν]{.greek-omitted} [χριστω]{.greek-omitted} ου ψευδομαι διδασκαλος εθνων εν πιστει και αληθεια[2:7]{.aside}

βουλομαι ουν προσευχεσθαι τους ανδρας εν παντι τοπω επαιροντας οσιους χειρας χωρις οργης και διαλογισμου[2:8]{.aside}

ωσαυτως και τας γυναικας εν καταστολη κοσμιω μετα αιδους και σωφροσυνης κοσμειν εαυτας μη εν πλεγμασιν η χρυσω η μαργαριταις η ιματισμω πολυτελει[2:9]{.aside}

αλλ ο πρεπει γυναιξιν επαγγελλομεναις θεοσεβειαν δι εργων αγαθων[2:10]{.aside}

γυνη εν ησυχια μανθανετω εν παση υποταγη[2:11]{.aside}

γυναικι δε διδασκειν ουκ επιτρεπω ουδε αυθεντειν ανδρος αλλ ειναι εν ησυχια[2:12]{.aside}

αδαμ γαρ πρωτος επλασθη ειτα ευα[2:13]{.aside}

και αδαμ ουκ ηπατηθη η δε γυνη απατηθεισα εν παραβασει γεγονεν[2:14]{.aside}

σωθησεται δε δια της τεκνογονιας εαν μεινωσιν εν πιστει και αγαπη και αγιασμω μετα σωφροσυνης[2:15]{.aside}

### Chapter 3

πιστος ο λογος ει τις επισκοπης ορεγεται καλου [εργου]{.greek-omitted} [επιθυμει]{.greek-omitted}[3:1]{.aside}

[πιστος]{.greek-omitted} [ο]{.greek-omitted} [λογος]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [επισκοπης]{.greek-omitted} [ορεγεται]{.greek-omitted} [καλου]{.greek-omitted} εργου επιθυμει[3:1 | instance no. 2]{.aside}

δει ουν τον επισκοπον ανεπιληπτον ειναι μιας γυναικος ανδρα [νηφαλεον]{.greek-omitted} [νηφαλιον]{.greek-added} σωφρονα κοσμιον φιλοξενον διδακτικον[3:2]{.aside}

μη παροι[νον]{.unclear} [μη]{.unclear} [πλη]{.unclear}κτην [μη]{.greek-omitted} [αισχροκερδη]{.greek-omitted} αλλ επιεικη αμαχον αφιλαρ[γυρον]{.unclear}[3:3]{.aside}

του ιδιου οικου καλως προισταμενον τεκνα εχοντα εν υποταγη μετα πασης σεμνοτητος[3:4]{.aside}

ει δε τις του ιδιου οικου προστηναι ουκ οιδεν πως εκκλησιας [θεου]{.greek-abbr} επιμελησεται[3:5]{.aside}

μη νεοφυτον ινα μη τυφωθεις εις κριμα εμπεση του διαβολου[3:6]{.aside}

δει δε αυτον και μαρτυριαν καλην εχειν απο των εξωθεν ινα μη εις ονειδισμον εμπεση και παγιδα του διαβολου[3:7]{.aside}

διακονους ωσαυτως σεμνους μη διλογους μη οινω πολλω προσεχοντας μη αισχροκερδεις[3:8]{.aside}

εχοντας το μυστηριον της πιστεως εν καθαρα συνειδησει[3:9]{.aside}

και ουτοι δε δοκιμαζεσθωσαν πρωτον ειτα διακονειτωσαν ανεγκλητοι οντες[3:10]{.aside}

γυναικας ωσαυτως σεμνας μη διαβολους [νηφαλεους]{.greek-omitted} [νηφαλιους]{.greek-added} πιστας εν πασιν[3:11]{.aside}

δια[κονοι]{.unclear} εστωσαν μιας γυναικος ανδρες τεκνων καλως προισταμενοι και των ιδιων οικων[3:12]{.aside}

οι γαρ καλως διακονησαντες βαθμον εαυτοις καλον περιποιουντ[α]{.unclear}ι και πολλην παρρησιαν εν πιστει τη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr}[3:13]{.aside}

ταυτα σοι γραφω ελπιζων ελθειν προς σε ταχιον[3:14]{.aside}

εαν δε βραδυνω ινα ειδης πως δει εν οικω [θεου]{.greek-abbr} αναστρεφεσθαι ητις εστιν εκκλησια [θεου]{.greek-abbr} ζωντος στυλος και εδραιωμα της αληθειας[3:15]{.aside}

και ομολογουμενως μεγα εστιν το της ευσεβειας μυστηριον [θεος]{.greek-abbr} εφανερωθη εν σαρκι εδικαιωθη εν [πνευματι]{.greek-abbr} ωφθη αγγελοις εκηρυχθη εν εθνεσιν επιστευθη εν κοσμω ανεληφθη εν δοξη[3:16]{.aside}

### Chapter 4

το δε [πνευμα]{.greek-abbr} ρητως λεγει οτι εν υστεροις καιροις αποστησονται τινες της πιστεως προσεχοντες πνευμασιν πλανοις και διδασκαλιαις δαιμονιων[4:1]{.aside}

εν υποκρισει ψευδολογων [κεκαυτηριασμενων]{.greek-omitted} [κεκαυστηριασμενων]{.greek-added} την ιδιαν συνειδησιν[4:2]{.aside}

κωλυοντων γαμειν απεχεσθαι βρωματων α ο [θεος]{.greek-abbr} εκτισεν εις μεταληψιν μετα ευχαριστιας τοις πιστοις και επεγνωκοσιν την αληθειαν[4:3]{.aside}

οτι παν κτισμα [θεου]{.greek-abbr} καλον και ουδεν αποβλητον μετα ευχαριστιας λαμβανομενον[4:4]{.aside}

αγιαζεται γαρ δια λογου [θεου]{.greek-abbr} και εντευξεως[4:5]{.aside}

ταυτα υποτιθεμενος τοις αδελφοις καλος εση διακονος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εντρεφομενος τοις λογοις της πιστεως και της καλης διδασκαλιας η παρηκολουθηκας[4:6]{.aside}

τους δε βεβηλους και γραωδεις μυθους παραιτου γυμναζε δε σεαυτον προς ευσεβειαν[4:7]{.aside}

η γαρ σωματικη γυμνασια προς ολιγον εστιν ωφελιμος η δε ευσεβεια προς παντα ωφελιμος εστιν [επαγγελιαν]{.greek-omitted} [επαγγελιασ]{.greek-added} εχουσα ζωης της νυν και της μελλουσης[4:8]{.aside}

πιστος ο λογος και πασης αποδοχης αξιος[4:9]{.aside}

εις τουτο γαρ και κοπιωμεν και ονειδιζομεθα οτι ηλπικαμεν επι [θεω]{.greek-abbr} ζωντι ος εστιν [σωτηρ]{.greek-abbr} παντων [ανθρωπων]{.greek-abbr} μαλιστα πιστων[4:10]{.aside}

[παραγγελλε]{.greek-omitted} [παραγγελαι]{.greek-added} ταυτα και διδασκε[4:11]{.aside}

μηδεις σου της νεοτητος καταφρονειτω αλλα τυπος γινου των πιστων εν λογω εν αναστροφη εν αγαπη εν [πνευματι]{.greek-abbr} εν πιστει εν αγνεια[4:12]{.aside}

εως ερχομαι προσεχε τη αναγνωσει τη παρακλησει τη διδασκαλια[4:13]{.aside}

μη αμελει του εν σοι χαρισματος ο εδοθη σοι δια προφητειας μετα επιθεσεως των χειρων του πρεσβυτεριου[4:14]{.aside}

ταυτα μελετα εν τουτοις ισθι ινα σου η προκοπη φανερα η εν πασιν[4:15]{.aside}

επεχε σεαυτω και τη διδασκαλια επιμενε αυτοις τουτο γαρ ποιων και σεαυτον σωσεις και τους ακουοντας σου[4:16]{.aside}

### Chapter 5

πρεσβυτερω μη επιπληξης αλλα [παρακαλει]{.greek-omitted} [πρακαλει]{.greek-added} ως [πατερα]{.greek-abbr} νεωτερους ως αδελφους[5:1]{.aside}

πρεσβυτερας ως [μητερας]{.greek-abbr} νεωτερας ως αδελφας εν παση αγνεια[5:2]{.aside}

χηρας τιμα τας οντως χηρας[5:3]{.aside}

ει δε τις χηρα τεκνα η εκγονα [εχει]{.unclear} μανθανετωσαν πρωτον τον ιδιον οικον [ευσεβειν]{.greek-omitted} [και]{.greek-omitted} [αμοιβας]{.greek-omitted} [αποδιδοναι]{.greek-omitted} [τοις]{.greek-omitted} [προγονοις]{.greek-omitted} [τουτο]{.greek-omitted} [γαρ]{.greek-omitted} [εστιν]{.greek-omitted} [αποδεκτον]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[5:4]{.aside}

[ει]{.greek-omitted} [δε]{.greek-omitted} [τις]{.greek-omitted} [χηρα]{.greek-omitted} [τεκνα]{.greek-omitted} [η]{.greek-omitted} [εκγονα]{.greek-omitted} [εχει]{.greek-omitted} [μανθανετωσαν]{.greek-omitted} [πρωτον]{.greek-omitted} [τον]{.greek-omitted} [ιδιον]{.greek-omitted} [οικον]{.greek-omitted} ευσεβειν και αμοιβας αποδιδοναι τοις προγονοις τουτο γαρ εστιν αποδεκτον ενωπιον του [θεου]{.greek-abbr}[5:4 | instance no. 2]{.aside}

η δε οντως χηρα και μεμονωμενη ηλπικεν επι τον [θεον]{.greek-abbr} και προσμενει ταις δεησεσιν και ταις προσευχαις νυκτος και ημερας[5:5]{.aside}

η δε σπαταλωσα ζωσα τεθνηκεν[5:6]{.aside}

και ταυτα παραγγελλε ινα ανεπιληπτοι ωσιν[5:7]{.aside}

ει δε τις των ιδιων και μαλιστα των οικειων ου προνοει την πιστιν ηρνηται και εστιν απιστου χειρων[5:8]{.aside}

χηρα καταλεγεσθω μη ελαττον ετων εξηκοντα γεγονυια ενος ανδρος γυνη[5:9]{.aside}

εν εργοις καλοις μαρτυρουμενη ει ετεκνοτροφησεν ει εξενοδοχησεν ει αγιων ποδας ενιψεν ει θλιβομενοις επηρκεσεν ει παντι εργω αγαθω επηκολουθησεν[5:10]{.aside}

νεωτερας δε χηρας παραιτου οταν γαρ καταστρηνιασωσιν του [χριστου]{.greek-abbr} γαμειν θελουσιν[5:11]{.aside}

εχουσαι κριμα οτι την πρωτην πιστιν ηθετησαν[5:12]{.aside}

αμα δε και αργαι μανθανουσιν περιερχομεναι τας οικιας ου μονον δε αργαι αλλα και φλυαροι και περιεργοι λαλουσαι τα μη δεοντα[5:13]{.aside}

βουλομαι ουν νεωτερας γαμειν τεκνογονειν οικοδεσποτειν μηδεμιαν αφορμην διδοναι τω αντικειμενω λοιδοριας χαριν[5:14]{.aside}

ηδη γαρ τινες εξετραπησαν οπισω του σατανα[5:15]{.aside}

ει τις πιστος η πιστη εχει χηρας επαρκειτω αυταις και μη βαρεισθω η εκκλησια ινα ταις οντως χηραις επαρκεση[5:16]{.aside}

οι καλως προεστωτες πρεσβυτεροι διπλης τιμης αξιουσθωσαν μαλιστα οι [κοπιωντες]{.greek-omitted} [κοποιωντες]{.greek-added} εν λογω και διδασκαλια[5:17]{.aside}

λεγει γαρ η γραφη βουν αλοωντα ου φιμωσεις και αξιος ο εργατης του μισθου αυτου[5:18]{.aside}

κατα πρεσβυτερου κατηγοριαν μη παραδεχου εκτος ει μη επι δυο η τριων μαρτυρων[5:19]{.aside}

τους αμαρτανοντας ενωπιον παντων ελεγχε ινα [και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [φοβον]{.greek-omitted} [εχωσιν]{.greek-omitted}[5:20]{.aside}

[τους]{.greek-omitted} [αμαρτανοντας]{.greek-omitted} [ενωπιον]{.greek-omitted} [παντων]{.greek-omitted} [ελεγχε]{.greek-omitted} [ινα]{.greek-omitted} και οι λοιποι φοβον εχωσιν[5:20 | instance no. 2]{.aside}

διαμαρτυρομαι ενωπιον του [θεου]{.greek-abbr} και [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} και των εκλεκτων αγγελων ινα ταυτα φυλαξης χωρις προκριματος μηδεν ποιων κατα [προσκλησιν]{.greek-omitted} [προσκλισιν]{.greek-added}[5:21]{.aside}

χειρας ταχεως μηδενι επιτιθει μηδε κοινωνει αμαρτιαις αλλοτριαις σεαυτον αγνον τηρει[5:22]{.aside}

μηκετι υδροποτει αλλ οινω ολιγω χρω δια τον στομαχον σου και τας πυκνας σου ασθενειας[5:23]{.aside}

τινων [ανθρωπων]{.greek-abbr} αι αμαρτιαι προδηλοι εισιν προαγουσαι εις κρισιν τισιν δε και επακολουθουσιν[5:24]{.aside}

ωσαυτως και τα καλα εργα προδηλα εστιν και τα αλλως εχοντα κρυβηναι ου [δυνανται]{.greek-omitted} [δυναται]{.greek-added}[5:25]{.aside}

### Chapter 6

οσοι εισιν υπο ζυγον δουλοι τους ιδιους δεσποτας πασης τιμης αξιους ηγεισθωσαν ινα μη το ονομα του [θεου]{.greek-abbr} και η διδασκαλια βλασφημηται[6:1]{.aside}

οι δε πιστους εχοντες δεσποτας μη καταφρονειτωσαν οτι αδελφοι εισιν αλλα μαλλον δουλευετωσαν οτι πιστοι εισιν και αγαπητοι οι της ευεργεσιας αντιλαμβανομενοι ταυτα διδασκε και παρακαλει[6:2]{.aside}

ει τις ετεροδιδασκαλει και μη προσερχεται υγιαινουσιν λογοις τοις του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} και τη κατ ευσεβειαν διδασκαλια[6:3]{.aside}

τετυφωται μηδεν επισταμενος αλλα νοσων περι ζητησεις και λογομαχιας εξ ων γινεται φθονος ερις βλασφημιαι υπονοιαι πονηραι[6:4]{.aside}

[δια]{.greek-added} [διαπαρατριβαι]{.greek-omitted} [παρατριβαι]{.greek-added} διεφθαρμενων [ανθρωπων]{.greek-abbr} τον νουν και απεστερημενων της αληθειας νομιζοντων πορισμον ειναι την ευσεβειαν αφιστασο απο των τοιουτων[6:5]{.aside}

εστιν δε πορισμος μεγας η ευσεβεια μετα αυταρκειας[6:6]{.aside}

ουδεν γαρ εισηνεγκαμεν εις τον κοσμον δηλον οτι ουδε εξενεγκειν τι [δυναμεθα]{.greek-omitted} [δυναμεθαι]{.greek-added}[6:7]{.aside}

εχοντες δε διατροφας και σκεπασματα τουτοις αρκεσθησομεθα[6:8]{.aside}

οι δε βουλομενοι πλουτειν [εμπιπτουσιν]{.greek-omitted} [εις]{.greek-omitted} [πειρασμον]{.greek-omitted} [και]{.greek-omitted} [παγιδα]{.greek-omitted} [και]{.greek-omitted} [επιθυμιας]{.greek-omitted} [πολλας]{.greek-omitted} [ανοητους]{.greek-omitted} [και]{.greek-omitted} [βλαβερας]{.greek-omitted} [αιτινες]{.greek-omitted} [βυθιζουσιν]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [εις]{.greek-omitted} [ολεθρον]{.greek-omitted} [και]{.greek-omitted} [απωλειαν]{.greek-omitted}[6:9]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [βουλομενοι]{.greek-omitted} [πλουτειν]{.greek-omitted} εμπιπτουσιν εις πειρασμον και παγιδα και επιθυμιας πολλας ανοητους και βλαβερας αιτινες βυθιζουσιν τους [ανθρωπους]{.greek-abbr} εις ολεθρον και απωλειαν[6:9 | instance no. 2]{.aside}

ριζα γαρ παντων των κακων εστιν η φιλαργυρια ης τινες ορεγομενοι απεπλανηθησαν απο της πιστεως και εαυτους περιεπειραν οδυναις πολλαις[6:10]{.aside}

συ δε ω [ανθρωπε]{.greek-abbr} του [θεου]{.greek-abbr} ταυτα φευγε διωκε [δε]{.greek-omitted} δικαιοσυνην ευσεβειαν πιστιν αγαπην υπομονην πραοτητα[6:11]{.aside}

αγωνιζου τον καλον αγωνα της πιστεως επιλαβου της αιωνιου ζωης εις ην [και]{.greek-added} εκληθης και ωμολογησας την καλην ομολογιαν ενωπιον [πολλων]{.greek-omitted} μαρτυρων[6:12]{.aside}

παραγγελλω [σοι]{.greek-omitted} [σο]{.greek-added} ενωπιον του [θεου]{.greek-abbr} του ζωοποιουντος τα παντα και [χριστου]{.greek-abbr} [ιησου]{.greek-abbr} του μαρτυρησαντος επι ποντιου πιλατου την καλην ομολογιαν[6:13]{.aside}

τηρησαι σε την εντολην ασπιλον ανεπιληπτον μεχρι της επιφανειας του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[6:14]{.aside}

ην καιροις ιδιοις δειξει ο μακαριος και μονος δυναστης ο βασιλευς των βασιλευοντων και [κυριος]{.greek-abbr} των κυριευοντων[6:15]{.aside}

ο μονος εχων αθανασιαν φως οικων απροσιτον ον ειδεν ουδεις [ανθρωπων]{.greek-abbr} ουδε ιδειν δυναται ω τιμη και κρατος αιωνιον αμην[6:16]{.aside}

τοις πλουσιοις εν τω νυν αιωνι παραγγελλε μη υψηλοφρονειν μηδε ηλπικεναι επι πλουτου αδηλοτητι αλλ εν τω [θεω]{.greek-abbr} τω ζωντι τω παρεχοντι ημιν παντα πλουσιως εις απολαυσιν[6:17]{.aside}

αγαθοεργειν πλουτειν εν εργοις καλοις ευμεταδοτους ειναι κοινωνικους[6:18]{.aside}

αποθησαυριζοντας εαυτοις θεμελιον καλον εις το μελλον ινα επιλαβωνται της αιωνιου ζωης[6:19]{.aside}

ω τιμοθεε την παραθηκην φυλαξον εκτρεπομενος τας βεβηλους κενοφωνιας και αντιθεσεις της [ψευδωνυμου]{.greek-omitted} [ψευδωνιμου]{.greek-added} γνωσεως[6:20]{.aside}

ην τινες επαγγελλομενοι περι [την]{.greek-omitted} [πιστιν]{.greek-omitted} [ηστοχησαν]{.greek-omitted} [η]{.greek-omitted} [χαρις]{.greek-omitted} [μετα]{.greek-omitted} [σου]{.greek-omitted} [αμην]{.greek-omitted}[6:21]{.aside}

[ην]{.greek-omitted} [τινες]{.greek-omitted} [επαγγελλομενοι]{.greek-omitted} [περι]{.greek-omitted} την πιστιν ηστοχησαν η χαρις μετα σου αμην[6:21 | instance no. 2]{.aside}

