---
title: "Collation of Byz^RP^ vs 31506 (1506)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1506 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31506).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1506                                   	| λογος                              	|
| 1506 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1506 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1506               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1506                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1506 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1506                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [υιου]{.corr} του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν [τη]{.greek-omitted} ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

[κ]{.unclear}αι [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορ[δα]{.unclear}ν[η]{.unclear} ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ενδεδυμενος τριχας καμηλου και ζωνην [δερματινην]{.greek-omitted} [δερματυνην]{.greek-added} περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας [εν]{.greek-omitted} υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} [α]{.unclear}πο ναζαρετ της γαλιλαιας και εβαπτισθη [υ]{.unclear}πο [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εις τον ιορδανην[1:9]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} [αναβαινων]{.greek-omitted} [αναβαινον]{.greek-added} απο του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και [το]{.greek-omitted} [τω]{.greek-added} [πνευμα]{.greek-abbr} ωσει περιστεραν [καταβαινον]{.greek-omitted} [καταβαιν[ων]{.unclear}]{.greek-added} επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο υιος μου ο αγαπητος εν ω [ε]{.unclear}υδοκησα[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} αυτον εκ[β]{.unclear}αλ[λ]{.unclear}ει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω [τεσσαρακοντα]{.greek-added} ημερας [τεσσαρακοντα]{.greek-omitted} πειραζομενος υπο [τ]{.unclear}ου σα[τ]{.unclear}ανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα [αυτων]{.greek-omitted} ηκολουθησαν αυτω[1:18]{.aside}

και [προβας]{.greek-omitted} [προσβας]{.greek-added} εκειθεν ολιγον ειδεν ιακωβον τον [του]{.greek-omitted} ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αυτους εν τω [πλοιω]{.greek-omitted} [πλιω]{.greek-added} καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο [παντες]{.greek-added} επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και [ην]{.corr} εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ενεκραξ[ε]{.unclear}]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι εστιν τουτο [τις]{.greek-omitted} [τι]{.greek-added} [εστιν]{.greek-added} η διδαχη η καινη αυτη [ο]{.unclear}τι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [[πνασι]{.greek-abbr}]{.greek-added} τοις ακαθαρτοις επιτασσει και [υ]{.greek-added} [υπακουουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[1:27]{.aside}

[και]{.greek-omitted} [εθαμβηθησαν]{.greek-omitted} [παντες]{.greek-omitted} [ωστε]{.greek-omitted} [συζητειν]{.greek-omitted} [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [λεγοντας]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [τουτο]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [διδαχη]{.greek-omitted} [η]{.greek-omitted} [καινη]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [κατ]{.greek-omitted} [εξουσιαν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [πνευμασιν]{.greek-omitted} [τοις]{.greek-omitted} [ακαθαρτοις]{.greek-omitted} [επιτασσει]{.greek-omitted} [και]{.greek-omitted} [υπακουουσιν]{.greek-omitted} [πακουουσιν]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added}[1:27 | instance no. 2]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} [δε]{.unclear} η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης [εξελθοντες]{.greek-omitted} [εξελθων]{.greek-added} [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο [πυρεσσουσα]{.greek-omitted} [πυρεττουσα]{.greek-added} και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντ[ας]{.unclear} και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [[εθ]{.unclear}εραπευσε]{.greek-added} πολλ[ους]{.unclear} κακως εχοντας ποικ[ι]{.unclear}λαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} [κα]{.unclear}ι ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [οτι]{.greek-omitted} [ηδεισαν]{.greek-omitted} [αυτον]{.greek-omitted}[1:34]{.aside}

[και]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [πολλους]{.greek-omitted} [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [ποικιλαις]{.greek-omitted} [νοσοις]{.greek-omitted} [και]{.greek-omitted} [δαιμονια]{.greek-omitted} [πολλα]{.greek-omitted} [εξεβαλεν]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηφιεν]{.greek-omitted} [λαλειν]{.greek-omitted} τα δαιμονια οτι ηδεισαν αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34 | instance no. 2]{.aside}

και πρωι εννυχον λιαν αναστας εξηλθεν και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες [σε]{.corr} [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ [ελ[η]{.unclear}]{.greek-added} [εξεληλυθα]{.corr}[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων αυτω οτι εαν θελης δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου [α]{.greek-omitted} [ο]{.greek-added} [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} αλλ εξω εν ερημοις [τοποι]{.greek-added} [τοποις]{.corr} ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παναχτοθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και εισηλθεν [παλιν]{.greek-omitted} εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον εστιν[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και [ερχονται]{.corr} προς αυτον παραλυτικον φεροντες αιρομενον υπο [τεσσαρων]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added}[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον [κραβατον]{.greek-added} [κραββατον]{.corr} εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον αφεωνται σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως λαλει [βλασφημιας]{.greek-omitted} [βλασφημει]{.greek-added} τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν εγειραι και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ειδειτε]{.greek-added} οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} και αρας τον κραββατον εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και [δοξαζειν]{.greek-omitted} [δοξαζει]{.greek-added} τον [θεον]{.greek-abbr} [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} οτι ουδεποτε ουτως ειδομεν[2:12]{.aside}

[και]{.unclear} [εξη]{.unclear}λθεν παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκε[ν]{.unclear} αυτους[2:13]{.aside}

[και]{.unclear} [παραγων]{.unclear} [ειδεν]{.unclear} [λευι]{.greek-omitted} [λευ[ει]{.unclear}]{.greek-added} τον του αλφαιου καθημενον [επ]{.unclear}ι το τελωνιον και λεγει αυτω ακολουθει μο[ι]{.unclear} και αναστας ηκολ[ου]{.unclear}θ[ησ]{.unclear}εν αυτω[2:14]{.aside}

και [ε]{.unclear}γενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολ[λοι]{.unclear} και ηκολουθη[σ]{.unclear}αν αυτω[2:15]{.aside}

και οι [γρ]{.unclear}αμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα [μετα]{.unclear} [των]{.greek-omitted} τελωνων και αμαρτωλων ελεγον τοις μαθηταις [αυτου]{.greek-supplied} τι [οτι]{.greek-omitted} μετα [των]{.greek-omitted} τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

[και]{.greek-omitted} ακουσας [δε]{.greek-added} ο [ιησους]{.greek-abbr} [λε]{.unclear}γει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ [η]{.unclear}λθον καλεσαι δ[ι]{.unclear}καιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

[και]{.greek-omitted} [ησαν]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευοντες]{.greek-omitted} [και]{.greek-omitted} [ερχονται]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευουσιν]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [σοι]{.greek-omitted} [μαθηται]{.greek-omitted} [ου]{.greek-omitted} [νηστευουσιν]{.greek-omitted}[[2:18 *(lacunose)*]{.lacunose}]{.aside}

και ησαν οι μαθηται [[ιω]{.greek-abbr}]{.greek-added} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευοντες]{.greek-omitted} [και]{.greek-omitted} [ερχονται]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευουσιν]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [σοι]{.greek-omitted} [μαθηται]{.greek-omitted} [ου]{.greek-omitted} [νηστευουσιν]{.greek-omitted}[[2:18 | instance no. 2 *(lacunose)*]{.lacunose}]{.aside}

και ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω ει δε μη αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και [ουδεις]{.greek-omitted} [ουδε]{.greek-added} βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται αλλα οινον νεον εις [καινους]{.greek-added} ασκους [καινους]{.greek-omitted} βλητεον[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις σαββασιν δια των σποριμων και [η]{.unclear}ρξαντο οι μαθηται αυτου οδον ποιειν [τιλλοντες]{.greek-omitted} [τιλοντες]{.greek-added} τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δαυιδ οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ [α]{.unclear}υτου[2:25]{.aside}

πως [εισηλθεν]{.greek-omitted} [εισηλθον]{.greek-added} εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [[ε]{.unclear}ξεστι]{.greek-added} φαγειν ει μη τοις ιερευσιν και εδωκεν και τοις συν [αυτω]{.greek-omitted} [αυτοις]{.greek-added} [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε κυριος εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σα[ββατου]{.greek-supplied}[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} [θεραπευσει]{.greek-omitted} [θεραπευση]{.greek-added} αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις [τι]{.greek-added} [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η [αποκτειναι]{.greek-omitted} [απολεσαι]{.greek-added} οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη πωρωσει της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου υγιης ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως [μετα]{.greek-omitted} [των]{.greek-omitted} [ηρωδιανων]{.greek-omitted} [συμβουλιον]{.greek-omitted} [εποιουν]{.greek-omitted} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} [οπως]{.greek-omitted} [αυτον]{.greek-omitted} [απολεσωσιν]{.greek-omitted}[3:6]{.aside}

[και]{.greek-omitted} [εξελθοντες]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [ευθεως]{.greek-omitted} [μ]{.unclear}ετα των ηρωδιανων συμβουλιον [εποουν]{.greek-added} [εποιουν]{.corr} κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6 | instance no. 2]{.aside}

και ο [ιησους]{.greek-abbr} ανεχωρ[ησεν]{.unclear} μετα των μαθητων αυτου [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της [ιδουμαιας]{.greek-omitted} [ιουδαιας]{.greek-added} και περαν [του]{.greek-omitted} ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπον]{.greek-added} τοις μαθηταις [αυτου]{.greek-omitted} ιν[α]{.unclear} πλοιαριον προσκαρτερη αυτω δια τον οχλον ινα μη [θλιβωσιν]{.greek-omitted} [θληβωσιν]{.greek-added} αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα [οταν]{.greek-omitted} [οτε]{.greek-added} αυτον ε[θ]{.unclear}εωρει προσεπιπτεν αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} [λεγοντα]{.greek-omitted} [λεγοντες]{.greek-added} οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους [ηλθεν]{.greek-added} [ηθελε[ν]{.unclear}]{.corr} αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα αποστελλη [αυτους]{.greek-omitted} κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονο[μα]{.greek-supplied} πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον [του]{.greek-omitted} ιακωβου και επεθηκεν αυτοις ονοματα [βοανεργες]{.greek-omitted} [βοαν[η]{.unclear}ργ[ες]{.unclear}]{.greek-added} ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακω[β]{.unclear}ον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν [τον]{.greek-added} ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος [ωσ]{.greek-added} [ωστε]{.greek-omitted} [μη]{.greek-omitted} [δυνασθαι]{.greek-omitted} [αυτους]{.greek-omitted} [μητε]{.greek-omitted} [αρτον]{.greek-omitted} [φαγειν]{.greek-omitted}[3:20]{.aside}

[τε]{.greek-added} [και]{.greek-omitted} [συνερχεται]{.greek-omitted} [παλιν]{.greek-omitted} [οχλος]{.greek-omitted} [ωστε]{.greek-omitted} μη δυνασθαι [αυτους]{.greek-omitted} [αυτον]{.greek-added} [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20 | instance no. 2]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαν[τ]{.unclear}ες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι [των]{.greek-omitted} [τον]{.greek-added} δαιμονιων εκβαλλει τα [δ]{.unclear}αιμο[ν]{.unclear}ια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται [ο]{.greek-added} σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτ[η]{.unclear}ν μερισθη ου δυναται σταθηναι [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [εκεινη]{.greek-omitted}[3:24]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [ανεστη]{.greek-omitted} [εφ]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [μεμερισται]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [σταθηναι]{.greek-omitted} αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα [σκευη]{.greek-omitted} [σκευει]{.greek-added} του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [[αυτου]{.corr}]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου [και]{.greek-omitted} εξω εστωτες απεστειλαν [ουν]{.greek-added} [φωνουντες]{.greek-added} προς αυτον [φωνουντες]{.greek-omitted} [αυτον]{.greek-omitted}[3:31]{.aside}

και εκαθητο [οχλος]{.corr} περι αυτον ειπον δε [αυτω]{.greek-omitted} [ιδου]{.greek-omitted} [η]{.greek-omitted} [μητηρ]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} [εξω]{.greek-omitted} [ζητουσιν]{.greek-omitted} [σε]{.greek-omitted}[3:32]{.aside}

[και]{.greek-omitted} [εκαθητο]{.greek-omitted} [οχλος]{.greek-omitted} [περι]{.greek-omitted} [αυτον]{.greek-omitted} [ειπον]{.greek-omitted} [δε]{.greek-omitted} αυτω [ιδου]{.greek-omitted} η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι [αδελφαι]{.greek-omitted} [αδελφε]{.greek-added} σου εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32 | instance no. 2]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και [αδελφη]{.greek-omitted} [αδελφοι]{.greek-added} μου και [μητηρ]{.greek-abbr} [εστιν]{.greek-omitted} [μου]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο [διδασκειν]{.greek-omitted} [διδασκει]{.greek-added} παρα την θαλασσαν και [συνηχθη]{.greek-omitted} [συνηχθησαν]{.greek-added} προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

[ακουσατ]{.greek-added} [ακουετε]{.greek-omitted} [[ακουσατε]{.corr}]{.greek-added} [οτι]{.greek-added} ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και ηλθεν [[ηλθε]{.corr}]{.greek-added} [τα]{.corr} πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο [δε]{.greek-omitted} επεσεν επι το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

[η]{.unclear}λιου δε ανατειλαντος εκαυματισθη και δια το μη [εχειν]{.greek-omitted} [εχει]{.greek-added} ριζαν εξηρανθη[4:6]{.aside}

και αλλο [επεσεν]{.greek-omitted} [επεσε]{.greek-added} [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} [τριακοντα]{.greek-omitted} [[λ]{.greek-abbr}]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} [εξηκοντα]{.greek-omitted} [[ξ]{.greek-abbr}]{.greek-added} και [[ρ]{.greek-abbr}]{.greek-added} [εν]{.greek-omitted} [εκατον]{.greek-omitted}[4:8]{.aside}

και ελεγεν [[ελεγε]{.corr}]{.greek-added} [ο]{.corr} εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα τ[ην]{.unclear} παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι [το]{.greek-omitted} [τα]{.greek-added} [μυστηριον]{.greek-omitted} [μυστηρια]{.greek-added} της βασιλειας του [θεου]{.greek-abbr} [εκεινοις]{.greek-omitted} [τοις]{.greek-added} δε [λοιποις]{.greek-added} [τοις]{.greek-omitted} [εξω]{.greek-omitted} εν παραβολαις [τα]{.greek-omitted} [παντα]{.greek-omitted} [γινεται]{.greek-omitted}[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι [δε]{.corr} εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και [αιρει]{.greek-omitted} [[ε]{.unclear}ρει]{.greek-added} τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι [του]{.greek-added} [οταν]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [λογου]{.greek-added} [ακουοντες]{.greek-added} [και]{.greek-added} ευθεως μετα χαρας [λαμβανουσιν]{.greek-omitted} [λαμβανοντες]{.greek-added} αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι [εις]{.corr} τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα [λοιπα]{.greek-omitted} [λιπα]{.greek-added} επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} [τριακοντα]{.greek-omitted} [[λ]{.greek-abbr}]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} [εξηκοντα]{.greek-omitted} [[ξ]{.greek-abbr}]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} [εκατον]{.greek-omitted} [[ρ]{.greek-abbr}]{.greek-added}[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21]{.aside}

ου γαρ εστιν [τι]{.greek-omitted} [κρυπτον]{.greek-omitted} [κριπτον]{.greek-added} ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθ[η]{.unclear}[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω [μετρειτε]{.greek-omitted} μετρ[η]{.unclear}θησεται [υμιν]{.greek-omitted} [και]{.greek-omitted} [προστεθησεται]{.greek-omitted} υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} εχ[η]{.unclear} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} [ουτως]{.greek-omitted} [ουτος]{.greek-added} εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος βλαστανη και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως [αποστ]{.unclear}ελλει το δρεπανον οτι [παρεστηκεν]{.greek-omitted} ο θερισμος [παρεστηκεν]{.greek-added}[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινι [ομοιωσωμεν]{.greek-omitted} [ομοιωσομεν]{.greek-added} [ομοιωσω]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως κοκκον σιναπεως ος οταν σπαρη επι της γης [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων των σπερματων εστιν των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων [τ]{.unclear}ων λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [επειλυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης [διελθωμεν]{.greek-omitted} [διελθωμε]{.greek-added} εις το περαν[4:35]{.aside}

και αφεντες τον οχλον [παραλαμβανουσιν]{.greek-omitted} [παρλαμβανουσιν]{.greek-added} αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και [γινεται]{.unclear} λαιλαψ ανεμου μεγαλη τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλε]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζ[ε]{.unclear}σθαι[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι το προσκεφαλαιον καθευδων και [δ]{.unclear}ιεγειρουσιν αυτον [και]{.greek-omitted} λεγουσιν αυτω διδασκαλε ου μελει σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι εστε ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και [ελεγον]{.greek-omitted} [ελεγε]{.greek-added} προς αλληλους τις αρα [εστιν]{.greek-added} ουτος [εστιν]{.greek-omitted} [ο]{.unclear}τι και ο ανεμος και [και]{.greek-added} η θαλασσα υπακουουσιν [αυτω]{.greek-omitted} [αυτου]{.greek-added}[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και [εξελθοντι]{.greek-omitted} [εξελθοντος]{.greek-added} [αυτω]{.greek-omitted} [αυτου]{.greek-added} εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδει[ς]{.unclear} [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας [παιδας]{.greek-added} [πεδας]{.corr} συντετριφθαι και [ουδεις]{.greek-omitted} [ουδεν]{.greek-added} [αυτον]{.greek-omitted} [αυτο]{.greek-added} [ισχυεν]{.greek-omitted} [ισχυσε]{.greek-added} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [μημειοις]{.greek-added} [[μνημειοις]{.corr}]{.greek-added} ην κραζων και κατακοπτων εαυτον [λιθοις]{.greek-omitted}[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν [εδραμεν]{.greek-omitted} [εδρ[α]{.unclear}με]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη ειπεν τι εμοι και σοι [ιησου]{.greek-omitted} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε [εις]{.greek-added} τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω [εξελθε]{.greek-omitted} [εξελθειν]{.greek-added} το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [επηρωτησεν]{.greek-added} [αυτω]{.greek-added} τι σοι ονομα και απεκριθη [λεγων]{.greek-omitted} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον πολλα ινα [μη]{.greek-omitted} αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει προς τω ορει αγελη χοιρων [μεγαλη]{.greek-omitted} [μεγαλων]{.greek-added} βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον [παντες]{.greek-omitted} οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} τα ακαθαρτα εισηλθον εις τους χοιρους και [ωρμησεν]{.greek-omitted} [ωρμησε]{.greek-added} η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και ανηγγειλαν εις την πολιν και εις τους αγρους [και]{.greek-omitted} [εξηλθον]{.greek-omitted} [ιδειν]{.greek-omitted} [τι]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [γεγονος]{.greek-omitted}[5:14]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [βοσκοντες]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [εφυγον]{.greek-omitted} [και]{.greek-omitted} [ανηγγειλαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αγρους]{.greek-omitted} και εξηλθον ιδειν τι εστιν το γεγονος[5:14 | instance no. 2]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και θεωρουσιν τον δαιμονιζομενον καθημενον [και]{.greek-omitted} ιματισμενον και [σωφρονουντα]{.greek-omitted} [σοφρονουντα]{.greek-added} τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [ε]{.unclear}μβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον [αυτοις]{.greek-omitted} [αυτω]{.greek-added} οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [σε]{.greek-omitted} [ελαλησε]{.greek-added} [σοι]{.greek-added}[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και απηλθεν μετ αυτου και ηκολουθει αυτω οχλος πολυς και [συνεθλιβον]{.greek-omitted} [συνεθλιβεν]{.greek-added} αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα [παρ]{.greek-omitted} [παρα]{.greek-added} [αυτης]{.greek-omitted} [αυτοις]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι καν των [ι]{.unclear}ματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν [εαυτω]{.greek-omitted} [αυτω]{.greek-added} την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον [συνθλι]{.greek-added} [συνθλιβοντα]{.greek-omitted} [σε]{.greek-omitted} [και]{.greek-omitted} [λεγεις]{.greek-omitted} [τις]{.greek-omitted} [μου]{.greek-omitted} [ηψατο]{.greek-omitted}[5:31]{.aside}

[βοντα]{.greek-added} [και]{.greek-omitted} [ελεγον]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [βλεπεις]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [συνθλιβοντα]{.greek-omitted} σε και λεγεις τις μου ηψατο[5:31 | instance no. 2]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλλης]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} [ακουσας]{.greek-added} ευθεως [ακουσας]{.greek-omitted} τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω συνακολουθησαι ει μη πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις [τον]{.greek-omitted} [οικον]{.greek-omitted} [την]{.greek-added} [οικιαν]{.greek-added} του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} [κλαιοντας]{.corr} και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει [αυτοις]{.greek-omitted} [αυτω]{.greek-added} τι θορυβεισθε και κλαιετε το [παιδιον]{.greek-omitted} [παιδαριον]{.greek-added} ουκ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} αλλα καθευδει[5:39]{.aside}

και κατεγελων [αυτου]{.greek-omitted} ο δε εκβαλων παντας [παραλαμβανει]{.greek-omitted} [παραλαμβανη]{.greek-added} τον [πατερα]{.greek-abbr} [του]{.greek-omitted} [τη[ς]{.unclear}]{.greek-added} [παιδιου]{.greek-omitted} [παιδος]{.greek-added} και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το [παιδιον]{.greek-omitted} [παιδαριον]{.greek-added} [ανακειμενον]{.greek-omitted} [κατακειμενον]{.greek-added}[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει [αυτη]{.greek-omitted} [αυτω]{.greek-added} ταλιθα [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω εγειραι[5:41]{.aside}

[και]{.greek-added} [ευθεως]{.greek-added} [ανεστη]{.greek-added} [το]{.greek-added} [κορασιον]{.greek-added} [σοι]{.greek-added} [λεγω]{.greek-added} [εγειραι]{.greek-added} και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις [γνω]{.greek-omitted} [γνωσει]{.greek-added} τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν [εκειθεν]{.greek-omitted} [εκειθε]{.greek-added} και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και [ακολουθουσιν]{.greek-omitted} [ακολοθουσιν]{.greek-added} αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο [εν]{.greek-omitted} [επι]{.greek-added} [τη]{.greek-omitted} [της]{.greek-added} [συναγωγη]{.greek-omitted} [συναγωγης]{.greek-added} διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες [ποθεν]{.greek-omitted} [ποθε]{.greek-added} [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτα και τις η [δοθησα]{.greek-added} σοφια [η]{.greek-omitted} [δοθεισα]{.greek-omitted} αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο τεκτων ο [υιος]{.greek-omitted} [υις]{.greek-added} [της]{.greek-added} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} ουκ εστιν προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενεσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη [ραβδον]{.greek-omitted} [ραυδον]{.greek-added} μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υποδεδεμενους σανδαλια και μη ενδυσησθε δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και [οσοι]{.greek-omitted} [οπου]{.greek-added} [αν]{.greek-omitted} [εαν]{.greek-added} μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν [εκτιναξατε]{.greek-omitted} [εκτιναξαντες]{.greek-added} τον [χον]{.greek-added} [χουν]{.corr} τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η [γομορροις]{.greek-omitted} [γομοροις]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα [εξεβαλλον]{.greek-omitted} [εκβαλλων]{.greek-added} και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} οτι [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο [βαπτιζων]{.greek-omitted} [βαπτιστης]{.greek-added} εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσι]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης [ειπεν]{.greek-omitted} [ειπε]{.greek-added} οτι ον εγω απεκεφαλισα [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ [ο]{.greek-omitted} ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και εδησεν αυτον [εν]{.greek-omitted} [φυλακη]{.greek-omitted} [δια]{.greek-omitted} [ηρωδιαδα]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [φιλιππου]{.greek-omitted} [του]{.greek-omitted} [αδελφου]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [αυτην]{.greek-omitted} [εγαμησεν]{.greek-omitted}[6:17]{.aside}

[αυτος]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ηρωδης]{.greek-omitted} [αποστειλας]{.greek-omitted} [εκρατησεν]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [και]{.greek-omitted} [εδησεν]{.greek-omitted} [αυτον]{.greek-omitted} εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [[ιω]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [ιωαννης]{.greek-omitted} τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομεν[ης]{.unclear} ημερας [ευκαιρου]{.greek-omitted} οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις [της]{.greek-omitted} [τοις]{.greek-added} γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος [αυτης]{.greek-omitted} [αυτου]{.greek-added} της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν με αιτησης δωσω σοι εως [ημισους]{.greek-omitted} [ημισου]{.greek-added} της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα μοι δως εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:25]{.aside}

και περιλυπο[ς]{.unclear} γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυσασθε]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι [υπαγοντες]{.greek-omitted} [παγοντες]{.greek-added} πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added}[6:31]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων ειδεν ο [ιησους]{.greek-abbr} [οχλον]{.greek-added} πολυν [οχλον]{.greek-omitted} και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη [πολλων]{.greek-added} [ωρας]{.greek-omitted} [πολλης]{.greek-omitted} [γενομενης]{.greek-omitted} [γενομενων]{.greek-added} [προσελθοντες]{.greek-omitted} [προσελθοντων]{.greek-added} αυτω οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν [αυτω]{.greek-omitted} [αυτοις]{.greek-added} [απελθοντες]{.greek-omitted} [απελθοντων]{.greek-added} αγορασωμεν δηναριων διακοσιων αρτους και δωμεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και γνοντες λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακλιθηναι]{.greek-added} παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα [εκατον]{.greek-omitted} [[ρ]{.greek-abbr}]{.greek-added} και ανα [πεντηκοντα]{.greek-omitted} [[ν]{.greek-abbr}]{.greek-added}[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ηυλογησε]{.greek-added} και κατεκλασεν τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [κλασματων]{.greek-omitted} [κλασματια]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους [πεντακισχιλιοι]{.greek-omitted} [[͵ε]{.greek-abbr}]{.greek-added} ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις το πλοιον και προαγειν εις το περαν προς [βηθσαιδαν]{.greek-omitted} [βησθαιδα]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν [εις]{.greek-omitted} [προς]{.greek-added} το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν [τω]{.greek-added} μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

[και]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [περιπατουντα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην γεννησαρετ και [προσωρμισθησαν]{.greek-omitted} [προσορμισθησαν]{.greek-added}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

[περιδραμοντες]{.greek-omitted} [παραδραμοντες]{.greek-added} ολην την περιχωρον εκεινην ηρξαντο επι τοις [κραββατοις]{.greek-omitted} [κραβατοις]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου αν εισεπορευετο εις [κωμας]{.greek-omitted} [κομας]{.greek-added} η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου [κοιναις]{.greek-omitted} [κιναις]{.greek-added} [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη [νιψωνται]{.greek-omitted} [νιψωσι]{.greek-added} τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη βαπτισωνται ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν [α]{.greek-omitted} [παρελαβον]{.greek-omitted} κρατειν [βαπτισμους]{.greek-omitted} [βαπτισμον]{.greek-added} ποτηριων και ξεστων και [χαλκιων]{.greek-omitted} [[κ]{.unclear}]{.greek-added} [[χαλκους]{.corr}]{.greek-added} και κλινων[7:4]{.aside}

[και]{.greek-added} επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την παραδοσιν των πρεσβυτερων [αλλα]{.greek-omitted} [αλλ]{.greek-added} ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε [αποκριθεις]{.greek-omitted} [αποκριθης]{.greek-added} ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος [ο]{.greek-omitted} [ο[υ]{.unclear}]{.greek-added} λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με [διδασκοντες]{.greek-omitted} διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα [πολλα]{.greek-added} παρομοια [τοιαυτα]{.greek-omitted} [πολλα]{.greek-omitted} ποιειτε[7:8]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο [εαν]{.greek-omitted} [αν]{.greek-added} εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} [εισπορευομενον]{.greek-omitted} [εις]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [εκπορευομενα]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [εκεινα]{.greek-omitted} [εστιν]{.greek-omitted} [τα]{.greek-omitted} [κοινουντα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[7:15]{.aside}

[ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [εξωθεν]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15 | instance no. 2]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} εις οικον απο του οχλου [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτ[ως]{.unclear} και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου [εις]{.greek-omitted} την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι [το]{.corr} εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ τη[ς]{.unclear} καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος ασελγεια οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα [εσωθεν]{.greek-omitted} [εσωθε]{.greek-added} εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις [την]{.greek-added} οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα [γαρ]{.greek-omitted} [δε]{.greek-added} [[η]{.corr}]{.greek-added} γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εκ της θυγατρος [αυτ[―]{.gap}]{.greek-added} [αυτης]{.corr}[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των [ψυχιων]{.greek-added} [ψιχιων]{.corr} των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος [σ]{.unclear}ου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [ανα]{.greek-omitted} [μεσον]{.greek-omitted} [των]{.greek-omitted} [οριων]{.greek-omitted} [δεκαπολεως]{.greek-omitted}[7:31]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-omitted} [εξελθων]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [οριων]{.greek-omitted} [τυρου]{.greek-omitted} [και]{.greek-omitted} [σιδωνος]{.greek-omitted} ηλθεν προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31 | instance no. 3]{.aside}

και φερουσιν αυτω [κωφον]{.greek-omitted} [κοφον]{.greek-added} μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο τ[ο]{.unclear}υ οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της [γλωσσης]{.greek-omitted} [γλωττης]{.greek-added} αυτου και ελαλει ορθ[ω]{.unclear}ς[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε [αυτος]{.greek-omitted} αυτοις [διεστελλετο]{.greek-omitted} [διεστειλε[το]{.unclear}]{.greek-added} μαλλον περισσοτερον [εκηρυσσον]{.greek-omitted} [εκηρυττον]{.greek-added}[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις παμπολλου οχλου οντος και μη εχοντων τι φαγωσιν προσκαλεσαμενος ο [ιησους]{.greek-abbr} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι [ηδοι]{.greek-added} [ηδη]{.greek-omitted} [ημεραι]{.greek-omitted} τρεις [ημερας]{.greek-added} [προσμενουσιν]{.greek-omitted} [προσμενοσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους [νηστεις]{.greek-omitted} [νηστις]{.greek-added} εις [τον]{.greek-added} οικον αυτων [εκλυθησονται]{.greek-omitted} [εκβλυθησονται]{.greek-added} εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκουσι]{.greek-added}[8:3]{.aside}

και απεκριθησαν [αυτω]{.greek-omitted} οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε [επ]{.greek-added} [ερημιας]{.greek-added} χορτασαι αρτων [επ]{.greek-omitted} [ερημιας]{.greek-omitted}[8:4]{.aside}

και επηρωτα αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αρτους [και]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [[ε]{.unclear}κλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και [παρεθηκαν]{.greek-omitted} [παρεθηκε]{.greek-added} τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παραθειναι και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν [περισσευματα]{.greek-omitted} [περισευματα]{.greek-added} κλασματων [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες [ωσει]{.greek-added} [τετρα]{.greek-added} [ως]{.greek-omitted} [τετρακισχιλιοι]{.greek-omitted} [και]{.greek-omitted} [απελυσεν]{.greek-omitted} [αυτους]{.greek-omitted}[8:9]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [φαγοντες]{.greek-omitted} [ως]{.greek-omitted} [τετρακισχιλιοι]{.greek-omitted} [κ[ισ]{.unclear}χ[ι]{.unclear}λιοι]{.greek-added} και απελυσεν αυτους[8:9 | instance no. 2]{.aside}

και ευθεως εμβας εις το πλοιον μετα των μαθητων αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} εις τα μερη [δαλμανουθα]{.greek-omitted} [σαλμανοθαν]{.greek-added}[8:10]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν αυτω ζητουντες [αυτω]{.greek-added} [παρ]{.greek-omitted} [αυτου]{.greek-omitted} [σημειον]{.greek-omitted} [σημεια]{.greek-added} απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη [μειον]{.greek-added} [σημειον]{.corr}[8:12]{.aside}

και αφεις αυτ[ους]{.unclear} εμβας παλιν εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο [οι]{.greek-added} [[μαθ]{.unclear}ηται]{.greek-added} [α[υτ]{.unclear}ου]{.greek-added} [λ]{.unclear}α[βε]{.unclear}ιν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω π[λ]{.unclear}οιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης [ηρωδου]{.greek-omitted} [η[ρ]{.unclear}ωδιανων]{.greek-added}[8:15]{.aside}

και διελογιζοντο προς αλ[λη]{.unclear}λους [λ]{.unclear}εγοντες [οτι]{.greek-omitted} αρτους ουκ εχομεν[8:16]{.aside}

και γνο[υ]{.unclear}ς ο [ιησους]{.greek-abbr} [λ]{.unclear}εγει αυτ[οι]{.unclear}ς τι δ[ι]{.unclear}αλο[γ]{.unclear}ιζεσ[θε]{.unclear} οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε [αλ[λ]{.unclear}]{.greek-added} ετι πεπωρωμενην εχετε την [καρ]{.unclear}διαν [υμ]{.unclear}ων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετ[ε]{.unclear} και ωτα εχοντες [ου]{.unclear}κ ακουετε και ου μν[η]{.unclear}μονευετε[8:18]{.aside}

[οτε]{.greek-omitted} [οτι]{.greek-added} τους [πεντε]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} αρ[τους]{.unclear} [εκλασα]{.greek-omitted} [[ε]{.unclear}κλασ[αν]{.unclear}]{.greek-added} εις [τους]{.greek-omitted} [τα]{.greek-added} πεντακ[ισ]{.unclear}χιλι[ους]{.greek-supplied} π[οσους]{.greek-supplied} [κοφινους]{.greek-omitted} [[κ]{.unclear}οιφινους]{.greek-added} [κλασματ[ων]{.unclear}]{.greek-added} πληρεις [κλασματων]{.greek-omitted} ηρ[ατε]{.unclear} λεγουσιν αυτω [δωδεκα]{.greek-omitted} [[[ι]{.unclear}β]{.greek-abbr}]{.greek-added}[8:19]{.aside}

[οτε]{.unclear} [δε]{.unclear} τους [επτα]{.greek-supplied} [εις]{.greek-supplied} [τους]{.greek-supplied} [τετρακισχιλιους]{.greek-omitted} [ποσων]{.greek-omitted} [σπυριδων]{.greek-omitted} [πληρωματα]{.greek-omitted} [κλασματων]{.greek-omitted} [ηρατε]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [ειπον]{.greek-omitted} [επτα]{.greek-omitted}[8:20]{.aside}

[[͵δ]{.greek-abbr}]{.greek-added} [οτε]{.greek-omitted} [δε]{.greek-omitted} [τους]{.greek-omitted} [επτα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [τετρακισχιλιους]{.greek-omitted} ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added}[8:20 | instance no. 2]{.aside}

και ελεγεν αυτοις πως ου συνιετ[ε]{.unclear}[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βησθαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρ[ας]{.unclear} αυτω επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα π[α]{.unclear}λιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και αποκατεσταθη και [ενεβλεψεν]{.greek-omitted} [αν[ε]{.unclear}βλεψε]{.greek-added} τηλαυγως [απαντας]{.greek-omitted} [απαντα]{.greek-added}[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων [αυτοις]{.greek-omitted} τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις [υμεις]{.greek-omitted} [δε]{.greek-omitted} [τινα]{.greek-omitted} [με]{.greek-omitted} [λεγετε]{.greek-omitted} [ειναι]{.greek-omitted} [αποκριθεις]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [συ]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted}[8:29]{.aside}

[και]{.greek-omitted} [επετιμησεν]{.greek-omitted} [αυτοις]{.greek-omitted} ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγουσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και των αρχιερεων και των γραμματεων και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[8:34]{.aside}

[ος]{.greek-omitted} [γαρ]{.greek-omitted} [ως]{.greek-added} [δ]{.greek-added} αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την εαυτου ψυχην ενεκ[εν]{.unclear} εμου και του ευαγγελιου ουτος σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} εαν κερδηση τον κοσμον ολον και [ζημιωθη]{.greek-omitted} [ζημιωθηναι]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαι[σ]{.unclear}χυνθ[η]{.unclear} με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο [υις]{.greek-added} [υιος]{.corr} του [ανθρωπου]{.greek-abbr} [επαισχυνθησεται]{.greek-omitted} αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτο[ι]{.unclear}ς αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων ο[ι]{.unclear}τινες ου μη γευσωνται θανατου εως [αν]{.greek-omitted} [ου]{.greek-added} [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας [εξ]{.greek-omitted} [[ϛ]{.greek-abbr}]{.greek-added} παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} [ιακωβον]{.greek-omitted} [ιακοβον]{.greek-added} και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} στιλβοντα λευκα λιαν ως χιων οια γναφευς επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωσει]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις [ο]{.greek-omitted} πετρος λεγει τω [ιησου]{.greek-abbr} [ραββι]{.greek-omitted} [ραμβι]{.greek-added} καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μω[υ]{.unclear}ση]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβο[ι]{.unclear}[9:6]{.aside}

και εγενετο νεφ[ελη]{.unclear} επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτο[υ]{.unclear} ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων [δε]{.greek-omitted} [αυτων]{.greek-omitted} [αυτον]{.greek-added} απο του ορους διεστειλατο αυτοις ινα μηδενι διηγησωνται α ειδον ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι εστιν το εκ νεκρων αναστηναι[9:10]{.aside}

και [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα και πως γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [και]{.greek-omitted} [εποιησαν]{.greek-omitted} [αυτω]{.greek-omitted} [οσα]{.greek-omitted} [ηθελησαν]{.greek-omitted} [καθως]{.greek-omitted} [γεγραπται]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted}[9:13]{.aside}

[αλλα]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [και]{.greek-omitted} [ηλιας]{.greek-omitted} εληλυθεν και εποιησαν αυτω οσα [ηθελο[ν]{.unclear}]{.greek-added} [ηθελησαν]{.corr} καθως γεγραπται επ αυτον[9:13 | instance no. 2]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτ[οις]{.unclear}[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και επηρωτησεν τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε ηνεγκα τον υιον μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα [αυτο]{.greek-omitted} [εκβαλωσιν]{.greek-omitted} [εκβαλλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσ[ω]{.unclear}ν επι της γης εκ[υ]{.unclear}λιετο αφριζων[9:20]{.aside}

και επηρωτησεν τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.corr} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του [παιδιου]{.greek-omitted} [παιδος]{.greek-added} μετα δακρυων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [συντρεχει]{.greek-added} [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις [αυτον]{.greek-omitted} [αυτο]{.greek-added}[9:25]{.aside}

και [κραξαν]{.greek-omitted} [κραξας]{.greek-added} και πολλα [σπαραξαν]{.greek-omitted} [σπαραξας]{.greek-added} αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον κατ ιδιαν οτι [δια]{.greek-added} [τι]{.greek-added} ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος [εν]{.greek-omitted} [ουδενι]{.greek-omitted} [ουδεν]{.greek-added} δυναται [εξελθειν]{.greek-omitted} [διεξελθειν]{.greek-added} ει μη εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της [γαλιλαιας]{.greek-omitted} [γαληνης]{.greek-added} και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο [επερωτησαι]{.greek-added} αυτον [επερωτησαι]{.greek-omitted}[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους [διαλογιζεσθαι]{.greek-added} [διελογιζεσθε]{.greek-omitted} [[διαλογιζεσθε]{.corr}]{.greek-added}[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και λεγει [αυτους]{.greek-added} [αυτοις]{.corr} ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και [εναγκαλισαμενος]{.greek-omitted} [αναγκαλισαμενος]{.greek-added} αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε [δεχηται]{.greek-added} [δεξηται]{.corr} ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε αυτω [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} λεγων διδασκαλε ειδομεν τινα [εν]{.greek-added} τω ονοματι σου εκβαλλοντα δαιμονια ος [ουκ]{.greek-omitted} ακολουθει ημιν και εκωλυσαμεν αυτον οτι [ετι]{.greek-added} ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ [κακολογησαι]{.greek-omitted} [κακολογησε]{.greek-added} με[9:39]{.aside}

ος γαρ ουκ εστιν καθ [υμων]{.greek-omitted} [ημων]{.greek-added} υπερ [υμων]{.greek-omitted} [ημων]{.greek-added} εστιν[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} [εστε]{.greek-omitted} [εσται]{.greek-added} αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεσει]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων εις εμε καλον εστιν [αυτω]{.greek-omitted} μαλλον ει περικειται λιθος μυλικος περι τον τραχηλ[ον]{.greek-supplied} αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλιζη]{.greek-omitted} [σκανδαλιση]{.greek-added} σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [σοι]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ [αυτων]{.greek-omitted} ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ [πυρι]{.greek-omitted} [αλισθησεται]{.greek-omitted} [και]{.greek-omitted} [πασα]{.greek-omitted} [θυσια]{.greek-omitted} [αλι]{.greek-omitted} [αλισθησεται]{.greek-omitted}[9:49]{.aside}

[πας]{.greek-omitted} [γαρ]{.greek-omitted} [πυρι]{.unclear} αλισθησεται και πασα θυσια αλι αλισθησεται[9:49 | instance no. 2]{.aside}

καλον [δε]{.greek-added} το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε [εχετε]{.greek-omitted} [εχη[τε]{.greek-supplied}]{.greek-added} εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας [δια]{.greek-omitted} [εις]{.greek-added} [του]{.greek-omitted} [το]{.greek-added} περαν του ιορδαν[ου]{.unclear} και συμπ[ο]{.unclear}ρευονται [παλιν]{.greek-omitted} [πα[ντ]{.unclear}ες]{.greek-added} οχλοι προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[[10:1 *(lacunose)*]{.lacunose}]{.aside}

[και]{.unclear} προσελθοντες [οι]{.greek-added} φαρισ[αιοι]{.unclear} επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπ[εν]{.unclear} αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυ[ν]{.unclear}αικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα μια σαρξ[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [τουτου]{.greek-added} [του]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [ηρωτησαν]{.greek-added} αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν απολυσ[η]{.unclear} την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη αλλω [μοιχαται]{.greek-omitted}[10:12]{.aside}

[και]{.greek-omitted} [εαν]{.greek-omitted} [γυνη]{.greek-omitted} [απολυση]{.greek-omitted} [τον]{.greek-omitted} [ανδρα]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [γαμηθη]{.greek-omitted} [αλλω]{.greek-omitted} μοιχαται[10:12 | instance no. 2]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε [μαθηται]{.greek-omitted} [μαθεται]{.greek-added} επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} ηγανακτησεν και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηυλογη]{.greek-added} αυτα[10:16]{.aside}

και εκπορευο[μενου]{.unclear} αυτου εις οδον προσδραμων εις και γο[ν]{.unclear}[υπετησ]{.greek-supplied}[ας]{.unclear} αυτο[ν]{.unclear} [επηρωτα]{.greek-omitted} [επρωτησεν]{.greek-added} [[επηρωτησεν]{.corr}]{.greek-added} αυτον διδασκαλε αγαθε τι [ποιη]{.unclear}[σω]{.greek-supplied} [ινα]{.unclear} ζωην α[ι]{.unclear}ωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη [ψευδομαρτυρησης]{.greek-omitted} [ψευδομαρτυρησεις]{.greek-added} [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μ[ου]{.unclear}[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} [εμβλεψας]{.greek-omitted} [αναβλεψας]{.greek-added} αυτω ηγαπησεν [αυτων]{.greek-added} [αυτ[ο]{.unclear}ν]{.corr} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} αυτω εν σοι υστερει υπαγε οσα εχεις [π]{.unclear}ωλη[σον]{.greek-supplied} και δος πτωχοις και εξεις θησαυρ[ον]{.unclear} εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} ακολουθει μοι αρα[ς]{.unclear} τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα [χ]{.unclear}ρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον εστιν τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον εστιν καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε π[ε]{.unclear}ρι[σσως]{.unclear} εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} [τουτω]{.greek-added} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} [παντα]{.greek-supplied} [γαρ]{.greek-supplied} [δυνα]{.greek-supplied}[τ]{.unclear}α [εστιν]{.greek-omitted} [πα]{.unclear}ρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω [οικιας]{.greek-omitted} [οικους]{.greek-added} και αδελφους και αδελφας και [μητερας]{.greek-omitted} [γυναικας]{.greek-added} και τεκνα [και]{.greek-added} [[μητερας]{.greek-abbr}]{.greek-added} και αγρους μετα διωγμων και [εν]{.greek-supplied} [τω]{.greek-supplied} αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται [οι]{.greek-added} πρωτοι εσχατοι και [οι]{.greek-added} εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [λεγειν]{.greek-added} αυτοις [λεγειν]{.greek-omitted} τα μελλοντα [αυτω]{.greek-omitted} [αυτοις]{.greek-added} συμβαινειν[10:32]{.aside}

οτι ιδου αναβαιν[ο]{.unclear}μεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδοθησεται]{.greek-omitted} [παραδιδοται]{.greek-added} τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις εθνεσιν [[εθνεσι]{.corr}]{.greek-added}[10:33]{.aside}

και εμπαιξουσιν αυτω [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [τη]{.greek-omitted} [τριτη]{.greek-omitted} [ημερα]{.greek-omitted} [αναστησεται]{.greek-omitted}[10:34]{.aside}

[και]{.greek-omitted} [εμπαιξουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [μαστιγωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34 | instance no. 2]{.aside}

και προσπορευονται αυτω [ιακωβος]{.greek-omitted} [ιακοβος]{.greek-added} και [[ιω]{.greek-abbr}]{.greek-added} [ιωαννης]{.greek-omitted} [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε [θε]{.unclear}λομεν [ινα]{.greek-omitted} ο εαν αιτησωμεν [ινα]{.greek-added} ποιησης ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε ποιησαι με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων [κατακυριευουσιν]{.greek-omitted} [κατακυριευσουσιν]{.greek-added} αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη [γενεσθαι]{.greek-added} υμων [γενεσθαι]{.greek-omitted} πρωτος εσται παντων δουλος[10:44]{.aside}

και [γαρ]{.greek-omitted} ο υιος του [ανθρωπου]{.greek-abbr} ουκ [η]{.unclear}λθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και [ερχονται]{.greek-omitted} [ερχεται]{.greek-added} εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο [ναζωραιος]{.greek-omitted} [ναζοραιος]{.greek-added} εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} δαυιδ [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν [υιε]{.greek-omitted} [[υιος]{.greek-abbr}]{.greek-added} δαυιδ ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον [τ[ου]{.unclear}φλον]{.greek-added} [τυφλον]{.corr} λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος ειπεν [αυτω]{.greek-omitted} [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} εις βηθσφαγη και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [εκαθισε]{.greek-added} [κεκαθικεν]{.greek-omitted} [[κεκαθικε]{.corr}]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και [εαν]{.greek-omitted} [αν]{.greek-added} τις υμιν ειπη τι πο[ι]{.unclear}ειτε [τουτο]{.greek-omitted} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εσ[τ]{.unclear}ηκοτων [ελεγον]{.greek-omitted} [λεγουσιν]{.greek-added} αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο [ημιν]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και [επεβαλον]{.greek-omitted} [επεβ[α]{.unclear}βαλλον]{.greek-added} αυτω τα ιματια αυτων και εκαθισεν επ [αυτω]{.greek-omitted} [αυτων]{.greek-added}[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} εκοπτον [στιβαδας]{.greek-added} εκ των δενδρων και εστρωννυ[ον]{.unclear} εις την οδον[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων δαυιδ ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα [ο]{.greek-omitted} [ιησους]{.greek-omitted} και εις το ιερον και περιβλεψαμενος [παντα]{.greek-omitted} [παντας]{.greek-added} οψιας ηδη ουσης [της]{.greek-omitted} [ωρας]{.greek-omitted} εξηλθεν εις βηθανιαν μετα [τω]{.greek-added} [των]{.corr} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο [της]{.greek-added} βηθανιας [επεινασεν]{.greek-omitted} [επεινα[σ]{.unclear}ε]{.greek-added}[11:12]{.aside}

και ιδων [συκην]{.greek-omitted} μακροθεν εχουσαν φυλλα ηλθεν [ινα]{.greek-added} [ει]{.greek-omitted} [αρα]{.greek-omitted} ευρησει τι εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη μηκετι εκ σου [καρπος]{.greek-added} [γενηται]{.greek-added} εις τον αιωνα [μηδεις]{.greek-omitted} [μηδε]{.greek-added} [τις]{.greek-added} καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και [ερχονται]{.greek-omitted} [ερχεται]{.greek-added} εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους [πωλουντας]{.greek-omitted} [πολουντας]{.greek-added} και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας καθεδρας [των]{.unclear} [πωλουντων]{.greek-omitted} [πωλλουντων]{.greek-added} τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ [η]{.unclear}φιεν ινα τις διενεγκη σκευος [δια]{.greek-omitted} [του]{.greek-omitted} [ιερου]{.greek-omitted}[11:16]{.aside}

[και]{.greek-omitted} [ουκ]{.greek-omitted} [ηφιεν]{.greek-omitted} [ινα]{.greek-omitted} [τις]{.greek-omitted} [διενεγκη]{.greek-omitted} [σκευος]{.greek-omitted} [δια]{.greek-supplied} [του]{.greek-supplied} ιερ[ου]{.greek-supplied}[11:16 | instance no. 2]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης [κ]{.unclear}λη[θ]{.unclear}ησεται [πασιν]{.greek-omitted} [παρα]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε [αυτον]{.greek-omitted} [αυτων]{.greek-added} σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι γραμματεις και οι αρχιερεις [κ]{.unclear}αι εζητουν πως αυτον [απολεσωσιν]{.greek-omitted} [απολεσουσιν]{.greek-added} εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και οτε [εγενετο]{.greek-added} οψε [εγενετο]{.greek-omitted} εξεπορευετο εξω της [π]{.unclear}ολεω[ς]{.unclear}[11:19]{.aside}

και πρωι παραπορευομενοι ειδον την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε [πιστιν]{.unclear} [θεου]{.greek-abbr}[11:22]{.aside}

αμην [γαρ]{.greek-omitted} λε[γω]{.unclear} υμιν οτι [ο]{.unclear}ς αν ειπη τω ο[ρ]{.unclear}ει τουτω αρθητι και βληθητι εις την θαλασσαν [και]{.unclear} μη διακριθη εν τη καρδια αυτου [αλλ]{.unclear}α [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν [αιτεισθε]{.greek-added} προσευχομενοι [αιτησθε]{.greek-omitted} πιστευετε οτι λαμβανετε και [εσται]{.greek-omitted} [εστε]{.greek-added} υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκειτε]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} [[[πατηρ]{.greek-abbr}]{.corr}]{.greek-added} [υ]{.unclear}μων ο εν τοις [ουρανοις]{.greek-abbr} [αφησει]{.greek-added} [αφη]{.greek-omitted} [υμιν]{.greek-omitted} τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} [υ]{.unclear}μων ο εν τοις [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω [ιερω]{.greek-omitted} [ει[ε]{.unclear}ρω]{.greek-added} περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις [και]{.unclear} οι γραμματ[εις]{.unclear} και οι πρε[σβυ]{.unclear}τεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα ποιης[11:28]{.aside}

ο [δ]{.unclear}ε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας και εγω ενα λογον και αποκριθητε μοι και ερω υμιν εν π[οια]{.unclear} εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} [αποκριθητε]{.greek-omitted} [μοι]{.greek-omitted}[11:30]{.aside}

και ελογιζοντο προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ ειχον τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και ωκοδομησεν πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και απεστειλεν προς τους γεωργους τω καιρω δουλον ινα [παρα]{.greek-omitted} [περι]{.greek-added} των γεωργων λαβη απο του καρπου του αμπελω[νος]{.unclear}[12:2]{.aside}

[οι]{.unclear} [δε]{.unclear} [λα]{.unclear}βοντες αυτον εδειραν [αυτον]{.greek-added} και απεστειλαν κενον[12:3]{.aside}

[κα]{.greek-added} [και]{.corr} παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον [λ]{.unclear}ιθοβολησαντες εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον απεστειλεν κακεινον απεκτειναν και πολλους [και]{.greek-added} αλλους τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα υιον [εχων]{.greek-omitted} [εχ[ο]{.unclear}ν]{.greek-added} αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον προς αυτους [εσ]{.unclear}χατον λεγων οτι [εντραπησονται]{.greek-omitted} [εντραπησωνται]{.greek-added} τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς [εαυ]{.unclear}τους [ο[―]{.gap}]{.greek-added} [οτι]{.greek-omitted} [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες [αυ]{.unclear}τον απ[εκ]{.unclear}τειναν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του [αμπελωνος]{.greek-omitted} [απελωνος]{.greek-added} ελ[ευ]{.unclear}σεται και απολεσει τους γεωργους και δωσει τον α[μ]{.unclear}πελωνα αλλοις[12:9]{.aside}

ουδε την γρα[φ]{.unclear}ην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς [αυτος]{.greek-added} [αυτους]{.corr} την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι αληθης ει και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δωμα]{.greek-added} [η]{.greek-added} [[μη]{.corr}]{.greek-added} [δωμα]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασ[αν]{.unclear} επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες [λεγουσιν]{.greek-omitted} [λεγου[σ]{.unclear}ι]{.greek-added} αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη αφ[η]{.unclear} ινα λαβη ο αδελφος αυτου την γυναικα αυτου και εξαναστηση σπερμα τω αδελφω αυτου[12:19]{.aside}

επ[τ]{.unclear}α αδελφοι ησαν και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} [την]{.greek-added} γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο [δευτερος]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added} ελαβεν αυτ[η]{.unclear}ν [και]{.greek-omitted} [απεθανεν]{.greek-omitted} [και]{.greek-omitted} [ουδε]{.greek-omitted} [αυτος]{.greek-omitted} [αφηκεν]{.greek-omitted} [σπερμα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [τριτος]{.greek-omitted} [ωσαυτως]{.greek-omitted}[12:21]{.aside}

[και]{.greek-omitted} [ελαβον]{.greek-omitted} [αυτην]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος [αυτων]{.greek-omitted} εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [ου]{.greek-omitted} δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [εγαμισκονται]{.greek-added} αλλ εισιν ως αγγελοι οι εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω μωσεως επι [του]{.greek-omitted} [της]{.greek-added} βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και [ο]{.greek-omitted} [θεος]{.greek-omitted} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-abbr} ζωντων υμεις ουν [πολυ]{.greek-omitted} πλανασθε[12:27]{.aside}

και προσελθων εις των γραμματεων ακουσας αυτων [συζητουντων]{.greek-omitted} [συζυτουντων]{.greek-added} ειδως οτι καλως αυτ[ο]{.unclear}ις απεκριθη επηρωτησεν αυτον ποια εστιν [πρωτη]{.greek-omitted} παντων εντολη [μειζων]{.greek-added}[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} [απεκριθη]{.greek-omitted} [ειπεν]{.greek-added} αυτω οτι πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [ακουε]{.greek-omitted} [ισραηλ]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ημων]{.greek-omitted} [κυριος]{.greek-omitted} [εις]{.greek-omitted} [εστιν]{.greek-omitted}[12:29]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [απεκριθη]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [πρωτη]{.greek-omitted} [παντων]{.greek-omitted} των εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις εστιν[12:29 | instance no. 2]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου [και]{.unclear} [ε]{.unclear}ξ ολης της διανοιας σου και εξ ολ[ης]{.unclear} της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

[και]{.greek-omitted} [δευτερα]{.greek-omitted} [ομοια]{.greek-omitted} [αυτη]{.greek-omitted} [αγαπησεις]{.greek-omitted} [τον]{.greek-omitted} [πλησιον]{.greek-omitted} [σου]{.greek-omitted} [ως]{.greek-omitted} [σεαυτον]{.greek-omitted} [μειζων]{.greek-omitted} [τουτων]{.greek-omitted} αλλη [εντολη]{.greek-omitted} ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [συνεσεως]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} [και]{.greek-omitted} εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων [αυτον]{.greek-omitted} οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον [επερωτησε]{.greek-added} [επερωτησαι]{.corr}[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι [ουχι]{.greek-added} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [υιος]{.greek-abbr} εστιν δαυιδ[12:35]{.aside}

αυτος γαρ δαυιδ ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν δαυιδ λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου εστιν και ο πολυς οχλος ηκουεν αυτου η[δ]{.unclear}εως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις [περιπατειν]{.greek-omitted} [περιπεριπατειν]{.greek-added} και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθε[δ]{.unclear}ριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των [χηρων]{.greek-omitted} [[χ]{.unclear}ειρων]{.greek-added} και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του [γαζοφυλακιου]{.greek-omitted} [γαζοφιλακιου]{.greek-added} εθε[ω]{.unclear}ρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλλε]{.greek-added} λεπτα δυο ο εστιν κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις [εβαλον]{.greek-omitted} [εβαλλον]{.greek-added} αυτη δε εκ της υστερησεως [αυτης]{.greek-omitted} παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι λιθω ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των [ελαιων]{.greek-omitted} [ελεων]{.greek-added} κατεναντι του ιερου [επηρωτων]{.greek-omitted} [επηρωτα]{.greek-added} αυτον [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} πετρος και ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται [επι]{.greek-omitted} [εν]{.greek-added} τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} [γαρ]{.greek-added} ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ [υμας]{.greek-omitted} [ημας]{.greek-added} εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατ[―]{.gap}]{.greek-added} [προμεριμνατε]{.corr} τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} μηδε μελετατε αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε [ιδητε]{.greek-omitted} [ειδητε]{.greek-added} το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο [αναγινωσκων]{.greek-omitted} [αναγινωκων]{.greek-added} νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω [αραι]{.greek-omitted} [τι]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [οικιας]{.greek-omitted} [αυτου]{.greek-omitted}[13:15]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [δωματος]{.greek-omitted} [μη]{.greek-omitted} [καταβατω]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [μηδε]{.greek-omitted} [εισελθετω]{.greek-omitted} αραι τ[ι]{.unclear} [ε]{.unclear}κ της οικιας αυτου[13:15 | instance no. 2]{.aside}

[και]{.greek-omitted} ο [δε]{.greek-added} εις τον αγρον ων μη επιστρ[ε]{.unclear}ψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχομενοι]{.greek-added} δε ινα μη γενηται η φυγη [[η]{.unclear}μων]{.greek-added} [υμων]{.corr} χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι [θλιψις]{.greek-omitted} [θλιψ[―]{.gap}ς]{.greek-added} [[θλιψης]{.corr}]{.greek-added} οια ου γεγονεν [τοιαυτη]{.greek-omitted} απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτ[ο]{.unclear}υς [εκολοβωσ[ε]{.unclear}]{.greek-added} ους εξελεξατο [εκολοβωσεν]{.greek-omitted} τας ημερας[13:20]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη πιστευετε[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και δωσουσιν σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκ[λεκ]{.unclear}τους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η [σεληνη]{.unclear} [ου]{.unclear} δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες [τ]{.unclear}ου [ουρανου]{.greek-abbr} [εσονται]{.greek-omitted} εκπιπτοντες και αι δυναμεις [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [αι]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν [εφελαις]{.greek-added} [[ν]{.unclear}εφελαις]{.corr} μετα δυναμεως πολλης και δοξης[13:26]{.aside}

και [τοτε]{.greek-omitted} αποστελει τους αγγελους [αυτου]{.greek-omitted} και επισυναξ[ει]{.unclear} τους [εκλεκτους]{.greek-omitted} [αγγελους]{.greek-added} αυτου εκ των τεσσαρων ανεμων απ ακρου [της]{.greek-added} γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης [ηδη]{.greek-omitted} ο κλαδος απαλος γενηται και [εκφυη]{.greek-omitted} τα φυλλ[α]{.unclear} [εκφυη]{.greek-added} γινωσκετε οτι [εγγυς]{.greek-omitted} το θερος [εγγυς]{.greek-added} εστιν[13:28]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσ[ε]{.unclear}ται οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκ[ει]{.unclear}νης [η]{.greek-omitted} [και]{.greek-added} [της]{.greek-added} ωρας [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} ουδε οι αγγελοι οι εν [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε κα[ι]{.unclear} προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικι[αν]{.unclear} αυτου και δους τοις [δ]{.unclear}ουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο ινα [γρηγορη]{.unclear}[13:34]{.aside}

[γρη]{.unclear}γορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε [η]{.unclear} [με]{.unclear}σονυκτιου η αλεκτο[ρο]{.unclear}φωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη [υ]{.unclear}μας καθευδοντας[13:36]{.aside}

α δε υμιν λεγω πασιν [λεγω]{.greek-omitted} γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως [αυτον]{.greek-omitted} εν δολω [αυτον]{.greek-added} κρατησαντες [απ]{.unclear}οκτ[εινωσιν]{.unclear}[14:1]{.aside}

[ε]{.unclear}λεγον [δε]{.greek-omitted} [[γαρ]{.unclear}]{.greek-added} μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν βηθα[νια]{.unclear} εν [τη]{.greek-omitted} [ο]{.unclear}ικια σιμωνο[ς]{.unclear} του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου [πιστ]{.unclear}ικη[ς]{.unclear} [πολυ]{.unclear}τελους και συντριψασα το αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τ[ι]{.unclear}νες [αγανακτουν]{.unclear}τες προς εαυτους και λεγοντες εις τι η [απωλεια]{.greek-omitted} [απ[ω]{.unclear}λια]{.greek-added} αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο [πρ]{.unclear}αθηναι επαν[ω]{.unclear} τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπ[εν]{.unclear} αφετε αυτην τι αυτη κοπους παρεχετε καλον [[γαρ]{.unclear}]{.greek-added} εργον [ειργασατο]{.greek-omitted} [[ηργα]{.unclear}σατο]{.greek-added} εν [ε]{.unclear}μοι[14:6]{.aside}

π[αντοτε]{.unclear} [γαρ]{.unclear} τ[ο]{.unclear}υς [πτωχους]{.unclear} εχε[τ]{.unclear}ε μεθ εαυτων και οταν θελητε δυνασθε [αυτους]{.greek-omitted} [αυτων]{.greek-added} [ευ]{.unclear} ποιησαι εμε δε ου παν[τοτε]{.unclear} εχετε[14:7]{.aside}

[ο]{.greek-omitted} [εσχεν]{.greek-omitted} [οπερ]{.greek-added} [γ[α]{.unclear}ρ]{.greek-added} αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβ[ε]{.unclear}]{.greek-added} μυρισαι [μου]{.greek-omitted} το σω[μα]{.unclear} [[μου]{.unclear}]{.greek-added} εις [τ]{.unclear}ον [εν]{.unclear}[ταφι]{.greek-supplied}[ασ]{.unclear}μον[14:8]{.aside}

[αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οπου]{.greek-omitted} [εαν]{.greek-omitted} [κηρυχθη]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [τουτο]{.greek-omitted} [εις]{.greek-omitted} [ολον]{.greek-omitted} [τον]{.greek-omitted} [κοσμον]{.greek-omitted} και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} [ιουδας]{.greek-omitted} [ιδα[ς]{.unclear}]{.greek-added} ο ισκαριωτης εις των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} απηλθεν προς τ[ους]{.unclear} αρχιερεις ινα παραδω αυτον αυτο[ι]{.unclear}ς[14:10]{.aside}

οι δε ακουσαντες εχαρησαν [και]{.greek-omitted} επηγγειλαντο αυτ[ω]{.unclear} [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη [η]{.unclear}μερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θε[λ]{.unclear}εις απ[ελ]{.unclear}θοντες [ετοιμασωμεν]{.greek-omitted} [ετοιμασ[ο]{.unclear}μεν]{.greek-added} ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυ[τοις]{.greek-supplied} υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν [δ]{.unclear}ει[ξ]{.unclear}[ει]{.greek-supplied} [ανωγεον]{.greek-omitted} [ανωγαιον]{.greek-added} μεγα εστρωμενον [ετοιμον]{.greek-omitted} εκει ετοιμασατε [ημιν]{.greek-omitted} [υμιν]{.greek-added}[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και [ητοιμασαν]{.greek-omitted} [οιτοιμασαν]{.greek-added} το [πασχα]{.greek-omitted}[14:16]{.aside}

[και]{.greek-omitted} [εξηλθον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [ευρον]{.greek-omitted} [καθως]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [ητοιμασαν]{.greek-omitted} [το]{.greek-omitted} πασχα[14:16 | instance no. 2]{.aside}

και οψιας γενομενης ερχεται μετα των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added}[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω [και]{.greek-omitted} [αλλος]{.greek-omitted} [μητι]{.greek-omitted} [εγω]{.greek-omitted}[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει [καθως]{.greek-omitted} [καθος]{.greek-added} γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ [εγεν[η]{.unclear}θη]{.greek-added} [εγεννηθη]{.corr} ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας εκλασεν και εδωκεν αυτοις και ειπεν λαβετε φαγετε τουτο εστιν το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον ευχαριστησας εδ[ωκεν]{.unclear} αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο εστιν [το]{.greek-omitted} [αιμα]{.greek-omitted} [μου]{.greek-omitted} το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οτι ουκετι ου μη πιω εκ του [γενηματος]{.greek-omitted} [γεννηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησ[εσ]{.unclear}θε [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμη[ν]{.unclear} λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν [η]{.greek-omitted} [δις]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} [τρις]{.greek-omitted} [απαρνηση]{.greek-omitted} [με]{.greek-omitted}[14:30]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [σοι]{.greek-omitted} [οτι]{.greek-omitted} [συ]{.greek-omitted} [σημερον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} [πριν]{.greek-omitted} η δις αλεκτορα φωνησαι τρις απαρνηση με[14:30 | instance no. 2]{.aside}

ο δε [πετρος]{.greek-added} εκπερισσου [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν [δεη]{.greek-added} με [δεη]{.greek-omitted} συναποθανειν σοι ου μη σε απαρνησωμαι [ωσαυτως]{.greek-omitted} [οσαυτως]{.greek-added} [δε]{.greek-omitted} και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα [ο]{.corr} [πατηρ]{.greek-abbr} παντα [σοι]{.greek-added} δυνατα [σοι]{.greek-omitted} παρενεγκ[ε]{.unclear} το ποτηριον απ [εμ]{.unclear}ου τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το [μεν]{.greek-omitted} [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν [αυτ[ο]{.unclear}ς]{.greek-added} [αυτους]{.corr} παλιν καθευδοντας [[καθευδοντας]{.corr}]{.greek-added} [και]{.greek-added} [λεγει]{.greek-added} [τω]{.greek-added} [πετρω]{.greek-added} [σιμων]{.greek-added} [καθευδεις]{.greek-added} [ουκ]{.greek-added} [ισχυσας]{.greek-added} [μιαν]{.greek-added} [ωραν]{.greek-added} [γρηγορησαι]{.greek-added} ησαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ ηδεισαν τι αυτω [αποκριθη[σον]{.unclear}ται]{.greek-added} [αποκριθωσιν]{.greek-omitted} [[αποκριθωσι]{.corr}]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε λοιπον και αναπαυεσθε απεχει [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος εστιν κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων [αυτω]{.greek-omitted} λεγει αυτω ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε [επεβαλον]{.greek-omitted} [επεβαλ[λ]{.unclear}ον]{.greek-added} επ αυτον τας χειρας [αυτων]{.greek-omitted} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις [των]{.greek-omitted} παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς [υμας]{.greek-omitted} [ημας]{.greek-added} εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι [δε]{.greek-omitted} αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι [μαρτυριαι]{.corr} ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντο[ς]{.unclear} οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και [δια]{.greek-omitted} [τριων]{.greek-omitted} [ημερων]{.greek-omitted} αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και [ουδε]{.greek-omitted} [ουδ]{.greek-added} ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον επηρωτησεν τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι [σου]{.greek-omitted} [σοι]{.greek-added} καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς [διαρρηξας]{.greek-omitted} [διαριξας]{.greek-added} τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της [βλασφημιας]{.greek-omitted} [βλασφιμιας]{.greek-added} τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν [αυτου]{.greek-added} το προσωπον [αυτου]{.greek-omitted} και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν αυτον εβαλλον[14:65]{.aside}

και οντος του πετρου εν τη αυλη [κατω]{.greek-omitted} [ερχεται]{.greek-omitted} [κατερχεται]{.greek-added} [μι]{.unclear}α των παιδισκων του αρχιερ[εως]{.unclear}[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο [δ]{.unclear}ε ηρνησατο [λεγων]{.unclear} ουκ οιδα ουδε επισταμαι τι συ λεγεις [και]{.unclear} εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκ[η]{.unclear} ιδουσα αυτον [π]{.unclear}αλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστικοσιν]{.greek-added} οτι ουτος εξ αυτων [εστιν]{.unclear}[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλ[ιν]{.unclear} [οι]{.unclear} παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια [σου]{.unclear} ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομ[νυειν]{.unclear}]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λ[εγετ]{.unclear}ε[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και [ανεμνησθη]{.greek-omitted} [εμνησθη]{.greek-added} ο πετρος το ρημα ο ειπ[εν]{.unclear} αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι δις απαρνηση με τρις [και]{.unclear} επιβαλων [εκλαιεν]{.greek-omitted} [εκλαι[ε]{.unclear}]{.greek-added}[14:72]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συν[εδ]{.unclear}ριον δ[η]{.unclear}σαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και πα[ρε]{.unclear}δωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν [αυτον]{.greek-omitted} ο πιλατος [αυτον]{.greek-added} συ ει ο βασιλευς [των]{.unclear} [ιουδαιων]{.unclear} ο δε [αποκ]{.unclear}ριθεις [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω συ λεγεις[15:2]{.aside}

[και]{.greek-supplied} κατηγ[ο]{.unclear}ρουν αυτο[υ]{.unclear} [οι]{.unclear} αρχ[ιερ]{.unclear}εις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [[α]{.unclear}πεκρινατο]{.greek-added}[15:3]{.aside}

[ο]{.unclear} [δε]{.greek-supplied} [π]{.unclear}ιλατος [παλιν]{.greek-omitted} επηρωτησεν αυτον [λεγ]{.unclear}ων ουκ αποκρινη ουδεν [ιδε]{.greek-omitted} [ποσα]{.greek-omitted} [σου]{.greek-omitted} [καταμαρτυρουσιν]{.greek-omitted}[15:4]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [πιλατος]{.greek-omitted} [παλιν]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} [ουκ]{.greek-omitted} [αποκρινη]{.greek-omitted} [ουδεν]{.greek-omitted} ιδε ποσα σου καταμαρτυρουσιν[15:4 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι [ουδεν]{.greek-omitted} [ουκ]{.greek-added} απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον ονπερ ητουντο[15:6]{.aside}

ην δε ο λεγομενος [βαραββας]{.greek-omitted} [βαραβας]{.greek-added} μετα των [συστασιαστων]{.greek-omitted} [στασιαστων]{.greek-added} δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν [τον]{.greek-omitted} βασιλεα των ιουδαιων[15:9]{.aside}

[εγηνωκε]{.greek-added} [εγινωσκεν]{.greek-omitted} [[εγηνωσκε]{.corr}]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδωκεισαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεστησαν]{.greek-added} τον οχλον ινα μαλλον τον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε π[οι]{.unclear}ησω ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν [ε]{.unclear}κραξαν [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περι[σ]{.unclear}σως]{.greek-added} [ε]{.unclear}κραξαν [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος [το]{.greek-added} [ικανον]{.greek-added} τω οχλω [το]{.greek-omitted} [ικανον]{.greek-omitted} [ποιησαι]{.greek-omitted} απελυσεν αυτοις τον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} και παρεδωκεν τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγ[ο]{.unclear}ν αυτον εσω της αυλης ο εστιν πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον [και]{.greek-added} [λεγειν]{.greek-added} χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον [αυτου]{.greek-omitted} την κεφαλην [αυτου]{.greek-added} καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και [οτε]{.greek-omitted} [οταν]{.greek-added} ενεπαιξαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον την πορφυραν και ενεδ[υ]{.unclear}σαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-omitted} [[στρωσωσιν]{.greek-abbr}]{.greek-added} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχο[μενον]{.unclear} α[π]{.unclear} αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

[και]{.unclear} φερουσιν αυτον επι [γολγοθα]{.greek-omitted} [γολγοθαν]{.greek-added} τοπον ο εστιν μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην [η]{.greek-omitted} επιγραφη της αιτιας [αυτου]{.greek-omitted} επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-abbr} [[[στρουσι]{.greek-abbr}]{.corr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των [γραματ[αι]{.unclear}ων]{.greek-added} [γραμματ[ε]{.unclear}ων]{.corr} ελεγον αλλους [ε]{.unclear}σωσεν [ε]{.unclear}αυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι [συνεσταυρωμενοι]{.greek-abbr} αυτω [ωνειδιζον]{.greek-omitted} [ωνιδιζον]{.greek-added} αυτον[15:32]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας [εκτης]{.greek-omitted} [[ϛ]{.greek-abbr}]{.greek-added} σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [[θ]{.greek-abbr}]{.greek-added}[15:33]{.aside}

και τη ωρα τη [ενατη]{.greek-omitted} [[θ]{.greek-abbr}]{.greek-added} [εβοησεν]{.greek-omitted} [εβοησε]{.greek-added} ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελ[ω]{.unclear}ι ελωι λιμα [σαβαχθανι]{.greek-omitted} [σαβαχθανη]{.greek-added} ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου [εις]{.greek-omitted} τι με [εγκατελιπες]{.greek-omitted} [εγατελιπες]{.greek-added}[15:34]{.aside}

και τινες των παρεστηκοτων [ακουσαντες]{.greek-omitted} ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτ[ον]{.unclear} λεγων αφετε ιδ[ω]{.unclear}μεν ει ερχεται ηλι[ας]{.greek-supplied} καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου [ε]{.unclear}σχισθη εις δυο απο ανωθεν εω[ς]{.unclear} κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο [παρεστηκως]{.greek-omitted} [παρεστικως]{.greek-added} εξ εναντιας αυτου οτι [ουτως]{.greek-omitted} [κραξας]{.greek-omitted} εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} [ην]{.greek-omitted} [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.unclear} μαρια η μαγδαληνη και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι [και]{.greek-omitted} οτε ην εν τη γαλιλαια ηκολουθουν [αυτω]{.greek-omitted} [και]{.greek-omitted} [διηκονουν]{.greek-omitted} αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

ηλθεν ιωσηφ ο απο [αριμαθαιας]{.greek-omitted} [αριματθαιας]{.greek-added} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας εισηλθεν προς πιλατον [και]{.unclear} ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους απο του κεντυριωνος εδω[ρ]{.unclear}ησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ανειλησε]{.greek-added} τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον ε[πι]{.unclear} την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που τ[ι]{.unclear}[θετ]{.greek-supplied}αι[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και [ελεγον]{.greek-omitted} [προς]{.greek-omitted} [εαυτας]{.greek-omitted} [τις]{.greek-omitted} [αποκυλισει]{.greek-omitted} [ημιν]{.greek-omitted} [τον]{.greek-omitted} [λιθον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [θυρας]{.greek-omitted} [του]{.greek-omitted} [μνημειου]{.greek-omitted}[16:3]{.aside}

[και]{.greek-omitted} ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3 | instance no. 2]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενο[ν]{.unclear} [στο]{.greek-supplied}λην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε [ει]{.greek-supplied}πατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε [κ]{.greek-supplied}αθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτ[α]{.unclear}ς τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης εκβεβληκει [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} δαιμονια[16:9]{.aside}

εκεινη [πορευθεισα]{.greek-omitted} [πορευθησα]{.greek-added} απηγγειλεν τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι [ακουσαντες]{.greek-omitted} [οτι]{.greek-omitted} [ζη]{.greek-omitted} [και]{.greek-omitted} [εθεαθη]{.greek-omitted} [υπ]{.greek-omitted} [αυτης]{.greek-omitted} [ηπιστησαν]{.greek-omitted}[16:11]{.aside}

[κακεινοι]{.greek-omitted} ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11 | instance no. 2]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον [δε]{.greek-added} ανακειμενοις αυτοις τοις [ενδεκα]{.greek-omitted} [[ια]{.greek-abbr}]{.greek-added} εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει [εν]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [δαιμονια]{.greek-omitted} [εκβαλουσιν]{.greek-omitted} [γλωσσαις]{.greek-omitted} [λαλησουσιν]{.greek-omitted} [καιναις]{.greek-omitted}[[16:17 *(lacunose)*]{.lacunose}]{.aside}

[εκεινοι]{.greek-omitted} [δε]{.greek-omitted} [εξελθοντες]{.greek-omitted} [εκηρυξαν]{.greek-omitted} [πανταχου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} [συνεργουντος]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [βεβαιουντος]{.greek-omitted} δια των επακολουθουντων σημειων αμην[[16:20 *(lacunose)*]{.lacunose}]{.aside}

