---
title: "Collation of Byz^RP^ vs 31546 (1546)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1546 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31546).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1546                                   	| λογος                              	|
| 1546 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1546 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1546               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1546                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1546 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1546                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

[ως]{.greek-omitted} [καθως]{.greek-added} γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου [εμπροσθεν]{.greek-omitted} [σου]{.greek-omitted}[1:2]{.aside}

φωνη [βοωντως]{.greek-added} [βοωντος]{.corr} εν τη ερημω [ετοιμασατε]{.greek-omitted} [ετοιμασ[α]{.unclear}ται]{.greek-added} την οδον [κυριου]{.greek-abbr} ευθειας [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added} τας τριβους αυτου[1:3]{.aside}

[εγενετω]{.greek-added} [εγενετο]{.corr} ιωαννης [βαπτιζων]{.greek-omitted} [βαπτιζον]{.greek-added} εν τη ερημω και [κηρυσσων]{.greek-omitted} [κυρησσον]{.greek-added} βαπτισμα [μετανοιας]{.greek-omitted} [μεταννοιας]{.greek-added} [εις]{.greek-omitted} [ει]{.greek-added} αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα [η]{.greek-omitted} ιουδαια χωρα και οι [ιεροσολυμιται]{.greek-omitted} [ιερωσωλυμιται]{.greek-added} και [εβαπτιζοντο]{.greek-omitted} [ευαπτιζοντω]{.greek-added} παντες εν τω [ιορδανη]{.greek-omitted} [ιορδανει]{.greek-added} ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε [ο]{.greek-omitted} ιωαννης ενδεδυμενος τριχας [καμηλου]{.greek-omitted} [καμιλο[υ]{.unclear}]{.greek-added} και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και [μελι]{.greek-omitted} [μελη]{.greek-added} αγριον[1:6]{.aside}

και [εκυρησεν]{.greek-added} [εκηρυσσεν]{.greek-omitted} [[εκυρησσεν]{.corr}]{.greek-added} λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των [υποδηματων]{.greek-omitted} [υποδυματων]{.greek-added} αυτου[1:7]{.aside}

εγω μεν [εβαπτισα]{.greek-omitted} [ε[ι]{.unclear}βαπτισα]{.greek-added} υμας εν υδατι αυτος δε [βαπτισει]{.greek-omitted} [βαπτιση]{.greek-added} υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν [εκειναις]{.greek-omitted} ταις ημεραις [εκειναις]{.greek-added} ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} της γαλιλαιας και [ευαπτισθη]{.greek-added} [εβαπτισθη]{.greek-omitted} [[ευβαπτισθη]{.corr}]{.greek-added} υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως [ανβενον]{.greek-added} [αναβαινων]{.greek-omitted} [[ανβαινον]{.corr}]{.greek-added} απο του υδατος [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} [ωσει]{.greek-omitted} [ως]{.greek-added} [περιστε[―]{.gap}ραν]{.greek-added} [περιστεραν]{.corr} καταβαινον επ [αυτον]{.greek-omitted} [αυτου]{.greek-added}[1:10]{.aside}

και φωνη [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} εκ των [ουρανων]{.greek-abbr} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδωκησα]{.greek-added}[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} [εκβαλλει]{.greek-added} αυτον [εκβαλλει]{.greek-omitted} εις την ερημον[1:12]{.aside}

και ην εκει [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} ημερας τεσσαρακοντα [πειραζομενος]{.greek-omitted} [πειραζωμενος]{.greek-added} υπο του σατανα και ην μετα των [θηριων]{.greek-omitted} [θυριων]{.greek-added} και οι αγγελοι [διηκονουν]{.greek-omitted} [διεικονουν]{.greek-added} αυτω[1:13]{.aside}

μετα δε το [παραδοθηναι]{.greek-omitted} [παραδωθηναι]{.greek-added} τον ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και [ηγγικεν]{.greek-omitted} [ειγγικεν]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} [μετανοειτε]{.greek-omitted} [μετανοειτα[ι]{.unclear}]{.greek-added} και [πιστευετε]{.greek-omitted} [πηστευηται]{.greek-added} [[πηστευσηται]{.corr}]{.greek-added} εν τ[ω]{.unclear} ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την [θαλασσαν]{.greek-omitted} [θαλασαν]{.greek-added} της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος [βαλλοντας]{.greek-omitted} [αμφιβαλλοντας]{.greek-added} [αμφιβληστρον]{.greek-omitted} [αμφιβλυστρον]{.greek-added} εν τη θαλασση ησαν γαρ [αλλειεις]{.greek-added} [αλιεις]{.greek-omitted} [[αλλιεις]{.corr}]{.greek-added}[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτ[ε]{.unclear} οπισω μου και [ποιησω]{.greek-omitted} [ποιεισω]{.greek-added} υμας [αλλιεις]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} γενεσθαι [αλιεις]{.greek-omitted} [ανθρωπων]{.greek-omitted}[1:17]{.aside}

και ευθεως αφεντες τα [δικτυα]{.greek-omitted} [δυκτια]{.greek-added} αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [ιακωβον]{.greek-omitted} [ιακωβων]{.greek-added} τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα [δικτυα]{.greek-omitted} [δυκτια]{.greek-added} [αυτων]{.greek-added}[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} [αυτων]{.greek-omitted} [αυτον]{.greek-added} ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων [εις]{.greek-omitted} [ει]{.greek-added} την συναγωγην [αυτων]{.greek-added} [διδασκεν]{.greek-added} [εδιδασκεν]{.corr}[1:21]{.aside}

και εξεπλησσοντο [παντες]{.greek-added} επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και ανεκραξεν[1:23]{.aside}

[λ]{.unclear}εγων εα τι [ημιν]{.greek-omitted} [υμιν]{.greek-added} και σοι [ιησου]{.greek-abbr} [ναζαρηνε]{.greek-omitted} [ναζωριναι]{.greek-added} ηλθες απολεσαι [ημας]{.greek-omitted} [υμας]{.greek-added} οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και [επετημησ[ο]{.unclear}ν]{.greek-added} [επετιμησεν]{.greek-omitted} [[επετημησεν]{.corr}]{.greek-added} αυτω ο [ιησους]{.greek-abbr} λεγων [φιμωθητι]{.greek-omitted} [φιμωθιτη]{.greek-added} [και]{.greek-omitted} εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και [εθαμβηθησαν]{.greek-omitted} [εθαμβιθησαν]{.greek-added} [παντες]{.greek-omitted} [απαντες]{.greek-added} ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τ[ι]{.unclear} εστιν τουτο τις η [δαδαχη]{.greek-added} [διδαχη]{.corr} η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-abbr} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν δε η ακοη αυτου ευθυς εις ολη[ν]{.unclear} την περιχωρον της γαλιλαιας[1:28]{.aside}

και [ευ]{.greek-added} [ευθεως]{.greek-omitted} [θεως]{.greek-added} εκ της συναγωγης [εξελθοντες]{.greek-omitted} [εξελθωντες]{.greek-added} ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα [του]{.greek-added} σιμωνος κατεκειτο πυρεσσουσα και [ευθεω]{.greek-added} [ευθεως]{.corr} λεγουσιν αυτω περι αυτης[1:30]{.aside}

και [προσελθων]{.greek-omitted} [προσελθον]{.greek-added} [ηγειρεν]{.greek-omitted} [ειγυρεν]{.greek-added} [ατην]{.greek-added} [αυτην]{.corr} κρατησας της χειρος αυτης και αφηκεν αυτην ο π[υ]{.unclear}ρετος ευθεως και διηκονει [αυτοις]{.greek-omitted} [αυτω]{.greek-added}[1:31]{.aside}

οψιας δε γενομενης οτε [εδυ]{.greek-omitted} [εδη]{.greek-added} ο ηλιος εφερον [αυτω]{.greek-added} [προς]{.corr} [αυτον]{.corr} παντας τους κακως εχοντας και τους [δαιμονιζομενους]{.greek-omitted} [δαιμονιζωμενους]{.greek-added}[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και εθεραπευσεν πολλους κακως [εχοντας]{.greek-omitted} [εχωντας]{.greek-added} [ποικ[α]{.unclear}λαις]{.greek-added} [ποικιλαις]{.corr} νοσοις και δαιμονια πολλα εξεβαλεν και ουκ ηφιεν [αυτα]{.greek-added} λαλειν [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} οτι [ηδεισαν]{.greek-omitted} [ηδισαν]{.greek-added} αυτον[1:34]{.aside}

και πρωι [εννυχον]{.greek-omitted} [ενυχεν]{.greek-added} λιαν αναστας εξηλθεν και απηλθεν εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και κατεδιωξαν αυτον ο [τε]{.greek-added} [σιμων]{.greek-omitted} [σιμον]{.greek-added} και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην [κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς [αυτον]{.greek-omitted} [αυτων]{.greek-added} λεπρος παρακαλω[ν]{.unclear} αυτον και [γονυπετων]{.greek-omitted} [γωνυπετων]{.greek-added} αυτον και λεγων αυτω οτι εαν [θελης]{.corr} [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} με [καθαρισαι]{.greek-omitted} [καθαρησαι]{.greek-added}[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} [σπλαγχνισθεις]{.greek-omitted} [σπλαχνισθεις]{.greek-added} εκτεινας την χειρα [ηψατο]{.greek-omitted} [ηψατω]{.greek-added} αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν [απ]{.greek-omitted} [αυτου]{.greek-omitted} η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω [ευθεως]{.greek-omitted} εξεβαλεν αυτον [ευθεως]{.greek-added}[1:43]{.aside}

και λεγει αυτω ορα μηδενι [μηδεν]{.greek-omitted} ειπης [αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγγε]{.greek-added} περι του καθαρισμου σου α προσεταξεν [μωσης]{.greek-omitted} [μω]{.greek-added} [υσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε [εξελθων]{.greek-omitted} [εξελθον]{.greek-added} [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} [κηρυσσειν]{.greek-omitted} [κη]{.greek-added} [ρυσσην]{.greek-added} πολλα και διαφημιζειν τον λογον ωστε [μηκετι]{.greek-omitted} [μηκετη]{.greek-added} [αυ]{.greek-added} [αυτον]{.greek-added} [αυτον]{.corr} δυνασθαι [φανερως]{.greek-omitted} [φανερο[ν]{.unclear}]{.greek-added} εις πολιν εισελθειν αλλ εξω εν [ε]{.greek-added} [ερημοις]{.greek-omitted} [ριμοις]{.greek-added} τοποις ην και [ηρχοντο]{.greek-omitted} [ηρχοντω]{.greek-added} προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [ησσηλθεν]{.greek-added} παλιν εις καπερναουμ δι ημερων και [η]{.greek-added} [ηκουσθη]{.greek-omitted} [κουσθη]{.greek-added} οτι εις οικον εστιν[2:1]{.aside}

και [ευ]{.unclear}θεως [συνηχθησαν]{.greek-omitted} [σηνηχθησαν]{.greek-added} πολλοι ωστε [μηκετι]{.greek-omitted} [μηκετη]{.greek-added} χωρειν μηδε τα προς την θυραν και [ελαλει]{.greek-omitted} [ελα]{.greek-added} [λη]{.greek-added} αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον [παραλυτικον]{.greek-omitted} [παραλυτι]{.greek-added} [κον]{.greek-added} φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι [προσεγγισαι]{.greek-omitted} αυτω [προσεγγησαι]{.greek-added} δια τον οχλον απεστεγασαν την στεγην [ο]{.greek-added} [οπου]{.greek-omitted} [που]{.greek-added} ην και εξορυξαντες χαλωσιν τον κραββατον εφ ω ο [πα]{.greek-added} [παραλυτικος]{.greek-omitted} [ραλυτικ[ος]{.unclear}]{.greek-added} [κατεκειτο]{.greek-omitted} [κατεκειτω]{.greek-added}[2:4]{.aside}

[ιδων]{.greek-omitted} [ιδον]{.greek-added} δε ο [ιησους]{.greek-abbr} την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} [αυτων]{.greek-omitted} [αυτον]{.greek-added} λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι [αμαρτιαι]{.greek-omitted} [αμαρτι]{.greek-added} [αι]{.greek-added} σου[2:5]{.aside}

ησαν δε [τινες]{.greek-omitted} [τοιναις]{.greek-added} των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} [ουτω]{.greek-added} [λα]{.greek-supplied}λει [βλασφημιας]{.greek-omitted} [βλασφιμηας]{.greek-added} τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι [ουτως]{.greek-omitted} [ουτος]{.greek-added} [αυτ[ω]{.unclear}]{.greek-added} [αυτοι]{.corr} διαλογιζονται εν [εαυτοις]{.greek-omitted} [ταις]{.greek-added} [καρδιαις]{.greek-added} [αυτων]{.greek-added} ειπεν αυτοις τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[2:8]{.aside}

τι [ε]{.greek-added} [εστιν]{.greek-omitted} [στιν]{.greek-added} [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} [εισπειν]{.greek-added} [ειπειν]{.corr} τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σου αι αμαρτιαι η ειπειν εγειραι και [αρον]{.greek-omitted} [σου]{.greek-omitted} [τον]{.greek-omitted} [κραββατον]{.greek-omitted} [και]{.greek-omitted} περιπατει[2:9]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ιδηται]{.greek-added} οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιε]{.greek-added} [ναι]{.greek-added} αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγερθητι]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σ[ο]{.unclear}υ[2:11]{.aside}

και ηγερθη [και]{.greek-added} ευθεως και αρας τον κραββατον εξηλθεν [ε]{.greek-added} [εναντιον]{.greek-omitted} [ναντιων]{.greek-added} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι [ουδεποτε]{.greek-omitted} [ουδεποται]{.greek-added} [ουτως]{.greek-omitted} [ουτος]{.greek-added} [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added}[2:12]{.aside}

και εξηλθεν [παλιν]{.greek-omitted} [παλην]{.greek-added} παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και [παραγων]{.greek-omitted} [παραγον]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [εκειθεν]{.greek-added} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} λευι τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας [ηκολουθη]{.greek-added} [ηκολουθησεν]{.corr} αυτω[2:14]{.aside}

και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} [αυ]{.greek-added} [αυτω]{.greek-added} εν τω [κατακεισθαι]{.greek-omitted} [κατοικεισθαι]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι [ισχυοντες]{.greek-omitted} [ισχιοντες]{.greek-added} ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [φαρισαιοι]{.greek-added} νηστευοντες και ερχονται και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} αυτω δια [τι]{.greek-omitted} [τοι]{.greek-added} οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου νηστευουσιν[2:18]{.aside}

και ειπεν αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} μη δυνανται οι υιοι του νυμφωνος [εν]{.greek-omitted} [ω]{.greek-omitted} [εφ]{.greek-added} [ωσον]{.greek-added} [μετ]{.greek-added} [αυτων]{.greek-added} ο νυμφιος [μετ]{.greek-omitted} [αυτων]{.greek-omitted} εστιν νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον ν[υ]{.unclear}μφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται [δε]{.greek-omitted} [δαι]{.greek-added} ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [εκεινη]{.greek-added} [τη]{.greek-added} [ημεραις]{.greek-omitted} [ημερα]{.greek-added}[2:20]{.aside}

[και]{.greek-omitted} ουδεις επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω [ει]{.greek-omitted} [η]{.greek-added} δε [μη]{.greek-omitted} [μηγε]{.greek-added} αιρει [απ]{.greek-added} [αυτου]{.greek-added} το πληρωμα [αυτου]{.greek-omitted} το καινον του παλαιου και χειρον [σχισμα]{.greek-omitted} [σχισ]{.greek-added} [μα]{.greek-added} γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις [ακους]{.greek-added} [ασκους]{.corr} παλαιους [ει]{.greek-omitted} [η]{.greek-added} δε μη [ρησσει]{.greek-omitted} [ρησει]{.greek-added} ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται αλλα οινον νεον εις ασκους καινους [βλητεον]{.greek-omitted} [βληταιον]{.greek-added}[2:22]{.aside}

και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} παραπορευεσθαι αυτον [δια]{.greek-added} [των]{.greek-added} [σποριμων]{.greek-added} εν τοις σαββασιν [δια]{.greek-omitted} [των]{.greek-omitted} [σποριμων]{.greek-omitted} και [ηρξαντο]{.greek-omitted} [ηρξαντω]{.greek-added} οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} αυτω ιδε τι ποιουσιν [εν]{.greek-omitted} τοις σαββασιν ο ουκ εξεστιν[2:24]{.aside}

[και]{.greek-added} [αυτος]{.greek-added} [[ελ]{.unclear}εγεν]{.greek-added} [αυτοις]{.greek-added} και αυτος ελεγεν αυτοις ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} τι εποιησεν [δαυιδ]{.greek-abbr} οτε χρειαν εσχεν και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} [επι]{.corr} [αβιαθαρ]{.corr} [[του]{.corr}]{.greek-added} [αρχιερεως]{.corr} [και]{.corr} [τους]{.corr} [αρτους]{.corr} [της]{.corr} [προθεσεως]{.corr} [[ε]{.unclear}φαγεν]{.corr} ους ουκ εξεστιν φαγειν ει [μη]{.greek-omitted} [μι]{.greek-added} τοις ιερευσιν και εδωκεν και τοις [συν]{.greek-omitted} [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} [σιν]{.greek-added} [ουσιν]{.corr}[2:26]{.aside}

και ελεγεν αυτοις το [σαββα[―]{.gap}τον]{.greek-added} [σαββατον]{.corr} δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν [παλιν]{.greek-omitted} [παλην]{.greek-added} εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} [εχων]{.greek-omitted} [εχον]{.greek-added} την χειρα[3:1]{.aside}

και [γαρ]{.greek-added} [παρετηρουν]{.greek-omitted} [ετηρουν]{.greek-added} αυτον [ει]{.greek-omitted} [η]{.greek-added} τοις σαββασιν [θεραπευσει]{.greek-omitted} αυτον [θεραπευσαι]{.greek-added} ινα κατηγορησωσιν [αυτου]{.greek-omitted} [αυτον]{.greek-added}[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχοντι την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις εξεστιν τοις σαββασιν [αγαθοποιησαι]{.greek-omitted} [αγαθοποιεισαι]{.greek-added} η [κακοποιησαι]{.greek-omitted} [κακοποιεισαι]{.greek-added} ψυχην σωσαι [η]{.unclear} αποκτειναι οι δε [εσιωπον]{.greek-added} [εσιωπων]{.corr}[3:4]{.aside}

και περιβλεψαμενος [αυτους]{.greek-omitted} [αυτοις]{.greek-added} μετ οργης [συλλυπουμενος]{.greek-omitted} [συλληπουμενος]{.greek-added} επι τη [πρ]{.greek-added} [πωρωσει]{.greek-omitted} [[πωρρωσει]{.corr}]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον [σου]{.greek-added} την χειρα [σου]{.greek-omitted} και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου [οπως]{.greek-omitted} [οπω]{.greek-added} αυτον [απολεσωσιν]{.greek-omitted} [υπολεσωσιν]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} ανεχωρησεν [εις]{.greek-added} [την]{.greek-added} [θαλασσαν]{.greek-added} μετα των μαθητων αυτου [προς]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} και [πολυ]{.greek-omitted} [πολλυ]{.greek-added} πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο [ιεροσολυμων]{.greek-omitted} [ιερωσωλυμων]{.greek-added} και απο της [ιουδουμαιας]{.greek-added} [ιδουμαιας]{.corr} και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος [πολυ]{.greek-omitted} [πολλυ]{.greek-added} ακουσαντες οσα [εποιει]{.greek-omitted} [εποιοι]{.greek-added} ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη [θλιβωσιν]{.greek-omitted} [θληβωσιν]{.greek-added} αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [απτονται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και [τα]{.greek-omitted} [πνευματα]{.greek-abbr} [τα]{.greek-omitted} ακαθαρτα οταν αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζων]{.greek-added} λεγοντα οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα [επετιμα]{.greek-omitted} [επετημα]{.greek-added} αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιωσιν]{.greek-added}[3:12]{.aside}

και [αναβαινει]{.greek-omitted} [αναβαινειν]{.greek-added} εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και εποιησεν δωδεκα ινα ωσιν μετ αυτου [και]{.greek-omitted} ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και [εκβαλλειν]{.greek-omitted} [εκβαλειν]{.greek-added} τα δαιμονια[3:15]{.aside}

και επεθηκεν τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον του [ιακωβου]{.greek-omitted} [ιακοβου]{.greek-added} και επεθηκεν αυτοις ονοματα [βοανεργες]{.greek-omitted} [βοανηργες]{.greek-added} ο εστιν υιοι βροντης[3:17]{.aside}

και [ανδρεαν]{.greek-omitted} [ανδραιαν]{.greek-added} και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του [αφαιου]{.greek-added} [αλφαιου]{.corr} και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην [ος]{.greek-omitted} [ως]{.greek-added} και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος [πολλυς]{.greek-added} ωστε μη δυνασθαι αυτους [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι [παρ]{.greek-omitted} [πα]{.greek-added} [ρ]{.greek-added} αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι [εξεστη]{.greek-omitted} [εξεστιν]{.greek-added}[3:21]{.aside}

και οι γραμματεις οι απο [ιεροσολυμων]{.greek-omitted} [ιερωσωλυμων]{.greek-added} καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των [δαιμονιων]{.greek-omitted} [δαιμωνιων]{.greek-added} εκβαλλει τα [δαιμονια]{.greek-omitted} [δαιμωνια]{.greek-added}[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου [δυναται]{.greek-omitted} [δηναται]{.greek-added} σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου [εισελθων]{.greek-omitted} εις την οικιαν αυτου [εισελθον]{.greek-added} διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [διαρπασαι]{.greek-added} [διαρπαση]{.corr}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted} τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημησει]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις [τον]{.greek-omitted} [τος]{.greek-added} αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} [ακαθαρτον]{.greek-omitted} [ακαθαρ]{.greek-added} εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς [αυτον]{.greek-omitted} [αυτων]{.greek-added} φωνουντες αυτον[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω ζητουσιν σε[3:32]{.aside}

και [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} αυτοις [λεγων]{.greek-omitted} [λεγον]{.greek-added} τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι [αδεφοι]{.greek-added} [αδελφοι]{.corr} μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και [ωι]{.greek-added} [οι]{.corr} αδελφοι μου[3:34]{.aside}

ος γαρ αν [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} εστιν[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο [διδασκειν]{.greek-omitted} παρα την θαλασσαν [διδασ]{.greek-added} [κειν]{.greek-added} και συνηχθη προς αυτον οχλος πολυς [ωστε]{.greek-omitted} [ωσται]{.greek-added} αυτον εμβαντα εις [το]{.greek-omitted} πλοιον [καθησθαι]{.greek-omitted} [καθησαι]{.greek-added} εν τη [θαλασση]{.greek-omitted} [θαλασσει]{.greek-added} και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

[ακουετε]{.greek-omitted} [ακουεται]{.greek-added} ιδου εξηλθεν ο [σπειρων]{.greek-omitted} [σπειρον]{.greek-added} του σπειραι[4:3]{.aside}

και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} εν τω σπειρειν ο μεν επεσεν παρα την οδον και ηλθεν τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

[αλλο]{.greek-omitted} [αλλω]{.greek-added} δε επεσεν επι [το]{.greek-omitted} [τα]{.greek-added} πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος [εκαυματισθη]{.greek-omitted} [εκαυματησθη]{.greek-added} και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ εδωκεν[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἓν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἓν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἓν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων [ωτα]{.greek-omitted} [ωττα]{.greek-added} ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν [δεδωτε]{.greek-added} [δεδοται]{.greek-omitted} [γνωναι]{.greek-omitted} το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα [γινεται]{.greek-omitted} [γυνεται]{.greek-added}[4:11]{.aside}

ινα [βλεποντες]{.greek-omitted} [βλεπωντες]{.greek-added} βλεπωσιν και μη ιδωσιν και ακουοντες [ακουωσιν]{.greek-omitted} [ακουειν]{.greek-added} και μη συνιωσιν [μηποτε]{.greek-omitted} [μηποται]{.greek-added} επιστρεψωσιν και [αφεθη]{.greek-omitted} [αφεθησεται]{.greek-added} αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ [οιδατε]{.greek-omitted} [ειδαται]{.greek-added} την παραβολην ταυτην και πως πασας τας παραβολας [γνωσεσθε]{.greek-omitted} [γνωσεσθαι]{.greek-added}[4:13]{.aside}

[ο]{.unclear} [σπειρων]{.greek-omitted} [σπειρ[ο]{.unclear}ν]{.greek-added} τον λογον σπειρει[4:14]{.aside}

ουτοι δε [εισιν]{.greek-omitted} [ησιν]{.greek-added} οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον [εσπαρμενον]{.greek-omitted} [σπαρμενον]{.greek-added} εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι [εισιν]{.greek-omitted} [ησιν]{.greek-added} ομοιως οι επι τα πετρωδη [σπειρομενοι]{.greek-omitted} [σπειρωμενοι]{.greek-added} οι οταν ακουσωσιν τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ εχουσιν ριζαν εν εαυτοις αλλα προσκαιροι [[η]{.unclear}σιν]{.greek-added} [εισιν]{.corr} ειτα γενομενης θλιψεως η [διωγμου]{.greek-omitted} [διογμου]{.greek-added} δια τον λογον ευθεως [σκανδαλιζονται]{.greek-omitted} [σκανδαλιζωνται]{.greek-added}[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας [σπειρομενοι]{.greek-omitted} [σπειρωμενοι]{.greek-added} οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι συμπνιγουσιν τον λογον και ακαρπος [γινεται]{.greek-omitted} [γυνεται]{.greek-added}[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακου[ω]{.unclear}σι]{.greek-added} [ακουουσιν]{.greek-omitted} [[ακουσοσι]{.corr}]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} [τριακοντα]{.greek-omitted} [τιακοντα]{.greek-added} και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και εν εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα [υπο]{.greek-omitted} [επι]{.greek-added} τον μοδιον [τ]{.unclear}εθη η υπο την [κλινην]{.greek-omitted} [κληνην]{.greek-added} ουχ ινα επι την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον [ο]{.greek-omitted} εαν μη φανερωθη ουδε [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} αποκρυφον αλλ ινα [[ν]{.unclear}ς]{.greek-added} [εις]{.corr} φανερον ελθη[4:22]{.aside}

ει τις εχει [ωτα]{.greek-omitted} [ωτια]{.greek-added} α[κ]{.unclear}ουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} τι [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} εν ω μετρω [μετρειτε]{.greek-omitted} [μετρειται]{.greek-added} [μετρηθησεται]{.greek-omitted} [αντιμετρηθησεται]{.greek-added} υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} [εχη]{.greek-omitted} [εχει]{.greek-added} [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} αυτω και ος ουκ εχει και ο [δωκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [βαλλει]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και καθευδη και [εγειρηται]{.greek-omitted} [εγειρειται]{.greek-added} [νυκτα]{.greek-omitted} [νυκταν]{.greek-added} και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και μηκυνηται ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν [τω]{.greek-omitted} σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει [το]{.greek-omitted} [τον]{.greek-added} δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν [τινι]{.greek-omitted} [τινη]{.greek-added} [ομοιωσωμεν]{.greek-omitted} [ωμοιωσωμεν]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} [παραβαλλωμεν]{.greek-added} αυτην[4:30]{.aside}

ως [κοκκον]{.greek-omitted} [κοκκος]{.greek-added} σιναπεως ος οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} [αναβαινει]{.greek-omitted} [αναβαινη]{.greek-added} και [γινεται]{.greek-omitted} [γηνεται]{.greek-added} παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και [τοιαυτας]{.greek-added} [τοιαυταις]{.corr} παραβολαις πολλαις ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [εδυνατο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ [ελαλει]{.greek-omitted} [αιλαλη]{.greek-added} αυτοις κατ ιδιαν δε τοις μαθηταις αυτου επελυεν παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και [γινεται]{.greek-omitted} [γυνεται]{.greek-added} [λαιλαψ]{.greek-omitted} [λελαψ]{.greek-added} ανεμου [μεγ[ει]{.unclear}λη]{.greek-added} [μεγαλη]{.corr} τα δε κυματα επεβαλλεν εις το [π[ο]{.unclear}]{.greek-added} [πλοιον]{.corr} [ωστε]{.greek-omitted} [ωσται]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added} [ηδη]{.greek-omitted} [ιδη]{.greek-added} [γεμιζεσθαι]{.greek-omitted} [γεμηζεσθαι]{.greek-added}[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλη]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

και [εγερθεις]{.greek-added} [διεγερθεις]{.corr} [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} τω ανεμω και ειπεν τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [πεφιμωσω]{.greek-added} και [εκοπασεν]{.greek-omitted} [εκωπασεν]{.greek-added} ο ανεμος και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} [γαληνη]{.greek-omitted} [γαλινη]{.greek-added} μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι [εστε]{.greek-omitted} [εσται]{.greek-added} ουτως πως ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} [πιστιν]{.greek-omitted} [πιστην]{.greek-added}[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγ[ο]{.greek-supplied}ν προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της [θα]{.greek-added} [θαλασσης]{.greek-omitted} [λασσης]{.greek-added} εις την χωραν των γαδαρηνων[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως απηντησεν αυτω [[ανθρωπος]{.greek-abbr}]{.greek-added} εκ των μνημειων [ανθρωπος]{.greek-omitted} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την [κατοικησιν]{.greek-omitted} [τοικησιν]{.greek-added} ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις εδυνατο αυτον [δησαι]{.greek-omitted} [δυσε]{.greek-added}[5:3]{.aside}

δια το αυτον [πολλακις]{.greek-omitted} [πολλακεις]{.greek-added} [πεδαις]{.greek-omitted} [παιδαις]{.greek-added} και αλυσεσιν δεδεσθαι και διεσπασθαι υπ αυτου τας αλυσεις και τας [πεδας]{.greek-omitted} [παιδας]{.greek-added} συντετριφθαι και ουδεις [ισχυσεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μημασιν]{.greek-added} [[μνημασιν]{.corr}]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και [κατακοπτων]{.greek-omitted} [κατακοπτον]{.greek-added} εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν εδραμεν και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και σοι [ιησου]{.greek-abbr} [υιε]{.greek-abbr} του [θεου]{.greek-abbr} του υψιστου [ορκιζω]{.greek-omitted} [ορκηζω]{.greek-added} [σαι]{.greek-added} [σε]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} μη με [βασανισης]{.greek-omitted} [βασανισεις]{.greek-added}[5:7]{.aside}

ελεγεν γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι [ονομα]{.greek-added} σοι [ονομα]{.greek-omitted} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη [αυτους]{.greek-omitted} αποστειλη [αυτον]{.greek-added} εξω της χωρας[5:10]{.aside}

ην δε εκει [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων μεγαλη βοσκομενη [προς]{.greek-added} [το]{.greek-added} [ορει]{.greek-added}[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον [παντες]{.greek-omitted} οι [δαιμονες]{.greek-omitted} [δαιμωνες]{.greek-added} λεγοντες πεμψον [ημας]{.greek-omitted} [υμας]{.greek-added} εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} τα ακαθαρτα εισηλθον εις τους χοιρους και [ωρμησεν]{.greek-omitted} [ορμησεν]{.greek-added} η αγελη κατα του [κρημνου]{.greek-omitted} [κρυμνου]{.greek-added} εις την θαλασσαν ησαν δε ως [δυσχιλοοι]{.greek-added} [δισχιλιοι]{.greek-omitted} [[δυσχιλιοι]{.corr}]{.greek-added} και [επνιγοντο]{.greek-omitted} [επνιγοντω]{.greek-added} εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες το[υ]{.unclear}ς χοιρο[υ]{.unclear}ς εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} ιδειν [τι]{.greek-omitted} [εστιν]{.greek-omitted} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και θεωρουσιν τον [δαιμονιζομενον]{.greek-omitted} [δαιμωνιζωμενον]{.greek-added} καθημενον και ιματισμενον και σωφρονουντα [τον]{.greek-omitted} εσχηκοτα τον λεγεωνα και [εφοβηθησαν]{.greek-omitted} [εφωβηθησαν]{.greek-added}[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} [αυ]{.greek-added} [αυτοις]{.greek-omitted} [τοις]{.greek-added} οι [ιδοντες]{.greek-omitted} [ιδωντες]{.greek-added} πως [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} τω [δαιμονιζομενω]{.greek-omitted} [δαιμωνιζωμενω]{.greek-added} και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο [δαιμονισθεις]{.greek-omitted} [δαιμωνισθεις]{.greek-added} ινα [η]{.greek-omitted} μετ αυτου [ει]{.greek-added}[5:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ [αφηκεν]{.greek-omitted} [ηφηκεν]{.greek-added} αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και [αναγγειλον]{.greek-omitted} [ανακειλον]{.greek-added} [[ανγακειλον]{.corr}]{.greek-added} αυτοις οσα σοι [ο]{.corr} [κυριος]{.greek-abbr} πεποιηκεν και ηλεησεν [σε]{.greek-omitted} [σαι]{.greek-added}[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω [παλιν]{.greek-omitted} [παλην]{.greek-added} εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των [αρχισυναγωγων]{.greek-omitted} [αρχισαναγωγων]{.greek-added} ονοματι ιαειρος και ιδων αυτον πιπτει [προς]{.greek-omitted} [εις]{.greek-added} τους ποδας αυτου[5:22]{.aside}

[και]{.greek-omitted} παρεκαλει αυτον [πολλα]{.greek-omitted} [λεγων]{.greek-omitted} [λεγον]{.greek-added} οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} αυτη τας χειρας οπως σωθη και ζησεται[5:23]{.aside}

και απηλθεν μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς [κ]{.greek-added} [και]{.corr} συνεθλιβον [αυτον]{.greek-omitted} [αυτω]{.greek-added}[5:24]{.aside}

και γυνη τις ουσα εν [ρυσει]{.greek-omitted} [ρυσσει]{.greek-added} αιματος [ετη]{.greek-omitted} [ετι]{.greek-added} δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα [τα]{.greek-added} περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν [ηψατο]{.greek-omitted} [ηψατω]{.greek-added} του ιματιου αυτου[5:27]{.aside}

ελεγεν γαρ [εν]{.greek-added} [εαυτη]{.greek-added} οτι καν των ιματιων αυτου [αψωμαι]{.greek-omitted} [σωθησομαι]{.greek-omitted} [αψωμε]{.greek-added} [σωθησωμε]{.greek-added}[5:28]{.aside}

και ευθεως εξηρανθη [η]{.greek-omitted} [υ]{.greek-added} πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της [μαστιγος]{.greek-omitted} [μαστηγος]{.greek-added}[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα [σε]{.greek-omitted} [σαι]{.greek-added} και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την [τουτο]{.greek-omitted} [τουτου]{.greek-added} ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα [ειδυια]{.greek-omitted} [ιδυια]{.greek-added} ο γεγ[ο]{.unclear}νεν [[γεγωνεν]{.corr}]{.greek-added} επ αυτη ηλθεν και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη [θυγατερ]{.greek-omitted} [θυγατηρ]{.greek-added} η [πιστις]{.greek-omitted} [πηστης]{.greek-added} σου σεσωκεν σε υπαγε εις ειρηνην και ισθι [υγιης]{.greek-omitted} [υγιυς]{.greek-added} απο της μαστιγος [ου]{.greek-added} [σου]{.corr}[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} οτι η [θυγατηρ]{.greek-omitted} [θυγατυρ]{.greek-added} σου απεθανεν τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω [συνακολουθησαι]{.greek-omitted} [ακολουθησαι]{.greek-added} ει μη πετρον και ιακωβον και ιωαννην τον αδελφον [του]{.greek-added} ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} κλαιοντας [και]{.greek-omitted} [αλαλαζοντας]{.greek-omitted} [αλλαλαζοντες]{.greek-added} πολλα[5:38]{.aside}

και [εισελθων]{.greek-omitted} [εισελθον]{.greek-added} λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και [κλαιετε]{.greek-omitted} [κλαιεται]{.greek-added} το παιδιον ουκ απεθανεν αλλα [καθευδει]{.greek-omitted} [καθευδη]{.greek-added}[5:39]{.aside}

και κατεγελων αυτου ο δε [εκβαλων]{.greek-omitted} [εκβαλον]{.greek-added} παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα κουμι ο εστιν μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγερθητη]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατ[ει]{.unclear} ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

[και]{.unclear} διεστειλατο αυτοις πολλα ινα μηδεις γνω [τουτο]{.greek-omitted} [τουτω]{.greek-added} και ειπεν [δοθηναι]{.greek-omitted} [δωθηναι]{.greek-added} αυτη φαγειν[5:43]{.aside}

### Chapter 6

[και]{.greek-omitted} εξηλθεν εκειθεν [και]{.greek-omitted} [ηλθεν]{.greek-omitted} εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα [ινα]{.greek-added} [και]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [η]{.greek-omitted} [δοθεισα]{.greek-omitted} [αυτω]{.greek-omitted} και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο [τεκτων]{.greek-omitted} [τεκτον]{.greek-added} [ο]{.greek-omitted} [υιος]{.greek-abbr} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και [εσκανδαλιζοντο]{.greek-omitted} [εσκανδαλιζοντω]{.greek-added} εν αυτω[6:3]{.aside}

ελεγεν δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ εστιν προφητης ατιμος ει [μη]{.greek-omitted} [μι]{.greek-added} εν τη [πατριδι]{.greek-omitted} [πατριδη]{.greek-added} [αυτω]{.greek-added} [αυτου]{.corr} και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσιν]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ [ηδυνατο]{.greek-omitted} [αιδυνατο]{.greek-added} εκει ουδεμιαν δυναμιν ποιησαι ει [μη]{.greek-omitted} [μι]{.greek-added} ολιγοις αρρωστοις [ε[―]{.gap}πιθεις]{.greek-added} [επιθεις]{.corr} τας χειρας εθεραπευσεν[6:5]{.aside}

και εθαυμαζεν δια την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και περιηγεν τας κωμας κυκλω [διδασκων]{.greek-omitted} [διδασκον]{.greek-added}[6:6]{.aside}

και προσκαλειται τους δωδεκα και [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει [μη]{.greek-omitted} [μι]{.greek-added} ραβδον μονον μ[η]{.unclear} [πηραν]{.greek-omitted} [πειραν]{.greek-added} μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσασθαι]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν [εισελθητε]{.greek-omitted} [εισελθηται]{.greek-added} εις οικιαν εκει [μενετε]{.greek-omitted} [μενεται]{.greek-added} εως αν [εξελθητε]{.greek-omitted} [εξελθηται]{.greek-added} εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν [εκτιναξατε]{.greek-omitted} [εκτειναξαται]{.greek-added} τον [χουν]{.greek-omitted} [χουο]{.greek-added} [τον]{.greek-omitted} [των]{.greek-added} υποκατω των ποδων υμων εις μαρτυριον αυτοις [αμην]{.greek-omitted} λεγω [δε]{.greek-added} υμιν [ανεκτοτερον]{.greek-omitted} [ενεκτοτερον]{.greek-added} εσται [σοδομοις]{.greek-omitted} [σωδομοις]{.greek-added} η [γομορροις]{.greek-omitted} [γομωρροις]{.greek-added} εν ημερα κρισεως η τη [πολει]{.greek-omitted} [πολη]{.greek-added} εκεινη[6:11]{.aside}

και εξελθοντες [εκηρυσσον]{.greek-omitted} [εκυρισσον]{.greek-added} ινα μετανοησωσιν[6:12]{.aside}

και [δαιμονια]{.greek-omitted} [δαιμωνια]{.greek-added} πολλα [εξεβαλλον]{.greek-omitted} [εξεβαλον]{.greek-added} και [ηλειφον]{.greek-omitted} [ειληφον]{.greek-added} ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο [β]{.unclear}ασιλευς ηρωδης φανερον γαρ [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} το ονομα αυτου [κ]{.unclear}α[ι]{.unclear} ε[λε]{.unclear}γε[ν]{.unclear} [και]{.greek-added} [ελεγεν]{.greek-added} οτι [ο]{.greek-added} [ιωαννης]{.corr} ο βαπτιζων εκ νεκρων [ηγερθη]{.greek-omitted} [ανεστη]{.greek-added} και δια τουτο ενεργουσιν αι δυναμεις εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} ιωαννην [ουτος]{.greek-omitted} [ουτως]{.greek-added} εστιν αυτος ηγερθη εκ [των]{.greek-added} νεκρων[6:16]{.aside}

αυτος γαρ [ο]{.greek-omitted} ηρωδης αποστειλας εκρατησεν τον ιωαννην [και]{.greek-omitted} [εδησεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [φυλακη]{.greek-omitted} δια ηρωδιαδα την [γυναικα]{.greek-omitted} [γυναικαν]{.greek-added} φιλιππου του [αδελφου]{.greek-omitted} [δελφου]{.greek-added} αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο ιωαννης τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας [ενειχεν]{.greek-omitted} [ηνειχεν]{.greek-added} αυτω και ηθελεν αυτον αποκτειναι και ουκ [ηδυνατο]{.greek-omitted} [ηδυνατω]{.greek-added}[6:19]{.aside}

ο γαρ ηρωδης [εφοβειτο]{.greek-omitted} [εφοβητω]{.greek-added} τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον [και]{.greek-omitted} [συνετηρει]{.greek-omitted} [συνετηρη]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added} και ακουσας αυτου πολλα εποιει και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος [και]{.corr} [ορχησαμενης]{.corr} και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω [κορασιω]{.greek-omitted} [κοραρασιω]{.greek-added} αιτησον [μοι]{.greek-added} [με]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [θελης]{.greek-omitted} και δωσω σοι[6:22]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [αιτησης]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted} εως [ημισους]{.greek-omitted} [ειμησου]{.greek-added} της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι [αιτησομαι]{.greek-omitted} [αιτησωμαι]{.greek-added} η δε ειπεν την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και [εισελθουσα]{.greek-omitted} [ησελθουσα]{.greek-added} ευθεως μετα [σπουδης]{.greek-omitted} [σπουδεις]{.greek-added} προς τον βασιλεα [ητησατο]{.greek-omitted} [ητησατω]{.greek-added} λεγουσα θελω ινα [μοι]{.greek-omitted} [μη]{.greek-added} δως εξαυτης επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ [ηθελησεν]{.greek-omitted} [ηθελεν]{.greek-added} αυτην αθετησαι[6:26]{.aside}

και ευθεως [αποστειλας]{.greek-omitted} ο βασιλευς [αποστειλας]{.greek-added} [σπεκουλατορα]{.greek-omitted} [σπεκουλατωρα]{.greek-added} επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθον]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι πινακι και εδωκεν [αυτην]{.greek-omitted} τω [κορασιω]{.greek-omitted} [κωρασιω]{.greek-added} και [το]{.greek-omitted} [τω]{.greek-added} [κορασιον]{.greek-omitted} [κωρασιον]{.greek-added} εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και [[―]{.gap}ν]{.greek-added} [ακουσαντες]{.corr} οι μαθηται αυτου ηλθον και ηραν [το]{.greek-omitted} [τω]{.greek-added} πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και [απηγγειλαν]{.greek-omitted} [απηλαν]{.greek-added} αυτω παντα [οσα]{.greek-added} [εδιδαξαν]{.greek-added} και οσα εποιησαν [και]{.greek-omitted} [οσα]{.greek-omitted} [εδιδαξαν]{.greek-omitted}[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις [εις]{.greek-added} [ερημ[―]{.gap}]{.greek-added} [αυτοι]{.corr} [κατ]{.corr} [ιδιαν]{.corr} εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added}[6:31]{.aside}

και απηλθον εις ερημον τοπον τω πλοιω κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδων]{.greek-added} αυτους υπαγοντας και επεγνωσαν αυτον πολλοι και [πεζη]{.greek-omitted} [πεζοι]{.greek-added} απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33]{.aside}

και [εξελθων]{.greek-omitted} [εξελθον]{.greek-added} [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [πολυν]{.greek-omitted} [ιδεν]{.greek-added} [πολλην]{.greek-added} οχλον και [εσπλαχνισθαι]{.greek-added} [εσπλαγχνισθη]{.greek-omitted} [[εσπλαχνισθ[η]{.unclear}]{.corr}]{.greek-added} επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο [αυτους]{.greek-added} διδασκειν [αυτους]{.greek-omitted} πολλα[6:34]{.aside}

και [ηδη]{.greek-omitted} [ιδη]{.greek-added} ωρας πολλης γενομενης [προσελθοντες]{.greek-omitted} [πρσελθοντες]{.greek-added} [αυτω]{.greek-omitted} [[πρωσελθοντες]{.corr}]{.greek-added} οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και [ηδη]{.greek-omitted} [ιδη]{.greek-added} ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας [αγορασωσιν]{.greek-omitted} [αγωρασωσιν]{.greek-added} εαυτοις αρτους [τι]{.greek-omitted} [οτι]{.greek-added} γαρ φαγωσιν ουκ [εχουσιν]{.greek-omitted} [εχωσιν]{.greek-added}[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις [δοτε]{.greek-omitted} [δοται]{.greek-added} αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες [αγορασωμεν]{.greek-omitted} [αγωρασω]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} [διακωσιων]{.greek-added} αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους [εχετε]{.greek-omitted} [εχεται]{.greek-added} [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} και [ιδετε]{.greek-omitted} [ιδατα]{.greek-added} και [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} λεγουσιν [αυτω]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον [και]{.greek-omitted} [ανα]{.greek-omitted} πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} ευλογησεν και [κατεκλασεν]{.greek-omitted} [κατεκασεν]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παρατηθωσιν]{.greek-added} αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερησεν]{.greek-added} πασιν[6:41]{.aside}

και εφαγον [παντες]{.greek-omitted} [παν]{.greek-added} [τες]{.greek-added} και εχορτασθησαν[6:42]{.aside}

και [ηραν]{.greek-omitted} [ηρον]{.greek-added} [κλασματων]{.greek-omitted} [ανακλασματων]{.greek-added} δωδεκα [κοφινους]{.greek-omitted} [πληρεις]{.greek-omitted} [κοφινων]{.greek-added} [πλειρης]{.greek-added} και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηνεγγασεν]{.greek-added} τους μαθητας αυτου [εμβηναι]{.greek-omitted} [εμβειναι]{.greek-added} εις το πλοιον και προαγειν εις το περαν προς βηθσαιδαν εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον [εν]{.greek-omitted} [μεσω]{.greek-omitted} [εμεσω]{.greek-added} [της]{.greek-omitted} [ης]{.greek-added} θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος [εαν]{.greek-added} [εναντιος]{.corr} αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν [αυτον]{.greek-added} φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ [ειδον]{.greek-added} αυτον [ειδον]{.greek-omitted} και εταραχθησαν και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις [θαρσειτε]{.greek-omitted} [θαρσειται]{.greek-added} εγω [[η]{.unclear}μι]{.greek-added} [ειμι]{.corr} μη [φοβεισθε]{.greek-omitted} [φ[ω]{.unclear}β[η]{.unclear}σθαι]{.greek-added} [[φ[ω]{.unclear}βεισθαι]{.corr}]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις [εξισταντο]{.greek-omitted} [εξησταντο]{.greek-added} και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} [πεπωρωμενη]{.greek-omitted} [πεπορρωμενη]{.greek-added}[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γεννησαρεθ]{.greek-added} και [προσωρμισθησαν]{.greek-omitted} [προσορμησθησαν]{.greek-added}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου [ηλθον]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} [και]{.greek-added} ευθεως επιγνοντες αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως [εχοντας]{.greek-omitted} [εχωντας]{.greek-added} περιφερειν οπου ηκουον οτι εκει εστιν[6:55]{.aside}

και οπου αν [εισεπορευετο]{.greek-omitted} [εισεπορευετω]{.greek-added} εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν [ηπτοντο]{.greek-omitted} [ηπτοντω]{.greek-added} [αυτου]{.corr} [εσωζοντο]{.greek-omitted} [εσωζοντω]{.greek-added}[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελθοντες απο [ιεροσολυμων]{.greek-omitted} [ιερωσωλυμων]{.greek-added}[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις χερσιν τουτ εστιν [ανιπτοις]{.greek-omitted} [ανυπτοις]{.greek-added} [χερσιν]{.greek-added} εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας χειρας ουκ εσθιουσιν κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και [απο]{.greek-omitted} [απ]{.greek-added} [αγοραις]{.greek-added} [αγορας]{.corr} εαν μη [βαπτισωνται]{.greek-omitted} [βαπτησονται]{.greek-added} ουκ εσθιουσιν και αλλα πολλα εστιν α [παρελαβον]{.greek-omitted} [περελαβον]{.greek-added} κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

[επειτα]{.greek-omitted} [επιτα]{.greek-added} επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου περιπατουσιν κατα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων αλλα ανιπτοις χερσιν εσθιουσιν [τον]{.greek-omitted} αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως [προεφητευσεν]{.greek-omitted} [ποεφητευσεν]{.greek-added} ησαιας περι υμων των υποκριτων ως γεγραπται [ουτος]{.greek-omitted} [ουτως]{.greek-added} ο λαος τοις χειλεσιν με τιμα η δε [γαρ]{.greek-added} καρδια αυτων [πορρω]{.greek-omitted} [πωρρω]{.greek-added} απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται [με]{.greek-omitted} [μαι]{.greek-added} διδασκοντες [διδασκαλιας]{.greek-omitted} [διδασκαλειας]{.greek-added} ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την [εντολην]{.greek-omitted} [εντωλην]{.greek-added} του [θεου]{.greek-abbr} [κρατειτε]{.greek-omitted} [κρατειται]{.greek-added} την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα [πολλα]{.greek-added} [παρομοια]{.greek-omitted} [παραμοια]{.greek-added} τοιαυτα [ποιειται]{.greek-added} πολλα [ποιειτε]{.greek-omitted}[7:8]{.aside}

και ελεγεν αυτοις καλως [αθετειτε]{.greek-omitted} [αθετειται]{.greek-added} την [εντολην]{.greek-omitted} [εντωλην]{.greek-added} του [θεου]{.greek-abbr} ινα την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων [τηρησητε]{.greek-omitted} [τηρησειται]{.greek-added}[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο [κακολογον]{.greek-added} [κακολογων]{.corr} [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} εαν [ειπη]{.greek-omitted} [ειπει]{.greek-added} [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο εστιν δωρον ο εαν εξ εμου [ωφεληθης]{.greek-omitted} [οφεληθεις]{.greek-added}[7:11]{.aside}

και [ουκετι]{.greek-omitted} [ουκετη]{.greek-added} [αφιετε]{.greek-omitted} [αφυεται]{.greek-added} αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωσει]{.greek-added} υμων η [παρεδωκατε]{.greek-omitted} [παρεδωκαται]{.greek-added} και [παρομοια]{.greek-omitted} [παρωμοια]{.greek-added} [πολλα]{.greek-added} τοιαυτα [πολλα]{.greek-omitted} [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added}[7:13]{.aside}

[και]{.greek-omitted} προσκαλεσαμενος [παντα[ς]{.unclear}]{.greek-added} [παντα]{.corr} τον οχλον ελεγεν αυτοις [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} μου παντες και [συνιετε]{.greek-omitted} [συνιεται]{.greek-added}[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον [ο]{.greek-omitted} [κοινησαι]{.greek-added} [ου]{.greek-added} δυναται [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted} αλλα τα εκπορευομενα απ αυτου εκεινα εστιν τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει [ωτα]{.greek-omitted} [ωττα]{.greek-added} ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων [αυτον]{.greek-omitted} [αυτων]{.greek-added} οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι [εστε]{.greek-omitted} [εσται]{.greek-added} ου [νοειτε]{.greek-omitted} [νοειται]{.greek-added} οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

ελεγεν δε οτι το [εκπορευομενον]{.greek-added} εκ του [ανθρωπου]{.greek-abbr} [εκπορευομενον]{.greek-omitted} εκεινο [κοινοι]{.greek-omitted} [κοινει]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν [γαρ]{.greek-omitted} [δε]{.greek-added} εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι [εκπορευονται]{.greek-omitted} [εκπορευον]{.greek-added} μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} [πλεονεξιαι]{.greek-omitted} [πλαιονεξιαι]{.greek-added} πονηριαι δολος ασελγεια οφθαλμος πονηρος [βλασφημια]{.greek-omitted} [βλασφιμιαι]{.greek-added} [υπερηφανια]{.greek-omitted} [υπεριφανιαι]{.greek-added} αφροσυνη[7:22]{.aside}

παντα ταυτα τα πονηρα εσωθεν [εκπορευεται]{.greek-omitted} [εισπορευεται]{.greek-added} και [κοινοι]{.greek-omitted} [κοινει]{.greek-added} τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ [ηδυνηθη]{.greek-omitted} [αιδυνηθη]{.greek-added} λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου [ης]{.greek-omitted} [ειχεν]{.greek-omitted} [εις]{.greek-added} [[η]{.unclear}χεν]{.greek-added} το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα προσεπεσεν [προς]{.greek-omitted} [επι]{.greek-added} τους ποδας [αυτου]{.greek-omitted} [του]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added}[7:25]{.aside}

ην δε η γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συροφοινικησσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης ευρεν [το]{.greek-omitted} [τω]{.greek-added} [δαιμονιον]{.greek-omitted} [δαιμωνιον]{.greek-added} εξεληλυθος και την θυγατερα [βεβλημενην]{.greek-omitted} [βεβλυμενην]{.greek-added} επι της κλινης[7:30]{.aside}

και [παλιν]{.greek-omitted} [παλην]{.greek-added} εξελθων εκ των οριων τυρου και σιδωνος ηλθεν προς την [θαλαν]{.greek-added} [θαλασσαν]{.greek-omitted} [[θαλασαν]{.corr}]{.greek-added} της γαλιλαιας ανα [μεσον]{.greek-omitted} [μεσων]{.greek-added} των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω [κωφον]{.greek-omitted} [κοφον]{.greek-added} [μογγιλαλον]{.greek-omitted} [μογιλαλον]{.greek-added} και παρακαλουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} ινα [επιθη]{.greek-omitted} [επιθει]{.greek-added} αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν εβαλεν τους δακτυλους αυτου εις τα [ωτα]{.greek-omitted} [ωττα]{.greek-added} αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} εστεναξεν και λεγει αυτω εφφαθα ο εστιν [διανοιχθητι]{.greek-omitted} [διανυχθητι]{.greek-added}[7:34]{.aside}

και ευθεως [διηνοιχθησαν]{.greek-omitted} [διηνυχθησαν]{.greek-added} αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ορθως[7:35]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστειλατω]{.greek-added} αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις [διεστελλετο]{.greek-omitted} [διεστειλατω]{.greek-added} μαλλον [περισσοτερον]{.greek-omitted} [περυσσοτερον]{.greek-added} εκηρυσσον[7:36]{.aside}

και [υπερπερισσως]{.greek-omitted} [υπερπερυσσος]{.greek-added} εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιεικεν]{.greek-added} και τους [κωφους]{.greek-omitted} [κοφους]{.greek-added} ποιει ακουειν [και]{.greek-omitted} [κε]{.greek-added} τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παμπολλου]{.greek-omitted} [παμπολου]{.greek-added} οχλου οντος και μη εχοντων τι φαγωσιν προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

[σπλαγχνιζομαι]{.greek-omitted} [σπλαχνιζωμε]{.greek-added} επι τον [λαον]{.greek-added} [οχλον]{.corr} οτι ηδη ημεραι τρεις προσμενουσιν μοι και ουκ [εχουσο[υ]{.unclear}]{.greek-added} [εχουσιν]{.corr} τι φαγωσιν[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις οικον αυτων [εκλυθησονται]{.greek-omitted} [εκληθησονται]{.greek-added} εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [οικουσιν]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε χορτασαι αρτων επ [ερημιας]{.greek-omitted} [ερημιαις]{.greek-added}[8:4]{.aside}

και επηρωτα αυτους ποσους [εχετε]{.greek-omitted} [εχεται]{.greek-added} αρτους οι δε ειπον επτα[8:5]{.aside}

και παρηγγειλεν τω οχλω [αναπεσειν]{.greek-omitted} [αναπεσιν]{.greek-added} επι της γης και λαβων τους επτα αρτους [ευχαριστησας]{.greek-omitted} εκλασεν και εδιδου τοις μαθηταις αυτου ινα παραθωσιν και παρεθηκαν τω οχλω[8:6]{.aside}

και [ειχον]{.greek-omitted} [ειχων]{.greek-added} ιχθυδια ολιγα και [ταυτα]{.greek-added} ευλογησας ειπεν [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν [παντες]{.greek-added} και ηραν [περισσευματα]{.greek-omitted} [περισευματα]{.greek-added} κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα [μερη]{.greek-omitted} [μερει]{.greek-added} [δαλμ[―]{.gap}νουθα]{.greek-added} [δαλμανουθα]{.corr}[8:10]{.aside}

και εξηλθον οι φαρισαιοι και [ηρξαντο]{.greek-omitted} [ηρξαντω]{.greek-added} [συζητειν]{.greek-omitted} [συζειτειν]{.greek-added} [αυτω]{.greek-omitted} [αυτων]{.greek-added} ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} [πειραζοντες]{.greek-omitted} [πειραζωντες]{.greek-added} αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} τι η γενεα αυτη σημειον επιζητει [αμην]{.greek-omitted} [αμ[ι]{.unclear}ν]{.greek-added} λεγω υμιν ει [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} τη γενεα [ταυτη]{.greek-omitted} [αυτη]{.greek-added} σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και [επελαθοντο]{.greek-omitted} [επελαθοντω]{.greek-added} λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων [ορατε]{.greek-omitted} [ωραται]{.greek-added} βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} οτι αρτους ουκ [εχετε]{.greek-omitted} [εχεται]{.greek-added} [ουπω]{.greek-omitted} [ουπο]{.greek-added} [νοειτε]{.greek-omitted} [νωειται]{.greek-added} ουδε [συνιετε]{.greek-omitted} [συνιεται]{.greek-added} [ετι]{.greek-omitted} [τι]{.greek-added} [πεπωρωμενην]{.greek-omitted} [πεπωρρωμενην]{.greek-added} [εχετε]{.greek-omitted} [εχεται]{.greek-added} την καρδιαν υμων[8:17]{.aside}

οφθαλμους [εχοντες]{.greek-omitted} [εχεται]{.greek-added} ου [βλεπετε]{.greek-omitted} [βλεποντες]{.greek-added} και [ωτα]{.greek-omitted} [ωττα]{.greek-added} εχοντες ουκ [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} και ου [μνημονευετε]{.greek-omitted} [μνημονευεται]{.greek-added}[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους [πεντακισχιλιους]{.greek-omitted} [πεντακισχιλοιους]{.greek-added} ποσους κοφινους πληρεις [κλασματω]{.greek-added} [κλασματων]{.corr} [ηρατε]{.greek-omitted} [ηραται]{.greek-added} λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους [ποσ[ας]{.unclear}]{.greek-added} [ποσων]{.corr} σπυριδων πληρωματα κλασματων [ηρατε]{.greek-omitted} [ηραται]{.greek-added} οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις [ουπω]{.greek-added} [πως]{.greek-omitted} [ου]{.greek-omitted} [συνιετε]{.greek-omitted} [συνιεται]{.greek-added}[8:21]{.aside}

και ερχεται εις [βηθσαιδαν]{.greek-omitted} [βιθσαιδαν]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος [τους]{.greek-added} [του]{.corr} τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα [ομματα]{.greek-omitted} [ωμματα]{.greek-added} αυτου επιθεις τας χειρας αυτω [επηρωτα]{.greek-omitted} [επειρωτα]{.greek-added} αυτον [ει]{.greek-omitted} [η]{.greek-added} τι βλεπει[8:23]{.aside}

και αναβλεψας ελεγεν βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα [ορω]{.greek-omitted} [ωρω]{.greek-added} περιπατουντας[8:24]{.aside}

[ειτα]{.greek-omitted} [ει]{.greek-added} [τα]{.greek-added} παλιν επεθηκεν τας χειρας [αυτου]{.greek-added} επι τους οφθαλμους αυτου και [εποιησεν]{.greek-omitted} [εποισεν]{.greek-added} αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψεν]{.greek-added} [τηλαυγως]{.greek-omitted} [τηλαυγος]{.greek-added} απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε ει[ς]{.unclear} την κωμην [εισελθης]{.greek-omitted} [εισελθεις]{.greek-added} μηδε [ειπης]{.greek-omitted} [ειπεις]{.greek-added} τινι εν τη [κωμη]{.greek-omitted} [πολη]{.greek-added}[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας [καισαρειας]{.greek-omitted} [κεσαρειας]{.greek-added} της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην [και]{.greek-omitted} αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} ειναι αποκριθεις [δε]{.greek-omitted} ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} αυτοις ινα μηδενι λεγωσιν περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και [αποδοκιμασθηναι]{.greek-omitted} [αποδοκημασθηναι]{.greek-added} [απο]{.greek-omitted} [αυτω]{.greek-added} [υπο]{.greek-added} των [αρχιεραιων]{.greek-added} [και]{.greek-added} [γραμματαιων]{.greek-added} [και]{.greek-added} πρεσβυτερων [και]{.greek-omitted} [των]{.greek-omitted} [αρχιερεων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} και αποκτανθηναι και [μετα]{.greek-omitted} [τρεις]{.greek-omitted} [τη]{.greek-added} [τη]{.greek-added} [[τρητη]{.corr}]{.greek-added} [ημερας]{.greek-omitted} [ημερα]{.greek-added} [αναστηναι]{.greek-omitted} [αναστησεται]{.greek-added}[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο [αυτον]{.greek-added} [επιτιμαν]{.greek-omitted} [επιτημαν]{.greek-added} [αυτω]{.greek-omitted}[8:32]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} τω πετρω λεγων υπαγε [σατανα]{.greek-added} οπισω μου [σατανα]{.greek-omitted} οτι ου [φρονεις]{.greek-omitted} [φρονιεις]{.greek-added} τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις οστις θελει [οπισω]{.greek-omitted} [οπησω]{.greek-added} μου [ακολουθειν]{.greek-omitted} [ελθειν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητ[ο]{.unclear}]{.greek-added} μοι[8:34]{.aside}

ος γαρ [αν]{.greek-omitted} [εαν]{.greek-added} θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την [εαυτου]{.greek-omitted} ψυχην [αυτου]{.greek-added} ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ [ωφελησει]{.greek-omitted} [οφελησει]{.greek-added} [τον]{.greek-added} [ανθρωπον]{.greek-abbr} εαν [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} τον κοσμον ολον και [ζημιωθη]{.greek-omitted} [ζημειωθει]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ εαν [επαισχυνθη]{.greek-omitted} [επεχυνθη]{.greek-added} με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [επαισχυνθησεται]{.greek-omitted} [επεσχυνθησεται]{.greek-added} [αυτον]{.greek-omitted} [αυτω]{.greek-added} οταν ελθη εν τη δοξη [του]{.greek-omitted} [πατρος]{.greek-omitted} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι εισιν τινες των [ωδε]{.greek-omitted} [οδε]{.greek-added} εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν ιδωσιν την βασιλειαν του [θεου]{.greek-abbr} [εληλυθυιαν]{.greek-omitted} [ελυληθεια]{.greek-added} εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και [τον]{.greek-added} ιωαννην και αναφερει αυτους [εις]{.greek-omitted} [ει]{.greek-added} ορος [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} κατ ιδιαν μονους και [μετεμορφωθη]{.greek-omitted} [μετεμορφοθη]{.greek-added} εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν [ως]{.greek-omitted} [ωση]{.greek-added} χιων οια [γναφευς]{.greek-omitted} [κναφες]{.greek-added} επι της γης ου [δυναται]{.greek-omitted} [δυνανται]{.greek-added} λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν [ημας]{.greek-omitted} [υμας]{.greek-added} ωδε ειναι και [ποιησωμεν]{.greek-omitted} [ποιεισωμεν]{.greek-added} σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυσει]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ [ηδει]{.greek-omitted} [ειδη]{.greek-added} τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} νεφελη επισκιαζουσα αυτοις και ηλθεν φωνη εκ της νεφελης [λεγουσα]{.greek-added} ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου [ακουετε]{.greek-omitted} [ακουεται]{.greek-added}[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} [διηγησονται]{.greek-added} α [ειδον]{.greek-omitted} [ιδων]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν [προς]{.greek-omitted} [εν]{.greek-added} [εαυτους]{.greek-omitted} [εαυτοις]{.greek-added} συζητουντες τι εστιν το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε [αποκριθεις]{.greek-omitted} [αποκρηθεις]{.greek-added} ειπεν αυτοις ηλιας μεν ελθων πρωτον [αποκαθιστα]{.greek-omitted} [αποκαθηστα]{.greek-added} παντα [καθως]{.greek-added} [και]{.greek-omitted} [πως]{.greek-omitted} γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και [εξουδενωθη]{.greek-omitted} [εξουδενοθη]{.greek-added}[9:12]{.aside}

αλλα λεγω υμιν οτι και [ηληας]{.greek-added} [ηλιας]{.corr} εληλυθεν και εποιησαν [εν]{.greek-added} αυτω [παντα]{.greek-added} οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον [πολυν]{.greek-omitted} [πολλην]{.greek-added} περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και [ευθεως]{.greek-omitted} [ευθεω]{.greek-added} πας ο [οχλος]{.greek-omitted} [λαος]{.greek-added} ιδων αυτον [εξεθαμβη[―]{.gap}ει]{.greek-added} [εξεθαμβηθη]{.greek-omitted} [[εξεθαμβηθει]{.corr}]{.greek-added} και προστρεχοντες [ησπαζοντο]{.greek-omitted} [εισπαζοντω]{.greek-added} αυτον[9:15]{.aside}

και επηρωτησεν τους γραμματεις τι [συζητειτε]{.greek-omitted} [συζητειται]{.greek-added} προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε [ηνεγκα]{.greek-omitted} [ηνεγγα]{.greek-added} τον υιον μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου [αν]{.greek-omitted} [εαν]{.greek-added} αυτον [καταλαβη]{.greek-omitted} [καταλαβει]{.greek-added} [ρησσει]{.greek-omitted} [ρυσσει]{.greek-added} αυτον και αφριζει και τριζει τους οδοντας αυτου και [ξηραινεται]{.greek-omitted} [ξηρενεται]{.greek-added} και [ειπον]{.greek-omitted} [ειπων]{.greek-added} τοις μαθηταις σου ινα [αυτο]{.greek-omitted} [αυτω]{.greek-added} εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [αυτω]{.greek-omitted} [αυτοις]{.greek-added} λεγει ω γενεα απιστος εως ποτε προς υμας [εσομαι]{.greek-omitted} [εσωμε]{.greek-added} εως ποτε [ανεξομαι]{.greek-omitted} [ανεξωμε]{.greek-added} υμων [φερετε]{.greek-omitted} [φερεται]{.greek-added} αυτον προς με[9:19]{.aside}

και [ηνεγκαν]{.greek-omitted} [ηνεγγαν]{.greek-added} αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και [πεσων]{.greek-omitted} [πεσον]{.greek-added} επι της γης [εκυλιετο]{.greek-omitted} [εκυλιετω]{.greek-added} αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επιρωτησεν]{.greek-added} [τον]{.greek-omitted} [τω]{.greek-added} [[πνευμα]{.greek-abbr}]{.greek-added} [[πατερα]{.greek-abbr}]{.corr} αυτου [ποσος]{.greek-omitted} [ποσο[υ]{.unclear}ς]{.greek-added} [χρονος]{.greek-omitted} [χρονο[υ]{.unclear}ς]{.greek-added} [[ποσως]{.corr}]{.greek-added} [[χρονως]{.corr}]{.greek-added} εστιν ως τουτο γεγονεν αυτω ο δε ειπεν παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ εβαλεν και εις υδατα ινα [απολεση]{.greek-omitted} [απολεσει]{.greek-added} αυτον αλλ ει τι δυνασαι βοηθησον [ημιν]{.greek-omitted} [υμιν]{.greek-added} [σπλαγχνισθεις]{.greek-omitted} [σπλαχνισθης]{.greek-added} εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [το]{.greek-omitted} ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [βοηθη]{.greek-added} μου [τη]{.greek-omitted} [τι]{.greek-added} [απιστια]{.greek-omitted} [απιστεια]{.greek-added}[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και [κωφον]{.greek-omitted} [κοφον]{.greek-added} εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι [εισελθης]{.greek-omitted} [εισελθεις]{.greek-added} εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον εξηλθεν και [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων [αυτον]{.greek-omitted} [αυτων]{.greek-added} κατ ιδιαν [δια]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} [ημεις]{.greek-omitted} [υμεις]{.greek-added} ουκ [ηδυνηθημεν]{.greek-omitted} [εδυνηθημεν]{.greek-added} εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται [ε]{.greek-added} [εξελθειν]{.greek-omitted} [ξελθειν]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} εις χειρας ανθρωπων και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε [ηγνοουν]{.greek-omitted} [ηγνωουν]{.greek-added} το ρημα και [εφοβουντο]{.greek-omitted} [εφοβουντω]{.greek-added} αυτον [επερωτησαι]{.greek-omitted} [επετησαι]{.greek-added}[9:32]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [διελογιζεσθε]{.greek-omitted} [διελογιζεσθαι]{.greek-added}[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} τις μειζων[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} εφωνησεν τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων [διακονος]{.greek-omitted} [δουλος]{.greek-added}[9:35]{.aside}

και λαβων [παιδιον]{.greek-omitted} [παιδιων]{.greek-added} εστησεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου εμε δεχεται και ος εαν εμε [δεξηται]{.greek-omitted} [δεχηται]{.greek-added} ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη δε αυτω [ο]{.greek-added} ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} τινα [εν]{.greek-added} τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ [ακολουθ[η]{.unclear}]{.greek-added} [ακολουθει]{.corr} [ημιν]{.greek-omitted} [υμιν]{.greek-added} και [εκωλυσαμεν]{.greek-omitted} [εκολλυσαμεν]{.greek-added} αυτον οτι ουκ [ακολουθ[η]{.unclear}]{.greek-added} [ακολουθει]{.corr} [ημιν]{.greek-omitted} [υμιν]{.greek-added}[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη [κωλυετε]{.greek-omitted} [κωλυεται]{.greek-added} αυτον ουδεις γαρ εστιν ος [ποιησει]{.greek-omitted} [ποιειση]{.greek-added} δυναμιν επι τω ονοματι μου και [δυνησεται]{.greek-omitted} [δυνησειται]{.greek-added} ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ εστιν καθ υμων υπερ υμων εστιν[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτησει]{.greek-added} υμας ποτηριον υδατος εν ονοματι [μου]{.greek-omitted} οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεσει]{.greek-added} τον μισθον αυτου[9:41]{.aside}

και ος εαν [σκανδαλιση]{.greek-omitted} [σκανδαλησει]{.greek-added} [ενα]{.greek-omitted} [εν]{.greek-added} των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον εστιν αυτω μαλλον ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν [σκανδαλη]{.greek-added} [σκανδαλιζη]{.greek-omitted} [[σκανδαληζη]{.corr}]{.greek-added} [σε[ι]{.unclear}]{.greek-added} [σε]{.corr} η χειρ σου αποκοψον αυτην [και]{.greek-added} [βαλε]{.greek-added} [απο]{.greek-added} [σου]{.greek-added} καλον σοι εστιν [κυλλον]{.greek-omitted} εις την ζωην εισελθειν [κυλλον]{.greek-added} η τας δυο χειρας εχοντα απελθειν εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο [σκολυξ]{.greek-added} [ο]{.greek-added} [ακυμητος]{.greek-added} [σκωληξ]{.greek-omitted} [αυτων]{.greek-omitted} [ου]{.greek-omitted} [τελευτα]{.greek-omitted} και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη [σε]{.greek-omitted} [σαι]{.greek-added} αποκοψον αυτον καλον [γαρ]{.greek-added} εστιν [σοι]{.greek-omitted} [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη [σε]{.greek-omitted} [σαι]{.greek-added} εκβαλε αυτον καλον σοι εστιν μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκοληξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια [αλι]{.greek-omitted} αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν [τινι]{.greek-omitted} [τινη]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added} [αρτυσετε]{.greek-omitted} [εχετε]{.greek-omitted} [αρτησεται]{.greek-added} [εχεται]{.greek-added} εν εαυτοις αλας και [ειρηνευετε]{.greek-omitted} [ειρηνευεται]{.greek-added} εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας δια του περαν του ιορδανου και [συμπορευονται]{.greek-omitted} [συμπορευοντε]{.greek-added} παλιν οχλοι προς αυτον και ως [ειωθει]{.greek-omitted} [ειωθη]{.greek-added} παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε [ειπον]{.greek-omitted} [ειπων]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [επετρεψεν]{.greek-omitted} [επεστρεψεν]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την [σκληροκαρδιαν]{.greek-omitted} [σκλιρωκαρδιαν]{.greek-added} υμων εγραψεν υμιν την [εντολην]{.greek-omitted} [εντωλην]{.greek-added} ταυτην[10:5]{.aside}

απο δε αρχης [κτισεως]{.greek-omitted} [κτησεως]{.greek-added} αρσεν και [θηλυ]{.greek-omitted} [θυλη]{.greek-added} [εποιησεν]{.greek-omitted} [εποιεισεν]{.greek-added} αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται [προς]{.greek-omitted} [την]{.greek-omitted} [τη]{.greek-added} γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι εισιν δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη [χωριζετω]{.greek-omitted} [χωρηζετω]{.greek-added}[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι [του]{.greek-omitted} αυτου επηρωτησαν αυτον[10:10]{.aside}

και λεγει [αυτο[υ]{.unclear}ς]{.greek-added} [αυτοις]{.corr} ος εαν απολυση την γυναικα αυτου και [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη απολυση τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται [επετιμων]{.greek-omitted} [επετημουν]{.greek-added} τοις προσφερουσιν[10:13]{.aside}

[ιδων]{.greek-omitted} [ιδον]{.greek-added} δε ο [ιησους]{.greek-abbr} ηγανακτησεν και ειπεν αυτοις [αφετε]{.greek-omitted} [αφεται]{.greek-added} τα παιδια ερχεσθαι προς με μη [κωλυετε]{.greek-omitted} [κολλυεται]{.greek-added} αυτα των γαρ τοιουτων [εστιν]{.greek-omitted} [εσται]{.greek-added} η βασιλεια [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added}[10:14]{.aside}

αμην λεγω υμιν [ος]{.greek-omitted} [ως]{.greek-added} εαν μη [δεξηται]{.greek-omitted} [δεξητε]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} ως [το]{.greek-added} [παιδιον]{.greek-omitted} [παιδιων]{.greek-added} [τουτο]{.greek-added} ου μη εισελθη εις αυτην[10:15]{.aside}

και [εναγκαλισαμενος]{.greek-omitted} [εναγγ[α]{.unclear}λισαμενος]{.greek-added} αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηυλογει]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} [πλουσιος]{.greek-added} προσδραμων [εις]{.greek-omitted} και [γονυπετησας]{.greek-omitted} [γωνυπετησας]{.greek-added} [αυτον]{.greek-omitted} [αυτω]{.greek-added} επηρωτα αυτον διδασκαλε αγαθε τι [ποιησω]{.greek-omitted} [ποιεισω]{.greek-added} ινα ζωην [αιωνιον]{.greek-omitted} [αιωνι]{.greek-added} [κληρονομησω]{.greek-omitted} [κληρωνομησω]{.greek-added}[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη [μοιχευσης]{.greek-omitted} μη [φονευσης]{.greek-omitted} [[μοιχευσεις]{.corr}]{.greek-added} μη [κλεψης]{.greek-omitted} [φονευσεις]{.greek-added} μη [ψευδομαρτυρησης]{.greek-omitted} [κλεψεις]{.greek-added} μη [αποστερησης]{.greek-omitted} [ψευδομαρτηρησεις]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} ταυτα παντα εφυλαξαμην εκ [νεοτητος]{.greek-omitted} [νεοτιτος]{.greek-added} μου [τι]{.greek-added} [ετι]{.greek-added} [υστερω]{.greek-added}[10:20]{.aside}

ο δε [ιησους]{.greek-omitted} εμβλεψας [αυτω]{.greek-omitted} [αυτον]{.greek-added} ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν [σοι]{.greek-omitted} [σε]{.greek-added} υστερει υπαγε [πολησον]{.greek-added} [παντα]{.greek-added} οσα εχεις [πωλησον]{.greek-omitted} και δος πτωχοις και εξεις [θησαυρον]{.greek-omitted} [θυσαυρον]{.greek-added} εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι [αρας]{.greek-omitted} [αρον]{.greek-added} τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ [εχων]{.greek-omitted} [εχον]{.greek-added} [κτηματα]{.greek-omitted} [κτειματα]{.greek-added} πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως [δυσκολως]{.greek-omitted} [δυσκο]{.greek-added} [λως]{.greek-added} οι τα [χρηματα]{.greek-omitted} [χρειματα]{.greek-added} εχοντες εις την [βασιλειαν]{.greek-omitted} [βασιλιαν]{.greek-added} του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται [εθαμβουντο]{.greek-omitted} [εθαμβουντω]{.greek-added} επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} [παλην]{.greek-added} αποκριθεις λεγει αυτοις [τεκνα]{.greek-omitted} πως δυσκολον εστιν τους [πεποιθοτας]{.greek-omitted} [πεποιθωτας]{.greek-added} επι [χρημασιν]{.greek-omitted} [τα]{.greek-added} [χρειματα]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

[ευκοπωτ[ο]{.unclear}]{.greek-added} [ευκοπωτερον]{.corr} εστιν καμηλον δια [της]{.greek-omitted} [τρυμαλιας]{.greek-omitted} [τριμαλιας]{.greek-added} [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added}[10:25]{.aside}

οι δε [περισσως]{.greek-omitted} [περυσσος]{.greek-added} εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [τω]{.greek-added} [θεω]{.greek-abbr} παντα γαρ δυνατα εστιν παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου [ημεις]{.greek-omitted} [υμεις]{.greek-added} αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν [του]{.greek-added} [ονοματος]{.greek-added} [εμου]{.greek-omitted} [μου]{.greek-added} και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε [τ[ο]{.unclear}ν]{.greek-added} [εν]{.corr} τη οδω αναβαινοντες [εις]{.greek-omitted} [ει]{.greek-added} [ιεροσολυμα]{.greek-omitted} [ιεροσωλυμα]{.greek-added} και ην [προαγων]{.greek-omitted} [προαγον]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και [εθαμβουντο]{.greek-omitted} [εθαμβουντω]{.greek-added} και ακολουθουντες [εφοβουντο]{.greek-omitted} [εθαμβουντω]{.greek-added} και παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω [συμβαινειν]{.greek-omitted} [συμβαιννειν]{.greek-added}[10:32]{.aside}

οτι ιδου αναβαινομεν εις [ιεροσολυμα]{.greek-omitted} [ιερωσωλυμα]{.greek-added} και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδοθησεται]{.greek-omitted} [παραδωθησεται]{.greek-added} τοις αρχιερευσιν και γραμματευσιν και κατακρινουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} θανατω και παραδωσουσιν αυτον τοις εθνεσιν[10:33]{.aside}

και [εμπαιξουσιν]{.greek-omitted} [εμπεξωσιν]{.greek-added} αυτω και μαστιγωσουσιν αυτον και [εμπτυσουσιν]{.greek-omitted} [εμπτισουσιν]{.greek-added} αυτω και [αποκτενουσιν]{.greek-omitted} [αποκτε]{.greek-added} [νουσιν]{.greek-added} αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και [προσπορευονται]{.greek-omitted} [προσπορευβονται]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε [θελομεν]{.greek-omitted} [θελωμεν]{.greek-added} ινα [ο]{.greek-omitted} [εαν]{.greek-omitted} [ον]{.greek-added} [σε]{.greek-added} [αιτησωμεν]{.greek-omitted} [ετησωμεν]{.greek-added} [ποιησης]{.greek-omitted} [ποιεισης]{.greek-added} [ημιν]{.greek-omitted} [υμιν]{.greek-added}[10:35]{.aside}

ο δε ειπεν αυτοις τι [θελετε]{.greek-omitted} [θελεται]{.greek-added} [ποιησαι]{.greek-omitted} [ποιησε]{.greek-added} με υμιν[10:36]{.aside}

οι δε ειπον αυτω δος [ημιν]{.greek-omitted} [υμιν]{.greek-added} ινα εις εκ δεξιων σου και εις εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ [οιδατε]{.greek-omitted} [ειδαται]{.greek-added} τι [ετεισθαι]{.greek-added} [αιτεισθε]{.greek-omitted} [[αιτεισθαι]{.corr}]{.greek-added} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} [πιειν]{.greek-omitted} [ποιειν]{.greek-added} το ποτηριον ο εγω πινω και το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζωμε]{.greek-added} βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω [πιεσθε]{.greek-omitted} [πιεσθαι]{.greek-added} και το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτιζωμε]{.greek-added} [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added}[10:39]{.aside}

το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις [ητοιμασται]{.greek-omitted} [ητοιμασθαι]{.greek-added}[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται [εν]{.greek-omitted} υμιν αλλ ος εαν θελη γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν θελη υμων γενεσθαι πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν [διακονηθηναι]{.greek-omitted} [διακονιθηναι]{.greek-added} αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος [εκαθητο]{.greek-omitted} [εκαθητω]{.greek-added} παρα την οδον [προσαιτων]{.greek-omitted} [προσετων]{.greek-added}[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και [επετιμων]{.greek-omitted} [επετημων]{.greek-added} αυτω πολλοι ινα [σιωπηση]{.greek-omitted} [σιοπηση]{.greek-added} ο δε πολλω μαλλον εκραζεν [υιε]{.greek-abbr} [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν [αυτον]{.greek-omitted} [αυτω]{.greek-added} φωνηθηναι και φωνουσιν τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49]{.aside}

ο δε [αποβαλων]{.greek-omitted} [αποβαλον]{.greek-added} το ιματιον αυτου αναστας ηλθεν προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} λεγει αυτω [ο]{.greek-omitted} [ιησους]{.greek-omitted} τι [σοι]{.greek-added} θελεις [ποιησω]{.greek-omitted} [ποιεισω]{.greek-added} [σοι]{.greek-omitted} ο δε τυφλος ειπεν αυτω ραββουνι ινα [αναβλεψω]{.greek-omitted} [αβλεψω]{.greek-added}[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω υπαγε η [πιστις]{.greek-omitted} [πιστ[ης]{.unclear}]{.greek-added} σου σεσωκεν σε και ευθεως ανεβλεψεν και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} και [βηθανιαν]{.greek-omitted} [βηθανειαν]{.greek-added} προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} εις την κωμην την [απεναντ[ε]{.unclear}]{.greek-added} [κατεναντι]{.greek-omitted} [[απεναντι]{.corr}]{.greek-added} υμων και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} πωλον δεδεμενον εφ ον [ουπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκεν]{.greek-added} λυσαντες αυτον [αγαγετε]{.greek-omitted} [αγαγεται]{.greek-added}[11:2]{.aside}

και εαν τις υμιν [ειπη]{.greek-omitted} [ειπει]{.greek-added} τι [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added} τουτο [ειπατε]{.greek-omitted} [ειπαται]{.greek-added} οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον [αποστελλει]{.greek-omitted} [αποστελει]{.greek-added} ωδε[11:3]{.aside}

[απηλθον]{.greek-omitted} [απηλθων]{.greek-added} δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

[και]{.greek-omitted} [κε]{.greek-added} τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added} λυοντες τον [πωλων]{.greek-added} [πωλον]{.corr}[11:5]{.aside}

οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} αυτοις καθως [ενετειλατο]{.greek-omitted} [ενετειλατω]{.greek-added} [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων εστρωσαν [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added} αλλοι [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} [εκοπτον]{.greek-omitted} [εκοπων]{.greek-added} [εκ]{.greek-omitted} [απο]{.greek-added} των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος [ο]{.greek-added} [ερχομενος]{.greek-added} εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

[και]{.greek-added} ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και [εισηλθεν]{.greek-omitted} [ησηλθεν]{.greek-added} εις [οεροσωλυμα]{.greek-added} [ιεροσολυμα]{.greek-omitted} [[ιεροσωλυμα]{.corr}]{.greek-added} ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος [παντα]{.greek-omitted} [παντας]{.greek-added} οψιας ηδη ουσης της ωρας εξηλθεν εις [βηθανιαν]{.greek-omitted} [βηθανειαν]{.greek-added} μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο [βηθανιας]{.greek-omitted} [βηθανειας]{.greek-added} επεινασεν[11:12]{.aside}

και ιδων συκην [μιαν]{.greek-added} [μακροθεν]{.greek-omitted} [μακρωθεν]{.greek-added} εχουσαν φυλλα [μονον]{.greek-added} ηλθεν ει αρα [τι]{.greek-added} ευρησει [τι]{.greek-omitted} εν αυτη και [ελθων]{.greek-omitted} [ελθον]{.greek-added} επ αυτην ουδεν ευρεν ει [μη]{.greek-omitted} [μι]{.greek-added} φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη [μηκετι]{.greek-omitted} [μηκετη]{.greek-added} εκ σου εις τον αιωνα μηδεις καρπον [φαγοι]{.greek-omitted} [φαγει]{.greek-added} και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις [ιεροσολυμα]{.greek-omitted} [ιερωσωλυμα]{.greek-added} και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο [εκβαλλειν]{.greek-omitted} [εκβαλλει]{.greek-added} τους [πωλουντας]{.greek-omitted} [πολουντας]{.greek-added} και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας καθεδρας των [πωλουντων]{.greek-omitted} [πολουντων]{.greek-added} τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ [ηφιεν]{.greek-omitted} [ιφυεν]{.greek-added} ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και εδιδασκεν λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης [κληθησεται]{.greek-omitted} [κληθησετε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε [εποιησατε]{.greek-omitted} αυτον [εποιεισαται]{.greek-added} σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ [αυτον]{.greek-omitted} οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και [οτε]{.greek-omitted} [οταν]{.greek-added} οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι [παραπορευομενοι]{.greek-omitted} [παραπωρευομενοι]{.greek-added} [ειδον]{.greek-omitted} [ιδον]{.greek-added} την συκην [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εκ ριζων[11:20]{.aside}

και [αναμνησθεις]{.greek-omitted} [αναμνησθης]{.greek-added} ο πετρος λεγει αυτω ραββι ιδε η συκη ην [κατηρασω]{.greek-omitted} [κατειρασω]{.greek-added} εξηρανται[11:21]{.aside}

και [αποκριθεις]{.greek-omitted} [αποκριθει]{.greek-added} ο [ιησους]{.greek-abbr} λεγει αυτοις [εχετε]{.greek-omitted} [εχεται]{.greek-added} [πιστιν]{.greek-omitted} [πιστην]{.greek-added} [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν [ειπη]{.greek-omitted} [ειπει]{.greek-added} τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη διακρι[θ]{.unclear}η [εν]{.greek-omitted} [τη]{.greek-omitted} [καρδια]{.greek-omitted} [αυτου]{.greek-omitted} [αλλα]{.greek-omitted} [πιστευση]{.greek-omitted} οτι α λεγει [γινεται]{.greek-omitted} [γυνεται]{.greek-added} εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα [αν]{.greek-omitted} [εαν]{.greek-added} [προσευχομενοι]{.greek-omitted} [προσευχωμενοι]{.greek-added} [αιτησθε]{.greek-omitted} [αιτεισθαι]{.greek-added} [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} οτι [λαμβανετε]{.greek-omitted} [λαμβανεται]{.greek-added} και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκηται]{.greek-added} προσευχομενοι [αφιετε]{.greek-omitted} [αφιεται]{.greek-added} ει τι [εχετε]{.greek-omitted} [εχεται]{.greek-added} κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ [αφιετε]{.greek-omitted} [αφιεται]{.greek-added} [και]{.greek-added} ουδε ο [πατηρ]{.greek-abbr} υμων ο εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} [αφησει]{.greek-omitted} [αφηση]{.greek-added} τα παραπτωματα υμων[11:26]{.aside}

και ερχονται [παλιν]{.greek-omitted} [παλην]{.greek-added} εις [ιεροσολυμα]{.greek-omitted} [ιεροσωλυμα]{.greek-added} και εν τω ιερω περιπατουντος αυτου ερχονται προς [αυτων]{.greek-added} [αυτον]{.corr} οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω [καγω]{.greek-added} υμας [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και [αποκριθητε]{.greek-omitted} [αποκριθηται]{.greek-added} μοι και ερω [υμιν]{.greek-omitted} εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ ανθρωπων αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογηζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει δια τι [ουν]{.corr} ουκ [επιστευσατε]{.greek-omitted} [επιστευσαται]{.greek-added} αυτω[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον απαντες γαρ ειχον τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες λεγουσιν [τον]{.greek-added} [τω]{.corr} [ιησου]{.greek-abbr} [ουδ]{.greek-added} [ουκ]{.corr} οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και περιεθηκεν [αυτω]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [οκοδωμησεν]{.greek-added} πυργον και [εξεδοτο]{.greek-omitted} [εξεδοτω]{.greek-added} αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και απεστειλεν προς τους [γεοργους]{.greek-added} [γεωργους]{.corr} [δουλον]{.greek-added} τω καιρω [δουλον]{.greek-omitted} ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον [εδειραν]{.greek-omitted} [απεκτειναν]{.greek-added} και απεστειλαν κενον[12:3]{.aside}

και παλιν απεστειλεν προς αυτους αλ[λ]{.greek-supplied}ον δουλον κακεινον λιθοβολησαντες εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και [παλιν]{.greek-omitted} [παλην]{.greek-added} αλλον απεστειλεν κακεινον απεκτειναν και πολλους αλλους [και]{.greek-added} τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα [υιον]{.greek-abbr} [εχων]{.greek-omitted} [εχον]{.greek-added} αγαπητον αυτου απεστειλεν και αυτον [εσχατον]{.greek-added} προς αυτους [εσχατον]{.greek-omitted} λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και [ημων]{.greek-omitted} [υμων]{.greek-added} εσται η [κληρονομια]{.greek-omitted} [κληρονωμια]{.greek-added}[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν [ποιησει]{.greek-omitted} [ποιεισει]{.greek-added} ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και [δωσει]{.greek-omitted} τον αμπελωνα [εκδωσειται]{.greek-added} αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην [ανεγνωτε]{.greek-omitted} [εγνωκειται]{.greek-added} λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδωκιμασαν]{.greek-added} οι οικοδομουντες [ουτος]{.greek-omitted} [ουτως]{.greek-added} εγενηθη εις [κεφαλην]{.greek-omitted} [κεφαλιν]{.greek-added} γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} αυτη και εστιν θαυμαστη εν οφθαλμοις [ημων]{.greek-omitted} [υμων]{.greek-added}[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι [την]{.greek-added} [παραβολην]{.greek-added} προς αυτους [[ε]{.unclear}λαλη]{.greek-added} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [ειπεν]{.greek-omitted} και αφεντες αυτον απηλθον[12:12]{.aside}

και αποστελλουσιν προς αυτον τινας των φαρισαιων και των [ηρωδιαν[ον]{.unclear}]{.greek-added} [ηρωδιανων]{.corr} ινα αυτον αγρευσωσιν λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και ου [μελει]{.greek-omitted} [σοι]{.greek-omitted} [μελη]{.greek-added} [σει]{.greek-added} περι ουδενος ου γαρ βλεπεις εις [προσωπον]{.greek-omitted} [πρωσωπον]{.greek-added} [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε [ειδως]{.greek-omitted} [οιδως]{.greek-added} αυτων την υποκρισιν ειπεν αυτοις τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} [φερετε]{.greek-omitted} [φερεται]{.greek-added} μοι [δηναριον]{.greek-omitted} [διναριον]{.greek-added} ινα ιδω[12:15]{.aside}

οι δε [η]{.unclear}νεγκαν και λεγει αυτοις τινος η [εικων]{.greek-omitted} [εικον]{.greek-added} αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [αποδοτε]{.greek-omitted} [αποδωται]{.greek-added} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και [επηρωτησαν]{.greek-omitted} [επηρω]{.greek-added} [τησαν]{.greek-added} αυτον λεγοντες[12:18]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν [ημιν]{.greek-omitted} [υμιν]{.greek-added} οτι εαν τινος αδελφος [αποθανη]{.greek-omitted} [αποθανει]{.greek-added} και [καταλιπη]{.greek-omitted} [καταλυπει]{.greek-added} γυναικα και τεκνα μη αφη ινα [λαβη]{.greek-omitted} [λαβει]{.greek-added} ο αδελφος αυτου την γυναικα αυτου και εξαναστηση σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα αδελφοι ησαν και ο πρωτος ελαβεν γυναικα και [αποθνησκων]{.greek-omitted} [αποθνεισκον]{.greek-added} ουκ αφηκεν σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν και ουδε αυτος αφηκεν σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και [ελαβον]{.greek-omitted} [ελαβων]{.greek-added} αυτην οι επτα και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατων]{.greek-added} [[εσχατον]{.corr}]{.greek-added} παντων απεθανεν και η γυνη[12:22]{.aside}

εν τη [ουν]{.greek-added} αναστασει οταν αναστωσιν τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις ου δια τουτο [π[α]{.unclear}]{.greek-added} [πλανασθε]{.greek-omitted} [[πλανασθαι]{.corr}]{.greek-added} μη [ειδοτες]{.greek-omitted} [ιδωτες]{.greek-added} τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ [ανεγνωτε]{.greek-omitted} [ανεγνω]{.greek-added} εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεω]{.greek-added} επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} [αβραμ]{.greek-added} [αβρααμ]{.corr} και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ [πλανασθε]{.greek-omitted} [πλανασθαι]{.greek-added}[12:27]{.aside}

και προσελθων εις των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ακουσας αυτων συζητουντων ειδως οτι καλως αυτοις απεκριθη επηρωτησεν [αυτον]{.greek-omitted} [αυτω]{.greek-added} ποια εστιν πρωτη παντων [εντολη]{.greek-omitted} [εντωλη]{.greek-added}[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω [οτι]{.greek-omitted} πρωτη παντων [εντωλη]{.greek-added} [των]{.greek-omitted} [εντολων]{.greek-omitted} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της [ψυχης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη [παντων]{.greek-added} [εντολη]{.greek-omitted} [εντωλη]{.greek-added}[12:30]{.aside}

και δευτερα [ομοια]{.greek-omitted} [ομοι]{.greek-added} αυτη αγαπησεις [τον]{.greek-omitted} [των]{.greek-added} πλησιον σου ως σεαυτον μειζων τουτων αλλη [εντολη]{.greek-omitted} [εντωλη]{.greek-added} ουκ εστιν[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις εστιν και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ [ολης]{.greek-omitted} [[ω]{.unclear}λης]{.greek-added} [της]{.greek-omitted} καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και [το]{.greek-omitted} [τω]{.greek-added} αγαπαν τον πλησιον ως εαυτον πλειον εστιν παντων [των]{.greek-omitted} [ολοκαυτωματων]{.greek-omitted} [ολοκαυτοματων]{.greek-added} και [[ο]{.unclear}υσιων]{.greek-added} [θυσιων]{.corr}[12:33]{.aside}

και ο [ιησους]{.greek-abbr} [ιδων]{.greek-omitted} [ιδον]{.greek-added} [αυτον]{.greek-omitted} οτι νουνεχως [απεκριθη]{.greek-omitted} [απεκριθει]{.greek-added} ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ελεγεν διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} εστιν [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου εστιν και ο πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} απο των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} των θελοντων [ε[πι]{.unclear}]{.greek-added} [εν]{.corr} στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και [πρωτοκαθεδριας]{.greek-omitted} [πρωτοκαθεδρειαις]{.greek-added} εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτωκλησιαις]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των [χηρων]{.greek-omitted} [χειρων]{.greek-added} και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου [εθεωρει]{.greek-omitted} [εθεορει]{.greek-added} πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια [χηρα]{.greek-omitted} [χειρα]{.greek-added} πτωχη εβαλεν λεπτα δυο ο εστιν κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου λεγει αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των βαλλοντων εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισευματος]{.greek-added} αυτοις εβαλον αυτη δε εκ της [υστερηεως]{.greek-added} [υστερησεως]{.corr} [αυτ[οι]{.unclear}ς]{.greek-added} [αυτης]{.corr} παντα οσα ειχεν εβαλεν ολον τον βιον [αυτ[ου]{.unclear}ς]{.greek-added} [αυτης]{.corr}[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και [ποταπαι]{.greek-omitted} [ποταποι]{.greek-added} οικοδομαι[13:1]{.aside}

και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [λεγει]{.greek-added} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} αυτω [βλεπεις]{.greek-omitted} [βλεπει]{.greek-added} [τας]{.greek-added} [ταυτας]{.corr} τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [ος]{.greek-omitted} [λιθον]{.greek-added} [εως]{.greek-added} ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε [ημιν]{.greek-omitted} [υμιν]{.greek-added} ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [συντελεισθαι]{.greek-omitted} [συντελησθαι]{.greek-added}[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας [πλανηση]{.greek-omitted} [πλανησει]{.greek-added}[13:5]{.aside}

πολλοι γαρ ελευσονται επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουσηται]{.greek-added} πολεμους και ακοας πολεμων μη [θροεισθε]{.greek-omitted} [θροεισθαι]{.greek-added} δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και [εσονται]{.greek-omitted} [εσον]{.greek-added} [λιμοι]{.greek-omitted} [λυμοι]{.greek-added} και ταραχαι [αρχαι]{.greek-omitted} [αρχη]{.greek-added} [ωδινων]{.greek-omitted} [ωδυνων]{.greek-added} ταυτα[13:8]{.aside}

[βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} δε υμεις εαυτους παραδωσουσιν γαρ υμας εις συνεδρια και εις συναγωγας [δαρησεσθε]{.greek-omitted} [δαρησασθαι]{.greek-added} και επι [ηεγμωνων]{.greek-added} [ηγεμονων]{.corr} [δε]{.greek-added} και [βασιλ[ω]{.unclear}]{.greek-added} [βασιλεων]{.corr} [σταθησεσθε]{.greek-omitted} [σταθησεσθαι]{.greek-added} [ενεκεν]{.greek-omitted} [εγεκεν]{.greek-added} εμου εις [μαρ]{.greek-added} [μαρτυριον]{.greek-omitted} [τυριον]{.greek-added} αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [προμεριμναται]{.greek-added} τι [λαλησητε]{.greek-omitted} [λαλησηται]{.greek-added} μηδε [μελετατε]{.greek-omitted} [μελεταται]{.greek-added} αλλ ο εαν [δοθη]{.greek-omitted} [δωθη]{.greek-added} υμιν εν εκεινη τη ωρα τουτο [λαλειτε]{.greek-omitted} [λαληται]{.greek-added} ου γαρ [εστε]{.greek-omitted} [εσται]{.greek-added} υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος [ουτος]{.greek-omitted} [ουτως]{.greek-added} σωθησεται[13:13]{.aside}

οταν δε [ιδητε]{.greek-omitted} [ιδηται]{.greek-added} το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου [εστως]{.greek-omitted} [εστος]{.greek-added} οπου ου δει ο [αναγινωσκων]{.greek-omitted} [αναγινοσκον]{.greek-added} [νοειτω]{.greek-omitted} [νοητω]{.greek-added} τοτε οι εν τη ιουδαια φευγετωσαν εις τα [ορη]{.greek-omitted} [ορει]{.greek-added}[13:14]{.aside}

ο δε επι του δωματος μη [καταβατω]{.greek-omitted} [καταβατο]{.greek-added} εις την οικιαν μηδε εισελθετω [τι]{.greek-added} [αρε]{.greek-added} [αραι]{.corr} [τι]{.greek-omitted} εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη [επιστρεψατω]{.greek-omitted} [επιστρεψατο]{.greek-added} εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη [γενηται]{.greek-omitted} [γενη]{.greek-added} η φυγη υμων [χειμωνος]{.greek-omitted} [χημωνος]{.greek-added}[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι [θλιψις]{.greek-omitted} [θλιψεις]{.greek-added} οια ου γεγονεν τοιαυτη απ αρχης [κτισεως]{.greek-omitted} [κτησεως]{.greek-added} ης [εκτισεν]{.greek-omitted} [εκτησεν]{.greek-added} ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει [μη]{.greek-omitted} [μι]{.greek-added} [κυριος]{.greek-abbr} εκολοβωσεν τας ημερας ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο εκολοβωσεν τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν [ειπη]{.greek-omitted} [ειπει]{.greek-added} ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευηται]{.greek-added} [[πιστευσηται]{.corr}]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και [ψευδοπροφηται]{.greek-omitted} [ψευδοπρωφηται]{.greek-added} και δωσουσιν σημεια και τερατα προς το [αποπλαναν]{.greek-omitted} [πλαναν]{.greek-added} ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} ιδου προειρηκα υμιν [παντα]{.greek-omitted} [απαντα]{.greek-added}[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την [θλιψιν]{.greek-omitted} [θληψιν]{.greek-added} [των]{.greek-added} [ημερων]{.greek-added} [εκεινην]{.greek-omitted} [εκεινων]{.greek-added} ο ηλιος [σκοτισθησεται]{.greek-omitted} [σκοτεισθησεται]{.greek-added} και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες [εσονται]{.greek-added} [εκ]{.greek-added} του [ουρανου]{.greek-abbr} [εσονται]{.greek-omitted} [εκπιπτοντες]{.greek-omitted} [πιπτοντες]{.greek-added} και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν [νεφελαις]{.greek-omitted} [ναιφελαις]{.greek-added} μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των [τεσαρων]{.greek-added} [τεσσαρων]{.corr} ανεμων απ ακρου γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την [παραβολην]{.greek-omitted} [παραβολολην]{.greek-added} οταν [αυτης]{.greek-omitted} ηδη ο κλαδος [αυτης]{.greek-added} [γυνεται]{.greek-added} απαλος [γενηται]{.greek-omitted} και εκφυη τα φυλλα [γινωσκετε]{.greek-omitted} [γυνοσκεται]{.greek-added} οτι εγγυς το θερος [εστιν]{.greek-omitted}[13:28]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις οταν [ιδηται]{.greek-added} ταυτα [γυνωσκεται]{.greek-added} [ιδητε]{.greek-omitted} [γινομενα]{.greek-omitted} [γινωσκετε]{.greek-omitted} οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρεις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μη παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης η [της]{.greek-added} ωρας ουδεις [οιδεν]{.greek-omitted} [ιδεν]{.greek-added} ουδε οι αγγελοι οι εν [ουρανω]{.greek-abbr} ουδ[ε]{.unclear} ο υιος ει [μη]{.greek-omitted} [μι]{.greek-added} ο [πατηρ]{.greek-abbr}[13:32]{.aside}

[βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} [αγρυπνειτε]{.greek-omitted} [αγρυπνειται]{.greek-added} και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ουκ [οιδατε]{.greek-omitted} [ειδαται]{.greek-added} γαρ ποτε ο καιρος εστιν[13:33]{.aside}

[ω]{.greek-added} [ως]{.corr} [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω [θυρωρω]{.greek-omitted} [θυρορω]{.greek-added} ενετειλατο ινα γρηγορη[13:34]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} ουν ουκ [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η μεσονυκτιου η [αλεκτοροφωνιας]{.greek-omitted} [αλεκτορωφωνιας]{.greek-added} η πρωι[13:35]{.aside}

μη [ελθων]{.greek-omitted} [ελθον]{.greek-added} εξαιφνης ευρη υμας καθευδοντας[13:36]{.aside}

[α]{.greek-omitted} [ο]{.greek-added} δε υμιν λεγω πασιν λεγω [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added}[13:37]{.aside}

### Chapter 14

ην δε τ[ο]{.unclear} πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν [δολω]{.greek-omitted} [δωλω]{.greek-added} κρατησ[α]{.unclear}ντες [αυτον]{.greek-added} αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη [εορτη]{.greek-omitted} [εωρτη]{.greek-added} μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν [βηθανια]{.greek-omitted} [βηθανει]{.greek-added} εν τη οικια [σιμωνος]{.greek-omitted} [σημωνος]{.greek-added} του λεπρου κατακειμενου αυτου ηλθεν γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης πολυτελους και συντριψασα [το]{.greek-omitted} [τον]{.greek-added} αλαβαστρον [και]{.greek-added} κατεχεεν [αυτου]{.greek-omitted} κατα της κεφαλης [αυτου]{.greek-added}[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η [απωλεια]{.greek-omitted} [απολυα]{.greek-added} αυτη του μυρου [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added}[14:4]{.aside}

[ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} γαρ τουτο [το]{.greek-added} [μυρον]{.greek-added} πραθηναι επανω [τριακωσιων]{.greek-added} [τριακοσιων]{.corr} [δηναριων]{.greek-omitted} [δυναριων]{.greek-added} και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αφετε]{.greek-omitted} [αφεται]{.greek-added} αυτην [τι]{.greek-omitted} [τη]{.greek-added} αυτη κοπους [παρεχετε]{.greek-omitted} [παρεχεται]{.greek-added} καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους [εχετε]{.greek-omitted} [εχεται]{.greek-added} μεθ εαυτων και οταν [θελητε]{.greek-omitted} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} ευ [ποιησαι]{.greek-omitted} [ποεισαι]{.greek-added} εμε δε ου παντοτε [εχετε]{.greek-omitted} [εχεται]{.greek-added}[14:7]{.aside}

ο εσχεν αυτη εποιησεν προελαβεν μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης εις των δωδεκα απηλθεν προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο αυτω [αργυριον]{.greek-omitted} [αργυρι]{.greek-added} δουναι και εζητει πως [αυτον]{.greek-added} ευκαιρως [αυτον]{.greek-omitted} παραδω[14:11]{.aside}

και τη πρωτη ημερα των [αζυμων]{.greek-omitted} [αζυμω]{.greek-added} οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα [φαγης]{.greek-omitted} [φαγεις]{.greek-added} το πασχα[14:12]{.aside}

και αποστελλει δυο των [μαθητων]{.greek-omitted} αυτου [και]{.greek-omitted} λεγει αυτοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων [ακολουθησατε]{.greek-omitted} [ακολουθησαται]{.greek-added} αυτω[14:13]{.aside}

και οπου εαν εισελθη [ειπατε]{.greek-omitted} [ειπαται]{.greek-added} τω οικοδεσποτη οτι ο διδασκαλος λεγει που εστιν το [καταλυμα]{.greek-omitted} [καταλημα]{.greek-added} οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν [δειξει]{.greek-omitted} [δειξη]{.greek-added} [ανωγεον]{.greek-omitted} [ανογεον]{.greek-added} μεγα εστρωμενον ετοιμον εκει [ετοιμασατε]{.greek-omitted} [ετοιμασαται]{.greek-added} [ημιν]{.greek-omitted} [υμιν]{.greek-added}[14:15]{.aside}

και εξηλθον οι μαθηται αυτου [και]{.corr} [ηλθον]{.corr} εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο [εσθιων]{.greek-omitted} [εσθιον]{.greek-added} μετ εμου[14:18]{.aside}

οι δε [ηρξαντο]{.greek-omitted} [ηρξαντω]{.greek-added} λυπεισθαι και λεγειν [αυτω]{.greek-omitted} εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο [εμβαπτομενος]{.greek-omitted} [εμβαπτωμενος]{.greek-added} μετ εμου εις το [τρυβλιον]{.greek-omitted} [τριβλυον]{.greek-added}[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως [γεγραπται]{.greek-omitted} [γεγραπαι]{.greek-added} περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} καλον ην αυτω [ει]{.greek-omitted} [η]{.greek-added} ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας εκλασεν και εδωκεν αυτοις και ειπεν [λαβετε]{.greek-omitted} [λαβεται]{.greek-added} [φαγετε]{.greek-omitted} τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} σωμα μου[14:22]{.aside}

[κα]{.greek-added} [και]{.corr} λαβων [το]{.corr} ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο εστιν [[εστι]{.corr}]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του [του]{.greek-added} γενηματος της αμπελου εως της ημερας εκεινης οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} [πο]{.greek-added} [πινω]{.greek-omitted} [[πιω]{.corr}]{.greek-added} καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεσθαι]{.greek-added} εν εμοι εν τη [νυκτι]{.greek-omitted} [νυτι]{.greek-added} ταυτη οτι γεγραπται παταξω τον ποιμενα και [διασκοσπισθησεται]{.greek-added} [διασκορπισθησεται]{.greek-omitted} [[διασκορσπισθησεται]{.corr}]{.greek-added} τα προβατα [της]{.greek-added} [ποιμ[η]{.unclear}]{.greek-added} [[ποιμνης]{.corr}]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες [σκανδαλισθησονται]{.greek-omitted} [κανδαλισθησονται]{.greek-added} αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν [η]{.greek-omitted} [δις]{.greek-omitted} [ι]{.greek-added} [δυς]{.greek-added} [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} [απαρνηση]{.greek-omitted} [απαρνησει]{.greek-added} με[14:30]{.aside}

ο δε εκπερισσου ελεγεν [μαλλον]{.greek-omitted} [μαλλονν]{.greek-added} εαν με δεη συναποθανειν σοι ου μη σε απαρνησωμαι [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added} δε και παντες ελεγον[14:31]{.aside}

και ερχονται [ς]{.greek-added} [εις]{.corr} χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσημανι]{.greek-added} και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησαται]{.greek-added} ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου [και]{.greek-omitted} ηρξατο εκθαμβεισθαι και [αδημονειν]{.greek-omitted} [αδημωνειν]{.greek-added}[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου [μεινατε]{.greek-omitted} [μειναται]{.greek-added} ωδε και [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added}[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι [παρενεγκε]{.greek-omitted} [παρενεγγε]{.greek-added} [απ]{.greek-added} [εμου]{.greek-added} το ποτηριον [απ]{.greek-omitted} [εμου]{.greek-omitted} τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν [γρηγορησαι]{.greek-omitted} [γρηγορεισαι]{.greek-added}[14:37]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ινα μη [εισελθητε]{.greek-omitted} [εισελθηται]{.greek-added} εις [πειρασμον]{.greek-omitted} [πειραμον]{.greek-added} το μεν [πνευμα]{.greek-abbr} προθυμον [η]{.greek-omitted} [ει]{.greek-added} δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας [ησαν]{.greek-omitted} [εισαν]{.greek-added} γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [κατα]{.greek-added} [κατα]{.greek-added} [κατ[α]{.unclear}βαρινομενοι]{.greek-added} [βαρινομενοι]{.greek-added} και ουκ [ηδεισαν]{.greek-omitted} [ειδησαν]{.greek-added} τι αυτω αποκριθωσιν[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις [καθευδετε]{.greek-omitted} [καθευδεσθαι]{.greek-added} [το]{.greek-added} λοιπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} απεχει ηλθεν η ωρα ιδου [παραδιδοται]{.greek-omitted} [παραδιδωται]{.greek-added} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας [των]{.greek-omitted} αμαρτωλων[14:41]{.aside}

[εγειρεσθε]{.greek-omitted} [εγειρεσθαι]{.greek-added} αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και [ευθεω]{.greek-added} [ευθεως]{.corr} ετι αυτου λαλουντος [παραγινεται]{.greek-omitted} [παραγυνεται]{.greek-added} ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα [των]{.greek-omitted} [τω]{.greek-added} [αρχιερεων]{.greek-omitted} [αρχιεραιων]{.greek-added} και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και των πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν [φιλησω]{.greek-omitted} [φυλησω]{.greek-added} αυτος εστιν [κρατησατε]{.greek-omitted} [κρατησαται]{.greek-added} [αυτων]{.greek-added} [αυτον]{.corr} και [απαγαγετε]{.greek-omitted} [απαγατε]{.greek-added} [[απαγαγεται]{.corr}]{.greek-added} ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει [αυτω]{.greek-omitted} ραββι ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας αυτων [προς]{.greek-added} [αυτον]{.greek-added} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επεσεν]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} [αυτοις]{.corr} ως επι λη[σ]{.unclear}την [εξηλθετε]{.greek-omitted} [εξηλθεται]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν [με]{.greek-omitted} [μαι]{.greek-added}[14:48]{.aside}

καθ ημεραν [ημην]{.greek-omitted} [ημιν]{.greek-added} προς υμας [διδασκων]{.greek-added} εν τω ιερω [διδασκων]{.greek-omitted} και ουκ [εκρατησατε]{.greek-omitted} [αικρατησαται]{.greek-added} με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω [περιβεβλημενος]{.greek-omitted} [περιβεβλυμενος]{.greek-added} [σινδονα]{.greek-omitted} [σινδωνα]{.greek-added} επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε [καταλιπων]{.greek-omitted} [καταλυπον]{.greek-added} την [σινδονα]{.greek-omitted} [σινδωνα]{.greek-added} γυμνος εφυγεν [αυτ]{.greek-added} [απ]{.corr} αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και συνερχονται αυτω παντες οι αρχιερεις και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added} και οι [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added}[14:53]{.aside}

και ο πετρος [απο]{.greek-omitted} [μακροθεν]{.greek-omitted} ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ [ευρισκον]{.greek-omitted} [ευρησκον]{.greek-added}[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι [μαρτυριαι]{.greek-omitted} [ματυριαι]{.greek-added} ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added}[14:57]{.aside}

οτι [ημεις]{.greek-omitted} [υμεις]{.greek-added} ηκουσαμεν αυτου λεγοντος οτι εγω [καταλυ]{.greek-added} [καταλυσω]{.corr} τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και [ουδε]{.greek-omitted} [ουδ]{.greek-added} ουτως [ησι]{.greek-added} [ιση]{.greek-omitted} [ην]{.greek-omitted} η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον επηρωτησεν [αυτον]{.greek-added} [τον]{.corr} [ιησουν]{.greek-abbr} [λεγων]{.greek-omitted} [λεγον]{.greek-added} ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν [απεκρινατο]{.greek-omitted} [απεκρινατω]{.greek-added} [παλιν]{.greek-omitted} [παλην]{.greek-added} ο αρχιερευς [επηρωτα]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [[θεου]{.greek-abbr}]{.greek-added} [του]{.greek-added} [ευλογητου]{.greek-omitted} [ευλογιτου]{.greek-added}[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [καθημενον]{.greek-added} εκ δεξιων [καθημενον]{.greek-omitted} της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

[ηκουσατε]{.greek-omitted} [ηκουσαται]{.greek-added} της [βλασφημιας]{.greek-omitted} [βλασφημηας]{.greek-added} τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν [αυτω]{.greek-omitted} [αυτου]{.greek-added} και περικαλυπτειν το [προσωπον]{.greek-omitted} [πρωσωπον]{.greek-added} αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον και οι [υπηρεται]{.greek-omitted} [υπυρεται]{.greek-added} ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [ελαβον]{.greek-added}[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον [θερμαινομενον]{.greek-omitted} [θερμενομενον]{.greek-added} [εμβλεψασα]{.greek-omitted} [εμβλεψας]{.greek-added} αυτω λεγει και συ μετα του [ναζαρηνου]{.greek-omitted} [ναζωρινου]{.greek-added} [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο [αυτον]{.greek-added} λεγων ουκ [οιδα]{.greek-omitted} [ιδα]{.greek-added} ουδε [επισταμαι]{.greek-omitted} [επισταμε]{.greek-added} τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και [αλεκτωρ]{.greek-omitted} [αλεκτορ]{.greek-added} εφωνησεν[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστωσιν]{.greek-added} οτι [ουτος]{.greek-omitted} [ουτως]{.greek-added} εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ειρνειτο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο [ομνυειν]{.greek-added} [και]{.greek-added} αναθεματιζειν [και]{.greek-omitted} [ομνυναι]{.greek-omitted} οτι ουκ [οιδα]{.greek-omitted} [ιδα]{.greek-added} τον [ανθρωπον]{.greek-abbr} τουτον ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added}[14:71]{.aside}

και εκ δευτερου [αλεκτωρ]{.greek-omitted} [αλεκτορ]{.greek-added} εφωνησεν και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι [δις]{.greek-omitted} [δυς]{.greek-added} απαρνηση με [τρις]{.greek-omitted} [τρεις]{.greek-added} και επιβαλων εκλαιεν[14:72]{.aside}

### Chapter 15

και [ευθεως]{.greek-omitted} [ευθεω]{.greek-added} επι [το]{.corr} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} [απηνεγκαν]{.greek-omitted} [απηνεγγαν]{.greek-added} και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν [αυτου]{.greek-omitted} [αυτω]{.greek-added} οι αρχιερεις πολλα[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν ιδε ποσα [σ[―]{.gap}]{.greek-added} [σου]{.corr} καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο [αιτεισθαι]{.greek-omitted} [αιτησθαι]{.greek-added} καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων [θελετε]{.greek-omitted} [θελεται]{.greek-added} απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [επεγυνοσκε[ν]{.unclear}]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδοκεισαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις [ανεσεισαν]{.greek-omitted} [ανεσισαν]{.greek-added} τον οχλον ινα μαλλον τον βαραββαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις [λεγει]{.greek-added} [αυτοις]{.greek-added} παλιν [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} τι ουν [θελετε]{.greek-omitted} [θελ[ε]{.unclear}ται]{.greek-added} ποιησω ον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν [ε[ξ]{.unclear}]{.greek-added} [εκραξαν]{.corr} [λεγοντες]{.greek-added} σταυρωσον αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσως]{.greek-added} [εκραξαν]{.greek-omitted} [εκραξον]{.greek-added} σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και παρεδωκεν τον [ιησουν]{.greek-abbr} φραγελλωσας ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [πραιτωριον]{.greek-omitted} [πρετωριον]{.greek-added} και συγκαλουσιν [ολην]{.greek-omitted} [ολιν]{.greek-added} την σπειραν[15:16]{.aside}

και ενδυο[υ]{.unclear}σιν αυτον πορφυραν και [περιτιθεασιν]{.greek-omitted} [περιτυθεασιν]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} πλεξαντες [ακανθινον]{.greek-omitted} [ακ[α]{.unclear}νθηνον]{.greek-added} στεφανον[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον [αυτου]{.greek-omitted} την κεφαλην [αυτου]{.greek-added} καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεμπεξαν]{.greek-added} αυτω εξεδυσαν αυτον την [π[ω]{.unclear}ρφυραν]{.greek-added} [πορφυραν]{.corr} και ενεδυσαν [αυτον]{.greek-omitted} [αυτων]{.greek-added} τα ιματια τα ιδια και [εξαγουσιν]{.greek-omitted} [εξαγουσι]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} [ω[ς]{.unclear}]{.greek-added} [ινα]{.corr} σταυρωσωσιν αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} πα[ρ]{.unclear}αγο[ν]{.unclear}τα τινα σιμωνα [κυρηναιον]{.greek-omitted} [κυριναιον]{.greek-added} ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και [ρο]{.unclear}υφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα τοπον [ο]{.greek-omitted} [ος]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και [εδιδουν]{.greek-omitted} [εδιδου]{.greek-added} αυτω πιειν εσμυρνισμενον οινον ο δε ουκ ελαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον [διαμεριζονται]{.greek-omitted} [διε]{.greek-added} [μερι[σ]{.unclear}αντο]{.greek-added} τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι [αρη]{.greek-omitted} [αρει]{.greek-added}[15:24]{.aside}

ην δε [τριτη]{.greek-added} ωρα [τριτη]{.greek-omitted} και εσταυρωσαν αυτον[15:25]{.aside}

και ην η επιγραφη της [αιτιας]{.greek-omitted} [ετιας]{.greek-added} αυτου [επιγεγραμμενη]{.greek-omitted} ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [στραυρουσιν]{.greek-added} δυο [ληστας]{.greek-omitted} [ληστασ[―]{.gap}]{.greek-added} ενα εκ δεξιων [αυτου]{.greek-added} και ενα εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} [αυτου]{.greek-omitted}[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον [κινουντες]{.greek-omitted} [κυνουντες]{.greek-added} τας κεφαλας αυτων και λεγοντες ουα ο [καταλυων]{.greek-omitted} [καταλυον]{.greek-added} τον ναον και εν τρισιν [ημεραις]{.greek-omitted} [ημερες]{.greek-added} [οικοδομων]{.greek-omitted} [οικοδομον]{.greek-added}[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως [δε]{.greek-added} και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζοντες]{.greek-added} προς αλληλους μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο βασιλευς [του]{.greek-omitted} [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι συνεσταυρωμενοι αυτω ωνειδιζον αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος [εγενετο]{.greek-omitted} [εγενετω]{.greek-added} εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και τη ωρα τη ενατη εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι λιμα [σαβαχθανι]{.greek-omitted} [σαβακθανι]{.greek-added} ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου εις τι με [εγκατελιπες]{.greek-omitted} [εγκατελυπες]{.greek-added}[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον [οτι]{.greek-added} ιδου ηλιαν φωνει[15:35]{.aside}

[δραμων]{.greek-omitted} [δραμον]{.greek-added} δε εις [και]{.greek-omitted} [γεμισας]{.greek-omitted} σπογγον οξους περιθεις τε καλαμω [εποτιζεν]{.greek-omitted} [εποτηζεν]{.greek-added} αυτον [λεγων]{.greek-omitted} [λεγον]{.greek-added} [αφετε]{.greek-omitted} [αφεται]{.greek-added} ιδωμεν [ει]{.greek-omitted} [η]{.greek-added} ερχεται ηλ[ι]{.unclear}ας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου [εσχισθη]{.greek-omitted} [εσχησθη]{.greek-added} εις δυο απο [ανωθεν]{.greek-omitted} [ανοθεν]{.greek-added} εως κατω[15:38]{.aside}

ιδων δε ο [κεντυριων]{.greek-omitted} [κεντηριων]{.greek-added} ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας [εξεπευ]{.greek-added} [εξεπνευσεν]{.greek-omitted} [[εξεπνευσιν]{.corr}]{.greek-added} ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και [γυναικες]{.greek-omitted} [γυνεκες]{.greek-added} απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο εστιν [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθον]{.greek-added} ιωσηφ ο απο αριμαθαιας [ευσχημων]{.greek-omitted} [ευχημων]{.greek-added} [βλευτης]{.greek-added} [βουλευτης]{.corr} ος και αυτος ην προσδεχομενος την βασιλειαν του [[θεου]{.greek-abbr}]{.corr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν [ει]{.corr} ηδη τεθνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους απο του [κεντ[η]{.unclear}]{.greek-added} [κεντυριωνος]{.corr} εδωρησατο [το]{.greek-omitted} [σωμα]{.greek-omitted} τω ιωσηφ[15:45]{.aside}

και αγορασας [σινδονα]{.greek-omitted} [σινδωνα]{.greek-added} και καθελων αυτον [εν[η]{.unclear}λησεν]{.greek-added} [ενειλησεν]{.corr} τη [σινδωνα]{.greek-added} [σινδονι]{.greek-omitted} [[σινδωνι]{.corr}]{.greek-added} και κατεθηκεν αυτον [εν]{.greek-omitted} [ε]{.greek-added} μνημειω ο ην λελατομημενον εκ πετρας και προσεκυλισεν λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η μαγδαληνη και μαρια ιωση εθεωρουν που [τιθεται]{.greek-omitted} [τεθηται]{.greek-added}[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια [η]{.greek-added} [του]{.greek-added} ιακωβου και σαλωμη ηγορασαν αρωματα ινα ελθουσαι [αλειψωσιν]{.greek-omitted} [αληψωσιν]{.greek-added} αυτον[16:1]{.aside}

και λιαν πρωι της μιας [των]{.greek-added} σαββατων ερχονται επι το μνημειον [ετι]{.greek-added} ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις [αποκυλισει]{.greek-omitted} [αποκυλησει]{.greek-added} [ημιν]{.greek-omitted} [υμιν]{.greek-added} τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι [θε[ρ]{.unclear}ο]{.greek-added} [θεωρουσιν]{.corr} οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον [ειδον]{.greek-omitted} [ιδον]{.greek-added} νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον [στολην]{.greek-omitted} [στολη]{.greek-added} [λευκην]{.greek-omitted} [λευκη]{.greek-added} και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβεισθαι]{.greek-added} [ιησουν]{.greek-abbr} [ζητ[η]{.unclear}ται]{.greek-added} [ζητειτε]{.greek-omitted} [[ζητειται]{.corr}]{.greek-added} τον [ναζαρηνον]{.greek-omitted} [ναζωρινον]{.greek-added} τον [εσταυρωμενον]{.greek-abbr} ηγερθη [ουκ]{.greek-omitted} [ου]{.greek-added} [εστιν]{.greek-omitted} [στιν]{.greek-added} ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} [ειπατε]{.greek-omitted} [ειπαται]{.greek-added} τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} καθως ειπεν υμιν[16:7]{.aside}

και [ελθουσαι]{.greek-added} [εξελθουσαι]{.corr} εφυγον απο του μνημειου [ειχεν]{.corr} [δε]{.corr} [αυτας]{.corr} [τρομος]{.corr} [και]{.corr} [εκστασις]{.greek-omitted} [[εκστασης]{.corr}]{.greek-added} και ουδενι ουδεν [ειπον]{.greek-omitted} [ειπων]{.greek-added} εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} [εφανη]{.greek-omitted} [εφανει]{.greek-added} πρωτον μαρια τη μαγδαληνη αφ [ης]{.greek-omitted} [εις]{.greek-added} [εκβεβληκη]{.greek-added} [εκβεβληκει]{.corr} επτα δαιμονια[16:9]{.aside}

εκεινη [πορευθεισα]{.greek-omitted} [απελθουσα]{.greek-added} [απηγγειλεν]{.greek-omitted} [απηγγιλεν]{.greek-added} τοις μετ αυτου [γενομενοις]{.greek-omitted} [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και κλαιουσιν[16:10]{.aside}

κακεινοι ακουσαντες οτι [ζη]{.greek-omitted} [ζει]{.greek-added} και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν [ετερα]{.greek-omitted} [εταιρα]{.greek-added} μορφη [πορευομενοις]{.greek-omitted} [πορευομενης]{.greek-added} εις αγρον[16:12]{.aside}

κακεινοι απελθοντες [απηγγειλαν]{.greek-omitted} [απηγγηλαν]{.greek-added} τοις [λοιποις]{.greek-omitted} [ληποις]{.greek-added} ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ονειδισεν]{.greek-added} την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και [σκληροκαρδιαν]{.greek-omitted} [σκληρωκαρδιαν]{.greek-added} οτι τοις θεασαμενοις αυτον [εγηγερμενον]{.greek-omitted} [εγειγερμενον]{.greek-added} [εκ]{.greek-added} [νεκρων]{.greek-added} ουκ επιστευσαν[16:14]{.aside}

[και]{.greek-added} [ειπεν]{.greek-added} [αυτοις]{.greek-added} και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα [κηρυξατε]{.greek-omitted} [κηρυξαται]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} ευαγγελιον παση τη [κτισει]{.greek-omitted} [κτησει]{.greek-added}[16:15]{.aside}

ο πιστευσας και [βαπτισθεις]{.greek-omitted} [βαπτισθης]{.greek-added} σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα [παρακολουθησει]{.greek-omitted} [παρακολουθουσιν]{.greek-added} εν τω ονοματι μου δαιμονια εκβαλουσιν γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις αρουσιν καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας επιθησουσιν και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} [[ιησους]{.greek-abbr}]{.greek-added} μετα το λαλησαι αυτοις ανεληφθη εις [τον]{.greek-omitted} [τους]{.greek-added} [ουρανον]{.greek-omitted} [[ουρανος]{.greek-abbr}]{.greek-added} [[[ουρανους]{.greek-abbr}]{.corr}]{.greek-added} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} [συνεργουντος]{.greek-omitted} [συνεργουν]{.greek-added} [τος]{.greek-added} και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

