---
title: "Collation of Byz^RP^ vs 31542 (1542)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1542 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31542).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1542                                   	| λογος                              	|
| 1542 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1542 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1542               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1542                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1542 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1542                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον κυριου ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} προς αυτον πασα [η]{.greek-omitted} ιουδαια χωρα και οι ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε [ο]{.greek-omitted} [ιωαννης]{.greek-omitted} [ενδεδυμενος]{.greek-omitted} [τριχας]{.greek-omitted} [καμηλου]{.greek-omitted} [και]{.greek-omitted} [ζωνην]{.greek-omitted} [δερματινην]{.greek-omitted} [περι]{.greek-omitted} [την]{.greek-omitted} [οσφυν]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εσθιων]{.greek-omitted} [ακριδας]{.greek-omitted} [και]{.greek-omitted} [μελι]{.greek-omitted} [αγριον]{.greek-omitted}[1:6]{.aside}

[ην]{.greek-omitted} [δε]{.greek-omitted} ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6 | instance no. 2]{.aside}

και εκηρυσσεν λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ιησους]{.greek-abbr} απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} της γαλιλαιας και εβαπτισθη υπο ιωαννου ει[ς]{.unclear} τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος ειδεν σχιζομενους τους [ουρανους]{.greek-omitted} [[ουνους]{.greek-abbr}]{.greek-added} και το [πνευμα]{.greek-abbr} [ωσει]{.greek-omitted} [ως]{.greek-added} περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-omitted} [[ουνων]{.greek-abbr}]{.greek-added} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την [γαλιλαιαν]{.greek-omitted} [κηρυσσων]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [της]{.greek-omitted} [βασιλειας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[1:14]{.aside}

[μετα]{.greek-omitted} [δε]{.greek-omitted} [το]{.greek-omitted} [παραδοθηναι]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [ηλθεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14 | instance no. 2]{.aside}

[και]{.greek-omitted} λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος [βαλλοντας]{.greek-omitted} [αμφιβαλλοντας]{.greek-added} αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα [δικτυα]{.greek-omitted} [δυκτυα]{.greek-added} αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην εδιδασκεν[1:21]{.aside}

και [εξεπλησσοντο]{.greek-omitted} [εξεπληττοντο]{.greek-added} επι τη διδαχη αυτου ην γαρ [διδασκων]{.greek-omitted} [αυτους]{.greek-omitted} [ως]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχων]{.greek-omitted} [και]{.greek-omitted} [ουχ]{.greek-omitted} [ως]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted}[1:22]{.aside}

[και]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22 | instance no. 2]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και ανεκραξεν [[ανεκραξε]{.corr}]{.greek-added}[1:23]{.aside}

λεγων εα τι [ημιν]{.greek-omitted} [υμιν]{.greek-added} και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων [φιμωθητι]{.greek-omitted} [φημωθητι]{.greek-added} και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους λεγοντας τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν δε η ακοη αυτου ευθυς εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην [κρατησας]{.greek-omitted} [της]{.greek-omitted} [χειρος]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [αφηκεν]{.greek-omitted} [αυτην]{.greek-omitted} [ο]{.greek-omitted} [πυρετος]{.greek-omitted} [ευθεως]{.greek-omitted} [και]{.greek-omitted} [διηκονει]{.greek-omitted} [αυτοις]{.greek-omitted}[1:31]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [ηγειρεν]{.greek-omitted} [αυτην]{.greek-omitted} κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31 | instance no. 2]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη [επισυνηγμενη]{.greek-omitted} [επισυνηγμενοι]{.greek-added} ην προς την θυραν[1:33]{.aside}

και εθεραπευσεν πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα εξεβαλεν και ουκ [ηφιεν]{.greek-omitted} [ηφειεν]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον[1:34]{.aside}

και πρωι εννυχον λιαν αναστας εξηλθεν και απηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην κηρυσσων εν ταις συναγωγαις αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων αυτον και λεγων αυτω [οτι]{.greek-omitted} [εαν]{.greek-omitted} [θελης]{.greek-omitted} [δυνασαι]{.greek-omitted} [με]{.greek-omitted} [καθαρισαι]{.greek-omitted}[1:40]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [λεπρος]{.greek-omitted} [παρακαλων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [γονυπετων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγων]{.greek-omitted} [αυτω]{.greek-omitted} οτι εαν θελης δυνασαι με καθαρισαι[1:40 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν [η]{.greek-added} [λεπρα]{.greek-added} απ αυτου [η]{.greek-omitted} [λεπρα]{.greek-omitted} και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν ειπης [αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και εισηλθεν παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον εστιν[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον [φεροντες]{.greek-omitted} [αιρομενον]{.greek-omitted} [υπο]{.greek-omitted} [τεσσαρων]{.greek-omitted}[2:3]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [παραλυτικον]{.greek-omitted} φεροντες αιρομενον υπο τεσσαρων[2:3 | instance no. 2]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε [[ιις]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} την πιστιν αυτων λεγει τω παραλυτικω τεκνον αφεωνται σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι [ουτως]{.greek-omitted} [ουτος]{.greek-added} αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω [παραλυτικω]{.greek-omitted} [παλυτικω]{.greek-added} αφεωνται σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον σου τον κραββατον και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι επι της γης αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον [κραββατον]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [υπαγε]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [σου]{.greek-omitted}[2:11]{.aside}

[σοι]{.greek-omitted} [λεγω]{.greek-omitted} [εγειραι]{.greek-omitted} [και]{.greek-omitted} [αρον]{.greek-omitted} [τον]{.greek-omitted} κραββατον σου και υπαγε εις τον οικον σου[2:11 | instance no. 2]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν [εναντι[ω]{.unclear}ν]{.greek-added} [εναντιον]{.corr} παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι [ουδεποτε]{.greek-omitted} [ουδεπωτε]{.greek-added} ουτως [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added}[2:12]{.aside}

και εξηλθεν παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ειδεν [λευι]{.greek-omitted} [λευιν]{.greek-added} τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας [η]{.unclear}κολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι [συνανεκειντο]{.greek-omitted} [συνανεγκειντο]{.greek-added} τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι [κακως]{.greek-omitted} [εχοντες]{.greek-omitted} [ουκ]{.greek-omitted} [ηλθον]{.greek-omitted} [καλεσαι]{.greek-omitted} [δικαιους]{.greek-omitted} [αλλα]{.greek-omitted} [αμαρτωλους]{.greek-omitted} [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[2:17]{.aside}

[και]{.greek-omitted} [ακουσας]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχουσιν]{.greek-omitted} [οι]{.greek-omitted} [ισχυοντες]{.greek-omitted} [ιατρου]{.greek-omitted} [αλλ]{.greek-omitted} [οι]{.greek-omitted} κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17 | instance no. 2]{.aside}

και ησαν οι μαθηται ιωαννου και οι των φαρισαιων νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων εστιν νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα ρακους αγναφου επιρραπτει επι ιματιω παλαιω ει δε μη αιρει το πληρωμα αυτου το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε μη ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον εις ασκους καινους βλητεον[2:22]{.aside}

και [εγενετο]{.greek-omitted} [εγετο]{.greek-added} [πα]{.greek-added} [παραπορευεσθαι]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [δια]{.greek-omitted} [των]{.greek-omitted} [σποριμων]{.greek-omitted} [και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [οδον]{.greek-omitted} [ποιειν]{.greek-omitted} [τιλλοντες]{.greek-omitted} [τους]{.greek-omitted} [σταχυας]{.greek-omitted}[2:23]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [παραπορευεσθαι]{.greek-omitted} [ραπορευεσθαι]{.greek-added} αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23 | instance no. 2]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι εποιησεν [[εποιησε]{.corr}]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν εσχεν και επεινασεν [και]{.greek-added} αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και εδωκεν και τοις συν αυτω ουσιν[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και εισηλθεν παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [ξηραμμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα [κατηγορησωσιν]{.greek-omitted} [κατηγορισωσιν]{.greek-added} αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω εξηραμμενην εχοντι την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις εξεστιν [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [αγαθοποιησαι]{.greek-omitted} [η]{.greek-omitted} [κακοποιησαι]{.greek-omitted} [ψυχην]{.greek-omitted} [σωσαι]{.greek-omitted} [η]{.greek-omitted} [αποκτειναι]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [εσιωπων]{.greek-omitted}[3:4]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [εξεστιν]{.greek-omitted} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4 | instance no. 2]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα [σου]{.greek-omitted} και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου υγιης ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον απολεσωσιν[3:6]{.aside}

και ο [ιησους]{.greek-abbr} ανεχωρησεν μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [ηκολουθησεν]{.greek-added} αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι [τυρον]{.greek-omitted} [τυρων]{.greek-added} και σιδωνα πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [οσοι]{.greek-omitted} [ειχον]{.greek-omitted} [μαστιγας]{.greek-omitted}[3:10]{.aside}

[πολλους]{.greek-omitted} [γαρ]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [ωστε]{.greek-omitted} [επιπιπτειν]{.greek-omitted} [αυτω]{.greek-omitted} [ινα]{.greek-omitted} [αυτου]{.greek-omitted} αψωνται οσοι ειχον μαστιγας[3:10 | instance no. 2]{.aside}

και τα [πνευματα]{.greek-omitted} [[πνατα]{.greek-abbr}]{.greek-added} [τα]{.greek-omitted} ακαθαρτα οταν αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και εκραζεν λεγοντα οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον ποιησωσιν[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και εποιησεν δωδεκα ινα ωσιν μετ αυτου και ινα αποστελλη αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και επεθηκεν τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον του ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον [τον]{.greek-omitted} του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν οχλος ωστε μη δυνασθαι αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον [οτι]{.greek-omitted} βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημησει]{.greek-added} εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον [αι]{.greek-added} [αιωνα]{.greek-omitted} [αλλ]{.greek-omitted} [ενοχος]{.greek-omitted} [εστιν]{.greek-omitted} [αιωνιου]{.greek-omitted} [κρισεως]{.greek-omitted}[3:29]{.aside}

[ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [βλασφημηση]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αγιον]{.greek-omitted} [ουκ]{.greek-omitted} [εχει]{.greek-omitted} [αφεσιν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [αιωνα]{.greek-omitted} [ωνα]{.greek-added} αλλ ενοχος εστιν αιωνιου κρισεως[3:29 | instance no. 2]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο οχλος περι αυτον ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου και αι αδελφαι σου εξω ζητουσιν σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν [η]{.greek-omitted} [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει ιδε [η]{.unclear} [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και [αδελφο[ς]{.unclear}]{.greek-added} [αδελφη]{.corr} μου και [μητηρ]{.greek-abbr} εστιν[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις το πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν επεσεν παρα την οδον και ηλθεν τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ εδωκεν[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη ιδωσιν και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει [αυ]{.greek-added} [αυτοις]{.greek-omitted} [ουκ]{.greek-omitted} [οιδατε]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [ταυτην]{.greek-omitted} [και]{.greek-omitted} [πως]{.greek-omitted} [πασας]{.greek-omitted} [τας]{.greek-omitted} [παραβολας]{.greek-omitted} [γνωσεσθε]{.greek-omitted}[4:13]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-added} ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13 | instance no. 2]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν ευθεως ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι [εισιν]{.greek-omitted} [οι]{.greek-omitted} εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι [ρι]{.greek-added} [περι]{.corr} τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι ο λυχνος [ερχεται]{.greek-omitted} [ινα]{.greek-omitted} [υπο]{.greek-omitted} [τον]{.greek-omitted} [μοδιον]{.greek-omitted} [τεθη]{.greek-omitted} [η]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [κλινην]{.greek-omitted} [ουχ]{.greek-omitted} [ινα]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [λυχνιαν]{.greek-omitted} [επιτεθη]{.greek-omitted}[4:21]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [μητι]{.greek-omitted} [ο]{.greek-omitted} [λυχνος]{.greek-omitted} ερχεται ινα υπο τον μοδιον τεθη η υπο την κλινην ουχ ινα επι την λυχνιαν επιτεθη[4:21 | instance no. 2]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} τι κρυπτον ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε μετρηθησεται υμιν [και]{.greek-omitted} [προστεθησεται]{.greek-omitted} [υμιν]{.greek-omitted} τοις ακουουσιν[4:24]{.aside}

ος γαρ αν εχη δοθησεται αυτω και ος ουκ [εχει]{.greek-omitted} [εχη]{.greek-added} και ο [εχει]{.greek-omitted} [εχη]{.greek-added} αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} [ως]{.greek-omitted} [ος]{.greek-added} [εαν]{.greek-omitted} [αν]{.greek-added} [ανθρωπος]{.greek-abbr} βαλη τον σπορον επι της γης[4:26]{.aside}

και [καθευδη]{.greek-omitted} [καθευδει]{.greek-added} και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον [οτι]{.greek-omitted} [οτε]{.greek-added} παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

[ως]{.greek-omitted} [ος]{.greek-added} κοκκον σιναπεως ος οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} επι της γης μικροτερος παντων [των]{.greek-omitted} [σπερματων]{.greek-omitted} [εστιν]{.greek-omitted} [των]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[4:31]{.aside}

[ως]{.greek-omitted} [κοκκον]{.greek-omitted} [σιναπεως]{.greek-omitted} [ος]{.greek-omitted} [οταν]{.greek-omitted} [σπαρη]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [μικροτερος]{.greek-omitted} [παντων]{.greek-omitted} των σπερματων εστιν των επι της γης[4:31 | instance no. 2]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων μειζων και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο [την]{.greek-omitted} [της]{.greek-added} [σκιαν]{.greek-omitted} [σκιας]{.greek-added} αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [εδυνατο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ [ελαλη]{.greek-added} [ελαλει]{.corr} αυτοις κατ ιδιαν δε τοις μαθηταις αυτου επελυεν παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε πλοιαρια ην μετ αυτου[4:36]{.aside}

και γινεται λαιλαψ ανεμου μεγαλη τα δε κυματα επεβαλλεν εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι τη πρυμνη επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου μελει σοι οτι [απολλυμεθα]{.greek-omitted} [απολυμεθα]{.greek-added}[4:38]{.aside}

και διεγερθεις επετιμησεν τω ανεμω και ειπεν τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [και]{.greek-omitted} [εκοπασεν]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [γαληνη]{.greek-omitted} [μεγαλη]{.greek-omitted}[4:39]{.aside}

[και]{.greek-omitted} [διεγερθεις]{.greek-omitted} [επετιμησεν]{.greek-omitted} [τω]{.greek-omitted} [ανεμω]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [σιωπα]{.greek-omitted} [πεφιμωσο]{.greek-omitted} [πεφημωσο]{.greek-added} και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39 | instance no. 2]{.aside}

και ειπεν αυτοις τι [δειλοι]{.greek-omitted} [δηλοι]{.greek-added} εστε ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γαδαρινων]{.greek-added}[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις εδυνατο αυτον δησαι[5:3]{.aside}

δια τ[ο]{.unclear} αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και διεσπασθαι [υπ]{.greek-omitted} [απ]{.greek-added} αυτου τας αλυσεις και τας πεδας [συντετριφθαι]{.greek-omitted} [συντριφθαι]{.greek-added} και ουδεις αυτον ισχυεν δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και εν τοις μνημασιν ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

[ιδων]{.greek-omitted} [ιδον]{.greek-added} δε τον [ιησουν]{.greek-abbr} απο μακροθεν εδραμεν και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη ειπεν [τι]{.greek-omitted} [εμοι]{.greek-omitted} [και]{.greek-omitted} [σοι]{.greek-omitted} [ιησου]{.greek-omitted} [υιε]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [υψιστου]{.greek-omitted} [ορκιζω]{.greek-omitted} [σε]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [μη]{.greek-omitted} [με]{.greek-omitted} [βασανισης]{.greek-omitted}[5:7]{.aside}

[και]{.greek-omitted} [κραξας]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [ειπεν]{.greek-omitted} τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7 | instance no. 2]{.aside}

ελεγεν γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι σοι ονομα και απεκριθη λεγων λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη αυτους αποστειλη εξω της χωρας[5:10]{.aside}

ην δε εκει προς τω ορει αγελη χοιρων μεγαλη [βοσκομενη]{.greek-omitted} [βοσκωμενη]{.greek-added}[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και [ευθεως]{.greek-added} επετρεψεν αυτοις [ευθεως]{.greek-omitted} ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-abbr} [τα]{.greek-omitted} ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε [ως]{.greek-omitted} [ωσει]{.greek-added} δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και θεωρουσι[ν]{.unclear} [[θεωρουσι]{.corr}]{.greek-added} τον δαιμονιζομενον [καθημενον]{.greek-omitted} [και]{.greek-omitted} [ιματισμενον]{.greek-omitted} [και]{.greek-omitted} [σωφρονουντα]{.greek-omitted} [τον]{.greek-omitted} [εσχηκοτα]{.greek-omitted} [τον]{.greek-omitted} [λεγεωνα]{.greek-omitted} [και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted}[5:15]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [και]{.greek-omitted} [θεωρουσιν]{.greek-omitted} [τον]{.greek-omitted} [δαιμονιζομενον]{.greek-omitted} καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον [λεωνα]{.greek-added} [λεγεωνα]{.corr} και εφοβηθησαν[5:15 | instance no. 2]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και [ηρξαντο]{.greek-omitted} [ηρξατο]{.greek-added} παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβατος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

ο δε [ιησους]{.greek-abbr} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [εποιησεν]{.greek-added} και ηλεησεν σε[5:19]{.aside}

και απηλθεν και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και [ιδου]{.greek-omitted} [ιδον]{.greek-added} ερχεται εις των αρχισυναγωγων ονοματι [αειρος]{.greek-added} [ιαειρος]{.corr} και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου [εσχατως]{.greek-omitted} [εσχατος]{.greek-added} [εχει]{.greek-omitted} [ινα]{.greek-omitted} [ελθων]{.greek-omitted} [επιθης]{.greek-omitted} [αυτη]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [οπως]{.greek-omitted} [σωθη]{.greek-omitted} [και]{.greek-omitted} [ζησεται]{.greek-omitted}[5:23]{.aside}

[και]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [πολλα]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [μου]{.greek-omitted} [εσχατως]{.greek-omitted} εχει ινα ελθων επιθης αυτη τας χειρας οπως σωθη και ζησεται[5:23 | instance no. 2]{.aside}

και απηλθεν μετ αυτου και [ηκολουθη]{.greek-added} [ηκολουθει]{.corr} αυτω οχλος πολυς και [συνεθλιβον]{.greek-omitted} [συνελθλιβον]{.greek-added} αυτον[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

ελεγεν γαρ οτι καν των ιματιων αυτου [αψωμαι]{.greek-omitted} [αψομαι]{.greek-added} σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και [εγνω]{.greek-omitted} [επεγνω]{.greek-added} τω σωματι οτι ιαται απο της [μαστηγος]{.greek-added} [μαστιγος]{.corr}[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν [εξελθουσαν]{.greek-omitted} [επελθουσαν]{.greek-added} επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

[ει]{.greek-added} [η]{.greek-omitted} [δε]{.greek-omitted} [γυνη]{.greek-omitted} [φοβηθεισα]{.greek-omitted} [και]{.greek-omitted} [τρεμουσα]{.greek-omitted} [ειδυια]{.greek-omitted} [ο]{.greek-omitted} [γεγονεν]{.greek-omitted} [επ]{.greek-omitted} [αυτη]{.greek-omitted} [ηλθεν]{.greek-omitted} [και]{.greek-omitted} [προσεπεσεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [πασαν]{.greek-omitted} [την]{.greek-omitted} [αληθειαν]{.greek-omitted}[5:33]{.aside}

[η]{.greek-omitted} δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη ηλθεν και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33 | instance no. 2]{.aside}

ο δε ειπεν αυτη θυγατερ η [πιστις]{.greek-omitted} [πιστη]{.greek-added} σου σεσωκεν σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος [ερχεται]{.greek-added} [ερχονται]{.corr} απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου απεθανεν τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα [αυτω]{.greek-omitted} [αυτων]{.greek-added} συνακολουθησαι ει μη πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει [θορ[ρ]{.unclear}βον]{.greek-added} [θορυβον]{.corr} κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι [θορυβεισθε]{.greek-omitted} [θορυβεισθαι]{.greek-added} και κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και [τους]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εισπορευεται]{.greek-omitted} [οπου]{.greek-omitted} [ην]{.greek-omitted} [το]{.greek-omitted} [παιδιον]{.greek-omitted} [ανακειμενον]{.greek-omitted}[5:40]{.aside}

[και]{.greek-omitted} [κατεγελων]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [εκβαλων]{.greek-omitted} [παντας]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [του]{.greek-omitted} [παιδιου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [και]{.greek-omitted} τους μετ αυτου και [εισπορευεται]{.greek-omitted} [εισπορευετε]{.greek-added} οπου ην το παιδιον ανακειμενον[5:40 | instance no. 2]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα κουμι ο εστιν μεθερμηνευομενον το κορασιον [σοι]{.greek-omitted} [συ]{.greek-added} λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω [τουτο]{.greek-omitted} [τουτω]{.greek-added} και ειπεν δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την πατριδα αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου [ηρξατο]{.greek-omitted} [ηρξαντο]{.greek-added} εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ταυτα και τις η σοφια η δοθεισα αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ [ουτος]{.greek-omitted} [ουτως]{.greek-added} εστιν ο τεκτων ο [υιος]{.greek-abbr} μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

ελεγεν δε [αυ]{.greek-added} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [προφητης]{.greek-omitted} [ατιμος]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πατριδι]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [συγγενεσιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [αυτου]{.greek-omitted}[6:4]{.aside}

[ελεγεν]{.greek-omitted} [δε]{.greek-omitted} [αυτοις]{.greek-omitted} [τοις]{.greek-added} ο [ιησους]{.greek-abbr} οτι ουκ εστιν προφητης ατιμος ει μη εν τη πατριδι αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσιν]{.greek-added} και εν τη οικια αυτου[6:4 | instance no. 2]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας εθεραπευσεν[6:5]{.aside}

και εθαυμαζεν δια την απιστιαν αυτων και περιηγεν τας κωμας κυκλω διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει [μη]{.corr} ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη ενδυσησθε δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν [εισελθητε]{.greek-omitted} [εισελθετε]{.greek-added} εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι αν μη δεξωνται υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις [α]{.greek-added} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [η]{.greek-omitted} [γομορροις]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [εκεινη]{.greek-omitted}[6:11]{.aside}

[και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [μη]{.greek-omitted} [δεξωνται]{.greek-omitted} [υμας]{.greek-omitted} [μηδε]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [υμων]{.greek-omitted} [εκπορευομενοι]{.greek-omitted} [εκειθεν]{.greek-omitted} [εκτιναξατε]{.greek-omitted} [τον]{.greek-omitted} [χουν]{.greek-omitted} [τον]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [μην]{.greek-added} λεγω υμιν ανεκτοτερον εσται [σοδομοις]{.greek-omitted} [σοδοδομοις]{.greek-added} η [γομορροις]{.greek-omitted} [γομοροις]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[6:11 | instance no. 2]{.aside}

και εξελθοντες εκηρυσσον ινα μετανοησωσιν[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω απεκεφαλισα ιωαννην ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ [ο]{.greek-omitted} ηρωδης αποστειλας εκρατησεν τον ιωαννην και εδησεν αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο ιωαννης τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας [εν]{.greek-added} [ενειχεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [αυτον]{.greek-omitted} [αποκτειναι]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνατο]{.greek-omitted}[6:19]{.aside}

[η]{.greek-omitted} [δε]{.greek-omitted} [ηρωδιας]{.greek-omitted} [ενειχεν]{.greek-omitted} [ειχεν]{.greek-added} αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19 | instance no. 2]{.aside}

ο γαρ ηρωδης εφοβειτο τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα [εποι[η]{.unclear}]{.greek-added} [εποιει]{.corr} και ηδεως αυτου ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και [ορχησαμενης]{.greek-omitted} [ορχισαμενης]{.greek-added} και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν με αιτησης δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα ειπεν τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε ειπεν την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και [εισελθουσα]{.greek-omitted} [εισελθουσης]{.greek-added} ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα [μη]{.greek-added} [μοι]{.corr} [δως]{.greek-omitted} [δος]{.greek-added} εξαυτης επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του [βαπτιστου]{.greek-omitted} [βα]{.greek-added}[6:25]{.aside}

[και]{.greek-omitted} [εισελθουσα]{.greek-omitted} [ευθεως]{.greek-omitted} [μετα]{.greek-omitted} [σπουδης]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [βασιλεα]{.greek-omitted} [ητησατο]{.greek-omitted} [λεγουσα]{.greek-omitted} [θελω]{.greek-omitted} [ινα]{.greek-omitted} [μοι]{.greek-omitted} [δως]{.greek-omitted} [εξαυτης]{.greek-omitted} [επι]{.greek-omitted} [πινακι]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [ιωαννου]{.greek-omitted} [του]{.greek-omitted} [βαπτιστου]{.greek-omitted} [πτιστου]{.greek-added}[6:25 | instance no. 2]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ [ηθελησεν]{.greek-omitted} [ηθελεν]{.greek-added} αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς [σπεκουλατορα]{.greek-omitted} [σπεκουλατωρα]{.greek-added} επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον εδωκεν [αυτην]{.greek-omitted} τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω παντα [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και αναπαυεσθε ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και απηλθον εις ερημον τοπον [εν]{.greek-added} τω πλοιω κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδων]{.greek-added} αυτους υπαγοντας και [επεγνωσαν]{.greek-omitted} [επεγνοσαν]{.greek-added} [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και πεζη απο πασων των πολεων συνεδραμον [εκει]{.greek-omitted} [και]{.greek-omitted} [προηλθον]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [συνηλθον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted}[6:33]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αυτους]{.greek-omitted} [υπαγοντας]{.greek-omitted} [και]{.greek-omitted} [επεγνωσαν]{.greek-omitted} [αυτον]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [πεζη]{.greek-omitted} [απο]{.greek-omitted} [πασων]{.greek-omitted} [των]{.greek-omitted} [πολεων]{.greek-omitted} [συνεδραμον]{.greek-omitted} εκει και προηλθον αυτους και συνηλθον προς αυτον[6:33 | instance no. 2]{.aside}

και εξελθων [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ο [ιησους]{.greek-abbr} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες [αυτω]{.greek-omitted} οι μαθηται αυτου λεγουσιν οτι ερημος εστιν ο τοπος και [ηδη]{.greek-omitted} [η]{.greek-added} ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν [αυτους]{.greek-added} [εαυτοις]{.greek-omitted} [[εαυτους]{.corr}]{.greek-added} αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν δηναριων διακοσιων αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} λεγουσιν πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις [ανακλιναι]{.greek-omitted} [ανακληθηναι]{.greek-added} παντας [συμποσια]{.greek-omitted} συμποσια επι τω [χλωρω]{.greek-omitted} [χλορω]{.greek-added} χορτω[6:39]{.aside}

και [ανεπεσον]{.greek-omitted} [ανεπεσαν]{.greek-added} πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [ευλογησεν]{.greek-omitted} [και]{.greek-omitted} [κατεκλασεν]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [παραθωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [εμερισεν]{.greek-omitted} [πασιν]{.greek-omitted}[6:41]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [αναβλεψας]{.greek-omitted} εις τον [ουρανον]{.greek-abbr} ευλογησεν και κατεκλασεν τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερησεν]{.greek-added} πασιν[6:41 | instance no. 2]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως ηναγκασεν τους μαθητας αυτου [εμβηναι]{.greek-omitted} [εμβην]{.greek-added} εις το πλοιον και προαγειν εις το περαν προς βηθσαιδαν εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην [το]{.corr} πλοιον [εν]{.greek-omitted} [μεσω]{.greek-omitted} [εμμεσω]{.greek-added} της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω [ελαυν[η]{.unclear}ν]{.greek-added} [ελαυνειν]{.corr} ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν [φαντασμα]{.greek-omitted} [ειναι]{.greek-omitted} [και]{.greek-omitted} [ανεκραξαν]{.greek-omitted}[6:49]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ιδοντες]{.greek-omitted} [αυτον]{.greek-omitted} [περιπατουντα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [εδοξαν]{.greek-omitted} φαντασμα ειναι και ανεκραξαν[6:49 | instance no. 2]{.aside}

παντες γαρ αυτον [ειδον]{.greek-omitted} [ιδον]{.greek-added} και εταραχθησαν και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις θαρσειτε [εγω]{.greek-omitted} [ειμι]{.greek-omitted} μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ αυτων η καρδια πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεννησαρετ]{.greek-omitted} [γεννησαρεθ]{.greek-added} και προσωρμισθησαν[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει εστιν[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς [αυ]{.greek-added} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [και]{.greek-omitted} [τινες]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [ελθοντες]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted}[7:1]{.aside}

[και]{.greek-omitted} [συναγονται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [τον]{.greek-added} οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1 | instance no. 2]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις χερσιν τουτ εστιν [ανιπτοις]{.greek-omitted} [ανιπτους]{.greek-added} εσθιοντας αρτους [εμεμψαντο]{.greek-omitted}[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι [ουδαιοι]{.greek-added} [ιουδαιοι]{.corr} εαν μη πυγμη [νιψωνται]{.greek-omitted} [νιψονται]{.greek-added} τας χειρας ουκ εσθιουσιν κρατουντες την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και απο αγορας εαν μη βαπτισωνται ουκ εσθιουσιν και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου περιπατουσιν κατα την παραδοσιν των πρεσβυτερων αλλα ανιπτοις χερσιν εσθιουσιν τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις χειλεσιν με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην [δε]{.greek-omitted} [σεβονται]{.greek-omitted} [με]{.greek-omitted} [διδασκοντες]{.greek-omitted} [διδασκαλιας]{.greek-omitted} [ενταλματα]{.greek-omitted} [ανθρωπων]{.greek-omitted}[7:7]{.aside}

[ματην]{.greek-omitted} δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7 | instance no. 2]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} [αυτου]{.greek-added} κορβαν ο εστιν δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωσει]{.greek-added} υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} [εισπορευομενον]{.greek-omitted} [εισπορευο]{.greek-added} [εις]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [δυναται]{.greek-omitted} [αυτον]{.greek-omitted} [κοινωσαι]{.greek-omitted} [αλλα]{.greek-omitted} [τα]{.greek-omitted} [εκπορευομενα]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [εκεινα]{.greek-omitted} [εστιν]{.greek-omitted} [τα]{.greek-omitted} [κοινουντα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted}[7:15]{.aside}

[μενον]{.greek-added} [ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [εξωθεν]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εισπορευομενον]{.greek-omitted} εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα εστιν τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15 | instance no. 2]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις οικον [απο]{.greek-omitted} [υπο]{.greek-added} του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

ελεγεν δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι [πορνειαι]{.greek-omitted} φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος [ασελγεια]{.greek-omitted} [ασελγειαι]{.greek-added} οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

παντα ταυτα [τα]{.greek-omitted} πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα ηθελεν γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ γυνη περι αυτου ης ειχεν το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα προσεπεσεν προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συροφοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των [ψυχιων]{.greek-added} [ψιχιων]{.corr} των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης ευρεν το δαιμονιον [εξεληλυθος]{.greek-omitted} [εξεληλυθως]{.greek-added} και την θυγατερα [βεβλημενην]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [αυτης]{.greek-added} [κλινης]{.greek-omitted} [βεβλη]{.greek-added}[7:30]{.aside}

[μενην]{.greek-added} [και]{.greek-omitted} [απελθουσα]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [αυτης]{.greek-omitted} [ευρεν]{.greek-omitted} [το]{.greek-omitted} [δαιμονιον]{.greek-omitted} [εξεληλυθος]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [θυγατερα]{.greek-omitted} [βεβλημενην]{.greek-omitted} επι της κλινης[7:30 | instance no. 2]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος ηλθεν προς την θαλασσαν της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν εβαλεν τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} εστεναξεν και λεγει αυτω εφφαθα ο εστιν διανοιχθητι[7:34]{.aside}

και ευθεως [διηνοιχθησαν]{.greek-omitted} [διηνυχθησαν]{.greek-added} αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα [μηδενι]{.greek-omitted} [μηδεν]{.greek-added} ειπωσιν οσον δε αυτος αυτοις [διεστελλετο]{.greek-omitted} [διεστειλατο]{.greek-added} μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα πεποιηκεν και τους κωφους [ποιει]{.greek-omitted} [ποιειν]{.greek-added} ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις παμπολλου οχλου [οντος]{.greek-omitted} [οντως]{.greek-added} και μη εχοντων τι φαγωσιν [προσ]{.greek-added} [προσκαλεσαμενος]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted}[8:1]{.aside}

[εν]{.greek-omitted} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [παμπολλου]{.greek-omitted} [οχλου]{.greek-omitted} [οντος]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [εχοντων]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [καλεσαμενος]{.greek-added} ο [ιησους]{.greek-abbr} [τους]{.greek-omitted} [τοις]{.greek-added} [μαθητας]{.greek-omitted} [μαθηταις]{.greek-added} αυτου λεγει αυτοις[8:1 | instance no. 2]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις προσμενουσιν μοι και ουκ εχουσιν τι φαγωσιν[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν ηκουσιν[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε χορτασαι αρτων επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και παρηγγειλεν τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους [και]{.greek-added} ευχαριστησας εκλασεν και εδιδου τοις μαθηταις αυτου ινα παραθωσιν και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και ευλογησας ειπεν [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} [και]{.greek-omitted} αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες [ως]{.greek-omitted} [ωσει]{.greek-added} τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και ευθεως εμβας εις το [πλοιον]{.greek-omitted} [πλοι]{.greek-added} [μετα]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [μερη]{.greek-omitted} [δαλμανουθα]{.greek-omitted}[8:10]{.aside}

[ον]{.greek-added} [και]{.greek-omitted} [ευθεως]{.greek-omitted} [εμβας]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} μετα των μαθητων αυτου ηλθεν εις τα μερη δαλμανουθα[8:10 | instance no. 2]{.aside}

και εξηλθον οι φαρισαιοι και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [και]{.greek-omitted} [της]{.greek-omitted} [ζυμης]{.greek-omitted} ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα [εις]{.greek-omitted} [τους]{.greek-omitted} [πεντακισχιλιους]{.greek-omitted} [ποσους]{.greek-omitted} [κοφινους]{.greek-omitted} [πληρεις]{.greek-omitted} [κλασματων]{.greek-omitted} [ηρατε]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δωδεκα]{.greek-omitted}[8:19]{.aside}

[οτε]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [εκλασα]{.greek-omitted} εις τους πεντακισχιλιους ποσους κοφινους [πληρεις]{.greek-omitted} [πληρης]{.greek-added} κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19 | instance no. 2]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως ου συνιετε[8:21]{.aside}

και ερχεται εις βηθσαιδαν και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας αυτω επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας ελεγεν βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν επεθηκεν τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψεν]{.greek-added} [τηλαυγως]{.greek-omitted} [τηλαυγ[ο]{.unclear}ς]{.greek-added} απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου [εις]{.greek-omitted} [τας]{.greek-omitted} [κωμας]{.greek-omitted} [καισαρειας]{.greek-omitted} [της]{.greek-omitted} [φιλιππου]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [επηρωτα]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγων]{.greek-omitted} [αυτοις]{.greek-omitted} [τινα]{.greek-omitted} [με]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} [ειναι]{.greek-omitted}[8:27]{.aside}

[και]{.greek-omitted} [εξηλθεν]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} εις τας κωμας [καισαρειας]{.greek-omitted} της φιλιππου και εν τη οδω [επηρωτα]{.greek-omitted} [επ[ε]{.unclear}ρωτα]{.greek-added} τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27 | instance no. 2]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι λεγωσιν περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτου[ς]{.unclear} οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι απο των πρεσβυτερων και των αρχιερεων και των [γραμματαιων]{.greek-added} [γραμματεων]{.corr} και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον [ελαλη]{.greek-added} [ελαλει]{.corr} και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου επετιμησεν τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [οστις]{.greek-omitted} [θελει]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [ακολουθειν]{.greek-omitted} [απαρνησασθω]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [αρατω]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ακολουθειτω]{.greek-omitted} [μοι]{.greek-omitted}[8:34]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} [οχλον]{.greek-omitted} [συν]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} οστις θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34 | instance no. 2]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι [απολεσει]{.greek-omitted} [απολεση]{.greek-added} αυτην ος δ αν απολεση [την]{.greek-omitted} [αυτην]{.greek-added} [εαυτου]{.greek-omitted} [ψυχην]{.greek-omitted} ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [ανθρωπον]{.greek-abbr} εαν κερδηση τον κοσμον ολον και ζημιωθη την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι εισιν τινες των ωδε [[η]{.unclear}στωτων]{.greek-added} [εστηκοτων]{.greek-omitted} [[εστωτων]{.corr}]{.greek-added} οιτινες ου μη γευσωνται θανατου εως αν ιδωσιν την βασιλειαν του [θεου]{.greek-abbr} [εληλυθυιαν]{.greek-omitted} [εληθυθυιαν]{.greek-added} εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη [εμπροσθεν]{.greek-omitted} [εμπροσ]{.greek-added} [αυτων]{.greek-omitted}[9:2]{.aside}

[θεν]{.greek-added} [και]{.greek-omitted} [μεθ]{.greek-omitted} [ημερας]{.greek-omitted} [εξ]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τον]{.greek-omitted} [πετρον]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [ιακωβον]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [και]{.greek-omitted} [αναφερει]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [ορος]{.greek-omitted} [υψηλον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [μονους]{.greek-omitted} [και]{.greek-omitted} [μετεμορφωθη]{.greek-omitted} [εμπροσθεν]{.greek-omitted} αυτων[9:2 | instance no. 2]{.aside}

και τα ιματια [αυτου]{.greek-omitted} εγενοντο στιλβοντα λευκα λιαν ως χιων οια γναφευς επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν μωση και ησαν [συλλαλουντες]{.greek-omitted} [συνλαλουντες]{.greek-added} τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυση]{.greek-added} μιαν και [ηλια]{.greek-omitted} [ηλιαν]{.greek-added} μιαν[9:5]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ εκφοβοι[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα αυτοις και ηλθεν φωνη εκ της νεφελης [λεγουσα]{.greek-added} ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε [αυτων]{.greek-omitted} απο του ορους διεστειλατο αυτοις ινα μηδενι διηγησωνται α ειδον ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι εστιν το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες [οτι]{.greek-omitted} [τι]{.greek-added} λεγουσιν οι [γραμματεις]{.greek-omitted} [γραμμα]{.greek-added} [οτι]{.greek-omitted} [ηλιαν]{.greek-omitted} [δει]{.greek-omitted} [ελθειν]{.greek-omitted} [πρωτον]{.greek-omitted}[9:11]{.aside}

[τεις]{.greek-added} [και]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [λεγοντες]{.greek-omitted} [οτι]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} οτι ηλιαν δει ελθειν πρωτον[9:11 | instance no. 2]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον [αποκαθηστα]{.greek-added} [αποκαθιστα]{.corr} παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας εληλυθεν και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και επηρωτησεν τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και [αποθεις]{.greek-added} [αποκριθεις]{.corr} εις εκ του οχλου ειπεν διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις αυτω λεγει ω γενεα απιστος [εως]{.greek-omitted} [ποτε]{.greek-omitted} [προς]{.greek-omitted} [υμας]{.greek-omitted} [εσομαι]{.greek-omitted} [εως]{.greek-omitted} [ποτε]{.greek-omitted} [ανεξομαι]{.greek-omitted} [υμων]{.greek-omitted} [φερετε]{.greek-omitted} [αυτον]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted}[9:19]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} [ω]{.greek-omitted} [γενεα]{.greek-omitted} [απιστος]{.greek-omitted} εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19 | instance no. 2]{.aside}

και ηνεγκαν αυτον προς αυτον και [ιδων]{.greek-omitted} [ιδοντα]{.greek-added} αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων [επι]{.greek-omitted} [επη]{.greek-added} της γης εκυλιετο αφριζων[9:20]{.aside}

και επηρωτησεν τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε ειπεν παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ εβαλεν και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα [κρυων]{.greek-added} [δακρυων]{.corr} ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει οχλος επετιμησεν τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον εξηλθεν και εγενετο ωσει νεκρος ωστε πολλους [λε]{.greek-added} [λεγειν]{.greek-omitted} [οτι]{.greek-omitted} [απεθανεν]{.greek-omitted}[9:26]{.aside}

[και]{.greek-omitted} [κραξαν]{.greek-omitted} [και]{.greek-omitted} [πολλα]{.greek-omitted} [σπαραξαν]{.greek-omitted} [αυτον]{.greek-omitted} [εξηλθεν]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [ωσει]{.greek-omitted} [νεκρος]{.greek-omitted} [ωστε]{.greek-omitted} [πολλους]{.greek-omitted} [λεγειν]{.greek-omitted} [γειν]{.greek-added} οτι απεθανεν[9:26 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου [επηρωτων]{.greek-omitted} [επηρωτουν]{.greek-added} αυτον κατ ιδιαν οτι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

[μεν]{.greek-added} [και]{.greek-omitted} [εισελθοντα]{.greek-omitted} [αυτον]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [οτι]{.greek-omitted} [ημεις]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθημεν]{.greek-omitted} εκβαλειν αυτο[9:28 | instance no. 2]{.aside}

[σου]{.greek-added} [εκβαλλοντα]{.greek-added} [δαιμονια]{.greek-added} [οστις]{.greek-added} [ουκ]{.greek-added} [ακολουθει]{.greek-added} [ημιν]{.greek-added} και [εισελθοντα]{.greek-omitted} [εκωλυσαμεν]{.greek-added} αυτον [εις]{.greek-omitted} [οικον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [οτι]{.greek-omitted} [ημεις]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθημεν]{.greek-omitted} [εκβαλειν]{.greek-omitted} [αυτο]{.greek-omitted}[9:28 | instance no. 3]{.aside}

και ειπεν αυτοις τουτο το γενος [εν]{.greek-omitted} ουδενι [δυναται]{.greek-omitted} [δυνατε]{.greek-added} εξελθειν ει μη εν προσευχη και νηστεια[9:29]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι [εξερχεται]{.greek-added} [δυναται]{.greek-omitted} [εξελθειν]{.greek-omitted} ει μη εν προσευχη και νηστεια[9:29 | instance no. 2]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[και]{.greek-omitted} [εκειθεν]{.greek-omitted} [κακειθεν]{.greek-added} εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30 | instance no. 2]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου [λεγων]{.greek-added} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδοθησεται]{.greek-added} εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη [εγειρεται]{.greek-added} ημερα [αναστησεται]{.greek-omitted}[9:31 | instance no. 2]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32 | instance no. 2]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω [διελλεχθητε]{.greek-added} προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [διελογιζεσθε]{.greek-omitted}[9:33 | instance no. 2]{.aside}

οι δε [εσιωπων]{.greek-omitted} [εσιωπουν]{.greek-added} προς αλληλους γαρ διελεχθησαν εν τη οδω τις μειζων[9:34]{.aside}

οι δε εσιωπων προς αλληλους γαρ [διελεχθησαν]{.greek-omitted} [διελλεγχθησαν]{.greek-added} εν τη οδω τις μειζων[9:34 | instance no. 2]{.aside}

και καθισας εφωνησεν τους δωδεκα και [λε]{.greek-added} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [θελει]{.greek-omitted} [πρωτος]{.greek-omitted} [ειναι]{.greek-omitted} [εσται]{.greek-omitted} [παντων]{.greek-omitted} [εσχατος]{.greek-omitted} [και]{.greek-omitted} [παντων]{.greek-omitted} [διακονος]{.greek-omitted}[9:35]{.aside}

[και]{.greek-omitted} [καθισας]{.greek-omitted} [εφωνησεν]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [γει]{.greek-added} αυτοις ει τις θελει πρωτος ειναι εσται παντων εσχατος και παντων διακονος[9:35 | instance no. 2]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35 | instance no. 3]{.aside}

και λαβων παιδιον εστησεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [εμμεσω]{.greek-added} αυτων και εναγκαλισαμενος [αυτο]{.greek-omitted} [αυτω]{.greek-added} ειπεν αυτοις[9:36]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36 | instance no. 2]{.aside}

ος εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

ος [εαν]{.greek-omitted} [αν]{.greek-added} εν [εκ]{.greek-added} των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37 | instance no. 2]{.aside}

απεκριθη δε αυτω ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} τινα [εν]{.greek-added} τω ονοματι σου [εκβαλλοντα]{.greek-omitted} [εκβαλοντα]{.greek-added} δαιμονια ος ουκ ακολουθει ημιν [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

απεκριθη δε αυτω [ιωαννης]{.greek-omitted} [λεγων]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [και]{.greek-added} [λεγει]{.greek-added} διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} τινα [εν]{.greek-added} τω [ονοματι]{.greek-omitted} [ονομα]{.greek-added} [σου]{.greek-omitted} [εκβαλλοντα]{.greek-omitted} [δαιμονια]{.greek-omitted} [ος]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted} [και]{.greek-omitted} [εκωλυσαμεν]{.greek-omitted} [αυτον]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν [ος]{.greek-omitted} [ο]{.greek-added} ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ο δε [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη [κωλυετε]{.greek-omitted} [κωλυητε]{.greek-added} [αυτον]{.greek-omitted} [αυτους]{.greek-added} ουδεις γαρ εστιν ος ποιησει δυναμιν [επι]{.greek-omitted} [εν]{.greek-added} τω [ωνοματι]{.greek-added} [ονοματι]{.corr} μου και δυνησεται [ταχυ]{.greek-omitted} [με]{.greek-added} κακολογησαι [με]{.greek-omitted}[9:39 | instance no. 2]{.aside}

ος γαρ ουκ εστιν καθ υμων υπερ υμων εστιν[9:40]{.aside}

ος γαρ ουκ [εστι]{.greek-added} [καθ]{.greek-added} [ημων]{.greek-added} [υπερ]{.greek-added} [ημων]{.greek-added} εστιν [καθ]{.greek-omitted} [υμων]{.greek-omitted} [υπερ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted}[9:40 | instance no. 2]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41 | instance no. 2]{.aside}

και ος εαν σκανδαλιση ενα των μικρων των πιστευοντων εις εμε καλον εστιν αυτω μαλλον [ει]{.greek-omitted} [περικειται]{.greek-omitted} [λιθος]{.greek-omitted} [μυλικος]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [τραχηλον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [βεβληται]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted}[9:42]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} σκανδαλιση ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις εμε καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} [μαλλον]{.greek-added} αυτω [μαλλον]{.greek-omitted} ει περικειται [μυ[―]{.gap}]{.greek-added} [[μυλικος]{.corr}]{.greek-added} [λιθος]{.corr} [μυλικος]{.greek-omitted} περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42 | instance no. 2]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [σοι]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου [σβεννυται]{.greek-omitted} [σβεν]{.greek-added}[9:46]{.aside}

[νυται]{.greek-added} [οπου]{.greek-omitted} [ο]{.greek-omitted} [σκωληξ]{.greek-omitted} [αυτων]{.greek-omitted} [ου]{.greek-omitted} [τελευτα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [ου]{.greek-omitted} [σβεννυται]{.greek-omitted}[9:46 | instance no. 2]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε [εκβαλε]{.greek-omitted} [εκβαλον]{.greek-added} αυτον καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} μονοφθαλμον [εισελθειν]{.greek-omitted} εις την βασιλειαν του [θεου]{.greek-abbr} [εισελθειν]{.greek-added} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

[και]{.greek-added} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} αναστας ερχεται εις τα [ορια]{.greek-omitted} [ορη]{.greek-added} της ιουδαιας [δια]{.greek-omitted} [του]{.greek-omitted} περαν του ιορδανου και [συμπορευονται]{.greek-omitted} [συμπορευεται]{.greek-added} παλιν [οχλοι]{.greek-omitted} [οχλος]{.greek-added} προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

[και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} [φαρισσαιοι]{.greek-added} προσελθοντες [φαρισαιοι]{.greek-omitted} επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν [μωυσης]{.greek-added} την εντολην ταυτην[10:5]{.aside}

απο δε αρχης [κτισεως]{.greek-omitted} [αρσεν]{.greek-omitted} [και]{.greek-omitted} [θηλυ]{.greek-omitted} [εποιησεν]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted}[10:6]{.aside}

[απο]{.greek-omitted} [δε]{.greek-omitted} [αρχης]{.greek-omitted} κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6 | instance no. 2]{.aside}

[και]{.greek-added} [ειπεν]{.greek-added} ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} επηρωτησαν αυτον [περι]{.greek-added} [τουτου]{.greek-added}[10:10]{.aside}

και λεγει αυτοις [ος]{.greek-omitted} εαν απολυση [την]{.greek-omitted} [γυναικα]{.greek-omitted} [αυτου]{.greek-omitted} [γυνη]{.greek-added} [τον]{.greek-added} [ανδρα]{.greek-added} [αυτης]{.greek-added} και γαμηση [αλλην]{.greek-omitted} [αλλον]{.greek-added} μοιχαται [επ]{.greek-omitted} [αυτην]{.greek-omitted}[10:11]{.aside}

και εαν [γυνη]{.greek-omitted} [ανηρ]{.greek-added} απολυση [τον]{.greek-omitted} [ανδρα]{.greek-omitted} [αυτης]{.greek-omitted} [την]{.greek-added} [γυναικα]{.greek-added} [εαυτου]{.greek-added} και [γαμηθη]{.greek-omitted} [γαμηση]{.greek-added} [αλλω]{.greek-omitted} [αλλην]{.greek-added} μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο ιησους [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και [επιτιμησας]{.greek-added} ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη [κωλυετε]{.greek-omitted} [κωλυσητε]{.greek-added} αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος [εαν]{.greek-omitted} [αν]{.greek-added} μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηυλογει]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [προσδραμων]{.greek-omitted} [εις]{.greek-omitted} [και]{.greek-omitted} [γονυπετησας]{.greek-omitted} [αυτον]{.greek-omitted} [επηρωτα]{.greek-omitted} [αυτον]{.greek-omitted} [διδασκαλε]{.greek-omitted} [αγαθε]{.greek-omitted} [τι]{.greek-omitted} [ποιησω]{.greek-omitted} [ινα]{.greek-omitted} [ζωην]{.greek-omitted} [αιωνιον]{.greek-omitted} [κληρονομησω]{.greek-omitted}[10:17]{.aside}

[τις]{.greek-added} [πλουσιος]{.greek-added} [και]{.greek-omitted} [εκπορευομενου]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [οδον]{.greek-omitted} προσδραμων [εις]{.greek-omitted} και γονυπετησας [αυτον]{.greek-omitted} επηρωτα αυτον [λεγων]{.greek-added} διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα [εφυλαξαμην]{.greek-omitted} [εποιησα]{.greek-added} εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας [αυτω]{.greek-omitted} ηγαπησεν αυτον και ειπεν αυτω [εν]{.greek-omitted} [σοι]{.greek-omitted} [υστερει]{.greek-omitted} υπαγε οσα εχεις πωλησον και δος [τοις]{.greek-added} πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [αρας]{.greek-added} [τον]{.greek-added} [[σταυρον]{.greek-abbr}]{.greek-added} δευρο ακολουθει μοι [αρας]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted}[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι [τοις]{.greek-added} χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} [τουτο]{.greek-added} αδυνατον αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο [λεγειν]{.greek-added} [αυτω]{.greek-added} ο πετρος [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο [και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} ακολουθουντες εφοβουντο και παραλαβων παλιν [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτοις]{.greek-omitted} [λεγειν]{.greek-omitted} [τα]{.greek-omitted} [μελλοντα]{.greek-omitted} [αυτω]{.greek-omitted} [συμβαινειν]{.greek-omitted}[10:32]{.aside}

[ησαν]{.greek-omitted} [δε]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} [αναβαινοντες]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [προαγων]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εθαμβουντο]{.greek-omitted} [και]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} [παραλαβων]{.greek-omitted} [παλιν]{.greek-omitted} τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32 | instance no. 2]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [τοις]{.greek-added} [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και εμπαιξουσιν [αυτον]{.greek-added} [και]{.greek-added} [εμπτυσουσιν]{.greek-added} αυτω και μαστιγωσουσιν αυτον και [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αποκτενουσι]{.greek-added} [αυτον]{.greek-omitted} και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και [[ιω]{.greek-abbr}]{.greek-added} [ιωαννης]{.greek-omitted} [οι]{.greek-omitted} υιοι [ζεβεδαιου]{.greek-omitted} [ζεβεδδαιου]{.greek-added} λεγοντες διδασκαλε θελομεν ινα ο εαν αιτησωμεν ποιησης [ημιν]{.greek-omitted}[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε [με]{.greek-added} ποιησαι [με]{.greek-omitted} υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω [και]{.greek-omitted} [η]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων [μου]{.greek-added} ουκ εστιν εμον δουναι αλλ οις [ητοιμασται]{.greek-omitted} [η]{.greek-added}[10:40]{.aside}

[το]{.greek-omitted} [δε]{.greek-omitted} [καθισαι]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ευωνυμων]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [εμον]{.greek-omitted} [δουναι]{.greek-omitted} [αλλ]{.greek-omitted} [οις]{.greek-omitted} [ητοιμασται]{.greek-omitted} [τοιμασται]{.greek-added}[10:40 | instance no. 2]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος [αυτους]{.greek-omitted} λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι [αυτων]{.greek-omitted} κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως [δε]{.greek-omitted} εσται εν υμιν αλλ ος εαν θελη [γενεσθαι]{.greek-omitted} μεγας εν υμιν [εσται]{.greek-omitted} [γενεσθαι]{.greek-added} [εστω]{.greek-added} υμων διακονος[10:43]{.aside}

και ος εαν θελη υμων [γενεσθαι]{.greek-omitted} [ειναι]{.greek-added} πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [ο]{.greek-added} υιος τιμαιου βαρτιμαιος [ο]{.greek-omitted} τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος [εστιν]{.greek-omitted} [[φ]{.unclear}ησιν]{.greek-added} [[ησιν]{.corr}]{.greek-added} ηρξατο κραζειν [λεγων]{.greek-added} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-omitted} ελεησον με[10:47]{.aside}

και [στας]{.greek-omitted} [σταθεις]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει εγειραι φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι [ο]{.greek-omitted} [δε]{.greek-omitted} [τυφλος]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ραββουνι]{.greek-omitted} [ινα]{.greek-omitted} [αναβλεψω]{.greek-omitted}[10:51]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τι]{.greek-omitted} [θελεις]{.greek-omitted} [ποιησω]{.greek-omitted} [σοι]{.greek-omitted} ο δε τυφλος ειπεν αυτω [ραββουνι]{.greek-omitted} [ραβουνει]{.greek-added} ινα αναβλεψω[10:51 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} εις βηθσφαγη και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

[λεγων]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθικε]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι [ποιειτε]{.greek-omitted} [τουτο]{.greek-omitted} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον [δε]{.greek-omitted} [ουν]{.greek-added} και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

[και]{.greek-omitted} τινες [δε]{.greek-added} των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως [ενετειλατο]{.greek-omitted} [ειπεν]{.greek-added} [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και [ηγαγον]{.greek-omitted} [αγουσι]{.greek-added} τον πωλον προς τον [ιησουν]{.greek-abbr} και [επεβαλον]{.greek-omitted} [επιβαλλουσιν]{.greek-added} αυτω τα ιματια αυτων και εκαθισεν επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων [εστρωσαν]{.greek-omitted} [εστρωννυον]{.greek-added} εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ [των]{.greek-omitted} [δενδρων]{.greek-omitted} [και]{.greek-omitted} [εστρωννυον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted}[11:8]{.aside}

[πολλοι]{.greek-omitted} [δε]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [αυτων]{.greek-omitted} [εστρωσαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [εκοπτον]{.greek-omitted} [εκ]{.greek-omitted} των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8 | instance no. 2]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων [αυτων]{.greek-omitted} απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην [απο]{.greek-added} μακροθεν εχουσαν φυλλα ηλθεν ει αρα [τι]{.greek-added} ευρησει [τι]{.greek-omitted} εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη [φυλλα]{.greek-omitted} [φυλα]{.greek-added} [μονον]{.greek-added} ου γαρ ην [ο]{.greek-added} καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι [εκ]{.greek-omitted} [σου]{.greek-omitted} εις τον αιωνα [εκ]{.greek-added} [σου]{.greek-added} μηδεις καρπον [φαγοι]{.greek-omitted} [φαγη]{.greek-added} και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων [κατεστρεψε]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων [αυτοις]{.greek-omitted} [ου]{.greek-omitted} γεγραπται [οτι]{.greek-omitted} [ο]{.greek-omitted} [οικος]{.greek-omitted} [μου]{.greek-omitted} [οικος]{.greek-omitted} [προσευχης]{.greek-omitted} [κληθησεται]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted} [υμεις]{.greek-omitted} [δε]{.greek-omitted} [εποιησατε]{.greek-omitted} [αυτον]{.greek-omitted} [σπηλαιον]{.greek-omitted} [ληστων]{.greek-omitted}[11:17]{.aside}

[και]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [λεγων]{.greek-omitted} [αυτοις]{.greek-omitted} [ου]{.greek-omitted} [γεγραπται]{.greek-omitted} [οτι]{.greek-omitted} ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17 | instance no. 2]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο [οχλος]{.greek-omitted} [λαος]{.greek-added} [εξεπλησσετο]{.greek-omitted} [εξεπλησσοντο]{.greek-added} επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε εγενετο [εξεπορευετο]{.greek-omitted} εξω της πολεως [εξεπορευοντο]{.greek-added}[11:19]{.aside}

και [παραπορευομενοι]{.greek-added} πρωι [παραπορευομενοι]{.greek-omitted} ειδον την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω [ραββι]{.greek-omitted} [ραββει]{.greek-added} ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις [εχετε]{.greek-omitted} [ειχετε]{.greek-added} πιστιν [[κυριου]{.greek-abbr}]{.greek-added} [[θεου]{.greek-abbr}]{.corr}[11:22]{.aside}

αμην [γαρ]{.greek-omitted} λεγω υμιν οτι ος αν ειπη τω ορει τουτω [αρθητι]{.greek-omitted} [αρθηναι]{.greek-added} και [βληθητι]{.greek-omitted} [βληθηναι]{.greek-added} εις την θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι α λεγει γινεται εσται αυτω [ο]{.greek-omitted} [εαν]{.greek-omitted} [ειπη]{.greek-omitted}[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι αιτησθε πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκετε]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και [λεγουσιν]{.greek-omitted} [ελεγον]{.greek-added} αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι [δεδωκε]{.greek-added} την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} [ινα]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιης]{.greek-omitted}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} [ενα]{.greek-omitted} λογον [και]{.greek-omitted} αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει [ημιν]{.greek-added} δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} [εφοβουντο]{.greek-omitted} [φοβουμεθα]{.greek-added} τον λαον [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ [ειχον]{.greek-omitted} [ηδεισαν]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι [οντως]{.greek-omitted} προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} τω [ιησου]{.greek-abbr} [λεγουσιν]{.greek-added} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις [λεγειν]{.greek-omitted} [λαλειν]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εφυτευσεν]{.greek-added} αμπελωνα [εφυτευσεν]{.greek-omitted} [ανθρωπος]{.greek-omitted} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους τω καιρω δουλον [ινα]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} [γεωργων]{.greek-omitted} [λαβη]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [καρπου]{.greek-omitted} [του]{.greek-omitted} [αμπελωνος]{.greek-omitted}[12:2]{.aside}

[και]{.greek-omitted} [απεστειλεν]{.greek-omitted} [προς]{.greek-omitted} [τους]{.greek-omitted} [γεωργους]{.greek-omitted} [τω]{.greek-omitted} [καιρω]{.greek-omitted} [δουλον]{.greek-omitted} ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2 | instance no. 2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον λιθοβολησαντες εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες [τους]{.greek-omitted} [ους]{.greek-added} δε αποκτενοντες[12:5]{.aside}

[υστερον]{.greek-added} [δε]{.greek-added} ετι [ουν]{.greek-omitted} ενα [υιον]{.greek-abbr} εχων [τον]{.greek-added} αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} [και]{.greek-omitted} [προς]{.greek-added} αυτον [προς]{.greek-omitted} [αυτους]{.greek-omitted} εσχατον λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [θεασαμενοι]{.greek-added} [αυτον]{.greek-added} [ερχομενον]{.greek-added} [προς]{.greek-added} [αυτους]{.greek-added} ειπον [προς]{.greek-omitted} [εαυτους]{.greek-omitted} [οτι]{.greek-omitted} ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος [εγενηθη]{.greek-omitted} [εγεννηθη]{.greek-added} εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν [τον]{.greek-omitted} [οχλον]{.greek-omitted} [εγνωσαν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [ειπεν]{.greek-omitted} [και]{.greek-omitted} [αφεντες]{.greek-omitted} [αυτον]{.greek-omitted} [απηλθον]{.greek-omitted}[12:12]{.aside}

[και]{.greek-omitted} [εζητουν]{.greek-omitted} [αυτον]{.greek-omitted} [κρατησαι]{.greek-omitted} [και]{.greek-omitted} [εφοβηθησαν]{.greek-omitted} τον οχλον εγνωσ[α]{.unclear}ν γαρ οτι προς αυτους την παραβολην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} και αφεντες αυτον απηλθον[12:12 | instance no. 2]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [ηρξαντο]{.greek-added} [επερωταν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [λογω]{.greek-added} διδασκαλε οιδαμεν οτι αληθης ει και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε [υποκριται]{.greek-added} φερετε μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον [αυτω]{.greek-omitted} [καισαρος]{.greek-omitted} [καισσαρος]{.greek-added}[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται [σαδδουκαιοι]{.greek-omitted} [σαδουκκαιοι]{.greek-added} προς αυτον οιτινες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} [αναστασιν]{.greek-omitted} μη ειναι [αναστασιν]{.greek-added} και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν [ημιν]{.greek-omitted} [υμιν]{.greek-added} [οτι]{.greek-omitted} εαν τινος αδελφος αποθανη και [καταλιπη]{.greek-omitted} [σχη]{.greek-added} γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος [αυτου]{.greek-omitted} την γυναικα [αυτου]{.greek-omitted} και εξαναστηση σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [αδελφοι]{.greek-omitted} ησαν [α]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [ελαβεν]{.greek-omitted} [γυναικα]{.greek-omitted} [και]{.greek-omitted} [αποθνησκων]{.greek-omitted} [ουκ]{.greek-omitted} [αφηκεν]{.greek-omitted} [σπερμα]{.greek-omitted}[12:20]{.aside}

[επτα]{.greek-omitted} [αδελφοι]{.greek-omitted} [δελφοι]{.greek-added} [ησαν]{.greek-omitted} [παρ]{.greek-added} [ημιν]{.greek-added} και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και [αποθνησκων]{.greek-omitted} [απεθανε]{.greek-added} [και]{.greek-added} ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20 | instance no. 2]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} [δε]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη αναστασει [ουν]{.greek-added} οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [εκγαμιζονται]{.greek-added} αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεος]{.greek-added} επι [του]{.greek-omitted} [της]{.greek-added} βατου ως ειπεν [αυτω]{.greek-omitted} ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν [πολυ]{.greek-omitted} [πολλοι]{.greek-added} πλανασθε[12:27]{.aside}

και προσελθων εις των γραμματεων [ακουσας]{.greek-omitted} [ακουων]{.greek-added} αυτων συζητουντων [ειδως]{.greek-omitted} [ιδων]{.greek-added} οτι καλως [απεκριθη]{.greek-added} αυτοις [απεκριθη]{.greek-omitted} επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη [παντων]{.greek-omitted} εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} [απεκριθη]{.greek-omitted} [ειπεν]{.greek-added} αυτω [πρωτον]{.greek-added} [οτι]{.greek-omitted} [πρωτη]{.greek-omitted} παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [ακουε]{.greek-omitted} [ακουει]{.greek-added} [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [διανοιας]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} [σου]{.greek-omitted} [αυτη]{.greek-omitted} [πρωτη]{.greek-omitted} [εντολη]{.greek-omitted}[12:30]{.aside}

[και]{.greek-omitted} [αγαπησεις]{.greek-omitted} [κυριον]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [σου]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30 | instance no. 2]{.aside}

[και]{.greek-omitted} δευτερα [δε]{.greek-added} ομοια αυτη αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις εστιν [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της [συνεσεως]{.greek-omitted} [ισχυος]{.greek-added} και εξ ολης της [συνεσεως]{.greek-added} [ψυχης]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων [αυτον]{.greek-omitted} οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον [επερωτησαι]{.greek-omitted} [επερωταν]{.greek-added}[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} [του]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου [υποποδιον]{.greek-omitted} [υποκατω]{.greek-added} των ποδων [σου]{.greek-omitted} [μου]{.greek-added}[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και [ποθεν]{.greek-omitted} [πως]{.greek-added} [υιος]{.greek-abbr} αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και [ο]{.greek-omitted} πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν [αυτοις]{.greek-omitted} εν τη διδαχη αυτου βλεπετε απο των [γραμ]{.greek-added} [γραμματεων]{.greek-omitted} [των]{.greek-omitted} [θελοντων]{.greek-omitted} [εν]{.greek-omitted} [στολαις]{.greek-omitted} [περιπατειν]{.greek-omitted} [και]{.greek-omitted} [ασπασμους]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [αγοραις]{.greek-omitted}[12:38]{.aside}

[και]{.greek-omitted} [ελεγεν]{.greek-omitted} [αυτοις]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted} [βλεπετε]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [ματεων]{.greek-added} των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38 | instance no. 2]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι ληψονται περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [εστως]{.greek-added} ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος [βαλλει]{.greek-omitted} [βαλει]{.greek-added} [τον]{.greek-added} χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου [λεγει]{.greek-omitted} [ελεγεν]{.greek-added} αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη [πλειον]{.greek-omitted} [πλεον]{.greek-added} παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του περισσευοντος αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν [εκ]{.greek-added} [της]{.greek-added} [υστερησεως]{.greek-added} [αυτης]{.greek-added} ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις [εκ]{.greek-added} των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και [ο]{.greek-omitted} [ιησους]{.greek-omitted} αποκριθεις ειπεν αυτω [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [συντελεισθαι]{.greek-omitted} [συντελεσθηναι]{.greek-added}[13:4]{.aside}

[και]{.greek-added} [αποκριθεις]{.greek-added} ο [δε]{.greek-omitted} [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-added} αυτοις [ηρξατο]{.greek-omitted} [λεγειν]{.greek-omitted} βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} και πολλους πλανησουσιν[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουητε]{.greek-added} [πολεμους]{.greek-omitted} [και]{.greek-omitted} ακοας πολεμων [και]{.greek-added} [πολεμους]{.greek-added} μη [θροεισθε]{.greek-omitted} [θροησθε]{.greek-added} δει γαρ [ταυτα]{.greek-added} γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και [ταραχαι]{.greek-omitted} [αρχαι]{.greek-omitted} [λοιμοι]{.greek-added} [ταυτα]{.greek-added} [δε]{.greek-added} [παντα]{.greek-added} [αρχη]{.greek-added} ωδινων [ταυτα]{.greek-omitted}[13:8]{.aside}

βλεπετε δε υμεις [εαυτους]{.greek-omitted} [εαυτοις]{.greek-added} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη προμεριμνατε τι [λαλησητε]{.greek-omitted} [λαλησετε]{.greek-added} [μηδε]{.greek-omitted} [μελετατε]{.greek-omitted} αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα [τουτο]{.greek-omitted} [εκεινο]{.greek-added} λαλειτε ου γαρ εστε υμεις οι [λαλουντες]{.greek-omitted} [αλλα]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αγιον]{.greek-omitted}[13:11]{.aside}

[οταν]{.greek-omitted} [δε]{.greek-omitted} [αγαγωσιν]{.greek-omitted} [υμας]{.greek-omitted} [παραδιδοντες]{.greek-omitted} [μη]{.greek-omitted} [προμεριμνατε]{.greek-omitted} [τι]{.greek-omitted} [λαλησητε]{.greek-omitted} [μηδε]{.greek-omitted} [μελετατε]{.greek-omitted} [αλλ]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [δοθη]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ωρα]{.greek-omitted} [τουτο]{.greek-omitted} [λαλειτε]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [εστε]{.greek-omitted} [υμεις]{.greek-omitted} [οι]{.greek-omitted} λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11 | instance no. 2]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως [στηκον]{.greek-added} [το]{.greek-omitted} [ρηθεν]{.greek-omitted} [υπο]{.greek-omitted} [δανιηλ]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [εστως]{.greek-omitted} οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο [δε]{.greek-omitted} επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι [τι]{.greek-omitted} εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται [ταυτα]{.greek-added} [η]{.greek-omitted} [φυγη]{.greek-omitted} [υμων]{.greek-omitted} χειμωνος [μηδε]{.greek-added} [εν]{.greek-added} [σαββατω]{.greek-added}[13:18]{.aside}

εσονται [γαρ]{.greek-omitted} [δε]{.greek-added} αι ημεραι εκειναι θλιψις οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν [και]{.greek-omitted} [ουδ]{.greek-added} ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-omitted} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ [αλλα]{.greek-omitted} δια [δε]{.greek-added} τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας[13:20]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} [η]{.greek-omitted} ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ [ψευ]{.greek-added} [ψευδοχριστοι]{.greek-omitted} [και]{.greek-omitted} [ψευδοπροφηται]{.greek-omitted} [και]{.greek-omitted} [δωσουσιν]{.greek-omitted} [σημεια]{.greek-omitted} [και]{.greek-omitted} [τερατα]{.greek-omitted} [προς]{.greek-omitted} [το]{.greek-omitted} [αποπλαναν]{.greek-omitted} [ει]{.greek-omitted} [δυνατον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εκλεκτους]{.greek-omitted}[13:22]{.aside}

[εγερθησονται]{.greek-omitted} [γαρ]{.greek-omitted} [δοπροφηται]{.greek-added} [και]{.greek-added} ψευδοχριστοι και [ψευδοπροφηται]{.greek-omitted} [και]{.greek-omitted} [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς [το]{.greek-omitted} [τω]{.greek-added} [αποπλαναν]{.greek-omitted} [πλαναν]{.greek-added} ει δυνατον και τους εκλεκτους[13:22 | instance no. 2]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ [εν]{.greek-omitted} εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες [εκ]{.greek-added} του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν [νεφελαις]{.greek-omitted} [νεφελη]{.greek-added} μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ [ακρου]{.greek-omitted} [ακρων]{.greek-added} [της]{.greek-added} γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν [αυτης]{.greek-omitted} ηδη ο κλαδος [αυτης]{.greek-added} απαλος γενηται και εκφυη [τα]{.greek-omitted} φυλλα γινωσκετε οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν [ιδητε]{.greek-added} ταυτα [ιδητε]{.greek-omitted} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [ου]{.greek-omitted} [εως]{.greek-added} [αν]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [οι]{.greek-omitted} εν [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

[ως]{.greek-omitted} [ωσπερ]{.greek-added} [γαρ]{.greek-added} [ανθρωπος]{.greek-abbr} [αποδημος]{.greek-omitted} [αποδημων]{.greek-added} αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο [ινα]{.greek-omitted} [γρηγορη]{.greek-omitted} [γρηγορειν]{.greek-added}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η [μεσονυκτιου]{.greek-omitted} [μεσονυκτιω]{.greek-added} η [αλεκτοροφωνιας]{.greek-omitted} [αλεκτωροφωνιας]{.greek-added} η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη υμας καθευδοντας[13:36]{.aside}

α δε [λεγω]{.greek-added} υμιν [λεγω]{.greek-omitted} [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον [εν]{.greek-omitted} δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται [του]{.greek-omitted} [λαου]{.greek-omitted} [τω]{.greek-added} [λαω]{.greek-added}[14:2]{.aside}

και οντος αυτου εν βηθανια εν [τη]{.greek-omitted} οικια σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης [πολυτελους]{.greek-omitted} [πολυτιμου]{.greek-added} και συντριψασα το αλαβαστρον κατεχεεν αυτου [κατα]{.greek-omitted} της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους [και]{.greek-omitted} [λεγοντες]{.greek-omitted} εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ [το]{.greek-added} [μυρον]{.greek-added} τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον [γαρ]{.greek-added} εργον ειργασατο [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εις]{.greek-added} [εμε]{.greek-added}[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων [και]{.greek-omitted} [οταν]{.greek-omitted} [θελητε]{.greek-omitted} [δυνασθε]{.greek-omitted} [αυτους]{.greek-omitted} [ευ]{.greek-omitted} [ποιησαι]{.greek-omitted} εμε δε ου παντοτε εχετε[14:7]{.aside}

ο [εσχεν]{.greek-omitted} [ειχεν]{.greek-added} [αυτη]{.greek-omitted} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης εις [εκ]{.greek-added} των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον [αυτοις]{.greek-omitted}[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο αυτω αργυριον δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται [αυτου]{.greek-omitted} που θελεις απελθοντες [ετοιμασωμεν]{.greek-omitted} [ετοιμασομεν]{.greek-added} ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και [εισελθοντων]{.greek-added} [υμων]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [πολει]{.greek-added} απαντησει υμιν [ανθρωπος]{.greek-abbr} [κεραμιον]{.greek-omitted} [κεραμειον]{.greek-added} [υδατος]{.greek-omitted} [βασταζων]{.greek-omitted} [ακολουθησατε]{.greek-omitted} [αυτω]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [αποστελλει]{.greek-omitted} [δυο]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [απαντησει]{.greek-omitted} [υμιν]{.greek-omitted} [ανθρωπος]{.greek-omitted} [κεραμιον]{.greek-omitted} υδατος βασταζων ακολουθησατε αυτω[14:13 | instance no. 2]{.aside}

και οπου εαν εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου [φαγω]{.greek-omitted} [φαγομαι]{.greek-added}[14:14]{.aside}

και αυτος υμιν δειξει [ανωγιον]{.greek-added} [ανωγεον]{.corr} μεγα [εστρωμενον]{.greek-omitted} [εστρωμμενον]{.greek-added} ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον [ετοιμασαι]{.greek-added} [αυτω]{.greek-added} οι μαθηται [αυτου]{.greek-omitted} και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων [ειπεν]{.greek-omitted} [λεγει]{.greek-added} ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο [εμβαπτομενος]{.greek-omitted} [εμβαψας]{.greek-added} μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδιδου]{.greek-added} αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον ευχαριστησας εδωκεν [αυτοις]{.greek-omitted} [και]{.greek-omitted} [επιον]{.greek-omitted} [εξ]{.greek-omitted} [αυτου]{.greek-omitted} [παντες]{.greek-omitted}[14:23]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [ευχαριστησας]{.greek-omitted} [εδωκεν]{.greek-omitted} αυτοις και επιον εξ αυτου παντες[14:23 | instance no. 2]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [υμεις]{.greek-added} σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη [οτι]{.greek-omitted} γεγραπται [γαρ]{.greek-added} παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} τα προβατα [διασκορπισθησονται]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος [εφη]{.greek-omitted} [αποκριθεις]{.greek-added} [λεγει]{.greek-added} αυτω [ει]{.greek-added} και [ει]{.greek-omitted} παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον [εν]{.greek-omitted} τη νυκτι ταυτη πριν [η]{.greek-omitted} [αλεκτορα]{.greek-added} δις [αλεκτορα]{.greek-omitted} φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε [εκπερισσου]{.greek-omitted} [πετρος]{.greek-added} [μαλλον]{.greek-added} [περισσως]{.greek-added} ελεγεν [μαλλον]{.greek-omitted} [οτι]{.greek-added} εαν [δεη]{.greek-added} με [συν]{.greek-added} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} σοι [αποθανειν]{.greek-added} ου μη σε απαρνησωμαι ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσημανει]{.greek-added} και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [αν]{.greek-added} προσευξωμαι[14:32]{.aside}

και [παρα]{.greek-added} [παραλαμβανει]{.greek-omitted} [τον]{.greek-omitted} [πετρον]{.greek-omitted} [και]{.greek-omitted} [ιακωβον]{.greek-omitted} [και]{.greek-omitted} [ιωαννην]{.greek-omitted} [μεθ]{.greek-omitted} [εαυτου]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [εκθαμβεισθαι]{.greek-omitted} [και]{.greek-omitted} [αδημονειν]{.greek-omitted}[14:33]{.aside}

[και]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [λαμβανει]{.greek-added} τον πετρον και [τον]{.greek-added} ιακωβον και [ιωαννην]{.greek-omitted} [μεθ]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [μετ]{.greek-added} [εαυτου]{.greek-omitted} [αυτου]{.greek-added} και ηρξατο εκθαμβεισθαι και αδημονειν[14:33 | instance no. 2]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} [μου]{.greek-added} παντα δυνατα σοι [εστι]{.greek-added} [παρενεγκε]{.greek-omitted} [παρενεγκαι]{.greek-added} το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ [ου]{.greek-omitted} [ουχ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας [μιαν]{.greek-omitted} [μικραν]{.greek-added} ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων [προσηυξατο]{.greek-omitted} [ηυξατο]{.greek-added} τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας [παλιν]{.greek-added} ευρεν αυτους [παλιν]{.greek-omitted} καθευδοντας ησαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ ηδεισαν τι αυτω [αποκριθωσιν]{.greek-omitted} [ανταποκριθωσι]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε λοιπον και αναπαυεσθε απεχει [το]{.greek-added} [τελος]{.greek-added} ηλθεν η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

εγειρεσθε αγωμεν [ιδου]{.greek-omitted} [ο]{.greek-omitted} [παραδιδους]{.greek-omitted} [με]{.greek-omitted} [ηγγικεν]{.greek-omitted}[14:42]{.aside}

[εγειρεσθε]{.greek-omitted} [αγωμεν]{.greek-omitted} ιδου ο παραδιδους με [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added}[14:42 | instance no. 2]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γραμματεων και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον [συσσημον]{.greek-omitted} [σημειον]{.greek-added} [λεγων]{.greek-added} αυτοις [λεγων]{.greek-omitted} ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και [ελθων]{.greek-omitted} ευθεως προσελθων αυτω λεγει [αυτω]{.greek-omitted} [χαιρε]{.greek-added} [ραββι]{.greek-omitted} [ραββει]{.greek-added} [ραββι]{.greek-omitted} και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος [την]{.greek-omitted} μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι [των]{.greek-added} [προφητων]{.greek-added}[14:49]{.aside}

[και]{.greek-omitted} [τοτε]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου [και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} [νεανισκοι]{.greek-added} κρατουσιν αυτον [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν [α]{.greek-added} [απ]{.greek-omitted} [αυτων]{.greek-omitted}[14:52]{.aside}

[π]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [καταλιπων]{.greek-omitted} [την]{.greek-omitted} [σινδονα]{.greek-omitted} [γυμνος]{.greek-omitted} [εφυγεν]{.greek-omitted} [απ]{.greek-omitted} αυτων[14:52 | instance no. 2]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και [συνερχονται]{.greek-omitted} [συνπορευονται]{.greek-added} [αυτω]{.greek-omitted} παντες οι αρχιερεις και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added} και οι [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added}[14:53]{.aside}

και ο πετρος απο μακροθεν [ηκολουθησεν]{.greek-omitted} [ηκολουθει]{.greek-added} αυτω εως [της]{.greek-added} [εσω]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [αυλην]{.greek-omitted} [αυλης]{.greek-added} του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως [ην]{.greek-added} ιση [ην]{.greek-omitted} η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις [το]{.greek-added} μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο [και]{.greek-added} παλιν ο αρχιερευς [επηρωτα]{.greek-omitted} [επηρωτησεν]{.greek-added} αυτον [ει]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} συ ει ο [χριστος]{.greek-abbr} ο υιος του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} ειπεν [αυτω]{.greek-added} [συ]{.greek-added} [ειπας]{.greek-added} [οτι]{.greek-added} εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων [καθημενον]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [και]{.greek-omitted} [κα]{.greek-added} [ερχομενον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [νεφελων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[14:62]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [και]{.greek-omitted} [οψεσθε]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [καθημενον]{.greek-omitted} [θημενον]{.greek-added} της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62 | instance no. 2]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε [της]{.greek-omitted} [παντες]{.greek-added} [την]{.greek-added} [βλασφημιας]{.greek-omitted} [βλασφημιαν]{.greek-added} [αυτου]{.greek-added} τι υμιν [φαινεται]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [δοκει]{.greek-added} [και]{.greek-added} [παντες]{.greek-added} [[κ]{.unclear}ατεκριναν]{.greek-added} [και]{.greek-added} παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [ελαμβανον]{.greek-added}[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα [τον]{.greek-omitted} [αυτον]{.greek-added} [πετρον]{.greek-omitted} θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} [ησθα]{.greek-omitted} [ει]{.greek-added}[14:67]{.aside}

ο δε ηρνησατο λεγων [ουκ]{.greek-omitted} [ουτε]{.greek-added} οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} επισταμαι [συ]{.greek-added} τι [συ]{.greek-omitted} [λεγ[η]{.unclear}ς]{.greek-added} [λεγεις]{.corr} και εξηλθεν εξω εις το [προαυλιον]{.greek-omitted} [προαυλειον]{.greek-added} και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-added} [δε]{.greek-added} [ιδουσα]{.greek-added} [αυτον]{.greek-added} η παιδισκη [ιδουσα]{.greek-omitted} [αυτον]{.greek-omitted} [παλιν]{.greek-omitted} ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστωσιν]{.greek-added} οτι [και]{.greek-added} [ουτος]{.greek-omitted} [αυτος]{.greek-added} εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει [και]{.greek-omitted} [η]{.greek-omitted} [λαλια]{.greek-omitted} [σου]{.greek-omitted} [ομοιαζει]{.greek-omitted}[14:70]{.aside}

ο δε ηρξατο [αναθεμα]{.greek-added} [αναθεματιζειν]{.greek-omitted} [και]{.greek-omitted} [ομνυναι]{.greek-omitted} [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [οιδα]{.greek-omitted} [τον]{.greek-omitted} [ανθρωπον]{.greek-omitted} [τουτον]{.greek-omitted} [ον]{.greek-omitted} [λεγετε]{.greek-omitted}[14:71]{.aside}

[τιζειν]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ηρξατο]{.greek-omitted} [αναθεματιζειν]{.greek-omitted} και [ομνυναι]{.greek-omitted} [ομνυνειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71 | instance no. 2]{.aside}

και [ευθεως]{.greek-added} εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και ανεμνησθη ο πετρος [το]{.greek-omitted} [του]{.greek-added} [ρημα]{.greek-omitted} [ο]{.greek-omitted} [ρηματος]{.greek-added} [ου]{.greek-added} ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα [δις]{.greek-added} φωνησαι [δις]{.greek-omitted} απαρνηση με τρις και επιβαλων [εκλαιεν]{.greek-omitted} [εκλαιε]{.greek-added}[14:72]{.aside}

### Chapter 15

και [ευθυς]{.greek-added} [ευθεως]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} πρωι συμβουλιον [ποιησαντες]{.greek-omitted} [εποιησαν]{.greek-added} οι αρχιερεις μετα των πρεσβυτερων και [των]{.greek-added} γραμματεων και ολον το συνεδριον [και]{.greek-added} δησαντες τον [ιησουν]{.greek-abbr} [απηνεγκαν]{.greek-omitted} [απηγαγον]{.greek-added} και παρεδωκαν [τω]{.greek-omitted} [πηλατω]{.greek-added} [πιλατω]{.corr}[15:1]{.aside}

και επηρωτησεν αυτον ο [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} [λεγων]{.greek-added} συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις [λεγει]{.greek-added} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} παλιν επηρωτησεν αυτον [λεγων]{.greek-omitted} ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον [πιλατον]{.greek-omitted} [πηλατον]{.greek-added}[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} ητουντο[15:6]{.aside}

ην δε ο λεγομενος [βαραββας]{.greek-omitted} [βαραβας]{.greek-added} μετα των [συστασιαστων]{.greek-omitted} [στασιαστων]{.greek-added} δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} [απεκριθη]{.greek-omitted} [αποκριθεις]{.greek-added} αυτοις [λεγων]{.greek-omitted} [λεγει]{.greek-added} θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [ηδει]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδωκαν]{.greek-added} αυτον [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted}[15:10]{.aside}

[εγινωσκεν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [δια]{.greek-omitted} [φθονον]{.greek-omitted} [παραδεδωκεισαν]{.greek-omitted} [αυτον]{.greek-omitted} οι αρχιερεις[15:10 | instance no. 2]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} [παλιν]{.greek-added} αποκριθεις [παλιν]{.greek-omitted} ειπεν αυτοις τι ουν θελετε ποιησω [ον]{.greek-omitted} [τον]{.greek-added} [λεγετε]{.greek-omitted} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν [εκραξαν]{.greek-omitted} [εκραυγαζον]{.greek-added} [ανασειομενοι]{.greek-added} [υπο]{.greek-added} [των]{.greek-added} [αρχιερεων]{.greek-added} [και]{.greek-added} [ελεγον]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσως]{.greek-added} [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} [λεγοντες]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν [και]{.greek-omitted} [τον]{.greek-added} [δε]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [φραγγελωσας]{.greek-added} παρεδωκεν [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [φραγελλωσας]{.greek-omitted} ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον [εσω]{.greek-omitted} [εως]{.greek-added} της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και [ενδυουσιν]{.greek-omitted} [ενδιδυσκουσιν]{.greek-added} [αυτον]{.greek-omitted} [αυτω]{.greek-added} [χλαμυδα]{.greek-added} [κοκκινην]{.greek-added} [και]{.greek-added} πορφυραν και περιτιθεασιν αυτω πλεξαντες [ακανθινον]{.greek-omitted} στεφανον [εξ]{.greek-added} [ακανθων]{.greek-added}[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [βασιλευ]{.greek-added} των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον [την]{.greek-added} [χλαμυδα]{.greek-added} [και]{.greek-added} την πορφυραν και ενεδυσαν αυτον τα ιματια τα [ιδια]{.greek-omitted} [και]{.greek-omitted} [εξαγουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [σταυρωσωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[15:20]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ενεπαιξαν]{.greek-omitted} [αυτω]{.greek-omitted} [εξεδυσαν]{.greek-omitted} [αυτον]{.greek-omitted} [την]{.greek-omitted} [πορφυραν]{.greek-omitted} [και]{.greek-omitted} [ενεδυσαν]{.greek-omitted} [αυτον]{.greek-omitted} [τα]{.greek-omitted} [ιματια]{.greek-omitted} [τα]{.greek-omitted} ιδια και εξαγουσιν αυτον [ινα]{.greek-omitted} [ωστε]{.greek-added} [σταυρωσωσιν]{.greek-omitted} [[σταυρωσαι]{.greek-abbr}]{.greek-added} αυτον[15:20 | instance no. 2]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα [σιμωνα]{.greek-added} τινα [σιμωνα]{.greek-omitted} κυρηναιον ερχομενον [απ]{.greek-omitted} [απο]{.greek-added} αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον [διαμεριζονται]{.greek-omitted} [διεμεριζοντο]{.greek-added} τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η [επιγραφη]{.greek-omitted} [αιτια]{.greek-added} της [αιτιας]{.greek-omitted} [επιγραφης]{.greek-added} αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας [αυτων]{.greek-omitted} και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες [προς]{.greek-omitted} [εις]{.greek-added} αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} [ο]{.greek-omitted} βασιλευς [του]{.greek-omitted} [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [συνεσταυρωμενοι]{.greek-omitted} [αυτω]{.greek-omitted} [ωνειδιζον]{.greek-omitted} [αυτον]{.greek-omitted}[15:32]{.aside}

[ο]{.greek-omitted} [χριστος]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [του]{.greek-omitted} [ισραηλ]{.greek-omitted} [καταβατω]{.greek-omitted} [νυν]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [σταυρου]{.greek-omitted} [ινα]{.greek-omitted} [ιδωμεν]{.greek-omitted} [και]{.greek-omitted} [πιστευσωμεν]{.greek-omitted} [αυτω]{.greek-omitted} και οι [συνεσταυρωμενοι]{.greek-abbr} αυτω ωνειδιζον αυτον[15:32 | instance no. 2]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη [εννατη]{.greek-added} ωρα [τη]{.greek-omitted} [ενατη]{.greek-omitted} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λαμα]{.greek-added} [λιμα]{.corr} [σαβαχθανι]{.greek-omitted} [σαβαχθανει]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον [ιδου]{.greek-omitted} [οτι]{.greek-added} ηλιαν φωνει[15:35]{.aside}

[δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} και [δραμοντες]{.greek-added} [γεμισας]{.greek-omitted} [εγεμισαν]{.greek-added} σπογγον οξους [και]{.greek-added} [περιθεις]{.greek-omitted} [περιθεντες]{.greek-added} [τε]{.greek-omitted} καλαμω [εποτιζεν]{.greek-omitted} [εποτιζον]{.greek-added} αυτον [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [λεγοντες]{.greek-added} [αφες]{.greek-added} ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως [αυτω]{.greek-added} [εξ]{.greek-omitted} [εναντιας]{.greek-omitted} [αυτου]{.greek-omitted} οτι [ουτως]{.greek-omitted} κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} [[θεου]{.greek-abbr}]{.greek-added} ην [θεου]{.greek-omitted}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια η [του]{.greek-omitted} ιακωβου του μικρου και [ιωσητος]{.greek-added} [ιωση]{.corr} [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι [συναναβασαι]{.greek-omitted} [συναβασαι]{.greek-added} αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς [πιλατον]{.greek-omitted} [πηλατον]{.greek-added} και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους [απο]{.greek-omitted} [παρα]{.greek-added} του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισσε]{.greek-added} τη σινδονι και [κατεθηκεν]{.greek-omitted} [εθηκεν]{.greek-added} αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε [μαρια]{.greek-omitted} [μαριαμ]{.greek-added} η μαγδαληνη και μαρια [ιωση]{.greek-omitted} [η]{.greek-added} [ιακωβου]{.greek-added} [και]{.greek-added} [ιωσητος]{.greek-added} [[μητηρ]{.greek-abbr}]{.greek-added} εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου [μαρια]{.greek-omitted} [μαριαμ]{.greek-added} η μαγδαληνη και μαρια [η]{.greek-added} ιακωβου και σαλωμη [πορευθεισαι]{.greek-added} ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον [ετι]{.greek-added} ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον [νεανι]{.greek-added} [νεανισκον]{.greek-omitted} [καθημενον]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [δεξιοις]{.greek-omitted} [περιβεβλημενον]{.greek-omitted} [στολην]{.greek-omitted} [λευκην]{.greek-omitted} [και]{.greek-omitted} [εξεθαμβηθησαν]{.greek-omitted}[16:5]{.aside}

[σκον]{.greek-added} [και]{.greek-omitted} [εισελθουσαι]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [μνημειον]{.greek-omitted} [ειδον]{.greek-omitted} [νεανισκον]{.greek-omitted} καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5 | instance no. 2]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβησθε]{.greek-added} [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι [ιδου]{.greek-added} προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ου[ν]{.unclear} [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

