---
title: "Collation of Byz^RP^ vs 31593 (1593)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1593 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31593).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1593                                   	| λογος                              	|
| 1593 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1593 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1593               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1593                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1593 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1593                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω [αποστελλω]{.greek-omitted} [αποστελω]{.greek-added} τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου ε[μ]{.unclear}προσθεν σου[1:2]{.aside}

φων[η]{.unclear} βοωντος εν [τη]{.greek-omitted} ερημω ετοιμασατε την οδον [του]{.greek-added} [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο [[ιω]{.greek-abbr}]{.greek-added} [ιωαννης]{.greek-omitted} [βαπτιζων]{.greek-omitted} εν τη ερημω [βαπτιζων]{.greek-added} και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται [παντες]{.greek-added} και εβαπτιζοντο [παντες]{.greek-omitted} εν τω [ιορδανη]{.greek-omitted} [ιορ]{.greek-added} [δανη]{.greek-added} ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και εκηρυσσεν λεγων ερχεται ο ισχυροτερος μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[1:8]{.aside}

και εγενετο εν [εκειναις]{.greek-omitted} ταις ημεραις [εκειναις]{.greek-added} ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ [της]{.greek-omitted} [εις]{.greek-added} [την]{.greek-added} [γαλιλαιας]{.greek-omitted} [γαλιλαιαν]{.greek-added} και εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει [περιστεραν]{.greek-omitted} [περαν]{.greek-added} καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν [ω]{.greek-omitted} [σοι]{.greek-added} [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και ευθυς το [πνευμα]{.greek-abbr} [εκβαλλει]{.greek-added} αυτον [εκβαλλει]{.greek-omitted} εις την ερημον[1:12]{.aside}

και ην εκει εν τη ερημω ημερας τεσσαρακοντα πειραζομενος υπο του σατανα και ην μετα των θηριων και [οι]{.greek-omitted} αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} σιμωνα και ανδρεαν τον αδελφον [αυτου]{.greek-omitted} του σιμωνος βαλλοντας αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας [γενεσθαι]{.greek-omitted} αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων [και]{.greek-added} απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο [[εξεπληττοντο]{.corr}]{.greek-added} επι τη διδαχη αυτου ην γαρ διδασκων αυτους [ως]{.greek-omitted} [ωο]{.greek-added} εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων εα τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε [εξ]{.greek-omitted} [απ]{.greek-added} αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους [λεγοντας]{.greek-omitted} [λεγοντες]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [[πνασι]{.greek-abbr}]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

εξηλθεν δε η ακοη αυτου ευθυς εις ολην την περιχωρον [εκεινην]{.greek-added} της γαλιλαιας[1:28]{.aside}

και ευθεως [εξελθοντες]{.greek-added} εκ της συναγωγης [εξελθοντες]{.greek-omitted} ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην [κρατησας]{.greek-omitted} [κρατισας]{.greek-added} της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ ηφιεν λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ειδησαν]{.greek-added} [τον]{.greek-added} [[χριστον]{.greek-abbr}]{.greek-added} αυτον [ειναι]{.greek-added}[1:34]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} αυτον ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες σε ζητουσιν[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και εκει κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [ταις]{.greek-omitted} [συναγωγαις]{.greek-omitted} [εις]{.greek-added} [την]{.greek-added} [συναγωγην]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων [αυτον]{.greek-omitted} [αυτω]{.greek-added} και λεγων αυτω οτι εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου [λεγων]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} αυτω θελω καθαρισθητι[1:41]{.aside}

και [ειποντος]{.greek-omitted} [αυτου]{.greek-omitted} ευθεως [η]{.greek-added} [λεπρα]{.greek-added} απηλθεν απ αυτου [η]{.greek-omitted} [λεπρα]{.greek-omitted} και [εκαθαρισθη]{.greek-omitted} [εκαθερισθη]{.greek-added}[1:42]{.aside}

και εμβριμησαμενος αυτω ευθεως εξεβαλεν αυτον[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως εις πολιν εισελθειν [αλλ]{.greek-omitted} [αλλα]{.greek-added} εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον πανταχοθεν[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι [χωρειν]{.greek-omitted} [χορειν]{.greek-added} μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

[και]{.greek-added} ιδων [δε]{.greek-omitted} ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι αμαρτιαι σου[2:5]{.aside}

ησαν δε τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [σου]{.greek-omitted} τον κραββατον [σου]{.greek-added} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} αφιεναι επι της γης αμαρτιας λεγει τω παραλυτικω[2:10]{.aside}

σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και [ηγερθη]{.greek-omitted} [εγερθεις]{.greek-added} ευθεως και αρας τον κραββατον εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added}[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} λευι τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου [και]{.greek-omitted} πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου [τι]{.greek-omitted} οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει [ο]{.greek-added} [διδασκαλος]{.greek-added} [υμων]{.greek-added}[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και [ησαν]{.greek-omitted} [ηησαν]{.greek-added} οι μαθηται [[ιω]{.greek-abbr}]{.greek-added} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται [οι]{.greek-omitted} υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον μεθ εαυτων [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν [απαρθη]{.greek-omitted} [απαρθει]{.greek-added} απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

και ουδεις επιβλημα [ρακους]{.greek-omitted} [ρακκους]{.greek-added} αγναφου επιρραπτει επι ιματιω παλαιω ει δε [μη]{.greek-omitted} [μηγε]{.greek-added} αιρει [απ]{.greek-added} [αυτου]{.greek-added} το πληρωμα [αυτου]{.greek-omitted} [του]{.greek-added} [παλαιου]{.greek-added} το καινον [του]{.greek-omitted} [παλαιου]{.greek-omitted} και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον [νεον]{.corr} εις ασκους παλαιους ει δε μη [ρησσει]{.greek-omitted} [ρισσει]{.greek-added} ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον εις ασκους [καινους]{.greek-omitted} [κενους]{.greek-added} βλητεον[2:22]{.aside}

και εγενετο [εν]{.greek-added} [τω]{.greek-added} παραπορευεσθαι αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και ηρξαντο οι μαθηται αυτου οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον αυτω ιδε τι ποιουσιν εν τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι εποιησεν [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ αρχιερεως και τους αρτους της προθεσεως εφαγεν ους ουκ εξεστιν φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον ει [εν]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} εχοντι [ξηραν]{.greek-added} την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις εξεστιν [εν]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη [πωρωσει]{.greek-omitted} [πορωσει]{.greek-added} της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου [υγιης]{.greek-omitted} [υγιεις]{.greek-added} ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι [ευθεως]{.greek-omitted} μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον απολεσωσιν[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρισεν]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [ηκολουθησεν]{.greek-added} αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και [σιδωνα]{.greek-omitted} [σιδονα]{.greek-added} πληθος πολυ ακουσαντες [οσα]{.greek-omitted} [τα]{.greek-added} [θαυμασια]{.greek-added} [α]{.greek-added} εποιει ηλθον προς αυτον[3:8]{.aside}

και ειπεν τοις μαθηταις αυτου ινα πλοιαριον [προσκαρτερη]{.greek-omitted} [προσκαρτερει]{.greek-added} αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα οταν αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και εποιησεν δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και [εχειν]{.greek-omitted} [εχει]{.greek-added} εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον του ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν [οι]{.greek-added} υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [εισερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν [ο]{.greek-added} οχλος ωστε μη δυνασθαι αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι [αρχιερεις]{.greek-added} [γραμματεις]{.corr} οι απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην [μερισθη]{.greek-omitted} [μερισθεισα]{.greek-added} ου δυναται σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται [ου]{.greek-omitted} [πως]{.greek-added} δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις την οικιαν αυτου διαρπασαι εαν μη πρωτον τον ισχυρον [δηση]{.greek-omitted} [δησει]{.greek-added} και τοτε την οικιαν αυτου [διαρπαση]{.greek-omitted} [διαρπασει]{.greek-added}[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα αμαρτηματα τοις υιοις των [ανθρωπων]{.greek-abbr} και βλασφημιαι οσας αν βλασφημησωσιν[3:28]{.aside}

ος δ αν [βλασφημηση]{.greek-omitted} [βλασφημησει]{.greek-added} εις το [αγιον]{.greek-added} [πνευμα]{.greek-abbr} [το]{.greek-omitted} [αγιον]{.greek-omitted} ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι και [η]{.greek-omitted} [οι]{.greek-added} [μητηρ]{.greek-abbr} αυτου και εξω [εστωτες]{.greek-omitted} [εστοτες]{.greek-added} απεστειλαν προς αυτον φωνουντες [αυτον]{.greek-omitted} [αυτ[ω]{.unclear}]{.greek-added}[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω ζητουσιν σε[3:32]{.aside}

και απεκριθη αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου η οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει ιδε η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [μου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν [της]{.greek-added} [γαλιλαιας]{.greek-added} και συνηχθη προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις [το]{.greek-omitted} πλοιον [καθησθαι]{.greek-omitted} [καθησαι]{.greek-added} εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων [του]{.greek-omitted} σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι [το]{.greek-omitted} [τα]{.greek-added} πετρωδες οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακαν[θα]{.unclear}ς και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added}[4:7]{.aside}

και αλλο επεσεν [εις]{.greek-omitted} [επι]{.greek-added} την γην την καλην και εδιδου καρπον [αναβαινοντα]{.greek-omitted} [αναβαινων]{.greek-added} και αυξανοντα και εφερεν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [ηρωτησαν]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} [ηρωτων]{.greek-added} αυτον οι περι αυτον συν τοις δωδεκα την παραβολην [ταυτην]{.greek-added}[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις τα παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη συνιωσιν μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και αφεθη αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν [ευθεως]{.greek-omitted} ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον λογον ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος [γινονται]{.greek-added} [γινεται]{.corr}[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και [καρποφορουσι]{.greek-added} [και]{.greek-added} παραδεχονται [και]{.greek-omitted} [καρποφορουσιν]{.greek-omitted} [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις μητι ο λυχνος ερχεται ινα [υπο]{.greek-omitted} [επι]{.greek-added} τον μοδιον [τεθη]{.greek-omitted} [τεθει]{.greek-added} η υπο την κλινην ουχ ινα επι την λυχνιαν [επιτεθη]{.greek-omitted} [επιτεθει]{.greek-added}[4:21]{.aside}

ου γαρ εστι[ν]{.unclear} τι κρυπτον ο εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

[ει]{.greek-omitted} [η]{.greek-added} τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε [μετρηθησεται]{.greek-omitted} [αντιμετριθησεται]{.greek-added} υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ αν [εχη]{.greek-omitted} [εχει]{.greek-added} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και [ουτως]{.greek-added} ελεγεν [ουτως]{.greek-omitted} εστιν η βασιλεια του [θεου]{.greek-abbr} ως [εαν]{.greek-omitted} [ανθρωπος]{.greek-abbr} βαλη [τον]{.greek-omitted} σπορον επι της γης[4:26]{.aside}

και [καθευδη]{.greek-omitted} [καθευδει]{.greek-added} και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλαστανει]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα [πληρη]{.greek-omitted} [πληροι]{.greek-added} σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει [το]{.greek-omitted} [τον]{.greek-added} δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως κοκκον σιναπεως [ος]{.greek-omitted} [ως]{.greek-added} οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} επι της γης [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν [σπαρη]{.greek-omitted} [[σπ]{.unclear}α[ρε]{.unclear}ι]{.greek-added} [[φυη]{.corr}]{.greek-added} αναβαινει και γινεται παντων των λαχανων [μειζων]{.greek-omitted} [μειζω]{.greek-added} και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις πολλαις ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

[χωρις]{.greek-omitted} [χορις]{.greek-added} δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον [ως]{.greek-omitted} [ος]{.greek-added} ην εν τω πλοιω και [ην]{.greek-added} αλλα [δε]{.greek-omitted} πλοιαρια [ην]{.greek-omitted} μετ αυτου[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λελαψ]{.greek-added} ανεμου μεγαλη τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε αυτο [ηδη]{.greek-omitted} [ηδει]{.greek-added} γεμιζεσθαι[4:37]{.aside}

και ην αυτος επι [τη]{.greek-omitted} [την]{.greek-added} [πρυμνη]{.greek-omitted} [πρυμνην]{.greek-added} επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελη]{.greek-added} σοι οτι [απολλυμεθα]{.greek-omitted} [απολυμεθα]{.greek-added}[4:38]{.aside}

και διεγερθ[ει]{.unclear}ς [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα [πεφιμωσο]{.greek-omitted} [πεφημωσο]{.greek-added} και εκοπασεν ο ανεμος και εγενετο [γαληνη]{.greek-omitted} [γαλινη]{.greek-added} μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι [δειλοι]{.greek-omitted} [δηλοι]{.greek-added} εστε ουτω[ς]{.unclear} [πως]{.greek-omitted} ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον [μεγαν]{.greek-omitted} [μεγα]{.greek-added} και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

[και]{.greek-omitted} [κκαι]{.greek-added} ηλθον εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γαδαρινων]{.greek-added}[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω[5:2]{.aside}

ος την κατοικησιν ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις εδυνατο αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις [πεδαις]{.greek-omitted} [πεδες]{.greek-added} και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και [διεσπασθαι]{.greek-omitted} [διασπασθαι]{.greek-added} [υπ]{.greek-omitted} [απ]{.greek-added} αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [ισχυεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημασι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και [σοι]{.greek-omitted} [συ]{.greek-added} [[ιησου]{.greek-abbr}]{.corr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

ελεγεν γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα αυτον τι [σοι]{.greek-omitted} [το]{.greek-added} ονομα [σου]{.greek-added} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον [πολλα]{.greek-omitted} [λεγων]{.greek-added} ινα μη [αποστειλει]{.greek-added} αυτους [αποστειλη]{.greek-omitted} εξω της χωρας[5:10]{.aside}

ην δε εκει [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων [μεγαλη]{.greek-omitted} [προς]{.greek-added} [το]{.greek-added} [ορει]{.greek-added} βοσκομενη[5:11]{.aside}

και παρεκαλεσαν αυτον παντες οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα [πνευματα]{.greek-omitted} [[πνατα]{.greek-abbr}]{.greek-added} τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και [επνιγοντο]{.greek-omitted} [επνηγοντο]{.greek-added} εν τη θαλασση[5:13]{.aside}

[και]{.greek-added} οι [δε]{.greek-omitted} βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} ιδειν [το]{.greek-added} [γεγωνος]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} [το]{.greek-omitted} [γεγονος]{.greek-omitted}[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και [σωφρονουντα]{.greek-omitted} [σοφρονουντα]{.greek-added} τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι [ιδοντες]{.greek-omitted} [ιδοτες]{.greek-added} πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα [η]{.greek-omitted} μετ αυτου [ει]{.greek-added}[5:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} πεποιηκεν και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν [τω]{.greek-omitted} πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων [επιθης]{.greek-omitted} [επιθεις]{.greek-added} [αυτη]{.greek-omitted} [αυτω]{.greek-added} τας χειρας οπως [σωθη]{.greek-omitted} [σωθει]{.greek-added} και ζησεται[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απ[η]{.unclear}λθε]{.greek-added} μετ αυτου και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω οχλος πολυς και συνεθλιβον [αυτον]{.greek-omitted} [αυτω]{.greek-added}[5:24]{.aside}

και γυνη τις ουσα εν [ρυσει]{.greek-omitted} [ρυση]{.greek-added} αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ αυτης παντα και μηδεν [ωφεληθεισα]{.greek-omitted} [οφεληθησα]{.greek-added} αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του [κρασπεδου]{.greek-added} [του]{.greek-added} ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι καν των ιματιων αυτου [αψωμαι]{.greek-omitted} [αψομαι]{.greek-added} σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη [φοβηθεισα]{.greek-omitted} [φοβηθησα]{.greek-added} και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη [θαρσει]{.greek-added} θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε [υπαγε]{.greek-omitted} [εις]{.greek-omitted} [πορευου]{.greek-added} [εν]{.greek-added} [ειρηνην]{.greek-omitted} [ειρηνη]{.greek-added} και ισθι [υγιης]{.greek-omitted} [υγιεις]{.greek-added} απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι [σκυλλεις]{.greek-omitted} [σκυλει]{.greek-added} τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} [ευθεως]{.greek-omitted} ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα [αυτω]{.greek-omitted} [αυτων]{.greek-added} [συνακολουθησαι]{.greek-omitted} [συνακολουθισαι]{.greek-added} ει μη πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι θορυβεισθε και [κλαιετε]{.greek-omitted} [κλαιεται]{.greek-added} το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και [κατεγελων]{.greek-omitted} [κατεγελουν]{.greek-added} αυτου ο δε εκβαλων [παντας]{.greek-omitted} [απαντας]{.greek-added} [παραλαμβανει]{.greek-omitted} [παραλαμβανη]{.greek-added} τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και εισπορευεται οπου ην το παιδιον ανακειμενον[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη [ταλιθα]{.greek-omitted} [ταβηθα]{.greek-added} [κουμι]{.greek-omitted} [κουμ]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω [τουτο]{.greek-omitted} [τουτω]{.greek-added} και ειπεν δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν [και]{.greek-omitted} [ηλθεν]{.greek-omitted} εις την [πατριδα]{.greek-omitted} [[πριδα]{.greek-abbr}]{.greek-added} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η σοφια η [δοθεισα]{.greek-omitted} [δοθησα]{.greek-added} αυτω [ινα]{.greek-added} και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο τεκτων ο [υιος]{.greek-abbr} μαριας αδελφος δε [ιωσηφ]{.greek-added} [[ιωση]{.corr}]{.greek-added} [και]{.greek-added} ιακωβου [και]{.greek-omitted} [ιωση]{.greek-omitted} και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

ελεγεν δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσι]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ ηδυνατο εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και εθαυμαζεν δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και [προσκαλειται]{.greek-omitted} [προσκαειται]{.greek-added} τους δωδεκα και ηρξατο [αυτους]{.greek-omitted} αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν [των]{.greek-omitted} [κατα]{.greek-added} [πνευματων]{.greek-abbr} [των]{.greek-omitted} ακαθαρτων[6:7]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν [αιρωσιν]{.greek-omitted} [ερωσιν]{.greek-added} εις [την]{.greek-added} οδον ει μη ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη ενδυσησθε δυο [χιτωνας]{.greek-omitted} [χιτονας]{.greek-added}[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη [δεξωνται]{.greek-omitted} [δεξονται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον [εσται]{.greek-omitted} [εστι]{.greek-added} σοδομοις η γομορροις εν ημερα κρισεως η τη πολει εκεινη[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και [ηλειφον]{.greek-omitted} [ειληφον]{.greek-added} ελαιω πολλους αρρωστους και [εθεραπευον]{.greek-omitted} [εθεραπευοντο]{.greek-added}[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης [την]{.greek-added} [ακοην]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων ηγερθη και δια τουτο ενεργουσιν αι δυναμεις [εν]{.corr} αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε ηρωδης ειπεν οτι ον [εγω]{.corr} [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ [ο]{.greek-omitted} ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και εδησεν αυτον [εν]{.greek-omitted} [εις]{.greek-added} [φυλακη]{.greek-omitted} [φυλακην]{.greek-added} δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

ελεγεν γαρ ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

[η]{.greek-omitted} [ο]{.greek-added} δε [ηρωδιας]{.greek-omitted} [ηρωδης]{.greek-added} ενειχεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και ηθελεν [αποκτιναι]{.greek-added} αυτον [αποκτειναι]{.greek-omitted} και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [ειδως]{.greek-omitted} [ιδως]{.greek-added} αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και [ακουσας]{.greek-omitted} [ακουων]{.greek-added} αυτου πολλα εποιει και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και [ορχησαμενης]{.greek-omitted} [ορχισαμενης]{.greek-added} και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω [αιτησον]{.greek-omitted} [αιτισον]{.greek-added} [με]{.greek-omitted} [μοι]{.greek-added} ο εαν [θελης]{.greek-omitted} [θελεις]{.greek-added} και δωσω σοι[6:22]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμωσεν]{.greek-added} αυτη [ο]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ο εαν με [αιτησης]{.greek-omitted} [αιτησεις]{.greek-added} δωσω σοι εως [ημισους]{.greek-omitted} [ημισου]{.greek-added} της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε ειπεν την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:24]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην [αθετησαι]{.greek-omitted} [αθετισαι]{.greek-added}[6:26]{.aside}

και ευθεως αποστειλας ο βασιλευς σπεκουλατορα επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλησεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακαι]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και ηνεγκεν την κεφαλην αυτου επι πινακι και εδωκεν αυτην τω κορασιω και το κορασιον [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} [αυτην]{.greek-omitted} τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλ[α]{.unclear}ν αυτω παντα και οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν εις ερημον τοπον και [αναπαυεσθε]{.greek-omitted} [αναπαυσασθε]{.greek-added} ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added}[6:31]{.aside}

και απηλθον εις ερημον τοπον [τω]{.greek-omitted} [πλοιω]{.greek-omitted} [το]{.greek-added} [πλοιον]{.greek-added} κατ ιδιαν[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδων]{.greek-added} αυτους υπαγοντας [πολλοι]{.greek-added} και επεγνωσαν [αυτον]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [πεζη]{.greek-omitted} απο πασων των πολεων [και]{.greek-added} [πεζει]{.greek-added} συνεδραμον εκει και [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ο [ιησους]{.greek-abbr} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και [ηδη]{.greek-omitted} [ηδει]{.greek-added} ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και [ηδη]{.greek-omitted} [ηδει]{.greek-added} ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας [αγορασωσιν]{.greek-omitted} [αγορασουσιν]{.greek-added} εαυτοις αρτους τι γαρ φαγωσιν ουκ εχουσιν[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω [απελθοντες]{.greek-omitted} [απελθοτες]{.greek-added} αγορασωμεν [διακοσιων]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} αρτους και δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και [γνοντες]{.greek-omitted} [γνωντες]{.greek-added} λεγουσιν [αυτω]{.greek-added} πεντε [αρτους]{.greek-added} και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι [[ανακλιθηναι]{.corr}]{.greek-added} παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ηυλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας εμερισεν [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν κλασματων δωδεκα κοφινους [πληρεις]{.greek-omitted} [πληρης]{.greek-added} και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηνεγκασε]{.greek-added} τους μαθητας [αυτου]{.greek-omitted} εμβηναι εις το πλοιον και προαγειν εις το περαν προς βηθσαιδαν εως αυτος [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον [μεσον]{.greek-added} [εν]{.greek-omitted} [μεσω]{.greek-omitted} της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω ελαυνειν ην γαρ [εναντιος]{.greek-added} [αυτοις]{.greek-added} ο ανεμος [εναντιος]{.greek-omitted} [αυτοις]{.greek-omitted} και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ [ειδον]{.greek-added} αυτον [ειδον]{.greek-omitted} και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ [αυτων]{.greek-omitted} η καρδια [αυτων]{.greek-added} πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην γεννησαρετ και [προσωρμισθησαν]{.greek-omitted} [προσορμισθησαν]{.greek-added}[6:53]{.aside}

και [εξελθοντων]{.greek-omitted} [εξελθωντων]{.greek-added} αυτων [εκ]{.greek-omitted} [απο]{.greek-added} του πλοιου ευθεως [επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} αυτον [οι]{.greek-added} [ανδρες]{.greek-added} [του]{.greek-added} [τοπου]{.greek-added}[6:54]{.aside}

[περιδραμοντες]{.greek-omitted} [περιδραμωντες]{.greek-added} ολην την περιχωρον εκεινην ηρξαντο επι τοις [κραββατοις]{.greek-omitted} [κραβαττοις]{.greek-added} τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει εστιν[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η [εις]{.greek-added} πολεις η αγρους εν ταις αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου [αψωνται]{.greek-omitted} [αψονται]{.greek-added} και οσοι αν ηπτοντο [αυτου]{.greek-omitted} εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις χερσιν τουτ εστιν ανιπτοις εσθιοντας αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη [νιψονται]{.greek-added} πυγμη [νιψωνται]{.greek-omitted} τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και [απο]{.greek-omitted} [απ]{.greek-added} αγορας εαν μη [βαπτισωνται]{.greek-omitted} [βαπτισονται]{.greek-added} ουκ εσθιουσιν και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και [ξεστων]{.greek-omitted} [ξεστιων]{.greek-added} και χαλκιων και κλινων[7:4]{.aside}

επειτα [επερωτωσιν]{.greek-omitted} [επαιρωτωσιν]{.greek-added} αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την [πα]{.greek-added} [παραδοσιν]{.greek-omitted} [ραδοσιν]{.greek-added} των πρεσβυτερων αλλα ανιπτοις χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε [σεβονται]{.greek-omitted} [σεβοντε]{.greek-added} με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα πολλα ποιειτε[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ ειπεν τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν [ειπη]{.greek-omitted} [ειπει]{.greek-added} [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου [ωφεληθης]{.greek-omitted} [οφεληθεις]{.greek-added}[7:11]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη [παραδοσει]{.greek-omitted} [παραδωσει]{.greek-added} υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον [ο]{.greek-omitted} [ου]{.greek-added} δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [κοινοι]{.greek-added} [εστιν]{.greek-omitted} [τα]{.greek-omitted} [κοινουντα]{.greek-omitted} τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

[ει]{.greek-omitted} [η]{.greek-added} τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου επηρωτων αυτον οι μαθηται αυτου περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε [ου]{.greek-omitted} [ουπω]{.greek-added} νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν [αλλ]{.greek-omitted} [αλλα]{.greek-added} εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

ελεγεν δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον [εκεινο]{.greek-omitted} [εκεινω]{.greek-added} κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται [μοιχειαι]{.greek-omitted} [μοιχιαι]{.greek-added} [πορνειαι]{.greek-omitted} [πορνιαι]{.greek-added} φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι πονηριαι δολος [ασελγεια]{.greek-omitted} [ασελγιαι]{.greek-added} οφθαλμος πονηρος βλασφημια υπερηφανια αφροσυνη[7:22]{.aside}

[ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [τα]{.greek-omitted} πονηρα εσωθεν [εκπορευεται]{.greek-omitted} [εκπορευονται]{.greek-added} και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελησεν]{.greek-added} γνωναι και ουκ [ηδυνηθη]{.greek-omitted} [εδυνηθη]{.greek-added} λαθειν[7:24]{.aside}

ακουσασα γαρ [γυνη]{.greek-omitted} περι αυτου ης ειχεν το θυγατριον αυτης [πνευμα]{.greek-abbr} ακαθαρτον ελθουσα προσεπεσεν προς τους ποδας αυτου[7:25]{.aside}

ην δε η γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συροφοινικησα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον εστιν λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των ψιχιων των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ηυρεν]{.greek-added} το δαιμονιον [εξεληλυθος]{.greek-omitted} [εξεληλυθως]{.greek-added} και την θυγατερα [βεβλημενην]{.greek-omitted} [βεβλημμενην]{.greek-added} επι της κλινης[7:30]{.aside}

και παλιν [εξελθων]{.greek-omitted} [εεξελθων]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εκ των οριων τυρου και σιδωνος ηλθεν προς την θαλασσαν της γαλιλαιας ανα [μεσον]{.greek-omitted} [μεσων]{.greek-added} των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} κωφον [και]{.greek-added} μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω [την]{.greek-omitted} [τας]{.greek-added} [χειρα]{.greek-omitted} [χειρας]{.greek-added}[7:32]{.aside}

και [απολαβομενος]{.greek-omitted} [επιλαβομενος]{.greek-added} αυτον απο του οχλου κατ ιδιαν εβαλεν τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον ουρανον εστεναξεν και λεγει αυτω εφφαθα ο εστιν διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο [δεσμος]{.greek-omitted} [δαισμος]{.greek-added} της γλωσσης αυτου και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ορθως[7:35]{.aside}

και [διεστειλατο]{.greek-omitted} [διεστηλατο]{.greek-added} [αυτοις]{.greek-omitted} [αυτης]{.greek-added} ινα μηδενι ειπωσιν οσον δε [αυτοις]{.greek-added} αυτος [αυτοις]{.greek-omitted} διεστελλετο [και]{.greek-added} μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και [υπερπερισσως]{.greek-omitted} [υπερπερυσσως]{.greek-added} εξεπλησσοντο λεγοντες καλως παντα πεποιηκεν και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν [εκειναις]{.greek-omitted} [αικειναις]{.greek-added} ταις [ημεραις]{.greek-omitted} [ηημεραις]{.greek-added} παμπολλου οχλου οντος και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγειν]{.greek-added} προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις προσμενουσιν μοι και ουκ εχουσιν τι φαγωσιν[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις [οικον]{.greek-omitted} [τους]{.greek-added} [οικους]{.greek-added} αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων [ηκουσιν]{.greek-added} μακροθεν [ηκουσιν]{.greek-omitted}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους [δυνησεται]{.greek-omitted} [δυνησηται]{.greek-added} τις ωδε χορτασαι [αρτων]{.greek-omitted} [αρτον]{.greek-added} επ ερημιας[8:4]{.aside}

και επηρωτα αυτους ποσους [εχετε]{.greek-omitted} [εχεται]{.greek-added} αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλλεν]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας εκλασεν και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παρατιθωσιν]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και [αυτα]{.greek-added} ευλογησας ειπεν [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες [ως]{.greek-omitted} τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου [ηλθεν]{.greek-omitted} [και]{.greek-added} [ειλθεν]{.greek-added} εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι [ππρος]{.greek-added} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} και ηρξαντο συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} [αυτου]{.greek-omitted} λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους και ει μη ενα αρτον ουκ [ειχον]{.greek-omitted} [ηχον]{.greek-added} μεθ [εαυτων]{.greek-omitted} [εαυτον]{.greek-added} εν τω [πλοιω]{.greek-omitted} [πλοιων]{.greek-added}[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

και διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added}[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι [διαλογιζεσθε]{.greek-omitted} [διαλογιζεσθαι]{.greek-added} [εν]{.greek-added} [ταις]{.greek-added} [καρδιαις]{.greek-added} [υμων]{.greek-added} οτι αρτους ουκ εχετε ουπω [νοειτε]{.greek-omitted} [νοειται]{.greek-added} ουδε συνιετε [ετι]{.greek-omitted} [οτι]{.greek-added} πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ [ακουετε]{.greek-omitted} [ακουεται]{.greek-added} και ου μνημονευετε[8:18]{.aside}

οτε τους [πεντε]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} αρτους εκλασα εις τους πεντακισχιλιους ποσους κοφινους πληρεις κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα [αρτους]{.greek-added} εις τους τετρακισχιλιους [ποσων]{.greek-omitted} [ποσον]{.greek-added} σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και ελεγεν αυτοις πως ου συνιετε[8:21]{.aside}

[και]{.greek-omitted} ερχεται [[δε]{.corr}]{.greek-added} εις βηθσαιδαν και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας [αυτω]{.greek-omitted} επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας ελεγεν βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ανεβλεψεν]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

[και]{.greek-omitted} εξηλθεν [δε]{.greek-added} ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων [αυτοις]{.greek-omitted} τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην και αλλοι ηλιαν [η]{.greek-added} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδεν[ι]{.unclear} [λεγωσιν]{.greek-omitted} [λεγουσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και των αρχιερεων και των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε [επιστραφεις]{.greek-omitted} [στραφεις]{.greek-added} και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [ει]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελει οπισω μου ακολουθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34]{.aside}

ος γαρ αν [θελη]{.greek-omitted} [θελει]{.greek-added} την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την [εαυτου]{.greek-omitted} ψυχην [αυτου]{.greek-added} ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ [ωφελησει]{.greek-omitted} [οφελησει]{.greek-added} [τον]{.greek-added} [ανθρωπον]{.greek-abbr} εαν [κερδηση]{.greek-omitted} [κερδησει]{.greek-added} τον κοσμον ολον και [ζημιωθη]{.greek-omitted} [ζημιωθει]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

[ος]{.greek-omitted} [οστις]{.greek-added} γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη [μοιχαλιδι]{.greek-omitted} [μυχαλιδι]{.greek-added} και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη [εν]{.greek-omitted} τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων των αγιων[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν [οτι]{.greek-omitted} [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ [παραλαμβανει]{.greek-omitted} [παραλαμβανη]{.greek-added} ο [ιησους]{.greek-abbr} τον πετρον και [τον]{.greek-omitted} ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν [ως]{.greek-omitted} [ωσει]{.greek-added} χιων οια γναφευς επι της γης [ου]{.corr} δυναται λευκαναι[9:3]{.aside}

και [ωφθη]{.greek-omitted} [ωφθησαν]{.greek-added} αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και μωση μιαν και ηλια μιαν[9:5]{.aside}

[ου]{.greek-omitted} [ουδε]{.greek-added} γαρ ηδει τι [λαλησει]{.greek-omitted} [λαλει]{.greek-added} ησαν γαρ [εκφοβοι]{.greek-omitted} [εμφοβοι]{.greek-added}[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και ηλθεν φωνη εκ της νεφελης ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και [εξαπινα]{.greek-omitted} [εξαπηνα]{.greek-added} περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον [μεθ]{.greek-omitted} [μετ]{.greek-added} [εαυτων]{.greek-omitted} [αυτων]{.greek-added}[9:8]{.aside}

[καταβαινοντων]{.greek-omitted} [καταβαινωντων]{.greek-added} δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} [διηγησονται]{.greek-added} α ειδον ει μη οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν [αυτοις]{.greek-omitted} ηλιας [μεν]{.greek-omitted} ελθων [πρωτον]{.greek-omitted} [πρωτου]{.greek-added} αποκαθιστα παντα και πως γεγραπται [επι]{.greek-omitted} [εις]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα [παθη]{.greek-omitted} [παθει]{.greek-added} και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ [αυτον]{.greek-omitted} [αυτω]{.greek-added}[9:13]{.aside}

και [ελθων]{.greek-omitted} [προσελθων]{.greek-added} προς τους μαθητας [αυτου]{.greek-added} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο [αυτον]{.greek-omitted} [αυτω]{.greek-added}[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτισε]{.greek-added} τους γραμματεις τι συζητειτε προς [αυτους]{.greek-omitted} [εαυτους]{.greek-added}[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν διδασκαλε ηνεγκα τον υιον μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου αν αυτον [καταλαβη]{.greek-omitted} [καταλαβει]{.greek-added} [ρησσει]{.greek-omitted} [ρισσει]{.greek-added} αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο εκβαλωσιν και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [λεγει]{.greek-added} αυτω [λεγει]{.greek-omitted} ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς [αυτον]{.greek-omitted} [τον]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτισε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως [τουτο]{.greek-omitted} [τουτω]{.greek-added} γεγονεν αυτω ο δε ειπεν παιδιοθεν[9:21]{.aside}

και πολλακις αυτον και εις το πυρ εβαλεν και εις υδατα ινα [απολεση]{.greek-omitted} [απολεσει]{.greek-added} αυτον αλλ [ει]{.greek-omitted} [η]{.greek-added} τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη [απιστια]{.greek-omitted} [απιστεια]{.greek-added}[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι [επισυντρεχει]{.greek-omitted} [συντρεχει]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-abbr} το αλαλον και κωφον εγω σοι επιτασσω εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και [πολλα]{.greek-omitted} [πολα]{.greek-added} σπαραξαν αυτον [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας [αυτον]{.greek-omitted} της χειρος [αυτου]{.greek-added} ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα [αυτον]{.greek-omitted} [αυτω]{.greek-added} εις οικον οι μαθηται αυτου [επηρωτων]{.greek-omitted} [επηρωτουν]{.greek-added} αυτον κατ ιδιαν οτι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις [τουτο]{.greek-omitted} [τουτω]{.greek-added} το γενος εν ουδενι [εξερχεται]{.greek-added} [δυναται]{.greek-omitted} [εξελθειν]{.greek-omitted} ει μη εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν [εξελθοντες]{.greek-omitted} [εξελθοτες]{.greek-added} παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

εδιδασκεν γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [ανθρωπων]{.greek-abbr} και [αποκτενουσιν]{.greek-omitted} [αποκτενουσι]{.greek-added} αυτον και [αποκτανθεις]{.greek-omitted} τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον [επερωτησαι]{.greek-omitted} [επαιρωτισαι]{.greek-added}[9:32]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} εις [καπερναουμ]{.greek-omitted} [κκαπερναουμ]{.greek-added} και εν τη οικια γενομενος [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} αυτους τι εν τη οδω [προς]{.greek-omitted} [εαυτους]{.greek-omitted} διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν εν τη οδω τις [μειζων]{.greek-omitted} [μειζω]{.greek-added}[9:34]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο [εν]{.greek-omitted} [μεσω]{.greek-omitted} [εις]{.greek-added} [το]{.greek-added} [μεσον]{.greek-added} αυτων και εναγκαλισαμενος αυτο ειπ[ε]{.unclear}ν αυτοις[9:36]{.aside}

ος εαν εν των [τοιουτων]{.greek-omitted} παιδιων [τουτων]{.greek-added} δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ εμε δεχεται αλλα τον αποστειλαντα με[9:37]{.aside}

απεκριθη [δε]{.greek-omitted} αυτω ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} τινα [εν]{.greek-added} τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και [εκωλυσαμεν]{.greek-omitted} [εκολυσαμεν]{.greek-added} αυτον οτι ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και [δυνησεται]{.greek-omitted} [δυνησηται]{.greek-added} ταχυ [κακολογησαι]{.greek-omitted} [κακολογισαι]{.greek-added} με[9:39]{.aside}

ος γαρ ουκ εστιν καθ υμων υπερ υμων [εστιν]{.greek-omitted} [εστι]{.greek-added}[9:40]{.aside}

ος γαρ αν [ποτιση]{.greek-omitted} [ποτησει]{.greek-added} υμας ποτηριον υδατος εν ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη [απολεση]{.greek-omitted} [απολεσει]{.greek-added} τον μισθον αυτου[9:41]{.aside}

[και]{.greek-omitted} ος [γαρ]{.greek-added} [εαν]{.greek-omitted} [αν]{.greek-added} [σκανδαλιση]{.greek-omitted} [σκανδδαλησει]{.greek-added} ενα των μικρων [τουτων]{.greek-added} των [πιστευοντων]{.greek-omitted} [πιστευωντων]{.greek-added} εις εμε καλον εστιν αυτω μαλλον ει [περικειται]{.greek-omitted} [περικηται]{.greek-added} [αυτω]{.greek-added} [μυλος]{.greek-added} [λιθος]{.corr} [μυλ[ι]{.unclear}κος]{.corr} περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι εστιν κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκολιξ]{.greek-added} αυτων ου τελευτα και το πυρ [αυτων]{.greek-added} ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [σοι]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκολιξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε [εκβαλε]{.greek-omitted} [εκβαλον]{.greek-added} αυτον καλον σοι εστιν μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο [σκωληξ]{.greek-omitted} [σκολιξ]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια [αλι]{.corr} αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας [[εα]{.unclear}ν]{.greek-added} [αναλον]{.corr} γενηται εν τινι [αυτο]{.greek-omitted} [αυτω]{.greek-added} [αρτυσετε]{.greek-omitted} [αρτυσεται]{.greek-added} εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας δια του περαν του ιορδανου και συμπορευονται παλιν οχλοι προς αυτον και ως [ειωθει]{.greek-omitted} [ειωθη]{.greek-added} παλιν εδιδασκεν αυτους[10:1]{.aside}

και προσελθοντες φαρισαιοι [επηρωτησαν]{.greek-omitted} [επηρωτισαν]{.greek-added} αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο μωσης[10:3]{.aside}

οι δε ειπον μωσης επετρεψεν βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

[ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-omitted} και την [μητερα]{.greek-abbr} [αυτου]{.greek-added} και προσκολληθησεται [προς]{.greek-omitted} την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα μια σαρξ[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη [χωριζετω]{.greek-omitted} [χοριζετω]{.greek-added}[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου [περι]{.corr} [του]{.corr} [αυτου]{.corr} [επηρωτησαν]{.greek-omitted} [επηρωτισαν]{.greek-added} αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου και [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον ανδρα αυτης και [γαμηθη]{.greek-omitted} [γαμηθει]{.greek-added} [αλλω]{.greek-omitted} [αλλα]{.greek-added} μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος εαν μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [[η]{.unclear}υλογει]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον προσδραμων εις και γονυπετησας [αυτον]{.greek-omitted} επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη [φονευσης]{.greek-omitted} [φονευσεις]{.greek-added} μη κλεψης μη [ψευδομαρτυρησης]{.greek-omitted} [ψευδομαρτυρισεις]{.greek-added} μη [αποστερησης]{.greek-omitted} [αποστερησεις]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε αποκριθεις ειπεν αυτω διδασκαλε ταυτα παντα εφυλαξαμην εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω εν σοι υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και δευρο [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι χρημασιν [εισελθειν]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} [εισελθειν]{.greek-omitted}[10:24]{.aside}

[ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} [καμηλον]{.greek-omitted} [καμιλον]{.greek-added} δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος εισελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε [περισσως]{.greek-omitted} [περισσοτερως]{.greek-added} εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [τω]{.greek-added} [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο ο πετρος λεγειν [αυτω]{.greek-omitted} [τω]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} του ευαγγελιου[10:29]{.aside}

εαν μη λαβη [εκατονταπλασιονα]{.greek-omitted} [εκατονταπλασιωνα]{.greek-added} νυν εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [μητερας]{.greek-abbr} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και [ην]{.greek-omitted} [προαγων]{.greek-omitted} [αυτους]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εθαμβουντο]{.greek-omitted} [και]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} παραλαβων [παλιν]{.greek-omitted} τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και [παραδωσουσιν]{.greek-omitted} [παραδοσουσιν]{.greek-added} αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και [εμπαιξουσιν]{.greek-omitted} [εμπαιξουσι]{.greek-added} [αυτω]{.greek-omitted} και [μαστιγωσουσιν]{.greek-omitted} [μαστηγωσουσιν]{.greek-added} αυτον και εμπτυσουσιν αυτω και αποκτενουσιν αυτον και τη τριτη ημερα αναστησεται[10:34]{.aside}

και [προσπορευονται]{.greek-omitted} [προπορευονται]{.greek-added} αυτω ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οι υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν [αιτησωμεν]{.greek-omitted} [αιτησομεν]{.greek-added} [ποιησης]{.greek-omitted} [ποιησεις]{.greek-added} ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε [ποιησαι]{.greek-omitted} [ποιησω]{.greek-added} [με]{.greek-omitted} υμιν[10:36]{.aside}

οι δε ειπον αυτω δ[ος]{.unclear} ημιν ινα εις εκ δεξιων [σ]{.unclear}[ου]{.greek-supplied} και εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [[κα]{.greek-supplied}θησομεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω [και]{.greek-omitted} [η]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} γενεσθαι μεγας εν υμιν εσται υμων διακονος[10:43]{.aside}

και ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} [υμων]{.greek-omitted} [υμιν]{.greek-added} γενεσθαι πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα [διακονησαι]{.greek-omitted} [διακονισαι]{.greek-added} και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-omitted} ελεησον με[10:47]{.aside}

και επετιμων [αυτω]{.greek-omitted} [αυτον]{.greek-added} πολλοι ινα [σιωπηση]{.greek-omitted} [σιωπησει]{.greek-added} ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-abbr} ελεησον με[10:48]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} [φωνει]{.greek-omitted} [φωνι]{.greek-added} [σε]{.greek-omitted} [σαι]{.greek-added}[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς [τον]{.greek-omitted} [αυτον]{.greek-added} [ιησουν]{.greek-omitted}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος ειπεν αυτω ραββουνι ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου σεσωκεν σε και ευθεως ανεβλεψεν και [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-abbr} [εις]{.greek-omitted} [και]{.greek-added} βηθσφαγη και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην [ευρησετε]{.greek-omitted} [ευρησητε]{.greek-added} πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθηκε]{.greek-added} λυσαντες αυτον αγαγετε[11:2]{.aside}

και εαν τις υμιν ειπη τι ποιειτε τουτο ειπατε οτι ο κυριος αυτου χρειαν εχει και ευθεως [αυτον]{.greek-omitted} [αυτους]{.greek-added} αποστελλει [ωδε]{.greek-omitted}[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως ενετειλατο [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια [αυτων]{.greek-omitted} εστρωσαν εις την οδον αλλοι [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [στηβαδας]{.greek-added} εκοπτον εκ των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος [ο]{.greek-omitted} [ερχομενος]{.greek-omitted} εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και [εισηλθεν]{.greek-omitted} [εισελθων]{.greek-added} εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον [και]{.greek-omitted} περιβλεψαμενος παντα οψιας [ηδη]{.greek-omitted} [ηδει]{.greek-added} ουσης [της]{.greek-omitted} [ωρας]{.greek-omitted} εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον [εξελθοντων]{.greek-omitted} [εξελθωντων]{.greek-added} αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην μακροθεν εχουσαν φυλλα ηλθεν ει αρα ευρησει τι εν αυτη και ελθων επ [αυτην]{.greek-omitted} [αυτη]{.greek-added} ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον [φαγοι]{.greek-omitted} [φαγει]{.greek-added} και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added}[11:15]{.aside}

και ουκ ηφιεν ινα τις [διενεγκη]{.greek-omitted} [ενεγκη]{.greek-added} σκευος δια του ιερου[11:16]{.aside}

και εδιδασκεν λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν [υμεις]{.corr} [δε]{.corr} [εποιησατε]{.corr} [αυτον]{.corr} [σπηλαιον]{.corr} [ληστων]{.greek-omitted} [[λιστων]{.corr}]{.greek-added}[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο οχλος εξεπλησσετο επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε εγενετο εξεπορευετο εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι [ειδον]{.greek-omitted} [ιδων]{.greek-added} την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και [αναμνησθεις]{.greek-omitted} [αναμνισθεις]{.greek-added} ο πετρος λεγει αυτω ραββι ιδε η συκη ην κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την θαλασσαν και μη [διακριθη]{.greek-omitted} [διακριθει]{.greek-added} εν τη καρδια αυτου αλλα [πιστευση]{.greek-omitted} [πιστευσει]{.greek-added} οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23]{.aside}

δια τουτο λεγω υμιν παντα οσα αν προσευχομενοι [αιτησθε]{.greek-omitted} [αιτεισθε]{.greek-added} πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκετε]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} [αφη]{.greek-omitted} [αφει]{.greek-added} υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων [αιτειτε]{.greek-added} [και]{.greek-added} [δοθησεται]{.greek-added} [υμιν]{.greek-added} [ζητειτε]{.greek-added} [και]{.greek-added} [ευρησητε]{.greek-added} [κρουετε]{.greek-added} [και]{.greek-added} [ανοιγησηται]{.greek-added} [υμιν]{.greek-added} [πας]{.greek-added} [γαρ]{.greek-added} [ο]{.greek-added} [αιτων]{.greek-added} [λαμβανη]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [ζητων]{.greek-added} [ευρησκει]{.greek-added} [και]{.greek-added} [τω]{.greek-added} [κρουοντι]{.greek-added} [ανοιγησεται]{.greek-added}[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα [ποιης]{.greek-omitted} [ποιεις]{.greek-added}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω [καγω]{.greek-added} υμας [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} [εις]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ ουρανου ερει δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-abbr} εφοβουντο τον λαον απαντες γαρ ειχον τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι [οντως]{.greek-omitted} [οντος]{.greek-added} προφητης ην[11:32]{.aside}

και [ειπον]{.greek-added} [αποκριθεντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν [ανθρωπος]{.greek-abbr} και περιεθηκεν [αυτω]{.greek-added} φραγμον και [ωρυξεν]{.greek-omitted} [ορυξεν]{.greek-added} υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων [λαβη]{.greek-omitted} [λαβει]{.greek-added} απο του [καρπου]{.greek-omitted} [του]{.greek-omitted} αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν απεστειλεν προς αυτους αλλον δουλον κακεινον [λιθοβολησαντες]{.greek-omitted} [λιθοβολισαντες]{.greek-added} εκεφαλαιωσαν και απεστειλαν [ητιμωμενον]{.greek-omitted} [ητιμαμενον]{.greek-added}[12:4]{.aside}

και παλιν αλλον απεστειλεν κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα υιον εχων αγαπητον αυτου απεστειλεν και αυτον προς αυτους εσχατον λεγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι [ουτος]{.greek-omitted} [ουτως]{.greek-added} [εστιν]{.greek-omitted} [εσται]{.greek-added} ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο [κυριος]{.greek-abbr} του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες [ουτος]{.greek-omitted} [ουτως]{.greek-added} εγενηθη εις κεφαλην [γωνιας]{.greek-omitted} [γονιας]{.greek-added}[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον [κρατησαι]{.greek-omitted} [κρατισαι]{.greek-added} και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς αυτον τινας των φαρισαιων και των ηρωδιανων ινα αυτον αγρευσωσιν [εν]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και ου [μελει]{.greek-omitted} [μελη]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [κηνσον]{.greek-omitted} [κινσον]{.greek-added} καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε [ειδως]{.greek-omitted} [ιδων]{.greek-added} αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε φερετε μοι [δηναριον]{.greek-omitted} [διναριον]{.greek-added} ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε [ουν]{.greek-added} τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται [οι]{.greek-added} σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και [επηρωτησαν]{.greek-omitted} [επηρωτισαν]{.greek-added} αυτον λεγοντες[12:18]{.aside}

διδασκαλε μωσης εγραψεν ημιν οτι εαν τινος αδελφος αποθανη και καταλιπη γυναικα και τεκνα μη [αφη]{.greek-omitted} [αφει]{.greek-added} ινα [λαβη]{.greek-omitted} [λαβει]{.greek-added} ο αδελφος αυτου την γυναικα αυτου και [εξαναστηση]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [ουν]{.greek-added} αδελφοι ησαν και ο πρωτος ελαβεν γυναικα και αποθνησκων ουκ αφηκεν σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και απεθανεν και ουδε αυτος αφηκεν σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην [και]{.greek-added} οι επτα και ουκ αφηκαν σπερμα εσχατη παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη [ουν]{.greek-added} αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη [ειδοτες]{.greek-omitted} [ιδοτες]{.greek-added} τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [γαμησκονται]{.greek-added} αλλ εισιν ως αγγελοι οι εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω μωσεως επι [του]{.greek-omitted} [της]{.greek-added} βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ [και]{.greek-omitted} ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ εστιν ο [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-abbr} ζωντων υμεις ουν [πολυ]{.greek-omitted} [πολλα]{.greek-added} πλανασθε[12:27]{.aside}

και προσελθων εις των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ακουσας αυτων [συζητουντων]{.greek-omitted} [συνζητουντων]{.greek-added} [ειδως]{.greek-omitted} [αυτον]{.greek-added} [ιδων]{.greek-added} οτι καλως [αυτοις]{.greek-omitted} απεκριθη [επηρωτησεν]{.greek-omitted} [επηρωτισεν]{.greek-added} αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη παντων εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} [απεκριθη]{.greek-omitted} [ειπεν]{.greek-added} αυτω οτι πρωτη παντων [των]{.greek-omitted} εντολων ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις εστιν[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως σεαυτον [μειζων]{.greek-omitted} [μειζω]{.greek-added} τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης της ψυχης και εξ ολης της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [παντων]{.greek-added} εστιν [παντων]{.greek-omitted} [των]{.greek-omitted} ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον [επερωτησαι]{.greek-omitted} [επαιρωτισαι]{.greek-added}[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ειπεν]{.greek-added} διδασκων εν τω ιερω π[ω]{.unclear}ς λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος εστιν [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} [τω]{.greek-added} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [ο]{.greek-added} [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-omitted} αυτου εστιν και [ο]{.corr} πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εν τη διδαχη αυτου βλεπετε απο των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} των [θελοντων]{.greek-omitted} [θελωντων]{.greek-added} εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και πρωτοκλισιας εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι [ληψονται]{.greek-omitted} [λειψονται]{.greek-added} περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [καθησας]{.greek-added} ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} τους μαθητας αυτου [ειπεν]{.greek-added} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλλωντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισσευματος]{.greek-added} [αυτοις]{.greek-omitted} [αυτων]{.greek-added} εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις [εκ]{.greek-added} των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και ο [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη [ωδε]{.greek-added} λιθος επι λιθω ος ου [μη]{.corr} καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη παντα [ταυτα]{.greek-omitted} συντελεισθαι[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις [αυτω]{.greek-added} [αυτοις]{.corr} ηρξατο λεγειν βλεπετε μη [τις]{.greek-omitted} [υμας]{.greek-omitted} [πλανηση]{.greek-omitted} [πλανηθητε]{.greek-added}[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους [και]{.greek-added} [ακαταστασιας]{.greek-added} και ακοας πολεμων μη θροεισθε δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται [γαρ]{.greek-omitted} εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι αρχαι ωδινων ταυτα[13:8]{.aside}

βλεπετε δε υμεις εαυτους παραδωσουσιν γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη [προμεριμνατε]{.greek-omitted} [μεριμνατε]{.greek-added} τι λαλησητε μηδε μελετατε αλλ ο εαν [δοθη]{.greek-omitted} [δοθει]{.greek-added} υμιν εν εκεινη τη ωρα [τουτο]{.greek-omitted} [τουτω]{.greek-added} [λαλειτε]{.greek-omitted} [λαλειται]{.greek-added} ου γαρ [εστε]{.greek-omitted} [εσται]{.greek-added} υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

[παραδωσει]{.greek-omitted} [παραδοση]{.greek-added} δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μ[ι]{.unclear}σουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε [η]{.greek-added} ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει[―]{.gap} [[δει]{.corr}]{.greek-added} ο αναγινωσκων [νοειτω]{.greek-omitted} [νοητω]{.greek-added} τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι τι εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη [γενηται]{.greek-omitted} [γενοιται]{.greek-added} η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις [οια]{.greek-omitted} [οιαι]{.greek-added} ου [γεγονεν]{.greek-omitted} [γεγοναν]{.greek-added} [τοιαυτη]{.greek-omitted} [τοιαυται]{.greek-added} απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη [γενηται]{.greek-omitted} [γεν[ον]{.unclear}ται]{.greek-added}[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολωβωσε]{.greek-added} τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δοσουσι]{.greek-added} σημεια και τερατα προς το [αποπλαναν]{.greek-omitted} [αποπλανειν]{.greek-added} ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν [παντα]{.greek-omitted} [απαντα]{.greek-added}[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου [δωσει]{.greek-omitted} [δοσει]{.greek-added} το φεγγος αυτης[13:24]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι [δυναμεις]{.greek-omitted} [αι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ [ακρου]{.greek-omitted} [ακρων]{.greek-added} γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν αυτης ηδη ο κλαδος απαλος γενηται και εκφυη τα φυλλα γινωσκετε οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν ταυτα [ιδητε]{.greek-omitted} [ηδειτε]{.greek-added} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

[ο]{.greek-added} ο [ουρανος]{.greek-abbr} και η γη παρελευσεται οι δε λογοι μου ου μ[η]{.unclear} παρελθωσιν[13:31]{.aside}

περι δε της ημερας εκεινης η ωρας [εκεινης]{.greek-added} ουδεις οιδεν ουδε οι αγγελοι οι εν [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} [αποδημος]{.greek-omitted} [αποδημως]{.greek-added} αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω [θυρωρω]{.greek-omitted} [θυρορω]{.greek-added} ενετειλατο ινα [γρηγορη]{.greek-omitted} [γρηγορει]{.greek-added}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται [η]{.greek-added} οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη [υμας]{.greek-omitted} [ημας]{.greek-added} καθευδοντας[13:36]{.aside}

α δε [λεγω]{.greek-added} υμιν [λεγω]{.greek-omitted} πασιν λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον [εν]{.greek-omitted} δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν τη οικια σιμωνος του λεπρου [κατακειμενου]{.greek-omitted} [καθημενου]{.greek-added} αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης [πολυτελους]{.greek-omitted} [πολυτιμου]{.greek-added} και συντριψασα [το]{.greek-omitted} [τον]{.greek-added} αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι τ[οις]{.unclear} πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους [παρεχετε]{.greek-omitted} [παρεχεται]{.greek-added} καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν [θελητε]{.greek-omitted} [θελετε]{.greek-added} δυνασθε αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} [μυρισαι]{.greek-omitted} [μυρισε]{.greek-added} μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιο[υ]{.unclear}δας ο ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν [[εχαρισαν]{.corr}]{.greek-added} και επηγγειλαντο αυτω αργυριον δουναι και εζητει πως ευκαιρως αυτον [αυτον]{.greek-added} παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις [ετοιμασωμεν]{.greek-added} απελθοντες [ετοιμασωμεν]{.greek-omitted} ινα [φαγης]{.greek-omitted} [φαγεις]{.greek-added} το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-abbr} κεραμιον υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου εαν εισελθη ειπατε τω [οικοδεσποτη]{.greek-omitted} [οικωδεσποτη]{.greek-added} οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και [αυτος]{.greek-omitted} [ουτος]{.greek-added} υμιν δειξει ανωγεον [μεγα]{.greek-omitted} εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω [ειμι]{.greek-added} και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον [και]{.greek-added} ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε [φαγετε]{.greek-omitted} τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων το ποτηριον [ευχαριστησας]{.greek-omitted} [ευχαριστεισας]{.greek-added} εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου [το]{.greek-omitted} της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} οτι παντες σκανδαλισθησεσθε [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} οτι γεγραπται παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} [διασκορπισθησονται]{.greek-added} τα προβατα[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω [ο]{.greek-omitted} [ιησους]{.greek-omitted} αμην λεγω σοι οτι συ σημερον εν τη νυκτι ταυτη πριν [η]{.unclear} δις αλεκτορα φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} [απαρνηση]{.greek-omitted} [απαρνησει]{.greek-added} με[14:30]{.aside}

ο δε [πετρος]{.greek-added} εκπερισσου ελεγεν μαλλον εαν με δεη συναποθανειν σοι ου μη σε απαρνησωμαι ωσαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα γεθσημανη και λεγει τοις μαθηταις αυτου [καθισατε]{.greek-omitted} [καθησατε]{.greek-added} ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και ιακωβον και ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε [μετ]{.greek-added} [εμου]{.greek-added}[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και [προσ[ε]{.unclear}υχεται]{.greek-added} [προσηυχετο]{.greek-omitted} [[προσηυχεται]{.corr}]{.greek-added} ινα ει δυνατον εστιν παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε το ποτηριον απ εμου τουτο αλλ [ο]{.greek-added} [[αλλ]{.corr}]{.greek-added} [ου]{.corr} τι εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [ο]{.greek-added} [[αλλ]{.corr}]{.greek-added} [[οι]{.corr}]{.greek-added} τι συ[14:36]{.aside}

και ερχεται και [ευρισκει]{.greek-omitted} [ευρισκη]{.greek-added} αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας μιαν ωραν [γρηγορησαι]{.greek-omitted} [γρηγορεισαι]{.greek-added}[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [βεβαριμενοι]{.greek-added} και ουκ ηδεισαν τι αυτω [αποκριθωσιν]{.greek-omitted} [αποκριθωσι]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα [ιδου]{.greek-omitted} παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις τας χειρας των αμαρτωλων[14:41]{.aside}

[εγειρεσθε]{.greek-omitted} [εγειρεσθαι]{.greek-added} αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας εις [ων]{.greek-omitted} των [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

[δεδωκει]{.greek-omitted} [δεδοκει]{.greek-added} δε ο παραδιδους αυτον [συσσημον]{.greek-omitted} [συσημον]{.greek-added} αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και [απαγαγετε]{.greek-omitted} [απαγετε]{.greek-added} [αυτον]{.greek-added} ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων αυτω λεγει αυτω [χαιρε]{.greek-added} [ραββι]{.corr} [ραββι]{.greek-omitted} [ραββει]{.greek-added} και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ αυτον τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος [την]{.greek-omitted} μαχαιραν [επαισεν]{.greek-omitted} [επεσε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν [ημην]{.greek-omitted} [ημιν]{.greek-added} προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα [πληρωθωσιν]{.greek-omitted} [αι]{.greek-omitted} [γραφαι]{.greek-omitted} [πληρωθη]{.greek-added} [η]{.greek-added} [γραφη]{.greek-added}[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51]{.aside}

ο δε καταλιπων την σινδονα [εφυγεν]{.greek-added} γυμνος [εφυγεν]{.greek-omitted} απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα και συνερχονται αυτω παντες οι αρχιερεις και οι πρεσβυτεροι και οι γραμματεις[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω [εως]{.greek-omitted} [εσω]{.greek-omitted} εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και [θερμαινομενος]{.greek-omitted} [θερμενομενος]{.greek-added} προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ [ευρισκον]{.greek-omitted} [ηυρισκον]{.greek-added}[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον [και]{.corr} [δια]{.corr} [τριων]{.corr} [ημερων]{.corr} [αλλον]{.corr} [αχειροποιητον]{.corr} [και]{.greek-added} οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας [ο]{.corr} αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επερωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και [ουδε]{.greek-added} [ουδεν]{.corr} απεκρινατο παλιν ο αρχιερευς επηρωτα αυτον [λεγων]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του [[θεου]{.greek-abbr}]{.greek-added} [του]{.greek-added} ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτω]{.greek-added} εγω ειμι και [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας [αυτου]{.greek-added} τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν [αυτω]{.greek-omitted} [και]{.greek-omitted} [περικαλυπτειν]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον και οι υπηρεται ραπισμασιν αυτον [ελαβον]{.greek-added} [εβαλλον]{.greek-omitted} [[εβαλον]{.corr}]{.greek-added}[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον [θερμαινομενον]{.greek-omitted} [θερμενομενον]{.greek-added} εμβλεψασα αυτω λεγει και συ μετα του [ναζαρηνου]{.greek-omitted} [ναζωρινου]{.greek-added} [ιησου]{.greek-abbr} ησθα[14:67]{.aside}

ο δε ηρνησατο λεγων ουκ οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} επισταμαι τι συ λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστηκωσιν]{.greek-added} οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν [ηρνειτο]{.greek-omitted} [ηρνησατο]{.greek-added} και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και ανεμνησθη ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι [πριν]{.greek-omitted} [τον]{.greek-added} [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι δις απαρνηση [με]{.greek-omitted} [μια]{.greek-added} [τρις]{.greek-omitted} [τρεις]{.greek-added} και επιβαλων [εκλαιεν]{.greek-omitted} [εκλεε]{.greek-added}[14:72]{.aside}

### Chapter 15

και ευθεως επι [το]{.greek-omitted} [τω]{.greek-added} πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και [κα]{.greek-added} [κατηγορουν]{.greek-omitted} [τηγορουν]{.greek-added} αυτου οι αρχιερεις πολλα[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6]{.aside}

ην δε ο λεγομενος βαραββας μετα των [συστασιαστων]{.greek-omitted} [συνστασιαστων]{.greek-added} δεδεμενος [οιτινες]{.greek-omitted} [οιτηνες]{.greek-added} εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει [εποιε]{.greek-added} [εποιει]{.corr} αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [εγινωσκε]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδωκεισαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε [τον]{.greek-added} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [[σταυρωθητω]{.greek-abbr}]{.greek-added} [σταυρωσον]{.greek-omitted} [αυτον]{.greek-omitted}[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε περισσοτερως εκραξαν [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγγελωσας]{.greek-added} [αυτον]{.greek-added} ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο εστιν πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και περιτιθεασιν αυτω πλεξαντες [ακανθινον]{.greek-omitted} [ακανθηνον]{.greek-added} στεφανον[15:17]{.aside}

και ηρξαντο [ασπαζεσθαι]{.greek-omitted} [ασπαζεσθε]{.greek-added} αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε [ενεπαιξαν]{.greek-omitted} [ενεπεξαν]{.greek-added} [αυτον]{.greek-added} [εξεδυσαν]{.greek-added} αυτω [εξεδυσαν]{.greek-omitted} [αυτον]{.greek-omitted} την πορφυραν και ενεδυσαν αυτον τα ιματια τα ιδια και εξαγουσιν αυτον ινα [σταυρωσωσιν]{.greek-abbr} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα [κυρηναιον]{.greek-omitted} [κυριναιον]{.greek-added} ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι γολγοθα [τοπον]{.greek-omitted} [τοπων]{.greek-added} ο εστιν μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν [αυτω]{.greek-omitted} [αυτον]{.greek-added} πιειν [εσμυρνισμενον]{.greek-omitted} [εσμυρνησμενον]{.greek-added} οινον ο δε ουκ ελαβεν[15:23]{.aside}

και [σταυρωσαντες]{.greek-abbr} αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα [τριτη]{.greek-omitted} [[γ]{.greek-abbr}]{.greek-added} και [εσταυρωσαν]{.greek-abbr} [αυτον]{.greek-omitted} [αυτω]{.greek-added}[15:25]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-abbr} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες [προς]{.greek-omitted} [αλληλους]{.greek-omitted} [μετ]{.greek-added} [αλληλων]{.greek-added} μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

[ο]{.greek-omitted} [χριστος]{.greek-omitted} ο βασιλευς του [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν αυτω και οι [συνεσταυρωμενοι]{.greek-abbr} [αυτω]{.greek-omitted} [ωνειδιζον]{.greek-omitted} [ωνιδιζον]{.greek-added} αυτον[15:32]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη ωρα τη ενατη εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι λιμα [σαβαχθανι]{.greek-omitted} [σαβαχθαν[η]{.unclear}]{.greek-added} ο εστιν μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των [παρεστηκοτων]{.greek-omitted} [παρεστικοτων]{.greek-added} ακουσαντες ελεγον ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και [γεμισας]{.greek-omitted} [γεμησας]{.greek-added} [σπογγον]{.greek-omitted} οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει [ερχεται]{.greek-omitted} [ερχετε]{.greek-added} ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} [αφεις]{.greek-omitted} [αφης]{.greek-added} φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο [απο]{.greek-omitted} [απ]{.greek-added} ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο [παρεστηκως]{.greek-omitted} [παρεστικως]{.greek-added} εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες [απο]{.greek-omitted} μακροθεν θεωρουσαι εν αις ην και μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια η του ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

[αι]{.greek-omitted} και οτε ην εν τη γαλιλαια [ηκολουθουν]{.greek-omitted} [ηκολουθησαν]{.greek-added} αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο εστιν προσαββατον[15:42]{.aside}

ηλθεν ιωσηφ ο απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη τεθνηκεν και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον ενειλησεν τη σινδονι και κατεθηκεν αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [ιωση]{.greek-omitted} [[η]{.unclear}ωση]{.greek-added} εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-added} [του]{.greek-added} ιακωβου και σαλωμη [ηγορασαν]{.greek-omitted} [ηγωρασαν]{.greek-added} αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον [ειδον]{.greek-omitted} [ιδον]{.greek-added} νεανισκον καθημενον εν τοις δεξιοις [περιβεβλημενον]{.greek-omitted} [περιβεβλημενην]{.greek-added} στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβησθε]{.greek-added} [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταυρωμενον]{.greek-omitted} [[εστρωμενον]{.greek-abbr}]{.greek-added} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου ειχεν δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης εκβεβληκει [επτα]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} δαιμονια[16:9]{.aside}

εκεινη [πορευθεισα]{.greek-omitted} [πορευθησα]{.greek-added} απηγγειλεν τοις μετ αυτου γενομενοις πενθουσιν και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης [ηπιστησαν]{.greek-omitted} [ειπιστισαν]{.greek-added}[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον [ανακειμενοις]{.greek-omitted} [ανακει]{.greek-added} [μενοις]{.greek-added} αυτοις τοις [ενδεκα]{.greek-omitted} [[ια]{.greek-abbr}]{.greek-added} εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδησεν]{.greek-added} την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και [σκηροκαρδιαν]{.greek-added} [σκληροκαρδιαν]{.corr} οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη [κτισει]{.greek-omitted} [κτιση]{.greek-added}[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε [απιστησας]{.greek-omitted} [απιστισας]{.greek-added} κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια εκβαλουσιν γλωσσαις λαλησουσιν καιναις[16:17]{.aside}

οφεις αρουσιν καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι [αρρωστους]{.greek-omitted} [αρωστους]{.greek-added} χειρας επιθησουσιν και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

