---
title: "Collation of Byz^RP^ vs 31604 (1604)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1604 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31604).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1604                                   	| λογος                              	|
| 1604 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1604 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1604               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1604                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1604 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1604                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

βιβλος γενεσεως [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου [δαυιδ]{.greek-abbr} υιου αβρααμ[1:1]{.aside}

αβρααμ [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ ισαακ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιουδαν και τους [αδελφους]{.greek-omitted} [αδελ]{.greek-added} [φους]{.greek-added} αυτου[1:2]{.aside}

ιουδας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον φαρες και τον ζαρα εκ της θαμαρ φαρες δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εσρωμ εσρωμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αραμ[1:3]{.aside}

αραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμιναδαβ αμιναδαβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ναασσων ναασσων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλμων[1:4]{.aside}

σαλμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον βοοζ εκ της ραχαβ βοοζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ωβηδ εκ της ρουθ ωβηδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεσσαι[1:5]{.aside}

ιεσσαι δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [δαυιδ]{.greek-abbr} τον βασιλεα [δαυιδ]{.greek-abbr} δε ο βασιλευς [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σολομωνα εκ της του ουριου[1:6]{.aside}

σολομων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ασα[1:7]{.aside}

ασα δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσαφατ ιωσαφατ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον οζιαν[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωαθαμ ιωαθαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχαζ αχαζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εζεκιαν[1:9]{.aside}

εζεκιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον μανασση μανασσης δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμων αμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-added} [ιωακειμ]{.greek-added} [ιωακειμ]{.greek-added} [δε]{.greek-added} [εγεννησε]{.greek-added} τον ιεχονιαν και τους αδελφους αυτου επι της μετοικεσιας βαβυλωνος[1:11]{.aside}

μετα δε την μετοικεσιαν βαβυλωνος ιεχονιας [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλαθιηλ σαλαθιηλ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβιουδ αβιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιακειμ ελιακειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [αχειμ]{.greek-omitted} [αχιμ]{.greek-added} [αχειμ]{.greek-omitted} [αχιμ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελεαζαρ ελεαζαρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-abbr} ο λεγομενος [[χριστος]{.greek-abbr}]{.corr}[1:16]{.aside}

πασαι ουν αι γενεαι απο [αβρααμ]{.greek-omitted} [αβραμ]{.greek-added} εως [δαυιδ]{.greek-abbr} γενεαι δεκατεσσαρες και απο [δαυιδ]{.greek-omitted} [[δαδ]{.corr}]{.greek-added} [εως]{.corr} της μετοικεσιας βαβυλωνος γενεαι δεκατεσσαρες και απο της μετοικεσιας βαβυλωνος εως του [χριστου]{.greek-abbr} γενεαι δεκατεσσαρες[1:17]{.aside}

του δε [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} η [γεννη[―]{.gap}]{.greek-added} [γεννησις]{.corr} ουτως ην [μνηστευθεισης]{.greek-omitted} [μνηστευθησης]{.greek-added} γαρ της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν η συνελθειν αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

ιωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων αυτην παραδειγματισαι εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

ταυτα δε αυτου [ενθυμηθεντος]{.greek-omitted} [ενθυμιθεντος]{.greek-added} ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ εφανη αυτω λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη [φοβηθης]{.greek-omitted} [φοβηθεις]{.greek-added} παραλαβειν [μαριαμ]{.greek-omitted} [μαριαν]{.greek-added} την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} εστιν αγιου[1:20]{.aside}

τεξεται δε υιον και [καλεσεις]{.greek-omitted} [καλεσης]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο [του]{.greek-omitted} [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται υιον και [καλεσουσιν]{.greek-omitted} [καλεσουσι]{.greek-added} το ονομα αυτου εμμανουηλ ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

διεγερθεις δε ο ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω [ο]{.greek-omitted} αγγελος [κυριου]{.greek-abbr} και [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} [τον]{.greek-omitted} [το]{.greek-added} υιον αυτης τον πρωτοτοκον και [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

του δε [ιησου]{.greek-abbr} γεννηθεντος [εν]{.greek-omitted} [απο]{.greek-added} [βηθλεεμ]{.greek-omitted} [βιθλεεμ]{.greek-added} της ιουδαιας εν ημεραις ηρωδου του βασιλεως ιδου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

λεγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι αυτω[2:2]{.aside}

ακουσας δε ηρωδης ο βασιλευς εταραχθη και πασα ιεροσολυμα μετ αυτου[2:3]{.aside}

και συναγαγων παντας τους αρχιερεις και [τους]{.greek-added} γραμματεις του λαου επυνθανετο παρ αυτων που ο [χριστος]{.greek-abbr} γενναται[2:4]{.aside}

οι δε ειπον αυτω εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου [λεγοντος]{.greek-added}[2:5]{.aside}

και συ βηθλεεμ γη ιουδα [ουδαμως]{.greek-omitted} [ελαχιστη]{.greek-omitted} [ει]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ηγεμοσιν]{.greek-omitted} [ιουδα]{.greek-omitted} εκ σου γαρ εξελευσεται [ηγουμενος]{.greek-omitted} [ηγου]{.greek-added} [μενος]{.greek-added} οστις ποιμανει τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ ειπεν πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ ον ειδον εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα εχαρησαν χαραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες εις την οικιαν ειδον το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου και [πεσοντες]{.greek-omitted} [πεσοντας]{.greek-added} προσεκυνησαν αυτω και ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω δωρα χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδου αγγελος [κυριου]{.greek-abbr} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του [απο]{.greek-added} [απολεσαι]{.greek-omitted} [λεσαι]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added}[2:13]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον υιον μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι [ενεπαιχθη]{.greek-omitted} [ενεπεχθη]{.greek-added} υπο των μαγων εθυμωθη λιαν και αποστειλας [ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} παντας τους παιδας τους εν [βηθλεεμ]{.greek-omitted} [βιθλεεμ]{.greek-added} και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις οριοις αυτης απο διετους και κατωτερω κατα τον χρονον ον [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρα των μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν υπο ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρακληθηναι οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added}[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ [φαινεται]{.greek-omitted} [φενεται]{.greek-added} τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων [εγερθεις]{.greek-omitted} [αναστας]{.greek-added} παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και πορευου εις γην [ισραηλ]{.greek-abbr} [τεθνηκασιν]{.greek-omitted} [τεθνηκασι]{.greek-added} γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει επι της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα [μερη]{.greek-omitted} [μερι]{.greek-added} της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν εις πολιν λεγομενην ναζαρετ οπως πληρωθη το ρηθεν δια των προφητων οτι ναζωραιος κληθησεται[2:23]{.aside}

### Chapter 3

εν [δε]{.greek-omitted} ταις ημεραις εκειναις παραγινεται [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

και λεγων [μετανοειτε]{.greek-omitted} [μετανοειται]{.greek-added} ηγγικεν [γαρ]{.corr} η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

ουτος γαρ εστιν ο [ρηθεις]{.greek-omitted} [ριθεις]{.greek-added} υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το ενδυμα [αυτου]{.greek-omitted} απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον [εις]{.greek-added} ιεροσολυμα και πασα [η]{.greek-omitted} ιουδαια και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο εν τω ιορδανη [ποταμω]{.greek-added} υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισμα αυτου ειπεν αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν [α]{.greek-added} [απο]{.greek-omitted} [πο]{.greek-added} της [μελλουσης]{.greek-omitted} [μελουσης]{.greek-added} οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν [εν]{.greek-omitted} [εαυτοις]{.greek-omitted} [πατερα]{.greek-abbr} [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} τον αβρααμ λεγω γαρ υμιν οτι [δυναται]{.greek-omitted} [δυνατε]{.greek-added} ο [θεος]{.greek-abbr} εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[3:10]{.aside}

εγω μεν βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω [και]{.greek-added} [πυρι]{.greek-added}[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον [αυτου]{.greek-omitted} εις την αποθηκην [αυτου]{.greek-added} το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην προς τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [διεκωλυεν]{.greek-omitted} [διεκολυεν]{.greek-added} αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν προς αυτον αφες αρτι ουτως γαρ [πρεπον]{.greek-omitted} [πρεπων]{.greek-added} εστιν ημιν πληρωσαι πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και βαπτισθεις ο [ιησους]{.greek-abbr} ανεβη ευθυς απο του υδατος και ιδου ανεωχθησαν [αυτω]{.greek-omitted} [αυ]{.greek-added} [τω]{.greek-added} οι [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ειδον]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} καταβαινον ωσει περιστεραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο υιος μου ο [αγαπητος]{.greek-omitted} [αγαπιτος]{.greek-added} εν ω ευδοκησα[3:17]{.aside}

### Chapter 4

τοτε [ανηχθη]{.greek-added} ο [ιησους]{.greek-abbr} [ανηχθη]{.greek-omitted} εις την ερημον υπο του [πνευματος]{.greek-abbr} πειρασθηναι υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας τεσσαρακοντα και νυκτας τεσσαρακοντα υστερον [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[4:2]{.aside}

και προσελθων αυτω ο πειραζων ειπεν ει υιος ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι γενωνται[4:3]{.aside}

ο δε αποκριθεις ειπεν γεγραπται ουκ επ αρτω μονω ζησεται [ο]{.greek-added} [ανθρωπος]{.greek-abbr} αλλ [επι]{.greek-omitted} [εν]{.greek-added} παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και [ιστησιν]{.greek-omitted} [εστησεν]{.greek-added} αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει υιος ει του [θεου]{.greek-abbr} βαλε σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} παλιν γεγραπται ουκ εκπειρασεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν παραλαμβανει αυτον ο διαβολος εις ορος [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα γεγραπται γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου προσκυνησεις και αυτω μονω λατρευσεις[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε [ο]{.greek-omitted} [ιησους]{.greek-omitted} οτι [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [παρεδοθη]{.greek-omitted} [παρεδωθη]{.greek-added} ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την ναζαρετ ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και νεφθαλειμ[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη νεφθαλειμ οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει ειδεν φως μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} κηρυσσειν και λεγειν μετανοειτε ηγγικεν [γαρ]{.greek-omitted} η βασιλεια των [ουρανων]{.greek-abbr}[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν δυο αδελφους σιμωνα τον [λεγομενον]{.greek-omitted} [καλουμενον]{.greek-added} πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και [ποιησω]{.greek-omitted} [ποιεισω]{.greek-added} υμας αλιεις [ανθρωπων]{.greek-abbr} [γενεσθαι]{.greek-added}[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν [ολιγον]{.greek-added} ειδεν αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας τα δικτυα αυτων και εκαλεσεν αυτους[4:21]{.aside}

οι δε ευθεως αφεντες το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν ολην την γαλιλαιαν ο [ιησους]{.greek-abbr} διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και απηλθεν η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως [εχοντας]{.greek-omitted} [εχωντας]{.greek-added} ποικιλαις νοσοις και βασανοις συνεχομενους και [δαιμονιζομενους]{.greek-omitted} [και]{.greek-omitted} [σεληνιαζομενους]{.greek-omitted} [και]{.greek-omitted} παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και [καθισαντος]{.greek-omitted} [καθησαντος]{.greek-added} αυτου προσηλθον αυτω οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους λεγων[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν η βασιλεια των ουρανων[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι [παρακληθησονται]{.greek-omitted} [παρακληθησωνται]{.greek-added}[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομισουσι]{.greek-added} [την]{.greek-omitted} γην[5:5]{.aside}

μακαριοι οι [πεινωντες]{.greek-omitted} [πινωντες]{.greek-added} και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

μακαριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} δικαιοσυνης οτι αυτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[5:10]{.aside}

μακαριοι [εσται]{.greek-added} [εστε]{.corr} οταν ονειδισωσιν υμας και [διωξωσιν]{.greek-omitted} [διωξωσι]{.greek-added} και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις [ουρανοις]{.greek-abbr} ουτως γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το αλας της γης εαν δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και τιθεασιν αυτον υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει πασιν τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων [εμπροσθεν]{.greek-omitted} [εμπροσθε]{.greek-added} των [ανθρωπων]{.greek-abbr} οπως [ιδωσιν]{.greek-omitted} [ειδωσιν]{.greek-added} υμων τα καλα εργα και [δοξασωσιν]{.greek-omitted} [δοξασουσι]{.greek-added} τον [πατερα]{.greek-abbr} υμων τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον [καλυσαι]{.greek-added} [καταλυσαι]{.corr} αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο [ουρανος]{.greek-abbr} και η γη ιωτα εν η μια κεραια ου μη παρελθη απο του νομου εως [αν]{.greek-omitted} παντα [γενηται]{.greek-omitted} [γενειται]{.greek-added}[5:18]{.aside}

[ο]{.unclear}ς εαν ουν λυση μιαν των εντολων τουτ[ω]{.unclear}ν των ελαχιστων και διδαξη ουτως τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [βασιλεια]{.greek-omitted} [βασιλειαν]{.greek-added} των [ουρανων]{.greek-abbr} ος δ αν ποιηση και διδαξη [ουτος]{.greek-omitted} [ουτως]{.greek-added} μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση η δικαιοσυνη υμων πλειον των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και φαρισαιων ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν [φονευση]{.greek-omitted} [φονευσει]{.greek-added} ενοχος εσται τη κρισει[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν ειπη τω αδελφω αυτου ρακα ενοχος εσται τω συνεδριω ος δ αν ειπη μωρε ενοχος εσται εις την γεενναν του πυρος[5:22]{.aside}

εαν ουν [προσφερης]{.greek-omitted} [προσφερεις]{.greek-added} το δωρον σου επι το θυσιαστηριον και εκει μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων [τω]{.greek-omitted} [το]{.greek-added} αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην βληθηση[5:25]{.aside}

αμην λεγω σοι [οτι]{.greek-added} ου μη εξελθης εκειθεν εως αν αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα προς το επιθυμησαι αυτην ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιος σκανδαλιζει σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

και ει η δεξια σου χειρ σκανδαλιζει σε εκκοψον αυτην και βαλε απο σου συμφερει γαρ σοι ινα [αποληται]{.greek-omitted} [απολειται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:30]{.aside}

ερρεθη δε οτι ος αν απολυση την [γυναικα]{.greek-omitted} [γυναι]{.greek-added} [κα]{.greek-added} αυτου δοτω αυτη [βιβλιον]{.greek-added} [αποστασιον]{.greek-omitted} [αποστασιου]{.greek-added}[5:31]{.aside}

εγω δε λεγω υμιν οτι [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} [πας]{.greek-added} [ο]{.greek-added} [απολυων]{.greek-added} την γυναικα αυτου παρεκτος λογου πορνειας ποιει αυτην μοιχασθαι και ος εαν απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε [τω]{.greek-omitted} [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη [ομοσαι]{.greek-omitted} [ομωσαι]{.greek-added} ολως μητε εν τω [ουρανω]{.greek-abbr} οτι θρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον [εστιν]{.greek-omitted} [εστη]{.greek-added} των ποδων αυτου μητε εις ιεροσολυμα οτι πολις [εστιν]{.greek-omitted} [εστι]{.greek-added} του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου ομοσης οτι ου δυνασαι μιαν [τριχα]{.greek-omitted} [τριχαν]{.greek-added} λευκην η [μελαιναν]{.greek-omitted} [μελεναν]{.greek-added} ποιησαι[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου εστιν[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω αλλ οστις σε [ραπισει]{.greek-omitted} [ραπιση]{.greek-added} επι την δεξιαν [σου]{.greek-added} σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

κα[ι]{.unclear} τ[ω]{.unclear} θελοντι σοι κριθηναι και τον χιτωνα σου λαβειν αφες αυτω και [το]{.greek-omitted} [τω]{.greek-added} ιματιον[5:40]{.aside}

και οστις σε [αγγαρευσει]{.greek-omitted} [αγγαρευση]{.greek-added} μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω αιτουντι σε διδου και τον θελοντα απο σου [δανεισασθαι]{.greek-omitted} [δανισασθαι]{.greek-added} μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και [μισησεις]{.greek-omitted} [μησησης]{.greek-added} τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων [ευλογειτε]{.greek-omitted} [ευλογητε]{.greek-added} τους καταρωμενους υμας καλως ποιειτε τοις μισουσιν υμας και προσευχεσθε υπερ των επηρεαζοντ[ων]{.unclear} υμας και διωκοντων υμας[5:44]{.aside}

οπως γενησθε υιοι του [πατρος]{.greek-abbr} υμων του εν τοις ουρανοις οτι τον ηλιον αυτου ανατελλε[ι]{.unclear} επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ αγαπησητε τους αγαπωντας υμας τινα μισθον εχετε ουχι και οι τελωναι [τουτο]{.greek-added} [το]{.greek-omitted} [αυτο]{.greek-omitted} [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[5:46]{.aside}

και εαν [ασπασησθε]{.greek-omitted} [ασπασεισθε]{.greek-added} τους φιλους υμων μονον τι περισσον ποιειτε ουχι και οι [τελωναι]{.greek-omitted} [ουτως]{.greek-omitted} [εθνικοι]{.greek-added} [τουτο]{.greek-added} [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[5:47]{.aside}

[εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} ουν υμεις τελειοι ωσπερ ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} τελειος [εστιν]{.greek-omitted} [εστι]{.greek-added}[5:48]{.aside}

### Chapter 6

[προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} [δε]{.greek-added} την ελεημοσυνην υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν [ποιης]{.greek-omitted} [ποιεις]{.greek-added} ελεημοσυνην μη σαλπιση[ς]{.greek-supplied} εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν τα[ις]{.unclear} ρυμαις οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη [γνωτω]{.greek-omitted} [γνωτο]{.greek-added} η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη [εν]{.greek-omitted} [τω]{.greek-omitted} [κρυπτω]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [σου]{.greek-omitted} [ο]{.greek-omitted} [βλεπων]{.greek-omitted} εν τω κρυπτω αυτος αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται οτι φιλουσιν εν ταις συναγωγαις και εν ταις [γωνιαις]{.greek-omitted} [γονιαις]{.greek-added} των πλατειων εστωτες προσευχεσθαι οπως αν [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το ταμιειον σου και [κλεισας]{.greek-omitted} [κλησας]{.greek-added} την [θυραν]{.greek-omitted} [θυρα]{.greek-added} σου [προσευξαι]{.greek-omitted} [προσευξε]{.greek-added} τω [πατρι]{.greek-abbr} σου [τω]{.greek-omitted} εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη [βαττολογησητε]{.greek-omitted} [βαττολογειτε]{.greek-added} ωσπερ οι εθνικοι [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν [ομοιωθητε]{.greek-omitted} [ομοιωθειτε]{.greek-added} αυτοις οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ων χρειαν εχετε προ του υμας αιτησαι αυτον[6:8]{.aside}

ουτως ουν προσευχεσθε υμεις [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το ονομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν [ουρανω]{.greek-abbr} και επι της γης[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα [οφειληματα]{.greek-omitted} [οφειλη]{.greek-added} [ματα]{.greek-added} [ημων]{.greek-omitted} [υμων]{.greek-added} ως και [ημεις]{.greek-omitted} [υμεις]{.greek-added} αφιεμεν τοις [οφειλεταις]{.greek-omitted} [οφιλεταις]{.greek-added} ημων[6:12]{.aside}

και μη εισενεγκης ημας εις [πειρασμον]{.greek-omitted} [πηρασμον]{.greek-added} αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα εις τους αιωνας αμην[6:13]{.aside}

εαν γαρ αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} [τα]{.greek-added} [παραπτωματα]{.greek-added} [υμων]{.greek-added}[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων αφησει τα παραπτωματα υμων[6:15]{.aside}

οταν δε [νηστευητε]{.greek-omitted} [νηστευηται]{.greek-added} μη γινεσθε ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} [γαρ]{.greek-omitted} [[π]{.unclear}]{.greek-added} [τα]{.corr} προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων αλειψαι σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι [εν]{.greek-added} [τω]{.greek-added} [φανερω]{.greek-added}[6:18]{.aside}

μη θησαυριζετε υμιν θησαυρους επι της γης οπου σης [διαφθερει]{.greek-added} και [βρωσις]{.greek-omitted} [βρωσεις]{.greek-added} αφανιζει και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορυσσουσι]{.greek-added} και [κλεπτουσιν]{.greek-omitted} [κλεπτουσι]{.greek-added}[6:19]{.aside}

[θησαυριζετε]{.greek-omitted} [θησαυριζεται]{.greek-added} δε υμιν θησαυρους εν [ουρανω]{.greek-abbr} οπου ουτε σης ουτε βρωσις αφανιζει και οπου κλεπται ου διορυσσουσιν ουδε κλεπτουσιν[6:20]{.aside}

οπου γαρ εστιν ο θησαυρος υμων εκει εσται και η καρδια υμων[6:21]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους [η]{.greek-omitted} [ει]{.greek-added} ολον το σωμα σου φωτεινον εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος [εστιν]{.greek-omitted} [εστι]{.greek-added} το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η ενος ανθεξεται και του ετερου καταφρονησει ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} [θεω]{.greek-abbr} δουλευειν και μαμωνα[6:24]{.aside}

δια τουτο λεγω υμιν μη μεριμνατε τη ψυχη υμων τι [φαγητε]{.greek-omitted} [φαγετε]{.greek-added} και τι [πιητε]{.greek-omitted} [πιετε]{.greek-added} μηδε τω σωματι υμων τι ενδυσησθε [ουχι]{.greek-omitted} [ουχη]{.greek-added} η ψυχη πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα πετεινα του [ουρανου]{.greek-abbr} οτι ου σπειρουσιν ουδε θεριζουσιν ουδε συναγουσιν εις αποθηκας και ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} τρεφει αυτα ουχ υμεις μαλλον διαφερετε αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται [προσθειναι]{.greek-omitted} [προσθηναι]{.greek-added} επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε νηθει[6:28]{.aside}

[λεγω]{.greek-omitted} [λε]{.greek-added} [γω]{.greek-added} δε υμιν οτι ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλομενον ο [θεος]{.greek-abbr} ουτως αμφιεννυσιν ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν μεριμνησητε λεγοντες τι φαγωμεν η τι πιωμεν η τι [περιβαλωμεθα]{.greek-omitted} [περιβαλομεθα]{.greek-added}[6:31]{.aside}

παντα γαρ ταυτα τα εθνη επιζητει οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ο [ουρανιος]{.greek-abbr} οτι χρηζετε τουτων απαντων[6:32]{.aside}

ζητειτε δε πρωτον την βασιλειαν του [θεου]{.greek-abbr} και την δικαιοσυνην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν μεριμνησητε εις την αυριον η γαρ αυριον [μεριμνησει]{.greek-omitted} [μεριμνησητε]{.greek-added} [τα]{.greek-omitted} εαυτης αρκετον τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

μη κρινετε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε [κριθησεσθε]{.greek-omitted} [κριθησεσθαι]{.greek-added} και εν ω μετρω μετρειτε [μετριθησετε]{.greek-added} [μετρηθησεται]{.greek-omitted} [[μετριθησεται]{.corr}]{.greek-added} υμιν[7:2]{.aside}

τι δε [βλεπεις]{.greek-omitted} [βλεπης]{.greek-added} το καρφος το εν τω οφθαλμω του αδελφου σου την δε εν τω σω οφθαλμω [δοκον]{.greek-omitted} [δοκων]{.greek-added} ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος απο του οφθαλμου σου και ιδου η [δοκος]{.greek-omitted} [δοκως]{.greek-added} εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη δωτε το αγιον τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε [βαλητε]{.greek-omitted} [βαλειτε]{.greek-added} τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε [καταπατησωσιν]{.greek-omitted} [καταπατησουσιν]{.greek-added} αυτους εν τοις ποσιν αυτων και στραφεντες [ρηξωσιν]{.greek-omitted} [ρηξουσιν]{.greek-added} υμας[7:6]{.aside}

αιτειτε και δοθησεται υμιν ζητειτε και ευρησετε κρουετε και ανοιγησεται υμιν[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις εστιν εξ υμων [ανθρωπος]{.greek-abbr} ον εαν αιτηση ο υιος αυτου αρτον μη λιθον επιδωσει [αυτον]{.greek-added} [αυτω]{.corr}[7:9]{.aside}

και εαν ιχθυν αιτηση μη οφιν επιδωσει αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων [ποσω]{.greek-omitted} [μαλλον]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added}[7:11]{.aside}

παντα ουν οσα αν θελητε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} ουτως και υμεις ποιειτε αυτοις ουτος γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

[εισελθετε]{.greek-omitted} [εισελθατε]{.greek-added} δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

τι στενη η πυλη και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

[προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε [αυ]{.greek-added} [αυτους]{.greek-omitted} [τους]{.greek-added} μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον σαπρον καρπους καλους ποιειν[7:18]{.aside}

παν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν ουρανοις[7:21]{.aside}

πολλοι [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μοι εν εκεινη τη ημερα [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου [τ]{.unclear}[ω]{.greek-supplied} σω ονοματι προεφητευσαμεν κα[ι]{.unclear} τω σω ονοματι δαιμονια εξεβαλομεν και τω σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε ομολογησω α[υτ]{.unclear}οις οτι ουδεποτε εγνων υμας αποχωρειτε απ εμου οι εργαζομενοι την ανομιαν[7:23]{.aside}

πας ουν οστις ακουει μου τους λογους τουτους και ποιει αυτους ομοιωσω αυτον ανδρ[ι]{.greek-supplied} φρονιμω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και [προσεπεσον]{.greek-omitted} [προσεπεσαν]{.greek-added} τη οικια εκεινη και ουκ [επεσεν]{.greek-omitted} [επεσε]{.greek-added} τεθεμελιωτο γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεκοψαν τη οικια εκεινη και [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγενετο οτε συνετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις [αυτων]{.greek-added}[7:29]{.aside}

### Chapter 8

καταβαντι δε αυτω απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου [προσελθων]{.greek-added} λεπρος [ελθων]{.greek-omitted} προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} εαν θελης δυνασαι με καθαρισαι[8:2]{.aside}

και εκτεινας την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω καθαρισθητι και ευθεως εκαθαρισθη αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι ειπης αλλα υπαγε σεαυτον δειξον τω ιερει και προσενεγκε το δωρον ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} μωσης εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε αυτω εις καπερναουμ προσηλθεν αυτω εκατονταρχος παρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου βεβληται εν τη οικια [παραλυτικος]{.greek-omitted} δεινως βασανιζομενος [παραλυτικος]{.greek-added}[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την στεγην εισελθης αλλα μονον ειπε λογω και ιαθησεται ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} ειμι [και]{.greek-added} [υπο]{.greek-omitted} [υπ]{.greek-added} εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου [ποιησον]{.greek-omitted} [ποιεισον]{.greek-added} τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} [εθαυμασεν]{.greek-omitted} [εθαυμασε]{.greek-added} και ειπεν τοις ακολουθουσιν αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην [πιστιν]{.greek-omitted} [πιστην]{.greek-added} ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και [ανακλιθησονται]{.greek-omitted} [ανακληθησονται]{.greek-added} μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των [ουρανων]{.greek-abbr}[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω εκατονταρχη υπαγε [και]{.greek-omitted} ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη[8:13]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου ειδεν την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και [αφηκεν]{.greek-omitted} [αφη]{.greek-added} [κεν]{.greek-added} αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα [πνευματα]{.greek-abbr} λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος αυτος τας ασθενειας ημων [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι [αυτον]{.greek-omitted} [αυτων]{.greek-added} εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν [απερχη]{.greek-omitted} [απερχει]{.greek-added}[8:19]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες φωλεους [εχουσιν]{.greek-omitted} [εχωσι]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε υιος του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κληναι]{.greek-added}[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} [επιτρεψον]{.greek-omitted} [επιστρεψον]{.greek-added} μοι πρωτον απελθειν και θαψαι τον [πατερα]{.greek-abbr} μου[8:21]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις το πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον [καλυπτεσθαι]{.greek-omitted} [καλυπτεσθε]{.greek-added} υπο των [κυματων]{.greek-omitted} [κοιματων]{.greek-added} [ην]{.greek-added} [γαρ]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [ανεμος]{.greek-added} [εναντιος]{.greek-added} [αυτοις]{.greek-added} αυτος δε εκαθευδεν[8:24]{.aside}

και [προσελθοντες]{.greek-omitted} [προσελθωντες]{.greek-added} οι [μαθηται]{.greek-omitted} [μαθη]{.greek-added} [ται]{.greek-added} [αυτου]{.greek-added} ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας [απολλυμεθα]{.greek-omitted} [απολυμεθα]{.greek-added}[8:25]{.aside}

και λεγει αυτοις τι δειλοι [εστε]{.greek-omitted} [εσται]{.greek-added} ολιγοπιστοι τοτε εγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τοις ανεμοις και τη [θαλασση]{.greek-omitted} [θαλασσει]{.greek-added} και εγενετο γαληνη μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

και ελθοντι αυτω εις το περαν εις την χωραν των γεργεσηνων [υπηντησαν]{.greek-omitted} [υπηντισαν]{.greek-added} αυτω δυο δαιμονιζομενοι εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} ηλθες [ωδε]{.greek-omitted} προ καιρου βασανισαι [ημας]{.greek-omitted} [υμας]{.greek-added}[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων πολλων βοσκομενη[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει εκβαλλεις ημας [επιτρεψον]{.greek-omitted} [επιστρεψον]{.greek-added} ημιν απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και ειπεν αυτοις υπαγετε οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου [ωρμησεν]{.greek-omitted} [ωρμησε]{.greek-added} πασα η αγελη [των]{.greek-omitted} [χοιρων]{.greek-omitted} κατα του [κρημνου]{.greek-omitted} [κριμνου]{.greek-added} εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και [ι]{.greek-added} [ιδου]{.greek-omitted} [δου]{.greek-added} πασα η πολις εξηλθεν εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις [το]{.greek-omitted} πλοιον [διεπερασεν]{.greek-omitted} [διεπερασε]{.greek-added} και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων ειπεν τω παραλυτικω θαρσει τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σοι]{.greek-omitted} [σου]{.greek-added} αι αμαρτιαι [σου]{.greek-omitted}[9:2]{.aside}

και ιδου τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και [ιδων]{.greek-omitted} [ειδως]{.greek-added} ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} [υμεις]{.greek-omitted} ενθυμεισθε πονηρα εν ταις καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} ειπειν [αφεωνται]{.greek-omitted} [αφαιωνται]{.greek-added} σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[9:5]{.aside}

ινα δε [ειδητε]{.greek-omitted} [ηδειτε]{.greek-added} οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την [κλινην]{.greek-omitted} [κληνην]{.greek-added} και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι εθαυμασαν και [εδοξασαν]{.greek-omitted} [εδοξαζαν]{.greek-added} τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

και παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} καθημενον επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας [η]{.greek-added} [ηκολουθησεν]{.greek-omitted} [κολουθη]{.greek-added} αυτω[9:9]{.aside}

και εγενετο αυτου ανακειμενου εν τη οικια και ιδου πολλοι τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι [ειπον]{.greek-omitted} [ελεγον]{.greek-added} τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων [εσθιει]{.greek-omitted} ο διδασκαλος υμων [εσθιει]{.greek-added}[9:11]{.aside}

ο δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ι[σ]{.greek-supplied}χυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν ελεον θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους αλλα αμαρτωλους [εις]{.greek-omitted} [μετανοιαν]{.greek-omitted}[9:13]{.aside}

τοτε προσερχονται αυτω οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε μαθηται σου ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[9:14]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος πενθειν εφ οσον μετ αυτων εστιν ο νυμφιος ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

ουδεις δε [επιβαλλη]{.greek-added} [επιβαλλει]{.corr} επιβλημα ρακους αγναφου επι ιματιω παλαιω [αιρει]{.greek-omitted} [ερει]{.greek-added} γαρ το πληρωμα αυτου απο του ιματιου και χειρον σχισμ[α]{.greek-supplied} γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} [βαλλουσιν]{.greek-omitted} οινον νεον εις ασκου[ς]{.unclear} [καινους]{.greek-omitted} [[και]{.unclear}]{.greek-added} [νους]{.greek-added} [βλητεον]{.greek-added} και αμφοτεροι συντηρουνται[9:17]{.aside}

ταυτα αυτου λαλουντος αυτοις ιδου [αρχων]{.greek-omitted} [αρχον]{.greek-added} [εις]{.greek-omitted} [τις]{.greek-added} ελθων προσεκυνει αυτω λεγων οτι η θυγατηρ μου [αρτι]{.greek-omitted} [αυτη]{.greek-added} ετελευτησεν αλλα ελθων επιθες την χειρα σου επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} [ηκολουθησεν]{.greek-omitted} [ηκολουθει]{.greek-added} αυτω και οι μαθηται αυτου[9:19]{.aside}

και ιδου γυνη αιμορροουσα δωδεκα ετη προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον αψωμαι του ιματιου αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} [επιστραφεις]{.greek-omitted} [στραφεις]{.greek-added} και ιδων αυτην ειπεν θαρσει θυγατερ η πιστις σου σεσωκεν σε και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

[ελεγεν]{.greek-added} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} αναχωρειτε ου γαρ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

οτε δε εξεβληθη ο οχλος εισελθων [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αὕτη]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

και παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

ελθοντι δε [αυτω]{.greek-added} εις την οικιαν προσηλθον αυτω οι [τυ]{.greek-added} [τυφλοι]{.greek-omitted} [φλοι]{.greek-added} και λεγει αυτοις ο [ιησους]{.greek-abbr} πιστευετε ο[τι]{.greek-supplied} δυναμαι τουτο [ποιησαι]{.greek-omitted} [ποιεισαι]{.greek-added} λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

τοτε ηψατο των οφθαλμων αυτων λεγων κατα την πιστιν υμων [γενηθητω]{.greek-omitted} [γεννηθητω]{.greek-added} υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθ[αλ]{.greek-supplied}μοι και ενεβριμησατο αυτοις ο [ιησους]{.greek-abbr} λεγω[ν]{.greek-supplied} ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθον[τες]{.greek-supplied} [διεφημισαν]{.greek-omitted} [διεφημησαν]{.greek-added} αυτον εν ολη τη γη εκεινη[9:31]{.aside}

αυτων δε εξερχομενων ιδου προσηνεγ[καν]{.greek-supplied} αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

[και]{.unclear} [εκβληθεντος]{.greek-omitted} [εκβλυθεντος]{.greek-added} του δαιμονιου ελαλησεν ο κωφος και εθαυμασαν οι οχλοι λεγοντες ουδεποτε εφανη ουτως εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

οι δε φαρισαιοι [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμον[ι]{.greek-supplied}α[9:34]{.aside}

και περιηγεν ο [ιησους]{.greek-abbr} τας πολεις πασα[ς]{.unclear} και τας κωμας διδασκων εν ταις συναγωγαις αυτων και κηρυσσων το ευ[α]{.unclear}γγελιον της βασιλειας και θεραπευ[ων]{.greek-supplied} πασαν νοσον και πασαν μαλακιαν [εν]{.greek-omitted} [τω]{.greek-omitted} [λαω]{.greek-omitted}[9:35]{.aside}

ιδων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν εσκυλμενοι και ερριμμενοι [ωσει]{.greek-omitted} [ως]{.greek-added} προβατα μη εχοντα ποιμ[ε]{.greek-supplied}να[9:36]{.aside}

τοτε λεγει τοις μαθηταις αυτου ο [μεν]{.greek-supplied} θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} εργατας εις τον [θερισμον]{.greek-omitted} [θερισ]{.greek-added} [μον]{.greek-added} αυτου[9:38]{.aside}

### Chapter 10

και προσκαλεσαμενος τους δωδεκα μαθητας αυτου εδωκεν αυτοις εξουσιαν [πνευματων]{.greek-abbr} ακαθαρτων ωστε [εκβαλλειν]{.greek-omitted} αυτα [εκβαλειν]{.greek-added} και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

των δε δωδεκα αποστολων τα ονοματα εστιν ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου ιακωβος ο του ζεβεδαιου και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και λεββαιος ο επικληθεις θαδδαιος[10:3]{.aside}

σιμων ο κανανιτης και ιουδας [ο]{.greek-added} ισκαριωτης ο και παραδους αυτον[10:4]{.aside}

τουτους τους δωδεκα απεστειλεν [αυτους]{.greek-added} ο [ιησους]{.greek-abbr} παραγγειλας αυτοις λεγων εις οδον εθνων μη απελθητε και εις πολιν σαμαρειτων μη εισελθητε[10:5]{.aside}

πορευεσθε δε μαλλον προς τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρυσσετε [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} [οτι]{.greek-omitted} [μετανοειτε]{.greek-added} ηγγικεν [γαρ]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

ασθενουντας θεραπευετε λεπρους καθαριζετε δαιμονια εκβαλλετε δωρεαν ελαβετε δωρεαν δοτε[10:8]{.aside}

μη [κτησησθε]{.greek-omitted} [κτησησθαι]{.greek-added} χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον μηδε δυο χιτωνας μηδε υποδηματα μηδε [ραβδους]{.greek-omitted} [ραβδον]{.greek-added} αξιος γαρ ο εργατης της τροφης αυτου εστιν[10:10]{.aside}

εις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις [αξιος]{.greek-added} [εστιν]{.greek-added} εν αυτη [αξιος]{.greek-omitted} [εστιν]{.greek-omitted} κακει [μεινατε]{.greek-omitted} [μηνατε]{.greek-added} εως αν εξελθητε[10:11]{.aside}

εισερχομενοι δε εις την οικιαν ασπασασθε αυτην [λεγοντες]{.greek-added} [ειρηνη]{.greek-added} [τω]{.greek-added} [οικ[ω]{.greek-supplied}]{.greek-added} [τουτω]{.greek-added}[10:12]{.aside}

και εαν μεν η η οικια αξια [ελθετω]{.greek-omitted} [ελθατω]{.greek-added} η ειρηνη υμων επ αυτην εαν δε μη η αξ[ια]{.greek-supplied} η ειρηνη υμων [προς]{.greek-omitted} [εφ]{.greek-added} υμας επιστραφητω[10:13]{.aside}

και ος εαν μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι [εξω]{.greek-added} τη[ς]{.unclear} οικιας η της πολεως εκεινης [εκτιναξατε]{.greek-omitted} [εκτειναξατε]{.greek-added} τον κονιορτον [εκ]{.greek-added} των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται γη σοδομων και γομορρων εν ημερα κρισ[εως]{.unclear} η τη πολει εκεινη[10:15]{.aside}

[ιδου]{.greek-omitted} [οιδου]{.greek-added} εγω αποστελ[λω]{.greek-supplied} υμας ως προβατα εν μεσω λυκων γ[ι]{.unclear}νεσθε ουν φρονιμοι ως οι οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εν ταις συναγωγα[ις]{.greek-supplied} αυτων μαστιγωσουσιν υμας[10:17]{.aside}

και επι η[γε]{.greek-supplied}μονας δε και βασιλεις αχθησεσθε ενεκ[εν]{.greek-supplied} εμου εις μαρτυριον αυτοις και τοις εθνεσιν[10:18]{.aside}

οταν δε [παραδιδωσιν]{.greek-omitted} [παραδωσ[ω]{.unclear}σιν]{.greek-added} υμας μη μεριμνησητε πως η τι [λαλησητε]{.greek-omitted} [λαλη[ση]{.unclear}]{.greek-added} [τε]{.greek-added} [δοθησεται]{.greek-omitted} [δοθησετε]{.greek-added} γαρ υμιν εν εκεινη τη ωρα τι [λαλησετε]{.greek-omitted} [λαλησητε]{.greek-added}[10:19]{.aside}

ου γαρ υμεις εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

παραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[10:22]{.aside}

οταν δε διωκωσιν υμας εν τη πολει ταυτη φευγετε εις την αλλην αμην γαρ λεγω [γαρ]{.greek-added} υμιν ου μη τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο υιος του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

ουκ εστιν μαθητης υπερ τον διδασκαλον [αυτου]{.greek-added} ουδε δουλος υπερ τον [κυριον]{.greek-abbr} αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα [γενηται]{.greek-omitted} [γενητε]{.greek-added} ως ο διδασκαλος αυτου και ο δουλος ως ο [κυριος]{.greek-abbr} αυτου ει τον οικοδεσποτην βεελζεβουλ [εκαλεσαν]{.greek-omitted} [επεκαλεσαντο]{.greek-added} ποσω μαλλον τους [οικειακους]{.greek-omitted} [οικιακους]{.greek-added} αυτου[10:25]{.aside}

μη ουν φοβηθητε αυτους ουδεν γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} κεκαλυμμενον ο ουκ αποκαλυφθησεται και κρυπτον ο ου γνωσθησεται[10:26]{.aside}

ο λεγω υμιν εν τη [σκοτια]{.greek-omitted} [σ[κ]{.unclear}οτεια]{.greek-added} ειπατε εν τω φωτι και ο εις το ους ακουετε κηρυξατε επι των [δωματων]{.greek-omitted} [δοματων]{.greek-added}[10:27]{.aside}

και μη [φοβεισθε]{.greek-omitted} [φοβησθε]{.greek-added} απο των αποκτενοντων το σωμα την δε ψυχην μη δυναμενων αποκτειναι [φοβηθητε]{.greek-omitted} [φοβηθηται]{.greek-added} δε μαλλον τον δυναμενον και την ψυχην και το σωμα απολεσαι εν γεεννη[10:28]{.aside}

ουχι δυο στρουθια [ασσαριου]{.greek-omitted} [ασσαρειων]{.greek-added} πωλειται και εν εξ αυτων ου πεσειται [επι]{.greek-omitted} [εις]{.greek-added} την γην ανευ του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} [του]{.greek-added} [εν]{.greek-added} [τοις]{.greek-added} [[ουρανοις]{.greek-abbr}]{.greek-added}[10:29]{.aside}

υμων δε και αι τριχες της κεφαλης πασαι ηριθμημεναι εισιν[10:30]{.aside}

μη ουν [φοβηθητε]{.greek-omitted} [φοβεισθαι]{.greek-added} πολλων στρουθιων [διαφερετε]{.greek-omitted} [διαφερεται]{.greek-added} υμεις[10:31]{.aside}

πας ουν οστις [ομολογησει]{.greek-omitted} [ομολογηση]{.greek-added} εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[10:32]{.aside}

οστις δ αν [αρνησηται]{.greek-omitted} [αρνησητε]{.greek-added} με εμπροσθεν των [ανθρωπων]{.greek-abbr} αρνησομαι αυτον καγω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:33]{.aside}

μη [νομισητε]{.greek-omitted} [νομησητε]{.greek-added} οτι ηλθον βαλειν ειρηνην επι την γην ουκ ηλθον βαλειν ειρηνην αλλα μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και θυγατερα κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και [οι]{.greek-added} εχθροι του [ανθρωπου]{.greek-abbr} οι [οικειακοι]{.greek-omitted} [οικιακοι]{.greek-added} αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ εστιν μου αξιος και ο φιλων υιον η [θυγατερα]{.greek-omitted} [θυγατεραν]{.greek-added} υπερ εμε ουκ εστιν μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} οπισω μου ουκ εστιν μου αξιος[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου [ληψεται]{.greek-omitted} [λειψεται]{.greek-added} και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου [ληψεται]{.greek-omitted} [λειψεται]{.greek-added}[10:41]{.aside}

και ος εαν ποτιση ενα των μικρων τουτων ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ακουσας εν τω δεσμωτηριω τα εργα του [χριστου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε [ιωαννη]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} και χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι [καθαριζονται]{.greek-omitted} [καθαριζωνται]{.greek-added} και κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

ουτος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ εγηγερται [εν]{.greek-omitted} [εκ]{.greek-added} γεννητοις γυναικων μειζων [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου ο δε μικροτερος εν τη βασιλεια των ουρανων [μειζων]{.greek-omitted} [μειζον]{.greek-added} αυτου εστιν[11:11]{.aside}

απο δε των ημερων [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου εως αρτι η βασιλεια των [ουρανων]{.greek-abbr} βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} προεφητευσαν[11:13]{.aside}

και ει [θελετε]{.greek-omitted} [θελεται]{.greek-added} δεξασθαι αυτος εστιν [η[―]{.gap}λειας]{.greek-added} [ηλιας]{.corr} ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακου[ε]{.unclear}τω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις εν αγοραις καθημενοις και προσφωνουσιν τοι[ς]{.unclear} [εταιροις]{.greek-omitted} [ετεροις]{.greek-added} αυτων[11:16]{.aside}

και λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ [ωρχησασθε]{.greek-omitted} [ορχησασθαι]{.greek-added} εθρηνησαμεν υμιν και ουκ [εκοψασθε]{.greek-omitted} [εκλαυσατε]{.greek-added}[11:17]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο υιος του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης τελωνων φιλος και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο [[ιησους]{.greek-abbr}]{.greek-added} ονειδιζειν τας πολεις εν αις εγενοντο [αι]{.greek-omitted} [ε]{.greek-added} πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χωραζειν]{.greek-added} ουαι σοι βηθσαιδα οτι [ε]{.unclear}ι εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν υμιν παλαι [αν]{.greek-omitted} εν σακκω και σποδω [καθημεναι]{.greek-added} μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ η εως του [ουρανου]{.greek-abbr} [υψωθεισα]{.greek-omitted} [υψωθησα]{.greek-added} εως αδου [καταβιβασθηση]{.greek-omitted} [καταβηβασθησει]{.greek-added} οτι ει εν σοδομοις [εγενοντο]{.greek-omitted} [εγενηθησαν]{.greek-added} αι δυναμεις αι γενομεναι εν σοι εμειναν αν [μεχρι]{.greek-omitted} [μεχρη]{.greek-added} της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι [γη]{.greek-omitted} σοδομων [και]{.greek-added} [γομορρας]{.greek-added} [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται εν ημερα κρισεως η σοι[11:24]{.aside}

εν εκεινω τω καιρω αποκριθεις ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι [παρεδοθη]{.greek-omitted} [παρεδωθη]{.greek-added} υπο του [πατρος]{.greek-abbr} μου και ουδεις επιγινωσκει τον υιον ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο υιος και [ω]{.greek-omitted} [ο]{.greek-added} εαν βουληται ο υιος αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι [κοπιωντες]{.greek-omitted} [κοποιωντες]{.greek-added} και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου [χρηστος]{.greek-omitted} [χριστος]{.greek-added} και το φορτιον μου ελαφρον [εστιν]{.greek-omitted} [εστι]{.greek-added}[11:30]{.aside}

### Chapter 12

εν εκεινω τω καιρω επορευθη ο [ιησους]{.greek-abbr} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων οι δε μαθηται αυτου επεινασαν και ηρξαντο τιλλειν σταχυας και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντες [ειπον]{.greek-omitted} [ειπαν]{.greek-added} αυτω ιδου οι μαθηται σου ποιουσιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} ποιειν εν σαββατω[12:2]{.aside}

ο δε ειπεν αυτοις ουκ ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε επεινασεν αυτος και οι μετ αυτου[12:3]{.aside}

πως εισηλ[θε]{.unclear}ν [εις]{.unclear} [τον]{.unclear} οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως εφαγεν ους ουκ [εξον]{.greek-omitted} [εξων]{.greek-added} ην αυτω φαγειν ουδε τοις μετ αυτου ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} μονοις[12:4]{.aside}

η ουκ ανεγνωτε εν τω νομω οτι τοις σαββασιν οι ιερεις εν τω ιερω το σαββατον βεβηλουσιν [και]{.greek-omitted} αναιτιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[12:5]{.aside}

λεγω δε υμιν οτι του ιερου μειζον εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε τι εστιν ελεον θελω και ου θυσιαν ουκ αν κατεδικασατε τους αναιτιους[12:7]{.aside}

[κυριος]{.greek-abbr} γαρ εστιν [του]{.greek-omitted} [σαββατου]{.greek-omitted} ο υιος του [ανθρωπου]{.greek-abbr} [και]{.greek-added} [του]{.greek-added} [σαββατου]{.greek-added}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ην]{.greek-added} [εκει]{.greek-added} [ανθρωπος]{.greek-abbr} [ην]{.greek-omitted} την χειρα εχων ξηραν και επηρωτησαν αυτον [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} ει εξεστιν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις εσται εξ υμων [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις βοθυνον ουχι κρατησει αυτο και εγερει[12:11]{.aside}

ποσω ουν διαφερει [ανθρωπος]{.greek-abbr} προβατου ωστε [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} καλως ποιειν[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

[εξελθοντες]{.greek-added} [δε]{.greek-added} οι [δε]{.greek-omitted} φαρισαιοι συμβουλιον ελαβον κατ αυτου [εξελθοντες]{.greek-omitted} οπως αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και επετιμησεν αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιεισωσιν]{.greek-added}[12:16]{.aside}

[οπως]{.greek-omitted} [ινα]{.greek-added} πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον ηρετισα ο αγαπητος μου εις ον [ευδοκησεν]{.greek-omitted} [ευδοκισεν]{.greek-added} η ψυχη μου [θησω]{.greek-omitted} [θησο]{.greek-added} το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει ουδε ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον τυφομενον ου σβεσει εως αν εκβαλη εις νικος την κρισιν[12:20]{.aside}

και τω ονοματι αυτου εθνη [ελπιουσιν]{.greek-omitted} [ελπιουσι]{.greek-added}[12:21]{.aside}

τοτε προσηνεχθη αυτω δαιμονιζομενος τυφλος και κωφος και εθεραπευσεν αυτον ωστε τον [κωφον]{.greek-added} [και]{.greek-added} τυφλον [και]{.greek-omitted} [κωφον]{.greek-omitted} και λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο παντες οι οχλοι και [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} μητι ουτος εστιν ο υιος [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες [ειπον]{.greek-omitted} [ειπαν]{.greek-added} ουτος ουκ εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

ειδως δε ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν αυτοις πασα βασιλεια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ερημουται και πασα πολις η οικια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν εκβαλλει εφ εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

και ει εγω εν βεελζεβουλ εκβαλλω τ[α]{.unclear} δαιμονια οι υιοι υμων εν τινι εκβαλλουσιν δια [τουτο]{.greek-omitted} [του]{.greek-added} [το]{.greek-added} αυτοι υμων [εσονται]{.greek-omitted} [εσωνται]{.greek-added} κριται[12:27]{.aside}

ει δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} εγω εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

η πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου διαρπασαι εαν μη πρωτον δηση τον ισχυρον και τοτε την οικιαν αυτου [διαρπασει]{.greek-omitted} [διαρπαση]{.greek-added}[12:29]{.aside}

ο [μη]{.greek-omitted} [μι]{.greek-added} ων μετ εμου κατ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

δια τουτο λεγω υμιν πασα αμαρτια και βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} [η]{.corr} [δε]{.corr} [του]{.corr} [[πνευματος]{.greek-abbr}]{.corr} [βλασφημια]{.corr} [ουκ]{.corr} [αφεθησεται]{.corr} [τοις]{.corr} [[ανθρωποις]{.greek-abbr}]{.corr}[12:31]{.aside}

και ος εαν ειπη λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω ος δ αν ειπη κατα του [πνευματος]{.greek-abbr} του αγιου ουκ αφεθησεται αυτω ουτε εν τω [νυν]{.greek-omitted} αιωνι [τουτω]{.greek-added} ουτε εν τω μελλοντι[12:32]{.aside}

η ποιησατε το δενδρον καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον γινωσκεται[12:33]{.aside}

γεννηματα εχιδνων πως δυνασθε αγαθα λαλειν πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου εκβαλλει [τα]{.greek-added} αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου [εκβαλλει]{.greek-omitted} [της]{.greek-added} [καρδιας]{.greek-added} [προφερει]{.greek-added} [τα]{.greek-added} πονηρα[12:35]{.aside}

λεγω [δε]{.greek-omitted} [γαρ]{.greek-added} υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσου]{.greek-added} [σι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων σου δικαιωθηση και εκ των λογων σου καταδικασθηση[12:37]{.aside}

τοτε απεκριθησαν [αυτω]{.greek-added} τινες των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και φαρισαιων [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} διδασκαλε [θελομεν]{.greek-omitted} [θελωμεν]{.greek-added} απο σου σημειον ιδειν[12:38]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} αποκριθεις ειπεν αυτοις γενεα πονηρα και [μοιχαλις]{.greek-omitted} [μιχαλις]{.greek-added} σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ γαρ ην ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας ουτως [εσται]{.greek-omitted} [εστε]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} εν τη καρδια της γης τρεις ημερας και τρεις νυκτας[12:40]{.aside}

ανδρες [νινευιται]{.greek-omitted} [νηνευιται]{.greek-added} αναστησονται εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

βασιλισσα νοτου εγερθησεται εν τη κρισει μετα της γενεας ταυτης και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν σολομωνος και ιδου πλειον σολομωνος ωδε[12:42]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητουν αναπαυσιν και ουχ ευρισκει[12:43]{.aside}

τοτε λεγει [επιστρεψω]{.greek-omitted} [υποστρεψω]{.greek-added} εις τ[ο]{.unclear}ν οικον μου οθεν [εξηλθον]{.greek-omitted} [εξηλ]{.greek-added} [θον]{.greek-added} και ελθον ευρισκει σχολαζοντα σεσαρωμενον και [κεκοσμημενον]{.greek-omitted} [κεκοσμιμενον]{.greek-added}[12:44]{.aside}

τοτε [πορευεται]{.greek-omitted} [πορευετε]{.greek-added} και παραλαμβανει μεθ εαυτου επτα ετερα [πνευματα]{.greek-abbr} πονηροτερα εαυτου και εισελθοντα κατοικει εκει και γινεται τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου [χειρονα]{.greek-omitted} [χειρωνα]{.greek-added} των πρωτων ουτως εσται και τη γενεα ταυτη τη πονηρα[12:45]{.aside}

ετι δε αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και [οι]{.greek-omitted} [η]{.greek-added} αδελφοι αυτου [ειστηκεισαν]{.greek-omitted} [ειστηκησαν]{.greek-added} εξω ζητουντες αυτω λαλησαι[12:46]{.aside}

ειπεν δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εξω [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} ζητουντες σοι λαλησαι[12:47]{.aside}

ο δε αποκριθεις ειπεν τω ειποντι αυτω τις εστιν η [μητηρ]{.greek-abbr} μου και τινες εισιν οι αδελφοι μου[12:48]{.aside}

και εκτεινας την χειρα αυτου επι τους μαθητας αυτου ειπεν ιδου η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[12:49]{.aside}

οστις γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr} [αυτος]{.greek-omitted} [ουτος]{.greek-added} μου αδελφος και αδελφη και [μητηρ]{.greek-abbr} εστιν[12:50]{.aside}

### Chapter 13

εν δε τη ημερα εκεινη εξελθων ο [ιησους]{.greek-abbr} απο της οικιας εκαθητο παρα την θαλασσαν[13:1]{.aside}

και συνηχθησαν προς αυτον οχλοι πολλοι ωστε αυτον [εις]{.greek-omitted} [το]{.greek-omitted} [πλοιον]{.greek-omitted} εμβαντα καθησθαι και πας ο οχλος επι τον αιγιαλον ειστηκει[13:2]{.aside}

και ελαλησεν αυτοις πολλα εν παραβολαις [λε]{.greek-added} [λεγων]{.greek-omitted} [γων]{.greek-added} ιδου εξηλθεν ο σπειρων του σπειρειν[13:3]{.aside}

και εν τω σπειρειν αυτον α μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} τα πετεινα [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν αυτα[13:4]{.aside}

αλλα δε επεσεν επι τα πετρωδη οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως [εξανετειλεν]{.greek-omitted} [εξανετειλε]{.greek-added} δια το μη εχειν βαθος γης[13:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[13:6]{.aside}

αλλα δε επεσεν επι τας ακανθας και ανεβησαν αι ακανθαι και απεπνιξαν αυτα[13:7]{.aside}

αλλα δε επεσεν επι την γην την καλην και εδιδου καρπον ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:8]{.aside}

ο εχων ωτα ακουειν ακουετω[13:9]{.aside}

και προσελθοντες οι μαθηται ειπον αυτω δια τι εν παραβολαις λαλεις αυτοις[13:10]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι υμιν δεδοται γνωναι τα μυστηρια της βασιλειας των [ουρανων]{.greek-abbr} εκεινοις δε ου δεδοται[13:11]{.aside}

οστις γαρ εχει δοθησεται αυτω και περισσευθησεται οστις δε ουκ εχει και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[13:12]{.aside}

δια τουτο εν παραβολαις αυτοις λαλω οτι βλεποντες ου [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και [ακουοντες]{.greek-omitted} [ακουωντες]{.greek-added} ουκ ακουουσιν ουδε συνιουσιν[13:13]{.aside}

και αναπληρουται αυτοις η προφητεια ησαιου η λεγουσα ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη [ιδητε]{.greek-omitted} [ειδητε]{.greek-added}[13:14]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις ωσιν [αυτων]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστραφωσι]{.greek-added} και ιασομαι αυτους[13:15]{.aside}

υμων δε μακαριοι οι οφθαλμοι οτι [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} και τα ωτα υμων οτι [ακουει]{.greek-omitted} [ακουουσιν]{.greek-added}[13:16]{.aside}

αμην γαρ λεγω υμιν οτι πολλοι προφηται και δικαιοι επεθυμησαν ιδειν α βλεπετε και ουκ ειδον και ακουσαι α ακουετε και ουκ ηκουσαν[13:17]{.aside}

υμεις ουν ακουσατε την παραβολην του [σπειροντος]{.greek-omitted} [σπειραντος]{.greek-added}[13:18]{.aside}

παντος ακουοντος τον λογον της βασιλειας [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} και μη συνιεντος ερχεται ο πονηρος και αρπαζει το εσπαρμενον εν τη καρδια αυτου ουτος εστιν ο παρα την οδον σπαρεις[13:19]{.aside}

ο δε επι τα πετρωδη σπαρεις ουτος εστιν ο τον λογον ακουων και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} μετα χαρας λαμβανων αυτον[13:20]{.aside}

ουκ εχει δε ριζαν εν εαυτω αλλα προσκαιρος εστιν γενομενης δε θλιψεως η διωγμου δια τον λογον [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} σκανδαλιζεται[13:21]{.aside}

ο δε εις τας ακανθας σπαρεις ουτος εστιν ο τον λογον ακουων και η μεριμνα του αιωνος τουτου και η απατη του πλουτου [συμπνιγει]{.greek-omitted} [συμπνηγει]{.greek-added} τον λογον και ακαρπος γινεται[13:22]{.aside}

ο δε επι την γην την καλην σπαρεις [ου]{.greek-added} [ουτος]{.greek-omitted} [τος]{.greek-added} εστιν ο τον λογον ακουων και [συνιων]{.greek-omitted} [συνιεις]{.greek-added} ος δη καρποφορει και ποιει ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:23]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων [ωμοιωθη]{.greek-omitted} [ομοια]{.greek-added} [εστιν]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} [σπειροντι]{.greek-omitted} [σπειραντι]{.greek-added} καλον σπερμα εν τω αγρω αυτου[13:24]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} καθευδειν τους ανθρωπους ηλθεν αυτου ο εχθρος και [εσπειρεν]{.greek-omitted} [επεσπειρε]{.greek-added} ζιζανια ανα μεσον του σιτου και απηλθεν[13:25]{.aside}

οτε δε εβλαστησεν ο χορτος και καρπον [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοτε εφανη και τα ζιζανια[13:26]{.aside}

[και]{.greek-added} [προσελθοντες]{.greek-omitted} [προσελθωντες]{.greek-added} [δε]{.greek-omitted} οι δουλοι του οικοδεσποτου ειπον αυτω [κυριε]{.greek-abbr} ουχι καλον σπερμα [εσπειρας]{.greek-omitted} [εσπειρες]{.greek-added} εν τω σω αγρω ποθεν ουν εχει ζιζανια[13:27]{.aside}

ο δε εφη αυτοις εχθρος [ανθρωπος]{.greek-abbr} τουτο εποιησεν οι δε δουλοι ειπον αυτω [θελεις]{.greek-omitted} [θελης]{.greek-added} ουν απελθοντες [συλλεξομεν]{.greek-omitted} [συλλεξωμεν]{.greek-added} αυτα[13:28]{.aside}

ο δε εφη ου μηποτε συλλεγοντες τα ζιζανια εκριζωσητε αμα αυτοις τον σιτον[13:29]{.aside}

[αφετε]{.greek-omitted} [αφεται]{.greek-added} συναυξανεσθαι [αμφοτερα]{.greek-omitted} [αμφοτεροι]{.greek-added} μεχρι του θερισμου και εν καιρω του θερισμου ερω τοις θερισταις συλλεξατε πρωτον τα ζιζανια και δησατε αυτα εις δεσμας προς το κατακαυσαι αυτα τον δε σιτον συναγαγετε εις την αποθηκην μου[13:30]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [κοκκω]{.greek-omitted} [κοκω]{.greek-added} [σιναπεως]{.greek-omitted} [συναπεως]{.greek-added} ον λαβων [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο μικροτερον μεν [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των σπερματων οταν δε αυξηθη [μειζον]{.greek-omitted} [μειζων]{.greek-added} των λαχανων εστιν και γινεται δενδρον ωστε ελθειν τα πετεινα του [ουρανου]{.greek-abbr} και κατασκηνουν εν τοις κλαδοις αυτου[13:32]{.aside}

αλλην παραβολην [ελαλησεν]{.greek-omitted} [παρεθηκεν]{.greek-added} αυτοις ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} ζυμη ην λαβουσα γυνη [εκρυψεν]{.greek-omitted} [ενεκρυψεν]{.greek-added} εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33]{.aside}

ταυτα παντα ελαλησεν ο [ιησους]{.greek-abbr} εν παραβολαις τοις οχλοις και χωρις παραβολης [ουκ]{.greek-omitted} [ελαλει]{.greek-omitted} [ουδεν]{.greek-added} [ελαλη]{.greek-added} αυτοις[13:34]{.aside}

οπως πληρωθη το ρηθεν δια του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου ερευξομαι κεκρυμμενα απο καταβολης κοσμου[13:35]{.aside}

τοτε αφεις τους οχλους ηλθεν εις την οικιαν ο [ιησους]{.greek-abbr} και προσηλθον αυτω οι μαθηται αυτου [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} φρασον ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις ο σπειρων το καλον σπερμα εστιν ο υιος του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του [πο]{.greek-added} [πονηρου]{.greek-omitted} [νηρου]{.greek-added}[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστιν οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν συλλεγεται τα ζιζανια και πυρι καιεται ουτως εσται εν τη συντελεια του αιωνος [τουτου]{.greek-omitted}[13:40]{.aside}

αποστελει ο υιος του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και [βαλουσιν]{.greek-omitted} [εμβαλουσιν]{.greek-added} αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν [τω]{.greek-omitted} αγρω ον ευρων [ανθρωπος]{.greek-abbr} εκρυψεν και απο της χαρας αυτου υπαγει και [πωλει]{.greek-added} παντα οσα εχει [πωλει]{.greek-omitted} και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

ος ευρων ενα πολυτιμον μαργαριτην απελθων [πεπρακεν]{.greek-omitted} [πεπρακε]{.greek-added} παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη βληθειση εις την θαλασσαν και εκ παντος γενους συναγαγουση[13:47]{.aside}

ην οτε επληρωθη [α]{.greek-added} [αναβιβασαντες]{.greek-omitted} [ναβηβασαντες]{.greek-added} επι τον αιγιαλον και [καθισαντες]{.greek-omitted} [καθησαντες]{.greek-added} συνελεξαν τα καλα εις [αγγεια]{.greek-omitted} [αγγια]{.greek-added} τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται εν τη συντελεια του αιωνος εξελευσονται οι αγγελοι και [αφοριουσιν]{.greek-omitted} [αφοριουσι]{.greek-added} τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται [ο]{.greek-omitted} κλαυθμος και ο βρυγμος των οδοντων[13:50]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[13:51]{.aside}

ο δε [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις δια τουτο πας γραμματευς μαθητευθεις εις την βασιλειαν των [ουρανων]{.greek-abbr} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις [εκβαλλει]{.greek-omitted} [εκβαλει]{.greek-added} εκ του θησαυρου αυτου καινα και παλαια[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας μετηρεν εκειθεν[13:53]{.aside}

και ελθων εις την [πατριδα]{.greek-abbr} αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων ωστε [εκπληττεσθαι]{.greek-omitted} [εκπλησσεσθαι]{.greek-added} αυτους και λεγειν ποθεν [τουτω]{.greek-omitted} [τουτο]{.greek-added} η σοφια αυτη και αι δυναμεις[13:54]{.aside}

ουχ ουτος εστιν ο του [τεκτονος]{.greek-omitted} [τεκτωνος]{.greek-added} υιος ουχι η [μητηρ]{.greek-abbr} αυτου λεγεται μαριαμ και οι αδελφοι αυτου ιακωβος και [ιωσης]{.greek-omitted} [ιωση]{.greek-added} και σιμων και ιουδας[13:55]{.aside}

και αι αδελφαι αυτου ουχι πασαι προς [ημας]{.greek-omitted} [υμας]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} ποθεν ουν τουτω ταυτα παντα[13:56]{.aside}

και εσκανδαλιζοντο εν αυτω ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} [ει]{.greek-added} [ειπεν]{.greek-omitted} [πεν]{.greek-added} αυτοις ουκ εστιν προφητης ατιμος ει μη εν τη [[πριδη]{.greek-abbr}]{.greek-added} [πατριδι]{.greek-omitted} [αυτου]{.greek-omitted} και εν τη οικια αυτου[13:57]{.aside}

και ουκ εποιησεν εκει δυναμεις πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω ηκουσεν ηρωδης ο τετραρχης την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και ειπεν τοις παισιν αυτου ουτος εστιν [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο βαπτιστης αυτος ηγερθη απο των νεκρων και δια τουτο αι δυναμεις ενεργουσιν εν αυτω[14:2]{.aside}

ο γαρ ηρωδης [τοτε]{.greek-added} κρατησας τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εδησεν αυτον και [εθετο]{.greek-omitted} [απεθετω]{.greek-added} εν [τη]{.greek-added} φυλακη δια [ηρωδιαδα]{.greek-omitted} [ηρωδιαδο[ς]{.unclear}]{.greek-added} την γυναικα φιλιππου του αδελφου αυτου[14:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουκ εξεστιν σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων δε [αγομενων]{.greek-omitted} [γενομενων]{.greek-added} του ηρωδου [ωρχησατο]{.greek-omitted} [ωρχησατω]{.greek-added} η θυγατηρ της ηρωδιαδος εν τω μεσω και ηρεσεν τω ηρωδη[14:6]{.aside}

οθεν μεθ ορκου [ωμολογησεν]{.greek-omitted} [ωμοσεν]{.greek-added} αυτη δουναι ο εαν αιτησηται[14:7]{.aside}

η δε [προβιβασθεισα]{.greek-omitted} [προβηβασθησα]{.greek-added} υπο της [μητρος]{.greek-abbr} αυτης [ειπεν]{.greek-added} δος [μοι]{.greek-omitted} φησιν ωδε επι πινακι την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[14:8]{.aside}

και [ελυπηθη]{.greek-omitted} [ελυπιθη]{.greek-added} ο βασιλευς δια δε τους ορκους και τους συνανακειμενους [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλησε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εν τη φυλακη[14:10]{.aside}

και ηνεχθη η [κεφαλη]{.greek-omitted} [κεφα]{.greek-added} [λη]{.greek-added} αυτου επι πινακι και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} τω κορασιω και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το [σωμα]{.greek-omitted} [πτωμα]{.greek-added} [αυτου]{.greek-added} και εθαψαν αυτο και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

[και]{.greek-omitted} ακουσας [δε]{.greek-added} ο [ιησους]{.greek-abbr} ανεχωρησεν εκειθεν εν πλοιω εις ερημον τοπον κατ ιδιαν και ακουσαντες οι οχλοι ηκολουθησαν αυτω πεζη απο των πολεων[14:13]{.aside}

και εξελθων ο [ιησους]{.greek-abbr} ειδεν πολυν οχλον και εσπλαγχνισθη επ αυτοις και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται αυτου λεγοντες ερημος εστιν ο τοπος και η ωρα [ηδη]{.greek-omitted} [ιδη]{.greek-added} παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας κωμας [αγορασωσιν]{.greek-omitted} [αγωρασωσιν]{.greek-added} εαυτοις βρωματα[14:15]{.aside}

ο δε [φησιν]{.greek-added} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} ου χρειαν εχουσιν απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ [εχομεν]{.greek-omitted} [εχωμεν]{.greek-added} ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε ειπεν φερετε μοι αυτους ωδε[14:18]{.aside}

και κελευσας τους οχλους [ανακλιθηναι]{.greek-omitted} [ανακληθηναι]{.greek-added} επι [τους]{.greek-omitted} [του]{.greek-added} [χορτους]{.greek-omitted} [χορτου]{.greek-added} λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και κλασας [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και [εφαγον]{.greek-omitted} [εφαγων]{.greek-added} παντες και εχορτασθησαν και ηραν το [πε]{.greek-added} [περισσευον]{.greek-omitted} [ρισσευον]{.greek-added} των κλασματων δωδεκα κοφινους [πληρεις]{.greek-omitted} [πληρης]{.greek-added}[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες [ωσει]{.greek-omitted} [ως]{.greek-added} πεντακισχιλιοι χωρις γυναικων και παιδιων[14:21]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας εμβηναι εις το πλοιον και προαγειν αυτον εις το περαν εως ου απολυση τους οχλους[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος [προσευξασθαι]{.greek-added} κατ ιδιαν [προσευξασθαι]{.greek-omitted} οψιας δε γενομενης μονος ην εκει[14:23]{.aside}

το δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος απηλθεν προς αυτους ο [ιησους]{.greek-abbr} περιπατων επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασσαν]{.greek-added}[14:25]{.aside}

και ιδοντες αυτον οι μαθηται επι την [θαλασσαν]{.greek-omitted} [θαλασ[σι]{.unclear}ν]{.greek-added} περιπατουντα εταραχθησαν λεγοντες οτι φαντασμα [εστιν]{.greek-omitted} [εστι]{.greek-added} και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} λεγων θαρσειτε εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε αυτω ο πετρος ειπεν [κυριε]{.greek-abbr} ει συ ει κελευσον [με]{.greek-omitted} [μοι]{.greek-added} προς σε ελθειν επι τα υδατα[14:28]{.aside}

ο δε ειπεν ελθε και καταβας απο του πλοιου ο πετρος περιεπατησεν επι τα υδατα [ελθειν]{.greek-omitted} [και]{.greek-added} [ηλθεν]{.greek-added} προς τον [ιησουν]{.greek-abbr}[14:29]{.aside}

βλεπων δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα [επελαβετο]{.greek-omitted} [απελαβετο]{.greek-added} αυτου και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω [ελθοντες]{.greek-omitted} προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} αληθως [θεου]{.greek-abbr} υιος ει[14:33]{.aside}

και διαπερασαντες ηλθον εις την γην γεννησαρετ[14:34]{.aside}

και επιγνοντες αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις ολην την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον αψωνται του [κρασπεδου]{.greek-omitted} [του]{.greek-omitted} ιματιου αυτου και οσοι ηψαντο διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτε [προσερχονται]{.greek-omitted} [προσερχωνται]{.greek-added} τω [ιησου]{.greek-abbr} οι απο ιεροσολυμων γραμματεις και φαρισαιοι λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου παραβαινουσιν την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} των πρεσβυτερων ου γαρ νιπτονται τας χειρας αυτων οταν αρτον εσθιωσιν[15:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και υμεις παραβαινετε την εντολην του [θεου]{.greek-abbr} δια την [παραδοσιν]{.greek-omitted} [παραδωσιν]{.greek-added} υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} ενετειλατο λεγων τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} και ο κακολογων [πατερα]{.greek-abbr} η μητερα θανατω τελευτατω[15:4]{.aside}

υμεις δε λεγετε ος αν ειπη τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} δωρον ο εαν εξ εμου ωφεληθης [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[και]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [τιμησει]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} και ηκυρωσατε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:6]{.aside}

υποκριται καλως [προεφητευσεν]{.greek-omitted} [προεφητευσε]{.greek-added} περι υμων ησαιας λεγων[15:7]{.aside}

[εγγιζει]{.greek-omitted} [μοι]{.greek-omitted} ο λαος ουτος [τω]{.greek-omitted} [στοματι]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[15:8]{.aside}

ματην δε [σεβονται]{.greek-omitted} [σεβοντασε]{.greek-added} [με]{.greek-omitted} διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις ακουετε και συνιετε[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} αλλα το εκπορευομενον εκ του στοματος τουτο κοινοι τον [ανθρωπον]{.greek-abbr}[15:11]{.aside}

τοτε προσελθοντες οι μαθηται αυτου [ειπον]{.greek-omitted} [λεγουσιν]{.greek-added} αυτω οιδας οτι οι φαρισαιοι ακουσαντες τον λογον εσκανδαλισθησαν[15:12]{.aside}

ο δε αποκριθεις ειπεν πασα φυτεια ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο [ουρανιος]{.greek-abbr} εκριζωθησεται[15:13]{.aside}

αφετε αυτους [τυφλοι]{.greek-added} [εισιν]{.greek-added} οδηγοι [εισιν]{.greek-omitted} [τυφλοι]{.greek-omitted} τυφλων τυφλος δε τυφλον εαν [οδηγη]{.greek-omitted} [οδηγηση]{.greek-added} αμφοτεροι εις βοθυνον πεσουνται[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν ακμην και υμεις ασυνετοι εστε[15:16]{.aside}

ουπω νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφ[ε]{.unclear}δρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ της καρδιας εξερχεται κακεινα κοινοι τον [ανθρωπον]{.greek-abbr}[15:18]{.aside}

εκ γαρ της καρδιας εξερχονται διαλογισμοι πονηροι [πορνειαι]{.greek-added} [μοιχειαι]{.greek-added} φονοι [μοιχειαι]{.greek-omitted} [πορνειαι]{.greek-omitted} κλοπαι ψευδομαρτυριαι βλασφημιαι[15:19]{.aside}

ταυτα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr} το δε ανιπτοις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} φαγειν ου κοινοι τον [ανθρωπον]{.greek-abbr}[15:20]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα [μερη]{.greek-omitted} [μερει]{.greek-added} τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα εκραυγασεν αυτω λεγουσα ελεησον με [κυριε]{.greek-abbr} υιε [δαυιδ]{.greek-abbr} η θυγατηρ μου κακως δαιμονιζεται[15:22]{.aside}

ο δε ουκ απεκριθη αυτη λογον και προσελθοντες οι μαθηται αυτου [ηρωτων]{.greek-omitted} [ηρωτον]{.greek-added} αυτον λεγοντες απολυσον αυτην οτι κραζει οπισθεν ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην ει μη εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

η δε ελθουσα [προσεκυνησεν]{.greek-omitted} [προσεκυνη]{.greek-added} αυτω λεγουσα [κυριε]{.greek-abbr} [βοηθει]{.greek-omitted} [βοηθη]{.greek-added} μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ εστιν καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε ειπεν ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των ψ[ιχ]{.unclear}ιων των πιπτοντων απο της τραπ[ε]{.unclear}ζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν [αυτη]{.greek-omitted} ω γυναι μεγαλη σου η πιστις γενηθητω σοι ως [θελεις]{.greek-omitted} [θε]{.greek-added} [θελης]{.greek-added} και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} ηλθεν παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος εκαθητο εκει[15:29]{.aside}

και [προσηλθον]{.greek-omitted} [προσηλθων]{.greek-added} αυτω οχλοι πολλοι εχοντες μεθ εαυτων χωλους τυφλους [κυλλους]{.greek-added} κωφους [κυλλους]{.greek-omitted} και ετερους πολλους και [ερριψαν]{.greek-omitted} [ερρηψαν]{.greek-added} αυτους παρα τους ποδας [του]{.greek-omitted} [αυτου]{.greek-added} [ιησου]{.greek-omitted} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους [λαλουντας]{.greek-omitted} [ακουωντας]{.greek-added} κυλλους υγιεις [και]{.greek-added} χωλους περιπατουντας και τυφλους βλεποντας και εδοξασαν τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου ειπεν σπλαγχνιζομαι επι τον οχλον οτι [ηδη]{.greek-omitted} [ειδη]{.greek-added} [ημεραι]{.greek-omitted} [ημερας]{.greek-added} τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} και απολυσαι αυτους [νηστεις]{.greek-omitted} [νηστις]{.greek-added} ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια αρτοι τοσουτοι ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} επτα και ολιγα ιχθυδια[15:34]{.aside}

και [εκελευσεν]{.greek-omitted} [τοις]{.greek-omitted} [οχλοις]{.greek-omitted} [παραγγειλας]{.greek-added} [τω]{.greek-added} [οχλω]{.greek-added} αναπεσειν επι την γην[15:35]{.aside}

[ελαβεν]{.greek-added} [και]{.greek-omitted} [λαβων]{.greek-omitted} τους επτα αρτους και τους ιχθυας [και]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδιδου]{.greek-added} τοις μαθηταις [αυτου]{.greek-omitted} οι δε μαθηται [τω]{.greek-omitted} [οχλω]{.greek-omitted} [τοις]{.greek-added} [οχλοις]{.greek-added}[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας πληρεις[15:37]{.aside}

οι δε εσθιοντες ησαν [ανδρες]{.greek-added} [ωσει]{.greek-added} τετρακισχιλιοι [ανδρες]{.greek-omitted} χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους ενεβη εις το πλοιον και ηλθεν εις τα [ορια]{.greek-omitted} [ορει]{.greek-added} μαγδαλα[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και [οι]{.greek-added} σαδδουκαιοι πειραζοντες επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε ευδια πυρραζει γαρ ο ουρανος[16:2]{.aside}

και πρωι σημερον χειμων πυρραζει γαρ στυγναζων ο [ουρανος]{.greek-abbr} [υποκριται]{.greek-omitted} το μεν προσωπον του [ουρανου]{.greek-abbr} γινωσκετε διακρινειν τα δε σημεια των καιρων ου δυνασθε[16:3]{.aside}

γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} αυτους απηλθεν[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν [επελαθοντο]{.greek-omitted} [απελαθοντο]{.greek-added} αρτους λαβειν[16:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ορατε και προσεχετε απο της ζυμης των φαρισαιων και σαδδουκαιων[16:6]{.aside}

οι δε διελογιζοντο εν εαυτοις [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} οτι αρτους ουκ [ε]{.greek-added} [ελαβομεν]{.greek-omitted} [λαβομεν]{.greek-added}[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-omitted} τι διαλογιζεσθε εν εαυτοις ολιγοπιστοι οτι αρτους ουκ [ελαβετε]{.greek-omitted} [εχετε]{.greek-added}[16:8]{.aside}

ουπω νοειτε ουδε μνημονευετε τους πεντε αρτους των πεντακισχιλιων και [ποσους]{.greek-omitted} [πωσους]{.greek-added} κοφινους ελαβετε[16:9]{.aside}

ουδε τους επτα αρτους των τετρακισχιλιων και [ποσας]{.greek-omitted} [πωσας]{.greek-added} σπυριδας ελαβετε[16:10]{.aside}

πως ου νοειτε οτι ου περι [αρτου]{.greek-omitted} [αρτων]{.greek-added} ειπον υμιν προσεχειν απο της ζυμης των φαρισαιων και σαδδουκαιων[16:11]{.aside}

τοτε συνηκαν οτι ουκ ειπεν προσεχειν απο της ζυμης του αρτου αλλα απο της [διδαχης]{.greek-omitted} [διδασκαλιας]{.greek-added} των φαρισαιων και σαδδουκαιων[16:12]{.aside}

[ελθων]{.greek-omitted} [εξελθων]{.greek-added} δε ο [ιησους]{.greek-abbr} εις τα μερη καισαρειας της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι τον υιον του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον οι μεν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λεγει αυτοις υμεις δε τινα [με]{.greek-omitted} λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος ειπεν συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτω μακαριος ει σιμων βαριωνα οτι [σαρξ]{.greek-omitted} [σα[ρ]{.unclear}]{.greek-added} και αιμα ουκ [απεκαλυψεν]{.greek-omitted} [απεκαλυψε]{.greek-added} σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις [ουρανοις]{.greek-abbr}[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι αδου ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της βασιλειας των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν τοις [ουρανοις]{.greek-abbr} και ο εαν λυσης επι της γης [εσται]{.greek-omitted} [εστε]{.greek-added} λελυμενον εν τοις [ουρανοις]{.greek-abbr}[16:19]{.aside}

τοτε [διεστειλατο]{.greek-omitted} [διεστηλατο]{.greek-added} τοις μαθηταις αυτου ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο τοτε [ηρξατο]{.greek-omitted} [ηρξατω]{.greek-added} [ο]{.greek-omitted} [ιησους]{.greek-omitted} δεικνυειν τοις μαθηταις αυτου οτι δει αυτον απελθειν εις ιεροσολυμα και πολλα παθειν [και]{.greek-added} [αποδοκιμασθηναι]{.greek-added} απο των πρεσβυτερων και αρχιερεων και [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και τη τριτη ημερα εγερθηναι[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω λεγων ιλεως σοι [κυριε]{.greek-abbr} ου μη εσται σοι τουτο[16:22]{.aside}

ο δε στραφεις ειπεν τω πετρω υπαγε οπισω μου σατανα σκανδαλον μου ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} ειπεν τοις μαθηταις αυτου ει [τι]{.greek-added} [τις]{.corr} [θελει]{.greek-omitted} [θελη]{.greek-added} οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω μοι[16:24]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν [απολεση]{.greek-omitted} [απολεσει]{.greek-added} την [ψυ]{.greek-added} [ψυχην]{.greek-omitted} [χην]{.greek-added} αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι γαρ [ωφελειται]{.greek-omitted} [ωφελησει]{.greek-added} [ανθρωπος]{.greek-omitted} [[ανθρωπον]{.greek-abbr}]{.greek-added} εαν τον κοσμον ολον κερδηση την δε ψυχην αυτου ζημιωθη η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο υιος του [ανθρωπου]{.greek-abbr} ερχεσθαι εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων αυτου και τοτε αποδωσει εκαστω κατα την πραξιν αυτου[16:27]{.aside}

αμην λεγω υμιν [οτι]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες [των]{.greek-added} ωδε [εστωτες]{.greek-omitted} [εστωτων]{.greek-added} οιτινες ου μη [γευσωνται]{.greek-omitted} [γευσονται]{.greek-added} θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου και αναφερει αυτους εις ορος [υψηλον]{.greek-omitted} [υψιλον]{.greek-added} κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και [ελαμψεν]{.greek-omitted} [ελαμψε]{.greek-added} το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} λευκα ως το φως[17:2]{.aside}

και ιδου ωφθησαν αυτοις μωσης και ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

αποκριθεις δε ο πετρος ειπεν [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι ει [θελεις]{.greek-omitted} [θελης]{.greek-added} [ποιησωμεν]{.greek-omitted} [ποιεισωμεν]{.greek-added} ωδε τρεις σκηνας [σοι]{.greek-omitted} [συ]{.greek-added} μιαν και μωση μιαν και [ηλια]{.greek-added} μιαν [ηλια]{.greek-omitted}[17:4]{.aside}

ετι [δε]{.greek-added} αυτου λαλουντος ιδου νεφελη [φωτεινη]{.greek-omitted} [φωτινη]{.greek-added} επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο υιος μου ο αγαπητος εν ω ευδοκησα αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται επεσον επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν εγερθητε και μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added}[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινοντων αυτων εκ του [ορους]{.greek-omitted} [ωρους]{.greek-added} ενετειλατο αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι ειπητε το οραμα εως ου ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων [αναστη]{.greek-omitted} [εγερθη]{.greek-added}[17:9]{.aside}

και επηρωτησαν αυτον οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν [δει]{.greek-omitted} [δη]{.greek-added} ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-omitted} αποκριθεις ειπεν αυτοις ηλιας μεν ερχεται πρωτον και αποκαταστησει παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας ηδη ηλθεν και ουκ επεγνωσαν αυτον αλλα εποιησαν [εν]{.greek-omitted} [αυτη]{.greek-added} [αυτω]{.corr} οσα ηθελησαν ουτως και ο υιος του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων αυτων προς τον οχλον προσηλθεν αυτω [ανθρωπος]{.greek-abbr} γονυπετων αυτον[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι [σεληνιαζεται]{.greek-omitted} [σελινιαζεται]{.greek-added} και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και [προσηνεγκα]{.greek-omitted} [προσηνεγκαν]{.greek-added} αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν αυτον θεραπευσαι[17:16]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε εσομαι μεθ υμων εως ποτε ανεξομαι υμων φερετε μοι αυτον ωδε[17:17]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε [προσελθοντες]{.greek-omitted} [προσελθωντες]{.greek-added} οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην γαρ λεγω υμιν εαν [εχητε]{.greek-omitted} [εχειτε]{.greek-added} πιστιν ως κοκκον σιναπεως ερειτε τω ορει τουτω [μεταβηθι]{.greek-omitted} [μεταβηθη]{.greek-added} εντευθεν εκει και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

αναστρεφομενων δε αυτων εν τη γαλιλαια ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα εγερθησεται και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε αυτων εις καπερναουμ προσηλθον οι τα διδραχμα λαμβανοντες τω πετρω και ειπον ο διδασκαλος υμων ου τελει τα διδραχμα[17:24]{.aside}

λεγει ναι και οτε εισηλθεν εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι [βα]{.greek-added} [βασιλεις]{.greek-omitted} [σιλεις]{.greek-added} της γης απο τινων [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} τελη η κηνσον απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

λεγει αυτω ο πετρος απο των αλλοτριων εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις την θαλασσαν βαλε αγκιστρον και τον αναβαινοντα πρωτον ιχθυν αρον και ανοιξας το στομα αυτου ευρησεις στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ωρα προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες τις αρα [μειζων]{.greek-omitted} [μειζον]{.greek-added} εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη [στραφητε]{.greek-omitted} [στραφηται]{.greek-added} και [γενησθε]{.greek-omitted} [γενεισθε]{.greek-added} ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο ουτος εστιν ο μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος εαν δεξηται παιδιον [τοιουτον]{.greek-omitted} [τοιουτο]{.greek-added} [εν]{.greek-omitted} επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν [σκανδαλιση]{.greek-omitted} [σκανδαλησει]{.greek-added} ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος εις τον [τραχηλον]{.greek-omitted} [τραχιλον]{.greek-added} αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

ει δε η χειρ σου η ο πους σου σκανδαλιζει σε εκκοψον αυτα και βαλε απο σου καλον σοι εστιν [εισελθειν]{.greek-omitted} εις την ζωην [εισελθειν]{.greek-added} χωλον η κυλλον η δυο [χειρας]{.greek-omitted} [ποδας]{.greek-added} η δυο [ποδας]{.greek-omitted} [χειρας]{.greek-added} εχοντα βληθηναι [εις]{.unclear} το πυρ το αιωνιον[18:8]{.aside}

και [ει]{.greek-omitted} [η]{.greek-added} ο οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι εστιν μονοφθαλμον [[εισελθειν]{.unclear}]{.greek-added} εις την ζωην εισελθειν η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

[ο]{.unclear}ρατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} το προσωπον του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:10]{.aside}

ηλθεν γαρ ο υιος του [ανθρωπου]{.greek-abbr} σωσαι το απολωλος [και]{.greek-added} [ζησεται]{.greek-added}[18:11]{.aside}

[τι]{.greek-omitted} [οτι]{.greek-added} [ημιν]{.greek-added} [υμιν]{.corr} [δοκει]{.greek-omitted} [δοκη]{.greek-added} εαν γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα [ενενηκοντα]{.greek-omitted} [ενενικοντα]{.greek-added} εννεα επι τα [ορη]{.greek-omitted} [ορει]{.greek-added} πορευθεις ζητει το [πλανωμενον]{.greek-omitted} [πλανομενον]{.greek-added}[18:12]{.aside}

και εαν γενηται ευρειν [αυτο]{.greek-omitted} [αυτω]{.greek-added} αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η επι τοις [ενενηκοντα]{.greek-omitted} [ενενικοντα]{.greek-added} εννεα τοις μη πεπλανημενοις[18:13]{.aside}

ουτως ουκ εστιν θελημα εμπροσθεν του [πατρος]{.greek-abbr} υμων του εν [ουρανοις]{.greek-abbr} ινα αποληται [εις]{.greek-omitted} [εν]{.greek-added} των μικρων τουτων[18:14]{.aside}

εαν δε αμαρτηση εις σε ο αδελφος σου υπαγε και ελεγξον αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε [σου]{.greek-added} μη ακουση παραλαβε μετα [σου]{.greek-omitted} [σεαυτου]{.greek-added} ετι [ενα]{.greek-omitted} [εναι]{.greek-added} η δυο ινα επι στοματος δυο μαρτυρων η τριων [σταθη]{.greek-omitted} [σταθησεται]{.greek-added} παν ρημα[18:16]{.aside}

εαν δε [και]{.greek-added} [τουτων]{.greek-added} παρακουση [αυτων]{.greek-omitted} ειπε τη εκκλησια εαν δε και της εκκλησιας παρακουση εστω σοι ωσπερ ο εθνικος και ο τελωνης[18:17]{.aside}

αμην λεγω υμιν οσα εαν δησητε επι της γης εσται δεδεμενα εν [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [τοις]{.greek-added} [[ουρανοις]{.greek-abbr}]{.greek-added} και οσα εαν λυσητε επι της γης εσται λελυμενα εν [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [τοις]{.greek-added} [[ουρανοις]{.greek-abbr}]{.greek-added}[18:18]{.aside}

παλιν [αμην]{.greek-omitted} [δε]{.greek-added} λεγω υμιν οτι εαν δυο [συμφωνισωσιν]{.greek-added} [εξ]{.greek-added} υμων [συμφωνησωσιν]{.greek-omitted} επι της γης περι παντος πραγματος ου εαν αιτησωνται γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:19]{.aside}

ου γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο η τρεις συνηγμενοι εις το εμον ονομα εκει ειμι εν μεσω αυτων[18:20]{.aside}

τοτε προσελθων [αυτω]{.greek-omitted} ο πετρος ειπεν [αυτω]{.greek-added} [κυριε]{.greek-abbr} [ποσακις]{.greek-omitted} [πωσακις]{.greek-added} [αμαρτησει]{.greek-omitted} [αμαρτισει]{.greek-added} εις εμε ο αδελφος μου και αφησω [αυτω]{.greek-omitted} [αυτον]{.greek-added} εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} ου λεγω σοι εως επτακις [α]{.greek-added} [αλλ]{.greek-omitted} [λλ]{.greek-added} εως εβδομηκοντακις επτα[18:22]{.aside}

δια τουτο ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος [ηθελησεν]{.greek-omitted} [ηθελησε]{.greek-added} συναραι λογον μετα των δουλων αυτου[18:23]{.aside}

αρξαμενου δε αυτου [συναιρειν]{.greek-omitted} [συνερειν]{.greek-added} προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν αυτον ο [κυριος]{.greek-abbr} αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα [ειχεν]{.greek-omitted} [εχει]{.greek-added} και αποδοθηναι[18:25]{.aside}

πεσων ουν ο δουλος [εκεινος]{.greek-added} [προσεκυνει]{.greek-omitted} [προσεκυνη]{.greek-added} αυτω λεγων [κυριε]{.greek-abbr} μακροθυμησον επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο [κυριος]{.greek-abbr} του δουλου εκεινου απελυσεν αυτον και το δανειον αφηκεν αυτω[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον δηναρια και κρατησας αυτον [επνιγεν]{.greek-omitted} [επνιγε]{.greek-added} λεγων αποδος μοι ει τι οφειλεις[18:28]{.aside}

πεσων ουν ο συνδουλος αυτου εις τους ποδας αυτου παρεκαλει αυτον λεγων μακροθυμησον επ εμοι και [παντα]{.greek-added} αποδωσω σοι[18:29]{.aside}

ο δε ουκ [ηθελεν]{.greek-omitted} [ηθελησεν]{.greek-added} αλλα απελθων εβαλεν αυτον εις φυλακην εως ου αποδω [παν]{.greek-added} το οφειλομενον [αυτω]{.greek-added}[18:30]{.aside}

ιδοντες δε οι συνδουλοι αυτου [παντα]{.greek-added} [τα]{.unclear} γενομενα ελυπηθησαν σφοδρα και ελθοντες διεσαφησαν τω [κυριω]{.greek-abbr} εαυτων παντα τα γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο [κυριος]{.greek-abbr} αυτου λεγει αυτω δουλε πονηρε πασαν την [οφειλην]{.greek-omitted} [οφειλειν]{.greek-added} εκεινην αφηκα σοι επει παρεκαλεσας με[18:32]{.aside}

ουκ [εδει]{.greek-omitted} [ειδη]{.greek-added} και σε ελεησαι τον συνδουλον σου ως [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} σε ηλεησα[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} αυτου παρεδωκεν αυτον τοις βασανισταις εως ου αποδω παν το οφειλομενον αυτω[18:34]{.aside}

ουτως και ο [πατηρ]{.greek-abbr} [μου]{.greek-omitted} [υμων]{.greek-added} ο [επουρανιος]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} ποιησει υμιν εαν μη αφητε εκαστος τω αδελφω αυτου απο των καρδιων υμων τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και προσηλθον αυτω οι φαρισαιοι [πειραζοντες]{.greek-omitted} [πειραζωντες]{.greek-added} αυτον και λεγοντες [αυτω]{.greek-omitted} ει εξεστιν [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε [αποκριθεις]{.greek-omitted} ειπεν αυτοις ουκ ανεγνωτε οτι ο ποιησας απ αρχης αρσεν και [θηλυ]{.greek-omitted} [θηλαι]{.greek-added} εποιησεν αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταληψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-added} και την [μητερα]{.greek-abbr} και προσκολληθησεται τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} συνεζευξεν ανθρωπος μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν μωσης ενετειλατο δουναι βιβλιον αποστασιου και απολυσαι αυτην[19:7]{.aside}

λεγει αυτοις οτι μωσης προς την σκληροκαρδιαν υμων επετρεψεν υμιν απολυσαι τας γυναικας υμων απ αρχης δε ου γεγονεν ουτως[19:8]{.aside}

λεγω δε υμιν οτι ος αν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την [γυναικα]{.greek-omitted} [γυναικαν]{.greek-added} αυτου μη επι πορνεια και [γαμηση]{.greek-omitted} [γαμιση]{.greek-added} αλλην μοιχαται και ο [απολελυμενην]{.greek-omitted} [απολελυμενον]{.greek-added} [γαμησας]{.greek-omitted} [γαμων]{.greek-added} μοιχαται[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτως εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφερει γαμησαι[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες [χωρουσιν]{.greek-omitted} [χωρουσι]{.greek-added} τον λογον τουτον αλλ οις δεδοται[19:11]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ ευνουχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} εγεννηθησαν ουτως και εισιν ευνουχοι οιτινες ευνουχισθησαν υπο των [ανθρωπων]{.greek-abbr} και εισιν ευνουχοι οιτινες ευνουχισαν εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε προσηνεχθη αυτω παιδια ινα τας χειρας επιθη αυτοις και προσευξηται οι δε μαθηται επετιμησαν αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-added} αφετε τα παιδια και μη [κωλυετε]{.greek-omitted} [κολυετε]{.greek-added} αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και επιθεις αυτοις τας χειρας επορευθη εκειθεν[19:15]{.aside}

και ιδου εις προσελθων ειπεν αυτω διδασκαλε αγαθε τι αγαθον ποιησω ινα [εσχω]{.greek-added} [εχω]{.corr} ζωην αιωνιον[19:16]{.aside}

ο δε ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr} ει δε [θελεις]{.greek-omitted} [θελης]{.greek-added} εισελθειν εις την ζωην τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} ειπεν το ου φονευσεις ου μοιχευσεις ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} και αγαπησεις τον πλησιον σου ως σεαυτον[19:19]{.aside}

λεγει αυτω ο νεανισκος [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} εφυλαξαμην εκ νεοτητος μου [τι]{.greek-omitted} [οτι]{.greek-added} ετι υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελεις τελειος ειναι υπαγε πωλησον σου τα υπαρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον απηλθεν [λυπουμενος]{.greek-omitted} [λοιπουμενος]{.greek-added} ην γαρ εχων κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως πλουσιος εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν δε λεγω υμιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [τρυπηματος]{.greek-omitted} [τρυμαλιας]{.greek-added} ραφιδος διελθειν η [πλουσιον]{.greek-omitted} [πλουσιος]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[19:24]{.aside}

ακουσαντες δε οι μαθηται [αυτου]{.greek-omitted} εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

εμβλεψας δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα δε [θεω]{.greek-abbr} παντα δυνατα[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται [ημιν]{.greek-omitted} [υμιν]{.greek-added}[19:27]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτοις αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη [παλιγγενεσια]{.greek-omitted} [παλιγγεννεσια]{.greek-added} οταν [καθιση]{.greek-omitted} [καθησει]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου [καθισεσθε]{.greek-omitted} [καθησεσθαι]{.greek-added} και υμεις επι δωδεκα θρονους κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας [ος]{.greek-omitted} [οστις]{.greek-added} αφηκεν οικιας η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [[μραν]{.greek-abbr}]{.greek-added} [μητερα]{.greek-omitted} [η]{.greek-omitted} [γυναικα]{.greek-omitted} η τεκνα η αγρους [ενεκεν]{.greek-omitted} [ενεκε]{.greek-added} του ονοματος μου [εκατονταπλασιονα]{.greek-omitted} [εκατονταπλασιωνα]{.greek-added} ληψεται και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[19:30]{.aside}

### Chapter 20

[ομοια]{.greek-omitted} [ομοιως]{.greek-added} γαρ εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

[και]{.greek-omitted} συμφωνησας [δε]{.greek-added} μετα των εργατων εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι τριτην ωραν ειδεν αλλους εστωτας εν τη [αγορα]{.greek-omitted} [αγωρα]{.greek-added} αργους[20:3]{.aside}

και εκεινοις ειπεν υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν [δε]{.greek-added} εξελθων περι εκτην και ενατην ωραν εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας [εμισθωσατο]{.greek-omitted} [εμισθωσατω]{.greek-added} λεγει αυτοις υπαγετε και υμεις εις τον αμπελωνα και ο εαν η δικαιον [ληψεσθε]{.greek-omitted} [ληψεσθαι]{.greek-added}[20:7]{.aside}

οψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω [αυτου]{.greek-omitted} [αυτω]{.greek-added} καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν [ελαβον]{.greek-omitted} [ελαβων]{.greek-added} ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι [ενομισαν]{.greek-omitted} [ενομησαν]{.greek-added} οτι [πλειονα]{.greek-omitted} [πληωνα]{.greek-added} [ληψονται]{.greek-omitted} [λειψονται]{.greek-added} και [ελαβον]{.greek-omitted} [ελαβων]{.greek-added} και αυτοι ανα δηναριον[20:10]{.aside}

λαβοντες δε [εγογγυζον]{.greek-omitted} [διεγογγυζον]{.greek-added} κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι [ουτοι]{.greek-omitted} [ουτος]{.greek-added} οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις [βαστασασιν]{.greek-omitted} [βαστασασι]{.greek-added} το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων εταιρε ουκ αδικω σε ουχι δηναριου συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε τουτω τω εσχατω δουναι ως και σοι[20:14]{.aside}

η ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι ποιησαι ο θελω εν τοις εμοις ει ο οφθαλμος σου πονηρος εστιν οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι εσχατοι πρωτοι και οι πρωτοι εσχατοι πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

και αναβαινων [εις]{.greek-added} [ιεροσολυμα]{.greek-added} ο [ιησους]{.greek-abbr} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} τους δωδεκα μαθητας κατ ιδιαν εν τη οδω και ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} [παραδοθησεται]{.greek-omitted} [παραδωθησεται]{.greek-added} τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω[20:18]{.aside}

και παραδωσουσιν αυτον τοις εθνεσιν εις το εμπαιξαι και [μαστιγωσαι]{.greek-omitted} [μαστηγοσαι]{.greek-added} και [σταυρωσαι]{.greek-abbr} και τη τριτη ημερα [αναστησεται]{.greek-omitted} [εγερθησεται]{.greek-added}[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυν[ου]{.unclear}σα και αιτουσα [τι]{.greek-omitted} παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι [θελεις]{.greek-omitted} [θελης]{.greek-added} [ο]{.greek-added} [δε]{.greek-added} λεγει αυτω ειπε ινα [καθισωσιν]{.greek-omitted} [καθησωσιν]{.greek-added} ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι αιτεισθε δυνασθε [πιειν]{.greek-omitted} [ποιειν]{.greek-added} το ποτηριον ο εγω μελλω πινειν η το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου [πιεσθε]{.greek-omitted} [πιεσθαι]{.greek-added} και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} μου ουκ εστιν εμον [τουτο]{.greek-added} δουναι αλλ οις ητοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως δε εσται εν [υμιν]{.greek-omitted} [ημιν]{.greek-added} αλλ ος εαν θελη εν υμιν μεγας γενεσθαι εσται υμων διακονος[20:26]{.aside}

και ος εαν θελη εν υμιν ειναι πρωτος [εστω]{.greek-omitted} [εσται]{.greek-added} υμων δουλος[20:27]{.aside}

[ωσπερ]{.greek-omitted} [και]{.greek-added} [γαρ]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και εκπορευομενων αυτων απο ιεριχω ηκολουθησεν αυτω οχλος πολυς[20:29]{.aside}

και ιδου δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

ο δε οχλος [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} αυτοις ινα σιωπησωσιν οι δε [μειζον]{.greek-omitted} [μειζων]{.greek-added} [εκραζον]{.greek-omitted} [εκραζων]{.greek-added} λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-abbr} εφωνησεν αυτους και ειπεν τι θελετε ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-abbr} ινα ανοιχθωσιν ημων οι οφθαλμοι[20:33]{.aside}

σπλαγχνισθεις δε ο [ιησους]{.greek-abbr} [ηψατο]{.greek-omitted} [ηψατω]{.greek-added} των οφθαλμων αυτων και ευθεως ανεβλεψαν [αυτων]{.greek-omitted} [οι]{.greek-omitted} [οφθαλμοι]{.greek-omitted} και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε [ηγγισαν]{.greek-omitted} [ηγγισεν]{.greek-added} εις ιεροσολυμα και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} προς το ορος των [ελαιων]{.greek-omitted} [ελεων]{.greek-added} τοτε ο [ιησους]{.greek-abbr} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} δυο μαθητας[21:1]{.aside}

λεγων αυτοις [πορευθητε]{.greek-omitted} [πορευθηται]{.greek-added} εις την κωμην την απεναντι υμων και ευθεως [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο [κυριος]{.greek-abbr} αυτων χρειαν εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και επιβεβηκως επι ονον και πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες [καθως]{.greek-omitted} [προσεταξεν]{.greek-omitted} [καθα]{.greek-added} [συνεταξεν]{.greek-added} αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και τον πωλον και επεθηκαν επανω αυτων τα ιματια αυτων και [επεκαθισεν]{.greek-omitted} [επεκαθησεν]{.greek-added} επανω αυτων[21:7]{.aside}

ο δε [πλειστος]{.greek-omitted} [πληστος]{.greek-added} οχλος εστρωσαν εαυτων τα ιματια εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και εστρωννυον εν τη οδω[21:8]{.aside}

οι δε οχλοι οι [προαγοντες]{.greek-omitted} [προαγωντες]{.greek-added} και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

και εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον του [θεου]{.greek-abbr} και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} παντας τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο οικος μου οικος προσευχης κληθησεται υμεις δε αυτον εποιησατε σπηλαιον ληστων[21:13]{.aside}

και [προσηλθον]{.greek-omitted} [προσηλ]{.greek-added} [θον]{.greek-added} αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α εποιησεν και τους παιδας [κραζοντας]{.greek-omitted} [κραζωντας]{.greek-added} εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω [ουκ]{.greek-added} ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων κατηρτισω αινον[21:16]{.aside}

και [καταλιπων]{.greek-omitted} [καταλειπων]{.greek-added} αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη εκει[21:17]{.aside}

πρωιας δε επαναγων εις την πολιν [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει μη φυλλα μονον και λεγει αυτη [μηκετι]{.greek-omitted} [μηκετη]{.greek-added} εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη παραχρημα η συκη[21:19]{.aside}

και ιδ[ο]{.unclear}ντες οι μαθηται [αυτου]{.greek-added} εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν εχητε πιστιν και μη διακριθητε ου μονον το της συκης [ποιησετε]{.greek-omitted} [ποιησητε]{.greek-added} αλλα καν [τω]{.greek-omitted} [το]{.greek-added} ορει τουτω ειπητε αρθητι και βληθητι εις την θαλασσαν [και]{.greek-added} γενησεται[21:21]{.aside}

και παντα οσα [εαν]{.greek-omitted} [αν]{.greek-added} αιτησητε εν τη προσευχη πιστευοντες [ληψεσθε]{.greek-omitted} [ληψεσθαι]{.greek-added}[21:22]{.aside}

και ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} εν ποια εξουσια ταυτα ποιεις και τις σοι [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω υμας καγω [ενα]{.greek-added} λογον [ενα]{.greek-omitted} ον εαν ειπητε μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο παρ εαυτοις [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει ημιν δια τι ουν ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ως προφητην[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} ειπον ουκ οιδαμεν εφη αυτοις και αυτος ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} [τις]{.greek-added} ειχεν τεκνα δυο και προσελθων τω πρωτω ειπεν τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε [μεταμεληθεις]{.greek-omitted} [μεταμελιθεις]{.greek-added} απηλθεν[21:29]{.aside}

και προσελθων τω [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν ωσαυτως ο δε αποκριθεις ειπεν εγω [κυριε]{.greek-abbr} και ουκ απηλθεν[21:30]{.aside}

τις εκ των δυο [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} το [θε]{.greek-added} [θελημα]{.greek-omitted} [λημα]{.greek-added} του [πατρος]{.greek-abbr} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

ηλθεν γαρ προς υμας [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω οι δε τελωναι και αι πορναι επιστευσαν αυτω υμεις δε ιδοντες ου μετεμεληθητε υστερον του πιστευσαι αυτω[21:32]{.aside}

αλλην παραβολην ακουσατε [ανθρωπος]{.greek-abbr} τις ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} και ωρυξεν εν αυτω ληνον και ωκοδομησεν πυργον και [εξεδοτο]{.greek-omitted} [εξεδωτο]{.greek-added} αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε ηγγισεν ο καιρος των καρπων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους [πλειονας]{.greek-omitted} [πλειωνας]{.greek-added} των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους τον υιον αυτου λεγων εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και [κατασχωμεν]{.greek-omitted} [κατασχο]{.greek-added} [μεν]{.greek-added} την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι [ποιησει]{.greek-omitted} [ποιειση]{.greek-added} τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα [εκδωσεται]{.greek-omitted} [εκδωσουσιν]{.greek-added} [αυτω]{.greek-added} [αλλοις]{.corr} [γεωργοις]{.corr} [οιτινες]{.corr} [αποδωσουσιν]{.corr} [αυτω]{.corr} τους καρπους εν τοις [καιροις]{.greek-omitted} [κεροις]{.greek-added} αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε ανεγνωτε εν ταις γραφαις λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδοκημασαν]{.greek-added} οι οικοδομουντες ουτος εγενηθη εις κεφαλην [γωνιας]{.greek-omitted} [γονιας]{.greek-added} παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστη]{.greek-added} θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται [εθνει]{.greek-omitted} [εθνη]{.greek-added} ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση λικμησει αυτον[21:44]{.aside}

και [οι]{.greek-added} ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παρα[βο]{.unclear}λας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους επειδη ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} παλιν ειπεν [αυτοις]{.greek-omitted} εν παραβολαις [αυτοις]{.greek-added} λεγων[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω αυτου[22:2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου [καλεσαι]{.greek-omitted} [καλεσε]{.greek-added} τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου [ητοιμασα]{.greek-omitted} [ητοιμακα]{.greek-added} οι ταυροι μου και τα σιτιστα τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον [ο]{.greek-omitted} [ος]{.greek-added} μεν εις τον ιδιον αγρον [ο]{.greek-omitted} [ος]{.greek-added} δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι κρατησαντες τους δουλους αυτου υβρισαν και απεκτειναν[22:6]{.aside}

[και]{.greek-omitted} [ακουσας]{.greek-omitted} ο [δε]{.greek-added} βασιλευς [εκεινος]{.greek-omitted} [ωργισθη]{.greek-omitted} [οργισθη]{.greek-added} και πεμψας τα στρατευματα αυτου [απωλεσεν]{.greek-omitted} [απωλεσε]{.greek-added} τους [φονεις]{.greek-omitted} [φωνεις]{.greek-added} εκεινους και την πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενεπρισεν]{.greek-added}[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον παντας οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς [θεασασθαι]{.greek-omitted} [θεασασθε]{.greek-added} τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει [αυτω]{.greek-omitted} [αυτων]{.greek-added} εταιρε πως εισηλθες ωδε μη εχω[ν]{.unclear} [ε]{.unclear}νδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις [δια]{.greek-added} [διακονοις]{.greek-omitted} [κονοις]{.greek-added} δησαντες αυτου ποδας και χειρας [αρατε]{.greek-omitted} [εκβαλετε]{.greek-added} αυτον [και]{.greek-omitted} [εκβαλετε]{.greek-omitted} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον [ελαβον]{.greek-omitted} [ελαβων]{.greek-added} οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλωσιν]{.greek-added} αυτω τους μαθητας αυτων μετα των ηρωδιανων [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αλιθης]{.greek-added} ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι [κηνσον]{.greek-omitted} [κινσον]{.greek-added} καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων ειπεν τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του κηνσου οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

[λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} [ειπαν]{.greek-added} καισαρος τοτε λεγει αυτοις αποδοτε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι οι λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης ειπεν εαν τις αποθανη μη εχων τεκνα επιγαμβρευσει ο αδελφος αυτου την γυναικα αυτου και [αναστησει]{.greek-omitted} [εξαναστησει]{.greek-added} σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος γαμησας [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και μη εχων σπερμα [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[22:27]{.aside}

[εν]{.greek-omitted} [τη]{.greek-omitted} [ουν]{.greek-omitted} [αναστασει]{.greek-omitted} [τινος]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [εσται]{.greek-omitted} [γυνη]{.greek-omitted} παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις πλανα[σθε]{.unclear} μη ειδοτες τας γραφας μηδε την [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε [εκγαμιζονται]{.greek-omitted} [εκγαμιζωνται]{.greek-added} αλλ ως αγγελοι [του]{.greek-omitted} [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} εισιν[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν [υμιν]{.greek-omitted} [ημιν]{.greek-added} υπο του [θεου]{.greek-abbr} [λεγοντος]{.greek-omitted} [λεγωντος]{.greek-added}[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημωσε]{.greek-added} τους σαδδουκαιους συνηχθησαν επι [το]{.greek-omitted} [τω]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added}[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη [τη]{.greek-added} καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων [επηρωτησεν]{.greek-omitted} [επερωτησεν]{.greek-added} αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} καλει αυτον [κυριον]{.greek-abbr} πως υιος αυτου [εστιν]{.greek-omitted}[22:45]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} [αποκριθηναι]{.greek-added} αυτω [αποκριθηναι]{.greek-omitted} λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας [επερωτησαι]{.greek-omitted} [επερωτισαι]{.greek-added} αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και ποιειτε κατα δε τα εργα αυτων μη ποιειτε [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} γαρ φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων ποιουσιν προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} [δε]{.greek-omitted} [γαρ]{.greek-added} τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} την [πρωτοκλισιαν]{.greek-omitted} [πρωτοκλησιαν]{.greek-added} εν τοις δειπνοις και τας πρωτοκαθεδριας εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι ραββι[23:7]{.aside}

υμεις δε μη κληθητε ραββι εις γαρ [εστιν]{.greek-omitted} υμων [ο]{.greek-omitted} [καθηγητης]{.greek-omitted} [εστι]{.greek-added} [διδασκαλος]{.greek-added} ο [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε υμων επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr}[23:9]{.aside}

μηδε κληθητε καθηγηται εις γαρ [εστιν]{.greek-added} υμων [εστιν]{.greek-omitted} [ο]{.greek-omitted} καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειεται]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χειρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθαι]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι περιαγετε την θαλασσαν και την ξηραν [ποιησαι]{.greek-omitted} [ποιεισαι]{.greek-added} ενα προσηλυτον και οταν γενηται [ποιειτε]{.greek-omitted} [ποιειται]{.greek-added} αυτον [υιον]{.greek-abbr} γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν ομοση εν τω [ναω]{.greek-omitted} [ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [ομοση]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} χρυσω του ναου [οφειλει]{.greek-omitted} [οφειλη]{.greek-added}[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζ[ων]{.greek-supplied} εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} ομοση εν τω θυσιαστηριω ουδεν εστιν ος δ αν ομοση εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι τι γαρ μειζον το δωρον [η]{.greek-omitted} [το]{.greek-omitted} [θυσιαστηριον]{.greek-omitted} [το]{.greek-omitted} [αγιαζον]{.greek-omitted} [το]{.greek-omitted} [δωρον]{.greek-omitted}[23:19]{.aside}

ο ουν ομοσας εν τω θυσιαστηριω ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο ομοσας εν τω ναω ομνυει εν αυτω και εν τω κατοικησαντι αυτον[23:21]{.aside}

και ο ομοσας εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι αποδεκατουτε το ηδυοσμον και το ανηθον και το κυμινον και αφηκατε τα βαρυτερα του νομου την κρισιν και [τον]{.greek-omitted} [το]{.greek-added} [ελεον]{.greek-omitted} [ελαιον]{.greek-added} και την πιστιν ταυτα εδει [ποιησαι]{.greek-omitted} [ποιεισαι]{.greek-added} κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον κωνωπα την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι καθαριζετε το εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν [εξ]{.greek-omitted} αρπαγης και αδικιας[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα [γενηται]{.greek-omitted} [γενητε]{.greek-added} και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι παρομοιαζετε ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

ουτως και υμεις εξωθεν μεν φαινεσθε τοις ανθρωποις δικαιοι εσωθεν δε [μεστοι]{.greek-omitted} εστε υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [οικοδομειτε]{.greek-omitted} [οικοδομητε]{.greek-added} τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει ημεν εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν ημεν [αυτων]{.greek-added} κοινωνοι [αυτων]{.greek-omitted} εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις [πληρωσατε]{.greek-omitted} [επληρωσατε]{.greek-added} το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις [γεννηματα]{.greek-omitted} [γενηματα]{.greek-added} εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και [σταυρωσετε]{.greek-abbr} και εξ αυτων [μαστιγωσετε]{.greek-omitted} [μαστηγωσετε]{.greek-added} εν ταις συναγωγαις υμων και διωξετε απο πολ[ε]{.unclear}ως εις πολιν[23:34]{.aside}

οπως ελθη εφ υμας παν αιμα δικαιον εκχυνομενον [επι]{.greek-omitted} [απο]{.greek-added} της γης απο [τ]{.unclear}ου αιματος αβελ του [δι]{.greek-added} [δικαιου]{.greek-omitted} [καιου]{.greek-added} εως του αιματος ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεινουσα]{.greek-added} τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον τροπον [ορνις]{.greek-added} επισυναγει [ορνις]{.greek-omitted} τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη με ιδητε απ αρτι εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} [εκ]{.greek-added} [επορευετο]{.greek-omitted} [απο]{.greek-omitted} του ιερου [επορευετο]{.greek-added} και προσηλθον [αυτω]{.greek-added} οι μαθηται αυτου επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-omitted} [αποκριθεις]{.greek-added} ειπεν αυτοις ου βλεπετε [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου [μη]{.greek-added} καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται [αυτου]{.greek-added} κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} [οτι]{.greek-added} εγω ειμι ο [χριστος]{.greek-abbr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added}[24:5]{.aside}

μελλησετε δε ακουειν πολεμους και ακοας πολεμων ορατε μη θροεισθε δει γαρ [παντα]{.greek-omitted} γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εστι]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και λοιμοι και σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα αρχη [ωδινων]{.greek-omitted} [ωδηνων]{.greek-added}[24:8]{.aside}

τοτε παραδωσουσιν υμας εις [θλιψιν]{.greek-omitted} [θλιψεις]{.greek-added} και αποκτενουσιν υμας και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μισουμενοι υπο παντων των εθνων δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} και [μισησουσιν]{.greek-omitted} [μησησουσιν]{.greek-added} αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται τουτο το ευαγγελιον της βασιλειας [εν]{.greek-omitted} [εις]{.greek-added} [ολη]{.greek-omitted} [ολην]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [οικουμενη]{.greek-omitted} [οικουμενην]{.greek-added} εις μαρτυριον [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν ιδητε το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου εστως εν τοπω αγιω ο αναγινωσκων νοειτω[24:15]{.aside}

τοτε οι εν τη [ι[―]{.gap}υδαια]{.greek-added} [ιουδαια]{.corr} φευγετωσαν [επι]{.greek-omitted} [εις]{.greek-added} τα ορη[24:16]{.aside}

ο επι του δωματος μη [καταβαινετω]{.greek-omitted} [καταβατω]{.greek-added} αραι τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω [εις]{.greek-added} [τα]{.greek-added} οπισω αραι [τα]{.greek-omitted} [το]{.greek-added} [ιματια]{.greek-omitted} [ιματιον]{.greek-added} αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη [γενηται]{.greek-omitted} [γενητε]{.greek-added} η φυγη υμων χειμωνος μηδε [σαββατω]{.greek-omitted} [σαββατου]{.greek-added}[24:20]{.aside}

εσται γαρ τοτε θλιψις μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν ουδ ου μη [γενηται]{.greek-omitted} [γενητε]{.greek-added}[24:21]{.aside}

και ει μη εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους κολοβωθησονται αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις [υμιν]{.greek-omitted} [ειμιν]{.greek-added} ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ [ψευδοχριστοι]{.greek-omitted} [ψευδοχρηστοι]{.greek-added} και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουση]{.greek-added} σημεια μεγαλα και τερατα ωστε πλανησαι [ει]{.greek-omitted} [η]{.greek-added} δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω [εστιν]{.greek-omitted} [εστι]{.greek-added} μη εξελθητε [η]{.greek-added} ιδου εν τοις ταμειοις μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ εαν η το πτωμα εκει συναχθησονται [και]{.greek-added} οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι [αστερες]{.greek-omitted} [αστεραις]{.greek-added} πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και [κοψονται]{.greek-added} τοτε [κοψονται]{.greek-omitted} πασαι αι φυλαι της γης και οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και αποστελει τους αγγελους αυτου μετα σαλπιγγος φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξει]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-abbr} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος αυτης [γενηται]{.greek-omitted} [γενητε]{.greek-added} απαλος και τα φυλλα [εκφυη]{.greek-omitted} [εκφυει]{.greek-added} γινωσκετε οτι εγγυς το θερος[24:32]{.aside}

ουτως και υμεις οταν ιδητε ταυτα παντα [γινομενα]{.greek-added} γινωσκετε οτι εγγυς εστιν επι θυραις[24:33]{.aside}

αμην λεγω υμιν ου μη παρελθη η γενεα αυτη εως [αν]{.greek-omitted} παντα ταυτα γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσονται οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[24:35]{.aside}

περι δε της ημερας εκεινης και ωρας ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} [ουδε]{.greek-added} [ο]{.greek-added} [υιος]{.greek-added} ει μη ο [πατηρ]{.greek-abbr} [μου]{.greek-omitted} μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις [προ]{.greek-omitted} [πρω]{.greek-added} του κατακλυσμου [τρωγοντες]{.greek-omitted} [τρωγονταις]{.greek-added} και πινοντες γαμουντες και εκγαμιζοντες αχρι ης ημερας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο [αληθουσαι]{.greek-omitted} [αλιθουσαι]{.greek-added} εν τω μυλωνι μια παραλαμβανεται και μια αφιεται[24:41]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε ποια ωρα ο [κυριος]{.greek-abbr} υμων ερχεται[24:42]{.aside}

[εκεινο]{.greek-omitted} [εκεινω]{.greek-added} δε γινωσκετε οτι ει [ηδει]{.greek-omitted} [ηδη]{.greek-added} ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν [ειασεν]{.greek-omitted} [ειασε]{.greek-added} [διορυγηναι]{.greek-omitted} [διαρυγηναι]{.greek-added} την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ετοιμοι οτι η ωρα ου δοκειτε ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα [εστιν]{.greek-omitted} [εστι]{.greek-added} ο πιστος δουλος και φρονιμος ον κατεστησεν ο [κυριος]{.greek-abbr} αυτου επι της [θεραπειας]{.greek-omitted} [θεραπιας]{.greek-added} αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [παση]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και [αρξηται]{.greek-omitted} [αρξητε]{.greek-added} τυπτειν τους συνδουλους εσθιειν [δε]{.greek-omitted} [τε]{.greek-added} και πινειν μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ [εαυτων]{.greek-omitted} [εαυτον]{.greek-added} ελαιον[25:3]{.aside}

αι δε φρονιμοι ελαβον ελαιον εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε ημιν εκ του ελαιου υμων οτι αι λαμπαδες ημων σβεννυνται[25:8]{.aside}

απεκριθησαν [δε]{.greek-omitted} αι φρονιμοι λεγουσαι μηποτε ουκ [αρκεση]{.greek-omitted} [αρκεσει]{.greek-added} ημιν και υμιν [πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} δε μαλλον προς τους [πωλουντας]{.greek-omitted} [πωλουν]{.greek-added} [τας]{.greek-added} και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι εισηλθον μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν [εν]{.greek-omitted} [η]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [ερχεται]{.greek-omitted}[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχ[ον]{.unclear}τα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως [δε]{.greek-added} και ο τα δυο [εκερδησεν]{.greek-omitted} [εκερδησε]{.greek-added} και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και [απεκρυψεν]{.greek-omitted} [απεκρυψε]{.greek-added} [το]{.greek-omitted} [τω]{.greek-added} αργυριον του [κυριου]{.greek-abbr} αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και [συναιρει]{.greek-omitted} [συνερει]{.greek-added} μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη δε αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [η]{.greek-added} πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε και [ο]{.greek-omitted} τα δυο ταλαντα λαβων ειπεν [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον [λ[αβ]{.unclear}ων]{.greek-added} [ειληφως]{.corr} ειπεν [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε [εχεις]{.greek-omitted} [εχης]{.greek-added} το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε ηδεις οτι θεριζω οπου ουκ [εσπειρα]{.greek-omitted} [ε[σπ]{.unclear}ηρα]{.greek-added} και συναγω οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε [βαλειν]{.greek-omitted} [λαβειν]{.greek-added} το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και [δοτε]{.greek-omitted} [δωτε]{.greek-added} [τω]{.greek-omitted} [το]{.greek-added} εχοντι τα δεκα ταλαντα[25:28]{.aside}

[τω]{.greek-omitted} [το]{.greek-added} γαρ εχοντι παντι [δοθησεται]{.greek-omitted} [δωθησεται]{.greek-added} και περισσευθησεται απο δε του μη εχοντος και ο εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον [εκβαλετε]{.greek-omitted} [εκβα]{.greek-added} [λετε]{.greek-added} εις το σκοτος το εξωτερον εκει [εσται]{.greek-omitted} [εστε]{.greek-added} ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες [ο]{.unclear}ι αγιοι αγγελοι μετ αυτου τοτε [καθισει]{.greek-omitted} [καθησει]{.greek-added} επι θρονου δοξης αυτου[25:31]{.aside}

και συναχθησεται εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε [με]{.greek-omitted} [μετ]{.greek-added} ξενος [ημην]{.greek-omitted} [ειμιν]{.greek-added} και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και επεσκεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} πεινωντα και εθρεψαμεν η [διψωντα]{.greek-omitted} [διψοντα]{.greek-added} και εποτισαμεν[25:37]{.aside}

ποτε δε σε ειδομεν ξενον και [συνηγαγομεν]{.greek-omitted} [συνηγαγωμεν]{.greek-added} η γυμνον και περιεβαλομεν[25:38]{.aside}

ποτε δε σε [ει]{.unclear}δομεν ασθενη η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και [απο]{.greek-added} [αποκριθεις]{.greek-omitted} [κριθεις]{.greek-added} ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου των ελαχιστων εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων [πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ [εποτισατε]{.greek-omitted} [εποτησατε]{.greek-added} με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε [με]{.greek-omitted} [γυμνος]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [περιεβαλετε]{.greek-omitted} με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ειδωμεν]{.greek-added} πεινωντα η διψωντα η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους ειπεν τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το σταυρωθηναι[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω [κρατησωσιν]{.greek-omitted} [κρατησωσι]{.greek-added} και αποκτεινωσιν[26:4]{.aside}

[ελεγον]{.greek-omitted} [ελεγων]{.greek-added} δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι [τοις]{.greek-added} πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους [παρεχετε]{.greek-omitted} [παρεχεται]{.greek-added} τη γυναικι εργον γαρ καλον ειργασατο εις εμε[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} τους πτωχους [γαρ]{.greek-added} [παντοτε]{.greek-added} εχετε μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το ενταφιασαι με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κ[ο]{.unclear}σμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

ειπεν τι θελετε μοι δουναι καγω υμιν [παραδωσω]{.greek-omitted} [παραδοσω]{.greek-added} αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε [εζητει]{.greek-omitted} [εζητη]{.greek-added} ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυμων προσηλθον οι μαθηται [τω]{.greek-omitted} [του]{.greek-added} [ιησου]{.greek-abbr} [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} αυτω που [θελεις]{.greek-omitted} [θελης]{.greek-added} [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς εστιν προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα[26:20]{.aside}

και εσθιοντων αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων παραδωσει με[26:21]{.aside}

και [λυπουμενοι]{.greek-omitted} [λοιπουμενοι]{.greek-added} σφοδρα ηρξαντο λεγειν [αυτω]{.greek-omitted} εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν ο εμβαψας μετ εμου εν τω [τρυβλιω]{.greek-omitted} [τριβλιω]{.greek-added} την χειρα ουτος με παραδωσει[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω [ει]{.greek-omitted} [η]{.greek-added} ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον ειπεν μητι εγω ειμι ραββι [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [συ]{.greek-omitted} [ειπας]{.greek-omitted}[26:25]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον και ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις και ειπεν λαβετε φαγετε τουτο [μου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα [μου]{.greek-omitted}[26:26]{.aside}

και λαβων το ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του [γεννηματος]{.greek-omitted} [γενηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν αυτο πινω μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις σκανδαλισθησεσθε εν εμοι εν τη [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} ταυτη γεγραπται γαρ παταξω τον ποιμενα και διασκορπισθησεται τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω [δε]{.greek-omitted} ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον γεθσημανη και λεγει τοις μαθηταις καθισατε αυτου εως ου απελθων [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added} εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους καθευδοντας και λεγει [αυτοις]{.greek-added} [τω]{.greek-omitted} [πετρω]{.greek-omitted} ουτως ουκ ισχυσατε μιαν ωραν γρηγορησαι μετ εμου[26:40]{.aside}

γρηγορειτε [ουν]{.greek-added} και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται τουτο το ποτηριον παρελθειν απ εμου εαν μη αυτο πιω γενηθητω το θελημα σου[26:42]{.aside}

και ελθων [ευρισκει]{.greek-omitted} [ευρεν]{.greek-added} αυτους παλιν καθευδοντας ησαν γαρ αυτων οι οφθαλμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας [αυτου]{.greek-omitted} και λεγει αυτοις καθευδετε το λοιπον και αναπαυεσθε ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας [των]{.greek-added} αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα ηλθεν και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων [απο]{.greek-omitted} [παρα]{.greek-added} των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον[26:48]{.aside}

και ευθεως προσελθων τω [ιησου]{.greek-abbr} ειπεν χαιρε ραββι και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ ω παρει τοτε προσελθοντες επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις [των]{.greek-omitted} [τον]{.greek-added} μετα [ιησου]{.greek-abbr} εκτεινα[ς]{.unclear} την χειρα [απεσπασεν]{.greek-omitted} [απεσπασε]{.greek-added} την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον σου την μαχαιραν εις τον τοπον αυτης παντες γαρ οι λαβοντες μαχαιραν εν μαχαιρα αποθανουνται[26:52]{.aside}

η δοκεις οτι ου [δυναμαι]{.greek-omitted} [δυναμε]{.greek-added} αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως [δει]{.greek-omitted} [δη]{.greek-added} γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι [ληστην]{.greek-omitted} [λιστην]{.greek-added} [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος [ηκολουθει]{.greek-omitted} [ηκωλουθει]{.greek-added} αυτω απο μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω [εκαθητο]{.greek-omitted} [εκαθητω]{.greek-added} μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και [ολον]{.greek-added} το συνεδριον [ολον]{.greek-omitted} εζητουν [ψευδομαρτυριαν]{.greek-omitted} [ψευδομαρτυρειαν]{.greek-added} κατα του [ιησου]{.greek-abbr} οπως θανατωσωσιν αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο [αρχιερευς]{.greek-omitted} [αρχιερεις]{.greek-added} ειπεν αυτω ουδεν [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω [εξορκιζω]{.greek-omitted} [εξορκι]{.greek-added} [ζω]{.greek-added} σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματια αυτου λεγων οτι [εβλασφημησεν]{.greek-omitted} [εβλασφημησε]{.greek-added} τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου [εστιν]{.greek-omitted} [εστι]{.greek-added}[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και [εκολαφισαν]{.greek-omitted} [εκολαφησαν]{.greek-added} αυτον οι δε [ερραπισαν]{.greek-omitted} [εραπισαν]{.greek-added} [αυτον]{.greek-added}[26:67]{.aside}

[λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο [παισας]{.greek-omitted} [πτεσας]{.greek-added} σε[26:68]{.aside}

ο δε πετρος [εξω]{.greek-omitted} [εκαθητο]{.greek-omitted} [εκαθητω]{.greek-added} [εσω]{.greek-added} εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε [ηρνησατο]{.greek-omitted} [ηρνησατω]{.greek-added} εμπροσθεν αυτων παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

[εξελθοντα]{.greek-omitted} [εξελθωντα]{.greek-added} δε [αυτον]{.greek-omitted} [αυτων]{.greek-added} εις τον πυλωνα ειδεν αυτον αλλη και λεγει αυτοις εκει και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες οι εστωτες [ειπον]{.greek-omitted} [ειπων]{.greek-added} τω πετρω αληθως και [συ]{.greek-omitted} [σοι]{.greek-added} εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος [του]{.greek-omitted} [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρα]{.greek-added} φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με και εξελθων εξω [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον [ελαβον]{.greek-omitted} [ελαβων]{.greek-added} παντες οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον [απηγαγον]{.greek-omitted} [απηγαγων]{.greek-added} και παρεδωκαν [αυτον]{.greek-omitted} ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε ιδων ιουδας ο παραδιδους αυτον οτι κατεκριθη [μεταμεληθεις]{.greek-omitted} [μεταμελιθεις]{.greek-added} [απεστρεψεν]{.greek-omitted} [απεστρεψε]{.greek-added} τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε ειπον τι προς ημας συ [οψει]{.greek-omitted} [οψη]{.greek-added}[27:4]{.aside}

και ριψας τα αργυρια εν τω [ναω]{.greek-omitted} ανεχωρησεν και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις [λαβοντες]{.greek-omitted} [λαβωντες]{.greek-added} τα αργυρια ειπον ουκ εξεστιν βαλειν αυτα εις τον [κορβαναν]{.greek-omitted} [κορβοναν]{.greek-added} επει [τιμη]{.greek-omitted} [τιμι]{.greek-added} αιματος [εστιν]{.greek-omitted} [εστι]{.greek-added}[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την [τι]{.greek-added} [τιμην]{.greek-omitted} [μην]{.greek-added} του τετιμημενου ον [ετιμησαντο]{.greek-omitted} [ετημησαντο]{.greek-added} απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και [εδωκαν]{.greek-omitted} [εδοκα]{.greek-added} αυτα εις τον αγρον του κεραμεως καθα συνεταξεν μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και των πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον ηγεμονα λιαν[27:14]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν ενα [τω]{.greek-omitted} [των]{.greek-added} οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος [απεστειλεν]{.greek-omitted} [απεστηλε]{.greek-added} προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ [επαθον]{.greek-omitted} [επαθων]{.greek-added} σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα αιτησωνται τον βαραββαν τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις [τινα]{.greek-omitted} [τι]{.greek-added} [να]{.greek-added} θελετε απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν αυτω παντες [σταυρωθητω]{.greek-abbr}[27:22]{.aside}

[λεγει]{.greek-added} [αυτοις]{.greek-added} ο [δε]{.greek-omitted} ηγεμων [εφη]{.greek-omitted} τι γαρ κακον εποιησεν οι δε περισσως [εκραζον]{.greek-omitted} [εκραζων]{.greek-added} [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} [σταυρωθητω]{.greek-abbr}[27:23]{.aside}

ιδων δε ο πιλατος οτι ουδεν ωφελει αλλα μαλλον θορυβος γινεται λαβων υδωρ [απενιψατο]{.greek-omitted} [απενηψατω]{.greek-added} τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος ειπεν το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} φραγελλωσας παρεδωκεν ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και [καλαμον]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [δεξιαν]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} γονυπετησαντες εμπροσθεν αυτου [ενεπαιζον]{.greek-omitted} [ενεπεξαν]{.greek-added} αυτω λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα ο εστιν [λεγομενος]{.greek-omitted} [μεθερμηνευομενον]{.greek-added} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης [μεμιγμενον]{.greek-omitted} [μεμηγμενον]{.greek-added} και γευσαμενος ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} πιειν[27:34]{.aside}

σταυρωσαντες δε αυτον [διεμερισαντο]{.greek-omitted} [διεμερησαντο]{.greek-added} τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-abbr} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουνται]{.greek-omitted} [[στρουντε]{.greek-abbr}]{.greek-added} συν αυτω δυο [λησται]{.greek-omitted} [λισται]{.greek-added} εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες [ουα]{.greek-added} ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} καταβηθι απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως δε και οι αρχιερεις [εμπαιζοντες]{.greek-omitted} [εμπεζωντες]{.greek-added} μετα των [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και πρεσβυτερων [και]{.greek-omitted} [φαρισαιων]{.greek-omitted} [ελεγον]{.greek-omitted} [ελεγων]{.greek-added}[27:41]{.aside}

αλλους εσωσεν εαυτον ου [δυναται]{.greek-omitted} [δυνατε]{.greek-added} σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} [ρυ]{.greek-added} [ρυσασθω]{.greek-omitted} [σασθω]{.greek-added} νυν αυτον ει θελει αυτον ειπεν γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ [αυτο]{.greek-omitted} [αυτω]{.greek-added} και οι [λησται]{.greek-omitted} [λισται]{.greek-added} οι [συσταυρωθεντες]{.greek-abbr} αυτω [ωνειδιζον]{.greek-omitted} [ονειδιζον]{.greek-added} αυτον[27:44]{.aside}

απο δε εκτης ωρας σκοτος εγενετο επι πασαν την γην εως ωρας ενατης[27:45]{.aside}

περι δε την ενατην ωραν [ανεβοησεν]{.greek-omitted} [αναβοησεν]{.greek-added} ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων [ηλι]{.greek-omitted} [ηλει]{.greek-added} [ηλι]{.greek-omitted} [ηλει]{.greek-added} [λιμα]{.greek-omitted} [λειμα]{.greek-added} σαβαχθανι τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου [θεε]{.greek-omitted} [μου]{.greek-omitted} [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με [εγκατελιπες]{.greek-omitted} [εγκατελειπες]{.greek-added}[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} οτι ηλιαν φωνει [ουτος]{.greek-omitted} [ουτως]{.greek-added}[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} αφες [ιδωμεν]{.greek-omitted} [ειδωμεν]{.greek-added} ει ερχεται ηλιας σωσων αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη εσεισθη και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια ανεωχθησαν και πολλα σωματα των [κεκοιμημενων]{.greek-omitted} [κεκοιμιμενων]{.greek-added} αγιων ηγερθη[27:52]{.aside}

και εξελθοντες εκ των μν[η]{.unclear}μειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και [τ]{.unclear}α γενομενα εφοβηθησαν σφοδρα [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} αληθως [θεου]{.greek-abbr} υιος ην ουτος[27:54]{.aside}

ησαν δε εκει γυναικες πολλαι [α]{.greek-added} [απο]{.greek-omitted} [πο]{.greek-added} μακροθεν [θεωρουσαι]{.greek-omitted} [θεορουσαι]{.greek-added} αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια η [του]{.greek-omitted} ιακωβου και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ ος και αυτος [εμαθητευσεν]{.greek-omitted} [εμαθητευσε]{.greek-added} τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω [ητησατο]{.greek-omitted} [ητησατω]{.greek-added} το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι [το]{.greek-omitted} [τω]{.greek-added} σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ ενετυλιξεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} σινδονι καθαρα[27:59]{.aside}

και εθηκεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν τω καινω αυτου μνημειω [ο]{.unclear} ελατομησεν εν τη πετρα και προσκυλισας λιθον [μεγαν]{.greek-omitted} [μεγα]{.greek-added} [εν]{.greek-added} τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη μαρια καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι [και]{.greek-added} [οι]{.greek-added} [πρεσβυτεροι]{.greek-added} προς πιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου [νυκτος]{.greek-omitted} [κλεψωσιν]{.greek-omitted} [κλεψουσιν]{.greek-added} αυτον και ειπωσιν τω λαω ηγερθη απο των νεκρων και εσται η εσχατη πλανη [χειρων]{.greek-omitted} [χειρω]{.greek-added} της πρωτης[27:64]{.aside}

εφη δε αυτοις ο πιλατος εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον σφραγισαντες τον λιθον μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε δε σαββατων τη επιφωσκουση εις μιαν σαββατων ηλθεν μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη μαρια θεωρησαι τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} [και]{.greek-added} προσελθων [απεκυλισεν]{.greek-omitted} [απεκυλισε]{.greek-added} τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και [εκαθητο]{.greek-omitted} [εκαθητω]{.greek-added} επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει [χιων]{.greek-omitted} [χειων]{.greek-added}[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκρ[ο]{.unclear}ι[28:4]{.aside}

αποκριθεις δε ο αγγελος ειπεν ταις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added} υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον [εσταυρωμενον]{.greek-abbr} ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη [γαρ]{.greek-omitted} καθως ειπεν δευτε [ιδετε]{.greek-omitted} [ειδετε]{.greek-added} τον τοπον οπου εκειτο [ο]{.greek-omitted} [κυριος]{.greek-omitted}[28:6]{.aside}

και ταχυ πορευθει[σα]{.unclear}ι ειπατε τοις μαθηταις αυτου οτι η[γ]{.unclear}ερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθ[ε]{.unclear} ιδου ειπον υμιν[28:7]{.aside}

και [εξελθουσαι]{.greek-omitted} [απελθουσαι]{.greek-added} ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

ως δε [επορευοντο]{.greek-omitted} [εδραμων]{.greek-added} απαγγειλαι τοις μαθηταις αυτου και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} [απηντησεν]{.greek-omitted} [υπηντησεν]{.greek-added} αυταις λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν αυτω[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν και εκει [με]{.greek-omitted} οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις [στρατιωταις]{.greek-omitted} [στρατιωτες]{.greek-added}[28:12]{.aside}

λεγοντες ειπατε οτι οι μαθηται αυτου νυκτος ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του ηγεμονος ημεις [πεισομεν]{.greek-omitted} [πεισωμεν]{.greek-added} αυτον και υμας αμεριμνους [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added}[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και διεφημισθη ο λογος ουτος παρα ιουδαιοις [μεχρι]{.greek-omitted} [μεχρη]{.greek-added} της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης [καθως]{.greek-added} [απεσταλκεν]{.greek-added} [με]{.greek-added} [ο]{.greek-added} [πηρ]{.greek-added} [καγω]{.greek-added} [αποστελλω]{.greek-added} [υμας]{.greek-added}[28:18]{.aside}

πορευθεντες [ουν]{.greek-added} μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

