---
title: "Collation of Byz^RP^ vs 31732 (1732)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1732 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31732).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1732                                   	| λογος                              	|
| 1732 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1732 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1732               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1732                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1732 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1732                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [και]{.greek-added} [α]{.greek-added} [τινα]{.greek-added} [εισι]{.greek-added} [και]{.greek-added} [α]{.greek-added} [χρη]{.greek-added} [γενεσθαι]{.greek-added} [μετα]{.greek-added} [ταυτα]{.greek-added}[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-omitted} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α [εστιν]{.greek-added} ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος [εκ]{.greek-added} των νεκρων και ο αρχων των βασιλεων της γης τω [αγαπωντι]{.greek-omitted} [αγαπησαντι]{.greek-added} ημας και λουσαντι [[λυσαντι]{.corr}]{.greek-added} ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και [το]{.greek-omitted} [τω]{.greek-added} κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα [[επι]{.corr}]{.greek-added} των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το αλφα και το [ω]{.greek-abbr} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και κοινωνος εν τη θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και [δια]{.greek-omitted} την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} οπισω μου [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} ως σαλπιγγος[1:10]{.aside}

λεγουσης ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις σμυρναν και εις περγαμον και εις θυατειρα και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

και εκει επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των επτα λυχνιων ομοιον υιω [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις [μαστοις]{.greek-omitted} [μαζοις]{.greek-added} ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω [ως]{.greek-omitted} [και]{.greek-added} εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια [χειρι]{.greek-added} αυτου [χειρι]{.greek-omitted} αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον [επεσα]{.greek-omitted} [επεσον]{.greek-added} προς τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} την δεξιαν αυτου [χειρα]{.greek-added} επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας κλεις του θανατου και του αδου[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν και αι [επτα]{.greek-added} λυχνιαι [αι]{.greek-omitted} [επτα]{.greek-omitted} [ας]{.greek-added} [ειδες]{.greek-added} επτα εκκλησιαι [εισιν]{.greek-omitted} [εισι]{.greek-added}[1:20]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα [σου]{.greek-added} τα εργα [σου]{.greek-omitted} και τον κοπον [σου]{.greek-omitted} και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις [και]{.greek-added} [εβαστασας]{.greek-added}[2:2]{.aside}

και υπομονην εχεις [και]{.greek-omitted} [εβαστασας]{.greek-omitted} δια το ονομα μου και [ουκ]{.greek-omitted} [ὀυκ]{.greek-added} [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

αλλα εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν [πεπτωκας]{.greek-omitted} [εκπεπτωκας]{.greek-added} και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω [αυτω]{.greek-omitted} φαγειν εκ του ξυλου της ζωης ο εστιν εν [τω]{.greek-omitted} [μεσω]{.greek-added} [του]{.greek-added} [παραδεισω]{.greek-omitted} [παραδεισου]{.greek-added} του [θεου]{.greek-abbr} μου[2:7]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και [εζησεν]{.greek-omitted} [εζησε]{.greek-added} [πρωτος]{.greek-added}[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν [εκ]{.greek-omitted} των λεγοντων [εαυτους]{.greek-added} ιουδαιους ειναι [εαυτους]{.greek-omitted} και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου [α]{.greek-omitted} [ων]{.greek-added} μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου δη μελλει [βαλειν]{.greek-omitted} [βαλεῖν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις εν αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς μου ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον [ουν]{.greek-omitted} ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω [φαγειν]{.greek-added} [απο]{.greek-added} του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου οτι αφεις την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο [ερευνων]{.greek-omitted} [εραυνων]{.greek-added} νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [αν]{.greek-omitted} ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα [κεραμικα]{.greek-omitted} [κεραμεικα]{.greek-added} [συντριβησεται]{.greek-omitted} [συντριβεσεται]{.greek-added} [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν [σαρδεσιν]{.greek-omitted} [σαραεσιν]{.greek-added} εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και [τηρησον]{.greek-added} [στηρισον]{.greek-omitted} [στηριξον]{.greek-added} τα λοιπα α [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [εμελλον]{.greek-added} [αποθνησκειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη γνως ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν [α]{.greek-omitted} [οι]{.greek-added} ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος [ο]{.greek-added} [νικων]{.greek-added} [ουτως]{.greek-added} περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν φιλαδελφεια εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την [κλειν]{.greek-omitted} [κλειδα]{.greek-added} του [δαυιδ]{.greek-abbr} [του]{.greek-added} [αδου]{.greek-added} ο ανοιγων και ουδεις κλεισει αυτην [και]{.greek-added} [ει]{.greek-omitted} [μη]{.greek-omitted} ο [ανοιγων]{.greek-omitted} [κλειων]{.greek-added} και ουδεις ανοιξει[3:7]{.aside}

οιδα σου τα εργα [και]{.greek-added} ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξουσι]{.greek-added} [ηκωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα μου το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος οφελον ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και πεπλουτηκα και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και ο ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι χρυσιον παρ εμου πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος σου και [κολλουρι]{.greek-added} [κολλυριον]{.greek-omitted} [[κολλουριον]{.corr}]{.greek-added} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [εγχρισον]{.greek-added} [επι]{.greek-added} τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω ζηλωσον ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν [και]{.greek-omitted} εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου [λεγων]{.greek-omitted} [λεγουσα]{.greek-added} αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι [τον]{.greek-omitted} [του]{.greek-added} [θρονον]{.greek-omitted} [θρονου]{.greek-added} καθημενος[4:2]{.aside}

ομοιος ορασει λιθω ιασπιδι και σαρδιω και [ιρις]{.greek-omitted} [ἶρις]{.greek-added} κυκλοθεν του θρονου [ομοιως]{.greek-omitted} [ομοια]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδινω]{.greek-added}[4:3]{.aside}

και [κυκλοθεν]{.greek-omitted} [κυκλω]{.greek-added} του θρονου θρονοι εικοσι τεσσαρες και επι τους θρονους [[κδ]{.greek-abbr}]{.greek-added} [τους]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα υαλινη ομοια κρυσταλλω [και]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον εχον [το]{.greek-added} προσωπον [ως]{.greek-added} [ανθρωπου]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} και το τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} εχον ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος [λεγοντες]{.greek-omitted} [λεγοντα]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσι]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλοῦσιν]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας [τα]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισι]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και [εξωθεν]{.greek-omitted} [οξωθεν]{.greek-added} κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο εν τω [ουρανω]{.greek-abbr} [ανω]{.greek-omitted} [ουτε]{.greek-omitted} [ουδε]{.greek-added} επι της γης [ουτε]{.greek-omitted} [ουδε]{.greek-added} υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως εσφαγμενον εχον κερατα επτα και οφθαλμους επτα α [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι επεσον ενωπιον του αρνιου εχοντες εκαστος [κιθαραν]{.greek-omitted} [κιθαρας]{.greek-added} και φιαλας χρυσας γεμουσας θυμιαματων αι εισιν [αι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας τω [θεω]{.greek-abbr} ημας εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και ειδον και ηκουσα [ως]{.greek-omitted} φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και [τον]{.greek-omitted} πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν [τω]{.greek-omitted} [ουρανω]{.greek-abbr} και επι [της]{.greek-omitted} γης και υποκατω της γης και επι της θαλασσης [εστιν]{.greek-omitted} και τα εν αυτοις [και]{.greek-added} παντας ηκουσα λεγοντας τω καθημενω επι του θρονου και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} [το]{.greek-omitted} αμην και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των [επτα]{.greek-omitted} σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνὴν]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα νικηση[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [την]{.greek-added} [σφραγιδα]{.greek-added} την δευτεραν [σφραγιδα]{.greek-omitted} ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος [πυρος]{.greek-omitted} [πυρρος]{.greek-added} και τω καθημενω επ αυτον εδοθη αυτω λαβειν την ειρηνην εκ της γης ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [ειδον]{.greek-added} και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες κριθης δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα [φωνην]{.greek-added} του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω [ο]{.greek-omitted} θανατος και ο αδης [ηκολουθει]{.greek-omitted} [ακολουθει]{.greek-added} [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} και εδοθη αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την [εκκλησιαν]{.greek-added} [μαρτυριαν]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} ην ειχον[6:9]{.aside}

και [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων [εκ]{.greek-omitted} [απο]{.greek-added} των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη [αυτοις]{.greek-omitted} εκαστω [αυτων]{.greek-added} στολη λευκη και [ερρεθη]{.greek-omitted} [ερρηθη]{.greek-added} αυτοις ινα αναπαυσωνται [χρονον]{.greek-added} ετι [χρονον]{.greek-omitted} [μικρον]{.greek-added} εως [ου]{.greek-added} [πληρωσωσιν]{.greek-omitted} [πληρωσουσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος μελας εγενετο ως σακκος τριχινος και η σεληνη ολη εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη [βαλουσα]{.greek-omitted} [αποβαλλει]{.greek-added} τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ελισσομενος]{.greek-added} και παν [ο]{.unclear}ρος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και [πας]{.greek-added} ελευθερος εκρυψαν [αυτους]{.greek-added} [εαυτους]{.corr} εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

και μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης [και]{.greek-added} κρατουντας τους τεσσαρας ανεμους της γης ινα μη πνεη ανεμος επι της γης μητε επι της θαλασσης μητε επι [τι]{.greek-omitted} [παν]{.greek-added} δενδρον[7:1]{.aside}

και ειδον [αγγελον]{.greek-added} αλλον [αγγελον]{.greek-omitted} αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη [αυτοις]{.greek-omitted} αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} [ου]{.greek-omitted} [αν]{.greek-added} σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον [και]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} [τεσσαρες]{.greek-omitted} [τεσσαρας]{.greek-added} [χιλιαδες]{.greek-omitted} [χιλιαδας]{.greek-added} εσφραγισμενων εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης ρουβιμ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης γαδ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης νεφθαλειμ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης μανασση [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:6]{.aside}

εκ φυλης συμεων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [λευι]{.corr} [δωδεκα]{.greek-omitted} [[[ιβ]{.greek-abbr}]{.corr}]{.greek-added} [χιλιαδες]{.corr} [εκ]{.corr} [φυλης]{.corr} [ισαχαρ]{.greek-omitted} [ισσαχαρ]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης βενιαμιν [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις εδυνατο εκ παντος εθνους και φυλων και λαων και γλωσσων [εστωτας]{.greek-omitted} [εστωτες]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου [περιβεβλημενους]{.greek-omitted} [περιβεβλημενοι]{.greek-added} στολας λευκας και φοινικας εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα [και]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας [λευκας]{.greek-added} στολας [τας]{.greek-omitted} [λευκας]{.greek-omitted} τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον αυτω κυριε μου συ οιδας και ειπεν [μοι]{.greek-omitted} ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και επλυναν τας [λευκας]{.greek-added} στολας αυτων και ελευκαναν [αυτας]{.greek-added} εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν ετι [τον]{.greek-added} [γαρ]{.greek-added} [αρτον]{.greek-added} [τον]{.greek-added} [[ουνιον]{.greek-abbr}]{.greek-added} [και]{.greek-added} [το]{.greek-added} [υδωρ]{.greek-added} [της]{.greek-added} [ζωης]{.greek-added} [εξουσιν]{.greek-added} [ουδ]{.greek-omitted} [ουδου]{.greek-added} [ου]{.greek-omitted} μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγησει]{.greek-added} αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον [εκ]{.greek-omitted} [απο]{.greek-added} των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως ημιωριον[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θρονου]{.greek-added} [του]{.greek-added} [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι του θυσιαστηριου εχων λιβανωτον χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δωσει]{.greek-added} ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο [φωναι]{.greek-added} [και]{.greek-added} βρονται [και]{.greek-omitted} [φωναι]{.greek-omitted} και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα [σαλπισωσιν]{.greek-omitted} [σαλπισωσι]{.greek-added}[8:6]{.aside}

και ο πρωτος [αγγελος]{.greek-added} [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον των κτισματων εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων [διεφθαρη]{.greek-omitted} [διεφθαρησαν]{.greek-added}[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι [των]{.corr} [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [μη]{.greek-added} [φαινη]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος αετου πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη [τρις]{.greek-added} ουαι ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} και ανεβη καπνος εκ του φρεατος ως καπνος καμινου καιομενης και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} [μονους]{.greek-added} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και εδοθη αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [πληξη]{.greek-added} [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [ἕυρωσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και φευξεται [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι χρυσοι και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [και]{.greek-added} εξουσιαν εχουσιν [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[και]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσιν]{.greek-added} [βασιλεα]{.greek-omitted} επ αυτων [βασιλεα]{.greek-added} [τον]{.greek-added} αγγελον της αβυσσου ονομα αυτω εβραιστι αββαδων εν δε τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια [απηλθεν]{.greek-omitted} [παρηλθεν]{.greek-added} ιδου [ερχεται]{.greek-omitted} [ερχοντει]{.greek-added} [ετι]{.corr} [αι]{.greek-added} δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ηκουσα φωνην μιαν εκ των [τεσσαρων]{.greek-omitted} κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

λεγουσαν τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους [επι]{.greek-omitted} [εν]{.greek-added} τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και [εις]{.greek-omitted} την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον [μερος]{.greek-added} των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [ιππου]{.greek-omitted} [ιππικου]{.greek-added} [δυο]{.greek-added} [μυριαδες]{.greek-omitted} [μυριαδας]{.greek-added} μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι [των]{.corr} [ιππων]{.corr} [ως]{.corr} [κεφαλαι]{.corr} λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} εχουσαι κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των φαρμακειων αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και [η]{.greek-omitted} [ιριν]{.greek-added} [ιρις]{.corr} επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν τη χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλιδαριον]{.greek-added} ανεωγμενον και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη [ωσπερ]{.greek-omitted} [ως]{.greek-added} λεων [μυκαται]{.greek-omitted} [βρυχαται]{.greek-added} [ωρυεται]{.greek-added} και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και [οτε]{.greek-omitted} [οσα]{.greek-added} ελαλησαν αι επτα βρονται εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και ωμοσεν [εν]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν [και]{.greek-omitted} [ετελεσθη]{.greek-omitted} [τελεσθη]{.greek-added} το μυστηριον του [θεου]{.greek-abbr} [ως]{.greek-omitted} [ο]{.greek-added} [ευηγγελισεν]{.greek-omitted} [ευηγγελισατο]{.greek-added} [τους]{.greek-omitted} [τοις]{.greek-added} [δουλους]{.greek-omitted} αυτου [δουλοις]{.greek-added} [τους]{.greek-omitted} [τοις]{.greek-added} [προφητας]{.greek-omitted} [προφηταις]{.greek-added}[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα μετ εμου και λεγουσα υπαγε λαβε το βιβλιδαριον το ανεωγμενον εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω [δουναι]{.greek-omitted} [δος]{.greek-added} μοι το βιβλιδαριον και λεγει μοι λαβε και καταφαγε [αυτο]{.greek-omitted} [ἀυτό]{.greek-added} και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βιβλιδαριον]{.greek-added} εκ της χειρος του αγγελου και κατεφαγον αυτο και ην εν τω στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και [επι]{.greek-added} γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω [και]{.greek-added} [ειστηκει]{.greek-added} [ο]{.greek-added} [αγγελος]{.greek-added} λεγων εγειραι και μετρησον τον ναον του [θεου]{.greek-abbr} και το [θυσιαστηριον]{.greek-omitted} [θησιαστηριον]{.greek-added} και τους [προσκυνουντας]{.greek-omitted} [προσκυνουντους]{.greek-added} εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα [και]{.greek-omitted} δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} [επι]{.greek-added} της γης εστωσαι[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους [αδικησαι]{.greek-omitted} [αποκτειναι]{.greek-added} ουτως δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι εχουσιν [εξουσιαν]{.greek-added} [κλεισαι]{.greek-added} τον [ουρανον]{.greek-abbr} [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην [οσακις]{.greek-omitted} [εαν]{.greek-omitted} [θελησωσιν]{.greek-omitted} εν παση πληγη [οσακις]{.greek-added} [εαν]{.greek-added} [θελησωσι]{.greek-added}[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωμαται]{.greek-added} αυτων [εασει]{.greek-added} επι της πλατειας της πολεως της μεγαλης [αταφα]{.greek-added} ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων [εσταυρωθη]{.greek-omitted} [εστρωθη]{.greek-added}[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων ημερας τρεις [και]{.greek-added} ημισυ και τα [πτωματα]{.greek-omitted} [σωματα]{.greek-added} αυτων ουκ [αφησουσιν]{.greek-omitted} [αφησουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} χαιρουσιν [επ]{.greek-omitted} [εν]{.greek-added} αυτοις και [ευφρανθησονται]{.greek-omitted} [ευφραινονται]{.greek-added} και δωρα [δωσουσιν]{.greek-omitted} [πεμπουσιν]{.greek-added} αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα [τας]{.greek-omitted} τρεις [ημερας]{.greek-omitted} και ημισυ [ημερας]{.greek-added} [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν [εις]{.greek-omitted} [επ]{.greek-added} αυτους και εστησαν επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} [επεπεσεν]{.greek-added} επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσαν]{.greek-omitted} [λεγουσης]{.greek-added} αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν [τη]{.greek-omitted} νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη ημερα εγενετο σεισμος μεγας και το δεκατον της πολεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι [γενομενοι]{.greek-added} [εγενοντο]{.greek-omitted} [και]{.greek-omitted} εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα [απηλθεν]{.greek-omitted} [παρηλθεν]{.greek-added} η ουαι η τριτη ιδου ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι οι ενωπιον [του]{.greek-omitted} [θρονου]{.greek-omitted} του [θεου]{.greek-abbr} καθημενοι επι τους θρονους αυτων επεσον επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην [και]{.greek-added} [ο]{.greek-added} [ερχομενος]{.greek-added} οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους [διαφθειροντας]{.greek-omitted} [διαφθειραντας]{.greek-added} την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} [ο]{.greek-added} εν τω [ουρανω]{.greek-abbr} και ωφθη [η]{.greek-omitted} κιβωτος της διαθηκης του [κυριου]{.greek-abbr} εν τω ναω αυτου και εγενοντο αστραπαι και [βρονται]{.greek-added} [και]{.greek-added} φωναι [και]{.greek-omitted} [βρονται]{.greek-omitted} και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος [δι]{.greek-added} αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα εκραζεν ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων [πυρος]{.greek-omitted} μεγας [πυρρος]{.greek-added} εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἕστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης [τεκειν]{.greek-omitted} [τικτειν]{.greek-added} ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και [ηρπασθη]{.greek-omitted} [ηρπαγη]{.greek-added} το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει [τοπον]{.greek-added} εκει [τοπον]{.greek-omitted} ητοιμασμενον [υπο]{.greek-omitted} [απο]{.greek-added} του [θεου]{.greek-abbr} ινα εκει εκτρεφωσιν αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη αυτω ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων [ολην]{.greek-added} την οικουμενην [ολην]{.greek-omitted} εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι [εβληθη]{.greek-omitted} [κατεβληθη]{.greek-added} ο [κατηγορος]{.greek-omitted} [κατηγωρος]{.greek-added} των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} [ημων]{.greek-omitted} ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν [αυτον]{.corr} δια το [ονομα]{.greek-added} αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

δια τουτο ευφραινεσθε [οι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν αυτοις σκηνουντες ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν τη γυναικι [αι]{.greek-added} δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον αυτης οπως τρεφηται εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον ποιηση[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθη]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον [και]{.greek-added} εχον κερατα δεκα και κεφαλας επτα και επι των κερατων [αυτου]{.greek-omitted} δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον [ομοιον]{.greek-added} ην [ομοιον]{.greek-omitted} παρδαλει και οι ποδες αυτου ως [αρκου]{.greek-omitted} [αρκτου]{.greek-added} και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου [ωσει]{.greek-omitted} [ως]{.greek-added} εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και [εθαυμασεν]{.greek-omitted} [εθαμβηθη]{.greek-added} ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [οτι]{.greek-added} [εδωκε]{.greek-added} την εξουσιαν τω θηριω και προσεκυνησαν τω θηριω λεγοντες τις ομοιος τω θηριω και τις δυνατος πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημα]{.greek-added} και εδοθη αυτω εξουσια πολεμον ποιησαι μηνας [[μβ]{.greek-abbr}]{.greek-added} [τεσσαρακοντα]{.greek-omitted} [δυο]{.greek-omitted}[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου [και]{.greek-added} τους εν τω [ουρανω]{.greek-abbr} σκηνουντας[13:6]{.aside}

και εδοθη αυτω ποιησαι πολεμον μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και λαον και [εθνος]{.greek-added} [και]{.greek-added} [γλωσσαν]{.greek-added} [γλωσσαν]{.corr} [και]{.corr} [εθνος]{.corr}[13:7]{.aside}

και προσκυνησουσιν αυτω παντες οι κατοικουντες επι της γης ων ου γεγραπται [το]{.greek-omitted} [τα]{.greek-added} [ονομα]{.greek-omitted} [ονοματα]{.greek-added} εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις εχει [αιχμαλωσιαν]{.greek-added} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτείνει]{.greek-added} δει αυτον εν μαχαιρα αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και [ειχεν]{.greek-omitted} [ειχε]{.greek-added} κερατα δυο ομοια αρνιω και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει σημεια μεγαλα [και]{.greek-omitted} [ινα]{.greek-added} [εν]{.greek-added} [πλανη]{.greek-added} [ποιη]{.greek-added} πυρ [ινα]{.greek-omitted} εκ του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [καταβαινειν]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [ὃ]{.greek-added} [εχει]{.greek-added} την πληγην [και]{.greek-omitted} [εζησεν]{.greek-omitted} [απο]{.greek-omitted} της μαχαιρας [και]{.greek-added} [εζησε]{.greek-added}[13:14]{.aside}

και εδοθη αυτω πνευμα δουναι τη εικονι του θηριου ινα και λαληση η εικων του θηριου και [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τη εικονι του θηριου [ινα]{.greek-added} [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} αυτοις [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της [δεξιας]{.greek-added} χειρος αυτων [και]{.greek-added} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [η]{.greek-omitted} επι [το]{.greek-omitted} [των]{.greek-added} μετωπον [αυτων]{.greek-omitted}[13:16]{.aside}

[και]{.greek-omitted} ινα μη τις [δυναται]{.greek-omitted} [δυνηται]{.greek-added} αγορασαι η πωλησαι ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν [ψηφισατω]{.greek-omitted} [ψηφησατω]{.greek-added} τον αριθμον [του]{.greek-added} [ονοματος]{.greek-added} του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο αριθμος αυτου εστιν εξακοσια εξηκοντα εξ[13:18]{.aside}

### Chapter 14

και ειδον και ιδου [το]{.greek-omitted} αρνιον [εστηκος]{.greek-omitted} [εστως]{.greek-added} επι το ορος σιων και μετ αυτου [αριθμος]{.greek-omitted} εκατον τεσσαρακοντα τεσσαρες χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα [φωνων]{.greek-added} [και]{.greek-added} [η]{.greek-added} [φωνην]{.greek-omitted} [φωνη]{.greek-added} [ην]{.greek-added} [ηκουσα]{.greek-added} [ως]{.greek-added} εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και [ως]{.greek-omitted} φωνην [βροντης]{.greek-omitted} [μεγαλης]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [ην]{.greek-omitted} ηκουσα ως κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες [οι]{.greek-omitted} [ως]{.greek-added} ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι [εισιν]{.greek-omitted} [εστιν]{.greek-added} οι ακολουθουντες τω αρνιω οπου αν υπαγη ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} εν τω στοματι αυτων [ουχ]{.greek-added} [ευρεθη]{.greek-added} ψευδος αμωμοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added}[14:5]{.aside}

και ειδον αγγελον πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον [ερχομενον]{.greek-added} [ευαγγελισαι]{.greek-omitted} [ευαγγελι]{.greek-added} [ονοματα]{.greek-added} [τα]{.greek-added} [εχοντα]{.greek-added} [τον]{.greek-added} [αριθμον]{.greek-added} [του]{.greek-added} [ονοματος]{.greek-added} [του]{.greek-added} [αντιχριστου]{.greek-added} [κυρια]{.greek-added} [μεν]{.greek-added} [λαμπετης]{.greek-added} [τειταν]{.greek-added} [λατεινος]{.greek-added} [βενεδικτος]{.greek-added} [προςηγορικα]{.greek-added} [δε]{.greek-added} [ο]{.greek-added} [νικητης]{.greek-added} [ο]{.greek-added} [επισαλος]{.greek-added} [κακος]{.greek-added} [ο]{.greek-added} [δηγος]{.greek-added} [αλητης]{.greek-added} [βλαβετρος]{.greek-added} [παλαι]{.greek-added} [βασκαλος]{.greek-added} [αμνος]{.greek-added} [αδικος]{.greek-added} [σασθαι]{.greek-added} τους [καθημενους]{.greek-omitted} [καατοικουντας]{.greek-added} επι της γης και [επι]{.greek-omitted} παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε αυτον τον ποιησαντα τον [ουρανον]{.greek-abbr} και την γην και [την]{.greek-omitted} θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος [αγγελος]{.greek-added} δευτερος [αγγελος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων επεσεν [επεσε]{.greek-added} βαβυλων η μεγαλη εκ του οινου του θυμου της πορνειας αυτης [ης]{.greek-added} [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} [παντα]{.greek-omitted} τα εθνη [παντα]{.greek-added}[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει χαραγμα επι του μετωπου [[το]{.corr}]{.greek-added} [[μετωπον]{.corr}]{.greek-added} αυτου [η]{.greek-omitted} [και]{.greek-added} επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις [αιωνας]{.greek-omitted} [αιωνα]{.greek-added} [αιωνων]{.greek-omitted} [αιωνος]{.greek-added} αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν [ωδε]{.greek-added} οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης [μοι]{.greek-added} γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀποάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} ινα αναπαυσωνται εκ των κοπων αυτων τα δε εργα αυτων ακολουθει μετ αυτων[14:13]{.aside}

και ειδον και ιδου νεφελη λευκη και επι [της]{.greek-added} [νεφελης]{.greek-added} [καθημενος]{.greek-added} [ομοιος]{.greek-added} [την]{.corr} [νεφελην]{.corr} [καθημενον]{.corr} [ομοιον]{.corr} υιω [ανθρωπου]{.greek-abbr} εχων [[εχοντα]{.corr}]{.greek-added} επι [της]{.greek-omitted} [την]{.greek-added} [κεφαλης]{.greek-omitted} [κεφαλην]{.greek-added} αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του [ναου]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} κραζων εν φωνη μεγαλη τω καθημενω επι [της]{.greek-omitted} [την]{.greek-added} [νεφελης]{.greek-omitted} [νεφελην]{.greek-added} πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους [βοτρυας]{.greek-omitted} [βοτρυς]{.greek-added} της αμπελου της γης οτι ηκμασαν αι σταφυλαι αυτης[14:18]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις την ληνον του θυμου του [θεου]{.greek-abbr} [τον]{.greek-omitted} [την]{.greek-added} [μεγαν]{.greek-omitted} [μεγανλην]{.greek-added}[14:19]{.aside}

και επατηθη η ληνος [εξωθεν]{.greek-omitted} [εξω]{.greek-added} της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας [επτα]{.greek-added} πληγας [επτα]{.greek-omitted} τας εσχατας οτι εν [αυταις]{.greek-omitted} [ταυταις]{.greek-added} ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} του δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη φοβηθη σε [κυριε]{.greek-abbr} και δοξαση το ονομα σου οτι μονος αγιος [ει]{.greek-added} οτι παντα τα εθνη [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας εκ του ναου [οι]{.greek-omitted} [ησαν]{.greek-omitted} ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι [περι]{.greek-omitted} [επι]{.greek-added} τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας [του]{.greek-omitted} θυμου [του]{.greek-omitted} [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων [αμην]{.greek-added}[15:7]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και [τις]{.greek-added} [ενεγκη]{.greek-added} [τον]{.greek-added} [θυμον]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των [επτα]{.greek-omitted} αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις υπαγετε [και]{.greek-omitted} εκχεατε τας [επτα]{.greek-omitted} φιαλας του θυμου του [θεου]{.greek-abbr} [εις]{.greek-omitted} [επι]{.greek-added} την γην[16:1]{.aside}

και απηλθεν ο πρωτος [αγγελος]{.greek-added} και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου [εις]{.greek-omitted} [επι]{.greek-added} την γην και εγενετο ελκος κακον και πονηρον [επι]{.greek-omitted} [εις]{.greek-added} τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και [τους]{.greek-omitted} προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη ζωσα [απεθανεν]{.greek-omitted} εν τη θαλασση [απεθανε]{.greek-added}[16:3]{.aside}

και ο τριτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και [εις]{.greek-omitted} τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην ο οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν αξιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:6]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και εδοθη αυτω καυματισαι [τους]{.greek-added} [[ανθρωπους]{.greek-abbr}]{.greek-added} εν πυρι [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} [καυμα]{.greek-omitted} [καυματι]{.greek-added} [μεγα]{.greek-omitted} [μεγαλω]{.greek-added} και εβλασφημησαν [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} το ονομα του [θεου]{.greek-abbr} του εχοντος [την]{.greek-added} εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου [εσκοτωμενη]{.greek-omitted} [εσκοτισμενη]{.greek-added} και εμασωντο τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ποταμον τον μεγαν [τον]{.greek-added} ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο [ανατολης]{.greek-omitted} [ανατολων]{.greek-added} ηλιου[16:12]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα [τρια]{.greek-added} ακαθαρτα [τρια]{.greek-omitted} ως βατραχοι [εκπορευθεντα]{.greek-added}[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ πνευματα [δαιμονιων]{.greek-omitted} [δαιμονων]{.greek-added} ποιουντα σημεια α εκπορευεται επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} [του]{.greek-omitted} παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἁρμαγεδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου [επι]{.greek-omitted} [εις]{.greek-added} τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη απο [του]{.greek-omitted} [ναου]{.greek-omitted} του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και φωναι και σεισμος [εγενετο]{.greek-added} μεγας οιος ουκ εγενετο αφ ου [οι]{.greek-omitted} [ανθρωποι]{.greek-abbr} [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} επι της γης τηλικουτος σεισμος ουτως μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και [αι]{.greek-omitted} πολεις των εθνων επεσον και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} [του]{.greek-added} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} [προς]{.greek-added} [επι]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-abbr} και εβλασφημησαν [τον]{.greek-added} [[θεον]{.greek-abbr}]{.greek-added} [οι]{.greek-added} [[ανθρωποι]{.greek-abbr}]{.greek-added} [οι]{.corr} [[ανθρωποι]{.greek-abbr}]{.corr} [τον]{.corr} [[θεον]{.greek-abbr}]{.corr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις [εκ]{.greek-omitted} των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων [μοι]{.greek-added} δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον κοκκινον γεμον [ονοματα]{.greek-omitted} [ονοματων]{.greek-added} βλασφημιας [εχον]{.greek-omitted} [εχων]{.greek-added} κεφαλας επτα και κερατα δεκα[17:3]{.aside}

[και]{.greek-added} [λεγει]{.greek-added} [μοι]{.greek-added} [η]{.greek-added} [γυνη]{.greek-added} [ἣν]{.greek-added} [ειδες]{.greek-added} [εστιν]{.greek-added} [η]{.greek-added} [πολις]{.greek-added} [η]{.greek-added} [μεγαλη]{.greek-added} [η]{.greek-added} [εχουσα]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} [επι]{.greek-added} [των]{.greek-added} [βασιλεων]{.greek-added} [της]{.greek-added} [γης]{.greek-added} και η γυνη ην περιβεβλημενη πορφυρουν [και]{.corr} κοκκινον κεχρυσωμενη [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις εχουσα [χρυσουν]{.greek-added} ποτηριον [χρυσουν]{.greek-omitted} εν τη χειρι αυτης γεμον βδελυγματων και τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν εκ του αιματος των αγιων [και]{.greek-added} εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος δια τι εθαυμασας εγω [σοι]{.greek-added} ερω [σοι]{.greek-omitted} το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες επι της γης ων ου γεγραπται τα ονοματα [εν]{.greek-added} [βιβλω]{.greek-added} [επι]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [της]{.greek-omitted} ζωης απο καταβολης κοσμου βλεποντων [το]{.greek-added} [θηριον]{.greek-added} οτι ην [το]{.greek-omitted} [θηριον]{.greek-omitted} και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και [παρεσται]{.greek-omitted} [παρεστιν]{.greek-added}[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται [και]{.greek-added} επ αυτων [βασιλεις]{.greek-added} [επτα]{.greek-added} [εισιν]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε επεσον ο εις εστιν ο αλλος ουπω [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και οταν ελθη ολιγον [αυτον]{.greek-added} δει [αυτον]{.greek-omitted} μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και αυτος ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} και εκ των επτα [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} μετα του θηριου [λαμβανουσιν]{.greek-added}[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} γνωμην [εχουσι]{.greek-added} και την δυναμιν και την εξουσιαν αυτων τω θηριω [διδοασιν]{.greek-omitted} [δωσουσιν]{.greek-added}[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων [εστι]{.greek-added} και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην ποιησουσιν αυτην και γυμνην [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} και τας σαρκας αυτης φαγονται και αυτην κατακαυσουσιν εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και [ποιησαι]{.greek-omitted} [γνωμην]{.greek-omitted} [μιαν]{.greek-omitted} [και]{.greek-omitted} δουναι την βασιλειαν αυτων τω θηριω αχρι [τελεσθωσιν]{.greek-omitted} [τελεσθησονται]{.greek-added} οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} [ειδον]{.greek-added} μετα ταυτα [ειδον]{.greek-omitted} αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν [εν]{.greek-added} ισχυρα φωνη λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} [επεσε]{.greek-added} βαβυλων η μεγαλη και εγενετο [κατοικητηριον]{.greek-omitted} [κατοικη]{.greek-added} [τηριον]{.greek-added} δαιμονων και φυλακη παντος πνευματος ακαθαρτου και φυλακη παντος ορνεου ακαθαρτου και μεμισημενου[18:2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν [εξελθε]{.greek-omitted} [εξελθησε]{.greek-added} εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη [λαβητε]{.greek-omitted} [βλαβητε]{.greek-added}[18:4]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν [υμιν]{.greek-added} και διπλωσατε αυτη διπλα κατα τα εργα αυτης εν τω ποτηριω ω εκερασεν [υμιν]{.greek-added} κερασατε αυτη διπλουν[18:6]{.aside}

οσα εδοξασεν [αυτην]{.greek-omitted} [εαυτην]{.greek-added} και [εστρηνιασεν]{.greek-omitted} [εστρηνιασε]{.greek-added} τοσουτον δοτε αυτη [βασανισμον]{.greek-omitted} [βησανισμον]{.greek-added} και πενθος [δι]{.greek-added} οτι εν τη καρδια αυτης λεγει οτι καθημαι βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο [κρινας]{.greek-omitted} [παντοκρατωρ]{.greek-added} [ο]{.greek-added} [κρινων]{.greek-added} αυτην[18:8]{.aside}

και κλαυσουσιν [αυτην]{.greek-added} και κοψονται επ [αυτην]{.greek-omitted} [αυτη]{.greek-added} οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν [εστηκοτες]{.greek-omitted} [στηκοντες]{.greek-added} δια τον φοβον του βασανισμου αυτης λεγοντες ουαι ουαι η πολις η μεγαλη βαβυλων η πολις η [ισχυρα]{.greek-omitted} [οχυρα]{.greek-added} οτι μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαιουσιν]{.greek-added} [εν]{.greek-added} [εαυτοις]{.greek-added} [και]{.greek-omitted} [πενθησουσιν]{.greek-omitted} [επ]{.greek-omitted} [αυτη]{.greek-omitted} οτι τον γομον αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και μαργαριτου και [βυσσινου]{.greek-omitted} [βυσσου]{.greek-added} και πορφυρου και σηρικου και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και κιναμωμον και θυμιαματα και [μυρον]{.greek-omitted} [σμυρναν]{.greek-added} και λιβανον και οινον και ελαιον και σεμιδαλιν και [σιτον]{.greek-omitted} [κτηνη]{.greek-added} και προβατα [και]{.greek-omitted} [κτηνη]{.greek-omitted} και ιππων και ραιδων και σωματων και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα [απωλετο]{.greek-omitted} [απηλθεν]{.greek-added} απο σου και ουκετι [αυτα]{.greek-omitted} ου μη ευρης [αυτα]{.greek-added} [ουτε]{.greek-added} [ψυχας]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [του]{.greek-added} [λοιπου]{.greek-added} [εμπορευση]{.greek-added} [ουτε]{.greek-added} [των]{.greek-added} [παλαι]{.greek-added} [λιπαρων]{.greek-added} [και]{.greek-added} [λαμπρων]{.greek-added} [εξεις]{.greek-added} [απολαυσιν]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15]{.aside}

και λεγοντες ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και πορφυρουν και κοκκινον και κεχρυσωμενη [εν]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος και πας κυβερνητης και πας [ο]{.greek-omitted} επι [τοπον]{.greek-omitted} [των]{.greek-added} [πλοιων]{.greek-added} πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν [εστησαν]{.greek-omitted} [εστηκασι]{.greek-added}[18:17]{.aside}

και εκραζον βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες [τις]{.greek-omitted} [ομοια]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [τη]{.greek-omitted} [μεγαλη]{.greek-omitted}[18:18]{.aside}

[και]{.greek-omitted} [εβαλον]{.greek-omitted} [χουν]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [κεφαλας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εκραζον]{.greek-omitted} [κλαιοντες]{.greek-omitted} [και]{.greek-omitted} [πενθουντες]{.greek-omitted} [και]{.greek-omitted} [λεγοντες]{.greek-omitted} ουαι ουαι η πολις η μεγαλη εν η επλουτησαν παντες οι εχοντες [τα]{.greek-omitted} πλοια εν τη θαλασση εκ της τιμιοτητος αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον [ως]{.greek-omitted} [ωσει]{.greek-added} μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης πασης τεχνης ου μη ευρεθη εν σοι ετι και φωνη μυλου ου μη ακουσθη εν σοι ετι[18:22]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [φανῆ]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη ακουσθη εν σοι ετι οτι οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν τη φαρμακεια σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη [αιματα]{.greek-omitted} [αιμα]{.greek-added} προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

[και]{.greek-added} μετα ταυτα ηκουσα ως [φωνην]{.greek-omitted} [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} οχλου πολλου εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δοξα]{.greek-added} και η [δοξα]{.greek-omitted} [δυναμις]{.greek-added} του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την [πορνην]{.greek-omitted} [πολιν]{.greek-added} την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [εφθειρε]{.greek-added} την γην εν τη πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ χειρος αυτης[19:2]{.aside}

και δευτερον [ειρηκεν]{.greek-omitted} [ειρηκασιν]{.greek-added} αλληλουια και ο καπνος αυτης [αναβαινει]{.greek-omitted} [ανεβη]{.greek-added} εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι [πρεσβυτεροι]{.greek-omitted} [οι]{.greek-omitted} εικοσι τεσσαρες [πρεσβυτεροι]{.greek-added} και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη [απο]{.greek-omitted} [εκ]{.greek-added} του θρονου [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} λεγουσα αινειτε τον [θεον]{.greek-abbr} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα ως φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντων]{.greek-added} αλληλουια οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και αγαλλιωμεθα και δωμεν την δοξαν αυτω οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα περιβαληται βυσσινον [καθαρον]{.greek-added} λαμπρον [και]{.greek-omitted} [καθαρον]{.greek-omitted} το γαρ βυσσινον τα δικαιωματα των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι [εισιν]{.greek-added} οι εις το δειπνον [του]{.greek-omitted} [γαμου]{.greek-omitted} του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι αληθινοι [εισι]{.greek-added} του [θεου]{.greek-abbr} [εισιν]{.greek-omitted}[19:9]{.aside}

και [επεσα]{.greek-omitted} [επεσον]{.greek-added} εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια [του]{.greek-omitted} [ιησου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον [καλουμενος]{.greek-omitted} πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων ονοματα γεγραμμενα και ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον βεβαμμενον αιματι και καλειται το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα τα εν τω [ουρανω]{.greek-abbr} [ηκολουθει]{.greek-omitted} [ηκολουθουν]{.greek-added} αυτω [επι]{.greek-omitted} [εφ]{.greek-added} ιπποις λευκοις ενδεδυμενοι βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια [οξεια]{.greek-added} διστομος [οξεια]{.greek-omitted} ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος πατει την ληνον του οινου του θυμου [και]{.greek-added} της οργης του [θεου]{.greek-abbr} [του]{.greek-omitted} παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον αγγελον εστωτα εν τω ηλιω και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν [τω]{.greek-added} μεσουρανηματι δευτε συναχθητε [εις]{.greek-added} [το]{.greek-added} [δειπνον]{.greek-added} [του]{.greek-added} [μεγαλου]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εις το δειπνον το μεγα του [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων και μικρων [τε]{.greek-omitted} και μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον και [ο]{.greek-omitted} μετ αυτου [ο]{.greek-added} ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας [τη]{.greek-omitted} [την]{.greek-added} [εικονι]{.greek-omitted} [εικονα]{.greek-added} αυτου ζωντες εβληθησαν οι δυο εις την λιμνην του πυρος την καιομενην εν [τω]{.greek-added} θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την κλειν της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος εστιν [ο]{.greek-added} διαβολος και ο σατανας ο πλανων την οικουμενην ολην και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλεισε]{.greek-added} και εσφραγισεν επανω αυτου ινα μη πλανα ετι τα εθνη αχρι τελεσθη [τα]{.greek-omitted} χιλια ετη και μετα ταυτα δει αυτον λυθηναι μικρον χρονον[20:3]{.aside}

και ειδον θρονους και εκαθισαν επ αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν το θηριον [ουδε]{.greek-omitted} [ουτε]{.greek-added} την εικονα αυτου και ουκ ελαβον το χαραγμα επι το μετωπον [αυτων]{.greek-added} και επι την χειρα αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} [τα]{.greek-omitted} χιλια ετη[20:4]{.aside}

και οι λοιποι των νεκρων ουκ εζησαν αχρι [τελεσθη]{.greek-omitted} [τελεσθωσι]{.greek-added} τα χιλια ετη αυτη η αναστασις η πρωτη[20:5]{.aside}

[και]{.greek-added} μακαριος και αγιος ο εχων μερος εν τη αναστασει τη πρωτη επι τουτων ο [θανατος]{.greek-added} [ο]{.greek-added} δευτερος [θανατος]{.greek-omitted} ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου χιλια ετη[20:6]{.aside}

και οταν τελεσθη τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι [παντα]{.greek-added} τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης [και]{.greek-added} τον γωγ και τον μαγωγ [και]{.greek-added} συναγαγειν αυτους [ε]{.greek-added} [εις]{.greek-omitted} [τον]{.greek-omitted} πολεμον ων ο αριθμος ως η αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και [εκυ]{.greek-added} [εκυκλωσαν]{.greek-omitted} [κλωσαν]{.greek-added} την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και [του]{.greek-added} θειου οπου και το θηριον και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10]{.aside}

και ειδον θρονον [λευκον]{.greek-added} μεγαν [λευκον]{.greek-omitted} και τον καθημενον επ αυτον ου απο προσωπου εφυγεν [ο]{.greek-added} [[ουρανος]{.greek-abbr}]{.greek-added} [και]{.greek-added} η γη [και]{.greek-omitted} [ο]{.greek-omitted} [ουρανος]{.greek-omitted} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον τους νεκρους τους μεγαλους και τους μικρους [εστωτας]{.greek-omitted} [εστω]{.greek-added} [τας]{.greek-added} ενωπιον του θρονου και βιβλια [ηνεωχθησαν]{.greek-omitted} [ηνοιχθησαν]{.greek-added} και αλλο βιβλιον [ηνεωχθη]{.greek-omitted} [ηνοιχθη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν αυτη και ο θανατος και ο αδης [εδωκαν]{.greek-omitted} τους νεκρους τους εν αυτοις και εκριθησαν [ε]{.unclear}καστος κατα τα εργα αυτων[20:13]{.aside}

και ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος ουτος [εστιν]{.greek-added} ο θανατος ο δευτερος [εστιν]{.greek-omitted} η λιμνη του πυρος[20:14]{.aside}

και ει τις ουχ ευρεθη [γεγραμμενος]{.greek-added} εν [τω]{.greek-omitted} [τη]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλω]{.greek-added} της ζωης [γεγραμμενος]{.greek-omitted} εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη [απηλθον]{.greek-omitted} [παρηλθε]{.greek-added} και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν [απο]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} ητοιμασμενην ως νυμφην κεκοσμημενην τω ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} εσται μετ αυτων [[θεος]{.greek-abbr}]{.greek-added} [αυτων]{.greek-added}[21:3]{.aside}

και εξαλειψει παν δακρυον απο των οφθαλμων αυτων και [ο]{.greek-omitted} θανατος [ουκ]{.greek-omitted} [ουκετι]{.greek-added} εσται [ετι]{.greek-omitted} ουτε πενθος ουτε κραυγη ουτε πονος ουκ εσται ετι [οτι]{.greek-omitted} τα [γαρ]{.greek-added} πρωτα απηλθον[21:4]{.aside}

[κ]{.unclear}αι ειπεν ο [εν]{.greek-added} [καθημενος]{.greek-omitted} [επι]{.greek-omitted} τω θρονω [καθημενος]{.greek-added} ιδου [καινο]{.greek-added} [ποιω]{.greek-added} παντα [καινα]{.greek-omitted} [ποιω]{.greek-omitted} και λεγει μοι γραψον οτι ουτοι οι λογοι αληθινοι και πιστοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[21:5]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι γεγονα [εγω]{.greek-added} το αλφα και το [ω]{.greek-abbr} η αρχη και το τελος εγω τω διψωντι δωσω εκ της πηγης του υδατος της ζωης [δ]{.unclear}ωρεαν[21:6]{.aside}

ο νικων κληρονομησει ταυτα και εσομαι [αυτω]{.greek-omitted} [αυτων]{.greek-added} [θεος]{.greek-abbr} και [αυτος]{.greek-omitted} [αυτοι]{.greek-added} [εσται]{.greek-omitted} [εσονται]{.greek-added} μοι [υιος]{.greek-omitted} [υιοι]{.greek-added}[21:7]{.aside}

τοις δε δειλοις και απιστοις και [αμαρτωλοις]{.greek-omitted} [και]{.greek-omitted} εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} και πορνοις και φαρμακοις και ειδωλολατραις και [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν τη λιμνη τη καιομενη πυρι και θειω ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} θανατος [ο]{.greek-omitted} δευτερος[21:8]{.aside}

και ηλθεν [ε]{.unclear}ις [εκ]{.greek-omitted} των επτα αγγελων των εχοντων τας επτα φιαλας [τας]{.greek-added} γεμουσας [των]{.greek-omitted} επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την [γυναικα]{.greek-omitted} [την]{.greek-omitted} νυμφην του αρνιου [την]{.greek-added} [γυναικα]{.greek-added}[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εν [πνευματι]{.greek-abbr} επ ορος μεγα και υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι την πολιν την μεγαλην [την]{.greek-omitted} [και]{.greek-added} αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr}[21:10]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης ομοιος λιθω τιμιωτατω ως λιθω ιασπιδι [κρυσταλλιζοντι]{.greek-omitted} [κρυσταλιζοντι]{.greek-added}[21:11]{.aside}

εχουσα τειχος μεγα και υψηλον εχουσα πυλωνας δωδεκα και επι τοις πυλωσιν αγγελους δωδεκα [και]{.greek-omitted} ονοματα επιγεγραμμενα α [εστιν]{.greek-omitted} [εστι]{.greek-added} [ονοματα]{.greek-omitted} των δωδεκα φυλ[ω]{.unclear}ν [του]{.greek-added} [των]{.greek-omitted} [υιων]{.greek-omitted} [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο [ανατολων]{.greek-omitted} [ανατολης]{.greek-added} πυλωνες τρεις [και]{.greek-omitted} απο βορρα πυλωνες τρεις και απο νοτου πυλωνες τρεις και απο δυσμων πυλωνες τρεις[21:13]{.aside}

και το τειχος της πολεως εχον θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} μετρον καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν [εν]{.greek-added} τω καλαμω επι [σταδιων]{.greek-added} [σταδιους]{.greek-omitted} [δωδεκα]{.greek-omitted} χιλιαδων δωδεκα το μηκος [και]{.greek-omitted} [αυτης]{.greek-added} [οσον]{.greek-added} το πλατος και το υψος αυτης ισα [εστιν]{.greek-omitted} [εστι]{.greek-added}[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} το τειχος αυτης εκατον [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον ομοιον [υελω]{.greek-omitted} [υαλω]{.greek-added} καθαρω[21:18]{.aside}

[και]{.greek-added} οι θεμελιοι του τειχους της πολεως παντι λιθω τιμιω κεκοσμημενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος [λιθος]{.greek-added} [σαπφειρος]{.greek-omitted} [σαπφιρος]{.greek-added} ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος [σαρδονυξ]{.greek-omitted} [σαρδωνυξ]{.greek-added} ο εκτος [σαρδιον]{.greek-omitted} [σαρδιος]{.greek-added} ο εβδομος χρυσολιθος ο ογδοος [βηρυλλος]{.greek-omitted} [βηρυλλιος]{.greek-added} ο ενατος τοπαζιον ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος ο δωδεκατος αμεθυσος[21:20]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται ανα εις εκαστος των πυλωνων ην [ως]{.greek-added} εξ ενος μαργαριτου και η πλατεια της πολεως χρυσιον καθαρον ως [υελος]{.greek-omitted} [υαλος]{.greek-added} διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν [αυτη]{.greek-omitted} [αυτην]{.greek-added} η γαρ δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης [φερουσιν]{.greek-omitted} [φερουσι]{.greek-added} [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν και [την]{.greek-added} τιμην [των]{.greek-omitted} [αυτων]{.greek-added} [εθνων]{.greek-omitted} εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην[21:26]{.aside}

και ου μη εισελθη εις αυτην παν κοινον [και]{.greek-omitted} ποιουν βδελυγμα [και]{.greek-omitted} [η]{.greek-added} ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον καθαρον υδατος ζωης λαμπρον ως κρυσταλλον εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και [εκειθεν]{.greek-omitted} [εντευθεν]{.greek-added} ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα εκαστον [αποδιδους]{.greek-omitted} [αποδιδουν]{.greek-added} τον καρπον αυτου και τα φυλλα του ξυλου εις θεραπειαν των εθνων[22:2]{.aside}

και παν κα[τα]{.unclear}θεμα ουκ εσται [ετι]{.greek-omitted} [εκει]{.greek-added} και ο θρονος του [θεου]{.greek-abbr} και του αρνιου [εν]{.unclear} αυτη εσται και οι δουλοι αυτου λατρευσουσιν αυτω[22:3]{.aside}

[και]{.unclear} [ο]{.unclear}ψονται το προσωπον αυτου και το ονομα αυτου [επ]{.unclear}ι των μετωπων αυτων[22:4]{.aside}

και νυξ ουκ εσται εκει και χρειαν [ο[υ]{.unclear}]{.greek-added} [χρειαν]{.greek-added} ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} [φωτος]{.greek-added} λυχνου και [φωτος]{.greek-omitted} ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [φωτιει]{.greek-omitted} [φωτ[ισ]{.unclear}ει]{.greek-added} [ει]{.greek-added} αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και [λεγει]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι οι λογοι [μου]{.greek-added} [αληθινοι]{.greek-added} [και]{.greek-added} πιστοι [και]{.greek-omitted} [αληθινοι]{.greek-omitted} [[ως]{.unclear}]{.greek-added} [[ε]{.unclear}κ]{.greek-added} [της]{.greek-added} [αληθειας]{.greek-added} [προφερομενοι]{.greek-added} και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-omitted} [αιων[ων]{.unclear}]{.greek-added} των προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου [δειξαι]{.greek-omitted} [διδαξαι]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} [δουλοις]{.greek-omitted} [δουλους]{.greek-added} αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

και ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

[καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} ιωαννης ο [βλεπων]{.greek-added} [και]{.greek-added} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} ταυτα [και]{.greek-omitted} οτε ηκουσα και εβλεψα επεσον προσκυνησαι εμπροσθεν των ποδων του αγγελου του δεικνυοντος μοι ταυτα[22:8]{.aside}

και λεγει μοι [μη]{.greek-added} ορα [μη]{.greek-omitted} συνδουλος σου ειμι και των αδελφων σου των προφητων και των τηρουντων τους λογους [της]{.greek-added} [προφητειας]{.greek-added} του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου ο [γαρ]{.greek-added} καιρος [γαρ]{.greek-omitted} εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος [ρυπαρευθητω]{.greek-omitted} [ρυπαρωθητω]{.greek-added} ετι και ο δικαιος [δικαιωθητω]{.greek-added} [δικαιοσυνην]{.greek-omitted} [ποιησατω]{.greek-omitted} ετι [και]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [αγιασθητω]{.greek-omitted} [ετι]{.greek-omitted}[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω [κατα]{.greek-added} [τα]{.greek-added} [εργα]{.greek-added} [ως]{.greek-omitted} [το]{.greek-omitted} [εργον]{.greek-omitted} [εσται]{.greek-omitted} αυτου[22:12]{.aside}

εγω το αλφα και το [ω]{.greek-abbr} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} ο πρωτος και ο εσχατος [η]{.greek-omitted} [αρχη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τελος]{.greek-omitted} [ουτε]{.greek-added} [προ]{.greek-added} [εμου]{.greek-added} [ουτε]{.greek-added} [μετ]{.greek-added} [εμε]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εστι]{.greek-added}[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι φονεις και οι ειδωλολατραι και πας φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα [επι]{.greek-omitted} [εν]{.greek-added} ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} [και]{.greek-added} ο αστηρ ο λαμπρος ο πρωινος[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν ερχου και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι τω ακουοντι τους λογους της προφητειας του βιβλιου τουτου εαν τις [επιθη]{.greek-omitted} [επιθησει]{.greek-added} επ αυτα [επιθησαι]{.greek-omitted} [επιθησει]{.greek-added} ο [θεος]{.greek-abbr} επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} τας [επτα]{.greek-added} πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και ε[αν]{.unclear} [τι]{.unclear}ς αφελη απο των λογων [της]{.greek-added} [προφητειας]{.greek-added} του βιβλιου [[τ]{.unclear}ουτου]{.greek-added} [της]{.greek-omitted} [προφητειας]{.greek-omitted} [ταυτης]{.greek-omitted} [αφελοι]{.greek-omitted} [αφελει]{.greek-added} ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν τω βιβλι[ω]{.unclear} [τ]{.unclear}ουτω[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην ναι ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντ[ω]{.unclear}ν των αγιων αμην[22:21]{.aside}

