---
title: "Collation of Byz^RP^ vs 31735 (1735)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1735 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31735).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1735                                   	| λογος                              	|
| 1735 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1735 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1735               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1735                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1735 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1735                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

τον μεν πρωτον λογον εποιησαμην περι παντων ω θεοφιλε ων ηρξατο ο [ιησους]{.greek-abbr} ποιειν τε και διδασκειν[1:1]{.aside}

αχρι ης ημερας εντειλαμενος τοις αποστολοις δια [πνευματος]{.greek-abbr} αγιου ους εξελεξατο ανεληφθη[1:2]{.aside}

οις και παρεστησεν εαυτον ζωντα μετα το παθειν αυτον εν πολλοις τεκμηριοις δι ημερων τεσσαρακοντα οπτανομενος αυτοις και λεγων τα περι της βασιλειας του [θεου]{.greek-abbr}[1:3]{.aside}

και συναλιζομενος παρηγγειλεν αυτοις απο ιεροσολυμων μη χωριζεσθαι αλλα περιμενειν την επαγγελιαν του [πατρος]{.greek-abbr} ην ηκουσατε μου[1:4]{.aside}

οτι ιωαννης μεν [εβαπτισεν]{.greek-omitted} [εβαπτησεν]{.greek-added} υδατι υμεις δε [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} εν [πνευματι]{.greek-abbr} αγιω ου μετα πολλας ταυτας ημερας[1:5]{.aside}

οι μεν ουν συνελθοντες επηρωτων αυτον λεγοντες [κυριε]{.greek-abbr} ει εν τω χρονω τουτω αποκαθιστανεις την βασιλειαν τω [ισραηλ]{.greek-abbr}[1:6]{.aside}

ειπεν δε προς αυτους ουχ υμων εστιν γνωναι χρονους η καιρους ους ο [πατηρ]{.greek-abbr} εθετο εν τη ιδια εξουσια[1:7]{.aside}

αλλα ληψεσθε δυναμιν επελθοντος του αγιου [πνευματος]{.greek-abbr} εφ υμας και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μοι μαρτυρες εν τε [ιερουσαλημ]{.greek-abbr} και εν παση τη ιουδαια και [σαμαρεια]{.greek-omitted} [σαμαρια]{.greek-added} και εως εσχατου της γης[1:8]{.aside}

και ταυτα ειπων βλεποντων αυτων επηρθη και νεφελη υπελαβεν αυτον απο των οφθαλμων αυτων[1:9]{.aside}

και ως ατενιζοντες ησαν εις τον [ουρανον]{.greek-abbr} πορευομενου αυτου και ιδου ανδρες δυο παρειστηκεισαν αυτοις εν εσθητι λευκη[1:10]{.aside}

οι και ειπον ανδρες γαλιλαιοι τι εστηκατε εμβλεποντες εις τον [ουρανον]{.greek-abbr} ουτος ο [ιησους]{.greek-abbr} ο αναληφθεις αφ υμων εις τον [ουρανον]{.greek-abbr} ουτως ελευσεται ον τροπον [εθεασασθε]{.greek-omitted} [εθεασασθαι]{.greek-added} αυτον πορευομενον εις τον [ουρανον]{.greek-abbr}[1:11]{.aside}

τοτε υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} απο ορους του καλουμενου ελαιωνος ο εστιν εγγυς [ιερουσαλημ]{.greek-abbr} σαββατου εχον οδον[1:12]{.aside}

και οτε εισηλθον ανεβησαν εις το υπερωον ου ησαν καταμενοντες ο τε πετρος και ιακωβος και ιωαννης και ανδρεας φιλιππος και θωμας βαρθολομαιος και ματθαιος ιακωβος αλφαιου και σιμων ο ζηλωτης και ιουδας ιακωβου[1:13]{.aside}

ουτοι παντες ησαν προσκαρτερουντες ομοθυμαδον τη προσευχη και τη δεησει συν γυναιξιν και μαρια τη [μητρι]{.greek-abbr} του [ιησου]{.greek-abbr} και συν τοις αδελφοις αυτου[1:14]{.aside}

και εν ταις ημεραις ταυταις αναστας πετρος εν μεσω των μαθητων ειπεν ην τε οχλος ονοματων επι το αυτο ως εκατον εικοσι[1:15]{.aside}

ανδρες αδελφοι εδει πληρωθηναι την γραφην ταυτην ην προειπεν το [πνευμα]{.greek-abbr} το αγιον δια στοματος [δαυιδ]{.greek-abbr} περι ιουδα του γενομενου οδηγου τοις συλλαβουσιν τον [ιησουν]{.greek-abbr}[1:16]{.aside}

οτι [κατηριθμημενος]{.greek-omitted} [κατειριθμημενος]{.greek-added} ην συν ημιν και ελαχεν τον κληρον της διακονιας ταυτης[1:17]{.aside}

ουτος μεν ουν εκτησατο χωριον εκ μισθου της αδικιας και [πρηνης]{.greek-omitted} [πρινης]{.greek-added} γενομενος ελακησεν μεσος και εξεχυθη παντα τα σπλαγχνα αυτου[1:18]{.aside}

και γνωστον εγενετο πασιν τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} ωστε κληθηναι το χωριον εκεινο τη ιδια διαλεκτω αυτων ακελδαμα τουτ εστιν χωριον αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω ψαλμων γενηθητω η επαυλις αυτου ερημος και μη εστω ο κατοικων εν αυτη και την επισκοπην αυτου λαβοι ετερος[1:20]{.aside}

δει ουν των συνελθοντων ημιν ανδρων εν παντι χρονω εν ω εισηλθεν και εξηλθεν εφ ημας ο [κυριος]{.greek-abbr} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βαπτισματος ιωαννου εως της ημερας ης ανεληφθη αφ ημων μαρτυρα της αναστασεως αυτου γενεσθαι συν ημιν ενα τουτων[1:22]{.aside}

και εστησαν δυο ιωσηφ τον καλουμενον [βαρσαβαν]{.greek-omitted} [βαρσαββαν]{.greek-added} ος επεκληθη ιουστος και ματθιαν[1:23]{.aside}

και προσευξαμενοι ειπον συ [κυριε]{.greek-abbr} καρδιογνωστα παντων αναδειξον ον εξελεξω εκ τουτων των δυο ενα[1:24]{.aside}

λαβειν τον κληρον της διακονιας ταυτης και αποστολης εξ ης παρεβη ιουδας πορευθηναι εις τον τοπον τον ιδιον[1:25]{.aside}

και εδωκαν κληρους αυτων και επεσεν ο κληρος επι ματθιαν και συγκατεψηφισθη μετα των ενδεκα αποστολων[1:26]{.aside}

### Chapter 2

και εν τω συμπληρουσθαι την ημεραν της [πεντηκοστης]{.greek-omitted} [πεντικοστης]{.greek-added} ησαν απαντες ομοθυμαδον επι το αυτο[2:1]{.aside}

και εγενετο αφνω εκ του [ουρανου]{.greek-abbr} ηχος ωσπερ φερομενης [πνοης]{.greek-omitted} [πνωης]{.greek-added} βιαιας και επληρωσεν ολον τον οικον ου ησαν καθημενοι[2:2]{.aside}

και ωφθησαν αυτοις διαμεριζομεναι γλωσσαι ωσει πυρος [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} τε εφ ενα εκαστον αυτων[2:3]{.aside}

και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετεραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου αυτοις αποφθεγγεσθαι[2:4]{.aside}

ησαν δε εν [ιερουσαλημ]{.greek-abbr} κατοικουντες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο τον [ουρανον]{.greek-abbr}[2:5]{.aside}

γενομενης δε της φωνης ταυτης συνηλθεν το πληθος και συνεχυθη οτι ηκουον εις εκαστος τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

εξισταντο δε [παντες]{.greek-omitted} και εθαυμαζον λεγοντες προς αλληλους ουκ ιδου παντες ουτοι εισιν οι λαλουντες γαλιλαιοι[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η [εγεννηθημεν]{.greek-omitted} [εγενηθημεν]{.greek-added}[2:8]{.aside}

παρθοι και μηδοι και [ελαμιται]{.greek-omitted} [ελαμηται]{.greek-added} και οι κατοικουντες την μεσοποταμιαν ιουδαιαν τε και καππαδοκιαν ποντον και την ασιαν[2:9]{.aside}

φρυγιαν τε και [παμφυλιαν]{.greek-omitted} [πανφυλιαν]{.greek-added} αιγυπτον και τα μερη της λιβυης της κατα κυρηνην και οι επιδημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[ιουδαιοι]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [προσηλυτοι]{.greek-added} κρητες και αραβες ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα [μεγαλεια]{.greek-omitted} [μεγαλια]{.greek-added} του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε παντες και διηπορουν αλλος προς αλλον λεγοντες τι αν θελοι τουτο ειναι[2:12]{.aside}

ετεροι δε χλευαζοντες ελεγον οτι [γλευκους]{.greek-omitted} [χλευκους]{.greek-added} μεμεστωμενοι εισιν[2:13]{.aside}

σταθεις δε πετρος συν τοις ενδεκα επηρεν την φωνην αυτου και απεφθεγξατο αυτοις ανδρες ιουδαιοι και οι κατοικουντες [ιερουσαλημ]{.greek-abbr} απαντες τουτο υμιν γνωστον εστω και [ενωτισασθε]{.greek-omitted} [ενωτησασθαι]{.greek-added} τα ρηματα μου[2:14]{.aside}

ου γαρ ως υμεις [υπολαμβανετε]{.greek-omitted} [υπολαμβανεται]{.greek-added} ουτοι μεθυουσιν εστιν γαρ ωρα τριτη της ημερας[2:15]{.aside}

αλλα τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το ειρημενον δια του προφητου ιωηλ[2:16]{.aside}

και εσται εν ταις εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υιοι [υμων]{.greek-omitted} [ημων]{.greek-added} και αι [θυγατερες]{.greek-omitted} [θυγατεραις]{.greek-added} [υμων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted} υμων ορασεις οψονται και οι πρεσβυτεροι υμων ενυπνια ενυπνιασθ[ησον]{.greek-supplied}ται[2:17]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις εκχεω απο του [πνευματος]{.greek-abbr} μου και προφητευσουσιν[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω και σημεια επι της γης κατω αιμα και πυρ και [ατμιδα]{.greek-omitted} [ατμηδα]{.greek-added} καπνου[2:19]{.aside}

ο ηλιος μεταστραφησεται [ει]{.greek-added} [εις]{.corr} σκοτος και η σεληνη εις αιμα πριν [η]{.greek-omitted} ελθειν την ημεραν [κυριου]{.greek-abbr} την μεγαλην και [επιφανη]{.greek-omitted} [επιφανει]{.greek-added}[2:20]{.aside}

και εσται πας ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθησεται[2:21]{.aside}

ανδρες ισραηλιται ακουσατε τους λογους τουτους [ιησουν]{.greek-abbr} τον ναζωραιον ανδρα απο του [θεου]{.greek-abbr} αποδεδειγμενον εις υμας [δυναμεσιν]{.greek-omitted} [δυναμεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και [σημειοις]{.greek-omitted} [σημιοις]{.greek-added} οις εποιησεν δι αυτου ο [θεος]{.greek-abbr} εν μεσω υμων καθως και αυτοι οιδατε[2:22]{.aside}

τουτον τη ωρισμενη βουλη και προγνωσει του [θεου]{.greek-abbr} εκδοτον λαβοντες δια χειρων ανομων [προσπηξαντες]{.greek-omitted} [προσπιξαντες]{.greek-added} [ανειλετε]{.greek-omitted} [ανειλαται]{.greek-added}[2:23]{.aside}

ον ο [θεος]{.greek-abbr} ανεστησεν λυσας τας [ωδινας]{.greek-omitted} [ωδηνας]{.greek-added} του θανατου καθοτι ουκ ην δυνατον κρατεισθαι αυτον υπ αυτου[2:24]{.aside}

[δαυιδ]{.greek-abbr} γαρ λεγει εις αυτον [προωρωμην]{.greek-omitted} [προορωμην]{.greek-added} τον [κυριον]{.greek-abbr} ενωπιον μου δια παντος οτι εκ δεξιων μου εστιν ινα μη σαλευθω[2:25]{.aside}

δια τουτο ευφρανθη η καρδια μου και ηγαλλιασατο η γλωσσα μου ετι δε και η σαρξ μου κατασκηνωσει επ [ελπιδι]{.greek-omitted} [ελπιδη]{.greek-added}[2:26]{.aside}

οτι ουκ [εγκαταλειψεις]{.greek-omitted} [εγκαταλιψεις]{.greek-added} την ψυχην μου εις αδου ουδε δωσεις τον οσιον σου ιδειν διαφθοραν[2:27]{.aside}

εγνωρισας μοι οδους ζωης πληρωσεις με ευφροσυνης μετα του προσωπου σου[2:28]{.aside}

ανδρες αδελφοι εξον ειπειν μετα παρρησιας προς υμας περι του πατριαρχου [δαυιδ]{.greek-abbr} οτι και ετελευτησεν και εταφη και το μνημα αυτου εστιν εν ημιν αχρι της ημερας ταυτης[2:29]{.aside}

προφητης ουν υπαρχων και ειδως οτι ορκω [ωμοσεν]{.greek-omitted} [ομωσεν]{.greek-added} αυτω ο [θεος]{.greek-abbr} εκ καρπου της οσφυος αυτου το κατα [σ]{.unclear}αρκα [αναστησειν]{.greek-omitted} [αναστησιν]{.greek-added} τον [χριστον]{.greek-abbr} [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} επι του θρονου αυτου[2:30]{.aside}

προιδων ελαλησεν περι της αναστασεως του [χριστου]{.greek-abbr} οτι ου [κατελειφθη]{.greek-omitted} [κατεληφθη]{.greek-added} η ψυχη αυτου εις αδου ουδε η σαρξ αυτου ειδεν διαφθοραν[2:31]{.aside}

τουτον τον [ιησουν]{.greek-abbr} ανεστησεν ο [θεος]{.greek-abbr} ου παντες ημεις εσμεν μαρτυρες[2:32]{.aside}

τη δεξια ουν του [θεου]{.greek-abbr} υψωθεις την τε επαγγελιαν του αγιου [πνευματος]{.greek-abbr} λαβων παρα του [πατρος]{.greek-abbr} εξεχεεν τουτο ο νυν υμεις [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} και [ακουετε]{.greek-omitted} [ακουεται]{.greek-added}[2:33]{.aside}

ου γαρ [δαυιδ]{.greek-abbr} [ανεβη]{.greek-omitted} [ανεβει]{.greek-added} εις τους [ουρανους]{.greek-abbr} λεγει δε αυτος ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου[2:34]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[2:35]{.aside}

ασφαλως ουν γινωσκετω πας οικος [ισραηλ]{.greek-abbr} οτι και [κυριον]{.greek-abbr} και [χριστον]{.greek-abbr} αυτον ο [θεος]{.greek-abbr} εποιησεν τουτον τον [ιησουν]{.greek-abbr} ον υμεις εσταυρωσατε[2:36]{.aside}

ακουσαντες δε κατενυγησαν τη καρδια ειπον τε προς τον πετρον και τους λοιπους αποστολους τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} ανδρες αδελφοι[2:37]{.aside}

πετρος δε εφη προς αυτους μετανοησατε [και]{.greek-omitted} [φησιν]{.greek-added} βαπτισθητω εκαστος υμων επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εις αφεσιν αμαρτιων και [ληψεσθε]{.greek-omitted} [λειψεσθε]{.greek-added} την δωρεαν του αγιου [πνευματος]{.greek-abbr}[2:38]{.aside}

υμιν γαρ εστιν η επαγγελια και τοις τεκνοις υμων και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εις μακραν οσους αν [προσκαλεσηται]{.greek-omitted} [προσκαλεσητε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων[2:39]{.aside}

ετεροις τε λογοις [πλειοσιν]{.greek-omitted} [πλειοσι]{.greek-added} διεμαρτυρετο και παρεκαλει [αυτους]{.greek-added} λεγων σωθητε απο της γενεας της σκολιας ταυτης[2:40]{.aside}

οι μεν ουν ασμενως αποδεξαμενοι τον λογον αυτου [εβαπτισθησαν]{.greek-omitted} [εβαπτησθησαν]{.greek-added} και προσετεθησαν τη ημερα εκεινη ψυχαι ωσει τρισχιλιαι[2:41]{.aside}

ησαν δε προσκαρτερουντες τη [διδαχη]{.greek-omitted} [δδαχη]{.greek-added} των αποστολων και τη κοινωνια και τη κλασει του αρτου και ταις προσευχαις[2:42]{.aside}

εγενετο δε παση ψυχη φοβος πολλα τε τερατα και σημεια δια των αποστολων [εγινετο]{.greek-omitted} [εγεινετο]{.greek-added}[2:43]{.aside}

παντες δε οι [πιστευοντες]{.greek-omitted} [πιστευσαντες]{.greek-added} ησαν επι το αυτο και ειχον απαντα κοινα[2:44]{.aside}

και τα [κτηματα]{.greek-omitted} [κτιματα]{.greek-added} και τας υπαρξεις επιπρασκον και διεμεριζον αυτα πασιν καθοτι αν τις χρειαν ειχεν[2:45]{.aside}

καθ ημεραν τε προσκαρτερουντες ομοθυμαδον εν τω ιερω [κλωντες]{.greek-omitted} [κλατες]{.greek-added} τε κατ οικον αρτον μετελαμβανον τροφης εν [αγαλλιασει]{.greek-omitted} [αγαλληασει]{.greek-added} και αφελοτητι καρδιας[2:46]{.aside}

αινουντες τον [θεον]{.greek-abbr} και εχοντες χαριν προς ολον τον λαον ο δε [κυριος]{.greek-abbr} [προσετιθει]{.greek-omitted} [προσετεθη]{.greek-added} τους σωζομενους καθ ημεραν τη εκκλησια[2:47]{.aside}

### Chapter 3

επι το αυτο δε πετρος και ιωαννης ανεβαινον εις το ιερον επι την ωραν της προσευχης την [ενατην]{.greek-omitted} [εννατην]{.greek-added}[3:1]{.aside}

και τις ανηρ χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων εβασταζετο ον ετιθουν καθ ημεραν προς την θυραν του ιερου την λεγομενην ωραιαν του αιτειν ελεημοσυνην παρα των εισπορευομενων εις το ιερον[3:2]{.aside}

ος ιδων πετρον και ιωαννην μελλοντας [εισιεναι]{.greek-omitted} [εισειεναι]{.greek-added} εις το ιερον ηρωτα ελεημοσυνην [λαβειν]{.greek-added}[3:3]{.aside}

ατενισας δε πετρος εις αυτον συν τω ιωαννη ειπεν βλεψον εις ημας[3:4]{.aside}

ο δε επειχεν αυτοις προσδοκων τι παρ αυτων λαβειν[3:5]{.aside}

ειπεν δε πετρος αργυριον και χρυσιον ουχ υπαρχει μοι ο δε εχω τουτο σοι διδωμι εν [τω]{.greek-omitted} [το]{.greek-added} ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[3:6]{.aside}

και πιασας αυτον της δεξιας χειρος ηγειρεν παραχρημα δε εστερεωθησαν αυτου αι βασεις και τα σφυρα[3:7]{.aside}

και εξαλλομενος [εστη]{.greek-omitted} [εστει]{.greek-added} και περιεπατει και εισηλθεν συν αυτοις εις το ιερον [και]{.greek-added} περιπατων και αλλομενος και αινων τον [θεον]{.greek-abbr}[3:8]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτον πας ο λαος περιπατουντα και αινουντα τον [θεον]{.greek-abbr}[3:9]{.aside}

επεγινωσκον τε αυτον οτι ουτος ην ο προς την ελεημοσυνην καθημενος επι τη ωραια πυλη του ιερου και επλησθησαν θαμβους και εκστασεως επι [τω]{.greek-omitted} [το]{.greek-added} [συμβεβηκοτι]{.greek-omitted} [συμβεβηκωτι]{.greek-added} αυτω[3:10]{.aside}

κρατουντος δε του ιαθεντος χωλου τον πετρον και ιωαννην συνεδραμεν προς αυτους πας ο λαος επι τη στοα τη καλουμενη [σολομωντος]{.greek-omitted} [σολομοντος]{.greek-added} εκθαμβοι[3:11]{.aside}

ιδων δε πετρος [απεκρινατο]{.greek-omitted} [απεκρηνατο]{.greek-added} προς τον λαον ανδρες ισραηλιται τι [θαυμαζετε]{.greek-omitted} [θαυμαζεται]{.greek-added} επι [τουτω]{.greek-omitted} [τουτο]{.greek-added} η ημιν τι ατενιζετε ως ιδια δυναμει η ευσεβεια πεποιηκοσιν του περιπατειν αυτο[ν]{.unclear}[3:12]{.aside}

ο [θεος]{.greek-abbr} αβρααμ και ισαακ και ιακωβ ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων εδοξασεν τον παιδα αυτου [ιησουν]{.greek-abbr} ον υμεις μεν παρεδωκατε και [ηρνησασθε]{.greek-omitted} [ηρνησασθαι]{.greek-added} αυτον κατα προσωπον [πιλατου]{.greek-omitted} [πηλατου]{.greek-added} κριναντος εκεινου απολυειν[3:13]{.aside}

υμεις δε τον αγιον και δικαιον [ηρνησασθε]{.greek-omitted} [ηρνησασθαι]{.greek-added} και ητησασθε ανδρα φονεα χαρισθηναι υμιν[3:14]{.aside}

τον δε αρχηγον της ζωης απεκτεινατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων ου ημεις μαρτυρες εσμεν[3:15]{.aside}

και επι τη πιστει του ονοματος αυτου τουτον ον [θεωρειτε]{.greek-omitted} [θεορειτε]{.greek-added} και οιδατε εστερεωσεν το ονομα αυτου και η [πιστις]{.greek-omitted} [πιστης]{.greek-added} η δι αυτου εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[3:16]{.aside}

και νυν αδελφοι οιδα οτι κατα αγνοιαν επραξατε ωσπερ και οι αρχοντες υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α προκατηγγειλεν δια στοματος παντων των προφητων αυτου παθειν τον [χριστον]{.greek-abbr} επληρωσεν ουτως[3:18]{.aside}

μετανοησατε ουν και επιστρεψατε εις το [εξαλειφθηναι]{.greek-omitted} [εξαληφθηναι]{.greek-added} υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσιν]{.greek-added} [καιροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και [αποστειλη]{.greek-omitted} [αποστηλη]{.greek-added} τον [προκεχειρισμενον]{.greek-omitted} [προκεχηρισμενον]{.greek-added} υμιν [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[3:20]{.aside}

ον δει [ουρανον]{.greek-abbr} μεν δεξασθαι αχρι χρονων αποκαταστασεως παντων ων ελαλησεν ο [θεος]{.greek-abbr} δια στοματος παντων των αγιων αυτου προφητων απ αιωνος[3:21]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} μεν γαρ προς τους [πατερας]{.greek-abbr} ειπεν οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε αυτου [ακουσεσθε]{.greek-omitted} [ακουσεσθαι]{.greek-added} κατα παντα οσα αν [λαληση]{.greek-omitted} [λαλησει]{.greek-added} προς υμας[3:22]{.aside}

εσται δε πασα ψυχη ητις εαν μη [ακουση]{.greek-omitted} [ακουσει]{.greek-added} του προφητου εκεινου εξολοθρευθησεται εκ του λαου[3:23]{.aside}

και παντες δε οι προφηται απο σαμουηλ και των καθεξης οσοι ελαλησαν και κατηγγειλαν τας ημερας ταυτας[3:24]{.aside}

υμεις [εστε]{.greek-omitted} [εσται]{.greek-added} υιοι των προφητων και της διαθηκης ης [διεθετο]{.greek-omitted} [διε]{.greek-added} [θετο]{.greek-added} ο [θεος]{.greek-abbr} προς τους [πατερας]{.greek-abbr} ημων λεγων προς αβρααμ και εν τω σπερματι σου ενευλογηθησονται πασαι αι πατριαι της γης[3:25]{.aside}

υμιν πρωτον ο [θεος]{.greek-abbr} αναστησας τον παιδα αυτου [ιησουν]{.greek-abbr} απεστειλεν αυτον ευλογουντα υμας εν τω αποστρεφειν εκαστον απο των πονηριων υμων[3:26]{.aside}

### Chapter 4

λαλουντων δε αυτων προς τον λαον επεστησαν αυτοις οι ιερεις και ο στρατηγος του ιερου και οι [σαδδουκαιοι]{.greek-omitted} [σαδουκαιοι]{.greek-added}[4:1]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον λαον και καταγγελλειν εν τω [ιησου]{.greek-omitted} [[ιησουν]{.greek-abbr}]{.greek-added} την αναστασιν των νεκρων[4:2]{.aside}

και [επεβαλον]{.greek-omitted} [επεβαλλον]{.greek-added} αυτοις τας χειρας και εθεντο εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι δε των ακουσαντων τον λογον επιστευσαν και εγενηθη ο αριθμος των ανδρων ωσει χιλιαδες πεντε[4:4]{.aside}

εγενετο δε επι την αυριον συναχθηναι αυτων τους αρχοντας και πρεσβυτερους και γραμματεις εις [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και ανναν τον αρχιερεα και καιαφαν και ιωαννην και αλεξανδρον και οσοι ησαν εκ γενους αρχιερατικου[4:6]{.aside}

και στησαντες αυτους εν μεσω [επυνθανοντο]{.greek-omitted} [εποινθανοντο]{.greek-added} εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος πλησθεις [πνευματος]{.greek-abbr} αγιου ειπεν προς αυτους αρχοντες του λαου και πρεσβυτεροι του [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα επι ευεργεσια [ανθρωπου]{.greek-abbr} ασθενους εν τινι ουτος σεσωσται[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω [ισραηλ]{.greek-abbr} οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις εσταυρωσατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν τουτω ουτος παρεστηκεν ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ υμων των οικοδομουντων ο γενομενος εις κεφα[λην]{.unclear} γωνιας[4:11]{.aside}

και ουκ εστιν εν αλλω ουδενι η [σωτηρια]{.greek-abbr} ουτε γαρ ονομα εστιν ετερον [υπο]{.greek-added} [των]{.greek-added} [[ουρανον]{.greek-abbr}]{.greek-added} το δεδομενον εν [ανθρωποις]{.greek-abbr} εν ω δει σωθηναι ημας[4:12]{.aside}

θεωρουντες δε [οι]{.greek-added} [ιουδαιοι]{.greek-added} την του πετρου παρρησιαν και ιωαννου και καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι εισιν και ιδιωται εθαυμαζον επεγινωσκον τε αυτους οτι συν τω [ιησου]{.greek-abbr} ησαν[4:13]{.aside}

τον δε [ανθρωπον]{.greek-abbr} βλεποντες συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου α[π]{.unclear}ελθειν συνεβαλλον προς αλληλους[4:15]{.aside}

[λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} τοις [ανθρωποις]{.greek-abbr} τουτοι[ς]{.unclear} οτι μεν γαρ γνωστον σημειον γεγονεν δι αυτων πασιν τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} φανερον και ου δυναμεθα αρνησασθαι[4:16]{.aside}

αλλ ινα μη επι πλειον διανεμηθη εις τον λαον απειλη [απειλησομεθα]{.greek-omitted} [απειλησωμεθα]{.greek-added} αυτοις μηκετι λαλειν επι τω ονοματι τουτω μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και καλεσαντες αυτους παρηγγειλαν αυτοις το καθολου μη φθεγγεσθαι μηδε διδασκειν επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

ο δε πετρος και ιωαννης [αποκριθεντες]{.greek-omitted} [αποκρηθεντες]{.greek-added} προς αυτους ειπον ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ ημεις α ειδομεν και ηκουσαμεν μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως κολασονται αυτους δια τον λαον οτι παντες εδοξαζον τον [θεον]{.greek-abbr} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων τεσσαρακοντα ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε ηλθον προς τους ιδιους και απηγγειλαν οσα προς αυτους οι αρχιερεις και οι [πρεσβυτεροι]{.greek-omitted} [πρεσβυ]{.greek-added} [τεροι]{.greek-added} ειπον[4:23]{.aside}

οι δε ακουσαντες ομοθυμαδον ηραν φωνην προς τον [θεον]{.greek-abbr} και ειπον δεσποτα συ ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[4:24]{.aside}

ο δια στοματος [δαυιδ]{.greek-abbr} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

[παρεστησαν]{.greek-omitted} [παρεστισαν]{.greek-added} οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας [εν]{.greek-added} [τη]{.greek-added} [πολει]{.greek-added} [ταυτη]{.greek-added} επι τον αγιον παιδα σου [ιησουν]{.greek-abbr} ον εχρισας ηρωδης τε και ποντιος [πιλατος]{.greek-omitted} [πηλατος]{.greek-added} συν εθνεσιν και λαοις [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η βουλη σου [προωρισεν]{.greek-omitted} [προωρησεν]{.greek-added} γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} [επιδε]{.greek-omitted} [επειδε]{.greek-added} επι τας απειλας αυτων και δος τοις δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την [χειρα]{.greek-omitted} [χειραν]{.greek-added} σου εκτεινειν σε εις ιασιν και σημεια και τερατα γινεσθαι δια του ονοματος του αγιου παιδος σου [ιησου]{.greek-abbr}[4:30]{.aside}

και δεηθεντων αυτων εσαλευθη ο τοπος εν ω ησαν συνηγμενοι και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ελαλουν τον λογον του [θεου]{.greek-abbr} μετα παρρησιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και ουδε εις τι των υπαρχοντων [αυτων]{.greek-omitted} ελεγεν ιδιον ειναι αλλ ην αυτοις απαντα κοινα[4:32]{.aside}

και μεγαλη δυναμει απεδιδουν το μαρτυριον οι αποστολοι της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} χαρις τε μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις [υπηρχεν]{.greek-omitted} [υπειρχεν]{.greek-added} εν αυτοις οσοι γαρ κτητορες χωριων η [οικιων]{.greek-omitted} [οικηων]{.greek-added} υπηρχον [πωλουντες]{.greek-omitted} [πολουντες]{.greek-added} εφερον τας τιμας των πιπρασκομενων[4:34]{.aside}

και ετιθουν παρα τους ποδας των αποστολων [διεδιδοτο]{.greek-omitted} [διεδιδετο]{.greek-added} δε εκαστω καθοτι αν τις [χρειαν]{.greek-omitted} [χριαν]{.greek-added} ειχεν[4:35]{.aside}

[ιωσης]{.greek-omitted} [ιωσηφ]{.greek-added} δε ο επικληθεις βαρναβας απο των αποστολων ο εστιν [μεθερμηνευομενον]{.greek-omitted} [μεθερμεινευομενον]{.greek-added} υιος παρακλησεως λευιτης κυπριος τω γενει[4:36]{.aside}

[υπαρχοντος]{.greek-omitted} [υπαρχωντος]{.greek-added} αυτω αγρου [πωλησας]{.greek-omitted} [πολησας]{.greek-added} ηνεγκεν το χρημα και εθηκεν παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις ανανιας ονοματι συν [σαπφειρη]{.greek-omitted} [σαπφηρη]{.greek-added} τη γυναικι αυτου επωλησεν κτημα[5:1]{.aside}

και [ενοσφισατο]{.greek-omitted} [ενοσφησατο]{.greek-added} απο της τιμης συνειδυιας και της γυναικος αυτου και ενεγκας μερος τι παρα τους ποδας των αποστολων εθηκεν[5:2]{.aside}

ειπεν δε πετρος ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι [σε]{.greek-omitted} απο της τιμης του χωριου[5:3]{.aside}

ουχι μενον σοι εμενεν και πραθεν εν τη ση εξουσια [υπηρχεν]{.greek-omitted} [υπειρχεν]{.greek-added} τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε ο ανανιας τους λογους τουτους πεσων εξεψυξεν και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι νεωτεροι συνεστειλαν αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων [διαστημα]{.greek-omitted} [διαστιμα]{.greek-added} και η γυνη [αυτου]{.corr} μη ειδυια το γεγονος εισηλθεν[5:7]{.aside}

απεκριθη δε αυτη ο πετρος ειπε μοι ει τοσουτου το χωριον απεδοσθε η δε ειπεν ναι τοσουτου[5:8]{.aside}

ο δε πετρος ειπεν προς αυτην τι οτι συνεφωνηθη υμιν πειρασαι το [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ιδου οι ποδες των θαψαντων τον ανδρα σου επι τη θυρα και [εξοισουσιν]{.greek-omitted} [εξυσουσιν]{.greek-added} σε[5:9]{.aside}

επεσεν δε παραχρημα παρα τους ποδας αυτου και εξεψυξεν εισελθοντες δε οι νεανισκοι ευρον αυτην νεκραν και εξενεγκαντες εθαψαν προς τον ανδρα αυτης[5:10]{.aside}

και εγενετο φοβος μεγας εφ ολην την εκκλησιαν και επι παντας τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων [εγινετο]{.greek-omitted} [εγενετο]{.greek-added} σημεια και τερατα εν τω λαω πολλα και ησαν ομοθυμαδον απαντες εν τη στοα [σολομωντος]{.greek-omitted} [σολομοντος]{.greek-added}[5:12]{.aside}

[των]{.greek-omitted} [τον]{.greek-added} δε λοιπων ουδεις ετολμα κολλασθαι αυτοις αλλ εμεγαλυνεν αυτους [πας]{.greek-added} ο λαος[5:13]{.aside}

μαλλον δε προσετιθεντο πιστευοντες τω [κυριω]{.greek-abbr} πληθη ανδρων τε και γυναικων[5:14]{.aside}

ωστε [κατα]{.greek-omitted} [και]{.greek-added} [εις]{.greek-added} τας πλατειας εκφερειν τους ασθενεις και τιθεναι επι [κλινων]{.greek-omitted} [κληνων]{.greek-added} και [κραββατων]{.greek-omitted} [κραβατ[τ]{.unclear}ων]{.greek-added} ινα ερχομενου πετρου καν η σκια [επισκιαση]{.greek-omitted} [επισκιασει]{.greek-added} τινι αυτων[5:15]{.aside}

συνηρχετο δε και το πληθος των περιξ πολεων εις [ιερουσαλημ]{.greek-abbr} φεροντες ασθενεις και οχλουμενους υπο πνευματων ακαθαρτων οιτινες εθεραπευοντο απαντες[5:16]{.aside}

αναστας δε ο αρχιερευς και παντες οι συν αυτω η ουσα [αιρεσις]{.greek-omitted} [αιρεσεις]{.greek-added} των σαδδουκαιων επλησθησαν ζηλου[5:17]{.aside}

και [επεβαλον]{.greek-omitted} [επεβαλλον]{.greek-added} τας χειρας αυτων επι τους αποστολους και εθεντο αυτους εν τηρησει δημοσια[5:18]{.aside}

αγγελος δε [κυριου]{.greek-abbr} δια της νυκτος ηνοιξεν τας θ[υ]{.unclear}ρας της φυλακης εξαγαγων τε αυτους ειπεν[5:19]{.aside}

πορευεσθε και σταθεντες [λαλητε]{.greek-added} [λαλ[ε]{.unclear}ιτε]{.corr} εν τω ιερω τω λαω παντα τα ρηματα της ζωης ταυτης[5:20]{.aside}

ακουσαντες δε εισηλθον υπο τον ορθρον εις το ιερον και εδιδασκον παραγενομενος δε ο αρχιερευς και οι συν αυτω συνεκαλεσαν το συνεδριον και πασαν την γερουσιαν των υιων [ισραηλ]{.greek-abbr} και απεστειλαν εις το δεσμωτηριον αχθηναι αυτους[5:21]{.aside}

οι δε υπηρεται παραγενομενοι ουχ ευρον αυτους εν τη φυλακη αναστρεψαντες δε απηγγειλαν[5:22]{.aside}

λεγοντες οτι το μεν δεσμ[ω]{.unclear}τηριον ευρομεν [κεκλεισμενον]{.greek-omitted} [κεκλησμενον]{.greek-added} εν παση ασφαλεια και τους φυλακας εστωτας προ των θυρων ανοιξαντες δε εσω ουδενα ευρομεν[5:23]{.aside}

ως δε ηκουσαν τους λογους τουτους ο τε ιερευς και ο στρατηγος του ιερου και οι αρχιερεις διηπορουν περι αυτων τι αν γενοιτο τουτο[5:24]{.aside}

παρ[α]{.unclear}γενομενος δε τις απηγγειλεν αυτοις οτι ιδου οι ανδρες ους εθεσθε εν τη φυλακη εισιν εν τω ιερω εστωτες και διδασκοντες τον λαον[5:25]{.aside}

τοτε απελθων ο στρατηγος συν τοις υπηρεταις ηγαγεν αυτους ου μετα βιας εφοβουντο γαρ τον λαον ινα μη λιθασθωσιν[5:26]{.aside}

αγαγοντες δε αυτους εστησαν εν τω συνεδριω και επηρωτησεν αυτους ο αρχιερευς[5:27]{.aside}

λεγων ου παραγγελια παρηγγειλαμεν υμιν μη διδασκειν επι τω ονοματι τουτω και ιδου πεπληρωκατε την [ιερουσαλημ]{.greek-abbr} της διδαχης υμων και βουλεσθε επαγαγειν εφ ημας το αιμα του [ανθρωπου]{.greek-abbr} τουτου[5:28]{.aside}

αποκριθεις δε πετρος και οι αποστολοι ειπον πειθαρχειν [δει]{.greek-omitted} [δε]{.greek-added} [θεω]{.greek-abbr} μαλλον η [ανθρωποις]{.greek-abbr}[5:29]{.aside}

ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων ηγειρεν [ιησουν]{.greek-abbr} ον υμεις [διεχειρισασθε]{.greek-omitted} [διεχειρησασθαι]{.greek-added} κρεμασαντες επι ξυλου[5:30]{.aside}

τουτον ο [θεος]{.greek-abbr} αρχηγον και [σωτηρα]{.greek-abbr} υψωσεν τη δεξια αυτου δουναι μετανοιαν τω [ισραηλ]{.greek-abbr} και αφεσιν αμαρτιων[5:31]{.aside}

και ημεις εσμεν αυτου μαρτυρες των ρηματων τουτων και το [πνευμα]{.greek-abbr} δε το αγιον ο εδωκεν ο [θεος]{.greek-abbr} τοις [πειθαρχουσιν]{.greek-omitted} [πειθαρχουσι]{.greek-added} αυτω[5:32]{.aside}

οι δε ακουοντες διεπριοντο και εβουλευοντο ανελειν αυτους[5:33]{.aside}

αναστας δε τις εν τω συνεδριω φαρισαιος ονοματι γαμαλιηλ νομοδιδασκαλος τιμιος παντι τω λαω εκελευσεν εξω βραχυ τι τους α[π]{.unclear}οστολους ποιησαι[5:34]{.aside}

ειπεν τε προς αυτους ανδρες ισραηλιται προσεχετε εαυτοις επι τοις ανθρωποις τουτοις τι μελλετε πρασσειν[5:35]{.aside}

προ γαρ τουτων των ημερων ανεστη θευδας λεγων ειναι τινα εαυτον ω [προσεκληθη]{.greek-omitted} [προσεκληθησαν]{.greek-added} αριθμος ανδρων ωσει τετρακοσιων ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις ουδεν[5:36]{.aside}

μετα τουτον ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της [απογραφης]{.greek-omitted} [απογραφεις]{.greek-added} και απεστησεν λαον ικανον οπισω αυτου κακεινος απωλετο και παντες οσοι επειθοντο αυτω [διεσκορπισθησαν]{.greek-omitted} [διεσκορπησθησαν]{.greek-added}[5:37]{.aside}

και τα νυν λεγω υμιν αποστητε απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε αυτους οτι εαν [ει]{.greek-added} η [βουλη]{.greek-added} [αυτη]{.greek-added} εξ [ανθρωπων]{.greek-abbr} [η]{.greek-omitted} [βουλη]{.greek-omitted} η το εργον τουτο καταλυθησεται[5:38]{.aside}

ει δε εκ [θεου]{.greek-abbr} εστιν ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} καταλυσαι αυτο μηποτε και θεομαχοι ευρεθητε [επεισθησαν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added}[5:39]{.aside}

[επεισθησαν]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} και προσκαλεσαμενοι τους αποστολους δειραντες παρηγγειλαν μη λαλειν επι [τω]{.greek-omitted} [το]{.greek-added} ονοματι του [ιησου]{.greek-abbr} και απελυσαν αυτους[5:40]{.aside}

οι μεν ουν επορευοντο χαιροντες απο προσωπου του συνεδριου οτι υπερ του ονοματος [του]{.greek-omitted} [αυτου]{.greek-added} [ιησου]{.greek-omitted} κατηξιωθησαν ατιμασθηναι[5:41]{.aside}

πασαν τε ημεραν εν τω ιερω και κατ οικον ουκ επαυοντο διδασκοντες και ευαγγελιζομενοι [ιησουν]{.greek-abbr} τον [χριστον]{.greek-abbr}[5:42]{.aside}

### Chapter 6

εν δε ταις ημεραις ταυταις πληθυνοντων των μαθητων εγενετο γογγυσμος των ελληνιστων προς τους εβραιους οτι [παρεθεωρουντο]{.greek-omitted} [παρεθεορουντο]{.greek-added} εν τη διακονια τη καθημερινη αι [χηραι]{.greek-omitted} [χειραι]{.greek-added} αυτων[6:1]{.aside}

προσκαλεσαμενοι δε οι δωδεκα το πληθος των μαθητων ειπον ουκ αρεστον εστιν ημας καταλειψαντας τον λογον του [θεου]{.greek-abbr} διακονειν τραπεζαις[6:2]{.aside}

επισκεψασθε ουν αδελφοι ανδρας εξ υμων μαρτυρουμενους επ[τ]{.unclear}α [πληρεις]{.greek-omitted} [πληρις]{.greek-added} [πνευματος]{.greek-abbr} αγιου και σοφιας ους καταστησωμεν επι της χρειας ταυτης[6:3]{.aside}

ημεις δε τη προσευχη και τη διακονια του λογου [προσκαρτερησομεν]{.greek-omitted} [προσκαρτερησωμεν]{.greek-added}[6:4]{.aside}

και ηρεσεν ο λογος ενωπιον παντος του πληθους και εξελεξαντο στεφανον ανδρα πληρης πιστεως και [πνευματος]{.greek-abbr} αγιου και φιλιππον και [προχορον]{.greek-omitted} [προχωρον]{.greek-added} και νικανορα και τιμωνα και παρμεναν και νικολαον προσηλυτον αντιοχεα[6:5]{.aside}

ους εστησαν ενωπιον των αποστολων και προσευξαμενοι επεθηκαν αυτοις τας χειρας[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} ηυξανεν και επληθυνετο ο αριθμος των μαθητων εν [ιερουσαλημ]{.greek-abbr} σφοδρα πολυς τε οχλος των ιερεων υπηκουον τη πιστει[6:7]{.aside}

στεφανος δε [πληρης]{.greek-omitted} [πληρις]{.greek-added} πιστεως και δυναμεως εποιει τερατα και σημεια μεγαλα εν τω λαω[6:8]{.aside}

ανεστησαν δε [τινες]{.greek-omitted} [τηνες]{.greek-added} των εκ της συναγωγης [της]{.greek-omitted} λεγομενης λιβερτινων και [κυρηναιων]{.greek-omitted} [κυριναιων]{.greek-added} και αλεξανδρεων και των απο [κιλικιας]{.greek-omitted} [[κ]{.unclear}ηλικιας]{.greek-added} και ασιας [συζητουντες]{.greek-omitted} [συνζητουντες]{.greek-added} τω στεφανω[6:9]{.aside}

και ουκ ισχυον αντιστηναι τη σοφια και τω [πνευματι]{.greek-abbr} ω ελαλει[6:10]{.aside}

τοτε [υπεβαλον]{.greek-omitted} [υπεβαλλον]{.greek-added} ανδρας λεγοντας οτι ακηκοαμεν αυτου λαλουντος ρηματα βλασφημα εις [μωσην]{.greek-omitted} [μωυσην]{.greek-added} και τον [θεον]{.greek-abbr}[6:11]{.aside}

[συνεκινησαν]{.greek-omitted} [συνεκηνισαν]{.greek-added} τε τον λαον και τους πρεσβυτερους και τους γραμματεις και επισταντες συνηρπασαν αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας [ψευδεις]{.greek-omitted} [ψευδης]{.greek-added} λεγοντας ο [ανθρωπος]{.greek-abbr} ουτος ου παυεται ρηματα βλασφημα λαλων κατα του τοπου του αγιου και του νομου[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος καταλυσει τον τοπον τουτον και [αλλαξει]{.greek-omitted} [αλλαξη]{.greek-added} τα εθη α [παρεδωκεν]{.greek-omitted} [περεδωκεν]{.greek-added} ημιν [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[6:14]{.aside}

και ατενισαντες εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω [ειδον]{.greek-omitted} [ιδον]{.greek-added} το προσωπον αυτου ωσει προσωπον αγγελου[6:15]{.aside}

### Chapter 7

ειπεν δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε [μου]{.greek-added} ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} ημων αβρααμ οντι εν τη [μεσοποταμια]{.greek-omitted} [μεσωποταμια]{.greek-added} πριν η κατοικησαι αυτον εν χαρραν[7:2]{.aside}

και ειπεν προς αυτον εξελθε εκ της γης σου και εκ της [συγγενειας]{.greek-omitted} [συγγενιας]{.greek-added} σου και [δευρο]{.greek-omitted} [δευρω]{.greek-added} εις γην ην αν σοι δειξω[7:3]{.aside}

τοτε εξελθων εκ γης χαλδαιων κατωκησεν εν χαρραν [και]{.greek-added} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μετωκησεν]{.greek-added} αυτον εις την γην ταυτην εις ην υμεις νυν [κατοικειτε]{.greek-omitted} [κατοικηται]{.greek-added}[7:4]{.aside}

και ουκ εδωκεν αυτω κληρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι αυτω εις κατασχεσιν αυτην και [τω]{.greek-omitted} [το]{.greek-added} σπερματι αυτου μετ αυτον ουκ οντος αυτω τεκνου[7:5]{.aside}

ελαλησεν δε ουτως ο [θεος]{.greek-abbr} οτι εσται το σπερμα αυτου παροικον εν γη α[λλο]{.greek-supplied}τρια και δουλωσουσιν αυτο και [κακωσουσιν]{.greek-omitted} [κακοσουσιν]{.greek-added} ετη τετρακοσια[7:6]{.aside}

και το εθνος [ω]{.greek-omitted} [ο]{.greek-added} εαν δουλευσωσιν κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και λατρευσουσιν μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και ουτως εγεννησεν τον ισαακ και περιετεμεν αυτον τη ημερα τη ογδοη και ο ισαακ τον ιακωβ και ο ιακωβ τους δωδεκα πατριαρχας[7:8]{.aside}

και οι πατριαρχαι ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και εξειλετο αυτον εκ πασων των [θλιψεων]{.greek-omitted} [θληψεων]{.greek-added} αυτου και εδωκεν αυτω χαριν και σοφιαν εναντιον φαραω βασιλεως αιγυπτου και κατεστησεν αυτον ηγουμενον επ αιγυπτον και ολον τον οικον αυτου[7:10]{.aside}

ηλθεν δε λιμος εφ ολην την γην αιγυπτου και χανααν και [θλιψις]{.greek-omitted} [θληψις]{.greek-added} μεγαλη και ουχ ευρισκον χορτασματα οι [πατερες]{.greek-abbr} ημων[7:11]{.aside}

ακουσας δε ιακωβ οντα σιτα εν αιγυπτω εξαπεστειλεν τους [πατερας]{.greek-abbr} ημων πρωτον[7:12]{.aside}

και εν τω δευτερω ανεγνωρισθη ιωσηφ τοις αδελφοις αυτου και φανερον εγενετο τω φαραω το γενος του ιωσηφ[7:13]{.aside}

αποστειλας δε ιωσηφ μετεκαλεσατο τον [πατερα]{.greek-abbr} αυτου ιακωβ και πασαν την [συγγενειαν]{.greek-omitted} [συγγενιαν]{.greek-added} εν ψυχαις εβδομηκοντα πεντε[7:14]{.aside}

κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν αυτος και οι [πατερες]{.greek-abbr} ημων[7:15]{.aside}

και μετετεθησαν εις συχεμ και ετεθησαν εν τω μνηματι ο ωνησατο αβρααμ τιμης αργυριου παρα των υιων [εμμορ]{.greek-omitted} [εμορ]{.greek-added} του συχεμ[7:16]{.aside}

καθως δε [ηγγιζεν]{.greek-omitted} [ηγγειζεν]{.greek-added} ο χρονος της επαγγελιας ης ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος ος ουκ [ηδει]{.greek-omitted} [ιδει]{.greek-added} τον ιωσηφ[7:18]{.aside}

ουτος κατασοφισαμενος το γενος ημων εκακωσεν τους [πατερας]{.greek-abbr} ημων του ποιειν εκθετα τα [βρεφη]{.greek-omitted} [βρεφει]{.greek-added} αυτων εις το μη ζωογονεισθαι[7:19]{.aside}

εν ω καιρω εγεννηθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ην αστειος τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr} [αυτου]{.greek-added}[7:20]{.aside}

εκτεθεντα δε αυτον [ανειλετο]{.greek-omitted} [ανειλατο]{.greek-added} [αυτον]{.greek-added} η θυγατηρ φαραω και ανεθρεψατο αυτον εαυτη εις [υιον]{.greek-abbr}[7:21]{.aside}

και επαιδευθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σοφια αιγυπτιων ην δε δυνατος εν λογοις και [εν]{.greek-added} εργοις [αυτου]{.greek-added}[7:22]{.aside}

ως δε επληρουτο αυτω [[αυτο]{.corr}]{.greek-added} τεσσαρακονταετης χρονος [ανεβη]{.greek-omitted} [ανεβει]{.greek-added} επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον ημυνατο και εποιησεν εκδικησιν τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

[ενομιζεν]{.greek-omitted} [ενωμηζεν]{.greek-added} δε συνιεναι τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις [σωτηριαν]{.greek-abbr} οι δε ου [συνηκαν]{.greek-omitted} [συνικαν]{.greek-added}[7:25]{.aside}

τη τε επιουση ημερα ωφθη αυτοις μαχομενοις και συνηλασεν αυτους εις ειρηνην ειπων ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} αδικειτε αλληλους[7:26]{.aside}

ο δε αδικων τον πλησιον απωσατο [αυτον]{.greek-omitted} [εαυτον]{.greek-added} ειπων τις σε κατεστησεν αρχοντα και δικαστην εφ ημας[7:27]{.aside}

μη ανελειν με συ θελεις ον τροπον [α]{.greek-supplied}νειλες χθες τον αιγυπτιον[7:28]{.aside}

εφυγεν δε μωσης εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων τεσσαρακοντα ωφθη αυτω εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-abbr} εν [φλογι]{.greek-omitted} [φλογη]{.greek-added} πυρος βατου[7:30]{.aside}

ο δε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ιδων εθαυμαζεν το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} προς αυτον[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} σου ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ εντρομος δε γενομενος [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουκ ετολμα κατανοησαι[7:32]{.aside}

ειπεν δε αυτω ο [κυριος]{.greek-abbr} λυσον το υποδημα [των]{.greek-omitted} [τον]{.greek-added} ποδων σου ο γαρ τοπος εν ω εστηκας γη αγια εστιν[7:33]{.aside}

[ιδων]{.greek-omitted} [ειδων]{.greek-added} [ειδον]{.greek-omitted} [ειδων]{.greek-added} την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και κατεβην εξελεσθαι αυτους και νυν [δευρο]{.greek-omitted} [δευρω]{.greek-added} αποστελω σε εις αιγυπτον[7:34]{.aside}

τουτον τον [μωσην]{.greek-omitted} [μωυσην]{.greek-added} ον [ηρνησαντο]{.greek-omitted} [ειρνησαντο]{.greek-added} ειποντες τις σε κατεστησεν αρχοντα και δικαστην [εφ]{.greek-added} [ημας]{.greek-added} τουτον ο [θεος]{.greek-abbr} αρχοντα και [λυτρωτην]{.greek-omitted} [λυτροτην]{.greek-added} απεστειλεν εν χειρι αγγελου του οφθεντος αυτω εν τη βατω[7:35]{.aside}

[ουτος]{.greek-omitted} [ουτως]{.greek-added} εξηγαγεν αυτους ποιησας τερατα και σημεια εν γη αιγυπτω και εν ερυθρα θαλασση και εν τη ερημω ετη τεσσαρακοντα[7:36]{.aside}

ουτος εστιν ο [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε [αυτου]{.greek-added} [ακουσεσθε]{.greek-added}[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο [λογον]{.greek-omitted} [λογια]{.greek-added} ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθελησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων αλλ απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

ειποντες τω ααρων ποιησον ημιν θεους οι προπορευσονται ημων ο γαρ [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις εκειναις και ανηγαγον θυσιαν τω [ειδωλω]{.greek-omitted} [ειδολω]{.greek-added} και ευφραινοντο εν τοις εργοις των χειρων αυτων[7:41]{.aside}

εστρεψεν δε ο [θεος]{.greek-abbr} και παρεδωκεν αυτους λατρευειν τη [στρατια]{.greek-omitted} [στρατηα]{.greek-added} του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη σφαγια και θυσιας προσηνεγκατε μοι ετη τεσσαρακοντα εν τη ερημω οικος [ισραηλ]{.greek-abbr}[7:42]{.aside}

και ανελαβετε την σκηνην του μολοχ και το αστρον του [θεου]{.greek-abbr} υμων ρεμφαν τους τυπους ους εποιησατε προσκυνειν αυτοις και μετο[ι]{.greek-supplied}κιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου ην [εν]{.greek-added} τοις πατρασιν ημων εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωυση]{.greek-added} ποιησαι αυτην κατα τον τυπον ον εωρακει[7:44]{.aside}

ην και εισηγαγον [δια]{.greek-added} [διαδεξαμενοι]{.greek-omitted} [δεξαμενοι]{.greek-added} οι [πατερες]{.greek-abbr} ημων μετα [ιησου]{.greek-abbr} εν τη κατασχεσει των εθνων ων εξωσεν ο [θεος]{.greek-abbr} απο προσωπου των [πατερων]{.greek-abbr} ημων εως των ημερων [δαυιδ]{.greek-abbr}[7:45]{.aside}

ος ευρεν χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν αυτω οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις ναοις κατοικει καθως ο προφητης λεγει[7:48]{.aside}

ο [ουρανος]{.greek-abbr} μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον [οικοδομησετε]{.greek-omitted} [οικοδομησατε]{.greek-added} μοι λεγει [κυριος]{.greek-abbr} η τις τοπος της καταπαυσεως μου[7:49]{.aside}

[ουχι]{.greek-omitted} [ουχη]{.greek-added} η χειρ μου [εποιησεν]{.greek-omitted} [εποιεισεν]{.greek-added} ταυτα παντα[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια και τοις ωσιν υμεις αει τω [πνευματι]{.greek-abbr} τω αγιω αντιπιπτετε ως οι [πατερες]{.greek-abbr} υμων και υμεις[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι [πατερες]{.greek-abbr} υμων και [απεκτειναν]{.greek-omitted} [απεκτηναν]{.greek-added} τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις προδοται και [φονεις]{.greek-omitted} [φωνεις]{.greek-added} γεγενησθε[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

ακουοντες δε ταυτα διεπριοντο ταις καρδιαις αυτων και εβρυχον τους οδοντας επ αυτον[7:54]{.aside}

υπαρχων δε [πληρης]{.greek-omitted} [πληρις]{.greek-added} [πνευματος]{.greek-abbr} αγιου ατενισας εις τον [ουρανον]{.greek-abbr} [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} δοξαν [θεου]{.greek-abbr} και [ιησουν]{.greek-abbr} εστωτα εκ δεξιων του [θεου]{.greek-abbr}[7:55]{.aside}

και ειπεν ιδου [θεωρω]{.greek-omitted} [θεορω]{.greek-added} τους [ουρανους]{.greek-abbr} ανεωγμενους και τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη συνεσχον τα ωτα αυτων και [ωρμησαν]{.greek-omitted} [ορμησαν]{.greek-added} ομοθυμαδον επ αυτον[7:57]{.aside}

και εκβαλοντες εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τα ιματια [αυτων]{.greek-added} παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} δεξαι το [πνευμα]{.greek-abbr} μου[7:59]{.aside}

θεις δε τα γονατα εκραξεν φωνη μεγαλη [κυριε]{.greek-abbr} μη [στησης]{.greek-omitted} [στησεις]{.greek-added} αυτοις την αμαρτια[ν]{.unclear} ταυτην και [τουτο]{.greek-omitted} [ταυτα]{.greek-added} ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

σαυλος δε ην συνευδοκων τη αναιρεσει αυτου εγενετο δε εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις παντες δε διεσπαρησαν κατα τας χωρας της ιουδαιας και [σαμαρειας]{.greek-omitted} [σαμαριας]{.greek-added} πλην των αποστολων[8:1]{.aside}

[συνεκομισαν]{.greek-omitted} [συνεκομησαν]{.greek-added} δε τον στεφανον ανδρες ε[υ]{.unclear}λαβεις και εποιησαντο κοπετον [μεγαν]{.greek-omitted} [μεγα]{.greek-added} επ αυτω[8:2]{.aside}

σαυλος δε [ελυμαινετο]{.greek-omitted} [ελοιμαινετο]{.greek-added} την εκκλησιαν κατα τους οικους εισπορευομενος συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπ[α]{.unclear}ρεντες διηλθον ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος [δε]{.unclear} κατελθων εις πολιν της [σαμαρειας]{.greek-omitted} [σαμαριας]{.greek-added} [εκηρυσσεν]{.greek-omitted} [εκηρυξεν]{.greek-added} αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον τε οι οχλοι τοις λεγομενοις υπο του φιλιππου ομοθυμαδον εν τω ακουειν αυτους και [β]{.unclear}[λ]{.greek-supplied}[ε]{.unclear}[πειν]{.greek-supplied} [τα]{.greek-supplied} [σημεια]{.greek-supplied} α εποιει[8:6]{.aside}

πολλων γαρ των εχοντων [πνευματα]{.greek-abbr} ακαθαρτα βοωντα φωνη μεγαλη [εξηρχετο]{.greek-omitted} [εξηρχοντο]{.greek-added} πολλοι δε παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

και εγενετο χαρα μεγαλη εν τη πολει εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι σιμων προυπηρχεν εν τη πολει μαγευων και [εξιστων]{.greek-omitted} [εξηστων]{.greek-added} το εθνος της σαμαρειας λεγων ειναι τινα εαυτον μεγαν[8:9]{.aside}

ω προσειχον [παντες]{.greek-added} απο μικρου εως μεγαλου λεγοντες ουτος εστιν η [δυναμις]{.greek-omitted} [δυναμεις]{.greek-added} του [θεου]{.greek-abbr} η μεγαλη[8:10]{.aside}

προσειχον δε αυτω δια το ικανω χρονω ταις [μαγειαις]{.greek-omitted} [μαγιαις]{.greek-added} εξεστακεναι αυτους[8:11]{.aside}

οτε δε επιστευσαν τω φιλιππω ευαγγελιζομενω τα περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος επιστευσεν και βαπτισθεις ην προσκαρτερων τω φιλιππω [θεωρων]{.greek-omitted} [θεορων]{.greek-added} τε [δυναμεις]{.greek-omitted} [δυναμης]{.greek-added} και σημεια γινομενα εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} απεστειλαν προς αυτους τον πετρον και ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως λαβωσιν [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

ουπω γαρ ην επ ουδενι αυτων επιπεπτωκος μονον δε βεβαπτισμενοι υπηρχον εις το ονομα του [χριστου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr}[8:16]{.aside}

τοτε επετιθουν τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιο[ν]{.unclear}[8:17]{.aside}

θεασαμενος δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω [εαν]{.greek-omitted} [αν]{.greek-added} επιθω τας χειρας λαμβανη [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε ειπεν προς αυτον το αργυριον σου συν [σοι]{.greek-omitted} [συ]{.greek-added} ειη εις [απωλειαν]{.greek-omitted} [απ[ο]{.unclear}λειαν]{.greek-added} οτι την [δωρεαν]{.greek-omitted} [δωραιαν]{.greek-added} του [θεου]{.greek-abbr} ενομισας δια χρηματων κτασθαι[8:20]{.aside}

ουκ εστιν σοι μερις ουδε κληρος εν τω λογω τουτω η γαρ καρδια σου ουκ εστιν ευθεια ενωπιον του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν [απο]{.corr} της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} ει α[ρα]{.greek-supplied} αφεθησεται σοι η επινοια της καρδιας σου[8:22]{.aside}

εις γαρ χολην πικρι[α]{.unclear}ς και συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

αποκρ[ιθ]{.unclear}εις δε ο σιμων ειπεν δεηθητε υμεις υπερ εμου προς τον [κυριον]{.greek-abbr} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι μεν ουν [διαμαρτυραμενοι]{.greek-omitted} [διαμαρτυρομενοι]{.greek-added} και λαλησαντες τον λο[γ]{.unclear}ον του [κυριου]{.greek-abbr} υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} πολλας τε κωμας των [σαμαρειτων]{.greek-omitted} [σαμαριτων]{.greek-added} ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} ελαλησεν προς φιλιππον λεγων αναστηθι και πορευου κατα μεσημβριαν επι την οδον την καταβαινουσαν απο [ιερουσαλημ]{.greek-abbr} εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ [αιθιοψ]{.greek-omitted} [αιθιωψ]{.greek-added} ευνουχος δυναστης κανδακης της βασιλισσης αιθιοπων ος ην επι πασης της γαζης αυτης ος [εληλυθει]{.greek-omitted} [εληλυθη]{.greek-added} [προσκυνησων]{.greek-omitted} [προσκυνισων]{.greek-added} εις [ιερουσαλημ]{.greek-abbr}[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου [και]{.greek-omitted} ανεγινωσκεν τον προφητην ησαιαν[8:28]{.aside}

ειπεν δε το [πνευμα]{.greek-abbr} τω φιλιππω [προσελθε]{.greek-omitted} [προσσελθε]{.greek-added} και κολληθητι τω αρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος τον προφητην ησαιαν και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε ειπεν πως γαρ αν δυναιμην εαν μη τις [οδηγηση]{.greek-omitted} [οδηγησει]{.greek-added} με παρεκαλεσεν τε τον φιλιππον αναβαντα [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} συν αυτω[8:31]{.aside}

η δε περιοχη της γραφης [ην]{.corr} [ανεγινωσκεν]{.corr} ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του [κειροντος]{.greek-omitted} [κειραντος]{.greek-added} αυτον αφωνος [ουτως]{.greek-omitted} [ουτος]{.greek-added} ουκ ανοιγει το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου ηρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω ειπεν δεομαι σου περι τινος ο προφητης λεγει τουτο περι εαυτου η περι ετερου τινος[8:34]{.aside}

ανοιξας δε ο φιλιππος το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο αυτω τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο κατα την οδον ηλθον επι τι υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

[ειπεν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added} [ει]{.greek-added} [πιστευεις]{.greek-added} [εξ]{.greek-added} [ολης]{.greek-added} [της]{.greek-added} [καρδιας]{.greek-added} [σου]{.greek-added} [εξεστιν]{.greek-added} [αποκριθεις]{.greek-added} [δε]{.greek-added} [ειπεν]{.greek-added} [πιστευω]{.greek-added} [τον]{.greek-added} [[υιον]{.greek-abbr}]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [[χριστον]{.greek-abbr}]{.greek-added}[8:37]{.aside}

και εκελευσεν στηναι το αρμα και κατεβησαν αμφοτεροι εις το υδωρ ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν εκ του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ηρπασεν τον φιλιππον και ουκ [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτον ουκετι ο ευνουχος [επορευετο]{.greek-omitted} [επορευετω]{.greek-added} γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις [καισαρειαν]{.greek-omitted} [καισαριαν]{.greek-added}[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων [απειλης]{.greek-omitted} [απηλεις]{.greek-added} και [φονου]{.greek-omitted} [φωνου]{.greek-added} εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις [δαμασκον]{.greek-omitted} [δαμασκων]{.greek-added} προς τας συναγωγας οπως εαν τινας ευρη της οδου οντας ανδρας τε και γυναικας δεδεμενους αγαγη εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε [τω]{.greek-omitted} [το]{.greek-added} πορευεσθαι [αυτον]{.greek-added} εγενετο αυτον [εγγιζειν]{.greek-omitted} [εγγηζειν]{.greek-added} τη δαμασκω και [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} περιηστραψεν αυτον φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γην ηκουσεν φωνην λεγουσαν αυτω σαουλ σαουλ τι με διωκεις[9:4]{.aside}

[[και]{.corr}]{.greek-added} ειπεν δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[9:5]{.aside}

αλλα αναστηθι και [εισελθε]{.greek-omitted} [εισελθαι]{.greek-added} εις την πολιν και λαληθησεται σοι τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι [συνοδευοντες]{.greek-omitted} [συνοοδευοντες]{.greek-added} αυτω [ειστηκεισαν]{.greek-omitted} [ιστηκησαν]{.greek-added} ενεοι ακουοντες μεν της φωνης μηδενα δε [θεωρουντες]{.greek-omitted} [θεορουντες]{.greek-added}[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων τε των οφθαλμων αυτου ουδενα εβλεπεν χειραγωγουντες δε αυτον εισηγαγον εις δαμασκον[9:8]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και ειπεν προς αυτον ο [κυριος]{.greek-abbr} εν οραματι ανανια ο δε ειπεν ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ προσευχεται[9:11]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [ε]{.unclear}ν οραματι ανδρα ονοματι ανανιαν εισελ[θ]{.unclear}[ο]{.greek-supplied}ντα και επιθεντα αυτω χειρα οπως αναβλεψη[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα εποιησεν τοις αγιοις [σου]{.greek-omitted} εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και ωδε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

ειπεν δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει αυτον υπερ του ονοματος μου παθειν[9:16]{.aside}

απηλθεν δε ανανιας και εισηλθεν εις την οικιαν και επιθεις επ αυτον τας χειρας ειπεν σαουλ αδελφε ο [κυριος]{.greek-abbr} απεσταλκεν με [[ιησους]{.greek-abbr}]{.greek-added} ο οφθεις σοι εν τη οδω η ηρχου οπως αναβλεψης και [πλησθης]{.greek-omitted} [πλησθεις]{.greek-added} [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

[και]{.greek-omitted} ευθεως [απεπεσον]{.greek-omitted} [απεπεσαν]{.greek-added} απο των οφθαλμων αυτου ωσει λεπιδες ανεβλεψεν τε και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε ο σαυλος μετα των εν δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις εκηρυσσεν τον [χριστον]{.greek-abbr} οτι ουτος εστιν ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγον ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο εληλυθεν ινα δεδεμενους αυτους αγαγη επι τους αρχιερεις[9:21]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και συνεχυνεν τους ιουδαιους τους κατοικουντας εν δαμασκω [συμβιβαζων]{.greek-omitted} [συμβηβαζων]{.greek-added} οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι [ικαναι]{.greek-omitted} [ηκαναι]{.greek-added} συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω [σαυλω]{.greek-omitted} [παυλω]{.greek-added} η επιβουλη αυτων παρετηρουν τε τας πυλας ημερας τε και νυκτος οπως αυτον ανελωσιν[9:24]{.aside}

λαβοντες δε αυτον οι μαθηται νυκτος [καθηκαν]{.greek-omitted} [καθεικαν]{.greek-added} δια του τειχους χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι εστιν μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον ηγαγεν προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν [τω]{.greek-omitted} [το]{.greek-added} ονοματι του [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος εις [ιερουσαλημ]{.greek-abbr} και παρρησιαζομενος εν [τω]{.greek-omitted} [το]{.greek-added} ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

[ελαλει]{.greek-omitted} [ελαλη]{.greek-added} τε και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

επιγνοντες δε οι αδελφοι κατηγαγον αυτον εις [καισαρειαν]{.greek-omitted} [σκαισαρειαν]{.greek-added} και εξαπεστειλαν αυτον εις ταρσον[9:30]{.aside}

αι μεν ουν εκκλησιαι καθ ολης της ιουδαιας και γαλιλαιας και σαμαρειας ειχον ειρηνην οικοδομουμεναι και πορευομεναι τω φοβω του [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} επληθυνοντο[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας [λυδδαν]{.greek-omitted} [λυδαν]{.greek-added}[9:32]{.aside}

ευρεν δε εκει [ανθρωπον]{.greek-abbr} τινα αινεαν ονοματι εξ ετων οκτω κατακειμενον επι [κραββατω]{.greek-omitted} [κραβαττω]{.greek-added} ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ο]{.greek-added} [[κυριος]{.greek-abbr}]{.greek-added} [ιησους]{.greek-abbr} [ο]{.greek-omitted} [χριστος]{.greek-omitted} αναστηθι και στρωσον σεαυτω και ευθεως ανεστη[9:34]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον παντες οι κατοικουντες [λυδδαν]{.greek-omitted} [λυδαν]{.greek-added} και τον [ασσαρωνα]{.greek-omitted} [σαρωνα]{.greek-added} οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι ταβηθα η [διερμηνευομενη]{.greek-omitted} [διερμεινευομενη]{.greek-added} λεγεται δορκας αυτη ην [πληρης]{.greek-omitted} [πληρις]{.greek-added} αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν εν υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν [δυο]{.greek-added} [ανδρας]{.greek-added} προς αυτον παρακαλουντες μη οκνησαι [διελθειν]{.greek-omitted} [ελθειν]{.greek-added} εως αυτων[9:38]{.aside}

αναστας δε πετρος συνηλθεν αυτοις ον παραγενομενον ανηγαγον εις το υπερωον και παρεστησαν αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι [χιτωνας]{.greek-omitted} [χειτωνας]{.greek-added} και ιματια οσα εποιει μετ αυτων ουσα η δορκας[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος [[και]{.unclear}]{.greek-added} θεις τα [γονατα]{.greek-omitted} [γωνατα]{.greek-added} προσηυξατο και επιστρεψας προς το σωμα ειπεν [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} αναστηθι η δε ηνοιξεν τους οφθαλμους αυτης και ιδουσα τον πετρον [ανεκαθισεν]{.greek-omitted} [ανεκαθησεν]{.greek-added}[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην φωνησας δε τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωστον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας [ικανας]{.greek-omitted} [ηκανας]{.greek-added} μειναι αυτον εν ιοππη παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις ην εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ [σπειρης]{.greek-omitted} [σπηρις]{.greek-added} της καλουμενης ιταλικης[10:1]{.aside}

[ευσεβης]{.greek-omitted} [ευσεβεις]{.greek-added} και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

[ειδεν]{.greek-omitted} [ιδεν]{.greek-added} εν οραματι φανερως ωσει ωραν ενατην της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε [ατενισας]{.greek-omitted} [ατενησας]{.greek-added} αυτω και εμφοβος γενομενος ειπεν τι εστιν [κυριε]{.greek-abbr} ειπεν δε αυτω αι προσευχαι σου και αι ελεημοσυναι σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν οικια παρα θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην ευσεβη των προσκαρτερουντων αυτω[10:7]{.aside}

και εξηγησαμενος αυτοις απαντα απεστειλεν αυτους εις την ιοππην[10:8]{.aside}

τη δε επαυριον [οδοιπορουντων]{.greek-omitted} [οδυπορουντων]{.greek-added} εκεινων και τη πολει [εγγιζοντων]{.greek-omitted} [εγγηζοντων]{.greek-added} ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν εκτην[10:9]{.aside}

εγενετο δε [προσπεινος]{.greek-omitted} [προσπινος]{.greek-added} και ηθελεν γευσασθαι παρασκευαζοντων δε εκεινων [επεπεσεν]{.greek-omitted} [επεσεν]{.greek-added} επ αυτον [εκστασις]{.greek-omitted} [εκστασεις]{.greek-added}[10:10]{.aside}

και [θεωρει]{.greek-omitted} [θεορει]{.greek-added} τον [ουρανον]{.greek-abbr} ανεωγμενον και [καταβαινον]{.greek-omitted} [καταβενοντα]{.greek-added} επ αυτον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις δεδεμενον και καθιεμενον επι της γης[10:11]{.aside}

εν ω [υπηρχεν]{.greek-omitted} [υπειρχεν]{.greek-added} παντα τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστας πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος ειπεν μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον η ακαθαρτον[10:14]{.aside}

και φωνη παλιν εκ δευτερου προς αυτον α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθερισεν]{.greek-added} συ μη [κοινου]{.greek-omitted} [κυνου]{.greek-added}[10:15]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν ανεληφθη το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν [εαυτω]{.greek-omitted} [αυτω]{.greek-added} διηπορει ο πετρος τι αν ειη το οραμα ο [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} και ιδου οι ανδρες οι απεσταλμενοι απο του κορνηλιου διερωτησαντες την οικιαν σιμωνος [επεστησαν]{.greek-omitted} [επεστεισαν]{.greek-added} επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει σιμων ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες ζητουσιν σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους[10:20]{.aside}

καταβας δε πετρος προς τους ανδρας ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος ουν αυτους [εξενισεν]{.greek-omitted} [εξενησεν]{.greek-added} τη δε επαυριον ο πετρος εξηλθεν συν αυτοις και τινες των αδελφων των απο ιοππης [συνηλθον]{.greek-omitted} [συνηλθων]{.greek-added} αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις την καισαρειαν ο δε κορνηλιος ην [προσδοκων]{.greek-omitted} [προσδο]{.greek-added} [κων]{.greek-added} αυτους [συγκαλεσαμενος]{.greek-omitted} [συνκαλεσαμενος]{.greek-added} τους συγγενεις αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος [αυτον]{.greek-omitted} ηγειρεν λεγων αναστηθι καγω αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω εισηλθεν και ευρισκει συνεληλυθοτας πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως [αθεμιτον]{.greek-omitted} [αθεμητον]{.greek-added} εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και [αναντιρρητως]{.greek-omitted} [αναντηρρητως]{.greek-added} ηλθον μεταπεμφθεις [πυνθανομαι]{.greek-omitted} [ποινθανομαι]{.greek-added} ουν τινι λογω μετεπεμψασθε με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και φησιν κορνηλιε εισηκουσθη σου η προσευχη και αι ελεημοσυναι σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και μετακαλεσαι σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος βυρσεως παρα θαλασσαν ος παραγενομενος λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα ειπεν επ αληθειας [καταλαμβανομαι]{.greek-omitted} [καταλαμβανωμαι]{.greek-added} οτι ουκ εστιν προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι [εθνει]{.greek-omitted} [εθνη]{.greek-added} ο φοβουμενος αυτον και εργαζομενος δικαι[ο]{.unclear}συνην δεκτος αυτω εστιν[10:35]{.aside}

τον λογον ον απεστειλεν τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος εστιν παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το [βαπτισμα]{.greek-omitted} [βαπτησμα]{.greek-added} ο εκηρυξεν ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ως [εχρισεν]{.greek-omitted} [εχρησεν]{.greek-added} αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-abbr} ον και ανειλον κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} ηγειρεν τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα μαρτυσιν τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες συνεφαγομεν και συνεπιομεν αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι αυτος εστιν ο [ωρισμενος]{.greek-omitted} [ορισμενος]{.greek-added} υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

[η]{.unclear}κουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη ο πετρος[10:46]{.aside}

μητι [το]{.greek-omitted} [τω]{.greek-added} υδωρ [κωλυσαι]{.greek-omitted} [κολυσαι]{.greek-added} [δυναται]{.greek-omitted} [δυνατε]{.greek-added} τις του μη βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

προσεταξεν τε αυτους βαπτισθηναι εν [τω]{.greek-omitted} [το]{.greek-added} ονοματι του [κυριου]{.greek-abbr} τοτε ηρωτησαν αυτον [επιμειναι]{.greek-omitted} [επιμηναι]{.greek-added} ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε ο πετρος [εξετιθετο]{.greek-omitted} [εξετηθετο]{.greek-added} αυτοις καθεξης λεγων[11:4]{.aside}

εγω [ημην]{.greek-omitted} [ημιν]{.greek-added} εν πολει ιοππη προσευχομενος και [ειδον]{.greek-omitted} [ιδων]{.greek-added} εν εκστασει οραμα καταβαινον σκευος τι ως [οθονην]{.greek-omitted} [οθωνην]{.greek-added} μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην [ατενισας]{.greek-omitted} [ατενησας]{.greek-added} κατενοουν και [ειδον]{.greek-omitted} [ιδων]{.greek-added} τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθερησεν]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν ανεσπασθη απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες [επεστησαν]{.greek-omitted} [επεστεισαν]{.greek-added} επι την οικιαν εν η [ημην]{.greek-omitted} [ημιν]{.greek-added} απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

ειπεν δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν διακρινομενον ηλθον δε συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

απηγγειλεν [τε]{.greek-omitted} [δε]{.greek-added} ημιν πως [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις [σωθηση]{.greek-omitted} [σωθησει]{.greek-added} συ και πας ο οικος σου[11:14]{.aside}

εν δε τω αρξασθαι με λαλειν επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [του]{.greek-added} [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} [ως]{.greek-omitted} [ωσπερ]{.greek-added} και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω δε τις [ημην]{.greek-omitted} [ημιν]{.greek-added} δυνατος [κωλυσαι]{.greek-omitted} [κολυσαι]{.greek-added} τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες αρα γε και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες απο της [θλιψεως]{.greek-omitted} [θληψεως]{.greek-added} της γενομενης επι στεφανω [διηλθον]{.greek-omitted} [διηλθων]{.greek-added} εως φοινικης και κυπρου και αντιοχειας μηδενι λαλουντες τον λογον ει μη [μονον]{.greek-omitted} [μονοις]{.greek-added} ιουδαιοις[11:19]{.aside}

[ησαν]{.greek-omitted} [εισαν]{.greek-added} δε τινες εξ αυτων ανδρες κυπριοι και [κυρηναιοι]{.greek-omitted} [κυριναιοι]{.greek-added} οιτινες εισελθοντες εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της εν ιεροσολυμοις περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει παντας τη προθεσει της καρδιας [προσμενειν]{.greek-omitted} [προσσμενειν]{.greek-added} τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και [πληρης]{.greek-omitted} [πληρις]{.greek-added} [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

εξηλθεν δε εις [ταρσον]{.greek-omitted} [ταρ]{.greek-added} [σον]{.greek-added} ο βαρναβας [αναζητησαι]{.greek-omitted} [αναζητεισαι]{.greek-added} σαυλον[11:25]{.aside}

και [ευρων]{.greek-omitted} [ευρον]{.greek-added} [αυτον]{.greek-added} ηγαγεν αυτον εις αντιοχειαν εγενετο δε αυτους ενιαυτον ολον συναχθηναι τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε [ο]{.greek-added} εις εξ αυτων ονοματι αγαβος εσημανεν δια του [πνευματος]{.greek-abbr} λιμον μεγαν μελλειν εσεσθαι εφ ολην την οικουμενην οστις και εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως [ευπορειτο]{.greek-omitted} [ηυπορειτο]{.greek-added} τις ωρισαν εκαστος αυτων εις [διακονιαν]{.greek-omitted} [διακονειαν]{.greek-added} πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

ο και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και [σαυλου]{.greek-omitted} [παυλου]{.greek-added}[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της εκκλησιας[12:1]{.aside}

ανειλεν δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

και ιδων οτι [αρεστον]{.greek-omitted} [αρεστος]{.greek-added} εστιν τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε [αι]{.greek-omitted} ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους τεσσαρσιν τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} αυτον προαγειν ο ηρωδης τη [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} εκεινη ην ο πετρος κοιμωμεν[ος]{.unclear} μεταξυ δυο στρατιωτων δεδεμενος αλυσεσιν δυσιν φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και εξεπεσον αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

ειπεν [τε]{.greek-omitted} [δε]{.greek-added} ο αγγελος προς αυτον περιζωσαι και υποδησαι τα σανδαλια σου [εποιησεν]{.greek-omitted} [εποιεισεν]{.greek-added} δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και [ακολουθει]{.greek-omitted} [ακολουθη]{.greek-added} μοι[12:8]{.aside}

και εξελθων [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και ουκ ηδει οτι [αληθες]{.greek-omitted} [αληθεις]{.greek-added} εστιν το γινομενον δια του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν εις την [πολιν]{.greek-omitted} [πολην]{.greek-added} ητις αυτοματη ηνοιχθη αυτοις και εξελθοντες προηλθον ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος γενομενος εν εαυτω ειπεν νυν οιδα αληθως οτι εξαπεστειλεν [κυριος]{.greek-abbr} τον αγγελον αυτου και [εξειλετο]{.greek-omitted} [εξειλατο]{.greek-added} με εκ χειρος ηρωδου και πασης της προσδοκιας του λαου των ιουδαιων[12:11]{.aside}

[συνιδων]{.greek-omitted} [συνειδων]{.greek-added} τε ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} ιωαννου του επικαλουμενου μαρκου ου ησαν ικανοι συνηθροισμενοι και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του πετρου την θυραν του πυλωνος προσηλθεν παιδισκη υπακουσαι ονοματι [ροδη]{.greek-omitted} [ρωδη]{.greek-added}[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ ηνοιξεν τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον [μαινη]{.greek-omitted} [μαινει]{.greek-added} η δε [διισχυριζετο]{.greek-omitted} [διησχυριζετο]{.greek-added} [ουτως]{.greek-omitted} [ου]{.greek-added} [τος]{.greek-added} εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος επεμενεν κρουων ανοιξαντες δε [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον και εξεστησαν[12:16]{.aside}

[κατασεισας]{.greek-omitted} [κατασησας]{.greek-added} δε [αυτοις]{.greek-omitted} τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξηγαγεν εκ της φυλακης ειπεν δε απαγγειλατε ιακωβω και τοις αδελφοις ταυτα [και]{.greek-omitted} [δε]{.greek-added} εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε [επιζητησας]{.greek-omitted} [επιζητεισας]{.greek-added} αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις την καισαρειαν [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added}[12:19]{.aside}

ην δε ο ηρωδης [θυμομαχων]{.greek-omitted} [θυμομαχον]{.greek-added} τυριοις και σιδωνιοις ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι αυτων την χωραν απο της βασιλικης[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα βασιλικην και [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εδημηγορει προς αυτους[12:21]{.aside}

ο δε δημος [επεφωνει]{.greek-omitted} [επεφωνη]{.greek-added} φωνη [θεου]{.greek-abbr} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε επαταξεν αυτον αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ εδωκεν δοξαν τω [θεω]{.greek-abbr} και γενομενος [σκωληκοβρωτος]{.greek-omitted} [σκωλικοβρωτος]{.greek-added} εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} ηυξανεν και επληθυνετ[ο]{.unclear}[12:24]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν εις ιερουσαλη[μ]{.unclear} πληρωσαντες την διακονιαν συμπαραλαβοντες και ιωαννην τον επικληθεντα μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε τινες εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος ο [κυρηναιος]{.greek-omitted} [κυριναιος]{.greek-added} μαναην τε ηρωδου του τετραρχου συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων ειπεν το [πνευμα]{.greek-abbr} το αγιον [αφορισατε]{.greek-omitted} [αφορησατε]{.greek-added} δη μοι τον βαρναβαν και τον σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες τας χειρας αυτοις απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεν[τες]{.unclear} υπο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις την [σελευκειαν]{.greek-omitted} [σελευκιαν]{.greek-added} εκειθεν δε απεπλευσαν εις την κυπρον[13:4]{.aside}

και γενομενοι εν [σαλαμινι]{.greek-omitted} [σαλαμηνη]{.greek-added} κατηγγελλον τον λογον του [θεου]{.greek-abbr} εν ταις συναγωγαις των ιουδαιων [ειχον]{.greek-omitted} [ηχον]{.greek-added} δε και ιωαννην [υπηρετην]{.greek-omitted} [υπειρετην]{.greek-added}[13:5]{.aside}

διελθοντες δε [ολην]{.greek-added} την [νησον]{.greek-omitted} [νησσον]{.greek-added} [αχρι]{.greek-omitted} [αχρη]{.greek-added} [παφου]{.greek-omitted} [παμφου]{.greek-added} ευρον [εκει]{.greek-added} [ανδρα]{.greek-added} τινα μαγον ψευδοπροφητην ιουδαιον ω ονομα βαριησους[13:6]{.aside}

ος ην συν τω ανθυ[πα]{.unclear}τω σεργιω παυλω ανδρι συνετω [ου]{.unclear}[τος]{.greek-supplied} προσκαλεσαμενος βαρναβαν και σαυλον [επεζητησεν]{.greek-omitted} [επεζητεισεν]{.greek-added} ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μαγος ουτως γαρ [μεθερμηνευεται]{.greek-omitted} [μεθερμεινευεται]{.greek-added} το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου και [ατενισας]{.greek-omitted} [ατενησας]{.greek-added} εις αυτον[13:9]{.aside}

ειπεν ω [πληρης]{.greek-omitted} [πληρις]{.greek-added} παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου [παυση]{.greek-omitted} [παυει]{.greek-added} διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον αχρι καιρου παραχρημα δε επεπεσεν επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το [γεγονω[ς]{.unclear}]{.greek-added} [γεγονος]{.corr} [ε]{.greek-supplied}[π]{.unclear}ιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε αποχωρησας απ αυτων υπεστρεψεν εις [ιεροσολυμα]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added}[13:13]{.aside}

[αυτοι]{.greek-omitted} [ουτοι]{.greek-added} δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added}[13:14]{.aside}

[και]{.greek-added} μετα [δε]{.greek-omitted} την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει [τις]{.greek-added} εστιν [λογος]{.greek-omitted} εν υμιν [λογος]{.greek-added} παρακλησεως προς τον λαον [λεγετε]{.greek-omitted} [λεγεται]{.greek-added}[13:15]{.aside}

αναστας δε παυλος και [κατασεισας]{.greek-omitted} [κατασησας]{.greek-added} τη χειρι [σηγαν]{.greek-added} ειπεν ανδρες [ισραηλιται]{.greek-omitted} [ισραιλιται]{.greek-added} και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου [[ισραηλ]{.greek-abbr}]{.greek-added} εξελεξατο τους πατερας ημων και τον λαον [και]{.greek-added} υψωσεν εν τη παροικια εν γη αιγυπτω και μετα [βραχιονος]{.greek-omitted} [βραχιωνος]{.greek-added} υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον ετροποφορησεν αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη επτα εν γη χανααν κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

και μετα ταυτα ως ετεσιν τετρακοσιοις και πεντηκοντα [και]{.greek-added} [μετα]{.greek-added} [ταυτα]{.greek-added} εδωκεν [αυτοις]{.greek-added} κριτας εως σαμουηλ του προφητου[13:20]{.aside}

[κα]{.greek-supplied}κειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ υιον [κις]{.greek-omitted} [κεις]{.greek-added} ανδρα εκ φυλης βενιαμιν ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και ειπεν μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν [ηγαγεν]{.greek-omitted} [ηγειρεν]{.greek-added} τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-omitted} [[σωτηρα]{.greek-abbr}]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added}[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας [παντι]{.greek-added} τω [λαω]{.greek-added} [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου ο ιωαννης τον δρομον ελεγεν τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων [αυτου]{.greek-added} λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος [ουτος]{.greek-added} της σωτηριας [ταυτης]{.greek-omitted} [απεσταλη]{.greek-omitted} [εξαπεσταλη]{.greek-added}[13:26]{.aside}

οι γαρ κατ[ο]{.unclear}ικουντες εν [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον αγνοησαντες και τας φωνας των προφητων τας κατα παν σαββατον αναγινωσκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο [πιλατον]{.greek-omitted} [πηλατον]{.greek-added} αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις [μνημειον]{.greek-omitted} [μνημηον]{.greek-added}[13:29]{.aside}

ο δε [θεος]{.greek-abbr} [η]{.unclear}γειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [νυν]{.greek-added} εισιν μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [εκπεπληρωκεν]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω [γεγραπται]{.greek-added} τω δευτερω [γεγραπται]{.greek-omitted} υιος μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} εκ νεκρων μηκετι μελλοντα υποστρεφειν εις [διαφθοραν]{.greek-omitted} [φθοραν]{.greek-added} ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα [υπηρετησας]{.greek-omitted} [υπειρετησας]{.greek-added} τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και ειδεν διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ ειδεν διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν ανδρες αδελφοι οτι [δια]{.greek-omitted} [δι]{.greek-added} [τουτου]{.greek-omitted} [αυτου]{.greek-added} υμιν αφεσις αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωυσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι [καταφρονηται]{.greek-omitted} [καταφρονιται]{.greek-added} [και]{.greek-added} [επιβλεψαται]{.greek-added} και θαυμασατε και αφανισθητε οτι εργον [εργαζομαι]{.greek-added} εγω [εργαζομαι]{.greek-omitted} εν ταις ημεραις υμων [εργον]{.greek-added} ο ου μη πιστευσητε εαν τις εκδιηγηται υμιν[13:41]{.aside}

[εξιοντων]{.greek-omitted} [εξιωντων]{.greek-added} [τε]{.greek-added} [δε]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [ιουδαιων]{.greek-omitted} παρεκαλουν [τα]{.greek-omitted} [εθνη]{.greek-omitted} εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

[λυθεισης]{.greek-omitted} [λυθησης]{.greek-added} δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και τω βαρναβα οιτινες προσλαλουντες [αυτοις]{.greek-added} επειθον αυτους [επιμενειν]{.greek-omitted} [προσμενειν]{.greek-added} τη [χαριτι]{.greek-omitted} [χαριτ[η]{.unclear}]{.greek-added} του [θεου]{.greek-abbr}[13:43]{.aside}

τω [τε]{.greek-omitted} [δε]{.greek-added} ερχομενω σαββατω σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλου λεγομενοις [αντιλεγοντες]{.greek-omitted} [και]{.greek-omitted} βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος και [ο]{.greek-omitted} βαρναβας ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} επειδη δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

ουτως γαρ εντεταλται ημιν ο [κυριος]{.greek-abbr} [ιδου]{.greek-added} [τεθεικα]{.greek-omitted} [τεθηκα]{.greek-added} σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον τον λογον του [κυριου]{.greek-abbr} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-abbr} [δι]{.greek-omitted} [καθ]{.greek-added} ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας [και]{.greek-omitted} τας ευσχημονας και τους πρωτους της πολεως και [επηγειραν]{.greek-omitted} [επειραν]{.greek-added} διωγμον επι τον παυλον και [τον]{.greek-omitted} βαρναβαν και εξεβαλον αυτους [εξω]{.greek-added} απο των οριων αυτων[13:50]{.aside}

οι δε [εκτιναξαμενοι]{.greek-omitted} [εκτηναξαμενοι]{.greek-added} τον κονιορτον των ποδων [αυτων]{.greek-omitted} επ αυτους ηλθον εις [ικονιον]{.greek-omitted} [εικονιον]{.greek-added}[13:51]{.aside}

οι δε μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων τε και ελληνων πολυ πληθος[14:1]{.aside}

οι δε [απειθουντες]{.greek-omitted} [απηθησαντες]{.greek-added} ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου [και]{.greek-added} [διδοντι]{.greek-omitted} [διδοντος]{.greek-added} σημεια και τερατα γινεσθαι δια των χειρων [αυτων]{.greek-omitted} [των]{.greek-added} [αποστολων]{.greek-added}[14:3]{.aside}

[εσχισθη]{.greek-omitted} [εσχησθη]{.greek-added} δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο [ο]{.unclear}ρμη των εθνων τε και ιουδαιων συ[ν]{.unclear} τοις αρχουσιν αυτων υβρισαι και λιθο[β]{.unclear}ολησαι αυτους[14:5]{.aside}

συνιδοντε[ς]{.greek-supplied} [κατεφυγον]{.greek-omitted} [[κ]{.greek-supplied}[α]{.unclear}τεφυγων]{.greek-added} εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει [ευαγγελιζομενοι]{.greek-added} ησαν [ευαγγελιζομενοι]{.greek-omitted}[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κο[ι]{.greek-supplied}λιας [μητρος]{.greek-abbr} αυτου υπαρχων ος ουδεποτε [περιπεπατηκει]{.greek-omitted} [περιεπατησεν]{.greek-added}[14:8]{.aside}

ουτος ηκουσεν του παυλου λαλουντος ος ατενισας αυτω και ιδων οτι [πιστιν]{.greek-omitted} εχει [πιστην]{.greek-added} του σωθηναι[14:9]{.aside}

ειπεν μεγαλη τη φωνη [σοι]{.greek-added} [λεγω]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [ονοματι]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} αναστηθι επι τους ποδας σου [ορθως]{.greek-omitted} [ορθος]{.greek-added} και [ηλλετο]{.greek-omitted} [ηλλατο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν [ο]{.greek-omitted} παυλος επηραν την φωνην αυτων λυκαονιστι λεγοντες οι θεοι [ομοιωθεντες]{.greek-omitted} [ομοιοθεντες]{.greek-added} ανθρωποις κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν [δια]{.greek-omitted} [διαν]{.greek-added} τον δε παυλον ερμην επειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο δε ιερευς του διος του οντος προ της πολεως [αυτων]{.greek-omitted} ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις [ηθελεν]{.greek-omitted} [ηλθεν]{.greek-added} θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες [αυτων]{.greek-added} τα ιματια [αυτων]{.greek-omitted} [εισεπηδησαν]{.greek-omitted} [εξεπιδησαν]{.greek-added} εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} και ημεις ομοιοπαθεις [υμιν]{.greek-added} εσμεν [υμιν]{.greek-omitted} [ανθρωποι]{.greek-omitted} [ανθροποι]{.greek-added} ευαγγελιζομενοι υμας απο τουτων των ματαιων επιστρεφειν επι [τον]{.greek-omitted} [θεον]{.greek-abbr} [τον]{.greek-omitted} ζωντα ος εποιησεν τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις παρωχημεναις γενεαις ειασεν παντα τα εθνη πορευεσθαι [εν]{.greek-added} ταις οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρον εαυτον αφηκεν αγαθοποιων [ουρανοθεν]{.greek-abbr} υμιν [υετους]{.greek-omitted} διδους [υιετους]{.greek-added} και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας [ημων]{.greek-omitted} [υμων]{.greek-added}[14:17]{.aside}

και ταυτα λεγοντες [μολις]{.greek-omitted} [μολης]{.greek-added} κατεπαυσαν τους οχλους του μη θυειν αυτοις [αλλα]{.greek-added} [πορευεσθαι]{.greek-added} [εκαστον]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ιδια]{.greek-added}[14:18]{.aside}

[επηλθον]{.greek-omitted} [διατριβοντων]{.greek-added} δε [αυτων]{.greek-added} [και]{.greek-added} [διδασκοντων]{.greek-added} [απηλθον]{.greek-added} [οι]{.greek-added} απο αντιοχειας και ικονιου ιουδαιοι και [πεισαντες]{.greek-omitted} [διαλεγομενων]{.greek-added} [αυτων]{.greek-added} [παρρησια]{.greek-added} [ανεπεισαν]{.greek-added} τους οχλους [αποστηναι]{.greek-added} [απ]{.greek-added} [αυτων]{.greek-added} [λεγοντες]{.greek-added} [οτι]{.greek-added} [ουδεν]{.greek-added} [αληθες]{.greek-added} [λεγουσιν]{.greek-added} [αλλα]{.greek-added} [παντα]{.greek-added} [ψευδονται]{.greek-added} και λιθασαντες τον παυλον εσυρον εξω της πολεως [νομισαντες]{.greek-omitted} [νομηζοντες]{.greek-added} αυτον τεθναναι[14:19]{.aside}

κυκλωσαντων [δε]{.greek-omitted} [τε]{.greek-added} αυτον των μαθητων αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν συν τω βαρναβα εις δερβην[14:20]{.aside}

[ευαγγελισαμενοι]{.greek-omitted} [ευαγγελιζομενοι]{.greek-added} τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν και [εις]{.greek-added} ικονιον και [εις]{.greek-added} αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων [και]{.greek-added} παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων [θληψεων]{.greek-added} [θλιψεων]{.corr} δει ημας εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις [πρεσβυτερους]{.greek-omitted} κατ εκκλησιαν [πρεσβυτερους]{.greek-added} [και]{.greek-added} προσευξαμενοι μετα [νηστειων]{.greek-omitted} [νηστιων]{.greek-added} παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον [πεπιστευκεισαν]{.greek-omitted} [πεπιστευκησαν]{.greek-added}[14:23]{.aside}

και διελθοντες την [πισιδιαν]{.greek-omitted} [πησηδιαν]{.greek-added} ηλθον εις [την]{.greek-added} παμφυλιαν[14:24]{.aside}

και λαλησαντες [εν]{.greek-omitted} [εις]{.greek-added} [περγη]{.greek-omitted} [περγην]{.greek-added} τον λογον [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} κατεβησαν εις [ατταλειαν]{.greek-omitted} [ατταλιαν]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις [αντιοχειαν]{.greek-omitted} [αντιοχιαν]{.greek-added} οθεν ησαν παραδεδομενοι τη χαριτι του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν [ανηγγειλαν]{.greek-omitted} [[α]{.greek-supplied}[π]{.unclear}ηγγειλαν]{.greek-added} οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτω[ν]{.greek-supplied} [και]{.greek-supplied} [ο]{.greek-supplied}τι ηνοιξεν τοις εθνεσιν θυραν [π]{.unclear}ιστ[εω]{.greek-supplied}ς[14:27]{.aside}

διετριβον δε εκει χρονον ουκ ολιγον [συν]{.greek-supplied} τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη [περιτεμνησθε]{.greek-omitted} [περιτμηθητε]{.greek-added} τω εθει μωυσεως ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης ουν στασεως και [ζητησεως]{.greek-omitted} [ζητεισεως]{.greek-added} ουκ ολιγης τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν [παυλον]{.greek-supplied} [και]{.greek-supplied} [βαρναβαν]{.greek-supplied} και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του [ζητηματος]{.greek-omitted} [ζητειματος]{.greek-added} τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την [τε]{.greek-added} φοινικην και σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις αδελφοις[15:3]{.aside}

παραγενομενοι δε εις ιερουσαλημ απεδεχθησαν υπο της εκκλησιας και των αποστολων και των πρεσβυτερων [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} τε οσα ο [θεος]{.greek-abbr} εποιησεν μετ αυτων[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων [πεπιστευκοτες]{.greek-omitted} [πεπιστευκοτων]{.greek-added} λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον μωυσεως[15:5]{.aside}

συνηχθησαν δε οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε [συζητησεως]{.greek-omitted} [ζητεισεως]{.greek-added} γενομενης αναστας πετρος ειπεν προς αυτους ανδρες αδελφοι υμεις [επιστασθε]{.greek-omitted} [επιστασθαι]{.greek-added} οτι αφ ημερων αρχαιων [εν]{.greek-added} [υμιν]{.greek-added} [εξελεξατο]{.greek-added} ο [θεος]{.greek-abbr} [εν]{.greek-omitted} [ημιν]{.greek-omitted} [εξελεξατο]{.greek-omitted} δια του στοματος μου ακουσαι τα εθνη τον λογον του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [δε]{.greek-added} [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και ουδεν διεκρινεν μεταξυ ημων τε και αυτων τη πιστει [καθαρισας]{.greek-omitted} [καθαρησας]{.greek-added} τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} τον [θεον]{.greek-abbr} [επιθειναι]{.greek-omitted} [επιθηναι]{.greek-added} ζυγον επι τον [τραχηλον]{.greek-omitted} [τραχειλον]{.greek-added} των μαθητων ον ουτε [ημεις]{.greek-added} [ουτε]{.greek-added} οι [πατερες]{.greek-abbr} ημων [ουτε]{.greek-omitted} [ημεις]{.greek-omitted} ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

[εσιγησεν]{.greek-omitted} [εσηγησεν]{.greek-added} δε παν το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα [εποιησεν]{.greek-omitted} [εποιεισεν]{.greek-added} ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις εθν[ε]{.greek-supplied}σιν δι αυτων[15:12]{.aside}

μετα δε το [σιγησαι]{.greek-omitted} [σηγησαι]{.greek-added} αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον [επι]{.greek-omitted} τω ονοματι αυτου[15:14]{.aside}

και τουτω συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και [ανορθωσω]{.greek-omitted} [ανωρθωσω]{.greek-added} αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων ταυτα παντα[15:17]{.aside}

γνωστα απ αιωνος εστιν τω [θεω]{.greek-abbr} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη [παρε]{.greek-added} [παρενοχλειν]{.greek-omitted} [νοχλειν]{.greek-added} τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

αλλα επιστειλαι αυτοις του απεχεσθαι απο των αλισγηματων των [ειδωλων]{.greek-omitted} [ειδολων]{.greek-added} και της [πορνειας]{.greek-omitted} [πορνηας]{.greek-added} και [του]{.greek-omitted} πνικτου και του αιματος[15:20]{.aside}

μωυσης γαρ εκ γενεων [αρχαιων]{.greek-omitted} [αρχεων]{.greek-added} κατα πολιν τους κηρυσσοντας αυτον εχει εν ταις συναγωγαις κατα παν σαββατον [αναγινωσκομενος]{.greek-omitted} [αναγινοσκομενος]{.greek-added}[15:21]{.aside}

τοτε εδοξεν τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν [τω]{.greek-added} παυλω και βαρναβα ιουδαν τον [επικαλουμενον]{.greek-omitted} [καλουμενον]{.greek-added} βαρσαββαν και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων εξελθοντες εταραξαν υμας λογοις ανασκευαζοντες τας ψυχας [υμων]{.greek-omitted} [[η]{.unclear}μων]{.greek-added} λεγοντες περιτεμνεσθαι και τηρειν τον νομον οις ου διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον [επι]{.greek-added} [το]{.greek-added} [αυτο]{.greek-added} εκλεξαμενους ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα και [παυλω]{.greek-omitted} [παυλου]{.greek-added}[15:25]{.aside}

[ανθρωποις]{.greek-abbr} [παραδεδωκοσιν]{.greek-omitted} [παραδεδωκωσι]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

εδοξεν γαρ τω αγιω [πνευματι]{.greek-abbr} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην [τουτων]{.greek-added} των [επαναγκες]{.greek-omitted} [επαναγκαις]{.greek-added} [τουτων]{.greek-omitted}[15:28]{.aside}

απεχεσθαι [ειδωλοθυτων]{.greek-omitted} [ειδωλοθυτου]{.greek-added} και αιματος και πνικτου και πορνειας εξ ων διατηρουντες εαυτους ευ πραξετε ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες [ηλθον]{.greek-omitted} [κατηλθον]{.greek-added} εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

[αναγνοντες]{.greek-omitted} [αναγνωντες]{.greek-added} δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον [ικανον]{.greek-added} απελυθησαν μετ ειρηνης απο των αδελφων προς τους [αποστολους]{.greek-omitted} [αποστειλαντας]{.greek-added} [αυτους]{.greek-added}[15:33]{.aside}

[εδοξεν]{.greek-added} [τε]{.greek-added} [τον]{.greek-added} [σιλαν]{.greek-added} [παραμειναι]{.greek-added} [αυτου]{.greek-added}[15:34]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας ειπεν παυλος προς βαρναβαν επιστρεψαντες δη επισκεψωμεθα τους αδελφους ημων κατα [πολιν]{.greek-added} πασαν [πολιν]{.greek-omitted} εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως εχουσιν[15:36]{.aside}

βαρναβας δε [εβουλευσατο]{.greek-omitted} [εβουλετο]{.greek-added} [συμπαραλαβειν]{.greek-omitted} [συνπαραλαμβανειν]{.greek-added} [τον]{.greek-omitted} [και]{.greek-added} ιωαννην τον [καλουμενον]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη [συμπαραλαβειν]{.greek-omitted} [συνπαραλαμβανειν]{.greek-added} τουτον[15:38]{.aside}

εγενετο [ουν]{.greek-omitted} [δε]{.greek-added} παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων τον τε βαρναβαν παρα[λα]{.greek-supplied}βοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν εξηλθεν παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και [την]{.greek-added} κιλικιαν επιστηριζων τας εκκλησια[ς]{.unclear}[15:41]{.aside}

### Chapter 16

κατηντησεν δε εις δερβην και [εις]{.greek-added} λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος υιος γυναικος [τινος]{.greek-omitted} [χ[η]{.greek-supplied}ρας]{.greek-added} ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τοποις εκεινοις ηδεισαν γαρ [απαντες]{.greek-omitted} [παντες]{.greek-added} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} οτι ελλην [ο]{.greek-added} [[πατηρ]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις [πασας]{.greek-added} [παρεδιδουν]{.greek-omitted} [παρεδιδωσαν]{.greek-added} αυτοις φυλασσειν τα δογματα τα κεκριμενα υπο των αποστολων και των πρεσβυτερων των εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και επερισσευον τω αριθμω καθ ημεραν[16:5]{.aside}

[διελθοντες]{.greek-omitted} [διηλθον]{.greek-added} δε την φρυγιαν και την γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες [δε]{.greek-added} κατα την μυσιαν επειραζον [κατα]{.greek-omitted} [εις]{.greek-added} την [βιθυνιαν]{.greek-omitted} [βυθυνιαν]{.greek-added} πορευεσθαι και ουκ ειασεν αυτους το [πνευμα]{.greek-abbr} [[ιησου]{.greek-abbr}]{.greek-added}[16:7]{.aside}

παρελθοντες δε την μυσιαν κατεβησαν εις τρωαδα[16:8]{.aside}

και οραμα δια της νυκτος [ωφθη]{.greek-omitted} τω παυλω [ωφθη]{.greek-added} ανηρ [μακεδων]{.greek-added} τις ην [μακεδων]{.greek-omitted} εστως [και]{.greek-added} παρακαλων αυτον και λεγων διαβας εις [μακεδονιαν]{.greek-omitted} [μακεδωνιαν]{.greek-added} βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα ειδεν ευθεως εζητησαμεν εξελθειν εις την [μακεδονιαν]{.greek-omitted} [μακεδω[ν]{.unclear}ιαν]{.greek-added} [συμβιβαζοντες]{.greek-omitted} [συνβηβαζοντες]{.greek-added} οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι αυτους[16:10]{.aside}

αναχθεντες [ουν]{.greek-omitted} [δε]{.greek-added} απο της τρωαδος ευθυδρομησαμεν εις σαμοθρακην τη [τε]{.greek-omitted} [δε]{.greek-added} επιουση εις νεαπολιν[16:11]{.aside}

[εκειθεν]{.greek-omitted} [κακειθεν]{.greek-added} [τε]{.greek-omitted} εις φιλιππους ητις εστιν πρωτη της μεριδος της μακεδονιας πολις [κολωνεια]{.greek-omitted} [κωλωνια]{.greek-added} ημεν δε εν [αυτη]{.greek-omitted} [ταυτη]{.greek-added} τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των σαββατων εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο προσευχη ειναι και [καθισαντες]{.greek-omitted} [καθησαντες]{.greek-added} ελαλουμεν ταις συνελθουσαις γυναιξιν[16:13]{.aside}

και τις γυνη ονοματι λυδια πορφυροπωλις πολεως [θυατειρων]{.greek-omitted} [θυατηρων]{.greek-added} σεβομενη τον [θεον]{.greek-abbr} ηκουεν ης ο [κυριος]{.greek-abbr} διηνοιξεν την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης παρεκαλεσεν λεγουσα ει κεκρικατε με πιστην τω [κυριω]{.greek-abbr} ειναι εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις [την]{.greek-added} προσευχην παιδισκην τινα εχουσαν [πνευμα]{.greek-abbr} [πυθωνος]{.greek-omitted} [ποιθονος]{.greek-added} [απαντησαι]{.greek-omitted} [υπαντησαι]{.greek-added} ημιν ητις εργασιαν πολλην παρειχεν τοις κυριοις αυτης [μαντευομενη]{.greek-omitted} [μαντευωμενη]{.greek-added}[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και ημιν εκραζεν λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον σωτηριας[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} ειπεν παραγγελλω σοι εν [τω]{.greek-omitted} ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η [ελπις]{.greek-omitted} [ελπεις]{.greek-added} της εργασιας αυτων επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις [στρατηγοις]{.greek-omitted} [στρατιγοις]{.greek-added} ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

[και]{.greek-omitted} [καταγγελουσιν]{.greek-added} [καταγγελλουσιν]{.corr} εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις ουσιν[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι [περιρρηξαντες]{.greek-omitted} [περιρηξαντες]{.greek-added} αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω [δεσμοφυλακι]{.greek-omitted} [δεσμωφυλακι]{.greek-added} ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην [ειληφως]{.greek-omitted} [λαβων]{.greek-added} εβαλεν αυτους εις την εσωτεραν φυλακην και τους ποδας [εισφαλισατο]{.greek-added} αυτων [ησφαλισατο]{.greek-omitted} εις το ξυλον[16:24]{.aside}

[κατα]{.greek-omitted} [περι]{.greek-added} δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [επηκροωντο]{.greek-omitted} [δε]{.greek-omitted} [αυτων]{.greek-omitted} [οι]{.greek-omitted} [δεσμιοι]{.greek-omitted}[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του [δεσμωτηριου]{.greek-omitted} [δεσμοτηριου]{.greek-added} [ανεωχθησαν]{.greek-omitted} [ηνεωχθησαν]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο [δεσμοφυλαξ]{.greek-omitted} [δεσμωφυλαξ]{.greek-added} και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν [εμελλεν]{.greek-omitted} [ημελλεν]{.greek-added} εαυτον αναιρειν [νομιζων]{.greek-omitted} [νομιζον]{.greek-added} εκπεφευγεναι τους δεσμιους[16:27]{.aside}

εφωνησεν δε [μεγαλη]{.greek-added} [τη]{.greek-added} φωνη [μεγαλη]{.greek-omitted} ο παυλος λεγων μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

[αιτησας]{.greek-omitted} [αιτεισας]{.greek-added} δε φωτα [εισεπηδησεν]{.greek-omitted} [εισεπιδησεν]{.greek-added} και εντρομος γενομενος προσεπεσεν τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και [σωθηση]{.greek-omitted} [σωθησει]{.greek-added} συ και ο οικος σου[16:31]{.aside}

και ελαλησαν αυτω τον λογον του [κυριου]{.greek-abbr} [και]{.greek-omitted} [συν]{.greek-added} πασιν τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα της νυκτος ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου πα[ν]{.unclear}τες παραχρημα[16:33]{.aside}

αναγαγων τε αυτους εις τον οικον αυτου παρεθηκεν τραπεζαν και [ηγαλλιατο]{.greek-omitted} [ηγαλληασατο]{.greek-added} [πανοικι]{.greek-omitted} [πανοικει]{.greek-added} πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενομενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους ανθρωπους εκεινους[16:35]{.aside}

απηγγειλεν δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι [απεσταλκασιν]{.greek-omitted} [απεσταλκαν]{.greek-added} οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους [δειραντες]{.greek-omitted} [δηραντες]{.greek-added} ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας εκβαλλουσιν ου γαρ α[λλ]{.unclear}α ελθοντες αυτοι [ημας]{.greek-added} εξαγαγετωσαν[16:37]{.aside}

[ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} δε τοις [στρατηγοις]{.greek-omitted} [στρατιγοις]{.greek-added} οι ραβδουχοι τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι εισιν[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και εξαγαγοντες [ηρωτων]{.greek-omitted} [ηρωτον]{.greek-added} [εξελθειν]{.greek-omitted} [απελθειν]{.greek-added} [απο]{.greek-added} της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες [παρεκαλεσαν]{.greek-added} τους αδελφους [παρεκαλεσαν]{.greek-omitted} [αυτους]{.greek-omitted} και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την [αμφιπολιν]{.greek-omitted} [αμφηπολιν]{.greek-added} και [[την]{.greek-supplied}]{.greek-added} [απολλωνιαν]{.greek-omitted} [[α]{.greek-supplied}[π]{.unclear}[ο]{.greek-supplied}λωνιαν]{.greek-added} ηλθον εις [θεσσαλονικην]{.greek-omitted} [θεσαλονικην]{.greek-added} οπου ην [η]{.greek-omitted} συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το [ειωθος]{.greek-omitted} [ιοθως]{.greek-added} τω παυλω εισηλθεν προς αυτους και επι σαββατα τρια διελεξατο [αυτοις]{.greek-omitted} [αυτους]{.greek-added} απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος οτι τον [χριστον]{.greek-abbr} εδει πα[θ]{.unclear}ειν και αναστηναι εκ νεκρων και οτι ουτος εστιν [ο]{.greek-omitted} [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων [επεισθησαν]{.greek-omitted} [επισθησαν]{.greek-added} και [προσε]{.greek-supplied}κληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων [πολυ]{.greek-omitted} πληθος [πολλυ]{.greek-added} γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

[προσλαβομενοι]{.greek-omitted} [ζηλωσαντες]{.greek-added} δε οι ιουδαιοι [οι]{.greek-omitted} [απειθουντες]{.greek-omitted} [και]{.greek-added} [προσλαβομενοι]{.greek-added} των [αγοραιων]{.greek-omitted} [αγορεων]{.greek-added} [ανδρας]{.greek-added} τινας [ανδρας]{.greek-omitted} πονηρους και οχλοποιη[σα]{.unclear}ντες εθορυβουν την πολιν [και]{.greek-added} επισταντες [τε]{.greek-omitted} τη οικια [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} εζητουν αυτους [αγαγειν]{.greek-omitted} [προσαγαγειν]{.greek-added} εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τον [ιασονα]{.greek-omitted} [ιασωνα]{.greek-added} και τινας αδελφους επι τους πολιταρχας βοωντες οτι οι την οικουμενην [αναστατωσαντες]{.greek-omitted} [αναστατοσαντες]{.greek-added} ουτοι και ενθαδε [παρεισιν]{.greek-omitted} [παρησιν]{.greek-added}[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος πρασσουσιν βασιλεα [ετερον]{.greek-added} λεγοντες [ετερον]{.greek-omitted} ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον οχλον και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του [ιασονος]{.greek-omitted} [ιασωνος]{.greek-added} και των [λοιπων]{.greek-omitted} [λυπων]{.greek-added} απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια [της]{.greek-omitted} νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις [βεροιαν]{.greek-omitted} [βερροιαν]{.greek-added} οιτινες παραγενομενοι εις την συναγωγην [απηεσαν]{.greek-omitted} των ιουδαιων [απιεσαν]{.greek-added}[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας το καθ ημεραν ανακρινοντες τας γραφας ει [εχοι]{.greek-omitted} ταυτα ουτως [εχοι]{.greek-added}[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της θεσσαλονικης ιουδαιοι οτι και εν τη βεροια κατηγγελη υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες [και]{.greek-added} [ταρασσοντες]{.greek-added} τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι ως επι την θαλασσαν [υπεμενον]{.greek-omitted} [δε]{.greek-omitted} [επεμειναν]{.greek-added} [τε]{.greek-added} ο τε σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε [καθιστωντες]{.greek-omitted} [αποκαθιστοντες]{.greek-added} τον παυλον ηγαγον [αυτον]{.greek-omitted} εως αθηνων και λαβοντες εντολην προς τον σιλαν και τιμοθεον ινα ως ταχιστα ελθωσιν προς αυτον [εξηεσαν]{.greek-omitted} [εξιεσαν]{.greek-added}[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου [παρωξυνετο]{.greek-omitted} [παροξυνετο]{.greek-added} το [πνευμα]{.greek-abbr} αυτου εν αυτω [θεωρουντι]{.greek-omitted} [θεωρουντος]{.greek-added} κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις ιουδαιοις και τοις σεβομενοις και εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε και των [επικουρειων]{.greek-omitted} [επικουριων]{.greek-added} και [των]{.greek-omitted} στοικων φιλοσοφων συνεβαλλον αυτω και τινες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} τι αν θελοι ο σπερμολογος ουτος λεγειν οι δε ξενων δαιμονιων δοκει καταγγελευς ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο [αυτοις]{.greek-added}[17:18]{.aside}

επιλαβομενοι τε αυτου επι τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη [η]{.greek-omitted} υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι [τινα]{.greek-added} [τι]{.greek-omitted} [αν]{.greek-omitted} θελοι ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον [ευκαιρουν]{.greek-omitted} [ηυκαιρουν]{.greek-added} η λεγειν τι και ακουειν [καινοτερον]{.greek-omitted} [καινωτερον]{.greek-added}[17:21]{.aside}

σταθεις δε [ο]{.greek-omitted} παυλος [εν]{.greek-omitted} [μεσω]{.greek-omitted} [εμμεσω]{.greek-added} του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως [δεισιδαιμονεστερους]{.greek-omitted} [δισειδεμονεστερους]{.greek-added} υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και αναθεωρων τα σεβασματα υμων ευρον και [βωμον]{.greek-omitted} [βομον]{.greek-added} εν ω [επεγεγραπτο]{.greek-omitted} [επεγεγραπτω]{.greek-added} αγνωστω [θεω]{.greek-abbr} ον ουν [αγνοουντες]{.greek-omitted} [αγνωουντες]{.greek-added} ευ[σ]{.unclear}εβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο [ποιησας]{.greek-omitted} [ποιεισας]{.greek-added} τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [υπαρχων]{.greek-added} [κυριος]{.greek-abbr} [υπαρχων]{.greek-omitted} ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε [υ]{.unclear}[πο]{.greek-supplied} χειρων [ανθρωπων]{.greek-abbr} θεραπευεται [ως]{.greek-added} προσδε[ο]{.unclear}μενος τινος αυτος διδους [πασιν]{.greek-omitted} [πασι]{.greek-added} ζωην και πνοην κατα παντα[17:25]{.aside}

εποιησεν τε εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι [παντος]{.greek-added} [παν]{.greek-omitted} [το]{.greek-omitted} [προσωπον]{.greek-omitted} [προσωπου]{.greek-added} της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ει αρα γε [ψηλαφησειαν]{.greek-omitted} [ψιλαφησειαν]{.greek-added} αυτον και [ευροιεν]{.greek-omitted} [ευρυεν]{.greek-added} και γε ου μακραν απο ενος εκαστου ημων υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ υμας ποιητων ειρηκασιν του γαρ και γενος εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν [χρυσω]{.greek-omitted} [χρυσιω]{.greek-added} η [αργυρω]{.greek-omitted} [αργυριω]{.greek-added} η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-abbr} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} [πασιν]{.greek-omitted} [παντας]{.greek-added} πανταχου μετανοειν[17:30]{.aside}

[διοτι]{.greek-omitted} [καθοτι]{.greek-added} εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω ωρισεν [πιστιν]{.greek-omitted} [πιστην]{.greek-added} παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον [ακουσομεθα]{.greek-omitted} [ακουσωμεθα]{.greek-added} σου [παλιν]{.greek-omitted} περι τουτου [και]{.greek-added} [παλιν]{.greek-added}[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο [αρεοπαγιτης]{.greek-omitted} [αρεωπαγητης]{.greek-added} και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα [ταυτα]{.greek-added} δε [ταυτα]{.greek-omitted} χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και [ευρων]{.greek-omitted} [ευρον]{.greek-added} τινα ιουδαιον [ακυλαν]{.greek-added} ονοματι [ακυλαν]{.greek-omitted} ποντικον τω [γενει]{.greek-omitted} [γενη]{.greek-added} προσφατως εληλυθοτα απο [της]{.greek-omitted} ιταλιας και πρισκιλλαν γυναικα αυτου δια [το]{.greek-omitted} [τω]{.greek-added} τεταχεναι κλαυδιον χωριζεσθαι παντας τους ιουδαιους εκ της ρωμης προσηλθεν αυτοις[18:2]{.aside}

[κ]{.unclear}[αι]{.greek-supplied} δια το ομοτεχνον ειναι εμενεν παρ αυτοις και [ειργαζετο]{.greek-omitted} [ηργαζε[το]{.greek-supplied}]{.greek-added} ησαν γαρ [σκηνοποιοι]{.greek-omitted} [σκηνωποιοι]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [τεχνην]{.greek-omitted} [τεχνη]{.greek-added}[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον επειθεν τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και ο τιμοθεος [συνειχετο]{.greek-omitted} [συνηχετο]{.greek-added} τω [πνευματι]{.greek-abbr} ο παυλος [διαμαρτυρομενος]{.greek-omitted} [διαμαρτυρωμενος]{.greek-added} τοις ιουδαιοις [ειναι]{.greek-added} τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων εκτιναξαμενος [αυτου]{.greek-added} τα ιματια ειπεν προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας εκειθεν [ηλθεν]{.greek-omitted} [εισηλθεν]{.greek-added} εις οικιαν τινος ονοματι ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια ην συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος επιστευσεν τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων ακουοντες επιστευον και εβαπτιζοντο[18:8]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} [εν]{.greek-added} [νυκτι]{.greek-added} δι οραματος [εν]{.greek-omitted} [νυκτι]{.greek-omitted} τω παυλω μη φοβου αλλα λαλει και μη σιωπησης[18:9]{.aside}

[διοτι]{.greek-omitted} εγω [γαρ]{.greek-added} ειμι μετα σου και ουδεις επιθησεται σοι του κακωσαι σε διοτι λαος [εστιν]{.greek-omitted} [εστι]{.greek-added} μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

εκαθισεν τε ενιαυτον και μηνας εξ διδασκων εν αυτοις τον λογον του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added}[18:11]{.aside}

[γαλλιωνος]{.greek-omitted} [γαλλιονος]{.greek-added} δε ανθυπατευοντος της αχαιας κατεπεστησαν ομοθυμαδον οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον [ουτος]{.greek-omitted} [αναπειθει]{.greek-omitted} [αναπιθη]{.greek-added} τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα [αυτου]{.greek-added} ειπεν ο γαλλιων προς τους ιουδαιους ει μεν [ουν]{.greek-omitted} ην αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν [ηνεσχομην]{.greek-omitted} [ανεσχομην]{.greek-added} υμων[18:14]{.aside}

ει δε [ζητημα]{.greek-omitted} [ζητηματα]{.greek-added} εστιν περι λογου και ονοματων και νομου του καθ υμας [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και [απηλασεν]{.greek-omitted} [απειλασεν]{.greek-added} αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι [δε]{.greek-omitted} [τε]{.greek-added} παντες οι ελληνες [σωσθενην]{.greek-omitted} [σοσθενην]{.greek-added} τον αρχισυναγωγον ετυπτον εμπροσθεν [επι]{.greek-added} του βηματος και ουδεν τουτων τω γαλλιωνι εμελλεν[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος [αυτοις]{.greek-added} εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος [εν]{.greek-added} [κεγχρειαις]{.greek-added} την κεφαλην [εν]{.greek-omitted} [κεγχρεαις]{.greek-omitted} ειχεν γαρ ευχην[18:18]{.aside}

[κατηντησεν]{.greek-omitted} [κατηντησαν]{.greek-added} δε εις εφεσον [και]{.greek-omitted} [εκεινους]{.greek-omitted} [κακεινους]{.greek-added} κατελιπεν αυτου αυτος δε εισελθων εις την συναγωγην διελεχθη τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε αυτων επι πλειονα χρονον [μειναι]{.greek-omitted} [παραμειναι]{.greek-added} [παρ]{.greek-omitted} [αυτοις]{.greek-omitted} ουκ επενευσεν[18:20]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} απεταξατο αυτοις ειπων δει με παντως την εορτην την ερχομενην [της]{.greek-added} [πεντικοστης]{.greek-added} ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

και κατελθων εις [καισαρειαν]{.greek-omitted} [καισαριαν]{.greek-added} αναβας και ασπασαμενος την εκκλησιαν κατεβη εις [αντιοχειαν]{.greek-omitted} [αντιωχειαν]{.greek-added}[18:22]{.aside}

και ποιησας χρονον τινα εξηλθεν διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις [απολλως]{.greek-omitted} [απελης]{.greek-added} ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε αυτου [πρισκιλλα]{.greek-added} [και]{.greek-added} ακυλας [και]{.greek-omitted} [πρισκιλλα]{.greek-omitted} προσελαβοντο αυτον και ακριβεστερον [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεθεντο την [οδον]{.greek-added} του [θεου]{.greek-abbr} [οδον]{.greek-omitted}[18:26]{.aside}

βουλομενου δε αυτου διελθειν εις την αχαιαν προτρεψαμενοι οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος [συνεβαλετο]{.greek-omitted} [συνεβαλλετο]{.greek-added} πολυ τοις πεπιστευκοσιν δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις [διακατηλεγχετο]{.greek-omitted} [διακατηλλεγχετο]{.greek-added} δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω [το]{.greek-supplied}ν απολλω ειναι εν κορινθω παυλον διελθοντα τα ανωτερικα μερη [ελθειν]{.greek-omitted} [κατελθειν]{.greek-added} εις εφεσον και [ευρων]{.greek-omitted} [ευρειν]{.greek-added} τινας μαθητας[19:1]{.aside}

ειπεν [τε]{.greek-added} προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

[ο]{.greek-added} [δε]{.greek-added} ειπεν [τε]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} εις τι ουν εβαπτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

ειπεν δε παυλος ιωαννης μεν εβαπτισεν βαπτισμα μετανοιας [παντι]{.greek-added} τω λαω λεγων εις τον ερχομενον μετ αυτον ινα πιστευσωσιν τουτ εστιν εις τον [[ιησουν]{.greek-abbr}]{.greek-added} [χριστον]{.greek-abbr} [ιησουν]{.greek-omitted}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας ηλθεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και προεφητευον[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει [δεκαδυο]{.greek-omitted} [δωδεκα]{.greek-added}[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους αποστας απ αυτων αφωρισεν τους μαθητας [το]{.greek-added} καθ ημεραν διαλεγομενος εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι ετη δυο ωστε παντας τους κατοικουντας [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [ασιαν]{.greek-omitted} [ασια]{.greek-added} ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-omitted} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας [εποιει]{.greek-omitted} ο [θεος]{.greek-abbr} [εποιει]{.greek-added} δια των χειρων παυλου[19:11]{.aside}

ωστε και επι τους ασθενουντας [επιφερεσθαι]{.greek-omitted} [αποφερεσθαι]{.greek-added} απο του χρωτος αυτου σουδαρια η σιμικινθια και [απαλλασσεσθαι]{.greek-omitted} [απαλλασεσθαι]{.greek-added} απ αυτων τας νοσους τα τε [πνευματα]{.greek-abbr} τα πονηρα [εξερχεσθαι]{.greek-omitted} [εκπορευεσθαι]{.greek-added} απ αυτων[19:12]{.aside}

επεχειρησαν δε τινες [απο]{.greek-omitted} [και]{.greek-added} των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους εχοντας τα πνευματα τα πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} λεγοντες [ορκιζομεν]{.greek-omitted} [ορκιζωμεν]{.greek-added} υμας τον [ιησουν]{.greek-abbr} ον [ο]{.greek-omitted} παυλος κηρυσσει[19:13]{.aside}

ησαν δε τινες υιοι σκευα ιουδαιου αρχιερεως επτα [οι]{.greek-omitted} [υιοι]{.greek-added} τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε [τοτε]{.greek-added} το [πνευμα]{.greek-abbr} το πονηρον ειπεν [αυτοις]{.greek-added} τον [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και εφαλλομενος [ο]{.greek-added} [ανθροπος]{.greek-added} επ αυτους [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον και κατακυριευσαν [αυτων]{.greek-omitted} [αμφοτερων]{.greek-added} ισχυσεν κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν εκ του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον πασιν ιουδαιοις τε και ελλησιν τοις κατοικουσιν την εφεσον και επεπεσεν φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι τε των πεπιστευκοτων ηρχοντο εξομολογουμενοι και αναγγελλοντες τας πραξεις αυτων[19:18]{.aside}

ικανοι [δε]{.greek-omitted} [τε]{.greek-added} των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και συνεψηφισαν τας τιμας αυτων και ευρον αργυριου μυριαδας πεντε[19:19]{.aside}

ουτως κατα κρατος ο λογος του [κυριου]{.greek-abbr} ηυξανεν και [ισχυεν]{.greek-omitted} [ενισχυεν]{.greek-added}[19:20]{.aside}

ως δε επληρωθη ταυτα εθετο ο παυλος εν τω [πνευματι]{.greek-abbr} διελθων την μακεδονιαν και [την]{.greek-added} αχαιαν πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις την μακεδονιαν δυο των διακονουντων αυτω τιμοθεον και εραστον αυτος επεσχεν χρονον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [ασιαν]{.greek-omitted} [ασια]{.greek-added}[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος περι της οδου[19:23]{.aside}

δημητριος γαρ τις ονοματι αργυροκοπος ποιων ναους αργυρους αρτεμιδος παρειχετο τοις [τεχνιταις]{.greek-omitted} [τεχνηταις]{.greek-added} [εργασιαν]{.greek-omitted} ουκ ολιγην [εργασιαν]{.greek-added}[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας ειπεν ανδρες [επιστασθε]{.greek-omitted} [επιστασθαι]{.greek-added} οτι εκ ταυτης της εργασιας η ευπορια [ημων]{.greek-omitted} [ημι[ν]{.unclear}]{.greek-added} [ε]{.unclear}στιν[19:25]{.aside}

και [θεωρειτε]{.greek-omitted} [θεορειτε]{.greek-added} και ακουετε οτι ου μονον εφεσου αλλα [και]{.greek-added} σχεδον πασης της ασιας ο παυλος ουτος πεισας μετεστησεν ικανον οχλον λεγων οτι ουκ εισιν θεοι οι δια χειρων γινομενοι[19:26]{.aside}

ου μονον δε τουτο κινδυνευει ημιν το μερος εις [απελεγμον]{.greek-omitted} [απελλεγμον]{.greek-added} ελθειν αλλα και το της μεγαλης θεας [αρτεμηδος]{.greek-added} ιερον [αρτεμιδος]{.greek-omitted} εις [ουθεν]{.greek-omitted} [ουδεν]{.greek-added} λογισθηναι μελλειν δε [και]{.greek-omitted} καθαιρεισθαι την [μεγαλειοτητα]{.greek-omitted} [μεγαλιοτητα]{.greek-added} αυτης ην ολη η ασια και η οικουμενη σεβεται[19:27]{.aside}

ακουσαντες δε και γενομενοι [πληρεις]{.greek-omitted} [πληρις]{.greek-added} θυμου [εκραζον]{.greek-omitted} [εκραζων]{.greek-added} λεγοντες μεγαλη η αρτεμις εφεσιων[19:28]{.aside}

και επλησθη η πολις ολη της συγχυσεως ωρμησαν τε ομοθυμαδον εις το θεατρον συναρπασαντες γαιον και αρισταρχον μακεδονας συνεκδημους παυλου[19:29]{.aside}

του δε παυλου βουλομενου εισελθειν εις τον δημον ουκ [ειων]{.greek-omitted} [ειον]{.greek-added} [αυτον]{.greek-omitted} [αυτων]{.greek-added} οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες [αυτω]{.greek-omitted} [αυτου]{.greek-added} φιλοι πεμψαντες προς [αυτον]{.greek-omitted} [αυτων]{.greek-added} παρεκαλουν μη δουναι εαυτον εις το θεατρον[19:31]{.aside}

αλλοι μεν ουν αλλο τι εκραζον ην γαρ η εκκλησια [συγκεχυμενη]{.greek-omitted} [συνκεχυμενη]{.greek-added} και οι πλειους ουκ ηδεισαν τινος [ενεκεν]{.greek-omitted} [ενεκα]{.greek-added} [συνεληλυθεισαν]{.greek-omitted} [συνεληλυθησαν]{.greek-added}[19:32]{.aside}

εκ δε του οχλου προεβιβασαν αλεξανδρον προβαλοντων αυτον των ιουδαιων ο [δε]{.greek-omitted} [ουν]{.greek-added} αλεξανδρος κατασεισας την χειρα ηθελεν απολογεισθαι τω δημω[19:33]{.aside}

[επιγνοντες]{.greek-omitted} [επιγνωντες]{.greek-added} δε οτι ιουδαιος εστιν φωνη εγενετο μια εκ παντων ως επι ωρας δυο κραζοντων μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλας δε ο γραμματευς τον οχλον φησιν ανδρες εφεσιοι τις γαρ εστιν [ανθρωπος]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} ος ου γινωσκει την εφεσιων πολιν [νεωκορον]{.greek-omitted} [νεοκορον]{.greek-added} ουσαν της μεγαλης [θεας]{.greek-omitted} αρτεμιδος και του διοπετους[19:35]{.aside}

[αναντιρρητων]{.greek-omitted} [αναντηρρητων]{.greek-added} ουν οντων τουτων δεον εστιν υμας κατεσταλμενους υπαρχειν και μηδεν προπετες πρασσειν[19:36]{.aside}

ηγαγετε γαρ τους ανδρας τουτους ουτε ιεροσυλους ουτε βλασφημουντας την θεον υμων[19:37]{.aside}

ει μεν ουν δημητριος και οι συν αυτω [τεχνιται]{.greek-omitted} [τεχνηται]{.greek-added} εχουσιν προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν εγκαλειτωσαν αλληλοις[19:38]{.aside}

ει δε τι περι ετερων επιζητειτε εν τη εννομω εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι [της]{.greek-omitted} [την]{.greek-added} σημερον μηδενος αιτιου υπαρχοντος περι ου ου δυνησομεθα [δουναι]{.greek-omitted} [αποδουναι]{.greek-added} λογον [περι]{.greek-added} της συστροφης ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσεν]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον θορυβον [προσκαλεσαμενος]{.greek-omitted} [μεταπεμψαμενος]{.greek-added} ο παυλος τους μαθητας και [παρ[α]{.unclear}καλεσας]{.greek-added} ασπασαμενος εξηλθεν [πορευθηναι]{.greek-omitted} [πορευεσθαι]{.greek-added} εις [την]{.greek-omitted} μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας τε μηνας τρεις γενομενης [επιβουλης]{.greek-added} αυτω [επιβουλης]{.greek-omitted} υπο των ιουδαιων [μελλοντι]{.greek-omitted} [μελλον]{.greek-added} αναγεσθαι εις την συριαν εγενετο γνωμη του υποστρεφειν δια μακεδονιας[20:3]{.aside}

συνειπετο δε αυτω αχρι της ασιας [σωπατρος]{.greek-omitted} [σωπτρο[ς]{.greek-supplied}]{.greek-added} βεροιαιος [θεσσαλονικεων]{.greek-omitted} [θεσσαλονικαιων]{.greek-added} δε αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος ασιανοι δε τυχικος και [τροφιμος]{.greek-omitted} [τροφημος]{.greek-added}[20:4]{.aside}

ουτοι [δε]{.greek-added} προσελθοντες εμενον ημας εν τρωαδι[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και ηλθομεν προς αυτους εις την τρωαδα [αχρι]{.greek-omitted} [αχρις]{.greek-added} [απο]{.greek-added} ημερων πεντε [ου]{.greek-omitted} [οπου]{.greek-added} διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων [ημων]{.greek-added} [των]{.greek-omitted} [μαθητων]{.greek-omitted} κλασαι αρτον ο παυλος διελεγετο αυτοις [μελλων]{.greek-omitted} [μελλον]{.greek-added} εξιεναι τη επαυριον παρετεινεν τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε λαμπαδες ικαναι εν τω υπερωω ου ημεν συνηγμενοι[20:8]{.aside}

[καθημενος]{.greek-omitted} [καθεζομενος]{.greek-added} δε τις νεανιας ονοματι ευτυχος επι της θυριδος καταφερομενος υπν[ω]{.unclear} [βαθει]{.greek-omitted} [βαθη]{.greek-added} διαλεγομενου του παυλου επι πλειον κατενεχθεις απο του υπνου επεσεν απο του [τριστεγου]{.greek-omitted} [τρειστεγου]{.greek-added} κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και συμπεριλαβων [αυτον]{.greek-added} ειπεν μη θορυβεισθε η γαρ ψυχη αυτου εν αυτω εστιν[20:10]{.aside}

αναβας δε και κλασας [τον]{.greek-added} αρτον και γευσαμενος εφ ικανον [τε]{.greek-omitted} [δε]{.greek-added} [ομιλησας]{.greek-omitted} [ομηλησας]{.greek-added} αχρι αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον δε τον παιδα ζωντα και παρεκληθησαν ου μετριως[20:12]{.aside}

ημεις δε προσελθοντες επι το πλοιον ανηχθημεν [εις]{.greek-omitted} [επι]{.greek-added} την ασσον εκειθεν μελλοντες αναλαμβανειν τον παυλον ουτως γαρ [διατεταγμενον]{.greek-added} ην [διατεταγμενος]{.greek-omitted} [μελλων]{.greek-omitted} [μελλον]{.greek-added} αυτος πεζευειν[20:13]{.aside}

ως δε συνεβαλεν ημιν εις την ασσον αναλαβοντες αυτον ηλθομεν εις [μιτυληνην]{.greek-omitted} [μιτυλινην]{.greek-added}[20:14]{.aside}

κακειθεν αποπλευσαντες τη επιουση κατηντησαμεν [αντικρυ]{.greek-omitted} [αντικρυς]{.greek-added} χιου τη δε ετερα παρεβαλομεν εις σαμον [και]{.greek-omitted} [μειναντες]{.greek-omitted} [εν]{.greek-omitted} [τρωγυλλιω]{.greek-omitted} τη [δε]{.greek-added} εχομενη ηλθομεν εις μιλητον[20:15]{.aside}

[εκρινεν]{.greek-omitted} [κεκρικει]{.greek-added} γαρ ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια εσπευδεν γαρ ει δυνατον ην αυτω την ημεραν της πεντηκοστης γενεσθαι εις [ιεροσολυμα]{.greek-omitted} [[ιερουσαλημ]{.greek-abbr}]{.greek-added}[20:16]{.aside}

απο δε της μιλητου πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον ειπεν αυτοις υμεις επιστασθε απο πρωτης ημερας αφ ης επεβην εις την ασιαν πως μεθ υμων τον παντα χρονον εγενομην[20:18]{.aside}

δουλευων τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και [πολλων]{.greek-omitted} δακρυων και πειρασμων των συμβαντων μοι εν ταις επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων του μη αναγγειλαι υμιν και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

διαμαρτυρομενος [τε]{.greek-added} ιουδαιοις [τε]{.greek-omitted} και ελλησιν την εις τον [θεον]{.greek-abbr} μετανοιαν και [πιστιν]{.greek-omitted} [πιστην]{.greek-added} [την]{.greek-omitted} εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr} [[χριστον]{.greek-abbr}]{.greek-added}[20:21]{.aside}

και νυν ιδου [εγω]{.greek-omitted} δεδεμενος τω [πνευματι]{.greek-abbr} πορευομαι εις [ιερουσαλημ]{.greek-abbr} τα εν αυτη συναντησοντα μοι μη [ειδως]{.greek-omitted} [ιδως]{.greek-added}[20:22]{.aside}

πλην οτι το [πνευμα]{.greek-abbr} το αγιον κατα πολιν διαμαρτυρεται [μοι]{.greek-added} λεγον οτι δεσμα [με]{.greek-omitted} και θλιψεις [με]{.greek-added} μενουσιν[20:23]{.aside}

αλλ ουδενος λογον [[λογον]{.unclear}]{.greek-added} [εχω]{.greek-added} [ουδε]{.greek-added} ποιουμαι [ουδε]{.greek-omitted} [εχω]{.greek-omitted} την ψυχην [μου]{.greek-omitted} τιμιαν εμαυτω ως τελειωσαι τον δρομον μου [μετα]{.greek-omitted} [χαρας]{.greek-omitted} και την διακονιαν ην ελαβον παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι οψεσθε το προσωπον μου υμεις παντες εν οις διηλθον κηρυσσων την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

διοτι μαρτυρομαι υμιν εν τη σημερον ημερα οτι καθαρος [εγω]{.greek-omitted} [ειμι]{.greek-added} απο του αιματος παντων[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι [υμιν]{.greek-omitted} πασαν την βουλην του [θεου]{.greek-abbr} [υμιν]{.greek-added}[20:27]{.aside}

προσεχετε [ουν]{.greek-omitted} εαυτοις και παντι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επισκοπους [ποιμαινειν]{.greek-omitted} [ποιμενην]{.greek-added} την εκκλησιαν του [κυριου]{.greek-abbr} [και]{.greek-omitted} [θεου]{.greek-omitted} ην περιεποιησατο δια του [αιματος]{.greek-added} [του]{.greek-added} ιδιου [αιματος]{.greek-omitted}[20:28]{.aside}

εγω γαρ οιδα [τουτο]{.greek-omitted} οτι εισελευσονται μετα την αφιξιν μου λυκοι βαρεις εις υμας μη φειδομενοι του [ποιμνιου]{.greek-omitted} [ποιμνηου]{.greek-added}[20:29]{.aside}

και εξ υμων αυτων αναστησονται ανδρες λαλουντες διεστραμμενα του αποσπαν τους μαθητας [οπισω]{.greek-omitted} [οπησω]{.greek-added} αυτων[20:30]{.aside}

διο γρηγορειτε μνημονευοντες οτι [τριετιαν]{.greek-omitted} [τριετια]{.greek-added} νυκτα και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον [υμων]{.greek-added}[20:31]{.aside}

και τα νυν [παρατιθεμαι]{.greek-omitted} [παρατηθεμαι]{.greek-added} υμας αδελφοι τω [θεω]{.greek-abbr} και τω λογω της χαριτος αυτου τω δυναμενω [εποικοδομησαι]{.greek-omitted} [οικοδομησαι]{.greek-added} και δουναι υμιν [την]{.greek-added} κληρονομιαν εν τοις ηγιασμενοις πασιν[20:32]{.aside}

αργυριου η χρυσιου η ιματισμου [ουδενος]{.greek-omitted} [ουθενος]{.greek-added} επεθυμησα[20:33]{.aside}

αυτοι γινωσκετε οτι ταις χρειαις μου και τοις ουσιν μετ εμου [υπηρετησαν]{.greek-omitted} [υπειρετησαν]{.greek-added} αι [χειρες]{.greek-omitted} [χειραι]{.greek-added} αυται[20:34]{.aside}

[και]{.greek-added} παντα υπεδειξα υμιν οτι ουτως [κοπιωντας]{.greek-omitted} [κοπιοντας]{.greek-added} δει [αντιλαμβανεσθαι]{.greek-omitted} [αντηλαμβανεσθαι]{.greek-added} των ασθενουντων μνημονευειν τε των λογων του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} οτι αυτος ειπεν μακαριον εστιν μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα γονατα αυτου συν πασιν αυτοις προσηυξατο[20:36]{.aside}

ικανος δε [κλαυθμος]{.greek-added} εγενετο [κλαυθμος]{.greek-omitted} παντων και επιπεσοντες επι τον τραχηλον του παυλου κατεφιλουν αυτον[20:37]{.aside}

οδυνωμενοι μαλιστα επι τω λογω ω ειρηκει οτι ουκετι μελλουσιν το προσωπον αυτου [θεωρειν]{.greek-omitted} [θεορειν]{.greek-added} προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας [αποσπασθεντας]{.greek-omitted} [αποσπασθεντες]{.greek-added} απ αυτων ευθυδρομησαντες [ηλθομεν]{.greek-omitted} [ηλθαμεν]{.greek-added} εις την κων τη δε εξης εις την ροδον κακειθεν εις παταρα[21:1]{.aside}

και ευροντες πλοιον διαπερων εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

αναφανεντες δε την κυπρον και [καταλιποντες]{.greek-omitted} [καταλειποντες]{.greek-added} αυτην ευωνυμον επλεομεν εις συριαν και [κατηχθημεν]{.greek-omitted} [κατηλθομεν]{.greek-added} εις τυρον εκεισε γαρ ην το πλοιον αποφορτιζομενον τον γομον[21:3]{.aside}

[και]{.greek-omitted} ανευροντες [δε]{.greek-added} [τους]{.greek-added} μαθητας επεμειναμεν [αυτου]{.greek-omitted} [αυτοις]{.greek-added} ημερας επτα οιτινες τω παυλω [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} δια του [πνευματος]{.greek-abbr} μη [αναβαινειν]{.greek-omitted} [επιβαινειν]{.greek-added} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added}[21:4]{.aside}

οτε δε εγενετο [εξαρτισαι]{.greek-added} ημας [εξαρτισαι]{.greek-omitted} τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν γυναιξιν και τεκνοις εως εξω της πολεως και θεντες τα γονατα επι τον αιγιαλον [προσηυξαμεθα]{.greek-omitted} [προσευξαμενοι]{.greek-added}[21:5]{.aside}

και ασπασαμενοι αλληλους επεβημεν εις το πλοιον εκεινοι δε υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν [διανυσαντες]{.greek-omitted} [διανοισαντες]{.greek-added} απο τυρου [κατηντησαμεν]{.greek-omitted} [κατεβημεν]{.greek-added} εις πτολεμαιδα και ασπασαμενοι τους αδελφους εμειναμεν ημεραν μιαν παρ αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες [οι]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [ηλθον]{.greek-omitted} [ηλθομεν]{.greek-added} εις καισαρειαν και εισελθοντες εις τον οικον φιλιππου του ευαγγελιστου οντος εκ των επτα εμειναμεν παρ αυτω[21:8]{.aside}

τουτω δε ησαν θυγατερες [τεσσαρες]{.greek-added} παρθενοι [τεσσαρες]{.greek-omitted} προφητευουσαι[21:9]{.aside}

επιμενοντων δε [ημων]{.greek-omitted} ημερας πλειους κατηλθεν τις απο της ιουδαιας προφητης ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρας την ζωνην του παυλου δησας [τε]{.greek-omitted} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} [τας]{.greek-added} [χειρας]{.greek-added} [και]{.greek-added} τους ποδας [και]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} ειπεν ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τον ανδρα ου εστιν η ζωνη αυτη ουτως δησουσιν εν [ιερουσαλημ]{.greek-abbr} οι ιουδαιοι και παραδωσουσιν εις χειρας εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκαλουμεν ημεις τε και οι εντοπιοι του μη αναβαινειν [αυτον]{.greek-omitted} εις [ιερουσαλημ]{.greek-abbr}[21:12]{.aside}

[τοτε]{.greek-added} απεκριθη [τε]{.greek-omitted} ο παυλος τι [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} κλαιοντες και συνθρυπτοντες μου την καρδιαν εγω γαρ ου μονον δεθηναι αλλα και αποθανειν εις [ιερουσαλημ]{.greek-abbr} [ετοιμως]{.greek-omitted} [ετυμως]{.greek-added} εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου ησυχασαμεν ειποντες το θελημα του [κυριου]{.greek-abbr} γενεσθω[21:14]{.aside}

μετα δε τας ημερας ταυτας [επισκευασαμενοι]{.greek-omitted} [επισκευσαμενοι]{.greek-added} ανεβαινομεν εις [ιερουσαλημ]{.greek-abbr}[21:15]{.aside}

[συνηλθον]{.greek-omitted} [συνηλθων]{.greek-added} δε και των μαθητων απο καισαρειας συν ημιν αγοντες παρ ω ξενισθωμεν [μνασωνι]{.greek-omitted} [μνασονι]{.greek-added} τινι κυπριω αρχαιω μαθητη[21:16]{.aside}

γενομενων δε ημων εις ιεροσολυμα ασμενως εδεξαντο ημας οι αδελφοι[21:17]{.aside}

τη δε επιουση [εισηει]{.greek-omitted} [εισειη]{.greek-added} ο παυλος συν ημιν προς ιακωβον παντες τε παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος αυτους εξηγειτο καθ εν εκαστον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις εθνεσιν δια της διακονιας αυτου[21:19]{.aside}

οι δε ακουσαντες εδοξαζον τον [κυριον]{.greek-abbr} ειποντες αυτω θεωρεις αδελφε ποσαι μυριαδες εισιν ιουδαιων των πεπιστευκοτων και παντες ζηλωται του νομου υπαρχουσιν[21:20]{.aside}

κατηχηθησαν δε περι σου οτι αποστασιαν διδασκεις απο μωυσεως τους κατα τα εθνη παντας ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις εθεσιν περιπατειν[21:21]{.aside}

τι ουν εστιν παντως δει πληθος συνελθειν [ακουσονται]{.greek-omitted} [ακουσοντε[ς]{.unclear}]{.greek-added} γαρ οτι εληλυθας[21:22]{.aside}

τουτο ουν ποιησον ο σοι λεγομεν εισιν ημιν ανδρες τεσσαρες ευχην εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων [αγνισθητι]{.greek-omitted} [αγνησθητι]{.greek-added} συν αυτοις και [δαπανησον]{.greek-omitted} [δαπανισον]{.greek-added} επ αυτοις ινα [ξυρησωνται]{.greek-omitted} [ξυρησονται]{.greek-added} την κεφαλην και [γνωσιν]{.greek-omitted} [γνωσονται]{.greek-added} παντες οτι ων κατηχηνται περι σου ουδεν εστιν αλλα στοιχεις και αυτος τον νομον φυλασσων[21:24]{.aside}

περι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες μηδεν τοιουτον τηρειν αυτους ει μη φυλασσεσθαι αυτους το τε ειδωλοθυτον και το αιμα και πνικτον και πορνειαν[21:25]{.aside}

τοτε ο παυλος παραλαβων τους ανδρας τη εχομενη ημερα συν αυτοις [αγνισθεις]{.greek-omitted} [αγνησθεις]{.greek-added} [εισηει]{.greek-omitted} [εισειη]{.greek-added} εις το ιερον διαγγελλων την εκπληρωσιν των ημερων του αγνισμου εως ου προσηνεχθη υπερ ενος εκαστου αυτων η προσφορα[21:26]{.aside}

ως δε εμελλον αι επτα ημεραι συντελεισθαι οι απο της ασιας ιουδαιοι θεασαμενοι αυτον εν τω ιερω συνεχεον παντα τον οχλον και [επεβαλον]{.greek-omitted} [επεβαλλον]{.greek-added} τας χειρας επ αυτον[21:27]{.aside}

κραζοντες ανδρες ισραηλιται [βοηθειτε]{.greek-omitted} [βοηθηται]{.greek-added} ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου τουτου παντας πανταχου διδασκ[ω]{.unclear}ν ετι τε και ελληνας εισηγαγεν εις το ιερον και κεκοινωκεν τον αγιον τοπον τουτον[21:28]{.aside}

ησαν γαρ εωρακοτες τροφιμον τον εφεσιον εν τη πολει συν αυτω ον ενομιζον οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

[εκινηθη]{.greek-omitted} [εκεινηθη]{.greek-added} τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του παυλου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

ζητουντων δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της σπειρης οτι ολη συγκεχυται [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και εκατονταρχους κατεδραμεν επ αυτους οι δε ιδοντες τον χιλιαρχον και τους στρατιωτας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

[τοτε]{.greek-added} [εγγισας]{.greek-omitted} [εγγησας]{.greek-added} [δε]{.greek-omitted} ο χιλιαρχος επελαβετο αυτου και εκελευσεν [αυτον]{.greek-added} δεθηναι αλυσεσιν δυσιν και [επυνθανετο]{.greek-omitted} [εποινθανετο]{.greek-added} τις αν ειη και τι εστιν πεποιηκως[21:33]{.aside}

αλλοι δε αλλο τι εβοων εν τω οχλω μη δυναμενος δε γνωναι το ασφαλες δια τον θορυβον εκελευσεν αγεσθαι αυτον εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον υπο των στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

[ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} γαρ το πληθος του λαου κραζον αιρε αυτον[21:36]{.aside}

μελλων [τε]{.greek-omitted} [δε]{.greek-added} εισαγεσθαι εις την παρεμβολην ο παυλος λεγει τω χιλιαρχω ει [εξεστιν]{.greek-omitted} [εξε]{.greek-added} [στιν]{.greek-added} μοι ειπειν προς σε ο δε εφη [ελληνιστι]{.greek-omitted} [ελληνιστη]{.greek-added} γινωσκεις[21:37]{.aside}

ουκ αρα συ ει ο αιγυπτιος ο προ τουτων των ημερων αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

ειπεν δε ο παυλος εγω [μεν]{.greek-added} [ανθρωπος]{.greek-abbr} [μεν]{.greek-omitted} ειμι ιουδαιος ταρσευς της κιλικιας ουκ [ασημου]{.greek-omitted} [ασιμου]{.greek-added} πολεως πολιτης δεομαι δε σου επιτρεψον μοι λαλησαι προς τον λαον[21:39]{.aside}

επιτρεψαντος δε αυτου ο παυλος εστως επι των αναβαθμων [κατεσεισεν]{.greek-omitted} [κατεσησεν]{.greek-added} τη χειρι τω λαω πολλης δε σιγης γενομενης προσεφωνει [δε]{.greek-added} τη [εβραιδι]{.greek-omitted} [εβραιδει]{.greek-added} διαλεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς υμας νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη [εβραιδι]{.greek-omitted} [εβραιδει]{.greek-added} διαλεκτω προσεφωνει αυτοις μαλλον παρεσχον ησυχιαν και φησιν[22:2]{.aside}

εγω μεν ειμι ανηρ ιουδαιος γεγεννημενος εν ταρσω της κιλικιας ανατεθραμμενος δε εν τη πολει ταυτη παρα τους ποδας γαμαλιηλ πεπαιδευμενος κατα [ακριβειαν]{.greek-omitted} [ακριβιαν]{.greek-added} του πατρωου νομου ζηλωτης υπαρχων του [θεου]{.greek-abbr} καθως παντες υμεις εστε σημερον[22:3]{.aside}

ος ταυτην την οδον εδιωξα αχρι θανατου δεσμευων και παραδιδους εις φυλακας ανδρας τε και γυναικας[22:4]{.aside}

ως και ο αρχιερευς μαρτυρει μοι και παν το πρεσβυτεριον παρ ων και επιστολας δεξαμενος προς τους αδελφους εις δαμασκον επορευομην αξων και τους εκεισε οντας δεδεμενους εις [ιερουσαλημ]{.greek-abbr} ινα τιμωρηθωσιν[22:5]{.aside}

εγενετο δε μοι πορευομενω και εγγιζοντι τη δαμασκω περι μεσημβριαν [εξαιφνης]{.greek-omitted} [εξεφνης]{.greek-added} εκ του [ουρανου]{.greek-abbr} περιαστραψαι φως ικανον περι εμε[22:6]{.aside}

επεσα τε εις το εδαφος και ηκουσα φωνης λεγουσης μοι [σαουλε]{.greek-added} [σαουλε]{.greek-added} [σαουλ]{.corr} [σαουλ]{.corr} τι με διωκεις[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} ειπεν τε προς με εγω ειμι [ιησους]{.greek-abbr} ο [ναζωραιος]{.greek-omitted} [ναζοραιος]{.greek-added} ον συ διωκεις[22:8]{.aside}

οι δε συν εμοι οντες το μεν φως εθεασαντο και [εμφοβοι]{.greek-omitted} [ενφοβοι]{.greek-added} εγενοντο την δε φωνην ουκ ηκουσαν του λαλουντος μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν προς με αναστας πορευου εις δαμασκον κακει σοι λαληθησεται περι παντων ων τετακται σοι ποιησαι[22:10]{.aside}

ως δε ουκ ενεβλεπον απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι ηλθον εις δαμασκον[22:11]{.aside}

ανανιας δε τις ανηρ ευσεβης κατα τον νομον μαρτυρουμενος [τε]{.greek-added} υπο παντων των κατοικουντων ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας ειπεν μοι σαουλ αδελφε αναβλεψον καγω αυτη τη ωρα ανεβλεψα εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [προεχειρισατο]{.greek-omitted} [προεχειρησατο]{.greek-added} σε γνωναι το θελημα αυτου και ιδειν τον δικαιον και ακουσαι φωνην εκ του στοματος αυτου[22:14]{.aside}

οτι εση μαρτυς αυτω προς παντας [ανθρωπους]{.greek-abbr} ων εωρακας και ηκουσας[22:15]{.aside}

και νυν τι μελλεις αναστας βαπτισαι και απολουσαι τας αμαρτιας σου επικαλεσαμενος το ονομα του [κυριου]{.greek-abbr}[22:16]{.aside}

εγενετο δε μοι υποστρεψαντι εις [ιερουσαλημ]{.greek-abbr} και προσευχομενου μου εν τω ιερω γενεσθαι με εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον και εξελθε εν ταχει εξ [ιερουσαλημ]{.greek-omitted} [[ιλημ]{.greek-abbr}]{.greek-added} διοτι ου παραδεξονται σου την μαρτυριαν περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω [ημην]{.greek-omitted} [ημιν]{.greek-added} φυλακιζων και δερων κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε [εξεχειτο]{.greek-omitted} [εξεχυνετο]{.greek-added} το αιμα στεφανου του μαρτυρος σου και αυτος [ημην]{.greek-omitted} [ημιν]{.greek-added} εφεστως και συνευδοκων τη αναιρ[ε]{.unclear}[σ]{.greek-supplied}ει αυτου φυλασσων [τε]{.greek-added} τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και ειπεν προς με πορευου οτι εγω εις εθνη μακραν εξαποστελω σε[22:21]{.aside}

ηκουον δε αυτου αχρι τουτου του λογου και επηραν την φωνην αυτων λεγοντες αιρε απο της γης τον τοιουτον ου γαρ καθηκεν αυτον ζην[22:22]{.aside}

κραζοντων δε αυτων και ριπτουντων τα ιματια και [κονιορτον]{.greek-omitted} [κονιορτων]{.greek-added} βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν αυτον ο χιλιαρχος [αγεσθαι]{.greek-omitted} [εισαγεσθαι]{.greek-added} εις την παρεμβολην ειπων μαστιξιν ανεταζ[ε]{.unclear}[σ]{.greek-supplied}θαι αυτον ινα επιγνω δι ην αιτιαν ουτως επεφωνουν αυτω[22:24]{.aside}

ως δε προετεινεν αυτον τοις ιμασιν ειπεν προς τον εστωτα εκατονταρχον ο παυλος ει [ανθρωπον]{.greek-abbr} ρωμαιον και [ακατακριτον]{.greek-omitted} [ακατακρητον]{.greek-added} εξεστιν [υμιν]{.greek-omitted} [υμας]{.greek-added} [μαστιζειν]{.greek-omitted} [μαστιξιν]{.greek-added}[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων απηγγειλεν τω χιλιαρχω λεγων ορα τι μελλεις ποιειν ο γαρ [ανθρωπος]{.greek-abbr} ουτος ρωμαιος εστιν[22:26]{.aside}

προσελθων δε ο χιλιαρχος ειπεν αυτω λεγε μοι ει συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκριθη τε ο χιλιαρχος εγω πολλου κεφαλαιου την πολιτειαν ταυτην εκτησαμην ο δε παυλος εφη εγω δε και γεγεννημαι[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες αυτον ανεταζειν και ο χιλιαρχος δε εφοβηθη επιγνους οτι ρωμαιος εστιν και οτι ην αυτον [δεδεκως]{.greek-omitted} [δεδοκως]{.greek-added}[22:29]{.aside}

τη δε επαυριον βουλομενος γνωναι το ασφαλες το τι κατηγορειται παρα των ιουδαιων ελυσεν αυτον απο των δεσμων και εκελευσεν ελθειν τους αρχιερεις και ολον το συνεδριον αυτων και καταγαγων τον παυλον εστησεν εις αυτους[22:30]{.aside}

### Chapter 23

[ατενισας]{.greek-omitted} [ατενησας]{.greek-added} δε ο παυλος τω συνεδριω [ει]{.unclear}πεν ανδρες αδελφοι εγω [παση]{.greek-omitted} [πασει]{.greek-added} [συνειδησει]{.greek-omitted} [συνηδησει]{.greek-added} αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι ταυτης της ημερας[23:1]{.aside}

ο δε αρχιερευς ανανιας επεταξεν τοις παρεστωσιν αυτω τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον ειπεν τυπτειν σε μελλει ο [θεος]{.greek-abbr} τ[ο]{.unclear}ιχε κεκονιαμενε και συ καθη κρινων με κατα τον νομον και παρανομων κελευεις με τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες ειπον τον αρχιερεα του [θεου]{.greek-abbr} [λοιδορεις]{.greek-omitted} [λυδωρεις]{.greek-added}[23:4]{.aside}

εφη τε ο παυλος ουκ ηδειν αδελφοι οτι εστιν αρχιερευς γεγραπται γαρ αρχοντα του λαου σου ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος εστιν [σαδοδουκαιων]{.greek-added} [σαδδουκαιων]{.corr} το δε ετερον φαρισαιων εκραξεν εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμι [και]{.greek-added} υιος φαρισαιου περι ελπιδος και αναστασεως νεκρων εγω κρινομαι[23:6]{.aside}

τουτο δε αυτου λαλησαντος εγενετο στασις των φαρισαιων και [των]{.greek-added} [σαδδουκαιων]{.greek-added} [και]{.greek-added} [εσχισθη]{.greek-omitted} [εσχησθη]{.greek-added} το πληθος[23:7]{.aside}

[σαδουκαιοι]{.greek-added} [σαδδουκαιοι]{.corr} μεν γαρ λεγουσιν μη ειναι αναστασιν μηδε αγγελον μητε [πνευμα]{.greek-abbr} φαρισαιοι δε ομολογουσιν τα αμφοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και ανασταντες [οι]{.greek-omitted} [τινες]{.greek-added} γραμματεις του μερους των φαρισαιων διεμαχοντο λεγοντες ουδεν κακον ευρισκομεν εν τω [ανθρωπω]{.greek-abbr} τουτω ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω η αγγελος μη θεομαχωμεν[23:9]{.aside}

πολλης δε γενομενης στασεως [ευλαβηθεις]{.greek-omitted} [φοβηθεις]{.greek-added} ο χιλιαρχος μη διασπασθη ο παυλος υπ αυτων εκελευσεν το στρατευμα καταβηναι και αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση [νυκτι]{.greek-omitted} [νυκτη]{.greek-added} επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν θαρσει παυλε ως γαρ διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} ουτως σε δει και εις ρωμην μαρτυρησαι[23:11]{.aside}

γενομενης δε ημερας ποιησαντες τινες των ιουδαιων συστροφην ανεθεματισαν εαυτους λεγοντες μητε φαγειν μητε πιειν εως ου [αποκτεινωσιν]{.greek-omitted} [αποκτηνωσιν]{.greek-added} τον παυλον[23:12]{.aside}

ησαν δε πλειους τεσσαρακοντα οι ταυτην την [συνωμοσιαν]{.greek-omitted} [συνομοσιαν]{.greek-added} πεποιηκοτες[23:13]{.aside}

οιτινες προσελθοντες τοις αρχιερευσιν και τοις πρεσβυτεροις ειπον αναθεματι ανεθεματισαμεν εαυτους μηδενος γευσασθαι εως ου [αποκτεινωμεν]{.greek-omitted} [αποκτηνομεν]{.greek-added} τον παυλον[23:14]{.aside}

νυν ουν υμεις [εμφανισατε]{.greek-omitted} [εμφανησατε]{.greek-added} τω χιλιαρχω συν τω συνεδριω οπως αυριον [αυτον]{.greek-omitted} [αυτων]{.greek-added} καταγαγη προς [υμας]{.greek-omitted} [ημας]{.greek-added} ως μελλοντας διαγινωσκειν ακριβεστερον τα περι αυτου ημεις δε προ του εγγισαι αυτον ετοιμοι εσμεν του ανελειν αυτον[23:15]{.aside}

ακουσας δε ο [υιος]{.greek-abbr} της αδελφης παυλου το ενεδρον παραγενομενος και εισελθων εις την παρεμβολην απηγγειλεν τω παυλω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων εφη τον νεανιαν τουτον απαγαγε προς τον χιλιαρχον εχει γαρ τι [απαγγειλαι]{.greek-omitted} [αναγγειλαι]{.greek-added} αυτω[23:17]{.aside}

ο μεν ουν παραλαβων αυτον ηγαγεν προς τον χιλιαρχον και φησιν ο δεσμιος παυλος προσκαλεσαμενος με ηρωτησεν τουτον τον νεανιαν αγαγειν προς σε εχοντα τι λαλησαι σοι[23:18]{.aside}

επιλαβομενος δε της χειρος αυτου ο χιλιαρχος και αναχωρησας κατ ιδιαν [επυνθανετο]{.greek-omitted} [εποινθανετο]{.greek-added} τι εστιν ο εχεις απαγγειλαι μοι[23:19]{.aside}

ειπεν δε οτι οι ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον εις το συνεδριον καταγαγης τον παυλον ως μελλοντα τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ ουν μη [πεισθης]{.greek-omitted} [πισθης]{.greek-added} αυτοις ενεδρευουσιν γαρ [αυτον]{.greek-omitted} εξ αυτων ανδρες πλειους τεσσαρακοντα οιτινες [ανεθεματισαν]{.greek-omitted} [ανεθεματησαν]{.greek-added} εαυτους μητε φαγειν μητε πιειν εως ου ανελωσιν αυτον και νυν ετοιμοι εισιν προσδεχομενοι την απο σου επαγγελιαν[23:21]{.aside}

ο μεν ουν χιλιαρχος απελυσεν τον νεανιαν παραγγειλας μηδενι εκλαλησαι οτι ταυτα [ενεφανισας]{.greek-omitted} [ενεφανησας]{.greek-added} προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους οπως πορευθωσιν εως καισαρειας και ιππεις εβδομηκοντα και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

[κτηνη]{.greek-omitted} [κτινη]{.greek-added} τε παραστησαι ινα [οπως]{.greek-added} επιβιβασαντες τον παυλον [διασωσωσιν]{.greek-omitted} [διασωσοσιν]{.greek-added} προς [φηλικα]{.greek-omitted} [φιλικα]{.greek-added} τον ηγεμονα[23:24]{.aside}

γραψας επιστολην περιεχουσαν τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω ηγεμονι [φηλικι]{.greek-omitted} [φιλικι]{.greek-added} χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο των ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι εξειλομην αυτον μαθων οτι ρωμαιος εστιν[23:27]{.aside}

βουλομενος δε γνωναι την αιτιαν δι ην ενεκαλουν αυτω κατηγαγον αυτον εις το συνεδριον αυτων[23:28]{.aside}

ον ευρον εγκαλουμενον περι [ζητηματων]{.greek-omitted} [ζητιματων]{.greek-added} του νομου αυτων [μηδεν]{.greek-omitted} [μηδενα]{.greek-added} [δε]{.greek-added} αξιον θανατου η δεσμων εγκλημα εχοντα[23:29]{.aside}

[μηνυθεισης]{.greek-omitted} [μηνοιθησης]{.greek-added} δε μοι επιβουλης εις τον ανδρα μελλειν εσεσθαι υπο των ιουδαιων εξαυτης επεμψα προς σε παραγγειλας και τοις κατηγοροις λεγειν τα προς αυτον επι σου ερρωσο[23:30]{.aside}

οι μεν ουν στρατιωται κατα το διατεταγμενον αυτοις αναλαβοντες τον παυλον ηγαγον δια της νυκτος εις την αντιπατριδα[23:31]{.aside}

τη δε επαυριον εασαντες τους ιππεις πορευεσθαι συν αυτω υπεστρεψαν εις την παρεμβολην[23:32]{.aside}

οιτινες εισελθοντες εις την καισαρειαν και αναδοντες την επιστολην τω [ηγεμονι]{.greek-omitted} [ηγεμονη]{.greek-added} παρεστησαν και τον παυλον αυτω[23:33]{.aside}

αναγνους δε ο ηγεμων και επερωτησας εκ ποιας επαρχιας εστιν και πυθομενος οτι απο κιλικιας[23:34]{.aside}

[διακουσομαι]{.greek-omitted} [διακουσωμαι]{.greek-added} σου εφη οταν και οι κατηγοροι σου παραγενωνται εκελευσεν τε αυτον εν τω [πραιτωριω]{.greek-omitted} [πρετωριω]{.greek-added} ηρωδου φυλασσεσθαι[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη ο αρχιερευς ανανιας μετα των πρεσβυτερων και ρητορος τερτυλλου τινος οιτινες [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} τω [ηγεμονι]{.greek-omitted} [ηγεμονη]{.greek-added} κατα του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο κατηγορειν ο [τερτυλλος]{.greek-omitted} [τερτυλος]{.greek-added} λεγων πολλης ειρηνης τυγχανοντες δια σου και κατορθωματων γινομενων τω [εθνει]{.greek-omitted} [εθνη]{.greek-added} τουτω δια της σης προνοιας[24:2]{.aside}

[παντη]{.greek-omitted} [παντι]{.greek-added} τε και πανταχου αποδεχομεθα [κρατιστε]{.greek-omitted} [κρατηστε]{.greek-added} [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} μετα πασης ευχαριστιας[24:3]{.aside}

ινα δε μη επι πλειον σε εγκοπτω παρακαλω ακουσαι σε ημων συντομως τη ση επιεικεια[24:4]{.aside}

ευροντες γαρ τον ανδρα τουτον [λοιμον]{.greek-omitted} [λυμον]{.greek-added} και κινουντα στασιν πασιν τοις ιουδαιοις τοις κατα την οικουμενην [πρωτοστατην]{.greek-omitted} [προτοστατην]{.greek-added} τε της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον επειρασεν βεβηλωσαι ον και εκρατησαμεν [και]{.greek-added} [κατα]{.greek-added} [τον]{.greek-added} [ημετερον]{.greek-added} [νομον]{.greek-added} [ηθελησαμεν]{.greek-added} [κριναι]{.greek-added}[24:6]{.aside}

[παρελθων]{.greek-added} [δε]{.greek-added} [ο]{.greek-added} [λυσιας]{.greek-added} [ο]{.greek-added} [χιλιαρχος]{.greek-added} [μετα]{.greek-added} [πολλης]{.greek-added} [βιας]{.greek-added} [εκ]{.greek-added} [των]{.greek-added} [χειρων]{.greek-added} [ημων]{.greek-added} [απηγαγεν]{.greek-added}[24:7]{.aside}

[κελευσας]{.greek-added} [τους]{.greek-added} [κατηγορους]{.greek-added} [αυτου]{.greek-added} [ερχεσθαι]{.greek-added} [επι]{.greek-added} [σε]{.greek-added} παρ ου δυνηση αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

[συνεπεθεντο]{.greek-omitted} [συνεπειθοντο]{.greek-added} δε και [οι]{.greek-omitted} ιουδαιοι φασκοντες ταυτα ουτως εχειν[24:9]{.aside}

απεκριθη δε ο παυλος νευσαντος αυτω του ηγεμονος λεγειν εκ πολλων ετων οντα σε κριτην [δικαιον]{.greek-added} τω [εθνει]{.greek-omitted} [εθνη]{.greek-added} τουτω επισταμενος [ευθυμοτερον]{.greek-omitted} [ευθυμωτερον]{.greek-added} τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} οτι ου πλειους εισιν μοι ημεραι δεκαδυο αφ ης [ανεβην]{.greek-omitted} [ανεβη]{.greek-added} προσκυνησων εν [ιερουσαλημ]{.greek-abbr}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η επισυστασιν ποιουντα οχλου ουτε εν ταις συναγωγαις ουτε κατα την [πολιν]{.greek-omitted} [πολην]{.greek-added}[24:12]{.aside}

ουτε παραστησαι με δυνανται περι ων νυν κατηγορουσιν μου[24:13]{.aside}

ομολογω δε τουτο σοι οτι κατα την οδον ην λεγουσιν αιρεσιν ουτως λατρευω τω πατρωω [θεω]{.greek-abbr} πιστευων πασιν τοις κατα τον νομον και τοις προφηταις γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι προσδεχονται αναστασιν μελλειν εσεσθαι νεκρων δικαιων τε και αδικων[24:15]{.aside}

εν τουτω δε αυτος ασκω απροσκοπον συνειδησιν εχων προς τον [θεον]{.greek-abbr} και τους ανθρωπους δια παντος[24:16]{.aside}

δι ετων δε πλειονων παρεγενομην ελεημοσυνας ποιησων εις το εθνος μου και προσφορας[24:17]{.aside}

εν οις ευρον με [ηγνισμενον]{.greek-omitted} [ηγνησμενον]{.greek-added} εν τω ιερω ου [μετα]{.greek-omitted} [ματα]{.greek-added} οχλου ουδε μετα θορυβου [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιοι]{.greek-added} ους δει επι σου παρειναι και κατηγορειν ει τι εχοιεν προς με[24:19]{.aside}

η αυτοι ουτοι ειπατωσαν τι ευρον εν εμοι αδικημα σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας ταυτης φωνης ης εκραξα εστως εν αυτοις οτι περι αναστασεως νεκρων εγω κρινομαι σημερον υφ υμων[24:21]{.aside}

ακουσας δε ταυτα ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [ανεβαλετο]{.greek-omitted} [ανελαβετο]{.greek-added} αυτους ακριβεστερον ειδως τα περι της οδου ειπων οταν λυσιας ο χιλιαρχος καταβη διαγνωσομαι τα καθ υμας[24:22]{.aside}

διαταξαμενος τε τω εκατονταρχη τηρεισθαι τον παυλον εχειν τε ανεσιν και μηδενα [κωλυειν]{.greek-omitted} [κολυειν]{.greek-added} των ιδιων αυτου υπηρετειν η προσερχεσθαι αυτω[24:23]{.aside}

μετα δε ημερας τινας [παραγενομενος]{.greek-omitted} [παραγεναμενος]{.greek-added} ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} συν δρουσιλλη τη γυναικι ουση ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου περι της εις [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του μελλοντος εσεσθαι εμφοβος γενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} απεκριθη το νυν εχον πορευου καιρον δε μεταλαβων μετακαλεσομαι σε[24:25]{.aside}

αμα και ελπιζων οτι χρηματα δοθησεται αυτω υπο του παυλου οπως [λυση]{.greek-omitted} [λυσει]{.greek-added} αυτον διο και πυκνοτερον αυτον μεταπεμπομενος ωμιλει αυτω[24:26]{.aside}

διετιας δε [πληρωθεισης]{.greek-omitted} [πληρωθησης]{.greek-added} ελαβεν διαδοχον ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} πορκιον φηστον θελων τε χαριτας καταθεσθαι τοις ιουδαιοις ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [κατελιπεν]{.greek-omitted} [κατελειπεν]{.greek-added} τον παυλον δεδεμενον[24:27]{.aside}

### Chapter 25

φηστος ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη εις [ιεροσολυμα]{.greek-omitted} [ιεροσο]{.greek-added} [λυμα]{.greek-added} απο καισαρειας[25:1]{.aside}

[ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} δε αυτω ο αρχιερευς και οι πρωτοι των ιουδαιων κατα του παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται αυτον εις [ιερουσαλημ]{.greek-abbr} ενεδραν ποιουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν [ουν]{.greek-omitted} [ου]{.greek-added} φηστος απεκριθη τηρεισθαι τον παυλον εν καισαρεια εαυτον δε μελλειν εν ταχει εκπορευεσθαι[25:4]{.aside}

οι [ουν]{.greek-omitted} [ου]{.greek-added} δυνατοι εν υμιν φησιν συγκαταβαντες ει τι εστιν εν τω ανδρι τουτω κατηγορειτωσαν αυτου[25:5]{.aside}

διατριψας δε εν αυτοις ημερας πλειους η δεκα καταβας εις καισαρειαν τη επαυριον [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εκελευσεν τον παυλον αχθηναι[25:6]{.aside}

παραγενομ[ε]{.greek-supplied}νου δε αυτου περιεστησαν [αυτω]{.greek-added} οι απο ιεροσολυμων καταβεβηκοτες ιουδαιοι πολλα και [βαρεα]{.greek-omitted} [βαραια]{.greek-added} αιτιωματα φεροντες κατα του παυλου α ουκ ισχυον αποδειξαι[25:7]{.aside}

[του]{.greek-added} [δε]{.greek-added} [παυλου]{.greek-added} απολογουμενου [αυτου]{.greek-omitted} οτι ουτε εις τον νομον των ιουδαιων ουτε εις το ιερον ουτε εις καισαρα τι ημαρτον[25:8]{.aside}

ο φηστος δε τοις ιουδαιοις θελων χαριν καταθεσθαι αποκριθεις τω παυλω ειπεν θελεις εις ιεροσολυμα αναβας εκει περι τουτων κρινεσθαι [επ]{.greek-omitted} [επι]{.greek-added} εμου[25:9]{.aside}

ειπεν δε ο παυλος επι του βηματος καισαρος εστως ειμι ου με δει κρινεσθαι ιουδαιους ουδεν ηδικησα ως και συ [καλλιον]{.greek-omitted} [καλαιον]{.greek-added} επιγινωσκεις[25:10]{.aside}

ει μεν γαρ αδικω και αξιον θανατου πεπραχα τι ου παραιτουμαι [το]{.greek-omitted} [του]{.greek-added} αποθανειν ει δε ουδεν εστιν ων ουτοι κατηγορουσιν [μου]{.greek-omitted} [μοι]{.greek-added} ουδεις με δυναται αυτοις χαρισασθαι καισαρα επικαλουμαι[25:11]{.aside}

τοτε ο φηστος συλλαλησας μετα του συμβουλιου απεκριθη καισαρα επικεκλησαι επι καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τινων αγριππας ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν ασπασαμενοι τον φηστον[25:13]{.aside}

ως δε πλειους ημερας διετριβεν εκει ο φηστος τω βασιλει ανεθετο τα κατα τον παυλον λεγων ανηρ τις εστιν [καταλελειμμενος]{.greek-omitted} [καταλελειμενος]{.greek-added} υπο φηλικος δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις ιεροσολυμα [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} εις [απωλειαν]{.greek-omitted} [απολειαν]{.greek-added} πριν η ο κατηγορουμενος κατα προσωπον εχοι τους κατηγορους τοπον τε απολογιας λαβοι περι του εγκληματος[25:16]{.aside}

συνελθοντων ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη εξης [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν επεφερον ων υπενοουν εγω [πονηρα]{.greek-added}[25:18]{.aside}

[ζητηματα]{.greek-omitted} [ζητειματα]{.greek-added} δε τινα περι της ιδιας δεισιδαιμονιας ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τεθνηκοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω την περι [τουτ[ω]{.unclear}ν]{.greek-added} [τουτου]{.greek-omitted} [[τουτον]{.corr}]{.greek-added} [ζητησιν]{.greek-omitted} [ζητεισιν]{.greek-added} ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-abbr} κακει κρινεσθαι περι τουτων[25:20]{.aside}

του δε παυλου επικαλεσαμενου τηρηθηναι αυτον εις την του σεβαστου διαγνωσιν εκελευσα τηρεισθαι αυτον εως ου πεμψω αυτον προς καισαρα[25:21]{.aside}

αγριππας δε προς τον φηστον εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της βερνικης μετα πολλης φαντασιας και εισελθοντων εις το ακροατηριον συν τε τοις χιλιαρχοις και ανδρασιν τοις κατ εξοχην ουσιν της πολεως και κελευσαντος του φηστου ηχθη ο παυλος[25:23]{.aside}

και φησιν ο φηστος αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες [θεωρειτε]{.greek-omitted} [θεορειτε]{.greek-added} τουτον περι ου παν το πληθος των ιουδαιων ενετυχον μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν ζην αυτον μηκετι[25:24]{.aside}

εγω δε καταλαβομενος μηδεν αξιον θανατου αυτον πεπραχεναι και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα πεμπειν αυτον[25:25]{.aside}

περι ου ασφαλες τι γραψαι τω κυριω ουκ εχω διο προηγαγον αυτον εφ υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως γενομενης [σχω]{.greek-omitted} [εχω]{.greek-added} τι γραψαι[25:26]{.aside}

αλογον γαρ μοι δοκει πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη επιτρεπεται σοι υπερ σεαυτου λεγειν τοτε ο παυλος [απελογειτο]{.greek-omitted} [απολογειτε]{.greek-added} εκτεινας την χειρα[26:1]{.aside}

περι παντων ων εγκαλουμαι υπο ιουδαιων βασιλευ αγριππα ηγημαι [εμαυτον]{.greek-omitted} [εαυτον]{.greek-added} μακαριον επι σου [μελλων]{.greek-omitted} [μελλον]{.greek-added} [απολογεισθαι]{.greek-omitted} [απολογησθαι]{.greek-added} σημερον[26:2]{.aside}

μαλιστα γνωστην [σε]{.greek-added} οντα [σε]{.greek-omitted} [ιδως]{.greek-added} παντων των κατα ιουδαιους ηθων τε και ζητηματων διο δεομαι σου μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ [νεοτητος]{.greek-omitted} [νεωτητος]{.greek-added} την απ αρχης γενομενην εν τω [εθνει]{.greek-omitted} [εθνη]{.greek-added} μου εν ιεροσολυμοις ισασιν παντες οι ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν θελωσιν μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας [θρησκειας]{.greek-omitted} [θρησκιας]{.greek-added} εζησα φαρισαιος[26:5]{.aside}

και νυν επ ελπιδι της προς τους [πατερας]{.greek-abbr} επαγγελιας γενομενης υπο του [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν εκτενεια νυκτα και [ημεραν]{.greek-omitted} [ημερα]{.greek-added} λατρευον ελπιζει καταντησαι περι ης ελπιδος εγκαλουμαι βασιλευ αγριππα υπο ιουδαιων[26:7]{.aside}

τι απιστον κρινεται παρ υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησα εν ιεροσολυμοις και πολλους των αγιων εγω φυλακαις [κατεκλεισα]{.greek-omitted} [κατεκλησα]{.greek-added} την παρα των αρχιερεων εξουσιαν λαβων αναιρουμενων τε αυτων κατηνεγκα ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις [τιμωρων]{.greek-omitted} [τιμωρον]{.greek-added} αυτους ηναγκαζον βλασφημειν περισσως τε εμμαινομενος αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις και πορευομενος εις την δαμασκον μετ εξουσιας και επιτροπης της παρα των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον [ειδον]{.greek-omitted} [ιδον]{.greek-added} βασιλευ ουρανοθεν υπερ την [λαμπροτητα]{.greek-omitted} [λαμπρωτητα]{.greek-added} του ηλιου περιλαμψαν με φως και τους συν εμοι πορευομενους[26:13]{.aside}

παντων δε καταπεσοντων ημων εις την γην ηκουσα φωνην λαλουσαν προς με και λεγουσαν τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε ειπον τις ει [κυριε]{.greek-abbr} ο δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [ιησους]{.greek-abbr} [ο]{.greek-added} [ναζωραιος]{.greek-added} ον συ διωκεις[26:15]{.aside}

αλλα αναστηθι και στηθι επι τους ποδας σου εις τουτο γαρ ωφθην σοι [προχειρισασθαι]{.greek-omitted} [προχειρησασθαι]{.greek-added} σε υπηρετην και μαρτυρα ων τε ειδες [με]{.greek-added} ων τε [οφθησομαι]{.greek-omitted} [ωφθησομαι]{.greek-added} σοι[26:16]{.aside}

εξαιρουμενο[ς]{.unclear} σε εκ του λαου και [εκ]{.greek-added} των εθνων εις ους εγω [αποστελω]{.greek-added} σε [αποστελλω]{.greek-omitted}[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του υποστρεψαι απο σκοτους εις φως και της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην [απειθης]{.greek-omitted} [απηθεις]{.greek-added} τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον και [εν]{.greek-added} ιεροσολυμοις εις πασαν τε την χωραν της ιουδαιας και τοις εθνεσιν απαγγελλων μετανοειν και επιστρεφειν επι τον [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων [με]{.greek-added} οι ιουδ[α]{.unclear}ιοι [με]{.greek-omitted} συλλαβομενοι εν τω ιερω επειρωντο δι[α]{.unclear}χειρισασθαι[26:21]{.aside}

επικουριας ουν τυχων της παρα του [θεου]{.greek-abbr} αχρι της ημερας ταυτης εστηκα μαρτυρομενος μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και μωυσης[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως [μελλει]{.greek-omitted} [μελλειν]{.greek-added} καταγγελλειν τω λαω και τοις εθνεσιν[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο φηστος μεγαλη τη φωνη εφη μαινη παυλε τα πολλα σε γραμματα εις μανιαν [περιτρεπει]{.greek-omitted} [προτρεπη]{.greek-added}[26:24]{.aside}

ο δε [παυλος]{.greek-added} ου μαινομαι φησιν κρατιστε φηστε αλλα αληθειας και [σωφροσυνης]{.greek-omitted} [σοφροσυνης]{.greek-added} ρηματα αποφθεγγομαι[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον και παρρησιαζομενος λαλω λανθανειν γαρ αυτον τι τουτων ου πειθομαι ουδεν ου γαρ εν [γωνια]{.greek-omitted} [γονια]{.greek-added} πεπραγμενον τουτο[26:26]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

ο δε αγριππα[ς]{.unclear} προς τον παυλον εφη εν ολιγω με πειθεις χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος ειπεν [ευξαιμην]{.greek-omitted} [ευξαμην]{.greek-added} αν τω [θεω]{.greek-abbr} και εν ολιγω και εν πολλω ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος καγω ειμι παρεκτος των δεσμων [μου]{.greek-added} τουτων[26:29]{.aside}

και ταυτα ειποντος αυτου ανεστη ο βασιλευς [και]{.unclear} ο ηγεμων η τε βερνικη και οι συγκαθημενοι αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν θανατου αξιον η δεσμων πρασσει ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω φηστω εφη απολελυσθαι [εδυνατο]{.greek-omitted} [ειδυνατον]{.greek-added} ο [ανθρωπος]{.greek-abbr} ουτος ει μη [επεκεκλητο]{.greek-omitted} [επικεκλητο]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την ιταλιαν παρεδιδουν τον τε παυλον και τινας ετερους δεσμωτας εκατονταρχη ονοματι ιουλιω [σπειρης]{.greek-omitted} [σπηρης]{.greek-added} σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω [αδραμυττηνω]{.greek-omitted} [αδραμυντινω]{.greek-added} μελλοντες πλειν τους κατα την ασιαν τοπους ανηχθημεν [οντος]{.greek-omitted} [οντως]{.greek-added} συν ημιν αρισταρχου μακεδονος θεσσαλονικεως[27:2]{.aside}

τη τε ετερα κατηχθημεν εις σιδωνα φιλανθρωπως τε ο ιουλιος τω παυλω χρησαμενος επετρεψεν προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες κατηλθομεν εις μυρα της λυκιας[27:5]{.aside}

κακει [ευρων]{.greek-omitted} [ευρον]{.greek-added} ο εκατονταρχ[ο]{.unclear}ς πλοιον αλεξανδρινον πλεον εις την [ιταλιαν]{.greek-omitted} [αταλιαν]{.greek-added} [ενεβιβασεν]{.greek-omitted} [ανεβηβασεν]{.greek-added} ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις βραδυπλοουντες και μολις γενομενοι κατα την κνιδον μη προσεωντος ημας του ανεμου [υπε]{.greek-supplied}πλευσαμεν την [κρητην]{.greek-omitted} [κριτην]{.greek-added} κατα σαλμωνην[27:7]{.aside}

μολις τε παραλεγομενοι αυτη[ν]{.unclear} ηλθομεν εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις λασαια[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος ηδη επισφαλους του πλοος δια το και την νηστειαν ηδη [παρεληλυθεναι]{.greek-omitted} [παραλελυθεναι]{.greek-added} [παρηνει]{.greek-omitted} [παρηνη]{.greek-added} ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των ψυχων ημων μελλειν εσεσθαι τον πλουν[27:10]{.aside}

ο δε [εκατονταρχης]{.greek-omitted} [εκατονταρχος]{.greek-added} τω κυβερνητη και τω ναυκληρω επειθετο μαλλον η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι πλειους εθεντο βουλην αναχθηναι κακειθεν [ει]{.greek-omitted} [η]{.greek-added} πως δυναιντο καταντησαντες εις [φοινικα]{.greek-omitted} [φυνικα]{.greek-added} παραχειμασαι λιμενα της [κρητης]{.greek-omitted} [κριτης]{.greek-added} [βλεποντα]{.greek-omitted} [βλεπον]{.greek-added} κατα λιβα και κατα χωρον[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως [κεκρατηκεναι]{.greek-omitted} [κεκρατικεναι]{.greek-added} αραντες ασσον παρελεγοντο την [κρητην]{.greek-omitted} [κριτην]{.greek-added}[27:13]{.aside}

μετ ου πολυ δε εβαλεν κατ αυτης ανεμος τυφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι υποδραμοντες καλουμενον κλαυδην μολις ισχυσαμεν [περικρατεις]{.greek-omitted} [περικρατης]{.greek-added} γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες βοηθειαις εχρωντο [υποζωννυντες]{.greek-omitted} [υποζοννυντες]{.greek-added} το πλοιον φοβουμενοι τε μη εις την συρτην εκπεσωσιν χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως δε χειμα[ζ]{.unclear}ομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη αυτοχειρες την σκευην του πλοιου ερριψαμεν[27:19]{.aside}

μητε δε ηλιου μητε αστρων [επιφαινοντων]{.greek-omitted} [επιφενοντων]{.greek-added} επι πλειονας ημερας [χειμωνος]{.greek-omitted} [χειμονος]{.greek-added} τε ουκ ολιγου επικειμενου λοιπον [περιηρειτο]{.greek-omitted} [περιειρητο]{.greek-added} πασα ελπις του σωζεσθαι ημας[27:20]{.aside}

πολλης δε [ασιτιας]{.greek-omitted} [ασητειας]{.greek-added} υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη αναγεσθαι απο της [κρητης]{.greek-omitted} [κριτης]{.greek-added} κερδησαι τε την [υβριν]{.greek-omitted} [υβρην]{.greek-added} ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης [ουδεμια]{.greek-omitted} [ουδεμιας]{.greek-added} εσται εξ υμων [πλην]{.greek-omitted} [πλειν]{.greek-added} του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι αγγελος του [θεου]{.greek-abbr} ου ειμι ω και λατρευω[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο [ευθυμειτε]{.greek-omitted} [ευθυμητε]{.greek-added} ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις [νησον]{.greek-omitted} [νησσον]{.greek-added} δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε [τεσσαρεσκαιδεκατη]{.greek-omitted} [τεσσαρεσκεδεκατη]{.greek-added} νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα μεσον της νυκτος υπενοουν οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας εικοσι βραχυ δε διαστησαντες και παλιν [βολισαντες]{.greek-omitted} [βολησαντες]{.greek-added} ευρον οργυιας δεκαπεντε[27:28]{.aside}

φοβουμενοι τε [μη]{.greek-added} [μηπως]{.greek-omitted} [πως]{.greek-added} [εκπεσωσιν]{.greek-added} εις τραχεις τοπους [εκπεσωμεν]{.greek-omitted} εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ [πρωρας]{.greek-omitted} [προρης]{.greek-added} [αγκυρας]{.greek-added} μελλοντων [αγκυρας]{.greek-omitted} [εκτεινειν]{.greek-omitted} [εκτινειν]{.greek-added}[27:30]{.aside}

ειπεν ο παυλος [τω]{.unclear} εκατονταρχη και τοις στρατιωταις εαν μη ουτοι [μεινωσιν]{.greek-omitted} [μηνωσιν]{.greek-added} εν τω πλοιω υμεις σωθηναι ου δυνασθε[27:31]{.aside}

τοτε [απεκοψαν]{.greek-added} οι στρατιωται [απεκοψαν]{.greek-omitted} τα σχοινια της σκαφης και ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου [ημερα]{.greek-added} ημελλεν [ημερα]{.greek-omitted} γινεσθαι παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην σημερον ημεραν προσδοκωντες [ασιτοι]{.greek-omitted} [ασειτοι]{.greek-added} διατελειτε [μηδεν]{.greek-omitted} [μηθενος]{.greek-added} προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας [προσλαβειν]{.greek-omitted} [μεταλαβειν]{.greek-added} τροφης τουτο γαρ προς της υμετερας σωτηριας υπαρχει ουδενος γαρ υμων θριξ [εκ]{.greek-omitted} [απο]{.greek-added} της κεφαλης [πεσειται]{.greek-omitted} [απολειται]{.greek-added}[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον [ευχαριστησεν]{.greek-omitted} [ευχαριστησας]{.greek-added} τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο [εσθιειν]{.greek-omitted} [εσθειην]{.greek-added}[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

[ημεν]{.greek-omitted} [ημεθα]{.greek-added} δε [αι]{.greek-added} [πασαι]{.greek-added} [ψυχαι]{.greek-added} εν τω πλοιω [αι]{.greek-omitted} [πασαι]{.greek-omitted} [ψυχαι]{.greek-omitted} διακοσιαι εβδομηκοντα εξ[27:37]{.aside}

κορεσθεντες δε [της]{.greek-omitted} τροφης εκουφιζον το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον [εβουλευσαντο]{.greek-omitted} [εβουλοντο]{.greek-added} ει δυνατον εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των πηδαλιων και επαραντες τον [αρτεμονα]{.greek-omitted} [αρτεμωνα]{.greek-added} τη πνεουση κατειχον εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον επωκειλαν την ναυν και η μεν πρωρα [ερεισασα]{.greek-omitted} [ερησασα]{.greek-added} εμεινεν ασαλευτος η δε πρυμνα ελυετο υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους [δεσμωτας]{.greek-omitted} [δεσμιους]{.greek-added} [αποκτεινωσιν]{.greek-omitted} [αποκτινωσιν]{.greek-added} μη τις εκκολυμβησας [διαφυγη]{.greek-omitted} [διαφυγει]{.greek-added}[27:42]{.aside}

ο δε [εκατονταρχος]{.greek-omitted} [εκατονταρχης]{.greek-added} βουλομενος [διασωσαι]{.greek-omitted} τον παυλον [διασωσαι]{.greek-added} [εκωλυσεν]{.greek-omitted} [εκολυσεν]{.greek-added} αυτους του [βου]{.greek-added} [βουληματος]{.greek-omitted} [εκελευσεν]{.greek-omitted} [τε]{.greek-omitted} [τους]{.greek-omitted} [δυναμενους]{.greek-omitted} [κολυμβαν]{.greek-omitted} [απορριψαντας]{.greek-omitted} [πρωτους]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [εξιεναι]{.greek-omitted}[27:43]{.aside}

