---
title: "Collation of Byz^RP^ vs 31828 (1828)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1828 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31828).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1828                                   	| λογος                              	|
| 1828 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1828 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1828               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1828                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1828 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1828                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα ειδεν[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [ος]{.greek-added} [μαρτυς]{.greek-added} [πιστος]{.greek-added} [εστιν]{.greek-added} ο [μαρτυς]{.greek-omitted} [ο]{.greek-omitted} [πιστος]{.greek-omitted} [ο]{.greek-omitted} [πρωτοτοκος]{.greek-omitted} [προτοτοκος]{.greek-added} των νεκρων και ο αρχων των βασιλεων της γης [τω]{.greek-omitted} [αγαπωντι]{.greek-omitted} [ος]{.greek-added} [ηγαπησεν]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [ελουσεν]{.greek-added} ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τ[ους]{.unclear} αιωνας των αιωνων αμην[1:6]{.aside}

ιδο[υ]{.unclear} [[ερ]{.unclear}]{.greek-added} [ερχεται]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [νεφελων]{.greek-omitted} [και]{.greek-omitted} [οψεται]{.greek-omitted} [αυτον]{.greek-omitted} [πας]{.greek-omitted} [οφθαλμος]{.greek-omitted} [και]{.greek-omitted} [οιτινες]{.greek-omitted} [αυτον]{.greek-omitted} [εξεκεντησαν]{.greek-omitted} [και]{.greek-omitted} [κοψονται]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [πασαι]{.greek-omitted} [αι]{.greek-omitted} [φυλαι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ναι]{.greek-omitted} [αμην]{.greek-omitted}[1:7]{.aside}

[ιδου]{.greek-omitted} [ερχεται]{.greek-omitted} [χεται]{.greek-added} [μετα]{.greek-omitted} [μετ]{.greek-added} των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες [αυτον]{.greek-omitted} [αυτων]{.greek-added} εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7 | instance no. 2]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [[ἄλφα]{.greek-abbr}]{.greek-added} και το [ω]{.greek-omitted} [[ὦ]{.greek-abbr}]{.greek-added} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συγκοινωνος]{.greek-added} εν τη θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα φωνην οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης [ο]{.greek-omitted} [α]{.greek-added} βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις [εις]{.greek-omitted} [ει]{.greek-added} εφεσον και εις σμυρναν και εις περγαμον και εις [θυατειρα]{.greek-omitted} [θυατειραν]{.greek-added} και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

και [εκει]{.greek-omitted} επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των επτα λυχνιων ομοιον [υιω]{.greek-omitted} [υιον]{.greek-added} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις μαστοις ζωνην [χρυσην]{.greek-omitted} [χρυσαν]{.greek-added}[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι [και]{.greek-added} ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [ως]{.greek-omitted} [εν]{.greek-omitted} [καμινω]{.greek-omitted} [πεπυρωμενοι]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [φωνη]{.greek-omitted} [υδατων]{.greek-omitted} [πολλων]{.greek-omitted}[1:15]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [ποδες]{.greek-omitted} [αυτου]{.greek-omitted} [ομοιοι]{.greek-omitted} χαλκολιβανω ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15 | instance no. 2]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν τη δεξια αυτου χειρι αστερας επτα και εκ του στοματος αυτ[ου]{.unclear} ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον [επεσα]{.greek-omitted} [επεσον]{.greek-added} προς τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι [με]{.greek-added} εις τους αιωνας των αιωνων αμην και εχω τας κλεις του θανατου και του αδου[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α [δει]{.greek-added} [μελλει]{.greek-omitted} [μελλειν]{.greek-added} [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων [ων]{.corr} ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων [εισιν]{.greek-omitted} [εισι]{.greek-added} και αι [επτα]{.greek-added} λυχνιαι αι επτα [επτα]{.greek-omitted} εκκλησιαι εισιν[1:20]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει [[κυριος]{.greek-abbr}]{.greek-added} ο κρατων τους επτα αστερας εν τη δεξια [χειρι]{.greek-added} αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις και εβαστ[ασας]{.unclear} δια το ονομα μου και ουκ [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα [σου]{.unclear} [οτι]{.greek-omitted} [την]{.greek-omitted} [αγαπην]{.greek-omitted} [σου]{.greek-omitted} [την]{.greek-omitted} [πρωτην]{.greek-omitted} [αφηκας]{.greek-omitted}[2:4]{.aside}

[αλλα]{.greek-omitted} [εχω]{.greek-omitted} [κατα]{.greek-omitted} [σου]{.greek-omitted} οτι την αγαπην σου την πρωτην αφηκας[2:4 | instance no. 2]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν [μεσω]{.greek-added} τω παραδεισω του [θεου]{.greek-abbr} μου[2:7]{.aside}

[[β]{.greek-abbr}]{.greek-added} και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν εκ των λεγοντων [ειναι]{.greek-added} ιουδαιους [ειναι]{.greek-omitted} εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βάλλειν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

[[γ]{.greek-abbr}]{.greek-added} και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις [εν]{.greek-omitted} αις [αν]{.greek-added} [αντιπας]{.greek-omitted} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [μου]{.greek-omitted} [ο]{.greek-omitted} [πιστος]{.greek-omitted} [ος]{.greek-omitted} [απεκτανθη]{.greek-omitted} [παρ]{.greek-omitted} [υμιν]{.greek-omitted} [οπου]{.greek-omitted} [ο]{.greek-omitted} [σατανας]{.greek-omitted} [κατοικει]{.greek-omitted}[2:13]{.aside}

[τεῖπας]{.greek-added} [οιδα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [σου]{.greek-omitted} και [που]{.greek-omitted} [κατοικεις]{.greek-omitted} [οπου]{.greek-omitted} [ο]{.greek-omitted} [θρονος]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [και]{.greek-omitted} [κρατεις]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηρνησω]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [μου]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [εν]{.greek-omitted} [αις]{.greek-omitted} [αντιπας]{.greek-omitted} ο μαρτυς [μου]{.greek-omitted} ο πιστος [μου]{.greek-added} ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13 | instance no. 2]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} και φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην [των]{.greek-omitted} νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω [εκ]{.greek-added} του μαννα [φαγειν]{.greek-added} του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

[[δ]{.greek-abbr}]{.greek-added} και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατηρη]{.greek-added} εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου οτι αφεις την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψι[ν]{.unclear} [μεγαλην]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [μετανοησωσιν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [εργων]{.greek-omitted} [αυτης]{.greek-omitted}[2:22]{.aside}

[ιδου]{.greek-omitted} [βαλλω]{.greek-omitted} [αυτην]{.greek-omitted} [εις]{.greek-omitted} [κλινην]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μοιχευοντας]{.greek-omitted} [μετ]{.greek-omitted} [αυτης]{.greek-omitted} [εις]{.greek-omitted} [θλιψιν]{.greek-omitted} μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22 | instance no. 2]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο [ερευνων]{.greek-omitted} [εραυνων]{.greek-added} νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου [βαλω]{.greek-added} [βαλλω]{.corr} εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων [ους]{.greek-omitted} [ουσ[ι]{.unclear}]{.greek-added} ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

[[ε]{.greek-abbr}]{.greek-added} και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει [[κυριος]{.greek-abbr}]{.greek-added} ο εχων τα επτα πνευματα του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [ο]{.greek-added} [και]{.greek-added} ζης και [νεκ]{.unclear}ρος ει[3:1]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [στηριξον]{.greek-added} τα λοιπα α [εμελλον]{.greek-added} [αποθανειν]{.greek-added} [εμελλες]{.greek-omitted} [ημελλες]{.greek-added} αποβαλλειν ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν [και]{.greek-added} [τηρει]{.greek-added} πως ειληφας και ηκουσας [και]{.greek-omitted} [τηρει]{.greek-omitted} και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωση]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

[[ϛ]{.greek-abbr}]{.greek-added} και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει [[κυριος]{.greek-abbr}]{.greek-added} ο αγιος [ο]{.greek-omitted} [και]{.greek-added} αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει [και]{.greek-added} [κλειων]{.greek-added} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} και ουδεις ανοιξει[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν [ανεωγμενην]{.greek-omitted} [ηνεωγμενην]{.greek-added} ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσιν]{.greek-added} ενωπιον των ποδων σου και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οι[κουμενης]{.unclear} [ολης]{.unclear} [πειρασαι]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[3:10]{.aside}

[οτι]{.greek-omitted} [ετηρησας]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [της]{.greek-omitted} [υπομονης]{.greek-omitted} [μου]{.greek-omitted} [καγω]{.greek-omitted} [σε]{.greek-omitted} [τηρησω]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [ωρας]{.greek-omitted} [του]{.greek-omitted} [πειρασμου]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [οικουμενης]{.greek-omitted} [ολης]{.greek-omitted} πειρασαι τους κατοικουντας επι της γης[3:10 | instance no. 2]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου [και]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [μου]{.greek-omitted} της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει [απο]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} εκ [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} του [θεου]{.greek-abbr} μου και το ονομα μου το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

[[ζ]{.greek-abbr}]{.greek-added} και τω αγγελω της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος οφελον [[ωφελον]{.corr}]{.greek-added} ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και [ου]{.greek-omitted} [ουτε]{.greek-added} ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και πεπλουτηκα και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και [ο]{.greek-omitted} [ελεεινος]{.greek-omitted} [ελεηνος]{.greek-added} και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι [αγορασαι]{.greek-omitted} [παρ]{.greek-added} [εμοι]{.greek-added} χρυσιον [παρ]{.greek-omitted} [εμου]{.greek-omitted} πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος σου και κολλυριον ινα εγχριση τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλευε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και [ανοιξη]{.greek-omitted} [ανοιξει]{.greek-added} την θυραν και εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου [εν]{.greek-omitted} [τω]{.greek-omitted} [θρονω]{.greek-omitted} [μου]{.greek-omitted} [ως]{.greek-omitted} [καγω]{.greek-omitted} [ενικησα]{.greek-omitted} [και]{.greek-omitted} [εκαθισα]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [θρονω]{.greek-omitted} [αυτου]{.greek-omitted}[3:21]{.aside}

[ο]{.greek-omitted} [νικων]{.greek-omitted} [δωσω]{.greek-omitted} [αυτω]{.greek-omitted} [καθισαι]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21 | instance no. 2]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

[και]{.greek-omitted} ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι τον θρονον καθημενος[4:2]{.aside}

[και]{.greek-added} [ο]{.greek-added} [καθημενος]{.greek-added} ομοιος ορασει λιθω ιασπιδι και σαρδιω και [η]{.greek-added} [ιρις]{.greek-omitted} [ἴρις]{.greek-added} [κυκλωθεν]{.greek-added} [κυκλοθεν]{.corr} του θρονου [ομοιως]{.greek-omitted} [ομοια]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδω]{.greek-added}[4:3]{.aside}

και κυκλοθεν του θρονου [θρονοι]{.greek-omitted} [θρονους]{.greek-added} [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} και επι τους θρονους τους [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι [φοβεραι]{.greek-added} και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου [αυτου]{.greek-added} ως θαλασσα υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσ[χω]{.unclear} και το τριτον ζωον [εχον]{.greek-omitted} [εχων]{.greek-added} προσωπον [ανθρωπου]{.greek-abbr} [και]{.unclear} [το]{.unclear} [τεταρτον]{.greek-omitted} [ζωον]{.greek-omitted} [ομοιον]{.greek-omitted} [αετω]{.greek-omitted} [πετομενω]{.greek-omitted}[4:7]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [ζωον]{.greek-omitted} [το]{.greek-omitted} [πρωτον]{.greek-omitted} [ομοιον]{.greek-omitted} [λεοντι]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [δευτερον]{.greek-omitted} [ζωον]{.greek-omitted} [ομοιον]{.greek-omitted} [μοσχω]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [ζωον]{.greek-omitted} [εχον]{.greek-omitted} [προσωπον]{.greek-omitted} [ανθρωπου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} τεταρτον [ζωον]{.greek-omitted} ομοιον αετω πετομενω[4:7 | instance no. 2]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} [εστως]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} ανα πτερυγας εξ κυκλοθεν [εξωθεν]{.greek-added} και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [κυριος]{.greek-abbr} [σαβαωθ]{.greek-added} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωση]{.greek-added} [δωσιν]{.greek-omitted} [[δωσι]{.corr}]{.greek-added} τα [τεσσαρα]{.greek-added} ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας παντα και δια το θελημα σου [ουκ]{.greek-added} ησαν και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν [οπισθεν]{.greek-added} κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εν τω [ουρανω]{.greek-abbr} ανω ουτε επι της γης ουτε υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν [αυτο]{.greek-omitted}[5:3]{.aside}

[και]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [ανω]{.greek-omitted} [ουτε]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ουτε]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ανοιξαι]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [ουτε]{.greek-omitted} [βλεπειν]{.greek-omitted} αυτο[5:3 | instance no. 2]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ο]{.greek-omitted} [o]{.greek-added} ανοιγων το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον [και]{.greek-added} [ιδου]{.greek-added} εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως εσφαγμενον εχον κερατα επτα και οφθαλμους επτα α [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα [πνευματα]{.greek-abbr} [του]{.greek-omitted} [τα]{.greek-added} [προς]{.greek-added} [θεου]{.greek-abbr} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και ηλθεν και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε ελαβεν το βιβλιον τα [τεσσαρα]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ζωα και οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του αρνιου εχοντες εκαστος κιθαραν και φιαλας χρυσας γεμουσας θυμιαματων αι εισιν [αι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν [καινην]{.greek-added} ωδην [καινην]{.greek-omitted} λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας [ημας]{.greek-added} τω [θεω]{.greek-abbr} [ημας]{.greek-omitted} εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και ειδον και ηκουσα ως φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και [τον]{.greek-omitted} [την]{.greek-added} πλουτον και [σοφιαν]{.unclear} [και]{.greek-omitted} [ισχυν]{.greek-omitted} [και]{.greek-omitted} [τιμην]{.greek-omitted} [και]{.greek-omitted} [δοξαν]{.greek-omitted} [και]{.greek-omitted} [ευλογιαν]{.greek-omitted}[5:12]{.aside}

[λεγοντες]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [αξιον]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [αρνιον]{.greek-omitted} [το]{.greek-omitted} [εσφαγμενον]{.greek-omitted} [λαβειν]{.greek-omitted} [την]{.greek-omitted} [δυναμιν]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [πλουτον]{.greek-omitted} [και]{.greek-omitted} [σοφιαν]{.greek-omitted} και ισχυν και τιμην και δοξαν και ευλογιαν[5:12 | instance no. 2]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν τω [ουρανω]{.greek-abbr} και επι της γης και [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} επι της θαλασσης [οσα]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις [παντας]{.greek-omitted} [παντα]{.greek-added} [και]{.greek-added} ηκουσα [λεγοντας]{.greek-omitted} [λεγοντων]{.greek-added} τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων [αμην]{.greek-omitted}[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγοντο]{.greek-added} [το]{.greek-omitted} αμην και οι πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και [προσκυνησα[ν]{.unclear}]{.greek-added} [προσεκυνησα[ν]{.unclear}]{.corr}[5:14]{.aside}

### Chapter 6

και ειδον [οτι]{.greek-omitted} [οτε]{.greek-added} [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνὴ]{.greek-added} βροντης ερχου και ιδε[6:1]{.aside}

και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων [και]{.greek-omitted} ινα νικηση[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [την]{.greek-added} [σφραγιδα]{.greek-added} την δευτεραν [σφραγιδα]{.greek-omitted} ηκουσα του δευτερου ζωου λεγοντος ερχου [και]{.greek-added} [ιδε]{.greek-added}[6:3]{.aside}

και [ειδον]{.greek-added} [και]{.greek-added} [ιδου]{.greek-added} εξηλθεν αλλος ιππος [πυρος]{.greek-omitted} [πυρρος]{.greek-added} και τω καθημενω επ αυτον εδοθη αυτω λαβειν την ειρηνην [απο]{.greek-added} [εκ]{.corr} της γης [και]{.greek-added} ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και ιδε και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων [ζωων]{.greek-omitted} [βωων]{.greek-added} λεγουσαν χοινιξ σιτου δηναριου και τρεις [χοινικες]{.greek-omitted} [χοινι]{.greek-added} [κριθης]{.greek-omitted} [δηναριου]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [ελαιον]{.greek-omitted} [και]{.greek-omitted} [τον]{.greek-omitted} [οινον]{.greek-omitted} [μη]{.greek-omitted} [αδικησης]{.greek-omitted}[6:6]{.aside}

[κες]{.greek-added} [και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [εν]{.greek-omitted} [μεσω]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [λεγουσαν]{.greek-omitted} [χοινιξ]{.greek-omitted} [σιτου]{.greek-omitted} [δηναριου]{.greek-omitted} [και]{.greek-omitted} [τρεις]{.greek-omitted} [χοινικες]{.greek-omitted} κριθης δηναριου και [το]{.greek-omitted} ελαιον και τον οινον μη αδικησης[6:6 | instance no. 2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου και ιδε[6:7]{.aside}

και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης ηκολουθει αυτω και εδοθη αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

[[ε]{.greek-abbr}]{.greek-added} και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} αρνιου [ην]{.greek-omitted} [ειχον]{.greek-omitted}[6:9]{.aside}

και εκραξαν [φωνη]{.greek-omitted} [φωνην]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαλην]{.greek-added} λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και [εκδικεις]{.greek-omitted} [εκδικης]{.greek-added} το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και [ερρεθη]{.greek-omitted} [ερρηθη]{.greek-added} αυτοις ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} ετι χρονον εως [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων και οι μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκτεννεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

[[ϛ]{.greek-abbr}]{.greek-added} και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος μελας εγενετο ως σακκος τριχινος και η σεληνη [ολη]{.greek-omitted} εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} [επεσον]{.greek-omitted} [επεσαν]{.greek-added} εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλουσα]{.greek-added} τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον ελισσομενον και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} [τοις]{.greek-omitted} [ορεσιν]{.greek-omitted} [και]{.greek-omitted} ταις πετραις [και]{.greek-added} [τοις]{.greek-added} [ορεσι]{.greek-added} πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι [τω]{.greek-added} [θρονω]{.greek-added} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης [αυτου]{.greek-omitted} [αυτων]{.greek-added} και τις δυναται [σταθηναι]{.greek-omitted} [στηναι]{.greek-added}[6:17]{.aside}

### Chapter 7

και μετα τουτο ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους [τεσσαρας]{.greek-omitted} [τεσσαρης]{.greek-added} ανεμους της γης ινα μη [πνεη]{.greek-omitted} [πνεει]{.greek-added} ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα [σφραγιδα]{.greek-omitted} [σφραγιδας]{.greek-added} [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον και τεσσαρακοντα τεσσαρες χιλιαδες εσφραγισμενων εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης [ρουβιμ]{.greek-omitted} [ρουβημ]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης γαδ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:6]{.aside}

εκ φυλης συμεων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης λευι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ισαχαρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης βενιαμιν [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις εδυνατο εκ παντος εθνους και φυλων και λαων και γλωσσων [εστωτας]{.greek-omitted} [εστως]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου περιβεβλημενους στολας λευκας και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω θρονω και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι [ειστηκεισαν]{.greek-omitted} [ιστηκεισαν]{.greek-added} κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του θρονου [αυτου]{.greek-added} επι τα προσωπα αυτων και [προσεκυνησαν]{.greek-omitted} [προσεκυνησι]{.greek-added} τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες [αμην]{.greek-omitted} [η]{.greek-omitted} [ευλογια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [ευχαριστια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [τιμη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δυναμις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [ισχυς]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [ημων]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [αμην]{.greek-omitted}[7:12]{.aside}

[λεγοντες]{.greek-omitted} [αμην]{.greek-omitted} η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας [των]{.greek-omitted} [αιωνων]{.greek-omitted} αμην[7:12 | instance no. 2]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι [περιβεβλημενοι]{.greek-omitted} [περιβεβλημμενοι]{.greek-added} τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον αυτω κυριε μου συ οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν [ετι]{.greek-omitted} ουδε διψησουσιν ετι ουδ ου μη [πεση]{.greek-omitted} [πεσει]{.greek-added} επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και οδηγει [η]{.greek-added} αυτους επι ζωης πηγας υδατων και [εξαλειψει]{.greek-omitted} [εξαληψει]{.greek-added} ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην [και]{.greek-added} εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἐιμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι του [θυσι]{.greek-added} [θυσιαστηριου]{.greek-omitted} [εχων]{.greek-omitted} [λιβανωτον]{.greek-omitted} [χρυσουν]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [θυμιαματα]{.greek-omitted} [πολλα]{.greek-omitted} [ινα]{.greek-omitted} [δωση]{.greek-omitted} [ταις]{.greek-omitted} [προσευχαις]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [παντων]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [θυσιαστηριον]{.greek-omitted} [το]{.greek-omitted} [χρυσουν]{.greek-omitted} [το]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted}[8:3]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [αγγελος]{.greek-omitted} [ηλθεν]{.greek-omitted} [και]{.greek-omitted} [εσταθη]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [αστηριου]{.greek-added} εχων λιβανωτον χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα δωση ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3 | instance no. 2]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος [τον]{.greek-omitted} [το]{.greek-added} λιβανωτον και εγεμισεν [αυτον]{.greek-omitted} [αυτο]{.greek-added} εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} βρονται και φωναι και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα [σαλπισωσιν]{.greek-omitted} [σαλπισωσι]{.greek-added}[8:6]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και [εβληθη]{.greek-omitted} [εβληθησαν]{.greek-added} εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα [πυρι]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον [μερος]{.greek-added} της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον [μερος]{.greek-added} των κτισματων [των]{.greek-added} εν τη θαλασση τα εχοντα ψυχας και το τριτον [των]{.greek-omitted} [πλοιων]{.greek-omitted} [διεφθαρη]{.greek-omitted}[8:9]{.aside}

[και]{.greek-omitted} [απεθανεν]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [κτισματων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [τα]{.greek-omitted} [εχοντα]{.greek-omitted} [ψυχας]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} των πλοιων διεφθαρη[8:9 | instance no. 2]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων [ινα]{.greek-omitted} [και]{.greek-added} [σκοτισθη]{.greek-omitted} [εσκοτισθη]{.greek-added} το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [ουκ]{.greek-added} [εφαινεν]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος αετου πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των [μελλονων]{.greek-added} [μελλοντων]{.corr} σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο [πεμσπτος]{.greek-added} [πεμπτος]{.corr} αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος [ως]{.greek-omitted} [ωσπερ]{.greek-added} καπνος καμινου καιομενης και [εσκοτισθη]{.greek-omitted} [εσκοτι]{.greek-added} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αηρ]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [καπνου]{.greek-omitted} [του]{.greek-omitted} [φρεατος]{.greek-omitted}[9:2]{.aside}

[θη]{.greek-added} [και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [ανεβη]{.greek-omitted} [καπνος]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [φρεατος]{.greek-omitted} [ως]{.greek-omitted} [καπνος]{.greek-omitted} [καμινου]{.greek-omitted} [καιομενης]{.greek-omitted} [και]{.greek-omitted} [εσκοτισθη]{.greek-omitted} ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2 | instance no. 2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και [ερρεθη]{.greek-omitted} [ερρηθη]{.greek-added} [αυταις]{.greek-omitted} [αυτοις]{.greek-added} [ινα]{.greek-omitted} μη [αδικησωσιν]{.greek-omitted} [αδικησουσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και εδοθη [αυταις]{.greek-omitted} [αυτοις]{.greek-added} ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [πεση]{.greek-added} [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [ἑυρίσουσιν]{.greek-added} αυτον και [επιθυμησουσιν]{.greek-omitted} [επιθυμισουσιν]{.greek-added} αποθανειν και φευξεται απ αυτων ο θανατος[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι [χρυσοι]{.greek-omitted} [ομοιοι]{.greek-added} [χρυσω]{.greek-added} και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας [ομοιας]{.greek-omitted} [ομοιοις]{.greek-added} [σκορπιοις]{.greek-omitted} [σκοπιοις]{.greek-added} και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι [τους]{.greek-omitted} [τοις]{.greek-added} [ανθρωπους]{.greek-omitted} [[ανθρωποις]{.greek-abbr}]{.greek-added} μηνας πεντε[9:10]{.aside}

[και]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσι]{.greek-added} βασιλεα επ αυτων αγγελον της αβυσσου ονομα αυτω εβραιστι [αββαδων]{.greek-omitted} [αβααδδων]{.greek-added} εν δε τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

λεγουσαν τω εκτω αγγελω [ο]{.greek-omitted} [εχων]{.greek-omitted} [τω]{.greek-added} [εχοντι]{.greek-added} την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι [τεσσαρες]{.greek-omitted} [τεσσαρις]{.greek-added} αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των ανθρωπων[9:15]{.aside}

και ο αριθμος των στρατευματων του ιππου μυριαδες μυριαδων ηκουσα [τον]{.greek-omitted} [των]{.greek-added} αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη [οραση]{.greek-added} [ορασει]{.corr} και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και [υακινθινους]{.greek-omitted} [οιακινθινους]{.greek-added} και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [στοματων]{.greek-omitted} [αυτων]{.greek-omitted} [εκπορευεται]{.greek-omitted} [πυρ]{.greek-omitted} [και]{.greek-omitted} [καπνος]{.greek-omitted} [και]{.greek-omitted} [θειον]{.greek-omitted}[9:17]{.aside}

[και]{.greek-omitted} [ουτως]{.greek-omitted} [ειδον]{.greek-omitted} [τους]{.greek-omitted} [ιππους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ορασει]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [καθημενους]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted} [εχοντας]{.greek-omitted} [θωρακας]{.greek-omitted} [πυρινους]{.greek-omitted} [και]{.greek-omitted} [υακινθινους]{.greek-omitted} [και]{.greek-omitted} [θειωδεις]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [κεφαλαι]{.greek-omitted} [των]{.greek-omitted} [ιππων]{.greek-omitted} [ως]{.greek-omitted} [κεφαλαι]{.greek-omitted} [λεοντων]{.greek-omitted} και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17 | instance no. 2]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} εχουσαι κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων [αυτων]{.greek-omitted} [ουτε]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [φαρμακειων]{.greek-omitted} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων [η]{.greek-added} [των]{.greek-added} [φαρμακιων]{.greek-added} [αυτων]{.greek-added}[9:21]{.aside}

### Chapter 10

και ειδον [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} [περιβεβλημενον]{.greek-omitted} [περιβεβλημμενον]{.greek-added} νεφελην και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και εχων εν τη χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλιδαρι[ον]{.unclear}]{.greek-added} [ανεωγμενον]{.greek-omitted} [και]{.greek-omitted} [εθηκεν]{.greek-omitted} [τον]{.greek-omitted} [ποδα]{.greek-omitted} [αυτου]{.greek-omitted} [τον]{.greek-omitted} [δεξιον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [τον]{.greek-omitted} [δε]{.greek-omitted} [ευωνυμον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[10:2]{.aside}

[ηνεωγμενον]{.greek-added} και [εχων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτου]{.greek-omitted} [βιβλιον]{.greek-omitted} [ανεωγμενον]{.greek-omitted} [και]{.greek-omitted} [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2 | instance no. 2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν [ελαλησαν]{.greek-omitted} [ελαλησεν]{.greek-added} αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται εμελλον [γραφειν]{.greek-omitted} [γραφην]{.greek-added} και ηκουσα φωνην εκ του [ουρανου]{.greek-omitted} [εβδομου]{.greek-added} [αγγελου]{.greek-added} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμοσε]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν και ετελεσθη το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελησε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του ουρανου παλιν λαλουσα μετ εμου και λεγουσα υπαγε λαβε το βιβλιδαριον το [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω δουναι μοι το βιβλιδαριον και λεγει μοι [λαβε]{.greek-omitted} [και]{.greek-omitted} [καταφαγε]{.greek-omitted} [αυτο]{.greek-omitted} [και]{.greek-omitted} [πικρανει]{.greek-omitted} [σου]{.greek-omitted} [την]{.greek-omitted} [κοιλιαν]{.greek-omitted} [αλλ]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [σου]{.greek-omitted} [εσται]{.greek-omitted} [γλυκυ]{.greek-omitted} [ως]{.greek-omitted} [μελι]{.greek-omitted}[10:9]{.aside}

[και]{.greek-omitted} [απηλθον]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [αγγελον]{.greek-omitted} [λεγων]{.greek-omitted} [αυτω]{.greek-omitted} [δουναι]{.greek-omitted} [μοι]{.greek-omitted} [το]{.greek-omitted} [βιβλιδαριον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9 | instance no. 2]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αυτό]{.greek-added} και ην εν τω στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο [και]{.greek-added} [ην]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [στοματι]{.greek-added} [μου]{.greek-added} [ως]{.greek-added} [μελι]{.greek-added} [γλυκυ]{.greek-added} [και]{.greek-added} επικρανθη η κοιλια μου[10:10]{.aside}

και λεγουσιν μοι δει σε παλιν προφητευσαι [παλιν]{.greek-added} [προφητευσαι]{.greek-added} επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω [και]{.greek-added} [ειστηκει]{.greek-added} [αγγελος]{.greek-added} λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και [μετρησον]{.greek-omitted} [μετρισον]{.greek-added} τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την [εξωθεν]{.greek-omitted} [εσωθεν]{.greek-added} του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα [και]{.greek-omitted} δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας [διακοσιας]{.greek-omitted} [εξακοσιας]{.greek-added} εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι [αι]{.greek-omitted} ενωπιον του [κυριου]{.greek-abbr} της γης [εστωσαι]{.greek-omitted} [εστωτες]{.greek-added}[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και [κατεσθιει]{.greek-omitted} [κατεσθηει]{.greek-added} τους εχθρους αυτων και ει τις θελει αυτους αδικησαι [ουτως]{.greek-omitted} [δει]{.greek-omitted} [αυτον]{.greek-omitted} [αποκτανθηναι]{.greek-omitted}[11:5]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [αυτους]{.greek-omitted} [θελει]{.greek-omitted} [αδικησαι]{.greek-omitted} [πυρ]{.greek-omitted} [εκπορευεται]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [κατεσθιει]{.greek-omitted} [τους]{.greek-omitted} [εχθρους]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [θελει]{.greek-omitted} [αυτους]{.greek-omitted} [αδικησαι]{.greek-omitted} ουτως δει αυτον αποκτανθηναι[11:5 | instance no. 2]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} [τον]{.greek-omitted} [τoν]{.greek-added} [ουρανον]{.greek-abbr} εξουσιαν κλεισαι ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην [οσακις]{.greek-omitted} [ωσακις]{.greek-added} εαν θελησωσιν εν παση πληγη[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου [και]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8]{.aside}

και βλεπουσιν εκ των λαων και [γλωσσων]{.greek-added} [και]{.greek-added} φυλων [και]{.greek-omitted} [γλωσσων]{.greek-omitted} και εθνων το πτωμα αυτων ημερας τρεις [ημισυ]{.greek-omitted} [ειμισυ]{.greek-added} και τα [πτωματα]{.greek-omitted} [σωματα]{.greek-added} αυτων ουκ [αφησουσιν]{.greek-omitted} [αφησουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και ευφρανθησονται και δωρα δωσουσιν αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} [εξηλθεν]{.greek-added} [εισηλθεν]{.corr} εις αυτους και εστησαν [ε]{.greek-added} [επι]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [φοβος]{.greek-omitted} [μεγας]{.greek-omitted} [επεσεν]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [θεωρουντας]{.greek-omitted} [αυτους]{.greek-omitted}[11:11]{.aside}

[και]{.greek-omitted} [μετα]{.greek-omitted} [τας]{.greek-omitted} [τρεις]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [ημισυ]{.greek-omitted} [πνευμα]{.greek-omitted} [ζωης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [εστησαν]{.greek-omitted} επι τους ποδας αυτων και φοβος μεγας επεσεν επι τους θεωρουντας αυτους[11:11 | instance no. 2]{.aside}

και ηκουσα φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη [ημερα]{.greek-omitted} [ωρα]{.greek-added} εγενετο σεισμος μεγας και το δεκατον της πολεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν η ουαι η τριτη ιδου ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι οι ενωπιον του [θρονου]{.greek-omitted} [θρωνου]{.greek-added} του [θεου]{.greek-abbr} [καθημενοι]{.greek-omitted} [οι]{.greek-added} [καθηνται]{.greek-added} επι τους θρονους αυτων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι τα [προσωπα]{.greek-omitted} [πρωσωπα]{.greek-added} αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην [και]{.greek-omitted} [εβασιλευσας]{.greek-omitted}[11:17]{.aside}

[λεγοντες]{.greek-omitted} [ευχαριστουμεν]{.greek-omitted} [σοι]{.greek-omitted} [κυριε]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [παντοκρατωρ]{.greek-omitted} [ο]{.greek-omitted} [ων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ην]{.greek-omitted} [οτι]{.greek-omitted} [ειληφας]{.greek-omitted} [την]{.greek-omitted} [δυναμιν]{.greek-omitted} [σου]{.greek-omitted} [την]{.greek-omitted} [μεγαλην]{.greek-omitted} και εβασιλευσας[11:17 | instance no. 2]{.aside}

και τα [τα]{.greek-added} [[τα]{.corr}]{.greek-added} εθνη [ωργισθησαν]{.greek-omitted} [οργισθησαν]{.greek-added} και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις φοβουμενοις το ονομα σου τοις μικροις και [τοις]{.greek-omitted} μεγαλοις και διαφθειραι τους διαφθειροντας την γην[11:18]{.aside}

και [ηνοιγη]{.greek-omitted} [ηνοιγει]{.greek-added} ο ναος του [θεου]{.greek-abbr} [ο]{.greek-added} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης του [κυριου]{.greek-abbr} εν τω ναω αυτου και εγενοντο αστραπαι και [βρονται]{.greek-added} [και]{.greek-added} φωναι και [βρονται]{.greek-omitted} [σεισμοι]{.greek-added} και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη [υποκατω]{.greek-omitted} [υπο]{.greek-added} [κατω]{.greek-added} των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα [εκραζεν]{.greek-omitted} [εκραξεν]{.greek-added} ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη [αλλο]{.greek-omitted} [αλλω]{.greek-added} σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων [πυρος]{.greek-omitted} [πυρρος]{.greek-added} μεγας εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας [αυτου]{.greek-omitted} [αυτ[ων]{.unclear}]{.greek-added} επτα [διαδηματα]{.greek-omitted} [διαδιματα]{.greek-added}[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων [ἕ]{.greek-added} [εστηκεν]{.greek-omitted} [ενωπιον]{.greek-omitted} [της]{.greek-omitted} [γυναικος]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} [τεκειν]{.greek-omitted} [ινα]{.greek-omitted} [οταν]{.greek-omitted} [τεκη]{.greek-omitted} [το]{.greek-omitted} [τεκνον]{.greek-omitted} [αυτης]{.greek-omitted} [καταφαγη]{.greek-omitted}[12:4]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [ουρα]{.greek-omitted} [αυτου]{.greek-omitted} [συρει]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [αστερων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [εστηκεν]{.greek-omitted} [στηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη [αυτο]{.greek-added}[12:4 | instance no. 2]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη αυτω ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην ολην [εβληθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [αυτου]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-omitted} [[σωτηρι]{.greek-abbr}]{.greek-added} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων [αυτων]{.greek-omitted} [αυτον]{.greek-added} ενωπιον του [θεου]{.greek-abbr} ημων ημερας και [νυκτος]{.greek-omitted}[12:10]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [μεγαλην]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [λεγουσαν]{.greek-omitted} [αρτι]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [σωτηρια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δυναμις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [εξουσια]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [εβληθη]{.greek-omitted} [ο]{.greek-omitted} [κατηγορος]{.greek-omitted} [των]{.greek-omitted} [αδελφων]{.greek-omitted} [ημων]{.greek-omitted} [ο]{.greek-omitted} [κατηγορων]{.greek-omitted} [αυτων]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} νυκτος[12:10 | instance no. 2]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν [την]{.greek-omitted} [ψυχην]{.greek-omitted} [τας]{.greek-added} [ψυχας]{.greek-added} αυτων αχρι θανατου[12:11]{.aside}

δια τουτο ευφραινεσθε [οι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν αυτοις σκηνουντες ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν τη γυναικι δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον αυτης οπως τρεφηται εκει καιρον [και]{.greek-omitted} καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορη[τον]{.unclear} ποιηση[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [εχοντων]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted}[12:17]{.aside}

[και]{.greek-omitted} [ωργισθη]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [γυναικι]{.greek-omitted} [και]{.greek-omitted} [απηλθεν]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [λοιπων]{.greek-omitted} [του]{.greek-omitted} [σπερματος]{.greek-omitted} [αυτης]{.greek-omitted} [των]{.greek-omitted} [τηρουντων]{.greek-omitted} [τας]{.greek-omitted} [εντολας]{.greek-omitted} του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [του]{.greek-added} [ιησου]{.greek-abbr}[12:17 | instance no. 2]{.aside}

[και]{.greek-added} [εσταθη]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ειδον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} θηριον αναβαινον εχον κερατα δεκα και κεφαλας επτα και επι των κερατων [αυτου]{.greek-omitted} [αυτων]{.greek-added} δεκα διαδηματα και επι τας κεφαλας [αυτου]{.greek-omitted} [αυτων]{.greek-added} ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον [ομοιον]{.greek-added} ην [ομοιον]{.greek-omitted} παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα [λεοντος]{.greek-omitted} [λεοντων]{.greek-added} και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου [ωσει]{.greek-omitted} [ως]{.greek-added} εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και [εθαυμασεν]{.greek-omitted} [εθαυμασθη]{.greek-added} ολη η [γη]{.corr} [οπισω]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [επι]{.greek-added} [τω]{.greek-added} [θηριω]{.greek-added}[13:3]{.aside}

και προσεκυνησαν τω δρακοντι [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [οτι]{.greek-added} [εδωκε]{.greek-added} την εξουσιαν τω θηριω και προσεκυνησαν τω θηριω λεγοντες τις ομοιος τω θηριω και τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και βλασφημιαν και εδοθη αυτω εξουσια πολεμον ποιησαι μηνας τεσσαρακοντα δυο[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις [βλασφημιαν]{.greek-omitted} [βλασφημιας]{.greek-added} προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου τους εν τω [ουρανω]{.greek-abbr} σκηνουντας[13:6]{.aside}

και εδοθη αυτω [ποιησαι]{.greek-omitted} πολεμον [μετα]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [νικησαι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσια]{.greek-omitted} [επι]{.greek-omitted} [πασαν]{.greek-omitted} [φυλην]{.greek-omitted} [και]{.greek-omitted} [λαον]{.greek-omitted} [και]{.greek-omitted} [γλωσσαν]{.greek-omitted} [και]{.greek-omitted} [εθνος]{.greek-omitted}[13:7]{.aside}

[και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} ποιησαι [πολεμον]{.greek-omitted} μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και λαον και γλωσσαν και εθνος[13:7 | instance no. 2]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες επι της γης [ων]{.greek-omitted} [ου]{.greek-added} ου γεγραπται το ονομα [αυτου]{.greek-added} εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} [αιχμαλωσιαν]{.greek-added} [απαγει]{.greek-added} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτενεῖ]{.greek-added} [δει]{.greek-omitted} [αυτον]{.greek-omitted} εν μαχαιρα αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και ειχεν κερατα δυο ομοια αρνιω και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν [ποιει]{.greek-omitted} [ποιησει]{.greek-added} ενωπιον αυτου και εποιει την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου [αυτου]{.greek-omitted}[13:12]{.aside}

και [ποιει]{.greek-omitted} [ποιησει]{.greek-added} [μεγαλα]{.greek-added} σημεια [μεγαλα]{.greek-omitted} [ινα]{.greek-added} και πυρ [ινα]{.greek-omitted} [ποιηση]{.greek-added} [καταβηναι]{.greek-added} εκ του [ουρανου]{.greek-abbr} [εις]{.greek-added} [καταβαινη]{.greek-omitted} [επι]{.greek-omitted} την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ποιησαι]{.greek-omitted} [εικονα]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [την]{.greek-omitted} [πληγην]{.greek-omitted} [και]{.greek-omitted} [εζησεν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

[και]{.greek-omitted} [πλανα]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [δια]{.greek-omitted} [τα]{.greek-omitted} [σημεια]{.greek-omitted} [α]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [ποιησαι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [λεγων]{.greek-omitted} [τοις]{.greek-omitted} [κατοικουσιν]{.greek-omitted} επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ὃς]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} την πληγην [της]{.greek-added} [μαχαιρας]{.greek-added} και εζησεν [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14 | instance no. 2]{.aside}

και εδοθη αυτω [πνευμα]{.greek-abbr} δουναι τη [εικονι]{.greek-omitted} [εικονει]{.greek-added} του θηριου ινα και λαληση η εικων του θηριου και [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} [ινα]{.greek-added} οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τη εικονι του θηριου [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και [ποιει]{.greek-omitted} [ποιη]{.greek-added} παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} [αυτοις]{.greek-omitted} [εαυτοις]{.greek-added} [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της χειρος αυτων της δεξιας η επι [το]{.greek-omitted} [τω]{.greek-added} [μετωπον]{.greek-omitted} [μετωπω]{.greek-added} αυτων[13:16]{.aside}

και ινα [μηδεις]{.greek-added} [μη]{.greek-omitted} [τις]{.greek-omitted} [δυναται]{.greek-omitted} [δυνηται]{.greek-added} [πωλησαι]{.greek-added} [η]{.greek-added} αγορασαι [ετι]{.greek-added} [η]{.greek-omitted} [πωλησαι]{.greek-omitted} ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν ψηφισατω [τον]{.greek-omitted} [το]{.greek-added} [αριθμον]{.greek-omitted} [ονομα]{.greek-added} του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} εστιν [και]{.greek-omitted} [αριθμος]{.greek-added} [γαρ]{.greek-added} [αυτου]{.greek-added} [εστιν]{.greek-added} ο αριθμος αυτου [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξακοσιοι]{.greek-added} εξηκοντα εξ[13:18]{.aside}

### Chapter 14

και ειδον και ιδου το αρνιον [εστηκος]{.greek-omitted} [εστως]{.greek-added} επι το ορος σιων και μετ αυτου [[ρμδ]{.greek-abbr}]{.greek-added} [αριθμος]{.greek-omitted} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες [αι]{.greek-added} εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου [γεγραμμενον]{.greek-omitted} [γεγραμμενων]{.greek-added} επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης [μεγαλης]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [ην]{.greek-omitted} [ηκουσα]{.greek-omitted} [ως]{.greek-omitted} [κιθαρωδων]{.greek-omitted} [κιθαριζοντων]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [κιθαραις]{.greek-omitted} [αυτων]{.greek-omitted}[14:2]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} [υδατων]{.greek-omitted} [πολλων]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} [βροντης]{.greek-omitted} μεγαλης και η φωνη ην ηκουσα ως κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2 | instance no. 2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι [εισιν]{.greek-omitted} οι ακολουθουντες [τω]{.greek-omitted} [αρνιω]{.greek-omitted} [το]{.greek-added} [αρνιον]{.greek-added} οπου αν υπαγη ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και ουχ ευρεθη εν τω στοματι αυτων [[ο]{.corr}]{.greek-added} ψευδος αμωμοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added}[14:5]{.aside}

και ειδον αγγελον [αλλον]{.greek-added} πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον ευαγγελισαι [επι]{.greek-added} τους [καθημενους]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης και επι παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-abbr} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε αυτον τον ποιησαντα τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος δευτερος αγγελος [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη [η]{.greek-added} εκ του οινου του θυμου [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted} [πεποτικεν]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted}[14:8]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [δευτερος]{.greek-omitted} [αγγελος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [λεγων]{.greek-omitted} [επεσεν]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8 | instance no. 2]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν [τη]{.greek-added} [μεγαλη]{.greek-added} [τη]{.greek-added} φωνη [μεγαλη]{.greek-omitted} ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει [το]{.greek-added} χαραγμα επι του μετωπου αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον των [αγιων]{.greek-omitted} αγγελων και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις αιωνας αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added} οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του ουρανου λεγουσης γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [ἀπάρτι]{.greek-added} [λεγοντες]{.greek-added} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} ναι το [πνευμα]{.greek-abbr} [το]{.greek-added} [αγιον]{.greek-added} ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυ[των]{.unclear} [ακολουθει]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσης]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [νεκροι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [κυριω]{.greek-omitted} [αποθνησκοντες]{.greek-omitted} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} [ναι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ινα]{.greek-omitted} [αναπαυσωνται]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κοπων]{.greek-omitted} [αυτων]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted} ακολουθει μετ αυτων[14:13 | instance no. 2]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην καθημενον ομοιον [υιω]{.greek-omitted} [υιον]{.greek-added} [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και [αγγελος]{.greek-added} αλλος [αγγελος]{.greek-omitted} εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι [ηκμασαν]{.greek-omitted} [ηκμασεν]{.greek-added} [αι]{.greek-omitted} [η]{.greek-added} [σταφυλαι]{.greek-omitted} [σταφυλη]{.greek-added} [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[14:18]{.aside}

και [εβαλεν]{.greek-omitted} [εξεβαλεν]{.greek-added} ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις την ληνον [του]{.greek-omitted} [θυμου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τον]{.greek-omitted} [μεγαν]{.greek-omitted}[14:19]{.aside}

[και]{.greek-omitted} [εβαλεν]{.greek-omitted} [ο]{.greek-omitted} [αγγελος]{.greek-omitted} [το]{.greek-omitted} [δρεπανον]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} την [μεγαλην]{.greek-added} [[τον]{.corr}]{.greek-added} [[μεγαν]{.corr}]{.greek-added} [γην]{.greek-omitted} [και]{.greek-omitted} [ετρυγησεν]{.greek-omitted} [την]{.greek-omitted} [αμπελον]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [ληνον]{.greek-omitted} του θυμου του [θεου]{.greek-abbr} [τον]{.greek-omitted} [μεγαν]{.greek-omitted}[14:19 | instance no. 2]{.aside}

και επατηθη η ληνος εξωθεν της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο [σημειον]{.greek-omitted} [σιμειον]{.greek-added} εν τω [ουρανω]{.greek-abbr} μεγα και [θαυμαστον]{.greek-omitted} [θαυμασιον]{.greek-added} αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην [την]{.greek-added} [μεμιγμενην]{.greek-added} [πυρι]{.greek-added} εχοντας [τας]{.greek-added} κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην μωυσεως [του]{.greek-omitted} δουλου του [θεου]{.greek-abbr} και την [ωδην]{.greek-omitted} [φωνην]{.greek-added} του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη [φοβηθη]{.greek-omitted} [φοβηθησε]{.greek-added} [σε]{.greek-omitted} [κυριε]{.greek-abbr} και [δοξαση]{.greek-omitted} [δοξασει]{.greek-added} το ονομα σου οτι μονος αγιος οτι [παντες]{.greek-added} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} οι ησαν ενδεδυμενοι [λινον]{.greek-omitted} [λινουν]{.greek-added} καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων [αμην]{.greek-added}[15:7]{.aside}

και εγεμισθη ο ναος [εκ]{.greek-added} [του]{.greek-added} καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας επτα φιαλας του θυμου [μου]{.greek-added} [του]{.greek-omitted} [θεου]{.greek-omitted} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος [αγγελος]{.greek-added} και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεσε]{.greek-added} την [φιαλην]{.greek-omitted} [φιαλιν]{.greek-added} αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη [ζωσα]{.greek-omitted} απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την [φιαλην]{.greek-omitted} [φιαλιν]{.greek-added} αυτου εις τους ποταμους και [εις]{.greek-omitted} [τας]{.greek-omitted} [πηγας]{.greek-omitted} [των]{.greek-omitted} [υδατων]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [αιμα]{.greek-omitted}[16:4]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [τριτος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [ποταμους]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} τας πηγας των υδατων και εγενετο αιμα[16:4 | instance no. 2]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην [και]{.greek-added} ο οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν αξιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:6]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και εδοθη αυτω καυματισαι εν πυρι τους [ανθρωπους]{.greek-abbr}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και εμασωντο τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ποταμον τον μεγαν ευφρατην και εξηρανθη το [υδωρ]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [ετοιμασθη]{.greek-omitted} [η]{.greek-omitted} [οδος]{.greek-omitted} [των]{.greek-omitted} [βασιλεων]{.greek-omitted} [των]{.greek-omitted} [απο]{.greek-omitted} [ανατολης]{.greek-omitted} [ηλιου]{.greek-omitted}[16:12]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [ποταμον]{.greek-omitted} [τον]{.greek-omitted} [μεγαν]{.greek-omitted} [ευφρατην]{.greek-omitted} [και]{.greek-omitted} [εξηρανθη]{.greek-omitted} [το]{.greek-omitted} υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12 | instance no. 2]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα ακαθαρτα τρια ως βατραχοι[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ πνευματα δαιμονιων ποιουντα σημεια α εκπορευεται επι τους βασιλεις της οικουμενης ολης [συναγαγειν]{.greek-omitted} [συναγειν]{.greek-added} αυτους εις τον πολεμον της ημερας [εκεινης]{.greek-omitted} της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου [γαρ]{.greek-added} ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [μαγεδώδ]{.greek-added}[16:16]{.aside}

και ο εβδομος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη [εκ]{.greek-added} [απο]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και φωναι και σεισμος μεγας οιος ουκ εγενετο αφ ου οι [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος ουτως μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι [αυτη]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [αυτου]{.greek-omitted}[16:19]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εις]{.greek-omitted} [τρια]{.greek-omitted} [μερη]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [πολεις]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted} [επεσον]{.greek-omitted} [και]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εμνησθη]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [δουναι]{.greek-omitted} αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19 | instance no. 2]{.aside}

και πασα νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη αυτης σφοδρα [ω]{.greek-added}[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον [το]{.greek-added} κοκκινον γεμον ονοματα βλασφημιας [εχον]{.greek-omitted} [εχων]{.greek-added} κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἦν]{.greek-added} περιβεβλημενη πορφυρουν και κοκκινον [περι]{.greek-added} κεχρυσωμενη χρυσιω και λιθω τιμιω και μαργαριταις εχουσα ποτηριον χρυσουν εν τη χει[ρι]{.unclear} αυτης γεμον βδελυγματων και τα ακαθαρτ[α]{.unclear} [της]{.unclear} πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [η]{.greek-omitted} [μητηρ]{.greek-omitted} [των]{.greek-omitted} [πορνων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [βδελυγματων]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[17:5]{.aside}

[και]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [μετωπον]{.greek-omitted} [αυτης]{.greek-omitted} [ονομα]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [μυστηριον]{.greek-omitted} βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5 | instance no. 2]{.aside}

και ειδον την γυναικα μεθυουσαν εκ του αιματος των αγιων εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και ειπεν μοι ο αγγελος δια τι εθαυμασας εγω ερω σοι το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ εστιν και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων ου γεγραπται [τα]{.greek-omitted} [το]{.greek-added} [ονοματα]{.greek-omitted} [ονομα]{.greek-added} επι [το]{.greek-omitted} [του]{.greek-added} [βιβλιον]{.greek-omitted} [βιβλιου]{.greek-added} της ζωης απο καταβολης κοσμου βλεποντων οτι ην το θηριον και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ [αυτων]{.greek-omitted} [ανω]{.greek-added} [και]{.greek-added} [βασιλεις]{.greek-added} [εισιν]{.greek-added} [επτα]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ο εις εστιν ο αλλος ουπω ηλθεν και οταν ελθη ολιγον δει αυτον μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ εστιν και [αυτος]{.greek-omitted} [ουτος]{.greek-added} ογδοος εστιν και εκ των επτα [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν [οιτινες]{.greek-omitted} [βασιλειαν]{.greek-omitted} [ουπω]{.greek-omitted} [ελαβον]{.greek-omitted} [αλλ]{.greek-omitted} [εξουσιαν]{.greek-omitted} [ως]{.greek-omitted} [βασιλεις]{.greek-omitted} [μιαν]{.greek-omitted} [ωραν]{.greek-omitted} [λαμβανουσιν]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted}[17:12]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [δεκα]{.greek-omitted} [κερατα]{.greek-omitted} [α]{.greek-omitted} [ειδες]{.greek-omitted} [δεκα]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} μετα του θηριου[17:12 | instance no. 2]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την δυναμιν και την εξουσιαν αυτων τω θηριω διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου κλητοι και [πιστοι]{.greek-added} [και]{.greek-added} εκλεκτοι [και]{.greek-omitted} [πιστοι]{.greek-omitted}[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη [επι]{.greek-added} καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην [ποιησουσιν]{.greek-omitted} [ποιησωσιν]{.greek-added} αυτην και γυμνην [ποιησουσιν]{.greek-omitted} [ποησουσ[ο]{.unclear}ν]{.greek-added} αυτην και τας σαρκας αυτης φαγονται και αυτην [κατακαυσουσιν]{.greek-omitted} [κατακαυσουσι]{.greek-added} [εν]{.greek-omitted} πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι γνωμην μιαν [αυτων]{.greek-added} και δουναι την βασιλειαν αυτων τω θηριω αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν ισχυρα φωνη λεγων επεσεν [επεσε]{.greek-added} βαβυλων [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [κατοικητηριον]{.greek-omitted} [δαιμονων]{.greek-omitted} [και]{.greek-omitted} [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [πνευματος]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [ορνεου]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} [μεμισημενου]{.greek-omitted}[18:2]{.aside}

[και]{.greek-omitted} [εκραξεν]{.greek-omitted} [ισχυρα]{.greek-omitted} [φωνη]{.greek-omitted} [λεγων]{.greek-omitted} [επεσεν]{.greek-omitted} [βαβυλων]{.greek-omitted} η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος [πνευματος]{.greek-abbr} ακαθαρτου και φυλακη παντος ορνεου ακαθαρτου και μεμισημενου[18:2 | instance no. 2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκαν]{.greek-added} παντα τα εθνη και οι [βασιλεις]{.greek-omitted} [βασιλης]{.greek-added} της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης [επλουτησαν]{.greek-omitted} [επλουτισαν]{.greek-added}[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν [αυτης]{.greek-added} ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

[αποδοτε]{.greek-omitted} [αποδωται]{.greek-added} αυτη ως και αυτη [απεδωκεν]{.greek-omitted} [απεδωκε]{.greek-added} και διπλωσατε αυτη διπλα [κατα]{.greek-omitted} τα εργα αυτης εν τω ποτηριω [ω]{.greek-omitted} [αυτης]{.greek-added} [ως]{.greek-added} [εκερασεν]{.greek-omitted} [εκερασε]{.greek-added} κερασατε αυτη διπλουν[18:6]{.aside}

οσα εδοξασεν [αυτην]{.greek-omitted} [εαυτη]{.greek-added} και [εστρηνιασεν]{.greek-omitted} [εστρηνιασε]{.greek-added} τοσουτον [δοτε]{.greek-omitted} [δωτε]{.greek-added} αυτη βασανισμον και πενθος οτι εν τη καρδια αυτης λεγει οτι [εγω]{.greek-added} καθημαι βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος [και]{.greek-omitted} πενθος και λιμος και εν [πυρι]{.greek-omitted} [κατακαυθησεται]{.greek-omitted} [οτι]{.greek-omitted} [ισχυρος]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ο]{.greek-omitted} [κρινας]{.greek-omitted} [αυτην]{.greek-omitted}[18:8]{.aside}

[δια]{.greek-omitted} [τουτο]{.greek-omitted} [εν]{.greek-omitted} [μια]{.greek-omitted} [ημερα]{.greek-omitted} [ηξουσιν]{.greek-omitted} [αι]{.greek-omitted} [πληγαι]{.greek-omitted} [αυτης]{.greek-omitted} [θανατος]{.greek-omitted} [και]{.greek-omitted} [πενθος]{.greek-omitted} [και]{.greek-omitted} [λιμος]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8 | instance no. 2]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και κοψονται επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του [βασανισμου]{.greek-omitted} [βανισμου]{.greek-added} αυτης λεγοντες [ουαι]{.greek-added} ουαι ουαι η πολις η μεγαλη [η]{.greek-added} βαβυλων η πολις η ισχυρα οτι μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και [πενθησουσιν]{.greek-omitted} [πενθησουσι]{.greek-added} επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} οτι τον γομον [αυτων]{.greek-omitted} [αυτης]{.greek-added} ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και [μαργαριτου]{.greek-omitted} [μαργαριτων]{.greek-added} και βυσσινου και πορφυρου και σηρικου και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κινναμωμου]{.greek-added} και [θυμιαματα]{.greek-omitted} [αμωμου]{.greek-added} και [θυμιαματος]{.greek-added} [και]{.greek-added} [μυρον]{.greek-omitted} [μυρου]{.greek-added} και λιβανον και οινον και ελαιον και σεμιδαλιν και σιτον και προβατα και κτηνη και ιππων και [ραιδων]{.greek-omitted} [ρεδων]{.greek-added} και σωματων και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η οπωρα [σου]{.greek-added} της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα απωλετο απο σου και ουκετι [αυτα]{.greek-omitted} ου μη [ευρης]{.greek-omitted} [αυτα]{.greek-added} [ευρησουσιν]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι [πλουτι]{.greek-added} [πλουτησαντες]{.greek-omitted} [απ]{.greek-omitted} [αυτης]{.greek-omitted} [απο]{.greek-omitted} [μακροθεν]{.greek-omitted} [στησονται]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [φοβον]{.greek-omitted} [του]{.greek-omitted} [βασανισμου]{.greek-omitted} [αυτης]{.greek-omitted} [κλαιοντες]{.greek-omitted} [και]{.greek-omitted} [πενθουντες]{.greek-omitted}[18:15]{.aside}

[σαντες]{.greek-added} [οι]{.greek-omitted} [εμποροι]{.greek-omitted} [τουτων]{.greek-omitted} [οι]{.greek-omitted} [πλουτησαντες]{.greek-omitted} απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15 | instance no. 2]{.aside}

[και]{.greek-omitted} λεγοντες ουαι ουαι η πολις η μεγαλη η περιβεβλημενη [βυσσινον]{.greek-omitted} [βυσσω]{.greek-added} και πορφυρουν και κοκκινον και [κεχρυσωμενη]{.greek-omitted} [κεχρυσομενη]{.greek-added} χρυσιω και λιθω τιμιω και [μαργαριταις]{.greek-omitted} [μαργαριτες]{.greek-added}[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος και πας κυβερνητης και πας ο επι τοπον πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και εκραζον βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη [πολ]{.unclear}ει τη μεγαλη[18:18]{.aside}

και εβαλον χουν επι τας [κεφαλας]{.unclear} αυτων και εκραζον κλαιοντες και πενθουντ[ες]{.unclear} [και]{.greek-omitted} λεγοντες ουαι ουαι η πολις η μεγαλη εν η [επλουτησαν]{.greek-omitted} [επλουτισαν]{.greek-added} παντες οι εχοντες [τα]{.greek-omitted} πλοια εν τη θαλασση εκ της [τιμιοτητος]{.greek-omitted} [τιμιωτητος]{.greek-added} αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ αυτ[η]{.unclear} [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελ[ος]{.unclear} ισχυρος λιθον ως [μυλον]{.greek-omitted} [μυλων]{.greek-added} [μεγαν]{.greek-omitted} [μεγα]{.greek-added} και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι [εν]{.greek-added} [αυτη]{.greek-added}[18:21]{.aside}

και φωνη [κιθαρωδων]{.greek-omitted} [κιθαρων]{.greek-added} και μουσικων και [αυλητων]{.greek-omitted} [αυλιτων]{.greek-added} και σαλπιστων ου μη ακουσθη εν σοι ετι και πας [τεχνιτης]{.greek-omitted} [τεχνητης]{.greek-added} πασης τεχνης [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22]{.aside}

