---
title: "Collation of Byz^RP^ vs 31827 (1827)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1827 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31827).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1827                                   	| λογος                              	|
| 1827 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1827 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1827               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1827                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1827 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1827                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 1

[ανδρες]{.greek-omitted} [αδελφοι]{.greek-omitted} [εδει]{.greek-omitted} [πληρωθηναι]{.greek-omitted} [την]{.greek-omitted} [γραφην]{.greek-omitted} [ταυτην]{.greek-omitted} [ην]{.greek-omitted} [προειπεν]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [το]{.greek-omitted} [αγιον]{.greek-omitted} [δια]{.greek-omitted} [στοματος]{.greek-omitted} [δαυιδ]{.greek-omitted} [περι]{.greek-omitted} [ιουδα]{.greek-omitted} [του]{.greek-omitted} [γενομενου]{.greek-omitted} οδηγου τοις [συλλαβουσιν]{.greek-omitted} [συλλαβουσι]{.greek-added} τον [ιησουν]{.greek-abbr}[[1:16 *(lacunose)*]{.lacunose}]{.aside}

οτι κατηριθμημενος ην συν ημιν και [ελαχεν]{.greek-omitted} [ελαχε]{.greek-added} τον κληρον της διακονιας ταυτης[1:17]{.aside}

ο[υ]{.unclear}τος μεν [ουν]{.greek-omitted} εκτησατο χωριον εκ μισθου της αδικιας και πρηνης γενομενος [ελακησεν]{.greek-omitted} [ελακισε]{.greek-added} μεσος και εξεχυθη παντα τα [σπλαγχνα]{.greek-omitted} [σπλαγνα]{.greek-added} αυτου[1:18]{.aside}

και γνωστον εγενετο [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} ωστε κληθηναι το χωριον εκεινο τη ιδια διαλεκτω αυτων ακελδαμα τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} [χωριον]{.greek-omitted} [χωριοι]{.greek-added} αιματος[1:19]{.aside}

γεγραπται γαρ εν βιβλω ψαλμων [γενηθητω]{.greek-omitted} [γεννηθητω]{.greek-added} η επαυλις αυτου ερημος και μη εστω ο κατοικων εν αυτη και την επισκοπην αυτου λαβοι ετερος[1:20]{.aside}

δει ουν [τον]{.greek-added} [των]{.corr} συνελθοντων ημιν αν[δ]{.unclear}ρων εν παντι χρονω εν ω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} και εξηλθεν εφ ημας ο [κυριος]{.greek-abbr} [ημων]{.greek-added} [ιησους]{.greek-abbr}[1:21]{.aside}

αρξαμενος απο του βαπτισματος ιωαννου εως τ[η]{.unclear}ς ημερ[α]{.unclear}ς ης ανεληφθη αφ ημων [μαρτυρα]{.greek-omitted} [μ[α]{.unclear}ρτυρας]{.greek-added} της αναστασεως αυτου γενεσθαι συν [η]{.unclear}μιν ενα τουτων[1:22]{.aside}

και εστησαν δυο ιωσηφ τον καλουμενον βαρσαβαν ος επεκληθη ιουστος και ματθιαν[1:23]{.aside}

και προσευξαμενοι ειπον συ [κυριε]{.greek-abbr} καρδιογνωστα παντων αναδει[ξον]{.greek-supplied} ον εξελεξω εκ [τουτων]{.greek-omitted} των δυο [τουτων]{.greek-added} ενα[1:24]{.aside}

λ[αβει]{.greek-supplied}ν τον κληρον της [[την]{.corr}]{.greek-added} διακονια[ς]{.unclear} ταυτ[ης]{.greek-supplied} [και]{.greek-supplied} [α]{.greek-supplied}ποστολης εξ ης παρεβη ιουδα[ς]{.unclear} π[ορευ]{.greek-supplied}θηναι εις τον [τ]{.unclear}οπον τον ιδιον[1:25]{.aside}

[κ]{.unclear}[αι]{.greek-supplied} [εδωκαν]{.greek-supplied} κληρους [αυτων]{.greek-omitted} [αυτοις]{.greek-added} και [ε]{.unclear}πεσεν ο κλη[ρος]{.greek-supplied} επι ματθιαν και συγκατεψ[η]{.unclear}[φισθη]{.greek-supplied} [μετ]{.greek-supplied}[α]{.unclear} [των]{.greek-omitted} [το[ν]{.unclear}]{.greek-added} ενδεκα αποστολων[1:26]{.aside}

### Chapter 2

και εν τω συμπληρουσθαι την ημεραν της πεντηκοστης ησαν απαντες [οι]{.greek-added} [αποστολοι]{.greek-added} [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} επι το αυτο[2:1]{.aside}

και εγενετο αφνω εκ του [ουρανου]{.greek-abbr} ηχος ωσπερ φερομενης πνοης βιαιας και επληρ[ω]{.unclear}σεν ολον τον οικον ου ησαν καθημενοι[2:2]{.aside}

και ωφθησαν αυτοις διαμεριζομεναι γλωσσα[ι]{.unclear} ωσει πυρος εκαθισεν τε εφ ενα εκαστον αυτων[2:3]{.aside}

και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ηρξαντο λαλειν ετεραις γλωσσαις καθως το [πνευμα]{.greek-abbr} εδιδου αυτοις αποφθεγγεσθαι[2:4]{.aside}

ησαν δε εν [ιερουσαλημ]{.greek-abbr} κατοικουντες ιουδαιοι ανδρες ευλαβεις απο παντος εθνους των υπο τον [ουρανον]{.greek-abbr}[2:5]{.aside}

γενομενης δε της φωνης ταυτ[η]{.unclear}ς [συνηλθεν]{.greek-omitted} [συνηλθε]{.greek-added} το πληθος και συνεχυθη οτι ηκουον [εις]{.greek-omitted} [ε]{.unclear}καστος τη ιδια διαλεκτω λαλουντων αυτων[2:6]{.aside}

εξισταντο δε παντες και εθαυμαζον λεγοντες προς αλληλους ουκ ιδου παντες ουτοι εισιν οι λαλουντες γαλιλαιοι[2:7]{.aside}

και πως ημεις ακουομεν εκαστος τη ιδια διαλεκτω ημων εν η εγεννηθημεν[2:8]{.aside}

παρθοι και [μη]{.greek-supplied}δοι και ελαμιται και οι κατοικουντες [τη]{.greek-supplied}ν [μεσοποταμιαν]{.greek-omitted} [μεσωποταμιαν]{.greek-added} ιουδαια[ν]{.unclear} τε και κα[ππα]{.greek-supplied}δοκιαν ποντον και την ασιαν[2:9]{.aside}

[φρυ]{.greek-supplied}γιαν τε και παμφυλιαν αιγυπτον [και]{.greek-supplied} τα μερη της λιβυης της κατα κυρηνην και οι [επι]{.greek-supplied}δημουντες ρωμαιοι [ιουδαιοι]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [προσηλυτοι]{.greek-omitted}[2:10]{.aside}

[ιουδαιοι]{.greek-added} [τε]{.greek-added} [κα[ι]{.greek-supplied}]{.greek-added} [[προσηλ]{.greek-supplied}[υ]{.unclear}τοι]{.greek-added} κρητες και [αραβες]{.greek-omitted} [αρραβ[ε]{.unclear}ς]{.greek-added} ακουομεν λαλουντων αυτων ταις ημετεραις γλωσσαις τα μεγαλεια του [θεου]{.greek-abbr}[2:11]{.aside}

εξισταντο δε [παντες]{.greek-omitted} [παν]{.greek-added} και διηπορουν αλλος προς αλλον λεγοντες τι αν θελοι τουτο ειναι[2:12]{.aside}

ετεροι δε χλευαζοντες ελεγον οτι γλευκους μεμεστωμενοι εισιν[2:13]{.aside}

[σταθεις]{.greek-omitted} [εσταθεις]{.greek-added} δε πετρος συν τοις ενδεκα [επηρεν]{.greek-omitted} [επηρε]{.greek-added} την φωνην αυτου και απεφθεγξατο αυτοις ανδρες ιουδαιοι και οι κατοικουντες [ιερουσαλημ]{.greek-abbr} απαντες τουτο υμιν γνωστον εστω και ενωτισασθε τα ρηματα μου[2:14]{.aside}

ου γαρ ως υμεις [υπολαμβανετε]{.greek-omitted} [υπολαμβανεται]{.greek-added} ουτοι [μεθυουσιν]{.greek-omitted} [μεθυουσι]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} γαρ ωρα τριτη της ημερας[2:15]{.aside}

αλλα τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το ειρημενον δια του προφητου ιωηλ[2:16]{.aside}

και εσται εν ταις εσχαταις ημεραις λεγει ο [θεος]{.greek-abbr} εκχεω απο του [πνευματος]{.greek-abbr} μου επι πασαν σαρκα και προφητευσουσιν οι υιοι υμων και αι θυγατερες υμων και οι νεανισκοι υμων ορασεις οψονται και οι πρεσβυτ[ε]{.unclear}ροι υμων ενυπνια ενυπνιασθησονται[2:17]{.aside}

και γε επι τους δουλους μου και επι τας δουλας μου εν ταις ημεραις εκειναις εκχεω απο του [πνευματος]{.greek-abbr} μου και [προφητευσουσιν]{.greek-omitted} [προφητευσουσι]{.greek-added}[2:18]{.aside}

και δωσω τερατα εν τω [ουρανω]{.greek-abbr} ανω και σημεια επι της γης κατω αιμα και πυρ και ατμιδα καπνου[2:19]{.aside}

ο ηλιος [μετα]{.greek-supplied}στραφησεται εις σκοτος και η σεληνη [εις]{.greek-supplied} [αι]{.greek-supplied}μα πριν η ελθειν την ημεραν [κυριου]{.greek-abbr} την μεγαλην και επιφανη[2:20]{.aside}

και εστα[ι]{.greek-supplied} [πα]{.greek-supplied}ς ος αν επικαλεσηται το ονομα [κυριου]{.greek-abbr} σωθησεται[2:21]{.aside}

ανδρες ισραηλιται ακουσατε τους λογους τουτους [ιησουν]{.greek-abbr} τον ναζωραιον ανδρα απο του [θεου]{.greek-abbr} αποδεδειγμενον εις υμας [δυναμεσιν]{.greek-omitted} [δυναμεσι]{.greek-added} και [τερασιν]{.greek-omitted} [τερασι]{.greek-added} και σημειοις οις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δι αυτου ο [θεος]{.greek-abbr} εν μεσω υμων καθως [και]{.greek-omitted} αυτοι οιδατε[2:22]{.aside}

τουτον τη ωρισμενη βουλη και προγνωσει του [θεου]{.greek-abbr} εκδοτον λαβοντες δια χειρων ανομων προσπηξαντες [ανειλετε]{.greek-omitted} [ανειλατε]{.greek-added}[2:23]{.aside}

ον ο [θεος]{.greek-abbr} [ανεστησεν]{.greek-omitted} [ανεστησε]{.greek-added} λυσας τας ωδινας του θανατου καθοτι ουκ ην δυνατον κρατεισθαι αυτον υπ αυτου[2:24]{.aside}

[δαυιδ]{.greek-abbr} γαρ λεγει εις αυτον προωρωμην τον [κυριον]{.greek-abbr} ενωπιον μου δια παντος οτι εκ δεξιων μου εστιν ινα μη σαλευθω[2:25]{.aside}

δια τουτο ευφρανθη η καρδια μου και ηγαλλιασατο η γλωσσα μου ετι δε και η σαρξ μου κατασκηνωσει επ ελπιδι[2:26]{.aside}

οτι ουκ εγκαταλειψεις την ψυχην μου εις [αδου]{.greek-omitted} [αδην]{.greek-added} ουδε δωσεις τον οσιον σου ιδειν διαφθοραν[2:27]{.aside}

εγνωρισας μοι οδους ζωης πληρωσεις με ευφροσυνης μετα του προσωπου σου[2:28]{.aside}

ανδρες αδελφοι [εξον]{.greek-omitted} [εξων]{.greek-added} ειπειν μετα [παρρησιας]{.greek-omitted} [παρρησηας]{.greek-added} προς υμας περι του [πατριαρχου]{.greek-abbr} [δαυιδ]{.greek-abbr} οτι και [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και εταφη και το μνημα αυ[του]{.greek-supplied} εστιν εν ημιν αχρι της ημερας ταυτης[2:29]{.aside}

[π]{.greek-supplied}[ρ]{.unclear}[ο]{.greek-supplied}φητης ουν υπαρχων και ειδως οτι ορκω ωμοσεν αυτω ο [θεος]{.greek-abbr} εκ καρπου της οσφυος αυτου το κατα σαρκα [ανα]{.greek-added} [αναστησειν]{.greek-omitted} [στησειν]{.greek-added} τον [χριστον]{.greek-abbr} καθισαι επι του θρονου αυτου[2:30]{.aside}

[προιδων]{.greek-omitted} [προειδων]{.greek-added} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} περι της αναστασεως του [χριστου]{.greek-abbr} οτι [ου]{.greek-omitted} [ουκ]{.greek-added} [κατελειφθη]{.greek-omitted} [εγκατεληφθη]{.greek-added} η ψυχη αυτου εις [αδου]{.greek-omitted} [αδην]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} η σαρξ αυτου [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[2:31]{.aside}

τουτον τον [ιησουν]{.greek-abbr} ανεστησεν ο [θεος]{.greek-abbr} ου παντες ημεις [μαρτυρες]{.greek-added} εσμεν [μαρτυρες]{.greek-omitted}[2:32]{.aside}

τη δεξια ουν του [θεου]{.greek-abbr} υψωθεις την τε επαγγελιαν του [[πνευματος]{.greek-abbr}]{.greek-added} [του]{.greek-added} αγιου [πνευματος]{.greek-omitted} λαβων παρα του [πατρος]{.greek-abbr} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} τουτο ο [νυν]{.greek-omitted} υμεις βλεπετε και ακουετε[2:33]{.aside}

ου γαρ [δαυιδ]{.greek-abbr} [αυτος]{.greek-added} ανεβη εις τους [ουρανους]{.greek-abbr} λεγει δε αυτος ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου[2:34]{.aside}

εως αν θω τους εχθρους σου υποποδιον των ποδων σου[2:35]{.aside}

ασφαλως ουν γινωσκετω πας οικος [ισραηλ]{.greek-abbr} οτι και [κυριον]{.greek-abbr} [αυτον]{.greek-added} και [χριστον]{.greek-abbr} [αυτον]{.greek-omitted} ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τουτον τον [ιησουν]{.greek-abbr} ον υμεις [εσταυρωσατε]{.greek-abbr}[2:36]{.aside}

ακουσαντες δε κατενυγησαν τη καρδια ειπον τε προς τον πετρον και τους λοιπους αποστολους τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} ανδρες αδελφοι[2:37]{.aside}

πετρος δε εφη προς αυτους μετανοησατε και βαπτισθητω εκαστος υμων επι τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εις αφεσιν αμαρτιων και ληψεσθε την δωρεαν του αγιου [πνευματος]{.greek-abbr}[2:38]{.aside}

υμιν γαρ εστιν η επαγγελια και τοις τεκνοις [υμων]{.greek-omitted} [ημων]{.greek-added} και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εις μακραν οσους αν προσκαλεσηται [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων[2:39]{.aside}

ε[τε]{.greek-supplied}ροις τε λογοις [πλειοσιν]{.greek-omitted} [πλειοσι]{.greek-added} διεμαρτυρε[το]{.greek-supplied} και παρεκαλει λεγων σωθητε απο της γενεας της σκολι[ας]{.greek-supplied} ταυτης[2:40]{.aside}

οι μεν ουν ασμενως αποδεξαμενοι τον λογον αυτου εβαπτισθησαν και προσετεθησαν τη ημερα εκεινη ψυχαι ωσει τρισχιλιαι[2:41]{.aside}

ησαν δε προσκαρτερουντες τη διδαχη των αποστολων και τη κοινωνια και τη κλασει του αρτου και ταις προσευχαις[2:42]{.aside}

εγενετο δε παση ψυχη φοβος πολλα τε τερατα και σημεια δια των αποστολων [εγινετο]{.greek-omitted} [εγενετο]{.greek-added}[2:43]{.aside}

παντες δε οι [πιστευοντες]{.greek-omitted} [πιστευσαντες]{.greek-added} ησαν επι το αυτο και ειχον απαντα κοινα[2:44]{.aside}

και τα κτηματα και τας υπαρξεις επιπρασκον και διεμεριζον αυτα [πασιν]{.greek-omitted} [πασι]{.greek-added} καθοτι αν τις χρειαν [ειχεν]{.greek-omitted} [ειχε]{.greek-added}[2:45]{.aside}

καθ ημεραν τε προσκαρτερουντες [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} εν τω ιερω κλωντες τε κατ οικον αρτον μετελαμβανον τροφης εν αγαλλιασει και αφελοτητι καρδιας[2:46]{.aside}

αινουντες τον [θεον]{.greek-abbr} και εχοντες χαριν προς ολον τον λαον ο δε [κυριος]{.greek-abbr} προσετιθει τους σωζομενους καθ ημεραν τη εκκλησια[2:47]{.aside}

### Chapter 3

επι το αυτο δε πετρος και ιωαννης ανεβαινον εις το ιερον επι την ωραν της προσευχης την [ενατην]{.greek-omitted} [εννατην]{.greek-added}[3:1]{.aside}

και τις ανηρ χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων εβασταζετο ον ετιθουν καθ ημεραν προς την θυραν του ιερου την λε[γο]{.greek-supplied}μενην ωραιαν του αιτειν ελεημοσυ[νην]{.greek-supplied} παρα των εισπορευομενων εις το ιερον[3:2]{.aside}

ος ιδων πετρον και ιωαννην μελλοντας εισιεναι εις το ιερον ηρωτα [ε]{.greek-added} [ελεημοσυνην]{.greek-omitted} [λεημοσυνην]{.greek-added}[3:3]{.aside}

ατενισας δε πετρος εις αυτον συν τω ιωαννη [ειπεν]{.greek-omitted} [ειπε]{.greek-added} βλεψον εις ημας[3:4]{.aside}

ο δε [επειχεν]{.greek-omitted} [επεισχεν]{.greek-added} αυτοις προσδοκων τι παρ αυτων λαβειν[3:5]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε [πετρος]{.greek-omitted} [πετρς]{.greek-added} αργυριον και χρυσιον ουχ υπαρχει μοι ο δε εχω τουτο σοι διδωμι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου εγειραι και περιπατει[3:6]{.aside}

και πιασας αυτον της δεξιας χειρος [ηγειρεν]{.greek-omitted} [ηγειρε]{.greek-added} παραχρημα δε εστερεωθησαν αυτου αι βασεις και τα σφυρα[3:7]{.aside}

και εξαλλομενος εστη και περιεπατει και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} συν αυτοις [περιπατων]{.greek-added} εις το ιερον [περιπατων]{.greek-omitted} και αλλομενος και αινων τον [θεον]{.greek-abbr}[3:8]{.aside}

και ειδεν αυτον πας ο λαος περιπατουντα και αινουντα τον [θεον]{.greek-abbr}[3:9]{.aside}

επεγινωσκον τε αυτον οτι ουτος ην ο προς την ελεημοσυνην καθημενος επι τη ωραια πυλη του ιερου και επλησθησαν θαμβους και εκστασεως επι τω συμβεβηκοτι αυτω[3:10]{.aside}

κρατουντος δε του [ιαθεντος]{.greek-omitted} [ιθεντος]{.greek-added} χωλου τον πετρον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} συνεδραμεν προς αυτους πας ο λαος επι τη στοα τη καλουμενη σολομωντος εκθαμβοι[3:11]{.aside}

ιδων δε [ο]{.greek-added} πετρος απεκρινατο προς τον λαον ανδρες ισραηλιται τι θαυμαζετε επι τουτω η ημιν τι ατενιζετε ως ιδια δυναμει η ευσεβεια [πεποιηκοσιν]{.greek-omitted} [πεποιηκοσι]{.greek-added} του περιπατειν αυτον[3:12]{.aside}

ο [θεος]{.greek-abbr} αβρααμ και ισαακ και ιακωβ ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων [εδοξασεν]{.greek-omitted} [εδοξασε]{.greek-added} τον παιδα αυτου ιησουν ον υμεις μεν [παρεδωκατε]{.greek-omitted} [παρεδεδωκατε]{.greek-added} και ηρνησασθε αυτον κατα προσωπον πιλατου κριναντος εκεινου απολυειν[3:13]{.aside}

υμεις δε τον αγιον και δικαιον ηρνησασθε και ητησασθε ανδρα φονεα χαρισθηναι υμιν[3:14]{.aside}

τον δε αρχηγον της ζωης απεκτεινατε ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων ου ημεις μαρτυρες εσμεν[3:15]{.aside}

και επι τη πιστει του ονοματος αυτου τουτον ον θεωρειτε και οιδατε [εστερεωσεν]{.greek-omitted} [εστερεωσε]{.greek-added} το ονομα αυτου και η πιστις η δι αυτου εδωκεν αυτω την ολοκληριαν ταυτην απεναντι παντων υμων[3:16]{.aside}

και νυν αδελφοι οιδα οτι κατα αγνοιαν επραξατε ωσπερ και οι αρχοντες υμων[3:17]{.aside}

ο δε [θεος]{.greek-abbr} α [προκατηγγειλεν]{.greek-omitted} [προκατηγγειλε]{.greek-added} δια στοματος παντων των προφητων αυτου παθειν τον [χριστον]{.greek-abbr} επληρωσεν ουτως[3:18]{.aside}

μετανοησατε ουν και επιστρεψατε εις το εξαλειφθηναι υμων τας αμαρτιας [οπως]{.greek-omitted} [αν]{.greek-omitted} [ελθωσιν]{.greek-omitted} [καιροι]{.greek-omitted} [αναψυξεως]{.greek-omitted} [απο]{.greek-omitted} [προσωπου]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted}[3:19]{.aside}

[οπως]{.greek-added} [αν]{.greek-added} [ελθωσι]{.greek-added} [καιροι]{.greek-added} [αναψυξεως]{.greek-added} [απο]{.greek-added} [προσωπου]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} και αποστειλη τον προκεχειρισμενον υμιν [[ιησουν]{.greek-abbr}]{.greek-added} [χριστον]{.greek-abbr} [ιησουν]{.greek-omitted}[3:20]{.aside}

ον δει [ουρανον]{.greek-abbr} μεν δεξασθαι αχρι χρονων αποκαταστασεως παντων ων ελαλησεν ο [θεος]{.greek-abbr} δια στοματος παντων των αγιων αυτου [προφητων]{.greek-omitted} [των]{.greek-added} απ αιωνος [προφητων]{.greek-added}[3:21]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} μεν [γαρ]{.greek-omitted} [ειπε]{.greek-added} προς τους [πατερας]{.greek-abbr} [ειπεν]{.greek-omitted} [ημων]{.greek-added} οτι προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων εκ [των]{.greek-omitted} [τω]{.greek-added} αδελφων υμων ως εμε αυτου ακουσεσθε κατα παντα οσα αν [λαληση]{.greek-omitted} [λαλησει]{.greek-added} προς υμας[3:22]{.aside}

εσται δε πασα ψυχη ητις [εαν]{.greek-omitted} [αν]{.greek-added} μη ακουση του [προφητου]{.greek-omitted} [φητου]{.greek-added} εκεινου εξολοθρευθησεται εκ του λαου[3:23]{.aside}

και παντες δε οι προφηται απο σαμουηλ και των καθεξης οσοι ελαλησαν και [κατηγγειλαν]{.greek-omitted} [προκατηγγειλαν]{.greek-added} τας ημερας ταυτας[3:24]{.aside}

υμεις εστε υιοι των προφητων και της διαθηκης ης διεθετο ο [θεος]{.greek-abbr} προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} λεγων προς αβρααμ και εν τω σπερματι σου ενευλογηθησονται πασαι αι [πατριαι]{.greek-abbr} της γης[3:25]{.aside}

υμιν πρωτον ο [θεος]{.greek-abbr} αναστησας τον παιδα αυτου [ιησουν]{.greek-abbr} απεστειλεν αυτον ευλογουντα υμας εν τω αποστρεφειν εκαστον [υμων]{.greek-added} απο των πονηριων [υμων]{.greek-omitted} [αυτου]{.greek-added}[3:26]{.aside}

### Chapter 4

λαλουντων δε αυτων προς τον λαον επεστησαν αυτοις οι ιερεις και ο στρατηγος του ιερου και οι σαδδουκαιοι[4:1]{.aside}

διαπονουμενοι δια το διδασκειν αυτους τον λαον και καταγγελλειν εν τω [ονοματι]{.greek-added} [ιησου]{.greek-abbr} την αναστασιν [των]{.greek-omitted} [την]{.greek-added} [εκ]{.greek-added} νεκρων[4:2]{.aside}

και [επεβαλον]{.greek-omitted} [επεβαλλον]{.greek-added} αυτοις [τας]{.greek-omitted} χειρας και εθεντο [αυτους]{.greek-added} εις τηρησιν εις την αυριον ην γαρ εσπερα ηδη[4:3]{.aside}

πολλοι δε των ακουσαντων τον λογον επιστευσαν και [εγενηθη]{.greek-omitted} [εγενετο]{.greek-added} ο αριθμος [των]{.greek-omitted} [τον]{.greek-added} [αδρων]{.greek-added} [ανδρων]{.corr} ωσει χιλιαδες πεντε[4:4]{.aside}

εγενετο δε επι την αυριον συναχθηναι αυτων τους αρχοντας και [τους]{.greek-added} πρεσβυτερους και γραμματεις [εις]{.greek-omitted} [εν]{.greek-added} [ιερουσαλημ]{.greek-abbr}[4:5]{.aside}

και ανναν τον αρχιερεα και καιαφαν και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και αλεξανδρον και οσοι ησαν εκ γενους αρχιερατικου[4:6]{.aside}

και στησαντες αυτους εν μεσω επυνθανοντο εν ποια δυναμει η εν ποιω ονοματι εποιησατε τουτο υμεις[4:7]{.aside}

τοτε πετρος πλησθεις [πνευματος]{.greek-abbr} αγιου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους αρχοντες του λαου και πρεσβυτεροι του [ισραηλ]{.greek-abbr}[4:8]{.aside}

ει ημεις σημερον ανακρινομεθα επι ευεργεσια [ανθρωπου]{.greek-abbr} ασθενους εν τινι ουτος σεσωσται[4:9]{.aside}

γνωστον εστω πασιν υμιν και παντι τω λαω [ισραηλ]{.greek-abbr} οτι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} του ναζωραιου ον υμεις [εσταυρωσατε]{.greek-abbr} ον ο [θεος]{.greek-abbr} ηγειρεν εκ νεκρων εν [τουτω]{.greek-omitted} [τουτο]{.greek-added} ουτος παρεστηκεν ενωπιον υμων υγιης[4:10]{.aside}

ουτος εστιν ο λιθος ο εξουθενηθεις υφ υμων των οικοδομουντων ο γενομενος εις κεφαλην γωνιας[4:11]{.aside}

και ουκ εστιν εν [αλλω]{.greek-omitted} [αλω]{.greek-added} ουδενι η [σωτηρια]{.greek-abbr} [ουτε]{.greek-omitted} [ουδε]{.greek-added} γαρ ονομα [ετερον]{.greek-added} εστιν [ετερον]{.greek-omitted} [υπο]{.greek-added} [τον]{.greek-added} [[ουρανον]{.greek-abbr}]{.greek-added} το δεδομενον εν [ανθρωποις]{.greek-abbr} [εν]{.greek-omitted} ω δει σωθηναι ημας[4:12]{.aside}

θεωρουντες δε την του πετρου παρρησιαν και ιωαννου και καταλαβομενοι οτι [ανθρωποι]{.greek-abbr} αγραμματοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και ιδιωται εθαυμαζον επεγινωσκον τε αυτους οτι συν τω [ιησου]{.greek-abbr} ησαν[4:13]{.aside}

τον [δε]{.greek-omitted} [τε]{.greek-added} [ανθρωπον]{.greek-abbr} [βλεποντες]{.greek-omitted} [θεωρουντες]{.greek-added} συν αυτοις εστωτα τον τεθεραπευμενον ουδεν ειχον αντειπειν[4:14]{.aside}

κελευσαντες δε αυτους εξω του συνεδριου απελθειν συνεβαλλον προς αλληλους[4:15]{.aside}

λεγοντες τι [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added} τοις [ανθρωποις]{.greek-abbr} τουτοις οτι μεν γαρ γνωστον σημειον [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} δι αυτων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατοικουσιν [ιερουσαλημ]{.greek-abbr} φανερον και ου δυναμεθα [αρνησασθαι]{.greek-omitted} [αρνεισθαι]{.greek-added}[4:16]{.aside}

αλλ [ινα]{.greek-omitted} [ιν]{.greek-added} μη επι πλειον διανεμηθη εις τον λαον απειλη [α]{.greek-added} [απειλησομεθα]{.greek-omitted} [πειλησωμεθα]{.greek-added} [αυτοις]{.greek-omitted} [αυτους]{.greek-added} μηκετι λαλειν επι τω ονοματι τουτω μηδενι [ανθρωπων]{.greek-abbr}[4:17]{.aside}

και [καλεσαντες]{.greek-omitted} [καλεσαντας]{.greek-added} αυτους παρηγγειλαν [αυτοις]{.greek-omitted} το καθολου μη φθεγγεσθαι μηδε διδασκειν επι τω ονοματι του [ιησου]{.greek-abbr}[4:18]{.aside}

ο δε πετρος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} αποκριθεντες [ειπον]{.greek-added} προς αυτους [ειπον]{.greek-omitted} ει δικαιον εστιν ενωπιον του [θεου]{.greek-abbr} υμων ακουειν μαλλον η του [θεου]{.greek-abbr} κρινατε[4:19]{.aside}

ου δυναμεθα γαρ ημεις α [ειδομεν]{.greek-omitted} [ειδ[α]{.unclear}μεν]{.greek-added} [και]{.greek-omitted} [ηκουσαμεν]{.greek-omitted} μη λαλειν[4:20]{.aside}

οι δε προσαπειλησαμενοι απελυσαν αυτους μηδεν ευρισκοντες το πως [κολασονται]{.greek-omitted} [κολασωνται]{.greek-added} αυτους δια τον λαον οτι παντες εδοξαζον τον [θεον]{.greek-abbr} επι τω γεγονοτι[4:21]{.aside}

ετων γαρ ην πλειονων τεσσαρακοντα ο [ανθρωπος]{.greek-abbr} εφ ον εγεγονει το σημειον τουτο της ιασεως[4:22]{.aside}

απολυθεντες δε ηλθον προς τους ιδιους και απηγγειλαν οσα προς αυτους οι αρχιερεις και οι πρεσβυτεροι ειπον[4:23]{.aside}

οι δε ακουσαντες [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} ηραν φωνην προς τον [θεον]{.greek-abbr} και ειπον δεσποτα [συ]{.greek-omitted} [[κυριε]{.greek-abbr}]{.greek-added} ο [θεος]{.greek-abbr} ο ποιησας τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[4:24]{.aside}

ο [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} δια [[πνευματος]{.greek-abbr}]{.greek-added} [αγιου]{.greek-added} στοματος [δαυιδ]{.greek-abbr} παιδος σου ειπων [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} εφρυαξαν εθνη και λαοι εμελετησαν κενα[4:25]{.aside}

παρεστησαν οι βασιλεις της γης και οι αρχοντες συνηχθησαν επι το αυτο κατα του [κυριου]{.greek-abbr} και κατα του [χριστου]{.greek-abbr} αυτου[4:26]{.aside}

συνηχθησαν γαρ επ αληθειας επι τον αγιον παιδα σου [ιησουν]{.greek-abbr} ον εχρισας ηρωδης [τε]{.greek-omitted} και ποντιος πιλατος συν [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και λαοις [ισραηλ]{.greek-abbr}[4:27]{.aside}

ποιησαι οσα η χειρ σου και η [βουλη]{.greek-omitted} [βουλης]{.greek-added} σου [προωρισεν]{.greek-omitted} [προωρισε]{.greek-added} γενεσθαι[4:28]{.aside}

και τα νυν [κυριε]{.greek-abbr} επιδε επι τας απειλας αυτων και δος τοις δουλοις σου μετα παρρησιας πασης λαλειν τον λογον σου[4:29]{.aside}

εν τω την χειρα σου εκτεινειν [σε]{.greek-omitted} εις ιασιν και σημεια και τερατα γινεσθαι δια του ονοματος του αγιου παιδος σου [ιησου]{.greek-abbr}[4:30]{.aside}

και δεηθεντων αυτων εσαλευθη ο τοπος εν ω ησαν συνηγμενοι και επλησθησαν απαντες [πνευματος]{.greek-abbr} αγιου και ελαλουν τον λογον του [θεου]{.greek-abbr} μετα παρρησιας[4:31]{.aside}

του δε πληθους των πιστευσαντων ην η καρδια και η ψυχη μια και ουδε εις τι των υπαρχοντων [αυτων]{.greek-omitted} [αυτω]{.greek-added} ελεγεν ιδιον ειναι αλλ ην αυτοις απαντα κοινα[4:32]{.aside}

και μεγαλη δυναμει απεδιδουν [οι]{.greek-added} [αποστολοι]{.greek-added} το μαρτυριον [οι]{.greek-omitted} [αποστολοι]{.greek-omitted} της αναστασεως του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} χαρις τε μεγαλη ην επι παντας αυτους[4:33]{.aside}

ουδε γαρ ενδεης τις υπηρχεν εν αυτοις οσοι γαρ κτητορες χωριων η οικιων υπηρχον πωλουντες εφερον τας τιμας των πιπρασκομενων[4:34]{.aside}

και ετιθουν παρα τους ποδας των αποστολων [διεδιδ[ε]{.unclear}το]{.greek-added} [διεδιδοτο]{.corr} δε εκαστω καθοτι αν τις χρειαν ειχεν[4:35]{.aside}

ιωσης δε ο επικληθεις βαρναβας [απο]{.greek-omitted} [υπο]{.greek-added} των αποστολων ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον υιος παρακλησεως λευιτης κυπριος τω γενει[4:36]{.aside}

υπαρχοντος [αυτω]{.greek-omitted} [αυτου]{.greek-added} αγρου πωλησας [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} το χρημα και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} παρα τους ποδας των αποστολων[4:37]{.aside}

### Chapter 5

ανηρ δε τις ανανιας ονοματι συν [σαπφειρη]{.greek-omitted} [σαπφηρη]{.greek-added} τη γυναικι αυτου [επωλησεν]{.greek-omitted} [επωλησε]{.greek-added} κτημα[5:1]{.aside}

και ενοσφισατο απο της τιμης [συνειδυιας]{.greek-omitted} [συνειδυας]{.greek-added} και της γυναικος αυτου και ενεγκας μερος τι παρα τους ποδας των αποστολων εθηκεν[5:2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε [ο]{.greek-added} πετρος ανανια δια τι επληρωσεν ο σατανας την καρδιαν σου ψευσασθαι σε το [πνευμα]{.greek-abbr} το αγιον και νοσφισασθαι [σε]{.greek-omitted} απο της τιμης του χωριου[5:3]{.aside}

ουχι μενον σοι [εμενεν]{.greek-omitted} [εμενε]{.greek-added} και πραθεν εν τη ση εξουσια [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} τι οτι εθου εν τη καρδια σου το πραγμα τουτο ουκ εψευσω [ανθρωποις]{.greek-abbr} αλλα τω [θεω]{.greek-abbr}[5:4]{.aside}

ακουων δε ο ανανιας τους λογους τουτους πεσων [εξεψυξεν]{.greek-omitted} [εξεψυξε]{.greek-added} και εγενετο φοβος μεγας επι παντας τους ακουοντας ταυτα[5:5]{.aside}

ανασταντες δε οι νεωτεροι συνεστειλαν αυτον και εξενεγκαντες εθαψαν[5:6]{.aside}

εγενετο δε ως ωρων τριων διαστημα και η γυνη αυτου μη ειδυια το γεγονος εισηλθεν[5:7]{.aside}

απεκριθη δε αυτη ο πετρος ειπε μοι ει τοσουτου το χωριον [απεδοσθε]{.greek-omitted} [απεδοσθαι]{.greek-added} η δε ειπεν ναι τοσουτου[5:8]{.aside}

ο δε πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτην τι οτι συνεφωνηθη υμιν πειρασαι το [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} ιδου οι ποδες των θαψαντων τον ανδρα σου επι τη θυρα και [εξοισουσιν]{.greek-omitted} [εξοισουσι]{.greek-added} σε[5:9]{.aside}

[επεσεν]{.greek-omitted} [επεσε]{.greek-added} δε παραχρημα παρα τους ποδας αυτου και εξεψυξεν εισελθοντες δε οι νεανισκοι ευρον αυτην νεκραν και εξενεγκαντες εθαψαν προς τον ανδρα αυτης[5:10]{.aside}

και εγενετο φοβος μεγας εφ ολην την εκκλησιαν και επι παντας τους ακουοντας ταυτα[5:11]{.aside}

δια δε των χειρων των αποστολων [εγινετο]{.greek-omitted} [εγενετο]{.greek-added} σημεια και τερατα εν τω λαω πολλα και ησαν [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} απαντες εν τη στοα [σολομωντος]{.greek-omitted} [σολομωνος]{.greek-added}[5:12]{.aside}

των δε λοιπων ουδεις ετολμα κολλασθαι αυτοις αλλ εμεγαλυνεν αυτους ο λαος[5:13]{.aside}

μαλλον δε προσετιθεντο [οι]{.greek-added} πιστευοντες τω [κυριω]{.greek-abbr} πληθη ανδρων τε και γυναικων[5:14]{.aside}

ωστε [κατα]{.greek-omitted} [και]{.greek-added} [εις]{.greek-added} τας πλατειας εκφερειν τους ασθενεις και τιθεναι επι κλινων και κραββατων ινα ερχομενου πετρου καν η σκια επισκιαση τινι αυτων[5:15]{.aside}

συνηρχετο δε [και]{.greek-omitted} το πληθος των περιξ πολεων εις [ιερουσαλημ]{.greek-abbr} φεροντες ασθενεις και οχλουμενους υπο [πνευματων]{.greek-abbr} ακαθαρτων οιτινες εθεραπευοντο απαντες[5:16]{.aside}

αναστας δε ο αρχιερευς και παντες οι συν αυτω η ουσα αιρεσις των σαδδουκαιων επλησθησαν ζηλου[5:17]{.aside}

και επεβαλον τας χειρας αυτων επι τους αποστολους και εθεντο αυτους εν τηρησει δημοσια[5:18]{.aside}

αγγελος δε [κυριου]{.greek-abbr} δια της νυκτος [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τας θυρας της φυλακης εξαγαγων τε αυτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added}[5:19]{.aside}

πορευεσθε και σταθεντες λαλειτε εν τω ιερω [τω]{.greek-omitted} [λαω]{.greek-omitted} [τον]{.greek-added} [λαον]{.greek-added} παντα τα ρηματα της ζωης ταυτης[5:20]{.aside}

ακουσαντες δε εισηλθον [οι]{.greek-added} [αποστολοι]{.greek-added} υπο τον ορθρον εις το ιερον και εδιδασκον παραγενομενος δε ο αρχιερευς και οι συν αυτω συνεκαλεσαν το συνεδριον και πασαν την γερουσιαν των υιων [ισραηλ]{.greek-abbr} και απεστειλαν εις το [δεσμωτηριον]{.greek-omitted} [δεσμοτηριον]{.greek-added} αχθηναι αυτους[5:21]{.aside}

οι δε υπηρεται παραγενομενοι ουχ ευρον αυτους εν τη φυλακη αναστρεψαντες δε απηγγειλαν[5:22]{.aside}

λεγοντες οτι το μεν [δεσμωτηριον]{.greek-omitted} [δεσμοτηριον]{.greek-added} [ευρομεν]{.greek-omitted} [ευραμεν]{.greek-added} κεκλεισμενον εν παση ασφαλεια και τους φυλακας εστωτας προ των θυρων ανοιξαντες δε εσω ουδενα [ευρομεν]{.greek-omitted} [ευραμεν]{.greek-added}[5:23]{.aside}

ως δε ηκουσαν τους λογους τουτους ο τε ιερευς και ο στρατηγος του ιερου και οι αρχιερεις [διηπορουν]{.greek-omitted} [διυπορουν]{.greek-added} περι αυτων τι αν [γενοιτο]{.greek-omitted} [γενοι]{.greek-added} τουτο[5:24]{.aside}

παραγενομενος δε τις απηγγειλεν αυτοις οτι ιδου οι ανδρες ους [εθεσθε]{.greek-omitted} [εθεσθαι]{.greek-added} εν τη φυλακη εισιν εν τω ιερω εστωτες και διδασκοντες τον λαον[5:25]{.aside}

τοτε απελθων ο στρατηγος συν τοις υπηρεταις ηγαγεν αυτους ου μετα βιας εφοβουντο γαρ τον λαον [ινα]{.greek-omitted} μη λιθασθωσιν[5:26]{.aside}

αγαγοντες δε αυτους εστησαν εν τω συνεδριω και επηρωτησεν αυτους ο αρχιερευς[5:27]{.aside}

λεγων ου παραγγελια παρηγγειλαμεν υμιν μη διδασκειν επι τω ονοματι τουτω και ιδου πεπληρωκατε την [ιερουσαλημ]{.greek-abbr} της διδαχης υμων και [βουλεσθε]{.greek-omitted} [βουλεσθαι]{.greek-added} επαγαγειν εφ ημας το αιμα του [ανθρωπου]{.greek-abbr} τουτου[5:28]{.aside}

αποκριθεις δε πετρος και οι αποστολοι ειπον πειθαρχειν δει [θεω]{.greek-abbr} μαλλον η [ανθρωποις]{.greek-abbr}[5:29]{.aside}

ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων ηγειρεν [ιησουν]{.greek-abbr} ον υμεις διεχειρισασθε κρεμασαντες επι ξυλου[5:30]{.aside}

τουτον ο [θεος]{.greek-abbr} αρχηγον και [σωτηρα]{.greek-abbr} [υψωσεν]{.greek-omitted} [υψωσε]{.greek-added} τη [δε]{.greek-added} [δεξια]{.greek-omitted} [ξια]{.greek-added} αυτου δουναι μετανοιαν τω [ισραηλ]{.greek-abbr} και αφεσιν αμαρτιων[5:31]{.aside}

και ημεις εσμεν αυτου μαρτυρες των ρηματων τουτων και το [πνευμα]{.greek-abbr} δε το αγιον ο εδωκεν ο [θεος]{.greek-abbr} τοις πειθαρχουσιν αυτω[5:32]{.aside}

οι δε [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} διεπριοντο και [εβουλευοντο]{.greek-omitted} [ευουλευοντο]{.greek-added} ανελειν αυτους[5:33]{.aside}

αναστας δε τις εν τω συνεδριω φαρισαιος ονοματι γαμαλιηλ [νομοδιδασκαλος]{.greek-omitted} [νμοδιδασκαλος]{.greek-added} τιμιος παντι τω λαω εκελευσεν εξω βραχυ [τι]{.greek-omitted} τους αποστολους ποιησαι[5:34]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε προς αυτους ανδρες ισραηλιται προσεχετε εαυτοις επι τοις [ανθρωποις]{.greek-abbr} τουτοις τι μελλετε πρασσειν[5:35]{.aside}

προ γαρ τουτων των ημερων ανεστη θευδας λεγων ειναι τινα εαυτον [μεγαν]{.greek-added} ω [προσεκληθη]{.greek-omitted} [προσεκολληθη]{.greek-added} αριθμος ανδρων [ωσει]{.greek-omitted} [ως]{.greek-added} τετρακοσιων ος ανηρεθη και παντες οσοι επειθοντο αυτω διελυθησαν και εγενοντο εις ουδεν[5:36]{.aside}

μετα [τουτον]{.greek-omitted} [τουτο]{.greek-added} ανεστη ιουδας ο γαλιλαιος εν ταις ημεραις της απογραφης και απεστησεν λαον ικανον οπισω αυτου κακεινος απωλετο και παντες οσοι επειθοντο αυτω διεσκορπισθησαν[5:37]{.aside}

και τα νυν λεγω υμιν αποστητε απο των [ανθρωπων]{.greek-abbr} τουτων και εασατε αυτους οτι εαν η εξ [ανθρωπων]{.greek-abbr} η βουλη [αυτη]{.greek-added} η το εργον τουτο καταλυθησεται[5:38]{.aside}

ει δε εκ [θεου]{.greek-abbr} εστιν ου [δυνασθε]{.greek-omitted} [δυνησεσθε]{.greek-added} καταλυσαι [αυτο]{.greek-omitted} [αυτω]{.greek-added} μηποτε και θεομαχοι ευρεθητε [επεισθησαν]{.greek-added} [δε]{.greek-added} [αυτω]{.greek-added}[5:39]{.aside}

[επεισθησαν]{.greek-omitted} [δε]{.greek-omitted} [αυτω]{.greek-omitted} και προσκαλεσαμενοι τους αποστολους δειραντες παρηγγειλαν μη λαλειν επι τω ονοματι του [ιησου]{.greek-abbr} και απελυσαν αυτους[5:40]{.aside}

οι μεν ουν επορευοντο χαιροντες απο προσωπου του συνεδριου οτι υπερ του ονοματος [του]{.greek-omitted} [ιησου]{.greek-abbr} κατηξιωθησαν ατιμασθηναι[5:41]{.aside}

πασαν τε ημεραν εν τω ιερω και κατ οικον ουκ επαυοντο διδασκοντες και ευαγγελιζομενοι [ιησουν]{.greek-omitted} τον [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added}[5:42]{.aside}

### Chapter 6

εν δε ταις ημεραις ταυταις πληθυνοντων των μαθητων εγενετο γογγυσμος των ελληνιστων προς τους εβραιους οτι παρεθεωρουντο εν τη διακονια τη καθημερινη αι [χηραι]{.greek-omitted} [χειραι]{.greek-added} αυτων[6:1]{.aside}

προσκαλεσαμενοι δε οι δωδεκα το πληθος των [μαθητων]{.greek-omitted} [ματων]{.greek-added} [ειπον]{.greek-omitted} [ειπων]{.greek-added} ουκ αρεστον εστιν ημας καταλειψαντας τον λογον του [θεου]{.greek-abbr} διακονειν τραπεζαις[6:2]{.aside}

[επισκεψασθε]{.corr} [ουν]{.corr} [αδελφοι]{.corr} [ανδρας]{.corr} εξ υμων μαρτυρουμενους επτα [πληρεις]{.greek-omitted} [πληρης]{.greek-added} [πνευματος]{.greek-abbr} αγιου και σοφιας ους [και]{.greek-added} [καταστησωμεν]{.greek-omitted} [καταστησομεν]{.greek-added} επι της χρειας ταυτης[6:3]{.aside}

ημεις δε τη προσευχη και τη διακονια του λογου [προσκαρτερησομεν]{.greek-omitted} [προσκαρτερησωμεν]{.greek-added}[6:4]{.aside}

και ηρεσεν ο λογος ενωπιον [παντος]{.greek-omitted} [τος]{.greek-added} του πληθους και εξελεξαντο στεφανον ανδρα [πληρης]{.greek-omitted} [πληρη]{.greek-added} πιστεως και [πνευματος]{.greek-abbr} αγιου και φιλιππον και προχορον και νικανορα και [τιμωνα]{.greek-omitted} [τιμονα]{.greek-added} και παρμεναν και νικολαον προσηλυτον αντιοχεα[6:5]{.aside}

ους εστησαν ενωπιον των αποστολων και προσευξαμενοι επεθηκαν αυτοις τας χειρας[6:6]{.aside}

και ο λογος του [θεου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και επληθυνετο ο αριθμος των μαθητων εν [ιερουσαλημ]{.greek-abbr} σφοδρα πολυς τε οχλος των [ιερεων]{.greek-omitted} [υπηκουον]{.greek-omitted} [ιουδαιων]{.greek-added} [υ]{.greek-added} [πηον]{.greek-added} τη πιστει[6:7]{.aside}

στεφανος δε πληρης [πιστεως]{.greek-omitted} [χαριτος]{.greek-added} και δυναμεως εποιει τερατα και σημεια μεγαλα εν τω λαω [δια]{.greek-added} [του]{.greek-added} [ονοματος]{.greek-added} [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added}[6:8]{.aside}

ανεστησαν δε τινες των εκ της συναγωγης [της]{.greek-omitted} [των]{.greek-added} [λεγομενης]{.greek-omitted} [λεγομενων]{.greek-added} λιβερτινων και κυρηναιων και αλεξανδρεων και των απο κιλικιας και ασιας συζητουντες τω στεφανω[6:9]{.aside}

και ουκ ισχυον αντιστηναι τη σοφια και τω [πνευματι]{.greek-abbr} ω ελαλει[6:10]{.aside}

τοτε [υπεβαλον]{.greek-omitted} [υπεβαλλον]{.greek-added} ανδρας [ψευδεις]{.greek-added} λεγοντας οτι ακηκοαμεν αυτου λαλουντος ρηματα βλασφημα εις μωσην και τον [θεον]{.greek-abbr}[6:11]{.aside}

[σ]{.unclear}υνεκινησαν τε τον λαον και τους πρεσβυτερους και [τους]{.greek-omitted} γραμματεις και επισταντες [συνηρπασαν]{.greek-omitted} [συνηρπαν]{.greek-added} αυτον και ηγαγον εις το συνεδριον[6:12]{.aside}

εστησαν τε μαρτυρας ψευδεις λεγοντας ο [ανθρωπος]{.greek-abbr} ουτος ου παυεται [ρηματα]{.greek-omitted} [βλασφημα]{.greek-omitted} [λαλων]{.greek-omitted} κατα του τοπου του [αγιου]{.greek-omitted} [ααγιου]{.greek-added} [τουτου]{.greek-added} και του νομου [λαλων]{.greek-added} [ρηματα]{.greek-added} [βλασφημα]{.greek-added}[6:13]{.aside}

ακηκοαμεν γαρ αυτου λεγοντος οτι [ιησους]{.greek-abbr} ο ναζωραιος ουτος καταλυσει τον τοπον τουτον και αλλαξει τα εθη α παρεδωκεν ημιν [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[6:14]{.aside}

και ατενισαντες εις αυτον απαντες οι καθεζομενοι εν τω συνεδριω ειδον το προσωπον αυτου ωσει προσωπον αγγελου[6:15]{.aside}

### Chapter 7

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο αρχιερευς ει αρα ταυτα ουτως εχει[7:1]{.aside}

ο δε εφη ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε ο [θεος]{.greek-abbr} της δοξης ωφθη τω [πατρι]{.greek-abbr} ημων αβρααμ οντι εν τη μεσοποταμια πριν η [κατοικησαι]{.greek-omitted} [κατηκησαι]{.greek-added} αυτον [εν]{.greek-omitted} [εις]{.greek-added} χαρραν[[7:2 *(lacunose)*]{.lacunose}]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον εξελθ[ε]{.unclear} εκ της γης σου και εκ της συγγενειας σου και δευρο εις γην ην αν σοι δειξω[7:3]{.aside}

τοτε εξελθων εκ γης χαλδαιων κατωκησεν [εν]{.greek-omitted} [εις]{.greek-added} χαρραν κακειθεν μετα το αποθανειν τον [πατερα]{.greek-abbr} αυτου [μετωκισεν]{.greek-omitted} [μετωκησεν]{.greek-added} αυτον εις την γην ταυτην εις ην υμεις νυν κατοικειτε[7:4]{.aside}

και ουκ εδωκεν αυτω κληρονομιαν εν αυτη ουδε βημα ποδος και επηγγειλατο δουναι [αυτω]{.greek-omitted} [αυτην]{.greek-added} εις κατασχεσιν [αυτην]{.greek-omitted} [αυτω]{.greek-added} και τω σπερματι αυτου μετ αυτον ουκ οντος αυτω τεκνου[7:5]{.aside}

[ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δε [ουτως]{.greek-omitted} [αυτω]{.greek-added} ο [θεος]{.greek-abbr} οτι εσται το σπερμα αυτου παροικον εν γη αλλοτρια και δουλωσουσιν αυτο και κακωσουσιν ετη τετρακοσια[7:6]{.aside}

και το εθνος [ω]{.greek-omitted} [ο]{.greek-added} εαν [δουλευσωσιν]{.greek-omitted} [δουλευσουσιν]{.greek-added} κρινω εγω ειπεν ο [θεος]{.greek-abbr} και μετα ταυτα εξελευσονται και [λατρευσουσιν]{.greek-omitted} [λατρευσουσι]{.greek-added} μοι εν τω τοπω τουτω[7:7]{.aside}

και εδωκεν αυτω διαθηκην περιτομης και ουτως [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ και περιετεμεν αυτον τη ημερα τη ογδοη και [ο]{.greek-omitted} ισαακ τον ιακωβ και [ο]{.greek-omitted} ιακωβ τους δωδεκα [πατριαρχας]{.greek-abbr}[7:8]{.aside}

και οι [πατριαρχαι]{.greek-abbr} ζηλωσαντες τον ιωσηφ απεδοντο εις αιγυπτον και ην ο [θεος]{.greek-abbr} μετ αυτου[7:9]{.aside}

και [εξειλετο]{.greek-omitted} [εξειλατο]{.greek-added} αυτον εκ πασων των θλιψεων αυτου και εδωκεν αυτω χαριν και σοφιαν [εναντιον]{.greek-omitted} [εναντι]{.greek-added} φαραω βασιλεως αιγυπτου και κατεστησεν αυτον ηγουμενον επ αιγυπτον και ολον τον οικον αυτου[7:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} δε λιμος εφ ολην [την]{.greek-omitted} [ην]{.greek-added} γην αιγυπτου και χανααν και θλιψις μεγαλη και ουχ ευρισκον χορτασματα οι [πατερες]{.greek-abbr} ημων[7:11]{.aside}

ακουσας δε ιακωβ οντα σιτα εν αιγυπτω [εξαπεστειλεν]{.greek-omitted} [εξαπεστειλε]{.greek-added} τους [πατερας]{.greek-abbr} ημων πρωτον[7:12]{.aside}

και εν τω δευτερω ανεγνωρισθη ιωσηφ τοις αδελφοις αυτου και φανερον εγενετο τω φαραω το γενος του ιωσηφ[7:13]{.aside}

αποστειλας δε ιωσηφ μετεκαλεσατο τον [πατερα]{.greek-abbr} αυτου ιακωβ και πασαν την συγγενειαν [αυτου]{.greek-added} εν [ευδομηκοντα]{.greek-added} [πεντε]{.greek-added} ψυχαις [εβδομηκοντα]{.greek-omitted} [πεντε]{.greek-omitted}[7:14]{.aside}

κατεβη δε ιακωβ εις αιγυπτον και ετελευτησεν αυτος και οι [πατερες]{.greek-abbr} ημων[7:15]{.aside}

και μετετεθησαν εις συχεμ και ετεθησαν εν τω μνηματι ο ωνησατο αβρααμ τιμης αργυριου παρα των υιων [εμμορ]{.greek-omitted} [εμμωρ]{.greek-added} του συχεμ[7:16]{.aside}

καθως δε ηγγιζεν ο χρονος της [επαγγελιας]{.greek-omitted} [επαγγελειας]{.greek-added} ης ωμοσεν ο [θεος]{.greek-abbr} τω αβρααμ ηυξησεν ο λαος και επληθυνθη εν αιγυπτω[7:17]{.aside}

[αχρι]{.greek-omitted} [αχρις]{.greek-added} ου ανεστη βασιλευς ετερος ος ουκ ηδει τον ιωσηφ[7:18]{.aside}

ουτος κατασοφισαμενος το γενος ημων [εκακωσεν]{.greek-omitted} [εκακωσε]{.greek-added} τους [πατερας]{.greek-abbr} ημων του ποιειν εκθετα τα βρεφη αυτων εις το μη ζωογονεισθαι[7:19]{.aside}

εν ω καιρω εγεννηθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ην αστειος τω [θεω]{.greek-abbr} ος ανετραφη μηνας τρεις εν τω οικω του [πατρος]{.greek-abbr} [αυτου]{.greek-added}[7:20]{.aside}

εκτεθεντα δε αυτον [ανειλετο]{.greek-omitted} [ανειλατο]{.greek-added} η θυγατηρ φαραω και ανεθρεψατο αυτον εαυτη εις υιον[7:21]{.aside}

και επαιδευθη [μωσης]{.greek-omitted} [μωυσης]{.greek-added} παση σοφια αιγυπτιων ην δε δυνατος εν [εργοις]{.greek-added} [και]{.greek-added} λογοις [και]{.greek-omitted} [εργοις]{.greek-omitted}[7:22]{.aside}

ως δε [επληρουτο]{.greek-omitted} [επληρουτω]{.greek-added} αυτω τεσσαρακονταετης χρονος ανεβη επι την καρδιαν αυτου επισκεψασθαι τους αδελφους αυτου τους υιους [ισραηλ]{.greek-abbr}[7:23]{.aside}

και ιδων τινα αδικουμενον ημυνατο [αυτο]{.greek-added} και εποιησεν εκδικησιν τω καταπονουμενω παταξας τον αιγυπτιον[7:24]{.aside}

[ενομιζεν]{.greek-omitted} [ενομιζε]{.greek-added} δε συνιεναι τους αδελφους αυτου οτι ο [θεος]{.greek-abbr} δια χειρος αυτου διδωσιν αυτοις [σωτηριαν]{.greek-abbr} οι δε ου σ[υ]{.unclear}νηκαν[7:25]{.aside}

τη τε επιουση ημερα ωφθη αυτοις μαχομενοις και [συνηλασεν]{.greek-omitted} [συνηλλασεν]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} [εις]{.greek-omitted} ειρηνην ειπων ανδρες αδελφοι εστε υμεις [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} αδικειτε αλληλους[7:26]{.aside}

ο δε αδικων τον πλησιον απωσατο αυτον ειπων τις σε κατεστησεν αρχοντα και δικαστην εφ [ημας]{.greek-omitted} [ημων]{.greek-added}[7:27]{.aside}

μη ανελειν με συ θελεις ον τροπον ανειλες χθες τον αιγυπτιον[7:28]{.aside}

[εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} δε μωσης εν τω λογω τουτω και εγενετο παροικος εν γη μαδιαμ ου εγεννησεν υιους δυο[7:29]{.aside}

και πληρωθεντων ετων τεσσαρακοντα ωφθη αυτω εν τη ερημω του ορους σινα αγγελος [κυριου]{.greek-abbr} εν φλογι πυρος βατου[7:30]{.aside}

ο δε μωσης ιδων [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} το οραμα προσερχομενου δε αυτου κατανοησαι εγενετο φωνη [κυριου]{.greek-abbr} προς αυτον[7:31]{.aside}

εγω ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} σου ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ εντρομος δε γενομενος μωσης ουκ [ε]{.greek-added} [ετολμα]{.greek-omitted} [τολμα]{.greek-added} κατανοησαι[7:32]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε α[υ]{.unclear}τω ο [κυριος]{.greek-abbr} λυσον το υποδημα [εκ]{.greek-added} των ποδων σου ο γαρ τοπος εν ω εστηκας γη αγια εστιν[7:33]{.aside}

ιδων ειδον την κακωσιν του λαου μου του εν αιγυπτω και του στεναγμου αυτων ηκουσα και κατεβην εξελεσθαι αυτους και νυν δευρο αποστελω σε εις αιγυπτον[7:34]{.aside}

τουτον τον [μωσην]{.greek-omitted} [μωυσην]{.greek-added} ον [ηρνησαντο]{.greek-omitted} [ηρνουντο]{.greek-added} ειποντες τις σε κατεστησεν αρχοντα και δικαστην [[ε]{.unclear}φ]{.greek-added} [ημας]{.greek-added} τουτον ο [θεος]{.greek-abbr} αρχοντα και λυτρωτην απεστειλεν [εν]{.greek-omitted} [συν]{.greek-added} χειρι αγγελου του οφθεντος αυτω εν τη βατω[7:35]{.aside}

ουτος εξηγαγεν αυτους ποιησας τερατα και σημεια εν γη αιγυπτω και εν ερυθρα θαλασση και εν τη ερημω ετη τεσσαρακοντα[7:36]{.aside}

ουτος εστιν ο [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ο ειπων τοις υιοις [ισραηλ]{.greek-abbr} προφητην υμιν αναστησει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} εκ των αδελφων υμων ως εμε [αυτου]{.greek-added} [ακουσεσθε]{.greek-added}[7:37]{.aside}

ουτος εστιν ο γενομενος εν τη εκκλησια εν τη ερημω μετα του αγγελου του λαλουντος αυτω εν τω ορει σινα και των [πατερων]{.greek-abbr} ημων ος εδεξατο [λογον]{.greek-omitted} [λογια]{.greek-added} ζωντα δουναι ημιν[7:38]{.aside}

ω ουκ ηθελησαν υπηκοοι γενεσθαι οι [πατερες]{.greek-abbr} ημων αλλ απωσαντο και εστραφησαν τη καρδια αυτων εις αιγυπτον[7:39]{.aside}

ειποντες τω ααρων ποιησον ημιν θεους οι προπορευσονται ημων ο γαρ [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ουτος ος εξηγαγεν ημας εκ γης αιγυπτου ουκ οιδαμεν τι γεγονεν αυτω[7:40]{.aside}

και εμοσχοποιησαν εν ταις ημεραις εκειναις και ανηγαγον θυσιαν τω ειδωλω και [ευφραινοντο]{.greek-omitted} [ηυφραινοντο]{.greek-added} εν τοις εργοις των χειρων αυτων[7:41]{.aside}

[εστρεψεν]{.greek-omitted} [εστρεψε]{.greek-added} δε ο [θεος]{.greek-abbr} και παρεδωκεν αυτους λατρευειν τη στρατια του [ουρανου]{.greek-abbr} καθως γεγραπται εν βιβλω των προφητων μη σφαγια και θυσιας προσηνεγκατε μοι ετη τεσσαρακοντα εν τη ερημω οικος [ισραηλ]{.greek-abbr}[7:42]{.aside}

και ανελαβετε την σκηνην του μολοχ και το αστ[ρο]{.unclear}[ν]{.greek-supplied} του [θεου]{.greek-abbr} υμων [ρεμφαν]{.greek-omitted} [ραφαν]{.greek-added} τους τυπους ους εποιησατε προσκυνειν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [νυν]{.greek-added} μετοικιω υμας επεκεινα βαβυλωνος[7:43]{.aside}

η σκηνη του μαρτυριου ην τοις πατρασιν ημων εν τη ερημω καθως διεταξατο ο λαλων τω [μωση]{.greek-omitted} [μωυση]{.greek-added} ποιησαι αυτην κατα τον τυπον ον εωρακει[7:44]{.aside}

ην και εισηγαγον διαδεξαμενοι οι [πατερες]{.greek-abbr} ημων μετα [ιησου]{.greek-abbr} εν τη κατασχεσει των εθνων ων [εξωσεν]{.greek-omitted} [εξεωσεν]{.greek-added} ο [θεος]{.greek-abbr} απο προσωπου των πατερων ημων εως των ημερων [δαυιδ]{.greek-abbr}[7:45]{.aside}

ος ευρεν χαριν ενωπιον του [θεου]{.greek-abbr} και ητησατο ευρειν σκηνωμα τω [θεω]{.greek-abbr} ιακωβ[7:46]{.aside}

σολομων δε ωκοδομησεν [αυτω]{.greek-omitted} [εαυτω]{.greek-added} οικον[7:47]{.aside}

αλλ ουχ ο υψιστος εν χειροποιητοις ναοις κατοικει καθως ο προφητης λεγει[7:48]{.aside}

ο [ουρανος]{.greek-abbr} μοι θρονος η δε γη υποποδιον των ποδων μου ποιον οικον [οικοδομησετε]{.greek-omitted} [οικοδομησεται]{.greek-added} μοι λεγει [κυριος]{.greek-abbr} η τις τοπος της καταπαυσεως μου [εστιν]{.greek-added}[7:49]{.aside}

ουχι η χειρ μου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} ταυτα παντα[7:50]{.aside}

σκληροτραχηλοι και απεριτμητοι τη καρδια και τοις ωσιν υμεις αει τω [πνευματι]{.greek-abbr} τω αγιω [αντιπιπτετε]{.greek-omitted} [αντιπιπτεται]{.greek-added} ως οι [πατερες]{.greek-abbr} υμων και υμεις[7:51]{.aside}

τινα των προφητων ουκ εδιωξαν οι πατερες υμων και απεκτειναν τους προκαταγγειλαντας περι της ελευσεως του δικαιου ου νυν υμεις προδοται και φο[ν]{.unclear}εις [γεγενησθε]{.greek-omitted} [εγενεσθε]{.greek-added}[7:52]{.aside}

οιτινες ελαβετε τον νομον εις διαταγας αγγελων και ουκ εφυλαξατε[7:53]{.aside}

ακουοντες δε ταυτα διεπριοντο ταις καρδιαις αυτων και εβρυχον τους οδοντας επ αυτον[7:54]{.aside}

υπαρχων δε πληρης [πνευματος]{.greek-abbr} αγιου ατενισας εις τον [ουρανον]{.greek-abbr} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} δοξαν [θεου]{.greek-abbr} και [ιησουν]{.greek-abbr} εστωτα εκ δεξιων του [θεου]{.greek-abbr}[7:55]{.aside}

και ειπεν ιδου θεωρω τους [ουρανους]{.greek-abbr} ανεωγμενους και τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων εστωτα του [θεου]{.greek-abbr}[7:56]{.aside}

κραξαντες δε φωνη μεγαλη συνεσχον τα ωτα αυτων και ωρμησαν [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} επ αυτον[7:57]{.aside}

και εκβαλοντες [αυτον]{.greek-added} εξω της πολεως ελιθοβολουν και οι μαρτυρες απεθεντο τα ιματια [αυτων]{.greek-added} παρα τους ποδας νεανιου καλουμενου σαυλου[7:58]{.aside}

και ελιθοβολουν τον στεφανον επικαλουμενον και λεγοντα [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added} δεξαι το [πνευμα]{.greek-abbr} μου[7:59]{.aside}

θεις δε τα γονατα [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη [κυριε]{.greek-abbr} μη στησης αυτοις την αμαρτιαν ταυτην και τουτο ειπων εκοιμηθη[7:60]{.aside}

### Chapter 8

σαυλος δε ην συνευδοκων τη αναιρεσει αυτου εγενετο δε εν εκεινη τη ημερα διωγμος μεγας επι την εκκλησιαν την εν ιεροσολυμοις [και]{.greek-added} παντες [δε]{.greek-omitted} διεσπαρησαν κατα τας χωρας της ιουδαιας και σαμαρειας πλην των αποστολων[8:1]{.aside}

συνεκομισαν δε τον στεφανον ανδρες ευλαβεις και [εποιησαντο]{.greek-omitted} [εποιησαν]{.greek-added} κοπετον μεγαν επ αυτω[8:2]{.aside}

σαυλος δε ελυμαινετο την εκκλησιαν κατα τους οικο[υς]{.unclear} εισπορευομενος συρων τε ανδρας και γυναικας παρεδιδου εις φυλακην[8:3]{.aside}

οι μεν ουν διασπαρεντες διηλθον ευαγγελιζομενοι τον λογον[8:4]{.aside}

φιλιππος δε κατελθων εις πολιν της σαμαρειας εκηρυσσεν αυτοις τον [χριστον]{.greek-abbr}[8:5]{.aside}

προσειχον [τε]{.greek-omitted} [δε]{.greek-added} οι οχλοι τοις λεγομενοις υπο του φιλιππου [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} εν τω ακουειν αυτους και βλεπειν τα σημεια α εποιει[8:6]{.aside}

πολλων γαρ των εχοντων πνευματα ακαθαρτα βοωντα φωνη μεγαλη [εξηρχετο]{.greek-omitted} [εξηρχοντο]{.greek-added} πολλοι δε [και]{.greek-added} παραλελυμενοι και χωλοι εθεραπευθησαν[8:7]{.aside}

και εγενετο χαρα μεγαλη εν τη πολει εκεινη[8:8]{.aside}

ανηρ δε τις ονοματι σιμων προυπηρχεν εν τη πολει μαγευων και εξιστων το εθνος της σαμαρειας λεγων ειναι τινα εαυτον μεγαν[8:9]{.aside}

ω προσειχον [παντες]{.greek-added} απο μικρου εως μεγαλου λεγοντες ουτος εστιν η δυναμις του [θεου]{.greek-abbr} η μεγαλη[8:10]{.aside}

προσειχον [δε]{.greek-omitted} [τε]{.greek-added} αυτω δια το ικανω χρονω ταις μαγειαις εξεστακεναι αυτους[8:11]{.aside}

[οτε]{.greek-omitted} [ως]{.greek-added} δε επιστευσαν τω φιλιππω ευαγγελιζομενω [τα]{.greek-omitted} περι της βασιλειας του [θεου]{.greek-abbr} και του ονοματος [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εβαπτιζοντο ανδρες τε και γυναικες[8:12]{.aside}

ο δε σιμων και αυτος [επιστευσεν]{.greek-omitted} [επιστευσε]{.greek-added} και βαπτισθεις ην προσκαρτερων τω φιλιππω θεωρων τε [σημεια]{.greek-added} [και]{.greek-added} δυναμεις [μεγαλας]{.greek-added} [και]{.greek-omitted} [σημεια]{.greek-omitted} [γινομενα]{.greek-omitted} [γινομε[ν]{.unclear}ας]{.greek-added} εξιστατο[8:13]{.aside}

ακουσαντες δε οι εν ιεροσολυμοις αποστολοι οτι δεδεκται η σαμαρεια τον λογον του [θεου]{.greek-abbr} [απεστειλαν]{.greek-omitted} [εξαπεστειλαν]{.greek-added} προς αυτους [τον]{.greek-omitted} πετρον και ιωαννην[8:14]{.aside}

οιτινες καταβαντες προσηυξαντο περι αυτων οπως [λαβωσιν]{.greek-omitted} [λαβωσι]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:15]{.aside}

[ουπω]{.greek-omitted} [ουδεπω]{.greek-added} γαρ ην επ ουδενι αυτων [επιπεπτωκος]{.greek-omitted} [επεληλυθως]{.greek-added} μονον δε βεβαπτισμενοι υπηρχον εις το ονομα του [χριστου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr}[8:16]{.aside}

τοτε επετιθουν τας χειρας επ αυτους και ελαμβανον [πνευμα]{.greek-abbr} αγιον[8:17]{.aside}

[θεασαμενος]{.greek-omitted} [ιδων]{.greek-added} δε ο σιμων οτι δια της επιθεσεως των χειρων των αποστολων διδοται το [πνευμα]{.greek-abbr} το αγιον προσηνεγκεν αυτοις χρηματα[8:18]{.aside}

λεγων δοτε καμοι την εξουσιαν ταυτην ινα ω εαν επιθω τας χειρας [λαμβανη]{.greek-omitted} [λαμβανει]{.greek-added} [πνευμα]{.greek-abbr} αγιον[8:19]{.aside}

πετρος δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον το αργυριον σου συν σοι ειη εις απωλειαν οτι την δωρεαν του [θεου]{.greek-abbr} ενομισας δια χρηματων κτασθαι[8:20]{.aside}

[ουκ]{.greek-omitted} [ου]{.greek-added} [κ]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} σοι μερις ουδε κληρος εν τω λογω τουτω η γαρ καρδια σου ουκ εστιν ευθεια [ενωπιον]{.greek-omitted} [εναντιον]{.greek-added} του [θεου]{.greek-abbr}[8:21]{.aside}

μετανοησον ουν απο της κακιας σου ταυτης και δεηθητι του [θεου]{.greek-abbr} ει αρα αφεθησεται σοι η επινοια της καρδιας σου[8:22]{.aside}

εις γαρ χολην πικριας και συνδεσμον αδικιας ορω σε οντα[8:23]{.aside}

αποκριθεις δε ο σιμων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δεηθητε υμεις υπερ εμου προς τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} οπως μηδεν επελθη επ εμε ων ειρηκατε[8:24]{.aside}

οι [μ]{.unclear}[ε]{.greek-supplied}[ν]{.unclear} ουν [διαμαρτυραμενοι]{.greek-omitted} [διαμαρτυρομενοι]{.greek-added} και λαλησαντες τον λογον του [κυριου]{.greek-abbr} υπεστρεψαν εις [ιερουσαλημ]{.greek-abbr} πολλας τε κωμας των σαμαρειτων ευηγγελισαντο[8:25]{.aside}

αγγελος δε [κυριου]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} προς φιλιππον λεγων αναστηθι και πορευου κατα μεσημβριαν επι την οδον την καταβαινουσαν απο ιερουσαλημ εις γαζαν αυτη εστιν ερημος[8:26]{.aside}

και αναστας επορευθη και ιδου ανηρ αιθιοψ ευνουχος δυναστης κανδακης [της]{.greek-omitted} βασιλισσης αιθιοπων ος ην επι πασης της γαζης αυτης ος εληλυθει προσκυνησων εις [ιερουσαλημ]{.greek-abbr}[8:27]{.aside}

ην τε υποστρεφων και καθημενος επι του αρματος αυτου [και]{.greek-omitted} [ανεγινωσκεν]{.greek-omitted} [ανεγινωσκε]{.greek-added} τον προφητην ησαιαν[8:28]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε το [πνευμα]{.greek-abbr} τω φιλιππω προσελθε και κολληθητι τω αρματι τουτω[8:29]{.aside}

προσδραμων δε ο φιλιππος ηκουσεν αυτου αναγινωσκοντος [ησαιαν]{.greek-added} τον προφητην [ησαιαν]{.greek-omitted} και ειπεν αρα γε γινωσκεις α αναγινωσκεις[8:30]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πως γαρ αν δυναιμην εαν μη τις οδηγηση [με]{.greek-omitted} [μαι]{.greek-added} [παρεκαλεσαι]{.greek-added} [παρεκαλεσεν]{.greek-omitted} [[παρεκαλεσε]{.corr}]{.greek-added} τε τον φιλιππον αναβαντα καθισαι συν αυτω[8:31]{.aside}

η δε περιοχη της γραφης ην ανεγινωσκεν ην αυτη ως προβατον επι σφαγην ηχθη και ως αμνος εναντιον του [κειροντος]{.greek-omitted} [κειραντος]{.greek-added} αυτον αφωνος [ουτως]{.greek-omitted} [ουτος]{.greek-added} ουκ ανοιγει το στομα αυτου[8:32]{.aside}

εν τη ταπεινωσει αυτου η κρισις αυτου [η]{.unclear}ρθη την δε γενεαν αυτου τις διηγησεται οτι αιρεται απο της γης η ζωη αυτου[8:33]{.aside}

αποκριθεις δε ο ευνουχος τω φιλιππω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δεομαι σου περι τινος ο προφητης λεγει τουτο περι εαυτου η περι ετερου τινος[8:34]{.aside}

ανοιξας δε ο φιλιππος το στομα αυτου και αρξαμενος απο της γραφης ταυτης ευηγγελισατο αυτω τον [ιησουν]{.greek-abbr}[8:35]{.aside}

ως δε επορευοντο κατα την οδον ηλθον επι [τι]{.greek-omitted} [το]{.greek-added} υδωρ και φησιν ο ευνουχος ιδου υδωρ τι κωλυει με βαπτισθηναι[8:36]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} στηναι το αρμα και κατεβησαν [αμφοτεροι]{.greek-omitted} εις το υδωρ [αμφοτεροι]{.greek-added} ο τε φιλιππος και ο ευνουχος και εβαπτισεν αυτον[8:38]{.aside}

οτε δε ανεβησαν [εκ]{.greek-omitted} [απο]{.greek-added} του υδατος [πνευμα]{.greek-abbr} [κυριου]{.greek-abbr} [ηρπασεν]{.greek-omitted} [ηρπασε]{.greek-added} τον φιλιππον και ουκ ειδεν αυτον ουκετι ο ευνουχος επορευετο γαρ την οδον αυτου χαιρων[8:39]{.aside}

φιλιππος δε ευρεθη εις αζωτον και διερχομενος ευηγγελιζετο τας πολεις πασας εως του ελθειν αυτον εις καισαρειαν[8:40]{.aside}

### Chapter 9

ο δε σαυλος ετι εμπνεων απειλης και φονου εις τους μαθητας του [κυριου]{.greek-abbr} προσελθων τω αρχιερει[9:1]{.aside}

ητησατο παρ αυτου επιστολας εις δαμασκον προς τας συναγωγας οπως εαν τινας ευρη της οδου [οντας]{.greek-omitted} ανδρας τε και γυναικας δεδεμενους αγαγη εις [ιερουσαλημ]{.greek-abbr}[9:2]{.aside}

εν δε τω πορευεσθαι [αυτον]{.greek-added} εγενετο αυτον εγγιζειν [τη]{.greek-omitted} [εις]{.greek-added} [δαμασκω]{.greek-omitted} [δαμασκον]{.greek-added} και εξαιφνης περιηστραψεν αυτον φως απο του [ουρανου]{.greek-abbr}[9:3]{.aside}

και πεσων επι την γ[ην]{.greek-supplied} ηκουσεν φωνην λεγουσαν αυτω σαουλ σαουλ τι με διωκεις[9:4]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις ει [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[9:5]{.aside}

αλλα αναστηθι και εισελθε εις την πολιν [και]{.greek-omitted} [κακει]{.greek-added} λαληθησεται σοι τι σε δει ποιειν[9:6]{.aside}

οι δε ανδρες οι συνοδευοντες αυτω [ειστηκεισαν]{.greek-omitted} [ηστηκεισαν]{.greek-added} [ενεοι]{.greek-omitted} [εννεοι]{.greek-added} ακουοντες μεν της φωνης μηδενα δε θεωρουντες[9:7]{.aside}

ηγερθη δε ο σαυλος απο της γης ανεωγμενων [τε]{.greek-omitted} [δε]{.greek-added} των οφθαλμων αυτου ουδενα [εβλεπεν]{.greek-omitted} [εβλεπε]{.greek-added} χειραγωγουντες δε αυτον εισηγαγον εις δαμασκον[9:8]{.aside}

και ην ημερας τρεις μη βλεπων και ουκ εφαγεν ουδε επιεν[9:9]{.aside}

ην δε τις μαθητης εν δαμασκω ονοματι ανανιας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον ο [κυριος]{.greek-abbr} εν οραματι ανανια ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ιδου εγω [κυριε]{.greek-abbr}[9:10]{.aside}

ο δε [κυριος]{.greek-abbr} προς αυτον αναστας πορευθητι επι την ρυμην την καλουμενην ευθειαν και ζητησον εν οικια ιουδα σαυλον ονοματι ταρσεα ιδου γαρ [προ]{.greek-added} [προσευχεται]{.greek-omitted} [σευχεται]{.greek-added}[9:11]{.aside}

και ειδεν εν οραματι ανδρα ονοματι ανανιαν εισελθοντα και επιθεντα αυτω χειρα οπως [αναβλεψη]{.greek-omitted} [αναβλεψει]{.greek-added}[9:12]{.aside}

απεκριθη δε ανανιας [κυριε]{.greek-abbr} ακηκοα απο πολλων περι του ανδρος τουτου οσα κακα [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τοις αγιοις σου εν [ιερουσαλημ]{.greek-abbr}[9:13]{.aside}

και ωδε εχει εξουσιαν παρα των αρχιερεων δησαι παντας τους επικαλουμενους το ονομα σου[9:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτον ο [κυριος]{.greek-abbr} πορευου οτι σκευος εκλογης μοι εστιν ουτος του βαστασαι το ονομα μου ενωπιον εθνων και βασιλεων υιων τε [ισραηλ]{.greek-abbr}[9:15]{.aside}

εγω γαρ υποδειξω αυτω οσα δει αυτον υπερ του ονοματος μου παθειν[9:16]{.aside}

[απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} δε ανανιας και εισηλθεν εις την οικιαν και επιθεις επ αυτον τας χειρας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} σαουλ αδελφε ο [κυριος]{.greek-abbr} [απεσταλκεν]{.greek-omitted} [απεσταλκε]{.greek-added} με [[ιησους]{.greek-abbr}]{.greek-added} ο οφθεις σοι εν τη οδω η ηρχου οπως αναβλεψης και [πλησθης]{.greek-omitted} [πλησθεις]{.greek-added} [πνευματος]{.greek-abbr} αγιου[9:17]{.aside}

και ευθεως [απεπεσον]{.greek-omitted} [απεπεσαν]{.greek-added} απο των οφθαλμων αυτου ωσει λεπιδες [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} τε [παραχρημα]{.greek-added} και αναστας εβαπτισθη[9:18]{.aside}

και λαβων τροφην ενισχυσεν εγενετο δε ο σαυλος μετα των [οντων]{.greek-added} εν [τη]{.greek-added} δαμασκω μαθητων ημερας τινας[9:19]{.aside}

και ευθεως εν ταις συναγωγαις [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} τον [χριστον]{.greek-omitted} [[ιησουν]{.greek-abbr}]{.greek-added} οτι ουτος εστιν ο υιος του [θεου]{.greek-abbr}[9:20]{.aside}

εξισταντο δε παντες οι ακουοντες και ελεγον ουχ ουτος εστιν ο πορθησας εν [ιερουσαλημ]{.greek-abbr} τους επικαλουμενους το ονομα τουτο και ωδε εις τουτο [εληλυθεν]{.greek-omitted} [εληλυθει]{.greek-added} ινα δεδεμενους αυτους [αγαγη]{.greek-omitted} [αγαγει]{.greek-added} επι τους αρχιερεις[9:21]{.aside}

σαυλος δε μαλλον ενεδυναμουτο και [συνεχυνεν]{.greek-omitted} [συνεχυνε]{.greek-added} τους ιουδαιους τους κατοικουντας εν δαμασκω συμβιβαζων οτι ουτος εστιν ο [χριστος]{.greek-abbr}[9:22]{.aside}

ως δε επληρουντο ημεραι ικαναι συνεβουλευσαντο οι ιουδαιοι ανελειν αυτον[9:23]{.aside}

εγνωσθη δε τω σαυλω η επιβουλη αυτων παρετηρουν τε τας πυλας ημερας [τε]{.greek-omitted} και νυκτος οπως αυτον [ανελωσιν]{.greek-omitted} [ανελωσι]{.greek-added}[9:24]{.aside}

λαβοντες δε αυτον οι [μα]{.unclear}θηται νυκτος καθηκαν [αυτον]{.greek-added} δια του τειχους χαλασαντες εν σπυριδι[9:25]{.aside}

παραγενομενος δε ο σαυλος εν [ιερουσαλημ]{.greek-abbr} επειρατο κολλασθαι τοις μαθηταις και παντες εφοβουντο αυτον μη πιστευοντες οτι [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης[9:26]{.aside}

βαρναβας δε επιλαβομενος αυτον [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} προς τους αποστολους και διηγησατο αυτοις πως εν τη οδω [ειδεν]{.greek-omitted} [ειδε]{.greek-added} τον [κυριον]{.greek-abbr} και οτι ελαλησεν αυτω και πως εν δαμασκω επαρρησιασατο εν τω ονοματι [του]{.greek-omitted} [ιησου]{.greek-abbr}[9:27]{.aside}

και ην μετ αυτων εισπορευομενος [και]{.greek-added} [εκπορευομενος]{.greek-added} εις [ιερουσαλημ]{.greek-abbr} [και]{.greek-omitted} παρρησιαζομενος εν τω ονοματι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[9:28]{.aside}

ελαλει τε και συνεζητει προς τους ελληνιστας οι δε επεχειρουν αυτον ανελειν[9:29]{.aside}

επιγνοντες δε οι αδελφοι κατηγαγον αυτον εις καισαρειαν και εξαπεστειλαν αυτον εις ταρσον[9:30]{.aside}

[αι]{.greek-omitted} [η]{.greek-added} μεν ουν [εκκλησιαι]{.greek-omitted} [εκκλησια]{.greek-added} καθ ολης της ιουδαιας και γαλιλαιας και σαμαρειας [ειχον]{.greek-omitted} [ειχεν]{.greek-added} ειρηνην [οικοδομουμεναι]{.greek-omitted} [οικοδομουμενη]{.greek-added} και [πορευομεναι]{.greek-omitted} [πορευομενη]{.greek-added} τω φοβω [του]{.greek-omitted} [κυριου]{.greek-abbr} και τη παρακλησει του αγιου [πνευματος]{.greek-abbr} [επληθυνοντο]{.greek-omitted} [επληθυνετο]{.greek-added}[9:31]{.aside}

εγενετο δε πετρον διερχομενον δια παντων κατελθειν και προς τους αγιους τους κατοικουντας [λυδδαν]{.greek-omitted} [λυδδα]{.greek-added}[9:32]{.aside}

[ευρεν]{.greek-omitted} [ευρε]{.greek-added} δε εκει [ανθρωπον]{.greek-abbr} τινα [ονοματι]{.greek-added} αινεαν [ονοματι]{.greek-omitted} εξ ετων οκτω κατακειμενον επι κραββατω ος ην παραλελυμενος[9:33]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ιησους]{.greek-omitted} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον [σε]{.unclear}αυτω και ευθεως ανεστη[9:34]{.aside}

και ειδον αυτον παντες οι κατοικουντες [λυδδαν]{.greek-omitted} [λυδδα]{.greek-added} και τον ασσαρωνα οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} η διερμηνευομενη λεγεται δορκας αυτη ην πληρης αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν εν [τω]{.greek-added} υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν [δυο]{.greek-added} [ανδρας]{.greek-added} προς αυτον παρακαλουντες μη οκνησαι διελθειν εως αυτων[9:38]{.aside}

αναστας δε πετρος συνηλθ[εν]{.unclear} αυτοις ον παραγενομενον ανηγαγον εις το [υπερωον]{.greek-omitted} [υπερωων]{.greek-added} και [παρεστησαν]{.greek-omitted} [περιεστησαν]{.greek-added} αυτω πασαι αι χηραι κλαιουσαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μετ αυτων ουσα η δορκα[ς]{.unclear}[9:39]{.aside}

εκβαλων δε εξω παντας ο πετρος θεις τα γονατα προσηυξατο και επιστρεψας προς το σωμα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} αναστηθι η δε [ηνοιξεν]{.greek-omitted} [διηνοιξεν]{.greek-added} τους οφθαλμους αυτης και ιδουσα τον πετρον [ανεκαθισεν]{.greek-omitted} [ανεκαθισε]{.greek-added}[9:40]{.aside}

δους δε αυτη χειρα ανεστησεν αυτην [και]{.greek-added} φωνησας [δε]{.greek-omitted} τους αγιους και τας χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

γνωστον δε εγενετο καθ ολης της ιοππης και πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι αυτον εν ιοππη παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις [ην]{.greek-omitted} εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ σπειρης της καλουμενης [ιταλικης]{.greek-omitted} [ιτταλικης]{.greek-added}[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω α[υ]{.unclear}του ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

ειδεν εν οραματι φανερως ωσει [περι]{.greek-added} ωραν [ενατην]{.greek-omitted} [εννατην]{.greek-added} της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε ατενισας αυτω και εμφοβος γενομενος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι [εστιν]{.greek-omitted} [εστι]{.greek-added} [κυριε]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε αυτω αι [προσευχαι]{.greek-omitted} [προσευχαις]{.greek-added} σου και αι [ελεημοσυναι]{.greek-omitted} [ελεημοσυναις]{.greek-added} σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν οικια παρα θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην ευσεβη των προσκαρτερουντων αυτω[10:7]{.aside}

και [εξ]{.unclear}ηγησαμενος αυτοις [απαντα]{.greek-omitted} [παντα]{.greek-added} απεστε[ιλ]{.greek-supplied}[ε]{.unclear}ν αυτους εις την ιοππην[10:8]{.aside}

τη δε επαυρ[ιο]{.unclear}ν οδοιπορουντων [εκεινων]{.greek-omitted} [αυτων]{.greek-added} και τη πολει εγγι[ζ]{.unclear}οντων ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν εκτην[10:9]{.aside}

εγενετο δε προσπεινος και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γευσασθαι παρασκευαζοντων δε [εκεινων]{.greek-omitted} [αυτων]{.greek-added} επεπεσεν επ αυτον εκστασις[10:10]{.aside}

και θεωρει τον [ουρανον]{.greek-abbr} ανεωγμενον και [καταβαινον]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [τεσσαρσιν]{.greek-added} [αρχαις]{.greek-added} [δεδεμενον]{.greek-added} σκευος τι ως οθονην μεγαλην [καταβαινον]{.greek-added} [τεσσαρσιν]{.greek-omitted} [αρχαις]{.greek-omitted} [δεδεμενον]{.greek-omitted} [και]{.greek-omitted} [καθιεμενον]{.greek-omitted} επι της γης[10:11]{.aside}

εν ω [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} παντα τα τετραποδα [της]{.greek-omitted} [γης]{.greek-omitted} και τα θηρια και τα ερπετα [της]{.greek-added} [γης]{.greek-added} και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστας πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μηδαμως [κυριε]{.greek-abbr} οτι ουδεποτε εφαγον παν κοινον [η]{.greek-omitted} [και]{.greek-added} ακαθαρτον[10:14]{.aside}

και φωνη [παλιν]{.greek-omitted} εκ δευτερου [παλιν]{.greek-added} προς αυτον α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαρισε]{.greek-added} συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν ανεληφθη το [σκευος]{.greek-omitted} [σκεβος]{.greek-added} εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο πετρος τι αν ειη το οραμα ο [ειδεν]{.greek-omitted} [ειδε]{.greek-added} και ιδου οι ανδρες οι απεσταλμενοι απο του κορνηλιου διερωτησαντες την οικιαν [του]{.greek-added} σιμωνος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες [ε]{.unclear}πυ[ν]{.unclear}θανοντο ει σιμων ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου [διεν]{.greek-added} [διενθυμουμενου]{.greek-omitted} [θυμουμενου]{.greek-added} περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους[10:20]{.aside}

καταβας δε πετρος προς τους ανδρας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

εισκαλεσαμενος ουν αυτους εξενισεν τη δε επαυριον [αναστας]{.greek-added} ο πετρος εξηλθεν [εις]{.greek-added} [καισαρειαν]{.greek-added} συν αυτοις και τινες των αδελφων των απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους συγγενεις αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος [ηγειρεν]{.greek-added} αυτον [ηγειρεν]{.greek-omitted} λεγων αναστηθι [καγω]{.greek-omitted} [και]{.greek-added} [γαρ]{.greek-added} [εγω]{.greek-added} αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} και ευρισκει συνεληλυθ[ο]{.unclear}τας πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως αθεμιτον εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και αναντιρρητως ηλθον μεταπεμφθεις [υφ]{.greek-added} [υμων]{.greek-added} πυνθανομαι ουν τινι λογω [μετεπεμψασθε]{.greek-omitted} [μετεπεμψασθαι]{.greek-added} με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και την [ενατην]{.greek-omitted} [εννατην]{.greek-added} ωραν προσευχομενος εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και φησιν κορνηλιε εισηκουσθη σου η προσευχη και αι ελεημοσυναι σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και μετακαλεσαι σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος [βυρσεως]{.greek-omitted} [βυρσεος]{.greek-added} παρα θαλασσαν ος παραγενομενος λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added}[10:33]{.aside}

ανοιξας δε πετρος το στομα ειπεν επ αληθειας καταλαμβανομαι οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι εθνει ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην δεκτος αυτω εστιν[10:35]{.aside}

τον λογον ον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος εστιν παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το βαπτισμα ο εκηρυξεν ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο ναζαρετ [ως]{.greek-omitted} [ον]{.greek-added} εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-omitted} [ιεροσολυμοις]{.greek-added} ον και ανειλον [κρεμασαντες]{.greek-omitted} [κρεμμασαντες]{.greek-added} επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} [ηγειρεν]{.greek-omitted} [ηγειρε]{.greek-added} τη τριτη ημερα και εδωκεν [αυτον]{.greek-omitted} [αυτω]{.greek-added} εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες συνεφαγομεν και συνεπιομεν αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι [αυτος]{.greek-omitted} [ουτος]{.greek-added} εστιν ο ωρισμενος υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη ο πετρος[10:46]{.aside}

μητι το υδωρ κωλυσαι δυναται τις του μη βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον [καθως]{.greek-omitted} [ως]{.greek-added} και ημεις[10:47]{.aside}

[προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} αυτους βαπτισθηναι εν τω ονοματι [του]{.greek-omitted} [κυριου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} τοτε ηρωτησαν αυτον επιμειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας [ακροβυστους]{.greek-added} [ακροβυστιαν]{.greek-omitted} [εχοντας]{.greek-omitted} εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

αρξαμενος δε [ο]{.greek-omitted} πετρος εξετιθετο αυτοις καθεξης λεγων[11:4]{.aside}

εγω ημην εν πολει ιοππη προσευχομενος και ειδον εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και ειδον τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι [παν]{.greek-omitted} κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} [εκαθαρισεν]{.greek-omitted} [εκαθαρισε]{.greek-added} συ μη κοινου[11:9]{.aside}

τουτο δε [ε]{.greek-added} [εγενετο]{.greek-omitted} [γενετο]{.greek-added} επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν ανεσπασθη απαντα εις τον [ουρανον]{.greek-abbr}[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν [εν]{.greek-omitted} η ημην απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν [διακρινομενον]{.greek-omitted} [διακριναντα]{.greek-added} ηλθον δε συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

[απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} ημιν πως [ειδεν]{.greek-omitted} [ειδε]{.greek-added} τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις σωθηση συ και πας ο οικος σου[11:14]{.aside}

εν δε τω αρξασθαι με λαλειν [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [του]{.greek-added} [κυριου]{.greek-abbr} [ως]{.greek-omitted} [ος]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} ιωαννης μεν εβαπτισεν υδατι υμεις δε βαπτισθησεσθε εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω δε τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες αρα [γε]{.greek-omitted} και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες απο της θλιψεως της γενομενης επι στεφανω διηλθον εως φοινικης και κυπρου και αντιοχειας [μη]{.greek-added} [μηδενι]{.greek-omitted} [δενι]{.greek-added} λαλουντες τον λογον ει μη μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων ανδρες κυπριοι και κυρηναιοι οιτινες [εισελθοντες]{.greek-omitted} [ελθοντες]{.greek-added} εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας επεστρεψεν επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της [ουσης]{.greek-added} εν ιεροσολυμοις [τα]{.greek-added} περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και [παρεκαλει]{.greek-omitted} [παρακαλεσας]{.greek-added} παντας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και πληρης [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε εις ταρσον ο βαρναβας [αναζητησαι]{.greek-omitted} [επιζητησαι]{.greek-added} σαυλον[11:25]{.aside}

και ευρων [αυτον]{.greek-added} ηγαγεν [αυτον]{.greek-omitted} εις αντιοχειαν εγενετο δε [αυτους]{.greek-omitted} ενιαυτον ολον συναχθηναι [εν]{.greek-added} τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος [εσημανεν]{.greek-omitted} [εσημανε]{.greek-added} δια του [πνευματος]{.greek-abbr} λιμον μεγαν μελλειν εσεσθαι εφ ολην την οικουμενην [ητις]{.greek-added} [οστις]{.greek-omitted} [και]{.greek-omitted} εγενετο επι κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως [ευπορειτο]{.greek-omitted} [ηυπορειτο]{.greek-added} τις ωρισαν εκαστος αυτων εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

ο και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι τινας των απο της εκκλησιας[12:1]{.aside}

[ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

και ιδων οτι αρεστον εστιν τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε αι ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε εμελλεν [προαγειν]{.greek-added} αυτον [προαγειν]{.greek-omitted} ο ηρωδης τη νυκτι εκεινη ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δυσιν φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και [εξεπεσον]{.greek-omitted} [εξεπεσαν]{.greek-added} αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} ο αγγελος προς αυτον περιζωσαι και υποδησαι τα σανδαλια σου [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και ακολουθει μοι[12:8]{.aside}

και εξελθων ηκολουθει αυτω και ουκ ηδει οτι αληθες [εστιν]{.greek-omitted} [εστι]{.greek-added} το γινομενον δια του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν εις την πολιν ητις αυτοματη ηνοιχθη αυτοις και εξελθοντες προηλθον ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος γενομενος εν εαυτω ειπεν νυν οιδα αληθως οτι [εξαπεστειλεν]{.greek-omitted} [εξαπεστειλε]{.greek-added} [κυριος]{.greek-abbr} τον αγγελον αυτου και [εξειλετο]{.greek-omitted} [ερρυσατο]{.greek-added} με εκ χειρος ηρωδου και πασης της προσδοκιας του λαου των ιουδαιων[12:11]{.aside}

συνιδων [τε]{.greek-omitted} [δε]{.greek-added} ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} ιωαννου του επικαλουμενου μαρκου ου ησαν ικανοι συνηθροισμενοι και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του πετρου την θυραν του πυλωνος [προσηλθεν]{.greek-omitted} [προσηλθε]{.greek-added} παιδισκη υπακουσαι ονοματι ροδη[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον μαινη η δε διισχυριζετο ουτως εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος [επεμενεν]{.greek-omitted} [επεμενε]{.greek-added} κρουων ανοιξαντες δε ειδον αυτον και εξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξηγαγεν εκ της φυλακης ειπεν δε απαγγειλατε ιακωβω και τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις [την]{.greek-omitted} καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης θυμομαχων τυριοις και σιδωνιοις [ομοθυμαδον]{.greek-omitted} [ομοθυμαδων]{.greek-added} δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι [αυτων]{.greek-omitted} [αυτω]{.greek-added} την χωραν απο της βασιλικης[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα βασιλικην και καθισας επι του βηματος εδημηγορει προς αυτους[12:21]{.aside}

ο δε δημος επεφωνει [[θεου]{.greek-abbr}]{.greek-added} φωνη [θεου]{.greek-omitted} και ουκ [ανθρωπου]{.greek-abbr}[12:22]{.aside}

παραχρημα δε [αυ]{.greek-added} [τον]{.greek-added} επαταξεν [αυτον]{.greek-omitted} αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} δοξαν τω [θεω]{.greek-abbr} και γενομενος σκωληκοβρωτος εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και επληθυνετο[12:24]{.aside}

βαρναβας δε και σαυλος υπεστρεψαν [εις]{.greek-omitted} [απο]{.greek-added} [ιερουσαλημ]{.greek-abbr} πληρωσαντες την διακονιαν συμπαραλαβοντες και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον [επικληθεντα]{.greek-omitted} [επικαλουμενον]{.greek-added} μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε τινες εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος ο κυρηναιος μαναην τε ηρωδου του τετραρχου συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον [αφορισατε]{.greek-omitted} [αφωρισατε]{.greek-added} [δη]{.greek-omitted} μοι τον [τε]{.greek-added} βαρναβαν και [τον]{.greek-omitted} σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες [αυτοις]{.greek-added} τας χειρας [αυτοις]{.greek-omitted} απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεντες υπο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις [την]{.greek-omitted} σελευκειαν εκειθεν [δε]{.greek-omitted} [τε]{.greek-added} απεπλευσαν εις [την]{.greek-omitted} κυπρον[13:4]{.aside}

και γενομενοι εν [σαλαμινι]{.greek-omitted} [σαλαμινη]{.greek-added} κατηγγελλον τον λογον του [θεου]{.greek-omitted} [[κυριου]{.greek-abbr}]{.greek-added} εν ταις συναγωγαις των ιουδαιων ειχον δε και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} υπηρετην[13:5]{.aside}

διελθοντες δε [ολην]{.greek-added} την νησον αχρι παφου ευρον [ανδρα]{.greek-added} τινα μαγον ψευδοπροφητην ιουδαιον ω ονομα [βαριησους]{.greek-omitted} [βαριησουν]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω [παυλω]{.greek-omitted} ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επεζητησεν ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μαγος ουτως γαρ [μεθερμηνευεται]{.greek-omitted} [ερμηνευεται]{.greek-added} το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου και ατενισας εις αυτον[13:9]{.aside}

ειπεν ω πληρης παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου [παυση]{.greek-omitted} [παυη]{.greek-added} διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον αχρι καιρου παραχρημα δε επεπεσεν επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

αναχθεντες δε απο της παφου οι περι τον παυλον ηλθον εις περγην της παμφυλιας ιωαννης δε αποχωρησας απ αυτων υπεστρεψεν εις ιεροσολυμα[13:13]{.aside}

αυτοι δε διελθοντες απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει εστιν λογος [εν]{.greek-omitted} υμιν παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι [εν]{.greek-added} [υμιν]{.greek-added} φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη [αιγυπτω]{.greek-omitted} [αιγυπτου]{.greek-added} και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον [ετροποφορησεν]{.greek-omitted} [ετροφοφορησεν]{.greek-added} αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη [επτα]{.greek-omitted} εν γη χανααν [επτα]{.greek-added} κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

και μετα ταυτα ως [ετεσιν]{.greek-omitted} [ετεσι]{.greek-added} τετρακοσιοις και πεντηκοντα [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ υιον κις ανδρα εκ φυλης βενιαμιν ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και ειπεν μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} τω [ισραηλ]{.greek-abbr} [σωτηριαν]{.greek-abbr}[13:23]{.aside}

προκηρυξαντος [ιωαννου]{.greek-abbr} προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας [παντι]{.greek-added} τω [λαω]{.greek-added} [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου ο ιωαννης τον δρομον [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τινα με υπονοειτε ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος της [σωτηριας]{.greek-abbr} ταυτης [απεσταλη]{.greek-omitted} [εξαπεσταλη]{.greek-added}[13:26]{.aside}

οι γαρ κατοικουντες [εν]{.greek-omitted} [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον αγνοησαντες και τας φωνας των προφητων τας κατα παν σαββατον αναγινωσκομενας κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου γεγραμμενα καθελοντες απο του ξυλου εθηκαν εις μνημειον[13:29]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [εισιν]{.greek-omitted} [εισι]{.greek-added} μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν γενομενην [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκε]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω τω δευτερω γεγραπται υιος μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον εκ νεκρων μηκετι μελλοντα [αυτον]{.greek-added} υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ ειδεν διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν ανδρες αδελφοι οτι δια τουτου υμιν αφεσις αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδ[υ]{.greek-supplied}νηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} εν τουτω πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται και [επιβλεψατε]{.greek-added} [και]{.greek-added} θα[υ]{.unclear}μασατε [θαυμασια]{.greek-added} και αφανισθητε οτι εργον [εργαζομαι]{.greek-added} εγω [εργαζομαι]{.greek-omitted} εν ταις ημεραις υμων [εργον]{.greek-added} ο ου μη [πιστευσηται]{.greek-added} [πιστευσητε]{.corr} εαν τις [εκδιηγηται]{.greek-omitted} [εκδιηγειται]{.greek-added} υμιν[13:41]{.aside}

εξιοντων δε [εκ]{.greek-omitted} [της]{.greek-omitted} [συναγωγης]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [ιουδαιων]{.greek-omitted} παρεκαλουν [τα]{.corr} [εθνη]{.corr} εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα [ταυτα]{.greek-added}[13:42]{.aside}

λυθεισης δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και τω βαρναβα οιτινες προσλαλουντες [αυτοις]{.greek-added} επειθον αυτους [επιμενειν]{.greek-omitted} [προσμενειν]{.greek-added} τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω [τε]{.greek-omitted} [δε]{.greek-added} ερχομενω [σαβ[α]{.unclear}]{.greek-added} [σαββατω]{.corr} σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-abbr}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλου λεγομενοις αντιλεγοντες και βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος και ο βαρναβας ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} επειδη δε [απωθεισθε]{.greek-omitted} [αποθεισθε]{.greek-added} αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ εντεταλται ημιν ο [κυριος]{.greek-abbr} τεθεικα σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον τον [[θεον]{.greek-abbr}]{.greek-added} [λογον]{.greek-omitted} [του]{.greek-omitted} [κυριου]{.greek-omitted} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-omitted} [δι]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} [καθ]{.greek-added} ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας [και]{.greek-omitted} τας ευσχημονας και τους πρωτους της πολεως και επηγειραν διωγμον επι τον παυλον και [τον]{.greek-omitted} βαρναβαν και εξεβαλον αυτους απο των οριων αυτων[13:50]{.aside}

οι δε εκτιναξαμενοι τον κονιορτον των ποδων [αυτων]{.greek-omitted} επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι δε μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων τε και ελληνων πολυ πληθος[14:1]{.aside}

οι δε [απειθουντες]{.greek-omitted} [απειθησαντες]{.greek-added} ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων [κατα]{.greek-omitted} [και]{.greek-added} των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου διδοντι σημεια και τερατα γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και [λιθοβολησαι]{.greek-omitted} [λιθασαι]{.greek-added} αυτους[14:5]{.aside}

[ους]{.greek-added} [συνιδοντες]{.greek-omitted} [ιδοντες]{.greek-added} κατεφυγον εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει ησαν ευαγγελιζομενοι[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων ος ουδεποτε περιπεπατηκει[14:8]{.aside}

ουτος [ηκουσεν]{.greek-omitted} [ηκουε]{.greek-added} του παυλου λαλουντος ος ατενισας αυτω και ιδων οτι πιστιν εχει του σωθηναι[14:9]{.aside}

ειπεν μεγαλη τη φωνη αναστηθι επι τους ποδας σου [ορθως]{.greek-omitted} [ορθος]{.greek-added} και [ηλλετο]{.greek-omitted} [ηλατο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν ο παυλος επηραν την φωνην αυτων λυκαονιστι λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν δια τον δε παυλον ερμην επειδη αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο δε ιερευς του διος του οντος προ της πολεως αυτων ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις [ηθελεν]{.greek-omitted} [ηθελον]{.greek-added} θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων εισεπηδησαν εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες [ανδρες]{.greek-omitted} τι ταυτα ποιειτε και ημεις ομοιοπαθεις εσμεν υμιν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο τουτων των ματαιων επιστρεφειν επι τον [θεον]{.greek-abbr} τον ζωντα ος [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις παρωχημεναις γενεαις [ειασεν]{.greek-omitted} [ειασε]{.greek-added} παντα τα εθνη πορευεσθαι ταις οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρον εαυτον αφηκεν αγαθοποιων [ουρανοθεν]{.greek-abbr} [υμιν]{.greek-omitted} [ημιν]{.greek-added} υετους διδους και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας [ημων]{.greek-omitted} [υμων]{.greek-added}[14:17]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν αυτοις [αλλα]{.greek-added} [πορευεσθαι]{.greek-added} [εκαστον]{.greek-added} [εις]{.greek-added} [τα]{.greek-added} [ιδια]{.greek-added}[14:18]{.aside}

[διατριβοντων]{.greek-added} [δε]{.greek-added} [αυτων]{.greek-added} [και]{.greek-added} [διδασκοντων]{.greek-added} επηλθον [δε]{.greek-omitted} απο αντιοχειας και ικονιου ιουδαιοι [και]{.greek-added} [διαλεγομενων]{.greek-added} [αυτων]{.greek-added} [παρρησια]{.greek-added} [επεισαν]{.greek-added} [τους]{.greek-added} [οχλους]{.greek-added} [αποστηναι]{.greek-added} [απ]{.greek-added} [αυτων]{.greek-added} [λεγοντες]{.greek-added} [οτι]{.greek-added} [ουδεν]{.greek-added} [αληθες]{.greek-added} [λεγουσιν]{.greek-added} [αλλα]{.greek-added} [παντα]{.greek-added} [ψευδονται]{.greek-added} και πεισαντες τους οχλους και λιθασαντες τον παυλον [εσυρον]{.greek-omitted} [εσυραν]{.greek-added} εξω της πολεως νομισαντες αυτον [τεθναναι]{.greek-omitted} [τεθνηκεναι]{.greek-added}[14:19]{.aside}

κυκλωσαντων δε [αυτον]{.greek-omitted} των μαθητων [αυτον]{.greek-added} αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν συν τω βαρναβα εις δερβην[14:20]{.aside}

ευαγγελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν και ικονιον και αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει ημας εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις πρεσβυτερους κατ εκκλησιαν προσευξαμενοι μετα νηστειων παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον πεπιστευκεισαν[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον εις παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον κατεβησαν εις [ατταλειαν]{.greek-omitted} [ατταλιαν]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν παραδεδομενοι τη χαριτι του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν [ανηγγειλον]{.greek-added} [ανηγγειλαν]{.corr} οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} θυραν πιστεως[14:27]{.aside}

διετριβον [δε]{.greek-omitted} [τε]{.greek-added} εκει χρονον ουκ ολιγον συν το[ι]{.unclear}ς μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντ[ε]{.unclear}ς απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη περιτεμνησθε τω εθει μωυσεως ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης ουν στασεως και ζητησεως ουκ ολιγης τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την φοινικην και σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις αδελφοις[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-abbr} απεδεχθησαν υπο της εκκλησιας και των αποστολων και των πρεσβυτερων ανηγγειλαν τε οσα ο [θεος]{.greek-abbr} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} μετ αυτων [και]{.greek-added} [οτι]{.greek-added} [ηνοιξε]{.greek-added} [τοις]{.greek-added} [εθνεσι]{.greek-added} [θυραν]{.greek-added} [πιστεως]{.greek-added}[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων πεπιστευκοτες λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added}[15:5]{.aside}

συνηχθησαν δε οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε συζητησεως γενομενης αναστας πετρος ειπεν προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων ο [θεος]{.greek-abbr} εν ημιν εξελεξατο δια του στοματος μου ακουσαι τα εθνη [τον]{.greek-omitted} [λογον]{.greek-omitted} του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και ου[δ]{.unclear}εν [[ουθεν]{.corr}]{.greek-added} [διεκρινεν]{.greek-omitted} [διεκρινε]{.greek-added} μεταξυ ημων τε και αυτων τη πιστει καθαρισας τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} [επιθειναι]{.greek-omitted} [επιθηναι]{.greek-added} ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

[εσιγησεν]{.greek-omitted} [εσιγησε]{.greek-added} δε παν το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δι αυτων[15:12]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον επι τω ονοματι αυτου[15:14]{.aside}

και [τουτω]{.greek-omitted} [τουτο]{.greek-added} συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη εφ ους επικεκληται το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων ταυτα παντα[15:17]{.aside}

γνωστα απ αιωνος [εστιν]{.greek-omitted} [εστι]{.greek-added} τω [θεω]{.greek-abbr} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

αλλα επιστειλαι αυτοις του απεχεσθαι απο των αλισγηματων των ειδωλων και της πορνειας και του πνικτου και του αιματος[15:20]{.aside}

μωυσης γαρ εκ γενεων αρχαιων κατα πολιν τους κηρυσσοντας αυτον [εχει]{.greek-omitted} [εχειν]{.greek-added} εν ταις συναγωγαις κατα παν σαββατον [αναγινωσκομενος]{.greek-omitted} [αναγινωσκομενον]{.greek-added}[15:21]{.aside}

τοτε [εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους ανδρας εξ αυτων πεμψαι εις αντιοχειαν συν [τω]{.greek-added} παυλω και βαρναβα [ιουδαν]{.greek-omitted} [ιουδα]{.greek-added} τον [επικαλουμενον]{.greek-omitted} [καλουμενον]{.greek-added} [βαρσαββαν]{.greek-omitted} [βαρσαβαν]{.greek-added} και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων εξελθοντες εταραξαν υμας λογοις [ανασκευαζοντες]{.greek-omitted} [ανασκεβαζοντες]{.greek-added} [τας]{.greek-omitted} [ψυχας]{.greek-omitted} [υμων]{.greek-omitted} [λεγοντες]{.greek-omitted} περιτεμνεσθαι και τηρειν τον νομον οις ου διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον [εκλεξαμενους]{.greek-omitted} [εκλεξαμενοις]{.greek-added} ανδρας πεμψαι προς υμας συν τοις αγαπητοις [ημων]{.greek-omitted} [υμων]{.greek-added} βαρναβα [τε]{.greek-added} και παυλω[15:25]{.aside}

[ανθρωποις]{.greek-abbr} [παραδεδωκοσιν]{.greek-omitted} [παραδεδωκοσι]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

[εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} γαρ τω [[πνευματι]{.greek-abbr}]{.greek-added} [τω]{.greek-added} αγιω [πνευματι]{.greek-omitted} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην [των]{.greek-omitted} [τουτων]{.greek-added} επαναγκες [τουτων]{.greek-omitted}[15:28]{.aside}

απεχεσθαι ειδωλοθυτων και αιματος και πνικτου και πορνειας εξ ων διατηρουντες [εαυτους]{.greek-omitted} [αυτους]{.greek-added} ευ πραξετε ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες [ηλθον]{.greek-omitted} [κατηλθον]{.greek-added} εις αντιοχειαν και συναγαγοντες το πληθος επεδωκαν την επιστολην[15:30]{.aside}

αναγνοντες δε εχαρησαν [χαραν]{.greek-added} [μεγαλην]{.greek-added} επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε χρονον απελυθησαν μετ ειρηνης απο των αδελφων προς τους αποστολους[15:33]{.aside}

[εδοξε]{.greek-added} [δε]{.greek-added} [τω]{.greek-added} [σιλα]{.greek-added} [επιμειναι]{.greek-added} [αυτου]{.greek-added}[15:34]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παυλος προς βαρναβαν επιστρεψαντες δη επισκεψωμεθα τους αδελφο[υ]{.unclear}ς ημων κατα πασαν πολιν εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added}[15:36]{.aside}

[βαρ]{.greek-added} [βαρναβας]{.greek-omitted} [ναβας]{.greek-added} δε εβουλευσατο συμπαραλαβειν τον ιωαννην τον καλουμενον μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη συμπαραλαβειν τουτον[15:38]{.aside}

εγενετο ουν παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων τον τε βαρναβαν παραλαβοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

[διηρχετο]{.greek-omitted} [διηρχοντο]{.greek-added} δε την συριαν και κιλικιαν [επιστηριζων]{.greek-omitted} [επιστηριζοντες]{.greek-added} τας εκκλησιας[15:41]{.aside}

### Chapter 16

[κατηντησεν]{.greek-omitted} [κατηντησε]{.greek-added} δε [και]{.greek-added} εις δερβην και [εις]{.greek-added} λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος υιος γυναικος [τινος]{.greek-omitted} ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν λυστροις και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους [ιουδαιους]{.greek-omitted} [τους]{.greek-omitted} οντας εν τοις τοποις εκεινοις [ιουδαιους]{.greek-added} ηδεισαν γαρ απαντες τον [πατερα]{.greek-abbr} αυτου οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις παρεδιδουν αυτοις φυλασσειν τα δογματα τα [κεκριμενα]{.greek-omitted} [κεκριμμενα]{.greek-added} υπο των αποστολων και των πρεσβυτερων των εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

[αι]{.unclear} μεν ουν εκκλησιαι εστερεουντο τη πιστει και επερισσευον τω αριθμω καθ ημεραν[16:5]{.aside}

[διελθοντες]{.greek-omitted} [διηλθον]{.greek-added} δε την φρυγιαν και [την]{.greek-omitted} γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες [δε]{.greek-added} κατα την μυσιαν επειραζον [κατα]{.greek-omitted} [εις]{.greek-added} την βιθυνιαν πορευεσθαι και ουκ ειασεν αυτους το [πνευμα]{.greek-abbr}[16:7]{.aside}

παρελθοντες δε την μυσιαν κατεβησαν εις τρωαδα[16:8]{.aside}

και οραμα δια της νυκτος ωφθη τω παυλω ανηρ τις ην μακεδων εστως [και]{.greek-added} παρακαλων αυτον και λεγων διαβας εις μακεδονιαν βοηθησον ημιν[16:9]{.aside}

ως δε το οραμα ειδεν ευθεως εζητησαμεν [εξελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις [την]{.greek-omitted} μακεδονιαν συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[16:10]{.aside}

αναχθεντες ουν απο [της]{.greek-omitted} τρωαδος ευθυδρομησαμεν εις σαμοθρακην τη [τε]{.greek-omitted} [δε]{.greek-added} επιουση εις νεαπολιν[16:11]{.aside}

εκειθεν τε εις φιλιππους ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη της μεριδος της μακεδονιας πολις [κολωνεια]{.greek-omitted} [κωλωνια]{.greek-added} ημεν δε εν [αυτη]{.greek-omitted} [ταυτη]{.greek-added} τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των σαββατων εξηλθομεν εξω της πολεως παρα [τον]{.greek-added} ποταμον ου ενομιζετο προσευχη ειναι και καθισαντες ελαλουμεν ταις συνελθουσαις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added}[16:13]{.aside}

και τις γυνη ονοματι λυδια [πορφυροπωλις]{.greek-omitted} [πορφυροπολις]{.greek-added} πολεως θυατειρων σεβομενη τον [θεον]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουσε]{.greek-added} ης ο [κυριος]{.greek-abbr} [διηνοιξεν]{.greek-omitted} [διηνοιξε]{.greek-added} την καρδιαν προσεχειν τοις [λαλουμενοις]{.greek-omitted} [λεγομενοις]{.greek-added} υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης [παρεκαλεσεν]{.greek-omitted} [παρεκαλεσε]{.greek-added} λεγουσα ει κεκρικατε με [αξιαν]{.greek-added} πιστην [ειναι]{.greek-added} τω [κυριω]{.greek-abbr} [ειναι]{.greek-omitted} εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην παιδισκην τινα εχουσαν [πνευμα]{.greek-abbr} πυθωνος απαντησαι ημιν ητις εργασιαν πολλην [παρειχεν]{.greek-omitted} [παρειχε]{.greek-added} τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη κατακολουθησασα τω παυλω και [ημιν]{.greek-omitted} [τω]{.greek-added} [σιλα]{.greek-added} [εκραζεν]{.greek-omitted} [εκραζε]{.greek-added} λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες καταγγελλουσιν ημιν οδον [σωτηριας]{.greek-abbr}[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} ειπεν παραγγελλω σοι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν αυτη τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της εργασιας αυτων επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και καταγγελλουσιν εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι [στρατηγοι]{.greek-omitted} [στρα]{.greek-added} [τηγοι]{.greek-added} [περιρρηξαντες]{.greek-omitted} [περιρριξαντες]{.greek-added} αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην ειληφως εβαλεν αυτους εις την εσωτεραν φυλακην και τους ποδας αυτων ησφαλισατο εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} [επηκροωντο]{.greek-omitted} [επικροωντο]{.greek-added} δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του δεσμωτηριου ανεωχθησαν τε παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν εμελλεν εαυτον αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

[εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} δε φωνη μεγαλη ο παυλος λεγων μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα [εισεπηδησεν]{.greek-omitted} [εισεπηδησε]{.greek-added} και εντρομος γενομενος [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δ[ε]{.unclear} ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και ο οικος σου[16:31]{.aside}

και [ελαλησαν]{.greek-omitted} [ελαλη]{.greek-added} [σαν]{.greek-added} αυτω τον λογον του [κυριου]{.greek-abbr} και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα της νυκτος ελουσεν απο των πληγων και εβαπτισθη αυτος και οι αυτου παντες παραχρημα[16:33]{.aside}

αναγαγων τε αυτους εις τον οικον [αυτου]{.greek-omitted} [παρεθηκεν]{.greek-omitted} [παρεθηκε]{.greek-added} τραπεζαν και ηγαλλιατο πανοικι πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενομενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

[απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες [πορευεσθε]{.greek-omitted} [πορεβεσθε]{.greek-added} εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη προς αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας [εκβαλλουσιν]{.greek-omitted} [εκβαλλουσι]{.greek-added} ου γαρ αλλα ελθοντες αυτοι [ημας]{.greek-added} εξαγαγετωσαν[16:37]{.aside}

ανηγγειλαν δε τοις στρατηγοις οι [ραβδουχοι]{.greek-omitted} [ραυδουχοι]{.greek-added} τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και εξαγαγοντες ηρωτων εξελθειν [απο]{.greek-added} της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες τους αδελφους παρεκαλεσαν αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και [α]{.greek-added} [απολλωνιαν]{.greek-omitted} [πολλωνιαν]{.greek-added} ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το ειωθος τω παυλω [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν ο [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} [εις]{.greek-added} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων επεισθησαν και προσεκληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων πολυ πληθος γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

προσλαβομενοι δε οι ιουδαιοι οι απειθουντες των αγοραιων τινας ανδρας πονηρους και οχλοποιησαντες εθορυβουν την πολιν επισταντες τε τη οικια ιασονος εζητουν αυτους αγαγειν εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους εσυρον τον ιασονα και τινας αδελφους επι τους πολιταρχας βοωντες οτι οι την οικουμενην αναστατωσαντες ουτοι και ενθαδε παρεισιν[17:6]{.aside}

[ους]{.greek-omitted} [οις]{.greek-added} υποδεδεκται ιασων και ουτοι παντες απεναντι των δογματων καισαρος [πρασσουσιν]{.greek-omitted} [πρασσουσι]{.greek-added} βασιλεα λεγοντες ετερον ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε τον οχλον και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του ιασονος και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια [της]{.greek-omitted} νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις [βεροιαν]{.greek-omitted} [βερροιαν]{.greek-added} οιτινες παραγενομενοι εις την συναγωγην [απηεσαν]{.greek-omitted} των ιουδαιων [απηεσαν]{.greek-added}[17:10]{.aside}

ουτοι δε ησαν [οι]{.greek-added} ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας [το]{.greek-omitted} καθ ημεραν ανακρινοντες τας γραφας ει εχοι ταυτα ουτως[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε εγνωσαν οι απο της θεσσαλονικης ιουδαιοι οτι και εν τη [βεροια]{.greek-omitted} [βερροια]{.greek-added} [κατηγγελη]{.greek-omitted} [κατηγγελει]{.greek-added} υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες [και]{.greek-added} [ταρασσοντες]{.greek-added} τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθαι ως επι την θαλασσαν [υπεμενον]{.greek-omitted} [υπεμειναν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} ο τε σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε καθιστωντες τον παυλον ηγαγον αυτον εως αθηνων και λαβοντες εντολην προς τον σιλαν και [τον]{.greek-added} τιμοθεον ινα ως ταχιστα [ελθωσιν]{.greek-omitted} [ελθωσι]{.greek-added} προς αυτον εξηεσαν[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου [τον]{.greek-added} [σιλαν]{.greek-added} [και]{.greek-added} [τον]{.greek-added} [τιμοθεον]{.greek-added} παρωξυνετο το [πνευμα]{.greek-abbr} αυτου εν αυτω [θεωρουντι]{.greek-omitted} [θεωρουντος]{.greek-added} κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη [τοις]{.greek-omitted} [ιουδαιοις]{.greek-omitted} [και]{.greek-omitted} τοις σεβομενοις και εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε [των]{.greek-added} [επικουριων]{.greek-added} και [στοικων]{.greek-added} [των]{.greek-omitted} [επικουρειων]{.greek-omitted} και [των]{.greek-omitted} [στοικων]{.greek-omitted} φιλοσοφων [συ]{.greek-added} [συνεβαλλον]{.greek-omitted} [νεβαλλον]{.greek-added} αυτω και τινες ελεγον τι αν θελοι ο σπερμολογος ουτος λεγειν οι δε ξενων δαιμονιων δοκει καταγγελευς ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο [αυτοις]{.greek-added}[17:18]{.aside}

επιλαβομενοι τε αυτου επι τον αρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι τι αν θελοι ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον ευκαιρουν η λεγειν τι και ακουειν καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως δεισιδαιμονεστερους υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και αναθεωρων τα σεβασματα υμων ευρον και βωμον εν ω επεγεγραπτο αγνωστω [θεω]{.greek-abbr} ον ουν αγνοουντες ευσεβειτε τουτον εγω καταγγελλω υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [υπαρχων]{.greek-added} [κυριος]{.greek-abbr} [υπαρχων]{.greek-omitted} ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} θεραπευεται προσδεομενος [τινος]{.greek-omitted} αυτος διδους [πασιν]{.greek-omitted} [πασι]{.greek-added} ζωην και πνοην κατα παντα[17:25]{.aside}

[εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τε εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης ορισας [προστεταγμενους]{.greek-omitted} [προστεταγμε]{.greek-added} [νους]{.greek-added} καιρους και τας ορ[ο]{.greek-supplied}θεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τ[ο]{.unclear}ν [κυριον]{.greek-abbr} ει αρα γε ψηλαφησειαν αυτον και ευροιεν και γε ου μακραν απο ενος εκαστου ημων υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και [τινες]{.greek-omitted} των καθ υμας ποιητων [τινες]{.greek-added} [ειρηκασιν]{.greek-omitted} [ειρηκασι]{.greek-added} του γαρ [και]{.greek-omitted} γενος εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν [χρυσω]{.greek-omitted} [χρυσιω]{.greek-added} η [αργυρω]{.greek-omitted} [αργυριω]{.greek-added} η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} [πασιν]{.greek-omitted} [πασι]{.greek-added} πανταχου μετανοειν[17:30]{.aside}

διοτι εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω ωρισεν πιστιν παρασχων [πασιν]{.greek-omitted} [πασι]{.greek-added} αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον ακουσομεθα σου παλιν περι τουτου[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα ιουδαιον ονοματι ακυλαν ποντικον τω γενει προσφατως εληλυθοτα απο της [ιταλιας]{.greek-omitted} [ιτταλιας]{.greek-added} και πρισκιλλαν γυναικα αυτου δια το [τεταχεναι]{.greek-omitted} [τεταχθεναι]{.greek-added} κλαυδιον χωριζεσθαι παντας τους ιουδαιους εκ της ρωμης προσηλθεν αυτοις[18:2]{.aside}

και δια το ομοτεχνον ειναι [και]{.greek-added} [εμενεν]{.greek-omitted} [εμεινε]{.greek-added} παρ αυτοις και ειργαζετο ησαν γαρ σκηνοποιοι την τεχνην[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον [επειθεν]{.greek-omitted} [επειθε]{.greek-added} τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και ο τιμοθεος συνειχετο τω [πνευματι]{.greek-abbr} ο παυλος διαμαρτυρομενος τοις ιουδαιοις [ειναι]{.greek-added} τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων [εκτιναξαμενος]{.greek-omitted} [εκτειναξαμενος]{.greek-added} τα ιματια [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και [μεταβας]{.greek-omitted} [καταβας]{.greek-added} εκειθεν [ηλθεν]{.greek-omitted} [εισηλθεν]{.greek-added} εις οικιαν τινος ονοματι [τιτου]{.greek-added} ιουστου σεβομενου τον [θεον]{.greek-abbr} ου η οικια [ην]{.greek-omitted} συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος [επιστευσεν]{.greek-omitted} [επιστευσε]{.greek-added} τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} επιστευον και [εβαπτιζοντο]{.greek-omitted} [ευαπτιζοντο]{.greek-added}[18:8]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο [κυριος]{.greek-abbr} δι οραματος εν νυκτι τω παυλω μη φοβου αλλα λαλει και μη σιωπησης[18:9]{.aside}

διοτι εγω ειμι μετα σου και ουδεις επιθησεται σοι του κακωσαι σε διοτι λαος [εστιν]{.greek-omitted} [εστι]{.greek-added} μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

[εκαθισεν]{.greek-omitted} [εκαθισε]{.greek-added} τε ενιαυτον και μηνας εξ διδασκων εν αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της αχαιας κατεπεστησαν ομοθυμαδον οι ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον [αναπειθει]{.greek-added} ουτος [αναπειθει]{.greek-omitted} τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν ουν [ην]{.greek-omitted} αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν ηνεσχομην υμων[18:14]{.aside}

ει δε ζητημα [εστιν]{.greek-omitted} [εστι]{.greek-added} περι λογου και ονοματων και νομου του καθ υμας οψεσθε αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι [δε]{.greek-omitted} [τε]{.greek-added} παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω γαλλιωνι εμελλεν[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος εξεπλει εις την συριαν και συν αυτω πρισκιλλα και ακυλας κειραμενος [εγκεχρεαις]{.greek-added} την κεφαλην [εν]{.greek-omitted} [κεγχρεαις]{.greek-omitted} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γαρ ευχην[18:18]{.aside}

[κατηντησεν]{.greek-omitted} [κατηντησαν]{.greek-added} δε εις εφεσον [και]{.greek-omitted} [κακει]{.greek-added} [εκεινους]{.greek-omitted} κατελιπεν [αυτου]{.greek-omitted} [αυτους]{.greek-added} αυτος δε εισελθων εις την συναγωγην [διελεχθη]{.greek-omitted} [διελεγετο]{.greek-added} τοις ιουδαιοις[18:19]{.aside}

ερωτωντων δε [αυτων]{.greek-omitted} [αυτον]{.greek-added} επι πλειονα χρονον μειναι παρ αυτοις ουκ επενευσεν[18:20]{.aside}

αλλ [απεταξατο]{.greek-omitted} [επεταξατο]{.greek-added} αυτοις ειπων δει με παντως την εορτην την ερχομενην ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} [ανοιχθη]{.greek-added} [ανηχθη]{.corr} απο της εφεσου[18:21]{.aside}

και κατελθων εις καισαρειαν αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} ελαλει και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-abbr} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε αυτου ακυλας και πρισκιλλα προσελαβοντο αυτον και ακριβεστερον αυτω εξεθεντο την του [θεου]{.greek-abbr} οδον[18:26]{.aside}

βουλομενου δε αυτου διελθειν εις την αχαιαν προτρεψαμενοι οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος συνεβαλετο πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπιστευκοσι]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω τον απολλω ειναι εν κορινθω παυλον διελθοντα τα ανωτερικα μερη ελθειν εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε ειπον προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

ειπεν [τε]{.greek-omitted} [δε]{.greek-added} προς αυτους εις τι ουν εβαπτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

ειπεν δε παυλος ιωαννης μεν [εβαπτισεν]{.greek-omitted} [εβαπτισε]{.greek-added} βαπτισμα μετανοιας τω λαω λεγων εις τον ερχομενον μετ αυτον ινα [πιστευσωσιν]{.greek-omitted} [πιστευσωσι]{.greek-added} τουτ εστιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και προεφητευον[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει δεκαδυο[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους αποστας απ αυτων [αφωρισεν]{.greek-omitted} [αφωρισε]{.greek-added} τους μαθητας καθ ημεραν διαλεγομενος εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι ετη δυο ωστε παντας τους κατοικουντας την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-omitted} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας εποιει ο [θεος]{.greek-abbr} δια των χειρων παυλου[19:11]{.aside}

ωστε και επι τους ασθενουντας [επιφερεσθαι]{.greek-omitted} [αποφερεσθαι]{.greek-added} απο του χρωτος αυτου σουδαρια η σιμικινθια και [απαλλασσεσθαι]{.greek-omitted} [απαλλαττεσθαι]{.greek-added} απ αυτων τας νοσους τα τε [πνευματα]{.greek-abbr} τα πονηρα [εκπορευεσθαι]{.greek-added} [εξερχεσθαι]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted}[19:12]{.aside}

επεχειρησαν δε τινες απο των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους εχοντας τα [πνευματα]{.greek-abbr} τα πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} λεγοντες ορκιζομεν υμας τον [ιησουν]{.greek-abbr} ον [ο]{.greek-omitted} παυλος κηρυσσει[19:13]{.aside}

ησαν δε τινες υιοι σκευα ιουδαιου αρχιερεως επτα οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε το [πνευμα]{.greek-abbr} το πονηρον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τον [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και εφαλλομενος επ αυτους ο [ανθρωπος]{.greek-abbr} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον και κατακυριευσαν αυτων [ισχυσεν]{.greek-omitted} [ισχυσε]{.greek-added} κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν [εκ]{.greek-omitted} του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον [πασιν]{.greek-omitted} [πασι]{.greek-added} [τοις]{.greek-added} ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} τοις [κατοικουσιν]{.greek-omitted} [κατοικουσι]{.greek-added} την εφεσον και [επεπεσεν]{.greek-omitted} [επεπεσε]{.greek-added} φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι τε των πεπιστευκοτων ηρχοντο εξομολογουμενοι και αναγγελλοντες τας πραξεις αυτων[19:18]{.aside}

ικανοι δε των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και συνεψηφισαν τας τιμας αυτων και ευρον αργυριου μυριαδας πεντε[19:19]{.aside}

ουτως κατα κρατος ο λογος του [κυριου]{.greek-abbr} [ηυξανεν]{.greek-omitted} [ηυξανε]{.greek-added} και ισχυεν[19:20]{.aside}

ως δε επληρωθη [παντα]{.greek-added} ταυτα εθετο ο παυλος εν τω [πνευματι]{.greek-abbr} διελθων την μακεδονιαν και αχαιαν [πορευεσθαι]{.greek-omitted} [πορευθηναι]{.greek-added} εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις την μακεδονιαν δυο των διακονουντων αυτω τιμοθεον και εραστον αυτος [επεσχεν]{.greek-omitted} [επεσχε]{.greek-added} χρονον εις την ασιαν[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος [περι]{.greek-omitted} [κατα]{.greek-added} της οδου[19:23]{.aside}

δημητριος γαρ τις ονοματι αργυροκοπος ποιων ναους αργυρους αρτεμιδος παρειχετο τοις τεχνιταις [εργασιαν]{.greek-omitted} ουκ ολιγην [εργασιαν]{.greek-added}[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας ειπεν ανδρες επιστασθε οτι εκ ταυτης της εργασιας η ευπορια ημων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:25]{.aside}

και θεωρειτε και ακουετε οτι ου μονον εφεσου αλλα σχεδον πασης της ασιας ο παυλος ουτος πεισας μετεστησεν ικανον οχλον λεγων οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} θεοι οι δια χειρων [[ανθρωπων]{.greek-abbr}]{.greek-added} γινομενοι[19:26]{.aside}

ου μονον δε τουτο [κινδυνευει]{.greek-omitted} [κινδυνεβει]{.greek-added} ημιν το μερος εις απελεγμον ελθειν αλλα και το της μεγαλης θεας [αρτεμιδος]{.greek-added} ιερον [αρτεμιδος]{.greek-omitted} [λογισθηναι]{.greek-added} εις [ουθεν]{.greek-omitted} [ουδεν]{.greek-added} [λογισθηναι]{.greek-omitted} μελλειν [δε]{.greek-omitted} και καθαιρεισθαι την μεγαλειοτητα αυτης ην ολη η ασια και η οικουμενη σεβεται[19:27]{.aside}

ακουσαντες δε και γενομενοι [πληρεις]{.greek-omitted} [πληρης]{.greek-added} θυμου εκραζον λεγοντες μεγαλη η αρτεμις εφεσιων[19:28]{.aside}

και επλησθη η πολις ολη της συγχυσεως ωρμησαν τε ομοθυμαδον εις το θεατρον συναρπασαντες γαιον και αρισταρχον μακεδονας συνεκδημους παυλου[19:29]{.aside}

του δε παυλου βουλομενου [εισελθειν]{.greek-omitted} εις τον δημον ουκ ειων αυτον οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες αυτω φιλοι πεμψαντες [προς]{.greek-omitted} αυτον παρεκαλουν μη δουναι εαυτον εις το θεατρον[19:31]{.aside}

αλλοι μεν [ουν]{.greek-omitted} αλλο τι εκραζον ην γαρ η εκκλησια [ολη]{.greek-added} συγκεχυμενη και οι πλειους ουκ [ηδεισαν]{.greek-omitted} [ειδεισαν]{.greek-added} τινος ενεκεν [συνεληλυθεισαν]{.greek-omitted} [συνεληλυθησαν]{.greek-added}[19:32]{.aside}

εκ δε του οχλου προεβιβασαν αλεξανδρον [προβαλοντων]{.greek-omitted} [προβαλλοντων]{.greek-added} αυτον των ιουδαιων ο [δε]{.greek-omitted} [ουν]{.greek-added} αλεξανδρος κατασεισας την χειρα ηθελεν [απολογεισθαι]{.greek-omitted} [απολογησασθαι]{.greek-added} τω δημω[19:33]{.aside}

επιγνοντες δε οτι ιουδαιος [εστιν]{.greek-omitted} [εστι]{.greek-added} φωνη εγενετο μια εκ παντων ως επι ωρας δυο κραζοντων μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλας δε ο γραμματευς τον οχλον φησιν ανδρες εφεσιοι τις γαρ εστιν [ανθρωπος]{.greek-omitted} [[ανθρωπων]{.greek-abbr}]{.greek-added} ος ου γινωσκει την εφεσιων πολιν νεωκορον ουσαν της μεγαλης [θεας]{.greek-omitted} αρτεμιδος και του διοπετους[19:35]{.aside}

αναντιρρητων ουν οντων τουτων δεον εστιν υμας κατεσταλμενους υπαρχειν και μηδεν προπετες πρασσειν[19:36]{.aside}

ηγαγετε γαρ τους ανδρας τουτους ουτε ιεροσυλους ουτε βλασφημουντας την [θεον]{.greek-omitted} [θεαν]{.greek-added} υμων[19:37]{.aside}

ει μεν ουν δημητριος και οι συν αυτω τεχνιται [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν εγκαλειτωσαν αλληλοις[19:38]{.aside}

ει δε τι περι ετερων [επιζητειτε]{.greek-omitted} [ζητειτε]{.greek-added} εν [τη]{.greek-omitted} [τω]{.greek-added} [εννομω]{.greek-omitted} [νομω]{.greek-added} εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι της σημερον μηδενος αιτιου υπαρχοντος περι ου [ου]{.greek-omitted} δυνησομεθα [δουναι]{.greek-omitted} [αποδουναι]{.greek-added} λογον [περι]{.greek-added} της συστροφης ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσε]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον θορυβον προσκαλεσαμενος ο παυλος τους μαθητας [και]{.greek-omitted} ασπασαμενος εξηλθεν [πορευθηναι]{.greek-omitted} εις [την]{.greek-omitted} μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας [τε]{.greek-omitted} [δε]{.greek-added} μηνας τρεις γενομενης αυτω επιβουλης υπο των ιουδαιων μελλοντι αναγεσθαι εις την συριαν εγενετο γνωμη του [υποστρεφειν]{.greek-omitted} [υποστρεψαι]{.greek-added} δια μακεδονιας[20:3]{.aside}

συνειπετο δε αυτω αχρι της ασιας [σωπατρος]{.greek-omitted} [σωσιπατρος]{.greek-added} [βεροιαιος]{.greek-omitted} [βερροιαιος]{.greek-added} θεσσαλονικεων [δε]{.greek-omitted} αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος ασιανοι δε τυχικος και τροφιμος[20:4]{.aside}

ουτοι προσελθοντες [εμενον]{.greek-omitted} [εμμενον]{.greek-added} ημας εν τρωαδι[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και ηλθομεν προς αυτους εις την τρωαδα αχρι [ημερων]{.greek-omitted} [ημερας]{.greek-added} πεντε ου διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων των μαθητων κλασαι αρτον ο παυλος διελεγετο αυτοις μελλων εξιεναι τη επαυριον [παρετεινεν]{.greek-omitted} [παρετεινε]{.greek-added} τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε λαμπαδες ικαναι εν τω υπερωω ου [ημεν]{.greek-omitted} [ησαν]{.greek-added} συνηγμενοι[20:8]{.aside}

καθημενος δε τις νεανιας ονοματι ευτυχος επι της θυριδος καταφερομενος υπνω βαθει διαλεγομενου του παυλου επι πλειον κατενεχθεις απο του υπνου επεσεν απο του τριστεγου κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και συμπεριλαβων ειπεν μη θορυβεισθε η γαρ ψυχη αυτου εν αυτω εστιν[20:10]{.aside}

αναβας δε και κλασας αρτον και γευσαμενος εφ ικανον τε ομιλησας [αχρι]{.greek-omitted} [αχρις]{.greek-added} αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον δε τον παιδα ζωντα και παρεκληθησαν ου μετριως[20:12]{.aside}

ημεις δε προσελθοντες επι το πλοιον ανηχθημεν εις την [ασσον]{.greek-omitted} [θασον]{.greek-added} εκειθεν μελλοντες αναλαμβανειν τον παυλον ουτως γαρ ην [διατεταγμενος]{.greek-omitted} [διατεταγμενον]{.greek-added} μελλων [αυτος]{.greek-omitted} [αυτους]{.greek-added} πεζευειν[20:13]{.aside}

ως δε [συνεβαλεν]{.greek-omitted} [συνε]{.greek-added} [βαλλεν]{.greek-added} ημιν εις την [ασσον]{.greek-omitted} [θασον]{.greek-added} αναλαβοντες αυτον ηλθομεν [εις]{.greek-omitted} [μιτυληνην]{.greek-omitted}[20:14]{.aside}

[κακειθεν]{.greek-omitted} [αποπλευσαντες]{.greek-omitted} [τη]{.greek-omitted} [επιουση]{.greek-omitted} [κατηντησαμεν]{.greek-omitted} [αντικρυ]{.greek-omitted} [αντικρυς]{.greek-added} χιου [τη]{.greek-omitted} [δε]{.greek-omitted} [ετερα]{.greek-omitted} [παρεβαλομεν]{.greek-omitted} εις σαμον και μειναντες εν [τρωγυλλιω]{.greek-omitted} [τρωγγυλιω]{.greek-added} τη εχομενη ηλθομεν εις μιλητον[20:15]{.aside}

[εκρινεν]{.greek-omitted} [κεκρικε]{.greek-added} γαρ ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια [εσπευδεν]{.greek-omitted} [εσπευδε]{.greek-added} γαρ ει δυνατον ην αυτω την ημεραν της πεντηκοστης γενεσθαι εις ιεροσολυμα[20:16]{.aside}

απο δε της μιλητου πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον ειπεν αυτοις υμεις επιστασθε απο πρωτης ημερας αφ ης επεβην εις την ασιαν πως μεθ υμων τον παντα χρονον εγενομην[20:18]{.aside}

δουλευων τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και πολλων δακρυων και πειρασμων των συμβαντων μοι εν ταις επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων του μη αναγγειλαι υμιν και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

διαμαρτυρομενος ιουδαιοις τε και [ελλησιν]{.greek-omitted} [ελλησι]{.greek-added} την εις [τον]{.greek-omitted} [θεον]{.greek-abbr} μετανοιαν και πιστιν την εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr} [[χριστον]{.greek-abbr}]{.greek-added}[20:21]{.aside}

και νυν ιδου [δεδεμενος]{.greek-added} εγω [δεδεμενος]{.greek-omitted} τω [πνευματι]{.greek-abbr} πορευομαι εις [ιερουσαλημ]{.greek-abbr} τα εν αυτη [συναντησοντα]{.greek-omitted} [συναντησαντα]{.greek-added} μοι μη ειδως[20:22]{.aside}

πλην οτι το [πνευμα]{.greek-abbr} το αγιον κατα πολιν διαμαρτυρεται [λεγον]{.greek-omitted} οτι δεσμα [με]{.greek-omitted} και θλιψεις [με]{.greek-added} μενουσιν[20:23]{.aside}

αλλ ουδενος [τουτων]{.greek-added} λογον ποιουμαι ουδε εχω την ψυχην [μου]{.greek-omitted} τιμιαν εμαυτω [ως]{.greek-omitted} [ωστε]{.greek-added} τελειωσαι τον δρομον μου [μετα]{.greek-omitted} [χαρας]{.greek-omitted} και την διακονιαν [μου]{.greek-added} ην ελαβον παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι οψεσθε το προσωπον μου υμεις παντες εν οις διηλθον κηρυσσων την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

διοτι μαρτυρομαι υμιν εν τη σημερον ημερα οτι καθαρος εγω απο του αιματος παντων[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι [υμιν]{.greek-omitted} πασαν την βουλην του [θεου]{.greek-abbr}[20:27]{.aside}

προσεχετε ουν εαυτοις και παντι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επισκοπους ποιμαινειν την εκκλησιαν του [κυριου]{.greek-abbr} και [θεου]{.greek-abbr} ην περιεποιησατο δια του ιδιου αιματος[20:28]{.aside}

εγω γαρ οιδα τουτο οτι εισελευσονται μετα την αφιξιν μου λυκοι βαρεις εις υμας μη φειδομενοι του ποιμνιου[20:29]{.aside}

και εξ υμων αυτων αναστησονται ανδρες λαλουντες διεστραμμενα του αποσπαν τους μαθητας οπισω αυτων[20:30]{.aside}

διο γρηγορειτε [μνημονευοντες]{.greek-omitted} [μνημονεβοντες]{.greek-added} οτι τριετιαν νυκτα και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον[20:31]{.aside}

και τα νυν παρατιθεμαι υμας αδελφοι τω [θεω]{.greek-abbr} και τω λογω της χαριτος αυτου τω δυναμενω εποικοδομησαι και δουναι υμιν κληρονομιαν εν τοις ηγιασμενοις πασιν[20:32]{.aside}

αργυριου η χρυσιου η ιματισμου ουδενος επεθυμησα[20:33]{.aside}

αυτοι γινωσκετε οτι ταις χρειαις μου και τοις [ουσιν]{.greek-omitted} [ουσι]{.greek-added} μετ εμου υπηρετησαν αι χειρες αυται[20:34]{.aside}

παντα υπεδειξα υμιν οτι ουτως κοπιωντας δει αντιλαμβανεσθαι των ασθενουντων μνημονευειν τε των λογων του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} οτι αυτος ειπεν μακαριον [εστιν]{.greek-omitted} [εστι]{.greek-added} μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα γονατα αυτου συν πασιν αυτοις προσηυξατο[20:36]{.aside}

ικανος δε [κλαυθμος]{.greek-added} εγενετο [κλαυθμος]{.greek-omitted} παντων και επιπεσοντες επι τον τραχηλον του παυλου κατεφιλουν αυτον[20:37]{.aside}

οδυνωμενοι μαλιστα επι τω λογω ω ειρηκει οτι ουκετι [μελλουσιν]{.greek-omitted} [μελλουσι]{.greek-added} το προσωπον αυτου θεωρειν προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας αποσπασθεντας απ αυτων ευθυδρομησαντες ηλθομεν εις την [κων]{.greek-omitted} [κω]{.greek-added} τη δε εξης εις [την]{.greek-omitted} ροδον κακειθεν εις παταρα[21:1]{.aside}

και ευροντες πλοιον διαπερων εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

[αναφανεντες]{.greek-omitted} [αναφαναντες]{.greek-added} δε την κυπρον και καταλιποντες αυτην ευωνυμον επλεομεν εις συριαν και [κατηχθημεν]{.greek-omitted} [κατηλθομεν]{.greek-added} εις τυρον εκεισε γαρ [ην]{.greek-omitted} το πλοιον [ην]{.greek-added} αποφορτιζομενον τον γομον[21:3]{.aside}

και ανευροντες μαθητας επεμειναμεν αυτο[υ]{.unclear} ημερας επτα οιτινες τω παυλω ελεγον δια του [πνευματος]{.greek-abbr} μη αναβαινειν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added}[21:4]{.aside}

οτε δε εγενετο ημας [εξαρτισαι]{.greek-omitted} [εξαρτησαι]{.greek-added} τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και τεκνοις εως εξω της πολεως και θεντες τα γονατα [επι]{.greek-omitted} [τον]{.greek-omitted} [αιγιαλον]{.greek-omitted} προσηυξαμεθα[21:5]{.aside}

και ασπασαμενοι αλληλους [επεβημεν]{.greek-omitted} [ανεβημεν]{.greek-added} εις το πλοιον εκεινοι δε υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν διανυσαντες απο τυρου κατηντησαμεν εις [πτολεμαιδα]{.greek-omitted} [πτωλεμαιδα]{.greek-added} και ασπασαμενοι τους αδελφους εμειναμεν ημεραν μιαν παρ αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες [οι]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} [ηλθον]{.greek-omitted} [ηλθομεν]{.greek-added} εις καισαρειαν και εισελθοντες εις τον οικον φιλιππου του ευαγγελιστου οντος εκ των επτα εμειναμεν παρ αυτω[21:8]{.aside}

τουτω δε ησαν θυγατερες παρθενοι τεσσαρες προφητευουσαι[21:9]{.aside}

επιμενοντων δε ημων ημερας πλειους [κατηλθεν]{.greek-omitted} [κατηλθε]{.greek-added} τις απο της ιουδαιας προφητης ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρας την ζωνην του παυλου δησας τε αυτου τους ποδας και τας χειρας ειπεν ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τον ανδρα ου εστιν η ζωνη αυτη ουτως δησουσιν εν [ιερουσαλημ]{.greek-abbr} οι ιουδαιοι και παραδωσουσιν εις χειρας εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκαλουμεν ημεις τε και οι εντοπιοι του μη αναβαινειν αυτον εις [ιερουσαλημ]{.greek-abbr}[21:12]{.aside}

απεκριθη τε ο παυλος τι ποιειτε κλαιοντες και συνθρυπτοντες μου την καρδιαν εγω γαρ ου μονον δεθηναι αλλα και αποθανειν εις [ιερουσαλημ]{.greek-abbr} ετοιμως εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου ησυχασαμεν ειποντες [του]{.greek-added} [[κυριου]{.greek-abbr}]{.greek-added} το θελημα [του]{.greek-omitted} [κυριου]{.greek-omitted} γενεσθω[21:14]{.aside}

μετα δε τας ημερας ταυτας επισκευασαμενοι [ανεβαινομεν]{.greek-omitted} [ανεβημεν]{.greek-added} εις [ιερουσαλημ]{.greek-abbr}[21:15]{.aside}

συνηλθον δε και των [μαθητων]{.greek-omitted} απο καισαρειας συν ημιν αγοντες παρ ω [ξενισθωμεν]{.greek-omitted} [εξενισθημεν]{.greek-added} [μνασωνι]{.greek-omitted} [μεμνασωνι]{.greek-added} τινι κυπριω αρχαιω μαθητη[21:16]{.aside}

γενομενων δε ημων εις ιεροσολυμα ασμενως εδεξαντο ημας οι αδελφοι[21:17]{.aside}

τη δε επιουση [εισηει]{.greek-omitted} [εισειη]{.greek-added} ο παυλος συν ημιν προς ιακωβον παντες [τε]{.greek-omitted} [δε]{.greek-added} παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος αυτους εξηγειτο καθ [εν]{.greek-omitted} [ενα]{.greek-added} εκαστον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δια της διακονιας αυτου[21:19]{.aside}

οι δε ακουσαντες [εδοξαζον]{.greek-omitted} [εδοξασαν]{.greek-added} τον [κυριον]{.greek-omitted} [ειποντες]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} [ειπεν]{.greek-added} [δε]{.greek-added} αυτω θεωρεις αδελφε ποσαι μυριαδες [εισιν]{.greek-omitted} [εισι]{.greek-added} [των]{.greek-added} ιουδαιων των πεπιστευκοτων και παντες ζηλωται του νομου [υπαρχουσιν]{.greek-omitted} [υπαρχουσι]{.greek-added}[21:20]{.aside}

κατηχηθησαν δε περι σου οτι αποστασιαν διδασκεις απο μωυσεως τους κατα τα εθνη [παντας]{.greek-omitted} [παντα]{.greek-added} ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις [εθεσιν]{.greek-omitted} [εθνεσι]{.greek-added} περιπατειν[21:21]{.aside}

τι ουν εστιν παντως δει [συνελθειν]{.greek-added} πληθος [συνελθειν]{.greek-omitted} ακουσονται γαρ οτι εληλυθας[21:22]{.aside}

τουτο ουν ποιησον ο σοι λεγομεν εισιν [γαρ]{.greek-added} [εν]{.greek-added} ημιν ανδρες τεσσαρες [ευχην]{.greek-omitted} [προσευχην]{.greek-added} εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων αγνισθητι συν αυτοις και δαπανησον επ [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ινα [ξυρησωνται]{.greek-omitted} [ξυρησονται]{.greek-added} την κεφαλην και [γνωσιν]{.greek-omitted} [γνωσονται]{.greek-added} παντες οτι ων κατηχηνται περι σου ουδεν εστιν αλλα στοιχεις και αυτος [φυλασσων]{.greek-added} [τ]{.unclear}[ον]{.greek-supplied} νομον [φυλασσων]{.greek-omitted}[21:24]{.aside}

περι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες μηδεν [το]{.greek-added} τοιουτον τηρειν αυτους ει μη φυλασσεσθαι αυτους το τε ειδωλοθυτον και το αιμα και [το]{.greek-added} πνικτον και πορνειαν[21:25]{.aside}

τοτε ο παυλος παραλαβων τους ανδρας τη εχομενη ημερα συν αυτοις αγνισθεις εισηει εις το ιερον διαγγελλων την εκπληρωσιν των ημερων του αγνισμου εως ου προσηνεχθη υπερ ενος εκαστου αυτων η προσφορα[21:26]{.aside}

ως δε εμελλον αι επτα ημεραι συντελεισθαι οι απο της ασιας ιουδαιοι θεασαμενοι αυτον εν τω ιερω συνεχεον παντα τον οχλον και επεβαλον τας χειρας επ αυτον[21:27]{.aside}

κραζοντες ανδρες ισραηλιται βοηθειτε ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου [τουτου]{.greek-omitted} [του]{.greek-added} [αγιου]{.greek-added} παντας πανταχου διδασκων ετι τε και ελληνας εισηγαγεν εις το ιερον και [κεκοινωκεν]{.greek-omitted} [κεκοινωκε]{.greek-added} τον αγιον τοπον τουτον[21:28]{.aside}

ησαν γαρ εωρακοτες τροφιμον τον εφεσιο[ν]{.unclear} εν τη πολει συν αυτω ον ενομιζον οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

εκινηθη τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του παυλου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

ζητουντων δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της σπειρης οτι ολη συγκεχυται [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και εκατονταρχους κατεδραμεν επ αυτους οι δε ιδοντες τον χιλιαρχον και τους στρατιωτας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

εγγισας δε ο χιλιαρχος επελαβετο αυτου και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δεθηναι [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δυσιν και επυνθανετο τις αν ειη και τι [εστιν]{.greek-omitted} [εστι]{.greek-added} πεποιηκως[21:33]{.aside}

αλλοι δε αλλο τι [εβοων]{.greek-omitted} [επεφωνουν]{.greek-added} εν τω οχλω μη [δυναμενος]{.greek-omitted} [δυναμενου]{.greek-added} δε [αυτου]{.greek-added} γνωναι το ασφαλες δια τον θορυβον εκελευσεν αγεσθαι αυτον εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον υπο των στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

[ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} γαρ το πληθος του λαου [κραζον]{.greek-omitted} [κραζοντες]{.greek-added} [αιρε]{.greek-omitted} [αυτον]{.greek-omitted} [ερρε]{.greek-added} [τουτον]{.greek-added}[21:36]{.aside}

μελλων [τε]{.greek-omitted} [δε]{.greek-added} εισαγεσθαι εις την παρεμβολην ο παυλος λεγει τω χιλιαρχω ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι ειπειν [τι]{.greek-added} προς σε ο δε εφη ελληνιστι γινωσκεις[21:37]{.aside}

ουκ αρα συ ει ο αιγυπτιος ο προ τουτων των ημερων αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο παυλος εγω [ανθρωπος]{.greek-abbr} [μεν]{.greek-omitted} ειμι ιουδαιος ταρσευς της κιλικιας ουκ ασημου πολεως πολιτης δεομαι δε σου επιτρεψον μοι λαλησαι προς τον λαον[21:39]{.aside}

επιτρεψαντος δε αυτου ο παυλος εστως επι των αναβαθμων [κατεσεισεν]{.greek-omitted} [κατεσεισε]{.greek-added} τη χειρι [τω]{.greek-omitted} [λαω]{.greek-omitted} [τον]{.greek-added} [λαον]{.greek-added} πολλης δε [γενομενης]{.greek-added} σιγης [γενομενης]{.greek-omitted} [προσεφωνει]{.greek-omitted} [προσεφωνησε]{.greek-added} τη εβραιδι διαλεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς υμας νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη εβραιδι διαλεκτω προσεφωνει αυτοις μαλλον παρεσχον ησυχιαν και φησιν[22:2]{.aside}

εγω μεν ειμι ανηρ ιουδαιος [γεγεννημενος]{.greek-omitted} [γεγενημενος]{.greek-added} [δε]{.greek-added} εν ταρσω της κιλικιας ανατεθραμμενος δε εν τη πολει ταυτη παρα τους ποδας γαμαλιηλ πεπαιδευμενος κατα ακριβειαν του πατρωου νομου ζηλωτης υπαρχων του [θεου]{.greek-abbr} καθως παντες υμεις εστε σημερον[22:3]{.aside}

ος ταυτην την οδον εδιωξα [αχρι]{.greek-omitted} [εως]{.greek-added} θανατου δεσμευων και παραδιδους εις φυλακας ανδρας τε και γυναικας[22:4]{.aside}

ως και ο αρχιερευς μαρτυρει μοι και [παν]{.greek-omitted} [απαν]{.greek-added} το πρεσβυτεριον παρ ων και επιστολας δεξαμενος προς τους αδελφους εις δαμασκον επορευομην αξων και τους εκεισε οντας δεδεμενους εις [ιερουσαλημ]{.greek-abbr} ινα τιμωρηθωσιν[22:5]{.aside}

εγενετο δε μοι πορευομενω και εγγιζοντι τη δαμασκω περι μεσημβριαν εξαιφνης εκ του [ουρανου]{.greek-abbr} [περιαστραψαι]{.greek-omitted} [περιηστραψε]{.greek-added} φως ικανον περι εμε[22:6]{.aside}

[επεσα]{.greek-omitted} [επεσον]{.greek-added} τε εις το εδαφος και [ηκουσα]{.greek-omitted} [ηκουον]{.greek-added} φωνης λεγουσης μοι σαουλ σαουλ τι με διωκεις[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τε προς με εγω ειμι [ιησους]{.greek-abbr} ο ναζωραιος [ον]{.greek-omitted} [συ]{.greek-omitted} [διωκεις]{.greek-omitted}[22:8]{.aside}

οι δε συν εμοι οντες το μεν φως εθεασαντο και εμφοβοι εγενοντο την δε φωνην ουκ ηκουσαν του λαλουντος μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς με αναστας πορευου εις δαμασκον κακει σοι λαληθησεται περι παντων ων τετακται σοι ποιησαι[22:10]{.aside}

ως δε ουκ [ενεβλεπον]{.greek-omitted} [εβλεπον]{.greek-added} απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι ηλθον εις δαμασκον[22:11]{.aside}

ανανιας δε τις ανηρ [ευσεβης]{.greek-omitted} [ευλαβης]{.greek-added} κατα τον νομον μαρτυρουμενος υπο παντων των κατοικουντων ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι σαουλ αδελφε αναβλεψον καγω αυτη τη ωρα ανεβλεψα εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων προεχειρισατο σε γνωναι το θελημα αυτου και ιδειν τον δικαιον και ακουσαι φωνην εκ [του]{.greek-omitted} στοματος αυτου[22:14]{.aside}

οτι εση μαρτυς αυτω προς παντας [ανθρωπους]{.greek-abbr} ων εωρακας και ηκουσας[22:15]{.aside}

και νυν τι μελλεις αναστας βαπτισαι και απολουσαι τας αμαρτιας σου επικαλεσαμενος το ονομ[α]{.unclear} του [κυριου]{.greek-abbr} [[ιησου]{.greek-abbr}]{.greek-added}[22:16]{.aside}

εγενετο δε μοι υποστρεψαντι εις [ιερουσαλημ]{.greek-abbr} και [προσευχομενου]{.greek-omitted} [προσευχομενω]{.greek-added} [μου]{.greek-omitted} [μοι]{.greek-added} εν τω ιερω γενεσθαι με εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον και εξελθε εν ταχει εξ [ιερουσαλημ]{.greek-abbr} διοτι ου παραδεξονται σου την μαρτυριαν περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω ημην φυλακιζων και δερων κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε εξεχειτο το αιμα στεφανου του μαρτυρος σου και αυτος ημην εφεστως και συνευδοκων τη αναιρεσει αυτου [και]{.greek-added} φυλασσων τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς με πορευου οτι εγω εις εθνη μακραν [εξαποστελω]{.greek-omitted} [εξαποστελλω]{.greek-added} σε[22:21]{.aside}

ηκουον δε αυτου αχρι τουτου του λογου και επηραν την φωνην αυτων λεγοντες [αιρε]{.greek-omitted} [ερρε]{.greek-added} απο της γης τον τοιουτον ου γαρ καθηκεν αυτον ζην[22:22]{.aside}

[κραζοντων]{.greek-omitted} [κραυγαζοντων]{.greek-added} δε αυτων και [ριπτουντων]{.greek-omitted} [ριπτοντων]{.greek-added} τα ιματια και κονιορτον βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν [αυτον]{.greek-omitted} ο χιλιαρχος [αγεσθαι]{.greek-omitted} [εισαγεσθαι]{.greek-added} [αυτον]{.greek-added} εις την παρεμβολην ειπων μαστιξιν [ανεταζεσθαι]{.greek-omitted} [αναταζεσθαι]{.greek-added} αυτον ινα επιγνω δι ην αιτιαν ουτως επεφωνουν αυτω[22:24]{.aside}

ως δε προετεινεν αυτον τοις ιμασιν [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς τον [εστωτα]{.greek-omitted} [εφεστωτα]{.greek-added} εκατονταρχον ο παυλος ει [ανθρωπον]{.greek-abbr} ρωμαιον και ακατακριτον εξεστιν υμιν μαστιζειν[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων [απηγγειλεν]{.greek-omitted} τω χιλιαρχω [απηγγειλε]{.greek-added} λεγων ορα τι μελλεις ποιειν ο γαρ [ανθρωπος]{.greek-abbr} ουτος ρωμαιος [εστιν]{.greek-omitted} [εστι]{.greek-added}[22:26]{.aside}

προσελθων δε ο χιλιαρχος ειπεν αυτω λεγε μοι ει συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκριθη [τε]{.greek-omitted} [δε]{.greek-added} ο χιλιαρχος εγω πολλου κεφαλαιου την πολιτειαν ταυτην εκτησαμην ο δε παυλος εφη εγω δε και [γεγεννημαι]{.greek-omitted} [γεγενημαι]{.greek-added}[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες αυτον ανεταζειν και ο χιλιαρχος δε [εφοβηθη]{.greek-omitted} επιγνους οτι ρωμαιος [εστιν]{.greek-omitted} [εστι]{.greek-added} [εφοβηθη]{.greek-added} και οτι ην [αυτον]{.greek-omitted} [δεδεκως]{.greek-omitted} [αυτω]{.greek-added} [δεδωκος]{.greek-added}[22:29]{.aside}

τη δε επαυριον βουλομενος [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} το ασφαλες το τι κατηγορειται [παρα]{.greek-omitted} [υπο]{.greek-added} των ιουδαιων ελυσεν αυτον απο των δεσμων και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} [ελθειν]{.greek-omitted} [συνελθειν]{.greek-added} τους αρχιερεις και [ολον]{.greek-omitted} [παν]{.greek-added} το συνεδριον [αυτων]{.greek-omitted} και καταγαγων τον παυλον εστησεν εις αυτους[22:30]{.aside}

### Chapter 23

ατενισας δε ο παυλος τω συνεδριω ειπεν ανδρες αδελφοι εγω παση συνειδησει αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι ταυτης της ημερας[23:1]{.aside}

ο δε αρχιερευς ανανιας επεταξεν τοις παρεστωσιν αυτω τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τυπτειν σε μελλει ο [θεος]{.greek-abbr} τοιχε κεκονιαμενε και συ καθη κρινων με κατα τον νομον και παρανομων κελευεις [με]{.greek-omitted} [μαι]{.greek-added} τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες ειπον τον αρχιερεα του [θεου]{.greek-abbr} λοιδορεις[23:4]{.aside}

εφη τε ο παυλος ουκ ηδειν αδελφοι οτι εστιν αρχιερευς γεγραπται γαρ [οτι]{.greek-added} αρχοντα του λαου σου ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος [εστιν]{.greek-omitted} [εστι]{.greek-added} σαδδουκαιων το δε ετερον φαρισαιων [εκραξεν]{.greek-omitted} [εκραζεν]{.greek-added} εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμι υιος φαρισαιου περι ελπιδος και αναστασεως νεκρων εγω κρινομαι[23:6]{.aside}

τουτο δε αυτου λαλησαντος εγενετο στασις των φαρισαιων και εσχισθη το πληθος[23:7]{.aside}

σαδδουκαιοι μεν γαρ [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} μη ειναι αναστασιν μηδε αγγελον μητε [πνευμα]{.greek-abbr} φαρισαιοι δε [ομολογουσιν]{.greek-omitted} [ομολογουσι]{.greek-added} τα αμφοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και ανασταντες [οι]{.greek-omitted} γραμματεις του μερους των φαρισαιων διεμαχοντο λεγοντες ουδεν κακον ευρισκομεν εν τω [ανθρωπω]{.greek-abbr} τουτω ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω η αγγελος μη θεομαχωμεν[23:9]{.aside}

πολλης δε γενομενης στασεως ευλαβηθεις ο χιλιαρχος μη διασπασθη ο παυλος [υπ]{.greek-omitted} [απ]{.greek-added} αυτων [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} το στρατευμα καταβηναι και αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση νυκτι επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν θαρσει παυλε ως γαρ διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} [ουτως]{.greek-omitted} [ουτω]{.greek-added} σε δει και εις ρωμην μαρτυρησαι[23:11]{.aside}

γενομενης δε ημερας ποιησαντες τινες των ιουδαιων συστροφην ανεθεματισαν εαυτους λεγοντες μητε φαγειν μητε πιειν εως ου [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} τον παυλον[23:12]{.aside}

ησαν δε πλειους τεσσαρακοντα οι ταυτην την συνωμοσιαν πεποιηκοτες[23:13]{.aside}

οιτινες προσελθοντες τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τοις πρεσβυτεροις ειπον αναθεματι ανεθεματισαμεν εαυτους [μηδενος]{.greek-omitted} [μηθενος]{.greek-added} γευσασθαι εως ου αποκτεινωμεν τον παυλον[23:14]{.aside}

νυν ουν υμεις εμφανισατε τω χιλιαρχω συν τω συνεδριω οπως αυριον [καταγαγη]{.greek-added} αυτον [καταγαγη]{.greek-omitted} προς [υμας]{.greek-omitted} [ημας]{.greek-added} ως [μελλοντας]{.greek-omitted} [μελλοντα]{.greek-added} διαγινωσκειν ακριβεστερον τα περι αυτου ημεις δε προ του εγγισαι [αυτον]{.greek-omitted} [αυτω]{.greek-added} ετοιμοι εσμεν του ανελειν αυτον[23:15]{.aside}

ακουσας δε ο υιος της αδελφης παυλου [το]{.greek-omitted} [την]{.greek-added} [ενεδρον]{.greek-omitted} [ενεδραν]{.greek-added} παραγενομενος και εισελθων εις την παρεμβολην [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τω παυλω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων εφη τον νεανιαν τουτον απαγαγε προς τον χιλιαρχον εχει γαρ [απαγγειλαι]{.greek-added} τι [απαγγειλαι]{.greek-omitted} αυτω[23:17]{.aside}

ο μεν ουν παραλαβων αυτον [ηγαγεν]{.greek-omitted} [ηγαγε]{.greek-added} προς τον χιλιαρχον και φησιν ο δεσμιος παυλος προσκαλεσαμενος με [ηρωτησεν]{.greek-omitted} [τουτον]{.greek-omitted} τον νεανιαν αγαγειν προς σε εχοντα τι λαλησαι σοι[23:18]{.aside}

επιλαβομενος δε της χειρος αυτου ο χιλιαρχος και αναχωρησας κατ ιδιαν επυνθανετο τι εστιν ο εχεις [απαγγειλαι]{.greek-omitted} [αναγγειλαι]{.greek-added} μοι[23:19]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε οτι [οι]{.greek-omitted} ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον [καταγαγης]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} εις το συνεδριον [καταγαγης]{.greek-omitted} [τον]{.greek-omitted} [παυλον]{.greek-omitted} ως μελλοντα τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ ουν μη [πεισθης]{.greek-omitted} [πεισθεις]{.greek-added} αυτοις [ενεδρευουσιν]{.greek-omitted} [ενεδρευουσι]{.greek-added} γαρ αυτον εξ αυτων ανδρες πλειους τεσσαρακοντα οιτινες ανεθεματισαν εαυτους μητε φαγειν μητε πιειν εως ου ανελωσιν αυτον και νυν ετοιμοι [εισιν]{.greek-omitted} [εισι]{.greek-added} προσδεχομενοι την απο σου επαγγελιαν[23:21]{.aside}

ο μεν ουν χιλιαρχος [απελυσεν]{.greek-omitted} [απελυσε]{.greek-added} τον νεανιαν παραγγειλας μηδενι εκλαλησαι οτι ταυτα ενεφανισας προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους [ενοπλους]{.greek-added} οπως πορευθωσιν εως καισαρειας και ιππεις [εβδομηκοντα]{.greek-omitted} [ευδομηκοντα]{.greek-added} και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

κτηνη τε παραστησαι ινα επιβιβασαντες τον παυλον [διασωσωσιν]{.greek-omitted} [διασωσηται]{.greek-added} προς [φηλικα]{.greek-omitted} [φιλικα]{.greek-added} τον ηγεμονα[23:24]{.aside}

γραψας επιστολην περιεχουσαν τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω ηγεμονι [φηλικι]{.greek-omitted} [φιλικι]{.greek-added} χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο των ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι [εξειλομην]{.greek-omitted} [εξειλαμην]{.greek-added} αυτον μαθων οτι ρωμαιος [εστιν]{.greek-omitted} [εστι]{.greek-added}[23:27]{.aside}

βουλομενος δε [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} την αιτιαν δι ην ενεκαλουν αυτω κατηγαγον αυτον εις το συνεδριον αυτων[23:28]{.aside}

ον ευρον εγκαλουμενον περι ζητηματων του νομου αυτων μηδεν [δε]{.greek-added} αξιον θανατου η δεσμων [εχοντα]{.greek-added} εγκλημα [εχοντα]{.greek-omitted}[23:29]{.aside}

μηνυθεισης δε μοι επιβουλης εις τον ανδρα μελλειν εσεσθαι υπο των ιουδαιων εξαυτης επεμψα προς σε παραγγειλας και τοις κατηγοροις λεγειν τα προς αυτον επι σου [ερρωσο[ν]{.unclear}]{.greek-added} [ερρωσο]{.corr}[23:30]{.aside}

οι μεν ουν στρατιωται κατα το διατεταγμενον αυτοις αναλαβοντες τον παυλον ηγαγον δια της νυκτος εις την αντιπατριδα[23:31]{.aside}

τη δε επαυριον εασαντες τους ιππεις [πορευεσθαι]{.greek-omitted} [απερχεσθαι]{.greek-added} συν αυτω [υπεστρεψαν]{.greek-omitted} [απεστρεψαν]{.greek-added} εις την παρεμβολην[23:32]{.aside}

οιτινες εισελθοντες εις την καισαρειαν και [αναδοντες]{.greek-omitted} [επιδοντες]{.greek-added} την επιστολην τω ηγεμονι παρεστησαν και τον παυλον αυτω[23:33]{.aside}

αναγνους δε ο ηγεμων και επερωτησας εκ ποιας επαρχιας [εστιν]{.greek-omitted} [εστι]{.greek-added} και [πυθομενος]{.greek-omitted} [πειθομενος]{.greek-added} οτι απο κιλικιας[23:34]{.aside}

[διακουσομαι]{.greek-omitted} [ακουσομαι]{.greek-added} σου εφη οταν και οι κατηγοροι σου παραγενωνται [κελευσας]{.greek-added} [εκελευσεν]{.greek-omitted} [τε]{.greek-omitted} [αυτον]{.greek-omitted} εν τω πραιτωριω [του]{.greek-added} ηρωδου φυλασσεσθαι [αυτον]{.greek-added}[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη ο αρχιερευς ανανιας μετα [των]{.greek-omitted} πρεσβυτερων [τινων]{.greek-added} και ρητορος τερτυλλου τινος οιτινες [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} τω ηγεμονι κατα του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο κατηγορειν ο τερτυλλος λεγων πολλης ειρηνης τυγχανοντες δια σου και κατορθωματων γινομενων τω εθνει τουτω δια της σης προνοιας[24:2]{.aside}

[παντη]{.greek-omitted} [παντι]{.greek-added} τε και πανταχου αποδεχομεθα κρατιστε [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} μετα πασης ευχαριστιας[24:3]{.aside}

ινα δε μη επι πλειον σε εγκοπτω παρακαλω ακουσαι σε ημων συντομως τη ση επιεικεια[24:4]{.aside}

ευροντες [γαρ]{.greek-omitted} τον ανδρα τουτον λοιμον και κινουντα στασιν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ιουδαιοις τοις κατα την οικουμενην πρωτοστατην τε της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον [επειρασεν]{.greek-omitted} [επειρασαι]{.greek-added} βεβηλωσαι ον και εκρατησαμεν[24:6]{.aside}

παρ ου [δυνηση]{.greek-omitted} [δυνησει]{.greek-added} αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

συνεπεθεντο δε και οι ιουδαιοι φασκοντες ταυτα ουτως εχειν[24:9]{.aside}

απεκριθη [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος νευσαντος αυτω του ηγεμονος λεγειν εκ πολλων ετων οντα σε κριτην τω εθνει τουτω επισταμενος ευθυμοτερον τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} οτι ου πλειους [εισιν]{.greek-omitted} [εισι]{.greek-added} μοι ημεραι δεκαδυο αφ ης ανεβην προσκυνησων [εν]{.greek-omitted} [εις]{.greek-added} [ιερουσαλημ]{.greek-abbr}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η [επισυστασιν]{.greek-omitted} [επιστασιν]{.greek-added} ποιουντα οχλου ουτε εν ταις συναγωγαις ουτε κατα την πολιν[24:12]{.aside}

ουτε παραστησαι [με]{.greek-omitted} δυνανται [σοι]{.greek-added} περι ων νυν [κατηγορουσιν]{.greek-omitted} [κατηγορουσι]{.greek-added} μου[24:13]{.aside}

ομολογω δε τουτο σοι οτι κατα την οδον ην λεγουσιν αιρεσιν ουτως λατρευω τω πατρωω [θεω]{.greek-abbr} πιστευων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατα τον νομον και τοις προφηταις γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι προσδεχονται αναστασιν μελλειν εσεσθαι [νεκρων]{.greek-omitted} δικαιων τε και αδικων[24:15]{.aside}

εν τουτω [δε]{.greek-omitted} [ουν]{.greek-added} [και]{.greek-added} αυτος ασκω απροσκοπον συνειδησιν [εχων]{.greek-omitted} [εχειν]{.greek-added} προς τον [θεον]{.greek-abbr} και τους [ανθρωπους]{.greek-abbr} δια παντος[24:16]{.aside}

δι ετων δε πλειονων παρεγενομην ελεημοσυνας ποιησων εις το εθνος μου και προσφορας[24:17]{.aside}

εν οις ευρον με ηγνισμενον εν τω ιερω ου μετα οχλου ουδε μετα θορυβου [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [δε]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιοι]{.greek-added} ους δει επι σου παρειναι και κατηγορειν ει τι εχοιεν προς με[24:19]{.aside}

η αυτοι ουτοι ειπατωσαν τι ευρον εν εμοι αδικημα σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας [φωνης]{.greek-added} ταυτης [φωνης]{.greek-omitted} ης [εκραξα]{.greek-omitted} [εκεκραξα]{.greek-added} [εστως]{.greek-omitted} εν αυτοις [εστως]{.greek-added} οτι περι αναστασεως νεκρων εγω κρινομαι σημερον [υφ]{.greek-omitted} [εφ]{.greek-added} υμων[24:21]{.aside}

ακουσας δε ταυτα ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [ανεβαλετο]{.greek-omitted} [ανεβαλλετο]{.greek-added} αυτους ακριβεστερον ειδως τα περι της οδου ειπων οταν λυσιας ο χιλιαρχος καταβη διαγνωσομαι τα καθ υμας[24:22]{.aside}

διαταξαμενος τε τω [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} τηρεισθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} εχειν τε ανεσιν και μηδενα κωλυειν των ιδιων αυτου υπηρετειν η προσερχεσθαι αυτω[24:23]{.aside}

μετα δε ημερας τινας παραγενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} συν δρουσιλλη τη [ιδια]{.greek-added} γυναικι [ουση]{.greek-omitted} [ου]{.greek-added} [ση]{.greek-added} ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου περι της εις [χριστον]{.greek-abbr} [[ιησουν]{.greek-abbr}]{.greek-added} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του μελλοντος εσεσθαι εμφοβος γενομενος ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} απεκριθη το νυν εχον πορευου καιρον δε [μεταλαβων]{.greek-omitted} [λαβων]{.greek-added} μετακαλεσομαι σε[24:25]{.aside}

αμα και ελπιζων οτι χρηματα δοθησεται αυτω υπο του παυλου οπως λυση αυτον διο και πυκνοτερον [αυτον]{.greek-omitted} μεταπεμπομενος ωμιλει αυτω[24:26]{.aside}

διετιας δε πληρωθεισης [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} διαδοχον ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} πορκιον φηστον θελων [τε]{.greek-omitted} [χαριτας]{.greek-omitted} [δε]{.greek-added} [χαριν]{.greek-added} καταθεσθαι τοις ιουδαιοις ο [φηλιξ]{.greek-omitted} [φιλιξ]{.greek-added} [κατελιπεν]{.greek-omitted} [κατελιπε]{.greek-added} τον παυλον δεδεμενον[24:27]{.aside}

### Chapter 25

φηστος ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη [απο]{.greek-added} [καισαρειας]{.greek-added} εις ιεροσολυμα [απο]{.greek-omitted} [καισαρειας]{.greek-omitted}[25:1]{.aside}

[ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} αυτω ο αρχιερευς και οι πρωτοι των ιουδαιων κατα του παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται αυτον εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} ενεδραν ποιουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν ουν φηστος απεκριθη τηρεισθαι τον παυλον εν καισαρεια εαυτον δε μελλειν εν ταχει εκπορευεσθαι[25:4]{.aside}

οι ουν δυνατοι εν υμιν [φησιν]{.greek-omitted} [φησι]{.greek-added} συγκαταβαντες ει τι εστιν εν τω ανδρι τουτω [κατηγορειτωσαν]{.greek-omitted} [κατηγορησατωσαν]{.greek-added} αυτου[25:5]{.aside}

διατριψας δε εν αυτοις [ου]{.greek-added} [πλει]{.greek-added} [ονας]{.greek-added} ημερας πλειους η δεκα καταβας εις καισαρειαν τη επαυριον καθισας επι του βηματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τον παυλον αχθηναι[25:6]{.aside}

παραγενομενου δε αυτου περιεστησαν οι απο ιεροσολυμων [καταβεβηκοτες]{.greek-omitted} [καταβαντες]{.greek-added} ιουδαιοι πολλα και βαρεα αιτιωματα φεροντες κατα του παυλου α ουκ ισχυον αποδειξαι[25:7]{.aside}

απολογουμενου [αυτου]{.greek-omitted} οτι ουτε εις τον νομον των ιουδαιων ουτε εις το ιερον ουτε εις καισαρα τι ημαρτον[25:8]{.aside}

ο φηστος δε [θελων]{.greek-added} τοις ιουδαιοις [θελων]{.greek-omitted} χαριν καταθεσθαι αποκριθεις τω παυλω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} θελεις εις ιεροσολυμα αναβας εκει περι τουτων κρινεσθαι επ εμου[25:9]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε ο παυλος επι του βηματος καισαρος εστως ειμι ου με δει κρινεσθαι ιουδαιους ουδεν ηδικησα ως και συ καλλιον επιγινωσκεις[25:10]{.aside}

ει μεν [γαρ]{.greek-omitted} [αδικω]{.greek-omitted} [ουν]{.greek-added} [αδικον]{.greek-added} και αξιον θανατου πεπραχα τι ου παραιτουμαι [το]{.greek-omitted} [του]{.greek-added} αποθανειν ει δε ουδεν εστιν ων ουτοι [κατηγορουσιν]{.greek-omitted} [κατηγορουσι]{.greek-added} μου ουδεις με δυναται αυτοις χαρισασθαι καισαρα επικαλουμαι[25:11]{.aside}

τοτε ο φηστος συλλαλησας μετα του [συμβουλιου]{.greek-omitted} [συμβουλου]{.greek-added} απεκριθη καισαρα [επικεκλησαι]{.greek-omitted} [επικαλησαι]{.greek-added} επι καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τινων αγριππας ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν ασπασαμενοι τον φηστον[25:13]{.aside}

ως δε πλειους ημερας [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added} εκει ο φηστος τω βασιλει ανεθετο τα κατα τον παυλον λεγων ανηρ τις εστιν καταλελειμμενος υπο [φηλικος]{.greek-omitted} [φιληκος]{.greek-added} δεσμιος[25:14]{.aside}

περι ου γενομενου [μου]{.greek-omitted} εις ιεροσολυμα [ενεφανισαν]{.greek-omitted} [ενεφανησαν]{.greek-added} οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα [ανθρωπον]{.greek-abbr} εις απωλειαν πριν η ο κατηγορουμενος κατα προσωπον εχοι τους κατηγορους τοπον τε απολογιας λαβοι περι του εγκληματος[25:16]{.aside}

συνελθοντων ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη εξης καθισας επι του βηματος [εκελευσα]{.greek-omitted} [εκελευσεν]{.greek-added} αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν επεφερον ων υπενοουν [[πονη]{.unclear}ρα]{.greek-added} εγω[25:18]{.aside}

ζητηματα δε τινα περι της ιδιας δεισιδαιμονιας ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τεθνηκοτος ον [εφασκεν]{.greek-omitted} [εφασκον]{.greek-added} ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω την περι [τουτου]{.greek-omitted} [τουτων]{.greek-added} ζητησιν ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} κακει κρινεσθαι περι [τουτων]{.greek-omitted} [τουτου]{.greek-added}[25:20]{.aside}

του δε παυλου [επικαλεσαμενου]{.greek-omitted} [επικαλουμενου]{.greek-added} τηρηθηναι αυτον εις την του σεβαστου διαγνωσιν εκελευσα τηρεισθαι αυτον εως ου [πεμψω]{.greek-omitted} [αναπεμψω]{.greek-added} αυτον [προς]{.greek-omitted} [εις]{.greek-added} καισαρα[25:21]{.aside}

αγριππας δε προς τον φηστον εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της βερνικης μετα πολλης φαντασιας και εισελθοντων εις το ακροατηριον συν τε τοις χιλιαρχοις και [ανδρασιν]{.greek-omitted} [ανδρασι]{.greek-added} τοις κατ εξοχην [ουσιν]{.greek-omitted} της πολεως [ουσι]{.greek-added} και κελευσαντος του φηστου ηχθη ο παυλος[25:23]{.aside}

και φησιν ο φηστος αγριππα [βασιλευ]{.greek-omitted} [βασιλευς]{.greek-added} και παντες οι συμπαροντες ημιν ανδρες θεωρειτε τουτον περι ου [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος των ιουδαιων [ενετυχον]{.greek-omitted} [μοι]{.greek-omitted} εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δειν [αυτον]{.greek-added} ζην [αυτον]{.greek-omitted} μηκετι[25:24]{.aside}

εγω δε καταλαβομενος μηδεν αξιον θανατου αυτον πεπραχεναι και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα πεμπειν [αυτον]{.greek-omitted}[25:25]{.aside}

περι ου ασφαλες τι γραψαι τω κυριω ουκ εχω διο προηγαγον αυτον εφ υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως γενομενης σχω τι γραψαι[25:26]{.aside}

αλογον γαρ μοι δοκει πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη επιτρεπεται σοι [υπερ]{.greek-omitted} [περι]{.greek-added} σεαυτου λεγειν τοτε ο παυλος [απελογειτο]{.greek-omitted} εκτεινας την χειρα [απελογειτο]{.greek-added}[26:1]{.aside}

περι παντων ων εγκαλουμαι υπο ιουδαιων βασιλευ αγριππα ηγημαι εμαυτον μακαριον επι σου μελλων [σημερον]{.greek-added} απολογεισθαι [σημερον]{.greek-omitted}[26:2]{.aside}

μαλιστα γνωστην οντα σε [παντων]{.greek-omitted} των κατα ιουδαιους [ηθων]{.greek-omitted} [εθων]{.greek-added} τε και ζητηματων διο δεομαι [σου]{.greek-omitted} μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ νεοτητος την απ αρχης γενομενην εν τω εθνει μου εν [τε]{.greek-added} ιεροσολυμοις [ισασιν]{.greek-omitted} [ισασι]{.greek-added} παντες [οι]{.greek-omitted} ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν [θελωσιν]{.greek-omitted} [θελωσι]{.greek-added} μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας θρησκειας εζησα φαρισαιος[26:5]{.aside}

και νυν επ ελπιδι της [προς]{.greek-omitted} [εις]{.greek-added} τους [πατερας]{.greek-abbr} επαγγελιας [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} υπο του [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν [εκτενεια]{.greek-omitted} [εκτενια]{.greek-added} νυκτα και ημεραν [λατρευον]{.greek-omitted} [λατρευων]{.greek-added} [επ]{.greek-added} [ελπιζει]{.greek-omitted} [ελπιδι]{.greek-added} καταντησαι περι ης ελπιδος εγκαλουμαι [υπο]{.greek-added} [ιουδαιων]{.greek-added} βασιλευ αγριππα [υπο]{.greek-omitted} [ιουδαιων]{.greek-omitted}[26:7]{.aside}

τι απιστον κ[ρ]{.unclear}ινεται [παρ]{.greek-omitted} [εν]{.greek-added} υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησα εν ιεροσολυμοις και πολλους των αγιων εγω [εν]{.greek-added} φυλακαις κατεκλεισα την παρα των αρχιερεων εξουσιαν λαβων αναιρουμενων [τε]{.greek-omitted} [δε]{.greek-added} αυτων κατηνεγκα ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν περισσως τε εμμαινομενος αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις και πορευομενος εις [την]{.greek-omitted} δαμασκον μετ εξουσιας και επιτροπης της παρα των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον ειδον βασιλευ [αγριππα]{.greek-added} [ουρανοθεν]{.greek-abbr} υπερ την λαμπροτητα του ηλιου περιλαμψαν με φως και τους συν εμοι πορευομενους[26:13]{.aside}

παντων [δε]{.greek-omitted} [τε]{.greek-added} καταπεσοντων ημων εις την γην ηκουσα φωνην [λαλουσαν]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted} [και]{.greek-omitted} λεγουσαν [μοι]{.greek-added} τη εβραιδι διαλεκτω σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε [ειπον]{.greek-omitted} [ειπα]{.greek-added} τις ει [κυριε]{.greek-abbr} ο δε [[κυριος]{.greek-abbr}]{.greek-added} ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[26:15]{.aside}

αλλα αναστηθι [και]{.greek-omitted} [στηθι]{.greek-omitted} επι τους ποδας σου εις τουτο γαρ ωφθην σοι προχειρισασθαι σε υπηρετην και μαρτυρα ων τε ειδες ων τε οφθησομαι σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου και των εθνων εις ους εγω [αποστελω]{.greek-added} σε [αποστελλω]{.greek-omitted}[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του [υποστρεψαι]{.greek-omitted} [απ[ο]{.unclear}στρεψαι]{.greek-added} απο σκοτους εις φως και της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην [απειθης]{.greek-omitted} [απειθεις]{.greek-added} τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον και ιεροσολυμοις εις πασαν [τε]{.greek-omitted} την χωραν της ιουδαιας και τοις εθνεσιν [απαγγελλων]{.greek-omitted} [απηγγελλον]{.greek-added} μετανοειν και επιστρεφειν επι τον [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων [με]{.greek-added} οι ιουδαιοι [με]{.greek-omitted} συλλαβομενοι εν τω ιερω επειρωντο διαχειρισασθαι[26:21]{.aside}

επικουριας ουν τυχων της παρα του [θεου]{.greek-abbr} αχρι της ημερας ταυτης εστηκα μαρτυρομενος μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και [μωυσης]{.greek-omitted} [μωσης]{.greek-added}[26:22]{.aside}

ει παθητος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως μελλει καταγγελλειν τω λαω και τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[26:23]{.aside}

ταυτα δε αυτου απολογουμενου ο φηστος μεγαλη τη φωνη [εφη]{.greek-omitted} [φησιν]{.greek-added} μαινη παυλε τα πολλα σε γραμματα εις μανιαν περιτρεπει[26:24]{.aside}

ο δε ου μαινομαι φησιν κρατιστε φηστε αλλα αληθειας και σωφροσυνης ρηματα αποφθεγγομαι[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον και παρρησιαζομενος λαλω λανθανειν γαρ αυτον τι τουτων ου πειθομαι ουδεν ου γαρ [εστιν]{.greek-added} εν γωνια πεπραγμενον τουτο[26:26]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

ο δε αγριππας προς τον παυλον εφη εν ολιγω με πειθεις χριστιανον γενεσθαι[26:28]{.aside}

ο δε παυλος ειπεν ευξαιμην αν τω [θεω]{.greek-abbr} και εν ολιγω και εν [πολλω]{.greek-omitted} [μεγαλω]{.greek-added} ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος καγω ειμι παρεκτος των δεσμων τουτων[26:29]{.aside}

[και]{.greek-omitted} ταυτα ειποντος αυτου ανεστη ο βασιλευς και ο ηγεμων η τε βερνικη και οι συγκαθημενοι αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν θανατου [αξιον]{.greek-omitted} η δεσμων [αξιον]{.greek-added} [τι]{.greek-added} πρασσει ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω φηστω εφη απολελυσθαι εδυνατο ο [ανθρωπος]{.greek-abbr} ουτος ει μη [επεκεκλητο]{.greek-omitted} [επικεκλ[η]{.unclear}το]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις την ιταλιαν [παρεδιδουν]{.greek-omitted} [παρεδιδου]{.greek-added} τον τε παυλον και τινας ετερους δεσμωτας εκατονταρχη ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω αδραμυττηνω [μελλοντες]{.greek-omitted} [μελλοντι]{.greek-added} πλειν τους κατα την ασιαν τοπους ανηχθημεν οντος συν ημιν αρισταρχου μακεδονος θεσσαλονικεως[27:2]{.aside}

τη τε ετερα κατηχθημεν εις σιδωνα φιλανθρωπως τε ο ιουλιος τω παυλω χρησαμενος [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες κατηλθομεν εις μυρα της λυκιας[27:5]{.aside}

κακει ευρων ο εκατονταρχος πλοιον αλεξανδρινον πλεον εις την ιταλιαν [ενεβιβασεν]{.greek-omitted} [ανεβιβασεν]{.greek-added} ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις βραδυπλοουντες και μολις γενομενοι κατα την κνιδον μη προσεωντος ημας του ανεμου υπεπλευσαμεν την κρητην κατα σαλμωνην[27:7]{.aside}

μολις τε παραλεγομενοι αυτην ηλθομεν εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις λασαια[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος ηδη επισφαλους του πλοος δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των ψυχων ημων μελλειν ε[σ]{.greek-supplied}[ε]{.unclear}σθαι τον πλουν[27:10]{.aside}

ο δε εκατονταρχης τω κυβερνητη και τω ναυκληρω επειθετο μαλλον η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι πλειους εθεντο βουλην αναχθηναι κακειθεν ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λι[μ]{.unclear}ενα της [κρητης]{.greek-omitted} [κριτης]{.greek-added} βλεποντα κατα λιβα και κατα [χωρον]{.greek-omitted} [χωραν]{.greek-added}[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες ασσον παρελεγοντο την κρητην[27:13]{.aside}

μετ ου πολυ δε [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} κατ αυτης ανεμος τυφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι υποδραμοντες καλουμενον κλαυδην μολις ισχυσαμεν περικρατεις γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες βοηθειαις εχρωντο υποζωννυντες το πλοιον φοβουμενοι τε μη [πως]{.greek-added} εις την συρτην [εκπεσωσιν]{.greek-omitted} [εκπεσωσι]{.greek-added} χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως [δε]{.greek-omitted} [τε]{.greek-added} χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη αυτοχειρες την [σκευην]{.greek-omitted} [σκεβην]{.greek-added} του πλοιου ερριψαμεν[27:19]{.aside}

μητε δε ηλιου μητε αστρων επιφαινοντων επι πλειονας ημερας χειμωνος τε ουκ ολιγου επικειμενου λοιπον περιηρειτο πασα ελπις του σωζεσθαι [ημας]{.greek-omitted} [αυτους]{.greek-added}[27:20]{.aside}

πολλης δε ασιτιας υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν [ανδρες]{.greek-added} εδει μεν [ω]{.greek-omitted} [ανδρες]{.greek-omitted} πειθαρχησαντας μοι μη αναγεσθαι απο της κρητης κερδησαι τε την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν παραινω υμας ευθυμειν αποβολη γαρ ψυχης ουδεμια εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι αγγελος του [θεου]{.greek-abbr} ου ειμι ω και λατρευω[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες [πιστευω]{.greek-omitted} [πιστεβω]{.greek-added} γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον λελαληται μοι[27:25]{.aside}

εις νησον δε τινα δει ημας εκπεσειν[27:26]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα [το]{.greek-added} μεσον της νυκτος υπενοουν οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και βολισαντες ευρον [οργυιας]{.greek-omitted} [οργυας]{.greek-added} εικοσι βραχυ δε διαστησαντες και παλιν βολισαντες ευρον [οργυιας]{.greek-omitted} [οργυας]{.greek-added} δεκαπεντε[27:28]{.aside}

φοβουμενοι τε [μη]{.greek-added} [μηπως]{.greek-omitted} [πως]{.greek-added} εις τραχεις τοπους [εκπεσωμεν]{.greek-omitted} [εκπεσωσι]{.greek-added} εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ πρωρας μελλοντων αγκυρας εκτεινειν[27:30]{.aside}

ειπεν ο παυλος τω εκατονταρχη και τοις στρατιωταις εαν μη ουτοι μεινωσιν εν τω πλοιω υμεις [σω]{.greek-added} [σωθηναι]{.greek-omitted} [θηναι]{.greek-added} ου [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added}[27:31]{.aside}

τοτε οι στρατιωται απεκοψαν τα σχοινια της σκαφης και ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου ημελλεν ημερα γινεσθαι παρεκαλει ο παυλος απαντας μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην σημερον ημεραν προσδοκωντες ασιτοι διατελειτε μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας προσλαβειν τροφης τουτο γαρ προς της υμετερας [σωτηριας]{.greek-abbr} υπαρχει ουδενος γαρ υμων θριξ εκ της κεφαλης πεσειται[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον [ευχαριστησεν]{.greek-omitted} [ευχαριστησε]{.greek-added} τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι [δε]{.corr} γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

ημεν δε εν τω πλοιω αι πασαι ψυχαι διακοσιαι [εβδομηκοντα]{.greek-omitted} [ευδομηκοντα]{.greek-added} εξ[27:37]{.aside}

κορεσθεντες δε [της]{.greek-omitted} τροφης εκουφιζον το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον εβουλευσαντο ει δυνατον εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα αν[ε]{.unclear}ντες τας ζευκτηριας των πηδαλιων και επαραντες τον [αρτεμονα]{.greek-omitted} [αρτεμωνα]{.greek-added} τη πνεουση κατειχον εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον επωκειλαν την ναυν και η με[ν]{.unclear} πρωρα ερεισασα εμεινεν ασαλευτος η δε πρυμνα ελυετο υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} μη τις εκκολυμβησας διαφυγη[27:42]{.aside}

ο δε εκατονταρχος βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του βουληματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τε τους δυναμενους κολυμβαν απορριψαντας πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους μεν επι σανισιν ους δε επι τινων των [απο]{.greek-omitted} [επι]{.greek-added} του πλοιου και ουτως εγενετο παντας διασωθηναι επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες [[οι]{.corr}]{.greek-added} [[περι]{.corr}]{.greek-added} [[τον]{.corr}]{.greek-added} [[παυλον]{.corr}]{.greek-added} [[εκ]{.corr}]{.greek-added} [[του]{.corr}]{.greek-added} [[πλοος]{.corr}]{.greek-added} τοτε επεγνωσαν οτι μελιτη η νησος καλειται[28:1]{.aside}

οι δε βαρβαροι παρειχον ου την τυχουσαν [φιλανθρωπιαν]{.greek-abbr} ημιν αναψαντες γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον εφεστωτα και δια το ψυχος[28:2]{.aside}

συστρεψαντος δε του παυλου φρυγανων πληθος και επιθεντος επι την πυραν εχιδνα εκ της θερμης διεξελθουσα [καθηψεν]{.greek-omitted} [καθηψε]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε [ει]{.greek-added} [ειδον]{.greek-omitted} [δον]{.greek-added} οι βαρβαροι κρεμαμενον το θηριον [εκ]{.greek-omitted} [επι]{.greek-added} της χειρος αυτου ελεγον προς αλληλους παντως φονευς εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν αποτιναξας το θηριον εις το πυρ επαθεν ουδεν κακον[28:5]{.aside}

οι δε προσεδοκων αυτον μελλειν [πιμπρασθαι]{.greek-omitted} [πιπρασθαι]{.greek-added} η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων [προσδοκωντων]{.greek-omitted} [προσδοκοντων]{.greek-added} και θεωρουντων μηδεν ατοπον εις αυτον γινομενον μεταβαλλομενοι ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6]{.aside}

εν δε τοις περι τον τοπον εκεινον [υπηρχεν]{.greek-omitted} [υπηρχε]{.greek-added} χωρια τω πρωτω της νησου ονοματι ποπλιω ος αναδεξαμενος ημας τρεις ημερας φιλοφρονως εξενισεν[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του ποπλιου πυρετοις και δυσεντερια συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος επιθεις τας χειρας αυτω ιασατο αυτον[28:8]{.aside}

τουτου ουν γενομενου και οι λοιποι οι εχοντες ασθενειας εν τη νησω προσηρχοντο και εθεραπευοντο[28:9]{.aside}

[οι]{.greek-omitted} και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρειαν[28:10]{.aside}

μετα δε τρεις μηνας [ηχθημεν]{.greek-omitted} [ανηχθημεν]{.greek-added} εν πλοιω παρακεχειμακοτι εν τη νησω αλεξανδρινω παρασημω διοσκουροις[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες κατηντησαμεν εις ρηγιον και μετα μιαν ημεραν επιγενομενου νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις επιμειναι ημερας επτα και ουτως εις την ρωμην ηλθομεν[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περι ημων εξηλθον εις απαντησιν [ημιν]{.greek-omitted} [ημων]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} αππιου φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} θαρσος[28:15]{.aside}

οτε δε ηλθομεν εις ρωμην ο εκατονταρχος [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τους δεσμιους τω στρατοπεδαρχη τω δε παυλω επετραπη μενειν καθ εαυτον συν τω φυλασσοντι αυτον στρατιωτη[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι τον παυλον τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} προς αυτους ανδρες αδελφοι εγω ουδεν εναντιον ποιησας τω λαω η τοις [εθεσιν]{.greek-omitted} [εθεσι]{.greek-added} τοις πατρωοις δεσμιος εξ ιεροσολυμων παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με εβουλοντο [με]{.greek-added} απολυσαι δια το μηδεμιαν αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου [εχον]{.greek-added} [εχων]{.corr} τι [κατηγορησαι]{.greek-omitted} [κατηγορειν]{.greek-added}[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι ενεκεν γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε γραμματα [εδεξαμεθα]{.greek-added} περι σου [εδεξαμεθα]{.greek-omitted} απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν η [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τι περι σου πονηρον[28:21]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον [ημιν]{.greek-added} εστιν [ημιν]{.greek-omitted} οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι [δε]{.greek-omitted} [τε]{.greek-added} αυτω ημεραν [ηλθον]{.greek-added} [ηκον]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} εις την ξενιαν [προς]{.greek-added} [αυτον]{.greek-added} πλειονες οις εξετιθετο διαμαρτυρομενος την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους τα περι του [ιησου]{.greek-abbr} απο τε του νομου [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι καλως το [πνευμα]{.greek-abbr} το αγιον [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} δια ησαιου του προφητου προς τους [πατερας]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added}[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και ειπον ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεψητε]{.greek-added} και ου μη ιδητε[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων [εκαμμυσαν]{.greek-omitted} [εκαμυσαν]{.greek-added} μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και ιασομαι αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη [τουτο]{.greek-added} το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και ταυτα αυτου ειποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις συζητησιν[28:29]{.aside}

[εμεινεν]{.greek-omitted} [εμεινε]{.greek-added} δε ο παυλος διετιαν ολην εν ιδιω μισθωματι και απεδεχετο παντας τους εισπορευομενους προς αυτον[28:30]{.aside}

κηρυσσων την βασιλειαν του [θεου]{.greek-abbr} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} μετα πασης παρρησιας [ακωλυτως]{.greek-omitted} [ακολυτως]{.greek-added}[28:31]{.aside}

