---
title: "Collation of Byz^RP^ vs 31823 (1823)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1823 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31823).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1823                                   	| λογος                              	|
| 1823 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1823 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1823               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1823                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1823 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1823                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 2

[και]{.greek-omitted} [συ]{.greek-omitted} [βηθλεεμ]{.greek-omitted} [γη]{.greek-omitted} [ιουδα]{.greek-omitted} [ουδαμως]{.greek-omitted} [ελαχιστη]{.greek-omitted} [ει]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ηγεμοσιν]{.greek-omitted} [ιουδα]{.greek-omitted} [εκ]{.greek-omitted} [σου]{.greek-omitted} [γαρ]{.greek-omitted} [εξελευσεται]{.greek-omitted} [ηγουμενος]{.greek-omitted} οστις ποιμανει τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους ηκριβωσεν παρ αυτων τον χρονον του [φαινομενου]{.greek-omitted} [φενομενου]{.greek-added} αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεε[μ]{.unclear} ειπεν πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ ον [ειδον]{.greek-omitted} [ιδον]{.greek-added} εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

ιδοντες δε τον αστερα εχαρησαν χαραν μεγαλην σφοδρα[2:10]{.aside}

και ελθοντες [ε]{.unclear}ις την οικιαν ειδον το παιδιον μετ[α]{.unclear} μαριας της [μητρος]{.greek-abbr} [αυτου]{.greek-omitted} [αυτ[ο]{.unclear}]{.greek-added} [και]{.greek-omitted} [πεσοντες]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-supplied} [ανοι]{.greek-supplied}ξαντες τους θησαυρο[υ]{.unclear}[ς]{.greek-supplied} [αυτων]{.greek-supplied} προσηνεγκαν αυτω [δωρα]{.greek-supplied} χρυσον και λιβανον και σμυρναν[2:11]{.aside}

και χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

[α]{.greek-supplied}ναχωρησαντων δε [αυτων]{.greek-omitted} [των]{.greek-added} [μαγων]{.greek-added} ιδου αγγελος [κυριου]{.greek-abbr} [φαινεται]{.greek-omitted} κατ οναρ [φενεται]{.greek-added} τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε εγερθεις [πα]{.unclear}ρελαβεν το παιδι[ον]{.unclear} και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον [υιον]{.greek-abbr} μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι [ενεπαιχθη]{.greek-omitted} [ενεπεχθη]{.greek-added} υπο των μαγων εθυμωθη λιαν και [αποστειλας]{.greek-omitted} [αποστοιλας]{.greek-added} ανειλεν παντας τους παιδας τους εν βηθλεεμ και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις οριοις αυτης απο διετους και κατωτερω [[κατοτερω]{.corr}]{.greek-added} κατα τον χρονον ον ηκριβωσεν παρ[α]{.unclear} [τ]{.unclear}ων μαγων[2:16]{.aside}

τοτε επληρωθη το ρηθεν υπο ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ ηθελεν παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

[τε]{.greek-added} [τελευτησαντος]{.greek-omitted} [λευτησαντος]{.greek-added} δε του ηρωδο[υ]{.unclear} ιδου αγγελος [κυριου]{.greek-abbr} κατ οναρ [φαινεται]{.greek-omitted} [φαινετε]{.greek-added} τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων [εγερθεις]{.greek-omitted} [εγερθοις]{.greek-added} παραλαβε [το]{.unclear} παιδιον και την [μητερα]{.greek-abbr} [α]{.unclear}υτου και πορευου εις γην [ισραηλ]{.greek-abbr} τεθνηκασιν γαρ οι ζητουντες την ψυχην του παιδιου[2:20]{.aside}

ο δε εγερθεις παρελαβεν το παιδιον και την [μητερα]{.greek-abbr} αυτου και ηλθεν εις γην [ισραηλ]{.greek-abbr}[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει επι της ιουδαιας αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν [εις]{.greek-omitted} [οις]{.greek-added} πολιν λεγομενην ναζαρετ οπως πληρωθη το ρηθεν δια των προφητων οτι ναζωραιος κληθησεται[2:23]{.aside}

### Chapter 3

[ε]{.greek-supplied}ν δε ταις [ημεραις]{.greek-omitted} [ημερες]{.greek-added} [εκειναις]{.greek-omitted} [εκεινες]{.greek-added} παραγινεται ιωαννης ο βαπτιστης κηρυσσων εν τη ερημω της ιουδαιας[3:1]{.aside}

και λεγων μετανοειτε ηγγικεν γαρ η βασιλεια των [ουρανων]{.greek-abbr}[3:2]{.aside}

ουτος γαρ εστιν ο ρηθεις υπο [η]{.greek-added} [ησαιου]{.greek-omitted} [σαιου]{.greek-added} του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε ο ι[ω]{.unclear}αννης ειχεν το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον [πασα]{.greek-added} ιεροσολυμα και πασα η [ιουδαια]{.greek-omitted} [ιουδεα]{.greek-added} και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και [εβαπτιζοντο]{.greek-omitted} [εβαπτι]{.greek-added} [ζοντο]{.greek-added} εν τω ιορδανη υπ αυτου [εξομολογουμενοι]{.greek-omitted} [εξομολογουμενη]{.greek-added} τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισ[μ]{.unclear}[α]{.greek-supplied} αυτου [ειπεν]{.greek-omitted} [οιπεν]{.greek-added} αυτοις γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της [[γ]{.unclear}μελλουσης]{.greek-added} [μελλουσης]{.corr} οργης[3:7]{.aside}

ποιησατε ουν καρπον αξιον της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν [εαυτοις]{.greek-omitted} [εαυτης]{.greek-added} [πατερα]{.greek-abbr} εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο [θεος]{.greek-abbr} εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων [κειται]{.greek-omitted} [κειτε]{.greek-added} παν ουν [δενδρον]{.greek-omitted} [δενδρων]{.greek-added} μη ποιουν καρπον [καλον]{.greek-omitted} [καλων]{.greek-added} [εκκοπτεται]{.greek-omitted} [εκκοπτετε]{.greek-added} και εις πυρ βαλλεται[3:10]{.aside}

εγω μεν βαπτιζω υμας εν υδατι [εις]{.greek-omitted} [οις]{.greek-added} μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι αυτος υμας βαπτισει εν [πνευματι]{.greek-abbr} αγιω[3:11]{.aside}

ου το [πτυον]{.greek-omitted} [πτιον]{.greek-added} εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον [αυτου]{.greek-omitted} εις την αποθηκην το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε [παραγινεται]{.greek-omitted} [παραγινετε]{.greek-added} ο [ιησους]{.greek-abbr} απο της γαλιλαιας επι τον ιορδανην [προς]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} του βαπτισθηναι υπ αυτου[3:13]{.aside}

ο δε ιωαννης διεκωλυεν αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν προς αυτον αφες αρτι [ουτως]{.greek-omitted} [ουτω]{.greek-added} γαρ [πρεπον]{.greek-omitted} [πρεπων]{.greek-added} εστιν ημιν πληρωσαι πασαν δικαιοσυνην τοτε αφιησιν αυτον[3:15]{.aside}

και βαπτισθεις ο [ιησους]{.greek-abbr} ανεβη ευθυς απο του υδατος και ιδου ανεωχθησαν αυτω οι [ουρανοι]{.greek-abbr} και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} το [πνευμα]{.greek-abbr} του [θεου]{.greek-abbr} [καταβαινον]{.greek-omitted} [καταβενον]{.greek-added} ωσει περισ[τ]{.unclear}εραν και ερχομενον επ αυτον[3:16]{.aside}

και ιδου φωνη εκ των [ουρανων]{.greek-abbr} λεγουσα ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος εν ω ευδοκησα[3:17]{.aside}

### Chapter 4

τοτε ο [ιησους]{.greek-abbr} ανηχθη [υπο]{.greek-added} [του]{.greek-added} [[πνευματος]{.greek-abbr}]{.greek-added} εις την ερημον [υπο]{.greek-omitted} [του]{.greek-omitted} [πνευματος]{.greek-omitted} [πειρασθηναι]{.greek-omitted} [ποιρασθηναι]{.greek-added} υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} και νυκτας [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} υστερον επεινασεν[4:2]{.aside}

και προσελθων αυτω ο πειραζων ειπεν ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} ειπε ινα οι λιθοι ουτοι αρτοι [γενωνται]{.greek-omitted} [γενωντε]{.greek-added}[4:3]{.aside}

ο δε αποκριθεις ειπεν γεγραπται [οτι]{.greek-added} ουκ επ α[ρ]{.greek-supplied}τω μονω ζησεται [ανθρωπος]{.greek-abbr} αλλ [επι]{.greek-omitted} [εν]{.greek-added} παντι ρηματι εκπορευομενω δια στοματος [θεου]{.greek-abbr}[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του ιερου[4:5]{.aside}

και λεγει αυτω ει [υιος]{.greek-abbr} ει του [θεου]{.greek-abbr} βαλε σεαυτον κατω [γεγραπται]{.greek-omitted} [γεγραπτε]{.greek-added} γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων αρουσιν σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} [παλην]{.greek-added} γεγραπται ουκ [εκπειρασεις]{.greek-omitted} [εκπειρασης]{.greek-added} [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου[4:7]{.aside}

παλιν [παραλαμβανει]{.greek-omitted} [παραλαμβανη]{.greek-added} αυτον ο διαβολος εις ορος υψηλον λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} υπαγε οπισω μου σατανα [γεγραπται]{.greek-omitted} [γεγραπτε]{.greek-added} γαρ [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου [προσκυνησεις]{.greek-omitted} [προσκυνησης]{.greek-added} και αυτω μονω [λατρευσεις]{.greek-omitted} [λατρευσης]{.greek-added}[4:10]{.aside}

τοτε αφιησιν α[υ]{.greek-supplied}τον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} οτι ιωαννης παρεδοθη ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την ναζαρετ ελθων κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και [νεφθαλειμ]{.greek-omitted} [νεφθαλιμ]{.greek-added}[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου [λεγοντος]{.greek-omitted}[4:14]{.aside}

γη ζαβουλων και γη [νε]{.greek-added} [νεφθαλειμ]{.greek-omitted} [φθαλιμ]{.greek-added} οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} φως μεγα και τοις καθημενοις εν χωρα και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε [ηρξατο]{.greek-omitted} ο [ιησους]{.greek-abbr} [ηρξατο]{.greek-added} κηρυσσειν και λεγειν μετανοειτε ηγγικεν γαρ η βασιλεια των ουρανων[4:17]{.aside}

[π]{.unclear}εριπατων δε παρα την θαλασσαν της γαλιλαιας ειδεν δυο αδελφους σιμωνα τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

και λεγει αυτοις δευτε οπισω μου και ποιησω υμας αλιεις [ανθρωπων]{.greek-abbr}[4:19]{.aside}

οι δε ευθεως αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αλλους δυο αδελφους ιακωβον τον του [ζεβεδαιου]{.greek-omitted} [ζεβεδεου]{.greek-added} και ιωαννην τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του [πατρος]{.greek-abbr} αυτων καταρτιζοντας τα δικτυα αυτων και εκαλεσεν αυτους[4:21]{.aside}

οι δε ευθεως [α]{.greek-added} [αφεντες]{.greek-omitted} [φεντες]{.greek-added} το πλοιον και τον [πατερα]{.greek-abbr} αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ολην την γαλιλαιαν [ο]{.greek-omitted} [ιησους]{.greek-omitted} διδασκων εν [ταις]{.greek-omitted} [τες]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγες]{.greek-added} αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και απηλθεν η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας ποικιλαις νοσοις και βασανοις συνεχομενους και δαιμονιζομενους και [παραλυτικους]{.greek-added} [και]{.greek-added} σεληνιαζομενους [και]{.greek-omitted} [παραλυτικους]{.greek-omitted} και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον αυτω οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους λεγων[5:2]{.aside}

μακαριοι οι πτωχοι τω [πνευματι]{.greek-abbr} οτι αυτων εστιν [η]{.greek-omitted} [ει]{.greek-added} βασιλεια των ουρανων[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι [παρακληθησονται]{.greek-omitted} [παρακλυθησονται]{.greek-added}[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομησουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι πεινωντες και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

[μακριοι]{.greek-added} [μακαριοι]{.corr} οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον [θεον]{.greek-abbr} οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι [θεου]{.greek-abbr} κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η βασιλεια των ουρανων[5:10]{.aside}

μακαριοι εστε οταν ονειδισωσιν υμας και διωξωσιν και ειπωσιν παν πονηρον ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι [ο]{.greek-omitted} [μισθος]{.greek-omitted} [μεισθος]{.greek-added} υμων πολυς εν τοις ουρανοις ουτως γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

[υμεις]{.greek-omitted} [εστε]{.greek-omitted} [μης]{.greek-added} [εσται]{.greek-added} το αλας της γης εαν δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των [ανθρωπων]{.greek-abbr}[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις [κρυβηναι]{.greek-omitted} [κρυβυναι]{.greek-added} επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και τιθεασιν αυτον υπο τον μοδιον αλλ επι την λυχνιαν και λαμπει πασιν τοις εν τη οικια[5:15]{.aside}

ουτως [λαμψατω]{.greek-omitted} [λαμ]{.greek-added} [ψατω]{.greek-added} το φως υμων εμπροσθεν των [ανθρωπων]{.greek-abbr} οπως ιδωσιν υμων τα καλα εργα και [δοξασωσιν]{.greek-omitted} [δοξασωσι]{.greek-added} τον [πατερα]{.greek-abbr} υμων τον εν τοις [ουρανοις]{.greek-abbr}[5:16]{.aside}

μη [νομησιτε]{.greek-added} [νομισητε]{.greek-omitted} [[νομησητε]{.corr}]{.greek-added} οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο ουρανος και η γη ιωτα εν η μια κεραια ου μη παρελθη απο του νομου εως αν παντα [γενηται]{.greek-omitted} [γενητε]{.greek-added}[5:18]{.aside}

ος εαν ουν λυση μιαν των εντολων τουτων των ελαχιστων και [διδαξη]{.greek-omitted} [διδαξει]{.greek-added} [ουτως]{.greek-omitted} [ουτος]{.greek-added} τους [ανθρωπους]{.greek-abbr} ελαχιστος κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr} ος δ αν ποιηση και [διδαξη]{.greek-omitted} [διδαξει]{.greek-added} ουτος μεγας κληθησεται εν τη βασιλεια των [ουρανων]{.greek-abbr}[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση η δικαιοσυνη υμων [πλειον]{.greek-omitted} [πλεον]{.greek-added} των γραμματεων και φαρισαιων ου μη εισελθητε εις την βασιλειαν των ουρανων[5:20]{.aside}

[ηκουσατε]{.greek-omitted} [ακουσατε]{.greek-added} οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν φονευση ενοχος εσται τη [κρισει]{.greek-omitted} [κρι]{.greek-added} [σει]{.greek-added}[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει ος δ αν ειπη τω αδελφω αυτου [ρακα]{.greek-omitted} [ρακκα]{.greek-added} ενοχος εσται τω συνεδριω ος δ αν ειπη μωρε ενοχος εσται εις την γεενναν του πυρος[5:22]{.aside}

εαν ουν [προσφερης]{.greek-omitted} [προσφερεις]{.greek-added} το [δωρον]{.greek-omitted} [δορον]{.greek-added} σου επι το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του [θυσιαστηριου]{.greek-omitted} [θυσιαστηρι]{.greek-added} [ου]{.greek-added} και υπαγε πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις [φυλακην]{.greek-omitted} [φυλακυν]{.greek-added} [βληθηση]{.greek-omitted} [βλυθηση]{.greek-added}[5:25]{.aside}

αμην λεγω [σοι]{.greek-omitted} [σει]{.greek-added} ου μη εξελθης εκειθεν εως [αν]{.greek-omitted} [ου]{.greek-added} αποδως τον [εσχατον]{.greek-omitted} [εσχατων]{.greek-added} κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο βλεπων γυναικα προς το [επιθυμησαι]{.greek-omitted} [επιθυμισαι]{.greek-added} αυτην ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

ει δε ο οφθαλμος σου ο δεξιος [σκανδαλιζει]{.greek-omitted} [σκανδαλυζη]{.greek-added} σε εξελε αυτον και βαλε απο σου συμφερει γαρ σοι ινα αποληται εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

ερρεθη [δε]{.greek-omitted} [οτι]{.greek-omitted} ος αν απολυση την γυναικα αυτου δοτω αυτη αποστασιον[5:31]{.aside}

εγω δε λεγω υμιν οτι [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} [πας]{.greek-added} [ο]{.greek-added} [απολυων]{.greek-added} την γυναικα αυτου [πα]{.greek-added} [παρεκτος]{.greek-omitted} [ρεκτος]{.greek-added} λογου [πορνειας]{.greek-omitted} [πορνοιας]{.greek-added} ποιει αυτην μοιχασθαι και ος εαν [απολελυμενην]{.greek-omitted} [απολελυμενυν]{.greek-added} γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ [επιορκησεις]{.greek-omitted} [επιορκησοις]{.greek-added} αποδωσεις δε τω [κυριω]{.greek-abbr} τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη [ομοσαι]{.greek-omitted} [ομωσαι]{.greek-added} ολως μητε εν τω ουρανω οτι θρονος εστιν του [θεου]{.greek-abbr}[5:34]{.aside}

μητε εν τη γη οτι υποποδιον εστιν των ποδων αυτου μητε εις ιεροσολυμα οτι πολις εστιν του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου [ομοσης]{.greek-omitted} [ομωσεις]{.greek-added} οτι ου δυνασαι μιαν τριχα λευκην [ποιησαι]{.greek-added} η μελαιναν [ποιησαι]{.greek-omitted}[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου εστιν[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω [πονηρω]{.greek-omitted} [πωνηρω]{.greek-added} αλλ οστις σε ραπισει επι την δεξιαν σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και τω θελοντι σοι κριθηναι και τον [χιτωνα]{.greek-omitted} [χιτω]{.greek-added} [να]{.greek-added} σου λαβειν αφες αυτω και το ιματιον[5:40]{.aside}

και οστις σε [αγγαρευσει]{.greek-omitted} [αγγαρευσοι]{.greek-added} μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω αιτουντι σε διδου και τον θελοντα απο σου δανεισασθαι μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και [μησισοις]{.greek-added} [μισησεις]{.greek-omitted} [[μισισοις]{.corr}]{.greek-added} τον [εχθρον]{.greek-omitted} [εχθρων]{.greek-added} σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων [ευλογειτε]{.greek-omitted} [ευλογητε]{.greek-added} τους [καταρωμενους]{.greek-omitted} [καταρομενους]{.greek-added} υμας καλως ποιειτε τοις μισουσιν υμας και προσευχεσθε υπερ των επηρεαζοντων [υμας]{.greek-omitted} και διωκοντων υμας[5:44]{.aside}

οπως [υιοι]{.greek-added} [γενησθε]{.corr} [υιοι]{.greek-omitted} του [πατρος]{.greek-abbr} υμων του εν τοις [ουρανοις]{.greek-abbr} οτι τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ [αγαπησητε]{.greek-omitted} [αγαπατε]{.greek-added} τους [αγαπωντας]{.greek-omitted} [αγαποντας]{.greek-added} υμας τινα μισθον εχετε ουχι και οι τελωναι το αυτο ποιουσιν[5:46]{.aside}

και εαν ασπασησθε τους φιλους [υμων]{.greek-omitted} [ημων]{.greek-added} μονον τι περισσον ποιειτε ουχι και οι [τελωναι]{.greek-omitted} [ουτως]{.greek-omitted} [εθνικοι]{.greek-added} [το]{.greek-added} [αυτο]{.greek-added} ποιουσιν[5:47]{.aside}

εσεσθε ουν υμεις [τελειοι]{.greek-omitted} [τελοιοι]{.greek-added} [ωσπερ]{.greek-omitted} [ως]{.greek-added} [και]{.greek-added} ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [ουρανιος]{.greek-added} τελειος εστιν[5:48]{.aside}

### Chapter 6

προσεχετε [δε]{.greek-added} την [ελεημοσυνην]{.greek-omitted} [ελεημοσυνυν]{.greek-added} υμων μη ποιειν εμπροσθεν των [ανθρωπων]{.greek-abbr} προς το [θεαθηναι]{.greek-omitted} [θεαθυναι]{.greek-added} αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1]{.aside}

οταν ουν [ποιης]{.greek-omitted} [ποιεις]{.greek-added} ελεημοσυνην μη [σαλπισης]{.greek-omitted} [σαλπισεις]{.greek-added} εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν [ταις]{.greek-omitted} [τες]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγες]{.greek-added} και εν ταις [ρυμαις]{.greek-omitted} [ρυμες]{.greek-added} οπως δοξασθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν απεχουσιν τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος [ελεημοσυνην]{.greek-omitted} [ελεημοσυνυν]{.greek-added} μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αυτος [αποδωσει]{.greek-omitted} [απωδοσει]{.greek-added} σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ [εση]{.greek-omitted} [εσοι]{.greek-added} ωσπερ οι υποκριται οτι φιλουσιν εν ταις [συναγωγαις]{.greek-omitted} [συναγωγες]{.greek-added} και εν ταις [γωνιαις]{.greek-omitted} [γονι]{.greek-added} [αις]{.greek-added} των πλατειων εστωτες προσευχεσθαι οπως αν φανωσιν τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν οτι απεχουσιν τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το [ταμιειον]{.greek-omitted} [ταμειον]{.greek-added} σου και κλεισας την θυραν σου προσευξαι τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη βαττολογησητε ωσπερ οι εθνικοι [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7]{.aside}

μη ουν ομοιωθητε αυτοις οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ων χρειαν [εχετε]{.greek-omitted} [εχητε]{.greek-added} προ του υμας αιτησαι αυτον[6:8]{.aside}

ουτως ουν [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} υμεις πατερ ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω το ονομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου [ως]{.greek-omitted} [ος]{.greek-added} εν ουρανω και επι της γης[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων [ως]{.greek-omitted} [ος]{.greek-added} και ημεις αφιεμεν τοις οφειλεταις ημων[6:12]{.aside}

και μη εισενεγκης ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα εις τους αιωνας αμην[6:13]{.aside}

εαν γαρ αφητε τοις [ανθρωποις]{.greek-abbr} τα παραπτωματα αυτων αφησει και υμιν ο [πατηρ]{.greek-abbr} υμων ο ουρανιος[6:14]{.aside}

εαν δε μη αφητε τοις [ανθρωποις]{.greek-abbr} [τ[―]{.gap}]{.greek-added} [τα]{.corr} παραπτωματα αυτων ουδε ο [πατηρ]{.greek-abbr} υμων [αφησει]{.greek-omitted} [αφησοι]{.greek-added} τα παραπτωματα υμων[6:15]{.aside}

οταν δε νηστευητε μη [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ωσπερ οι υποκριται σκυθρωποι αφανιζουσιν γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} νηστευοντες αμην λεγω υμιν οτι απεχουσιν τον μισθον αυτων[6:16]{.aside}

συ δε νηστευων αλειψαι σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις [ανθρωποις]{.greek-abbr} νηστευων αλλα τω [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλεπων εν τω κρυπτω αποδωσει σοι[6:18]{.aside}

μη [θησαυριζετε]{.greek-omitted} [θησαυριζεται]{.greek-added} [δε]{.greek-added} υμιν θησαυρους επι της γης οπου [σης]{.greek-omitted} [σις]{.greek-added} και [βρωσις]{.greek-omitted} [βρωσεις]{.greek-added} αφανιζει και οπου κλεπται διορυσσουσιν και κλεπτουσιν[6:19]{.aside}

οπου γαρ εστιν ο [θηαυρος]{.greek-added} [θησαυρος]{.corr} υμων εκει εσται και η καρδια υμων[6:21]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν [η]{.greek-added} ο οφθαλμος σου απλους [η]{.greek-omitted} ολον το σωμα σου [φωτεινον]{.greek-omitted} [φωτινον]{.greek-added} εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος εστιν το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η ενος ανθεξεται και του ετερου καταφρονησει ου δυνασθε θεω δουλευειν και μαμωνα[6:24]{.aside}

δια [τουτο]{.greek-omitted} [τουτω]{.greek-added} λεγω υμιν μη μεριμνατε τη [ψυχη]{.greek-omitted} [ψηχυ]{.greek-added} υμων τι φαγητε και τι [πιητε]{.greek-omitted} [ποιητε]{.greek-added} μηδε τω σωματι υμων τι ενδυσησθε ουχι η ψυχη πλειον εστιν της τροφης και [το]{.greek-omitted} [τω]{.greek-added} σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα [πετεινα]{.greek-omitted} [πετοινα]{.greek-added} του [ουρανου]{.greek-abbr} οτι ου σπειρουσιν ουδε θεριζουσιν ουδε συναγουσιν εις αποθηκας και ο [πατηρ]{.greek-abbr} υμων ο ουρανιος [τρεφει]{.greek-omitted} [τρε]{.greek-added} [φη]{.greek-added} αυτα ουχ [υμεις]{.greek-omitted} [υμοις]{.greek-added} μαλλον [διαφερετε]{.greek-omitted} [διαφερεται]{.greek-added} αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται [προσθειναι]{.greek-omitted} [προσθηναι]{.greek-added} επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως [αυξανει]{.greek-omitted} [αυξανη]{.greek-added} ου κοπια ουδε [νηθει]{.greek-omitted} [νηθη]{.greek-added}[6:28]{.aside}

λεγω δε υμιν οτι ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλομενον ο [θεος]{.greek-abbr} ουτως αμφιεννυσιν ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν [μεριμνησητε]{.greek-omitted} [μεριμνησετε]{.greek-added} [λε]{.greek-added} [λεγοντες]{.greek-omitted} [γοντες]{.greek-added} τι [φαγωμεν]{.greek-omitted} [φαγομεν]{.greek-added} η τι [πιωμεν]{.greek-omitted} [πιομεν]{.greek-added} η τι [περιβαλωμεθα]{.greek-omitted} [περιβαλομεθα]{.greek-added}[6:31]{.aside}

παντα γαρ ταυτα τα εθνη [επιζητει]{.greek-omitted} [επιζητη]{.greek-added} οιδεν γαρ ο [πατηρ]{.greek-abbr} υμων ο ουρανιος οτι [χρηζετε]{.greek-omitted} [χριζεται]{.greek-added} τουτων απαντων[6:32]{.aside}

ζητειτε δε πρωτον την βασιλειαν του [θεου]{.greek-abbr} και την [δικαιοσυνην]{.greek-omitted} [δικαιοσυνυν]{.greek-added} αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ουν [μεριμνησητε]{.greek-omitted} [μεριμνησετε]{.greek-added} εις την αυριον η γαρ αυριον [μεριμνησει]{.greek-omitted} [μεριμνυσοι]{.greek-added} τα εαυτης αρκετον τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

μη κρινετε [ινα]{.greek-omitted} [και]{.greek-added} [ου]{.greek-added} μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε κριθησεσθε και εν ω μετρω [μετρειτε]{.greek-omitted} [με]{.greek-added} [τρειται]{.greek-added} [μετρηθησεται]{.greek-omitted} [μετριθησεται]{.greek-added} υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος [το]{.greek-omitted} [τω]{.greek-added} εν τω οφθαλμω του αδελφου σου την δε εν τω σω οφθαλμω δοκον ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος απο του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε [διαβλεψεις]{.greek-omitted} [διαβλεψης]{.greek-added} [εκβαλειν]{.greek-omitted} [εκβαλην]{.greek-added} το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη [δωτε]{.greek-omitted} [δοτε]{.greek-added} το αγιον τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε βαλητε τους [μαργαριτας]{.greek-omitted} [μαργαρι]{.greek-added} [τας]{.greek-added} υμων εμπροσθεν των χοιρων μηποτε [καταπατησωσιν]{.greek-omitted} [καταπατησουσιν]{.greek-added} αυτους εν τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

αιτειτε και δοθησεται υμιν ζητειτε και [ευρησετε]{.greek-omitted} [ευρησεται]{.greek-added} [κρουετε]{.greek-omitted} [κρουεται]{.greek-added} και [ανοιγησεται]{.greek-omitted} [ανοιγησετε]{.greek-added} υμιν[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων [ευρισκει]{.greek-omitted} [ευρυσκη]{.greek-added} και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις [εστιν]{.greek-omitted} εξ υμων [ανθρωπος]{.greek-abbr} ον [εαν]{.greek-omitted} [αιτηση]{.greek-omitted} [αιτησει]{.greek-added} ο [υιος]{.greek-abbr} αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

και εαν ιχθυν [αιτηση]{.greek-omitted} [αιτησει]{.greek-added} μη οφιν επιδωσει αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} δωσει αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

παντα ουν οσα αν θελητε ινα ποιωσιν υμιν οι [ανθρωποι]{.greek-abbr} [ουτως]{.greek-omitted} και υμεις [ουτως]{.greek-added} ποιειτε αυτοις [ουτος]{.greek-omitted} [ουτως]{.greek-added} γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

[εισελθετε]{.greek-omitted} [εισελθατε]{.greek-added} δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα [εις]{.greek-omitted} [την]{.greek-omitted} [οις]{.greek-added} [τυν]{.greek-added} απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

τι στενη η πυλη και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

[προσεχετε]{.greek-omitted} [προσεχεται]{.greek-added} [δε]{.greek-omitted} απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} προβατων εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον σαπρον καρπους καλους ποιειν[7:18]{.aside}

παν δενδρον μη ποιουν καρπον καλον εκκοπτεται και [εις]{.greek-omitted} [oις]{.greek-added} πυρ [βαλλεται]{.greek-omitted} [βαλλετε]{.greek-added}[7:19]{.aside}

αρα γε απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων μοι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} [εισελευσεται]{.greek-omitted} [εισελευσετε]{.greek-added} [εις]{.greek-omitted} [οις]{.greek-added} την [βασιλειαν]{.greek-omitted} [βασιλοιαν]{.greek-added} των [ουρανων]{.greek-abbr} αλλ ο ποιων το θελημα του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr}[7:21]{.aside}

πολλοι ερουσιν μοι εν [εκεινη]{.greek-omitted} [εκοινη]{.greek-added} τη [ημερα]{.greek-omitted} [υμερα]{.greek-added} [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ου τω σω ονοματι [προεφητευσαμεν]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [σω]{.greek-omitted} [ονοματι]{.greek-omitted} [δαιμονια]{.greek-omitted} [δεμονια]{.greek-added} εξεβαλομεν και τω σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε [ο]{.greek-added} [ομολογησω]{.greek-omitted} [μολογησω]{.greek-added} αυτοις οτι [ουδεποτε]{.greek-omitted} [ουδεπωτε]{.greek-added} εγνων υμας [αποχωρειτε]{.greek-omitted} [αποχωροιτε]{.greek-added} απ εμου [παντες]{.greek-added} οι εργαζομενοι την ανομιαν[7:23]{.aside}

πας [ουν]{.greek-omitted} οστις [ακουει]{.greek-omitted} [ακουοι]{.greek-added} μου τους λογους τουτους και ποιει αυτους [ομοιωσω]{.greek-omitted} [ωμοιωσω]{.greek-added} αυτον ανδρι φρονιμω οστις ωκοδομησεν την οικιαν α[υτ]{.unclear}ου επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και [επνευσαν]{.greek-omitted} [οι]{.greek-omitted} [ανεμοι]{.greek-omitted} [και]{.greek-omitted} [προσεπεσον]{.greek-omitted} [προσεπεσαν]{.greek-added} τη οικια εκεινη και ουκ επεσεν τεθεμελιωτο γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω [οστις]{.greek-omitted} [ωστις]{.greek-added} [ω]{.greek-added} [ωκοδομησεν]{.greek-omitted} [κοδομησεν]{.greek-added} την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεκοψαν τη οικια εκεινη και επεσεν και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγενετο οτε [συνετελεσεν]{.greek-omitted} [ετελεσεν]{.greek-added} ο [ιησους]{.greek-abbr} τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις [αυτων]{.greek-added}[7:29]{.aside}

### Chapter 8

[κ]{.greek-supplied}αταβαντι δε αυτω απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου λεπρος [ελθων]{.greek-omitted} προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} εαν θελης [δυνασαι]{.greek-omitted} [δυνασε]{.greek-added} με καθαρισαι[8:2]{.aside}

και εκτεινας την χειρα ηψατο αυτου ο [ιησους]{.greek-abbr} λεγων θελω [καθαρισθητι]{.greek-omitted} [καθαρυσ]{.greek-added} [θητι]{.greek-added} και ευθεως εκαθαρισθη αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} ορα μηδενι ειπης [αλλα]{.greek-omitted} [αλλ]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε το [δωρον]{.greek-omitted} [δορον]{.greek-added} ο προσεταξεν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[8:4]{.aside}

εισελθοντι δε αυτω [ε]{.greek-supplied}ις καπερναουμ προσηλθεν αυτω εκατονταρχος παρακαλων αυτον[8:5]{.aside}

και λεγων [κυριε]{.greek-abbr} ο παις μου [βεβληται]{.greek-omitted} [βεβλητε]{.greek-added} εν τη οικια παραλυτικος δεινως βασανιζομενος[8:6]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} εγω ελθων θεραπευσω αυτον[8:7]{.aside}

και αποκριθεις ο εκατονταρχος εφη [κυριε]{.greek-abbr} ουκ ειμι ικανος ινα μου υπο την [στεγην]{.greek-omitted} [στεγυν]{.greek-added} εισελθης αλλα μονον ειπε [λογω]{.greek-omitted} [λογον]{.greek-added} και [ια]{.greek-added} [ιαθησεται]{.greek-omitted} [θησεται]{.greek-added} ο παις μου[8:8]{.aside}

και γαρ εγω [ανθρωπος]{.greek-abbr} [ειμι]{.greek-omitted} [ειμη]{.greek-added} υπο εξουσιαν εχων υπ εμαυτον στρατιωτας και λεγω τουτω πορευθητι και πορευεται και αλλω ερχου και ερχεται και τω δουλω μου ποιησον τουτο και ποιει[8:9]{.aside}

ακουσας δε ο [ιησους]{.greek-abbr} εθαυμασεν και ειπεν τοις ακολουθουσιν αμην λεγω υμιν ουδε εν τω [ισραηλ]{.greek-abbr} τοσαυτην πιστιν ευρον[8:10]{.aside}

λεγω δε υμιν οτι πολλοι απο ανατολων και δυσμων ηξουσιν και [ανακλιθησονται]{.greek-omitted} [ανακλιθησοντε]{.greek-added} μετα αβρααμ και ισαακ και ιακωβ εν τη βασιλεια των ουρανων[8:11]{.aside}

οι δε υιοι της βασιλειας εκβληθησονται εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[8:12]{.aside}

και ειπεν ο [ιησους]{.greek-abbr} τω [ε]{.greek-added} [εκατονταρχη]{.greek-omitted} [κατονταρχη]{.greek-added} υπαγε [και]{.greek-omitted} ως επιστευσας γενηθητω σοι και ιαθη ο παις αυτου εν τη ωρα εκεινη[8:13]{.aside}

και ελθων ο [ιησους]{.greek-abbr} εις την οικιαν πετρου ειδεν την πενθεραν αυτου βεβλημενην και πυρεσσουσαν[8:14]{.aside}

και ηψατο της χειρος αυτης και αφηκεν αυτην ο πυρετος και ηγερθη και διηκονει αυτω[8:15]{.aside}

οψιας δε γενομενης προσηνεγκαν αυτω δαιμονιζομενους πολλους και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} τα πνευματα λογω και παντας τους κακως εχοντας εθεραπευσεν[8:16]{.aside}

οπως [πληρωθη]{.greek-omitted} [πλυρωθη]{.greek-added} το ρηθεν [δια]{.greek-omitted} [υπο]{.greek-added} ησαιου του προφητου [λεγοντος]{.greek-omitted} [λεγον]{.greek-added} [τος]{.greek-added} [αυτος]{.greek-omitted} [ουτος]{.greek-added} τας [ασθενειας]{.greek-omitted} [ασθενιας]{.greek-added} ημων ελαβεν και τας νοσους εβαστασεν[8:17]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} πολλους οχλους περι αυτον εκελευσεν απελθειν εις το περαν[8:18]{.aside}

και προσελθων εις γραμματευς ειπεν αυτω διδασκαλε ακολουθησω σοι οπου εαν απερχη[8:19]{.aside}

και [λεγει]{.greek-omitted} [λεγοι]{.greek-added} αυτω ο [ιησους]{.greek-abbr} αι αλωπεκες [φωλεους]{.greek-omitted} [φολεους]{.greek-added} εχουσιν και τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνωσεις ο δε [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ εχει που την κεφαλην [κλινη]{.greek-omitted} [κλινει]{.greek-added}[8:20]{.aside}

ετερος δε των μαθητων αυτου ειπεν αυτω [κυριε]{.greek-abbr} επιτρεψον μοι πρωτον [α]{.greek-added} [απελθειν]{.greek-omitted} [πελθοιν]{.greek-added} [και]{.greek-omitted} θαψαι τον [πατερα]{.greek-abbr} [μου]{.greek-omitted} [[μιου]{.corr}]{.greek-added}[8:21]{.aside}

ο δε [ιησους]{.greek-omitted} ειπεν αυτω ακολουθει μοι και αφες τους νεκρους θαψαι τους εαυτων νεκρους[8:22]{.aside}

και εμβαντι αυτω εις το πλοιον ηκολουθησαν αυτω οι μαθηται αυτου[8:23]{.aside}

και ιδου σεισμος μεγας εγενετο εν τη θαλασση ωστε το πλοιον καλυπτεσθαι υπο των κυματων αυτος δε εκαθευδεν[8:24]{.aside}

και προσελθοντες οι μαθηται [αυτου]{.greek-added} ηγειραν αυτον λεγοντες [κυριε]{.greek-abbr} σωσον ημας απολλυμεθα[8:25]{.aside}

και [λεγει]{.greek-omitted} [λεγοι]{.greek-added} αυτοις τι δειλοι [εστε]{.greek-omitted} [εσται]{.greek-added} ολιγοπιστοι τοτε εγερθεις επετιμησεν τοις ανεμοις και τη θαλασση και εγενετο [γαληνη]{.greek-omitted} [γαλυνη]{.greek-added} μεγαλη[8:26]{.aside}

οι δε [ανθρωποι]{.greek-abbr} εθαυμασαν λεγοντες ποταπος εστιν ουτος οτι και οι ανεμοι και η θαλασσα υπακουουσιν αυτω[8:27]{.aside}

και ελθοντι αυτω εις το περαν εις την χωραν των [γεργεσηνων]{.greek-omitted} [γεργεσινων]{.greek-added} υπηντησαν αυτω δυο δαιμονιζομενοι εκ των μνημειων εξερχομενοι χαλεποι λιαν ωστε μη ισχυειν τινα παρελθειν δια της οδου εκεινης[8:28]{.aside}

και ιδου εκραξαν λεγοντες τι ημιν και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} ηλθες ωδε προ καιρου βασανισαι ημας[8:29]{.aside}

ην δε μακραν απ αυτων αγελη χοιρων πολλων βοσκομενη[8:30]{.aside}

οι δε δαιμονες παρεκαλουν αυτον λεγοντες ει [εκβαλλεις]{.greek-omitted} [εκβαλεις]{.greek-added} ημας επιτρεψον ημιν απελθειν εις την αγελην των χοιρων[8:31]{.aside}

και [ειπεν]{.greek-omitted} [επετρεψεν]{.greek-added} αυτοις [υπαγετε]{.greek-omitted} οι δε εξελθοντες απηλθον εις την αγελην των χοιρων και ιδου [ωρμησεν]{.greek-omitted} [ορμησεν]{.greek-added} πασα η αγελη των χοιρων κατα του κρημνου εις την θαλασσαν και απεθανον εν τοις υδασιν[8:32]{.aside}

οι δε βοσκοντες εφυγον και απελθοντες εις την πολιν απηγγειλαν παντα και τα των δαιμονιζομενων[8:33]{.aside}

και ιδου πασα η πολις εξηλθεν εις συναντησιν τω [ιησου]{.greek-abbr} και ιδοντες αυτον παρεκαλεσαν οπως μεταβη απο των οριων αυτων[8:34]{.aside}

### Chapter 9

και εμβας εις [το]{.greek-omitted} πλοιον διεπερασεν και ηλθεν εις την ιδιαν πολιν[9:1]{.aside}

και ιδου προσεφερον αυτω παραλυτικον επι κλινης βεβλημενον και ιδων ο [ιησους]{.greek-abbr} την πιστιν αυτων ειπεν τω παραλυτικω [θαρσει]{.greek-omitted} [θαρσοι]{.greek-added} τεκνον [αφεωνται]{.greek-omitted} [αφεωντε]{.greek-added} σοι αι αμαρτιαι σου[9:2]{.aside}

και ιδου τινες των γραμματεων ειπον εν εαυτοις ουτος βλασφημει[9:3]{.aside}

και ιδων ο [ιησους]{.greek-abbr} τας [ενθυμησεις]{.greek-omitted} [ενθυμησοις]{.greek-added} αυτων ειπεν [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} υμεις ενθυμεισθε πονηρα εν [ταις]{.greek-omitted} [τες]{.greek-added} καρδιαις υμων[9:4]{.aside}

τι γαρ εστιν ευκοπωτερον ειπειν αφεωνται [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και περιπατει[9:5]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επι της γης αφιεναι αμαρτιας [τοτε]{.greek-omitted} λεγει τω παραλυτικω εγερθεις αρον σου την [κλινην]{.greek-omitted} [κλυνην]{.greek-added} και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι [εθαυμασαν]{.greek-omitted} [εφοβηθησαν]{.greek-added} και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα [εξουσιαν]{.greek-omitted} [τοιαυτην]{.greek-omitted} [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted}[9:8]{.aside}

### Chapter 10

[και]{.greek-omitted} [εχθροι]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [οι]{.greek-omitted} [κοι]{.greek-added} [οικειακοι]{.greek-omitted} αυτου[10:36]{.aside}

ο φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ εστιν μου αξιος και ο φιλων [υιον]{.greek-abbr} η θυγατερα υπερ εμε ουκ εστιν μου αξιος[10:37]{.aside}

και ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ εστιν μου αξιος[10:38]{.aside}

ο ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησει αυτην[10:39]{.aside}

ο δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον [αποστειλαντα]{.greek-omitted} [αποστoιλαντα]{.greek-added} με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος [δικαιον]{.greek-omitted} [δικεον]{.greek-added} εις ονομα [δικαιου]{.greek-omitted} [δικεου]{.greek-added} μισθον δικαιου ληψεται[10:41]{.aside}

και ος εαν [ποτιση]{.greek-omitted} [ποτηση]{.greek-added} ενα των μικρων τουτων [των]{.greek-added} [ελαχιστων]{.greek-added} ποτηριον ψυχρου μονον εις ονομα μαθητου αμην λεγω υμιν ου μη [[υ]{.unclear}πολεση]{.greek-added} [απολεση]{.corr} τον μισθον αυτου[10:42]{.aside}

### Chapter 11

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων τοις δωδεκα μαθηταις αυτου μετεβη εκειθεν του διδασκειν και κηρυσσειν εν ταις πολεσιν αυτων[11:1]{.aside}

ο δε ιωαννης ακουσας εν τω [δεσμωτηριω]{.greek-omitted} [δεσμοτηριω]{.greek-added} τα εργα του [χριστου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} πεμψας δυο των μαθητων αυτου[11:2]{.aside}

ειπεν αυτω συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι αναβλεπουσιν και χωλοι περιπατουσιν λεπροι καθαριζονται και κωφοι ακουουσιν νεκροι [εγειρονται]{.greek-omitted} [εγειροντε]{.greek-added} και πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος εστιν ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

τουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωαννου τι εξηλθετε εις την ερημον [θεασασθαι]{.greek-omitted} [θεασασθε]{.greek-added} καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

αλλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν προφητην ναι λεγω υμιν και περισσοτερον [προ]{.greek-added} [προφητου]{.greek-omitted} [φητου]{.greek-added}[11:9]{.aside}

ουτος γαρ εστιν περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

αμην λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων μειζων ιωαννου του βαπτιστου ο δε μικροτερος εν τη βασιλεια των ουρανων μειζων αυτου εστιν[11:11]{.aside}

απο δε των ημερων ιωαννου του βαπτιστου εως αρτι η βασιλεια των ουρανων [βια]{.greek-added} [βιαζεται]{.greek-omitted} [ζεται]{.greek-added} και βιασται αρπαζουσιν αυτην[11:12]{.aside}

παντες γαρ οι προφηται και ο νομος εως ιωαννου προεφητευσαν[11:13]{.aside}

και ει [θελετε]{.greek-omitted} [θελεται]{.greek-added} δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

ο εχων ωτα ακουειν ακουετω[11:15]{.aside}

τινι δε ομοιωσω την γενεαν ταυτην ομοια εστιν παιδιοις [καθεζομενοις]{.greek-added} εν [ταις]{.greek-added} αγοραις [α]{.greek-added} [καθημενοις]{.greek-omitted} [και]{.greek-omitted} [προσφωνουσιν]{.greek-omitted} [προσφωνουντα]{.greek-added} τοις [εταιροις]{.greek-omitted} [ετεροις]{.greek-added} αυτων[11:16]{.aside}

[και]{.greek-omitted} λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ [ωρχησασθε]{.greek-omitted} [ορχησασθαι]{.greek-added} [εθρηνησαμεν]{.greek-omitted} [εθρυνησαμεν]{.greek-added} υμιν και ουκ [εκοψασθε]{.greek-omitted} [εκοψασθαι]{.greek-added}[11:17]{.aside}

ηλθεν γαρ [προς]{.greek-added} [ημας]{.greek-added} ιωαννης μητε εσθιων μητε πινων και λεγουσιν δαιμονιον εχει[11:18]{.aside}

ηλθεν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εσθιων και πινων και λεγουσιν ιδου [ανθρωπος]{.greek-abbr} φαγος και οινοποτης τελωνων φιλος και αμαρτωλων και εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

τοτε ηρξατο ονειδιζειν τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου [οτι]{.greek-omitted} ου μετενοησαν[11:20]{.aside}

ουαι σοι [χοραζιν]{.greek-omitted} [χοραζην]{.greek-added} ουαι σοι βηθσαιδα οτι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι εν [υμιν]{.greek-omitted} [σοι]{.greek-added} παλαι αν εν σακκω και σποδω [καθημενοι]{.greek-added} μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι ανεκτοτερον εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

και συ καπερναουμ η εως του [ουρανου]{.greek-abbr} υψωθεισα εως αδου καταβιβασθηση οτι ει εν σοδομοις εγενοντο αι δυναμεις αι γενομεναι εν σοι εμειναν αν [μεχι]{.greek-added} [μεχρι]{.corr} [της]{.greek-omitted} σημερον[11:23]{.aside}

πλην λεγω υμιν οτι γη σοδομων ανεκτοτερον εσται εν ημερα κρισεως η [σοι]{.greek-omitted} [υμιν]{.greek-added}[11:24]{.aside}

[εν]{.greek-omitted} [ειν]{.greek-added} εκεινω τω καιρω [αποκριθεις]{.greek-omitted} [αποκριθοις]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

ναι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

παντα μοι [παρεδοθη]{.greek-omitted} [παρεδο]{.greek-added} [θη]{.greek-added} υπο του [πατρος]{.greek-abbr} μου και ουδεις επιγινωσκει τον [υιον]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο [υιος]{.greek-abbr} και [ω]{.greek-omitted} [ο]{.greek-added} εαν βουληται ο [υιος]{.greek-abbr} αποκαλυψαι[11:27]{.aside}

δευτε προς με παντες οι κοπιωντες και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

αρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και ταπεινος τη καρδια και [ευρησετε]{.greek-omitted} [ευρησηται]{.greek-added} αναπαυσιν ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου [χρηστος]{.greek-omitted} [χριστος]{.greek-added} και το φορτιον μου ελαφρον εστιν[11:30]{.aside}

### Chapter 12

εν εκεινω τω καιρω επορευθη ο [ιησους]{.greek-abbr} τοις σαββασιν δια των σποριμων οι δε μαθηται αυτου επεινασαν και ηρξαντο [σταχυας]{.greek-added} τιλλειν [σταχυας]{.greek-omitted} και εσθιειν[12:1]{.aside}

οι δε φαρισαιοι ιδοντες [αυτους]{.greek-added} ειπον αυτω ιδου οι μαθηται σου [τι]{.greek-added} ποιουσιν ο ουκ εξεστιν ποιειν εν σαββατω[12:2]{.aside}

ο δε ειπεν αυτοις ουκ ανεγνωτε τι εποιησεν [δαυιδ]{.greek-abbr} οτε επεινασεν αυτος και οι μετ αυτου[12:3]{.aside}

πως [εισηλθεν]{.greek-omitted} [εισηλ]{.greek-added} [θεν]{.greek-added} εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως εφαγεν ους ουκ εξον [φαγειν]{.greek-added} ην αυτω [φαγειν]{.greek-omitted} ουδε τοις μετ αυτου ει μη [μονοις]{.greek-added} τοις ιερευσιν [μονοις]{.greek-omitted}[12:4]{.aside}

η ουκ ανεγνωτε εν τω νομω οτι τοις σαββασιν οι ιερεις εν τω ιερω το σαββατον βεβηλουσιν και [αναιτιοι]{.greek-omitted} [ανετι]{.greek-added} εισιν[12:5]{.aside}

λεγω δε υμιν οτι του ιερου [μειζον]{.greek-omitted} [μειζων]{.greek-added} εστιν ωδε[12:6]{.aside}

ει δε εγνωκειτε τι εστιν ελεον θελω και ου θυσιαν ουκ αν κατεδικασατε τους [αναιτιους]{.greek-omitted} [ανετιους]{.greek-added}[12:7]{.aside}

κυριος γαρ εστιν [του]{.greek-omitted} [σαββατου]{.greek-omitted} ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [και]{.greek-added} [του]{.greek-added} [σαββατου]{.greek-added}[12:8]{.aside}

και μεταβας εκειθεν ηλθεν εις την [συναγωγην]{.greek-omitted} [σειναγω]{.greek-added} [γην]{.greek-added} αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} ην [εκει]{.greek-added} την [χειρα]{.greek-omitted} [χειραν]{.greek-added} εχων ξηραν και επηρωτησαν αυτον λεγοντες ει εξεστιν τοις σαββασιν θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

ο δε ειπεν αυτοις τις [εσται]{.greek-omitted} εξ υμων [ανθρωπος]{.greek-omitted} [εστιν]{.greek-added} ος εξει προβατον εν και εαν εμπεση τουτο τοις σαββασιν εις [τον]{.greek-added} βοθυνον [ουχι]{.greek-omitted} [ουχη]{.greek-added} [κρατησει]{.greek-omitted} [κρατηση]{.greek-added} αυτο και [εγερει]{.greek-omitted} [εγειρη]{.greek-added}[12:11]{.aside}

ποσω [ουν]{.greek-omitted} [μαλλον]{.greek-added} διαφερει [ανθρωπος]{.greek-abbr} προβατου ωστε εξεστιν τοις σαββασιν καλως ποιειν[12:12]{.aside}

τοτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον [σου]{.greek-added} την χειρα [σου]{.greek-omitted} και εξετεινεν και [αποκατεσταθη]{.greek-omitted} [απεκατε]{.greek-added} [σταθη]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

[και]{.greek-added} [εξελθοντες]{.greek-added} οι [δε]{.greek-omitted} φαρισαιοι συμβουλιον ελαβον κατ αυτου [εξελθοντες]{.greek-omitted} οπως αυτον [απολεσωσιν]{.greek-omitted} [απωλεσωσιν]{.greek-added}[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν και [ηκολουθησαν]{.greek-omitted} [οικολουθησαν]{.greek-added} αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και επετιμησεν αυτοις ινα μη φανερον [ποιησωσιν]{.greek-added} αυτον [ποιησωσιν]{.greek-omitted}[12:16]{.aside}

οπως πληρωθη το ρηθεν [δια]{.greek-omitted} [υπο]{.greek-added} ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον ηρετισα ο αγαπητος μου εις ον [ευδοκησεν]{.greek-omitted} [ηυδοκησεν]{.greek-added} η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει ουδε ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

καλαμον συντετριμμενον ου κατεαξει και λινον τυφομενον ου σβεσει εως αν εκβαλη εις νικος [την]{.greek-omitted} [και]{.greek-added} κρισιν[12:20]{.aside}

και τω ονοματι αυτου εθνη ελπιουσιν[12:21]{.aside}

[τ]{.greek-supplied}οτε [προσηνεχθη]{.greek-omitted} [προσηνεγκαν]{.greek-added} αυτω [δαιμονιζομενος]{.greek-omitted} [δαιμονιζομενον]{.greek-added} [τυφλος]{.greek-omitted} [τυφλον]{.greek-added} και [κωφος]{.greek-omitted} [κωφον]{.greek-added} και εθεραπευσεν αυτον ωστε τον [τυφλον]{.greek-omitted} [και]{.greek-omitted} κωφον [και]{.greek-omitted} λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο [παντες]{.greek-omitted} [παν]{.greek-added} [τες]{.greek-added} οι οχλοι και ελεγον μητι ουτος εστιν ο [[χριστος]{.greek-abbr}]{.greek-added} [ο]{.greek-added} υιος [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες ειπον [ουτος]{.greek-omitted} [ουτως]{.greek-added} ουκ εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

ειδως δε ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν αυτοις πασα βασιλεια [μερισθεισα]{.greek-omitted} [μερισθησα]{.greek-added} καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ερημουται και πασα πολις η οικια [μερισθεισα]{.greek-omitted} [μερισθησα]{.greek-added} καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν εκβαλλει εφ εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

[και]{.greek-omitted} ει [δε]{.greek-added} εγω εν βεελζεβουλ εκβαλλω τα δαιμονια οι υιοι υμων εν τινι [εκβαλλουσιν]{.greek-omitted} [εκβαλουσιν]{.greek-added} δια τουτο αυτοι [κριται]{.greek-added} υμων εσονται [κριται]{.greek-omitted}[12:27]{.aside}

ει δε [εγω]{.greek-added} εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} [εγω]{.greek-omitted} εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

η πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου [διαρπασαι]{.greek-omitted} [αρπασαι]{.greek-added} εαν μη πρωτον δηση τον ισχυρον και τοτε την οικιαν αυτου [διαρπασει]{.greek-omitted} [αρπασει]{.greek-added}[12:29]{.aside}

ο [γαρ]{.greek-added} μη ων μετ [εμου]{.greek-omitted} [κατ]{.greek-omitted} εμου εστιν και ο μη συναγων μετ εμου [σκορπιζει]{.greek-omitted} [σκορ]{.greek-added} [πιζει]{.greek-added}[12:30]{.aside}

δια τουτο λεγω υμιν πασα αμαρτια και βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} η δε του [πνευματος]{.greek-abbr} βλασφημια ουκ αφεθησεται τοις [ανθρωποις]{.greek-abbr}[12:31]{.aside}

και ος [εαν]{.greek-omitted} ειπη λογον κατα του υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω ος δ αν ειπη κατα του [πνευματος]{.greek-abbr} του αγιου ουκ αφεθησεται αυτω ουτε εν [τουτω]{.greek-added} τω [νυν]{.greek-omitted} αιωνι ουτε εν τω μελλοντι[12:32]{.aside}

η ποιησατε το δενδρον καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον γινωσκεται[12:33]{.aside}

[γεννηματα]{.greek-omitted} [γεννημα]{.greek-added} [τα]{.greek-added} εχιδνων πως δυνασθε αγαθα λαλειν πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου εκβαλλει [τα]{.greek-added} αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου εκβαλλει [τα]{.greek-added} πονηρα[12:35]{.aside}

[αμην]{.greek-added} λεγω [δε]{.greek-omitted} υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι ανθρωποι αποδωσουσιν περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων σου δικαιωθηση και εκ των λογων σου [καταδικασθηση]{.greek-omitted} [κατακριθηση]{.greek-added}[12:37]{.aside}

τοτε απεκριθησαν [αυτω]{.greek-added} τινες των γραμματεων και φαρισαιων λεγοντες διδασκαλε θελομεν απο σου σημειον ιδειν[12:38]{.aside}

ο δε [αποκριθεις]{.greek-omitted} [αποκριθης]{.greek-added} ειπεν αυτοις γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ γαρ ην ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας ουτως εσται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εν τη καρδια της γης τρεις ημερας και τρεις νυκτας[12:40]{.aside}

ανδρες νινευιται αναστησονται εν τη κρισει μετα της [γενεας]{.greek-omitted} [γενε]{.greek-added} [ας]{.greek-added} ταυτης και [κατακρινουσιν]{.greek-omitted} [κατακρινουσην]{.greek-added} αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

βασιλισσα νοτου εγερθησεται εν τη κρισει μετα της γενεας ταυτης και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν σολομωνος και ιδου πλειον σολομωνος ωδε[12:42]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων ζητουν αναπαυσιν και ουχ ευρισκει[12:43]{.aside}

τοτε λεγει επιστρεψω εις τον οικον [μου]{.greek-omitted} οθεν εξηλθον και [ελθον]{.greek-omitted} [ελθων]{.greek-added} ευρισκει σχολαζοντα [και]{.greek-added} σεσαρωμενον και κεκοσμημενον[12:44]{.aside}

τοτε πορευεται και παραλαμβανει μεθ εαυτου επτα ετερα πνευματα πονηροτερα εαυτου και εισελθοντα κατοικει εκει και γινεται τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου χειρονα των πρωτων ουτως εσται και τη γενεα [ταυτη]{.greek-omitted} τη πονηρα [ταυτη]{.greek-added}[12:45]{.aside}

ετι δε αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και οι αδελφοι αυτου [ειστηκεισαν]{.greek-omitted} [ιστηκεισαν]{.greek-added} εξω ζητουντες αυτω λαλησαι[12:46]{.aside}

[ειπεν]{.greek-omitted} [οιπεν]{.greek-added} δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [εστηκασιν]{.greek-added} εξω [εστηκασιν]{.greek-omitted} ζητουντες [σοι]{.greek-omitted} [λαλησαι]{.greek-omitted} [σε]{.greek-added} [ιδειν]{.greek-added}[12:47]{.aside}

ο δε αποκριθεις ειπεν τω [ειποντι]{.greek-omitted} [λεγοντι]{.greek-added} αυτω τις εστιν η [μητηρ]{.greek-abbr} μου και τινες εισιν οι αδελφοι μου[12:48]{.aside}

και εκτεινας την χειρα αυτου επι τους μαθητας αυτου [ειπεν]{.greek-omitted} [εφη]{.greek-added} ιδου η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[12:49]{.aside}

οστις γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr} [αυτος]{.greek-omitted} [ουτος]{.greek-added} μου [και]{.greek-added} αδελφος και αδελφη και [μητηρ]{.greek-abbr} εστιν[12:50]{.aside}

### Chapter 13

εν δε τη ημερα εκεινη εξελθων ο [ιησους]{.greek-abbr} [απο]{.greek-omitted} [[απω]{.corr}]{.greek-added} της οικιας εκαθητο παρα την θαλασσαν[13:1]{.aside}

και [συνη]{.greek-added} [συνηχθησαν]{.greek-omitted} [χθησαν]{.greek-added} προς αυτον οχλοι πολλοι ωστε αυτον εις [το]{.greek-omitted} πλοιον εμβαντα [καθησθαι]{.greek-omitted} [καθισαι]{.greek-added} και πας ο οχλος επι τον αιγιαλον [ειστηκει]{.greek-omitted} [ιστηκει]{.greek-added}[13:2]{.aside}

και ελαλησεν αυτοις πολλα εν παραβολαις λεγων ιδου εξηλθεν ο σπειρων του [σπειρειν]{.greek-omitted} [σπειραι]{.greek-added}[13:3]{.aside}

και εν τω σπειρειν αυτον α μεν επεσεν παρα την οδον και [ηλθεν]{.greek-omitted} [ελθοντα]{.greek-added} τα πετεινα [και]{.greek-omitted} [του]{.greek-added} [ουρανου]{.greek-added} κατεφαγεν αυτα[13:4]{.aside}

αλλα δε επεσεν επι τα πετρωδη οπου ουκ ειχεν γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[13:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη [και]{.corr} [δια]{.greek-omitted} [το]{.greek-omitted} [[δυα]{.corr}]{.greek-added} [[τουτο]{.corr}]{.greek-added} [μη]{.corr} [εχειν]{.greek-omitted} [[εχι]{.corr}]{.greek-added} [ριζαν]{.greek-omitted} [[ριζα]{.corr}]{.greek-added} [εξηρανθη]{.greek-omitted} [[εξιρ[αν]{.greek-supplied}θι]{.corr}]{.greek-added}[13:6]{.aside}

αλλα δε επεσεν επι τας ακανθας και ανεβησαν αι ακανθαι και απεπνιξαν αυτα[13:7]{.aside}

αλλα δε επεσεν επι την γην την καλην και εδιδου καρπον ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:8]{.aside}

ο εχων ωτα ακουειν ακουετω[13:9]{.aside}

και προσελθοντες οι μαθηται ειπον αυτω δια τι εν παραβολαις λαλεις αυτοις[13:10]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι υμιν δεδοται γνωναι τα μυστηρια της βασιλειας τ[ω]{.unclear}ν ουρανων εκεινοις δε [ου]{.greek-omitted} [δεδοται]{.greek-omitted} [εν]{.greek-added} [παραβολαις]{.greek-added}[13:11]{.aside}

οστις γαρ εχει δοθησεται αυτω και περισσευθησεται οστις δε ουκ εχει [και]{.greek-omitted} [ο]{.greek-omitted} [εχει]{.greek-omitted} αρθησεται απ αυτου[13:12]{.aside}

δια τουτο εν παραβολαις [λαλω]{.greek-added} αυτοις [ινα]{.greek-added} [λαλω]{.greek-omitted} [οτι]{.greek-omitted} βλεποντες [ου]{.greek-omitted} [μη]{.greek-added} [βλεπουσιν]{.greek-omitted} [βλεπωσιν]{.greek-added} και [ακουοντες]{.greek-omitted} [ακουωντες]{.greek-added} [ουκ]{.greek-omitted} [μη]{.greek-added} [ακουουσιν]{.greek-omitted} [ακουωσιν]{.greek-added} [ουδε]{.greek-omitted} [μηδε]{.greek-added} [συνιουσιν]{.greek-omitted} [συνιωσιν]{.greek-added} [μητε]{.greek-added} [επιστρεψωσιν]{.greek-added}[13:13]{.aside}

και [αναπληρουται]{.greek-omitted} [τοτε]{.greek-added} [πληρωθησεται]{.greek-added} αυτοις η προφητεια ησαιου [η]{.greek-omitted} λεγουσα ακοη [ακουσετε]{.greek-omitted} [ακουσητε]{.greek-added} και ου μη συνητε και βλεποντες [βλεψετε]{.greek-omitted} [βλεπετε]{.greek-added} και ου μη ιδητε[13:14]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις ωσιν βαρεως ηκουσαν και τους οφθαλμους αυτων εκαμμυσαν μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} και [τη]{.greek-omitted} [καρδια]{.greek-omitted} [συνωσιν]{.greek-omitted} [και]{.greek-omitted} [επιστρεψωσιν]{.greek-omitted} [επιστρεψωσι]{.greek-added} και ιασομαι αυτους[13:15]{.aside}

υμων δε μακαριοι οι οφθαλμοι οτι βλεπουσιν και τα ωτα υμων οτι [ακουει]{.greek-omitted} [ακουουσιν]{.greek-added}[13:16]{.aside}

αμην γαρ λεγω υμιν οτι πολλοι προφηται και δικαιοι επεθυμησαν ιδειν α βλεπετε και ουκ ειδον και ακουσαι α ακουετε και ουκ ηκουσαν[13:17]{.aside}

υμεις ουν ακουσατε την [παραβολην]{.greek-omitted} [παραβο]{.greek-added} [λην]{.greek-added} του [σπειροντος]{.greek-omitted} [σπειραντος]{.greek-added}[13:18]{.aside}

παντος ακουοντος τον λογον της βασιλειας και μη συνιεντος ερχεται ο πονηρος και [αρπαζει]{.greek-omitted} [αιρει]{.greek-added} το εσπαρμενον εν τη καρδια αυτου ουτος εστιν ο παρα την οδον σπαρεις[13:19]{.aside}

ο δε επι τα πετρωδη σπαρεις ουτος εστιν ο τον λογον ακουων και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} μετα χαρας [δεχομενος]{.greek-added} [και]{.greek-added} λαμβανων αυτον[13:20]{.aside}

ουκ εχει δε ριζαν εν εαυτω αλλα προσκαιρος εστιν γενομενης δε θλιψεως [η]{.greek-omitted} [και]{.greek-added} διωγμου δια τον λογον [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} [σκανδαλιζεται]{.greek-omitted} [σκανδαλιζονται]{.greek-added}[13:21]{.aside}

ο δε [εις]{.greek-omitted} [επι]{.greek-added} τας ακανθας σπαρεις ουτος εστιν ο τον λογον ακουων και [η]{.greek-omitted} [μεριμνα]{.greek-omitted} του αιωνος τουτου και η απατη του πλουτου συμπνιγει τον λογον και ακαρπος γινεται[13:22]{.aside}

ο δε επι την γην την καλην σπαρεις ουτος εστιν ο τον λογον ακουων και συνιων ος δη καρποφορει και ποιει ο μεν εκατον ο δε εξηκοντα ο δε τριακοντα[13:23]{.aside}

αλλην παραβολην παρεθηκεν αυτοις λεγων [ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των ουρανων [ανθρωπω]{.greek-abbr} σπειροντι καλον σπερμα εν τω αγρω αυτου[13:24]{.aside}

εν δε τω καθευδειν [αυτον]{.greek-added} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} ηλθεν αυτου ο εχθρος και [εσπειρεν]{.greek-omitted} [επειρεν]{.greek-added} [ζιζανια]{.greek-omitted} [ζηζανια]{.greek-added} ανα μεσον του σιτου και απηλθεν[13:25]{.aside}

οτε δε εβλαστησεν ο χορτος και καρπον εποιησεν τοτε εφανη [και]{.greek-omitted} τα [ζιζανια]{.greek-omitted} [ζηζανια]{.greek-added}[13:26]{.aside}

προσελθοντες δε οι δουλοι του οικοδεσποτου ειπον αυτω [κυριε]{.greek-abbr} ουχι καλον σπερμα εσπειρας εν τω [σω]{.greek-omitted} αγρω ποθεν ουν εχει [τα]{.greek-added} [ζιζανια]{.greek-omitted} [ζηζανια]{.greek-added}[13:27]{.aside}

ο δε εφη αυτοις εχθρος [ανθρωπος]{.greek-abbr} τουτο εποιησεν [λεγουσιν]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [δουλοι]{.greek-omitted} [ειπον]{.greek-omitted} αυτω θελεις ουν απελθοντες [συλλεξομεν]{.greek-omitted} [συλλεξωμεν]{.greek-added} αυτα[13:28]{.aside}

ο δε [εφη]{.greek-omitted} [λεγει]{.greek-added} [αυτοις]{.greek-added} ου μηποτε [συλλεγοντες]{.greek-omitted} [συνλεγοντες]{.greek-added} τα ζιζανια εκριζωσητε αμα αυτοις τον σιτον[13:29]{.aside}

αφετε [συναυξανεσθαι]{.greek-omitted} [αυξανεσθαι]{.greek-added} αμφοτερα [μεχρι]{.greek-omitted} [εως]{.greek-added} του θερισμου και εν καιρω του θερισμου ερω τοις θερισταις συλλεξατε πρωτον τα ζιζανια και δησατε αυτα [δεσμα]{.greek-added} εις [δεσμας]{.greek-omitted} [προς]{.greek-omitted} το κατακαυσαι αυτα τον δε σιτον συναγαγετε εις την αποθηκην μου[13:30]{.aside}

αλλην παραβολην [παρεθηκεν]{.greek-omitted} [ελαλησεν]{.greek-added} αυτοις λεγων ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} κοκκω σιναπεως ον λαβων [ανθρωπος]{.greek-abbr} εσπειρεν εν τω αγρω αυτου[13:31]{.aside}

ο [μικροτερον]{.greek-omitted} [μηκροτερον]{.greek-added} [μεν]{.greek-omitted} εστιν παντων των σπερματων οταν δε αυξηθη [μειζον]{.greek-omitted} [μειζων]{.greek-added} των λαχανων εστιν και γινεται δενδρον ωστε ελθειν τα πετεινα του [ουρανου]{.greek-abbr} και κατασκηνουν εν τοις κλαδοις αυτου[13:32]{.aside}

αλλην παραβολην ελαλησεν αυτοις [[[ιησους]{.greek-abbr}]{.corr}]{.greek-added} ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} ζυμη ην λαβουσα γυνη εκρυψεν εις αλευρου σατα τρια εως ου εζυμωθη ολον[13:33]{.aside}

ταυτα παντα ελαλησεν ο [ιησους]{.greek-abbr} εν παραβολαις τοις οχλοις και χωρις [παραβολης]{.greek-omitted} [παραβολεις]{.greek-added} ουκ [ελαλει]{.greek-omitted} [ελαλησεν]{.greek-added} αυτοις[13:34]{.aside}

οπως πληρωθη το ρηθεν δια του προφητου λεγοντος ανοιξω εν παραβολαις το στομα μου ερευξομαι κεκρυμμενα απο καταβολης [κοσμου]{.greek-omitted} [κοσ]{.greek-added} [μου]{.greek-added}[13:35]{.aside}

τοτε αφεις τους οχλους ηλθεν εις την οικιαν [ο]{.greek-omitted} [ιησους]{.greek-omitted} και προσηλθον αυτω οι μαθηται αυτου λεγοντες [φρασον]{.greek-omitted} [διασαφισον]{.greek-added} ημιν την παραβολην των ζιζανιων του αγρου[13:36]{.aside}

ο δε αποκριθεις ειπεν [αυτοις]{.greek-omitted} ο σπειρων το καλον σπερμα εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr}[13:37]{.aside}

ο δε αγρος εστιν ο κοσμος το δε καλον σπερμα ουτοι εισιν οι υιοι της βασιλειας τα δε ζιζανια εισιν οι υιοι του πονηρου[13:38]{.aside}

ο δε εχθρος ο σπειρας αυτα εστιν ο διαβολος ο δε θερισμος συντελεια του αιωνος εστιν οι δε θερισται αγγελοι εισιν[13:39]{.aside}

ωσπερ ουν συλλεγεται τα ζιζανια και πυρι [καιεται]{.greek-omitted} [καιετε]{.greek-added} ουτως εσται εν τη συντελεια του αιωνος τουτου[13:40]{.aside}

αποστελει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} τους αγγελους αυτου και συλλεξουσιν εκ της βασιλειας αυτου παντα τα σκανδαλα και τους ποιουντας την ανομιαν[13:41]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:42]{.aside}

τοτε οι δικαιοι εκλαμψουσιν ως ο ηλιος εν τη βασιλεια του [πατρος]{.greek-abbr} αυτων ο εχων ωτα ακουειν ακουετω[13:43]{.aside}

παλιν [ομοι]{.greek-added} [ομοια]{.corr} εστιν η βασιλεια των [ουρανων]{.greek-abbr} θησαυρω κεκρυμμενω εν [τω]{.greek-omitted} αγρω ον ευρων [ανθρωπος]{.greek-abbr} [εκρυψεν]{.greek-omitted} [εκρυψε]{.greek-added} και απο της χαρας αυτου υπαγει και παντα οσα εχει πωλει και αγοραζει τον αγρον εκεινον[13:44]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} εμπορω ζητουντι καλους μαργαριτας[13:45]{.aside}

ος ευρων ενα πολυτιμον μαργαριτην απελθων πεπρακεν παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και ηγορασεν αυτον[13:46]{.aside}

παλιν ομοια εστιν η βασιλεια των [ουρανων]{.greek-abbr} σαγηνη [βληθειση]{.greek-omitted} [βληθει]{.greek-added} [ση]{.greek-added} εις την θαλασσαν και εκ παντος γενους συναγαγουση[13:47]{.aside}

[ην]{.greek-omitted} [η[γγ]{.unclear}]{.greek-added} οτε επληρωθη αναβιβασαντες [αυτην]{.greek-added} επι τον αιγιαλον και καθισαντες συνελεξαν τα καλα εις αγγεια τα δε σαπρα εξω εβαλον[13:48]{.aside}

ουτως εσται εν τη συντελεια του αιωνος [εξελευσονται]{.greek-omitted} [εξελευσοντε]{.greek-added} οι αγγελοι και [αφοριουσιν]{.greek-omitted} [αφοριουσι]{.greek-added} τους πονηρους εκ μεσου των δικαιων[13:49]{.aside}

και βαλουσιν αυτους εις την καμινον του πυρος εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[13:50]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} συνηκατε ταυτα παντα λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[13:51]{.aside}

ο δε ειπεν αυτοις δια τουτο πας γραμματευς μαθητευθεις εις την βασιλειαν των [ουρανων]{.greek-abbr} ομοιος εστιν [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εκβαλλει εκ του θησαυρου αυτου καινα και [παλαια]{.greek-omitted} [παλεα]{.greek-added}[13:52]{.aside}

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τας παραβολας ταυτας μετηρεν εκειθεν[13:53]{.aside}

και ελθων εις την [πατριδα]{.greek-abbr} αυτου εδιδασκεν αυτους εν τη συναγωγη αυτων ωστε [εκπληττεσθαι]{.greek-omitted} [εκπλησσεσθαι]{.greek-added} αυτους και λεγειν ποθεν τουτω η σοφια αυτη και αι δυναμεις[13:54]{.aside}

ουχ ουτος εστιν ο του τεκτονος υιος ουχι η [μητηρ]{.greek-abbr} αυτου λεγεται μαριαμ και οι αδελφοι αυτου [ιακωβος]{.greek-omitted} [ιακω]{.greek-added} [βος]{.greek-added} και ιωσης και σιμων και ιουδας[13:55]{.aside}

και αι αδελφαι αυτου ουχι πασαι προς ημας [εισιν]{.greek-omitted} [εισι]{.greek-added} ποθεν ουν τουτω ταυτα παντα[13:56]{.aside}

και εσκανδαλιζοντο εν αυτω ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου και εν τη οικια αυτου[13:57]{.aside}

και ουκ εποιησεν εκει δυναμεις πολλας δια την απιστιαν αυτων[13:58]{.aside}

### Chapter 14

εν εκεινω τω καιρω [η]{.unclear}κουσεν ηρωδης ο τετραρχης την ακοην [ιησου]{.greek-abbr}[14:1]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις παισιν αυτου ουτος εστιν ιωαννης ο βαπτιστης αυτος ηγερθη απο των νεκρων και δια [τουτο]{.greek-omitted} [του]{.greek-added} [το]{.greek-added} αι δυναμεις ενεργουσιν εν αυτω[14:2]{.aside}

ο γαρ ηρωδης κρατησας τον ιωαννην εδησεν αυτον και εθετο εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου[14:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω ο ιωαννης ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν αυτην[14:4]{.aside}

και θελων αυτον αποκτειναι εφοβηθη τον οχλον οτι ως προφητην αυτον ειχον[14:5]{.aside}

γενεσιων δε αγομενων του ηρωδου ωρχησατο η θυγατηρ της ηρωδιαδος εν τω μεσω και [ηρεσεν]{.greek-omitted} [ηρεσε]{.greek-added} τω ηρωδη[14:6]{.aside}

οθεν μεθ ορκου ωμολογησεν αυτη δουναι ο εαν αιτησηται[14:7]{.aside}

η δε προβιβασθεισα υπο της [μητρος]{.greek-abbr} αυτης δος μοι φησιν [ωδε]{.greek-omitted} επι πινακι την κεφαλην ιωαννου του βαπτιστου[14:8]{.aside}

και ελυπηθη ο βασιλευς δια δε τους ορκους και τους συνανακειμενους [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} δοθηναι[14:9]{.aside}

και πεμψας [απεκεφαλισεν]{.greek-omitted} [απεκεφαλισε]{.greek-added} τον ιωαννην εν τη φυλακη[14:10]{.aside}

και ηνεχθη η κεφαλη αυτου επι πινακι και εδοθη τω κορασιω και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης[14:11]{.aside}

και προσελθοντες οι μαθηται αυτου ηραν το σωμα και εθαψαν αυτο και ελθοντες απηγγειλαν τω [ιησου]{.greek-abbr}[14:12]{.aside}

[[―]{.gap}κουσας]{.greek-added} [και]{.corr} [ακουσας]{.greek-omitted} [[κουσας]{.corr}]{.greek-added} [δε]{.greek-added} ο [ιησους]{.greek-abbr} ανεχωρησεν εκειθεν εν πλοιω εις ερημον τοπον κατ ιδιαν και ακουσαντες οι [οχλοι]{.greek-omitted} [οχλει]{.greek-added} ηκολουθησαν αυτω πεζη απο των πολεων[14:13]{.aside}

και εξελθων ο [ιησους]{.greek-abbr} [ειδεν]{.greek-omitted} [ειδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} τους αρρωστους αυτων[14:14]{.aside}

οψιας δε γενομενης προσηλθον αυτω οι μαθηται αυτου λεγοντες ερημος εστιν ο τοπος και η ωρα ηδη παρηλθεν απολυσον τους οχλους ινα απελθοντες εις τας κωμας αγορασωσιν εαυτοις βρωματα[14:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου χρειαν [εχουσιν]{.greek-omitted} [εχου]{.greek-added} [σιν]{.greek-added} απελθειν δοτε αυτοις υμεις φαγειν[14:16]{.aside}

οι δε λεγουσιν αυτω ουκ εχομεν ωδε ει μη πεντε αρτους και δυο ιχθυας[14:17]{.aside}

ο δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} φερετε μοι αυτους ωδε[14:18]{.aside}

και κελευσας τους οχλους ανακλιθηναι επι τους χορτους λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον ουρανον [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και κλασας [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις τους αρτους οι δε μαθηται τοις οχλοις[14:19]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των [κλασματων]{.greek-omitted} [κλασ]{.greek-added} [ματων]{.greek-added} δωδεκα κοφινους πληρεις[14:20]{.aside}

οι δε εσθιοντες ησαν ανδρες ωσει πεντακισχιλιοι χωρις [γυναικων]{.greek-omitted} [γυνεκων]{.greek-added} και παιδιων[14:21]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} [ο]{.greek-omitted} [[ιησους]{.greek-abbr}]{.corr} τους μαθητας [αυτου]{.greek-added} εμβηναι εις το πλοιον και προαγειν αυτον εις το περαν εως ου [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τους οχλους[14:22]{.aside}

και απολυσας τους οχλους ανεβη εις το ορος κατ ιδιαν προσευξασθαι οψιας δε γενομενης μονος ην εκει[14:23]{.aside}

το δε πλοιον ηδη μεσον της θαλασσης ην βασανιζομενον υπο των κυματων ην γαρ εναντιος ο ανεμος[14:24]{.aside}

τεταρτη δε φυλακη της νυκτος [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς αυτους ο [ιησους]{.greek-abbr} περιπατων επι της θαλασσης[14:25]{.aside}

και ιδοντες αυτον οι μαθηται επι την θαλασσαν περιπατουντα εταραχθησαν λεγοντες οτι φαντασμα [εστιν]{.greek-omitted} [εστι]{.greek-added} και απο του φοβου εκραξαν[14:26]{.aside}

ευθεως δε ελαλησεν αυτοις ο [ιησους]{.greek-abbr} λεγων θαρσειτε εγω ειμι μη φοβεισθε[14:27]{.aside}

αποκριθεις δε αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} ει συ ει κελευσον με προς σε ελθειν επι τα υδατα[14:28]{.aside}

ο δε ειπεν ελθε και καταβας απο του πλοιου ο πετρος περιεπατησεν επι τα υδατα ελθειν προς τον [ιησουν]{.greek-abbr}[14:29]{.aside}

βλεπων δε τον ανεμον ισχυρον εφοβηθη και αρξαμενος καταποντιζεσθαι [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} λεγων [κυριε]{.greek-abbr} σωσον με[14:30]{.aside}

ευθεως δε ο [ιησους]{.greek-abbr} εκτεινας την χειρα επελαβετο αυτου και λεγει αυτω ολιγοπιστε εις τι εδιστασας[14:31]{.aside}

και εμβαντων αυτων εις το πλοιον εκοπασεν ο ανεμος[14:32]{.aside}

οι δε εν τω πλοιω ελθοντες προσεκυνησαν αυτω λεγοντες αληθως [θεου]{.greek-abbr} υιος ει[14:33]{.aside}

και διαπερασαντες ηλθον εις την γην [γεννησαρετ]{.greek-omitted} [γεννη]{.greek-added} [σαρετ]{.greek-added}[14:34]{.aside}

και επιγνοντες αυτον οι ανδρες του τοπου εκεινου απεστειλαν εις [ολην]{.greek-omitted} [ολυν]{.greek-added} την περιχωρον εκεινην και προσηνεγκαν αυτω παντας τους κακως εχοντας[14:35]{.aside}

και παρεκαλουν αυτον ινα μονον αψωνται του κρασπεδου του ιματιου αυτου και οσοι ηψαντο διεσωθησαν[14:36]{.aside}

### Chapter 15

τοτε προσερχονται τω [ιησου]{.greek-abbr} οι απο ιεροσολυμων [γραμματης]{.greek-added} [γραμματεις]{.corr} και φαρισαιοι λεγοντες[15:1]{.aside}

δια τι οι μαθηται σου [παραβαινουσιν]{.greek-omitted} [παραβαινουσι]{.greek-added} την παραδοσιν των πρεσβυτερων ου γαρ νιπτονται τας χειρας αυτων οταν αρτον εσθιωσιν[15:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δια τι και υμεις παραβαινετε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:3]{.aside}

ο γαρ [θεος]{.greek-abbr} ενετειλατο λεγων τιμα τον [πατερα]{.greek-abbr} και την [μητερα]{.greek-abbr} και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[15:4]{.aside}

υμεις δε λεγετε ος [αν]{.greek-omitted} [εαν]{.greek-added} ειπη τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} δωρον ο εαν εξ εμου ωφεληθης [και]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [τιμηση]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted}[15:5]{.aside}

[και]{.greek-added} [ου]{.greek-added} [μη]{.greek-added} [τιμηση]{.greek-added} [τον]{.greek-added} [[πατερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} [η]{.greek-added} [την]{.greek-added} [[μητερα]{.greek-abbr}]{.greek-added} [αυτου]{.greek-added} και ηκυρωσατε την εντολην του [θεου]{.greek-abbr} δια την παραδοσιν υμων[15:6]{.aside}

υποκριται καλως [προεφητευσεν]{.greek-omitted} [προεφητευσε]{.greek-added} περι υμων ησαιας λεγων[15:7]{.aside}

εγγιζει μοι ο [λαος]{.greek-omitted} [λα]{.greek-added} [ος]{.greek-added} ουτος τω στοματι αυτων και τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[15:8]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[15:9]{.aside}

και προσκαλεσαμενος τον οχλον ειπεν αυτοις ακουετε και συνιετε[15:10]{.aside}

ου το εισερχομενον εις το στομα κοινοι τον [ανθρωπον]{.greek-abbr} αλλα το εκπορευομενον εκ του στοματος τουτο κοινοι τον [ανθρωπον]{.greek-abbr}[15:11]{.aside}

τοτε προσελθοντες οι μαθηται αυτου ειπον αυτω οιδας οτι οι φαρισαιοι ακουσαντες τον λογον εσκανδαλισθησαν[15:12]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πασα φυτεια ην ουκ εφυτευσεν ο [πατηρ]{.greek-abbr} μου ο [ουρανιος]{.greek-abbr} εκριζωθησεται[15:13]{.aside}

αφετε αυτους οδηγοι [εισιν]{.greek-omitted} [εισι]{.greek-added} τυφλοι τυφλων τυφλος δε τυφλον εαν οδηγη αμφοτεροι εις βοθυνον πεσουνται[15:14]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω φρασον ημιν την παραβολην ταυτην[15:15]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν ακμην και υμεις ασυνετοι εστε[15:16]{.aside}

ουπω νοειτε οτι παν το εισπορευομενον εις το στομα εις την κοιλιαν χωρει και εις αφεδρωνα εκβαλλεται[15:17]{.aside}

τα δε εκπορευομενα εκ του στοματος εκ της καρδιας εξερχεται κακεινα κοινοι τον [ανθρωπον]{.greek-abbr}[15:18]{.aside}

εκ γαρ της καρδιας εξερχονται διαλογισμοι πονηροι φονοι μοιχειαι πορνειαι κλοπαι ψευδομαρτυριαι βλασφημιαι[15:19]{.aside}

ταυτα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr} το δε ανιπτοις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} φαγειν ου κοινοι τον [ανθρωπον]{.greek-abbr}[15:20]{.aside}

και εξελθων εκειθεν ο [ιησους]{.greek-abbr} ανεχωρησεν εις τα μερη τυρου και σιδωνος[15:21]{.aside}

και ιδου γυνη χαναναια απο των οριων εκεινων εξελθουσα εκραυγασεν αυτω λεγουσα ελεησον με [κυριε]{.greek-abbr} υιε [δαυιδ]{.greek-abbr} η θυγατηρ μου κακως [δαιμονιζεται]{.greek-omitted} [δαιμονιζε]{.greek-added} [ται]{.greek-added}[15:22]{.aside}

ο δε ουκ απεκριθη αυτη λογον και προσελθοντες οι μαθηται αυτου ηρωτων αυτον λεγοντες απολυσον αυτην οτι κραζει οπισθεν ημων[15:23]{.aside}

ο δε αποκριθεις ειπεν ουκ απεσταλην ει μη εις τα προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[15:24]{.aside}

η δε ελθουσα προσεκυνησεν αυτω λεγουσα [κυριε]{.greek-abbr} βοηθει μοι[15:25]{.aside}

ο δε αποκριθεις ειπεν ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καλον λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[15:26]{.aside}

η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια εσθιει απο των ψιχιων των πιπτοντων απο της τραπεζης των κυριων αυτων[15:27]{.aside}

τοτε αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτη ω γυναι μεγαλη σου η [πιστις]{.greek-omitted} [πιστης]{.greek-added} γενηθητω σοι ως θελεις και ιαθη η θυγατηρ αυτης απο της ωρας εκεινης[15:28]{.aside}

και μεταβας εκειθεν ο [ιησους]{.greek-abbr} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} παρα την θαλασσαν της γαλιλαιας και αναβας εις το ορος εκαθητο εκει[15:29]{.aside}

και προσηλθον αυτω οχλοι πολλοι εχοντες μεθ εαυτων χωλους τυφλους κωφους κυλλους και ετερους πολλους και ερριψαν αυτους παρα τους ποδας του [ιησου]{.greek-abbr} και εθεραπευσεν αυτους[15:30]{.aside}

ωστε τους οχλους θαυμασαι βλεποντας κωφους [ακουοντας]{.greek-added} [αλαλους]{.greek-added} λαλουντας κυλλους υγιεις χωλους περιπατουντας και τυφλους βλεποντας και εδοξασαν τον [θεον]{.greek-abbr} [ισραηλ]{.greek-abbr}[15:31]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος τους μαθητας αυτου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} και απολυσαι αυτους [νηστεις]{.greek-omitted} [νηστις]{.greek-added} ου θελω μηποτε εκλυθωσιν εν τη οδω[15:32]{.aside}

και λεγουσιν αυτω οι μαθηται αυτου ποθεν ημιν εν ερημια αρτοι τοσουτοι ωστε χορτασαι οχλον τοσουτον[15:33]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} ποσους αρτους εχετε οι δε ειπον επτα και ολιγα ιχθυδια[15:34]{.aside}

και [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} [τοις]{.greek-omitted} [τους]{.greek-added} [οχλοις]{.greek-omitted} [οχλους]{.greek-added} [αναπεσιν]{.greek-added} [αναπεσειν]{.corr} επι την γην[15:35]{.aside}

και λαβων τους επτα αρτους και τους ιχθυας ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις μαθηταις αυτου οι δε μαθηται [τω]{.greek-omitted} [οχλω]{.greek-omitted} [τοις]{.greek-added} [οχλοις]{.greek-added}[15:36]{.aside}

και εφαγον παντες και εχορτασθησαν και ηραν το περισσευον των κλασματων επτα σπυριδας πληρεις[15:37]{.aside}

οι δε εσθιοντες ησαν τετρακισχιλιοι ανδρες χωρις γυναικων και παιδιων[15:38]{.aside}

και απολυσας τους οχλους [ενεβη]{.greek-omitted} [ανεβη]{.greek-added} εις το [πλοιον]{.greek-omitted} [πλειον]{.greek-added} και ηλθεν εις τα ορια μαγδαλα[15:39]{.aside}

### Chapter 16

και προσελθοντες οι φαρισαιοι και σαδδουκαιοι [π[η]{.unclear}ραζοντες]{.greek-added} [πειραζοντες]{.corr} επηρωτησαν αυτον σημειον εκ του [ουρανου]{.greek-abbr} επιδειξαι αυτοις[16:1]{.aside}

ο δε αποκριθεις ειπεν αυτοις οψιας γενομενης λεγετε ευδια πυρραζει γαρ ο [ουρανος]{.greek-abbr}[16:2]{.aside}

και πρωι σημερον χειμων πυρραζει γαρ στυγναζων ο [ουρανος]{.greek-abbr} υποκριται το μεν προσωπον του [ουρανου]{.greek-abbr} γινωσκετε διακρινειν τα δε σημεια των καιρων ου δυνασθε [γνωναι]{.greek-added}[16:3]{.aside}

γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου και καταλιπων αυτους [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[16:4]{.aside}

και ελθοντες οι μαθηται αυτου εις το περαν επελαθοντο αρτους λαβειν[16:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ορατε και προσεχετε απο της ζυμης των φαρισαιων και σαδδουκαιων[16:6]{.aside}

οι δε διελογιζοντο εν εαυτοις λεγοντες οτι αρτους ουκ ελαβομεν[16:7]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι διαλογιζεσθε εν εαυτοις ολιγοπιστοι οτι αρτους ουκ ελαβετε[16:8]{.aside}

ουπω νοειτε ουδε μνημονευετε τους πεντε αρτους των πεντακισχιλιων και ποσους κοφινους ελαβετε[16:9]{.aside}

ουδε τους επτα αρτους των [τετρα]{.greek-added} [τετρακισχιλιων]{.greek-omitted} [κισχιλιων]{.greek-added} και ποσας σπυριδας ελαβετε[16:10]{.aside}

πως ου νοειτε οτι ου περι αρτου ειπον υμιν προσεχειν απο της ζυμης των φαρισαιων και σαδδουκαιων[16:11]{.aside}

τοτε συνηκαν οτι ουκ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προσεχειν απο της ζυμης του αρτου αλλα απο της διδαχης των φαρισαιων και σαδδουκαιων[16:12]{.aside}

ελθων δε ο [ιησους]{.greek-abbr} εις τα μερη [καισαρειας]{.greek-omitted} [καισαριας]{.greek-added} της φιλιππου ηρωτα τους μαθητας αυτου λεγων τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι τον υιον του [ανθρωπου]{.greek-abbr}[16:13]{.aside}

οι δε ειπον οι μεν ιωαννην τον βαπτιστην αλλοι δε ηλιαν ετεροι δε ιερεμιαν η ενα των προφητων[16:14]{.aside}

λεγει αυτοις υμεις δε τινα με λεγετε ειναι[16:15]{.aside}

αποκριθεις δε σιμων πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr} του ζωντος[16:16]{.aside}

[και]{.greek-omitted} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτω μακαριος ει σιμων βαριωνα οτι σαρξ και αιμα ουκ [απεκαλυψαι]{.greek-added} [απεκαλυψεν]{.greek-omitted} [[απεκαλυψε]{.corr}]{.greek-added} σοι αλλ ο [πατηρ]{.greek-abbr} μου ο εν τοις ουρανοις[16:17]{.aside}

καγω δε σοι λεγω οτι συ ει πετρος και επι ταυτη τη πετρα οικοδομησω μου την εκκλησιαν και πυλαι αδου ου κατισχυσουσιν αυτης[16:18]{.aside}

και δωσω σοι τας κλεις της [βασιλειας]{.greek-omitted} [βασιλει]{.greek-added} [ας]{.greek-added} των [ουρανων]{.greek-abbr} και ο εαν δησης επι της γης εσται δεδεμενον εν τοις [ουρανοις]{.greek-abbr} και ο εαν λυσης επι της γης εσται λελυμενον εν τοις [ουρανοις]{.greek-abbr}[16:19]{.aside}

τοτε διεστειλατο τοις μαθηταις αυτου ινα μηδενι ειπωσιν οτι αυτος εστιν [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr}[16:20]{.aside}

απο τοτε ηρξατο ο [ιησους]{.greek-abbr} δεικνυειν τοις μαθηταις αυτου οτι δει αυτον απελθειν εις ιεροσολυμα και πολλα παθειν απο των πρεσβυτερων και αρχιερεων και γραμματεων και αποκτανθηναι και τη τριτη ημερα [εγερθηναι]{.greek-omitted} [εγερθη]{.greek-added} [ναι]{.greek-added}[16:21]{.aside}

και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω λεγων ιλεως σοι [κυριε]{.greek-abbr} ου μη εσται σοι τουτο[16:22]{.aside}

ο δε στραφεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω πετρω υπαγε οπισω μου σατανα σκανδαλον μου ει οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[16:23]{.aside}

τοτε ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ει τις θελει οπισω μου ελθειν απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και ακολουθειτω [μοι]{.greek-omitted} [μει]{.greek-added}[16:24]{.aside}

ος γαρ αν [θελει]{.greek-added} [θελη]{.corr} την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την ψυχην αυτου ενεκεν εμου ευρησει αυτην[16:25]{.aside}

τι γαρ ωφελειται [ανθρωπος]{.greek-abbr} εαν τον κοσμον ολον κερδηση την δε ψυχην αυτου ζημιωθη η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[16:26]{.aside}

μελλει γαρ ο υιος του [ανθρωπου]{.greek-abbr} ερχεσθαι εν τη δοξη του [πατρος]{.greek-abbr} αυτου μετα των αγγελων αυτου και τοτε αποδωσει εκαστω κατα την πραξιν αυτου[16:27]{.aside}

αμην λεγω υμιν [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες [των]{.greek-added} ωδε [εστωτες]{.greek-omitted} [εστωτων]{.greek-added} οιτινες ου μη γευσωνται θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν τη βασιλεια αυτου[16:28]{.aside}

### Chapter 17

και μεθ ημερας εξ [παραλαμβανει]{.greek-omitted} [παραλαμ]{.greek-added} [βανει]{.greek-added} ο [ιησους]{.greek-abbr} τον πετρον και ιακωβον και ιωαννην τον αδελφον αυτου και αναφερει αυτους εις ορος υψηλον κατ ιδιαν[17:1]{.aside}

και μετεμορφωθη εμπροσθεν αυτων και [ελαμψεν]{.greek-omitted} [ελαμψε]{.greek-added} το προσωπον αυτου ως ο ηλιος τα δε ιματια αυτου [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} λευκα ως το φως[17:2]{.aside}

και ιδου ωφθησαν αυτοις [μωσης]{.greek-omitted} [μωυσης]{.greek-added} και ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

αποκριθεις δε ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω [ιησου]{.greek-abbr} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι ει θελεις ποιησωμεν ωδε τρεις σκηνας σοι μιαν και [μωση]{.greek-omitted} [μωσει]{.greek-added} μιαν και μιαν ηλια[17:4]{.aside}

ετι αυτου λαλουντος ιδου νεφελη φωτεινη επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο υιος μου ο αγαπητος εν ω ευδοκησα αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται επεσον επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων [και]{.greek-omitted} ειπεν εγερθητε και μη φοβεισθε[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει μη τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινοντων αυτων εκ του ορους [ενετειλατο]{.greek-omitted} [ενετοιλατο]{.greek-added} αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι ειπητε το οραμα εως ου ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[17:9]{.aside}

και επηρωτησαν [αυ]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-added} οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν δει ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις ηλιας μεν [ερχαιται]{.greek-added} [ερχεται]{.corr} πρωτον και αποκαταστησει παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας ηδη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ουκ επεγνωσαν αυτον αλλα εποιησαν εν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οσα ηθελησαν ουτως και ο υιος του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι ιωαννου του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και [ελθοντων]{.greek-omitted} [ελθωντων]{.greek-added} αυτων προς τον οχλον προσηλθεν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ανθρωπος]{.greek-abbr} [τις]{.greek-added} γονυπετων αυτον[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι σεληνιαζεται και κακως πασχει πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και προσηνεγκα αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν αυτον θεραπευσαι[17:16]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε εσομαι μεθ υμων εως ποτε ανεξομαι υμων φερετε μοι αυτον ωδε[17:17]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε προσελθοντες οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι [ημεις]{.greek-omitted} [υμεις]{.greek-added} ουκ ηδυνηθημεν εκβαλειν αυτο[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} υμων αμην γαρ λεγω υμιν εαν εχητε πιστιν ως κοκκον σιναπεως ερειτε [τω]{.greek-omitted} [τωι]{.greek-added} [ορη]{.greek-added} [ορει]{.corr} τουτω μεταβηθι εντευθεν εκει και μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ εκπορευεται ει μη εν προσευχη και νηστεια[17:21]{.aside}

αναστρεφομενων δε αυτων [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [γαλιλαια]{.greek-omitted} [γαλιλαιαν]{.greek-added} ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοσθαι εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα εγερθησεται και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων δε αυτων εις καπερναουμ προσηλθον οι τα διδραχμα λαμβανοντες τω πετρω και ειπον ο διδασκαλος υμων ου τελει τα διδραχμα[17:24]{.aside}

λεγει ναι και οτε εισηλθεν εις την οικιαν προεφθασεν αυτον ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο τινων [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} τελη η [κηνσον]{.greek-omitted} [κηνσων]{.greek-added} απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

λεγει αυτω ο πετρος απο των αλλοτριων εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις την θαλασσαν βαλε αγκιστρον και τον [αναβαινοντα]{.greek-omitted} [αναβαντα]{.greek-added} πρωτον ιχθυν αρον και ανοιξας το στομα αυτου ευρησεις στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ωρα προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες τις αρα [μειζων]{.greek-omitted} [μει]{.greek-added} [ζων]{.greek-added} εστιν εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη στραφητε και γενησθε ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

οστις ουν ταπεινωσει εαυτον ως το παιδιον τουτο ουτος εστιν ο μειζων εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:4]{.aside}

και ος εαν δεξηται παιδιον τοιουτον εν επι τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν σκανδαλιση ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος εις τον τραχηλον αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

[ει]{.greek-omitted} [η]{.greek-added} δε η χειρ σου [η]{.greek-omitted} ο πους σου [σκανδαλιζει]{.greek-omitted} [σκανδαληζει]{.greek-added} σε εκκοψον αυτα και βαλε απο σου καλον σοι εστιν εισελθειν εις την ζωην χωλον η κυλλον η δυο χειρας η δυο ποδας εχοντα βληθηναι εις το πυρ το αιωνιον[18:8]{.aside}

και ει ο οφθαλμος σου σκανδαλιζει σε εξελε αυτον και βαλε απο σου καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} [μονοφθαλμον]{.greek-omitted} [μονοφθαλμων]{.greek-added} εις την ζωην εισελθειν η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[18:9]{.aside}

[ορατε]{.greek-omitted} [οραται]{.greek-added} μη [καταφρονησητε]{.greek-omitted} [καταφρονησηται]{.greek-added} ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος [βλεπουσιν]{.greek-omitted} [βλεπουσι]{.greek-added} το προσωπον του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο υιος του [ανθρωπου]{.greek-abbr} [ζητησαι]{.greek-added} [και]{.greek-added} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει εαν γενηται τινι [ανθρωπω]{.greek-abbr} εκατον προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα ενενηκοντα εννεα επι τα ορη [και]{.greek-added} πορευθεις ζητει το πλανωμενον[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν οτι χαιρει επ αυτω μαλλον η επι τοις ενενηκοντα εννεα τοις μη πεπλανημενοις[18:13]{.aside}

ουτως ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} θελημα εμπροσθεν του [πατρος]{.greek-abbr} [η]{.greek-added} [υμων]{.corr} του εν ουρανοις ινα [αποληται]{.greek-omitted} [απωληται]{.greek-added} εις των μικρων τουτων[18:14]{.aside}

εαν δε [αμαρτηση]{.greek-omitted} [αμαρτει]{.greek-added} εις σε ο αδελφος σου υπαγε [και]{.greek-omitted} ελεγξον αυτον μεταξυ σου και αυτου μονου εαν σου ακουση εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη [σου]{.greek-added} ακουση παραλαβε μετα σου ετι ενα η δυο ινα επι στοματος δυο μαρτυρων η τριων σταθη παν ρημα[18:16]{.aside}

εαν δε παρακουση αυτων ειπε τη εκκλησια εαν δε και της εκκλησιας παρακουση εστω σ[ο]{.unclear}ι ωσπερ ο [εθνικος]{.greek-omitted} [εθνηκως]{.greek-added} και ο τελωνης[18:17]{.aside}

αμην [γαρ]{.greek-added} λεγω [υμιν]{.greek-omitted} [ημιν]{.greek-added} [ος]{.greek-added} [οσα]{.corr} εαν [δησητε]{.greek-omitted} [δησηται]{.greek-added} επι της γης εσται δεδεμενα εν [τω]{.greek-omitted} [ουρανω]{.greek-abbr} και οσα εαν [λυσητε]{.greek-omitted} [λυσηται]{.greek-added} επι της γης εσται [λελυμενον]{.greek-added} [λελυμενα]{.corr} εν τω [ουρανω]{.greek-abbr} [[[ουνο]{.greek-abbr}]{.corr}]{.greek-added}[18:18]{.aside}

[παλιν]{.greek-omitted} [παλην]{.greek-added} [αμην]{.greek-omitted} λεγω υμιν οτι εαν δυο υμων [συμφωνησωσιν]{.greek-omitted} [συμφωνησουσιν]{.greek-added} επι της γης περι παντος πραγματος ου εαν [αιτησωνται]{.greek-omitted} [αιτησονται]{.greek-added} γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:19]{.aside}

ου γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο η τρεις συνηγμενοι εις το εμον ονομα εκει ειμι εν μεσω αυτων[18:20]{.aside}

τοτε προσελθων αυτω ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} [ποσακις]{.greek-omitted} [ποσα]{.greek-added} [κις]{.greek-added} αμαρτησει εις εμε ο αδελφος μου και αφησω αυτω εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} [ου]{.greek-omitted} [ουκ]{.greek-added} [λεγω]{.greek-omitted} [ειπον]{.greek-added} σοι εως επτακις αλλ εως εβδομηκοντακις επτα[18:22]{.aside}

δια [τουτο]{.greek-omitted} [τουτω]{.greek-added} [ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει ος [ηθελησεν]{.greek-omitted} [ηθελησε]{.greek-added} συναραι λογον μετα των δουλων αυτου[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν προσηνεχθη αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν αυτον ο κυριος αυτου πραθηναι και την γυναικα αυτου και τα τεκνα και παντα οσα [ειχεν]{.greek-omitted} [ειχε]{.greek-added} και αποδοθηναι[18:25]{.aside}

πεσων ουν ο [δουλος]{.greek-omitted} [συνδουλος]{.greek-added} [εκεινος]{.greek-added} προσεκυνει αυτω λεγων [κυριε]{.greek-abbr} [μακροθυμησον]{.greek-omitted} [μακροθυ]{.greek-added} [μησον]{.greek-added} επ εμοι και παντα σοι αποδωσω[18:26]{.aside}

σπλαγχνισθεις δε ο κυριος του δουλου εκεινου απελυσεν αυτον και το δανειον αφηκεν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[18:27]{.aside}

εξελθων δε ο δουλος εκεινος ευρεν ενα των συνδουλων αυτου ος ωφειλεν αυτω εκατον δηναρια και κρατησας αυτον [επνιγεν]{.greek-omitted} [επνιγε]{.greek-added} λεγων [αποδος]{.greek-omitted} [μοι]{.greek-omitted} [ει]{.greek-omitted} [τι]{.greek-omitted} [οφειλεις]{.greek-omitted}[18:28]{.aside}

[πεσων]{.greek-omitted} [ουν]{.greek-omitted} [ο]{.greek-omitted} [συνδουλος]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [λεγων]{.greek-omitted} μακροθυμησον επ εμοι και [παντα]{.greek-added} [σ[ει]{.unclear}]{.greek-added} αποδωσω [σοι]{.greek-omitted}[18:29]{.aside}

ο δε ουκ ηθελεν [αλλα]{.greek-omitted} [αλλ]{.greek-added} απελθων εβαλεν αυτον εις φυλακην εως ου αποδω το οφειλομενον[18:30]{.aside}

ιδοντες δε οι συνδουλοι αυτου τα γενομενα ελυπηθησαν σφοδρα και ελθοντες διεσαφησαν τω κυριω εαυτων παντα [τα]{.greek-omitted} [τω]{.greek-added} γενομενα[18:31]{.aside}

τοτε προσκαλεσαμενος αυτον ο κυριος αυτου λεγει αυτω δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι [επει]{.greek-omitted} [επι]{.greek-added} παρεκαλεσας με[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως και εγω σε ηλεησα[18:33]{.aside}

και οργισθεις ο κυριος αυτου παρεδωκεν αυτον τοις βασανισταις εως ου αποδω παν το οφειλομενον αυτω[18:34]{.aside}

ουτως και ο [πατηρ]{.greek-abbr} μου ο [επουρανιος]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} ποιησει υμιν εαν μη [αφητε]{.greek-omitted} [αφηται]{.greek-added} εκαστος τω αδελφω αυτου απο των καρδιων υμων [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [αυτων]{.greek-omitted}[18:35]{.aside}

### Chapter 19

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και [προσηλθον]{.greek-omitted} [ροσηλθον]{.greek-added} αυτω [οι]{.greek-omitted} φαρισαιοι πειραζοντες [αυτον]{.greek-omitted} και λεγοντες [αυτω]{.greek-omitted} [αυτον]{.greek-added} ει εξεστιν [ανθρωπω]{.greek-abbr} απολυσαι την γυναικα αυτου κατα πασαν αιτιαν[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ ανεγνωτε οτι ο ποιησας απ αρχης αρσεν και θηλυ εποιησεν αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου [καταλειψει]{.greek-omitted} [καταληψει]{.greek-added} [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} [αυτου]{.greek-added} και την [μητερα]{.greek-abbr} και [προσκολληθησεται]{.greek-omitted} [προσκολληθησετε]{.greek-added} τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα σαρξ μια ο ουν ο [θεος]{.greek-abbr} [συνεζευξεν]{.greek-omitted} [εζευξεν]{.greek-added} [ανθρωπος]{.greek-abbr} μη χωριζετω[19:6]{.aside}

λεγουσιν αυτω τι ουν [μωσης]{.greek-omitted} [μωυσης]{.greek-added} ενετειλατο δουναι βιβλιον αποστασιου και απολυσαι αυτην[19:7]{.aside}

λεγει αυτοις οτι [μωσης]{.greek-omitted} [μωυσης]{.greek-added} προς την σκληροκαρδιαν υμων επετρεψεν υμιν απολυσαι τας γυναικας υμων απ αρχης δε ου [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} ουτως[19:8]{.aside}

λεγω δε υμιν οτι ος [αν]{.greek-omitted} [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου μη επι πορνεια και [γαμηση]{.greek-omitted} [γαμησει]{.greek-added} αλλην μοιχαται και ο απολελυμενην γαμησας μοιχαται[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει ουτως εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφερει γαμησαι[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες [χωρουσιν]{.greek-omitted} [χωρουσι]{.greek-added} τον λογον τουτον αλλ οις δεδοται[19:11]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ ευνουχοι οιτινες εκ κοιλιας [μητρος]{.greek-abbr} [αυτων]{.greek-added} εγεννηθησαν ουτως και εισιν ευνουχοι οιτινες ευνουχισθησαν υπο των [ανθρωπων]{.greek-abbr} και εισιν ευνουχοι οιτινες [ευνουχισαν]{.greek-omitted} [ευνουχησαν]{.greek-added} εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος χωρειν χωρειτω[19:12]{.aside}

τοτε προσηνεχθη αυτω παιδια ινα τας χειρας επιθη αυτοις και προσευξηται οι δε μαθηται επετιμησαν αυτοις[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε τα παιδια και μη κωλυετε αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και επιθεις αυτοις τας χειρας επορευθη εκειθεν[19:15]{.aside}

και ιδου εις προσελθων ειπεν αυτω διδασκαλε αγαθε τι αγαθον ποιησω ινα [εχω]{.greek-omitted} [κληρονομησω]{.greek-added} ζωην αιωνιον[19:16]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr} ει δε θελεις εισελθειν εις την ζωην τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το ου [φονευσεις]{.greek-omitted} [φωνευσεις]{.greek-added} ου [μοιχευσεις]{.greek-omitted} [μηχευσεις]{.greek-added} ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} και αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[19:19]{.aside}

λεγει αυτω ο νεανισκος [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} εφυλαξαμην εκ νεοτητος μου τι [ετι]{.greek-omitted} [ετη]{.greek-added} υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελεις τελειος ειναι υπαγε πωλησον σου τα υπαρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} [ακολουθη]{.greek-added} [ακολουθει]{.corr} μοι[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον απηλθεν λυπουμενος ην γαρ εχων κτηματα πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου αμην λεγω υμιν οτι δυσκολως πλουσιος εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν δε λεγω [υμιν]{.greek-omitted} [ημιν]{.greek-added} [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια τρυπηματος ραφιδος [διελθειν]{.greek-omitted} [εισελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[19:24]{.aside}

ακουσαντες δε οι μαθηται αυτου εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

εμβλεψας δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα [δε]{.greek-omitted} [τω]{.greek-added} [θεω]{.greek-abbr} παντα δυνατα[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω [[κυριε]{.greek-abbr}]{.greek-added} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.corr} ειπεν αυτοις αμην λεγω υμιν οτι [υμεις]{.greek-omitted} [υμης]{.greek-added} οι [ακολουθησαντες]{.greek-omitted} [ακωλουθησαντες]{.greek-added} μοι εν τη παλιγγενεσια οταν [καθιση]{.greek-omitted} [καθεισει]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου [καθισεσθε]{.greek-omitted} [καθησεσθαι]{.greek-added} και υμεις επι δωδεκα [θρονους]{.greek-omitted} [θρονων]{.greek-added} κρινοντες τας δωδεκα φυλας του [ισραηλ]{.greek-abbr}[19:28]{.aside}

και πας [ος]{.greek-omitted} [οστις]{.greek-added} αφηκεν οικιας η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η [γυναικα]{.greek-omitted} [γυνεκα]{.greek-added} η τεκνα η αγρους ενεκεν του ονοματος μου εκατονταπλασιονα [ληψεται]{.greek-omitted} [λημψεται]{.greek-added} και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[19:30]{.aside}

### Chapter 20

ομοια γαρ εστιν [η]{.unclear} βασιλεια των [ουρανων]{.greek-omitted} [ουρα]{.greek-added} [νων]{.greek-added} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

[και]{.corr} συμφωνησας [δε]{.greek-added} μετα των εργατων εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι τριτην [ευρεν]{.greek-added} [ωραν]{.greek-omitted} [ειδεν]{.greek-omitted} αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

[και]{.greek-omitted} [εκεινοις]{.greek-omitted} [κακεινοις]{.greek-added} ειπεν υπαγετε και υμεις εις τον [αμπελων]{.greek-added} [αμπελωνα]{.corr} [μου]{.greek-added} και ο εαν [η]{.greek-omitted} [ει]{.greek-added} δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν [δε]{.greek-added} εξελθων περι εκτην [ωραν]{.greek-added} και ενατην [ωραν]{.greek-omitted} εποιησεν ωσαυτως[20:5]{.aside}

περι δε την ενδεκατην ωραν εξελθων [ευρεν]{.greek-omitted} [ειδεν]{.greek-added} αλλους εστωτας αργους και λεγει αυτοις τι ωδε εστηκατε [αργοι]{.greek-added} ολην την [ημεραν]{.greek-omitted} [υμεραν]{.greek-added} [αργοι]{.greek-omitted}[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο [λεγει]{.greek-omitted} [λεγοι]{.greek-added} αυτοις υπαγετε και υμεις εις τον αμπελωνα [μου]{.greek-added} και ο εαν [η]{.greek-omitted} [ει]{.greek-added} δικαιον [ληψεσθε]{.greek-omitted} [ληψεσθαι]{.greek-added}[20:7]{.aside}

οψιας δε γενομενης λεγει ο κυριος του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των εσχατων εως των πρωτων[20:8]{.aside}

και ελθοντες οι περι την ενδεκατην ωραν ελαβον ανα δηναριον[20:9]{.aside}

ελθοντες δε οι πρωτοι ενομισαν οτι πλειονα ληψονται και ελαβον και αυτοι ανα [δηναριον]{.greek-omitted} [δηνα]{.greek-added} [ριον]{.greek-added}[20:10]{.aside}

λαβοντες δε εγογγυζον κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι ουτοι οι εσχατοι μιαν ωραν εποιησαν και ισους [ημιν]{.greek-omitted} [ημας]{.greek-added} αυτους εποιησας τοις [βαστασασιν]{.greek-omitted} [βαστασασι]{.greek-added} το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν [ενι]{.greek-omitted} [αυτων]{.greek-omitted} [αυτω]{.greek-added} [εταιρε]{.greek-omitted} [ετερε]{.greek-added} ουκ αδικω [σε]{.greek-omitted} [σαι]{.greek-added} ουχι [δηναριου]{.greek-omitted} [δυναριου]{.greek-added} συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε [τουτω]{.corr} τω εσχατω δουναι ως και σοι[20:14]{.aside}

η ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} μοι ποιησαι ο θελω εν τοις εμοις ει ο οφθαλμος σου πονηρος [εστιν]{.greek-omitted} [εστην]{.greek-added} οτι εγω αγαθος ειμι[20:15]{.aside}

ουτως [εσονται]{.greek-omitted} [αισονται]{.greek-added} οι εσχατοι πρωτοι και οι πρωτοι εσχατοι πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

και αναβαινων ο [ιησους]{.greek-abbr} εις ιεροσολυμα [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} τους δωδεκα μαθητας [αυτου]{.greek-added} κατ ιδιαν εν τη οδω και ειπεν αυτοις[20:17]{.aside}

ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω[20:18]{.aside}

και [παραδωσουσιν]{.greek-omitted} [παραδοσουσιν]{.greek-added} αυτον τοις εθνεσιν εις το εμπαιξαι και μαστιγωσαι και [σταυρωσαι]{.greek-abbr} και τη τριτη ημερα [αναστη[σ]{.unclear}αι]{.greek-added} [αναστησεται]{.corr}[20:19]{.aside}

τοτε προσηλθεν αυτω η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και αιτουσα τι παρ αυτου[20:20]{.aside}

ο δε ειπεν αυτη τι θελεις λεγει αυτω ειπε ινα [καθισωσιν]{.greek-omitted} [καθησωσιν]{.greek-added} ουτοι οι δυο υιοι μου εις εκ δεξιων σου και εις εξ ευωνυμων σου εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν [αυτη]{.greek-added} ουκ [οιδατε]{.greek-omitted} [οιδας]{.greek-added} τι [αιτεισθε]{.greek-omitted} [αιτεισαι]{.greek-added} δυνασθε πιειν το ποτηριον ο εγω μελλω πινειν [η]{.greek-omitted} [και]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι [βαπτισθηναι]{.greek-omitted} [βαπτισθυναι]{.greek-added} λεγουσιν αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου [πιεσθε]{.greek-omitted} [πιεσθαι]{.greek-added} και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ [δε]{.greek-added} [δεξιων]{.greek-omitted} [ξιων]{.greek-added} μου και εξ ευωνυμων μου ουκ εστιν εμον [τουτο]{.greek-added} δουναι αλλ οις ητοιμασται υπο του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα ηγανακτησαν περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν [ουκ]{.greek-added} οιδατε οτι οι αρχοντες των εθνων κατακυριευουσιν αυτων και οι μεγαλοι [κατεξουσιν]{.greek-added} [κατεξουσιαζουσιν]{.corr} αυτων[20:25]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} εν υμιν [μεγας]{.greek-omitted} [γενεσθαι]{.greek-omitted} [ειναι]{.greek-added} [πρωτος]{.greek-added} εσται υμων διακονος[20:26]{.aside}

και ος εαν [θελη]{.greek-omitted} [θελει]{.greek-added} εν υμιν [ειναι]{.greek-omitted} [πρωτος]{.greek-omitted} [εστω]{.greek-omitted} [μεγας]{.greek-added} [γενεσθαι]{.greek-added} [εσται]{.greek-added} υμων δουλος[20:27]{.aside}

ωσπερ ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθαι]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και [εκπορευομενων]{.greek-omitted} [εκπορευομενον]{.greek-added} αυτων απο ιεριχω ηκολουθησεν αυτω οχλος πολυς[20:29]{.aside}

και ιδου δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} [παραγει]{.greek-omitted} [παραγη]{.greek-added} [εκραξαν]{.greek-omitted} [[παρεστη]{.corr}]{.greek-added} [εκραζον]{.greek-added} λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

ο δε οχλος επετιμησεν αυτοις ινα σιωπησωσιν οι δε [μειζον]{.greek-omitted} [μειζων]{.greek-added} εκραζον λεγοντες ελεησον ημας [κυριε]{.greek-omitted} υιος [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-abbr} εφωνησεν [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι [θελετε]{.greek-omitted} [θελεται]{.greek-added} ποιησω υμιν[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-omitted} ινα ανοιχθωσιν [ημων]{.greek-omitted} [υμων]{.greek-added} οι οφθαλμοι[20:33]{.aside}

[σπλαγχνισθεις]{.greek-omitted} [σπλαγχνισθης]{.greek-added} δε ο [ιησους]{.greek-abbr} ηψατο των οφθαλμων αυτων και ευθεως ανεβλεψαν αυτων οι [οφ]{.greek-added} [οφθαλμοι]{.greek-omitted} [θαλμοι]{.greek-added} και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε ηγγισαν εις ιεροσολυμα και ηλθον εις βηθσφαγη [και]{.greek-added} [βηθανιαν]{.greek-added} προς το ορος των [ελαιων]{.greek-omitted} [ελεων]{.greek-added} τοτε [ο]{.greek-omitted} [ιησους]{.greek-omitted} απεστειλεν δυο [μαθητας]{.greek-omitted} [των]{.greek-added} [μαθητων]{.greek-added} [αυτου]{.greek-added}[21:1]{.aside}

λεγων αυτοις πορευθητε εις την κωμην την απεναντι υμων και ευθεως [ευρησετε]{.greek-omitted} [ευρησητε]{.greek-added} ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο κυριος αυτων χρειαν εχει ευθεως δε [αποστελλει]{.greek-omitted} [αποστελει]{.greek-added} αυτους[21:3]{.aside}

[τουτον]{.greek-added} [τουτο]{.corr} δε ολον [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο [βα]{.greek-added} [βασιλευς]{.greek-omitted} [σιλευς]{.greek-added} σου ερχεται σοι πρα[υ]{.unclear}ς [[πραεις]{.corr}]{.greek-added} και επιβεβηκως επι ονον και πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες καθως προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και τον πωλον και επεθηκαν επανω [αυτων]{.greek-omitted} [αυτον]{.greek-added} τα ιματια αυτων και [επεκαθισεν]{.greek-omitted} [επεκαθησεν]{.greek-added} επανω αυτων[21:7]{.aside}

ο δε [πλειστος]{.greek-omitted} [πλιστος]{.greek-added} οχλος εστρωσαν εαυτων τα ιματια εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και [εστρωννυον]{.greek-omitted} [εστρωννιον]{.greek-added} εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} [ευλο]{.greek-added} [ευλογημενος]{.greek-omitted} [γημενος]{.greek-added} ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

και εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον του [θεου]{.greek-abbr} και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} παντας τους πωλουντας και αγοραζοντας [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται ο οικος μου οικος προσευχης κληθησεται υμεις δε αυτον εποιησατε σπηλαιον ληστων[21:13]{.aside}

και προσηλθον αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

ιδοντες δε οι αρχιερεις και οι [γραμματεις]{.greek-omitted} [γραμματοις]{.greek-added} τα θαυμασια α εποιησεν [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} και τους παιδας κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} ηγανακτησαν[21:15]{.aside}

και ειπον αυτω ακουεις τι ουτοι [λεγουσιν]{.greek-omitted} [λεγουσυν]{.greek-added} ο δε [ιησους]{.greek-abbr} λεγει αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και [θηλαζοντων]{.greek-omitted} [θηλαζωντων]{.greek-added} [κατηρτισω]{.greek-omitted} [κατηρτησω]{.greek-added} αινον[21:16]{.aside}

και καταλιπων αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη εκει[21:17]{.aside}

πρωιας [δ]{.unclear}ε επαναγων εις την [πολιν]{.greek-omitted} [πολην]{.greek-added} [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει μη φυλλα μονον και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη παραχρημα η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν [εχητε]{.greek-omitted} [εχεται]{.greek-added} πιστιν και μη [διακριθητε]{.greek-omitted} [διακριθειτε]{.greek-added} ου μονον το της συκης [ποιησετε]{.greek-omitted} [ποιησητε]{.greek-added} αλλα καν τω ορει τουτω ειπητε αρθητι και βληθητι εις την θαλασσαν γενησεται[21:21]{.aside}

και παντα οσα εαν αιτησητε εν τη προσευχη [υμων]{.greek-added} πιστευοντες [ληψεσθε]{.greek-omitted} [λημψεσθαι]{.greek-added}[21:22]{.aside}

και ελθοντι αυτω εις το ιερον [προσηλθον]{.greek-omitted} [προσηλθων]{.greek-added} αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις σοι εδωκεν την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω υμας καγω λογον ενα [ον]{.greek-omitted} [ο]{.greek-added} εαν ειπητε μοι καγω [ερω]{.greek-added} υμιν [ερω]{.greek-omitted} εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ποθεν ην εξ [ουρανου]{.greek-abbr} [ην]{.greek-added} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο [παρ]{.greek-omitted} [πα]{.greek-added} [ρ]{.greek-added} εαυτοις λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει ημιν δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[21:25]{.aside}

εαν δε ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον ιωαννην ως προφητην[21:26]{.aside}

και αποκριθεντες τω [ιησου]{.greek-abbr} ειπον ουκ οιδαμεν εφη αυτοις και αυτος ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} τεκνα δυο και προσελθων τω πρωτω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

ο δε [αποκριθεις]{.greek-omitted} [αποκρι]{.greek-added} [θεις]{.greek-added} ειπεν ου θελω υστερον δε μεταμεληθεις [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:29]{.aside}

και προσελθων τω [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν ωσαυτως ο δε αποκριθεις ειπεν εγω [κυριε]{.greek-abbr} και ουκ [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:30]{.aside}

τις εκ των δυο [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ προς υμας ιωαννης εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω οι δε τελωναι και αι πορναι επιστευσαν αυτω [υμεις]{.greek-omitted} [υμης]{.greek-added} δε ιδοντες ου μετεμεληθητε υστερον του πιστευσαι αυτω[21:32]{.aside}

αλλην παραβολην ακουσατε [ανθρωπος]{.greek-abbr} τις ην οικοδεσποτης οστις [εφυτευσεν]{.greek-omitted} [εφυτευσε]{.greek-added} αμπελωνα και φραγμον αυτω [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} και ωρυξεν εν αυτω ληνον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[21:33]{.aside}

οτε δε ηγγισεν ο καιρος των καρπων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και λαβοντες οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους τον υιον αυτου λεγων εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον ειπον εν εαυτοις [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [κληρονομος]{.greek-omitted} δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και [λαβοντες]{.greek-omitted} [λαβον]{.greek-added} [τες]{.greek-added} αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

[οταν]{.greek-omitted} [οτε]{.greek-added} ουν ελθη ο κυριος του αμπελωνος τι ποιησει τοις γεωργοις [εκεινης]{.greek-added} [εκεινοις]{.greek-omitted} [[εκεινεις]{.corr}]{.greek-added}[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα [εκδωσεται]{.greek-omitted} [εκδοσεται]{.greek-added} αλλοις γεωργοις οιτινες αποδωσουσιν αυτω τους καρπους εν τοις [καρ]{.greek-added} [καιροις]{.corr} αυτων[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} ουδεποτε ανεγνωτε εν ταις γραφαις λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστη]{.greek-added} θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν οτι αρθησεται αφ υμων η βασιλεια του [θεου]{.greek-abbr} και δοθησεται εθνει ποιουντι τους καρπους αυτης[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν πεση λικμησει αυτον[21:44]{.aside}

και ακουσαντες οι [αρχιερεις]{.greek-omitted} [αρχιεροις]{.greek-added} και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι [εφοβηθησαν]{.greek-omitted} [εφοβηθεισαν]{.greek-added} τους οχλους επειδη ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

[κ]{.unclear}αι αποκριθεις ο [ιησους]{.greek-abbr} παλιν ειπεν αυτοις εν παραβολαις λεγων[22:1]{.aside}

[ωμοιωθη]{.greek-omitted} [ομοιωθη]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω αυτου[22:2]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου καλεσαι τους κεκλημενους εις τους γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων ειπατε τοις κεκλημενοις ιδου το αριστον μου [ητοιμασα]{.greek-omitted} [ετοιμον]{.greek-added} οι ταυροι μου και τα [σιστα]{.greek-added} [σιτιστα]{.corr} τεθυμενα και παντα ετοιμα δευτε εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον ο δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε λοιποι [κρα]{.greek-added} [κρατησαντες]{.greek-omitted} [τησαντες]{.greek-added} τους δουλους αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος [ωργισθη]{.greek-omitted} [οργισθη]{.greek-added} και πεμψας τα στρατευματα αυτου [απωλεσεν]{.greek-omitted} [απωλεσε]{.greek-added} τους [φονεις]{.greek-omitted} [φωνεις]{.greek-added} εκεινους και την πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενεπρησε]{.greek-added}[22:7]{.aside}

[το]{.greek-added} τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

[πορευεσθε]{.greek-omitted} [πορευθεντες]{.greek-added} ουν επι τας διεξοδους των οδων και οσους αν ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους συνηγαγον [παντας]{.greek-omitted} οσους ευρον πονηρους τε και [α]{.greek-added} [αγαθους]{.greek-omitted} [γαθους]{.greek-added} και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου [χειρας]{.greek-added} [και]{.greek-added} ποδας [και]{.greek-omitted} [χειρας]{.greek-omitted} αρατε αυτον και [εκβαλετε]{.greek-omitted} [εμβαλλετε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε [εκλεκτοι]{.greek-omitted} [εκκλεκτοι]{.greek-added}[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον ελαβον [οπως]{.greek-omitted} [αυτον]{.greek-omitted} [παγιδευσωσιν]{.greek-omitted} [εν]{.greek-omitted} [λογω]{.greek-omitted}[22:15]{.aside}

[και]{.greek-omitted} [αποστελλουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτων]{.greek-omitted} μετα των ηρωδιανων λεγοντες διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν [ημιν]{.greek-omitted} [υμιν]{.greek-added} τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι κηνσον καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του κηνσου οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις αποδοτε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι [οι]{.greek-omitted} λεγοντες μη ειναι αναστασιν και επηρωτησαν αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης [ειπεν]{.greek-omitted} [ειπε]{.greek-added} εαν τις αποθανη μη εχων τεκνα επιγαμβρευσει ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος γαμησας [ετελευτησεν]{.greek-omitted} [ετελευτησε]{.greek-added} και μη εχων σπερμα [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος [εως]{.greek-omitted} [ε]{.greek-added} των επτα[22:26]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις πλανασθε μη [ειδοτες]{.greek-omitted} [ιδοντες]{.greek-added} τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε εκγαμιζονται αλλ ως αγγελοι του [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν [υμιν]{.greek-omitted} [ημιν]{.greek-added} υπο του [θεου]{.greek-abbr} [δια]{.greek-added} [του]{.greek-added} [προφητου]{.greek-added} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημωσε]{.greek-added} τους σαδδουκαιους συνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} [εφη]{.greek-omitted} [ειπεν]{.greek-added} αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη [τη]{.greek-added} καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται κρεμανται[22:40]{.aside}

συνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} [εν]{.greek-added} [[πνευματι]{.greek-abbr}]{.greek-added} καλει αυτον [κυριον]{.greek-abbr} πως υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added}[22:45]{.aside}

και ουδεις εδυνατο [ανταποκριθηναι]{.greek-added} αυτω [αποκριθηναι]{.greek-omitted} λογον ουδε [ετολμησεν]{.greek-omitted} [ετολ]{.greek-added} [μησε]{.greek-added} τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και ποιειτε κατα δε τα εργα αυτων μη ποιειτε [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} γαρ φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} δε τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των [ιματιων]{.greek-omitted} [ιματιον]{.greek-added} αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} τε την [προτοκλισιαν]{.greek-added} [πρωτοκλισιαν]{.corr} εν τοις δειπνοις και [τας]{.greek-omitted} [ταις]{.greek-added} πρωτοκαθεδριας εν [ταις]{.greek-omitted} [τες]{.greek-added} [συναγωγες]{.greek-added} [συναγωγαις]{.corr}[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι ραββι[23:7]{.aside}

υμεις δε μη [κληθητε]{.greek-omitted} [κληθειτε]{.greek-added} ραββι εις γαρ εστιν υμων ο [καθηγητης]{.greek-omitted} [διδασκαλος]{.greek-added} ο [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη καλεσητε [υ]{.greek-added} [υμων]{.greek-omitted} [μων]{.greek-added} επι της γης εις γαρ εστιν ο [πατηρ]{.greek-abbr} υμων ο εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr}[23:9]{.aside}

μηδε [κληθητε]{.greek-omitted} [κληθειτε]{.greek-added} καθηγηται εις γαρ [υμων]{.greek-omitted} εστιν ο καθηγητης ο [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων εσται υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [δε]{.greek-omitted} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθε]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [εισελθειν]{.greek-added}[23:13]{.aside}

ουαι [δε]{.greek-added} υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χηρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψονται]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [περιαγετε]{.greek-omitted} [περιαγεται]{.greek-added} την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν γενηται ποιειτε αυτον υιον γεεννης διπλοτερον υμων[23:15]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες ος αν [ομοση]{.greek-omitted} [ομωσει]{.greek-added} εν τω ναω ουδεν εστιν ος δ αν [ομοση]{.greek-omitted} [ομωσει]{.greek-added} εν τω χρυσω του ναου οφειλει[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} [ομοση]{.greek-omitted} [ομοσει]{.greek-added} εν τω θυσιαστηριω ουδεν εστιν ος δ αν [ομοση]{.greek-omitted} [ομωσει]{.greek-added} εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι [τι]{.greek-omitted} [τις]{.greek-added} γαρ [μειζον]{.greek-omitted} [μειζων]{.greek-added} το δωρον η το θυσιαστηριον το [αγιαζον]{.greek-omitted} [αγιαζων]{.greek-added} το δωρον[23:19]{.aside}

ο ουν [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω θυσιαστηριω ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω ναω ομνυει εν αυτω και εν τω κατοικησαντι [αυτον]{.greek-omitted} [εν]{.greek-added} [αυτω]{.greek-added}[23:21]{.aside}

και ο [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [αποδεκατουτε]{.greek-omitted} [αποδεκατουται]{.greek-added} το ηδυοσμον και το [ανηθον]{.greek-omitted} [ανιθον]{.greek-added} και το κυμινον και αφηκατε τα βαρυτερα του νομου την κρισιν και τον ελεον και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι τυφλοι οι διυλιζοντες τον [κωνωπα]{.greek-omitted} [κονοπα]{.greek-added} την δε καμηλον καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι καθαριζετε το εξωθεν του ποτηριου και της παροψιδος [του]{.greek-added} [πινακος]{.greek-added} εσωθεν δε γεμουσιν εξ αρπαγης και [αδικιας]{.greek-omitted} [ακρασιας]{.greek-added}[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος αυτων καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [παρομοιαζετε]{.greek-omitted} [παροιμιαζετε]{.greek-added} ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

ουτως και υμεις εξωθεν μεν [φαινεσθε]{.greek-omitted} [φαινεσθαι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι εστε υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι οικοδομειτε τους ταφους των προφητων και κοσμειτε τα μνημεια των δικαιων[23:29]{.aside}

και λεγετε ει [ημεν]{.greek-omitted} [ημεθα]{.greek-added} εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν [ημεν]{.greek-omitted} [ημεθα]{.greek-added} κοινωνοι αυτων εν τω αιματι των προφητων[23:30]{.aside}

ωστε μαρτυρειτε εαυτοις οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και υμεις [πληρωσατε]{.greek-omitted} [επληρωσατε]{.greek-added} το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

οφεις γεννηματα εχιδνων πως φυγητε απο της κρισεως της γεεννης[23:33]{.aside}

δια τουτο ιδου εγω αποστελλω προς υμας προφητας και σοφους και γραμματεις και εξ αυτων αποκτενειτε και [σταυρωσετε]{.greek-omitted} [[στρωσεται]{.greek-abbr}]{.greek-added} και εξ αυτων [μαστιγωσετε]{.greek-omitted} [μαστιγωσεται]{.greek-added} εν ταις συναγωγαις υμων και [διωξετε]{.greek-omitted} [διωξεται]{.greek-added} απο πολεως εις πολιν[23:34]{.aside}

οπως [αν]{.greek-added} ελθη εφ υμας παν αιμα [δικαιον]{.greek-omitted} [δικεον]{.greek-added} εκχυνομενον επι της γης απο του αιματος αβελ του δικαιου εως του αιματος ζαχαριου υιου βαραχιου ον [εφονευσατε]{.greek-omitted} [εφωνευσατε]{.greek-added} μεταξυ του ναου και του θυσιαστηριου[23:35]{.aside}

αμην λεγω υμιν οτι ηξει [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεινουσα]{.greek-added} τους προφητας και λιθοβολουσα τους [απεσταλμενους]{.greek-omitted} [αποσταλμενους]{.greek-added} προς αυτην ποσακις ηθελησα επισυναγαγειν τα τεκνα σου ον τροπον επισυναγει ορνις τα νοσσια εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται υμιν ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη με ιδητε απ αρτι εως αν ειπητε ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον οι μαθηται αυτου επιδειξαι αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ου βλεπετε [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη αφεθη ωδε λιθος επι λιθον ος ου [μη]{.greek-added} καταλυθησεται[24:2]{.aside}

καθημενου δε αυτου επι του ορους των ελαιων προσηλθον αυτω οι μαθηται κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της σης παρουσιας και της συντελειας του αιωνος[24:3]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις βλεπετε μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added}[24:5]{.aside}

μελλησετε δε ακουειν πολεμους [και]{.greek-added} [ακαταστασιας]{.greek-added} και ακοας πολεμων ορατε μη θροεισθε δει γαρ παντα γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εστι]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και [λοιμοι]{.greek-omitted} [και]{.greek-omitted} σεισμοι κατα τοπους[24:7]{.aside}

παντα δε ταυτα [αρχη]{.greek-omitted} [αρχαι]{.greek-added} ωδινων[24:8]{.aside}

τοτε παραδωσουσιν υμας εις θλιψιν και αποκτενουσιν υμας και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μισουμενοι υπο παντων των εθνων δια το ονομα μου [ο]{.greek-added} [δε]{.greek-added} [υπομεινας]{.greek-added} [εις]{.greek-added} [τελος]{.greek-added} [ουτος]{.greek-added} [σωθησεται]{.greek-added}[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους [πα]{.greek-added} [παραδωσουσιν]{.greek-omitted} [ραδωσουσι]{.greek-added} και μισησουσιν αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και [πλανησουσιν]{.greek-omitted} [πλανησουσι]{.greek-added} πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται τουτο το ευαγγελιον της βασιλειας εν ολη τη οικουμενη εις μαρτυριον [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν και τοτε ηξει το τελος[24:14]{.aside}

οταν ουν [ιδητε]{.greek-omitted} [ηδητε]{.greek-added} το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου εστως εν τοπω αγιω ο [ανα]{.greek-added} [αναγινωσκων]{.greek-omitted} [γινωσκων]{.greek-added} νοειτω[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν επι τα ορη[24:16]{.aside}

ο επι του δωματος μη καταβαινετω αραι τα εκ της οικιας αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω οπισω αραι τα ιματια αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις [θηλαζουσ[α]{.unclear}ς]{.greek-added} [θηλαζουσαις]{.corr} εν εκειναις ταις ημεραις[24:19]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος μηδε σαββατω[24:20]{.aside}

εσται γαρ τοτε θλιψις μεγαλη οια ου γεγονεν απ αρχης κοσμου εως του νυν ουδ ου μη [γενηται]{.greek-omitted} [γενη]{.greek-added} [ται]{.greek-added}[24:21]{.aside}

και ει μη εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους [κολοβωθησονται]{.greek-omitted} [κολοβοθησονται]{.greek-added} αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη πιστευσητε[24:23]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια μεγαλα και τερατα ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου προειρηκα υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω [εστιν]{.greek-omitted} [εστι]{.greek-added} μη εξελθητε ιδου εν τοις ταμειοις μη πιστευσητε[24:26]{.aside}

ωσπερ γαρ η αστραπη [εξερχεται]{.greek-omitted} [εξερ]{.greek-added} [χεται]{.greek-added} απο ανατολων και φαινεται εως δυσμων ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ εαν [η]{.greek-omitted} [ει]{.greek-added} το πτωμα [εκει]{.greek-omitted} [εκοι]{.greek-added} συναχθησονται οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε [κοψονται]{.greek-omitted} [κοψον]{.greek-added} [ται]{.greek-added} πασαι αι φυλαι της γης και οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

[μετα]{.greek-added} και αποστελει τους αγγελους αυτου μετα σαλπιγγος φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξουσι]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-abbr} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης μαθετε την παραβολην οταν ηδη ο κλαδος αυτης γενηται απαλος και τα φυλλα [εκφυη]{.greek-omitted} [εκφυει]{.greek-added} γινωσκετε οτι εγγυς το θερος[24:32]{.aside}

[ουτως]{.greek-omitted} [ου]{.greek-added} [τος]{.greek-added} και υμεις οταν ιδητε ταυτα παντα γινωσκετε οτι εγγυς εστιν επι θυραις[24:33]{.aside}

αμην λεγω υμιν ου μη παρελθη η γενεα αυτη εως αν παντα ταυτα γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη παρελευσονται οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[24:35]{.aside}

περι δε της ημερας εκεινης και ωρας ουδεις οιδεν ουδε οι αγγελοι των [ουρανων]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις προ του κατακλυσμου [τρωγοντες]{.greek-omitted} [τρωγον]{.greek-added} [τες]{.greek-added} και πινοντες γαμουντες και εκγαμιζοντες αχρι ης ημερας εισηλθεν [ο]{.greek-added} [κατακλυσμος]{.greek-added} [και]{.greek-added} νωε εις την κιβωτον[24:38]{.aside}

και [ουκ]{.greek-omitted} [εγνωσαν]{.greek-omitted} [εως]{.greek-omitted} ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο αληθουσαι εν τω μυλωνι μια παραλαμβανεται και μια [αφιεται]{.greek-omitted} [αφιε]{.greek-added} [ται]{.greek-added}[24:41]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} ουν οτι ουκ οιδατε [ποια]{.greek-omitted} [ωρα]{.greek-omitted} [την]{.greek-added} [ημεραν]{.greek-added} [[η]{.unclear}ν]{.greek-added} [[εν]{.corr}]{.greek-added} [η]{.greek-added} ο [κυριος]{.greek-abbr} [υμων]{.greek-omitted} ερχεται[24:42]{.aside}

εκεινο δε [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι ει ηδει ο οικοδεσποτης ποια φυλακη ο κλεπτης ερχεται εγρηγορησεν αν και ουκ αν [ειασεν]{.greek-omitted} [ειασε]{.greek-added} [διορυγηναι]{.greek-omitted} [διωρυγηναι]{.greek-added} την οικιαν αυτου[24:43]{.aside}

δια τουτο και υμεις γινεσθε ετοιμοι οτι η ωρα ου [δοκειτε]{.greek-omitted} [δοκειται]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και φρονιμος ον [κατεστησεν]{.greek-omitted} [καταστησει]{.greek-added} ο κυριος αυτου επι της θεραπειας αυτου του διδοναι αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο [δουλος]{.greek-omitted} [δου]{.greek-added} [λος]{.greek-added} εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου ευρησει ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει [μου]{.greek-added} ο κυριος [μου]{.greek-omitted} ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους εσθιειν δε και πινειν μετα των μεθυοντων[24:49]{.aside}

ηξει ο κυριος του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και διχοτομησει αυτον και το μερος αυτου [θησει]{.greek-added} μετα των υποκριτων [θησει]{.greek-omitted} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

τοτε [[ειπε]{.corr}]{.greek-added} [[ο]{.corr}]{.greek-added} [[[κυριος]{.greek-abbr}]{.corr}]{.greek-added} ομοιωθησεται [[ομιωθησεται]{.corr}]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων εξηλθον εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων [ελαιον]{.greek-omitted} [ελεον]{.greek-added}[25:3]{.aside}

αι δε φρονιμοι ελαβον [ελαιον]{.greek-omitted} [ελε]{.greek-added} [ον]{.greek-added} εν τοις αγγειοις αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και εκαθευδον[25:5]{.aside}

μεσης δε νυκτος κραυγη γεγονεν ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι ταις φρονιμοις ειπον δοτε [ημιν]{.greek-omitted} [υμιν]{.greek-added} εκ του ελαιου υμων οτι αι λαμπαδες [ημων]{.greek-omitted} [υμων]{.greek-added} σβεννυνται[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε [ουκ]{.greek-omitted} [ου]{.greek-added} [κ]{.greek-added} [αρκεση]{.greek-omitted} [αρκεσει]{.greek-added} ημιν και υμιν πορευεσθε δε μαλλον προς τους πωλουντας και αγορασατε εαυταις[25:9]{.aside}

απερχομενων δε αυτων αγορασαι ηλθεν ο νυμφιος και αι ετοιμοι [εισηλθον]{.greek-omitted} [ηλθον]{.greek-added} μετ αυτου εις τους γαμους και εκλεισθη η θυρα[25:10]{.aside}

υστερον δε ερχονται και αι λοιπαι παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

γρηγορειτε ουν οτι ουκ οιδατε την ημεραν ουδε την ωραν εν η ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} [αποδημων]{.greek-omitted} [αποδυμων]{.greek-added} [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα ω δε δυο ω δε εν εκαστω κατα την ιδιαν δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

πορευθεις δε ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα πεντε ταλαντα[25:16]{.aside}

ωσαυτως και ο τα δυο [ταλαντα]{.greek-added} [λαβων]{.greek-added} [εκερδησεν]{.greek-omitted} [εκερδυσε]{.greek-added} και αυτος αλλα δυο[25:17]{.aside}

ο δε το εν λαβων απελθων ωρυξεν εν τη γη και απεκρυψεν το αργυριον του κυριου αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο κυριος των δουλων εκεινων και [συν[ι]{.unclear}]{.greek-added} [συναιρει]{.corr} μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα πεντε ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη [δε]{.greek-omitted} αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [εις]{.greek-added} πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του κυριου σου[25:21]{.aside}

προσελθων δε και ο τα δυο ταλαντα [λαβων]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο [ταλαντα]{.greek-omitted} εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο κυριος αυτου ευ δουλε αγαθε και πιστε επι ολιγα [ης]{.greek-omitted} [εις]{.greek-added} πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του κυριου σου[25:23]{.aside}

προσελθων δε και ο το εν ταλαντον ειληφως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} εγνων σε οτι σκληρος ει [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο κυριος αυτου ειπεν αυτω πονηρε δουλε και οκνηρε [εκ]{.greek-added} [του]{.greek-added} [στοματος]{.greek-added} [σου]{.greek-added} [κρινω]{.greek-added} [σε]{.greek-added} ηδεις οτι θεριζω οπου ουκ εσπειρα και συναγω οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις τραπεζιταις και ελθων εγω εκομισαμην αν το εμον συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το [τα]{.greek-added} [ταλαντον]{.greek-omitted} [λαντον]{.greek-added} και δοτε τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο [δοκει]{.greek-added} [εχει]{.greek-omitted} [εχειν]{.greek-added} αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον [εκβαλετε]{.greek-omitted} [εμβαλετε]{.greek-added} εις το [σκοτος]{.greek-omitted} [σκωτος]{.greek-added} το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου τοτε [καθισει]{.greek-omitted} [καθησεται]{.greek-added} επι θρονου δοξης αυτου[25:31]{.aside}

και [συναχθησεται]{.greek-omitted} [συνα]{.greek-added} [χθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και αφοριει αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα προβατα απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ ευωνυμων[25:33]{.aside}

τοτε ερει ο βασιλευς τοις εκ δεξιων αυτου δευτε οι ευλογημενοι του [πατρος]{.greek-abbr} μου κληρονομησατε την ητοιμασμενην υμιν βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

επεινασα γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε με [ξε]{.greek-added} [ξενος]{.greek-omitted} [νος]{.greek-added} ημην και συνηγαγετε με[25:35]{.aside}

γυμνος και περιεβαλετε με ησθενησα και επεσκεψασθε με εν φυλακη ημην και ηλθετε προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} πεινωντα και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε [δε]{.greek-omitted} σε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} ξενον και [συνηγαγομεν]{.greek-omitted} [συνηγαγωμεν]{.greek-added} η γυμνον και [περιεβαλομεν]{.greek-omitted} [περιεβαλωμεν]{.greek-added}[25:38]{.aside}

ποτε δε σε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} [ασθενη]{.greek-omitted} [η]{.greek-omitted} [ασθενουντα]{.greek-added} [και]{.greek-added} εν φυλακη και [ηλθομεν]{.greek-omitted} [ηλθωμεν]{.greek-added} προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον εποιησατε ενι τουτων των αδελφων μου [των]{.greek-omitted} [ελαχιστων]{.greek-omitted} εμοι εποιησατε[25:40]{.aside}

τοτε ερει και τοις εξ ευωνυμων [πορευεσθε]{.greek-omitted} [υπαγετε]{.greek-added} απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το [ητοιμασμενον]{.greek-omitted} [ητοιμασμενω]{.greek-added} τω διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

επεινασα γαρ και ουκ εδωκατε μοι φαγειν εδιψησα και ουκ [εποτισα]{.greek-added} [εποτισατε]{.corr} με[25:42]{.aside}

ξενος ημην και ου συνηγαγετε με γυμνος και ου περιεβαλετε με ασθενης και εν φυλακη και ουκ επεσκεψασθε με[25:43]{.aside}

[τοτε]{.greek-omitted} [και]{.greek-added} αποκριθησονται και αυτοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} πεινωντα η [διψωντα]{.greek-omitted} [διψων]{.greek-added} [τα]{.greek-added} η ξενον η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ εποιησατε ενι τουτων των [αδελφων]{.greek-added} [μου]{.greek-added} [των]{.greek-added} ελαχιστων ουδε εμοι εποιησατε[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι εις ζωην αιωνιον[25:46]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου[26:1]{.aside}

οιδατε οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το [σταυρωθηναι]{.greek-abbr}[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του αρχιερεως του λεγομενου καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω [κρατησωσιν]{.greek-omitted} [κρατησωσι]{.greek-added} και αποκτεινωσιν[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται εν τω λαω[26:5]{.aside}

του δε [ιησου]{.greek-abbr} γενομενου εν βηθανια εν οικια σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου ηγανακτησαν λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

[ηδυνατο]{.greek-omitted} [ειδυνατο]{.greek-added} γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους [παρεχετε]{.greek-omitted} [παρεχεται]{.greek-added} τη γυναικι εργον γαρ καλον ειργασατο εις εμε[26:10]{.aside}

[παντοτε]{.greek-omitted} [γαρ]{.greek-omitted} τους πτωχους [εχετε]{.greek-omitted} [γαρ]{.greek-added} [παντοτε]{.greek-added} [εχεται]{.greek-added} μεθ εαυτων εμε δε ου παντοτε εχετε[26:11]{.aside}

βαλουσα γαρ αυτη το μυρον τουτο επι του σωματος μου προς το ενταφιασαι με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις μνημοσυνον αυτης[26:13]{.aside}

τοτε πορευθεις εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι [μοι]{.greek-added} θελετε [μοι]{.greek-omitted} δουναι καγω υμιν παραδωσω αυτον οι δε εστησαν αυτω τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε πρωτη των αζυ[μ]{.greek-supplied}ων προσηλθον οι μαθηται [αυτου]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} λεγοντες αυτω που θελεις [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν υπαγετε εις την πολιν προς τον δεινα και ειπατε αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς [εστιν]{.greek-omitted} [εστι]{.greek-added} προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

και εποιησαν οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο [μετα]{.greek-omitted} [με]{.greek-added} των δωδεκα[26:20]{.aside}

και εσθιοντων αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων [παραδωσει]{.greek-omitted} [παραδοσει]{.greek-added} με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν αυτω εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε [αποκριθεις]{.greek-omitted} [αποκρι]{.greek-added} [θεις]{.greek-added} ειπεν ο εμβαψας μετ εμου εν τω τρυβλιω την χειρα ουτος με [παραδωσει]{.greek-omitted} [παραδοσει]{.greek-added}[26:23]{.aside}

[και]{.greek-added} ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ [εγεννηθη]{.greek-omitted} [εγενηθη]{.greek-added} ο [ανθρωπος]{.greek-abbr} εκεινος[26:24]{.aside}

αποκριθεις δε ιουδας ο παραδιδους αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μητι εγω ειμι ραββι λεγει αυτω συ ειπας[26:25]{.aside}

[ε]{.greek-supplied}σθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} τον αρτον [ευχαριστησας]{.greek-added} [εκλασε]{.greek-added} και [εδι]{.greek-added} [δου]{.greek-added} [ευχαριστησας]{.greek-omitted} [εκλασεν]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} τοις μαθηταις [αυτου]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν οτι ου μη πιω απ αρτι εκ τουτου του γεννηματος της αμπελου [ταυτης]{.greek-added} εως της ημερας εκεινης οταν αυτο πινω μεθ υμων [καινον]{.greek-omitted} εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} παντες υμεις σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον ποιμενα και διασκορπισθησεται τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι εγω δε ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη [νυκτι]{.greek-omitted} [νυκ]{.greek-added} [τι]{.greek-added} πριν αλεκτορα φωνησαι τρις απαρνηση με[26:34]{.aside}

λεγει αυτω ο πετρος καν δεη με συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ομοιως δε και παντες οι μαθηται ειπον[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον λεγομενον γεθσημανη και λεγει τοις μαθηταις [αυτου]{.greek-added} [καθισατε]{.greek-omitted} [καθη[σα]{.unclear}τ[ε]{.unclear}]{.greek-added} [αυ]{.unclear}του εως [ου]{.greek-omitted} απελθων [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added} εκει[26:36]{.aside}

και παραλαβων τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο λυπεισθαι και αδημονειν[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε μετ εμου[26:38]{.aside}

και προσελθων μικρον [ε]{.unclear}πεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθετω απ εμου το ποτηριον τουτο πλην ουχ ως εγω θελω αλλ ως [συ]{.greek-omitted} [σοι]{.greek-added}[26:39]{.aside}

[και]{.unclear} [ε]{.unclear}ρχ[ε]{.unclear}ται προς τους μαθητας [αυτου]{.greek-added} και ευρισκει αυτους καθευδοντας και λεγει τω πετρω [ουτως]{.greek-omitted} [ουτος]{.greek-added} ουκ ισχυσατε μιαν ωραν [γρηγορησαι]{.greek-omitted} μετ εμου[26:40]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις [πειρασμον]{.greek-omitted} [πειρασ]{.greek-added} [μον]{.greek-added} το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου απελθων προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται τουτο το ποτηριον παρελθειν απ εμου εαν μη αυτο [πιω]{.greek-omitted} [ποιω]{.greek-added} γενηθητω το θελημα σου[26:42]{.aside}

και ελθων ευρισκει αυτους παλιν καθευδοντας ησαν γαρ αυτων ο[ι]{.unclear} οφθ[α]{.unclear}λμοι βεβαρημενοι[26:43]{.aside}

και αφεις αυτους απελθων παλιν προσηυξατο εκ τριτου τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις καθευδετε το λοιπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

εγειρεσθε αγωμεν [εντευθεν]{.greek-added} ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου [ιουδας]{.greek-omitted} εις των δωδεκα [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και μετ αυτου οχλος πολ[υς]{.unclear} [με]{.unclear}τα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον [λεγων]{.greek-omitted} ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον[26:48]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω εταιρε εφ ω παρει τοτε προσελθοντες επεβαλον τας χειρας επι [τον]{.greek-omitted} [των]{.greek-added} [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου [εις]{.greek-omitted} των μετα [ιησου]{.greek-abbr} εκτεινας την χειρα [απεσπασεν]{.greek-omitted} [απεσπασε]{.greek-added} την [μαχαιραν]{.greek-omitted} [μαχαιρα]{.greek-added} αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον[26:51]{.aside}

τοτε λεγει [αυτω]{.greek-omitted} [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} αποστρεψον [σου]{.greek-omitted} την μαχαιραν [σου]{.greek-added} εις [τον]{.greek-omitted} [τοπον]{.greek-omitted} [την]{.greek-added} [θηκην]{.greek-added} αυτης [παντες]{.unclear} γαρ ο[ι]{.unclear} λαβοντες μαχαιραν εν μαχαιρα [αποθανουνται]{.greek-omitted} [απολουνται]{.greek-added}[26:52]{.aside}

[η]{.greek-omitted} [ει]{.greek-added} δοκεις οτι ου δυναμαι [αρτι]{.greek-omitted} παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι οτι ουτως δει γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην εξηλθετε μετα μαχαιρων και ξυλων συλλαβειν με καθ ημεραν προς υμας εκαθεζομην διδασκων εν τω ιερω και ουκ εκρατησατε με[26:55]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} απηγαγον προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο δε πετρος [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω απο μακροθεν εως της αυλης του αρχιερεως [οπου]{.greek-added} [οι]{.greek-added} [γραμματεις]{.greek-added} [συνερχονται]{.greek-added} και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και [ολον]{.greek-added} το [συνεδριον]{.greek-omitted} [ολον]{.greek-omitted} [εζητουν]{.greek-omitted} [συνε]{.greek-added} [δριον]{.greek-added} [εζητει]{.greek-added} ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως [θανατωσωσιν]{.greek-omitted} [θανατωσουσιν]{.greek-added} αυτον[26:59]{.aside}

και ουχ ευρον και πολλων ψευδομαρτυρων προσελθοντων ουχ ευρον [υστερον]{.greek-added} [δε]{.greek-added} [προσελθοντες]{.greek-added} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και δια τριων ημερων [οικοδομησαι]{.greek-omitted} [οικοδομησω]{.greek-added} αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν [αποκρινη]{.greek-omitted} [αποκρινει]{.greek-added} τι ουτοι σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω εξορκιζω σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν ειπης ει συ ει ο [χριστος]{.greek-abbr} ο υιος του [θεου]{.greek-abbr}[26:63]{.aside}

[λε]{.greek-added} [λεγει]{.greek-omitted} [γει]{.greek-added} αυτω ο [ιησους]{.greek-abbr} συ ειπας πλην λεγω υμιν απ αρτι οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} καθημενον [εκ]{.greek-omitted} [εν]{.greek-added} δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64]{.aside}

τοτε ο αρχιερευς [διερρηξεν]{.greek-omitted} [διερρηξε]{.greek-added} τα ιματια αυτου λεγων οτι εβλασφημησεν τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες ειπον ενοχος θανατου [εστιν]{.greek-omitted} [εστι]{.greek-added}[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και [εκολαφισαν]{.greek-omitted} [εκολλαφησαν]{.greek-added} αυτον οι δε [ερραπισαν]{.greek-omitted} [εραπησαν]{.greek-added}[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο παισας σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη [κ]{.greek-supplied}αι προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν αυτων παντων λεγων ουκ οιδα τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει αυτοις εκει και ουτος ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν ηρνησατο μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον δε προσελθοντες οι εστωτες ειπον τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο [καταθεματιζειν]{.greek-omitted} [καταθεματιζην]{.greek-added} και ομνυειν οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ εφωνησεν[26:74]{.aside}

και [ε]{.greek-added} [εμνησθη]{.greek-omitted} [μνησθη]{.greek-added} ο πετρος του ρηματος του [ιησου]{.greek-abbr} ειρηκοτος αυτω οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω [εκλαυσεν]{.greek-omitted} [εκλαυσε]{.greek-added} πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον ελαβον παντες οι [αρχιερεις]{.greek-omitted} [αρχιερoις]{.greek-added} και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} ωστε θανατωσαι αυτον[27:1]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν αυτον ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε [ι]{.greek-supplied}δων ιουδας ο παραδιδους αυτον οτι κατεκριθη μεταμεληθεις [απεστρεψεν]{.greek-omitted} [απεστρεψε]{.greek-added} τα τριακοντα αργυρια τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και τ[οις]{.unclear} πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε [ειπον]{.greek-omitted} [oιπoν]{.greek-added} τι προς ημας συ οψει[27:4]{.aside}

και [ρι]{.greek-added} [ριψας]{.greek-omitted} [ψας]{.greek-added} τα αργυρια εν τω ναω [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια ειπον ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον [κορβαναν]{.greek-omitted} [κορβοναν]{.greek-added} επει τιμη αιματος εστιν[27:6]{.aside}

συμβουλιον [δε]{.greek-omitted} [τε]{.greek-added} λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της σημερον[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα τριακοντα αργυρια την τιμην του τετιμημενου ον ετιμησαντο απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα [συνεταξεν]{.greek-omitted} [συνεταξε]{.greek-added} μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ λεγεις[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και [των]{.greek-omitted} πρεσβυτερων [ουδεν]{.greek-omitted} [ουδε]{.greek-added} απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και ουκ απεκριθη αυτω προς ουδε εν ρημα ωστε θαυμαζειν τον [ημονα]{.greek-added} [ηγεμονα]{.corr} λιαν[27:14]{.aside}

κατα δε εορτην [ειωθει]{.greek-omitted} [ειωθη]{.greek-added} ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον [βαραββαν]{.greek-omitted} [βαρβαραβαν]{.greek-added}[27:16]{.aside}

συνηγμενων ουν αυτων ειπεν αυτοις ο πιλατος τινα θελετε [απο]{.greek-added} [των]{.greek-added} [δυο]{.greek-added} απολυσω υμιν [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} η [ιησουν]{.greek-abbr} [τον]{.greek-omitted} [το]{.greek-added} λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

[ηδει]{.greek-omitted} [ηδη]{.greek-added} γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτον η γυνη αυτου λεγουσα μηδεν σοι και τω δικαιω εκεινω πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα [αιτησωνται]{.greek-omitted} [αιτησονται]{.greek-added} τον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα θελετε απο των δυο απολυσω υμιν οι δε ειπον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added}[27:21]{.aside}

λεγει αυτοις ο [πιλατος]{.greek-omitted} [πιλα]{.greek-added} [τος]{.greek-added} τι ουν ποιησω [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr} λεγουσιν αυτω παντες [σταυρωθητω]{.greek-abbr}[27:22]{.aside}

ο δε ηγεμων εφη τι γαρ κακον εποιησεν οι δε περισσως εκραζον λεγοντες [σταυρωθητω]{.greek-abbr}[27:23]{.aside}

ιδων δε ο πιλατος οτι ουδεν [ωφελει]{.greek-omitted} [οφελει]{.greek-added} αλλα μαλλον θορυβος γινεται λαβων υδωρ απενιψατο τας χειρας απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις οψεσθε[27:24]{.aside}

και αποκριθεις πας ο λαος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} τον δε [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγγελλωσας]{.greek-added} παρεδωκεν ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του ηγεμονος παραλαβοντες τον [ιησουν]{.greek-abbr} εις το πραιτωριον συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και εκδυσαντες αυτον περιεθηκαν αυτω χλαμυδα κοκκινην[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και γονυπετησαντες εμπροσθεν αυτου ενεπαιζον αυτω λεγοντες χαιρε ο βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον εις την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την χλαμυδα και ενεδυσαν [αυτον]{.greek-omitted} τα ιματια αυτου και απηγαγον αυτον εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον ηγγαρευσαν ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον γολγοθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [λεγομενος]{.greek-omitted} [λεγομενον]{.greek-added} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω πιειν οξος μετα χολης μεμιγμενον και γευσαμενος ουκ ηθελεν πιειν[27:34]{.aside}

[σταυρωσαντες]{.greek-abbr} δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την αιτιαν αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-abbr} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουνται]{.greek-abbr} συν αυτω δυο λησται εις εκ δεξιων και εις εξ ευωνυμων[27:38]{.aside}

[και]{.greek-added} οι [δε]{.greek-omitted} παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} καταβηθι απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως δε και οι αρχιερεις εμπαιζοντες μετα των γραμματεων και πρεσβυτερων και φαρισαιων ελεγον[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι ει βασιλευς [ισραηλ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} καταβατω νυν απο του [σταυρου]{.greek-abbr} και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} επ αυτω[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω [νυν]{.greek-omitted} αυτον ει θελει αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι [συσταυρωθεντες]{.greek-abbr} [αυτω]{.greek-omitted} [αυτου]{.greek-added} ωνειδιζον αυτον[27:44]{.aside}

απο δε εκτης ωρας [εως]{.greek-added} [ωρας]{.greek-added} [ενατης]{.greek-added} σκοτος εγενετο επι πασαν την γην [εως]{.greek-omitted} [ωρας]{.greek-omitted} [ενατης]{.greek-omitted}[27:45]{.aside}

περι δε την [ενατην]{.greek-omitted} [ενδεκατην]{.greek-added} ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι λιμα [σαβαχθανι]{.greek-omitted} [σαβαχθανη]{.greek-added} τουτ [εστιν]{.greek-omitted} [εστι]{.greek-added} θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελιπες[27:46]{.aside}

[και]{.greek-added} τινες [δε]{.greek-omitted} των εκει εστωτων ακουσαντες ελεγον οτι ηλιαν φωνει ουτος[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και [περιθεις]{.greek-omitted} [περιθης]{.greek-added} καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας [σωσων]{.greek-omitted} [σωσον]{.greek-added} αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας [φωνη]{.greek-omitted} [φω]{.greek-added} [νη]{.greek-added} μεγαλη [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω και η γη εσεισθη και αι πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια ανεωχθησαν και πολλα σωματα των κεκοιμημενων αγιων ηγερθη[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου εισηλθον εις την αγιαν πολιν και [ενεφανισθησαν]{.greek-omitted} [ενεφανησθησαν]{.greek-added} πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} υιος ην ουτος[27:54]{.aside}

ησαν δε [εκει]{.greek-omitted} [και]{.greek-added} γυναικες πολλαι απο [μακροθεν]{.greek-omitted} [μακρο]{.greek-added} [θεν]{.greek-added} θεωρουσαι αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η μαγδαληνη και μαρια [η]{.greek-omitted} [του]{.greek-omitted} [ιακωβου]{.greek-omitted} [ιακωβω]{.greek-added} και ιωση [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ ος και αυτος [εμαθητευσεν]{.greek-omitted} [εμαθητευσε]{.greek-added} τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω ητησατο το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν αποδοθηναι το σωμα[27:58]{.aside}

και λαβων το σωμα ο ιωσηφ ενετυλιξεν αυτο σινδονι καθαρα[27:59]{.aside}

και [εθηκεν]{.greek-omitted} [εθετο]{.greek-added} αυτο εν τω καινω αυτου μνημειω ο ελατομησεν εν τη πετρα και [προσκυλισας]{.greek-omitted} [προσκυ]{.greek-added} [λισας]{.greek-added} λιθον μεγαν τη θυρα του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η μαγδαληνη και η αλλη μαρια [καθημεναι]{.greek-omitted} [καθημενοι]{.greek-added} απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς πιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι [εκεινος]{.greek-omitted} ο πλανος [εκεινος]{.greek-added} ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν ασφαλισθηναι τον ταφον εως της τριτης ημερας μηποτε ελθοντες οι μαθηται αυτου νυκτος κλεψωσιν αυτον και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} τω λαω ηγερθη απο των νεκρων και εσται η εσχατη πλανη χειρων της πρωτης[27:64]{.aside}

εφη [δε]{.greek-omitted} [αυ]{.greek-added} [αυτοις]{.greek-omitted} [τοις]{.greek-added} ο πιλατος εχετε κουστωδιαν υπαγετε ασφαλισασθε ως οιδατε[27:65]{.aside}

οι δε πορευθεντες [ησφαλισαντο]{.greek-omitted} [ησφαλισατο]{.greek-added} τον ταφον [σφραγισαντες]{.greek-omitted} [τον]{.greek-omitted} [λιθον]{.greek-omitted} μετα της κουστωδιας[27:66]{.aside}

### Chapter 28

οψε [δε]{.greek-omitted} σαββατων τη επιφωσκουση εις μιαν σαββατων [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} μαρια η μαγδαληνη και η αλλη μαρια [θερησαι]{.greek-added} [θεωρησαι]{.corr} τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} προσελθων απεκυλισεν τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

[αποκριθεις]{.greek-omitted} [αποκρι]{.greek-added} [θεις]{.greek-added} δε ο αγγελος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ταις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} μη φοβεισθε υμεις οιδα γαρ οτι [ιησουν]{.greek-abbr} τον [εσταυρωμενον]{.greek-abbr} ζητειτε[28:5]{.aside}

ουκ εστιν ωδε ηγερθη γαρ καθως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δευτε [ιδετε]{.greek-omitted} [ειδετε]{.greek-added} τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ πορευθεισαι ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου [ειπον]{.greek-omitted} [ειπα]{.greek-added} υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις αυτου[28:8]{.aside}

ως δε [επορευοντο]{.greek-omitted} [επορευθησαν]{.greek-added} απαγγειλαι [ταις]{.greek-added} [μαθηταις]{.greek-added} [αυτου]{.greek-added} [ως]{.greek-added} [δε]{.greek-added} [επορευθησαν]{.greek-added} [α]{.greek-added} [παγγειλαι]{.greek-added} τοις μαθηταις αυτου και ιδου [ιησους]{.greek-abbr} απηντησεν [αυταις]{.greek-omitted} [αυτοις]{.greek-added} λεγων χαιρετε αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[28:9]{.aside}

τοτε λεγει αυταις ο [ιησους]{.greek-abbr} μη φοβεισθε υπαγετε απαγγειλατε τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις [στρατ[ω]{.unclear}]{.greek-added} [στρατιωταις]{.corr}[28:12]{.aside}

[λε]{.greek-added} [λεγοντες]{.greek-omitted} [γοντες]{.greek-added} ειπατε οτι οι μαθηται αυτου νυκτος ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν [ακουσθη]{.greek-omitted} [ακουστη]{.greek-added} τουτο επι του ηγεμονος ημεις [πεισομεν]{.greek-omitted} [πεισωμεν]{.greek-added} αυτον και υμας αμεριμνους [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added}[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και [διεφημισθη]{.greek-omitted} [διεφημησθη]{.greek-added} ο λογος ουτος παρα [ι]{.unclear}ουδαιοις μεχρι της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν αυτω οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων εδοθη μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες μαθητευσατε παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων ειμι πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

