---
title: "Collation of Byz^RP^ vs 31852 (1852)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1852 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31852).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1852                                   	| λογος                              	|
| 1852 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1852 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1852               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1852                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1852 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1852                                                     	| [―]{.gap}                        	|
:::

## Acts

### Chapter 9

[ευρεν]{.greek-omitted} [δε]{.greek-omitted} [εκει]{.greek-omitted} [ανθρωπον]{.greek-omitted} [τινα]{.greek-omitted} [αινεαν]{.greek-omitted} [ονοματι]{.greek-omitted} [εξ]{.greek-omitted} [ετων]{.greek-omitted} [οκτω]{.greek-omitted} [κατακειμενον]{.greek-omitted} [επι]{.greek-omitted} [κραββατω]{.greek-omitted} ος ην παραλελυμενος[[9:33 *(lacunose)*]{.lacunose}]{.aside}

και ειπεν αυτω ο πετρος αινεα ιαται σε [ιησους]{.greek-abbr} ο [χριστος]{.greek-abbr} αναστηθι και στρωσον σεαυτ[ω]{.unclear} και ευθεως ανεστη[9:34]{.aside}

και ειδον αυτον παντες οι κατοικουντες λυδδαν και τον [ασσαρωνα]{.greek-omitted} [ασαρωναν]{.greek-added} οιτινες επεστρεψαν επι τον [κυριον]{.greek-abbr}[9:35]{.aside}

εν ιοππη δε τις ην μαθητρια ονοματι [ταβηθα]{.greek-omitted} [ταβιθα]{.greek-added} η διερμηνευομενη [λεγεται]{.greek-omitted} [λεγετε]{.greek-added} δορκας αυτη ην πληρης αγαθων εργων και ελεημοσυνων ων εποιει[9:36]{.aside}

εγενετο δε εν ταις ημεραις εκειναις ασθενησασαν αυτην αποθανειν λουσαντες δε αυτην εθηκαν εν υπερωω[9:37]{.aside}

εγγυς δε ουσης λυδδης τη ιοππη οι μαθηται ακουσαντες οτι πετρος εστιν εν αυτη απεστειλαν προς αυτον παρακαλουντες μη οκνησαι διελθειν εως αυτων[9:38]{.aside}

αναστας δε πετ[ρ]{.unclear}ος συνηλθεν αυτοις ον παραγενομενον αν[η]{.unclear}γ[α]{.unclear}γον εις το υπερωον [κ]{.unclear}αι παρεστησαν αυτω πασαι αι χηραι κλαι[ου]{.unclear}σαι και επιδεικνυμεναι χιτωνας και ιματια οσα εποιει μ[ε]{.unclear}τ αυ[τ]{.greek-supplied}[ω]{.unclear}ν ουσα η δορκας[9:39]{.aside}

  εκβαλων δε ε[ξω]{.greek-supplied} [παντ]{.greek-supplied}ας ο πετρος θεις τα γονατα προ[σηυξατο]{.greek-supplied} και επιστρεψας προς το [ταβηθα]{.greek-omitted} [σωμα]{.greek-added} [ειπεν]{.greek-supplied} ταβιθα αναστηθι η δε ηνοιξεν [τ]{.greek-supplied}[ου]{.unclear}[ς]{.greek-supplied} οφ[θ]{.unclear}αλ[μους]{.greek-supplied} αυτης και ιδουσα τον[9:40]{.aside}

δους δε αυτη χειρα [ανεστ]{.greek-supplied}ησεν αυτην φωνησας δε τους αγ[ι]{.unclear}ους και τα[ς]{.unclear} χηρας παρεστησεν αυτην ζωσαν[9:41]{.aside}

[γνωσ]{.greek-supplied}τον δε εγενετο καθ ολης της ιοππης [κ]{.unclear}αι πολλοι επιστευσαν επι τον [κυριον]{.greek-abbr}[9:42]{.aside}

εγενετο δε ημερας ικανας μειναι αυτον εν ιοππη παρα τινι σιμωνι βυρσει[9:43]{.aside}

### Chapter 10

ανηρ δε τις [ην]{.greek-omitted} εν καισαρεια ονοματι κορνηλιος εκατονταρχης εκ σπειρης της καλουμενης ιταλικης[10:1]{.aside}

ευσεβης και φοβουμενος τον [θεον]{.greek-abbr} συν παντι τω οικω αυτου ποιων τε ελεημοσυνας πολλας τω λαω και δεομενος του [θεου]{.greek-abbr} δια παντος[10:2]{.aside}

ειδεν εν οραματι φανερως ωσει ωραν ενατην της ημερας αγγελον του [θεου]{.greek-abbr} εισελθοντα προς αυτον και ειποντα αυτω κορνηλιε[10:3]{.aside}

ο δε ατενισας αυτω και εμφοβος γενομενος ειπεν τι εστιν [κυριε]{.greek-abbr} ειπεν δε αυτω αι προσευχαι σου και [αι]{.greek-omitted} [ελεημοσυναι]{.greek-omitted} [αιλεημοσυναι]{.greek-added} σου ανεβησαν εις μνημοσυνον ενωπιον του [θεου]{.greek-abbr}[10:4]{.aside}

και νυν πεμψον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[10:5]{.aside}

ουτος ξενιζεται παρα τινι σιμωνι βυρσει ω εστιν οικια παρα θαλασσαν[10:6]{.aside}

ως δε απηλθεν ο αγγελος ο λαλων τω κορνηλιω φωνησας δυο των οικετων αυτου και στρατιωτην ευσεβη των προσκαρτερουντων αυτω[10:7]{.aside}

και εξηγησαμενος αυτοις απαντα απεστειλεν αυτους εις την [ιοππην]{.greek-omitted} [ιωππην]{.greek-added}[10:8]{.aside}

τη δε επαυριον οδοιπορουντων εκεινων και τη πολει εγγιζοντων ανεβη πετρος επι το δωμα προσευξασθαι περι ωραν [εκτην]{.greek-omitted} [ενατην]{.greek-added}[10:9]{.aside}

εγενετο δε προσπεινος κα[ι]{.unclear} ηθελεν γευσασθαι παρασκευαζοντων δε εκεινων επεπεσεν επ αυτον εκστασις[10:10]{.aside}

και [θεωρει]{.greek-omitted} [θεορει]{.greek-added} τον [ουρανον]{.greek-abbr} ανεωγμενον και καταβαινον επ αυτον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις δεδεμενον και καθιεμενον επι της γης[10:11]{.aside}

εν ω υπηρχεν παντα τα τετραποδα της γης και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[10:12]{.aside}

και εγενετο φωνη προς αυτον αναστας πετρε θυσον και φαγε[10:13]{.aside}

ο δε πετρος ειπεν μηδαμως [κυριε]{.greek-abbr} [και]{.greek-added} οτι ουδεποτε εφαγον παν κοινον η ακαθαρτον[10:14]{.aside}

και φωνη παλιν εκ δευτερου προς αυτον α ο [θεος]{.greek-abbr} εκαθαρισεν συ μη κοινου[10:15]{.aside}

τουτο δε εγενετο επι [τρις]{.greek-omitted} [τρεις]{.greek-added} και παλιν ανεληφθη το σκευος εις τον [ουρανον]{.greek-abbr}[10:16]{.aside}

ως δε εν εαυτω διηπορει ο πετρος τι αν ειη το οραμα ο ειδεν και ιδου οι ανδρες οι απεσταλμενοι απο του κορνηλιου διερωτησαντες την οικιαν σιμωνος επεστησαν επι τον πυλωνα[10:17]{.aside}

και φωνησαντες επυνθανοντο ει σιμων ο επικαλουμενος πετρος ενθαδε ξενιζεται[10:18]{.aside}

του δε πετρου διενθυμουμενου περι του οραματος ειπεν αυτω το [πνευμα]{.greek-abbr} ιδου ανδρες ζητουσιν σε[10:19]{.aside}

αλλα αναστας καταβηθι και πορευου συν αυτοις μηδεν διακρινομενος διοτι εγω απεσταλκα αυτους[10:20]{.aside}

καταβας δε πετρος προς τους ανδρας [τους]{.greek-added} [απεσταλμενους]{.greek-added} [απο]{.greek-added} [κορνηλιου]{.greek-added} [προς]{.greek-added} [αυτον]{.greek-added} ειπεν ιδου εγω ειμι ον ζητειτε τις η αιτια δι ην παρεστε[10:21]{.aside}

οι δε ειπον κορνηλιος εκατονταρχης ανηρ δικαιος και φοβουμενος τον [θεον]{.greek-abbr} μαρτυρουμενος τε υπο ολου του εθνους των ιουδαιων εχρηματισθη υπο αγγελου αγιου μεταπεμψασθαι σε εις τον οικον αυτου και ακουσαι ρηματα παρα σου[10:22]{.aside}

[εισκαλεσαμενως]{.greek-added} [εισκαλεσαμενος]{.corr} ουν αυτους εξενισεν τη δε επαυριον ο πετρος εξηλθεν συν αυτοις και τινες των αδελφων των απο ιοππης συνηλθον αυτω[10:23]{.aside}

και τη επαυριον εισηλθον εις την καισαρειαν ο δε κορνηλιος ην προσδοκων αυτους συγκαλεσαμενος τους [συγκενεις]{.greek-added} [συγγενεις]{.corr} αυτου και τους αναγκαιους φιλους[10:24]{.aside}

ως δε εγενετο του εισελθειν τον πετρον συναντησας αυτω ο κορνηλιος πεσων επι τους ποδας προσεκυνησεν[10:25]{.aside}

ο δε πετρος αυτον ηγειρεν λεγων αναστηθι καγω αυτος [ανθρωπος]{.greek-abbr} ειμι[10:26]{.aside}

και συνομιλων αυτω εισηλθεν και ευρισκει συνεληλυθοτας πολλους[10:27]{.aside}

εφη τε προς αυτους υμεις επιστασθε ως αθεμιτον εστιν ανδρι ιουδαιω κολλασθαι η προσερχεσθαι αλλοφυλω και εμοι ο [θεος]{.greek-abbr} εδειξεν μηδενα κοινον η ακαθαρτον λεγειν [ανθρωπον]{.greek-abbr}[10:28]{.aside}

διο και αναντιρρητως ηλθον μεταπεμφθεις πυνθανομαι ουν τινι λογω [μετεπεμψασθε]{.greek-omitted} [μεταπεμψασθε]{.greek-added} με[10:29]{.aside}

και ο κορνηλιος εφη απο τεταρτης ημερας μεχρι ταυτης της ωρας ημην νηστευων και την ενατην ωραν [προσ]{.greek-added} [προσευχομενος]{.greek-omitted} [ευχομενος]{.greek-added} εν τω οικω μου και ιδου ανηρ εστη ενωπιον μου εν εσθητι λαμπρα[10:30]{.aside}

και φησιν κορνηλιε εισηκουσθη σου η προσευχη και [αι]{.greek-omitted} [ελεημοσυναι]{.greek-omitted} [αιλεημοσυναι]{.greek-added} σου εμνησθησαν ενωπιον του [θεου]{.greek-abbr}[10:31]{.aside}

πεμψον ουν εις ιοππην και μετακαλεσαι σιμωνα ος επικαλειται πετρος ουτος ξενιζεται εν οικια σιμωνος βυρσεως παρα θαλασσαν ος παραγενομενος λαλησει σοι[10:32]{.aside}

εξαυτης ουν επεμψα προς σε συ τε καλως εποιησας παραγενομενος νυν ουν παντες ημεις ενωπιον του [θεου]{.greek-abbr} παρεσμεν ακουσαι παντα τα προστεταγμενα σοι υπο του [θεου]{.greek-abbr}[10:33]{.aside}

ανοιξας δε πετρος το στομα ειπεν επ αληθειας καταλαμβανομαι οτι ουκ εστιν προσωποληπτης ο [θεος]{.greek-abbr}[10:34]{.aside}

αλλ εν παντι [εθνει]{.greek-omitted} [εθνη]{.greek-added} ο φοβουμενος αυτον και εργαζομενος δικαιοσυνην δεκτος αυτω εστιν[10:35]{.aside}

τον λογον ον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τοις υιοις [ισραηλ]{.greek-abbr} ευαγγελιζομενος ειρηνην δια [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ουτος [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων [κυριος]{.greek-abbr}[10:36]{.aside}

υμεις οιδατε το γενομενον ρημα καθ ολης της ιουδαιας αρξαμενον απο της γαλιλαιας μετα το βαπτισμα ο [ε]{.greek-added} [εκηρυξεν]{.greek-omitted} [κηρυξεν]{.greek-added} ιωαννης[10:37]{.aside}

[ιησουν]{.greek-abbr} τον απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} ως εχρισεν αυτον ο [θεος]{.greek-abbr} [πνευματι]{.greek-abbr} αγιω και δυναμει ος διηλθεν ευεργετων και ιωμενος παντας τους καταδυναστευομενους υπο του διαβολου οτι ο [θεος]{.greek-abbr} ην μετ αυτου[10:38]{.aside}

και ημεις εσμεν μαρτυρες παντων ων εποιησεν εν τε τη χωρα των ιουδαιων και εν [ιερουσαλημ]{.greek-abbr} ον και ανειλον κρεμασαντες επι ξυλου[10:39]{.aside}

τουτον ο [θεος]{.greek-abbr} ηγειρεν τη τριτη ημερα και εδωκεν αυτον εμφανη γενεσθαι[10:40]{.aside}

ου παντι τω λαω αλλα [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} τοις προκεχειροτονημενοις υπο του [θεου]{.greek-abbr} ημιν οιτινες συνεφαγομεν και συνεπιομεν αυτω μετα το αναστηναι αυτον εκ νεκρων[10:41]{.aside}

και παρηγγειλεν ημιν κηρυξαι τω λαω και διαμαρτυρασθαι οτι αυτος εστιν ο ωρισμενος υπο του [θεου]{.greek-abbr} κριτης ζωντων και νεκρων[10:42]{.aside}

τουτω παντες οι προφηται μαρτυρουσιν αφεσιν αμαρτιων λαβειν δια του ονοματος αυτου παντα τον πιστευοντα εις αυτον[10:43]{.aside}

ετι λαλουντος του πετρου τα ρηματα ταυτα επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επι παντας τους ακουοντας τον λογον[10:44]{.aside}

και εξεστησαν οι εκ περιτομης πιστοι οσοι συνηλθον τω πετρω οτι και επι τα εθνη η δωρεα του αγιου [πνευματος]{.greek-abbr} εκκεχυται[10:45]{.aside}

ηκουον γαρ αυτων λαλουντων γλωσσαις και μεγαλυνοντων τον [θεον]{.greek-abbr} τοτε απεκριθη ο πετρος[10:46]{.aside}

μητι το υδωρ κωλυσαι δυναται τις του μη βαπτισθηναι τουτους οιτινες το [πνευμα]{.greek-abbr} το αγιον ελαβον καθως και ημεις[10:47]{.aside}

προσεταξεν τε αυτους βαπτισθηναι εν τω ονοματι του [κυριου]{.greek-abbr} τοτε ηρωτησαν αυτον επι[μ]{.unclear}ειναι ημερας τινας[10:48]{.aside}

### Chapter 11

ηκουσαν δε οι αποστολοι και οι αδελφοι οι οντες κατα την ιουδαιαν οτι και τα εθνη εδεξαντο τον λογον του [θεου]{.greek-abbr}[11:1]{.aside}

και οτε ανεβη πετρος εις ιεροσολυμα διεκρινοντο προς αυτον οι εκ περιτομης[11:2]{.aside}

λεγοντες οτι προς ανδρας ακροβυστιαν εχοντας εισηλθες και συνεφαγες αυτοις[11:3]{.aside}

[α]{.unclear}ρξαμενος δε ο πετρος [εξετιθετο]{.greek-omitted} [εξετιηθετο]{.greek-added} αυτοις καθεξης λεγων[11:4]{.aside}

εγω [ημην]{.greek-omitted} [ημιν]{.greek-added} εν πολει ιοππη προσευχομενος και ειδον εν εκστασει οραμα καταβαινον σκευος τι ως οθονην μεγαλην τεσσαρσιν αρχαις καθιεμενην εκ του [ουρανου]{.greek-abbr} και ηλθεν [αχρι]{.greek-omitted} [αχρις]{.greek-added} εμου[11:5]{.aside}

εις ην ατενισας κατενοουν και ειδον τα τετραποδα [της]{.greek-omitted} [γης]{.greek-omitted} και τα θηρια και τα ερπετα και τα πετεινα του [ουρανου]{.greek-abbr}[11:6]{.aside}

ηκουσα δε φωνης λεγουσης μοι αναστας πετρε θυσον και φαγε[11:7]{.aside}

ειπον δε μηδαμως [κυριε]{.greek-abbr} οτι παν κοινον η ακαθαρτον ουδεποτε εισηλθεν εις το στομα μου[11:8]{.aside}

απεκριθη δε μοι φωνη εκ δευτερου εκ του [ουρανου]{.greek-abbr} α ο [θεος]{.greek-abbr} εκαθαρισεν συ μη κοινου[11:9]{.aside}

τουτο δε εγενετο επι τρις και παλιν ανεσπασθη απαντα εις τον ουρανον[11:10]{.aside}

και ιδου εξαυτης τρεις ανδρες επεστησαν επι την οικιαν εν η ημην απεσταλμενοι απο καισαρειας προς με[11:11]{.aside}

ειπεν δε μοι το [πνευμα]{.greek-abbr} συνελθειν αυτοις μηδεν διακρινομενον ηλθον δε συν εμοι και οι εξ αδελφοι ουτοι και εισηλθομεν εις τον οικον του ανδρος[11:12]{.aside}

απηγγειλεν τε ημιν πως ειδεν τον αγγελον εν τω οικω αυτου σταθεντα και ειποντα αυτω αποστειλον εις ιοππην ανδρας και μεταπεμψαι σιμωνα τον επικαλουμενον πετρον[11:13]{.aside}

ος λαλησει ρηματα προς σε εν οις σωθηση συ και πας ο οικος σου[11:14]{.aside}

εν δε τω αρξασθαι με λαλειν επεπεσεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ωσπερ και εφ ημας εν αρχη[11:15]{.aside}

εμνησθην δε του ρηματος [του]{.greek-added} [κυριου]{.greek-abbr} ως ελεγεν ιωαννης μεν εβαπτισεν υδατι υμεις δε [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} εν [πνευματι]{.greek-abbr} αγιω[11:16]{.aside}

ει ουν την ισην δωρεαν εδωκεν αυτοις ο [θεος]{.greek-abbr} ως και ημιν πιστευσασιν επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} εγω δε τις ημην δυνατος κωλυσαι τον [θεον]{.greek-abbr}[11:17]{.aside}

ακουσαντες δε ταυτα ησυχασαν και εδοξαζον τον [θεον]{.greek-abbr} λεγοντες αρα γε και τοις εθνεσιν ο [θεος]{.greek-abbr} την μετανοιαν εδωκεν εις ζωην[11:18]{.aside}

οι μεν ουν διασπαρεντες [απο]{.greek-omitted} [[επι]{.corr}]{.greek-added} [τ[ης]{.unclear}]{.corr} θλιψεως της γενομενης επι στεφανω διηλθον εως [φοινικοις]{.greek-added} [φοινικης]{.corr} και κυπρου και αντιοχειας μηδενι λαλουντες τον λογον ει μη μονον ιουδαιοις[11:19]{.aside}

ησαν δε τινες εξ αυτων ανδρες κυπριοι και [κυρηναιοι]{.greek-omitted} [κυριναιοι]{.greek-added} οιτινες εισελθοντες εις αντιοχειαν ελαλουν προς τους ελληνιστας ευαγγελιζομενοι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr}[11:20]{.aside}

και ην χειρ [κυριου]{.greek-abbr} μετ αυτων πολυς τε αριθμος πιστευσας [επεστρεψεν]{.greek-omitted} [υπεστρεψεν]{.greek-added} επι τον [κυριον]{.greek-abbr}[11:21]{.aside}

ηκουσθη δε ο λογος εις τα ωτα της εκκλησιας της [εν]{.greek-omitted} ιεροσολυμοις περι αυτων και εξαπεστειλαν βαρναβαν διελθειν εως αντιοχειας[11:22]{.aside}

ος παραγενομενος και ιδων την χαριν του [θεου]{.greek-abbr} εχαρη και παρεκαλει παντας τη προθεσει της καρδιας προσμενειν τω [κυριω]{.greek-abbr}[11:23]{.aside}

οτι ην ανηρ αγαθος και πληρης [πνευματος]{.greek-abbr} αγιου και πιστεως και προσετεθη οχλος ικανος τω [κυριω]{.greek-abbr}[11:24]{.aside}

εξηλθεν δε εις ταρσον ο βαρναβας αναζητησαι σαυλον[11:25]{.aside}

και ευρων [αυτον]{.greek-added} ηγαγεν αυτον εις αντιοχειαν εγενετο δε αυτους ενιαυτον ολον συναχθηναι τη εκκλησια και διδαξαι οχλον ικανον χρηματισαι τε πρωτον εν αντιοχεια τους μαθητας χριστιανους[11:26]{.aside}

εν ταυταις δε ταις ημεραις κατηλθον απο ιεροσολυμων προφηται εις αντιοχειαν[11:27]{.aside}

αναστας δε εις εξ αυτων ονοματι αγαβος εσημανεν δια του [πνευματος]{.greek-abbr} λιμον μεγαν [μελειν]{.greek-added} [μελλειν]{.corr} εσεσθαι εφ ολην την οικουμενην οστις και εγενετο [επη]{.greek-added} [επι]{.corr} κλαυδιου καισαρος[11:28]{.aside}

των δε μαθητων καθως ευπορειτο τις ωρισαν εκαστος αυτων εις διακονιαν πεμψαι τοις κατοικουσιν εν τη ιουδαια αδελφοις[11:29]{.aside}

ο και εποιησαν αποστειλαντες προς τους πρεσβυτερους δια χειρος βαρναβα και σαυλου[11:30]{.aside}

### Chapter 12

κατ εκεινον δε τον καιρον επεβαλεν ηρωδης ο βασιλευς τας χειρας κακωσαι [τινας]{.greek-omitted} [τινα]{.greek-added} των απο της εκκλησιας[12:1]{.aside}

ανειλεν δε ιακωβον τον αδελφον ιωαννου μαχαιρα[12:2]{.aside}

και ιδων οτι αρεστον [εστιν]{.greek-omitted} [εστι]{.greek-added} τοις ιουδαιοις προσεθετο συλλαβειν και πετρον ησαν δε [αι]{.greek-omitted} ημεραι των αζυμων[12:3]{.aside}

ον και πιασας εθετο εις φυλακην παραδους [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} τετραδιοις στρατιωτων φυλασσειν αυτον βουλομενος μετα το πασχα αναγαγειν αυτον τω λαω[12:4]{.aside}

ο μεν ουν πετρος ετηρειτο εν τη φυλακη προσευχη δε ην εκτενης γινομενη υπο της εκκλησιας προς τον [θεον]{.greek-abbr} υπερ αυτου[12:5]{.aside}

οτε δε εμελλεν αυτον προαγειν ο ηρωδης τη νυκτι εκεινη ην ο πετρος κοιμωμενος μεταξυ δυο στρατιωτων δεδεμενος [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δυσιν φυλακες τε προ της θυρας ετηρουν την φυλακην[12:6]{.aside}

και ιδου αγγελος [κυριου]{.greek-abbr} επεστη και φως ελαμψεν εν τω οικηματι παταξας δε την πλευραν του πετρου ηγειρεν αυτον λεγων αναστα εν ταχει και εξεπεσον αυτου αι αλυσεις εκ των χειρων[12:7]{.aside}

ειπεν τε ο αγγελος προς αυτον περιζωσαι και υποδησαι τα σανδαλια σου εποιησεν δε ουτως και λεγει αυτω περιβαλου το ιματιον σου και ακολουθει μοι[12:8]{.aside}

και εξελθων [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και ουκ ηδει οτι αληθες [εστιν]{.greek-omitted} [εστι]{.greek-added} το γινομενον [δια]{.greek-omitted} [υπο]{.greek-added} του αγγελου εδοκει δε οραμα βλεπειν[12:9]{.aside}

διελθοντες δε πρωτην φυλακην και δευτεραν ηλθον επι την πυλην την σιδηραν την φερουσαν εις την πολιν ητις αυτοματη ηνοιχθη αυτοις και εξελθοντες [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} ρυμην μιαν και ευθεως απεστη ο αγγελος απ αυτου[12:10]{.aside}

και ο πετρος γενομενος εν εαυτω ειπεν νυν οιδα αληθως οτι εξαπεστειλεν [κυριος]{.greek-abbr} τον αγγελον αυτου και εξειλετο με εκ χειρος ηρωδου και πασης της προσδοκιας του λαου των ιουδαιων[12:11]{.aside}

συνιδων τε ηλθεν επι την οικιαν μαριας της [μητρος]{.greek-abbr} ιωαννου του επικαλουμενου μαρκου ου ησαν ικανοι συνηθροισμενοι και προσευχομενοι[12:12]{.aside}

κρουσαντος δε του πετρου την θυραν του πυλωνος προσηλθεν παιδισκη υπακουσαι ονοματι [ροδη]{.greek-omitted} [ρωδη]{.greek-added}[12:13]{.aside}

και επιγνουσα την φωνην του πετρου απο της χαρας ουκ ηνοιξεν τον πυλωνα εισδραμουσα δε απηγγειλεν εσταναι τον πετρον προ του πυλωνος[12:14]{.aside}

οι δε προς αυτην ειπον μαινη η δε διισχυριζετο ουτως εχειν οι δε ελεγον ο αγγελος αυτου εστιν[12:15]{.aside}

ο δε πετρος επεμενεν κρουων ανοιξαντες δε ειδον αυτον και εξεστησαν[12:16]{.aside}

κατασεισας δε αυτοις τη χειρι σιγαν διηγησατο αυτοις πως ο [κυριος]{.greek-abbr} αυτον εξηγαγεν εκ της φυλακης ειπεν δε απαγγειλατε ιακωβω και τοις αδελφοις ταυτα και εξελθων επορευθη εις ετερον τοπον[12:17]{.aside}

γενομενης δε ημερας ην ταραχος ουκ ολιγος εν τοις στρατιωταις τι αρα ο πετρος εγενετο[12:18]{.aside}

ηρωδης δε επιζητησας αυτον και μη ευρων ανακρινας τους φυλακας εκελευσεν απαχθηναι και κατελθων απο της ιουδαιας εις την καισαρειαν διετριβεν[12:19]{.aside}

ην δε ο ηρωδης θυμομαχων τυριοις και [σιδωνιοις]{.greek-omitted} [σιδονιοις]{.greek-added} ομοθυμαδον δε παρησαν προς αυτον και πεισαντες βλαστον τον επι του κοιτωνος του βασιλεως ητουντο ειρηνην δια το τρεφεσθαι αυτων την χωραν απο της [βασιλικης]{.greek-omitted} [βασιλεικης]{.greek-added}[12:20]{.aside}

τακτη δε ημερα ο ηρωδης ενδυσαμενος εσθητα βασιλικην και [καθισας]{.greek-omitted} [καθησας]{.greek-added} επι του βηματος [εδημηγορει]{.greek-omitted} [εδημιγορει]{.greek-added} προς αυτους[12:21]{.aside}

ο δε δημος [επεφωνει]{.greek-omitted} [επεφωνη]{.greek-added} φωνη [θεου]{.greek-abbr} και ουκ ανθρωπου[12:22]{.aside}

παραχρημα δε επαταξεν αυτον αγγελος [κυριου]{.greek-abbr} ανθ ων ουκ εδωκεν δοξαν τω [θεω]{.greek-abbr} και γενομενος σκωληκοβρωτος εξεψυξεν[12:23]{.aside}

ο δε λογος του [θεου]{.greek-abbr} ηυξανεν και [ε]{.greek-added} [επληθυνετο]{.greek-omitted} [πληθυνετο]{.greek-added}[12:24]{.aside}

βαρναβας δε και σαυλος [υπεστρεψον]{.greek-added} [υπεστρεψαν]{.corr} εις [ιερουσαλημ]{.greek-abbr} πληρωσαντες την διακονιαν συμπαραλαβοντες και ιωαννην τον επικληθεντα μαρκον[12:25]{.aside}

### Chapter 13

ησαν δε τινες εν αντιοχεια κατα την ουσαν εκκλησιαν προφηται και διδασκαλοι ο τε βαρναβας και συμεων ο καλουμενος νιγερ και λουκιος ο [κυρηναιος]{.greek-omitted} [κυριναιος]{.greek-added} μαναην τε ηρωδου του [τετραρχου]{.greek-omitted} [τεταρχου]{.greek-added} συντροφος και σαυλος[13:1]{.aside}

λειτουργουντων δε αυτων τω [κυριω]{.greek-abbr} και νηστευοντων ειπεν το [πνευμα]{.greek-abbr} το αγιον αφορισατε δη μοι τον [τε]{.greek-added} βαρναβαν και [τον]{.greek-omitted} σαυλον εις το εργον ο προσκεκλημαι αυτους[13:2]{.aside}

τοτε νηστευσαντες και προσευξαμενοι και επιθεντες τας χειρας αυτοις απελυσαν[13:3]{.aside}

ουτοι μεν ουν εκπεμφθεντες υπο του [πνευματος]{.greek-abbr} του αγιου κατηλθον εις την σελευκειαν εκειθεν δε απεπλευσαν εις την κυπρον[13:4]{.aside}

και γενομενοι εν σαλαμινι [κατηγγελλον]{.greek-omitted} [κατηγγελον]{.greek-added} τον λογον του [θεου]{.greek-abbr} εν ταις συναγωγαις των ιουδαιων ειχον δε και ιωαννην υπηρετην[13:5]{.aside}

διελθοντες δε την νησον αχρι παφου ευρον τινα μαγον ψευδοπροφητην ιουδαιον ω ονομα [βαριησους]{.greek-omitted} [βαριησουν]{.greek-added}[13:6]{.aside}

ος ην συν τω ανθυπατω σεργιω παυλω ανδρι συνετω ουτος προσκαλεσαμενος βαρναβαν και σαυλον επεζητησεν ακουσαι τον λογον του [θεου]{.greek-abbr}[13:7]{.aside}

ανθιστατο δε αυτοις ελυμας ο μαγος [ουτως]{.greek-omitted} [ουτος]{.greek-added} γαρ μεθερμηνευεται το ονομα αυτου ζητων διαστρεψαι τον ανθυπατον απο της πιστεως[13:8]{.aside}

σαυλος δε ο και [[κ]{.greek-supplied}[α]{.unclear}λουμενος]{.greek-added} παυλος πλησθεις [πνευματος]{.greek-abbr} αγιου [και]{.greek-omitted} ατενισας εις αυτον[13:9]{.aside}

ειπεν ω πληρης παντος δολου και πασης ραδιουργιας υιε διαβολου εχθρε πασης δικαιοσυνης ου [παυση]{.greek-omitted} [παυσει]{.greek-added} διαστρεφων τας οδους [κυριου]{.greek-abbr} τας ευθειας[13:10]{.aside}

και νυν ιδου χειρ [κυριου]{.greek-abbr} επι σε και εση τυφλος μη βλεπων τον ηλιον αχρι καιρου παραχρημα δε επεπεσεν επ αυτον αχλυς και σκοτος και περιαγων εζητει χειραγωγους[13:11]{.aside}

τοτε ιδων ο ανθυπατος το γεγονος επιστευσεν εκπλησσομενος επι τη διδαχη του [κυριου]{.greek-abbr}[13:12]{.aside}

[αναχθεντες]{.greek-added} [δε]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [παφου]{.greek-added} [οι]{.greek-added} [περι]{.greek-added} [τον]{.greek-added} [παυλον]{.greek-added} [ηλθεν]{.greek-added} [εις]{.greek-added} [περγην]{.greek-added} [της]{.greek-added} [παμφυλιας]{.greek-added} [ιωαννης]{.greek-added} [δε]{.greek-added} [αποχωρησας]{.greek-added} [απ]{.greek-added} [αυτων]{.greek-added} [απεστρεψων]{.greek-added} [εις]{.greek-added} [εωροσολυμα]{.greek-added} [αναθεντες]{.greek-added} [αναχθεντες]{.corr} δε απο της παφου οι περι τον παυλον ηλθον [[ηλθεν]{.corr}]{.greek-added} [εις]{.greek-omitted} [περγην]{.greek-omitted} [της]{.greek-omitted} [παμφυλιας]{.greek-omitted} [ιωαννης]{.greek-omitted} [δε]{.greek-omitted} [αποχωρησας]{.greek-omitted} [απ]{.greek-omitted} [αυτων]{.greek-omitted} [υπεστρεψεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted}[13:13]{.aside}

αυτοι δε διελθο[ν]{.unclear}τ[ε]{.unclear}ς απο της περγης παρεγενοντο εις αντιοχειαν της πισιδιας και εισελθοντες εις την συναγωγην τη ημερα των σαββατων εκαθισαν[13:14]{.aside}

μετα δε την αναγνωσιν του νομου και των προφητων απεστειλαν οι αρχισυναγωγοι προς αυτους λεγοντες ανδρες αδελφοι ει εστιν [λογος]{.greek-omitted} εν υμιν [λογος]{.greek-added} παρακλησεως προς τον λαον λεγετε[13:15]{.aside}

αναστας δε παυλος και κατασεισας τη χειρι ειπεν ανδρες ισραηλιται και οι φοβουμενοι τον [θεον]{.greek-abbr} ακουσατε[13:16]{.aside}

ο [θεος]{.greek-abbr} του λαου τουτου εξελεξατο τους [πατερας]{.greek-abbr} ημων και τον λαον υψωσεν εν τη παροικια εν γη αιγυπτω και μετα βραχιονος υψηλου εξηγαγεν αυτους εξ αυτης[13:17]{.aside}

και ως τεσσαρακονταετη χρονον ετροποφορησεν αυτους εν τη ερημω[13:18]{.aside}

και καθελων εθνη επτα εν γη χανααν κατεκληρονομησεν αυτοις την γην αυτων[13:19]{.aside}

και μετα ταυτα ως [ετεσιν]{.greek-omitted} [ετεσι]{.greek-added} τετρακοσιοις και πεντηκοντα εδωκεν κριτας εως σαμουηλ του προφητου[13:20]{.aside}

κακειθεν ητησαντο βασιλεα και εδωκεν αυτοις ο [θεος]{.greek-abbr} τον σαουλ [υιον]{.greek-abbr} κις ανδρα εκ φυλης βενιαμιν ετη τεσσαρακοντα[13:21]{.aside}

και μεταστησας αυτον ηγειρεν αυτοις τον [δαυιδ]{.greek-abbr} εις βασιλεα ω και ειπεν μαρτυρησας ευρον [δαυιδ]{.greek-abbr} τον του ιεσσαι ανδρα κατα την καρδιαν μου ος ποιησει παντα τα θεληματα μου[13:22]{.aside}

τουτου ο [θεος]{.greek-abbr} απο του σπερματος κατ επαγγελιαν ηγαγεν τω [ισραηλ]{.greek-abbr} σωτηριαν[13:23]{.aside}

προκηρυξαντος ιωαννου προ προσωπου της εισοδου αυτου βαπτισμα μετανοιας τω [ισραηλ]{.greek-abbr}[13:24]{.aside}

ως δε επληρου ο ιωαννης τον δρομον ελεγεν τινα με [ειπον]{.greek-added} [υπονοειτε]{.greek-omitted} [νοειτε]{.greek-added} ειναι ουκ ειμι εγω αλλ ιδου ερχεται μετ εμε ου ουκ ειμι αξιος το υποδημα των ποδων λυσαι[13:25]{.aside}

ανδρες αδελφοι υιοι γενους αβρααμ και οι εν υμιν φοβουμενοι τον [θεον]{.greek-abbr} υμιν ο λογος της [σωτηριας]{.greek-abbr} ταυτης απεσταλη[13:26]{.aside}

οι γαρ κατοικουντες εν [ιερουσαλημ]{.greek-abbr} και οι αρχοντες αυτων τουτον [αγνοησαντες]{.greek-omitted} [αγνωησαντες]{.greek-added} και τας φωνας των προφητων τας κατα παν [σαβατον]{.greek-added} [σαββατον]{.corr} [αναγινωσκομενας]{.greek-omitted} [αναγινοσκομενας]{.greek-added} κριναντες επληρωσαν[13:27]{.aside}

και μηδεμιαν αιτιαν θανατου ευροντες ητησαντο πιλατον αναιρεθηναι αυτον[13:28]{.aside}

ως δε ετελεσαν παντα τα περι αυτου γεγραμμενα [και]{.greek-added} [θελοντες]{.greek-added} [καθελοντες]{.corr} απο του ξυλου εθηκαν εις μνημειον[13:29]{.aside}

ο δε [θεος]{.greek-abbr} ηγειρεν αυτον εκ νεκρων[13:30]{.aside}

ος ωφθη επι ημερας πλειους τοις συναναβασιν αυτω απο της γαλιλαιας εις [ιερουσαλημ]{.greek-abbr} οιτινες [εισιν]{.greek-omitted} [εισι]{.greek-added} μαρτυρες αυτου προς τον λαον[13:31]{.aside}

και ημεις υμας ευαγγελιζομεθα την προς τους [πατερας]{.greek-abbr} επαγγελιαν [γενομενην]{.greek-omitted} [γινομενην]{.greek-added} [οτι]{.greek-omitted} [ταυτην]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [εκπεπληρωκεν]{.greek-omitted} [τοις]{.greek-omitted} [τεκνοις]{.greek-omitted} [αυτων]{.greek-omitted} [ημιν]{.greek-omitted} [αναστησας]{.greek-omitted} [ιησουν]{.greek-omitted}[13:32]{.aside}

[οτι]{.greek-added} [ταυτην]{.greek-added} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκπεπληρωκεν]{.greek-added} [τοις]{.greek-added} [τεκνοις]{.greek-added} [αυτων]{.greek-added} [ημιν]{.greek-added} [αναστησας]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} ως και εν τω ψαλμω τω δευτερω γεγραπται [υιος]{.greek-abbr} μου ει συ εγω σημερον γεγεννηκα σε[13:33]{.aside}

οτι δε ανεστησεν αυτον εκ νεκρων μηκετι μελλοντα υποστρεφειν εις διαφθοραν ουτως ειρηκεν οτι δωσω υμιν τα οσια [δαυιδ]{.greek-abbr} τα πιστα[13:34]{.aside}

διο και εν ετερω λεγει ου δωσεις τον οσιον σου ιδειν διαφθοραν[13:35]{.aside}

[δαυιδ]{.greek-abbr} μεν γαρ ιδια γενεα υπηρετησας τη του [θεου]{.greek-abbr} βουλη εκοιμηθη και προσετεθη προς τους [πατερας]{.greek-abbr} αυτου και ειδεν διαφθοραν[13:36]{.aside}

ον δε ο [θεος]{.greek-abbr} ηγειρεν ουκ ειδεν διαφθοραν[13:37]{.aside}

γνωστον ουν εστω υμιν ανδρες αδελφοι οτι δια [τουτου]{.greek-omitted} [τουτο]{.greek-added} υμιν [αφεσις]{.greek-omitted} [αφεσιν]{.greek-added} αμαρτιων καταγγελλεται [και]{.greek-added} [απο]{.greek-added} [παντων]{.greek-added} [ων]{.greek-added} [ουκ]{.greek-added} [ηδυνηθητε]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [νομω]{.greek-added} [μωυσεως]{.greek-added} [δικαιωθηναι]{.greek-added}[13:38]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [ουκ]{.greek-omitted} [ηδυνηθητε]{.greek-omitted} εν [τω]{.greek-omitted} [νομω]{.greek-omitted} [μωυσεως]{.greek-omitted} [δικαιωθηναι]{.greek-omitted} [εν]{.greek-omitted} [τουτω]{.greek-omitted} [τουτο]{.greek-added} πας ο πιστευων δικαιουται[13:39]{.aside}

βλεπετε ουν μη επελθη εφ υμας το ειρημενον εν τοις προφηταις[13:40]{.aside}

ιδετε οι καταφρονηται και θαυμασατε και αφανισθητε οτι εργον εγω εργαζομαι εν ταις ημεραις υμων ο ου μη πιστευσητε εαν τις εκδιηγηται υμιν[13:41]{.aside}

εξιοντων δε [αυτων]{.greek-added} εκ της συναγωγης των ιουδαιων παρεκαλουν τα εθνη εις το μεταξυ σαββατον λαληθηναι αυτοις τα ρηματα[13:42]{.aside}

λυθεισης δε της συναγωγης ηκολουθησαν πολλοι των ιουδαιων και των σεβομενων προσηλυτων τω παυλω και τω βαρναβα οιτινες προσλαλουντες επειθον αυτους επιμενειν τη χαριτι του [θεου]{.greek-abbr}[13:43]{.aside}

τω τε ερχομενω σαββατω σχεδον πασα η πολις συνηχθη ακουσαι τον λογον του [θεου]{.greek-abbr}[13:44]{.aside}

ιδοντες δε οι ιουδαιοι τους οχλους επλησθησαν ζηλου και αντελεγον τοις υπο του παυλο[υ]{.unclear} λεγομενοις [και]{.greek-added} αντιλεγοντες και βλασφημουντες[13:45]{.aside}

παρρησιασαμενοι δε ο παυλος και [ο]{.greek-omitted} βαρναβας ειπον υμιν ην αναγκαιον πρωτον λαληθηναι τον λογον του [θεου]{.greek-abbr} επειδη δε απωθεισθε αυτον και ουκ αξιους κρινετε εαυτους της αιωνιου ζωης ιδου στρεφομεθα εις τα εθνη[13:46]{.aside}

ουτως γαρ [εντεταλται]{.greek-omitted} ημιν [εντεταλτο]{.greek-added} ο [κυριος]{.greek-abbr} [τεθεικα]{.greek-omitted} [τεθηκα]{.greek-added} σε εις φως εθνων του ειναι σε εις [σωτηριαν]{.greek-abbr} εως εσχατου της γης[13:47]{.aside}

ακουοντα δε τα εθνη [εχαιρεν]{.greek-omitted} [εχαιρον]{.greek-added} και εδοξαζον τον λογον του [κυριου]{.greek-abbr} και επιστευσαν οσοι ησαν τεταγμενοι εις ζωην αιωνιον[13:48]{.aside}

διεφερετο δε ο λογος του [κυριου]{.greek-abbr} δι ολης της χωρας[13:49]{.aside}

οι δε ιουδαιοι παρωτρυναν τας σεβομενας γυναικας και τας ευσχημονας και τους πρωτους της πολεως και επηγειραν διωγμον επι τον παυλον και τον βαρναβαν και εξεβαλον αυτους απο των οριων αυτων[13:50]{.aside}

οι δε εκτιναξαμενοι τον κονιορτον των ποδων αυτων επ αυτους ηλθον εις ικονιον[13:51]{.aside}

οι δε μαθηται επληρουντο χαρας και [πνευματος]{.greek-abbr} αγιου[13:52]{.aside}

### Chapter 14

εγενετο δε εν ικονιω κατα το αυτο εισελθειν αυτους εις την συναγωγην των ιουδαιων και λαλησαι ουτως ωστε πιστευσαι ιουδαιων τε και ελληνων πολυ πληθος[14:1]{.aside}

οι δε απειθουντες ιουδαιοι επηγειραν και εκακωσαν τας ψυχας των εθνων κατα των αδελφων[14:2]{.aside}

ικανον μεν ουν χρονον διετριψαν παρρησιαζομενοι επι τω [κυριω]{.greek-abbr} τω μαρτυρουντι τω λογω της χαριτος αυτου [και]{.greek-added} διδοντι σημεια και τερατα γινεσθαι δια των χειρων αυτων[14:3]{.aside}

εσχισθη δε το πληθος της πολεως και οι μεν ησαν συν τοις ιουδαιοις οι δε συν τοις αποστολοις[14:4]{.aside}

ως δε εγενετο ορμη των εθνων τε και ιουδαιων συν τοις αρχουσιν αυτων υβρισαι και λιθοβολησαι αυτους[14:5]{.aside}

συνιδοντες κατεφυγον εις τας πολεις της λυκαονιας λυστραν και δερβην και την περιχωρον[14:6]{.aside}

κακει ησαν ευαγγελιζομενοι[14:7]{.aside}

και τις ανηρ εν λυστροις αδυνατος τοις ποσιν εκαθητο χωλος εκ κοιλιας [μητρος]{.greek-abbr} αυτου υπαρχων ος ουδεποτε [περιπεπατηκει]{.greek-omitted} [περιπατηκει]{.greek-added}[14:8]{.aside}

ουτος ηκουσεν του παυλου λαλουντος ος ατενισας αυτω και ιδων οτι πιστιν εχει του σωθηναι[14:9]{.aside}

ειπεν μεγαλη τη φωνη αναστηθι επι τους ποδας σου ορθως και [ηλλετο]{.greek-omitted} [ηλετο]{.greek-added} και περιεπατει[14:10]{.aside}

οι δε οχλοι ιδοντες ο εποιησεν ο παυλος επηραν [αυτων]{.greek-added} την φωνην [αυτων]{.greek-omitted} λυκαονιστι λεγοντες οι θεοι ομοιωθεντες [ανθρωποις]{.greek-abbr} κατεβησαν προς ημας[14:11]{.aside}

εκαλουν τε τον μεν βαρναβαν δια τον δε παυλον ερμην επειδ[η]{.unclear} αυτος ην ο ηγουμενος του λογου[14:12]{.aside}

ο δε ιερευς του διος του οντος προ της πολεως αυτων ταυρους και στεμματα επι τους πυλωνας ενεγκας συν τοις οχλοις [ηθελεν]{.greek-omitted} [ηθελον]{.greek-added} θυειν[14:13]{.aside}

ακουσαντες δε οι αποστολοι βαρναβας και παυλος διαρρηξαντες τα ιματια αυτων [εισεπηδησαν]{.greek-omitted} [εισεπιδησαν]{.greek-added} εις τον οχλον κραζοντες[14:14]{.aside}

και λεγοντες ανδρες τι ταυτα ποιειτε και ημεις ομοιοπαθεις εσμεν υμιν [ανθρωποι]{.greek-abbr} ευαγγελιζομενοι υμας απο τουτων των ματαιων επιστρεφειν επι τον [θεον]{.greek-abbr} τον ζωντα ος [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και παντα τα εν αυτοις[14:15]{.aside}

ος εν ταις παρωχημεναις γενεαις ειασεν παντα τα εθνη πορευεσθαι ταις οδοις αυτων[14:16]{.aside}

καιτοιγε ουκ αμαρτυρον εαυτον αφηκεν αγαθοποιων [ουρανοθεν]{.greek-abbr} υμιν υετους διδους και καιρους καρποφορους εμπιπλων τροφης και ευφροσυνης τας καρδιας ημων[14:17]{.aside}

και ταυτα λεγοντες μολις κατεπαυσαν τους οχλους του μη θυειν αυτοις[14:18]{.aside}

επηλθον δε απο αντιοχειας και ικονιου ιουδαιοι και πεισαντες τους οχλους και λιθασαντες τον παυλον εσυρον εξω της πολεως νομισαντες αυτον τεθναναι[14:19]{.aside}

[κυκλωσαντων]{.greek-omitted} [κυκλωσαντες]{.greek-added} δε αυτον των μαθητων αναστας εισηλθεν εις την πολιν και τη επαυριον εξηλθεν συν τω βαρναβα εις δερβην[14:20]{.aside}

ευαγγελισαμενοι τε την πολιν εκεινην και μαθητευσαντες ικανους υπεστρεψαν εις την λυστραν και ικονιον και αντιοχειαν[14:21]{.aside}

επιστηριζοντες τας ψυχας των μαθητων παρακαλουντες εμμενειν τη πιστει και οτι δια πολλων θλιψεων δει ημας εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr}[14:22]{.aside}

χειροτονησαντες δε αυτοις πρεσβυτερους κατ εκκλησιαν προσευξαμενοι μετα νηστειων παρεθεντο αυτους τω [κυριω]{.greek-abbr} εις ον πεπιστευκεισαν[14:23]{.aside}

και διελθοντες την πισιδιαν ηλθον εις παμφυλιαν[14:24]{.aside}

και λαλησαντες εν περγη τον λογον κατεβησαν εις [ατταλειαν]{.greek-omitted} [αταλιαν]{.greek-added}[14:25]{.aside}

κακειθεν απεπλευσαν εις αντιοχειαν οθεν ησαν παραδεδομενοι τη χαριτι του [θεου]{.greek-abbr} εις το εργον ο επληρωσαν[14:26]{.aside}

παραγενομενοι δε και συναγαγοντες την εκκλησιαν ανηγγειλαν οσα εποιησεν ο [θεος]{.greek-abbr} μετ αυτων και οτι ηνοιξεν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} θυραν πιστεως[14:27]{.aside}

διετριβον δε εκει χρονον ουκ ολιγον συν τοις μαθηταις[14:28]{.aside}

### Chapter 15

και τινες κατελθοντες απο της ιουδαιας εδιδασκον τους αδελφους οτι εαν μη περιτεμνησθε τω εθει μωυσεως ου δυνασθε σωθηναι[15:1]{.aside}

γενομενης ουν στασεως [και]{.greek-omitted} [ζητησεως]{.greek-omitted} ουκ [ολιγης]{.greek-omitted} [ολιγοις]{.greek-added} τω παυλω και τω βαρναβα προς αυτους εταξαν αναβαινειν παυλον και βαρναβαν και τινας αλλους εξ αυτων προς τους αποστολους και πρεσβυτερους εις [ιερουσαλημ]{.greek-abbr} περι του ζητηματος τουτου[15:2]{.aside}

οι μεν ουν προπεμφθεντες υπο της εκκλησιας διηρχοντο την φοινικην και [την]{.greek-added} σαμαρειαν εκδιηγουμενοι την επιστροφην των εθνων και εποιουν χαραν μεγαλην [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις αδελφοις[15:3]{.aside}

παραγενομενοι δε εις [ιερουσαλημ]{.greek-abbr} απεδεχθησαν υπο της εκκλησιας και των αποστολων και των πρεσβυτερων ανηγγειλαν τε οσα ο [θεος]{.greek-abbr} εποιησεν μετ αυτων[15:4]{.aside}

εξανεστησαν δε τινες των απο της αιρεσεως των φαρισαιων πεπιστευκοτες λεγοντες οτι δει περιτεμνειν αυτους παραγγελλειν τε τηρειν τον νομον μωυσεως[15:5]{.aside}

συνηχθησαν δε οι αποστολοι και οι πρεσβυτεροι ιδειν περι του λογου τουτου[15:6]{.aside}

πολλης δε συζητησεως [γενομενης]{.greek-omitted} [γινομενης]{.greek-added} αναστας πετρος ειπεν προς αυτους ανδρες αδελφοι υμεις επιστασθε οτι αφ ημερων αρχαιων ο [θεος]{.greek-abbr} εν ημιν εξελεξατο δια του στοματος μου ακουσαι τα εθνη τον λογον του ευαγγελιου και πιστευσαι[15:7]{.aside}

και ο καρδιογνωστης [θεος]{.greek-abbr} εμαρτυρησεν αυτοις δους αυτοις το [πνευμα]{.greek-abbr} το αγιον καθως και ημιν[15:8]{.aside}

και ουδεν διεκρινεν [εν]{.greek-added} μεταξυ ημων τε και αυτων τη πιστει καθαρισας τας καρδιας αυτων[15:9]{.aside}

νυν ουν τι πειραζετε τον [θεον]{.greek-abbr} επιθειναι ζυγον επι τον τραχηλον των μαθητων ον ουτε οι [πατερες]{.greek-abbr} ημων ουτε ημεις ισχυσαμεν βαστασαι[15:10]{.aside}

αλλα δια της χαριτος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} πιστευομεν σωθηναι καθ ον τροπον κακεινοι[15:11]{.aside}

εσιγησεν δε παν το πληθος και ηκουον βαρναβα και παυλου εξηγουμενων οσα εποιησεν ο [θεος]{.greek-abbr} σημεια και τερατα εν τοις εθνεσιν δι αυτων[15:12]{.aside}

μετα δε το σιγησαι αυτους απεκριθη ιακωβος λεγων ανδρες αδελφοι ακουσατε μου[15:13]{.aside}

συμεων εξηγησατο καθως πρωτον ο [θεος]{.greek-abbr} επεσκεψατο λαβειν εξ εθνων λαον επι τω ονοματι αυτου[15:14]{.aside}

και [τουτω]{.greek-omitted} [τουτο]{.greek-added} συμφωνουσιν οι λογοι των προφητων καθως γεγραπται[15:15]{.aside}

μετα ταυτα αναστρεψω και ανοικοδομησω την σκηνην [δαυιδ]{.greek-abbr} την πεπτωκυιαν και τα κατεσκαμμενα αυτης ανοικοδομησω και ανορθωσω αυτην[15:16]{.aside}

οπως αν εκζητησωσιν οι καταλοιποι των [ανθρωπων]{.greek-abbr} τον [κυριον]{.greek-abbr} και παντα τα εθνη [εφ]{.greek-omitted} [εφφ]{.greek-added} ους [επικεκληται]{.greek-omitted} [επικεκλητε]{.greek-added} το ονομα μου επ αυτους λεγει [κυριος]{.greek-abbr} ο ποιων [παντα]{.greek-added} ταυτα [παντα]{.greek-omitted}[15:17]{.aside}

γνωστα απ αιωνος εστιν τω [θεω]{.greek-abbr} παντα τα εργα αυτου[15:18]{.aside}

διο εγω κρινω μη παρενοχλειν τοις απο των εθνων επιστρεφουσιν επι τον [θεον]{.greek-abbr}[15:19]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} επιστειλαι αυτοις του απεχεσθαι απο των αλισγηματων των ειδωλων και της πορνειας και του πνικτου και του αιματος[15:20]{.aside}

μωυσης γαρ εκ γενεων αρχαιων κατα πολιν τους κηρυσσοντας αυτον [εχει]{.greek-omitted} [εχειν]{.greek-added} εν ταις συναγωγαις κατα παν σαββατον αναγινωσκομενος[15:21]{.aside}

τοτε εδοξεν τοις αποστολοις και τοις πρεσβυτεροις συν ολη τη εκκλησια εκλεξαμενους [ανδρας]{.greek-omitted} [ανδραν]{.greek-added} εξ αυτων πεμψαι εις αντιοχειαν συν παυλω και βαρναβα ιουδαν τον επικαλουμενον [βαρσαββαν]{.greek-omitted} [βαρσαβαν]{.greek-added} και σιλαν ανδρας ηγουμενους εν τοις αδελφοις[15:22]{.aside}

γραψαντες δια χειρος αυτων ταδε οι αποστολοι και οι πρεσβυτεροι και οι αδελφοι τοις κατα την αντιοχειαν και συριαν και κιλικιαν αδελφοις τοις εξ εθνων χαιρειν[15:23]{.aside}

επειδη ηκουσαμεν οτι τινες εξ ημων εξελθοντες εταραξαν υμας λογοις ανασκευαζοντες τας ψυχας υμων λεγοντες περιτεμνεσθαι και τηρειν τον νομον οις ου διεστειλαμεθα[15:24]{.aside}

εδοξεν ημιν γενομενοις ομοθυμαδον εκλεξαμενους ανδρας πεμψαι προς υμας συν τοις αγαπητοις ημων βαρναβα και παυλω[15:25]{.aside}

[ανθρωποις]{.greek-abbr} [παραδεδωκοσιν]{.greek-omitted} [παραδεδωκοσι]{.greek-added} τας ψυχας αυτων υπερ του ονοματος του [κυριου]{.greek-abbr} ημων [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[15:26]{.aside}

απεσταλκαμεν ουν ιουδαν και σιλαν και αυτους δια λογου απαγγελλοντας τα αυτα[15:27]{.aside}

εδοξεν γαρ τω αγιω [πνευματι]{.greek-abbr} και ημιν μηδεν πλεον επιτιθεσθαι υμιν βαρος πλην [τουτων]{.greek-added} των [επαναγκες]{.greek-omitted} [επαγναγκες]{.greek-added} [τουτων]{.greek-omitted}[15:28]{.aside}

[απεχεσθαι]{.greek-omitted} [απεχεσθε]{.greek-added} ειδωλοθυτων και αιματος και πνικτου και πορνειας εξ ων διατηρουντες εαυτους ευ [πραξετε]{.greek-omitted} [πραξατε]{.greek-added} ερρωσθε[15:29]{.aside}

οι μεν ουν απολυθεντες ηλθον εις αντιοχειαν και συναγαγοντες [το]{.greek-omitted} πληθος επεδωκαν την επιστολην[15:30]{.aside}

αναγνοντες δε εχαρησαν επι τη παρακλησει[15:31]{.aside}

ιουδας τε και σιλας και αυτοι προφηται οντες δια λογου πολλου παρεκαλεσαν τους αδελφους και επεστηριξαν[15:32]{.aside}

ποιησαντες δε [χρονον]{.greek-omitted} [χρονους]{.greek-added} απελυθησαν μετ ειρηνης απο των [α]{.greek-added} [αδελφων]{.greek-omitted} [δελφων]{.greek-added} προς τους αποστολους[15:33]{.aside}

παυλος δε και βαρναβας διετριβον εν αντιοχεια διδασκοντες και ευαγγελιζομενοι μετα και ετερων πολλων τον λογον του [κυριου]{.greek-abbr}[15:35]{.aside}

μετα δε τινας ημερας ειπεν παυλος προς βαρναβαν επιστρεψαντες [δη]{.greek-omitted} επισκεψωμεθα τους αδελφους ημων κατα πασαν πολιν εν αις κατηγγειλαμεν τον λογον του [κυριου]{.greek-abbr} πως εχουσιν[15:36]{.aside}

βαρναβας δε εβουλευσατο συμπαραλαβειν τον ιωαννην τον καλουμενον μαρκον[15:37]{.aside}

παυλος δε ηξιου τον αποσταντα απ αυτων απο παμφυλιας και μη συνελθοντα αυτοις εις το εργον μη συμπαραλαβειν τουτον[15:38]{.aside}

εγενετο ουν παροξυσμος ωστε αποχωρισθηναι αυτους απ αλληλων τον [τε]{.greek-omitted} [δε]{.greek-added} βαρναβαν παραλαβοντα τον μαρκον εκπλευσαι εις κυπρον[15:39]{.aside}

παυλος δε επιλεξαμενος σιλαν εξηλθεν παραδοθεις τη χαριτι του [θεου]{.greek-abbr} υπο των αδελφων[15:40]{.aside}

διηρχετο δε την συριαν και κιλικιαν επιστηριζων τας εκκλησιας[15:41]{.aside}

### Chapter 16

κατηντησεν δε εις δερβην και λυστραν και ιδου μαθητης τις ην εκει ονοματι τιμοθεος [υιος]{.greek-abbr} γυναικος τινος ιουδαιας πιστης [πατρος]{.greek-abbr} δε ελληνος[16:1]{.aside}

ος εμαρτυρειτο υπο των εν [λυστροις]{.greek-omitted} [λυτροις]{.greek-added} και ικονιω αδελφων[16:2]{.aside}

τουτον ηθελησεν ο παυλος συν αυτω εξελθειν και λαβων περιετεμεν αυτον δια τους ιουδαιους τους οντας εν τοις τοποις εκεινοις ηδεισαν γαρ απαντες τον [πατερα]{.greek-abbr} αυτου οτι ελλην υπηρχεν[16:3]{.aside}

ως δε διεπορευοντο τας πολεις παρεδιδουν αυτοις φυλασσειν τα δογμ[α]{.unclear}τα τα κεκριμενα υπο των αποστολων και των πρεσβυτερων των εν [ιερουσαλημ]{.greek-abbr}[16:4]{.aside}

αι μεν ουν εκκλησιαι εστερεουντο τη πιστει και επερισσευον τω αριθμω καθ ημεραν[16:5]{.aside}

διελθοντες δε την φρυγιαν και την γαλατικην χωραν κωλυθεντες υπο του αγιου [πνευματος]{.greek-abbr} λαλησαι τον λογον εν τη ασια[16:6]{.aside}

ελθοντες κατα την μυσιαν επειραζον κατα την [βιθυνιαν]{.greek-omitted} [βιθανιαν]{.greek-added} πορευεσθαι και ουκ [ειασαν]{.greek-added} [ειασεν]{.corr} αυτους το [πνευμα]{.greek-abbr}[16:7]{.aside}

παρελθοντες δε την μυσιαν κατεβησαν εις τρωαδα[16:8]{.aside}

και [οραμα]{.greek-omitted} [ωραμα]{.greek-added} δια της νυκτος ωφθη τω παυλω [ανηρ]{.greek-abbr} τις ην μακεδων εστως παρακαλων αυτον και λεγων διαβας εις μακεδονιαν βοηθησον ημιν[16:9]{.aside}

ως δε το [οραμα]{.greek-omitted} [ωραμα]{.greek-added} ειδεν ευθεως εζητησαμεν εξελθειν εις την μακεδονιαν συμβιβαζοντες οτι προσκεκληται ημας ο [κυριος]{.greek-abbr} ευαγγελισασθαι αυτους[16:10]{.aside}

αναχθεντες ουν απο της τρωαδος ευθυδρομησαμεν εις σαμοθρακην τη τε επιουση εις νεαπολιν[16:11]{.aside}

εκειθεν τε εις φιλιππους [και]{.greek-added} ητις [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη της μεριδος της μακεδονιας πολις κολωνεια ημεν δε εν αυτη τη πολει διατριβοντες ημερας τινας[16:12]{.aside}

τη τε ημερα των [σαββατων]{.greek-omitted} [σαβατων]{.greek-added} εξηλθομεν εξω της πολεως παρα ποταμον ου ενομιζετο [προσευχη]{.greek-omitted} [προσευσευχη]{.greek-added} ειναι και καθισαντες ελαλουμεν ταις συνελθουσαις γυναιξιν[16:13]{.aside}

και τις γυνη ονοματι λυδια [πορφυροπωλις]{.greek-omitted} [πορφυροπολις]{.greek-added} πολεως θυατειρων σεβομενη τον [θεον]{.greek-abbr} [ηκουεν]{.greek-omitted} [ηκουσεν]{.greek-added} ης ο [κυριος]{.greek-abbr} διηνοιξεν την καρδιαν προσεχειν τοις λαλουμενοις υπο του παυλου[16:14]{.aside}

ως δε εβαπτισθη και ο οικος αυτης παρεκαλεσεν λεγουσα ει κεκρικατε με πιστην τω [κυριω]{.greek-abbr} ειναι εισελθοντες εις τον οικον μου μεινατε και παρεβιασατο ημας[16:15]{.aside}

εγενετο δε πορευομενων ημων εις προσευχην παιδισκην τινα εχουσαν πνευμα πυθωνος απαντησαι ημιν ητις εργασιαν πολλην παρειχεν τοις κυριοις αυτης μαντευομενη[16:16]{.aside}

αυτη [κατακολουθησασα]{.greek-omitted} [κατακολουθεισα]{.greek-added} τω παυλω και [ημιν]{.greek-omitted} [τω]{.greek-added} [σιλα]{.greek-added} εκραζεν λεγουσα ουτοι οι [ανθρωποι]{.greek-abbr} δουλοι του [θεου]{.greek-abbr} του υψιστου εισιν οιτινες [καταγγελλουσιν]{.greek-omitted} [καταγγελουσιν]{.greek-added} ημιν οδον [σωτηριας]{.greek-abbr}[16:17]{.aside}

τουτο δε εποιει επι πολλας ημερας διαπονηθεις δε ο παυλος και επιστρεψας τω [πνευματι]{.greek-abbr} ειπεν [παραγγελλω]{.greek-omitted} [παραγγέλω]{.greek-added} σοι εν τω ονοματι [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} εξελθειν απ αυτης και εξηλθεν [αυτη]{.greek-omitted} [αυτῆ]{.greek-added} τη ωρα[16:18]{.aside}

ιδοντες δε οι κυριοι αυτης οτι εξηλθεν η ελπις της [εργασιας]{.greek-omitted} [εργασισιας]{.greek-added} αυτων επιλαβομενοι τον παυλον και τον σιλαν ειλκυσαν εις την αγοραν επι τους αρχοντας[16:19]{.aside}

και προσαγαγοντες αυτους τοις στρατηγοις ειπον ουτοι οι [ανθρωποι]{.greek-abbr} εκταρασσουσιν ημων την πολιν ιουδαιοι υπαρχοντες[16:20]{.aside}

και [καταγγελλουσιν]{.greek-omitted} [καταγγελουσιν]{.greek-added} εθη α ουκ εξεστιν ημιν παραδεχεσθαι ουδε ποιειν ρωμαιοις ουσιν[16:21]{.aside}

και συνεπεστη ο οχλος κατ αυτων και οι στρατηγοι περιρρηξαντες αυτων τα ιματια εκελευον ραβδιζειν[16:22]{.aside}

πολλας τε επιθεντες αυτοις πληγας εβαλον εις φυλακην παραγγειλαντες τω δεσμοφυλακι ασφαλως τηρειν αυτους[16:23]{.aside}

ος παραγγελιαν τοιαυτην ειληφως εβαλεν αυτους εις την εσωτεραν φυλακην και τους ποδας αυτων ησφαλισατο εις το ξυλον[16:24]{.aside}

κατα δε το μεσονυκτιον παυλος και σιλας προσευχομενοι υμνουν τον [θεον]{.greek-abbr} επηκροωντο δε αυτων οι δεσμιοι[16:25]{.aside}

αφνω δε σεισμος εγενετο μεγας ωστε σαλευθηναι τα θεμελια του δεσμωτηριου ανεωχθησαν τε παραχρημα αι θυραι πασαι και παντων τα δεσμα ανεθη[16:26]{.aside}

εξυπνος δε γενομενος ο δεσμοφυλαξ και ιδων ανεωγμενας τας θυρας της φυλακης σπασαμενος μαχαιραν εμελλεν εαυτον αναιρειν νομιζων εκπεφευγεναι τους δεσμιους[16:27]{.aside}

[εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} δε φωνη μεγαλη ο παυλος λεγων μηδεν πραξης σεαυτω κακον απαντες γαρ εσμεν ενθαδε[16:28]{.aside}

αιτησας δε φωτα εισεπηδησεν και εντρομος γενομενος προσεπεσεν τω παυλω και τω σιλα[16:29]{.aside}

και προαγαγων αυτους εξω εφη κυριοι τι με δει ποιειν ινα σωθω[16:30]{.aside}

οι δε ειπον πιστευσον επι τον [κυριον]{.greek-abbr} [ιησουν]{.greek-abbr} [χριστον]{.greek-abbr} και σωθηση συ και ο οικος σου[16:31]{.aside}

και [ελαλησαν]{.greek-omitted} [ελαλησεν]{.greek-added} αυτω τον λογον του [κυριου]{.greek-abbr} και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια αυτου[16:32]{.aside}

και παραλαβων αυτους εν εκεινη τη ωρα της νυκτος ελουσεν απο των πληγων και εβαπτισθη [και]{.greek-added} αυτος και οι αυτου παντες παραχρημα[16:33]{.aside}

[αναγαγων]{.greek-omitted} [αναγαγωντες]{.greek-added} [τε]{.greek-omitted} αυτους εις τον οικον αυτου παρεθηκεν τραπεζαν και ηγαλλιατο [[ηγαλλιασατο]{.corr}]{.greek-added} πανοικι πεπιστευκως τω [θεω]{.greek-abbr}[16:34]{.aside}

ημερας δε γενομενης απεστειλαν οι στρατηγοι τους ραβδουχους λεγοντες απολυσον τους [ανθρωπους]{.greek-abbr} εκεινους[16:35]{.aside}

απηγγειλεν δε ο δεσμοφυλαξ τους λογους τουτους προς τον παυλον οτι απεσταλκασιν οι στρατηγοι ινα απολυθητε νυν ουν εξελθοντες πορευεσθε εν ειρηνη[16:36]{.aside}

ο δε παυλος εφη [προς]{.greek-omitted} [πρους]{.greek-added} αυτους δειραντες ημας δημοσια ακατακριτους [ανθρωπους]{.greek-abbr} ρωμαιους υπαρχοντας εβαλον εις φυλακην και νυν λαθρα ημας εκβαλλουσιν ου γαρ αλλα ελθοντες αυτοι εξαγαγετωσαν[16:37]{.aside}

ανηγγειλαν δε τοις στρατηγοις οι ραβδουχοι τα ρηματα ταυτα και εφοβηθησαν ακουσαντες οτι ρωμαιοι εισιν[16:38]{.aside}

και ελθοντες παρεκαλεσαν αυτους και εξαγαγοντες ηρωτων εξελθειν της πολεως[16:39]{.aside}

εξελθοντες δε εκ της φυλακης εισηλθον προς την λυδιαν και ιδοντες τους αδελφους παρεκαλεσαν αυτους και εξηλθον[16:40]{.aside}

### Chapter 17

διοδευσαντες δε την αμφιπολιν και απολλωνιαν ηλθον εις θεσσαλονικην οπου ην η συναγωγη των ιουδαιων[17:1]{.aside}

κατα δε το ειωθος τω παυλω εισηλθεν προς αυτους και επι σαββατα τρια [διελεξατο]{.greek-omitted} [διελεγετο]{.greek-added} αυτοις απο των γραφων[17:2]{.aside}

διανοιγων και παρατιθεμενος οτι τον [χριστον]{.greek-abbr} εδει παθειν και αναστηναι εκ νεκρων και οτι ουτος εστιν ο [χριστος]{.greek-abbr} [ιησους]{.greek-abbr} ον εγω καταγγελλω υμιν[17:3]{.aside}

και τινες εξ αυτων επεισθησαν και προσεκληρωθησαν τω παυλω και τω σιλα των τε σεβομενων ελληνων πολυ πληθος γυναικων τε των πρωτων ουκ ολιγαι[17:4]{.aside}

προσλαβομενοι δε οι ιουδαιοι οι απειθουντες των αγοραιων τινας ανδρας πονηρους και οχλοποιησαντες εθορυβουν την πολιν επισταντες τε τη οικια ιασονος εζητουν αυτους αγαγειν εις τον δημον[17:5]{.aside}

μη ευροντες δε αυτους [εσυρον]{.greek-omitted} [εσυραν]{.greek-added} τον ιασονα και τινας αδελφους επι τους πολιταρχας βοωντες οτι [οι]{.greek-omitted} [εις]{.greek-added} την οικουμενην αναστατωσαντες ουτοι και ενθαδε παρεισιν[17:6]{.aside}

ους υποδεδεκται ιασων και ουτοι παντες απεναντι των [δογ]{.greek-added} [δογματων]{.greek-omitted} [ματων]{.greek-added} κ[α]{.unclear}ισαρος πρασσουσιν βασιλεα λεγοντες ε[τε]{.unclear}ρον ειναι [ιησουν]{.greek-abbr}[17:7]{.aside}

εταραξαν δε [τ]{.unclear}ον οχλον και τους πολιταρχας ακουοντας ταυτα[17:8]{.aside}

και λαβοντες το ικανον παρα του ιασονος και των λοιπων απελυσαν αυτους[17:9]{.aside}

οι δε αδελφοι ευθεως δια της νυκτος εξεπεμψαν τον τε παυλον και τον σιλαν εις βεροιαν οιτινες παραγενομενοι εις την συναγωγην απηεσαν των ιουδαιων[17:10]{.aside}

ουτοι δε ησαν ευγενεστεροι των εν θεσσαλονικη οιτινες εδεξαντο τον λογον μετα πασης προθυμιας το καθ ημεραν ανακρινοντες τας γραφας ει εχοι ταυτα ουτως[17:11]{.aside}

πολλοι μεν ουν εξ αυτων επιστευσαν και των ελληνιδων γυναικων των ευσχημονων και ανδρων ουκ ολιγοι[17:12]{.aside}

ως δε [ε]{.unclear}γνωσαν οι απο τη[ς]{.unclear} [θ]{.unclear}εσσαλονικης ιουδαιοι οτι και εν τη [βεροια]{.greek-omitted} [βερροια]{.greek-added} [κατηγγελη]{.greek-omitted} [καταγγελει]{.greek-added} υπο του παυλου ο λογος του [θεου]{.greek-abbr} ηλθον κακει σαλευοντες τους οχλους[17:13]{.aside}

ευθεως δε τοτε τον παυλον εξαπεστειλαν οι αδελφοι πορευεσθα[ι]{.greek-supplied} ως επι την θαλασσαν υπεμενον δε ο τε σιλας και ο τιμοθεος εκει[17:14]{.aside}

οι δε καθιστωντες τον παυλον ηγαγον αυτον εως αθηνων και λαβοντες εντολην προς τον σιλαν και τιμοθεον ινα ως ταχιστα ελθωσιν προς αυτον εξηεσαν[17:15]{.aside}

εν δε ταις αθηναις εκδεχομενου αυτους του παυλου [παρωξυνετο]{.greek-omitted} [παροξυνετο]{.greek-added} το [πνευμα]{.greek-abbr} αυτου εν αυτω θεωρουντι κατειδωλον ουσαν την πολιν[17:16]{.aside}

διελεγετο μεν ουν εν τη συναγωγη τοις [ιουδαιοις]{.greek-omitted} [ιουδεοις]{.greek-added} και τοις σεβομενοις και εν τη αγορα κατα πασαν ημεραν προς τους παρατυγχανοντας[17:17]{.aside}

τινες δε και των [επικουρειων]{.greek-omitted} [επικουριων]{.greek-added} και των στοικων φιλοσοφων συνεβαλλον αυτω και τινες ελεγον τι αν θελοι ο σπερμολογος ουτος λεγειν οι δε ξενων δαιμονιων δοκει καταγγελευς ειναι οτι τον [ιησουν]{.greek-abbr} και την αναστασιν ευηγγελιζετο[17:18]{.aside}

επιλαβομενοι τε αυτου επι τον [α]{.unclear}ρειον παγον ηγαγον λεγοντες δυναμεθα γνωναι τις η καινη αυτη η υπο σου λαλουμενη διδαχη[17:19]{.aside}

ξενιζοντα γαρ τινα εισφερεις εις τας ακοας ημων βουλομεθα ουν γνωναι τι αν θελοι ταυτα ειναι[17:20]{.aside}

αθηναιοι δε παντες και οι επιδημουντες ξενοι εις ουδεν ετερον ευκαιρουν η λεγειν τι και ακουειν καινοτερον[17:21]{.aside}

σταθεις δε ο παυλος εν μεσω του αρειου παγου εφη ανδρες αθηναιοι κατα παντα ως δεισιδαιμονεστερους υμας θεωρω[17:22]{.aside}

διερχομενος γαρ και [αναθεωρων]{.greek-omitted} [αναθεορων]{.greek-added} τα σεβασματα υμων ευρον και βωμον εν ω [επ[―]{.gap}]{.greek-added} επεγεγραπτο αγνωστω [θεω]{.greek-abbr} ον ουν αγνοουντες ευσεβειτε τουτον εγω [καταγγελω]{.greek-added} [καταγγελλω]{.corr} υμιν[17:23]{.aside}

ο [θεος]{.greek-abbr} ο ποιησας τον κοσμον και παντα τα εν αυτω ουτος [ουρανου]{.greek-abbr} και γης [κυριος]{.greek-abbr} υπαρχων ουκ εν χειροποιητοις ναοις κατοικει[17:24]{.aside}

ουδε υπο χειρων [ανθρωπων]{.greek-abbr} θεραπευεται προσδεομενος τινος αυτος διδους [πασιν]{.greek-omitted} [πασι]{.greek-added} ζωην και πνοην κατα παντα[17:25]{.aside}

εποιησεν τε εξ ενος αιματος παν εθνος [ανθρωπων]{.greek-abbr} κατοικειν επι παν το προσωπον της γης ορισας προστεταγμενους καιρους και τας οροθεσιας της κατοικιας αυτων[17:26]{.aside}

ζητειν τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} ει αρα γε ψηλαφησειαν αυτον και ευροιεν και γε ου μακραν απο ενος εκαστου ημων υπαρχοντα[17:27]{.aside}

εν αυτω γαρ ζωμεν και κινουμεθα και εσμεν ως και τινες των καθ υμας ποιητων ειρηκασιν του γαρ και γενος εσμεν[17:28]{.aside}

γενος ουν υπαρχοντες του [θεου]{.greek-abbr} ουκ οφειλομεν νομιζειν χρυσω η αργυρω η λιθω χαραγματι τεχνης και ενθυμησεως [ανθρωπου]{.greek-abbr} το θειον ειναι ομοιον[17:29]{.aside}

τους μεν ουν χρονους της αγνοιας υπεριδων ο [θεος]{.greek-abbr} τα νυν παραγγελλει τοις [ανθρωποις]{.greek-abbr} [πασιν]{.greek-omitted} [πα[σ]{.unclear}ι]{.greek-added} πανταχου μετανοειν[17:30]{.aside}

διοτι εστησεν ημεραν εν η μελλει κρινειν την οικουμενην εν δικαιοσυνη εν ανδρι ω ωρισεν πιστιν παρασχων πασιν αναστησας αυτον εκ νεκρων[17:31]{.aside}

ακουσαντες δε αναστασιν νεκρων οι μεν εχλευαζον οι δε ειπον ακουσομεθα σου παλιν περι τουτου[17:32]{.aside}

και ουτως ο παυλος εξηλθεν εκ μεσου αυτων[17:33]{.aside}

τινες δε ανδρες κολληθεντες αυτω επιστευσαν εν οις και διονυσιος ο αρεοπαγιτης και γυνη ονοματι δαμαρις και ετεροι συν αυτοις[17:34]{.aside}

### Chapter 18

μετα δε ταυτα χωρισθεις ο παυλος εκ των αθηνων ηλθεν εις κορινθον[18:1]{.aside}

και ευρων τινα ιουδαιον ονοματι ακυλαν ποντικον τω γενει προσφατως εληλυθοτα απο της ιταλιας και πρισκιλλαν γυναικα αυτου δια το [τεταχεναι]{.greek-omitted} [διατεταχεναι]{.greek-added} κλαυδιον χωριζεσθαι παντας τους ιουδαιους εκ της ρωμης προσηλθεν αυτοις[18:2]{.aside}

και δια το ομοτεχνον ειναι [εμενεν]{.greek-omitted} [εμεινεν]{.greek-added} παρ αυτοις και [ειργαζετο]{.greek-omitted} [εργαζετο]{.greek-added} ησαν γαρ σκηνοποιοι την τεχνην[18:3]{.aside}

διελεγετο δε εν τη συναγωγη κατα παν σαββατον επειθεν τε ιουδαιους και ελληνας[18:4]{.aside}

ως δε κατηλθον απο της μακεδονιας ο τε σιλας και ο τιμοθεος συνειχετο τω [πνευματι]{.greek-abbr} ο παυλος διαμαρτυρομενος τοις ιουδαιοις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:5]{.aside}

αντιτασσομενων δε αυτων και βλασφημουντων εκτιναξαμενος τα ιματια ειπεν προς αυτους το αιμα υμων επι την κεφαλην υμων καθαρος εγω απο του νυν εις τα εθνη πορευσομαι[18:6]{.aside}

και μεταβας εκειθεν ηλθεν εις οικιαν [τινος]{.greek-omitted} [τινοι]{.greek-added} ονοματι ιουστου σεβομενου τον [θεον]{.greek-abbr} ου [η]{.greek-omitted} οικια ην συνομορουσα τη συναγωγη[18:7]{.aside}

κρισπος δε ο αρχισυναγωγος επιστευσεν τω [κυριω]{.greek-abbr} συν ολω τω οικω αυτου και πολλοι των κορινθιων [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added} επιστευον και εβαπτιζοντο[18:8]{.aside}

ειπεν δε ο [κυριος]{.greek-abbr} δι οραματος εν νυκτι τω παυλω μη φοβου αλλα λαλει και μη σιωπησης[18:9]{.aside}

διοτι εγω ειμι μετα σου και ουδεις επιθησεται σοι του [κα]{.greek-added} [κακωσαι]{.greek-omitted} [κωσαι]{.greek-added} σε διοτι λαος εστιν μοι πολυς εν τη πολει ταυτη[18:10]{.aside}

εκαθισεν τε ενιαυτον και μηνας εξ διδασκων εν αυτοις τον λογον του [θεου]{.greek-abbr}[18:11]{.aside}

γαλλιωνος δε ανθυπατευοντος της αχαιας κατεπεστησαν ομοθυμαδον [οι]{.greek-omitted} ιουδαιοι τω παυλω και ηγαγον αυτον επι το βημα[18:12]{.aside}

λεγοντες οτι παρα τον νομον ουτος αναπειθει τους [ανθρωπους]{.greek-abbr} σεβεσθαι τον [θεον]{.greek-abbr}[18:13]{.aside}

μελλοντος δε του παυλου ανοιγειν το στομα ειπεν ο γαλλιων προς τους ιουδαιους ει μεν ουν [ην]{.greek-omitted} αδικημα τι η ραδιουργημα πονηρον ω ιουδαιοι κατα λογον αν ηνεσχομην υμων[18:14]{.aside}

ει δε [ζητημα]{.greek-omitted} [ζητηματα]{.greek-added} εστιν περι λογου και ονοματων και νομου του καθ υμας οψεσθε αυτοι κριτης γαρ εγω τουτων ου βουλομαι ειναι[18:15]{.aside}

και απηλασεν αυτους απο του βηματος[18:16]{.aside}

επιλαβομενοι δε παντες οι ελληνες σωσθενην τον αρχισυναγωγον ετυπτον εμπροσθεν του βηματος και ουδεν τουτων τω [λλιωνι]{.greek-added} [γαλλιωνι]{.corr} εμελλεν[18:17]{.aside}

ο δε παυλος ετι προσμεινας ημερας ικανας τοις αδελφοις αποταξαμενος εξεπλει εις την συριαν και συν αυτω πρισκιλλα και [ακυλας]{.greek-omitted} [ακυλα]{.greek-added} κειραμενος την κεφαλην εν [κεχρεαις]{.greek-added} [κεγχρεαις]{.corr} ειχεν γαρ ευχην[18:18]{.aside}

κατηντησεν δε εις εφεσον και εκεινους κατελιπεν αυτου αυτος δε εισελθων εις την συναγωγην διελεχθη τοις ιουδαιοις[18:19]{.aside}

[ερωτωντων]{.greek-omitted} [ερωτοντων]{.greek-added} δε αυτων επι πλειονα χρονον μειναι παρ αυτοις ουκ επενευσεν[18:20]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} απεταξατο αυτοις ειπων δει με παντως την εορτην την ερχομενην ποιησαι εις ιεροσολυμα παλιν δε ανακαμψω προς υμας του [θεου]{.greek-abbr} θελοντος [και]{.greek-added} ανηχθη απο της εφεσου[18:21]{.aside}

και κατελθων εις [καισαρειαν]{.greek-omitted} [καισσαρειαν]{.greek-added} αναβας και ασπασαμενος την εκκλησιαν κατεβη εις αντιοχειαν[18:22]{.aside}

και ποιησας χρονον τινα εξηλθεν διερχομενος καθεξης την γαλατικην χωραν και φρυγιαν επιστηριζων παντας τους μαθητας[18:23]{.aside}

ιουδαιος δε τις απολλως ονοματι αλεξανδρευς τω γενει ανηρ λογιος κατηντησεν εις εφεσον δυνατος ων εν ταις γραφαις[18:24]{.aside}

ουτος ην κατηχημενος την οδον του [κυριου]{.greek-abbr} και ζεων τω [πνευματι]{.greek-abbr} [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} και εδιδασκεν ακριβως τα περι του [κυριου]{.greek-abbr} επισταμενος μονον το βαπτισμα ιωαννου[18:25]{.aside}

ουτος τε ηρξατο παρρησιαζεσθαι εν τη συναγωγη ακουσαντες δε αυτου ακυλας και [πρισκιλλα]{.greek-omitted} [πρισ[κι]{.unclear}λα]{.greek-added} προσελαβοντο αυτον και ακριβεστερον αυτω εξεθεντο την του [θεου]{.greek-abbr} οδον[18:26]{.aside}

βουλομενου δε αυτου διελθειν εις την αχαιαν προτρεψαμενοι οι αδελφοι εγραψαν τοις μαθηταις αποδεξασθαι αυτον ος παραγενομενος συνεβαλετο πολυ τοις [πεπιστευκοσιν]{.greek-omitted} [πεπιστευκοσι]{.greek-added} δια της χαριτος[18:27]{.aside}

ευτονως γαρ τοις ιουδαιοις διακατηλεγχετο δημοσια επιδεικνυς δια των γραφων ειναι τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[18:28]{.aside}

### Chapter 19

εγενετο δε εν τω τον απολλω ειναι εν κορινθω παυλον [δε]{.greek-added} διελθοντα τα ανωτερικα μερη ελθειν εις εφεσον και ευρων τινας μαθητας[19:1]{.aside}

ειπεν προς αυτους ει [πνευμα]{.greek-abbr} αγιον ελαβετε πιστευσαντες οι δε [ειπον]{.greek-omitted} [ειπαν]{.greek-added} προς αυτον αλλ ουδε ει [πνευμα]{.greek-abbr} αγιον εστιν ηκουσαμεν[19:2]{.aside}

ειπεν τε προς αυτους εις τι ουν εβαπτισθητε οι δε ειπον εις το ιωαννου βαπτισμα[19:3]{.aside}

ειπεν [δε]{.greek-omitted} [τε]{.greek-added} παυλος ιωαννης μεν εβαπτισεν βαπτισμα μετανοιας τω λαω λεγων εις τον ερχομενον μετ [αυτον]{.greek-omitted} [αυτων]{.greek-added} ινα πιστευσωσιν τουτ εστιν εις τον [χριστον]{.greek-abbr} [ιησουν]{.greek-abbr}[19:4]{.aside}

ακουσαντες δε εβαπτισθησαν εις το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:5]{.aside}

και επιθεντος αυτοις του παυλου τας χειρας ηλθεν το [πνευμα]{.greek-abbr} το αγιον επ αυτους ελαλουν τε γλωσσαις και [προφητευον]{.greek-added} [προεφητευον]{.corr}[19:6]{.aside}

ησαν δε οι παντες ανδρες ωσει δεκαδυο[19:7]{.aside}

εισελθων δε εις την συναγωγην επαρρησιαζετο επι μηνας τρεις διαλεγομενος και πειθων τα περι της βασιλειας του [θεου]{.greek-abbr}[19:8]{.aside}

ως δε τινες εσκληρυνοντο και ηπειθουν κακολογουντες την οδον ενωπιον του πληθους αποστας απ αυτων αφωρισεν τους μαθητας καθ ημεραν διαλεγομενος εν τη σχολη τυραννου τινος[19:9]{.aside}

τουτο δε εγενετο επι ετη δυο ωστε παντας τους κατοικουντας την ασιαν ακουσαι τον λογον του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} ιουδαιους τε και ελληνας[19:10]{.aside}

δυναμεις τε ου τας τυχουσας εποιει ο [θεος]{.greek-abbr} δια των χειρων παυλου[19:11]{.aside}

ωστε και επι τους ασθενουντας επιφερεσθαι απο του χρωτος αυτου σουδαρια η σιμικινθια και [απαλλασσεσθαι]{.greek-omitted} [απαλλασεσθαι]{.greek-added} απ αυτων τας νοσους [τας]{.greek-added} [τα]{.corr} τε πνευματα τα πονηρα [εξερχεσθαι]{.greek-omitted} [εξερχεσθε]{.greek-added} απ αυτων[19:12]{.aside}

επεχειρησαν δε τινες [και]{.greek-added} απο των περιερχομενων ιουδαιων εξορκιστων ονομαζειν επι τους εχοντας τα [πνευματα]{.greek-abbr} τα πονηρα το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} λεγοντες ορκιζομεν υμας τον [ιησουν]{.greek-abbr} ον ο παυλος κηρυσσει[19:13]{.aside}

ησαν δε τινες υιοι σκευα ιουδαιου αρχιερεως επτα οι τουτο ποιουντες[19:14]{.aside}

αποκριθεν δε το [πνευμα]{.greek-abbr} το πονηρον ειπεν τον [ιησουν]{.greek-abbr} γινωσκω και τον παυλον επισταμαι υμεις δε τινες εστε[19:15]{.aside}

και εφαλλομενος επ αυτους ο [ανθρωπος]{.greek-abbr} εν ω ην το [πνευμα]{.greek-abbr} το πονηρον και κατακυριευσαν αυτων ισχυσεν κατ αυτων ωστε γυμνους και τετραυματισμενους εκφυγειν εκ του οικου εκεινου[19:16]{.aside}

τουτο δε εγενετο γνωστον πασιν ιουδαιοις τε και ελλησιν τοις [κατοικουσιν]{.greek-omitted} [κατοικουσι]{.greek-added} την εφεσον και επεπεσεν φοβος επι παντας αυτους και εμεγαλυνετο το ονομα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[19:17]{.aside}

πολλοι τε των πεπιστευκοτων ηρχοντο εξομολογουμενοι και αναγγελλοντες τας πραξεις αυτων[19:18]{.aside}

ικανοι δε των τα περιεργα πραξαντων συνενεγκαντες τας βιβλους κατεκαιον ενωπιον παντων και συνεψηφισαν τας τιμας αυτων και ευρον αργυριου μυριαδας πεντε[19:19]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} κατα κρατος ο λογος του [κυριου]{.greek-abbr} ηυξανεν και ισχυεν[19:20]{.aside}

ως δε επληρωθη ταυτα εθετο ο παυλος εν τω [πνευματι]{.greek-abbr} διελθων την μακεδονιαν και αχαιαν πορευεσθαι εις ιερουσαλημ ειπων οτι μετα το γενεσθαι με εκει δει με και ρωμην ιδειν[19:21]{.aside}

αποστειλας δε εις την μακεδονιαν δυο των διακονουντων αυτω τιμοθεον και εραστον αυτος επεσχεν χρονον εις την ασιαν[19:22]{.aside}

εγενετο δε κατα τον καιρον εκεινον ταραχος ουκ ολιγος περι της οδου[19:23]{.aside}

δημητριος γαρ τις ονοματι αργυροκοπος ποιων ναους αργυρους [της]{.greek-added} αρτεμιδος παρειχετο τοις τεχνιταις εργασιαν ουκ ολιγην[19:24]{.aside}

ους συναθροισας και τους περι τα τοιαυτα εργατας ειπεν ανδρες επιστασθε οτι εκ ταυτης της εργασιας η ευπορια ημων εστιν[19:25]{.aside}

και θεωρειτε και ακουετε οτι ου μονον εφεσου αλλα σχεδον πασης της ασιας ο παυλος ουτος πεισας μετεστησεν ικανον οχλον λεγων οτι ουκ εισιν θεοι οι δια χειρων γινομενοι[19:26]{.aside}

ου μονον δε τουτο κινδυνευει ημιν το μερος εις απελεγμον ελθειν αλλα και το της μεγαλης θεας ιερον αρτεμιδος εις [ουθεν]{.greek-omitted} [ουδεν]{.greek-added} λογισθηναι μελλειν δε και καθαιρεισθαι την μεγαλειοτητα αυτης ην ολη η ασια και η οικουμενη σεβεται[19:27]{.aside}

ακουσαντες δε και γενομενοι [πληρεις]{.greek-omitted} [πληρης]{.greek-added} θυμου εκραζον λεγοντες μεγαλη η αρτεμις εφεσιων[19:28]{.aside}

και επλησθη η πολις ολη της συγχυσεως ωρμησαν τε ομοθυμαδον εις το θεατρον συναρπασαντες γαιον και αρισταρχον [και]{.greek-added} μακεδονας συνεκδημους παυλου[19:29]{.aside}

του δε παυλου βουλομενου εισελθειν εις τον δημον ουκ ειων αυτον οι μαθηται[19:30]{.aside}

τινες δε και των ασιαρχων οντες αυτω φιλοι πεμψαντες προς αυτον παρεκαλουν μη δουναι εαυτον εις το θεατρον[19:31]{.aside}

αλλοι μεν ουν αλλο τι εκραζον ην γαρ η εκκλησια συγκεχυμενη και οι πλειους ουκ ηδεισαν τινος ενεκεν [συνεληλυθεισαν]{.greek-omitted} [συνελυθεισαν]{.greek-added}[19:32]{.aside}

εκ δε του οχλου προεβιβασαν αλεξανδρον προβαλοντων αυτον των ιουδαιων ο δε αλεξανδρος κατασεισας την χειρα ηθελεν απολογεισθαι τω δημω[19:33]{.aside}

επιγνοντες δε οτι ιουδαιος εστιν φωνη [εγενετο]{.greek-omitted} [ελεγετο]{.greek-added} μια εκ παντων ως επι ωρας δυο κραζοντων μεγαλη η αρτεμις εφεσιων[19:34]{.aside}

καταστειλας δε ο γραμματευς τον οχλον φησιν ανδρες εφεσιοι τις γαρ εστιν [ανθρωπος]{.greek-abbr} ος ου γινωσκει την εφεσιων πολιν νεωκορον ουσαν της μεγαλης θεας αρτεμιδος και του διοπετους[19:35]{.aside}

αναντιρρητων ουν οντων τουτων δεον εστιν υμας [κατεσταλμενους]{.greek-omitted} [κατεσταμενους]{.greek-added} υπαρχειν και μηδεν προπετες [πρασσειν]{.greek-omitted} [πρασειν]{.greek-added}[19:36]{.aside}

[ηγαγετε]{.greek-omitted} [ηγαγεται]{.greek-added} γαρ τους ανδρας τουτους ουτε ιεροσυλους ουτε βλασφημουντας την [θεον]{.greek-omitted} [θεαν]{.greek-added} υμων[19:37]{.aside}

ει μεν ουν δημητριος και οι συν αυτω τεχνιται [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} προς τινα λογον αγοραιοι αγονται και ανθυπατοι εισιν εγκαλειτωσαν αλληλοις[19:38]{.aside}

ει δε τι περι ετερων επιζητειτε εν τη εννομω εκκλησια επιλυθησεται[19:39]{.aside}

και γαρ κινδυνευομεν εγκαλεισθαι στασεως περι της σημερον μηδενος αιτιου υπαρχοντος περι ου ου δυνησομεθα δουναι λογον της συστροφης ταυτης [και]{.greek-added} [ταυτα]{.greek-added} [ειπων]{.greek-added} [απελυσεν]{.greek-added} [την]{.greek-added} [εκκλησιαν]{.greek-added}[19:40]{.aside}

### Chapter 20

μετα δε το παυσασθαι τον θορυβον προσκαλεσαμενος ο παυλος τους μαθητας και ασπασαμενος εξηλθεν πορευθηναι εις την μακεδονιαν[20:1]{.aside}

διελθων δε τα μερη εκεινα και παρακαλεσας αυτους λογω πολλω ηλθεν εις την ελλαδα[20:2]{.aside}

ποιησας τε μηνας τρεις γενομενης αυτω επιβουλης υπο των ιουδαιων μελλοντι αναγεσθαι εις την συριαν εγενετο γνωμη του υποστρεφειν δια μακεδονιας[20:3]{.aside}

συνειπετο δε αυτω αχρι της ασιας σωπατρος [βεροιαιος]{.greek-omitted} [βηροιαιος]{.greek-added} θεσσαλονικεων δε αρισταρχος και σεκουνδος και γαιος δερβαιος και τιμοθεος ασιανοι δε τυχικος και τροφιμος[20:4]{.aside}

ουτοι προσελθοντες εμενον ημας εν τρωαδι[20:5]{.aside}

ημεις δε εξεπλευσαμεν μετα τας ημερας των αζυμων απο φιλιππων και ηλθομεν προς αυτους εις την τρωαδα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ημερων πεντε ου διετριψαμεν ημερας επτα[20:6]{.aside}

εν δε τη μια των σαββατων συνηγμενων των μαθητων κλασαι αρτον ο παυλος διελεγετο αυτοις μελλων εξιεναι τη επαυριον παρετεινεν τε τον λογον μεχρι μεσονυκτιου[20:7]{.aside}

ησαν δε λαμπαδες ικαναι εν τω υπερωω ου ημεν συνηγμενοι[20:8]{.aside}

καθημενος δε τις νεανιας ονοματι ευτυχος επι της θυριδος καταφερομενος υπνω βαθει διαλεγομενου του παυλου επι πλειον κατενεχθεις [απο]{.greek-omitted} [υπο]{.greek-added} του υπνου επεσεν απο του τριστεγου κατω και ηρθη νεκρος[20:9]{.aside}

καταβας δε ο παυλος επεπεσεν αυτω και συμπεριλαβων ειπεν μη θορυβεισθε η γαρ ψυχη αυτου εν αυτω εστιν[20:10]{.aside}

αναβας δε και κλασας αρτον και γευσαμενος εφ ικανον τε ομιλησας [αχρι]{.greek-omitted} [αχρις]{.greek-added} αυγης ουτως εξηλθεν[20:11]{.aside}

ηγαγον δε τον παιδα ζωντα και παρεκληθησαν ου μετριως[20:12]{.aside}

ημε[ι]{.unclear}ς δε προσελθοντες επι το πλοιον ανηχθημεν εις τ[η]{.unclear}ν [ασσον]{.greek-omitted} [θασον]{.greek-added} εκειθεν μελλοντες αναλαμβανειν τον παυλον ουτως γαρ ην διατεταγμενος μελλων αυτος [πεζευειν]{.greek-omitted} [παιζευειν]{.greek-added}[20:13]{.aside}

ως δε συνεβαλεν ημιν εις την [ασσον]{.greek-omitted} [θασον]{.greek-added} αναλαβοντες αυτον ηλθομεν εις μιτυληνην[20:14]{.aside}

κακειθεν αποπλευσαντες τη επιουση κατηντησαμεν αντικρυ χιου τη δε ετερα παρεβαλομεν εις [σαμον]{.greek-omitted} [ἄμον]{.greek-added} και μειναντες εν τρωγυλλιω τη εχομενη ηλθομεν εις μιλητον[20:15]{.aside}

εκρινεν [γαρ]{.greek-omitted} ο παυλος παραπλευσαι την εφεσον οπως μη γενηται αυτω χρονοτριβησαι εν τη ασια εσπευδεν γαρ ει δυνατον ην αυτω την ημεραν της πεντηκοστης γενεσθαι εις ιεροσολυμα[20:16]{.aside}

απο δε της μιλητου πεμψας εις εφεσον μετεκαλεσατο τους πρεσβυτερους της εκκλησιας[20:17]{.aside}

ως δε παρεγενοντο προς αυτον ειπεν αυτοις υμεις επιστασθε απο πρωτης ημερας αφ ης επεβην εις την ασιαν πως μεθ υμων τον [παντα]{.greek-omitted} [απαντα]{.greek-added} χρονον εγενομην[20:18]{.aside}

δουλευων τω [κυριω]{.greek-abbr} μετα πασης ταπεινοφροσυνης και πολλων δακρυων και πειρασμων των συμβαντων μοι εν ταις επιβουλαις των ιουδαιων[20:19]{.aside}

ως ουδεν υπεστειλαμην των συμφεροντων του μη αναγγειλαι υμιν και διδαξαι υμας δημοσια και κατ οικους[20:20]{.aside}

[διαμαρτυρομενος]{.greek-omitted} [διαμαρτυραμενος]{.greek-added} ιουδαιοις τε και ελλησιν την εις τον [θεον]{.greek-abbr} μετανοιαν και πιστιν την εις τον [κυριον]{.greek-abbr} ημων [ιησουν]{.greek-abbr}[20:21]{.aside}

και νυν ιδου εγω δεδεμενος τω [πνευματι]{.greek-abbr} πορευομαι εις [ιερουσαλημ]{.greek-abbr} τα εν αυτη συναντησοντα μοι μη ειδως[20:22]{.aside}

πλην οτι το [πνευμα]{.greek-abbr} το αγιον κατα πολιν διαμαρτυρεται [λεγον]{.greek-omitted} [λεγων]{.greek-added} οτι δ[εσ]{.unclear}μα με και θλιψεις μενουσιν[20:23]{.aside}

αλλ ουδενος λογον ποιουμαι ουδε εχω την ψυχην μου τιμιαν εμαυτω ως τελειωσαι τον δρομον μου μετα χαρας και την διακονιαν ην ελαβον παρα του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} διαμαρτυρασθαι το ευαγγελιον της χαριτος του [θεου]{.greek-abbr}[20:24]{.aside}

και νυν ιδου εγω οιδα οτι ουκετι [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} το προσωπον μου υμεις παντες εν οις διηλθον κηρυσσων την βασιλειαν του [θεου]{.greek-abbr}[20:25]{.aside}

[διοτι]{.greek-omitted} [διο]{.greek-added} μαρτυρομαι υμιν εν τη σημερον ημερα οτι καθαρος εγω απο του αιματος παντων[20:26]{.aside}

ου γαρ υπεστειλαμην του μη αναγγειλαι υμιν πασαν την βουλην του [θεου]{.greek-abbr}[20:27]{.aside}

προσεχετε ουν εαυτοις και παντι τω ποιμνιω εν ω υμας το [πνευμα]{.greek-abbr} το αγιον εθετο επισκοπους ποιμαινειν την εκκλησιαν του [κυριου]{.greek-abbr} και [θεου]{.greek-abbr} ην περιεποιησατο δια του ιδιου αιματος[20:28]{.aside}

εγω γαρ οιδα τουτο οτι εισελευσονται μετα την [αφιξιν]{.greek-omitted} [αφηξιν]{.greek-added} μου λυκοι βαρεις εις υμας μη φειδομενοι του ποιμνιου[20:29]{.aside}

και εξ υμων αυτων αναστησονται ανδρες λαλουντες διεστρα[μ]{.unclear}μενα του αποσπαν τους μαθητας οπισω αυτων[20:30]{.aside}

διο γρηγορειτε μνημονευοντες οτι τριετιαν νυκτα και ημεραν ουκ επαυσαμην μετα δακρυων νουθετων ενα εκαστον[20:31]{.aside}

και τα νυν παρατιθεμαι υμας αδελφοι τω [θεω]{.greek-abbr} και τω λογω της χαριτος αυτου τω δυναμενω εποικοδομησαι και δουναι [υμιν]{.greek-omitted} κληρονομιαν εν τοις ηγιασμενοις πασιν[20:32]{.aside}

αργυριου η χρυσιου η [ιματισμου]{.greek-omitted} [ιαματισμου]{.greek-added} ουδενος επεθυμησα[20:33]{.aside}

αυτοι γινωσκετε οτι ταις χρειαις μου και τοις [ουσιν]{.greek-omitted} [ουσι]{.greek-added} μετ εμου υπηρετησαν αι χειρες αυται[20:34]{.aside}

παντα υπεδειξα υμιν οτι ουτως κοπιωντας δει αντιλαμβανεσθαι των ασθενουντων μνημονευειν τε [των]{.greek-omitted} [λογων]{.greek-omitted} [του]{.greek-added} [λογου]{.greek-added} του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} οτι αυτος ειπεν μακαριον εστιν μαλλον διδοναι η λαμβανειν[20:35]{.aside}

και ταυτα ειπων θεις τα γονατα αυτου συν πασιν αυτοις προσηυξατο[20:36]{.aside}

ικανος δε εγενετο κλαυθμος παντων και επιπεσοντες επι τον τραχηλον του παυλου κατεφιλουν αυτον[20:37]{.aside}

οδυνωμενοι [μαλιστα]{.greek-omitted} [μαλλιστα]{.greek-added} επι τω λογω ω [ειρηκει]{.greek-omitted} [ειρηκη]{.greek-added} οτι ουκετι μελλουσιν το προσωπον αυτου θεωρειν προεπεμπον δε αυτον εις το πλοιον[20:38]{.aside}

### Chapter 21

ως δε εγενετο αναχθηναι ημας αποσπασθεντας απ αυτων [ευθυδρομησαντες]{.greek-omitted} [ευθυδρομησανσαντες]{.greek-added} ηλθομεν εις την κων τη δε εξης εις την ροδον κακειθεν εις παταρα[21:1]{.aside}

και ευροντες πλοιον διαπερων εις φοινικην επιβαντες ανηχθημεν[21:2]{.aside}

αναφανεντες δε την κυπρον και [καταλιποντες]{.greek-omitted} [καταλιπόντες]{.greek-added} αυτην ευωνυμον επλεομεν εις συριαν και κατηχθημεν εις τυρον εκεισε γαρ ην το πλοιον αποφορτιζομενον τον γομον[21:3]{.aside}

και ανευροντες μαθητας επεμειναμεν αυτου ημερας επτα οιτινες τω παυλω ελεγον δια του [πνευματος]{.greek-abbr} μη αναβαινειν εις [ιερουσαλημ]{.greek-abbr}[21:4]{.aside}

οτε δε εγενετο ημας [εξαρτισαι]{.greek-omitted} [εξαρτησαι]{.greek-added} τας ημερας εξελθοντες επορευομεθα προπεμποντων ημας παντων συν [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} και τεκνοις εως εξω της πολεως και θεντες τα γονατα επι τον αιγιαλον [προσηυξαμεθα]{.greek-omitted} [προευξαμεθα]{.greek-added}[21:5]{.aside}

και ασπασαμενοι αλληλους επεβημεν εις το πλοιον εκεινοι δε υπεστρεψαν εις τα ιδια[21:6]{.aside}

ημεις δε τον πλουν διανυσαντες απο τυρου κατηντησαμεν εις [πτολεμαιδα]{.greek-omitted} [πολεμαιδα]{.greek-added} και ασπασαμενοι τους αδελφους [εμειναμεν]{.greek-omitted} [επεμειναμεν]{.greek-added} ημεραν μιαν παρ αυτοις[21:7]{.aside}

τη δε επαυριον εξελθοντες οι περι τον παυλον ηλθον εις καισαρειαν και εισελθοντες εις τον οικον φιλιππου του ευαγγελιστου [οντος]{.greek-omitted} [οντως]{.greek-added} εκ των επτα εμειναμεν παρ αυτω[21:8]{.aside}

τουτω δε ησαν θυγατερες παρθενοι τεσσαρες προφητευουσαι[21:9]{.aside}

επιμενοντων δε [ημων]{.greek-omitted} ημερας πλειους κατηλθεν τις απο της ιουδαιας προφητης ονοματι αγαβος[21:10]{.aside}

και ελθων προς ημας και αρας την ζωνην του παυλου [δησας]{.greek-omitted} [δησα]{.greek-added} τε αυτου [τας]{.greek-added} [χειρας]{.greek-added} [και]{.greek-added} τους ποδας [και]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} ειπεν ταδε λεγει το [πνευμα]{.greek-abbr} το αγιον τον ανδρα ου εστιν η ζωνη αυτη ουτω[ς]{.unclear} [[ουτο[ς]{.unclear}]{.corr}]{.greek-added} δησουσιν εν ιερουσαλημ [οι]{.greek-omitted} ιουδαιοι και παραδωσουσιν εις χειρας εθνων[21:11]{.aside}

ως δε ηκουσαμεν ταυτα παρεκαλουμεν ημεις τε και οι εντοπιοι του μη αναβαινειν αυτον εις [ιερουσαλημ]{.greek-abbr}[21:12]{.aside}

απεκριθη τε ο παυλος τι ποιειτε κλαιοντες και [συνθρυπτοντες]{.greek-omitted} [θρυπτοντες]{.greek-added} μου την καρδιαν εγω γαρ ου μονον δεθηναι αλλα και αποθανειν εις [ιερουσαλημ]{.greek-abbr} ετοιμως εχω υπερ του ονοματος του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr}[21:13]{.aside}

μη πειθομενου δε αυτου ησυχασαμεν ειποντες το θελημα του [κυριου]{.greek-abbr} γενεσθω[21:14]{.aside}

μετα δε τας ημερας ταυτας επισκευασαμενοι ανεβαινομεν εις [ιερουσαλημ]{.greek-abbr}[21:15]{.aside}

συνηλθον δε και των μαθητων απο καισαρειας συν ημιν αγοντες παρ ω ξενισθωμεν μνασωνι τινι κυπριω αρχαιω μαθητη[21:16]{.aside}

γενομενων δε ημων εις ιεροσολυμα ασμενως εδεξαντο ημας οι αδελφοι[21:17]{.aside}

τη δε επιουση εισηει ο παυλος συν ημιν προς ιακωβον παντες τε παρεγενοντο οι πρεσβυτεροι[21:18]{.aside}

και ασπασαμενος αυτους εξηγειτο καθ εν εκα[σ]{.unclear}τον ων εποιησεν ο [θεος]{.greek-abbr} εν τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} δια της διακονιας αυτου[21:19]{.aside}

οι δε ακουσαντες εδοξαζον τον [κυριον]{.greek-abbr} [ειποντες]{.greek-omitted} [ειπον]{.greek-added} [δε]{.greek-added} αυτω θεωρεις αδελφε ποσαι μυριαδες εισιν ιουδαιων των πεπιστευκοτων και παντες ζηλωται του [ν]{.unclear}ομου υπαρχουσιν[21:20]{.aside}

κατηχηθησαν δε περι σου οτι αποστασιαν διδασκεις απο μωυσεως τους κατα τα εθνη παντας ιουδαιους λεγων μη περιτεμνειν αυτους τα τεκνα μηδε τοις [εθεσιν]{.greek-omitted} [εθνεσιν]{.greek-added} περιπατειν[21:21]{.aside}

τι ουν εστιν παντως δει πληθος συνελθειν ακουσονται γαρ οτι εληλυθας[21:22]{.aside}

τουτο ουν ποιησον ο σοι λεγομεν εισιν ημιν ανδρες τεσσαρες ευχην εχοντες εφ εαυτων[21:23]{.aside}

τουτους παραλαβων αγνισθητι συν αυτοις και δαπανησον επ αυτοις ινα [ξυρησωνται]{.greek-omitted} [ξυρησονται]{.greek-added} την κεφαλην και γνωσιν παντες οτι ων κατηχηνται περι σου ουδεν εστιν αλλα στοιχεις και αυτος τον νομον φυλασσων[21:24]{.aside}

περι δε των πεπιστευκοτων εθνων ημεις επεστειλαμεν κριναντες μηδεν τοιουτον τηρειν αυτους ει μη φυλασσεσθαι αυτους το τε ειδωλοθυτον και το αιμα και πνικτον και πορνειαν[21:25]{.aside}

τοτε ο παυλος παραλαβων τους ανδρας τη εχομενη ημερα συν αυτοις αγνισθεις εισηει εις το ιερον [διαγγελλων]{.greek-omitted} [διαγγελων]{.greek-added} την εκπληρωσιν των ημερων του αγνισμου εως ου προσηνεχθη υπερ ενος εκαστου αυτων η προσφορα[21:26]{.aside}

ως δε εμελλον αι επτα ημεραι συντελεισθαι οι απο της ασιας ιουδαιοι θεασαμενοι αυτον εν τω ιερω συνεχεον παντα τον οχλον και επεβαλον τας χειρας επ αυτον[21:27]{.aside}

κραζοντες ανδρες ισραηλιται βοηθειτε ουτος εστιν ο [ανθρωπος]{.greek-abbr} ο κατα του λαου και του νομου και του τοπου τουτου παντας πανταχου διδασκων ετι τε και ελληνας εισηγαγεν εις το ιερον και κεκοινωκεν τον αγιον τοπον τουτον[21:28]{.aside}

ησαν γαρ εωρακοτες τροφιμον τον εφεσιον εν τη πολει συν αυτω ον ενομιζον οτι εις το ιερον εισηγαγεν ο παυλος[21:29]{.aside}

εκινη[θ]{.unclear}η τε η πολις ολη και εγενετο συνδρομη του λαου και επιλαβομενοι του παυλου ειλκον αυτον εξω του ιερου και ευθεως εκλεισθησαν αι θυραι[21:30]{.aside}

ζητουντων δε αυτον αποκτειναι ανεβη φασις τω χιλιαρχω της σπειρης οτι ολη συγκεχυται [ιερουσαλημ]{.greek-abbr}[21:31]{.aside}

ος εξαυτης παραλαβων στρατιωτας και εκατονταρχους κατεδραμεν επ αυτους οι δε ιδοντες τον χιλιαρχον και τους στρατιω[τ]{.unclear}ας επαυσαντο τυπτοντες τον παυλον[21:32]{.aside}

εγγισας δε ο χιλιαρχος ε[π]{.greek-supplied}ελαβετο αυτου και εκελευσεν δεθηναι [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δυσιν και επυνθανετο τις αν ειη και τι εστιν πεποιηκως[21:33]{.aside}

αλλοι δε [αλλο]{.greek-omitted} [αλλ]{.greek-added} [τι]{.greek-omitted} [ὅτι]{.greek-added} εβοων εν τω οχλω μη δυναμενος δε γνωναι το ασφαλες δια τον θορυβον εκελευσεν αγεσθαι αυτον εις την παρεμβολην[21:34]{.aside}

οτε δε εγενετο επι τους αναβαθμους συνεβη βασταζεσθαι αυτον υπο των στρατιωτων δια την βιαν του οχλου[21:35]{.aside}

[ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} γαρ το πληθος του λαου κραζον αιρε αυτον[21:36]{.aside}

μελλων τε εισαγεσθαι εις την παρεμβολην ο παυλος λεγει τω χιλιαρχω ει εξεστιν μοι ειπειν [τι]{.greek-added} προς σε ο δε εφη ελληνιστι γινωσκεις[21:37]{.aside}

ουκ αρα συ ει ο αιγυπτιος ο προ τουτων των ημερων αναστατωσας και εξαγαγων εις την ερημον τους τετρακισχιλιους ανδρας των σικαριων[21:38]{.aside}

ειπεν δε ο παυλος εγω [ανθρωπος]{.greek-abbr} μεν ειμι ιουδαιος ταρσευς της κιλικιας ουκ [ασημου]{.greek-omitted} [ασιμου]{.greek-added} πολεως πολιτης δεομαι δε σου επιτρεψον μοι λαλησαι προς τον λαον[21:39]{.aside}

[επιτρεψαντος]{.greek-omitted} [επιτρε]{.greek-added} [ψαντος]{.greek-added} δε αυτου ο παυλος εστως επι των αναβαθμων κατεσεισεν τη χειρι τω λαω πολλης δε σιγης γενομενης [προσεφωνει]{.greek-omitted} [προσεφωνησεν]{.greek-added} τη εβραιδι διαλεκτω λεγων[21:40]{.aside}

### Chapter 22

ανδρες αδελφοι και [πατερες]{.greek-abbr} ακουσατε μου της προς υμας νυνι απολογιας[22:1]{.aside}

ακουσαντες δε οτι τη εβραιδι διαλεκτω [προσεφωνει]{.greek-omitted} [προσφωνει]{.greek-added} αυτοις μαλλον [παρεσχον]{.greek-omitted} [παρεχον]{.greek-added} ησυχιαν και φησιν[22:2]{.aside}

εγω μεν ειμι ανηρ ιουδαιος γεγεννημενος εν ταρσω της κιλικιας ανατεθραμμενος δε εν τη πολει ταυτη παρα τους ποδας γαμαλιηλ πεπαιδευμενος [δε]{.greek-added} κατα ακριβειαν του πατρωου νομου ζηλωτης υπαρχων του [θεου]{.greek-abbr} καθως παντες [υμεις]{.greek-omitted} [ημεις]{.greek-added} εστε σημερον[22:3]{.aside}

ος ταυτην την οδον εδιωξα αχρι θανατου δεσμευων και [παραδιδους]{.greek-omitted} [διδους]{.greek-added} εις φυλακας ανδρας τε και γυναικας[22:4]{.aside}

ως και ο αρχιερευς μαρτυρει μοι και παν το [πρεσβυτεριον]{.greek-omitted} [πρεσβυτερειον]{.greek-added} παρ ων και επιστολας δεξαμενος προς τους αδελφους εις δαμασκον επορευομην αξων και τους εκεισε οντας δεδεμενους εις [ιερουσαλημ]{.greek-abbr} ινα τιμωρηθωσιν[22:5]{.aside}

εγενετο δε μοι πορευομενω και εγγιζοντι τη δαμασκω περι μεσημβριαν εξαιφνης εκ του [ουρανου]{.greek-abbr} περιαστραψαι φως ικανον περι εμε[22:6]{.aside}

επεσα τε εις το εδαφος και ηκουσα φωνης λεγουσης μοι σαουλ σαουλ τι με διωκεις[22:7]{.aside}

εγω δε απεκριθην τις ει [κυριε]{.greek-abbr} ειπεν τε προς με εγω ειμι [ιησους]{.greek-abbr} ο ναζωραιος ον συ διωκεις[22:8]{.aside}

οι δε συν εμοι οντες το μεν φως εθεασαντο [και]{.greek-omitted} [εμφοβοι]{.greek-omitted} [εγενοντο]{.greek-omitted} την δε φωνην ουκ ηκουσαν του λαλουντος μοι[22:9]{.aside}

ειπον δε τι ποιησω [κυριε]{.greek-abbr} ο δε [κυριος]{.greek-abbr} ειπεν προς με αναστας πορευου εις δαμασκον κακει σοι λαληθησεται [τι]{.greek-added} [σε]{.greek-added} [δει]{.greek-added} [περι]{.greek-omitted} [παντων]{.greek-omitted} [ων]{.greek-omitted} [τετακται]{.greek-omitted} [σοι]{.greek-omitted} ποιησαι[22:10]{.aside}

ως δε ουκ ενεβλεπον απο της δοξης του φωτος εκεινου χειραγωγουμενος υπο των συνοντων μοι ηλθον εις δαμασκον[22:11]{.aside}

ανανιας δε τις ανηρ [ευσεβης]{.greek-omitted} [ευλαβης]{.greek-added} κατα τον νομον μαρτυρουμενος υπο παντων των κατοικουντων [εν]{.greek-added} [δαμασκω]{.greek-added} ιουδαιων[22:12]{.aside}

ελθων προς με και επιστας ειπεν μοι σαουλ αδελφε αναβλεψον καγω αυτη τη ωρα ανεβλεψα εις αυτον[22:13]{.aside}

ο δε ειπεν ο [θεος]{.greek-abbr} των [πατερων]{.greek-abbr} ημων προεχειρισατο σε γνωναι το θελημα αυτου και ιδειν τον δικαιον και ακουσαι φωνην εκ του στοματος αυτου[22:14]{.aside}

οτι εση μαρτυς αυτω προς παντας [ανθρωπους]{.greek-abbr} ων εωρακας και ηκουσας[22:15]{.aside}

και νυν τι μελλεις αναστας [βαπτισαι]{.greek-omitted} [βαπτισε]{.greek-added} και απολο[υ]{.unclear}σαι τας αμαρτιας σου επικαλεσαμενος το ονομα του [κυριου]{.greek-abbr} [[ιησου]{.greek-abbr}]{.greek-added}[22:16]{.aside}

εγενετο δε μοι υποστρεψαντι εις [ιερουσαλημ]{.greek-abbr} και προσευχομενου μου εν τω ιερω γενεσθαι με εν εκστασει[22:17]{.aside}

και ιδειν αυτον λεγοντα μοι σπευσον και εξελθε εν ταχει εξ [ιερουσαλημ]{.greek-abbr} διοτι ου παραδεξονται σου την μαρτυριαν περι εμου[22:18]{.aside}

καγω ειπον [κυριε]{.greek-abbr} αυτοι επιστανται οτι εγω ημην φυλακιζων και δερων κατα τας συναγωγας τους πιστευοντας επι σε[22:19]{.aside}

και οτε εξεχειτο το αιμα στεφανου του μαρτυρος σου και αυτος ημην εφεστως και συνευδοκων τη αναιρεσει αυτου φυλασσων τα ιματια των αναιρουντων αυτον[22:20]{.aside}

και ειπεν προς με πορευου οτι εγω εις εθνη μακραν εξαποστελω σε[22:21]{.aside}

ηκουον δε [αυτου]{.greek-omitted} αχρι τουτου του λογου και επηραν την φωνην αυτων λεγοντες αιρε απο της γης τον τοιουτον ου γαρ καθηκεν αυτον ζην[22:22]{.aside}

[κραζοντων]{.greek-omitted} [κραυγαζοντων]{.greek-added} δε αυτων και [ριπτουντων]{.greek-omitted} [ριπτοντων]{.greek-added} τα ιματια και κονιορτον βαλλοντων εις τον αερα[22:23]{.aside}

εκελευσεν αυτον ο χιλιαρχος αγεσθαι εις την παρεμβολην ειπων μαστιξιν ανεταζεσθαι αυτον ινα επιγνω δι ην αιτιαν ουτως επεφωνουν αυτω[22:24]{.aside}

ως δε [προετεινεν]{.greek-omitted} [προσετεινεν]{.greek-added} αυτον τοις ιμασιν ειπεν προς τον εστωτα εκατονταρχον ο παυλος ει [ανθρωπον]{.greek-abbr} ρωμαιον και ακατακριτον εξεστιν υμιν μαστιζειν[22:25]{.aside}

ακουσας δε ο εκατονταρχος προσελθων [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τω χιλιαρχω λεγων ορα τι μελλεις ποιειν ο γαρ [ανθρωπος]{.greek-abbr} ουτος ρωμαιος εστιν[22:26]{.aside}

προσελθων δε ο χιλιαρχος ειπεν αυτω λεγε μοι [ει]{.greek-omitted} συ ρωμαιος ει ο δε εφη ναι[22:27]{.aside}

απεκριθη τε ο [χιλ[―]{.gap}αρχος]{.greek-added} [χιλιαρχος]{.corr} εγω πολλου κεφαλαιου την πολιτειαν ταυτην εκτησαμην ο δε παυλος εφη εγω δε και γεγεννημαι[22:28]{.aside}

ευθεως ουν απεστησαν απ αυτου οι μελλοντες αυτον ανεταζειν και ο χιλιαρχος δε εφοβηθη επιγνους οτι ρωμαιος εστιν και οτι ην αυτον δεδε[κ]{.unclear}ως[22:29]{.aside}

τη δε επαυριον βουλομενος γνωναι [τ]{.unclear}ο ασφαλες το τι κατηγορειται παρα των ιουδαιων ελυσεν αυτον απο των δεσμων [κ]{.greek-supplied}[αι]{.unclear} εκελευσεν ελθειν τους αρχιερεις και ολον το συνεδριον αυτων και καταγαγων τον παυλον εστησεν εις αυτους[22:30]{.aside}

### Chapter 23

ατενισας δε ο παυλος τω συνεδριω ειπεν ανδρες αδελφοι εγω παση συνειδησει αγαθη πεπολιτευμαι τω [θεω]{.greek-abbr} αχρι ταυτης της ημερας[23:1]{.aside}

ο δε αρχιερευς ανανιας επεταξεν τοις παρεστωσιν αυτω τυπτειν αυτου το στομα[23:2]{.aside}

τοτε ο παυλος προς αυτον ειπεν τυπτειν σε μελλει ο [θεος]{.greek-abbr} τοιχε κεκονιαμενε και συ καθη [κρινων]{.greek-omitted} [κρινον]{.greek-added} με κατα τον νομον και παρανομων κελευεις με τυπτεσθαι[23:3]{.aside}

οι δε παρεστωτες ειπον τον αρχιερεα του [θεου]{.greek-abbr} λοιδορεις[23:4]{.aside}

εφη τε ο παυλος ουκ ηδειν αδελφοι οτι εστιν αρχιερευς γεγραπται γαρ αρχοντα του λαου σου ουκ ερεις κακως[23:5]{.aside}

γνους δε ο παυλος οτι το εν μερος εστιν σαδδουκαιων το δε ετερον φαρισαιων [εκραξεν]{.greek-omitted} [εκραζεν]{.greek-added} εν τω συνεδριω ανδρες αδελφοι εγω φαρισαιος ειμι υιος φαρισαιου περι ελπιδος και αναστασεως νεκρων εγω κρινομαι[23:6]{.aside}

τουτο δε αυτου λαλησαντος εγενετο στασις των φαρισαιων και [των]{.greek-added} [σαδδουκαιων]{.greek-added} [και]{.greek-added} εσχισθη το πληθος[23:7]{.aside}

σαδδουκαιοι μεν γαρ λεγουσιν μη ειναι αναστασιν μηδε αγγελον μητε [πνευμα]{.greek-abbr} φαρισαιοι δε ομολογουσιν τα αμφοτερα[23:8]{.aside}

εγενετο δε κραυγη μεγαλη και ανασταντες οι γραμματεις του μερους των φαρισαιων διεμαχοντο λεγοντες ουδεν κακον [ευρισκομεν]{.greek-omitted} [ευρισκωμεν]{.greek-added} εν τω [ανθρωπω]{.greek-abbr} τουτω ει δε [πνευμα]{.greek-abbr} ελαλησεν αυτω η αγγελος μη θεομαχωμεν[23:9]{.aside}

πολλης δε [γενομενης]{.greek-omitted} [γινο]{.greek-added} [μενης]{.greek-added} στασεως ευλαβηθεις ο χιλιαρχος μη διασπασθη ο παυλος υπ αυτων εκελευσεν το στρατευμα καταβηναι και αρπασαι αυτον εκ μεσου αυτων αγειν τε εις την παρεμβολην[23:10]{.aside}

τη δε επιουση νυκτι επιστας αυτω ο [κυριος]{.greek-abbr} ειπεν θαρσει παυλε ως γαρ διεμαρτυρω τα περι εμου εις [ιερουσαλημ]{.greek-abbr} ουτως σε δει και εις ρωμην μαρτυρησαι[23:11]{.aside}

γενομενης δε ημερας ποιησαντες τινες των ιουδαιων συστροφην ανεθεματισαν εαυτους λεγοντες μητε φαγειν μητε πιειν εως ου [αποκτεινωσιν]{.greek-omitted} [αποκτηνωσι]{.greek-added} τον παυλον[23:12]{.aside}

ησαν δε πλειους τεσσαρακοντα οι ταυτην την συνωμοσιαν πεποιηκοτες[23:13]{.aside}

οιτινες προσελθοντες τοις αρχιερευσιν και τοις πρεσβυτεροις ειπον αναθεματι ανεθεματισαμεν εαυτους μηδενος γευσασθαι εως ου [αποκτεινωμεν]{.greek-omitted} [αποκτηνομεν]{.greek-added} τον παυλον[23:14]{.aside}

νυν ουν υμεις εμφανισατε τω χιλιαρχω συν τω συνεδριω οπως αυριον αυτον καταγαγη προς υμας ως μελλοντας διαγινωσκειν ακριβεστερον τα περι αυτου ημεις δε προ του εγγισαι αυτον ετοιμοι εσμεν του ανελειν αυτον[23:15]{.aside}

ακουσας δε ο [υιος]{.greek-abbr} της αδελφης παυλου το ενεδρον παραγενομενος και εισελθων εις την παρεμβολην απηγγειλεν τω παυλω[23:16]{.aside}

προσκαλεσαμενος δε ο παυλος ενα των εκατονταρχων εφη τον νεανιαν τουτον απαγαγε προς τον χιλιαρχον εχει γαρ τι απαγγειλαι αυτω[23:17]{.aside}

ο μεν ουν παραλαβων αυτον ηγαγεν προς τον χιλιαρχον και φησιν ο δεσμιος παυλος προσκαλεσαμενος με ηρωτησεν τουτον τον νεανιαν αγαγειν προς σε εχοντα τι λαλησαι σοι[23:18]{.aside}

επιλαβομενος δε [της]{.greek-omitted} [χειρος]{.greek-omitted} [αυτου]{.greek-omitted} ο χιλιαρχος και αναχωρησας κατ ιδιαν επυνθανετο τι εστιν ο εχεις [απαγγειλαι]{.greek-omitted} [αναγγειλαι]{.greek-added} μοι[23:19]{.aside}

ειπεν δε οτι οι ιουδαιοι συνεθεντο του ερωτησαι σε οπως αυριον εις το συνεδριον [καταγαγης]{.greek-omitted} [καταγαγεις]{.greek-added} τον παυλον ως μελλοντα τι ακριβεστερον πυνθανεσθαι περι αυτου[23:20]{.aside}

συ ουν μη πεισθης αυτοις ενεδρευουσιν γαρ αυτον εξ αυτων ανδρες πλειους τεσσαρακοντα οιτινες ανεθεματισαν εαυτους μητε φαγειν μητε πιειν εως ου ανελωσιν αυτον και νυν ετοιμοι εισιν προσδεχομενοι την απο σου επαγγελιαν[23:21]{.aside}

ο μεν ουν χιλιαρχος απελυσεν τον νεανιαν παραγγειλας μηδενι εκλαλησαι οτι ταυτα ενεφανισας προς με[23:22]{.aside}

και προσκαλεσαμενος δυο τινας των εκατονταρχων ειπεν ετοιμασατε στρατιωτας διακοσιους οπως πορευθωσιν εως καισαρειας και ιππεις εβδομηκοντα και δεξιολαβους διακοσιους απο τριτης ωρας της νυκτος[23:23]{.aside}

κτηνη τε παραστησαι ινα επιβιβασαντες τον παυλον διασωσωσιν προς [φηλικα]{.greek-omitted} [φιλικα]{.greek-added} τον ηγεμονα[23:24]{.aside}

γραψας επιστολην περιεχουσαν τον τυπον τουτον[23:25]{.aside}

κλαυδιος λυσιας τω κρατιστω ηγεμονι φηλικι χαιρειν[23:26]{.aside}

τον ανδρα τουτον συλληφθεντα υπο των ιουδαιων και μελλοντα αναιρεισθαι υπ αυτων επιστας συν τω στρατευματι [εξειλομην]{.greek-omitted} [εξειλαμην]{.greek-added} [αυτον]{.greek-omitted} μαθων οτι ρωμαιος εστιν[23:27]{.aside}

βουλομενος [δε]{.greek-omitted} [γνωναι]{.greek-omitted} [τε]{.greek-added} [μαθειν]{.greek-added} την αιτιαν δι ην ενεκαλουν αυτω κατηγαγον αυτον εις το συνεδριον αυτων[23:28]{.aside}

ον ευρον εγκαλουμενον περι ζητηματων του νομου αυτων μηδεν [δε]{.greek-added} αξιον θανατου η δεσμων εγκλημα εχοντα[23:29]{.aside}

μηνυθεισης δε μοι επιβουλης εις τον ανδρα [μελλειν]{.greek-omitted} εσεσθαι [υπο]{.greek-omitted} [εξ]{.greek-added} [των]{.greek-omitted} [αυτων]{.greek-added} [ιουδαιων]{.greek-omitted} [εξαυτης]{.greek-omitted} επεμψα προς σε παραγγειλας και τοις κατηγοροις λεγειν τα προς αυτον επι σου ερρωσο[23:30]{.aside}

οι μεν ουν στρατιωται κατα το διατεταγμενον αυτοις αναλαβοντες τον παυλον ηγαγον δια [της]{.greek-omitted} νυκτος εις την αντιπατριδα[23:31]{.aside}

τη δε επαυριον εασαντες τους ιππεις πορευεσθαι συν αυτω υπεστρεψαν εις την παρεμβολην[23:32]{.aside}

οιτινες εισελθοντες εις την καισαρειαν και αναδοντες [[αναγνοντες]{.corr}]{.greek-added} την επιστολην τω ηγεμονι παρεστησαν [αυτω]{.greek-added} και τον παυλον [αυτω]{.greek-omitted}[23:33]{.aside}

αναγνους δε [ο]{.greek-omitted} [ηγεμων]{.greek-omitted} και επερωτησας εκ ποιας επαρχιας [εστιν]{.greek-omitted} [εστι]{.greek-added} και [πυθομενος]{.greek-omitted} [ποιθομενος]{.greek-added} [οτι]{.greek-omitted} απο κιλικιας[23:34]{.aside}

διακουσομαι σου εφη οταν και οι κατηγοροι σου παραγενωνται [κελευσας]{.greek-added} [εκελευσεν]{.greek-omitted} [τε]{.greek-omitted} [αυτον]{.greek-omitted} εν τω πραιτωριω ηρωδου [φυλασσεσθαι]{.greek-omitted} [φυλασεσθαι]{.greek-added} [αυτον]{.greek-added}[23:35]{.aside}

### Chapter 24

μετα δε πεντε ημερας κατεβη [ανανιας]{.greek-added} ο αρχιερευς [ανανιας]{.greek-omitted} μετα [των]{.greek-omitted} πρεσβυτερων [τινων]{.greek-added} και ρητορος τερτυλλου [τινος]{.greek-omitted} οιτινες ενεφανισαν τω ηγεμονι κατα του παυλου[24:1]{.aside}

κληθεντος δε αυτου ηρξατο κατηγορειν ο τερτυλλος λεγων πολλης ειρηνης τυγχανοντες δια σου και [κατορθωματων]{.greek-omitted} [διορθωματων]{.greek-added} γινομενων τω εθνει τουτω δια της σης προνοιας[24:2]{.aside}

παντη τε και πανταχου αποδεχομεθα κρατιστε φηλιξ μετα πασης ευχαριστιας[24:3]{.aside}

ινα δε [μοι]{.greek-added} [μη]{.corr} επι πλειον σε [εγκοπτω]{.greek-omitted} [κοπτω]{.greek-added} παρακαλω ακουσαι σε [συντομως]{.greek-added} ημων [συντομως]{.greek-omitted} τη ση επιεικεια[24:4]{.aside}

ευροντες γαρ τον ανδρα τουτον λοιμον και κινουντα [στασιν]{.greek-omitted} [στασεις]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ιουδαιοις τοις κατα την οικουμενην πρωτοστατην τε της των ναζωραιων αιρεσεως[24:5]{.aside}

ος και το ιερον επειρασεν βεβηλωσαι ον και εκρατησαμεν [και]{.greek-added} [κατα]{.greek-added} [τον]{.greek-added} [ημετερον]{.greek-added} [νομον]{.greek-added} [ηθελησαμεν]{.greek-added} [κριναι]{.greek-added}[24:6]{.aside}

[παρελθων]{.greek-added} [δε]{.greek-added} [λυσιας]{.greek-added} [ο]{.greek-added} [χιλιαρχος]{.greek-added} [μετα]{.greek-added} [πολλης]{.greek-added} [βιας]{.greek-added} [εκ]{.greek-added} [των]{.greek-added} [χειρων]{.greek-added} [ημων]{.greek-added} [απηγαγεν]{.greek-added}[24:7]{.aside}

[κελευσας]{.greek-added} [τους]{.greek-added} [κατηγορους]{.greek-added} [αυτου]{.greek-added} [ερχεσθαι]{.greek-added} [επι]{.greek-added} [σου]{.greek-added} παρ ου [δυνηση]{.greek-omitted} [δυνασαι]{.greek-added} αυτος ανακρινας περι παντων τουτων επιγνωναι ων ημεις κατηγορουμεν αυτου[24:8]{.aside}

συνεπεθεντο δε και οι ιουδαιοι φασκοντες ταυτα ουτως εχειν[24:9]{.aside}

απεκριθη [δε]{.greek-omitted} [τε]{.greek-added} ο παυλος νευσαντος αυτω του ηγεμονος λεγειν εκ πολλων ετων οντα σε κριτην [δικαιον]{.greek-added} τω εθνει τουτω επισταμενος [ευθυμοτερον]{.greek-omitted} [ευθυμως]{.greek-added} τα περι εμαυτου απολογουμαι[24:10]{.aside}

δυναμενου σου [γνωναι]{.greek-omitted} [επιγνωναι]{.greek-added} οτι ου πλειους εισιν μοι ημεραι [δεκαδυο]{.greek-omitted} [δωδεκα]{.greek-added} αφ ης ανεβην προσκυνησων [εν]{.greek-omitted} [εις]{.greek-added} [ιερουσαλημ]{.greek-abbr}[24:11]{.aside}

και ουτε εν τω ιερω ευρον με προς τινα διαλεγομενον η [επισυστασιν]{.greek-omitted} [επιστασιν]{.greek-added} ποιουντα οχλου ουτε εν ταις συναγωγαις ουτε κατα την πολιν[24:12]{.aside}

ουτε παραστησαι [με]{.greek-omitted} δυνανται [σοι]{.greek-added} περι ων [νυν]{.greek-omitted} [νυνι]{.greek-added} κατηγορουσιν μου[24:13]{.aside}

ομολογω δε τουτο σοι οτι κατα την οδον ην λεγουσιν αιρεσιν [ουτως]{.greek-omitted} [ουτω]{.greek-added} λατρευω [πιστευων]{.greek-added} τω [πατρωω]{.greek-omitted} [θεω]{.greek-abbr} [[πατρι]{.greek-abbr}]{.greek-added} πιστευων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις κατα τον νομον και τοις [εν]{.greek-added} [τοις]{.greek-added} προφηταις γεγραμμενοις[24:14]{.aside}

ελπιδα εχων εις τον [θεον]{.greek-abbr} ην και αυτοι ουτοι [προσδεχονται]{.greek-omitted} [εκδεχονται]{.greek-added} αναστασιν [μελλειν]{.greek-omitted} [μελειν]{.greek-added} εσεσθαι νεκρων δικαιων τε και αδικων[24:15]{.aside}

εν τουτω [δε]{.greek-omitted} [και]{.greek-added} αυτος ασκω απροσκοπον συνειδησιν [εχων]{.greek-omitted} [εχειν]{.greek-added} προς τον [θεον]{.greek-abbr} και τους [ανθρωπους]{.greek-abbr} [δια]{.greek-omitted} [παντος]{.greek-omitted}[24:16]{.aside}

δι ετων δε πλειονων [παρεγενομην]{.greek-omitted} ελεημοσυνας ποιησων εις το εθνος μου [παρεγενομην]{.greek-added} και προσφορας[24:17]{.aside}

εν [οις]{.greek-omitted} [αις]{.greek-added} ευρον [με]{.greek-omitted} ηγνισμενον εν τω ιερω ου μετα οχλου ουδε μετα θορυβου [τινες]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ασιας]{.greek-omitted} [ιουδαιοι]{.greek-omitted}[24:18]{.aside}

[τινες]{.greek-added} [δε]{.greek-added} [των]{.greek-added} [απο]{.greek-added} [της]{.greek-added} [ασιας]{.greek-added} [ιουδαιων]{.greek-added} ους [δει]{.greek-omitted} [εδει]{.greek-added} επι σου παρειναι και κατηγορειν ει τι εχοιεν προς με[24:19]{.aside}

η αυτοι ουτοι ειπατωσαν τι ευρον εν εμοι αδικημα σταντος μου επι του συνεδριου[24:20]{.aside}

η περι μιας [φωνης]{.greek-added} ταυτης [φωνης]{.greek-omitted} ης [εκραξα]{.greek-omitted} [εκεκραξα]{.greek-added} [εστως]{.greek-omitted} εν αυτοις [εστως]{.greek-added} οτι περι αναστασεως νεκρων εγω κρινομαι σημερον υφ υμων[24:21]{.aside}

[ακουσας]{.greek-omitted} [ανεβαλετο]{.greek-added} δε [ταυτα]{.greek-omitted} ο φηλιξ [ανεβαλετο]{.greek-omitted} αυτους ακριβεστερον ειδως τα περι της οδου ειπων [οτι]{.greek-added} οταν λυσιας ο χιλιαρχος καταβη διαγνωσομαι τα καθ υμας[24:22]{.aside}

διαταξαμενος [τε]{.greek-omitted} τω εκατονταρχη τηρεισθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} εχειν τε ανεσιν και μηδενα κωλυειν των ιδιων αυτου υπηρετειν [η]{.greek-omitted} [προσερχεσθαι]{.greek-omitted} αυτω[24:23]{.aside}

μετα δε ημερας τινας παραγενομενος ο φηλιξ συν δρουσιλλη τη γυναικι ουση ιουδαια μετεπεμψατο τον παυλον και ηκουσεν αυτου περι της εις [τον]{.greek-added} [χριστον]{.greek-abbr} πιστεως[24:24]{.aside}

διαλεγομενου δε αυτου περι δικαιοσυνης και εγκρατειας και του κριματος του μελλοντος [εσεσθαι]{.greek-omitted} εμφοβος γενομενος ο φηλιξ απεκριθη το νυν εχον πορευου καιρον δε μεταλαβων [μετακαλεσομαι]{.greek-omitted} [μετακαλεσο]{.greek-added} [μαι]{.greek-added} σε[24:25]{.aside}

αμα και ελπιζων οτι χρηματα δοθησεται αυτω υπο του παυλου [οπως]{.greek-omitted} [λυση]{.greek-omitted} [αυτον]{.greek-omitted} διο και πυκνοτερον αυτον με[τ]{.unclear}απεμπομενος [ωμιλει]{.greek-omitted} [ομιλει]{.greek-added} αυτω[24:26]{.aside}

διετιας δε πληρωθεισης ελαβεν διαδοχον ο φηλιξ πορκιον φηστον θελων [τε]{.greek-omitted} [χαριτας]{.greek-omitted} [δε]{.greek-added} [χαριν]{.greek-added} καταθεσθαι τοις ιουδαιοις ο φηλιξ [κατελιπεν]{.greek-omitted} [κατελιπε]{.greek-added} τον παυλον δεδεμενον[24:27]{.aside}

### Chapter 25

φηστος ουν επιβας τη επαρχια μετα τρεις ημερας ανεβη εις ιεροσολυμα απο καισαρειας[25:1]{.aside}

[ενεφανισαν]{.greek-omitted} [ανεφανισαν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} αυτω [ο]{.greek-omitted} [οι]{.greek-added} [αρχιερευς]{.greek-omitted} [αρχιερεις]{.greek-added} και οι πρωτοι των ιουδαιων κατα του παυλου και παρεκαλουν αυτον[25:2]{.aside}

αιτουμενοι χαριν κατ αυτου οπως μεταπεμψηται αυτον εις ιερουσαλημ [ενεδραν]{.greek-omitted} [ενεδρον]{.greek-added} ποιουντες ανελειν αυτον κατα την οδον[25:3]{.aside}

ο μεν ουν φηστος απεκριθη τηρεισθαι τον παυλον εν καισαρεια εαυτον δε μελλειν εν ταχει εκπορευεσθαι[25:4]{.aside}

οι ουν δυνατοι εν υμιν φησιν συγκαταβαντες ει τι εστιν εν τω ανδρι τουτω [ατοπον]{.greek-added} κατηγορειτωσαν αυτου[25:5]{.aside}

διατριψας δε εν αυτοις ημερας πλειους η δεκα καταβας εις καισαρειαν τη επαυριον καθισας επι του βηματος [εκελευσεν]{.greek-omitted} [εκελευσε]{.greek-added} τον παυλον αχθηναι[25:6]{.aside}

παραγενομενου δε αυτου περιεστησαν οι απο ιεροσολυμων καταβεβηκοτες ιουδαιοι πολλα και [βαρεα]{.greek-omitted} [βαραια]{.greek-added} αιτιωματα [φεροντες]{.greek-omitted} [καταφεροντες]{.greek-added} [κατα]{.greek-omitted} του παυλου α ουκ ισχυον αποδειξαι[25:7]{.aside}

απολογουμενου αυτου οτι ουτε εις τον νομον των ιουδαιων ουτε εις το ιερον ουτε εις καισαρα τι ημαρτον[25:8]{.aside}

ο φηστος δε [θελων]{.greek-added} τοις ιουδαιοις [θελων]{.greek-omitted} χαριν [κατα]{.greek-added} [καταθεσθαι]{.greek-omitted} [θεσθαι]{.greek-added} αποκριθεις [δε]{.greek-added} τω παυλω ειπεν θελεις εις ιεροσολυμα αναβας εκει περι τουτων [κρινεσθαι]{.greek-omitted} [κριθηναι]{.greek-added} επ εμου[25:9]{.aside}

ειπεν δε ο παυλος επι του βηματος καισαρος εστως ειμι ου με δει κρινεσθαι ιουδαιους ουδεν ηδικησα ως και συ [καλλιον]{.greek-omitted} [καλιον]{.greek-added} επιγινωσκεις[25:10]{.aside}

ει μεν γαρ αδικω και αξιον θανατου πεπραχα τι ου παραιτουμαι [το]{.greek-omitted} αποθανειν ει δε ουδεν εστιν ων ουτοι [κατηγορουσιν]{.greek-omitted} [κατοιγορουσι]{.greek-added} μου ουδεις με δυναται αυτοις χαρισασθαι καισαρα επικαλουμαι[25:11]{.aside}

τοτε ο φηστος συλλαλησας μετα του συμβουλιου απεκριθη καισαρα επικεκλησαι επι καισαρα πορευση[25:12]{.aside}

ημερων δε διαγενομενων τινων [αγριππας]{.greek-omitted} [αγριπας]{.greek-added} ο βασιλευς και βερνικη κατηντησαν εις καισαρειαν [ασπασαμενοι]{.greek-omitted} [ασπασομενοι]{.greek-added} τον φηστον[25:13]{.aside}

ως δε πλειους ημερας [διετριβεν]{.greek-omitted} [διετριβον]{.greek-added} εκει ο φηστος τω βασιλει ανεθετο τα κατα τον παυλον λεγων ανηρ τις [εστιν]{.greek-omitted} [εστι]{.greek-added} καταλελειμμενος υπο φηλικος δεσμιος[25:14]{.aside}

περι ου γενομενου μου εις ιεροσολυμα [ενεφανισαν]{.greek-omitted} [ανεφανισαν]{.greek-added} οι αρχιερεις και οι πρεσβυτεροι των ιουδαιων αιτουμενοι κατ αυτου δικην[25:15]{.aside}

προς ους απεκριθην οτι ουκ εστιν εθος ρωμαιοις χαριζεσθαι τινα ανθρωπον [εις]{.greek-omitted} [απωλειαν]{.greek-omitted} πριν η ο κατηγορουμενος κατα προσωπον εχοι τους κατηγορους τοπον [τε]{.greek-omitted} [δε]{.greek-added} απολογιας λαβοι περι του εγκληματος[25:16]{.aside}

συνελθοντων ουν αυτων ενθαδε αναβολην μηδεμιαν ποιησαμενος τη εξης καθισας επι του βηματος εκελευσα αχθηναι τον ανδρα[25:17]{.aside}

περι ου σταθεντες οι κατηγοροι ουδεμιαν αιτιαν [επεφερον]{.greek-omitted} [εφερον]{.greek-added} ων υπενοουν εγω [πονηραν]{.greek-added}[25:18]{.aside}

ζητηματα δε τινα περι της ιδιας [δεισιδαιμονιας]{.greek-omitted} ειχον προς αυτον και περι τινος [ιησου]{.greek-abbr} τεθνηκοτος ον εφασκεν ο παυλος ζην[25:19]{.aside}

απορουμενος δε εγω [εις]{.greek-added} την περι [τουτου]{.greek-omitted} [τουτων]{.greek-added} ζητησιν ελεγον ει βουλοιτο πορευεσθαι εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} κακει [κρινεσθαι]{.greek-omitted} [κρινεσσθαι]{.greek-added} περι τουτων[25:20]{.aside}

του δε παυλου [επικαλεσαμενου]{.greek-omitted} [επικαλουμενου]{.greek-added} τηρηθηναι αυτον εις την του σεβαστου διαγνωσιν εκελευσα τηρεισθαι αυτον εως ου [πεμψω]{.greek-omitted} [αναπεμψω]{.greek-added} αυτον προς καισαρα[25:21]{.aside}

αγριππας δε προς τον φηστον εφη εβουλομην και αυτος του [ανθρωπου]{.greek-abbr} ακουσαι ο δε αυριον φησιν ακουση αυτου[25:22]{.aside}

τη ουν επαυριον ελθοντος του αγριππα και της βερνικης μετα [πολλης]{.greek-omitted} [πολης]{.greek-added} φαντασιας και εισελθοντων εις το [ακροατηριον]{.greek-omitted} [ακροτηριον]{.greek-added} συν τε [τοις]{.greek-omitted} χιλιαρχοις και [ανδρασιν]{.greek-omitted} [ανδρασι]{.greek-added} τοις κατ εξοχην [ουσιν]{.greek-omitted} [ουσι]{.greek-added} της πολεως και κελευσαντος του φηστου ηχθη ο παυλος[25:23]{.aside}

και φησιν ο φηστος αγριππα βασιλευ και παντες οι συμπαροντες ημιν ανδρες θεωρειτε τουτον περι [τουτου]{.greek-added} [ου]{.corr} [παν]{.greek-omitted} [απαν]{.greek-added} το πληθος των ιουδαιων ενετυχον μοι εν τε ιεροσολυμοις και ενθαδε επιβοωντες μη δ[ει]{.unclear}ν ζην αυτον μηκετι[25:24]{.aside}

εγω δε καταλαβομενος μηδεν αξιον θανατου [πεπραχεναι]{.greek-added} αυτον [πεπραχεναι]{.greek-omitted} και αυτου δε τουτου επικαλεσαμενου τον σεβαστον εκρινα πεμπειν αυτον[25:25]{.aside}

περι ου ασφαλες τι γραψαι τω [κυριω]{.greek-abbr} ουκ εχω διο προηγαγον αυτον εφ υμων και μαλιστα επι σου βασιλευ αγριππα οπως της ανακρισεως γενομενης [σχω]{.greek-omitted} [εχω]{.greek-added} τι [γραψαι]{.greek-omitted} [γραψω]{.greek-added}[25:26]{.aside}

αλογον γαρ [δοκει]{.greek-added} μοι [δοκει]{.greek-omitted} πεμποντα δεσμιον μη και τας κατ αυτου αιτιας σημαναι[25:27]{.aside}

### Chapter 26

αγριππας δε προς τον παυλον εφη [επιτρεπεται]{.greek-omitted} [επιτετραπται]{.greek-added} σοι [λεγειν]{.greek-added} υπερ σεαυτου [λεγειν]{.greek-omitted} τοτε ο παυλος [απελογειτο]{.greek-omitted} [απολογειτο]{.greek-added} εκτεινας την χειρα[26:1]{.aside}

περι παντων ων εγκαλουμαι υπο ιουδαιων βασιλευ αγριππα ηγημαι εμαυτον μακαριον επι σου μελλων απολογεισθαι σημερον[26:2]{.aside}

μαλιστα γνωστην οντα σε παντων [ειδως]{.greek-added} των κατα ιουδαιους [εθνων]{.greek-added} [ηθων]{.greek-omitted} [[εθων]{.corr}]{.greek-added} τε και ζητηματων διο δεομαι [σου]{.greek-omitted} μακροθυμως ακουσαι μου[26:3]{.aside}

την μεν ουν βιωσιν μου την εκ νεοτητος την απ αρχης γενομενην εν τω εθνει μου εν ιεροσολυμοις [ισασιν]{.greek-omitted} [ισασι]{.greek-added} παντες οι ιουδαιοι[26:4]{.aside}

προγινωσκοντες με ανωθεν εαν [θελωσιν]{.greek-omitted} [θελωσι]{.greek-added} μαρτυρειν οτι κατα την ακριβεστατην αιρεσιν της ημετερας θρησκειας εζησα φαρισαιος[26:5]{.aside}

και νυν επ ελπιδι της προς τους [πατερας]{.greek-abbr} [ημων]{.greek-added} επαγγελιας γενομενης υπο του [θεου]{.greek-abbr} εστηκα κρινομενος[26:6]{.aside}

εις ην το δωδεκαφυλον ημων εν [εκτενεια]{.greek-omitted} [εκτενια]{.greek-added} νυκτα και ημεραν λατρευον ελπιζει [καταντησαι]{.greek-omitted} [καταν]{.greek-added} [τησαι]{.greek-added} περι ης ελπιδος εγκαλουμαι [υπο]{.greek-added} [ιουδαιων]{.greek-added} βασιλευ αγριππα [υπο]{.greek-omitted} [ιουδαιων]{.greek-omitted}[26:7]{.aside}

τι απιστον κρινεται παρ υμιν ει ο [θεος]{.greek-abbr} νεκρους εγειρει[26:8]{.aside}

εγω μεν ουν εδοξα εμαυτω προς το ονομα [ιησου]{.greek-abbr} του ναζωραιου δειν πολλα εναντια πραξαι[26:9]{.aside}

ο και εποιησα εν ιεροσολυμοις και πολλους των αγιων εγω φυλακαις κατεκλεισα την παρα των αρχιερεων εξουσιαν λαβων αναιρουμενων [τε]{.greek-omitted} [δε]{.greek-added} αυτων κατηνεγκα ψηφον[26:10]{.aside}

και κατα πασας τας συναγωγας πολλακις τιμωρων αυτους ηναγκαζον βλασφημειν περισσως τε [εμμαινομενος]{.greek-omitted} [εμμενομενος]{.greek-added} αυτοις εδιωκον εως και εις τας εξω πολεις[26:11]{.aside}

εν οις [και]{.greek-omitted} πορευομενος εις την δαμασκον μετ εξουσιας και επιτροπης της παρα των αρχιερεων[26:12]{.aside}

ημερας μεσης κατα την οδον ειδον βασιλευ [ουρανοθεν]{.greek-omitted} [ουνοθεν]{.greek-added} υπερ την λαμπροτητα του ηλιου περιλαμψαν με φως και τους συν εμοι πορευομενους[26:13]{.aside}

παντων [δε]{.greek-omitted} [τε]{.greek-added} καταπεσοντων [ημων]{.greek-omitted} εις την γην ηκουσα φωνην λαλουσαν προς με και λεγουσαν τη εβραιδι [διαλεκτω]{.greek-omitted} σαουλ σαουλ τι με διωκεις σκληρον σοι προς κεντρα λακτιζειν[26:14]{.aside}

εγω δε ειπον τις ει [κυριε]{.greek-abbr} ο δε ειπεν εγω ειμι [ιησους]{.greek-abbr} ον συ διωκεις[26:15]{.aside}

αλλα αναστηθι και στηθι επι τους ποδας σου εις τουτο γαρ [ωφθην]{.greek-omitted} [ωφθειν]{.greek-added} σοι προχειρισασθαι σε υπηρετην και μαρτυρα ων τε ειδες [με]{.greek-added} ων τε οφθησομαι σοι[26:16]{.aside}

εξαιρουμενος σε εκ του λαου και των εθνων εις ους εγω [αποστελῶ]{.greek-added} σε [αποστελλω]{.greek-omitted}[26:17]{.aside}

ανοιξαι οφθαλμους αυτων του [υποστρεψαι]{.greek-omitted} [αποστρεψαι]{.greek-added} απο σκοτους εις φως και [απο]{.greek-added} της εξουσιας του σατανα επι τον [θεον]{.greek-abbr} του λαβειν αυτους αφεσιν αμαρτιων και κληρον εν τοις ηγιασμενοις πιστει τη εις εμε[26:18]{.aside}

οθεν βασιλευ αγριππα ουκ εγενομην απειθης τη [ουρανιω]{.greek-abbr} οπτασια[26:19]{.aside}

αλλα τοις εν δαμασκω πρωτον και [εν]{.greek-added} ιεροσολυμοις εις πασαν τε την χωραν της ιουδαιας και τοις εθνεσιν [απαγγελλων]{.greek-omitted} [απηγγελλον]{.greek-added} μετανοειν και επιστρεφειν επι τον [θεον]{.greek-abbr} αξια της μετανοιας εργα πρασσοντας[26:20]{.aside}

ενεκα τουτων [με]{.greek-added} οι ιουδαιοι [με]{.greek-omitted} [συλλαβομενοι]{.greek-omitted} [συλαβομενοι]{.greek-added} [οντες]{.greek-added} εν τω ιερω επειρωντο διαχειρισασθαι[26:21]{.aside}

[ε]{.unclear}πικουριας ουν τυχων της παρα του [θεου]{.greek-abbr} αχρι της ημερας ταυτης εστηκα μαρτυρομενος μικρω τε και μεγαλω ουδεν εκτος λεγων ων τε οι προφηται ελαλησαν μελλοντων γινεσθαι και μωυσης[26:22]{.aside}

ει παθ[η]{.greek-supplied}τος ο [χριστος]{.greek-abbr} ει πρωτος εξ αναστασεως νεκρων φως μελλει [καταγγελλειν]{.greek-omitted} [καταγγέλειν]{.greek-added} τω [τε]{.greek-added} λαω και τοις εθνεσιν[26:23]{.aside}

ταυτα δε αυτου απολογουμενου [ο]{.unclear} φηστος μεγαλη τη φωνη εφη μαινη παυλε τα πολλα σε γραμματα εις μανιαν περιτρεπει[26:24]{.aside}

ο δε ου μαινομαι φησιν [κ]{.unclear}ρατιστε φηστε [αλλα]{.greek-omitted} [αλλ]{.greek-added} αληθειας και [σωφροσυνης]{.greek-omitted} [σοφροσυνης]{.greek-added} ρηματα αποφθεγγομαι[26:25]{.aside}

επισταται γαρ περι τουτων ο βασιλευς προς ον και παρρησιαζομενος λαλω [λανθανειν]{.greek-omitted} [λαθειν]{.greek-added} γαρ αυτον [τι]{.greek-omitted} τουτων ου πειθομαι ουδεν [ου]{.greek-omitted} [ουδε]{.greek-added} γ[αρ]{.unclear} [εστιν]{.greek-added} εν γωνια πεπραγμενον τουτο[26:26]{.aside}

πιστευεις βασιλευ αγριππα τοις προφηταις οιδα οτι πιστευεις[26:27]{.aside}

ο δε [αγριπας]{.greek-added} [αγριππας]{.corr} προς τον παυλον [εφη]{.greek-omitted} εν ολιγω με [πειθεις]{.greek-omitted} [πεισθεις]{.greek-added} χριστιανον [γενεσθαι]{.greek-omitted} [ποιησαι]{.greek-added}[26:28]{.aside}

ο δε παυλος [ειπεν]{.greek-omitted} ευξαιμην αν τω [θεω]{.greek-abbr} και εν ολιγω και εν πολλω ου μονον σε αλλα και παντας τους ακουοντας μου σημερον γενεσθαι τοιουτους οποιος καγω ειμι [παρεκτος]{.greek-omitted} [παρεκτως]{.greek-added} των δεσμων τουτων[26:29]{.aside}

[και]{.greek-omitted} [ταυτα]{.greek-omitted} [ειποντος]{.greek-omitted} [αυτου]{.greek-omitted} ανεστη [τε]{.greek-added} ο βασιλευς και ο ηγεμων η τε βερνικη και [παντες]{.greek-added} οι συγκαθημενοι αυτοις[26:30]{.aside}

και αναχωρησαντες ελαλουν προς αλληλους λεγοντες οτι ουδεν [αξιον]{.greek-added} θανατου [αξιον]{.greek-omitted} η δεσμων πρασσει ο [ανθρωπος]{.greek-abbr} ουτος[26:31]{.aside}

αγριππας δε τω φηστω εφη [απολελυσθαι]{.greek-omitted} [απολυεσθαι]{.greek-added} εδυνατο ο [ανθρωπος]{.greek-abbr} ουτος ει μη [επεκεκλητο]{.greek-omitted} [επικεκλητο]{.greek-added} καισαρα[26:32]{.aside}

### Chapter 27

ως δε εκριθη του αποπλειν ημας εις [την]{.greek-omitted} ιταλιαν παρεδιδουν τον τε παυλον και τινας [ετερους]{.greek-omitted} [δ]{.unclear}εσμωτας [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} ονοματι ιουλιω σπειρης σεβαστης[27:1]{.aside}

επιβαντες δε πλοιω αδραμυττηνω [μελλοντες]{.greek-omitted} [μελλοντι]{.greek-added} πλειν [επι]{.greek-added} τους κατα την ασιαν τοπους ανηχθημεν οντος συν ημιν αρισταρχου μακεδονος [θεσσαλονικεως]{.greek-omitted} [θεσσαλονικεσως]{.greek-added}[27:2]{.aside}

τη τε ετερα κατηχθημεν εις σιδωνα φιλανθρωπως τε ο ιουλιος τω παυλω χρησαμενος επετρεψεν προς τους φιλους πορευθεντα επιμελειας τυχειν[27:3]{.aside}

κακειθεν αναχθεντες υπεπλευσαμεν την κυπρον δια το τους ανεμους ειναι εναντιους[27:4]{.aside}

το τε πελαγος το κατα την κιλικιαν και παμφυλιαν διαπλευσαντες κατηλθομεν εις μυρα της λυκιας[27:5]{.aside}

κακει ευρων ο εκατονταρχος πλοιον αλεξανδρινον πλεον εις την ιταλιαν [ενεβιβασεν]{.greek-omitted} [ανεβιβασεν]{.greek-added} ημας εις αυτο[27:6]{.aside}

εν ικαναις δε ημεραις βραδυπλοουντες και μολις γενομενοι κατα την κνιδον μη προσεωντος ημας του ανεμου υπεπλευσαμεν την κρητην κατα σαλμωνην[27:7]{.aside}

μολις τε [παραλεγομενοι]{.greek-omitted} [παραναλεγομενοι]{.greek-added} αυτην [ηλθομεν]{.greek-omitted} [ηκομεν]{.greek-added} εις τοπον τινα καλουμενον καλους λιμενας ω εγγυς ην πολις [λασαια]{.greek-omitted} [λασεα]{.greek-added}[27:8]{.aside}

ικανου δε χρονου διαγενομενου και οντος ηδη [επισφαλους]{.greek-omitted} του πλοος [επισφαλους]{.greek-added} δια το και την νηστειαν ηδη παρεληλυθεναι παρηνει ο παυλος[27:9]{.aside}

λεγων αυτοις ανδρες θεωρω οτι μετα υβρεως και πολλης ζημιας ου μονον του φορτιου και του πλοιου αλλα και των ψυχων ημων μελλειν εσεσθαι τον πλουν[27:10]{.aside}

ο δε [εκατονταρχης]{.greek-omitted} [εκατονταρχος]{.greek-added} τω κυβερνητη και τω ναυκληρω επειθετο μαλλον η τοις υπο του παυλου λεγομενοις[27:11]{.aside}

ανευθετου δε του λιμενος υπαρχοντος προς παραχειμασιαν οι πλειους εθεντο βουλην αναχθηναι [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} ει πως δυναιντο καταντησαντες εις φοινικα παραχειμασαι λιμενα της κρητης βλεποντα κατα λιβ[α]{.unclear} και κατα [χωρον]{.greek-omitted} [χωραν]{.greek-added}[27:12]{.aside}

υποπνευσαντος δε νοτου δοξαντες της προθεσεως κεκρατηκεναι αραντες ασσον [παρελεγοντο]{.greek-omitted} [παρελεγομεν]{.greek-added} την [κρητην]{.greek-omitted} [κριτην]{.greek-added}[27:13]{.aside}

μετ ου πολυ δε εβαλεν κατ αυτης ανεμος [τ]{.unclear}υφωνικος ο καλουμενος ευροκλυδων[27:14]{.aside}

συναρπασθεντος δε του πλοιου και μη δυναμενου αντοφθαλμειν τω ανεμω επιδοντες εφερομεθα[27:15]{.aside}

νησιον δε τι [υποδραμοντες]{.greek-omitted} [επιδραμοντες]{.greek-added} καλουμενον κλαυδην [ισχυσαμεν]{.greek-added} μολις [ισχυσαμεν]{.greek-omitted} περικρατεις γενεσθαι της σκαφης[27:16]{.aside}

ην αραντες βοηθειαις [εχ[θ]{.unclear}ρωντο]{.greek-added} [εχρωντο]{.corr} υποζωννυντες το πλοιον φοβουμενοι τε μη εις την συρτην εκπεσωσιν χαλασαντες το σκευος ουτως εφεροντο[27:17]{.aside}

σφοδρως [δε]{.greek-omitted} [τε]{.greek-added} χειμαζομενων ημων τη εξης εκβολην εποιουντο[27:18]{.aside}

και τη τριτη αυτοχειρες την σκευην του πλοιου ερριψαμεν[27:19]{.aside}

μητε δε ηλιου μητε αστρων επιφαινοντων επι πλειονας ημερας [χειμωνος]{.greek-omitted} [χειμονος]{.greek-added} τε ουκ ολιγου επικειμενου λοιπον περιηρειτο πασα ελπις του σωζεσθαι ημας[27:20]{.aside}

πολλης [δε]{.greek-omitted} [τε]{.greek-added} [ασιτιας]{.greek-omitted} [ασιτειας]{.greek-added} υπαρχουσης τοτε σταθεις ο παυλος εν μεσω αυτων ειπεν εδει μεν ω ανδρες πειθαρχησαντας μοι μη [αναγεσθαι]{.greek-omitted} [αναγαγεσθαι]{.greek-added} απο της κρητης κερδησαι τε την υβριν ταυτην και την ζημιαν[27:21]{.aside}

και τα νυν [παραινω]{.greek-omitted} [παρενω]{.greek-added} υμας ευθυμειν αποβολη γαρ ψυχης ουδεμια εσται εξ υμων πλην του πλοιου[27:22]{.aside}

παρεστη γαρ μοι ταυτη τη νυκτι [αγγελος]{.greek-omitted} του [θεου]{.greek-abbr} ου ειμι ω και λατρευω [αγγελος]{.greek-added}[27:23]{.aside}

λεγων μη φοβου παυλε καισαρι σε δει παραστηναι και ιδου κεχαρισται σοι ο [θεος]{.greek-abbr} παντας τους πλεοντας μετα σου[27:24]{.aside}

διο ευθυμειτε ανδρες πιστευω γαρ τω [θεω]{.greek-abbr} οτι ουτως εσται καθ ον τροπον [λελαληται]{.greek-omitted} [ελαληται]{.greek-added} μοι[27:25]{.aside}

ως δε τεσσαρεσκαιδεκατη νυξ εγενετο διαφερομενων ημων εν τω αδρια κατα μεσον της νυκτος υπενοουν οι ναυται προσαγειν τινα αυτοις χωραν[27:27]{.aside}

και βολισαντες ευρον [οργυιας]{.greek-omitted} [οργυας]{.greek-added} εικοσι βραχυ δε διαστησαντες και παλιν βολισαντες ευρον [οργυιας]{.greek-omitted} [οργυας]{.greek-added} δεκαπεντε[27:28]{.aside}

φοβουμενοι [τε]{.greek-omitted} [δε]{.greek-added} μηπως εις τραχεις τοπους [εκπεσωμεν]{.greek-omitted} [εκπεσωσιν]{.greek-added} εκ πρυμνης ριψαντες αγκυρας τεσσαρας ηυχοντο ημεραν γενεσθαι[27:29]{.aside}

των δε ναυτων ζητουντων φυγειν εκ του πλοιου και χαλασαντων την σκαφην εις την θαλασσαν προφασει ως εκ πρωρας μελλοντων αγκυρας εκτεινειν[27:30]{.aside}

ειπεν ο παυλος τω [εκατονταρχη]{.greek-omitted} [εκατονταρχω]{.greek-added} και τοις στρατιωταις εαν μη ουτοι [μεινωσιν]{.greek-omitted} εν τω πλοιω [μεινωσιν]{.greek-added} υμεις σωθηναι ου δυνασθε[27:31]{.aside}

τοτε [απεκοψαν]{.greek-added} οι στρατιωται [απεκοψαν]{.greek-omitted} τα σχοινια της σκαφης και ειασαν αυτην εκπεσειν[27:32]{.aside}

αχρι δε ου [ημελλεν]{.greek-omitted} [ημελεν]{.greek-added} ημερα γινεσθαι παρεκαλει ο παυλος [απαντας]{.greek-omitted} μεταλαβειν τροφης λεγων τεσσαρεσκαιδεκατην σημερον ημεραν προσδοκωντες ασιτοι διατελειτε μηδεν προσλαβομενοι[27:33]{.aside}

διο παρακαλω υμας προσλαβειν [τινος]{.greek-added} τροφης τουτο γαρ [προς]{.greek-omitted} [προ]{.greek-added} της [ημερας]{.greek-added} [υμετερας]{.greek-omitted} [[ημετερας]{.corr}]{.greek-added} [σωτηριας]{.greek-abbr} υπαρχει ουδενος γαρ υμων θριξ εκ της κεφαλης [πεσειται]{.greek-omitted} [εκπεσειται]{.greek-added}[27:34]{.aside}

ειπων δε ταυτα και λαβων αρτον ευχαριστησεν τω [θεω]{.greek-abbr} ενωπιον παντων και κλασας ηρξατο εσθιειν[27:35]{.aside}

ευθυμοι δε γενομενοι παντες και αυτοι προσελαβοντο τροφης[27:36]{.aside}

ημεν δε [αι]{.greek-added} [πασαι]{.greek-added} [ψυχαι]{.greek-added} εν τω πλοιω [[σος]{.greek-abbr}]{.greek-added} [αι]{.greek-omitted} [πασαι]{.greek-omitted} [ψυχαι]{.greek-omitted} [διακοσιαι]{.greek-omitted} [εβδομηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[27:37]{.aside}

κορεσθεντες δε [της]{.greek-omitted} τροφης εκουφιζον το πλοιον εκβαλλομενοι τον σιτον εις την θαλασσαν[27:38]{.aside}

οτε δε ημερα εγενετο την γην ουκ επεγινωσκον κολπον δε τινα κατενοουν εχοντα αιγιαλον εις ον εβουλευσαντο ει [δυνατον]{.greek-omitted} [δυναιντο]{.greek-added} εξωσαι το πλοιον[27:39]{.aside}

και τας αγκυρας περιελοντες ειων εις την θαλασσαν αμα ανεντες τας ζευκτηριας των πηδαλιων και επαραντες τον [αρτεμονα]{.greek-omitted} [αρτεμωνα]{.greek-added} τη πνεουση κατειχον εις τον αιγιαλον[27:40]{.aside}

περιπεσοντες δε εις τοπον διθαλασσον [επ[ε]{.unclear}κλειναν]{.greek-added} [επωκειλαν]{.greek-omitted} [επωκιλαν]{.greek-added} την ναυν και η μεν πρωρα ερεισασα [εμεινεν]{.greek-omitted} [εμενεν]{.greek-added} ασαλευτος η δε πρυμνα ελυετο υπο της βιας των κυματων[27:41]{.aside}

των δε στρατιωτων βουλη εγενετο ινα τους δεσμωτας [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} μη τις εκκολυμβησας διαφυγη[27:42]{.aside}

ο δε εκατονταρχος βουλομενος διασωσαι τον παυλον εκωλυσεν αυτους του βουληματος εκελευσεν τε τους δυναμενους κολυμβαν απορριψαντας πρωτους επι την γην εξιεναι[27:43]{.aside}

και τους λοιπους ους μεν επι σανισιν ους δε επι τινων των απο του πλοιου και ουτως εγενετο παντας διασωθηναι επι την γην[27:44]{.aside}

### Chapter 28

και διασωθεντες τοτε επεγνωσαν οτι μελιτη η νησος καλειται[28:1]{.aside}

οι [δε]{.greek-omitted} [τε]{.greek-added} βαρβαροι παρειχον ου την τυχουσαν [φιλανθρωπιαν]{.greek-omitted} [[φιλανιαν]{.greek-abbr}]{.greek-added} ημιν [αναψαντες]{.greek-omitted} [αψαντες]{.greek-added} γαρ πυραν προσελαβοντο παντας ημας δια τον υετον τον εφεστωτα και δια το ψυχος[28:2]{.aside}

συστρεψαντος δε του παυλου φρυγανων πληθος και επιθεντος επι την πυραν εχιδνα [εκ]{.greek-omitted} [απο]{.greek-added} της θερμης διεξελθουσα [καθηψεν]{.greek-omitted} [καθηψε]{.greek-added} της χειρος αυτου[28:3]{.aside}

ως δε ειδον οι βαρβαροι [κρεμαμενον]{.greek-omitted} το θηριον [κρεμαμενον]{.greek-added} εκ της χειρος αυτου [ελεγον]{.greek-omitted} προς αλληλους [ελεγον]{.greek-added} παντως φονευς εστιν ο [ανθρωπος]{.greek-abbr} ουτος ον διασωθεντα εκ της θαλασσης η δικη ζην ουκ ειασεν[28:4]{.aside}

ο μεν ουν αποτιναξας το θηριον εις το πυρ [επαθεν]{.greek-omitted} [επασχεν]{.greek-added} ουδεν [κακον]{.greek-omitted} [πονηρον]{.greek-added}[28:5]{.aside}

οι δε προσεδοκων αυτον μελλειν πιμπρασθαι η καταπιπτειν αφνω νεκρον επι πολυ δε αυτων προσδοκωντων και [θεωρουντων]{.greek-omitted} [θεωρησαντων]{.greek-added} [μηδεν]{.greek-omitted} [μηδε]{.greek-added} ατοπον εις αυτον [γενομενον]{.greek-added} [γινομενον]{.corr} μεταβαλλομενοι ελεγον [θεον]{.greek-abbr} αυτον ειναι[28:6]{.aside}

εν δε τοις περι τον τοπον εκεινον [υπηρχεν]{.greek-omitted} [[υ]{.unclear}πηρχε]{.greek-added} χωρια τω πρωτω της νησου ονομ[α]{.unclear}τι π[ο]{.unclear}πλιω ο[ς]{.unclear} αναδεξαμενος ημας τρεις ημερας φιλοφρονως [εξενισεν]{.greek-omitted} [εξενησεν]{.greek-added}[28:7]{.aside}

εγενετο δε τον [πατερα]{.greek-abbr} του ποπλιου πυρετοις και δυσεντερια συνεχομενον κατακεισθαι προς ον ο παυλος εισελθων και προσευξαμενος [επιθεις]{.greek-omitted} [επιθεισθε]{.greek-added} τας χειρας αυτω ιασατο αυτον[28:8]{.aside}

τουτου [ουν]{.greek-omitted} [δε]{.greek-added} γενομενου και οι λοιποι οι εχοντες [ασθενειας]{.greek-omitted} [ασθενεις]{.greek-added} εν τη νησω προσηρχοντο και εθεραπευοντο[28:9]{.aside}

οι και πολλαις τιμαις ετιμησαν ημας και αναγομενοις επεθεντο τα προς την χρειαν[28:10]{.aside}

μετα δε τρεις μηνας [ηχθημεν]{.greek-omitted} [ανηχθημεν]{.greek-added} εν πλοιω παρακεχειμακοτι εν τη νησω αλεξανδρινω παρασημω διοσκουροις[28:11]{.aside}

και καταχθεντες εις συρακουσας επεμειναμεν ημερας τρεις[28:12]{.aside}

οθεν περιελθοντες κατηντησαμεν εις ρηγιον και μετα μιαν ημεραν επιγενομενου νοτου δευτεραιοι ηλθομεν εις ποτιολους[28:13]{.aside}

ου ευροντες αδελφους παρεκληθημεν επ αυτοις [επιμειναι]{.greek-omitted} [επιμειναντες]{.greek-added} ημερας επτα και ουτως εις την ρωμην ηλθομεν[28:14]{.aside}

κακειθεν οι αδελφοι ακουσαντες τα περι ημων εξηλθον εις απαντησιν [ημιν]{.greek-omitted} [ημων]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} [αππιου]{.greek-omitted} [απφιου]{.greek-added} φορου και τριων ταβερνων ους ιδων ο παυλος ευχαριστησας τω [θεω]{.greek-abbr} ελαβεν θαρσος[28:15]{.aside}

οτε δε ηλθομεν εις [την]{.greek-added} ρωμην [επετραπη]{.greek-added} [ο]{.greek-omitted} [εκατονταρχος]{.greek-omitted} [παρεδωκεν]{.greek-omitted} [τους]{.greek-omitted} [δεσμιους]{.greek-omitted} τω [στρατοπεδαρχη]{.greek-omitted} [τω]{.greek-omitted} [δε]{.greek-omitted} παυλω [επετραπη]{.greek-omitted} μενειν καθ εαυτον συν τω φυλασσοντι αυτον στρατιωτη[28:16]{.aside}

εγενετο δε μετα ημερας τρεις συγκαλεσασθαι [τον]{.greek-omitted} [αυτον]{.greek-added} [παυλον]{.greek-omitted} τους οντας των ιουδαιων πρωτους συνελθοντων δε αυτων ελεγεν προς αυτους [εγω]{.greek-added} ανδρες αδελφοι [εγω]{.greek-omitted} ουδεν εναντιον ποιησας τω λαω [η]{.greek-omitted} [ει]{.greek-added} τοις [εθνεσι]{.greek-added} [εθεσιν]{.greek-omitted} [[εθεσι]{.corr}]{.greek-added} τοις πατρωοις δεσμιος [εξ]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [εν]{.greek-added} [[ιερουσαλημ]{.greek-abbr}]{.greek-added} παρεδοθην εις τας χειρας των ρωμαιων[28:17]{.aside}

οιτινες ανακριναντες με εβουλοντο απολυσαι δια το [μη]{.greek-added} [μηδεμιαν]{.greek-omitted} [δεμιαν]{.greek-added} αιτιαν θανατου υπαρχειν εν εμοι[28:18]{.aside}

αντιλεγοντων δε των ιουδαιων ηναγκασθην επικαλεσασθαι καισαρα ουχ ως του εθνους μου εχων τι κατηγορησαι[28:19]{.aside}

δια ταυτην ουν την αιτιαν παρεκαλεσα υμας ιδειν και προσλαλησαι ενεκεν γαρ της ελπιδος του [ισραηλ]{.greek-abbr} την αλυσιν ταυτην περικειμαι[28:20]{.aside}

οι δε προς αυτον ειπον ημεις ουτε γραμματα περι σου εδεξαμεθα απο της ιουδαιας ουτε παραγενομενος τις των αδελφων απηγγειλεν η ελαλησεν τι [πονηρον]{.greek-added} περι σου [πονηρον]{.greek-omitted}[28:21]{.aside}

αξιουμεν δε παρα σου ακουσαι α φρονεις περι μεν γαρ της αιρεσεως ταυτης γνωστον εστιν ημιν οτι πανταχου αντιλεγεται[28:22]{.aside}

ταξαμενοι δε αυτω ημεραν ηκον προς αυτον εις την ξενιαν πλειονες οις εξετιθετο διαμαρτυρομενος την βασιλειαν του [θεου]{.greek-abbr} πειθων τε αυτους τα περι του [ιησου]{.greek-abbr} απο τε του νομου [μωυσεως]{.greek-omitted} και των προφητων απο πρωι εως εσπερας[28:23]{.aside}

και οι μεν επειθοντο τοις λεγομενοις οι δε ηπιστουν[28:24]{.aside}

ασυμφωνοι δε οντες προς αλληλους απελυοντο ειποντος του παυλου ρημα εν οτι [καλως]{.greek-omitted} [καλλως]{.greek-added} το [πνευμα]{.greek-abbr} το αγιον ελαλησεν δια [του]{.greek-added} ησαιου του προφητου προς τους [πατερας]{.greek-abbr} ημων[28:25]{.aside}

[λεγον]{.greek-omitted} [λεγων]{.greek-added} πορευθητι προς τον λαον τουτον και [ειπον]{.greek-omitted} [ειπε]{.greek-added} ακοη [ακουσετε]{.greek-omitted} [ακουετε]{.greek-added} και ου μη συνητε και βλεποντες βλεψετε και ου μη [ιδητε]{.greek-omitted} [ιδετε]{.greek-added}[28:26]{.aside}

επαχυνθη γαρ η καρδια του λαου τουτου και τοις [ωσιν]{.greek-omitted} [ωσι]{.greek-added} βαρεως ηκουσαν και τους οφθαλμους αυτων [εκαμμυσαν]{.greek-omitted} [εκαμυσαν]{.greek-added} μηποτε [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} τοις οφθαλμοις και τοις ωσιν ακουσωσιν και τη καρδια [συνωσιν]{.greek-omitted} [συνωσι]{.greek-added} και επιστρεψωσιν και ιασομαι αυτους[28:27]{.aside}

γνωστον ουν εστω υμιν οτι τοις εθνεσιν απεσταλη το [σωτηριον]{.greek-abbr} του [θεου]{.greek-abbr} αυτοι και ακουσονται[28:28]{.aside}

και ταυτα αυτου [ε]{.unclear}ιποντος απηλθον οι ιουδαιοι πολλην εχοντες εν εαυτοις συζητησιν[28:29]{.aside}

[εμεινεν]{.greek-omitted} [επεμεινεν]{.greek-added} δε [ο]{.greek-omitted} [παυλος]{.greek-omitted} διετιαν ολην εν ιδιω μισθωματι [ο]{.greek-added} [παυλος]{.greek-added} και απεδεχετο παντας τους εισπορευομενους προς αυτον[28:30]{.aside}

[κηρυσσων]{.greek-omitted} [κηρυσσον]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} και διδασκων τα περι του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα [πασης]{.greek-omitted} παρρησιας ακωλυτως[28:31]{.aside}

