---
title: "Collation of Byz^RP^ vs 31872 (1872)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1872 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31872).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1872                                   	| λογος                              	|
| 1872 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1872 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1872               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1872                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1872 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1872                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου [ιωαννη]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [[χριστου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} οσα ειδεν[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των [επτα]{.greek-abbr} [πνευματων]{.greek-abbr} α ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος των νεκρων και ο αρχων των βασιλεων της γης τω αγαπωντι ημας και λουσαντι ημας απο των αμαρτιων ημων [εν]{.corr} [τω]{.corr} [αιματι]{.corr} [αυτου]{.corr}[1:5]{.aside}

και εποιησεν ημας βασιλειαν ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και [και]{.greek-added} κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [[ἄλφα]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και κοινωνος εν τη θλιψει και [βασι]{.greek-added} [βασιλεια]{.greek-omitted} [και]{.greek-omitted} [υπομονη]{.greek-omitted} [εν]{.greek-omitted} [χριστω]{.greek-omitted} [ιησου]{.greek-omitted} [εγενομην]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [νησω]{.greek-omitted} [τη]{.greek-omitted} [καλουμενη]{.greek-omitted} [πατμω]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted}[1:9]{.aside}

[λεια]{.greek-added} [εγω]{.greek-omitted} [ιωαννης]{.greek-omitted} [ο]{.greek-omitted} [αδελφος]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [κοινωνος]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θλιψει]{.greek-omitted} [και]{.greek-omitted} [βασιλεια]{.greek-omitted} και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9 | instance no. 2]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα φωνην οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

[λεγουσης]{.greek-omitted} [λαλουσης]{.greek-added} ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις [σμυρναν]{.greek-omitted} [μυρναν]{.greek-added} και εις περγαμον και εις θυατειρα και εις σαρδεις και εις [φιλαδελφειαν]{.greek-omitted} [φιλαδελφιαν]{.greek-added} και εις λαοδικειαν[1:11]{.aside}

και εκει επεστρε[ψα]{.unclear} βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των [επτα]{.greek-abbr} λυχνιων ομοιον [υιω]{.greek-omitted} [[υιον]{.greek-abbr}]{.greek-added} ανθρωπου ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκα[ι]{.unclear} ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια αυτου [χειρι]{.greek-omitted} αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος [οξεια]{.greek-omitted} εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον [επεσα]{.greek-omitted} [επεσον]{.greek-added} προς τους ποδας αυτου [ως]{.greek-omitted} νεκρος και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην [και]{.greek-omitted} [εχω]{.greek-omitted} [τας]{.greek-omitted} [κλεις]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [αδου]{.greek-omitted}[1:18]{.aside}

### Chapter 2

[δε]{.greek-added} [και]{.greek-omitted} [τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [σμυρνη]{.greek-omitted} [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} [ταδε]{.greek-omitted} λεγει ο πρωτος και ο εσχατος [ος]{.corr} εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος [ει]{.greek-omitted} [η]{.greek-added} και την βλασφημιαν εκ των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

[μη]{.greek-added} [μηδεν]{.greek-omitted} [δεν]{.greek-added} φοβου α μελλεις παθειν ιδου [δη]{.corr} μελλει [βαλειν]{.greek-omitted} ο διαβολος [βάλλειν]{.greek-added} εξ υμων εις φυλακην ινα [πειρασθη]{.greek-added} [πειρασθητε]{.corr} και εξετε θλιψιν [ημερων]{.greek-omitted} [ημερας]{.greek-added} [δεκα]{.greek-abbr} γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την δι[στο]{.unclear}μον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και π[ου]{.unclear} κατοικεις οπου ο θρονος του σατανα [και]{.unclear} κρατεις [το]{.greek-omitted} [ονομα]{.greek-omitted} [την]{.greek-added} [πιστιν]{.greek-added} μου και ουκ ηρνησω [την]{.greek-omitted} [πιστιν]{.greek-omitted} [τ[ο]{.unclear}]{.greek-added} [ονομα]{.greek-added} μου εν ταις ημεραις [εν]{.greek-omitted} αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς μου ο πιστος ος απεκτανθη παρ [υμιν]{.greek-omitted} [[υ]{.unclear}μων]{.greek-added} οπου ο σατανας κατοικει[2:13]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδαξε]{.greek-added} τον [βαλακ]{.greek-omitted} [βαλαακ]{.greek-added} βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} και φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του [στο]{.greek-added} [στοματος]{.greek-omitted} [μου]{.greek-omitted}[2:16]{.aside}

[μετανοησον]{.greek-omitted} [ουν]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [ερχομαι]{.greek-omitted} [σοι]{.greek-omitted} [ταχυ]{.greek-omitted} [και]{.greek-omitted} [πολεμησω]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ρομφαια]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [ματος]{.greek-added} μου[2:16 | instance no. 2]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου οτι αφεις την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα αυτη [χρονον]{.greek-omitted} [καιρον]{.greek-added} ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως [λεγουσιν]{.greek-omitted} [ου]{.greek-omitted} [βαλλω]{.greek-omitted} [εφ]{.greek-omitted} [υμας]{.greek-omitted} [αλλο]{.greek-omitted} [βαρος]{.greek-omitted}[2:24]{.aside}

[υμιν]{.greek-omitted} [δε]{.greek-omitted} [λεγω]{.greek-omitted} [τοις]{.greek-omitted} [λοιποις]{.greek-omitted} [τοις]{.greek-omitted} [εν]{.greek-omitted} [θυατειροις]{.greek-omitted} [οσοι]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [την]{.greek-omitted} [διδαχην]{.greek-omitted} [ταυτην]{.greek-omitted} [οιτινες]{.greek-omitted} [ουκ]{.greek-omitted} [εγνωσαν]{.greek-omitted} [τα]{.greek-omitted} [βαθεα]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [ως]{.greek-omitted} λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24 | instance no. 2]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [ανοιξω]{.greek-added} [αν]{.greek-omitted} [ηξω]{.greek-omitted}[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [και]{.greek-added} ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και στηρισον τα λοιπα α εμελλες αποβαλλειν ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας [και]{.greek-omitted} [ηκουσας]{.greek-omitted} [και]{.greek-omitted} [τηρει]{.greek-omitted} και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωση]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων [ουτος]{.greek-omitted} [ουτως]{.greek-added} περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου [της]{.greek-omitted} [ζωης]{.greek-omitted} [των]{.greek-added} [ζωντων]{.greek-added} και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον [ταδε]{.greek-omitted} [λεγει]{.greek-omitted} [ο]{.greek-omitted} [αγιος]{.greek-omitted} [ο]{.greek-omitted} [αληθινος]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [την]{.greek-omitted} [κλειν]{.greek-omitted} [του]{.greek-omitted} [δαυιδ]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [κλεισει]{.greek-omitted} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [ανοιξει]{.greek-omitted}[3:7]{.aside}

[και]{.greek-omitted} [τω]{.greek-omitted} [αγγελω]{.greek-omitted} [της]{.greek-omitted} [εν]{.greek-omitted} [φιλαδελφεια]{.greek-omitted} [εκκλησιας]{.greek-omitted} [γραψον]{.greek-omitted} ταδε λεγει ο αγιος ο αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει αυτην ει μη ο ανοιγων και ουδεις ανοιξει[3:7 | instance no. 2]{.aside}

οιδα σου τα εργα ιδου δεδωκα [θυραν]{.greek-added} ενωπιον σου [θυραν]{.greek-omitted} ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου [τον]{.greek-omitted} [λογον]{.greek-omitted} [τα]{.greek-added} [εργα]{.greek-added} και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα [μη]{.greek-added} [μηδεις]{.greek-omitted} [δεις]{.greek-added} λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω [αυτον]{.greek-omitted} [αυτω]{.greek-added} στυλον εν τω [ναω]{.greek-omitted} [ονοματι]{.greek-added} του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα [μου]{.greek-omitted} το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν λαοδικεια [εκκλησιας]{.greek-omitted} γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα [οτι]{.greek-omitted} [ουτε]{.greek-omitted} [ψυχρος]{.greek-omitted} [ει]{.greek-omitted} [ουτε]{.greek-omitted} [ζεστος]{.greek-omitted} [οφελον]{.greek-omitted} [ψυχρος]{.greek-omitted} [ης]{.greek-omitted} [η]{.greek-omitted} [ζεστος]{.greek-omitted}[3:15]{.aside}

[οιδα]{.greek-omitted} [σου]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} οτι ουτε ψυχρος ει ουτε ζεστος οφελον ψυχρος ης η ζεστος[3:15 | instance no. 2]{.aside}

ουτως οτι χλιαρος ει και [ου]{.greek-omitted} [ουτε]{.greek-added} ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και πεπλουτηκα και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και [ο]{.greek-omitted} ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι χρυσιον παρ [εμου]{.greek-omitted} [εμοι]{.greek-added} πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος [σου]{.unclear} και [κολλυριον]{.greek-omitted} [κολλουριον]{.greek-added} ινα εγχριση τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους [εαν]{.greek-omitted} [αν]{.greek-added} φιλω ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλευε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν και εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} [λεγει]{.greek-omitted} ταις εκκλησιαις [λεγει]{.greek-added}[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

[και]{.greek-omitted} ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι τον θρονον [καθημενος]{.greek-omitted} [κα]{.greek-added}[4:2]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [εγενομην]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [θρονος]{.greek-omitted} [εκειτο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [θρονον]{.greek-omitted} [καθημενος]{.greek-omitted} [θημενος]{.greek-added}[4:2 | instance no. 2]{.aside}

[ορασει]{.greek-added} ομοιος [ορασει]{.greek-omitted} [λιθω]{.greek-omitted} ιασπιδι και σαρδιω και [ιρις]{.greek-omitted} [ἶρις]{.greek-added} [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} του θρονου ομοιως ορασις σμαραγδινων[4:3]{.aside}

[και]{.greek-omitted} [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} του θρονου θρονοι [εικοσιτεσσαρες]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} και επι τους [εικοσιτεσσαρας]{.greek-added} [θρονους]{.greek-omitted} [τους]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες [καιομεναι]{.greek-added} πυρος [καιομεναι]{.greek-omitted} ενωπιον του θρονου αυτου αι εισιν επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα υαλινη ομοια [κρυσταλλω]{.greek-omitted} [κρυσταλω]{.greek-added} και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον εχον προσωπον [ανθρωπου]{.greek-abbr} και το τεταρτον [ζωον]{.greek-omitted} ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν εχον [ανα]{.greek-omitted} [πτερυγας]{.greek-omitted} [αναπτερυγας]{.greek-added} εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσι]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[4:9]{.aside}

[πεσουνται]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} και [προσκυνησουσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων [και]{.greek-omitted} [βαλουσιν]{.greek-omitted} [τους]{.greek-omitted} [στεφανους]{.greek-omitted} [αυτων]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [λεγοντες]{.greek-omitted}[4:10]{.aside}

πεσουνται οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} [τω]{.greek-omitted} [το]{.greek-added} ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλλοῦσι]{.greek-added} τους στεφανους αυτων [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} λεγοντες[4:10 | instance no. 2]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας παντα και δια το θελημα σου ησαν και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν [κατεσφραγισμενον]{.greek-omitted} [κατεσφιγμενον]{.greek-added} σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας [φραγιδας]{.greek-added} [σφραγιδας]{.corr} αυτου[5:2]{.aside}

και ουδεις εδυνατο εν τω [ουρανω]{.greek-abbr} ανω ουτε επι της γης ουτε υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης [του]{.greek-added} ιουδα η ριζα [δαυιδ]{.greek-abbr} ο ανοιγων το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος [ως]{.greek-omitted} εσφαγμενον εχον κερατα επτα και οφθαλμους επτα α [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ειληφεν εκ της [δεξιας]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted}[5:7]{.aside}

[και]{.greek-omitted} [ηλθεν]{.greek-omitted} [και]{.greek-omitted} [ειληφεν]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} δεξιας του καθημενου επι του θρονου[5:7 | instance no. 2]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα [τεσσαρα]{.greek-abbr} ζωα και οι [εικοσιτεσσαρες]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι επεσον ενωπιον του αρνιου εχοντες εκαστος κιθαραν και φιαλας χρυσας γεμουσας θυμιαματων αι [εισιν]{.greek-omitted} [εισι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας τω [θεω]{.greek-abbr} ημας εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και [βασιλευσουσιν]{.greek-omitted} [βασιλευουσιν]{.greek-added} επι της γης[5:10]{.aside}

και ειδον και ηκουσα ως φωνην [πολλων]{.greek-added} αγγελων [πολλων]{.greek-omitted} κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

[λεγοντες]{.greek-omitted} [λεγοντων]{.greek-added} φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν [και]{.greek-omitted} [τον]{.greek-omitted} [πλουτον]{.greek-omitted} και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο εν τω [ουρανω]{.greek-abbr} και [επι]{.greek-omitted} [εν]{.greek-added} [της]{.greek-omitted} [τη]{.greek-added} [γης]{.greek-omitted} [γη]{.greek-added} [και]{.greek-omitted} [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} και επι της θαλασσης [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις παντας ηκουσα λεγοντας τω καθημενω επι του θρονου και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13]{.aside}

[και]{.greek-omitted} [τα]{.greek-omitted} [τεσσαρα]{.greek-omitted} [ζωα]{.greek-omitted} [λεγοντα]{.greek-omitted} [το]{.greek-omitted} [αμην]{.greek-omitted} και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα [ενος]{.greek-omitted} εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνῆ]{.greek-added} βροντης [ερχου]{.greek-omitted} [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [οτι]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [αρνιον]{.greek-omitted} [μιαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [σφραγιδων]{.greek-omitted} [και]{.greek-omitted} [ηκουσα]{.greek-omitted} [ενος]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [λεγοντος]{.greek-omitted} [ως]{.greek-omitted} [φωνη]{.greek-omitted} [βροντης]{.greek-omitted} ερχου και ιδε[6:1 | instance no. 2]{.aside}

και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα νικηση[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την δευτεραν σφραγιδα ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος πυρος και τω καθημενω επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} [εδοθη]{.greek-omitted} [εδοθησαν]{.greek-added} αυτω λαβειν την ειρηνην εκ της γης ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και [εδοθησαν]{.greek-added} [εδοθη]{.corr} αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και ιδε και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες κριθης δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερ[χου]{.unclear} και ιδε[6:7]{.aside}

και ιδου ιππος [λευκος]{.greek-added} χλωρος και ο καθημενος επανω αυτου ονομα αυτω [ο]{.greek-omitted} θανατος και ο αδης ηκολουθει αυτω και εδοθη αυτω εξουσια επι το τεταρτον της γης αποκτειναι [αυτο]{.greek-added} εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} [και]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [ην]{.greek-omitted} [ειχον]{.greek-omitted}[6:9]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [πεμπτην]{.greek-omitted} [σφραγιδα]{.greek-omitted} [ειδον]{.greek-omitted} [υποκατω]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [τας]{.greek-omitted} [ψυχας]{.greek-omitted} [των]{.greek-omitted} [εσφαγμενων]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} και δια την μαρτυριαν του αρνιου ην ειχον[6:9 | instance no. 2]{.aside}

και εκραξαν [φωνη]{.greek-omitted} [φωνην]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαλην]{.greek-added} λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις [εκαστω]{.greek-omitted} στολη λευκη και [ερρεθη]{.greek-omitted} [ερρηθη]{.greek-added} αυτοις ινα αναπαυσωνται ετι χρονον εως [πληρωσωσιν]{.greek-omitted} [πληρωσουσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων και οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και [ειδον]{.greek-omitted} οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην [και]{.greek-omitted} σεισμος μεγας εγενετο και ο ηλιος [μεγας]{.greek-added} [μελας]{.greek-added} [μελας]{.corr} εγενετο ως σακκος τριχινος και η σεληνη ολη εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον [εις]{.greek-omitted} [επι]{.greek-added} την γην ως συκη βαλουσα τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ελισσομενος]{.greek-added} και παν ορος και νησος εκ των τοπων αυτων [εκινηθησαν]{.greek-omitted} [εσαλευθησαν]{.greek-added}[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

και μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους τεσσαρας ανεμους της γης ινα μη [πνεη]{.greek-omitted} [πεση]{.greek-added} [ο]{.greek-added} ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την [θαλασσαν]{.greek-omitted} [θαλατταν]{.greek-added}[7:2]{.aside}

λεγων μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} [ημων]{.greek-omitted} επι των μετωπων αυτων[7:3]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [κηκουσα]{.greek-added} [τον]{.greek-omitted} [αριθμον]{.greek-omitted} των [εσφραγισμενων]{.greek-omitted} [εκατον]{.greek-omitted} [και]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} [χιλιαδες]{.greek-omitted} εσφραγισμενων εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες εσφραγισμεναι εκ φυλης ρουβιμ δωδεκα χιλιαδες εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ δωδεκα χιλιαδες εκ φυλης [νεφθαλειμ]{.greek-omitted} [νεφθαλιμ]{.greek-added} δωδεκα χιλιαδες εκ φυλης [μανασση]{.greek-omitted} [μαναση]{.greek-added} δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι δωδεκα χιλιαδες εκ φυλης ισαχαρ δωδεκα χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων δωδεκα χιλιαδες εκ φυλης ιωσηφ δωδεκα χιλιαδες εκ φυλης βενιαμιν δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις εδυνατο εκ παντος εθνους και [φυλων]{.greek-omitted} [και]{.greek-omitted} [λαων]{.greek-omitted} [και]{.greek-omitted} [γλωσσων]{.greek-omitted} [εστωτας]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [περιβεβλημενους]{.greek-omitted} [στολας]{.greek-omitted} [λευκας]{.greek-omitted} [και]{.greek-omitted} [φοινικας]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [χερσιν]{.greek-omitted} [αυτων]{.greek-omitted}[7:9]{.aside}

[μετα]{.greek-omitted} [ταυτα]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted} [ον]{.greek-omitted} [αριθμησαι]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [εκ]{.greek-omitted} [παντος]{.greek-omitted} [εθνους]{.greek-omitted} [και]{.greek-omitted} φυλων και λαων και γλωσσων εστωτας ενωπιον του θρονου και ενωπιον του αρνιου περιβεβλημενους στολας λευκας και φοινικας εν ταις χερσιν αυτων[7:9 | instance no. 2]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω θρονω και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον αυτω κυριε μου συ οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και [επλυναν]{.greek-omitted} [επλατυναν]{.greek-added} τας στολας αυτων και ελευκαναν εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι τω θρονω σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν ετι ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου ποιμαινει αυτους και [οδηγη]{.greek-added} [οδηγει]{.greek-omitted} [αυτους]{.greek-omitted} [επι]{.greek-omitted} [ζωης]{.greek-omitted} [πηγας]{.greek-omitted} [υδατων]{.greek-omitted} [και]{.greek-omitted} [εξαλειψει]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [παν]{.greek-omitted} [δακρυον]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [οφθαλμων]{.greek-omitted} [αυτων]{.greek-omitted}[7:17]{.aside}

[σει]{.greek-added} [οτι]{.greek-omitted} [το]{.greek-omitted} [αρνιον]{.greek-omitted} [το]{.greek-omitted} [ανα]{.greek-omitted} [μεσον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [ποιμαινει]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [οδηγει]{.greek-omitted} αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον [εκ]{.greek-omitted} [απο]{.greek-added} των οφθαλμων αυτων[7:17 | instance no. 2]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και [εδοθησαν]{.greek-omitted} [εδοθη]{.greek-added} αυτοις επτα σαλπιγγες [ινα]{.greek-added} [σαλπισωσι]{.greek-added}[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι [του]{.greek-omitted} [το]{.greek-added} [θυσιαστηριου]{.greek-omitted} [θυσιαστηριον]{.greek-added} εχων λιβανωτον χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δωσει]{.greek-added} ταις προσευχαις των αγιων [παντων]{.corr} επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και [ο]{.greek-added} ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο βρονται [[βρονται]{.corr}]{.greek-added} [και]{.corr} [φωναι]{.corr} και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας [επτα]{.corr} [[επτα]{.corr}]{.greek-added} σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και [εγενετο]{.greek-added} ως ορος μεγα καιομενον [και]{.greek-added} εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον [των]{.greek-omitted} [κτισματων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted} [τα]{.greek-omitted} [εχοντα]{.greek-omitted} [ψυχας]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [πλοιων]{.greek-omitted} [διεφθαρη]{.greek-omitted}[8:9]{.aside}

[και]{.greek-omitted} [απεθανεν]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} των κτισματων εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9 | instance no. 2]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και το τριτον [αυτης]{.greek-omitted} μη φανη η ημερα και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος αετου πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα [πεπτωκοτα]{.greek-added} εκ του [ουρανου]{.greek-abbr} [πεπτωκοτα]{.greek-omitted} εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} και ανεβη καπνος εκ του φρεατος ως καπνος καμινου καιομενης και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις [εξου]{.greek-added} [εξουσια]{.greek-omitted} [ως]{.greek-omitted} [εχουσιν]{.greek-omitted} [εξουσιαν]{.greek-omitted} [οι]{.greek-omitted} [σκορπιοι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[9:3]{.aside}

[σια]{.greek-added} [και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [καπνου]{.greek-omitted} [εξηλθον]{.greek-omitted} [ακριδες]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυταις]{.greek-omitted} [εξουσια]{.greek-omitted} ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3 | instance no. 2]{.aside}

και [ερρεθη]{.greek-omitted} [ερρηθη]{.greek-added} αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και εδοθη αυταις ινα μη [αποκτεινωσιν]{.greek-omitted} [αδικησωσιν]{.greek-added} αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [πεση]{.greek-added} [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [εὑρήσουσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και φευξεται απ αυτων ο θανατος[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι χρυσοι και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

[και]{.corr} [ειχον]{.corr} [θωρακας]{.corr} [ως]{.corr} [θωρακας]{.corr} [σιδηρους]{.corr} και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα και εν ταις ουραις αυτων εξουσιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} [του]{.greek-omitted} [αδικησαι]{.greek-omitted} τους ανθρωπους [αδικησαι]{.greek-added} μηνας πεντε[9:10]{.aside}

εχουσαι βασιλεα επ αυτων αγγελον της αβυσσου ονομα αυτω εβραιστι [αββαδων]{.greek-omitted} [αβααδων]{.greek-added} εν δε τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου ερχεται ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος [ε]{.greek-added} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [μιαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [κερατων]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [του]{.greek-omitted} [χρυσου]{.greek-omitted} [του]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[9:13]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [σαλπισε]{.greek-added} και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13 | instance no. 2]{.aside}

[λεγουσαν]{.greek-omitted} [λεγοντος]{.greek-added} τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του ιππου μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

[και]{.greek-omitted} ουτως ειδον τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-omitted} [ανων]{.greek-added} [ην]{.greek-added} απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ [των]{.greek-omitted} [του]{.greek-added} [στοματων]{.greek-omitted} [στοματος]{.greek-added} αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι οφεων [εχουσαι]{.corr} [κεφαλας]{.corr} και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα [χαλκα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} λιθινα και τα ξυλινα α ουτε βλεπειν δυναται ουτε [α]{.greek-added} [ακουειν]{.greek-omitted} [ουτε]{.greek-omitted} [περιπατειν]{.greek-omitted}[9:20]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [οι]{.greek-omitted} [ουκ]{.greek-omitted} [απεκτανθησαν]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [πληγαις]{.greek-omitted} [ταυταις]{.greek-omitted} [ου]{.greek-omitted} [μετενοησαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [εργων]{.greek-omitted} [των]{.greek-omitted} [χειρων]{.greek-omitted} [αυτων]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [προσκυνησωσιν]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [ειδωλα]{.greek-omitted} [τα]{.greek-omitted} [χρυσα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [αργυρα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [χαλκα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [λιθινα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [ξυλινα]{.greek-omitted} [α]{.greek-omitted} [ουτε]{.greek-omitted} [βλεπειν]{.greek-omitted} [δυναται]{.greek-omitted} [ουτε]{.greek-omitted} [ακουειν]{.greek-omitted} [κουειν]{.greek-added} ουτε περιπατειν[9:20 | instance no. 2]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και εχων εν τη χειρι αυτου βιβλιον ανεωγμενον και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμοσε]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος [ουκετι]{.greek-omitted} [ουκ]{.greek-added} [ετι]{.greek-added} εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} σαλπιζειν και ετελεσθη το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} [παλιν]{.greek-omitted} [λαλουσα]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [λεγουσα]{.greek-omitted} [υπαγε]{.greek-omitted} [λαβε]{.greek-omitted} [το]{.greek-omitted} [βιβλιδαριον]{.greek-omitted} [το]{.greek-omitted} [ανεωγμενον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [του]{.greek-omitted} [αγγελου]{.greek-omitted} [του]{.greek-omitted} [εστωτος]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[10:8]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [ην]{.greek-omitted} [ηκουσα]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} παλιν λαλουσα μετ εμου και λεγουσα υπαγε λαβε το βιβλιδαριον το [ανεωγμενον]{.greek-omitted} [ανεωιγμενον]{.greek-added} εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8 | instance no. 2]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω δουναι μοι το βιβλιδαριον και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται [γλυκυ]{.greek-omitted} ως μελι [γλυκυ]{.greek-added}[10:9]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτὸ]{.greek-added} και ην εν τω στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} μοι δει σε παλιν προφητευσαι επι [λαοις]{.greek-omitted} [λαου]{.greek-added} και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω λεγων εγειραι και [μετρησον]{.greek-omitted} [μετρησαι]{.greek-added} τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και [την]{.greek-omitted} [το]{.greek-added} αυλην την εξωθεν του ναου εκβαλε εξω και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα και δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-abbr} της γης εστωσαι[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους [αδικησαι]{.greek-omitted} [ουτως]{.greek-omitted} [δει]{.greek-omitted} [αυτον]{.greek-omitted} [αποκτανθηναι]{.greek-omitted}[11:5]{.aside}

[και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [αυτους]{.greek-omitted} [θελει]{.greek-omitted} αδικησαι [πυρ]{.greek-omitted} [εκπορευεται]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [κατεσθιει]{.greek-omitted} [τους]{.greek-omitted} [εχθρους]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [θελει]{.greek-omitted} [αυτους]{.greek-omitted} [αδικησαι]{.greek-omitted} [ουτως]{.greek-omitted} [ουτω]{.greek-added} δει αυτον αποκτανθηναι[11:5 | instance no. 2]{.aside}

ουτοι εχουσιν [εξουσιαν]{.greek-added} τον [ουρανον]{.greek-abbr} [εξουσιαν]{.greek-omitted} κλεισαι ινα μη [υ]{.unclear}ετος βρεχη τας ημερας [αυτων]{.greek-added} της προφητειας [αυτων]{.greek-omitted} και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην οσακις [εαν]{.greek-omitted} [αν]{.greek-added} [θελησωσιν]{.greek-omitted} [θελησωσι]{.greek-added} [εν]{.greek-omitted} [παση]{.greek-omitted} [πληγη]{.greek-omitted}[11:6]{.aside}

[[εν]{.corr}]{.greek-added} [[παση]{.corr}]{.greek-added} [[πληγη]{.corr}]{.greek-added} [και]{.corr} [οταν]{.corr} [τελεσωσιν]{.greek-omitted} [[τελεσωσι]{.corr}]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και το πτωμα αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται πνευματικως σοδομα και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφησουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και ευφρανθησονται και δωρα δωσουσιν αλληλοις οτι ουτοι οι δυο προφηται [εβασανιλευσαν]{.greek-added} [εβασανισαν]{.corr} τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν εις αυτους και εστησαν επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} [επεπεσεν]{.greek-added} επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον ουρανον εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

[και]{.greek-omitted} εν εκεινη τη ημερα εγενετο σεισμος μεγας και το δεκατον [της]{.greek-omitted} [πολεως]{.greek-omitted} [επεσεν]{.greek-omitted} [και]{.greek-omitted} [απεκτανθησαν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σεισμω]{.greek-omitted} [ονοματα]{.greek-omitted} [ανθρωπων]{.greek-omitted} [χιλιαδες]{.greek-omitted} [επτα]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [εμφοβοι]{.greek-omitted} [εγενοντο]{.greek-omitted} [και]{.greek-omitted} [εδωκαν]{.greek-omitted} [δοξαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[11:13]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ημερα]{.greek-omitted} [εγενετο]{.greek-omitted} [σεισμος]{.greek-omitted} [μεγας]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [δεκατον]{.greek-omitted} της πολεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13 | instance no. 2]{.aside}

η ουαι η δευτερα απηλθεν η ουαι η τριτη ιδου ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} [λεγουσαι]{.greek-omitted} [λεγοντες]{.greek-added} εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι οι ενωπιον του θρονου του [θεου]{.greek-abbr} [καθημενοι]{.greek-omitted} [οι]{.greek-added} [καθηνται]{.greek-added} επι τους θρονους αυτων επεσον επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των [νεκρων]{.greek-omitted} [εθνων]{.greek-added} κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις [σου]{.greek-added} και τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους διαφθειροντας την γην[11:18]{.aside}

και [ηνοιγη]{.greek-omitted} [ηνοιχθη]{.greek-added} ο ναος του [θεου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης [του]{.greek-omitted} [κυριου]{.greek-abbr} εν τω ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης [και]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted} [αυτης]{.greek-omitted} [στεφανος]{.greek-omitted} [αστερων]{.greek-omitted} [δωδεκα]{.greek-omitted}[12:1]{.aside}

[και]{.greek-omitted} [σημειον]{.greek-omitted} [μεγα]{.greek-omitted} [ωφθη]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [γυνη]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [τον]{.greek-omitted} [ηλιον]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [σεληνη]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [αυτης]{.greek-omitted} και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1 | instance no. 2]{.aside}

και εν γαστρι εχουσα [εκραζεν]{.greek-omitted} [εκραξεν]{.greek-added} ω[δ]{.unclear}ινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων πυρος μεγας εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἕστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν [υιον]{.greek-abbr} αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκ[ει]{.unclear} τοπον ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει εκτρεφωσιν αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη αυτω ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο [οφις]{.greek-added} [ο]{.greek-added} μεγας [ο]{.greek-omitted} [οφις]{.greek-omitted} ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου [εβληθησαν]{.greek-added} μετ αυτου [εβληθησαν]{.greek-omitted}[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν [αρτι]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [σωτηρια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δυναμις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [εξουσια]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [εβληθη]{.greek-omitted} [ο]{.greek-omitted} [κατηγορος]{.greek-omitted} [των]{.greek-omitted} [αδελφων]{.greek-omitted} [ημων]{.greek-omitted} [ο]{.greek-omitted} [κατηγορων]{.greek-omitted} [αυτων]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [νυκτος]{.greek-omitted}[12:10]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνην]{.greek-omitted} [μεγαλην]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [λεγουσαν]{.greek-omitted} αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} [ημων]{.greek-omitted} ημερας και νυκτος[12:10 | instance no. 2]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

[δια]{.greek-omitted} [τουτο]{.greek-omitted} [διατουτο]{.greek-added} ευφραινεσθε [ουρανοι]{.greek-abbr} και οι εν αυτοις [σκηνουντες]{.greek-omitted} [κατοικουντες]{.greek-added} ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν τη γυναικι δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον αυτης οπως τρεφηται [εκει]{.greek-omitted} καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον ποιηση[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} [και]{.greek-omitted} [εχοντων]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted}[12:17]{.aside}

[και]{.greek-omitted} [ωργισθη]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [γυναικι]{.greek-omitted} [και]{.greek-omitted} [απηλθεν]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [λοιπων]{.greek-omitted} [του]{.greek-omitted} [σπερματος]{.greek-omitted} [αυτης]{.greek-omitted} [των]{.greek-omitted} [τηρουντων]{.greek-omitted} [τας]{.greek-omitted} [εντολας]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17 | instance no. 2]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον εχον κερατα [δεκα]{.greek-abbr} και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον ην ομοιον παρδαλει και οι ποδες αυτου ως [αρκου]{.greek-omitted} [αρκτου]{.greek-added} και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου ωσει εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι τω δεδωκοτι την εξουσιαν τω θηριω και προσεκυνησαν τω θηριω λεγοντες τις ομοιος τω θηριω [και]{.greek-omitted} τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημια]{.greek-added} και εδοθη αυτω εξουσια πολεμον ποιησαι μηνας [τεσσαρακοντα]{.greek-omitted} [τεσσαρακονταδυο]{.greek-added} [δυο]{.greek-omitted}[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου τους εν τω [ουρανω]{.greek-abbr} σκηνουντας[13:6]{.aside}

και εδοθη αυτω [εξουσια]{.greek-added} ποιησαι πολεμον μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και λαον και [πο]{.greek-added} γλωσσαν [και]{.greek-omitted} [εθνος]{.greek-omitted}[13:7]{.aside}

[λιν]{.greek-added} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [νικησαι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσια]{.greek-omitted} [επι]{.greek-omitted} [πασαν]{.greek-omitted} [φυλην]{.greek-omitted} [και]{.greek-omitted} [λαον]{.greek-omitted} [και]{.greek-omitted} [γλωσσαν]{.greek-omitted} και εθνος[13:7 | instance no. 2]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων [ου]{.greek-omitted} [ουτε]{.greek-added} γεγραπται το ονομα εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις εχει αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} δει αυτον [εν]{.greek-omitted} [μαχαιρα]{.greek-omitted} αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και [ειχεν]{.greek-omitted} [ειχε]{.greek-added} κερατα [δυο]{.greek-omitted} ομοια αρνιω και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και εποιει την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει σημεια μεγαλα και πυρ ινα εκ του [ουρανου]{.greek-abbr} καταβαινη επι την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ὃ]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} [την]{.greek-omitted} πληγην και εζησεν απο της μαχαιρας[13:14]{.aside}

και εδοθη αυτω [πνευμα]{.greek-abbr} δουναι τη εικονι του θηριου ινα και λαληση η εικων του θηριου και ποιηση οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τη εικονι του θηριου [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσουσιν]{.greek-added} αυτοις χαραγματα επι [της]{.greek-omitted} [χειρος]{.greek-omitted} [αυτων]{.greek-omitted} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [η]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [μετωπον]{.greek-omitted} [αυτων]{.greek-omitted}[13:16]{.aside}

[και]{.greek-omitted} [ποιει]{.greek-omitted} [παντας]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πλουσιους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [πτωχους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [ελευθερους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [ινα]{.greek-omitted} [δωσωσιν]{.greek-omitted} [αυτοις]{.greek-omitted} [χαραγματα]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} χειρος αυτων της δεξιας η επι [το]{.greek-omitted} [των]{.greek-added} [μετωπον]{.greek-omitted} [μετωπων]{.greek-added} αυτων[13:16 | instance no. 2]{.aside}

και ινα μη τις δυναται αγορασαι η πωλησαι ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} εστιν [και]{.greek-omitted} ο αριθμος αυτου [[χξϛ]{.greek-abbr}]{.greek-added} [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και ειδον και ιδου το αρνιον [εστηκως]{.greek-added} [εστηκος]{.corr} επι το ορος σιων και μετ αυτου αριθμος [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες [εχου]{.greek-added} [εχουσαι]{.corr} το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα [φωνην]{.greek-omitted} εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλης και η φωνη ην ηκουσα ως κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και [ουδεις]{.greek-omitted} [ουδε]{.greek-added} [εις]{.greek-added} εδυνατο μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι εισιν οι [ακολουθουντες]{.greek-omitted} [ακολουθησαντες]{.greek-added} τω αρνιω οπου [αν]{.greek-omitted} [εαν]{.greek-added} υπαγη ουτοι υπο [ιησου]{.greek-abbr} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και ουχ ευρεθη εν τω στοματι αυτων ψευδος αμωμοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added}[14:5]{.aside}

και ειδον αγγελον πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον ευαγγελισαι τους καθημενους επι της γης και επι παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-abbr} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε αυτον τον ποιησαντα τον ουρανον και την γην και την θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος δευτερος αγγελος [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη εκ του οινου [της]{.greek-added} [πορνειας]{.greek-added} του θυμου [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted} [ταυτης]{.greek-added} [πεποτικεν]{.greek-omitted} [πεποθηκε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει χαραγμα επι του μετωπου αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις [αιωνας]{.greek-omitted} [αιωνα]{.greek-added} αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [ἀπάρτι]{.greek-added} [απ]{.greek-omitted} [αρτι]{.greek-omitted} λεγει ναι το [πνευμα]{.greek-abbr} ινα [ανα]{.greek-added} [αναπαυσωνται]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κοπων]{.greek-omitted} [αυτων]{.greek-omitted} [τα]{.greek-omitted} [δε]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted} [ακολουθει]{.greek-omitted} [μετ]{.greek-omitted} [αυτων]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [φωνης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [λεγουσης]{.greek-omitted} [γραψον]{.greek-omitted} [μακαριοι]{.greek-omitted} [οι]{.greek-omitted} [νεκροι]{.greek-omitted} [οι]{.greek-omitted} [εν]{.greek-omitted} [κυριω]{.greek-omitted} [αποθνησκοντες]{.greek-omitted} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [λεγει]{.greek-omitted} [ναι]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [ινα]{.greek-omitted} [αναπαυσωνται]{.greek-omitted} [παυσωνται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυτων ακολουθει μετ αυτων[14:13 | instance no. 2]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην καθημενον ομοιον υιω [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι [την]{.greek-omitted} [τη]{.greek-added} [νεφελην]{.greek-omitted} [νεφελη]{.greek-added} το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [κραυγη]{.greek-omitted} [εν]{.greek-added} [φωνη]{.greek-added} μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι [ηκμασαν]{.greek-omitted} [ηκμασεν]{.greek-added} [αι]{.greek-omitted} [η]{.greek-added} [σταφυλαι]{.greek-omitted} [σταφυλη]{.greek-added} [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[14:18]{.aside}

και [εβαλεν]{.greek-omitted} [εξεβαλεν]{.greek-added} ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις την ληνον [του]{.greek-omitted} [τον]{.greek-added} [θυμου]{.greek-omitted} [θυμον]{.greek-added} του [θεου]{.greek-abbr} τον μεγαν[14:19]{.aside}

και επατηθη η ληνος εξωθεν της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο [σταδιων]{.greek-omitted} [σταδιω]{.greek-added} [[αχ]{.greek-abbr}]{.greek-added} [χιλιων]{.greek-omitted} [εξακοσιων]{.greek-omitted}[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας [επτα]{.greek-added} πληγας [επτα]{.greek-omitted} τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ [της]{.greek-added} [εικονος]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} του θηριου [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [εικονος]{.greek-omitted} αυτου και εκ του αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και αδουσιν [την]{.greek-omitted} ωδην μωυσεως [του]{.greek-omitted} δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη [φοβηθη]{.greek-omitted} [φοβηθησε]{.greek-added} [σε]{.greek-omitted} [κυριε]{.greek-abbr} και [δοξαση]{.greek-omitted} [δοξασει]{.greek-added} το ονομα σου οτι μονος αγιος οτι [παντες]{.greek-added} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και [ηνοιγη]{.greek-omitted} [ηνοιχθη]{.greek-added} ο ναος της [σκηνης]{.greek-omitted} [κηνης]{.greek-added} του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι [οι]{.corr} [εχοντες]{.corr} [τας]{.corr} [επτα]{.corr} [πληγας]{.corr} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} οι ησαν ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος [εκ]{.greek-added} [του]{.greek-added} καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις εδυνατο εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα [μεγαλης]{.greek-added} φωνης [μεγαλης]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας επτα φιαλας του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και [απηλθεν]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [και]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [ελκος]{.greek-omitted} [κακον]{.greek-omitted} [και]{.greek-omitted} [πονηρον]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [τους]{.greek-omitted} [εχοντας]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [προσκυνουντας]{.greek-omitted} [τη]{.greek-omitted} [εικονι]{.greek-omitted} [αυτου]{.greek-omitted}[16:2]{.aside}

[και]{.greek-omitted} απηλθεν ο πρωτος και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2 | instance no. 2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη [ζωσα]{.greek-omitted} απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων [και]{.corr} [εγενετο]{.corr} [αιμα]{.corr}[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην ο οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν αξιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:6]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος [αγγελος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και εδοθη [αυτω]{.greek-omitted} καυματισαι εν πυρι τους [ανθρωπους]{.greek-abbr}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και [εμασωντο]{.greek-omitted} [εμασσωντο]{.greek-added} τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ [τον]{.greek-added} [πονον]{.greek-added} [των]{.corr} [πονων]{.corr} αυτων και εκ των ελκων αυτων και ου [μετενοησαν]{.greek-omitted} [μετενοη]{.greek-added} [εκ]{.greek-omitted} [των]{.greek-omitted} [εργων]{.greek-omitted} [αυτων]{.greek-omitted}[16:11]{.aside}

[σαν]{.greek-added} [και]{.greek-omitted} [εβλασφημησαν]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [πονων]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [ελκων]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μετενοησαν]{.greek-omitted} εκ των εργων αυτων[16:11 | instance no. 2]{.aside}

και ο εκτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην [αυτου]{.greek-omitted} επι τον ποταμον τον μεγαν ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου [πνευματα]{.greek-abbr} [ακαθαρτα]{.greek-omitted} τρια ως βατραχοι[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ [πνευματα]{.greek-abbr} δαιμονιων ποιουντα σημεια α εκπορευεται επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την [ασχημοσυνην]{.greek-omitted} [αισχυνην]{.greek-added} αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [μαγεδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη απο του ναου του [ουρανου]{.greek-abbr} απο του θρονου [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} λεγουσα [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[16:17]{.aside}

και εγενοντο [βρονται]{.greek-added} [και]{.greek-added} αστραπαι [και]{.greek-omitted} [βρονται]{.greek-omitted} και φωναι και σεισμος μεγας οιος [ουκ]{.greek-omitted} [ου]{.greek-added} [εγενετο]{.greek-omitted} [γεγονεν]{.greek-added} αφ ου οι [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [[ουτω]{.corr}]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων επεσον και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και [πα]{.greek-added} [πασα]{.greek-omitted} [νησος]{.greek-omitted} [εφυγεν]{.greek-omitted} [και]{.greek-omitted} [ορη]{.greek-omitted} [ουχ]{.greek-omitted} [ευρεθησαν]{.greek-omitted}[16:20]{.aside}

[σα]{.greek-added} [και]{.greek-omitted} [πασα]{.greek-omitted} νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20 | instance no. 2]{.aside}

και χαλαζα [μεγαλη]{.greek-omitted} [βιαια]{.greek-added} [καταβαινει]{.greek-added} ως ταλαντιαια [καταβαινει]{.greek-omitted} εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της [χαλαζης]{.greek-added} [της]{.greek-added} πληγης [της]{.greek-omitted} [χαλαζης]{.greek-omitted} οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι των υδατων των πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην [εκ]{.greek-omitted} [απο]{.greek-added} του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [ανηνεγκε]{.greek-added} με εις ερημον [εν]{.greek-omitted} [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι [το]{.greek-added} θηριον [το]{.greek-added} κοκκινον γεμον ονοματα βλασφημιας εχον κεφαλας επτα και κερατα [δεκα]{.greek-abbr}[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἣν]{.greek-added} περιβεβλημενη πορφυρουν και κοκκινον κεχρυσωμενη χρυσιω και λιθω τιμιω και μαργαριταις εχουσα ποτηριον [χρυσουν]{.corr} εν τη χειρι αυτης [γεμον]{.greek-omitted} [γεμοντα]{.greek-added} βδελυγματων και τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν [εκ]{.greek-omitted} του αιματος των αγιων εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος [δια]{.greek-omitted} [διατι]{.greek-added} [τι]{.greek-omitted} εθαυμασας [εγω]{.greek-omitted} [ερω]{.greek-omitted} [σοι]{.greek-omitted} [το]{.greek-omitted} [μυστηριον]{.greek-omitted} [της]{.greek-omitted} [γυναικος]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [του]{.greek-omitted} [βασταζοντος]{.greek-omitted} [αυτην]{.greek-omitted} [του]{.greek-omitted} [εχοντος]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [κεφαλας]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [δεκα]{.greek-omitted} [κερατα]{.greek-omitted}[17:7]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [μοι]{.greek-omitted} [ο]{.greek-omitted} [αγγελος]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [εθαυμασας]{.greek-omitted} εγω ερω σοι το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7 | instance no. 2]{.aside}

το θηριον ο ειδες ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων ου γεγραπται [τα]{.greek-omitted} [το]{.greek-added} [ονοματα]{.greek-omitted} [ονομα]{.greek-added} επι [το]{.greek-omitted} [του]{.greek-added} [βιβλιον]{.greek-omitted} [βιβλιου]{.greek-added} της ζωης απο καταβολης κοσμου βλεποντων οτι ην το θηριον και ουκ [εστιν]{.greek-omitted} [εσται]{.greek-added} και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [εισιν]{.greek-added} [επτα]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ο εις εστιν ο αλλος ουπω [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και οταν ελθη ολιγον δει αυτον μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ [εστιν]{.greek-omitted} [εσται]{.greek-added} και [αυτος]{.greek-omitted} [ουτος]{.greek-added} ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} και εκ των επτα [εστιν]{.greek-omitted} [εισι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [υπο]{.greek-added} [του]{.greek-added} [θηριου]{.greek-added} μετα του θηριου [λαμβανουσιν]{.greek-added}[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την δυναμιν και την εξουσιαν αυτων τω θηριω διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και [οχλοι]{.greek-omitted} [γλωσσαι]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και [γλωσσαι]{.greek-omitted} [οχλοι]{.greek-added}[17:15]{.aside}

[και]{.greek-omitted} τα [δε]{.greek-added} δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην ποιησουσιν αυτην και [γυμνην]{.greek-omitted} [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} τας σαρκας αυτης [φαγονται]{.greek-omitted} [φαγωνται]{.greek-added} και αυτην [κατακαυσουσιν]{.greek-omitted} [κατακαυσουσι]{.greek-added} [εν]{.greek-omitted} πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι γνωμην μιαν και δουναι την βασιλειαν αυτων τω θηριω αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} η εχουσα βασιλειαν επι των βασιλεων [επι]{.greek-added} της γης[17:18]{.aside}

### Chapter 18

μετα ταυτα ειδον [αγγελον]{.greek-added} αλλον [αγγελον]{.greek-omitted} καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν ισχυρα φωνη λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος [πνευματος]{.greek-abbr} ακαθαρτου και φυλακη παντος ορνεου [ακαθαρτου]{.greek-omitted} και μεμισημενου[18:2]{.aside}

οτι εκ του οινου του θυμου της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκασι]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι [της]{.greek-omitted} [αυτης]{.greek-added} [γης]{.greek-omitted} εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν [αυτης]{.greek-omitted} αι αμαρτιαι αχρι του ουρανου και εμνημονευσεν [αυτης]{.greek-added} ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη [ως]{.greek-omitted} [και]{.greek-omitted} [αυτη]{.greek-omitted} [απεδωκεν]{.greek-omitted} [και]{.greek-omitted} [διπλωσατε]{.greek-omitted} [αυτη]{.greek-omitted} [διπλα]{.greek-omitted} [κατα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [αυτης]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ποτηριω]{.greek-omitted} [ω]{.greek-omitted} [εκερασεν]{.greek-omitted} [κερασατε]{.greek-omitted} [αυτη]{.greek-omitted} [διπλουν]{.greek-omitted}[18:6]{.aside}

[αποδοτε]{.greek-omitted} [αυτη]{.greek-omitted} ως και αυτη [απεδωκεν]{.greek-omitted} [απεδωκε]{.greek-added} και διπλωσατε [τα]{.greek-added} [διπλα]{.greek-added} [ως]{.greek-added} [και]{.greek-added} αυτη [διπλα]{.greek-omitted} [και]{.greek-added} κατα τα εργα αυτης εν τω ποτηριω [αυτης]{.greek-added} ω [εκερασεν]{.greek-omitted} [εκερασε]{.greek-added} κερασατε αυτη διπλουν[18:6 | instance no. 2]{.aside}

οσα εδοξασεν αυτην και [εστρηνιασεν]{.greek-omitted} [εστρηνιασε]{.greek-added} [τοσουτον]{.greek-omitted} [τοσουτο]{.greek-added} δοτε αυτη βασανισμον και πενθος οτι εν τη καρδια αυτης λεγει οτι [καθημαι]{.greek-omitted} [καθως]{.greek-added} βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

[δια]{.greek-omitted} [τουτο]{.greek-omitted} [διατουτο]{.greek-added} εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-omitted} [ο]{.greek-omitted} κρινας αυτην[18:8]{.aside}

και κλα[υ]{.unclear}σουσιν [και]{.greek-omitted} [κοψονται]{.greek-omitted} επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του βασανισμου αυτης λεγοντες ουαι ουαι η πολις η μεγαλη βαβυλων η πολις η ισχυρα οτι μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και πενθησουσιν επ αυτη οτι τον γομον αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και μαργαριτου και βυσσινου και πορφυρου [και]{.corr} [σηρικου]{.corr} και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κιναμωμου]{.greek-added} και θυμιαματα και μυρον και λιβανον [και]{.greek-omitted} [οινον]{.greek-omitted} και ελαιον και σεμιδαλιν και σιτον και προβατα και κτηνη και ιππων και ραιδων και σωματων [και]{.greek-omitted} [ψυχας]{.greek-omitted} [ανθρωπων]{.greek-omitted}[18:13]{.aside}

[και]{.greek-omitted} [κιναμωμον]{.greek-omitted} [και]{.greek-omitted} [θυμιαματα]{.greek-omitted} [και]{.greek-omitted} [μυρον]{.greek-omitted} [και]{.greek-omitted} [λιβανον]{.greek-omitted} [και]{.greek-omitted} [οινον]{.greek-omitted} [και]{.greek-omitted} [ελαιον]{.greek-omitted} [και]{.greek-omitted} [σεμιδαλιν]{.greek-omitted} [και]{.greek-omitted} [σιτον]{.greek-omitted} [και]{.greek-omitted} [προβατα]{.greek-omitted} [και]{.greek-omitted} [κτηνη]{.greek-omitted} [και]{.greek-omitted} [ιππων]{.greek-omitted} [και]{.greek-omitted} [ραιδων]{.greek-omitted} [και]{.greek-omitted} [σωματων]{.greek-omitted} και ψυχας [ανθρωπων]{.greek-abbr}[18:13 | instance no. 2]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα απωλετο απο σου και ουκετι αυτα ου μη ευρης[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες [απ]{.corr} [αυτης]{.corr} απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15]{.aside}

και λεγοντες [ουαι]{.greek-omitted} ουαι η πολις η μεγαλη η περιβεβλημενη [βυσσινον]{.greek-omitted} [βυσσον]{.greek-added} και πορφυρουν και κοκκινον και κεχρυσωμενη χρυσιω και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος και πας κυβερνητης και πας ο επι τοπον πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και [εκραζον]{.greek-omitted} [εκλαιον]{.greek-added} βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη πολει τη μεγαλη[18:18]{.aside}

και εβαλον χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες και λεγοντες ουαι ουαι η πολις η μεγαλη εν η επλουτησαν παντες οι εχοντες τα πλοια εν τη θαλασση εκ της τιμιοτητος αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την [θαλασσαν]{.greek-omitted} [θαλασσα]{.greek-added} λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδω[ν]{.unclear} [και]{.greek-omitted} [μουσικων]{.greek-omitted} [και]{.greek-omitted} [αυλητων]{.greek-omitted} [και]{.greek-omitted} [σαλπιστων]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [τεχνιτης]{.greek-omitted} [πασης]{.greek-omitted} [τεχνης]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22]{.aside}

και [αυλητων]{.greek-added} [φωνη]{.greek-omitted} [κιθαρωδων]{.greek-omitted} και μουσικων [και]{.greek-omitted} [αυλητων]{.greek-omitted} και σαλπιστων ου μη ακουσθη [ετι]{.greek-added} εν σοι [ετι]{.greek-omitted} και πας τεχνιτης πασης τεχνης ου μη ευρεθη [ετι]{.greek-added} εν σοι [ετι]{.greek-omitted} [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22 | instance no. 2]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [φανῆ]{.greek-added} [εν]{.greek-omitted} σοι ετι και φωνη νυμφιου και [φωνη]{.greek-added} νυμφης ου μη ακουσθη εν σοι ετι [οτι]{.greek-omitted} οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν τη φαρμακεια σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα ηκουσα ως φωνην μεγαλην οχλου πολλου εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η δυναμις και η δοξα του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [διεφθειρε]{.greek-added} την γην εν τη πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ [της]{.greek-added} χειρος αυτης[19:2]{.aside}

και δευτερον ειρηκεν αλληλουια και ο καπνος αυτης αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι [[κδ]{.greek-abbr}]{.greek-added} πρεσβυτεροι [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη απο του θρονου [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} λεγουσα αινειτε τον [θεον]{.greek-abbr} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα ως φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντων]{.greek-added} αλληλουια οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [ημων]{.greek-omitted} [ο]{.greek-omitted} [παντοκρατωρ]{.greek-omitted}[19:6]{.aside}

[και]{.greek-omitted} [ηκουσα]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} [οχλου]{.greek-omitted} [πολλου]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} [υδατων]{.greek-omitted} [πολλων]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} [βροντων]{.greek-omitted} [ισχυρων]{.greek-omitted} [λεγοντες]{.greek-omitted} [αλληλουια]{.greek-omitted} [οτι]{.greek-omitted} [εβασιλευσεν]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} ημων ο παντοκρατωρ[19:6 | instance no. 2]{.aside}

χαιρωμεν και αγαλλιωμεθα και δωμεν την δοξαν αυτω οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα [περιβαληται]{.greek-omitted} [περιβαλληται]{.greek-added} βυσσινον λαμπρον και καθαρον το γαρ βυσσινον τα δικαιωματα των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις το δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι αληθινοι του [θεου]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[19:9]{.aside}

και [επεσα]{.greek-omitted} [επεσον]{.greek-added} εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η [γαρ]{.corr} μαρτυρια του [ιησου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον καλουμενος πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου [διαδηματα]{.corr} [πολλα]{.corr} [ονοματα]{.greek-added} εχων [ονοματα]{.greek-omitted} γεγραμμενα και ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον [πορφυρουν]{.greek-added} βεβαμμενον αιματι και [καλειται]{.greek-omitted} [κεκληται]{.greek-added} το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα [του]{.greek-added} [τα]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} ηκολουθει αυτω [επι]{.greek-omitted} [εν]{.greek-added} ιπποις λευκοις [ενδεδυμενον]{.greek-added} ενδεδυμενοι βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει [αυτους]{.greek-omitted} [εν]{.greek-omitted} [ραβδω]{.greek-omitted} [σιδηρα]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [πατει]{.greek-omitted} [την]{.greek-omitted} [ληνον]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [παντοκρατορος]{.greek-omitted}[19:15]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτου]{.greek-omitted} [εκπορευεται]{.greek-omitted} [ρομφαια]{.greek-omitted} [διστομος]{.greek-omitted} [οξεια]{.greek-omitted} [ινα]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [παταξη]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ποιμανει]{.greek-omitted} αυτους εν ραβδω σιδηρα και αυτος πατει την ληνον του οινου του θυμου της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15 | instance no. 2]{.aside}

και εχει επι το ιματιον [αυτου]{.greek-added} και επι [τον]{.greek-omitted} [των]{.greek-added} [μηρον]{.greek-omitted} [μηρων]{.greek-added} [αυτου]{.greek-omitted} ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον αγγελον εστωτα εν τω ηλιω και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι δευτε συναχθητε εις το δειπνον [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} το μεγα [του]{.greek-omitted} [θεου]{.greek-omitted}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων και μικρων τε και μεγαλων[19:18]{.aside}

και ειδον το θηριον [της]{.greek-added} [γης]{.greek-added} και τους βασιλεις [της]{.greek-omitted} [γης]{.greek-omitted} και τα στρατευματα αυτων συνηγμενα ποιησαι [[τον]{.corr}]{.greek-added} πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον και ο μετ αυτου ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας [τη]{.greek-omitted} [την]{.greek-added} [εικονι]{.greek-omitted} [εικονα]{.greek-added} αυτου ζωντες εβληθησαν [οι]{.greek-omitted} [δυο]{.greek-omitted} εις την λιμνην του πυρος την καιομενην εν θειω [οι]{.greek-added} [δυο]{.greek-added}[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση [απο]{.greek-added} [του]{.greek-added} [στοματος]{.greek-added} εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} [εχοντα]{.greek-omitted} [την]{.greek-omitted} [κλειν]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [αλυσιν]{.greek-omitted} [μεγαλην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted} [αυτου]{.greek-omitted}[20:1]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [αγγελον]{.greek-omitted} [καταβαινοντα]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} εχοντα την κλειν της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1 | instance no. 2]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και [ο]{.greek-omitted} σατανας ο πλανων την οικουμενην ολην και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλεισε]{.greek-added} και εσφραγισεν επανω αυτου ινα μη πλανα ετι τα εθνη αχρι τελεσθη τα χιλια ετη [και]{.greek-omitted} μετα ταυτα δει [λυθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και ειδον θρονους και εκαθισαν επ αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} [και]{.corr} οιτινες ου προσεκυνησαν το θηριον ουδε την εικονα αυτου και ουκ ελαβον το χαραγμα επι το μετωπον και επι την χειρα αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} τα χιλια ετη[20:4]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [ουκ]{.greek-omitted} [εζησαν]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθη]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν τη αναστασει [αυτου]{.greek-added} τη πρωτη επι τουτων ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου χιλια ετη[20:6]{.aside}

και [οταν]{.greek-omitted} [τελεσθη]{.greek-omitted} [μετα]{.greek-added} [ταυτα]{.greek-added} τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} [γωνιας]{.greek-added} [γωνιαις]{.corr} της γης τον γωγ και τον μαγωγ συναγαγειν αυτους εις τον πολεμον ων ο αριθμος [ως]{.greek-omitted} [η]{.greek-omitted} [αυτων]{.greek-added} [ωσει]{.greek-added} αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το [πλα]{.greek-added} [πλατος]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [εκυκλωσαν]{.greek-omitted} [την]{.greek-omitted} [παρεμβολην]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [ηγαπημενην]{.greek-omitted} [και]{.greek-omitted} [κατεβη]{.greek-omitted} [πυρ]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [κατεφαγεν]{.greek-omitted} [αυτους]{.greek-omitted}[20:9]{.aside}

[και]{.greek-omitted} [ανεβησαν]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [τος]{.greek-added} [πλατος]{.greek-omitted} της γης και [εκυκλωσαν]{.greek-omitted} [εκυκλευσαν]{.greek-added} την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} και κατεφαγεν αυτους[20:9 | instance no. 2]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και θειου οπου και το θηριον και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10]{.aside}

και ειδον θρονον μεγαν λευκον και τον καθημενον επ αυτον ου απο προσωπου εφυγεν η γη και ο [ουρανος]{.greek-abbr} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον τους νεκρους [τους]{.greek-omitted} [μεγαλους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μικρους]{.greek-omitted} εστωτας ενωπιον του θρονου και βιβλια [ηνεωχθησαν]{.greek-omitted} [ηνοιξαν]{.greek-added} και αλλο βιβλιον [ηνεωχθη]{.greek-omitted} [ανεωχθη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν αυτη και ο θανατος και ο αδης εδωκαν τους νεκρους [τους]{.greek-omitted} [τοις]{.greek-added} εν αυτοις και εκριθησαν εκαστος κατα τα εργα [αυτων]{.greek-omitted} [αυτου]{.greek-added}[20:13]{.aside}

και ο θανατος και ο αδης εβληθησαν [εις]{.greek-omitted} [εχ]{.greek-added} την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ει τις ουχ ευρεθη εν τω βιβλιω της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη απηλθον και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν [απ]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} εκ του [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr} [ητοιμασμενην]{.greek-omitted} [ως]{.greek-omitted} [νυμφην]{.greek-omitted} [κεκοσμημενην]{.greek-omitted} [τω]{.greek-omitted} [ανδρι]{.greek-omitted} [αυτης]{.greek-omitted}[21:2]{.aside}

[και]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [αγιαν]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [καινην]{.greek-omitted} [ειδον]{.greek-omitted} [καταβαινουσαν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} ητοιμασμενην ως νυμφην κεκοσμημενην τω ανδρι αυτης[21:2 | instance no. 2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} [εσται]{.greek-omitted} μετ αυτων [εσται]{.greek-added}[21:3]{.aside}

και [εξαλειψει]{.greek-omitted} [εξαλειψη]{.greek-added} [απ]{.greek-added} [αυτων]{.greek-added} παν δακρυον απο των οφθαλμων αυτων και ο θανατος ουκ εσται ετι ουτε πενθος ουτε κραυγη ουτε πονος ουκ εσται ετι οτι τα πρωτα απηλθον[21:4]{.aside}

[και]{.greek-omitted} ειπεν ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} ιδου παντα καινα ποιω και λεγει μοι γραψον οτι ουτοι οι λογοι [πιστοι]{.greek-added} [και]{.greek-added} αληθινοι [και]{.greek-omitted} [πιστοι]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added}[21:5]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι γεγονα το [αλφα]{.greek-omitted} [[ἄλφα]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} [και]{.greek-added} η αρχη και το τελος εγω τω διψωντι δωσω [αυτω]{.greek-added} εκ της πηγης του υδατος της ζωης δωρεαν[21:6]{.aside}

ο νικων [κληρονομησει]{.greek-omitted} [δωσω]{.greek-added} [αυτω]{.greek-added} ταυτα και εσομαι αυτω [θεος]{.greek-abbr} και αυτος εσται μοι υιος[21:7]{.aside}

τοις δε δειλοις και απιστοις και αμαρτωλοις και εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} και πορνοις και [φαρμακοις]{.greek-omitted} [και]{.greek-omitted} ειδωλολατραις και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν τη λιμνη τη καιομενη πυρι και θειω ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} θανατος ο δευτερος[21:8]{.aside}

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας γεμουσας [των]{.greek-omitted} επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την γυναικα την νυμφην του αρνιου[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εν [πνευματι]{.greek-abbr} επ ορος μεγα και υψηλον και [εδει]{.greek-added} [εδειξεν]{.greek-omitted} [μοι]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [την]{.greek-omitted} [μεγαλην]{.greek-omitted} [την]{.greek-omitted} [αγιαν]{.greek-omitted} [ιερουσαλημ]{.greek-omitted} [καταβαινουσαν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[21:10]{.aside}

[ξε]{.greek-added} [και]{.greek-omitted} [απηνεγκεν]{.greek-omitted} [με]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [επ]{.greek-omitted} [ορος]{.greek-omitted} [μεγα]{.greek-omitted} [και]{.greek-omitted} [υψηλον]{.greek-omitted} [και]{.greek-omitted} [εδειξεν]{.greek-omitted} μοι την πολιν [την]{.greek-omitted} [μεγαλην]{.greek-omitted} την αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του [θεου]{.greek-abbr}[21:10 | instance no. 2]{.aside}

[εχουσαν]{.corr} [την]{.corr} [δοξαν]{.corr} [του]{.corr} [[θεου]{.greek-abbr}]{.corr} ο φωστηρ αυτης ομοιος λιθω τιμιωτατω ως λιθω ιασπιδι [κρυσταλλιζοντι]{.greek-omitted} [κρυσταλιζοντι]{.greek-added}[21:11]{.aside}

εχουσα τειχος μεγα και υψηλον εχουσα πυλωνας δωδεκα και επι τοις πυλωσιν αγγελους [δωδεκα]{.greek-omitted} [δεκαδυο]{.greek-added} και ονοματα επιγεγραμμενα α εστιν ονοματα των δωδεκα φυλων [των]{.greek-omitted} [υιων]{.greek-omitted} [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο ανατολων πυλωνες τρεις και απο βορρα πυλωνες τρεις και απο νοτου πυλωνες τρεις και απο δυσμων πυλωνες τρεις[21:13]{.aside}

και το τειχος της πολεως εχον θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} μετρον καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης [και]{.greek-omitted} [το]{.greek-omitted} [τειχος]{.greek-omitted} [αυτης]{.greek-omitted}[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον το πλατος [και]{.corr} [εμετρησεν]{.greek-omitted} [[εμετρησε]{.corr}]{.greek-added} [την]{.corr} [πολιν]{.corr} [[εν]{.corr}]{.greek-added} [τω]{.corr} [καλαμω]{.corr} [επι]{.corr} [σταδιους]{.corr} [δωδεκα]{.corr} [χιλιαδων]{.corr} [δωδεκα]{.corr} [[χιλιαδων]{.corr}]{.greek-added} [το]{.corr} [μηκος]{.corr} και το πλατος και το υψος αυτης ισα [εστιν]{.greek-omitted} [εστι]{.greek-added}[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} το τειχος αυτης [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρων]{.greek-omitted} πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον ομοιον [υελω]{.greek-omitted} [υαλω]{.greek-added} καθαρω[21:18]{.aside}

οι θεμελιοι του τειχους της πολεως παντι λιθω τιμιω κεκοσμημενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος [σαρδονυξ]{.greek-omitted} [σαρδωνυξ]{.greek-added} ο εκτος σαρδιον [ο]{.greek-omitted} [εβδομος]{.greek-omitted} [χρυσολιθος]{.greek-omitted} [ο]{.greek-omitted} [ογδοος]{.greek-omitted} [βηρυλλος]{.greek-omitted} [ο]{.greek-omitted} [ενατος]{.greek-omitted} [τοπαζιον]{.greek-omitted} [ο]{.greek-omitted} [δεκατος]{.greek-omitted} [χρυσοπρασος]{.greek-omitted} [ο]{.greek-omitted} [ενδεκατος]{.greek-omitted} [υακινθος]{.greek-omitted} [ο]{.greek-omitted} [δωδεκατος]{.greek-omitted} [αμεθυσος]{.greek-omitted}[21:20]{.aside}

[ο]{.greek-omitted} [πεμπτος]{.greek-omitted} [σαρδονυξ]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [σαρδιον]{.greek-omitted} ο εβδομος χρυσολιθος ο ογδοος βηρυλλος ο ενατος τοπαζιον ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος ο δωδεκατος αμεθυσος[21:20 | instance no. 2]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται ανα εις εκαστος των πυλωνων ην εξ ενος μαργαριτου και η πλατεια της πολεως χρυσιον καθαρον ως υελος διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-omitted} [ο]{.greek-omitted} παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν αυτη [γαρ]{.greek-added} η [γαρ]{.greek-omitted} δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης φερουσιν αυτω δοξαν και τιμην των εθνων εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και [την]{.greek-omitted} τιμην [εις]{.greek-added} [αυτην]{.greek-added} των εθνων [εις]{.greek-omitted} [αυτην]{.greek-omitted}[21:26]{.aside}

[ινα]{.greek-added} [εισελθωσι]{.greek-added} και ου μη εισελθη εις αυτην παν κοινον και [ποιουν]{.greek-omitted} [ποιων]{.greek-added} βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον [καθαρον]{.greek-omitted} υδατος ζωης λαμπρον ως κρυσταλλον εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης [και]{.greek-omitted} [του]{.greek-omitted} [ποταμου]{.greek-omitted} [εντευθεν]{.greek-omitted} [και]{.greek-omitted} [εκειθεν]{.greek-omitted} [ξυλον]{.greek-omitted} [ζωης]{.greek-omitted} [ποιουν]{.greek-omitted} [καρπους]{.greek-omitted} [δωδεκα]{.greek-omitted} [κατα]{.greek-omitted} [μηνα]{.greek-omitted} [εκαστον]{.greek-omitted} [αποδιδους]{.greek-omitted} [τον]{.greek-omitted} [καρπον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [εις]{.greek-omitted} [θεραπειαν]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted}[22:2]{.aside}

[εν]{.greek-omitted} [μεσω]{.greek-omitted} [της]{.greek-omitted} [πλατειας]{.greek-omitted} [αυτης]{.greek-omitted} και του ποταμου εντευθεν και εκειθεν ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα [αποδιδους]{.greek-added} εκαστον [αποδιδους]{.greek-omitted} τον καρπον αυτου και τα φυλλα του ξυλου εις θεραπειαν των εθνων[22:2 | instance no. 2]{.aside}

και παν καταθεμα ουκ εσται ετι και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι δουλοι αυτου λατρευσουσιν αυτω[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των μετωπων αυτων[22:4]{.aside}

και νυξ ουκ εσται [ουδε]{.greek-added} [εκει]{.greek-omitted} [και]{.greek-omitted} [χρειαν]{.greek-omitted} [χρεια]{.greek-added} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} λυχνου και φωτος [ηλιου]{.greek-omitted} οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} φωτιει αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και λεγει μοι ουτοι οι λογοι πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των πνευματων των προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου [δειξαι]{.corr} [τοις]{.corr} [δουλοις]{.corr} [αυτου]{.corr} α δει γενεσθαι εν ταχει[22:6]{.aside}

και ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

καγω ιωαννης [ο]{.greek-omitted} ακουων και βλεπων ταυτα και οτε ηκουσα [ταυτα]{.greek-added} [και]{.greek-omitted} [εβλεψα]{.greek-omitted} επεσον προσκυνησαι [εμπροσθεν]{.greek-omitted} [ενωπιον]{.greek-added} των ποδων του αγγελου του δεικνυοντος μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των προφητων [και]{.greek-omitted} των τηρουντων τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου ο καιρος γαρ εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος ρυπαρευθητω ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον εσται αυτου[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [[ἄλφα]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} ο πρωτος και ο εσχατος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι [φονεις]{.greek-omitted} [φωνεις]{.greek-added} και οι ειδωλολατραι και πας φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα επι ταις εκκλησιαις εγω ειμι η ριζα [[δαυιδ]{.greek-abbr}]{.greek-added} και το γενος [δαυιδ]{.greek-omitted} ο αστηρ ο λαμπρος ο πρωινος[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν ερχου και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων [λαμβαβετω]{.greek-added} [λαβετω]{.corr} υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι τω ακουοντι τους λογους της προφητειας του βιβλιου τουτου [εαν]{.greek-omitted} [τις]{.greek-omitted} [επιθη]{.greek-omitted} [επ]{.greek-omitted} [αυτα]{.greek-omitted} [επιθησαι]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted} [τας]{.greek-omitted} [πληγας]{.greek-omitted} [τας]{.greek-omitted} [γεγραμμενας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [τουτω]{.greek-omitted}[22:18]{.aside}

[μαρτυρω]{.greek-omitted} [εγω]{.greek-omitted} [παντι]{.greek-omitted} [τω]{.greek-omitted} [ακουοντι]{.greek-omitted} [τους]{.greek-omitted} [λογους]{.greek-omitted} [της]{.greek-omitted} [προφητειας]{.greek-omitted} [του]{.greek-omitted} [βιβλιου]{.greek-omitted} [τουτου]{.greek-omitted} εαν τις επιθη επ αυτα επιθησαι ο [θεος]{.greek-abbr} επ αυτον τας πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18 | instance no. 2]{.aside}

και εαν τις [αφελη]{.greek-omitted} [αφεληται]{.greek-added} απο των λογων του βιβλιου της προφητειας ταυτης αφελοι ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως [της]{.greek-omitted} [αγιας]{.greek-omitted} των γεγραμμενων εν τω βιβλιω τουτω[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην ναι ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} μετα παντων των αγιων αμην [δοξα]{.greek-added} [το]{.greek-added} [δοντι]{.greek-added} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added}[22:21]{.aside}

