---
title: "Collation of Byz^RP^ vs 31888 (1888)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 1888 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=31888).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 1888                                   	| λογος                              	|
| 1888 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 1888 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 1888               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 1888                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 1888 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 1888                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος εμαρτυρησεν [[εμαρτυρησε]{.corr}]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα ειδεν[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των επτα πνευματων α ενωπιον του θρονου αυτου[1:4]{.aside}

και απο ιησου χριστου [ο]{.greek-omitted} [ος]{.greek-added} μαρτυς [ο]{.greek-omitted} πιστος [εστιν]{.greek-added} ο πρωτοτ[ο]{.unclear}κος των νεκρων και ο αρχων των βασιλεων της γης [τω]{.greek-omitted} [αγαπωντι]{.greek-omitted} [ος]{.greek-added} [ηγαπησεν]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [ελουσεν]{.greek-added} ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας [απο]{.greek-added} [των]{.greek-added} [αμαρτι]{.greek-added} [ων]{.greek-added} [ημων]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [αιματι]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εποιησεν]{.greek-added} [ημας]{.greek-added} [βασιλεις]{.greek-added} [βασιλειαν]{.corr} ιερεις τω θεω και πατρι αυτου αυτω η δοξα και το κρατος εις τους αιωνα[ς]{.unclear} των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα [των]{.greek-omitted} νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξ[ε]{.unclear}κεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συγκοινωνος]{.greek-added} εν τη θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη [πατμω]{.greek-omitted} [πατμωι]{.greek-added} δια τον λογον του [θεου]{.greek-abbr} και [δια]{.greek-omitted} την μαρτυριαν ιησου [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα φωνην [οπισω]{.greek-omitted} [οπι]{.greek-added} [σω]{.greek-added} μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης [ο]{.greek-omitted} [α]{.greek-added} βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις σμυρναν και εις περγαμον και εις [θυατειρα]{.greek-omitted} [θυατειραν]{.greek-added} και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

και [εκει]{.greek-omitted} επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των επτα λυχνιων [των]{.greek-added} [χρυσων]{.greek-added} ομοιον [υιω]{.greek-omitted} [[υιον]{.greek-abbr}]{.greek-added} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον [προς]{.greek-omitted} [εν]{.greek-added} τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι [και]{.greek-added} ως εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν τη δεξια [χειρι]{.greek-added} αυτου [χειρι]{.greek-omitted} αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον επεσα προς τους ποδας αυτου ως νεκρος και εθηκεν την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας κλεις του θανατου και του [αδου]{.greek-omitted} [αιδου]{.greek-added}[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το [μυστηριον]{.greek-omitted} [μυστηριων]{.greek-added} των επτα αστερων ων ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν και αι [επτα]{.greek-added} λυχνιαι αι επτα [επτα]{.greek-omitted} εκκλησιαι εισιν[1:20]{.aside}

### Chapter 2

[[α]{.greek-abbr}]{.greek-added} τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει [[κυριος]{.greek-abbr}]{.greek-added} ο κρατων τους επτα αστερας εν τη δεξια [χειρι]{.greek-added} αυτου ο περιπατων εν μεσω των [ε]{.greek-added} [επτα]{.greek-omitted} [πτα]{.greek-added} λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ εισιν και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις και εβαστασας δια το ονομα μου και [ουκ]{.greek-omitted} [οὐκ]{.greek-added} [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

αλλα εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν [τω]{.greek-omitted} [μεσω]{.greek-added} [του]{.greek-added} [παραδεισω]{.greek-omitted} [παραδεισου]{.greek-added} του θεου μου[2:7]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν [σου]{.greek-added} εκ των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βάλλειν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

[[γ]{.greek-abbr}]{.greek-added} και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις εν αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} [και]{.greek-added} ο μαρτυς μου ο πιστος [ος]{.greek-omitted} απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος εδιδαξεν [[εδιδαξε]{.corr}]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} και φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην [των]{.greek-omitted} νικολαιτων ομοιως[2:15]{.aside}

μετανοησον ουν ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω του μαννα [φαγειν]{.greek-added} του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο υιος του θεου ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου οτι αφεις την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει [[κυριος]{.greek-abbr}]{.greek-added} ο εχων τα επτα πνευματα του θεου και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [στηριξον]{.greek-added} τα λοιπα α [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [εμελλον]{.greek-added} [αποθανειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη γρηγορησης ηξω [επι]{.greek-omitted} [επισε]{.greek-added} [σε]{.greek-omitted} ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωση]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του πατρος μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις[3:6]{.aside}

[[ϛ]{.greek-abbr}]{.greek-added} και τω αγγελω της εν φιλαδελφεια εκκλησιας γραψον ταδε λεγει [κυριος]{.greek-added} ο αγιος [ο]{.greek-omitted} [και]{.greek-added} αληθινος ο εχων την κλειν [του]{.greek-omitted} [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει [και]{.greek-added} [κλειων]{.greek-added} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} και ουδεις ανοιξει[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν [ανεωγμενην]{.greek-omitted} [ηνεωγμενην]{.greek-added} ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του θεου μου και το ονομα της πολεως του θεου μου της καινης ιερουσαλημ η καταβαινει [εκ]{.greek-omitted} [απο]{.greek-added} του [ουρανου]{.greek-abbr} απο του θεου μου και το ονομα μου το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το πνευμα λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτ[υς]{.unclear} ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος οφελον ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος μελλω σε [εμεσαι]{.greek-omitted} [αιμεσαι]{.greek-added} εκ του στοματος μου[3:16]{.aside}

οτι λεγεις [οτι]{.greek-added} πλουσιος ειμι και πεπλουτηκα και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και ο ελεεινος και πτωχος και τυφλ[ος]{.unclear} και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορ[α]{.unclear}σαι χρυσιον [παρ]{.greek-omitted} [εμου]{.greek-omitted} πεπυρωμενον εκ [πυ]{.unclear}ρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος σου και κολλυριον ινα εγχριση τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλευε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν και εισελευσομαι προς αυτον και [δ]{.unclear}ειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω ουρανω και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι τον θρονον καθημενος[4:2]{.aside}

ομοιος ορασει λιθω ιασπιδι και σαρδιω και [ιρις]{.greek-omitted} [ἴρις]{.greek-added} κυκλοθεν του θρονου [ομοιως]{.greek-omitted} [ομοια]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδω]{.greek-added}[4:3]{.aside}

και κυκλοθεν του θρονου [θρονοι]{.greek-omitted} [θρονους]{.greek-added} [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} και επι τους θρονους τους [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται [αστραπαι]{.greek-omitted} [αστρα]{.greek-added} [παι]{.greek-added} και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα πνευματα του θεου[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον εχον προσωπον [ανθρωπου]{.greek-abbr} και το τεταρτον [ζωον]{.greek-omitted} ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} [εστως]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} [αγιος]{.greek-added} κυριος ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσι]{.greek-added} τα [τεσσαρα]{.greek-added} ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο θεος ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας [τα]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισι]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον [αλλον]{.greek-added} αγγελον ισχυρον κ[η]{.unclear}ρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο εν τω ουρανω ανω ουτε επι της γης ουτε υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησε[ν]{.unclear} ο λεων ο εκ της φυλης ιουδα η ριζα δαυιδ ο ανοιγων το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον [και]{.greek-added} [ιδου]{.greek-added} εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον [εστηκος]{.greek-omitted} [εστηκως]{.greek-added} ως εσφαγμενον εχον κερατα επτα και οφθαλμους επτα α [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα πνευματα του [θεου]{.greek-abbr} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και ηλθεν και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι επεσον ενωπιον του αρνιου εχοντες εκαστος κιθαραν και φιαλας χρυσας γεμουσας θυμιαματων αι [εισιν]{.greek-omitted} [εισι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} [καινην]{.greek-added} ωδην [καινην]{.greek-omitted} λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας [ημας]{.greek-added} τω θεω [ημας]{.greek-omitted} εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και ειδον και ηκουσα ως φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και τον πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν τω [ουρανω]{.greek-abbr} και επι της γης και υποκατω της γης και επι της θαλασσης [οσα]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις [παντας]{.greek-omitted} [παντα]{.greek-added} [και]{.greek-added} ηκουσα [λεγοντας]{.greek-omitted} [λεγοντων]{.greek-added} τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων [αμην]{.greek-omitted}[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγεν]{.greek-added} το αμην και οι πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και προσεκυνησαν [α]{.greek-added}[5:14]{.aside}

### Chapter 6

και ειδον οτι ηνοιξεν το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνὴ]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ιδε]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα νικηση [β]{.greek-added}[6:2]{.aside}

και οτε ηνοιξεν την [σφραγιδα]{.greek-added} [την]{.greek-added} δευτεραν [σφραγιδα]{.greek-omitted} ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και [ιδε]{.greek-added} [και]{.greek-added} [ειδον]{.greek-added} [και]{.greek-added} [ιδου]{.greek-added} εξηλθεν αλλος ιππος πυρος και τω καθημενω επ αυτον εδοθη αυτω λαβειν την ειρηνην εκ της γης [και]{.greek-added} ινα αλληλους [σφα]{.greek-added} [σφαξωσιν]{.greek-omitted} [ξωσιν]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε ηνοιξεν την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και ιδε και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες κριθης δηναριου [και]{.greek-omitted} το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου και ιδε[6:7]{.aside}

και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης ηκολουθει αυτω και εδοθη αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε ηνοιξεν την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των εσφαγμενων δια τον λογον του θεου και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} [[χριστου]{.greek-abbr}]{.greek-added} ην ειχον[6:9]{.aside}

και εκραξαν [φωνη]{.greek-omitted} [φωνην]{.greek-added} [μεγαλη]{.greek-omitted} [μεγαλην]{.greek-added} λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα αναπαυσωνται ετι [χρονον]{.greek-omitted} [χρονων]{.greek-added} εως [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκτεννεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

[[ϛ]{.greek-abbr}]{.greek-added} και ειδον οτε [ηνοιξεν]{.greek-omitted} [ην[οι]{.unclear}ξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος μελας εγενετο ως σακκος τριχινος και η σεληνη ολη εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλουσα]{.greek-added} τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον ελισσομενον και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι [τω]{.greek-added} [θρονω]{.greek-added} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται [σταθηναι]{.greek-omitted} [στηναι]{.greek-added}[6:17]{.aside}

### Chapter 7

και μετα τουτο ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους τεσσαρας ανεμους [επι]{.greek-added} της γης ινα μη [πνεη]{.greek-omitted} [πνευση]{.greek-added} ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα θεου ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του θεου ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον [των]{.greek-omitted} [τον]{.greek-added} εσφραγισμενων εκατον [και]{.greek-omitted} τεσσαρακοντα τεσσαρες χιλιαδες εσφραγισμενων εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης [ρουβιμ]{.greek-omitted} [ρουβειν]{.greek-added} δωδεκα χιλιαδες εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ δωδεκα χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι δωδεκα χιλιαδες εκ φυλης ισαχαρ δωδεκα χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων δωδεκα [χιλιαδες]{.greek-omitted} [χιλιαδας]{.greek-added} εκ φυλης ιωσηφ δωδεκα [χιλιαδες]{.greek-omitted} [χιλιαδας]{.greek-added} εκ φυλης [βε]{.greek-added} [βενιαμιν]{.greek-omitted} [νιαμιν]{.greek-added} δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εκ παντος εθνους και φυλων και λαων και γλωσσων εστωτας ενωπιον του θρονου και ενωπιον του αρνιου περιβεβλημενους στολας λευκας και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραξουσι]{.greek-added} φωνη μεγαλη λεγοντες η σωτηρια τω θεω ημων τω καθημενω επι τω θρονω και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου [αυτου]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον αυτω κυριε μου συ οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν [ετι]{.greek-omitted} ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου ποιμαινει αυτους και οδηγει αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην [και]{.greek-added} εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος ηλθεν και εσταθη επι του θυσιαστηριου εχων λιβανωτον χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δωσει]{.greek-added} ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του θεου[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} βρονται και φωναι και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος εσαλπισεν και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και [εβληθη]{.greek-omitted} [εβληθησαν]{.greek-added} εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

[[β]{.greek-abbr}]{.greek-added} και ο δευτερος αγγελος εσαλπισεν και ως ορος μεγα [πυρι]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον [μερος]{.greek-added} της θαλασσης αιμα[8:8]{.aside}

και απεθανεν το τριτον [μερος]{.greek-added} των κτισματων [των]{.greek-added} εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη [γ]{.greek-added}[8:9]{.aside}

και ο τριτος αγγελος εσαλπισεν και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

[[δ]{.greek-abbr}]{.greek-added} και ο τεταρτος αγγελος εσαλπισεν και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων [ινα]{.greek-omitted} [και]{.greek-added} [σκοτισθη]{.greek-omitted} [εσκοτισθη]{.greek-added} το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [ουκ]{.greek-added} [εφαινεν]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος αετου πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος εσαλπισεν και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και ηνοιξεν το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος [ως]{.greek-omitted} [ωσπερ]{.greek-added} καπνος καμινου καιομενης και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και [ερρεθη]{.greek-omitted} [ερρηθη]{.greek-added} [αυταις]{.greek-omitted} [αυτοις]{.greek-added} ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και εδοθη αυταις ινα μη [αποκτεινωσιν]{.greek-omitted} [αποκτεινω]{.greek-added} [σιν]{.greek-added} αυτους αλλ ινα βασανισθωσιν μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν παιση [ανθρωπον]{.greek-omitted} [ανθρωπων]{.greek-added}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι ανθρωποι τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [εὕρωσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και φευξεται απ αυτων ο θανατος[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι [χρυσοι]{.greek-omitted} [ομοιοι]{.greek-added} [χρυσω]{.greek-added} και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[εχουσαι]{.greek-omitted} [και]{.greek-added} [εχου]{.greek-added} [σι]{.greek-added} βασιλεα επ αυτων [αγγελον]{.greek-omitted} [αγγελων]{.greek-added} της αβυσσου ονομα αυτω εβραιστι [αββαδων]{.greek-omitted} [αββααδων]{.greek-added} εν δε τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και ηκουσα φωνην [μιαν]{.greek-omitted} [μεγαλην]{.greek-added} εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

λεγουσαν τω εκτω αγγελω [ο]{.greek-omitted} [εχων]{.greek-omitted} [τω]{.greek-added} [εχοντι]{.greek-added} την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των ανθρωπων[9:15]{.aside}

και ο αριθμος των στρατευματων του ιππου μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλ[αι]{.unclear} λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των ανθρωπων απο του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι οφεων εχουσαι κεφαλας και εν αυταις αδικουσιν[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και εχων εν τη χειρι αυτου βιβλιον [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε [[οσαι]{.corr}]{.greek-added} [[τε]{.corr}]{.greek-added} ελαλησαν αι επτα βρονται εμελλον [[εμελλον]{.corr}]{.greek-added} [[αυτα]{.corr}]{.greek-added} γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης ηρεν την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμοσε]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος εκτισεν τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} σαλπιζειν και ετελεσθη το μυστηριον του θεου ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα μετ εμου και λεγουσα υπαγε λαβε το βιβλιδαριον το [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γ[ης]{.unclear}[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω δουναι μοι το βιβλιδαριον και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το βιβλιον εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [ἀυτό]{.greek-added} και ην εν τω στοματι μου ως μελι [γλυκυ]{.greek-omitted} [γλυκι]{.greek-added} και [οτε]{.greek-omitted} [εφαγον]{.greek-omitted} [αυτο]{.greek-omitted} επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω [και]{.greek-added} [ειστηκει]{.greek-added} [ο]{.greek-added} [αγγελος]{.greek-added} λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την [εξωθεν]{.greek-omitted} [εσωθεν]{.greek-added} του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην μετρησης οτι εδοθη τοις εθνεσιν και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα [και]{.greek-omitted} δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι [αι]{.greek-omitted} ενωπιον του [κυριου]{.greek-abbr} της γης [εστωσαι]{.greek-omitted} [εστωτες]{.greek-added}[11:4]{.aside}

και ει τις [θελει]{.greek-added} αυτους [θελει]{.greek-omitted} αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους αδικησαι ουτως δει [αυτον]{.greek-omitted} [αποκτανθηναι]{.greek-omitted} [αυτους]{.greek-added} [αποκταν]{.greek-added} [θηναι]{.greek-added}[11:5]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον [ουρανον]{.greek-abbr} εξουσιαν κλεισαι ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην οσακις εαν θελησωσιν εν παση πληγη[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και το [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου [και]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφησουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και ευφρανθησονται και δωρα δωσουσιν αλληλοις οτι [ουτοι]{.greek-omitted} οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν εις αυτους και [εστησαν]{.greek-omitted} [εστησα]{.greek-added} επι τους ποδας αυτων και φοβος μεγας επεσεν επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον ουρανον εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη ημερα εγενετο σεισμος μεγας και το δεκατον της πολεως επεσεν και απεκτανθησαν εν τω σεισμω ονοματα ανθρωπων χιλια[δ]{.unclear}ες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν η ουαι η τριτη ιδου ερχεται [ταχυ]{.greek-omitted}[11:14]{.aside}

και ο εβδομος αγγελος εσαλπισεν και εγενοντο φωναι μεγαλαι εν τω ουρανω λεγουσαι εγενετο η βασιλεια του κοσμου του κυριου ημων και του χριστου αυτου και [βασιλευσει]{.greek-omitted} [βασιλευει]{.greek-added} εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες [πρε]{.greek-added} [πρεσβυτεροι]{.greek-omitted} [σβυτεροι]{.greek-added} οι ενωπιον του θρονου του [θεου]{.greek-abbr} [καθημενοι]{.greek-omitted} [οι]{.greek-added} [καθηνται]{.greek-added} επι τους θρονους αυτω[ν]{.unclear} επεσον επι τα προσωπα αυτων [και]{.greek-omitted} [επε]{.greek-added} προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους [διαφθειροντας]{.greek-omitted} [διαφθειραντας]{.greek-added} την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} [ο]{.greek-added} εν τω [ουρανω]{.greek-omitted} [ουρανωι]{.greek-added} και ωφθη η κιβωτος της διαθηκης [του]{.greek-omitted} [αυτου]{.greek-added} [κυριου]{.greek-omitted} εν τω ναω αυτου και εγενοντο αστραπαι και [βρονται]{.greek-added} [και]{.greek-added} φωναι και [βρονται]{.greek-omitted} [σεισμοι]{.greek-added} και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα [εκραζεν]{.greek-omitted} [εκραξεν]{.greek-added} ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων πυρος μεγας εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του ουρανου και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἕστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη [αυτο]{.greek-added}[12:4]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα [τα]{.greek-added} τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον θεον και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του δρακοντος και ο δρακων επολεμησεν και οι αγγελοι αυτου[12:7]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη [αυ]{.greek-added} [[ευρε]{.corr}]{.greek-added} [θη]{.greek-added} αυτω ετι εν τω ουρανω[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και [ο]{.greek-added} σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω ουρανω λεγουσαν αρτι εγενετο η σωτηρια και η δυναμις και η βασιλεια του θεου ημων και η εξουσια του χριστου αυτου οτ[ι]{.unclear} εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του θεου ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν [την]{.greek-omitted} [ψυχην]{.greek-omitted} [τας]{.greek-added} [ψυχας]{.greek-added} αυτων αχρι θανατου[12:11]{.aside}

δια [τουτο]{.greek-omitted} [του]{.greek-added} ευφραινεσθε ουρανοι και οι εν αυτοις σκηνουντες ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην εδιωξεν την γυναικα ητις ετεκεν τον αρρενα[12:13]{.aside}

και εδοθησαν τη γυναικι δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον αυτης οπως [τρεφηται]{.greek-omitted} [τρεφειται]{.greek-added} εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον ποιηση[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [η]{.greek-omitted} [γη]{.greek-omitted} το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι τη γυναικι και απηλθεν ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του θεου και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθη]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον εχον κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον [ομοιον]{.greek-added} ην [ομοιον]{.greek-omitted} παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου ωσει εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [οτι]{.greek-added} [εδωκεν]{.greek-added} την εξουσιαν τω θηριω και προσεκυνησαν τω θηριω λεγοντες τις ομοιος τω θηριω και τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημα]{.greek-added} και εδοθη αυτω εξουσια πολεμον ποιησαι μηνας τεσσαρακοντα δυο[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις [βλασφημιαν]{.greek-omitted} [βλασφημιας]{.greek-added} προς τον θεον βλασφημησαι το ονομα αυτου και την σκηνην αυτου τους εν τω ουρανω σκηνουντας[13:6]{.aside}

και εδοθη αυτω [πολεμον]{.greek-added} ποιησαι [πολεμον]{.greek-omitted} μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και λαον και γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες επι της γης ων ου γεγραπται το ονομα εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} [αιχμαλωσιαν]{.greek-added} [απαγει]{.greek-added} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν [μαχαιρα]{.greek-omitted} [μαχαιρη]{.greek-added} [αποκτενει]{.greek-omitted} [ἀποκτέννει]{.greek-added} δει αυτον εν μαχαιρα [αποκτανθηναι]{.greek-omitted} [ἀποκτανθῆναι]{.greek-added} ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και ειχεν κερατα δυο ομοια αρνιω και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν [ποιει]{.greek-omitted} [ποιησει]{.greek-added} ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιησει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} [το]{.greek-omitted} [θηριον]{.greek-omitted} [το]{.greek-omitted} [πρωτον]{.greek-omitted} [τω]{.greek-added} [θηριω]{.greek-added} [τω]{.greek-added} [πρωτω]{.greek-added} ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και [ποιει]{.greek-omitted} [ποιησει]{.greek-added} [μεγαλα]{.greek-added} [εκ]{.greek-added} [[μεγαλα]{.corr}]{.greek-added} [σημεια]{.corr} [[ιν[α]{.unclear}]{.corr}]{.greek-added} [μεγαλα]{.greek-omitted} [και]{.greek-omitted} [[πυρ]{.unclear}]{.corr} [ινα]{.greek-omitted} [[ηση]{.corr}]{.greek-added} [εκ]{.corr} του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [καταβηναι]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} την γην ενωπιον των ανθρωπων[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [ὃς]{.greek-added} [εχει]{.greek-added} την πληγην [της]{.greek-added} [μαχαιρας]{.greek-added} και εζησεν [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

και εδοθη αυτω [πνευμα]{.greek-abbr} δουναι τη εικονι του θηριου ινα και λαληση η εικων του θηριου και ποιηση οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τη εικονι του θηριου αποκτανθωσιν[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} αυτοις [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της χειρος αυτων της δεξιας η επι το μετωπον αυτων[13:16]{.aside}

και ινα [μηδεις]{.greek-added} [μη]{.greek-omitted} [τις]{.greek-omitted} [δυναται]{.greek-omitted} [δυνηται]{.greek-added} [πωλησαι]{.greek-added} [η]{.greek-added} αγορασαι [ετι]{.greek-added} [η]{.greek-omitted} [πωλησαι]{.greek-omitted} ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ ανθρωπου εστιν [και]{.greek-omitted} ο αριθμος αυτου [[χξς]{.greek-abbr}]{.greek-added} [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και ειδον και ιδου [το]{.greek-omitted} αρνιον [εστηκος]{.greek-omitted} [εστως]{.greek-added} επι το ορος σιων και μετ αυτου αριθμος εκατον [τεσσαρακοντα]{.greek-omitted} τεσσαρες χιλιαδες εχουσαι το ονομα αυτου και το ονομα του πατρος αυτου γεγραμμενον επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του ουρανου ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλης και η φωνη ην ηκουσα ως κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και [ενωπιον]{.greek-omitted} [ενω]{.greek-added} [πιον]{.greek-added} των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει μη αι εκατον τεσσαρακοντα τεσσαρες χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι εισιν οι ακολουθουντες τω αρνιω οπου αν υπαγη ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} ηγορασθησαν απο των ανθρωπων απαρχη τω θεω και τω αρνιω[14:4]{.aside}

και ουχ ευρεθη εν τω στοματι αυτων ψευδος αμωμοι γαρ εισιν [ουτοι]{.greek-added} [εισιν]{.greek-added} [οι]{.greek-added} [ακολουθουντες]{.greek-added} [τω]{.greek-added} [αρνιω]{.greek-added}[14:5]{.aside}

και ειδον αγγελον [αλλον]{.greek-added} πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον [ευαγγελισαι]{.greek-omitted} [ευαγγελισασθαι]{.greek-added} [επι]{.greek-added} τους καθημενους επι της γης και επι παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-abbr} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε [τω]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [ποιησαντι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και [την]{.greek-omitted} θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος δευτερος αγγελος [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων [επεσεν]{.greek-omitted} [επεσε]{.greek-added} βαβυλων η μεγαλη [η]{.greek-added} εκ του οινου του θυμου της πορνειας αυτης [πεποτικεν]{.greek-omitted} [πεποτηκε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει [το]{.greek-added} χαραγμα επι του μετωπου αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου [αυτου]{.greek-added} [του]{.corr} θεου του κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις αιωνας αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν οι τηρουντες τας εντολας του θεου και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το πνευμα ινα αναπαυσωνται εκ των κοπων αυτων τα δε εργα αυτων ακολουθει μετ αυτων[14:13]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην καθημενον ομοιον υιω [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και [αγγελος]{.greek-added} αλλος [αγγελος]{.greek-omitted} εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι [ηκμασαν]{.greek-omitted} [ηκμασεν]{.greek-added} [αι]{.greek-omitted} [σταφυλαι]{.greek-omitted} [σταφυλη]{.greek-added} [αυτης]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[14:18]{.aside}

και [εβαλεν]{.greek-omitted} [εξεβαλεν]{.greek-added} ο αγγελος το δρεπανον αυτου εις την γην και ετρυγησεν την αμπελον της γης και εβαλεν εις την ληνον [την]{.greek-added} [μεγαλην]{.greek-added} του θυμου του θεου [τον]{.greek-omitted} [μεγαν]{.greek-omitted}[14:19]{.aside}

και επατηθη η ληνος εξωθεν της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω ουρανω μεγα και θαυμαστον αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του θεου[15:1]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην [την]{.greek-added} [μεμιγμενην]{.greek-added} [πυρι]{.greek-added} εχοντας [τας]{.greek-added} κιθαρας του θεου[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην μωυσεως [του]{.greek-omitted} δουλου του θεου και την [ωδην]{.greek-omitted} [φωνην]{.greek-added} του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη [φοβηθη]{.greek-omitted} [φοβηθησε]{.greek-added} [σε]{.greek-omitted} [κυριε]{.greek-abbr} και δοξαση το ονομα σου οτι μονος αγιος οτι [παντες]{.greek-added} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν τω ουρανω[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας [εκ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} οι ησαν ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων ζωων εδωκεν τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του θεου του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος [εκ]{.greek-added} [του]{.greek-added} καπνου εκ της δοξης του θεου και εκ της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας επτα φιαλας του θυμου του θεου εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος [αγγελος]{.greek-added} και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως [νε]{.greek-added} [νεκρου]{.greek-omitted} [και]{.greek-omitted} [πασα]{.greek-omitted} [ψυχη]{.greek-omitted} [ζωσα]{.greek-omitted} [απεθανεν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted}[16:3]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [πεμπτος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [θρονον]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [και]{.greek-omitted} εγενετο η βασιλεια αυτου εσκοτωμενη και [εμασωντο]{.greek-omitted} [εμασσωντο]{.greek-added} τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του ουρανου εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [εξεχεεν]{.greek-omitted} [αγγελοςεξεχεε]{.greek-added} την φιαλην αυτου επι τον ποταμον τον μεγαν [τον]{.greek-added} ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο ανατολης ηλιου[16:12]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα ακαθαρτα τρια ως βατραχοι[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ πνευματα δαιμονιων ποιουντα σημεια α εκπορευεται επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του θεου του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἁρμαγεδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη απο του ναου του ουρανου απο του θρονου λεγουσα γεγονεν[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και φωναι και σεισμος μεγας οιος ουκ εγενετο αφ ου οι [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων επεσον και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα νησος εφυγεν και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως [ταλαντιαια]{.greek-omitted} [ταλαντιεα]{.greek-added} καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη αυτης σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον [το]{.greek-added} κοκκινον γεμον [ονοματα]{.greek-omitted} [ονοματων]{.greek-added} βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἣν]{.greek-added} περιβεβλημενη πορφυρουν και κοκκινον [περι]{.greek-added} κεχρυσωμενη χρυσιω και λιθω τιμιω και μαργαριταις εχουσα ποτηριον χρυσουν εν τη χειρι αυτης γεμον βδελυγματων και τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η μητηρ των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον [την]{.greek-omitted} γυναικα μεθυουσαν εκ του αιματος των αγιων εκ του αιματος των μαρτυρων ιησου και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και ειπεν μοι ο αγγελος δια τι εθαυμασας εγω ερω σοι το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ εστιν και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων ου γεγραπται [τα]{.greek-omitted} [το]{.greek-added} [ονοματα]{.greek-omitted} [ονομα]{.greek-added} επι [το]{.greek-omitted} [του]{.greek-added} [βιβλιον]{.greek-omitted} [βιβλιου]{.greek-added} της ζωης απο καταβολης κοσμου βλεποντων οτι ην το θηριον και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [εισιν]{.greek-added} [επτα]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε επεσον ο εις εστιν ο αλλος ουπω ηλθεν και οταν ελθη ολιγον δει αυτον μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και [αυτος]{.greek-omitted} [ουτος]{.greek-added} ογδοος εστιν και εκ των επτα [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν λαμβανουσιν μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} γνωμην και την δυναμιν και την εξουσιαν αυτων τω θηριω διδοασιν[17:13]{.aside}

[ουτοι]{.greek-omitted} [ουτο]{.greek-added} μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει [αυτους]{.greek-omitted} [αυτοις]{.greek-added} οτι [κυριος]{.greek-omitted} [κυριως]{.greek-added} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου κλητοι και [πιστοι]{.greek-added} [και]{.greek-added} εκλεκτοι [και]{.greek-omitted} [πιστοι]{.greek-omitted}[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και [οχλοι]{.greek-omitted} [εθνη]{.greek-added} εισιν και [εθνη]{.greek-omitted} [οχλοι]{.greek-added} και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησωσι]{.greek-added} την πορνην και ηρημωμενην [ποιησουσιν]{.greek-omitted} [ποιησωσιν]{.greek-added} αυτην και γυμνην [ποιησουσιν]{.greek-omitted} [ποιησωσιν]{.greek-added} αυτην και τας σαρκας αυτης [φαγονται]{.greek-omitted} [φαγωνται]{.greek-added} και αυτην [κατακαυσουσιν]{.greek-omitted} [κατακαυσωσι]{.greek-added} [εν]{.greek-omitted} πυρι[17:16]{.aside}

ο γαρ θεος εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι γνωμην [μιαν]{.greek-omitted} [αυτων]{.greek-added} και δουναι την βασιλειαν αυτων τω [θηριω]{.greek-omitted} [θηριωι]{.greek-added} αχρι τελεσθωσιν οι λογοι του θεου[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του ουρανου εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν ισχυρα φωνη λεγων [επεσεν]{.greek-added} επεσεν βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος πνευματος ακαθαρτου και φυλακη παντος ορνεου ακαθαρτου και μεμισημενου [και]{.greek-added} [φυλακη]{.greek-added} [παντος]{.greek-added} [θηριου]{.greek-added} [και]{.greek-added} [μεμισημενου]{.greek-added}[18:2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκασιν]{.greek-added} παντα τα εθνη και οι [βα]{.greek-added} [βασιλεις]{.greek-omitted} [σιλεις]{.greek-added} της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν εξελθε εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του ουρανου και εμνημονευσεν [αυτης]{.greek-added} ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη [απεδωκεν]{.greek-omitted} [και]{.greek-omitted} [διπλωσατε]{.greek-omitted} [αυτη]{.greek-omitted} διπλα [κατα]{.greek-omitted} τα εργα αυτης εν τω ποτηριω [ω]{.greek-omitted} [αυτης]{.greek-added} [ως]{.greek-added} εκερασεν κερασατε αυτη διπλουν[18:6]{.aside}

[οσα]{.greek-omitted} [ως]{.greek-added} εδοξασεν [αυτην]{.greek-omitted} [εαυτην]{.greek-added} και εστρηνιασεν τοσουτον δοτε αυτη βασανισμον και πενθος οτι εν τη καρδια αυτης λεγει οτι [εγω]{.greek-added} καθημαι βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος [και]{.greek-omitted} πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος κυριος ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσουσι]{.greek-added} και κοψονται επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του βασανισμου αυτης λεγοντες ουαι ουαι [ουαι]{.greek-added} η πολις η μεγαλη [η]{.greek-added} βαβυλων η πολις η ισχυρα οτι μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαισουσι]{.greek-added} και πενθησουσιν επ [αυτη]{.greek-omitted} [αυτης]{.greek-added} [[αυτην]{.corr}]{.greek-added} οτι τον γομον [αυτων]{.greek-omitted} [αυτης]{.greek-added} ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και [μαργαριτου]{.greek-omitted} [μαργαριτων]{.greek-added} και βυσσινου και [πορφυρου]{.greek-omitted} [πορφυρας]{.greek-added} και [σηρικου]{.greek-omitted} [σιρικου]{.greek-added} και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και κιναμωμον [και]{.greek-added} [αμωμον]{.greek-added} και θυμιαματα και μυρον και λιβανον και [σεμιδαλιν]{.greek-added} [και]{.greek-added} οινον και ελαιον [και]{.greek-omitted} [σεμιδαλιν]{.greek-omitted} και σιτον και προβατα και κτηνη και ιππων και [ραιδων]{.greek-omitted} [ρεδων]{.greek-added} και σωματων [και]{.greek-omitted} ψυχας ανθρωπων[18:13]{.aside}

και η οπωρα [σου]{.greek-added} της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα [απωλετο]{.greek-omitted} [απωλοντο]{.greek-added} απο σου και ουκετι [αυτα]{.greek-omitted} ου μη [ευρης]{.greek-omitted} [αυτα]{.greek-added} [ευρησουσιν]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες [και]{.greek-added}[18:15]{.aside}

[και]{.greek-omitted} λεγοντες [ουαι]{.greek-added} ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον και κεχρυσωμενη χρυσιω και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος και πας κυβερνητης και πας ο επι τοπον πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και [εκραζον]{.greek-omitted} [εκραξαν]{.greek-added} βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη πολει τη μεγαλη[18:18]{.aside}

και εβαλον χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες [και]{.greek-omitted} λεγοντες [ουαι]{.greek-added} ουαι ουαι η πολις η μεγαλη εν η επλουτησαν παντες οι εχοντες [τα]{.greek-omitted} πλοια εν τη θαλασση εκ της τιμιοτητος αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} [ουρανε]{.greek-abbr} και οι αγιοι και οι αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και [σαλπιστων]{.greek-omitted} [σαλπιγγων]{.greek-added} ου μη ακουσθη εν σοι ετι και πας τεχνιτης πασης τεχνης ου μη ευρεθη εν σοι ετι [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22]{.aside}

[και]{.greek-omitted} [φως]{.greek-omitted} [λυχνου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} και φωνη νυμφιου και νυμφης ου μη ακουσθη εν σοι ετι οτι οι εμποροι σου ησαν οι [μεγιστανες]{.greek-omitted} [μεγιστανοι]{.greek-added} της γης οτι εν τη [φαρμακεια]{.greek-omitted} [φαρμακια]{.greek-added} σου [επλανηθησαν]{.greek-omitted} [επλανησας]{.greek-added} παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

μετα ταυτα ηκουσα ως φωνην μεγαλην οχλου πολλου εν τω ουρανω λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η σωτηρια και η δυναμις και η δοξα του θεου ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [εφθειρε]{.greek-added} την γην εν τη πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ χειρος αυτης[19:2]{.aside}

και [εκ]{.greek-added} [δευτερον]{.greek-omitted} [δευτερου]{.greek-added} [ειρηκεν]{.greek-omitted} [ειρηκαν]{.greek-added} αλληλουια και ο καπνος αυτης [αναβαινει]{.greek-omitted} [ανεβαινεν]{.greek-added} εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι πρεσβυτεροι οι εικοσι τεσσαρες και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη απο του θρονου [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} λεγουσα αινειτε [τον]{.greek-added} τον θεον ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα [ως]{.greek-omitted} φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντων]{.greek-added} αλληλουια οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και [αγαλλιωμεθα]{.greek-omitted} [αγαλλιωμεν]{.greek-added} και δωμεν [την]{.greek-omitted} δοξαν αυτω οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα περιβαληται βυσσινον λαμπρον και καθαρον το γαρ βυσσινον τα δικαιωματα των αγιων εστιν[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι αληθινοι του θεου εισιν[19:9]{.aside}

και επεσα εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ [μαρ]{.greek-added} [μαρτυρια]{.greek-omitted} [τυρια]{.greek-added} του [ιησου]{.greek-abbr} εστιν το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον καλουμενος πιστος και αληθινος και εν [δικαιοσυνη]{.greek-omitted} [δικαιοσυνει]{.greek-added} κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου [ως]{.greek-added} φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων ονοματα γεγραμμενα και ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον [βεβαμμενον]{.greek-omitted} [ερραντισμενον]{.greek-added} αιματι και [καλειται]{.greek-omitted} [κεκληται]{.greek-added} το ονομα αυτου ο λογος του θεου[19:13]{.aside}

και τα στρατευματα [τα]{.greek-omitted} εν τω ουρανω ηκολουθει αυτω επι ιπποις λευκοις ενδεδυμενοι βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος πατει την ληνον του οινου του θυμου της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον [αυτου]{.greek-added} και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και κυριος κυριων[19:16]{.aside}

και ειδον [ενα]{.greek-added} [αλλον]{.greek-added} αγγελον εστωτα εν τω ηλιω και εκραξεν [εν]{.greek-added} φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} δευτε συναχθητε εις το δειπνον [το]{.greek-omitted} [τον]{.greek-added} [μεγα]{.greek-omitted} [μεγαν]{.greek-added} του [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων και μικρων [τε]{.greek-omitted} και μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον και ο μετ αυτου ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις επλανησεν τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες εβληθησαν οι δυο εις την λιμνην του πυρος την καιομενην εν [τω]{.greek-added} θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων [αυτων]{.greek-omitted} [αυτου]{.greek-added}[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την κλειν της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και ο σατανας ο πλανων την οικουμενην ολην και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και εκλεισεν και εσφραγισεν επανω αυτου ινα μη πλανα ετι τα εθνη αχρι τελεσθη τα χιλια ετη [και]{.greek-omitted} μετα ταυτα δει [λυθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και ειδον θρονους και [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} επ αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν το θηριον ουδε την εικονα αυτου και ουκ ελαβον το χαραγμα επι το μετωπον και επι την χειρα αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} τα χιλια ετη[20:4]{.aside}

[και]{.greek-omitted} οι [δε]{.greek-added} λοιποι των νεκρων ουκ εζησαν αχρι τελεσθη τα χιλια ετη αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν τη αναστασει τη πρωτη επι τουτων ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου χιλια ετη[20:6]{.aside}

και οταν τελεσθη τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη [τα]{.greek-omitted} εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης τον γωγ και τον μαγωγ συναγαγειν αυτους εις τον πολεμον [ων]{.greek-omitted} [ον]{.greek-added} ο αριθμος [αυτων]{.greek-added} ως η αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και εκυκλωσαν την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ εκ του ουρανου απο του θεου και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και θειου οπου και το θηριον και ο ψευδοπροφητης και βασανισθησονται ημερας και [νυκτος]{.greek-omitted} [νυκτας]{.greek-added} εις τους αιωνας των αιωνων[20:10]{.aside}

και ειδον θρονον μεγαν λευκον και τον καθημενον επ αυτον ου απο προσωπου εφυγεν η γη και ο ουρανος και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ει[δον]{.unclear} [τους]{.unclear} [νε]{.unclear}κρους τους μεγαλους και τους μικρους εστωτας ενωπιον του θρονου και βιβλια [ηνεωχθησαν]{.greek-omitted} [ηνοιχθησαν]{.greek-added} και αλλο βιβλιον [ηνεωχθη]{.greek-omitted} [ηνοιχθη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους νεκρους τους εν αυτη και ο θανατος και ο αδης εδωκαν τους νεκρους τους εν αυτοις και εκριθησαν εκαστος κατα τα εργα [αυτων]{.greek-omitted} [αυτου]{.greek-added}[20:13]{.aside}

και ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ει τις ουχ ευρεθη εν τω βιβλιω της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος ουρανος και η πρωτη γη [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την [αγιαν]{.unclear} [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν εκ του ουρανου απο του [θεου]{.greek-abbr} ητοιμασμενην ως νυμφην κεκοσμημενην τω ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του ουρανου λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι λαος αυτου εσονται και αυτος ο [θεος]{.greek-abbr} [εσται]{.greek-omitted} μετ αυτων [ε]{.greek-added} [σται]{.greek-added}[21:3]{.aside}

και εξαλειψει [απ]{.greek-added} [αυτων]{.greek-added} παν δακρυον απο των οφθαλμων αυτων και ο θανατος ουκ εσται ετι [ουτε]{.greek-omitted} [πενθος]{.greek-omitted} [ουτε]{.greek-omitted} [κραυγη]{.greek-omitted} [ουτε]{.greek-omitted} [πονος]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [ετι]{.greek-omitted} οτι τα πρωτα απηλθον[21:4]{.aside}

και ειπεν ο καθημενος [επι]{.greek-omitted} [εν]{.greek-added} τω θρονω ιδου [παντα]{.greek-omitted} καινα ποιω [παντα]{.greek-added} και λεγει [μοι]{.greek-omitted} γραψον [οτι]{.greek-omitted} ουτοι οι λογοι [πιστοι]{.greek-added} [και]{.greek-added} αληθινοι [και]{.greek-omitted} [πιστοι]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εισιν[21:5]{.aside}

και ειπεν μοι γεγονα [εγω]{.greek-added} το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} η αρχη και το τελος εγω τω διψωντι δωσω [αυτω]{.greek-added} εκ της πηγης του υδατος [της]{.greek-omitted} [ζωης]{.greek-omitted} δωρεαν[21:6]{.aside}

ο νικων [κληρονομησει]{.greek-omitted} [δωσω]{.greek-added} [αυτω]{.greek-added} ταυτα και εσομαι αυτω [θεος]{.greek-abbr} και αυτος εσται μοι [υιος]{.greek-abbr}[21:7]{.aside}

τοις δε δειλοις και απιστοις και αμαρτωλοις και εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} [και]{.unclear} πορνοις και φαρμακοις και ειδωλολατραις και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν τη λιμνη τη καιομενη πυρι και θειω ο εστιν ο θανατος ο δευτερος[21:8]{.aside}

και ηλθεν [εις]{.greek-omitted} [εκ]{.greek-omitted} [ο]{.greek-added} [πρωτος]{.greek-added} των επτα αγγελων των εχοντων τας επτα φιαλας [τας]{.greek-added} [γεμουσας]{.greek-omitted} [εχουσας]{.greek-added} των επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την [νυμφην]{.greek-added} [την]{.greek-added} γυναικα [την]{.greek-omitted} [νυμφην]{.greek-omitted} του αρνιου[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εν πνευματι [επ]{.greek-omitted} [επι]{.greek-added} ορος μεγα και υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι την πολιν [την]{.greek-omitted} [μεγαλην]{.greek-omitted} την αγιαν ιερουσαλημ καταβαινουσαν εκ του ουρανου [απο]{.greek-omitted} [εκ]{.greek-added} του θεου[21:10]{.aside}

εχουσαν την δοξαν του θεου [και]{.greek-added} ο φωστηρ αυτης ομοιος λιθω τιμιωτατω ως λιθω ιασπιδι [κρυσταλλιζοντι]{.greek-omitted} [κρυσταλιζοντι]{.greek-added}[21:11]{.aside}

[εχουσα]{.greek-omitted} [εχουσαν]{.greek-added} τειχος μεγα και υψηλον [εχουσα]{.greek-omitted} [εχουσαν]{.greek-added} πυλωνας δωδεκα και επι [τοις]{.greek-omitted} [ταις]{.greek-added} πυλωσιν αγγελους [δωδεκα]{.greek-omitted} [δεκαδυο]{.greek-added} και ονοματα επιγεγραμμενα α [εστιν]{.greek-omitted} [εστι]{.greek-added} [τα]{.greek-added} ονοματα των δωδεκα φυλων [των]{.greek-omitted} υιων [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο ανατολων πυλωνες τρεις και απο [βορρα]{.greek-omitted} [βορραν]{.greek-added} πυλωνες τρεις και απο νοτου πυλωνες τρεις και απο δυσμων πυλωνες τρεις[21:13]{.aside}

και το τειχος της πολεως εχον θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου [ειχεν]{.greek-omitted} [ει]{.greek-added} [χε]{.greek-added} μετρον καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης οσον το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν τω καλαμω επι [σταδιους]{.greek-omitted} [σταδιων]{.greek-added} δωδεκα [χιλιαδων]{.greek-omitted} [χιλιαδας]{.greek-added} [δωδεκα]{.greek-omitted} το μηκος και το [πλατος]{.greek-omitted} [υψος]{.greek-added} και το [υψος]{.greek-omitted} [πλατος]{.greek-added} αυτης ισα εστιν[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} το τειχος αυτης εκατον τεσσαρακοντα τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον ομοιον [υελω]{.greek-omitted} [υαλω]{.greek-added} καθαρω[21:18]{.aside}

[και]{.greek-added} οι θεμελιοι του τειχους της πολεως παντι λιθω τιμιω κεκοσμημενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος [χαλκηδων]{.greek-omitted} [καρχηδων]{.greek-added} ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος σαρδονυξ ο εκτος [σαρδιον]{.greek-omitted} [σαρδειων]{.greek-added} ο εβδομος χρυσολιθος ο ογδοος βηρυλλος ο ενατος τοπαζιον ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος ο δωδεκατος [αμεθυσος]{.greek-omitted} [αμεθυστος]{.greek-added}[21:20]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται [ανα]{.greek-omitted} [ινα]{.greek-added} εις [και]{.greek-added} εκαστος των πυλωνων ην εξ ενος μαργαριτου και η πλατεια της πολεως χρυσιον καθαρον ως υελος διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης εστιν και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν αυτη η γαρ δοξα του θεου εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης [φερουσιν]{.greek-omitted} [φερουσι]{.greek-added} [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν και [τη[ν]{.unclear}]{.greek-added} τιμην των εθνων εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην[21:26]{.aside}

και ου μη εισελθη εις αυτην παν [κοινον]{.greek-omitted} [κοινων]{.greek-added} και [ποιουν]{.greek-omitted} [ο]{.greek-added} [ποιων]{.greek-added} βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον [καθαρον]{.greek-omitted} υδατος ζωης λαμπρον ως [κρυσταλλον]{.greek-omitted} [κρυσταλον]{.greek-added} εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και [εκειθεν]{.greek-omitted} [εντευθεν]{.greek-added} ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα [αποδιδους]{.greek-added} εκαστον [αποδιδους]{.greek-omitted} τον καρπον αυτου και τα [φυλλα]{.greek-omitted} [φυλα]{.greek-added} του ξυλου εις θεραπειαν των εθνων[22:2]{.aside}

και παν καταθεμα ουκ εσται ετι και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι δουλοι αυτου λατρευσουσιν αυτω[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των μετ[ωπων]{.greek-supplied} αυτων[22:4]{.aside}

και νυξ ουκ εσται [εκει]{.greek-omitted} [ετι]{.greek-added} και [ου]{.greek-added} χρειαν ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} [λυχνου]{.greek-omitted} [και]{.greek-omitted} φωτος ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} φωτιει [επ]{.greek-added} αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και λεγει μοι ουτοι οι λογοι [μου]{.greek-added} πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [πνευματων]{.greek-omitted} [[πνω]{.greek-abbr}]{.greek-added} των [αγιων]{.greek-added} προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

και ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

καγω ιωαννης ο ακουων και βλεπων ταυτα και οτε ηκουσα και [εβλεψα]{.greek-omitted} [επεσον]{.greek-omitted} [ειδον]{.greek-added} [επεσα]{.greek-added} προσκυνησαι εμπροσθεν των ποδων του αγγελου του δεικνυοντος μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των προφητων και των τηρουντων τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[[22:9 *(lacunose)*]{.lacunose}]{.aside}

και λεγει μοι [μη]{.unclear} σφραγισης τους λογους της προφητειας του βιβλιου του[του]{.greek-supplied} ο καιρος γαρ εγγυς εστιν[22:10]{.aside}

[και]{.greek-added} ο αδικων αδικησατω [ετι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ρυπαρος]{.greek-omitted} [ρυπαρευθητω]{.greek-omitted} ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον εσται αυτου[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-abbr} ο πρωτος και ο εσχατος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα [εσται]{.greek-omitted} η εξουσια αυτων [εσται]{.greek-added} επι το ξυλον της ζωης και τοις πυλωσιν εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι πορνοι και οι φονεις και οι ειδωλολατραι και πας [ο]{.greek-added} [ποιων]{.greek-added} [και]{.greek-added} [ο]{.greek-added} φιλων [και]{.greek-omitted} [ποιων]{.greek-omitted} ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα επι ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} [και]{.greek-added} ο αστηρ ο λαμπρος ο πρωινος[22:16]{.aside}

και το πνευμα και η νυμφη λεγουσιν ερ[χου]{.unclear} και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι τω ακουοντι τους λ[ογους]{.unclear} της προφητειας του βιβλιου τουτου εαν τις επιθη επ αυτα [επιθησαι]{.greek-omitted} [επιθησεται]{.greek-added} ο [θεος]{.greek-abbr} επ αυτον τας πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και εαν τις αφελη απο των λογων του βιβλιου της προφητειας ταυτης αφελοι ο θεος το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των [γεγραμμενων]{.greek-omitted} [εγγεγραμμενων]{.greek-added} εν τω βιβλιω τουτω[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην ναι ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων [αμην]{.greek-omitted} [αμ]{.greek-added} [ην]{.greek-added}[22:21]{.aside}

