---
title: "Collation of Byz^RP^ vs 32019 (2019)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2019 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32019).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2019                                   	| λογος                              	|
| 2019 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2019 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2019               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2019                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2019 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2019                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [εστι]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [χρη]{.greek-added} [γενεσθαι]{.greek-added} [μετα]{.greek-added} [ταυτα]{.greek-added}[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντ[ες]{.unclear} τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα [οτι]{.greek-added} [ο]{.greek-omitted} [γαρ]{.greek-omitted} καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις [ουσαις]{.greek-added} εν τη ασια χαρις υμιν και [ειρηνει]{.greek-added} [ειρηνη]{.corr} απο [θεου]{.greek-omitted} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α [εισιν]{.greek-added} ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο [πρωτοτοκος]{.greek-omitted} [προτοτοκος]{.greek-added} των νεκρων και [ο]{.greek-omitted} [αρχων]{.greek-omitted} [αρχον]{.greek-added} των βασιλεων της γης τω [αγαπωντι]{.greek-omitted} [αγαπησαν]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [λυσαντι]{.greek-added} [ε[κ]{.unclear}]{.greek-added} [ημας]{.greek-omitted} [απο]{.greek-omitted} των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και [εποιησεν]{.greek-omitted} [ποιησαντι]{.greek-added} ημας βασιλειαν [και]{.greek-added} ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [ἄλφα]{.greek-added} και το [ω]{.greek-omitted} [ὦ]{.greek-added} [η]{.greek-added} [αρχη]{.greek-added} [και]{.greek-added} [το]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συγκοι[ν]{.unclear}ωνος]{.greek-added} εν τη θλιψει και [εν]{.greek-added} [τη]{.greek-added} βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγεν[ο]{.unclear}μην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-omitted}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα [φωνην]{.greek-omitted} οπισω μου [ως]{.greek-added} [φωνην]{.greek-added} μεγαλην ως [φωνην]{.greek-added} σαλπιγγος[1:10]{.aside}

λεγουσης [εγω]{.greek-added} [ειμι]{.greek-added} [το]{.greek-added} [αλφα]{.greek-added} [και]{.greek-added} [το]{.greek-added} [ω]{.greek-added} [ο]{.greek-added} [πρωτος]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [εσχατος]{.greek-added} [και]{.greek-added} ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις [σμυρναν]{.greek-omitted} [μυρναν]{.greek-added} και εις περγαμον και [εις]{.greek-omitted} [θυατειρα]{.greek-omitted} [εν]{.greek-added} [θυατηροις]{.greek-added} και εις σαρδεις και εις [φιλαδελφειαν]{.greek-omitted} [φιλαδελφιαν]{.greek-added} και εις [λαοδικειαν]{.greek-omitted} [λαοδικιαν]{.greek-added}[1:11]{.aside}

και [εκει]{.greek-omitted} επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας [ειδον]{.greek-omitted} [ιδον]{.greek-added} επτα λυχνιας χρυσας[1:12]{.aside}

και ε[ν]{.greek-supplied} μεσω των επτα λυχνιων ομοιον υιω [ανθρωπου]{.greek-abbr} εν[δεδυ]{.unclear}μενον [ποδηρη]{.greek-omitted} [ποδηρι]{.greek-added} και περιεζωσμενον προς τοις μαστ[οις]{.unclear} [ζωνην]{.greek-omitted} [ζωνη]{.greek-added} χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι [ως]{.greek-omitted} [ωσει]{.greek-added} εριον λευκον [ως]{.greek-omitted} [ωσει]{.greek-added} χιων και οι οφθαλμοι αυτου ως φλοξ πυρ[ος]{.unclear}[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν τη δεξια [χειρι]{.greek-added} αυτου [χειρι]{.greek-omitted} αστερας επτα και εκ του στοματος αυτου ρομφαια [διστομος]{.greek-omitted} [δυστομος]{.greek-added} οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος [φαινει]{.greek-omitted} [φαινη]{.greek-added} εν τη δυναμει αυτου[1:16]{.aside}

και οτε [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον επεσα [προς]{.greek-omitted} [εις]{.greek-added} τους ποδας αυτου [ως]{.greek-omitted} [ωσει]{.greek-added} νεκρος και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} την δεξιαν αυτου [χειρα]{.greek-added} επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων [αμην]{.greek-omitted} και εχω τας κλεις του [θανατου]{.greek-omitted} [αδου]{.greek-added} και του [αδου]{.greek-omitted} [θανατου]{.greek-added}[1:18]{.aside}

γραψον ουν α [ειδες]{.greek-omitted} [ιδες]{.greek-added} και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων [ειδες]{.greek-omitted} [ιδες]{.greek-added} επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων [εισιν]{.greek-omitted} [εισι]{.greek-added} και αι [επτα]{.greek-added} λυχνιαι αι [επτα]{.greek-omitted} [χρυσαι]{.greek-added} επτα εκκλησιαι [εισιν]{.greek-omitted} [εισι]{.greek-added}[1:20]{.aside}

### Chapter 2

τω αγγελω [τω]{.greek-added} της [εν]{.greek-omitted} εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον [σου]{.greek-omitted} και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ εισιν και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις και εβαστασας δια το ονομα μου και [ουκ]{.greek-omitted} [οὐ]{.greek-added} [κεππίασας]{.greek-added} [εκοπιασας]{.greek-omitted} [[κεκπίασας]{.corr}]{.greek-added}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν [πεπτωκας]{.greek-omitted} [εκπεπτωκας]{.greek-added} και μετανοησον και [τα]{.greek-added} [πρωτα]{.greek-added} [εργα]{.greek-added} [ποιησον]{.greek-added} τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχ[εις]{.unclear} οτι μισεις τα εργα των [αισχρον]{.greek-added} [εγω]{.greek-added} [η]{.greek-added} νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω [νικωντι]{.greek-omitted} [νικοντι]{.greek-added} [δωσω]{.greek-omitted} [δοσω]{.greek-added} αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν [τω]{.greek-omitted} [μεσω]{.greek-added} [του]{.greek-added} [παραδεισω]{.greek-omitted} [παραδεισου]{.greek-added} του [θεου]{.greek-abbr} [μου]{.greek-omitted}[2:7]{.aside}

και τω αγγελω της εν [σμυρνη]{.greek-omitted} [σμυρνει]{.greek-added} εκκλησιας γραψον ταδε λεγει ο πρωτος και ο [εσχατος]{.greek-omitted} [αισχατος]{.greek-added} ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την [πτωχειαν]{.greek-omitted} [πτωχιαν]{.greek-added} αλλα πλουσιος [ει]{.unclear} και την βλασφημιαν [εκ]{.greek-omitted} των λεγοντων ιουδαιους [εαυτους]{.greek-added} ειναι [εαυτους]{.greek-omitted} και ουκ ε[ι]{.unclear}σιν αλλα συναγωγη του σατανα[2:9]{.aside}

[μηδεν]{.greek-omitted} [μιδεν]{.greek-added} φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βάλλειν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και [εξετε]{.greek-omitted} [εχηται]{.greek-added} θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και [δωσω]{.greek-omitted} [δοσω]{.greek-added} σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστο[μ]{.unclear}ον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις εν αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς [μου]{.greek-omitted} ο πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την [δι]{.greek-added} [διδαχην]{.greek-omitted} [δαχην]{.greek-added} [του]{.greek-added} βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδασκεν]{.greek-added} τον [βαλακ]{.greek-omitted} [βαλαακ]{.greek-added} βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} φαγειν [ειδωλοθυτα]{.greek-omitted} [ειδολοθυτα]{.greek-added} και πορνευσαι[2:14]{.aside}

ουτως εχεις και [συ]{.greek-omitted} κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον [ουν]{.greek-omitted} ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω [νικωντι]{.greek-omitted} [νικοντι]{.greek-added} [δωσω]{.greek-omitted} [δοσω]{.greek-added} αυτω [φαγειν]{.greek-added} [εκ]{.greek-added} του μαννα του κεκρυμμενου και [δωσω]{.greek-omitted} [δοσω]{.greek-added} αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατηροις]{.greek-added} εκκλησιας γραψον ταδε λεγει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο εχων τους οφθαλμους [αυτου]{.greek-omitted} ως [φλογα]{.greek-omitted} [φλοξ]{.greek-added} πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και [την]{.greek-omitted} υπομονην σου [και]{.corr} τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου [πολυ]{.greek-added} οτι [αφεις]{.greek-omitted} [αφηκας]{.greek-added} την γυναικα [σου]{.greek-omitted} ιεζαβελ [η]{.greek-omitted} [λεγει]{.greek-omitted} [την]{.greek-added} [λεγουσαν]{.greek-added} εαυτην [προφητιν]{.greek-omitted} [προφητην]{.greek-added} [ειναι]{.greek-added} και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν [ειδολοθυτα]{.greek-added} [ειδωλοθυτα]{.corr}[2:20]{.aside}

και εδωκα αυτη χρονον ινα [μετανοηση]{.greek-omitted} [μετανοησει]{.greek-added} και ου θελει [[θελη]{.corr}]{.greek-added} μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων [αυτης]{.greek-omitted} [αυτων]{.greek-added}[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν [θανατω]{.greek-omitted} [θυμω]{.greek-added} και γν[ω]{.unclear}σονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και [δωσω]{.greek-omitted} [δοσω]{.greek-added} υμιν εκαστω κατα τα εργα [υμων]{.greek-omitted} [ημων]{.greek-added}[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν [θυατειροις]{.greek-omitted} [θυατηροις]{.greek-added} οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ [εγνωσαν]{.greek-omitted} [εγνωται]{.greek-added} τα [βαθεα]{.greek-omitted} [βάθη]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε [κρατησατε]{.greek-omitted} [κρατειτε]{.greek-added} [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικ[ων]{.unclear} και ο τηρων αχρι τελους τα εργα μου [δωσω]{.greek-omitted} [δοσω]{.greek-added} αυ[τω]{.unclear} εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα [και]{.greek-added} [συντριψει]{.greek-added} [αυτους]{.greek-added} ως τα [σκευη]{.greek-omitted} [σκευει]{.greek-added} τα κεραμικα [συντριβησεται]{.greek-omitted} [συντριβεται]{.greek-added} [συντριβονται]{.greek-added} [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και [δωσω]{.greek-omitted} [δοσω]{.greek-added} αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και [τω]{.greek-omitted} [το]{.greek-added} αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [τηρησον]{.greek-added} τα λοιπα α [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [εμελλον]{.greek-added} [αποθνεισκειν]{.greek-added} [[αποθνησκειν]{.corr}]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} [μου]{.greek-omitted}[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και [τηρει]{.greek-omitted} [τηρη]{.greek-added} και μετανοησον εαν [ουν]{.greek-omitted} [δε]{.greek-added} μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη γνως ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ [εχεις]{.greek-added} ολιγα [εχεις]{.greek-omitted} ονοματα εν σαρδεσιν [α]{.greek-omitted} [οι]{.greek-added} ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπαπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοι[ς]{.unclear} και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την [κλειν]{.greek-omitted} [κλειδα]{.greek-added} του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις [κλιει]{.greek-added} [και]{.greek-added} [κλειων]{.greek-added} [κλεισει]{.greek-omitted} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} και ουδεις [ανοιξει]{.greek-omitted} [ανοιγει]{.greek-added}[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν [δυναμιν]{.greek-added} εχεις [δυναμιν]{.greek-omitted} και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου [διδωμι]{.greek-omitted} [διδομι]{.greek-added} εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται [ιδου]{.greek-omitted} [και]{.greek-added} ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξουσιν]{.greek-added} και [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσιν]{.greek-added} ενωπιον των ποδων σου και [γνωσιν]{.greek-omitted} [γνωσονται]{.greek-added} οτι [εγω]{.greek-added} ηγαπησα σε[3:9]{.aside}

[οτι]{.greek-omitted} [οτε]{.greek-added} ετηρησας τον λογον της υπομονης μου καγω σε [τηρησω]{.greek-supplied} εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

[ιδου]{.greek-added} ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη [τον]{.greek-omitted} [τους]{.greek-added} [στεφανον]{.greek-omitted} [στεφανους]{.greek-added} σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} [μου]{.greek-omitted} και εξω ου μη [εξελθη]{.greek-omitted} [εξελθοι]{.greek-added} [ετι]{.greek-omitted} [ετη]{.greek-added} και γραψω επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πο[λεως]{.unclear} του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η καταβαινει εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το [ονομα]{.unclear} [μου]{.unclear} [το]{.unclear} [καινον]{.unclear}[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν [λαοδικεια]{.greek-omitted} [λαοδικαια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε [ψυχρος]{.greek-omitted} [ψυχρο]{.greek-added} ει ουτε ζεστος οφελον [ψυχρος]{.greek-omitted} [ψυχρο]{.greek-added} ης η ζεστος[3:15]{.aside}

[ουτως]{.greek-omitted} οτι χλιαρος ει και [ου]{.greek-omitted} [ουτε]{.greek-added} ζεστος ουτε [ψυχρος]{.greek-omitted} [ψυχρο]{.greek-added} μελλω σε [εμεσαι]{.greek-omitted} [αιμεσαι]{.greek-added} εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και [πεπλουτηκα]{.greek-omitted} [πεπλουτικα]{.greek-added} και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει [ταλεπορος]{.greek-added} [ο]{.greek-omitted} [ταλαιπωρος]{.greek-omitted} και [ο]{.greek-omitted} ελεεινος και πτωχος και [τυφλος]{.greek-omitted} [και]{.greek-omitted} γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι [χρυσιον]{.greek-omitted} παρ εμου [χρυσιον]{.greek-added} πεπυρωμενον εκ πυρος ινα [πλουτησης]{.greek-omitted} [πλουτισης]{.greek-added} και ιματια λευκα ινα περιβαλη και μη φανερωθη η [αισχυνη]{.greek-omitted} [ασχημοσυνη]{.greek-added} της γυμνοτητος σου [κ]{.unclear}αι [κολλυριον]{.greek-omitted} [κολλουριον]{.greek-added} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [εγχρισαι]{.greek-added} τους οφθαλμους σου [ινα]{.greek-omitted} [βλεπης]{.greek-omitted}[3:18]{.aside}

εγω [οσους]{.greek-omitted} [ους]{.greek-added} [εαν]{.greek-omitted} [αν]{.greek-added} φιλω ελεγχω και παιδευω ζηλωσον ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι [την]{.greek-omitted} [τη]{.greek-added} [θυραν]{.greek-omitted} [θυρα]{.greek-added} και κρουω εαν τις ακουση της φωνης μου και [ανοιξη]{.greek-omitted} [ανοιξει]{.greek-added} την θυραν [και]{.greek-omitted} εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων [δωσω]{.greek-omitted} [δοσω]{.greek-added} αυτω καθισαι μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως [φωνη]{.greek-added} σαλπιγγος λαλουσης μετ εμου [λεγων]{.greek-omitted} [και]{.greek-added} [λεγουσαν]{.greek-added} [μοι]{.greek-added} αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι [τον]{.greek-omitted} [του]{.greek-added} [θρονον]{.greek-omitted} [θρονου]{.greek-added} καθημενος[4:2]{.aside}

[και]{.greek-added} [ο]{.greek-added} [καθημενος]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [καθημενος]{.greek-added} ομοιος ορασει λιθω ιασπιδι και [σαρδιω]{.greek-omitted} [σαρδινω]{.greek-added} και [ιρις]{.greek-omitted} [ἴρις]{.greek-added} [κυκλω]{.greek-added} [κυκλοθεν]{.greek-omitted} [του]{.greek-omitted} θρονου [ομοιως]{.greek-omitted} [ομοιος]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδινω]{.greek-added}[4:3]{.aside}

και [κυκλοθεν]{.greek-omitted} [κυκλω]{.greek-added} του θρονου θρονοι εικοσι [τεσσαρες]{.greek-omitted} [τεσσαρις]{.greek-added} και επι τους θρονους [[κδ]{.greek-abbr}]{.greek-added} [τους]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρας]{.greek-omitted} πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φων[αι]{.unclear} και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου [α]{.greek-added} [αυτου]{.greek-omitted} [αι]{.greek-omitted} [εισιν]{.greek-omitted} [εισι]{.greek-added} [τα]{.greek-added} επτα [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα [οφθαλμων]{.greek-omitted} [οφθαλμους]{.greek-added} εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το [δευτερον]{.greek-omitted} [δευτε]{.greek-added} ζωον ομοιον [μοσχω]{.greek-omitted} [μοσχου]{.greek-added} και το τριτον ζωον [εχον]{.greek-omitted} [εχων]{.greek-added} [το]{.greek-added} προσωπον [ως]{.greek-added} [ανθρωπου]{.greek-abbr} και [το]{.greek-omitted} τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} [εχον]{.greek-omitted} [εχων]{.greek-added} ανα πτερυγας εξ [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} [σαβαωθ]{.greek-added} ο [θεος]{.greek-omitted} [παντοκρατορ]{.greek-added} ο [παντοκρατωρ]{.greek-omitted} [ων]{.greek-added} [και]{.greek-added} ο ην και ο [ων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσουσιν]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω [ζωντι]{.greek-omitted} [ζοντι]{.greek-added} εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τω [ζωντι]{.greek-omitted} [ζοντι]{.greek-added} εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βάλλουσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει [[κυριε]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [και]{.greek-omitted} ο [θεος]{.greek-abbr} ημων [ο]{.greek-omitted} [αγιος]{.greek-omitted} λαβειν την δοξαν και [τι]{.greek-added} [την]{.corr} τιμην και την δυναμιν οτι συ εκτισας [τα]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [και]{.greek-omitted} εκτισθησαν[4:11]{.aside}

### Chapter 5

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αγγελον ισχυρον κηρυσσοντα [εν]{.greek-omitted} φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος [εστιν]{.greek-omitted} ανοιξαι το βιβλιον και λυσαι τας [επτα]{.greek-added} σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο [ουτε]{.greek-added} εν τω [ουρανω]{.greek-abbr} [ανω]{.greek-omitted} ουτε [επι]{.greek-omitted} [εν]{.greek-added} [της]{.greek-omitted} [τη]{.greek-added} [γης]{.greek-omitted} [γη]{.greek-added} ουτε υποκατω της γης [του]{.greek-added} ανοιξαι το βιβλιον ουτε [βλεπειν]{.greek-omitted} [βλε[πων]{.unclear}]{.greek-added} αυτο[5:3]{.aside}

και [εγω]{.greek-omitted} [εκλαιον]{.greek-omitted} [εκλεον]{.greek-added} πολυ οτι ουδεις αξιος [ευρεθη]{.greek-omitted} [ηυρεθη]{.greek-added} ανοιξα[ι]{.unclear} [και]{.greek-added} [αναγνωναι]{.greek-added} το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη [κλαιε]{.greek-omitted} [κλεε]{.greek-added} ιδου [γης]{.greek-added} ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον [εστηκος]{.greek-omitted} [εστηκως]{.greek-added} ως εσφαγμενον [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα επτα και οφθαλμους επτα α [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} του [θεου]{.greek-abbr} [τα]{.greek-added} [αποστελλομενα]{.greek-omitted} [απεστελλομενα]{.greek-added} εις πασαν την γην[5:6]{.aside}

και ηλθεν και ειληφεν [το]{.greek-added} [βιβλιον]{.greek-added} εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε ελαβεν το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι [επεσον]{.greek-omitted} ενωπιον του αρνιου [εχοντες]{.greek-omitted} [[εχοντι]{.corr}]{.greek-added} εκαστος [κιθαραν]{.greek-omitted} [κιθαρας]{.greek-added} και φιαλας χρυσας γεμουσας [θυμιαματων]{.greek-omitted} [θυμιαματα]{.greek-added} [α]{.greek-added} [εισιν]{.greek-added} αι [εισιν]{.greek-omitted} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης [[και]{.unclear}]{.corr} [[ηγορασας]{.unclear}]{.corr} [και]{.greek-added} [ημας]{.greek-added} τω [θεω]{.greek-abbr} [ημας]{.greek-omitted} εν τω αιματι σου εκ πασης φυλης και [γλωσσης]{.greek-omitted} [και]{.greek-omitted} λαου και εθνους [και]{.greek-added} [γλωσσης]{.greek-added}[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ηκουσα ως φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και [χιλιαδες]{.greek-omitted} [χιλιαδα]{.greek-added} [χιλιαδων]{.greek-omitted} [χιλιαδα]{.greek-added}[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον εστιν το αρνιον το εσφαγμενον λαβειν [την]{.greek-omitted} δυναμιν και [τον]{.greek-omitted} πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν τω [ουρανω]{.greek-abbr} και επι της γης και υπο[κ]{.unclear}ατω της γης και επι της [θ]{.unclear}αλασσης [α]{.greek-added} εστιν [και]{.greek-omitted} [τα]{.greek-omitted} εν αυτοις [παντας]{.greek-omitted} [παντα]{.greek-added} [και]{.greek-added} ηκουσα λεγοντας τω καθημενω επι του θρονου και τω αρνιω η ευλογια και η [τιμη]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} [το]{.greek-omitted} αμην και οι πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [οτι]{.greek-omitted} [οτε]{.greek-added} ηνοιξεν το αρνιον μιαν εκ των επτα σφραγιδων [και]{.greek-omitted} ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνὴν]{.greek-added} βροντης [λεγουσας]{.greek-added} ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ιδον]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και εξηλθεν νικων και ινα [νικηση]{.greek-omitted} [νικησει]{.greek-added} [και]{.greek-added} [ενικησεν]{.greek-added}[6:2]{.aside}

και οτε ηνοιξεν την δευτεραν σφραγιδα ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος [πυρος]{.greek-omitted} [πυρρος]{.greek-added} και τω καθημενω επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} εδοθη αυτω λαβειν [απο]{.greek-added} [την]{.greek-omitted} [ειρηνην]{.greek-omitted} [εκ]{.greek-omitted} της γης [και]{.greek-added} ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξουσιν]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε ηνοιξεν την [[γ]{.greek-abbr}]{.greek-added} σφραγιδα [την]{.greek-omitted} [τριτην]{.greek-omitted} ηκουσα του [τριτου]{.greek-omitted} [[γ]{.greek-abbr}]{.greek-added} ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [ιδον]{.greek-added} και ιδου ιππος μελας και ο καθημενος επ αυτον [εχων]{.greek-omitted} [εχον]{.greek-added} ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα [ως]{.greek-added} φωνην εν μεσω των τεσσαρων ζωων [λεγουσαν]{.greek-omitted} [λεγοντων]{.greek-added} [χοινιξ]{.greek-omitted} [χοινοιξ]{.greek-added} σιτου δηναριου και τρεις [χοινικες]{.greek-omitted} [χοινοικες]{.greek-added} [κριθης]{.greek-omitted} [κριδης]{.greek-added} δηναριου [και]{.greek-omitted} [το]{.greek-omitted} [ελαιον]{.greek-omitted} και τον οινον [και]{.greek-added} [τον]{.greek-added} [ελαιον]{.greek-added} μη αδικησης[6:6]{.aside}

και οτε ηνοιξεν την σφραγιδα την τεταρτην ηκουσα [φωνην]{.greek-added} του [τεταρτου]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ιδον]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και εδοθη αυτω εξουσια επι το τεταρτον [μερος]{.greek-added} της γης [αποκτειναι]{.greek-omitted} [αποκτηναι]{.greek-added} εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε ηνοιξεν την [πεμπτην]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} σφραγιδα [ειδον]{.greek-omitted} [ιδον]{.greek-added} υποκατω του θυσιαστηριου τας ψυχας [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} ην ειχον[6:9]{.aside}

και [εκραξαν]{.greek-omitted} [εκραξον]{.greek-added} φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων [εκ]{.greek-omitted} [απο]{.greek-added} των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} ετι [μικρον]{.greek-added} χρονον εως [ου]{.greek-added} [πληρωσωσιν]{.greek-omitted} [πληρωσουσι]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [συνδουλοι]{.greek-omitted} [αυτων]{.greek-omitted} και οι αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [και]{.greek-added} οτε ηνοιξεν την σφραγιδα την εκτην [και]{.greek-omitted} σεισμος μεγας εγενετο και ο ηλιος [εγενετο]{.greek-added} μελας [εγενετο]{.greek-omitted} ως σακκος [τριχινος]{.greek-omitted} [τριχυνος]{.greek-added} και η σεληνη [ολη]{.greek-omitted} εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} [επεσον]{.greek-omitted} [επεσαν]{.greek-added} εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλει]{.greek-added} τους ολυνθους αυτης υπο [μεγαλου]{.greek-added} ανεμου [μεγαλου]{.greek-omitted} σειομενη[6:13]{.aside}

και [ο]{.greek-omitted} [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ειλισσομενον]{.greek-added} και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι [χιλιαρχοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} πλουσιοι και οι [ισχυροι]{.greek-omitted} [χιλιαρχοι]{.greek-added} και πας δουλος και [πας]{.greek-added} ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεοις]{.greek-added} και ταις πετραις [πεσετε]{.greek-omitted} [πεσεται]{.greek-added} εφ ημας και [κρυψατε]{.greek-omitted} [κρυψαται]{.greek-added} ημας απο [προσωπου]{.greek-omitted} [πρωσωπου]{.greek-added} του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} η ημερα η μεγαλη της οργης αυτου και τις δυναται [σταθηναι]{.greek-omitted} [στηναι]{.greek-added}[6:17]{.aside}

### Chapter 7

και μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} [ειδον]{.greek-omitted} [ιδον]{.greek-added} [τεσσαρας]{.greek-omitted} [τεσσαρες]{.greek-added} αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους [τεσσαρας]{.greek-omitted} [[δ]{.greek-abbr}]{.greek-added} ανεμους της γης ινα μη [πνεη]{.greek-omitted} [πνεει]{.greek-added} ανεμος επι της γης μητε επι της θαλασσης μητε επι [τι]{.greek-omitted} [παν]{.greek-added} δενδρον[7:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλον αγγελον αναβαινοντα απο [ανατολης]{.greek-omitted} [του]{.greek-added} ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και εκραξεν [εν]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη [αδικησητε]{.greek-omitted} [αδικησηται]{.greek-added} την γην μητε την θαλασσαν μητε τα δενδρα αχρι ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} [ημων]{.greek-omitted} επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [και]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες [εσφραγισμενων]{.greek-omitted} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr} [εσφραγισμενοι]{.greek-added}[7:4]{.aside}

εκ φυλ[ης]{.unclear} ιουδα [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης [ρουβιμ]{.greek-omitted} [δωδεκα]{.greek-omitted} [ρουβην]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} [χιλιαδες]{.greek-omitted} [χιλιαδας]{.greek-added} [εσφραγισμενοι]{.greek-added} [[γ]{.greek-abbr}]{.greek-added} εκ φυλης γαδ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:5]{.aside}

[[δ]{.greek-abbr}]{.greek-added} εκ φυλης ασηρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [[ε]{.greek-abbr}]{.greek-added} εκ φυλης νεφθαλειμ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [[ϛ]{.greek-abbr}]{.greek-added} εκ φυλης μανασση [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:6]{.aside}

[[ζ]{.greek-abbr}]{.greek-added} εκ φυλης συμεων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [[η]{.greek-abbr}]{.greek-added} εκ φυλης λευι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [[θ]{.greek-abbr}]{.greek-added} εκ φυλης [ισαχαρ]{.greek-omitted} [ισσαχαρ]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

[[ι]{.greek-abbr}]{.greek-added} εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [[ια]{.greek-abbr}]{.greek-added} εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [[ιβ]{.greek-abbr}]{.greek-added} εκ φυλης βενιαμιν [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted}[7:8]{.aside}

μετα ταυτα [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου οχλος πολυς ον αριθμησαι [αυτον]{.greek-added} ουδεις εδυνατο εκ παντος εθνους και [λαων]{.greek-added} [και]{.greek-added} φυλων και [λαων]{.greek-omitted} [και]{.greek-omitted} γλωσσων [εστωτας]{.greek-omitted} [εστωτες]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου [περιβεβλημενους]{.greek-omitted} [περιβεβλημενοι]{.greek-added} στολας λευκας και [φοινικας]{.greek-omitted} [φοινοικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η σωτηρια τω [θεω]{.greek-abbr} ημων τω καθημενω επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} [και]{.corr} τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι [ειστηκεισαν]{.greek-omitted} [ιστηκησαν]{.greek-added} κυκλω του θρονου [και]{.greek-omitted} των πρεσβυτερων και των τεσσαρων ζωων και [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του θρονου [και]{.greek-added} [ενωπιον]{.greek-added} [του]{.greek-added} [αρνιου]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η [ευχαριστια]{.greek-omitted} [ευχαριστεια]{.greek-added} και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων [αμην]{.greek-omitted}[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και [ειπον]{.greek-omitted} [ειρηκ[α]{.greek-supplied}]{.greek-added} [αυτω]{.greek-supplied} [κυριε]{.greek-abbr} μου συ οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι εκ της [θλιψεως]{.greek-omitted} [θληψεως]{.greek-added} της μεγαλης και [επλυναν]{.greek-omitted} [επληναν]{.greek-added} τας στολας αυτων και ελευκαναν [αυτας]{.greek-added} εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ [αυτους]{.greek-omitted} [αυτοις]{.greek-added}[7:15]{.aside}

ου πεινασουσιν [ετι]{.greek-omitted} ουδε διψησουσιν [ετι]{.greek-omitted} [ουδ]{.greek-omitted} [ουδε]{.greek-added} [ου]{.greek-omitted} μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [πειμανει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγησει]{.greek-added} αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον [εκ]{.greek-omitted} [απο]{.greek-added} των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε ηνοιξεν την σφραγιδα την εβδομην εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος ηλθεν και εσταθη επι [του]{.greek-omitted} [το]{.greek-added} [θυσιαστηριου]{.greek-omitted} [θυσιαστηριον]{.greek-added} εχων λιβανωτον χρυσουν και εδοθη [αυτω]{.greek-omitted} [αυτο]{.greek-added} θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δω]{.greek-added} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [προσευχαις]{.greek-omitted} [προσευχας]{.greek-added} των αγιων [παντων]{.greek-omitted} επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και [εγεμισεν]{.greek-omitted} [εγεμησεν]{.greek-added} αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην κ[αι]{.unclear} εγενοντο [φωναι]{.greek-added} [και]{.greek-added} βρονται [και]{.greek-omitted} [φωναι]{.greek-omitted} και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος [αγγελος]{.greek-added} εσαλπισεν και εγενετο χαλαζα και πυρ [μεμιγμενα]{.greek-omitted} [μεμιγμενον]{.greek-added} [εν]{.greek-omitted} αιματι και εβληθη εις την γην και το τριτον της γης [κατεκαη]{.greek-omitted} [κατεκαει]{.greek-added} και το τριτον των δενδρων [κατεκαη]{.greek-omitted} [κατεκαει]{.greek-added} και πας χορτος [χλωρος]{.greek-omitted} [χλορος]{.greek-added} [κατεκαη]{.greek-omitted} [κατεκαει]{.greek-added}[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα [πυρι]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον [μερος]{.greek-added} των κτισματων [των]{.greek-added} εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον [μερος]{.greek-added} των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος [λεγεται]{.greek-omitted} [ελεγετο]{.greek-added} ο αψινθος και [εγενετο]{.greek-omitted} [γινεται]{.greek-added} το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος εσαλπισεν και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [μη]{.greek-added} [φαινει]{.greek-added} [το]{.greek-added} [φως]{.greek-added} [αυτης]{.greek-added} [και]{.greek-added} [η]{.greek-added} [νρ]{.greek-added} [[νυξ]{.corr}]{.greek-added} [ομοιως]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [νυξ]{.greek-omitted} [ομοιως]{.greek-omitted}[8:12]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ηκουσα ενος αετου πετομενου εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} [λεγοντος]{.greek-omitted} [λεγον]{.greek-added} φωνη [μεγαλη]{.greek-omitted} [τρις]{.greek-added} ουαι ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος εσαλπισεν και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αστερα εκ του [ουου]{.greek-added} [[ουρανου]{.greek-abbr}]{.corr} [πεπτωκοτα]{.greek-omitted} [πεπτοκοτα]{.greek-added} εις την γην και εδοθη [αυτω]{.greek-omitted} [αυτο]{.greek-added} η [κλεις]{.greek-omitted} [κλις]{.greek-added} του φρεατος της αβυσσου[9:1]{.aside}

και ηνοιξεν το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος ως καπνος καμινου [μεγαλης]{.greek-added} καιομενης και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον [λεοντι]{.greek-added} [λοκουσι]{.greek-added} ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι [κορπιοι]{.greek-added} [σκορπιοι]{.corr} της γης[9:3]{.aside}

και ερρεθη αυταις ινα [ινα]{.greek-added} μη [αδικησωσιν]{.greek-omitted} [δικησουσι]{.greek-added} τον χορτον της γης ουδε παν [χλωρον]{.greek-omitted} [χλορον]{.greek-added} ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ εχουσιν την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και εδοθη αυταις ινα μη [αποκτεινωσιν]{.greek-omitted} [αποκτεινουσιν]{.greek-added} αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθησονται]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν παιση [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη ευρησουσιν αυτον και [επιθυμησουσιν]{.greek-omitted} [επιθυμισουσιν]{.greek-added} αποθανειν και [φευξεται]{.greek-omitted} [φευγει]{.greek-added} [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως [στ]{.greek-added} [στεφανοι]{.greek-omitted} [[εφανοι]{.greek-supplied}]{.greek-added} [χρυσοι]{.greek-omitted} [[ο]{.greek-supplied}μοιοι]{.greek-added} [χρυσω]{.greek-added} και τα προσωπα αυτων ως προ[σω]{.greek-supplied}πα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας [σιδηρους]{.greek-omitted} [σηδηρους]{.greek-added} και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[εχουσαι]{.greek-omitted} [εχουσιν]{.greek-added} [βασιλεα]{.greek-omitted} επ αυτων [βασιλεις]{.greek-added} [τον]{.greek-added} αγγελον της αβυσσου ονομα αυτω εβραιστι αββαδων [και]{.greek-added} εν [δε]{.greek-omitted} τη ελληνικη [εχει]{.greek-added} ονομα [εχει]{.greek-omitted} απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} [ετι]{.greek-omitted} [αι]{.greek-added} δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγουσασαν]{.greek-added} τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους [τεσσαρας]{.greek-omitted} [τεσσαρεις]{.greek-added} αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και [εις]{.greek-omitted} [την]{.greek-omitted} ημεραν και μηνα και [ενιαυτων]{.greek-added} [ενιαυτον]{.corr} ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [ιππου]{.greek-omitted} [ιππικου]{.greek-added} [μυριαδες]{.greek-omitted} [δισμυριαδες]{.greek-added} μυριαδων ηκουσα [των]{.greek-added} [τον]{.corr} αριθμον αυτων[9:16]{.aside}

και ουτως [ειδον]{.greek-omitted} [ιδον]{.greek-added} τους [ιππους]{.greek-omitted} [καθους]{.greek-added} εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας [πυρινους]{.greek-omitted} [π[ε]{.unclear}ρινους]{.greek-added} και υακινθιν[ους]{.unclear} και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων [ησαν]{.greek-added} και εκ [των]{.greek-omitted} [του]{.greek-added} [στοματων]{.greek-omitted} [στοματος]{.greek-added} αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του πυρος και του καπνου και του θειου του εκπορευομενου εκ [των]{.greek-omitted} [του]{.greek-added} [στοματων]{.greek-omitted} [στοματος]{.greek-added} αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων εστιν [και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ουραις]{.greek-omitted} [αυτων]{.greek-omitted} αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσαις]{.greek-added} κεφαλας και εν αυταις αδικουσιν[9:19]{.aside}

και [οι]{.corr} λοιποι των [ανθρωπων]{.greek-abbr} [οι]{.greek-supplied} [ουκ]{.greek-supplied} [α]{.greek-supplied}πεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τα [δαιμονια]{.greek-omitted} [δαιμωνια]{.greek-added} και τα ειδωλα τα χρυσα και [τα]{.greek-omitted} αργυρα και [τα]{.greek-omitted} χαλκα και τα λιθινα και [τα]{.greek-omitted} ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των [φονων]{.greek-omitted} [φωνων]{.greek-added} αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και [η]{.greek-omitted} ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν τη χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλιδαριον]{.greek-added} ανεωγμενον και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε [ευωνυμον]{.greek-omitted} [ευονυμον]{.greek-added} επι της γης[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων [μυκαται]{.greek-omitted} [μυκατε]{.greek-added} και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και [μη]{.greek-omitted} [μετα]{.greek-added} [αυτα]{.greek-omitted} [ταυτα]{.greek-added} [γραψης]{.greek-omitted} [γραφεις]{.greek-added}[10:4]{.aside}

και ο αγγελος ον [ειδον]{.greek-omitted} [ιδον]{.greek-added} εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου [την]{.greek-omitted} [δεξιαν]{.greek-omitted} εις τον ουρανον[10:5]{.aside}

και ωμοσεν [εν]{.greek-added} τω ζωντι εις τους αιωνας των αιω[ν]{.unclear}ων [αμην]{.greek-added} ος [εκτισεν]{.greek-omitted} [εκτησε]{.greek-added} τον ουρανον και τα εν αυτω [και]{.greek-omitted} την γην και τα εν [αυτω]{.greek-added} [αυτη]{.corr} [και]{.greek-omitted} την θαλασσαν και τα [εν]{.unclear} αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν [μελλη]{.greek-omitted} [μελλει]{.greek-added} σαλπιζειν και [ετελεσθη]{.greek-omitted} [τελεσθη]{.greek-added} το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελησε]{.greek-added} τους [αυτου]{.greek-added} δουλους [αυτου]{.greek-omitted} τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν [λαλουσα]{.greek-omitted} [λαλουσαν]{.greek-added} μετ εμου και [λεγουσα]{.greek-omitted} [λεγουσαν]{.greek-added} [μοι]{.greek-added} υπαγε λαβε το βιβλιδαριον το [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} [εκ]{.greek-added} [χειρος]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω [δουναι]{.greek-omitted} [δος]{.greek-added} μοι το βιβλιδαριον και λεγει μοι λαβε και καταφαγε αυτο και [πικρανει]{.greek-omitted} [πικρανι]{.greek-added} σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βιβλιδαριον]{.greek-added} εκ [της]{.greek-omitted} χειρος του αγγελου και [κατεφαγον]{.greek-omitted} [αυτο]{.greek-omitted} [κατέφαγα]{.greek-added} [αυτων]{.greek-added} και ην εν τω στοματι μου [γλυκι]{.greek-added} ως μελι [γλυκυ]{.greek-omitted} και οτε [εφαγον]{.greek-omitted} [εφαγα]{.greek-added} αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} μοι δει [σε]{.greek-omitted} [σαι]{.greek-added} παλιν προφητευσαι επι λαοις και [επι]{.greek-omitted} [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και [μετρησον]{.greek-omitted} [μετρισον]{.greek-added} τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην [μετρησης]{.greek-omitted} [μετρισης]{.greek-added} οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας [[μβ]{.greek-abbr}]{.greek-added} [τεσσαρακοντα]{.greek-omitted} [και]{.greek-omitted} [δυο]{.greek-omitted}[11:2]{.aside}

και [δωσω]{.greek-omitted} [δοσω]{.greek-added} τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} της γης εστωσαι[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ [εκπορευεται]{.greek-omitted} εκ του στοματος αυτων [εκπορευεται]{.greek-added} και κατεσθιει τους εχθρους αυτων και ει τις [αυτους]{.greek-added} θελει [αποκτειναι]{.greek-added} [αυτους]{.greek-omitted} [αδικησαι]{.greek-omitted} ουτως δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι εχουσιν [εξουσιαν]{.greek-added} [κλεισαι]{.greek-added} τον [ουρανον]{.greek-abbr} [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων [στρεφειν]{.greek-omitted} [στρεφουσιν]{.greek-added} αυτα εις αιμα και παταξαι την γην [οσακις]{.greek-omitted} [εαν]{.greek-omitted} [θελησωσιν]{.greek-omitted} εν παση πληγη [ως]{.greek-added} [ακις]{.greek-added} [εαν]{.greek-added} [θελωσιν]{.greek-added}[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το αναβαινον εκ της [αβυσσου]{.greek-omitted} [αβυσου]{.greek-added} ποιησει [πολεμον]{.greek-added} μετ αυτων [πολεμον]{.greek-omitted} και νικησει αυτους [και]{.greek-omitted} [αποκτενει]{.greek-omitted} [αυτους]{.greek-omitted}[11:7]{.aside}

και [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων επι της πλατειας της [μεγαλης]{.greek-added} πολεως [της]{.greek-omitted} [μεγαλης]{.greek-omitted} ητις [καλειται]{.greek-omitted} [καλειτ[ε]{.unclear}]{.greek-added} πνευματικως [σοδομα]{.greek-omitted} [σσοδομα]{.greek-added} και [αιγυπτος]{.greek-omitted} [το]{.greek-added} [βορρα]{.greek-added} οπου [και]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτων [εσταυρωθη]{.greek-abbr}[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφουσιν]{.greek-added} [τεθηναι]{.greek-omitted} [τεθηνε]{.greek-added} εις [μνημα]{.greek-omitted} [μνημειον]{.greek-added}[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ [αυτοις]{.greek-omitted} [αυτους]{.greek-added} και [ευφρανθησονται]{.greek-omitted} [ευφραινονται]{.greek-added} και δωρα [δωσουσιν]{.greek-omitted} [πεμπουσιν]{.greek-added} αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα [τας]{.greek-omitted} τρεις ημερας και [ημισυ]{.greek-omitted} [ειμισυ]{.greek-added} πνευμα ζωης εκ του [θεου]{.greek-abbr} εισηλθεν [εις]{.greek-omitted} [εν]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και εστησαν επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} [επεπεσεν]{.greek-added} επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσαν]{.greek-omitted} [λεγουσης]{.greek-added} αυτοις [αναβητε]{.greek-omitted} [ἀναβᾶται]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη [ημερα]{.greek-omitted} [ωρα]{.greek-added} εγενετο σεισμος μεγας και το δεκατον της πολεως επεσεν και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι [λοιποι]{.greek-omitted} [λυποι]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} εμφοβοι εγενοντο και [εδωκαν]{.greek-omitted} [εδοκαν]{.greek-added} δοξαν τω [θεω]{.greek-abbr} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[11:13]{.aside}

η ουαι η δευτερα απηλθεν [ιδου]{.greek-added} [ερχεται]{.greek-added} η ουαι η τριτη [ιδου]{.greek-omitted} [ερχεται]{.greek-omitted} ταχυ[11:14]{.aside}

και ο εβδομος αγγελος εσαλπισεν και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι [ε]{.greek-added} εγενετο [η]{.greek-omitted} [αι]{.greek-added} βασιλ[εια]{.unclear} του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι οι ενωπιον του [θρονου]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-abbr} καθημενοι [[κ[α]{.unclear}θ[ην]{.unclear}τ[αι]{.unclear}]{.corr}]{.greek-added} επι τους θρονους αυτων επεσον επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-omitted} [[κυριω]{.greek-abbr}]{.greek-added}[11:16]{.aside}

λεγοντες ευχαριστο[υμεν]{.unclear} σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο [παντοκρατωρ]{.greek-omitted} [παντοκρατορ]{.greek-added} ο ων και ο ην [και]{.greek-added} [ο]{.greek-added} [ερχομενος]{.greek-added} οτι ειληφας την δυναμιν σου [την]{.greek-omitted} [μεγαλην]{.greek-omitted} και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν [και]{.greek-added} [ηλθεν]{.greek-added} [η]{.greek-added} [οργη]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [καιρος]{.greek-added} [των]{.greek-added} [νεκρων]{.greek-added} και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις [και]{.greek-omitted} τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους [διαφθειροντας]{.greek-omitted} [διαφθειραντας]{.greek-added} την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης [του]{.greek-omitted} [αυτου]{.greek-added} [κυριου]{.greek-omitted} εν τω ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και [σεισμος]{.greek-added} [και]{.greek-added} χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα [και]{.greek-added} [εκραζεν]{.greek-omitted} [κραζει]{.greek-added} ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο [σημειον]{.greek-omitted} [σειμειον]{.greek-added} εν τω [ουρανω]{.greek-abbr} και ιδου δρακων [πυρος]{.greek-omitted} μεγας [πυρρος]{.greek-added} εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και [εβαλεν]{.greek-omitted} [βαλλει]{.greek-added} αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἔστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν [ινα]{.greek-omitted} [ιν]{.greek-added} οταν [τεκη]{.greek-omitted} [τεκει]{.greek-added} [καταφαγε]{.greek-added} το [τεκνον]{.greek-omitted} [τεκριον]{.greek-added} αυτης [καταφαγη]{.greek-omitted}[12:4]{.aside}

και ετεκεν [υιον]{.greek-abbr} αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και [προς]{.greek-omitted} τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει [εκει]{.greek-omitted} τοπον ητοιμασμενον [αυτη]{.greek-added} υπο του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφουσιν]{.greek-added} αυτην ημερας [[ασξ]{.greek-abbr}]{.greek-added} [χιλιας]{.greek-omitted} [διακοσιας]{.greek-omitted} [εξηκοντα]{.greek-omitted}[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου [του]{.greek-added} πολεμησαι μετα του δρακοντος και ο δρακων επολεμησεν και οι αγγελοι αυτου[12:7]{.aside}

και ουκ [ισχυσεν]{.greek-omitted} [ισχυσαν]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} τοπος ευρεθη [αυτω]{.greek-omitted} [αυτοις]{.greek-added} ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και [ο]{.greek-added} σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι [εβληθη]{.greek-omitted} [κατεβληθη]{.greek-added} ο κατηγορος των αδελφων ημων ο κατηγορων [αυτων]{.greek-omitted} [αυτους]{.greek-added} ενωπιον του [θεου]{.greek-abbr} [ημων]{.greek-omitted} ημερας και νυκτος[12:10]{.aside}

και αυτοι [ενικησαν]{.greek-omitted} [ενικισαν]{.greek-added} αυτον δια [το]{.greek-omitted} [του]{.greek-added} [αιμα]{.greek-omitted} [αιματος]{.greek-added} του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων [αχρι]{.greek-omitted} [μεχρι]{.greek-added} θανατου[12:11]{.aside}

δια τουτο [ευφραινεσθε]{.greek-omitted} [ευφραινεσθαι]{.greek-added} [οι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν αυτοις σκηνουντες ουαι [τη]{.greek-omitted} [την]{.greek-added} [γη]{.greek-omitted} [γην]{.greek-added} και [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσαν]{.greek-added} οτι κατεβη ο διαβολος προς [υμας]{.greek-omitted} [ημας]{.greek-added} εχων θυμον [μ]{.unclear}εγαν [ειδως]{.greek-omitted} [ειδος]{.greek-added} οτι [ο]{.unclear}λιγον καιρον εχει[12:12]{.aside}

και οτε [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις ετεκεν τον αρρενα[12:13]{.aside}

και εδοθησαν τη [γυναικι]{.greek-omitted} [γυναικη]{.greek-added} [αι]{.greek-added} δυο πτερυγες του αετου του μεγαλου ινα [πετηται]{.greek-omitted} [πεταται]{.greek-added} εις την ερημον εις τον τοπον αυτης [οπως]{.greek-omitted} [οπου]{.greek-added} [τρεφηται]{.greek-omitted} [τρεφειται]{.greek-added} εκει καιρον και καιρους και [ημισυ]{.greek-omitted} [ειμισυ]{.greek-added} καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον [ποιηση]{.greek-omitted} [ποιησει]{.greek-added}[12:15]{.aside}

και εβοηθησεν η γη τη [γυναικι]{.greek-omitted} [γυναικη]{.greek-added} και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [η]{.greek-omitted} [γη]{.greek-omitted} το στομα αυτης και κατεπιεν τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και [ωργισθη]{.greek-omitted} [οργισθη]{.greek-added} [φησιν]{.greek-added} ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων [του]{.greek-omitted} [σπερματος]{.greek-omitted} [σπερματων]{.greek-added} αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

και [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ειδον]{.greek-omitted} [ιδον]{.greek-added} εκ της θαλασσης θηριον αναβαινον εχον κερατα δεκα και κεφαλας επτα και [ε]{.unclear}πι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο [ειδον]{.greek-omitted} [ιδ[ο]{.unclear}ν]{.greek-added} [ην]{.greek-omitted} ομοιον [παρδαλει]{.greek-omitted} [παρδαλι]{.greek-added} και οι [ποδες]{.greek-omitted} [ποδας]{.greek-added} αυτου ως αρκου και το στομα αυτου ως [στομα]{.greek-omitted} [τομα]{.greek-added} λεοντος [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [την]{.greek-omitted} [δυναμιν]{.greek-omitted} [αυτου]{.greek-omitted} και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν [εκ]{.greek-omitted} των κεφαλων αυτου [ωσει]{.greek-omitted} [ως]{.greek-added} εσφαγμενην εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και [εθαυμασεν]{.greek-omitted} [εθαυμασθη]{.greek-added} [εν]{.greek-added} ολη [η]{.greek-omitted} [τη]{.greek-added} γη οπισω του θηριου[13:3]{.aside}

και [προσεκυνησαν]{.greek-omitted} [προσεκυνησε]{.greek-added} τω δρακοντι [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [οτι]{.greek-added} [εδωκεν]{.greek-added} την εξουσιαν [του]{.greek-added} [θηριου]{.greek-added} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} τω θηριω λεγοντες τις ομοιος τω θηριω και τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημα]{.greek-added} και εδοθη αυτω εξουσια [πολεμον]{.greek-omitted} ποιησαι μηνας [[μβ]{.greek-abbr}]{.greek-added} [τεσσαρακοντα]{.greek-omitted} [δυο]{.greek-omitted}[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το [στομα]{.greek-omitted} [τομα]{.greek-added} αυτου εις [βλασφημιαν]{.greek-omitted} [βλασφημιας]{.greek-added} προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου [και]{.greek-added} τους εν τω [ουρανω]{.greek-abbr} [σκηνουντας]{.greek-omitted} [οικουντας]{.greek-added}[13:6]{.aside}

και εδοθη αυτω ποιησαι πολεμον μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και [λαον]{.greek-omitted} [και]{.greek-omitted} γλωσσαν και εθνος[13:7]{.aside}

και [προσκυνησουσιν]{.greek-omitted} [προσκηνησουσιν]{.greek-added} αυτω παντες οι κατοικουντες επι της γης ων ου γεγραπται [το]{.greek-omitted} [τα]{.greek-added} [ονομα]{.greek-omitted} [ονοματα]{.greek-added} εν [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [βιβλω]{.greek-added} [της]{.greek-omitted} ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις ε[χ]{.unclear}ει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [αιχμαλωτησει]{.greek-added} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτενεῖ]{.greek-added} δει αυτον εν μαχαιρα [αποκτανθηναι]{.greek-omitted} [ἀποκτανθῆναι]{.greek-added} ωδε εστιν η [υπομονη]{.greek-omitted} [πιστις]{.greek-added} και η [πιστις]{.greek-omitted} [υπομονη]{.greek-added} των αγιων[13:10]{.aside}

και [ειδον]{.greek-omitted} [[ι]{.unclear}δον]{.greek-added} αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και ειχεν κερατα δυο ομοια αρνιω και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} το θηριον [το]{.greek-omitted} [τω]{.greek-added} πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει [σημεια]{.greek-omitted} [σειμεια]{.greek-added} μεγαλα [ινα]{.greek-added} και πυρ [ινα]{.greek-omitted} [καταβαινει]{.greek-added} εκ του [ουρανου]{.greek-abbr} [εις]{.greek-added} [καταβαινη]{.greek-omitted} [επι]{.greek-omitted} την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [ὂς]{.greek-added} [εχει]{.greek-added} την πληγην [της]{.greek-added} [μαχαιρης]{.greek-added} και εζησεν [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

και εδοθη αυτω [δουναι]{.greek-added} [πνευμα]{.greek-abbr} [δουναι]{.greek-omitted} τη εικονι του θηριου ινα και [λαληση]{.greek-omitted} [λαλησει]{.greek-added} η εικων του θηριου και [ποιηση]{.greek-omitted} [ποιησοι]{.greek-added} [ινα]{.greek-added} οσοι [εαν]{.greek-omitted} [αν]{.greek-added} μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσουσι]{.greek-added} τη εικονι του θηριου [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους [ελευθερους]{.greek-omitted} [δουλους]{.greek-added} και τους [δουλους]{.greek-omitted} [ελευθερους]{.greek-added} ινα [δωσωσιν]{.greek-omitted} [δοσιν]{.greek-added} αυτοις [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της χειρος αυτων της δεξιας η επι [το]{.greek-omitted} [των]{.greek-added} [μετωπον]{.greek-omitted} [μετωπων]{.greek-added} αυτων[13:16]{.aside}

και ινα μη τις [δυναται]{.greek-omitted} [δυ[νη]{.unclear}ται]{.greek-added} αγορασαι η [πωλησαι]{.greek-omitted} [πολησαι[τι]{.unclear}]{.greek-added} ει μη ο εχων το χαραγμα [του]{.greek-added} [θηριου]{.greek-added} [και]{.greek-added} το ονομα [του]{.greek-omitted} [αυτου]{.greek-added} [θηριου]{.greek-omitted} η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν [ψηφισατω]{.greek-omitted} [ψιφισατω]{.greek-added} [τον]{.greek-omitted} [το]{.greek-added} [αριθμον]{.greek-omitted} [ονομα]{.greek-added} του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο αριθμος αυτου [[χξϛ]{.greek-abbr}]{.greek-added} [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου [το]{.greek-omitted} αρνιον [εστηκος]{.greek-omitted} [εστος]{.greek-added} επι το ορος σιων και μετ αυτου [[ρμδ]{.greek-abbr}]{.greek-added} [αριθμος]{.greek-omitted} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες εχουσαι το ονομα αυτου και το [τνομα]{.greek-added} [ονομα]{.corr} του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων [αυτων]{.greek-omitted} [αυτον]{.greek-added}[14:1]{.aside}

και ηκο[υσα]{.unclear} φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων [και]{.unclear} ως φωνην βροντης μεγαλης και η φωνη ην [ηκου]{.unclear}σα ως [φωνη]{.greek-added} κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου [του]{.greek-added} [αρνιου]{.greek-added} και ενωπιον των τεσσαρων ζωων και [ενωπιον]{.greek-added} των [[κδ]{.greek-abbr}]{.greek-added} πρεσβυτερων και ουδεις εδυνατο μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι εισιν οι ακολουθουντες τω αρνιω οπου αν [υπαγη]{.greek-omitted} [υπαγει]{.greek-added} ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} [ηγορασθησαν]{.greek-omitted} [αγορασθησαν]{.greek-added} απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} εν τω στοματι αυτων [ουχ]{.greek-added} [ευρεθη]{.greek-added} ψευδος [αμωμοι]{.greek-omitted} [γαρ]{.greek-omitted} [εισιν]{.greek-omitted}[14:5]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αγγελον [πετομενον]{.greek-omitted} [πετωμενον]{.greek-added} εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} εχοντα ευαγγελιον αιωνιον [ευαγγελισαι]{.greek-omitted} [ευαγγελισασθαι]{.greek-added} τους καθημενους [και]{.greek-added} [κατοικουντας]{.greek-added} επι της γης και [επι]{.greek-omitted} παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

[λεγων]{.greek-omitted} [λεγον]{.greek-added} εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} και δοτε αυτω δοξαν οτι ηλθεν [η]{.corr} ωρα της κρισεως αυτου και προσκυνησατε [τω]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [ποιησαντι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην [και]{.greek-omitted} την θαλασσαν και πηγας υδατων[14:7]{.aside}

και [αγγελος]{.greek-added} [[αγγελος]{.corr}]{.greek-added} [αλλος]{.corr} δευτερος [αγγελος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων [επεσεν]{.greek-added} επεσεν βαβυλων η μεγαλη [οτι]{.greek-added} εκ του οινου του θυμου της πορνειας αυτης [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει [το]{.greek-added} χαραγμα επι του μετωπου αυτου η επι [την]{.greek-omitted} [χειρα]{.greek-omitted} [της]{.greek-added} [δεξιας]{.greek-added} [χειρος]{.greek-added} αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του [[αιματος]{.corr}]{.greek-added} [[ου]{.corr}]{.greek-added} θυμου του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και [βασανισθησεται]{.greek-omitted} [βασανισθησονται]{.greek-added} εν πυρι και θειω ενωπιον [των]{.greek-omitted} αγιων αγγελων [αγιων]{.greek-added} και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις [αιωνας]{.greek-omitted} [αιωνα]{.greek-added} αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες [το]{.greek-omitted} [θηριον]{.greek-omitted} [τω]{.greek-added} [θηριω]{.greek-added} και [την]{.greek-omitted} [τη]{.greek-added} [εικονα]{.greek-omitted} [εικονι]{.greek-added} αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν [οι]{.greek-omitted} [των]{.greek-added} [τηρουντες]{.greek-omitted} [τηρουντων]{.greek-added} τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα [φωνης]{.greek-omitted} [φωνην]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσης]{.greek-omitted} [λεγουσεις]{.greek-added} [[μοι]{.corr}]{.greek-added} γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} [ινα]{.greek-omitted} [οτι]{.greek-added} [αναπαυσωνται]{.greek-omitted} [αναπαησονται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυτων ακολουθει μετ αυτων[14:13]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου νεφελη λευκη και επι την νεφελην [καθημενον]{.greek-omitted} [καθημενος]{.greek-added} [ομοιον]{.greek-omitted} [ομοιος]{.greek-added} [υιω]{.greek-abbr} [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ [λιαν]{.greek-added}[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του [ναου]{.greek-omitted} [[ουου]{.greek-abbr}]{.greek-added} [κραζων]{.greek-omitted} [κραζον]{.greek-added} εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και [θερισον]{.greek-omitted} [θερησον]{.greek-added} οτι ηλθεν [σου]{.greek-added} η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι [την]{.greek-omitted} [της]{.greek-added} [νεφελην]{.greek-omitted} [νεφελης]{.greek-added} το δρεπανον αυτου επι [την]{.greek-omitted} [γην]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added} και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} [εχον]{.greek-added} [εχων]{.corr} και αυτος δρεπανον οξυ [λιαν]{.greek-added}[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν κραυγη μεγαλη [τω]{.greek-omitted} [το]{.greek-added} εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι ηκμασαν αι σταφυλαι αυτης[14:18]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και ετρυγησεν την αμπελον της γης και εβαλεν εις [την]{.greek-omitted} [τον]{.greek-added} [ληνον]{.greek-omitted} [λινον]{.greek-added} [του]{.greek-added} [θυμου]{.greek-added} [[[θεου]{.greek-abbr}]{.corr}]{.greek-added} του θυμου του [μεγαλου]{.greek-added} [θεου]{.greek-omitted} [τον]{.greek-omitted} [μεγαν]{.greek-omitted}[14:19]{.aside}

και επατηθη [η]{.greek-omitted} [ο]{.greek-added} [ληνος]{.greek-omitted} [λινος]{.greek-added} [εξωθεν]{.greek-omitted} [εξω]{.greek-added} της πολεως και εξηλθεν αιμα εκ της [ληνου]{.greek-omitted} [λινου]{.greek-added} αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας πληγας [επτα]{.greek-omitted} τας εσχατας οτι εν [αυταις]{.greek-omitted} [αυτας]{.greek-added} ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην [την]{.greek-added} [μεμιγμενην]{.greek-added} [πυρι]{.greek-added} εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην μωυσεως του δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και [αληθιναι]{.greek-omitted} [αληθη]{.greek-added} [και]{.greek-added} αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

[και]{.greek-added} τις ου μη φοβηθη [σε]{.greek-omitted} [κυριε]{.greek-abbr} και [δοξαση]{.greek-omitted} [δοξασοι]{.greek-added} το ονομα σου οτι μονος [αγιος]{.greek-omitted} [οτι]{.greek-omitted} [οσιος]{.greek-added} [ει]{.greek-added} [και]{.greek-added} παντα τα εθνη [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και [προσκυνησουσιν]{.greek-omitted} [προσκυνησου]{.greek-added} ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ηνοιγη ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας [τκ]{.greek-added} [εκ]{.corr} του ναου [οι]{.greek-omitted} [ησαν]{.greek-omitted} ενδεδυμενοι [λινον]{.greek-omitted} [ληνουν]{.greek-added} καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν εις τον ναον αχρι τελεσθωσιν αι [επτα]{.greek-omitted} πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις [υπαγετε]{.greek-omitted} [υπαγετ[αι]{.unclear}]{.greek-added} [και]{.greek-omitted} [εκχεατε]{.greek-omitted} [εκχεαται]{.greek-added} τας επτα [φιαλας]{.greek-omitted} [φυαλας]{.greek-added} του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος [αγγελος]{.greek-added} και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον [επι]{.greek-omitted} [εις]{.greek-added} τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο [δευτερος]{.greek-omitted} [[β]{.greek-abbr}]{.greek-added} αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις [την]{.greek-omitted} θαλασσαν και εγενετο [ως]{.greek-added} αιμα [ως]{.greek-omitted} νεκρου και πασα ψυχη ζωσα [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} [των]{.greek-added} εν τη θαλασση[16:3]{.aside}

και ο τριτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την [φιαλην]{.greek-omitted} [φυαλην]{.greek-added} αυτου εις τους ποταμους και εις τας πηγας των υδατων και [εγενετο]{.greek-omitted} [εγενοντο]{.greek-added} α[ι]{.greek-supplied}μα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην [και]{.greek-added} ο οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι [αιμα]{.greek-omitted} [αιματα]{.greek-added} [ἁγίων]{.greek-added} [αγιων]{.greek-omitted} [και]{.greek-omitted} προφητων εξεχεαν και αιμα αυτοις εδωκας [πιειν]{.greek-omitted} [ποιειν]{.greek-added} [οτι]{.greek-added} αξιοι εισιν[16:6]{.aside}

και ηκουσα [φωνην]{.greek-added} [εκ]{.greek-added} του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο [παντοκρατωρ]{.greek-omitted} [παντοκρατορ]{.greek-added} [αληθιναι]{.greek-omitted} [αλιθηναι]{.greek-added} και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την [φιαλην]{.greek-omitted} [φυαλην]{.greek-added} αυτου επι τον ηλιον και εδοθη αυτω [καυματισαι]{.greek-omitted} [καυματησαι]{.greek-added} [τους]{.greek-added} [[ανθρωπους]{.greek-abbr}]{.greek-added} εν πυρι [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} το ονομα του [θεου]{.greek-abbr} του εχοντος [την]{.greek-added} εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την [φιαλην]{.greek-omitted} [φυαλην]{.greek-added} αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και [εμασωντο]{.greek-omitted} [εμασσοντο]{.greek-added} τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την [φιαλην]{.greek-omitted} [φυαλην]{.greek-added} αυτου επι τον ποταμον τον μεγαν [τον]{.greek-added} ευφρατην και εξηρανθη το υδωρ [αυτου]{.greek-omitted} ινα ετοιμασθη [η]{.greek-omitted} οδος [τοις]{.greek-added} [των]{.greek-omitted} [βασιλεων]{.greek-omitted} [των]{.greek-omitted} απο [ανατολης]{.greek-omitted} [ανατολων]{.greek-added} ηλιου[16:12]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} εκ του στοματος του δρακοντος και εκ του στοματος του [θηριου]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [του]{.greek-omitted} ψευδοπροφητου [πνευματα]{.greek-abbr} [τρια]{.greek-added} ακαθαρτα [τρια]{.greek-omitted} ως [βατραχοι]{.greek-omitted} [βατραχους]{.greek-added}[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ [πνευματα]{.greek-abbr} δαιμονιων ποιουντα σημεια [α]{.greek-omitted} [και]{.greek-added} [εκπορευεται]{.greek-omitted} [εκπορευονται]{.greek-added} επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης [ταχυ]{.greek-added} μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος [περιπατη]{.greek-omitted} [περιπατησει]{.greek-added} και [βλεπωσιν]{.greek-omitted} [βλεπουσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις [τον]{.greek-omitted} τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἁρμαγεδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την [φιαλην]{.greek-omitted} [φυαλην]{.greek-added} αυτου [επι]{.greek-omitted} [εις]{.greek-added} τον αερα και εξηλθεν φωνη [εκ]{.greek-added} [μεγαλη]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα γεγονεν[16:17]{.aside}

και εγενοντο αστραπαι και [φωναι]{.greek-added} [και]{.greek-added} βρονται και [φωναι]{.greek-omitted} [και]{.greek-omitted} σεισμος [εγενετο]{.greek-added} μεγας οιος ουκ εγενετο αφ ου [οι]{.greek-omitted} [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια [μερη]{.greek-omitted} [μερει]{.greek-added} και αι πολεις των εθνων επεσον και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης [αυτου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added}[16:19]{.aside}

και πασα νησος εφυγεν και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια [καταβαινει]{.greek-omitted} [καταβαινε]{.greek-added} εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη αυτης σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα [φιαλας]{.greek-omitted} [φυαλας]{.greek-added} και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγεκε]{.greek-added} με εις ερημον [τοπον]{.greek-added} εν [πνευματι]{.greek-abbr} και [ειδον]{.greek-omitted} [ιδον]{.greek-added} γυναικα καθημενην επι θηριον κοκκινον γεμον [ονοματα]{.greek-omitted} [ονοματων]{.greek-added} βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἢν]{.greek-added} περιβεβλημενη [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον [και]{.greek-added} [κεχρυσωμενη]{.greek-omitted} [κεχρυσομενη]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις εχουσα [χρυσουν]{.greek-added} ποτηριον [χρυσουν]{.greek-omitted} εν τη χειρι αυτης γεμον βδελυγματων και τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτης [ονομα]{.greek-omitted} γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πόρνων]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} την γυναικα μεθυουσαν εκ του αιματος των αγιων [και]{.greek-added} εκ του αιματος των μαρτυρων [ιησου]{.greek-omitted} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και ειπεν μοι ο αγγελος δια τι εθαυμασας εγω [σοι]{.greek-added} ερω [σοι]{.greek-omitted} το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος [τας]{.greek-omitted} επτα κεφαλας και [τα]{.greek-omitted} [κερατα]{.greek-added} δεκα [κερατα]{.greek-omitted}[17:7]{.aside}

το θηριον ο ειδες ην και ουκ εστιν και μελλει αναβαινειν εκ της αβυσσου και εις [απωλειαν]{.greek-omitted} [απολειαν]{.greek-added} υπαγειν και θαυμασονται οι κατοικουντες επι της γης ων ου γεγραπται τα ονοματα επι το βιβλιον της ζωης απο καταβολης κοσμου [βλεποντων]{.greek-omitted} [βλεποντες]{.greek-added} [ο]{.greek-added} [[το]{.corr}]{.greek-added} [θηριον]{.greek-added} οτι ην [το]{.greek-omitted} [θηριον]{.greek-omitted} και ουκ εστιν και [παρεσται]{.greek-omitted} [παρεστιν]{.greek-added}[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη [καθηται]{.greek-omitted} [καθιται]{.greek-added} επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [επτα]{.greek-added} [εισι]{.greek-added} [και]{.greek-added} [βασιλεις]{.greek-added} [επτα]{.greek-added} [εισιν]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ο εις εστιν ο αλλος ουπω ηλθεν και οταν ελθη ολιγον [δει]{.greek-omitted} [δη]{.greek-added} αυτον [μειναι]{.greek-omitted} [μηναι]{.greek-added}[17:10]{.aside}

και το θηριον ο ην και ουκ εστιν και [αυτος]{.greek-omitted} [αυτο]{.greek-added} [ογδοος]{.greek-omitted} [ογδοοκ]{.greek-added} εστιν και εκ των επτα εστιν και εις απωλειαν υπαγει[17:11]{.aside}

και τα [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν λαμβανουσιν μετα του θηριου[17:12]{.aside}

ουτοι μιαν [γνωμην]{.greek-added} εχουσιν [γνωμην]{.greek-omitted} και την δυναμιν και την εξουσιαν αυτων τω θηριω διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμισουσι]{.greek-added} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου [κλητοι]{.greek-omitted} [κλοιτοι]{.greek-added} και εκλεκτοι και πιστοι[17:14]{.aside}

και [λεγει]{.greek-omitted} [λεγοι]{.greek-added} μοι τα υδατα α [ειδες]{.greek-omitted} [ιδες]{.greek-added} ου η πορνη καθηται [καοι]{.greek-added} [λαοι]{.corr} και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} κερατα α [ειδες]{.greek-omitted} [ιδες]{.greek-added} και το θηριον ουτοι μισησουσιν [την]{.greek-omitted} [αυτην]{.greek-added} [πορνην]{.greek-omitted} και [ηρημωμενην]{.greek-omitted} [ερημωμενην]{.greek-added} ποιησουσιν αυτην και γυμνην [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} και τας σαρκας αυτης φαγονται και αυτην [κατακαυσουσιν]{.greek-omitted} [καυσουσιν]{.greek-added} εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων [ποιησαι]{.greek-omitted} [ποιησαν]{.greek-added} την γνωμην αυτου και ποιησαι [μιαν]{.greek-added} γνωμην [μιαν]{.greek-omitted} και δουναι την βασιλειαν αυτων τω θηριω αχρι [τελεσθωσιν]{.greek-omitted} [τελεσθησονται]{.greek-added} οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} μετα ταυτα [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν [εν]{.greek-added} ισχυρα φωνη [και]{.greek-added} [μεγαλη]{.greek-added} λεγων [επεσεν]{.greek-added} επεσεν βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος [πνευματος]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [ορνεου]{.greek-omitted} ακαθαρτου και μεμισημενου[18:2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωτηκε]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν [εξελθε]{.greek-omitted} [εξελθατε]{.greek-added} εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πλη[γ]{.unclear}ων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

[αποδοτε]{.greek-omitted} [αποδωτε]{.greek-added} αυτη ως και αυτη απεδωκεν [υμιν]{.greek-added} και [διπλωσατε]{.greek-omitted} [διπλωσαται]{.greek-added} αυτη διπλα κατα [τους]{.greek-added} [τα]{.corr} εργα αυτης [εν]{.greek-omitted} [τω]{.greek-omitted} [ποτηριω]{.greek-omitted} [ω]{.greek-omitted} [εκερασεν]{.greek-omitted} [κερασατε]{.greek-omitted} [αυτη]{.greek-omitted} [διπλουν]{.greek-omitted}[18:6]{.aside}

οσα εδοξασεν αυτην [[εαυτην]{.corr}]{.greek-added} και [εστρηνιασεν]{.greek-omitted} [εστρινοιασε]{.greek-added} τοσουτον δοτε αυτη βασανισμον και πενθος οτι εν τη καρδια αυτης λεγει οτι [καθημαι]{.greek-omitted} [καθημε]{.greek-added} [βασιλισσα]{.greek-omitted} [βασιλεισσα]{.greek-added} και [χηρα]{.greek-omitted} [χειρα]{.greek-added} ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσονται]{.greek-added} [ταυτην]{.greek-added} και κοψονται επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και [στρηνιασαντες]{.greek-omitted} [στρινιασαντες]{.greek-added} οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του βασανισμου αυτης [και]{.greek-added} λεγοντες [ουαι]{.greek-omitted} ουαι η πολις η μεγαλη βαβυλων η πολις η ισχυρα οτι μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαι[σ]{.unclear}ουσι]{.greek-added} και πενθησουσιν [επ]{.greek-omitted} [αυτη]{.greek-omitted} [εφ]{.greek-added} [εαυτων]{.greek-added} οτι τον γομον αυτων ουδεις [αγοραζει]{.greek-omitted} [εξαγοραζει]{.greek-added} ουκετι[18:11]{.aside}

γομον [χρυσου]{.greek-omitted} [χρυσιου]{.greek-added} και [αργυρου]{.greek-omitted} [αργυριου]{.greek-added} και λιθου τιμιου και μαργαριτου και [βυσσινου]{.greek-omitted} [βυσσου]{.greek-added} και [πορφυρου]{.greek-omitted} [πορφυρας]{.greek-added} και [σηρικου]{.greek-omitted} [συρικου]{.greek-added} και κοκκινου και παν ξυλον [θνηνον]{.greek-added} [θυινον]{.greek-omitted} [[θυηνον]{.corr}]{.greek-added} και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και [μαργαριτου]{.greek-added} [και]{.greek-added} [μαρμαρου]{.greek-omitted} [μαρμαρον]{.greek-added}[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κινναμωμον]{.greek-added} [και]{.greek-added} [αμωμον]{.greek-added} και θυμιαματα και μυρον και λιβανον και οινον και ελαιον και σεμιδαλιν και σιτον και [κτηνη]{.greek-added} [και]{.greek-added} προβατα [και]{.greek-omitted} [κτηνη]{.greek-omitted} [προς]{.greek-added} [υπακουσεται]{.greek-added} [τουτοις]{.greek-added} [τ[ο]{.unclear}]{.greek-added} [ουδεις]{.greek-added} [αγοραζει]{.greek-added} και ιππων και [ραιδων]{.greek-omitted} [ρεδων]{.greek-added} και σωματων και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και [τα]{.greek-omitted} λαμπρα [απωλετο]{.greek-omitted} [απολετο]{.greek-added} [απολετο]{.greek-added} απο σου και ουκετι [αυτα]{.greek-omitted} ου μη ευρης [αυτα]{.greek-added}[18:14]{.aside}

[και]{.greek-added} οι εμποροι τουτων οι [πλουτησαντες]{.greek-omitted} [πλουτισαντες]{.greek-added} απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης [κλαιοντες]{.greek-omitted} [κλεοντες]{.greek-added} και πενθουντες[18:15]{.aside}

και λεγοντες ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον και [κεχρυσωμενη]{.greek-omitted} [κεχρυσομενη]{.greek-added} [εν]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος [αυτης]{.greek-added} και πας [κυβερνητης]{.greek-omitted} [κιβερνιτης]{.greek-added} και πας ο επι [τοπον]{.greek-omitted} [των]{.greek-added} [πλοιων]{.greek-added} πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και εκραζον βλεποντες τον καπνον της πυρωσεως αυτης [λεγοντες]{.greek-omitted} [και]{.greek-added} [ελεγον]{.greek-added} τις [ομοια]{.greek-omitted} [ωμοια]{.greek-added} τη πολει τη μεγαλη[18:18]{.aside}

και [εβαλον]{.greek-omitted} [εβαλλον]{.greek-added} χουν επι τας κεφαλας αυτων και εκραζον [κλαιοντες]{.greek-omitted} [κλ[ε]{.unclear}ιοντες]{.greek-added} και πενθουντες και λεγοντες [ουαι]{.greek-omitted} ουαι η πολις η μεγαλη εν η [ε]{.greek-added} [επλουτησαν]{.greek-omitted} [πλουτησαν]{.greek-added} παντες οι εχοντες [τα]{.greek-omitted} πλοια εν τη θαλασση εκ της τιμιοτητος αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} [ο]{.greek-added} [ουρανε]{.greek-omitted} [[ουρανος]{.greek-abbr}]{.greek-added} και οι αγιοι [και]{.greek-omitted} [οι]{.greek-omitted} αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον [ως]{.greek-omitted} [μυλον]{.greek-omitted} [μεγαν]{.greek-omitted} [μεγα]{.greek-added} και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και [αυλητων]{.greek-omitted} [αυλιτων]{.greek-added} και σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης [και]{.greek-added} πασης τεχνης [επινοια]{.greek-added} ου μη ευρεθη εν σοι ετι και φωνη μυλου ου μη ακουσθη εν σοι ετι[18:22]{.aside}

[και]{.greek-omitted} [φως]{.greek-omitted} [λυχνου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [φωνη]{.greek-omitted} [νυμφιου]{.greek-omitted} [και]{.greek-omitted} [νυμφης]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} οτι οι εμποροι [σου]{.greek-omitted} ησαν οι μεγιστανες της γης οτι εν τη [φαρμακεια]{.greek-omitted} [φαρμακια]{.greek-added} σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη [αιματα]{.greek-omitted} [αιμα]{.greek-added} προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

[και]{.greek-added} μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην μεγαλην [ως]{.greek-added} οχλου πολλου εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δοξα]{.greek-added} και η [δοξα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τιμη]{.greek-added} [και]{.greek-added} [η]{.greek-added} [δυναμις]{.greek-added} [τ[ω]{.unclear}]{.greek-added} [[θεω]{.greek-abbr}]{.greek-added} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι [και]{.greek-added} [πισται]{.greek-added} αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [εφθειρε]{.greek-added} την γην εν τη πορνεια αυτης και εξεδικησεν το αιμα των δουλων αυτου εκ [της]{.greek-added} χειρος αυτης[19:2]{.aside}

και δευτερον [ειρηκεν]{.greek-omitted} [ειρεικεν]{.greek-added} αλληλουια και ο καπνος αυτης [αναβανει]{.greek-added} [αναβαινει]{.corr} εις τους αιωνας των αιωνων[19:3]{.aside}

και [επεσον]{.greek-omitted} [επεσαν]{.greek-added} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} οι εικοσι τεσσαρες [πρεσβυτεροι]{.greek-added} και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη [απο]{.greek-omitted} [εκ]{.greek-added} του θρονου εξηλθεν λεγουσα αινειτε [τον]{.greek-omitted} [θεον]{.greek-omitted} [τω]{.greek-added} [[θεω]{.greek-abbr}]{.greek-added} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα [φωνην]{.greek-added} ως [φωνην]{.greek-omitted} οχλου πολλου και [ως]{.greek-omitted} [ο]{.greek-added} φωνην υδατων πολλων και ως φωνην βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντων]{.greek-added} αλληλουια οτι εβασιλευσεν [κυριος]{.greek-omitted} ο [θεος]{.greek-abbr} ημων ο [παντοκρατωρ]{.greek-omitted} [παντοκρατορ]{.greek-added}[19:6]{.aside}

[χαιρωμεν]{.greek-omitted} [χαιρομεν]{.greek-added} και [αγαλλιωμεθα]{.greek-omitted} [αγαλλιωμεν]{.greek-added} και [δωμεν]{.greek-omitted} [δοσωμεν]{.greek-added} την δοξαν αυτω οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα περιβαληται βυσσινον [καθαρον]{.greek-added} [και]{.greek-added} λαμπρον [και]{.greek-omitted} [καθαρον]{.greek-omitted} το γαρ βυσσινον τα δικαιωματα των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις το δειπνον του [γαμου]{.greek-omitted} [του]{.greek-omitted} αρνιου κεκλημενοι [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} ουτοι οι λογοι αληθινοι [εισι]{.greek-added} του [θεου]{.greek-abbr} [εισιν]{.greek-omitted}[19:9]{.aside}

και επεσα εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι ορα μη [ποιησεις]{.greek-added} [τουτο]{.greek-added} συνδουλος σου ειμι [εγω]{.greek-added} και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια [του]{.greek-omitted} [ιησου]{.greek-abbr} εστιν το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον [κα]{.unclear}λουμενος πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων [ονοματα]{.greek-omitted} [γεγραμμενα]{.greek-omitted} [και]{.greek-omitted} ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματι[ο]{.unclear}ν [βεβαμμενον]{.greek-omitted} [ρεραντισμενον]{.greek-added} αιματι και καλειται το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα [του]{.greek-added} [τα]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ουρανω]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} ηκολουθει αυτω [επι]{.greek-omitted} [εφ]{.greek-added} ιπποις [λευκοις]{.greek-omitted} [πολλοι]{.greek-added} ενδεδυμενοι βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια [διστομος]{.greek-omitted} [οξεια]{.greek-omitted} [οζεια]{.greek-added} ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος πατει την [ληνον]{.greek-omitted} [λινον]{.greek-added} του οινου του θυμου [και]{.greek-added} της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-omitted} [[υιος]{.greek-abbr}]{.greek-added} κυριων[19:16]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [αλλον]{.greek-added} αγγελον εστωτα εν τω ηλιω και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη [λεγων]{.greek-omitted} [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι δευτε συναχθητε εις το δειπνον [το]{.greek-omitted} [μεγα]{.greek-omitted} του [μεγαλου]{.greek-added} [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων [και]{.greek-omitted} σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων [και]{.greek-omitted} μικρων τε και μεγαλων[19:18]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι [τον]{.greek-added} πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον και [ο]{.greek-omitted} μετ αυτου [ο]{.greek-added} [ψευδοπροφητης]{.greek-omitted} [ψευδοπροφητις]{.greek-added} ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες [εβληθησαν]{.greek-omitted} [βληθησονται]{.greek-added} οι δυο εις την λιμνην του πυρος την [καιομενην]{.greek-omitted} [κεομενην]{.greek-added} εν [τω]{.greek-added} θειω[19:20]{.aside}

