---
title: "Collation of Byz^RP^ vs 32028 (2028)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2028 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32028).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2028                                   	| λογος                              	|
| 2028 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2028 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2028               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2028                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2028 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2028                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} [οσα]{.greek-omitted} [ειδεν]{.greek-omitted}[1:2]{.aside}

[ος]{.greek-omitted} [εμαρτυρησεν]{.greek-omitted} [τον]{.greek-omitted} λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [τε]{.greek-added} [ειδεν]{.greek-omitted} [ειδον]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [εισι]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [χρη]{.greek-added} [γενεσθαι]{.greek-added}[1:2 | instance no. 2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και [οι]{.greek-added} [τηρουντες]{.greek-omitted} [πληρουντες]{.greek-added} τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-omitted} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α [εστιν]{.greek-added} ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [[χριστου]{.greek-abbr}]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} ο μαρτυς ο πιστος ο πρωτοτοκος [εκ]{.greek-added} των νεκρων και ο αρχων των βασιλεων της γης [τω]{.greek-omitted} [αγαπωντι]{.greek-omitted} [ημας]{.greek-omitted} [και]{.greek-omitted} [λουσαντι]{.greek-omitted} [ημας]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [αμαρτιων]{.greek-omitted} [ημων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [αιματι]{.greek-omitted} [αυτου]{.greek-omitted} [αυτος]{.greek-added} [γαρ]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [μαρτυρησας]{.greek-added} [επι]{.greek-added} [ποντιου]{.greek-added} [πιλατου]{.greek-added}[1:5]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιησου]{.greek-omitted} [χριστου]{.greek-omitted} [ο]{.greek-omitted} [μαρτυς]{.greek-omitted} [ο]{.greek-omitted} [πιστος]{.greek-omitted} [ο]{.greek-omitted} [πρωτοτοκος]{.greek-omitted} [των]{.greek-omitted} [νεκρων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αρχων]{.greek-omitted} [των]{.greek-omitted} [βασιλεων]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} τω [αγαπωντι]{.greek-omitted} [αγαπησαντι]{.greek-added} [φησιν]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [λυσαντι]{.greek-added} ημας [απο]{.greek-omitted} [εκ]{.greek-added} των [ανομιων]{.greek-added} [αμαρτιων]{.greek-omitted} [ημων]{.greek-omitted} εν τω αιματι αυτου[1:5 | instance no. 2]{.aside}

και εποιησεν ημας [βασιλειαν]{.greek-omitted} [βασιλεις]{.greek-added} [και]{.greek-added} ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται [αυτον]{.greek-omitted} πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται [επ]{.greek-omitted} [αυτον]{.greek-omitted} πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [α]{.greek-added} και το ω [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συγκοινωνος]{.greek-added} εν τη θλιψει και [εν]{.greek-added} [τη]{.greek-added} βασιλεια και υπομονη εν [χριστω]{.greek-omitted} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα [φωνην]{.greek-omitted} οπισω μου [φωνην]{.greek-added} μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης [ο]{.greek-omitted} [εγω]{.greek-added} [ειμι]{.greek-added} [το]{.greek-added} [[α]{.greek-abbr}]{.greek-added} [και]{.greek-added} [το]{.greek-added} [[ω]{.greek-abbr}]{.greek-added} [πρωτος]{.greek-added} [και]{.greek-added} [εσχατος]{.greek-added} [και]{.greek-added} [α]{.greek-added} βλεπεις γραψον εις βιβλιον και πεμψον [ταις]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαις]{.greek-omitted} [εις]{.greek-omitted} [εφεσον]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [σμυρναν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [περγαμον]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [θυατειρα]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [σαρδεις]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [φιλαδελφειαν]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [λαοδικειαν]{.greek-omitted}[1:11]{.aside}

[λεγουσης]{.greek-omitted} [ο]{.greek-omitted} [βλεπεις]{.greek-omitted} [γραψον]{.greek-omitted} [εις]{.greek-omitted} [βιβλιον]{.greek-omitted} [και]{.greek-omitted} [πεμψον]{.greek-omitted} ταις επτα εκκλησιαις εις εφεσον και εις σμυρναν και εις περγαμον και [εις]{.greek-omitted} [θυατειρα]{.greek-omitted} [εν]{.greek-added} [θυατεροις]{.greek-added} και εις σαρδεις και εις [φιλαδελφειαν]{.greek-omitted} [φιλαδελφιαν]{.greek-added} και εις λαοδικειαν[1:11 | instance no. 2]{.aside}

και [εκει]{.greek-omitted} επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των επτα λυχνιων ομοιον υιω [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι [ως]{.greek-omitted} [και]{.greek-added} [ωσει]{.greek-added} εριον λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου [φησιν]{.greek-added} ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [αυτου]{.greek-omitted} [ως]{.greek-omitted} [φωνη]{.greek-omitted} [υδατων]{.greek-omitted} [πολλων]{.greek-omitted}[1:15]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [ποδες]{.greek-omitted} [αυτου]{.greek-omitted} [ομοιοι]{.greek-omitted} [χαλκολιβανω]{.greek-omitted} [ως]{.greek-omitted} [εν]{.greek-omitted} [καμινω]{.greek-omitted} [πεπυρωμενοι]{.greek-omitted} και η φωνη αυτου [φησιν]{.greek-added} ως φωνη υδατων πολλων[1:15 | instance no. 2]{.aside}

και εχων εν τη δεξια αυτου [χειρι]{.greek-omitted} [φησιν]{.greek-added} αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως [ο]{.greek-omitted} ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον [επεσα]{.greek-omitted} [προς]{.greek-omitted} [[φη]{.greek-abbr}]{.greek-added} [επεσον]{.greek-added} [επι]{.greek-added} τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} την δεξιαν αυτου [χειρα]{.greek-added} επ εμε λεγων [μοι]{.greek-added} [μη]{.greek-omitted} [φοβου]{.greek-omitted} εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων [αμην]{.greek-omitted} [και]{.greek-omitted} [εχω]{.greek-omitted} [τας]{.greek-omitted} [κλεις]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [αδου]{.greek-omitted}[1:18]{.aside}

γραψον [ουν]{.greek-omitted} α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων [ων]{.greek-omitted} [ους]{.greek-added} ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν [και]{.greek-omitted} [αι]{.greek-omitted} [λυχνιαι]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιαι]{.greek-omitted} [εισιν]{.greek-omitted}[1:20]{.aside}

[και]{.greek-added} [το]{.greek-omitted} [μυστηριον]{.greek-omitted} [των]{.greek-omitted} επτα [αστερων]{.greek-omitted} [ων]{.greek-omitted} [λυχνιαι]{.greek-added} [ας]{.greek-added} ειδες [επι]{.greek-omitted} [της]{.greek-omitted} [δεξιας]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [λυχνιας]{.greek-omitted} [τας]{.greek-omitted} [χρυσας]{.greek-omitted} [οι]{.greek-omitted} [επτα]{.greek-omitted} [αστερες]{.greek-omitted} [αγγελοι]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [εκκλησιων]{.greek-omitted} [εισιν]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [λυχνιαι]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} επτα εκκλησιαι εισιν[1:20 | instance no. 2]{.aside}

### Chapter 2

τω αγγελω της [εν]{.greek-omitted} [εφεσω]{.greek-omitted} [εφεσιων]{.greek-added} εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων [επι]{.greek-added} [εν]{.greek-omitted} [μεσω]{.greek-omitted} των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη [βαστασαι]{.greek-omitted} [βασταξαι]{.greek-added} [τους]{.greek-added} κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις [και]{.greek-added} [εβαπτισας]{.greek-added}[2:2]{.aside}

και υπομονην εχεις [και]{.greek-omitted} [εβαστασας]{.greek-omitted} δια το ονομα μου και [κεκοπίακες]{.greek-added} [ουκ]{.greek-omitted} [εκοπιασας]{.greek-omitted}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν [ποθεν]{.greek-omitted} [οθεν]{.greek-added} [εκ]{.greek-added} πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν [μη]{.greek-omitted} [μετανοησης]{.greek-omitted}[2:5]{.aside}

[μνημονευε]{.greek-omitted} [ουν]{.greek-omitted} [ποθεν]{.greek-omitted} [πεπτωκας]{.greek-omitted} [και]{.greek-omitted} [μετανοησον]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [πρωτα]{.greek-omitted} [εργα]{.greek-omitted} [ποιησον]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [ερχομαι]{.greek-omitted} [σοι]{.greek-omitted} [ταχυ]{.greek-omitted} [και]{.greek-omitted} [κινησω]{.greek-omitted} [την]{.greek-omitted} [λυχνιαν]{.greek-omitted} [σου]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [τοπου]{.greek-omitted} [αυτης]{.greek-omitted} [εαν]{.greek-omitted} μη μετανοησης[2:5 | instance no. 2]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν [τω]{.greek-omitted} [μεσω]{.greek-added} [του]{.greek-added} [παραδεισω]{.greek-omitted} [παραδεισου]{.greek-added} του [θεου]{.greek-abbr} [μου]{.greek-omitted}[2:7]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την [πτωχειαν]{.greek-omitted} [πενιαν]{.greek-added} αλλα πλουσιος ει και την βλασφημιαν εκ των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βάλλειν]{.greek-added} [εξ]{.greek-added} [υμων]{.greek-added} ο διαβολος [εξ]{.greek-omitted} [υμων]{.greek-omitted} εις φυλακην ινα πειρασθητε και εξετε θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις [φησι]{.greek-added} το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις εν αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς μου ο [πιστος]{.greek-added} [οτι]{.greek-added} [πας]{.greek-added} [μαρτυς]{.greek-added} πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου ολιγα οτι εχεις [εκει]{.greek-omitted} κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδασκεν]{.greek-added} [τον]{.greek-omitted} [εν]{.greek-added} [τω]{.greek-added} [βαλακ]{.greek-omitted} [βαλαακ]{.greek-added} βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ [κρατουντας]{.greek-omitted} [κρατουντα]{.greek-added} την διδαχην των νικολαιτων [ομοιως]{.greek-omitted} [ημισω]{.greek-added}[2:15]{.aside}

μετανοησον [ουν]{.greek-omitted} ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω [φαγειν]{.greek-added} [απο]{.greek-added} του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την [διακονιαν]{.greek-added} [και]{.greek-added} [την]{.greek-added} αγαπην και την πιστιν [και]{.greek-omitted} [την]{.greek-omitted} [διακονιαν]{.greek-omitted} και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου [οτι]{.greek-omitted} [αφεις]{.greek-omitted} την γυναικα [σου]{.greek-omitted} ιεζαβελ [η]{.greek-omitted} [λεγει]{.greek-omitted} [την]{.greek-added} [λεγουσαν]{.greek-added} εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και [ειδωλοθυτα]{.greek-added} φαγειν [ειδωλοθυτα]{.greek-omitted}[2:20]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση [και]{.greek-omitted} [ου]{.greek-omitted} [θελει]{.greek-omitted} [μετανοησαι]{.greek-omitted} εκ της πορνειας αυτης [και]{.greek-added} [ου]{.greek-added} [μετανοησεν]{.greek-added}[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους [μοι]{.greek-added} [μοιχευοντας]{.greek-omitted} [μετ]{.greek-omitted} [αυτης]{.greek-omitted} [εις]{.greek-omitted} [θλιψιν]{.greek-omitted} [μεγαλην]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [μετανοησωσιν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [εργων]{.greek-omitted} [αυτης]{.greek-omitted}[2:22]{.aside}

[ιδου]{.greek-omitted} [βαλλω]{.greek-omitted} [αυτην]{.greek-omitted} [εις]{.greek-omitted} [κλινην]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μοιχευοντας]{.greek-omitted} [χευοντας]{.greek-added} μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22 | instance no. 2]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο [ερευνων]{.greek-omitted} [εραυνων]{.greek-added} νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βάθη]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω [σιδηρα]{.greek-omitted} [ως]{.greek-omitted} [τα]{.greek-omitted} [σκευη]{.greek-omitted} [τα]{.greek-omitted} [κεραμικα]{.greek-omitted} [συντριβησεται]{.greek-omitted} [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[σιδηρα]{.greek-added} και [ποιμανει]{.greek-omitted} [αυτους]{.greek-omitted} [εν]{.greek-omitted} [ραβδω]{.greek-omitted} [σιδηρα]{.greek-omitted} [ως]{.greek-omitted} τα σκευη τα κεραμικα [συντριβησεται]{.greek-omitted} [συντριβεται]{.greek-added} [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27 | instance no. 2]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι ζης και νεκρος [ει]{.greek-omitted} [η]{.greek-added}[3:1]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [στηριζον]{.greek-added} τα [λοιπα]{.greek-omitted} [μακρα]{.greek-added} α [εμελλες]{.greek-omitted} [ημελλες]{.greek-added} αποβαλλειν ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} [μου]{.greek-omitted}[3:2]{.aside}

μνημονευε ουν [φησι]{.greek-added} πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη γνως ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα [και]{.greek-added} εν σαρδεσιν [α]{.greek-omitted} [οι]{.greek-added} ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν φιλαδελφεια εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο [εχων]{.greek-omitted} [εχον]{.greek-added} την [κλειν]{.greek-omitted} [κλειδα]{.greek-added} του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει [και]{.greek-added} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} ο [ανοιγων]{.greek-omitted} [κλειων]{.greek-added} και ουδεις [ανοιξει]{.greek-omitted} [ανοιγει]{.greek-added}[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην [ην]{.greek-omitted} [και]{.greek-added} ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι [σοι]{.greek-added} εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται [ιδου]{.greek-omitted} [και]{.greek-added} ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι [εγω]{.greek-added} [ηγαπησα]{.greek-omitted} [ηγαπηκα]{.greek-added} σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι [της]{.greek-omitted} [την]{.greek-added} [οικουμενης]{.greek-omitted} [οικουμενην]{.greek-added} [ολης]{.greek-omitted} [ολην]{.greek-added} πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η [καταβαινει]{.greek-omitted} [καταβαινουσα]{.greek-added} εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα μου το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της κτισεως του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος οφελον ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος [μελλω]{.greek-omitted} [σε]{.greek-omitted} [εμεσαι]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [μου]{.greek-omitted}[3:16]{.aside}

[ουτως]{.greek-omitted} [οτι]{.greek-omitted} [χλιαρος]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [ζεστος]{.greek-omitted} [ουτε]{.greek-omitted} [ψυχρος]{.greek-omitted} μελλω σε εμεσαι εκ του στοματος μου[3:16 | instance no. 2]{.aside}

οτι λεγεις πλουσιος ειμι και [πεπλουτηκα]{.greek-omitted} [πεπλουτικα]{.greek-added} [και]{.greek-omitted} [ουδενος]{.greek-omitted} [ουδεν]{.greek-added} [ος]{.greek-added} χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και [ο]{.greek-omitted} ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι [χρυσιον]{.greek-omitted} παρ εμου [χρυσιον]{.greek-added} πεπυρωμενον εκ πυρος ινα [πλουτησης]{.greek-omitted} [πλουτισης]{.greek-added} και ιματια λευκα ινα [περιβαλη]{.greek-omitted} [περιβαλλη]{.greek-added} και μη φανερωθη η αισχυνη της γυμνοτητος σου και κολλυριον [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [εγχρισον]{.greek-added} τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω ζηλωσον ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω [εαν]{.greek-omitted} [τις]{.greek-omitted} [ακουση]{.greek-omitted} [της]{.greek-omitted} [φωνης]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ανοιξη]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted} [και]{.greek-omitted} [εισελευσομαι]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [δειπνησω]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted}[3:20]{.aside}

[ιδου]{.greek-omitted} [εστηκα]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [θυραν]{.greek-omitted} [και]{.greek-omitted} [κρουω]{.greek-omitted} εαν τις ακουση της φωνης μου και ανοιξη την θυραν [και]{.greek-omitted} εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20 | instance no. 2]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω [αυτου]{.greek-omitted} [μου]{.greek-added}[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη [ην]{.greek-omitted} [ης]{.greek-added} ηκουσα ως σαλπιγγος λαλουσης μετ εμου [λεγων]{.greek-omitted} [λεγουσα]{.greek-added} αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι [τον]{.greek-omitted} [του]{.greek-added} [θρονον]{.greek-omitted} [θρονου]{.greek-added} καθημενος[4:2]{.aside}

ομοιος ορασει [λιθου]{.greek-added} [ιασπιδος]{.greek-added} [και]{.greek-added} [σαρδιου]{.greek-added} λιθω ιασπιδι και σαρδιω και [ιρις]{.greek-omitted} [ἴρις]{.greek-added} κυκλοθεν του θρονου [ομοιως]{.greek-omitted} [ομοιος]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδινου]{.greek-added}[4:3]{.aside}

και κυκλοθεν του θρονου θρονοι εικοσι τεσσαρες και επι τους θρονους [τους]{.greek-omitted} εικοσι τεσσαρας πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται [και]{.greek-omitted} [επτα]{.greek-omitted} [λαμπαδες]{.greek-omitted} [πυρος]{.greek-omitted} [καιομεναι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [αυτου]{.greek-omitted} [αι]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} [πνευματα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[4:5]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [εκπορευονται]{.greek-omitted} [αστραπαι]{.greek-omitted} [και]{.greek-omitted} [φωναι]{.greek-omitted} [και]{.greek-omitted} [βρονται]{.greek-omitted} και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr}[4:5 | instance no. 2]{.aside}

και ενωπιον του θρονου [ως]{.greek-omitted} θαλασσα [υαλινη]{.greek-omitted} [υελινη]{.greek-added} ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον εχον [το]{.greek-added} προσωπον [ως]{.greek-added} [ανθρωπου]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} και το τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα εν καθ εν εχον ανα πτερυγας εξ κυκλοθεν και εσωθεν [γεμουσιν]{.greek-omitted} [γεμοντα]{.greek-added} οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσι]{.greek-added} τα ζωα δοξαν και τιμην [και]{.greek-omitted} [ευχαριστιαν]{.greek-omitted} [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[4:9]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [δωσιν]{.greek-omitted} [τα]{.greek-omitted} [ζωα]{.greek-omitted} [δοξαν]{.greek-omitted} [και]{.greek-omitted} [τιμην]{.greek-omitted} και ευχαριστιαν τω καθημενω επι του θρονου [τω]{.greek-omitted} [ζωντι]{.greek-omitted} εις τους αιωνας των αιωνων[4:9 | instance no. 2]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και [προσκυνησουσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει [[κυριε]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [και]{.greek-omitted} ο [θεος]{.greek-abbr} ημων [ο]{.greek-omitted} [αγιος]{.greek-omitted} λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας [τα]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισι]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος εστιν ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις εδυνατο εν τω [ουρανω]{.greek-abbr} ανω ουτε επι της γης [κατω]{.greek-added} ουτε υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και τας επτα σφραγιδας αυτου[5:5]{.aside}

και ειδον εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως εσφαγμενον εχον κερατα επτα και οφθαλμους επτα [α]{.greek-omitted} [οι]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} τα επτα [πνευματα]{.greek-omitted} του [θεου]{.greek-abbr} [[πνευματα]{.greek-abbr}]{.greek-added} [τα]{.greek-added} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ειληφεν εκ της δεξιας του καθημενου επι του θρονου [το]{.greek-added} [βιβλιον]{.greek-added}[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι επεσον [ενω]{.greek-added} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [εχοντες]{.greek-omitted} [εκαστος]{.greek-omitted} [κιθαραν]{.greek-omitted} [και]{.greek-omitted} [φιαλας]{.greek-omitted} [χρυσας]{.greek-omitted} [γεμουσας]{.greek-omitted} [θυμιαματων]{.greek-omitted} [αι]{.greek-omitted} [εισιν]{.greek-omitted} [προσευχαι]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted}[5:8]{.aside}

[πιον]{.greek-added} [και]{.greek-omitted} [οτε]{.greek-omitted} [ελαβεν]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [τα]{.greek-omitted} [τεσσαρα]{.greek-omitted} [ζωα]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [επεσον]{.greek-omitted} [ενωπιον]{.greek-omitted} του αρνιου εχοντες εκαστος κιθαραν και φιαλας χρυσας γεμουσας θυμιαματων αι [εισιν]{.greek-omitted} [εισι]{.greek-added} [αι]{.greek-added} προσευχαι των αγιων[5:8 | instance no. 2]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας [τω]{.greek-omitted} [θεω]{.greek-omitted} ημας εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και ειδον και ηκουσα ως [φωνην]{.greek-omitted} [φωνης]{.greek-added} αγγελων πολλων κυκλω του θρονου και των ζωων και των [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [ο]{.greek-omitted} [αριθμος]{.greek-omitted} [αυτων]{.greek-omitted} [μυριαδες]{.greek-omitted} [μυριαδων]{.greek-omitted} [και]{.greek-omitted} [χιλιαδες]{.greek-omitted} [χιλιαδων]{.greek-omitted}[5:11]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [και]{.greek-omitted} [ηκουσα]{.greek-omitted} [ως]{.greek-omitted} [φωνην]{.greek-omitted} [αγγελων]{.greek-omitted} [πολλων]{.greek-omitted} [κυκλω]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [ζωων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11 | instance no. 2]{.aside}

[λεγοντες]{.greek-omitted} [λεγουσαι]{.greek-added} φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και [τον]{.greek-omitted} πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν τω [ουρανω]{.greek-abbr} και [επι]{.greek-omitted} [εν]{.greek-added} [της]{.greek-omitted} [τη]{.greek-added} [γης]{.greek-omitted} [γη]{.greek-added} και υποκατω της γης και επι της θαλασσης [α]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις παντας ηκουσα λεγοντας τω καθημενω επι του θρονου και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} [το]{.greek-omitted} αμην και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον [οτι]{.greek-omitted} [οτε]{.greek-added} [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνὴ]{.greek-added} βροντης ερχου και ιδε[6:1]{.aside}

και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα νικηση[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [την]{.greek-added} [σφραγιδα]{.greek-added} την δευτεραν [σφραγιδα]{.greek-omitted} ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος [πυρος]{.greek-omitted} [πυρρος]{.greek-added} και τω καθημενω επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτω λαβειν [αυτω]{.greek-added} την ειρηνην [εκ]{.greek-omitted} [απο]{.greek-added} της γης [και]{.greek-added} ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} την τριτην [σφραγιδα]{.greek-added} ηκουσα του τριτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [και]{.greek-omitted} ιδου ιππος μελας και ο καθημενος [επ]{.greek-omitted} [αυτον]{.greek-omitted} [εχων]{.greek-omitted} [ζυγον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτου]{.greek-omitted}[6:5]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [σφραγιδα]{.greek-omitted} [την]{.greek-omitted} [τριτην]{.greek-omitted} [ηκουσα]{.greek-omitted} [του]{.greek-omitted} [τριτου]{.greek-omitted} [ζωου]{.greek-omitted} [λεγοντος]{.greek-omitted} [ερχου]{.greek-omitted} [και]{.greek-omitted} [ιδε]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [ιππος]{.greek-omitted} [μελας]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [καθημενος]{.greek-omitted} επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5 | instance no. 2]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες [κριθης]{.greek-omitted} [κριθων]{.greek-added} δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου και ιδε[6:7]{.aside}

και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και εδοθη αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας των [[ανθρωπων]{.greek-abbr}]{.greek-added} [των]{.greek-added} [εσφαγμενων]{.greek-omitted} [εσφραγισμενων]{.greek-added} δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} [ην]{.greek-omitted} [ειχον]{.greek-omitted}[6:9]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [την]{.greek-omitted} [πεμπτην]{.greek-omitted} [σφραγιδα]{.greek-omitted} [ειδον]{.greek-omitted} [υποκατω]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [τας]{.greek-omitted} [ψυχας]{.greek-omitted} [των]{.greek-omitted} [εσφαγμενων]{.greek-omitted} [δια]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [δια]{.greek-omitted} [την]{.greek-omitted} [μαρτυριαν]{.greek-omitted} του αρνιου ην ειχον[6:9 | instance no. 2]{.aside}

και [εκραξαν]{.greek-omitted} [εκραξον]{.greek-added} φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης [ημων]{.greek-added} ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων [εκ]{.greek-omitted} [απο]{.greek-added} των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} ετι χρονον [μικρον]{.greek-added} εως [ου]{.greek-added} [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων και οι μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκτεινεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

και ειδον οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος [εγενετο]{.greek-added} μελας [εγενετο]{.greek-omitted} ως σακκος τριχινος και η σεληνη [ολη]{.greek-omitted} εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη βαλουσα τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον [ελισσομενον]{.greek-omitted} [ειλισσομενον]{.greek-added} [και]{.greek-omitted} [παν]{.greek-omitted} [ορος]{.greek-omitted} [και]{.greek-omitted} [νησος]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [τοπων]{.greek-omitted} [αυτων]{.greek-omitted} [εκινηθησαν]{.greek-omitted}[6:14]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ουρανος]{.greek-omitted} [απεχωρισθη]{.greek-omitted} [ως]{.greek-omitted} [βιβλιον]{.greek-omitted} [ελισσομενον]{.greek-omitted} και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14 | instance no. 2]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι [χιλιαρχοι]{.greek-omitted} [πλουσιοι]{.greek-added} και οι [πλουσιοι]{.greek-omitted} [χιλιαρχοι]{.greek-added} και οι ισχυροι και πας δουλος και [πας]{.greek-added} ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις [πεσετε]{.greek-omitted} [πεσεται]{.greek-added} εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

και μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους τεσσαρας ανεμους [της]{.greek-omitted} [γης]{.greek-omitted} ινα μη πνεη ανεμος επι της γης μητε [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [μητε]{.greek-omitted} [επι]{.greek-omitted} [τι]{.greek-omitted} [δενδρον]{.greek-omitted}[7:1]{.aside}

[και]{.greek-omitted} [μετα]{.greek-omitted} [τουτο]{.greek-omitted} [ειδον]{.greek-omitted} [τεσσαρας]{.greek-omitted} [αγγελους]{.greek-omitted} [εστωτας]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [τεσσαρας]{.greek-omitted} [γωνιας]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [κρατουντας]{.greek-omitted} [τους]{.greek-omitted} [τεσσαρας]{.greek-omitted} [ανεμους]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [πνεη]{.greek-omitted} [ανεμος]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [μητε]{.greek-omitted} επι της θαλασσης μητε επι [τι]{.greek-omitted} [παν]{.greek-added} δενδρον[7:1 | instance no. 2]{.aside}

και ειδον [αγγελον]{.greek-added} αλλον [αγγελον]{.greek-omitted} αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων [μη]{.greek-omitted} [αδικησητε]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [μητε]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [μητε]{.greek-omitted} [τα]{.greek-omitted} [δενδρα]{.greek-omitted} [αχρι]{.greek-omitted} [ου]{.greek-omitted} [σφραγισωμεν]{.greek-omitted} [τους]{.greek-omitted} [δουλους]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ημων]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [μετωπων]{.greek-omitted} [αυτων]{.greek-omitted}[7:3]{.aside}

[λεγων]{.greek-omitted} μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου [σφραγισωμεν]{.greek-omitted} [σφραγισομεν]{.greek-added} τους δουλους [του]{.greek-omitted} [το[υς]{.unclear}]{.greek-added} [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3 | instance no. 2]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον [και]{.greek-omitted} τεσσαρακοντα [τεσσαρες]{.greek-omitted} [τεσσαρας]{.greek-added} [χιλιαδες]{.greek-omitted} [χιλιαδας]{.greek-added} [εσφραγισμενων]{.greek-omitted} [εσφραγισμενοι]{.greek-added} [απο]{.greek-added} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

[φυλης]{.greek-added} [ιουδα]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} [χιλιαδες]{.greek-added} [εσφραγισμενοι]{.greek-added} εκ φυλης [ιουδα]{.greek-omitted} [δωδεκα]{.greek-omitted} [ρουβιν]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [ρουβιμ]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted} εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ δωδεκα χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι δωδεκα χιλιαδες εκ φυλης ισαχαρ δωδεκα χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων δωδεκα χιλιαδες εκ φυλης ιωσηφ δωδεκα χιλιαδες εκ φυλης βενιαμιν δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εκ παντος εθνους και φυλων και λαων και γλωσσων [εστωτας]{.greek-omitted} [εστωτων]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου περιβεβλημενους στολας [λευκας]{.greek-omitted} και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [καθημενω]{.greek-added} [επι]{.greek-added} [του]{.greek-added} [θρονου]{.greek-added} [θεω]{.greek-abbr} ημων [τω]{.greek-omitted} [καθημενω]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [θρονω]{.greek-omitted} και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και [ειπον]{.greek-omitted} [ειρηκα]{.greek-added} αυτω [κυριε]{.greek-abbr} μου συ οιδας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι εισιν οι ερχομενοι εκ [της]{.greek-omitted} θλιψεως της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν [αυτας]{.greek-added} εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν ετι ουδε διψησουσιν [ετι]{.greek-omitted} ουδ ου μη [πεση]{.greek-omitted} [πεσειται]{.greek-added} επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγησει]{.greek-added} αυτους επι [ζωης]{.greek-omitted} [ζωσας]{.greek-added} πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον εκ των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και [εσταθη]{.greek-omitted} [εστη]{.greek-added} [επι]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [εχων]{.greek-omitted} [λιβανωτον]{.greek-omitted} [χρυσουν]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [θυμιαματα]{.greek-omitted} [πολλα]{.greek-omitted} [ινα]{.greek-omitted} [δωση]{.greek-omitted} [ταις]{.greek-omitted} [προσευχαις]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [παντων]{.greek-omitted} επι το θυσιαστηριον [εχων]{.greek-added} [το]{.greek-omitted} [τον]{.greek-added} [λιβανωτον]{.greek-added} χρυσουν [το]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted}[8:3]{.aside}

[και]{.greek-omitted} [αλλος]{.greek-omitted} [αγγελος]{.greek-omitted} [ηλθεν]{.greek-omitted} [και]{.greek-omitted} [εσταθη]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted} [εχων]{.greek-omitted} [λιβανωτον]{.greek-omitted} [χρυσουν]{.greek-omitted} και εδοθη αυτω θυμιαματα πολλα ινα δωση ταις προσευχαις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3 | instance no. 2]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο [φωναι]{.greek-added} [και]{.greek-added} βρονται [και]{.greek-omitted} [φωναι]{.greek-omitted} και αστραπαι και [σεισμος]{.greek-omitted} [σεισμοι]{.greek-added}[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα [σαλπισωσιν]{.greek-omitted} [σαλπισωσι]{.greek-added}[8:6]{.aside}

και ο πρωτος [αγγελος]{.greek-added} [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ [μεμιγμενα]{.greek-omitted} [μεμιγμενον]{.greek-added} [εν]{.greek-omitted} αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον των κτισματων [των]{.greek-added} εν τη θαλασση [τα]{.greek-omitted} [των]{.greek-added} [εχοντα]{.greek-omitted} [εχοντων]{.greek-added} ψυχας και το τριτον των πλοιων διεφθαρη[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος [ως]{.greek-omitted} [λαμπας]{.greek-omitted} [και]{.greek-omitted} [επεσεν]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [ποταμων]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [τας]{.greek-omitted} [πηγας]{.greek-omitted} [των]{.greek-omitted} [υδατων]{.greek-omitted}[8:10]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [τριτος]{.greek-omitted} [αγγελος]{.greek-omitted} [εσαλπισεν]{.greek-omitted} [και]{.greek-omitted} [επεσεν]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [αστηρ]{.greek-omitted} [μεγας]{.greek-omitted} [καιομενος]{.greek-omitted} ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10 | instance no. 2]{.aside}

και το ονομα του αστερος λεγεται [ο]{.greek-omitted} αψινθος και εγενετο το τριτον των υδατων [εις]{.greek-omitted} αψινθον και πολλοι των [ανθρωπων]{.greek-omitted} [ανθροπων]{.greek-added} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και [το]{.greek-omitted} [τριτον]{.greek-omitted} [αυτης]{.greek-omitted} [μη]{.greek-omitted} [φανη]{.greek-omitted} η ημερα [μη]{.greek-added} [φαινη]{.greek-added} και η νυξ ομοιως[8:12]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} και ηκουσα ενος [αετου]{.greek-omitted} [αγγελου]{.greek-added} πετομενου εν μεσουρανηματι λεγοντος φωνη μεγαλη [ουαι]{.greek-omitted} ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος ως καπνος καμινου [καιομενης]{.greek-omitted} [μεγαλης]{.greek-added} και εσκοτισθη ο ηλιος και [ο]{.greek-omitted} [αηρ]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [καπνου]{.greek-omitted} [του]{.greek-omitted} [φρεατος]{.greek-omitted}[9:2]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [ανεβη]{.greek-omitted} [καπνος]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [φρεατος]{.greek-omitted} [ως]{.greek-omitted} [καπνος]{.greek-omitted} [καμινου]{.greek-omitted} [καιομενης]{.greek-omitted} [και]{.greek-omitted} [εσκοτισθη]{.greek-omitted} [ο]{.greek-omitted} [ηλιος]{.greek-omitted} [και]{.greek-omitted} ο αηρ εκ του καπνου του φρεατος[9:2 | instance no. 2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων αυτων[9:4]{.aside}

και εδοθη αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθησονται]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος [αυτων]{.greek-added} [ως]{.greek-added} [βασανισμος]{.greek-added} σκορπιου οταν παιση [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη ευρησουσιν αυτον και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευγει]{.greek-added} [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα [ομοιωα]{.greek-added} [ομοιωματα]{.corr} των ακριδων ομοια ιπποις ητοιμασμενοις [εις]{.greek-omitted} [προς]{.greek-added} πολεμον και επι τας κεφαλας αυτων ως στεφανοι [χρυσοι]{.greek-omitted} [ομοιοι]{.greek-added} [χρυσω]{.greek-added} και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους [και]{.greek-omitted} [η]{.greek-omitted} [φωνη]{.greek-omitted} [των]{.greek-omitted} [πτερυγων]{.greek-omitted} [αυτων]{.greek-omitted} [ως]{.greek-omitted} [φωνη]{.greek-omitted} [αρματων]{.greek-omitted} [ιππων]{.greek-omitted} [πολλων]{.greek-omitted} [τρεχοντων]{.greek-omitted} [εις]{.greek-omitted} [πολεμον]{.greek-omitted}[9:9]{.aside}

[και]{.greek-omitted} [ειχον]{.greek-omitted} [θωρακας]{.greek-omitted} [ως]{.greek-omitted} [θωρακας]{.greek-omitted} [σιδηρους]{.greek-omitted} και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9 | instance no. 2]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [και]{.greek-added} [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους ανθρωπους μηνας πεντε[9:10]{.aside}

[και]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσιν]{.greek-added} [βασιλεα]{.greek-omitted} επ αυτων [βασιλεα]{.greek-added} [τον]{.greek-added} αγγελον της αβυσσου ονομα αυτω εβραιστι αββαδων [και]{.greek-added} εν [δε]{.greek-omitted} τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} [ετι]{.greek-omitted} δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

λεγουσαν τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και [εις]{.greek-omitted} [την]{.greek-omitted} ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [ιππου]{.greek-omitted} [ιππικου]{.greek-added} μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη ορασει και [τους]{.greek-omitted} [καθημενους]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted} [εχοντας]{.greek-omitted} [θωρακας]{.greek-omitted} [πυρινους]{.greek-omitted} [και]{.greek-omitted} [υακινθινους]{.greek-omitted} [και]{.greek-omitted} [θειωδεις]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [κεφαλαι]{.greek-omitted} [των]{.greek-omitted} [ιππων]{.greek-omitted} [ως]{.greek-omitted} [κεφαλαι]{.greek-omitted} [λεοντων]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [στοματων]{.greek-omitted} [αυτων]{.greek-omitted} [εκπορευεται]{.greek-omitted} [πυρ]{.greek-omitted} [και]{.greek-omitted} [καπνος]{.greek-omitted} [και]{.greek-omitted} [θειον]{.greek-omitted}[9:17]{.aside}

[και]{.greek-omitted} [ουτως]{.greek-omitted} [ειδον]{.greek-omitted} [τους]{.greek-omitted} [ιππους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ορασει]{.greek-omitted} [και]{.greek-omitted} τους καθημενους επ αυτων [θωρακας]{.greek-added} εχοντ[ας]{.unclear} [θωρακας]{.greek-omitted} πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17 | instance no. 2]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του πυρος και [εκ]{.greek-added} του καπνου και [εκ]{.greek-added} του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν [ταις]{.greek-added} [ουραις]{.greek-added} [και]{.greek-added} [εν]{.greek-added} τω στοματι αυτων [εισι]{.greek-added} [εστιν]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ουραις]{.greek-omitted} [αυτων]{.greek-omitted} αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφ[εσι]{.unclear}ν]{.greek-added} εχουσαι κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [ηδικουσαν]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις [ου]{.greek-omitted} [ουδε]{.greek-added} μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα [και]{.greek-omitted} [η]{.greek-added} τα αργυρα και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν [εκ]{.greek-added} [τουτων]{.greek-added} [ουτε]{.greek-added} εκ των φονων αυτων ουτε εκ των φαρμακειων αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και [η]{.greek-omitted} ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν τη χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλαριδιον]{.greek-added} [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι [της]{.greek-omitted} [την]{.greek-added} [θαλασσης]{.greek-omitted} [θαλασσαν]{.greek-added} τον δε ευωνυμον επι [της]{.greek-omitted} [γης]{.greek-omitted} [την]{.greek-added} [γην]{.greek-added}[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται [εμελλον]{.greek-omitted} [ημελλον]{.greek-added} γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη [αυτα]{.greek-omitted} [ταυτα]{.greek-added} γραψης[10:4]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και [ωμοσεν]{.greek-omitted} [ωμοσε]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτω]{.greek-omitted} και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος [ουκετι]{.greek-omitted} [ουκ]{.greek-added} εσται [ετι]{.greek-added}[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν και [ετελεσθη]{.greek-omitted} [τελεσθη]{.greek-added} το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελησε]{.greek-added} τους [εαυτου]{.greek-added} δουλους [αυτου]{.greek-omitted} τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα μετ εμου και λεγουσα υπαγε λαβε το [βιβλιδαριον]{.greek-omitted} [βιβλαριδιον]{.greek-added} το ανεωγμενον εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων [αυτω]{.greek-omitted} [δουναι]{.greek-omitted} [μοι]{.greek-omitted} [το]{.greek-omitted} [βιβλιδαριον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [μοι]{.greek-omitted} [λαβε]{.greek-omitted} [και]{.greek-omitted} [καταφαγε]{.greek-omitted} [αυτο]{.greek-omitted} [και]{.greek-omitted} [πικρανει]{.greek-omitted} [σου]{.greek-omitted} [την]{.greek-omitted} [κοιλιαν]{.greek-omitted} [αλλ]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [σου]{.greek-omitted} [εσται]{.greek-omitted} [γλυκυ]{.greek-omitted} [ως]{.greek-omitted} [μελι]{.greek-omitted}[10:9]{.aside}

[και]{.greek-omitted} [απηλθον]{.greek-omitted} [προς]{.greek-omitted} [τον]{.greek-omitted} [αγγελον]{.greek-omitted} [λεγων]{.greek-omitted} αυτω [δουναι]{.greek-omitted} [δος]{.greek-added} μοι το [βιβλιδαριον]{.greek-omitted} [βιβλαριδιον]{.greek-added} και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9 | instance no. 2]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βιβλαριδιον]{.greek-added} εκ [της]{.greek-omitted} χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [ἀυτό]{.greek-added} και ην εν τω στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και [επι]{.greek-omitted} [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την [εξωθεν]{.greek-omitted} [εσωθεν]{.greek-added} του ναου εκβαλε εξω και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας [[μβ]{.greek-abbr}]{.greek-added} [τεσσαρακοντα]{.greek-omitted} [και]{.greek-omitted} [δυο]{.greek-omitted}[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} της γης εστωσαι[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις [αυτ[ους]{.unclear}]{.greek-added} θελει [αυτους]{.greek-omitted} αδικησαι ουτως δει [αυτον]{.greek-omitted} αποκτανθηναι[11:5]{.aside}

ουτοι εχουσιν [εξουσιαν]{.greek-added} [κλεισαι]{.greek-added} τον ουρανον [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} ινα μη [βρεχη]{.greek-added} υετος [βρεχη]{.greek-omitted} [τας]{.greek-omitted} [ταις]{.greek-added} [ημερας]{.greek-omitted} [ημεραις]{.greek-added} [αυτων]{.greek-added} της προφητειας [αυτων]{.greek-omitted} και εξουσιαν εχουσιν επι των υδατων στρεφειν [αυτα]{.greek-omitted} εις αιμα και παταξαι την γην [οσακις]{.greek-omitted} [εαν]{.greek-omitted} [θελησωσιν]{.greek-omitted} εν παση πληγη [ωσακις]{.greek-added} [εαν]{.greek-added} [θελησωσιν]{.greek-added}[11:6]{.aside}

και [οταν]{.greek-omitted} [οτε]{.greek-added} [τελεσωσιν]{.greek-omitted} [τελεσουσι]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει [μετ]{.greek-omitted} [αυτων]{.greek-omitted} πολεμον και νικησει αυτους [και]{.greek-omitted} [αποκτενει]{.greek-omitted} [αυτους]{.greek-omitted}[11:7]{.aside}

και [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων επι της πλατειας της [μεγαλης]{.greek-added} πολεως [εσονται]{.greek-added} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων [εσταυρωθη]{.greek-abbr}[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και [γλωσσων]{.greek-omitted} [και]{.greek-omitted} [εθνων]{.greek-omitted} [το]{.greek-omitted} [πτωμα]{.greek-omitted} [αυτων]{.greek-omitted} [ημερας]{.greek-omitted} [τρεις]{.greek-omitted} [ημισυ]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [πτωματα]{.greek-omitted} [αυτων]{.greek-omitted} [ουκ]{.greek-omitted} [αφησουσιν]{.greek-omitted} [τεθηναι]{.greek-omitted} [εις]{.greek-omitted} [μνημα]{.greek-omitted}[11:9]{.aside}

[γλωσσων]{.greek-added} [τα]{.greek-added} [πτωματα]{.greek-added} [αυτων]{.greek-added} και [βλεπουσιν]{.greek-omitted} [οι]{.greek-added} εκ των [λαων]{.greek-omitted} [και]{.greek-omitted} [φυλων]{.greek-omitted} [και]{.greek-omitted} [γλωσσων]{.greek-omitted} [και]{.greek-omitted} εθνων [το]{.greek-omitted} [πτωμα]{.greek-omitted} [αυτων]{.greek-omitted} ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφιουσι]{.greek-added} τεθηναι εις μνημα[11:9 | instance no. 2]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και [ευφρανθησονται]{.greek-omitted} [ευφραινονται]{.greek-added} και δωρα [δωσουσιν]{.greek-omitted} [πεμψουσιν]{.greek-added} αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα [τας]{.greek-omitted} τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν [εις]{.greek-omitted} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και εστησαν [επι]{.greek-omitted} [υπο]{.greek-added} τους ποδας αυτων και φοβος μεγας επεσεν επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσαν]{.greek-omitted} [λεγουσης]{.greek-added} αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη [ημερα]{.greek-omitted} [ωρα]{.greek-added} εγενετο σεισμος μεγας και το δεκατον της πολεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα [και]{.greek-omitted} [οι]{.greek-omitted} [λοιποι]{.greek-omitted} [εμφοβοι]{.greek-omitted} [εγενοντο]{.greek-omitted} [και]{.greek-omitted} [εδωκαν]{.greek-omitted} [δοξαν]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[11:13]{.aside}

[και]{.greek-omitted} [εν]{.greek-omitted} [εκεινη]{.greek-omitted} [τη]{.greek-omitted} [ημερα]{.greek-omitted} [εγενετο]{.greek-omitted} [σεισμος]{.greek-omitted} [μεγας]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [δεκατον]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [επεσεν]{.greek-omitted} [και]{.greek-omitted} [απεκτανθησαν]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σεισμω]{.greek-omitted} [ονοματα]{.greek-omitted} [ανθρωπων]{.greek-omitted} [χιλιαδες]{.greek-omitted} [επτα]{.greek-omitted} και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13 | instance no. 2]{.aside}

[η]{.greek-omitted} ουαι η δευτερα απηλθεν η [ουαι]{.greek-omitted} [η]{.greek-omitted} τριτη [ιδου]{.greek-omitted} ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι [εγενετο]{.greek-omitted} [εγενοντο]{.greek-added} [η]{.greek-omitted} [αι]{.greek-added} [βασιλεια]{.greek-omitted} [βασιλειαι]{.greek-added} του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι [οι]{.greek-omitted} ενωπιον [του]{.greek-omitted} [θρονου]{.greek-omitted} του [θεου]{.greek-abbr} καθημενοι επι τους θρονους αυτων επεσον επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και [ηλθεν]{.greek-added} [η]{.greek-added} [οργη]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [ο]{.greek-added} [καιρος]{.greek-added} [των]{.greek-added} [νεκρων]{.greek-added} ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις [και]{.greek-omitted} τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους [διαφθειροντας]{.greek-omitted} [φθειροντας]{.greek-added} την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης [του]{.greek-omitted} [αυτου]{.greek-added} [κυριου]{.greek-omitted} εν τω ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και [σεισμος]{.greek-added} [και]{.greek-added} χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων [δωδεκα]{.greek-omitted} [δεκαδυο]{.greek-added}[12:1]{.aside}

και εν γαστρι εχουσα [εκραζεν]{.greek-omitted} ωδινουσα [κραζει]{.greek-added} και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων [μεγας]{.greek-added} πυρος [μεγας]{.greek-omitted} εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην [και]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [εστηκεν]{.greek-omitted} [ενωπιον]{.greek-omitted} [της]{.greek-omitted} [γυναικος]{.greek-omitted} [της]{.greek-omitted} [μελλουσης]{.greek-omitted} [τεκειν]{.greek-omitted} [ινα]{.greek-omitted} [οταν]{.greek-omitted} [τεκη]{.greek-omitted} [το]{.greek-omitted} [τεκνον]{.greek-omitted} [αυτης]{.greek-omitted} [καταφαγη]{.greek-omitted}[12:4]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [ουρα]{.greek-omitted} [αυτου]{.greek-omitted} [συρει]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [αστερων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [και]{.greek-omitted} [εβαλεν]{.greek-omitted} [αυτους]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} και ο δρακων [εστηκεν]{.greek-omitted} [ἕστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4 | instance no. 2]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον [υπο]{.greek-omitted} [απο]{.greek-added} του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου πολεμησαι μετα του [δρακοντος]{.greek-omitted} [δρακοντοι]{.greek-added} και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και ουκ [ισχυσεν]{.greek-omitted} [ισχυσαν]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} τοπος ευρεθη [αυτω]{.greek-omitted} [αυτων]{.greek-added} ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο [δρακων]{.greek-omitted} [αρχων]{.greek-added} ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και [ο]{.greek-added} σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου [μετ]{.greek-omitted} [αυτου]{.greek-omitted} εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην [λεγουσαν]{.greek-added} εν τω [ουρανω]{.greek-abbr} [λεγουσαν]{.greek-omitted} αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια [του]{.greek-omitted} [αυτου]{.greek-added} [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι [εβληθη]{.greek-omitted} [κατεβληθη]{.greek-added} ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} [ημων]{.greek-omitted} ημερας και νυκτος [η]{.greek-added} [κατηγορια]{.greek-added} [και]{.greek-added} [η]{.greek-added} [διαβολη]{.greek-added} [η]{.greek-added} [κατα]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added}[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

[και]{.greek-added} δια τουτο [ευφραινεσθε]{.greek-omitted} [ευφραινεσθαι]{.greek-added} [οι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν αυτοις [σκηνουντες]{.greek-omitted} [κατοικουντες]{.greek-added} ουαι [τοις]{.greek-added} [κατοικουσι]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [γη]{.greek-omitted} [γην]{.greek-added} και [τη]{.greek-omitted} [την]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσαν]{.greek-added} οτι κατεβη ο διαβολος προς υμας [ο]{.greek-added} εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την [γην]{.greek-omitted} [εδιωξεν]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [ητις]{.greek-omitted} [ετεκεν]{.greek-omitted} [τον]{.greek-omitted} [αρρενα]{.greek-omitted}[12:13]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [ειδεν]{.greek-omitted} [ο]{.greek-omitted} [δρακων]{.greek-omitted} [οτι]{.greek-omitted} [εβληθη]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13 | instance no. 2]{.aside}

και εδοθησαν τη γυναικι [αι]{.greek-added} δυο πτερυγες του αετου του μεγαλου ινα [πετηται]{.greek-omitted} [πεταται]{.greek-added} [εις]{.greek-omitted} [την]{.greek-omitted} [ερημον]{.greek-omitted} εις τον τοπον αυτης [οπως]{.greek-omitted} [οπου]{.greek-added} [τρεφηται]{.greek-omitted} [τρεφεται]{.greek-added} εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις [οπισω]{.greek-added} [της]{.greek-added} [γυναικος]{.greek-added} εκ του στοματος αυτου [οπισω]{.greek-omitted} [της]{.greek-omitted} [γυναικος]{.greek-omitted} υδωρ ως ποταμον [ινα]{.greek-omitted} [αυτην]{.greek-omitted} [ποταμοφορητον]{.greek-omitted} [ποιηση]{.greek-omitted}[12:15]{.aside}

[και]{.greek-omitted} [εβαλεν]{.greek-omitted} [ο]{.greek-omitted} [οφις]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [στοματος]{.greek-omitted} [αυτου]{.greek-omitted} [οπισω]{.greek-omitted} [της]{.greek-omitted} [γυναικος]{.greek-omitted} [υδωρ]{.greek-omitted} [ως]{.greek-omitted} [ποταμον]{.greek-omitted} ινα [αυτην]{.greek-omitted} [ταυτην]{.greek-added} ποταμοφορητον ποιηση[12:15 | instance no. 2]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον [εβαλεν]{.greek-omitted} [εβαλλεν]{.greek-added} ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [του]{.greek-added} [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον [θηριον]{.greek-added} [αναβαινον]{.greek-added} εκ της θαλασσης [θηριον]{.greek-omitted} [αναβαινον]{.greek-omitted} εχον κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου [ονοματα]{.greek-omitted} [ονομα]{.greek-added} βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον [ην]{.greek-omitted} ομοιον παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν [εκ]{.greek-omitted} των κεφαλων αυτου [ωσει]{.greek-omitted} [ως]{.greek-added} [εσφαγμενην]{.greek-omitted} [εσφαγισμενην]{.greek-added} εις θανατον [και]{.greek-omitted} [η]{.greek-omitted} [πληγη]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [αυτου]{.greek-omitted} [εθεραπευθη]{.greek-omitted} [και]{.greek-omitted} [εθαυμασεν]{.greek-omitted} [ολη]{.greek-omitted} [η]{.greek-omitted} [γη]{.greek-omitted} [οπισω]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted}[13:3]{.aside}

και [μιαν]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [κεφαλων]{.greek-omitted} [αυτου]{.greek-omitted} [ωσει]{.greek-omitted} [εσφαγμενην]{.greek-omitted} [εις]{.greek-omitted} [θανατον]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [πληγη]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [αυτου]{.greek-omitted} [εθεραπευθη]{.greek-omitted} [και]{.greek-omitted} [εθαυμασεν]{.greek-omitted} [εθαυμαστη]{.greek-added} [εν]{.greek-added} ολη [η]{.greek-omitted} [τη]{.greek-added} γη οπισω του θηριου[13:3 | instance no. 2]{.aside}

και προσεκυνησαν τω δρακοντι τω δεδωκοτι την εξουσιαν τω θηριω και προσεκυνησαν τω θηριω λεγοντες τις ομοιος τω θηριω και τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και βλασφημιαν και εδοθη αυτω εξουσια πολεμον ποιησαι μηνας τεσσαρακοντα δυο[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου [και]{.greek-added} τους εν [τω]{.greek-omitted} [ουρανω]{.greek-abbr} [σκηνουντας]{.greek-omitted} [οικουντας]{.greek-added}[13:6]{.aside}

[και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [νικησαι]{.greek-omitted} [αυτους]{.greek-omitted} και εδοθη αυτω εξουσια επι πασαν φυλην [και]{.greek-omitted} [λαον]{.greek-omitted} [και]{.greek-omitted} [γλωσσαν]{.greek-omitted} [και]{.greek-omitted} [εθνος]{.greek-omitted}[13:7]{.aside}

[και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [νικησαι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [εξουσια]{.greek-omitted} [επι]{.greek-omitted} [πασαν]{.greek-omitted} [φυλην]{.greek-omitted} [και]{.greek-omitted} [λαον]{.greek-omitted} και γλωσσαν και εθνος [και]{.greek-added} [λαον]{.greek-added}[13:7 | instance no. 2]{.aside}

και προσκυνησουσιν αυτω παντες οι κατοικουντες επι της γης ων ου γεγραπται [το]{.greek-omitted} [τα]{.greek-added} [ονομα]{.greek-omitted} [ονοματα]{.greek-added} εν [τω]{.greek-omitted} [τη]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλω]{.greek-added} της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} αιχμαλωσιαν [υπαγει]{.greek-omitted} [συναγει]{.greek-added} ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτανεῖ]{.greek-added} δει αυτον εν μαχαιρα αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης [εχον]{.greek-added} [και]{.greek-omitted} [ειχεν]{.greek-omitted} κερατα δυο ομοια [αρνιω]{.greek-omitted} [αρνιου]{.greek-added} και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει σημεια μεγαλα [ινα]{.greek-added} και πυρ [ινα]{.greek-omitted} [ποιη]{.greek-added} [καταβαινειν]{.greek-added} εκ του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [ενωπιον]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} επι την γην [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω [ποιειν]{.greek-added} [ενω]{.greek-added} [ποιησαι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θηριου]{.greek-omitted} [λεγων]{.greek-omitted} [τοις]{.greek-omitted} [κατοικουσιν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ποιησαι]{.greek-omitted} [εικονα]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [την]{.greek-omitted} [πληγην]{.greek-omitted} [και]{.greek-omitted} [εζησεν]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

[πιον]{.greek-added} [και]{.greek-omitted} [πλανα]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [τους]{.greek-omitted} [κατοικουντας]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [δια]{.greek-omitted} [τα]{.greek-omitted} [σημεια]{.greek-omitted} [α]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [ποιησαι]{.greek-omitted} [ενωπιον]{.greek-omitted} του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [ὃ]{.greek-added} [εχει]{.greek-added} την πληγην [επι]{.greek-added} [και]{.greek-omitted} [εζησεν]{.greek-omitted} [απο]{.greek-omitted} της μαχαιρας [και]{.greek-added} [εζησε]{.greek-added}[13:14 | instance no. 2]{.aside}

και εδοθη αυτω πνευμα δουναι τη εικονι του θηριου ινα [και]{.greek-omitted} λαληση η εικων του θηριου και ποιηση οσοι [εαν]{.greek-omitted} [αν]{.greek-added} μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [εικονι]{.greek-omitted} [εικονα]{.greek-added} του θηριου [ινα]{.greek-added} [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και [ποιει]{.greek-omitted} παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους [ουαι]{.greek-added} [τοις]{.greek-added} [μελλουσιν]{.greek-added} [ευρεθηναι]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [καιρω]{.greek-added} [εκεινω]{.greek-added} πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} αυτοις [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της χειρος αυτων της δεξιας η επι [το]{.greek-omitted} [μετωπον]{.greek-omitted} [των]{.greek-added} [μετοπων]{.greek-added} αυτων[13:16]{.aside}

[και]{.greek-omitted} ινα μη τις δυναται αγορασαι η πωλησαι ει μη [ο]{.greek-omitted} [η]{.greek-added} εχων το χαραγμα το [ονομα]{.greek-omitted} [ονοματος]{.greek-added} του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων [τον]{.greek-added} νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} εστιν [[χξ]{.greek-abbr}]{.greek-added} και [[στ]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [αριθμος]{.greek-omitted} [αυτου]{.greek-omitted} [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και ειδον και ιδου [το]{.greek-omitted} αρνιον [εστηκος]{.greek-omitted} [εστως]{.greek-added} επι το ορος σιων και μετ αυτου αριθμος εκατον τεσσαρακοντα τεσσαρες χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων [πολων]{.greek-added} [πολλων]{.corr} και ως φωνην βροντης μεγαλης και [η]{.greek-omitted} [φωνη]{.greek-omitted} [φωνην]{.greek-added} [ην]{.greek-omitted} ηκουσα [ως]{.greek-omitted} κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν [ωδην]{.greek-omitted} [ως]{.greek-added} [αυδην]{.greek-added} καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει μη αι εκατον [[μδ]{.greek-abbr}]{.greek-added} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι [εισιν]{.greek-omitted} οι ακολουθουντες τω αρνιω οπου [αν]{.greek-omitted} [υπαγη]{.greek-omitted} [ουτοι]{.greek-omitted} [υπο]{.greek-omitted} [ιησου]{.greek-omitted} [ηγορασθησαν]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [απαρχη]{.greek-omitted} [τω]{.greek-omitted} [θεω]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [αρνιω]{.greek-omitted}[14:4]{.aside}

[ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [μετα]{.greek-omitted} [γυναικων]{.greek-omitted} [ουκ]{.greek-omitted} [εμολυνθησαν]{.greek-omitted} [παρθενοι]{.greek-omitted} [γαρ]{.greek-omitted} [εισιν]{.greek-omitted} [ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [ακολουθουντες]{.greek-omitted} [τω]{.greek-omitted} [αρνιω]{.greek-omitted} [οπου]{.greek-omitted} αν υπαγη ουτοι [ηγορασθησαν]{.greek-added} υπο [ιησου]{.greek-omitted} [ηγορασθησαν]{.greek-omitted} [απο]{.greek-omitted} των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4 | instance no. 2]{.aside}

και [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} εν τω στοματι αυτων [ψευδος]{.greek-omitted} [ουχ]{.greek-added} [ευρεθη]{.greek-added} [δολος]{.greek-added} αμωμοι γαρ εισιν[14:5]{.aside}

και ειδον αγγελον πετομενον εν [μεσουρανηματι]{.greek-omitted} [μεσουρανισματι]{.greek-added} εχοντα ευαγγελιον αιωνιον ευαγγελισαι τους καθημενους [τους]{.greek-added} [κατοικουντας]{.greek-added} επι της γης και [επι]{.greek-omitted} παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} και δοτε [αυτω]{.greek-omitted} δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε [τω]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [ποιησαντι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος δευτερος αγγελος [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων επεσεν [βαβυλων]{.greek-omitted} [επεσεν]{.greek-added} η μεγαλη [βαβυλων]{.greek-added} [οτι]{.greek-added} εκ του οινου του θυμου της πορνειας αυτης [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος [τριτος]{.greek-added} αγγελος [τριτος]{.greek-omitted} ηκολουθησεν αυτοις λεγων εν φωνη μεγαλη ει τις [προσκυνει]{.greek-omitted} το θηριον [προσκυνει]{.greek-added} και την εικονα αυτου και λαμβανει χαραγμα επι του μετωπου αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [κεκερασμενου]{.greek-omitted} [ακρατου]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ποτηριω]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [βασανισθησεται]{.greek-omitted} [εν]{.greek-omitted} [πυρι]{.greek-omitted} [και]{.greek-omitted} [θειω]{.greek-omitted} [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [αγγελων]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted}[14:10]{.aside}

[και]{.greek-omitted} [αυτος]{.greek-omitted} [πιεται]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον [των]{.greek-omitted} [αγγελων]{.greek-added} αγιων [αγγελων]{.greek-omitted} και ενωπιον του αρνιου[14:10 | instance no. 2]{.aside}

και ο καπνος του βασανισμου αυτων εις [αιωνας]{.greek-omitted} [αιωνα]{.greek-added} αιωνων [αναβαινει]{.greek-omitted} [αναβαινων]{.greek-added} και ουκ εχουσιν αναπαυσιν ημερας και [νυ]{.greek-added} [νυκτος]{.greek-omitted} [οι]{.greek-omitted} [προσκυνουντες]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [εικονα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ει]{.greek-omitted} [τις]{.greek-omitted} [λαμβανει]{.greek-omitted} [το]{.greek-omitted} [χαραγμα]{.greek-omitted} [του]{.greek-omitted} [ονοματος]{.greek-omitted} [αυτου]{.greek-omitted}[14:11]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [καπνος]{.greek-omitted} [του]{.greek-omitted} [βασανισμου]{.greek-omitted} [αυτων]{.greek-omitted} [εις]{.greek-omitted} [αιωνας]{.greek-omitted} [αιωνων]{.greek-omitted} [αναβαινει]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [αναπαυσιν]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [νυκτος]{.greek-omitted} [κτος]{.greek-added} οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11 | instance no. 2]{.aside}

ωδε η υπομονη των αγιων εστιν [ωδε]{.greek-added} οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης [μοι]{.greek-added} γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυτων ακολουθει μετ αυτων[14:13]{.aside}

και ειδον και ιδου νεφελη λευκη και επι [την]{.greek-omitted} [τη]{.greek-added} νεφελην [καθημενον]{.greek-omitted} [καθημενος]{.greek-added} [ομοιον]{.greek-omitted} [ομοιος]{.greek-added} [υιω]{.greek-omitted} [υιος]{.greek-added} [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του [ναου]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} [σου]{.greek-added} η ωρα [του]{.greek-added} θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος [αγγελος]{.greek-omitted} εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} [αγγελος]{.greek-added} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και [τρυγησον]{.greek-omitted} [τρυγυσον]{.greek-added} τους βοτρυας της αμπελου της γης οτι ηκμασαν αι σταφυλαι αυτης[14:18]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις [την]{.greek-omitted} [τον]{.greek-added} ληνον του θυμου του [θεου]{.greek-abbr} τον μεγαν[14:19]{.aside}

και [επατηθη]{.greek-omitted} [ετηθη]{.greek-added} [η]{.greek-omitted} [o]{.greek-added} ληνος [εξωθεν]{.greek-omitted} [εξω]{.greek-added} της πολεως και εξηλθεν αιμα εκ της ληνου αχρι [των]{.greek-omitted} [χαλινων]{.greek-omitted} [της]{.greek-added} [χαληνου]{.greek-added} των ιππων απο σταδιων [[αχ´]{.greek-abbr}]{.greek-added} [χιλιων]{.greek-omitted} [εξακοσιων]{.greek-omitted}[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του θεου[15:1]{.aside}

και ειδον ως θαλασσαν [υαλινην]{.greek-omitted} [υελινην]{.greek-added} μεμιγμενην πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την [υαλινην]{.greek-omitted} [υελινην]{.greek-added} εχοντας κιθαρας [του]{.greek-omitted} [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην μωυσεως του δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη φοβηθη [σε]{.greek-omitted} [κυριε]{.greek-abbr} και δοξαση το ονομα σου οτι μονος [αγιος]{.greek-omitted} [οσιος]{.greek-added} οτι παντα τα εθνη [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και [ηνοιγη]{.greek-omitted} [ηνοιγει]{.greek-added} ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας εκ του ναου οι ησαν ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι [περι]{.greek-omitted} [επι]{.greek-added} τα στηθη ζωνας χρυσας[15:6]{.aside}

και [εν]{.greek-omitted} εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου [και]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [εισελθειν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθωσιν]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [πληγαι]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αγγελων]{.greek-omitted}[15:8]{.aside}

[και]{.greek-omitted} [εγεμισθη]{.greek-omitted} [ο]{.greek-omitted} [ναος]{.greek-omitted} [καπνου]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [δοξης]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [αυτου]{.greek-omitted} και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εισελθειν [εις]{.greek-omitted} [τον]{.greek-omitted} [ναον]{.greek-omitted} [εν]{.greek-added} [τω]{.greek-added} [ναω]{.greek-added} αχρι τελεσθωσιν αι επτα [των]{.greek-added} [αγγελων]{.greek-added} πληγαι [των]{.greek-omitted} [επτα]{.greek-omitted} [αγγελων]{.greek-omitted}[15:8 | instance no. 2]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας [επτα]{.greek-omitted} [φιαλας]{.greek-omitted} [φυαλας]{.greek-added} του θυμου του [θεου]{.greek-abbr} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου [εις]{.greek-omitted} [επι]{.greek-added} την γην και εγενετο ελκος κακον και πονηρον επι τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους [την]{.greek-added} [εικονα]{.greek-added} προσκυνουντας [τη]{.greek-omitted} [εικονι]{.greek-omitted} αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο αιμα ως νεκρου και πασα ψυχη ζωσα απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και εις τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην [ο]{.greek-omitted} [και]{.greek-added} οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν αξιοι εισιν[16:6]{.aside}

και ηκουσα [εκ]{.greek-added} του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [καυματισαι]{.greek-omitted} [εν]{.greek-omitted} [πυρι]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted}[16:8]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} [αγγελος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [ηλιον]{.greek-omitted} [και]{.greek-omitted} εδοθη αυτω [καυματισαι]{.greek-omitted} [καυματησαι]{.greek-added} εν πυρι τους [ανθρωπους]{.greek-abbr}[16:8 | instance no. 2]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και [ου]{.greek-omitted} [ουκ]{.greek-added} [μετενοησαν]{.greek-omitted} [εμετενοησαν]{.greek-added} δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και εμασωντο τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ [των]{.greek-omitted} [πονων]{.greek-omitted} [του]{.greek-added} [πονου]{.greek-added} αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο εκτος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ποταμον τον μεγαν [τον]{.greek-added} ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο [α]{.greek-added} [ανατολης]{.greek-omitted} [ηλιου]{.greek-omitted}[16:12]{.aside}

[νατολων]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [εξεχεεν]{.greek-omitted} [την]{.greek-omitted} [φιαλην]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [ποταμον]{.greek-omitted} [τον]{.greek-omitted} [μεγαν]{.greek-omitted} [ευφρατην]{.greek-omitted} [και]{.greek-omitted} [εξηρανθη]{.greek-omitted} [το]{.greek-omitted} [υδωρ]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [ετοιμασθη]{.greek-omitted} [η]{.greek-omitted} [οδος]{.greek-omitted} [των]{.greek-omitted} [βασιλεων]{.greek-omitted} [των]{.greek-omitted} [απο]{.greek-omitted} [ανατολης]{.greek-omitted} ηλιου[16:12 | instance no. 2]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα ακαθαρτα [τρια]{.greek-omitted} ως βατραχοι[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ πνευματα [δαιμονιων]{.greek-omitted} [δαιμονων]{.greek-added} ποιουντα σημεια [α]{.greek-omitted} [εκπορευεται]{.greek-omitted} [εκπορευεσθαι]{.greek-added} επι τους βασιλεις [της]{.greek-added} [γης]{.greek-added} της οικουμενης ολης συναγαγειν αυτους εις [τον]{.greek-omitted} πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπουσι]{.greek-added} την [ασχημοσυνην]{.greek-omitted} [αισχυνην]{.greek-added} αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις [τον]{.greek-omitted} τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἀρμεγεδών]{.greek-added} [ἀρμαγεδδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την [φιαλην]{.greek-omitted} [φιαλιν]{.greek-added} αυτου [επι]{.greek-omitted} [εις]{.greek-added} τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη μεγαλη [εκ]{.greek-added} [απο]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[16:17]{.aside}

και εγενοντο [αστραπαι]{.greek-omitted} [φωναι]{.greek-added} και βρονται και [φωναι]{.greek-omitted} [αστραπαι]{.greek-added} και σεισμος [εγενετο]{.greek-added} μεγας οιος ουκ εγενετο αφ ου οι [ανθρωποι]{.greek-abbr} [εγενοντο]{.greek-omitted} [εγενετο]{.greek-added} επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων επεσον [και]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εμνησθη]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [δουναι]{.greek-omitted} [αυτη]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [αυτου]{.greek-omitted}[16:19]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εις]{.greek-omitted} [τρια]{.greek-omitted} [μερη]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [πολεις]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted} [επεσον]{.greek-omitted} και βαβυλων η μεγαλη εμνησθη ενωπιον [του]{.greek-omitted} [θεου]{.greek-omitted} [δουναι]{.greek-omitted} [αυτη]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [οργης]{.greek-omitted} [αυτου]{.greek-omitted}[16:19 | instance no. 2]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εις]{.greek-omitted} [τρια]{.greek-omitted} [μερη]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [πολεις]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted} [επεσον]{.greek-omitted} [και]{.greek-omitted} [βαβυλων]{.greek-omitted} [η]{.greek-omitted} [μεγαλη]{.greek-omitted} [εμνησθη]{.greek-omitted} [ενωπιον]{.greek-omitted} του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19 | instance no. 3]{.aside}

και πασα νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια [καταβαινει]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [και]{.greek-omitted} [εβλασφημησαν]{.greek-omitted} [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [πληγης]{.greek-omitted} [της]{.greek-omitted} [χαλαζης]{.greek-omitted} [οτι]{.greek-omitted} [μεγαλη]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [πληγη]{.greek-omitted} [αυτης]{.greek-omitted} [σφοδρα]{.greek-omitted}[16:21]{.aside}

[και]{.greek-omitted} [χαλαζα]{.greek-omitted} [μεγαλη]{.greek-omitted} [ως]{.greek-omitted} [ταλαντιαια]{.greek-omitted} καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21 | instance no. 2]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων [μοι]{.greek-added} δευρο δειξω σοι το κριμα της πορνης της μεγαλης της [καθημενης]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [υδατων]{.greek-omitted} [των]{.greek-omitted} [πολλων]{.greek-omitted}[17:1]{.aside}

[και]{.greek-omitted} [ηλθεν]{.greek-omitted} [εις]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [επτα]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [εχοντων]{.greek-omitted} [τας]{.greek-omitted} [επτα]{.greek-omitted} [φιαλας]{.greek-omitted} [και]{.greek-omitted} [ελαλησεν]{.greek-omitted} [μετ]{.greek-omitted} [εμου]{.greek-omitted} [λεγων]{.greek-omitted} [δευρο]{.greek-omitted} [δειξω]{.greek-omitted} [σοι]{.greek-omitted} [το]{.greek-omitted} [κριμα]{.greek-omitted} [της]{.greek-omitted} [πορνης]{.greek-omitted} [της]{.greek-omitted} [μεγαλης]{.greek-omitted} [της]{.greek-omitted} καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1 | instance no. 2]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν [οι]{.greek-omitted} [κατοικουντες]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} εκ του οινου της πορνειας αυτης [οι]{.greek-added} [κατοικουντες]{.greek-added} [την]{.greek-added} [γην]{.greek-added}[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον [εν]{.greek-omitted} [τω]{.greek-added} [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον κοκκινον γεμον ονοματα βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [ην]{.greek-omitted} [περιβεβλημενη]{.greek-omitted} [πορφυρουν]{.greek-omitted} [και]{.greek-omitted} [κοκκινον]{.greek-omitted} [κεχρυσωμενη]{.greek-omitted} [χρυσιω]{.greek-omitted} [και]{.greek-omitted} [λιθω]{.greek-omitted} [τιμιω]{.greek-omitted} [και]{.greek-omitted} [μαργαριταις]{.greek-omitted} [εχουσα]{.greek-omitted} [ποτηριον]{.greek-omitted} [χρυσουν]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [χειρι]{.greek-omitted} [αυτης]{.greek-omitted} [γεμον]{.greek-omitted} βδελυγματων και τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα [την]{.greek-added} μεθυουσαν εκ του αιματος των αγιων [και]{.greek-added} εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος δια τι εθαυμασας εγω [σοι]{.greek-added} ερω [σοι]{.greek-omitted} το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν [αει]{.greek-added} [ζητουν]{.greek-added} [τινα]{.greek-added} [καταπιη]{.greek-added} [και]{.greek-omitted} [θαυμασονται]{.greek-omitted} [οι]{.greek-omitted} [κατοικουντες]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [ων]{.greek-omitted} [ου]{.greek-omitted} [γεγραπται]{.greek-omitted} [τα]{.greek-omitted} [ονοματα]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [βιβλιον]{.greek-omitted} [της]{.greek-omitted} [ζωης]{.greek-omitted} [απο]{.greek-omitted} [καταβολης]{.greek-omitted} [κοσμου]{.greek-omitted} [βλεποντων]{.greek-omitted} [οτι]{.greek-omitted} [ην]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [παρεσται]{.greek-omitted}[17:8]{.aside}

[το]{.greek-omitted} [θηριον]{.greek-omitted} [ο]{.greek-omitted} [ειδες]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [εστιν]{.greek-omitted} [και]{.greek-omitted} [μελλει]{.greek-omitted} [αναβαινειν]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [απωλειαν]{.greek-omitted} [υπαγειν]{.greek-omitted} και θαυμασονται οι κατοικουντες [την]{.greek-added} [γην]{.greek-added} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} ων ου γεγραπται τα ονοματα επι το βιβλιον της ζωης απο καταβολης κοσμου [βλεποντων]{.greek-omitted} [βλεποντες]{.greek-added} οτι ην το θηριον και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και παρεσται[17:8 | instance no. 2]{.aside}

ωδε ο νους ο εχων [την]{.greek-added} σοφιαν αι επτα κεφαλαι [επτα]{.greek-omitted} ορη εισιν [επτα]{.greek-added} οπου [η]{.greek-omitted} [γυνη]{.greek-omitted} [καθηται]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted}[17:9]{.aside}

[ωδε]{.greek-omitted} [ο]{.greek-omitted} [νους]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [σοφιαν]{.greek-omitted} [αι]{.greek-omitted} [επτα]{.greek-omitted} [κεφαλαι]{.greek-omitted} [επτα]{.greek-omitted} [ορη]{.greek-omitted} [εισιν]{.greek-omitted} [οπου]{.greek-omitted} η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [επτα]{.greek-added} [εισιν]{.greek-added}[17:9 | instance no. 2]{.aside}

[ωδε]{.greek-omitted} [ο]{.greek-omitted} [νους]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} [σοφιαν]{.greek-omitted} [αι]{.greek-omitted} [και]{.greek-added} [βασιλεις]{.greek-added} επτα [κεφαλαι]{.greek-omitted} [επτα]{.greek-omitted} [ορη]{.greek-omitted} εισιν [οπου]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [καθηται]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted}[17:9 | instance no. 3]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ο εις [εστιν]{.greek-omitted} [εστι]{.greek-added} [και]{.greek-added} ο αλλος ουπω [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και οταν ελθη ολιγον [αυτον]{.greek-added} δει [αυτον]{.greek-omitted} μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και αυτος ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} και εκ των επτα [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} γνωμην [εχουσι]{.greek-added} και την δυναμιν και την εξουσιαν αυτων τω θηριω [διδοασιν]{.greek-omitted} [δεδωκασιν]{.greek-added}[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και [ηρημωμενην]{.greek-omitted} [ηρημομενην]{.greek-added} ποιησουσιν αυτην και γυμνην [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} και τας σαρκας αυτης φαγονται και αυτην [κατακαυσουσιν]{.greek-omitted} [καυσουσιν]{.greek-added} εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και [ποιησαι]{.greek-omitted} [γνωμην]{.greek-omitted} μιαν [γνωμη]{.greek-added} [ποιησουσι]{.greek-added} και δουναι την βασιλειαν αυτων τω θηριω αχρι τελεσθωσιν οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν ισχυρα φωνη [μεγαλη]{.greek-added} λεγων επεσεν [επεσε]{.greek-added} βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος πνευματος ακαθαρτου και φυλακη παντος ορνεου ακαθαρτου και μεμισημενου[18:2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκε]{.greek-added} παντα τα εθνη [και]{.greek-omitted} [οι]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [μετ]{.greek-omitted} [αυτης]{.greek-omitted} [επορνευσαν]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [εμποροι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [εκ]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [του]{.greek-omitted} [στρηνους]{.greek-omitted} [αυτης]{.greek-omitted} [επλουτησαν]{.greek-omitted}[18:3]{.aside}

[οτι]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [οινου]{.greek-omitted} [του]{.greek-omitted} [θυμου]{.greek-omitted} [της]{.greek-omitted} [πορνειας]{.greek-omitted} [αυτης]{.greek-omitted} [πεπτωκασιν]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι [της]{.greek-omitted} [αυτης]{.greek-added} [γης]{.greek-omitted} εκ της δυναμεως του [στρηνους]{.greek-omitted} [στρηνου]{.greek-added} αυτης επλουτησαν[18:3 | instance no. 2]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν [εξελθε]{.greek-omitted} [εξελθετε]{.greek-added} εξ αυτης ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν [αυτης]{.greek-omitted} αι αμαρτιαι [αυτης]{.greek-added} αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν [υμιν]{.greek-added} και διπλωσατε αυτη διπλα κατα τα εργα αυτης εν τω ποτηριω ω [εκερασεν]{.greek-omitted} [εκερασε]{.greek-added} κερασατε αυτη διπλουν[18:6]{.aside}

[οσα]{.greek-omitted} [οσον]{.greek-added} εδοξασεν αυτην και [εστρηνιασεν]{.greek-omitted} [εστρηνιασε]{.greek-added} τοσουτον δοτε αυτη βασανισμον και πενθος [οτι]{.greek-omitted} [και]{.greek-added} εν τη καρδια αυτης λεγει [οτι]{.greek-omitted} καθημαι βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο [κρινας]{.greek-omitted} [κρινων]{.greek-added} αυτην[18:8]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσονται]{.greek-added} [αυτην]{.greek-added} και κοψονται [ε]{.greek-added} επ [αυτην]{.greek-omitted} [αυτη]{.greek-added} οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον [καπνον]{.greek-omitted} [καρπον]{.greek-added} της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του βασανισμου αυτης λεγοντες ουαι ουαι η πολις η μεγαλη βαβυλων η πολις η ισχυρα οτι [εν]{.greek-added} μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαιουσι]{.greek-added} και [πενθησουσιν]{.greek-omitted} [πενθουσιν]{.greek-added} [επ]{.greek-omitted} [αυτη]{.greek-omitted} [εφ]{.greek-added} [εαυτοις]{.greek-added} οτι τον γομον αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου [και]{.greek-omitted} [ουτε]{.greek-added} μαργαριτου και [βυσσινου]{.greek-omitted} [βυσσου]{.greek-added} και πορφυρου και [σηρικου]{.greek-omitted} [κοκκινου]{.greek-added} και [κοκκινου]{.greek-omitted} [συρικου]{.greek-added} και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και κιναμωμον και [θυμιαματα]{.greek-omitted} [θυμιαμα]{.greek-added} και μυρον και λιβανον και οινον και ελαιον και σεμιδαλιν και σιτον και [προβατα]{.greek-omitted} [και]{.greek-omitted} κτηνη και [ιππων]{.greek-omitted} [προβατα]{.greek-added} [ω]{.greek-added} [της]{.greek-added} [αισχυνης]{.greek-added} [οτι]{.greek-added} [τα]{.greek-added} [δουνατην]{.greek-added} [ημιν]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [βιω]{.greek-added} [ως]{.greek-added} [επι]{.greek-added} [δοξα]{.greek-added} [καιπερ]{.greek-added} [πνα]{.greek-added} και [ραιδων]{.greek-omitted} [ευωδη]{.greek-added} και [σωματων]{.greek-omitted} [δια]{.greek-added} [τουτο]{.greek-added} και [ψυχας]{.greek-omitted} [ανθρωπων]{.greek-omitted} [περισπου]{.greek-added} [δασταδηθεν]{.greek-added} [ημιν]{.greek-added} [τε]{.greek-added} [και]{.greek-added} [περιμαχητα]{.greek-added} [ινα]{.greek-added} [την]{.greek-added} [σαρην]{.greek-added} [τουτοις]{.greek-added} [κοσμησωμεν]{.greek-added} [ταυτα]{.greek-added} [τοις]{.greek-added} [φονησασιν]{.greek-added} [αληθεν]{.greek-added} [ως]{.greek-added} [κατα]{.greek-added} [πτυστα]{.greek-added} [μαλλον]{.greek-added} [διασυρεται]{.greek-added} [και]{.greek-added} [δυσωδη]{.greek-added} [και]{.greek-added} [εις]{.greek-added} [ελεγχον]{.greek-added} [ημων]{.greek-added} [ονει]{.greek-added} [διζεται]{.greek-added}[18:13]{.aside}

[και]{.greek-omitted} [κιναμωμον]{.greek-omitted} [και]{.greek-omitted} [θυμιαματα]{.greek-omitted} [και]{.greek-omitted} [μυρον]{.greek-omitted} [και]{.greek-omitted} [λιβανον]{.greek-omitted} [και]{.greek-omitted} [οινον]{.greek-omitted} [και]{.greek-omitted} [ελαιον]{.greek-omitted} [και]{.greek-omitted} [σεμιδαλιν]{.greek-omitted} [και]{.greek-omitted} [σιτον]{.greek-omitted} [και]{.greek-omitted} [προβατα]{.greek-omitted} [και]{.greek-omitted} [κτηνη]{.greek-omitted} και ιππων και [ραιδων]{.greek-omitted} [ρεδων]{.greek-added} και σωματων [και]{.greek-omitted} [ψυχας]{.greek-omitted} [ανθρωπων]{.greek-omitted}[18:13 | instance no. 2]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα [απωλετο]{.greek-omitted} [απηλθεν]{.greek-added} απο σου και ουκετι [αυτα]{.greek-omitted} ου μη [ευρης]{.greek-omitted} [ευρησεις]{.greek-added} [αυτα]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες [απ]{.greek-omitted} [εξ]{.greek-added} αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15]{.aside}

και λεγοντες ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και πορφυρουν και κοκκινον [και]{.greek-omitted} κεχρυσωμενη [εν]{.greek-added} χρυσιω και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος [και]{.greek-omitted} [πας]{.greek-omitted} [κυβερνητης]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [επι]{.greek-omitted} [τοπον]{.greek-omitted} [πλεων]{.greek-omitted} [και]{.greek-omitted} [ναυται]{.greek-omitted} [και]{.greek-omitted} [οσοι]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [εργαζονται]{.greek-omitted} [απο]{.greek-omitted} [μακροθεν]{.greek-omitted} [εστησαν]{.greek-omitted}[18:17]{.aside}

[οτι]{.greek-omitted} [μια]{.greek-omitted} [ωρα]{.greek-omitted} [ηρημωθη]{.greek-omitted} [ο]{.greek-omitted} [τοσουτος]{.greek-omitted} [πλουτος]{.greek-omitted} και πας [κυβερνητης]{.greek-omitted} [κυβερνιτης]{.greek-added} και πας [ο]{.greek-omitted} επι [τοπον]{.greek-omitted} [πλεων]{.greek-omitted} [των]{.greek-added} [πλοιων]{.greek-added} [ομιλος]{.greek-added} και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17 | instance no. 2]{.aside}

και εκραζον [βλεποντες]{.greek-omitted} [ορωντες]{.greek-added} τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη πολει τη μεγαλη[18:18]{.aside}

και εβαλον χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες και λεγοντες ουαι ουαι η πολις η μεγαλη εν η επλουτησαν παντες οι εχοντες τα πλοια εν τη θαλασση εκ της τιμιοτητος αυτης οτι [εν]{.greek-added} μια ωρα [ηρημωθη]{.greek-omitted} [ερημωθη]{.greek-added}[18:19]{.aside}

ευφραινου επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} [ουρανε]{.greek-abbr} και οι αγιοι [και]{.greek-omitted} [οι]{.greek-omitted} αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και [σαλπιστων]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [τεχνιτης]{.greek-omitted} [πασης]{.greek-omitted} [τεχνης]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22]{.aside}

[και]{.greek-omitted} [φωνη]{.greek-omitted} [κιθαρωδων]{.greek-omitted} [και]{.greek-omitted} [μουσικων]{.greek-omitted} [και]{.greek-omitted} [αυλητων]{.greek-omitted} [και]{.greek-omitted} σαλπιστων ου μη ακουσθη εν σοι ετι και πας τεχνιτης πασης τεχνης ου μη ευρεθη εν σοι ετι [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22 | instance no. 2]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [ευρεθη]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη [ακουσθη]{.greek-omitted} [ευρεθη]{.greek-added} εν σοι ετι οτι οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν τη [φαρμακεια]{.greek-omitted} [φαρμακια]{.greek-added} σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων ευρεθη και παντων των [εσφαγμενων]{.greek-omitted} [εσφαγισμενων]{.greek-added} επι της γης[18:24]{.aside}

### Chapter 19

[και]{.greek-added} μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην [μεγαλην]{.greek-omitted} οχλου πολλου εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δοξα]{.greek-added} και η [δοξα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τιμη]{.greek-added} [και]{.greek-added} [η]{.greek-added} [δυναμις]{.greek-added} [[κυριω]{.greek-abbr}]{.greek-added} [τω]{.greek-added} [[θεω]{.greek-abbr}]{.greek-added} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [εφθειρε]{.greek-added} την γην εν τη πορνεια αυτης [και]{.greek-omitted} [εξεδικησεν]{.greek-omitted} [το]{.greek-omitted} [αιμα]{.greek-omitted} [των]{.greek-omitted} [δουλων]{.greek-omitted} [αυτου]{.greek-omitted} [εκ]{.greek-omitted} [χειρος]{.greek-omitted} [αυτης]{.greek-omitted}[19:2]{.aside}

[οτι]{.greek-omitted} [αληθιναι]{.greek-omitted} και [δικαιαι]{.greek-omitted} [αι]{.greek-omitted} [κρισεις]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [εκρινεν]{.greek-omitted} [την]{.greek-omitted} [πορνην]{.greek-omitted} [την]{.greek-omitted} [μεγαλην]{.greek-omitted} [ητις]{.greek-omitted} [διεφθειρεν]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πορνεια]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ [της]{.greek-added} χειρος αυτης[19:2 | instance no. 2]{.aside}

και δευτερον [ειρηκεν]{.greek-omitted} [ειρηκαν]{.greek-added} αλληλουια και ο καπνος αυτης αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι πρεσβυτεροι οι εικοσι τεσσαρες και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη [απο]{.greek-omitted} [εκ]{.greek-added} του θρονου εξηλθεν [λεγουσα]{.greek-omitted} αινειτε τον [θεον]{.greek-abbr} ημων [λεγουσα]{.greek-added} παντες οι δουλοι αυτου και οι φοβουμενοι αυτον [και]{.greek-added} οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα [ως]{.greek-omitted} φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντων]{.greek-added} αλληλουια οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και αγαλλιωμεθα και δωμεν την δοξαν [αυτω]{.greek-omitted} [αυτου]{.greek-added} οτι ηλθεν ο γαμος του αρνιου [και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [αυτου]{.greek-omitted} [ητοιμασεν]{.greek-omitted} [εαυτην]{.greek-omitted}[19:7]{.aside}

[χαιρωμεν]{.greek-omitted} [και]{.greek-omitted} [αγαλλιωμεθα]{.greek-omitted} [και]{.greek-omitted} [δωμεν]{.greek-omitted} [την]{.greek-omitted} [δοξαν]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [ηλθεν]{.greek-omitted} [ο]{.greek-omitted} [γαμος]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} και η γυνη αυτου ητοιμασεν [εαυτην]{.greek-omitted} [αυτην]{.greek-added}[19:7 | instance no. 2]{.aside}

και εδοθη αυτη ινα [περιβαληται]{.greek-omitted} [περιβαλληται]{.greek-added} βυσσινον [καθαρον]{.greek-added} [και]{.greek-added} λαμπρον [και]{.greek-omitted} [καθαρον]{.greek-omitted} το γαρ βυσσινον τα δικαιωματα [εστι]{.greek-added} των αγιων [εστιν]{.greek-omitted}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις το δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι [αληθινοι]{.greek-omitted} [αληθηνοι]{.greek-added} [εισι]{.greek-added} του [θεου]{.greek-abbr} [εισιν]{.greek-omitted}[19:9]{.aside}

και επεσα εμπροσθεν των ποδων αυτου προσκυνησαι αυτω και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια [του]{.greek-omitted} [ιησου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον [καλουμενος]{.greek-omitted} πιστος και αληθινος [καλουμενος]{.greek-added} και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου [ως]{.greek-added} φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα [εχων]{.greek-omitted} [ονοματα]{.greek-omitted} [γεγραμμενα]{.greek-omitted} [και]{.greek-omitted} [ονομα]{.greek-omitted} [γεγραμμενον]{.greek-omitted} [ο]{.greek-omitted} [ουδεις]{.greek-omitted} [οιδεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [αυτος]{.greek-omitted}[19:12]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [οφθαλμοι]{.greek-omitted} [αυτου]{.greek-omitted} [φλοξ]{.greek-omitted} [πυρος]{.greek-omitted} [και]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [αυτου]{.greek-omitted} [διαδηματα]{.greek-omitted} [πολλα]{.greek-omitted} εχων ονοματα γεγραμμενα και ονομα γεγραμμενον ο ουδεις οιδεν ει μη αυτος[19:12 | instance no. 2]{.aside}

και περιβεβλημενος ιματιον [βεβαμμενον]{.greek-omitted} [βεβαμενον]{.greek-added} αιματι και [καλειται]{.greek-omitted} [καλεται]{.greek-added} το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα [τα]{.greek-omitted} εν τω [ουρανω]{.greek-abbr} ηκολουθει αυτω [επι]{.greek-omitted} [εφ]{.greek-added} ιπποις λευκοις ενδεδυμενοι βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος πατει [την]{.greek-omitted} [τον]{.greek-added} ληνον του οινου του θυμου [και]{.greek-added} της οργης του [θεου]{.greek-abbr} [του]{.greek-omitted} παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και [επι]{.greek-omitted} τον μηρον αυτου [το]{.greek-added} ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον [ενα]{.greek-added} αγγελον εστωτα εν τω ηλιω και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις [τοις]{.greek-omitted} πετομενοις εν [μεσουρανηματι]{.greek-omitted} [μεσουρανισματι]{.greek-added} δευτε συναχθητε εις το δειπνον [το]{.greek-omitted} [μεγα]{.greek-omitted} του [μεγαλου]{.greek-added} [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων [και]{.greek-omitted} [σαρκας]{.greek-omitted} [χιλιαρχων]{.greek-omitted} [και]{.greek-omitted} [σαρκας]{.greek-omitted} [ισχυρων]{.greek-omitted} [και]{.greek-omitted} [σαρκας]{.greek-omitted} [ιππων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [καθημενων]{.greek-omitted} [επ]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [σαρκας]{.greek-omitted} [παντων]{.greek-omitted} [ελευθερων]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [δουλων]{.greek-omitted} [και]{.greek-omitted} [μικρων]{.greek-omitted} [τε]{.greek-omitted} [και]{.greek-omitted} [μεγαλων]{.greek-omitted}[19:18]{.aside}

[ινα]{.greek-omitted} [φαγητε]{.greek-omitted} [σαρκας]{.greek-omitted} [βασιλεων]{.greek-omitted} και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας [παντων]{.greek-omitted} ελευθερων [τε]{.greek-omitted} και δουλων και μικρων [τε]{.greek-omitted} και μεγαλων[19:18 | instance no. 2]{.aside}

και ειδον το θηριον και τους βασιλεις της γης [και]{.greek-omitted} [τα]{.greek-omitted} [στρατευματα]{.greek-omitted} [αυτων]{.greek-omitted} [συνηγμενα]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [ιππου]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [στρατευματος]{.greek-omitted} [αυτου]{.greek-omitted}[19:19]{.aside}

[και]{.greek-omitted} [ειδον]{.greek-omitted} [το]{.greek-omitted} [θηριον]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} και τα στρατευματα αυτων συνηγμενα ποιησαι πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19 | instance no. 2]{.aside}

και επιασθη το θηριον και [ο]{.greek-omitted} μετ αυτου [ο]{.greek-added} ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες [εβληθησαν]{.greek-omitted} [βληθησονται]{.greek-added} οι δυο εις την λιμνην του πυρος [την]{.greek-omitted} [της]{.greek-added} [καιομενην]{.greek-omitted} [καιομενης]{.greek-added} εν [τω]{.greek-added} θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την [κλειν]{.greek-omitted} [κλειδα]{.greek-added} της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και [ο]{.greek-omitted} σατανας [ο]{.greek-omitted} [πλανων]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} [ολην]{.greek-omitted} και εδησεν αυτον χιλια ετη[20:2]{.aside}

και εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλεισε]{.greek-added} και εσφραγισεν επανω αυτου ινα μη πλανα ετι τα εθνη αχρι τελεσθη [τα]{.greek-omitted} χιλια ετη και μετα ταυτα [δει]{.greek-omitted} [αυτον]{.greek-omitted} [λυθηναι]{.greek-omitted} [μικρον]{.greek-omitted} [χρονον]{.greek-omitted}[20:3]{.aside}

[και]{.greek-omitted} [εβαλεν]{.greek-omitted} [αυτον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [αβυσσον]{.greek-omitted} [και]{.greek-omitted} [εκλεισεν]{.greek-omitted} [και]{.greek-omitted} [εσφραγισεν]{.greek-omitted} [επανω]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [πλανα]{.greek-omitted} [ετι]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθη]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} [και]{.greek-omitted} [μετα]{.greek-omitted} [ταυτα]{.greek-omitted} δει αυτον λυθηναι μικρον χρονον[20:3 | instance no. 2]{.aside}

και ειδον θρονους και εκαθισαν επ αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [του]{.greek-added} [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν [το]{.greek-omitted} [θηριον]{.greek-omitted} [τω]{.greek-added} [θυσιαστηριω]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [εικονα]{.greek-omitted} [εικονι]{.greek-added} αυτου και ουκ ελαβον το χαραγμα επι το μετωπον [αυτων]{.greek-added} και επι την χειρα αυτων και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} [τα]{.greek-omitted} χιλια ετη[20:4]{.aside}

και οι λοιποι των νεκρων ουκ [εζησαν]{.greek-omitted} [ανεστησαν]{.greek-added} αχρι τελεσθη τα χιλια ετη αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων [μερος]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [αναστασει]{.greek-omitted} [τη]{.greek-omitted} [πρωτη]{.greek-omitted} [επι]{.greek-omitted} [τουτων]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [θανατος]{.greek-omitted} [ουκ]{.greek-omitted} [εχει]{.greek-omitted} [εξουσιαν]{.greek-omitted} [αλλ]{.greek-omitted} [εσονται]{.greek-omitted} [ιερεις]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [χριστου]{.greek-omitted} [και]{.greek-omitted} [βασιλευσουσιν]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted}[20:6]{.aside}

[μακαριος]{.greek-omitted} [και]{.greek-omitted} [αγιος]{.greek-omitted} [ο]{.greek-omitted} [εχων]{.greek-omitted} μερος εν τη αναστασει τη πρωτη επι τουτων ο δευτερος θανατος ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου [τα]{.greek-added} χιλια ετη[20:6 | instance no. 2]{.aside}

και [οταν]{.greek-omitted} [οτε]{.greek-added} [τελεσθη]{.greek-omitted} [ετελεσθησαν]{.greek-added} τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης τον γωγ και [τον]{.greek-omitted} μαγωγ συναγαγειν αυτους εις [τον]{.greek-omitted} πολεμον ων ο αριθμος [ωσει]{.greek-added} [ως]{.greek-omitted} [η]{.greek-omitted} αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και εκυκλωσαν την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη [πυρ]{.greek-omitted} εκ του [ουρανου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} [πυρ]{.greek-added} απο του [θεου]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και θειου οπου [και]{.greek-omitted} το θηριον και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10]{.aside}

και ειδον θρονον [λευκον]{.greek-added} μεγαν [λευκον]{.greek-omitted} και τον καθημενον επ αυτον ου απο προσωπου εφυγεν η γη και ο [ουρανος]{.greek-abbr} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον τους νεκρους τους μεγαλους και τους μικρους εστωτας ενωπιον του θρονου [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} και βιβλια ηνεωχθησαν και αλλο βιβλιον [ηνεωχθη]{.greek-omitted} [ηνοιχθη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους [εαυτης]{.greek-added} νεκρους [τους]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αδης]{.greek-omitted} [εδωκαν]{.greek-omitted} [τους]{.greek-omitted} [νεκρους]{.greek-omitted} [τους]{.greek-omitted} [εν]{.greek-omitted} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [εκριθησαν]{.greek-omitted} [εκαστος]{.greek-omitted} [κατα]{.greek-omitted} [τα]{.greek-omitted} [εργα]{.greek-omitted} [αυτων]{.greek-omitted}[20:13]{.aside}

[και]{.greek-omitted} [εδωκεν]{.greek-omitted} [η]{.greek-omitted} [θαλασσα]{.greek-omitted} [τους]{.greek-omitted} [νεκρους]{.greek-omitted} [τους]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} και ο θανατος και ο αδης εδωκαν τους [νεκρους]{.greek-omitted} [τους]{.greek-omitted} εν αυτοις [νεκρους]{.greek-added} και εκριθησαν εκαστος κατα τα εργα αυτων[20:13 | instance no. 2]{.aside}

και ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος ουτος ο θανατος ο δευτερος εστιν η λιμνη του πυρος[20:14]{.aside}

και ει τις ουχ ευρεθη [εν]{.greek-omitted} [τω]{.greek-omitted} [βιβλιω]{.greek-omitted} [εις]{.greek-added} [την]{.greek-added} [βιβλον]{.greek-added} της ζωης [γεγραμμενος]{.greek-omitted} [εγγεγραμμενος]{.greek-added} εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη [απηλθον]{.greek-omitted} [παρηλθε]{.greek-added} και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν [απο]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} ητοιμασμενην ως νυμφην κεκοσμημενην τω ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι [λαος]{.greek-omitted} [λαοι]{.greek-added} αυτου εσονται και αυτος ο [θεος]{.greek-abbr} εσται μετ αυτων[21:3]{.aside}

και εξαλειψει [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} παν δακρυον απο των οφθαλμων αυτων και ο θανατος ουκ εσται ετι ουτε πενθος ουτε κραυγη ουτε πονος ουκ [ε]{.greek-added} [εσται]{.greek-omitted} [ετι]{.greek-omitted} [οτι]{.greek-omitted} [τα]{.greek-omitted} [πρωτα]{.greek-omitted} [απηλθον]{.greek-omitted}[21:4]{.aside}

[και]{.greek-omitted} [εξαλειψει]{.greek-omitted} [παν]{.greek-omitted} [δακρυον]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [οφθαλμων]{.greek-omitted} [αυτων]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} [σται]{.greek-added} [ετι]{.greek-omitted} [ουτε]{.greek-omitted} [πενθος]{.greek-omitted} [ουτε]{.greek-omitted} [κραυγη]{.greek-omitted} [ουτε]{.greek-omitted} [πονος]{.greek-omitted} [ουκ]{.greek-omitted} [εσται]{.greek-omitted} ετι οτι τα πρωτα απηλθον[21:4 | instance no. 2]{.aside}

και ειπεν ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} ιδου [καινα]{.greek-added} παντα [καινα]{.greek-omitted} ποιω και λεγει μοι γραψον οτι [ουτοι]{.greek-omitted} οι λογοι [ουτοι]{.greek-added} αληθινοι και πιστοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[21:5]{.aside}

και ειπεν μοι [γεγονα]{.greek-omitted} [γεγονε]{.greek-added} το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} [και]{.greek-added} η αρχη και το τελος εγω τω διψωντι δωσω εκ της πηγης του υδατος της ζωης δωρεαν[21:6]{.aside}

ο νικων κληρονομησει [ταυτα]{.greek-omitted} [παντα]{.greek-added} και εσομαι αυτω [θεος]{.greek-abbr} και [αυτος]{.greek-omitted} [αυτοι]{.greek-added} [εσται]{.greek-omitted} [εσονται]{.greek-added} μοι [υιος]{.greek-omitted} [υιοι]{.greek-added}[21:7]{.aside}

[τοις]{.greek-omitted} [δειλοις]{.greek-added} δε [δειλοις]{.greek-omitted} και απιστοις και αμαρτωλοις και εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευσι]{.greek-added} και πορνοις και φαρμακοις και ειδωλολατραις και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν τη λιμνη τη καιομενη πυρι και θειω [ο]{.greek-omitted} [εστιν]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted}[21:8]{.aside}

και ηλθεν εις [εκ]{.greek-omitted} των επτα αγγελων των εχοντων τας επτα φιαλας [τας]{.greek-added} γεμουσας των επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την [γυναικα]{.greek-omitted} [την]{.greek-omitted} νυμφην του αρνιου [την]{.greek-added} [γυναικα]{.greek-added}[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εν [πνευματι]{.greek-abbr} επ ορος μεγα και υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι την πολιν την μεγαλην [την]{.greek-omitted} [και]{.greek-added} αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr}[21:10]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} [και]{.greek-added} ο φωστηρ αυτης ομοιος λιθω τιμιωτατω ως λιθω ιασπιδι [κρυσταλλιζοντι]{.greek-omitted} [κρυσταλιζοντι]{.greek-added}[21:11]{.aside}

[εχουσα]{.greek-omitted} [εχουσατε]{.greek-added} τειχος μεγα και υψηλον εχουσα πυλωνας δωδεκα και [επι]{.greek-omitted} [τοις]{.greek-omitted} [πυλωσιν]{.greek-omitted} [αγγελους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} ονοματα επιγεγραμμενα α [εστιν]{.greek-omitted} [εστι]{.greek-added} [ονοματα]{.greek-omitted} των δωδεκα φυλων των υιων [ισραηλ]{.greek-abbr}[21:12]{.aside}

απο ανατολων πυλωνες τρεις [και]{.greek-omitted} απο βορρα πυλωνες τρεις [και]{.greek-omitted} [απο]{.greek-omitted} [νοτου]{.greek-omitted} [πυλωνες]{.greek-omitted} [τρεις]{.greek-omitted} [και]{.greek-omitted} απο δυσμων πυλωνες τρεις [απο]{.greek-added} [μεσημεριας]{.greek-added} [πυλωνες]{.greek-added} [τρεις]{.greek-added}[21:13]{.aside}

και το τειχος της πολεως εχον θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} [μετρον]{.greek-omitted} καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης [οσον]{.greek-omitted} [και]{.greek-added} το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν [εν]{.greek-added} τω καλαμω επι [σταδιους]{.greek-omitted} [σταδιων]{.greek-added} δωδεκα χιλιαδων [δωδεκα]{.greek-omitted} το μηκος και το πλατος και το υψος αυτης ισα [εστιν]{.greek-omitted} [εστι]{.greek-added}[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} το τειχος αυτης εκατον τεσσαρακοντα τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν [αγγελου]{.greek-omitted} [αγγελος]{.greek-added}[21:17]{.aside}

και [ην]{.greek-omitted} η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον [ομοιον]{.greek-omitted} [ομοια]{.greek-added} υελω καθαρω[21:18]{.aside}

[και]{.greek-added} οι θεμελιοι του τειχους της πολεως παντι λιθω τιμιω κεκοσμημενοι [ο]{.greek-omitted} [θεμελιος]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [ιασπις]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [σαπφειρος]{.greek-omitted} [ο]{.greek-omitted} [τριτος]{.greek-omitted} [χαλκηδων]{.greek-omitted} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} [σμαραγδος]{.greek-omitted}[21:19]{.aside}

[οι]{.greek-omitted} [θεμελιοι]{.greek-omitted} [του]{.greek-omitted} [τειχους]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [παντι]{.greek-omitted} [λιθω]{.greek-omitted} [τιμιω]{.greek-omitted} [κεκοσμημενοι]{.greek-omitted} ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος [χαλκηδων]{.greek-omitted} [χαλκιδων]{.greek-added} [ο]{.greek-omitted} [τεταρτος]{.greek-omitted} [σμαραγδος]{.greek-omitted}[21:19 | instance no. 2]{.aside}

[οι]{.greek-omitted} [θεμελιοι]{.greek-omitted} [του]{.greek-omitted} [τειχους]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [παντι]{.greek-omitted} [λιθω]{.greek-omitted} [τιμιω]{.greek-omitted} [κεκοσμημενοι]{.greek-omitted} [ο]{.greek-omitted} [θεμελιος]{.greek-omitted} [ο]{.greek-omitted} [πρωτος]{.greek-omitted} [ιασπις]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [σαπφειρος]{.greek-omitted} [ο]{.greek-omitted} [τριτος]{.greek-omitted} [χαλκηδων]{.greek-omitted} ο τεταρτος σμαραγδος[21:19 | instance no. 3]{.aside}

ο πεμπτος σαρδονυξ ο εκτος [σαρδιον]{.greek-omitted} [σαρδιος]{.greek-added} ο εβδομος χρυσολιθος [ο]{.greek-omitted} [ογδοος]{.greek-omitted} [βηρυλλος]{.greek-omitted} [ο]{.greek-omitted} [ενατος]{.greek-omitted} [τοπαζιον]{.greek-omitted} [ο]{.greek-omitted} [δεκατος]{.greek-omitted} [χρυσοπρασος]{.greek-omitted} [ο]{.greek-omitted} [ενδεκατος]{.greek-omitted} [υακινθος]{.greek-omitted} [ο]{.greek-omitted} [δωδεκατος]{.greek-omitted} [αμεθυσος]{.greek-omitted}[21:20]{.aside}

[ο]{.greek-omitted} [πεμπτος]{.greek-omitted} [σαρδονυξ]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [σαρδιον]{.greek-omitted} [ο]{.greek-omitted} [εβδομος]{.greek-omitted} [χρυσολιθος]{.greek-omitted} ο ογδοος [βηρυλλος]{.greek-omitted} [βηρυλλιος]{.greek-added} ο [ενατος]{.greek-omitted} [εννατος]{.greek-added} τοπαζιον ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος [ο]{.greek-omitted} [δωδεκατος]{.greek-omitted} [αμεθυσος]{.greek-omitted}[21:20 | instance no. 2]{.aside}

[ο]{.greek-omitted} [πεμπτος]{.greek-omitted} [σαρδονυξ]{.greek-omitted} [ο]{.greek-omitted} [εκτος]{.greek-omitted} [σαρδιον]{.greek-omitted} [ο]{.greek-omitted} [εβδομος]{.greek-omitted} [χρυσολιθος]{.greek-omitted} [ο]{.greek-omitted} [ογδοος]{.greek-omitted} [βηρυλλος]{.greek-omitted} [ο]{.greek-omitted} [ενατος]{.greek-omitted} [τοπαζιον]{.greek-omitted} [ο]{.greek-omitted} [δεκατος]{.greek-omitted} [χρυσοπρασος]{.greek-omitted} [ο]{.greek-omitted} [ενδεκατος]{.greek-omitted} [υακινθος]{.greek-omitted} ο δωδεκατος αμεθυσος[21:20 | instance no. 3]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται [ανα]{.greek-omitted} [και]{.greek-added} εις εκαστος των πυλωνων ην εξ ενος μαργαριτου [και]{.greek-omitted} [η]{.greek-omitted} [πλατεια]{.greek-omitted} [της]{.greek-omitted} [πολεως]{.greek-omitted} [χρυσιον]{.greek-omitted} [καθαρον]{.greek-omitted} [ως]{.greek-omitted} [υελος]{.greek-omitted} [διαυγης]{.greek-omitted}[21:21]{.aside}

[και]{.greek-omitted} [οι]{.greek-omitted} [δωδεκα]{.greek-omitted} [πυλωνες]{.greek-omitted} [δωδεκα]{.greek-omitted} [μαργαριται]{.greek-omitted} [ανα]{.greek-omitted} [εις]{.greek-omitted} [εκαστος]{.greek-omitted} [των]{.greek-omitted} [πυλωνων]{.greek-omitted} [ην]{.greek-omitted} [εξ]{.greek-omitted} [ενος]{.greek-omitted} [μαργαριτου]{.greek-omitted} και η πλατεια της πολεως χρυσιον καθαρον ως υελος διαυγης[21:21 | instance no. 2]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν αυτη η γαρ δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο [λυχνος]{.greek-omitted} [αυτης]{.greek-omitted} [το]{.greek-omitted} [αρνιον]{.greek-omitted}[21:23]{.aside}

[και]{.greek-omitted} [η]{.greek-omitted} [πολις]{.greek-omitted} [ου]{.greek-omitted} [χρειαν]{.greek-omitted} [εχει]{.greek-omitted} [του]{.greek-omitted} [ηλιου]{.greek-omitted} [ουδε]{.greek-omitted} [της]{.greek-omitted} [σεληνης]{.greek-omitted} [ινα]{.greek-omitted} [φαινωσιν]{.greek-omitted} [αυτη]{.greek-omitted} [η]{.greek-omitted} [γαρ]{.greek-omitted} [δοξα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εφωτισεν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} λυχνος αυτης το αρνιον[21:23 | instance no. 2]{.aside}

και [τα]{.greek-added} [εθνη]{.greek-added} [των]{.greek-added} [σωζομενων]{.greek-added} [τω]{.greek-added} [φωτι]{.greek-added} [αυτης]{.greek-added} [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης [και]{.greek-omitted} οι βασιλεις της γης [φερουσιν]{.greek-omitted} [φερουσι]{.greek-added} [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν [αυτων]{.greek-added} [εις]{.greek-added} [αυτην]{.greek-added} και [την]{.greek-added} τιμην των εθνων [εις]{.greek-omitted} [αυτην]{.greek-omitted}[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην [ινα]{.greek-added} [εισελθωσι]{.greek-added}[21:26]{.aside}

και ου μη εισελθη εις αυτην παν κοινον και ποιουν βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον καθαρον υδατος ζωης λαμπρον ως [κρυσταλλον]{.greek-omitted} [κρυσταλον]{.greek-added} εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και [εκειθεν]{.greek-omitted} [εντευθεν]{.greek-added} ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα [ενα]{.greek-added} εκαστον [αποδιδους]{.greek-omitted} [αποδιδουν]{.greek-added} τον καρπον αυτου [και]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [του]{.greek-omitted} [ξυλου]{.greek-omitted} [εις]{.greek-omitted} [θεραπειαν]{.greek-omitted} [των]{.greek-omitted} [εθνων]{.greek-omitted}[22:2]{.aside}

[εν]{.greek-omitted} [μεσω]{.greek-omitted} [της]{.greek-omitted} [πλατειας]{.greek-omitted} [αυτης]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [ποταμου]{.greek-omitted} [εντευθεν]{.greek-omitted} [και]{.greek-omitted} [εκειθεν]{.greek-omitted} [ξυλον]{.greek-omitted} [ζωης]{.greek-omitted} [ποιουν]{.greek-omitted} [καρπους]{.greek-omitted} [δωδεκα]{.greek-omitted} [κατα]{.greek-omitted} [μηνα]{.greek-omitted} [εκαστον]{.greek-omitted} [αποδιδους]{.greek-omitted} [τον]{.greek-omitted} [καρπον]{.greek-omitted} [αυτου]{.greek-omitted} και τα φυλλα του ξυλου εις θεραπειαν των εθνων[22:2 | instance no. 2]{.aside}

και παν καταθεμα ουκ εσται [εκει]{.greek-added} [ετι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [θρονος]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [αρνιου]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [εσται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [δουλοι]{.greek-omitted} [αυτου]{.greek-omitted} [λατρευσουσιν]{.greek-omitted} [αυτω]{.greek-omitted}[22:3]{.aside}

και [λεγει]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι οι λογοι πιστοι και αληθινοι και [κυριος]{.greek-omitted} [ο[κυριος]{.greek-abbr}]{.greek-added} ο [θεος]{.greek-abbr} των [αγιων]{.greek-added} [πνευματων]{.greek-omitted} [των]{.greek-omitted} προφητων απεστειλεν τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

[και]{.greek-omitted} ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας του βιβλιου τουτου[22:7]{.aside}

[καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} ιωαννης ο [βλεπων]{.greek-added} [και]{.greek-added} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} ταυτα και οτε ηκουσα και εβλεψα επεσον προσκυνησαι εμπροσθεν [των]{.greek-omitted} [ποδων]{.greek-omitted} του αγγελου του δεικνυοντος μοι ταυτα[22:8]{.aside}

και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των προφητων και των τηρουντων τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου [οτι]{.greek-added} ο καιρος [γαρ]{.greek-omitted} εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο ρυπαρος ρυπαρευθητω ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον [αυτου]{.greek-added} εσται [αυτου]{.greek-omitted}[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και [το]{.greek-omitted} [ω]{.greek-abbr} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} ο πρωτος και ο εσχατος [η]{.greek-omitted} [αρχη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τελος]{.greek-omitted}[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι το ξυλον της ζωης και τοις πυλωσιν [[πυλεωσιν]{.corr}]{.greek-added} εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και [οι]{.greek-omitted} πορνοι και οι φονεις και οι ειδωλολατραι και πας [ο]{.greek-added} φιλων και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι υμιν ταυτα [επι]{.greek-omitted} ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} [και]{.greek-added} ο αστηρ ο λαμπρος ο πρωινος [ο]{.greek-added} [αυτος]{.greek-added}[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν ερχου και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων [λαβετω]{.greek-omitted} [λαβειν]{.greek-added} υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι τω ακουοντι τους λογους της προφητειας του βιβλιου τουτου εαν τις [επιθη]{.greek-omitted} [επιθηση]{.greek-added} επ [αυτα]{.greek-omitted} [αυτω]{.greek-added} [επιθησαι]{.greek-omitted} [επιθησει]{.greek-added} ο [θεος]{.greek-abbr} [αυτω]{.greek-added} [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας [επτα]{.greek-added} πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και εαν τις [αφελη]{.greek-omitted} [αφεληται]{.greek-added} απο των λογων [της]{.greek-added} [προφητειας]{.greek-added} του βιβλιου [τουτου]{.greek-added} [της]{.greek-omitted} [προφητειας]{.greek-omitted} [ταυτης]{.greek-omitted} [αφελοι]{.greek-omitted} [αφελει]{.greek-added} ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν τω βιβλιω τουτω[22:19]{.aside}

λεγει ο μαρτυρων ταυτα [το]{.greek-added} ναι ερχομαι ταχυ [αμην]{.greek-omitted} [ναι]{.greek-omitted} ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων αμην[22:21]{.aside}

