---
title: "Collation of Byz^RP^ vs 32057 (2057)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2057 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32057).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2057                                   	| λογος                              	|
| 2057 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2057 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2057               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2057                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2057 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2057                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου [ιωαννη]{.greek-abbr}[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [εισι]{.greek-added} [και]{.greek-added} [αχρη]{.greek-added} [γενεσθαι]{.greek-added} [μετα]{.greek-added} [ταυτα]{.greek-added}[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο [γαρ]{.greek-omitted} καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-omitted} ο ων και ο ην και ο ερχομενος και απο των επτα [πνευματων]{.greek-abbr} α [εστιν]{.greek-added} ενωπιον του θρονου αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος [εκ]{.greek-added} των νεκρων και ο αρχων των βασιλεων της γης τω [αγαπωντι]{.greek-omitted} [αγαπησαντι]{.greek-added} ημας και λουσαντι ημας [απο]{.greek-omitted} [εκ]{.greek-added} των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας [βασιλειαν]{.greek-omitted} [βασιλεις]{.greek-added} [και]{.greek-added} ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου [αυτω]{.greek-omitted} [ω]{.greek-added} η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συγκοινωνος]{.greek-added} [εν]{.unclear} τη θλιψει και [εν]{.greek-added} [τη]{.greek-added} βασιλεια και υπομονη [εν]{.greek-omitted} [χριστω]{.greek-omitted} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} [εγενομην]{.greek-omitted} [εγενομη]{.greek-added} εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-omitted}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν [τη]{.greek-omitted} κυριακη ημερα και ηκουσα [φωνην]{.greek-omitted} οπισω μου [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} ως σαλπιγγος[1:10]{.aside}

λεγουσης [εγω]{.greek-added} [ειμι]{.greek-added} [το]{.greek-added} [[α]{.greek-abbr}]{.greek-added} [και]{.greek-added} [το]{.greek-added} [[ω]{.greek-abbr}]{.greek-added} [ο]{.greek-added} [πρωτος]{.greek-added} [και]{.greek-added} [εσχατος]{.greek-added} [και]{.greek-added} ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις [σμυρναν]{.greek-omitted} [μυρναν]{.greek-added} και εις περγαμον και [εις]{.greek-omitted} [θυατειρα]{.greek-omitted} [εν]{.greek-added} [θυατηροις]{.greek-added} και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

και [εκει]{.greek-omitted} [επεστρεψα]{.greek-omitted} [υπεστρεψα]{.greek-added} [βλεπειν]{.greek-omitted} [βλεψαι]{.greek-added} την φωνην ητις [ελαλει]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου και [επιστρεψας]{.greek-omitted} [υποστρεψας]{.greek-added} ειδον επτα λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των [επτα]{.greek-omitted} [λυχνιων]{.greek-omitted} [λυχνων]{.greek-added} ομοιον υιω [ανθρωπου]{.greek-abbr} ενδεδυμενον [ποδηρη]{.greek-omitted} [ποδηρει]{.greek-added} και περιεζωσμενον προς τοις [μαστοις]{.greek-omitted} [μαζοις]{.greek-added} ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι [τριχες]{.greek-omitted} [τριχαις]{.greek-added} λευκαι [ως]{.greek-omitted} [ωσει]{.greek-added} [εριον]{.greek-omitted} [ερειον]{.greek-added} [λευκον]{.greek-omitted} [ως]{.greek-omitted} [λευκαι]{.greek-added} [ωσει]{.greek-added} χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια αυτου χειρι αστερας επτα και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον επεσα προς τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} την δεξιαν αυτου [χειρα]{.greek-added} επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην [νεκρος]{.greek-omitted} [νοκρος]{.greek-added} και ιδου ζων ειμι εις τους αιωνας των αιωνων [αμην]{.greek-omitted} [και]{.greek-omitted} [εχω]{.greek-omitted} [τας]{.greek-omitted} [κλεις]{.greek-omitted} [του]{.greek-omitted} [θανατου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [αδου]{.greek-omitted}[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων [ων]{.greek-omitted} [ους]{.greek-added} ειδες επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων [εισιν]{.greek-omitted} [εισι]{.greek-added} και αι [επτα]{.greek-added} λυχνιαι [αι]{.greek-omitted} [επτα]{.greek-omitted} [ας]{.greek-added} [ειδες]{.greek-added} επτα εκκλησιαι [εισιν]{.greek-omitted} [εισι]{.greek-added}[1:20]{.aside}

### Chapter 2

τω αγγελω της [εν]{.greek-omitted} [εφεσω]{.greek-omitted} [ενεφεσω]{.greek-added} εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των [επτα]{.greek-omitted} λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη [βαστασαι]{.greek-omitted} [βασταξαι]{.greek-added} κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ εισιν και ευρες αυτους ψευδεις[2:2]{.aside}

[και]{.greek-added} [εβαστασας]{.greek-added} και υπομονην εχεις [και]{.greek-omitted} [εβαστασας]{.greek-omitted} δια το ονομα μου και ουκ [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν [πεπτωκας]{.greek-omitted} [εκπεπτωκας]{.greek-added} και μετανοησον και τα [πρωτα]{.greek-omitted} [πρωτερα]{.greek-added} [[προτερα]{.corr}]{.greek-added} εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω [αυτω]{.greek-omitted} φαγειν εκ του ξυλου της ζωης ο εστιν εν [τω]{.greek-omitted} [μεσω]{.greek-added} [του]{.greek-added} [παραδεισω]{.greek-omitted} [παραδεισου]{.greek-added} του [θεου]{.greek-abbr} [μου]{.greek-omitted}[2:7]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την βλασφημιαν [εκ]{.greek-omitted} των λεγοντων [εαυτους]{.greek-added} ιουδαιους ειναι [εαυτους]{.greek-omitted} και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} ο [διαβολος]{.greek-omitted} [αβολος]{.greek-added} [βάλλειν]{.greek-added} εξ υμων εις φυλακην ινα πειρασθητε και [εξετε]{.greek-omitted} [εχητε]{.greek-added} θλιψιν ημερων δεκα γινου πιστος [αχρι]{.greek-omitted} [αχρη]{.greek-added} θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα [σου]{.greek-added} τα εργα [σου]{.greek-omitted} και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} μου εν ταις ημεραις [εν]{.greek-omitted} [αις]{.greek-omitted} [εναις]{.greek-added} [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς μου ο [πιστος]{.greek-added} [οτι]{.greek-added} [πας]{.greek-added} [μαρτυς]{.greek-added} πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην [του]{.greek-added} βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδασκεν]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [βαλααμ]{.greek-added} τον βαλακ βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και [συ]{.greek-omitted} κρατουντας την διδαχην των νικολαιτων ομοιως [ων]{.greek-added} [μισων]{.greek-added}[2:15]{.aside}

μετανοησον [ουν]{.greek-omitted} ει δε μη ερχομαι [σοι]{.greek-omitted} ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω [νικωντι]{.greek-omitted} [νικοντι]{.greek-added} δωσω [αυτω]{.greek-omitted} [φαγειν]{.greek-added} [απο]{.greek-added} του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατηροις]{.greek-added} εκκλησιας γραψον ταδε λεγει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως [φλογα]{.greek-omitted} [φλοξ]{.greek-added} πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου [πολυ]{.greek-added} οτι [αφεις]{.greek-omitted} [αφηκας]{.greek-added} την γυναικα [σου]{.greek-omitted} ιεζαβελ [η]{.greek-omitted} [λεγει]{.greek-omitted} [την]{.greek-added} [λεγουσαν]{.greek-added} εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση [και]{.greek-omitted} [ου]{.greek-omitted} [θελει]{.greek-omitted} [μετανοησαι]{.greek-omitted} εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους [μοιχευοντας]{.greek-omitted} [μοιχευσοντας]{.greek-added} [[μοιχευσαντας]{.corr}]{.greek-added} μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων [αυτης]{.greek-omitted} [αυτων]{.greek-added}[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν [θυατειροις]{.greek-omitted} [θυατηροις]{.greek-added} οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βάθη]{.greek-added} του σατανα ως λεγουσιν ου βαλλω εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} [ου]{.greek-omitted} αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν [επι]{.greek-omitted} [επανω]{.greek-added} των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι [ζεις]{.greek-added} [ζης]{.corr} και νεκρος ει[3:1]{.aside}

γινου γρηγορων και [στηρισον]{.greek-omitted} [στηριξον]{.greek-added} τα λοιπα α [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [εμελλον]{.greek-added} [αποθανειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} [μου]{.greek-omitted}[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη γρηγορησης ηξω [επι]{.greek-omitted} [σε]{.greek-omitted} ως κλεπτης και ου μη γνως ποιαν ωραν ηξω επι σε[3:3]{.aside}

[αλλ]{.greek-omitted} [εχεις]{.greek-added} ολιγα [εχεις]{.greek-omitted} ονοματα εν σαρδεσιν [α]{.greek-omitted} [οι]{.greek-added} ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την [κλειν]{.greek-omitted} [κλειδα]{.greek-added} του [δαυιδ]{.greek-omitted} [αδου]{.greek-added} ο ανοιγων και ουδεις [κλεισει]{.greek-omitted} [κλειει]{.greek-added} [και]{.greek-added} [κλειων]{.greek-added} [αυτην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} και ουδεις [ανοιξει]{.greek-omitted} [ανοιγει]{.greek-added}[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται [ιδου]{.greek-omitted} [και]{.greek-added} ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι [εγω]{.greek-added} ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον [σου]{.corr}[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και [εξω]{.greek-omitted} ου μη εξελθη ετι και γραψω επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} η [καταβαινει]{.greek-omitted} [καταβαινουσα]{.greek-added} εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr} μου και το ονομα μου το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν [λαοδικεια]{.greek-omitted} [λαοδικια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και [αληθης]{.greek-added} [αληθινος]{.greek-omitted} [η]{.greek-omitted} [αρχη]{.greek-omitted} [της]{.greek-omitted} [κτισεως]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε ζεστος [οφελον]{.greek-omitted} [ωφελον]{.greek-added} ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και [ου]{.greek-omitted} [ουτε]{.greek-added} ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και πεπλουτηκα και [ουδενος]{.greek-omitted} [ουδεν]{.greek-added} χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και ο ελεεινος και πτωχος και [γυμνος]{.greek-added} [και]{.greek-added} τυφλος [και]{.greek-omitted} [γυμνος]{.greek-omitted}[3:17]{.aside}

συμβουλευω σοι αγορασαι [χρυσιον]{.greek-omitted} παρ εμου [χρυσιον]{.greek-added} [πεπυρωμενον]{.greek-omitted} [πεπυρομενον]{.greek-added} εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη [φανερωθη]{.greek-omitted} [φανη]{.greek-added} η [αισχυνη]{.greek-omitted} [ασχημοσυνη]{.greek-added} της γυμνοτητος σου και κολλυριον [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [εγχρισον]{.greek-added} τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους [εαν]{.greek-omitted} φιλω ελεγχω και παιδευω ζηλωσον ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν [και]{.greek-omitted} εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη [ην]{.greek-omitted} [ηκουσα]{.greek-omitted} ως σαλπιγγος [λαλουσης]{.greek-omitted} [λεγουσης]{.greek-added} μετ εμου [λεγων]{.greek-omitted} αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι [τον]{.greek-omitted} [του]{.greek-added} [θρονον]{.greek-omitted} [θρονου]{.greek-added} καθημενος[4:2]{.aside}

ομοιος ορασει λιθω ιασπιδι και [σαρδιω]{.greek-omitted} [σαρδινω]{.greek-added} και [ιρις]{.greek-omitted} [ἶρις]{.greek-added} κυκλοθεν του θρονου [ομοιως]{.greek-omitted} [ομοια]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδινω]{.greek-added}[4:3]{.aside}

και κυκλοθεν του θρονου θρονοι εικοσι τεσσαρες και επι [τους]{.greek-omitted} [του]{.greek-added} [θρονους]{.greek-omitted} [θρονου]{.greek-added} [τους]{.greek-omitted} [εικοσι]{.greek-omitted} τεσσαρας πρεσβυτερους [καθημενους]{.greek-omitted} περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του [θρονου]{.greek-omitted} [φοβου]{.greek-added} εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου [αυτου]{.greek-omitted} αι [εισιν]{.greek-omitted} [εισι]{.greek-added} [τα]{.greek-added} επτα [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα [υαλινη]{.greek-omitted} [υελινη]{.greek-added} ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον [εχων]{.greek-added} [εχον]{.corr} [το]{.greek-added} προσωπον [ως]{.greek-added} [ανθρωπου]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} και το τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και [τα]{.greek-omitted} τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} εχον ανα πτερυγας εξ [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} [και]{.greek-omitted} [εσωθεν]{.greek-omitted} γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος [λεγοντες]{.greek-omitted} [λεγοντα]{.greek-added} αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσωσι]{.greek-added} τα ζωα δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου τω ζωντι εις τους αιωνας των αιωνων [αμην]{.greek-added} [τελος]{.greek-added}[4:9]{.aside}

[πεσουνται]{.greek-omitted} [οι]{.greek-omitted} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [καθημενου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} και [προσκυνησουσιν]{.greek-omitted} [τω]{.greek-omitted} [ζωντι]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted} [και]{.greek-omitted} [βαλουσιν]{.greek-omitted} [βαλοῦσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει [[κυριε]{.greek-abbr}]{.greek-added} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [και]{.greek-omitted} ο [θεος]{.greek-abbr} ημων [ο]{.greek-omitted} [αγιος]{.greek-omitted} λαβειν την δοξαν και την τιμην [και]{.greek-omitted} [την]{.greek-omitted} [δυναμιν]{.greek-omitted} οτι συ εκτισας [τα]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισι]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και [εξωθεν]{.greek-omitted} [οπισθεν]{.greek-added} κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα [εν]{.greek-omitted} φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος [εστιν]{.greek-omitted} ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εν τω [ουρανω]{.greek-abbr} [ανω]{.greek-omitted} [ουτε]{.greek-omitted} [ουδε]{.greek-added} επι της γης [ουτε]{.greek-omitted} [ουδε]{.greek-added} υποκατω της γης ανοιξαι το βιβλιον [ουτε]{.greek-omitted} [ουδε]{.greek-added} βλεπειν αυτο[5:3]{.aside}

και [εγω]{.greek-omitted} εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι [και]{.greek-added} [αναγνωναι]{.greek-added} το βιβλιον ουτε βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και τας [επτα]{.greek-omitted} σφραγιδας αυτου[5:5]{.aside}

και [ειδον]{.greek-omitted} [ιδου]{.greek-added} εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος [ως]{.greek-omitted} εσφαγμενον εχον κερατα επτα [οι]{.greek-added} [και]{.greek-omitted} [οφθαλμους]{.greek-omitted} [επτα]{.greek-omitted} [α]{.greek-omitted} [εισιν]{.greek-omitted} [εισι]{.greek-added} τα [επτα]{.greek-omitted} [πνευματα]{.greek-omitted} [[πνευμα]{.greek-abbr}]{.greek-added} του [θεου]{.greek-abbr} [αποστελλομενα]{.greek-omitted} [απεσταλμενα]{.greek-added} εις πασαν την γην[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι επεσον ενωπιον του αρνιου εχοντες εκαστος [κιθαραν]{.greek-omitted} [κιθαρας]{.greek-added} και φιαλας χρυσας γεμουσας θυμιαματων [α]{.greek-added} [εισιν]{.greek-added} αι [εισιν]{.greek-omitted} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας τω [θεω]{.greek-abbr} ημας εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων [βασιλεις]{.greek-omitted} [βασιλαις]{.greek-added} και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και ειδον και ηκουσα [ως]{.greek-omitted} φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον [εστιν]{.greek-omitted} [εστι]{.greek-added} το αρνιον το εσφαγμενον λαβειν την δυναμιν και τον πλουτον και [την]{.greek-added} σοφιαν και [την]{.greek-added} ισχυν και [την]{.greek-added} τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν τω [ουρανω]{.greek-abbr} και επι της γης και [υποκατω]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} επι της θαλασσης [α]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις [παντας]{.greek-omitted} [παντα]{.greek-added} ηκουσα [λεγοντας]{.greek-omitted} [λεγοντα]{.greek-added} τω καθημενω επι του θρονου και τω αρνιω [η]{.greek-omitted} ευλογια και [η]{.greek-omitted} τιμη και [η]{.greek-omitted} δοξα [και]{.greek-omitted} [το]{.greek-omitted} [κρατος]{.greek-omitted} εις τους αιωνας των αιωνων αμην[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} [το]{.greek-omitted} αμην και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των [επτα]{.greek-omitted} σφραγιδων και ηκουσα [ενος]{.greek-omitted} [τινος]{.greek-added} εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνῆς]{.greek-added} βρον[της]{.greek-supplied} [ερχου]{.greek-supplied} [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[[και]{.greek-supplied}]{.greek-added} [[ειδον]{.greek-supplied}]{.greek-added} [και]{.greek-supplied} ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα νικηση[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [την]{.greek-added} [σφραγιδα]{.greek-added} την δευτεραν [σφραγιδα]{.greek-omitted} ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος πυρος και τω καθημενω επ αυτον εδοθη αυτω λαβειν την ειρηνην [εκ]{.greek-omitted} της γης [και]{.greek-added} ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [ειδον]{.greek-added} και ιδου ιππος [μεγας]{.greek-added} [μελας]{.corr} και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα [ως]{.greek-added} φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες κριθης δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα [φωνης]{.greek-added} του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω [αυτου]{.greek-omitted} ονομα αυτω ο θανατος και ο αδης [ηκολουθει]{.greek-omitted} [ακολουθει]{.greek-added} [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} και εδοθη [αυτω]{.greek-omitted} [αυτοις]{.greek-added} εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και [υπο]{.greek-omitted} [απο]{.greek-added} των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [του]{.greek-omitted} [αρνιου]{.greek-omitted} ην ειχον[6:9]{.aside}

και [εκραξαν]{.greek-omitted} [εκραξον]{.greek-added} φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και [εκδικεις]{.greek-omitted} [εκδικης]{.greek-added} το αιμα ημων [εκ]{.greek-omitted} [απο]{.greek-added} των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} [ετι]{.greek-omitted} χρονον [μικρον]{.greek-added} εως [ου]{.greek-added} [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων [και]{.greek-omitted} οι μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκταινεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

και ειδον [και]{.greek-added} οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος [εγενετο]{.greek-added} μελας [εγενετο]{.greek-omitted} ως σακκος τριχινος και η [σεληνη]{.greek-omitted} [σελινη]{.greek-added} [ολη]{.greek-omitted} εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλει]{.greek-added} τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} [απεχωρισθη]{.greek-omitted} [απεχορισθη]{.greek-added} ως βιβλιον [ελισσομενον]{.greek-omitted} [ειλισσομενον]{.greek-added} και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι [χιλιαρχοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} πλουσιοι και οι [ισχυροι]{.greek-omitted} [χιλιαρχοι]{.greek-added} και πας δουλος και [πας]{.greek-added} ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις [πεσετε]{.greek-omitted} [πεσε[τ]{.unclear}αι]{.greek-added} εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

και μετα [τουτο]{.greek-omitted} [ταυτα]{.greek-added} ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης [ινα]{.greek-added} [μη]{.greek-added} [πνεη]{.greek-added} [κρατουντας]{.greek-omitted} [μηκρατουντας]{.greek-added} [τους]{.greek-omitted} [τας]{.greek-added} τεσσαρας ανεμους της γης ινα μη πνεη ανεμος επι της γης μητε επι της θαλασσης μητε επι [τι]{.greek-omitted} [παν]{.greek-added} δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα [σφραγιδα]{.greek-omitted} [σφραγιδας]{.greek-added} [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην [μητε]{.greek-omitted} [μη]{.greek-added} [δε]{.greek-added} την θαλασσαν [μητε]{.greek-omitted} [μη]{.greek-added} [δε]{.greek-added} τα δενδρα αχρι [ου]{.greek-omitted} σφραγισωμεν τους [δουλους]{.greek-omitted} [δουλος]{.greek-added} του [θεου]{.greek-abbr} ημων επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον [και]{.greek-omitted} τεσσαρακοντα τεσσαρες χιλιαδες [εσφραγισμενων]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης ρουβιμ δωδεκα χιλιαδες [εσφραγισμενοι]{.greek-added} εκ φυλης γαδ δωδεκα χιλιαδες[7:5]{.aside}

εκ φυλης ασηρ δωδεκα χιλιαδες εκ φυλης νεφθαλειμ δωδεκα χιλιαδες εκ φυλης μανασση δωδεκα χιλιαδες[7:6]{.aside}

εκ φυλης συμεων δωδεκα χιλιαδες εκ φυλης λευι δωδεκα χιλιαδες εκ φυλης ισαχαρ δωδεκα χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων δωδεκα χιλιαδες εκ φυλης ιωσηφ δωδεκα χιλιαδες εκ φυλης βενιαμιν δωδεκα χιλιαδες [εσφραγισμεναι]{.greek-omitted}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι [αυτον]{.greek-added} ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εκ παντος εθνους και φυλων και λαων και γλωσσων [εστωτας]{.greek-omitted} [εστωτες]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου [περιβεβλημενους]{.greek-omitted} [περιβιβλιμενοι]{.greek-added} στολας λευκας και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω θρονω και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα [και]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} και η ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην [-]{.greek-added}[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι [περιβεβλημενοι]{.greek-omitted} [περιβεβλιμενοι]{.greek-added} τας στολας τας λευκας τινες [εισιν]{.greek-omitted} και ποθεν ηλθον[7:13]{.aside}

και [ειπον]{.greek-omitted} [ειρηκα]{.greek-added} αυτω κυριε μου συ [οιδας]{.greek-omitted} [ειδας]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι εισιν οι ερχομενοι [εκ]{.greek-omitted} [απο]{.greek-added} της θλιψεως της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν [αυτας]{.greek-added} εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

ου πεινασουσιν [ετι]{.greek-omitted} ουδε διψησουσιν [ετι]{.greek-omitted} ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγησει]{.greek-added} αυτους επι ζωης πηγας υδατων και [εξαλειψει]{.greek-omitted} [εξ[α]{.unclear}λει]{.greek-added} ο [θεος]{.greek-abbr} παν δακρυον [εκ]{.greek-omitted} [απο]{.greek-added} των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την εβδομην εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι [του]{.greek-omitted} [το]{.greek-added} [θυσιαστηριου]{.greek-omitted} [θυσιαστηριον]{.greek-added} εχων λιβανωτον χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα δωση [ταις]{.greek-omitted} [τας]{.greek-added} [προσευχαις]{.greek-omitted} [προσευχας]{.greek-added} των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων [ταις]{.greek-omitted} [της]{.greek-added} [προσευχαις]{.greek-omitted} [προσευχης]{.greek-added} των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο [φωναι]{.greek-added} [και]{.greek-added} βρονται [και]{.greek-omitted} [φωναι]{.greek-omitted} και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος [αγγελος]{.greek-added} [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ [μεμιγμενα]{.greek-omitted} [μεμιγμενον]{.greek-added} [εν]{.greek-omitted} αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη [και]{.greek-omitted} [το]{.greek-omitted} [τριτον]{.greek-omitted} [των]{.greek-omitted} [δενδρων]{.greek-omitted} [κατεκαη]{.greek-omitted} [και]{.greek-omitted} [πας]{.greek-omitted} [χορτος]{.greek-omitted} [χλωρος]{.greek-omitted} [κατεκαη]{.greek-omitted}[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα [πυρι]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το τριτον των κτισματων εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων διεφθαρη[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} [ο]{.greek-added} αστηρ [ο]{.greek-added} μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας [πηγας]{.greek-omitted} [πιγας]{.greek-added} των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται [ο]{.greek-omitted} αψινθος και [εγενετο]{.greek-omitted} [γινεται]{.greek-added} το τριτον των υδατων εις αψινθον και πολλοι των ανθρωπων απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [μη]{.greek-added} [φαινηται]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος [αγγελου]{.greek-added} [αετου]{.greek-omitted} [πετομενου]{.greek-omitted} εν μεσουρανηματι λεγοντος φωνη [μεγαλη]{.greek-omitted} ουαι ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος [της]{.greek-omitted} [αβυσσου]{.greek-omitted}[9:1]{.aside}

[και]{.greek-omitted} [ηνοιξεν]{.greek-omitted} [το]{.greek-omitted} [φρεαρ]{.greek-omitted} [της]{.greek-omitted} [αβυσσου]{.greek-omitted} [και]{.greek-omitted} [ανεβη]{.greek-omitted} [καπνος]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [φρεατος]{.greek-omitted} ως καπνος καμινου [καιομενης]{.greek-omitted} [μεγαλης]{.greek-added} και [εσκοτισθη]{.greek-omitted} [εσκοτωθη]{.greek-added} ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν [εξουσιαν]{.greek-omitted} οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν [χλωρον]{.greek-omitted} [χλορον]{.greek-added} ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα [του]{.greek-omitted} [θεου]{.greek-omitted} επι των μετωπων [αυτων]{.greek-omitted}[9:4]{.aside}

και εδοθη αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθησονται]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [κρουση]{.greek-added} [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [εὕρωσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευγει]{.greek-added} [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι [χρυσοι]{.greek-omitted} [ομοιοι]{.greek-added} [χρυσω]{.greek-added} και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως [τριχας]{.greek-omitted} γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων [αυτων]{.greek-omitted} ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας [ομοιας]{.greek-omitted} [ομοιως]{.greek-added} σκορπιοις και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[εχουσαι]{.greek-omitted} [εχουσιν]{.greek-added} [βασιλεα]{.greek-omitted} επ αυτων [βασιλεα]{.greek-added} [τον]{.greek-added} αγγελον της αβυσσου ονομα αυτω εβραιστι αββαδων [και]{.greek-added} εν [δε]{.greek-omitted} τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια α[πη]{.unclear}λθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} [ετι]{.greek-omitted} δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του [θυσιαστηριου]{.greek-omitted} [του]{.greek-omitted} χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγουσα]{.greek-added} τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω [ευφρατη]{.greek-omitted} [εφρατη]{.greek-added}[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και [εις]{.greek-omitted} [την]{.greek-omitted} ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [ιππου]{.greek-omitted} [ιππικου]{.greek-added} [μυριαδες]{.greek-omitted} [δισμυριαδες]{.greek-added} μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και [υακινθινους]{.greek-omitted} [υακινθυνους]{.greek-added} και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και [θειον]{.greek-omitted} [θυιον]{.greek-added}[9:17]{.aside}

απο των τριων [πληγων]{.greek-omitted} τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του πυρος και [εκ]{.greek-added} του καπνου και [εκ]{.greek-added} του [θειου]{.greek-omitted} [θυιου]{.greek-added} του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η [γαρ]{.greek-omitted} εξουσια [εκ]{.greek-added} [του]{.greek-added} [των]{.greek-omitted} [ιππων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [στοματι]{.greek-omitted} [στοματος]{.greek-added} αυτων εστιν [και]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [ουραις]{.greek-omitted} [αυτων]{.greek-omitted} αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} εχουσαι κεφαλας και εν αυταις αδικουσιν[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και τα αργυρα και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακιων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και [η]{.greek-omitted} [ιρις]{.greek-omitted} [ιριν]{.greek-added} επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και [εχων]{.greek-omitted} [εχει]{.greek-added} εν τη χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλαριδιον]{.greek-added} ανεωγμενον και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και [οτε]{.greek-omitted} εκραξεν [φωνησαν]{.greek-added} [ελαλησαν]{.corr} αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και [μη]{.greek-omitted} [μετα]{.greek-added} [αυτα]{.greek-omitted} [ταυτα]{.greek-added} [γραψης]{.greek-omitted} [γραφεις]{.greek-added}[10:4]{.aside}

και ο αγγελος ον ειδον εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου [την]{.greek-omitted} [δεξιαν]{.greek-omitted} εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και ωμοσεν [εν]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν αυτω [και]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν και [ετελεσθη]{.greek-omitted} [τελεσθη]{.greek-added} το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους [εαυτου]{.greek-added} δουλους [αυτου]{.greek-omitted} τους προφητας[10:7]{.aside}

και [η]{.greek-omitted} [φωνη]{.greek-omitted} [φωνην]{.greek-added} [ην]{.greek-omitted} ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν [λαλουσα]{.greek-omitted} [λαλουσαν]{.greek-added} μετ εμου και [λεγουσα]{.greek-omitted} [λεγουσαν]{.greek-added} υπαγε λαβε το [βιβλιδαριον]{.greek-omitted} [βιβλαριδιον]{.greek-added} το [ανεωγμενον]{.greek-omitted} [ηνεωγμενον]{.greek-added} εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων αυτω [δουναι]{.greek-omitted} [δος]{.greek-added} μοι το [βιβλιδαριον]{.greek-omitted} [βιβλαριδιον]{.greek-added} και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βιβλαριδιον]{.greek-added} εκ της χειρος του αγγελου και κατεφαγον [αυτο]{.greek-omitted} [αὐτό]{.greek-added} και ην εν τω στοματι μου ως [μελι]{.greek-omitted} [μελη]{.greek-added} γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} μοι δει σε παλιν προφητευσαι επι [τοις]{.greek-added} λαοις και [επι]{.greek-omitted} [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και [γλωσσαις]{.greek-omitted} [γλωτταις]{.greek-added} και [βασιλευσιν]{.greek-omitted} [βασιλεις]{.greek-added} [πολλοις]{.greek-omitted} [της]{.greek-added} [γης]{.greek-added}[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω λεγων εγειραι και [μετρησον]{.greek-omitted} [μετρισον]{.greek-added} τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας τεσσαρακοντα [και]{.greek-omitted} δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα [περιβεβλημενοι]{.greek-omitted} [σακκους]{.greek-omitted}[11:3]{.aside}

[και]{.greek-added} ουτοι εισιν [αι]{.greek-omitted} [δυο]{.greek-omitted} [ελαιαι]{.greek-omitted} [και]{.greek-omitted} αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} της γης εστωσαι[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους αδικησαι ουτως δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι εχουσιν [εξουσιαν]{.greek-added} [κλεισαι]{.greek-added} τον [ουρανον]{.greek-abbr} [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν [αυτα]{.greek-omitted} εις αιμα και παταξαι την γην [οσακις]{.greek-omitted} [εαν]{.greek-omitted} [θελησωσιν]{.greek-omitted} εν παση πληγη [ωσακις]{.greek-added} [εαν]{.greek-added} [θελησωσιν]{.greek-added}[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της αβυσσου ποιησει [πολεμον]{.greek-added} μετ αυτων [πολεμον]{.greek-omitted} και νικησει αυτους [και]{.greek-omitted} [αποκτενει]{.greek-omitted} [αυτους]{.greek-omitted}[11:7]{.aside}

και [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου [και]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτων [εσταυρωθη]{.greek-abbr}[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων [τα]{.greek-added} [και]{.greek-omitted} [εθνων]{.greek-omitted} [το]{.greek-omitted} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφιουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και [ευφρανθησονται]{.greek-omitted} [ευφραινονται]{.greek-added} και δωρα [δωσουσιν]{.greek-omitted} [πεμψουσι]{.greek-added} αλληλοις οτι ουτοι οι δυο προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα [τας]{.greek-omitted} τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν [εις]{.greek-omitted} [εν]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και εστησαν [επι]{.greek-omitted} [υπο]{.greek-added} τους ποδας αυτων και φοβος μεγας επεσεν επι [τους]{.greek-omitted} [των]{.greek-added} [θεωρουντας]{.greek-omitted} [θεωρουντων]{.greek-added} αυτους[11:11]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσαν]{.greek-omitted} [λεγουσης]{.greek-added} αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη [ημερα]{.greek-omitted} [ωρα]{.greek-added} εγενετο σεισμος μεγας και το δεκατον της πολεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} [χιλιαδες]{.greek-omitted} [χιλιαδας]{.greek-added} επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν [ιδου]{.greek-added} η ουαι η τριτη [ιδου]{.greek-omitted} ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι [αι]{.greek-added} [εγενετο]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [βασιλειαι]{.greek-added} του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και [βασιλευσει]{.greek-omitted} [βασιλευσι]{.greek-added} εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι [οι]{.greek-omitted} ενωπιον [του]{.greek-omitted} [θρονου]{.greek-omitted} του [θεου]{.greek-abbr} καθημενοι επι τους θρονους αυτων επεσον επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη [ωργησθησαν]{.greek-added} [ωργισθησαν]{.corr} και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις [και]{.greek-omitted} τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους [διαφθειροντας]{.greek-omitted} [φθειροντας]{.greek-added} την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης [του]{.greek-omitted} [αυτου]{.greek-added} [κυριου]{.greek-omitted} εν τω ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και [σεισμος]{.greek-added} [και]{.greek-added} χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα [εκραζεν]{.greek-omitted} [κραζει]{.greek-added} ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη [αλλο]{.greek-omitted} [αλλον]{.greek-added} σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων [μεγας]{.greek-added} πυρος [μεγας]{.greek-omitted} εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου [επτα]{.greek-omitted} διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην [και]{.greek-omitted} ο δρακων [εστηκεν]{.greek-omitted} [ἕστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν υιον [αρρενα]{.greek-omitted} [αρσενα]{.greek-added} ος μελλει [ποιμαινειν]{.greek-omitted} [ποιμενειν]{.greek-added} παντα τα εθνη εν ραβδω σιδηρα και [ηρπασθη]{.greek-omitted} [ηρπαγη]{.greek-added} το τεκνον αυτης προς τον [θεον]{.greek-abbr} και [προς]{.greek-omitted} τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην [ημερας]{.greek-omitted} [χιλιας]{.greek-omitted} [διακοσιας]{.greek-omitted} [εξηκοντα]{.greek-omitted}[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου [πολεμησαι]{.greek-omitted} [πολε]{.greek-added} [μησαι]{.greek-added} μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

[και]{.greek-omitted} ουκ [ισχυσεν]{.greek-omitted} [ισχυσαν]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} τοπος ευρεθη αυτω ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο [η]{.corr} [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι [εβληθη]{.greek-omitted} [κατεβληθη]{.greek-added} ο κατηγορος των αδελφων ημων ο κατηγορων [αυτων]{.greek-omitted} [αυτους]{.greek-added} ενωπιον του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

δια τουτο [ευφραινεσθε]{.greek-omitted} [ευφραινεσθαι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν αυτοις σκηνουντες ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν [και]{.greek-added} ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε [ειδεν]{.greek-omitted} [ειδε]{.greek-added} ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν τη γυναικι [αι]{.greek-added} δυο πτερυγες του αετου του μεγαλου ινα [πετηται]{.greek-omitted} [πεταται]{.greek-added} εις την ερημον εις τον τοπον αυτης [οπως]{.greek-omitted} [οπου]{.greek-added} [τρεφηται]{.greek-omitted} [τρεφεται]{.greek-added} εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου [οπισω]{.greek-omitted} [εν]{.greek-added} [μεσω]{.greek-added} της γυναικος υδωρ ως ποταμον ινα [αυτην]{.greek-omitted} [ταυτην]{.greek-added} ποταμοφορητον ποιηση[12:15]{.aside}

και [εβοηθησεν]{.greek-omitted} [εβοησεν]{.greek-added} η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και [ωργισθη]{.greek-omitted} [οργισθη]{.greek-added} ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των [τηρουντων]{.greek-omitted} [τυρουντων]{.greek-added} τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [εστι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον εχον κερατα δεκα και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου [ονοματα]{.greek-omitted} [ονομα]{.greek-added} βλασφημιας[13:1]{.aside}

και [το]{.greek-omitted} θηριον [ο]{.greek-omitted} ειδον [ονομα]{.greek-added} [ην]{.greek-omitted} [ομοιον]{.greek-omitted} παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν [εκ]{.greek-omitted} των κεφαλων αυτου [ωσει]{.greek-omitted} [ως]{.greek-added} [εσφαγμενην]{.greek-omitted} [εσφραγισμενην]{.greek-added} εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και [εθαυμασεν]{.greek-omitted} [εθαυμασθη]{.greek-added} [εν]{.greek-added} ολη [η]{.greek-omitted} [τη]{.greek-added} γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι [οτι]{.greek-added} [εδωκεν]{.greek-added} [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [την]{.greek-omitted} εξουσιαν [τω]{.greek-omitted} [θηριω]{.greek-omitted} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} τω θηριω λεγοντες τις ομοιος τω θηριω και τις [δυνατος]{.greek-omitted} [δυναται]{.greek-added} πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και βλασφημιαν και εδοθη αυτω εξουσια [πολεμον]{.greek-omitted} ποιησαι μηνας τεσσαρακοντα δυο[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις βλασφημιαν προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου [και]{.greek-added} τους εν τω [ουρανω]{.greek-abbr} [σκηνουντας]{.greek-omitted} [κατοικουντας]{.greek-added}[13:6]{.aside}

[και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [νικησαι]{.greek-omitted} [αυτους]{.greek-omitted} και εδοθη αυτω εξουσια επι πασαν φυλην και [λαον]{.greek-omitted} [και]{.greek-omitted} γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν αυτω παντες οι κατοικουντες επι της γης ων ου γεγραπται το ονομα εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις [εν]{.greek-omitted} μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτενεῖ]{.greek-added} δει αυτον εν μαχαιρα αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον [αλλο]{.greek-omitted} [αλλον]{.greek-added} θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και [ειχεν]{.greek-omitted} [ειχε]{.greek-added} κερατα δυο ομοια αρνιω και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει σημεια μεγαλα [ινα]{.greek-added} και [το]{.greek-added} πυρ [ινα]{.greek-omitted} [ποιη]{.greek-added} [καταβαινειν]{.greek-added} εκ του [ουρανου]{.greek-abbr} [εις]{.greek-added} [καταβαινη]{.greek-omitted} [επι]{.greek-omitted} την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου [λεγων]{.greek-omitted} [λεγον]{.greek-added} τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ειχεν]{.greek-omitted} [ὃς]{.greek-added} [εχει]{.greek-added} την [πληγην]{.greek-omitted} [της]{.greek-added} [μαχαιρας]{.greek-added} και εζησεν [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

και εδοθη αυτω [δουναι]{.greek-added} [πνευμα]{.greek-abbr} [δουναι]{.greek-omitted} τη εικονι του θηριου ινα και λαληση η εικων του θηριου και [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} οσοι [εαν]{.greek-omitted} [αν]{.greek-added} μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τη εικονι του θηριου [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους [πλουσιους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} πτωχους [και]{.greek-omitted} [τους]{.greek-omitted} [ελευθερους]{.greek-omitted} και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} αυτοις [χαραγματα]{.greek-omitted} [χαραγμα]{.greek-added} επι της χειρος αυτων της δεξιας η επι [το]{.greek-omitted} [των]{.greek-added} [μετωπον]{.greek-omitted} [μετωπων]{.greek-added} αυτων[13:16]{.aside}

και ινα μη τις δυναται αγορασαι η [πωλησαι]{.greek-omitted} [πολησαι]{.greek-added} ει μη ο εχων το χαραγμα [και]{.greek-added} το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-omitted} [θηριου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο αριθμος αυτου εστιν εξακοσια εξηκοντα εξ[13:18]{.aside}

### Chapter 14

και ειδον και ιδου [το]{.greek-omitted} αρνιον [εστηκος]{.greek-omitted} [εστως]{.greek-added} επι το ορος σιων και μετ αυτου [αριθμος]{.greek-omitted} εκατον τεσσαρακοντα τεσσαρες χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλης και [η]{.greek-omitted} [φωνη]{.greek-omitted} [φωνην]{.greek-added} [ην]{.greek-omitted} ηκουσα [ως]{.greek-omitted} κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει μη αι εκατον τεσσαρακοντα τεσσαρες χιλιαδες οι [ηγορασμενοι]{.greek-omitted} [αγορασμενοι]{.greek-added} απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι [εισιν]{.greek-omitted} οι ακολουθουντες τω αρνιω οπου αν υπαγη ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} εν τω στοματι αυτων [ουχ]{.greek-added} [ευρεθη]{.greek-added} ψευδος αμωμοι [γαρ]{.greek-omitted} εισιν[14:5]{.aside}

και ειδον αγγελον πετομενον εν μεσουρανηματι εχοντα ευαγγελιον [αι]{.unclear}ωνιον ευαγγελισαι τους [καθημενους]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης και [επι]{.greek-omitted} παν εθνος και [φυλην]{.greek-omitted} [φιλην]{.greek-added} και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} και δοτε [[δωτε]{.corr}]{.greek-added} αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε [τω]{.greek-added} [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [ποιησαντι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και [την]{.greek-omitted} θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος [αγγελος]{.greek-added} δευτερος [αγγελος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων επεσεν [επεσε]{.greek-added} βαβυλων η μεγαλη εκ του οινου του θυμου [και]{.greek-added} της πορνειας αυτης [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις [λεγων]{.greek-omitted} εν φωνη μεγαλη [λεγων]{.greek-added} ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει χαραγμα επι του [μετωπου]{.greek-omitted} [μετοπου]{.greek-added} αυτου η επι την χειρα αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι και θειω ενωπιον [των]{.greek-omitted} [αγγελων]{.greek-added} αγιων [αγγελων]{.greek-omitted} και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις [αιωνας]{.greek-omitted} [αιωνα]{.greek-added} [αιωνων]{.greek-omitted} [αιωνος]{.greek-added} αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν [ωδε]{.greek-added} οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης [μοι]{.greek-added} γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} ινα [αναπαυσωνται]{.greek-omitted} [αναπαυσονται]{.greek-added} εκ των κοπων αυτων τα δε εργα [αυτων]{.greek-omitted} ακολουθει μετ αυτων[14:13]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην [καθημενον]{.greek-omitted} [καθημενος]{.greek-added} [ομοιον]{.greek-omitted} [ομοιος]{.greek-added} υιω [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του [ναου]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον [το]{.greek-omitted} [τον]{.greek-added} δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου [του]{.greek-omitted} [αυτου]{.greek-added} εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και [αγγελος]{.greek-added} αλλος [αγγελος]{.greek-omitted} [εξηλθεν]{.greek-omitted} [ηλθεν]{.greek-added} εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι ηκμασαν αι σταφυλαι αυτης[14:18]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις [την]{.greek-omitted} [τον]{.greek-added} ληνον [του]{.greek-omitted} [θυμου]{.greek-omitted} του [θεου]{.greek-abbr} τον μεγαν[14:19]{.aside}

και επατηθη η ληνος [εξωθεν]{.greek-omitted} [εξω]{.greek-added} της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των [χαλινων]{.greek-omitted} [χαληνων]{.greek-added} των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους επτα εχοντας πληγας επτα τας εσχατας οτι εν [αυταις]{.greek-omitted} [ταυταις]{.greek-added} ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ του θηριου και εκ της εικονος αυτου και εκ του [χαραγματος]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} [εκ]{.greek-added} [του]{.greek-added} αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην εχοντας κιθαρας του [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} του δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη φοβηθη [σε]{.greek-omitted} [κυριε]{.greek-omitted} και δοξαση το ονομα σου οτι [συ]{.greek-added} μονος [αγιος]{.greek-omitted} [οσιος]{.greek-added} οτι παντα τα εθνη [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου [[κυριε]{.greek-abbr}]{.greek-added} οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο ναος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-omitted} [ναω]{.greek-added}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας εκ του ναου [οι]{.greek-omitted} [ησαν]{.greek-omitted} ενδεδυμενοι λινον καθαρον λαμπρον [και]{.greek-omitted} [περιεζωσμενοι]{.greek-omitted} [περιεζωμενοι]{.greek-added} περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και [εν]{.greek-omitted} εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας γεμουσας [εκ]{.greek-added} του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των [επτα]{.greek-omitted} αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις υπαγετε [και]{.greek-omitted} εκχεατε τας [επτα]{.greek-omitted} φιαλας του θυμου [του]{.greek-omitted} [θεου]{.greek-omitted} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος [αγγελος]{.greek-added} και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην [αυτου]{.greek-omitted} [εις]{.greek-omitted} [αυτ[ης]{.unclear}]{.greek-added} [επι]{.greek-added} την γην και εγενετο ελκος κακον και πονηρον [επι]{.greek-omitted} [εις]{.greek-added} τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και [τους]{.greek-omitted} προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου [εις]{.greek-omitted} [επι]{.greek-added} την θαλασσαν και εγενετο [ως]{.greek-added} αιμα [ως]{.greek-omitted} νεκρου και πασα ψυχη ζωσα απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και [εις]{.greek-omitted} τας πηγας των υδατων [και]{.greek-omitted} [εγενετο]{.greek-omitted} [αιμα]{.greek-omitted}[16:4]{.aside}

[λεγων]{.greek-added} [και]{.greek-omitted} [ηκουσα]{.greek-omitted} [του]{.greek-omitted} [αγγελου]{.greek-omitted} [των]{.greek-omitted} [υδατων]{.greek-omitted} [λεγοντος]{.greek-omitted} δικαιος ει ο ων και ο ην [ο]{.greek-omitted} [και]{.greek-added} οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας [πιειν]{.greek-omitted} [ποιειν]{.greek-added} αξιοι εισιν[16:6]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και εδοθη αυτω καυματισαι [τους]{.greek-added} [[ανθρωπους]{.greek-abbr}]{.greek-added} εν πυρι [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} το ονομα του [θεου]{.greek-abbr} του εχοντος εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και εμασωντο τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και εκ των ελκων αυτων και ου μετενοησαν εκ των εργων [αυτων]{.greek-omitted}[16:11]{.aside}

και ο εκτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ποταμον τον μεγαν [ευφρατην]{.greek-omitted} [εφρατην]{.greek-added} και [εξηλανθη]{.greek-added} [εξηρανθη]{.corr} το υδωρ [αυτου]{.greek-omitted} ινα ετοιμασθη [το]{.greek-added} [υδωρ]{.greek-added} η οδος των βασιλεων των απο ανατολης ηλιου[16:12]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου [πνευματα]{.greek-abbr} [τρια]{.greek-added} ακαθαρτα [τρια]{.greek-omitted} [ως]{.greek-omitted} [βατραχοι]{.greek-omitted}[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ [πνευματα]{.greek-abbr} δαιμονιων ποιουντα σημεια [α]{.greek-omitted} [εκπορευεται]{.greek-omitted} [εκπορευεσθαι]{.greek-added} επι [τους]{.greek-omitted} [βασιλεις]{.greek-omitted} της οικουμενης ολης συναγαγειν αυτους εις [τον]{.greek-omitted} πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις τον τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἁρμαγεδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου [επι]{.greek-omitted} [εις]{.greek-added} τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη [εκ]{.greek-added} [μεγαλη]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added}[16:17]{.aside}

και εγενοντο αστραπαι και βρονται και [φωναι]{.greek-omitted} [και]{.greek-omitted} σεισμος [εγενετο]{.greek-added} μεγας οιος ουκ εγενετο αφ ου [οι]{.greek-omitted} [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων επεσον και βαβυλων η μεγαλη εμνησθη ενωπιον του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα [ν]{.unclear}ησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και [εβλασφημησαν]{.greek-omitted} [εβλασφημισαν]{.greek-added} οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των επτα αγγελων των εχοντων τας επτα φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων [[μοι]{.corr}]{.greek-added} δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι [των]{.greek-omitted} υδατων [των]{.greek-omitted} πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα [καθημενην]{.greek-omitted} [καθιμενην]{.greek-added} επι θηριον κοκκινον γεμον [ονοματα]{.greek-omitted} [ονοματων]{.greek-added} βλασφημιας εχον κεφαλας επτα και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἦν]{.greek-added} περιβεβλημενη [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον [κεχρυσωμενη]{.greek-omitted} [κεχρυσωμενην]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις εχουσα [χρυσον]{.greek-added} ποτηριον [χρυσουν]{.greek-omitted} εν τη χειρι αυτης γεμον βδελυγματων [και]{.greek-omitted} τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον [και]{.greek-added} βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν εκ του αιματος των αγιων [και]{.greek-added} εκ του αιματος των μαρτυρων [ιησου]{.greek-omitted} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος δια τι εθαυμασας εγω [σοι]{.greek-added} ερω [σοι]{.greek-omitted} το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας επτα κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και μελλει [αναβαινειν]{.greek-omitted} εκ της αβυσσου [αναβαινειν]{.greek-added} και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες επι της γης ων ου γεγραπται τα ονοματα επι [το]{.greek-omitted} βιβλιον της ζωης απο καταβολης κοσμου βλεποντων [το]{.greek-added} [θηριον]{.greek-added} οτι ην [το]{.greek-omitted} [θηριον]{.greek-omitted} και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και [παρεσται]{.greek-omitted} [παρεστιν]{.greek-added}[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι επτα κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [επτα]{.greek-added} [εισιν]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε επεσον ο εις εστιν ο αλλος ουπω [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και οταν ελθη ολιγον [αυτον]{.greek-added} δει [αυτον]{.greek-omitted} μειναι[17:10]{.aside}

και το θηριον ο ην [και]{.greek-omitted} ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και αυτος ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} και [αυτος]{.greek-added} εκ των επτα [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} γνωμην [εχουσι]{.greek-added} και την δυναμιν και την εξουσιαν αυτων τω θηριω διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει αυτους οτι [κυριος]{.greek-abbr} κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και [οι]{.greek-omitted} μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι [τα]{.greek-added} τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [γυμνην]{.greek-omitted} ποιησουσιν αυτην και τας σαρκας αυτης φαγονται και αυτην κατακαυσουσιν εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι [μιαν]{.greek-added} γνωμην [μιαν]{.greek-omitted} και δουναι την βασιλειαν αυτων τω θηριω αχρι [τελεσθωσιν]{.greek-omitted} [τελεσθησονται]{.greek-added} οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν [εν]{.greek-added} ισχυρα φωνη [μεγαλη]{.greek-added} λεγων επεσεν [επεσε]{.greek-added} βαβυλων η μεγαλη και εγενετο [κ]{.unclear}ατοικητηριον δαιμονων και φυλακη παντος πνευματος ακαθαρτου και [φυλακη]{.greek-omitted} [παντος]{.greek-omitted} [ορνεου]{.greek-omitted} [ακαθαρτου]{.greek-omitted} [και]{.greek-omitted} μεμισημενου[18:2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεποτηκε]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του στρηνους αυτης επλουτησαν[18:3]{.aside}

και ηκουσα [αλλην]{.greek-omitted} φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν [εξελθε]{.greek-omitted} [εξελθετε]{.greek-added} [εξ]{.greek-omitted} [αυτης]{.greek-omitted} [ο]{.greek-omitted} [λαος]{.greek-omitted} [λαοι]{.greek-added} μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης [και]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [πληγων]{.greek-omitted} [αυτης]{.greek-omitted} ινα μη λαβητε[18:4]{.aside}

οτι [εκολληθησαν]{.greek-omitted} [αυτης]{.greek-omitted} αι αμαρτιαι [αυτης]{.greek-added} [εκολληθησαν]{.greek-added} αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν [υμιν]{.greek-added} και διπλωσατε [αυτη]{.greek-omitted} [αυτην]{.greek-added} διπλα κατα τα εργα αυτης εν τω ποτηριω ω [εκερασεν]{.greek-omitted} [εκερασε]{.greek-added} κερασατε αυτη διπλουν[18:6]{.aside}

οσα εδοξασεν [αυτην]{.greek-omitted} [εαυτην]{.greek-added} και [εστρηνιασεν]{.greek-omitted} [εστρηνιασε]{.greek-added} τοσουτον δοτε [αυτη]{.greek-omitted} [αυτην]{.greek-added} βασανισμον [και]{.greek-omitted} [πενθος]{.greek-omitted} [οτι]{.greek-omitted} εν τη καρδια αυτης λεγει οτι καθημαι βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και κλαυσουσιν [αυτην]{.greek-added} και κοψονται επ [αυτην]{.greek-omitted} [αυτη]{.greek-added} οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες οταν [βλεπωσιν]{.greek-omitted} [βλεπουσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του βασανισμου αυτης λεγοντες [ουαι]{.greek-omitted} ουαι η πολις η μεγαλη βαβυλων η πολις η ισχυρα οτι μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαιουσι]{.greek-added} και [πενθησουσιν]{.greek-omitted} [πενθουσιν]{.greek-added} [επ]{.greek-omitted} [αυτη]{.greek-omitted} [εφ]{.greek-added} [εαυτους]{.greek-added} οτι τον γομον αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και μαργαριτου και [βυσσινου]{.greek-omitted} [βυσσου]{.greek-added} και [πορφυρου]{.greek-omitted} [πορφυρας]{.greek-added} και σηρικου και κοκκινου και παν ξυλον θυινον και παν [σκευος]{.greek-omitted} [ξυλον]{.greek-added} ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και [μαρμαρου]{.greek-omitted} [μαργαρου]{.greek-added}[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κινναμωμον]{.greek-added} και θυμιαματα και μυρον και λιβανον και οινον και ελαιον και σεμιδαλιν και σιτον και [κτινη]{.greek-added} [και]{.greek-added} προβατα [και]{.greek-omitted} [κτηνη]{.greek-omitted} [και]{.greek-omitted} [ιππων]{.greek-omitted} [και]{.greek-omitted} [ραιδων]{.greek-omitted} [και]{.greek-omitted} [σωματων]{.greek-omitted} και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και [τα]{.greek-omitted} λαμπρα [απωλετο]{.greek-omitted} [απηλθεν]{.greek-added} απο σου και ουκετι [αυτα]{.greek-omitted} ου μη [ευρης]{.greek-omitted} [ευρησεις]{.greek-added} [αυτα]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και [πενθουντες]{.greek-omitted}[18:15]{.aside}

[και]{.greek-omitted} λεγοντες ουαι ουαι η πολις η μεγαλη η περιβεβλημενη βυσσινον και πορφυρουν και κοκκινον [και]{.greek-omitted} κεχρυσωμενη [εν]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο [πλουτος]{.greek-added} [ο]{.greek-added} τοσουτος [πλουτος]{.greek-omitted} και πας κυβερνητης και πας [ο]{.greek-omitted} επι [τοπον]{.greek-omitted} [των]{.greek-added} [πλοιων]{.greek-added} πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και εκραζον βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη πολει τη μεγαλη[18:18]{.aside}

και [εβαλον]{.greek-omitted} [εβαλλον]{.greek-added} χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες και λεγοντες ουαι ουαι η πολις η μεγαλη εν η επλουτησαν παντες οι εχοντες [τα]{.greek-omitted} πλοια εν τη θαλασση εκ της τιμιοτητος αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} [ουρανε]{.greek-abbr} και οι αγιοι [και]{.greek-omitted} [οι]{.greek-omitted} αποστολοι [και]{.greek-omitted} [οι]{.greek-omitted} [προφηται]{.greek-omitted} οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και σαλπιστων ου μη ακουσθη εν σοι ετι και πας [τεχνιτης]{.greek-omitted} [τεχνητης]{.greek-added} πασης τεχνης ου μη ευρεθη εν σοι ετι [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [φανὴ]{.greek-added} εν σοι ετι και φωνη [μυλου]{.greek-added} [νυμφιου]{.greek-omitted} [και]{.greek-omitted} [νυμφης]{.greek-omitted} ου μη ακουσθη εν σοι ετι οτι οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν τη [φαρμακεια]{.greek-omitted} [φαρμακια]{.greek-added} σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν αυτη αιματα προφητων και αγιων ευρεθη και παντων των [εσφαγμενων]{.greek-omitted} [εσφαγμινων]{.greek-added} επι της γης[18:24]{.aside}

### Chapter 19

[και]{.greek-added} μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην [μεγαλην]{.greek-omitted} οχλου πολλου εν τω [ουρανω]{.greek-abbr} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλούια]{.greek-added} η [σωτηρια]{.greek-abbr} και η [δυναμις]{.greek-omitted} [δοξα]{.greek-added} και η [δοξα]{.greek-omitted} [δυναμις]{.greek-added} του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην [ητις]{.greek-omitted} [διεφθειρεν]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} εν τη πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ [της]{.greek-added} χειρος αυτης[19:2]{.aside}

και δευτερον [ειρηκεν]{.greek-omitted} [ειρηκασιν]{.greek-added} αλληλουια και ο καπνος [αυτης]{.greek-omitted} αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και επεσον οι πρεσβυτεροι οι εικοσι τεσσαρες και τα τεσσαρα ζωα και προσεκυνησαν τω [θεω]{.greek-abbr} τω καθημενω επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη [απο]{.greek-omitted} [εκ]{.greek-added} του θρονου εξηλθεν [λεγουσα]{.greek-omitted} αινειτε τον [θεον]{.greek-abbr} ημων παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα [ως]{.greek-omitted} [φωνην]{.greek-omitted} [οχλου]{.greek-omitted} [πολλου]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} φωνην υδατων πολλων και ως φωνην [βροντων]{.greek-omitted} [ισχυρων]{.greek-omitted} [υδατων]{.greek-added} [σφοδρων]{.greek-added} [λεγοντες]{.greek-omitted} [λεγοντος]{.greek-added} αλληλουια οτι εβασιλευσεν [κυριος]{.greek-omitted} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και [αγαλλιωμεθα]{.greek-omitted} [αγαλλιωμεν]{.greek-added} και [δωμεν]{.greek-omitted} [δωσωμεν]{.greek-added} την δοξαν αυτω οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα περιβαληται βυσσινον [καθαρον]{.greek-added} λαμπρον [και]{.greek-omitted} [καθαρον]{.greek-omitted} το γαρ βυσσινον τα δικαιωματα [εστι]{.greek-added} των αγιων [εστιν]{.greek-omitted}[19:8]{.aside}

και λεγει μοι [γραψον]{.greek-omitted} μακαριοι οι εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον του [γαμου]{.greek-omitted} [του]{.greek-omitted} αρνιου [κεκλημενοι]{.greek-omitted} [κληθεντες]{.greek-added} και λεγει μοι ουτοι οι λογοι [οι]{.greek-added} αληθινοι [εισι]{.greek-added} του [θεου]{.greek-abbr} [εισιν]{.greek-omitted}[19:9]{.aside}

και επεσα εμπροσθεν των ποδων αυτου [και]{.greek-added} [προσκυνησαι]{.greek-omitted} [προσεκυνησα]{.greek-added} αυτω και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} τω [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια του [ιησου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον [καλουμενος]{.greek-omitted} πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων [ονοματα]{.greek-omitted} [γεγραμμενα]{.greek-omitted} [και]{.greek-omitted} ονομα γεγραμμενον ο ουδεις οιδεν [ειμι]{.greek-added} [ει]{.greek-omitted} [μη]{.greek-omitted} αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον [βεβαμμενον]{.greek-omitted} [βεβαμενον]{.greek-added} [αιματι]{.greek-omitted} [υδατι]{.greek-added} και καλειται το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα [τα]{.greek-omitted} εν τω [ουρανω]{.greek-abbr} [ηκολουθει]{.greek-omitted} [ηκολουθουν]{.greek-added} αυτω [επι]{.greek-omitted} [εφ]{.greek-added} [ιπποις]{.greek-omitted} [ιπποι]{.greek-added} [λευκοις]{.greek-omitted} [πολλοι]{.greek-added} ενδεδυμενοι βυσσινον λευκον [και]{.greek-added} καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια [διστομος]{.greek-omitted} οξεια ινα εν αυτη παταξη τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα [και]{.greek-omitted} αυτος πατει την ληνον του οινου του θυμου [και]{.greek-added} της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και [επι]{.greek-omitted} τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και [κυριος]{.greek-abbr} κυριων[19:16]{.aside}

και ειδον αγγελον εστωτα εν τω ηλιω και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη [λεγων]{.greek-omitted} [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι δευτε [συναχθητε]{.greek-omitted} εις [το]{.greek-omitted} [τον]{.greek-added} δειπνον [το]{.greek-omitted} [μεγα]{.greek-omitted} του [μεγαλου]{.greek-added} [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων [και]{.greek-omitted} μικρων [τε]{.greek-omitted} και μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι πολεμον μετα του καθημενου επι του ιππου και [μετα]{.greek-omitted} του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον και [ο]{.greek-omitted} μετ αυτου [ο]{.greek-added} ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} [τους]{.greek-omitted} [λαβοντας]{.greek-omitted} το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες [εβληθησαν]{.greek-omitted} [βληθησονται]{.greek-added} οι δυο εις την λιμνην του πυρος [την]{.greek-omitted} [της]{.greek-added} [καιομενην]{.greek-omitted} [καιομενης]{.greek-added} εν [τω]{.greek-added} θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν τη ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την [κλειν]{.greek-omitted} [κλειδα]{.greek-added} της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον δρακοντα τον οφιν τον αρχαιον ος [εστιν]{.greek-omitted} [εστι]{.greek-added} διαβολος και [ο]{.greek-omitted} σατανας [ο]{.greek-omitted} [πλανων]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} [ολην]{.greek-omitted} και εδησεν αυτον χιλια ετη[20:2]{.aside}

[και]{.greek-omitted} [εβαλεν]{.greek-omitted} [αυτον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [αβυσσον]{.greek-omitted} [και]{.greek-omitted} [εκλεισεν]{.greek-omitted} [και]{.greek-omitted} [εσφραγισεν]{.greek-omitted} [επανω]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [μη]{.greek-omitted} [πλανα]{.greek-omitted} [ετι]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [αχρι]{.greek-omitted} [τελεσθη]{.greek-omitted} [τα]{.greek-omitted} [χιλια]{.greek-omitted} [ετη]{.greek-omitted} και μετα ταυτα δει αυτον [λυθηναι]{.greek-omitted} [κλυθηναι]{.greek-added} μικρον χρονον[20:3]{.aside}

και ειδον θρονους [και]{.greek-omitted} [αι]{.greek-added} εκαθισαν επ αυτους και κριμα εδοθη αυτοις και τας ψυχας των πεπελεκισμενων δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} και οιτινες ου προσεκυνησαν το [θηριον]{.greek-omitted} [[τω]{.corr}]{.greek-added} [θηριω]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [εικονα]{.greek-omitted} [εικονι]{.greek-added} αυτου και ουκ ελαβον [το]{.greek-omitted} χαραγμα επι το μετωπον [αυτων]{.greek-added} και επι την χειρα αυτων και εζησαν και εβασιλευσαν μετα [του]{.greek-omitted} [χριστου]{.greek-abbr} [τα]{.greek-omitted} χιλια ετη[20:4]{.aside}

και οι λοιποι των νεκρων ουκ εζησαν αχρι τελεσθη τα χιλια ετη αυτη [η]{.greek-omitted} αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν τη αναστασει τη πρωτη [επι]{.greek-omitted} [επει]{.greek-added} τουτων ο [θανατος]{.greek-added} [ο]{.greek-added} δευτερος [θανατος]{.greek-omitted} ουκ εχει εξουσιαν αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου χιλια ετη[20:6]{.aside}

και οταν τελεσθη τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη [τα]{.greek-omitted} εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης τον γωγ και τον μαγωγ [και]{.greek-added} συναγαγειν αυτους εις [τον]{.greek-omitted} πολεμον ων ο αριθμος [ωσει]{.greek-added} [ως]{.greek-omitted} [η]{.greek-omitted} αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και εκυκλωσαν την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ εκ [[θεου]{.greek-abbr}]{.greek-added} [απο]{.greek-added} του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} και κατεφαγεν αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και [θειου]{.greek-omitted} [θυιου]{.greek-added} οπου [και]{.greek-omitted} το θηριον [και]{.greek-omitted} ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [των]{.greek-omitted} [αιωνων]{.greek-omitted}[20:10]{.aside}

και ειδον θρονον [λευκον]{.greek-added} μεγαν [λευκον]{.greek-omitted} και τον καθημενον επ αυτον ου απο προσωπου εφυγεν [η]{.greek-omitted} [και]{.greek-added} γη και ο [ουρανος]{.greek-abbr} και τοπος ουχ ευρεθη αυτοις[20:11]{.aside}

και ειδον τους νεκρους τους μεγαλους και τους μικρους εστωτας ενωπιον του θρονου και βιβλια [ηνεωχθησαν]{.greek-omitted} [ανεωχθησαν]{.greek-added} και αλλο βιβλιον [ηνεωχθη]{.greek-omitted} [ανεωχθη]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} της ζωης και εκριθησαν οι νεκροι εκ των γεγραμμενων εν τοις βιβλιοις κατα τα εργα αυτων[20:12]{.aside}

και εδωκεν η θαλασσα τους [νεκρους]{.greek-omitted} [τους]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [αδης]{.greek-omitted} [εδωκαν]{.greek-omitted} [τους]{.greek-omitted} [νεκρους]{.greek-omitted} [τους]{.greek-omitted} εν αυτοις [νεκρους]{.greek-added} και εκριθησαν εκαστος κατα τα εργα αυτων[20:13]{.aside}

[και]{.greek-omitted} ο θανατος και ο αδης εβληθησαν εις την λιμνην του πυρος [ουτος]{.greek-omitted} [ο]{.greek-omitted} [θανατος]{.greek-omitted} [ο]{.greek-omitted} [δευτερος]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [λιμνη]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted}[20:14]{.aside}

και ει τις ουχ ευρεθη εν [τω]{.greek-omitted} [τη]{.greek-added} [βιβλιω]{.greek-omitted} [βιβλω]{.greek-added} της ζωης γεγραμμενος εβληθη εις την λιμνην του πυρος[20:15]{.aside}

### Chapter 21

και ειδον [ουρανον]{.greek-abbr} καινον και γην καινην ο γαρ πρωτος [ουρανος]{.greek-abbr} και η πρωτη γη [απηλθον]{.greek-omitted} [παρηλθε]{.greek-added} και η θαλασσα ουκ εστιν ετι[21:1]{.aside}

και την πολιν την αγιαν [ιερουσαλημ]{.greek-abbr} καινην ειδον καταβαινουσαν [απο]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} εκ του [ουρανου]{.greek-abbr} [απο]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} ητοιμασμενην ως νυμφην κεκοσμημενην τω ανδρι αυτης[21:2]{.aside}

και ηκουσα φωνης μεγαλης εκ του [ουρανου]{.greek-abbr} λεγουσης ιδου η σκηνη του [θεου]{.greek-abbr} μετα των [ανθρωπων]{.greek-abbr} και σκηνωσει μετ αυτων και αυτοι [λαος]{.greek-omitted} [λαοι]{.greek-added} αυτου εσονται και αυτος ο [θεος]{.greek-abbr} εσται μετ αυτων [[θεος]{.greek-abbr}]{.greek-added} [αυτων]{.greek-added}[21:3]{.aside}

και εξαλειψει παν δακρυον απο των οφθαλμων αυτων και ο θανατος ουκ εσται ετι ουτε πενθος ουτε κραυγη ουτε πονος ουκ εσται ετι [οτι]{.greek-omitted} τα πρωτα απηλθον[21:4]{.aside}

και ειπεν ο καθημενος επι τω θρονω ιδου [καινο]{.greek-added} [ποιω]{.greek-added} παντα [καινα]{.greek-omitted} [ποιω]{.greek-omitted} και λεγει μοι γραψον οτι ουτοι οι λογοι αληθινοι και πιστοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[21:5]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι γεγονα [εγω]{.greek-added} το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} [η]{.greek-omitted} αρχη και [το]{.greek-omitted} τελος εγω τω διψωντι δωσω εκ της πηγης του υδατος της ζωης δωρεαν[21:6]{.aside}

ο νικων κληρονομησει ταυτα και εσομαι [αυτω]{.greek-omitted} [αυτων]{.greek-added} [θεος]{.greek-abbr} και [αυτος]{.greek-omitted} [αυτοι]{.greek-added} [εσται]{.greek-omitted} [εσονται]{.greek-added} μοι [υιος]{.greek-omitted} [υιοι]{.greek-added}[21:7]{.aside}

τοις δε [δειλοις]{.greek-omitted} [δηλοις]{.greek-added} και απιστοις [και]{.greek-omitted} [αμαρτωλοις]{.greek-omitted} [και]{.greek-omitted} εβδελυγμενοις και [φονευσιν]{.greek-omitted} [φονευουσι]{.greek-added} και πορνοις και φαρμακοις και ειδωλολατραις και [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις [ψευδεσιν]{.greek-omitted} [ψευδεσι]{.greek-added} το μερος αυτων εν τη λιμνη τη καιομενη πυρι και [θειω]{.greek-omitted} [θυιω]{.greek-added} ο εστιν ο [δευτερος]{.greek-added} θανατος [ο]{.greek-omitted} [δευτερος]{.greek-omitted}[21:8]{.aside}

και ηλθεν εις [εκ]{.greek-omitted} των επτα αγγελων των εχοντων τας επτα φιαλας [γεμουσας]{.greek-omitted} [των]{.greek-added} [γεμοντων]{.greek-added} των επτα πληγων των εσχατων και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι την [γυναικα]{.greek-omitted} [την]{.greek-omitted} νυμφην του αρνιου [την]{.greek-added} [γυναικα]{.greek-added}[21:9]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εν [πνευματι]{.greek-abbr} επ ορος μεγα [και]{.greek-omitted} υψηλον και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι την πολιν την μεγαλην [την]{.greek-omitted} [και]{.greek-added} αγιαν [ιερουσαλημ]{.greek-abbr} καταβαινουσαν εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-abbr}[21:10]{.aside}

εχουσαν την δοξαν του [θεου]{.greek-abbr} ο φωστηρ αυτης ομοιος λιθω τιμιωτατω [ως]{.greek-omitted} [λιθω]{.greek-omitted} ιασπιδι [κρυσταλλιζοντι]{.greek-omitted} [κρυσταλιζοντι]{.greek-added}[21:11]{.aside}

εχουσα τειχος μεγα και υψηλον εχουσα πυλωνας δωδεκα και επι τοις πυλωσιν αγγελους δωδεκα και ονοματα επιγεγραμμενα α [εστιν]{.greek-omitted} [εστι]{.greek-added} [ονοματα]{.greek-omitted} των δωδεκα [φυλων]{.greek-omitted} [φιλων]{.greek-added} [του]{.greek-added} [των]{.greek-omitted} [υιων]{.greek-omitted} [ισραηλ]{.greek-abbr}[21:12]{.aside}

[απο]{.greek-omitted} [απ]{.greek-added} [ανατολων]{.greek-omitted} [ανατολης]{.greek-added} πυλωνες τρεις [και]{.greek-omitted} απο βορρα πυλωνες τρεις [και]{.greek-omitted} απο νοτου πυλωνες τρεις [και]{.greek-omitted} απο δυσμων πυλωνες τρεις[21:13]{.aside}

και [το]{.greek-omitted} τειχος της πολεως εχον θεμελιους δωδεκα και επ αυτων δωδεκα ονοματα των δωδεκα αποστολων του αρνιου[21:14]{.aside}

και ο λαλων μετ εμου ειχεν [μετρον]{.greek-omitted} καλαμον χρυσουν ινα μετρηση την πολιν και τους πυλωνας αυτης και το τειχος αυτης[21:15]{.aside}

και η πολις τετραγωνος κειται και το μηκος αυτης [οσον]{.greek-omitted} [και]{.greek-added} το πλατος και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} την πολιν [εν]{.greek-added} τω καλαμω επι [σταδιους]{.greek-omitted} [σταδιων]{.greek-added} δωδεκα χιλιαδων [δωδεκα]{.greek-omitted} το μηκος και το πλατος και το υψος αυτης ισα εστιν[21:16]{.aside}

και [εμετρησεν]{.greek-omitted} [εμετρησε]{.greek-added} το τειχος αυτης εκατον τεσσαρακοντα τεσσαρων πηχων μετρον [ανθρωπου]{.greek-abbr} ο εστιν αγγελου[21:17]{.aside}

και ην η ενδομησις του τειχους αυτης ιασπις και η πολις χρυσιον καθαρον [ομοιον]{.greek-omitted} [ομοια]{.greek-added} [υελω]{.greek-omitted} [υαλω]{.greek-added} καθαρω[21:18]{.aside}

[και]{.greek-added} οι θεμελιοι του τειχους [οι]{.greek-added} της πολεως παντι λιθω τιμιω κεκοσμημενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος σαπφειρος ο τριτος χαλκηδων ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος σαρδονυξ ο εκτος [σαρδιον]{.greek-omitted} [σαρδιος]{.greek-added} ο εβδομος χρυσολιθος ο ογδοος [βηρυλλος]{.greek-omitted} [βουριλλιος]{.greek-added} ο [ενατος]{.greek-omitted} [εννατος]{.greek-added} [τοπαζιον]{.greek-omitted} [παζιον]{.greek-added} ο δεκατος χρυσοπρασος ο ενδεκατος υακινθος ο δωδεκατος αμεθυσος[21:20]{.aside}

και οι δωδεκα πυλωνες δωδεκα μαργαριται ανα εις εκαστος των [πυλωνων]{.greek-omitted} [πυλων]{.greek-added} ην εξ ενος μαργαριτου και η πλατεια της πολεως χρυσιον καθαρον ως [υελος]{.greek-omitted} [υαλος]{.greek-added} διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν αυτη ο γαρ [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

και η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινωσιν αυτη η γαρ δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχνος αυτης το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φωτος αυτης και οι βασιλεις της γης [φερουσιν]{.greek-omitted} [φερουσι]{.greek-added} [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν [και]{.greek-omitted} [τιμην]{.greek-omitted} [των]{.greek-omitted} [αυτων]{.greek-added} [εθνων]{.greek-omitted} εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην των εθνων εις αυτην[21:26]{.aside}

και ου μη [εισελθη]{.greek-omitted} [εισελθοι]{.greek-added} εις αυτην παν κοινον και ποιουν βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον καθαρον υδατος ζωης λαμπρον ως [κρυσταλλον]{.greek-omitted} [κρυσταλον]{.greek-added} εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της [πλατειας]{.greek-omitted} [πολιτειας]{.greek-added} αυτης και του ποταμου εντευθεν και [εκειθεν]{.greek-omitted} [ενταθεν]{.greek-added} ξυλον ζωης ποιουν καρπους δωδεκα κατα μηνα [ενα]{.greek-added} εκαστον αποδιδους τον καρπον αυτου και τα φυλλα του ξυλου εις θεραπειαν των εθνων[22:2]{.aside}

και παν καταθεμα ουκ εσται [ετι]{.greek-omitted} [εκει]{.greek-added} και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν αυτη εσται και οι δουλοι αυτου [λατρευσουσιν]{.greek-omitted} [λατρευουσιν]{.greek-added} αυτω[22:3]{.aside}

και οψονται το προσωπον αυτου και το ονομα αυτου επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[22:4]{.aside}

και νυξ ουκ εσται εκει και χρειαν ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} λυχνου και φωτος ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [φωτιει]{.greek-omitted} [φωτισει]{.greek-added} αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

και [λεγει]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι οι λογοι [οι]{.greek-added} πιστοι και αληθινοι [και]{.greek-omitted} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} των [αγιων]{.greek-added} [πνευματων]{.greek-omitted} [των]{.greek-omitted} προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

[και]{.greek-omitted} ιδου ερχομαι ταχυ μακαριος ο τηρων τους λογους της προφητειας [ταυτης]{.greek-added} [του]{.greek-omitted} [βιβλιου]{.greek-omitted} [τουτου]{.greek-omitted}[22:7]{.aside}

[καγω]{.greek-omitted} [και]{.greek-added} [εγω]{.greek-added} ιωαννης ο [βλεπων]{.greek-added} [και]{.greek-added} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} ταυτα και οτε ηκουσα [ταυτα]{.greek-added} και εβλεψα [επεσον]{.greek-omitted} [επεσα]{.greek-added} προσκυνησαι εμπροσθεν των ποδων του αγγελου του δεικνυοντος μοι ταυτα[22:8]{.aside}

και λεγει [μοι]{.greek-omitted} ορα μη συνδουλος σου ειμι και των αδελφων σου των προφητων [και]{.greek-omitted} των τηρουντων τους λογους του βιβλιου τουτου τω [θεω]{.greek-abbr} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου [οτι]{.greek-added} ο καιρος [γαρ]{.greek-omitted} εγγυς εστιν[22:10]{.aside}

ο αδικων αδικησατω ετι και ο [ρυπαρος]{.greek-omitted} [ρυπαρευθητω]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} δικαιος δικαιοσυνην [ποιησατω]{.greek-omitted} [ποιειτω]{.greek-added} ετι και ο αγιος αγιασθητω ετι[22:11]{.aside}

[και]{.greek-added} ιδου ερχομαι ταχυ και ο μισθος μου μετ εμου αποδουναι εκαστω ως το εργον [αυτου]{.greek-added} εσται [αυτου]{.greek-omitted}[22:12]{.aside}

εγω το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} ο πρωτος και ο εσχατος [η]{.greek-omitted} [αρχη]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [τελος]{.greek-omitted}[22:13]{.aside}

μακαριοι οι ποιουντες τας εντολας αυτου ινα εσται η εξουσια αυτων επι [το]{.greek-omitted} [του]{.greek-added} [ξυλον]{.greek-omitted} [ξυλου]{.greek-added} της ζωης και τοις [πυλωσιν]{.greek-omitted} [πυλεωσιν]{.greek-added} εισελθωσιν εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμακοι και οι [πορνοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} φονεις και οι ειδωλολατραι και πας [ο]{.greek-added} φιλων [το]{.greek-added} [και]{.greek-omitted} [ποιων]{.greek-omitted} ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησαι [υμιν]{.greek-omitted} ταυτα [επι]{.greek-omitted} ταις εκκλησιαις εγω ειμι η ριζα και το γενος [δαυιδ]{.greek-abbr} [και]{.greek-added} ο αστηρ ο [λαμπρος]{.greek-omitted} [ο]{.greek-omitted} πρωινος[22:16]{.aside}

και το [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν ερχου και ο ακουων ειπατω ερχου και ο διψων ερχεσθω ο θελων λαβετω υδωρ ζωης δωρεαν[22:17]{.aside}

μαρτυρω εγω παντι [τω]{.greek-omitted} ακουοντι τους λογους της προφητειας του βιβλιου τουτου εαν τις επιθη επ [αυτα]{.greek-omitted} [αυτω]{.greek-added} [επιθησαι]{.greek-omitted} [επιθησει]{.greek-added} [επ]{.greek-added} [αυτον]{.greek-added} ο [θεος]{.greek-abbr} [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας [επτα]{.greek-added} πληγας τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και εαν τις αφελη [απο]{.greek-omitted} [των]{.greek-omitted} [λογων]{.greek-omitted} [του]{.greek-omitted} [βιβλιου]{.greek-omitted} [της]{.greek-omitted} [προφητειας]{.greek-omitted} [ταυτης]{.greek-omitted} [αφελοι]{.greek-omitted} [αφελει]{.greek-added} ο [θεος]{.greek-abbr} το μερος αυτου απο του ξυλου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν τω βιβλιω τουτω[22:19]{.aside}

λεγει ο μαρτυρων ταυτα [ναι]{.greek-omitted} [ερχομαι]{.greek-omitted} [ανερχομαι]{.greek-added} ταχυ αμην [ναι]{.greek-omitted} ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added}[22:20]{.aside}

η χαρις του [κυριου]{.greek-abbr} [ημων]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων αμην[22:21]{.aside}

