---
title: "Collation of Byz^RP^ vs 32188 (2188)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2188 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32188).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2188                                   	| λογος                              	|
| 2188 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2188 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2188               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2188                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2188 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2188                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 12

η [ποιησατε]{.greek-omitted} [ποιησαται]{.greek-added} το δενδρον καλον και τον καρπον αυτου καλον η [ποιησατε]{.greek-omitted} [ποιησαται]{.greek-added} το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου το δενδρον [γινωσκεται]{.greek-omitted} [γνωριζεται]{.greek-added}[12:33]{.aside}

γεννηματα εχιδνων πως [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} αγαθα λαλειν πονηροι οντες εκ γαρ του περισσευματος της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου εκβαλλει αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου εκβαλλει πονηρα[12:35]{.aside}

λεγω [δε]{.greek-omitted} υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσωσιν]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

[και]{.greek-added} [γαρ]{.greek-added} εκ [γαρ]{.greek-omitted} των λογων σου [δικαιωθηση]{.greek-omitted} [δικαιωθησει]{.greek-added} και εκ των λογων σου [καταδικασθηση]{.greek-omitted} [κατακριθησει]{.greek-added}[12:37]{.aside}

τοτε απεκριθησαν τινες των γραμματεων [και]{.greek-omitted} [φαρισαιων]{.greek-omitted} [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} διδασκαλε θελομεν απο σου σημειον ιδειν[12:38]{.aside}

[αποκριθεις]{.greek-added} [δε]{.greek-added} ο [[ιησους]{.greek-abbr}]{.greek-added} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} ειπεν αυτοις γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ [γαρ]{.greek-omitted} ην [ο]{.greek-added} ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας [ουτως]{.greek-omitted} [εσται]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [καρδια]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [τρεις]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [τρεις]{.greek-omitted} [νυκτας]{.greek-omitted}[12:40]{.aside}

ανδρες νινευιται αναστησονται εν τη κρισει μετα της [γενεας]{.greek-omitted} [γεναιας]{.greek-added} ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

[βασιλισσα]{.greek-omitted} [βασιλεισσα]{.greek-added} νοτου [εγερθησεται]{.greek-omitted} [ευρεθησεται]{.greek-added} εν τη κρισει μετα της γενεας ταυτης και κατακρινει αυτην οτι ηλθεν εκ των περατων της γης ακουσαι την σοφιαν [σολομωνος]{.greek-omitted} [σολομωντος]{.greek-added} και ιδου πλειον [σολομωνος]{.greek-omitted} [σολομωντος]{.greek-added} ωδε[12:42]{.aside}

οταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} [διερχεται]{.greek-omitted} [πορευεται]{.greek-added} [δι]{.greek-omitted} [δια]{.greek-added} ανυδρων [τοπων]{.greek-omitted} ζητουν αναπαυσιν και ουχ ευρισκει[12:43]{.aside}

τοτε λεγει επιστρεψω εις τον οικον μου οθεν εξηλθον και ελθον ευρισκει σχολαζοντα [και]{.greek-added} σεσαρωμενον [και]{.greek-omitted} [κεκοσμημενον]{.greek-omitted}[12:44]{.aside}

τοτε πορευεται και [παραλαμβανει]{.greek-omitted} [λαμβανει]{.greek-added} μεθ εαυτου επτα ετερα [πνευματα]{.greek-abbr} πονηροτερα εαυτου και εισελθοντα [κατοικει]{.greek-omitted} [κατικει]{.greek-added} εκει και γινεται τα εσχατα [το]{.unclear}υ [ανθρωπου]{.greek-abbr} εκεινου [χειρονα]{.greek-omitted} [χειρωνα]{.greek-added} των [πρωτων]{.greek-omitted} [προτων]{.greek-added} ουτως εσται και [εν]{.greek-added} τη γενεα ταυτη τη πονηρα[12:45]{.aside}

ετι [δε]{.greek-omitted} αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} και οι αδελφοι αυτου ειστηκεισαν εξω ζητουντες [αυτω]{.greek-omitted} [αυτου]{.greek-added} λαλησαι[12:46]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου εξω [εστηκασιν]{.greek-omitted} [ειστικασιν]{.greek-added} ζητουντες σοι λαλησαι[12:47]{.aside}

ο δε αποκριθεις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω ειποντι αυτω τις εστιν [η]{.greek-omitted} [μητηρ]{.greek-abbr} μου και τινες εισιν οι αδελφοι μου[12:48]{.aside}

και εκτεινας την χειρα [αυτου]{.greek-omitted} [επι]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} αυτου ειπεν ιδου η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[12:49]{.aside}

[οστις]{.greek-omitted} [ωστις]{.greek-added} γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr} αυτος μου αδελφος και [αδελφη]{.greek-omitted} [αδελφοι]{.greek-added} και [μητηρ]{.greek-abbr} εστιν[12:50]{.aside}

### Chapter 17

[και]{.greek-omitted} [ιδου]{.greek-omitted} [ωφθησαν]{.greek-omitted} [αυτοις]{.greek-omitted} [μωσης]{.greek-omitted} [και]{.greek-omitted} ηλιας μετ αυτου συλλαλουντες[17:3]{.aside}

αποκριθεις δε ο πετρος [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τω [ιησου]{.greek-abbr} [κυριε]{.greek-abbr} καλον εστιν ημας ωδε ειναι ει θελεις [ποιησωμεν]{.greek-omitted} [ποιησομεν]{.greek-added} ωδε τρεις σκηνας σοι μιαν και μωση μιαν και μιαν [ηλια]{.greek-omitted} [ηλιαν]{.greek-added}[17:4]{.aside}

ετι αυτου λαλουντος ιδου νεφελη φωτεινη επεσκιασεν αυτους και ιδου φωνη εκ της νεφελης λεγουσα ουτος εστιν ο υιος μου ο αγαπητος εν ω [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added} αυτου ακουετε[17:5]{.aside}

και ακουσαντες οι μαθηται επεσον επι προσωπον αυτων και εφοβηθησαν σφοδρα[17:6]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ηψατο αυτων και ειπεν [εγερθητε]{.greek-omitted} [εγερθηται]{.greek-added} και μη [φοβεισθε]{.greek-omitted} [φοβησθε]{.greek-added}[17:7]{.aside}

επαραντες δε τους οφθαλμους αυτων ουδενα ειδον ει [μη]{.greek-omitted} [μι]{.greek-added} τον [ιησουν]{.greek-abbr} μονον[17:8]{.aside}

και καταβαινοντων αυτων εκ του ορους ενετειλατ[ο]{.greek-supplied} αυτοις ο [ιησους]{.greek-abbr} λεγων μηδενι [ειπητε]{.greek-omitted} [ειπηται]{.greek-added} το οραμα εως ου ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων [α]{.unclear}ναστη[17:9]{.aside}

και [επηρωτησαν]{.greek-omitted} [επερωτησαν]{.greek-added} αυτον οι μαθηται αυτου λεγοντες τι ουν οι γραμματεις λεγουσιν οτι ηλιαν δει ελθειν πρωτον[17:10]{.aside}

ο δε [ιησους]{.greek-omitted} αποκριθεις ειπεν αυτοις ηλιας μεν ερχεται [πρωτον]{.greek-omitted} [πρωτος]{.greek-added} και αποκαταστησει [ημιν]{.greek-added} παντα[17:11]{.aside}

λεγω δε υμιν οτι ηλιας [ηδη]{.greek-omitted} [ηδει]{.greek-added} ηλθεν και ουκ επεγνωσαν αυτον αλλα εποιησαν εν [αυτω]{.greek-omitted} [αυτοις]{.greek-added} οσα ηθελησαν ουτως και ο υιος του [ανθρωπου]{.greek-abbr} μελλει πασχειν υπ αυτων[17:12]{.aside}

τοτε συνηκαν οι μαθηται οτι περι [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου ειπεν αυτοις[17:13]{.aside}

και ελθοντων [αυτων]{.greek-omitted} [αυτον]{.greek-added} προς τον οχλον προσηλθεν αυτω ανθρωπος γονυπετων [αυτον]{.greek-omitted} [αυτω]{.greek-added}[17:14]{.aside}

και λεγων [κυριε]{.greek-abbr} ελεησον μου τον υιον οτι σεληνιαζεται [και]{.greek-omitted} κακως π[ασχει]{.greek-supplied} πολλακις γαρ πιπτει εις το πυρ και πολλακις εις το υδωρ[17:15]{.aside}

και προσηνεγκα αυτον τοις μαθηταις σου και ουκ ηδυνηθησαν [θεραπευσαι]{.greek-added} αυτον [θεραπευσαι]{.greek-omitted}[17:16]{.aside}

αποκριθεις [δε]{.greek-omitted} ο [ιησους]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} ειπεν ω γενεα απιστος και διεστραμμενη εως ποτε [εσομαι]{.greek-omitted} [μεθ]{.greek-omitted} [υμων]{.greek-omitted} [εως]{.greek-omitted} [ποτε]{.greek-omitted} ανεξομαι [υμων]{.greek-omitted} [ημων]{.greek-added} [φερετε]{.greek-omitted} [φερε]{.greek-added} [μοι]{.greek-omitted} αυτον [ωδε]{.greek-omitted} [οδε]{.greek-added}[17:17]{.aside}

και επετιμησεν [αυτω]{.greek-omitted} [αυτον]{.greek-added} ο [ιησους]{.greek-abbr} και εξηλθεν απ αυτου το δαιμονιον και εθεραπευθη ο παις απο της ωρας εκεινης[17:18]{.aside}

τοτε [προσελθοντες]{.greek-omitted} [π[ρ]{.unclear}[οση]{.greek-supplied}[λ]{.unclear}θον]{.greek-added} οι μαθηται τω [ιησου]{.greek-abbr} κατ ιδιαν ειπον δια τι ημεις ουκ ηδυνηθημεν εκβαλειν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[17:19]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις δια την απιστιαν υμων αμην [γαρ]{.greek-omitted} λεγω υμιν εαν [εχητε]{.greek-omitted} [εχεται]{.greek-added} πιστιν ως [κοκκον]{.greek-omitted} [κοκον]{.greek-added} σιναπεως ερειτε τω ορει [τουτω]{.greek-omitted} [τουτο]{.greek-added} μεταβηθι εντευθεν εκει [και]{.greek-omitted} μεταβησεται και ουδεν αδυνατησει υμιν[17:20]{.aside}

τουτο δε το γενος ουκ εκπορευεται ει μη εν προσευχη και [νηστεια]{.greek-omitted} [νιστεια]{.greek-added}[17:21]{.aside}

[αναστρεφομενων]{.greek-omitted} [αναστραφομενων]{.greek-added} δε αυτων [εν]{.greek-omitted} [εις]{.greek-added} [τη]{.greek-omitted} [την]{.greek-added} [γαλιλαια]{.greek-omitted} [γαλιλαιαν]{.greek-added} ειπεν αυτοις ο [ιησους]{.greek-abbr} μελλει [παραδιδοσθαι]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} [παραδιδοσθαι]{.greek-omitted} εις χειρας [ανθρωπων]{.greek-abbr}[17:22]{.aside}

και αποκτενουσιν αυτον και τη τριτη ημερα [εγερθησεται]{.greek-omitted} [εγερθησονται]{.greek-added} και ελυπηθησαν σφοδρα[17:23]{.aside}

ελθοντων [δε]{.greek-omitted} αυτων εις καπερναουμ προσηλθον οι τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added} λαμβανοντες τω πετρω και [ειπον]{.greek-omitted} [ειπων]{.greek-added} ο διδασκαλος υμων ου τελει τα [διδραχμα]{.greek-omitted} [διδραγμα]{.greek-added}[17:24]{.aside}

[λεγει]{.greek-omitted} [ναι]{.greek-omitted} και οτε εισηλθεν εις την οικιαν προεφθασεν [αυτον]{.greek-omitted} [αυτω]{.greek-added} ο [ιησους]{.greek-abbr} λεγων τι σοι δοκει σιμων οι βασιλεις της γης απο [τινων]{.greek-omitted} [τινος]{.greek-added} λαμβανουσιν τελη η κηνσον απο των υιων αυτων η απο των αλλοτριων[17:25]{.aside}

[λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [απο]{.greek-omitted} [των]{.greek-omitted} [αλλοτριων]{.greek-omitted} εφη αυτω ο [ιησους]{.greek-abbr} αρα γε ελευθεροι εισιν οι υιοι[17:26]{.aside}

ινα δε μη σκανδαλισωμεν αυτους πορευθεις εις [την]{.greek-omitted} θαλασσαν βαλε αγκιστρον και τον [αναβαινοντα]{.greek-omitted} [αναβαντα]{.greek-added} πρωτον ιχθυν αρον και ανοιξας το στομα αυτου [ευρησεις]{.greek-omitted} [ευρισεις]{.greek-added} στατηρα εκεινον λαβων δος αυτοις αντι εμου και σου[17:27]{.aside}

### Chapter 18

εν εκεινη τη ωρα προσηλθον οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες τις αρα μειζων [εστιν]{.greek-omitted} εν τη βασιλεια των [ουρανων]{.greek-abbr}[18:1]{.aside}

και προσκαλεσαμενος ο [ιησους]{.greek-abbr} παιδιον εστησεν αυτο εν μεσω αυτων[18:2]{.aside}

και ειπεν αμην λεγω υμιν εαν μη στραφητε και γενησθε ως τα παιδια ου μη εισελθητε εις την βασιλειαν των [ουρανων]{.greek-abbr}[18:3]{.aside}

και ος εαν δεξηται παιδιον [τοιουτον]{.greek-omitted} [τοιουτο]{.greek-added} [εν]{.greek-omitted} επι τω ονοματι μου εμε δεχεται[18:5]{.aside}

ος δ αν [σκανδαλιση]{.greek-omitted} [σκανδαλισει]{.greek-added} ενα των μικρων τουτων των πιστευοντων εις εμε συμφερει αυτω ινα κρεμασθη μυλος ονικος εις τον τραχηλον αυτου και καταποντισθη εν τω πελαγει της θαλασσης[18:6]{.aside}

ουαι τω κοσμω απο των σκανδαλων αναγκη γαρ εστιν ελθειν τα σκανδαλα πλην ουαι τω [ανθρωπω]{.greek-abbr} εκεινω δι ου το σκανδαλον ερχεται[18:7]{.aside}

[ει]{.greek-omitted} [ι]{.greek-added} δε η χειρ σου [η]{.greek-omitted} [ο]{.greek-omitted} [πους]{.greek-omitted} [σου]{.greek-omitted} σκανδαλιζει σε εκκοψον [αυτα]{.greek-omitted} [αυτην]{.greek-added} και [βαλε]{.greek-omitted} [εκβαλε]{.greek-added} απο σου καλον σοι εστιν [εισελθειν]{.greek-omitted} [ελθειν]{.greek-added} εις την ζωην χωλον η [κυλλον]{.greek-omitted} [κυλον]{.greek-added} η δυο χειρας [εχοντα]{.greek-added} η δυο ποδας [εχοντα]{.greek-omitted} βληθηναι εις το πυρ το αιωνιον [το]{.greek-added} [εξοτερον]{.greek-added}[18:8]{.aside}

και [ε]{.unclear}ι [ο]{.greek-omitted} οφθαλμος σου σκανδαλιζει σε εξελε αυτον και [βαλε]{.greek-omitted} [εκβαλλε]{.greek-added} απο σου καλον σοι εστιν μονοφθαλμον [εισελθειν]{.greek-added} εις την [ζωην]{.greek-omitted} [εισελθειν]{.greek-omitted} [βασιλειαν]{.greek-added} [των]{.greek-added} [[ουονων]{.greek-abbr}]{.greek-added} η δυο οφθαλμους εχοντα βληθηναι εις την [γεενναν]{.greek-omitted} [γεεναν]{.greek-added} του πυρος[18:9]{.aside}

ορατε μη καταφρονησητε ενος των μικρων τουτων λεγω γαρ υμιν οτι οι αγγελοι αυτων εν [ουρανοις]{.greek-abbr} δια παντος βλεπουσιν το προσωπον του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:10]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ ο υιος του [ανθρωπου]{.greek-abbr} σωσαι το απολωλος[18:11]{.aside}

τι υμιν δοκει εαν γενηται τινι [ανθρωπω]{.greek-abbr} [εκατον]{.greek-omitted} [[ρ]{.greek-abbr}]{.greek-added} προβατα και πλανηθη εν εξ αυτων ουχι αφεις τα [[ϙθ]{.greek-abbr}]{.greek-added} [ενενηκοντα]{.greek-omitted} [εννεα]{.greek-omitted} επι τα ορη πορευθεις ζητει το πλανωμενον[18:12]{.aside}

και εαν γενηται ευρειν αυτο αμην λεγω υμιν [οτι]{.greek-omitted} χαιρει επ [αυτω]{.greek-omitted} [αυτο]{.greek-added} μαλλον η επι τοις [[ϙθ]{.greek-abbr}]{.greek-added} [ενενηκοντα]{.greek-omitted} [εννεα]{.greek-omitted} τοις μη πεπλανημενοις[18:13]{.aside}

ουτως ουκ εστιν θελημα εμπροσθεν του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} του εν [τοις]{.greek-added} [ουρανοις]{.greek-abbr} ινα αποληται εις των μικρων τουτων[18:14]{.aside}

εαν δε αμαρτηση εις σε ο αδελφος σου υπαγε [και]{.greek-omitted} ελεγξον [αυ]{.unclear}τον μεταξυ σου και αυτου μονου εαν σου [ακουση]{.greek-omitted} [ακουσει]{.greek-added} εκερδησας τον αδελφον σου[18:15]{.aside}

εαν δε μη ακουση [σου]{.greek-added} παραλαβε μετα σου ετι ενα η δυο ινα επι [στοματος]{.greek-omitted} [στοματι]{.greek-added} δυο μαρτυρων η τριων σταθη παν [το]{.greek-added} ρημα[18:16]{.aside}

εαν δε [αυτων]{.greek-added} παρακουση [αυτων]{.greek-omitted} ειπε τη εκκλησια εαν δε και της εκκλησιας παρακουση εστω σοι ωσπερ ο εθνικος και ο τελωνης[18:17]{.aside}

αμην λεγω υμιν οσα εαν [δησητε]{.greek-omitted} [δησειται]{.greek-added} επι της γης εσται δεδεμενα εν τω [ουρανω]{.greek-abbr} και οσα εαν λυσητε επι της γης εσται λελυμενα εν τω [ουρανω]{.greek-abbr}[18:18]{.aside}

παλιν αμην λεγω υμιν οτι εαν δυο [υμων]{.greek-omitted} συμφωνησωσιν επι της γης περι παντος πραγματος ου εαν [αιτησωνται]{.greek-omitted} [αιτισονται]{.greek-added} γενησεται αυτοις παρα του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[18:19]{.aside}

τοτε προσελθων αυτω ο πετρος ειπεν [κυριε]{.greek-abbr} ποσακις [εαν]{.greek-added} [αμαρτησει]{.greek-omitted} [αμ[αρ]{.unclear}τησεις]{.greek-added} [εις]{.greek-omitted} [[αμ[αρ]{.unclear}τησης]{.corr}]{.greek-added} [σε]{.greek-added} εμε ο αδελφος μου και αφησω [αυτω]{.greek-omitted} [αυτον]{.greek-added} εως επτακις[18:21]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} ου λεγω σοι εως επτακις αλλ εως [εβδομηκοντακις]{.greek-omitted} [ευδομικοντακις]{.greek-added} [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added}[18:22]{.aside}

δια τουτο ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-omitted} βασιλει ος ηθελησεν συναραι λογον μετα των δουλων αυτου[18:23]{.aside}

αρξαμενου δε αυτου συναιρειν [προσηνεχθη]{.greek-omitted} [προσσυνεχθη]{.greek-added} αυτω εις οφειλετης μυριων ταλαντων[18:24]{.aside}

μη εχοντος δε αυτου αποδουναι εκελευσεν αυτον ο [κυριος]{.greek-abbr} αυτου [πραθηναι]{.greek-omitted} [πραχθηναι]{.greek-added} και την γυναικα αυτου [και]{.unclear} τα τεκνα και παντα οσα [ειχεν]{.greek-omitted} [ει[χε]{.unclear}]{.greek-added} και [αποδοθηναι]{.greek-omitted} [αποδουναι]{.greek-added}[18:25]{.aside}

πεσων ουν ο δουλος [προσεκυνει]{.greek-omitted} [προσεκεινη]{.greek-added} αυτω λεγων [κυριε]{.greek-abbr} μακροθυμησον επ εμοι και παντα σοι [αποδωσω]{.greek-omitted} [δωσω]{.greek-added}[18:26]{.aside}

σπλαγχνισθεις δε ο [κυριος]{.greek-abbr} του δουλου εκεινου απελυσεν αυτον και το δανειον [αφηκεν]{.greek-omitted} [αυτω]{.greek-omitted} [αυτο]{.greek-added}[18:27]{.aside}

εξελθων δε ο δουλος [εκεινος]{.greek-omitted} ευρεν ενα των συνδουλων αυτου [ος]{.greek-omitted} [ως]{.greek-added} [ωφειλεν]{.greek-omitted} [οφειλεν]{.greek-added} αυτω [εκατον]{.greek-omitted} [[ρ]{.greek-abbr}]{.greek-added} δηναρια και κρατησας αυτον επνιγεν λεγων [αποδος]{.greek-omitted} [αποδως]{.greek-added} μοι ει τι οφειλεις[18:28]{.aside}

πεσων [ουν]{.greek-omitted} ο συνδουλος αυτου εις τους ποδας αυτου παρεκαλει αυτον λεγων μακροθυμησον επ εμοι και αποδωσω σοι[18:29]{.aside}

ο δε ουκ ηθελεν αλλα απελθων εβαλεν [αυτον]{.greek-omitted} εις φυλακην εως ου αποδω το οφειλομενον[18:30]{.aside}

[ιδοντες]{.greek-omitted} [ιδωντες]{.greek-added} δε οι συνδουλοι [αυτου]{.greek-omitted} τα γενομενα [ελυπηθησαν]{.greek-omitted} [σφοδρα]{.greek-omitted} [και]{.greek-omitted} [ελθοντες]{.greek-omitted} [διεσαφησαν]{.greek-omitted} [τω]{.greek-omitted} [κυριω]{.greek-omitted} [εαυτων]{.greek-omitted} [παντα]{.greek-omitted} [τα]{.greek-omitted} [γενομενα]{.greek-omitted}[18:31]{.aside}

[ιδοντες]{.greek-omitted} [δε]{.greek-omitted} [οι]{.greek-omitted} [συνδουλοι]{.greek-omitted} [αυτου]{.greek-omitted} [τα]{.greek-omitted} [γενομενα]{.greek-omitted} ελυπηθησαν σφοδρα [λεγωντες]{.greek-added} και [ελθοντες]{.greek-omitted} διεσαφησαν τω [κυριω]{.greek-abbr} εαυτων [παντα]{.greek-omitted} τα γενομενα [παντα]{.greek-added}[18:31 | instance no. 2]{.aside}

τοτε προσκαλεσαμενος αυτον ο [κυριος]{.greek-abbr} αυτου λεγει [αυτω]{.greek-omitted} δουλε πονηρε πασαν την οφειλην εκεινην αφηκα σοι [επει]{.greek-omitted} [παρεκαλεσας]{.greek-omitted} [με]{.greek-omitted}[18:32]{.aside}

ουκ εδει και σε ελεησαι τον συνδουλον σου ως [καγω]{.greek-added} [και]{.corr} [εγω]{.corr} σε ηλεησα[18:33]{.aside}

και οργισθεις ο [κυριος]{.greek-abbr} αυτου [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} [αυτον]{.greek-omitted} τοις βασανισταις εως ου αποδω [παν]{.greek-omitted} το οφειλομενον αυτω[18:34]{.aside}

ουτως [και]{.greek-omitted} ο [πατηρ]{.greek-abbr} μου ο [επουρανιος]{.greek-abbr} ποιησει [υμιν]{.greek-omitted} [ημιν]{.greek-added} εαν μη [αφητε]{.greek-omitted} [αφηται]{.greek-added} εκαστος τω αδελφω αυτου απο των καρδιων [υμων]{.greek-omitted} [ημων]{.greek-added} τα παραπτωματα αυτων[18:35]{.aside}

### Chapter 19

και εγενετο οτε [ετελεσεν]{.greek-omitted} [συνετελεσεν]{.greek-added} ο [ιησους]{.greek-abbr} τους λογους τουτους μετηρεν απο της γαλιλαιας και ηλθεν εις τα ορια της ιουδαιας περαν του ιορδανου[19:1]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους εκει[19:2]{.aside}

και [προσηλθον]{.greek-omitted} [προσηλθαν]{.greek-added} αυτω οι φαρισαιοι πειραζοντες αυτον και λεγοντες αυτω ει εξεστιν [ανθρωπω]{.greek-omitted} απολυσαι την γυναικα αυτου κατα πασαν [αιτιαν]{.greek-omitted}[19:3]{.aside}

ο δε αποκριθεις ειπεν αυτοις ουκ ανεγνωτε οτι ο ποιησας [αυτους]{.greek-added} απ αρχης αρσεν και [θηλυ]{.greek-omitted} [θυλυ]{.greek-added} εποιησεν αυτους[19:4]{.aside}

και ειπεν ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} και την [μητερα]{.greek-abbr} και [προσκολληθησεται]{.greek-omitted} [κολυθησεται]{.greek-added} τη γυναικι αυτου και εσονται οι δυο εις σαρκα μιαν[19:5]{.aside}

[ωστε]{.greek-omitted} [ουκετι]{.greek-omitted} [εισιν]{.greek-omitted} [δυο]{.greek-omitted} [αλλα]{.greek-omitted} [σαρξ]{.greek-omitted} [μια]{.greek-omitted} ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη [χωριζετω]{.greek-omitted} [χωριζετο]{.greek-added}[19:6]{.aside}

λεγουσιν αυτω τι ουν μωσης ενετειλατο δουναι βιβλιον αποστασιου και απολυσαι αυτην[19:7]{.aside}

λεγει αυτοις οτι μωσης προς την σκληροκαρδιαν υμων επετρεψεν υμιν απολυσαι τας γυναικας [υμων]{.greek-omitted} [ημων]{.greek-added} απ αρχης δε ου [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} ουτως[19:8]{.aside}

λεγω δε υμιν [ως]{.greek-added} [οτι]{.greek-omitted} [ος]{.greek-omitted} αν [απολυση]{.greek-omitted} [απολυσει]{.greek-added} την γυναικα αυτου μη επι [πορνεια]{.greek-omitted} [πορνειαν]{.greek-added} και [γαμηση]{.greek-omitted} [γαμισει]{.greek-added} αλλην [μοιχαται]{.greek-omitted} [μοιχατε]{.greek-added} [και]{.greek-omitted} [ο]{.greek-omitted} [απολελυμενην]{.greek-omitted} [γαμησας]{.greek-omitted} [μοιχαται]{.greek-omitted}[19:9]{.aside}

λεγουσιν αυτω οι μαθηται αυτου ει [ουτως]{.greek-omitted} [ουτος]{.greek-added} εστιν η αιτια του [ανθρωπου]{.greek-abbr} μετα της γυναικος ου συμφερει [γαμησαι]{.greek-omitted} [γαμισαι]{.greek-added}[19:10]{.aside}

ο δε ειπεν αυτοις ου παντες χωρουσιν τον λογον [τουτον]{.greek-omitted} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} αλλ οις [δεδοται]{.greek-omitted} [δεδωται]{.greek-added}[19:11]{.aside}

[εισιν]{.greek-omitted} [γαρ]{.greek-omitted} [ευνουχοι]{.greek-omitted} [οιτινες]{.greek-omitted} [εκ]{.greek-omitted} [κοιλιας]{.greek-omitted} [μητρος]{.greek-omitted} [εγεννηθησαν]{.greek-omitted} [ουτως]{.greek-omitted} [και]{.greek-omitted} εισιν ευνουχοι οιτινες ευνουχισθησαν υπο των [ανθρωπων]{.greek-abbr} [και]{.greek-added} [εισιν]{.greek-added} [ευνουχοι]{.greek-added} [οι]{.greek-added} [εκ]{.greek-added} [κοιλιας]{.greek-added} [[μητρος]{.greek-abbr}]{.greek-added} [εγεννηθησαν]{.greek-added} [ουτως]{.greek-added} και εισιν ευνουχοι οιτινες ευνουχισαν εαυτους δια την βασιλειαν των [ουρανων]{.greek-abbr} ο δυναμενος [χωρειν]{.greek-omitted} [χορειν]{.greek-added} [χωρειτω]{.greek-omitted} [χοριτω]{.greek-added}[19:12]{.aside}

τοτε προσηνεχθη αυτω παιδια ινα τας χειρας [επιθη]{.greek-omitted} [επιθει]{.greek-added} αυτοις και προσευξηται [και]{.greek-added} οι [δε]{.greek-omitted} μαθηται επετιμησαν [αυτοις]{.greek-omitted}[19:13]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αφετε]{.greek-omitted} [αφεται]{.greek-added} τα παιδια [και]{.greek-omitted} μη [κωλυετε]{.greek-omitted} [κολυεται]{.greek-added} αυτα ελθειν προς με των γαρ τοιουτων εστιν η βασιλεια των [ουρανων]{.greek-abbr}[19:14]{.aside}

και επιθεις αυτοις τας χειρας επορευθη εκειθεν[19:15]{.aside}

και ιδου εις προσελθων ειπεν αυτω διδασκαλε αγαθε τι αγαθον ποιησω ινα εχω ζωην αιωνιον[19:16]{.aside}

ο δε ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr} [η]{.greek-added} [θελης]{.greek-added} [ει]{.greek-omitted} [δε]{.greek-omitted} [θελεις]{.greek-omitted} εισελθειν εις την ζωην τηρησον τας εντολας[19:17]{.aside}

λεγει αυτω ποιας ο δε [ιησους]{.greek-abbr} ειπεν το ου φονευσεις ου μοιχευσεις ου κλεψεις ου ψευδομαρτυρησεις[19:18]{.aside}

τιμα τον [πατερα]{.greek-abbr} [σου]{.greek-added} και την [μητερα]{.greek-abbr} [σου]{.greek-added} και αγα[πη]{.unclear}σεις [τ]{.unclear}ον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[19:19]{.aside}

[ταυτα]{.greek-added} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [νεανισκος]{.greek-omitted} παντα [ταυτα]{.greek-omitted} εφυλαξαμην εκ νεοτητος μου τι ετι υστερω[19:20]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} ει θελεις τελειος ειναι [υπαγε]{.greek-omitted} πωλησον σου τα υπαρχοντα και δος πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} και [δευρο]{.greek-omitted} [δευρω]{.greek-added} ακολουθει μοι[19:21]{.aside}

ακουσας δε ο νεανισκος τον λογον απηλθεν λυπουμενος ην γαρ εχων [κτηματα]{.greek-omitted} [κτιματα]{.greek-added} πολλα[19:22]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου αμην λεγω υμιν οτι [δυσκολως]{.greek-omitted} [δυσκολος]{.greek-added} πλουσιος εισελευσεται εις την βασιλειαν των [ουρανων]{.greek-abbr}[19:23]{.aside}

παλιν δε λεγω υμιν [ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} εστιν [καμηλον]{.greek-omitted} [καμιλον]{.greek-added} δια [ραφιδος]{.greek-added} τρυπηματος [ραφιδος]{.greek-omitted} διελθειν η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[19:24]{.aside}

ακουσαντες δε οι μαθηται αυτου εξεπλησσοντο σφοδρα λεγοντες τις αρα δυναται σωθηναι[19:25]{.aside}

εμβλεψας δε ο [ιησους]{.greek-abbr} ειπεν αυτοις παρα [ανθρωποις]{.greek-abbr} τουτο αδυνατον [εστιν]{.greek-omitted} παρα δε [θεω]{.greek-abbr} παντα δυνατα[19:26]{.aside}

τοτε αποκριθεις ο πετρος ειπεν αυτω [ιδου]{.greek-omitted} ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι τι αρα εσται ημιν[19:27]{.aside}

[αποκριθεις]{.greek-added} [δε]{.greek-added} ο [[κυριος]{.greek-abbr}]{.greek-added} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτοις αμην λεγω υμιν οτι υμεις οι ακολουθησαντες μοι εν τη παλιγγενεσια οταν [καθιση]{.greek-omitted} [καθισει]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} επι θρονου δοξης αυτου [καθισεσθε]{.greek-omitted} [και]{.greek-omitted} [υμεις]{.greek-omitted} [επι]{.greek-omitted} [δωδεκα]{.greek-omitted} [θρονους]{.greek-omitted} [κρινοντες]{.greek-omitted} [τας]{.greek-omitted} [δωδεκα]{.greek-omitted} [φυλας]{.greek-omitted} [του]{.greek-omitted} [ισραηλ]{.greek-omitted}[19:28]{.aside}

[καθησεσθαι]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [υμεις]{.greek-omitted} [οι]{.greek-omitted} [ακολουθησαντες]{.greek-omitted} [μοι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [παλιγγενεσια]{.greek-omitted} [οταν]{.greek-omitted} [καθιση]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [επι]{.greek-omitted} [θρονου]{.greek-omitted} [δοξης]{.greek-omitted} [αυτου]{.greek-omitted} [καθισεσθε]{.greek-omitted} και υμεις επι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} θρονους κρινοντες τας [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} φυλας του [ισραηλ]{.greek-abbr}[19:28 | instance no. 2]{.aside}

και πας [ος]{.greek-omitted} [οστις]{.greek-added} αφηκεν [οικιας]{.greek-omitted} [οικειας]{.greek-added} η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν του ονοματος μου εκατονταπλασιονα ληψεται και ζωην αιωνιον κληρονομησει[19:29]{.aside}

πολλοι δε εσονται πρωτοι [εσχατοι]{.greek-omitted} [αισχατοι]{.greek-added} και [οι]{.greek-added} εσχατοι πρωτοι[19:30]{.aside}

### Chapter 20

ομοια γαρ [εστιν]{.greek-omitted} [φησιν]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} οικοδεσποτη οστις εξηλθεν αμα πρωι μισθωσασθαι εργατας εις τον αμπελωνα αυτου[20:1]{.aside}

[και]{.greek-omitted} συμφωνησας [[δε]{.unclear}]{.greek-added} μετα των εργατων εκ δηναριου την ημεραν απεστειλεν αυτους εις τον αμπελωνα αυτου[20:2]{.aside}

και εξελθων περι [τριτην]{.greek-omitted} [[γ]{.greek-abbr}]{.greek-added} ωραν ειδεν αλλους εστωτας εν τη αγορα αργους[20:3]{.aside}

και εκεινοις ειπεν υπαγετε και υμεις εις τον αμπελωνα [μου]{.greek-added} και ο εαν η δικαιον δωσω υμιν[20:4]{.aside}

οι δε απηλθον παλιν [δε]{.greek-added} εξελθων περι [εκτην]{.greek-omitted} [[ϛ]{.greek-abbr}]{.greek-added} [ωραν]{.greek-added} και [[θ]{.greek-abbr}]{.greek-added} [ενατην]{.greek-omitted} [ωραν]{.greek-omitted} εποιησεν ωσαυτως[20:5]{.aside}

περι δε την [ενδεκατην]{.greek-omitted} [[ια]{.greek-abbr}]{.greek-added} ωραν εξελθων ευρεν αλλους εστωτας αργους και λεγει αυτοις τι ωδε [εστηκατε]{.greek-omitted} [εστικατε]{.greek-added} ολην την ημεραν αργοι[20:6]{.aside}

λεγουσιν αυτω οτι ουδεις ημας εμισθωσατο λεγει αυτοις [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} και υμεις εις τον αμπελωνα [μου]{.greek-added} και ο [εαν]{.greek-omitted} [εν]{.greek-added} η δικαιον [ληψεσθε]{.greek-omitted} [ληψεσθαι]{.greek-added}[20:7]{.aside}

οψιας δε γενομενης λεγει ο [κυριος]{.greek-abbr} του αμπελωνος τω επιτροπω αυτου καλεσον τους εργατας και αποδος αυτοις τον μισθον αρξαμενος απο των [εσχατων]{.greek-omitted} [αισχατων]{.greek-added} εως των πρωτων[20:8]{.aside}

και [ελθοντες]{.greek-omitted} [ελθωντες]{.greek-added} οι περι την ενδεκατην ωραν [ελαβον]{.greek-omitted} [ελαβων]{.greek-added} ανα δηναριον[20:9]{.aside}

[ελθοντες]{.greek-omitted} [ελθοντων]{.greek-added} [δε]{.greek-omitted} [οι]{.greek-omitted} [πρωτοι]{.greek-omitted} [ενομισαν]{.greek-omitted} [οτι]{.greek-omitted} [πλειονα]{.greek-omitted} [ληψονται]{.greek-omitted} [και]{.greek-omitted} [ελαβον]{.greek-omitted} [και]{.greek-omitted} [αυτοι]{.greek-omitted} [ανα]{.greek-omitted} [δηναριον]{.greek-omitted}[20:10]{.aside}

[ελθοντες]{.greek-omitted} δε [και]{.greek-added} οι πρωτοι [ενομισαν]{.greek-omitted} [ενομησαν]{.greek-added} οτι [πλειονα]{.greek-omitted} [πλειον]{.greek-added} ληψονται και [ελαβον]{.greek-omitted} [ελαβων]{.greek-added} [και]{.greek-omitted} αυτοι ανα [δηναριον]{.greek-omitted} [δηναριου]{.greek-added}[20:10 | instance no. 2]{.aside}

λαβοντες δε εγογγυζον κατα του οικοδεσποτου[20:11]{.aside}

λεγοντες οτι [ουτοι]{.greek-omitted} οι εσχατοι μιαν ωραν εποιησαν και ισους ημιν αυτους εποιησας τοις βαστασασιν το βαρος της ημερας και τον καυσωνα[20:12]{.aside}

ο δε αποκριθεις ειπεν ενι αυτων [εταιρε]{.greek-omitted} [ετερε]{.greek-added} ουκ αδικω σε ουχι δηναριου συνεφωνησας μοι[20:13]{.aside}

αρον το σον και υπαγε θελω δε [και]{.greek-added} [τουτω]{.greek-omitted} [τουτο]{.greek-added} τω εσχατω [[αισχατω]{.corr}]{.greek-added} δουναι ως και σοι[20:14]{.aside}

[η]{.greek-omitted} [ει]{.greek-added} ουκ [εξεστιν]{.greek-omitted} [εξεστοι]{.greek-added} μοι ποιησαι ο θελω εν [τοις]{.greek-omitted} [εμοις]{.greek-omitted} [το]{.greek-added} [εμω]{.greek-added} ει [ο]{.greek-omitted} οφθ[αλ]{.unclear}μος σου πονηρος εστιν οτι [εγω]{.greek-omitted} αγαθος ειμι[20:15]{.aside}

ουτως εσονται οι [εσχατοι]{.greek-omitted} [αισχατοι]{.greek-added} πρωτοι και οι πρωτοι [εσχατοι]{.greek-omitted} [αισχατοι]{.greek-added} πολ[λοι]{.greek-supplied} [γαρ]{.greek-supplied} [ει]{.unclear}σιν κλητοι ολιγοι δε εκλεκτοι[20:16]{.aside}

τοτε προσηλθεν [αυτω]{.greek-omitted} η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου μετα των υιων αυτης προσκυνουσα και [αιτουσα]{.greek-omitted} [ε[τουσα]{.unclear}]{.greek-added} [τι]{.greek-omitted} παρ αυτου[20:20]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτη τι θελεις λεγει αυτω ειπε ινα καθισωσιν ουτοι οι δυο [μου]{.greek-added} υιοι [μου]{.greek-omitted} εις εκ δεξιων σου και εις εξ ευωνυμων σου [καθησωσιν]{.greek-added} εν τη βασιλεια σου[20:21]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-added} ουκ [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} τι [αιτεισθε]{.greek-omitted} [αιτισθε]{.greek-added} δυνασθε [πιειν]{.greek-omitted} [ποιειν]{.greek-added} το ποτηριον ο εγω μελλω πινειν [η]{.greek-omitted} [και]{.greek-added} το βαπτισμα ο εγω [βαπτιζομαι]{.greek-omitted} [βαπτισθησομαι]{.greek-added} βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

και λεγει αυτοις το μεν ποτηριον μου πιεσθε και το βαπτισμα ο εγω βαπτιζομαι [βαπτισθησεσθε]{.greek-omitted} [βαπτισθησεσθαι]{.greek-added} το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και εξ ευωνυμων μου ουκ εστιν [εμον]{.greek-omitted} [εμων]{.greek-added} δουναι αλλ οις ητοιμασται [υπο]{.greek-omitted} [παρα]{.greek-added} του [πατρος]{.greek-abbr} μου[20:23]{.aside}

και ακουσαντες οι δεκα [ηγανακτησαν]{.greek-omitted} [ηγανακτισαν]{.greek-added} περι των δυο αδελφων[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους ειπεν [οιδατε]{.greek-omitted} [ιδετε]{.greek-added} οτι οι αρχοντες των εθνων κατακυριευουσιν [αυτων]{.greek-omitted} [αυτον]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [μεγαλοι]{.greek-omitted} [κατεξουσιαζουσιν]{.greek-omitted} [αυτων]{.greek-omitted}[20:25]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ [ος]{.greek-omitted} [ως]{.greek-added} εαν θελη εν υμιν [μεγας]{.greek-omitted} [γενεσθαι]{.greek-omitted} [εσται]{.greek-omitted} [υμων]{.greek-omitted} [διακονος]{.greek-omitted}[20:26]{.aside}

[και]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [θελη]{.greek-omitted} [εν]{.greek-omitted} [υμιν]{.greek-omitted} ειναι πρωτος εστω υμων δουλος[20:27]{.aside}

ωσπερ ο υιος του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

και [εκπορευομενων]{.greek-omitted} [εκπορευομενου]{.greek-added} [αυτων]{.greek-omitted} [αυτου]{.greek-added} απο ιεριχω [ηκολουθησεν]{.greek-omitted} [ηκολουθ[η]{.unclear}σαν]{.greek-added} αυτω οχλος πολυς[20:29]{.aside}

και ιδου δυο τυφλοι [καθημενοι]{.greek-omitted} παρα την οδον [καθημενοι]{.greek-added} ακουσαντες οτι [ιησους]{.greek-abbr} [παραγει]{.greek-omitted} [παραγινεται]{.greek-added} εκραξαν [λεγοντες]{.greek-omitted} [λεγων]{.greek-added} ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

και στας ο [ιησους]{.greek-omitted} [[κυριος]{.greek-abbr}]{.greek-added} εφωνησεν αυτους και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε ποιησω [υμιν]{.greek-omitted} [ημιν]{.greek-added}[20:32]{.aside}

λεγουσιν αυτω [κυριε]{.greek-abbr} ινα ανοιχθωσιν ημων οι οφθαλμοι[20:33]{.aside}

σπλαγχνισθεις [δε]{.greek-omitted} ο [ιησους]{.greek-abbr} ηψατο των οφθαλμων αυτων και ευθεως ανεβλεψαν αυτων οι οφθαλμοι και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

και οτε [ηγγισαν]{.greek-omitted} [ηγγισεν]{.greek-added} εις ιεροσολυμα και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις βηθσφαγη προς το ορος των ελαιων τοτε [ο]{.greek-omitted} [ιησους]{.greek-abbr} απεστειλεν δυο μαθητας[21:1]{.aside}

λεγων [αυτοις]{.greek-omitted} [αυτους]{.greek-added} [πορευθητε]{.greek-omitted} [πορευθηται]{.greek-added} εις [την]{.greek-omitted} [τον]{.greek-added} κωμην την απεναντι υμων και ευθεως [ευρησετε]{.greek-omitted} [ευρισηται]{.greek-added} ονον δεδεμενην και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν [ειπη]{.greek-omitted} [ειπει]{.greek-added} τι [ερειτε]{.greek-omitted} [ερειται]{.greek-added} [αυτω]{.greek-added} οτι ο [κυριος]{.greek-abbr} αυτων χρειαν εχει ευθεως δε [αποστελλει]{.greek-omitted} [αποστελει]{.greek-added} αυτους[21:3]{.aside}

τουτο δε ολον [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

[ειπατε]{.greek-omitted} [ειπαται]{.greek-added} τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι [πραυς]{.greek-omitted} [πραις]{.greek-added} και επιβεβηκως επι ονον και [επι]{.greek-added} πωλον υιον υποζυγιου[21:5]{.aside}

πορευθεντες δε οι μαθηται και ποιησαντες [καθως]{.greek-omitted} [καθος]{.greek-added} προσεταξεν αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον την ονον και [τον]{.greek-omitted} [την]{.greek-added} πωλον και επεθηκαν επανω αυτων τα ιματια [αυτων]{.greek-omitted} [εαυτων]{.greek-added} και [επεκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} επανω αυτων[21:7]{.aside}

ο δε πλειστος οχλος εστρωσαν εαυτων τα ιματια εν τη οδω αλλοι δε [εκοπτον]{.greek-omitted} [εκοπτων]{.greek-added} κλαδους απο των δενδρων και [εστρωννυον]{.greek-omitted} [εστρωνιον]{.greek-added} εν τη οδω[21:8]{.aside}

οι δε οχλοι οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} ωσαννα εν τοις υψιστοις[21:9]{.aside}

και εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον [ουτος]{.greek-omitted} [εστιν]{.greek-omitted} [ιησους]{.greek-omitted} [ο]{.greek-omitted} [προφητης]{.greek-omitted} [ο]{.greek-omitted} [απο]{.greek-omitted} [ναζαρετ]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted}[21:11]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [οχλοι]{.greek-omitted} [ελεγον]{.greek-omitted} ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11 | instance no. 2]{.aside}

και εισηλθεν [ο]{.greek-omitted} [ιησους]{.greek-omitted} εις το ιερον του [θεου]{.greek-abbr} και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} παντας τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβηστων]{.greek-added} κατεστρεψεν και τας [καθεδρας]{.greek-omitted} [τραπεζας]{.greek-added} των [πωλουντων]{.greek-omitted} [πoλουντων]{.greek-added} τας περιστερας[21:12]{.aside}

και λεγει αυτοις γεγραπται [οτι]{.greek-added} ο οικος μου οικος προσευχης κληθησεται υμεις δε [εποιησατε]{.greek-added} αυτον [εποιησατε]{.greek-omitted} σπηλαιον ληστων[21:13]{.aside}

και προσηλθον [αυτω]{.greek-omitted} [εαυτω]{.greek-added} [χωλοι]{.greek-omitted} [χολοι]{.greek-added} και τυφλοι εν τω ιερω και εθεραπευσεν [αυτους]{.greek-omitted} [εαυτους]{.greek-added}[21:14]{.aside}

ιδοντες [δε]{.greek-omitted} οι αρχιερεις και οι γραμματεις τα θαυμασια α εποιησεν και τους παιδας [κραζοντας]{.greek-omitted} [κραζωντα[ς]{.unclear}]{.greek-added} [εν]{.unclear} τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-abbr} [ηγανακτησαν]{.greek-omitted} [ηγανακτισαν]{.greek-added}[21:15]{.aside}

και ειπον αυτω [ακουεις]{.greek-omitted} [ακουης]{.greek-added} τι ουτοι λεγουσιν ο [δε]{.greek-supplied} [ιησους]{.greek-abbr} [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις ναι ουδεποτε [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} οτι εκ στοματος νηπιων και θηλαζοντων κατηρτισω αινον[21:16]{.aside}

και [καταλιπων]{.greek-omitted} [καταλοιπων]{.greek-added} αυτους [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} εξω της πολεως εις βηθανιαν και [ηυλισθη]{.greek-omitted} [ηυλισ[η]{.unclear}]{.greek-added} [[ηυλισθον]{.corr}]{.greek-added} [[ηυλισθαν]{.corr}]{.greek-added} εκει[21:17]{.aside}

πρωιας δε επαναγων εις την πολιν [επεινασεν]{.greek-omitted} [επινασεν]{.greek-added}[21:18]{.aside}

και ιδων συκην μιαν επι της οδου ηλθεν επ αυτην και ουδεν ευρεν εν αυτη ει [μη]{.greek-omitted} [μι]{.greek-added} φυλλα μ[ο]{.unclear}νον και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και εξηρανθη παραχρημα η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν λεγοντες πως παραχρημα εξηρανθη η συκη[21:20]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις αμην λεγω υμιν εαν [εχητε]{.greek-omitted} [εχεται]{.greek-added} πιστιν και μη [διακριθητε]{.greek-omitted} [διακριθηται]{.greek-added} ου μονον το της συκης [ποιησετε]{.greek-omitted} [ποιησεται]{.greek-added} αλλα καν [τω]{.greek-omitted} [ορει]{.greek-omitted} [το]{.greek-added} [ορη]{.greek-added} [τουτω]{.greek-omitted} [τουτο]{.greek-added} [ειπητε]{.greek-omitted} [ειπηται]{.greek-added} αρθητι και βληθητι εις την θαλασσαν γενησεται[21:21]{.aside}

[κα]{.unclear}ι παντα οσα [εαν]{.greek-omitted} [αν]{.greek-added} [αιτησητε]{.greek-omitted} [αιτησηται]{.greek-added} εν τη προσευχη πιστευοντες ληψεσθε[21:22]{.aside}

και [ελθοντι]{.greek-omitted} [ελθοντος]{.greek-added} [αυτω]{.greek-omitted} εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου [λεγοντες]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιεις]{.greek-omitted} και [ειπων]{.greek-added} [τις]{.greek-omitted} [τι]{.greek-added} σοι εδωκεν την εξουσιαν ταυτην[21:23]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις ερωτησω [υμας]{.greek-omitted} [ημας]{.greek-added} καγω λογον ενα ον εαν [ειπητε]{.greek-omitted} [ειπειται]{.greek-added} μοι καγω υμιν ερω εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ποθεν [ην]{.greek-omitted} [ουν]{.greek-added} εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο [παρ]{.greek-omitted} [εν]{.greek-added} εαυτοις λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} [ερει]{.greek-omitted} [ερρει]{.greek-added} ημιν δια τι [ουν]{.greek-omitted} ουκ [επιστευσατε]{.greek-omitted} [επιστευσαται]{.greek-added} [αυτω]{.greek-omitted} [εις]{.greek-added} [αυτον]{.greek-added}[21:25]{.aside}

εαν [δε]{.greek-omitted} ειπωμεν εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ εχουσιν τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ως προφητην[21:26]{.aside}

και αποκριθεντες [τω]{.greek-omitted} [ιησου]{.greek-omitted} [ειπον]{.greek-omitted} [ειπων]{.greek-added} ουκ οιδαμεν εφη αυτοις και αυτος ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

τι δε υμιν δοκει [ανθρωπος]{.greek-abbr} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} [τεκνα]{.greek-omitted} δυο [υιους]{.greek-added} και προσελθων τω [πρωτω]{.greek-omitted} [προτω]{.greek-added} ειπεν τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε μεταμεληθεις απηλθεν[21:29]{.aside}

και προσελθων τω δευτερω ειπεν [ωσαυτως]{.greek-omitted} [ωσαυτος]{.greek-added} [και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} αποκριθεις ειπεν εγω [κυριε]{.greek-abbr} και ουκ απηλθεν[21:30]{.aside}

τις [ουν]{.greek-added} εκ των δυο εποιησεν το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι [οι]{.greek-omitted} [αι]{.greek-added} τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

ηλθεν [γαρ]{.greek-omitted} προς [υμας]{.greek-omitted} [ημας]{.greek-added} [ιωαννης]{.greek-omitted} [ο]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω οι δε τελωναι και αι πορναι επιστευσαν αυτω υμεις δε [ιδοντες]{.greek-omitted} [ειδοντες]{.greek-added} ου [μετεμεληθητε]{.greek-omitted} [μεταιμεληθηται]{.greek-added} υστερον του πιστευσαι αυτω[21:32]{.aside}

αλλην παραβολην [ακουσατε]{.greek-omitted} [ακουσαται]{.greek-added} [ανθρωπος]{.greek-abbr} τις ην οικοδεσποτης οστις εφυτευσεν αμ[πελω]{.unclear}να και φραγμον [αυτω]{.greek-omitted} [αυτον]{.greek-added} [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} και [ωρυξεν]{.greek-omitted} [ωρηξεν]{.greek-added} [εν]{.greek-omitted} αυτω ληνον και [ωκοδομησεν]{.greek-omitted} [οκοδομησεν]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεκδημησεν]{.greek-added}[21:33]{.aside}

οτε δε [ηγγισεν]{.greek-omitted} [ηγγησεν]{.greek-added} ο καιρος των καρπων απεστειλεν τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

και [λαβοντες]{.greek-omitted} [λαβων[τες]{.unclear}]{.greek-added} οι γεωργοι τους δουλους αυτου ον μεν εδειραν ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν [απεστειλεν]{.greek-omitted} [απεστηλε]{.greek-added} αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε [απεστειλεν]{.greek-omitted} [απεστηλεν]{.greek-added} [προς]{.greek-omitted} [αυτους]{.greek-omitted} τον υιον αυτου [προς]{.greek-added} [αυτους]{.greek-added} λεγων εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον [ειπον]{.greek-omitted} [ειπων]{.greek-added} εν εαυτοις [ουτος]{.greek-omitted} [ουτως]{.greek-added} εστιν ο κληρονομος [δευτε]{.greek-omitted} [δευται]{.greek-added} αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον εξεβαλον εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

οταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

[λεγουσιν]{.greek-omitted} [ερουσιν]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} κακους κακως απολεσει αυτους και τον αμπελωνα εκδωσεται αλλοις γεωργοις [οιτινες]{.greek-omitted} [ητινες]{.greek-added} αποδωσουσιν αυτω τους καρπους εν τοις καιροις [αυτων]{.greek-omitted} [αυτοις]{.greek-added}[21:41]{.aside}

λεγει αυτοις ο [ιησους]{.greek-abbr} [ουδεποτε]{.greek-omitted} [ουκ]{.greek-added} [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} εν ταις γραφαις λιθον ον [απεδοκιμασαν]{.greek-omitted} [απεδοκημασαν]{.greek-added} [οι]{.greek-omitted} [η]{.greek-added} οικοδομουντες ουτος εγενηθη εις κεφαλην γωνιας παρα [κυριου]{.greek-abbr} εγενετο αυτη και εστιν θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν [οτι]{.greek-omitted} αρθησεται αφ [υμων]{.greek-omitted} [ημων]{.greek-added} η βασιλεια του [θεου]{.greek-abbr} και δοθησεται εθνει [ποιουντι]{.greek-omitted} [ποιουντα]{.greek-added} τους καρπους [αυτης]{.greek-omitted} [αυτου]{.greek-added}[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον δ αν [πεση]{.greek-omitted} [πεσει]{.greek-added} λικμησει [αυτους]{.greek-added} [αυτον]{.corr}[21:44]{.aside}

[και]{.greek-omitted} ακουσαντες [δε]{.greek-added} οι αρχιερεις και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν τους οχλους επειδη [αυτον]{.greek-added} ως προφητην [αυτον]{.greek-omitted} ειχον[21:46]{.aside}

### Chapter 22

και αποκριθεις ο [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} ειπεν αυτοις εν παραβολαις λεγων[22:1]{.aside}

[ωμοιωθη]{.greek-omitted} [ομοιωθησεται]{.greek-added} η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει [οστις]{.greek-omitted} [ωστις]{.greek-added} εποιησεν γαμους τω υιω αυτου[22:2]{.aside}

και απεστειλεν τους δουλους αυτου καλεσαι τους κεκλημενους εις [τους]{.greek-omitted} [τον]{.greek-added} γαμους και ουκ ηθελον ελθειν[22:3]{.aside}

παλιν απεστειλεν αλλους δουλους λεγων [ειπατε]{.greek-omitted} [ειπαται]{.greek-added} τοις κεκλημενοις ιδου [το]{.greek-omitted} [τον]{.greek-added} αριστον μου ητοιμασα οι ταυροι [μου]{.greek-omitted} και τα σιτιστα [τεθυμενα]{.greek-omitted} [τεθημενα]{.greek-added} και παντα ετοιμα [δευτε]{.greek-omitted} [δευται]{.greek-added} εις τους γαμους[22:4]{.aside}

οι δε αμελησαντες απηλθον ο μεν εις τον ιδιον αγρον [ο]{.greek-omitted} [ος]{.greek-added} δε εις την εμποριαν αυτου[22:5]{.aside}

οι δε [λυποι]{.greek-added} [λοιποι]{.corr} [κρατησαντες]{.greek-omitted} [κρατισαντες]{.greek-added} τους δουλους αυτου υβρισαν και απεκτειναν[22:6]{.aside}

και ακουσας ο βασιλευς εκεινος [ωργισθη]{.greek-omitted} [οργισθη]{.greek-added} και πεμψας τα στρατευματα αυτου [απωλεσεν]{.greek-omitted} [απολεσεν]{.greek-added} τους φονεις εκεινους και [την]{.greek-omitted} [τον]{.greek-added} πολιν αυτων [ενεπρησεν]{.greek-omitted} [ενεπρισεν]{.greek-added}[22:7]{.aside}

τοτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος εστιν οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

πορευεσθε ουν επι τας διεξοδους των οδων και οσους [αν]{.greek-omitted} [εαν]{.greek-added} [ευρητε]{.greek-omitted} [ευρηται]{.greek-added} [καλεσατε]{.greek-omitted} [καλεσαται]{.greek-added} εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους [συνηγαγον]{.greek-omitted} [συνηγαγων]{.greek-added} [παντας]{.greek-omitted} οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

εισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

και λεγει αυτω εταιρε πως εισηλθες ωδε μη εχων ενδυμα γαμου ο δε εφιμωθη[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου [χειρας]{.greek-added} [και]{.greek-added} ποδας [και]{.greek-omitted} [χειρας]{.greek-omitted} αρατε αυτον και [εκβαλετε]{.greek-omitted} [εμβαλετε]{.greek-added} εις το σκοτος το [εξωτερον]{.greek-omitted} [εξοτερον]{.greek-added} εκει [εσται]{.greek-omitted} [εστιν]{.greek-added} ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

τοτε πορευθεντες οι φαρισαιοι συμβουλιον ελαβον οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των [ηρωδιανων]{.greek-omitted} [ηρoδιανων]{.greek-added} [λεγοντες]{.greek-omitted} διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-abbr}[22:16]{.aside}

ειπε ουν [ημιν]{.greek-omitted} [ειμι]{.greek-added} τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι [κηνσον]{.greek-omitted} [κεινσον]{.greek-added} καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων ειπεν τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του [κηνσου]{.greek-omitted} [κινσου]{.greek-added} οι δε προσηνεγκαν αυτω δηναριον[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος τοτε λεγει αυτοις [αποδοτε]{.greek-omitted} [αποδοται]{.greek-added} ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

εν εκεινη τη ημερα [προσηλθον]{.greek-omitted} [προσηλθων]{.greek-added} αυτω [σαδδουκαιοι]{.greek-omitted} [σαδουκαιοι]{.greek-added} [οι]{.greek-omitted} [ο]{.greek-added} [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} μη ειναι αναστασιν και επηρωτησαν [αυτον]{.greek-omitted} [αυτω]{.greek-added}[22:23]{.aside}

λεγοντες διδασκαλε μωσης ειπεν εαν τις αποθανη μη εχων τεκνα [επιγαμβρευσει]{.greek-omitted} [επιγαμβευσει]{.greek-added} ο αδελφος αυτου την γυναικα αυτου και αναστησει σπερμα τω αδελφω αυτου[22:24]{.aside}

ησαν δε παρ ημιν [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αδελφοι και ο πρωτος γαμησας ετελευτησεν και μη εχων σπερμα αφηκεν την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο [τριτος]{.greek-omitted} [[γ]{.greek-abbr}]{.greek-added} εως των [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added}[22:26]{.aside}

υστερον δε παντων απεθανεν και η γυνη[22:27]{.aside}

εν τη [ουν]{.greek-omitted} αναστασει τινος [των]{.greek-omitted} [επτα]{.greek-omitted} εσται γυνη παντες [γαρ]{.greek-omitted} εσχον αυτην[22:28]{.aside}

αποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν [αυτοις]{.greek-omitted} πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε [εκγαμιζονται]{.greek-omitted} [εγγαμιζωνται]{.greek-added} αλλ ως αγγελοι [του]{.greek-omitted} [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} εισιν[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ [ανεγνωτε]{.greek-omitted} [ανεγνωται]{.greek-added} το ρηθεν [υμιν]{.greek-omitted} [ειμιν]{.greek-added} υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα [ζωντων]{.greek-omitted} [ζοντων]{.greek-added}[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

οι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημωσεν]{.greek-added} τους [σαδδουκαιους]{.greek-omitted} [σαδουκαιους]{.greek-added} συνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν εις εξ αυτων νομικος πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη [εστιν]{.greek-omitted} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added}[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται [κρεμανται]{.greek-omitted} [κρεμμανσαι]{.greek-added}[22:40]{.aside}

συνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει περι του [χριστου]{.greek-abbr} τινος υιος εστιν λεγουσιν αυτω του [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-omitted} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει λεγων[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} καλει [α]{.unclear}υτον [κυριον]{.greek-abbr} πως υιος αυτου εστιν[22:45]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} [αυτω]{.greek-omitted} [αυτο]{.greek-added} αποκριθηναι λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας [επερωτησαι]{.greek-omitted} [επερωτισαι]{.greek-added} αυτον ουκετι[22:46]{.aside}

### Chapter 23

τοτε ο [ιησους]{.greek-abbr} [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} τοις οχλοις και τοις μαθηταις αυτου[23:1]{.aside}

λεγων επι της μωσεως καθεδρας [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} οι γραμματεις και [οι]{.greek-omitted} φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν τηρειν τηρειτε και [ποιειτε]{.greek-omitted} [ποιηται]{.greek-added} κατα δε τα εργα αυτων μη [ποιειτε]{.greek-omitted} [ποιηται]{.greek-added} λεγουσιν γαρ και ου ποιουσιν[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [δεσμευουσι]{.greek-added} γαρ φορτια βαρεα και δυσβαστακτα και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω αυτων ου θελουσιν κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} δε τα φυλακτηρια αυτων και μεγαλυνουσιν τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [φιλουσι]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} την [πρωτοκλισιαν]{.greek-omitted} [προτοκλησιαν]{.greek-added} εν τοις δειπνοις και τας [πρωτοκαθεδριας]{.greek-omitted} [προτοκαθεδριας]{.greek-added} εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} ραββι [ραββι]{.greek-omitted}[23:7]{.aside}

υμεις δε μη [κληθητε]{.greek-omitted} [κληθηται]{.greek-added} ραββι εις γαρ [εστιν]{.greek-omitted} υμων ο καθηγητης ο [χριστος]{.greek-abbr} [παντες]{.greek-omitted} [δε]{.greek-omitted} [υμεις]{.greek-omitted} [αδελφοι]{.greek-omitted} [εστε]{.greek-omitted}[23:8]{.aside}

[και]{.greek-omitted} [μη]{.greek-added} [καλεσηται]{.greek-added} [πατερα]{.greek-abbr} [μη]{.greek-omitted} [καλεσητε]{.greek-omitted} [υμων]{.greek-omitted} επι [της]{.greek-omitted} γης εις γαρ [[εστιν]{.unclear}]{.corr} [υμων]{.greek-added} ο [πατηρ]{.greek-abbr} [υμων]{.greek-omitted} [ο]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted}[23:9]{.aside}

[μηδε]{.greek-omitted} [κληθητε]{.greek-omitted} [καθηγηται]{.greek-omitted} [εις]{.greek-omitted} [γαρ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted} ο [[θεος]{.greek-abbr}]{.greek-added} [καθηγητης]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted}[23:10]{.aside}

ο δε μειζων υμων εσται υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται και οστις ταπεινωσει εαυτον υψωθησεται[23:12]{.aside}

ουαι [υμεις]{.greek-added} [δε]{.greek-omitted} [υμιν]{.greek-omitted} γραμματεις και φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειεται]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [γαρ]{.greek-added} [ουκ]{.greek-added} [εισερχεσθαι]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιεται]{.greek-added} [ελθειν]{.greek-added}[23:13 | instance no. 2]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιεται]{.greek-added} [τας]{.greek-added} [οικειας]{.greek-added} των [χειρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευχομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθαι]{.greek-added} [περισσον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

ουαι [υμιν]{.greek-omitted} [υμην]{.greek-added} γραμματεις και φαρισαιοι υποκριται οτι [περιαγετε]{.greek-omitted} [περιαγεται]{.greek-added} την θαλασσαν και την ξηραν ποιησαι ενα [προσηλυτον]{.greek-omitted} [προσηλητον]{.greek-added} και οταν γενηται [ποιηται]{.greek-added} [ποιειτε]{.greek-omitted} [αυτον]{.greek-omitted} [υιον]{.greek-omitted} [γεεννης]{.greek-omitted} [διπλοτερον]{.greek-omitted} [υμων]{.greek-omitted}[23:15]{.aside}

[ουαι]{.greek-omitted} [υμιν]{.greek-omitted} [γραμματεις]{.greek-omitted} [και]{.greek-omitted} [φαρισαιοι]{.greek-omitted} [υποκριται]{.greek-omitted} [οτι]{.greek-omitted} [περιαγετε]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [ξηραν]{.greek-omitted} [ποιησαι]{.greek-omitted} [ενα]{.greek-omitted} [προσηλυτον]{.greek-omitted} [και]{.greek-omitted} [οταν]{.greek-omitted} [γενηται]{.greek-omitted} [ποιειτε]{.greek-omitted} αυτον υιον γεεννης διπλοτερον υμων[23:15 | instance no. 2]{.aside}

ουαι υμιν οδηγοι τυφλοι οι λεγοντες [ος]{.greek-omitted} [ως]{.greek-added} αν [ομοση]{.greek-omitted} [ομωση]{.greek-added} εν τω ναω ουδεν εστιν ος δ αν [ομοση]{.greek-omitted} [ομωση]{.greek-added} εν τω χρυσω του ναου οφειλει[23:16]{.aside}

μωροι και τυφλοι τις γαρ μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} [ομοση]{.greek-omitted} [ομωση]{.greek-added} εν τω θυσιαστηριω ουδεν εστιν [ος]{.greek-omitted} [ως]{.greek-added} δ αν [ομοση]{.greek-omitted} [ομωση]{.greek-added} εν τω δωρω τω επανω αυτου οφειλει[23:18]{.aside}

μωροι και τυφλοι [τι]{.greek-omitted} [τις]{.greek-added} γαρ [μειζον]{.greek-omitted} [μειζων]{.greek-added} το δωρον η το θυσιαστηριον [το]{.greek-omitted} [αγιαζον]{.greek-omitted} [το]{.greek-omitted} [δωρον]{.greek-omitted}[23:19]{.aside}

ο [ουν]{.greek-omitted} [ομοσας]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [θυσιαστηριω]{.greek-omitted} ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο [ομοσας]{.greek-omitted} [ομνυον]{.greek-added} εν τω ναω ομνυει εν αυτω και εν τω [κατοικησαντι]{.greek-omitted} [κατοικουντι]{.greek-added} [αυτον]{.greek-omitted} [εν]{.greek-added} [αυτω]{.greek-added}[23:21]{.aside}

και ο [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [αποδεκατουτε]{.greek-omitted} [αποδεκατουται]{.greek-added} το ηδυοσμον και το [ανηθον]{.greek-omitted} [ανιθον]{.greek-added} και το [κυμινον]{.greek-omitted} [κειμινον]{.greek-added} και [αφηκατε]{.greek-omitted} [αφηκαται]{.greek-added} τα βαρυτερα του νομου την κρισιν και [τον]{.greek-omitted} [το]{.greek-added} [ελεον]{.greek-omitted} [ελεος]{.greek-added} και την πιστιν ταυτα εδει ποιησαι κακεινα μη αφιεναι[23:23]{.aside}

οδηγοι [η]{.greek-added} [τυφλοι]{.greek-omitted} [οι]{.greek-omitted} διυλιζοντες τον [κωνωπα]{.greek-omitted} [κονωπα]{.greek-added} την δε [καμηλον]{.greek-omitted} [καμιλον]{.greek-added} καταπινοντες[23:24]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [καθαριζετε]{.greek-omitted} [καθαριζεται]{.greek-added} το εξωθεν του ποτηριου και της παροψιδος εσωθεν δε γεμουσιν εξ αρπαγης και αδικιας[23:25]{.aside}

φαρισαιε τυφλε καθαρισον πρωτον το εντος του ποτηριου και της παροψιδος ινα γενηται και το εκτος [αυτων]{.greek-omitted} [αυτου]{.greek-added} καθαρον[23:26]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [παρομοιαζετε]{.greek-omitted} [παρομιαζεται]{.greek-added} ταφοις κεκονιαμενοις οιτινες εξωθεν μεν φαινονται ωραιοι εσωθεν δε γεμουσιν οστεων νεκρων και πασης ακαθαρσιας[23:27]{.aside}

[ουτως]{.greek-omitted} [ουτω]{.greek-added} και υμεις εξωθεν μεν [φαινεσθε]{.greek-omitted} [φαινεσθαι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} δικαιοι εσωθεν δε μεστοι [εστε]{.greek-omitted} [εσται]{.greek-added} υποκρισεως και ανομιας[23:28]{.aside}

ουαι υμιν γραμματεις και φαρισαιοι υποκριται οτι [οικοδομειτε]{.greek-omitted} [οικοδομειται]{.greek-added} τους ταφους των προφητων και [κοσμειτε]{.greek-omitted} [κοσμειται]{.greek-added} τα μνημεια των δικαιων[23:29]{.aside}

[και]{.greek-omitted} [λεγετε]{.greek-omitted} [λεγεται]{.greek-added} ει ημεν εν ταις ημεραις των [πατερων]{.greek-abbr} ημων ουκ αν ημεν κοινωνοι [αυτων]{.greek-omitted} [αυτω]{.greek-added} εν τω αιματι των προφητων[23:30]{.aside}

[ωστε]{.greek-omitted} [ωσται]{.greek-added} [μαρτυρειτε]{.greek-omitted} [μαρτυρειται]{.greek-added} [εν]{.greek-added} [εαυτοις]{.greek-omitted} [αυτοις]{.greek-added} οτι υιοι εστε των φονευσαντων τους προφητας[23:31]{.aside}

και [υμεις]{.greek-omitted} [ν[υν]{.unclear}]{.greek-added} πληρωσατε το μετρον των [πατερων]{.greek-abbr} υμων[23:32]{.aside}

[οφεις]{.greek-omitted} [οφις]{.greek-added} [γεννηματα]{.greek-omitted} [γενηματα]{.greek-added} εχιδνων πως [φυγητε]{.greek-omitted} [φυγηται]{.greek-added} απο της κρισεως της [εν]{.greek-added} [γεεννης]{.greek-omitted} [γεεννη]{.greek-added}[23:33]{.aside}

δια τουτο ιδου εγω [αποστελλω]{.greek-omitted} [αποστελω]{.greek-added} προς υμας προφητας και σοφους κ[α]{.unclear}[ι]{.greek-supplied} [γ]{.greek-supplied}ρ[αμ]{.greek-supplied}[μ]{.unclear}ατεις και εξ αυτων [αποκτενειτε]{.greek-omitted} [αποκτεινεται]{.greek-added} και [σταυρωσετε]{.greek-omitted} [[στρωσεται]{.greek-abbr}]{.greek-added} και εξ αυτων [μαστιγωσατε]{.greek-added} [μαστιγωσετε]{.corr} εν ταις συναγωγαις υμων και [διωξετε]{.greek-omitted} [διωξεται]{.greek-added} απο πολεως εις πολιν[23:34]{.aside}

οπως [αν]{.greek-added} ελθη εφ [υμας]{.greek-omitted} [ημας]{.greek-added} παν αιμα δικαιον εκχυνομενον [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} απο του αιματος αβελ του δικαιου εως του αιματος [ζαχαριου]{.greek-omitted} [υιου]{.greek-omitted} [βαραχιου]{.greek-omitted} [ον]{.greek-omitted} [εφονευσατε]{.greek-omitted} [μεταξυ]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} [και]{.greek-omitted} [του]{.greek-omitted} [θυσιαστηριου]{.greek-omitted}[23:35]{.aside}

[οπως]{.greek-omitted} [ελθη]{.greek-omitted} [εφ]{.greek-omitted} [υμας]{.greek-omitted} [παν]{.greek-omitted} [αιμα]{.greek-omitted} [δικαιον]{.greek-omitted} [εκχυνομενον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [αιματος]{.greek-omitted} [αβελ]{.greek-omitted} [του]{.greek-omitted} [δικαιου]{.greek-omitted} [εως]{.greek-omitted} [του]{.greek-omitted} [αιματος]{.greek-omitted} ζαχαριου υιου βαραχιου ον εφονευσατε μεταξυ του ναου και του θυσιαστηριου[23:35 | instance no. 2]{.aside}

αμην λεγω υμιν οτι ηξει [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} επι την γενεαν ταυτην[23:36]{.aside}

[ιερουσαλημ]{.greek-abbr} [ιερουσαλημ]{.greek-abbr} η [αποκτενουσα]{.greek-omitted} [αποκτεινουσα]{.greek-added} τους προφητας και λιθοβολουσα τους απεσταλμενους προς αυτην ποσακις [ηθελησα]{.greek-omitted} [ηθελησεν]{.greek-added} επισυναγαγειν τα τεκνα σου ον τροπον επισυναγει ορνις τα [νοσσια]{.greek-omitted} [νοσια]{.greek-added} εαυτης υπο τας πτερυγας και ουκ ηθελησατε[23:37]{.aside}

ιδου αφιεται [υμιν]{.greek-omitted} ο οικος υμων ερημος[23:38]{.aside}

λεγω γαρ υμιν ου μη [με]{.greek-omitted} [ιδητε]{.greek-omitted} [μαι]{.greek-added} [ιδηται]{.greek-added} απ αρτι εως [αν]{.greek-omitted} [ειπητε]{.greek-omitted} [ειπηται]{.greek-added} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[23:39]{.aside}

### Chapter 24

και εξελθων ο [ιησους]{.greek-abbr} επορευετο απο του ιερου και προσηλθον [αυτω]{.greek-added} οι μαθηται αυτου [επιδειξαι]{.greek-omitted} [δειξαι]{.greek-added} αυτω τας οικοδομας του ιερου[24:1]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις [ου]{.greek-omitted} [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} [[ταυτα]{.greek-supplied}]{.greek-added} [παντα]{.greek-supplied} [ταυτα]{.greek-omitted} αμην λεγω υμιν ου μη [αφεθει]{.greek-added} [αφεθη]{.greek-omitted} [ωδε]{.greek-omitted} λιθος επι λιθον ος ου [καταλυθησεται]{.greek-omitted} [καταληθησεται]{.greek-added}[24:2]{.aside}

καθημενου δε αυτου [επι]{.greek-omitted} [εις]{.greek-added} [του]{.greek-omitted} [το]{.greek-added} [ορους]{.greek-omitted} [ορος]{.greek-added} των ελαιων προσηλθον αυ[τ]{.greek-supplied}[ω]{.unclear} οι μαθηται κατ ιδιαν λεγοντες ειπε ημιν ποτε ταυτα εσται και τι το σημειον της [σης]{.greek-omitted} παρουσιας και της [συν]{.greek-added} [συντελειας]{.greek-omitted} [του]{.greek-omitted} [αιωνος]{.greek-omitted}[24:3]{.aside}

[καθημενου]{.greek-omitted} [δε]{.greek-omitted} [αυτου]{.greek-omitted} [επι]{.greek-omitted} [του]{.greek-omitted} [ορους]{.greek-omitted} [των]{.greek-omitted} [ελαιων]{.greek-omitted} [προσηλθον]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [κατ]{.greek-omitted} [ιδιαν]{.greek-omitted} [λεγοντες]{.greek-omitted} [ειπε]{.greek-omitted} [ημιν]{.greek-omitted} [ποτε]{.greek-omitted} [ταυτα]{.greek-omitted} [εσται]{.greek-omitted} [και]{.greek-omitted} [τι]{.greek-omitted} [το]{.greek-omitted} [σημειον]{.greek-omitted} [της]{.greek-omitted} [σης]{.greek-omitted} [παρουσιας]{.greek-omitted} [και]{.greek-omitted} [της]{.greek-omitted} [συντελειας]{.greek-omitted} [τελειας]{.greek-added} του αιωνος[24:3 | instance no. 2]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις [βλεπετε]{.greek-omitted} [βλεπεται]{.greek-added} μη τις υμας πλανηση[24:4]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες εγω ειμι ο [χριστος]{.greek-abbr} και πολλους [πλανησουσιν]{.greek-omitted} [πλανισουσιν]{.greek-added}[24:5]{.aside}

[μελλησετε]{.greek-omitted} [μελησεται]{.greek-added} δε ακουειν πολεμους και [ακοας]{.greek-omitted} [πολεμων]{.greek-omitted} [ακαταστασιας]{.greek-added} [πολεμους]{.greek-added} ορατε μη θροεισθε δει γαρ [παντα]{.greek-omitted} [ταυτα]{.greek-added} γενεσθαι αλλ ουπω [εστιν]{.greek-omitted} [εσται]{.greek-added} το τελος[24:6]{.aside}

εγερθησεται [γαρ]{.greek-omitted} εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται λιμοι και [λοιμοι]{.greek-omitted} [λιμοι]{.greek-added} και [σεισμοι]{.greek-omitted} [σησμοι]{.greek-added} κατα τοπους[24:7]{.aside}

παντα δε ταυτα [αρχη]{.greek-omitted} [αρχαι]{.greek-added} ωδινων[24:8]{.aside}

τοτε παραδωσουσιν [υμας]{.greek-omitted} [ημας]{.greek-added} εις [θλιψιν]{.greek-omitted} [θλιψεις]{.greek-added} και αποκτενουσιν [υμας]{.greek-omitted} [ημας]{.greek-added} και [εσεσθε]{.greek-omitted} [εσεσθαι]{.greek-added} μισουμενοι υπο παντων των εθνων δια το ονομα μου[24:9]{.aside}

και τοτε σκανδαλισθησονται πολλοι και αλληλους παραδωσουσιν και [μισησουσιν]{.greek-omitted} [μησισουσιν]{.greek-added} αλληλους[24:10]{.aside}

και πολλοι ψευδοπροφηται εγερθησονται και πλανησουσιν πολλους[24:11]{.aside}

και δια το πληθυνθηναι την ανομιαν ψυγησεται η αγαπη των πολλων[24:12]{.aside}

ο δε υπομεινας εις τελος ουτος σωθησεται[24:13]{.aside}

και κηρυχθησεται τουτο το ευαγγελιον της βασιλειας [μου]{.greek-added} εν ολη τη οικουμενη εις μαρτυριον πασιν τοις εθνεσιν και τοτε ηξει το τελος[24:14]{.aside}

οταν [ιδηται]{.greek-added} [ουν]{.greek-omitted} [ιδητε]{.greek-omitted} το βδελυγμα της ερημωσεως το ρηθεν δια δανιηλ του προφητου εστως εν τοπω αγιω ο αναγιν[ωσκων]{.unclear} [νοειτω]{.greek-omitted} [[ν]{.unclear}οητω]{.greek-added}[24:15]{.aside}

τοτε οι εν τη ιουδαια φευγετωσαν επι τα ορη[24:16]{.aside}

ο επι του δωματος μη [καταβαινετω]{.greek-omitted} [καταβατω]{.greek-added} [αραι]{.greek-omitted} [αρε]{.greek-added} τα [ιματια]{.greek-added} [εκ]{.greek-omitted} [της]{.greek-omitted} [οικιας]{.greek-omitted} αυτου[24:17]{.aside}

και ο εν τω αγρω μη επιστρεψατω [οπισω]{.greek-omitted} αραι [τα]{.greek-omitted} [ιματια]{.greek-omitted} [τι]{.greek-added} [εκ]{.greek-added} [της]{.greek-added} [οικειας]{.greek-added} αυτου[24:18]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[24:19]{.aside}

[προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} δε ινα μη γενηται η φυγη υμων χειμωνος [μηδε]{.greek-omitted} [η]{.greek-added} [εν]{.greek-added} σαββατω[24:20]{.aside}

[εσται]{.greek-omitted} [εστε]{.greek-added} γαρ τοτε [θλιψις]{.greek-omitted} [θλιψεις]{.greek-added} μεγαλη οια ου γεγονεν απ αρχης [του]{.greek-added} κοσμου εως του νυν ουδ ου μη γενηται[24:21]{.aside}

και ει [μη]{.greek-omitted} [μι]{.greek-added} εκολοβωθησαν αι ημεραι εκειναι ουκ αν εσωθη πασα σαρξ δια δε τους εκλεκτους [κολοβωθησονται]{.greek-omitted} [κολοβοθησονται]{.greek-added} αι ημεραι εκειναι[24:22]{.aside}

τοτε εαν τις [ειπη]{.greek-added} υμιν [ειπη]{.greek-omitted} ιδου ωδε ο [χριστος]{.greek-abbr} η ωδε μη [πιστευσητε]{.greek-omitted} [πιστευσηται]{.greek-added}[24:23]{.aside}

εγερθησονται γαρ [ψευδοχριστοι]{.greek-omitted} [ψευδοχρηστοι]{.greek-added} και ψευδοπροφηται και δωσουσιν σημεια [μεγαλα]{.greek-omitted} και τερατα [μεγαλα]{.greek-added} ωστε πλανησαι ει δυνατον και τους εκλεκτους[24:24]{.aside}

ιδου [προειρηκα]{.greek-omitted} [πρωειρηκα]{.greek-added} υμιν[24:25]{.aside}

εαν ουν ειπωσιν υμιν ιδου εν τη ερημω εστιν μη [εξελθητε]{.greek-omitted} [εξελθηται]{.greek-added} ιδου εν τοις ταμειοις μη [πιστευσητε]{.greek-omitted} [πιστευσηται]{.greek-added}[24:26]{.aside}

ωσπερ γαρ η αστραπη εξερχεται απο ανατολων και φαινεται εως δυσμων ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:27]{.aside}

οπου γαρ [ην]{.greek-added} [εαν]{.greek-omitted} [η]{.greek-omitted} το πτωμα εκει συναχθησονται [και]{.greek-added} οι αετοι[24:28]{.aside}

ευθεως δε μετα την θλιψιν των ημερων εκεινων ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης και οι αστερες πεσουνται απο του [ουρανου]{.greek-abbr} και αι δυναμεις των [ουρανων]{.greek-abbr} σαλευθησονται[24:29]{.aside}

και τοτε φανησεται το σημειον του υιου του [ανθρωπου]{.greek-abbr} εν τω [ουρανω]{.greek-abbr} και τοτε κοψονται πασαι αι φυλαι της γης και οψονται τον υιον του [ανθρωπου]{.greek-abbr} [ερχομενον]{.greek-omitted} [εν]{.greek-added} [τω]{.greek-added} [[ουρανω]{.greek-abbr}]{.greek-added} επι των νεφελων του [ουρανου]{.greek-abbr} μετα δυναμεως και δοξης πολλης[24:30]{.aside}

και [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου μετα σαλπιγγος φωνης μεγαλης και [επισυναξουσιν]{.greek-omitted} [επισυναξωσιν]{.greek-added} τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρων [ουρανων]{.greek-omitted} [[ουρανου]{.greek-abbr}]{.greek-added} εως ακρων αυτων[24:31]{.aside}

απο δε της συκης [μαθετε]{.greek-omitted} [μαθεται]{.greek-added} την παραβολην οταν [ηδη]{.greek-omitted} [ιδη]{.greek-added} ο κλαδος αυτης γενηται απαλος και τα φυλλα [εκφυη]{.greek-omitted} [εκφυει]{.greek-added} [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος[24:32]{.aside}

ουτως και [υμεις]{.greek-omitted} [ημεις]{.greek-added} οταν [ιδητε]{.greek-omitted} [ιδηται]{.greek-added} ταυτα παντα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς εστιν επι [θυραις]{.greek-omitted} [θυρες]{.greek-added}[24:33]{.aside}

αμην λεγω υμιν [οτι]{.greek-added} ου μη παρελθη η γενεα [αυτη]{.greek-omitted} [ταυτη]{.greek-added} εως [αν]{.greek-omitted} [ου]{.greek-added} [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[24:34]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσονται]{.greek-omitted} [παρελευσεται]{.greek-added} οι δε λογοι μου ου μη παρελθωσιν[24:35]{.aside}

περι δε της ημερας εκεινης και [[της]{.corr}]{.greek-added} ωρας ουδεις [οιδεν]{.greek-omitted} [ιδεν]{.greek-added} ουδε οι αγγελοι των [ουρανων]{.greek-abbr} [ουτε]{.greek-added} [ο]{.greek-added} [υιος]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} ο [πατηρ]{.greek-abbr} μου μονος[24:36]{.aside}

ωσπερ δε αι ημεραι του νωε ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:37]{.aside}

ωσπερ γαρ ησαν εν ταις ημεραις ταις προ του κατακλυσμου [τρωγοντες]{.greek-omitted} [τρογωντες]{.greek-added} και [πινοντες]{.greek-omitted} [πινωντες]{.greek-added} [γαμουντες]{.greek-omitted} [γαμοντες]{.greek-added} και εκγαμιζοντες αχρι [ης]{.greek-omitted} [εις]{.greek-added} ημερας εισηλθεν νωε εις την κιβωτον[24:38]{.aside}

και ουκ εγνωσαν εως [ου]{.greek-added} ηλθεν ο κατακλυσμος και ηρεν απαντας ουτως εσται και η παρουσια του υιου του [ανθρωπου]{.greek-abbr}[24:39]{.aside}

τοτε δυο εσονται εν τω αγρω ο εις παραλαμβανεται και ο εις αφιεται[24:40]{.aside}

δυο [αληθουσαι]{.greek-omitted} [αλιθουσαι]{.greek-added} εν τω μυλωνι [[η]{.corr}]{.greek-added} μια παραλαμβανεται και [η]{.greek-added} μια αφιεται[24:41]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} [ουν]{.greek-omitted} οτι ουκ [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} ποια ωρα ο [κυριος]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added} ερχεται[24:42]{.aside}

[εκεινο]{.greek-omitted} [εκεινω]{.greek-added} δε [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι ει [ηδει]{.greek-omitted} [ηδη]{.greek-added} ο οικοδεσποτης ποια φυλακη ο [κλεπτης]{.greek-omitted} [κλαιπτης]{.greek-added} ερχεται [εγρηγορησεν]{.greek-omitted} [εγρηγορισεν]{.greek-added} αν και ουκ αν ειασεν [διαριγηναι]{.greek-added} [διορυγηναι]{.greek-omitted} [[διοριγηναι]{.corr}]{.greek-added} την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} αυτου[24:43]{.aside}

δια τουτο [και]{.greek-omitted} [υμεις]{.greek-omitted} [γινεσθε]{.greek-omitted} [γινεσθαι]{.greek-added} ετοιμοι [οτι]{.greek-omitted} [διοτι]{.greek-added} η ωρα [η]{.greek-added} ου [δοκειτε]{.greek-omitted} [δοκειται]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[24:44]{.aside}

τις αρα εστιν ο πιστος δουλος και [φρονιμος]{.greek-omitted} [φρονημος]{.greek-added} ον κατεστησεν ο [κυριος]{.greek-abbr} [αυτου]{.greek-omitted} επι της θεραπειας αυτου του [διδοναι]{.greek-omitted} [δουναι]{.greek-added} αυτοις την τροφην εν καιρω[24:45]{.aside}

μακαριος ο δουλος εκεινος ον ελθων ο [κυριος]{.greek-abbr} αυτου [ευρησει]{.greek-omitted} [ευρισει]{.greek-added} ποιουντα ουτως[24:46]{.aside}

αμην λεγω υμιν οτι επι πασιν τοις υπαρχουσιν αυτου καταστησει αυτον[24:47]{.aside}

εαν δε ειπη ο κακος δουλος εκεινος εν τη καρδια αυτου χρονιζει ο [κυριος]{.greek-abbr} μου ελθειν[24:48]{.aside}

και αρξηται τυπτειν τους συνδουλους [εσθιειν]{.greek-omitted} [εσθυειν]{.greek-added} [δε]{.greek-omitted} [τε]{.greek-added} και πινειν μετα των μεθυοντων[24:49]{.aside}

ηξει ο [κυριος]{.greek-abbr} του δουλου εκεινου εν ημερα η ου προσδοκα και εν ωρα η ου γινωσκει[24:50]{.aside}

και [διχοτομησει]{.greek-omitted} [διχοτομισει]{.greek-added} αυτον και το μερος αυτου μετα των υποκριτων θησει εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[24:51]{.aside}

### Chapter 25

[ποτε]{.greek-added} [τοτε]{.corr} ομοιωθησεται η βασιλεια των [ουρανων]{.greek-abbr} δεκα παρθενοις αιτινες λαβουσαι τας λαμπαδας αυτων [εξηλθον]{.greek-omitted} [εξηλθων]{.greek-added} εις απαντησιν του νυμφιου[25:1]{.aside}

πεντε δε ησαν εξ αυτων φρονιμοι και αι πεντε μωραι[25:2]{.aside}

αιτινες μωραι λαβουσαι τας λαμπαδας αυτων ουκ ελαβον μεθ εαυτων ελαιον[25:3]{.aside}

αι δε [φρονιμοι]{.greek-omitted} [φρονημοι]{.greek-added} ελαβον ελαιον εν τοις [αγγειοις]{.greek-omitted} [αγγιοις]{.greek-added} αυτων μετα των λαμπαδων αυτων[25:4]{.aside}

χρονιζοντος δε του νυμφιου ενυσταξαν πασαι και [εκαθευδον]{.greek-omitted} [εκαθευδων]{.greek-added}[25:5]{.aside}

[μεσης]{.greek-omitted} [μεσουσης]{.greek-added} δε [της]{.greek-added} νυκτος κραυγη [γεγονεν]{.greek-omitted} [γεγωνεν]{.greek-added} ιδου ο νυμφιος ερχεται εξερχεσθε εις απαντησιν αυτου[25:6]{.aside}

τοτε ηγερθησαν πασαι αι παρθενοι εκειναι και εκοσμησαν τας λαμπαδας αυτων[25:7]{.aside}

αι δε μωραι [ταις]{.greek-omitted} [τοις]{.greek-added} [φρονιμοις]{.greek-omitted} [φρονημοις]{.greek-added} [ειπον]{.greek-omitted} [ειπαν]{.greek-added} [δοτε]{.greek-omitted} [δοται]{.greek-added} ημιν εκ του ελαιου υμων οτι αι λαμπαδες [ημων]{.greek-omitted} [υμων]{.greek-added} [σβεννυνται]{.greek-omitted} [σβενεινται]{.greek-added}[25:8]{.aside}

απεκριθησαν δε αι φρονιμοι λεγουσαι μηποτε ουκ [αρκεση]{.greek-omitted} [αρκεσει]{.greek-added} ημιν και υμιν [πορευεσθε]{.greek-omitted} [πορευυεσθαι]{.greek-added} δε μαλλον προς τους πωλουντας και [αγορασατε]{.greek-omitted} [αγωρασατε]{.greek-added} εαυταις[25:9]{.aside}

απερχομενων δε αυτων [αγορασαι]{.greek-omitted} [αγωρασαι]{.greek-added} ηλθεν ο νυμφιος και [αιτιμοι]{.greek-added} [αι]{.greek-omitted} [ετοιμοι]{.greek-omitted} [εισηλθον]{.greek-omitted} [εισηλθων]{.greek-added} μετ [αυτου]{.greek-omitted} [αυτων]{.greek-added} εις τους γαμους και [εκλεισθη]{.greek-omitted} [εκλησθη]{.greek-added} η θυρα[25:10]{.aside}

υστερον [ηλθων]{.greek-added} [δε]{.greek-omitted} [ερχονται]{.greek-omitted} και αι [λοιπαι]{.greek-omitted} [λιπαι]{.greek-added} παρθενοι λεγουσαι [κυριε]{.greek-abbr} [κυριε]{.greek-abbr} ανοιξον ημιν[25:11]{.aside}

ο δε αποκριθεις ειπεν αμην λεγω υμιν ουκ οιδα υμας[25:12]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} ουν οτι ουκ [οιδατε]{.greek-omitted} [οιδαται]{.greek-added} την ημεραν ουδε την ωραν εν [η]{.greek-omitted} [ι]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} ερχεται[25:13]{.aside}

ωσπερ γαρ [ανθρωπος]{.greek-abbr} αποδημων [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} τους ιδιους δουλους [αυτου]{.greek-added} και παρεδωκεν αυτοις τα υπαρχοντα αυτου[25:14]{.aside}

και ω μεν [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} πεντε ταλαντα [ω]{.greek-omitted} [ο]{.greek-added} δε δυο ω δε εν εκαστω κατα την [ιδιαν]{.greek-omitted} [οικειαν]{.greek-added} δυναμιν και απεδημησεν ευθεως[25:15]{.aside}

[πορευθεις]{.greek-omitted} [πορευθυς]{.greek-added} [δε]{.greek-omitted} ο τα πεντε ταλαντα λαβων ειργασατο εν αυτοις και εποιησεν αλλα [[ε]{.greek-abbr}]{.greek-added} [πεντε]{.greek-omitted} [ταλαντα]{.greek-omitted}[25:16]{.aside}

ωσαυτως και ο τα [[β]{.greek-abbr}]{.greek-added} [δυο]{.greek-omitted} [εκερδησεν]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [αλλα]{.greek-omitted} [δυο]{.greek-omitted}[25:17]{.aside}

ο δε το εν λαβων απελθων [ωρυξεν]{.greek-omitted} [ορηξεν]{.greek-added} εν τη γη και απεκρυψεν το αργυριον του [κυριου]{.greek-abbr} αυτου[25:18]{.aside}

μετα δε χρονον πολυν ερχεται ο [κυριος]{.greek-abbr} των δουλων εκεινων και [συναιρει]{.greek-omitted} [συνερει]{.greek-added} μετ αυτων λογον[25:19]{.aside}

και προσελθων ο τα [πεντε]{.greek-omitted} [[ε]{.greek-abbr}]{.greek-added} ταλαντα λαβων προσηνεγκεν αλλα πεντε ταλαντα λεγων [κυριε]{.greek-abbr} πεντε ταλαντα μοι παρεδωκας ιδε αλλα πεντε ταλαντα εκερδησα επ αυτοις[25:20]{.aside}

εφη [δε]{.greek-omitted} αυτω ο [κυριος]{.greek-abbr} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω εισελθε εις την χαραν του [κυριου]{.greek-abbr} σου[25:21]{.aside}

προσελθων δε [κ]{.greek-supplied}αι ο τα δυο ταλαντα [λαβων]{.greek-omitted} [ειληφως]{.greek-added} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} δυο ταλαντα μοι παρεδωκας ιδε αλλα δυο ταλαντα εκερδησα επ αυτοις[25:22]{.aside}

εφη αυτω ο [κυριος]{.greek-omitted} [κς]{.greek-added} αυτου ευ δουλε αγαθε και πιστε επι ολιγα ης πιστος επι πολλων σε καταστησω [εισελθε]{.greek-omitted} [εισηλθε]{.greek-added} εις την χαραν του [κυριου]{.greek-abbr} σου[25:23]{.aside}

προσελθων [δε]{.greek-omitted} και ο το εν [τα]{.greek-added} [ταλαντον]{.greek-omitted} [ειληφως]{.greek-omitted} [ειπεν]{.greek-omitted} [κυριε]{.greek-omitted} [εγνων]{.greek-omitted} [σε]{.greek-omitted} [οτι]{.greek-omitted} [σκληρος]{.greek-omitted} [ει]{.greek-omitted} [ανθρωπος]{.greek-omitted} [θεριζων]{.greek-omitted} [οπου]{.greek-omitted} [ουκ]{.greek-omitted} [εσπειρας]{.greek-omitted} [και]{.greek-omitted} [συναγων]{.greek-omitted} [οθεν]{.greek-omitted} [ου]{.greek-omitted} [διεσκορπισας]{.greek-omitted}[25:24]{.aside}

[προσελθων]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [το]{.greek-omitted} [εν]{.greek-omitted} [ταλαντον]{.greek-omitted} [λαντον]{.greek-added} ειληφως [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [κυριε]{.greek-abbr} εγνων σε οτι σκληρος [ει]{.greek-omitted} [συ]{.greek-added} [ανθρωπος]{.greek-abbr} θεριζων οπου ουκ εσπειρας και συναγων οθεν ου διεσκορπισας[25:24 | instance no. 2]{.aside}

και φοβηθεις απελθων εκρυψα το ταλαντον σου εν τη γη ιδε εχεις το σον[25:25]{.aside}

αποκριθεις δε ο [κυριος]{.greek-abbr} αυτου ειπεν αυτω πονηρε δουλε και οκνηρε [ηδεις]{.greek-omitted} [ιδεις]{.greek-added} οτι θεριζω οπου ουκ [εσπειρα]{.greek-omitted} [εσπηρα]{.greek-added} και [συναγω]{.greek-omitted} [συναγων]{.greek-added} οθεν ου διεσκορπισα[25:26]{.aside}

εδει ουν σε βαλειν το αργυριον μου τοις [τραπεζιταις]{.greek-omitted} [τραπεζηταις]{.greek-added} και ελθων [εγω]{.greek-omitted} εκομισαμην αν το [εμον]{.greek-omitted} [εμο]{.greek-added} συν τοκω[25:27]{.aside}

αρατε ουν απ αυτου το ταλαντον και [δοτε]{.greek-omitted} [δωται]{.greek-added} τω εχοντι τα δεκα ταλαντα[25:28]{.aside}

τω γαρ εχοντι παντι δοθησεται και περισσευθησεται απο δε του μη εχοντος και ο [δοκει]{.greek-added} εχει αρθησεται απ αυτου[25:29]{.aside}

και τον αχρειον δουλον [εκβαλετε]{.greek-omitted} [εκβαλεται]{.greek-added} εις το σκοτος το [εξωτερον]{.greek-omitted} [εξοτερον]{.greek-added} εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[25:30]{.aside}

οταν δε ελθη ο υιος του [ανθρωπου]{.greek-abbr} εν τη δοξη αυτου και παντες οι αγιοι αγγελοι μετ αυτου [τοτε]{.greek-omitted} [καθισει]{.greek-omitted} [επι]{.greek-omitted} [θρονου]{.greek-omitted} [δοξης]{.greek-omitted} [αυτου]{.greek-omitted}[25:31]{.aside}

[οταν]{.greek-omitted} [δε]{.greek-omitted} [ελθη]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δοξη]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [αγιοι]{.greek-omitted} [αγγελοι]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} τοτε καθισει επι θρονου δοξης αυτου[25:31 | instance no. 2]{.aside}

και [συναχθησεται]{.greek-omitted} [συναχθησονται]{.greek-added} εμπροσθεν αυτου παντα τα εθνη και [αφοριει]{.greek-omitted} [αφορισει]{.greek-added} αυτους απ αλληλων ωσπερ ο ποιμην αφοριζει τα [προβατα]{.greek-omitted} [αβατα]{.greek-added} απο των εριφων[25:32]{.aside}

και στησει τα μεν προβατα εκ δεξιων αυτου τα δε εριφια εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added}[25:33]{.aside}

τοτε ερει ο βασιλευς [τοις]{.greek-omitted} [της]{.greek-added} εκ δεξιων αυτου [δευτε]{.greek-omitted} [δευται]{.greek-added} οι ευλογημενοι του [πατρος]{.greek-abbr} μου [κληρονομησατε]{.greek-omitted} [κληρονομησαται]{.greek-added} την ητοιμασμενην [υμιν]{.greek-omitted} [ημιν]{.greek-added} βασιλειαν απο καταβολης κοσμου[25:34]{.aside}

[επεινασα]{.greek-omitted} [επινασα]{.greek-added} γαρ και εδωκατε μοι φαγειν εδιψησα και εποτισατε [με]{.greek-omitted} [μοι]{.greek-added} ξενος [ημην]{.greek-omitted} [ημιν]{.greek-added} και συνηγαγετε [με]{.greek-omitted} [μοι]{.greek-added}[25:35]{.aside}

γυμνος και περιεβαλετε [με]{.greek-omitted} [μοι]{.greek-added} ησθενησα και [επεσκεψασθε]{.greek-omitted} [επισκεψασθαι]{.greek-added} με εν φυλακη [ημην]{.greek-omitted} [ημιν]{.greek-added} και [ηλθετε]{.greek-omitted} [ηλθατε]{.greek-added} προς με[25:36]{.aside}

τοτε αποκριθησονται αυτω οι δικαιοι λεγοντες [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} [πεινωντα]{.greek-omitted} [πινοντα]{.greek-added} και εθρεψαμεν η διψωντα και εποτισαμεν[25:37]{.aside}

ποτε [δε]{.greek-omitted} σε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} ξενον και [συνηγαγομεν]{.greek-omitted} [συνηγαγωμεν]{.greek-added} η γυμνον και [περιεβαλομεν]{.greek-omitted} [περιεβαλλομεν]{.greek-added}[25:38]{.aside}

ποτε [δε]{.greek-omitted} σε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} [ασθενη]{.greek-omitted} [ασθενουντα]{.greek-added} η εν φυλακη και ηλθομεν προς σε[25:39]{.aside}

και αποκριθεις ο βασιλευς ερει αυτοις αμην λεγω υμιν εφ οσον [εποιησατε]{.greek-omitted} [εποιησαται]{.greek-added} ενι τουτων των αδελφων μου των ελαχιστων εμοι [εποιησατε]{.greek-omitted} [εποιησαται]{.greek-added}[25:40]{.aside}

τοτε ερει και τοις εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added} [πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} απ εμου οι κατηραμενοι εις το πυρ το αιωνιον το ητοιμασμενον [τω]{.greek-omitted} [το]{.greek-added} διαβολω και τοις αγγελοις αυτου[25:41]{.aside}

[επεινασα]{.greek-omitted} [επινασα]{.greek-added} γαρ και ουκ [εδωκατε]{.greek-omitted} [εδωκαται]{.greek-added} μοι φαγειν εδιψησα και ουκ εποτισατε [με]{.greek-omitted} [μοι]{.greek-added}[25:42]{.aside}

ξενος ημην και ου [συνηγαγετε]{.greek-omitted} [συνηγαγεται]{.greek-added} [με]{.greek-omitted} [μοι]{.greek-added} γυμνος και ου [περιεβαλετε]{.greek-omitted} [περιεβαλλεται]{.greek-added} [με]{.greek-omitted} [μοι]{.greek-added} ασθενης και εν φυλακη και ουκ [επεσκεψασθε]{.greek-omitted} [επεσκεψασθαι]{.greek-added} με[25:43]{.aside}

τοτε αποκριθησονται και αυτοι [λεγοντες]{.greek-omitted} [λεγωντες]{.greek-added} [κυριε]{.greek-abbr} ποτε σε [ειδομεν]{.greek-omitted} [ιδωμεν]{.greek-added} [πεινωντα]{.greek-omitted} [πινοντα]{.greek-added} η διψωντα [η]{.greek-omitted} [ξενον]{.greek-omitted} η γυμνον η ασθενη η εν φυλακη και ου διηκονησαμεν σοι[25:44]{.aside}

τοτε αποκριθησεται αυτοις λεγων αμην λεγω υμιν εφ οσον ουκ [εποιησατε]{.greek-omitted} [εποιησαται]{.greek-added} ενι τουτων των ελαχιστων ουδε εμοι [εποιησατε]{.greek-omitted} [εποιησαται]{.greek-added}[25:45]{.aside}

και απελευσονται ουτοι εις κολασιν αιωνιον οι δε δικαιοι [εις]{.greek-omitted} [ζωην]{.greek-omitted} [αιωνιον]{.greek-omitted}[25:46]{.aside}

[και]{.greek-omitted} [απελευσονται]{.greek-omitted} [ουτοι]{.greek-omitted} [εις]{.greek-omitted} [κολασιν]{.greek-omitted} [αιωνιον]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [δικαιοι]{.greek-omitted} εις ζωην αιωνιον[25:46 | instance no. 2]{.aside}

### Chapter 26

και εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} παντας τους λογους τουτους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου[26:1]{.aside}

[οιδατε]{.greek-omitted} [οιδαται]{.greek-added} οτι μετα δυο ημερας το πασχα γινεται και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις το [σταυρωθηναι]{.greek-abbr}[26:2]{.aside}

τοτε συνηχθησαν οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι του λαου εις την αυλην του [αρχιερεως]{.greek-omitted} [του]{.greek-omitted} [λεγομενου]{.greek-omitted} καιαφα[26:3]{.aside}

και συνεβουλευσαντο ινα τον [ιησουν]{.greek-abbr} δολω κρατησωσιν και [αποκτεινωσιν]{.greek-omitted} [αποκτενουσιν]{.greek-added}[26:4]{.aside}

ελεγον δε μη εν τη εορτη ινα μη θορυβος γενηται [εν]{.greek-omitted} τω λαω[26:5]{.aside}

του [δε]{.greek-omitted} [ιησου]{.greek-abbr} γενομενου εν βηθανια [εν]{.greek-omitted} [οικια]{.greek-omitted} σιμωνος του λεπρου[26:6]{.aside}

προσηλθεν αυτω γυνη αλαβαστρον μυρου εχουσα βαρυτιμου και κατεχεεν επι την κεφαλην αυτου ανακειμενου[26:7]{.aside}

ιδοντες δε οι μαθηται αυτου [ηγανακτησαν]{.greek-omitted} [ηγανακτισαν]{.greek-added} λεγοντες εις τι η απωλεια αυτη[26:8]{.aside}

ηδυνατο γαρ τουτο το μυρον πραθηναι πολλου και δοθηναι πτωχοις[26:9]{.aside}

γνους δε ο [ιησους]{.greek-abbr} ειπεν αυτοις τι κοπους [παρεχετε]{.greek-omitted} [παρεχεται]{.greek-added} τη γυναικι εργον γαρ καλον ειργασατο εις [εμε]{.greek-omitted} [εμοι]{.greek-added}[26:10]{.aside}

παντοτε [γαρ]{.greek-omitted} τους πτωχους [εχετε]{.greek-omitted} [εχεται]{.greek-added} μεθ εαυτων εμε δε ου παντοτε [εχετε]{.greek-omitted} [εχεται]{.greek-added}[26:11]{.aside}

βαλουσα [γαρ]{.greek-omitted} αυτη το μυρον τουτο επι του σωματος μου προς το ενταφιασαι με εποιησεν[26:12]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εν ολω τω κοσμω λαληθησεται και ο εποιησεν αυτη εις [μνημοσυνον]{.greek-omitted} [μαρτυριον]{.greek-added} αυτης[26:13]{.aside}

τοτε [πορευθεις]{.greek-omitted} [πορευθυς]{.greek-added} εις των δωδεκα ο λεγομενος ιουδας ισκαριωτης προς τους αρχιερεις[26:14]{.aside}

ειπεν τι [θελετε]{.greek-omitted} [θελεται]{.greek-added} μοι δουναι καγω υμιν [παραδωσω]{.greek-omitted} [παραδοσω]{.greek-added} αυτον [οι]{.greek-omitted} [η]{.greek-added} δε εστησαν [αυτω]{.greek-omitted} τριακοντα αργυρια[26:15]{.aside}

και απο τοτε εζητει ευκαιριαν ινα αυτον παραδω[26:16]{.aside}

τη δε [πρωτη]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} των αζυμων [προσηλθον]{.greek-omitted} [προσηλθων]{.greek-added} οι μαθηται τω [ιησου]{.greek-abbr} λεγοντες [αυτω]{.greek-omitted} [αυτο]{.greek-added} που θελεις [ετοιμασομεν]{.greek-omitted} [ετοιμασωμεν]{.greek-added} σοι φαγειν το πασχα[26:17]{.aside}

ο δε ειπεν [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} εις την πολιν προς τον δεινα και [ειπατε]{.greek-omitted} [ειπαται]{.greek-added} αυτω ο διδασκαλος λεγει ο καιρος μου εγγυς εστιν προς σε ποιω το πασχα μετα των μαθητων μου[26:18]{.aside}

[και]{.greek-omitted} εποιησαν [δε]{.greek-added} οι μαθηται ως συνεταξεν αυτοις ο [ιησους]{.greek-abbr} και ητοιμασαν το πασχα[26:19]{.aside}

οψιας δε γενομενης ανεκειτο μετα των δωδεκα[26:20]{.aside}

[και]{.greek-omitted} εσθιοντων αυτων ειπεν αμην λεγω υμιν οτι εις εξ υμων [παραδωσει]{.greek-omitted} [παραδοσει]{.greek-added} με[26:21]{.aside}

και λυπουμενοι σφοδρα ηρξαντο λεγειν [αυτω]{.greek-omitted} εκαστος αυτων μητι εγω ειμι [κυριε]{.greek-abbr}[26:22]{.aside}

ο δε αποκριθεις ειπεν [αυτοις]{.greek-added} ο εμβαψας μετ εμου εν τω τρυβλιω την χειρα ουτος με [παραδωσει]{.greek-omitted} [παραδοσει]{.greek-added}[26:23]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου [ουαι]{.greek-omitted} [δε]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [εκεινω]{.greek-omitted} [δι]{.greek-omitted} [ου]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδιδοται]{.greek-omitted} [καλον]{.greek-omitted} [ην]{.greek-omitted} [αυτω]{.greek-omitted} [ει]{.greek-omitted} [ουκ]{.greek-omitted} [εγεννηθη]{.greek-omitted} [ο]{.greek-omitted} [ανθρωπος]{.greek-omitted} [εκεινος]{.greek-omitted}[26:24]{.aside}

[ο]{.greek-omitted} [μεν]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [υπαγει]{.greek-omitted} [καθως]{.greek-omitted} [γεγραπται]{.greek-omitted} [περι]{.greek-omitted} [αυτου]{.greek-omitted} ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω [ει]{.greek-omitted} [η]{.greek-added} ουκ [εγεννηθη]{.greek-omitted} [εγενηθη]{.greek-added} ο [ανθρωπος]{.greek-abbr} εκεινος[26:24 | instance no. 2]{.aside}

εσθιοντων δε αυτων λαβων ο [ιησους]{.greek-abbr} [τον]{.greek-omitted} αρτον και ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις και ειπεν [λαβετε]{.greek-omitted} [λαβεται]{.greek-added} [φαγετε]{.greek-omitted} [φαγεται]{.greek-added} τουτο [μου]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[26:26]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον και ευχαριστησας εδωκεν αυτοις λεγων πιετε εξ αυτου παντες[26:27]{.aside}

τουτο [γαρ]{.greek-omitted} εστιν το αιμα μου το της καινης διαθηκης το περι πολλων [εκχυνομενον]{.greek-omitted} [εκχυννομενον]{.greek-added} εις αφεσιν αμαρτιων[26:28]{.aside}

λεγω δε υμιν [οτι]{.greek-omitted} ου μη πιω απ αρτι εκ [τουτου]{.greek-omitted} του [γεννηματος]{.greek-omitted} [γενηματος]{.greek-added} της αμπελου εως της ημερας εκεινης οταν [αυτο]{.greek-omitted} [αυτω]{.greek-added} [πινω]{.greek-omitted} [πινο]{.greek-added} μεθ υμων καινον εν τη βασιλεια του [πατρος]{.greek-abbr} μου[26:29]{.aside}

και υμνησαντες [εξηλθον]{.greek-omitted} [εξηλθεν]{.greek-added} εις το ορος των ελαιων[26:30]{.aside}

τοτε λεγει αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} παντες [υμεις]{.greek-omitted} [σκανδαλισθησεσθε]{.greek-omitted} [σκανδαλισθησεσθαι]{.greek-added} εν εμοι εν τη νυκτι ταυτη γεγραπται γαρ παταξω τον ποιμενα και διασκορπισθησεται τα προβατα της ποιμνης[26:31]{.aside}

μετα δε το εγερθηναι με προαξω υμας εις την γαλιλαιαν[26:32]{.aside}

αποκριθεις δε ο πετρος ειπεν αυτω ει παντες σκανδαλισθησονται εν σοι [αλλ]{.greek-added} εγω [δε]{.greek-omitted} ουδεποτε σκανδαλισθησομαι[26:33]{.aside}

εφη αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι εν ταυτη τη νυκτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρ]{.greek-added} φωνησαι τρις απαρνηση με[26:34]{.aside}

[λεγει]{.greek-omitted} [[―]{.gap}εγη]{.greek-added} [[λεγη]{.corr}]{.greek-added} αυτω ο πετρος καν δεη [με]{.greek-omitted} [μαι]{.greek-added} συν σοι αποθανειν ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ομοιως δε και παντες οι μαθηται [ειπον]{.greek-omitted} [ειπων]{.greek-added}[26:35]{.aside}

τοτε ερχεται μετ αυτων ο [ιησους]{.greek-abbr} εις χωριον [λεγομενον]{.greek-omitted} [λεγωμενον]{.greek-added} [γεθσημανη]{.greek-omitted} [γεθσημανι]{.greek-added} και λεγει [τοις]{.greek-omitted} [αυτοις]{.greek-added} [καθησαται]{.greek-added} [μαθηταις]{.greek-omitted} [καθισατε]{.greek-omitted} αυτου εως ου απελθων [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added} εκει[26:36]{.aside}

και [παραλαβων]{.greek-omitted} [παραλαμβανει]{.greek-added} τον πετρον και τους δυο υιους ζεβεδαιου ηρξατο [λυπεισθαι]{.greek-omitted} [λυπησθαι]{.greek-added} [και]{.greek-omitted} [αδημονειν]{.greek-omitted}[26:37]{.aside}

τοτε λεγει αυτοις ο [ιησους]{.greek-abbr} [περιλυπος]{.greek-omitted} [περιληπος]{.greek-added} εστιν η ψυχη μου εως θανατου [μεινατε]{.greek-omitted} [μειναται]{.greek-added} ωδε και [γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} μετ εμου[26:38]{.aside}

και προσελθων μικρον επεσεν επι προσωπον αυτου προσευχομενος και λεγων [πατερ]{.greek-abbr} μου ει δυνατον εστιν [παρελθετω]{.greek-omitted} [απελθετω]{.greek-added} [τουτο]{.greek-added} [το]{.greek-added} [ποτηριον]{.greek-added} απ εμου [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [τουτο]{.greek-omitted} πλην ουχ ως εγω θελω αλλ [ως]{.greek-omitted} [ω]{.greek-added} συ[26:39]{.aside}

και ερχεται προς τους μαθητας και ευρισκει αυτους [καθευδοντας]{.greek-omitted} [καθευδωντας]{.greek-added} και λεγει τω πετρω ουτως ουκ [ισχυσατε]{.greek-omitted} [ισχισαται]{.greek-added} μιαν ωραν [γρηγορησαι]{.greek-omitted} [αγρυπνισαι]{.greek-added} μετ εμου[26:40]{.aside}

[γρηγορειτε]{.greek-omitted} [γρηγορειται]{.greek-added} και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} ινα μη [εισελθητε]{.greek-omitted} [εισελθηται]{.greek-added} εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[26:41]{.aside}

παλιν εκ δευτερου [απελθων]{.greek-omitted} προσηυξατο λεγων [πατερ]{.greek-abbr} μου ει ου δυναται [τουτο]{.greek-omitted} το ποτηριον [τουτο]{.greek-added} παρελθειν απ εμου εαν μη [αυτο]{.greek-omitted} [αυτω]{.greek-added} [πιω]{.greek-omitted} [γενηθητω]{.greek-omitted} [το]{.greek-omitted} [θελημα]{.greek-omitted} [σου]{.greek-omitted}[26:42]{.aside}

[παλιν]{.greek-omitted} [εκ]{.greek-omitted} [δευτερου]{.greek-omitted} [απελθων]{.greek-omitted} [προσηυξατο]{.greek-omitted} [λεγων]{.greek-omitted} [πατερ]{.greek-omitted} [μου]{.greek-omitted} [ει]{.greek-omitted} [ου]{.greek-omitted} [δυναται]{.greek-omitted} [τουτο]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [παρελθειν]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [αυτο]{.greek-omitted} πιω γενηθητω το θελημα σου[26:42 | instance no. 2]{.aside}

και ελθων [παλιν]{.greek-added} ευρισκει αυτους [παλιν]{.greek-omitted} [καθευδοντας]{.greek-omitted} [καθευδωντας]{.greek-added} ησαν γαρ [αυτων]{.greek-omitted} οι οφθαλμοι [αυτων]{.greek-added} βεβαρημενοι[26:43]{.aside}

και αφεις αυτους [απελθων]{.greek-omitted} παλιν προσηυξατο [εκ]{.greek-omitted} [τριτου]{.greek-omitted} τον αυτον λογον ειπων[26:44]{.aside}

τοτε ερχεται προς τους μαθητας αυτου και λεγει αυτοις [καθευδετε]{.greek-omitted} [καθευδεται]{.greek-added} το λοιπον και [αναπαυεσθε]{.greek-omitted} [αναπαυεσθαι]{.greek-added} ιδου ηγγικεν η ωρα και ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται εις χειρας αμαρτωλων[26:45]{.aside}

[εγειρεσθε]{.greek-omitted} [εγειρεσθαι]{.greek-added} αγωμεν ιδου ηγγικεν ο παραδιδους με[26:46]{.aside}

και ετι αυτου λαλουντος ιδου ιουδας εις των δωδεκα ηλθεν και μετ αυτου οχλος [πολυς]{.greek-omitted} [πολλυς]{.greek-added} μετα μαχαιρων και ξυλων απο των αρχιερεων και πρεσβυτερων του λαου[26:47]{.aside}

ο δε παραδιδους αυτον εδωκεν αυτοις σημειον λεγων ον αν φιλησω αυτος εστιν [κρατησατε]{.greek-omitted} [κρατησαται]{.greek-added} αυτον[26:48]{.aside}

και ευθεως [προσελθων]{.greek-omitted} [προσηλθεν]{.greek-added} τω [ιησου]{.greek-abbr} [και]{.greek-added} ειπεν χαιρε [ραββι]{.greek-omitted} [ραμβι]{.greek-added} και κατεφιλησεν αυτον[26:49]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [εταιρε]{.greek-omitted} [ετερε]{.greek-added} εφ ω παρει τοτε [προσελθοντες]{.greek-omitted} [προσελθων]{.greek-added} επεβαλον τας χειρας επι τον [ιησουν]{.greek-abbr} και εκρατησαν αυτον[26:50]{.aside}

και ιδου εις των μετα [του]{.greek-added} [ιησου]{.greek-abbr} εκτεινας την [χειρα]{.greek-omitted} [χειραν]{.greek-added} απεσπασεν την μαχαιραν αυτου και παταξας τον δουλον του αρχιερεως αφειλεν αυτου το ωτιον [το]{.greek-added} [δεξιον]{.greek-added}[26:51]{.aside}

τοτε λεγει αυτω ο [ιησους]{.greek-abbr} αποστρεψον [σου]{.greek-omitted} την μαχαιραν εις [τον]{.greek-omitted} [τοπον]{.greek-omitted} [την]{.greek-added} [θηκην]{.greek-added} αυτης παντες γαρ οι [λαβοντες]{.greek-omitted} [λαβωντες]{.greek-added} μαχαιραν εν μαχαιρ[α]{.unclear} αποθανουνται[26:52]{.aside}

η δοκεις οτι ου δυναμαι αρτι παρακαλεσαι τον [πατερα]{.greek-abbr} μου και παραστησει μοι πλειους η δωδεκα λεγεωνας αγγελων[26:53]{.aside}

πως ουν πληρωθωσιν αι γραφαι [των]{.greek-added} [προφητων]{.greek-added} οτι ουτως [δει]{.greek-omitted} [δη]{.greek-added} γενεσθαι[26:54]{.aside}

εν εκεινη τη ωρα ειπεν ο [ιησους]{.greek-abbr} τοις οχλοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθαται]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν [με]{.greek-omitted} [μαι]{.greek-added} καθ ημεραν προς υμας εκαθεζομην [διδασκων]{.greek-omitted} εν τω ιερω [διδασκων]{.greek-added} και ουκ [εκρατησατε]{.greek-omitted} [εκρατισεται]{.greek-added} με[26:55]{.aside}

[τουτο]{.greek-omitted} [τουτον]{.greek-added} δε ολον γεγονεν ινα πληρωθωσιν αι γραφαι των προφητων τοτε οι μαθηται παντες αφεντες αυτον εφυγον[26:56]{.aside}

οι δε κρατησαντες τον [ιησουν]{.greek-abbr} [απηγαγον]{.greek-omitted} [ανηγαγον]{.greek-added} προς καιαφαν τον αρχιερεα οπου οι γραμματεις και οι πρεσβυτεροι συνηχθησαν[26:57]{.aside}

ο [δε]{.greek-omitted} πετρος [ηκολουθει]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω [απο]{.greek-omitted} μακροθεν εως της αυλης του αρχιερεως και εισελθων εσω εκαθητο μετα των υπηρετων ιδειν το τελος[26:58]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι και [ολον]{.greek-added} το συνεδριον [ολον]{.greek-omitted} εζητουν ψευδομαρτυριαν κατα του [ιησου]{.greek-abbr} οπως [θανατωσωσιν]{.greek-omitted} [θανατωσουσιν]{.greek-added} αυτον[26:59]{.aside}

και ουχ ευρον [και]{.greek-omitted} [[―]{.gap}στερον]{.greek-added} [[υστερον]{.corr}]{.greek-added} [δε]{.greek-added} πολλων [ψευδομαρτυρων]{.greek-omitted} προσελθοντων [ουχ]{.greek-omitted} [ευρον]{.greek-omitted} [δυο]{.greek-added} [ψευδομαρτυρες]{.greek-added}[26:60]{.aside}

[υστερον]{.greek-omitted} [δε]{.greek-omitted} [προσελθοντες]{.greek-omitted} [δυο]{.greek-omitted} [ψευδομαρτυρες]{.greek-omitted} ειπον ουτος εφη δυναμαι καταλυσαι τον ναον του [θεου]{.greek-abbr} και [δια]{.greek-omitted} [τριων]{.greek-omitted} [ημερων]{.greek-omitted} [εν]{.greek-added} [τρισιν]{.greek-added} [ημεραις]{.greek-added} οικοδομησαι αυτον[26:61]{.aside}

και αναστας ο αρχιερευς ειπεν αυτω ουδεν απ[ο]{.unclear}κρινη [τι]{.greek-omitted} [ουτοι]{.greek-omitted} [τοιουτοι]{.greek-added} σου καταμαρτυρουσιν[26:62]{.aside}

ο δε [ιησους]{.greek-abbr} εσιωπα και αποκριθεις ο αρχιερευς ειπεν αυτω [εξορκιζω]{.greek-omitted} [ορκιζω]{.greek-added} σε κατα του [θεου]{.greek-abbr} του ζωντος ινα ημιν [ειπης]{.greek-omitted} [ειπεις]{.greek-added} ει συ ει ο [χριστος]{.greek-omitted} [ο]{.greek-omitted} υιος του [θεου]{.greek-abbr} [του]{.greek-added} [ζωντος]{.greek-added}[26:63]{.aside}

λεγει αυτω ο [ιησους]{.greek-abbr} συ ειπας [πλην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [απ]{.greek-omitted} [αρτι]{.greek-omitted} [οψεσθε]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [καθημενον]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [και]{.greek-omitted} [ερχομενον]{.greek-omitted} [επι]{.greek-omitted} [των]{.greek-omitted} [νεφελων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[26:64]{.aside}

[αμην]{.greek-added} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [συ]{.greek-omitted} [ειπας]{.greek-omitted} [πλην]{.greek-omitted} λεγω υμιν [οτι]{.greek-added} απ αρτι [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} καθημενον εκ δεξιων της δυναμεως και ερχομενον επι των νεφελων του [ουρανου]{.greek-abbr}[26:64 | instance no. 2]{.aside}

τοτε ο αρχιερευς διερρηξεν τα ιματια αυτου λεγων οτι εβλασφημησεν τι ετι χρειαν εχομεν μαρτυρων ιδε νυν ηκουσατε την βλασφημιαν αυτου[26:65]{.aside}

τι υμιν δοκει οι δε αποκριθεντες [ειπον]{.greek-omitted} [ειπων]{.greek-added} ενοχος θανατου εστιν[26:66]{.aside}

τοτε ενεπτυσαν εις το προσωπον αυτου και [εκολαφισαν]{.greek-omitted} [εκολαφησαν]{.greek-added} αυτον οι δε [ερραπισαν]{.greek-omitted} [ερραπησαν]{.greek-added} [αυτον]{.greek-added}[26:67]{.aside}

λεγοντες προφητευσον ημιν [χριστε]{.greek-abbr} τις εστιν ο [παισας]{.greek-omitted} [παισα]{.greek-added} σε[26:68]{.aside}

ο δε πετρος εξω εκαθητο εν τη αυλη και προσηλθεν αυτω μια παιδισκη λεγουσα και συ ησθα μετα [ιησου]{.greek-abbr} του γαλιλαιου[26:69]{.aside}

ο δε ηρνησατο εμπροσθεν αυτων [παντων]{.greek-omitted} λεγων ουκ [οιδα]{.greek-omitted} [ειδα]{.greek-added} τι λεγεις[26:70]{.aside}

εξελθοντα δε αυτον εις τον πυλωνα ειδεν αυτον αλλη και λεγει [αυτοις]{.greek-omitted} εκει και [ουτος]{.greek-omitted} [ουτως]{.greek-added} ην μετα [ιησου]{.greek-abbr} του ναζωραιου[26:71]{.aside}

και παλιν [ηρνησατο]{.greek-omitted} [ηρνισατο]{.greek-added} μεθ ορκου οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr}[26:72]{.aside}

μετα μικρον [δε]{.greek-omitted} προσελθοντες οι εστωτες [ειπον]{.greek-omitted} [ειπων]{.greek-added} τω πετρω αληθως και συ εξ αυτων ει και γαρ η λαλια σου δηλον σε ποιει[26:73]{.aside}

τοτε ηρξατο καταθεματιζειν και ομνυειν οτι ουκ [οιδα]{.greek-omitted} [ειδα]{.greek-added} τον [ανθρωπον]{.greek-abbr} και ευθεως αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[26:74]{.aside}

και εμνησθη ο πετρος του ρηματος του [ιησου]{.greek-abbr} ειρηκοτος [αυτω]{.greek-omitted} οτι πριν αλεκτορα φωνησαι τρις απαρνηση με και εξελθων εξω εκλαυσεν πικρως[26:75]{.aside}

### Chapter 27

πρωιας δε γενομενης συμβουλιον [εποιησαν]{.greek-added} [ελαβον]{.greek-omitted} [παντες]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted} [του]{.greek-omitted} [λαου]{.greek-omitted} [κατα]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted} [ωστε]{.greek-omitted} [θανατωσαι]{.greek-omitted} [αυτον]{.greek-omitted}[27:1]{.aside}

[πρωιας]{.greek-omitted} [δε]{.greek-omitted} [γενομενης]{.greek-omitted} [συμβουλιον]{.greek-omitted} [ελαβον]{.greek-omitted} [παντες]{.greek-omitted} οι αρχιερεις και οι πρεσβυτεροι του λαου κατα του [ιησου]{.greek-abbr} [ωστε]{.greek-omitted} [ωσται]{.greek-added} θανατωσαι αυτον[27:1 | instance no. 2]{.aside}

και δησαντες αυτον απηγαγον και παρεδωκαν [αυτον]{.greek-omitted} ποντιω πιλατω τω ηγεμονι[27:2]{.aside}

τοτε ιδων [ο]{.greek-added} ιουδας ο παραδιδους αυτον οτι κατεκριθη μεταμεληθεις απεστρεψεν τα [τριακοντα]{.greek-omitted} [[λ]{.greek-abbr}]{.greek-added} αργυρια τοις αρχιερευσιν και τοις πρεσβυτεροις[27:3]{.aside}

λεγων ημαρτον παραδους αιμα αθωον οι δε [ειπον]{.greek-omitted} [ειπων]{.greek-added} τι προς [ημας]{.greek-omitted} [υμας]{.greek-added} συ οψει[27:4]{.aside}

και ριψας τα αργυρια εν τω ναω [ανεχωρησεν]{.greek-omitted} [υπεχωρησεν]{.greek-added} και απελθων απηγξατο[27:5]{.aside}

οι δε αρχιερεις λαβοντες τα αργυρια [ειπον]{.greek-omitted} [ειπων]{.greek-added} ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} βαλειν αυτα εις τον [κορβαναν]{.greek-omitted} [κορβοναν]{.greek-added} επει τιμη αιματος εστιν[27:6]{.aside}

συμβουλιον δε λαβοντες ηγορασαν εξ αυτων τον αγρον του κεραμεως εις ταφην τοις ξενοις[27:7]{.aside}

διο εκληθη ο αγρος εκεινος αγρος αιματος εως της [σημερον]{.greek-omitted} [ημερον]{.greek-added}[27:8]{.aside}

τοτε επληρωθη το ρηθεν δια ιερεμιου του προφητου λεγοντος και ελαβον τα [τριακοντα]{.greek-omitted} [[λ]{.greek-abbr}]{.greek-added} αργυρια την τιμην του τετιμημενου ον ετιμησαντο [[ετιμησαντο]{.corr}]{.greek-added} απο υιων [ισραηλ]{.greek-abbr}[27:9]{.aside}

και εδωκαν αυτα εις τον αγρον του κεραμεως καθα [συνεταξεν]{.greek-omitted} [συνεταξε]{.greek-added} μοι [κυριος]{.greek-abbr}[27:10]{.aside}

ο δε [ιησους]{.greek-abbr} εστη εμπροσθεν του ηγεμονος και επηρωτησεν αυτον ο ηγεμων λεγων συ ει ο βασιλευς των ιουδαιων ο δε [ιησους]{.greek-abbr} εφη αυτω συ [λεγεις]{.greek-omitted} [ειπας]{.greek-added}[27:11]{.aside}

και εν τω κατηγορεισθαι αυτον υπο των αρχιερεων και [των]{.greek-omitted} πρεσβυτερων ουδεν απεκρινατο[27:12]{.aside}

τοτε λεγει αυτω ο πιλατος ουκ ακουεις ποσα σου [καταμαρτυρουσιν]{.greek-omitted} [καταμαρτυρουσι]{.greek-added}[27:13]{.aside}

και [ουκ]{.greek-omitted} απεκριθη αυτω προς [ουδε]{.greek-omitted} [ουδεν]{.greek-added} [εν]{.greek-omitted} ρημα ωστε θαυμαζειν τον ηγεμονα [λιαν]{.greek-omitted}[27:14]{.aside}

[και]{.greek-omitted} [ουκ]{.greek-omitted} [απεκριθη]{.greek-omitted} [αυτω]{.greek-omitted} [προς]{.greek-omitted} [ουδε]{.greek-omitted} [εν]{.greek-omitted} [ρημα]{.greek-omitted} [ωστε]{.greek-omitted} [θαυμαζειν]{.greek-omitted} [τον]{.greek-omitted} [ηγεμονα]{.greek-omitted} λιαν[27:14 | instance no. 2]{.aside}

κατα δε εορτην ειωθει ο ηγεμων απολυειν ενα τω οχλω δεσμιον ον ηθελον[27:15]{.aside}

ειχον δε τοτε δεσμιον επισημον λεγομενον βαραββαν[27:16]{.aside}

συνηγμενων [ουν]{.greek-omitted} [δε]{.greek-added} αυτων ειπεν αυτοις ο πιλατος τινα [θελετε]{.greek-omitted} [θελεται]{.greek-added} απολυσω υμιν βαραββαν η [ιησουν]{.greek-abbr} τον λεγομενον [χριστον]{.greek-abbr}[27:17]{.aside}

ηδει γαρ οτι δια φθονον παρεδωκαν αυτον[27:18]{.aside}

καθημενου δε αυτου επι του βηματος απεστειλεν [προς]{.greek-omitted} [αυτον]{.greek-omitted} η γυνη αυτου [προς]{.greek-added} [αυτον]{.greek-added} λεγουσα μηδεν σοι και τω δικαιω [εκεινω]{.greek-omitted} [τουτω]{.greek-added} πολλα γαρ επαθον σημερον κατ οναρ δι αυτον[27:19]{.aside}

οι δε αρχιερεις και οι πρεσβυτεροι επεισαν τους οχλους ινα [αιτησωνται]{.greek-omitted} [αιτησονται]{.greek-added} τον [βαραββαν]{.greek-omitted} [βαραβαν]{.greek-added} τον δε [ιησουν]{.greek-abbr} απολεσωσιν[27:20]{.aside}

αποκριθεις δε ο ηγεμων ειπεν αυτοις τινα [θελετε]{.greek-omitted} [θελεται]{.greek-added} απο των δυο απολυσω υμιν οι δε ειπον βαραββαν[27:21]{.aside}

λεγει αυτοις ο πιλατος τι ουν ποιησω [ιησουν]{.greek-abbr} τον [λεγομενον]{.greek-omitted} [λεγωμενον]{.greek-added} [χριστον]{.greek-abbr} λεγουσιν αυτω παντες [σταυρωθητω]{.greek-abbr}[27:22]{.aside}

ιδων δε ο πιλατος οτι ουδεν [ωφελει]{.greek-omitted} [οφελει]{.greek-added} αλλα μαλλον θορυβος γινεται λαβων υδωρ [απενιψατο]{.greek-omitted} [απενυψατο]{.greek-added} τας χειρας [αυτου]{.greek-added} απεναντι του οχλου λεγων αθωος ειμι απο του αιματος του δικαιου τουτου υμεις [οψεσθε]{.greek-omitted} [οψεσθαι]{.greek-added}[27:24]{.aside}

και αποκριθεις πας ο [λαος]{.greek-omitted} [οχλος]{.greek-added} ειπεν το αιμα αυτου εφ ημας και επι τα τεκνα ημων[27:25]{.aside}

τοτε απελυσεν αυτοις τον βαραββαν τον δε [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγγελωσας]{.greek-added} παρεδωκεν ινα [σταυρωθη]{.greek-abbr}[27:26]{.aside}

τοτε οι στρατιωται του [ηγεμονος]{.greek-omitted} [ηγεμωνος]{.greek-added} παραλαβοντες τον [ιησουν]{.greek-abbr} εις το [πραιτωριον]{.greek-omitted} [πραιτοριον]{.greek-added} συνηγαγον επ αυτον ολην την σπειραν[27:27]{.aside}

και [εκδυσαντες]{.greek-omitted} [εκδησαντες]{.greek-added} αυτον περιεθηκαν αυτω χλαμ[υ]{.unclear}δα [[χλαμ[ι]{.unclear}δα]{.corr}]{.greek-added} [κοκκινην]{.greek-omitted} [κοκινην]{.greek-added}[27:28]{.aside}

και πλεξαντες στεφανον εξ ακανθων επεθηκαν επι την κεφαλην αυτου και καλαμον επι την δεξιαν αυτου και [γονυπετησαντες]{.greek-omitted} [γονυπαιτησαντες]{.greek-added} εμπροσθεν αυτου [ενεπαιζον]{.greek-omitted} [επαιζον]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added} λεγοντες χαιρ[ε]{.unclear} [ο]{.unclear} βασιλευς των ιουδαιων[27:29]{.aside}

και εμπτυσαντες εις αυτον ελαβον τον καλαμον και ετυπτον [εις]{.greek-omitted} [επι]{.greek-added} την κεφαλην αυτου[27:30]{.aside}

και οτε ενεπαιξαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον την [χλαμυδα]{.greek-omitted} [χλαμιδα]{.greek-added} και ενεδυσαν αυτον τα ιματια αυτου και απηγαγον [αυτον]{.greek-omitted} εις το [σταυρωσαι]{.greek-abbr}[27:31]{.aside}

εξερχομενοι δε ευρον [ανθρωπον]{.greek-abbr} κυρηναιον ονοματι σιμωνα τουτον [ηγγαρευσαν]{.greek-omitted} [ηγκαρευσαν]{.greek-added} ινα αρη τον [σταυρον]{.greek-abbr} αυτου[27:32]{.aside}

και ελθοντες εις τοπον λεγομενον [γολγοθα]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [λεγομενος]{.greek-omitted} κρανιου τοπος[27:33]{.aside}

εδωκαν αυτω [πιειν]{.greek-omitted} [ποιειν]{.greek-added} οξος μετα χολης [μεμιγμενον]{.greek-omitted} [μεμειγμενον]{.greek-added} και γευσαμενος ουκ ηθελεν [πιειν]{.greek-omitted} [ποιειν]{.greek-added}[27:34]{.aside}

[σταυρωσαντες]{.greek-abbr} δε αυτον διεμερισαντο τα ιματια αυτου βαλλοντες κληρον [επ]{.greek-added} [αυτα]{.greek-added}[27:35]{.aside}

και καθημενοι ετηρουν αυτον εκει[27:36]{.aside}

και επεθηκαν επανω της κεφαλης αυτου την [αιτιαν]{.greek-omitted} [ετιαν]{.greek-added} αυτου γεγραμμενην ουτος εστιν [ιησους]{.greek-omitted} ο βασιλευς των ιουδαιων[27:37]{.aside}

τοτε [σταυρουνται]{.greek-abbr} συν αυτω δυο λησται εις εκ δεξιων και εις εξ [ευωνυμων]{.greek-omitted} [ευονυμων]{.greek-added}[27:38]{.aside}

οι δε παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων[27:39]{.aside}

και λεγοντες ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων σωσον σεαυτον ει υιος ει του [θεου]{.greek-abbr} [καταβηθι]{.greek-omitted} [καταβιθη]{.greek-added} απο του [σταυρου]{.greek-abbr}[27:40]{.aside}

ομοιως δε και οι αρχιερεις εμπαιζοντες μετα των [γραμματεων]{.greek-omitted} [και]{.greek-omitted} πρεσβυτερων και φαρισαιων [και]{.greek-added} [γραμματεων]{.greek-added} [ελεγον]{.greek-omitted} [ελεγων]{.greek-added}[27:41]{.aside}

αλλους εσωσεν εαυτον ου δυναται σωσαι [ει]{.greek-omitted} [οι]{.greek-added} βασιλευς [ισραηλ]{.greek-abbr} εστιν καταβατω νυν απο του [σταυρου]{.greek-abbr} και [πιστευσομεν]{.greek-omitted} [πιστευσωμεν]{.greek-added} [επ]{.greek-omitted} [αυτω]{.greek-omitted} [εις]{.greek-added} [αυτον]{.greek-added}[27:42]{.aside}

πεποιθεν επι τον [θεον]{.greek-abbr} ρυσασθω [νυν]{.greek-omitted} αυτον ει θελει αυτον [ειπεν]{.greek-omitted} [ειπε]{.greek-added} γαρ οτι [θεου]{.greek-abbr} ειμι υιος[27:43]{.aside}

το δ αυτο και οι λησται οι [συσταυρωθεντες]{.greek-abbr} [αυτω]{.greek-omitted} [ωνειδιζον]{.greek-omitted} [ονειδιζον]{.greek-added} αυτον[27:44]{.aside}

απο δε [εκτης]{.greek-omitted} [[ϛ]{.greek-abbr}]{.greek-added} ωρας σκοτος εγενετο επι πασαν την γην εως ωρας [ενατης]{.greek-omitted} [[θ]{.greek-abbr}]{.greek-added}[27:45]{.aside}

περι δε την [ενατην]{.greek-omitted} [[θ]{.greek-abbr}]{.greek-added} ωραν ανεβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ηλι ηλι λιμα σαβαχθανι τουτ εστιν θεε μου θεε μου [ινα]{.greek-omitted} [ινατι]{.greek-added} [τι]{.greek-omitted} με εγκατελιπες[27:46]{.aside}

τινες δε των εκει εστωτων ακουσαντες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added} οτι ηλιαν φωνει [ουτος]{.greek-omitted} [ουτως]{.greek-added}[27:47]{.aside}

και ευθεως δραμων εις εξ αυτων και λαβων σπογγον πλησας τε οξους και περιθεις καλαμω εποτιζεν αυτον[27:48]{.aside}

οι δε λοιποι ελεγον αφες ιδωμεν ει ερχεται ηλιας σωσων αυτον[27:49]{.aside}

ο δε [ιησους]{.greek-abbr} παλιν κραξας φωνη μεγαλη αφηκεν το [πνευμα]{.greek-abbr}[27:50]{.aside}

και ιδου το καταπετασμα του ναου [εσχισθη]{.greek-omitted} [εσχινθην]{.greek-added} εις δυο απο ανωθεν εως [κατω]{.greek-omitted} [κατωθεν]{.greek-added} και η γη εσεισθη και [αι]{.greek-omitted} πετραι εσχισθησαν[27:51]{.aside}

και τα μνημεια [ανεωχθησαν]{.greek-omitted} [ηνεωχθησαν]{.greek-added} και πολλα σωματα των κεκοιμημενων αγιων [ηγερθη]{.greek-omitted} [ηγερθησαν]{.greek-added}[27:52]{.aside}

και εξελθοντες εκ των μνημειων μετα την εγερσιν αυτου [εισηλθον]{.greek-omitted} [εισηλθεν]{.greek-added} εις την αγιαν πολιν και ενεφανισθησαν πολλοις[27:53]{.aside}

ο δε εκατονταρχος και οι μετ αυτου τηρουντες τον [ιησουν]{.greek-abbr} ιδοντες τον σεισμον και τα γενομενα εφοβηθησαν σφοδρα λεγοντες αληθως [θεου]{.greek-abbr} υιος ην ουτος[27:54]{.aside}

ησαν δε [εκει]{.greek-omitted} [και]{.greek-added} γυναικες πολλαι [απο]{.greek-omitted} [ααπο]{.greek-added} μακροθεν [θεωρουσαι]{.greek-omitted} [θεορουσαι]{.greek-added} αιτινες ηκολουθησαν τω [ιησου]{.greek-abbr} απο της γαλιλαιας διακονουσαι αυτω[27:55]{.aside}

εν αις ην μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου και [ιωση]{.greek-omitted} [ιωσηφ]{.greek-added} [μητηρ]{.greek-abbr} και η [μητηρ]{.greek-abbr} των υιων ζεβεδαιου[27:56]{.aside}

οψιας δε γενομενης ηλθεν [ανθρωπος]{.greek-abbr} πλουσιος απο αριμαθαιας τουνομα ιωσηφ ος και αυτος εμαθητευσεν τω [ιησου]{.greek-abbr}[27:57]{.aside}

ουτος προσελθων τω πιλατω [ητησατο]{.greek-omitted} [ητησαι]{.greek-added} το σωμα του [ιησου]{.greek-abbr} τοτε ο πιλατος εκελευσεν [αποδοθηναι]{.greek-omitted} [αποδωθηναι]{.greek-added} το σωμα[27:58]{.aside}

και λαβων [ο]{.greek-added} [ιωσηφ]{.greek-added} το σωμα [ο]{.greek-omitted} [ιωσηφ]{.greek-omitted} [ενετυλιξεν]{.greek-omitted} [ενετυληξεν]{.greek-added} [αυτο]{.greek-omitted} [αυτω]{.greek-added} [σινδονι]{.greek-omitted} [σινδωνι]{.greek-added} καθαρα[27:59]{.aside}

και εθηκεν [αυτο]{.greek-omitted} [αυτω]{.greek-added} εν τω καινω αυτου μνημειω [ο]{.greek-omitted} [ος]{.greek-added} ελατομησεν εν τη πετρα και [προσκυλισας]{.greek-omitted} [προσκυλησας]{.greek-added} [λιθω]{.greek-added} [λιθον]{.greek-omitted} [μεγαν]{.greek-omitted} τη θυρα [μετα]{.greek-added} του μνημειου απηλθεν[27:60]{.aside}

ην δε εκει μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη [μαρια]{.greek-omitted} καθημεναι απεναντι του ταφου[27:61]{.aside}

τη δε επαυριον [ητις]{.greek-omitted} [ειτις]{.greek-added} εστιν μετα την παρασκευην συνηχθησαν οι αρχιερεις και οι φαρισαιοι προς πιλατον[27:62]{.aside}

λεγοντες [κυριε]{.greek-abbr} εμνησθημεν οτι εκεινος ο πλανος ειπεν ετι ζων μετα τρεις ημερας εγειρομαι[27:63]{.aside}

κελευσον ουν [ασφαλισθηναι]{.greek-omitted} [ασφαλιστηναι]{.greek-added} τον ταφον [εως]{.greek-omitted} [της]{.greek-omitted} [τριτης]{.greek-omitted} [ημερας]{.greek-omitted} μηποτε ελθοντες οι μαθηται αυτου [νυκτος]{.greek-omitted} κλεψωσιν αυτον [νυκτος]{.greek-added} και ειπωσιν τω λαω ηγερθη απο των νεκρων και εσται η [εσχατη]{.greek-omitted} [πλανη]{.greek-omitted} [αισχατοι]{.greek-added} [πλανοι]{.greek-added} [χειρων]{.greek-omitted} [χειρον]{.greek-added} [της]{.greek-omitted} [τοις]{.greek-added} πρωτης[27:64]{.aside}

εφη [δε]{.greek-omitted} αυτοις ο πιλατος [εχετε]{.greek-omitted} [εχεται]{.greek-added} [κουστωδιαν]{.greek-omitted} [κουστωδια]{.greek-added} [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} [ασφαλισασθε]{.greek-omitted} [ασφαλισαται]{.greek-added} ως [οιδατε]{.greek-omitted} [ιδαται]{.greek-added}[27:65]{.aside}

οι δε πορευθεντες ησφαλισαντο τον ταφον [σφραγισαντες]{.greek-omitted} [σφραγυσαντες]{.greek-added} τον λιθον μετα της κουστωδιας [αυτων]{.greek-added}[27:66]{.aside}

### Chapter 28

οψε δε [σαββατων]{.greek-omitted} [σαββατον]{.greek-added} τη [επιφωσκουση]{.greek-omitted} [επιφασκουση]{.greek-added} εις μιαν [σαββατων]{.greek-omitted} [σαββατου]{.greek-added} ηλθεν μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και η αλλη μαρια [θεωρησαι]{.greek-omitted} [θεωρισαι]{.greek-added} τον ταφον[28:1]{.aside}

και ιδου σεισμος εγενετο μεγας αγγελος γαρ [κυριου]{.greek-abbr} καταβας εξ [ουρανου]{.greek-abbr} προσελθων απεκυλισεν τον λιθον απο της θυρας [του]{.greek-added} [μνημειου]{.greek-added} και εκαθητο επανω αυτου[28:2]{.aside}

ην δε η ιδεα αυτου ως αστραπη και το ενδυμα αυτου λευκον ωσει χιων[28:3]{.aside}

απο δε του φοβου αυτου εσεισθησαν οι τηρουντες και εγενοντο ωσει νεκροι[28:4]{.aside}

[αποκριθεις]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-added} [ειπεν]{.greek-added} ο αγγελος [ειπεν]{.greek-omitted} ταις [γυναιξιν]{.greek-omitted} [γυναιξι]{.greek-added} μη φοβεισθε υμεις [οιδα]{.greek-omitted} [ηδα]{.greek-added} γαρ [οτι]{.greek-omitted} [οτιν]{.greek-added} [ιησουν]{.greek-omitted} τον [εσταυρωμενον]{.greek-abbr} [ζητειτε]{.greek-omitted} [ζητειται]{.greek-added}[28:5]{.aside}

ουκ εστιν ωδε ηγερθη [γαρ]{.greek-omitted} καθως ειπεν δευτε ιδετε τον τοπον οπου εκειτο ο [κυριος]{.greek-abbr}[28:6]{.aside}

και ταχυ [πορευθεισαι]{.greek-omitted} [πορευθησαι]{.greek-added} ειπατε τοις μαθηταις αυτου οτι ηγερθη απο των νεκρων και ιδου προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε ιδου ειπον υμιν[28:7]{.aside}

και εξελθουσαι ταχυ απο του μνημειου μετα φοβου και χαρας μεγαλης εδραμον απαγγειλαι τοις μαθηταις [αυτου]{.greek-omitted}[28:8]{.aside}

ως δε επορευοντο απαγγειλαι τοις μαθηταις αυτου και ιδου [ο]{.greek-added} [ιησους]{.greek-abbr} απηντησεν αυταις λεγων [χαιρετε]{.greek-omitted} [χαιρεται]{.greek-added} αι δε προσελθουσαι εκρατησαν αυτου τους ποδας και προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[28:9]{.aside}

[τοτε]{.greek-omitted} λεγει αυταις ο [ιησους]{.greek-abbr} μη [φοβεισθε]{.greek-omitted} [φοβεισθαι]{.greek-added} [υπαγετε]{.greek-omitted} [υπαγεται]{.greek-added} [απαγγειλατε]{.greek-omitted} [απαγγηλαται]{.greek-added} τοις αδελφοις μου ινα απελθωσιν εις την γαλιλαιαν [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} με οψονται[28:10]{.aside}

πορευομενων δε αυτων ιδου τινες της κουστωδιας ελθοντες εις την πολιν απηγγειλαν τοις αρχιερευσιν απαντα τα γενομενα[28:11]{.aside}

και συναχθεντες μετα των πρεσβυτερων συμβουλιον τε λαβοντες αργυρια ικανα εδωκαν τοις στρατιωταις[28:12]{.aside}

λεγοντες [ειπατε]{.greek-omitted} [ειπαται]{.greek-added} οτι οι μαθηται αυτου [νυκτος]{.greek-omitted} ελθοντες εκλεψαν αυτον ημων κοιμωμενων[28:13]{.aside}

και εαν ακουσθη τουτο επι του [ηγεμονος]{.greek-omitted} [ηγεμωνος]{.greek-added} ημεις [πεισομεν]{.greek-omitted} [πισωμεν]{.greek-added} αυτον και [υμας]{.greek-omitted} [ημας]{.greek-added} αμεριμνους [ποιησομεν]{.greek-omitted} [ποιησωμεν]{.greek-added}[28:14]{.aside}

οι δε λαβοντες τα αργυρια εποιησαν ως εδιδαχθησαν και διεφημισθη [ουτος]{.greek-added} ο λογος [ουτος]{.greek-omitted} παρα ιουδαιοις μεχρι [και]{.greek-added} της σημερον[28:15]{.aside}

οι δε ενδεκα μαθηται επορευθησαν εις την γαλιλαιαν εις το ορος ου εταξατο αυτοις ο [ιησους]{.greek-abbr}[28:16]{.aside}

και ιδοντες αυτον προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} οι δε εδιστασαν[28:17]{.aside}

και προσελθων ο [ιησους]{.greek-abbr} ελαλησεν αυτοις λεγων [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} μοι πασα εξουσια εν [ουρανω]{.greek-abbr} και επι γης[28:18]{.aside}

πορευθεντες [μαθητευσατε]{.greek-omitted} [μαθητευσαται]{.greek-added} παντα τα εθνη βαπτιζοντες αυτους εις το ονομα του [πατρος]{.greek-abbr} και του υιου και του αγιου [πνευματος]{.greek-abbr}[28:19]{.aside}

διδασκοντες αυτους τηρειν παντα οσα ενετειλαμην υμιν και ιδου εγω μεθ υμων [ειμι]{.greek-omitted} [ειμιν]{.greek-added} πασας τας ημερας εως της συντελειας του αιωνος αμην[28:20]{.aside}

