---
title: "Collation of Byz^RP^ vs 32201 (2201)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2201 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32201).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2201                                   	| λογος                              	|
| 2201 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2201 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2201               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2201                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2201 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2201                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου [τω]{.greek-omitted} [τωι]{.greek-added} [δουλω]{.greek-omitted} [δουλωι]{.greek-added} αυτου [ιωαννη]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[1:1]{.aside}

ος [εμαρτυρησεν]{.greek-omitted} [εμαρτυρησε]{.greek-added} τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ειδε]{.greek-added} [και]{.greek-added} [ατινα]{.greek-added} [εισι]{.greek-added} [και]{.greek-added} [αχρη]{.greek-added} [γενεσθαι]{.greek-added} [μετα]{.greek-added} [ταυτα]{.greek-added}[1:2]{.aside}

μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

[ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ταις επτα εκκλησιαις [ταις]{.greek-omitted} εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [πνευματων]{.greek-abbr} α ενωπιον του θρονου αυτου [εστι]{.greek-added}[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} [ο]{.greek-omitted} [ος]{.greek-added} μαρτυς [ο]{.greek-omitted} πιστος [εστι]{.greek-added} ο πρωτοτοκος των νεκρων και ο αρχων των βασιλεων της γης [τω]{.greek-omitted} [αγαπωντι]{.greek-omitted} [ος]{.greek-added} [ηγαπησεν]{.greek-added} ημας και [λουσαντι]{.greek-omitted} [ελουσεν]{.greek-added} ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας βασιλειαν [και]{.greek-added} ιερεις τω [θεω]{.greek-abbr} και [πατρι]{.greek-abbr} αυτου [αυτω]{.greek-omitted} [αυτωι]{.greek-added} η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και οψεται αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται επ αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το αλφα και το [ω]{.greek-abbr} [η]{.greek-added} [αρχη]{.greek-added} [και]{.greek-added} [το]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων [και]{.corr} [ο]{.greek-omitted} [ην]{.corr} και ο ερχομενος [ο]{.greek-omitted} παντοκρατωρ[1:8]{.aside}

εγω [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συγκοινωνος]{.greek-added} εν τη θλιψει και βασιλεια και υπομονη [εν]{.greek-omitted} [χριστω]{.greek-omitted} [ιησου]{.greek-abbr} [[χριστου]{.greek-abbr}]{.greek-added} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και [δια]{.greek-omitted} την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-omitted}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα [φωνην]{.greek-omitted} οπισω μου [φωνην]{.greek-added} μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης [εγω]{.greek-added} [ειμι]{.greek-added} [αλφα]{.greek-added} [και]{.greek-added} [ω]{.greek-added} [προτος]{.greek-added} [και]{.greek-added} [εσχατος]{.greek-added} [και]{.greek-added} ο βλεπεις γραψον εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις σμυρναν και εις περγαμον και εις θυατειρα και εις σαρδεις και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

και [εκει]{.greek-omitted} επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας ειδον [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} λυχνιας χρυσας[1:12]{.aside}

και εν μεσω των [επτα]{.greek-omitted} λυχνιων ομοιον υιω [ανθρωπου]{.greek-abbr} [ενδεδυμενον]{.greek-omitted} [ενδεδημενον]{.greek-added} ποδηρη και περιεζωσμενον προς τοις [μαστοις]{.greek-omitted} [μαζοις]{.greek-added} ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι [ως]{.greek-omitted} [ωσει]{.greek-added} εριον λευκον ως χιων και οι οφθαλμοι αυτου [ως]{.greek-omitted} φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι χαλκολιβανω ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια [χειρι]{.greek-added} αυτου [χειρι]{.greek-omitted} αστερας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και εκ του στοματος αυτου ρομφαια διστομος οξεια εκπορευομενη και η οψις αυτου ως ο ηλιος φαινει εν τη δυναμει αυτου[1:16]{.aside}

και οτε ειδον αυτον επεσα προς τους ποδας αυτου ως νεκρος και [εθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} την δεξιαν αυτου [χειρα]{.greek-added} επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας κλεις του [θανατου]{.greek-omitted} [αδου]{.greek-added} και του [αδου]{.greek-omitted} [θανατου]{.greek-added}[1:18]{.aside}

γραψον ουν α ειδες και α [εισιν]{.greek-omitted} [εισι]{.greek-added} και α μελλει [γινεσθαι]{.greek-omitted} [γενεσθαι]{.greek-added} μετα ταυτα[1:19]{.aside}

### Chapter 2

τω αγγελω της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον [σου]{.greek-omitted} και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added} και ευρες αυτους ψευδεις[2:2]{.aside}

[και]{.greek-added} [εβαστασας]{.greek-added} και υπομονην εχεις [και]{.greek-omitted} [εβαστασας]{.greek-omitted} δια το ονομα μου και [ουκ]{.greek-omitted} [οὐκ]{.greek-added} [εκοπιασας]{.greek-omitted} [ἐκοπίασας]{.greek-added}[2:3]{.aside}

[αλλα]{.greek-omitted} [αλλ]{.greek-added} εχω κατα σου οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν [εκ]{.greek-added} πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και κινησω την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω μισω[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν [μεσω]{.greek-added} τω παραδεισω του [θεου]{.greek-abbr} [μου]{.greek-omitted}[2:7]{.aside}

και τω αγγελω της εν σμυρνη εκκλησιας γραψον ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και [την]{.greek-omitted} πτωχειαν αλλα πλουσιος ει και την βλασφημιαν [εκ]{.greek-omitted} των λεγοντων ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις [παθειν]{.greek-omitted} [πασχειν]{.greek-added} ιδου [δη]{.greek-omitted} μελλει [βαλειν]{.greek-omitted} [βαλλεῖν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και [εξετε]{.greek-omitted} [εχητε]{.greek-added} θλιψιν ημερων δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο νικων ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας γραψον ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις εν αις [αντιπας]{.greek-omitted} [ἀντίπας]{.greek-added} ο μαρτυς [μου]{.greek-omitted} ο [πιστος]{.greek-added} [ο[τε]{.unclear}]{.greek-added} [πας]{.greek-added} [μαρτυς]{.greek-added} πιστος ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

αλλ εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος [εδιδαξεν]{.greek-omitted} [εδιδασκεν]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [βαλααμ]{.greek-added} τον [βαλακ]{.greek-omitted} [βαλαακ]{.greek-added} βαλειν σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} [και]{.greek-omitted} φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον [ουν]{.greek-omitted} ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν [τη]{.greek-omitted} [τηι]{.greek-added} ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω [φαγειν]{.greek-added} [απο]{.greek-added} του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν θυατειροις εκκλησιας γραψον ταδε λεγει ο υιος του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι χαλκολιβανω[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την πιστιν και την διακονιαν και την υπομονην [σου]{.greek-omitted} και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

αλλ εχω κατα σου οτι αφεις την γυναικα σου ιεζαβελ η λεγει εαυτην προφητιν και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν ειδωλοθυτα[2:20]{.aside}

και εδωκα αυτη χρονον ινα μετανοηση και ου θελει μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου βαλλω αυτην εις κλινην και τους μοιχευοντας μετ αυτης εις θλιψιν μεγαλην εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο [ερευνων]{.greek-omitted} [εραυνων]{.greek-added} νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν θυατειροις οσοι ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βάθη]{.greek-added} του σατανα ως λεγουσιν ου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων αχρι τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα κεραμικα συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας γραψον ταδε λεγει ο εχων τα [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} πνευματα του [θεου]{.greek-abbr} και τους [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αστερας οιδα σου τα εργα οτι ονομα εχεις [οτι]{.greek-omitted} [και]{.greek-added} ζης και νεκρος ει[3:1]{.aside}

γινου γρηγορων και στηρισον τα λοιπα α εμελλες [αποβαλλειν]{.greek-omitted} [αποβαλειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} [μου]{.greek-omitted}[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη γρηγορησης ηξω επι σε ως κλεπτης και ου μη γνως ποιαν ωραν ηξω επι σε[3:3]{.aside}

αλλ ολιγα εχεις ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και [περιπατησουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων ουτος περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της [βιβλου]{.greek-omitted} [βιλου]{.greek-added} της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν φιλαδελφεια εκκλησιας γραψον ταδε λεγει ο αγιος ο αληθινος ο εχων την κλειν του [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει αυτην ει μη ο ανοιγων και ουδεις ανοιξει[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις δυναμιν και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν ενωπιον των ποδων σου και γνωσιν οτι [εγω]{.greek-added} ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας επι της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

ο νικων ποιησω αυτον στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του [θεου]{.greek-abbr} μου και το ονομα της πολεως του [θεου]{.greek-abbr} μου της καινης [ιερουσαλημ]{.greek-abbr} [η]{.greek-omitted} [καταβαινει]{.greek-omitted} [της]{.greek-added} [καταβαινουσης]{.greek-added} εκ του ουρανου απο του [θεου]{.greek-abbr} μου και το ονομα μου το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν λαοδικεια εκκλησιας γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος και αληθινος η αρχη της [κτισεως]{.greek-omitted} [πιστεως]{.greek-added} του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε [ψυχρος]{.greek-omitted} [ζεστος]{.greek-added} ει ουτε [ζεστος]{.greek-omitted} [ψυχρος]{.greek-added} οφελον ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και [ου]{.greek-omitted} [ουτε]{.greek-added} ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και πεπλουτηκα και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο ταλαιπωρος και ο ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

συμβουλευω σοι αγορασαι χρυσιον παρ εμου πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη φανερωθη η αισχυνη της γυμνοτητος σου και [κολλυριον]{.greek-omitted} [κολλουριον]{.greek-added} [ινα]{.greek-omitted} [εγχριση]{.greek-omitted} [εγχρισον]{.greek-added} [επι]{.greek-added} τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω ζηλωσον ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν [και]{.greek-omitted} εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

ο νικων δωσω αυτω καθισαι μετ εμου εν τω θρονω μου ως καγω ενικησα και εκαθισα μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου [λεγων]{.greek-omitted} [λεγουσα]{.greek-added} αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

και ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι [τον]{.greek-omitted} [του]{.greek-added} [θρονον]{.greek-omitted} [θρονου]{.greek-added} καθημενος[4:2]{.aside}

ομοιος ορασει λιθω ιασπιδι και σαρδιω και [η]{.greek-added} [ιρις]{.greek-omitted} [ἴρις]{.greek-added} κυκλοθεν του θρονου [ομοιως]{.greek-omitted} [ομοιος]{.greek-added} [ορασις]{.greek-omitted} [ορασει]{.greek-added} [σμαραγδινων]{.greek-omitted} [σμαραγδινω]{.greek-added}[4:3]{.aside}

και κυκλοθεν του θρονου θρονοι εικοσι τεσσαρες και επι τους θρονους [ειδον]{.greek-added} τους εικοσι τεσσαρας πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου αι εισιν επτα πνευματα του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα υαλινη ομοια [κρυσταλλω]{.greek-omitted} [κρυσταλλων]{.greek-added} και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα γεμοντα οφθαλμων εμπροσθεν και οπισθεν[4:6]{.aside}

και το ζωον το πρωτον ομοιον λεοντι και το δευτερον ζωον ομοιον [μοσχω]{.greek-omitted} [μοσχωι]{.greek-added} και το τριτον ζωον εχον [το]{.greek-added} προσωπον [ως]{.greek-added} [ανθρωπου]{.greek-omitted} [[ανθρωπος]{.greek-abbr}]{.greek-added} και το τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν [αυτων]{.greek-added} εχον ανα πτερυγας εξ κυκλοθεν και εσωθεν γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος [λεγοντες]{.greek-omitted} [λεγοντα]{.greek-added} αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσουσι]{.greek-added} [δωσιν]{.greek-omitted} [τα]{.greek-omitted} [ζωα]{.greek-omitted} δοξαν και τιμην και ευχαριστιαν τω καθημενω επι του θρονου [τω]{.greek-omitted} [και]{.greek-added} ζωντι εις τους αιωνας των αιωνων[4:9]{.aside}

πεσουνται οι εικοσι τεσσαρες πρεσβυτεροι ενωπιον του καθημενου επι του θρονου [και]{.corr} [προσκυνησουσιν]{.greek-omitted} [[προσκυνησουσι]{.corr}]{.greek-added} [τω]{.corr} [ζωντι]{.corr} [εις]{.corr} [τους]{.corr} [[αι]{.unclear}ωνας]{.corr} [των]{.corr} [α[ι]{.unclear}ων[ων]{.unclear}]{.corr} [[και]{.greek-supplied}]{.corr} [βαλουσιν]{.greek-omitted} [[βαλουσι]{.corr}]{.greek-added} [τους]{.corr} [στεφανους]{.corr} [αυτων]{.corr} [ενωπιον]{.corr} [του]{.corr} [θρονου]{.corr} λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την δυναμιν οτι συ εκτισας [τα]{.greek-added} παντα και δια το θελημα σου [ησαν]{.greek-omitted} [εισι]{.greek-added} και εκτισθησαν[4:11]{.aside}

### Chapter 5

και ειδον επι την δεξιαν του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και εξωθεν κατεσφραγισμενον σφραγισιν επτα[5:1]{.aside}

και ειδον αγγελον ισχυρον κηρυσσοντα [εν]{.greek-omitted} φωνη μεγαλη [τις]{.greek-omitted} [τίς]{.greek-added} αξιος [εστιν]{.greek-omitted} ανοιξαι το βιβλιον και λυσαι τας σφραγιδας αυτου[5:2]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εν τω [ουρανω]{.greek-abbr} [ανω]{.greek-omitted} [ουτε]{.greek-omitted} [ουδε]{.greek-added} επι της γης [ουτε]{.greek-omitted} [ουδε]{.greek-added} υποκατω της γης ανοιξαι το βιβλιον [ουτε]{.greek-omitted} [ουδε]{.greek-added} βλεπειν αυτο[5:3]{.aside}

και εγω εκλαιον πολυ οτι ουδεις αξιος ευρεθη ανοιξαι [και]{.greek-added} [αναγνωναι]{.greek-added} το βιβλιον [ουτε]{.greek-omitted} [ουδε]{.greek-added} βλεπειν αυτο[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} [ανοιξαι]{.greek-added} [ο]{.greek-omitted} [ανοιγων]{.greek-omitted} το βιβλιον και τας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} σφραγιδας αυτου[5:5]{.aside}

και ειδον εν μεσω του θρονου και των τεσσαρων ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως [εσφαγμενον]{.greek-omitted} [εσφαγμεναι]{.greek-added} εχον κερατα [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και οφθαλμους [επτα]{.greek-omitted} [α]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [οι]{.greek-added} [εισιν]{.greek-omitted} [εισι]{.greek-added} τα [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} [τα]{.greek-added} [αποστελλομενα]{.greek-omitted} [απεσταλμενα]{.greek-added} εις πασαν την [γην]{.greek-omitted} [γηνν]{.greek-added}[5:6]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} το βιβλιον τα τεσσαρα ζωα και οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι επεσον ενωπιον του αρνιου εχοντες εκαστος [κιθαραν]{.greek-omitted} [κιθαρας]{.greek-added} και φιαλας χρυσας γεμουσας θυμιαματων αι εισιν [αι]{.greek-added} προσευχαι των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας [τω]{.greek-omitted} [θεω]{.greek-omitted} ημας εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και ειδον και ηκουσα ως φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον εστιν το αρνιον το εσφαγμενον λαβειν την δυναμιν και [τον]{.greek-omitted} πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο [εστιν]{.greek-added} εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} και επι της γης και υποκατω της γης και επι της θαλασσης [α]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και τα εν αυτοις παντας ηκουσα λεγοντας τω καθημενω επι του θρονου και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων [αμην]{.greek-omitted}[5:13]{.aside}

και τα τεσσαρα ζωα λεγοντα το αμην και οι πρεσβυτεροι επεσον και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και ειδον οτι [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το αρνιον μιαν εκ των [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνῆ]{.greek-added} βροντης ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:1]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων [και]{.greek-added} [ενικησε]{.greek-added} και ινα νικηση[6:2]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} [την]{.greek-added} [σφραγιδα]{.greek-added} την δευτεραν [σφραγιδα]{.greek-omitted} ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος πυρος και τω καθημενω επ αυτον εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} λαβειν την ειρηνην [εκ]{.greek-omitted} της γης ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη[6:4]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου και [ιδε]{.greek-omitted} [ειδον]{.greek-added} και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου[6:5]{.aside}

και ηκουσα φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες [κριθης]{.greek-omitted} [κριθων]{.greek-added} δηναριου και το ελαιον και τον οινον μη αδικησης[6:6]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την τεταρτην ηκουσα [φωνην]{.greek-added} του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

[και]{.greek-added} [ειδον]{.greek-added} και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω [ο]{.greek-omitted} θανατος και ο αδης [ηκολουθει]{.greek-omitted} [ακολουθει]{.greek-added} [αυτω]{.greek-omitted} [μετ]{.greek-added} [αυτου]{.greek-added} και εδοθη [αυτω]{.greek-omitted} [αυτοις]{.greek-added} εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την πεμπτην σφραγιδα ειδον υποκατω του θυσιαστηριου τας ψυχας [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} των εσφαγμενων δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν του αρνιου ην ειχον[6:9]{.aside}

και εκραξαν φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και εκδικεις το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και εδοθη αυτοις εκαστω στολη λευκη και ερρεθη αυτοις ινα αναπαυσωνται [ετι]{.greek-omitted} [επι]{.greek-added} χρονον [μικρον]{.greek-added} εως [ου]{.greek-added} [πληρωσωσιν]{.greek-omitted} [πληρωσωσι]{.greek-added} και οι συνδουλοι αυτων και οι αδελφοι αυτων [ως]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} μελλοντες [αποκτενεσθαι]{.greek-omitted} [αποκτεννεσθαι]{.greek-added} ως και αυτοι[6:11]{.aside}

και ειδον [και]{.greek-added} οτε ηνοιξεν την σφραγιδα την [εκτην]{.greek-omitted} [[στ]{.greek-abbr}]{.greek-added} και σεισμος μεγας εγενετο και ο ηλιος [εγενετο]{.greek-added} μελας [εγενετο]{.greek-omitted} ως σακκος τριχινος και η σεληνη [ολη]{.greek-omitted} εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του [ουρανου]{.greek-abbr} επεσον εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλει]{.greek-added} τους ολυνθους αυτης υπο [μεγαλου]{.greek-added} ανεμου [μεγαλου]{.greek-omitted} σειομενη[6:13]{.aside}

και ο [ουρανος]{.greek-abbr} απεχωρισθη ως βιβλιον ελισσομενον και παν ορος και νησος εκ των τοπων αυτων εκινηθησαν[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι [χιλιαρχοι]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} πλουσιοι και οι [ισχυροι]{.greek-omitted} [χιλιαρχοι]{.greek-added} και πας δουλος και [πας]{.greek-added} ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας [πετρας]{.greek-omitted} [σχισμας]{.greek-added} των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις πεσετε εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι του θρονου και απο της οργης του αρνιου[6:16]{.aside}

οτι ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

και μετα τουτο ειδον τεσσαρας αγγελους εστωτας επι τας τεσσαρας γωνιας της γης κρατουντας τους τεσσαρας ανεμους της γης ινα μη πνεη ανεμος επι της γης μητε επι της θαλασσης μητε επι [τι]{.greek-omitted} [παν]{.greek-added} δενδρον[7:1]{.aside}

και ειδον αλλον αγγελον αναβαινοντα απο ανατολης ηλιου εχοντα σφραγιδα [θεου]{.greek-abbr} ζωντος και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη τοις τεσσαρσιν αγγελοις οις εδοθη αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην μητε την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των μετωπων αυτων[7:3]{.aside}

και ηκουσα τον αριθμον των εσφραγισμενων εκατον και τεσσαρακοντα τεσσαρες χιλιαδες [εσφραγισμενων]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης [ρουβιμ]{.greek-omitted} [ρουβιν]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμενοι]{.greek-added} εκ φυλης γαδ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:5]{.aside}

[εσφραγισμενοι]{.greek-added} εκ φυλης ασηρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμενοι]{.greek-added} εκ φυλης νεφθαλειμ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης μανασση [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:6]{.aside}

εκ φυλης συμεων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης λευι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ισαχαρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης βενιαμιν [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added}[7:8]{.aside}

μετα ταυτα ειδον και ιδου οχλος πολυς ον αριθμησαι ουδεις εδυνατο εκ παντος εθνους και φυλων και λαων και γλωσσων [εστωτας]{.greek-omitted} [εστωτες]{.greek-added} ενωπιον του θρονου και ενωπιον του αρνιου [περιβεβλημενους]{.greek-omitted} [περιβεβλημενοι]{.greek-added} στολας λευκας και [φοινικας]{.greek-omitted} [φοινικες]{.greek-added} εν ταις χερσιν αυ[τ]{.unclear}ων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} ημων τω καθημενω επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι ειστηκεισαν κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και επεσον ενωπιον του θρονου επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και [η]{.greek-omitted} ευχαριστια και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες [εισιν]{.greek-omitted} [εισι]{.greek-added} και ποθεν ηλθον[7:13]{.aside}

και ειπον [αυτω]{.greek-omitted} [αυτωι]{.greek-added} κυριε μου συ οιδας και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ουτοι εισιν οι ερχομενοι εκ της θλιψεως της μεγαλης και [επλυναν]{.greek-omitted} [επλατυναν]{.greek-added} τας στολας αυτων και ελευκαναν [αυτας]{.greek-added} εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι [τω]{.greek-omitted} [θρονω]{.greek-omitted} [του]{.greek-added} [θρονου]{.greek-added} σκηνωσει επ αυτους[7:15]{.aside}

[και]{.greek-added} ου πεινασουσιν ετι ουδε διψησουσιν [ετι]{.greek-omitted} ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμανει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγησει]{.greek-added} αυτους επι ζωης πηγας υδατων και εξαλειψει ο [θεος]{.greek-abbr} παν δακρυον [εκ]{.greek-omitted} [απο]{.greek-added} των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} την σφραγιδα την [εβδομην]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} εγενετο σιγη εν τω [ουρανω]{.greek-abbr} ως [ημιωριον]{.greek-omitted} [ἡμιώριον]{.greek-added}[8:1]{.aside}

και ειδον τους [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αγγελους οι ενωπιον του [θεου]{.greek-abbr} [εστηκασιν]{.greek-omitted} [εστηκασι]{.greek-added} και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και εσταθη επι του θυσιαστηριου εχων λιβανωτον χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δωσει]{.greek-added} ταις προσ[ευχ]{.unclear}αις των αγιων παντων επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και εγεμισεν αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο [φωναι]{.greek-added} [και]{.greek-added} βρονται [και]{.greek-omitted} [φωναι]{.greek-omitted} και αστραπαι και σεισμος[8:5]{.aside}

και οι επτα αγγελοι οι εχοντες τας επτα σαλπιγγας ητοιμασαν εαυτους ινα σαλπισωσιν[8:6]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και εβληθη εις την γην και το τριτον της γης κατεκαη και το τριτον των δενδρων κατεκαη και πας χορτος χλωρος κατεκαη[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ως ορος μεγα καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} [των]{.greek-added} [κτισματων]{.greek-added} το τριτον των [κτισματων]{.greek-omitted} εν τη θαλασση τα εχοντα ψυχας και το τριτον των πλοιων [διεφθαρη]{.greek-omitted} [διεφθαρησαν]{.greek-added}[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επεσεν εκ του [ουρανου]{.greek-abbr} αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων εις αψινθον και πολλοι των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και [η]{.greek-added} [ημερα]{.greek-added} [μη]{.greek-added} [φαινη]{.greek-added} το τριτον αυτης [μη]{.greek-omitted} [φανη]{.greek-omitted} [η]{.greek-omitted} [ημερα]{.greek-omitted} και η νυξ ομοιως[8:12]{.aside}

και ειδον και ηκουσα ενος αετου πετομενου εν [τω]{.greek-added} μεσουρανηματι λεγοντος φωνη μεγαλη [τρις]{.greek-added} ουαι ουαι ουαι τοις κατοικουσιν επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ειδον αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος ως καπνος καμινου [καιομενης]{.greek-omitted} [καιομηνης]{.greek-added} και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και εδοθη αυταις εξουσια ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησωσι]{.greek-added} τον χορτον της γης ουδε παν χλωρον ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την σφραγιδα του [θεου]{.greek-abbr} επι των μετωπων [αυτων]{.greek-omitted}[9:4]{.aside}

και εδοθη αυταις ινα μη αποκτεινωσιν αυτους αλλ ινα [βασανισθωσιν]{.greek-omitted} [βασανισθωσι]{.greek-added} μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν παιση [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και ου μη [ευρησουσιν]{.greek-omitted} [ευρωσιν]{.greek-added} αυτον και επιθυμησουσιν αποθανειν και [φευξεται]{.greek-omitted} [φευγει]{.greek-added} [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα ομοιωματα των ακριδων ομοια ιπποις [ητοιμασμενοις]{.greek-omitted} [ητοιμασμενος]{.greek-added} εις πολεμον και επι τας κεφαλας αυτων ως στεφανοι χρυσοι και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και ειχον τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και ειχον θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα [και]{.greek-omitted} εν ταις ουραις αυτων [και]{.greek-added} εξουσιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} του αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[εχουσαι]{.greek-omitted} [εχουσι]{.greek-added} [βασιλεα]{.greek-omitted} [δε]{.greek-added} επ αυτων [βασιλεα]{.greek-added} [τον]{.greek-added} αγγελον της αβυσσου ονομα αυτω εβραιστι αββαδων εν δε τη ελληνικη ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} ετι δυο ουαι [μετα]{.greek-omitted} [ταυτα]{.greek-omitted}[9:12]{.aside}

και ο εκτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και ηκουσα φωνην μιαν εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

λεγουσαν [τω]{.greek-omitted} [τωι]{.greek-added} εκτω [αγγελω]{.greek-omitted} [αγγελωι]{.greek-added} ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα [αποκτεινωσιν]{.greek-omitted} [αποκτεινωσι]{.greek-added} το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [ιππου]{.greek-omitted} [ιππικου]{.greek-added} μυριαδες μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως ειδον τους ιππους εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [εκ]{.greek-added} του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσι]{.greek-added} κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19]{.aside}

και οι λοιποι των [ανθρωπων]{.greek-abbr} [οι]{.greek-omitted} ουκ απεκτανθησαν εν ταις πληγαις ταυταις [ου]{.greek-omitted} [ουτε]{.greek-added} μετενοησαν εκ των εργων των χειρων αυτων ινα μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τα δαιμονια και τα ειδωλα τα χρυσα και [τα]{.greek-omitted} αργυρα και [τα]{.greek-omitted} [λιθινα]{.greek-added} [και]{.greek-added} χαλκα και [τα]{.greek-omitted} [λιθινα]{.greek-omitted} [και]{.greek-omitted} [τα]{.greek-omitted} ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των φαρμακειων αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και ειδον [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και η ιρις επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και [εχων]{.greek-omitted} [ειχεν]{.greek-added} εν τη χειρι αυτου [βιβλιον]{.greek-omitted} [βιβλαδαριον]{.greek-added} ανεωγμενον και [εθηκεν]{.greek-omitted} [εθηκε]{.greek-added} τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευωνυμον επι της γης[10:2]{.aside}

και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη ωσπερ λεων μυκαται και οτε εκραξεν ελαλησαν αι [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} βρονται εμελλον γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} βρονται και [μετα]{.greek-added} [ταυτα]{.greek-added} μη αυτα γραψης[10:4]{.aside}

και ο αγγελος ον ειδον [εστωτα]{.greek-omitted} επι της θαλασσης και επι της γης [εστωτα]{.greek-added} [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και ωμοσεν [εν]{.greek-added} τω ζωντι εις τους αιωνας των αιωνων ος [εκτισεν]{.greek-omitted} [εκτισε]{.greek-added} τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν [και]{.greek-omitted} [ετελεσθη]{.greek-omitted} [τελεσθη]{.greek-added} το μυστηριον του [θεου]{.greek-abbr} [ως]{.greek-omitted} [ο]{.greek-added} [ευηγγελισεν]{.greek-omitted} [ευηγγελισε]{.greek-added} τους δουλους αυτου τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του ουρανου παλιν [λαλουσα]{.greek-omitted} [λαλουσαν]{.greek-added} μετ εμου και [λεγουσα]{.greek-omitted} [λεγουσαν]{.greek-added} υπαγε λαβε το [βιβλιδαριον]{.greek-omitted} [βιβλαδαριον]{.greek-added} το ανεωγμενον εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και απηλθον προς τον αγγελον λεγων [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [δουναι]{.greek-omitted} [δος]{.greek-added} μοι το [βιβλιδαριον]{.greek-omitted} [βιβλαδαριον]{.greek-added} και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την κοιλιαν αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βιβλαδαριον]{.greek-added} εκ της χειρος του αγγελου και [κατεφαγον]{.greek-omitted} [κατέφαγον]{.greek-added} αυτο και ην εν τω στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο επικρανθη η κοιλια μου[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγει]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω [και]{.greek-added} [ειστηκει]{.greek-added} [ο]{.greek-added} [αγγελος]{.greek-added} λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην μετρησης οτι εδοθη τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και την πολιν την αγιαν [πατησουσιν]{.greek-omitted} [πατησουσι]{.greek-added} μηνας [τεσσαρακοντα]{.greek-omitted} [τεσσερακονταδυο]{.greek-added} [και]{.greek-omitted} [δυο]{.greek-omitted}[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι αι ενωπιον του [κυριου]{.greek-abbr} της γης εστωσ[αι]{.unclear}[11:4]{.aside}

και ει τις αυτους θελει αδικησαι πυρ εκπορευεται εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις θελει αυτους [αδικησαι]{.greek-omitted} [αποκτειναι]{.greek-added} ουτως δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι εχουσιν [εξουσιαν]{.greek-added} [κλεισαι]{.greek-added} τον [ουρανον]{.greek-abbr} [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην [εν]{.greek-added} [πασηι]{.greek-added} [πληγη]{.greek-added} οσακις εαν [θελησωσιν]{.greek-omitted} [θελησωσι]{.greek-added} [εν]{.greek-omitted} [παση]{.greek-omitted} [πληγη]{.greek-omitted}[11:6]{.aside}

και οταν [τελεσωσιν]{.greek-omitted} [τελεσωσι]{.greek-added} την μαρτυριαν αυτων το θηριον το αναβαινον εκ της αβυσσου ποιησει [πολεμον]{.greek-added} μετ αυτων [πολεμον]{.greek-omitted} και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματικως]{.greek-abbr} σοδομα και αιγυπτος οπου [και]{.greek-omitted} ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων [το]{.greek-omitted} [τα]{.greek-added} [πτωμα]{.greek-omitted} [πτωματα]{.greek-added} αυτων ημερας τρεις ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφιουσι]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και ευφρανθησονται και δωρα [δωσουσιν]{.greek-omitted} [πεμψουσιν]{.greek-added} αλληλοις οτι ουτοι οι δυο [οι]{.greek-added} προφηται εβασανισαν τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης [εκ]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} εισηλθεν εις [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και εστησαν επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} [επεπεσεν]{.greek-added} επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα [φωνην]{.greek-omitted} [φωνης]{.greek-added} [μεγαλην]{.greek-omitted} [μεγαλης]{.greek-added} εκ του [ουρανου]{.greek-abbr} [λεγουσαν]{.greek-omitted} [λεγουσης]{.greek-added} αυτοις [αναβητε]{.greek-omitted} [ἀνάβητε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη ημερα εγενετο σεισμος μεγας και το δεκατον της πολεως [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι εμφοβοι εγενοντο και εδωκαν δοξαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν η ουαι η τριτη [ωπουιδπωπα]{.greek-added} ιδου ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπισε]{.greek-added} και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} λεγουσαι [εγενετο]{.greek-omitted} [εγενοντο]{.greek-added} [η]{.greek-omitted} [αι]{.greek-added} βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι [[κδ]{.greek-abbr}]{.greek-added} [εικοσι]{.greek-omitted} [τεσσαρες]{.greek-omitted} πρεσβυτεροι οι ενωπιον [του]{.greek-omitted} [θρονου]{.greek-omitted} του [θεου]{.greek-abbr} καθημενοι επι τους θρονους αυτων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην [και]{.greek-added} [ο]{.greek-added} [ερχομενος]{.greek-added} οτι ειληφας την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη ωργισθησαν και ηλθεν η οργη σου και ο καιρος των νεκρων κριθηναι και δουναι τον μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις [και]{.greek-omitted} τοις φοβουμενοις το ονομα σου τοις μικροις και τοις μεγαλοις και διαφθειραι τους διαφθειροντας την γην[11:18]{.aside}

και ηνοιγη ο ναος του [θεου]{.greek-abbr} [ο]{.greek-added} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης του [κυριου]{.greek-abbr} εν τω ναω αυτου και εγενοντο αστραπαι και [και]{.greek-added} φωναι και βρονται και χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν [τω]{.greek-omitted} [τωι]{.greek-added} ουρανω γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα [εκραζεν]{.greek-omitted} [εκραζη]{.greek-added} ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-abbr} και ιδου δρακων [μεγας]{.greek-added} πυρος [μεγας]{.greek-omitted} εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου [επτα]{.greek-omitted} διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του ουρανου και εβαλεν αυτους εις την γην και ο δρακων [εστηκεν]{.greek-omitted} [ἕστηκεν]{.greek-added} ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν τεκη το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν υιον αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν [ραβδω]{.greek-omitted} [ραβδωι]{.greek-added} σιδηρα και [ηρπασθη]{.greek-omitted} [ηρπαγη]{.greek-added} το τεκνον αυτης προς τον [θεον]{.greek-abbr} και [προς]{.greek-omitted} τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον [υπο]{.greek-omitted} [απο]{.greek-added} του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας [[ασξ]{.greek-abbr}]{.greek-added} [χιλιας]{.greek-omitted} [διακοσιας]{.greek-omitted} [εξηκοντα]{.greek-omitted}[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ο μιχαηλ και οι αγγελοι αυτου [του]{.greek-added} πολεμησαι μετα του δρακοντος και ο δρακων [επολεμησεν]{.greek-omitted} [επολεμησε]{.greek-added} και οι αγγελοι αυτου[12:7]{.aside}

και ουκ ισχυσεν ουδε τοπος ευρεθη [αυτω]{.greek-omitted} [αυτων]{.greek-added} ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και η βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι [εβληθη]{.greek-omitted} [κατεβληθη]{.greek-added} ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν την ψυχην αυτων αχρι θανατου[12:11]{.aside}

δια τουτο ευφραινεσθε [ουρανοι]{.greek-abbr} και οι εν αυτοις σκηνουντες ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε ειδεν ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις [ετεκεν]{.greek-omitted} [ετεκε]{.greek-added} τον αρρενα[12:13]{.aside}

και εδοθησαν τη γυναικι δυο πτερυγες του αετου του μεγαλου ινα πετηται εις την ερημον εις τον τοπον αυτης οπως [τρεφηται]{.greek-omitted} [τρεφεται]{.greek-added} εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον ποιηση[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και [κατεπιεν]{.greek-omitted} [κατεπιε]{.greek-added} τον ποταμον ον εβαλεν ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων επι τη γυναικι και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθην]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

[και]{.greek-omitted} [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} και ειδον εκ της θαλασσης θηριον αναβαινον εχον [δεκα]{.greek-added} κερατα [δεκα]{.greek-omitted} και κεφαλας επτα και επι των κερατων αυτου δεκα διαδηματα και επι τας κεφαλας αυτου ονοματα βλασφημιας[13:1]{.aside}

και το θηριον ο ειδον ην ομοιον παρδαλει και οι ποδες αυτου ως [αρκου]{.greek-omitted} [αρκτου]{.greek-added} και το στομα αυτου ως στομα λεοντος και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου ωσει εσφαγμενην εις θανατον και η πληγη του θανατου [αυτου]{.greek-omitted} εθεραπευθη και [εθαυμασεν]{.greek-omitted} [εθαυμασθη]{.greek-added} ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [οτι]{.greek-added} [εδωκε]{.greek-added} την εξουσιαν τω [θηριω]{.greek-omitted} [θηριωι]{.greek-added} [και]{.greek-omitted} [προσεκυνησαν]{.greek-omitted} [τω]{.greek-omitted} [θηριω]{.greek-omitted} λεγοντες τις ομοιος τω θηριω και τις δυνατος πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη αυτω στομα λαλουν μεγαλα και [βλασφημιαν]{.greek-omitted} [βλασφημιας]{.greek-added} και εδοθη αυτω εξουσια πολεμον ποιησαι μηνας [τεσσαρακοντα]{.greek-omitted} [τεσσαρακονταδυο]{.greek-added} [δυο]{.greek-omitted}[13:5]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνοιξε]{.greek-added} το στομα αυτου εις [βλασφημιαν]{.greek-omitted} [βλασφημιας]{.greek-added} προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου [και]{.greek-added} τους εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} σκηνουντας[13:6]{.aside}

και εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} [ποιησαι]{.greek-omitted} [πολεμον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted} [και]{.greek-omitted} [νικησαι]{.greek-omitted} [αυτους]{.greek-omitted} [και]{.greek-omitted} [εδοθη]{.greek-omitted} [αυτω]{.greek-omitted} εξουσια επι πασαν φυλην και [λαον]{.greek-omitted} [και]{.greek-omitted} γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες επι της γης ων ου γεγραπται το ονομα εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν μαχαιρα [αποκτενει]{.greek-omitted} [ἀποκτενεῖ]{.greek-added} δει αυτον εν μαχαιρα [αποκτανθηναι]{.greek-omitted} [ἀποκτανθῆναι]{.greek-added} ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και ειδον αλλο θηριον [αναβαινον]{.greek-omitted} [ἀναβαῖνον]{.greek-added} εκ της γης και [ειχεν]{.greek-omitted} [ειχε]{.greek-added} κερατα δυο ομοια αρνιω και ελαλει ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και [εποιει]{.greek-omitted} [ποιει]{.greek-added} την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει σημεια μεγαλα και πυρ ινα [ποιη]{.greek-added} εκ του [ουρανου]{.greek-abbr} καταβαινη επι την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω [ποιησαι]{.greek-omitted} [ποιη]{.greek-added} ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ὃ]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} την πληγην [της]{.greek-added} [μαχαιρης]{.greek-added} και [εζησεν]{.greek-omitted} [εζησε]{.greek-added} [απο]{.greek-omitted} [της]{.greek-omitted} [μαχαιρας]{.greek-omitted}[13:14]{.aside}

και εδοθη αυτω πνευμα δουναι τη εικονι του θηριου ινα [και]{.greek-omitted} λαληση η εικων του θηριου και ποιηση οσοι εαν μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησωσι]{.greek-added} τη εικονι του θηριου [αποκτανθωσιν]{.greek-omitted} [αποκτανθωσι]{.greek-added}[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} αυτοις χαραγματα επι [της]{.greek-omitted} χειρος αυτων της δεξιας η επι [το]{.greek-omitted} [των]{.greek-added} [μετωπον]{.greek-omitted} [μετωπων]{.greek-added} αυτων[13:16]{.aside}

[και]{.greek-omitted} ινα μη τις [δυναται]{.greek-omitted} [δυνηται]{.greek-added} αγορασαι η πωλησαι ει μη ο εχων το χαραγμα [το]{.greek-omitted} [του]{.greek-added} [ονομα]{.greek-omitted} [ονοματος]{.greek-added} του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια εστιν ο εχων νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο αριθμος αυτου εστιν [[χξστ]{.greek-abbr}]{.greek-added} [τειταν]{.greek-added} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

και ειδον και ιδου [το]{.greek-omitted} αρνιον εστηκος επι το ορος σιων και μετ αυτου [[ρμδ]{.greek-abbr}]{.greek-added} [αριθμος]{.greek-omitted} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες εχουσαι το ονομα αυτου και το ονομα του [πατρος]{.greek-abbr} αυτου γεγραμμενον επι των μετωπων αυτων[14:1]{.aside}

και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} ως φωνην υδατων πολλων και ως φωνην βροντης μεγαλη[ς]{.unclear} και η φωνη ην ηκουσα ως [φωνη]{.greek-added} κιθαρωδων κιθαριζοντων εν ταις κιθαραις αυτων[14:2]{.aside}

και αδουσιν ωδην καινην ενωπιον του θρονου και ενωπιον των τεσσαρων ζωων και των πρεσβυτερων και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} μαθειν την ωδην ει μη αι [[ρμδ]{.greek-abbr}]{.greek-added} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} χιλιαδες οι ηγορασμενοι απο της γης[14:3]{.aside}

ουτοι εισιν οι μετα γυναικων ουκ εμολυνθησαν παρθενοι γαρ εισιν ουτοι [εισιν]{.greek-omitted} οι ακολουθουντες τω αρνιω οπου αν υπαγη ουτοι [υπο]{.greek-omitted} [ιησου]{.greek-omitted} ηγορασθησαν απο των [ανθρωπων]{.greek-abbr} απαρχη [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} και τω αρνιω[14:4]{.aside}

και [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} εν τω στοματι αυτων [ουχ]{.greek-added} [ευρεθη]{.greek-added} ψευδος αμωμοι γαρ εισιν[14:5]{.aside}

και ειδον [αλλον]{.greek-added} αγγελον πετομενον εν μεσουρανηματι εχοντα ευαγγελιον αιωνιον ευαγγελισαι τους καθημενους επι της γης και επι παν εθνος και φυλην και γλωσσαν και λαον[14:6]{.aside}

λεγων εν φωνη μεγαλη φοβηθητε τον [κυριον]{.greek-omitted} [[θεον]{.greek-abbr}]{.greek-added} και δοτε αυτω δοξαν οτι ηλθεν η ωρα της κρισεως αυτου και προσκυνησατε [αυτον]{.greek-omitted} [τον]{.greek-omitted} [ποιησαντα]{.greek-omitted} [τω]{.greek-added} [ποιη]{.greek-added} [σαντι]{.greek-added} τον [ουρανον]{.greek-abbr} και την γην και την θαλασσαν και πηγας υδατων[14:7]{.aside}

και αλλος [αγγελος]{.greek-added} δευτερος [αγγελος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} λεγων επεσεν [επεσε]{.greek-added} βαβυλων η μεγαλη εκ του οινου του θυμου της πορνειας αυτης [πεποτικεν]{.greek-omitted} [πεποτικε]{.greek-added} παντα τα εθνη[14:8]{.aside}

και αλλος αγγελος τριτος ηκολουθησεν αυτοις λεγων εν [φωνη]{.greek-omitted} [φωνηι]{.greek-added} μεγαλη ει τις προσκυνει το θηριον και την εικονα αυτου και λαμβανει χαραγμα επι του μετωπου αυτου η επι [την]{.greek-omitted} [της]{.greek-added} [χειρα]{.greek-omitted} [χειρας]{.greek-added} αυτου[14:9]{.aside}

και αυτος πιεται εκ του οινου του θυμου του [θεου]{.greek-abbr} του κεκερασμενου ακρατου εν τω ποτηριω της οργης αυτου και βασανισθησεται εν πυρι [και]{.greek-omitted} [θειω]{.greek-omitted} [θειωι]{.greek-added} ενωπιον των αγιων αγγελων και ενωπιον του αρνιου[14:10]{.aside}

και ο καπνος του βασανισμου αυτων εις αιωνας αιωνων αναβαινει και ουκ εχουσιν αναπαυσιν ημερας και νυκτος οι προσκυνουντες το θηριον και την εικονα αυτου και ει τις λαμβανει το χαραγμα του ονοματος αυτου[14:11]{.aside}

ωδε η υπομονη των αγιων εστιν [ωδε]{.greek-added} οι τηρουντες τας εντολας του [θεου]{.greek-abbr} και την πιστιν [του]{.greek-added} [ιησου]{.greek-abbr}[14:12]{.aside}

και ηκουσα φωνης εκ του [ουρανου]{.greek-abbr} λεγουσης [μοι]{.greek-added} γραψον μακαριοι οι νεκροι οι εν [κυριω]{.greek-abbr} αποθνησκοντες [απ]{.greek-omitted} [αρτι]{.greek-omitted} [ἀπάρτι]{.greek-added} [ναι]{.greek-added} λεγει [ναι]{.greek-omitted} το [πνευμα]{.greek-abbr} [το]{.greek-added} [αγιον]{.greek-added} ινα [αναπαυσωνται]{.greek-omitted} [αναπαησωνται]{.greek-added} εκ των κοπων αυτων τα δε εργα αυτων ακολουθει μετ αυτων[14:13]{.aside}

και ειδον και ιδου νεφελη λευκη και επι την νεφελην [καθημενον]{.greek-omitted} [καθημενος]{.greek-added} [ομοιον]{.greek-omitted} [ομοιος]{.greek-added} υιω [ανθρωπου]{.greek-abbr} εχων επι της κεφαλης αυτου στεφανον χρυσουν και εν τη χειρι αυτου δρεπανον οξυ[14:14]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου κραζων εν φωνη μεγαλη τω καθημενω επι της νεφελης πεμψον το δρεπανον σου και θερισον οτι ηλθεν η ωρα θερισαι οτι εξηρανθη ο θερισμος της γης[14:15]{.aside}

και εβαλεν ο καθημενος επι την νεφελην το δρεπανον αυτου επι την γην και εθερισθη η γη[14:16]{.aside}

και αλλος αγγελος εξηλθεν εκ του ναου του εν τω [ουρανω]{.greek-abbr} εχων και αυτος δρεπανον οξυ[14:17]{.aside}

και αλλος αγγελος εξηλθεν εκ του θυσιαστηριου εχων εξουσιαν επι του πυρος και εφωνησεν [εν]{.greek-added} κραυγη μεγαλη τω εχοντι το δρεπανον το οξυ λεγων πεμψον σου το δρεπανον το οξυ και τρυγησον τους βοτρυας της αμπελου της γης οτι ηκμασαν αι σταφυλαι αυτης[14:18]{.aside}

και εβαλεν ο αγγελος το δρεπανον αυτου εις την γην και [ετρυγησεν]{.greek-omitted} [ετρυγησε]{.greek-added} την αμπελον της γης και εβαλεν εις την ληνον του [οινου]{.greek-added} [του]{.greek-added} θυμου του [θεου]{.greek-abbr} τον μεγαν[14:19]{.aside}

και επατηθη η ληνος εξωθεν της πολεως και εξηλθεν αιμα εκ της ληνου αχρι των χαλινων των ιππων απο σταδιων χιλιων εξακοσιων[14:20]{.aside}

### Chapter 15

και ειδον αλλο σημειον εν τω [ουρανω]{.greek-abbr} μεγα και θαυμαστον αγγελους [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} εχοντας πληγας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} τας εσχατας οτι εν αυταις ετελεσθη ο θυμος του [θεου]{.greek-abbr}[15:1]{.aside}

και ειδον ως θαλασσαν υαλινην μεμιγμενην πυρι και τους νικωντας εκ [της]{.greek-added} [εικονος]{.greek-added} του θηριου και εκ της εικονος αυτου και εκ του αριθμου του ονοματος αυτου εστωτας επι την θαλασσαν την υαλινην εχοντας κιθαρας [του]{.greek-omitted} [θεου]{.greek-abbr}[15:2]{.aside}

και [αδουσιν]{.greek-omitted} [αδουσι]{.greek-added} την ωδην [μωυσεως]{.greek-omitted} [μωσεως]{.greek-added} του δουλου του [θεου]{.greek-abbr} και την ωδην του αρνιου λεγοντες μεγαλα και θαυμαστα τα εργα σου [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ δικαιαι και αληθιναι αι οδοι σου ο βασιλευς των εθνων[15:3]{.aside}

τις ου μη [φοβηθη]{.greek-omitted} [φοβηθησε]{.greek-added} [σε]{.greek-omitted} [κυριε]{.greek-abbr} και δοξαση το ονομα σου οτι μονος [αγιος]{.greek-omitted} [οσιος]{.greek-added} [ει]{.greek-added} οτι παντα τα εθνη [ηξουσιν]{.greek-omitted} [ηξουσι]{.greek-added} και προσκυνησουσιν ενωπιον σου οτι τα δικαιωματα σου εφανερωθησαν[15:4]{.aside}

και μετα ταυτα ειδον και ηνοιγη ο [ν]{.unclear}αος της σκηνης του μαρτυριου εν τω [ουρανω]{.greek-abbr}[15:5]{.aside}

και εξηλθον οι επτα αγγελοι οι εχοντες τας επτα πληγας εκ του ναου οι ησαν ενδεδυμενοι λινον καθαρον λαμπρον και περιεζωσμενοι περι τα στηθη ζωνας χρυσας[15:6]{.aside}

και εν εκ των τεσσαρων ζωων [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} τοις επτα αγγελοις επτα φιαλας χρυσας [σεμουσας]{.greek-added} [γεμουσας]{.corr} του θυμου του [θεου]{.greek-abbr} του ζωντος εις τους αιωνας των αιωνων[15:7]{.aside}

και εγεμισθη ο ναος καπνου εκ της δοξης του [θεου]{.greek-abbr} και εκ της δυναμεως αυτου και ουδεις εδυνατο εισελθειν εις τον ναον αχρι τελεσθωσιν αι επτα πληγαι των επτα αγγελων[15:8]{.aside}

### Chapter 16

και ηκουσα φωνης μεγαλης εκ του ναου λεγουσης τοις επτα αγγελοις υπαγετε και εκχεατε τας [επτα]{.greek-omitted} φιαλας του θυμου [του]{.greek-omitted} [θεου]{.greek-omitted} εις την γην[16:1]{.aside}

και απηλθεν ο πρωτος και [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την γην και εγενετο ελκος κακον και πονηρον [επι]{.greek-omitted} [εις]{.greek-added} τους [ανθρωπους]{.greek-abbr} τους εχοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου[16:2]{.aside}

και ο δευτερος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις την θαλασσαν και εγενετο [ως]{.greek-added} αιμα [ως]{.greek-omitted} νεκρου και πασα ψυχη ζωσα απεθανεν εν τη θαλασση[16:3]{.aside}

και ο τριτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου εις τους ποταμους και [εις]{.greek-omitted} τας πηγας των υδατων και εγενετο αιμα[16:4]{.aside}

και ηκουσα του αγγελου των υδατων λεγοντος δικαιος ει ο ων και ο ην ο οσιος οτι ταυτα εκρινας[16:5]{.aside}

οτι αιμα [αγιων]{.greek-omitted} [ἁγίων]{.greek-added} και προφητων εξεχεαν και αιμα αυτοις εδωκας πιειν [οτι]{.greek-added} αξιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[16:6]{.aside}

και ηκουσα του θυσιαστηριου λεγοντος ναι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ αληθιναι και δικαιαι αι κρισεις σου[16:7]{.aside}

και ο τεταρτος αγγελος [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ηλιον και [εγενετο]{.greek-added} [ο]{.greek-added} [ηλιος]{.greek-added} [μελας]{.greek-added} [ως]{.greek-added} [ακκος]{.greek-added} [τριχινος]{.greek-added} [και]{.greek-added} εδοθη [αυτω]{.greek-omitted} [αυτωι]{.greek-added} καυματισαι [τους]{.greek-added} [[ανθρωπους]{.greek-abbr}]{.greek-added} εν πυρι [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted}[16:8]{.aside}

και εκαυματισθησαν οι [ανθρωποι]{.greek-abbr} καυμα μεγα και εβλασφημησαν [οι]{.greek-omitted} [ανθρωποι]{.greek-omitted} το ονομα του [θεου]{.greek-abbr} του εχοντος [την]{.greek-added} εξουσιαν επι τας πληγας ταυτας και ου μετενοησαν δουναι αυτω δοξαν[16:9]{.aside}

και ο πεμπτος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον θρονον του θηριου και εγενετο η βασιλεια αυτου εσκοτωμενη και εμασωντο τας γλωσσας αυτων εκ του πονου[16:10]{.aside}

και εβλασφημησαν τον [θεον]{.greek-abbr} του [ουρανου]{.greek-abbr} εκ των πονων αυτων και [εκ]{.greek-omitted} [των]{.greek-omitted} ελκων αυτων και ου μετενοησαν εκ των εργων αυτων[16:11]{.aside}

και ο [εκτος]{.greek-omitted} [[στ]{.greek-abbr}]{.greek-added} [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου επι τον ποταμον τον μεγαν [τον]{.greek-added} ευφρατην και εξηρανθη το υδωρ αυτου ινα ετοιμασθη η οδος των βασιλεων των απο [ανατολης]{.greek-omitted} [ανατολων]{.greek-added} ηλιου[16:12]{.aside}

και ειδον εκ του στοματος του δρακοντος και εκ του στοματος του θηριου και εκ του στοματος του ψευδοπροφητου πνευματα [ακαθαρτα]{.greek-omitted} τρια [ως]{.greek-omitted} [εκπορευομενα]{.greek-added} [εοικοτα]{.greek-added} [βατραχοι]{.greek-omitted} [βατραχοις]{.greek-added}[16:13]{.aside}

[εισιν]{.greek-omitted} [εισι]{.greek-added} γαρ πνευματα [δαιμονιων]{.greek-omitted} [δαιμονων]{.greek-added} ποιουντα σημεια α εκπορευεται επι τους βασιλεις της οικουμενης ολης συναγαγειν αυτους εις τον πολεμον της ημερας εκεινης της μεγαλης του [θεου]{.greek-abbr} του παντοκρατορος[16:14]{.aside}

ιδου ερχομαι ως κλεπτης μακαριος ο γρηγορων και τηρων τα ιματια αυτου ινα μη γυμνος περιπατη και [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} την ασχημοσυνην αυτου[16:15]{.aside}

και συνηγαγεν αυτους εις [τον]{.greek-omitted} τοπον τον καλουμενον εβραιστι [αρμαγεδων]{.greek-omitted} [ἁρμαγεδών]{.greek-added}[16:16]{.aside}

και ο εβδομος [αγγελος]{.greek-added} [εξεχεεν]{.greek-omitted} [εξεχεε]{.greek-added} την φιαλην αυτου [επι]{.greek-omitted} [εις]{.greek-added} τον αερα και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} φωνη [εκ]{.greek-added} [μεγαλη]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [ναου]{.greek-omitted} του [ουρανου]{.greek-abbr} απο του θρονου λεγουσα γεγονεν[16:17]{.aside}

και εγενοντο αστραπαι και [φωναι]{.greek-added} [και]{.greek-added} βρονται και [φωναι]{.greek-omitted} [και]{.greek-omitted} σεισμος [εγενετο]{.greek-added} μεγας οιος ουκ εγενετο αφ ου [οι]{.greek-omitted} [ανθρωποι]{.greek-abbr} εγενοντο επι της γης τηλικουτος σεισμος [ουτως]{.greek-omitted} [ουτω]{.greek-added} μεγας[16:18]{.aside}

και εγενετο η πολις η μεγαλη εις τρια μερη και αι πολεις των εθνων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και βαβυλων η μεγαλη [εμνησθη]{.greek-omitted} [εμισηθη]{.greek-added} ενωπιον του [θεου]{.greek-abbr} δουναι αυτη το ποτηριον του οινου του θυμου της οργης αυτου[16:19]{.aside}

και πασα νησος [εφυγεν]{.greek-omitted} [εφυγε]{.greek-added} και ορη ουχ ευρεθησαν[16:20]{.aside}

και χαλαζα μεγαλη ως ταλαντιαια καταβαινει εκ του [ουρανου]{.greek-abbr} επι τους [ανθρωπους]{.greek-abbr} και εβλασφημησαν οι [ανθρωποι]{.greek-abbr} τον [θεον]{.greek-abbr} εκ της πληγης της χαλαζης οτι μεγαλη εστιν η πληγη [αυτης]{.greek-omitted} [αυτη]{.greek-added} σφοδρα[16:21]{.aside}

### Chapter 17

και ηλθεν εις εκ των [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} αγγελων των εχοντων τας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} φιαλας και [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ εμου λεγων δευρο δειξω σοι το κριμα της πορνης της μεγαλης της καθημενης επι των υδατων των πολλων[17:1]{.aside}

μεθ ης επορνευσαν οι βασιλεις της γης και εμεθυσθησαν οι κατοικουντες την γην εκ του οινου της πορνειας αυτης[17:2]{.aside}

και [απηνεγκεν]{.greek-omitted} [απηνεγκε]{.greek-added} με εις ερημον εν [πνευματι]{.greek-abbr} και ειδον γυναικα καθημενην επι θηριον κοκκινον γεμον ονοματα βλασφημιας εχον κεφαλας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} και κερατα δεκα[17:3]{.aside}

και η γυνη [ην]{.greek-omitted} [ἦν]{.greek-added} περιβεβλημενη [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον κεχρυσωμενη [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις εχουσα [χρυσουν]{.greek-added} ποτηριον [χρυσουν]{.greek-omitted} εν τη χειρι αυτης γεμον [βδελυγματων]{.greek-omitted} [βδελυγματα]{.greek-added} και τα ακαθαρτα της πορνειας αυτης[17:4]{.aside}

και επι το μετωπον αυτης ονομα γεγραμμενον μυστηριον βαβυλων η μεγαλη η [μητηρ]{.greek-abbr} των [πορνων]{.greek-omitted} [πορνῶν]{.greek-added} και των βδελυγματων της γης[17:5]{.aside}

και ειδον την γυναικα μεθυουσαν εκ του αιματος των αγιων [και]{.greek-added} εκ του αιματος των μαρτυρων [ιησου]{.greek-abbr} και εθαυμασα ιδων αυτην θαυμα μεγα[17:6]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μοι ο αγγελος δια τι εθαυμασας εγω [σοι]{.greek-added} ερω [σοι]{.greek-omitted} το μυστηριον της γυναικος και του θηριου του βασταζοντος αυτην του εχοντος τας [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} κεφαλας και τα δεκα κερατα[17:7]{.aside}

το θηριον ο ειδες ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και μελλει αναβαινειν εκ της αβυσσου και εις απωλειαν υπαγειν και θαυμασονται οι κατοικουντες επι της γης ων ου γεγραπται τα ονοματα επι το βιβλιον της ζωης απο καταβολης κοσμου βλεποντων [το]{.greek-added} [θηριον]{.greek-added} οτι ην [το]{.greek-omitted} [θηριον]{.greek-omitted} και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και παρεσται[17:8]{.aside}

ωδε ο νους ο εχων σοφιαν αι [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} κεφαλαι επτα ορη εισιν οπου η γυνη καθηται επ αυτων [και]{.greek-added} [βασιλεις]{.greek-added} [[ζ]{.greek-abbr}]{.greek-added} [εισιν]{.greek-added}[17:9]{.aside}

[και]{.greek-omitted} [βασιλεις]{.greek-omitted} [εισιν]{.greek-omitted} [επτα]{.greek-omitted} οι πεντε [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ο εις εστιν ο αλλος ουπω [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και οταν ελθη ολιγον [αυτον]{.greek-added} δει [αυτον]{.greek-omitted} μειναι[17:10]{.aside}

και το θηριον ο ην και ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} και αυτος ογδοος [εστιν]{.greek-omitted} [εστι]{.greek-added} και εκ των [επτα]{.greek-omitted} [[ζ]{.greek-abbr}]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} και εις απωλειαν υπαγει[17:11]{.aside}

και τα δεκα κερατα α ειδες δεκα βασιλεις εισιν οιτινες βασιλειαν ουπω ελαβον αλλ εξουσιαν ως βασιλεις μιαν ωραν [λαμβανουσιν]{.greek-omitted} [λαμβανουσι]{.greek-added} μετα του θηριου[17:12]{.aside}

ουτοι μιαν [εχουσιν]{.greek-omitted} γνωμην [εχουσι]{.greek-added} και την δυναμιν και την εξουσιαν αυτων τω θηριω διδοασιν[17:13]{.aside}

ουτοι μετα του αρνιου [πολεμησουσιν]{.greek-omitted} [πολεμησουσι]{.greek-added} και το αρνιον νικησει αυτους οτι κυριος κυριων [εστιν]{.greek-omitted} [εστι]{.greek-added} και βασιλευς βασιλεων και οι μετ αυτου κλητοι και εκλεκτοι και πιστοι[17:14]{.aside}

και λεγει μοι τα υδατα α ειδες ου η πορνη καθηται λαοι και οχλοι [εισιν]{.greek-omitted} [εισι]{.greek-added} και εθνη και [φυλαι]{.greek-added} [και]{.greek-added} γλωσσαι[17:15]{.aside}

και τα δεκα κερατα α ειδες και το θηριον ουτοι [μισησουσιν]{.greek-omitted} [μισησουσι]{.greek-added} την πορνην και ηρημωμενην [ποιησουσιν]{.greek-omitted} [αυτην]{.greek-omitted} [και]{.greek-omitted} [γυμνην]{.greek-omitted} ποιησουσιν αυτην και τας σαρκας αυτης φαγονται και αυτην κατακαυσουσιν εν πυρι[17:16]{.aside}

ο γαρ [θεος]{.greek-abbr} εδωκεν εις τας καρδιας αυτων ποιησαι την γνωμην αυτου και ποιησαι γνωμην μιαν και δουναι την βασιλειαν αυτων τω θηριω αχρι [τελεσθωσιν]{.greek-omitted} [τελεσθησονται]{.greek-added} οι λογοι του [θεου]{.greek-abbr}[17:17]{.aside}

και η γυνη ην ειδες εστιν η πολις η μεγαλη η εχουσα βασιλειαν επι των βασιλεων της γης[17:18]{.aside}

### Chapter 18

[και]{.greek-added} μετα ταυτα ειδον αλλον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα εξουσιαν μεγαλην και η γη εφωτισθη εκ της δοξης αυτου[18:1]{.aside}

και εκραξεν [εν]{.greek-added} ισχυρα φωνη λεγων επεσεν [επεσε]{.greek-added} βαβυλων η μεγαλη και εγενετο κατοικητηριον δαιμονων και φυλακη παντος πνευματος ακαθαρτου [και]{.greek-omitted} [[φυ]{.greek-supplied}λακη]{.corr} [παντος]{.corr} [[ορνε]{.greek-supplied}ου]{.corr} [ακαθαρτου]{.corr} και [φυλακη]{.greek-added} [παντος]{.greek-added} [θηριου]{.greek-added} [ακαθαρτου]{.greek-added} [και]{.greek-added} μεμισημενου[18:2]{.aside}

οτι εκ του [θυμου]{.greek-added} [του]{.greek-added} οινου [του]{.greek-omitted} [θυμου]{.greek-omitted} της πορνειας αυτης [πεπτωκασιν]{.greek-omitted} [πεπωκε]{.greek-added} παντα τα εθνη και οι βασιλεις της γης μετ αυτης επορνευσαν και οι εμποροι της γης εκ της δυναμεως του [στρηνους]{.greek-omitted} [στρηνου]{.greek-added} αυτης επλουτησαν[18:3]{.aside}

και ηκουσα αλλην φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν [εξελθε]{.greek-omitted} [εξελθετε]{.greek-added} [εξ]{.greek-omitted} [αυτης]{.greek-omitted} ο λαος μου ινα μη συγκοινωνησητε ταις αμαρτιαις αυτης και εκ των πληγων αυτης ινα μη λαβητε[18:4]{.aside}

οτι εκολληθησαν αυτης αι αμαρτιαι αχρι του [ουρανου]{.greek-abbr} και εμνημονευσεν ο [θεος]{.greek-abbr} τα αδικηματα αυτης[18:5]{.aside}

αποδοτε αυτη ως και αυτη απεδωκεν [υμιν]{.greek-added} και διπλωσατε αυτη διπλα κατα τα εργα αυτης εν τω ποτηριω [ω]{.greek-omitted} [ωι]{.greek-added} [εκερασεν]{.greek-omitted} [εκερασε]{.greek-added} κερασατε αυτη διπλουν[18:6]{.aside}

οσα εδοξασεν [αυτην]{.greek-omitted} [εαυτην]{.greek-added} και [εστρηνιασεν]{.greek-omitted} [εστρηνιασε]{.greek-added} τοσουτον δοτε αυτη βασανισμον [και]{.greek-omitted} [πενθος]{.greek-omitted} οτι εν τη καρδια αυτης λεγει οτι καθημαι βασιλισσα και χηρα ουκ ειμι και πενθος ου μη ιδω[18:7]{.aside}

δια τουτο εν μια ημερα ηξουσιν αι πληγαι αυτης θανατος και πενθος και λιμος και εν πυρι κατακαυθησεται οτι ισχυρος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο κρινας αυτην[18:8]{.aside}

και [κλαυσουσιν]{.greek-omitted} [κλαυσονται]{.greek-added} και κοψονται επ αυτην οι βασιλεις της γης οι μετ αυτης πορνευσαντες και στρηνιασαντες [και]{.greek-added} [πλουτησαντες]{.greek-added} οταν [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} τον καπνον της πυρωσεως αυτης[18:9]{.aside}

απο μακροθεν εστηκοτες δια τον φοβον του βασανισμου αυτης λεγοντες ουαι ουαι η πολις η μεγαλη βαβυλων η πολις η ισχυρα οτι [εν]{.greek-added} μια ωρα ηλθεν η κρισις σου[18:10]{.aside}

και οι εμποροι της γης [κλαυσουσιν]{.greek-omitted} [κλαιουσι]{.greek-added} και [πενθησουσιν]{.greek-omitted} [πενθουσιν]{.greek-added} επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} οτι τον γομον αυτων ουδεις αγοραζει ουκετι[18:11]{.aside}

γομον χρυσου και αργυρου και λιθου τιμιου και μαργαριτου και [βυσσινου]{.greek-omitted} [βυσσου]{.greek-added} και πορφυρου και σηρικου και κοκκινου και παν ξυλον θυινον και παν σκευος ελεφαντινον και παν σκευος εκ ξυλου τιμιωτατου και χαλκου και σιδηρου και μαρμαρου[18:12]{.aside}

και [κιναμωμον]{.greek-omitted} [κινναμωμον]{.greek-added} και θυμιαματα και μυρον και λιβανο[ν]{.unclear} και οινον και ελαιον και σεμιδαλιν και σιτον και [κτηνη]{.greek-added} [και]{.greek-added} προβατα [και]{.greek-omitted} [κτηνη]{.greek-omitted} και ιππων και [ραιδων]{.greek-omitted} [ρεδων]{.greek-added} και σωματων και ψυχας [ανθρωπων]{.greek-abbr}[18:13]{.aside}

και η οπωρα της επιθυμιας της ψυχης σου απηλθεν απο σου και παντα τα λιπαρα και τα λαμπρα [απωλετο]{.greek-omitted} [απωλοντο]{.greek-added} απο σου και ουκετι [αυτα]{.greek-omitted} ου μη [ευρης]{.greek-omitted} [ευρησεις]{.greek-added} [αυτα]{.greek-added}[18:14]{.aside}

οι εμποροι τουτων οι πλουτησαντες απ αυτης απο μακροθεν στησονται δια τον φοβον του βασανισμου αυτης κλαιοντες και πενθουντες[18:15]{.aside}

και λεγοντες [ουαι]{.greek-omitted} ουαι η πολις η μεγαλη [βαβυλων]{.greek-added} η περιβεβλημενη βυσσινον και [πορφυρουν]{.greek-omitted} [πορφυραν]{.greek-added} και κοκκινον και κεχρυσωμενη [εν]{.greek-added} [χρυσιω]{.greek-omitted} [χρυσω]{.greek-added} και λιθω τιμιω και μαργαριταις[18:16]{.aside}

οτι μια ωρα ηρημωθη ο τοσουτος πλουτος και πας κυβερνητης και πας ο επι [τοπον]{.greek-omitted} [των]{.greek-added} [πλοιων]{.greek-added} πλεων και ναυται και οσοι την θαλασσαν εργαζονται απο μακροθεν εστησαν[18:17]{.aside}

και εκραζον βλεποντες τον καπνον της πυρωσεως αυτης λεγοντες τις ομοια τη πολει τη μεγαλη[18:18]{.aside}

και εβαλον χουν επι τας κεφαλας αυτων και εκραζον κλαιοντες και πενθουντες και λεγοντες ουαι ουαι η πολις η μεγαλη εν η επλουτησαν παντες οι εχοντες [τα]{.greek-omitted} πλοια εν [τη]{.greek-omitted} [τηι]{.greek-added} [θαλασση]{.greek-omitted} [θαλασσηι]{.greek-added} εκ της τιμιοτητος αυτης οτι μια ωρα ηρημωθη[18:19]{.aside}

ευφραινου επ αυτη [ουρανε]{.greek-abbr} και οι αγιοι [και]{.greek-omitted} [οι]{.greek-omitted} αποστολοι και οι προφηται οτι εκρινεν ο [θεος]{.greek-abbr} το κριμα υμων εξ αυτης[18:20]{.aside}

και ηρεν εις αγγελος ισχυρος λιθον ως μυλον μεγαν και εβαλεν εις την θαλασσαν λεγων ουτως ορμηματι βληθησεται βαβυλων η μεγαλη πολις και ου μη ευρεθη ετι[18:21]{.aside}

και φωνη κιθαρωδων και μουσικων και αυλητων και σαλπιστων ου μη ακουσθη εν σοι ετι [και]{.greek-omitted} [πας]{.greek-omitted} [τεχνιτης]{.greek-omitted} [πασης]{.greek-omitted} [τεχνης]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ευρεθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted} [και]{.greek-omitted} [φωνη]{.greek-omitted} [μυλου]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [ακουσθη]{.greek-omitted} [εν]{.greek-omitted} [σοι]{.greek-omitted} [ετι]{.greek-omitted}[18:22]{.aside}

και φως λυχνου ου μη [φανη]{.greek-omitted} [φανῆ]{.greek-added} εν σοι ετι και φωνη νυμφιου και νυμφης ου μη ακουσθη εν σοι ετι οτι οι εμποροι σου ησαν οι μεγιστανες της γης οτι εν τη φαρμακεια σου επλανηθησαν παντα τα εθνη[18:23]{.aside}

και εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} αιματα προφητων και αγιων ευρεθη και παντων των εσφαγμενων επι της γης[18:24]{.aside}

### Chapter 19

[και]{.greek-added} μετα ταυτα ηκουσα [ως]{.greek-omitted} φωνην [μεγαλην]{.greek-omitted} οχλου πολλου εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} λεγοντων [αλληλουια]{.greek-omitted} [ἀλληλόυια]{.greek-added} η [σωτηρια]{.greek-abbr} και η δυναμις και η δοξα του [θεου]{.greek-abbr} ημων[19:1]{.aside}

οτι αληθιναι και δικαιαι αι κρισεις αυτου οτι [εκρινεν]{.greek-omitted} [εκρινε]{.greek-added} την πορνην την μεγαλην ητις [διεφθειρεν]{.greek-omitted} [διεφθειρ[ος]{.unclear}]{.greek-added} την γην εν τη πορνεια αυτης και [εξεδικησεν]{.greek-omitted} [εξεδικησε]{.greek-added} το αιμα των δουλων αυτου εκ χειρος αυτης[19:2]{.aside}

και δευτερον [ειρηκεν]{.greek-omitted} [ειρηκαν]{.greek-added} αλληλουια και ο καπνος αυτης αναβαινει εις τους αιωνας των αιωνων[19:3]{.aside}

και [επεσον]{.greek-omitted} [επεσαν]{.greek-added} οι πρεσβυτεροι οι εικοσι τεσσαρες και τα τεσσαρα ζωα και προσεκυνησαν [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} τω καθημενω επι του θρονου λεγοντες αμην αλληλουια[19:4]{.aside}

και φωνη [απο]{.greek-omitted} [εκ]{.greek-added} του θρονου [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} λεγουσα αινειτε τον [θεον]{.greek-abbr} [ημων]{.greek-omitted} [υμων]{.greek-added} παντες οι δουλοι αυτου και οι φοβουμενοι αυτον οι μικροι και οι μεγαλοι[19:5]{.aside}

και ηκουσα [ως]{.greek-omitted} φωνην οχλου πολλου και ως φωνην υδατων πολλων και ως φωνην βροντων ισχυρων [λεγοντες]{.greek-omitted} [λεγοντων]{.greek-added} [αλληλουια]{.greek-omitted} οτι [εβασιλευσεν]{.greek-omitted} [εβασιλευσε]{.greek-added} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων ο παντοκρατωρ[19:6]{.aside}

χαιρωμεν και [αγαλλιωμεθα]{.greek-omitted} [αγαλλιωμεν]{.greek-added} και δωμεν [την]{.greek-omitted} δοξαν [αυτω]{.greek-omitted} [αυτωι]{.greek-added} οτι ηλθεν ο γαμος του αρνιου και η γυνη αυτου ητοιμασεν εαυτην[19:7]{.aside}

και εδοθη αυτη ινα [περιβαληται]{.greek-omitted} [περιβαλληται]{.greek-added} βυσσινον λαμπρον και καθαρον το γαρ βυσσινον τα δικαιωματα των αγιων [εστιν]{.greek-omitted} [εστι]{.greek-added}[19:8]{.aside}

και λεγει μοι γραψον μακαριοι οι εις το δειπνον του γαμου του αρνιου κεκλημενοι και λεγει μοι ουτοι οι λογοι αληθινοι [εισι]{.greek-added} του [θεου]{.greek-abbr} [εισιν]{.greek-omitted}[19:9]{.aside}

και επεσα εμπροσθεν των ποδων αυτου προσκυνησαι [αυτω]{.greek-omitted} [αυτωι]{.greek-added} και λεγει μοι ορα μη συνδουλος σου ειμι και των αδελφων σου των εχοντων την μαρτυριαν [ιησου]{.greek-abbr} [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-abbr} προσκυνησον η γαρ μαρτυρια του [ιησου]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} το [πνευμα]{.greek-abbr} της προφητειας[19:10]{.aside}

και ειδον τον [ουρανον]{.greek-abbr} ανεωγμενον και ιδου ιππος λευκος και ο καθημενος επ αυτον καλουμενος πιστος και αληθινος και εν δικαιοσυνη κρινει και πολεμει[19:11]{.aside}

οι δε οφθαλμοι αυτου φλοξ πυρος και επι την κεφαλην αυτου διαδηματα πολλα εχων ονοματα γεγραμμενα και ονομα γεγραμμενον [και]{.greek-added} ο ουδεις οιδεν ει μη αυτος[19:12]{.aside}

και περιβεβλημενος ιματιον [πορφυρουν]{.greek-added} βεβαμμενον αιματι και καλειται το ονομα αυτου ο λογος του [θεου]{.greek-abbr}[19:13]{.aside}

και τα στρατευματα τα εν [τω]{.greek-omitted} [τωι]{.greek-added} [ουρανω]{.greek-omitted} [[ουνωι]{.greek-abbr}]{.greek-added} ηκολου[θει]{.unclear} [αυτω]{.greek-omitted} [[αυτ]{.unclear}ωι]{.greek-added} [επι]{.greek-omitted} [εφ]{.greek-added} ιπποις λευκοις ενδεδυμενοι βυσσινον λευκον καθαρον[19:14]{.aside}

και εκ του στοματος αυτου εκπορευεται ρομφαια διστομος οξεια ινα εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} παταξη τα εθνη και αυτος ποιμανει αυτους εν ραβδω σιδηρα και αυτος πατει την ληνον του οινου του θυμου της οργης του [θεου]{.greek-abbr} του παντοκρατορος[19:15]{.aside}

και εχει επι το ιματιον και επι τον μηρον αυτου ονομα γεγραμμενον βασιλευς βασιλεων και κυριος κυριων[19:16]{.aside}

και ειδον [ενα]{.greek-added} αγγελον εστωτα εν τω ηλιω και [εκραξεν]{.greek-omitted} [εκραξε]{.greek-added} φωνη μεγαλη λεγων [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις ορνεοις τοις πετομενοις εν μεσουρανηματι δευτε [συναχθητε]{.greek-omitted} εις το δειπνον το μεγα του [θεου]{.greek-abbr}[19:17]{.aside}

ινα φαγητε σαρκας βασιλεων και σαρκας χιλιαρχων και σαρκας ισχυρων και σαρκας ιππων και των καθημενων επ αυτων και σαρκας παντων ελευθερων τε και δουλων και μικρων [τε]{.greek-omitted} και μεγαλων[19:18]{.aside}

και ειδον το θηριον και τους βασιλεις της γης και τα στρατευματα αυτων συνηγμενα ποιησαι πολεμον μετα του καθημενου επι του ιππου και μετα του στρατευματος αυτου[19:19]{.aside}

και επιασθη το θηριον και [ο]{.greek-omitted} μετ αυτου [ο]{.greek-added} ψευδοπροφητης ο ποιησας τα σημεια ενωπιον αυτου εν οις [επλανησεν]{.greek-omitted} [επλανησε]{.greek-added} τους λαβοντας το χαραγμα του θηριου και τους προσκυνουντας τη εικονι αυτου ζωντες [εβληθησαν]{.greek-omitted} [βληθησονται]{.greek-added} οι δυο εις την [λιμνην]{.greek-omitted} [καμινον]{.greek-added} του πυρος την καιομενην εν θειω[19:20]{.aside}

και οι λοιποι απεκτανθησαν εν [τη]{.greek-omitted} [τηι]{.greek-added} ρομφαια του καθημενου επι του ιππου τη εξελθουση εκ του στοματος αυτου και παντα τα ορνεα εχορτασθησαν εκ των σαρκων αυτων[19:21]{.aside}

### Chapter 20

και ειδον αγγελον καταβαινοντα εκ του [ουρανου]{.greek-abbr} εχοντα την κλειν της αβυσσου και αλυσιν μεγαλην επι την χειρα αυτου[20:1]{.aside}

και εκρατησεν το[ν]{.unclear} δ[ρ]{.unclear}ακον[τα]{.unclear} τον οφιν τον αρχαιον ος εστιν [ο]{.greek-added} διαβολος και ο σατανας [ο]{.greek-omitted} [πλανων]{.greek-omitted} [την]{.greek-omitted} [οικουμενην]{.greek-omitted} [ολην]{.greek-omitted} [και]{.greek-omitted} εδησεν αυτον [χ]{.unclear}ιλια ετη[20:2]{.aside}

[κ]{.unclear}αι εβαλεν αυτον εις την αβυσσον και [εκλεισεν]{.greek-omitted} [εκλεισε]{.greek-added} [και]{.unclear} εσφρα[γισεν]{.unclear} [ε]{.unclear}πανω αυτου ινα μη πλανα ετι τα εθνη αχρι τελεσθη τα χιλια ετη και μετα ταυτα δει [λυθηναι]{.greek-added} αυτον [λυθηναι]{.greek-omitted} μικρον χρονον[20:3]{.aside}

και ειδον θρονους και εκαθισαν επ αυτους και κριμα εδοθη αυτ[οις]{.unclear} και τας ψυχας των [πεπελεκισμενων]{.greek-omitted} [πεπελεκημενων]{.greek-added} δια την μαρτυριαν [ιησου]{.greek-abbr} και δια τον λογον του [θεου]{.greek-abbr} [και]{.greek-omitted} οιτινες ου προσεκυνησαν [το]{.greek-omitted} [θηριον]{.greek-omitted} [τω]{.greek-added} [θηριω]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [εικονα]{.greek-omitted} [εικονι]{.greek-added} αυτου και ουκ ελαβον το χαραγμα επι το μετωπον [αυτων]{.greek-added} και επι την χειρα [αυτων]{.greek-omitted} και εζησαν και εβασιλευσαν μετα του [χριστου]{.greek-abbr} [τα]{.greek-omitted} χιλια ετη[20:4]{.aside}

και οι λοιποι των νεκρων ουκ εζησαν αχρι τελεσθη τα χιλια ετη αυτη η αναστασις η πρωτη[20:5]{.aside}

μακαριος και αγιος ο εχων μερος εν τη αναστασει τη πρωτη επι τουτων ο [δευτερος]{.greek-omitted} θανατος ουκ εχει εξουσιαν [ο]{.greek-added} [δευτερος]{.greek-added} αλλ εσονται ιερεις του [θεου]{.greek-abbr} και του [χριστου]{.greek-abbr} και [βασιλευσουσιν]{.greek-omitted} [βασιλευσουσι]{.greek-added} μετ αυτου χιλια ετη[20:6]{.aside}

και οταν τελεσθη τα χιλια ετη λυθησεται ο σατανας εκ της φυλακης αυτου[20:7]{.aside}

και εξελευσεται πλανησαι τα εθνη τα εν ταις [τεσσαρσιν]{.greek-omitted} [τεσσαρσι]{.greek-added} γωνιαις της γης τον γωγ και τον μαγωγ συναγαγειν αυτους εις τον πολεμον ων ο αριθμος [ωσει]{.greek-added} [ως]{.greek-omitted} [η]{.greek-omitted} αμμος της θαλασσης[20:8]{.aside}

και ανεβησαν επι το πλατος της γης και [εκυκλωσαν]{.greek-omitted} [εκυκλευσαν]{.greek-added} την παρεμβολην των αγιων και την πολιν την ηγαπημενην και κατεβη πυρ εκ του [ουρανου]{.greek-abbr} απο του [θεου]{.greek-omitted} και [κατεφαγεν]{.greek-omitted} [κατεφλεξεν]{.greek-added} αυτους[20:9]{.aside}

και ο διαβολος ο πλανων αυτους εβληθη εις την λιμνην του πυρος και θειου οπου και το θηριον και ο ψευδοπροφητης και βασανισθησονται ημερας και νυκτος εις τους αιωνας των αιωνων[20:10]{.aside}

### Chapter 21

[και]{.greek-added} οι θεμελιοι του τειχους της πολεως παντι λιθω τι[μιω]{.unclear} [κεκοσμη]{.unclear}μενοι ο θεμελιος ο πρωτος ιασπις ο δευτερος [σαπφειρος]{.greek-omitted} [σαπφιρος]{.greek-added} ο τριτος χαλκη[δων]{.greek-supplied} ο τεταρτος σμαραγδος[21:19]{.aside}

ο πεμπτος [σαρδονυξ]{.greek-omitted} [σαρδωνυξ]{.greek-added} ο εκτος σαρδιον [ο]{.greek-omitted} [εβδομος]{.greek-omitted} χρυσολιθος ο ογδοος βηρυλλος ο ενατος τοπαζιον ο δ[εκατ]{.unclear}ος χρυσοπρασος ο ενδεκατος [υακινθος]{.greek-omitted} [υακινθινος]{.greek-added} ο δωδεκατος [αμεθυσος]{.greek-omitted} [αμεθυσ[τος]{.unclear}]{.greek-added}[21:20]{.aside}

και [οι]{.greek-omitted} [ο]{.greek-added} δωδεκα πυλωνες δωδεκα μαργαριται [ανα]{.greek-omitted} [αν]{.greek-added} εις [και]{.greek-added} εκαστος [των]{.unclear} πυλωνων ην εξ ενος μαργαριτου και η πλατεια της πολεως χρυσιον καθαρον ως υελος διαυγης[21:21]{.aside}

και ναον ουκ ειδον εν αυτη ο [γαρ]{.greek-supplied} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ναος αυτης [εστιν]{.greek-omitted} [εστι]{.greek-added} και το αρνιον[21:22]{.aside}

[και]{.greek-omitted} η πολις ου χρειαν εχει του ηλιου ουδε της σεληνης ινα φαινω[σιν]{.greek-supplied} αυτη η γαρ δοξα του [θεου]{.greek-abbr} εφωτισεν αυτην και ο λυχν[ος]{.greek-supplied} [αυτης]{.greek-omitted} το αρνιον[21:23]{.aside}

και [περιπατησουσιν]{.greek-omitted} [περιπατησουσι]{.greek-added} τα εθνη δια του φω[τος]{.greek-supplied} αυ[της]{.greek-supplied} και οι βασιλεις της γης [φερουσιν]{.greek-omitted} [φε[ρο]{.unclear}υσι]{.greek-added} [αυτω]{.greek-omitted} [την]{.greek-added} δοξαν και [την]{.greek-added} τιμην [των]{.greek-omitted} [αυτων]{.greek-added} [εθνων]{.greek-omitted} εις αυτην[21:24]{.aside}

και οι πυλωνες αυτης ου μη κλεισθωσιν ημερας νυξ γαρ ουκ εσται εκει[21:25]{.aside}

και [οισουσιν]{.greek-omitted} [οισουσι]{.greek-added} την δοξαν και την τιμην [των]{.greek-omitted} [εθνων]{.greek-omitted} εις αυτην [ινα]{.greek-added} [εις]{.greek-added} [ενθωσι]{.greek-added}[21:26]{.aside}

και ου μη εισελθη εις αυτην παν κοινον και [ποιουν]{.greek-omitted} [ο]{.greek-added} [ποιων]{.greek-added} βδελυγμα και ψευδος ει μη οι γεγραμμενοι εν τω βιβλιω της ζωης του αρνιου[21:27]{.aside}

### Chapter 22

και [εδειξεν]{.greek-omitted} [εδειξε]{.greek-added} μοι ποταμον καθαρον υδατος ζωης λαμπρον ως κρυσταλλον εκπορευομενον εκ του θρονου του [θεου]{.greek-abbr} και του αρνιου[22:1]{.aside}

εν μεσω της πλατειας αυτης και του ποταμου εντευθεν και [εκειθεν]{.greek-omitted} [εντευθεν]{.greek-added} ξυλον ζωης ποιουν καρπους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} κατα [μ]{.unclear}ηνα [ενα]{.greek-added} [ε]{.greek-supplied}καστον [αποδιδους]{.greek-omitted} [αποδιδον]{.greek-added} τον καρπον αυτου και τα [φυλλα]{.greek-supplied} του ξ[υλου]{.greek-supplied} εις θεραπειαν των εθνων[22:2]{.aside}

και παν καταθεμα ου[κ]{.unclear} [εστ]{.unclear}αι [ετι]{.unclear} και ο θρονος του [θεου]{.greek-abbr} και του αρνιου εν [αυτη]{.greek-omitted} [αυτηι]{.greek-added} [εσ]{.unclear}ται και οι δουλοι αυτο[υ]{.unclear} [λατρευσουσιν]{.greek-omitted} [λατρευουσιν]{.greek-added} αυτω[22:3]{.aside}

και οψονται το προσωπον αυ[του]{.greek-supplied} [και]{.greek-supplied} το ονομα αυτου επι των μετωπων αυτων[22:4]{.aside}

και νυξ ουκ εσται [εκει]{.greek-omitted} [και]{.greek-supplied} [[ουκ]{.greek-supplied}]{.greek-added} [χρειαν]{.greek-supplied} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} λυχνου και φωτος ηλιου οτι [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} φωτιει αυτους και βασιλευσουσιν εις τους αιωνας των αιωνων[22:5]{.aside}

[κα]{.greek-supplied}ι λεγει μοι ουτοι οι λογοι πιστοι και αληθινοι και [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} [τω]{.unclear}ν [πνευματων]{.greek-omitted} [των]{.greek-omitted} προφητων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τον αγγελον αυτου δειξαι τοις δουλ[οι]{.unclear}ς αυτου α δει γενεσθαι εν ταχει[22:6]{.aside}

[και]{.greek-omitted} ιδου ερχομαι ταχυ [μ]{.greek-supplied}[α]{.unclear}καριος ο τηρων τους λογους της προφητειας του [βιβ]{.greek-supplied}λιου [το]{.unclear}υτου[22:7]{.aside}

[καγω]{.greek-supplied} [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο [βλεπων]{.greek-added} [και]{.greek-added} ακουων [και]{.greek-omitted} [βλεπων]{.greek-omitted} ταυτα [και]{.greek-omitted} οτε ηκουσα και [εβ]{.greek-supplied}λεψα [επεσον]{.greek-omitted} [επεσα]{.greek-added} προσκυνησαι εμπροσθεν των [πο]{.greek-supplied}[δω]{.unclear}ν του αγγελου του δεικνυοντος μοι ταυτα[22:8]{.aside}

[κα]{.greek-supplied}ι λεγει μοι ορα μη συν[δ]{.unclear}ουλος σου ειμι [κ]{.greek-supplied}αι των αδελφων σου των προφητων [και]{.greek-omitted} των [τ]{.greek-supplied}ηρουντων τους λογους του βιβλιου τουτου [τω]{.greek-omitted} [τωι]{.greek-added} [θεω]{.greek-omitted} [[θωι]{.greek-abbr}]{.greek-added} προσκυνησον[22:9]{.aside}

και λεγει μοι μη σφραγισης τους λογους της προφητειας του βιβλιου τουτου [οτι]{.greek-added} ο καιρος [γαρ]{.greek-omitted} εγγυς εστιν[22:10]{.aside}

ο αδι[κ]{.unclear}ων αδικησατω [ετι]{.greek-omitted} και ο ρυπαρος ρυπαρευθητω ετι και ο δικαιος δικαιοσυνην ποιησατω ετι και ο αγιος [αγ]{.greek-supplied}[ια]{.unclear}σθητω ετι[22:11]{.aside}

ιδου ερχομαι ταχυ και ο μ[ισ]{.greek-supplied}[θος]{.greek-supplied} [μου]{.greek-supplied} [μετ]{.greek-supplied} [εμου]{.greek-supplied} [απ]{.unclear}οδουναι εκαστω ως το ερ[γον]{.greek-supplied} [εσται]{.greek-omitted} [[εστιν]{.greek-supplied}]{.greek-added} [αυ]{.unclear}του[22:12]{.aside}

εγω το αλφα [και]{.unclear} [το]{.unclear} [ω]{.unclear} ο πρωτος [και]{.greek-supplied} ο εσ[χατ]{.unclear}ος η αρχη και το τελος[22:13]{.aside}

μακαριοι οι [ποιουντες]{.greek-omitted} [[πλυν]{.greek-supplied}[ον]{.unclear}τες]{.greek-added} τας εντολας αυτου ινα [εστ]{.unclear}αι η εξουσια αυτων [επι]{.greek-supplied} [το]{.greek-supplied} [ξυ]{.greek-supplied}λον της ζωης και τοις [πυλωσιν]{.greek-omitted} [πυλωσι]{.greek-added} [εισελθωσιν]{.greek-omitted} [εισ[ελθω]{.unclear}[σι]{.greek-supplied}]{.greek-added} εις την πολιν[22:14]{.aside}

εξω οι κυνες και οι φαρμα[κοι]{.greek-supplied} και ο[ι]{.greek-supplied} [πορνοι]{.greek-supplied} και οι φονεις και οι ειδωλολατραι κα[ι]{.greek-supplied} [πας]{.greek-supplied} [φιλων]{.greek-supplied} και ποιων ψευδος[22:15]{.aside}

εγω [ιησους]{.greek-abbr} επεμψα τον αγγελον μου μαρτυρησ[αι]{.greek-supplied} υμιν τα[υ]{.unclear}[τα]{.greek-supplied} [επι]{.greek-supplied} ταις εκκλησιαις εγω ειμι η ριζα και [το]{.greek-supplied} [γενος]{.greek-supplied} [δαυιδ]{.greek-abbr} ο αστηρ ο λαμπρος ο πρωινος[22:16]{.aside}

κ[αι]{.unclear} [το]{.unclear} [πνευμα]{.greek-abbr} και η νυμφη λεγουσιν [ερχου]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ακουων]{.greek-omitted} [ειπατω]{.greek-omitted} ερχου και ο διψων [ερ]{.greek-supplied}χεσθω ο θελων λαβετω υδωρ ζωης δω[ρεαν]{.greek-supplied}[22:17]{.aside}

[μαρτυρω]{.greek-omitted} [μαρτυρομαι]{.greek-added} εγω παντι τω ακουοντι τους λογους της προφητειας του βιβλιου τουτου εαν [τις]{.greek-supplied} [επι]{.unclear}[θη]{.greek-supplied} επ αυτα [επιθησαι]{.greek-omitted} [επιθησεται]{.greek-added} ο [θεος]{.greek-abbr} επ αυτον τας [ε[πτα]{.greek-supplied}]{.greek-added} πλ[η]{.unclear}γ[ας]{.greek-supplied} τας γεγραμμενας εν τω βιβλιω τουτω[22:18]{.aside}

και εαν τις αφελη απο των λογων του βιβλιου της προφητειας ταυτης αφελοι ο [θεος]{.greek-abbr} το μερος αυτου απο του [ξυ]{.greek-supplied}λου της ζωης και εκ της πολεως της αγιας των γεγραμμενων εν τω βιβλιω τουτω[22:19]{.aside}

λεγει ο μαρτυρων ταυτα ναι ερχομαι ταχυ αμην [ναι]{.greek-omitted} [και]{.greek-added} ερχου [κυριε]{.greek-abbr} [ιησου]{.greek-abbr} [[χριστε]{.greek-abbr}]{.greek-added}[22:20]{.aside}

η χαρις του [κυριου]{.greek-omitted} [[θεου]{.greek-abbr}]{.greek-added} [ημων]{.greek-added} [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} μετα παντων των αγιων αμην[22:21]{.aside}

