---
title: "Collation of Byz^RP^ vs 32236 (2236)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2236 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32236).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2236                                   	| λογος                              	|
| 2236 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2236 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2236               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2236                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2236 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2236                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Luke

### Chapter 1

επειδηπερ πολλ[οι]{.unclear} επεχειρησαν αναταξασθαι [διηγησιν]{.greek-omitted} [διηγησην]{.greek-added} περι των πεπληροφορημενων εν ημιν πραγματων[1:1]{.aside}

καθως [παρεδοσαν]{.greek-omitted} [παρεδωσαν]{.greek-added} ημιν οι απ αρχης αυτοπται και υπηρεται γενομενοι του λογου[1:2]{.aside}

[εδοξεν]{.greek-omitted} [εδοξε]{.greek-added} καμοι [παρηκολουθηκοτι]{.greek-omitted} [παρηκολουθηκοτη]{.greek-added} ανωθεν πασιν ακριβως καθεξης σοι γραψαι κρατιστε θεοφιλε[1:3]{.aside}

ινα επιγνως περι ων κατηχηθης [λογων]{.greek-omitted} [λογον]{.greek-added} την [ασφαλειαν]{.greek-omitted} [ασφαλιαν]{.greek-added}[1:4]{.aside}

εγενετο εν ταις ημεραις ηρωδου του βασιλεως της ιουδαιας ιερευς τις ονοματι ζαχαριας [εξ]{.greek-omitted} εφημεριας αβια και η γυνη αυτου εκ των θυγατερων ααρων και το ονομα αυτης ελισαβετ[1:5]{.aside}

ησαν δε δικαιοι αμφοτεροι [ενωπιον]{.greek-omitted} [ενωποιον]{.greek-added} του [θεου]{.greek-abbr} πορευομενοι εν πασαις ταις εντολαις και [δικαιωμασιν]{.greek-omitted} [δικαιωμασι]{.greek-added} του [κυριου]{.greek-abbr} αμεμπτοι[1:6]{.aside}

και ουκ [ην]{.greek-omitted} [ειν]{.greek-added} αυτοις τεκνον καθοτι η ελισαβετ ην στειρα και αμφοτεροι [προβεβηκοτες]{.greek-omitted} [προβεβηκοταις]{.greek-added} εν ταις ημεραις αυτων ησαν[1:7]{.aside}

εγενετο δε εν τω ιερατευειν αυτον εν τη [ταξει]{.greek-omitted} [ταξη]{.greek-added} της εφημεριας αυτου εναντι του [θεου]{.greek-abbr}[1:8]{.aside}

κατα το εθος της ιερατειας [ελαχεν]{.greek-omitted} [ελαχε]{.greek-added} του θυμιασαι εισελθων εις τον ναον του [κυριου]{.greek-abbr}[1:9]{.aside}

και παν [το]{.greek-omitted} [τω]{.greek-added} πληθος ην του λαου [προσευχομενον]{.greek-omitted} [προσευχωμενον]{.greek-added} εξω τη ωρα του θυμιαματος[1:10]{.aside}

ωφθη δε αυτω αγγελος [κυριου]{.greek-abbr} εστως εκ δεξιων του θυσιαστηριου του θυμιαματος[1:11]{.aside}

και εταραχθη ζαχαριας ιδων και φοβος επεπεσεν επ αυτον[1:12]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} δε προς αυτον ο [αγγελος]{.greek-omitted} [μη]{.greek-omitted} [φοβου]{.greek-omitted} [ζαχαρια]{.greek-omitted} [διοτι]{.greek-omitted} [εισηκουσθη]{.greek-omitted} [η]{.greek-omitted} [δεησις]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} [σου]{.greek-omitted} [ελισαβετ]{.greek-omitted} [γεννησει]{.greek-omitted} [υιον]{.greek-omitted} [σοι]{.greek-omitted} [και]{.greek-omitted} [καλεσεις]{.greek-omitted} [το]{.greek-omitted} [ονομα]{.greek-omitted} [αυτου]{.greek-omitted} [ιωαννην]{.greek-omitted}[1:13]{.aside}

