---
title: "Collation of Byz^RP^ vs 32351 (2351)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2351 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32351).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2351                                   	| λογος                              	|
| 2351 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2351 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2351               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2351                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2351 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2351                                                     	| [―]{.gap}                        	|
:::

## Revelation

### Chapter 1

αποκαλυψις [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ην εδωκεν αυτω ο [θεος]{.greek-abbr} δειξαι τοις δουλοις αυτου α δει γενεσθαι εν ταχει και εσημανεν αποστειλας δια του αγγελου αυτου τω δουλω αυτου ιωαννη[1:1]{.aside}

[γ]{.greek-added} ος εμαρτυρησεν τον λογον του [θεου]{.greek-abbr} και την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} οσα [ειδεν]{.greek-omitted} [ιδεν]{.greek-added}[1:2]{.aside}

[δ]{.greek-added} μακαριος ο αναγινωσκων και οι ακουοντες τους λογους της προφητειας και τηρουντες τα εν αυτη γεγραμμενα ο γαρ καιρος εγγυς[1:3]{.aside}

ιωαννης ταις επτα εκκλησιαις ταις εν τη ασια χαρις υμιν και ειρηνη απο [θεου]{.greek-abbr} ο ων και ο ην και ο ερχομενος και απο των επτα πνευματων α ενωπιον του [θρονου]{.greek-omitted} [θρωνου]{.greek-added} αυτου[1:4]{.aside}

και απο [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} ο μαρτυς ο πιστος ο πρωτοτοκος των νεκρων και ο αρχων των [βασιλεων]{.greek-omitted} [βασιλειων]{.greek-added} της γης τω αγαπωντι ημας και [λουσαντι]{.greek-omitted} [λυσαντι]{.greek-added} ημας απο των αμαρτιων ημων εν τω αιματι αυτου[1:5]{.aside}

και εποιησεν ημας [βασιλειαν]{.greek-omitted} [βασιλειον]{.greek-added} [ιερεις]{.greek-omitted} [ιερατευμα]{.greek-added} τω [θεω]{.greek-abbr} [ημων]{.greek-added} και [πατρι]{.greek-abbr} αυτου αυτω η δοξα και το κρατος εις τους αιωνας των αιωνων αμην[1:6]{.aside}

ιδου ερχεται μετα των νεφελων και [οψεται]{.greek-omitted} [οψονται]{.greek-added} αυτον πας οφθαλμος και οιτινες αυτον εξεκεντησαν και κοψονται [επ]{.greek-omitted} αυτον πασαι αι φυλαι της γης ναι αμην[1:7]{.aside}

εγω ειμι το [αλφα]{.greek-omitted} [[α]{.greek-abbr}]{.greek-added} και το [ω]{.greek-abbr} [αρχη]{.greek-added} [και]{.greek-added} [τελος]{.greek-added} λεγει [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο ων και ο ην και ο ερχομενος ο παντοκρατωρ[1:8]{.aside}

εγω ιωαννης ο αδελφος υμων και [κοινωνος]{.greek-omitted} [συγκοινωνος]{.greek-added} εν τη θλιψει και βασιλεια και υπομονη εν [χριστω]{.greek-abbr} [ιησου]{.greek-abbr} εγενομην εν τη νησω τη καλουμενη πατμω δια τον λογον του [θεου]{.greek-abbr} και δια την μαρτυριαν [ιησου]{.greek-abbr} [χριστου]{.greek-abbr}[1:9]{.aside}

εγενομην εν [πνευματι]{.greek-abbr} εν τη κυριακη ημερα και ηκουσα φωνην οπισω μου μεγαλην ως σαλπιγγος[1:10]{.aside}

λεγουσης ο [βλεπεις]{.greek-omitted} [βλεπης]{.greek-added} [γραψον]{.greek-omitted} [γραψων]{.greek-added} εις βιβλιον και πεμψον ταις επτα εκκλησιαις εις εφεσον και εις σμυρναν και εις περγαμον και εις [θυατειρα]{.greek-omitted} [θυατειραν]{.greek-added} και εις [σαρδεις]{.greek-omitted} [σαρδις]{.greek-added} και εις φιλαδελφειαν και εις λαοδικειαν[1:11]{.aside}

και εκει επεστρεψα βλεπειν την φωνην ητις ελαλει μετ εμου και επιστρεψας [ειδον]{.greek-omitted} [ιδον]{.greek-added} επτα λυχνιας χρυσας[1:12]{.aside}

και εν [μεσω]{.greek-omitted} [μεσωι]{.greek-added} των επτα λυχνιων ομοιον [υιω]{.greek-abbr} [ανθρωπου]{.greek-abbr} ενδεδυμενον ποδηρη και περιεζωσμενον προς τοις μαστοις ζωνην χρυσην[1:13]{.aside}

η δε κεφαλη αυτου και αι τριχες λευκαι ως [εριον]{.greek-omitted} [ερειον]{.greek-added} λευκον ως χιων και οι οφθαλμοι αυτου ως φλοξ πυρος[1:14]{.aside}

και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκ[ω]{.unclear}λιβανω]{.greek-added} ως εν καμινω πεπυρωμενοι και η φωνη αυτου ως φωνη υδατων πολλων[1:15]{.aside}

και εχων εν τη δεξια αυτου χειρι αστερας επτα [ϛ]{.greek-added} και εκ του στοματος αυτου ρομφαια διστομος [οξεια]{.greek-omitted} [οξια]{.greek-added} εκπορευομενη και η οψις αυτου ως ο ηλιος [φαιννει]{.greek-added} [φαινει]{.corr} εν τη δυναμει αυτου[1:16]{.aside}

και οτε [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτον επεσα προς τους ποδας αυτου ως νεκρος και εθηκεν την δεξιαν αυτου επ εμε λεγων μη φοβου εγω ειμι ο πρωτος και ο εσχατος[1:17]{.aside}

[η]{.greek-added} και ο ζων και εγενομην νεκρος και ιδου ζων ειμι εις τους αιωνας των αιωνων αμην και εχω τας [κλεις]{.greek-omitted} [κλειδας]{.greek-added} του θανατου και του αδου[1:18]{.aside}

γραψον ουν α [ειδες]{.greek-omitted} [ιδες]{.greek-added} και α εισιν και α μελλει γινεσθαι μετα ταυτα[1:19]{.aside}

το μυστηριον των επτα αστερων ων [ειδες]{.greek-omitted} [ιδες]{.greek-added} επι της δεξιας μου και τας επτα λυχνιας τας χρυσας οι επτα αστερες αγγελοι των επτα εκκλησιων εισιν [θ]{.greek-added} και αι [επτα]{.greek-added} λυχνιαι [αι]{.greek-omitted} [επτα]{.greek-omitted} επτα εκκλησιαι εισιν[1:20]{.aside}

### Chapter 2

[τω]{.greek-omitted} [των]{.greek-added} [αγγελω]{.greek-omitted} [αγγελων]{.greek-added} της εν εφεσω εκκλησιας γραψον ταδε λεγει ο κρατων τους επτα αστερας εν τη δεξια αυτου ο περιπατων εν μεσω των επτα λυχνιων των χρυσων[2:1]{.aside}

οιδα τα εργα σου και τον κοπον σου και την υπομονην σου και οτι ου δυνη βαστασαι κακους και επειρασας τους λεγοντας εαυτους αποστολους ειναι και ουκ εισιν και ευρες αυτους ψευδεις[2:2]{.aside}

και υπομονην εχεις και εβαστασας δια το ονομα μου και [ουκ]{.greek-omitted} [ου]{.greek-added} [εκοπιασας]{.greek-omitted} [κεκοπίασας]{.greek-added}[2:3]{.aside}

αλλα εχω κατα σου [ι]{.greek-added} οτι την αγαπην σου την πρωτην αφηκας[2:4]{.aside}

μνημονευε ουν ποθεν πεπτωκας και μετανοησον και τα πρωτα εργα ποιησον ει δε μη ερχομαι σοι ταχυ και [κινησω]{.greek-omitted} [κηνησω]{.greek-added} την λυχνιαν σου εκ του τοπου αυτης εαν μη μετανοησης[2:5]{.aside}

αλλα τουτο εχεις οτι μισεις τα εργα των νικολαιτων α καγω [μισω]{.greek-omitted} [μησω]{.greek-added}[2:6]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω φαγειν εκ του ξυλου της ζωης ο εστιν εν τω παραδεισω του [θεου]{.greek-abbr} μου[2:7]{.aside}

και τω αγγελω της [εσμυρνη]{.greek-added} [εν]{.corr} [σμυρνη]{.corr} εκκλησιας [γραψον]{.greek-omitted} [γραψων]{.greek-added} ταδε λεγει ο πρωτος και ο εσχατος ος εγενετο νεκρος και εζησεν[2:8]{.aside}

οιδα σου τα εργα και την θλιψιν και την πτωχειαν αλλα πλουσιος ει και την [βλασφημιαν]{.greek-omitted} [βλασφημειαν]{.greek-added} [εκ]{.greek-omitted} των [λεγοντων]{.greek-omitted} [λεγωντων]{.greek-added} ιουδαιους ειναι εαυτους και ουκ εισιν αλλα συναγωγη του σατανα[2:9]{.aside}

μηδεν φοβου α μελλεις παθειν ιδου δη μελλει [βαλειν]{.greek-omitted} [λαβειν]{.greek-added} ο διαβολος εξ υμων εις φυλακην ινα πειρασθητε και εξετε θλιψιν [ημερων]{.greek-omitted} [ημερας]{.greek-added} δεκα γινου πιστος αχρι θανατου και δωσω σοι τον στεφανον της ζωης[2:10]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις ο [νικων]{.greek-omitted} [νηκων]{.greek-added} ου μη αδικηθη εκ του θανατου του δευτερου[2:11]{.aside}

και τω αγγελω της εν περγαμω εκκλησιας [γραψον]{.greek-omitted} [γραψων]{.greek-added} ταδε λεγει ο εχων την ρομφαιαν την διστομον την οξειαν[2:12]{.aside}

οιδα τα εργα σου και που κατοικεις οπου ο θρονος του σατανα και κρατεις το ονομα μου και ουκ ηρνησω την πιστιν μου εν ταις ημεραις [εν]{.greek-omitted} αις [αντιπας]{.greek-omitted} [αντειπας]{.greek-added} ο μαρτυς μου ο πιστος [μου]{.greek-added} ος απεκτανθη παρ υμιν οπου ο σατανας κατοικει[2:13]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου ολιγα οτι εχεις εκει κρατουντας την διδαχην βαλααμ ος εδιδαξεν τον βαλακ [βαλειν]{.greek-omitted} [βαλιν]{.greek-added} σκανδαλον ενωπιον των υιων [ισραηλ]{.greek-abbr} και φαγειν ειδωλοθυτα και πορνευσαι[2:14]{.aside}

ουτως εχεις και συ κρατουντας την διδαχην των νικολαιτων ομοιως[2:15]{.aside}

μετανοησον [ουν]{.greek-omitted} ει δε μη ερχομαι σοι ταχυ και πολεμησω μετ αυτων εν τη ρομφαια του στοματος μου[2:16]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις τω νικωντι δωσω αυτω [φαγειν]{.greek-added} του μαννα του κεκρυμμενου και δωσω αυτω ψηφον λευκην και επι την ψηφον ονομα καινον γεγραμμενον ο ουδεις οιδεν ει μη ο λαμβανων[2:17]{.aside}

και τω αγγελω της εν [θυατειροις]{.greek-omitted} [θυατηρη]{.greek-added} εκκλησιας γραψον ταδε λεγει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr} ο εχων τους οφθαλμους αυτου ως φλογα πυρος και οι ποδες αυτου ομοιοι [χαλκολιβανω]{.greek-omitted} [χαλκωλιβανω]{.greek-added}[2:18]{.aside}

οιδα σου τα εργα και την αγαπην και την [πιστιν]{.greek-omitted} [πιστην]{.greek-added} και την διακονιαν και την υπομονην σου και τα εργα σου τα εσχατα πλειονα των πρωτων[2:19]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} εχω κατα σου οτι αφεις την [γυναικα]{.greek-omitted} [γυνεκα]{.greek-added} σου ιεζαβελ η λεγει εαυτην [προφητιν]{.greek-omitted} [προφητην]{.greek-added} και διδασκει και πλανα τους εμους δουλους πορνευσαι και φαγειν [ειδωλοθυτα]{.greek-omitted} [ειδολωθυτα]{.greek-added}[2:20]{.aside}

[ιζ]{.greek-added} και εδωκα [αυτη]{.greek-omitted} [αυτην]{.greek-added} χρονον ινα μετανοηση και ου [θελει]{.greek-omitted} [θελη]{.greek-added} μετανοησαι εκ της πορνειας αυτης[2:21]{.aside}

ιδου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} αυτην εις κλινην και τους [μοιχευοντας]{.greek-omitted} [μυχευοντας]{.greek-added} μετ αυτης εις θλιψιν [μεγαλην]{.greek-omitted} [μεγαλιν]{.greek-added} εαν μη μετανοησωσιν εκ των εργων αυτης[2:22]{.aside}

και τα τεκνα αυτης αποκτενω εν θανατω και γνωσονται πασαι αι εκκλησιαι οτι εγω ειμι ο ερευνων νεφρους και καρδιας και δωσω υμιν εκαστω κατα τα εργα υμων[2:23]{.aside}

υμιν δε λεγω τοις λοιποις τοις εν [θυατειροις]{.greek-omitted} [θυατιροις]{.greek-added} οσοι ουκ εχουσιν την διδαχην ταυτην οιτινες ουκ εγνωσαν τα [βαθεα]{.greek-omitted} [βαθέα]{.greek-added} του σατανα ως λεγουσιν ου [βαλλω]{.greek-omitted} [βαλω]{.greek-added} εφ υμας αλλο βαρος[2:24]{.aside}

πλην ο εχετε κρατησατε αχρι ου αν ηξω[2:25]{.aside}

και ο νικων και ο τηρων [αχρι]{.greek-omitted} [αχρη]{.greek-added} τελους τα εργα μου δωσω αυτω εξουσιαν επι των εθνων[2:26]{.aside}

και ποιμανει αυτους εν ραβδω σιδηρα ως τα σκευη τα [κεραμικα]{.greek-omitted} [κεραμηκα]{.greek-added} συντριβησεται [ως]{.greek-omitted} [καγω]{.greek-omitted} [ειληφα]{.greek-omitted} [παρα]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [μου]{.greek-omitted}[2:27]{.aside}

[ως]{.greek-added} [καγω]{.greek-added} [ειληφα]{.greek-added} [παρα]{.greek-added} [του]{.greek-added} [[πατρος]{.greek-abbr}]{.greek-added} [μου]{.greek-added} και δωσω αυτω τον αστερα τον πρωινον[2:28]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[2:29]{.aside}

### Chapter 3

και τω αγγελω της εν σαρδεσιν εκκλησιας [[ιθ]{.greek-abbr}]{.greek-added} γραψον ταδε λεγει ο εχων τα επτα [πνευματα]{.greek-abbr} του [θεου]{.greek-abbr} και τους επτα αστερας οιδα σου τα εργα οτι ονομα εχεις οτι ζης και νεκρος [ει]{.greek-omitted}[3:1]{.aside}

[γινου]{.greek-omitted} [εγηνου]{.greek-added} [γρηγορων]{.greek-omitted} [γρηγορον]{.greek-added} και στηρισον τα λοιπα α [εμελλες]{.greek-omitted} [αποβαλλειν]{.greek-omitted} [ημελλον]{.greek-added} [αποθανειν]{.greek-added} ου γαρ ευρηκα σου τα εργα πεπληρωμενα ενωπιον του [θεου]{.greek-abbr} μου[3:2]{.aside}

μνημονευε ουν πως ειληφας και ηκουσας και τηρει και μετανοησον εαν ουν μη γρηγορησης ηξω [επι]{.greek-omitted} [σε]{.greek-omitted} ως κλεπτης και ου μη [γνως]{.greek-omitted} [γνωση]{.greek-added} ποιαν ωραν ηξω επι σε[3:3]{.aside}

[αλλ]{.greek-omitted} [αλλα]{.greek-added} [εχεις]{.greek-added} ολιγα [εχεις]{.greek-omitted} ονοματα εν σαρδεσιν α ουκ εμολυναν τα ιματια αυτων και περιπατησουσιν μετ εμου εν λευκοις οτι αξιοι εισιν[3:4]{.aside}

ο νικων [ουτος]{.greek-omitted} [ουτως]{.greek-added} περιβαλειται εν ιματιοις λευκοις και ου μη εξαλειψω το ονομα αυτου εκ της βιβλου της ζωης και ομολογησω το ονομα αυτου ενωπιον του [πατρος]{.greek-abbr} μου και ενωπιον των αγγελων αυτου[3:5]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:6]{.aside}

και τω αγγελω της εν [φιλαδελφεια]{.greek-omitted} [φιλαδελφια]{.greek-added} εκκλησιας γραψον ταδε λεγει ο [αγγε(λ)ος]{.greek-added} [αγιος]{.greek-omitted} [ο]{.greek-omitted} αληθινος ο εχων την κλειν [του]{.greek-omitted} [δαυιδ]{.greek-abbr} ο ανοιγων και ουδεις κλεισει αυτην [και]{.greek-added} [κλειων]{.greek-added} [και]{.greek-added} [ουδεις]{.greek-added} [ανοιγη]{.greek-added} ει μη ο ανοιγων και ουδεις ανοιξει[3:7]{.aside}

οιδα σου τα εργα ιδου δεδωκα ενωπιον σου θυραν ανεωγμενην ην ουδεις δυναται κλεισαι αυτην οτι μικραν εχεις [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} και ετηρησας μου τον λογον και ουκ ηρνησω το ονομα μου[3:8]{.aside}

ιδου διδωμι εκ της συναγωγης του σατανα των λεγοντων εαυτους ιουδαιους ειναι και ουκ εισιν αλλα ψευδονται ιδου ποιησω αυτους ινα [ηξωσιν]{.greek-omitted} [ηξωσι]{.greek-added} και προσκυνησωσιν [ενωπιων]{.greek-added} [ενωπιον]{.corr} των ποδων σου και [γνωσιν]{.greek-omitted} [γνωσει]{.greek-added} οτι ηγαπησα σε[3:9]{.aside}

οτι ετηρησας τον λογον της υπομονης μου καγω σε τηρησω εκ της ωρας του πειρασμου της μελλουσης ερχεσθαι επι της οικουμενης ολης πειρασαι τους κατοικουντας [επι]{.greek-omitted} [επη]{.greek-added} της γης[3:10]{.aside}

ερχομαι ταχυ κρατει ο εχεις ινα μηδεις λαβη τον στεφανον σου[3:11]{.aside}

[[κα]{.greek-abbr}]{.greek-added} ο νικων ποιησω [αυτον]{.greek-omitted} [αυτω]{.greek-added} στυλον εν τω ναω του [θεου]{.greek-abbr} μου και εξω ου μη εξελθη ετι και γραψω επ αυτον το ονομα του θεου μου και το ονομα της [πολεως]{.greek-omitted} [πολεος]{.greek-added} του θεου μου της καινης [ιερουσαλημ]{.greek-abbr} η [καταβαινει]{.greek-omitted} [καταβαινη]{.greek-added} εκ του ουρανου απο του [θεου]{.greek-abbr} μου και το ονομα μου το καινον[3:12]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:13]{.aside}

και τω αγγελω της εν [λαοδικεια]{.greek-omitted} [λαωδικεια]{.greek-added} [εκκλησιας]{.greek-omitted} [εκκλησιαις]{.greek-added} γραψον ταδε λεγει ο αμην ο μαρτυς ο πιστος [και]{.greek-omitted} [ο]{.greek-added} [α]{.greek-added} [αληθινος]{.greek-omitted} [ληθινος]{.greek-added} η αρχη της [κτισεως]{.greek-omitted} [κτησεως]{.greek-added} του [θεου]{.greek-abbr}[3:14]{.aside}

οιδα σου τα εργα οτι ουτε ψυχρος ει ουτε [[κγ]{.greek-abbr}]{.greek-added} ζεστος οφελον ψυχρος ης η ζεστος[3:15]{.aside}

ουτως οτι χλιαρος ει και ου ζεστος ουτε ψυχρος μελλω σε εμεσαι εκ του στοματος μου[3:16]{.aside}

οτι λεγεις πλουσιος ειμι και [πεπλουτηκα]{.greek-omitted} [πεπλουτικα]{.greek-added} και ουδενος χρειαν εχω και ουκ οιδας οτι συ ει ο [ταλαιπωρος]{.greek-omitted} [ταλαιπορος]{.greek-added} και ο ελεεινος και πτωχος και τυφλος και γυμνος[3:17]{.aside}

[συμβουλευω]{.greek-omitted} [συμβουλευο]{.greek-added} σοι αγορασαι [χρυσιον]{.greek-omitted} παρ εμου [χρυσιον]{.greek-added} πεπυρωμενον εκ πυρος ινα πλουτησης και ιματια λευκα ινα περιβαλη και μη [φανερωθη]{.greek-omitted} [φανει]{.greek-added} η αισχυνη της [γυμνοτητος]{.greek-omitted} [γυμνωτητος]{.greek-added} σου και [κολλυριον]{.greek-omitted} [κολλουριον]{.greek-added} ινα εγχριση τους οφθαλμους σου ινα βλεπης[3:18]{.aside}

εγω οσους εαν φιλω ελεγχω και παιδευω [ζηλωσον]{.greek-omitted} [ζηλευε]{.greek-added} ουν και μετανοησον[3:19]{.aside}

ιδου εστηκα επι την θυραν και κρουω εαν τις ακουση της φωνης μου και ανοιξη την θυραν και εισελευσομαι προς αυτον και δειπνησω μετ αυτου και αυτος μετ εμου[3:20]{.aside}

[[κδ]{.greek-abbr}]{.greek-added} ο νικων δωσω αυτω [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} μετ εμου εν τω θρονω μου ως καγω ενικησα και [εκαθισα]{.greek-omitted} [εκαθησα]{.greek-added} μετα του [πατρος]{.greek-abbr} μου εν τω θρονω αυτου[3:21]{.aside}

ο εχων ους ακουσατω τι το [πνευμα]{.greek-abbr} λεγει ταις εκκλησιαις[3:22]{.aside}

### Chapter 4

μετα ταυτα ειδον και ιδου θυρα ανεωγμενη εν τω [ουρανω]{.greek-abbr} και η φωνη η πρωτη ην ηκουσα ως σαλπιγγος λαλουσης μετ εμου λεγων αναβα ωδε και δειξω σοι α δει γενεσθαι μετα ταυτα[4:1]{.aside}

[και]{.greek-omitted} ευθεως εγενομην εν [πνευματι]{.greek-abbr} και ιδου θρονος εκειτο εν τω [ουρανω]{.greek-abbr} και επι τον θρονον καθημενος[4:2]{.aside}

[και]{.greek-added} [ο]{.greek-added} [καθημενος]{.greek-added} ομοιος ορασει λιθω ιασπιδι και σαρδιω και [ιρις]{.greek-omitted} [ϊρις]{.greek-added} [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} του θρονου [[ομ]{.unclear}οιως]{.corr} [[ως]{.corr}]{.greek-added} [ορασις]{.greek-omitted} [[ορα[σει]{.unclear}ς]{.corr}]{.greek-added} [σμαραγδινων]{.greek-omitted} [[σμαραγδηνω]{.corr}]{.greek-added}[4:3]{.aside}

[και]{.greek-omitted} [[θρονου]{.corr}]{.greek-added} [κυκλοθεν]{.greek-omitted} [[κυ[κλω]{.unclear}θεν]{.corr}]{.greek-added} [του]{.corr} [θρονου]{.corr} θρονοι εικοσι τεσσαρες και επι τους θρονους τους εικοσι [τεσσαρας]{.greek-omitted} [τεσσαρες]{.greek-added} πρεσβυτερους καθημενους περιβεβλημενους εν ιματιοις λευκοις και επι τας κεφαλας αυτων στεφανους χρυσους[4:4]{.aside}

και εκ του θρονου εκπορευονται αστραπαι και φωναι και βρονται και επτα λαμπαδες πυρος καιομεναι ενωπιον του θρονου αυτου [αι]{.greek-omitted} [και]{.greek-added} [εισιν]{.greek-omitted} [τα]{.greek-added} επτα πνευματα του [θεου]{.greek-abbr}[4:5]{.aside}

και ενωπιον του θρονου ως θαλασσα υαλινη ομοια κρυσταλλω και εν μεσω του θρονου και κυκλω του θρονου τεσσαρα ζωα [γεμοντα]{.greek-omitted} [γεμωντα]{.greek-added} οφθαλμων εμπροσθεν και [οπισθεν]{.greek-omitted} [οπιθεν]{.greek-added}[4:6]{.aside}

και το ζωον το πρωτον ομοιον [λεοντι]{.greek-omitted} [λεωντι]{.greek-added} και το δευτερον ζωον ομοιον μοσχω και το τριτον ζωον [εχον]{.greek-omitted} [εχων]{.greek-added} προσωπον [ανθρωπου]{.greek-abbr} και το τεταρτον ζωον ομοιον αετω πετομενω[4:7]{.aside}

και τα τεσσαρα ζωα εν καθ εν [εχον]{.greek-omitted} [εχοντα]{.greek-added} ανα [πτε]{.greek-added} [πτερυγας]{.greek-omitted} [ρυγας]{.greek-added} εξ [κυκλοθεν]{.greek-omitted} [κυκλωθεν]{.greek-added} [εσωθεν]{.greek-added} και [εσωθεν]{.greek-omitted} [εξοθεν]{.greek-added} γεμουσιν οφθαλμων και αναπαυσιν ουκ εχουσιν ημερας και νυκτος λεγοντες αγιος αγιος αγιος [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ο [παντοκρατωρ]{.greek-omitted} [παντωκρατορ]{.greek-added} ο ην και ο ων και ο ερχομενος[4:8]{.aside}

και οταν [δωσιν]{.greek-omitted} [δωσωσιν]{.greek-added} τα ζωα δοξαν και τιμην και [ευχαριστιαν]{.greek-omitted} [ευχαριστειαν]{.greek-added} τω [καθημενω]{.greek-omitted} [καθειμενω]{.greek-added} επι του θρονου τω ζωντι εις τους αιωνας των αιωνων [αμην]{.greek-added}[4:9]{.aside}

πεσουνται οι εικοσι [τεσαρες]{.greek-added} [τεσσαρες]{.corr} πρεσβυτεροι ενωπιον του καθημενου επι του θρονου και προσκυνησουσιν τω ζωντι εις τους αιωνας των αιωνων και [βαλουσιν]{.greek-omitted} [βάλουσι]{.greek-added} τους στεφανους αυτων ενωπιον του θρονου λεγοντες[4:10]{.aside}

αξιος ει ο [κυριος]{.greek-abbr} και ο [θεος]{.greek-abbr} ημων ο αγιος λαβειν την δοξαν και την τιμην και την [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} οτι συ [εκτισας]{.greek-omitted} [εκτησας]{.greek-added} παντα και δια το θελημα σου ησαν και εκτισθησαν[4:11]{.aside}

### Chapter 5

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} επι την δεξιαν [και]{.greek-added} [εν]{.greek-added} [μεσω]{.greek-added} του καθημενου επι του θρονου βιβλιον γεγραμμενον εσωθεν και [εξωθεν]{.greek-omitted} [εξθεν]{.greek-added} κατεσφραγισμενον [σφραγισιν]{.greek-omitted} [σφραγησιν]{.greek-added} επτα[5:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} [αγγελον]{.greek-added} αγγελον ισχυρον κηρυσσοντα εν φωνη μεγαλη τις αξιος [εστιν]{.greek-omitted} ανοιξαι το βιβλιον και λυσαι τας [σφραγιδας]{.greek-omitted} [σφραγηδας]{.greek-added} αυτου[5:2]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εν τω [ουρανω]{.greek-abbr} ανω ουτε επι της γης ουτε υποκατω της γης ανοιξαι το βιβλιον ουτε βλεπειν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[5:3]{.aside}

και εγω [εκλαιον]{.greek-omitted} [εκλεον]{.greek-added} πολυ οτι ουδεις αξιος ευρεθη ανοιξαι το βιβλιον ουτε βλεπειν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[5:4]{.aside}

και εις εκ των πρεσβυτερων λεγει μοι μη κλαιε ιδου ενικησεν ο λεων ο εκ της φυλης ιουδα η ριζα [δαυιδ]{.greek-abbr} ο ανοιγων το βιβλιον [[κζ]{.greek-abbr}]{.greek-added} και τας επτα [σφραγιδας]{.greek-omitted} [σφραγηδας]{.greek-added} αυτου[5:5]{.aside}

[[κη]{.greek-abbr}]{.greek-added} και [ειδον]{.greek-omitted} [ιδον]{.greek-added} εν μεσω του θρονου και των [τεσ]{.greek-added} [τεσσαρων]{.greek-omitted} [σαρων]{.greek-added} ζωων και εν μεσω των πρεσβυτερων αρνιον εστηκος ως εσφαγμενον [εχον]{.greek-omitted} [εχων]{.greek-added} κερατα επτα και οφθαλμους επτα α εισιν τα επτα πνευματα του [θεου]{.greek-abbr} αποστελλομενα εις πασαν την γην[5:6]{.aside}

και ηλθεν και ειληφεν εκ της δεξιας του καθημενου επι του θρονου[5:7]{.aside}

και οτε [[κη]{.greek-abbr}]{.greek-added} ελαβεν το βιβλιον τα τεσσαρα ζωα και οι εικοσι τεσσαρες πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} ενωπιον του αρνιου εχοντες εκαστος [κιθαραν]{.greek-omitted} [κηθαραν]{.greek-added} και φιαλας χρυσας γεμουσας θυμιαματων αι εισιν [προσευχαι]{.greek-omitted} [προσευχαιων]{.greek-added} των αγιων[5:8]{.aside}

και αδουσιν ωδην καινην λεγοντες αξιος ει λαβειν το βιβλιον και ανοιξαι τας σφραγιδας αυτου οτι εσφαγης και ηγορασας τω [θεω]{.greek-abbr} ημας εν τω αιματι σου εκ πασης φυλης και γλωσσης και λαου και εθνους[5:9]{.aside}

και εποιησας αυτους τω [θεω]{.greek-abbr} ημων βασιλεις και ιερεις και βασιλευσουσιν επι της γης[5:10]{.aside}

και [ειδον]{.greek-omitted} [ιδων]{.greek-added} και ηκουσα [ως]{.greek-omitted} φωνην αγγελων πολλων κυκλω του θρονου και των ζωων και των πρεσβυτερων και ην ο αριθμος αυτων μυριαδες μυριαδων και χιλιαδες χιλιαδων[5:11]{.aside}

λεγοντες φωνη μεγαλη αξιον εστιν το αρνιον το εσφαγμενον λαβειν την [δυναμιν]{.greek-omitted} [δυναμην]{.greek-added} και τον πλουτον και σοφιαν και ισχυν και τιμην και δοξαν και ευλογιαν[5:12]{.aside}

και παν κτισμα ο εν τω [ουρανω]{.greek-abbr} και επι της γης και υποκατω της γης και επι της θαλασσης [οσα]{.greek-added} εστιν και τα εν αυτοις παντας ηκουσα λεγοντας τω καθημενω επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} και τω αρνιω η ευλογια και η τιμη και η δοξα και το κρατος εις τους αιωνας των αιωνων [αμην]{.greek-omitted}[5:13]{.aside}

και τα τεσσαρα ζωα [λεγοντα]{.greek-omitted} [ελεγον]{.greek-added} [το]{.greek-omitted} αμην και οι πρεσβυτεροι [επεσον]{.greek-omitted} [επεσαν]{.greek-added} και προσεκυνησαν[5:14]{.aside}

### Chapter 6

και [ειδον]{.greek-omitted} [ιδ[ω]{.unclear}ν]{.greek-added} οτι ηνοιξεν το αρνιον μιαν εκ των επτα σφραγιδων και ηκουσα ενος εκ των τεσσαρων ζωων λεγοντος ως [φωνη]{.greek-omitted} [φωνή]{.greek-added} βροντης ερχου και [ιδε]{.greek-omitted} [ειδον]{.greek-added} [α]{.greek-added}[6:1]{.aside}

και ιδου ιππος λευκος και ο καθημενος επ αυτον εχων τοξον και εδοθη αυτω στεφανος και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} νικων και ινα νικηση[6:2]{.aside}

[[β]{.greek-abbr}]{.greek-added} και οτε ηνοιξεν την δευτεραν σφραγιδα ηκουσα του δευτερου ζωου λεγοντος ερχου[6:3]{.aside}

και εξηλθεν αλλος ιππος πυρος και τω καθημενω επ αυτον εδοθη αυτω λαβειν την ειρηνην εκ της γης ινα αλληλους [σφαξωσιν]{.greek-omitted} [σφαξωσι]{.greek-added} και εδοθη αυτω μαχαιρα μεγαλη [[γ]{.greek-abbr}]{.greek-added}[6:4]{.aside}

και οτε ηνοιξεν την σφραγιδα την τριτην ηκουσα του τριτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted} και ιδου ιππος μελας και ο καθημενος επ αυτον εχων ζυγον εν τη χειρι αυτου[6:5]{.aside}

και ηκουσα [ως]{.greek-added} φωνην εν μεσω των τεσσαρων ζωων λεγουσαν χοινιξ σιτου δηναριου και τρεις χοινικες [κριθης]{.greek-omitted} [κριθεις]{.greek-added} δηναριου και το ελαιον και τον οινον μη αδικησης [[δ]{.greek-abbr}]{.greek-added}[6:6]{.aside}

και οτε ηνοιξεν την [σφραγιδα]{.greek-omitted} [σφαγιδα]{.greek-added} την τεταρτην ηκουσα του τεταρτου ζωου λεγοντος ερχου [και]{.greek-omitted} [ιδε]{.greek-omitted}[6:7]{.aside}

και ιδου ιππος χλωρος και ο καθημενος επανω αυτου ονομα αυτω ο θανατος και ο αδης ηκολουθει αυτω και εδοθη αυτω εξουσια επι το τεταρτον της γης αποκτειναι εν ρομφαια και εν λιμω και εν θανατω και υπο των θηριων της γης[6:8]{.aside}

και οτε ηνοιξεν την πεμπτην σφραγιδα [ειδον]{.greek-omitted} [ιδον]{.greek-added} υποκατω του θυσιαστηριου τας ψυχας των [εσφαγμενων]{.greek-omitted} [εσφραγισμενων]{.greek-added} δια [τον]{.greek-omitted} [των]{.greek-added} [λογον]{.greek-omitted} [λογων]{.greek-added} του [θεου]{.greek-abbr} και δια την μαρτυριαν του αρνιου ην ειχον[6:9]{.aside}

και [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} φωνη μεγαλη λεγοντες εως ποτε ο δεσποτης ο αγιος και αληθινος ου κρινεις και [εδικεις]{.greek-added} [εκδικεις]{.corr} το αιμα ημων εκ των κατοικουντων επι της γης[6:10]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτοις [εκαστω]{.greek-omitted} στολη λευκη και ερρεθη αυτοις [ινα]{.greek-omitted} [αναπαυσωνται]{.greek-omitted} [αναπαυσασθαι]{.greek-added} [μικρον]{.greek-added} [ετι]{.greek-omitted} [χρονον]{.greek-omitted} εως πληρωσωσιν και οι συνδουλοι αυτων και οι αδελφοι αυτων και οι μελλοντες αποκτενεσθαι ως και αυτοι[6:11]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} οτε ηνοιξεν την σφραγιδα την εκτην και σεισμος μεγας εγενετο και ο ηλιος [εγενετο]{.greek-added} μελας [εγενετο]{.greek-omitted} ως σακκος τριχινος και η σεληνη ολη εγενετο ως αιμα[6:12]{.aside}

και οι αστερες του ουρανου [επεσον]{.greek-omitted} [επεσαν]{.greek-added} εις την γην ως συκη [βαλουσα]{.greek-omitted} [βαλλουσα]{.greek-added} τους ολυνθους αυτης υπο ανεμου μεγαλου σειομενη[6:13]{.aside}

και ο ουρανος απεχωρισθη ως βιβλιον ελισσομενον και παν ορος και νησος εκ των τοπων αυτων [εκινηθησαν]{.greek-omitted} [εκεινηθησαν]{.greek-added}[6:14]{.aside}

και οι βασιλεις της γης και οι μεγιστανες και οι χιλιαρχοι και οι πλουσιοι και οι ισχυροι και πας δουλος και ελευθερος εκρυψαν εαυτους εις τα σπηλαια και εις τας πετρας των ορεων[6:15]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} τοις [ορεσιν]{.greek-omitted} [ορεσι]{.greek-added} και ταις πετραις [πεσετε]{.greek-omitted} [πεσατε]{.greek-added} εφ ημας και κρυψατε ημας απο προσωπου του καθημενου επι [του]{.greek-omitted} [θρονου]{.greek-omitted} [τω]{.greek-added} [θρονω]{.greek-added} και απο της οργης του αρνιου[6:16]{.aside}

[οτι]{.greek-omitted} ηλθεν η ημερα η μεγαλη της οργης αυτου και τις δυναται σταθηναι[6:17]{.aside}

### Chapter 7

[και]{.greek-omitted} μετα τουτο [ειδον]{.greek-omitted} [ιδον]{.greek-added} [τεσσαρας]{.greek-omitted} [τεσσα]{.greek-added} [ρας]{.greek-added} αγγελους εστωτας επι τας τεσσαρας [γωνιας]{.greek-omitted} [γονιας]{.greek-added} της γης κρατουντας τους τεσσαρας ανεμους της γης ινα μη [πνεη]{.greek-omitted} [πνεει]{.greek-added} [ο]{.greek-added} ανεμος επι της γης μητε επι της θαλασσης μητε επι τι δενδρον[7:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλον αγγελον [αναβαινοντα]{.greek-omitted} [αναβενοντα]{.greek-added} απο ανατολης ηλιου εχοντα [σφραγιδα]{.greek-omitted} [σφραγηδα]{.greek-added} [θεου]{.greek-abbr} ζωντος και εκραξεν φωνη μεγαλη τοις [τεσαρσιν]{.greek-added} [τεσσαρσιν]{.corr} αγγελοις οις [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυτοις αδικησαι την γην και την θαλασσαν[7:2]{.aside}

λεγων μη αδικησητε την γην [μητε]{.greek-omitted} [και]{.greek-added} την θαλασσαν μητε τα δενδρα [αχρι]{.greek-omitted} [αχρις]{.greek-added} ου σφραγισωμεν τους δουλους του [θεου]{.greek-abbr} ημων επι των [μετωπων]{.greek-omitted} [μετοπων]{.greek-added} αυτων[7:3]{.aside}

και ηκουσα [[λα]{.greek-abbr}]{.greek-added} τον αριθμον των εσφραγισμενων [σαραντα]{.greek-added} [εκατον]{.greek-omitted} [και]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} τεσσαρες χιλιαδες εσφραγισμενων εκ πασης φυλης υιων [ισραηλ]{.greek-abbr}[7:4]{.aside}

εκ φυλης ιουδα [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφραγισμενοι]{.greek-added} εκ φυλης [ρουβιμ]{.greek-omitted} [δωδεκα]{.greek-omitted} [ρουβην]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης γαδ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:5]{.aside}

εκ φυλης [ασηρ]{.greek-omitted} [δωδεκα]{.greek-omitted} [νεφθαλειμ]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [νεφθαλειμ]{.greek-omitted} [δωδεκα]{.greek-omitted} [μαναση]{.greek-added} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εκ]{.greek-omitted} [φυλης]{.greek-omitted} [μανασση]{.greek-omitted} [δωδεκα]{.greek-omitted} [χιλιαδες]{.greek-omitted}[7:6]{.aside}

εκ φυλης συμεων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης λευι [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ισαχαρ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες[7:7]{.aside}

εκ φυλης ζαβουλων [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης ιωσηφ [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες εκ φυλης [βενιαμιν]{.greek-omitted} [βενιαμειν]{.greek-added} [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} χιλιαδες [εσφραγισμεναι]{.greek-omitted} [εσφ]{.greek-added}[7:8]{.aside}

[μ]{.greek-added} [μετα]{.greek-omitted} [ετα]{.greek-added} ταυτα [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ιδου οχλος πολυς ον αριθμησαι [αυτον]{.greek-added} ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} εκ παντος εθνους και φυλων και λαων και γλωσσων εστωτας ενωπιον του θρονου και ενωπιον του [αρ]{.greek-added} [αρνιου]{.greek-omitted} [νιου]{.greek-added} [[λγ]{.greek-abbr}]{.greek-added} [περιβεβλημενους]{.greek-omitted} [περιβεβλημενοι]{.greek-added} στολας λευκας και [φοινικας]{.greek-omitted} [φυνικας]{.greek-added} εν ταις χερσιν αυτων[7:9]{.aside}

και [κραζουσιν]{.greek-omitted} [κραζουσι]{.greek-added} φωνη μεγαλη λεγοντες η [σωτηρια]{.greek-abbr} τω [θεω]{.greek-abbr} ημων τω καθημενω επι τω θρονω και τω αρνιω[7:10]{.aside}

και παντες οι αγγελοι [ειστηκεισαν]{.greek-omitted} [ιστεικησαν]{.greek-added} κυκλω του θρονου και των πρεσβυτερων και των τεσσαρων ζωων και [επεσον]{.greek-omitted} [επεσαν]{.greek-added} [ενωπιον]{.greek-omitted} [ενοπιον]{.greek-added} του θρονου επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[7:11]{.aside}

λεγοντες αμην η ευλογια και η δοξα και η σοφια και η [ευχαριστια]{.greek-omitted} [ευχαριστεια]{.greek-added} και η τιμη και η δυναμις και η ισχυς τω [θεω]{.greek-abbr} ημων εις τους αιωνας των αιωνων αμην[7:12]{.aside}

και απεκριθη εις εκ των πρεσβυτερων λεγων μοι ουτοι οι περιβεβλημενοι τας στολας τας λευκας τινες εισιν και ποθεν ηλθον[7:13]{.aside}

και [ειπον]{.greek-omitted} [ειρηκα]{.greek-added} αυτω [κυριε]{.greek-abbr} μου συ οιδας και ειπεν μοι ουτοι εισιν οι ερχομενοι εκ της [θλιψεως]{.greek-omitted} [θληψεως]{.greek-added} της μεγαλης και επλυναν τας στολας αυτων και ελευκαναν εν τω αιματι του αρνιου[7:14]{.aside}

δια τουτο εισιν ενωπιον του θρονου του [θεου]{.greek-abbr} και λατρευουσιν αυτω ημερας και νυκτος εν τω ναω αυτου και ο καθημενος επι τω θρονω σκηνωσει επ αυτους[7:15]{.aside}

ου [πι]{.greek-added} [πεινασουσιν]{.greek-omitted} [νασουσι]{.greek-added} ετι ουδε [μη]{.greek-added} διψησουσιν ετι ουδ ου μη πεση επ αυτους ο ηλιος ουδε παν καυμα[7:16]{.aside}

οτι το αρνιον το ανα μεσον του θρονου [ποιμαινει]{.greek-omitted} [ποιμενει]{.greek-added} αυτους και [οδηγει]{.greek-omitted} [οδηγη]{.greek-added} αυτους επι ζωης πηγας υδατων και [εξαλειψει]{.greek-omitted} [εξαληψη]{.greek-added} ο [θεος]{.greek-abbr} παν δακρυον [εκ]{.greek-omitted} [απο]{.greek-added} των οφθαλμων αυτων[7:17]{.aside}

### Chapter 8

και οτε ηνοιξεν την [σφραγιδα]{.greek-omitted} [σφραγηδα]{.greek-added} την εβδομην εγενετο [σιγη]{.greek-omitted} [σηγη]{.greek-added} εν τω [ουρανω]{.greek-abbr} ως ημιωριον[8:1]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} τους επτα αγγελους οι ενωπιον του [θεου]{.greek-abbr} εστηκασιν και εδοθησαν αυτοις επτα σαλπιγγες[8:2]{.aside}

και αλλος αγγελος [ηλθεν]{.greek-omitted} [εξηλθεν]{.greek-added} και εσταθη επι του θυσιαστηριου εχων [λιβανωτον]{.greek-omitted} [λιβανοτον]{.greek-added} χρυσουν και εδοθη αυτω θυμιαματα πολλα ινα [δωση]{.greek-omitted} [δοση]{.greek-added} ταις προσευχαις [παντων]{.greek-added} των αγιων [παντων]{.greek-omitted} επι το θυσιαστηριον το χρυσουν το ενωπιον του θρονου[8:3]{.aside}

και ανεβη ο καπνος των θυμιαματων ταις προσευχαις των αγιων εκ χειρος του αγγελου ενωπιον του [θεου]{.greek-abbr}[8:4]{.aside}

και ειληφεν ο αγγελος τον λιβανωτον και [εγεμισεν]{.greek-omitted} [εγεμησεν]{.greek-added} αυτον εκ του πυρος του θυσιαστηριου και εβαλεν εις την γην και εγενοντο βρονται και φωναι και αστραπαι και [σεισμος]{.greek-omitted} [σεισμοι]{.greek-added}[8:5]{.aside}

και οι επτα αγγελοι [οι]{.greek-omitted} εχοντες τας επτα σαλπιγγας ητοιμασαν [εαυτους]{.greek-omitted} [αυτους]{.greek-added} ινα [σαλπισωσιν]{.greek-omitted} [σαλπησωσιν]{.greek-added}[8:6]{.aside}

και ο πρωτος [εσαλπισεν]{.greek-omitted} [εσαλπησεν]{.greek-added} και εγενετο χαλαζα και πυρ μεμιγμενα εν αιματι και εβληθη εις την γην και το τριτον της γης [κατεκαη]{.greek-omitted} [κατεκαει]{.greek-added} και το τριτον των δενδρων [κατεκαη]{.greek-omitted} [κατεκαει]{.greek-added} και πας χορτος [χλωρος]{.greek-omitted} [χλορος]{.greek-added} [κατεκαη]{.greek-omitted} [κατεκαει]{.greek-added}[8:7]{.aside}

και ο δευτερος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπησεν]{.greek-added} και ως ορος μεγα [πυρι]{.greek-added} καιομενον εβληθη εις την θαλασσαν και εγενετο το τριτον της θαλασσης αιμα[8:8]{.aside}

και απεθανεν το τριτον των κτισματων [των]{.greek-added} εν τη θαλασση τα εχοντα ψυχας και το τριτον των [πλοιων]{.greek-omitted} [πλυων]{.greek-added} [διεφθαρη]{.greek-omitted} [διεφθαρει]{.greek-added}[8:9]{.aside}

και ο τριτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπησεν]{.greek-added} και επεσεν εκ του ουρανου αστηρ μεγας καιομενος ως λαμπας και επεσεν επι το τριτον των ποταμων και επι τας πηγας των υδατων[8:10]{.aside}

και το ονομα του αστερος λεγεται ο αψινθος και εγενετο το τριτον των υδατων [εις]{.greek-omitted} [ως]{.greek-added} αψινθον και [πολλοι]{.greek-omitted} [πολλυ]{.greek-added} των [ανθρωπων]{.greek-abbr} απεθανον εκ των υδατων οτι επικρανθησαν[8:11]{.aside}

και ο τεταρτος αγγελος [εσαλπισεν]{.greek-omitted} [εσαλπησεν]{.greek-added} και επληγη το τριτον του ηλιου και το τριτον της σεληνης και το τριτον των αστερων ινα σκοτισθη το τριτον αυτων και το τριτον αυτης μη φανη [ημερα]{.greek-added} [και]{.greek-added} η ημερα [μη]{.greek-added} [φανη]{.greek-added} [το]{.greek-added} [τριτον]{.greek-added} [αυτης]{.greek-added} και η νυξ ομοιως[8:12]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} και ηκουσα ενος αετου πετομενου εν [μεσουρανηματι]{.greek-omitted} [μεσουρανιματι]{.greek-added} λεγοντος φωνη μεγαλη ουαι ουαι ουαι [τοις]{.greek-omitted} [τους]{.greek-added} [κατοικουσιν]{.greek-omitted} [κατοικουντας]{.greek-added} επι της γης εκ των λοιπων φωνων της σαλπιγγος των τριων αγγελων των μελλοντων σαλπιζειν[8:13]{.aside}

### Chapter 9

και ο πεμπτος αγγελος εσαλπισεν και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αστερα εκ του [ουρανου]{.greek-abbr} πεπτωκοτα εις την γην και εδοθη αυτω η κλεις του φρεατος της αβυσσου[9:1]{.aside}

και [ηνοιξεν]{.greek-omitted} [ηνιξεν]{.greek-added} το φρεαρ της αβυσσου και ανεβη καπνος εκ του φρεατος ως καπνος καμινου [καιομενης]{.greek-omitted} [καιωμενης]{.greek-added} και εσκοτισθη ο ηλιος και ο αηρ εκ του καπνου του φρεατος[9:2]{.aside}

και εκ του καπνου εξηλθον ακριδες εις την γην και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυταις [εξουσια]{.greek-omitted} [εξουσιαν]{.greek-added} ως εχουσιν εξουσιαν οι σκορπιοι της γης[9:3]{.aside}

και ερρεθη αυταις ινα μη [αδικησωσιν]{.greek-omitted} [αδικησουσιν]{.greek-added} τον χορτον της γης ουδε παν [χλωρον]{.greek-omitted} [χλορον]{.greek-added} ουδε παν δενδρον ει μη τους [ανθρωπους]{.greek-abbr} οιτινες ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} την [σφραγιδα]{.greek-omitted} [σφραγηδα]{.greek-added} του [θεου]{.greek-abbr} επι [των]{.greek-omitted} [τω]{.greek-added} [μετωπων]{.greek-omitted} [μετοπω]{.greek-added} αυτων[9:4]{.aside}

και [εδοθη]{.greek-omitted} [εδωθη]{.greek-added} αυταις ινα μη [αποκτεινωσιν]{.greek-omitted} [αποκτινωσιν]{.greek-added} αυτους αλλ ινα βασανισθωσιν μηνας πεντε και ο βασανισμος αυτων ως βασανισμος σκορπιου οταν [παιση]{.greek-omitted} [πεση]{.greek-added} [ανθρωπον]{.greek-abbr}[9:5]{.aside}

και εν ταις ημεραις εκειναις ζητησουσιν οι [ανθρωποι]{.greek-abbr} τον θανατον και [ου]{.greek-omitted} [ουχ]{.greek-added} [μη]{.greek-omitted} ευρησουσιν αυτον και επιθυμησουσιν αποθανειν και φευξεται [ο]{.greek-added} [θανατος]{.greek-added} απ αυτων [ο]{.greek-omitted} [θανατος]{.greek-omitted}[9:6]{.aside}

και τα ομοιωματα των ακριδων [ομοια]{.greek-omitted} [ομοιωμα]{.greek-added} ιπποις ητοιμασμενοις εις πολεμον και επι τας κεφαλας αυτων [ομοιωμα]{.greek-added} ως στεφανοι χρυσοι [ομοιοι]{.greek-added} [χρυσω]{.greek-added} και τα προσωπα αυτων ως προσωπα [ανθρωπων]{.greek-abbr}[9:7]{.aside}

και [ειχον]{.greek-omitted} [ηχον]{.greek-added} τριχας ως τριχας γυναικων και οι οδοντες αυτων ως λεοντων ησαν[9:8]{.aside}

και [ειχον]{.greek-omitted} [ηχον]{.greek-added} θωρακας ως θωρακας σιδηρους και η φωνη των πτερυγων αυτων ως φωνη αρματων ιππων πολλων τρεχοντων εις πολεμον[9:9]{.aside}

και εχουσιν ουρας ομοιας σκορπιοις και κεντρα και εν ταις ουραις αυτων [και]{.greek-added} [η]{.greek-added} [εξουσιαν]{.greek-omitted} [εξουσια]{.greek-added} [αυτων]{.greek-added} [εχουσιν]{.greek-omitted} [του]{.greek-omitted} αδικησαι τους [ανθρωπους]{.greek-abbr} μηνας πεντε[9:10]{.aside}

[και]{.greek-added} [εχουσαι]{.greek-omitted} [εχουσιν]{.greek-added} [βασιλεα]{.greek-omitted} επ αυτων [βασιλεα]{.greek-added} [τον]{.greek-added} αγγελον της αβυσσου ονομα αυτω [εβραιστι]{.greek-omitted} [εβραιστη]{.greek-added} αββαδων εν δε τη [ελλινικη]{.greek-added} [ελληνικη]{.corr} ονομα εχει απολλυων[9:11]{.aside}

η ουαι η μια απηλθεν ιδου ερχεται ετι δυο ουαι μετα ταυτα[9:12]{.aside}

και ο εκτος αγγελος εσαλπισεν και ηκουσα [μιαν]{.greek-added} φωνην [μιαν]{.greek-omitted} εκ των τεσσαρων κερατων του θυσιαστηριου του χρυσου του ενωπιον του [θεου]{.greek-abbr}[9:13]{.aside}

[λεγουσαν]{.greek-omitted} [λεγοντος]{.greek-added} τω εκτω αγγελω ο εχων την σαλπιγγα λυσον τους τεσσαρας αγγελους τους δεδεμενους επι τω ποταμω τω μεγαλω ευφρατη[9:14]{.aside}

και ελυθησαν οι τεσσαρες αγγελοι οι ητοιμασμενοι εις την ωραν και εις την ημεραν και μηνα και ενιαυτον ινα αποκτεινωσιν το τριτον των [ανθρωπων]{.greek-abbr}[9:15]{.aside}

και ο αριθμος των στρατευματων του [ιππου]{.greek-omitted} [ιππικου]{.greek-added} [μυριαδες]{.greek-omitted} [δισμυριαδες]{.greek-added} μυριαδων ηκουσα τον αριθμον αυτων[9:16]{.aside}

και ουτως [ειδον]{.greek-omitted} [ιδον]{.greek-added} τους [ιππους]{.greek-omitted} [ιππικους]{.greek-added} εν τη ορασει και τους καθημενους επ αυτων εχοντας θωρακας πυρινους και υακινθινους και θειωδεις και αι κεφαλαι των ιππων ως κεφαλαι λεοντων και εκ των στοματων αυτων εκπορευεται πυρ και καπνος και θειον[9:17]{.aside}

απο των τριων πληγων τουτων απεκτανθησαν το τριτον των [ανθρωπων]{.greek-abbr} [απο]{.greek-omitted} [και]{.greek-added} [εκ]{.greek-added} του πυρος και του καπνου και του θειου του εκπορευομενου εκ των στοματων αυτων[9:18]{.aside}

η γαρ εξουσια των ιππων εν τω στοματι αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} και εν ταις ουραις αυτων αι γαρ ουραι αυτων ομοιαι [οφεων]{.greek-omitted} [οφεσιν]{.greek-added} εχουσαι κεφαλας και εν αυταις [αδικουσιν]{.greek-omitted} [αδικουσι]{.greek-added}[9:19]{.aside}

και οι λοιποι των [[λε]{.greek-abbr}]{.greek-added} [ανθρωπων]{.greek-abbr} οι ουκ απεκτανθησαν εν ταις πληγαις ταυταις ου μετενοησαν εκ των εργων των χειρων αυτων ινα μη προσκυνησωσιν τα δαιμονια και τα ειδωλα τα [χρυσα]{.greek-omitted} [χρυσεα]{.greek-added} και τα [αργυρα]{.greek-omitted} [αργυραια]{.greek-added} και τα χαλκα και τα λιθινα και τα ξυλινα α ουτε βλεπειν [δυναται]{.greek-omitted} [δυνανται]{.greek-added} ουτε ακουειν ουτε περιπατειν[9:20]{.aside}

και ου μετενοησαν εκ των φονων αυτων ουτε εκ των [φαρμακειων]{.greek-omitted} [φαρμακιων]{.greek-added} αυτων ουτε εκ της πορνειας αυτων ουτε εκ των κλεμματων αυτων[9:21]{.aside}

### Chapter 10

και [ειδον]{.greek-omitted} [ιδων]{.greek-added} [αλλον]{.greek-added} αγγελον ισχυρον καταβαινοντα εκ του [ουρανου]{.greek-abbr} περιβεβλημενον νεφελην και [η]{.greek-omitted} [ηρεις]{.greek-added} [ιρις]{.greek-omitted} [[ιρεις]{.corr}]{.greek-added} επι της κεφαλης αυτου και το προσωπον αυτου ως ο ηλιος και οι ποδες αυτου ως στυλοι πυρος[10:1]{.aside}

και εχων εν [τη]{.greek-omitted} [τηι]{.greek-added} χειρι αυτου [βιβλιον]{.greek-omitted} [β[υ]{.unclear}βλα]{.greek-added} [ριδιον]{.greek-added} ανεωγμενον και εθηκεν τον ποδα αυτου τον δεξιον επι της θαλασσης τον δε ευ[ω]{.unclear}νυμον επι της γης[10:2]{.aside}

και εκραξεν φωνη μεγαλη ωσπερ λεων μυκαται και οτε [ε]{.greek-added} [[λϛ]{.greek-abbr}]{.greek-added} [εκραξεν]{.greek-omitted} [κραξεν]{.greek-added} ελαλησαν αι επτα βρονται τας εαυτων φωνας[10:3]{.aside}

και οτε ελαλησαν αι επτα βρονται [εμελλον]{.greek-omitted} [ημελλον]{.greek-added} γραφειν και ηκουσα φωνην εκ του [ουρανου]{.greek-abbr} λεγουσαν σφραγισον α ελαλησαν αι επτα βρονται και μη αυτα γραψης[10:4]{.aside}

και ο αγγελος ον [ειδον]{.greek-omitted} [ιδον]{.greek-added} εστωτα επι της θαλασσης και επι της γης [ηρεν]{.greek-omitted} [ηρε]{.greek-added} την χειρα αυτου την δεξιαν εις τον [ουρανον]{.greek-abbr}[10:5]{.aside}

και ωμοσεν τω ζωντι εις τους αιωνας των αιωνων ος εκτισεν τον [ουρανον]{.greek-abbr} και τα εν αυτω και την γην και τα εν αυτη και την θαλασσαν και τα εν αυτη οτι χρονος ουκετι εσται[10:6]{.aside}

αλλ εν ταις ημεραις της φωνης του εβδομου αγγελου οταν μελλη σαλπιζειν και [ετελεσθη]{.greek-omitted} [τελεσθη]{.greek-added} το μυστηριον του [θεου]{.greek-abbr} ως [ευηγγελισεν]{.greek-omitted} [ευηγγελι[σ]{.unclear}ατο]{.greek-added} τους [εαυτου]{.greek-added} δουλους [αυτου]{.greek-omitted} τους προφητας[10:7]{.aside}

και η φωνη ην ηκουσα εκ του [ουρανου]{.greek-abbr} παλιν λαλουσα μετ εμου και λεγουσα υπαγε λαβε το [βιβλιδαριον]{.greek-omitted} [βιβλαριδιον]{.greek-added} το ανεωγμενον εν τη χειρι του αγγελου του εστωτος επι της θαλασσης και επι της γης[10:8]{.aside}

και [απηλθον]{.greek-omitted} [απηλθα]{.greek-added} προς τον αγγελον λεγων αυτω δουναι μοι το [βιβλιδαριον]{.greek-omitted} [βυβλαριδιον]{.greek-added} και λεγει μοι λαβε και καταφαγε αυτο και πικρανει σου την [κοιλιαν]{.greek-omitted} [καρδιαν]{.greek-added} αλλ εν τω στοματι σου εσται γλυκυ ως μελι[10:9]{.aside}

και ελαβον το [βιβλιον]{.greek-omitted} [βυβλαρυδιον]{.greek-added} εκ της χειρος του αγγελου και [κατεφαγον]{.greek-omitted} [κατεφαγα]{.greek-added} [αυτο]{.greek-omitted} [ἀυτό]{.greek-added} και ην εν [τω]{.greek-omitted} [τωι]{.greek-added} στοματι μου ως μελι γλυκυ και οτε εφαγον αυτο επικρανθη η [καρδια]{.greek-added} [κοιλια]{.corr} [μου]{.corr} [μου]{.greek-added}[10:10]{.aside}

και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} μοι δει σε παλιν προφητευσαι επι λαοις και επι [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added} και γλωσσαις και [βασιλευσιν]{.greek-omitted} [βασιλευσι]{.greek-added} πολλοις[10:11]{.aside}

### Chapter 11

και εδοθη μοι καλαμος ομοιος ραβδω [και]{.greek-added} [ιστηκει]{.greek-added} [ο]{.greek-added} [αγγελος]{.greek-added} λεγων [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και μετρησον τον ναον του [θεου]{.greek-abbr} και το θυσιαστηριον και τους προσκυνουντας εν αυτω[11:1]{.aside}

και την αυλην την εξωθεν του ναου εκβαλε [εξω]{.greek-omitted} [εξωθεν]{.greek-added} και μη αυτην μετρησης οτι εδοθη τοις εθνεσιν και την πολιν την αγιαν πατησουσιν μηνας τεσσαρακοντα [και]{.greek-omitted} δυο[11:2]{.aside}

και δωσω τοις [δυσιν]{.greek-omitted} [δυσι]{.greek-added} [μαρτυσιν]{.greek-omitted} [μαρτυσι]{.greek-added} μου και προφητευσουσιν ημερας χιλιας διακοσιας εξηκοντα περιβεβλημενοι σακκους[11:3]{.aside}

ουτοι εισιν αι δυο ελαιαι και αι δυο λυχνιαι [αι]{.greek-omitted} ενωπιον του [κυριου]{.greek-abbr} της γης [εστωσαι]{.greek-omitted} [εστωτες]{.greek-added}[11:4]{.aside}

και [ει]{.greek-omitted} [τις]{.greek-omitted} [ητις]{.greek-added} αυτους θελει αδικησαι πυρ [εκπορευεται]{.greek-omitted} [εκπορευσεται]{.greek-added} εκ του στοματος αυτων και κατεσθιει τους εχθρους αυτων και ει τις [θελει]{.greek-omitted} [θελισει]{.greek-added} αυτους αδικησαι ουτως δει αυτον αποκτανθηναι[11:5]{.aside}

ουτοι [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} [την]{.greek-added} [εξουσιαν]{.greek-added} [και]{.greek-added} [κλεισαι]{.greek-added} τον [ουρανον]{.greek-abbr} [εξουσιαν]{.greek-omitted} [κλεισαι]{.greek-omitted} ινα μη υετος βρεχη τας ημερας της προφητειας αυτων και εξουσιαν εχουσιν επι των υδατων στρεφειν αυτα εις αιμα και παταξαι την γην [οσακις]{.greek-omitted} [εαν]{.greek-omitted} [θελησωσιν]{.greek-omitted} εν παση πληγη [οσακις]{.greek-added} [εαν]{.greek-added} [θελωσι]{.greek-added}[11:6]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [τελεσωσιν]{.greek-omitted} την μαρτυριαν αυτων το θηριον το [αναβαινον]{.greek-omitted} [αναβαίνον]{.greek-added} εκ της αβυσσου [ποιησει]{.greek-omitted} [ποιηση]{.greek-added} μετ αυτων πολεμον και νικησει αυτους και αποκτενει αυτους[11:7]{.aside}

και το πτωμα αυτων επι της πλατειας της πολεως της μεγαλης ητις καλειται [πνευματι]{.greek-abbr}κως σοδομα και αιγυπτος οπου και ο [κυριος]{.greek-abbr} αυτων εσταυρωθη[11:8]{.aside}

και βλεπουσιν εκ των λαων και φυλων και γλωσσων και εθνων το πτωμα αυτων ημερας τρεις [και]{.greek-added} ημισυ και τα πτωματα αυτων ουκ [αφησουσιν]{.greek-omitted} [αφιησιν]{.greek-added} τεθηναι εις μνημα[11:9]{.aside}

και οι κατοικουντες επι της γης χαιρουσιν επ αυτοις και [ευφρανθησονται]{.greek-omitted} [ευφραινονται]{.greek-added} και δωρα [δωσουσιν]{.greek-omitted} [πεμψουσιν]{.greek-added} αλληλοις οτι ουτοι οι δυο προφηται [εβασανισαν]{.greek-omitted} [εβασανησαν]{.greek-added} τους κατοικουντας επι της γης[11:10]{.aside}

και μετα τας τρεις ημερας και ημισυ [πνευμα]{.greek-abbr} ζωης εκ του [θεου]{.greek-abbr} εισηλθεν [εις]{.greek-omitted} [εν]{.greek-added} [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και εστησαν επι τους ποδας αυτων και φοβος μεγας [επεσεν]{.greek-omitted} [επεπεσεν]{.greek-added} επι τους θεωρουντας αυτους[11:11]{.aside}

και ηκουσα φωνην μεγαλην εκ του [ουρανου]{.greek-abbr} λεγουσαν αυτοις [αναβητε]{.greek-omitted} [αναβατε]{.greek-added} ωδε και ανεβησαν εις τον [ουρανον]{.greek-abbr} εν τη νεφελη και εθεωρησαν αυτους οι εχθροι αυτων[11:12]{.aside}

και εν εκεινη τη [ημερα]{.greek-omitted} [ωρα]{.greek-added} εγενετο σεισμος μεγας και το δεκατον της πολεως επεσεν και απεκτανθησαν εν τω σεισμω ονοματα [ανθρωπων]{.greek-abbr} χιλιαδες επτα και οι λοιποι [εμφοβοι]{.greek-omitted} [εν]{.greek-added} [φοβω]{.greek-added} εγενοντο και εδωκαν δοξαν τω [θεω]{.greek-abbr} του [ουρανου]{.greek-abbr}[11:13]{.aside}

η ουαι η δευτερα απηλθεν [ιδου]{.greek-added} η ουαι η τριτη [ιδου]{.greek-omitted} ερχεται ταχυ[11:14]{.aside}

και ο εβδομος αγγελος εσαλπισεν και εγενοντο φωναι μεγαλαι εν τω [ουρανω]{.greek-abbr} [λεγουσαι]{.greek-omitted} [λεγοντες]{.greek-added} εγενετο η βασιλεια του κοσμου του [κυριου]{.greek-abbr} ημων και του [χριστου]{.greek-abbr} αυτου και βασιλευσει εις τους αιωνας των αιωνων[11:15]{.aside}

και οι εικοσι τεσσαρες πρεσβυτεροι οι ενωπιον του θρονου του [θεου]{.greek-abbr} [οι]{.greek-added} καθημενοι επι τους θρονους αυτων [επεσον]{.greek-omitted} [επεσαν]{.greek-added} επι τα προσωπα αυτων και προσεκυνησαν τω [θεω]{.greek-abbr}[11:16]{.aside}

λεγοντες ευχαριστουμεν σοι [κυριε]{.greek-abbr} ο [θεος]{.greek-abbr} ο παντοκρατωρ ο ων και ο ην οτι [ειληφας]{.greek-omitted} [ηλιφας]{.greek-added} την δυναμιν σου την μεγαλην και εβασιλευσας[11:17]{.aside}

και τα εθνη [ωργισθησαν]{.greek-omitted} [οργισθησαν]{.greek-added} και ηλθεν η οργη σου και ο καιρος των νεκρων [σου]{.greek-added} κριθηναι και δουναι [τον]{.greek-omitted} μισθον τοις δουλοις σου τοις προφηταις και τοις αγιοις και [τοις]{.greek-omitted} [τους]{.greek-added} [φοβουμενοις]{.greek-omitted} [φοβουμενους]{.greek-added} το ονομα σου [τοις]{.greek-omitted} [τους]{.greek-added} [μικροις]{.greek-omitted} [μικρους]{.greek-added} και [τοις]{.greek-omitted} [τους]{.greek-added} [μεγαλοις]{.greek-omitted} [μεγαλους]{.greek-added} και διαφθειραι τους διαφθειροντας την γην[11:18]{.aside}

και [ηνοιγη]{.greek-omitted} [ηνυγη]{.greek-added} ο ναος του [θεου]{.greek-abbr} [ο]{.greek-added} εν τω [ουρανω]{.greek-abbr} και ωφθη η κιβωτος της διαθηκης του [κυριου]{.greek-abbr} εν [τω]{.greek-omitted} [τωι]{.greek-added} ναω αυτου και εγενοντο αστραπαι και φωναι και βρονται και [σεισμος]{.greek-added} [και]{.greek-added} χαλαζα μεγαλη[11:19]{.aside}

### Chapter 12

και σημειον μεγα ωφθη εν τω [ουρανω]{.greek-abbr} γυνη περιβεβλημενη τον ηλιον και η σεληνη υποκατω των ποδων αυτης και επι της κεφαλης αυτης στεφανος αστερων δωδεκα[12:1]{.aside}

και εν γαστρι εχουσα εκραζεν ωδινουσα και βασανιζομενη τεκειν[12:2]{.aside}

και ωφθη αλλο σημειον εν τω [ουρανω]{.greek-abbr} και ιδου δρακων [μεγας]{.greek-added} πυρος [μεγας]{.greek-omitted} εχων κεφαλας επτα και κερατα δεκα και επι τας κεφαλας αυτου επτα διαδηματα[12:3]{.aside}

και η ουρα αυτου συρει το τριτον των αστερων του [ουρανου]{.greek-abbr} και εβαλεν αυτους εις την γην και ο δρακων εστηκεν ενωπιον της γυναικος της μελλουσης τεκειν ινα οταν [τεκη]{.greek-omitted} [τεκει]{.greek-added} το τεκνον αυτης καταφαγη[12:4]{.aside}

και ετεκεν [υιον]{.greek-abbr} αρρενα ος μελλει ποιμαινειν παντα τα εθνη εν ραβδω σιδηρα και ηρπασθη το τεκνον αυτης προς τον [θεον]{.greek-abbr} και προς τον θρονον αυτου[12:5]{.aside}

και η γυνη εφυγεν εις την ερημον οπου εχει εκει τοπον ητοιμασμενον υπο του [θεου]{.greek-abbr} ινα εκει [εκτρεφωσιν]{.greek-omitted} [τρεφωσιν]{.greek-added} αυτην ημερας χιλιας διακοσιας εξηκοντα[12:6]{.aside}

και εγενετο πολεμος εν τω [ουρανω]{.greek-abbr} ο μιχαηλ και οι αγγελοι αυτου [πολεμησαι]{.greek-omitted} μετα του δρακοντος και ο δρακων επολεμησεν και οι αγγελοι αυτου[12:7]{.aside}

και ουκ [ισχυσεν]{.greek-omitted} [ισχυσαν]{.greek-added} [ουδε]{.greek-omitted} [ουτε]{.greek-added} τοπος ευρεθη [αυτω]{.greek-omitted} [αυτων]{.greek-added} ετι εν τω [ουρανω]{.greek-abbr}[12:8]{.aside}

και εβληθη ο δρακων ο μεγας ο οφις ο αρχαιος ο καλουμενος διαβολος και [ο]{.greek-added} σατανας ο πλανων την οικουμενην ολην εβληθη εις την γην και οι αγγελοι αυτου μετ αυτου εβληθησαν[12:9]{.aside}

και ηκουσα φωνην μεγαλην εν τω [ουρανω]{.greek-abbr} λεγουσαν αρτι εγενετο η [σωτηρια]{.greek-abbr} και η δυναμις και [η]{.greek-omitted} βασιλεια του [θεου]{.greek-abbr} ημων και η εξουσια του [χριστου]{.greek-abbr} αυτου οτι εβληθη ο κατηγορος των αδελφων ημων ο κατηγορων αυτων ενωπιον του [θεου]{.greek-abbr} ημων ημερας και νυκτος[12:10]{.aside}

και αυτοι ενικησαν αυτον δια το αιμα του αρνιου και δια τον λογον της μαρτυριας αυτων και ουκ ηγαπησαν τ[η]{.unclear}ν ψυχην αυτων αχρι θανατου[12:11]{.aside}

δια τουτο ευφραινεσθε [οι]{.greek-added} [ουρανοι]{.greek-abbr} και οι εν αυτοις σκηνουντες ουαι τη γη και τη θαλασση οτι κατεβη ο διαβολος προς υμας εχων θυμον μεγαν ειδως οτι ολιγον καιρον εχει[12:12]{.aside}

και οτε [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} ο δρακων οτι εβληθη εις την γην [εδιωξεν]{.greek-omitted} [εδιωξε]{.greek-added} την γυναικα ητις ετεκεν τον [αρρενα]{.greek-omitted} [αρσενα]{.greek-added}[12:13]{.aside}

και εδοθησαν τη γυναικι δυο πτερυγες του αετου του μεγαλου ινα [πετηται]{.greek-omitted} [πετητε]{.greek-added} εις την ερημον εις τον τοπον αυτης [οπως]{.greek-omitted} [ινα]{.greek-added} [οπου]{.greek-added} [τρεφηται]{.greek-omitted} [τρεφεται]{.greek-added} εκει καιρον και καιρους και ημισυ καιρου απο προσωπου του οφεως[12:14]{.aside}

και εβαλεν ο οφις εκ του στοματος αυτου οπισω της γυναικος υδωρ ως ποταμον ινα αυτην ποταμοφορητον ποιηση[12:15]{.aside}

και εβοηθησεν η γη τη γυναικι και ηνοιξεν η γη το στομα αυτης και κατεπ[ι]{.unclear}εν τον ποταμον ον [εβαλεν]{.greek-omitted} [ενεβαλεν]{.greek-added} ο δρακων εκ του στοματος αυτου[12:16]{.aside}

και ωργισθη ο δρακων [επι]{.greek-omitted} [εν]{.greek-added} τη γυναικι και απηλθεν ποιησαι πολεμον μετα των λοιπων του σπερματος αυτης των τηρουντων τας εντολας του [θεου]{.greek-abbr} και εχοντων την μαρτυριαν [ιησου]{.greek-abbr}[12:17]{.aside}

[και]{.greek-added} [εσταθη]{.greek-added} [επι]{.greek-added} [την]{.greek-added} [αμμον]{.greek-added} [της]{.greek-added} [θαλασσης]{.greek-added}[12:18]{.aside}

### Chapter 13

και [εσταθην]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [αμμον]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ειδον]{.greek-omitted} [ιδον]{.greek-added} εκ της θαλασσης θηριον αναβαινον εχον κερατα [δεκα]{.greek-omitted} [[ι]{.greek-abbr}]{.greek-added} και κεφαλας επτα και επι των κερατων αυτου δεκα [διαδηματα]{.greek-omitted} [διαδιματα]{.greek-added} και επι τας κεφαλας αυτου ονοματα [βλασφημιας]{.greek-omitted} [βλασφημειας]{.greek-added}[13:1]{.aside}

και το θηριον ο [ειδον]{.greek-omitted} [ιδον]{.greek-added} ην ομοιον παρδαλει και οι ποδες αυτου ως αρκου και το στομα αυτου ως στομα [λεοντος]{.greek-omitted} [λεοντων]{.greek-added} και εδωκεν αυτω ο δρακων την δυναμιν αυτου και τον θρονον αυτου και εξουσιαν μεγαλην[13:2]{.aside}

και μιαν εκ των κεφαλων αυτου ωσει [εσφαγμενην]{.greek-omitted} [εσφα]{.greek-added} [γμανην]{.greek-added} εις θανατον και η πληγη του θανατου αυτου εθεραπευθη και εθαυμασεν ολη η γη οπισω του θηριου[13:3]{.aside}

και προσεκυνησαν τω δρακοντι [οτι]{.greek-added} [εδωκεν]{.greek-added} [τω]{.greek-omitted} [δεδωκοτι]{.greek-omitted} [την]{.greek-omitted} εξουσιαν τω θηριω και προσεκυνησαν τω θηριω λεγοντες τις ομοιος [σοι]{.greek-added} τω θηριω και τις δυνατος πολεμησαι μετ αυτου[13:4]{.aside}

και εδοθη [αυτω]{.greek-omitted} [αυτο]{.greek-added} στομα λαλουν μεγαλα και βλασφημιαν και εδοθη αυτω [εξουσια]{.greek-omitted} [πολεμον]{.greek-omitted} [ποιησαι]{.greek-omitted} [πολεμησαι]{.greek-added} μηνας [τεσσαρακοντα]{.greek-omitted} [τεσσαρακονταδυο]{.greek-added} [δυο]{.greek-omitted}[13:5]{.aside}

και ηνοιξεν το στομα αυτου εις βλασφημιαν [[βλασφημειαν]{.corr}]{.greek-added} προς τον [θεον]{.greek-abbr} βλασφημησαι το ονομα αυτου και την σκηνην αυτου τους εν τω [ουρανω]{.greek-abbr} [σκηνουντας]{.greek-omitted} [σκινουντας]{.greek-added}[13:6]{.aside}

και εδοθη αυτω ποιησαι πολεμον μετα των αγιων και νικησαι αυτους και εδοθη αυτω εξουσια επι πασαν φυλην και λαον και γλωσσαν και εθνος[13:7]{.aside}

και προσκυνησουσιν [αυτω]{.greek-omitted} [αυτον]{.greek-added} παντες οι κατοικουντες επι της γης ων ου γεγραπται το ονομα εν τω βιβλιω της ζωης του αρνιου του εσφαγμενου απο καταβολης κοσμου[13:8]{.aside}

ει τις εχει ους ακουσατω[13:9]{.aside}

ει τις [εχει]{.greek-omitted} [εις]{.greek-added} [αιχμαλωσιαν]{.greek-added} [απαγει]{.greek-added} [εις]{.greek-added} αιχμαλωσιαν υπαγει ει τις εν [μαχαιρα]{.greek-omitted} [μαχαιρη]{.greek-added} [αποκτενει]{.greek-omitted} [αποκτένει]{.greek-added} δει αυτον εν [μαχαιρα]{.greek-omitted} [μαχαιρη]{.greek-added} αποκτανθηναι ωδε εστιν η υπομονη και η πιστις των αγιων[13:10]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλο θηριον [αναβαινον]{.greek-omitted} [αναβαῖνον]{.greek-added} εκ της γης και ειχεν κερατα δυο ομοια αρνιω και [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} ως δρακων[13:11]{.aside}

και την εξουσιαν του πρωτου θηριου πασαν ποιει ενωπιον αυτου και εποιει την γην και τους εν αυτη κατοικουντας ινα [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσι]{.greek-added} το θηριον το πρωτον ου εθεραπευθη η πληγη του θανατου αυτου[13:12]{.aside}

και ποιει σημεια μεγαλα και πυρ ινα εκ του [ουρανου]{.greek-abbr} [καταβαινη]{.greek-omitted} [καταβαινει]{.greek-added} [επι]{.greek-omitted} [εις]{.greek-added} την γην ενωπιον των [ανθρωπων]{.greek-abbr}[13:13]{.aside}

και πλανα [τους]{.greek-omitted} [εμους]{.greek-omitted} τους κατοικουντας επι της γης δια τα σημεια α εδοθη αυτω ποιησαι ενωπιον του θηριου λεγων τοις κατοικουσιν επι της γης ποιησαι εικονα τω θηριω [ο]{.greek-omitted} [ὡς]{.greek-added} ειχεν την πληγην και εζησεν απο της [μαχαιρας]{.greek-omitted} [μαχαιρης]{.greek-added}[13:14]{.aside}

και εδοθη αυτω [δουναι]{.greek-added} [πνευμα]{.greek-abbr} [δουναι]{.greek-omitted} τη εικονι του θηριου ινα και λαληση η εικων του θηριου και [ποιηση]{.greek-omitted} [ποιησει]{.greek-added} οσοι [εαν]{.greek-omitted} [αν]{.greek-added} μη [προσκυνησωσιν]{.greek-omitted} [προσκυνησουσιν]{.greek-added} τη εικονι του θηριου [αποκτανθωσιν]{.greek-omitted} [αποκτανθηναι]{.greek-added}[13:15]{.aside}

και ποιει παντας τους μικρους και τους μεγαλους και τους πλουσιους και τους πτωχους και τους ελευθερους και τους δουλους ινα [δωσωσιν]{.greek-omitted} [δωσιν]{.greek-added} αυτοις χαραγματα επι της χειρος αυτων της δεξιας η επι το [μετωπον]{.greek-omitted} [μετοπον]{.greek-added} αυτων[13:16]{.aside}

και ινα μη τις [δυναται]{.greek-omitted} [δυνηται]{.greek-added} αγορασαι η [πωλησαι]{.greek-omitted} [πολησαι]{.greek-added} ει μη ο εχων το χαραγμα το ονομα του θηριου η τον αριθμον του ονοματος αυτου[13:17]{.aside}

ωδε η σοφια [εστιν]{.greek-omitted} [εχει]{.greek-added} ο εχων νουν ψηφισατω τον αριθμον του θηριου αριθμος γαρ [ανθρωπου]{.greek-abbr} εστιν [και]{.greek-omitted} [αριθμος]{.greek-added} [γαρ]{.greek-added} [[ανθρωπου]{.greek-abbr}]{.greek-added} [εστιν]{.greek-added} [[χξϛ]{.greek-abbr}]{.greek-added} ο αριθμος αυτου [εστιν]{.greek-omitted} [εξακοσια]{.greek-omitted} [εξηκοντα]{.greek-omitted} [εξ]{.greek-omitted}[13:18]{.aside}

### Chapter 14

[και]{.greek-omitted} [αδουσιν]{.greek-omitted} [ωδην]{.greek-omitted} [καινην]{.greek-omitted} [ενωπιον]{.greek-omitted} [του]{.greek-omitted} [θρονου]{.greek-omitted} [και]{.greek-omitted} [ενωπιον]{.greek-omitted} [των]{.greek-omitted} [τεσσαρων]{.greek-omitted} [ζωων]{.greek-omitted} [και]{.greek-omitted} [των]{.greek-omitted} [πρεσβυτερων]{.greek-omitted} [και]{.greek-omitted} [ουδεις]{.greek-omitted} [εδυνατο]{.greek-omitted} [μαθειν]{.greek-omitted} [την]{.greek-omitted} [ωδην]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [αι]{.greek-omitted} [εκατον]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσαρες]{.greek-omitted} [χιλιαδες]{.greek-omitted} [οι]{.greek-supplied} [ηγορασμενοι]{.greek-supplied} [απο]{.greek-supplied} [της]{.greek-supplied} γης[14:3]{.aside}

ο[υτοι]{.greek-supplied} [εισιν]{.greek-supplied} [οι]{.greek-supplied} μετα [γυναικων]{.greek-supplied} ουκ εμολυν[θη]{.greek-supplied}σαν παρθενοι γαρ εισιν ουτοι εισιν [οι]{.greek-supplied} ακολουθουντες τω αρνιω οπου [αν]{.greek-omitted} [ε[αν]{.greek-supplied}]{.greek-added} υ[παγη]{.greek-supplied} ουτοι υπο [ιησου]{.greek-abbr} [ηγορασθησαν]{.greek-omitted} [[α]{.unclear}γορασθη[σαν]{.greek-supplied}]{.greek-added} [α]{.greek-supplied}πο των [ανθρωπων]{.greek-abbr} απαρχη τω [θεω]{.greek-abbr} και τω αρνιω[14:4]{.aside}

και [ουχ]{.greek-omitted} [ευρεθη]{.greek-omitted} εν τω στοματι αυτων [ουχ]{.greek-added} [ευρεθη]{.greek-added} ψευδος αμωμοι γαρ εισιν[14:5]{.aside}

