---
title: "Collation of Byz^RP^ vs 32411 (2411)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2411 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32411).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2411                                   	| λογος                              	|
| 2411 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2411 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2411               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2411                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2411 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2411                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1 | instance no. 2]{.aside}

[ως]{.greek-omitted} [καθως]{.greek-added} γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου [εμπροσθεν]{.greek-omitted} [σου]{.greek-omitted}[1:2]{.aside}

[ως]{.greek-omitted} [καθως]{.greek-added} γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου [εμπροσθεν]{.greek-omitted} [σου]{.greek-omitted}[1:2 | instance no. 2]{.aside}

φωνη βοωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο ιωαννης βαπτιζων εν τη ερημω και κηρυσσων βαπτισμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται και εβαπτιζοντο παντες εν τω ιορδανη ποταμω υπ αυτου εξομολογουμενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε [ο]{.greek-omitted} ιωαννης ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και μελι αγριον[1:6]{.aside}

και εκηρυσσεν λεγων ερχεται ο [ισ]{.greek-added} [ισχυροτερος]{.greek-omitted} [μου]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [ου]{.greek-omitted} [ουκ]{.greek-omitted} [ειμι]{.greek-omitted} [ικανος]{.greek-omitted} [κυψας]{.greek-omitted} [λυσαι]{.greek-omitted} [τον]{.greek-omitted} [ιμαντα]{.greek-omitted} [των]{.greek-omitted} [υποδηματων]{.greek-omitted} [αυτου]{.greek-omitted}[1:7]{.aside}

[και]{.greek-omitted} [εκηρυσσεν]{.greek-omitted} [λεγων]{.greek-omitted} [ερχεται]{.greek-omitted} [ο]{.greek-omitted} [ισχυροτερος]{.greek-omitted} [χυροτερος]{.greek-added} μου οπισω μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7 | instance no. 2]{.aside}

εγω μεν εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ιησους]{.greek-abbr} απο [ναζαρετ]{.greek-omitted} [ναζαρεθ]{.greek-added} της γαλιλαιας και εβαπτισθη υπο ιωαννου εις τον ιορδανην[1:9]{.aside}

και ευθεως αναβαινων απο του υδατος ειδεν σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει περιστεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ [των]{.greek-omitted} [τον]{.greek-added} [ουρανων]{.greek-omitted} [[ουρανον]{.greek-abbr}]{.greek-added} συ ει ο υιος μου ο αγαπητος εν ω ευδοκησα[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το πνευμα αυτον εκβαλλει εις την ερημον[1:12]{.aside}

και ην εκει [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} ημερας [τεσσαρακοντα]{.greek-omitted} [πειραζομενος]{.greek-omitted} [υπο]{.greek-omitted} [του]{.greek-omitted} [σατανα]{.greek-omitted} [και]{.greek-omitted} [ην]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [θηριων]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [αγγελοι]{.greek-omitted} [διηκονουν]{.greek-omitted} [αυτω]{.greek-omitted}[1:13]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [εκει]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [ημερας]{.greek-omitted} [τεσσαρακοντα]{.greek-omitted} [τεσσερακοντα]{.greek-added} πειραζομενος υπο του σατανα και ην μετα των θηριων και οι αγγελοι διηκονουν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[1:13 | instance no. 2]{.aside}

μετα δε το παραδοθηναι τον ιωαννην ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι πεπληρωται ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευαγγελιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου του σιμωνος [βαλλοντας]{.greek-omitted} [αμφιβαλλοντας]{.greek-added} αμφιβληστρον εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησ[ω]{.unclear} [υ]{.greek-added} [υμας]{.greek-omitted} [γενεσθαι]{.greek-omitted} [αλιεις]{.greek-omitted} [ανθρωπων]{.greek-omitted}[1:17]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [δευτε]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [και]{.greek-omitted} [ποιησω]{.greek-omitted} [υμας]{.greek-omitted} [μας]{.greek-added} [γενεσθαι]{.greek-omitted} [γενεσθε]{.greek-added} αλιεις [ανθρωπων]{.greek-abbr}[1:17 | instance no. 2]{.aside}

[και]{.greek-omitted} ευθεως αφεντες τα δικτυα αυτων ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} [ιακωβον]{.greek-omitted} [ιακοβων]{.greek-added} τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου και αυτους εν τω πλοιω καταρτιζοντας τα δικτυα [αυτων]{.greek-added}[1:19]{.aside}

και ευθεως εκαλεσεν αυτους και [αφεντες]{.greek-omitted} [αφενταις]{.greek-added} τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω [πλω]{.greek-added} [πλοιω]{.corr} μετα των [μισθωτων]{.greek-omitted} [μισθοτων]{.greek-added} απηλθον οπισω αυτου[1:20]{.aside}

και εισπορευονται εις καπερναουμ και ευθεως τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι [γραμματεις]{.greek-omitted} [γραμ]{.greek-added}[1:22]{.aside}

[και]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [επι]{.greek-omitted} [τη]{.greek-omitted} [διδαχη]{.greek-omitted} [αυτου]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [διδασκων]{.greek-omitted} [αυτους]{.greek-omitted} [ως]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχων]{.greek-omitted} [και]{.greek-omitted} [ουχ]{.greek-omitted} [ως]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [ματεις]{.greek-added}[1:22 | instance no. 2]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν πνευματι ακαθαρτω και ανεκραξεν[1:23]{.aside}

λεγων εα τι ημιν και [σοι]{.greek-omitted} [συ]{.greek-added} [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το πνευμα το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και [εθαμβηθησαν]{.greek-omitted} [εθαυμασαν]{.greek-added} παντες ωστε συζητειν προς εαυτους λεγοντας τι εστιν τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν αυτω[1:27]{.aside}

[εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} δε η ακοη αυτου ευθυς εις ολην [την]{.greek-omitted} [περιχωρον]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted}[1:28]{.aside}

[εξηλθεν]{.greek-omitted} [δε]{.greek-omitted} [η]{.greek-omitted} [ακοη]{.greek-omitted} [αυτου]{.greek-omitted} [ευθυς]{.greek-omitted} [εις]{.greek-omitted} [ολην]{.greek-omitted} την περιχωρον της γαλιλαιας[1:28 | instance no. 2]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα [του]{.greek-added} σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος ευθεως και [διηκονει]{.greek-omitted} [διηκονη]{.greek-added} αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους [κακως]{.greek-omitted} [εχοντας]{.greek-omitted} [ποικιλαις]{.greek-omitted} [νοσοις]{.greek-omitted} [και]{.greek-omitted} [δαιμονια]{.greek-omitted} [πολλα]{.greek-omitted} [εξεβαλεν]{.greek-omitted} [και]{.greek-omitted} [ουκ]{.greek-omitted} [ηφιεν]{.greek-omitted} [λαλειν]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted} [οτι]{.greek-omitted} [ηδεισαν]{.greek-omitted} [αυτον]{.greek-omitted}[1:34]{.aside}

[και]{.greek-omitted} [εθεραπευσεν]{.greek-omitted} [πολλους]{.greek-omitted} κακως εχοντας ποικιλαις νοσοις και δαιμονια πολλα εξεβαλεν και ουκ ηφιεν λαλειν τα δαιμονια οτι ηδεισαν αυτον[1:34 | instance no. 2]{.aside}

και πρωι εννυχον λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και κατεδιωξαν αυτον ο [τε]{.greek-added} σιμων και οι μετ αυτου[1:36]{.aside}

και [ευροντες]{.greek-omitted} [ευρονταις]{.greek-added} αυτον λεγουσιν αυτω οτι παντες σε [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας [κωμοπολεις]{.greek-omitted} [κωμοπολοις]{.greek-added} ινα και εκει κηρυξω εις τουτο γαρ εξεληλυθα[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και τα δαιμονια εκβαλλων[1:39]{.aside}

και ερχεται προς αυτον λεπρος [πα]{.greek-added} [παρακαλων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [γονυπετων]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγων]{.greek-omitted} [αυτω]{.greek-omitted} [οτι]{.greek-omitted} [εαν]{.greek-omitted} [θελης]{.greek-omitted} [δυνασαι]{.greek-omitted} [με]{.greek-omitted} [καθαρισαι]{.greek-omitted}[1:40]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [λεπρος]{.greek-omitted} [παρακαλων]{.greek-omitted} [ρακαλων]{.greek-added} [αυτον]{.greek-omitted} [και]{.greek-omitted} [γονυπετων]{.greek-omitted} αυτον και λεγων [αυτω]{.greek-omitted} οτι εαν θελης δυνασαι με καθαρισαι[1:40 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν [απ]{.greek-omitted} [αυτου]{.greek-omitted} η λεπρα και [εκαθαρισθη]{.greek-omitted} [εκαθερισθη]{.greek-added}[1:42]{.aside}

και [εμβριμησαμενος]{.greek-omitted} [εμβρισαμενος]{.greek-added} αυτω [ευθεως]{.greek-omitted} εξεβαλεν αυτον [ευθεως]{.greek-added}[1:43]{.aside}

και λεγει αυτω ορα μηδενι μηδεν ειπης [αλλ]{.greek-omitted} [αλλα]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα [και]{.greek-omitted} διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι φανερως [εις]{.greek-omitted} [πολιν]{.greek-omitted} [εισελθειν]{.greek-omitted} [αλλ]{.greek-omitted} [εξω]{.greek-omitted} [εν]{.greek-omitted} [ερημοις]{.greek-omitted} [τοποις]{.greek-omitted} [ην]{.greek-omitted} [και]{.greek-omitted} [ηρχοντο]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [πανταχοθεν]{.greek-omitted}[1:45]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [εξελθων]{.greek-omitted} [ηρξατο]{.greek-omitted} [κηρυσσειν]{.greek-omitted} [πολλα]{.greek-omitted} [και]{.greek-omitted} [διαφημιζειν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [ωστε]{.greek-omitted} [μηκετι]{.greek-omitted} [αυτον]{.greek-omitted} [δυνασθαι]{.greek-omitted} [φανερως]{.greek-omitted} εις πολιν εισελθειν αλλ εξω εν ερημοις τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45 | instance no. 2]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισελθε]{.greek-added} παλιν εις καπερναουμ δι ημερων και [ηκουσθη]{.greek-omitted} [ηκουσθην]{.greek-added} οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε [μηκε]{.greek-added} [μηκετι]{.corr} χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτον παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι [αυτω]{.greek-added} προσεγγισαι [αυτω]{.greek-omitted} δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω [παραλυτικω]{.greek-omitted} [παραλυ]{.greek-added} [τεκνον]{.greek-omitted} [αφεωνται]{.greek-omitted} [σοι]{.greek-omitted} [αι]{.greek-omitted} [αμαρτιαι]{.greek-omitted} [σου]{.greek-omitted}[2:5]{.aside}

[τικω]{.greek-added} [ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [την]{.greek-omitted} [πιστιν]{.greek-omitted} [αυτων]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [παραλυτικω]{.greek-omitted} τεκνον αφεωνται σοι αι αμαρτιαι σου[2:5 | instance no. 2]{.aside}

ησαν δε τινες των [γραμματαιων]{.greek-added} [γραμματεων]{.corr} εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος [ουτως]{.greek-omitted} [ουτω]{.greek-added} λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} αυτου οτι ουτως αυτοι διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω αφεωνται σου αι αμαρτιαι η ειπειν [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} και αρον [τον]{.greek-added} [κραβαττον]{.greek-added} σου [τον]{.greek-omitted} [κραββατον]{.greek-omitted} και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} αφιεναι επι της [γης]{.greek-omitted} [αμαρτιας]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [παραλυτικω]{.greek-omitted}[2:10]{.aside}

[ινα]{.greek-omitted} [δε]{.greek-omitted} [ειδητε]{.greek-omitted} [οτι]{.greek-omitted} [εξουσιαν]{.greek-omitted} [εχει]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [αφιεναι]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} γης αμαρτιας λεγει τω παραλυτικω[2:10 | instance no. 2]{.aside}

σοι λεγω εγειραι και αρον τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον [κραββατον]{.greek-omitted} [κραβαττον]{.greek-added} εξηλθεν εναντιον παντων ωστε [εξιστασθαι]{.greek-omitted} [εξιστασθε]{.greek-added} παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added}[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την [θαλασσαν]{.greek-omitted} [θαλασσα]{.greek-added} και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ιδε]{.greek-added} λευι τον του αλφαιου καθημενον επι το τελωνιον και λεγει αυτω ακολουθει μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και [πο]{.greek-added} [πολλοι]{.greek-omitted} [τελωναι]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλοι]{.greek-omitted} [συνανεκειντο]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ησαν]{.greek-omitted} [γαρ]{.greek-omitted} [πολλοι]{.greek-omitted} [και]{.greek-omitted} [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted}[2:15]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κατακεισθαι]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [λλοι]{.greek-added} τελωναι και αμαρτωλοι [συνανεκειντο]{.greek-omitted} [ανεκειντο]{.greek-added} τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15 | instance no. 2]{.aside}

και οι γραμματεις και οι φαρισαιοι ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

και ακουσας ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται ιωαννου και οι [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [φαρισαιοι]{.greek-added} νηστευοντες και ερχονται και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} [αυτω]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευουσιν]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [σοι]{.greek-omitted} [μαθηται]{.greek-omitted} [ου]{.greek-omitted} [νηστευουσιν]{.greek-omitted}[2:18]{.aside}

[και]{.greek-omitted} [ησαν]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [ιωαννου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [των]{.greek-omitted} [φαρισαιων]{.greek-omitted} [νηστευοντες]{.greek-omitted} [και]{.greek-omitted} [ερχονται]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} αυτω δια τι οι μαθηται ιωαννου και οι των φαρισαιων νηστευουσιν οι δε σοι μαθηται ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18 | instance no. 2]{.aside}

και ειπεν αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον μεθ [εαυτων]{.greek-omitted} [εαυτον]{.greek-added} [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τον νυμφιον ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν απαρθη απ αυτων ο νυμφιος και τοτε νηστευσουσιν εν [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [εκεινη]{.greek-added} [τη]{.greek-added} [ημεραις]{.greek-omitted} [ημερα]{.greek-added}[2:20]{.aside}

[και]{.greek-omitted} ουδεις επιβλημα ρακους [[ρακκους]{.corr}]{.greek-added} [αγναφου]{.greek-omitted} [ακναφου]{.greek-added} [επιρραπτει]{.greek-omitted} [επιραπτει]{.greek-added} επι ιματιω παλαιω ει δε [μη]{.greek-omitted} [μηγε]{.greek-added} αιρει [απ]{.greek-added} [αυτου]{.greek-added} το πληρωμα [αυτου]{.greek-omitted} το καινον του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [παλαιους]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [ρησσει]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [ο]{.greek-omitted} [νεος]{.greek-omitted} [τους]{.greek-omitted} [ασκους]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [οινος]{.greek-omitted} [εκχειται]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [ασκοι]{.greek-omitted} [απολουνται]{.greek-omitted} [αλλα]{.greek-omitted} [οινον]{.greek-omitted} [νεον]{.greek-omitted} [εις]{.greek-omitted} [ασκους]{.greek-omitted} [καινους]{.greek-omitted} [βλητεον]{.greek-omitted}[2:22]{.aside}

[και]{.greek-omitted} [ουδεις]{.greek-omitted} [βαλλει]{.greek-omitted} οινον νεον εις ασκους παλαιους ει δε μη ρησσει [ο]{.greek-omitted} [οινος]{.greek-omitted} [ο]{.greek-omitted} [νεος]{.greek-omitted} [τους]{.greek-omitted} [ασκους]{.greek-omitted} [και]{.greek-omitted} ο οινος εκχειται και οι ασκοι απολουνται αλλα οινον νεον εις ασκους καινους βλητεον[2:22 | instance no. 2]{.aside}

και εγενετο παραπορευεσθαι αυτον [εν]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} δια των σποριμων [εν]{.greek-added} [τοις]{.greek-added} [σαββασι]{.greek-added} και ηρξαντο οι μαθηται αυτου οδον ποιειν [τυλοντες]{.greek-added} [τιλλοντες]{.greek-omitted} [[τυλλοντες]{.corr}]{.greek-added} τους σταχυας[2:23]{.aside}

και οι φαρισαιοι ελεγον [αυτω]{.greek-omitted} [αυτον]{.greek-added} ιδε τι [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} [εν]{.greek-omitted} τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε τι εποιησεν [δαυιδ]{.greek-abbr} οτε χρειαν εσχεν και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι αβιαθαρ [του]{.greek-added} αρχιερεως και τους αρτους της προθεσεως [εφαγεν]{.greek-omitted} [ους]{.greek-omitted} [ουκ]{.greek-omitted} [εξεστιν]{.greek-omitted} [φαγειν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [τοις]{.greek-omitted} [ιερευσιν]{.greek-omitted} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [ουσιν]{.greek-omitted}[2:26]{.aside}

[πως]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [οικον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [επι]{.greek-omitted} [αβιαθαρ]{.greek-omitted} [αρχιερεως]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [της]{.greek-omitted} [προθεσεως]{.greek-omitted} εφαγεν ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει [μη]{.greek-omitted} [μι]{.greek-added} τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} και τοις συν αυτω [ουσιν]{.greek-omitted} [ουσι]{.greek-added}[2:26 | instance no. 2]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} [εγενετο]{.greek-omitted} [εγενετον]{.greek-added} ουχ ο ανθρωπος δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο υιος του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} εξηραμμενην εχων την χειρα[3:1]{.aside}

και παρετηρουν αυτον [ει]{.greek-omitted} [εν]{.greek-added} τοις σαββασιν [αυτον]{.greek-added} θεραπευσει [αυτον]{.greek-omitted} ινα [κατηγορησωσιν]{.greek-omitted} [κατηγορισ[ω]{.unclear}σιν]{.greek-added} αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω εξηραμμενην [εχοντι]{.greek-omitted} [εχων]{.greek-added} την χειρα [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} εις το μεσον[3:3]{.aside}

και λεγει αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις σαββασιν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η [απολεσαι]{.greek-added} [αποκτειναι]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} [εσιωπων]{.greek-omitted}[3:4]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [εξεστιν]{.greek-omitted} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} [αγαθοποιησαι]{.greek-omitted} [η]{.greek-omitted} [κακοποιησαι]{.greek-omitted} [ψυχην]{.greek-omitted} [σωσαι]{.greek-omitted} [η]{.greek-omitted} [αποκτειναι]{.greek-omitted} οι δε εσιωπων[3:4 | instance no. 2]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη πωρωσει της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και αποκατεσταθη η χειρ αυτου [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κατ αυτου οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν [αυτον]{.greek-added} [αυτω]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted}[3:7]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα εποιει ηλθον προς [αυτον]{.greek-omitted}[3:8]{.aside}

[και]{.greek-omitted} [απο]{.greek-omitted} [ιεροσολυμων]{.greek-omitted} [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} [και]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [περι]{.greek-omitted} [τυρον]{.greek-omitted} [και]{.greek-omitted} [σιδωνα]{.greek-omitted} [πληθος]{.greek-omitted} [πολυ]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οσα]{.greek-omitted} [εποιει]{.greek-omitted} [ηλθον]{.greek-omitted} [προς]{.greek-omitted} αυτον[3:8 | instance no. 2]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον προσκαρτερη αυτω δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν [αυτω]{.greek-omitted} [αυτον]{.greek-added} ινα αυτου [αψωνται]{.greek-omitted} [απτωνται]{.greek-added} [οσει]{.greek-added} [οσοι]{.corr} ειχον μαστιγας[3:10]{.aside}

και τα πνευματα τα ακαθαρτα οταν αυτον εθεωρει [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυτον [ποιησωσιν]{.greek-omitted} [ποιωσι]{.greek-added}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα [αποστελλη]{.greek-omitted} [αποστελλει]{.greek-added} αυτους κηρυσσειν[3:14]{.aside}

και εχειν [ε]{.greek-added} [εξουσιαν]{.greek-omitted} [θεραπευειν]{.greek-omitted} [τας]{.greek-omitted} [νοσους]{.greek-omitted} [και]{.greek-omitted} [εκβαλλειν]{.greek-omitted} [τα]{.greek-omitted} [δαιμονια]{.greek-omitted}[3:15]{.aside}

[και]{.greek-omitted} [εχειν]{.greek-omitted} [εξουσιαν]{.greek-omitted} [ξουσιαν]{.greek-added} [θεραπευειν]{.greek-omitted} [θεραπευει]{.greek-added} τας νοσους και εκβαλλειν τα δαιμονια[3:15 | instance no. 2]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον του ιακωβου και επεθηκεν αυτοις ονοματα βοανεργες ο εστιν [υιοι]{.greek-omitted} [υιον]{.greek-added} βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν [ο]{.greek-added} οχλος ωστε μη δυνασθαι αυτους [μητε]{.greek-omitted} [μηδε]{.greek-added} αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου [εξηλθον]{.greek-omitted} [κρατησαι]{.greek-omitted} [αυτον]{.greek-omitted} [ελεγον]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [εξεστη]{.greek-omitted}[3:21]{.aside}

[και]{.greek-omitted} [ακουσαντες]{.greek-omitted} [οι]{.greek-omitted} [παρ]{.greek-omitted} [αυτου]{.greek-omitted} εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21 | instance no. 2]{.aside}

και οι γραμματεις οι απο ιεροσολυμων καταβαντες ελεγον οτι [βεελζεβουλ]{.greek-omitted} [βελζεβουλ]{.greek-added} εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια [εφ]{.greek-omitted} [αφ]{.greek-added} εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται [σταθηναι]{.greek-omitted} [στηναι]{.greek-added} η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων εις [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπασαι]{.greek-omitted} [εαν]{.greek-omitted} [μη]{.greek-omitted} [πρωτον]{.greek-omitted} [τον]{.greek-omitted} [ισχυρον]{.greek-omitted} [δηση]{.greek-omitted} [και]{.greek-omitted} [τοτε]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [διαρπαση]{.greek-omitted}[3:27]{.aside}

[ουδεις]{.greek-omitted} [δυναται]{.greek-omitted} [τα]{.greek-omitted} [σκευη]{.greek-omitted} [του]{.greek-omitted} [ισχυρου]{.greek-omitted} [εισελθων]{.greek-omitted} [εις]{.greek-omitted} την [οικιαν]{.greek-omitted} [οικειαν]{.greek-added} αυτου διαρπασαι εαν μη πρωτον τον ισχυρον δηση και τοτε την οικιαν αυτου διαρπαση[3:27 | instance no. 2]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται τα [αμαρτηματα]{.greek-omitted} [αμαρτιματα]{.greek-added} τοις υιοις των ανθρωπων και βλασφημιαι οσας αν [βλασφημησωσιν]{.greek-omitted} [βλασφημισωσιν]{.greek-added}[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν εις τον αιωνα αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

[οτι]{.greek-omitted} [ο]{.greek-added} ελεγον πνευμα ακαθαρτον εχει[3:30]{.aside}

ερχονται ουν οι αδελφοι [αυτου]{.greek-added} και η [μητηρ]{.greek-abbr} αυτου και εξω εστωτες απεστειλαν προς αυτον φωνουντες αυτον[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} ειπον δε αυτω ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω ζητουσιν σε[3:32]{.aside}

και απεκριθη [αυτοις]{.greek-omitted} [λεγων]{.greek-omitted} [τις]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [μητηρ]{.greek-omitted} [μου]{.greek-omitted} [η]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [μου]{.greek-omitted}[3:33]{.aside}

[και]{.greek-omitted} [απεκριθη]{.greek-omitted} αυτοις λεγων τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33 | instance no. 2]{.aside}

και περιβλεψαμενος κυκλω τους περι αυτον καθημενους λεγει [ιδε]{.greek-omitted} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη μου και [μητηρ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35]{.aside}

### Chapter 4

και παλιν ηρξατο διδασκειν παρα την θαλασσαν και [συνηχθη]{.greek-omitted} [συνηχθησαν]{.greek-added} προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις [το]{.greek-omitted} πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και [ε]{.greek-added} [εγενετο]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [σπειρειν]{.greek-omitted} [ο]{.greek-omitted} [μεν]{.greek-omitted} [επεσεν]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [και]{.greek-omitted} [ηλθεν]{.greek-omitted} [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [και]{.greek-omitted} [κατεφαγεν]{.greek-omitted} [αυτο]{.greek-omitted}[4:4]{.aside}

[και]{.greek-omitted} [εγενετο]{.greek-omitted} [γενετο]{.greek-added} εν τω σπειρειν ο μεν επεσεν παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα [του]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} και κατεφαγεν [αυτο]{.greek-omitted} [αυτω]{.greek-added}[4:4 | instance no. 2]{.aside}

αλλο δε επεσεν επι [το]{.greek-omitted} [τα]{.greek-added} πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην πολλην και ευθεως εξανετειλεν δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν εξηρανθη[4:6]{.aside}

και αλλο επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ εδωκεν[4:7]{.aside}

και αλλο επεσεν εις την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και εφερεν εν τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} ηρωτησαν αυτον οι περι αυτον συν τοις δωδεκα την παραβολην[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται [γνωναι]{.greek-omitted} το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα γινεται[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [συνιωσι]{.greek-added} [μηπωτε]{.greek-added} [επιστρεψωσι]{.greek-added} και [αφεθησεται]{.greek-added} [ακουοντες]{.greek-omitted} [ακουωσιν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [συνιωσιν]{.greek-omitted} [μηποτε]{.greek-omitted} [επιστρεψωσιν]{.greek-omitted} [και]{.greek-omitted} [αφεθη]{.greek-omitted} αυτοις τα αμαρτηματα[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και [πως]{.greek-omitted} πασας τας παραβολας [γνωσεσθε]{.greek-omitted} [γνωσεσθαι]{.greek-added}[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε [εισιν]{.greek-omitted} [ησιν]{.greek-added} οι παρα την οδον οπου [σπειρεται]{.greek-omitted} [σπειρετε]{.greek-added} ο λογος και οταν ακουσωσιν ευθεως ερχεται [ο]{.greek-omitted} [σατανας]{.greek-omitted} [και]{.greek-omitted} [αιρει]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [τον]{.greek-omitted} [εσπαρμενον]{.greek-omitted} [εν]{.greek-omitted} [ταις]{.greek-omitted} [καρδιαις]{.greek-omitted} [αυτων]{.greek-omitted}[4:15]{.aside}

[ουτοι]{.greek-omitted} [δε]{.greek-omitted} [εισιν]{.greek-omitted} [οι]{.greek-omitted} [παρα]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [οπου]{.greek-omitted} [σπειρεται]{.greek-omitted} [ο]{.greek-omitted} [λογος]{.greek-omitted} [και]{.greek-omitted} [οταν]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [ευθεως]{.greek-omitted} [ερχεται]{.greek-omitted} ο σατανας και αιρει τον λογον τον εσπαρμενον εν ταις καρδιαις αυτων[4:15 | instance no. 2]{.aside}

και ουτοι εισιν ομοιως οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και ουτοι εισιν οι εις τας ακανθας σπειρομενοι οι τον [λογον]{.corr} ακουοντες[4:18]{.aside}

και αι μεριμναι του αιωνος τουτου και η απατη του πλουτου και αι περι τα λοιπα επιθυμιαι εισπορευομεναι [συμπνιγουσιν]{.greek-omitted} [συμπνιγουσι]{.greek-added} τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν [οι]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [την]{.greek-omitted} [καλην]{.greek-omitted} [σπαρεντες]{.greek-omitted} [οιτινες]{.greek-omitted} [ακουουσιν]{.greek-omitted} [τον]{.greek-omitted} [λογον]{.greek-omitted} [και]{.greek-omitted} [παραδεχονται]{.greek-omitted} [και]{.greek-omitted} [καρποφορουσιν]{.greek-omitted} [εν]{.greek-omitted} [τριακοντα]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [εξηκοντα]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [εκατον]{.greek-omitted}[4:20]{.aside}

[και]{.greek-omitted} [ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20 | instance no. 2]{.aside}

και ελεγεν αυτοις μητι ο λυχνος ερχεται ινα υπο τον μοδιον τεθη [η]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [κλινην]{.greek-omitted} [ουχ]{.greek-omitted} [ινα]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [λυχνιαν]{.greek-omitted} [επιτεθη]{.greek-omitted}[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον [ο]{.greek-omitted} εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

ει τις εχει ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε μετρηθησεται υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ αν [εχη]{.greek-omitted} [εχει]{.greek-added} δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} ως εαν [ανθρωπος]{.greek-abbr} [βα]{.greek-added} [βαλη]{.greek-omitted} [τον]{.greek-omitted} [σπορον]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted}[4:26]{.aside}

[λη]{.greek-added} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} [ουτως]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [ως]{.greek-omitted} [εαν]{.greek-omitted} [ανθρωπος]{.greek-omitted} [βαλη]{.greek-omitted} τον σπορον επι της γης[4:26 | instance no. 2]{.aside}

και καθευδη και εγειρηται νυκτα και ημεραν και ο σπορος βλαστανη και μηκυνηται ως ουκ οιδεν αυτος[4:27]{.aside}

αυτοματη γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη σιτον εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και ελεγεν τινι ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη παραβαλωμεν αυτην[4:30]{.aside}

ως [κοκκον]{.greek-omitted} [κοκκω]{.greek-added} σιναπεως ος οταν [σπαρη]{.greek-omitted} [σπαρει]{.greek-added} επι της γης [μικροτερος]{.greek-omitted} [μικροτερον]{.greek-added} παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται παντων των λαχανων μειζων [και]{.greek-omitted} [ποιει]{.greek-omitted} [κλαδους]{.greek-omitted} [μεγαλους]{.greek-omitted} [ωστε]{.greek-omitted} [δυνασθαι]{.greek-omitted} [υπο]{.greek-omitted} [την]{.greek-omitted} [σκιαν]{.greek-omitted} [αυτου]{.greek-omitted} [τα]{.greek-omitted} [πετεινα]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted} [κατασκηνουν]{.greek-omitted}[4:32]{.aside}

[και]{.greek-omitted} [οταν]{.greek-omitted} [σπαρη]{.greek-omitted} [αναβαινει]{.greek-omitted} [και]{.greek-omitted} [γινεται]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} [λαχανων]{.greek-omitted} [μειζων]{.greek-omitted} [και]{.greek-omitted} ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του [ουρανου]{.greek-abbr} κατασκηνουν[4:32 | instance no. 2]{.aside}

και τοιαυταις παραβολαις πολλαις [ελαλει]{.greek-omitted} [ελαλη]{.greek-added} αυτοις τον λογον καθως εδυναντο ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου επελυεν παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και αφεντες τον οχλον παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε [πλοιαρια]{.greek-omitted} [πλοια]{.greek-added} ην μετ αυτου[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λαιλαμψ]{.greek-added} ανεμου μεγαλη τα δε κυματα [επεβαλλεν]{.greek-omitted} [επεβαλεν]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος [επι]{.greek-omitted} [τη]{.greek-omitted} [πρυμνη]{.greek-omitted} [επι]{.greek-omitted} [το]{.greek-omitted} [προσκεφαλαιον]{.greek-omitted} [καθευδων]{.greek-omitted} [και]{.greek-omitted} [διεγειρουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [και]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [οτι]{.greek-omitted} [απολλυμεθα]{.greek-omitted}[4:38]{.aside}

[και]{.greek-omitted} [ην]{.greek-omitted} [αυτος]{.greek-omitted} επι τη πρυμνη [[πρυπνη]{.corr}]{.greek-added} επι το προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38 | instance no. 2]{.aside}

και διεγερθεις επετιμησεν [τω]{.greek-omitted} [αυτω]{.greek-added} ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι δειλοι [εστε]{.greek-omitted} [εσται]{.greek-added} ουτως πως ουκ εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον [μεγαν]{.greek-omitted} [μεγα]{.greek-added} και ελεγον προς αλληλους τις αρα ουτος εστιν οτι και ο ανεμος και η θαλασσα υπακουουσιν αυτω[4:41]{.aside}

### Chapter 5

και ηλθον εις το περαν της θαλασσης εις την χωραν των γαδαρηνων[5:1]{.aside}

και εξελθοντι [αυτω]{.greek-omitted} [αυτον]{.greek-added} εκ του πλοιου [ευ]{.greek-added} [ευθεως]{.greek-omitted} [απηντησεν]{.greek-omitted} [αυτω]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [μνημειων]{.greek-omitted} [ανθρωπος]{.greek-omitted} [εν]{.greek-omitted} [πνευματι]{.greek-omitted} [ακαθαρτω]{.greek-omitted}[5:2]{.aside}

[και]{.greek-omitted} [εξελθοντι]{.greek-omitted} [αυτω]{.greek-omitted} [εκ]{.greek-omitted} [του]{.greek-omitted} [πλοιου]{.greek-omitted} [ευθεως]{.greek-omitted} [θεως]{.greek-added} απηντησεν αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν πνευματι ακαθαρτω[5:2 | instance no. 2]{.aside}

ος την κατοικησιν [ειχεν]{.greek-omitted} [ηχεν]{.greek-added} εν τοις [μνημασιν]{.greek-omitted} [μνημασι]{.greek-added} και ουτε αλυσεσιν ουδεις εδυνατο αυτον δησαι[5:3]{.aside}

δια το αυτον πολλακις πεδαις και [αλυσεσιν]{.greek-omitted} [αλυσεσι]{.greek-added} δεδεσθαι και [διεσπασθαι]{.greek-omitted} [διεσπασασθαι]{.greek-added} υπ αυτου τας αλυσεις και τας πεδας συντετριφθαι και ουδεις [ισχυεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημασι]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} [απο]{.greek-omitted} μακροθεν εδραμεν και προσεκυνησεν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και σοι [ιησου]{.greek-omitted} [υιε]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [του]{.greek-omitted} [υψιστου]{.greek-omitted} [ορκιζω]{.greek-omitted} [σε]{.greek-omitted} [τον]{.greek-omitted} [θεον]{.greek-omitted} [μη]{.greek-omitted} [με]{.greek-omitted} [βασανισης]{.greek-omitted}[5:7]{.aside}

[και]{.greek-omitted} [κραξας]{.greek-omitted} [φωνη]{.greek-omitted} [μεγαλη]{.greek-omitted} [ειπεν]{.greek-omitted} [τι]{.greek-omitted} [εμοι]{.greek-omitted} [και]{.greek-omitted} [σοι]{.greek-omitted} [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε [τον]{.greek-omitted} [θεον]{.greek-omitted} [τω]{.greek-added} [[θεω]{.greek-abbr}]{.greek-added} μη με βασανισης[5:7 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το πνευμα το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα [αυτον]{.greek-omitted} [αυτω]{.greek-added} τι [ονομα]{.greek-added} σοι [ονομα]{.greek-omitted} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [[αυ]{.unclear}τω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και παρεκαλει αυτον πολλα ινα μη [αυτους]{.greek-omitted} αποστειλη [αυτον]{.greek-added} εξω της χωρας[5:10]{.aside}

ην δε εκει [προς]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} αγελη χοιρων μεγαλη βοσκομενη [προς]{.greek-added} [το]{.greek-added} [ορει]{.greek-added}[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον [παντες]{.greek-omitted} οι δαιμονες λεγοντες πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις ευθεως ο [ιησους]{.greek-abbr} και εξελθοντα τα πνευματα τα ακαθαρτα εισηλθον εις τους χοιρους και [ορμη]{.greek-added} [ωρμησεν]{.greek-omitted} [η]{.greek-omitted} [αγελη]{.greek-omitted} [κατα]{.greek-omitted} [του]{.greek-omitted} [κρημνου]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted} [ησαν]{.greek-omitted} [δε]{.greek-omitted} [ως]{.greek-omitted} [δισχιλιοι]{.greek-omitted} [και]{.greek-omitted} [επνιγοντο]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [θαλασση]{.greek-omitted}[5:13]{.aside}

[σεν]{.greek-added} [και]{.greek-omitted} [επετρεψεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} [εξελθοντα]{.greek-omitted} [τα]{.greek-omitted} [πνευματα]{.greek-omitted} [τα]{.greek-omitted} [ακαθαρτα]{.greek-omitted} [εισηλθον]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [χοιρους]{.greek-omitted} [και]{.greek-omitted} [ωρμησεν]{.greek-omitted} η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13 | instance no. 2]{.aside}

οι δε βοσκοντες τους χοιρους εφυγον και [ανηγγειλαν]{.greek-omitted} [απηγγειλαν]{.greek-added} εις την πολιν και εις τους αγρους και [εξηλθον]{.greek-omitted} [ηλθον]{.greek-added} ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και [σωφρονουντα]{.greek-omitted} [σοφρονουντα]{.greek-added} τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι [ιδοντες]{.greek-omitted} [ιδοτες]{.greek-added} πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και [εμβαντος]{.greek-omitted} [εμβαινοντος]{.greek-added} αυτου εις το πλοιον παρεκαλει αυτον ο [δαιμονισθεις]{.greek-omitted} [δαιμονισ]{.greek-added} [ινα]{.greek-omitted} [η]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted}[5:18]{.aside}

[και]{.greek-omitted} [εμβαντος]{.greek-omitted} [αυτου]{.greek-omitted} [εις]{.greek-omitted} [θεις]{.greek-added} [το]{.greek-omitted} [πλοιον]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [ο]{.greek-omitted} [δαιμονισθεις]{.greek-omitted} ινα [η]{.greek-omitted} μετ αυτου [η]{.greek-added}[5:18 | instance no. 2]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ [αφηκεν]{.greek-omitted} [ηφηκεν]{.greek-added} αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και αναγγειλον αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} εν τω πλοιω παλιν εις το περαν συνηχθη οχλος πολυς επ [αυτον]{.greek-omitted} [αυτω]{.greek-added} και ην παρα την θαλασσαν[5:21]{.aside}

και ιδου ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον πιπτει προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων επιθης [αυτη]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [οπως]{.greek-omitted} [σωθη]{.greek-omitted} [και]{.greek-omitted} [ζησεται]{.greek-omitted}[5:23]{.aside}

[και]{.greek-omitted} [παρεκαλει]{.greek-omitted} [αυτον]{.greek-omitted} [πολλα]{.greek-omitted} [λεγων]{.greek-omitted} [οτι]{.greek-omitted} [το]{.greek-omitted} [θυγατριον]{.greek-omitted} [μου]{.greek-omitted} [εσχατως]{.greek-omitted} [εχει]{.greek-omitted} [ινα]{.greek-omitted} [ελθων]{.greek-omitted} [επιθης]{.greek-omitted} αυτη τας χειρας οπως σωθη και ζησεται[5:23 | instance no. 2]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και ηκολουθει αυτω οχλος πολυς και συνεθλιβον [αυτον]{.greek-omitted} [αυτω]{.greek-added}[5:24]{.aside}

και γυνη τις ουσα εν ρυσει αιματος ετη δωδεκα[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα παρ [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα εν τω οχλω οπισθεν ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ [εν]{.greek-added} [εαυτη]{.greek-added} οτι καν των ιματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} [ε]{.greek-added} [επιγνους]{.greek-omitted} [εν]{.greek-omitted} [εαυτω]{.greek-omitted} [την]{.greek-omitted} [εξ]{.greek-omitted} [αυτου]{.greek-omitted} [δυναμιν]{.greek-omitted} [εξελθουσαν]{.greek-omitted} [επιστραφεις]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [ελεγεν]{.greek-omitted} [τις]{.greek-omitted} [μου]{.greek-omitted} [ηψατο]{.greek-omitted} [των]{.greek-omitted} [ιματιων]{.greek-omitted}[5:30]{.aside}

[και]{.greek-omitted} [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [επιγνους]{.greek-omitted} [πιγνους]{.greek-added} εν εαυτω την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω ελεγεν τις μου ηψατο των ιματιων[5:30 | instance no. 2]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ [αυτη]{.greek-omitted} [αυτην]{.greek-added} [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την αληθειαν[5:33]{.aside}

ο δε ειπεν αυτη θυγατερ η [πιστις]{.greek-omitted} [πιστι]{.greek-added} σο[υ]{.unclear} [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} [σε]{.greek-omitted} [σαι]{.greek-added} υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [τι]{.greek-omitted} [ετι]{.greek-omitted} [σκυλλεις]{.greek-omitted} [τον]{.greek-omitted} [διδασκαλον]{.greek-omitted}[5:35]{.aside}

[ετι]{.greek-omitted} [αυτου]{.greek-omitted} [λαλουντος]{.greek-omitted} [ερχονται]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [αρχισυναγωγου]{.greek-omitted} [λεγοντες]{.greek-omitted} [οτι]{.greek-omitted} [η]{.greek-omitted} [θυγατηρ]{.greek-omitted} [σου]{.greek-omitted} [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι σκυλλεις τον διδασκαλον[5:35 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} ευθεως ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω [συνακολουθησαι]{.greek-omitted} [ακολουθησαι]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} πετρον και ιακωβον και ιωαννην τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει [αυτοις]{.greek-omitted} [αυτης]{.greek-added} τι θορυβεισθε και κλαιετε το παιδιον ουκ απεθανεν αλλα [καθευδει]{.greek-omitted} [καθευδη]{.greek-added}[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους μετ αυτου και [εισπορευεται]{.greek-omitted} [εισπορευε]{.greek-added} [οπου]{.greek-omitted} [ην]{.greek-omitted} [το]{.greek-omitted} [παιδιον]{.greek-omitted} [ανακειμενον]{.greek-omitted}[5:40]{.aside}

[ται]{.greek-added} [και]{.greek-omitted} [κατεγελων]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [εκβαλων]{.greek-omitted} [παντας]{.greek-omitted} [παραλαμβανει]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [του]{.greek-omitted} [παιδιου]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [μετ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εισπορευεται]{.greek-omitted} οπου ην το παιδιον ανακειμενον[5:40 | instance no. 2]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα κουμι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω [εγειραι]{.greek-omitted} [εγειρε]{.greek-added}[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει μεγαλη[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και ειπεν δοθηναι [αυτη]{.greek-omitted} [αυτην]{.greek-added} φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την πατριδα αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν [τουτω]{.greek-omitted} [ταυτα]{.greek-omitted} [και]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [η]{.greek-omitted} [δοθεισα]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [δυναμεις]{.greek-omitted} [τοιαυται]{.greek-omitted} [δια]{.greek-omitted} [των]{.greek-omitted} [χειρων]{.greek-omitted} [αυτου]{.greek-omitted} [γινονται]{.greek-omitted}[6:2]{.aside}

[και]{.greek-omitted} [γενομενου]{.greek-omitted} [σαββατου]{.greek-omitted} [ηρξατο]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [συναγωγη]{.greek-omitted} [διδασκειν]{.greek-omitted} [και]{.greek-omitted} [πολλοι]{.greek-omitted} [ακουοντες]{.greek-omitted} [εξεπλησσοντο]{.greek-omitted} [λεγοντες]{.greek-omitted} [ποθεν]{.greek-omitted} τουτω ταυτα [ινα]{.greek-added} [και]{.greek-omitted} [τις]{.greek-omitted} [η]{.greek-omitted} [σοφια]{.greek-omitted} [η]{.greek-omitted} [δοθεισα]{.greek-omitted} [αυτω]{.greek-omitted} και δυναμεις τοιαυται δια των χειρων αυτου [γινονται]{.greek-omitted} [γινωνται]{.greek-added}[6:2 | instance no. 2]{.aside}

ουχ ουτος εστιν ο τεκτων ο υιος μαριας αδελφος δε ιακωβου και ιωση και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις ο [ιησους]{.greek-abbr} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει [μη]{.greek-omitted} [μι]{.greek-added} εν τη πατριδι αυτου και εν τοις [συγγεν[―]{.gap}σι]{.greek-added} [συγγενεσιν]{.greek-omitted} [[συγγενεσι]{.corr}]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ [ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} εκει ουδεμιαν δυναμιν ποιησαι ει μη ολιγοις αρρωστοις επιθεις τας χειρας [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added}[6:5]{.aside}

και εθαυμαζεν δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας κωμας κυκλω διδασκων[6:6]{.aside}

και [προσ]{.greek-added} [προσκαλειται]{.greek-omitted} [τους]{.greek-omitted} [δωδεκα]{.greek-omitted} [και]{.greek-omitted} [ηρξατο]{.greek-omitted} [αυτους]{.greek-omitted} [αποστελλειν]{.greek-omitted} [δυο]{.greek-omitted} [δυο]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [αυτοις]{.greek-omitted} [εξουσιαν]{.greek-omitted} [των]{.greek-omitted} [πνευματων]{.greek-omitted} [των]{.greek-omitted} [ακαθαρτων]{.greek-omitted}[6:7]{.aside}

[και]{.greek-omitted} [προσκαλειται]{.greek-omitted} [καλειται]{.greek-added} τους δωδεκα και ηρξατο αυτους αποστελλειν δυο δυο και εδιδου αυτοις εξουσιαν των πνευματων των ακαθαρτων[6:7 | instance no. 2]{.aside}

και παρηγγειλεν αυτοις ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

αλλ υποδεδεμενους σανδαλια και μη [ενδυσησθε]{.greek-omitted} [ενδυσασθε]{.greek-added} δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου εαν εισελθητε [εις]{.greek-omitted} [οικιαν]{.greek-omitted} [εκει]{.greek-omitted} [μενετε]{.greek-omitted} [εως]{.greek-omitted} [αν]{.greek-omitted} [εξελθητε]{.greek-omitted} εκειθεν[6:10]{.aside}

και οσοι [αν]{.greek-omitted} [εαν]{.greek-added} μη [δεξονται]{.greek-added} [δεξωνται]{.corr} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε [και]{.greek-added} τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις αμην λεγω υμιν ανεκτοτερον εσται σοδομοις η [γομορροις]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [εκεινη]{.greek-omitted}[6:11]{.aside}

[και]{.greek-omitted} [οσοι]{.greek-omitted} [αν]{.greek-omitted} [μη]{.greek-omitted} [δεξωνται]{.greek-omitted} [υμας]{.greek-omitted} [μηδε]{.greek-omitted} [ακουσωσιν]{.greek-omitted} [υμων]{.greek-omitted} [εκπορευομενοι]{.greek-omitted} [εκειθεν]{.greek-omitted} [εκτιναξατε]{.greek-omitted} [τον]{.greek-omitted} [χουν]{.greek-omitted} [τον]{.greek-omitted} [υποκατω]{.greek-omitted} [των]{.greek-omitted} [ποδων]{.greek-omitted} [υμων]{.greek-omitted} [εις]{.greek-omitted} [μαρτυριον]{.greek-omitted} [αυτοις]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [η]{.greek-omitted} γομορροις εν ημερα κρισεως η τη πολει εκεινη[6:11 | instance no. 2]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι ιωαννης ο βαπτιζων εκ νεκρων [ηγερθη]{.greek-omitted} [ανεστη]{.greek-added} και δια τουτο [ενεργουσιν]{.greek-omitted} αι δυναμεις [ενεργουσιν]{.greek-added} εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω [απεκεφαλισα]{.greek-omitted} [απεκεφαλησα]{.greek-added} ιωαννην ουτος εστιν αυτος ηγερθη [εκ]{.greek-omitted} [απο]{.greek-added} [των]{.greek-added} νεκρων[6:16]{.aside}

αυτος [γαρ]{.greek-omitted} [δε]{.greek-added} ο [ηρω]{.greek-added} [ηρωδης]{.greek-omitted} [αποστειλας]{.greek-omitted} [εκρατησεν]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [και]{.greek-omitted} [εδησεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [φυλακη]{.greek-omitted} [δια]{.greek-omitted} [ηρωδιαδα]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [φιλιππου]{.greek-omitted} [του]{.greek-omitted} [αδελφου]{.greek-omitted} [αυτου]{.greek-omitted} [οτι]{.greek-omitted} [αυτην]{.greek-omitted} [εγαμησεν]{.greek-omitted}[6:17]{.aside}

[δης]{.greek-added} [αυτος]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ηρωδης]{.greek-omitted} αποστειλας εκρατησεν [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [και]{.greek-omitted} [εδησεν]{.greek-omitted} αυτον εν φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17 | instance no. 2]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο ιωαννης τω ηρωδη οτι ουκ εξεστιν σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ [ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added}[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον ιωαννην ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως [αυτου]{.greek-omitted} [αυτον]{.greek-added} ηκουεν[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον εποιει τοις μεγιστασιν αυτου και τοις [χιλι]{.greek-added} [χιλιαρχοις]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [πρωτοις]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted}[6:21]{.aside}

[και]{.greek-omitted} [γενομενης]{.greek-omitted} [ημερας]{.greek-omitted} [ευκαιρου]{.greek-omitted} [οτε]{.greek-omitted} [ηρωδης]{.greek-omitted} [τοις]{.greek-omitted} [γενεσιοις]{.greek-omitted} [αυτου]{.greek-omitted} [δειπνον]{.greek-omitted} [εποιει]{.greek-omitted} [τοις]{.greek-omitted} [μεγιστασιν]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [χιλιαρχοις]{.greek-omitted} [αρχοις]{.greek-added} και τοις πρωτοις της γαλιλαιας[6:21 | instance no. 2]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και ορχησαμενης και αρεσασης τω ηρωδη και τοις συνανακειμενοις ειπεν ο βασιλευς τω κορασιω αιτησον [μοι]{.greek-added} [με]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [θελης]{.greek-omitted} και δωσω σοι[6:22]{.aside}

[και]{.greek-omitted} [ωμοσεν]{.greek-omitted} [αυτη]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [με]{.greek-omitted} [αιτησης]{.greek-omitted} [δωσω]{.greek-omitted} [σοι]{.greek-omitted} εως [ημισους]{.greek-omitted} [ημισου]{.greek-added} της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε ειπεν την κεφαλην ιωαννου του βαπτιστου[6:24]{.aside}

και εισελθουσα ευθεως μετα σπουδης προς τον βασιλεα ητησατο λεγουσα θελω ινα [μοι]{.greek-omitted} [μη]{.greek-added} δως εξαυτης επι πινακι την κεφαλην ιωαννου του βαπτιστου[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και [τους]{.greek-omitted} [συνανακειμενους]{.greek-omitted} [ουκ]{.greek-omitted} [ηθελησεν]{.greek-omitted} [αυτην]{.greek-omitted} [αθετησαι]{.greek-omitted}[6:26]{.aside}

[και]{.greek-omitted} [περιλυπος]{.greek-omitted} [γενομενος]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [δια]{.greek-omitted} [τους]{.greek-omitted} [ορκους]{.greek-omitted} [και]{.greek-omitted} τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26 | instance no. 2]{.aside}

και ευθεως [αποστειλας]{.greek-omitted} ο βασιλευς [αποστειλας]{.greek-added} σπεκουλατορα επεταξεν ενεχθηναι [αυτου]{.greek-added} την κεφαλην [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτου]{.greek-omitted} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [φυλακη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγγε]{.greek-added} την κεφαλην αυτου επι πινακι και εδωκεν [αυτην]{.greek-omitted} τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-omitted} [[ιησου]{.greek-abbr}]{.greek-added} και [απηγγειλαν]{.greek-omitted} [απηγγηλαν]{.greek-added} αυτω παντα και οσα [εποιησαν]{.greek-omitted} [εδιδαξαν]{.greek-added} και οσα [εδιδαξαν]{.greek-omitted} [εποιησαν]{.greek-added}[6:30]{.aside}

και ειπεν αυτοις δευτε υμεις αυτοι κατ ιδιαν [[εις]{.greek-supplied}]{.corr} [[ερ]{.greek-supplied}ημον]{.corr} [τοπον]{.corr} [και]{.corr} [αναπαυεσθε]{.greek-omitted} [[αναπαυσ[ασθ]{.unclear}ε]{.corr}]{.greek-added} [ολιγον]{.corr} [ησαν]{.corr} [[γαρ]{.greek-supplied}]{.corr} [[οι]{.greek-supplied}]{.corr} [ερχομενοι]{.corr} [[κα]{.unclear}ι]{.corr} [οι]{.greek-omitted} [υπαγοντες]{.corr} [πολλοι]{.corr} [και]{.corr} [ου[δε]{.unclear}]{.corr} [[φα]{.unclear}[γειν]{.greek-supplied}]{.corr} [[ε]{.greek-supplied}υκαιρουν]{.corr}[6:31]{.aside}

[[και]{.unclear}]{.corr} [απηλθ[ο]{.unclear}ν]{.corr} [εις]{.corr} [ερημον]{.corr} [τοπον]{.corr} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} [[κα]{.greek-supplied}τ]{.corr} [[ιδιαν]{.greek-supplied}]{.corr}[6:32]{.aside}

και [ειδον]{.greek-omitted} [ιδον]{.greek-added} αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} [αυτους]{.greek-added} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και [προηλθον]{.greek-omitted} [προσηλθον]{.greek-added} αυτους και συνηλθον προς αυτον[6:33]{.aside}

και εξελθων [ειδεν]{.greek-omitted} ο [ιησους]{.greek-abbr} [ιδε]{.greek-added} πολυν οχλον και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο [αυτους]{.greek-added} διδασκειν [αυτους]{.greek-omitted} πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες [αυτω]{.greek-omitted} οι μαθηται αυτου λεγουσιν [αυτω]{.greek-added} οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εα[υ]{.unclear}τοις αρτους τι γαρ φαγωσιν ουκ [εχουσιν]{.greek-omitted} [ε]{.greek-added}[6:36]{.aside}

[απολυσον]{.greek-omitted} [αυτους]{.greek-omitted} [ινα]{.greek-omitted} [απελθοντες]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [κυκλω]{.greek-omitted} [αγρους]{.greek-omitted} [και]{.greek-omitted} [κωμας]{.greek-omitted} [αγορασωσιν]{.greek-omitted} [εαυτοις]{.greek-omitted} [αρτους]{.greek-omitted} [τι]{.greek-omitted} [γαρ]{.greek-omitted} [φαγωσιν]{.greek-omitted} [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted} [χουσιν]{.greek-added}[6:36 | instance no. 2]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες αγορασωμεν [δηριων]{.greek-added} [δηναριων]{.corr} διακοσιων αρτους [και]{.greek-omitted} δωμεν αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους αρτους εχετε υπαγετε και ιδετε και γνοντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια επι τω χλωρω χορτω[6:39]{.aside}

και ανεπεσον πρασιαι πρασιαι ανα εκατον [και]{.greek-omitted} [ανα]{.greek-omitted} πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ευλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παρατιθωσιν]{.greek-added} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [εμερισεν]{.greek-omitted} [πασιν]{.greek-omitted}[6:41]{.aside}

[και]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [δυο]{.greek-omitted} [ιχθυας]{.greek-omitted} [αναβλεψας]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ουρανον]{.greek-omitted} [ευλογησεν]{.greek-omitted} [και]{.greek-omitted} [κατεκλασεν]{.greek-omitted} [τους]{.greek-omitted} [αρτους]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [παραθωσιν]{.greek-omitted} αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41 | instance no. 2]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [κλασματων]{.greek-omitted} [κλασματα]{.greek-added} δωδεκα κοφινους πληρεις και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες τους αρτους πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου [εμβηναι]{.greek-omitted} [εμβην]{.greek-added} εις το πλοιον και προαγειν εις το περαν προς βηθσαιδαν εως αυτος απολυση τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας γενομενης ην το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} αυτους βασανιζομενους εν τω [ελαυνειν]{.greek-omitted} [ελαυειν]{.greek-added} ην γαρ ο ανεμος [εναντιος]{.greek-omitted} [εναντι]{.greek-added} [αυτοις]{.greek-omitted} [και]{.greek-omitted} [περι]{.greek-omitted} [τεταρτην]{.greek-omitted} [φυλακην]{.greek-omitted} [της]{.greek-omitted} [νυκτος]{.greek-omitted} [ερχεται]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [περιπατων]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [θαλασσης]{.greek-omitted} [και]{.greek-omitted} [ηθελεν]{.greek-omitted} [παρελθειν]{.greek-omitted} [αυτους]{.greek-omitted}[6:48]{.aside}

[ος]{.greek-added} [και]{.greek-omitted} [ειδεν]{.greek-omitted} [αυτους]{.greek-omitted} [βασανιζομενους]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ελαυνειν]{.greek-omitted} [ην]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [ανεμος]{.greek-omitted} [εναντιος]{.greek-omitted} αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και ηθελεν παρελθειν αυτους[6:48 | instance no. 2]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης εδοξαν φαντασμα ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον [ειδον]{.greek-omitted} [ιδον]{.greek-added} και εταραχθησαν και ευθεως ελαλησεν μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη φοβεισθε[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και λιαν [εκ]{.greek-added} [εκπερισσου]{.greek-omitted} [περισσου]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ αυτων η καρδια πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον επι την γην [γεν]{.greek-added} [γεννησαρετ]{.greek-omitted} [και]{.greek-omitted} [προσωρμισθησαν]{.greek-omitted}[6:53]{.aside}

[και]{.greek-omitted} [διαπερασαντες]{.greek-omitted} [ηλθον]{.greek-omitted} [επι]{.greek-omitted} [την]{.greek-omitted} [γην]{.greek-omitted} [γεννησαρετ]{.greek-omitted} [νησαρετ]{.greek-added} και προσωρμισθησαν[6:53 | instance no. 2]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι τοις κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι εκει [εστιν]{.greek-omitted} [εστι]{.greek-added}[6:55]{.aside}

και οπου [αν]{.greek-omitted} εισεπορευετο εις κωμας η πολεις η αγρους εν [ταις]{.greek-omitted} [τες]{.greek-added} αγοραις ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των [μαθη]{.greek-added} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [κοιναις]{.greek-omitted} [χερσιν]{.greek-omitted} [τουτ]{.greek-omitted} [εστιν]{.greek-omitted} [ανιπτοις]{.greek-omitted} [εσθιοντας]{.greek-omitted} [αρτους]{.greek-omitted} [εμεμψαντο]{.greek-omitted}[7:2]{.aside}

[και]{.greek-omitted} [ιδοντες]{.greek-omitted} [τινας]{.greek-omitted} των [μαθητων]{.greek-omitted} αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας [αρτους]{.greek-omitted} [αρτοις]{.greek-added} εμεμψαντο[7:2 | instance no. 2]{.aside}

οι [γαρ]{.greek-omitted} φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη [νιψοντε]{.greek-added} [νιψωνται]{.corr} τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την [παραδοσιν]{.greek-omitted} [παραδοσι]{.greek-added} των πρεσβυτερων[7:3]{.aside}

και [απο]{.greek-omitted} [απ]{.greek-added} αγορας εαν μη βαπτισωνται ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα [εστιν]{.greek-omitted} [εστι]{.greek-added} α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

επειτα επερωτωσιν αυτον οι φαρισαιοι και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την [παραδοσιν]{.greek-omitted} [παραδοσι]{.greek-added} των πρεσβυτερων αλλα ανιπτοις χερσιν εσθιουσιν [τον]{.greek-omitted} αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις [οτι]{.greek-omitted} [καλως]{.greek-omitted} [προεφητευσεν]{.greek-omitted} [ησαιας]{.greek-omitted} [περι]{.greek-omitted} [υμων]{.greek-omitted} [των]{.greek-omitted} [υποκριτων]{.greek-omitted} [ως]{.greek-omitted} [γεγραπται]{.greek-omitted} [ουτος]{.greek-omitted} [ο]{.greek-omitted} [λαος]{.greek-omitted} [τοις]{.greek-omitted} [χειλεσιν]{.greek-omitted} [με]{.greek-omitted} [τιμα]{.greek-omitted} [η]{.greek-omitted} [δε]{.greek-omitted} [καρδια]{.greek-omitted} [αυτων]{.greek-omitted} [πορρω]{.greek-omitted} [απεχει]{.greek-omitted} [απ]{.greek-omitted} [εμου]{.greek-omitted}[7:6]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6 | instance no. 2]{.aside}

ματην δε σεβονται με διδασκοντες διδασκαλιας ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν [[παραδοσι]{.corr}]{.greek-added} των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα παρομοια τοιαυτα [ποιειτε]{.greek-added} πολλα [ποιειτε]{.greek-omitted}[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων τηρησητε[7:9]{.aside}

μωσης γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε [λεγετε]{.greek-omitted} [εαν]{.greek-omitted} [ειπη]{.greek-omitted} [ανθρωπος]{.greek-omitted} [τω]{.greek-omitted} [πατρι]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [μητρι]{.greek-omitted} [κορβαν]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [δωρον]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [εξ]{.greek-omitted} [εμου]{.greek-omitted} [ωφεληθης]{.greek-omitted}[7:11]{.aside}

[υμεις]{.greek-omitted} [δε]{.greek-omitted} λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11 | instance no. 2]{.aside}

και ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} αυτου η τη [μητρι]{.greek-abbr} αυτου[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και παρομοια τοιαυτα πολλα ποιειτε[7:13]{.aside}

και προσκαλεσαμενος παντα τον [οχχλον]{.greek-added} [οχλον]{.corr} ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν εις οικον απο του οχλου [επη]{.greek-added} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [μαθηται]{.greek-omitted} [αυτου]{.greek-omitted} [περι]{.greek-omitted} [της]{.greek-omitted} [παραβολης]{.greek-omitted}[7:17]{.aside}

[και]{.greek-omitted} [οτε]{.greek-omitted} [εισηλθεν]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [οχλου]{.greek-omitted} [επηρωτων]{.greek-omitted} [ρωτων]{.greek-added} αυτον οι μαθηται αυτου περι της παραβολης[7:17 | instance no. 2]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται [καθαριζον]{.greek-omitted} [καθαριζων]{.greek-added} παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

[εσωθεν]{.greek-omitted} [εσωθε]{.greek-added} γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι φονοι [κλοπαι]{.greek-added}[7:21]{.aside}

[κλοπαι]{.greek-omitted} πλεονεξιαι [πονηριαι]{.greek-omitted} δολος ασελγεια οφθαλμος πονηρος βλασφημια [υπερηφανια]{.greek-omitted} [υπερηφα]{.greek-added} [αφροσυνη]{.greek-omitted}[7:22]{.aside}

[νια]{.greek-added} [κλοπαι]{.greek-omitted} [πλεονεξιαι]{.greek-omitted} [πονηριαι]{.greek-omitted} [δολος]{.greek-omitted} [ασελγεια]{.greek-omitted} [οφθαλμος]{.greek-omitted} [πονηρος]{.greek-omitted} [βλασφημια]{.greek-omitted} [υπερηφανια]{.greek-omitted} αφροσυνη[7:22 | instance no. 2]{.aside}

παντα ταυτα [τα]{.greek-omitted} πονηρα εσωθεν εκπορευεται και κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα μεθορια τυρου και σιδωνος και εισελθων εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ [ηδυνηθη]{.greek-omitted} [εδυνηθη]{.greek-added} λαθειν[7:24]{.aside}

ακουσασα [γαρ]{.greek-omitted} γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το θυγατριον αυτης πνευμα ακαθαρτον ελθουσα [προσεπεσεν]{.greek-omitted} [προσεπεσε]{.greek-added} προς τους ποδας αυτου[7:25]{.aside}

ην δε [η]{.greek-omitted} γυνη ελληνις [συραφοινικισσα]{.greek-omitted} [συροφοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον εκβαλη εκ της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτη αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν τοις [κυναριοις]{.greek-omitted} [κυ]{.greek-added}[7:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτη]{.greek-omitted} [αφες]{.greek-omitted} [πρωτον]{.greek-omitted} [χορτασθηναι]{.greek-omitted} [τα]{.greek-omitted} [τεκνα]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [λαβειν]{.greek-omitted} [τον]{.greek-omitted} [αρτον]{.greek-omitted} [των]{.greek-omitted} [τεκνων]{.greek-omitted} [και]{.greek-omitted} [βαλειν]{.greek-omitted} [τοις]{.greek-omitted} [κυναριοις]{.greek-omitted} [ναριοις]{.greek-added}[7:27 | instance no. 2]{.aside}

η δε απεκριθη και λεγει αυτω ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης εσθιει απο των [ψυχιων]{.greek-added} [ψιχιων]{.corr} των παιδιων[7:28]{.aside}

και ειπεν αυτη δια τουτον τον λογον υπαγε εξεληλυθεν το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και σιδωνος [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς την [θαλασσαν]{.greek-omitted} [θαλασσα]{.greek-added} της γαλιλαιας ανα μεσον των οριων δεκαπολεως[7:31]{.aside}

και φερουσιν [αυτω]{.greek-omitted} [αυτο]{.greek-added} [κωφον]{.greek-omitted} [κοφω]{.greek-added} [μογγιλαλον]{.greek-omitted} [μογιλαλω]{.greek-added} και παρακαλουσιν αυτον ινα επιθη [αυ]{.greek-added} [αυτω]{.greek-omitted} [την]{.greek-omitted} [χειρα]{.greek-omitted}[7:32]{.aside}

[τω]{.greek-added} [και]{.greek-omitted} [φερουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [κωφον]{.greek-omitted} [μογγιλαλον]{.greek-omitted} [και]{.greek-omitted} [παρακαλουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [ινα]{.greek-omitted} [επιθη]{.greek-omitted} [αυτω]{.greek-omitted} την χειρα[7:32 | instance no. 2]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου εις τα ωτα αυτου και πτυσας ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και διεστειλατο αυτοις ινα μηδενι ειπωσιν οσον δε αυτος αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} και τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις ταις ημεραις [παμπολου]{.greek-added} [παμπολλου]{.corr} οχλου [ον]{.greek-added} [οντος]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [εχοντων]{.greek-omitted} [τι]{.greek-omitted} [φαγωσιν]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [τους]{.greek-omitted} [μαθητας]{.greek-omitted} [αυτου]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted}[8:1]{.aside}

[εν]{.greek-omitted} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted} [παμπολλου]{.greek-omitted} [οχλου]{.greek-omitted} [οντος]{.greek-omitted} [τος]{.greek-added} και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1 | instance no. 2]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους νηστεις εις οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκουσι]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν τουτους δυνησεται τις ωδε χορτασαι αρτων επ ερημιας[8:4]{.aside}

και [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλε]{.greek-added} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [τον]{.greek-added} [οχλον]{.greek-added} αναπεσειν επι της γης και λαβων τους επτα αρτους ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδιδου τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και [πα]{.greek-added} [παρεθηκαν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted}[8:6]{.aside}

[ρεθηκαν]{.greek-added} [και]{.greek-omitted} [παρηγγειλεν]{.greek-omitted} τω οχλω [αναπεσειν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [λαβων]{.greek-omitted} [τους]{.greek-omitted} [επτα]{.greek-omitted} [αρτους]{.greek-omitted} [ευχαριστησας]{.greek-omitted} [εκλασεν]{.greek-omitted} [και]{.greek-omitted} [εδιδου]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ινα]{.greek-omitted} [παραθωσιν]{.greek-omitted} [και]{.greek-omitted} [παρεθηκαν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted}[8:6 | instance no. 2]{.aside}

και ειχον ιχθυδια ολιγα και [ταυτα]{.greek-added} ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [παραθειναι]{.greek-omitted} [παραθηναι]{.greek-added} και αυτα[8:7]{.aside}

εφαγον δε και εχορτασθησαν [παντες]{.greek-added} και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [εμβας]{.greek-added} ευθεως [εμβας]{.greek-omitted} εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη δαλμανουθα[8:10]{.aside}

και εξηλθον οι φαρισαιοι [και]{.greek-omitted} [ηρξαντο]{.greek-omitted} [ηραντο]{.greek-added} συζητειν αυτω ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζοντες αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} αυτου λεγει τι η γενεα αυτη σημειον επιζητει αμην λεγω υμιν ει δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους [εμβας]{.greek-omitted} [παλιν]{.greek-omitted} [εις]{.greek-omitted} [πλοιον]{.greek-omitted} [απηλθεν]{.greek-omitted} [εις]{.greek-omitted} [το]{.greek-omitted} [περαν]{.greek-omitted}[8:13]{.aside}

[και]{.greek-omitted} [αφεις]{.greek-omitted} [αυτους]{.greek-omitted} εμβας παλιν εις [το]{.greek-added} πλοιον απηλθεν εις το περαν[8:13 | instance no. 2]{.aside}

και επελαθοντο λαβειν αρτους και ει [μη]{.greek-omitted} [μι]{.greek-added} ενα αρτον ουκ ειχον μεθ εαυτων εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων ορατε βλεπετε απο της ζυμης των φαρισαιων και της ζυμης ηρωδου[8:15]{.aside}

[και]{.greek-omitted} διελογιζοντο προς αλληλους λεγοντες οτι αρτους ουκ εχομεν[8:16]{.aside}

και γνους ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ [εχετε]{.greek-omitted} [εχομεν]{.greek-added} ουπω νοειτε ουδε συνιετε ετι πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε και ου μνημονευετε[8:18]{.aside}

οτε τους πεντε αρτους εκλασα εις τους [πεντακισχιλιους]{.greek-omitted} [πεντακισχι]{.greek-added} [ποσους]{.greek-omitted} [κοφινους]{.greek-omitted} [πληρεις]{.greek-omitted} [κλασματων]{.greek-omitted} [ηρατε]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [δωδεκα]{.greek-omitted}[8:19]{.aside}

[λιους]{.greek-added} [οτε]{.greek-omitted} [τους]{.greek-omitted} [πεντε]{.greek-omitted} [αρτους]{.greek-omitted} [εκλασα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [πεντακισχιλιους]{.greek-omitted} ποσους κοφινους πληρεις κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19 | instance no. 2]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων πληρωματα κλασματων ηρατε οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις [ουπω]{.greek-added} [πως]{.greek-omitted} [ου]{.greek-omitted} συνιετε[8:21]{.aside}

και ερχεται εις βηθσαιδαν και φερουσιν αυτω τυφλον και παρακαλουσιν [αυτω]{.greek-added} [ινα]{.greek-added} αυτον [ινα]{.greek-omitted} [αυτου]{.greek-omitted} αψηται[8:22]{.aside}

και επιλαβομενος της χειρος του τυφλου εξηγαγεν αυτον εξω της κωμης και πτυσας εις τα ομματα αυτου επιθεις τας χειρας [αυτω]{.greek-omitted} [αυτου]{.greek-added} επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας ελεγεν βλεπω τους [ανθρωπους]{.greek-abbr} οτι ως δενδρα ορω [περιπατουντας]{.greek-omitted} [περιπατουν]{.greek-added}[8:24]{.aside}

[τας]{.greek-added} [και]{.greek-omitted} [αναβλεψας]{.greek-omitted} [ελεγεν]{.greek-omitted} [βλεπω]{.greek-omitted} [τους]{.greek-omitted} [ανθρωπους]{.greek-omitted} [οτι]{.greek-omitted} [ως]{.greek-omitted} [δενδρα]{.greek-omitted} [ορω]{.greek-omitted} [περιπατουντας]{.greek-omitted}[8:24 | instance no. 2]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας επι τους οφθαλμους αυτου και εποιησεν αυτον αναβλεψαι και αποκατεσταθη και [ενεβλεψεν]{.greek-omitted} [εβλεψαι]{.greek-added} τηλαυγως απαντας[8:25]{.aside}

και απεστειλεν αυτον εις [τον]{.greek-omitted} οικον αυτου λεγων μηδε εις την κωμην εισελθης μηδε ειπης τινι εν τη κωμη[8:26]{.aside}

και εξηλθεν ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν ιωαννην τον βαπτιστην και αλλοι ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

και αυτος λεγει αυτοις [υ]{.greek-added} [υμεις]{.greek-omitted} [δε]{.greek-omitted} [τινα]{.greek-omitted} [με]{.greek-omitted} [λεγετε]{.greek-omitted} [ειναι]{.greek-omitted} [αποκριθεις]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [συ]{.greek-omitted} [ει]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted}[8:29]{.aside}

[και]{.greek-omitted} [αυτος]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [υμεις]{.greek-omitted} [μεις]{.greek-added} δε τινα με λεγετε ειναι αποκριθεις [δε]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29 | instance no. 2]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγουσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι [δει]{.greek-omitted} [δ[―]{.gap}]{.greek-added} [[δη]{.corr}]{.greek-added} τον υιον του [ανθρωπου]{.greek-abbr} πολλα παθειν και αποδοκιμασθηναι [απο]{.greek-omitted} [υπο]{.greek-added} των πρεσβυτερων και [των]{.greek-omitted} αρχιερεων και [των]{.greek-omitted} [γραμματεων]{.greek-omitted} [γραμματαιων]{.greek-added} και αποκτανθηναι και μετα τρεις ημερας αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν [αυτω]{.greek-omitted} [αυτον]{.greek-added}[8:32]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε [σατανα]{.greek-added} οπισω μου [σατανα]{.greek-omitted} οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον [οχλον]{.greek-omitted} [συν]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [οστις]{.greek-omitted} [θελει]{.greek-omitted} [οπισω]{.greek-omitted} [μου]{.greek-omitted} [ακολουθειν]{.greek-omitted} [απαρνησασθω]{.greek-omitted} [εαυτον]{.greek-omitted} [και]{.greek-omitted} [αρατω]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ακολουθειτω]{.greek-omitted} [μοι]{.greek-omitted}[8:34]{.aside}

[και]{.greek-omitted} [προσκαλεσαμενος]{.greek-omitted} [τον]{.greek-omitted} οχλον συν τοις μαθηταις αυτου ειπεν αυτοις οστις θελει οπισω μου [ακολουθειν]{.greek-omitted} [ελθειν]{.greek-added} [απαρησασθω]{.greek-added} [απαρνησασθω]{.corr} εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34 | instance no. 2]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [τον]{.greek-added} [ανθρωπον]{.greek-abbr} εαν κερδηση τον κοσμον ολον και [ζημιωθη]{.greek-omitted} [ζημειωθη]{.greek-added} την ψυχην αυτου[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με [και]{.greek-omitted} τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο υιος του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη [του]{.greek-omitted} [πατρος]{.greek-omitted} αυτου [με]{.greek-added} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} [των]{.greek-omitted} [αγιων]{.greek-omitted}[8:38]{.aside}

[τα]{.greek-added} [ος]{.greek-omitted} [γαρ]{.greek-omitted} [εαν]{.greek-omitted} [επαισχυνθη]{.greek-omitted} [με]{.greek-omitted} [και]{.greek-omitted} [τους]{.greek-omitted} [εμους]{.greek-omitted} [λογους]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [γενεα]{.greek-omitted} [ταυτη]{.greek-omitted} [τη]{.greek-omitted} [μοιχαλιδι]{.greek-omitted} [και]{.greek-omitted} [αμαρτωλω]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [επαισχυνθησεται]{.greek-omitted} [αυτον]{.greek-omitted} [οταν]{.greek-omitted} [ελθη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [δοξη]{.greek-omitted} [του]{.greek-omitted} [πατρος]{.greek-omitted} [αυτου]{.greek-omitted} [μετα]{.greek-omitted} των αγγελων των αγιων[8:38 | instance no. 2]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη γευσωνται θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και [τον]{.greek-added} ιωαννην και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν [ως]{.greek-omitted} [ωσει]{.greek-added} χιων οια [γναφευς]{.greek-omitted} [κναφευς]{.greek-added} επι της γης ου δυναται λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος λεγει τω [ιησου]{.greek-abbr} [ραββι]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [ημας]{.greek-omitted} [ωδε]{.greek-omitted} [ειναι]{.greek-omitted} [και]{.greek-omitted} [ποιησωμεν]{.greek-omitted} [σκηνας]{.greek-omitted} [τρεις]{.greek-omitted} [σοι]{.greek-omitted} [μιαν]{.greek-omitted} [και]{.greek-omitted} [μωση]{.greek-omitted} [μιαν]{.greek-omitted} [και]{.greek-omitted} [ηλια]{.greek-omitted} [μιαν]{.greek-omitted}[9:5]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} ραββι καλον εστιν ημας ωδε ειναι και ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυση]{.greek-added} μιαν και ηλια μιαν[9:5 | instance no. 2]{.aside}

ου γαρ ηδει τι λαλησει ησαν γαρ [εκφοβοι]{.greek-omitted} [εμφοβοι]{.greek-added}[9:6]{.aside}

και εγενετο νεφελη επισκιαζουσα αυτοις και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} φωνη εκ της νεφελης ουτος εστιν ο υιος μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα [ειδον]{.greek-omitted} [ιδον]{.greek-added} αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι διηγησωνται α [ειδον]{.greek-omitted} [ιδον]{.greek-added} ει [μη]{.greek-omitted} [μι]{.greek-added} οταν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και επηρωτων αυτον λεγοντες [οτι]{.greek-omitted} [λεγουσιν]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} [οτι]{.greek-omitted} [ηλιαν]{.greek-omitted} [δει]{.greek-omitted} [ελθειν]{.greek-omitted} [πρωτον]{.greek-omitted}[9:11]{.aside}

[και]{.greek-omitted} [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} [λεγοντες]{.greek-omitted} οτι λεγουσιν οι γραμματεις οτι ηλιαν δει ελθειν πρωτον[9:11 | instance no. 2]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας μεν ελθων πρωτον αποκαθιστα παντα [καθως]{.greek-added} [και]{.greek-omitted} [πως]{.greek-omitted} γεγραπται επι τον υιον του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και εξουδενωθη[9:12]{.aside}

αλλα λεγω υμιν οτι και ηλιας [εληλυθεν]{.greek-omitted} [εληλυθε]{.greek-added} και εποιησαν [εν]{.greek-added} αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας [ειδεν]{.greek-omitted} [ιδεν]{.greek-added} οχλον πολυν περι αυτους και γραμματεις συζητουντας αυτοις[9:14]{.aside}

και ευθεως πας ο οχλος ιδων αυτον εξεθαμβηθη και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και επηρωτησεν τους γραμματεις τι [συζητειτε]{.greek-omitted} [ζητειτε]{.greek-added} προς αυτους[9:16]{.aside}

και αποκριθεις εις [εκ]{.greek-omitted} [του]{.greek-omitted} [οχλου]{.greek-omitted} [ειπεν]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ηνεγκα]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [μου]{.greek-omitted} [προς]{.greek-omitted} [σε]{.greek-omitted} [εχοντα]{.greek-omitted} [πνευμα]{.greek-omitted} [αλαλον]{.greek-omitted}[9:17]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [εις]{.greek-omitted} εκ του οχλου ειπεν διδασκαλε ηνεγκα τον υιον μου προς σε εχοντα πνευμα αλαλον[9:17 | instance no. 2]{.aside}

και οπου [αν]{.greek-omitted} [εαν]{.greek-added} αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας αυτου και ξηραινεται και ειπον τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

ο δε αποκριθεις [αυτω]{.greek-omitted} [αυτοις]{.greek-added} λεγει ω γενεα απιστος εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το πνευμα εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} [τον]{.greek-omitted} [το]{.greek-added} [πατερα]{.greek-abbr} αυτου ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε ειπεν [παιδιοθεν]{.greek-omitted} [παι]{.greek-added}[9:21]{.aside}

[και]{.greek-omitted} [επηρωτησεν]{.greek-omitted} [τον]{.greek-omitted} [πατερα]{.greek-omitted} [αυτου]{.greek-omitted} [ποσος]{.greek-omitted} [χρονος]{.greek-omitted} [εστιν]{.greek-omitted} [ως]{.greek-omitted} [τουτο]{.greek-omitted} [γεγονεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ειπεν]{.greek-omitted} [παιδιοθεν]{.greek-omitted} [διοθεν]{.greek-added}[9:21 | instance no. 2]{.aside}

και πολλακις αυτον και εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα ινα απολεση αυτον αλλ ει τι δυνασαι βοηθησον ημιν σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω [το]{.greek-omitted} ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου μετα δακρυων ελεγεν πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων [δε]{.greek-omitted} ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πνευματι τω ακαθαρτω λεγων αυτω το πνευμα το αλαλον και κωφον εγω σοι [επιτασω]{.greek-added} [επιτασσω]{.corr} εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν και πολλα σπαραξαν αυτον [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και [εγενετο]{.greek-omitted} [εγενετον]{.greek-added} ωσει νεκρος ωστε [πολλους]{.greek-omitted} [λεγειν]{.greek-omitted} [οτι]{.greek-omitted} [απεθανεν]{.greek-omitted}[9:26]{.aside}

[και]{.greek-omitted} [κραξαν]{.greek-omitted} [και]{.greek-omitted} [πολλα]{.greek-omitted} [σπαραξαν]{.greek-omitted} [αυτον]{.greek-omitted} [εξηλθεν]{.greek-omitted} [και]{.greek-omitted} [εγενετο]{.greek-omitted} [ωσει]{.greek-omitted} [νεκρος]{.greek-omitted} [ωστε]{.greek-omitted} πολλους λεγειν οτι απεθανεν[9:26 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας αυτον της χειρος ηγειρεν αυτον και ανεστη[9:27]{.aside}

και εισελθοντα αυτον εις οικον οι μαθηται αυτου επηρωτων αυτον κατ ιδιαν [δια]{.greek-added} [οτι]{.greek-omitted} [τι]{.greek-added} ημεις ουκ [ηδυνηθημεν]{.greek-omitted} [εδυνηθημεν]{.greek-added} εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι δυναται εξελθειν ει [μη]{.greek-omitted} [μι]{.greek-added} εν προσευχη και νηστεια[9:29]{.aside}

και εκειθεν εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου και ελεγεν αυτοις οτι ο υιος του [ανθρωπου]{.greek-abbr} [παραδιδωται]{.greek-added} [παραδιδοται]{.corr} εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη ημερα αναστησεται[9:31]{.aside}

οι δε [ηγνο]{.greek-added} [ηγνοουν]{.greek-omitted} [το]{.greek-omitted} [ρημα]{.greek-omitted} [και]{.greek-omitted} [εφοβουντο]{.greek-omitted} [αυτον]{.greek-omitted} [επερωτησαι]{.greek-omitted}[9:32]{.aside}

[ουν]{.greek-added} [οι]{.greek-omitted} [δε]{.greek-omitted} [ηγνοουν]{.greek-omitted} το ρημα και εφοβουντο αυτον επερωτησαι[9:32 | instance no. 2]{.aside}

και ηλθεν εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω προς εαυτους διελογιζεσθε[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ διελεχθησαν [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted} τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι [εσται]{.greek-omitted} [εστω]{.greek-added} παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

[ος]{.greek-omitted} εαν εν των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος εαν εμε δεξηται ουκ [ε]{.greek-added} [εμε]{.greek-omitted} [δεχεται]{.greek-omitted} [αλλα]{.greek-omitted} [τον]{.greek-omitted} [αποστειλαντα]{.greek-omitted} [με]{.greek-omitted}[9:37]{.aside}

[ος]{.greek-omitted} [εαν]{.greek-omitted} [εν]{.greek-omitted} [των]{.greek-omitted} [τοιουτων]{.greek-omitted} [παιδιων]{.greek-omitted} [δεξηται]{.greek-omitted} [επι]{.greek-omitted} [τω]{.greek-omitted} [ονοματι]{.greek-omitted} [μου]{.greek-omitted} [εμε]{.greek-omitted} [με]{.greek-added} [δεχεται]{.greek-omitted} [και]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [εμε]{.greek-omitted} [δεξηται]{.greek-omitted} [ουκ]{.greek-omitted} [εμε]{.greek-omitted} δεχεται αλλα τον αποστειλαντα με[9:37 | instance no. 2]{.aside}

απεκριθη δε αυτω ιωαννης λεγων διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} τινα τω ονοματι σου εκβαλλοντα δαιμονια ος ουκ ακολουθει ημιν και εκωλυσαμεν αυτον οτι ουκ ακολουθει ημιν[9:38]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη κωλυετε αυτον ουδεις γαρ εστιν ος ποιησει δυναμιν επι τω ονοματι μου και δυνησεται ταχυ κακολογησαι με[9:39]{.aside}

ος γαρ ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} καθ υμων υπερ υμων [εστιν]{.greek-omitted} [εστι]{.greek-added}[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν ονοματι [μου]{.greek-omitted} οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος εαν σκανδαλιση ενα [των]{.greek-omitted} [τον]{.greek-added} μικρων των [πιστευοντων]{.greek-omitted} [πιστευον]{.greek-added} [εις]{.greek-omitted} [εμε]{.greek-omitted} [καλον]{.greek-omitted} [εστιν]{.greek-omitted} [αυτω]{.greek-omitted} [μαλλον]{.greek-omitted} [ει]{.greek-omitted} [περικειται]{.greek-omitted} [λιθος]{.greek-omitted} [μυλικος]{.greek-omitted} [περι]{.greek-omitted} [τον]{.greek-omitted} [τραχηλον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [βεβληται]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [θαλασσαν]{.greek-omitted}[9:42]{.aside}

[και]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [σκανδαλιση]{.greek-omitted} [ενα]{.greek-omitted} των [μικρων]{.greek-omitted} [των]{.greek-omitted} [πιστευοντων]{.greek-omitted} εις εμε καλον εστιν αυτω μαλλον ει περικειται λιθος μυλικος περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42 | instance no. 2]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο [σκοληξ]{.greek-added} [σκωληξ]{.corr} [ο]{.greek-added} [ακοιβητος]{.greek-added} αυτων ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε αποκοψον αυτον καλον [γαρ]{.greek-added} εστιν [σοι]{.greek-omitted} εισελθειν εις την ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο [σκοληξ]{.greek-added} [σκωληξ]{.corr} αυτων [ου]{.greek-omitted} [τελευτα]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [πυρ]{.greek-omitted} [ου]{.greek-omitted} [σβεννυται]{.greek-omitted}[9:46]{.aside}

[οπου]{.greek-omitted} [ο]{.greek-omitted} [σκωληξ]{.greek-omitted} [αυτων]{.greek-omitted} ου τελευτα και το πυρ ου σβεννυται[9:46 | instance no. 2]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε εκβαλε αυτον καλον σοι εστιν [μονοφθαλμον]{.greek-omitted} [μονοφαλμον]{.greek-added} εισελθειν εις την [βασιλειαν]{.greek-omitted} [βασιλει]{.greek-added} του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

κακειθεν αναστας ερχεται εις τα ορια της ιουδαιας δια του περαν του ιορδανου και συμπορευονται παλιν οχλοι [πολλοι]{.greek-added} προς [αυ]{.greek-added} [αυτον]{.greek-omitted} [και]{.greek-omitted} [ως]{.greek-omitted} [ειωθει]{.greek-omitted} [παλιν]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [αυτους]{.greek-omitted}[10:1]{.aside}

[κακειθεν]{.greek-omitted} [αναστας]{.greek-omitted} [ερχεται]{.greek-omitted} [εις]{.greek-omitted} [τα]{.greek-omitted} [ορια]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} [δια]{.greek-omitted} [του]{.greek-omitted} [περαν]{.greek-omitted} [του]{.greek-omitted} [ιορδανου]{.greek-omitted} [και]{.greek-omitted} [συμπορευονται]{.greek-omitted} [παλιν]{.greek-omitted} [οχλοι]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [τον]{.greek-added} και ως ειωθει παλιν εδιδασκεν αυτους[10:1 | instance no. 2]{.aside}

και προσελθοντες φαρισαιοι επηρωτησαν αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} επετρεψεν βιβλιον αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την σκληροκαρδιαν υμων εγραψεν υμιν την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως [αρσεν]{.greek-omitted} [αρσε]{.greek-added} και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι [δυο]{.greek-omitted} [δυ]{.greek-added} [εις]{.greek-omitted} [σαρκα]{.greek-omitted} [μιαν]{.greek-omitted} [ωστε]{.greek-omitted} [ουκετι]{.greek-omitted} [εισιν]{.greek-omitted} [δυο]{.greek-omitted} [αλλα]{.greek-omitted} [μια]{.greek-omitted} [σαρξ]{.greek-omitted}[10:8]{.aside}

[ο]{.greek-added} [και]{.greek-omitted} [εσονται]{.greek-omitted} [οι]{.greek-omitted} [δυο]{.greek-omitted} εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δυο αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8 | instance no. 2]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου περι του αυτου επηρωτησαν αυτον[10:10]{.aside}

και λεγει αυτοις ος εαν απολυση την γυναικα αυτου και γαμηση αλλην μοιχαται επ αυτην[10:11]{.aside}

και εαν γυνη [απολυση]{.greek-omitted} [απολυσει]{.greek-added} τον ανδρα αυτης και γαμηθη αλλω μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται [αυτου]{.greek-added} επετιμων τοις [προσφερουσιν]{.greek-omitted} [προσφερουσι]{.greek-added}[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και ειπεν αυτοις αφετε τα παιδια [ερχεσθαι]{.greek-omitted} [ερχεσθε]{.greek-added} προς με μη κωλυετε αυτα των γαρ [τοιουτων]{.greek-omitted} [τοιου]{.greek-added} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[10:14]{.aside}

[ιδων]{.greek-omitted} [δε]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ηγανακτησεν]{.greek-omitted} [και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [αφετε]{.greek-omitted} [τα]{.greek-omitted} [παιδια]{.greek-omitted} [ερχεσθαι]{.greek-omitted} [προς]{.greek-omitted} [με]{.greek-omitted} [μη]{.greek-omitted} [κωλυετε]{.greek-omitted} [αυτα]{.greek-omitted} των [γαρ]{.greek-omitted} [τοιουτων]{.greek-omitted} εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14 | instance no. 2]{.aside}

αμην λεγω υμιν ος εαν [μη]{.greek-omitted} [μοι]{.greek-added} δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ευλογογει]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} [πλουσιος]{.greek-added} προσδραμων [εις]{.greek-omitted} και γονυπετησας αυτον επηρωτα αυτον διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει [μη]{.greek-omitted} [μι]{.greek-added} εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr}[10:19]{.aside}

ο δε [α]{.greek-added} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [ταυτα]{.greek-omitted} [παντα]{.greek-omitted} [εφυλαξαμην]{.greek-omitted} [εκ]{.greek-omitted} [νεοτητος]{.greek-omitted} [μου]{.greek-omitted}[10:20]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ποκριθεις]{.greek-added} ειπεν αυτω [διδασκαλε]{.greek-omitted} ταυτα παντα [εφυλαξαμην]{.greek-omitted} εκ νεοτητος [μου]{.greek-omitted} [εφυλαξαμην]{.greek-added} [τι]{.greek-added} [ετι]{.greek-added} [υστερω]{.greek-added}[10:20 | instance no. 2]{.aside}

ο δε [ιησους]{.greek-omitted} εμβλεψας αυτω ηγαπησεν αυτον και ειπεν αυτω [ει]{.greek-added} [θελεις]{.greek-added} [τελειος]{.greek-added} [ειναι]{.greek-added} εν [σοι]{.greek-omitted} [σε]{.greek-added} υστερει υπαγε οσα εχεις πωλησον και δος πτωχοις και εξεις [θησαυρον]{.greek-omitted} [θησαυρω]{.greek-added} εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} και [δευρω]{.greek-added} [δευρο]{.corr} ακολουθει μοι αρας τον [σταυρον]{.greek-abbr}[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν [του]{.greek-omitted} [θεου]{.greek-omitted} [των]{.greek-added} [[ουρανων]{.greek-abbr}]{.greek-added} [εισελευσονται]{.greek-omitted} [εισελευσοντε]{.greek-added}[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις [τεκνα]{.greek-omitted} πως δυσκολον [εστιν]{.greek-omitted} [τους]{.greek-omitted} [πεποιθοτας]{.greek-omitted} [επι]{.greek-omitted} [χρημασιν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [εισελθειν]{.greek-omitted}[10:24]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [μαθηται]{.greek-omitted} [εθαμβουντο]{.greek-omitted} [επι]{.greek-omitted} [τοις]{.greek-omitted} [λογοις]{.greek-omitted} [αυτου]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [παλιν]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [τεκνα]{.greek-omitted} [πως]{.greek-omitted} [δυσκολον]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24 | instance no. 2]{.aside}

[ευκοπωτερον]{.greek-omitted} [ευκοποτερον]{.greek-added} [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added} η [πλουσιον]{.greek-omitted} [πλουσιος]{.greek-added} εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε [αυτοις]{.greek-omitted} ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} αδυνατον αλλ ου παρα [τω]{.greek-added} [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} [εστι]{.greek-added} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

ηρξατο [δε]{.greek-added} ο πετρος λεγειν αυτω ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

αποκριθεις [δε]{.greek-added} ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η [τε]{.greek-added} [τεκνα]{.greek-omitted} [η]{.greek-omitted} [αγρους]{.greek-omitted} [ενεκεν]{.greek-omitted} [εμου]{.greek-omitted} [και]{.greek-omitted} [ενεκεν]{.greek-omitted} [του]{.greek-omitted} [ευαγγελιου]{.greek-omitted}[10:29]{.aside}

[αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ουδεις]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} [αφηκεν]{.greek-omitted} [οικιαν]{.greek-omitted} [η]{.greek-omitted} [αδελφους]{.greek-omitted} [η]{.greek-omitted} [αδελφας]{.greek-omitted} [η]{.greek-omitted} [πατερα]{.greek-omitted} [η]{.greek-omitted} [μητερα]{.greek-omitted} [η]{.greek-omitted} [γυναικα]{.greek-omitted} [η]{.greek-omitted} [τεκνα]{.greek-omitted} [κνα]{.greek-added} η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29 | instance no. 2]{.aside}

εαν μη λαβη εκατονταπλασιονα νυν εν τω καιρω [τουτω]{.greek-omitted} [τουτο]{.greek-added} οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα [διωγμων]{.greek-omitted} [διωγμου]{.greek-added} και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο και [ακολουθουντες]{.greek-omitted} [εφοβουντο]{.greek-omitted} [και]{.greek-omitted} παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου αναβαινομεν εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [γραμ]{.greek-added} [γραμματευσιν]{.greek-omitted} [και]{.greek-omitted} [κατακρινουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [θανατω]{.greek-omitted} [και]{.greek-omitted} [παραδωσουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted}[10:33]{.aside}

[ματευσι]{.greek-added} [οτι]{.greek-omitted} [ιδου]{.greek-omitted} [αναβαινομεν]{.greek-omitted} [εις]{.greek-omitted} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [παραδοθησεται]{.greek-omitted} [τοις]{.greek-omitted} [αρχιερευσιν]{.greek-omitted} [και]{.greek-omitted} [γραμματευσιν]{.greek-omitted} και κατακρινουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} θανατω και [παραδωσουσιν]{.greek-omitted} [παραδοσουσιν]{.greek-added} αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33 | instance no. 2]{.aside}

και εμπαιξουσιν αυτω και μαστιγωσουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} και εμπτυσουσιν αυτω και αποκτενουσιν [αυτον]{.greek-omitted} [αυτω]{.greek-added} και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και ιωαννης [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν [σε]{.greek-added} αιτησωμεν ποιησης ημιν[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε [ποιησαι]{.greek-omitted} [ποιησω]{.greek-added} [με]{.greek-omitted} υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις εκ δεξιων σου και εις εξ ευωνυμων σου [καθισωμεν]{.greek-omitted} [καθησωμεν]{.greek-added} εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε [πιειν]{.greek-omitted} [ποιειν]{.greek-added} το ποτηριον ο εγω πινω [και]{.greek-omitted} [το]{.greek-omitted} [βαπτισμα]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [βαπτιζομαι]{.greek-omitted} [βαπτισθηναι]{.greek-omitted}[10:38]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ουκ]{.greek-omitted} [οιδατε]{.greek-omitted} [τι]{.greek-omitted} [αιτεισθε]{.greek-omitted} [δυνασθε]{.greek-omitted} [πιειν]{.greek-omitted} [το]{.greek-omitted} [ποτηριον]{.greek-omitted} [ο]{.greek-omitted} [εγω]{.greek-omitted} [πινω]{.greek-omitted} και το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38 | instance no. 2]{.aside}

οι δε ειπον αυτω δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και ιωαννου[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι αυτων κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως δε εσται εν υμιν αλλ ος εαν θελη γενεσθαι [με]{.greek-added} [μεγας]{.greek-omitted} [εν]{.greek-omitted} [υμιν]{.greek-omitted} [εσται]{.greek-omitted} [υμων]{.greek-omitted} [διακονος]{.greek-omitted}[10:43]{.aside}

[ουχ]{.greek-omitted} [ουτως]{.greek-omitted} [δε]{.greek-omitted} [εσται]{.greek-omitted} [εν]{.greek-omitted} [υμιν]{.greek-omitted} [αλλ]{.greek-omitted} [ος]{.greek-omitted} [εαν]{.greek-omitted} [θελη]{.greek-omitted} [γενεσθαι]{.greek-omitted} [μεγας]{.greek-omitted} [γας]{.greek-added} εν υμιν εσται [υμων]{.greek-omitted} [υμιν]{.greek-added} διακονος[10:43 | instance no. 2]{.aside}

και ος εαν θελη υμων γενεσθαι πρωτος εσται παντων δουλος[10:44]{.aside}

και γαρ ο υιος του [ανθρωπου]{.greek-abbr} ουκ ηλθεν διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και [ερχονται]{.greek-omitted} [ερχοντε]{.greek-added} εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου υιος τιμαιου βαρτιμαιος ο τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ο]{.greek-added} [ιησους]{.greek-abbr} ο ναζωραιος εστιν ηρξατο κραζειν και λεγειν ο [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-abbr} ελεησον με[10:47]{.aside}

και επετιμων αυτω πολλοι ινα σιωπηση ο δε πολλω μαλλον εκραζεν υιε [δαυιδ]{.greek-omitted} [ελεησον]{.greek-omitted} [με]{.greek-omitted}[10:48]{.aside}

[και]{.greek-omitted} [επετιμων]{.greek-omitted} [αυτω]{.greek-omitted} [πολλοι]{.greek-omitted} [ινα]{.greek-omitted} [σιωπηση]{.greek-omitted} [ο]{.greek-omitted} [δε]{.greek-omitted} [πολλω]{.greek-omitted} [μαλλον]{.greek-omitted} [εκραζεν]{.greek-omitted} [υιε]{.greek-omitted} [δαυιδ]{.greek-abbr} ελεησον με[10:48 | instance no. 2]{.aside}

και στας ο [ιησους]{.greek-abbr} ειπεν [αυτον]{.greek-omitted} [αυτω]{.greek-added} φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει [εγειραι]{.greek-omitted} [εγειρε]{.greek-added} φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} λεγει αυτω [ο]{.greek-omitted} [ιησους]{.greek-omitted} τι θελεις ποιησω [σοι]{.greek-omitted} ο δε τυφλος ειπεν αυτω [ραβουν]{.greek-added} [ιν]{.greek-added} [ραββουνι]{.greek-omitted} [[ραβουνι]{.corr}]{.greek-added} [ινα]{.corr} αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [λεγει]{.greek-added} αυτω υπαγε η πιστις [σου]{.greek-omitted} [ου]{.greek-added} [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει τω [ιησου]{.greek-abbr} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις ιερουσαλημ εις [βηθσφαγη]{.greek-omitted} [βηθφαγη]{.greek-added} και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

και λεγει αυτοις υπαγετε εις την κωμην την [κατεναντι]{.greek-omitted} [απεναντι]{.greek-added} υμων και ευθεως [εισπορευομενοι]{.greek-omitted} [εις]{.greek-omitted} [αυτην]{.greek-omitted} [ευρησετε]{.greek-omitted} [πωλον]{.greek-omitted} [δεδεμενον]{.greek-omitted} [εφ]{.greek-omitted} [ον]{.greek-omitted} [ουδεις]{.greek-omitted} [ανθρωπων]{.greek-omitted} [κεκαθικεν]{.greek-omitted} [λυσαντες]{.greek-omitted} [αυτον]{.greek-omitted} [αγαγετε]{.greek-omitted}[11:2]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [κωμην]{.greek-omitted} [την]{.greek-omitted} [κατεναντι]{.greek-omitted} [υμων]{.greek-omitted} [και]{.greek-omitted} [ευθεως]{.greek-omitted} εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον [ουπω]{.greek-added} ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [εκαθισε]{.greek-added} λυσαντες αυτον αγαγετε[11:2 | instance no. 2]{.aside}

και εαν τις υμιν ειπη τι ποιειτε τουτο ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον [αποστελλει]{.greek-omitted} [αποστελει]{.greek-added} ωδε[11:3]{.aside}

απηλθον δε και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

και τινες των εκει εστηκοτων ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

[οι]{.greek-omitted} [ο]{.greek-added} δε [ειπον]{.greek-omitted} [ειπεν]{.greek-added} αυτοις καθως [ενετειλατο]{.greek-omitted} [ενετει]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και ηγαγον τον πωλον προς τον [ιησουν]{.greek-abbr} και επεβαλον αυτω τα ιματια αυτων και εκαθισεν επ αυτω[11:7]{.aside}

πολλοι δε τα [ιματια]{.greek-omitted} [αυτων]{.greek-omitted} [εστρωσαν]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [αλλοι]{.greek-omitted} [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [εκοπτον]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [δενδρων]{.greek-omitted} [και]{.greek-omitted} [εστρωννυον]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted}[11:8]{.aside}

[πολλοι]{.greek-omitted} [δε]{.greek-omitted} [τα]{.greek-omitted} ιματια αυτων εστρωσαν [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added} αλλοι [δε]{.greek-omitted} [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον [εκ]{.greek-omitted} [απο]{.greek-added} των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδωι]{.greek-added}[11:8 | instance no. 2]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

[και]{.greek-added} ευλογημενη η [βασιλεια]{.greek-added} [η]{.greek-added} ερχομενη [βασιλεια]{.greek-omitted} εν ονοματι [κυριου]{.greek-abbr} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα ο [ιησους]{.greek-abbr} και εις το ιερον και περιβλεψαμενος παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων αυτων απο βηθανιας [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[11:12]{.aside}

και ιδων συκην [μιαν]{.greek-added} μακροθεν [εχου]{.greek-added} [εχουσαν]{.greek-omitted} [φυλλα]{.greek-omitted} [ηλθεν]{.greek-omitted} [ει]{.greek-omitted} [αρα]{.greek-omitted} [ευρησει]{.greek-omitted} [τι]{.greek-omitted} [εν]{.greek-omitted} [αυτη]{.greek-omitted} [και]{.greek-omitted} [ελθων]{.greek-omitted} [επ]{.greek-omitted} [αυτην]{.greek-omitted} [ουδεν]{.greek-omitted} [ευρεν]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} [φυλλα]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [ην]{.greek-omitted} [καιρος]{.greek-omitted} [συκων]{.greek-omitted}[11:13]{.aside}

[σαν]{.greek-added} [και]{.greek-omitted} [ιδων]{.greek-omitted} [συκην]{.greek-omitted} [μακροθεν]{.greek-omitted} [εχουσαν]{.greek-omitted} φυλλα ηλθεν ει αρα [τι]{.greek-added} ευρησει [τι]{.greek-omitted} εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα ου γαρ ην καιρος συκων[11:13 | instance no. 2]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι εκ σου εις τον αιωνα μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και [τους]{.greek-added} αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων και τας καθεδρας των πωλουντων τας περιστερας κατεστρεψεν[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [διδασκεν]{.greek-added} [εδιδασκεν]{.corr} λεγων αυτοις ου γεγραπται οτι ο οικος μου οικος [προσευχης]{.greek-omitted} [κληθησεται]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [εθνεσιν]{.greek-omitted} [υμεις]{.greek-omitted} [δε]{.greek-omitted} [εποιησατε]{.greek-omitted} [αυτον]{.greek-omitted} [σπηλαιον]{.greek-omitted} [ληστων]{.greek-omitted}[11:17]{.aside}

[και]{.greek-omitted} [εδιδασκεν]{.greek-omitted} [λεγων]{.greek-omitted} [αυτοις]{.greek-omitted} [ου]{.greek-omitted} [γεγραπται]{.greek-omitted} [οτι]{.greek-omitted} [ο]{.greek-omitted} [οικος]{.greek-omitted} [μου]{.greek-omitted} [οικος]{.greek-omitted} προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε [αυτον]{.greek-added} εποιησατε [αυτον]{.greek-omitted} σπηλαιον ληστων[11:17 | instance no. 2]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιρεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ [αυτον]{.greek-omitted} οτι πας ο οχλος [εξεπλησσετο]{.greek-omitted} [εξεπλησσοντο]{.greek-added} επι τη διδαχη αυτου[11:18]{.aside}

και [οτε]{.greek-omitted} [οταν]{.greek-added} οψε εγενετο [εξεπορευετο]{.greek-omitted} [εξεπορευοντο]{.greek-added} εξω της πολεως[11:19]{.aside}

και πρωι παραπορευομενοι [ειδον]{.greek-omitted} [ιδον]{.greek-added} την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει [αυτω]{.greek-omitted} [αυτωι]{.greek-added} ραββι ιδε η συκη ην κατηρασω εξηρανται[11:21]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} λεγει αυτοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμιν οτι ος αν ειπη τω ορει τουτω αρθητι και βληθητι εις την [θαλασσαν]{.greek-omitted} [και]{.greek-omitted} [μη]{.greek-omitted} [διακριθη]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [καρδια]{.greek-omitted} [αυτου]{.greek-omitted} [αλλα]{.greek-omitted} [πιστευση]{.greek-omitted} [οτι]{.greek-omitted} [α]{.greek-omitted} [λεγει]{.greek-omitted} [γινεται]{.greek-omitted} [εσται]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [εαν]{.greek-omitted} [ειπη]{.greek-omitted}[11:23]{.aside}

[αμην]{.greek-omitted} [γαρ]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [ος]{.greek-omitted} [αν]{.greek-omitted} [ειπη]{.greek-omitted} [τω]{.greek-omitted} [ορει]{.greek-omitted} [τουτω]{.greek-omitted} [αρθητι]{.greek-omitted} [και]{.greek-omitted} [βληθητι]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} θαλασσαν και μη διακριθη εν τη καρδια αυτου αλλα πιστευση οτι α λεγει γινεται εσται αυτω ο εαν ειπη[11:23 | instance no. 2]{.aside}

δια τουτο λεγω υμιν παντα οσα [αν]{.greek-omitted} [εαν]{.greek-added} προσευχομενοι αιτησθε πιστευετε οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν στηκητε προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} [μου]{.greek-added} [υμων]{.corr} ο εν τοις [ουρανοις]{.greek-abbr} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο εν [τοις]{.greek-omitted} [ουρανοις]{.greek-abbr} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι [γραμματεις]{.greek-omitted} [γραμμα]{.greek-added} [και]{.greek-omitted} [οι]{.greek-omitted} [πρεσβυτεροι]{.greek-omitted}[11:27]{.aside}

[και]{.greek-omitted} [ερχονται]{.greek-omitted} [παλιν]{.greek-omitted} [εις]{.greek-omitted} [τεις]{.greek-added} [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [ιερω]{.greek-omitted} [περιπατουντος]{.greek-omitted} [αυτου]{.greek-omitted} [ερχονται]{.greek-omitted} [προς]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [αρχιερεις]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [γραμματεις]{.greek-omitted} και οι πρεσβυτεροι[11:27 | instance no. 2]{.aside}

και λεγουσιν αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι την εξουσιαν ταυτην εδωκεν ινα ταυτα ποιης[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω [καγω]{.greek-added} υμας [και]{.greek-omitted} [εγω]{.greek-omitted} ενα λογον και αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα ιωαννου εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ ουρανου ερει δια τι [ουν]{.greek-omitted} ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ ειπωμεν εξ [ανθρωπων]{.greek-abbr} [εφοβουν]{.greek-added} [εφοβουντο]{.corr} τον λαον απαντες γαρ ειχον τον ιωαννην οτι οντως προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} [λεγουσ[ι]{.unclear}]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [ουκ]{.greek-omitted} [οιδαμεν]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ουδε]{.greek-omitted} [εγω]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [εν]{.greek-omitted} [ποια]{.greek-omitted} [εξουσια]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιω]{.greek-omitted}[11:33]{.aside}

[και]{.greek-omitted} [αποκριθεντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} τω [ιησου]{.greek-abbr} ουκ οιδαμεν και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33 | instance no. 2]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις λεγειν αμπελωνα εφυτευσεν ανθρωπος και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους [δουλον]{.greek-added} τω καιρω [δουλον]{.greek-omitted} ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον λιθοβολησαντες εκεφαλαιωσαν [και]{.greek-omitted} [απεστειλαν]{.greek-omitted} [ητιμωμενον]{.greek-omitted}[12:4]{.aside}

[και]{.greek-omitted} [παλιν]{.greek-omitted} [απεστειλεν]{.greek-omitted} [προς]{.greek-omitted} [αυτους]{.greek-omitted} [αλλον]{.greek-omitted} [δουλον]{.greek-omitted} [κακεινον]{.greek-omitted} [λιθοβολησαντες]{.greek-omitted} [εκεφαλαιωσαν]{.greek-omitted} και απεστειλαν ητιμωμενον[12:4 | instance no. 2]{.aside}

και παλιν αλλον απεστειλεν κακεινον απεκτειναν και πολλους αλλους τους μεν δεροντες τους δε αποκτενοντες[12:5]{.aside}

ετι ουν ενα υιον εχων αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} και αυτον [εσχατον]{.greek-added} προς αυτους [εσχατον]{.greek-omitted} λεγων οτι εντραπησονται τον υιον μου[12:6]{.aside}

εκεινοι δε οι γεωργοι ειπον προς εαυτους οτι ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον [αυτον]{.greek-added} εξω του αμπελωνος[12:8]{.aside}

[τι]{.greek-omitted} [ουν]{.greek-omitted} [ποιησει]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [του]{.greek-omitted} [αμπελωνος]{.greek-omitted} ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα [αλλοις]{.greek-omitted}[12:9]{.aside}

[τι]{.greek-omitted} [ουν]{.greek-omitted} [ποιησει]{.greek-omitted} [ο]{.greek-omitted} [κυριος]{.greek-omitted} [του]{.greek-omitted} [αμπελωνος]{.greek-omitted} [ελευσεται]{.greek-omitted} [και]{.greek-omitted} [απολεσει]{.greek-omitted} [τους]{.greek-omitted} [γεωργους]{.greek-omitted} [και]{.greek-omitted} [δωσει]{.greek-omitted} [τον]{.greek-omitted} [αμπελωνα]{.greek-omitted} αλλοις [γεωργοις]{.greek-added}[12:9 | instance no. 2]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην [γωνιας]{.greek-omitted} [γονιας]{.greek-added}[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} [θαυμαστη]{.greek-omitted} [θαυμαστοι]{.greek-added} εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην ειπεν και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελουσι]{.greek-added} προς [αυτον]{.greek-omitted} [αυτους]{.greek-added} τινας των φαρισαιων και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσοσι]{.greek-added} [λογω]{.greek-omitted} [λογον]{.greek-added}[12:13]{.aside}

οι δε ελθοντες λεγουσιν αυτω διδασκαλε οιδαμεν οτι [αληθης]{.greek-omitted} [αληθεις]{.greek-added} ει και ου μελει σοι περι ουδενος ου γαρ βλεπεις εις [προ]{.greek-added} [προσωπον]{.greek-omitted} [ανθρωπων]{.greek-omitted} [αλλ]{.greek-omitted} [επ]{.greek-omitted} [αληθειας]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [διδασκεις]{.greek-omitted} [εξεστιν]{.greek-omitted} [κηνσον]{.greek-omitted} [καισαρι]{.greek-omitted} [δουναι]{.greek-omitted} [η]{.greek-omitted} [ου]{.greek-omitted}[12:14]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ελθοντες]{.greek-omitted} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} [οιδαμεν]{.greek-omitted} [οτι]{.greek-omitted} [αληθης]{.greek-omitted} [ει]{.greek-omitted} [και]{.greek-omitted} [ου]{.greek-omitted} [μελει]{.greek-omitted} [σοι]{.greek-omitted} [περι]{.greek-omitted} [ουδενος]{.greek-omitted} [ου]{.greek-omitted} [γαρ]{.greek-omitted} [βλεπεις]{.greek-omitted} [εις]{.greek-omitted} [προσωπον]{.greek-omitted} [σωπον]{.greek-added} [ανθρωπων]{.greek-abbr} αλλ επ αληθειας την οδον του [θεου]{.greek-abbr} διδασκεις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} κηνσον καισαρι δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14 | instance no. 2]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με [πειραζετε]{.greek-omitted} [πειραζεται]{.greek-added} [φερετε]{.greek-omitted} [φερεται]{.greek-added} μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον αυτω καισαρος[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται σαδδουκαιοι προς αυτον οιτινες λεγουσιν αναστασιν μη ειναι και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν ημιν οτι εαν τινος αδελφος [α]{.greek-added} [αποθανη]{.greek-omitted} [και]{.greek-omitted} [καταλιπη]{.greek-omitted} [γυναικα]{.greek-omitted} [και]{.greek-omitted} [τεκνα]{.greek-omitted} [μη]{.greek-omitted} [αφη]{.greek-omitted} [ινα]{.greek-omitted} [λαβη]{.greek-omitted} [ο]{.greek-omitted} [αδελφος]{.greek-omitted} [αυτου]{.greek-omitted} [την]{.greek-omitted} [γυναικα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [εξαναστηση]{.greek-omitted} [σπερμα]{.greek-omitted} [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [αυτου]{.greek-omitted}[12:19]{.aside}

[διδασκαλε]{.greek-omitted} [μωσης]{.greek-omitted} [εγραψεν]{.greek-omitted} [ημιν]{.greek-omitted} [οτι]{.greek-omitted} [εαν]{.greek-omitted} [τινος]{.greek-omitted} [αδελφος]{.greek-omitted} αποθανη και καταλιπη γυναικα και τεκνα μη αφη ινα λαβη ο αδελφος αυτου την γυναικα αυτου και εξαναστηση σπερμα τω αδελφω αυτου[12:19 | instance no. 2]{.aside}

επτα αδελφοι ησαν και ο πρωτος ελαβεν γυναικα και αποθνησκων ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην [οι]{.greek-omitted} [η]{.greek-added} επτα και ουκ [αφηκαν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη [ουν]{.greek-added} αναστασει οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται [η]{.greek-added} γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη [ειδοτες]{.greek-omitted} [τας]{.greek-omitted} [γραφας]{.greek-omitted} [μηδε]{.greek-omitted} [την]{.greek-omitted} [δυναμιν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted}[12:24]{.aside}

[και]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ου]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [πλανασθε]{.greek-omitted} [μη]{.greek-omitted} ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24 | instance no. 2]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε γαμισκονται αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεως]{.greek-added} επι του βατου ως ειπεν αυτω ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν πολυ πλανασθε[12:27]{.aside}

και προσελθων εις των [γραμματαιων]{.greek-added} [γραμματεων]{.corr} ακουσας αυτων συζητουντων [ειδως]{.greek-omitted} [ειδος]{.greek-added} οτι καλως αυτοις απεκριθη επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη [παντων]{.greek-omitted} εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} απεκριθη αυτω [οτι]{.greek-omitted} πρωτη [παντων]{.greek-omitted} [των]{.greek-omitted} [εντολων]{.greek-omitted} [ακουε]{.greek-omitted} [ισραηλ]{.greek-omitted} [κυριος]{.greek-omitted} [ο]{.greek-omitted} [θεος]{.greek-omitted} [ημων]{.greek-omitted} [κυριος]{.greek-omitted} [εις]{.greek-omitted} [εστιν]{.greek-omitted}[12:29]{.aside}

[παντων]{.greek-added} [εντολη]{.greek-added} ο δε [ιησους]{.greek-abbr} απεκριθη αυτω [οτι]{.greek-omitted} πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [εντολη]{.greek-added} ακουε [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29 | instance no. 2]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της [ψυχης]{.greek-omitted} [σου]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη [παντων]{.greek-added} εντολη[12:30]{.aside}

και δευτερα ομοια αυτη αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις [εστιν]{.greek-omitted} [εστι]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της συνεσεως και εξ ολης [της]{.greek-omitted} [ψυχης]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} [και]{.greek-omitted} [το]{.greek-omitted} [αγαπαν]{.greek-omitted} [τον]{.greek-omitted} [πλησιον]{.greek-omitted} [ως]{.greek-omitted} [εαυτον]{.greek-omitted} [πλειον]{.greek-omitted} [εστιν]{.greek-omitted} [παντων]{.greek-omitted} [των]{.greek-omitted} [ολοκαυτωματων]{.greek-omitted} [και]{.greek-omitted} [θυσιων]{.greek-omitted}[12:33]{.aside}

[και]{.greek-omitted} [το]{.greek-omitted} [αγαπαν]{.greek-omitted} [αυτον]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [καρδιας]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [συνεσεως]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ψυχης]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} της ισχυος και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33 | instance no. 2]{.aside}

και ο [ιησους]{.greek-abbr} ιδων αυτον οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον επερωτησαι[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω λεγει ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και ποθεν [υιος]{.greek-abbr} αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και [ο]{.greek-omitted} πολυς οχλος ηκουεν [αυ]{.greek-added} [αυτου]{.greek-omitted} [ηδεως]{.greek-omitted}[12:37]{.aside}

[αυτος]{.greek-omitted} [ουν]{.greek-omitted} [δαυιδ]{.greek-omitted} [λεγει]{.greek-omitted} [αυτον]{.greek-omitted} [κυριον]{.greek-omitted} [και]{.greek-omitted} [ποθεν]{.greek-omitted} [υιος]{.greek-omitted} [αυτου]{.greek-omitted} [του]{.greek-added} [εστιν]{.greek-omitted} [και]{.greek-omitted} [ο]{.greek-omitted} [πολυς]{.greek-omitted} [οχλος]{.greek-omitted} [ηκουεν]{.greek-omitted} [αυτου]{.greek-omitted} ηδεως[12:37 | instance no. 2]{.aside}

και ελεγεν αυτοις εν τη διδαχη αυτου βλεπετε απο των [γραμματαιων]{.greek-added} [γραμματεων]{.corr} των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και [πρωτοκαθεδριας]{.greek-omitted} [πρωτοκαθεδριαις]{.greek-added} εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιαις]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι [ληψονται]{.greek-omitted} [λημψονται]{.greek-added} περισσοτερον κριμα[12:40]{.aside}

και καθισας ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι [εβαλλον]{.greek-omitted} [εβαλον]{.greek-added} πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα [δυο]{.greek-omitted} [ο]{.greek-omitted} [εστιν]{.greek-omitted} [κοδραντης]{.greek-omitted}[12:42]{.aside}

[και]{.greek-omitted} [ελθουσα]{.greek-omitted} [μια]{.greek-omitted} [χηρα]{.greek-omitted} [πτωχη]{.greek-omitted} [εβαλεν]{.greek-omitted} [λεπτα]{.greek-omitted} δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42 | instance no. 2]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των βαλλοντων εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισευοντος]{.greek-added} αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις των [μαθητων]{.greek-omitted} αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και [αποκριθεις]{.greek-added} ο [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} ειπεν αυτω βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι λιθω ος ου μη [καταλυθη]{.greek-omitted}[13:2]{.aside}

[και]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [βλεπεις]{.greek-omitted} [ταυτας]{.greek-omitted} [τας]{.greek-omitted} [μεγαλας]{.greek-omitted} [οικοδομας]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [αφεθη]{.greek-omitted} [λιθος]{.greek-omitted} [επι]{.greek-omitted} [λιθω]{.greek-omitted} [ος]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} καταλυθη[13:2 | instance no. 2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και ιωαννης και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον οταν μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [συντελεισθε]{.greek-added} [συντελεισθαι]{.corr}[13:4]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις αυτοις ηρξατο λεγειν βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι και πολλους πλανησουσιν[13:6]{.aside}

οταν δε ακουσητε πολεμους και ακοας πολεμων μη θροεισθε δει [γαρ]{.greek-omitted} [γ]{.greek-added} [[και]{.corr}]{.greek-added} γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος [επι]{.greek-omitted} [επ]{.greek-added} εθνος και [βασι]{.greek-added} [βασιλεια]{.greek-omitted} [επι]{.greek-omitted} [βασιλειαν]{.greek-omitted} [και]{.greek-omitted} [εσονται]{.greek-omitted} [σεισμοι]{.greek-omitted} [κατα]{.greek-omitted} [τοπους]{.greek-omitted} [και]{.greek-omitted} [εσονται]{.greek-omitted} [λιμοι]{.greek-omitted} [και]{.greek-omitted} [ταραχαι]{.greek-omitted} [αρχαι]{.greek-omitted} [ωδινων]{.greek-omitted} [ταυτα]{.greek-omitted}[13:8]{.aside}

[λεια]{.greek-added} [εγερθησεται]{.greek-omitted} [γαρ]{.greek-omitted} [εθνος]{.greek-omitted} [επι]{.greek-omitted} [εθνος]{.greek-omitted} [και]{.greek-omitted} [βασιλεια]{.greek-omitted} επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και ταραχαι αρχαι ωδινων ταυτα[13:8 | instance no. 2]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι [ηγεμονων]{.greek-omitted} [οιγεμονων]{.greek-added} [δε]{.greek-added} και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη προμεριμνατε τι λαλησητε μηδε [μελετατε]{.greek-omitted} [μελεταται]{.greek-added} αλλ ο εαν δοθη υμιν εν εκεινη τη ωρα τουτο λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

[πα]{.greek-added} [παραδωσει]{.greek-omitted} [δε]{.greek-omitted} [αδελφος]{.greek-omitted} [αδελφον]{.greek-omitted} [εις]{.greek-omitted} [θανατον]{.greek-omitted} [και]{.greek-omitted} [πατηρ]{.greek-omitted} [τεκνον]{.greek-omitted} [και]{.greek-omitted} [επαναστησονται]{.greek-omitted} [τεκνα]{.greek-omitted} [επι]{.greek-omitted} [γονεις]{.greek-omitted} [και]{.greek-omitted} [θανατωσουσιν]{.greek-omitted} [αυτους]{.greek-omitted}[13:12]{.aside}

[παραδωσει]{.greek-omitted} [ραδωσει]{.greek-added} δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και [θανατωσουσιν]{.greek-omitted} [θανατωσουσι]{.greek-added} αυτους[13:12 | instance no. 2]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος [σωθησεται]{.greek-omitted} [σοθησεται]{.greek-added}[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως το ρηθεν υπο δανιηλ του προφητου εστως οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο δε επι του δωματος μη καταβατω εις την οικιαν [μη]{.greek-added} [μηδε]{.corr} εισελθετω [τι]{.greek-added} αραι [τι]{.greek-omitted} εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι [το]{.greek-omitted} [τα]{.greek-added} [ιματιον]{.greek-omitted} [ιματια]{.greek-added} αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι [ε]{.greek-added} [εχουσαις]{.greek-omitted} [και]{.greek-omitted} [ταις]{.greek-omitted} [θηλαζουσαις]{.greek-omitted} [εν]{.greek-omitted} [εκειναις]{.greek-omitted} [ταις]{.greek-omitted} [ημεραις]{.greek-omitted}[13:17]{.aside}

[ουαι]{.greek-omitted} [δε]{.greek-omitted} [ταις]{.greek-omitted} [εν]{.greek-omitted} [γαστρι]{.greek-omitted} [εχουσαις]{.greek-omitted} [χουσαις]{.greek-added} και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17 | instance no. 2]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη υμων χειμωνος[13:18]{.aside}

εσονται γαρ αι ημεραι εκειναι θλιψις οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν και ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-abbr} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας ουκ αν εσωθη πασα σαρξ αλλα δια τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας[13:20]{.aside}

[και]{.greek-added} τοτε εαν τις υμιν ειπη ιδου ωδε ο [χριστος]{.greek-abbr} η ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν [παντα]{.greek-omitted} [απαντα]{.greek-added}[13:23]{.aside}

αλλ εν εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το [φεγγος]{.greek-omitted} [φεγκος]{.greek-added} αυτης[13:24]{.aside}

και οι αστερες [εσοντε]{.greek-added} [εκ]{.greek-added} του [ουρανου]{.greek-abbr} [εσονται]{.greek-omitted} [εκπιπτοντες]{.greek-omitted} [πιπτοντες]{.greek-added} και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον υιον του [ανθρωπου]{.greek-abbr} ερχομενον εν νεφελαις μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε αποστελει τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ ακρου [της]{.greek-added} γης εως ακρου [του]{.greek-added} [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν [αυτης]{.greek-omitted} ηδη ο κλαδος [απαλος]{.greek-omitted} [αυτης]{.greek-added} γενηται [α]{.greek-added} [και]{.greek-omitted} [εκφυη]{.greek-omitted} [τα]{.greek-omitted} [φυλλα]{.greek-omitted} [γινωσκετε]{.greek-omitted} [οτι]{.greek-omitted} [εγγυς]{.greek-omitted} [το]{.greek-omitted} [θερος]{.greek-omitted} [εστιν]{.greek-omitted}[13:28]{.aside}

[απο]{.greek-omitted} [δε]{.greek-omitted} [της]{.greek-omitted} [συκης]{.greek-omitted} [μαθετε]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [οταν]{.greek-omitted} [αυτης]{.greek-omitted} [ηδη]{.greek-omitted} [ο]{.greek-omitted} [κλαδος]{.greek-omitted} [απαλος]{.greek-omitted} [παλος]{.greek-added} [γενηται]{.greek-omitted} και εκφυη τα φυλλα [γινωσκετε]{.greek-omitted} [γινωσκεται]{.greek-added} οτι εγγυς το θερος [εστιν]{.greek-omitted}[13:28 | instance no. 2]{.aside}

ουτως και υμεις οταν [ιδητε]{.greek-added} ταυτα [ιδητε]{.greek-omitted} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [μεχρις]{.greek-added} ου παντα ταυτα γενηται[13:30]{.aside}

ο ουρανος και η γη παρελευσεται οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι οι εν [ουρανω]{.greek-omitted} [[ουρανοις]{.greek-abbr}]{.greek-added} ουδε ο υιος ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

ως [ανθρωπος]{.greek-abbr} αποδημος αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και [τω]{.greek-omitted} [θυρωρω]{.greek-omitted} [ενετειλατο]{.greek-omitted} [ινα]{.greek-omitted} [γρηγορη]{.greek-omitted}[13:34]{.aside}

[ως]{.greek-omitted} [ανθρωπος]{.greek-omitted} [αποδημος]{.greek-omitted} [αφεις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [δους]{.greek-omitted} [τοις]{.greek-omitted} [δουλοις]{.greek-omitted} [αυτου]{.greek-omitted} [την]{.greek-omitted} [εξουσιαν]{.greek-omitted} [και]{.greek-omitted} [εκαστω]{.greek-omitted} [το]{.greek-omitted} [εργον]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} τω θυρωρω ενετειλατο ινα γρηγορη[13:34 | instance no. 2]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο [κυριος]{.greek-abbr} της οικιας ερχεται οψε η μεσονυκτιου η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη [ελθων]{.greek-omitted} [εξελθων]{.greek-added} [εξεφνης]{.greek-added} [εξαιφνης]{.corr} ευρη υμας καθευδοντας[13:36]{.aside}

[α]{.greek-omitted} [ο]{.greek-added} δε υμιν [λεγω]{.greek-omitted} [λεγων]{.greek-added} πασιν λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον εν δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

[ελεγον]{.greek-omitted} [ελεγων]{.greek-added} δε μη εν τη εορτη μηποτε θορυβος εσται του λαου[14:2]{.aside}

και οντος αυτου εν βηθανια εν τη οικια [σιμωνος]{.greek-omitted} [σημωνος]{.greek-added} του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου [πιστικης]{.greek-omitted} [πολυτελους]{.greek-omitted} [και]{.greek-omitted} [συντριψασα]{.greek-omitted} [το]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [κατεχεεν]{.greek-omitted} [αυτου]{.greek-omitted} [κατα]{.greek-omitted} [της]{.greek-omitted} [κεφαλης]{.greek-omitted}[14:3]{.aside}

[και]{.greek-omitted} [οντος]{.greek-omitted} [αυτου]{.greek-omitted} [εν]{.greek-omitted} [βηθανια]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οικια]{.greek-omitted} [σιμωνος]{.greek-omitted} [του]{.greek-omitted} [λεπρου]{.greek-omitted} [κατακειμενου]{.greek-omitted} [αυτου]{.greek-omitted} [ηλθεν]{.greek-omitted} [γυνη]{.greek-omitted} [εχουσα]{.greek-omitted} [αλαβαστρον]{.greek-omitted} [μυρου]{.greek-omitted} [ναρδου]{.greek-omitted} πιστικης πολυτελους και συντριψασα [το]{.greek-omitted} [τον]{.greek-added} αλαβαστρον κατεχεεν αυτου κατα της κεφαλης[14:3 | instance no. 2]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους και λεγοντες εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

[ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} γαρ τουτο [το]{.greek-added} [μυρον]{.greek-added} πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και ενεβριμωντο αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον εργον ειργασατο εν εμοι[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων και οταν θελητε δυνασθε αυτους ευ ποιησαι εμε δε ου παντοτε εχετε[14:7]{.aside}

ο εσχεν αυτη [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον [ενταφιασμον]{.greek-omitted} [εν]{.greek-added}[14:8]{.aside}

[ο]{.greek-omitted} [εσχεν]{.greek-omitted} [αυτη]{.greek-omitted} [εποιησεν]{.greek-omitted} [προελαβεν]{.greek-omitted} [μυρισαι]{.greek-omitted} [μου]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [εις]{.greek-omitted} [τον]{.greek-omitted} [ενταφιασμον]{.greek-omitted} [ταφιασμον]{.greek-added}[14:8 | instance no. 2]{.aside}

αμην [δε]{.greek-added} λεγω υμιν οπου [εαν]{.greek-omitted} [αν]{.greek-added} κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης εις των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον αυτοις[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο αυτω [αργυριον]{.greek-omitted} [αργυρια]{.greek-added} δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται αυτου που θελεις απελθοντες ετοιμασωμεν ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των [μαθητων]{.greek-omitted} αυτου και λεγει αυτοις υπαγετε εις την πολιν και απαντησει υμιν [ανθρωπος]{.greek-omitted} [κεραμιον]{.greek-omitted} [υδατος]{.greek-omitted} [βασταζων]{.greek-omitted} [ακολουθησατε]{.greek-omitted} [αυτω]{.greek-omitted}[14:13]{.aside}

[και]{.greek-omitted} [αποστελλει]{.greek-omitted} [δυο]{.greek-omitted} [των]{.greek-omitted} [μαθητων]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [υπαγετε]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [πολιν]{.greek-omitted} [και]{.greek-omitted} [απαντησει]{.greek-omitted} [υμιν]{.greek-omitted} [ανθρωπος]{.greek-abbr} κεραμιον υδατος [βασταζων]{.greek-omitted} [βασταζοντα]{.greek-added} ακολουθησατε αυτω[14:13 | instance no. 2]{.aside}

και οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου φαγω[14:14]{.aside}

και αυτος υμιν δειξει [ανωγεον]{.greek-omitted} [ανογεον]{.greek-added} μεγα εστρωμενον ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον οι μαθηται αυτου και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας γενομενης ερχεται μετα [των]{.greek-omitted} δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων ειπεν ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν [αυτω]{.greek-omitted} [εις]{.greek-omitted} [καθ]{.greek-omitted} [εις]{.greek-omitted} [μητι]{.greek-omitted} [εγω]{.greek-omitted} [και]{.greek-omitted} [αλλος]{.greek-omitted} [μητι]{.greek-omitted} [εγω]{.greek-omitted}[14:19]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [ηρξαντο]{.greek-omitted} [λυπεισθαι]{.greek-omitted} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} εις καθ εις μητι εγω και αλλος μητι εγω[14:19 | instance no. 2]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο εμβαπτομενος μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο υιος του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο ανθρωπος εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και εδωκεν αυτοις και ειπεν λαβετε [φαγετε]{.greek-omitted} τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον [ευχαριστησας]{.greek-omitted} [ευχαρηστησας]{.greek-added} εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι [πολλων]{.greek-omitted} [εκχυνομενον]{.greek-omitted}[14:24]{.aside}

[και]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} [τουτο]{.greek-omitted} [εστιν]{.greek-omitted} [το]{.greek-omitted} [αιμα]{.greek-omitted} [μου]{.greek-omitted} [το]{.greek-omitted} [της]{.greek-omitted} [καινης]{.greek-omitted} [διαθηκης]{.greek-omitted} [το]{.greek-omitted} [περι]{.greek-omitted} πολλων εκχυνομενον[14:24 | instance no. 2]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη οτι γεγραπται παταξω τον ποιμενα και διασκορπισθησεται τα προβατα [της]{.greek-added} [φοιμνης]{.greek-added} [[ποιμνης]{.corr}]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος εφη αυτω και ει παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον εν τη [νυκτι]{.greek-omitted} [ταυτη]{.greek-omitted} [πριν]{.greek-omitted} [η]{.greek-omitted} [δις]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} [τρις]{.greek-omitted} [απαρνηση]{.greek-omitted} [με]{.greek-omitted}[14:30]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [σοι]{.greek-omitted} [οτι]{.greek-omitted} [συ]{.greek-omitted} [σημερον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} νυκτι ταυτη πριν η δις [αλεκτορα]{.greek-omitted} [αλεκτορ]{.greek-added} φωνησαι [τρις]{.greek-omitted} [τρεις]{.greek-added} απαρνηση με[14:30 | instance no. 2]{.aside}

ο δε [εκπερισσου]{.greek-omitted} [εκπερισου]{.greek-added} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} μαλλον εαν με δεη συναποθανειν σοι ου μη σε [απαρνησωμαι]{.greek-omitted} [απαρνησομαι]{.greek-added} ωσαυτως δε και παντες [ελεγον]{.greek-omitted} [ελεγων]{.greek-added}[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσημανι]{.greek-added} και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [προσευξωμαι]{.greek-omitted} [προσευξομαι]{.greek-added}[14:32]{.aside}

και παραλαμβανει τον πετρον και [ιακωβον]{.greek-omitted} [ιωακωβον]{.greek-added} και [τον]{.greek-added} ιωαννην μεθ εαυτου και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα [ει]{.greek-omitted} [δυνατον]{.greek-omitted} [εστιν]{.greek-omitted} [παρελθη]{.greek-omitted} [απ]{.greek-omitted} [αυτου]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted}[14:35]{.aside}

[ι]{.greek-added} [και]{.greek-omitted} [προσελθων]{.greek-omitted} [μικρον]{.greek-omitted} [επεσεν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [και]{.greek-omitted} [προσηυχετο]{.greek-omitted} [ινα]{.greek-omitted} [ει]{.greek-omitted} δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35 | instance no. 2]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} παντα δυνατα σοι παρενεγκε [απ]{.greek-added} [εμου]{.greek-added} το ποτηριον [απ]{.greek-omitted} [εμου]{.greek-omitted} τουτο αλλ ου τι εγω θελω αλλα τι συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων [καθευδης]{.greek-added} [καθευδεις]{.corr} ουκ ισχυσας μιαν ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων προσηυξατο τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας ευρεν αυτους παλιν καθευδοντας ησαν γαρ οι οφθαλμοι αυτων [βεβαρημενοι]{.greek-omitted} [καταβαρυνομενοι]{.greek-added} και ουκ ηδεισαν τι αυτω [αποκριθωσιν]{.greek-omitted} [αποκριθωσι]{.greek-added}[14:40]{.aside}

και ερχεται το [τριτον]{.greek-omitted} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [καθευδετε]{.greek-omitted} [λοιπον]{.greek-omitted} [και]{.greek-omitted} [αναπαυεσθε]{.greek-omitted} [απεχει]{.greek-omitted} [ηλθεν]{.greek-omitted} [η]{.greek-omitted} [ωρα]{.greek-omitted} [ιδου]{.greek-omitted} [παραδιδοται]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εις]{.greek-omitted} [τας]{.greek-omitted} [χειρας]{.greek-omitted} [των]{.greek-omitted} [αμαρτωλων]{.greek-omitted}[14:41]{.aside}

[και]{.greek-omitted} [ερχεται]{.greek-omitted} [το]{.greek-omitted} τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει ηλθεν η ωρα ιδου παραδιδοται ο υιος του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των αμαρτωλων[14:41 | instance no. 2]{.aside}

εγειρεσθε αγωμεν ιδου ο παραδιδους με ηγγικεν[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου οχλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γραμματεων και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον συσσημον αυτοις λεγων ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και ελθων ευθεως προσελθων [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} [ραββι]{.greek-omitted} [και]{.greek-omitted} [κατεφιλησεν]{.greek-omitted} [αυτον]{.greek-omitted}[14:45]{.aside}

[και]{.greek-omitted} [ελθων]{.greek-omitted} [ευθεως]{.greek-omitted} [προσελθων]{.greek-omitted} αυτω λεγει [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} [ραβι]{.greek-added} [ραββι]{.greek-omitted} [ραβι]{.greek-added} και κατεφιλησεν αυτον[14:45 | instance no. 2]{.aside}

οι δε επεβαλον [επ]{.greek-omitted} [αυτον]{.greek-omitted} τας χειρας αυτων [επ]{.greek-added} [αυτον]{.greek-added} και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος την μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην εξηλθετε μετα μαχαιρων και [ξυλ[ο]{.unclear}ν]{.greek-added} [ξυλων]{.corr} συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι[14:49]{.aside}

και αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω [περι]{.greek-added} [περιβεβλημενος]{.greek-omitted} [σινδονα]{.greek-omitted} [επι]{.greek-omitted} [γυμνου]{.greek-omitted} [και]{.greek-omitted} [κρατουσιν]{.greek-omitted} [αυτον]{.greek-omitted} [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[14:51]{.aside}

[και]{.greek-omitted} [εις]{.greek-omitted} [τις]{.greek-omitted} [νεανισκος]{.greek-omitted} [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted} [περιβεβλημενος]{.greek-omitted} [βεβλημενος]{.greek-added} [σινδονα]{.greek-omitted} [σινδωνα]{.greek-added} επι γυμνου και κρατουσιν αυτον οι νεανισκοι[14:51 | instance no. 2]{.aside}

ο δε [καταλιπων]{.greek-omitted} [καταλιπον]{.greek-added} την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και συνερχονται αυτω παντες οι αρχιερεις και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added} και οι [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added}[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως εσω εις την αυλην του αρχιερεως και ην συγκαθημενος μετα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι [μαρ]{.greek-added} [μαρτυριαι]{.greek-omitted} [ουκ]{.greek-omitted} [ησαν]{.greek-omitted}[14:56]{.aside}

[πολλοι]{.greek-omitted} [γαρ]{.greek-omitted} [εψευδομαρτυρουν]{.greek-omitted} [κατ]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [ισαι]{.greek-omitted} [αι]{.greek-omitted} [μαρτυριαι]{.greek-omitted} [τυριαι]{.greek-added} ουκ ησαν[14:56 | instance no. 2]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως ιση ην η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι [ουτοι]{.greek-omitted} [ουτι]{.greek-added} σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο παλιν ο αρχιερευς [επηρωτα]{.greek-omitted} [επερωτα]{.greek-added} αυτον και λεγει αυτω συ ει ο [χριστος]{.greek-abbr} ο υιος του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων [καθη]{.greek-added} [καθημενον]{.greek-omitted} [της]{.greek-omitted} [δυναμεως]{.greek-omitted} [και]{.greek-omitted} [ερχομενον]{.greek-omitted} [μετα]{.greek-omitted} [των]{.greek-omitted} [νεφελων]{.greek-omitted} [του]{.greek-omitted} [ουρανου]{.greek-omitted}[14:62]{.aside}

[μενον]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [εγω]{.greek-omitted} [ειμι]{.greek-omitted} [και]{.greek-omitted} [οψεσθε]{.greek-omitted} [τον]{.greek-omitted} [υιον]{.greek-omitted} [του]{.greek-omitted} [ανθρωπου]{.greek-omitted} [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [καθημενον]{.greek-omitted} της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62 | instance no. 2]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε της βλασφημιας τι υμιν φαινεται οι δε παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν [αυτω]{.greek-omitted} [αυτον]{.greek-added} και περικαλυπτειν το προσωπον αυτου και κολαφιζειν [αυτον]{.greek-omitted} [αυτω]{.greek-added} και λεγειν [αυτω]{.greek-omitted} προφητευσον και οι υπηρεται ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [ελαβον]{.greek-added}[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα τον πετρον θερμαινομενον [εμβλεψασα]{.greek-omitted} [εμβλεψας]{.greek-added} αυτω λεγει και συ μετα του [ναζαρηνου]{.greek-omitted} [ιησου]{.greek-omitted} [ησθα]{.greek-omitted}[14:67]{.aside}

[και]{.greek-omitted} [ιδουσα]{.greek-omitted} [τον]{.greek-omitted} [πετρον]{.greek-omitted} [θερμαινομενον]{.greek-omitted} [εμβλεψασα]{.greek-omitted} [αυτω]{.greek-omitted} [λεγει]{.greek-omitted} [και]{.greek-omitted} [συ]{.greek-omitted} [μετα]{.greek-omitted} [του]{.greek-omitted} [ναζαρηνου]{.greek-omitted} [ναζαρινου]{.greek-added} [ιησου]{.greek-abbr} ησθα[14:67 | instance no. 2]{.aside}

ο δε ηρνησατο [αυτον]{.greek-added} λεγων ουκ οιδα ουδε [επισταμαι]{.greek-omitted} [επισταμε]{.greek-added} τι [συ]{.greek-omitted} λεγεις και εξηλθεν εξω εις το προαυλιον και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

και η παιδισκη ιδουσα αυτον παλιν ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστωσιν]{.greek-added} οτι ουτος εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω [αληθως]{.greek-omitted} [αλληθως]{.greek-added} εξ αυτων ει και γαρ γαλιλαιος ει και η λαλια σου ομοιαζει[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυειν]{.greek-added} οτι ουκ οιδα τον ανθρωπον τουτον ον λεγετε[14:71]{.aside}

και εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και ανεμνησθη ο πετρος το ρημα [ο]{.greek-omitted} [ως]{.greek-added} ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν [αλεκτορα]{.greek-omitted} [αλεκτωρ]{.greek-added} φωνησαι δις [απαρνηση]{.greek-omitted} [με]{.greek-omitted} [τρις]{.greek-omitted} [και]{.greek-omitted} [επιβαλων]{.greek-omitted} [εκλαιεν]{.greek-omitted}[14:72]{.aside}

[και]{.greek-omitted} [εκ]{.greek-omitted} [δευτερου]{.greek-omitted} [αλεκτωρ]{.greek-omitted} [εφωνησεν]{.greek-omitted} [και]{.greek-omitted} [ανεμνησθη]{.greek-omitted} [ο]{.greek-omitted} [πετρος]{.greek-omitted} [το]{.greek-omitted} [ρημα]{.greek-omitted} [ο]{.greek-omitted} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [οτι]{.greek-omitted} [πριν]{.greek-omitted} [αλεκτορα]{.greek-omitted} [φωνησαι]{.greek-omitted} [δις]{.greek-omitted} απαρνηση με [τρις]{.greek-omitted} [τρεις]{.greek-added} και [επιβαλων]{.greek-omitted} [επιβαλον]{.greek-added} εκλαιεν[14:72 | instance no. 2]{.aside}

### Chapter 15

και ευθεως επι το πρωι συμβουλιον ποιησαντες οι αρχιερεις μετα των πρεσβυτερων και γραμματεων και ολον το συνεδριον δησαντες τον [ιησουν]{.greek-abbr} απηνεγκαν και παρεδωκαν τω πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις ειπεν αυτω συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον λεγων ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε [εορτην]{.greek-omitted} [απελυεν]{.greek-omitted} [αυτοις]{.greek-omitted} [ενα]{.greek-omitted} [δεσμιον]{.greek-omitted} [ονπερ]{.greek-omitted} [ητουντο]{.greek-omitted}[15:6]{.aside}

[κατα]{.greek-omitted} [δε]{.greek-omitted} εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} [ητουντο]{.greek-omitted} [περητουντο]{.greek-added}[15:6 | instance no. 2]{.aside}

ην δε ο λεγομενος [βαραββας]{.greek-omitted} [βαραβας]{.greek-added} μετα των συστασιαστων δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει [εποιει]{.greek-omitted} [εποιη]{.greek-added} αυτοις[15:8]{.aside}

ο δε πιλατος απεκριθη αυτοις λεγων θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [επεγινωσκε]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδωκεισαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος αποκριθεις παλιν ειπεν αυτοις τι ουν θελετε ποιησω ον λεγετε βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν εκραξαν [λεγοντες]{.greek-added} σταυρωσον αυτον[15:13]{.aside}

ο δε π[ιλ]{.unclear}ατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [εκραξαν]{.greek-omitted} [περισως]{.greek-added} [εκραζον]{.greek-added} σταυρωσον αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος τω οχλω το ικανον ποιησαι απελυσεν αυτοις τον βαραββαν και [παρεδωκεν]{.greek-omitted} [παρεδωκε]{.greek-added} τον [ιησουν]{.greek-abbr} [φραγελλωσας]{.greek-omitted} [φραγγελλωσας]{.greek-added} ινα σταυρωθη[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω της αυλης ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και ενδυουσιν αυτον πορφυραν και [περιτιθεασιν]{.greek-omitted} [περιτηνθεασιν]{.greek-added} αυτω πλεξαντες ακανθινον στεφανον[15:17]{.aside}

και ηρξαντο [ασπαζεσθαι]{.greek-omitted} [ασπαζεσθε]{.greek-added} αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον [αυτου]{.greek-omitted} την κεφαλην [αυτου]{.greek-added} [καλαμω]{.greek-omitted} [κλαμω]{.greek-added} και ενεπτυον [αυτω]{.greek-omitted} [και]{.greek-omitted} [τιθεντες]{.greek-omitted} [τα]{.greek-omitted} [γονατα]{.greek-omitted} [προσεκυνουν]{.greek-omitted} [αυτω]{.greek-omitted}[15:19]{.aside}

[και]{.greek-omitted} [ετυπτον]{.greek-omitted} [αυτου]{.greek-omitted} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [καλαμω]{.greek-omitted} [και]{.greek-omitted} [ενεπτυον]{.greek-omitted} αυτω και τιθεντες τα γονατα [προσεκυνουν]{.greek-omitted} [προσεκυνον]{.greek-added} [αυτω]{.greek-omitted} [αυτον]{.greek-added}[15:19 | instance no. 2]{.aside}

και οτε [ενεπεξαν]{.greek-added} [ενεπαιξαν]{.corr} [αυτω]{.greek-omitted} [αυτον]{.greek-added} εξεδυσαν αυτον την πορφυραν και ενεδυσαν αυτον τα [ιδια]{.greek-added} ιματια [τα]{.greek-omitted} [ιδια]{.greek-omitted} και εξαγουσιν αυτον ινα [σταυρωθει]{.greek-added} [σταυρωσωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα τινα σιμωνα κυρηναιον ερχομενον απ αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ ελαβεν[15:23]{.aside}

και σταυρωσαντες αυτον διαμεριζονται τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε [τριτη]{.greek-added} ωρα [τριτη]{.greek-omitted} [και]{.greek-omitted} [εσταυρωσαν]{.greek-omitted} [αυτον]{.greek-omitted}[15:25]{.aside}

[ην]{.greek-omitted} [δε]{.greek-omitted} [ωρα]{.greek-omitted} [τριτη]{.greek-omitted} και εσταυρωσαν αυτον[15:25 | instance no. 2]{.aside}

και ην η επιγραφη της αιτιας αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [συσταυρουσι]{.greek-added} δυο ληστας ενα εκ δεξιων [αυτου]{.greek-added} και ενα εξ [ευονυμων]{.greek-added} [ευωνυμων]{.corr} [αυτου]{.greek-omitted}[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας αυτων και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον και καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες προς αλληλους μετα των [γραμματαιων]{.greek-added} [γραμματεων]{.corr} ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} ο [βασι]{.greek-added} [βασιλευς]{.greek-omitted} [του]{.greek-omitted} [ισραηλ]{.greek-omitted} [καταβατω]{.greek-omitted} [νυν]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [σταυρου]{.greek-omitted} [ινα]{.greek-omitted} [ιδωμεν]{.greek-omitted} [και]{.greek-omitted} [πιστευσωμεν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [οι]{.greek-omitted} [συνεσταυρωμενοι]{.greek-omitted} [αυτω]{.greek-omitted} [ωνειδιζον]{.greek-omitted} [αυτον]{.greek-omitted}[15:32]{.aside}

[λευς]{.greek-added} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [του]{.greek-omitted} [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν [αυτω]{.greek-omitted} και οι [συνεσταυρωμενοι]{.greek-abbr} [αυτω]{.greek-omitted} [αυτον]{.greek-added} ωνειδιζον αυτον[15:32 | instance no. 2]{.aside}

γενομενης δε ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας ενατης[15:33]{.aside}

και τη ωρα τη ενατη εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι λιμα σαβαχθανι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} [μου]{.greek-omitted} ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον [οτι]{.greek-added} ιδου ηλιαν φωνει[15:35]{.aside}

δραμων δε εις και γεμισας σπογγον οξους περιθεις τε καλαμω εποτιζεν αυτον λεγων αφετε ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην εξεπνευσεν[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως εξ εναντιας αυτου οτι ουτως κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} ην [του]{.greek-added} [θεου]{.greek-abbr}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην και μαρια η μαγδαληνη και μαρια [η]{.greek-omitted} [του]{.greek-omitted} ιακωβου του μικρου και ιωση [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο αριμαθαιας ευσχημων βουλευτης ος και αυτος ην [προσδεχομενος]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [τολμησας]{.greek-omitted} [εισηλθεν]{.greek-omitted} [προς]{.greek-omitted} [προσ]{.greek-added} [πιλατον]{.greek-omitted} [και]{.greek-omitted} [ητησατο]{.greek-omitted} [το]{.greek-omitted} [σωμα]{.greek-omitted} [του]{.greek-omitted} [ιησου]{.greek-omitted}[15:43]{.aside}

[ηλθεν]{.greek-omitted} [ιωσηφ]{.greek-omitted} [ο]{.greek-omitted} [απο]{.greek-omitted} [αριμαθαιας]{.greek-omitted} [ευσχημων]{.greek-omitted} [βουλευτης]{.greek-omitted} [ος]{.greek-omitted} [και]{.greek-omitted} [αυτος]{.greek-omitted} [ην]{.greek-omitted} [προσδεχομενος]{.greek-omitted} [δεχομενος]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43 | instance no. 2]{.aside}

ο δε πιλατος [εθαυμασεν]{.greek-omitted} ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added}[15:44]{.aside}

και γνους απο του κεντυριωνος εδωρησατο [το]{.greek-omitted} [σωμα]{.greek-omitted} τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλησε]{.greek-added} τη σινδονι και κατεθηκεν [[κατεθεικεν]{.corr}]{.greek-added} αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε μαρια η [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} και μαρια ιωση εθεωρουν που [τιθεται]{.greek-omitted} [τεθειται]{.greek-added}[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου μαρια η μαγδαληνη και μαρια [η]{.greek-added} [του]{.greek-added} ιακωβου και σαλωμη ηγορασαν [αρωματα]{.greek-omitted} [ινα]{.greek-omitted} [ελθουσαι]{.greek-omitted} [αλειψωσιν]{.greek-omitted} [αυτον]{.greek-omitted}[16:1]{.aside}

[και]{.greek-omitted} [διαγενομενου]{.greek-omitted} [του]{.greek-omitted} [σαββατου]{.greek-omitted} [μαρια]{.greek-omitted} [η]{.greek-omitted} [μαγδαληνη]{.greek-omitted} [και]{.greek-omitted} [μαρια]{.greek-omitted} [ιακωβου]{.greek-omitted} [και]{.greek-omitted} [σαλωμη]{.greek-omitted} [ηγορασαν]{.greek-omitted} αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1 | instance no. 2]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται [επι]{.greek-omitted} [προς]{.greek-added} το μνημειον [ετι]{.greek-added} ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις [αποκυλισει]{.greek-omitted} [αποκυλιση]{.greek-added} ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον [ειδον]{.greek-omitted} [ιδον]{.greek-added} νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη εκθαμβεισθε [ιησουν]{.greek-abbr} ζητειτε τον [ναζαρηνον]{.greek-omitted} [ναζαρινον]{.greek-added} τον εσταυρωμενον ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις [αυ]{.greek-added} [αυτου]{.greek-omitted} [και]{.greek-omitted} [τω]{.greek-omitted} [πετρω]{.greek-omitted} [οτι]{.greek-omitted} [προαγει]{.greek-omitted} [υμας]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γαλιλαιαν]{.greek-omitted} [εκει]{.greek-omitted} [αυτον]{.greek-omitted} [οψεσθε]{.greek-omitted} [καθως]{.greek-omitted} [ειπεν]{.greek-omitted} [υμιν]{.greek-omitted}[16:7]{.aside}

[αλλ]{.greek-omitted} [υπαγετε]{.greek-omitted} [ειπατε]{.greek-omitted} [τοις]{.greek-omitted} [μαθηταις]{.greek-omitted} [αυτου]{.greek-omitted} [του]{.greek-added} και τω πετρω οτι προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7 | instance no. 2]{.aside}

και εξελθουσαι εφυγον απο του μνημειου ειχεν δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη [σαββατου]{.greek-omitted} [σαββατων]{.greek-added} εφανη πρωτον μαρια τη [μαγδαληνη]{.greek-omitted} [μαγδαλινη]{.greek-added} αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη [πορευθεισα]{.greek-omitted} [απελθουσα]{.greek-added} [και]{.greek-added} [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου [γενομενης]{.greek-added} [γενομενοις]{.corr} [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι [απελθοντες]{.greek-omitted} [απελθον]{.greek-added} [απηγγειλαν]{.greek-omitted} [τοις]{.greek-omitted} [λοιποις]{.greek-omitted} [ουδε]{.greek-omitted} [εκεινοις]{.greek-omitted} [επιστευσαν]{.greek-omitted}[16:13]{.aside}

[τες]{.greek-added} [κακεινοι]{.greek-omitted} [απελθοντες]{.greek-omitted} απηγγειλαν τοις λοιποις ουδε εκεινοις επιστευσαν[16:13 | instance no. 2]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την [απιστιαν]{.greek-omitted} [απιστειαν]{.greek-added} αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα [παρακολουθησει]{.greek-omitted} [παρακολουθουσει]{.greek-added} εν τω ονοματι μου δαιμονια [εκβαλουσιν]{.greek-omitted} [εκβαλουσι]{.greek-added} γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι [αρρω]{.greek-added} [αρρωστους]{.greek-omitted} [χειρας]{.greek-omitted} [επιθησουσιν]{.greek-omitted} [και]{.greek-omitted} [καλως]{.greek-omitted} [εξουσιν]{.greek-omitted}[16:18]{.aside}

[στους]{.greek-added} [οφεις]{.greek-omitted} [αρουσιν]{.greek-omitted} [καν]{.greek-omitted} [θανασιμον]{.greek-omitted} [τι]{.greek-omitted} [πιωσιν]{.greek-omitted} [ου]{.greek-omitted} [μη]{.greek-omitted} [αυτους]{.greek-omitted} [βλαψη]{.greek-omitted} [επι]{.greek-omitted} [αρρωστους]{.greek-omitted} χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18 | instance no. 2]{.aside}

ο μεν [[ιησους]{.greek-abbr}]{.greek-added} [ουν]{.greek-omitted} [κυριος]{.greek-omitted} μετα το λαλησαι αυτοις ανεληφθη εις [τον]{.greek-omitted} [τους]{.greek-added} [ουρανον]{.greek-omitted} [[ουρανους]{.greek-abbr}]{.greek-added} και [εκαθισεν]{.greek-omitted} [εκαθησεν]{.greek-added} εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

