---
title: "Collation of Byz^RP^ vs 32538 (2538)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2538 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32538).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2538                                   	| λογος                              	|
| 2538 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2538 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2538               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2538                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2538 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2538                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

η δε πενθερα σιμωνος κατεκειτο π[υ]{.unclear}ρεσσο[υσα]{.greek-supplied} [και]{.greek-supplied} [ευ]{.greek-supplied}θεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος [αυτης]{.greek-omitted} [αυτου]{.greek-added} και αφηκεν αυτην ο πυρετος ευθεως και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και η πολις ολη επισυνηγμενη ην προς την θυραν[1:33]{.aside}

και [εθεραπευσεν]{.greek-omitted} [εθεραπευσε]{.greek-added} πολλους κακως εχον[τ]{.unclear}[ας]{.greek-supplied} ποικιλαις νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι [ηδεισαν]{.greek-omitted} [ηδισαν]{.greek-added} αυτον[1:34]{.aside}

και πρωι [εννυχον]{.greek-omitted} [εννυ[χ]{.unclear}[α]{.greek-supplied}]{.greek-added} [λιαν]{.greek-omitted} αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

### Chapter 3

[και]{.greek-omitted} [λεγει]{.greek-omitted} [τω]{.greek-omitted} [ανθρωπω]{.greek-omitted} [τω]{.greek-omitted} [εξηραμμενην]{.greek-omitted} [[ραμμε]{.greek-supplied}νην]{.greek-added} εχοντι την χειρα εγειραι εις το μεσον[3:3]{.aside}

και λεγει αυτοις [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τ[ο]{.unclear}[ις]{.greek-supplied} [σαβ]{.greek-supplied}βασ[ι]{.unclear}ν αγαθοποιησαι η κακοποιησαι ψυχην σωσαι η αποκτειναι [οι]{.greek-supplied} [δε]{.greek-supplied} [ε]{.greek-supplied}σιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ ο[ρ]{.unclear}[γ]{.greek-supplied}ης συλλυπουμενος επι τη πωρωσει της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρ[α]{.unclear} σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και αποκατεσταθη η χειρ αυτου υγ[ι]{.unclear}ης ως η αλλη[3:5]{.aside}

και εξελθοντες οι φαρισαιοι ευθεως μετα των ηρωδιανων συμβουλιον εποιουν κα[τ]{.greek-supplied} αυτο[υ]{.unclear} οπως αυτον [απολεσωσιν]{.greek-omitted} [απολεσωσι]{.greek-added}[3:6]{.aside}

και ο [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} [ανεχωρησε]{.greek-added} μετα των μαθητων αυτου προς την θαλασσαν και πολυ πληθος απο της γαλιλαιας ηκολουθησαν αυτω και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων και απο της ιδουμαιας και περαν του ιορδανου και οι περι τυρον και σιδωνα πληθος πολυ ακουσαντες οσα [εποιει]{.greek-omitted} [[μ]{.unclear}ενοιει]{.greek-added} ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοια[ρ]{.unclear}ιον προσκαρτερη αυτω δια τον [ο]{.unclear}χλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ εθεραπευσεν ωστε επιπιπτειν αυτω ινα αυτου αψωνται οσοι ειχον μαστιγας[3:10]{.aside}

και τα [πνευματα]{.greek-abbr} τα ακαθαρτα οταν αυτον εθεωρει προσεπιπτεν αυτω και [εκραζεν]{.greek-omitted} [ε[κ]{.unclear}[ρ]{.greek-supplied}αζε]{.greek-added} λεγοντα οτι συ ει ο υιος του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη φανερον αυ[τον]{.unclear} ποιησωσιν[3:12]{.aside}

[και]{.unclear} [α]{.unclear}ναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα αποστελλη αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξ[ο]{.unclear}υσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

