---
title: "Collation of Byz^RP^ vs 32542 (2542)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2542 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32542).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2542                                   	| λογος                              	|
| 2542 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2542 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2542               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2542                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2542 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2542                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Mark

### Chapter 1

αρχη του ευαγγελιου [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου του [θεου]{.greek-abbr}[1:1]{.aside}

ως γεγραπται εν τοις προφηταις ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[1:2]{.aside}

φωνη [β]{.unclear}οωντος εν τη ερημω ετοιμασατε την οδον [κυριου]{.greek-abbr} ευθειας ποιειτε τας τριβους αυτου[1:3]{.aside}

εγενετο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} βαπτιζων εν τη ερημω και κηρυσσων βαπ[τι]{.unclear}σμα μετανοιας εις αφεσιν αμαρτιων[1:4]{.aside}

και εξεπορευετο προς αυτον πασα η ιουδαια χωρα και οι ιεροσολυμιται [παντες]{.greek-added} και εβαπτιζοντο [παντες]{.greek-omitted} εν τω ιορδανη [ποταμω]{.greek-omitted} υπ αυτου εξομολογου[μ]{.unclear}ενοι τας αμαρτιας αυτων[1:5]{.aside}

ην δε ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ενδεδυμενος τριχας καμηλου και ζωνην δερματινην περι την οσφυν αυτου και εσθιων ακριδας και [μ]{.unclear}ελι αγριον[1:6]{.aside}

και [εκηρυσσεν]{.greek-omitted} [εκηρυσσε]{.greek-added} λεγων ερχεται ο [ισχυ]{.greek-added} [ρωτερος]{.greek-added} [ισχυροτερος]{.greek-omitted} [μου]{.greek-omitted} [οπισω]{.greek-omitted} μου ου ουκ ειμι ικανος κυψας λυσαι τον ιμαντα των υποδηματων αυτου[1:7]{.aside}

εγω [μεν]{.greek-omitted} εβαπτισα υμας εν υδατι αυτος δε βαπτισει υμας εν [πνευματι]{.greek-abbr} αγιω[1:8]{.aside}

και εγενετο εν εκειναις ταις ημεραις ηλθεν [ο]{.greek-added} [ιησους]{.greek-abbr} απο ναζαρετ της γαλιλαιας και εβαπτισθη [υπο]{.greek-omitted} [ιωαννου]{.greek-omitted} εις τον ιορδανην [υπο]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added}[1:9]{.aside}

και ευθεως αναβαινων [απο]{.greek-omitted} [εκ]{.greek-added} του υδατος [ειδεν]{.greek-omitted} [ειδε]{.greek-added} σχιζομενους τους [ουρανους]{.greek-abbr} και το [πνευμα]{.greek-abbr} ωσει πε[ρι]{.greek-supplied}στεραν καταβαινον επ αυτον[1:10]{.aside}

και φωνη εγενετο εκ των [ουρανων]{.greek-abbr} συ ει ο [υιος]{.greek-abbr} μου ο αγαπητος εν [ω]{.greek-omitted} [σοι]{.greek-added} [ευδοκησα]{.greek-omitted} [ηυδοκησα]{.greek-added}[1:11]{.aside}

και [ευθυς]{.greek-omitted} [ευθεως]{.greek-added} το [πνευμα]{.greek-abbr} [εκβαλλει]{.greek-added} αυτον [εκβαλλει]{.greek-omitted} εις την ερημον[1:12]{.aside}

και ην εκει [επι]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} ημερας τεσσαρακοντα πειραζομενος υπο του [σατανα]{.greek-omitted} [διαβολου]{.greek-added} και ην μετα των θηριων και οι αγγελοι διηκονουν αυτω[1:13]{.aside}

μετα δε το παραδοθηναι [[ιω]{.greek-abbr}]{.greek-added} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} ηλθεν ο [ιησους]{.greek-abbr} εις την γαλιλαιαν κηρυσσων το ευαγγελιον της βασιλειας του [θεου]{.greek-abbr}[1:14]{.aside}

και λεγων οτι [πεπληρωται]{.greek-omitted} [πεπλη]{.greek-added} [ρωται]{.greek-added} ο καιρος και ηγγικεν η βασιλεια του [θεου]{.greek-abbr} μετανοειτε και πιστευετε εν τω ευα[γ]{.unclear}γ[ε]{.unclear}λιω[1:15]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδ[ε]{.unclear}]{.greek-added} σιμωνα και ανδρεαν τον αδελφον αυτου [αμφιβληστρον]{.greek-added} [του]{.greek-omitted} [σιμωνος]{.greek-omitted} βαλλοντας [αμφιβληστρον]{.greek-omitted} εν τη θαλασση ησαν γαρ αλιεις[1:16]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} δευτε οπισω μου και ποιησω υμας γενεσθαι αλιεις [ανθρωπων]{.greek-abbr}[1:17]{.aside}

και ευθεως αφεντες τα δικτυα [αυτων]{.greek-omitted} ηκολουθησαν αυτω[1:18]{.aside}

και προβας εκειθεν ολιγον ειδεν ιακωβον τον του ζεβεδαιου και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον αυτου [και]{.greek-omitted} [αυτους]{.greek-omitted} εν τω πλοιω καταρτιζοντας τα δικτυα[1:19]{.aside}

και [ευθεως]{.greek-omitted} εκαλεσεν αυτους και [ευθεως]{.greek-added} αφεντες τον [πατερα]{.greek-abbr} αυτων ζεβεδαιον εν τω πλοιω μετα των μισθωτων απηλθον οπισω αυτου[1:20]{.aside}

και [εισπορευονται]{.greek-omitted} [εισεπορευοντο]{.greek-added} εις καπερναουμ και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} τοις σαββασιν εισελθων εις την συναγωγην [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added}[1:21]{.aside}

και εξεπλησσοντο επι τη διδαχη αυτου ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[1:22]{.aside}

και ην εν τη συναγωγη αυτων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} ακαθαρτω [συνεχομενος]{.greek-added} και [ανεκραξεν]{.greek-omitted} [ανεκραξε]{.greek-added}[1:23]{.aside}

λεγων [εα]{.greek-omitted} τι ημιν και σοι [ιησου]{.greek-abbr} ναζαρηνε ηλθες απολεσαι ημας οιδα σε τις ει ο αγιος του [θεου]{.greek-abbr}[1:24]{.aside}

και επετιμησεν αυτω ο [ιησους]{.greek-abbr} λεγων φιμωθητι και εξελθε εξ αυτου[1:25]{.aside}

και σπαραξαν αυτον το [πνευμα]{.greek-abbr} το ακαθαρτον και κραξαν φωνη μεγαλη εξηλθεν εξ αυτου[1:26]{.aside}

και εθαμβηθησαν παντες ωστε συζητειν προς εαυτους λεγοντας τι [εστιν]{.greek-omitted} [εστι]{.greek-added} τουτο τις η διδαχη η καινη αυτη οτι κατ εξουσιαν και τοις [πνευμασιν]{.greek-omitted} [πνευμασι]{.greek-added} τοις ακαθαρτοις επιτασσει και υπακουουσιν [αυτω]{.greek-omitted} [αυτου]{.greek-added}[1:27]{.aside}

[και]{.greek-added} εξηλθεν [δε]{.greek-omitted} η ακοη αυτου [ευθυς]{.greek-omitted} εις ολην την περιχωρον της γαλιλαιας[1:28]{.aside}

και ευθεως εκ της συναγωγης εξελθοντες ηλθον εις την οικιαν σιμωνος και ανδρεου μετα ιακωβου και ιωαννου[1:29]{.aside}

η δε πενθερα σιμωνος κατεκειτο πυρεσσουσα και ευθεως λεγουσιν αυτω περι αυτης[1:30]{.aside}

και προσελθων ηγειρεν αυτην κρατησας της χειρος αυτης και αφηκεν αυτην ο πυρετος [ευθεως]{.greek-omitted} και διηκονει αυτοις[1:31]{.aside}

οψιας δε γενομενης οτε εδυ ο ηλιος εφερον προς αυτον παντας τους κακως εχοντας και τους δαιμονιζομενους[1:32]{.aside}

και [ην]{.greek-added} η πολις ολη επισυνηγμενη [ην]{.greek-omitted} προς [την]{.greek-omitted} [τας]{.greek-added} [θυραν]{.greek-omitted} [θυρας]{.greek-added}[1:33]{.aside}

και εθεραπευσεν [πολλους]{.greek-omitted} [αυτους]{.greek-added} κακως εχοντας [ποικιλαις]{.greek-omitted} [ποικιλλαις]{.greek-added} νοσοις και δαιμονια πολλα [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} και ουκ [ηφιεν]{.greek-omitted} [ηφιε]{.greek-added} λαλειν τα δαιμονια οτι ηδεισαν αυτον [[χριστον]{.greek-abbr}]{.greek-added} [ειναι]{.greek-added}[1:34]{.aside}

και πρωι [εννυχον]{.greek-omitted} [εννυχα]{.greek-added} λιαν αναστας [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και απηλθεν εις ερημον τοπον κακει προσηυχετο[1:35]{.aside}

και [κατεδιωξαν]{.greek-omitted} [κατεδιωξεν]{.greek-added} [οπισω]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added} ο σιμων και οι μετ αυτου[1:36]{.aside}

και ευροντες αυτον λεγουσιν αυτω οτι παντες [ζητουσι]{.greek-added} σε [ζητουσιν]{.greek-omitted}[1:37]{.aside}

και λεγει αυτοις αγωμεν εις τας εχομενας κωμοπολεις ινα και [ε]{.greek-supplied}[κ]{.unclear}ει κηρυξω εις τουτο γαρ [εξεληλυθα]{.greek-omitted} [απεσταλην]{.greek-added}[1:38]{.aside}

και ην κηρυσσων [εν]{.greek-omitted} [εις]{.greek-added} [ταις]{.greek-omitted} [τας]{.greek-added} [συναγωγαις]{.greek-omitted} [συναγωγας]{.greek-added} αυτων εις ολην την γαλιλαιαν και [τα]{.greek-omitted} δαιμονια [πολλα]{.greek-added} εκβαλλ[ω]{.unclear}ν[1:39]{.aside}

και ερχεται προς αυτον λεπρος παρακαλων αυτον και γονυπετων [αυτον]{.greek-omitted} και λεγων αυτω οτι εαν θελης δυνασαι με καθαρισαι[1:40]{.aside}

ο δε [ιησους]{.greek-abbr} σπλαγχνισθεις εκτεινας την χειρα ηψατο αυτου και λεγει αυτω θελω καθαρισθητι[1:41]{.aside}

και ειποντος αυτου ευθεως απηλθεν απ αυτου η λεπρα και εκαθαρισθη[1:42]{.aside}

και εμβριμησαμενος [αυτω]{.greek-omitted} [αυτον]{.greek-added} ευθεως εξεβαλεν αυτον[1:43]{.aside}

[ειπων]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} αυτω [ορα]{.greek-omitted} [αρα]{.greek-added} μηδενι [μηδεν]{.greek-omitted} ειπης αλλ υπαγε σεαυτον δειξον τω ιερει και [προσενεγκε]{.greek-omitted} [προσενεγκαι]{.greek-added} περι του καθαρισμου σου α [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[1:44]{.aside}

ο δε εξελθων ηρξατο κηρυσσειν πολλα και διαφημιζειν τον λογον ωστε μηκετι αυτον δυνασθαι [φανερως]{.greek-omitted} εις πολιν [φανερως]{.greek-added} εισελθειν αλλ εξω [εν]{.greek-omitted} [επ]{.greek-added} ερημοις τοποις ην και ηρχοντο προς αυτον [πανταχοθεν]{.greek-omitted} [παντοθεν]{.greek-added}[1:45]{.aside}

### Chapter 2

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις καπερναουμ δι ημερων και ηκουσθη οτι εις οικον [εστιν]{.greek-omitted} [εστι]{.greek-added}[2:1]{.aside}

και ευθεως συνηχθησαν πολλοι ωστε μηκετι χωρειν μηδε τα προς την θυραν και ελαλει αυτοις τον λογον[2:2]{.aside}

και ερχονται προς αυτο[ν]{.unclear} παραλυτικον φεροντες αιρομενον υπο τεσσαρων[2:3]{.aside}

και μη δυναμενοι προσεγγισαι αυτω δια τον οχλον απεστεγασαν την στεγην οπου ην και εξορυξαντες [χαλωσιν]{.greek-omitted} [χαλωσι]{.greek-added} τον κραββατον εφ ω ο παραλυτικος κατεκειτο[2:4]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} την πιστιν αυτων λεγει τω παραλυτικω τεκνον [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} σοι αι αμαρτιαι [σου]{.greek-omitted}[2:5]{.aside}

ησαν δε τινες των γραμματεων εκει καθημενοι και διαλογιζομενοι εν ταις καρδιαις αυτων[2:6]{.aside}

τι ουτος ουτως λαλει βλασφημιας τις δυναται αφιεναι αμαρτιας ει μη εις ο [θεος]{.greek-abbr}[2:7]{.aside}

και ευθεως επιγνους ο [ιησους]{.greek-abbr} τω [πνευματι]{.greek-abbr} [αυτου]{.unclear} οτι ουτως [αυτοι]{.greek-omitted} διαλογιζονται εν εαυτοις ειπεν αυτοις τι ταυτα διαλογιζεσθε εν ταις καρδιαις υμων[2:8]{.aside}

τι εστιν ευκοπωτερον ειπειν τω παραλυτικω [αφεωνται]{.greek-omitted} [αφεονται]{.greek-added} [σου]{.greek-omitted} [σοι]{.greek-added} αι αμαρτιαι η ειπειν εγειραι και αρον σου τον κραββατον και περιπατει[2:9]{.aside}

ινα δε ειδητε οτι εξουσιαν εχει ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [αφιεναι]{.greek-omitted} επι της γης [αφιεναι]{.greek-added} αμαρτιας λεγει τ[ω]{.unclear} παραλυτικω[2:10]{.aside}

σοι λεγω εγειραι [και]{.greek-omitted} αρον τον κραββατον σου και υπαγε εις τον οικον σου[2:11]{.aside}

και ηγερθη ευθεως και αρας τον κραββατον εξηλθεν εναντιον παντων ωστε εξιστασθαι παντας και δοξαζειν τον [θεον]{.greek-abbr} λεγοντας οτι ουδεποτε ουτως [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added}[2:12]{.aside}

και [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} παλιν παρα την θαλασσαν και πας ο οχλος ηρχετο προς αυτον και εδιδασκεν αυτους[2:13]{.aside}

και παραγων [ειδεν]{.greek-omitted} [ειδε]{.greek-added} λευι τον του αλφαιου καθημενον επι το [τελωνιον]{.greek-omitted} [τελωνειον]{.greek-added} και λεγει αυτω [α]{.unclear}κολουθει μοι και αναστας ηκολουθησεν αυτω[2:14]{.aside}

και εγενετο εν τω κατακεισθαι αυτον εν τη οικια αυτου και πολλοι τελωναι και αμαρτωλοι συνανεκειντο τω ιησου και τοις μαθηταις αυτου ησαν γαρ πολλοι και ηκολουθησαν αυτω[2:15]{.aside}

και οι γραμματεις και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ιδοντες αυτον εσθιοντα μετα των τελωνων και αμαρτωλων ελεγον τοις μαθηταις αυτου τι οτι μετα των τελωνων και αμαρτωλων εσθιει και πινει[2:16]{.aside}

[και]{.greek-omitted} ακουσας [δε]{.greek-added} ο [ιησους]{.greek-abbr} λεγει αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες ουκ ηλθον καλεσαι δικαιους αλλα αμαρτωλους εις μετανοιαν[2:17]{.aside}

και ησαν οι μαθηται [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και οι των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} νηστευοντες και ερχονται και λεγουσιν αυτω δια τι οι μαθηται ιωαννου και οι των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} νηστευουσιν οι δε [σοι]{.greek-omitted} μαθηται [σου]{.greek-added} ου [νηστευουσιν]{.greek-omitted} [νηστευουσι]{.greek-added}[2:18]{.aside}

και ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος εν ω ο νυμφιος μετ αυτων [εστιν]{.greek-omitted} [εστι]{.greek-added} νηστευειν οσον χρονον [εχουσι]{.greek-added} [τον]{.greek-added} [νυμφιον]{.greek-added} μεθ εαυτων [εχουσιν]{.greek-omitted} [τον]{.greek-omitted} [νυμφιον]{.greek-omitted} ου δυνανται νηστευειν[2:19]{.aside}

ελευσονται δε ημεραι οταν [απαρθη]{.greek-omitted} [αρθη]{.greek-added} [απ]{.greek-omitted} [αυτων]{.greek-omitted} ο νυμφιος και τοτε νηστευσουσιν εν εκειναις ταις ημεραις[2:20]{.aside}

[και]{.greek-omitted} ουδεις [δε]{.greek-added} επιβλημα ρακους αγναφου [επιρραπτει]{.greek-omitted} [επιρριπτει]{.greek-added} επι ιματιω παλαιω ει δε [μη]{.greek-omitted} [μηγε]{.greek-added} αιρει το [επιβλημα]{.greek-added} [πληρωμα]{.greek-omitted} [αυτου]{.greek-omitted} το καινον [απο]{.greek-added} του παλαιου και χειρον σχισμα γινεται[2:21]{.aside}

και ουδεις βαλλει οινον νεον εις ασκους παλαιους ει δε [μη]{.greek-omitted} [μηγε]{.greek-added} ρησσει ο οινος ο νεος τους ασκους και ο οινος εκχειται και οι ασκοι απολουνται [αλλα]{.greek-omitted} [αλλ]{.greek-added} οινον νεον εις ασκους καινους βλητεον[2:22]{.aside}

και εγενετο παραπορευεσθαι αυτον εν τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων και [ηρξαντο]{.greek-omitted} οι μαθηται αυτου [ηρξαντο]{.greek-added} οδον ποιειν τιλλοντες τους σταχυας[2:23]{.aside}

και οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} ελεγον αυτω ιδε τι ποιουσιν [εν]{.greek-omitted} [οι]{.greek-added} [μαθηται]{.greek-added} [σου]{.greek-added} τοις σαββασιν ο ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added}[2:24]{.aside}

και αυτος ελεγεν αυτοις ουδεποτε ανεγνωτε [τι]{.greek-omitted} [ο]{.greek-added} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε χρειαν [εσχεν]{.greek-omitted} [εσχε]{.greek-added} και επεινασεν αυτος και οι μετ αυτου[2:25]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} επι [αβ]{.unclear}ιαθαρ [του]{.greek-added} αρχιερεως και τους αρτους της προθεσεως [εφαγεν]{.greek-omitted} [εφαγε]{.greek-added} [και]{.greek-added} [εδωκε]{.greek-added} [και]{.greek-added} [τοις]{.greek-added} [μετ]{.greek-added} [αυτου]{.greek-added} ους ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} φαγειν ει μη τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} [και]{.greek-omitted} [εδωκεν]{.greek-omitted} [και]{.greek-omitted} [τοις]{.greek-omitted} [συν]{.greek-omitted} [αυτω]{.greek-omitted} [ουσιν]{.greek-omitted}[2:26]{.aside}

και ελεγεν αυτοις το σαββατον δια τον [ανθρωπον]{.greek-abbr} εγενετο ουχ ο [ανθρωπος]{.greek-abbr} δια το σαββατον[2:27]{.aside}

ωστε [κυριος]{.greek-abbr} εστιν ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} και του σαββατου[2:28]{.aside}

### Chapter 3

και [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} παλιν εις την συναγωγην και ην εκει [ανθρωπος]{.greek-abbr} [εξηραμμενην]{.greek-omitted} [εξηραμενην]{.greek-added} εχων την χειρα[3:1]{.aside}

και [παρετηρουν]{.greek-omitted} [παρετηρουντο]{.greek-added} αυτον ει [εν]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευσει αυτον ινα κατηγορησωσιν αυτου[3:2]{.aside}

και λεγει τω [ανθρωπω]{.greek-abbr} τω [εξηραμμενην]{.greek-omitted} [εχοντι]{.greek-omitted} την χειρα [εχοντι]{.greek-added} [εξηραμμενην]{.greek-added} εγειραι εις [το]{.corr} μεσον[3:3]{.aside}

και λεγει αυτοις [τι]{.greek-added} [εξεστιν]{.greek-omitted} [εστιν]{.greek-added} [εν]{.greek-added} τοις σαββασιν αγαθ[οπ]{.greek-supplied}οιησαι η κακοποιησαι ψυχην σωσαι η [αποκτειναι]{.greek-omitted} [απολεσαι]{.greek-added} οι δε εσιωπων[3:4]{.aside}

και περιβλεψαμενος αυτους μετ οργης συλλυπουμενος επι τη πωρωσει της καρδιας αυτων λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} η χειρ αυτου [υγιης]{.greek-omitted} [ως]{.greek-omitted} [η]{.greek-omitted} [αλλη]{.greek-omitted}[3:5]{.aside}

και εξελθοντες [ευθεως]{.greek-added} οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} [ευθεως]{.greek-omitted} μετα των ηρωδιανων συμβουλιον [εποιουν]{.greek-omitted} [εδιδουν]{.greek-added} κατ αυτου οπως αυτον απολεσωσιν[3:6]{.aside}

[και]{.greek-omitted} ο [δε]{.greek-added} [ιησους]{.greek-abbr} [ανεχωρησεν]{.greek-omitted} μετα των μαθητων αυτου [προς]{.greek-omitted} [ανεχωρησεν]{.greek-added} [εις]{.greek-added} την θαλασσαν και πολυ πληθος απο της γαλιλαιας [ηκολουθησαν]{.greek-omitted} [αυτω]{.greek-omitted} και απο της ιουδαιας[3:7]{.aside}

και απο ιεροσολυμων [και]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [ιδουμαιας]{.greek-omitted} και περαν του ιορδανου και οι περι τυρον και [σιδωνα]{.greek-omitted} [σιδονα]{.greek-added} πληθος πολυ ακουσαντες οσα εποιει ηλθον προς αυτον[3:8]{.aside}

και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τοις μαθηταις αυτου ινα πλοιαριον προσκαρτερη [αυτω]{.greek-omitted} δια τον οχλον ινα μη θλιβωσιν αυτον[3:9]{.aside}

πολλους γαρ [εθεραπευσεν]{.greek-omitted} [εθερα]{.greek-added} [πευσεν]{.greek-added} ωστε επιπιπτειν αυτω ινα αυτου [αψωνται]{.greek-omitted} [απτωνται]{.greek-added} οσοι ειχον μαστιγας[3:10]{.aside}

και τα πνευματα τα ακαθαρτα οταν [εθεωρουν]{.greek-added} αυτον [εθεωρει]{.greek-omitted} [προσεπιπτεν]{.greek-omitted} [προσεπιπτον]{.greek-added} αυτω και [εκραζεν]{.greek-omitted} [εκραζον]{.greek-added} λεγοντα οτι συ ει ο [υιος]{.greek-abbr} του [θεου]{.greek-abbr}[3:11]{.aside}

και πολλα επετιμα αυτοις ινα μη [αυτον]{.greek-added} φανερον [αυτον]{.greek-omitted} [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[3:12]{.aside}

και αναβαινει εις το ορος και προσκαλειται ους ηθελεν αυτος και απηλθον προς αυτον[3:13]{.aside}

και [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} δωδεκα ινα [ωσιν]{.greek-omitted} [ωσι]{.greek-added} μετ αυτου και ινα αποστελλη αυτους κηρυσσειν[3:14]{.aside}

και εχειν εξουσιαν θεραπευειν τας νοσους και εκβαλλειν τα δαιμονια[3:15]{.aside}

και [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τω σιμωνι ονομα πετρον[3:16]{.aside}

και ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον [του]{.greek-omitted} ιακωβου και επεθηκεν αυτοις ονοματα [βοανεργες]{.greek-omitted} [βοανηργες]{.greek-added} ο εστιν υιοι βροντης[3:17]{.aside}

και ανδρεαν και φιλιππον και βαρθολομαιον και ματθαιον [τον]{.greek-added} [τελωνην]{.greek-added} και θωμαν και ιακωβον τον του αλφαιου και θαδδαιον και σιμωνα τον κανανιτην[3:18]{.aside}

και ιουδαν ισκαριωτην ος και παρεδωκεν αυτον [και]{.greek-omitted} [ερχονται]{.greek-omitted} [εις]{.greek-omitted} [οικον]{.greek-omitted}[3:19]{.aside}

[και]{.greek-added} [ερχονται]{.greek-added} [εις]{.greek-added} [οικον]{.greek-added} και συνερχεται παλιν [ο]{.greek-added} οχλος ωστε μη δυνασθαι αυτους μητε αρτον φαγειν[3:20]{.aside}

και ακουσαντες οι παρ αυτου εξηλθον κρατησαι αυτον ελεγον γαρ οτι εξεστη[3:21]{.aside}

και οι γραμματεις [οι]{.greek-omitted} απο ιεροσολυμων καταβαντες ελεγον οτι βεελζεβουλ εχει και οτι εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[3:22]{.aside}

και προσκαλεσαμενος αυτους εν παραβολαις ελεγεν αυτοις πως δυναται σατανας σαταναν εκβαλλειν[3:23]{.aside}

και εαν βασιλεια εφ εαυτην μερισθη ου δυναται σταθηναι η βασιλεια εκεινη[3:24]{.aside}

και εαν οικια εφ εαυτην μερισθη ου δυναται σταθηναι η οικια εκεινη[3:25]{.aside}

και ει ο σατανας ανεστη εφ εαυτον και μεμερισται ου δυναται σταθηναι αλλα τελος εχει[3:26]{.aside}

ουδεις δυναται τα σκευη του ισχυρου εισελθων [εις]{.greek-omitted} [την]{.greek-omitted} [οικιαν]{.greek-omitted} [αυτου]{.greek-omitted} διαρπασαι εαν μη [πρωτον]{.greek-omitted} [προτερον]{.greek-added} τον ισχυρον δηση και τοτε την οικιαν αυτου διαρπαση[3:27]{.aside}

αμην λεγω υμιν οτι παντα αφεθησεται [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted} τοις υιοις των [ανθρωπων]{.greek-abbr} [τα]{.greek-added} [αμαρτηματα]{.greek-added} και [αι]{.greek-added} βλασφημιαι [οσας]{.greek-omitted} [οσα]{.greek-added} [αν]{.greek-omitted} [εαν]{.greek-added} βλασφημησωσιν[3:28]{.aside}

ος δ αν βλασφημηση εις το [πνευμα]{.greek-abbr} το αγιον ουκ εχει αφεσιν [εις]{.greek-omitted} [τον]{.greek-omitted} [αιωνα]{.greek-omitted} αλλ ενοχος εστιν αιωνιου κρισεως[3:29]{.aside}

οτι ελεγον [πνευμα]{.greek-abbr} ακαθαρτον εχει[3:30]{.aside}

[και]{.greek-added} ερχονται [ουν]{.greek-omitted} [οι]{.greek-omitted} [αδελφοι]{.greek-omitted} [και]{.greek-omitted} η [μητηρ]{.greek-abbr} αυτου και [οι]{.greek-added} [αδελφοι]{.greek-added} [αυτου]{.greek-added} [και]{.greek-added} εξω [εστωτες]{.greek-omitted} [εστηκοτες]{.greek-added} απεστειλαν προς αυτον [φωνουντες]{.greek-omitted} [αυτον]{.greek-omitted}[3:31]{.aside}

και εκαθητο [οχλος]{.greek-omitted} περι αυτον [οχλος]{.greek-added} [ειπον]{.greek-omitted} [ειποντων]{.greek-added} δε [αυτω]{.greek-omitted} [αυτων]{.greek-added} ιδου η [μητηρ]{.greek-abbr} σου και οι αδελφοι σου [και]{.greek-omitted} [αι]{.greek-omitted} [αδελφαι]{.greek-omitted} [σου]{.greek-omitted} εξω [ζητουσιν]{.greek-omitted} [ζητουσι]{.greek-added} σε[3:32]{.aside}

[και]{.greek-omitted} απεκριθη αυτοις [λεγων]{.greek-omitted} [και]{.greek-added} [λεγει]{.greek-added} τις εστιν η [μητηρ]{.greek-abbr} μου [η]{.greek-omitted} [και]{.greek-added} οι αδελφοι μου[3:33]{.aside}

και περιβλεψαμενος [τους]{.greek-added} κυκλω [τους]{.greek-omitted} περι αυτον [μαθητας]{.greek-added} καθημενους [λεγει]{.greek-omitted} [ιδε]{.greek-omitted} [ειπεν]{.greek-added} [ιδου]{.greek-added} η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[3:34]{.aside}

ος γαρ αν ποιηση το θελημα του [θεου]{.greek-abbr} ουτος αδελφος μου και αδελφη [μου]{.greek-omitted} και [μητηρ]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added}[3:35]{.aside}

### Chapter 4

[και]{.greek-omitted} παλιν [δε]{.greek-added} ηρξατο διδασκειν παρα την θαλασσαν και [συνηχθη]{.greek-omitted} [συναγεται]{.greek-added} προς αυτον οχλος πολυς ωστε αυτον εμβαντα εις [το]{.greek-omitted} πλοιον καθησθαι εν τη θαλασση και πας ο οχλος προς την θαλασσαν επι της γης ην[4:1]{.aside}

και εδιδασκεν αυτους εν παραβολαις πολλα και ελεγεν αυτοις εν τη διδαχη αυτου[4:2]{.aside}

ακουετε ιδου εξηλθεν ο σπειρων του σπειραι[4:3]{.aside}

και εγενετο εν τω σπειρειν ο μεν [επεσεν]{.greek-omitted} [επεσε]{.greek-added} παρα την οδον και [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} τα πετεινα και κατεφαγεν αυτο[4:4]{.aside}

αλλο δε επεσεν επι το πετρωδες οπου ουκ [ειχεν]{.greek-omitted} [ειχε]{.greek-added} γην [πολλην]{.greek-omitted} [καλην]{.greek-added} και ευθεως [εξανετειλεν]{.greek-omitted} [εξεβλαστησε]{.greek-added} δια το μη εχειν βαθος γης[4:5]{.aside}

ηλιου δε ανατειλαντος εκαυματισθη και δια το μη εχειν ριζαν [εξη]{.greek-added} [εξηρανθη]{.greek-omitted} [ρανθη]{.greek-added}[4:6]{.aside}

[και]{.greek-omitted} αλλο [δε]{.greek-added} επεσεν εις τας ακανθας και ανεβησαν αι ακανθαι και συνεπνιξαν αυτο και καρπον ουκ εδωκεν[4:7]{.aside}

[και]{.greek-omitted} αλλο [δε]{.greek-added} επεσεν [εις]{.greek-omitted} [επι]{.greek-added} την γην την καλην και εδιδου καρπον αναβαινοντα και αυξανοντα και [εφερεν]{.greek-omitted} [εν]{.greek-omitted} [φερει]{.greek-added} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:8]{.aside}

και ελεγεν ο εχων ωτα ακουειν ακουετω[4:9]{.aside}

οτε δε εγενετο [καταμονας]{.greek-omitted} [κατα]{.greek-added} [μονας]{.greek-added} [ηρωτησαν]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον οι [περι]{.greek-omitted} [μαθηται]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added} [συν]{.greek-omitted} [τοις]{.greek-omitted} [τις]{.greek-added} [η]{.greek-added} [δωδεκα]{.greek-omitted} [την]{.greek-omitted} [παραβολην]{.greek-omitted} [παραβολη]{.greek-added} [αυτη]{.greek-added}[4:10]{.aside}

και ελεγεν αυτοις υμιν δεδοται γνωναι το μυστηριον της βασιλειας του [θεου]{.greek-abbr} εκεινοις δε τοις εξω εν παραβολαις [τα]{.greek-omitted} παντα [γινεται]{.greek-omitted} [λεγεται]{.greek-added}[4:11]{.aside}

ινα βλεποντες [βλεπωσιν]{.greek-omitted} [βλεπωσι]{.greek-added} και μη [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} και ακουοντες [ακουωσιν]{.greek-omitted} [ακουωσι]{.greek-added} και μη [συνιωσιν]{.greek-omitted} [συνιωσι]{.greek-added} μηποτε [επιστρεψωσιν]{.greek-omitted} [επιστραψωσι]{.greek-added} και αφεθη αυτοις [τα]{.greek-omitted} [αμαρτηματα]{.greek-omitted}[4:12]{.aside}

και λεγει αυτοις ουκ οιδατε την παραβολην ταυτην και πως πασας τας παραβολας γνωσεσθε[4:13]{.aside}

ο σπειρων τον λογον σπειρει[4:14]{.aside}

ουτοι δε εισιν οι παρα την οδον οπου σπειρεται ο λογος και οταν ακουσωσιν [ευθεως]{.greek-omitted} [αυτου]{.greek-added} ερχεται ο σατανας και αιρει τον λογον τον εσπαρμενον [εις]{.greek-added} [αυτους]{.greek-added} [εν]{.greek-omitted} [ταις]{.greek-omitted} [καρδιαις]{.greek-omitted} [αυτων]{.greek-omitted}[4:15]{.aside}

και ουτοι εισιν [ομοιως]{.greek-omitted} οι επι τα πετρωδη σπειρομενοι οι οταν [ακουσωσιν]{.greek-omitted} [ακουσωσι]{.greek-added} τον λογον ευθεως μετα χαρας λαμβανουσιν αυτον[4:16]{.aside}

και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} ριζαν εν εαυτοις αλλα προσκαιροι εισιν ειτα γενομενης θλιψεως η διωγμου δια τον λογον ευθεως σκανδαλιζονται[4:17]{.aside}

και [ουτοι]{.greek-omitted} [εισιν]{.greek-omitted} οι εις τας ακανθας σπειρομενοι [ουτοι]{.greek-added} [εισιν]{.greek-added} οι τον λογον [ακουοντες]{.greek-omitted} [ακουσαντες]{.greek-added}[4:18]{.aside}

και αι μεριμναι του αιωνος [τουτου]{.greek-omitted} και η απατη του πλουτου [και]{.greek-omitted} [αι]{.greek-omitted} [περι]{.greek-omitted} [τα]{.greek-omitted} [λοιπα]{.greek-omitted} [επιθυμιαι]{.greek-omitted} εισπορευομεναι συμπνιγουσιν τον λογον και ακαρπος γινεται[4:19]{.aside}

και ουτοι εισιν οι επι την γην την καλην σπαρεντες οιτινες [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} τον λογον και παραδεχονται και καρποφορουσιν [εν]{.greek-omitted} [ἐν]{.greek-added} τριακοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εξηκοντα και [εν]{.greek-omitted} [ἐν]{.greek-added} εκατον[4:20]{.aside}

και ελεγεν αυτοις μητι [ο]{.greek-omitted} [ερχεται]{.greek-added} λυχνος [ερχεται]{.greek-omitted} ινα υπο τον μοδιον τεθη η [ινα]{.greek-added} υπο την κλινην [τεθη]{.greek-added} ουχ ινα επι την λυχνιαν [επιτεθη]{.greek-omitted} [τεθη]{.greek-added}[4:21]{.aside}

ου γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [τι]{.greek-omitted} κρυπτον [ο]{.greek-omitted} εαν μη φανερωθη ουδε εγενετο αποκρυφον αλλ ινα εις φανερον ελθη[4:22]{.aside}

[ο]{.greek-added} [εχων]{.greek-added} [ει]{.greek-omitted} [τις]{.greek-omitted} [εχει]{.greek-omitted} ωτα ακουειν ακουετω[4:23]{.aside}

και ελεγεν αυτοις βλεπετε τι ακουετε εν ω μετρω μετρειτε μετρηθησεται υμιν και προστεθησεται υμιν τοις ακουουσιν[4:24]{.aside}

ος γαρ αν εχη δοθησεται αυτω και ος ουκ εχει και ο εχει αρθησεται απ αυτου[4:25]{.aside}

και ελεγεν ουτως εστιν η βασιλεια του [θεου]{.greek-abbr} [ωσπερ]{.greek-added} [ως]{.greek-omitted} [εαν]{.greek-omitted} [ανθρωπος]{.greek-abbr} [βαλη]{.greek-omitted} [βαλλει]{.greek-added} τον σπορον επι της γης[4:26]{.aside}

και [ου]{.greek-added} [καθευδη]{.greek-omitted} [καθευδει]{.greek-added} και [εγειρηται]{.greek-omitted} [εγειρεται]{.greek-added} νυκτα και ημεραν και ο σπορος [βλαστανη]{.greek-omitted} [βλασταν[ει]{.unclear}]{.greek-added} και [μηκυνηται]{.greek-omitted} [μηκυνεται]{.greek-added} ως ουκ οιδεν [αυτος]{.greek-omitted}[4:27]{.aside}

[αυτοματη]{.greek-omitted} [αυτοματως]{.greek-added} γαρ η γη καρποφορει πρωτον χορτον ειτα σταχυν ειτα πληρη [[πληρης]{.corr}]{.greek-added} [σιτον]{.greek-omitted} [σιτων]{.greek-added} εν τω σταχυι[4:28]{.aside}

οταν δε παραδω ο καρπος ευθεως αποστελλει το δρεπανον οτι παρεστηκεν ο θερισμος[4:29]{.aside}

και [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} [τινι]{.greek-omitted} [πως]{.greek-added} ομοιωσωμεν την βασιλειαν του [θεου]{.greek-abbr} η εν ποια παραβολη [παραβαλωμεν]{.greek-omitted} αυτην [παραβαλλομεν]{.greek-added}[4:30]{.aside}

ως [κοκκον]{.greek-omitted} [κοκκω]{.greek-added} σιναπεως ος οταν σπαρη επι της γης μικροτερος παντων των σπερματων [εστιν]{.greek-omitted} [εστι]{.greek-added} των επι της γης[4:31]{.aside}

και οταν σπαρη αναβαινει και γινεται [μειζων]{.greek-added} παντων των λαχανων [μειζων]{.greek-omitted} και ποιει κλαδους μεγαλους ωστε δυνασθαι υπο την σκιαν αυτου τα πετεινα του ουρανου κατασκηνουν[4:32]{.aside}

και τοιαυταις παραβολαις [πολλαις]{.greek-omitted} ελαλει αυτοις τον λογον καθως [εδυναντο]{.greek-omitted} [ηδυναντο]{.greek-added} ακουειν[4:33]{.aside}

χωρις δε παραβολης ουκ ελαλει αυτοις κατ ιδιαν δε τοις μαθηταις αυτου [επελυεν]{.greek-omitted} [επελυε]{.greek-added} παντα[4:34]{.aside}

και λεγει αυτοις εν εκεινη τη ημερα οψιας γενομενης διελθωμεν εις το περαν[4:35]{.aside}

και [αφεντες]{.greek-omitted} [αφιουσι]{.greek-added} τον οχλον [και]{.greek-added} παραλαμβανουσιν αυτον ως ην εν τω πλοιω και αλλα δε [πλοιαρια]{.greek-omitted} [πλοια]{.greek-added} ην μετ αυτου[4:36]{.aside}

και γινεται [λαιλαψ]{.greek-omitted} [λαι]{.greek-added} [λαψ]{.greek-added} [μεγαλη]{.greek-added} ανεμου [μεγαλη]{.greek-omitted} [και]{.greek-added} τα [δε]{.greek-omitted} κυματα [επεβαλλεν]{.greek-omitted} [επεβαλον]{.greek-added} εις το πλοιον ωστε αυτο ηδη γεμιζεσθαι[4:37]{.aside}

και ην αυτος [επι]{.greek-omitted} [εν]{.greek-added} τη πρυμνη επι [το]{.greek-omitted} προσκεφαλαιον καθευδων και διεγειρουσιν αυτον και λεγουσιν αυτω διδασκαλε ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι οτι απολλυμεθα[4:38]{.aside}

και διεγερθεις [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω ανεμω και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη θαλασση σιωπα πεφιμωσο και εκοπασεν ο ανεμος και εγενετο γαληνη μεγαλη[4:39]{.aside}

και ειπεν αυτοις τι [ουτως]{.greek-added} δειλοι εστε [ουπω]{.greek-added} [ουτως]{.greek-omitted} [πως]{.greek-omitted} [ουκ]{.greek-omitted} εχετε πιστιν[4:40]{.aside}

και εφοβηθησαν φοβον μεγαν και ελεγον προς αλληλους τις αρα [εστιν]{.greek-added} ουτος [εστιν]{.greek-omitted} οτι και [ο]{.greek-omitted} [οι]{.greek-added} [ανεμος]{.greek-omitted} [ανεμοι]{.greek-added} και η θαλασσα [υπακουουσιν]{.greek-omitted} αυτω [υπακουει]{.greek-added}[4:41]{.aside}

### Chapter 5

και [ηλθον]{.greek-omitted} [ηλθεν]{.greek-added} εις το περαν της θαλασσης εις την χωραν των [γαδαρηνων]{.greek-omitted} [γεργεσηνων]{.greek-added}[5:1]{.aside}

και εξελθοντι αυτω εκ του πλοιου ευθεως [απηντησεν]{.greek-omitted} [υπηντησεν]{.greek-added} αυτω εκ των μνημειων [ανθρωπος]{.greek-abbr} εν [πνευματι]{.greek-abbr} [ακα]{.greek-added} [ακαθαρτω]{.greek-omitted} [θαρτω]{.greek-added}[5:2]{.aside}

ος την [κατοικησιν]{.greek-omitted} [κατοικιαν]{.greek-added} ειχεν εν τοις μνημασιν και ουτε αλυσεσιν ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} αυτον [οτι]{.greek-added} δησαι[5:3]{.aside}

δια το αυτον [πολλακις]{.greek-omitted} [πολλας]{.greek-added} [πεδαις]{.greek-omitted} [πεδας]{.greek-added} και [αλυσεσιν]{.greek-omitted} [αλυσεις]{.greek-added} [δεδεσθαι]{.greek-omitted} [αις]{.greek-added} [εδησαν]{.greek-added} [διεσπακεναι]{.greek-added} και [διεσπασθαι]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} [τας]{.greek-omitted} [αλυσεις]{.greek-omitted} [και]{.greek-omitted} [τας]{.greek-omitted} [πεδας]{.greek-omitted} [συντετριφθαι]{.greek-omitted} [συντετριφεναι]{.greek-added} και ουδεις [ισχυεν]{.greek-added} αυτον [ισχυεν]{.greek-omitted} δαμασαι[5:4]{.aside}

και δια παντος νυκτος και ημερας εν τοις [ορεσιν]{.greek-omitted} [μνημειοις]{.greek-added} και εν τοις [μνημασιν]{.greek-omitted} [ορεσιν]{.greek-added} ην κραζων και κατακοπτων εαυτον λιθοις[5:5]{.aside}

ιδων δε τον [ιησουν]{.greek-abbr} απο μακροθεν [εδραμεν]{.greek-omitted} [εδραμε]{.greek-added} και προσεκυνησεν αυτω[5:6]{.aside}

και κραξας φωνη μεγαλη [ειπεν]{.greek-omitted} [λεγει]{.greek-added} τι εμοι και σοι [ιησου]{.greek-abbr} υιε του [θεου]{.greek-abbr} του υψιστου ορκιζω σε τον [θεον]{.greek-abbr} μη με βασανισης[5:7]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ αυτω εξελθε το [πνευμα]{.greek-abbr} το ακαθαρτον εκ του [ανθρωπου]{.greek-abbr}[5:8]{.aside}

και επηρωτα [αυτον]{.greek-omitted} [αυτω]{.greek-added} τι [ονομα]{.greek-added} σοι [ονομα]{.greek-omitted} και [απεκριθη]{.greek-omitted} [λεγων]{.greek-omitted} [λεγει]{.greek-added} [αυτω]{.greek-added} λεγεων ονομα μοι οτι πολλοι εσμεν[5:9]{.aside}

και [παρεκαλει]{.greek-omitted} [παρεκαλουν]{.greek-added} αυτον πολλα ινα μη [αυτους]{.greek-omitted} [αποστειλη]{.greek-omitted} εξω της χωρας [αυτους]{.greek-added} [αποστειλη]{.greek-added}[5:10]{.aside}

ην δε εκει [αγελη]{.greek-added} [χοιρων]{.greek-added} [μεγαλη]{.greek-added} προς τω ορει [αγελη]{.greek-omitted} [χοιρων]{.greek-omitted} [μεγαλη]{.greek-omitted} βοσκομενη[5:11]{.aside}

και [παρεκαλεσαν]{.greek-omitted} [παρεκαλεσαντες]{.greek-added} αυτον [ειπον]{.greek-added} [παντες]{.greek-omitted} [οι]{.greek-omitted} [δαιμονες]{.greek-omitted} [λεγοντες]{.greek-omitted} πεμψον ημας εις τους χοιρους ινα εις αυτους εισελθωμεν[5:12]{.aside}

και επετρεψεν αυτοις [ευθεως]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} και εξελθοντα τα [πνευματα]{.greek-abbr} τα ακαθαρτα εισηλθον εις τους χοιρους και ωρμησεν η αγελη κατα του κρημνου εις την θαλασσαν ησαν δε ως δισχιλιοι και επνιγοντο εν τη θαλασση[5:13]{.aside}

[και]{.greek-added} οι [δε]{.greek-omitted} βοσκοντες [τους]{.greek-omitted} [αυτους]{.greek-added} [χοιρους]{.greek-omitted} εφυγον και ανηγγειλαν εις την πολιν και εις τους αγρους και εξηλθον ιδειν τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το γεγονος[5:14]{.aside}

και ερχονται προς τον [ιησουν]{.greek-abbr} και [θεωρουσιν]{.greek-omitted} [θεωρουσι]{.greek-added} τον δαιμονιζομενον καθημενον και ιματισμενον και σωφρονουντα τον εσχηκοτα τον λεγεωνα και εφοβηθησαν[5:15]{.aside}

[και]{.greek-added} διηγησαντο [δε]{.greek-omitted} αυτοις οι ιδοντες πως εγενετο τω δαιμονιζομενω και περι των χοιρων[5:16]{.aside}

και ηρξαντο παρακαλειν αυτον απελθειν απο των οριων αυτων[5:17]{.aside}

και εμβαντος αυτου εις το πλοιον παρεκαλει αυτον ο δαιμονισθεις ινα η μετ αυτου[5:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} [ιησους]{.greek-omitted} ουκ αφηκεν αυτον αλλα λεγει αυτω υπαγε εις τον οικον σου προς τους σους και [αναγγειλον]{.greek-omitted} [διαγγειλον]{.greek-added} αυτοις οσα σοι ο [κυριος]{.greek-abbr} [πεποιηκεν]{.greek-omitted} [πεποι]{.greek-added} [ηκε]{.greek-added} και [ηλεησεν]{.greek-omitted} [ηλεησε]{.greek-added} σε[5:19]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} και ηρξατο κηρυσσειν εν τη δεκαπολει οσα εποιησεν αυτω ο [ιησους]{.greek-abbr} και παντες εθαυμαζον[5:20]{.aside}

και διαπερασαντος του [ιησου]{.greek-abbr} [εν]{.greek-omitted} [τω]{.greek-omitted} [πλοιω]{.greek-omitted} παλιν εις το περαν συνηχθη οχλος πολυς [επ]{.greek-omitted} [προς]{.greek-added} αυτον και ην παρα την θαλασσαν[5:21]{.aside}

και [ιδου]{.greek-omitted} [ιδον]{.greek-added} ερχεται εις των αρχισυναγωγων ονοματι ιαειρος και ιδων αυτον [πιπτει]{.greek-omitted} [προσπιπτει]{.greek-added} προς τους ποδας αυτου[5:22]{.aside}

και παρεκαλει αυτον πολλα λεγων οτι το θυγατριον μου εσχατως εχει ινα ελθων επιθης [αυτη]{.greek-omitted} τας χειρας [οπως]{.greek-omitted} [αυτη]{.greek-added} [ινα]{.greek-added} σωθη και [ζησεται]{.greek-omitted} [ζησηται]{.greek-added}[5:23]{.aside}

και [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} μετ αυτου και ηκολουθει αυτω οχλος πολυς και συνεθλιβον αυτον[5:24]{.aside}

και γυνη [τις]{.greek-omitted} ουσα εν ρυσει αιματος [δωδεκα]{.greek-added} ετη [δωδεκα]{.greek-omitted}[5:25]{.aside}

και πολλα παθουσα υπο πολλων ιατρων και δαπανησασα τα [παρ]{.greek-omitted} [αυτης]{.greek-omitted} [εαυτης]{.greek-added} παντα και μηδεν ωφεληθεισα αλλα μαλλον εις το χειρον ελθουσα[5:26]{.aside}

ακουσασα περι του [ιησου]{.greek-abbr} ελθουσα [εν]{.greek-omitted} [τω]{.greek-omitted} [οχλω]{.greek-omitted} [εις]{.greek-added} [τον]{.greek-added} [οχλον]{.greek-added} [οπισθεν]{.greek-omitted} [οπιθεν]{.greek-added} ηψατο του ιματιου αυτου[5:27]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ οτι καν των ιματιων αυτου αψωμαι σωθησομαι[5:28]{.aside}

και ευθεως εξηρανθη η πηγη του αιματος αυτης και εγνω τω σωματι οτι ιαται απο της μαστιγος[5:29]{.aside}

και ευθεως ο [ιησους]{.greek-abbr} επιγνους [εν]{.greek-omitted} [εαυτω]{.greek-omitted} την εξ αυτου δυναμιν εξελθουσαν επιστραφεις εν τω οχλω [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} τις μου ηψατο των ιματιων[5:30]{.aside}

και ελεγον αυτω οι μαθηται αυτου βλεπεις τον οχλον συνθλιβοντα σε και λεγεις τις μου ηψατο[5:31]{.aside}

και περιεβλεπετο ιδειν την τουτο ποιησασαν[5:32]{.aside}

η δε γυνη φοβηθεισα και τρεμουσα ειδυια ο γεγονεν επ αυτη [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} και προσεπεσεν αυτω και ειπεν αυτω πασαν την [αληθειαν]{.greek-omitted} [αιτιαν]{.greek-added} [αυ[―]{.gap}]{.greek-added} [[αυτης]{.corr}]{.greek-added}[5:33]{.aside}

ο δε [[ιησους]{.greek-abbr}]{.greek-added} ειπεν αυτη θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε υπαγε εις ειρηνην και ισθι υγιης απο της μαστιγος σου[5:34]{.aside}

ετι αυτου λαλουντος ερχονται απο του αρχισυναγωγου λεγοντες οτι η θυγατηρ σου [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} τι ετι σκυλλεις τον διδασκαλον[5:35]{.aside}

ο δε [ιησους]{.greek-abbr} [ευθεως]{.greek-omitted} ακουσας τον λογον λαλουμενον λεγει τω αρχισυναγωγω μη φοβου μονον πιστευε[5:36]{.aside}

και ουκ αφηκεν ουδενα αυτω [παρακολουθησαι]{.greek-added} [συνακολουθησαι]{.corr} ει μη [τον]{.greek-added} πετρον και [τον]{.greek-added} ιακωβον και [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον αδελφον ιακωβου[5:37]{.aside}

και ερχεται εις τον οικον του αρχισυναγωγου και θεωρει θορυβον [και]{.greek-added} κλαιοντας και αλαλαζοντας πολλα[5:38]{.aside}

και εισελθων λεγει αυτοις τι θορυβεισθε και κλαιετε το παιδιον ουκ απεθανεν αλλα καθευδει[5:39]{.aside}

και κατεγελων αυτου ο δε εκβαλων παντας παραλαμβανει τον [πατερα]{.greek-abbr} του παιδιου και την [μητερα]{.greek-abbr} και τους [μετ]{.greek-omitted} [μεθ]{.greek-added} [αυτου]{.greek-omitted} [εαυτου]{.greek-added} και εισπορευεται οπου ην το παιδιον [ανακειμενον]{.greek-omitted} [κατακειμενον]{.greek-added}[5:40]{.aside}

και κρατησας της χειρος του παιδιου λεγει αυτη ταλιθα κουμι ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον το κορασιον σοι λεγω εγειραι[5:41]{.aside}

και ευθεως ανεστη το κορασιον και περιεπατει ην γαρ ετων δωδεκα και εξεστησαν εκστασει [με]{.greek-added} [μεγαλη]{.greek-omitted} [γαλη]{.greek-added}[5:42]{.aside}

και διεστειλατο αυτοις πολλα ινα μηδεις γνω τουτο και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} δοθηναι αυτη φαγειν[5:43]{.aside}

### Chapter 6

και εξηλθεν εκειθεν και ηλθεν εις την [πατριδα]{.greek-abbr} αυτου και ακολουθουσιν αυτω οι μαθηται αυτου[6:1]{.aside}

και γενομενου σαββατου ηρξατο εν τη συναγωγη διδασκειν και πολλοι ακουοντες εξεπλησσοντο λεγοντες ποθεν τουτω ταυτα και τις η σοφια η δοθεισα αυτω και δυναμεις τοιαυται δια των χειρων αυτου γινονται[6:2]{.aside}

ουχ ουτος εστιν ο [τεκτων]{.greek-omitted} [του]{.greek-added} [τεκτονος]{.greek-added} ο [υιος]{.greek-abbr} [της]{.greek-added} μαριας αδελφος [δε]{.greek-omitted} ιακωβου και [ιωση]{.greek-omitted} [ιωσητος]{.greek-added} και ιουδα και σιμωνος και ουκ εισιν αι αδελφαι αυτου ωδε προς ημας και εσκανδαλιζοντο εν αυτω[6:3]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} οτι ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} προφητης ατιμος ει μη εν τη [πατριδι]{.greek-abbr} αυτου και εν τοις [συγγενεσιν]{.greek-omitted} [συγγενευσιν]{.greek-added} και εν τη οικια αυτου[6:4]{.aside}

και ουκ [ηδυνατο]{.greek-omitted} [εδυνατο]{.greek-added} εκει [ποιησαι]{.greek-added} ουδεμιαν δυναμιν [ποιησαι]{.greek-omitted} ει μη ολιγοις αρρωστοις επιθεις τας χειρας εθεραπευσεν [αυτους]{.greek-added}[6:5]{.aside}

και [εθαυμαζεν]{.greek-omitted} [εθαυμαζε]{.greek-added} δια την απιστιαν αυτων και [περιηγεν]{.greek-omitted} [περιηγε]{.greek-added} τας [κυκλω]{.greek-added} κωμας [κυκλω]{.greek-omitted} διδασκων[6:6]{.aside}

και προσκαλειται τους δωδεκα [μαθητας]{.greek-added} [αυτου]{.greek-added} και ηρξατο [αποστελλειν]{.greek-added} αυτους [αποστελλειν]{.greek-omitted} δυο δυο και εδιδου αυτοις εξουσιαν των [πνευματων]{.greek-abbr} των ακαθαρτων[6:7]{.aside}

και παρηγγειλεν [αυτοις]{.greek-omitted} [αυτους]{.greek-added} ινα μηδεν αιρωσιν εις οδον ει μη ραβδον μονον μη πηραν μη αρτον μη εις την ζωνην χαλκον[6:8]{.aside}

[αλλ]{.greek-omitted} [μηδε]{.greek-added} υποδεδεμενους σανδαλια και μη ενδυσησθε δυο χιτωνας[6:9]{.aside}

και ελεγεν αυτοις οπου [δ]{.greek-added} [εαν]{.greek-omitted} [αν]{.greek-added} εισελθητε εις οικιαν εκει μενετε εως αν εξελθητε εκειθεν[6:10]{.aside}

και οσοι αν μη [δεξωνται]{.greek-omitted} [δεχωνται]{.greek-added} υμας μηδε ακουσωσιν υμων εκπορευομενοι εκειθεν εκτιναξατε τον χουν τον υποκατω των ποδων υμων εις μαρτυριον αυτοις [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [ανεκτοτερον]{.greek-omitted} [εσται]{.greek-omitted} [σοδομοις]{.greek-omitted} [η]{.greek-omitted} [γομορροις]{.greek-omitted} [εν]{.greek-omitted} [ημερα]{.greek-omitted} [κρισεως]{.greek-omitted} [η]{.greek-omitted} [τη]{.greek-omitted} [πολει]{.greek-omitted} [εκεινη]{.greek-omitted}[6:11]{.aside}

και εξελθοντες εκηρυσσον ινα [μετανοησωσιν]{.greek-omitted} [μετανοησωσι]{.greek-added}[6:12]{.aside}

και δαιμονια πολλα εξεβαλλον και ηλειφον ελαιω πολλους αρρωστους και εθεραπευον[6:13]{.aside}

και ηκουσεν ο βασιλευς ηρωδης φανερον γαρ εγενετο το ονομα αυτου και ελεγεν οτι [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ο [βαπτιζων]{.greek-omitted} [βαπτιστης]{.greek-added} εκ νεκρων ηγερθη και δια τουτο ενεργουσιν αι δυναμεις εν αυτω[6:14]{.aside}

αλλοι [δε]{.greek-added} ελεγον οτι ηλιας εστιν αλλοι δε ελεγον οτι προφητης εστιν ως εις των προφητων[6:15]{.aside}

ακουσας δε [ο]{.greek-added} ηρωδης ειπεν οτι ον εγω απεκεφαλισα [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ουτος εστιν αυτος ηγερθη εκ νεκρων[6:16]{.aside}

αυτος γαρ ο ηρωδης αποστειλας [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και εδησεν αυτον εν [τη]{.greek-added} φυλακη δια ηρωδιαδα την γυναικα φιλιππου του αδελφου αυτου οτι αυτην εγαμησεν[6:17]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ ο [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τω ηρωδη οτι ουκ [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} σοι εχειν την γυναικα του αδελφου σου[6:18]{.aside}

η δε ηρωδιας ενειχεν αυτω και ηθελεν αυτον αποκτειναι και ουκ ηδυνατο[6:19]{.aside}

ο γαρ ηρωδης εφοβειτο τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} ειδως αυτον ανδρα δικαιον και αγιον και συνετηρει αυτον και ακουσας αυτου πολλα εποιει και ηδεως αυτου [ηκουεν]{.greek-omitted} [ηκουε]{.greek-added}[6:20]{.aside}

και γενομενης ημερας ευκαιρου οτε ηρωδης τοις γενεσιοις αυτου δειπνον [εποιει]{.greek-omitted} [εποιησε]{.greek-added} τοις μεγιστασιν αυτου και τοις χιλιαρχοις και τοις πρωτοις της γαλιλαιας[6:21]{.aside}

και εισελθουσης της θυγατρος αυτης της ηρωδιαδος και [ορχησαμενης]{.greek-omitted} [ωρχησαμενης]{.greek-added} και αρεσασης τω ηρωδη και τοις συνανακειμενοις [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [τω]{.greek-added} [κορασιω]{.greek-added} ο βασιλευς [τω]{.greek-omitted} [κορασιω]{.greek-omitted} αιτησον με ο εαν θελης και δωσω σοι[6:22]{.aside}

και ωμοσεν αυτη οτι ο εαν με αιτησης δωσω σοι εως ημισους της βασιλειας μου[6:23]{.aside}

η δε εξελθουσα [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τη [μητρι]{.greek-abbr} αυτης τι αιτησομαι η δε [ειπεν]{.greek-omitted} [ειπε]{.greek-added} την κεφαλην [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} του βαπτιστου[6:24]{.aside}

και εισελθουσα [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} μετα σπουδης προς τον βασιλεα [ειπε]{.greek-added} [ητησατο]{.greek-omitted} [λεγουσα]{.greek-omitted} θελω ινα [δως]{.greek-added} μοι [δως]{.greek-omitted} εξαυτης [την]{.greek-added} [κεφαλην]{.greek-added} επι πινακι [[ιω]{.greek-abbr}]{.greek-added} [την]{.greek-omitted} [κεφαλην]{.greek-omitted} [ιωαννου]{.greek-omitted} του [βαπτιστου]{.greek-omitted} [βαπτιζοντος]{.greek-added}[6:25]{.aside}

και περιλυπος γενομενος ο βασιλευς δια τους ορκους και τους συνανακειμενους ουκ ηθελησεν αυτην αθετησαι[6:26]{.aside}

και ευθεως αποστειλας [ο]{.greek-omitted} [βασιλευς]{.greek-omitted} [σπεκουλατορα]{.greek-omitted} [σπεκουλατωρα]{.greek-added} επεταξεν ενεχθηναι την κεφαλην αυτου [ο]{.greek-added} [δε]{.greek-added} [απελθων]{.greek-added} [απεκεφαλισεν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [κεφαλη]{.greek-added}[6:27]{.aside}

[ο]{.greek-omitted} [δε]{.greek-omitted} [απελθων]{.greek-omitted} [απεκεφαλισεν]{.greek-omitted} [αυτον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [φυλακη]{.greek-omitted} και [ηνεγκεν]{.greek-omitted} [ηνεγκε]{.greek-added} την κεφαλην αυτου επι πινακι και [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} [αυτην]{.greek-omitted} τω κορασιω και το κορασιον εδωκεν αυτην τη [μητρι]{.greek-abbr} αυτης[6:28]{.aside}

και ακουσαντες οι μαθηται αυτου ηλθον και ηραν το πτωμα αυτου και εθηκαν αυτο εν μνημειω[6:29]{.aside}

και συναγονται οι αποστολοι προς τον [ιησουν]{.greek-abbr} και απηγγειλαν αυτω [παντα]{.greek-omitted} [και]{.greek-omitted} οσα εποιησαν και οσα εδιδαξαν[6:30]{.aside}

και ειπεν αυτοις [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} δευτε υμεις [αυτοι]{.greek-omitted} κατ ιδιαν εις ερημον τοπον και αναπαυεσθε ολιγον ησαν γαρ οι ερχομενοι και οι υπαγοντες πολλοι και ουδε φαγειν ευκαιρουν[6:31]{.aside}

και [απηλθον]{.greek-omitted} [απηλθεν]{.greek-added} εις ερημον τοπον [τω]{.greek-omitted} [πλοιω]{.greek-omitted} [το]{.greek-added} [πλοιον]{.greek-added} κατ ιδιαν[6:32]{.aside}

και ειδον αυτους υπαγοντας και επεγνωσαν [αυτον]{.greek-omitted} πολλοι και πεζη απο πασων των πολεων συνεδραμον εκει και προηλθον αυτους και [συνηλθον]{.greek-omitted} [[η]{.unclear}λθον]{.greek-added} προς αυτον[6:33]{.aside}

και εξελθων ειδεν ο [ιησους]{.greek-abbr} [οχλον]{.greek-added} πολυν [οχλον]{.greek-omitted} και εσπλαγχνισθη επ αυτοις οτι ησαν ως προβατα μη εχοντα ποιμενα και ηρξατο διδασκειν αυτους πολλα[6:34]{.aside}

και ηδη ωρας πολλης γενομενης προσελθοντες αυτω οι μαθηται [αυτου]{.greek-omitted} λεγουσιν οτι ερημος εστιν ο τοπος και ηδη ωρα πολλη[6:35]{.aside}

απολυσον αυτους ινα απελθοντες εις τους κυκλω αγρους και κωμας αγορασωσιν εαυτοις [αρτους]{.greek-omitted} τι [γαρ]{.greek-omitted} φαγωσιν [ουκ]{.greek-omitted} [εχουσιν]{.greek-omitted}[6:36]{.aside}

ο δε αποκριθεις ειπεν αυτοις δοτε αυτοις υμεις φαγειν και λεγουσιν αυτω απελθοντες [αγορασωμεν]{.greek-omitted} [αγορασομεν]{.greek-added} [διακοσιων]{.greek-added} δηναριων [διακοσιων]{.greek-omitted} αρτους και [δωμεν]{.greek-omitted} [δωσομεν]{.greek-added} αυτοις φαγειν[6:37]{.aside}

ο δε λεγει αυτοις ποσους [εχετε]{.greek-added} αρτους [εχετε]{.greek-omitted} υπαγετε [και]{.greek-omitted} ιδετε και γνοντες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} πεντε και δυο ιχθυας[6:38]{.aside}

και επεταξεν αυτοις ανακλιναι παντας συμποσια συμποσια [επι]{.greek-omitted} [εν]{.greek-added} τω χλωρω χορτω[6:39]{.aside}

και [ανεπεσον]{.greek-omitted} [ανεβησαν]{.greek-added} πρασιαι πρασιαι ανα εκατον και ανα πεντηκοντα[6:40]{.aside}

και λαβων τους πεντε αρτους και τους δυο ιχθυας αναβλεψας εις τον [ουρανον]{.greek-abbr} [ευλογησεν]{.greek-omitted} [ηυλογησε]{.greek-added} και [κατεκλασεν]{.greek-omitted} [κατεκλασε]{.greek-added} τους αρτους και εδιδου τοις μαθηταις αυτου ινα παραθωσιν αυτοις και τους δυο ιχθυας [εμερισεν]{.greek-omitted} [εμερισε]{.greek-added} [πασιν]{.greek-omitted} [πασι]{.greek-added}[6:41]{.aside}

και εφαγον παντες και εχορτασθησαν[6:42]{.aside}

και ηραν [κλασματων]{.greek-omitted} [κλασματα]{.greek-added} δωδεκα [κοφινους]{.greek-omitted} [πληρεις]{.greek-omitted} [κοφηνων]{.greek-added} [πληρωματα]{.greek-added} και απο των ιχθυων[6:43]{.aside}

και ησαν οι φαγοντες [ως]{.greek-added} [τους]{.greek-omitted} [αρτους]{.greek-omitted} πεντακισχιλιοι ανδρες[6:44]{.aside}

και ευθεως [ηναγκασεν]{.greek-omitted} [ηναγκασε]{.greek-added} τους μαθητας αυτου εμβηναι εις [το]{.greek-omitted} πλοιον και προαγειν [αυτον]{.greek-added} εις το περαν [προς]{.greek-omitted} [εις]{.greek-added} [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} εως αυτος [απολυση]{.greek-omitted} [απολυει]{.greek-added} τον οχλον[6:45]{.aside}

και αποταξαμενος αυτοις απηλθεν εις το ορος προσευξασθαι[6:46]{.aside}

και οψιας [γενομενης]{.greek-omitted} [γενωμενης]{.greek-added} ην [παλαι]{.greek-added} το πλοιον εν μεσω της θαλασσης και αυτος μονος επι της γης[6:47]{.aside}

και ειδεν αυτους βασανιζομενους εν τω ελαυνειν ην γαρ ο ανεμος εναντιος αυτοις και περι τεταρτην φυλακην της νυκτος ερχεται προς αυτους περιπατων επι της θαλασσης και [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρελθειν αυτους[6:48]{.aside}

οι δε ιδοντες αυτον περιπατουντα επι της θαλασσης [φαντασμα]{.greek-added} εδοξαν [φαντασμα]{.greek-omitted} ειναι και ανεκραξαν[6:49]{.aside}

παντες γαρ αυτον ειδον και εταραχθησαν και ευθεως [ελαλησεν]{.greek-omitted} [ελαλησε]{.greek-added} μετ αυτων και λεγει αυτοις θαρσειτε εγω ειμι μη [φοβεισθε]{.greek-omitted} [φοβησθε]{.greek-added}[6:50]{.aside}

και ανεβη προς αυτους εις το πλοιον και εκοπασεν ο ανεμος και [λιαν]{.greek-omitted} [εκπερισσου]{.greek-omitted} [εκ]{.greek-added} [περισσως]{.greek-added} εν εαυτοις εξισταντο και εθαυμαζον[6:51]{.aside}

ου γαρ συνηκαν επι τοις αρτοις ην γαρ αυτων η καρδια πεπωρωμενη[6:52]{.aside}

και διαπερασαντες ηλθον [επι]{.greek-omitted} [εις]{.greek-added} την γην [γεννησαρετ]{.greek-omitted} [γενησαρετ]{.greek-added} [και]{.greek-omitted} [προσωρμισθησαν]{.greek-omitted}[6:53]{.aside}

και εξελθοντων αυτων εκ του πλοιου ευθεως επιγνοντες αυτον[6:54]{.aside}

περιδραμοντες ολην την περιχωρον εκεινην ηρξαντο επι [τοις]{.greek-omitted} κραββατοις τους κακως εχοντας περιφερειν οπου ηκουον οτι [εστιν]{.greek-added} εκει [εστιν]{.greek-omitted}[6:55]{.aside}

και οπου αν εισεπορευετο εις κωμας η πολεις η αγρους εν ταις [αγοραις]{.greek-omitted} [πλατειαις]{.greek-added} ετιθουν τους ασθενουντας και παρεκαλουν αυτον ινα καν του κρασπεδου του ιματιου αυτου αψωνται και οσοι αν ηπτοντο αυτου εσωζοντο[6:56]{.aside}

### Chapter 7

και συναγονται προς αυτον οι φαρισαιοι και τινες των γραμματεων ελθοντες απο ιεροσολυμων[7:1]{.aside}

και ιδοντες τινας των μαθητων αυτου κοιναις [χερσιν]{.greek-omitted} [χερσι]{.greek-added} τουτ εστιν ανιπτοις εσθιοντας [τους]{.greek-added} αρτους εμεμψαντο[7:2]{.aside}

οι γαρ φαρισαιοι και παντες οι ιουδαιοι εαν μη πυγμη νιψωνται τας χειρας ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} κρατουντες την παραδοσιν των πρεσβυτερων[7:3]{.aside}

και [απο]{.greek-omitted} [απ]{.greek-added} αγορας εαν μη βαπτισωνται ουκ [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} και αλλα πολλα εστιν α παρελαβον κρατειν βαπτισμους ποτηριων και ξεστων και χαλκιων και κλινων[7:4]{.aside}

επειτα [επερωτωσιν]{.greek-omitted} [ερωτωσιν]{.greek-added} αυτον οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και οι γραμματεις δια τι οι μαθηται σου ου [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} κατα την παραδοσιν των πρεσβυτερων αλλα [ανιπτοις]{.greek-omitted} [κοιναις]{.greek-added} χερσιν [εσθιουσιν]{.greek-omitted} [εσθιουσι]{.greek-added} τον αρτον[7:5]{.aside}

ο δε αποκριθεις ειπεν αυτοις οτι καλως προεφητευσεν ησαιας περι υμων των υποκριτων ως γεγραπται ουτος ο λαος τοις [χειλεσιν]{.greek-omitted} [χειλεσι]{.greek-added} με τιμα η δε καρδια αυτων πορρω απεχει απ εμου[7:6]{.aside}

ματην δε σεβονται με διδασκοντες [διδασκαλιας]{.greek-omitted} [διδασκαλιαις]{.greek-added} ενταλματα [ανθρωπων]{.greek-abbr}[7:7]{.aside}

αφεντες γαρ την εντολην του [θεου]{.greek-abbr} κρατειτε την παραδοσιν των [ανθρωπων]{.greek-abbr} βαπτισμους ξεστων και ποτηριων και αλλα [πολλα]{.greek-added} παρομοια τοιαυτα [ποιουντες]{.greek-added} [πολλα]{.greek-omitted} [ποιειτε]{.greek-omitted}[7:8]{.aside}

και ελεγεν αυτοις καλως αθετειτε την εντολην του [θεου]{.greek-abbr} ινα την παραδοσιν υμων [τηρησητε]{.greek-omitted} [στησητε]{.greek-added}[7:9]{.aside}

[μωσης]{.greek-omitted} [μωυσης]{.greek-added} γαρ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} σου και ο κακολογων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} θανατω τελευτατω[7:10]{.aside}

υμεις δε λεγετε εαν ειπη [ανθρωπος]{.greek-abbr} τω [πατρι]{.greek-abbr} η τη [μητρι]{.greek-abbr} κορβαν ο [εστιν]{.greek-omitted} [εστι]{.greek-added} δωρον ο εαν εξ εμου ωφεληθης[7:11]{.aside}

[και]{.greek-omitted} ουκετι αφιετε αυτον ουδεν ποιησαι τω [πατρι]{.greek-abbr} [αυτου]{.greek-omitted} η τη [μητρι]{.greek-abbr} [αυτου]{.greek-omitted}[7:12]{.aside}

ακυρουντες τον λογον του [θεου]{.greek-abbr} τη παραδοσει υμων η παρεδωκατε και παρομοια τοιαυτα [ποιειτε]{.greek-added} πολλα [ποιειτε]{.greek-omitted}[7:13]{.aside}

και προσκαλεσαμενος παντα τον οχλον ελεγεν αυτοις ακουετε μου παντες και συνιετε[7:14]{.aside}

ουδεν εστιν εξωθεν του [ανθρωπου]{.greek-abbr} εισπορευομενον εις αυτον ο δυναται αυτον κοινωσαι αλλα τα εκπορευομενα απ αυτου εκεινα [εστιν]{.greek-omitted} [εστι]{.greek-added} τα κοινουντα τον [ανθρωπον]{.greek-abbr}[7:15]{.aside}

ει τις εχει ωτα ακουειν ακουετω[7:16]{.aside}

και οτε εισηλθεν [εις]{.greek-omitted} [οικον]{.greek-omitted} απο του οχλου [εις]{.greek-added} [οικον]{.greek-added} επηρωτων αυτον οι μαθηται [αυτου]{.greek-omitted} περι της παραβολης[7:17]{.aside}

και λεγει αυτοις ουτως και υμεις ασυνετοι εστε ου νοειτε οτι παν το εξωθεν εισπορευομενον εις τον [ανθρωπον]{.greek-abbr} ου δυναται αυτον κοινωσαι[7:18]{.aside}

οτι ουκ εισπορευεται αυτου εις την καρδιαν αλλ εις την κοιλιαν και εις τον αφεδρωνα εκπορευεται καθαριζον παντα τα βρωματα[7:19]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} δε οτι το εκ του [ανθρωπου]{.greek-abbr} εκπορευομενον εκεινο κοινοι τον [ανθρωπον]{.greek-abbr}[7:20]{.aside}

εσωθεν γαρ εκ της καρδιας των [ανθρωπων]{.greek-abbr} οι διαλογισμοι οι κακοι εκπορευονται μοιχειαι πορνειαι [κλοπαι]{.greek-added} φονοι[7:21]{.aside}

[κλοπαι]{.greek-omitted} [πλεονεξιαι]{.greek-omitted} [πλεονεξια]{.greek-added} [πονηριαι]{.greek-omitted} [πονηρια]{.greek-added} δολος ασελγεια οφθαλμος πονηρος βλασφημια [αφροσυνη]{.greek-added} υπερηφανια [αφροσυνη]{.greek-omitted}[7:22]{.aside}

παντα [ταυτα]{.greek-omitted} τα πονηρα εσωθεν [εκπορευεται]{.greek-omitted} [εκπορευονται]{.greek-added} [και]{.greek-omitted} [εκεινα]{.greek-added} κοινοι τον [ανθρωπον]{.greek-abbr}[7:23]{.aside}

και εκειθεν αναστας απηλθεν εις τα [μεθορια]{.greek-omitted} [ορια]{.greek-added} τυρου και [σιδωνος]{.greek-omitted} [σιδονος]{.greek-added} και εισελθων εις οικιαν ουδενα [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} γνωναι και ουκ ηδυνηθη λαθειν[7:24]{.aside}

ακουσασα γαρ [η]{.greek-added} γυνη περι αυτου ης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} [το]{.greek-omitted} θυγατριον [αυτης]{.greek-omitted} [εν]{.greek-added} [πνευμα]{.greek-omitted} [[πνευματι]{.greek-abbr}]{.greek-added} [ακαθαρτον]{.greek-omitted} [ακαθαρτω]{.greek-added} ελθουσα προσεπεσεν [αυτω]{.greek-added} [προς]{.greek-omitted} [τους]{.greek-omitted} [ποδας]{.greek-omitted} [αυτου]{.greek-omitted}[7:25]{.aside}

[η]{.greek-added} [δε]{.greek-added} [γυνη]{.greek-added} ην [δε]{.greek-omitted} [η]{.greek-omitted} [γυνη]{.greek-omitted} ελληνις [συρα]{.greek-added} [συραφοινικισσα]{.greek-omitted} [φοινικισσα]{.greek-added} τω γενει και ηρωτα αυτον ινα το δαιμονιον [εκβαλη]{.greek-omitted} [εκβαλλη]{.greek-added} [εκ]{.greek-omitted} της θυγατρος αυτης[7:26]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν [αυτη]{.greek-omitted} αφες πρωτον χορτασθηναι τα τεκνα ου γαρ καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} λαβειν τον αρτον των τεκνων και βαλειν τοις κυναριοις[7:27]{.aside}

η δε απεκριθη [λεγουσα]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} ναι [κυριε]{.greek-abbr} και γαρ τα κυναρια υποκατω της τραπεζης [εσθιει]{.greek-omitted} [εσθιουσιν]{.greek-added} απο των [ψιχιων]{.greek-omitted} [ψηχιων]{.greek-added} των [παιδιων]{.greek-omitted} [πιπτοντων]{.greek-added}[7:28]{.aside}

και ειπεν [αυτοις]{.greek-added} [αυτη]{.corr} [υπαγε]{.greek-added} δια τουτον τον λογον [υπαγε]{.greek-omitted} [εξεληλυθεν]{.greek-omitted} [εξεληλυθε]{.greek-added} το δαιμονιον εκ της θυγατρος σου[7:29]{.aside}

και απελθουσα εις τον οικον αυτης [ευρεν]{.greek-omitted} [ευρε]{.greek-added} το δαιμονιον εξεληλυθος και την θυγατερα βεβλημενην επι της κλινης[7:30]{.aside}

και παλιν εξελθων εκ των οριων τυρου και [σιδωνος]{.greek-omitted} [σιδ[ο]{.unclear}νος]{.greek-added} ηλθεν [προς]{.greek-omitted} [εις]{.greek-added} την θαλασσαν της γαλιλαιας ανα μεσον των οριων [της]{.greek-added} δεκαπολεως[7:31]{.aside}

και φερουσιν αυτω κωφον [και]{.greek-added} μογγιλαλον και παρακαλουσιν αυτον ινα επιθη αυτω την χειρα[7:32]{.aside}

και απολαβομενος αυτον απο του οχλου κατ ιδιαν [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} τους δακτυλους αυτου [πτυσας]{.greek-added} εις τα ωτα αυτου και [πτυσας]{.greek-omitted} ηψατο της γλωσσης αυτου[7:33]{.aside}

και αναβλεψας εις τον [ουρανον]{.greek-abbr} [εστεναξεν]{.greek-omitted} [εστεναξε]{.greek-added} και λεγει αυτω εφφαθα ο [εστιν]{.greek-omitted} [εστι]{.greek-added} διανοιχθητι[7:34]{.aside}

και ευθεως διηνοιχθησαν αυτου αι ακοαι και ελυθη ο δεσμος της γλωσσης αυτου και ελαλει ορθως[7:35]{.aside}

και [δι]{.greek-added} [διεστειλατο]{.greek-omitted} [εστειλατο]{.greek-added} αυτοις ινα μηδενι [ειπωσιν]{.greek-omitted} [λεγωσιν]{.greek-added} οσον δε [αυτος]{.greek-omitted} αυτοις διεστελλετο μαλλον περισσοτερον εκηρυσσον[7:36]{.aside}

και υπερπερισσως εξεπλησσοντο λεγοντες καλως παντα [πεποιηκεν]{.greek-omitted} [πεποιηκε]{.greek-added} [και]{.greek-omitted} τους κωφους ποιει ακουειν και τους αλαλους λαλειν[7:37]{.aside}

### Chapter 8

εν εκειναις [δε]{.greek-added} ταις ημεραις [παλιν]{.greek-added} [παμπολλου]{.greek-omitted} [πολλου]{.greek-added} οχλου οντος και μη εχοντων τι [φαγωσιν]{.greek-omitted} [φαγωσι]{.greek-added} προσκαλεσαμενος [ο]{.greek-omitted} [ιησους]{.greek-omitted} τους μαθητας αυτου λεγει αυτοις[8:1]{.aside}

σπλαγχνιζομαι επι τον οχλον οτι ηδη ημεραι τρεις [προσμενουσιν]{.greek-omitted} [προσμενουσι]{.greek-added} μοι και ουκ [εχουσιν]{.greek-omitted} [εχουσι]{.greek-added} τι [φαγωσιν]{.greek-omitted} [φαγουσι]{.greek-added}[8:2]{.aside}

και εαν απολυσω αυτους [νηστεις]{.greek-omitted} [νηστις]{.greek-added} εις οικον αυτων εκλυθησονται εν τη οδω τινες γαρ αυτων μακροθεν [ηκουσιν]{.greek-omitted} [ηκασι]{.greek-added}[8:3]{.aside}

και απεκριθησαν αυτω οι μαθηται αυτου ποθεν [τουτους]{.greek-omitted} [ωδε]{.greek-added} δυνησεται τις [ωδε]{.greek-omitted} χορτασαι [αυτους]{.greek-added} [αρτων]{.greek-omitted} [αρτον]{.greek-added} επ [ερημιας]{.greek-omitted} [ερημια]{.greek-added}[8:4]{.aside}

και επηρωτα αυτους ποσους εχετε αρτους οι δε ειπον επτα[8:5]{.aside}

και [παρηγγειλεν]{.greek-omitted} [παρηγγειλλεν]{.greek-added} τω οχλω αναπεσειν επι της γης και λαβων τους επτα αρτους [και]{.greek-added} ευχαριστησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [ε]{.greek-added} [εδιδου]{.greek-omitted} [διδου]{.greek-added} τοις μαθηταις αυτου ινα [παραθωσιν]{.greek-omitted} [παραθωσι]{.greek-added} και παρεθηκαν τω οχλω[8:6]{.aside}

και ειχον ιχθυδια ολιγα και [αυτα]{.greek-added} ευλογησας [ειπεν]{.greek-omitted} [ειπε]{.greek-added} παραθειναι [και]{.greek-omitted} [αυτα]{.greek-omitted}[8:7]{.aside}

[και]{.greek-added} εφαγον [δε]{.greek-omitted} και εχορτασθησαν και ηραν περισσευματα κλασματων επτα σπυριδας[8:8]{.aside}

ησαν δε οι φαγοντες ως τετρακισχιλιοι και απελυσεν αυτους[8:9]{.aside}

και [ευθεως]{.greek-omitted} εμβας [ευθυς]{.greek-added} εις το πλοιον μετα των μαθητων αυτου ηλθεν εις τα μερη [δαλμανουθα]{.greek-omitted} [μαγδαλα]{.greek-added}[8:10]{.aside}

και εξηλθον οι [φαρισαιοι]{.greek-omitted} [φαρισσαιοι]{.greek-added} και ηρξαντο συζητειν [αυτω]{.greek-omitted} [αυτον]{.greek-added} ζητουντες παρ αυτου σημειον απο του [ουρανου]{.greek-abbr} πειραζον[τε]{.unclear}ς αυτον[8:11]{.aside}

και αναστεναξας τω [πνευματι]{.greek-abbr} [αυτου]{.greek-omitted} λεγει τι η γενε[α]{.unclear} αυτη [ζητει]{.greek-added} σημειον [επιζητει]{.greek-omitted} αμην λεγω υμιν [ει]{.greek-omitted} [ου]{.greek-added} δοθησεται τη γενεα ταυτη σημειον[8:12]{.aside}

και αφεις αυτους [παλιν]{.greek-added} εμβας [παλιν]{.greek-omitted} εις πλοιον απηλθεν εις το περαν[8:13]{.aside}

και επελαθοντο λαβειν αρτους [και]{.greek-omitted} [ει]{.greek-omitted} [μη]{.greek-omitted} ενα [μονον]{.greek-added} [εχοντες]{.greek-added} [αρτον]{.greek-omitted} [ουκ]{.greek-omitted} [ειχον]{.greek-omitted} μεθ εαυτων [αρτον]{.greek-added} εν τω πλοιω[8:14]{.aside}

και διεστελλετο αυτοις λεγων [ορατε]{.greek-omitted} βλεπετε απο της ζυμης των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και της ζυμης [ηρωδου]{.greek-omitted} [των]{.greek-added} [ηρωδιανων]{.greek-added}[8:15]{.aside}

και διελογιζοντο προς αλληλους [λεγοντες]{.greek-omitted} οτι αρτους ουκ εχομεν[8:16]{.aside}

[και]{.greek-omitted} γνους [δε]{.greek-added} ο [ιησους]{.greek-abbr} λεγει αυτοις τι διαλογιζεσθε οτι αρτους ουκ εχετε ουπω νοειτε ουδε συνιετε [ετι]{.greek-omitted} πεπωρωμενην εχετε την καρδιαν υμων[8:17]{.aside}

οφθαλμους εχοντες ου βλεπετε και ωτα εχοντες ουκ ακουετε [και]{.greek-omitted} [ου]{.greek-omitted} [ουπω]{.greek-added} [νοειτε]{.greek-added} [ουδε]{.greek-added} μνημονευετε[8:18]{.aside}

[οτε]{.greek-omitted} [οτι]{.greek-added} τους πεντε αρτους εκλασα εις τους πεντακισχιλιους [και]{.greek-added} ποσους [κοφινους]{.greek-omitted} [κοφηνους]{.greek-added} πληρεις κλασματων ηρατε λεγουσιν αυτω δωδεκα[8:19]{.aside}

οτε δε τους επτα εις τους τετρακισχιλιους ποσων σπυριδων [κλασματων]{.greek-added} πληρωματα [κλασματων]{.greek-omitted} ηρατε οι δε ειπον επτα[8:20]{.aside}

και [ελεγεν]{.greek-omitted} [λεγει]{.greek-added} αυτοις πως ου συνιετε[8:21]{.aside}

και [ερχεται]{.greek-omitted} [ερχονται]{.greek-added} εις [βηθσαιδαν]{.greek-omitted} [βηθσαιδα]{.greek-added} και φερουσιν αυτω τυφλον και παρακαλουσιν αυτον ινα αυτου αψηται[8:22]{.aside}

και επιλαβομενος της χειρος [αυτον]{.greek-added} [του]{.greek-omitted} [τυφλου]{.greek-omitted} εξηγαγεν [αυτον]{.greek-omitted} εξω της κωμης και πτυσας εις τα ομματα αυτου [και]{.greek-added} επιθεις τας χειρας αυτω επηρωτα αυτον ει τι βλεπει[8:23]{.aside}

και αναβλεψας [ε]{.greek-added} [ελεγεν]{.greek-omitted} [λεγε]{.greek-added} βλεπω τους [ανθρωπους]{.greek-abbr} [οτι]{.greek-omitted} ως δενδρα [ορω]{.greek-omitted} περιπατουντας[8:24]{.aside}

ειτα παλιν [επεθηκεν]{.greek-omitted} [επεθηκε]{.greek-added} τας χειρας [αυτου]{.greek-added} επι τους οφθαλμους [αυτου]{.greek-omitted} [του]{.greek-added} [τυφλου]{.greek-added} και [διεβλεψε]{.greek-added} [εποιησεν]{.greek-omitted} [αυτον]{.greek-omitted} [αναβλεψαι]{.greek-omitted} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} και [ενεβλεψεν]{.greek-omitted} [ενεβλεπε]{.greek-added} τηλαυγως [απαντας]{.greek-omitted} [απαντα]{.greek-added}[8:25]{.aside}

και απεστειλεν αυτον εις τον οικον αυτου λεγων [μηδε]{.greek-omitted} [υπαγε]{.greek-added} [εις]{.greek-added} [τον]{.greek-added} [οικον]{.greek-added} [σου]{.greek-added} [και]{.greek-added} [εαν]{.greek-added} εις την κωμην εισελθης [μηδε]{.greek-omitted} [μηδενι]{.greek-added} ειπης [τινι]{.greek-omitted} εν τη κωμη[8:26]{.aside}

και [εξηλθεν]{.greek-omitted} [απηλθεν]{.greek-added} ο [ιησους]{.greek-abbr} και οι μαθηται αυτου εις τας κωμας καισαρειας της φιλιππου και εν τη οδω επηρωτα τους μαθητας αυτου λεγων αυτοις τινα με λεγουσιν οι [ανθρωποι]{.greek-abbr} ειναι[8:27]{.aside}

οι δε απεκριθησαν [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} τον βαπτιστην [και]{.greek-omitted} αλλοι [δε]{.greek-added} ηλιαν αλλοι δε ενα των προφητων[8:28]{.aside}

[και]{.greek-omitted} [αυτος]{.greek-omitted} λεγει αυτοις υμεις δε τινα με λεγετε ειναι αποκριθεις δε ο πετρος λεγει αυτω συ ει ο [χριστος]{.greek-abbr}[8:29]{.aside}

και επετιμησεν αυτοις ινα μηδενι [λεγωσιν]{.greek-omitted} [λεγωσι]{.greek-added} περι αυτου[8:30]{.aside}

και ηρξατο διδασκειν αυτους οτι δει τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} πολλα παθειν και [αποδοκιμασθηναι]{.greek-omitted} [αποδοκι]{.greek-added} [μασθηναι]{.greek-added} απο των πρεσβυτερων και των αρχιερεων και των γραμματεων και αποκτανθηναι και [μετα]{.greek-omitted} [τρεις]{.greek-omitted} [τη]{.greek-added} [τριτη]{.greek-added} [ημερας]{.greek-omitted} [ημερα]{.greek-added} αναστηναι[8:31]{.aside}

και παρρησια τον λογον ελαλει και προσλαβομενος αυτον ο πετρος ηρξατο επιτιμαν αυτω[8:32]{.aside}

ο δε επιστραφεις και ιδων τους μαθητας αυτου [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω πετρω λεγων υπαγε οπισω μου σατανα οτι ου φρονεις τα του [θεου]{.greek-abbr} αλλα τα των [ανθρωπων]{.greek-abbr}[8:33]{.aside}

και προσκαλεσαμενος τον οχλον συν τοις μαθηταις αυτου ειπεν αυτοις [ει]{.greek-added} [οστις]{.greek-omitted} [τις]{.greek-added} θελει οπισω μου [ακολουθειν]{.greek-omitted} [ελθειν]{.greek-added} απαρνησασθω εαυτον και αρατω τον [σταυρον]{.greek-abbr} αυτου και [ακολουθειτω]{.greek-omitted} [ακολουθητω]{.greek-added} μοι[8:34]{.aside}

ος γαρ αν θελη την ψυχην αυτου σωσαι απολεσει αυτην ος δ αν απολεση την εαυτου ψυχην ενεκεν εμου και του ευαγγελιου [ουτος]{.greek-omitted} σωσει αυτην[8:35]{.aside}

τι γαρ ωφελησει [τον]{.greek-added} [ανθρωπον]{.greek-abbr} εαν κερδησ[η]{.unclear} τον κοσμον ολον [και]{.greek-omitted} [ζημιωθη]{.greek-omitted} την [δε]{.greek-added} ψυχην αυτου [ζημιωθη]{.greek-added}[8:36]{.aside}

η τι δωσει [ανθρωπος]{.greek-abbr} ανταλλαγμα της ψυχης αυτου[8:37]{.aside}

ος γαρ [εαν]{.greek-omitted} [αν]{.greek-added} επαισχυνθη με και τους εμους λογους εν τη γενεα ταυτη τη μοιχαλιδι και αμαρτωλω και ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} επαισχυνθησεται αυτον οταν ελθη εν τη δοξη του [πατρος]{.greek-abbr} αυτου [και]{.greek-added} [μετα]{.greek-omitted} [των]{.greek-omitted} [αγγελων]{.greek-omitted} των αγιων [αγγελων]{.greek-added}[8:38]{.aside}

### Chapter 9

και ελεγεν αυτοις αμην λεγω υμιν οτι [εισιν]{.greek-omitted} [εισι]{.greek-added} τινες των ωδε εστηκοτων οιτινες ου μη γευσωνται θανατου εως αν [ιδωσιν]{.greek-omitted} [ιδωσι]{.greek-added} την βασιλειαν του [θεου]{.greek-abbr} εληλυθυιαν [προς]{.greek-added} [αυτους]{.greek-added} εν δυναμει[9:1]{.aside}

και μεθ ημερας εξ παραλαμβανει ο [ιησους]{.greek-abbr} τον πετρον και τον ιακωβον και [ιωαννην]{.greek-omitted} [τον]{.greek-added} [[ιω]{.greek-abbr}]{.greek-added} και αναφερει αυτους εις ορος υψηλον κατ ιδιαν μονους και μετεμορφωθη εμπροσθεν αυτων[9:2]{.aside}

και τα ιματια αυτου εγενοντο στιλβοντα λευκα λιαν ως χιων οια γναφευς επι της γης ου δυναται [ουτως]{.greek-added} λευκαναι[9:3]{.aside}

και ωφθη αυτοις ηλιας συν [μωση]{.greek-omitted} [μωυση]{.greek-added} και ησαν συλλαλουντες τω [ιησου]{.greek-abbr}[9:4]{.aside}

και αποκριθεις ο πετρος [λεγει]{.greek-omitted} [ελεγε]{.greek-added} τω [ιησου]{.greek-abbr} ραββι καλον εστιν ημας ωδε ειναι [και]{.greek-omitted} ποιησωμεν σκηνας τρεις σοι μιαν και [μωση]{.greek-omitted} [μωυσει]{.greek-added} μιαν και ηλια μιαν[9:5]{.aside}

ου γαρ ηδει [[ηδεισαν]{.corr}]{.greek-added} τι [λαλησει]{.greek-omitted} [αποκριθηναι]{.greek-added} ησαν γαρ εκφοβοι[9:6]{.aside}

και [ιδου]{.greek-added} εγενετο νεφελη επισκιαζουσα αυτοις και [ηλθεν]{.greek-omitted} φωνη [εγενετο]{.greek-added} εκ της νεφελης ουτος εστιν ο [υιος]{.greek-abbr} μου ο αγαπητος αυτου ακουετε[9:7]{.aside}

και εξαπινα περιβλεψαμενοι ουκετι ουδενα ειδον αλλα τον [ιησουν]{.greek-abbr} μονον μεθ εαυτων[9:8]{.aside}

καταβαινοντων δε αυτων απο του ορους διεστειλατο αυτοις ινα μηδενι [διηγησωνται]{.greek-omitted} α ειδον [εξηγησωνται]{.greek-added} ει μη οταν ο υιος του [ανθρωπου]{.greek-abbr} εκ νεκρων αναστη[9:9]{.aside}

και τον λογον εκρατησαν προς εαυτους συζητουντες τι [εστιν]{.greek-omitted} [εστι]{.greek-added} το εκ νεκρων αναστηναι[9:10]{.aside}

και [επηρωτων]{.greek-omitted} [επηρωτησαν]{.greek-added} αυτον λεγοντες οτι λεγουσιν οι γραμματεις [οτι]{.greek-omitted} ηλιαν δει ελθειν πρωτον[9:11]{.aside}

ο δε αποκριθεις ειπεν αυτοις ηλιας [μεν]{.greek-omitted} ελθων πρωτον [αποκαθιστα]{.greek-omitted} [αποκαθιστανει]{.greek-added} παντα και πως γεγραπται επι τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ινα πολλα παθη και [εξουδενωθη]{.greek-omitted} [εξουθενωθη]{.greek-added}[9:12]{.aside}

αλλα λεγω υμιν οτι [και]{.greek-omitted} ηλιας [εληλυθεν]{.greek-omitted} [ηλθε]{.greek-added} και εποιησαν αυτω οσα ηθελησαν καθως γεγραπται επ αυτον[9:13]{.aside}

και ελθων προς τους μαθητας ειδεν οχλον [πολυν]{.greek-omitted} περι αυτους και γραμματεις συζητουντας [προς]{.greek-added} [αυτοις]{.greek-omitted} [αυτους]{.greek-added}[9:14]{.aside}

και [ευθεως]{.greek-omitted} [ευθυς]{.greek-added} πας ο οχλος [ιδων]{.greek-omitted} [ι]{.greek-added} [δοντες]{.greek-added} αυτον [εξεθαμβηθη]{.greek-omitted} [εξεθαμβηθησαν]{.greek-added} και προστρεχοντες ησπαζοντο αυτον[9:15]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τους γραμματεις τι συζητειτε προς αυτους[9:16]{.aside}

και αποκριθεις εις εκ του οχλου ειπεν [αυτω]{.greek-added} διδασκαλε ηνεγκα τον [υιον]{.greek-abbr} μου προς σε εχοντα [πνευμα]{.greek-abbr} αλαλον[9:17]{.aside}

και οπου [αν]{.greek-omitted} [εαν]{.greek-added} αυτον καταλαβη ρησσει αυτον και αφριζει και τριζει τους οδοντας [αυτου]{.greek-omitted} και ξηραινεται και [ειπον]{.greek-omitted} [ειπα]{.greek-added} τοις μαθηταις σου ινα αυτο [εκβαλωσιν]{.greek-omitted} [εκβαλλωσι]{.greek-added} και ουκ ισχυσαν[9:18]{.aside}

[και]{.greek-added} [ο]{.greek-omitted} [δε]{.greek-omitted} αποκριθεις [αυτω]{.greek-omitted} [αυτοις]{.greek-added} λεγει ω γενεα απιστος [και]{.greek-added} [διεστραμμενη]{.greek-added} εως ποτε προς υμας εσομαι εως ποτε ανεξομαι υμων φερετε αυτον προς με[9:19]{.aside}

και ηνεγκαν αυτον προς αυτον και ιδων αυτον ευθεως το [πνευμα]{.greek-abbr} εσπαραξεν αυτον και πεσων επι της γης εκυλιετο αφριζων[9:20]{.aside}

και [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [πατερα]{.greek-abbr} αυτου [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ποσος χρονος εστιν ως τουτο γεγονεν αυτω ο δε ειπεν [εκ]{.greek-added} [παιδιοθεν]{.greek-omitted} [παιδοθεν]{.greek-added}[9:21]{.aside}

και πολλακις αυτον [και]{.greek-omitted} εις [το]{.greek-omitted} πυρ [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} και εις υδατα ινα απολεση αυτον [αλλ]{.greek-omitted} [αλ]{.greek-added} [λ]{.greek-added} ει τι [δυνασαι]{.greek-omitted} [δυνη]{.greek-added} βοηθησον ημιν [[κυριε]{.greek-abbr}]{.greek-added} σπλαγχνισθεις εφ ημας[9:22]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω το ει δυνασαι πιστευσαι παντα δυνατα τω πιστευοντι[9:23]{.aside}

και ευθεως κραξας ο [πατηρ]{.greek-abbr} του παιδιου [μετα]{.greek-omitted} [δακρυων]{.greek-omitted} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} πιστευω [κυριε]{.greek-abbr} βοηθει μου τη απιστια[9:24]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} οτι επισυντρεχει [ο]{.greek-added} οχλος [επετιμησεν]{.greek-omitted} [επετιμησε]{.greek-added} τω [πνευματι]{.greek-abbr} τω ακαθαρτω λεγων αυτω το [πνευμα]{.greek-omitted} [το]{.greek-omitted} αλαλον και κωφον [[πνευμα]{.greek-abbr}]{.greek-added} εγω [επιτασσω]{.greek-added} σοι [επιτασσω]{.greek-omitted} εξελθε εξ αυτου και μηκετι εισελθης εις αυτον[9:25]{.aside}

και κραξαν [πολλα]{.greek-added} και [πολλα]{.greek-omitted} σπαραξαν [αυτον]{.greek-omitted} [εξηλθεν]{.greek-omitted} [εξηλθε]{.greek-added} και εγενετο ωσει νεκρος ωστε πολλους λεγειν οτι απεθανεν[9:26]{.aside}

ο δε [ιησους]{.greek-abbr} κρατησας [αυτον]{.greek-omitted} της χειρος [αυτου]{.greek-added} ηγειρεν αυτον και ανεστη[9:27]{.aside}

και [εισελθοντα]{.greek-omitted} [εισελθοντος]{.greek-added} [αυτον]{.greek-omitted} [αυτου]{.greek-added} εις οικον οι μαθηται αυτου [επηρωτων]{.greek-omitted} [αυτον]{.greek-omitted} κατ ιδιαν [ηρωτησαν]{.greek-added} [αυτον]{.greek-added} οτι ημεις ουκ ηδυνηθημεν εκβαλειν αυτο[9:28]{.aside}

και ειπεν αυτοις τουτο το γενος εν ουδενι [εξερχεται]{.greek-added} [δυναται]{.greek-omitted} [εξελθειν]{.greek-omitted} ει μη εν προσευχη και νηστεια[9:29]{.aside}

[και]{.greek-omitted} [εκειθεν]{.greek-omitted} [κακειθεν]{.greek-added} εξελθοντες παρεπορευοντο δια της γαλιλαιας και ουκ ηθελεν ινα τις γνω[9:30]{.aside}

[εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} γαρ τους μαθητας αυτου [λεγων]{.greek-added} [και]{.greek-omitted} [ελεγεν]{.greek-omitted} αυτοις οτι ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} [παραδιδοται]{.greek-omitted} [παραδοθησεται]{.greek-added} εις χειρας [ανθρωπων]{.greek-abbr} και αποκτενουσιν αυτον και αποκτανθεις τη τριτη [εγειρεται]{.greek-added} ημερα [αναστησεται]{.greek-omitted}[9:31]{.aside}

οι δε ηγνοουν το ρημα και εφοβουντο αυτον επερωτησαι[9:32]{.aside}

και [ηλθεν]{.greek-omitted} [ηλθον]{.greek-added} εις καπερναουμ και εν τη οικια γενομενος επηρωτα αυτους τι εν τη οδω [διελλεγχθητε]{.greek-added} προς [εαυτους]{.greek-omitted} [αυτους]{.greek-added} [διελογιζεσθε]{.greek-omitted}[9:33]{.aside}

οι δε εσιωπων προς αλληλους γαρ [διελεχθησαν]{.greek-omitted} [διελλεγχθησαν]{.greek-added} εν τη οδω τις μειζων[9:34]{.aside}

και καθισας [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} τους δωδεκα και λεγει αυτοις ει τις θελει πρωτος ειναι εσται παντων εσχατος και παντων διακονος[9:35]{.aside}

και λαβων παιδιον εστησεν αυτο εν μεσω αυτων και εναγκαλισαμενος αυτο ειπεν αυτοις[9:36]{.aside}

ος [εαν]{.greek-omitted} [αν]{.greek-added} εν [εκ]{.greek-added} των τοιουτων παιδιων δεξηται επι τω ονοματι μου εμε δεχεται και ος [εαν]{.greek-omitted} [αν]{.greek-added} εμε δεξηται ουκ εμε δεχεται αλλα τον [αποστειλαντα]{.greek-omitted} [πεμψαντα]{.greek-added} με[9:37]{.aside}

[απεκριθη]{.greek-omitted} [αποκριθη]{.greek-added} δε αυτω [ιωαννης]{.greek-omitted} [λεγων]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [και]{.greek-added} [λεγει]{.greek-added} διδασκαλε [ειδομεν]{.greek-omitted} [ιδομεν]{.greek-added} τινα [εν]{.greek-added} τω ονοματι σου εκβαλλοντα δαιμονια [ος]{.greek-omitted} [οστις]{.greek-added} ουκ ακολουθει ημιν και εκωλυσαμεν αυτον [οτι]{.greek-omitted} [ουκ]{.greek-omitted} [ακολουθει]{.greek-omitted} [ημιν]{.greek-omitted}[9:38]{.aside}

ο δε [ιησους]{.greek-omitted} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} μη [κωλυετε]{.greek-omitted} [κωλυητε]{.greek-added} [αυτον]{.greek-omitted} [αυτους]{.greek-added} ουδεις γαρ εστιν ος ποιησει δυναμιν [επι]{.greek-omitted} [εν]{.greek-added} τω ονοματι μου και δυνησεται [ταχυ]{.greek-omitted} [με]{.greek-added} κακολογησαι [με]{.greek-omitted}[9:39]{.aside}

ος γαρ ουκ [εστι]{.greek-added} [καθ]{.greek-added} [ημων]{.greek-added} [υπερ]{.greek-added} [ημων]{.greek-added} εστιν [καθ]{.greek-omitted} [υμων]{.greek-omitted} [υπερ]{.greek-omitted} [υμων]{.greek-omitted} [εστιν]{.greek-omitted}[9:40]{.aside}

ος γαρ αν ποτιση υμας ποτηριον υδατος εν [τω]{.greek-added} ονοματι μου οτι [χριστου]{.greek-abbr} εστε αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[9:41]{.aside}

και ος [εαν]{.greek-omitted} [αν]{.greek-added} σκανδαλιση ενα των μικρων [τουτων]{.greek-added} των πιστευοντων εις [εμε]{.greek-omitted} [αυτον]{.greek-added} καλον [εστιν]{.greek-omitted} [εστι]{.greek-added} [μαλλον]{.greek-added} αυτω [μαλλον]{.greek-omitted} ει περικειται [μυλικος]{.greek-added} λιθος [μυλικος]{.greek-omitted} περι τον τραχηλον αυτου και βεβληται εις την θαλασσαν[9:42]{.aside}

και εαν σκανδαλιζη σε η χειρ σου αποκοψον αυτην καλον σοι [εστιν]{.greek-omitted} [εστι]{.greek-added} κυλλον εις την ζωην εισελθειν η τας δυο χειρας εχοντα απελθειν εις την γεενναν εις το πυρ το ασβεστον[9:43]{.aside}

οπου ο σκωληξ [αυτων]{.greek-omitted} ου τελευτα και το πυρ ου σβεννυται[9:44]{.aside}

και εαν ο πους σου σκανδαλιζη σε [αποκοψον]{.greek-omitted} [αποκο]{.greek-added} [ψον]{.greek-added} αυτον καλον εστιν [σοι]{.greek-omitted} εισελθειν [σε]{.greek-added} εις [την]{.greek-omitted} ζωην χωλον η τους δυο ποδας εχοντα βληθηναι εις την γεενναν εις το πυρ το ασβεστον[9:45]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:46]{.aside}

και εαν ο οφθαλμος σου σκανδαλιζη σε [εκβαλε]{.greek-omitted} [εκβαλλον]{.greek-added} αυτον καλον [σοι]{.greek-omitted} [εστιν]{.greek-omitted} [εστι]{.greek-added} [σε]{.greek-added} μονοφθαλμον εισελθειν εις την βασιλειαν του [θεου]{.greek-abbr} η δυο οφθαλμους εχοντα βληθηναι εις την γεενναν του πυρος[9:47]{.aside}

οπου ο σκωληξ αυτων ου τελευτα και το πυρ ου σβεννυται[9:48]{.aside}

πας γαρ πυρι αλισθησεται και πασα θυσια αλι αλισθησεται[9:49]{.aside}

καλον το αλας εαν δε το αλας αναλον γενηται εν τινι αυτο αρτυσετε εχετε εν εαυτοις αλας και ειρηνευετε εν αλληλοις[9:50]{.aside}

### Chapter 10

[και]{.greek-added} [κακειθεν]{.greek-omitted} [εκειθεν]{.greek-added} αναστας ερχεται εις τα [ορια]{.greek-omitted} [ορα]{.greek-added} της ιουδαιας [δια]{.greek-omitted} [του]{.greek-omitted} περαν του ιορδανου και [συμπορευονται]{.greek-omitted} [συμπορευεται]{.greek-added} παλιν [οχλοι]{.greek-omitted} [οχλος]{.greek-added} προς αυτον και ως ειωθει παλιν εδιδασκεν αυτους[10:1]{.aside}

[και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} [φαρισσαιοι]{.greek-added} προσελθοντες [φαρισαιοι]{.greek-omitted} [επηρωτησαν]{.greek-omitted} [[ε]{.unclear}πηρω]{.greek-added} [τησαν]{.greek-added} αυτον ει εξεστιν ανδρι γυναικα απολυσαι πειραζοντες αυτον[10:2]{.aside}

ο δε αποκριθεις ειπεν αυτοις τι υμιν ενετειλατο [μωσης]{.greek-omitted} [μωυσης]{.greek-added}[10:3]{.aside}

οι δε ειπον [μωσης]{.greek-omitted} [μωυσης]{.greek-added} [επετρεψεν]{.greek-omitted} [επετρεψε]{.greek-added} [βιβλιον]{.greek-omitted} [βιβλιου]{.greek-added} αποστασιου γραψαι και απολυσαι[10:4]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις προς την [σ]{.greek-supplied}κληροκαρδιαν υμων εγραψεν υμιν [μωυσης]{.greek-added} την εντολην ταυτην[10:5]{.aside}

απο δε αρχης κτισεως αρσεν και θηλυ εποιησεν αυτους ο [θεος]{.greek-abbr}[10:6]{.aside}

[και]{.greek-added} [ειπεν]{.greek-added} ενεκεν τουτου καταλειψει [ανθρωπος]{.greek-abbr} τον [πατερα]{.greek-abbr} αυτου και την [μητερα]{.greek-abbr} και προσκολληθησεται προς την γυναικα αυτου[10:7]{.aside}

και εσονται οι δυο εις σαρκα μιαν ωστε ουκετι [εισιν]{.greek-omitted} [εισι]{.greek-added} δ[υο]{.unclear} αλλα [σαρξ]{.greek-added} μια [σαρξ]{.greek-omitted}[10:8]{.aside}

ο ουν ο [θεος]{.greek-abbr} συνεζευξεν [ανθρωπος]{.greek-abbr} μη χωριζετω[10:9]{.aside}

και εν τη οικια παλιν οι μαθηται αυτου [περι]{.greek-omitted} [του]{.greek-omitted} [αυτου]{.greek-omitted} επηρωτησαν αυτον [περι]{.greek-added} [τουτου]{.greek-added}[10:10]{.aside}

και λεγει αυτοις [ος]{.greek-omitted} εαν απολυση [την]{.greek-omitted} [γυναικα]{.greek-omitted} [αυτου]{.greek-omitted} [γυνη]{.greek-added} [τον]{.greek-added} [ανδρα]{.greek-added} [εαυτης]{.greek-added} και γαμηση [αλλην]{.greek-omitted} [αλλον]{.greek-added} μοιχαται [επ]{.greek-omitted} [αυτην]{.greek-omitted}[10:11]{.aside}

και εαν [γυνη]{.greek-omitted} [ανηρ]{.greek-added} απολυση [τον]{.greek-omitted} [ανδρα]{.greek-omitted} [αυτης]{.greek-omitted} [την]{.greek-added} [γυναικα]{.greek-added} [εαυτου]{.greek-added} και [γαμηθη]{.greek-omitted} [γαμηση]{.greek-added} [αλλω]{.greek-omitted} [αλλην]{.greek-added} μοιχαται[10:12]{.aside}

και προσεφερον αυτω παιδια ινα αψηται αυτων οι δε μαθηται επετιμων τοις προσφερουσιν[10:13]{.aside}

ιδων δε ο [ιησους]{.greek-abbr} [ηγανακτησεν]{.greek-omitted} [ηγανακτησε]{.greek-added} και [επιτιμησας]{.greek-added} ειπεν αυτοις αφετε τα παιδια ερχεσθαι προς με [και]{.greek-added} μη κωλυετε αυτα των γαρ τοιουτων εστιν η βασιλεια του [θεου]{.greek-abbr}[10:14]{.aside}

αμην λεγω υμιν ος [εαν]{.greek-omitted} [αν]{.greek-added} μη δεξηται την βασιλειαν του [θεου]{.greek-abbr} ως παιδιον ου μη εισελθη εις αυτην[10:15]{.aside}

και εναγκαλισαμενος αυτα τιθεις τας χειρας επ αυτα [ευλογει]{.greek-omitted} [ηυλογει]{.greek-added} αυτα[10:16]{.aside}

και εκπορευομενου αυτου εις οδον [ιδου]{.greek-added} [τις]{.greek-added} [πλουσιος]{.greek-added} προσδραμων [εις]{.greek-omitted} και γονυπετησας [αυτον]{.greek-omitted} επηρωτα αυτον [λεγων]{.greek-added} διδασκαλε αγαθε τι ποιησω ινα ζωην αιωνιον κληρονομησω[10:17]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω τι με λεγεις αγαθον ουδεις αγαθος ει μη εις ο [θεος]{.greek-abbr}[10:18]{.aside}

τας εντολας οιδας μη μοιχευσης μη φονευσης μη κλεψης μη ψευδομαρτυρησης [μη]{.greek-omitted} [αποστερησης]{.greek-omitted} τιμα τον [πατερα]{.greek-abbr} σου και την [μητερα]{.greek-abbr} [σου]{.greek-added}[10:19]{.aside}

ο δε αποκριθεις ειπεν [αυτω]{.greek-omitted} [διδασκαλε]{.greek-omitted} ταυτα παντα [εφυλαξαμην]{.greek-omitted} [εποιησα]{.greek-added} εκ νεοτητος μου[10:20]{.aside}

ο δε [ιησους]{.greek-abbr} εμβλεψας [αυτω]{.greek-omitted} ηγαπησεν αυτον και ειπεν αυτω [εν]{.greek-omitted} [σοι]{.greek-omitted} [υστερει]{.greek-omitted} υπαγε οσα εχεις πωλησον και δος [τοις]{.greek-added} πτωχοις και εξεις θησαυρον εν [ουρανω]{.greek-abbr} και [αρας]{.greek-added} [τον]{.greek-added} [[σταυρον]{.greek-abbr}]{.greek-added} δευρο ακολουθει μοι [αρας]{.greek-omitted} [τον]{.greek-omitted} [σταυρον]{.greek-omitted}[10:21]{.aside}

ο δε στυγνασας επι τω λογω [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} λυπουμενος ην γαρ εχων κτηματα πολλα[10:22]{.aside}

και περιβλεψαμενος ο [ιησους]{.greek-abbr} λεγει τοις μαθηταις αυτου πως δυσκολως οι τα χρηματα εχοντες εις την βασιλειαν του [θεου]{.greek-abbr} εισελευσονται[10:23]{.aside}

οι δε μαθηται εθαμβουντο επι τοις λογοις αυτου ο δε [ιησους]{.greek-abbr} παλιν αποκριθεις λεγει αυτοις τεκνα πως δυσκολον [εστιν]{.greek-omitted} [εστι]{.greek-added} τους πεποιθοτας επι [τοις]{.greek-added} χρημασιν εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:24]{.aside}

ευκοπωτερον [εστιν]{.greek-omitted} [εστι]{.greek-added} καμηλον δια [της]{.greek-omitted} τρυμαλιας [της]{.greek-omitted} ραφιδος [εισελθειν]{.greek-omitted} [διελθειν]{.greek-added} η πλουσιον εις την βασιλειαν του [θεου]{.greek-abbr} εισελθειν[10:25]{.aside}

οι δε περισσως εξεπλησσοντο λεγοντες προς εαυτους και τις δυναται σωθηναι[10:26]{.aside}

εμβλεψας δε αυτοις ο [ιησους]{.greek-abbr} λεγει παρα [ανθρωποις]{.greek-abbr} [τουτο]{.greek-added} αδυνατον [εστι]{.greek-added} αλλ ου παρα [θεω]{.greek-abbr} παντα γαρ δυνατα [εστιν]{.greek-omitted} παρα τω [θεω]{.greek-abbr}[10:27]{.aside}

[και]{.greek-added} ηρξατο [λεγειν]{.greek-added} [αυτω]{.greek-added} ο πετρος [λεγειν]{.greek-omitted} [αυτω]{.greek-omitted} ιδου ημεις αφηκαμεν παντα και ηκολουθησαμεν σοι[10:28]{.aside}

[και]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αμην λεγω υμιν ουδεις εστιν ος αφηκεν οικιαν η αδελφους η αδελφας η [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} η γυναικα η τεκνα η αγρους ενεκεν εμου και ενεκεν του ευαγγελιου[10:29]{.aside}

εαν μη λαβη [νυν]{.greek-added} εκατονταπλασιονα [νυν]{.greek-omitted} εν τω καιρω τουτω οικιας και αδελφους και αδελφας και [[πατερα]{.greek-abbr}]{.greek-added} [και]{.greek-added} [μητερας]{.greek-omitted} [[μητερα]{.greek-abbr}]{.greek-added} και τεκνα και αγρους μετα διωγμων και εν τω αιωνι τω ερχομενω ζωην αιωνιον[10:30]{.aside}

πολλοι δε εσονται πρωτοι εσχατοι και εσχατοι πρωτοι[10:31]{.aside}

ησαν δε εν τη οδω αναβαινοντες εις ιεροσολυμα και ην προαγων αυτους ο [ιησους]{.greek-abbr} και εθαμβουντο [και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} ακολουθουντες εφοβουντο και παραλαβων παλιν τους δωδεκα ηρξατο αυτοις λεγειν τα μελλοντα αυτω συμβαινειν[10:32]{.aside}

οτι ιδου [αναβαινομεν]{.greek-omitted} [αναβαι]{.greek-added} [νομεν]{.greek-added} εις ιεροσολυμα και ο υιος του [ανθρωπου]{.greek-abbr} παραδοθησεται τοις [αρχιερευσιν]{.greek-omitted} [αρχιερευσι]{.greek-added} και [τοις]{.greek-added} [γραμματευσιν]{.greek-omitted} [γραμματευσι]{.greek-added} και κατακρινουσιν αυτον θανατω και παραδωσουσιν αυτον τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:33]{.aside}

και εμπαιξουσιν [αυτω]{.greek-added} [και]{.greek-added} [εμπτυσουσιν]{.greek-added} αυτω και μαστιγωσουσιν αυτον και [εμπτυσουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [και]{.greek-omitted} [αποκτενουσιν]{.greek-omitted} [αποκτενουσι]{.greek-added} [αυτον]{.greek-omitted} και τη τριτη ημερα αναστησεται[10:34]{.aside}

και προσπορευονται αυτω ιακωβος και [[ιω]{.greek-abbr}]{.greek-added} [ιωαννης]{.greek-omitted} [οι]{.greek-omitted} υιοι ζεβεδαιου λεγοντες διδασκαλε θελομεν ινα ο εαν αιτησωμεν ποιησης [ημιν]{.greek-omitted}[10:35]{.aside}

ο δε ειπεν αυτοις τι θελετε [με]{.greek-added} ποιησαι [με]{.greek-omitted} υμιν[10:36]{.aside}

οι δε ειπον αυτω δος ημιν ινα εις [εκ]{.greek-omitted} [δεξιων]{.greek-omitted} [εξ]{.greek-added} [ευωνυμων]{.greek-added} σου και εις [εξ]{.greek-omitted} [ευωνυμων]{.greek-omitted} [εκ]{.greek-added} [δεξιων]{.greek-added} σου καθισωμεν εν τη δοξη σου[10:37]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} ειπεν αυτοις ουκ οιδατε τι αιτεισθε δυνασθε πιειν το ποτηριον ο εγω πινω [και]{.greek-omitted} [η]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι[10:38]{.aside}

οι δε ειπον [αυτω]{.greek-omitted} δυναμεθα ο δε [ιησους]{.greek-abbr} ειπεν αυτοις το μεν ποτηριον ο εγω πινω πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε[10:39]{.aside}

το δε καθισαι εκ δεξιων μου και εξ ευωνυμων ουκ εστιν εμον δουναι αλλ οις ητοιμασται[10:40]{.aside}

και ακουσαντες οι δεκα ηρξαντο αγανακτειν περι ιακωβου και [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added}[10:41]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος [αυτους]{.greek-omitted} λεγει αυτοις οιδατε οτι οι δοκουντες αρχειν των εθνων κατακυριευουσιν αυτων και οι μεγαλοι [αυτων]{.greek-omitted} κατεξουσιαζουσιν αυτων[10:42]{.aside}

ουχ ουτως [δε]{.greek-omitted} εσται εν υμιν αλλ ος εαν θελη [γενεσθαι]{.greek-omitted} μεγας εν [υμιν]{.greek-omitted} [υμων]{.greek-added} [εσται]{.greek-omitted} [γενεσθαι]{.greek-added} [εστω]{.greek-added} υμων διακονος[10:43]{.aside}

και ος εαν θελη [υμων]{.greek-omitted} [υμιν]{.greek-added} [γενεσθαι]{.greek-omitted} [ειναι]{.greek-added} πρωτος εσται παντων [δ]{.unclear}ουλος[10:44]{.aside}

και γαρ ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[10:45]{.aside}

και ερχονται εις ιεριχω και εκπορευομενου αυτου απο ιεριχω και των μαθητων αυτου και οχλου ικανου [ο]{.greek-added} [υιος]{.greek-abbr} τιμαιου βαρτιμαιος [ο]{.greek-omitted} τυφλος εκαθητο παρα την οδον προσαιτων[10:46]{.aside}

και ακουσας οτι [ιησους]{.greek-abbr} ο ναζωραιος [εστιν]{.greek-omitted} [φησιν]{.greek-added} ηρξατο κραζειν [λεγων]{.greek-added} [και]{.greek-omitted} [λεγειν]{.greek-omitted} [ο]{.greek-omitted} [υιος]{.greek-abbr} [δαυιδ]{.greek-abbr} [ιησου]{.greek-omitted} ελεησον με[10:47]{.aside}

και [στας]{.greek-omitted} [σταθεις]{.greek-added} ο [ιησους]{.greek-abbr} [ειπεν]{.greek-omitted} [ειπε]{.greek-added} [προς]{.greek-added} αυτον φωνηθηναι και [φωνουσιν]{.greek-omitted} [φωνουσι]{.greek-added} τον τυφλον λεγοντες αυτω θαρσει εγειραι φωνει σε[10:49]{.aside}

ο δε αποβαλων το ιματιον αυτου αναστας [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} προς τον [ιησουν]{.greek-abbr}[10:50]{.aside}

και αποκριθεις λεγει αυτω ο [ιησους]{.greek-abbr} τι θελεις ποιησω σοι ο δε τυφλος ειπεν αυτω [ραββουνι]{.greek-omitted} [ραβουνι]{.greek-added} ινα αναβλεψω[10:51]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αυτω υπαγε η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε και ευθεως [ανεβλεψεν]{.greek-omitted} [ανεβλεψε]{.greek-added} και ηκολουθει [αυτω]{.greek-added} [τω]{.greek-omitted} [ιησου]{.greek-omitted} εν τη οδω[10:52]{.aside}

### Chapter 11

και οτε εγγιζουσιν εις [ιερουσαλημ]{.greek-omitted} [ιεροσολυμα]{.greek-added} εις βηθσφαγη και βηθανιαν προς το ορος των ελαιων αποστελλει δυο των μαθητων αυτου[11:1]{.aside}

[λεγων]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} υπαγετε εις την κωμην την κατεναντι υμων και ευθεως εισπορευομενοι εις αυτην ευρησετε πωλον δεδεμενον εφ ον ουδεις [ανθρωπων]{.greek-abbr} [κεκαθικεν]{.greek-omitted} [κεκαθικε]{.greek-added} λυσαντες αυτον [α]{.greek-added} [αγαγετε]{.greek-omitted} [γαγετε]{.greek-added}[11:2]{.aside}

και εαν τις υμιν ειπη τι [ποιειτε]{.greek-omitted} [τουτο]{.greek-omitted} ειπατε οτι ο [κυριος]{.greek-abbr} αυτου χρειαν εχει και ευθεως αυτον αποστελλει ωδε[11:3]{.aside}

απηλθον [δε]{.greek-omitted} [ουν]{.greek-added} και ευρον πωλον δεδεμενον προς την θυραν εξω επι του αμφοδου και λυουσιν αυτον[11:4]{.aside}

[και]{.greek-omitted} τινες [δε]{.greek-added} των εκει [εστηκοτων]{.greek-omitted} [εστωτων]{.greek-added} ελεγον αυτοις τι ποιειτε λυοντες τον πωλον[11:5]{.aside}

οι δε ειπον αυτοις καθως [ενετειλατο]{.greek-omitted} [ειπεν]{.greek-added} [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} και αφηκαν αυτους[11:6]{.aside}

και [ηγαγον]{.greek-omitted} [αγουσι]{.greek-added} τ[ον]{.unclear} πωλον προς τον [ιησουν]{.greek-abbr} και [επεβαλον]{.greek-omitted} [επιβαλλουσιν]{.greek-added} αυτω τα ιματια αυτων και εκαθισεν επ αυτω[11:7]{.aside}

πολλοι δε τα ιματια αυτων [εστρωσαν]{.greek-omitted} [εστρωννυον]{.greek-added} εις την οδον αλλοι δε [στοιβαδας]{.greek-omitted} [στιβαδας]{.greek-added} εκοπτον εκ των δενδρων και εστρωννυον [εις]{.greek-omitted} [εν]{.greek-added} [την]{.greek-omitted} [τη]{.greek-added} [οδον]{.greek-omitted} [οδω]{.greek-added}[11:8]{.aside}

και οι προαγοντες και οι ακολουθουντες εκραζον λεγοντες ωσαννα ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr}[11:9]{.aside}

ευλογημενη η ερχομενη βασιλεια [εν]{.greek-omitted} [ονοματι]{.greek-omitted} [κυριου]{.greek-omitted} του [πατρος]{.greek-abbr} ημων [δαυιδ]{.greek-abbr} ωσαννα εν τοις υψιστοις[11:10]{.aside}

και εισηλθεν εις ιεροσολυμα [ο]{.greek-omitted} [ιησους]{.greek-omitted} [και]{.greek-omitted} εις το ιερον και [περι]{.greek-added} [περιβλεψαμενος]{.greek-omitted} [βλεψαμενος]{.greek-added} παντα οψιας ηδη ουσης της ωρας εξηλθεν εις βηθανιαν μετα των δωδεκα[11:11]{.aside}

και τη επαυριον εξελθοντων [αυτων]{.greek-omitted} απο βηθανιας επεινασεν[11:12]{.aside}

και ιδων συκην [απο]{.greek-added} μακροθεν εχουσαν φυλλα ηλθεν ει αρα [τι]{.greek-added} ευρησει [τι]{.greek-omitted} εν αυτη και ελθων επ αυτην ουδεν ευρεν ει μη φυλλα [μονον]{.greek-added} ου γαρ ην [ο]{.greek-added} καιρος συκων[11:13]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτη μηκετι [εκ]{.greek-omitted} [σου]{.greek-omitted} εις τον αιωνα [εκ]{.greek-added} [σου]{.greek-added} μηδεις καρπον φαγοι και ηκουον οι μαθηται αυτου[11:14]{.aside}

και ερχονται εις ιεροσολυμα και εισελθων ο [ιησους]{.greek-abbr} εις το ιερον ηρξατο εκβαλλειν τους πωλουντας και αγοραζοντας εν τω ιερω και τας τραπεζας των κολλυβιστων [κατεστρεψε]{.greek-added} και τας καθεδρας των πωλουντων τας περιστερας [κατεστρεψεν]{.greek-omitted}[11:15]{.aside}

και ουκ ηφιεν ινα τις διενεγκη σκευος δια του ιερου[11:16]{.aside}

και [εδιδασκεν]{.greek-omitted} [εδιδασκε]{.greek-added} λεγων [αυτοις]{.greek-omitted} [ου]{.greek-omitted} γεγραπται [οτι]{.greek-omitted} ο οικος μου οικος προσευχης κληθησεται [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εθνεσιν υμεις δε εποιησατε αυτον σπηλαιον ληστων[11:17]{.aside}

και ηκουσαν οι [γραμματεις]{.greek-omitted} [αρχιερεις]{.greek-added} και οι [αρχιερεις]{.greek-omitted} [γραμματεις]{.greek-added} και εζητουν πως αυτον απολεσωσιν εφοβουντο γαρ αυτον οτι πας ο [οχλος]{.greek-omitted} [λαος]{.greek-added} [εξεπλησσετο]{.greek-omitted} [εξεπλησσοντο]{.greek-added} επι τη διδαχη αυτου[11:18]{.aside}

και οτε οψε εγενετο [εξεπορευετο]{.greek-omitted} εξω της πολεως [εξεπορευετο]{.greek-added}[11:19]{.aside}

και [παραπορευομενοι]{.greek-added} πρωι [παραπορευομενοι]{.greek-omitted} ειδον την συκην εξηραμμενην εκ ριζων[11:20]{.aside}

και αναμνησθεις ο πετρος λεγει αυτω ραββι ιδε η συκη η[ν]{.unclear} κατηρασω [εξηρανται]{.greek-omitted} [εξηραται]{.greek-added}[11:21]{.aside}

και αποκριθεις [ο]{.greek-omitted} [ιησους]{.greek-abbr} λεγει [αυ]{.unclear}τοις εχετε πιστιν [θεου]{.greek-abbr}[11:22]{.aside}

αμην γαρ λεγω υμ[ι]{.unclear}ν οτι ος αν ειπη τω ορ[ει]{.unclear} τουτ[ω]{.unclear} [αρθητι]{.greek-omitted} [αρθ[ηναι]{.unclear}]{.greek-added} και [βληθητι]{.greek-omitted} [βληθηναι]{.greek-added} εις την θαλασσαν και μη διακριθη [εν]{.unclear} τ[η]{.unclear} καρδια αυτου αλλα [πιστευση]{.greek-omitted} [[πισ]{.unclear}τευ[ει]{.unclear}]{.greek-added} οτι [α]{.greek-omitted} [[ο]{.greek-supplied}]{.greek-added} λεγει γινεται εσται αυτω [ο]{.greek-omitted} [εαν]{.greek-omitted} [ειπη]{.greek-omitted}[11:23]{.aside}

δια τουτ[ο]{.unclear} λεγ[ω]{.unclear} [υ]{.greek-supplied}μιν παν[τα]{.greek-supplied} οσα [αν]{.unclear} προσευχομενοι [αιτησθε]{.greek-omitted} [αιτ[ε]{.unclear}ισθε]{.greek-added} πιστευ[ε]{.unclear}τ[ε]{.unclear} οτι λαμβανετε και εσται υμιν[11:24]{.aside}

και οταν [στηκητε]{.greek-omitted} [στηκετε]{.greek-added} προσευχομενοι αφιετε ει τι εχετε κατα τινος ινα και ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} αφη υμιν τα παραπτωματα υμων[11:25]{.aside}

ει δε υμεις ουκ αφιετε ουδε ο [πατηρ]{.greek-abbr} υμων ο [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted} [[ουρανιος]{.greek-abbr}]{.greek-added} [αφη]{.greek-added} [υμιν]{.greek-added} [τα]{.greek-added} [παρα]{.greek-added} [πτωματα]{.greek-added} [υμων]{.greek-added} [ει]{.greek-added} [δε]{.greek-added} [υμεις]{.greek-added} [ουκ]{.greek-added} [αφιετε]{.greek-added} [ουδε]{.greek-added} [ο]{.greek-added} [[πατηρ]{.greek-abbr}]{.greek-added} [υμων]{.greek-added} [ο]{.greek-added} [[ουρανιος]{.greek-abbr}]{.greek-added} αφησει τα παραπτωματα υμων[11:26]{.aside}

και ερχονται παλιν εις ιεροσολυμα και εν τω ιερω περιπατουντος αυτου ερχονται προς αυτον οι αρχιερεις και οι γραμματεις και οι πρεσβυτεροι[11:27]{.aside}

και [λεγουσιν]{.greek-omitted} [ελεγον]{.greek-added} αυτω εν ποια εξουσια ταυτα ποιεις και τις σοι [δεδωκε]{.greek-added} την εξουσιαν ταυτην [εδωκεν]{.greek-omitted} [ινα]{.greek-omitted} [ταυτα]{.greek-omitted} [ποιης]{.greek-omitted}[11:28]{.aside}

ο δε [ιησους]{.greek-abbr} αποκριθεις ειπεν αυτοις επερωτησω υμας [καγω]{.greek-added} [και]{.greek-omitted} [εγω]{.greek-omitted} [ενα]{.greek-omitted} λογον [και]{.greek-omitted} αποκριθητε μοι και ερω υμιν εν ποια εξουσια ταυτα ποιω[11:29]{.aside}

το βαπτισμα [ιωαννου]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} εξ [ουρανου]{.greek-abbr} ην η εξ [ανθρωπων]{.greek-abbr} αποκριθητε μοι[11:30]{.aside}

και [ελογιζοντο]{.greek-omitted} [διελογιζοντο]{.greek-added} προς εαυτους λεγοντες εαν ειπωμεν εξ [ουρανου]{.greek-abbr} ερει [[η]{.unclear}μιν]{.greek-added} δια τι ουν ουκ επιστευσατε αυτω[11:31]{.aside}

αλλ [εαν]{.greek-added} ειπωμεν εξ [ανθρωπων]{.greek-abbr} [εφοβουντο]{.greek-omitted} [φοβουμεθα]{.greek-added} τον λαον [απαντες]{.greek-omitted} [παντες]{.greek-added} γαρ [ειχον]{.greek-omitted} [ηδεισαν]{.greek-added} τον [ιωαννην]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} οτι [οντως]{.greek-omitted} προφητης ην[11:32]{.aside}

και αποκριθεντες [λεγουσιν]{.greek-omitted} τω [ιησου]{.greek-abbr} [λεγουσιν]{.greek-added} ουκ οιδαμεν και ο [ιησους]{.greek-abbr} αποκριθεις λεγει αυτοις ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[11:33]{.aside}

### Chapter 12

και ηρξατο αυτοις εν παραβολαις [λεγειν]{.greek-omitted} [λαλειν]{.greek-added} [[ανθρωπος]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εφυτευσεν]{.greek-added} αμπελωνα [εφυτευσεν]{.greek-omitted} [ανθρωπος]{.greek-omitted} και [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} φραγμον και ωρυξεν υποληνιον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και [εξεδοτο]{.greek-omitted} [εξεδετο]{.greek-added} αυτον γεωργοις και [απεδημησεν]{.greek-omitted} [απεδημησε]{.greek-added}[12:1]{.aside}

και [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς τους γεωργους τω καιρω δουλον ινα παρα των γεωργων λαβη απο του καρπου του αμπελωνος[12:2]{.aside}

οι δε λαβοντες αυτον εδειραν και απεστειλαν κενον[12:3]{.aside}

και παλιν [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} προς αυτους αλλον δουλον κακεινον λιθοβολησαντες εκεφαλαιωσαν και απεστειλαν ητιμωμενον[12:4]{.aside}

και παλιν αλλον [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} κακεινον απεκτειναν και πολλους αλλους τους μεν [δεροντες]{.greek-omitted} [δαιροντες]{.greek-added} [τους]{.greek-omitted} [ους]{.greek-added} δε αποκτενοντες[12:5]{.aside}

[υστερον]{.greek-added} [δε]{.greek-added} ετι [ουν]{.greek-omitted} ενα [υιον]{.greek-abbr} εχων [τον]{.greek-added} αγαπητον αυτου [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} [και]{.greek-omitted} [προς]{.greek-added} αυτον [προς]{.greek-omitted} [αυτους]{.greek-omitted} εσχατον λεγων οτι εντραπησονται τον [υιον]{.greek-abbr} μου[12:6]{.aside}

εκεινοι δε οι γεωργοι [ειπον]{.greek-omitted} [θεασαμενοι]{.greek-added} [αυτον]{.greek-added} [ερχομενον]{.greek-added} προς εαυτους [οτι]{.greek-omitted} [ειπον]{.greek-added} ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και ημων εσται η κληρονομια[12:7]{.aside}

και λαβοντες αυτον απεκτειναν και εξεβαλον εξω του αμπελωνος[12:8]{.aside}

τι ουν ποιησει ο κυριος του αμπελωνος ελευσεται και απολεσει τους γεωργους και δωσει τον αμπελωνα αλλοις[12:9]{.aside}

ουδε την γραφην ταυτην ανεγνωτε λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος [εγενηθη]{.greek-omitted} [εγεννηθη]{.greek-added} εις κεφαλην γωνιας[12:10]{.aside}

παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[12:11]{.aside}

και εζητουν αυτον κρατησαι και εφοβηθησαν τον οχλον εγνωσαν γαρ οτι προς αυτους την παραβολην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} και αφεντες αυτον απηλθον[12:12]{.aside}

και [αποστελλουσιν]{.greek-omitted} [αποστελλουσι]{.greek-added} προς [αυτον]{.greek-omitted} [αυτους]{.greek-added} τινας των [φαρισαιων]{.greek-omitted} [φαρισσαιων]{.greek-added} και των ηρωδιανων ινα αυτον [αγρευσωσιν]{.greek-omitted} [αγρευσωσι]{.greek-added} λογω[12:13]{.aside}

οι δε ελθοντες [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [ηρξαντο]{.greek-added} [επερωταν]{.greek-added} [αυτον]{.greek-added} [εν]{.greek-added} [λογω]{.greek-added} διδασκαλε οιδαμεν οτι αληθης ει και [την]{.greek-added} [οδον]{.greek-added} [του]{.greek-added} [[θεου]{.greek-abbr}]{.greek-added} [εν]{.greek-added} [αληθεια]{.greek-added} [διδασκεις]{.greek-added} [και]{.greek-added} ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added} [αλλ]{.greek-omitted} [επ]{.greek-omitted} [αληθειας]{.greek-omitted} [την]{.greek-omitted} [οδον]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [διδασκεις]{.greek-omitted} [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [κηνσον]{.greek-omitted} [κινσον]{.greek-added} [καισαρι]{.greek-omitted} [καισσαρι]{.greek-added} δουναι η ου [δωμεν]{.greek-added} [η]{.greek-added} [μη]{.greek-added} [δωμεν]{.greek-added}[12:14]{.aside}

[δωμεν]{.greek-omitted} [η]{.greek-omitted} [μη]{.greek-omitted} [δωμεν]{.greek-omitted} ο δε ειδως αυτων την υποκρισιν ειπεν αυτοις τι με πειραζετε [υποκριται]{.greek-added} φερετε μοι δηναριον ινα ιδω[12:15]{.aside}

οι δε ηνεγκαν και λεγει αυτοις τινος η εικων αυτη και η επιγραφη οι δε ειπον [αυτω]{.greek-omitted} [καισαρος]{.greek-omitted} [καισσαρος]{.greek-added}[12:16]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις αποδοτε τα [καισαρος]{.greek-omitted} [καισσαρος]{.greek-added} [καισαρι]{.greek-omitted} [καισσαρι]{.greek-added} και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr} και εθαυμασαν επ αυτω[12:17]{.aside}

και ερχονται [σαδδουκαιοι]{.greek-omitted} [σαδουκκαιοι]{.greek-added} προς αυτον οιτινες [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} [αναστασιν]{.greek-omitted} μη ειναι [αναστασιν]{.greek-added} και επηρωτησαν αυτον λεγοντες[12:18]{.aside}

διδασκαλε [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εγραψεν ημιν [οτι]{.greek-omitted} εαν τινος αδελφος αποθανη και [καταλιπη]{.greek-omitted} [σχη]{.greek-added} γυναικα και [τεκνα]{.greek-omitted} [τεκνον]{.greek-added} μη αφη ινα λαβη ο αδελφος [αυτου]{.greek-omitted} την γυναικα [αυτου]{.greek-omitted} και εξαναστηση σπερμα τω αδελφω αυτου[12:19]{.aside}

επτα [ησαν]{.greek-added} αδελφοι [ησαν]{.greek-omitted} [παρ]{.greek-added} [ημιν]{.greek-added} και ο πρωτος [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added} γυναικα και [αποθνησκων]{.greek-omitted} [απεθανε]{.greek-added} [και]{.greek-added} ουκ [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα[12:20]{.aside}

και ο δευτερος ελαβεν αυτην και [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και ουδε αυτος [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} σπερμα και ο τριτος ωσαυτως[12:21]{.aside}

και ελαβον αυτην οι επτα και ουκ αφηκαν σπερμα [εσχατη]{.greek-omitted} [εσχατον]{.greek-added} [δε]{.greek-added} παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[12:22]{.aside}

εν τη αναστασει [ουν]{.greek-added} οταν [αναστωσιν]{.greek-omitted} [αναστωσι]{.greek-added} τινος αυτων εσται γυνη οι γαρ επτα εσχον αυτην γυναικα[12:23]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ου δια τουτο πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[12:24]{.aside}

οταν γαρ εκ νεκρων αναστωσιν ουτε γαμουσιν ουτε [γαμισκονται]{.greek-omitted} [γαμιζονται]{.greek-added} αλλ εισιν ως αγγελοι [οι]{.greek-omitted} εν τοις [ουρανοις]{.greek-abbr}[12:25]{.aside}

περι δε των νεκρων οτι εγειρονται ουκ ανεγνωτε εν τη βιβλω [μωσεως]{.greek-omitted} [μωυσεος]{.greek-added} επι [του]{.greek-omitted} [της]{.greek-added} βατου ως ειπεν [αυτω]{.greek-omitted} ο [θεος]{.greek-abbr} λεγων εγω ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ[12:26]{.aside}

ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} [θεος]{.greek-abbr} νεκρων αλλα [θεος]{.greek-omitted} ζωντων υμεις ουν [πολυ]{.greek-omitted} [πολλοι]{.greek-added} πλανασθε[12:27]{.aside}

και προσελθων εις των γραμματεων [ακουσας]{.greek-omitted} [ακουων]{.greek-added} αυτων συζητουντων [ειδως]{.greek-omitted} [ιδων]{.greek-added} οτι καλως [απεκριθη]{.greek-added} αυτοις [απεκριθη]{.greek-omitted} επηρωτησεν αυτον ποια [εστιν]{.greek-omitted} [εστι]{.greek-added} πρωτη [παντων]{.greek-omitted} εντολη[12:28]{.aside}

ο δε [ιησους]{.greek-abbr} [απεκριθη]{.greek-omitted} [ειπεν]{.greek-added} αυτω [οτι]{.greek-omitted} πρωτη παντων [των]{.greek-omitted} [εντολων]{.greek-omitted} [ακουε]{.greek-omitted} [ακουει]{.greek-added} [ισραηλ]{.greek-abbr} [κυριος]{.greek-abbr} ο [θεος]{.greek-abbr} ημων [κυριος]{.greek-abbr} εις [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:29]{.aside}

και αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εξ ολης της καρδιας σου και εξ ολης της ψυχης σου και εξ ολης της διανοιας σου και εξ ολης της ισχυος σου αυτη πρωτη εντολη[12:30]{.aside}

[και]{.greek-omitted} δευτερα [δε]{.greek-added} ομοια αυτη αγαπησεις τον πλησιον σου ως [σεαυτον]{.greek-omitted} [εαυτον]{.greek-added} μειζων τουτων αλλη εντολη ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added}[12:31]{.aside}

και ειπεν αυτω ο γραμματευς καλως διδασκαλε επ αληθειας ειπας οτι εις εστιν [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} και ουκ εστιν αλλος πλην αυτου[12:32]{.aside}

και το αγαπαν αυτον εξ ολης της καρδιας και εξ ολης της [συνεσεως]{.greek-omitted} [ισχυος]{.greek-added} και εξ ολης της [συνεσεως]{.greek-added} [ψυχης]{.greek-omitted} [και]{.greek-omitted} [εξ]{.greek-omitted} [ολης]{.greek-omitted} [της]{.greek-omitted} [ισχυος]{.greek-omitted} και το αγαπαν τον πλησιον ως εαυτον πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} παντων των ολοκαυτωματων και θυσιων[12:33]{.aside}

και ο [ιησους]{.greek-abbr} ιδων [αυτον]{.greek-omitted} οτι νουνεχως απεκριθη ειπεν αυτω ου μακραν ει απο της βασιλειας του [θεου]{.greek-abbr} και ουδεις ουκετι ετολμα αυτον [επερωτησαι]{.greek-omitted} [επερωταν]{.greek-added}[12:34]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} [ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} διδασκων εν τω ιερω πως λεγουσιν οι γραμματεις οτι ο [χριστος]{.greek-abbr} [υιος]{.greek-abbr} [εστιν]{.greek-omitted} [εστι]{.greek-added} [του]{.greek-added} [δαυιδ]{.greek-abbr}[12:35]{.aside}

αυτος γαρ [ο]{.greek-added} [δαυιδ]{.greek-abbr} ειπεν εν [πνευματι]{.greek-abbr} αγιω [λεγει]{.greek-omitted} [ειπεν]{.greek-added} ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου [υποποδιον]{.greek-omitted} [υποκατω]{.greek-added} των ποδων σου[12:36]{.aside}

αυτος ουν [δαυιδ]{.greek-abbr} λεγει αυτον [κυριον]{.greek-abbr} και [ποθεν]{.greek-omitted} [πως]{.greek-added} [υιος]{.greek-abbr} αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added} και [ο]{.greek-omitted} πολυς οχλος ηκουεν αυτου ηδεως[12:37]{.aside}

και ελεγεν [αυτοις]{.greek-omitted} εν τη διδαχη αυτου βλεπετε απο των γραμματεων των θελοντων εν στολαις περιπατειν και ασπασμους εν ταις αγοραις[12:38]{.aside}

και πρωτοκαθεδριας εν ταις συναγωγαις και [πρωτοκλισιας]{.greek-omitted} [πρωτοκλησιας]{.greek-added} εν τοις δειπνοις[12:39]{.aside}

οι κατεσθιοντες τας οικιας των χηρων και προφασει μακρα προσευχομενοι ουτοι [ληψονται]{.greek-omitted} [λημψονται]{.greek-added} περισσοτερον κριμα[12:40]{.aside}

και [καθισας]{.greek-omitted} [εστως]{.greek-added} ο [ιησους]{.greek-abbr} κατεναντι του γαζοφυλακιου εθεωρει πως ο οχλος βαλλει [τον]{.greek-added} χαλκον εις το γαζοφυλακιον και πολλοι πλουσιοι εβαλλον πολλα[12:41]{.aside}

και ελθουσα μια χηρα πτωχη [εβαλεν]{.greek-omitted} [εβαλε]{.greek-added} λεπτα δυο ο [εστιν]{.greek-omitted} [εστι]{.greek-added} κοδραντης[12:42]{.aside}

και προσκαλεσαμενος τους μαθητας αυτου [λεγει]{.greek-omitted} [ελεγεν]{.greek-added} αυτοις αμην λεγω υμιν οτι η χηρα αυτη η πτωχη πλειον παντων [βεβληκεν]{.greek-omitted} [βεβληκε]{.greek-added} των [βαλλοντων]{.greek-omitted} [βαλοντων]{.greek-added} εις το γαζοφυλακιον[12:43]{.aside}

παντες γαρ εκ του [περισσευοντος]{.greek-omitted} [περισσευματου]{.greek-added} αυτοις εβαλον αυτη δε εκ της υστερησεως αυτης παντα οσα ειχεν εβαλεν ολον τον βιον αυτης[12:44]{.aside}

### Chapter 13

και εκπορευομενου αυτου εκ του ιερου λεγει αυτω εις [εκ]{.greek-added} των μαθητων αυτου διδασκαλε ιδε ποταποι λιθοι και ποταπαι οικοδομαι[13:1]{.aside}

και [ο]{.greek-omitted} [ιησους]{.greek-omitted} αποκριθεις ειπεν αυτω [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} βλεπεις ταυτας τας μεγαλας οικοδομας ου μη αφεθη λιθος επι [λιθω]{.greek-omitted} [λιθον]{.greek-added} ος ου μη καταλυθη[13:2]{.aside}

και καθημενου αυτου εις το ορος των ελαιων κατεναντι του ιερου επηρωτων αυτον κατ ιδιαν πετρος και ιακωβος και [ιωαννης]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} και ανδρεας[13:3]{.aside}

ειπε ημιν ποτε ταυτα εσται και τι το σημειον [οταν]{.greek-omitted} [της]{.greek-added} μελλη [ταυτα]{.greek-added} παντα [ταυτα]{.greek-omitted} [συντελεισθαι]{.greek-omitted} [συντελεσθηναι]{.greek-added}[13:4]{.aside}

[και]{.greek-added} [αποκριθεις]{.greek-added} ο [δε]{.greek-omitted} [ιησους]{.greek-abbr} [αποκριθεις]{.greek-omitted} [ειπεν]{.greek-added} αυτοις [ηρξατο]{.greek-omitted} [λεγειν]{.greek-omitted} βλεπετε μη τις υμας πλανηση[13:5]{.aside}

πολλοι γαρ ελευσονται επι τω ονοματι μου λεγοντες οτι εγω ειμι [ο]{.greek-added} [[χριστος]{.greek-abbr}]{.greek-added} και πολλους πλανησουσιν[13:6]{.aside}

οταν δε [ακουσητε]{.greek-omitted} [ακουητε]{.greek-added} [πολεμους]{.greek-omitted} [και]{.greek-omitted} ακοας πολεμων [και]{.greek-added} [πολεμους]{.greek-added} μη [θροεισθε]{.greek-omitted} [θροησθε]{.greek-added} δει γαρ γενεσθαι αλλ ουπω το τελος[13:7]{.aside}

εγερθησεται γαρ εθνος επι εθνος και βασιλεια επι βασιλειαν και εσονται σεισμοι κατα τοπους και εσονται λιμοι και [ταραχαι]{.greek-omitted} [αρχαι]{.greek-omitted} [λοιμοι]{.greek-added} [ταυτα]{.greek-added} [δε]{.greek-added} [παντα]{.greek-added} [αρχη]{.greek-added} ωδινων [ταυτα]{.greek-omitted}[13:8]{.aside}

βλεπετε δε υμεις εαυτους [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ υμας εις συνεδρια και εις συναγωγας δαρησεσθε και επι ηγεμονων και βασιλεων σταθησεσθε ενεκεν εμου εις μαρτυριον αυτοις[13:9]{.aside}

και εις παντα τα εθνη δει πρωτον κηρυχθηναι το ευαγγελιον[13:10]{.aside}

οταν δε [αγαγωσιν]{.greek-omitted} [αγωσιν]{.greek-added} υμας παραδιδοντες μη προμεριμνατε τι [λα]{.greek-added} [λεσετε]{.greek-added} [λαλησητε]{.greek-omitted} [μηδε]{.greek-omitted} [μελετατε]{.greek-omitted} αλλ ο [εαν]{.greek-omitted} [αν]{.greek-added} δοθη υμιν εν εκεινη τη ωρα [τουτο]{.greek-omitted} [εκεινο]{.greek-added} λαλειτε ου γαρ εστε υμεις οι λαλουντες αλλα το [πνευμα]{.greek-abbr} το αγιον[13:11]{.aside}

[παραδωσει]{.greek-omitted} [παραδωσουσι]{.greek-added} δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και επαναστησονται τεκνα επι γονεις και θανατωσουσιν αυτους[13:12]{.aside}

και εσεσθε μισουμενοι υπο παντων δια το ονομα μου ο δε υπομεινας εις τελος ουτος σωθησεται[13:13]{.aside}

οταν δε ιδητε το βδελυγμα της ερημωσεως [στηκο[ν]{.unclear}]{.greek-added} [το]{.greek-omitted} [ρηθεν]{.greek-omitted} [υπο]{.greek-omitted} [δανιηλ]{.greek-omitted} [του]{.greek-omitted} [προφητου]{.greek-omitted} [εστως]{.greek-omitted} οπου ου δει ο αναγινωσκων νοειτω τοτε οι εν τη ιουδαια φευγετωσαν εις τα ορη[13:14]{.aside}

ο [δε]{.greek-omitted} επι του δωματος μη καταβατω εις την οικιαν μηδε εισελθετω αραι [τι]{.greek-omitted} εκ της οικιας αυτου[13:15]{.aside}

και ο εις τον αγρον ων μη επιστρεψατω εις τα οπισω αραι το ιματιον αυτου[13:16]{.aside}

ουαι δε ταις εν γαστρι εχουσαις και ταις θηλαζουσαις εν εκειναις ταις ημεραις[13:17]{.aside}

προσευχεσθε δε ινα μη γενηται η φυγη [υμων]{.greek-omitted} [ημων]{.greek-added} χειμωνος [μηδε]{.greek-added} [εν]{.greek-added} [σαββατω]{.greek-added}[13:18]{.aside}

εσονται [γαρ]{.greek-omitted} [δε]{.greek-added} αι ημεραι εκειναι θλιψις οια ου [γεγονεν]{.greek-omitted} [γεγονε]{.greek-added} τοιαυτη απ αρχης κτισεως ης εκτισεν ο [θεος]{.greek-abbr} εως του νυν [και]{.greek-omitted} [ουδ]{.greek-added} ου μη γενηται[13:19]{.aside}

και ει μη [κυριος]{.greek-omitted} [ο]{.greek-added} [[θεος]{.greek-abbr}]{.greek-added} [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας [εκεινας]{.greek-added} ουκ αν εσωθη πασα σαρξ [αλλα]{.greek-omitted} δια [δε]{.greek-added} τους εκλεκτους ους εξελεξατο [εκολοβωσεν]{.greek-omitted} [εκολοβωσε]{.greek-added} τας ημερας[13:20]{.aside}

τοτε εαν τις [υμιν]{.greek-omitted} [υμων]{.greek-added} ειπη ιδου ωδε ο [χριστος]{.greek-abbr} [η]{.greek-omitted} ιδου εκει μη [πιστευετε]{.greek-omitted} [πιστευσητε]{.greek-added}[13:21]{.aside}

εγερθησονται γαρ ψευδοχριστοι και ψευδοπροφηται και [δωσουσιν]{.greek-omitted} [δωσουσι]{.greek-added} σημεια και τερατα προς το αποπλαναν ει δυνατον και τους εκλεκτους[13:22]{.aside}

υμεις δε βλεπετε ιδου προειρηκα υμιν παντα[13:23]{.aside}

αλλ [εν]{.greek-omitted} εκειναις ταις ημεραις μετα την θλιψιν εκεινην ο ηλιος σκοτισθησεται και η σεληνη ου δωσει το φεγγος αυτης[13:24]{.aside}

και οι αστερες [εκ]{.greek-added} του [ουρανου]{.greek-abbr} εσονται εκπιπτοντες και αι δυναμεις αι εν τοις [ουρανοις]{.greek-abbr} σαλευθησονται[13:25]{.aside}

και τοτε οψονται τον [υιον]{.greek-abbr} του [ανθρωπου]{.greek-abbr} ερχομενον εν [νεφελαις]{.greek-omitted} [νεφελη]{.greek-added} μετα δυναμεως [πολλης]{.greek-omitted} και δοξης [πολλης]{.greek-added}[13:26]{.aside}

και τοτε [αποστελει]{.greek-omitted} [αποστελλει]{.greek-added} τους αγγελους αυτου και επισυναξει τους εκλεκτους αυτου εκ των τεσσαρων ανεμων απ [ακρου]{.greek-omitted} [ακ[ρ]{.unclear}ων]{.greek-added} [της]{.greek-added} γης εως ακρου [ουρανου]{.greek-abbr}[13:27]{.aside}

απο δε της συκης μαθετε την παραβολην οταν [αυτης]{.greek-omitted} ηδη ο κλαδος [αυτης]{.greek-added} απαλος γενηται και εκφυη [τα]{.greek-omitted} φυλλα γινωσκετε οτι εγγυς το θερος εστιν[13:28]{.aside}

ουτως και υμεις οταν [ιδητε]{.greek-added} ταυτα [ιδητε]{.greek-omitted} [παντα]{.greek-added} γινομενα γινωσκετε οτι εγγυς εστιν επι θυραις[13:29]{.aside}

αμην λεγω υμιν οτι ου μη παρελθη η γενεα αυτη [μεχρι]{.greek-omitted} [ου]{.greek-omitted} [εως]{.greek-added} [αν]{.greek-added} παντα [ταυτα]{.greek-omitted} γενηται[13:30]{.aside}

ο [ουρανος]{.greek-abbr} και η γη [παρελευσεται]{.greek-omitted} [παρελευσονται]{.greek-added} οι δε λογοι μου ου μη [παρελθωσιν]{.greek-omitted} [παρελθωσι]{.greek-added}[13:31]{.aside}

περι δε της ημερας εκεινης [η]{.greek-omitted} [και]{.greek-added} [της]{.greek-added} ωρας ουδεις οιδεν ουδε οι αγγελοι [οι]{.greek-omitted} εν [ουρανω]{.greek-abbr} ουδε ο [υιος]{.greek-abbr} ει μη ο [πατηρ]{.greek-abbr}[13:32]{.aside}

βλεπετε αγρυπνειτε και προσευχεσθε ουκ οιδατε γαρ ποτε ο καιρος εστιν[13:33]{.aside}

[ως]{.greek-omitted} [ωσπερ]{.greek-added} [γαρ]{.greek-added} [ανθρωπος]{.greek-abbr} [αποδημος]{.greek-omitted} [αποδημων]{.greek-added} αφεις την οικιαν αυτου και δους τοις δουλοις αυτου την εξουσιαν και εκαστω το εργον αυτου και τω θυρωρω ενετειλατο [ινα]{.greek-omitted} [γρηγορη]{.greek-omitted} [γρηγορειν]{.greek-added}[13:34]{.aside}

γρηγορειτε ουν ουκ οιδατε γαρ ποτε ο κυριος της οικιας ερχεται οψε [η]{.unclear} [μεσονυκτιου]{.greek-omitted} [μεσονυκτιω]{.greek-added} η αλεκτοροφωνιας η πρωι[13:35]{.aside}

μη ελθων εξαιφνης ευρη υμας καθευδοντας[13:36]{.aside}

α δε [λεγω]{.greek-added} υμιν [λεγω]{.greek-omitted} [πασιν]{.greek-omitted} [πασι]{.greek-added} λεγω γρηγορειτε[13:37]{.aside}

### Chapter 14

ην δε το πασχα και τα αζυμα μετα δυο ημερας και εζητουν οι αρχιερεις και οι γραμματεις πως αυτον [εν]{.greek-omitted} δολω κρατησαντες αποκτεινωσιν[14:1]{.aside}

ελεγον δε μη εν τη εορτη μηποτε θορυβος εσται [του]{.greek-omitted} [λαου]{.greek-omitted} [τω]{.greek-added} [λαω]{.greek-added}[14:2]{.aside}

και οντος αυτου εν βηθανια εν [τη]{.greek-omitted} [οικια]{.greek-omitted} [οιια]{.greek-added} σιμωνος του λεπρου κατακειμενου αυτου [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γυνη εχουσα αλαβαστρον μυρου ναρδου πιστικης [πολυτελους]{.greek-omitted} [πολυτιμου]{.greek-added} και συντριψασα το αλαβαστρον κατεχεεν αυτου [κατα]{.greek-omitted} της κεφαλης[14:3]{.aside}

ησαν δε τινες αγανακτουντες προς εαυτους [και]{.greek-omitted} [λεγοντες]{.greek-omitted} εις τι η απωλεια αυτη του μυρου γεγονεν[14:4]{.aside}

ηδυνατο γαρ [το]{.greek-added} [μυρον]{.greek-added} τουτο πραθηναι επανω τριακοσιων δηναριων και δοθηναι τοις πτωχοις και [ενεβριμωντο]{.greek-omitted} [ενεβριμησατο]{.greek-added} αυτη[14:5]{.aside}

ο δε [ιησους]{.greek-abbr} ειπεν αφετε αυτην τι αυτη κοπους παρεχετε καλον [γαρ]{.greek-added} εργον [ειργασατο]{.greek-omitted} [ηργασατο]{.greek-added} [εν]{.greek-omitted} [εμοι]{.greek-omitted} [εις]{.greek-added} [εμε]{.greek-added}[14:6]{.aside}

παντοτε γαρ τους πτωχους εχετε μεθ εαυτων [και]{.greek-omitted} [οταν]{.greek-omitted} [θελητε]{.greek-omitted} [δυνασθε]{.greek-omitted} [αυτους]{.greek-omitted} [ευ]{.greek-omitted} [ποιησαι]{.greek-omitted} εμε δε ου παντοτε εχετε[14:7]{.aside}

ο [εσχεν]{.greek-omitted} [ειχεν]{.greek-added} [αυτη]{.greek-omitted} [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [προελαβεν]{.greek-omitted} [προελαβε]{.greek-added} μυρισαι μου το σωμα εις τον ενταφιασμον[14:8]{.aside}

αμην λεγω υμιν οπου εαν κηρυχθη το ευαγγελιον τουτο εις ολον τον κοσμον και ο εποιησεν αυτη λαληθησεται εις μνημοσυνον αυτης[14:9]{.aside}

και [ο]{.greek-omitted} ιουδας ο ισκαριωτης εις [εκ]{.greek-added} των δωδεκα [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added} προς τους αρχιερεις ινα παραδω αυτον [αυτοις]{.greek-omitted}[14:10]{.aside}

οι δε ακουσαντες εχαρησαν και επηγγειλαντο αυτω αργυριον δουναι και εζητει πως ευκαιρως αυτον παραδω[14:11]{.aside}

και τη πρωτη ημερα των αζυμων οτε το πασχα εθυον λεγουσιν αυτω οι μαθηται [αυτου]{.greek-omitted} που θελεις απελθοντες [ετοιμασωμεν]{.greek-omitted} [ετοιμασομεν]{.greek-added} ινα φαγης το πασχα[14:12]{.aside}

και αποστελλει δυο των μαθητων αυτου και λεγει αυτοις υπαγετε εις την πολιν και [εισελθοντων]{.greek-added} [υμων]{.greek-added} [εν]{.greek-added} [τη]{.greek-added} [πολη]{.greek-added} απαντησει υμιν [ανθρωπος]{.greek-abbr} [κεραμιον]{.greek-omitted} [κεραμειον]{.greek-added} υδατος βασταζων ακολουθησατε αυτω[14:13]{.aside}

και οπου [εαν]{.greek-omitted} [αν]{.greek-added} εισελθη ειπατε τω οικοδεσποτη οτι ο διδασκαλος λεγει που [εστιν]{.greek-omitted} [εστι]{.greek-added} το καταλυμα οπου το πασχα μετα των μαθητων μου [φαγω]{.greek-omitted} [φαγομαι]{.greek-added}[14:14]{.aside}

και αυτος υμιν δειξει [ανωγεον]{.greek-omitted} [ανωγεων]{.greek-added} μεγα [εστρωμενον]{.greek-omitted} [εστρωμμενον]{.greek-added} ετοιμον εκει ετοιμασατε ημιν[14:15]{.aside}

και εξηλθον [ετοιμασαι]{.greek-added} [αυτω]{.greek-added} οι μαθηται [αυτου]{.greek-omitted} και ηλθον εις την πολιν και ευρον καθως ειπεν αυτοις και ητοιμασαν το πασχα[14:16]{.aside}

και οψιας [γ]{.unclear}ενομενης ερχεται μετα των δωδεκα[14:17]{.aside}

και ανακειμενων αυτων και εσθιοντων [ειπεν]{.greek-omitted} [λεγει]{.greek-added} [αυτοις]{.greek-added} ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι εις εξ υμων παραδωσει με ο εσθιων μετ εμου[14:18]{.aside}

οι δε ηρξαντο λυπεισθαι και λεγειν αυτω εις καθ εις μητι εγω και αλλος μητι εγω[14:19]{.aside}

ο δε αποκριθεις ειπεν αυτοις εις εκ των δωδεκα ο [εμβαπτομενος]{.greek-omitted} [εμβαψας]{.greek-added} μετ εμου εις το τρυβλιον[14:20]{.aside}

ο μεν υιος του [ανθρωπου]{.greek-abbr} υπαγει καθως γεγραπται περι αυτου ουαι δε τω [ανθρωπω]{.greek-abbr} εκεινω δι ου ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} παραδιδοται καλον ην αυτω ει ουκ εγεννηθη ο [ανθρωπος]{.greek-abbr} εκεινος[14:21]{.aside}

και εσθιοντων αυτων λαβων ο [ιησους]{.greek-abbr} αρτον ευλογησας [εκλασεν]{.greek-omitted} [εκλασε]{.greek-added} και [εδωκεν]{.greek-omitted} [εδιδου]{.greek-added} αυτοις και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} λαβετε φαγετε τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το σωμα μου[14:22]{.aside}

και λαβων [το]{.greek-omitted} ποτηριον ευχαριστησας εδωκεν αυτοις και επιον εξ αυτου παντες[14:23]{.aside}

και ειπεν αυτοις τουτο [εστιν]{.greek-omitted} [εστι]{.greek-added} το αιμα μου το της καινης διαθηκης το περι πολλων εκχυνομενον[14:24]{.aside}

αμην λεγω υμιν οτι ουκετι ου μη πιω εκ του γενηματος της αμπελου εως της ημερας εκεινης οταν αυτο πινω καινον εν τη βασιλεια του [θεου]{.greek-abbr}[14:25]{.aside}

και υμνησαντες εξηλθον εις το ορος των ελαιων[14:26]{.aside}

και λεγει αυτοις ο [ιησους]{.greek-abbr} οτι παντες [υμεις]{.greek-added} σκανδαλισθησεσθε εν εμοι εν τη νυκτι ταυτη [οτι]{.greek-omitted} γεγραπται [γαρ]{.greek-added} παταξω τον ποιμενα και [διασκορπισθησεται]{.greek-omitted} τα προβατα [διασκορπισθησονται]{.greek-added}[14:27]{.aside}

αλλα μετα το εγερθηναι με προαξω υμας εις την γαλιλαιαν[14:28]{.aside}

ο δε πετρος [εφη]{.greek-omitted} [αποκριθεις]{.greek-added} [λεγει]{.greek-added} αυτω [ει]{.greek-added} και [ει]{.greek-omitted} παντες σκανδαλισθησονται αλλ ουκ εγω[14:29]{.aside}

και λεγει αυτω ο [ιησους]{.greek-abbr} αμην λεγω σοι οτι συ σημερον [εν]{.greek-omitted} τη νυκτι ταυτη πριν [η]{.greek-omitted} [αλεκτορα]{.greek-added} δις [αλεκτορα]{.greek-omitted} φωνησαι τρις απαρνηση με[14:30]{.aside}

ο δε [εκπερισσου]{.greek-omitted} [πετρος]{.greek-added} [μαλλον]{.greek-added} [περισσως]{.greek-added} ελεγεν [μαλλον]{.greek-omitted} [οτι]{.greek-added} εαν [δεη]{.greek-added} με [συν]{.greek-added} [δεη]{.greek-omitted} [συναποθανειν]{.greek-omitted} σοι [αποθανειν]{.greek-added} ου μη σε απαρνησωμαι [ω]{.unclear}σαυτως δε και παντες ελεγον[14:31]{.aside}

και ερχονται εις χωριον ου το ονομα [γεθσημανη]{.greek-omitted} [γεθσημανι]{.greek-added} και λεγει τοις μαθηταις αυτου καθισατε ωδε εως [αν]{.greek-added} προσευξωμαι[14:32]{.aside}

και παραλαμβανει τον πετρον και [τον]{.greek-added} ιακωβον και [ιωαννην]{.greek-omitted} [μεθ]{.greek-omitted} [[ιω]{.greek-abbr}]{.greek-added} [μετ]{.greek-added} [εαυτου]{.greek-omitted} [αυτου]{.greek-added} και ηρξατο εκθαμβεισθαι και αδημονειν[14:33]{.aside}

και λεγει αυτοις περιλυπος εστιν η ψυχη μου εως θανατου μεινατε ωδε και γρηγορειτε[14:34]{.aside}

και προσελθων μικρον επεσεν επι της γης και προσηυχετο ινα ει δυνατον [εστιν]{.greek-omitted} [εστι]{.greek-added} παρελθη απ αυτου η ωρα[14:35]{.aside}

και ελεγεν αββα ο [πατηρ]{.greek-abbr} [μου]{.greek-added} παντα δυνατα σοι [εστι]{.greek-added} [παρενεγκε]{.greek-omitted} [παρενεγκαι]{.greek-added} το ποτηριον [τουτο]{.greek-added} απ εμου [τουτο]{.greek-omitted} αλλ [ου]{.greek-omitted} [ουχ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} εγω θελω [αλλα]{.greek-omitted} [αλλ]{.greek-added} [τι]{.greek-omitted} [ως]{.greek-added} συ[14:36]{.aside}

και ερχεται και ευρισκει αυτους καθευδοντας και λεγει τω πετρω σιμων καθευδεις ουκ ισχυσας [μιαν]{.greek-omitted} [μικραν]{.greek-added} ωραν γρηγορησαι[14:37]{.aside}

γρηγορειτε και προσευχεσθε ινα μη εισελθητε εις πειρασμον το μεν [πνευμα]{.greek-abbr} προθυμον η δε σαρξ ασθενης[14:38]{.aside}

και παλιν απελθων [προσηυξατο]{.greek-omitted} [ηυξατο]{.greek-added} τον αυτον λογον ειπων[14:39]{.aside}

και υποστρεψας [παλιν]{.greek-added} ευρεν αυτους [παλιν]{.greek-omitted} καθευδοντας [η]{.unclear}σαν γαρ οι οφθαλμοι αυτων βεβαρημενοι και ουκ ηδεισαν τι αυτω [αποκριθωσιν]{.greek-omitted} [ανταποκριθωσι]{.greek-added}[14:40]{.aside}

και ερχεται το τριτον και λεγει αυτοις καθευδετε [το]{.greek-added} λοιπον και αναπαυεσθε απεχει [το]{.greek-added} [τελος]{.greek-added} ηλθεν η ωρα ιδου παραδιδοται ο [υιος]{.greek-abbr} του [ανθρωπου]{.greek-abbr} εις [τας]{.greek-omitted} χειρας των αμαρτωλων[14:41]{.aside}

[εγειρεσθε]{.greek-omitted} [εγηρεσθε]{.greek-added} αγωμεν ιδου ο παραδιδους με [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added}[14:42]{.aside}

και ευθεως ετι αυτου λαλουντος παραγινεται ιουδας [ο]{.greek-added} [ισκαριωτης]{.greek-added} εις [ων]{.greek-omitted} των δωδεκα και μετ αυτου [ο]{.unclear}χλος πολυς μετα μαχαιρων και ξυλων παρα των αρχιερεων και [των]{.greek-omitted} γραμματεων και [των]{.greek-omitted} πρεσβυτερων[14:43]{.aside}

δεδωκει δε ο παραδιδους αυτον [συσσημον]{.greek-omitted} [σημειον]{.greek-added} [λεγων]{.greek-added} αυτοις [λεγων]{.greek-omitted} ον αν φιλησω αυτος [εστιν]{.greek-omitted} [εστι]{.greek-added} κρατησατε αυτον και απαγαγετε ασφαλως[14:44]{.aside}

και [ελθων]{.greek-omitted} ευθεως προσελθων αυτω λεγει [χαιρε]{.greek-added} [αυτω]{.greek-omitted} [ραββι]{.greek-omitted} ραββι και κατεφιλησεν αυτον[14:45]{.aside}

οι δε επεβαλον επ α[υ]{.unclear}τον τας χειρας αυτων και εκρατησαν αυτον[14:46]{.aside}

εις δε τις των παρεστηκοτων σπασαμενος [την]{.greek-omitted} μαχαιραν [επαισεν]{.greek-omitted} [επαισε]{.greek-added} τον δουλον του αρχιερεως και αφειλεν αυτου το ωτιον[14:47]{.aside}

και αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις ως επι ληστην [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} μετα μαχαιρων και ξυλων συλλαβειν με[14:48]{.aside}

καθ ημεραν ημην προς υμας εν τω ιερω διδασκων και ουκ εκρατησατε με αλλ ινα πληρωθωσιν αι γραφαι [των]{.greek-added} [προφητων]{.greek-added}[14:49]{.aside}

[και]{.greek-omitted} [τοτε]{.greek-added} [οι]{.greek-added} [μαθηται]{.greek-added} αφεντες αυτον παντες εφυγον[14:50]{.aside}

και εις τις νεανισκος ηκολουθησεν αυτω περιβεβλημενος σινδονα επι γυμνου [και]{.greek-omitted} [ο[ι]{.unclear}]{.greek-added} [δε]{.greek-added} [νεανισκοι]{.greek-added} κρατουσιν αυτον [οι]{.greek-omitted} [νεανισκοι]{.greek-omitted}[14:51]{.aside}

ο δε καταλιπων την σινδονα γυμνος εφυγεν απ αυτων[14:52]{.aside}

και απηγαγον τον [ιησουν]{.greek-abbr} προς τον αρχιερεα [καιαφαν]{.greek-added} και [συνερχονται]{.greek-omitted} [συνπορευονται]{.greek-added} [αυτω]{.greek-omitted} παντες οι αρχιερεις και οι [πρεσβυτεροι]{.greek-omitted} [γραμματεις]{.greek-added} και οι [γραμματεις]{.greek-omitted} [πρεσβυτεροι]{.greek-added}[14:53]{.aside}

και ο πετρος απο μακροθεν ηκολουθησεν αυτω εως [της]{.greek-added} [εσω]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [αυλην]{.greek-omitted} [αυλης]{.greek-added} του αρχιερεως και ην συγκαθημενος [με]{.unclear}τα των υπηρετων και θερμαινομενος προς το φως[14:54]{.aside}

οι δε αρχιερεις και ολον το συνεδριον εζητουν κατα του [ιησου]{.greek-abbr} μαρτυριαν εις το θανατωσαι αυτον και ουχ ευρισκον[14:55]{.aside}

πολλοι γαρ εψευδομαρτυρουν κατ αυτου και ισαι αι μαρτυριαι ουκ ησαν[14:56]{.aside}

και τινες ανασταντες εψευδομαρτυρουν κατ αυτου λεγοντες[14:57]{.aside}

οτι ημεις ηκουσαμεν αυτου λεγοντος οτι εγω καταλυσω τον ναον τουτον τον χειροποιητον και δια τριων ημερων αλλον αχειροποιητον οικοδομησω[14:58]{.aside}

και ουδε ουτως [ην]{.greek-added} ιση [ην]{.greek-omitted} η μαρτυρια αυτων[14:59]{.aside}

και αναστας ο αρχιερευς εις [το]{.greek-added} μεσον [επηρωτησεν]{.greek-omitted} [επηρωτησε]{.greek-added} τον [ιησουν]{.greek-abbr} λεγων ουκ αποκρινη ουδεν τι ουτοι σου καταμαρτυρουσιν[14:60]{.aside}

ο δε εσιωπα και ουδεν απεκρινατο [και]{.greek-added} παλιν ο αρχιερευς επηρωτα αυτον [ει]{.greek-added} [και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτω]{.greek-omitted} συ ει ο [χριστος]{.greek-abbr} ο [υιος]{.greek-abbr} του ευλογητου[14:61]{.aside}

ο δε [ιησους]{.greek-abbr} [αποκριθεις]{.greek-added} ειπεν [αυτω]{.greek-added} [συ]{.greek-added} [ειπας]{.greek-added} [οτι]{.greek-added} εγω ειμι και οψεσθε τον υιον του [ανθρωπου]{.greek-abbr} εκ δεξιων καθημενον της δυναμεως και ερχομενον μετα των νεφελων του [ουρανου]{.greek-abbr}[14:62]{.aside}

ο δε αρχιερευς διαρρηξας τους χιτωνας αυτου λεγει τι ετι χρειαν εχομεν μαρτυρων[14:63]{.aside}

ηκουσατε [της]{.greek-omitted} [παντες]{.greek-added} [την]{.greek-added} [βλασφημιας]{.greek-omitted} [βλασφημιαν]{.greek-added} [αυτου]{.greek-added} τι υμιν [δοκει]{.greek-added} [και]{.greek-added} [φαινεται]{.greek-omitted} [οι]{.greek-omitted} [δε]{.greek-omitted} παντες κατεκριναν αυτον ειναι ενοχον θανατου[14:64]{.aside}

και ηρξαντο τινες εμπτυειν αυτω και περικαλυπτειν το προσωπον αυτου και κολαφιζειν αυτον και λεγειν αυτω προφητευσον [ημιν]{.greek-added} [[χριστε]{.greek-abbr}]{.greek-added} [τις]{.greek-added} [εστιν]{.greek-added} [ο]{.greek-added} [παισας]{.greek-added} [σε]{.greek-added} και οι υπηρεται ραπισμασιν αυτον [εβαλλον]{.greek-omitted} [ελαμβανον]{.greek-added}[14:65]{.aside}

και οντος του πετρου εν τη αυλη κατω ερχεται μια των παιδισκων του αρχιερεως[14:66]{.aside}

και ιδουσα [τον]{.greek-omitted} [αυτον]{.greek-added} [πετρον]{.greek-omitted} θερμαινομενον εμβλεψασα αυτω λεγει και συ μετα του ναζαρηνου [ιησου]{.greek-abbr} [ησθα]{.greek-omitted} [ει]{.greek-added}[14:67]{.aside}

ο δε ηρνησατο λεγων [ουκ]{.greek-omitted} [ουτε]{.greek-added} οιδα [ουδε]{.greek-omitted} [ουτε]{.greek-added} επισταμαι [συ]{.greek-added} τι [συ]{.greek-omitted} λεγεις και εξηλθεν εξω εις το [προαυλιον]{.greek-omitted} [προαυλειον]{.greek-added} και αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added}[14:68]{.aside}

[παλιν]{.greek-added} [δε]{.greek-added} [και]{.greek-omitted} [η]{.greek-omitted} [παιδισκη]{.greek-omitted} ιδουσα αυτον [παλιν]{.greek-omitted} [παιδισκη]{.greek-added} ηρξατο λεγειν τοις [παρεστηκοσιν]{.greek-omitted} [παρεστωσιν]{.greek-added} οτι [και]{.greek-added} [ουτος]{.greek-omitted} [αυτος]{.greek-added} εξ αυτων εστιν[14:69]{.aside}

ο δε παλιν ηρνειτο και μετα μικρον παλιν οι παρεστωτες ελεγον τω πετρω αληθως εξ αυτων ει και γαρ γαλιλαιος ει [και]{.greek-omitted} [η]{.greek-omitted} [λαλια]{.greek-omitted} [σου]{.greek-omitted} [ομοιαζει]{.greek-omitted}[14:70]{.aside}

ο δε ηρξατο αναθεματιζειν και [ομνυναι]{.greek-omitted} [ομνυνειν]{.greek-added} οτι ουκ οιδα τον [ανθρωπον]{.greek-abbr} τουτον ον λεγετε[14:71]{.aside}

και [ευθεως]{.greek-added} εκ δευτερου αλεκτωρ [εφωνησεν]{.greek-omitted} [εφωνησε]{.greek-added} και [ανεμνησθη]{.greek-omitted} [εμνησθη]{.greek-added} ο πετρος το ρημα ο ειπεν αυτω ο [ιησους]{.greek-abbr} οτι πριν αλεκτορα φωνησαι [δις]{.greek-omitted} απαρνηση με τρις και [επιβαλων]{.greek-omitted} [επιλαβων]{.greek-added} εκλαιεν[14:72]{.aside}

### Chapter 15

και ευθεως [επι]{.greek-omitted} [το]{.greek-omitted} πρωι συμβουλιον [ποιησαντες]{.greek-omitted} [εποιησαν]{.greek-added} οι αρχιερεις μετα των πρεσβυτερων και [των]{.greek-added} γραμματεων και ολον το συνεδριον [και]{.greek-added} δησαντες τον [ιησουν]{.greek-abbr} [απηνεγκαν]{.greek-omitted} [απηγαγον]{.greek-added} και παρεδωκαν [τω]{.greek-omitted} πιλατω[15:1]{.aside}

και επηρωτησεν αυτον ο πιλατος [λεγων]{.greek-added} συ ει ο βασιλευς των ιουδαιων ο δε αποκριθεις [λεγει]{.greek-added} [ειπεν]{.greek-omitted} [αυτω]{.greek-omitted} συ λεγεις[15:2]{.aside}

και κατηγορουν αυτου οι αρχιερεις πολλα [αυτος]{.greek-added} [δε]{.greek-added} [ουδεν]{.greek-added} [απεκρινατο]{.greek-added}[15:3]{.aside}

ο δε πιλατος παλιν επηρωτησεν αυτον [λεγων]{.greek-omitted} ουκ αποκρινη ουδεν ιδε ποσα σου καταμαρτυρουσιν[15:4]{.aside}

ο δε [ιησους]{.greek-abbr} ουκετι ουδεν απεκριθη ωστε θαυμαζειν τον πιλατον[15:5]{.aside}

κατα δε εορτην απελυεν αυτοις ενα δεσμιον [ονπερ]{.greek-omitted} [ον]{.greek-added} ητουντο[15:6]{.aside}

ην δε ο λεγομενος [βαραββας]{.greek-omitted} [βαραβας]{.greek-added} μετα των [συστασιαστων]{.greek-omitted} [στασιαστων]{.greek-added} δεδεμενος οιτινες εν τη στασει φονον πεποιηκεισαν[15:7]{.aside}

και αναβοησας ο οχλος ηρξατο αιτεισθαι καθως αει εποιει αυτοις[15:8]{.aside}

ο δε πιλατος [απεκριθη]{.greek-omitted} [αποκριθεις]{.greek-added} αυτοις [λεγων]{.greek-omitted} [λεγει]{.greek-added} θελετε απολυσω υμιν τον βασιλεα των ιουδαιων[15:9]{.aside}

[εγινωσκεν]{.greek-omitted} [ηδει]{.greek-added} γαρ οτι δια φθονον [παραδεδωκεισαν]{.greek-omitted} [παρεδωκαν]{.greek-added} αυτον οι αρχιερεις[15:10]{.aside}

οι δε αρχιερεις ανεσεισαν τον οχλον ινα μαλλον τον βαραββαν απολυση αυτοις[15:11]{.aside}

ο δε πιλατος [παλιν]{.greek-added} αποκριθεις [παλιν]{.greek-omitted} ειπεν αυτοις τι ουν θελετε ποιησω [ον]{.greek-omitted} [τον]{.greek-added} [λεγετε]{.greek-omitted} βασιλεα των ιουδαιων[15:12]{.aside}

οι δε παλιν [εκραξαν]{.greek-omitted} [εκραυγαζον]{.greek-added} [ανασειομενοι]{.greek-added} [υπο]{.greek-added} [των]{.greek-added} [αρχιερεων]{.greek-added} [και]{.greek-added} [ελεγον]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:13]{.aside}

ο δε πιλατος ελεγεν αυτοις τι γαρ κακον εποιησεν οι δε [περισσοτερως]{.greek-omitted} [περισσως]{.greek-added} [εκραξαν]{.greek-omitted} [εκραζον]{.greek-added} [λεγοντες]{.greek-added} [σταυρωσον]{.greek-abbr} αυτον[15:14]{.aside}

ο δε πιλατος βουλομενος [το]{.greek-added} [ικανον]{.greek-added} τω οχλω [το]{.greek-omitted} [ικανον]{.greek-omitted} ποιησαι απελυσεν αυτοις τον βαραββαν [και]{.greek-omitted} [τον]{.greek-added} [δε]{.greek-added} [[ιησουν]{.greek-abbr}]{.greek-added} [φραγγελωσας]{.greek-added} παρεδωκεν [τον]{.greek-omitted} [ιησουν]{.greek-omitted} [φραγελλωσας]{.greek-omitted} ινα [σταυρωθη]{.greek-abbr}[15:15]{.aside}

οι δε στρατιωται απηγαγον αυτον εσω [της]{.greek-omitted} [εις]{.greek-added} [την]{.greek-added} [αυλης]{.greek-omitted} [αυλην]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} πραιτωριον και συγκαλουσιν ολην την σπειραν[15:16]{.aside}

και [ενδυουσιν]{.greek-omitted} [ενδιδυσκουσιν]{.greek-added} [αυτον]{.greek-omitted} [αυτω]{.greek-added} [χλαμμυδα]{.greek-added} [κοκκινην]{.greek-added} [και]{.greek-added} πορφυραν και περιτιθεασιν αυτω πλεξαντες [ακανθινον]{.greek-omitted} στεφανον [εξ]{.greek-added} [ακανθων]{.greek-added}[15:17]{.aside}

και ηρξαντο ασπαζεσθαι αυτον χαιρε ο βασιλευς των ιουδαιων[15:18]{.aside}

και ετυπτον αυτου την κεφαλην καλαμω και ενεπτυον αυτω και τιθεντες τα γονατα προσεκυνουν αυτω[15:19]{.aside}

και οτε ενεπαιξαν αυτω εξεδυσαν αυτον την [χλαμυδα]{.greek-added} [και]{.greek-added} [την]{.greek-added} πορφυραν και [ενε]{.greek-added} [ενεδυσαν]{.greek-omitted} [δυσαν]{.greek-added} αυτον τα ιματια τα ιδια και εξαγουσιν αυτον [ινα]{.greek-omitted} [ωστε]{.greek-added} [σταυρωσωσιν]{.greek-omitted} [[σταυρωσαι]{.greek-abbr}]{.greek-added} αυτον[15:20]{.aside}

και [αγγαρευουσιν]{.greek-omitted} [αγγαρευουσι]{.greek-added} παραγοντα [σιμωνα]{.greek-added} τινα [σιμωνα]{.greek-omitted} κυρηναιον ερχομενον [απ]{.greek-omitted} [απο]{.greek-added} αγρου τον [πατερα]{.greek-abbr} αλεξανδρου και ρουφου ινα αρη τον [σταυρον]{.greek-abbr} αυτου[15:21]{.aside}

και φερουσιν αυτον επι [τον]{.greek-added} γολγοθα τοπον ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον κρανιου τοπος[15:22]{.aside}

και εδιδουν αυτω πιειν εσμυρνισμενον οινον ο δε ουκ [ελαβεν]{.greek-omitted} [ελαβε]{.greek-added}[15:23]{.aside}

και [σταυρωσαντες]{.greek-omitted} [[στρωσαντες]{.greek-abbr}]{.greek-added} αυτον [διαμεριζονται]{.greek-omitted} [διεμεριζοντο]{.greek-added} τα ιματια αυτου βαλλοντες κληρον επ αυτα τις τι αρη[15:24]{.aside}

ην δε ωρα τριτη και [εσταυρωσαν]{.greek-abbr} αυτον[15:25]{.aside}

και ην η [επιγραφη]{.greek-omitted} [αιτια]{.greek-added} της [αιτιας]{.greek-omitted} [επιγραφης]{.greek-added} αυτου επιγεγραμμενη ο βασιλευς των ιουδαιων[15:26]{.aside}

και συν αυτω [σταυρουσιν]{.greek-omitted} [[στρουσι]{.greek-abbr}]{.greek-added} δυο ληστας ενα εκ δεξιων και ενα εξ ευωνυμων αυτου[15:27]{.aside}

και επληρωθη η γραφη η λεγουσα και μετα ανομων ελογισθη[15:28]{.aside}

και οι παραπορευομενοι εβλασφημουν αυτον κινουντες τας κεφαλας [αυτων]{.greek-omitted} και λεγοντες ουα ο καταλυων τον ναον και εν τρισιν ημεραις οικοδομων[15:29]{.aside}

σωσον σεαυτον [και]{.greek-omitted} καταβα απο του [σταυρου]{.greek-abbr}[15:30]{.aside}

ομοιως και οι αρχιερεις εμπαιζοντες [προς]{.greek-omitted} [εις]{.greek-added} αλληλους μετα των γραμματεων ελεγον αλλους εσωσεν εαυτον ου δυναται σωσαι[15:31]{.aside}

ο [χριστος]{.greek-abbr} [ο]{.greek-omitted} βασιλευς [του]{.greek-omitted} [ισραηλ]{.greek-abbr} καταβατω νυν απο του [σταυρου]{.greek-abbr} ινα ιδωμεν και πιστευσωμεν αυτω και οι [συνεσταυρωμενοι]{.greek-abbr} [αυτω]{.greek-omitted} ωνειδιζον αυτον[15:32]{.aside}

[και]{.greek-added} γενομενης [δε]{.greek-omitted} ωρας εκτης σκοτος εγενετο εφ ολην την γην εως ωρας [ενατης]{.greek-omitted} [εννατης]{.greek-added}[15:33]{.aside}

και τη [εννατη]{.greek-added} ωρα [τη]{.greek-omitted} [ενατη]{.greek-omitted} εβοησεν ο [ιησους]{.greek-abbr} φωνη μεγαλη λεγων ελωι ελωι [λιμα]{.greek-omitted} [λαμα]{.greek-added} [σαβαχθανι]{.greek-omitted} [σαβαχθανει]{.greek-added} ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον ο [θεος]{.greek-abbr} μου ο [θεος]{.greek-abbr} μου εις τι με εγκατελιπες[15:34]{.aside}

και τινες των παρεστηκοτων ακουσαντες ελεγον [ιδου]{.greek-omitted} [οτι]{.greek-added} ηλιαν φωνει[15:35]{.aside}

[δραμων]{.greek-omitted} [δε]{.greek-omitted} [εις]{.greek-omitted} και [δραμοντες]{.greek-added} [γεμισας]{.greek-omitted} [εγεμισαν]{.greek-added} σπογγον οξους [και]{.greek-added} [περιθεις]{.greek-omitted} [περιθεντες]{.greek-added} [τε]{.greek-omitted} καλαμω [εποτιζεν]{.greek-omitted} [εποτιζαν]{.greek-added} αυτον [λεγων]{.greek-omitted} [αφετε]{.greek-omitted} [λεγοντες]{.greek-added} [αφες]{.greek-added} ιδωμεν ει ερχεται ηλιας καθελειν αυτον[15:36]{.aside}

ο δε [ιησους]{.greek-abbr} αφεις φωνην μεγαλην [εξεπνευσεν]{.greek-omitted} [εξεπνευσε]{.greek-added}[15:37]{.aside}

και το καταπετασμα του ναου εσχισθη εις δυο απο ανωθεν εως κατω[15:38]{.aside}

ιδων δε ο κεντυριων ο παρεστηκως [αυτω]{.greek-added} [εξ]{.greek-omitted} [εναντιας]{.greek-omitted} [αυτου]{.greek-omitted} οτι [ουτως]{.greek-omitted} κραξας εξεπνευσεν ειπεν αληθως ο [ανθρωπος]{.greek-abbr} ουτος [υιος]{.greek-abbr} [[θεου]{.greek-abbr}]{.greek-added} ην [θεου]{.greek-omitted}[15:39]{.aside}

ησαν δε και γυναικες απο μακροθεν θεωρουσαι εν αις ην [και]{.greek-omitted} μαρια η μαγδαληνη και μαρια η [του]{.greek-omitted} ιακωβου του μικρου και ιωση[―]{.gap} [[ιωση]{.corr}]{.greek-added} [μητηρ]{.greek-abbr} και σαλωμη[15:40]{.aside}

αι και οτε ην εν τη γαλιλαια ηκολουθουν αυτω και διηκονουν αυτω και αλλαι πολλαι αι συναναβασαι αυτω εις ιεροσολυμα[15:41]{.aside}

και ηδη οψιας γενομενης επει ην παρασκευη ο [εστιν]{.greek-omitted} [εστι]{.greek-added} [προς]{.greek-added} [προσαββατον]{.greek-omitted} [σαββατον]{.greek-added}[15:42]{.aside}

[ηλθεν]{.greek-omitted} [ελθων]{.greek-added} ιωσηφ ο απο [αριμαθαιας]{.greek-omitted} [αριματθαιας]{.greek-added} ευσχημων βουλευτης ος και αυτος ην προσδεχομενος την βασιλειαν του [θεου]{.greek-abbr} τολμησας [εισηλθεν]{.greek-omitted} [εισηλθε]{.greek-added} προς πιλατον και ητησατο το σωμα του [ιησου]{.greek-abbr}[15:43]{.aside}

ο δε πιλατος εθαυμασεν ει ηδη [τεθνηκεν]{.greek-omitted} [τεθνηκε]{.greek-added} και προσκαλεσαμενος τον κεντυριωνα επηρωτησεν αυτον ει παλαι απεθανεν[15:44]{.aside}

και γνους [απο]{.greek-omitted} [του]{.greek-omitted} [παρα]{.greek-added} [των]{.greek-added} κεντυριωνος εδωρησατο το σωμα τω ιωσηφ[15:45]{.aside}

και αγορασας σινδονα και καθελων αυτον [ενειλησεν]{.greek-omitted} [ενειλισσε]{.greek-added} τη σινδονι και [κατεθηκεν]{.greek-omitted} [εθηκεν]{.greek-added} αυτον εν μνημειω ο ην λελατομημενον εκ πετρας και [προσεκυλισεν]{.greek-omitted} [προσεκυλισε]{.greek-added} λιθον επι την θυραν του μνημειου[15:46]{.aside}

η δε [μαρια]{.greek-omitted} [μαριαμ]{.greek-added} η μαγδαληνη και μαρια [ιωση]{.greek-omitted} [η]{.greek-added} [ιακωβου]{.greek-added} [και]{.greek-added} [ιωσητος]{.greek-added} [[μητηρ]{.greek-abbr}]{.greek-added} εθεωρουν που τιθεται[15:47]{.aside}

### Chapter 16

και διαγενομενου του σαββατου [μαρια]{.greek-omitted} [μαριαμ]{.greek-added} η μαγδαληνη και μαρια [η]{.greek-added} ιακωβου και σαλωμη [πορευθεισαι]{.greek-added} ηγορασαν αρωματα ινα ελθουσαι αλειψωσιν αυτον[16:1]{.aside}

και λιαν πρωι της μιας σαββατων ερχονται επι το μνημειον [ετι]{.greek-added} ανατειλαντος του ηλιου[16:2]{.aside}

και ελεγον προς εαυτας τις αποκυλισει ημιν τον λιθον εκ της θυρας του μνημειου[16:3]{.aside}

και αναβλεψασαι θεωρουσιν οτι αποκεκυλισται ο λιθος ην γαρ μεγας σφοδρα[16:4]{.aside}

και εισελθουσαι εις το μνημειον ειδον νεανισκον καθημενον εν τοις δεξιοις περιβεβλημενον στολην λευκην και εξεθαμβηθησαν[16:5]{.aside}

ο δε λεγει αυταις μη [εκθαμβεισθε]{.greek-omitted} [εκθαμβησθε]{.greek-added} [ιησουν]{.greek-abbr} ζητειτε τον ναζαρηνον τον [εσταυρωμενον]{.greek-abbr} ηγερθη ουκ εστιν ωδε ιδε ο τοπος οπου εθηκαν αυτον[16:6]{.aside}

αλλ υπαγετε ειπατε τοις μαθηταις αυτου και τω πετρω οτι [ιδου]{.greek-added} προαγει υμας εις την γαλιλαιαν εκει αυτον οψεσθε καθως ειπεν υμιν[16:7]{.aside}

και εξελθουσαι εφυγον απο του μνημειου [ειχεν]{.greek-omitted} [ειχε]{.greek-added} δε αυτας τρομος και εκστασις και ουδενι ουδεν ειπον εφοβουντο γαρ[16:8]{.aside}

αναστας δε πρωι πρωτη σαββατου εφανη πρωτον μαρια τη μαγδαληνη αφ ης εκβεβληκει επτα δαιμονια[16:9]{.aside}

εκεινη πορευθεισα [απηγγειλεν]{.greek-omitted} [απηγγειλε]{.greek-added} τοις μετ αυτου γενομενοις [πενθουσιν]{.greek-omitted} [πενθουσι]{.greek-added} και [κλαιουσιν]{.greek-omitted} [κλαιουσι]{.greek-added}[16:10]{.aside}

κακεινοι ακουσαντες οτι ζη και εθεαθη υπ αυτης ηπιστησαν[16:11]{.aside}

μετα δε ταυτα δυσιν εξ αυτων περιπατουσιν εφανερωθη εν ετερα μορφη πορευομενοις εις αγρον[16:12]{.aside}

κακεινοι απελθοντες απηγγειλαν [τοις]{.greek-omitted} [λοιποις]{.greek-omitted} ουδε εκεινοις επιστευσαν[16:13]{.aside}

υστερον ανακειμενοις αυτοις τοις ενδεκα εφανερωθη και [ωνειδισεν]{.greek-omitted} [ωνειδισε]{.greek-added} την απιστιαν αυτων και σκληροκαρδιαν οτι τοις θεασαμενοις αυτον εγηγερμενον ουκ επιστευσαν[16:14]{.aside}

και ειπεν αυτοις πορευθεντες εις τον κοσμον απαντα κηρυξατε το ευαγγελιον παση τη κτισει[16:15]{.aside}

ο πιστευσας και βαπτισθεις σωθησεται ο δε απιστησας κατακριθησεται[16:16]{.aside}

σημεια δε τοις [πιστευσασιν]{.greek-omitted} [πιστευσασι]{.greek-added} ταυτα παρακολουθησει εν τω ονοματι μου δαιμονια εκβαλουσιν γλωσσαις [λαλησουσιν]{.greek-omitted} [λαλησουσι]{.greek-added} καιναις[16:17]{.aside}

οφεις [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} καν θανασιμον τι πιωσιν ου μη αυτους βλαψη επι αρρωστους χειρας [επιθησουσιν]{.greek-omitted} [επιθησουσι]{.greek-added} και καλως εξουσιν[16:18]{.aside}

ο μεν ουν [κυριος]{.greek-abbr} μετα το λαλησαι αυτοις ανεληφθη εις τον [ουρανον]{.greek-abbr} και εκαθισεν εκ δεξιων του [θεου]{.greek-abbr}[16:19]{.aside}

εκεινοι δε εξελθοντες εκηρυξαν πανταχου του [κυριου]{.greek-abbr} συνεργουντος και τον λογον βεβαιουντος δια των επακολουθουντων σημειων αμην[16:20]{.aside}

