---
title: "Collation of Byz^RP^ vs 32551 (2551)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2551 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32551).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2551                                   	| λογος                              	|
| 2551 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2551 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2551               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2551                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2551 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2551                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 5

[μητε]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [κεφαλη]{.greek-omitted} [σου]{.greek-omitted} [ομοσης]{.greek-omitted} [οτι]{.greek-omitted} [ου]{.greek-omitted} [δυνασαι]{.greek-omitted} [μιαν]{.greek-omitted} [τριχα]{.greek-omitted} [λευκην]{.greek-omitted} [η]{.greek-supplied} [μελαιν]{.unclear}[αν]{.greek-supplied} [ποιη]{.greek-supplied}σαι[5:36]{.aside}

[εστω]{.greek-supplied} [δε]{.greek-supplied} [ο]{.greek-supplied} [λογος]{.greek-supplied} [υμων]{.greek-supplied} [ναι]{.greek-supplied} [ναι]{.greek-supplied} [ου]{.greek-supplied} [ου]{.greek-supplied} [το]{.greek-supplied} δε περ[ι]{.greek-supplied}[σ]{.unclear}σον τουτων εκ του πον[ηρου]{.greek-supplied} [εστι]{.greek-supplied}ν[5:37]{.aside}

ηκουσατ[ε]{.greek-supplied} [ο]{.greek-supplied}τι ερ[ρ]{.unclear}εθη οφθαλμον αντι οφθαλμου και οδοντα [αν]{.greek-supplied}[τι]{.unclear} [οδ]{.unclear}οντος[5:38]{.aside}

εγω δε λεγω υμιν μη α[ν]{.unclear}τιστηναι τω πον[η]{.unclear}[ρω]{.greek-supplied} [α]{.greek-supplied}λλ οσ[τι]{.unclear}ς σε ραπισει επι την δεξια[ν]{.unclear} [[σο]{.unclear}[υ]{.greek-supplied}]{.greek-added} [σια]{.greek-supplied}γ[ονα]{.greek-supplied} στρε[ψον]{.greek-supplied} αυ[τω]{.greek-supplied} και την αλλην[5:39]{.aside}

και τω θελ[οντι]{.unclear} [σοι]{.unclear} [κρι]{.unclear}[θηναι]{.greek-supplied} [και]{.greek-supplied} [τον]{.greek-supplied} χι[τω]{.unclear}να σου λαβειν αφες αυτω και το ιματιον[5:40]{.aside}

κ[αι]{.unclear} [ο]{.unclear}στις σε αγγαρευσει μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

[τ]{.greek-supplied}ω αιτουντι σε διδου και τον θελοντα απο σ[ου]{.unclear} [δανει]{.unclear}σα[σθαι]{.greek-supplied} μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις [τ]{.unclear}[ον]{.greek-supplied} πλησιον σου και μισησεις τον εχθρον σου[5:43]{.aside}

εγω δε [λ]{.unclear}[ε]{.greek-supplied}γω υμιν αγαπατε τους εχθρους υμων [ευλογειτε]{.greek-omitted} [τους]{.greek-omitted} [καταρωμενους]{.greek-omitted} [υμας]{.greek-omitted} καλως ποι[ει]{.greek-supplied}τε τοις μισουσιν υμας και [προσευχεσθε]{.greek-omitted} [προσευχεσθαι]{.greek-added} υπερ των [ε]{.unclear}[πη]{.greek-supplied}ρεαζοντων υμας και διωκοντων υμας[5:44]{.aside}

οπως [γε]{.greek-supplied}νησθε υιοι του [πατρος]{.greek-abbr} υμων του εν τοις [ουρανοις]{.greek-abbr} οτι τον [η]{.greek-supplied}λιον αυτου ανατελλει επι πονηρους και αγαθους κ[αι]{.greek-supplied} βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν γαρ αγαπ[η]{.greek-supplied}σητε τους αγαπωντας υμας τινα μισθον εχε[τ]{.unclear}[ε]{.greek-supplied} ουχι και οι τελωναι το αυτο [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[5:46]{.aside}

κ[αι]{.unclear} [εαν]{.unclear} [α]{.unclear}[σπα]{.greek-supplied}σησθε τους φιλους υμ[ων]{.unclear} μονον τ[ι]{.unclear} [περι]{.unclear}[σσον]{.greek-supplied} [ποιει]{.greek-supplied}τε ουχι και οι τελωναι ουτως ποιουσ[ι]{.greek-supplied}ν[5:47]{.aside}

[εσεσθε]{.greek-omitted} [[εσ]{.unclear}εσθαι]{.greek-added} [ουν]{.greek-omitted} υμεις τελειοι ωσπερ ο [πατηρ]{.greek-abbr} υμων ο εν τοις [ουρανοις]{.greek-abbr} [τε]{.greek-supplied}λειος εστιν[5:48]{.aside}

### Chapter 6

[π]{.greek-supplied}ροσεχετε την ελεημοσυνην υμων μη ποιε[ι]{.unclear}ν εμ[π]{.unclear}[ρο]{.greek-supplied}σθεν των [ανθρωπων]{.greek-abbr} προς το θεαθηναι αυτο[ις]{.greek-supplied} ε[ι]{.unclear} δ[ε]{.greek-supplied} [[μη]{.greek-supplied}]{.greek-added} [μηγε]{.greek-omitted} [μισθον]{.greek-omitted} [ουκ]{.greek-omitted} [εχετε]{.greek-omitted} [παρα]{.greek-omitted} [τω]{.greek-omitted} [πατρι]{.greek-omitted} [υμων]{.greek-omitted} [τω]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ουρανοις]{.greek-omitted}[6:1]{.aside}

[[γε]{.greek-supplied}]{.greek-added} [προσεχετε]{.greek-omitted} [την]{.greek-omitted} [ελεημοσυνην]{.greek-omitted} [υμων]{.greek-omitted} [μη]{.greek-omitted} [ποιειν]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [προς]{.greek-omitted} [το]{.greek-omitted} [θεαθηναι]{.greek-omitted} [αυτοις]{.greek-omitted} [ει]{.greek-omitted} [δε]{.greek-omitted} [μηγε]{.greek-omitted} [μισθον]{.greek-supplied} [ουκ]{.greek-supplied} [ε]{.greek-supplied}[χετε]{.unclear} π[αρα]{.greek-supplied} τω [πατρι]{.greek-abbr} υμων τω εν τοις [ουρανοις]{.greek-abbr}[6:1 | instance no. 2]{.aside}

[οταν]{.greek-supplied} ουν ποιης ελεημοσυνην μη σαλπισης εμπροσθεν [σου]{.greek-supplied} [ωσ]{.greek-supplied}περ οι υποκριται ποιουσιν [εν]{.greek-omitted} [ταις]{.greek-omitted} [συναγωγαις]{.greek-omitted} [και]{.greek-omitted} εν ταις ρυμαις οπ[ως]{.unclear} [δο]{.unclear}[ξα]{.greek-supplied}σθωσιν υπο των [ανθρωπων]{.greek-abbr} αμην λεγω υμιν απεχου[σιν]{.greek-supplied} [τον]{.greek-supplied} [μι]{.greek-supplied}σθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη [γνωτω]{.unclear} [η]{.greek-supplied} [α]{.greek-supplied}[ρ]{.greek-supplied}ιστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεη[μο]{.greek-supplied}σ[υνη]{.greek-supplied} [εν]{.greek-supplied} τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλ[επ]{.unclear}ων εν τω κρυπτω α[υτ]{.unclear}ος [απο]{.greek-supplied}δωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ [εση]{.greek-supplied} [ωσ]{.greek-supplied}περ οι υποκριται οτι φιλουσιν εν ταις συναγωγαις [κα]{.greek-supplied}ι εν ταις γωνιαις των πλατειων εστωτες [προσ]{.unclear}[ευ]{.greek-supplied}χ[εσθαι]{.greek-supplied} [ο]{.greek-supplied}[π]{.unclear}ως [αν]{.greek-omitted} [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις [ανθρωποις]{.greek-abbr} αμην λεγω υμιν οτι απεχουσ[ιν]{.greek-supplied} [τον]{.greek-supplied} μισθον [αυτων]{.greek-omitted} [αυτον]{.greek-added}[6:5]{.aside}

συ δε οταν προσευχη εισ[ε]{.unclear}λθε εις το [τα]{.greek-supplied}[μ]{.unclear}ιειον σου και κλεισας την θυραν σου προσευξαι [τω]{.greek-supplied} [πατρι]{.greek-abbr} σου τω εν τω κρυπτω και ο [πατηρ]{.greek-abbr} σου ο βλε[π]{.unclear}ω[ν]{.unclear} [εν]{.greek-supplied} τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

[προ]{.greek-supplied}[σ]{.unclear}ευχομενοι δε μη [βαττολογησητε]{.greek-omitted} [βατταλογησητε]{.greek-added} ωσπερ οι εθν[ι]{.unclear}[κοι]{.greek-supplied} [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισ[α]{.unclear}[κου]{.greek-supplied}σθησονται[6:7]{.aside}

μη ουν ομοιωθητε αυτοις [οιδεν]{.greek-supplied} [γαρ]{.greek-supplied} ο [πατηρ]{.greek-abbr} υμων ων χρειαν εχετε προ [του]{.unclear} [υμας]{.greek-supplied} [αι]{.greek-supplied}τησαι αυτον[6:8]{.aside}

ουτως ουν προσ[ευ]{.unclear}χ[εσθε]{.greek-supplied} [υμεις]{.greek-supplied} [πατερ]{.greek-abbr} ημων ο εν τοις [ουρανοις]{.greek-abbr} αγιασθητω [το]{.unclear} [ονομα]{.greek-supplied} [σο]{.greek-supplied}[υ]{.unclear}[6:9]{.aside}

ελθετω η βασιλεια σου γενηθ[η]{.unclear}τω το θε[λημα]{.greek-supplied} [σο]{.unclear}υ ως εν [ουρανω]{.greek-abbr} και επι της [γη]{.unclear}ς[6:10]{.aside}

τον αρτ[ον]{.greek-supplied} [ημω]{.greek-supplied}ν τ[ον]{.unclear} επιουσιον δος ημιν σημερ[ο]{.unclear}ν[6:11]{.aside}

και αφ[ες]{.greek-supplied} [ημιν]{.greek-supplied} τα οφειληματα ημων ως και [ημεις]{.greek-supplied} [αφιεμεν]{.greek-omitted} [[αφηκα]{.greek-supplied}μ[εν]{.greek-supplied}]{.greek-added} τοις οφειλεταις ημων[6:12]{.aside}

και μη [εισενεγκης]{.greek-supplied} [ημας]{.greek-omitted} [εις]{.greek-omitted} [πειρασμον]{.greek-omitted} [αλλα]{.greek-omitted} [ρυσαι]{.greek-omitted} [ημας]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [πονηρου]{.greek-omitted} [οτι]{.greek-omitted} [σου]{.greek-omitted} [εστιν]{.greek-omitted} [η]{.greek-omitted} [βασιλεια]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δυναμις]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [δοξα]{.greek-omitted} [εις]{.greek-omitted} [τους]{.greek-omitted} [αιωνας]{.greek-omitted} [αμην]{.greek-omitted}[6:13]{.aside}

