---
title: "Collation of Byz^RP^ vs 32583 (2583)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2583 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32583).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2583                                   	| λογος                              	|
| 2583 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2583 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2583               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2583                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2583 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2583                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 2

[και]{.greek-omitted} [συ]{.greek-omitted} [βηθλεεμ]{.greek-omitted} [γη]{.greek-omitted} [ιουδα]{.greek-omitted} [ουδαμως]{.greek-omitted} [ελαχιστη]{.greek-omitted} [ει]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [ηγεμοσιν]{.greek-omitted} [ιουδα]{.greek-omitted} [εκ]{.greek-omitted} [σου]{.greek-omitted} [γαρ]{.greek-omitted} [εξελευσεται]{.greek-omitted} [ηγουμενος]{.greek-omitted} οστις ποιμανει τον λαον μου τον ισραηλ[2:6]{.aside}

τοτε ηρωδης λαθρα καλεσας τους μαγους [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

και πεμψας αυτους εις βηθλεεμ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πορευθεντες ακριβως εξετασατε περι του παιδιου επαν δε ευρητε απαγγειλατε μοι οπως καγω ελθων προσκυνησω αυτω[2:8]{.aside}

οι δε ακουσαντες του βασιλεως επορευθησαν και ιδου ο αστηρ ον ειδον εν τη ανατολη προηγεν αυτους εως ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

και χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

αναχωρησαντων δε αυτων ιδου αγγελος κυριου φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την μητερα αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την μητερα αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του κυριου δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον υιον μου[2:15]{.aside}

τοτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη [γαρ]{.greek-added} [φησι]{.greek-added} λιαν και αποστειλας [ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} παντας τους παιδας τους εν βηθλεεμ [και]{.greek-omitted} [εν]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [οριοις]{.greek-omitted} [αυτης]{.greek-omitted} [απο]{.greek-omitted} [διετους]{.greek-omitted} [και]{.greek-omitted} [κατωτερω]{.greek-omitted} [κατα]{.greek-omitted} [τον]{.greek-omitted} [χρονον]{.greek-omitted} [ον]{.greek-omitted} [ηκριβωσεν]{.greek-omitted} [παρα]{.greek-omitted} [των]{.greek-omitted} [μαγων]{.greek-omitted}[2:16]{.aside}

τοτε επληρωθη το ρηθεν υπο ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη [γαρ]{.greek-added} [φησιν]{.greek-added} εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρακληθηναι οτι ουκ εισιν[2:18]{.aside}

τελευτησαντος δε του ηρωδου ιδου αγγελος κυριου κατ οναρ φαινεται τω ιωσηφ εν αιγυπτω[2:19]{.aside}

λεγων εγερθεις παραλαβε το παιδιον και την μητερα αυτου και πορευου εις γην ισραηλ [τεθνηκασιν]{.greek-omitted} [γαρ]{.greek-omitted} [οι]{.greek-omitted} [ζητουντες]{.greek-omitted} [την]{.greek-omitted} [ψυχην]{.greek-omitted} [του]{.greek-omitted} [παιδιου]{.greek-omitted}[2:20]{.aside}

[λεγων]{.greek-omitted} [εγερθεις]{.greek-omitted} [παραλαβε]{.greek-omitted} [το]{.greek-omitted} [παιδιον]{.greek-omitted} [και]{.greek-omitted} [την]{.greek-omitted} [μητερα]{.greek-omitted} [αυτου]{.greek-omitted} [και]{.greek-omitted} [πορευου]{.greek-omitted} [εις]{.greek-omitted} [γην]{.greek-omitted} [ισραηλ]{.greek-omitted} [τεθνηκασιν]{.greek-omitted} [τεθνηκασι]{.greek-added} γαρ οι ζητουντες την ψυχην του παιδιου[2:20 | instance no. 2]{.aside}

ο δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την μητερα αυτου και ηλθεν εις γην ισραηλ[2:21]{.aside}

ακουσας δε οτι αρχελαος βασιλευει [επι]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted} αντι ηρωδου του [πατρος]{.greek-abbr} αυτου εφοβηθη εκει απελθειν χρηματισθεις δε κατ οναρ ανεχωρησεν εις τα μερη της γαλιλαιας[2:22]{.aside}

και ελθων κατωκησεν εις πολιν [λεγομενην]{.greek-omitted} [καλουμενην]{.greek-added} ναζαρετ οπως πληρωθη το ρηθεν δια των προφητων οτι ναζωραιος κληθησεται[2:23]{.aside}

### Chapter 3

εν [δε]{.greek-omitted} ταις ημεραις εκειναις παραγινεται ιωαννης ο βαπτιστης [κηρυσσων]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [ερημω]{.greek-omitted} [της]{.greek-omitted} [ιουδαιας]{.greek-omitted}[3:1]{.aside}

[και]{.greek-omitted} [λεγων]{.greek-omitted} μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των ουρανων[3:2]{.aside}

ουτος γαρ εστιν ο ρηθεις υπο ησαιου του προφητου λεγοντος φωνη βοωντος εν τη ερημω ετοιμασατε την οδον κυριου ευθειας ποιειτε τας τριβους αυτου[3:3]{.aside}

αυτος δε [ο]{.corr} ιωαννης [ειχεν]{.greek-omitted} [ειχε]{.greek-added} το ενδυμα αυτου απο τριχων καμηλου και ζωνην δερματινην περι την οσφυν αυτου η δε τροφη αυτου ην ακριδες και μελι αγριον[3:4]{.aside}

τοτε εξεπορευετο προς αυτον ιεροσολυμα και πασα η ιουδαια και πασα η περιχωρος του ιορδανου[3:5]{.aside}

και εβαπτιζοντο [εν]{.greek-omitted} [τω]{.greek-omitted} [ιορδανη]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted} εξομολογουμενοι τας αμαρτιας αυτων[3:6]{.aside}

ιδων δε πολλους των φαρισαιων και σαδδουκαιων ερχομενους επι το βαπτισμα αυτου [ειπεν]{.greek-omitted} [αυτοις]{.greek-omitted} γεννηματα εχιδνων τις υπεδειξεν υμιν φυγειν απο της μελλουσης οργης[3:7]{.aside}

ποιησατε ουν [καρπον]{.greek-omitted} [καρπους]{.greek-added} [αξιον]{.greek-omitted} [αξιους]{.greek-added} της μετανοιας[3:8]{.aside}

και μη δοξητε λεγειν εν εαυτοις πατερα εχομεν τον αβρααμ λεγω γαρ υμιν οτι δυναται ο θεος εκ των λιθων τουτων εγειραι τεκνα τω αβρααμ[3:9]{.aside}

ηδη δε και η αξινη προς την ριζαν των δενδρων κειται [παν]{.greek-omitted} [ουν]{.greek-omitted} [δενδρον]{.greek-omitted} [μη]{.greek-omitted} [ποιουν]{.greek-omitted} [καρπον]{.greek-omitted} [καλον]{.greek-omitted} [εκκοπτεται]{.greek-omitted} [και]{.greek-omitted} [εις]{.greek-omitted} [πυρ]{.greek-omitted} [βαλλεται]{.greek-omitted}[3:10]{.aside}

[ηδη]{.greek-omitted} [δε]{.greek-omitted} [και]{.greek-omitted} [η]{.greek-omitted} [αξινη]{.greek-omitted} [προς]{.greek-omitted} [την]{.greek-omitted} [ριζαν]{.greek-omitted} [των]{.greek-omitted} [δενδρων]{.greek-omitted} [κειται]{.greek-omitted} παν ουν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[3:10 | instance no. 2]{.aside}

εγω μεν βαπτιζω υμας εν υδατι εις μετανοιαν ο δε οπισω μου ερχομενος ισχυροτερος μου εστιν ου ουκ ειμι ικανος τα υποδηματα βαστασαι αυτος υμας βαπτισει εν πνευματι αγιω[3:11]{.aside}

ου το πτυον εν τη χειρι αυτου και διακαθαριει την αλωνα αυτου και συναξει τον σιτον αυτου εις την αποθηκην το δε αχυρον κατακαυσει πυρι ασβεστω[3:12]{.aside}

τοτε παραγινεται ο ιησους απο της γαλιλαιας [επι]{.greek-omitted} [εις]{.greek-added} τον ιορδανην [προς]{.greek-omitted} [τον]{.greek-omitted} [ιωαννην]{.greek-omitted} [του]{.greek-omitted} [βαπτισθηναι]{.greek-omitted} [υπ]{.greek-omitted} [αυτου]{.greek-omitted}[3:13]{.aside}

[τοτε]{.greek-omitted} [παραγινεται]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [απο]{.greek-omitted} [της]{.greek-omitted} [γαλιλαιας]{.greek-omitted} [επι]{.greek-omitted} [τον]{.greek-omitted} [ιορδανην]{.greek-omitted} προς τον ιωαννην του βαπτισθηναι υπ αυτου[3:13 | instance no. 2]{.aside}

ο δε ιωαννης διεκωλυεν αυτον λεγων εγω χρειαν εχω υπο σου βαπτισθηναι και συ ερχη προς με[3:14]{.aside}

αποκριθεις δε ο ιησους [ειπεν]{.greek-omitted} [ειπε]{.greek-added} προς αυτον αφες αρτι ουτως γαρ πρεπον εστιν ημιν πληρωσαι πασαν δικαιοσυνην [τοτε]{.greek-omitted} [αφιησιν]{.greek-omitted} [αυτον]{.greek-omitted}[3:15]{.aside}

και βαπτισθεις ο ιησους [ευθυς]{.greek-added} ανεβη [ευθυς]{.greek-omitted} απο του υδατος και ιδου ανεωχθησαν αυτω οι ουρανοι και [ειδεν]{.greek-omitted} [ειδε]{.greek-added} το πνευμα του θεου καταβαινον ωσει [περιστεραν]{.greek-omitted} [και]{.greek-omitted} [ερχομενον]{.greek-omitted} [επ]{.greek-omitted} [αυτον]{.greek-omitted}[3:16]{.aside}

[και]{.greek-omitted} [βαπτισθεις]{.greek-omitted} [ο]{.greek-omitted} [ιησους]{.greek-omitted} [ανεβη]{.greek-omitted} [ευθυς]{.greek-omitted} [απο]{.greek-omitted} [του]{.greek-omitted} [υδατος]{.greek-omitted} [και]{.greek-omitted} [ιδου]{.greek-omitted} [ανεωχθησαν]{.greek-omitted} [αυτω]{.greek-omitted} [οι]{.greek-omitted} [ουρανοι]{.greek-omitted} [και]{.greek-omitted} [ειδεν]{.greek-omitted} [το]{.greek-omitted} [πνευμα]{.greek-omitted} [του]{.greek-omitted} [θεου]{.greek-omitted} [καταβαινον]{.greek-omitted} [ωσει]{.greek-omitted} περιστεραν και ερχομενον επ αυτον[3:16 | instance no. 2]{.aside}

[και]{.greek-omitted} [ιδου]{.greek-omitted} [φωνη]{.greek-omitted} [εκ]{.greek-omitted} [των]{.greek-omitted} [ουρανων]{.greek-omitted} [λεγουσα]{.greek-omitted} ουτος εστιν ο υιος μου ο αγαπητος εν ω ευδοκησα[3:17]{.aside}

### Chapter 4

τοτε ο ιησους ανηχθη εις την ερημον υπο του πνευματος πειρασθηναι υπο του διαβολου[4:1]{.aside}

και νηστευσας ημερας τεσσαρακοντα και νυκτας τεσσαρακοντα υστερον επεινασεν[4:2]{.aside}

και προσελθων αυτω ο πειραζων ειπεν ει υιος ει [του]{.greek-omitted} [θεου]{.greek-omitted} [ειπε]{.greek-omitted} [ινα]{.greek-omitted} [οι]{.greek-omitted} [λιθοι]{.greek-omitted} [ουτοι]{.greek-omitted} [αρτοι]{.greek-omitted} [γενωνται]{.greek-omitted}[4:3]{.aside}

[και]{.greek-omitted} [προσελθων]{.greek-omitted} [αυτω]{.greek-omitted} [ο]{.greek-omitted} [πειραζων]{.greek-omitted} [ειπεν]{.greek-omitted} [ει]{.greek-omitted} [υιος]{.greek-omitted} [ει]{.greek-omitted} του θεου ειπε ινα οι λιθοι ουτοι αρτοι γενωνται[4:3 | instance no. 2]{.aside}

ο δε αποκριθεις ειπεν γεγραπται ουκ επ αρτω μονω ζησεται ανθρωπος αλλ επι παντι ρηματι εκπορευομενω δια στοματος θεου[4:4]{.aside}

τοτε παραλαμβανει αυτον ο διαβολος εις την αγιαν πολιν και ιστησιν αυτον επι το πτερυγιον του [ιερου]{.greek-omitted} [ναου]{.greek-added}[4:5]{.aside}

και λεγει αυτω ει υιος ει του θεου [βαλε]{.greek-omitted} [βαλλε]{.greek-added} σεαυτον κατω γεγραπται γαρ οτι τοις αγγελοις αυτου εντελειται περι σου και επι χειρων [αρουσιν]{.greek-omitted} [αρουσι]{.greek-added} σε μηποτε προσκοψης προς λιθον τον ποδα σου[4:6]{.aside}

εφη αυτω ο ιησους παλιν γεγραπται ουκ εκπειρασεις κυριον τον θεον σου[4:7]{.aside}

παλιν [παραλαμβανει]{.greek-omitted} [λαμβανει]{.greek-added} αυτον ο διαβολος εις ορος υψηλον λιαν και δεικνυσιν αυτω πασας τας βασιλειας του κοσμου και την δοξαν αυτων[4:8]{.aside}

και λεγει αυτω ταυτα παντα σοι δωσω εαν πεσων προσκυνησης μοι[4:9]{.aside}

τοτε λεγει αυτω ο ιησους υπαγε οπισω μου σατανα γεγραπται γαρ κυριον τον θεον σου προσκυνησεις και αυτω μονω λατρευσεις[4:10]{.aside}

τοτε αφιησιν αυτον ο διαβολος και ιδου αγγελοι προσηλθον και διηκονουν αυτω[4:11]{.aside}

ακουσας δε ο ιησους οτι ιωαννης παρεδοθη ανεχωρησεν εις την γαλιλαιαν[4:12]{.aside}

και καταλιπων την ναζαρετ [ελθων]{.greek-omitted} κατωκησεν εις καπερναουμ την παραθαλασσιαν εν οριοις ζαβουλων και νεφθαλειμ[4:13]{.aside}

ινα πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[4:14]{.aside}

γη ζαβουλων και γη νεφθαλειμ οδον θαλασσης περαν του ιορδανου γαλιλαια των εθνων[4:15]{.aside}

ο λαος ο καθημενος εν σκοτει [ειδεν]{.greek-omitted} [ειδε]{.greek-added} φως μεγα και τοις καθημενοις εν [χωρα]{.greek-omitted} [σκοτει]{.greek-added} και σκια θανατου φως ανετειλεν αυτοις[4:16]{.aside}

απο τοτε ηρξατο ο ιησους κηρυσσειν και λεγειν μετανοειτε [ηγγικεν]{.greek-omitted} [ηγγικε]{.greek-added} γαρ η βασιλεια των ουρανων[4:17]{.aside}

περιπατων δε παρα την θαλασσαν της γαλιλαιας [ειδεν]{.greek-omitted} [ειδε]{.greek-added} δυο αδελφους σιμωνα τον λεγομενον πετρον και ανδρεαν τον αδελφον αυτου βαλλοντας αμφιβληστρον εις την θαλασσαν ησαν γαρ αλιεις[4:18]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} δευτε οπισω μου και ποιησω υμας αλιεις ανθρωπων[4:19]{.aside}

οι δε [ευθεως]{.greek-omitted} αφεντες τα δικτυα ηκολουθησαν αυτω[4:20]{.aside}

και προβας εκειθεν ειδεν αλλους δυο αδελφους ιακωβον τον του ζεβεδαιου και ιωαννην τον αδελφον αυτου εν τω πλοιω μετα ζεβεδαιου του πατρος αυτων καταρτιζοντας τα δικτυα αυτων [και]{.greek-omitted} [εκαλεσεν]{.greek-omitted} [αυτους]{.greek-omitted}[4:21]{.aside}

οι δε [ευθεως]{.greek-omitted} αφεντες το πλοιον και τον πατερα αυτων ηκολουθησαν αυτω[4:22]{.aside}

και περιηγεν [ο]{.greek-added} [ιησους]{.greek-added} ολην την γαλιλαιαν [ο]{.greek-omitted} [ιησους]{.greek-omitted} διδασκων εν ταις συναγωγαις αυτων [και]{.greek-omitted} [κηρυσσων]{.greek-omitted} [το]{.greek-omitted} [ευαγγελιον]{.greek-omitted} [της]{.greek-omitted} [βασιλειας]{.greek-omitted} και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[4:23]{.aside}

και [απηλθεν]{.greek-omitted} [εξηλθεν]{.greek-added} η ακοη αυτου εις ολην την συριαν και προσηνεγκαν αυτω παντας τους κακως εχοντας πο[ικ]{.unclear}ιλαις νοσοις [και]{.greek-omitted} [βασανοις]{.greek-omitted} συνεχομενους [και]{.greek-omitted} [δαιμονιζομενους]{.greek-omitted} και σεληνιαζομενους και παραλυτικους και εθεραπευσεν αυτους[4:24]{.aside}

και ηκολουθησαν αυτω οχλοι πολλοι απο της γαλιλαιας και δεκαπολεως και ιεροσολυμων και ιουδαιας και περαν του ιορδανου[4:25]{.aside}

### Chapter 5

ιδων δε τους οχλους ανεβη εις το ορος και καθισαντος αυτου προσηλθον αυτω οι μαθηται αυτου[5:1]{.aside}

και ανοιξας το στομα αυτου εδιδασκεν αυτους [λεγων]{.greek-omitted}[5:2]{.aside}

μακαριοι οι πτωχοι τω πνευματι οτι αυτων εστιν η βασιλεια των ουρανων[5:3]{.aside}

μακαριοι οι πενθουντες οτι αυτοι παρακληθησονται[5:4]{.aside}

μακαριοι οι πραεις οτι αυτοι [κληρονομησουσιν]{.greek-omitted} [κληρονομισουσι]{.greek-added} την γην[5:5]{.aside}

μακαριοι οι πεινωντες και διψωντες την δικαιοσυνην οτι αυτοι χορτασθησονται[5:6]{.aside}

μακαριοι οι ελεημονες οτι αυτοι ελεηθησονται[5:7]{.aside}

μακαριοι οι καθαροι τη καρδια οτι αυτοι τον θεον οψονται[5:8]{.aside}

μακαριοι οι ειρηνοποιοι οτι αυτοι υιοι θεου κληθησονται[5:9]{.aside}

μακαριοι οι δεδιωγμενοι ενεκεν δικαιοσυνης οτι αυτων εστιν η βασιλεια των ουρανων[5:10]{.aside}

μακαριοι εστε οταν ονειδισωσιν υμας και διωξωσιν και [ειπωσιν]{.greek-omitted} [ειπωσι]{.greek-added} παν πονηρον ρημα καθ υμων ψευδομενοι ενεκεν εμου[5:11]{.aside}

χαιρετε και αγαλλιασθε οτι ο μισθος υμων πολυς εν τοις ουρανοις ουτως γαρ εδιωξαν τους προφητας τους προ υμων[5:12]{.aside}

υμεις εστε το αλας της γης εαν δε το αλας μωρανθη εν τινι αλισθησεται εις ουδεν ισχυει ετι ει μη βληθηναι εξω και καταπατεισθαι υπο των ανθρωπων[5:13]{.aside}

υμεις εστε το φως του κοσμου ου δυναται πολις κρυβηναι επανω ορους κειμενη[5:14]{.aside}

ουδε [καιουσιν]{.greek-omitted} [καιουσι]{.greek-added} λυχνον και τιθεασιν [αυτον]{.greek-omitted} υπο [τον]{.greek-omitted} [το]{.greek-added} μοδιον αλλ επι την λυχνιαν και λαμπει [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις εν τη οικια[5:15]{.aside}

ουτως λαμψατω το φως υμων εμπροσθεν των ανθρωπων οπως ιδωσιν υμων τα καλα εργα και [δοξασωσιν]{.greek-omitted} [δοξασωσι]{.greek-added} τον πατερα υμων τον εν τοις ουρανοις[5:16]{.aside}

μη νομισητε οτι ηλθον καταλυσαι τον νομον η τους προφητας ουκ ηλθον καταλυσαι αλλα πληρωσαι[5:17]{.aside}

αμην γαρ λεγω υμιν εως αν παρελθη ο ουρανος και η γη ιωτα εν η μια κεραια ου μη παρελθη [απο]{.greek-omitted} [εκ]{.greek-added} του νομου εως αν παντα γενηται[5:18]{.aside}

ος εαν ουν λυση μιαν των εντολων τουτων των ελαχιστων και διδαξη ουτως τους ανθρωπους ελαχιστος κληθησεται εν τη βασιλεια των ουρανων ος δ αν ποιηση και διδαξη ουτος μεγας κληθησεται εν τη βασιλεια των ουρανων[5:19]{.aside}

λεγω γαρ υμιν οτι εαν μη περισσευση η δικαιοσυνη υμων πλειον των γραμματεων και φαρισαιων ου μη εισελθητε εις την βασιλειαν των ουρανων[5:20]{.aside}

ηκουσατε οτι ερρεθη τοις αρχαιοις ου φονευσεις ος δ αν φονευση ενοχος εσται τη κρισει[5:21]{.aside}

εγω δε λεγω υμιν οτι πας ο οργιζομενος τω αδελφω αυτου εικη ενοχος εσται τη κρισει [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [ειπη]{.greek-omitted} [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [αυτου]{.greek-omitted} [ρακα]{.greek-omitted} [ενοχος]{.greek-omitted} [εσται]{.greek-omitted} [τω]{.greek-omitted} [συνεδριω]{.greek-omitted} [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [ειπη]{.greek-omitted} [μωρε]{.greek-omitted} [ενοχος]{.greek-omitted} [εσται]{.greek-omitted} [εις]{.greek-omitted} [την]{.greek-omitted} [γεενναν]{.greek-omitted} [του]{.greek-omitted} [πυρος]{.greek-omitted}[5:22]{.aside}

[εγω]{.greek-omitted} [δε]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [πας]{.greek-omitted} [ο]{.greek-omitted} [οργιζομενος]{.greek-omitted} [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [αυτου]{.greek-omitted} [εικη]{.greek-omitted} [ενοχος]{.greek-omitted} [εσται]{.greek-omitted} [τη]{.greek-omitted} [κρισει]{.greek-omitted} ος δ αν ειπη τω αδελφω αυτου ρακα ενοχος εσται τω συνεδριω ος δ αν ειπη μωρε ενοχος εσται εις την γεενναν του πυρος[5:22 | instance no. 2]{.aside}

εαν ουν προσφερης το δωρον σου επι το θυσιαστηριον [και]{.greek-omitted} [κακει]{.greek-added} [εκει]{.greek-omitted} μνησθης οτι ο αδελφος σου εχει τι κατα σου[5:23]{.aside}

αφες εκει το δωρον σου εμπροσθεν του θυσιαστηριου και [υπαγε]{.greek-omitted} [απελθε]{.greek-added} πρωτον διαλλαγηθι τω αδελφω σου και τοτε ελθων προσφερε το δωρον σου[5:24]{.aside}

ισθι ευνοων τω αντιδικω σου ταχυ εως οτου ει εν τη οδω μετ αυτου μηποτε σε παραδω ο αντιδικος τω κριτη και ο κριτης σε παραδω τω υπηρετη και εις φυλακην βληθηση[5:25]{.aside}

αμην λεγω σοι ου μη εξελθης εκειθεν εως αν αποδως τον εσχατον κοδραντην[5:26]{.aside}

ηκουσατε οτι ερρεθη ου μοιχευσεις[5:27]{.aside}

εγω δε λεγω υμιν οτι πας ο [βλεπων]{.greek-omitted} [εμβλεπων]{.greek-added} γυναικα προς το επιθυμησαι [αυτην]{.greek-omitted} [αυτης]{.greek-added} ηδη εμοιχευσεν αυτην εν τη καρδια αυτου[5:28]{.aside}

[εαν]{.greek-added} [ει]{.greek-omitted} [δε]{.greek-omitted} ο οφθαλμος σου ο δεξιος [σκανδαλιζει]{.greek-omitted} [σκανδαλιζη]{.greek-added} σε [εξελε]{.greek-omitted} [εκκοψον]{.greek-added} αυτον και βαλε απο σου συμφερει [γαρ]{.greek-omitted} σοι ινα [αποληται]{.greek-omitted} [απολυται]{.greek-added} εν των μελων σου και μη ολον το σωμα σου βληθη εις γεενναν[5:29]{.aside}

ερρεθη δε οτι ος αν απολυση την γυναικα αυτου δοτω αυτη αποστασιον[5:31]{.aside}

εγω δε λεγω υμιν οτι [ος]{.greek-omitted} [αν]{.greek-omitted} [απολυση]{.greek-omitted} [πας]{.greek-added} [ο]{.greek-added} [απολυων]{.greek-added} την γυναικα αυτου παρεκτος λογου πορνειας ποιει αυτην μοιχασθαι και ος [εαν]{.greek-omitted} [αν]{.greek-added} απολελυμενην γαμηση μοιχαται[5:32]{.aside}

παλιν ηκουσατε οτι ερρεθη τοις αρχαιοις ουκ επιορκησεις αποδωσεις δε τω κυριω τους ορκους σου[5:33]{.aside}

εγω δε λεγω υμιν μη [ομοσαι]{.greek-omitted} [ομωσαι]{.greek-added} ολως μητε εν τω ουρανω οτι θρονος [εστιν]{.greek-omitted} [εστι]{.greek-added} του θεου[5:34]{.aside}

μητε εν τη γη οτι υποποδιον [εστιν]{.greek-omitted} [εστι]{.greek-added} των ποδων αυτου μητε εις ιεροσολυμα οτι πολις [εστιν]{.greek-omitted} [εστι]{.greek-added} του μεγαλου βασιλεως[5:35]{.aside}

μητε εν τη κεφαλη σου ομοσης οτι ου δυνασαι μιαν τριχα λευκην η μελαιναν ποιησαι[5:36]{.aside}

εστω δε ο λογος υμων ναι ναι ου ου το δε περισσον τουτων εκ του πονηρου [εστιν]{.greek-omitted} [εστι]{.greek-added}[5:37]{.aside}

ηκουσατε οτι ερρεθη οφθαλμον αντι οφθαλμου και οδοντα αντι οδοντος[5:38]{.aside}

εγω δε λεγω υμιν μη αντιστηναι τω πονηρω αλλ οστις σε ραπισει [επι]{.greek-omitted} [εις]{.greek-added} την δεξιαν σιαγονα στρεψον αυτω και την αλλην[5:39]{.aside}

και τω θελοντι σοι κριθηναι και τον χιτωνα σου λαβειν αφες αυτω και το ιματιον[5:40]{.aside}

και οστις σε αγγαρευσει μιλιον εν υπαγε μετ αυτου δυο[5:41]{.aside}

τω αιτουντι σε διδου και [τον]{.greek-omitted} [τω]{.greek-added} [θελοντα]{.greek-omitted} [θελοντι]{.greek-added} απο σου δανεισασθαι μη αποστραφης[5:42]{.aside}

ηκουσατε οτι ερρεθη αγαπησεις τον πλησιον σου και μισησεις τον εχθρον σου[5:43]{.aside}

εγω δε λεγω υμιν αγαπατε τους εχθρους υμων ευλογειτε τους καταρωμενους υμας [καλως]{.greek-omitted} [ποιειτε]{.greek-omitted} [τοις]{.greek-omitted} [μισουσιν]{.greek-omitted} [υμας]{.greek-omitted} και προσευχεσθε υπερ των επηρεαζοντω[ν]{.unclear} υμας και διωκοντων υμας[5:44]{.aside}

οπως γενησθε υιοι του πατρος υμων του εν τοις ουρανοις οτι τον ηλιον αυτου ανατελλει επι πονηρους και αγαθους και βρεχει επι δικαιους και αδικους[5:45]{.aside}

εαν [γαρ]{.greek-omitted} αγαπησητε [φησι]{.greek-added} τους αγαπωντας υμας τινα μισθον εχετε ουχι και οι τελωναι το αυτο ποιουσιν[5:46]{.aside}

και εαν ασπασησθε τους φιλους υμων μονον τι περισσον ποιειτε ουχι και οι τελωναι [ουτως]{.greek-omitted} [ουτω]{.greek-added} ποιουσιν[5:47]{.aside}

εσεσθε ουν υμεις τελειοι ωσπερ [και]{.greek-added} ο πατηρ υμων ο εν τοις ουρανοις τελειος εστιν[5:48]{.aside}

### Chapter 6

προσεχετε την ελεημοσυνην υμων μη ποιειν εμπροσθεν των ανθρωπων προς το θεαθηναι αυτοις ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} μισθον ουκ εχετε παρα τω πατρι υμων τω εν τοις ουρανοις[6:1]{.aside}

οταν ουν ποιης ελεημοσυνην μη σαλπισης εμπροσθεν σου ωσπερ οι υποκριται ποιουσιν εν ταις συναγωγαις και εν ταις ρυμαις [οπως]{.greek-omitted} [δοξασθωσιν]{.greek-omitted} [υπο]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} αμην λεγω υμιν [οτι]{.greek-added} [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:2]{.aside}

σου δε ποιουντος ελεημοσυνην μη γνωτω η αριστερα σου τι ποιει η δεξια σου[6:3]{.aside}

οπως η σου η ελεημοσυνη εν τω κρυπτω και ο [πατηρ]{.greek-omitted} [πατερ]{.greek-added} σου ο βλεπων εν τω κρυπτω [αυτος]{.greek-omitted} αποδωσει σοι εν τω φανερω[6:4]{.aside}

και οταν προσευχη ουκ εση ωσπερ οι υποκριται [σκυθρωποι]{.greek-added} οτι φιλουσιν εν ταις συναγωγαις και εν ταις γωνιαις των πλατειων εστωτες προσευχεσθαι οπως αν [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις ανθρωποις αμην λεγω υμιν οτι [απεχουσιν]{.greek-omitted} [απεχουσι]{.greek-added} τον μισθον αυτων[6:5]{.aside}

συ δε οταν προσευχη εισελθε εις το [ταμιειον]{.greek-omitted} [ταμειον]{.greek-added} σου και κλεισας την θυραν σου προσευξαι τω πατρι σου τω εν τω κρυπτω και ο πατηρ σου ο βλεπων εν τω κρυπτω αποδωσει σοι εν τω φανερω[6:6]{.aside}

προσευχομενοι δε μη [βαττολογησητε]{.greek-omitted} [βατολογησητε]{.greek-added} ωσπερ οι εθνικοι [δοκουσιν]{.greek-omitted} [γαρ]{.greek-omitted} [οτι]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [πολυλογια]{.greek-omitted} [αυτων]{.greek-omitted} [εισακουσθησονται]{.greek-omitted}[6:7]{.aside}

[προσευχομενοι]{.greek-omitted} [δε]{.greek-omitted} [μη]{.greek-omitted} [βαττολογησητε]{.greek-omitted} [ωσπερ]{.greek-omitted} [οι]{.greek-omitted} [εθνικοι]{.greek-omitted} [δοκουσιν]{.greek-omitted} [δοκουσι]{.greek-added} γαρ οτι εν τη πολυλογια αυτων εισακουσθησονται[6:7 | instance no. 2]{.aside}

[ειδε]{.greek-added} [μη]{.greek-omitted} [ουν]{.greek-omitted} [ομοιωθητε]{.greek-omitted} [αυτοις]{.greek-omitted} [οιδεν]{.greek-omitted} γαρ ο πατηρ υμων [ων]{.greek-omitted} [χρειαν]{.greek-omitted} [εχετε]{.greek-omitted} προ του υμας αιτησαι αυτον [ων]{.greek-added} [χρειαν]{.greek-added} [εχετε]{.greek-added}[6:8]{.aside}

ουτως ουν προσευχεσθε [υμεις]{.greek-omitted} πατερ ημων ο εν τοις ουρανοις αγιασθητω το ονομα σου[6:9]{.aside}

ελθετω η βασιλεια σου γενηθητω το θελημα σου ως εν ουρανω και επι της γης[6:10]{.aside}

τον αρτον ημων τον επιουσιον δος ημιν σημερον[6:11]{.aside}

και αφες ημιν τα οφειληματα ημων ως και ημεις αφιεμεν τοις οφειλεταις ημων[6:12]{.aside}

και μη εισενεγκης ημας εις πειρασμον αλλα ρυσαι ημας απο του πονηρου οτι σου εστιν η βασιλεια και η δυναμις και η δοξα εις τους αιωνας αμην[6:13]{.aside}

εαν [γαρ]{.greek-omitted} [αφητε]{.greek-omitted} [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted} [τα]{.greek-omitted} [παραπτωματα]{.greek-omitted} [αυτων]{.greek-omitted} [αφησει]{.greek-omitted} [και]{.greek-omitted} [υμιν]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [ουρανιος]{.greek-omitted}[6:14]{.aside}

[γαρ]{.greek-added} [εαν]{.greek-omitted} [δε]{.greek-omitted} μη αφητε τοις ανθρωποις τα παραπτωματα αυτων ουδε ο πατηρ υμων αφησει τα παραπτωματα υμων[6:15]{.aside}

οταν δε νηστευητε μη γινεσθε ωσπερ οι υποκριται σκυθρωποι [αφανιζουσιν]{.greek-omitted} [αφανιζουσι]{.greek-added} γαρ τα προσωπα αυτων οπως [φανωσιν]{.greek-omitted} [φανωσι]{.greek-added} τοις ανθρωποις νηστευοντες [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} [οτι]{.greek-omitted} [απεχουσιν]{.greek-omitted} [τον]{.greek-omitted} [μισθον]{.greek-omitted} [αυτων]{.greek-omitted}[6:16]{.aside}

συ δε νηστευων αλειψαι σου την κεφαλην και το προσωπον σου νιψαι[6:17]{.aside}

οπως μη φανης τοις ανθρωποις νηστευων αλλα τω πατρι σου τω εν τω κρυπτω [και]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [σου]{.greek-omitted} [ο]{.greek-omitted} [βλεπων]{.greek-omitted} [εν]{.greek-omitted} [τω]{.greek-omitted} [κρυπτω]{.greek-omitted} [αποδωσει]{.greek-omitted} [σοι]{.greek-omitted}[6:18]{.aside}

μη θησαυριζετε υμιν θησαυρους επι της γης οπου σης και βρωσις αφανιζει και οπου κλεπται [διορυσσουσιν]{.greek-omitted} [διορυσσουσι]{.greek-added} και [κλεπτουσιν]{.greek-omitted} [κλεπτουσι]{.greek-added}[6:19]{.aside}

θησαυριζετε δε υμιν θησαυρους εν [ουρανω]{.greek-omitted} [ουρανοις]{.greek-added} οπου ουτε σης ουτε βρωσις αφανιζει και οπου κλεπται ου διορυσσουσιν ουδε κλεπτουσιν[6:20]{.aside}

ο λυχνος του σωματος εστιν ο οφθαλμος εαν ουν ο οφθαλμος σου απλους η ολον το σωμα σου φωτεινον εσται[6:22]{.aside}

εαν δε ο οφθαλμος σου πονηρος η ολον το σωμα σου σκοτεινον εσται ει ουν το φως το εν σοι σκοτος [εστιν]{.greek-omitted} [εστι]{.greek-added} το σκοτος ποσον[6:23]{.aside}

ουδεις δυναται [δυσιν]{.greek-omitted} [δυσι]{.greek-added} κυριοις δουλευειν η γαρ τον ενα μισησει και τον ετερον αγαπησει η [του]{.greek-added} ενος ανθεξεται και του ετερου καταφρονησει ου δυνασθε θεω δουλευειν και [μαμωνα]{.greek-omitted} [μαμμωνα]{.greek-added}[6:24]{.aside}

δια τουτο λεγω υμιν μη μεριμνατε τη ψυχη υμων τι φαγητε και τι πιητε μηδε τω σωματι υμων τι ενδυσησθε ουχι η ψυχη πλειον [εστιν]{.greek-omitted} [εστι]{.greek-added} της τροφης και το σωμα του ενδυματος[6:25]{.aside}

εμβλεψατε εις τα πετεινα του ουρανου οτι ου σπειρουσιν [ουδε]{.greek-omitted} [θεριζουσιν]{.greek-omitted} ουδε συναγουσιν εις αποθηκας και ο πατηρ υμων ο ουρανιος τρεφει αυτα ουχ υμεις μαλλον διαφερετε αυτων[6:26]{.aside}

τις δε εξ υμων μεριμνων δυναται προσθειναι επι την ηλικιαν αυτου πηχυν ενα[6:27]{.aside}

και περι ενδυματος τι μεριμνατε καταμαθετε τα κρινα του αγρου πως αυξανει ου κοπια ουδε νηθει[6:28]{.aside}

λεγω δε υμιν οτι ουδε σολομων εν παση τη δοξη αυτου περιεβαλετο ως εν τουτων[6:29]{.aside}

ει δε τον χορτον του αγρου σημερον οντα και αυριον εις κλιβανον βαλλομενον ο θεος ουτως αμφιεννυσιν ου πολλω μαλλον υμας ολιγοπιστοι[6:30]{.aside}

μη ουν μεριμνησητε λεγοντες τι φαγωμεν η τι πιωμεν η τι περιβαλωμεθα[6:31]{.aside}

[ταυτα]{.greek-added} [γαρ]{.greek-added} παντα [γαρ]{.greek-omitted} [ταυτα]{.greek-omitted} τα εθνη επιζητει [οιδεν]{.greek-omitted} [οιδε]{.greek-added} γαρ ο πατηρ υμων ο ουρανιος οτι χρηζετε [τουτων]{.greek-omitted} [απαντων]{.greek-omitted}[6:32]{.aside}

[παντα]{.greek-omitted} [γαρ]{.greek-omitted} [ταυτα]{.greek-omitted} [τα]{.greek-omitted} [εθνη]{.greek-omitted} [επιζητει]{.greek-omitted} [οιδεν]{.greek-omitted} [γαρ]{.greek-omitted} [ο]{.greek-omitted} [πατηρ]{.greek-omitted} [υμων]{.greek-omitted} [ο]{.greek-omitted} [ουρανιος]{.greek-omitted} [οτι]{.greek-omitted} [χρηζετε]{.greek-omitted} τουτων απαντων[6:32 | instance no. 2]{.aside}

ζητειτε δε πρωτον την βασιλειαν του θεου και την δικαιοσυνην αυτου και ταυτα παντα προστεθησεται υμιν[6:33]{.aside}

μη ου[ν]{.unclear} μεριμνησητε εις την αυριον η γαρ αυριον μεριμνησ[ει]{.greek-supplied} [τα]{.greek-omitted} [εαυ]{.unclear}της αρκετον τη ημερα η κακια αυτης[6:34]{.aside}

### Chapter 7

μη κριν[ε]{.unclear}τε ινα μη κριθητε[7:1]{.aside}

εν ω γαρ κριματι κρινετε κριθησεσθε και εν ω μετρω μετρειτε μετρηθησεται υμιν[7:2]{.aside}

τι δε βλεπεις το καρφος το εν τω οφθαλμω του αδελφου σου την δε εν τω σω οφθαλμω δοκον ου κατανοεις[7:3]{.aside}

η πως ερεις τω αδελφω σου αφες εκβαλω το καρφος απο του οφθαλμου σου και ιδου η δοκος εν τω οφθαλμω σου[7:4]{.aside}

υποκριτα εκβαλε πρωτον την δοκον εκ του οφθαλμου σου και τοτε διαβλεψεις εκβαλειν το καρφος εκ του οφθαλμου του αδελφου σου[7:5]{.aside}

μη δωτε το αγιον τοις [κυσιν]{.greek-omitted} [κυσι]{.greek-added} μηδε βαλητε τους μαργαριτας υμων εμπροσθεν των χοιρων μηποτε καταπατησωσιν αυτους εν τοις ποσιν αυτων και στραφεντες ρηξωσιν υμας[7:6]{.aside}

[αι]{.unclear}τειτ[ε]{.unclear} και [δ]{.unclear}οθησεται υμιν [ζητειτε]{.greek-omitted} [και]{.greek-omitted} [ευρησετε]{.greek-omitted} κρουετε και ανοιγησεται υμιν[7:7]{.aside}

πας γαρ ο αιτων λαμβανει και ο ζητων ευρισκει και τω κρουοντι ανοιγησεται[7:8]{.aside}

η τις εστιν εξ υμων ανθρωπος ον εαν αιτηση ο υιος αυτου αρτον μη λιθον επιδωσει αυτω[7:9]{.aside}

και εαν ιχθυν αιτηση μη οφιν [επιδωσει]{.greek-omitted} [επιδωδωσει]{.greek-added} αυτω[7:10]{.aside}

ει ουν υμεις πονηροι οντες οιδατε δοματα αγαθα διδοναι τοις τεκνοις υμων ποσω μαλλον ο πατηρ υμων ο εν τοις ουρανοις δωσει αγαθα τοις αιτουσιν αυτον[7:11]{.aside}

παντα ουν οσα αν θελητε ινα ποιωσιν υμιν οι ανθρωποι [ουτως]{.greek-omitted} και υμεις ποιειτε αυτοις [ουτος]{.greek-omitted} [ουτως]{.greek-added} γαρ εστιν ο νομος και οι προφηται[7:12]{.aside}

εισελθετε δια της στενης πυλης οτι πλατεια η πυλη και ευρυχωρος η οδος η απαγουσα εις την απωλειαν και πολλοι εισιν οι εισερχομενοι δι αυτης[7:13]{.aside}

τι στενη η πυλη και τεθλιμμενη η οδος η απαγουσα εις την ζωην και ολιγοι εισιν οι ευρισκοντες αυτην[7:14]{.aside}

προσεχετε δε απο των ψευδοπροφητων οιτινες ερχονται προς υμας εν [ενδυμασιν]{.greek-omitted} [ενδυμασι]{.greek-added} [προβατων]{.greek-omitted} [προβατου]{.greek-added} εσωθεν δε [εισιν]{.greek-omitted} [εισι]{.greek-added} λυκοι αρπαγες[7:15]{.aside}

απο των καρπων αυτων επιγνωσεσθε αυτους μητι συλλεγουσιν απο ακανθων σταφυλην η απο τριβολων συκα[7:16]{.aside}

ουτως παν δενδρον αγαθον καρπους καλους ποιει το δε σαπρον δενδρον καρπους πονηρους ποιει[7:17]{.aside}

ου δυναται δενδρον αγαθον καρπους πονηρους ποιειν ουδε δενδρον σαπρον καρπους καλους ποιειν[7:18]{.aside}

παν δενδρον μη ποιουν καρπον καλον εκκοπτεται και εις πυρ βαλλεται[7:19]{.aside}

αρα γε απο των καρπων αυτων επιγνωσεσθε αυτους[7:20]{.aside}

ου πας ο λεγων μοι κυριε κυριε εισελευσεται εις την βασιλειαν των ουρανων αλλ ο ποιων το θελημα του πατρος μου του εν ουρανοις[7:21]{.aside}

πολλοι [ερουσιν]{.greek-omitted} [ερουσι]{.greek-added} μοι εν εκεινη τη ημερα κυριε κυριε ου τω σω ονοματι προεφητευσαμεν και τω σω ονοματι δαιμονια [εξεβαλομεν]{.greek-omitted} [εξεβαλλομεν]{.greek-added} και τω σω ονοματι δυναμεις πολλας εποιησαμεν[7:22]{.aside}

και τοτε ομολογησω αυτοις οτι ουδεποτε εγνων [υ]{.unclear}μας αποχωρειτε απ εμου οι εργαζομενοι την ανομιαν[7:23]{.aside}

πας ουν οστις ακουει μου τους λογους [τουτους]{.greek-omitted} και ποιει αυτους ομοιωσω αυτον ανδρι φρονιμω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την πετραν[7:24]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και προσεπεσον τη οικια εκεινη και ουκ [επεσεν]{.greek-omitted} [επεσε]{.greek-added} τεθεμελιωτο γαρ επι την πετραν[7:25]{.aside}

και πας ο ακουων μου τους λογους τουτους και μη ποιων αυτους ομοιωθησεται ανδρι μωρω οστις [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} την οικιαν αυτου επι την αμμον[7:26]{.aside}

και κατεβη η βροχη και ηλθον οι ποταμοι και επνευσαν οι ανεμοι και [προσεκοψαν]{.greek-omitted} [προσεκρουσαν]{.greek-added} τη οικια εκεινη και [επεσεν]{.greek-omitted} [επεσε]{.greek-added} και ην η πτωσις αυτης μεγαλη[7:27]{.aside}

και εγενετο οτε συνετελεσεν ο ιησους τους λογους τουτους εξεπλησσοντο οι οχλοι επι τη διδαχη αυτου[7:28]{.aside}

ην γαρ διδασκων αυτους ως εξουσιαν εχων και ουχ ως οι γραμματεις[7:29]{.aside}

### Chapter 8

καταβαντι δε αυτω απο του ορους ηκολουθησαν αυτω οχλοι πολλοι[8:1]{.aside}

και ιδου λεπρος ελθων προσεκυνει αυτω λεγων κυριε εαν θελης δυνασαι με καθαρισαι[8:2]{.aside}

[και]{.greek-omitted} εκτεινας την χειρα ηψατο αυτου [ο]{.greek-omitted} [ιησους]{.greek-omitted} λεγων θελω καθαρισθητι και ευθεως εκαθαρισθη αυτου η λεπρα[8:3]{.aside}

και λεγει αυτω ο ιησους ορα μηδενι ειπης [αλλα]{.greek-omitted} [αλλ]{.greek-added} υπαγε σεαυτον δειξον τω ιερει και προσενεγκε το δωρον ο [προσεταξεν]{.greek-omitted} [προσεταξε]{.greek-added} [μωσης]{.greek-omitted} [μωυσης]{.greek-added} εις μαρτυριον αυτοις[8:4]{.aside}

