---
title: "Collation of Byz^RP^ vs 32597 (2597)"
author: ""
date: ""
toc: true
toc-title: Contents
---

::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Links to official texts

Read 2597 in the INTF website [here](https://ntvmr.uni-muenster.de/manuscript-workspace?docID=32597).

Download the Robinson-Pierpont 2018 edition of the Byzantine textform [here](https://web.archive.org/web/20210413060536/https://byzantinetext.com/wp-content/uploads/2021/03/robinson-pierpont-2018-gnt-edition.pdf).


:::


::: {.callout-note appearance="minimal" icon="false" collapse="true"}
# Conventions

| Description                                                              	| Examples                           	|
|--------------------------------------------------------------------------	|------------------------------------	|
| Word in both Byz^RP^ and 2597                                   	| λογος                              	|
| 2597 *adds* (word not present in Byz^RP^)                       	| [λογος]{.greek-added}            	|
| 2597 *omits* (word present in Byz^RP^)                          	| [λογος]{.greek-omitted}          	|
| Text fragmentary, supplied by transcriber of 2597               	| [λογος]{.greek-supplied}         	|
| Text unclear, supplied by transcriber of 2597                   	| [λογος]{.unclear}                	|
| Corrector's hand is superscript (corrector agrees with Byz^RP^)          	| [λογος]{.corr}                   	|
| Corrector's hand is superscript (corrector adds, not present in Byz^RP^) 	| [[λογος]{.corr}]{.greek-added} 	|
| 2597 abbreviates *nomen sacrum*                                 	| [θεος]{.greek-abbr}            	|
| Gap in 2597                                                     	| [―]{.gap}                        	|
:::

## The Gospel of Matthew

### Chapter 1

[β]{.greek-supplied}ιβλος γενεσεως [ιησου]{.greek-abbr} [χριστου]{.greek-abbr} υιου [δαυιδ]{.greek-abbr} υιου αβρααμ[1:1]{.aside}

αβρααμ [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ισαακ ισαακ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ιουδαν]{.greek-omitted} [ιουδα]{.greek-added} και τους αδελφους αυτου[1:2]{.aside}

[ι]{.greek-supplied}ουδας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον φαρες και τον ζαρα εκ της θαμαρ [φ]{.greek-supplied}αρες δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εσρωμ εσρωμ δε [εγεννησεν]{.greek-omitted} [εγεννη[σε]{.unclear}]{.greek-added} τον αραμ[1:3]{.aside}

αραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [αμ]{.unclear}ιναδαβ αμιναδαβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ναασσων ναασσων δε [εγεννησεν]{.greek-omitted} [εγ[ε]{.unclear}ννησε]{.greek-added} τον σαλμων[1:4]{.aside}

σαλμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον βοοζ εκ της ραχαβ [β]{.greek-supplied}οοζ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ωβηδ]{.greek-omitted} [οβηδ]{.greek-added} εκ της ρουθ [ωβηδ]{.greek-omitted} [[ο]{.greek-supplied}βηδ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [ιεσσαι]{.greek-omitted} [ιεσαι]{.greek-added}[1:5]{.aside}

[ιεσσαι]{.greek-omitted} [ιεσαι]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [δαυιδ]{.greek-abbr} τον βασιλεα [δαυιδ]{.greek-abbr} δε ο βασιλευς [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [σολομωνα]{.greek-omitted} [σολομονα]{.greek-added} εκ της του ουριου[1:6]{.aside}

[σ]{.greek-supplied}ολομων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ροβοαμ ροβοαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αβια αβια δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ασα[1:7]{.aside}

ασα δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσαφατ ιωσαφατ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωραμ ιωραμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον οζιαν[1:8]{.aside}

οζιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωαθαμ ιωαθαμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον [αχαζ]{.greek-omitted} [αχατζ]{.greek-added} [αχαζ]{.greek-omitted} [αχατζ]{.greek-added} δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον εζεκιαν[1:9]{.aside}

εζεκιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον μανασση μανασσης δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αμων αμων δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσιαν[1:10]{.aside}

ιωσιας δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιεχονιαν και τους αδελφους αυτου επι της μετοικεσιας βαβυλωνος[1:11]{.aside}

[μ]{.greek-supplied}ετα δε την μετοικεσιαν βαβυλωνος ιεχονιας [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαλαθιηλ σαλαθιηλ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ζοροβαβελ[1:12]{.aside}

ζοροβαβελ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [αβιουδ]{.greek-omitted} [αβιουδ]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} τον ελιακειμ ελιακειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αζωρ[1:13]{.aside}

αζωρ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον σαδωκ σαδωκ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον αχειμ αχειμ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ελιουδ[1:14]{.aside}

ελιουδ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} [τον]{.greek-omitted} [ελεαζαρ]{.greek-omitted} [ελεαζαρ]{.greek-omitted} [δε]{.greek-omitted} [εγεννησεν]{.greek-omitted} τον ματθαν ματθαν δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιακωβ[1:15]{.aside}

ιακωβ δε [εγεννησεν]{.greek-omitted} [εγεννησε]{.greek-added} τον ιωσηφ τον ανδρα μαριας εξ ης εγεννηθη [ιησους]{.greek-omitted} ο λεγομενος [χριστος]{.greek-abbr}[1:16]{.aside}

[π]{.greek-supplied}ασαι ουν αι γενεαι απο αβρααμ εως [δαυιδ]{.greek-abbr} γενεαι [δεκατεσσαρες]{.greek-omitted} [[ιδ]{.greek-abbr}]{.greek-added} και απο [δαυιδ]{.greek-abbr} εως της μετοικεσιας βαβυλωνος γενεαι [δεκατεσσαρες]{.greek-omitted} [[ιδ]{.greek-abbr}]{.greek-added} και απο της μετοικεσιας βαβυλωνος εως του [χριστου]{.greek-abbr} γενεαι [δεκατεσσαρες]{.greek-omitted} [[ιδ]{.greek-abbr}]{.greek-added}[1:17]{.aside}

[τ]{.greek-supplied}ου δε [ιησου]{.greek-abbr} [χριστου]{.greek-omitted} η γεννησις ουτως ην μνηστευθεισης [γαρ]{.greek-omitted} της [μητρος]{.greek-abbr} αυτου μαριας τω ιωσηφ πριν [η]{.greek-omitted} [συνελθειν]{.greek-omitted} [εισελθειν]{.greek-added} αυτους ευρεθη εν γαστρι εχουσα εκ [πνευματος]{.greek-abbr} αγιου[1:18]{.aside}

[ι]{.greek-supplied}ωσηφ δε ο ανηρ αυτης δικαιος ων και μη θελων [αυτην]{.greek-omitted} παραδειγματισαι εβουληθη λαθρα απολυσαι αυτην[1:19]{.aside}

[τ]{.greek-supplied}αυτα δε αυτου ενθυμηθεντος ιδου αγγελος [κυριου]{.greek-abbr} [εφανη]{.greek-added} κατ οναρ [εφανη]{.greek-omitted} [αυτω]{.greek-omitted} [τω]{.greek-added} [ιωσηφ]{.greek-added} λεγων ιωσηφ υιος [δαυιδ]{.greek-abbr} μη [φοβηθης]{.greek-omitted} [φοβηθεις]{.greek-added} παραλαβειν [μαριαμ]{.greek-omitted} [μαριαν]{.greek-added} την γυναικα σου το γαρ εν αυτη γεννηθεν εκ [πνευματος]{.greek-abbr} [αγιου]{.greek-added} εστιν [αγιου]{.greek-omitted}[1:20]{.aside}

τεξεται δε [υιον]{.greek-omitted} και καλεσεις το ονομα αυτου [ιησουν]{.greek-abbr} αυτος γαρ σωσει τον λαον αυτου απο των αμαρτιων αυτων[1:21]{.aside}

[τ]{.greek-supplied}ουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος[1:22]{.aside}

ιδου η παρθενος εν γαστρι εξει και τεξεται υιον και [καλεσουσιν]{.greek-omitted} [καλεσουσι]{.greek-added} το ονομα αυτου εμμανουηλ ο [εστιν]{.greek-omitted} [εστι]{.greek-added} μεθερμηνευομενον μεθ ημων ο [θεος]{.greek-abbr}[1:23]{.aside}

[δ]{.greek-supplied}ιεγερθεις δε ο ιωσηφ απο του υπνου εποιησεν ως προσεταξεν αυτω ο αγγελος [κυριου]{.greek-abbr} και [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} την γυναικα αυτου[1:24]{.aside}

και ουκ εγινωσκεν αυτην εως ου ετεκεν τον υιον αυτης τον πρωτοτοκον και [εκαλεσεν]{.greek-omitted} [εκαλεσε]{.greek-added} το ονομα αυτου [ιησουν]{.greek-abbr}[1:25]{.aside}

### Chapter 2

[τ]{.greek-supplied}ου δε [ιησου]{.greek-abbr} γεννηθεντος εν βηθλεεμ της ιουδαιας [ε]{.greek-supplied}ν ημεραις ηρωδου του βασιλεως [ι]{.greek-supplied}δου μαγοι απο ανατολων παρεγενοντο εις ιεροσολυμα[2:1]{.aside}

[λ]{.greek-supplied}εγοντες που εστιν ο τεχθεις βασιλευς των ιουδαιων [ειδομεν]{.greek-omitted} [[ι]{.greek-supplied}δομεν]{.greek-added} γαρ αυτου τον αστερα εν τη ανατολη και ηλθομεν προσκυνησαι [αυτω]{.greek-omitted} [αυτον]{.greek-added}[2:2]{.aside}

[α]{.greek-supplied}κουσας δε ηρωδης ο βασιλευς εταραχθη και πασα ιεροσολυμα μετ αυτου[2:3]{.aside}

[κ]{.greek-supplied}αι συναγαγων παντας τους αρχιερεις και γραμματεις του λαου [επυνθανετο]{.greek-omitted} [παρ]{.greek-omitted} [αυτων]{.greek-omitted} [που]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-omitted} [γενναται]{.greek-omitted}[2:4]{.aside}

[ο]{.greek-supplied}ι δε ειπον [αυτω]{.greek-omitted} εν βηθλεεμ της ιουδαιας ουτως γαρ γεγραπται δια του προφητου[2:5]{.aside}

και συ βηθλεεμ γη ιουδα ουδαμως [ελαχιστη]{.greek-omitted} [ελαχιστι]{.greek-added} ει εν τοις ηγεμοσιν ιουδα [ε]{.greek-supplied}κ σου γαρ εξελευσεται ηγουμενος [ο]{.greek-supplied}στις ποιμανει τον λαον μου τον [ισραηλ]{.greek-abbr}[2:6]{.aside}

[τ]{.greek-supplied}οτε ηρωδης λαθρα καλεσας τους [τους]{.greek-added} μαγους [ηκριβωσεν]{.greek-omitted} [[η]{.greek-supplied}κριβωσε]{.greek-added} παρ αυτων τον χρονον του φαινομενου αστερος[2:7]{.aside}

[κ]{.greek-supplied}αι πεμψας αυτους εις βηθλεεμ [ειπεν]{.greek-omitted} [ειπε]{.greek-added} πορευθεντες ακριβως εξετασατε περι του παιδιου [ε]{.greek-supplied}παν δε [ευρητε]{.greek-omitted} [ευρησ[αντ]{.unclear}ες]{.greek-added} απαγγειλατε μοι οπως καγω ελθων [προσκυνησω]{.greek-omitted} [προσκυνησαι]{.greek-added} [αυτω]{.greek-omitted} [αυτο]{.greek-added}[2:8]{.aside}

οι δε ακουσαντες [του]{.greek-omitted} [βασιλεως]{.greek-omitted} επορευθησαν [κ]{.greek-supplied}αι ιδου ο αστηρ ον ειδον εν τη ανατολη προηγεν αυτους [ε]{.greek-supplied}ως [ου]{.greek-added} ελθων εστη επανω ου ην το παιδιον[2:9]{.aside}

[ι]{.greek-supplied}δοντες δε τον αστερα εχαρησαν χαραν μεγαλην σφοδρα[2:10]{.aside}

[κ]{.greek-supplied}αι [ελθοντες]{.greek-omitted} [ελθον]{.greek-added} εις την οικιαν [ειδον]{.greek-omitted} [ιδον]{.greek-added} το παιδιον μετα μαριας της [μητρος]{.greek-abbr} αυτου [κ]{.greek-supplied}αι πεσοντες προσεκυνησαν [αυτω]{.greek-omitted} [αυτον]{.greek-added} [κ]{.greek-supplied}αι ανοιξαντες τους θησαυρους αυτων προσηνεγκαν αυτω [δωρα]{.greek-omitted} χρυσον και λιβανον και σμυρναν[2:11]{.aside}

[κ]{.greek-supplied}αι χρηματισθεντες κατ οναρ μη ανακαμψαι προς ηρωδην δι αλλης οδου ανεχωρησαν εις την χωραν αυτων[2:12]{.aside}

[α]{.greek-supplied}ναχωρησαντων [δε]{.greek-omitted} [αυτων]{.greek-omitted} [των]{.greek-added} [μαγων]{.greek-added} ιδου αγγελος [κυριου]{.greek-abbr} φαινεται κατ οναρ τω ιωσηφ λεγων εγερθεις παραλαβε το παιδιον και την [μητερα]{.greek-abbr} αυτου και φευγε εις αιγυπτον και ισθι εκει εως αν ειπω σοι μελλει γαρ ηρωδης ζητειν το παιδιον του απολεσαι αυτο[2:13]{.aside}

[ο]{.greek-supplied} δε εγερθεις [παρελαβεν]{.greek-omitted} [παρελαβε]{.greek-added} το παιδιον και την [μητερα]{.greek-abbr} αυτου νυκτος και ανεχωρησεν εις αιγυπτον[2:14]{.aside}

και ην εκει εως της τελευτης ηρωδου ινα πληρωθη το ρηθεν υπο του [κυριου]{.greek-abbr} δια του προφητου λεγοντος εξ αιγυπτου εκαλεσα τον υιον μου[2:15]{.aside}

[τ]{.greek-supplied}οτε ηρωδης ιδων οτι ενεπαιχθη υπο των μαγων εθυμωθη λιαν και αποστειλας [ανειλεν]{.greek-omitted} [ανειλε]{.greek-added} παντας τους παιδας τους εν βηθλεεμ [και]{.greek-omitted} [εν]{.greek-omitted} [πασιν]{.greek-omitted} [τοις]{.greek-omitted} [οριοις]{.greek-omitted} [αυτης]{.greek-omitted} απο διετους και [κατωτερω]{.greek-omitted} [κατωτερους]{.greek-added} κατα τον χρονον ον [ηκριβωσεν]{.greek-omitted} [ηκριβωσε]{.greek-added} παρα των μαγων[2:16]{.aside}

[τ]{.greek-supplied}οτε επληρωθη το ρηθεν [υπο]{.greek-omitted} [δια]{.greek-added} ιερεμιου του προφητου λεγοντος[2:17]{.aside}

φωνη εν ραμα ηκουσθη θρηνος και κλαυθμος και οδυρμος πολυς ραχηλ κλαιουσα τα τεκνα αυτης και ουκ [ηθελεν]{.greek-omitted} [ηθελε]{.greek-added} παρακληθηναι οτι ουκ [εισιν]{.greek-omitted} [εισι]{.greek-added}[2:18]{.aside}

### Chapter 9

[ι]{.greek-supplied}να δε [ειδητε]{.greek-omitted} [ιδητε]{.greek-added} ο[τι]{.greek-supplied} εξουσιαν εχει ο υιος του [ανθρωπου]{.greek-abbr} [επι]{.greek-omitted} [της]{.greek-omitted} [γης]{.greek-omitted} [α]{.greek-supplied}φιεναι αμαρτιας τοτε λεγει τω παραλυτικω εγερθεις αρον σου την κλινην και υπαγε εις τον οικον σου[9:6]{.aside}

και εγερθεις απηλθεν εις τον οικον αυτου[9:7]{.aside}

ιδοντες δε οι οχλοι [το]{.greek-added} [σημειον]{.greek-added} εθαυμασαν και εδοξασαν τον [θεον]{.greek-abbr} τον δοντα εξουσιαν τοιαυτην τοις [ανθρωποις]{.greek-abbr}[9:8]{.aside}

[κ]{.greek-supplied}αι παραγων ο [ιησους]{.greek-abbr} εκειθεν ειδεν [ανθρωπον]{.greek-abbr} καθημενον επι το τελωνιον ματθαιον λεγομενον και λεγει αυτω ακολουθει μοι και αναστας [ηκολουθησεν]{.greek-omitted} [ηκολουθησε]{.greek-added} αυτω[9:9]{.aside}

[κ]{.greek-supplied}αι εγενετο αυτου ανακειμενου εν τη [οικια]{.greek-omitted} [οικεια]{.greek-added} και ιδου [πολλοι]{.greek-omitted} τελωναι και αμαρτωλοι ελθοντες συνανεκειντο τω [ιησου]{.greek-abbr} και τοις μαθηταις αυτου[9:10]{.aside}

και ιδοντες οι φαρισαιοι ειπον τοις μαθηταις αυτου δια τι μετα των τελωνων και αμαρτωλων εσθιει ο διδασκαλος υμων[9:11]{.aside}

[ο]{.greek-supplied} δε [ιησους]{.greek-abbr} ακουσας ειπεν αυτοις ου χρειαν εχουσιν οι ισχυοντες ιατρου αλλ οι κακως εχοντες[9:12]{.aside}

πορευθεντες δε μαθετε τι εστιν [ελεον]{.greek-omitted} [ελαιον]{.greek-added} θελω και ου θυσιαν ου γαρ ηλθον καλεσαι δικαιους [αλλα]{.greek-omitted} [αλλ]{.greek-added} αμαρτωλους εις μετανοιαν[9:13]{.aside}

[τ]{.greek-supplied}οτε προσερχονται [αυτω]{.greek-omitted} οι μαθηται ιωαννου λεγοντες δια τι ημεις και οι φαρισαιοι νηστευομεν πολλα οι δε [σοι]{.greek-added} μαθηται σου ου [νηστευουσιν]{.greek-omitted} [νηστεουσιν]{.greek-added}[9:14]{.aside}

[κ]{.greek-supplied}αι ειπεν αυτοις ο [ιησους]{.greek-abbr} μη δυνανται οι υιοι του νυμφωνος πενθειν εφ οσ[ον]{.greek-supplied} μετ αυτων εστιν ο νυμφιος [ε]{.greek-supplied}λευσονται δε ημεραι οταν [απαρθη]{.greek-omitted} [α[ρ]{.unclear}θη]{.greek-added} απ αυτων ο νυμφιος και τοτε νηστευσουσιν[9:15]{.aside}

[ο]{.greek-supplied}υδεις δε επιβαλλει επιβλημα ρακους αγναφου επι ιματιω παλαιω αιρει γαρ το πληρωμα αυτου απο του ιματιου και χειρον σχισμα γινεται[9:16]{.aside}

ουδε βαλλουσιν οινον νεον εις ασκους παλαιους ει δε [μηγε]{.greek-omitted} [μη]{.greek-added} [γε]{.greek-added} ρηγνυνται οι ασκοι και ο οινος [εκχειται]{.greek-omitted} [εκκεχειται]{.greek-added} και οι ασκοι απολουνται αλλα βαλλουσιν οινον νεον εις ασκους καινους και [αμφοτεροι]{.greek-omitted} [αμφοτερα]{.greek-added} συντηρουνται[9:17]{.aside}

[τ]{.greek-supplied}αυτα [ουν]{.greek-added} [αυτοις]{.greek-added} [λαλουντος]{.greek-added} αυτου [λαλουντος]{.greek-omitted} [αυτοις]{.greek-omitted} ιδου αρχων [εἰσελθὼν]{.greek-added} [εις]{.greek-omitted} [ελθων]{.greek-omitted} προσεκυνει αυτω λεγων οτι η θυγατηρ μου αρτι ετελευτησεν [αλλα]{.greek-omitted} [αλλ]{.greek-added} ελθων επιθες την χειρα [σου]{.greek-omitted} επ αυτην και ζησεται[9:18]{.aside}

και εγερθεις ο [ιησους]{.greek-abbr} [ηκολουθησεν]{.greek-omitted} [ηκολουθη]{.greek-added} αυτω και οι μαθηται αυτου[9:19]{.aside}

[κ]{.greek-supplied}αι ιδου γυνη αιμορροουσα [ετη]{.greek-added} δωδεκα [ετη]{.greek-omitted} προσελθουσα οπισθεν ηψατο του κρασπεδου του ιματιου αυτου[9:20]{.aside}

[ελεγεν]{.greek-omitted} [ελεγε]{.greek-added} γαρ εν εαυτη εαν μονον αψωμαι [του]{.greek-omitted} [ιματιου]{.greek-omitted} [των]{.greek-added} [ιματιων]{.greek-added} αυτου σωθησομαι[9:21]{.aside}

ο δε [ιησους]{.greek-abbr} επιστραφεις και ιδων αυτην [ειπεν]{.greek-omitted} [ειπε]{.greek-added} θαρσει θυγατερ η πιστις σου [σεσωκεν]{.greek-omitted} [σεσωκε]{.greek-added} σε [πορευου]{.greek-added} [εις]{.greek-added} [ειρηνην]{.greek-added} και εσωθη η γυνη απο της ωρας εκεινης[9:22]{.aside}

[κ]{.greek-supplied}αι ελθων ο [ιησους]{.greek-abbr} εις την οικιαν του αρχοντος και ιδων τους αυλητας και τον οχλον θορυβουμενον[9:23]{.aside}

λεγει αυτοις αναχωρειτε ου γαρ [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} το κορασιον αλλα καθευδει και κατεγελων αυτου[9:24]{.aside}

[ο]{.greek-supplied}τε δε εξεβληθη ο οχλος εισελθων [εκρατησεν]{.greek-omitted} [εκρατησε]{.greek-added} της χειρος αυτης και ηγερθη το κορασιον[9:25]{.aside}

και εξηλθεν η φημη [αυτη]{.greek-omitted} [αυτου]{.greek-added} εις ολην την γην εκεινην[9:26]{.aside}

[κ]{.greek-supplied}αι παραγοντι εκειθεν τω [ιησου]{.greek-abbr} ηκολουθησαν αυτω δυο τυφλοι κραζοντες και λεγοντες ελεησον ημας υιε [δαυιδ]{.greek-abbr}[9:27]{.aside}

[ε]{.greek-supplied}λθοντι δε εις [την]{.greek-omitted} οικιαν προσηλθον αυτω οι τυφλοι και λεγει αυτοις [ο]{.greek-omitted} [ιησους]{.greek-omitted} [πιστευετε]{.greek-omitted} [πιστευεται]{.greek-added} οτι δυναμαι τουτο ποιησαι λεγουσιν αυτω ναι [κυριε]{.greek-abbr}[9:28]{.aside}

[τ]{.greek-supplied}οτε ηψατο των οφθαλμων αυτων λεγων κατα την πιστιν [υμων]{.greek-omitted} [ημων]{.greek-added} γενηθητω υμιν[9:29]{.aside}

και ανεωχθησαν αυτων οι οφθαλμοι [κ]{.greek-supplied}αι [ενεβριμησατο]{.greek-omitted} [ενεμβριμησατο]{.greek-added} αυτοις ο [ιησους]{.greek-abbr} λεγων ορατε μηδεις γινωσκετω[9:30]{.aside}

οι δε εξελθοντες [διεφημισαν]{.greek-omitted} [διεφημησαν]{.greek-added} αυτον εν ολη τη γη εκεινη[9:31]{.aside}

[α]{.greek-supplied}υτων δε εξερχομενων ιδου προσηνεγκαν αυτω [ανθρωπον]{.greek-abbr} κωφον δαιμονιζομενον[9:32]{.aside}

και [εκβληθεντος]{.greek-omitted} [εξελθοντος]{.greek-added} του δαιμονιου ελαλησεν ο κωφος [κ]{.greek-supplied}αι εθαυμασαν οι οχλοι λεγοντες ουδεποτε εφανη [ουτως]{.greek-omitted} [ουτος]{.greek-added} εν τω [ισραηλ]{.greek-abbr}[9:33]{.aside}

[ο]{.greek-supplied}ι δε φαρισαιοι ελεγον εν τω αρχοντι των δαιμονιων εκβαλλει τα δαιμονια[9:34]{.aside}

[κ]{.greek-supplied}αι περιηγεν ο [ιησους]{.greek-abbr} τας πολεις πασας και τας κωμας διδασκων εν ταις [συναγωγαις]{.greek-omitted} [συναγω]{.greek-added} [γαις]{.greek-added} αυτων και κηρυσσων το ευαγγελιον της βασιλειας και θεραπευων πασαν νοσον και πασαν μαλακιαν εν τω λαω[9:35]{.aside}

[ι]{.greek-supplied}δων δε τους οχλους εσπλαγχνισθη περι αυτων οτι ησαν [εσκυλμενοι]{.greek-omitted} [εκλελυμενοι]{.greek-added} και [ερριμμενοι]{.greek-omitted} [ερριμενοι]{.greek-added} ωσει προβατα μη εχοντα ποιμενα[9:36]{.aside}

[τ]{.greek-supplied}οτε λεγει τοις μαθηταις αυτου ο μεν θερισμος πολυς οι δε εργαται ολιγοι[9:37]{.aside}

δεηθητε ουν του [κυριου]{.greek-abbr} του θερισμου οπως εκβαλη εργατας εις τον θερισμον αυτου[9:38]{.aside}

### Chapter 10

[κ]{.greek-supplied}αι προσκαλεσαμενος τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} μαθητας αυτου εδωκεν αυτοι[ς]{.unclear} εξουσιαν [κατα]{.greek-added} [πνευματων]{.greek-abbr} ακαθαρτων ωστε [αυτα]{.greek-added} εκβαλλειν [αυτα]{.greek-omitted} και θεραπευειν πασαν νοσον και πασαν μαλακιαν[10:1]{.aside}

[τ]{.greek-supplied}ων [δε]{.greek-omitted} δωδεκα αποστολων τα ονοματα [εστιν]{.greek-omitted} [εισι]{.greek-added} ταυτα πρωτος σιμων ο λεγομενος πετρος και ανδρεας ο αδελφος αυτου ιακωβος ο του ζεβεδαιου και ιωαννης ο αδελφος αυτου[10:2]{.aside}

φιλιππος και βαρθολομαιος θωμας και ματθαιος ο τελωνης ιακωβος ο του αλφαιου και [λεββαιος]{.greek-omitted} [λεβαιος]{.greek-added} ο [ε]{.greek-added} [επικληθεις]{.greek-omitted} [πικληθεις]{.greek-added} θαδδαιος[10:3]{.aside}

σιμων ο κανανιτης και ιουδας [ο]{.greek-added} ισκαριωτης ο και [παραδους]{.greek-omitted} [παραδιδους]{.greek-added} αυτον[10:4]{.aside}

[τ]{.greek-supplied}ουτους τους [δωδεκα]{.greek-omitted} [[ιβ]{.greek-abbr}]{.greek-added} απεστειλεν ο [ιησους]{.greek-abbr} [παραγγειλας]{.greek-omitted} [αυτοις]{.greek-omitted} λεγων εις οδον εθνων μη απελθητε και εις πολιν [σαμαρειτων]{.greek-omitted} [σαμαριτων]{.greek-added} μη εισελθητε[10:5]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} δε μαλλον [προς]{.greek-omitted} [τα]{.greek-omitted} προβατα τα απολωλοτα οικου [ισραηλ]{.greek-abbr}[10:6]{.aside}

πορευομενοι δε κηρυσσετε λεγοντες οτι ηγγικεν η βασιλεια των [ουρανων]{.greek-abbr}[10:7]{.aside}

[α]{.greek-supplied}σθενουντας θεραπευετε λεπρους [καθαριζετε]{.greek-omitted} [καθαριζεται]{.greek-added} δαιμονια [εκβαλλετε]{.greek-omitted} [εκβαλλεται]{.greek-added} δωρεαν ελαβετε δωρεαν δοτε[10:8]{.aside}

[μ]{.greek-supplied}η [κτησησθε]{.greek-omitted} [κτησασθε]{.greek-added} χρυσον μηδε αργυρον μηδε χαλκον εις τας ζωνας υμων[10:9]{.aside}

μη πηραν εις οδον [μηδε]{.greek-omitted} [μητε]{.greek-added} δυο χιτωνας [μηδε]{.greek-omitted} [μητε]{.greek-added} υποδηματα μηδε ραβδους αξιος γαρ ο εργατης [της]{.greek-omitted} [τροφης]{.greek-omitted} [του]{.greek-added} [μισθου]{.greek-added} αυτου [εστιν]{.greek-omitted}[10:10]{.aside}

[ε]{.greek-supplied}ις ην δ αν πολιν η κωμην εισελθητε εξετασατε τις εν αυτη αξιος εστιν κακει μεινατε εως αν εξελθητε[10:11]{.aside}

[ε]{.greek-supplied}ισερχομενοι δε εις την οικιαν [ασπασασθε]{.greek-omitted} [ασπασασθαι]{.greek-added} [αυτην]{.greek-omitted} [αυτους]{.greek-added} [λεγοντες]{.greek-added} [ειρηνη]{.greek-added} [τω]{.greek-added} [οικω]{.greek-added} [τουτω]{.greek-added}[10:12]{.aside}

και εαν [μεν]{.greek-omitted} η η οικια αξια [ελθετω]{.greek-omitted} [εισελθη]{.greek-added} η ειρηνη υμων [επ]{.greek-omitted} [εν]{.greek-added} [αυτην]{.greek-omitted} [αυτη]{.greek-added} εαν δε μη η αξια η ειρηνη υμων προς υμας [επιστραφητω]{.greek-omitted} [αποστραφησεται]{.greek-added}[10:13]{.aside}

[κ]{.greek-supplied}αι ος [εαν]{.greek-omitted} [αν]{.greek-added} μη δεξηται υμας μηδε ακουση τους λογους υμων εξερχομενοι της οικιας η της πολεως εκεινης εκτιναξατε τον κονιορτον των ποδων υμων[10:14]{.aside}

αμην λεγω υμιν [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται γη σοδομων [και]{.greek-omitted} [η]{.greek-added} [γομορρων]{.greek-omitted} [γομορων]{.greek-added} εν ημερα κρισεως η τη πολει εκεινη[10:15]{.aside}

[και]{.greek-added} ιδου εγω αποστελλω υμας ως προβατα εν μεσω λυκων [γ]{.greek-supplied}ινεσθε ουν φρονιμοι ως οι οφεις και ακεραιοι ως αι περιστεραι[10:16]{.aside}

προσεχετε δε απο των [ανθρωπων]{.greek-abbr} [παραδωσουσιν]{.greek-omitted} [παραδωσουσι]{.greek-added} γαρ [υμας]{.greek-omitted} [ημας]{.greek-added} εις συνεδρια και εν ταις συναγωγαις αυτων μαστιγωσουσιν [υμας]{.greek-omitted} [ημας]{.greek-added}[10:17]{.aside}

και επι ηγεμονας [δε]{.greek-omitted} και βασιλεις αχθησεσθε ενεκεν εμου εις μαρτυριον αυτοις και τοις [εθνεσιν]{.greek-omitted} [εθνεσι]{.greek-added}[10:18]{.aside}

[ο]{.greek-supplied}ταν δε [παραδιδωσιν]{.greek-omitted} [παραδωσωσιν]{.greek-added} υμας μη μεριμνησητε πως [ειπητε]{.greek-added} η τι λαλησητε δοθησεται γαρ [υμιν]{.greek-omitted} εν εκεινη τη ωρα τι [λαλησετε]{.greek-omitted} [λαλησητε]{.greek-added}[10:19]{.aside}

ου γαρ υμεις εστε οι λαλουντες αλλα το [πνευμα]{.greek-abbr} του [πατρος]{.greek-abbr} υμων το λαλουν εν υμιν[10:20]{.aside}

[π]{.greek-supplied}αραδωσει δε αδελφος αδελφον εις θανατον και [πατηρ]{.greek-abbr} τεκνον και [επαναστησονται]{.greek-omitted} [αναστησονται]{.greek-added} τεκνα επι γονεις και θανατωσουσιν αυτους[10:21]{.aside}

[κ]{.greek-supplied}αι εσεσθε μισουμενοι υπο παντων δια το ονομα μου [ο]{.greek-omitted} [δε]{.greek-omitted} [υπομεινας]{.greek-omitted} [εις]{.greek-omitted} [τελος]{.greek-omitted} [ουτος]{.greek-omitted} [σωθησεται]{.greek-omitted}[10:22]{.aside}

[ο]{.greek-supplied}ταν δε διωκωσιν υμας εν τη [πολει]{.greek-omitted} [πολη]{.greek-added} ταυτη φευγετε εις την αλλην αμην [γαρ]{.greek-omitted} λεγω υμιν ου μη [γαρ]{.greek-added} τελεσητε τας πολεις του [ισραηλ]{.greek-abbr} εως αν ελθη ο υιος του [ανθρωπου]{.greek-abbr}[10:23]{.aside}

[ο]{.greek-supplied}υκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μαθητης υπερ τον διδασκαλον ουδε δουλος υπερ τον [κυριον]{.greek-abbr} αυτου[10:24]{.aside}

αρκετον τω μαθητη ινα γενηται ως ο διδασκαλος [αυτου]{.greek-omitted} και ο δουλος ως ο [κυριος]{.greek-abbr} αυτου [ε]{.greek-supplied}ι [ουν]{.greek-added} τον [οικοδεσποτην]{.greek-omitted} [δεσποτην]{.greek-added} βεελζεβουλ [εκαλεσαν]{.greek-omitted} [επεκαλεσαν]{.greek-added} ποσω μαλλον τους οικειακους αυτου[10:25]{.aside}

μη ουν φοβηθητε αυτους ουδεν γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} κεκαλυμμενον ο ουκ αποκαλυφθησεται και κρυπτον ο ου [μη]{.greek-added} γνωσθησεται[10:26]{.aside}

[ο]{.greek-supplied} λεγω υμιν εν τη [σκοτια]{.greek-omitted} [σκοτεια]{.greek-added} ειπατε εν τω φωτι και ο εις το ους [ακουετε]{.greek-omitted} [ηκουσατε]{.greek-added} κηρυξατε επι των δωματων[10:27]{.aside}

[και]{.greek-omitted} μη [ουν]{.greek-added} [φοβεισθε]{.greek-omitted} [φοβησθε]{.greek-added} απο των αποκτενοντων το σωμα την δε ψυχην μη δυναμενων αποκτειναι φοβηθητε δε μαλλον τον δυναμενον [και]{.greek-omitted} [την]{.greek-omitted} ψυχην και [το]{.greek-omitted} σωμα απολεσαι εν γεεννη[10:28]{.aside}

[ο]{.greek-supplied}υχι δυο στρουθια ασσαριου πωλειται και εν εξ αυτων ου πεσειται επι την γην ανευ του [πατρος]{.greek-abbr} [υμων]{.greek-omitted} [ημων]{.greek-added}[10:29]{.aside}

υμων δε και αι τριχες της κεφαλης [πασαι]{.greek-omitted} ηριθμημεναι [εισιν]{.greek-omitted} [εισι]{.greek-added}[10:30]{.aside}

μη ουν φοβηθητε πολλων στρουθιων διαφερετε υμεις[10:31]{.aside}

[π]{.greek-supplied}ας ουν οστις ομολογησει εν εμοι εμπροσθεν των [ανθρωπων]{.greek-abbr} ομολογησω καγω εν αυτω εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:32]{.aside}

οστις δ αν [αρνησηται]{.greek-omitted} [αρνησετε]{.greek-added} με εμπροσθεν των [ανθρωπων]{.greek-abbr} αρνησομαι [καγω]{.greek-added} αυτον [καγω]{.greek-omitted} εμπροσθεν του [πατρος]{.greek-abbr} μου του εν [ουρανοις]{.greek-abbr}[10:33]{.aside}

[μ]{.greek-supplied}η νομισητε οτι ηλθον βαλειν ειρηνην επι την γην ουκ ηλθον βαλειν ειρηνην [επι]{.greek-added} [την]{.greek-added} [γην]{.greek-added} αλλα μαχαιραν[10:34]{.aside}

ηλθον γαρ διχασαι [ανθρωπον]{.greek-abbr} κατα του [πατρος]{.greek-abbr} αυτου και θυγατερα κατα της [μητρος]{.greek-abbr} αυτης και νυμφην κατα της πενθερας αυτης[10:35]{.aside}

και εχθροι του [ανθρωπου]{.greek-abbr} οι οικειακοι αυτου[10:36]{.aside}

[ο]{.greek-supplied} φιλων [πατερα]{.greek-abbr} η [μητερα]{.greek-abbr} υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος και ο φιλων υιον η θυγατερα υπερ εμε ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:37]{.aside}

[κ]{.greek-supplied}αι ος ου λαμβανει τον [σταυρον]{.greek-abbr} αυτου και ακολουθει οπισω μου ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} μου αξιος[10:38]{.aside}

[ο]{.greek-supplied} ευρων την ψυχην αυτου απολεσει αυτην και ο απολεσας την ψυχην αυτου ενεκεν εμου ευρησ[ει]{.unclear} αυτην[10:39]{.aside}

[ο]{.greek-supplied} δεχομενος υμας εμε δεχεται και ο εμε δεχομενος δεχεται τον αποστειλαντα με[10:40]{.aside}

ο δεχομενος προφητην εις ονομα προφητου μισθον προφητου ληψεται και ο δεχομενος δικαιον εις ονομα δικαιου μισθον δικαιου ληψεται[10:41]{.aside}

[κ]{.greek-supplied}αι ος εαν ποτιση ενα των μικρων [τουτων]{.greek-omitted} ποτηριον [ψυχρου]{.greek-omitted} [ψυχρον]{.greek-added} μονον εις ονομα μαθητου αμην λεγω υμιν ου μη απολεση τον μισθον αυτου[10:42]{.aside}

### Chapter 11

[κ]{.greek-supplied}αι εγενετο οτε ετελεσεν ο [ιησους]{.greek-abbr} διατασσων [τοις]{.greek-omitted} [τους]{.greek-added} δωδεκα [μαθηταις]{.greek-omitted} [μαθητας]{.greek-added} αυτου [μετεβη]{.greek-omitted} [μετεβει]{.greek-added} εκειθεν του διδασκειν και κηρυσσειν εν ταις [πολεσιν]{.greek-omitted} [συναγωγαις]{.greek-added} αυτων [και]{.greek-added} [τας]{.greek-added} [πολεις]{.greek-added}[11:1]{.aside}

[ο]{.greek-supplied} δε ιωαννης ακουσας εν τω [δεσμωτηριω]{.greek-omitted} [δεσμοτιριω]{.greek-added} τα εργα του [χριστου]{.greek-abbr} πεμψας δυο των μαθητων [αυτου]{.greek-omitted}[11:2]{.aside}

[ειπεν]{.greek-omitted} [ειπε]{.greek-added} [αυτω]{.greek-omitted} συ ει ο ερχομενος η ετερον προσδοκωμεν[11:3]{.aside}

[κ]{.greek-supplied}αι αποκριθεις ο [ιησους]{.greek-abbr} ειπεν αυτοις πορευθεντες απαγγειλατε [τω]{.greek-added} ιωαννη α ακουετε και βλεπετε[11:4]{.aside}

τυφλοι [αναβλεπουσιν]{.greek-omitted} [αναβλεπουσι]{.greek-added} [και]{.greek-omitted} χωλοι [περιπατουσιν]{.greek-omitted} [περιπατουσι]{.greek-added} λεπροι καθαριζονται [και]{.greek-omitted} κωφοι [ακουουσιν]{.greek-omitted} [ακουουσι]{.greek-added} νεκροι εγειρονται [και]{.greek-omitted} πτωχοι ευαγγελιζονται[11:5]{.aside}

και μακαριος [εστιν]{.greek-omitted} ος εαν μη σκανδαλισθη εν εμοι[11:6]{.aside}

[τ]{.greek-supplied}ουτων δε πορευομενων ηρξατο ο [ιησους]{.greek-abbr} λεγειν τοις οχλοις περι ιωαννου τι εξηλθετε [[εξηλθατε]{.corr}]{.greek-added} εις την ερημον θεασασθαι καλαμον υπο ανεμου σαλευομενον[11:7]{.aside}

[α]{.greek-supplied}λλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν [ανθρωπον]{.greek-abbr} εν μαλακοις ιματιοις ημφιεσμενον ιδου οι τα μαλακα φορουντες εν τοις οικοις των [βασιλειων]{.greek-omitted} [βασιλεων]{.greek-added} εισιν[11:8]{.aside}

[α]{.greek-supplied}λλα τι [εξηλθετε]{.greek-omitted} [εξηλθατε]{.greek-added} ιδειν προφητην ναι λεγω υμιν και περισσοτερον προφητου[11:9]{.aside}

[ο]{.greek-supplied}υτος γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} περι ου γεγραπται ιδου εγω αποστελλω τον αγγελον μου προ προσωπου σου ος κατασκευασει την οδον σου εμπροσθεν σου[11:10]{.aside}

[α]{.greek-supplied}μην λεγω υμιν ουκ εγηγερται εν γεννητοις γυναικων μειζων ιωαννου του βαπτιστου [ο]{.greek-supplied} δε μικροτερος εν τη βασιλεια των ουρανων μειζων αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added}[11:11]{.aside}

[α]{.greek-supplied}πο δε των ημερων ιωαννου του βαπτιστου εως αρτι η βασιλεια των ουρανων βιαζεται και βιασται αρπαζουσιν αυτην[11:12]{.aside}

[π]{.greek-supplied}αντες γαρ οι προφηται και ο νομος εως ιωαννου προεφητευσαν[11:13]{.aside}

[κ]{.greek-supplied}αι ει θελετε δεξασθαι αυτος εστιν ηλιας ο μελλων ερχεσθαι[11:14]{.aside}

[ο]{.greek-supplied} εχων ωτα ακουειν [ακουετω]{.greek-omitted} [ακου]{.greek-added} [ετω]{.greek-added}[11:15]{.aside}

[τ]{.greek-supplied}ινι [δε]{.greek-omitted} ομοιωσω την γενεαν ταυτην ομοια [εστιν]{.greek-omitted} [εστι]{.greek-added} παιδιοις [καθημενοις]{.greek-added} εν [αγοραις]{.greek-omitted} [αγορα]{.greek-added} [καθημενοις]{.greek-omitted} και [προσφωνουσιν]{.greek-omitted} [προσφωνουσι]{.greek-added} τοις [εταιροις]{.greek-omitted} [ετεροις]{.greek-added} αυτων[11:16]{.aside}

και λεγουσιν [ηυλησαμεν]{.greek-omitted} [ηυλισαμεν]{.greek-added} υμιν και ουκ [ωρχησασθε]{.greek-omitted} [ορχισασθε]{.greek-added} εθρηνησαμεν υμιν και ουκ εκοψασθε[11:17]{.aside}

[η]{.greek-supplied}λθεν [[ιω]{.greek-abbr}]{.greek-added} [γαρ]{.greek-omitted} [ιωαννης]{.greek-omitted} μητε εσθιων μητε πινων και [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} δαιμονιον εχει[11:18]{.aside}

ηλθεν ο υιος του [ανθρωπου]{.greek-abbr} εσθιων και πινων [και]{.greek-omitted} λεγουσιν ιδου ανθρωπος φαγος και οινοποτης [φιλος]{.greek-added} τελωνων [φιλος]{.greek-omitted} και αμαρτωλων [κ]{.greek-supplied}αι εδικαιωθη η σοφια απο των τεκνων αυτης[11:19]{.aside}

[τ]{.greek-supplied}οτε ηρξατο [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} ονειδιζειν τας πολεις εν αις εγενοντο αι πλεισται δυναμεις αυτου οτι ου μετενοησαν[11:20]{.aside}

[ο]{.greek-supplied}υαι σοι [χοραζιν]{.greek-omitted} [χωραζιν]{.greek-added} ουαι σοι βηθσαιδα [ο]{.greek-supplied}τι ει εν τυρω και σιδωνι εγενοντο αι δυναμεις αι γενομεναι [εν]{.greek-omitted} υμιν [παλαι]{.greek-omitted} [ταχα]{.greek-added} αν εν σακκω και σποδω μετενοησαν[11:21]{.aside}

πλην λεγω υμιν τυρω και σιδωνι [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται εν ημερα κρισεως η υμιν[11:22]{.aside}

[κ]{.greek-supplied}αι συ καπερναουμ η εως του [ουρανου]{.greek-abbr} υψωθεισα εως [του]{.greek-added} αδου [καταβιβασθηση]{.greek-omitted} [καταβιβασθειση]{.greek-added} οτι ει εν [σοδομοις]{.greek-omitted} [σινδωνοις]{.greek-added} εγενοντο αι δυναμεις αι γενομεναι εν σοι [εμειναν]{.greek-omitted} [εμεινεν]{.greek-added} αν μεχρι της σημερον[11:23]{.aside}

πλην λεγω υμιν οτι γη σοδομων [ανεκτοτερον]{.greek-omitted} [ανεκτωτερον]{.greek-added} εσται εν ημερα κρισεως [η]{.greek-omitted} [σοι]{.greek-omitted}[11:24]{.aside}

[ε]{.greek-supplied}ν εκεινω τω [καιρω]{.greek-omitted} [ρω]{.greek-added} αποκριθεις ο [ιησους]{.greek-abbr} ειπεν εξομολογουμαι σοι [πατερ]{.greek-abbr} [κυριε]{.greek-abbr} του [ουρανου]{.greek-abbr} και της γης οτι απεκρυψας ταυτα απο σοφων και συνετων και απεκαλυψας αυτα νηπιοις[11:25]{.aside}

[ν]{.greek-supplied}αι ο [πατηρ]{.greek-abbr} οτι ουτως εγενετο ευδοκια εμπροσθεν σου[11:26]{.aside}

[π]{.greek-supplied}αντα μοι παρεδοθη υπο του [πατρος]{.greek-abbr} [μου]{.greek-omitted} [κ]{.greek-supplied}αι ουδεις επιγινωσκει τον υιον ει μη ο [πατηρ]{.greek-abbr} ουδε τον [πατερα]{.greek-abbr} τις επιγινωσκει ει μη ο υιος και ω εαν βουληται ο υιος αποκαλυψαι[11:27]{.aside}

[δ]{.greek-supplied}ευτε προς με παντες οι κοπιωντες και πεφορτισμενοι καγω αναπαυσω υμας[11:28]{.aside}

[α]{.greek-supplied}ρατε τον ζυγον μου εφ υμας και μαθετε απ εμου οτι πραος ειμι και [ταπεινος]{.greek-omitted} [ταπενος]{.greek-added} τη καρδια και [ευρησετε]{.greek-omitted} [ευρησητε]{.greek-added} αναπαυσιν [ταις]{.greek-added} ταις ψυχαις υμων[11:29]{.aside}

ο γαρ ζυγος μου χρηστος και το φορτιον μου ελαφρον εστιν[11:30]{.aside}

### Chapter 12

[ε]{.greek-supplied}ν εκεινω τω καιρω επορευθη ο [ιησους]{.greek-abbr} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} δια των σποριμων οι δε μαθηται αυτου επεινασαν και ηρξαντο τιλλειν [τους]{.greek-added} σταχυας και εσθιειν[12:1]{.aside}

[ο]{.greek-supplied}ι δε φαρισαιοι ιδοντες ειπον αυτω ιδου οι μαθηται σου ποιουσιν [ο]{.greek-omitted} [α]{.greek-added} ουκ εξεστιν ποιειν εν σαββατω[12:2]{.aside}

ο δε [αποκριθεις]{.greek-added} ειπεν αυτοις ουκ ανεγνωτε τι [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} [δαυιδ]{.greek-abbr} οτε επεινασεν αυτος και οι μετ αυτου[12:3]{.aside}

πως εισηλθεν εις τον οικον του [θεου]{.greek-abbr} και τους αρτους της προθεσεως [εφαγεν]{.greek-omitted} [εφαγον]{.greek-added} ους ουκ εξον [αυτω]{.greek-added} ην [αυτω]{.greek-omitted} φαγειν ουδε τοις μετ αυτου [αλλα]{.greek-added} [ει]{.greek-omitted} [μη]{.greek-omitted} τοις [ιερευσιν]{.greek-omitted} [ιερευσι]{.greek-added} μονοις[12:4]{.aside}

[η]{.greek-supplied} ουκ ανεγνωτε [οτι]{.greek-added} εν τω νομω [οτι]{.greek-omitted} τοις σαββασιν οι ιερεις εν τω ιερω [το]{.greek-omitted} [τω]{.greek-added} σαββατον [βεβηλουσιν]{.greek-omitted} [βεβηλουσι]{.greek-added} και αναιτιοι [εισιν]{.greek-omitted} [εισι]{.greek-added}[12:5]{.aside}

λεγω δε υμιν οτι του ιερου μειζον εστιν ωδε[12:6]{.aside}

[ε]{.greek-supplied}ι δε εγνωκειτε τι εστιν [ελεον]{.greek-omitted} [ελαιον]{.greek-added} θελω και ου θυσιαν ουκ αν κατεδικασατε τους αναιτιους[12:7]{.aside}

κυριος γαρ εστιν του σαββατου ο υιος του [ανθρωπου]{.greek-abbr}[12:8]{.aside}

[κ]{.greek-supplied}αι μεταβας εκειθεν ηλθεν εις την συναγωγην αυτων[12:9]{.aside}

και ιδου [ανθρωπος]{.greek-abbr} [ην]{.greek-omitted} την χειρα εχων ξηραν και επηρωτησαν αυτον λεγοντες ει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} τοις [σαββασιν]{.greek-omitted} [σαββασι]{.greek-added} θεραπευειν ινα κατηγορησωσιν αυτου[12:10]{.aside}

[ο]{.greek-supplied} δε ειπεν αυτοις τις [εσται]{.greek-omitted} εξ υμων [εστιν]{.greek-added} [ανθρωπος]{.greek-abbr} ος εξει προβατον εν και εαν [εμπεση]{.greek-omitted} [πεση]{.greek-added} τουτο τοις σαββασιν εις [βοθυνον]{.greek-omitted} [βοθρον]{.greek-added} ουχι κρατησει αυτο και εγερει[12:11]{.aside}

ποσω ουν διαφερει [ο]{.greek-added} [ανθρωπος]{.greek-abbr} προβατου ωστε [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} [τοις]{.greek-omitted} [σαββασιν]{.greek-omitted} καλως ποιειν[12:12]{.aside}

[τ]{.greek-supplied}οτε λεγει τω [ανθρωπω]{.greek-abbr} εκτεινον την χειρα σου και [εξετεινεν]{.greek-omitted} [εξετεινε]{.greek-added} και [αποκατεσταθη]{.greek-omitted} [απεκατεσταθη]{.greek-added} υγιης ως η αλλη[12:13]{.aside}

[ο]{.greek-supplied}ι δε φαρισαιοι συμβουλιον ελαβον κατ αυτου εξελθοντες οπως αυτον απολεσωσιν[12:14]{.aside}

ο δε [ιησους]{.greek-abbr} γνους ανεχωρησεν εκειθεν [κ]{.greek-supplied}αι ηκολουθησαν αυτω οχλοι πολλοι και εθεραπευσεν αυτους παντας[12:15]{.aside}

και [επετιμησεν]{.greek-omitted} [επετημησεν]{.greek-added} αυτοις ινα μη φανερον [αυτον]{.greek-omitted} [ποιησωσιν]{.greek-omitted} [ποιησωσι]{.greek-added}[12:16]{.aside}

[ο]{.greek-supplied}πως πληρωθη το ρηθεν δια ησαιου του προφητου λεγοντος[12:17]{.aside}

ιδου ο παις μου ον [ηρετισα]{.greek-omitted} [ηρετισαμην]{.greek-added} ο αγαπητος μου εις ον ευδοκησεν η ψυχη μου θησω το [πνευμα]{.greek-abbr} μου επ αυτον και κρισιν τοις εθνεσιν απαγγελει[12:18]{.aside}

ουκ ερισει ουδε κραυγασει [ουδε]{.greek-omitted} [[ο]{.greek-supplied}υδ]{.greek-added} ακουσει τις εν ταις πλατειαις την φωνην αυτου[12:19]{.aside}

[κ]{.greek-supplied}αλαμον συντετριμμενον ου κατεαξει και λινον τυφομενον ου σβεσει εως αν εκβαλη εις νικος την κρισιν[12:20]{.aside}

[κ]{.greek-supplied}αι τω ονοματι αυτου εθνη ελπιουσιν[12:21]{.aside}

[τ]{.greek-supplied}οτε προσηνεχθη αυτω [τυφλος]{.greek-added} δαιμονιζομενος [τυφλος]{.greek-omitted} και κωφος και εθεραπευσεν αυτον ωστε τον τυφλον και κωφον και λαλειν και βλεπειν[12:22]{.aside}

και εξισταντο παντες οι οχλοι και ελεγον μητι ουτος εστιν ο υιος [δαυιδ]{.greek-abbr}[12:23]{.aside}

οι δε φαρισαιοι ακουσαντες ειπον ουτος [ουκ]{.greek-omitted} εκβαλλει τα δαιμονια ει μη εν τω βεελζεβουλ αρχοντι των δαιμονιων[12:24]{.aside}

[ε]{.greek-supplied}ιδως δε ο [ιησους]{.greek-abbr} τας ενθυμησεις αυτων ειπεν αυτοις πασα βασιλεια [μερισθεισα]{.greek-omitted} [διαμερισθεισα]{.greek-added} καθ εαυτης ερημουται και πασα πολις η οικια μερισθεισα καθ [εαυτης]{.greek-omitted} [εαυτην]{.greek-added} ου σταθησεται[12:25]{.aside}

και ει ο σατανας τον σαταναν εκβαλλει [εφ]{.greek-omitted} [αφ]{.greek-added} εαυτον εμερισθη πως ουν σταθησεται η βασιλεια αυτου[12:26]{.aside}

[και]{.greek-omitted} [ε]{.greek-supplied}ι εγω εν [τω]{.greek-added} βεελζεβουλ εκβαλλω τα δαιμονια οι υιοι υμων εν τινι [εκβαλλουσιν]{.greek-omitted} [εκβαλλουσι]{.greek-added} δια τουτο αυτοι υμων εσονται κριται[12:27]{.aside}

[ε]{.greek-supplied}ι δε εν [πνευματι]{.greek-abbr} [θεου]{.greek-abbr} εγω εκβαλλω τα δαιμονια αρα εφθασεν εφ υμας η βασιλεια του [θεου]{.greek-abbr}[12:28]{.aside}

[η]{.greek-supplied} πως δυναται τις εισελθειν εις την οικιαν του ισχυρου και τα σκευη αυτου διαρπασαι [εαν]{.greek-omitted} [ει]{.greek-added} μη [πρωτον]{.greek-omitted} [δηση]{.greek-omitted} [προτε[ρ]{.unclear}ον]{.greek-added} [δησει]{.greek-added} τον ισχυρον και τοτε την οικιαν αυτου [διαρπασει]{.greek-omitted} [διαρπασαι]{.greek-added}[12:29]{.aside}

[ο]{.greek-supplied} μη ων μετ εμου κατ εμου [εστιν]{.greek-omitted} [εστι]{.greek-added} και ο μη συναγων μετ εμου σκορπιζει[12:30]{.aside}

[δ]{.greek-supplied}ια τουτο λεγω υμιν πασα αμαρτια και βλασφημια αφεθησεται τοις [ανθρωποις]{.greek-abbr} [η]{.greek-omitted} [δε]{.greek-omitted} [του]{.greek-omitted} [πνευματος]{.greek-omitted} [βλασφημια]{.greek-omitted} [ουκ]{.greek-omitted} [αφεθησεται]{.greek-omitted} [τοις]{.greek-omitted} [ανθρωποις]{.greek-omitted}[12:31]{.aside}

και ος εαν ειπη λογον κατα [του]{.greek-omitted} υιου του [ανθρωπου]{.greek-abbr} αφεθησεται αυτω [ος]{.greek-omitted} [ως]{.greek-added} δ αν ειπη κατα του [πνευματος]{.greek-abbr} του αγιου ουκ αφεθησεται [αυτω]{.greek-omitted} ουτε εν τω νυν αιωνι ουτε εν τω μελλοντι[12:32]{.aside}

[η]{.greek-supplied} ποιησατε το δενδρον καλον και τον καρπον αυτου καλον η ποιησατε το δενδρον σαπρον και τον καρπον αυτου σαπρον εκ γαρ του καρπου [γινωσκεται]{.greek-added} το δενδρον [γινωσκεται]{.greek-omitted}[12:33]{.aside}

[γ]{.greek-supplied}εννηματα εχιδνων πως [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} [αγαθα]{.greek-omitted} [αγα]{.greek-added} λαλειν πονηροι οντες [ε]{.greek-supplied}κ γαρ του [περισσευματος]{.greek-omitted} [περισευματος]{.greek-added} της καρδιας το στομα λαλει[12:34]{.aside}

ο αγαθος [ανθρωπος]{.greek-abbr} εκ του αγαθου θησαυρου εκβαλλει [τα]{.greek-added} αγαθα και ο πονηρος [ανθρωπος]{.greek-abbr} εκ του πονηρου θησαυρου εκβαλλει [τα]{.greek-added} πονηρα[12:35]{.aside}

[λ]{.greek-supplied}εγω δε υμιν οτι παν ρημα αργον ο εαν λαλησωσιν οι [ανθρωποι]{.greek-abbr} [αποδωσουσιν]{.greek-omitted} [αποδωσουσι]{.greek-added} περι αυτου λογον εν ημερα κρισεως[12:36]{.aside}

εκ γαρ των λογων σου δικαιωθηση και εκ των λογων σου [καταδικασθηση]{.greek-omitted} [κατακριθηση]{.greek-added}[12:37]{.aside}

[τ]{.greek-supplied}οτε απεκριθησαν τινες των [φαρισαιων]{.greek-added} [και]{.greek-added} γραμματεων [και]{.greek-omitted} [φαρισαιων]{.greek-omitted} λεγοντες διδασκαλε θελομεν απο σου σημειον ιδειν[12:38]{.aside}

[ο]{.greek-omitted} [[α]{.greek-supplied}ποκριθεις]{.greek-added} δε [αποκριθεις]{.greek-omitted} ειπεν [αυτοις]{.greek-omitted} [αυτης]{.greek-added} γενεα πονηρα και μοιχαλις σημειον επιζητει και σημειον ου δοθησεται αυτη ει μη το σημειον ιωνα του προφητου[12:39]{.aside}

ωσπερ γαρ [ην]{.greek-omitted} [ο]{.greek-added} ιωνας εν τη κοιλια του κητους τρεις ημερας και τρεις νυκτας ουτως εσται [και]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} [τρεις]{.greek-added} [νυκτας]{.greek-added} [και]{.greek-added} [τρεις]{.greek-added} [ημερας]{.greek-added} εν τη καρδια της γης [τρεις]{.greek-omitted} [ημερας]{.greek-omitted} [και]{.greek-omitted} [τρεις]{.greek-omitted} [νυκτας]{.greek-omitted}[12:40]{.aside}

[α]{.greek-supplied}νδρες νινευιται αναστησονται εν τη κρισει μετα της γενεας ταυτης και κατακρινουσιν αυτην οτι μετενοησαν εις το κηρυγμα ιωνα και ιδου πλειον ιωνα ωδε[12:41]{.aside}

[β]{.greek-supplied}ασιλισσα νοτου εγερθησεται εν τη κρισει μετα της γενεας ταυτης και κατακρινει [αυτην]{.greek-omitted} [αυτους]{.greek-added} οτι ηλθεν [απο]{.greek-added} [εκ]{.greek-omitted} [των]{.greek-omitted} περατων της γης ακουσαι [την]{.greek-omitted} σοφιαν σολομωνος και ιδου πλειον σολομωνος ωδε[12:42]{.aside}

[ο]{.greek-supplied}ταν δε το ακαθαρτον [πνευμα]{.greek-abbr} εξελθη απο του [ανθρωπου]{.greek-abbr} διερχεται δι ανυδρων τοπων [ζητουν]{.greek-omitted} [ζητων]{.greek-added} αναπαυσιν και ουχ ευρισκει[12:43]{.aside}

τοτε λεγει επιστρεψω εις τον οικον μου οθεν εξηλθον και [ελθον]{.greek-omitted} [ελθων]{.greek-added} ευρισκει [σχολαζοντα]{.greek-omitted} [χολαζοντα]{.greek-added} σεσαρωμενον και [κεκοσμημενον]{.greek-omitted} [κεκοσμιμενον]{.greek-added}[12:44]{.aside}

τοτε [πορευεται]{.greek-omitted} [πορευετε]{.greek-added} και [παραλαμβανει]{.greek-omitted} [λαμβανει]{.greek-added} μεθ εαυτου επτα ετερα [πνευματα]{.greek-abbr} πονηροτερα [εαυτου]{.greek-omitted} [αυτου]{.greek-added} και [εισελθοντα]{.greek-omitted} [εισελθοντος]{.greek-added} κατοικει εκει και γινεται τα εσχατα του [ανθρωπου]{.greek-abbr} εκεινου χειρονα των πρωτων ουτως εσται και τη γενεα ταυτη τη πονηρα[12:45]{.aside}

[ε]{.greek-supplied}τι [δε]{.greek-omitted} αυτου λαλουντος τοις οχλοις ιδου η [μητηρ]{.greek-abbr} [αυτου]{.greek-added} και οι αδελφοι αυτου ειστηκεισαν εξω ζητουντες αυτω λαλησαι[12:46]{.aside}

[ειπεν]{.greek-omitted} [[ε]{.greek-supplied}ιπε]{.greek-added} δε τις αυτω ιδου η [μητηρ]{.greek-abbr} σου και [οι]{.greek-omitted} [η]{.greek-added} αδελφοι σου εξω [εστηκασιν]{.greek-omitted} ζητουντες σοι λαλησαι[12:47]{.aside}

ο δε αποκριθεις ειπεν [τω]{.greek-omitted} [αυτω]{.greek-added} ειποντι αυτω τις εστιν η [μητηρ]{.greek-abbr} μου και τινες εισιν οι αδελφοι μου[12:48]{.aside}

[κ]{.greek-supplied}αι εκτεινας την χειρα αυτου επι τους μαθητας αυτου [ειπεν]{.greek-omitted} [ειπε]{.greek-added} ιδου η [μητηρ]{.greek-abbr} μου και οι αδελφοι μου[12:49]{.aside}

οστις γαρ αν ποιηση το θελημα του [πατρος]{.greek-abbr} [μου]{.greek-omitted} [του]{.greek-omitted} [εν]{.greek-omitted} [ουρανοις]{.greek-omitted} [αυτος]{.greek-omitted} [μου]{.greek-omitted} [αδελφος]{.greek-omitted} [και]{.greek-omitted} [αδελφη]{.greek-omitted} [και]{.greek-omitted} [μητηρ]{.greek-omitted} [εστιν]{.greek-omitted}[12:50]{.aside}

### Chapter 20

[α]{.greek-supplied}ποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν ουκ οιδατε τι [αιτεισθε]{.greek-omitted} [αιτεισθαι]{.greek-added} [δυνασθε]{.greek-omitted} [δυνασθαι]{.greek-added} πιειν το ποτηριον ο εγω μελλω [πινειν]{.greek-omitted} [πιειν]{.greek-added} [η]{.greek-omitted} [και]{.greek-added} το βαπτισμα ο εγω βαπτιζομαι βαπτισθηναι λεγουσιν αυτω δυναμεθα[20:22]{.aside}

[και]{.greek-omitted} [[o]{.greek-supplied}]{.greek-added} [δε]{.greek-added} λεγει αυτοις το μεν ποτηριον [μου]{.greek-omitted} [ο]{.greek-added} [εγω]{.greek-added} [πινω]{.greek-added} πιεσθε και το βαπτισμα ο εγω βαπτιζομαι βαπτισθησεσθε το δε [καθισαι]{.greek-omitted} [καθησαι]{.greek-added} εκ δεξιων μου και [εξ]{.unclear} ευωνυμων μου ουκ [εστιν]{.greek-omitted} [εστι]{.greek-added} εμον δουναι αλλ οις ητοιμασται [υπο]{.greek-omitted} [παρα]{.greek-added} του [πατρος]{.greek-abbr} μου[20:23]{.aside}

[κ]{.greek-supplied}αι ακουσαντες οι δεκα [ηγανακτησαν]{.greek-omitted} [ηρξαντο]{.greek-added} [αγανακτειν]{.greek-added} περι [των]{.greek-omitted} [δυο]{.greek-omitted} [αδελφων]{.greek-omitted} [ιακωβου]{.greek-added} [και]{.greek-added} [ιωαννου]{.greek-added}[20:24]{.aside}

ο δε [ιησους]{.greek-abbr} προσκαλεσαμενος αυτους [ειπεν]{.greek-omitted} [λεγει]{.greek-added} [αυτοις]{.greek-added} οιδατε οτι οι [αρχοντες]{.greek-omitted} [δοκουντες]{.greek-added} [αρχειν]{.greek-added} των εθνων κατακυριευουσιν αυτων και οι μεγαλοι [αυτων]{.greek-added} κατεξουσιαζουσιν αυτων[20:25]{.aside}

ουχ ουτως δε εσται [εν]{.greek-omitted} υμιν αλλ ος εαν θελη [εν]{.greek-omitted} [υμιν]{.greek-omitted} [μεγας]{.greek-omitted} γενεσθαι [εσται]{.greek-omitted} [πρωτος]{.greek-added} υμων [εστω]{.greek-added} διακονος[20:26]{.aside}

και ος εαν θελη [εν]{.greek-omitted} [υμιν]{.greek-omitted} [υμων]{.greek-added} [ειναι]{.greek-omitted} [πρωτος]{.greek-omitted} [γενεσθαι]{.greek-added} [μεγας]{.greek-added} εστω [υμων]{.greek-omitted} [παντων]{.greek-added} δουλος[20:27]{.aside}

[ωσπερ]{.greek-omitted} [και]{.greek-added} [γαρ]{.greek-added} ο υιος του [ανθρωπου]{.greek-abbr} ουκ [ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} διακονηθηναι αλλα διακονησαι και δουναι την ψυχην αυτου λυτρον αντι πολλων[20:28]{.aside}

[κ]{.greek-supplied}αι [εκπορευομενων]{.greek-omitted} [εκπορευομενου]{.greek-added} [αυτων]{.greek-omitted} [αυτου]{.greek-added} απο ιεριχω [ηκολουθησεν]{.greek-omitted} [αυτω]{.greek-omitted} [οχλος]{.greek-omitted} [πολυς]{.greek-omitted}[20:29]{.aside}

[και]{.greek-omitted} ιδου δυο τυφλοι καθημενοι παρα την οδον ακουσαντες οτι [ιησους]{.greek-abbr} παραγει εκραξαν λεγοντες ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:30]{.aside}

ο δε οχλος [επετιμησεν]{.greek-omitted} [επετιμα]{.greek-added} αυτοις ινα σιωπησωσιν οι δε μειζον εκραζον [λεγοντες]{.greek-omitted} ελεησον ημας [κυριε]{.greek-abbr} [υιος]{.greek-omitted} [υιε]{.greek-added} [δαυιδ]{.greek-abbr}[20:31]{.aside}

και στας ο [ιησους]{.greek-abbr} εφωνησεν [αυτους]{.greek-omitted} [αυτοις]{.greek-added} και [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι θελετε ποιησω υμιν[20:32]{.aside}

[οι]{.greek-added} [δε]{.greek-added} [λεγουσιν]{.greek-omitted} [αυτω]{.greek-omitted} [κυριε]{.greek-omitted} ινα ανοιχθωσιν [ημων]{.greek-omitted} οι οφθαλμοι [ημων]{.greek-added}[20:33]{.aside}

σπλαγχνισθεις δε ο [ιησους]{.greek-abbr} ηψατο των οφθαλμων αυτων και [ευθεως]{.greek-omitted} ανεβλεψαν [αυτων]{.greek-omitted} [οι]{.greek-omitted} [οφθαλμοι]{.greek-omitted} και ηκολουθησαν αυτω[20:34]{.aside}

### Chapter 21

[κ]{.greek-supplied}αι οτε [ηγγισαν]{.greek-omitted} [ηγγισεν]{.greek-added} [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} [και]{.greek-added} [ηλθεν]{.greek-added} εις [ιεροσολυμα]{.greek-omitted} [και]{.greek-omitted} [ηλθον]{.greek-omitted} [εις]{.greek-omitted} [βηθσφαγη]{.greek-omitted} [βηθσφαγην]{.greek-added} προς το ορος των ελαιων τοτε [ο]{.greek-omitted} [ιησους]{.greek-omitted} [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} δυο μαθητας[21:1]{.aside}

λεγων αυτοις πορευθητε εις την κωμην την απεναντι υμων και ευθεως [ευρησετε]{.greek-omitted} [ευρησητε]{.greek-added} ονον [δεδεμενην]{.greek-omitted} [δεδεμενον]{.greek-added} και πωλον μετ αυτης λυσαντες αγαγετε μοι[21:2]{.aside}

και εαν τις υμιν ειπη τι ερειτε οτι ο [κυριος]{.greek-abbr} αυτων χρειαν εχει ευθεως δε αποστελλει αυτους[21:3]{.aside}

τουτο δε ολον γεγονεν ινα πληρωθη το ρηθεν δια του προφητου λεγοντος[21:4]{.aside}

ειπατε τη θυγατρι σιων ιδου ο βασιλευς σου ερχεται σοι πραυς και [σωζων]{.greek-added} [και]{.greek-added} επιβεβηκως επι ονον και πωλον υιον υποζυγιου[21:5]{.aside}

[π]{.greek-supplied}ορευθεντες δε οι μαθηται και ποιησαντες καθως [προσεταξεν]{.greek-omitted} [συνεταξεν]{.greek-added} αυτοις ο [ιησους]{.greek-abbr}[21:6]{.aside}

ηγαγον [την]{.greek-omitted} [τον]{.greek-added} ονον και τον πωλον και επεθηκαν [αυτ]{.greek-added} επανω αυτων τα ιματια αυτων και [επεκαθισεν]{.greek-omitted} [εκαθισεν]{.greek-added} επανω αυτων[21:7]{.aside}

[ο]{.greek-supplied} δε πλειστος οχλος εστρωσαν [εαυτων]{.greek-omitted} τα ιματια [αυτων]{.greek-added} εν τη οδω αλλοι δε εκοπτον κλαδους απο των δενδρων και [εβασταζον]{.greek-added} [εστρωννυον]{.greek-omitted} [εν]{.greek-omitted} [τη]{.greek-omitted} [οδω]{.greek-omitted}[21:8]{.aside}

[οι]{.greek-omitted} [δε]{.greek-omitted} [οχλοι]{.greek-omitted} οι προαγοντες [δε]{.greek-added} και οι ακολουθουντες εκραζον λεγοντες ωσαννα τω υιω [δαυιδ]{.greek-abbr} ευλογημενος ο ερχομενος εν ονοματι [κυριου]{.greek-abbr} [ωσαννα]{.greek-omitted} [εν]{.greek-omitted} [τοις]{.greek-omitted} [υψιστοις]{.greek-omitted}[21:9]{.aside}

[κ]{.greek-supplied}αι εισελθοντος αυτου εις ιεροσολυμα εσεισθη πασα η πολις λεγουσα τις εστιν ουτος[21:10]{.aside}

οι δε οχλοι ελεγον ουτος εστιν [ιησους]{.greek-abbr} ο προφητης ο απο ναζαρετ της γαλιλαιας[21:11]{.aside}

[κ]{.greek-supplied}αι εισηλθεν ο [ιησους]{.greek-abbr} εις το ιερον του [θεου]{.greek-abbr} και [εξεβαλεν]{.greek-omitted} [εξεβαλε]{.greek-added} παντας τους πωλουντας [και]{.greek-omitted} [αγοραζοντας]{.greek-omitted} εν τω ιερω και τας τραπεζας των [κολλυβιστων]{.greek-omitted} [κολυβιστων]{.greek-added} [κατεστρεψεν]{.greek-omitted} [κατεστρεψε]{.greek-added} και [τας]{.greek-omitted} [καθεδρας]{.greek-omitted} των [πωλουντων]{.greek-omitted} τας περιστερας [πωλουντων]{.greek-added}[21:12]{.aside}

[και]{.greek-omitted} [λεγει]{.greek-omitted} [αυτοις]{.greek-omitted} [ειπεν]{.greek-added} [αρατε]{.greek-added} [ταυτα]{.greek-added} [εντευθεν]{.greek-added} γεγραπται [γαρ]{.greek-added} ο οικος μου οικος προσευχης κληθησεται υμεις δε [εποιησατε]{.greek-added} αυτον [εποιησατε]{.greek-omitted} σπηλαιον ληστων[21:13]{.aside}

[κ]{.greek-supplied}αι προσηλθον αυτω χωλοι και τυφλοι εν τω ιερω και εθεραπευσεν αυτους[21:14]{.aside}

[ι]{.greek-supplied}δοντες δε οι αρχιερεις και οι γραμματεις τα θαυμασια α [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} και τους παιδ[ας]{.unclear} κραζοντας εν τω ιερω και λεγοντας ωσαννα τω υιω [δαυιδ]{.greek-omitted} [δαβιδ]{.greek-added} [ηγανακτησαν]{.greek-omitted} [ηγανακτισαν]{.greek-added}[21:15]{.aside}

και ειπον αυτω [ουκ]{.greek-added} ακουεις τι ουτοι λεγουσιν ο δε [ιησους]{.greek-abbr} [λεγει]{.greek-omitted} [ειπεν]{.greek-added} αυτοις ναι ουδεποτε ανεγνωτε οτι εκ στοματος νηπιων και θηλαζοντων [κατηρτισω]{.greek-omitted} [κατηρτησω]{.greek-added} αινον[21:16]{.aside}

[κ]{.greek-supplied}αι καταλιπων αυτους εξηλθεν εξω της πολεως εις βηθανιαν και ηυλισθη εκει[21:17]{.aside}

[π]{.greek-supplied}ρωιας δε επαναγων [ο]{.greek-added} [[ιησους]{.greek-abbr}]{.greek-added} εις την πολιν [επεινασεν]{.greek-omitted} [επεινασε]{.greek-added}[21:18]{.aside}

και ιδων συκην [μιαν]{.greek-omitted} [επι]{.greek-omitted} [της]{.greek-omitted} [οδου]{.greek-omitted} ηλθεν επ αυτην και [ουδεν]{.greek-omitted} [ουχ]{.greek-added} ευρεν εν αυτη ει μη φυλλα μονον και λεγει αυτη μηκετι εκ σου καρπος γενηται εις τον αιωνα και [παραχρημα]{.greek-added} εξηρανθη [παραχρημα]{.greek-omitted} η συκη[21:19]{.aside}

και ιδοντες οι μαθηται εθαυμασαν [λεγοντες]{.greek-omitted} [πως]{.greek-omitted} [παραχρημα]{.greek-omitted} [εξηρανθη]{.greek-omitted} [η]{.greek-omitted} [συκη]{.greek-omitted}[21:20]{.aside}

[α]{.greek-supplied}ποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις [αμην]{.greek-omitted} [λεγω]{.greek-omitted} [υμιν]{.greek-omitted} εαν εχητε πιστιν και μη διακριθητε ου μονον το της συκης [ποιησητε]{.greek-added} [ποιησετε]{.corr} αλλα καν τω ορει τουτω ειπητε αρθητι και [βληθητι]{.greek-omitted} [βλη]{.greek-added} [μεταβηθι]{.greek-added} εις την [θαλασσαν]{.greek-omitted} [θαλλασσαν]{.greek-added} γενησεται[21:21]{.aside}

και [παντα]{.greek-omitted} [παν]{.greek-added} [τα]{.greek-added} οσα [εαν]{.greek-omitted} [αν]{.greek-added} [αιτησητε]{.greek-omitted} [αιτησησθε]{.greek-added} [ληψεσθε]{.greek-added} [εν]{.greek-omitted} [τη]{.greek-omitted} [προσευχη]{.greek-omitted} πιστευοντες [ληψεσθε]{.greek-omitted}[21:22]{.aside}

[κ]{.greek-supplied}αι ελθοντι αυτω εις το ιερον προσηλθον αυτω διδασκοντι οι αρχιερεις και οι πρεσβυτεροι του λαου λεγοντες εν ποια εξουσια ταυτα ποιεις και τις σοι [εδωκεν]{.greek-omitted} [εδωκε]{.greek-added} την εξουσιαν ταυτην[21:23]{.aside}

[αποκριθεις]{.greek-omitted} [ο]{.greek-added} δε [ο]{.greek-omitted} [ιησους]{.greek-omitted} ειπεν αυτοις ερωτησω υμας καγω [ενα]{.greek-added} λογον [ενα]{.greek-omitted} ον εαν ειπητε μοι καγω [ειπω]{.greek-added} υμιν [ερω]{.greek-omitted} εν ποια εξουσια ταυτα ποιω[21:24]{.aside}

το βαπτισμα ιωαννου ποθεν ην εξ [ουρανου]{.greek-abbr} η εξ [ανθρωπων]{.greek-abbr} οι δε διελογιζοντο [παρ]{.greek-omitted} [εαυτοις]{.greek-omitted} λεγοντες εαν ειπωμεν [εξ]{.greek-omitted} [ουρανου]{.greek-omitted} [ερει]{.greek-omitted} [ημιν]{.greek-omitted} [δια]{.greek-omitted} [τι]{.greek-omitted} [ουν]{.greek-omitted} [ουκ]{.greek-omitted} [επιστευσατε]{.greek-omitted} [αυτω]{.greek-omitted}[21:25]{.aside}

[εαν]{.greek-omitted} [δε]{.greek-omitted} [ειπωμεν]{.greek-omitted} εξ [ανθρωπων]{.greek-abbr} φοβουμεθα τον οχλον παντες γαρ [εχουσιν]{.greek-omitted} [ειχον]{.greek-added} τον ιωαννην ως προφητην [εαν]{.greek-added} [δε]{.greek-added} [ειπωμεν]{.greek-added} [εξ]{.greek-added} [[ουρανου]{.greek-abbr}]{.greek-added} [ερει]{.greek-added} [ημιν]{.greek-added} [δια]{.greek-added} [τι]{.greek-added} [ουκ]{.greek-added} [επιστευσατε]{.greek-added} [αυτω]{.greek-added}[21:26]{.aside}

[λεγουσιν]{.greek-added} [αυτω]{.greek-added} [και]{.greek-omitted} [αποκριθεντες]{.greek-omitted} [τω]{.greek-omitted} [ιησου]{.greek-omitted} [ειπον]{.greek-omitted} ουκ οιδαμεν [εφη]{.greek-omitted} [ο]{.greek-added} [δε]{.greek-added} [λεγει]{.greek-added} αυτοις [και]{.greek-omitted} [αυτος]{.greek-omitted} ουδε εγω λεγω υμιν εν ποια εξουσια ταυτα ποιω[21:27]{.aside}

[τ]{.greek-supplied}ι [δε]{.greek-omitted} υμιν δοκει [ανθρωπος]{.greek-abbr} [τις]{.greek-added} [ειχεν]{.greek-omitted} [ειχε]{.greek-added} τεκνα δυο και προσελθων τω πρωτω [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τεκνον υπαγε σημερον εργαζου εν τω αμπελωνι μου[21:28]{.aside}

ο δε αποκριθεις ειπεν ου θελω υστερον δε μεταμεληθεις [απηλθεν]{.greek-omitted} [απηλθε]{.greek-added}[21:29]{.aside}

και προσελθων τω [δευτερω]{.greek-omitted} [ετερω]{.greek-added} ειπεν [ωσαυτως]{.greek-omitted} [ουτως]{.greek-added} ο δε αποκριθεις ειπεν εγω [κυριε]{.greek-abbr} και ουκ απηλθεν[21:30]{.aside}

τις [ουν]{.greek-added} εκ των δυο [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} το θελημα του [πατρος]{.greek-abbr} λεγουσιν αυτω ο πρωτος λεγει αυτοις ο [ιησους]{.greek-abbr} αμην λεγω υμιν οτι οι τελωναι και αι πορναι προαγουσιν υμας εις την βασιλειαν του [θεου]{.greek-abbr}[21:31]{.aside}

[ηλθεν]{.greek-omitted} [ηλθε]{.greek-added} γαρ προς υμας [ο]{.greek-added} ιωαννης εν οδω δικαιοσυνης και ουκ επιστευσατε αυτω [οι]{.greek-omitted} [δε]{.greek-omitted} [τελωναι]{.greek-omitted} [και]{.greek-omitted} [αι]{.greek-omitted} [πορναι]{.greek-omitted} [επιστευσαν]{.greek-omitted} [αυτω]{.greek-omitted} [υμεις]{.greek-omitted} [δε]{.greek-omitted} [ιδοντες]{.greek-omitted} [ου]{.greek-omitted} [μετεμεληθητε]{.greek-omitted} [υστερον]{.greek-omitted} [του]{.greek-omitted} [πιστευσαι]{.greek-omitted} [αυτω]{.greek-omitted}[21:32]{.aside}

[α]{.greek-supplied}λλην παραβολην ακουσατε [ανθρωπος]{.greek-abbr} τις ην οικοδεσποτης οστις εφυτευσεν αμπελωνα και φραγμον αυτω [περιεθηκεν]{.greek-omitted} [περιεθηκε]{.greek-added} και ωρυξεν [εν]{.greek-omitted} [αυτω]{.greek-omitted} [εαυτω]{.greek-added} ληνον και [ωκοδομησεν]{.greek-omitted} [ωκοδομησε]{.greek-added} πυργον και εξεδοτο αυτον γεωργοις και απεδημησεν[21:33]{.aside}

[ο]{.greek-supplied}τε δε [ηγγισεν]{.greek-omitted} [ηγγικεν]{.greek-added} ο καιρος των καρπων [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} τους δουλους αυτου προς τους γεωργους λαβειν τους καρπους αυτου[21:34]{.aside}

[και]{.greek-omitted} [οι]{.greek-added} [δε]{.greek-added} [γεωργοι]{.greek-added} λαβοντες [οι]{.greek-omitted} [γεωργοι]{.greek-omitted} τους δουλους [αυτου]{.greek-omitted} ον μεν [εδειραν]{.greek-omitted} [εδηραν]{.greek-added} ον δε απεκτειναν ον δε ελιθοβολησαν[21:35]{.aside}

παλιν απεστειλεν αλλους δουλους πλειονας των πρωτων και εποιησαν αυτοις ωσαυτως[21:36]{.aside}

υστερον δε [απεστειλεν]{.greek-omitted} [απεστειλε]{.greek-added} [προς]{.greek-omitted} [αυτους]{.greek-omitted} τον υιον αυτου λεγων εντραπησονται τον υιον μου[21:37]{.aside}

οι δε γεωργοι ιδοντες τον υιον [αυτου]{.greek-added} ειπον εν εαυτοις ουτος εστιν ο κληρονομος δευτε αποκτεινωμεν αυτον και κατασχωμεν την κληρονομιαν αυτου[21:38]{.aside}

και λαβοντες αυτον [εξεβαλον]{.greek-omitted} [εξεβαλαν]{.greek-added} εξω του αμπελωνος και απεκτειναν[21:39]{.aside}

[ο]{.greek-supplied}ταν ουν ελθη ο [κυριος]{.greek-abbr} του αμπελωνος τι ποιησει τοις γεωργοις εκεινοις[21:40]{.aside}

λεγουσιν αυτω κακους κακως απολεσει αυτους και τον αμπελωνα [εκδωσεται]{.greek-omitted} [εκδοσεται]{.greek-added} αλλοις γεωργοις οιτινες [αποδωσουσιν]{.greek-omitted} [αποδωσουσι]{.greek-added} [αυτω]{.greek-omitted} τους καρπους εν [τοις]{.greek-omitted} [καιροις]{.greek-omitted} [τω]{.greek-added} [καιρω]{.greek-added} αυτων[21:41]{.aside}

[λ]{.greek-supplied}εγει αυτοις ο [ιησους]{.greek-abbr} [ουδεποτε]{.greek-omitted} [ουκ]{.greek-added} ανεγνωτε [εν]{.greek-omitted} [ταις]{.greek-omitted} [γραφαις]{.greek-omitted} λιθον ον απεδοκιμασαν οι οικοδομουντες ουτος εγενηθη εις κεφαλην [γωνιας]{.greek-omitted} [γονιας]{.greek-added} παρα [κυριου]{.greek-abbr} εγενετο αυτη και [εστιν]{.greek-omitted} [εστι]{.greek-added} θαυμαστη εν οφθαλμοις ημων[21:42]{.aside}

δια τουτο λεγω υμιν [οτι]{.greek-omitted} αρθησεται [αφ]{.greek-omitted} [υμων]{.greek-omitted} η βασιλεια του [θεου]{.greek-abbr} και δοθησεται [εθνει]{.greek-omitted} [ποιουντι]{.greek-omitted} [τους]{.greek-omitted} [εθνη]{.greek-added} [αποδιδοντα]{.greek-added} [τον]{.greek-added} [καρπους]{.greek-omitted} [καρπον]{.greek-added} [αυτης]{.greek-omitted} [αυτου]{.greek-added}[21:43]{.aside}

και ο πεσων επι τον λιθον τουτον συνθλασθησεται εφ ον [δε]{.greek-added} [πεσει]{.greek-added} [δ]{.greek-omitted} [αν]{.greek-omitted} [πεση]{.greek-omitted} λικμησει αυτον[21:44]{.aside}

[κ]{.greek-supplied}αι ακουσαντες οι αρχιερεις και οι φαρισαιοι τας παραβολας αυτου εγνωσαν οτι περι αυτων λεγει[21:45]{.aside}

και ζητουντες αυτον κρατησαι εφοβηθησαν [τους]{.greek-omitted} [οχλους]{.greek-omitted} [τον]{.greek-added} [οχλον]{.greek-added} επειδη ως προφητην αυτον ειχον[21:46]{.aside}

### Chapter 22

[κ]{.greek-supplied}αι αποκριθεις ο [ιησους]{.greek-abbr} [παλιν]{.greek-omitted} ειπεν αυτοις [λεγων]{.greek-added} εν παραβολαις [λεγων]{.greek-omitted}[22:1]{.aside}

ωμοιωθη η βασιλεια των [ουρανων]{.greek-abbr} [ανθρωπω]{.greek-abbr} βασιλει οστις [εποιησεν]{.greek-omitted} [εποιησε]{.greek-added} γαμους τω υιω [αυτου]{.greek-omitted} [αυ]{.greek-added}[22:2]{.aside}

[τ]{.greek-supplied}οτε λεγει τοις δουλοις αυτου ο μεν γαμος ετοιμος [εστιν]{.greek-omitted} [εστι]{.greek-added} οι δε κεκλημενοι ουκ ησαν αξιοι[22:8]{.aside}

[πορευεσθε]{.greek-omitted} [πορευεσθαι]{.greek-added} [ουν]{.greek-omitted} [δε]{.greek-added} [μαλλον]{.greek-added} επι τας διεξοδους των οδων και οσους αν ευρητε καλεσατε εις τους γαμους[22:9]{.aside}

και εξελθοντες οι δουλοι εκεινοι εις τας οδους [και]{.greek-added} [πλατειας]{.greek-added} συνηγαγον παντας οσους ευρον πονηρους τε και αγαθους και επλησθη ο γαμος ανακειμενων[22:10]{.aside}

[ε]{.greek-supplied}ισελθων δε ο βασιλευς θεασασθαι τους ανακειμενους ειδεν εκει [ανθρωπον]{.greek-abbr} ουκ ενδεδυμενον ενδυμα γαμου[22:11]{.aside}

[και]{.greek-omitted} λεγει αυτω εταιρε πως εισηλθες ωδε μη [εχων]{.greek-omitted} [εχον]{.greek-added} ενδυμα γαμου ο δε [εφιμωθη]{.greek-omitted} [εφημωθη]{.greek-added}[22:12]{.aside}

τοτε ειπεν ο βασιλευς τοις διακονοις δησαντες αυτου [χειρας]{.greek-added} [και]{.greek-added} ποδας [και]{.greek-omitted} [χειρας]{.greek-omitted} αρατε αυτον και [εκβαλετε]{.greek-omitted} [εμβαλατε]{.greek-added} εις το σκοτος το εξωτερον εκει εσται ο κλαυθμος και ο βρυγμος των οδοντων[22:13]{.aside}

πολλοι γαρ [εισιν]{.greek-omitted} [εισι]{.greek-added} κλητοι ολιγοι δε εκλεκτοι[22:14]{.aside}

[τ]{.greek-supplied}οτε πορευθεντες οι φαρισαιοι συμβουλιον [ελαβον]{.greek-omitted} [εποιησαν]{.greek-added} οπως αυτον παγιδευσωσιν εν λογω[22:15]{.aside}

και αποστελλουσιν αυτω τους μαθητας αυτων μετα των ηρωδιανων λεγοντες [αυτω]{.greek-added} [δ]{.greek-supplied}ιδασκαλε οιδαμεν οτι αληθης ει και την οδον του [θεου]{.greek-abbr} εν αληθεια διδασκεις και ου [μελει]{.greek-omitted} [μελλει]{.greek-added} σοι περι ουδενος ου γαρ βλεπεις εις προσωπον [ανθρωπων]{.greek-omitted} [[ανθρωπου]{.greek-abbr}]{.greek-added}[22:16]{.aside}

ειπε ουν ημιν τι σοι δοκει [εξεστιν]{.greek-omitted} [εξεστι]{.greek-added} δουναι κηνσον καισαρι η ου[22:17]{.aside}

γνους δε ο [ιησους]{.greek-abbr} την πονηριαν αυτων [ειπεν]{.greek-omitted} [ειπε]{.greek-added} τι με πειραζετε υποκριται[22:18]{.aside}

επιδειξατε μοι το νομισμα του κηνσου οι δε [προσηνεγκαν]{.greek-omitted} [προσεδωκαν]{.greek-added} αυτω [δηναριον]{.greek-omitted} [δυναριον]{.greek-added}[22:19]{.aside}

και λεγει αυτοις τινος η εικων αυτη και η επιγραφη[22:20]{.aside}

λεγουσιν αυτω καισαρος [τοτε]{.greek-omitted} [ο]{.greek-added} [δε]{.greek-added} λεγει αυτοις αποδοτε ουν τα καισαρος καισαρι και τα του [θεου]{.greek-abbr} τω [θεω]{.greek-abbr}[22:21]{.aside}

και ακουσαντες εθαυμασαν και αφεντες αυτον απηλθον[22:22]{.aside}

[ε]{.greek-supplied}ν εκεινη τη ημερα προσηλθον αυτω σαδδουκαιοι [οι]{.greek-omitted} λεγοντες μη ειναι αναστασιν και [επηρωτησαν]{.greek-omitted} [επερωτησαν]{.greek-added} αυτον[22:23]{.aside}

λεγοντες διδασκαλε μωσης ειπεν εαν τις αποθανη μη [εχων]{.greek-omitted} [εχον]{.greek-added} τεκνα [επιγαμβρευσει]{.greek-omitted} [επιγαμβρευση]{.greek-added} ο αδελφος αυτου την γυναικα αυτου [και]{.greek-omitted} [αναστησει]{.greek-omitted} [σπερμα]{.greek-omitted} [τω]{.greek-omitted} [αδελφω]{.greek-omitted} [αυτου]{.greek-omitted}[22:24]{.aside}

ησαν δε παρ ημιν επτα αδελφοι και ο πρωτος γαμησας [αυτην]{.greek-added} ετελευτησεν και μη εχων σπερμα [αφηκεν]{.greek-omitted} [αφηκε]{.greek-added} την γυναικα αυτου τω αδελφω αυτου[22:25]{.aside}

ομοιως και ο δευτερος και ο τριτος εως των επτα[22:26]{.aside}

υστερον δε παντων [απεθανεν]{.greek-omitted} [απεθανε]{.greek-added} και η γυνη[22:27]{.aside}

εν τη ουν αναστασει τινος των επτα εσται γυνη παντες γαρ εσχον αυτην[22:28]{.aside}

[α]{.greek-supplied}ποκριθεις δε ο [ιησους]{.greek-abbr} ειπεν αυτοις πλανασθε μη ειδοτες τας γραφας μηδε την δυναμιν του [θεου]{.greek-abbr}[22:29]{.aside}

εν γαρ τη αναστασει ουτε γαμουσιν ουτε [εκγαμιζονται]{.greek-omitted} [γαμιζονται]{.greek-added} αλλ ως αγγελοι [του]{.greek-omitted} [θεου]{.greek-abbr} εν [ουρανω]{.greek-abbr} [εισιν]{.greek-omitted} [εισι]{.greek-added}[22:30]{.aside}

περι δε της αναστασεως των νεκρων ουκ ανεγνωτε το ρηθεν [υμιν]{.greek-omitted} υπο του [θεου]{.greek-abbr} λεγοντος[22:31]{.aside}

εγω ειμι ο [θεος]{.greek-abbr} αβρααμ και ο [θεος]{.greek-abbr} ισαακ και ο [θεος]{.greek-abbr} ιακωβ ουκ εστιν ο [θεος]{.greek-abbr} [θεος]{.greek-abbr} νεκρων αλλα ζωντων[22:32]{.aside}

και ακουσαντες οι οχλοι εξεπλησσοντο επι τη διδαχη αυτου[22:33]{.aside}

[ο]{.greek-supplied}ι δε φαρισαιοι ακουσαντες οτι [εφιμωσεν]{.greek-omitted} [εφημωσε]{.greek-added} τους σαδδουκαιους συνηχθησαν επι το αυτο[22:34]{.aside}

και επηρωτησεν [εις]{.greek-omitted} [αυτον]{.greek-added} [τις]{.greek-added} [νομικος]{.greek-added} εξ αυτων [νομικος]{.greek-omitted} πειραζων αυτον και λεγων[22:35]{.aside}

διδασκαλε ποια εντολη μεγαλη εν τω νομω[22:36]{.aside}

ο δε [ιησους]{.greek-abbr} εφη αυτω αγαπησεις [κυριον]{.greek-abbr} τον [θεον]{.greek-abbr} σου εν ολη [τη]{.greek-added} καρδια σου και εν ολη [τη]{.greek-added} ψυχη σου και εν ολη τη διανοια σου[22:37]{.aside}

αυτη εστιν [η]{.greek-added} πρωτη και μεγαλη εντολη[22:38]{.aside}

δευτερα δε ομοια [αυτη]{.greek-omitted} [αὕτη]{.greek-added} αγαπησεις τον πλησιον σου ως σεαυτον[22:39]{.aside}

εν ταυταις ταις δυσιν εντολαις ολος ο νομος και οι προφηται [κρεμανται]{.greek-omitted} [κρεματαις]{.greek-added}[22:40]{.aside}

[σ]{.greek-supplied}υνηγμενων δε των φαρισαιων επηρωτησεν αυτους ο [ιησους]{.greek-abbr}[22:41]{.aside}

λεγων τι υμιν δοκει [περι]{.greek-omitted} [πεπερι]{.greek-added} του [χριστου]{.greek-abbr} τινος υιος [εστιν]{.greek-omitted} [εστι]{.greek-added} λεγουσιν αυτω [του]{.greek-omitted} [δαυιδ]{.greek-abbr}[22:42]{.aside}

λεγει αυτοις πως ουν [δαυιδ]{.greek-abbr} εν [πνευματι]{.greek-abbr} [κυριον]{.greek-abbr} αυτον καλει [λεγων]{.greek-omitted}[22:43]{.aside}

ειπεν ο [κυριος]{.greek-abbr} τω [κυριω]{.greek-abbr} μου καθου εκ δεξιων μου εως αν θω τους εχθρους σου υποποδιον των ποδων σου[22:44]{.aside}

ει ουν [δαυιδ]{.greek-abbr} [[κυριον]{.greek-abbr}]{.greek-added} [αυτον]{.greek-added} καλει [αυτον]{.greek-omitted} [κυριον]{.greek-omitted} πως υιος αυτου [εστιν]{.greek-omitted} [εστι]{.greek-added}[22:45]{.aside}

και ουδεις [εδυνατο]{.greek-omitted} [ηδυνατο]{.greek-added} [αποκριθηναι]{.greek-added} αυτω [αποκριθηναι]{.greek-omitted} λογον ουδε [ετολμησεν]{.greek-omitted} [ετολμησε]{.greek-added} τις απ εκεινης της ημερας επερωτησαι αυτον ουκετι[22:46]{.aside}

### Chapter 23

[τ]{.greek-supplied}οτε ο [ιησους]{.greek-abbr} ελαλησεν [αυτοις]{.greek-added} τοις οχλοις και τοις μαθηταις αυτο[υ]{.unclear}[23:1]{.aside}

λεγων επι της μωσεως καθεδρας [εκαθισαν]{.greek-omitted} [εκαθησαν]{.greek-added} οι γραμματεις και οι φαρισαιοι[23:2]{.aside}

παντα ουν οσα εαν ειπωσιν υμιν [τηρειν]{.greek-omitted} [ποιητε]{.greek-added} [και]{.greek-added} τηρειτε [και]{.greek-omitted} [ποιειτε]{.greek-omitted} κατα δε τα εργα αυτων μη [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} [λεγουσιν]{.greek-omitted} [λεγουσι]{.greek-added} γαρ και ου [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added}[23:3]{.aside}

[δεσμευουσιν]{.greek-omitted} [[δ]{.greek-supplied}εσμευουσι]{.greek-added} γαρ φορτια βαρεα [και]{.greek-omitted} [δυσβαστακτα]{.greek-omitted} και επιτιθεασιν επι τους ωμους των [ανθρωπων]{.greek-abbr} τω δε δακτυλω [αυτων]{.greek-omitted} ου [θελουσιν]{.greek-omitted} [θελουσι]{.greek-added} κινησαι αυτα[23:4]{.aside}

παντα δε τα εργα αυτων [ποιουσιν]{.greek-omitted} [ποιουσι]{.greek-added} προς το θεαθηναι τοις [ανθρωποις]{.greek-abbr} [πλατυνουσιν]{.greek-omitted} [πλατυνουσι]{.greek-added} δε τα φυλακτηρια αυτων και [μεγαλυνουσιν]{.greek-omitted} [μεγαλυνουσι]{.greek-added} τα κρασπεδα των ιματιων αυτων[23:5]{.aside}

[φιλουσιν]{.greek-omitted} [[φ]{.greek-supplied}ιλουσι]{.greek-added} [τε]{.greek-omitted} [δε]{.greek-added} την [πρωτοκλισιαν]{.greek-omitted} [πρωτοκλησιαν]{.greek-added} εν τοις δειπνοις και τας [πρωτοκαθεδριας]{.greek-omitted} [πρωτοκα]{.greek-added} [θεδριας]{.greek-added} εν ταις συναγωγαις[23:6]{.aside}

και τους ασπασμους εν ταις αγοραις και καλεισθαι υπο των [ανθρωπων]{.greek-abbr} [ραββι]{.greek-omitted} [ραμβι]{.greek-added} [ραββι]{.greek-omitted} [ραμβι]{.greek-added}[23:7]{.aside}

[υ]{.greek-supplied}μεις δε [[―]{.gap}η]{.greek-added} [μη]{.corr} κληθητε [ραββι]{.greek-omitted} [ραμβι]{.greek-added} εις γαρ εστιν [ο]{.greek-added} [διδασκαλος]{.greek-added} υμων [ο]{.greek-omitted} [καθηγητης]{.greek-omitted} [ο]{.greek-omitted} [χριστος]{.greek-abbr} παντες δε υμεις αδελφοι εστε[23:8]{.aside}

και [πατερα]{.greek-abbr} μη [καλεσητε]{.greek-omitted} [επικαλεσητε]{.greek-added} [υμων]{.greek-omitted} επι της γης εις γαρ [εστιν]{.greek-omitted} [εστι]{.greek-added} [ο]{.greek-omitted} [πατηρ]{.greek-abbr} υμων ο εν τοις ουρανοις[23:9]{.aside}

μηδε κληθητε [καθηγητης]{.greek-added} [καθηγηται]{.corr} εις γαρ [υμων]{.greek-omitted} εστιν ο καθηγητης [ο]{.greek-omitted} [υμων]{.greek-added} [χριστος]{.greek-abbr}[23:10]{.aside}

ο δε μειζων υμων [εσται]{.greek-omitted} [εστω]{.greek-added} υμων διακονος[23:11]{.aside}

οστις δε υψωσει εαυτον ταπεινωθησεται [και]{.greek-omitted} [οστις]{.greek-omitted} [ο]{.greek-added} [δε]{.greek-added} [ταπεινωσει]{.greek-omitted} [ταπεινων]{.greek-added} εαυτον υψωθησεται[23:12]{.aside}

[ο]{.greek-supplied}υαι [δε]{.greek-omitted} υμιν γραμματεις [και]{.greek-omitted} φαρισαιοι υποκριται οτι [κατεσθιετε]{.greek-omitted} [τας]{.greek-omitted} [οικιας]{.greek-omitted} [κλειετε]{.greek-added} [την]{.greek-added} [βασιλειαν]{.greek-added} των [χηρων]{.greek-omitted} [και]{.greek-omitted} [προφασει]{.greek-omitted} [μακρα]{.greek-omitted} [προσευχομενοι]{.greek-omitted} [δια]{.greek-omitted} [τουτο]{.greek-omitted} [ληψεσθε]{.greek-omitted} [περισσοτερον]{.greek-omitted} [κριμα]{.greek-omitted} [[ουρανων]{.greek-abbr}]{.greek-added} [εμπροσθεν]{.greek-added} [των]{.greek-added} [[ανθρωπων]{.greek-abbr}]{.greek-added} [υμεις]{.greek-added} [δε]{.greek-added} [[γαρ]{.corr}]{.greek-added} [ουκ]{.greek-added} [εισερχεσθαι]{.greek-added} [ουδε]{.greek-added} [τους]{.greek-added} [εισερχομενους]{.greek-added} [αφιετε]{.greek-added} [ελθειν]{.greek-added}[23:13]{.aside}

[ο]{.greek-supplied}υαι υμιν γραμματεις [και]{.greek-omitted} φαρισαιοι υποκριται οτι [κλειετε]{.greek-omitted} [την]{.greek-omitted} [βασιλειαν]{.greek-omitted} [κατεσθιετε]{.greek-added} [τας]{.greek-added} [οικιας]{.greek-added} των [χηρων]{.greek-added} [και]{.greek-added} [προφασει]{.greek-added} [μακρα]{.greek-added} [προσευ]{.greek-added} [χομενοι]{.greek-added} [δια]{.greek-added} [τουτο]{.greek-added} [ληψεσθε]{.greek-added} [περισσοτερον]{.greek-added} [κριμα]{.greek-added} [ουρανων]{.greek-omitted} [εμπροσθεν]{.greek-omitted} [των]{.greek-omitted} [ανθρωπων]{.greek-omitted} [υμεις]{.greek-omitted} [γαρ]{.greek-omitted} [ουκ]{.greek-omitted} [εισερχεσθε]{.greek-omitted} [ουδε]{.greek-omitted} [τους]{.greek-omitted} [εισερχομενους]{.greek-omitted} [αφιετε]{.greek-omitted} [εισελθειν]{.greek-omitted}[23:14]{.aside}

[ο]{.greek-supplied}υαι υμιν γραμματεις [και]{.greek-omitted} φαρισαιοι υποκριται οτι περιαγετε την θαλασσαν και την ξηραν ποιησαι ενα προσηλυτον και οταν γενηται [ποιειτε]{.greek-omitted} [ποιητε]{.greek-added} αυτον υιον γεεννης [διπλοτερον]{.greek-omitted} [διπλωτερον]{.greek-added} υμων[23:15]{.aside}

[ο]{.greek-supplied}υαι υμιν οδηγοι [τυφλοι]{.greek-omitted} [τυφλων]{.greek-added} οι λεγοντες ος αν [ομοση]{.greek-omitted} [ομωση]{.greek-added} [εν]{.greek-omitted} [τω]{.greek-omitted} [ναω]{.greek-omitted} [ουδεν]{.greek-omitted} [εστιν]{.greek-omitted} [ος]{.greek-omitted} [δ]{.greek-omitted} [αν]{.greek-omitted} [ομοση]{.greek-omitted} εν τω χρυσω του ναου οφειλει [ος]{.greek-added} [δ]{.greek-added} [αν]{.greek-added} [ομωση]{.greek-added} [εν]{.greek-added} [τω]{.greek-added} [ναω]{.greek-added} [ουδεν]{.greek-added} [εστι]{.greek-added}[23:16]{.aside}

μωροι και τυφλοι τις [γαρ]{.greek-omitted} μειζων εστιν ο χρυσος η ο ναος ο αγιαζων τον χρυσον[23:17]{.aside}

και ος [δ]{.greek-added} [εαν]{.greek-omitted} [αν]{.greek-added} [ομοση]{.greek-omitted} [ομωση]{.greek-added} εν τω θυσιαστηριω ουδεν εστιν ος δ αν [ομοση]{.greek-omitted} [ομωση]{.greek-added} εν τω δωρω [τω]{.greek-omitted} [το]{.greek-added} ε[π]{.unclear}ανω αυτου [οφειλει]{.greek-omitted} [οφειλη]{.greek-added}[23:18]{.aside}

μω[ρ]{.unclear}οι και τυφλοι [τι]{.greek-omitted} [τις]{.greek-added} [γαρ]{.greek-omitted} [ουν]{.greek-added} [μειζον]{.greek-omitted} [μειζων]{.greek-added} [εστιν]{.greek-added} το δωρον η το θυσιαστηριον το αγιαζον το δωρον[23:19]{.aside}

ο ουν [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω θυσιαστηριω ομνυει εν αυτω και εν [πασιν]{.greek-omitted} [πασι]{.greek-added} τοις επανω αυτου[23:20]{.aside}

και ο [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω ναω ομνυει εν αυτω και εν τω [κατοικησαντι]{.greek-omitted} [κατοικουντι]{.greek-added} [αυτον]{.greek-omitted} [εν]{.greek-added} [αυτω]{.greek-added}[23:21]{.aside}

και ο [ομοσας]{.greek-omitted} [ομωσας]{.greek-added} εν τω [ουρανω]{.greek-abbr} ομνυει εν τω θρονω του [θεου]{.greek-abbr} και εν τω καθημενω επανω αυτου[23:22]{.aside}

[ο]{.greek-supplied}υαι υμιν γραμματεις [και]{.greek-omitted} φαρισαιοι υποκριται οτι αποδεκατουτε το [ηδυοσμον]{.greek-omitted} [ιδιοσμον]{.greek-added} και το [ανηθον]{.greek-omitted} [ανιθον]{.greek-added} και το κυμινον και αφηκατε τα [βαρυτερα]{.greek-omitted} [βαρεα]{.greek-added} του νομου την κρισιν και [τον]{.greek-omitted} [το]{.greek-added} ελεον και την πιστιν [ταυτα]{.greek-omitted} [ταυτ]{.greek-added} εδει ποιησαι κακεινα μη [αφιεναι]{.greek-omitted} [αφηναι]{.greek-added}[23:23]{.aside}

οδηγοι τυφλοι οι [διυλιζοντες]{.greek-omitted} [διηλιζοντες]{.greek-added} τον κωνωπα [και]{.greek-added} την [δε]{.greek-omitted} καμηλον καταπινοντες[23:24]{.aside}

